### ISSUE TITLE
Bug: Search all on cutoff tab is searching missing movies, not cutoff movies

### ISSUE THREAD

**Issue by zductiv** [Radarr/Radarr#1000]
**Description:**

The search all button on the cutoff tab isn't searching cutoff movies, it's searching missing.

**Radarr Version:**
0.2.0.434

**Logs:**
I have more than 1000 cutoff movies unmet.

log: 
![image](https://cloud.githubusercontent.com/assets/8939440/23576622/77f510a4-00e5-11e7-88e0-d8abd7f18b28.png)

After search.

**Comment by onedr0p** [comment]
Fixed in next release, let me know how it goes!
