### ISSUE TITLE
Make Manual Import Great - Rename, Move and Merge for Existing but Missing

### ISSUE THREAD

**Issue by ylnest2018** [Radarr/Radarr#10023]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

No a problem although makes it difficult, whenever I use the manual import there is no option to merge for existing added movies that have missing media, eg added through a list, couldn't be sourced, but then on an old HDD and when trying to import in bulk 

### Describe the solution you'd like

I would love the ability to have some more options on the import
Rename on Import?
Move to Root Folder?

and also the ability for the manual import to detect existing movies, but those which have missing content, allow the manual import to progress and not grey out the icon.

### Describe alternatives you've considered

theres no option but to delete the existing movie, then to let the manual import detect it and re-add, then after a bulk add, i have to filter those movies imported by path (as its different to my root which is used by plex) and then do a bulk root folder change, rename etc.

### Anything else?

love your work!

**Comment by bakerboy448** [comment]
Manual Import from the Movie Index not the Movie Details page is the same as Sonarr's Wanted => Manual Import that imports from anywhere
