### ISSUE TITLE
Release group name is captured incorrectly after import

### ISSUE THREAD

**Issue by Xiphan** [Radarr/Radarr#10035]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Downloading a movie whose release group is CyTSuNee results in the release group being saved as yTS:

![image](https://github.com/Radarr/Radarr/assets/4989354/67761386-b0d7-4631-9802-f516bc78c7be)

![image](https://github.com/Radarr/Radarr/assets/4989354/6024c033-6dbc-4adb-ac45-9d295641f0b5)

### Expected Behavior

Release group should be detected as CyTSuNee.

### Steps To Reproduce

1. Parse or download a release by CyTSuNee.
2. It will parse or import the release group as yTS.

### Environment

```markdown
- OS: Windows
- Radarr: 5.6.0.8846
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Firefox
- Database: Sqlite 3.36.0
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

[radarr.debug.txt](https://github.com/Radarr/Radarr/files/15379317/radarr.debug.txt)
[radarr.trace.txt](https://github.com/Radarr/Radarr/files/15379318/radarr.trace.txt)

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
Likely hitting the exact exception group match regex
https://github.com/Radarr/Radarr/blob/638f92495cea757ad07bed6df9819f0381c9abfc/src/NzbDrone.Core/Parser/Parser.cs#L160

**Comment by Xiphan** [comment]
This issue appears to have been resolved by a recent update.

**Comment by bakerboy448** [comment]
Likely was fixed with https://github.com/Radarr/Radarr/commit/a5b48153a6fb22b5a2ee6e51df8f8a9265414152 and the \b addition
