### ISSUE TITLE
Reasons: [Permanent] Unknown Movie (bug grabber film with specific condition/specs)

### ISSUE THREAD

**Issue by vincenzogianfelice** [Radarr/Radarr#10036]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

These are other tests I did. Even though it is indexed in the trackers (I also reset the Radarr settings, installed prowlarr instead of Jackett) I still get all this. It is not possible that despite having set precise settings which among other things are also present as you can see from the screen (the film is there and also in Italian!), Radarr continues to do its own thing. I do not know what to do. Indeed, by setting the profile ONLY in Italian I don't understand why you download a 720p version when there is (as shown in the screen) a 1080p version with also TrueHD!! Crazy, I've been trying for days but nothing. I think it's a bug at this point

### Expected Behavior

Grabber this movie: ```American.history.X.1999.1080p.REMUX.ENG.ITA.LATINO.Dolby.TrueHD.DDP5.1.MKV-BEN.THE.MEN```

### Environment

```markdown
- Radarr: 5.6.0.8846
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

[radarr.debug.log.txt](https://github.com/Radarr/Radarr/files/15390273/radarr.debug.log.txt)

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by vincenzogianfelice** [comment]
I already did, but they weren't helpful at all. We probably won't even see the message!! This could be a serious problem as it doesn't capture movies properly!

**Comment by bakerboy448** [comment]
For year questions, that's on the FAQ https://wiki.servarr.com/radarr/faq#how-does-radarr-determine-the-year-of-a-movie

As previously mentioned, please visit discord for support questions.

**Comment by bakerboy448** [comment]
Please use [Discord](https://radarr.video/discord) for support/questions.

Further comments will be considered spam and result in negative consequences.

**Comment by vincenzogianfelice** [comment]
undoubtedly, but can't this be considered a problem?  given that many torrents sometimes have the release date based on the country, is it not possible to insert an option in radarr where the date of a film title is ignored film?
