### ISSUE TITLE
Imported movies incorrectly identified quality

### ISSUE THREAD

**Issue by janipewter** [Radarr/Radarr#1004]
**Description:**

Bulk imported 500 movies into Radarr. About 495 of them are 1080p BluRay rips (the other 5 being DVD rips) but Radarr has misidentified every single one of the BluRay rips as HDTV 1080p. I can see it is possible to manually edit it to BluRay 1080p but this will take forever to do with 500 movies.

Is it possible to add a button to relabel them in bulk?

Thanks

**Radarr Version:**

Version
0.2.0.375
Mono Version
4.8.0 (Stable 4.8.0.495/e4a3cf3 Wed Feb 22 18:30:58 UTC 2017)

**Logs:**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by onedr0p** [comment]
This is a duplicate issue, we are aware hdtv is not the best default.
