### ISSUE TITLE
Bulk Import - Allow changing quality per movie

### ISSUE THREAD

**Issue by onedr0p** [Radarr/Radarr#1005]

**Comment by galli-leo** [comment]
I don't think it's a high priority issue, since it will work correctly if you name your movies the right way. I also think Bluray is a good enough default.

**Comment by stevenolsen** [comment]
@galli-leo The issue I find is most bulk imports have already renamed files (e.g. from Couchpotato). Bluray is a good enough default but resolution has never worked for me. It says it does in the options but it never has. Even in Sonarr 1080 videos are imported as HDTV-720p.

**Comment by galli-leo** [comment]
@stevenolsen Then you don't have libmediainfo installed on your system.

**Comment by spencercharest** [comment]
I'm having trouble with the file quality when bulk importing. I have tried setting the filename and folder name to end with combinations of [DVD], [DVD-572p], [DVD-SD] and nothing seems to be working. Many files still register as 720p or 1080p. I am using Radarr on MacOS Sierra. How should files be named to be initially imported as DVD quality during a bulk import? Do I need to edit the actual metadata and not just the file name? The reason I'd like to bulk import as DVD quality is so that all movies will be registered as "cutoff unmet" and can be downloaded again.

**Comment by galli-leo** [comment]
@spencercharest Currently when importing only HDTV, WEB-DL and Bluray are considered, since I forgot about DVD when implementing that :/. Try disabling Analyse video files in Settings -> Media Management -> File Management.

**Comment by spencercharest** [comment]
So you're saying I could end file names with [720p-HDTV] and they would import as such? Then if I set cutoff at 720 BluRay movies would all be "wanted" under cutoff unmet? Thanks a ton for your quick responses by the way.  I just realized you answered both of my questions in two separate threads. I appreciate the help!

**Comment by galli-leo** [comment]
@spencercharest If you name it as 720p-HDTV and the file is 720p resolution it will import as such. However, if the movie was 1080p resolution, it would be imported as 1080p-HDTV.

Regarding your second question. Yes all movies that are lower than 720-Bluray will be considered as cutoff unmet.

**Comment by spencercharest** [comment]
Awesome! I should be able to get everything done with this info. Thanks again!

**Comment by simonwestenholz** [comment]
I'd just like to add that I'd love to have Bluray as the default assumption for imports. I have a rather large library where the naming scheme is less than ideal, and a lot of the movies are just named <movietitle> (<movieyear>).<ext>, or similar. Is it a large undertaking to either have it as a user settable option, or to change the default from HDTV to bluray?

**Comment by galli-leo** [comment]
The default is Bluray. However, it will also look at your size profiles. So if you have small bluray files, they might not get tagged as such. Also the UI does not do these calculations (default there is hdtv). So once you import you should get the correct tags.

**Comment by simonwestenholz** [comment]
What you describe doesn't match my experience. The files both identify and import as HDTV-1080p regardless of my size settings during bulk import. I have tried with 'Analyse Files' enabled and disabled, but it makes no difference. What am I missing?

**Comment by galli-leo** [comment]
Do you have libmediainfo installed?

**Comment by simonwestenholz** [comment]
Good question. I am running Radarr on a Synology DS1815+. Would I have to manually install libmediainfo?

**Comment by galli-leo** [comment]
Probably from what I have gathered.

**Comment by dmwyatt** [comment]
@galli-leo Are you sure it looks at the size profiles?

I just set my HDTV-1080p profile to a a max of a few hundred MB, went to do a bulk import, and all my 8-12GB movies without any source information in the filename still were set to import as 1080p.

I double-checked that I saved the size profiles so I don't think this is user error.
