### ISSUE TITLE
Movies added via "Movies & Collection" from Import Lists are wiped when Clean Library = Remove Movies not in List

### ISSUE THREAD

**Issue by imran0** [Radarr/Radarr#10050]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I have an import list from Trakt Popular that I've set to grab both Movie & Collection. In my Clean Library Level setting, I've set this to Remove Movie and Delete folder.

When I do this and let the scheduled tasks run, it will import the film and collections when its new but on the next run all the films from the collection are purged.

In my example I can see that The Fast and Furious is in the popular list, so it should download the whole collection (which it does do) but as soon as the import / delete tasks run again, all the added films via collection are purged.

Looking at the logs, I can see that when the film detects Fast and Furious again, it already sees it in the DB, so it doesn't do the action of adding the film and the collection again, which is why the collection films simply disappear instead of being readdded each time the importer runs.

### Expected Behavior

The Clean Library Level when set to Remove Movies and Folders, should be able to include movies added as part of a collection and exclude these from the deletion task.

### Steps To Reproduce

1. Add Trakt Popular List (include Movies & Collection)
2. Set Clean Library Status to Remove Movie and Files
3. Let the schedule tasks run for import list and clean library.
4. Notice that films added via collection have no been removed.

### Environment

```markdown
- OS: Synology DSM6
- Radarr: 5.6.0.8846
- Docker Install: Yes
- Using Reverse Proxy: No
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

This is the moment a film from a collection was purged, I dont have when the film was originally added.

2024-05-30 13:31:12.1|Info|ImportListSyncService|[Fast X (2023)][tt5433140, 385687] was in your library, but not found in your lists --> Removing from library and deleting files
2024-05-30 13:31:12.1|Debug|PlexServer|Performing library update for 1 movies
2024-05-30 13:31:12.1|Debug|PlexServerService|Sending Update Request to Plex Server
2024-05-30 13:31:12.1|Debug|PlexServerService|Getting sections from Plex host: 192.168.1.100
2024-05-30 13:31:12.1|Debug|PlexServerProxy|Url: http://192.168.1.100:32402/library/sections?X-Plex-Client-Identifier=(removed)&X-Plex-Product=Radarr&X-Plex-Platform=Windows&X-Plex-Platform-Version=7&X-Plex-Device-Name=Radarr&X-Plex-Version=5.6.0.8846&X-Plex-Token=(removed)
2024-05-30 13:31:12.2|Debug|PlexServerService|Updating matching section location, /volume2/Scratch/Remote/plex/Movies
2024-05-30 13:31:12.2|Debug|PlexServerService|Updating section location, /volume2/Scratch/Remote/plex/Movies

I can see in a subsequent run it detects the first film in the import list, but doesnt do anything because it already exists.
3772: 2024-05-30 13:31:22.4|Debug|ImportListSyncService|9799 [The Fast and the Furious] Rejected, Movie Exists in DB

I know these are two films, but they both belong to the same collection. Likely they both appeared in the import list.

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
This is functioning as designed and expected. Movies in radarr not on a list will be removed as you configured it.
If you want collection movies to stay you need to ensure they are on a list.

**Comment by imran0** [comment]
@bakerboy448 Surely if the import job allows for the Movie _and Collection_ to be imported, then the Clean Level setting should have an option to exclude films added from collection?
It might be working as intended but it doesn't make sense to have automatic add movies from collection if the clean level will only purge it later.

I have included the debug logs which show the exact point in the execution where it's decided to remove the files and the reason for why it was deleted.

**Comment by bakerboy448** [comment]
Regardless, not a bug and **working as designed**. Please use discord for support issues.  Bug reports are not feature requests.
debug logs are not trace logs.

**Comment by GodBleak** [comment]
@bakerboy448 If this is working _as designed_, then what's the use case where you'd explicitly set both "Monitor Movie and Collection" and "Clean Library"? The only one I can think of is to waste bandwidth. Otherwise, this seems like a flaw in the design.

**Comment by bakerboy448** [comment]
It leaves a footgun for users, yes.
