### ISSUE TITLE
When searching interactive, display resolution of releases

### ISSUE THREAD

**Issue by RuneMason1** [Radarr/Radarr#10073]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I'd love to be able to see resolution for releases in search results. It would allow me to more easily filter and choose a release that doesn't have hard coded black bars 

### Describe the solution you'd like

Display resolution or give the option to show resolution within the interactive search dialog box

### Describe alternatives you've considered

Looking at each release manually 

### Anything else?

Nothing

**Comment by bakerboy448** [comment]
Unnecessary - quality is already composed of source and resolution.

Torznab and newznab do not and likely never will support a resolution attribute.

closing, no plans
