### ISSUE TITLE
Logged out every time I close the tab

### ISSUE THREAD

**Issue by rwjack** [Radarr/Radarr#10084]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Radarr logs me out every time I close the tab.

### Expected Behavior

The remember me button should remember me. I don't have this issue with Sonarr.

### Steps To Reproduce

Open radarr, check remember me, log in, close browser tab, open radarr, asked to log in again.

### Environment

```markdown
- OS: Docker
- Radarr: 5.6.0.8846-ls223 by linuxserver.io
- Docker Install: yes
- Using Reverse Proxy: yes
- Browser: Firefox
- Database: Sqlite 3.45.3
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

[trace.txt](https://github.com/user-attachments/files/15804772/trace.txt)

Steps:

1. Enable trace logs
2. Save
3. Close tab
4. Open radarr
5. Log in
6. Close tab
7. Open radarr
8. Log in
9. Disable trace logs
10. Save

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
- basic auth does not support remembering login - this is a browser limitation
- Forms auth does and uses cookies. Presumably you have something clearing radarr's cookies.

For further support questions, visit discord
