### ISSUE TITLE
manual override for basic password requirement

### ISSUE THREAD

**Issue by dsm1212** [Radarr/Radarr#10098]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I now need to enter two passwords to log into radarr. I know it was a recent change to require a password for non-local addresses, but that's what I use authelia for. I really don't need a second password to access radarr. 

### Describe the solution you'd like

Can you provide a way for someone to turn this off please? Is ok if it is a backdoor. Maybe a docker environment setting even.

### Describe alternatives you've considered

Reverting to an earlier version but then I'm behind.
I did find a number of issues about disabling but they all appear to be prior to dropping the support for none.

### Anything else?

I don't think logs are necessary for this one.

**Comment by bakerboy448** [comment]
>>>  I have searched the existing open and closed issues

I doubt this given the numerous duplicates relating to users wanting to disable auth, which is covered in the FAQ as well as the numerous duplicates for this issue

#9354
#9284
#9282
#9245
#9163
#9104
