### ISSUE TITLE
Another Movie not found issue: Never Tear Us Apart: The Untold Story Of INXS

### ISSUE THREAD

**Issue by stuart0001** [Radarr/Radarr#1010]
**Description:**

Looks like the sub title is throwing it out. Thanks

![image](https://cloud.githubusercontent.com/assets/2950932/23582711/09f03168-0128-11e7-9bed-52d618023bed.png)

**Radarr Version:**
0.2.0.375

**Logs:**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by jOOc** [comment]
Maybe its because its listed both as a TV show and a MOVIE on TMDB
And IMDB only show its as a TV-Series.

You can download it via Sonarr (Search for: Never Tear Us Apart)

**Comment by onedr0p** [comment]
Yes, handle this in Sonarr.
