### ISSUE TITLE
Removed TMDB entry complicates manual searches and deleting database entries.

### ISSUE THREAD

**Issue by 4C3T** [Radarr/Radarr#10102]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I think there should be a link to the movie's entry in the Radarr database and not just a name like: 
`Movies Secret Society (tmdbid 812644), Mystery Science Theater 3000: Carnival Magic (tmdbid 1303360) were removed from TMDb`. There's not even a year shown which could be helpful.

In my case I have a lot of movies, which not only makes Radarr slow, but it takes time to sort out which potential duplicate it is that I need to remove.
Sometimes Lists generated from actors can add a whole bunch of movies and that can take a long time to manually remove these entries.

### Describe the solution you'd like

There could also be a delete icon, or for when TMDB  goes on a deleting spree, a check box for each entry and a remove button, but that's probably a lot of work, so that would be a bonus to have & perhaps wishful thinking.

I'd settle for just a link to the movie's page.
Thank you.

### Describe alternatives you've considered

None available.

### Anything else?

I also question the warning in red when it comes to removed entries from TMDB.
Red to me is critical, and a removed movie isn't.
Sure it complicates things if imports or any other traffic is en route, but it isn't a fire, and no more in conflict than a file that won't import for whatever reason, which coincidentally gives warnings in orange.

**Comment by bakerboy448** [comment]
Movies removed from tmdb have a status of deleted which can be filtered on the movie index
