### ISSUE TITLE
List import still broken

### ISSUE THREAD

**Issue by HybridTheory47** [Radarr/Radarr#10125]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

https://github.com/Radarr/Radarr/issues/10101

This was closed, but I tried to respoind and it wouldn't let me. You guys said that list only had less than 20 items - https://www.themoviedb.org/company/72685/movie - but yet on the tmdb web page it has hundreds.

### Expected Behavior

List import should import all items in list

### Environment

```markdown
- OS: Linux
- Radarr: 5.7.0.8882
- Docker Install: No
- Using Reverse Proxy: No 
- Browser: Chrome
- Database: Default/Embedded
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

[radarr.trace.2.txt](https://github.com/user-attachments/files/16036648/radarr.trace.2.txt)

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
Provided logs do not appear to be valid for the issue and only appear to show list refresh attempts that are blocked due to the mandatory refresh interval.

invalid bug report. Perhaps we can reopen if and when you provide the correct logs

**Comment by HybridTheory47** [comment]
What exactly am I looking for?

**Comment by HybridTheory47** [comment]
So I have to do my own debugging and come to you guys with a fully realised solution?

**Comment by bakerboy448** [comment]
You need to provide logs that capture the issue as noted in the bug report template

this would be trace logs of a successful sync showing all movies on your list that radarr processes.

currently this bug report is invalid and yes it is expected that users provide the mandatory required information for bug reports including trace logs demonstrating the reported issue you do not need to provide the code fix...

**Comment by HybridTheory47** [comment]
[radarr.debug.6.txt](https://github.com/user-attachments/files/16036827/radarr.debug.6.txt)

**Comment by HybridTheory47** [comment]
IN my previous ticket I did that but it was closed prematurely. Here's another one that says there are only 17 items in that list, when the TMDB UI shows hundreds.

**Comment by HybridTheory47** [comment]
230 to be exact, says it on the top right of their page

**Comment by bakerboy448** [comment]
Debug logs are not the required trace logs

**Comment by HybridTheory47** [comment]
I've done a grep on the term UFC in all my trace logs and nothing comes back relevant - would that be helpful if I provide that grep output? I have like 50 trace logs

**Comment by HybridTheory47** [comment]
[radarr logs - grep ufc on log dir.txt](https://github.com/user-attachments/files/16036877/radarr.logs.-.grep.ufc.on.log.dir.txt)

**Comment by bakerboy448** [comment]
No the only thing that will be helpful is the requested trace logs. Please stop spamming every thought.

Please use [Discord](https://radarr.video/discord) for support/questions.

further commentary that's unproductive and not what is asked may result in this issue being locked

**Comment by HybridTheory47** [comment]
Oh wow that's really unhelpful.

What happens if radarr does not do adequate logging? Which is what I have seemed to have discovered? There is nothing in the logs that says anything went wrong, it says it found 17 items and works normally. But the list is 230 items.... Where is the disconnect?

**Comment by HybridTheory47** [comment]
I had thought to reduce the size of my trace logs by providing a limiting term "UFC" - obviously thats unhelpful.

Here is a full trace log, every trace log output by my radarr instance in the last few weeks. A much larger file.

[radarr.all.trace.logs.zip](https://github.com/user-attachments/files/16036965/radarr.all.trace.logs.zip)

**Comment by bakerboy448** [comment]
No one is going to bother to download a random zip and review all the logs file for you.
If your unable to provide what is requested then please do not waste time by opening bug invalid reports.

Please use [Discord](https://radarr.video/discord) for support/questions.

**Comment by HybridTheory47** [comment]
Im trying here

**Comment by HybridTheory47** [comment]
[radarr.trace.42.txt](https://github.com/user-attachments/files/16036997/radarr.trace.42.txt)


2024-06-29 00:45:18.3|Trace|FetchAndParseImportListService|Skipping refresh of Import List TMDb Keyword ([UFC]) due to minimum refresh interval. Next Sync after 29/6/2024 12:44:20 am

This line is interesting. Talks about skipping, but its after the threshold. 

Then about 100 lines down in the file it next talks about this: 2024-06-29 00:45:18.3|Trace|FetchAndParseImportListService|Skipping refresh of Import List TMDb Company ([[UFC]] 2) due to minimum refresh interval. Next Sync after 28/6/2024 4:29:10 pm

It's as if it decided to skip when it shouldn't - and updated the next available time to run anyway.

**Comment by bakerboy448** [comment]
Not a bug as Bogdan previously informed you. TMDb's api is only returning returning 13 items. Content TMDb support for their api. Thanks for providing the logs that confirm that.

a random search result on their site has nothing to do with tmdb's api

please do not open a triplicate bug.

**Comment by HybridTheory47** [comment]
I will raise a support request on tmdb then.

You're definitely sure radarr is grabbing everything that tmdb returns?

**Comment by HybridTheory47** [comment]
Radarr supports it fine if it's not marked as a video in tmdb. If you accept videos in your lists, it works great.
