### ISSUE TITLE
Radarr not importing all list items

### ISSUE THREAD

**Issue by HybridTheory47** [Radarr/Radarr#10126]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Per https://github.com/Radarr/Radarr/issues/10125,

Radarr imports lists from TMDB. By default it appears not to set include_video as an option in the request, limiting what items are brought back from TMDB

Looks like TMDB changed how they behave as this used to work and Radarr was not made aware of that change in order to ensure they updated with that behaviour change.

Radarr shouold add include_video=true to list requests

### Expected Behavior

A TMDB list with 230 items should come back with 230, not 17

### Steps To Reproduce

https://api.themoviedb.org/3/discover/movie?include_adult=false&include_video=false&language=en-US&page=1&sort_by=popularity.desc&with_companies=72685 -> 17 results

### Environment

```markdown
- OS: linux
- Radarr: 5.7.0.8882
- Docker Install: no
- Using Reverse Proxy: no 
- Browser:  Chrome
- Database:  embedded
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

https://api.themoviedb.org/3/discover/movie?include_adult=false&include_video=false&language=en-US&page=1&sort_by=popularity.desc&with_companies=72685 -> 17 results

https://api.themoviedb.org/3/discover/movie?include_adult=false&include_video=false&language=en-US&page=1&sort_by=popularity.desc&with_companies=72685&include_video=true -> 230 results

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
Not a bug

no plans for videos / sports support at this time
https://github.com/Radarr/Radarr/issues/10125#issuecomment-2197820777
