### ISSUE TITLE
Radarr not finding upgrades

### ISSUE THREAD

**Issue by zprewitt** [Radarr/Radarr#1013]
**Description:**

A couple of days ago, I did a bulk import of my movie library. For all of the films that were 720p, I set them to Monitored with the HD-1080p profile. Since then, Radarr has found but not grabbed any eligible releases. I've posted a couple of screenshots below.

I've set the HD-1080p cutoff to 1080p-BluRay, and Radarr set the quality of my 720p files to HDTV-720p, so it should be grabbing stuff. I'm seeing this a lot in the logs:

17-3-4 12:16:02.1|Info|RssSyncService|Starting RSS Sync
17-3-4 12:16:38.5|Info|DownloadDecisionMaker|Processing 200 releases
17-3-4 12:16:44.7|Info|RssSyncService|RSS Sync Completed. Reports found: 200, Reports grabbed: 0

**Radarr Version:**
0.2.0.375 develop

**Logs:**
[radarr.txt](https://github.com/Radarr/Radarr/files/819017/radarr.txt)

![wailing](https://cloud.githubusercontent.com/assets/12501149/23583292/1f6055e2-00f5-11e7-96fc-ab4f240f71dd.png)

![startrek](https://cloud.githubusercontent.com/assets/12501149/23583293/22f85650-00f5-11e7-8ea5-b62f1b3fff82.png)

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by onedr0p** [comment]
RSS Sync doesn't search for all movies, it only grabs the latest feed of movies (i.e. last 50 movies uploaded to a indexer) from your indexers. What you want is in the Wanted page and under the cutoff tab. In the next release there will be a Search all for all cutoff unmet.
