### ISSUE TITLE
Can't access radarr ui du to duplicated key in DB

### ISSUE THREAD

**Issue by Tomarok** [Radarr/Radarr#10144]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Today after several days of absence I tried to connect to the UI of my Radarr container and impossible to access it 

` Failed to load Radarr `

looking at the logs of my container I noticed that it there was a duplication in my database 

`System.ArgumentException: An item with the same key has already been added. Key: 3052`

I checked my "Collections" table and my "Movies" table but I got nothing find with key 3052, I looked in the other issues and I saw something similar but nothing that corresponded exactly to my problem [here](https://github.com/Radarr/Radarr/issues/6340)

### Expected Behavior

Radarr should be able to not insert duplicate keys into tables.

### Steps To Reproduce

Can't really tell how to reproduce...

### Environment

```markdown
- OS: Unraid 6.12.8
- Radarr: Radarr 5.8.2.8908
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: ARC v.1.8.0
- Database: Sqlite 3.35.5
```

### What branch are you running?

Nightly

### Trace Logs? **Not Optional**

https://logs.notifiarr.com/?d919083edb42ea19#73bKjHWCAsKjgi9g8TwSpwMr247CX5nuFDFCu9HCKrgK

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
- also the provided logs are not the trace logs the bug report required that the wiki notes how to get and indicates you lied by checking  the box saying the wiki was followed and trace logs provided

why lie? (Rhetorical, don't answer it)

**Comment by Tomarok** [comment]
Sorry, I consulted the wiki link to find out how to post my logs, but since my ui was inaccessible I didn't think I could go from Info to Trace

**Comment by Tomarok** [comment]
> * also the provided logs are not the trace logs the bug report required that the wiki notes how to get and indicates you lied by checking  the box saying the wiki was followed and trace logs provided
> 
> why lie? (Rhetorical, don't answer it)

So I have to re-open an issue with the trace logs? because I clearly don't think this is a support request given that it's not normal for radarr to write the same key twice in base
