### ISSUE TITLE
Radarr keeps upgrading my movies, for unknown reason

### ISSUE THREAD

**Issue by journeym** [Radarr/Radarr#10159]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I have configured two format scores for releases

![Screenshot 2024-07-12 195822](https://github.com/user-attachments/assets/fa045b98-e914-4e6e-b31f-d4cd4fdfe71c)

But for some reason my releases keep updating with same format score

![Screenshot 2024-07-12 200018](https://github.com/user-attachments/assets/5976eb57-e93e-4f11-a6e0-53c5e61a86d3)

What am i doing wrong here?

### Expected Behavior

upgrade to +25 and then wait for +50 occurence

### Environment

```markdown
- OS: Ubuntu latest
- Radarr: 5.7.0.8882
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Edge
- Database: Sqlite 3.45.3
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

[radarr (1).txt](https://github.com/user-attachments/files/16198461/radarr.1.txt)

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by journeym** [comment]
Custom formats
![image](https://github.com/user-attachments/assets/77d6eeaf-1e77-48a2-8d4a-83be63089390)
![image](https://github.com/user-attachments/assets/a77a53ad-45e7-4b5c-890e-70b406b12534)

![image](https://github.com/user-attachments/assets/5b38908e-0f0c-4dc8-a08a-204529481132)
![image](https://github.com/user-attachments/assets/51afb97f-7bd1-42f3-8983-976d22c8d055)

**Comment by bakerboy448** [comment]
This is a support issue.

For Future Reference:
- info logs are not the required trace logs
- Please do not check the box claiming the wiki was followed when no such attempt was made `I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain trace - that are relevant and show this issue.`
