### ISSUE TITLE
{Quality Title} doesn't work in Movie Folder Format.

### ISSUE THREAD

**Issue by Copyrighter** [Radarr/Radarr#10192]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I would like to use following format:
{Movie Collection}/{Movie Title} ({Release Year}) [{Quality Title}]
The result displayed in Example:
The Movie Collection/The Movie Title (2010) [Bluray-1080p]

Actual Result:
The Movie Collection/The Movie Title (2010) []

### Expected Behavior

Expected to work according to example in Movie Folder Format.
The Movie Collection/The Movie Title (2010) [Bluray-1080p]

### Steps To Reproduce

1. Use following Movie Folder Format:
{Movie Collection}/{Movie Title} ({Release Year}) [{Quality Title}]
2. Discover and wait for download to be completed.
3. Look on the result.

### Environment

```markdown
- OS: Docker
- Radarr: 5.7.0.8882-ls227 by linuxserver.io
- Docker Install: linuxserver/radarr
- Using Reverse Proxy: 
- Browser: Chrome Version 125.0.6422.77 (Official Build) (64-bit) 
- Database: Docker
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

NA in INFO Log Level.
Problem can be reproduced easily.
Can take TRACE Level Log if necessary.

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
- duplicate of several GHI
- Not a bug
- No where does anything indicate you can use movie file properties in your movie folder name
- Only movie properties - not file properties - can be used in the folder name. The tokens can be found in the wiki and in the UI via the blue question mark
- No plans to add or support movie file properties in the movie folder

**Comment by Copyrighter** [comment]
> * duplicate of several GHI
> 
>     * Not a bug
> 
>     * No where does anything indicate you can use movie file properties in your movie folder name
> 
>     * Only movie properties - not file properties - can be used in the folder name. The tokens can be found in the wiki and in the UI via the blue question mark
> 
>     * No plans to add or support movie file properties in the movie folder

hi,
thank You for the prompt reply.

if it is not a Bug, then why it is not showed in "example"?
UI should reflect what the function is doing ... isn't it?

**Comment by bakerboy448** [comment]
Please use [Discord](https://radarr.video/discord) for support/questions.

**Comment by Copyrighter** [comment]
> * duplicate of several GHI
> 
>     * Not a bug
> 
>     * No where does anything indicate you can use movie file properties in your movie folder name
> 
>     * Only movie properties - not file properties - can be used in the folder name. The tokens can be found in the wiki and in the UI via the blue question mark
> 
>     * No plans to add or support movie file properties in the movie folder

then why I see this in UI?
![image](https://github.com/user-attachments/assets/0d32615a-9cba-4e7f-adb0-bcefbe988905)

**Comment by bakerboy448** [comment]
Please use [Discord](https://radarr.video/discord) for support/questions.
