### ISSUE TITLE
"Date added" column does not sort correct on window reload

### ISSUE THREAD

**Issue by jOOc** [Radarr/Radarr#1020]
**Description:**

When reloading the page the "date added" column is not sorted correct, you must click the title twice to get it sorted, see this:
http://recordit.co/FHdJFxSPfS

**Radarr Version:**

Radarr Ver. 0.2.0.449

**Comment by jOOc** [comment]
Noticed the sort seams to work if I choose page size 25, but not if I use any higher

**Comment by galli-leo** [comment]
Fixed on the latest nightly
