### ISSUE TITLE
allow hardcoded subs

### ISSUE THREAD

**Issue by p0nt** [Radarr/Radarr#1022]
I would like to be able to allow hardcoded dutch subs, setting the profile to dutch is not enough and is not working.

**Comment by p0nt** [comment]
example:

http://imgur.com/a/wIDOx

**Comment by onedr0p** [comment]
So DKSubs are not hardcoded, but NLSubs are? this shit is confusing..

**Comment by p0nt** [comment]
we have a few groups in the Netherlands releasing under their own name hardcoding dutch subs in their releases, but Radarr never choose them because it says that nlsubs are hardcoded.

is there any possible switch to enable/disable to allow or disallow the hardcoded subs as shown in the picture http://imgur.com/a/wIDOx

**Comment by onedr0p** [comment]
@galli-leo I think is looking into this today.

**Comment by onedr0p** [comment]
Closing for being a duplicate.

**Comment by piejanssens** [comment]
@onedr0p I've never seen a release with 'NLSubs' which had real hardcoded ( = subs are baked into the frames) subs. It's just to indicate that the MKV has an NL srt within it. 
I saw @galli-leo talk about adding an option to whitelist sub tags, but I can't find this in the UI of Radarr so I am assuming this isn't implemented yet?

**Comment by galli-leo** [comment]
@piejanssens It is. Try enabling advanced settings and looking at the indexer settings

**Comment by piejanssens** [comment]
@galli-leo Lovely! Thanks! I didn't check the indexer settings 😄
