### ISSUE TITLE
Need to downgrade to develop branch instead of nightly

### ISSUE THREAD

**Issue by mikelagase** [Radarr/Radarr#1026]
Seems that Nzb360 currently does not work with Radarr nightly branch (returns blank data) and need to switch to develop branch. I tried that but it seems that does not work as my profiles and quality are blank.

How can I downgrade to develop branch but also keep my configuration intact?

**Comment by onedr0p** [comment]
You cannot, sorry, you would have to "downgrade" your database and we don't do that. I would stay on nightly I know kev (nzb260 dev) is working on it. We are also doing a release today.

**Comment by mikelagase** [comment]
Great thanks!! I will stay on nightly releases then.

**Comment by mikelagase** [comment]
latest version works great. Would be great to get the wanted list as a tab option on the top as that is my ONLY issue at the moment. Trying to find the wanted movies in the list is tedious and time consuming. 

Thanks for the updates and the great app!!
