### ISSUE TITLE
Trakt list not working.

### ISSUE THREAD

**Issue by rickytin** [Radarr/Radarr#1029]
Trakt list integration is not working since yesterday.

**Comment by rickytin** [comment]
You can delete the issue.
This morning I try the Trakt Authentication and it did not work, now it try again and it work so Trakt list is working again.
Thanks

**Comment by geogolem** [comment]
wa just about to test and then respond to try and find out more information. It appears to be working for me. I will close this issue off.. Please let me know if you experience another issue.

**Comment by zmasterar** [comment]
i think trakt API was clanky
