### ISSUE TITLE
Update timeout

### ISSUE THREAD

**Issue by blackley** [Radarr/Radarr#1030]
For many weeks now i have been receiving an error message when attempting to update to the latest nightly version.

Version
    0.2.0.449
Mono Version
    4.8.0 (Stable 4.8.0.495/e4a3cf3 Wed Feb 22 18:30:58 UTC 2017)
AppData directory
    /home/plex/.config/Radarr
Startup directory
    /opt/Radarr 

**Logs:**
17-3-5 18:25:03.2|Warn|HttpClient|Failed to get response from: https://ci.appveyor.com/api/buildjobs/x4j2x87a162mfac0/artifacts/_artifacts/Radarr.develop.0.2.0.449.linux.tar.gz The operation has timed out.
17-3-5 18:25:03.3|Error|CommandExecutor|Error occurred while executing task ApplicationUpdate

**Comment by fryfrog** [comment]
I'd suggest turning logging level up to trace and capture the logs from a manually initiated update. It'd also be worth doing a wget of that url from the machine in question both to see if it works and if it does, to see how fast it goes.

**Comment by onedr0p** [comment]
Do you have libcurlssl installed?

**Comment by blackley** [comment]
I have turned on trace logging and just run a manual update - same error.  Here is the log entry below;

17-3-7 18:07:20.5|Info|InstallUpdateService|Deleting old update files
17-3-7 18:07:20.5|Info|InstallUpdateService|Downloading update 0.2.0.475
17-3-7 18:07:23.3|Warn|HttpClient|Failed to get response from: https://ci.appveyor.com/api/buildjobs/mrkfsuk5rma06ced/artifacts/_artifacts/Radarr.develop.0.2.0.475.linux.tar.gz The operation has timed out.
17-3-7 18:07:25.2|Error|CommandExecutor|Error occurred while executing task ApplicationUpdate

[v0.2.0.472] System.Net.WebException: The operation has timed out.
  at System.Net.WebClient.DownloadFile (System.Uri address, System.String fileName) [0x000c9] in <5641e4edad4f4464ba58c620a7b8ea48>:0 
  at System.Net.WebClient.DownloadFile (System.String address, System.String fileName) [0x00019] in <5641e4edad4f4464ba58c620a7b8ea48>:0 
  at (wrapper remoting-invoke-with-check) System.Net.WebClient:DownloadFile (string,string)
  at NzbDrone.Common.Http.HttpClient.DownloadFile (System.String url, System.String fileName) [0x00056] in <5cbd3cce2b4c4e2caee94731fee82be6>:0

**Comment by blackley** [comment]
yes i have libcurlssl installed

**Comment by blackley** [comment]
Wget results - 

wget https://ci.appveyor.com/api/buildjobs/mrkfsuk5rma06ced/artifacts/_artifacts/Radarr.develop.0.2.0.475.linux.tar.gz
--2017-03-07 18:10:49--  https://ci.appveyor.com/api/buildjobs/mrkfsuk5rma06ced/artifacts/_artifacts/Radarr.develop.0.2.0.475.linux.tar.gz
Resolving ci.appveyor.com (ci.appveyor.com)... 138.91.141.243
Connecting to ci.appveyor.com (ci.appveyor.com)|138.91.141.243|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://appveyorcidata.blob.core.windows.net/galli-leo-54456/radarr-usby1/0-2-0-475/mrkfsuk5rma06ced/_artifacts/Radarr.develop.0.2.0.475.linux.tar.gz?sv=2015-12-11&sr=c&sig=1KK26ijxMz10HIoQPOPtAUgZhytcCkahfQhc2vh1sL8%3D&st=2017-03-07T10%3A09%3A50Z&se=2017-03-07T10%3A15%3A50Z&sp=r [following]
--2017-03-07 18:10:51--  https://appveyorcidata.blob.core.windows.net/galli-leo-54456/radarr-usby1/0-2-0-475/mrkfsuk5rma06ced/_artifacts/Radarr.develop.0.2.0.475.linux.tar.gz?sv=2015-12-11&sr=c&sig=1KK26ijxMz10HIoQPOPtAUgZhytcCkahfQhc2vh1sL8%3D&st=2017-03-07T10%3A09%3A50Z&se=2017-03-07T10%3A15%3A50Z&sp=r
Resolving appveyorcidata.blob.core.windows.net (appveyorcidata.blob.core.windows.net)... 13.88.145.72
Connecting to appveyorcidata.blob.core.windows.net (appveyorcidata.blob.core.windows.net)|13.88.145.72|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7132576 (6.8M) [application/octet-stream]
Saving to: 'Radarr.develop.0.2.0.475.linux.tar.gz\u2019

Radarr.develop.0.2.0.475.linux.tar.gz             100%[==========================================================================================================>]   6.80M   476KB/s    in 13s     

2017-03-07 18:11:05 (552 KB/s) - 'Radarr.develop.0.2.0.475.linux.tar.gz\u2019 saved [7132576/7132576]

**Comment by onedr0p** [comment]
It's prolly just appveyor being slow.

**Comment by blackley** [comment]
@onedr0p is there anything I can do to resolve this? I have a 100mbps internet connection so I know it is not an issue with the uplink speed :-)

**Comment by onedr0p** [comment]
I know, but it's a problem with appveyor.

**Comment by fent** [comment]
Getting a similar response

    Failed to get response from: https://github.com/Radarr/Radarr/releases/download/v0.2.0.995/Radarr.develop.0.2.0.995.linux.tar.gz Error: SecureChannelFailure (The authentication or decryption has failed.)

**Comment by galli-leo** [comment]
@fent You need to upgrade mono to 5.8
