### ISSUE TITLE
ER : Push notifications on update

### ISSUE THREAD

**Issue by epheterson** [Radarr/Radarr#1032]
It's an advanced feature, but Sonarr and Radar offer automatic updates. There's no way for me to ever really know the update happened w/out checking. It'd be nice if the system could notify me via whatever service I've setup (PushBullet, Telegram, etc...) once an update is available, and again once the update is applied (just in case it never comes back up...).

**Comment by fryfrog** [comment]
Have a look at http://feathub.com/Radarr/Radarr and see if the request already exists, upvote if it does. If it doesn't, create one. One of the devs will probably close this issue soon.

**Comment by epheterson** [comment]
Added, thanks!
http://feathub.com/Radarr/Radarr/+124

(Didn't find one while searching)
