### ISSUE TITLE
Trakt authentication redirect doesn't account for URL base

### ISSUE THREAD

**Issue by chtk** [Radarr/Radarr#1034]
**Description:**

I use Radarr from behind a reverse proxy. So I have the URL base configured with the subdirectory as configured in nginx. 

After confirming the Trakt authentication dialog, the redirect to Radarr navigates to /settings/netimport instead of **/radarr**/settings/netimport. 

**Radarr Version:** Ver. 0.2.0.453

**Comment by onedr0p** [comment]
Fixed in nightly
