### ISSUE TITLE
Allow "Fallback Language" setting when Release (either per indexer, a profile, or per movie)

### ISSUE THREAD

**Issue by zwimer** [Radarr/Radarr#10395]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Release names do not always label English releases as English. This is rarely a problem if you primarily consume movies with English as an original language, but for foreign films it can often lead to English-audio releases being mislabeled as foreign languages and thus not being grabbed.

This is particularly common for SCENE releases. According to the [scenerules.org](https://scenerules.org/nfo/2020_X265.nfo)
```
18.5.7) Non-English releases must include the language tag. English releases must not include the language tag.
```

For example, consider the following case:
1. User uses an English-language tracker, foreign audio releases are either banned or rare/exceptions
2. User has quality profile set to Bluray (which is more likely to have dual audio than WEB, for example)
3. User requests `Lost in the Stars (2022)`, a Chinese film released with the primary audio language of Chinese, but with English as a secondary
4. Tracker contains `Lost.in.the.Stars.2022.1080p.Bluray.h264-ETHEL`, a Bluray rip that contains an English language audio track

In this case, Radarr will label this release's language as "Chinese" as it will fail to parse it, leading to something akin to the following in the logs:
```
2024-09-02 21:06:17.1|Debug|DownloadDecisionMaker|Processing release 'Lost.in.the.Stars.2022.1080p.Bluray.h264-ETHEL' from 'MyTracker'
2024-09-02 21:06:17.1|Debug|Parser|Parsing string 'Lost.in.the.Stars.2022.1080p.Bluray.h264-ETHEL'
2024-09-02 21:06:17.1|Debug|Parser|Movie Parsed. Lost in the Star - 2022
2024-09-02 21:06:17.1|Debug|Parser|Release Group parsed: ETHEL
2024-09-02 21:06:17.1|Debug|Parser|Languages parsed: Unknown
...
2024-09-02 21:06:17.1|Debug|AggregateLanguages|Language couldn't be parsed from release, fallback to movie original language: Chinese
2024-09-02 21:06:17.1|Debug|AggregateLanguages|Selected languages: Chinese
```

By default, Radarr selecting the original language for a movie it cannot parse the language for is a very good default, but in this situation it leads to an undesirable result.

### Describe the solution you'd like

It would be nice if users could, knowing their tracker is unlikely to release a torrent with non-English audio, and knowing their profile might discourage it (like if it requests the BDMV or something), could change the 'fallback language' from 'movie original' to a specific language (like English).

Specifically, one or multiple of the following would be appreciated:
1. Allow users to set a 'fallback language' per tracker, sort of like they can already define what `Multi Languages` means
2. Allow users to set a 'fallback language' per profile
3. Allow users to set a 'fallback language' per movie

### Describe alternatives you've considered

Requesting the movie in the movie-original / any language. The reason to avoid this is, for example, in case the following two releases both exist:
  - `Lost.in.the.Stars.2022.1080p.Bluray.h264-ETHEL`
  - `Lost.in.the.Stars.2022.2160p.Bluray.h264-Chinese-ETHEL`

In this case, SCENE rules might dictate that the English version be unlabeled, but the non-English be labeled (rule 18.5.7 listed above for example). In this case, Radarr is likely to prefer the 4k version to the 1080p version because we have explicitly told it that movies labeled as `Chinese` are preferred. Instead, we want the 1080p version, however, as that is in English

### Anything else?

1. If this is added per-indexer: Users could add a 'low priority' index that has this setting enabled if they desire, so it only ever is considered if movies explicitly labeled as English cannot be found.
2. If this is added per-profile: Radarr-users who do not manage radarr directly but instead use some frontend like overseerr could add a profile that toggles if this is allowed. Since users of overseerr can select quality profiles, they can choose to set this profile on foreign films as they request them should they desire.

**Comment by zwimer** [comment]
If you can link any issue this is a duplicate of

**Comment by zwimer** [comment]
@mynameisbogdan I will wait for the person you @'d to respond but if you/they can find any issues this is a duplicate of, I'd be happy to close this. I couldn't find any that matched this particular problem among the open issues after searching for 'language'. The most similar issues I could find were:
https://github.com/Radarr/Radarr/issues/10044 (This is awaiting triage still and I am unclear if it is the same underlying issue or not because there's not much written here)
https://github.com/Radarr/Radarr/issues/3437 (This is different, but the suggested fix comment by @fryfrog [here](https://github.com/Radarr/Radarr/issues/3437#issuecomment-485632211) is similar)

I'm not sure what "FR" means, but this issue is not exclusive to scene releases. I very rarely see movies tagged with English- anecdotally, only 10/7631 of my movies contain "English" in their names.
 
The point is merely that English-audio releases of non-English-original-audio movies, which are often not labeled as "English" across SCENE, P2P, NOGRP, etc releases, default to the movies' original-audio; which can often lead to English-audio releases not being snatched when they ought to be; adding one of these settings might allow some users to bypass this issue.

I do understand this being a low priority until langue-support is included in the future.

**Comment by bakerboy448** [comment]
Denied.

> Using Scene rules as an argument makes this whole FR invalid from the start since we don't keep track of scene groups, and any change would affect P2P or user ripped media.

concur

Related to https://github.com/Radarr/Radarr/issues/9972

This is an tracker issue with them failing to name releases correctly thus the primary issue AND presumably failing to note the languages correctly on the site which would prevent Prowlarr/Jackett reporting the release's languages via Torznab attributes.

and 

> knowing their profile might discourage it

Makes this a support/configuration

Further discussion on discord confirms this is a feature request caused by 1) trackers being 💩 and 2) user misconfiguration

>> ,or just use the original language?
> The reason I've avoided that is in the off chance someone uploads a release like `Dragonkeeper.2024.Chinese-ETHEL.mkv` or something. Non-english releases are rare, but they do sometimes temporarily pop up on the tracker, but they are almost labeled as non-English. For now I think I'll code a script for this.

This seems to be a tracker specific issue more than a Radarr issue
