### ISSUE TITLE
Proper Downloaded when "Download Propers" is set to NO

### ISSUE THREAD

**Issue by vertigo235** [Radarr/Radarr#1039]
Radarr downloaded a proper this morning, but I have that turned off. It was not an upgrade as I already had a 1080p version of the movie. 

This wasn't a problem until recently. 

**Radarr Version:**
Radarr Ver. 0.2.0.459

**Logs:**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by onedr0p** [comment]
I think this is a duplicate issue.

**Comment by onedr0p** [comment]
See here https://github.com/Radarr/Radarr/issues/546

**Comment by vertigo235** [comment]
That's a closed issue, also mine was picked up by RSS so not by design as you stated in the other issue.

**Comment by vertigo235** [comment]
Unless we are scheduling backlog searches now?

**Comment by vertigo235** [comment]
Is this perhaps what the issue was? From recent change log?

* DIsable movie search after list sync (causing issues)
