### ISSUE TITLE
Authentication for local addresses should also include Shared Address Space in local IP list

### ISSUE THREAD

**Issue by tazz4843** [Radarr/Radarr#10393]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

RFC 6598 defines the `100.64.0.0/10` subnet as local addresses for private networks (Tailscale the easiest example) that aren't exposed to the public internet. See https://www.rfc-editor.org/rfc/rfc6598 

*arr don't include this address range in their list of local IPs, despite it being explicitly reserved for local devices. This causes authentication walls to still be shown to devices originating from the 100.64.0.0/10 subnet.

### Describe the solution you'd like

*arr should include `100.64.0.0/10` as a local network address.

### Describe alternatives you've considered

Allow users to configure the list of allowed local network IPs in the web UI - probably the best idea in general, but without that this is a sufficient replacement for this use case.

### Anything else?

Only reference I can find was https://github.com/Radarr/Radarr/issues/9242#issuecomment-1786338872 but this was never responded to despite getting 5 +1 reactions before the thread was locked.

**Comment by bakerboy448** [comment]
No plans for this for now

Won't fix per upstream notes given this would  allow non-local access due to CGAT on some carriers

https://github.com/Sonarr/Sonarr/issues/6534#issuecomment-1957930557
