### ISSUE TITLE
Subfolder scan

### ISSUE THREAD

**Issue by renedis** [Radarr/Radarr#1040]
**Description:**

Radarr is not able to add movies that are in subfolders.
It keeps telling "File not found" or it just is not showing up in the list.

**Radarr Version:**
0.2.0.453 - Mar 6 2017

**Logs:**
[radarr.txt](https://github.com/Radarr/Radarr/files/821617/radarr.txt)

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by onedr0p** [comment]
What do you mean, care to give example of what you set your root folder to and the full path to the movie file?

**Comment by onedr0p** [comment]
Please read the setup guide in the wiki for how you movies should be structured.
