### ISSUE TITLE
Requesting support for S3 object storage

### ISSUE THREAD

**Issue by bernardgut** [Radarr/Radarr#10417]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Anyone who has libraries 30TB+ or bigger cannot use your software suite because, well 30TB+ devices dont really exist. So such a library is unmountable. It turns out distributed object storage such as Minio is what is used for big data. *Arr suite should therefore support S3 protocol natively.

### Describe the solution you'd like

same as https://github.com/Radarr/Radarr/issues/7020

### Describe alternatives you've considered

There are no realistic alternatives for really large datasets (50TB+)

### Anything else?

same as https://github.com/Radarr/Radarr/issues/7020

**Comment by bernardgut** [comment]
> Have you tried rclone?

Have you read the request : You cannot use rclone because you cannot mount 50TB+ volumes, because there is no such thing in the market as a 50TB disk. When you start having more data than the biggest disk in existence you need to split this data into multiple disks. So, for such cases, you use the tools designed for such use cases: Distributed Object Storage aka, S3.

**Comment by bernardgut** [comment]
I understand that it is possible using NFS. NFS is slow, old and insecure. It is strongly recommended not to use it even by the Kubernetes SIGs that maintains the NFS CSI upstream in kubernetes due to its security issues. Why not plan to add support for the standard for large datasets in 2024 which is Distributed Object Storage ? 

Until someone writes a free CSI implementing `readWriteMany` that is fast enough there is literally only S3 as a solution to this problem. I don't blame people for using NFS (NAS) but really its a non-solution in 2024. Consider what your users use your application for.

**Comment by bernardgut** [comment]
I am not trying to be a smartass. I understand. I am not talking about AWS: S3 is a *protocol*. *Not* an AWS service.

You realize if you have 10 nodes at home with 40TB each, spinning up a K8s cluster with Minio instance and storing 400TB takes 10min. Try spinning up anything that supports these kind of workloads with NFS (TrueNAS Scale) with good performance.... Good luck with that. I should know I do that for a living.

Now I understand 400+TB is a "niche" in your mind... But with 8K video on the horizon and people getting more familiar with kubernetes at home, why keep this backward NFS only mindset ? Sounds pretty bad to me for 2024.

Again you might not be familiar with current DevSecOps trends but deploying this : https://github.com/bitnami/charts/tree/main/bitnami/minio/ on your cluster will take you 5 min and this thing can eat 200PB. Even on Raspberry Pis.

Just Saying.

**Comment by Roxedus** [comment]
S3 for media should be the last thing these tools change for cluster configs.

**Comment by Krandor1** [comment]
I have mounted a 700TB volume with rclone without any issues.  That was
gdrive and not S3 but rclone absolutely supports large volumes.
--
Brian Hartsfield
