### ISSUE TITLE
Allow for multi instance log in

### ISSUE THREAD

**Issue by rafapirotto** [Radarr/Radarr#10416]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Basically, I have multiple instances of Radarr and whenever I'm logged in to one and then try to log in to the other one it basically logs me out from the first one. So login in one instance logs me out from the other one. I think that the reason is that the cookie is named "RadarrAuth" in both instances so one replaces the other one, which would explain why I get redirected to the log in screen:
![radarr-bug](https://github.com/user-attachments/assets/449f7d9b-964a-4581-a50d-00917c08dae8)

### Describe the solution you'd like

I think the solution is as simple as using "`RadarrInstanceNameAuth`" to prevent the instances from replacing the other's cookie hence login out from the other instance. This can be applied to the other settings in localStorage as well.
![image](https://github.com/user-attachments/assets/53311cac-cbfb-4342-b154-ee244f01d4bd)

This could be `RadarrInstanceNameAuth` instead of `RadarrAuth`:
![image](https://github.com/user-attachments/assets/b8bd0f94-f333-4213-a951-16feab1fd055)

### Describe alternatives you've considered

Just live with this. Not much else to add to this section.

### Anything else?

Nope

**Comment by rafapirotto** [comment]
Maybe the change is something along these lines:
src/Radarr.Http/Authentication/AuthenticationBuilderExtensions.cs

```
        public static AuthenticationBuilder AddAppAuthentication(this IServiceCollection services)
        {
            return services.AddAuthentication()
                .AddNone(AuthenticationType.None.ToString())
                .AddExternal(AuthenticationType.External.ToString())
                .AddBasic(AuthenticationType.Basic.ToString())
                .AddCookie(AuthenticationType.Forms.ToString(), options =>
                {
                    // update this to use the instanceName variable
                    options.Cookie.Name = "RadarrAuth";
                    options.AccessDeniedPath = "/login?loginFailed=true";
                    options.LoginPath = "/login";
                    options.ExpireTimeSpan = TimeSpan.FromDays(7);
                    options.SlidingExpiration = true;
                    options.ReturnUrlParameter = "returnUrl";
                })
                .AddApiKey("API", options =>
                {
                    options.HeaderName = "X-Api-Key";
                    options.QueryName = "apikey";
                })
                .AddApiKey("SignalR", options =>
                {
                    options.HeaderName = "X-Api-Key";
                    options.QueryName = "access_token";
                });
        }
```

**Comment by rafapirotto** [comment]
Exactly, that is why I proposed using the `instanceName` variable

**Comment by bakerboy448** [comment]
Some legacy commentary on https://github.com/Radarr/Radarr/pull/6722

**Comment by rafapirotto** [comment]
Using the port seems reasonable right? It that simple to do?

**Comment by rafapirotto** [comment]
What about using the url?

**Comment by rafapirotto** [comment]
Hey @mynameisbogdan , a sonarr dev pulled up this pr. Maybe we could do something similar for Radarr?
https://github.com/Sonarr/Sonarr/pull/7208

**Comment by rafapirotto** [comment]
But is it the exact same code? I’m not sure that we can cherry pick thar commit and would have to do it manually

**Comment by rafapirotto** [comment]
Pr created [here](https://github.com/Radarr/Radarr/pull/10440)
