### ISSUE TITLE
Unable to change Remux titles

### ISSUE THREAD

**Issue by kalendubrick** [Radarr/Radarr#1042]
Description:

When I attempt to change the titles of the new Remux-1080p and Remux-2160p qualities, radarr shows the toast notification saying settings have been saved, but when I return to the Quality settings, the titles always revert to the default.  This does not occur with the other qualities that existed before the latest update.

Radarr Version: 0.2.0.453 (develop)

**Comment by onedr0p** [comment]
Set a page size in ui settings and try again, this is a known issue.

**Comment by kalendubrick** [comment]
I tried this; however, the page size also does not persist for me.

**Comment by onedr0p** [comment]
Clear cache, try incognito, set page size. I know this is a issue and this solves it Everytime.
