### ISSUE TITLE
Movie Page resets sort options upon page refresh

### ISSUE THREAD

**Issue by theebanka** [Radarr/Radarr#1043]
After the last version upgrade I have noticed that my main page doesnt obey the selected sort options when I refresh the page despite showing the right options greyed out. In the attached picture you can see that I have the "Missing Only" option selected yet all of the movies that it shows have been downloaded already or are not monitored. 
![screen shot 2017-03-06 at 10 18 09 am](https://cloud.githubusercontent.com/assets/10566478/23623342/8ba7f14e-0256-11e7-8804-e181d6996bd0.png)

In my experience clicking the "Missing Only" button again will return it to the expected view

**Comment by geogolem** [comment]
I put fixes in for this this morning. Can you please try again with the latest. I put the fix in about 2 or 3 hours ago... I will close this issue for now; however, if you are still having problems please comment back.
