### ISSUE TITLE
Copy & Paste when adding movies

### ISSUE THREAD

**Issue by Fredrik81** [Radarr/Radarr#1044]
**Description:**

Copy & Paste does not automatically start search when adding movies.
If i copy a movie title from a page then go into "Add Movie" then paste in the title nothing is happening.
So after that i have to remove last character and add it again to make it search.

Same thing is happening on Sonarr so i think it's an inherited issue. (using Google Chrome)

**Radarr Version:**
0.2.0.453

**Comment by onedr0p** [comment]
Working as intended, just hit enter.
