### ISSUE TITLE
Movie Search in Indexer fail to identify Movie Title due to Brackets in release.

### ISSUE THREAD

**Issue by Copyrighter** [Radarr/Radarr#10451]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Following Search classified as Release Rejected due to Unknown Movie:
"
Быль-небылица (Владимир Полковников) [1970, рисованный, TVRip]
"
Current Result:
Release Title - Быль-небылица (Владимир Полковников) [1970, рисованный, TVRip]
Movie Title - Быль-небылица (Владимир Полковников) [
Year - 1970
All Titles - Быль-небылица (Владимир Полковников) [

### Expected Behavior

Everything in round brackets and square brackets should not be considered as Movie Title.
Result Should be:
Movie Title - Быль-небылица

In some cases, only in Round Brackets can be alternative name, but never in square brackets.

### Steps To Reproduce

1. Paste in Test Parsing:
Быль-небылица (Владимир Полковников) [1970, рисованный, TVRip]

### Environment

```markdown
- OS: Docker
- Radarr: 5.9.1.9070
- Docker Install: 5.9.1.9070-ls236 by linuxserver.io
- Using Reverse Proxy: 
- Browser: Chrome Version 126.0.6478.183 (Official Build) (64-bit)
- Database: Sqlite 3.45.3
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

None

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
- Not valid naming scheme
- no plans to support this Non-standard niche naming
- Simply requirements are movie title before the year only - no other garbage
- Limited support for AKA and multiple titles before year exists

**Comment by Copyrighter** [comment]
@bakerboy448 
in other words, Radarr will not support automatic search for a lot of Torrents out there.
... you are most welcome to teach a lot of torrent to recreate their content per Radarr demand ...
as a reminder, Radarr is still not at the level of establishing standards and definitely not be with this kind of approach.

**Comment by bakerboy448** [comment]
Trackers that support id based search don't have this issue.  Bitch to your trackers for allowing non-standard naming and not supporting id based searching - https://wiki.servarr.com/radarr/faq#how-does-radarr-handle-foreign-movies-or-foreign-titles

**Comment by zakkarry** [comment]
I love how dude claims the majority of torrents out there are like his examples.

Sorry dude, the real solution is to stop using garbage trackers. As @bakerboy448 there are, and have been for about 40 years now, standard naming conventions that the community uses. The naming conventions that Radarr "accepts" (through extensive testing and painstaking regex creation) - was not created by Radarr. It was created in the 80s and has been used ever since with small variation outside of a handful of countries that don't understand logic (anime/eurasia/eastern eu being the big offenders).

Radarr is specifically geared towards content that is available in the western world and majority english adjacent (given TMDB is english centric) - so complaining that some Cyrillic titled movie with no naming convention doesn't parse is to be expected.

**Comment by Copyrighter** [comment]
@Copyrighter 
:-) hahahaha

it looks like I need to simplify it for you ... as now I understand why lately so many don't like Radarr ... hope alternative will rise soon. ( after looking on old Radarr issues, in the past there was a great guys working on the project ... )

Movie Name (Year) [sourceid=xxxx]
Regex: (Movie Name)( \(Year\))( \[sourceid\=xxxx\])
This is a Kodi standard ...

Kodi is taking Movie Title only from $1 ( see Regex ).
While Radarr ... the hell know why is taking: 
Movie Name (Year) [

I'm posting here and nod on Discord for one reason only, it's contribution to other guys who want to work together on best solution.
Unfortunately Radarr is well worth of your comments.

**Comment by Copyrighter** [comment]
@zakkarry 
again, Kodi is the standard, with all the respect for your contribution ... not Radarr.
If something works in Kodi, no reason it will not work in Radarr and Radarr will define new standard.

**Comment by zakkarry** [comment]
Kodi was initially released in 2002. The naming standards used in torrenting have been around at least twice as long as Kodi has existed.

Kodi isn't a standard. Standards are rules and conventions. There are scene nfo's released every few years with specifications. Updated as needed. These are what the torrent community basically goes by, as does the majority of the community by and large.

You have a survivor's bias towards Kodi.

Kodi is not a standard. It's a media program. Radarr and Kodi do not make the standards. They never have. Radarr adapted to the majority's ACTUAL standard and Kodi decided it was going to just wing it with random bullshit. You are now suffering at the hands of Kodi, not Radarr.

If you are unhappy with Radarr, no one is forcing you to use it. But be assured that you are incorrect and the trackers you are on are garbage.

**Comment by Copyrighter** [comment]
hmm ... just a history and a fact lesson for you ... Kodi, Plex, Emby, Jellyfin are all based on Xmbc ... you should read at least WIKI ...
from Xbmc era, they defacto created naming convention standard to which most of the content contributors in the world are applying.
Here is a link for you.
https://kodi.wiki/view/Naming_video_files/Movies

I truly hope one day Radarr will understand that they are managing Kodi/XBMC Like naming conventions ... not Radarr ...
or
will provide option for users to manage naming convention by themself using Regex.

The fact right now, Radarr can't automatically apply Custom Formats and download automatically files which are based on Kodi Movies naming convention.

The question, do You want to solve problem and improve Radarr, or will ALL wait for Radarr alternative or other contributors to Radarr.

**Comment by zakkarry** [comment]
And 25 years before any of those forks or anything else existed, naming conventions already existed. Plex works with scene naming conventions, just as a note.

It's fine, Believe whatever you want, its a free world. Ignorance is bliss, everyone can tell you you're wrong and you still think you're the one teaching here.

It doesn't change the facts though.

Since you want to link to Kodi's wiki, how about a non-biased source?

https://en.wikipedia.org/wiki/Standard_(warez)

Search for "Naming" - happy reading.

**Comment by RobinDadswell** [comment]
I have locked this issue as there is no point in arguing here. As @zakkarry and @bakerboy448 have mentioned we (all of the Arrs) follow Scene based naming conventions for the purpose of downloads. Naming convention for the file once it has been downloaded can be set to whatever format you chose through the naming convention area within each of the Arrs. 

Based on the example provided this goes far against the Scene naming convention, and having the year in the square brackets even goes against the KODI naming convention that you have provided a link to and as such is not going to be picked up in it's format as given. 

I would also like to make it clear that KODI works based on very specific naming conventions of files that you provide it, however we try to react to the various naming conventions out there where possible and have in some cases got some logic in for where indexers/trackers do not quite align to scene but are mostly there.
