### ISSUE TITLE
Movie Editor not showing any movies

### ISSUE THREAD

**Issue by teminvictus** [Radarr/Radarr#1051]
**Description:**

The movie editor is not showing any movies, although there are there are about 300 movies listed under "Movies".  I get the output "You must be new around here, You should add some movies."

**Radarr Version:**

0.2.0.472

**Logs:**

[radarr.txt](https://github.com/Radarr/Radarr/files/823547/radarr.txt)

**Comment by geogolem** [comment]
ya we know about this -- a bug got introduced yesterday and we already have a fix -- should be merged later today. I'll let you know when and then I'll close this issue.

**Comment by aspiziri** [comment]
@geogolem I'm still seeing this issue in build 0.2.0.846 from Aug 28th - is that expected? Using incognito mode works but can't get my movie lists to load otherwise.

**Comment by galli-leo** [comment]
@aspiziri Then its a caching issue. Clear cookies and cache
