### ISSUE TITLE
Parse IDMB and TMDB Full URLs in Add New Movie Page

### ISSUE THREAD

**Issue by Qualous** [Radarr/Radarr#10511]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Especially when working on a mobile phone, I would like to search for a new movie by the IMDB ID.  I often click on Share from the IMDB page to get the URL in the clipboard, switch to Radarr in a browser, go to the Add New Movie page, paste in the full URL, then adjust that URL to the tagged format of imdb:tt########.  The same applies to adjusting a TMDB URL to tmdb:#####.

### Describe the solution you'd like

I would like Radarr to detect that a full IMDB or TMDB URL was pasted and automatically search on that without having to manually manipulate/edit the URL into the tagged format.

- https://www.imdb.com/title/tt########/....
- https://www.themoviedb.org/movie/#####-....

### Describe alternatives you've considered

I've been working around this by manually editing the URLs.

### Anything else?

Example URLs:

- https://www.themoviedb.org/movie/889737-joker-folie-a-deux
- https://www.imdb.com/title/tt11315808/?ref_=fn_al_tt_1

 and their expected equivalents:

- tmdb:889737
- imdb:tt11315808

**Comment by bakerboy448** [comment]
Relating to https://github.com/Radarr/Radarr/issues/9395

PRs welcome for this, but no plans for us to work on it anytime soon
