### ISSUE TITLE
Search all missing on /wanted/missing page does not seem to function

### ISSUE THREAD

**Issue by ltomes** [Radarr/Radarr#1052]
**Description:**

I believe there is a bug around `Search all missing`
<img width="114" alt="screen shot 2017-03-07 at 12 47 46 am" src="https://cloud.githubusercontent.com/assets/4184677/23645035/be06bfd4-02cf-11e7-9c2f-8fae6591512b.png">
 on the `/wanted/missing` page. Pushing the button results in an immediate toast of 
> [missingmoviesearch] Completed
<img width="355" alt="screen shot 2017-03-07 at 12 43 29 am" src="https://cloud.githubusercontent.com/assets/4184677/23645005/9b2047d8-02cf-11e7-87b2-c380fbcde9f5.png">

Yet going page by page, selecting results, and pressing `Search Selected` results in files being added to my indexer.

**Radarr Version:**
Radarr Ver. 0.2.0.267

**Logs:**
[radarr.0.txt](https://github.com/Radarr/Radarr/files/823563/radarr.0.txt)
[radarr.1.txt](https://github.com/Radarr/Radarr/files/823565/radarr.1.txt)
[radarr.txt](https://github.com/Radarr/Radarr/files/823564/radarr.txt)

Let me know if I can provide any other details.

**Comment by zductiv** [comment]
You're running a pretty old version of radarr. Upgrade to one of the more recent releases.

**Comment by geogolem** [comment]
yes - I believe this has been fixed in more recent released. I am going to close this issue off. If it is still an issue in the latest - let us know.
