### ISSUE TITLE
Proxy check is failing

### ISSUE THREAD

**Issue by AeonLucid** [Radarr/Radarr#1053]
**Description:**

Proxy check is failing because /ping endpoint is not implemented in RadarrAPI. 
https://github.com/Radarr/Radarr/blob/520836f475cd5ed79e72b663c8b3cceb820a5f4f/src/NzbDrone.Core/HealthCheck/Checks/ProxyCheck.cs#L38

**Comment by AeonLucid** [comment]
I'll look at implementing /ping later today.

**Comment by evilvibes** [comment]
Yea having same issue.

**Comment by AeonLucid** [comment]
Added to RadarrAPI (and deployed): https://github.com/Radarr/RadarrAPI/commit/525692238df72a41cc20151104392fe8898635f2

Waiting for comment about if it's fixed. ( @evilvibes )

**Comment by evilvibes** [comment]
Working now
