### ISSUE TITLE
[Feature Request] YTS.AG Indexer!

### ISSUE THREAD

**Issue by twilightrazor** [Radarr/Radarr#1054]
I would really love to see a YTS.ag indexer. They have an API. I would rather download movies from here as the movie files are really small (which is perfect for streaming). Sadly Jackett does not support it. 
I do realize that the website in question is not the most savvy, which is why I want automatic downloading.

Link to YTS API Documentation:
https://yts.ag/api

**Comment by onedr0p** [comment]
You may want to open a request with github too.

**Comment by twilightrazor** [comment]
I just did lol

**Comment by galli-leo** [comment]
Closing this. Jackett implementation should be fine.
