### ISSUE TITLE
Downloaded files not being removed

### ISSUE THREAD

**Issue by SwedishMoosey** [Radarr/Radarr#10543]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

File is not removed once imported

### Expected Behavior

File is removed once imported

### Steps To Reproduce

1. Use 5.9.1.9070-ls236 by [linuxserver.io](https://linuxserver.io/)
2. Disable hardlinks setting and enable automatic removal of files once downloaded.
3. Use qbittorent to download a file.
4. File gets imported to streaming server but file is never removed,

### Environment

```markdown
- OS: Ubuntu 23
- Radarr: 5.9.1
- Docker Install: yes
- Using Reverse Proxy: Yes (traefik but happens without too)
- Browser: Firefox
- Database: Sqlite 3.45.3
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

[log.txt](https://github.com/user-attachments/files/17319409/log.txt)

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
- invalid bug report
- Support issue
- info logs are not trace logs
- checkbox for logs /Wiki link claiming it was followed checked in error
