### ISSUE TITLE
Automatic Downloads Not Triggering Despite Available Releases (Manual triggering of Search button works)

### ISSUE THREAD

**Issue by mordax7** [Radarr/Radarr#10558]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Radarr is **SOMETIMES** not automatically downloading movies, even though matching releases are available. When I manually initiate a search or remove and add the movie, Radarr finds the available releases and downloads them successfully. However, the automatic RSS sync does not trigger the download, even though the movie is set as "monitored" and meets the quality profile.

### Expected Behavior

Radarr should automatically download the movie when a matching release becomes available in the configured indexers during the scheduled RSS sync, without requiring a manual search.

### Steps To Reproduce

I was able to reproduce this issue if I requested multiple movies at once. So here is how:
1. Add multiple movies via Jellyseerr that had been already been released are available on the indexers.
2. Wait for Radarr to perform the scheduled RSS sync.
3. Observe that Radarr does not automatically download some movies.
4. Manually click the search button, and Radarr finds the available release and starts downloading.

I also waiting for a full day to see if it was some task that did not run yet, without success.

I think I was also able to reproduce the issue if the indexers were offline for the time when I added the movie. Once the indexers were back, and RSS got synked, it did not try to re-search for the movie.

### Environment

```markdown
- OS: https://github.com/linuxserver/docker-radarr/tree/master
- Radarr: radarr:5.11.0
- Docker Install: yes
- Using Reverse Proxy: no
- Database: sqlite-libs-3.45.3-r1
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

I am sorry but I was not able to reproduce the issue with the trace logs enabled. But I keep on trying.
[radarr.trace.txt](https://github.com/user-attachments/files/17403589/radarr.trace.txt)

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
https://wiki.servarr.com/radarr/faq#how-does-radarr-find-movies
