### ISSUE TITLE
Use Instance Name in PWA Manifest

### ISSUE THREAD

**Issue by Daviid-P** [Radarr/Radarr#10576]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Right now I have 2 instances of radarr one for 1080p and one for 4K content.

If I add both to my homescreen in android they both get the name "Radarr" making them indistinguishable.

### Describe the solution you'd like

Maybe we can have a setting called "Rename PWA" and a button "Regenerate manifest.json"?

### Describe alternatives you've considered

Manually editing the manifest.json file once installed 

### Anything else?

No

**Comment by Daviid-P** [comment]
I edited `/opt/Sonarr/UI/Content/manifest.json` on Sonarr and it worked.

Sadly I can't find the manifest file in Radarr.

I'm using tteck's LXC script.

**Comment by bakerboy448** [comment]
@markus101 upstream thoughts on using instance name?  If even possible?

**Comment by bakerboy448** [comment]
https://github.com/Radarr/Radarr/commit/10e39641118ea98fefb66d312fc91d5c32d2426d
