### ISSUE TITLE
[FIX] For unmtached movies places in correct folders 

### ISSUE THREAD

**Issue by ajkis** [Radarr/Radarr#1057]
Due some bugs in previous versions some movies were not matched.
I made simple script to fix those.
https://github.com/ajkis/scripts/blob/master/radarr/radarr-fixunmatched.sh

**Comment by hotio** [comment]
Perhaps add this to the Wiki too...?

**Comment by galli-leo** [comment]
@ajkis `UPDATE Movies SET MovieFileId = (SELECT Id FROM MovieFiles WHERE Movies.Id == MovieFiles.MovieId) WHERE MovieFileId != (SELECT Id FROM MovieFiles WHERE Movies.Id == MovieFiles.MovieId)` I think this could be even better, since it will update wrongly matched files.

**Comment by galli-leo** [comment]
This is now run every 24 hours.
