### ISSUE TITLE
Radarr Has Trouble Choosing Same Movie Titles With Different Years

### ISSUE THREAD

**Issue by okiwoki** [Radarr/Radarr#1058]
**Description:**

Radarr seems to have trouble downloading movie titles that share the same name but have were released in different years.

Example would be Casanova released in 2005 (Radarr will go out and download an older version) and Ghost in the Shell (soon to be released) where it will download the older anime version, not paying attention to the year. 

**Radarr Version:**

0.2.0.453

**Logs:**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by onedr0p** [comment]
What indexer(s) are you using? They more than likely don't support searching by imdbid.

**Comment by galli-leo** [comment]
Even after deliberately removing all code making sure Radarr only searches for Movies with correct title and year, Radarr still rejects movies with different years. So you probably have something terribly wrong with your config.

**Comment by Sparh4wk** [comment]
have the same problem with Ghost in the Shell (2017) Im using PTP indexer.. yet it downloading older version. have latest radarr installed.

**Comment by galli-leo** [comment]
@Sparh4wk What was the exact release name as appearing on PTP of that Torrent?

**Comment by Sparh4wk** [comment]
@galli-leo 

one was Ghost.in.the.Shell.1995.1080p.BluRay.FLAC.x264-Section9
second was Ghost in The Shell 1995 1080p Remux Blu-Ray AVC DTS DTS-MA - BluDragon
