### ISSUE TITLE
Calendar link doesn't work

### ISSUE THREAD

**Issue by ksbansal** [Radarr/Radarr#1059]
**Description:**
ical link doesn't work.

Provide a description of the feature request or bug here, the more details the better. 
Please also try to include the following if you are reporting a bug

**Radarr Version:**
0.2.0.453
**Logs:**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by onedr0p** [comment]
This is a duplicate issue.
