### ISSUE TITLE
Shorter Refresh Rate on Import Lists

### ISSUE THREAD

**Issue by rjcogin** [Radarr/Radarr#10612]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

-

### Describe the solution you'd like

I would love a shorter refresh rate on Import Lists.
Particularly custom lists.

### Describe alternatives you've considered

There used to be an option where you could set the interval. but I can no longer find it.

### Anything else?

-

**Comment by bakerboy448** [comment]
Dupe
No plans

**Comment by bakerboy448** [comment]
https://wiki.servarr.com/radarr/faq#why-are-lists-sync-times-so-long-and-can-i-change-it
