### ISSUE TITLE
Inconsistency on resources with * in name

### ISSUE THREAD

**Issue by sbe-arg** [Radarr/Radarr#10624]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

![image](https://github.com/user-attachments/assets/a327c580-36a9-48d4-b48b-a8a85b833c9f)

![image](https://github.com/user-attachments/assets/c5d5b308-db22-409a-85dc-fdeb5d9cfee7)

![image](https://github.com/user-attachments/assets/fe8f3e03-10be-44a1-bdcf-1681d3e7e35f)

### Expected Behavior

If was able to find the torrent it should be able to figure out that files and directories with * are invalid and try something else to find them?

### Steps To Reproduce

try to get any content with a wildcard in title

### Environment

```markdown
irrelevant
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

not applicable
it is not a permissions issue is a condition for character replacement

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
invalid bug report - no information provided, no logs provided.

Download client paths come from the download client.

**Comment by sbe-arg** [comment]
But why cannot find the movie file in the download client? Because there is no wildcard in the file name match.

The problem is the match between download client and movie folder paths.

Test this.

**Comment by bakerboy448** [comment]
> But why cannot find the movie file in the download client? Because there is no wildcard in the file name match.

You've provided no logs to prove this. Radarr relies on the path the download client reports.

> The problem is the match between download client and movie folder paths.

A movie's assigned folder in radarr has nothing to do with where your download client downloads to, the name of the folder your download client names the download, or anything relating to the issue described.

This GitHub issue is 100% not a bug report and invalid.

For support and inquiries, please use our [Discord](http://radarr.video/discord) channel. GitHub is designated solely for bug reports and feature requests. It seems that this issue may fall under a support request, so we kindly ask you to visit our Discord for assistance. Thank you.
