### ISSUE TITLE
[Request] On /movieeditor provide a way to select all

### ISSUE THREAD

**Issue by eriksneff** [Radarr/Radarr#1064]
**Description:**

Right now, there's no quick way to select all items through pagination. You have to simply paginate, select all, paginate, select all. 

FYI - the reason I had to do this was to force the hundreds of movies I added to use the custom quality profile I made. So, that might be a separate thing to consider - being able to specify a default quality profile and a bulk apply this profile to everything button, all from the settings area. If that had been present, I wouldn't have been looking in the /movieeditor page in the first place. Just a thought!

**Radarr Version:**

Radarr Version: 0.2.0.453
Mono Version 4.6.1 (mono-4.6.0-branch-c8sr0/abb06f1 Fri Sep 23 19:24:23 EDT 2016)

**Comment by fryfrog** [comment]
You *can* crank up the number of movies per page, which is helpful... but I agree, having a *real* select all would be nice.

You should make a feature request at feathub.com/Radarr/Radarr

**Comment by geogolem** [comment]
Im going to close this issue off --> as I consider it the same/related to: https://github.com/Radarr/Radarr/issues/1025

**Comment by geogolem** [comment]
please see the comments in https://github.com/Radarr/Radarr/issues/1025 where you could way in as to how this should be implemented.
