### ISSUE TITLE
Radarr: update is failing (version `GLIBC_2.27' not found)

### ISSUE THREAD

**Issue by woutercoppens** [Radarr/Radarr#10653]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Launching the update from within Radarr is failing

### Expected Behavior

Update should succeed

### Steps To Reproduce

Launch update from within Radarr

### Environment

```markdown
- OS: Synololgy DSM 7.1.1-42962 Update 5
- Radarr: 5.14.0.9383
- Docker Install: No

Version 5.11.0.9244
Package Version armv7-7.1_20231118-21 by Team Radarr
.NET Yes (6.0.32)
Database Sqlite 3.34.1
Database Migration 239
AppData Directory /volume1/@appdata/radarr/.config/Radarr
Startup Directory /volume1/@appstore/radarr/share/Radarr/bin
Mode Console
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

2024-11-07 09:40:50.6|Info|InstallUpdateService|Downloading update 5.14.0.9383
2024-11-07 09:41:02.7|Info|InstallUpdateService|Verifying update package
2024-11-07 09:41:04.3|Info|InstallUpdateService|Update package verified successfully
2024-11-07 09:41:04.3|Info|InstallUpdateService|Extracting Update package
2024-11-07 09:41:37.5|Info|InstallUpdateService|Update package extracted successfully
2024-11-07 09:41:37.6|Info|BackupService|Starting Backup
2024-11-07 09:41:43.1|Info|InstallUpdateService|Preparing client
2024-11-07 09:41:48.4|Info|InstallUpdateService|Starting update client /volume1/@apptemp/radarr/radarr_update/Radarr.Update
2024-11-07 09:41:48.4|Info|InstallUpdateService|Radarr will restart shortly.
2024-11-07 09:41:48.9|Error|Radarr.Update|Failed to load /volume1/@apptemp/radarr/radarr_update/libcoreclr.so, error: /lib/libm.so.6: version `GLIBC_2.27' not found (required by /volume1/@apptemp/radarr/radarr_update/libcoreclr.so)

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by mreid-tt** [comment]
Hi Radarr team,

I believe this may indeed be a bug. After investigating [SynoCommunity issue #6309](https://github.com/SynoCommunity/spksrc/issues/6309), it appears that the upgrade from Radarr 5.11.0.9244 (which includes .NET 6.0.32) to Radarr 5.14.0.9383 (with .NET 6.0.35) could be causing problems specifically on ARMv7 CPUs. I've tested the upgrade on an x86_64 platform where it runs without any issues, so this may be related to differences in the libraries bundled for ARMv7.

The .NET release notes reference a feedback thread on the version following the last working build ([.NET issue #9447](https://github.com/dotnet/core/issues/9447)), and [this comment](https://github.com/dotnet/core/issues/9447#issuecomment-2299001398) appears to confirm the issue on ARMv7.

> I know Debian 9 (armhf) is not supported anymore, but since version 6.0.33 starting an application results in a segmentation fault.
> ```
> Failed to load /usr/share/dotnet/shared/Microsoft.NETCore.App/6.0.33/libcoreclr.so, error: /lib/arm-linux-gnueabihf/libm.so.6: version `GLIBC_2.27' not found (required by /usr/share/dotnet/shared/Microsoft.NETCore.App/6.0.33/libcoreclr.so)
> Segmentation fault
> ```
> I didn't expect breaking changes like these in LTS versions, even if the OS is not supported anymore.

This suggests there may be a breaking change introduced starting from .NET 6.0.33.

**Comment by bakerboy448** [comment]
Upstream track https://github.com/dotnet/runtime/issues/109739

**Comment by bakerboy448** [comment]
The plan is to move to dotnet 8 in the near future. Which I believe also comes with platform support changes.  Cc @mynameisbogdan for additional commentary

**Comment by mreid-tt** [comment]
@mynameisbogdan, really appreciate this. I've gone ahead and packaged it for Synology as a [pre-release](https://github.com/mreid-tt/spksrc/releases/tag/Radarr_6.0.0.9927). I've deployed on my system as a test and it works well:

<img width="498" alt="Image" src="https://github.com/user-attachments/assets/476321f3-9967-4e48-8eea-b1395d639642" />

Now awaiting the target users on ARMv7 to provide feedback.

**Comment by mreid-tt** [comment]
Hey @mynameisbogdan, the last test version you provided worked successfully on the Synology ARMv7 platform. This looks like a viable path forward to ensure future updates reach those users.

**Comment by mreid-tt** [comment]
Hey @mynameisbogdan, do you think we can go ahead and close the upstream ticket at this point? The Microsoft team has requested closure.

**Comment by woutercoppens** [comment]
What is for now the way forward? I uninstall this test version and go back to the old version of synocommunity?

**Comment by woutercoppens** [comment]
In both scenario's I won't receive any updates until Radarr 6 is released?

**Comment by mreid-tt** [comment]
> In both scenario's I won't receive any updates until Radarr 6 is released?

That's my interpretation of the current state of things. @mynameisbogdan will have to confirm.

**Comment by mreid-tt** [comment]
> I'm willing to maintain some custom builds with a downgrade version of dotnet for Synology if you're interested.

I appreciate the effort, but I'm not sure maintaining custom builds is worthwhile. From what I understand, the internal updater will still target the standard releases, which means updates will continue to fail unless we re-release each version to the repository. Historically, we haven’t maintained apps this way, especially since our update cadence doesn’t align with projects that release frequently. Given that, maintaining custom builds solely for ARMv7 users doesn’t seem like a sustainable approach.

**Comment by woutercoppens** [comment]
How do I install v6.0.0.10217?

I changed the channel to develop (and even restarted Radarr). I can see v6.0.0.10217 in the available updates but when I clikc on install latest, it always downloads v5.28.0.10205.

**Comment by ben63vw** [comment]
I'm having this issue now with Radarr 6.0.3.10276 that has .NET 8.0.12 installed and running on a Qnap TVS-682 which is running an Intel x86 CPU.  I'm on the develop update channel and it shows that 6.1.0.10293 update is available but I get errors for GLIBC_2.34 and GLIBC_2.35 not found when trying to update from within Radarr.  I've attached my log file.

[radarr.txt](https://github.com/user-attachments/files/24041925/radarr.txt)

**Comment by mynameisbogdan** [comment]
FYI .NET got bumped to 8.0.27 in nightly.

559a2980c360473a9e017f37669cd5e300657cb8
