### ISSUE TITLE
(feature request) balance data with multiple disks

### ISSUE THREAD

**Issue by lknite** [Radarr/Radarr#10658]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Given two network disks:
- older /data1 with 20TB
- newer /data2 with 64TB

When adding a new movie, you pretty much just default to /data2, but this leads to /data1 not really being used.

It's hard to keep track of which disk to use next.

### Describe the solution you'd like

Instead of defaulting to /data2, I'd like it to default to "managed", and have radarr decide automatically for me which disk to use so that new data gets evenly spread across available media shares.

Some use cases might be:
- one share is faster so prefer to use it if less than 70% is used, otherwise use both disks evenly
- keep the same % free on each share, so they both are always approximately the same percentage full
- at some point you could mark a share as 'out' and radarr would move all the movies off it to the other available disks

Alternatively, a nightly maintenance task could be setup to move things around during a scheduled window to restore balanced usage.

### Describe alternatives you've considered

I try to use one for movies and one for tv shows, but really I'm not good at managing the space between the two, and as one tends to get full I then move some things over via the gui, a pretty slow process.

### Anything else?

Would be good to implement the same feature in sonarr.

**Comment by bakerboy448** [comment]
No plans to automatic root folder selecting.

users should explore merge file systems / OSes that would accomplish this.
For support and inquiries, please use our [Discord](http://radarr.video/discord) channel.
