### ISSUE TITLE
After adding a movie, Radarr crashes

### ISSUE THREAD

**Issue by kingwoftam** [Radarr/Radarr#1065]
**Description:**
After adding a movie - via the Add Movies button, then typing in a movie title and clicking add - Radarr crashes and requires a restart.

**Radarr Version:**
0.2.0.480 - running on Qnap

**Logs:**
Nothing in the logs of note:
17-3-8 10:19:39.4|Info|MovieService|Adding Movie [][Madagascar] Path: [/share/Multimedia/Movies/Animation Library/Dreamworks/Madagascar (2005)]
17-3-8 10:19:39.8|Info|MediaCoverService|Downloading Poster for [][Madagascar] http://image.tmdb.org/t/p/original/2YiESGB68BGQSAFvfJxBi774sc4.jpg
17-3-8 10:19:39.9|Info|RefreshMovieService|Updating Info for Madagascar
17-3-8 10:19:40.9|Info|DiskScanService|Scanning disk for Madagascar
17-3-8 10:19:40.9|Info|MovieScannedHandler|[Madagascar] was recently added, performing post-add actions
17-3-8 10:19:41.0|Info|MediaCoverService|Downloading Poster for [tt0351283][Madagascar] http://image.tmdb.org/t/p/original/2YiESGB68BGQSAFvfJxBi774sc4.jpg
17-3-8 10:19:41.1|Info|MediaCoverService|Downloading Banner for [tt0351283][Madagascar] http://image.tmdb.org/t/p/original/wUetiqu2EFhHW94yTP0pWABfyUG.jpg

17-3-8 10:22:20.8|Info|Bootstrap|Starting Radarr - /share/CE_CACHEDEV1_DATA/.qpkg/Radarr/Radarr/Radarr.exe - Version 0.2.0.480
17-3-8 10:22:36.8|Info|MigrationLogger|*** Migrating data source=/share/CE_CACHEDEV1_DATA/.qpkg/Radarr/Home/.config/Radarr/nzbdrone.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
17-3-8 10:22:37.3|Info|MigrationLogger|*** Migrating data source=/share/CE_CACHEDEV1_DATA/.qpkg/Radarr/Home/.config/Radarr/logs.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
17-3-8 10:22:37.5|Info|Router|Application mode: Interactive
17-3-8 10:22:37.5|Info|OwinHostController|Listening on the following URLs:
17-3-8 10:22:37.5|Info|OwinHostController|  http://*:7878/
17-3-8 10:22:38.0|Info|NancyBootstrapper|Starting NzbDrone API

**Comment by kingwoftam** [comment]
The gap between the Downloading Banner log entry and starting Radarr is the crash and me restarting Radarr

**Comment by onedr0p** [comment]
Hm, you need to enable trace logging and try to capture it again.

**Comment by SWu** [comment]
Same issue with latest nightly, running on a synology NAS.

Radarr crashes every time it updates the database---which is every couple of seconds because after the update it's trying to update the db for every entry in my movie list.

I'll try to get it to stay alive long enough to turn on trace debugging, but it's basically unusable for me right now :(

**Comment by SWu** [comment]
This is the only exception I see in the trace log:
`17-3-7 20:37:27.1|Trace|DiskProviderBase|Deleting file: /usr/local/radarr/var/.config/Radarr/MediaCover/14/poster.jpg
17-3-7 20:37:27.1|Info|MediaCoverService|Downloading Poster for [tt0144084][American Psycho] http://image.tmdb.org/t/p/original/qXsylPM4Lr5397R3eHrfqHhTUNc.jpg
17-3-7 20:37:27.1|Debug|HttpClient|Downloading [http://image.tmdb.org/t/p/original/qXsylPM4Lr5397R3eHrfqHhTUNc.jpg] to [/usr/local/radarr/var/.config/Radarr/MediaCover/14/poster.jpg]
17-3-7 20:37:27.1|Trace|HttpClient|Req: [GET] https://api.themoviedb.org/3/movie/109443?api_key=1a7373301961d03f97f853a876dd1212&append_to_response=alternative_titles%2Crelease_dates%2Cvideos&language=EN
17-3-7 20:37:27.1|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
17-3-7 20:37:27.1|Trace|Http|Req: 62 [GET] /api/log/file/update
17-3-7 20:37:27.1|Debug|GlobalExceptionHandlers|Minor Fail: The type initializer for 'System.Drawing.GDIPlus' threw an exception.

[v0.2.0.484] System.TypeInitializationException: The type initializer for 'System.Drawing.GDIPlus' threw an exception. ---> System.DllNotFoundException: libgdiplus.so.0
  at (wrapper managed-to-native) System.Drawing.GDIPlus:GdiplusStartup (ulong&,System.Drawing.GdiplusStartupInput&,System.Drawing.GdiplusStartupOutput&)
  at System.Drawing.GDIPlus..cctor () [0x000cc] in /spksrc/native/mono/work-native/mono-4.6.2/mcs/class/System.Drawing/System.Drawing/gdipFunctions.cs:119 
   --- End of inner exception stack trace ---
  at (wrapper managed-to-native) System.Object:__icall_wrapper_mono_generic_class_init (intptr)
  at System.Drawing.Image.Dispose (System.Boolean disposing) [0x00000] in /spksrc/native/mono/work-native/mono-4.6.2/mcs/class/System.Drawing/System.Drawing/Image.cs:794 
  at System.Drawing.Image.Finalize () [0x00000] in /spksrc/native/mono/work-native/mono-4.6.2/mcs/class/System.Drawing/System.Drawing/Image.cs:789 
`

**Comment by SWu** [comment]
I think it's a regression from this commit: https://github.com/Radarr/Radarr/pull/835/files

IsValidGDIPlusImage was moved, but didn't preserve the dll check block:

```
try {
    GdiPlusInterop.CheckGdiPlus();
    //[...]
}
catch (DllNotFoundException ex) {
    _logger.Error(ex, "Could not find libgdiplus. Cannot test if image is corrupt.");
    return true;
}
```

**Comment by levijay** [comment]
I am having the same issue as SWu with both latest release and nightly - I'm on a Synology NAS also

**Comment by kingwoftam** [comment]
Glad SWu commented and provided information

**Comment by WebBuddha** [comment]
Same for me. Radarr runs a few seconds after start and shows following errormessage in the trace log:
`17-3-8 10:10:05.5|Debug|GlobalExceptionHandlers|Minor Fail: The type initializer for 'System.Drawing.GDIPlus' threw an exception.

[v0.2.0.484] System.TypeInitializationException: The type initializer for 'System.Drawing.GDIPlus' threw an exception. ---> System.DllNotFoundException: libgdiplus.so.0
  at (wrapper managed-to-native) System.Drawing.GDIPlus:GdiplusStartup (ulong&,System.Drawing.GdiplusStartupInput&,System.Drawing.GdiplusStartupOutput&)
  at System.Drawing.GDIPlus..cctor () [0x000cc] in /spksrc/native/mono/work-native/mono-4.6.2/mcs/class/System.Drawing/System.Drawing/gdipFunctions.cs:119
   --- End of inner exception stack trace ---
  at (wrapper managed-to-native) System.Object:__icall_wrapper_mono_generic_class_init (intptr)
  at System.Drawing.Image.Dispose (System.Boolean disposing) [0x00000] in /spksrc/native/mono/work-native/mono-4.6.2/mcs/class/System.Drawing/System.Drawing/Image.cs:794
  at System.Drawing.Image.Finalize () [0x00000] in /spksrc/native/mono/work-native/mono-4.6.2/mcs/class/System.Drawing/System.Drawing/Image.cs:789
`

**Comment by Lagrik** [comment]
Same issue for me.  Radarr crashes when adding a movie as well on Synology.  It also happens every time I Click Update Library.  I have to ssh into my NAS and do a rm -RF /usr/local/radarr/var/.config/Radarr/MediaCover.  After that, Radarr no longer crashes but after several hours, Radarr starts crashing again when the library is updated or adding a new movie.

Only started happening sometime in the last couple of days.

**Comment by Lagrik** [comment]
Just updated to the latest nightly (0.2.0.516) and looks like this is resolved.  I can now add movies and Update Library and no more crashes.  Thank you team!

**Comment by WebBuddha** [comment]
Just updated also to nightly 0.2.0.516 and it looks fine at the moment. Thanks for your work.
