### ISSUE TITLE
Unable to add Usenet indexers

### ISSUE THREAD

**Issue by jneljeff** [Radarr/Radarr#1066]
**Description:**

Unable to add Usenet indexers.  Cannot connect to any indexer including NZB Hydra.  Testing Failed

**Radarr Version:**

0.2.0.453

**Logs:**

None generated

**Comment by onedr0p** [comment]
This is prolly on your end, make sure you have the correct port, host and apikey. Works here..

**Comment by jneljeff** [comment]
Fresh install after troubleshooting last issue.  Was working before with
all outgoing ports open.  Sonarr works using exact same info.  Torrents
work.  This is only usenet indexers added since update.

**Comment by onedr0p** [comment]
Just added a new one with newznab, with my hydra settings and it's working here. Maybe check your logs in Radarr???

**Comment by jneljeff** [comment]
As I mentioned in the ticket, no new logs were generated by the action.
Everything else (so far) seems to behave normally.  I guess I'll blow it
all out again and hope for the best.

**Comment by fryfrog** [comment]
Try cranking log level up to debug or trace and `tail` those files for details.

**Comment by jneljeff** [comment]
I captured the logs as you suggested, but I don't see anything about the action I'm performing in the logs.

Set log to debug and all i get is this:

`17-3-7 19:07:33.1|Debug|Api|[GET] /api/log/file: 200.OK (1 ms)
17-3-7 19:07:34.9|Debug|Api|[GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc&filterType=equal: 200.OK (6 ms)
17-3-7 19:07:36.7|Debug|Api|[POST] /api/command: 201.Created (18 ms)
17-3-7 19:07:36.8|Info|Database|Vacuuming Log database
17-3-7 19:07:36.8|Info|Database|Log database compressed
17-3-7 19:07:37.2|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (5 ms)
17-3-7 19:07:37.2|Debug|Api|[GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc&filterType=equal: 200.OK (10 ms)
17-3-7 19:07:37.3|Debug|Api|[GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc&filterType=equal: 200.OK (6 ms)
17-3-7 19:07:37.3|Debug|Api|[GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc&filterType=equal: 200.OK (5 ms)
17-3-7 19:07:40.6|Debug|Api|[GET] /api/config/mediamanagement: 200.OK (38 ms)
17-3-7 19:07:40.6|Debug|Api|[GET] /api/config/indexer: 200.OK (24 ms)
17-3-7 19:07:40.6|Debug|Api|[GET] /api/config/naming: 200.OK (39 ms)
17-3-7 19:07:40.8|Debug|Api|[GET] /api/config/downloadclient: 200.OK (5 ms)
17-3-7 19:07:40.8|Debug|Api|[GET] /api/notification: 200.OK (15 ms)
17-3-7 19:07:40.8|Debug|Api|[GET] /api/config/host: 200.OK (12 ms)
17-3-7 19:07:40.8|Debug|Api|[GET] /api/config/ui: 200.OK (1 ms)
17-3-7 19:07:40.9|Debug|Api|[GET] /api/config/netimport: 200.OK (5 ms)
17-3-7 19:07:41.1|Debug|Api|[GET] /api/profile: 200.OK (8 ms)
17-3-7 19:07:41.2|Debug|Api|[GET] /api/delayprofile: 200.OK (24 ms)
17-3-7 19:07:41.2|Debug|Api|[GET] /api/qualitydefinition: 200.OK (22 ms)
17-3-7 19:07:41.2|Debug|Api|[GET] /api/config/naming/samples?renameEpisodes=true&replaceIllegalCharacters=true&standardMovieFormat=%7BMovie+Title%7D+(%7BRelease+Year%7D)+%7BQuality+Full%7D&movieFolderFormat=%7BMovie+Title%7D+(%7BRelease+Year%7D)&multiEpisodeStyle=0&includeSeriesTitle=false&includeEpisodeTitle=false&includeQuality=false&replaceSpaces=false&id=1: 200.OK (106 ms)
17-3-7 19:07:41.3|Debug|Api|[GET] /api/indexer: 200.OK (53 ms)
17-3-7 19:07:41.3|Debug|Api|[GET] /api/Restriction: 200.OK (13 ms)
17-3-7 19:07:41.4|Debug|Api|[GET] /api/downloadclient: 200.OK (9 ms)
17-3-7 19:07:41.4|Debug|Api|[GET] /api/remotePathMapping: 200.OK (8 ms)
17-3-7 19:07:41.5|Debug|Api|[GET] /api/netimport: 200.OK (25 ms)
17-3-7 19:07:41.5|Debug|Api|[GET] /api/rootfolder: 200.OK (24 ms)
17-3-7 19:07:41.6|Debug|Api|[GET] /api/metadata: 200.OK (45 ms)
17-3-7 19:07:44.2|Debug|Api|[GET] /api/indexer/schema: 200.OK (134 ms)
17-3-7 19:08:05.6|Debug|Api|[GET] /api/health: 200.OK (4 ms)
17-3-7 19:08:05.7|Debug|Api|[GET] /api/diskspace: 200.OK (43 ms)
17-3-7 19:08:05.8|Debug|Api|[GET] /api/health: 200.OK (1 ms)
17-3-7 19:08:05.9|Debug|Api|[GET] /api/diskspace: 200.OK (35 ms)
17-3-7 19:08:07.0|Debug|Api|[GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc&filterType=equal: 200.OK (7 ms)
17-3-7 19:08:07.1|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (4 ms)
17-3-7 19:08:07.2|Debug|Api|[GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc&filterType=equal: 200.OK (12 ms)
17-3-7 19:08:08.5|Debug|Api|[GET] /api/log/file: 200.OK (5 ms)`

Trace level give me this:
`17-3-7 19:13:04.2|Trace|DiskProviderBase|Deleting file: /config/logs/radarr.txt
17-3-7 19:13:04.2|Trace|CommandQueueManager|Updating command status
17-3-7 19:13:04.2|Trace|EventAggregator|Publishing CommandUpdatedEvent
17-3-7 19:13:04.2|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
17-3-7 19:13:04.2|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
17-3-7 19:13:04.2|Trace|EventAggregator|Publishing CommandExecutedEvent
17-3-7 19:13:04.2|Trace|EventAggregator|CommandExecutedEvent -> TaskManager
17-3-7 19:13:04.2|Trace|EventAggregator|CommandExecutedEvent <- TaskManager
17-3-7 19:13:04.2|Trace|EventAggregator|CommandExecutedEvent -> TaskModule
17-3-7 19:13:04.2|Trace|EventAggregator|CommandExecutedEvent <- TaskModule
17-3-7 19:13:04.2|Trace|CommandExecutor|DeleteLogFilesCommand <- DeleteLogFilesService [00:00:00.0110750]
17-3-7 19:13:04.6|Trace|Http|Req: 22 [GET] /api/log/file
17-3-7 19:13:04.6|Trace|Http|Res: 22 [GET] /api/log/file: 200.OK (2 ms)
17-3-7 19:13:04.6|Debug|Api|[GET] /api/log/file: 200.OK (2 ms)
17-3-7 19:13:04.7|Trace|Http|Req: 23 [GET] /api/log/file/radarr.trace.txt
17-3-7 19:13:04.7|Trace|Http|Res: 23 [GET] /api/log/file/radarr.trace.txt: 200.OK (1 ms)
17-3-7 19:13:04.7|Debug|Api|[GET] /api/log/file/radarr.trace.txt: 200.OK (1 ms)
17-3-7 19:13:12.1|Trace|Http|Req: 24 [GET] /api/config/mediamanagement
17-3-7 19:13:12.1|Trace|Http|Req: 25 [GET] /api/config/naming
17-3-7 19:13:12.1|Trace|ConfigService|Using default config value for 'recyclebin' defaultValue:''
17-3-7 19:13:12.1|Trace|ConfigService|Using default config value for 'autodownloadpropers' defaultValue:'True'
17-3-7 19:13:12.1|Trace|ConfigService|Using default config value for 'createemptyseriesfolders' defaultValue:'False'
17-3-7 19:13:12.1|Trace|ConfigService|Using default config value for 'filedate' defaultValue:'None'
17-3-7 19:13:12.1|Trace|ConfigService|Using default config value for 'setpermissionslinux' defaultValue:'False'
17-3-7 19:13:12.1|Trace|ConfigService|Using default config value for 'filechmod' defaultValue:'0644'
17-3-7 19:13:12.1|Trace|ConfigService|Using default config value for 'folderchmod' defaultValue:'0755'
17-3-7 19:13:12.1|Trace|ConfigService|Using default config value for 'chownuser' defaultValue:''
17-3-7 19:13:12.1|Trace|ConfigService|Using default config value for 'chowngroup' defaultValue:''
17-3-7 19:13:12.1|Trace|ConfigService|Using default config value for 'skipfreespacecheckwhenimporting' defaultValue:'False'
17-3-7 19:13:12.1|Trace|ConfigService|Using default config value for 'copyusinghardlinks' defaultValue:'True'
17-3-7 19:13:12.1|Trace|ConfigService|Using default config value for 'extrafileextensions' defaultValue:''
17-3-7 19:13:12.1|Trace|ConfigService|Using default config value for 'enablemediainfo' defaultValue:'True'
17-3-7 19:13:12.1|Trace|Http|Req: 26 [GET] /api/config/indexer
17-3-7 19:13:12.1|Trace|ConfigService|Using default config value for 'minimumage' defaultValue:'0'
17-3-7 19:13:12.1|Trace|ConfigService|Using default config value for 'retention' defaultValue:'0'
17-3-7 19:13:12.1|Trace|ConfigService|Using default config value for 'rsssyncinterval' defaultValue:'60'
17-3-7 19:13:12.1|Trace|ConfigService|Using default config value for 'availabilitydelay' defaultValue:'0'
17-3-7 19:13:12.1|Trace|Http|Res: 24 [GET] /api/config/mediamanagement: 200.OK (31 ms)
17-3-7 19:13:12.1|Debug|Api|[GET] /api/config/mediamanagement: 200.OK (31 ms)
17-3-7 19:13:12.1|Trace|Http|Res: 26 [GET] /api/config/indexer: 200.OK (10 ms)
17-3-7 19:13:12.1|Debug|Api|[GET] /api/config/indexer: 200.OK (10 ms)
17-3-7 19:13:12.2|Trace|Http|Res: 25 [GET] /api/config/naming: 200.OK (40 ms)
17-3-7 19:13:12.2|Debug|Api|[GET] /api/config/naming: 200.OK (40 ms)
17-3-7 19:13:12.3|Trace|Http|Req: 27 [GET] /api/config/downloadclient
17-3-7 19:13:12.3|Trace|ConfigService|Using default config value for 'downloadedepisodesfolder' defaultValue:''
17-3-7 19:13:12.3|Trace|ConfigService|Using default config value for 'downloadclientworkingfolders' defaultValue:'_UNPACK_|_FAILED_'
17-3-7 19:13:12.3|Trace|ConfigService|Using default config value for 'downloadedepisodesscaninterval' defaultValue:'0'
17-3-7 19:13:12.3|Trace|ConfigService|Using default config value for 'removecompleteddownloads' defaultValue:'False'
17-3-7 19:13:12.3|Trace|ConfigService|Using default config value for 'autoredownloadfailed' defaultValue:'True'
17-3-7 19:13:12.3|Trace|ConfigService|Using default config value for 'removefaileddownloads' defaultValue:'True'
17-3-7 19:13:12.3|Trace|Http|Req: 28 [GET] /api/notification
17-3-7 19:13:12.3|Trace|Http|Res: 27 [GET] /api/config/downloadclient: 200.OK (8 ms)
17-3-7 19:13:12.3|Debug|Api|[GET] /api/config/downloadclient: 200.OK (8 ms)
17-3-7 19:13:12.3|Trace|Http|Req: 29 [GET] /api/config/host
17-3-7 19:13:12.3|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
17-3-7 19:13:12.3|Trace|ConfigService|Using default config value for 'proxytype' defaultValue:'Http'
17-3-7 19:13:12.3|Trace|ConfigService|Using default config value for 'proxyhostname' defaultValue:''
17-3-7 19:13:12.4|Trace|ConfigService|Using default config value for 'proxyport' defaultValue:'8080'
17-3-7 19:13:12.4|Trace|Http|Res: 28 [GET] /api/notification: 200.OK (48 ms)
17-3-7 19:13:12.4|Debug|Api|[GET] /api/notification: 200.OK (48 ms)
17-3-7 19:13:12.4|Trace|ConfigService|Using default config value for 'proxyusername' defaultValue:''
17-3-7 19:13:12.4|Trace|ConfigService|Using default config value for 'proxypassword' defaultValue:''
17-3-7 19:13:12.4|Trace|ConfigService|Using default config value for 'proxybypassfilter' defaultValue:''
17-3-7 19:13:12.4|Trace|ConfigService|Using default config value for 'proxybypasslocaladdresses' defaultValue:'True'
17-3-7 19:13:12.4|Trace|Http|Res: 29 [GET] /api/config/host: 200.OK (33 ms)
17-3-7 19:13:12.4|Debug|Api|[GET] /api/config/host: 200.OK (33 ms)
17-3-7 19:13:12.4|Trace|Http|Req: 30 [GET] /api/config/ui
17-3-7 19:13:12.4|Trace|ConfigService|Using default config value for 'firstdayofweek' defaultValue:'0'
17-3-7 19:13:12.4|Trace|ConfigService|Using default config value for 'calendarweekcolumnheader' defaultValue:'ddd M/D'
17-3-7 19:13:12.4|Trace|ConfigService|Using default config value for 'shortdateformat' defaultValue:'MMM D YYYY'
17-3-7 19:13:12.4|Trace|ConfigService|Using default config value for 'longdateformat' defaultValue:'dddd, MMMM D YYYY'
17-3-7 19:13:12.4|Trace|ConfigService|Using default config value for 'timeformat' defaultValue:'h(:mm)a'
17-3-7 19:13:12.4|Trace|ConfigService|Using default config value for 'showrelativedates' defaultValue:'True'
17-3-7 19:13:12.4|Trace|ConfigService|Using default config value for 'enablecolorimpairedmode' defaultValue:'False'
17-3-7 19:13:12.4|Trace|Http|Res: 30 [GET] /api/config/ui: 200.OK (3 ms)
17-3-7 19:13:12.4|Debug|Api|[GET] /api/config/ui: 200.OK (3 ms)
17-3-7 19:13:12.5|Trace|Http|Req: 31 [GET] /api/config/netimport
17-3-7 19:13:12.5|Trace|ConfigService|Using default config value for 'netimportsyncinterval' defaultValue:'60'
17-3-7 19:13:12.5|Trace|ConfigService|Using default config value for 'listsynclevel' defaultValue:'disabled'
17-3-7 19:13:12.5|Trace|ConfigService|Using default config value for 'importexclusions' defaultValue:''
17-3-7 19:13:12.5|Trace|ConfigService|Using default config value for 'traktauthtoken' defaultValue:''
17-3-7 19:13:12.5|Trace|ConfigService|Using default config value for 'traktrefreshtoken' defaultValue:''
17-3-7 19:13:12.5|Trace|ConfigService|Using default config value for 'trakttokenexpiry' defaultValue:'0'
17-3-7 19:13:12.5|Trace|Http|Res: 31 [GET] /api/config/netimport: 200.OK (9 ms)
17-3-7 19:13:12.5|Debug|Api|[GET] /api/config/netimport: 200.OK (9 ms)
17-3-7 19:13:12.7|Trace|Http|Req: 32 [GET] /api/config/naming/samples?renameEpisodes=true&replaceIllegalCharacters=true&standardMovieFormat=%7BMovie+Title%7D+(%7BRelease+Year%7D)+%7BQuality+Full%7D&movieFolderFormat=%7BMovie+Title%7D+(%7BRelease+Year%7D)&multiEpisodeStyle=0&includeSeriesTitle=false&includeEpisodeTitle=false&includeQuality=false&replaceSpaces=false&id=1
17-3-7 19:13:12.7|Trace|Http|Req: 33 [GET] /api/delayprofile
17-3-7 19:13:12.7|Trace|Http|Req: 34 [GET] /api/profile
17-3-7 19:13:12.7|Trace|Http|Res: 34 [GET] /api/profile: 200.OK (7 ms)
17-3-7 19:13:12.7|Debug|Api|[GET] /api/profile: 200.OK (7 ms)
17-3-7 19:13:12.7|Trace|Http|Res: 33 [GET] /api/delayprofile: 200.OK (40 ms)
17-3-7 19:13:12.7|Debug|Api|[GET] /api/delayprofile: 200.OK (40 ms)
17-3-7 19:13:12.8|Trace|Http|Res: 32 [GET] /api/config/naming/samples?renameEpisodes=true&replaceIllegalCharacters=true&standardMovieFormat=%7BMovie+Title%7D+(%7BRelease+Year%7D)+%7BQuality+Full%7D&movieFolderFormat=%7BMovie+Title%7D+(%7BRelease+Year%7D)&multiEpisodeStyle=0&includeSeriesTitle=false&includeEpisodeTitle=false&includeQuality=false&replaceSpaces=false&id=1: 200.OK (97 ms)
17-3-7 19:13:12.8|Debug|Api|[GET] /api/config/naming/samples?renameEpisodes=true&replaceIllegalCharacters=true&standardMovieFormat=%7BMovie+Title%7D+(%7BRelease+Year%7D)+%7BQuality+Full%7D&movieFolderFormat=%7BMovie+Title%7D+(%7BRelease+Year%7D)&multiEpisodeStyle=0&includeSeriesTitle=false&includeEpisodeTitle=false&includeQuality=false&replaceSpaces=false&id=1: 200.OK (97 ms)
17-3-7 19:13:12.9|Trace|Http|Req: 35 [GET] /api/qualitydefinition
17-3-7 19:13:12.9|Trace|Http|Res: 35 [GET] /api/qualitydefinition: 200.OK (6 ms)
17-3-7 19:13:12.9|Debug|Api|[GET] /api/qualitydefinition: 200.OK (6 ms)
17-3-7 19:13:12.9|Trace|Http|Req: 36 [GET] /api/indexer
17-3-7 19:13:12.9|Trace|Http|Req: 37 [GET] /api/Restriction
17-3-7 19:13:12.9|Trace|Http|Res: 37 [GET] /api/Restriction: 200.OK (14 ms)
17-3-7 19:13:12.9|Debug|Api|[GET] /api/Restriction: 200.OK (14 ms)
17-3-7 19:13:13.0|Trace|Http|Res: 36 [GET] /api/indexer: 200.OK (70 ms)
17-3-7 19:13:13.0|Debug|Api|[GET] /api/indexer: 200.OK (70 ms)
17-3-7 19:13:13.0|Trace|Http|Req: 38 [GET] /api/downloadclient
17-3-7 19:13:13.0|Trace|Http|Res: 38 [GET] /api/downloadclient: 200.OK (7 ms)
17-3-7 19:13:13.0|Debug|Api|[GET] /api/downloadclient: 200.OK (7 ms)
17-3-7 19:13:13.0|Trace|Http|Req: 39 [GET] /api/remotePathMapping
17-3-7 19:13:13.0|Trace|Http|Res: 39 [GET] /api/remotePathMapping: 200.OK (8 ms)
17-3-7 19:13:13.0|Debug|Api|[GET] /api/remotePathMapping: 200.OK (8 ms)
17-3-7 19:13:13.1|Trace|Http|Req: 40 [GET] /api/netimport
17-3-7 19:13:13.1|Trace|Http|Res: 40 [GET] /api/netimport: 200.OK (10 ms)
17-3-7 19:13:13.1|Debug|Api|[GET] /api/netimport: 200.OK (10 ms)
17-3-7 19:13:13.1|Trace|Http|Req: 41 [GET] /api/rootfolder
17-3-7 19:13:13.1|Trace|Http|Res: 41 [GET] /api/rootfolder: 200.OK (17 ms)
17-3-7 19:13:13.1|Trace|Http|Req: 42 [GET] /api/metadata
17-3-7 19:13:13.1|Debug|Api|[GET] /api/rootfolder: 200.OK (17 ms)
17-3-7 19:13:13.2|Trace|Http|Res: 42 [GET] /api/metadata: 200.OK (27 ms)
17-3-7 19:13:13.2|Debug|Api|[GET] /api/metadata: 200.OK (27 ms)
17-3-7 19:13:13.2|Trace|Http|Req: 43 [GET] /Content/zero.clipboard.swf?noCache=1488935593838
17-3-7 19:13:13.2|Trace|Http|Res: 43 [GET] /Content/zero.clipboard.swf?noCache=1488935593838: 200.OK (1 ms)
17-3-7 19:13:19.1|Trace|Http|Req: 44 [GET] /api/indexer/schema
17-3-7 19:13:19.1|Trace|Http|Res: 44 [GET] /api/indexer/schema: 200.OK (95 ms)
17-3-7 19:13:19.1|Debug|Api|[GET] /api/indexer/schema: 200.OK (95 ms)
17-3-7 19:13:20.0|Trace|Scheduler|Pending Tasks: 1
17-3-7 19:13:20.0|Trace|CommandQueueManager|Publishing CheckForFinishedDownload
17-3-7 19:13:20.0|Trace|CommandQueueManager|Checking if command is queued or started: CheckForFinishedDownload
17-3-7 19:13:20.0|Trace|CommandQueueManager|Inserting new command: CheckForFinishedDownload
17-3-7 19:13:20.0|Trace|CommandExecutor|CheckForFinishedDownloadCommand -> DownloadMonitoringService
17-3-7 19:13:20.0|Trace|CommandQueueManager|Marking command as started: CheckForFinishedDownload
17-3-7 19:13:20.0|Trace|EventAggregator|Publishing TrackedDownloadRefreshedEvent
17-3-7 19:13:20.0|Trace|EventAggregator|TrackedDownloadRefreshedEvent -> QueueService
17-3-7 19:13:20.0|Trace|EventAggregator|Publishing QueueUpdatedEvent
17-3-7 19:13:20.1|Trace|EventAggregator|QueueUpdatedEvent -> QueueModule
17-3-7 19:13:20.1|Trace|EventAggregator|QueueUpdatedEvent <- QueueModule
17-3-7 19:13:20.1|Trace|EventAggregator|TrackedDownloadRefreshedEvent <- QueueService
17-3-7 19:13:20.1|Trace|CommandQueueManager|Updating command status
17-3-7 19:13:20.1|Trace|EventAggregator|Publishing CommandExecutedEvent
17-3-7 19:13:20.1|Trace|EventAggregator|CommandExecutedEvent -> TaskManager
17-3-7 19:13:20.1|Trace|TaskManager|Updating last run time for: NzbDrone.Core.Download.CheckForFinishedDownloadCommand
17-3-7 19:13:20.1|Trace|EventAggregator|CommandExecutedEvent <- TaskManager
17-3-7 19:13:20.1|Trace|EventAggregator|CommandExecutedEvent -> TaskModule
17-3-7 19:13:20.1|Trace|EventAggregator|CommandExecutedEvent <- TaskModule
17-3-7 19:13:20.1|Trace|CommandExecutor|CheckForFinishedDownloadCommand <- DownloadMonitoringService [00:00:00.0216410]
17-3-7 19:13:20.2|Trace|Http|Req: 45 [GET] /api/queue?sort_by=timeleft&order=asc
17-3-7 19:13:20.2|Trace|Http|Res: 45 [GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (5 ms)
17-3-7 19:13:20.2|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (5 ms)
17-3-7 19:13:32.9|Trace|Http|Req: 46 [GET] /api/indexer/schema
17-3-7 19:13:32.9|Trace|Http|Res: 46 [GET] /api/indexer/schema: 200.OK (15 ms)
17-3-7 19:13:32.9|Debug|Api|[GET] /api/indexer/schema: 200.OK (15 ms)
17-3-7 19:13:50.0|Trace|Scheduler|Pending Tasks: 1
17-3-7 19:13:50.0|Trace|CommandQueueManager|Publishing CheckForFinishedDownload
17-3-7 19:13:50.0|Trace|CommandQueueManager|Checking if command is queued or started: CheckForFinishedDownload
17-3-7 19:13:50.0|Trace|CommandQueueManager|Inserting new command: CheckForFinishedDownload
17-3-7 19:13:50.0|Trace|CommandExecutor|CheckForFinishedDownloadCommand -> DownloadMonitoringService
17-3-7 19:13:50.0|Trace|CommandQueueManager|Marking command as started: CheckForFinishedDownload
17-3-7 19:13:50.1|Trace|EventAggregator|Publishing TrackedDownloadRefreshedEvent
17-3-7 19:13:50.1|Trace|EventAggregator|TrackedDownloadRefreshedEvent -> QueueService
17-3-7 19:13:50.1|Trace|EventAggregator|Publishing QueueUpdatedEvent
17-3-7 19:13:50.1|Trace|EventAggregator|QueueUpdatedEvent -> QueueModule
17-3-7 19:13:50.1|Trace|EventAggregator|QueueUpdatedEvent <- QueueModule
17-3-7 19:13:50.1|Trace|EventAggregator|TrackedDownloadRefreshedEvent <- QueueService
17-3-7 19:13:50.1|Trace|CommandQueueManager|Updating command status
17-3-7 19:13:50.1|Trace|EventAggregator|Publishing CommandExecutedEvent
17-3-7 19:13:50.1|Trace|EventAggregator|CommandExecutedEvent -> TaskManager
17-3-7 19:13:50.1|Trace|TaskManager|Updating last run time for: NzbDrone.Core.Download.CheckForFinishedDownloadCommand
17-3-7 19:13:50.1|Trace|EventAggregator|CommandExecutedEvent <- TaskManager
17-3-7 19:13:50.1|Trace|EventAggregator|CommandExecutedEvent -> TaskModule
17-3-7 19:13:50.1|Trace|EventAggregator|CommandExecutedEvent <- TaskModule
17-3-7 19:13:50.1|Trace|CommandExecutor|CheckForFinishedDownloadCommand <- DownloadMonitoringService [00:00:00.0118140]
17-3-7 19:13:50.2|Trace|Http|Req: 47 [GET] /api/queue?sort_by=timeleft&order=asc
17-3-7 19:13:50.2|Trace|Http|Res: 47 [GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (7 ms)
17-3-7 19:13:50.2|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (7 ms)
17-3-7 19:13:59.7|Trace|Http|Req: 48 [GET] /api/health
17-3-7 19:13:59.7|Trace|Http|Req: 49 [GET] /api/diskspace
17-3-7 19:13:59.7|Trace|Http|Res: 48 [GET] /api/health: 200.OK (9 ms)
17-3-7 19:13:59.7|Debug|Api|[GET] /api/health: 200.OK (9 ms)
17-3-7 19:13:59.8|Trace|ConfigService|Using default config value for 'downloadedepisodesfolder' defaultValue:''
17-3-7 19:13:59.9|Trace|Http|Res: 49 [GET] /api/diskspace: 200.OK (131 ms)
17-3-7 19:13:59.9|Debug|Api|[GET] /api/diskspace: 200.OK (131 ms)
17-3-7 19:13:59.9|Trace|Http|Req: 50 [GET] /api/health
17-3-7 19:13:59.9|Trace|Http|Res: 50 [GET] /api/health: 200.OK (2 ms)
17-3-7 19:13:59.9|Debug|Api|[GET] /api/health: 200.OK (2 ms)
17-3-7 19:14:00.0|Trace|Http|Req: 51 [GET] /api/diskspace
17-3-7 19:14:00.0|Trace|ConfigService|Using default config value for 'downloadedepisodesfolder' defaultValue:''
17-3-7 19:14:00.1|Trace|Http|Res: 51 [GET] /api/diskspace: 200.OK (40 ms)
17-3-7 19:14:00.1|Debug|Api|[GET] /api/diskspace: 200.OK (40 ms)
17-3-7 19:14:02.7|Trace|Http|Req: 52 [GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc&filterType=equal
17-3-7 19:14:02.7|Trace|Http|Res: 52 [GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc&filterType=equal: 200.OK (11 ms)
17-3-7 19:14:02.7|Debug|Api|[GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc&filterType=equal: 200.OK (11 ms)
17-3-7 19:14:02.9|Trace|Http|Req: 53 [GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc&filterType=equal
17-3-7 19:14:02.9|Trace|Http|Res: 53 [GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc&filterType=equal: 200.OK (7 ms)
17-3-7 19:14:02.9|Debug|Api|[GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc&filterType=equal: 200.OK (7 ms)
17-3-7 19:14:05.2|Trace|Http|Req: 54 [GET] /api/log/file
17-3-7 19:14:05.2|Trace|Http|Res: 54 [GET] /api/log/file: 200.OK (12 ms)
17-3-7 19:14:05.2|Debug|Api|[GET] /api/log/file: 200.OK (12 ms)
17-3-7 19:14:05.4|Trace|Http|Req: 55 [GET] /api/log/file/radarr.trace.txt`

**Comment by fryfrog** [comment]
I'd suggest pastebin'ing this to make it easier to parse. Also, it helps to carefully coordinate your tail w/ your action so you can trim down the info. :)

**Comment by jneljeff** [comment]
Maybe I'm not understanding what you're looking for by using tail to cut down the logs to the last few lines/bytes.  These logs are the result of clearing the log files, and immediately attempting to add a usenet indexer with no other action after a fresh install.

Trace: http://pastebin.com/jna0jaJL
Debug: http://pastebin.com/9C630mgY

**Comment by jneljeff** [comment]
Alright, never-mind.  Rebooted the whole server for the 3rd time and it's magically cooperating.
