### ISSUE TITLE
.plexmatch Plex Metadata support

### ISSUE THREAD

**Issue by rEkCaRc1337** [Radarr/Radarr#10685]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Better matching for people who don't want ids in folder names.

### Describe the solution you'd like

For the ones of us that like clean looking dir structure like Linux ISO (2024) without imdb/tmdb ids and stuff, the .plexmatch solution is very good, this is already implemented in sonarr, so should be pretty simple to add here too?

### Describe alternatives you've considered

Only alternative would be to bite the bullet and use different names or run plexarr script all the time to fix matches.

### Anything else?

No, not really.

**Comment by bakerboy448** [comment]
Duplicate of https://github.com/Radarr/Radarr/issues/8141
