### ISSUE TITLE
Downloaded Movies only get partially moved to target directory; ending up with undesized/incomplete .mkv file (random size below 1 GB)

### ISSUE THREAD

**Issue by freaked1234** [Radarr/Radarr#10683]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Download via SABnzb finishes (different movies, same result every time)
Radarr parses files
Radarr is trying to move files
Copy process stops midway at random file size below 1 GB - ending up with a small/incomplate .mkv file

### Expected Behavior

Download via SABnzb finishes
Radarr parses files
Radarr is trying to move files
File is moved to destination completely

### Steps To Reproduce

1. Add Random Movie
2. Let Radarr handle search and download via SABnzb

### Environment

```markdown
- OS: Debian 12 bookworm
- Radarr: 5.14.0.9383
- Proxmox 8 LXC
- Using Reverse Proxy: NginX 
- Browser: not relevant
- Database: Sqlite 3.40.1

Radarr is using same LXC config as Sonarr (working)
Donwload path is on a Dataset on the NAS (NFS Share full access)
Target path is on a Dataset on the same NAS (NFS Share full access)
Confirmed permissions and access via shell (touch, delete, move, new and existing files)
Thought Jellyfin might interfere with the copy process; shut it down; no change
No other services access the library/target dir
Issue might have started with the latest update
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

[trace FreeMovie.txt](https://github.com/user-attachments/files/17779657/trace.FreeMovie.txt)
Movie in Question = FreeMovie (replace all was used)

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
And to hopefully save the discord support folks some time; most likely https://wiki.servarr.com/radarr/faq#why-can-radarr-not-see-my-files-on-a-remote-server

**Comment by freaked1234** [comment]
> And to hopefully save the discord support folks some time; most likely https://wiki.servarr.com/radarr/faq#why-can-radarr-not-see-my-files-on-a-remote-server

not...
