### ISSUE TITLE
Kometa Local Assets

### ISSUE THREAD

**Issue by miaLDN** [Radarr/Radarr#10690]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

#10059 and #10419  have been implemented without reference to Kometa’s local asset file naming requirements

### Describe the solution you'd like

Implement as per Kometa’s local media asset requirements 

Please refer here [Kometa Local Assets Requirements](https://kometa.wiki/en/latest/kometa/guides/assets/#requirements-and-configuration)

### Describe alternatives you've considered

I don’t use Radarr for anything other than a downloader.

### Anything else?

Strictly speaking `Kometa` has *two* local assets formats, and assets would normally not be in the media directory as been implemented here.

`ASSET_FOLDERS=(True|False)`

`ASSET_FOLDERS=True`

``` txt

config
├── config.yml
├── Movies.yml
├── TV Shows.yml
└── assets
    ├── The Lord of the Rings
    │   ├── poster.png
    │   └── background.png
    ├── The Lord of the Rings The Fellowship of the Ring (2001)
    │   ├── poster.png
    │   └── background.png
    ├── The Lord of the Rings The Two Towers (2002)
    │   ├── poster.png
    │   └── background.png
    ├── The Lord of the Rings The Return of the King (2003)
    │   ├── poster.png
    │   └── background.png
    ├── Star Wars (Animated)
    │   ├── poster.png
    │   └── background.png
    ├── Star Wars The Clone Wars
    │   ├── poster.png
    │   ├── background.png
    │   ├── Season00.png
    │   ├── Season01.png
    │   ├── Season02.png
    │   ├── Season03.png
    │   ├── Season04.png
    │   ├── Season05.png
    │   ├── Season06.png
    │   ├── Season07.png
    │   ├── S07E01.png
    │   ├── S07E02.png
    │   ├── S07E03.png
    │   ├── S07E04.png
    │   └── S07E05.png
    └── Star Wars Rebels
        ├── poster.png
        ├── background.png
        ├── Season01.png
        ├── Season01_background.png
        ├── Season02.png
        ├── Season02_background.png
        ├── Season03.png
        ├── Season03_background.png
        ├── Season04.png
        └── Season04_background.png
```

`ASSET_FOLDERS=False`

``` txt

config
├── config.yml
├── Movies.yml
├── TV Shows.yml
└── assets
    ├── The Lord of the Rings.png
    ├── The Lord of the Rings_background.png
    ├── The Lord of the Rings The Fellowship of the Ring (2001).png
    ├── The Lord of the Rings The Fellowship of the Ring (2001)_background.png
    ├── The Lord of the Rings The Two Towers (2002).png
    ├── The Lord of the Rings The Two Towers (2002)_background.png
    ├── The Lord of the Rings The Return of the King (2003).png
    ├── The Lord of the Rings The Return of the King (2003)_background.png
    ├── Star Wars (Animated).png
    ├── Star Wars (Animated)_background.png
    ├── Star Wars The Clone Wars.png
    ├── Star Wars The Clone Wars_background.png
    ├── Star Wars The Clone Wars_Season00.png
    ├── Star Wars The Clone Wars_Season01.png
    ├── Star Wars The Clone Wars_Season02.png
    ├── Star Wars The Clone Wars_Season03.png
    ├── Star Wars The Clone Wars_Season04.png
    ├── Star Wars The Clone Wars_Season05.png
    ├── Star Wars The Clone Wars_Season06.png
    ├── Star Wars The Clone Wars_Season07.png
    ├── Star Wars The Clone Wars_S07E01.png
    ├── Star Wars The Clone Wars_S07E02.png
    ├── Star Wars The Clone Wars_S07E03.png
    ├── Star Wars The Clone Wars_S07E04.png
    ├── Star Wars The Clone Wars_S07E05.png
    ├── Star Wars Rebels.png
    ├── Star Wars Rebels_background.png
    ├── Star Wars Rebels_Season01.png
    ├── Star Wars Rebels_Season01_background.png
    ├── Star Wars Rebels_Season02.png
    ├── Star Wars Rebels_Season02_background.png
    ├── Star Wars Rebels_Season03.png
    ├── Star Wars Rebels_Season03_background.png
    ├── Star Wars Rebels_Season04.png
    └── Star Wars Rebels_Season04_background.png
```

Please refer here [Kometa Local Assets Requirements](https://kometa.wiki/en/latest/kometa/guides/assets/#requirements-and-configuration)

I use `ASSET_FOLDERS=False` and have a separate volume for media assets.

Unfortunately this FR doesn’t help me.

**Comment by stevietv** [comment]
> Currently the implementation only supports `ASSET_FOLDERS=True`. So basically you're requesting support for `ASSET_FOLDERS=False` with a custom folder for Kometa assets?
> 
> AFAIK the arrs should support only local assets in the movie/series folder, so I'm more inclined at this to just remove this metadata provider at this point.
> 
> /cc @stevietv for thoughts on this since you're the OP at Sonarr.

Hi @mynameisbogdan - this was also raised as issue on Sonarr (ref https://github.com/Sonarr/Sonarr/issues/7400), so I'll take a look at it there. Right now the assets go to the media folder instead of an assets folder, so both implementations are not actually correctly incorporated.

I was thinking of potentially introducing a 'assets path' option for this implementation, but not sure if that's going to work given that we store the ExtraFiles Relative Path.

**Comment by markus101** [comment]
Sonarr only manages metadata files within the media folder. The purpose of Kometa support in Sonarr is to avoid renaming files that Kometa put in the media folder, not create files that Kometa will manage outside that folder.

if we’re creating files that Kometa can’t manage because they’re outside the expected folder structure then we should stop creating them, but we shouldn’t support a different folder structure to support Kometa.

**Comment by bakerboy448** [comment]
Concur with markus on not managing files outside of Starr Root Folder

**Comment by stevietv** [comment]
> if we’re creating files that Kometa can’t manage because they’re outside the expected folder structure then we should stop creating them, but we shouldn’t support a different folder structure to support Kometa.

Then we should remove this integration!

**Comment by markus101** [comment]
These were files within Sonarr's directory, we need to track them if they're there. Though it sounds like we shouldn't be creating new files because Kometa expects them in a different location.

**Comment by stevietv** [comment]
We're currently creating them in the with the kometa filenames but not in a folder that kometa uses. Kometa doesn't seem to save an image files itself in the series folders, only in its asset folder. So i think the only thing we're actually tracking here is the files we created via this integration

**Comment by markus101** [comment]
Yeah, you're right. In that case, we should immediately stop creating them and keep it as tracking only, in the next major version we should remove it completely. If we want to support creating metadata files for Kometa that live outside of the series folder then it should be done via a connection instead.
