### ISSUE TITLE
Custom Filter - Downloading

### ISSUE THREAD

**Issue by tekmyster** [Radarr/Radarr#10708]
### Is there an existing issue for this?

- [ ] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

yes, downloading is mixed in with missing and there is no way to filter out one or the other from the list of items.

### Describe the solution you'd like

creating a filter item to be able to include/exclude the downloading status when listing missing.

### Describe alternatives you've considered

have not found any way, there is no sort or filter to separate these out

### Anything else?

nothing else

**Comment by bakerboy448** [comment]
Relating to https://github.com/Radarr/Radarr/issues/5252#issuecomment-927230592
