### ISSUE TITLE
Quality file size sliders won't save changes

### ISSUE THREAD

**Issue by redfuel318** [Radarr/Radarr#1071]
Hey guys,

Looks like my slider bars for file sizes per quality type have stopped saving any changes. I've tried all sorts of things to change them, including setting them all to Unlimited/Unlimited and 0/0. Every save, and subsequent reload or service restart just shows them back to where they were, when I last customised them. I'm hitting Save, each time to no avail. 

Interestingly, the last time this worked without a problem I had only changed the size slider for Bluray-1080 and nothing else, but everything else of less quality seem to have auto-adjusted. Not sure if this is related or a feature.

![image](https://cloud.githubusercontent.com/assets/26263767/23685197/aa7ddf94-039a-11e7-8d3e-3446605adcaf.png)

**Comment by onedr0p** [comment]
Save a page size in UI settings.

**Comment by DrizzlyOwl** [comment]
I'm having the same problem, except that I can't persist the 'Page Size' value in the UI settings.

Every time I select '25' click 'save' then visit another screen, then return to the UI settings, the dropdown is still blank and the profiles and qualities still lose their preference.
