### ISSUE TITLE
Labels support for Transmission

### ISSUE THREAD

**Issue by gitdeath** [Radarr/Radarr#10759]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Missing Label Support for Transmission.

### Describe the solution you'd like

Recently added in Sonarr
https://github.com/Sonarr/Sonarr/pull/7303

### Describe alternatives you've considered

n/a

### Anything else?

n/a

**Comment by bakerboy448** [comment]
Invalid request.
[You did not search](https://github.com/Radarr/Radarr/issues?q=is%3Aissue+transmission+)

https://github.com/Radarr/Radarr/pull/10726

https://github.com/Radarr/Radarr/commit/a2b38c5b7d8de16b4c844c4406b39de9d20f19ea
