### ISSUE TITLE
Feature: Add default path to profile settings

### ISSUE THREAD

**Issue by bahace** [Radarr/Radarr#10760]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

I'd like in the profiles settings to set a default path. 

For example:
Profile - MoviesDeu >> Path /movies/deu
Profile - MoviesEng >> Path /movies/eng

### Describe alternatives you've considered

tagging. If this could be done with tags that after the movie is importing, radarr looks at the tags and then moves again to a new root folder for the movie, that would work. 

### Anything else?

n/a

**Comment by bakerboy448** [comment]
No plans for default paths by quality profile.
