### ISSUE TITLE
An error occurred while sending the request

### ISSUE THREAD

**Issue by sy911212** [Radarr/Radarr#10775]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Request Failed. GET /MediaCoverProxy/1eb75ad7b0d0b4ada5edc64ed49ab518a72797246fc224734c27a0aed3d6d49d/uKjPUmOMmYYMFYtLBNXBDPAtcOz.jpg: An error occurred while sending the request.

### Expected Behavior

图片显示和人物图片获取异常

### Environment

```markdown
- OS: 4.3.3.RC92
- Radarr: 5.16.3.9541
- Docker Install: yes
- Using Reverse Proxy: no
- Browser: Microsoft Edge131
- Database:
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

![image](https://github.com/user-attachments/assets/f107e1bd-3ef7-450a-a238-0afc53ff4811)
![Uploading image.png…]()

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
Someone not responding to[ your discord message](https://discord.com/channels/264387956343570434/264388019585286144/1318386251350671480) in 17 minutes does not make it a bug.
