### ISSUE TITLE
Simkl - Custom name list and support private list

### ISSUE THREAD

**Issue by Firemad03** [Radarr/Radarr#10787]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Yes

### Describe the solution you'd like

Simkl custom private list when you pay for Simkl. Same thing like we have with trakt.tv Also to have the possibility to use a specific list like trakt.tv

Right now we can only use watch list without using custom list. For example we can't use 2, 3 or more list. Just make it compatible with 1 list name and after that the user can add multiple Simkl import list.

### Describe alternatives you've considered

Using trakt.tv but Simkl is superior :)

### Anything else?

In trakt.tv module in Radarr you can use a custom list name. Same thing we need :)

**Comment by Firemad03** [comment]
Also it will be nice to use other public list that people share if it's possible like trakt.tv

**Comment by bakerboy448** [comment]
Relating partially to https://github.com/Radarr/Radarr/issues/8875 and https://github.com/Radarr/Radarr/issues/8915

**Comment by bakerboy448** [comment]
It does not appear this is something Simkl's API supports at this time.

https://simkl.docs.apiary.io/#reference/sync/get-all-items/get-all-items-in-the-user's-watchlist.

If simlkl api documentation can be provided that would facilitate this request it can be explored

**Comment by Firemad03** [comment]
I asked dev at Simkl in Discord about it if they can update the documentation or provide the API for it.
