### ISSUE TITLE
Enhance Arabp2p Indexer Search by Supporting TMDb ID

### ISSUE THREAD

**Issue by mkarimdev** [Radarr/Radarr#10784]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Radarr's integration with the Arabp2p indexer currently faces issues when searching for Arabic movies. The primary problem is that searches often fail due to mismatches in the movie name, especially when dealing with non-standard naming conventions in Arabic or alternative titles.

Recently, Arabp2p has updated its search mechanics to allow searching by several parameters, including torrent name, release year, actor, director, and, most importantly, TMDb ID. Leveraging the TMDb ID for searches would significantly improve the success rate by ensuring precise matches, regardless of title variations or formatting issues.

Raddarr currently searches arabp2p with only movies' names..
![image](https://github.com/user-attachments/assets/fae46659-1fb9-462c-8342-73f280bd95a0)

### Describe the solution you'd like

I propose that Radarr enhances its integration with the Arabp2p API to include the option of searching by TMDb ID. By implementing this feature:

- Radarr can directly utilize TMDb IDs (already available in its database) to perform accurate searches.
- Search failures caused by mismatched or inconsistent titles can be minimized.
- Users can more reliably fetch Arabic content through Radarr without manual intervention.

### Describe alternatives you've considered

Currently, users must rely on manual searches or try to match torrent names with movie titles, which is error-prone and inefficient. Another alternative would be searching by release year or cast information, but these methods are less precise than using TMDb ID, which provides a unique identifier for each movie.

### Anything else?

- [Arabp2p.net](https://www.arabp2p.net/) recently updated their search mechanics to include TMDb ID support.
- Adding TMDb ID support in Radarr would align it with Arabp2p's updated capabilities and greatly improve user experience.
- This update could potentially benefit other indexers that may also support TMDb ID searches in the future.

**Comment by bakerboy448** [comment]
Radarr does not natively implement this indexer. No plans to add additional custom indexers.  Radarr replied on the newznab/Torznab caps for what capabilities are supported.

using chatgpt to create issues makes for very irrelevant and odd commentary.
