### ISSUE TITLE
Custom TraktList not working

### ISSUE THREAD

**Issue by greatvc** [Radarr/Radarr#1078]
v0.2.0.453
MacOS Latest

I created the trakt auth and successful linked with my username but i cannot add a custom list. I'm trying to add the movist list which is private named "Wish List", Isn't this possible ?

![image](https://cloud.githubusercontent.com/assets/13116317/23700836/e7d41a04-03fc-11e7-929a-f83a577d5a7b.png)

thank you

**Comment by onedr0p** [comment]
Replace the space in the list name with a dash, let me know if that works. I'll add a fix if so!

**Comment by greatvc** [comment]
The test passes but then i go to add movie, add from lists select a list and get the below error

![clipboard-1](https://cloud.githubusercontent.com/assets/13116317/23709863/754800e6-0423-11e7-9353-a1535de02ac2.jpg)

**Comment by onedr0p** [comment]
Looks like I'll have to debug later today. I'll have a fix tonight hopefully. Also i see no dash in the name, you just removed the space.

**Comment by onedr0p** [comment]
That or the movies are already in radarr.

**Comment by greatvc** [comment]
my mistake witht works with the dash
I havent hange the list type to customlist. once i changed that and hit save and import it added all my movies.

**Comment by onedr0p** [comment]
Cool I'll update the code to replace spaces with dashes.

**Comment by onedr0p** [comment]
Fixed in next release
