### ISSUE TITLE
Local address checking is not working for properly configured ipv6

### ISSUE THREAD

**Issue by dsm1212** [Radarr/Radarr#10795]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

If my browser picks up an ipv6 address to reach radarr I get a basic authentication prompt I cannot disable even though I'm on the same network and have the setting to allow local addressing.  

There was an issue about this before, but the response was based on poor usage of ipv6 and needs further reconsideration.

### Expected Behavior

The code seems to be allowing ipv6 mapped to ipv4 which is a poor configuration and no one should be doing. 

IPV6 has multiple types of addresss:

link-local: In hex these start with fe8 through feb. These should be considered local always

lan only routed: In hex these start with fc through fd. This should be consider local always

"Permanent" addresses: These are allocated from a range provided by the service provider. A prefix is broadcast by your router and these typically end with the bits from your mac address but it depends on your router.

"Temporary" addresses: Also allocated from a service provider range (I think). These are really only useful as a source address to help keep clients secure. The log I attached shows my browser using the pc's temporary ipv6 address starting with 2601 which Is what I'd expect to find on windows and mac these days.

The only thing I can think of is to allow the user to enter some prefixes. And you should also allow the link-local and lan only ranges by checking the start of the address.

I keep radarr behind authelia so this is an unnecessary nuisance I'm forced to struggle to defeat. But I understand you feel strongly about this requirement so maybe fixing the ipv6 check is something we can address.

### Steps To Reproduce

You need to have ipv6 enabled on your lan and set up correctly on your router. A system on your lan will likely start getting ipv6 addressing for hosts in URL's. Once that happens for radarr you will be prompted for authentication.

### Environment

```markdown
- OS: debian 12
- Radarr: 5.16.3.9541
- Docker Install: 5.16.3.9541-ls250 by linuxserver.io
- Using Reverse Proxy: swag
- Browser: chrome

.NET
Yes (6.0.35)
Docker
Yes
Database
Sqlite 3.45.3
Database Migration
240
AppData Directory
/config
Startup Directory
/app/radarr/bin
Mode
Console
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

[radarr_trace.log](https://github.com/user-attachments/files/18242093/radarr_trace.log)

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
> The code seems to be allowing ipv6 mapped to ipv4 which is a poor configuration and no one should be doing.

Only if it's an ipv4 mapped via an ipv6

https://github.com/Radarr/Radarr/blob/af60cca9ae47c9d4d47f327fa2e2d32cbde50691/src/NzbDrone.Common/Extensions/IpAddressExtensions.cs#L31-33

the ip in your logs does not appear to be local

**Comment by dsm1212** [comment]
Yes, this is a difference between v4 and v6. They have reserved certain addresses like in v4 to be reused but all other addresses are global and every device has a permanent global address and possibly many temporary ones. The 2601 number is my desktops temporary global address. The temporary part is the suffix of the address, that changes periodically. The global address types are allocated from one of two pools provided by the service provider. I'm confident the permanent one never changes, because you need to use it in your router config. Even a commercial one like cisco. But the temporary one is automatic and I'm sure it changes. I have a 12 month old log though that shows it's been that 2601 prefix for at least that long at my house. So it must change rarely. I think if we could specify two prefixes to check it would cover this. Even an environment setting would be fine.

**Comment by bakerboy448** [comment]
No near term plans to give user easy footguns of wide open access; (I.e. custom ip range or ipv6 prefix to whitelist)

I'd suggest a feature request upstream @ Sonarr to see if appetite exists to allow a user input for a custom ip range if the existing dotnet native and RFC based logic doesn't work for your needs.
