### ISSUE TITLE
Deluge 1.3.14 Not Working With Radarr

### ISSUE THREAD

**Issue by evilvibes** [Radarr/Radarr#1080]
Deluge 1.3.14 isnt playing nice with Radarr 

HTTP Error - Res: [POST] http://localhost:7698/json: 500.InternalServerError
Close
Unable to connect to Deluge, please check your settings: Unable to connect to Deluge, please check your settings

Invalid JSON request content-type: application/json-rpc

1.3.13 worked fine but 1.3.14 having some issues

**Comment by evilvibes** [comment]
Same issue was here [https://github.com/Sonarr/Sonarr/issues/1738](url)

**Comment by fryfrog** [comment]
I think https://github.com/Radarr/Radarr/commit/73f0916fa035b1748be6a920e23e7c9562f855ab fixed it and was released in a very recent nightly.

**Comment by evilvibes** [comment]
Yea i just seen that. Closing this now.
