### ISSUE TITLE
[Feature Request] Revert nightly to previous update 

### ISSUE THREAD

**Issue by ajkis** [Radarr/Radarr#1081]
Since some of nightly releases are breaking core features it would be nice if we had option to revert to previous version as well.

**Comment by onedr0p** [comment]
No, this would require downgrading the database which we aren't going to support. Just use your database back ups and install the old version with the old database.

**Comment by onedr0p** [comment]
Once we have a stable release it will be better since we won't be releasing a new update every couple weeks.
