### ISSUE TITLE
Windows 10 Stop Errors

### ISSUE THREAD

**Issue by DejaVu** [Radarr/Radarr#1085]
While scanning directories i have my movies in, i am greeted with Windows Stop Errors.

It only happens during scans, but it is happening a lot. The first one i noticed did mention KMODE.

It only happens when I'm using Radarr so has got to be something to do with it.

Would like to be more help, but not sure where to look. My event log is clear because it just blue screens with no warning. 

Any ideas?!

**Comment by bloodsplatter** [comment]
Do you have any logs? Try and recreate the issue then after the computer restarts, get the log files and post them in a gist and post the link here.

**Comment by galli-leo** [comment]
If you still have these issues please let me know and I will reopen.
