### ISSUE TITLE
Application updating using built in updater, even when disabled

### ISSUE THREAD

**Issue by evulhotdog** [Radarr/Radarr#109]
I manually ran the 'Application Update' task to check for the latest update and see if it would notify me with the red badge icon on the system tab. As soon as I ran it it started the application update. I don't think this is the intended behavior, when the automatic update is disabled. Logs are included below. 

![image](https://cloud.githubusercontent.com/assets/365456/21822207/474729da-d744-11e6-8c47-3f2a00525fcc.png)

![image](https://cloud.githubusercontent.com/assets/365456/21822162/223aefa0-d744-11e6-8bf8-24655b8ae15a.png)

`17-1-10 14:45:34.3|Trace|CommandQueueManager|Publishing ApplicationUpdate
17-1-10 14:45:34.3|Trace|CommandQueueManager|Checking if command is queued or started: ApplicationUpdate
17-1-10 14:45:34.3|Trace|CommandQueueManager|Inserting new command: ApplicationUpdate
17-1-10 14:45:34.3|Trace|Http|Res: 1148 [POST] /api/command: 201.Created (28 ms)
17-1-10 14:45:34.3|Debug|Api|[POST] /api/command: 201.Created (28 ms)
17-1-10 14:45:34.3|Trace|CommandExecutor|ApplicationUpdateCommand -> InstallUpdateService
17-1-10 14:45:34.3|Trace|CommandQueueManager|Marking command as started: ApplicationUpdate
17-1-10 14:45:34.3|Trace|EventAggregator|Publishing CommandUpdatedEvent
17-1-10 14:45:34.3|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
17-1-10 14:45:34.3|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
17-1-10 14:45:34.3|Debug|InstallUpdateService|Checking for updates
17-1-10 14:45:34.3|Trace|EventAggregator|Publishing CommandUpdatedEvent
17-1-10 14:45:34.3|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
17-1-10 14:45:34.3|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
17-1-10 14:45:34.3|Trace|HttpClient|Req: [GET] http://radarr.aeonlucid.com/v1/update/develop?version=0.2.0.32&os=linux
17-1-10 14:45:34.4|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
17-1-10 14:45:35.1|Trace|HttpClient|Res: [GET] http://radarr.aeonlucid.com/v1/update/develop?version=0.2.0.32&os=linux: 200.OK (723 ms)
17-1-10 14:45:35.1|Info|InstallUpdateService|Deleting old update files
17-1-10 14:45:35.1|Info|InstallUpdateService|Downloading update 0.2.0.45
17-1-10 14:45:35.1|Trace|EventAggregator|Publishing CommandUpdatedEvent
17-1-10 14:45:35.1|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
17-1-10 14:45:35.1|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
17-1-10 14:45:35.1|Debug|InstallUpdateService|Downloading update package from [https://github.com/galli-leo/Radarr/releases/download/v0.2.0.45/Radarr.develop.0.2.0.45.linux.tar.gz] to [/tmp/radarr_update/Radarr.develop.0.2.0.45.linux.tar.gz]
17-1-10 14:45:35.1|Debug|HttpClient|Downloading [https://github.com/galli-leo/Radarr/releases/download/v0.2.0.45/Radarr.develop.0.2.0.45.linux.tar.gz] to [/tmp/radarr_update/Radarr.develop.0.2.0.45.linux.tar.gz]
17-1-10 14:45:37.8|Debug|HttpClient|Downloading Completed. took 2s
17-1-10 14:45:37.8|Info|InstallUpdateService|Verifying update package
17-1-10 14:45:37.8|Trace|EventAggregator|Publishing CommandUpdatedEvent
17-1-10 14:45:37.8|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
17-1-10 14:45:37.8|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
17-1-10 14:45:37.9|Info|InstallUpdateService|Update package verified successfully
17-1-10 14:45:37.9|Info|InstallUpdateService|Extracting Update package
17-1-10 14:45:37.9|Trace|EventAggregator|Publishing CommandUpdatedEvent
17-1-10 14:45:37.9|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
17-1-10 14:45:37.9|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
17-1-10 14:45:38.0|Debug|ArchiveService|Extracting archive [/tmp/radarr_update/Radarr.develop.0.2.0.45.linux.tar.gz] to [/tmp/radarr_update/]
17-1-10 14:45:38.7|Debug|ArchiveService|Extraction complete.
17-1-10 14:45:38.7|Info|InstallUpdateService|Update package extracted successfully
17-1-10 14:45:38.7|Info|BackupService|Starting Backup
17-1-10 14:45:38.7|Trace|EventAggregator|Publishing CommandUpdatedEvent
17-1-10 14:45:38.7|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
17-1-10 14:45:38.7|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
17-1-10 14:45:38.7|Trace|DiskProviderBase|Deleting file: /tmp/nzbdrone_backup/config.xml
17-1-10 14:45:38.7|Trace|DiskProviderBase|Deleting file: /tmp/nzbdrone_backup/nzbdrone.db
17-1-10 14:45:38.7|Debug|BackupService|Cleaning up old backup files
17-1-10 14:45:38.7|Debug|BackupService|Finished cleaning up old backup files
17-1-10 14:45:38.7|Debug|BackupService|Backing up config.xml
17-1-10 14:45:38.7|Trace|EventAggregator|Publishing CommandUpdatedEvent
17-1-10 14:45:38.7|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
17-1-10 14:45:38.7|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
17-1-10 14:45:38.7|Debug|DiskTransferService|Copy [/home/radarr/.config/Radarr/config.xml] > [/tmp/nzbdrone_backup/config.xml]
17-1-10 14:45:38.7|Trace|SymbolicLinkResolver|Checking path /tmp/nzbdrone_backup/config.xml for symlink returned error ENOENT, assuming it's not a symlink.
17-1-10 14:45:38.7|Debug|BackupService|Backing up database
17-1-10 14:45:38.7|Trace|EventAggregator|Publishing CommandUpdatedEvent
17-1-10 14:45:38.7|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
17-1-10 14:45:38.7|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
17-1-10 14:45:38.7|Debug|DiskTransferService|Copy [/home/radarr/.config/Radarr/nzbdrone.db] > [/tmp/nzbdrone_backup/nzbdrone.db]
17-1-10 14:45:38.7|Trace|SymbolicLinkResolver|Checking path /tmp/nzbdrone_backup/nzbdrone.db for symlink returned error ENOENT, assuming it's not a symlink.
17-1-10 14:45:38.7|Debug|BackupService|Creating backup zip
17-1-10 14:45:38.7|Trace|EventAggregator|Publishing CommandUpdatedEvent
17-1-10 14:45:38.7|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
17-1-10 14:45:38.7|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
17-1-10 14:45:39.1|Debug|BackupService|Backup zip created
17-1-10 14:45:39.1|Trace|EventAggregator|Publishing CommandUpdatedEvent
17-1-10 14:45:39.1|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
17-1-10 14:45:39.1|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
17-1-10 14:45:39.1|Info|InstallUpdateService|Preparing client
17-1-10 14:45:39.1|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/CurlSharp.dll] > [/tmp/radarr_update/CurlSharp.dll]
17-1-10 14:45:39.1|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/CurlSharp.dll.mdb] > [/tmp/radarr_update/CurlSharp.dll.mdb]
17-1-10 14:45:39.1|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/ICSharpCode.SharpZipLib.dll] > [/tmp/radarr_update/ICSharpCode.SharpZipLib.dll]
17-1-10 14:45:39.1|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/LogentriesCore.dll] > [/tmp/radarr_update/LogentriesCore.dll]
17-1-10 14:45:39.1|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/LogentriesCore.dll.mdb] > [/tmp/radarr_update/LogentriesCore.dll.mdb]
17-1-10 14:45:39.1|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/LogentriesNLog.dll] > [/tmp/radarr_update/LogentriesNLog.dll]
17-1-10 14:45:39.1|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/LogentriesNLog.dll.mdb] > [/tmp/radarr_update/LogentriesNLog.dll.mdb]
17-1-10 14:45:39.1|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/NLog.dll] > [/tmp/radarr_update/NLog.dll]
17-1-10 14:45:39.1|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/Newtonsoft.Json.dll] > [/tmp/radarr_update/Newtonsoft.Json.dll]
17-1-10 14:45:39.1|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/NzbDrone.Common.dll] > [/tmp/radarr_update/NzbDrone.Common.dll]
17-1-10 14:45:39.1|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/NzbDrone.Common.dll.mdb] > [/tmp/radarr_update/NzbDrone.Common.dll.mdb]
17-1-10 14:45:39.1|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/NzbDrone.Mono.dll] > [/tmp/radarr_update/NzbDrone.Mono.dll]
17-1-10 14:45:39.1|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/NzbDrone.Mono.dll.mdb] > [/tmp/radarr_update/NzbDrone.Mono.dll.mdb]
17-1-10 14:45:39.1|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/Org.Mentalis.dll] > [/tmp/radarr_update/Org.Mentalis.dll]
17-1-10 14:45:39.1|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/Radarr.Update.exe] > [/tmp/radarr_update/Radarr.Update.exe]
17-1-10 14:45:39.1|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/Radarr.Update.exe.config] > [/tmp/radarr_update/Radarr.Update.exe.config]
17-1-10 14:45:39.1|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/Radarr.Update.exe.mdb] > [/tmp/radarr_update/Radarr.Update.exe.mdb]
17-1-10 14:45:39.1|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/SocksWebProxy.dll] > [/tmp/radarr_update/SocksWebProxy.dll]
17-1-10 14:45:39.1|Info|InstallUpdateService|Starting update client /tmp/radarr_update/Radarr.Update.exe
17-1-10 14:45:39.1|Info|InstallUpdateService|Radarr will restart shortly.`

**Comment by evulhotdog** [comment]
Updated again.

`17-1-10 18:12:34.5|Trace|CommandQueueManager|Updating command status
17-1-10 18:12:34.5|Trace|Http|Res: 2234 [POST] /api/command: 201.Created (10 ms)
17-1-10 18:12:34.5|Debug|Api|[POST] /api/command: 201.Created (10 ms)
17-1-10 18:12:34.5|Trace|EventAggregator|Publishing CommandUpdatedEvent
17-1-10 18:12:34.5|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
17-1-10 18:12:34.5|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
17-1-10 18:12:34.5|Trace|EventAggregator|Publishing CommandExecutedEvent
17-1-10 18:12:34.5|Trace|EventAggregator|CommandExecutedEvent -> TaskManager
17-1-10 18:12:34.5|Trace|EventAggregator|CommandExecutedEvent <- TaskManager
17-1-10 18:12:34.5|Trace|EventAggregator|CommandExecutedEvent -> TaskModule
17-1-10 18:12:34.5|Trace|EventAggregator|CommandExecutedEvent <- TaskModule
17-1-10 18:12:34.5|Trace|CommandExecutor|DeleteLogFilesCommand <- DeleteLogFilesService [00:00:00.0041260]
17-1-10 18:12:34.7|Trace|Http|Req: 2235 [GET] /api/log/file
17-1-10 18:12:34.7|Trace|Http|Res: 2235 [GET] /api/log/file: 200.OK (1 ms)
17-1-10 18:12:34.7|Debug|Api|[GET] /api/log/file: 200.OK (1 ms)
17-1-10 18:12:34.7|Trace|Http|Req: 2236 [GET] /api/log/file
17-1-10 18:12:34.7|Trace|Http|Res: 2236 [GET] /api/log/file: 200.OK (1 ms)
17-1-10 18:12:34.7|Debug|Api|[GET] /api/log/file: 200.OK (1 ms)
17-1-10 18:12:34.7|Trace|Http|Req: 2237 [GET] /api/log/file/sonarr.debug.txt
17-1-10 18:12:34.7|Trace|Http|Res: 2237 [GET] /api/log/file/sonarr.debug.txt: 200.OK (1 ms)
17-1-10 18:12:34.7|Debug|Api|[GET] /api/log/file/sonarr.debug.txt: 200.OK (1 ms)
17-1-10 18:12:34.8|Trace|Http|Req: 2238 [GET] /api/log/file/sonarr.debug.txt
17-1-10 18:12:34.8|Trace|Http|Res: 2238 [GET] /api/log/file/sonarr.debug.txt: 200.OK (1 ms)
17-1-10 18:12:34.8|Debug|Api|[GET] /api/log/file/sonarr.debug.txt: 200.OK (1 ms)
17-1-10 18:12:41.3|Trace|Http|Req: 2239 [GET] /api/system/task??sort_by=name&order=asc
17-1-10 18:12:41.3|Trace|Http|Res: 2239 [GET] /api/system/task??sort_by=name&order=asc: 200.OK (4 ms)
17-1-10 18:12:41.3|Debug|Api|[GET] /api/system/task??sort_by=name&order=asc: 200.OK (4 ms)
17-1-10 18:12:41.4|Trace|Http|Req: 2240 [GET] /api/system/task??sort_by=name&order=asc
17-1-10 18:12:41.4|Trace|Http|Res: 2240 [GET] /api/system/task??sort_by=name&order=asc: 200.OK (3 ms)
17-1-10 18:12:41.4|Debug|Api|[GET] /api/system/task??sort_by=name&order=asc: 200.OK (3 ms)
17-1-10 18:12:44.1|Trace|Http|Req: 2241 [POST] /api/command
17-1-10 18:12:44.1|Trace|CommandQueueManager|Publishing ApplicationUpdate
17-1-10 18:12:44.1|Trace|CommandQueueManager|Checking if command is queued or started: ApplicationUpdate
17-1-10 18:12:44.1|Trace|CommandQueueManager|Inserting new command: ApplicationUpdate
17-1-10 18:12:44.1|Trace|CommandExecutor|ApplicationUpdateCommand -> InstallUpdateService
17-1-10 18:12:44.1|Trace|CommandQueueManager|Marking command as started: ApplicationUpdate
17-1-10 18:12:44.1|Trace|Http|Res: 2241 [POST] /api/command: 201.Created (10 ms)
17-1-10 18:12:44.1|Debug|Api|[POST] /api/command: 201.Created (10 ms)
17-1-10 18:12:44.1|Trace|EventAggregator|Publishing CommandUpdatedEvent
17-1-10 18:12:44.1|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
17-1-10 18:12:44.1|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
17-1-10 18:12:44.1|Debug|InstallUpdateService|Checking for updates
17-1-10 18:12:44.1|Trace|EventAggregator|Publishing CommandUpdatedEvent
17-1-10 18:12:44.1|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
17-1-10 18:12:44.1|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
17-1-10 18:12:44.1|Trace|HttpClient|Req: [GET] http://radarr.aeonlucid.com/v1/update/develop?version=0.2.0.45&os=linux
17-1-10 18:12:44.1|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
17-1-10 18:12:44.8|Trace|HttpClient|Res: [GET] http://radarr.aeonlucid.com/v1/update/develop?version=0.2.0.45&os=linux: 200.OK (669 ms)
17-1-10 18:12:44.8|Info|InstallUpdateService|Deleting old update files
17-1-10 18:12:44.8|Info|InstallUpdateService|Downloading update 0.2.0.61
17-1-10 18:12:44.8|Trace|EventAggregator|Publishing CommandUpdatedEvent
17-1-10 18:12:44.8|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
17-1-10 18:12:44.8|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
17-1-10 18:12:44.8|Debug|InstallUpdateService|Downloading update package from [https://github.com/Radarr/Radarr/releases/download/v0.2.0.61/Radarr.develop.0.2.0.61.linux.tar.gz] to [/tmp/radarr_update/Radarr.develop.0.2.0.61.linux.tar.gz]
17-1-10 18:12:44.8|Debug|HttpClient|Downloading [https://github.com/Radarr/Radarr/releases/download/v0.2.0.61/Radarr.develop.0.2.0.61.linux.tar.gz] to [/tmp/radarr_update/Radarr.develop.0.2.0.61.linux.tar.gz]
17-1-10 18:12:46.7|Debug|HttpClient|Downloading Completed. took 1s
17-1-10 18:12:46.7|Info|InstallUpdateService|Verifying update package
17-1-10 18:12:46.7|Trace|EventAggregator|Publishing CommandUpdatedEvent
17-1-10 18:12:46.7|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
17-1-10 18:12:46.7|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
17-1-10 18:12:46.8|Info|InstallUpdateService|Update package verified successfully
17-1-10 18:12:46.8|Info|InstallUpdateService|Extracting Update package
17-1-10 18:12:46.8|Trace|EventAggregator|Publishing CommandUpdatedEvent
17-1-10 18:12:46.8|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
17-1-10 18:12:46.8|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
17-1-10 18:12:46.8|Debug|ArchiveService|Extracting archive [/tmp/radarr_update/Radarr.develop.0.2.0.61.linux.tar.gz] to [/tmp/radarr_update/]
17-1-10 18:12:47.3|Debug|ArchiveService|Extraction complete.
17-1-10 18:12:47.3|Info|InstallUpdateService|Update package extracted successfully
17-1-10 18:12:47.3|Info|BackupService|Starting Backup
17-1-10 18:12:47.3|Trace|EventAggregator|Publishing CommandUpdatedEvent
17-1-10 18:12:47.3|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
17-1-10 18:12:47.3|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
17-1-10 18:12:47.3|Trace|DiskProviderBase|Deleting file: /tmp/nzbdrone_backup/config.xml
17-1-10 18:12:47.3|Trace|DiskProviderBase|Deleting file: /tmp/nzbdrone_backup/nzbdrone.db
17-1-10 18:12:47.3|Debug|BackupService|Cleaning up old backup files
17-1-10 18:12:47.3|Debug|BackupService|Finished cleaning up old backup files
17-1-10 18:12:47.3|Debug|BackupService|Backing up config.xml
17-1-10 18:12:47.3|Trace|EventAggregator|Publishing CommandUpdatedEvent
17-1-10 18:12:47.3|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
17-1-10 18:12:47.3|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
17-1-10 18:12:47.3|Debug|DiskTransferService|Copy [/home/radarr/.config/Radarr/config.xml] > [/tmp/nzbdrone_backup/config.xml]
17-1-10 18:12:47.3|Trace|SymbolicLinkResolver|Checking path /tmp/nzbdrone_backup/config.xml for symlink returned error ENOENT, assuming it's not a symlink.
17-1-10 18:12:47.3|Debug|BackupService|Backing up database
17-1-10 18:12:47.3|Trace|EventAggregator|Publishing CommandUpdatedEvent
17-1-10 18:12:47.3|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
17-1-10 18:12:47.3|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
17-1-10 18:12:47.3|Debug|DiskTransferService|Copy [/home/radarr/.config/Radarr/nzbdrone.db] > [/tmp/nzbdrone_backup/nzbdrone.db]
17-1-10 18:12:47.3|Trace|SymbolicLinkResolver|Checking path /tmp/nzbdrone_backup/nzbdrone.db for symlink returned error ENOENT, assuming it's not a symlink.
17-1-10 18:12:47.4|Debug|BackupService|Creating backup zip
17-1-10 18:12:47.4|Trace|EventAggregator|Publishing CommandUpdatedEvent
17-1-10 18:12:47.4|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
17-1-10 18:12:47.4|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
17-1-10 18:12:47.7|Debug|BackupService|Backup zip created
17-1-10 18:12:47.7|Trace|EventAggregator|Publishing CommandUpdatedEvent
17-1-10 18:12:47.7|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
17-1-10 18:12:47.7|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
17-1-10 18:12:47.7|Info|InstallUpdateService|Preparing client
17-1-10 18:12:47.7|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/CurlSharp.dll] > [/tmp/radarr_update/CurlSharp.dll]
17-1-10 18:12:47.7|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/CurlSharp.dll.mdb] > [/tmp/radarr_update/CurlSharp.dll.mdb]
17-1-10 18:12:47.7|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/ICSharpCode.SharpZipLib.dll] > [/tmp/radarr_update/ICSharpCode.SharpZipLib.dll]
17-1-10 18:12:47.7|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/LogentriesCore.dll] > [/tmp/radarr_update/LogentriesCore.dll]
17-1-10 18:12:47.7|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/LogentriesCore.dll.mdb] > [/tmp/radarr_update/LogentriesCore.dll.mdb]
17-1-10 18:12:47.7|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/LogentriesNLog.dll] > [/tmp/radarr_update/LogentriesNLog.dll]
17-1-10 18:12:47.7|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/LogentriesNLog.dll.mdb] > [/tmp/radarr_update/LogentriesNLog.dll.mdb]
17-1-10 18:12:47.7|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/NLog.dll] > [/tmp/radarr_update/NLog.dll]
17-1-10 18:12:47.7|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/Newtonsoft.Json.dll] > [/tmp/radarr_update/Newtonsoft.Json.dll]
17-1-10 18:12:47.7|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/NzbDrone.Common.dll] > [/tmp/radarr_update/NzbDrone.Common.dll]
17-1-10 18:12:47.7|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/NzbDrone.Common.dll.mdb] > [/tmp/radarr_update/NzbDrone.Common.dll.mdb]
17-1-10 18:12:47.7|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/NzbDrone.Mono.dll] > [/tmp/radarr_update/NzbDrone.Mono.dll]
17-1-10 18:12:47.7|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/NzbDrone.Mono.dll.mdb] > [/tmp/radarr_update/NzbDrone.Mono.dll.mdb]
17-1-10 18:12:47.7|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/Org.Mentalis.dll] > [/tmp/radarr_update/Org.Mentalis.dll]
17-1-10 18:12:47.7|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/Radarr.Update.exe] > [/tmp/radarr_update/Radarr.Update.exe]
17-1-10 18:12:47.7|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/Radarr.Update.exe.config] > [/tmp/radarr_update/Radarr.Update.exe.config]
17-1-10 18:12:47.7|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/Radarr.Update.exe.mdb] > [/tmp/radarr_update/Radarr.Update.exe.mdb]
17-1-10 18:12:47.7|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/SocksWebProxy.dll] > [/tmp/radarr_update/SocksWebProxy.dll]
17-1-10 18:12:47.7|Info|InstallUpdateService|Starting update client /tmp/radarr_update/Radarr.Update.exe
17-1-10 18:12:47.7|Info|InstallUpdateService|Radarr will restart shortly.
17-1-10 18:12:47.7|Trace|EventAggregator|Publishing CommandUpdatedEvent
17-1-10 18:12:47.7|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
17-1-10 18:12:47.7|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
17-1-10 18:12:48.0|Info|InstallUpdateService|Updater Arguments: 80504 /tmp/radarr_update /home/radarr/Radarr/Radarr.exe /nobrowser
17-1-10 18:12:48.0|Debug|mono|Starting mono --debug /tmp/radarr_update/Radarr.Update.exe 80504 /tmp/radarr_update /home/radarr/Radarr/Radarr.exe /nobrowser`

**Comment by Qstick** [comment]
Seems the logic in update service interprets a manual trigger as you wanting to update, which technically is not automatically updating if you are manually triggering. Looks to be same logic as Sonarr. @galli-leo do we want to change this?

https://github.com/Radarr/Radarr/blob/b3e46d02c6cc03cf812c384fe6edf330cd3f07bd/src/NzbDrone.Core/Update/InstallUpdateService.cs#L207

**Comment by galli-leo** [comment]
@Qstick Seems like an interesting question, I say, if you manually run application update task, you should expect an update.
