### ISSUE TITLE
Movie Editor - bulk change of movie path

### ISSUE THREAD

**Issue by davkav** [Radarr/Radarr#1091]
I recently migrated my movie collection on to a new server and restored a backup of Radarr.

Restoring of Radarr worked fine. However when I try to bulk edit the movie path names to their new locations, I can only change 10 at a time. Radarr shows the movies in Movie Editor in groups of 10 per page where as Sonarr lists all TV shows in one big list. I think the Save & Organise buttons are coded so that they will only function on the page that is displayed. So if you have 3 or 4 pages of movies and each selected to be organised, Radarr does not process any of the movies.

Radarr Version: 0.2.0.453

**Comment by geogolem** [comment]
i dont know about the "Organize button"...

but you are able to select items across pages, and the Save button will save the change to all the movies you have selected.

**Comment by jOOc** [comment]
@geogolem there are also some other issues with the save.
1. When saving your moved to first page, not the page you're on.
2. The WebUI is not updating the changes until you reload the page

![movie_editor](https://cloud.githubusercontent.com/assets/9382342/23790266/acb6f1ca-057e-11e7-9de1-2f7e39e5936a.gif)

**Comment by geogolem** [comment]
@jOOc : going back to the first page was intentional; however, I will change this. I will see why the rootFolder change it not being shown without reloading. looking into it now..  Can you confirm that the issue the original poster posted about is resolved in the latest?

**Comment by jOOc** [comment]
@geogolem Thank you
I'm on Radarr Version: 0.2.0.453 and there the selection/save works over pages.
I think I saw the issue that @davkav have weeks ago. So probably you fixed it in the later versions.

**Comment by geogolem** [comment]
@jOOc : thanks for the update.. Im looking at the code now, and Im quite sure I can fix the page issue.. but Im confused why the rootFolder is not showing without reloading...  but I just barely started looking into it.. Stay tuned, I should have more info in the next 20 minutes.

**Comment by jOOc** [comment]
Great. Maybe OT, but I have other issues with the list to. Should I take it here, make a new issue or chat with you in Discord?

**Comment by geogolem** [comment]
ok - so I know why this is happening a... i have a preliminary fix; however, i need to discuss with @onedr0p regarding the fix to make sure it works on all platforms.

**Comment by geogolem** [comment]
I merged the fix for this just now. Please let me know if you still have any issues.

**Comment by jOOc** [comment]
@geogolem as I told you in chat it works great now. Thank you!
