### ISSUE TITLE
Error 500 connecting to Deluge after they updated json-rpc

### ISSUE THREAD

**Issue by kaaresgut** [Radarr/Radarr#1098]
Can't connect to Deluge after Deluge updated json-rpc.
Getting this error when testing connection:
"Unknown exception: HTTP request failed: [500:InternalServerError] [POST] at [http://192.168.86.108:60002/json]"

Sonarr just issued a fix for the the same problem. From their changelog: "Deluge 1.3.14 API support due to changed json-rpc checks. (hotfix)".

Radarr v0.2.0.453 tested.

**Comment by onedr0p** [comment]
This was already committed.
