### ISSUE TITLE
Editing the max size of Bluray 1080P above 11.71GB - Maybe Adding Remux Quality for Unlimited

### ISSUE THREAD

**Issue by julestop** [Radarr/Radarr#110]
Can't edit the Bluray 1080P quality above 11.71GB.
Maybe spliting 1080P Bluray between Bluray 1080P and Remux 1080P would be helpful...

**Comment by HamilcarH** [comment]
Yes sometimes Radarr is grabbing remux instead of 1080p bluray for me.

**Comment by fryfrog** [comment]
I've actually added "Remux" (and "YIFY") to my exclude list to help stop that. :/

**Comment by galli-leo** [comment]
Actually, you set the file size limit to 12GB for a 60 minute movie. The maximum file size is computed per minute of movie. So for example a 120 minute movie can be maximum 24GB, a 180 minute movie 36 GB. Do you want have a higher possible maximum?
