### ISSUE TITLE
VPS, rclone and cloud storage help

### ISSUE THREAD

**Issue by mechanimal82** [Radarr/Radarr#1100]
I've been toying around with this to no avail, would appreciate thoughts on how others are managing/would manage this setup:

Server: Ubuntu VPS with Radarr, Sonarr, Sabnzbd etc & 50GB dedicated SSD for downloads.
Cloud Storage: Google Drive with dedicated Plex Cloud Server folder for use with (yep, you guessed it) Plex Cloud Server

In the VPS I have a Plex folder which I'm using rclone mount to be able to read the contents of the gdrive cloud storage (_/mnt/data/Plex_). I have a second folder for sab downloads(_/mnt/data/downloads/movies/_) and a third folder into which I currently have Radarr set to look in/move files to after processing (_/mnt/data/downloads/processed/movies/_). After renaming movies Radarr calls a custom rclone copy script which transfers the downloaded movie in the correct naming format from my processed folder to my gdrive Plex folder. Brilliant.

Except, now Radarr doesn't see that I have a copy of the movie and will try to redownload the movie again... causing a loop. Is this what the remote path mapping is for? Should I put the location of my mounted plex folder (_/mnt/data/Plex_) in this location so that Radarr can see what I have downloaded so it doesn't try again?

Anyone else using this type of scenario and can assist in how to best manage it?

**Comment by jscottdouglas** [comment]
@reboot ENCFS6_CONFIG='/home/nas/encfs/encfs.xml' /usr/bin/encfs --extpass="cat /home/nas/encfs/encfspass" -o allow_other /hd/00/media/.local-sorted /hd/00/media/local-sorted >/dev/null 2>&1
@reboot ENCFS6_CONFIG='/home/nas/encfs/encfs.xml' /usr/bin/encfs --extpass="cat /home/nas/encfs/encfspass" -o allow_other /hd/00/media/.acd-sorted /hd/00/media/acd-sorted >/dev/null 2>&1
@reboot /usr/bin/unionfs-fuse -o cow,allow_other /hd/00/media/local-sorted=RW:/hd/00/media/acd-sorted=RO /hd/00/media/sorted >/dev/null 2>&1
@reboot /bin/sleep 60; /usr/local/bin/rclone mount Amazon:/NAS /hd/00/media/.acd-sorted/ --allow-non-empty --allow-other --umask 22 >/dev/null 2>&1

*/10 * * * * flock -n /home/nas/encfs/acdcheck.lock -c 'bash /usr/local/bin/rclone-check.sh' >> /hd/00/media/logs/rclone-check.log 2>&1
40 */1 * * * flock -n /home/nas/encfs/acdupload.lock -c 'bash /usr/local/bin/rclone-upload.sh' >> /hd/00/media/logs/rclone-upload.log 2>&1
0 */12 * * * flock -n /home/nas/encfs/acdrsync.lock -c '/usr/bin/rsync -r --delete --existing --ignore-existing --verbose /hd/00/media/sorted/media/ /hd/00/media/acd-sorted/media/' >> /hd/00/media/logs/rclonersync.log 2>&1

`#!/bin/bash
if pidof -o %PPID -x "rclone-upload.sh"; then
echo "$(date "+%d.%m.%Y %T") SKIP: rclone-upload.sh already running." | tee -a "/hd/00/media/logs/rclone-upload-check.log"
exit 1
fi
/usr/local/bin/rclone move /hd/00/media/.local-sorted/xDRZiPinr4MQRKmZkuog3SiF/ Amazon:/NAS/xDRZiPinr4MQRKmZkuog3SiF/ -c --stats=1m --max-size=50G --transfers=1 --verbose -L --delete-after --min-age 1440m --log-file=/hd/00/media/logs/rclone-upload.log
exit


`
`
#!/bin/bash
if pidof -o %PPID -x "rclone-check.sh"; then
echo "$(date "+%d.%m.%Y %T") SKIP: rclone-check.sh already running." | tee -a "/hd/00/media/logs/rclone-check.log"
exit 1
fi
if [[ -f "/hd/00/media/acd-sorted/acd-check" ]]; then
   echo "$(date "+%d.%m.%Y %T") INFO: Check successful,drive mounted" | tee -a "/hd/00/media/logs/rclone-check.log"
else
   echo "$(date "+%d.%m.%Y %T") ERROR: Drive not mounted remount in progress" | tee -a "/hd/00/media/logs/rclone-check.log"
   fusermount -uz /hd/00/media/.acd-sorted/
   /usr/local/bin/rclone mount Amazon:/NAS /hd/00/media/.acd-sorted/ --allow-non-empty --allow-other --umask 22 | tee -a "/hd/00/media/logs/rclone-check.log"

   if [[ -f "/hd/00/media/acd-sorted/acd-check" ]]; then
      echo "$(date "+%d.%m.%Y %T") INFO: Remount successful" | tee -a "/hd/00/media/logs/rclone-check.log"
   else
      echo "$(date "+%d.%m.%Y %T") CRITICAL: Remount failed." | tee -a "/hd/00/media/logs/rclone-check.log"
   fi
fi
exit
`
This should help

**Comment by mechanimal82** [comment]
Thanks @jscottdouglas I'll try to work out how this is working and if I can make it fit into my setup. Appreciate the help!
