### ISSUE TITLE
Import Existing Movies on Disk: Many Listed as "Already Exists"

### ISSUE THREAD

**Issue by houdini3009** [Radarr/Radarr#1101]
**Description:**

When I visit **"Import Existing Movies on Disk"**, many of the movies listed are ones that I already imported and are marked as such (**"Already Exists"**). However, I don't think this is the intended behavior. Shouldn't any imported movies not be displayed in this view? Most of my movies are not shown in this view by many (50-100) are. It's not a permissions issue because I have 777'd the entire directory tree.

Additionally, every time I reload this page I get slightly different results. Many times the movies are NOT marked **"Already exists"**. When you then try to add the movie you get the **"This movie has already been added"** error.

**Radarr Version:**

0.2.0.453

**Logs:**

n/a

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by galli-leo** [comment]
Use bulk import when importing existing movies.

**Comment by galli-leo** [comment]
The non bulk import is just staying around as a legacy feature.
