### ISSUE TITLE
"a fatal error in the mono runtime " Ver. 0.2.0.453

### ISSUE THREAD

**Issue by sch1308** [Radarr/Radarr#1102]
Radarr Ver. 0.2.0.453 develop branch. 
![image](https://cloud.githubusercontent.com/assets/7896067/23780088/ad44ead2-0512-11e7-8f04-f60092114f9b.png)

**Comment by onedr0p** [comment]
This doesn't look like a error with radarr, most likely with your installed mono version, or OS.

**Comment by sch1308** [comment]
i deleted the appdata folder then used the linuxserver version of radarr docker on unraid to install as new.
