### ISSUE TITLE
Issue with Deluge 1.3.14

### ISSUE THREAD

**Issue by shinjijai** [Radarr/Radarr#1105]
**Description:**
I think it's similar to the bug [#1738](https://github.com/Sonarr/Sonarr/issues/1738) filed with Sonarr that was recently fixed. Deluge is connected to my Sonarr (v. 2.0.0.4645) install with all the same settings and such. Radarr was working with Deluge 1.3.6 until I updated it today. 

**Radarr Version:**
0.2.0.453

**Logs:**
HTTP Error - Res: [POST] https://<redacted>:443/json: 500.InternalServerError

**Comment by onedr0p** [comment]
Already fixed in nightlies
