### ISSUE TITLE
Latest update ruined it for me - Not pulling new movies, just old ones

### ISSUE THREAD

**Issue by henrikrox** [Radarr/Radarr#1110]
**Description:**

So the latest devolp update (6th march ruinde radarr for me).

I test now with office christmas party, i doesnt find it, if i test with die hard, it starts to download.
I set min availabity to "announced" but all the new movies arent being pulled. If its web-dl or remux :/

**Radarr Version:**
0.2.0.453
**Logs:**
MovieSearchService	Movie search completed. 0 reports downloaded.	18:36
DownloadDecisionMaker	No results found	18:36
MediaCoverService	Downloading Banner for [tt3216348][Incarnate] http://image.tmdb.org/t/p/original/esYrvwvNtigW09Oh12UXnSxG6Fz.jpg	18:36
NzbSearchService	Searching 1 indexers for [Incarnate]	18:36
MediaCoverService	Downloading Poster for [tt3216348][Incarnate] http://image.tmdb.org/t/p/original/3wv9bTEHDFWcLHf8RtaGk4XJ8JJ.jpg	18:36
MovieScannedHandler	[Incarnate] was recently added, performing post-add actions	18:36
DiskScanService	Scanning disk for Incarnate	18:36
RefreshMovieService	Updating Info for Incarnate	18:36
MovieService	Adding Movie [][Incarnate] Path: [H:\Movies\Incarnate (2016)]	18:36
MovieSearchService	Movie search completed. 1 reports downloaded.	18:34
DownloadService	Report sent to sabn. Die.Hard.1988.1080p.BluRay.x264.REPACK-WPi	18:34
Sabnzbd	Adding report [Die.Hard.1988.1080p.BluRay.x264.REPACK-WPi] to the queue.	18:34
DownloadDecisionMaker	Processing 47 releases	18:34
MediaCoverService	Downloading Banner for [tt0095016][Die Hard] http://image.tmdb.org/t/p/original/j31bCZR33MLwgH5IFMcGKjbr3z5.jpg	18:33
NzbSearchService	Searching 1 indexers for [Die Hard]	18:33
MediaCoverService	Downloading Poster for [tt0095016][Die Hard] http://image.tmdb.org/t/p/original/mc7MubOLcIw3MDvnuQFrO9psfCa.jpg	18:33
MovieScannedHandler	[Die Hard] was recently added, performing post-add actions	18:33
DiskScanService	Scanning disk for Die Hard	18:33
RefreshMovieService	Updating Info for Die Hard	18:33
MovieService	Adding Movie [][Die Hard] Path: [H:\Movies\Die Hard (1988)]	18:33
MovieSearchService	Movie search completed. 0 reports downloaded.	18:32
DownloadDecisionMaker	No results found	18:32
MediaCoverService	Downloading Banner for [tt1711525][Office Christmas Party] http://image.tmdb.org/t/p/original/bzguuhqUI9G8jJ3EBtJ9p12g1Lr.jpg	18:32
MediaCoverService	Downloading Poster for [tt1711525][Office Christmas Party] http://image.tmdb.org/t/p/original/cW85VlHPm3pz0anupAXHL9eTh5b.jpg	18:32
NzbSearchService	Searching 1 indexers for [Office Christmas Party]	18:32
MovieScannedHandler	[Office Christmas Party] was recently added, performing post-add actions	18:32
DiskScanService	Scanning disk for Office Christmas Party	18:32
RefreshMovieService	Updating Info for Office Christmas Party	18:31
MovieService	Adding Movie [][Office Christmas Party] Path: [H:\Movies\Office Christmas Party (2016)]	18:31

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by henrikrox** [comment]
Test with old movies and new ones, its the same indexer, and i can see the files on my indexer, it was uploaded 1-2 days ago. Radarr doesnt find the new ones, but it finds the old movies.

It worked fine before the update :/

**Comment by onedr0p** [comment]
It sounds like your indexer, what one do you use? And do they support search by imdbid?

**Comment by onedr0p** [comment]
Also please try on the latest nightly, you change change to that release in settings.

**Comment by henrikrox** [comment]
I use dognzb

Weirdly i just added the movies again, and it worked now, so maybe the indexer had issues. But its also weird because the movies that it was supposed to grab was added 2-3 days ago. Through automatic searching.

Quick question, i use ombi for adding movies to radarr, but when using ombi, it doesnt set a value inside min availability. Is this important? Because radarr has never pulled the wrong movie, it just sets the value as blank instead of predb/announced etc.

I will try nightly now

**Comment by henrikrox** [comment]
Ok nightly seems better, i can also change settings now, for whatever reason that didnt work before, the settings never saved. So i will try over the weekend and then just close this.

Only thing i wonder about now is that ombi imports all movies with blank info in min availablity, and if that causes errors

**Comment by onedr0p** [comment]
@henrikrox please open a issue with ombi to support min availablity
