### ISSUE TITLE
RSS Sync does not grab any files

### ISSUE THREAD

**Issue by fevkalbeser** [Radarr/Radarr#1112]
RSS Sync does not grab any files:

Today I noticed one of the movies in the monitored list (Assassin's Creed) was released as web-dl in almost all torrent sites. However, radarr RSS sync did not grab it. I manually checked the contents of the RSS feeds I had set up as indexers (IPTorrents, Katcr, Extratorrent and some more) and they all had the movie in various formats. When I did manual search, I was able to find a suitable release and download. 

To reproduce the issue, I added another movie which was released today (Live by Night) and did an RSS sync. Again, it was unsuccessful. I changed the profile to "any", it didn't help.

I was on "develop" when I ran into this issue, changed to "nightly" and updated to version 0.2.0.521. Didn't help.

It was able to grab from the RSS sync two days earlier.

Here are the logs:

17-3-10 23:39:31.5|Info|RssSyncService|Starting RSS Sync
17-3-10 23:39:36.0|Info|DownloadDecisionMaker|Processing 290 releases
17-3-10 23:39:39.7|Info|RssSyncService|RSS Sync Completed. Reports found: 290, Reports grabbed: 0

Any thoughts?

**Comment by galli-leo** [comment]
What RSS Interval do you have set?

**Comment by jOOc** [comment]
@fevkalbeser I had the same issue. And it was because I had set "Minimum Availability" to "PreDB". Changed it to "Announced" and then the RSS sync found the movie.

**Comment by fevkalbeser** [comment]
@jOOc Thank you very much. That solved the issue. Should be fixed though.
