### ISSUE TITLE
Page size setting not holding

### ISSUE THREAD

**Issue by mow4cash** [Radarr/Radarr#1115]
**Description:**

The page size setting won't hold. I try to change it but it usally only holds for one use and sometimes it won't save at all. I don't see anything in the logs.

**Radarr Version:**

0.2.0.453

chrome

**Comment by galli-leo** [comment]
Are you in incognito mode?

**Comment by mow4cash** [comment]
No.

**Comment by galli-leo** [comment]
Are you on the latest chrome version?

**Comment by mow4cash** [comment]
Version 57.0.2987.98 (64-bit) up to date

There was an update but I am still having the issue.

Seems to be working on firefox. How is it possible for a setting to be changed without user input?

In bulk import I was never able to get it to work with more than 50 in the list, I don't know if that is related.

**Comment by galli-leo** [comment]
Idk. If it works in fire fox, chrome might have a bug.

**Comment by galli-leo** [comment]
It works for me in chrome Version 56.0.2924.87 (64-bit). 57 might have a bug?

**Comment by mow4cash** [comment]
I think I just updated from 56.

I think this is the error, if it helps.

.vendor.js:24910 Uncaught TypeError: Cannot read property 'toString' of undefined
    at Object.setValue (vendor.js:24910)
    at child.saveSettings (main.js:14100)
    at triggerEvents (vendor.js:10851)
    at EA.trigger (vendor.js:10794)
    at child._save (main.js:8723)
    at HTMLButtonElement.bound (vendor.js:12901)
    at HTMLDivElement.dispatch (vendor.js:4830)
    at HTMLDivElement.elemData.handle (vendor.js:4498)

**Comment by galli-leo** [comment]
Hmm 57 works for me too. Might have to try it on windows. @fedoranimus could you do that?

**Comment by galli-leo** [comment]
Can you try on the latest version? Should be fixed there.

**Comment by mow4cash** [comment]
Looks to be working. You're awesome, thanks.
