### ISSUE TITLE
Update Library not scanning 2nd path

### ISSUE THREAD

**Issue by McGriddle** [Radarr/Radarr#1119]
**Description:**

I have two paths containing movies in them. Only the first path that I added has movies displaying and scanned when I click 'Update Library'.  I know radarr sees this 2nd directory because it downloaded and moved a single movie there.

I've tried removing the path, then re-adding it via both 'Bulk Import Movies' and 'Import Existing Movies on Disk' but both way movies do not show up.

Also, both paths have the same layout:
`/movies/FirstDirectory/MovieTitle (MovieYear)/MovieTitle (MovieYear).mkv`
`/movies/SecondDirectory/MovieTitle (MovieYear)/MovieTitle (MovieYear).mkv`

**Radarr Version:** 0.2.0.453

**Logs:** The logs only show movies scanned in the first directory.

**Comment by geogolem** [comment]
Each movie has a path specified... you have to make sure the movies in the one path have the rootFolder set properly...  

Its not like CouchPotato where you set all your root paths and then they all get scanned for movies.

You set root paths, but each movie has its rootPath set individually.

**Comment by onedr0p** [comment]
`/movies/FirstDirectory/` is one root folder
`/movies/SecondDirectory/` is another root folder

**Comment by McGriddle** [comment]
geogolem, good to know. I assumed it'd be like couch potato in that regard. Thanks!
