### ISSUE TITLE
Movie sets/collections

### ISSUE THREAD

**Issue by woble** [Radarr/Radarr#112]
**Feature request**
Show and manage related movies if an already added/downloaded movie belongs to a collection. Perhaps show the collections when adding a new movie as well.

**Comment by Kyrluckechuck** [comment]
Definitely agree this is a must-feature, especially when dealing with so many others libraries who already have that format for their existing library (It would be nice if this were to properly handle putting them into the existing collections)

**Comment by rubdos** [comment]
:+1:

This allows for so many more nice features in the future:

- Kodi has the notion of sets.
- "Follow" a set: when a new movie of a set gets announced, they are automatically set to watched.
- Optionally compressing the main movie list
