### ISSUE TITLE
IPTorrents via Jackett (No results returned)

### ISSUE THREAD

**Issue by mgiljum** [Radarr/Radarr#1120]
**Description:**

Attempted to add IPTorrents/Alpharatio via jackett as an indexer, which fails due to "no results returned" (log below). 

Manual search works fine in Jackett, and Radarr can search Torrentleech via Jacket without issue.

**Radarr Version:**

0.2.0.453

**Logs:**

```
17-3-11 01:16:04.5|Info|Database|Vacuuming Log database
17-3-11 01:16:04.5|Info|Database|Log database compressed
17-3-11 01:16:29.1|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- No results were returned from your indexer, please check your settings.
```

Jackett only returns:

```2017-03-11 01:19:51.3002 Info Found 0 torrentpotato releases from IPTorrents for: -```

**Comment by mgiljum** [comment]
Possibly here?

https://github.com/Radarr/Radarr/blob/50fdbd896cb1cca8bfbb3108ee0fe8bdd5acee2b/src/NzbDrone.Core/Indexers/TorrentPotato/TorrentPotatoRequestGenerator.cs#L68

**Comment by onedr0p** [comment]
We recommend to use Torznab :)

**Comment by jszolony** [comment]
I have similar issue. I was trying to add Potato feed of sceneaccess.eu tracker and it returns same error. If I try to add indexer it tries to loads 
> http://10.0.0.23:9117/potato/sceneaccess?passkey=xxxxxx&user=&search=-

which really return zero results. However if I try to load

> http://10.0.0.23:9117/potato/sceneaccess?passkey=xxxxxx&user=&search=2016

it returns some results. So I think that this "-" (as mentioned by mgiljum above) is not the best search phrase to test (at least for some trackers).

**Comment by onedr0p** [comment]
Please try using torznab over potato.
