### ISSUE TITLE
Cant find any movies after latest update

### ISSUE THREAD

**Issue by jOOc** [Radarr/Radarr#1122]
**Description:**

![image](https://cloud.githubusercontent.com/assets/9382342/23821763/bf63a4b2-063c-11e7-89fa-3faa08dd72d7.png)

**Radarr Version:**

Radarr Ver. 0.2.0.530

**Logs:**
17-3-11 09:23:42.5|Trace|Http|Req: 575 [GET] /api/movies/lookup?term=alien
17-3-11 09:23:42.5|Debug|Parser|Parsing string 'alien'
17-3-11 09:23:42.5|Debug|Parser|Unable to parse alien
17-3-11 09:23:42.5|Trace|HttpClient|Req: [GET] https://api.themoviedb.org/3/search/movie?api_key=1a7373301961d03f97f853a876dd1212&query=alien&year=&include_adult=False
17-3-11 09:23:42.5|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
17-3-11 09:23:43.0|Trace|HttpClient|Res: [GET] https://api.themoviedb.org/3/search/movie?api_key=1a7373301961d03f97f853a876dd1212&query=alien&year=&include_adult=False: 200.OK (453 ms)
17-3-11 09:23:43.0|Trace|Http|Res: 575 [GET] /api/movies/lookup?term=alien: 200.OK (510 ms)
17-3-11 09:23:43.0|Debug|Api|[GET] /api/movies/lookup?term=alien: 200.OK (510 ms)

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by jOOc** [comment]
Also new movies added to my Traktlist is not picked up when doing a new netimport sync.

**Comment by ghallford** [comment]
Same issue here

**Comment by galli-leo** [comment]
Fixed in latest release.
