### ISSUE TITLE
Api issues since the last couple updates

### ISSUE THREAD

**Issue by astlaurent** [Radarr/Radarr#1123]
I use the mp4 automator script and Since the last couple nightly updates the api call download movie scan is not working at the end of tree script. It was working fine last week. The automator script shows a key error and that is about it. I am not sure if you need anything else to troubleshoot this?

Thanks for all the hard work. Radarr is a dream come true

**Comment by sugarfunk** [comment]
Yep, I am using NZBTOMEDIA and the situation is the same.
Using debugging, Radarr is throwing 500/ unauthorized. The NZBToMedia code hasn't changed in 15 days. Was working fine Tuesday. I only know it's failing as of yesterday

**Comment by ghallford** [comment]
Same issues with nzbToMedia. I actually get the below in the logs (The movie is at the location it says it is looking but cannot find it):

17-3-11 10:51:28.8|Warn|ImportApprovedMovie|Couldn't import movie e:\Downloads\DownloadedMoviesRadarr\Little.Men.2016.1080p.BluRay.H264.AAC-RARBG\Little.Men.2016.1080p.BluRay.H264.AAC-RARBG.mp4

[v0.2.0.532] System.IO.DirectoryNotFoundException: Root folder 'C:\Program Files\Radarr\1\' was not found.
   at NzbDrone.Core.MediaFiles.MovieFileMovingService.EnsureMovieFolder(MovieFile movieFile, Movie movie, String filePath) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\MovieFileMovingService.cs:line 150
   at NzbDrone.Core.MediaFiles.MovieFileMovingService.MoveMovieFile(MovieFile movieFile, LocalMovie localMovie) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\MovieFileMovingService.cs:line 75
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeMovieFile(MovieFile movieFile, LocalMovie localMovie, Boolean copyOnly) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\UpgradeMediaFileService.cs:line 66
   at NzbDrone.Core.MediaFiles.EpisodeImport.ImportApprovedMovie.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\EpisodeImport\ImportApprovedMovie.cs:line 103

**Comment by onedr0p** [comment]
If this is a issue with everyone using nzbToMedia we might have changed something that broke nzbToMedia, I would open a issue on their GH project too.

**Comment by astlaurent** [comment]
I am using mp4automator and also opened an issue on their github. I think the end goal is the same nzbtomedia except there is a conversion piece. It seems that it is the last api call which is the download movie scan call and it points to the location of the final product for pickup. I think if you look at that api call you will see the issue

**Comment by astlaurent** [comment]
This is the call it uses. I suspect nzbtomedia uses the same

Api/command

DownloadedMovieScan

Instruct Radarr to scan the DroneFactoryFolder or a folder defined by the path variable.
Each file and folder in the DroneFactoryFolder is interpreted as separate download.

But a folder specified by the path variable is assumed to be a single download (job) and the folder name should be the release name.

The downloadClientId can be used to support this API endpoint in conjunction with Completed Download Handling, so Radarr knows that a particular download has already been imported.

Parameters

Optional:

path (string),
downloadClientId (string) (nzoid for sabnzbd, special 'drone' attribute value for nzbget, uppercase infohash for torrents),
importMode (string) = Move or Copy (Copy = Copy Or Hardlink depending on Radarr configuration) Can be used to override the default Copy for torrents with external preprocessing/transcoding/unrar.

**Comment by galli-leo** [comment]
We changed the DownloadedMovieScan command to DownloadedMovie**s**Scan.
