### ISSUE TITLE
An extra 2016 tag has added to release

### ISSUE THREAD

**Issue by greatvc** [Radarr/Radarr#1124]
Hi,

Latest release on MacOS sierra,  cannot find the release of "Why Him?" in DVD rip, couchpotato identifies and finds the release with no issue but as you can see in the screenshot radarr adds a second 2016 on the movie making undetectable (on nzbgeek the file is correctly with one "2016" tag)

![image](https://cloud.githubusercontent.com/assets/13116317/23824260/ba132ec6-067b-11e7-93b5-a94d98c5f33a.png)

many thanks.

**Comment by onedr0p** [comment]
Please switch to nightly or wait for the next release. Already fixed.

**Comment by greatvc** [comment]
oops sorry then.
Thank you again
