### ISSUE TITLE
Failling to postprocess

### ISSUE THREAD

**Issue by baikunz** [Radarr/Radarr#1126]
**Description:**

I'm using nzbToMedia to trigger Radarr postprocessing. nzbToMedia sends a "DownloadedMovieScan" command, with correct parameters. But Radarr seems to fails finding it.
Even if the file is actually there and has correct permissions.

**Radarr Version:**

Docker - Ver. 0.2.0.453

**Logs:**

Command sent by nzbToMedia to Radarr:
```
Opening URL: http://localhost:8087/radarr/api/command with PARAMS: {'path': '/home/dorian/icybox/downloads/complete/movies/Jack.Reacher.Never.Go.Back.2016.720p.BluRay.DD5.1.x264-FuzerHD', 'name': 'DownloadedMovieScan'}
```

Content of directory:
```
total 6,1G
drwxrwxrwx 2 dorian dorian 4,0K mars  11 11:52 .
drwxrwxrwx 3 dorian dorian 4,0K mars  11 03:18 ..
-rw-rw-rw- 1 dorian dorian 6,1G janv. 23 17:01 Jack.Reacher.Never.Go.Back.2016.720p.BluRay.DD5.1.x264-FuzerHD.cp(tt3393786).mkv
```

Log line in Radarr:
```
Folder/File specified for import scan [/home/dorian/icybox/downloads/complete/movies/Jack.Reacher.Never.Go.Back.2016.720p.BluRay.DD5.1.x264-FuzerHD] doesn't exist.
```

id on myself:
```
uid=1000(dorian) gid=1000(dorian) groupes=1000(dorian)
```

I'm launching the docker image with UID/GID 1000 too.

**Comment by ghallford** [comment]
Since the latest update, I also getting this in nzbget for nzbToMedia:

nzbToRadarr: Radarr: Failed to post-process - Server returned status 500!

Wasn't happening before this nightly update.

**Comment by baikunz** [comment]
Actually I was getting this error too on the last docker image I pulled from linuxserver.io.
I hoped pulling this new release would fix the issue but it's not the case.

**Comment by onedr0p** [comment]
I think the command is DownloadMoviesScan

**Comment by ghallford** [comment]
He said he fixed that on a recently closed issue. 

⁣
--
Geoff Hallford​

**Comment by baikunz** [comment]
Oh my bad, while I was checking the code triggering the error message, and found nothing weird. I figured where the problem is coming from... 
I'm using Docker and mounted my movies directory on a /movies path instead of the full path on the host. Which is why it don't find anything.
I guess I'll have to work on nzbToMedia side now.

Sorry for the bothering.
