### ISSUE TITLE
Deluge HTTP - Error Json check

### ISSUE THREAD

**Issue by fc0712** [Radarr/Radarr#1127]
Unable to retrieve queue and history items from Deluge: HTTP request failed: [500:InternalServerError] [POST] at LocalIP:port/json]

I'm running the latest version of radarr. (0.2.0.453)

It seems to be a known issue that sonarr have fixed on their end. But it doesn't seem to have been fixed in Radarr. 

Sonarr - Release log: 
Fixed Deluge 1.3.14 API support due to changed json-rpc checks. (hotfix)

Are you aware of the issue?

**Comment by onedr0p** [comment]
Already in nightly

**Comment by fc0712** [comment]
I'm using the Linux Server Docker. When will you implement in the release?

**Comment by onedr0p** [comment]
Next pre release, can't say when, maybe within a week. There's a nightly docker image by hotio/docker-radarr that is always the latest version. It's what i use, just be careful since it's a development build.
