### ISSUE TITLE
Home Page not saving "monitored only"

### ISSUE THREAD

**Issue by RyanOver9000** [Radarr/Radarr#1128]
**Description:**

Whenever I click the movies tab, it loads all my movies including unmonitored, even with monitored only chosen.  I click monitored only again and it filters them properly, but when I come back to the movies tab, it hangs and then brings up every movie.

**Radarr Version:** 0.2.0.453 on UnRAID 6.3.2 using Linuxserver.io's Docker

**Logs:**

**Comment by onedr0p** [comment]
I believe this was fixed in the nighties.

**Comment by RyanOver9000** [comment]
Thanks for the update, I'll have to wait until Linuxserver.io updates the Docker next week.
