### ISSUE TITLE
Trakt Download Folder can't be changed

### ISSUE THREAD

**Issue by jpborjas** [Radarr/Radarr#1135]
**Description:**

While looking for a few movies that SAB had just downloaded after I had just added them to Trakt, I realized that they were dropped on my / folder, not the /Volumes/PlexMedia/Movies folder, as all my other movies. When I went to the configuration for my Trakt List, I saw that the entry for Folder was empty. I clicked on it, and now it had one specific folder in it, one that belongs to a movie, and I can't change it, so I guess all my new Trakt downloaded movies are going to be dropped there. Shouldn't we be able to type a folder in or browse to it?

**Radarr Version:**

0.2.0.534 nightly 
**Logs:**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by galli-leo** [comment]
You have to first configure your folders. To do this, go to add movie, search for any movie and then select Add Path from the Path dropdown. There you can configure your folders.

After that add the newly added folder to your list. I agree it's not really intuitive. We will add this to the settings in the future.
