### ISSUE TITLE
Bug: Radarr says movie already added but not searchable via search bar

### ISSUE THREAD

**Issue by GregoryGHarding** [Radarr/Radarr#1136]
upon trying to add a movie which may already be added to db but not visible, radarr will correctly say its already added, but it cannot be found while browsing movies listing, also not searchable, db size: 3K movies

**Comment by galli-leo** [comment]
Are you on the latest nightly? That should be fixed there.

**Comment by GregoryGHarding** [comment]
I switched to the nightly now it works well. I'm replying via email can
someone close this. Thanks
