### ISSUE TITLE
Bug: Not Supporting Multiple Folders

### ISSUE THREAD

**Issue by GregoryGHarding** [Radarr/Radarr#1137]
i have two main folders for my movies;

General Movies
Kids movies

for obvious reasons i dont want these to get mixed up.

when i bulk import in radarr i choose general movies.. do the import..
this i choose the Kids movies folder and do bulk import... 
both General and Kids show up as separate folders, however as movies download the movie directory defaults to General Movies regardless of their location during import.

**Comment by fryfrog** [comment]
The root path defaults to what ever the last one you used was. When you add a new movie, pick the right root path before you add it, just like you pick the right quality profile.

FWIW, I have Kids Movies, Anime Movies and Movies and it works fine. I do occasionally forget to flip the path when I add a movie, to fix it I manually move it to the right directory and then edit the path for that movie in Radarr (or Sonarr, since it works the same way).

**Comment by GregoryGHarding** [comment]
I've been running develop branch until last night, up until that point I
have been selecting the directory correctly upon add. But later when
download occurs it would always default to General Movies. I have not tried
any on the nightly branch yet.

**Comment by fryfrog** [comment]
So you add a movie, pick the correct directory and then immediately go view it and it is wrong after adding?

**Comment by GregoryGHarding** [comment]
correct it defaults to the first directory i setup. which in this case is general movies, i have to manually change it, if i miss it and it downloads, i have to delete the file change directory, and trigger search. after that it goes to correct directory.

**Comment by GregoryGHarding** [comment]
also same goes for when i set up trakt lists i cant set up two trakt lists with different search parameters and folders they end up mirroring each other

**Comment by welle** [comment]
Me too, it will be so great to have different folder for each trakt list :)
I can add an other trakt list but I can not change the folder :(

**Comment by galli-leo** [comment]
@GregoryGHarding Lists are now fixed (It was just a visual glitch btw.)

**Comment by permster** [comment]
Is this fixed in 0.2.0.778?  I just updated to it and you can update a list and click save but when you go back in the folder field is blank.  At this point I haven't played with it enough to tell whether it's just a visual bug or not.

**Comment by galli-leo** [comment]
@permster it’s just visual again.
