### ISSUE TITLE
Bug: Connection issue with Deluge 1.3.14 released Mar '17

### ISSUE THREAD

**Issue by GregoryGHarding** [Radarr/Radarr#1138]
Radarr cannot connect to deluge after this version update.

the error i receive is:
_Unknown exception: HTTP request failed: [500:InternalServerError] [POST] at [http://10.16.0.3:9005/json]_

**Comment by ctroncoso** [comment]
check this
https://github.com/Radarr/Radarr/issues/1130#issuecomment-285904768

**Comment by GregoryGHarding** [comment]
ty will try now

**Comment by ctroncoso** [comment]
remember to close the issue if it works.

**Comment by GregoryGHarding** [comment]
that did it thanks 
#1130
