### ISSUE TITLE
Ability to toggle date when searching torznab

### ISSUE THREAD

**Issue by MattTreadwell** [Radarr/Radarr#1139]
**Description:**

Hi, I'm currently having issues regarding searches on AB through Jackett (torznab). In short, searches do work, but the `MOVIENAME MOVIEDATE` format Radarr uses for searching returns 0 results on AB (they use a separate section on their website for dates). On the other hand, using only `MOVIENAME` achieves the desired results. 

I think the best way to solve it would be by adding a date toggle in the Torznab indexer setup. This way it could be set for each individual tracker. 

**Radarr Version:**

Radarr Ver. 0.2.0.453

**Logs:**

Not needed

**Comment by galli-leo** [comment]
That is actually a very good idea. I will probably implement that for all newznab based indexers.

**Comment by galli-leo** [comment]
This is fixed in the latest release.
