### ISSUE TITLE
Import movies from various online sources

### ISSUE THREAD

**Issue by onedr0p** [Radarr/Radarr#114]
I basically copy these from couchpotato, but if there are anymore we could possibly add them. This will require significant UI enhancement and back-end work.

**List of Services you can connect to:**
- [x] CouchPotato - Import via the CouchPotato API your wanted movies
- [x] Popular Movies - http://movies.stevenlu.com/
- [x] IMDB - From any public IMDB watchlists.
- [x] Trakt - Import movies from your own watchlist
- [ ] Movieo.me - Import lists from movieo
- [ ] Blu-ray.com - Imports movies from blu-ray.com.
- [ ] iTunes - From any iTunes Store feed. Url should be the RSS link.
- [ ] IMDB - Import movies from IMDB Charts

**Each Importer will have the following configurable options on the modal:**

**Comment by simonk83** [comment]
An import from CouchPotato function would be really, really handy for a lot of people I imagine.  I know I have hundreds in there and would rather not have to add them all from scratch ;)

There is an existing little python script out there by Clinton Hall I think that exports your CP list to text file, and can reimport them if need be (it acts as a simple database backup).  Could possibly tap into that (it's better than nothing).

**Comment by kniffs** [comment]
I know it says IMDB charts, but to clarify - Does that mean public charts or is there also going to be a way to import your IMDB Watchlist?

I guess if not, we can push our Watchlist from IMDB to Trakt and pull it from there.

**Comment by onedr0p** [comment]
As long as the imdb watch list is public I don't see why not.

**Comment by kniffs** [comment]
My bad, i realized IMDB remade how lists work a long while back which makes them public if user activates. I guess i thought Charts only means IMDB's official charts, like most popular movie, top 250, etc.

**Comment by onedr0p** [comment]
They are both on the list :)

**Comment by AeonLucid** [comment]
Hummingbird is now https://kitsu.io/.

It's for anime and I'm not sure if Radarr is going to support anime movies.

**Comment by SJ50** [comment]
Please also add language option in requirements as well, so it adds movie from certain language only gets added as wanted.

**Comment by 4getit** [comment]
As for personal watchlists, it would be great but I'm afraid it's going to work via scraping only.

See the note here:
https://www.reddit.com/r/radarr/comments/5o2c5r/feature_request_browse_movies/dch9zg9/

**Comment by onedr0p** [comment]
Balls, I just got the rss feed code written :/

**Comment by bidulle95** [comment]
yes i do it IMDb watchlists

**Comment by breadcan** [comment]
+1 for the IMDb watchlist

**Comment by whodisUK** [comment]
what's the sitrep? watchlists are the priority and see that they have been worked on, but RSS is not the way to go (couchpotato scrapes for that)

are you continuing with watchlist integration and changing it to scrape @onedr0p? 

I will get try to get IMDB charts with minimal requirements implemented - don't want to duplicate efforts :)

**Comment by 4getit** [comment]
If it's a one time thing, you can export your watchlist to a .csv file (when logged in). Maybe that's an easy option to start with?

As for scraping like CP does, please note that there is a difference between public lists and watchlists.
http://www.imdb.com/list/ls123456789/
vs
http://www.imdb.com/user/ur123456789/watchlist

Although similar, the pages look different.

Either way, it would be great to somehow import IMDb watchlists.

**Comment by galli-leo** [comment]
@whodisUK @4getit I implemented a base RSS Parser that can be used for all kinds of movie RSS feeds. To get started I though the IMDb Watchlists can just use RSS for the time being. We can update them to use scraping for later.

**Comment by 4getit** [comment]
The problem with the RSS feeds is that they're limited to 250. And there doesn't seem to be any logic on what the 250 are (first, last, based on sort order etc.).

**Comment by galli-leo** [comment]
@4getit That's why I am going to add Scraping later. The RSS version is just done so we can get the ball rolling on this feature. It will also help us simplify adding other sources later.

**Comment by 4getit** [comment]
Understood. Thank you

**Comment by galli-leo** [comment]
Couchpotato and IMDb Watchlist are implemented on feature/net-import branch. Automatically adding movies is also already implemented. Only manually importing ones from list needs to be done now.

**Comment by PastaGringo** [comment]
Hello,
How can I test this ? (if it's possible now)
Do I need to build Radarr with the feature/net-import branch ?
I tried to change the branch in General settings from Radarr but I can't see updates in System menu.
Thanks!

**Comment by galli-leo** [comment]
@PastaGringo Yeah, you would need to compile it yourself. However, I would not recommend it at this moment as it's still in an early stage.

**Comment by PastaGringo** [comment]
Got it ! 
I will try just for fun ;) 
Thanks

**Comment by freshcelery** [comment]
Is it possible to add Letterboxd watchlists as an option for this feature?

**Comment by onedr0p** [comment]
@freshcelery We don't want to revert to scraping the page of a website, with that said letterboxd will have a API soon.

https://letterboxd.com/api-coming-soon/

**Comment by ming1981** [comment]
any possibility to add from itune's RSS feed?
https://rss.itunes.apple.com/us/?urlDesc=

**Comment by onedr0p** [comment]
iTunes is on our list, do you have an example list you can share with me?

**Comment by onedr0p** [comment]
Closing issue, please open up separate issue if you want a new source added.
