### ISSUE TITLE
Grabbing movie with the wrong year.

### ISSUE THREAD

**Issue by HamilcarH** [Radarr/Radarr#1140]
**Description:**

I've had that one a few times now, radarr is grabbing a movie with the same title and different year, the last one was ghost in the shell (2017) and it grabbed: Ghost.in.the.Shell.1995.1080p.BluRay.FLAC.x264-Section9.mkv

The indexer used was PassThePopcorn, built-in, not jackett.

**Radarr Version:**

Ver. 0.2.0.453

**Logs:**

Nothing in the log.

**Comment by onedr0p** [comment]
PtP searches by imdbid of the movie, are you sure this was properly tagged on ptp? It might have since been corrected there. Indexers are prone to errors, I noticed the same thing with the movie split. The indexer said it was the movie I wanted and turned out to be some dumb bowling romcom.

**Comment by HamilcarH** [comment]
Maybe you're right, it happened to me also about split :)

**Comment by kyse** [comment]
I think this is more related to the type of release Radarr matches against vs Plex metadata.  Ie, released to theaters vs released on DVD.  I have a feeling this issue will pop back up next December unless the topic is thought out.  Perhaps give an option for folks to decide which release date to use when it imports.

**Comment by onedr0p** [comment]
Closing this issue, because I believe it is a indexer mistake for labeling a movie with a incorrect imdbid. I've noticed this too.

**Comment by kyse** [comment]
Agreed, for the original poster issue, that seems fair.  But for cases where you have a library and am doing an import, the algorithm for matching using dvd release date vs theater release date is the issue.  The indexer imdbid has nothing to do with that.  Perhaps it's worth a new ticket?
