### ISSUE TITLE
Config.js:58 Uncaught TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by jamesmacwhite** [Radarr/Radarr#1143]
**Description:**

The following error is displayed in console when the save button is pressed. Happens across all settings pages.

```
Config.js:58 Uncaught TypeError: Cannot read property 'toString' of undefined
    at Object.setValue (Config.js:58)
    at child.saveSettings (UiSettingsModel.js:18)
    at triggerEvents (backbone.js:203)
    at EA.trigger (backbone.js:146)
    at child._save (SettingsLayout.js:250)
    at HTMLButtonElement.bound (lodash.underscore.js:665)
    at HTMLDivElement.dispatch (jquery.js:4670)
    at HTMLDivElement.elemData.handle (jquery.js:4338)
setValue @ Config.js:58
saveSettings @ UiSettingsModel.js:18
triggerEvents @ backbone.js:203
trigger @ backbone.js:146
_save @ SettingsLayout.js:250
bound @ lodash.underscore.js:665
dispatch @ jquery.js:4670
elemData.handle @ jquery.js:4338
```

Google Chrome
Version 56.0.2924.87 (64-bit)

**Radarr Version:**

Radarr Ver. 0.2.0.453
develop

**Comment by galli-leo** [comment]
What os are you on?

**Comment by jamesmacwhite** [comment]
@galli-leo Windows 10.

**Comment by galli-leo** [comment]
Can you try to clear cache & cookies? Also can you try another browser?

**Comment by jamesmacwhite** [comment]
@galli-leo Occurs on Firefox as well. Its a JS issue, but its coming from the server-side for sure.

I am using an Apache reverse proxy with /radarr as the URL base, not sure if that could be related.

**Comment by galli-leo** [comment]
It shouldn't be coming from the server side. Can you click on UiSettingsModel.js:18 in the error and post what you see here?

**Comment by jamesmacwhite** [comment]
Line 18 in `UiSettingsModel.js` referring to 

```Config.setValue("pageSize", this.get("pageSize"));```

**Comment by galli-leo** [comment]
And in line 13 do you see: `this.set("pageSize", Config.getValue("pageSize", 1000));`?

**Comment by jamesmacwhite** [comment]
@galli-leo Yep

![image](https://cloud.githubusercontent.com/assets/8067792/23836186/5401477a-076c-11e7-888f-3102b0e10615.png)

**Comment by galli-leo** [comment]
There's the problem. Somehow you have an old js file. Can you try a reinstall?

**Comment by galli-leo** [comment]
Oh no wait. Just upgrade to the latest version

**Comment by jamesmacwhite** [comment]
@galli-leo Confirmed fixed in release:

https://github.com/Radarr/Radarr/commit/e525f23281e3870f3029daa65036bc616eaf0d33
