### ISSUE TITLE
Request: Rearrange the order of the profiles

### ISSUE THREAD

**Issue by desimaniac** [Radarr/Radarr#1146]
**Description:**
Hi. I would like for a way to rearrange the order of the profiles on the "profile" page and to reflect the changes on the movie "adding/editing menu" as well.

Thanks.

**Radarr Version:**
0.2.0.535

**Logs:**
Not needed.

**Relevant Screenshots:**
![image](https://cloud.githubusercontent.com/assets/5501908/23837133/8aa88cea-0751-11e7-8e39-25e2bacc1422.png)

-----

![image](https://cloud.githubusercontent.com/assets/5501908/23837142/b072a852-0751-11e7-836e-6a845d2b6590.png)

**Comment by fryfrog** [comment]
Go to http://feathub.com/Radarr/Radarr and see if this request has already been made, if so... up-vote it. If it hasn't, make it. Expect this to be closed soon.

**Comment by desimaniac** [comment]
My apologies..  I will move it there.

**Comment by galli-leo** [comment]
Just a heads up: This wont happen until we implement a new UI.

**Comment by desimaniac** [comment]
Sounds good. Thank you.

**Comment by desimaniac** [comment]
Just wanted to add that it could be like how [Feedly](feedly.com) does it under the "Organize My Feeds" setting, by dragging and snapping it around with a crosshair cursor.

**Comment by piejanssens** [comment]
@galli-leo I don't see a need to wait for a complete redesign. I'm not familiar with the mechanics of the backbone of Radarr. But a hidden sort key on the profile should be sufficient. In terms of drag and drop it's as simple as this (paste in console on settings/profiles page to test):
```
$(".profiles").sortable({
        tolerance: 'pointer',
        revert: 'invalid',
        placeholder: 'profile-item thingy',
        forceHelperSize: true
    });
```
API info: https://api.jqueryui.com/sortable/

--- 

For reference, related feathub request: https://feathub.com/Radarr/Radarr/+139

**Comment by galli-leo** [comment]
I don‘t want to do any work on the UI that we will have to scrap anyways. Also, while the UI side may be trivial, we have to persist those changes which are non trivial. Additionally, I don‘t see any benefit in having the ability to reorder the profiles.

**Comment by piejanssens** [comment]
Mainly for convenience in selecting the profile when adding a new movie. Allows ordering from most to least used.
