### ISSUE TITLE
Wanted 404 Error

### ISSUE THREAD

**Issue by Fiala06** [Radarr/Radarr#1148]
This was an issue with the last update but once you hit reload it was fine. The new update released today just goes right back to the 404 error. Even after clearing the cache. This happens for all my wanted movies (57) some still in theaters some released. 

See here: http://imgur.com/a/tcovs

**Version*
0.2.0.535

**Logs:**
http://pastebin.com/pwnpy3Hn

**Comment by fryfrog** [comment]
I'm running the latest release and links in both Wanted Missing and Wanted Cutoff Unmet work fine.

Can you fire up an Incognito window and test? If it works there, you didn't quite clear the right cache and need to do more / go deeper.

**Comment by Fiala06** [comment]
Dang it, tried it at work this morning and its fine. Weird as I did use incognito mode at home. O well I see it's working. Might be time to reinstall Chrome.

**Comment by kakistos153** [comment]
Getting the same issue for sadako vs kayako. Should be a released movie. sab just grabbed it and its in its completed folder but now radarr wont import it. Think this is happening for multiple movies, lots of stuff seems to be missing.

Not sure if also related but the checked movies in this screenshot are movies that were already imported and also give 404 errors. http://imgur.com/a/uHmH1

**Comment by kakistos153** [comment]
Tested and confirmed. Browser seems to be caching settings incorrectly. Incognito worked and then Chrome worked after clearing the cache with CCleaner. would still say that browser thing is an issue, but a minor one.
