### ISSUE TITLE
Request: Movie library search will search for movie if not in library

### ISSUE THREAD

**Issue by thejacer87** [Radarr/Radarr#1149]
I think it would be nice to be able to add new movies from anywhere if you put it in the search bar. If Radarr doesn't find the movie in the library, have it grab that string and send us to the add new movie page... maybe something like this:

![image](https://cloud.githubusercontent.com/assets/6412919/23842523/fed93c66-0771-11e7-9be4-43dd9695aef5.png)

**Comment by onedr0p** [comment]
Prolly not going to happen with this UI.

**Comment by galli-leo** [comment]
Might be simple enough to include in this version.

**Comment by thejacer87** [comment]
i was going to try to do this myself, but I'm having and issue using monodevelop. never used it before and can't even open the project lol

**Comment by thejacer87** [comment]
almost done, heres what it looks like right now:
![image](https://cloud.githubusercontent.com/assets/6412919/24030114/188d53c6-0a98-11e7-8ba2-067ffa3597f2.png)

maybe some input on the UI :)

**Comment by thejacer87** [comment]
k, i literraly just need to know what the path needs to be to send the user to the add movies page with the input in the search bar

Router.js seems to indicate that i can use something like `addmovies/{some_action}/{the_query}`, but everything i try comes up empty
```js
'addmovies'                  : 'addMovies',
'addmovies/:action(/:query)' : 'addMovies',
```

**Comment by galli-leo** [comment]
Maybe change it to addMovies?

**Comment by thejacer87** [comment]
@galli-leo if you wanna take a quick look at my latest commit, for whatever reason the AddMoviesLayout.js gets initialized twice here. The first time the url options come in and it would search the movie for you, but bcuz the view gets loaded again immediatly without the args

**Comment by thejacer87** [comment]
i was able to trace the issue... the view does get loaded twice. first when addmovie is called, and then onShow... dunno if this is intentional... but anyway i was able to pass the options through the onshow as well... 

will push the commit later tonight.

**Comment by galli-leo** [comment]
Cool!
