### ISSUE TITLE
Sonarr Branding that needs to be updated to Radarr

### ISSUE THREAD

**Issue by jamma007** [Radarr/Radarr#115]
I am going to use this Issue to keep track of locations that I am still coming across Sonarr Branding.  This is not a huge priority, but I thought it would be good to keep it all on one place.

- [x] Restart message "Sonarr will restart shortly"
- [x] Shutdown message "Sonarr will shutdown shortly"
- [x] When window is shrunk the word Sonarr appears beside the logo.  
- [x] Log files are still generating Sonarr.txt
- [x] some info bubbles are still showing Sonarr
- [x] Settings > Indexers > Add Indexer > “Sonarr supports any indexer that uses the Newznab standard…”
- [x] Settings > Download Client > Remote Path Mapping (Advanced setting) > Add new Mapping > “…Sonarr will use the information provided…” & the “?” for Local Path (“Path that Sonarr…”)
- [x] Settings > General > Start-Up > “?” for Open browser on start (“…navigate to Sonarr…”)
- [x] Settings > General > Security > “?” for Authentication (“…password to access Sonarr”)
- [x] Settings > General > “?” for Analytics (“…to Sonarr servers…”)*

**Comment by onedr0p** [comment]
I updated you post to be a checklist.

**Comment by donldmn** [comment]
I had a quick run through Radarr and this is what I found. Not a huge issue though. 

Settings > Indexers > Add Indexer > “Sonarr supports any indexer that uses the Newznab standard…”
Settings > Download Client > Remote Path Mapping (Advanced setting) > Add new Mapping > “…Sonarr will use the information provided…” & the “?” for Local Path (“Path that Sonarr…”)
Settings > General > Start-Up > “?” for Open browser on start (“…navigate to Sonarr…”)
Settings > General > Security > “?” for Authentication (“…password to access Sonarr”)
Settings > General > “?” for Analytics (“…to Sonarr servers…”)*


*Issue reported here: https://github.com/Radarr/Radarr/issues/113

**Comment by onedr0p** [comment]
Added to OP post thanks @donldmn

**Comment by bakthomas** [comment]
Donate Page still links to Sonarr too

**Comment by derik0709** [comment]
In the mobile view Sonarr is next to the logo on every page.

**Comment by woble** [comment]
In regards to the Donate button, perhaps have a separate page where besides Radarr Sonarr can be mentioned as well, as they've done great work and deserve all the credit still.

**Comment by nbisson** [comment]
Adding another Sonarr Reference

Forms Authentication -> Login -> Page Title / Header (still reads Sonarr)
