### ISSUE TITLE
Import list place movies in incorrect directory 

### ISSUE THREAD

**Issue by astlaurent** [Radarr/Radarr#1153]
**Description:**

I originally saw this about a month ago while helping my friend install his Radarr. Movies that got imported from a list (he had stevenlu) got placed into c:\windows, or c:\program files\, i think there was one more as well. Either way really strange system paths. I figured he did something wrong and we killed his list as he ended up not wanting it. Now just recently i found in my installation several of the new movies coming in from my stevenlu list (i believe others as well since one of the movies affected came in from trakt) has begun the same behavior. When i went into my import lists i noticed that the folder i had selected before was gone. This makes me think that there might have been a bug or could be a bug that makes the import list lose its path. I re selected the path and now cannot get it to disappear. see screenshots. 
![2017-03-13 08_29_20-movie editor - radarr](https://cloud.githubusercontent.com/assets/11797070/23854389/94727206-07c7-11e7-8b9b-977c663e1f1e.png)

![2017-03-13 08_29_48-ballerina - radarr](https://cloud.githubusercontent.com/assets/11797070/23854394/9af09702-07c7-11e7-99f2-83196a1a188c.png)

**Radarr Version:**
0.2.0.535
**Logs:**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by galli-leo** [comment]
This is only a Ui glitch. Once you set the correct path abd click save it will stick. There's an issue already open for that.
