### ISSUE TITLE
Feature Request: Show all movies on first page like Sonarr

### ISSUE THREAD

**Issue by MrMxyzptlk** [Radarr/Radarr#1154]
Feature Request: Show all movies on first page like Sonarr.

I have over 2000 pages that I have to click through if I want to change settings on all my movies.

In Sonarr all of my TV shows (435), are showing on 1 screen for easy management.

**Comment by galli-leo** [comment]
I don't think you want to do that. It will cause extreme UI lag. If you do want it though, just edit the page size dropdown and add a 100000 option.

We will consider adding higher page sizes with a new UI that can handle that many movies.

**Comment by MrMxyzptlk** [comment]
Thank you!

**Comment by MrMxyzptlk** [comment]
I changed it to 1000 then tried 50, but it always shows 10 movies per screen (list not poster), no matter what I set.

**Comment by MrMxyzptlk** [comment]
Nevermind I got it to work...

**Comment by muddro1** [comment]
How do you  edit the page size dropdown. cant find it anywhere.
