### ISSUE TITLE
[Feature Request] Ability to set Certain Task intervals:

### ISSUE THREAD

**Issue by gold007eye** [Radarr/Radarr#1156]
**Description:**
I know this was requested under #888 and was closed, but I think at a minimum Refreshing Movie and RSS sync should be adjustable.  

The manual ability to set the Task times ourselves would be a great feature.  I know for me certain things like refreshing movie I would rather do more frequently than 1 day same with RSS sync. 

**Radarr Version:**
0.2.0.535 - Nightly

**Comment by galli-leo** [comment]
RSS Sync is already adjustable under the Indexer Settings. Why would you need to refresh movies more than once a day?

**Comment by gold007eye** [comment]
Sorry about the RSS Sync part.. I had adjusted that.  But there is a bug then in the "Interval text" that doesn't update with the Indexer RSS Sync time.
Showing "1 Hour", but the interval was set at 45 Minutes
![image](https://cloud.githubusercontent.com/assets/4365462/23860621/7ad2126c-07d5-11e7-8a58-211f1c8b235d.png)

![image](https://cloud.githubusercontent.com/assets/4365462/23860683/a82d37b4-07d5-11e7-9257-0ed61713da28.png)

As for the Movie Refresh, because anything that seems to download won't actually change the status to "Downloaded" on the movie page until the Movie refresh is done.  This should be happening after the movie has completed successfully I would think (like Sonarr does).  So I have to manually hit refresh to get the movie page to realize the file is actually there.  At the same time shouldn't it be "un-monitoring" a movie once it has downloaded the requested quality successfully so it doesn't keep searching for it?

**Comment by galli-leo** [comment]
Downloaded status should work like you describe it. If it happens again, please look out in the logs for "Movie is null for the file" and report back. And once a monitored movie meets the cutoff defined for your profile, it will stop looking for new files, but it it's still marked as monitored.

**Comment by gold007eye** [comment]
I will keep an eye out.  Is there any way to unmark the monitored status once the cutoff has been met?  This would probably prevent the other "multiple downloading" issue #1108 at the same time.

Will the error show in the logs if I just have default logging or do I need to enable a different log level.
