### ISSUE TITLE
[Feature Request] Hide Unwanted Quality Definitions in UI and Searches

### ISSUE THREAD

**Issue by gold007eye** [Radarr/Radarr#1157]
**Description:**
I think it would be great in the UI if you could hide or delete Quality Definitions that you will never use or don't want to be listed in the "Search" tab for movies.

Example:  I want Assassin's Creed to only find 720p/1080p quality.  When I go to the movie page and click the search tab, it shouldn't list anything thing like "Telesync", "Cam", "DVD", etc unless I am requesting it to find that quality.

Maybe something there if you have the Quality Definition hidden or removed then it won't show those qualities when you are actually manually searching.

I know that the file size limits can be changed via the API, but being able to make these changes via the UI would definitely be helpful  especially if not at home and working on this stuff.

So the highlighted below in the search wouldn't show based on me only looking for "720p/1080p" of the movie.
![image](https://cloud.githubusercontent.com/assets/4365462/23860402/d8afcb0a-07d4-11e7-8d19-d60c5d276023.png)

**Radarr Version:**
Latest nightly

**Comment by galli-leo** [comment]
Definitely won't happen with the current UI. I also don't really see the need for it, those qualities are neatly tucked away at the bottom, so they shouldn't interrupt you in anyway.

**Comment by darknessgp** [comment]
This is actually one of the things I absolutely HATED about CP. Hiding releases it finds. IMO, you're doing a manual search at this point and you should be shown everything that was found... That said, I LOVE the current approach which is what Sonarr does... Show all, but gives a clear indicator of why the found item wouldn't be automatically downloaded. 

![image](https://cloud.githubusercontent.com/assets/1521243/23866363/9a8c7c94-07e6-11e7-9d45-e14455452588.png)

This gives the user the ability to grab a release that doesn't match the profile, without going and modifying the profile or other filter list. There are times where, yea, I'll want to wait for a certain release and default all my movies to using that profile... but this one movie, I want to see it sooner, so it's nice to be able to just go do a manual search and grab the CAM of it.

**Comment by gold007eye** [comment]
Not saying as a replacement for everyone, but maybe an option at some point for the actual end user to decide (could be defaulted "show all") so users would have to manually change this feature.  I see what @darknessgp is saying, but using our 2 different opinions.  If it was a toggle or option that someone like him could have all Quality Options shown whereas someone like myself could have just the Quality Options that I actually want shown.

**Comment by darknessgp** [comment]
I actually like the idea of a toggle in the search tab. Maybe on the right, above the rejected column. Perhaps defaults to showing non-rejected (which includes profile not matching) and then toggles to show all.

Sorry if it my reply seemed a bit much, I just want to make sure that Radarr never hides releases... which is something I hate about CP and a big reason for me to move to Radarr.

**Comment by Qstick** [comment]
This can be done with custom filters in Aphrodite

**Comment by fryfrog** [comment]
If this were an easy toggle, people would turn this on accidentally and then wonder why they don't see search results. Just like already happens when they mess up categories. Thanks for making this possible in a difficult to do accidentally sort of way. :)

**Comment by jaxjexjox** [comment]
> If this were an easy toggle, people would turn this on accidentally and then wonder why they don't see search results. Just like already happens when they mess up categories. Thanks for making this possible in a difficult to do accidentally sort of way. :)

Why do you assume your users are idiots?  Couchpotato has had this feature since before Radarr was born and it works well.

**Comment by fryfrog** [comment]
I've done support for Sonarr and Radarr day in and day out for *years*, on issues, reddit and Discord. If something is easy to toggle w/o understanding what it does, people will do it. Then they'll describe exactly the symptoms of what that option does, w/o making the connection. Even I'm not beyond that happening. ;)
