### ISSUE TITLE
Very Large Media Libary UI Performance

### ISSUE THREAD

**Issue by michaltrow** [Radarr/Radarr#1159]
**Description:**

Currently Radarr like Sonarr before it keeps all the added Movies on a single page.

This significantly reduces performance for larger libraries 1000 movies+ and makes it virtually impossible to load from a mobile device.

Suggested fix, limit items per page, i.e. 100/50/20....

**Radarr Version:**

**Logs:**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by onedr0p** [comment]
Already done, read patch notes plzthx :)

**Comment by galli-leo** [comment]
Go to Settings-> UI. You can set a page size for how many movies you want shown there.
