### ISSUE TITLE
Docker Container

### ISSUE THREAD

**Issue by CHBMB** [Radarr/Radarr#116]
Hey guys,

I'm a member of [linuxserver.io](https://linuxserver.io) and we produce a fair amount of docker containers for various applications for Linux home servers.

We've created a build of [Radarr](https://github.com/linuxserver/docker-radarr)  and it seems to be working really well, very impressed with the amount of progress you guys/girls have made already with this project, it's awesome.

Wondered if you'd like to perhaps add our docker container as an installation option in your readme?

Currently we've had over 16 million pulls of our containers, update the images each week to incorporate upstream fixes/improvements.

Feel free to take a look at our other stuff [here.](http://tools.linuxserver.io/dockers)

If you want to talk more about this then feel free to either reply here or I've joined your Discourse chat room so you can ping me there.

Look forward to, hopefully, hearing from you soon.

CHBMB

**Comment by onedr0p** [comment]
I believe you have access to our wiki, please provide information there. Thanks.

**Comment by fedoranimus** [comment]
The readme has been updated.

**Comment by onedr0p** [comment]
oh nice 👍

**Comment by onedr0p** [comment]
Thanks for adding us, we hope to beat couchpotato to the top of your list!

**Comment by CHBMB** [comment]
You're not the only one....

**Comment by onedr0p** [comment]
Just inflate it a bit ;)
