### ISSUE TITLE
Radarr doesn't autosearch for torrents because of delay profiles. 

### ISSUE THREAD

**Issue by zzecool** [Radarr/Radarr#1162]
**Description:**
In the /settings/profiles if you choose for the delay profile "only torrents" radarr doesn't grab any release either when you add a new movie or later periodically, but you can find numerous releases using the manual search. If you switch to "Prefer Torrents" then everything works fine.

**Radarr Version:**
0.2.0.535

**Logs:**

**Comment by fryfrog** [comment]
https://github.com/Radarr/Radarr/wiki/Common-Problems#movie-added-but-not-searched

Neither Radarr nor Sonarr ever actively search for a movie unless triggered manually, they both parse "RSS" feeds. Can you clarify exactly what you mean and what you did?

For example, no matter your priority (torrents only, prefer torrents, prefer usenet, usenet only), a manually triggered search either via clicking 'add and search' when adding a movie, clicking the search icon at an existing movie or searching from the Wanted page should always work.

So should downloading a movie that is Wanted when it shows up in the RSS feeds.

My guess is you're confused about how both Sonarr and Radarr work and that what happened is no movies you wanted showed up while you were set to torrents only and one happened to show up when you switched to prefer torrents.
