### ISSUE TITLE
Request -- Unknown release for specific title. 

### ISSUE THREAD

**Issue by jerkbag** [Radarr/Radarr#1164]
**Description:**

As per the other thread, can I request a fix for this movie? 

It's Only The End Of The World

![screen shot 2017-03-13 at 3 56 42 pm](https://cloud.githubusercontent.com/assets/15878206/23872728/c76176e2-0805-11e7-84cc-19713dfb2804.png)

In general: is it possible to allow for a manual override? Basically, the user can force anything found in the search box to download as the movie in question? I imagine this would require renaming the downloaded folder before radarr tries to import it? 

Also -- AHD has searching by IMDB -- not sure if that is implemented? 

Many thanks. 
**Radarr Version:**

2.0.535

**Logs:**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by onedr0p** [comment]
I am a member of ahd, and it should be allowed. I'll take a look and see why it's being rejected. My guess is the release name.

**Comment by onedr0p** [comment]
Fixed in next release
