### ISSUE TITLE
Renaming does not recognise incorrect folder.

### ISSUE THREAD

**Issue by Jleagle** [Radarr/Radarr#1167]
**Description:**

If i manually rename a movie, it detects if the filename does/doesn't match what i have in settings. But if the folder differs from what settings says, it never detects it and therefore never gives you the option of fixing the folder name.

![screen shot 2017-03-14 at 10 45 07](https://cloud.githubusercontent.com/assets/381099/23897069/acad9918-08a3-11e7-8c72-7d3289ac1aae.png)
![screen shot 2017-03-14 at 10 45 37](https://cloud.githubusercontent.com/assets/381099/23897070/acae36b6-08a3-11e7-9bf9-9d08403eee41.png)
![screen shot 2017-03-14 at 10 45 54](https://cloud.githubusercontent.com/assets/381099/23897071/acaed3f0-08a3-11e7-9ab2-a09f6de691ba.png)

**Radarr Version:**

0.2.0.535

**Comment by fryfrog** [comment]
Right now, Radarr can't manipulate the folder name after creation.

**Comment by Jleagle** [comment]
This is in the latest version, marked as alpha. Thanks.
