### ISSUE TITLE
Merge sonarr rtorrent magnet fixes into Radarr

### ISSUE THREAD

**Issue by weirdcrap** [Radarr/Radarr#1168]
Sonarr recently committed a number of fixes that should (and in my testing do) resolve the issues many users have with meta files (magnet links) not maintaining their label and download directory after being resolved. I tested Sonarr's latest nightly and the magnet support worked flawlessly.

https://github.com/Sonarr/Sonarr/commit/3590fedeaf5b0372930f56d8f02aedc77b3c5c94 & https://github.com/Sonarr/Sonarr/commit/2326db0deabb387a1020466ae66e8cdbe5e6c2c2 & https://github.com/Sonarr/Sonarr/commit/2bf3b9e7dd799953b4f5c53db6212bf720ed41f1

This should resolve #644 and I would love to see it integrated into radarr so I can ditch my torrent black hole setup and get back to using the rtorrent xmlrpc.

**Comment by testarea1** [comment]
Need to include a typo fix https://github.com/Sonarr/Sonarr/commit/2bf3b9e7dd799953b4f5c53db6212bf720ed41f1

**Comment by weirdcrap** [comment]
Added to OP.

**Comment by onedr0p** [comment]
Fixed in next release.

**Comment by weirdcrap** [comment]
Works great so far, thanks for the quick work!
