### ISSUE TITLE
allow multiple lang with in profiles

### ISSUE THREAD

**Issue by p0nt** [Radarr/Radarr#1169]
I am dutch, and allot of movies are subbed by certain release groups and are marked as dutch releases in radarr, which means within "/settings/profiles" if I select dutch as the profile's language and connect the profile to that certain movie in my watch list it will download that release.

But sometimes it happens, dutch release does not exists... I would like it to fallback to english if dutch is not existing. And if it every happens that a dutch one is release, it should upgrade it to the dutch version the way 720p gets upgraded by 1080p when its found.

Is this maybe a nice feature for a future release?

**Comment by mitchelp** [comment]
That would be a very nice feature!! i'm missing that too

**Comment by onedr0p** [comment]
This is already on feathub.
