### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by Tatt2edone** [Radarr/Radarr#1172]
**Description:**
Is there a way to get the Calendar to look just like the Sonarr calendar? I have adjusted all options to look just like my settings in Sonarr, but Radarr doesn't change the view. Sonarr will show month view with month and year, days are listed as days with a number in the box and items to get.

Currently it shows 03-12-17 as the header for the day column and same format for Calendar title. I know its not a program issue, more of a viewing issue.

Check first that your problem is not listed in our wiki section:
* https://github.com/Radarr/Radarr/wiki/Common-Problems
* https://github.com/Radarr/Radarr/wiki/FAQ

Provide a description of the feature request or bug here, the more details the better. 
Please also try to include the following if you are reporting a bug

**Radarr Version:** 0.2.0.535

**Logs:**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by galli-leo** [comment]
You mean the 03-12-17 should be formatted differently? Yeah, I was too lazy to change that yet 😜
