### ISSUE TITLE
Unable to manually download when error : Cannot parse release name.

### ISSUE THREAD

**Issue by clementdubois** [Radarr/Radarr#1173]
**Description:**
I'm trying to download a movie but none is downloaded. So I checked for manually dowload one torrent found but I cannot because of this error : "Cannot parse release name.". This is because the name of the movie is not quite right for the radarr parsor. That's frustrating because the torrent file is good and I cannot do it because of the name parser. 
![capture d ecran 2017-03-14 a 19 02 38](https://cloud.githubusercontent.com/assets/129418/23915254/d55a08b6-08e8-11e7-9f2b-e8b099418f1e.png)

It would be nice if we can "parse" manually an unrecognize file. If the automatic parser does not work, a popin would appear where we manually write the movie name, release year and other needed infos.

WDYT ?

**Radarr Version:**
0.2.0.535

**Comment by galli-leo** [comment]
That seems like a good idea! But we would have to then keep track of all the entered information. Probably wont be implemented until a new UI comes along :/

**Comment by wolffstarr** [comment]
As a note for a work-around, I had this issue last night with an NZB, and editing the displayed name manually in sabnzbd caused it to get picked up as a wanted movie automatically by Radarr. So for a temp-fix, starting the download manually and editing its name in the download client seems to work.

**Comment by Alteration** [comment]
Also had this issue, assuming either because of no year or no quality listed

> 17-5-1 10:51:55.4|Debug|NzbSearchService|Total of 2 reports were found for [Wanderers] from 1 indexers
> 17-5-1 10:51:55.4|Info|DownloadDecisionMaker|Processing 2 releases
> 17-5-1 10:51:55.4|Debug|Parser|Parsing string 'Wanderers'
> 17-5-1 10:51:55.4|Debug|Parser|Unable to parse Wanderers
> 17-5-1 10:51:55.4|Debug|Parser|Parsing string 'Wanderers - a short film by Erik Wernquist from Erik Wernquist'
> 17-5-1 10:51:55.4|Debug|Parser|Unable to parse Wanderers - a short film by Erik Wernquist from Erik Wernquist

**Comment by galli-leo** [comment]
This is implemented on the latest version of Radarr (make sure you take a look at the parsing leniency setting)
