### ISSUE TITLE
Wrong root folder

### ISSUE THREAD

**Issue by baikunz** [Radarr/Radarr#1174]
**Description:**

Somehow Radarr is adding ```/1/``` to my root installation folder. Even if my startup directory is correctly set in the System > About section: ```Startup directory /opt/radarr```.
ImportApprovedMovie is failing because of that.

**Radarr Version:**

linuxserver docker image - Ver. **0.2.0.535**

**Logs:**

```
Couldn't import movie /home/dorian/icybox/downloads/complete/movies/Dirty.Grandpa.2016.720p.HDRip.x264.AC3.LiNE.Exclusive-CPG/Dirty.Grandpa.2016.720p.HDRip.x264.AC3.LiNE.Exclusive-CPG.cp(tt1860213).mkv: Root folder '/opt/radarr/1/' was not found.
```

**Comment by onedr0p** [comment]
Was this added via a list? if so delete the list and re-add it.

**Comment by baikunz** [comment]
Yes it was added by a list. I'm going to try to re-add the list.

**Comment by onedr0p** [comment]
I think all future movies downloaded via a list should be okay, can you test that please?

**Comment by baikunz** [comment]
Well it seems to be fixed now ! Recreating the lists was a success thanks !
