### ISSUE TITLE
[Feature Request] Separate Process path & Physical path

### ISSUE THREAD

**Issue by mechanimal82** [Radarr/Radarr#1175]
Note: Also suggested in the Sonarr git

For example; people who store their media on a mapped drive to cloud storage mounted onto the local machine (e.g. VPS with Amazon Cloud Drive). I would like to be able to set a global setting to determine the 'Process path' which will be used to organise and rename (if left blank, use the physical path from the individual movie setting). This needs to be different to the individual file 'physical path' which would be on a mounted drive.

This enables the application to sort, organise & rename. Then a custom script push the file to cloud storage where the physical path would capture the file quality etc.

**Comment by bakerboy448** [comment]
Use MergerFS and Rclone  and/or  Remote Mapping.
