### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by ghallford** [Radarr/Radarr#1177]
**Description:**

Movie downloads in NZBGet and then nzbToMedia sends location of file to Radarr to import and post process. In the logs, it see's the file properly, then calls the ImportApproveMovie and that code looks for it in the wrong directory. Some it mentions like c:\projects.... don't even exist on my system or configs.

**Radarr Version:**

0.2.0.545 (nightly)

**Logs:**

17-3-14 20:16:39.5|Debug|DownloadedMovieImportService|I.Am.Not.a.Serial.Killer.2016.1080p.BluRay.x264.AC3-BUYMORE folder quality: Bluray-1080p v1
17-3-14 20:16:39.5|Debug|DiskScanService|Scanning 'E:\Downloads\DownloadedMoviesRadarr\I.Am.Not.a.Serial.Killer.2016.1080p.BluRay.x264.AC3-BUYMORE' for video files
17-3-14 20:16:39.5|Debug|DiskScanService|1 video files were found in E:\Downloads\DownloadedMoviesRadarr\I.Am.Not.a.Serial.Killer.2016.1080p.BluRay.x264.AC3-BUYMORE
17-3-14 20:16:39.5|Debug|ImportDecisionMaker|Analyzing 1/1 files.
17-3-14 20:16:39.5|Debug|QualityParser|Trying to parse quality for E:\Downloads\DownloadedMoviesRadarr\I.Am.Not.a.Serial.Killer.2016.1080p.BluRay.x264.AC3-BUYMORE\I.Am.Not.a.Serial.Killer.2016.1080p.BluRay.x264.AC3-BUYMORE.cp(tt4303340).mp4
17-3-14 20:16:39.5|Debug|QualityParser|Trying to parse quality for I.Am.Not.a.Serial.Killer.2016.1080p.BluRay.x264.AC3-BUYMORE.cp(tt4303340).mp4
17-3-14 20:16:39.5|Debug|ImportDecisionMaker|Size: 4292975407
17-3-14 20:16:39.5|Debug|VideoFileInfoReader|Getting media info from E:\Downloads\DownloadedMoviesRadarr\I.Am.Not.a.Serial.Killer.2016.1080p.BluRay.x264.AC3-BUYMORE\I.Am.Not.a.Serial.Killer.2016.1080p.BluRay.x264.AC3-BUYMORE.cp(tt4303340).mp4
17-3-14 20:16:39.5|Debug|Parser|Parsing string 'I.Am.Not.a.Serial.Killer.2016.1080p.BluRay.x264.AC3-BUYMORE'
17-3-14 20:16:39.5|Debug|Parser|Episode Parsed. I Am Not a Serial Killer - Season 01 
17-3-14 20:16:39.5|Debug|Parser|Language parsed: English
17-3-14 20:16:39.5|Debug|QualityParser|Trying to parse quality for I.Am.Not.a.Serial.Killer.2016.1080p.BluRay.x264.AC3-BUYMORE
17-3-14 20:16:39.5|Debug|Parser|Quality parsed: Bluray-1080p v1
17-3-14 20:16:39.5|Debug|Parser|Release Group parsed: BUYMORE
17-3-14 20:16:39.5|Debug|VideoFileInfoReader|Getting media info from E:\Downloads\DownloadedMoviesRadarr\I.Am.Not.a.Serial.Killer.2016.1080p.BluRay.x264.AC3-BUYMORE\I.Am.Not.a.Serial.Killer.2016.1080p.BluRay.x264.AC3-BUYMORE.cp(tt4303340).mp4
17-3-14 20:16:39.5|Debug|DetectSample|Runtime is over 90 seconds
17-3-14 20:16:39.5|Debug|ImportApprovedMovie|Decisions: 1
17-3-14 20:16:39.5|Debug|Parser|Parsing string 'I.Am.Not.a.Serial.Killer.2016.1080p.BluRay.x264.AC3-BUYMORE'
17-3-14 20:16:39.5|Debug|Parser|Movie Parsed. I. Am Not a Serial Killer - 2016 
17-3-14 20:16:39.5|Debug|Parser|Language parsed: English
17-3-14 20:16:39.5|Debug|QualityParser|Trying to parse quality for I.Am.Not.a.Serial.Killer.2016.1080p.BluRay.x264.AC3-BUYMORE
17-3-14 20:16:39.5|Debug|Parser|Quality parsed: Bluray-1080p v1
17-3-14 20:16:39.5|Debug|Parser|Release Group parsed: BUYMORE
17-3-14 20:16:39.5|Warn|ImportApprovedMovie|Couldn't import movie E:\Downloads\DownloadedMoviesRadarr\I.Am.Not.a.Serial.Killer.2016.1080p.BluRay.x264.AC3-BUYMORE\I.Am.Not.a.Serial.Killer.2016.1080p.BluRay.x264.AC3-BUYMORE.cp(tt4303340).mp4

[v0.2.0.545] System.IO.DirectoryNotFoundException: Root folder 'C:\Program Files\Radarr\1\' was not found.
   at NzbDrone.Core.MediaFiles.MovieFileMovingService.EnsureMovieFolder(MovieFile movieFile, Movie movie, String filePath) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\MovieFileMovingService.cs:line 150
   at NzbDrone.Core.MediaFiles.MovieFileMovingService.MoveMovieFile(MovieFile movieFile, LocalMovie localMovie) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\MovieFileMovingService.cs:line 75
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeMovieFile(MovieFile movieFile, LocalMovie localMovie, Boolean copyOnly) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\UpgradeMediaFileService.cs:line 66
   at NzbDrone.Core.MediaFiles.EpisodeImport.ImportApprovedMovie.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\EpisodeImport\ImportApprovedMovie.cs:line 103

**Comment by onedr0p** [comment]
Did this movie come from a list? If so delete the list and re-add it.

**Comment by ghallford** [comment]
No it was manual add

⁣
--
Geoff Hallford​

**Comment by ghallford** [comment]
Okay, so originally it came from a list but I removed the movie altogether, and added manually but still failed. Hadn't deleted the list though. Now deleted the list and readded manually and now it works.
