### ISSUE TITLE
Skyhook Proxy?

### ISSUE THREAD

**Issue by madvtak** [Radarr/Radarr#1182]
Not sure if this is a Me problem or a Radarr problem or a 3rd party problem

![image](https://cloud.githubusercontent.com/assets/18261123/23936887/bbd60fba-0911-11e7-8bac-ed57234406fc.png)

**Radarr Version: 0.2.0.535** 

**Logs: see screenshot**

**Comment by galli-leo** [comment]
Well this is just the case when a movie is deleted from TMDB. This can often be the case with new movies, where multiple people add an entry to TMDB, so they delete the duplicates.
