### ISSUE TITLE
Films with language names in the title confuse the language detection (e.g. "The Italian Job")

### ISSUE THREAD

**Issue by knobunc** [Radarr/Radarr#1183]
**Description:**

I had "The Italian Job (1969)" in my requests list.  All of the search results were skipped because the word "Italian" in the title made radarr think they were all in Italian, and so were ignored.

**Radarr Version:**

0.2.0.535 (develop)

**Comment by galli-leo** [comment]
This should be fixed. At least it worked for "The Danish Girl". Will have to investigate.

**Comment by jOOc** [comment]
I can confirm this works without any problems on 0.2.0.549 nightly
