### ISSUE TITLE
Quality settings not save

### ISSUE THREAD

**Issue by kevincork** [Radarr/Radarr#1184]
I tried to change the quality settings arounds 10 times, but the settings are never save.

I'm getting a lot of fake, but each time go back to the settings min is back to 0b

**Comment by onedr0p** [comment]
Set a page size in ui settings, then it will save.

**Comment by kevincork** [comment]
Actually I think the issue with with everything, when I go on the web interface and I remove all the Movies , then come back by them safe. for the Quality I tried from Settings/Quality -Advanced settings
