### ISSUE TITLE
Movies keep coming back even when deleted

### ISSUE THREAD

**Issue by kevincork** [Radarr/Radarr#1186]
when I search for wanted movie, the old movie keep coming back, I delete them do it again and they coming back in loop.

**Comment by onedr0p** [comment]
Huh?

**Comment by kevincork** [comment]
Sorry, basically I download a movie, or delete from the movie list, but for some reason the movie comeback by himself and download it again and again.

**Comment by onedr0p** [comment]
Do you have a list set up?
