### ISSUE TITLE
Cutoff in Profiles does not work as expected.

### ISSUE THREAD

**Issue by wolffstarr** [Radarr/Radarr#1187]
**Description:**

Check first that your problem is not listed in our wiki section:
* https://github.com/Radarr/Radarr/wiki/Common-Problems
* https://github.com/Radarr/Radarr/wiki/FAQ

**Provide a description of the feature request or bug here, the more details the better.**

Not sure if this is a bug or a feature, but Cutoff in profiles appears to be based solely on how far down the list the cutoff functions. I personally use HD - 720p/1080p for my "default" quality, but I have it set up so that the lower qualities are preferred, since 720p is fine for most of my stuff and I'd rather save disk space.

When setting a quality cutoff, I set it to the lowest actual resolution/quality (HDTV-720p), which because of my ordering is the first entry on the list. This caused all of my movies to be listed as "Cutoff Unmet", and in fact was causing movies to download 720p replacements for 1080p movies. Once I changed my cutoff to HDTV-1080p, all the 720p movies were removed from the list.

If this is intended behavior, I'd like to suggest an "absolute quality cutoffs" option, where it lets you set a checkmark to have it use a specific absolute ordering instead of the sorted list.

**Radarr Version:**: 0.2.545 Nightly

**Logs:**: N/A

**Comment by galli-leo** [comment]
Why don't you just set the cutoff to HDTV-1080p? This would achieve the exact same results as 720p with absolute ordering.

**Comment by wolffstarr** [comment]
I did set it to that. In my opinion, the intuitive way for cutoffs to work would be for absolute quality to be set to the lowest quality, not the lowest item on the list. A situation where a 1080p movie is replaced by a 720p movie is silly automatically is silly, and nowhere in the documentation that I've looked at indicates that cutoff for a profile is based on position on the list, as opposed to absolute quality.

**Comment by galli-leo** [comment]
IMO, it makes intuitively more sense to use the order you set (I mean there is a reason the Sonarr team implemented it this way). The documentation also does not state that the absolute quality value is used. Anyways, IMO there is no such thing as "absolute quality", because that will always remain somewhat subjective.
