### ISSUE TITLE
Feature Request: Option to not create individual movie folders

### ISSUE THREAD

**Issue by pgdownload** [Radarr/Radarr#1188]
**Description:**

Radarr currently forces every download into its own folder. This is handy for people that add their own metadata files (e.g. posters) but useless otherwise. Many users simply have a MOVIES folder with all their movies in it. Can you please provide a option in settings to turn off creating a folder for each new movie?

**Radarr Version:**

All

**Comment by fryfrog** [comment]
http://feathub.com/Radarr/Radarr

^ Upvote the feature request there. This is known and the devs have committed to it being part of the first release.

**Comment by galli-leo** [comment]
Also there's already an issue for that on here (On mobile so can't link though)
