### ISSUE TITLE
Bug: Hitting BACK should return to the same place in a list (not the top of the list)

### ISSUE THREAD

**Issue by pgdownload** [Radarr/Radarr#1189]
**Description:**

Click on a movie in radar to see its individual details.
Then hit BACK on your browser to return to your complete movie list.
Radarr will jump to the top of the list instead of wear you left from.

Please ensure hitting BACK goes back to where you were and not the top of the list.

**Radarr Version:**

All

Regards

Peter Gillespie

**Comment by jknight2014** [comment]
This bug actually exists in Sonarr as well, however it has been fixed I think since this was forked.

**Comment by onedr0p** [comment]
@jknight2014 be a bro and find the commit in sonarr for us :)

**Comment by jamesmacwhite** [comment]
Looks like its related to this:

https://github.com/Sonarr/Sonarr/issues/1533

No commit to pick yet, as its part of their v3 release.
