### ISSUE TITLE
Feature Request: Calendar: Calendar Year View

### ISSUE THREAD

**Issue by diedrichg** [Radarr/Radarr#1190]
**Description:**

I would like to request a third option on the calendar page to show the entire calendar year (e.g. 2017) displayed in months. Yes, this would require scrolling, but it would give the user a big-picture overview of upcoming movies. Yes, sort of like the List view but in calendar format.

Design: You could put two months on a single row to reduce scrolling. Each day with a movie release would show a colored bar corresponding to the legend. The day could then be clicked (since it would be so too small for text) and it would then popup a larger view of that day with the movie titles which would be clickable and would take you to the movie's info page.

**Comment by fryfrog** [comment]
Make sure it isn't already a feature request at http://feathub.com/Radarr/Radarr and if it isn't, add it.

**Comment by onedr0p** [comment]
This is an old issue tagged with UI, this is very likely fixed in v3. Please let us know otherwise and I will reopen the issue.
