### ISSUE TITLE
List import broken in 0.2.0.549

### ISSUE THREAD

**Issue by 4getit** [Radarr/Radarr#1193]
It seems that one of the last nightly releases has broken the list imports.

In order to import custom lists, I formatted mine to match StevenLu's. This worked fine but when I import a list now, it shows the first item only.
No errors in the log.

**Comment by onedr0p** [comment]
delete the list and add it back, report back if it's fixed.

**Comment by 4getit** [comment]
No, no luck.

They imported fine until about 7 nightly's ago. Now when I open a new one, nothing is displayed. I am using the StevenLu format.
Yesterday, I downgraded to the 'develop' version and that worked fine. Today, back to the latest nightly and it doesn't work anymore.
