### ISSUE TITLE
Trakt list not working

### ISSUE THREAD

**Issue by rickytin** [Radarr/Radarr#1194]
Yesterday I add 5 movies and today I check and they have not been added to Radarr.
I did a test in setting and it is a succeeded.

**Comment by galli-leo** [comment]
Did you ran a netimportsync? (Located in System -> Tasks)

**Comment by rickytin** [comment]
Yes

**Comment by galli-leo** [comment]
What were the movies? Also can you provide us with the list to test or is it private?

**Comment by onedr0p** [comment]
Also, try to delete the list and add it back.

**Comment by rickytin** [comment]
Movies: Pineapple Express, Zeroville, The Lost City of Z and Casi leyendas.
I will delete the list and add it back tonight at home and I will let you know.
Thanks

**Comment by rickytin** [comment]
I delete the list and add it back and it did not work.
I try manual netimportsync and it failed.

**Comment by rickytin** [comment]
I have Imdb watchlist and it's working.

**Comment by rickytin** [comment]
Anybody else have this problem, any news on a fix.

**Comment by onedr0p** [comment]
Was there anything in the logs? Can you post the link to the list?

**Comment by rickytin** [comment]
Thanks for the help. 
Here is my list: https://trakt.tv/users/rickytin/watchlist
A question, do I need the private setting to be off for Trakt integration with Radarr or can it be on.
It has been off all this time but I would like to make it private.
I read the logs and I don't see anything related to Trakt but I am not expert.
In the log I see this error but I don't know if is related to my Trakt list:
"Error occurred while executing task NetImportSync: HTTP request failed: [404:NotFound] [GET] at [https://api.themoviedb.org/3/movie/271395?api_key=1a7373301961d03f97f853a876dd1212&append_to_response=alternative_titles%2Crelease_dates%2Cvideos&language=US]"

**Comment by onedr0p** [comment]
You can keep it private but you must authenticate your account.

![image](https://cloud.githubusercontent.com/assets/213795/24073536/20e9bb3a-0bcf-11e7-88eb-47afc9a0efc0.png)

**Comment by rickytin** [comment]
Yes it's authenticated and it have been working.
It's not working since march 15, my last movie add to Radarr with Trakt watchlist was in march 13.

**Comment by galli-leo** [comment]
@rickytin Seems like the movie cannot be found anymore on TMDB. This is usually the case, when you add an upcoming movie to your list, that then changes the TMDBID. Therefore, the old tmdbid given by trakt is invalid. Try readding the movie in trakt.

**Comment by rickytin** [comment]
Thanks but how do I know what movie is the one giving me trouble.

**Comment by rickytin** [comment]
I remove the lates movies I add in Trakt and then I have add other movies in Trakt and now it is working.
Thanks foe all the help.
