### ISSUE TITLE
Safari and page size

### ISSUE THREAD

**Issue by jc00per** [Radarr/Radarr#1197]
Safari seems to be trying to load a page size of 1000 regardless of the UI page size setting causing safari to time out and load a grey screen.
![img_0738](https://cloud.githubusercontent.com/assets/6727699/24002483/1cbcdc3e-0a1e-11e7-9781-9d5c82e27665.JPG)

**Comment by galli-leo** [comment]
The page size setting is set per browser. You can manually set it by going to Storage > Local Storage and add Radarr.pageSize and set a number there.

**Comment by jc00per** [comment]
So, maybe pagesize is the issue.  Is safari not supported?

**Comment by jc00per** [comment]
How do I fix this on iOS?

**Comment by galli-leo** [comment]
Safari should be supported. Actually no idea how to fix that on iOS.

**Comment by galli-leo** [comment]
Maybe try first connecting on a local network (So it loads faster) and then set the page size.

**Comment by jc00per** [comment]
The server running Radarr is a Synology NAS with an atom processor, so It is a little slow.  This might be the primary reasons why I am getting the timeouts.   I was able to change the page size to 25 both the iPad and desktop mac and the Radarr loaded.  I hooked my iPad up to my mac and opened the safari web inspector and did what you said... now it loads on both.  both times it was very finicky trying to add the pageSize key.  It would let me add it at first.  I am not sure what I did to finally get the key to be accepted.  This does not seem like the optimal solution to fixing a slow server and safari.

**Comment by galli-leo** [comment]
Yeah I agree. We should look into increasing the timeout.

**Comment by adgoudsmit** [comment]
For me it does not even load on my Iphone 6S. So i see all the data is loaded, but the UI is never drawn. So i'm unable to change the configuration for my phone. Is it possible to just have the default "1000" to be changed to for example 
"25"?

**Comment by leeramsay** [comment]
For those suffering this issue, a quick update how to work around on your iOS device, you need a Mac too.

https://webdesign.tutsplus.com/articles/quick-tip-using-web-inspector-to-debug-mobile-safari--webdesign-8787

^^ That guide helps you configure developer menu on Safari & Web inspector in your iOS settings. Once that's done:

1.  Launch Safari on iOS, go to your radarr URL, mine was doing the black screen with the bouncing balls business
1. Launch remote web inspector on your Mac Safari (developer -> name of iPhone -> domain name of radarr install)
1. Go to the Storage tab
1. Click 'Local Storage'
1. Double click the first empty 'Key field', enter 'Radarr.pageSize'. Hit tab to go to Value, enter '25', hit enter.
1. Refresh your iOS browser, you should find Radarr will then load.

To the best of my testing I can quit the Safari app on iOS and relaunch, it keeps this setting.

Hope this helps people until the devs get around to fixing this. Sucks if you don't have a Mac though!

**Comment by galli-leo** [comment]
@jc00per Can you delete the pageSize key on the latest nightly and try again. Default pageSize should be 250 now.
