### ISSUE TITLE
Add setting to hide unwanted links

### ISSUE THREAD

**Issue by sanderploegsma** [Radarr/Radarr#1198]
I find the main UI very cluttered with sometimes up to five 'links', some of which I won't ever use (trakt, for instance). IMO the user should be able to hide unwanted links.

**Comment by X32izzle** [comment]
This could be a selection in Settings > UI, allowing us to turn the full column off or which links are shown.

**Comment by j2ghz** [comment]
The labels are making each line twice as wide as it could be with one less label. It's very annoying.
[![screenshot](http://i.imgur.com/CsW6LjF.png)](http://i.imgur.com/CsW6LjF.png)

**Comment by onedr0p** [comment]
This is better in v3
