### ISSUE TITLE
[Feature Request] Automatically Unmonitor after Quality met

### ISSUE THREAD

**Issue by 1activegeek** [Radarr/Radarr#1199]
**Description:**
Feature Enhancement Request
Allow automatic status change from monitored to unmonitored, to allow for better sorting of content loaded in from various sources. Often there is no reason to monitor a release after say 30, 45, 60 days past successfully downloading a release that meets one of the cutoff values in quality profiles. 
This would aid in resolving other future situations that can occur from something like cleaning out old releases from your collection. If removed on the underlying storage but not through Radarr, Radarr may then pick up that it's missing and just re download it again. It can also reduce the list of items that Radarr needs to scan/search through. As collections become larger, this can become quite extensive and slow down the performance. 

**Validated it is not listed in Wiki or already an open issue**

**Comment by fryfrog** [comment]
Feature requests should go to http://feathub.com/Radarr/Radarr, but honestly this serves no purpose. It does nothing, is a noop.

**Comment by 1activegeek** [comment]
Got straightened out on another feature that will likely fit the need.
