### ISSUE TITLE
Radarr downloads movies fine but doesn't update, shows as missing.

### ISSUE THREAD

**Issue by CKyle22** [Radarr/Radarr#1203]
**Description:**

Hi, I just downloaded a movie that worked perfectly. It renamed it, put it in a folder, and moved it. So I know Radarr "saw" it. But Radarr never marked it complete.

**Radarr Version:**  0.2.0.535

**Logs:**

`17-3-16 22:37:42.4|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: Z:\Downloads\complete\Movies\MOVIE_NAME\`

This directory doesn't exist, Radarr is right. But I don't see a spot to correct it. The correct finished folder is Z:\Movies, which Radarr _**DID**_ move the movie to. Is it because it's not a UNC path? Where do I change that in Radarr? Do I have to change something in Sabnzbd?

**Comment by kakistos153** [comment]
Check the movie path in the settings of the actual movie. See if thats pointing to the same folder. make sure the paths match. I had similar problems to this and just had to update the paths of the movies.

**Comment by EWING1** [comment]
I have a similar issue where radarr does not update the status.. I receive this error:

`[/home/user/files/downloads/movie_name/movie.name.720p.BluRay.H264.AAC-RARBG.mp4] has a runtime of 0, is it a valid video file?`

Could this be related to this error?:
`mediainfo is required but was not found: libmediainfo.so.0`

**Comment by CKyle22** [comment]
That was it, thanks!

**Comment by wdghub** [comment]
[Radarr_Logs.zip](https://github.com/Radarr/Radarr/files/873238/Radarr_Logs.zip)
Similiar issue - Radarr downloaded the movie, created the Folder and renamed the file, but Status is still shown as "Missing". so radarr Downloads the same release again, and again, and again,...
The movie title is "The Edge of Seventeen - Das Jahr der Entscheidung (2016)".
Other movies do work, so it's not a general issue.

**Comment by galli-leo** [comment]
@wdghub Can you run the housekeeping Task under System -> Tasks?

**Comment by wdghub** [comment]
startet Housekeeping and now it Shows "Downloaded". Strange :)

**Comment by galli-leo** [comment]
@wdghub Not really strange, I added something there that should fix those types of errors :)

**Comment by onedr0p** [comment]
I am getting this for every movie I download now. :/ I have to run housekeeping and then refresh the movie.

**Comment by onedr0p** [comment]
For me, movies are showing as missing after downloading, I have to refresh the movie in-order for it to update the MovieFile.

**Comment by ltjdym** [comment]
Same problem here. I looked for an autoupdate every x minutes in settings but couldn't find it. For now I'm having to manually update list every so often. Any fixes?

**Comment by Phoenix2683** [comment]
I seem to have a similar issue. It is downloading some items through transmission, but doesn't get notified I think that they are done. So they stay in the completed folder transmission puts them in but don't get moved to my library folder. Radarr doesn't know they are done downloading.
