### ISSUE TITLE
Movie Naming page CSS misalignment

### ISSUE THREAD

**Issue by psarossy** [Radarr/Radarr#1204]
**Description:**
On a fresh install of Radarr, the toggle buttons on the Media Management page are not aligned, attached a photo to demonstrate.

The first switch is set in further than the rest.

![2b5c3e4ddd244bae97536020d1fb53e6](https://cloud.githubusercontent.com/assets/207358/24051450/77e52054-0b08-11e7-9590-a679a88a46d9.png)

**Radarr Version:**
0.2.0.535

**Logs:**
Not relevant

**Comment by jamesmacwhite** [comment]
This looks to be because of the `.advanced-setting` class

**Comment by galli-leo** [comment]
Fixed on latest nightly.
