### ISSUE TITLE
[FEATURE REQUEST]Instead of showing "Sample" as import rejection reason for invalid/corrupt files, show something more informing in "Activity->Queue" Tab

### ISSUE THREAD

**Issue by Rusk85** [Radarr/Radarr#1207]
**OS:**
`$ uname -a`
`Linux nas 4.9.11-1-ARCH #1 SMP PREEMPT Sun Feb 19 13:45:52 UTC 2017 x86_64 GNU/Linux`

**version as reported by radarr:**

	Version
	0.2.0.535
	Mono Version
	4.6.1 (Stable 4.6.1.3/abb06f1 Mon Oct 3 07:51:42 UTC 2016)
	AppData directory
	/var/lib/radarr
	Startup directory
	/usr/lib/radarr

**Package Info**
`$ yaourt -Qi`

	Repository     : aur
	Name           : radarr
	Version        : 0.2.0.535-1
	Description    : Movie downloader for usenet and torrents.
	Architecture   : any
	URL            : 
	AUR URL        : 
	[..] 

**Logs:**
[Link to Gist](https://gist.github.com/Rusk85/34be6311d6b3d2be2b6730993db8841f)
[Link to Direct Download as Zip](https://gist.github.com/Rusk85/34be6311d6b3d2be2b6730993db8841f/archive/38647e45f3dcc6e17dbf3ab090b38ad7f538a944.zip)

**Screenshots**
[Imgur album showing bug and radarr filesystem  permissions](http://imgur.com/a/9FoJd)

I have checked the common problems list, the FAQ and all issues and couldn't find a duplicate. By all means feel free to correct me otherwise.

**Bug Description**

I am using `Steven Lu` to automatically download `popular movies`. So far it has worked for all but two of them which are `Moana` and `Fifty Shades Darker`. In both cases it shows an activity where I can presumably import the movies. When I try It says `Movie must be chosen for each selected file` which I can't make any sense of and that appears no matter If I only check the one file showing or use the checkbox from the header row. As initial reason for import rejection it says in both cases movies were detected as samples. I looked at the files and they are physically there with the right perms (`chmod a=rw`). 
Thanks for looking into this.

**Edit**:
Fixed/Re-added links gone AWOL after editing.

**Comment by Rusk85** [comment]
Corrected pgk manager cmd and output (output was correct nonetheless)

**Comment by hotio** [comment]
Did you even bother reading your log? An iso is not a movie file and not supported by Radarr.

**Comment by Rusk85** [comment]
Nope I did not read a single line of it. Then I can safely assume this is also not a move file:
`Fifty.Shades.Darker.2017.720p.DivX.Avi.avi`

**Comment by Rusk85** [comment]
Well using .NETCoreApp 1.1 works just fine:

	static void Main(string[] args)
	{
		string input = @"Fifty.Shades.Darker.2017.720p.DivX.Avi.avi";
		Console.WriteLine(Path.GetExtension(input)); //output => .avi
		Console.ReadKey();
	}

I'll check the Mono version I have installed and see to what .NET Framework version it correlates to and I'll try it with that but I am sure it's certainly not as trivial as that assuming that radarr extracts metadata from all movie files such as duration, codec and what have you.

**Comment by Rusk85** [comment]
I am looking into it myself as well now. I've got my "production" server running on an arch linux and for development I am using a Windows machine (VS2017/ReSharper) but so far its working fine. Tried to mirror the config on my linux box as much as possible (usenet client, profiles,..). What I noticed is I couldn't add notifications for my Kodi. It threw a ValidationException being unhappy about the "host" property. At first I thought I might be the local "TLD" I have set up in my home network but same exception when using the IP of the box. Verified I could still send messages with my linux box which worked. I'll have a look into that as well unless it's a known issue. 
So I started with `Fifty Shades Darker` which completed and is being processed judging by the output. I'll update as I go along.

**Comment by Rusk85** [comment]
Okay after debugging the whole thing I saw what I expected radarr to do which is extracting metadata for the movie. 

In case of `Fifty.Shades.Darker.2017.720p.DivX.Avi.avi` it can't find any metadata at all. Well I then looked at the directory and found a readme telling me if it's not working I should install a `Codec.exe`. Windows Defender immediately sounds off when touching said file. I then took the liberty of having [virustotal.com have a go at it](https://virustotal.com/en/file/2e8b85d400a644893d67e3c38771c28d56469c273c0ea0cc0bebd6393ab87fd4/analysis/). It's some malware/virus.

So radarr was totally correct to question the validity of this particular "movie". It's probably just an `dd` generated file or something to that effect. 

What should be fixed though is the stated rejection within the `Activity -> Queue` part of radarr. Because right now it says `Sample` where I feel `Invalid File` or something along those lines would be more of a help to inform the next step to take for the user. I see If I can find an appropriate solution with my _very_ limited knowledge of the code base. 

Should I close this issue therefore and reopen a new one or just change the title? What's considered best practise in such a case?

**Comment by hotio** [comment]
No, I did not read your entire log. Apology.  I usually stop reading when the problem becomes obvious. You could try disabling "analyze video files" to see if it helps for importing your malware/iso's.

Not sure what Kodi, an OS or Sonarr supporting iso files has to do with Radarr?

I do agree that Radarr is a bit overly happen to call some errors "sample" in the UI.

**Comment by Rusk85** [comment]
Thanks for coming back to me. As for the paths, hostnames, domains, etc (in case there is a TLD reference to `muncic.local` that would be my DNS server "on-premise" 👍)  you see its all in my local network behind a router w/o any open inbound ports (not even/especially 22). So it's all good and safe. But still thanks for pointing it out.

Now as for the actual issue I looked into the code base and is very obvious that the project is in its very early stages seeing references to Episodes this and that all over the place. I thought since I am a C#.NET dev at day I might be able to contribute a little. Checked out the milestone goals for 0.2 and I'll try to PR some fixes. But the code base is just huge (like ~30 Projects in one solution?).

Anyway my thing can safely bet put in the backlog for later milestones. I think what should happen now is some serious porting of the actual functionality over from sonarr to radarr. The stuff I have come accross looked like loosely applied bandaids. Dont't mean to rain on anybodies parade. Quite on the contrary. As soon as I have seen there is a port I `yaourt -Rsu chouchpotato && yaourt -Sy radarr && systemtctl enable radarr && systemctl start radarr` and been using it ever sind (~about a week? ;)).

**Comment by hotio** [comment]
I have no idea what you are trying to say with the first part of your message, I was refering to your question about you not being able to manually import a movie... see my picture between number 2 and red line "Click to select movie"

**Comment by Rusk85** [comment]
Never-mind the first part. In fact I deleted it. Was utter noise.

Oh I never saw that. So that would allow me to chose the correct file or what? But basically I could import the movie then no matter if it was rejected?

I'm always on the lookout for some pass-time coding. Helps me relax. You know coding what I want and not what the bossman says must be done. Then again currently transitioning to agile with scrum and adding a CI/CD pipeline to our workflow. That's quit exciting as well 🔨 📦 👍 . Sorry for OT. Also is there any system to the `:<KEY>` emojis ?

**Comment by piejanssens** [comment]
+1
