### ISSUE TITLE
Allow Hardcoded subs

### ISSUE THREAD

**Issue by SuperPotatoMen** [Radarr/Radarr#1208]
**Description:**
In my opinion i like to have a switch to allow or not allow hardcoded subs.
Beceause movie versions like: 
_xxxx.xx.2016.DTS-HD.DTS.MULTISUBS.1080p.BluRay.x264.HQ-TUSAHD_

aren't bad at all. Is it possible to have a switch in the admin panel to allow auto select this kind of movies? The systems doesn't select multisubs now :(

**Radarr Version:**
0.2.0.535 

**Logs:**

**Comment by galli-leo** [comment]
Yeah I also really want that feature ;). Probably will also have a whitelist for subs. But IIRC there's an issue already on here about that. So gonna close yours
