### ISSUE TITLE
Move extra files (Subtitles, .nfo, poster artwork, etc.) just like Sonarr

### ISSUE THREAD

**Issue by woble** [Radarr/Radarr#121]
Include subtitle file(s) when performing move/copy.

**Comment by chrisallen** [comment]
Could you also include moving local `poster.jpg` artwork as well?

**Comment by Elfman72** [comment]
Would love to also have the trailer downloaded and moved (again, this idea comes from CP).

**Comment by livejamie** [comment]
Yes please

**Comment by pdf** [comment]
Now implemented in Sonarr: https://github.com/Sonarr/Sonarr/pull/1544

**Comment by onedr0p** [comment]
Neat!

**Comment by xelra** [comment]
Yes, it would be great if this could be pulled from upstream.

There are also 2 fixes out:
https://github.com/Sonarr/Sonarr/commit/47915d5e058742e60f3f1f30a0f9a829102e92c3
https://github.com/Sonarr/Sonarr/commit/081c5fc33269666dfb1033f3510a1fb8eaf93137

**Comment by fedoranimus** [comment]
First we have to get extras working in general. I have the framework in place to do so, but need to finish it up (may get some time this weekend to do so), then we can start pulling across the work done to manage subtitles specifically.

Thank you all for the links, they help a lot!

**Comment by spacecabbie** [comment]
Is there a rough eta on this feature ?

**Comment by webersnet** [comment]
Would also like to see an option to copy/move srt files in post.

**Comment by galli-leo** [comment]
@spacecabbie Rough ETA is release date of 0.2 😛

**Comment by desimaniac** [comment]
@galli-leo August 2017?

**Comment by galli-leo** [comment]
@desimaniac Yeah, maybe even later, depending on how much time I have to work on Radarr.

**Comment by desimaniac** [comment]
@galli-leo I see. Thanks for looking into this.

**Comment by gstrange42** [comment]
Preferred and other language subs downloading would be fantastic.

**Comment by f3bruary** [comment]
When implementing, please retain language codes in subtitles. e.g. The Matrix**.eng**.srt. For each subtitle found with these lang codes.

Some releases already contain multiple subtitles with their respective language codes. In this case the lang code and extension should be left intact. Other times subtitles are fetched using the download client (post processing script).

If no language code is present, then Title.ext is enough.

**Comment by Rhysers** [comment]
This would be awesome! Thanks for all your work!

**Comment by chernoes** [comment]
Any news on this?

**Comment by msdos** [comment]
Any ETA for this?  Out of curiosity, why this wasn't the default behavior in the first place?

**Comment by msdos** [comment]
I prefer to move the folder intact. Is it possible to this become an option in download client interface, "When moving, just renames the folder keeping it's original files"?

**Comment by desimaniac** [comment]
They could get the coding from upstream as Sonarr has the ability to import extra files by specifying extensions.

**Comment by chernoes** [comment]
@galli-leo ^ ?

**Comment by thenoid** [comment]
+1

**Comment by daymanbpi** [comment]
+1

**Comment by zjpleau** [comment]
+1

**Comment by tynan-cr** [comment]
Perhaps it would be good to manually specify language codes for subtitle renaming, if they are not named already? This is mostly useful for Plex integration, where subtitles should be of the form `Movie_Name (Release Date).[Language_Code].ext`

Plex info [here](https://support.plex.tv/hc/en-us/articles/200471133-Adding-Local-Subtitles-to-Your-Media). 
Language codes [here](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes). 

I recommend the implementation of this feature allows users to specify subtitle renaming upon using the `Manual Import` feature, or in the `Edit` menu for movies. This is because some filenames do not include this ISO code, but they do have a language, and Plex won't recognize this otherwise.

**Comment by mattmac24** [comment]
Any updates on this?

**Comment by DeviantEng** [comment]
+1

**Comment by BuSHari** [comment]
any update? you already have the code from sonarr

**Comment by jsaddiction** [comment]
+1 Could it also download missing artwork/trailer?  This could make the system automated enough that us "local file" / "shared kodi library" guys can spend more time watching and less time managing.  I would like to see the following features (just a request) much like couchpotato and mediaElch and others do.  These features could provide a one stop shop to manage movie files.
- Download / move "extra artwork" (actors images, fanart, posters) into subfolders of movie
- Download trailer
- upgrade trailer if higher quality is found
- Download / move / create files in the movie folder 
-- movieFileName.nfo
-- movieFileName-banner.jpg
-- movieFileName-clearart.png
-- movieFileName-disk.png
-- movieFileName-fanart.jpg
-- movieFileName-landscape.jpg
-- movieFileName-logo.jpg
-- movieFileName-poster.jpg
-- movieFileName-trailer.*

If I can help with the coding I will but I don't have much experience with the tool chain used here so I may need a little help to get started.

**Comment by msdos** [comment]
@jsaddiction I think this is a nice idea but IMHO is out of the scope of this issue. I suggest creating another one.

**Comment by woble** [comment]
@jsaddiction see #167

**Comment by Nottt** [comment]
I'm trying to make a post-processing script that does just that. However I'm stuck in some complex areas...if anyone with linux knowledge can help me, we could have a post-processing script at least

**Comment by jsaddiction** [comment]
@Nottt maybe I could be of assistance. What do you have so far? Language?

**Comment by Nottt** [comment]
@jsaddiction I have the code already to move subtitles and language, but I still have to update the logic to deal with multiple languages from different languages present. I also can handle forced subs for now. 

My to-do list now is deleting existing subs (should be easy) support multiple languages at once. I see you want to add *.jpg and *.nfo files. Should be easy to adapt my existing code for them. 

To lessen the complexity I decided to not match all languages out there. People will have to do manually edit the variables for the language they desire to keep/import. I'm using por/pt-BR/eng right now.

I'm going to sleep now as I spent a very good amount of hours into this already, but if you want to look at the code right now I think I can make a gist.

**Comment by jsaddiction** [comment]
@Nottt make a new repository and we could possibly work on this together.

**Comment by Nottt** [comment]
@jsaddiction  https://github.com/Nottt/scripts

**Comment by valantislevas** [comment]
any news about it? to copy/move proccessing also the subtitles?

**Comment by Buster14** [comment]
Any news on this? posters and nfo should be easier to implement than subtitles i think?

**Comment by Sitruk** [comment]
Also curious about the official status of this request.

**Comment by woble** [comment]
There's a pull request #2262 that implements it. It seems to be ready to be merged.

**Comment by mattmac24** [comment]
Awesome to hear. Hopefully this happens soon :)

**Comment by Buster14** [comment]
#2262 does not currently handle metadata files?

**Comment by woble** [comment]
It does not.

**Comment by Nottt** [comment]
You guys can look at my script repo to see the script I'm currently using to import subtitles.

It's very simple and assumes the files there are just one language. As my source of external subs are always the same language it works for me. Just edit the script to rename to your desired language. 

I also made a very simple, not tested yet using the same logic to import .nfo files. If someone can test it and report back to me.

**Comment by Nottt** [comment]
This script will import any subs, but it's not language aware so any language tags will be stripped.
```
#!/bin/bash
shopt -s extglob

DESTINATION=$radarr_movie_path
SOURCEPATH=$radarr_moviefile_sourcefolder
MOVIENAME=$radarr_moviefile_relativepath

for file in "$SOURCEPATH"/*(*.vtt|*.srt|*.ass) ; do
mv "$file" "$DESTINATION/${MOVIENAME%.*}.${file#*.}"
done
shopt -u extglob
```

I guess you could add another `|*.nfo` and other formats you want to import too. Add this as a post-processing script. 

This will be incorporated in my scripts soon. If anyone here has the knowledge and will to help keep developing scripts like this, I would appreciate :D Just get in touch !
