### ISSUE TITLE
Lists import triggered a re-download even it already there

### ISSUE THREAD

**Issue by PotatoQuality** [Radarr/Radarr#1210]
**Description:**

I used the option to import list from Trakt - Popular, Trakt - Trending, Trakt - BoxOffice and the StevenLu.
The problem is, if there is a dublication beceause the movie is already on one of the other list, it will trigger a second same snatch for the same movie even it already running a snatch.
Some times i got 3 or 4 exact same snatches :/
Also: when the movie already exist its look like radarr ignores it and re-snatch it anyway :(

**Radarr Version:**
0.2.0.535

**Logs:**

**Comment by SuperPotatoMen** [comment]
Maybe related to: https://github.com/Radarr/Radarr/issues/1108

**Comment by onedr0p** [comment]
there's a bug with is double searching, we have disabled the search after add (from list) until we get it sorted. I have a PR with a bunch of stuff that needs to get with lists and that''s on there.

**Comment by scoopydude2002** [comment]
Just noticed this bug too on 0.2.0.535. Wasn't aware it was related to importing but I just notice this after setting up Trakt list auto importing.

**Comment by SuperPotatoMen** [comment]
@onedr0p thanks for you quick replay :)

**Comment by Stealthii** [comment]
I believe this is related to #1263, however correct me if I'm wrong - there may be multiple ways that dual downloads are getting triggered right now.

**Comment by galli-leo** [comment]
@PotatoQuality Is this still occurring on the latest develop release?

**Comment by PotatoQuality** [comment]
@galli-leo sorry for the late response. It is still happening. 

I just re install radarr. I bulk import my file libary. And after the Sync with trakteren.tv it triggered a re download.

**Comment by galli-leo** [comment]
@PotatoQuality Do the movies that are redownloaded have their cutoff met?

**Comment by RaRaRadarr** [comment]
@galli-leo @PotatoQuality , did you manage to resolve this?
