### ISSUE TITLE
Ignoring ignore releases including these terms 

### ISSUE THREAD

**Issue by lessthantom** [Radarr/Radarr#1213]
Hey all 

Got the most recent develop installed and for the last few releases it seems radarr doesn't pay any attention to my ignore tags, but then when I go into search the release it has downloaded has the flag saying it will be ignored due to including the word korsub for example. 

Happening across the board with various films any ideas to try would be great

**Comment by galli-leo** [comment]
Is this still happening on the latest release? If yes, could you provide some logs?

**Comment by lessthantom** [comment]
I have checked for a while I think it's stopped, I'll check when I get back home and if it is I'll post up
