### ISSUE TITLE
Not downloading correct films

### ISSUE THREAD

**Issue by rosarch** [Radarr/Radarr#1215]
Have been seeing issues with incorrect movies downloaded if the film is not an original or a remake.

Not really wanting to add too much details so will be cryptic but still explain the issue.

I added a film called B&B (2017)

So far, this has been downloaded twice, a 2014 version and a 1991 version.

This has happened with similar films that are out this year.

Is this a know issue?

Logs (slightly changed)

17-3-17 21:49:54.6|Info|DiskScanService|Scanning disk for B&B
17-3-17 21:49:54.6|Info|DiskScanService|Completed scanning disk for B&B
17-3-18 01:52:09.2|Info|Nzbget|Adding report [B&B.2014.1080p.BluRay.x264-RedBlade] to the queue.
17-3-18 01:52:09.6|Info|DownloadService|Report sent to NZBget. B&B.2014.1080p.BluRay.x264-RedBlade
  
 Version
0.2.0.453
Mono Version
4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4)

**Comment by onedr0p** [comment]
Are you positive your indexer didn't mislabel the imdbid on those older ones?

**Comment by rosarch** [comment]
Hmm, looks like you could be right, each time these are grabbed from
PFMonkey, and they are showing via PF when doing a search via Hydra.

Looks like I need to raise it with them.

Thanks

[tt2771200]

**Comment by obelisk3847** [comment]
I think this might be a real issue... my system pulled down this 

Beauty And The Beast 2014 720p BluRay x264-RedBlade
Here is the IMDBID on the NZB... http://www.imdb.com/title/tt2316801/ 

Radarr is configured for this... http://www.imdb.com/title/tt2771200/

It also pulled down 
https://www.limetorrents.cc/The-Day-The-Earth-Stood-Still-1951-1080p-BluRay-x264-iKA-[NORAR][PRiME]-torrent-8718389.html

When upgrading this 
http://www.imdb.com/title/tt0970416/

I don't believe Limetorrents uses IMDBIDs in their indexes.

**Comment by galli-leo** [comment]
@obelisk3847 If you are using Jackett with limetorrent, then Jackett tries to guess the imdbid. Also most of the time the usenet indexers fix the wrong imdbs pretty quickly, but the RSS sync already grabbed them. Try doing a manual search for beauty and the beast. It should reject the 2014 one now. Also, we now check the year on the latest nightly, so that should fix all problems here.
