### ISSUE TITLE
[Wiki/Discussion]Coding Conventions 

### ISSUE THREAD

**Issue by Rusk85** [Radarr/Radarr#1216]
**Coding Conventions** should be discussed and affixed in some sort of an official document such as a wiki page or the readme. It doesn't have to be complete 200 page essay exploring every angle and side to this but It could start out as just a small list with a few key items. What I would like to have some guarantees on for instance are the following points:

- line endings in all files especially those containing source code because if you don't get them right your diffs are worthless and my recommendation would be unix-style line endings `\n`. Folks using Visual Studio can use the [Line Endings Unifier]() and enforce their line endings that way
- when to use `var` and when not and my recommendation is to use `var` only when its at a glance clear what type ends up on the left side. Here are some examples of Do's and Dont's from my perspective:

		< ------			some random examples			------>
		# <GOOD>: that's okay because the resulting type is obvious
		var hostname = "t2-ec2-small"; 
		
		# <GOOD>: that's okay too because again resulting type is obvious
		var intel1000TX = new NetworkInterfaceCard(); 
		
		# <BAD>: Don't do this
		var results = Query.Where(s => s.CleanTitle == cleanTitle);
		
		# <GOOD>: but do this instead		
		IEnumerable<Movie> results = Query.Where(s => s.CleanTitle == cleanTitle);	
		
		# <BAD>: this probably is an int and it might be enforced by the compiler
		# but I'm not sure and it might be important to know if it is float, int, ..
		# edit: well okay looking at the names granted you are not dealing with floats here but it could be Int64 instead of Int32
		var lastPossiblePage = pagingSpec.TotalRecords / pagingSpec.PageSize + 1;
		
		# <BAD>: due to muddled naming perhaps it's really hard for the uninitiated to see
		# at a glace what return type you get. So qualify the result type.
		var someFuzzyName = someFuzzyIdentifier.SomeUtterlyNebelouslyNamedMethod(someParam);
		
		# feel free to add more to this list ..
		< ------			some random examples			------>

 - Also maybe a good idea to talk in general about class/type naming schemes
 - Feel free to add ..

**Comment by AeonLucid** [comment]
If everyone uses ReSharper with the _default_ settings, the style is consistent 😄 
You have to take into account that this is a fork of Sonarr too. Not **every** single line has been touched by us.

**Comment by galli-leo** [comment]
Yeah, I just cleaned up the issue and just assigned everyone lol. But agree, since we all have free ReSharper, we should just use that (or Rider) and it shouldn't be a problem.
