### ISSUE TITLE
"Movie Folder Format" not working as it should.

### ISSUE THREAD

**Issue by frossmant** [Radarr/Radarr#1219]
**Description:**

I have tried to change the "Movie Folder Format" in "media management" under the settings menu to "{Movie.Title}.{Release Year}.{IMDb Id}" but this customization settings does not seem to work.

I've tried multiple settings and every time i add a new (non-existing) movie radarr is creating the movie folder name as "{Movie.Title}.{Release Year}" ignoring my custom-settings.

**Radarr Version:**
0.2.0.535 - 2017-03-12

**Logs:**
Adding Movie [][My Movie] Path: [/volume1/video/movies/my.movie.2015]

**Comment by 19wolf** [comment]
I'm also having this problem

**Comment by galli-leo** [comment]
The problem here is that we only get the IMDb Id after we already have created the folder. We have a branch working where folders are renamed, but need to test it some more before it can be merged.
