### ISSUE TITLE
/api/history nullreferenceexception error

### ISSUE THREAD

**Issue by cblakely** [Radarr/Radarr#1221]
Radarr Version 0.2.0.535
Mono Version 4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4)
Docker version 1.13.1, build 092cba3 on Ubuntu 16.04
Container version: linuxserver/radarr, latest, 021bc74c5607

Radarr application in general works fine, except when making API call to history an error is recieved:

```
curl http://localhost:7878/api/history?api-key=[key removed]
{
  "message": "Object reference not set to an instance of an object",
  "description": "System.NullReferenceException: Object reference not set to an instance of an object\n  at NzbDrone.Api.REST.RestModule`1[TResource].<set_GetResourcePaged>b__35_0 (System.Object options) [0x00017] in C:\\projects\\radarr-usby1\\src\\NzbDrone.Api\\REST\\RestModule.cs:129 \n  at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)\n  at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, CancellationToken context) <0x41817550 + 0x0013b> in <filename unknown>:0 "
}
```

I have tested with an empty history in the web GUI, but I would not expect an error condition for this, instead an empty response, or "no content" 204 status.

Testing against a live system with actual activity provides the same null-ref response.

**Comment by galli-leo** [comment]
You have to pass paging parameters. Try to look at the network requests our UI does to see how it's done.

**Comment by cblakely** [comment]
Thanks for responding.

1. this is new behavior, older versions didn't have such a requirement (So things change that's OK)
2. that sort of violates the spirit of a rest API - you should never be returning a stack trace, either set a sane default for pagingSpec on GET (that any UI use of the method would override anyway), or return a 400 with an error message stating missing properties.

I will look through the code and put in a pull request for #2 if I get some free time.

**Comment by oziee** [comment]
I am looking into this too atm.. in the wiki https://github.com/Radarr/Radarr/wiki/API:History it states there are no required params only optional items

what do you mean by paging params??
