### ISSUE TITLE
[Feature Request] Preferred File Sizes

### ISSUE THREAD

**Issue by some-guy-23** [Radarr/Radarr#1224]
For myself, and I'm guessing others as well, there is a file size that is "preferred" and a file size that is "acceptable". It would be great to have options to set this, and have Radarr only search for preferred file size initially, before falling back to simply getting an "acceptable" file size.

I think the UI for the quality page could be pretty easily adapted to support something like this. For example, you could have when "Advanced Settings" are shown, every quality has a secondary file size limit slider show up labeled "Preferred". You could then have a global option that says to wait for this preferred size for X days. If none is found, it will then go back to the normal file size restrictions for filtering releases.

Here is an example of how that might look - http://i.imgur.com/ehpxbaI.png

There are many alternative ways this could be done as well. For example you could stick to just a single slider (which would then be preferred values). Then advanced settings would show options for acceptable relative to preferred, e.g. "up to 20% (number field) larger or smaller (select)".

**Comment by Qstick** [comment]
Believe this is done with custom formats
