### ISSUE TITLE
Wrong folders for movies imported from lists  (bug)

### ISSUE THREAD

**Issue by ksbansal** [Radarr/Radarr#1227]
**Description:**
Can't select folders for lists. For some reason when I select a folder for a list, it changes every list to that same folder.
Also once a movie is imported from a list, the folder always changes to C:\ProgramData\Radarr\Bin\1\ movie name here.

Check first that your problem is not listed in our wiki section:
* https://github.com/Radarr/Radarr/wiki/Common-Problems
* https://github.com/Radarr/Radarr/wiki/FAQ

Provide a description of the feature request or bug here, the more details the better. 
Please also try to include the following if you are reporting a bug

**Radarr Version:**
0.2.0.535
**Logs:**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by onedr0p** [comment]
Delete the list and add it back.

**Comment by onedr0p** [comment]
Every list having the same folder is just a UI bug
