### ISSUE TITLE
Cannot select ANY path after update

### ISSUE THREAD

**Issue by gtwy** [Radarr/Radarr#1228]
**Description:**

While there are already a few bugs reported regarding selecting folders, I cannot select ANY folders for lists. When I edit or create a new list, "Folder:" is a drop down box that just reads "Select Path." Clicking it does not do anything. There's nowhere to type a path in manually, either.

![capture](https://cloud.githubusercontent.com/assets/11441407/24089821/06c0b284-0d11-11e7-9909-2a40da54f74c.PNG)

When I attempted to start downloading from lists, it tried to download to "/Select Path/Movie Name"

**Radarr Version:**

Version 0.2.0.535
Mono Version 4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4)
AppData directory /home/tor/.config/Radarr
Startup directory /opt/Radarr

**Comment by galli-leo** [comment]
Did you add your paths yet?

**Comment by galli-leo** [comment]
By going to add movie and searching for any movie and then selecting add new path?

**Comment by gtwy** [comment]
I tried it that way as well. I can add and edit paths on the movies page
but they don't carry over to the lists.

Sincerely,

James Watt
President

Tech Direct Services
412-303-1380 (9am-5pm)
888-261-2258 (24/7)

**Comment by galli-leo** [comment]
Can you try a different browser?

**Comment by gtwy** [comment]
I blew it away and started over. After adding at least 1 film manually, it
now let's me set the directory as you indicated earlier.

Thank you.

**Comment by galli-leo** [comment]
This should be fixed on latest nightly. Can you verify that?
