### ISSUE TITLE
Importing from list only fetches last movie on IMDB sourced lists

### ISSUE THREAD

**Issue by VanCityGuy** [Radarr/Radarr#1229]
**Description:**

I have tried two IMDB lists, one from a list I found on the site, and another from my watchlist. On both attempts when I add the list, and then select fetch list, it only fetches the last movie on the list. Lists from Trakt seem to be working fine.

**Radarr Version:**

0.2.0.559

**Logs:**

No relevant logs

**Comment by VanCityGuy** [comment]
Just pinging this issue to see if you guys had any other reports of similar or could duplicate it?

I'm on the nightly build, and the most recent commit is still having the same issue.

Thanks!

**Comment by galli-leo** [comment]
Could it be that you already have added all the movies of that list? How many movies are on that list?

**Comment by fevkalbeser** [comment]
I have the exact same issue. Additionally, it seems that radarr does not automatically fetch and import the movies added to the IMDB watchlist.

**Comment by galli-leo** [comment]
@fevkalbeser How many movies do you have on that list?

**Comment by fevkalbeser** [comment]
@galli-leo Curently 49. To reproduce the issue I added two movies and only the last one added appears when I click fetch list. They are both added at the same time. And as I mentioned, it does not auto grab the movies in the list. List update interval is 60 minutes.
![radarr1](https://cloud.githubusercontent.com/assets/26334331/24300808/5650914a-10b6-11e7-8ebd-d8cff0c29fd6.JPG)
![radarr2](https://cloud.githubusercontent.com/assets/26334331/24300817/5c51dae0-10b6-11e7-9f11-eaf95f1372d1.JPG)

**Comment by VanCityGuy** [comment]
Same issues here. I have 38 movies on my watchlist, and maybe one or two are in my library currently.

**Comment by fevkalbeser** [comment]
Problem solved with the 0.2.0.564 nightly update. Also automatically fetching. Thanks.
