### ISSUE TITLE
Radarr should not identify HDRip as web-dl

### ISSUE THREAD

**Issue by jpat0000** [Radarr/Radarr#1234]
Can we please get a separate quality for HDRip? web-dl is often sourced from itunes, a direct download/copy. HDRip is often a screen captured version of a source, typically with korean subs. I would like to have some early releases which are HDRips upgrade to web-dl later, but that currently wont happen.

**Comment by glennols** [comment]
I would like this aswell

**Comment by galli-leo** [comment]
But usually when a web-dl comes out the bluray will be released too anyways, so you can just upgrade to that?

**Comment by Quiksmage** [comment]
From my experience, Korean Sub WEB-DL's come out a good few months before the bluray hits.

**Comment by galli-leo** [comment]
Can be made by yourself via custom formats.

**Comment by speedyflipper** [comment]
I've had this issue today and yesterday where a HDRip was downloading with hard coded Korean Subs and was being identified as bluray
