### ISSUE TITLE
Support Trakt private accounts - list importing

### ISSUE THREAD

**Issue by bbaraniec** [Radarr/Radarr#1235]
I have few accounts I would like to import watch lists from. All those accounts are private. Are you planning to implement some auth method for private accounts?

**Comment by lordzkin** [comment]
I just set up a trakt account, set to private, and was able to import the anticipated list without any issues.  Did you get a denied message of some sort when you tried?

**Comment by galli-leo** [comment]
You can authenticate your trakt account in the lists settings.

**Comment by bbaraniec** [comment]
Like I said I was looking for solution to authenticate multiple accounts but I've found work around.
Your "main" account has to be allowed to follow additional accounts.
But there is another issue. Trakt allows dots in username but radarr doesn't allow it.
There you have two users watchlists to test it:
https://trakt.tv/users/radarrtest/watchlist
https://trakt.tv/users/radarr-test/watchlist 

Please note that there is "-" instead of "."in address bar, but username has dot: https://trakt.tv/users/radarr-test
