### ISSUE TITLE
OS X - Crashes on open

### ISSUE THREAD

**Issue by dafzthomas** [Radarr/Radarr#1237]
Downloaded 0.2.0.453 OSX App and it does not open.

From activity monitor is shows up and disappears around 5 seconds later as terminated.

Anyone else having this issue? What system files need to be cleared to try and start again if anything's gone wrong?

I've also tried the 4 previous pre-release versions.

**Comment by Hubszo** [comment]
No problems on OS X Yosemite. How do you start Radarr? Don't launch from Applications but from Finder with right-click and then open (if I remember correctly - sorry at work right now with Windows machine, but can check later when back home).

**Comment by dafzthomas** [comment]
@Hubszo Any way I open it has the same effect, in the Applications folder, out - double clicking it, right click and open, all results in a crash 5 seconds later. (I'm on macOS Sierra)

**Comment by dafzthomas** [comment]
Seems my DB was corrupt without any backups to go back to... Oh well, start again!
