### ISSUE TITLE
Request: Media management option to NOT create movie folders

### ISSUE THREAD

**Issue by tjhobbes** [Radarr/Radarr#1238]
An option to have movie files moved into one single folder, and not create subfolders for each individual movie. Excellent product thus far, I already manage media in folders but when creating individual folders for each file it becomes unruly and causes issues with media servers (plex, emby, upnp, etc..) in that you now have to navigate extra folder depths to play movies.

**Radarr Version: 0.2.0.535

**Comment by galli-leo** [comment]
There is already an issue open for this.
