### ISSUE TITLE
[Feature Request] Cover Art support For Lists

### ISSUE THREAD

**Issue by zero77** [Radarr/Radarr#1239]
Can you add cover art next to the film title when adding from your list.
Thanks

**Comment by lattedesu** [comment]
Huge +1 👍 

It'd be awesome if we could see the cover art, just like the main page in list fetches. In the current state, from the lists, choosing is a bit hard.

**Comment by galli-leo** [comment]
Probably wont happen until we get a new Ui

**Comment by galli-leo** [comment]
This is implemented on the latest nightly when using Discover new movies with supported lists.
