### ISSUE TITLE
Change File Date option does not appear to work

### ISSUE THREAD

**Issue by chrisallen** [Radarr/Radarr#124]
The `Change File Date` option when import/rescanning files does not seem to work. I had hoped it would set the file Date created and date modified to the earliest release date from ThemovieDB

![image](https://cloud.githubusercontent.com/assets/203867/21828938/47d72760-d7f8-11e6-9282-b491c051a525.png)

**Comment by chrisallen** [comment]
Is there a chance this can be looked into now that the renamer is working correctly?

**Comment by onedr0p** [comment]
I make it a higher priority :) Not sure when we'll get to it though,
