### ISSUE TITLE
[Feature Request] Extra Options For Backups

### ISSUE THREAD

**Issue by zero77** [Radarr/Radarr#1240]
Can you add the option to set a folder for backup files to be automatically saved to and how often this should happen.
Thanks

**Comment by pgdownload** [comment]
I'd like some way to save your current wanted list. Had a install issue and realised my 50+ collection of upcoming would be almost impossible to put back together again. Even just the option to download a text file from the Settings menu would be enough.

**Comment by galli-leo** [comment]
Backups are automatically saved every week and before every update.
