### ISSUE TITLE
movies handled by torrents are being moved to folder outside of the specified folder

### ISSUE THREAD

**Issue by GitHub010931** [Radarr/Radarr#1241]
I use qbittorrent to handle torrents and when adding more than a few movies to my synced trakt list, it seems to move some certain movies into the folder one level above. For reference, qbittorent is set to limit to max of 3 active downloads.

- I have qBittorrent download torrents by default to D:\Downloads
- Whenever i add movies using radarr, it typically downloads movies into D:\Downloads\radarr
- Whenever the torrent is finished downloading, Completed Download Handling moves the actual movie into my movies folder located in D:\Movies, and deletes all the files in D:\Downloads\radarr that are not the movie

For some reason, i added about 20 movies, certain files were being downloaded to the D:\Downloads folder instead of D:\Downloads\radarr. This makes it an issue as then the movie stays sitting in that folder, and does not automatically get pulled into my movie folder location. I have to go to Wanted section and manually import the video file, match it to a correct movie then it is completed.

**Radarr Version:** 0.2.0.535 - 03/12/2017

**Comment by pikachukaki** [comment]
Same problem with utorrent but im quite sure its torrents app problem when no folder is given then they go to downloads

**Comment by galli-leo** [comment]
This seems like a problem with your downloader.
