### ISSUE TITLE
API endpoint ReleasePushModule fails for specific releases

### ISSUE THREAD

**Issue by nero01** [Radarr/Radarr#1242]
Hello,
first thanks for creating this wonderful application.

I get an error from the release push endpoint, when i try to push some specific torrent releases using the following code:

`/usr/bin/curl -v -i -H "Accept: application/json" -H "Content-Type: application/json" -H "X-Api-Key: APIKEY" -X POST -d '{"title":"The.Great.Wall.German.DL.AC3.Dubbed.1080p.WebHD.h264-PsO","downloadUrl":"RELEASEURL","downloadProtocol":"torrent","publishDate":"2017-01-01"}' http://RADARR_ENDPOINT:PORT/api/release/push`

I am running radarr using the "--debug" and can see the following error message:

`System.InvalidOperationException: Sequence contains no elements`

I analyzed the source code and found that the error is thrown in the following object on line 45-47: 
`Radarr/src/NzbDrone.Api/Indexers/ReleasePushModule.cs`

`var decisions = _downloadDecisionMaker.GetRssDecision(new List<ReleaseInfo> { info });
   _downloadDecisionProcessor.ProcessDecisions(decisions);
   return MapDecisions(decisions).First().AsResponse();`

The error is thrown because the command (First) does not contain any elements.

Why does the decision process fail in this case? 

**Radarr Version:**
0.2.0.559
Mono Version 4.6.2 (Stable 4.6.2.7)
Log:
[log.txt](https://github.com/Radarr/Radarr/files/859329/log.txt)

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by galli-leo** [comment]
Try adding the year to the release title after the movie title.

**Comment by nero01** [comment]
Thanks a lot that was the solution to my issue. Why is the year field so
important? Why does Radarr not pull that information from tmdb/imdb or
trakt?

2017-03-21 22:21 GMT+01:00 Leonardo Galli <notifications@github.com>:

**Comment by galli-leo** [comment]
Two reasons:
1. Radarr's parser uses the year as an "anchorpoint" to determine where the movie title ends and the tags (such as quality, release group, etc.) start.
2. The year in the name of a release is used to determine whether a movie really matches what you tell radarr it is. If you e.g. push The Beauty and the Beast, Radarr needs to know which one, 19something or 2017.
