### ISSUE TITLE
Library doesn't list .mkv files

### ISSUE THREAD

**Issue by bnm12** [Radarr/Radarr#1245]
I've had an issue lately with files I know are downloaded showing up as missing. Looking closer at Radarr in the history it says that the file was sent to download and then imported to the correct path and it does in fact exist in the folder on disk however it still shows up as missing - size 0 bytes in Radarr. After a little while i realized that all the affected files were .mkv files and after trying a .mp4 file for the same movies (existing side by side with the .mkv file) it picks that one up just fine.

Version
0.2.0.535
Mono Version
3.12.1 (mono-3.12.0-branch/0849ec7 Wed Jun 3 23:08:05 CEST 2015)

I don't see anything unusual related to this in the logs, it says checking for files, and then finished checking for files (or scanning disk or whatever is the exact phrase in the log)

**Comment by galli-leo** [comment]
MKVs shouldn't be an issue. Can you look for "Movie is null for the file" in the logs?

**Comment by galli-leo** [comment]
MKVs shouldn't be an issue. Can you look for "Movie is null for the file" in the logs?

**Comment by bnm12** [comment]
Not finding it in any of my logs, but it is working now, so that's great and weird.

I was messing wit it for hours last night doing complete library scans etc. but nothing. 
All the movies which had issues last night (and had been downloaded at some point in the past week or so) now shows up. :S 

Sorry I know it's not a really good report... 
Feel free to close the bug, I guess it must have been something in my environment which was weird...

**Comment by galli-leo** [comment]
No it's a known issue. Somehow, sometimes, some files are not properly linked to their movies. They are known to Radarr, but are not known to the movie, so they show up as missing. I added a periodic command to fix those linking issues, but that's only mitigating the symptoms. I will close this issue for now.

**Comment by Masiosare** [comment]
This is still happening. I've made some experimentation and found some patterns.

This happens if there is two files with different extensions on the same folder, and the files are named different as the Standard movie format

SMF:  {Movie Title} ({Release Year})

Files:

Star Wars.avi
Star Wars.mkv

This will only detect the .avi file, ignoring the mkv (but the .mkv file is showing on the rename file dialog) 

If i delete the .avi, the .mkv still wont get recognized.

But if I change the .mkv file to the standard movie format, then the .mkv file gets picked, for example
Star Wars (1977).mkv

I don't know if there is some discrepancy to get the file recognized and the SMF, but that might be it. 

Feel free to ask me for more info

**Comment by galli-leo** [comment]
The issue here prolly was that

**Comment by galli-leo** [comment]
What probably happened was that Radarr saw both files, registered them both and linked the first one (avi). Then when the avi was deleted, it had already scanned the mkv so it did not add it again. Try deleting and then readding the movie after deleting the avi.

**Comment by bnm12** [comment]
This wasn't the issue specifically here but some of the elements might have been the same. I only had the .mkv file, I only downloaded the .avi later to test (Being a programmer myself and wanting to explore the issue a bit before reporting it). Also the file was imported and renamed by Radarr so it had the correct naming.

**Comment by Masiosare** [comment]
Deleting and rescanning didn't work. It worked until I changed the SMF, that's why I found it odd.
Probably it could have something to do with the file rename. But simply deleting the .avi and scanning didnt pick the .mkv file.

**Comment by galli-leo** [comment]
I will try and see if I can reproduce it

**Comment by sgtsquiggs** [comment]
I'm having the same issue. I renamed a .mkv that was not being detected to .avi and it was recognized.

Not happening to all files though? I have plenty of mkv recognized in my library.

In my case, the unrecognized was:

`/share/movies/2 Fast 2 Furious (2003)/2 Fast 2 Furious.mkv`

After renaming the file back to .mkv and refreshing in radarr, it was again marked as missing.

**Comment by galli-leo** [comment]
@sgtsquiggs That's probably related to another error where sometimes movie files are not properly linked to the movie. Try running the housekeeping task under System -> Tasks. (Your scenario worked fine for me.)

**Comment by sgtsquiggs** [comment]
@galli-leo - this issue resolved itself. Every remaining "missing" movie is legit missing.
