### ISSUE TITLE
Depending on quality to specific folder

### ISSUE THREAD

**Issue by mitchelp** [Radarr/Radarr#1246]
Hi Guys,

I got a feature request, it would be nice if you can let Radarr postprocess movies depending on quality. To explain my situation.

I have a Plex server running, and I don't want people watching by me to have access to my 4K content. Because when they start watching and my server starts the transcoding it will hurt my server so much that it won't be able function anymore.

What I would like to achieve is the following:
When Radarr picks a normal release for example 1080p move on finish to: /plex/Movies
When Radarr picks a UHD release 2160p move on finish to: /plex/4k-uhd

Where the profile searches for both. So it will look for 1080p. But also for 2160p. Only depending on the picked quality it needs to decide the destination folder.

So I could give certain people access to the 4k library in plex and certain only to the Movie library in plex.

Or am I asking for something that already exist?

Wondering what you guys think about this! Let me know! 👍

**Comment by galli-leo** [comment]
We will not add options to change the path anytime soon :/

**Comment by corydorning** [comment]
with 4k being more and more common, this would be a HUGE +1 for me. I have a 4TB drive that i'd like to download the 4k movies but need the ability to change the path based on the quality.

would donations get this going? :)

**Comment by titan04** [comment]
I was wanting to do the same thing and found a workaround for this scenario.  In docker this is more simple, but just run a second radarr instance on another port.  This allows you to create another category in your downloader for UHD content.

**Comment by RDDJ** [comment]
+1 from me also. Does a year count as 'anytime soon'? 😃

**Comment by bobbintb** [comment]
This is two things really. One is changing the download directory depending on the quality and the other is downloading multiple copies of the same movie. As far as downloading multiple copies, you'd need a separate instance.

As for changing the location based on some quality, that can already be accomplished. For one, you can manually set the quality and location when adding the movie. Alternatively, you can accomplish this with a custom post processing script. I have something similar in my setup. Run a script that runs on grab and check the environmental variable for file quality. Then you can send an API request (I use curl) to change the download location. Here is a quick and untested example in bash:

```
if 
[[ $Radarr_MovieFile_Quality== "1080p"]]
  then
  download_location="/1080p/"
  else
  download_location="/other/"
fi
  curl -s http://192.168.1.2:7878/api/movie/$radarr_movie_id?apikey=$apikey | /config/jq --arg dl "$download_location" '.path |= sub("/sort/"; $dl)' | curl -H "Content-Type: application/json" -X PUT -d @- http://192.168.1.2:7878/api/movie/$radarr_movie_id?apikey=$apikey > /dev/null 2>&1

```
I use jq to make the json parsing easier and you'll need to define your radar api key in the script. I download all my movies to a folder named "sort" but none of them actually end up there. They all get immediately relocated on grab.

**Comment by Qstick** [comment]
Closing for #1910, same concept
