### ISSUE TITLE
movie posters not being cached locally

### ISSUE THREAD

**Issue by feld** [Radarr/Radarr#1247]
**Radarr Version:** 0.2.0.535

Movie posters are always being fetched from the internet. Pulling from the page source directly:

`
<img class="series-poster x-series-poster" src="https://image.tmdb.org/t/p/original/aeiVxTSTeGJ2ICf1iSDXkF3ivZp.jpg" onerror="window.NzbDrone.imageError(this);">
`

These should be getting cached and served locally like Sonarr does.

**Comment by galli-leo** [comment]
Where on the page is this?

**Comment by feld** [comment]
I'm seeing it on the main list of movies and when I look at the details of a specific movie. The images appear to be sourced from external sites instead of served locally as Sonarr does. This may also explain why Radarr is significantly slower to load than Sonarr, but I haven't proven that yet

**Comment by weirdcrap** [comment]
I am also seeing this, latest development version of radar. On my main movie list page it loads a TON of images from image.tmdb.org:

![screenshot 2017-03-24 14 28 42](https://cloud.githubusercontent.com/assets/22824785/24310563/6309b9ce-109e-11e7-844d-4c3b5aa13779.png)

**Comment by galli-leo** [comment]
Not quite sure yet why that would be happening.

**Comment by galli-leo** [comment]
Should be fixed now.

**Comment by weirdcrap** [comment]
On latest nightly it appears to be fixed. It did still load a few images from tmdb for me but I'm pretty sure those were movies that I had just added so they hadn't been cached yet.
