### ISSUE TITLE
Can't rename to only {Original Filename}

### ISSUE THREAD

**Issue by DominicMe** [Radarr/Radarr#1248]
I am getting an error "Must contain Movie Title" when trying to use only "{Original Filename}" in Standard movie format field. This works fine in Sonarr so it's clearly a bad conditional check. There is no reason to require movie title at all especially when there is original filename option.
The reason why this is essential to me is that I want to keep original filename but the default movie folder name of "movie (year)" is not what I want.

**Comment by galli-leo** [comment]
You cannot currently use anything other than the movie title and year in the movie folder. We are currently working on finishing up that feature.

**Comment by DominicMe** [comment]
Ah ok, that's a real shame. It seem like near identical what you would have in Sonarr so why would it be changed when code could be reused? At the very least original filename should work with no code changes, I mean it simply skips renaming the file in that case.

**Comment by galli-leo** [comment]
You also cannot change the show folder name in Sonarr? If you want to rename the file, use {Original Title}

**Comment by DominicMe** [comment]
Well, folder name is not an issue here since I get the error for filename, meaning I cannot use renaming at all. In sonarr I just have "{Original Filename}" for filenames.
I do NOT want to rename the file, I want to keep original filename. I only want to rename folder but cannot do that because of the error and there is no way to rename only folder.

**Comment by DominicMe** [comment]
This was fixed for a while but the most recent update seems to have re-introduced this bug, why was this done? I had no issues at all prior to this bug being re-introduced. I have "{Movie Title} {Release Year}" in Movie Folder Format setting. The problem is that new movies added default to "{Movie Title} ({Release Year})" (notice brackets). This means the movies will show up missing even after downloaded.

**Comment by galli-leo** [comment]
@DominicMe We default to {Movie Title} {Release Year} when there is no movie file, since we have to have something and Original Title would just be an empty string. Can you try scanning disk for those movies? If it still shows up missing, I think that's an entirely unrelated bug (#657)

**Comment by DominicMe** [comment]
@galli-leo I am not talking about the movie filename but rather the path/folder name that appears in the  "Edit Movie" page -> Path option. The last part of the path defaults to movie name followed by year encased in brackets. Before the last update this path was based on the entry in the file rename options but now it defaults to {Movie Title} {Release Year} ignoring the renaming options. This means when the movie is downloaded it gets renamed as per the rename settings but this path does not change automatically.

**Comment by galli-leo** [comment]
@DominicMe Is the movie path set to static?

**Comment by DominicMe** [comment]
"Movie Paths Default to Static" is set to yes.

**Comment by ltjdym** [comment]
should it be set to static?

**Comment by DominicMe** [comment]
I should also add that It does appear to work partially. I believe movies added automatically by radarr OR movies added manually by the user default to { title (year) } path. I see both some movies have correct path some don't so it looks like it's been implemented in one section and forgotten in another, should be an easy fix if that's all it is as the code only need to be same in both sections.

**Comment by DominicMe** [comment]
I almost opened a new issue but I remembered I already have! Any progress on this issue? I looked at the code but could not find the parts that would need to be changed for this. It works in Sonarr, I don't get why this feature was removed.

I should add that  {Original Title} uses the filename of the NZB when snatched. The issue with this is that any renaming done in NZBGet gets ignored, that is why  {Original Filename} is important.

**Comment by galli-leo** [comment]
@DominicMe Just use {Original Title}. {Original Filename} will not be supported since most of the time, it wouldn't get recognized by Radarr again, because it doesn't have a nice naming scheme. It may get support when we truly add dynamic paths, but that's gonna take a long time.

**Comment by DominicMe** [comment]
@galli-leo  {Original Title} doesn't work, it ignores any changes made by nzbget. Why wouldn't Raddarr recognize this {Original Filename}? It is the same as {Original Title} unless renamed in nzbget. Also Sonarr works perfectly with {Original Filename}, why was this feature removed?  {Original Filename} is even listed in the documentation as supported. All I want is for Radarr to use the name NZBGet gives it like I do in Sonarr.

**Comment by galli-leo** [comment]
@DominicMe Ah sorry I though you were talking about the folder name. Not sure why {Original Filename} doesn't work, though for the time being you can just turn of renaming.

**Comment by DominicMe** [comment]
@galli-leo I can't turn off renaming because then it uses original nzb names (when snatched) so we are back at the same point. This is the only reason I have renaming turned on in Sonaar and Radarr, but in Radarr {Original Filename} doesn't work properly so either way it will use original snatched nzb name.

One thing to not when I try to use {Original Filename} I get this error: "Must contain movie title". Maybe a fix is as simple as removing an if statement that requires movie title? I couldn't find the core where this logic happens.

**Comment by galli-leo** [comment]
Yeah just had to tweak a regex a bit, fixed now (well on nightly at least)

**Comment by DominicMe** [comment]
@galli-leo Will try and do a new install to test, will report back then!

**Comment by DominicMe** [comment]
For a moment I though I could just edit the file in place but I guess it need to be compiled, is there a guide?   I assume nightly is the main release you get via download as zip or clone right? Any idea when this might be in develop branch? If it's not too long I can wait.

**Comment by galli-leo** [comment]
@DominicMe No idea. For nightly you can just set the branch in settings to nightly and it will update automatically when you go to the Update page. You can also manually download the nightly under the continuous releases page on the main github page.

**Comment by DominicMe** [comment]
@galli-leo Ah, forgot you could do that! Will risk using nightly for now. Seems to be working as expected, movie was renamed by nzbget and Radarr imported it. Looks like no more manual renaming, Thank you!
