### ISSUE TITLE
Upgrading not removing old movie from Plex

### ISSUE THREAD

**Issue by kmickeletto** [Radarr/Radarr#1249]
When upgrading a movie that has a different extension, the Plex notification doesn't remove the old record for the movie.  Requires user to manually clean up duplicated records.  Plex UI shows unavailable for movie which is confusing for users.

**Comment by counterfit** [comment]
You'd have to turn on "Empty trash automatically after every scan" option under Library, or ensure that the upgraded file has the same name as the file it replaced.
