### ISSUE TITLE
Renaming files does not use extended naming tags such as video codec, and audio codec.

### ISSUE THREAD

**Issue by chrisallen** [Radarr/Radarr#125]
I currently have the following Movie Naming Format

`{Movie Title} ({Release Year}) [{Quality Title}{ MediaInfo VideoCodec}{ MediaInfo AudioCodec}{ MediaInfo AudioChannels}]`

But movies only get renamed to `Movie Title (2010) [Bluray 1080p]`

I think this is a regression as it was previously working.

**Comment by chrisallen** [comment]
It appears this works correctly when importing a movie from SABNZBD but not when using the organize option from the Movie Editor.

**Comment by fedoranimus** [comment]
Interesting; I'll take a look!

**Comment by kylerw** [comment]
Can we add IMDB ID as an option as well? Maybe that's a new request?

**Comment by galli-leo** [comment]
@chrisallen Can you try this again in the latest release? You will probably first have to scan the disk again for this movie. Also look if the media info is empty in the file info tab.
