### ISSUE TITLE
Unable to change information about files

### ISSUE THREAD

**Issue by smidley** [Radarr/Radarr#1250]
I have some files that are detected as 1080p-HDTV and I click on the wrench that says "change information about this file".  Then I select 1080p-Bluray and click save.  Nothing happens.  The loading circle just keeps spinning and the file is not updated.

**Radarr Version:**
0.2.0.535

**Comment by galli-leo** [comment]
There's already an issue open for this (on mobile, so can't link). Will try to fix in a few hours.
