### ISSUE TITLE
Indexers Keep Breaking

### ISSUE THREAD

**Issue by zero77** [Radarr/Radarr#1251]
The RARBG indexer stop working some times and manually refreshing the capture token fixes it.
Therefore, could you please add the ability to auto refresh the capture token.

**Comment by galli-leo** [comment]
Do you mean manually refreshing the captcha?

**Comment by zero77** [comment]
There is a button to refresh capture token, I click that and it fixes the problem but no actual capture pops up for me to complete.

**Comment by onedr0p** [comment]
I would suggest using Jackett for public trackers, they are more responsive in fixing them.

**Comment by zero77** [comment]
Sorry, I don’t think I explained this very well. When I manually search for results after a while all RARBG search results stop when theres definitely results available. If I manually refresh the capture and the search again it works.
