### ISSUE TITLE
RSS Sync not adhering to schedule?

### ISSUE THREAD

**Issue by a92nj2efnfsa** [Radarr/Radarr#1258]
I have my RSS sync set to every 30 minutes. Looking at the logs, I see a lot of:

Indexer <redacted> sync didn't cover the period between 3/24/2017 9:43:39 AM and 3/24/2017 11:11:22 AM UTC. Search may be required.

Why is it waiting two hours to sync the RSS feed?

**Radarr Version:**
Radarr Ver. 0.2.0.535

**Comment by galli-leo** [comment]
Did you restart Radarr after changing the RSS Sync Interval?

**Comment by a92nj2efnfsa** [comment]
Of course. In fact, that box has been bounced several times since. Error still happening as we speak.

Indexer <redacted> sync didn't cover the period between 3/25/2017 9:48:29 AM and 3/25/2017 11:24:28 AM UTC. Search may be required.

**Comment by galli-leo** [comment]
@a92nj2efnfsa Could it be that your machine looses it's network or something during these times? If the schedule is not adhered to, It should display those errors for all times during the day.

**Comment by a92nj2efnfsa** [comment]
No, the machine is not losing any network connectivity. Verified via firewall logs and also Sonarr is on this box too and does not have any of these errors. Only radarr.

Just checked and it's still doing it. Every hour on the hour.

Indexer [snip] rss sync didn't cover the period between 3/26/2017 7:56:46 PM and 3/26/2017 8:41:34 PM UTC. Search may be required.

**Comment by a92nj2efnfsa** [comment]
I've enabled debug logging to see if I can get anymore information. Will post once it happens again.

**Comment by a92nj2efnfsa** [comment]
Debug logging did not provide any additional details.

**Comment by galli-leo** [comment]
Do you see "Starting RSS Sync" every 30 minutes in the log?

**Comment by a92nj2efnfsa** [comment]
Yes. Give or take a couple of minutes. Interestingly enough the time doesn't match the error I'm getting. For example:

starting rss sync at 4:18 pm (EST)
the right after that it says
Indexer (snip) rss sync didn't cover the period between 3/28/2017 6:05:49 PM and 3/28/2017 7:19:55 PM UTC. Search may be required.
but that error is also logged at 4:18pm too. Yet the window in the error doesn't match the time it logged...

**Comment by galli-leo** [comment]
@a92nj2efnfsa Interesting. In that case the RSS Sync runs fine. Might be that your indexer is using a different Timezone or something?

**Comment by a92nj2efnfsa** [comment]
@galli-leo This same exact indexer is in sonarr and does not give this warning :/
