### ISSUE TITLE
Minimum Seeders

### ISSUE THREAD

**Issue by theCheek** [Radarr/Radarr#1262]
I know this subject is a bit of a controversial one, and discussed often in Sonarr threads, but the fact that there is no way to configure the minimum acceptable seeders for trackers/jackett is in my view much more noticeable for large movie files.

The switch from Couchpotato to Radarr has been insanely helpful apart from this one missing feature. It is resulting in movies downloading at crazy slow speeds when there is a similar (albeit slight lower quality) torrent available with higher seeders and thus higher speeds.

Do you think it at all possible to adjust the current 1 minimum seed requirements to a user specified one?

Please keep up the good work nonetheless. Epic fork.

**Comment by r1nzl3r9991** [comment]
I agree, I hope this can be added as a feature somehow.

**Comment by galli-leo** [comment]
Just created a pr for this, should be merged in a few hours and live on nightly :).

**Comment by theCheek** [comment]
This is so awesome. Thank you. You said thanks to Markus over on the other thread is this because the fix is now integrated in Sonarr also? If so double awesome!

**Comment by galli-leo** [comment]
@theCheek Yup :) (But I don't know if it's made it into the latest release of Sonarr yet)

**Comment by theCheek** [comment]
@galli-leo It looks like theres an issue with saving the minimum seeders for torrentpotato feeds. It just doesn't seem to remember the entry. Can you reproduce these steps to double check?
1) Edit a torrentpotato feed, and enter a value under the minimum seeders option
2) Save
3) Re-open the same feed, and see the value has not been remembered.

I also tried creating a new torrentpotato feed from scratch and getting same issue.

**Comment by galli-leo** [comment]
Let's use #1736 for the issues on the develop version.
