### ISSUE TITLE
Multiple Downloads Sent to SABNZBD

### ISSUE THREAD

**Issue by ratoka** [Radarr/Radarr#1263]
I am seeing issues where a searched movie will add 2 downloads of the same item to SAB.
[radarr.0.txt](https://github.com/Radarr/Radarr/files/869402/radarr.0.txt)

**Comment by galli-leo** [comment]
Can you give an example of such a movie (So my life is easier when crawling through the logs :))?

**Comment by Stealthii** [comment]
This is happening to me as well.

I've an list pulled from my Imdb watchlist. I've one download client configured (Sabnzbd) and one indexer configured. For each item in the list, Radarr is sending downloads to the list twice.

About 90% of them are the exact same download, but sometimes it's an alternative download to the first one (different release, same quality).

**Comment by galli-leo** [comment]
@Stealthii On which Radarr version are you?

**Comment by ratoka** [comment]
I apologize for not getting back sooner, I was redoing my media center server when I migrated to Radarr from CP.  I had already run through my movie list and removed the duplicates, so any narrowing would only be a guess at this point.  If you would like, I will add a few more movies and see if duplication happens again, and grab new logs with info.  To answer the version question, I am on 0.2.0.535.

**Comment by ratoka** [comment]
I am also using a single indexer, and single download client.  I do have a few lists that are being watched if that makes a difference.

**Comment by galli-leo** [comment]
@ratoka Are all the lists of the same type?

**Comment by ratoka** [comment]
I have 3 TMDb lists.  Not all the same list, but there is the possibility of duplicates between lists.

**Comment by Stealthii** [comment]
@galli-leo 0.2.0.535 - Mar 12 2017. Using tag 30 (current latest) from the docker images provided by [linuxserver](https://hub.docker.com/r/linuxserver/radarr/tags/).

**Comment by galli-leo** [comment]
This is fixed in the latest nightly version. Expect a release in the coming days.
