### ISSUE TITLE
Feature Request: RSS Authentication

### ISSUE THREAD

**Issue by CooperBarrett** [Radarr/Radarr#1268]
*Sorry for my english, i use google trad*

----------

Hello, will it be possible to add RSS feeds authentication for lists ?

By testing with http://username:password@urlsite this does not work.

Thank you for your work

**Radarr Version:**
Radarr Ver. 0.2.0.535

**Comment by onedr0p** [comment]
We need to support lists by coding in a way to parse it, what is the feed you are trying to add? RSS lists is generic but won't work 99% of the time on anything but IMDB

**Comment by CooperBarrett** [comment]
Sorry for my english, i use google trad

-------
OK, thanks.
It was for a personal RSS feed.

I have two radarr installation: one on NAS and one on a dedicated server.
- On dedicated server: download in 1080p x264
- On the NAS: download in 1080p x265 to retain

The feed allows me to notify you of the download of the dedicated server.
I would have liked that it used me to index the films on the Radar of the NAS to avoid to manually search the films a second time.

It is not very serious, thank you for your work!

**Comment by galli-leo** [comment]
@CooperBarrett Can you post the error found in the logs when trying to add the list? Maybe the rss feed is just missing something, which you should be able to easily add.
