### ISSUE TITLE
Ignore Deleted Movies option not working as expected

### ISSUE THREAD

**Issue by idolos** [Radarr/Radarr#1269]
Hi,

I may be misunderstanding how this feature is supposed to work, but it doesn't seem to do anything for me. My use case is that I have Radarr up on a seedbox, and I have to periodically clear out movies there to manage my disk space. I would expect that with this setting checked that deleting a movie from the disk would cause it to be removed from Radarr altogether, but this doesn't seem to be the case. If this setting is does something else, then is there a way to accomplish what I want? Thank you.

**Comment by galli-leo** [comment]
Ignore deleted movies means that the movies are unmonitored in Radarr when you delete them. However, there is a pr for integrating what you asked for.
