### ISSUE TITLE
Delete files not working

### ISSUE THREAD

**Issue by donldmn** [Radarr/Radarr#127]
When I go to "Edit Movie" > "Delete" > "Delete all files" it says "0 episode files will be deleted" and does not delete the movie from the disk.

**Comment by guyspronck** [comment]
Just wondering, is included in the latest release? If so, it is not working yet.

**Comment by julestop** [comment]
IS this working for others? It is not working for me, it shows the same behaviour as described '0 files to delete' and when you press delete, nothing gets deleted.

![image](https://cloud.githubusercontent.com/assets/1585230/22249257/362dabac-e210-11e6-84a1-bb8f35fab5be.png)


Would be nice if it deletes the movie folder and everything in it... 

This is on Windows BTW.
