### ISSUE TITLE
Radarr no longer searching by imdbid?

### ISSUE THREAD

**Issue by c2af5c5f28e38384295f2fc2af** [Radarr/Radarr#1270]
**Description:**

I am using:
- Jackett 0.7.1197.0
- Radarr 0.2.0.564

I noticed in my logs that Radarr is using the movie title and year as the search query and not the imdbid. This is causing some movies to return 0 results. If I do a manual search via Jackett using the movie's imdbid, it lists several torrents. If I do another search using the movie title and year, I get 0 results.

Is searching by imdbid no longer the default behavior?

**Logs:**

```text
17-3-26 23:17:04.7|Info|NzbSearchService|Searching 1 indexers for [Rogue One: A Star Wars Story]
17-3-26 23:17:04.7|Debug|Torznab|Downloading Feed http://192.168.1.192:9117/torznab/beyondhd/api?t=search&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060&extended=1&apikey=(removed)&offset=0&limit=100&q=rogue%20one%20star%20wars%20story%202016
17-3-26 23:17:05.9|Debug|NzbSearchService|Total of 0 reports were found for [Rogue One: A Star Wars Story] from 1 indexers
17-3-26 23:17:05.9|Info|DownloadDecisionMaker|No results found
```

**Comment by galli-leo** [comment]
I think only certain Jackett indexers support searching by imdbid.

**Comment by c2af5c5f28e38384295f2fc2af** [comment]
@galli-leo Ah, that makes sense. I just checked Jackett's source and didn't see anything regarding imdb for that indexer so I think you're right. Thanks!
