### ISSUE TITLE
Error DownloadDecisionMaker

### ISSUE THREAD

**Issue by evilvibes** [Radarr/Radarr#1271]
Couldn't process release.: Object reference not set to an instance of an object.
This is happening when the task Rss Sync happens

![sse](https://cloud.githubusercontent.com/assets/17504733/24347183/ad9d4b2a-1294-11e7-8005-0ac35124e6c5.png)
![sse1](https://cloud.githubusercontent.com/assets/17504733/24347187/afb6b73e-1294-11e7-893f-8d41172c9405.png)
![sse2](https://cloud.githubusercontent.com/assets/17504733/24352806/34ba67f6-12a8-11e7-94aa-acdf36f42aef.png)

**Comment by PeteOdeath** [comment]
Ubuntu 16.04
Version: 0.2.0.564
Mono: Version 4.2.2
Exact same problem since latest nightly.

**Comment by galli-leo** [comment]
Fixed in latest nightly (should be up in a few minutes).
