### ISSUE TITLE
systemd script not working

### ISSUE THREAD

**Issue by bebetech** [Radarr/Radarr#1272]
Installed the latest version but when trying to run sudo systemctl enable radarr.service, I get the following error:

> Failed to execute operation: Invalid argument

If I run /usr/bin/mono --debug /opt/Radarr/Radarr.exe --nobrowser on it's own it runs fine

**Comment by onedr0p** [comment]
Take a look at the AUR package and the systemd file there.

https://aur.archlinux.org/cgit/aur.git/tree/radarr.service?h=radarr
