### ISSUE TITLE
HDTV-720p & WEBDL-720p imports not removed from Cutoff Unmet list

### ISSUE THREAD

**Issue by Jleagle** [Radarr/Radarr#1273]
**Description:**

I have some movies in "wanted / cutoff unmet", I have set them to HD720p. When i search for them it downloads HDTV-720p & WEBDL-720p versions of the movies but they stay in cutoff unmet. When they get downloaded as Bluray-720p they work fine and are taken out the cutoff unmet list.

**Radarr Version:**

0.2.0.535

**Comment by majora2007** [comment]
Isn't BluRay 720p the cutoff for HD720p? At least it is for me and Radarr is functioning correctly.

**Comment by fryfrog** [comment]
I don't have my profiles from the install anymore, but I agree with @majora2007. I think Bluray 720p is the cutoff for the HD720p profile, so the behavior you're describing sounds correct.

Can you screenshot your HD720p profile and add it here?

**Comment by Jleagle** [comment]
My cutoff is indeed Bluray-720 - Does that mean it will stay in ‘cutoff unmet’ until it reach this quality.

I was thinking any of the qualities ticked in the profile would be acceptable.

**Comment by fryfrog** [comment]
Yup, that is how cutoff works. You set it to the quality you want to stop looking at. If you have ones defined above it, they'll be fetched in a search or if they show up in rss.

https://cdn.discordapp.com/attachments/264388019585286144/296687510786932739/unknown.png

**Comment by fryfrog** [comment]
The qualities ticked in the profile are *all* acceptable, but the one defined in the cutoff drop down is what is considered good enough to stop upgrading. So if you're okay w/ HDTV and/or WEBDL, just set your cutoff to the lowest one and leave the other ticked. If needed, you'll grab any of them, but once it has one, it'll stop.
