### ISSUE TITLE
Feature: Minimum votes field for trakt RSS feed

### ISSUE THREAD

**Issue by rmangahas-coupa** [Radarr/Radarr#1275]
**Description:**

Add a field to the RSS feeds for Trakt.tv for minimum number of votes. I checked documentation and tested via Postman. Adding &votes=250 ensures only items with at least 250 votes shows up on the RSS.

As a sorta workaround, I've been able to append "&votes=250" to the existing Genre field to get the effect.

**Radarr Version:** N/A

**Logs:** N/A

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by galli-leo** [comment]
@onedr0p Maybe we should just put an additional query params field to the lists, just like the indexers do.

**Comment by onedr0p** [comment]
Good idea!
