### ISSUE TITLE
[BUG] |Error|NzbSearchService|Error while searching for

### ISSUE THREAD

**Issue by ajkis** [Radarr/Radarr#1277]
Latest nightly 

> 17-3-28 06:34:36.1|Error|NzbSearchService|Error while searching for [Before the Gates]
> 
> [v0.2.0.567] System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string.
> Parameter name: startIndex
>   at System.String.Substring (Int32 startIndex, Int32 length) <0x7f156785b950 + 0x000f4> in <filename unknown>:0 
>   at System.String.Substring (Int32 startIndex) <0x7f156785b920 + 0x0001e> in <filename unknown>:0 
>   at NzbDrone.Core.Indexers.Newznab.NewznabRequestGenerator.GetSearchRequests (NzbDrone.Core.IndexerSearch.Definitions.MovieSearchCriteria searchCriteria) <0x4207b910 + 0x000a1> in <filename unknown>:0 
>   at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].Fetch (NzbDrone.Core.IndexerSearch.Definitions.MovieSearchCriteria searchCriteria) <0x4207b830 + 0x000b4> in <filename unknown>:0 
>   at NzbDrone.Core.IndexerSearch.NzbSearchService+<>cDisplayClass10_0.<MovieSearch>b0 (IIndexer indexer) <0x4207b800 + 0x00025> in <filename unknown>:0 
>   at NzbDrone.Core.IndexerSearch.NzbSearchService+<>cDisplayClass20_1.<Dispatch>b0 () <0x4207b6b0 + 0x0003d> in <filename unknown>:0

> 17-3-28 06:39:24.5|Error|NzbSearchService|Error while searching for [The Dressmaker]
> 
> [v0.2.0.567] System.NullReferenceException: Object reference not set to an instance of an object
>   at NzbDrone.Core.Indexers.Newznab.NewznabRequestGenerator.GetSearchRequests (NzbDrone.Core.IndexerSearch.Definitions.MovieSearchCriteria searchCriteria) <0x4207b910 + 0x00092> in <filename unknown>:0 
>   at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].Fetch (NzbDrone.Core.IndexerSearch.Definitions.MovieSearchCriteria searchCriteria) <0x4207b830 + 0x000b4> in <filename unknown>:0 
>   at NzbDrone.Core.IndexerSearch.NzbSearchService+<>c__DisplayClass10_0.<MovieSearch>b__0 (IIndexer indexer) <0x4207b800 + 0x00025> in <filename unknown>:0 
>   at NzbDrone.Core.IndexerSearch.NzbSearchService+<>c__DisplayClass20_1.<Dispatch>b__0 () <0x4207b6b0 + 0x0003d> in <filename unknown>:0

**Comment by galli-leo** [comment]
Try updating that movie which you are trying to search for. Seems like it does not have an imdbid associated with it. You can also try adding the imdbid to The Movie Database for that movie, wait a few hours and then update your movie. Will try to push a fix over the Github web (Not sure if that will work :/)
