### ISSUE TITLE
[Feature Request] Custom script on Radarr Update

### ISSUE THREAD

**Issue by ajkis** [Radarr/Radarr#1278]
Any chance to add a hook for at Radarr update so we can make custom script that would radarr (not just database) so we could revert when nightly versions are "broken".

**Comment by galli-leo** [comment]
Not quite sure what you mean? Radarr auto backs up after every update on it's own.

**Comment by ajkis** [comment]
Radarr backups database but not the installation. 
Atm I manually rar installation folder before every update so if I need to revert I unrar latest DB backup and installation folder.

**Comment by onedr0p** [comment]
This is best handled by external tools, the media covers are a necessity to keep backed up.
