### ISSUE TITLE
Feature Request: Missing Transmission Priority Options

### ISSUE THREAD

**Issue by SleepingPanda** [Radarr/Radarr#1279]
The options from [Sonarr](http://i.imgur.com/S5x8eV0.png) to prioritize downloads in Transmission are missing in [Radarr](http://i.imgur.com/WoXSPQH.png). 

Are there any plans to add them back? Were they specifically removed for a reason? I found them quite useful as I don't just use Transmission for Sonarr/Radarr. Please consider reviewing these options for inclusion in the project!

Radarr Version: 0.2.0.535

**Comment by galli-leo** [comment]
There's already an issue open for the priority options. They will definitely be in the first release version.

**Comment by SleepingPanda** [comment]
Oh I'm sorry. I did a search for "Transmission" and didn't find anything related to this.

**Comment by galli-leo** [comment]
@SleepingPanda It's an issue for all clients.

**Comment by SleepingPanda** [comment]
It's present for [uTorrent](http://i.imgur.com/yyHr9UC.png). (That's why I did a specific search for "Transmission".)
Can't say if it actually works though!

Thank you very much for working on this!

**Comment by galli-leo** [comment]
Doesn't actually do anything 😬

**Comment by galli-leo** [comment]
Also was this a recent addition to Sonarr?

**Comment by SleepingPanda** [comment]
I thought so! It's been there since at least October 2016 when I started using it.
