### ISSUE TITLE
Unable to sort columns in table view when clicking on the header.

### ISSUE THREAD

**Issue by chrisallen** [Radarr/Radarr#128]
This appears to be a recent regression. If I click on any of the header titles such as "Links" or "Status" nothing happens.

![image](https://cloud.githubusercontent.com/assets/203867/21829616/14a1b262-d7fc-11e6-9d98-e0f1ef2d4dd0.png)

**Comment by onedr0p** [comment]
Sorting links makes no sense, but sorting status should work.

**Comment by fedoranimus** [comment]
Do other columns sort? Does this column sort in Sonarr? I agree with @onedr0p.

**Comment by chrisallen** [comment]
Sonarr does not have the `Links` or `Status` column on the list view. It has `Episodes` and I just checked, all columns sort ascending/descending as you click them.

**Comment by fedoranimus** [comment]
Do the other columns sort in this view in Radarr? Which view is this?

**Comment by ShanDestromp** [comment]
For me sorting by status does not work properly in table view, furthermore sorting by "in cinemas" does not properly as well.  They both seem to sort either by some unknown value or "randomly."

**Comment by ShanDestromp** [comment]
To further clarify for the above I was referencing the "movies I have / want" page, table view; however I just noticed that if I do a manual search on a movies page, and attempt to sort by (for ex) quality, it's.....not.  I can't see any pattern to HOW it sorts but it's definitely not by quality.
