### ISSUE TITLE
Downloaded successfully status in DB

### ISSUE THREAD

**Issue by 4getit** [Radarr/Radarr#1280]
In the DB, I cannot figure out what indicates that a file has downloaded successfullly.
In the History table, I see EventTypes for when the nzb was downloaded, if the actual download failed and if it's missing from disk. I assumed it was EventType 2 but that doesn't seem the case. 

What triggers the "Movie downloaded successfully and picked up from download client" -flag?

I'm asking because I'm trying to force Movie.Monitored to 0 as soon as a file is downloaded.

**Comment by onedr0p** [comment]
Can you use a script on download send a API request to make the movie un-monitored?

**Comment by 4getit** [comment]
Yes, good one. But that's for future downloads only.
I currently have many thousands that weren't set correctly to unmonitored by the disk scan.

Can you tell me where it get's the "Movie downloaded successfully and picked up from download client" -status in the UI (on the History tab)?

**Comment by 4getit** [comment]
Duh, found it to be status 3.
I was confused because I used the .db from the backup and somehow that doesn't get written when hitting the backup button. After a restart, it's updated properly.
