### ISSUE TITLE
Send indexer flags along to custom scripts.

### ISSUE THREAD

**Issue by bobbintb** [Radarr/Radarr#1282]
Version
0.2.0.535

I didn't see an open issue for this yet. I have a custom script on-grab that uses the radarr_release_title variable. According to the documentation, that variable is "NZB/Torrent title". In my debugging I found that it seems to be formatted improperly. What it ends up showing is the same title that shows up under "Source Title" in the individual movie page that includes the checkmark and golden popcorn indicator, if available.

So instead of `Movie.2017.1080p.BluRay.x264-Group` it shows `Movie.2017.1080p.BluRay.x264-Group 🍿 ✔`. I'm pretty sure this is not intended behavior as my torrent program and the indexer refer to it as the former. I'll likely have to use sed to reformat it to match, but I'm not even sure if I can with those characters.

**Comment by bobbintb** [comment]
As a side note, this bug actually improved my script. Previously, I was connecting to the PTP API and parsing the JSON to see if the grab was golden popcorn, since that information is not retained in Radarr and passed to the custom post processing script. However, once I noticed this bug, I simply just had to see if that character was in the variable to determine if it was golden popcorn or not. So if this bug does get fixed, hopefully the dev will retain the ability for custom scripts to determine golden popcorn status without having to query the site again.

**Comment by bobbintb** [comment]
This seems to be fixed in my docker, which is v0.2.0.696.

Unfortunately, my script is now broken and I have to figure how to query PTP to see if the torrent is GP. Any chance of adding a GP variable to the custom processing variables? I realize it is a special case for one tracker but it's pretty much THE movie tracker and there are already similar variables for other aspects of quality.

**Comment by galli-leo** [comment]
@bobbintb Yeah sure. We definitely should pass those flags which we capture along to the script (There are now even some for other trackers or just general freeleech, etc.)

**Comment by bobbintb** [comment]
Sweet, looking forward to it. Thanks.
:)

**Comment by bobbintb** [comment]
I might take a stab at this. I looked at it and it seemed pretty straight forward.

**Comment by galli-leo** [comment]
Thanks!

**Comment by bobbintb** [comment]
This was a pretty easy one-liner. I'm not too experienced with git so hopefully I didn't mess up the pull request or anything.
