### ISSUE TITLE
[Feature Request] Fix incorrect matches on existing collection

### ISSUE THREAD

**Issue by kappaknight** [Radarr/Radarr#1287]
**Description:**

I'm having Radarr scan my current selection so it can figure out which ones are okay to leave, vs. ones it should find better versions of. However, when a film is incorrectly matched, there's no way to "fix" it in the system. 

It'd be nice to be able to fix an incorrect match; something like what Plex offers.

**Radarr Version:**

**Logs:**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by fryfrog** [comment]
Make your feature request at http://feathub.com/Radarr/Radarr so it can be voted on.

**Comment by Qstick** [comment]
Dupe #355
