### ISSUE TITLE
[Request] Indexers https://zooqle.com and https://torrentz2.eu 

### ISSUE THREAD

**Issue by zero77** [Radarr/Radarr#1288]
Can you please add support for these two sites as indexes https://zooqle.com and https://torrentz2.eu I have been unable to add them with RSS or the other provided methods.
Thanks

**Comment by fryfrog** [comment]
Install and use Jackett instead. If they don't support these already, make this request to them. Jackett does a great job of interfacing with torrent indexers and providing a torznab interface to them for Sonarr/Radarr (or anything else) to use.

**Comment by bobbintb** [comment]
Cardigann is another option.

**Comment by fryfrog** [comment]
Did Radarr start supporting Cardigann? I think there was an issue w/ supporting it that they needed to resolve and I haven't seen anything since.

**Comment by bobbintb** [comment]
I'm not aware. I use Cardigann with Sonarr but have not used it with Radarr. Just giving you more options.

Also, why did @onedr0p thumbs down that comment? Unnecessarily rude.

**Comment by onedr0p** [comment]
> Unnecessarily rude.

Cardigann isn't being actively developed anymore, it doesn't support Radarr.

**Comment by bobbintb** [comment]
Oh ok. Thanks for the clarification. Sorry if I offended. Intent is hard to convey.

Somehow I was under the impression the opposite was true. I thought Jackett was no linger being developed and someone forked it to Cardigann. I'll have to look at that. I don't need either for Radarr but as I mentioned I use Cardigann for Sonarr for one particular tracker. I had issues with the Jackett docker, which is why I switched.

**Comment by onedr0p** [comment]
Cardigann is only getting definition updates, the core app isn't getting much love.

**Comment by zero77** [comment]
So to clarify, the only way to use other torrent Search engines other than with RSS is to install another third party app.

Also, is there any plans to change this, maybe by using the torrent Search engines URL as this should work for most if not all for example, https://torrentz2.eu/search?f=[Search input] and https://zooqle.com/search?q=[Search input]

**Comment by onedr0p** [comment]
@zero77 you may think it's that simple, but we will need to continue support for those indexers and it's not something I am thrilled about upkeeping since Jackett does all that for us.

**Comment by zero77** [comment]
Well if you think that jacket is a good option then, Is there any way that you could look at integrating Jackett.

**Comment by galli-leo** [comment]
@zero77 Not sure what you mean exactly? Just add those indexers in Jackett and then add a Torznab indexer pointing to Jackett within Radarr.

**Comment by Baconnaise** [comment]
FWIW Sonarr and Radarr work fine with Zooqle OOTB. The caveat is you need to create an account to setup RSS feeds atm.
