### ISSUE TITLE
Cannot parse "2in1" titles

### ISSUE THREAD

**Issue by tsubus** [Radarr/Radarr#1289]
"2in1" movies (movies with alternative endings that include both) cannot be parsed, for example a movie title could be: Gladiator 2000 2in1 1080p BluRay DD5.1 x264-RlsGrp

The issue is that the parser does not like anything that starts with a number after the year. I have resolved by changing the line below, but I am not sure this is not going to break something else, so I won't push it as a pull request. I'd rather someone with more experience takes a look.

Line 25 of src/NzbDrone.Core/Parser
`//Special, Despecialized, etc. Edition Movies, e.g: Mission.Impossible.3.2011.Special.Edition //TODO: Seems to slow down parsing heavily!
            new Regex(@"^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(19|20)\d{2}(?!p|i|\d+|\])))+(\W+|_|$)(?!\\)(?<edition>((Extended.|Ultimate.)?(Director.?s|Collector.?s|Theatrical|Ultimate|Final|Extended|Rogue|Special|Despecialized).(Cut|Edition|Version)|Extended|Uncensored|Remastered|Unrated|Uncut|IMAX|2in1))",
                          RegexOptions.IgnoreCase | RegexOptions.Compiled),`

**Comment by galli-leo** [comment]
Sadly just adding 2in1 won't really help. I will have to rework the regex once I have more time to do so.
