### ISSUE TITLE
Consider displaying a preview of all renaming on the Movie Editor

### ISSUE THREAD

**Issue by chrisallen** [Radarr/Radarr#129]
In Sonarr It made sense to not show this as each show might have 10-150 episodes. In Radarr there is a 1:1 relation ship between Movie and Movie File.

It would be awesome to quickly see multiple movies being renamed on this screen. In the same way Sonarr shows all episodes for a show on the same Preview screen at the show details page.

![image](https://cloud.githubusercontent.com/assets/203867/21829693/8db0dca0-d7fc-11e6-833e-a85c009ecc48.png)

**Comment by onedr0p** [comment]
This is fine, unless you want to update 100+ movies, we can sit on this and think about it.
