### ISSUE TITLE
Radarr don't detect movie files

### ISSUE THREAD

**Issue by aswieton** [Radarr/Radarr#1290]
**Description:**
Radarr don't detect movie files without year in (). For example: 'Movie Title.mkv' it's doesn't detected but when I change filename to: 'Movie Title (2016).mkv radarr detects this file.

 
Check first that your problem is not listed in our wiki section:
* https://github.com/Radarr/Radarr/wiki/Common-Problems
* https://github.com/Radarr/Radarr/wiki/FAQ

Provide a description of the feature request or bug here, the more details the better. 
Please also try to include the following if you are reporting a bug

**Radarr Version:**

**Logs:**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by galli-leo** [comment]
This is intentional. There are a number of issues already open on this discussing why, but the gist of it is, that without a year, we cannot certainly decide which movie it is. Beauty and the Beast for example has multiple versions, in 2014, 2017 and one in 1980 something.

**Comment by aswieton** [comment]
Ok but when I add existing movie to the library I can manualy decide witch version of the movie it is. So from my point of view (maybay I'm wrong) it is better detect file and manualy assign good movie version from few propositions then not detect file at all.

**Comment by galli-leo** [comment]
I agree, though Radarr should recognize the movie file if you have the year in the folder name. Also it's a good idea to add the year to all your movie files, since it will be easier for other applications or yourself to identify the movie.

**Comment by 1liminal1** [comment]
Ok, so that's fine. But does it give you a way to bulk update the files to make it easy? I'm not going to go and rename them manually.
