### ISSUE TITLE
[Feature Request] Replace normal versions of movies with Unrated or Extended versions when released.

### ISSUE THREAD

**Issue by akizzle** [Radarr/Radarr#1292]

**Comment by weirdcrap** [comment]
This would have to be a toggle-able option. Not everyone wants the release they have replaced with a different edition.

**Comment by akizzle** [comment]
I agree or it could be implemented in a profile.

**Comment by sickboy2137** [comment]
I'd like the option to keep multiple versions of some movies, if possible.

**Comment by bobbintb** [comment]
One problem I see with this is movie databases don't yet support this. TMDB is supposed to be adding support later this year but it might be difficult until then. Just my 2 cents.

**Comment by galli-leo** [comment]
@bobbintb Oh they are adding support for Director's cut etc.? Do you have a link to that?

**Comment by jOOc** [comment]
I have not seen any updates for TMDB adding this, the ticket is very old and looks like very low prioritized.

https://tmdb.lighthouseapp.com/projects/83076/tickets/470-Support-multiple-versions-of-a-movie-cuts-anniversary-editions-3D

**Comment by bobbintb** [comment]
Yes, it's been talked about for years. Here is the thread where it is mentioned they will (should) get to it this year:

https://www.themoviedb.org/talk/56aa8fd09251417e1100036e

**Comment by JamzTheMan** [comment]
Would it be possible instead to allow us to add a movie more than once? And then supply "tags" like "Extended" or "Director's Cut".

I was told there is a naming tag for these already {Edition.tags} or some such, so these would be used to keep the movies in separate folders. Perhaps force the use of at least 1 tag when adding a movie a second time...

Surely there has to be a limited way to manually allow this to work without TMDB?

**Comment by galli-leo** [comment]
@JamzTheMan Of course we can implement this on our own. But it will require a significant rework of some parts and I would rather wait on TMDB than have to rework the code twice.

**Comment by akizzle** [comment]
Well what I noticed is Radarr already recognized that the movie was Unrated. When clicking on the movie in Radarr under "Edition" it shows that it's the unrated version.

**Comment by weirdcrap** [comment]
That I believe is parsed from the filenames not from tmdb

**Comment by galli-leo** [comment]
@weirdcrap Correct.

**Comment by xandian** [comment]
Being able to add multiple versions of a movie is a feature I was just about to request, as I needed this whilst importing my old library, but stumbled upon this issue.
I would say that this issue doesn't only concern different editions of a movie, but **different languages** as well, e.g. a movie which you would want in both the original language as well as your own local language.

First off, shouldn't this issue be split into two (REPLACE editions and ADD editions)?

In regards to adding multiple versions, I also noticed that Radarr already have support for parsing editions from the filename.
My suggestion would be to simply add the possibility to add another file, during importing movies, for files that are detected and not already added to the database, with the possibility for the user to manually select the version or enter a manual text.
This selected (parsed from the filename) version or manually entered text, would be added to the filename as the version/edition.

This would simply mean that a movie would still have only one entry in the database, but under Files for that particular movie, there would exist multiple files.

**Comment by Qstick** [comment]
This can be done with CF in V3
