### ISSUE TITLE
Movie already added but not accessible

### ISSUE THREAD

**Issue by mikey2p22** [Radarr/Radarr#1295]
I saw, that there was already an issue and this should be solved in the nightly branch.
(Bug: Radarr says movie already added but not searchable via search bar #1136)

I reopened this issue because I am on the nightly branch but I have some movies that still have this bug.
When I search the movie in the app (Sonarrlink for android) the Movie appears.

Can't add Movie because it already exists:
![image](https://cloud.githubusercontent.com/assets/18078206/24539463/f25d3ce0-15ee-11e7-86d4-e9ddda7a7cce.png)

No results in search:
![image](https://cloud.githubusercontent.com/assets/18078206/24539493/20a36fc0-15ef-11e7-844e-dffb6fa1f1fd.png)

No Entry in complete movie list (Search via Browser):
![image](https://cloud.githubusercontent.com/assets/18078206/24539512/49023988-15ef-11e7-8a7d-721c1a06662e.png)

My Radarr Version:
![image](https://cloud.githubusercontent.com/assets/18078206/24539550/82d68ae2-15ef-11e7-8265-7f5175e8295e.png)

**Comment by galli-leo** [comment]
Can you restart Radarr?

**Comment by mikey2p22** [comment]
Somehow this works now... I restarted Radarr multiple times without success. Even my NAS.
Now, 2 days later, The Movies appear in the search-bar.
Thanks for the help anyway.

**Comment by galli-leo** [comment]
@mikey2p22 I think the problem is where the cache of your browser still kept the UI of an older version with a bug present.
