### ISSUE TITLE
[Feature Request] Bulk import search subfolders

### ISSUE THREAD

**Issue by Mushin** [Radarr/Radarr#1296]
**Description:**

I currently have my movies organised by year, e.g. \Movies\2016\Arrival (2016)\

When I try to use the bulk importer to add my movies to Radarr, it only works if I add the year folder, not the main Movies folder.

Would it be possible to make the bulk importer search subfolders?

**Radarr Version:** 0.2.0.535

**Comment by galli-leo** [comment]
There is an issue open for this already. We will not support such folder structures in the near futures, since it will require a rewrite of a lot of code.
