### ISSUE TITLE
after RSS/Indexer Sync, Radarr does not download available title

### ISSUE THREAD

**Issue by dVIAN13** [Radarr/Radarr#1297]
Description:

I have added a title as monitored, and after adding, it shows missing, but available. My understanding was that after the rss/indexer search, if the title was available, it would automatically download the title.

After adding the title, I clicked on RSS sync, and it does not automatically download the title. If i look at the manual search, it shows as being available to download. If i click the magnifying glass, it will search and download the title.

I am probably not fully understanding how the system works... 

I thought it worked like sonarr, where if i add a title, whether new or old, as long as i add it marked as "monitored", it will search for it the next time the rss sync/indexer search happens..

Radarr Version: 0.2.0.571

Logs:

![screen shot 2017-03-31 at 8 55 14 am](https://cloud.githubusercontent.com/assets/22992333/24558442/03556ad0-15f0-11e7-9ec8-dcc4e103f592.png)

**Comment by 4getit** [comment]
Does the RSS feed actually contain the movie?
RSS feeds normally show you the latest additions of whatever indexer or site. I think you want a 'search'.
If you want a full sweep search of everything you have monitored, go to the Wanted tab and select 'Search All'.

**Comment by dVIAN13** [comment]
Thanks for the reply. The RSS/List, is StevenLu's, and it adds the titles to my Movies list. However, I assumed that by being in my Movie/Wanted List, it would automatically search for those titles periodically...?

**Comment by galli-leo** [comment]
@dVIAN13 That's currently not in Radarr yet. We plan to add that for the 0.2 release, but it will have to wait.
