### ISSUE TITLE
NZBGet - Get added to the Queue twice.

### ISSUE THREAD

**Issue by Snookieboy** [Radarr/Radarr#1300]
Running latest build of Radarrr on Mac OSX

Version
0.2.0.535
Mono Version
4.2.1 (explicit/6dd2d0d Tue Nov 10 18:01:18 EST 2015)

Using Downloader NZBGet connected.

When it goes to add an NZB to it, it always adds every movie twice regardless of source.

Example in log:

17-4-1 09:19:19.1|Info|Nzbget|Adding report [Movie.2009.1080p.BluRay.DTS-ES.x264] to the queue.
17-4-1 09:19:19.6|Info|Nzbget|Adding report [Movie.2009.1080p.BluRay.DTS-ES.x264] to the queue.
17-4-1 09:19:20.8|Info|DownloadService|Report sent to NZBGet. Movie.2009.1080p.BluRay.DTS-ES.x264
17-4-1 09:19:20.8|Info|DownloadService|Report sent to NZBGet. Movie.2009.1080p.BluRay.DTS-ES.x264
17-4-1 09:19:20.9|Info|MovieSearchService|Movie search completed. 1 reports downloaded.

**Comment by galli-leo** [comment]
Known issue. Partially fixed on the latest nightly.
