### ISSUE TITLE
Movies results incorrect, "Downloaded" header un-filters results

### ISSUE THREAD

**Issue by JamzTheMan** [Radarr/Radarr#1301]
In the Movies view, when you have Missing filter clicked, and then you click the "Downloaded" header to filter, it shows ALL movies again. Clicking on other sort headers correctly filters the results again.

--Sort by Downloaded
![image](https://cloud.githubusercontent.com/assets/8051654/24582782/f0e730be-16fc-11e7-97a5-ee1e1c306956.png)

vs

--Sort by Date
![image](https://cloud.githubusercontent.com/assets/8051654/24582794/0f0a9018-16fd-11e7-933f-c9169581e006.png)

**Comment by galli-leo** [comment]
Yeah this is a limitation of the current UI. We can't currently have two filters at once.

**Comment by JamzTheMan** [comment]
I'm afraid you may have missed the issue?  This is only ONE filter, in this case Status == "Missing".
If you click Title, Date Added, Profile, or In Cinemas, the "Missing" movies are "Sorted" correctly.

However, if you click "Downloaded" to sort (NOT filter) it breaks the one filter I want (missing)...

**Comment by galli-leo** [comment]
Yeah that's because if you sort by downloaded, it auto filters by which ones are downloaded. Why would you want to filter by missing and sort by downloading? None of those downloaded are missing.
