### ISSUE TITLE
Downloading scene instead of non-scene when set to not prefer scene.

### ISSUE THREAD

**Issue by bobbintb** [Radarr/Radarr#1302]
I expected there to already be an issue on this but I did not find one. Forgive me if I overlooked.

I have my indexer set to prefer golden and not prefer scene. The torrent I downloaded does not have a golden popcorn but it does have a scene and a non-scene, non-golden popcorn. I would expect it to download the non-scene file but it downloaded scene instead. Anyone else having the issue?

Radarr v0.2.0.535

**Comment by galli-leo** [comment]
Did the scene release have a higher quality?

**Comment by bobbintb** [comment]
I forgot to mention, no. They were the same quality as far as Radar is concerned: Bluray-1080p. Now that you mention it though, the scene release was a repack, so that is likely the reason. I'm not sure if that is intentional or not. I really only want scene if there is nothing else available, repack or no.

**Comment by galli-leo** [comment]
Yeah that's probably the issue here then. We will have to rethink how propers & repacks are gonna work and are factored into the prioritization of downloads.

**Comment by bobbintb** [comment]
Ok, I just had this happen again but there was no remux, so maybe that wasn't the issue. So maybe it is a bug after all. I still have it set to not prefer scene releases but it downloaded a scene release over a larger non-scene release. I'm trying to find something in the logs but I don't think the log level is set high enough. Would you like me to send the log? Is there another issue out like this?

**Comment by galli-leo** [comment]
Nah it's fine. Probably, something to do maybe with propers again.

**Comment by bobbintb** [comment]
There was no proper this time though. It downloaded:
x264 / MKV / Blu-ray / 1080p / Scene / Extended Edition
Movie.1988.Extended.Edition.1080p.BluRay.x264-Group 8.72 GiB

instead of:
x264 / MKV / Blu-ray / 1080p / Extended Edition
Movie.1988.EXTENDED.BluRay1080p.DTS.x264-AnotherGroup 13.06 GiB

I dunno. I have a lot of ratio so I suppose I could reproduce the error but I'd still rather not waste it. I'll probably turn the logs up and keep an eye on it.

**Comment by bobbintb** [comment]
Just did it again. Downloaded:

x264 / MKV / Blu-ray / 1080p / Scene
Movie.2017.1080p.BluRay.x264-DRONES.mkv 6.55 GiB

instead of:

x264 / MKV / Blu-ray / 1080p
Movie.19.2017.1080p.BluRay.DTS.x264-NCmt 8.88 GiB

However the one from the day before worked fine. Not sure what to look for in the logs. No proper again.

**Comment by galli-leo** [comment]
Where did you disable prefer scene? I cannot actually find that option in my Radarr instance.

**Comment by bobbintb** [comment]
It's in the indexer setup for PTP.

**Comment by galli-leo** [comment]
@bobbintb Ah. That option does not actually work IIRC.

**Comment by bobbintb** [comment]
Ah. That explains it then. I can work around it for now then. Do the other ones like prefer GP work?

**Comment by galli-leo** [comment]
@bobbintb No but you can generally prefer Golden, approved, etc. in the indexer settings. (General settings there where the hardcoded subs options are located)

**Comment by bobbintb** [comment]
@galli-leo That's what I'm talking about. Now I'm confused. Here are my indexer settings:
![image](https://user-images.githubusercontent.com/2601376/27235660-e06f6c5c-527e-11e7-8519-4ef729ca20a9.png)

You're saying 'prefer scene' doesn't work, right? Which would explain why it downloads a scene release over a non-scene release when I have it set to 'no'. What I was asking was if the other options like 'prefer golden' work. Your answer is kind of confusing because you say 'no' but then 'yes', kind of.

**Comment by bobbintb** [comment]
Had another scene release downloaded when there are two better non-scene releases. Not sure what to make of this since I didn't quite understand the last response.

**Comment by galli-leo** [comment]
Sorry about not responding. Must have missed the notification :/ So essentially these options never worked in the first place. They were very hacky. However, when we introduced a new system to handle Golden, Approved, Freeleech, etc. we also introduced an option to make those release a higher priority.

This option is called Prefer Special Indexer Flags and can be found under Settings -> Indexers.

**Comment by bobbintb** [comment]
Sorry to bring this up again but I had a follow up question just come up with a recent download. I have it set to prefer indexer flags. How does this work exactly? For example, if PTP has a torrent with a golden popcorn and a scene flag, which will it download? I'm assuming it will download the golden popcorn. Secondly, I try to get the best quality encode, which on PTP would be golden popcorn, if available. Scene is generally the lowest quality but I'll get it if there is nothing else. But with this setting that lumps all flags together, it seems to create a problem. If there is a scene release and no golden popcorn, it downloads the scene, which I only want as a last resort. In a sense, it lumps the highest quality and lowest quality together because they are both special flags.

**Comment by galli-leo** [comment]
@bobbintb Yeah currently Radarr will just prefer any release with an indexer flag. This will be fixed in the upcoming custom formats update, where you can create a format for e.g. golden popcorn.
