### ISSUE TITLE
Radarr Service not Automatic starting

### ISSUE THREAD

**Issue by ibra0078** [Radarr/Radarr#1303]
After a reboot, the service will not start on its own. Startup type is set to Automatic of course but after a reboot I always need to start it manually.

**Comment by galli-leo** [comment]
Do you see any attempt of starting up in the logs? Without any logs we wont be able to help much :/

**Comment by ibra0078** [comment]
Nothing gwea registered in the log file in regards to trying to start the
service. The last entry was at 1:45am yesterday as It snatched a movie. I
restarted the computer today and service didn't start nor it didn't record
anything in the log since 1:45am. Thanks

**Comment by ipark** [comment]
I am having the same issue, not sure if this is helpful or not but when I try to start the service manually I receive these errors:

```
The Radarr service failed to start due to the following error: 
The service did not respond to the start or control request in a timely fashion.
```

```
A timeout was reached (30000 milliseconds) while waiting for the Radarr service to connect.
```

**Comment by ibra0078** [comment]
I fixed it, added the radarr.console.exe to the startup folder

**Comment by ipark** [comment]
radarr.console.exe fails unless I run it as an administrator, is there anyway around this? It says permission denied and that something else is using port 7878 (but nothing is using it - pretty sure it's error due to permissions).

**Comment by ibra0078** [comment]
Are you running anything else on port 7878? Run netstat it will say

**Comment by ipark** [comment]
No, nothing else is running on port 7878.

**Comment by Goot449** [comment]
I am having the Same Issue.

I try to start the service manually, this was all that was in the Radarr Log. Windows just said 

> The Radarr service failed to start due to the following error: 
The service did not respond to the start or control request in a timely fashion.


This is all that was in the Logs of Radarr
`17-4-11 12:27:38.4|Info|Bootstrap|Starting Radarr - C:\ProgramData\Radarr\Bin\Radarr.Console.exe - Version 0.2.0.596
17-4-11 12:27:50.3|Info|MigrationLogger|*** Migrating data source=C:\ProgramData\Radarr\nzbdrone.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
17-4-11 12:27:56.6|Info|MigrationLogger|*** Migrating data source=C:\ProgramData\Radarr\logs.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***`

I was able to start Radarr myself just fine by launching the console exe but I don't want to have to leave this console window open.

The computer is running windows 8.1 x64

**Comment by astlaurent** [comment]
I had this issue but I put the service in delayed start and it seems better

**Comment by gibxxi** [comment]
If running this on Linux (i.e: Linux-based NAS, or full Linux install) make sure Mono is starting before Radarr. You may need to adjust your package load-order to ensure this. As this will likely differ for different flavours of NAS / Linux distro, I won't elaborate on this further, except to say I had this issue on my QNAP TS453-Pro and juggling the Qpkg load-order solved the problem for me.
