### ISSUE TITLE
Add Genre to Movies [feature request]

### ISSUE THREAD

**Issue by tooviral** [Radarr/Radarr#1305]
One piece of info that I think is missing is Genre.

Would love to see this listied in the Movie's detailed pages.

**Comment by aaronth07** [comment]
Is there really any need? You should not be using Radarr as a media client, but something like Plex instead. Plex automatically downloads movie data from The Movie Database. That includes genres.

**Comment by galli-leo** [comment]
Additionally, I think this will have to wait until we get a new UI.

**Comment by TJohnson93** [comment]
@galli-leo Are you working on a new UI?

**Comment by galli-leo** [comment]
@TJohnson93 We are at least thinking about it.

**Comment by TJohnson93** [comment]
@galli-leo If you'd like a hand let me know :)

**Comment by FrAllard** [comment]
This would also allow us to tell Radarr to prevent it from adding certain genre from the different lists... StevenLu list might have an horror movie in it but I don't want any horror movie in my medias I hate horror movies...

**Comment by TheTomCanuck** [comment]
I would love this. I use the KODI remote to navigate my library which has a genre option. So if I only have a vague idea of what I wanna watch browsing by genre is my best bet.
