### ISSUE TITLE
Add button to test proxy settings

### ISSUE THREAD

**Issue by 0xdevalias** [Radarr/Radarr#1306]
It would be awesome if there was a button to test the proxy settings. Not a major deal, but would help to know that they're right. :)

**Comment by aaronth07** [comment]
Proxy settings? Like a VPN? 

You can test indexers, download clients, connections, and etc by clicking "Test".

**Comment by alias1** [comment]
*nods* But on the screen where you enter proxy settings, there is no test button next to it. You can add the proxy, then go to another screen and test as you mentioned, but this isn't overly intuitive.

It would be good to be able to test from this same settings screen, and know radarr was able to connect to the proxy.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by onedr0p** [comment]
This is an old issue tagged with UI, this is very likely fixed in v3. Please let us know otherwise (and even if you want this feature in v3) and we will reopen the issue.
