### ISSUE TITLE
[Bug] With no movie folders added, imports from list silently fail

### ISSUE THREAD

**Issue by 0xdevalias** [Radarr/Radarr#1309]
If you don't have any 'movie folders' added, then importing from lists get into a weird failure state, where they seem to be added, but clicking through to the page 404's.

Adding a 'movie folder', and ensuring it's selected in the list settings seems to fix this.

**Comment by aaronth07** [comment]
Radarr does not support support a flat folder of movies. You have to have movie folders.

**Comment by alias1** [comment]
Which is fine, but with a fresh install there is nothing that forces me to make that first movie folder, so as a user who doesn't realise that requirement, I might go and try an import a movie, not have a folder set, not get prompted by radarr that I need a folder set, and then find myself in the situation I was in, with a bunch of broken imports and the assumption that that part of radarr must just not work.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by galli-leo** [comment]
@alias1 I agree we should document that a bit more, but a user who sets up a list as a first act, probably know what he is doing and should realise you cannot add a movie folder in the add list dialog.

**Comment by alias1** [comment]
To some degree I agree, but it still feels like a big assumption. Maybe adding some extra validation to the add list dialogue, so it won't let you save it when there are no lists, and tells you how to create one?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
