### ISSUE TITLE
Deleted movies show up in log

### ISSUE THREAD

**Issue by onedr0p** [Radarr/Radarr#131]
After I have downloaded a movie and deleted it from Radarr, it continues to show up in log with an error. Every minute the log spits out this information

![image](https://cloud.githubusercontent.com/assets/213795/21831378/4a54cbdc-d771-11e6-81ce-2aebcb9eeeaa.png)

**Comment by onedr0p** [comment]
I am trying to duplicate this on my my local environment but can't get it replicated. Maybe I should blowout the database on my server and start over to see if it happens again.

**Comment by bobloadmire** [comment]
Is there any resolution to this issue? I did a clean install today of Radarr, added my current library, and i'm in process of upgrading some old 1080p versions with 4k versions. However once done downloading, Radarr won't overwrite the old 1080p version.
