### ISSUE TITLE
Image URL's from API are unusable

### ISSUE THREAD

**Issue by jasontruluck** [Radarr/Radarr#1311]
Hello,
It looks like the images on the API are unusable, at least directly as source values on images, due to the API requests requiring a header for authentication.

i.e. From the `/movie` API response:
```
{
...
"images": [
      {
        "coverType": "poster",
        "url": "/radarr/MediaCover/1/poster.jpg?lastWrite=636200219330000000"
      },
      {
        "coverType": "banner",
        "url": "/radarr/MediaCover/1/banner.jpg?lastWrite=636200219340000000"
      }
    ],
...
}
```

Sonarr looks to get around this by using a URL param for the API key but I see no such option in Radarr. For now a way around this I have used is to load all the images after the fact using XMLHttpRequests but this is a bit cumbersome. It would be great if this option was also available on Radarr's API.

**Comment by galli-leo** [comment]
You can do the same in Radarr?
