### ISSUE TITLE
Radarr is not downloading movies because they are under the size limit even though they aren't.

### ISSUE THREAD

**Issue by aaronth07** [Radarr/Radarr#1312]
Radarr is not downloading movies because they are under the size limit even though they aren't. I found out it's because Radarr is automatically adjusting the movies minimum size. Here is what is says: "limits are automatically adjusted for the movies run time". I could not find how to disable this.

Radarr Version: 0.2.0.535

EDIT: Never mind, being stupid. I looked at the 60min movie size instead of the 140min movie.

**Comment by erylflynn** [comment]
Same issue, specifically for movie Teen Titans: The Judas Contract, there is one link on rarbg.to that meets the requirements.  But error is does not meet maximum size 0B.  Same error is on all links as well even for other qualities. I have changed qualities, changed minimum availability and no change after a new search.

**Comment by fryfrog** [comment]
@aaronth07: You don't want to disable adjustment of minimum size based on run time. That would make selecting a movie based on size far less useful. Instead, you should reduce your size limit if you want to catch movies that small.

@erylflynn: Your issue sounds like maybe the search isn't returning the size of the result or maybe you have you mins and maxs screwed up?

**Comment by erylflynn** [comment]
@fryfrog Radarr comes back with 5 results, the 2 you list and 3 that are 480p.  My quality settings are stock, and set in a similiar fashion to Sonarr.  Minimum at 0 and max at the upper cutoff.  Problem with troubleshooting is that movies are not as common as TV shows.  Next thing to download is possibly months away.

![image](https://cloud.githubusercontent.com/assets/7002628/24731937/46f196e8-1a22-11e7-856d-7fcca0bf8535.png)

![image](https://cloud.githubusercontent.com/assets/7002628/24731957/71065e28-1a22-11e7-9826-ef512b95d8ee.png)

**Comment by galli-leo** [comment]
@erylflynn Seems like Radarr does not have any info about the movie runtime. Can you do an update library and make sure the runtime information is correct on themoviedb.org?

**Comment by galli-leo** [comment]
@erylflynn This should be fixed on the latest nightly. If TMDB does not give us a runtime, I set a default of 110 minutes.
