### ISSUE TITLE
radarr not fetching release when negative delay is set in Availibilty Delay and no Availibilty Profile is set

### ISSUE THREAD

**Issue by nilleiz** [Radarr/Radarr#1313]
**Description:**

When having a movie added without Min Availibilty Profile (like ombi does at the moment) and having a negative value in Settings > Indexers > Availibilty Options > Availibility Delay releases will not be fetched when searching indexers.

**Radarr Version:**
0.2.0.535

**Logs:**

17-4-4 13:12:33.8|Error|DownloadDecisionMaker|Couldn't evaluate decision on <*ReleaseName*" , with spec: AvailabilitySpecification

[v0.2.0.535] System.ArgumentOutOfRangeException: Der addierte oder subtrahierte Wert ergibt eine nicht darstellbare DateTime.
Parametername: value
   bei System.DateTime.AddTicks(Int64 value)
   bei System.DateTime.Add(Double value, Int32 scale)
   bei NzbDrone.Core.Tv.Movie.IsAvailable(Int32 delay) in C:\projects\radarr-usby1\src\NzbDrone.Core\Tv\Movie.cs:Zeile 101.
   bei NzbDrone.Core.DecisionEngine.Specifications.RssSync.AvailabilitySpecification.IsSatisfiedBy(RemoteMovie subject, SearchCriteriaBase searchCriteria) in C:\projects\radarr-usby1\src\NzbDrone.Core\DecisionEngine\Specifications\RssSync\AvailabilitySpecification.cs:Zeile 36.
   bei NzbDrone.Core.DecisionEngine.DownloadDecisionMaker.EvaluateSpec(IDecisionEngineSpecification spec, RemoteMovie remoteMovie, SearchCriteriaBase searchCriteriaBase) in C:\projects\radarr-usby1\src\NzbDrone.Core\DecisionEngine\DownloadDecisionMaker.cs:Zeile 248.

**Comment by galli-leo** [comment]
Well that's kinda a fringe case, since you are expected to set a min availability profile.

**Comment by galli-leo** [comment]
Fixed in latest release.
