### ISSUE TITLE
Movie Editor checkboxes no longer working in nightly 0.2.0.572

### ISSUE THREAD

**Issue by mcroach** [Radarr/Radarr#1314]
Description:

The Selection boxes on the Movie Editor page appears to be broken in latest nightly (0.2.0.572). The problem was not present before the update. 

No matter how many movies are checked, the options in the editor footer remain unavailable, and the textual notation on how many movies have been selected remains at zero.

Clearing the browser cache has no effect.
Restarting Radarr has no effect.

Chrome's developer tools is showing the following error is thrown each time a checkbox is checked/unchecked (MovieEditorFooterView.js:49):

Uncaught TypeError: Cannot read property 'set' of undefined
    at child.<anonymous> (MovieEditorFooterView.js:49)
    at triggerEvents (backbone.js:205)
    at child.trigger (backbone.js:146)
    at child._onModelEvent (backbone.js:933)
    at triggerEvents (backbone.js:206)
    at child.trigger (backbone.js:147)
    at child.onChange (SelectAllCell.js:22)
    at HTMLInputElement.bound (lodash.underscore.js:665)
    at HTMLTableCellElement.dispatch (jquery.js:4670)
    at HTMLTableCellElement.elemData.handle (jquery.js:4338)

Radarr Version:  0.2.0.572 running on QNAP

**Comment by geogolem** [comment]
Im not having any issues with this on the latest build  ---> on Windows..

So it is likely something related to QNAP... 

based on your log and the code:
------
        this.listenTo(this.moviesCollection, 'backgrid:selected', function(model, selected) {
            **var m =  FullMovieCollection.findWhere({ tmdbId : model.get('tmdbId') });**
            m.set('selected', selected);
            this._updateInfo();
        });
------

the problem is with the line: var m =  FullMovieCollection.findWhere({ tmdbId : model.get('tmdbId') });

--> I cant reproduce the problem but Im on Windows... but it seems that the movie is not being found via tmdbID in the fullCollection.

**Comment by mcroach** [comment]
I love random; this morning with no known changes made to the environment everything is working as expected again. If it comes up again I'll fire up the debugger to see if I can track down the culprit.

Closing issue for now.

**Comment by galli-leo** [comment]
Probably happened because of the cache. The UI prolly had an old version of the js code cached causing calls to a changed backend to fail.
