### ISSUE TITLE
Unable to view "Not Monitored" only

### ISSUE THREAD

**Issue by Bterrell721** [Radarr/Radarr#1315]
Hello,

I believe this should be included as a feature request and didn't see an existing report.  I am looking to have a way to view a list of only movies currently in "Not Monitored" status.

The use case for this is that I currently keep all my movies in monitored status, except then I have a number of lists set up that I like to let auto-add movies.  However, I have it add them "Not Monitored" so that I can go back and review and make sure I want them before they are sent to downloader.  Currently I have to view "All Missing" and just search through all the pages for ones that are Not Monitored, but it would be great to be able to toggle if I want to see Monitored or Not Monitored movies only.

Thank you!

**Comment by galli-leo** [comment]
For now you can go to the wanted tab.

**Comment by jpborjas** [comment]
Was this ever fixed? Monitored Only, Missing Only, etc, are not working for me.

**Comment by galli-leo** [comment]
@jpborjas What exactly is not working with them? Please be more specific as all of these work fine for me.

**Comment by jpborjas** [comment]
When I'm on the main screen and select All, Monitor, or Missing Only options, there is no change on the screen whatsoever. I'm always looking at the same movies titles on that screen. This used to work. I'm running 0.2.0.935 Develop Version. Thanks

**Comment by galli-leo** [comment]
@jpborjas Did you do a hard refresh, cleared cookies or tried an incognito window? Also, did you wait long enough for it to happen? Are you on a remote connection, i.e. Radarr is on a different network than your internet browser? What's your page size setting?

**Comment by jpborjas** [comment]
Clearing my browser cookies worked. Thanks a lot!!!
