### ISSUE TITLE
Sorting Movies by downloaded [Bug]

### ISSUE THREAD

**Issue by chuckkay** [Radarr/Radarr#1316]
Sorting by downloaded (ascending or descending) results in ALL movies being listed no matter what filter you are using (monitored, missing, released, announced...etc)

Version
0.2.0.571

I Can re-create bug every time..
steps to re-create bug:

-go to movie tab 
-Click all movies filter (the circle icon)
   make note of total movies you have (mine says Total records: 1,309)
-Click on another filter like "in cinemas"  (the ticket icon)
for in cinemas mine says Total Records: 39
-Click on the downloaded column to sort by downloaded (or use sort by drop down list and select downloaded)
Wait a few seconds and total records are now back to every movie in the library 
(mine says Total records: 1,309 again) 
which is incorrect it should still only show me the 39 movies that are "in cinema" and they should be sorted by the type of quality I have downloaded (or blank)... 

This bug happens with all other types of filters (missing, in cinemas, released etc) when sorting by "Downloaded" but not when sorting by "Title" "Profile" "Date added" etc..

**Comment by galli-leo** [comment]
There's already another issue on this (sorry can't linke, on mobile). The gist of it is, that we currently cannot have more than one filter. (Sorting by downloaded auto filters by downloaded as well).

**Comment by galli-leo** [comment]
We want to improve filtering much more when we have a new UI.

**Comment by galli-leo** [comment]
Fixed in latest nightly.
