### ISSUE TITLE
Pending Releases Stuck in Queue / Also Missing Information

### ISSUE THREAD

**Issue by vertigo235** [Radarr/Radarr#1318]
**Description:**
I have a 400 min Usenet delay, items are showing up pending in my queue, but they never go away, also no quality is noted, it always says "Unknown".

When I try to delete from the queue nothing happens. 

Check first that your problem is not listed in our wiki section:
* https://github.com/Radarr/Radarr/wiki/Common-Problems
* https://github.com/Radarr/Radarr/wiki/FAQ

Provide a description of the feature request or bug here, the more details the better. 
Please also try to include the following if you are reporting a bug

**Radarr Version:**
Radarr Ver. 0.2.0.572

**Logs:**
Per request, but should be able to duplicate this issue by adding a delay profile. 

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by vertigo235** [comment]
Also it appears that the items do still download, although it has picked up the wrong movies (wrong year), once they download the pending items still stay in my queue.  

I have removed them by using a SQL Lite database tool.

**Comment by galli-leo** [comment]
Is this just one or two items or all pending items?

**Comment by tooviral** [comment]
There is two pending torrent downloads as I do have a usenet delay.  They are both listed as quality unknown and I am unable to clear them.

**Comment by galli-leo** [comment]
@tooviral Would it be possible for you to go into the Radarr database (nzbdrone.db located in https://github.com/Radarr/Radarr/wiki/AppData-Directory) using a sqlite editor (e.g. sqlitebrowser.org) and posting a picture of the Pending Releases Table?
