### ISSUE TITLE
Folders get added without IMDB id

### ISSUE THREAD

**Issue by 19wolf** [Radarr/Radarr#1319]
**Description:**
Some folders are being added without an IMDB id when it clearly exists (and is shown on the movie page), but otherwise function fine

**Radarr Version:**
Latest
**Logs:**
Attached
[radarr.txt](https://github.com/Radarr/Radarr/files/895085/radarr.txt)

**Comment by galli-leo** [comment]
Known issue. Fix is actually more complicated and working on a seperate branch. But still needs more testing to make sure nothing else breaks.
