### ISSUE TITLE
Update Movie Naming

### ISSUE THREAD

**Issue by donldmn** [Radarr/Radarr#132]
"Movie Naming" under "Settings" > "Media Management" still show options for TV shows such as series title, episode title, among others.
To change the movie naming style advanced settings must be set to shown.

Advanced: Hidden
![image](https://cloud.githubusercontent.com/assets/25023565/21832199/f8c77f0a-d76e-11e6-8d85-3648728fe831.png)

Advanced: Shown
![image](https://cloud.githubusercontent.com/assets/25023565/21832211/12e44c1a-d76f-11e6-999d-f1d0044ce764.png)

**Comment by fedoranimus** [comment]
Huh. I could have sworn I cleaned that up. Good catch.

**Comment by dawtmaytrikx** [comment]
I also feel this error shouldn't appear.
![2017-01-10 23_21_58-add movie - radarr](https://cloud.githubusercontent.com/assets/3049190/21846589/197fc02a-d7f8-11e6-95c1-963fbdd03d31.png)

**Comment by fedoranimus** [comment]
How are Original Title and Movie Title different? Can you provide what would be expected?

**Comment by judhat2** [comment]
> How are Original Title and Movie Title different?

I assumed that "Original Title" was different because it's the full nzb name.

I configured Sonarr's renamer to only use {Original Title}.  With that setting, Sonarr renames files that have an obfuscated file name to the nzb name.  I also mentioned this in #103
