### ISSUE TITLE
Wrong release year on folder renaming (media management)

### ISSUE THREAD

**Issue by int3nz0r** [Radarr/Radarr#1320]
I noticed this for several movies now.

My movie file format looks like this: {Movie Title} ({Release Year})

But Radarr seems to automatically choose 2017 as the release year, even for movies that are released in 2016 according to IMDb (http://www.imdb.com/title/tt4972582). It looks like Radarr alwasys chooses the year of download. Example:

Split (2017) \ Split.2016.Bluray-720p.x264.DTS-SPARKS

This "bug" (?) causes wrong scraping results in Kodi and other applications. Any thoughts/work arounds?

**Comment by galli-leo** [comment]
That's because The Movie DB (our source of metadata) says that the movie is released in 2017. Not much we can do, but you could change it to correct release date on themoviedb.org

**Comment by int3nz0r** [comment]
@Crowley007 Indeed, that's what's confusing me. I assume both file renaming and folder renaming use the same information provider?

**Comment by galli-leo** [comment]
@Crowley007 What probably happened: TMDB only has 2017 as release date when you added the movie, so the folder was created with 2017. Then the correct date (2016) was added. And then Radarr downloaded and imported the file and thus renamed it with the now correct date, while the folder was unchanged.

**Comment by Crowley007** [comment]
Makes sense I guess, but in that case perhaps Radarr should check if the year differs and if it does rename both to match the correct date.

**Comment by galli-leo** [comment]
@Crowley007 Once we have dynamic folder renaming in, that shouldn't be a problem anymore.
