### ISSUE TITLE
Download Quality Being Changed by Radarr to HDTV-720p and triggering Re-Download

### ISSUE THREAD

**Issue by gold007eye** [Radarr/Radarr#1321]
Just an update.. I think I know what might be causing the downloading to start, finish, delete and restart the same download.  I just noticed with the next movie. it is grabbing as "Blue-Ray 720", but Radarr is tagging the completed download as "**HDTV**-720p"  So then it regrabs the movie again, because "technically" that doesn't meet the cut-off quality.  

That looks like remnants of Sonarr coding maybe fixing that will fix this issue?  If you look at the previous images of mine above showing the history you see the same thing happened.. Radarr setting finished downloaded quality as HDTV-720.

![image](https://cloud.githubusercontent.com/assets/4365462/24717086/d9bae884-19f6-11e7-8a5f-8784b78dc394.png)

Edit:
I am on latest nightly .572

Log section for Split:
`17-4-4 22:28:20.7|Info|Sabnzbd|Adding report [Split.2016.720p.BluRay.x264-SPARKS] to the queue.
17-4-4 22:28:21.2|Info|DownloadService|Report sent to SABnzbd. Split.2016.720p.BluRay.x264-SPARKS
17-4-4 22:28:22.6|Info|RssSyncService|RSS Sync Completed. Reports found: 198, Reports grabbed: 1
17-4-4 22:45:16.4|Info|MovieService|Linking [Split (2016).mkv] > [[tt4972582][Split]]
17-4-4 22:45:17.1|Info|MovieService|Linking [Split (2016).mkv] > [[tt4972582][Split]]
17-4-4 23:13:26.4|Info|RssSyncService|Starting RSS Sync
17-4-4 23:13:27.5|Info|DownloadDecisionMaker|Processing 198 releases
17-4-4 23:13:31.9|Info|Sabnzbd|Adding report [Split.2016.720p.BluRay.x264-SPARKS] to the queue.
17-4-4 23:13:32.3|Info|DownloadService|Report sent to SABnzbd. Split.2016.720p.BluRay.x264-SPARKS
17-4-4 23:13:33.2|Info|RssSyncService|RSS Sync Completed. Reports found: 198, Reports grabbed: 1
17-4-4 23:22:52.8|Info|NetImportSearchService|No lists are enabled for auto-import.
17-4-4 23:23:54.4|Info|PreDBService|Starting PreDB Sync
17-4-4 23:23:54.6|Warn|PreDBService|Non 200 StatusCode Forbidden encountered while searching PreDB.
17-4-4 23:25:28.2|Info|RecycleBinProvider|Recycling Bin has not been configured, deleting permanently. T:\Movies\Split (2017)\Split (2016).mkv
17-4-4 23:25:33.9|Info|MovieService|Linking [Split (2016).mkv] > [[tt4972582][Split]]
17-4-4 23:25:34.1|Info|MovieService|Linking [Split (2016).mkv] > [[tt4972582][Split]]
17-4-4 23:30:44.0|Warn|MediaCoverMapper|File C:\ProgramData\Radarr\MediaCover\92\poster.jpg not found
17-4-4 23:30:44.0|Warn|MediaCoverMapper|File C:\ProgramData\Radarr\MediaCover\88\poster.jpg not found
17-4-4 23:30:44.5|Warn|MediaCoverMapper|File C:\ProgramData\Radarr\MediaCover\92\poster.jpg not found
17-4-4 23:30:44.5|Warn|MediaCoverMapper|File C:\ProgramData\Radarr\MediaCover\88\poster.jpg not found`

Edit 2:
Also noticed HDTV is in the Quality profiles.  as you can see I don't have them checked at all, but shouldn't anything related to TV be removed since this is for Movies?

![image](https://cloud.githubusercontent.com/assets/4365462/24717958/e12e3852-19f9-11e7-97dc-83e41582f4d6.png)

**Comment by gold007eye** [comment]
Any update on this issue?

**Comment by FrankOrtmann** [comment]
I have a feeling that some cases are caused by, for example, files marked as 720p because their horizontal pixel count is 1280px, but because the film was not shot at 16:9, the vertical pixel count is 536px (21:9).
