### ISSUE TITLE
Add ability to disable media info on import.

### ISSUE THREAD

**Issue by animosity22** [Radarr/Radarr#1328]
My current setup is using some local storage and an ACD encrypted mount point for all my archiving of my stuff.

I have some naming conventions previously from Couchpotato that had the shorter quality type info in there and I do not want it to analyze the media and 'trust' the fact it's named right. I turned off the Analyze Video option in the setting, but it seems to still analyze the file.

I gave the example in the log. Is there a way to prevent the analyze of the file as I just want to match it based on the name and assume I have the quality right as if it has to scan each file, that tends to take a day based on the size of the library that I'm trying to import in.

Check first that your problem is not listed in our wiki section:
* https://github.com/Radarr/Radarr/wiki/Common-Problems
* https://github.com/Radarr/Radarr/wiki/FAQ

Provide a description of the feature request or bug here, the more details the better. 
Please also try to include the following if you are reporting a bug

**Radarr Version:**

**Logs:**
```
17-4-6 11:46:22.0|Debug|Parser|Quality parsed: Unknown v1
17-4-6 11:46:22.0|Debug|Parser|Release Group parsed:
17-4-6 11:46:22.0|Debug|Parser|Parsing string '13.Sins.(2014)'
17-4-6 11:46:22.0|Debug|Parser|Movie Parsed. 13 Sins - 2014
17-4-6 11:46:22.0|Debug|Parser|Language parsed: English
17-4-6 11:46:22.0|Debug|QualityParser|Trying to parse quality for 13.Sins.(2014)
17-4-6 11:46:22.0|Debug|Parser|Quality parsed: Unknown v1
17-4-6 11:46:22.0|Debug|Parser|Release Group parsed:
17-4-6 11:46:22.0|Debug|DiskScanService|Scanning '/media/Movies/13.Sins.(2014)' for video files
17-4-6 11:46:22.2|Debug|DiskScanService|1 video files were found in /media/Movies/13.Sins.(2014)
17-4-6 11:46:22.2|Debug|ImportDecisionMaker|Analyzing 1/1 files.
17-4-6 11:46:22.2|Debug|Parser|Parsing string '13.Sins.1080p.mp4'
17-4-6 11:46:22.2|Debug|Parser|Unable to parse 13.Sins.1080p.mp4
17-4-6 11:46:22.2|Debug|Parser|Attempting to parse episode info using directory and file names. 13.Sins.(2014)
17-4-6 11:46:22.2|Debug|Parser|Parsing string '13.Sins.(2014) 13.Sins.1080p.mp4'
17-4-6 11:46:22.2|Debug|Parser|Movie Parsed. 13 Sins - 2014
17-4-6 11:46:22.2|Debug|Parser|Language parsed: English
17-4-6 11:46:22.2|Debug|QualityParser|Trying to parse quality for 13.Sins.(2014) 13.Sins.1080p.mp4
17-4-6 11:46:22.2|Debug|Parser|Quality parsed: HDTV-1080p v1
17-4-6 11:46:22.2|Debug|Parser|Release Group parsed:
17-4-6 11:46:22.2|Debug|ImportDecisionMaker|Size: 7995668202
17-4-6 11:46:22.2|Debug|VideoFileInfoReader|Getting media info from /media/Movies/13.Sins.(2014)/13.Sins.1080p.mp4
17-4-6 11:46:27.7|Debug|ImportDecisionMaker|Checking quality for this video file to make sure nothing mismatched.
17-4-6 11:46:27.7|Debug|FreeSpaceSpecification|Skipping free space check for existing episode
17-4-6 11:46:27.7|Debug|VideoFileInfoReader|Getting media info from /media/Movies/13.Sins.(2014)/13.Sins.1080p.mp4
```

**Comment by animosity22** [comment]
I was trying to work around this.

My use case is that I have ~10TB on a cloud drive and slow seek times. 

I want to bulk import about 1000 or so movies that are there so Radarr knows about them.

Is there anyway to do that now? I don't mind if something takes a day but if I try via the gui, it just hangs trying to enumerate all the files using the bulk import there.

**Comment by galli-leo** [comment]
@animosity22 not really. The only option i see is doing the bulk import with a page size of 25 or even lower.

**Comment by animosity22** [comment]
@galli-leo  - so the page size would limit it to only grabbing 25 items? I think I can do like a 100 at a time and just leave it spin while at work 👍

**Comment by animosity22** [comment]
@galli-leo  - since we were having the trakt discussion earlier, you gave me a great idea for a work around.

I used the trakt list of Collection, imported them as not monitored, updated the path to my ACD path instead, refreshed the series and it found them without doing any type of analyze.

**Comment by galli-leo** [comment]
@animosity22 Good to hear that!

**Comment by Qstick** [comment]
Should be fixed in Aphrodite
