### ISSUE TITLE
Is there a limit to the number of items Radarr will retrieve from a tracker?

### ISSUE THREAD

**Issue by talentedmrripley** [Radarr/Radarr#1329]
**Description:**
I added The Fifth Element to Radarr and told it to search.  I have specified Remux for quality but it didn't begin to download anything.  I checked manually to see if there was an issue with size or name parsing etc, these are the options it presented:

![image](https://cloud.githubusercontent.com/assets/10006695/24766260/e4e09634-1ab7-11e7-9d8d-1bad9454af25.png)

I was surprised to not see a remux available and went to check what the tracker had available.  

![image](https://cloud.githubusercontent.com/assets/10006695/24766312/106efe58-1ab8-11e7-8397-435f5ba66a1c.png)

There is a Remux available, but it and several of the other versions weren't displayed in Radarr.  Does the software have a cap on the number of items it can/will retrieve?  Can that limit be changed?

**Radarr Version:**
0.2.0.535

**Comment by galli-leo** [comment]
@onedr0p Can you take a look at this?
