### ISSUE TITLE
Web UI won't load - not caching issue

### ISSUE THREAD

**Issue by pferreira** [Radarr/Radarr#1330]
GET http://10.0.0.197:7878/api/movie?page=1&pageSize=1000&sortKey=sortTitle&sortDir=asc&filterKey=null&filterValue=null 500 (Internal Server Error)
send @ jquery.js:9664
ajax @ jquery.js:9215
$.ajax @ jquery.ajax.js:21
get @ ApiData.js:7
(anonymous) @ MoviesCollection.js:282
__webpack_require__ @ bootstrap 437fb7d…:50
(anonymous) @ FullMovieCollection.js:1
__webpack_require__ @ bootstrap 437fb7d…:50
(anonymous) @ Search.js:5
__webpack_require__ @ bootstrap 437fb7d…:50
(anonymous) @ NavbarLayout.js:5
__webpack_require__ @ bootstrap 437fb7d…:50
(anonymous) @ main.js:6
__webpack_require__ @ bootstrap 437fb7d…:50
webpackJsonpCallback @ bootstrap 437fb7d…:21
(anonymous) @ main.js?h=n+hiLPt76AGo3E/jajILug:1
ApiData.js:13 Uncaught Internal Server Error
(anonymous) @ ApiData.js:13
fire @ jquery.js:3148
add @ jquery.js:3194
get @ ApiData.js:12
(anonymous) @ MoviesCollection.js:282
__webpack_require__ @ bootstrap 437fb7d…:50
(anonymous) @ FullMovieCollection.js:1
__webpack_require__ @ bootstrap 437fb7d…:50
(anonymous) @ Search.js:5
__webpack_require__ @ bootstrap 437fb7d…:50
(anonymous) @ NavbarLayout.js:5
__webpack_require__ @ bootstrap 437fb7d…:50
(anonymous) @ main.js:6
__webpack_require__ @ bootstrap 437fb7d…:50
webpackJsonpCallback @ bootstrap 437fb7d…:21
(anonymous) @ main.js?h=n+hiLPt76AGo3E/jajILug:1
jquery.js:9664 GET http://10.0.0.197:7878/api/queue?sort_by=timeleft&order=asc 500 (Internal Server Error)

Running latest version of Radarr.  I imported my movies yesterday.  Today the web UI just won't load.  The dots go back and forth forever and when I look at the logs when you hit control shift I in chrome this is what I get.  Any thoughts on what I should do? (I tried clearing logs, loading in incognito and even booted up my mac and tried it in chrome for mac).  My library is maybe 1100 or 1500 movies if I had to guess (I had like 485 maybe and I think it imported like 1100 more so 1585 I'm guessing?)  It's still adding movies from time to time in my sabnzbd so it is working, it's just the webui won't.

**Comment by tscibilia** [comment]
I've come across the exact same issue! glad i'm not the only one, i'm just hoping there's a way to fix it.

**Comment by pferreira** [comment]
Radarr has a lot of potential, and couchpotato is a mess.  I posted that I'd be willing to support this project when it was ready, and someone responded that it was.  I gave it a shot, but without a direction to move forward and go through a trouble shooting process, and with the very limited documentation set I don't think I can agree that it is ready.  Good luck with this project. I'll check back in a year and see how things are progressing.

**Comment by galli-leo** [comment]
Can you post logs? You find them in your AppData directory (See the wiki for where that's located)

**Comment by pferreira** [comment]
[radarr.txt](https://github.com/Radarr/Radarr/files/906726/radarr.txt)

**Comment by galli-leo** [comment]
@pferreira From the logs it seems like you messed up a UNC path. Can you try and edit the Radarr db to remove the errouneous paths?

**Comment by pferreira** [comment]
I never defined any UNC paths... all the paths are static as far as radarr knows.  The other errors about not finding goodquality/a-f is legit I moved all the movies into a single directory because it was only picking up on a few of them. How do I edit the db file nano?

**Comment by galli-leo** [comment]
@pferreira You have to grab a sqlite editor (e.g. sqlitebrowser.org). But I would just delete the database and start a new in your case, if you have not added many movies yet.

**Comment by galli-leo** [comment]
Is this still an issue on the latest Radarr version?

**Comment by brkaminski** [comment]
I just encountered this issue in the past 2 days.  Radarr had been installed and working flawlessly until sometime Tuesday night.  I have not been able to get the program up and running again, even on a new VM.

Running on Ubuntu server 16.04 LTS. Going to give Centos a try to see if it's a server issue.

**Comment by galli-leo** [comment]
@brkaminski Probably an issue with updating to the latest mono version. 5.10 and anything below .995 of Radarr won't work together, you either need a manual update of Radarr or downgrade mono.
