### ISSUE TITLE
Feature Request: Remote Path Mapping Copy Progress Status

### ISSUE THREAD

**Issue by beefycheddar** [Radarr/Radarr#1331]
**Description:**
Love the clone. We are all saying "it's about time!"

I use a remotely accessed nzb downloader and I use the remote path mapping feature. It works great. My local server has a slower (sub 10mbps) connection to the downloader, so when a file starts to copy over, my whole network connection can be saturated with no indication of how long this may last. I think it would be improved by adding a progress indicator (bar, pie chart, ##%) next to the file being copied in the movie page or in the Activity page. 

What do you think?

**Comment by bakerboy448** [comment]
https://github.com/Radarr/Radarr/issues/1333 is related;  closing this in favor of covering it there.
