### ISSUE TITLE
Setting up Multiple Lists Default Folder

### ISSUE THREAD

**Issue by mrsparkle969** [Radarr/Radarr#1332]
**Description:**
When setting up multiple lists the default folder is reverting to the last folder set: 

List 1 R rated goes to R rated folder
List 2 PG rated goes to kids folder

When you set list 2 to the kids folder list 1 changes to kids.
Set List 1 back to r rated folder List 2 changes to R rated folder

**Radarr Version:**
0.2.0.535

**Comment by galli-leo** [comment]
That is a known issue and only UI related. The actual folder is not changed.
