### ISSUE TITLE
Feature Request: download 1080p first then replace with 2160p

### ISSUE THREAD

**Issue by xxredxpandaxx** [Radarr/Radarr#1335]
It always seems like you have to wait a month or more for a 2160p version to be released. So it would be nice to be able to download a 1080p version of a file and then later when the 2160p versions get released download that.

**Comment by zductiv** [comment]
You should already be able to do this. 

Go to settings->profiles. Then click add. Name as you want and tick all of the 2160p qualities you want, and the 1080p qualities you want. Then change the cutoff to the minimum quality 2160p you want.

Something like this.

![image](https://cloud.githubusercontent.com/assets/8939440/24796093/36476438-1bbe-11e7-8113-6dd9963c8ca1.png)

Then just change the assigned profile on the movies you want to change to this.

**Comment by galli-leo** [comment]
Not sure what your issue here is. That's already in Radarr.

**Comment by xxredxpandaxx** [comment]
Oh, thanks! I didn't know I could do that.
