### ISSUE TITLE
Unable to connect to indexer

### ISSUE THREAD

**Issue by Kryten121** [Radarr/Radarr#134]
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 322
Close
Radarr Ver. 0.2.0.61

Unable to connect to indexer: Sequence contains no elements

Log shows that error when testing the connection, the connection is fine as it works in SOnarr without a hitch.

**Comment by onedr0p** [comment]
Please provide more information like what indexer you are using.

**Comment by Kryten121** [comment]
usenet crawler and www.newztown.co.za also when I switch to the default ones that don't require an API key like fanzub it fails on that too

**Comment by onedr0p** [comment]
Fanzub.com is closed, I'll remove this one

**Comment by onedr0p** [comment]
I did some more investigations it appears that usenet-crawler and newztown doesn't support search for movies, they do support searching for TV series hence it works with Sonarr.
`<movie-search available="no" supportedParams="q" />`

Maybe contact the staff of those sites and see if they will turn it on.

**Comment by onedr0p** [comment]
duplicate #4 closing
