### ISSUE TITLE
Movies picked up with wrong year

### ISSUE THREAD

**Issue by erwintwr2** [Radarr/Radarr#1347]
**Description: Movies picked up with wrong year

Version
0.2.0.535

I am picking it up a few times where movies is detected incorrectly from my download folder. ( using drone factory folder with completed downloading switch off)

for example  : 

have Detour(2013) and Detour (2016) in library 

Detour 2016 is downloaded, but then the following happens :  
Name: Detour
Source: C:\Downloads\Complete\Movies\Detour.2016.720p.BRRiP.900MB.ShAaNiG.mkv
Imported To: \\storage\Movies\D\Detour (2013)\Detour (2013) Bluray-720p.mkv

Same with aftermath

have Aftermath (2012) and am trying to get Aftermath 2016

Name:Aftermath
Source: C:\Downloads\Complete\Movies\Aftermath.2017.720p.WEB-DL.850MB.ShAaNiG.mkv
Imported To:\\storage\Movies\A\Aftermath (2012)\Aftermath (2012) WEBDL-720p.mkv

currently i have recyle bin configued, thus movies is not completely missing, but still a mess to sort out.

Any ideas what could be causing this?
i could probably attempt with completed downloading switched on.

Thx

PS

one additional issue , it replaced in one instance the movie trailer and not the actual movie

(file was named Detour (2013)-trailer,flv and was <100Mb in size).  maybe at a check in to ignore trailer files if possible?)

**Comment by galli-leo** [comment]
Can you try with completed downloading on as well as using the latest nightly?

**Comment by erwintwr2** [comment]
ok will test. How to i activate latest nightly? ( windows)

**Comment by galli-leo** [comment]
Go to Settings -> General -> Updates -> Branch -> Set to "nightly" (Without quotes). Might need to enable Advanced Settings for that to show up.

**Comment by erwintwr2** [comment]
done :) 
ok will report back if i notice again ( might just redownload the same file)

**Comment by Quiksmage** [comment]
I had a problem with It 2017 grabbing the original "It", but since switching to nightly and doing manual searches on it/beauty and the beast/ etc, I haven't found an instance where a different year with the same name was showing up. Thanks for fixing this!

**Comment by animosity22** [comment]
Nice. I was seeing this with Split as it was finding the 2016 version. I'll wait till it get pushed to develop as I'm not quite the "Nightly" type of guy :)

**Comment by galli-leo** [comment]
@animosity22 That commit should be on the latest release (.596) now.

**Comment by animosity22** [comment]
I'm not seeing the issue anyone. Confirmed for me.

**Comment by animosity22** [comment]
Still seems to be working ok. I got this hit but it was wrong on the indexer:

https://dognzb.cr/details/ee3946260298a94cfe9f9e6652011a36

The search has it for 2017 Split, but the files from 2016.
