### ISSUE TITLE
No results returned from Hydra

### ISSUE THREAD

**Issue by peavers** [Radarr/Radarr#1348]
Radarr Version: 0.2.0.535

Setting Hydra as my only indexer returns no results to Radarr. 

I can see in my logs on Hydra that the search is being hit from Radarr, and Hydra has results returned when I manually search the same thing on Hydra. However nothing is making it back to Radarr. If I disable Hydra in Radarr and add my indexers directly things work as expected. 

Don't know how much help it is but Hydra is working fine with Sonarr. 

Sorry I know this is vague, but if you're aware of anything that could cause this?

**Comment by galli-leo** [comment]
Do you see anything in the logs of Radarr? Also might be worth turning on Debug logging, trying again and then looking into the logs.

**Comment by Jleagle** [comment]
I also have just started having issues with Radarr/Hydra. Getting "All search-capable indexers are temporarily unavailable due to recent indexer errors" in system.

**Comment by onedr0p** [comment]
Not sure what is going on, but hydra seems to be working here.

**Comment by weirdcrap** [comment]
I am using the latest Hydra as my sole NZB Indexer as well without any issues.

**Comment by peavers** [comment]
From the debug logs:
```
17-4-10 21:42:31.8|Info|NzbSearchService|Searching 1 indexers for [127 Hours]
17-4-10 21:42:31.8|Debug|Newznab|Downloading Feed http://(removed)api?t=movie&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060&extended=1&apikey=(removed)&offset=0&limit=100&imdbid=1542344
17-4-10 21:42:31.9|Debug|NzbSearchService|Total of 0 reports were found for [127 Hours] from 1 indexers
17-4-10 21:42:31.9|Info|DownloadDecisionMaker|No results found
```
If I hit that endpoint in my browser I get: 
```
<rss xmlns:newznab="http://www.newznab.com/DTD/2010/feeds/attributes/" version="2.0">
<channel>
<title>NZB Hydra</title>
<description>NZB Hydra - the meta search</description>
<link>https://github.com/theotherp/nzbhydra</link>
<language>en-gb</language>
<webMaster>TheOtherP@gmx.de (TheOtherP)</webMaster>
</channel>
</rss>
```
I don't see anything else in the logs that look like things have gone wrong, just getting zero results back...

**Comment by galli-leo** [comment]
@peavers Can you remove 2060 from the category string in Radarr and try again?

**Comment by galli-leo** [comment]
Also maybe the imdbid is not correctly used in your indexers?

**Comment by peavers** [comment]
Have removed 2060 and still no luck I'm afraid, using nzb.su and oznzb which both support imdbid as far as I know. Any other suggestions?

**Comment by peavers** [comment]
Trace logs, might be helpful. Is the database being locked an issue here?
```
17-4-10 22:19:55.1|Info|NzbSearchService|Searching 1 indexers for [127 Hours]
17-4-10 22:19:55.2|Debug|Newznab|Downloading Feed http://(removed)/api?t=movie&cat=2000,2010,2020,2030,2035,2040,2045,2050&extended=1&apikey=(removed)&offset=0&limit=100&imdbid=1542344
17-4-10 22:19:55.2|Trace|HttpClient|Req: [GET] http://(removed)/api?t=movie&cat=2000,2010,2020,2030,2035,2040,2045,2050&extended=1&apikey=(removed)&offset=0&limit=100&imdbid=1542344
17-4-10 22:19:55.2|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
17-4-10 22:19:55.2|Trace|HttpClient|Res: [GET] http://(removed)/api?t=movie&cat=2000,2010,2020,2030,2035,2040,2045,2050&extended=1&apikey=(removed)&offset=0&limit=100&imdbid=1542344: 200.OK (32 ms)
17-4-10 22:19:55.3|Trace|Owin|SQLite error (5): database is locked

17-4-10 22:19:55.3|Debug|NzbSearchService|Total of 0 reports were found for [127 Hours] from 1 indexers
17-4-10 22:19:55.3|Info|DownloadDecisionMaker|No results found
```

**Comment by galli-leo** [comment]
No that's a "normal" error that does not influence anything, hence why it is only on a Trace level. Can you try only using category 2000? Also can you try (in a browser) using q=Star+Wars instead of imdbid=...?

**Comment by peavers** [comment]
Thanks heaps for the responses so far. 

Removing everything but 2000 didn't change anything; Sending a query via Postman returns a bunch of objects/matches looking like...
```
        <item>
            <title>Rogue.One.A.Star.Wars.Story.2016.TRUEFRENCH.720p.BluRay.x264-SOZER</title>
            <guid isPermaLink="false">bda992ec82be0e94e14972df43c114540e8ab14f</guid>
            <link>http://(removed)/getnzb?apikey=(removed)&amp;searchresultid=bda992ec82be0e94e14972df43c114540e8ab14f</link>
            <comments>https://nzb.su/details/76b62165242e3e05d2278bd11324fdaa</comments>
            <pubDate>Thu, 06 Apr 2017 09:16:35 -0400</pubDate>
            <category>Movies</category>
            <description>Rogue.One.A.Star.Wars.Story.2016.TRUEFRENCH.720p.BluRay.x264-SOZER - nzb.su</description>
            <enclosure url="http://(removed)/getnzb?apikey=(removed)&amp;searchresultid=bda992ec82be0e94e14972df43c114540e8ab14f" length="6373057662" type="application/x-nzb"/>
            <newznab:attr name="hydraIndexerScore" value="0"/>
            <newznab:attr name="category" value="2010"/>
            <newznab:attr name="password" value="0"/>
            <newznab:attr name="hydraIndexerHost" value="https://api.nzb.su"/>
            <newznab:attr name="hydraIndexerName" value="nzb.su"/>
            <newznab:attr name="poster" value="mq@meh.com"/>
            <newznab:attr name="grabs" value="3"/>
            <newznab:attr name="comments" value="0"/>
            <newznab:attr name="imdb" value="0000000"/>
            <newznab:attr name="group" value="not available"/>
            <newznab:attr name="guid" value="bda992ec82be0e94e14972df43c114540e8ab14f"/>
            <newznab:attr name="usenetdate" value="Thu, 06 Apr 2017 09:16:35 -0400"/>
            <newznab:attr name="files" value="66"/>
            <newznab:attr name="size" value="6373057662"/>
            <newznab:attr name="category" value="2000"/>
        </item>
```
Since the imdb value is 0000000 for each object, does that mean my indexers don't support the imdbid?

**Comment by galli-leo** [comment]
@peavers  Can you confirm that doing the query via postman using imdbid=tt3748528 does not return any such results?

**Comment by peavers** [comment]
Correct. This means it's definitely an issue with Hydra? 

If that's the case, those people above that say it works for them - would love to see your config!

**Comment by peavers** [comment]
Ugh just worked it out. This was a accidental configuration change in Hydra. For anyone else that finds this, make sure in Hydra under config you've set Generate queries to both internal and external api calls. 

Sorry for wasting your time @galli-leo, but thanks for sticking it out!

**Comment by tabularasa138** [comment]
" set Generate queries to both internal and external api call"

This fixed it for me as well, thanks!

**Comment by alculete** [comment]
Solved my problem also. Thank you @peavers
