### ISSUE TITLE
[Feature request] Select specific indexer and download client in profile

### ISSUE THREAD

**Issue by pbrink231** [Radarr/Radarr#1350]
Here is the scenario.  auto looking for early releases.  usually not great quality.  a lot of the time they have hard coded subs.  I want to allow these for specific movies and keep track of them to replace with something better when they are released.

The way I see it happening
Have the options all in the profiler.  Option to allow HC or not (Or allow specific indexer or any). Option to use a specific Download Client or any which will fix the Label (Category) issue.  This will allow me to place files in a different root directory which I will remove over time.

To use I set a profile that allows these on any movie.

[AB#892](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/892)

**Comment by toddcurry** [comment]
You could accomplish the same thing by running two instances of radarr -- one for HC subs and the other for, well other.  Each will point to a different movie repository and download client.  Then when you are ready to transition, you need only to import or re-create a movie on your "other" instance and delete the original on HC Subs. 

If you are using docker, this is super, super simple to do!

**Comment by vicelversa** [comment]
Would also like to see this feature added.

**Comment by Mushin** [comment]
I would also like to see this feature added. I often start with better quality indexers enabled, then have to manually enable the lower quality indexers occasionally to do a wider search, e.g. for older movies. But I don't like to keep the low quality indexers enabled for newer releases. It would be nice to be able to select indexers within the profile.

**Comment by sataris** [comment]
I would also like to see this added, but for different reasons, I want any public indexer to use a specific download client (which is behind a VPN). 

I really don't want to maintain two seperate instances of Radarr for this as then movie management becomes difficult.
