### ISSUE TITLE
English is wanted, but found Norwegian/Danish

### ISSUE THREAD

**Issue by gilbN** [Radarr/Radarr#1352]
There should be possible to add several languages in the profile settings.  Or is there a way to get around this? Because the torrent says NORDIC or DanishBits radarr thinks the language is Norwegian or Danish but it's just the subs. 
http://imgur.com/jo2nBw6
http://imgur.com/a/CVzzX

**Radarr Version:**
0.2.0.596

**Logs:**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by ptempier** [comment]
I'd like to be able to set multiple languages in the profiles.
Typically unless usa/uk, a lot of peoples would speak english+their mother tongue.

Optionally sometime download subtitle with multiple language would be a good option.
For English movie with a lot of slang/strong accent, or for example an anime if you dont speak Japanese.

**Comment by galli-leo** [comment]
This will come to fruition in the "profilinator" update. Though we are not sure when that's going to come and how long that's going to take.

**Comment by Vildibuks** [comment]
+1 just donated to keep motivation on the subject.. will again when fixed :)
thx

**Comment by anderslo** [comment]
+1
However, the issue creator suggests two solutions - add the possibility of selecting several languages for a profile or remove the connection between the "nordic" and Norwegian and "danishbits" and Danish.

Danishbits is the release group and nordic just means that the movie has nordic subs.  So in reality the real fix for this would be that the words "nordic" and "danishbits" are not interpreted as having anything to do with the language of a movie.

In order to get movies with "nordic" in the file name, I have to set my profile to Norwegian.
However, this also means that when I search for the movie in my list of movies I have to search for the Norwegian title and that is very frustrating because I only know and refer to the English title of the movie.

One way I could think of to solve this in order to get English language movies with Nordic subtitles is to set the profile to English and also use the restriction feature (everything tagged with "some tag" must include "nordic") and this tag should be possible to connect to a profile.  But there are probably other/(better?) ways of doing this as well :)

**Comment by Kodarane** [comment]
To fix this properly, NORDIC should match Norwegian, Swedish, Danish and Finish. These are very commonly packed together as physical discs are distributed in the Nordic countries with all these subtitles.

I would also like to +1 the change to unmatch Danishbits with danish. That group usually uploads nordic releases.

**Comment by Cykle** [comment]
+1
Had to create 3x RSS profiles for each RSS category to get all releases covered.

**Comment by OoGuru** [comment]
How did you do the whole thing with RSS and what not?
I so want to switch to Radarr from Couchpotato but this language issue is the main thing holdning me back.

**Comment by OoGuru** [comment]
Adding to your comment @silentmiles, if you could disable the language matching and instead use "must contain" much like we have as a global value you could solve this and locally sort out most of the quirks.

**Comment by Cykle** [comment]
Why not just make an option to disable language check?

I know a Dane had the code rewritten (NORDIC -> NORWEGIAN) but since im on a docker on Unraid i have no idea how to implement it :(

**Comment by galli-leo** [comment]
Sure I could add an option to disable the language check but that would introduce more problems than it solves: e.g. it would just download the movie in the first language it finds (probably english) and then forget about it. You could then also start having downloads in e.g. french. So imo not really an option. I will try to write an outline I have for an idea on how to rework profiles (which would fix this) over the next few days.

**Comment by Vildibuks** [comment]
@galli-leo most danish torrent sites don't have movies in other languages then the original. (some cartoons might be the exception) so for us Danes (and other Scandinavians) disable language check would be good enough for now. :)

**Comment by Cykle** [comment]
@galli-leo Disabling the language check would as you describe surely waste bandwith and make it act ie. like RSS feeds i would guess. 
Hope you can work something out, would really like to change to Radarr from CP :)

Donation sent :)

**Comment by bendikrb** [comment]
Is it perhaps possible to atleast remove the `nordic` check?
Although tagging a release as "Norwegian"/"Danish"/"Swedish" == movie language, can perhaps be up for debate though. But "Nordic" being "Norwegian" doesn't make sense in way.

**Comment by JBCn1** [comment]
I can see this is marked at done, but I'm still having issue with it.

How did you fix it?

![image](https://user-images.githubusercontent.com/37335412/39511901-53327c7c-4def-11e8-87c4-d69aca3d0abb.png)

**Comment by galli-leo** [comment]
@bendikrb Would tagging the release as Norwegian and Danish and Swedish, be better?

**Comment by bendikrb** [comment]
@galli-leo in this case; no. Because "Nordic" in this context just means its shipped with norwegian+danish+swedish subtitles.

**Comment by galli-leo** [comment]
@bendikrb Does it mean that in every context? i.e. does it always designate subs and not dubbed languages?

**Comment by bendikrb** [comment]
@galli-leo Yes, atleast in my experience. It can mean it has nordic audio tracks aswell, but then as additional tracks (i.e. the original language is kept).
Generally speaking movies in nordic languages aren't dubbed at all -- the exception is animation films for kids (Frozen, Cars and the likes).

**Comment by JBCn1** [comment]
Looking really forward to this one! Galli-leo i'm donating when your fix this - its the only problem i have with Radarr! :)

**Comment by Grohnheit** [comment]
Great work galli-leo. Can´t wait to try this out.
Any ETA on Project Metis?

**Comment by galli-leo** [comment]
@Grohnheit It’s currently in nightly

**Comment by Grohnheit** [comment]
@galli-leo I made a custom format, multi-lang, with English, Danish and Nordic, and it works great when running tests on it. But we still need to use "Profiles" right? and when there is no "Any" option in the language selection, it will still fail with the same errors as stated in the 1. post from gilbN. Am I missing something, or just too ealy in trying this? :)

**Comment by gilbN** [comment]
I'm also currently seeing same behaviour,. Are we missing something?

**Comment by galli-leo** [comment]
@Grohnheit @gilbN Yes, there is currently no Any option, I want to add that in the future.

**Comment by Grohnheit** [comment]
Working great in latest nighly.
I am using this custom format: http://prntscr.com/ktoz8z with this profile http://prntscr.com/ktp0b2
So I could replace 3 profiles with 1.
I had to delete the "old" custom formats and create them again.

**Comment by gilbN** [comment]
Yup, looks to be working here also! :D

**Comment by fryfrog** [comment]
Omg, can this issue be closed!?!?

**Comment by galli-leo** [comment]
@fryfrog Probably not, because custom formats only provide a workaround. The ideal solution would be to have a switch that makes Nordic tag not match norwegian language.

**Comment by niXta1** [comment]
Is there any news about this issue?

**Comment by nero12** [comment]
do we have an update? i understand people work for free but i been waiting for years now :(  hope someone make a fix for this.

**Comment by fryfrog** [comment]
It'll probably be quicker for someone who strongly cares about this to learn .NET and work on the fix. ;)

**Comment by TheOnlyMunk** [comment]
![image](https://user-images.githubusercontent.com/23356406/83169284-18c16700-a113-11ea-8db4-6ea44faeb575.png)
Is this still broken? I made a custom profile that matches but the release is still rejected.
