### ISSUE TITLE
LSOpenURLsWithRole() failed with error -10810 for the file /Applications/Radarr.app

### ISSUE THREAD

**Issue by mcgae-iscteiulpt** [Radarr/Radarr#1353]
Hi, 
My Sonarr app works but the Radarr app doesn't. 
I open with the command sudo open "/Applications/Radarr.app" on Terminal and give me this error:
LSOpenURLsWithRole() failed with error -10810 for the file /Applications/Radarr.app. 
And I couldn't make the app work whatever I did (including deleting and re-installing the app with other version)
Someone can help me?
I'm working on OSX

**Comment by galli-leo** [comment]
Can you open a Terminal and do the following?:
```
cd /Applications/Radarr.app/Contents/MacOS
chmod +x Sonarr
./Sonarr
```
If Radarr starts up after that, quit the terminal and you are good to go. If not, please post the error here.

**Comment by mcgae-iscteiulpt** [comment]
Give me this error 

![captura de ecra 2017-04-11 as 10 35 47](https://cloud.githubusercontent.com/assets/26227312/24902663/c2514156-1ea2-11e7-8fca-910946dd1619.png)

**Comment by galli-leo** [comment]
Seems like the database is corrupt. Can you follow this: https://github.com/Sonarr/Sonarr/wiki/FAQ#i-use-sonarr-on-a-mac-and-it-suddenly-stopped-working-what-happened except go into ~/.config/Radarr instead of ~/.config/nzbdrone?

**Comment by mcgae-iscteiulpt** [comment]
Only the 6 and 7 steps solve me the problem.
Problem solved, Radarr is working again 👍 
Thanks :)

**Comment by lordkage** [comment]
I am guessing somewhere along the line, `Sonarr` was changes to `Radarr`?
