### ISSUE TITLE
[Feature Request] Option to disable scanning for missing files

### ISSUE THREAD

**Issue by talisto** [Radarr/Radarr#1354]
I use Radarr on a server that moves the movies to a cloud drive and then deletes them off the server after they've been downloaded.  I have "Ignore Deleted Movies" enabled so that Radarr won't keep continually downloading the same movie repeatedly when the files get moved off the local drive.  

However, the problem I'm having is that if "Ignore Deleted Movies" is enabled and a better quality version comes out after the movie has already been downloaded and moved/deleted, the better version will never be downloaded because once Radarr notices that the file is missing the movie will be marked as unmonitored.

What I'd like is the ability to completely disable the task that scans for missing files.  I'd like Radarr to just assume the files are still there even if they've been deleted, so that if an "upgraded" movie becomes available it will still be able to download the better version even if the previous version was removed.  

Is that possible?

**Comment by galli-leo** [comment]
One thing you could do before we implement something like this, is replace the movie files with a 0KB file that has the exact same name. AFAIK Radarr then should still retain the movie, but it won't take up harddrive space.

**Comment by talisto** [comment]
Thanks for the suggestion!  I've modified my post-processing script to keep empty files in place.
