### ISSUE TITLE
Don't import at all- simply send download to client and later scan for file/directory

### ISSUE THREAD

**Issue by Qdhcjv** [Radarr/Radarr#1355]
I don't need to organize my /movies directory (seeding and the like can be a challenge) so I want to leave my movies in their original file structure (`/movies/Big.Buck.Bunny.1080p.WEBDL/`) rather than Radarr copying/linking to `/movies/Big Buck Bunny/` or whatever. It seems in the current state I either let it copy or I can manually update the directory for the movie. Does anyone else want this or is it just me? Let me know if I'm being to vague.

**Comment by galli-leo** [comment]
You could disable completed download handling in Settings -> Download Clients.

**Comment by Qdhcjv** [comment]
I have done this, but still Radarr assumes the movie is in /movies/Fancy
Title (Year) and not /movies/Crappy.Title.that.it.Downloads.in.720p.WEBDL,
so it never marks the movie as downloaded. I have to manually update the
path once the download is complete.

**Comment by galli-leo** [comment]
@Qdhcjv Ah ok, gotcha. So you don't want the movie to be moved?

**Comment by Qdhcjv** [comment]
Yep exactly @galli-leo. Like the-automation-software-that-shall-not-be-named (CouchPotato), I'm fine with Radarr leaving the files in the directory dictated by the download client.

**Comment by animosity22** [comment]
If you want to make some adjustments, you can always use filebot or something like that to make some fixes.

I'm not sure why you'd want the quality listed in the directory name as things like Plex/Emby don't like that in terms of naming conventions.  I user their standard file naming/directory naming and things work quite well and it's portable if you want to change out things. I like keeping the quality as that helps it match too.

[img]http://i.imgur.com/IPFA97i.png[/img]

**Comment by animosity22** [comment]
@Qdhcjv  - assuming Windows? You can use hard links as a possible option if on Linux.

**Comment by Qdhcjv** [comment]
@animosity22 unfortunately, my current raid setup doesn't allow for hardlinks, only symbolic ones, which Radarr/sonarr do not.

**Comment by hotio** [comment]
The point of Radarr is automation and neatly organizing it, if you don't want what it does best...perhaps just use an RSS feed watcher OR let your downloader create dummy files which fool Radarr...

**Comment by galli-leo** [comment]
@Qdhcjv Would renaming to {Original Title} work for you? (That would be the scene name the download client gives us)

**Comment by Qdhcjv** [comment]
Unfortunately it looks like I can't set directory name to {Original Title},
only the file within it. Could there be an update allowing this or is there
a technical reason for that being unavailable?

**Comment by galli-leo** [comment]
@Qdhcjv Yeah, currently that's not possible (since Sonarr likes to keep the Series path constant). But we have a branch with that feature working, so I just wanted to ask you if that's a possibility.

**Comment by Qdhcjv** [comment]
Which branch? I'm willing to be on the bleeding edge. Thanks for your quick
response.

**Comment by galli-leo** [comment]
@Qdhcjv Not possible to upgrade to that atm. Also a lot of bugs and will probably break your install.

**Comment by Qdhcjv** [comment]
I'm using it in a docker container and don't care what happens. There's no
way to set it to my branch in Radarr settings?

**Comment by galli-leo** [comment]
@Qdhcjv Nope

**Comment by Qdhcjv** [comment]
Darn- I guess I'll stick to CP until this is worked out

**Comment by galli-leo** [comment]
Well Automatic folder renaming is on the latest develop release. So closing this.
