### ISSUE TITLE
Force search for "Missing, Monitored and considered Available"

### ISSUE THREAD

**Issue by mitchelp** [Radarr/Radarr#1356]
Maybe there already is a way to force this but i'm not aware how?
But i'm looking for a way to push Radarr to search for the Missing movies but that are already considered as Available.

Currently you need to filter the output for those movies, and manually open a movie page and press the "magnifying glass" to start the search. But I have 300+ missing movies but those are considered available and I would like to force Radarr to search for them.

Maybe you guys could make an option to force the search for the new movies?

Currently Radarr will pick them up if they appear in the RSS feed of the indexers correct? But not search for them actively.

Thank you for the software, it's awesome!!

**Comment by galli-leo** [comment]
You can go to the Wanted tab and then select Available & Monitored as the filter. If you then click search all, Radarr will search all movies that are monitored & missing & available.

**Comment by mitchelp** [comment]
@galli-leo you're right!! Sorry thanks for the help.
