### ISSUE TITLE
Wrong title language in folder after renaming

### ISSUE THREAD

**Issue by ErAzOr2k** [Radarr/Radarr#1357]
**Description:**
The automatic renamig function doesn't create folders in the wanted language (german in this example). The file however is named correctly.

Example:
/mnt/movies/The Hobbit An Unexpected Journey (2012)/Der Hobbit - Eine unerwartete Reise (2012).mkv

or

/mnt/movies/The Magnificent Seven (2016)/Die glorreichen Sieben (2016).mkv

**Radarr Version:**
0.2.0.596

**Comment by galli-leo** [comment]
This is fixed on the rename-folders branch.

**Comment by Seimann** [comment]
Fixed?
I have 0.2.0.654 and the Filename is every time german... Foldername english. How can i fix it??

**Comment by galli-leo** [comment]
@Seimann Either update to nightly or preferably wait until the folder renaming feature is in the latest release.

**Comment by pokemon81** [comment]
@galli-leo 
i have Version 0.2.0.870 and exact the same Problem. 
Movie Folder is englishc and the Movie inside ist german (what ist correct) the Movie folder should be even in german.

**Comment by silv3r23** [comment]
@galli-leo 
exact same problem here on v0.2.0.995.
The movie folder are always englisch after renaming, but I want there in german.
![image](https://user-images.githubusercontent.com/28316411/37460599-fd71fbf0-284b-11e8-9a12-abc2189bbc5b.png)
Radarr is able to find the correct german title, please implement this.
![image](https://user-images.githubusercontent.com/28316411/37460660-2c5510b0-284c-11e8-9197-efbda07894e5.png)

**Comment by galli-leo** [comment]
@silv3r23 You have to enable automatic folder naming

**Comment by Err0r0815** [comment]
@galli-leo this doesn´t work. even with enabled automatic folder renaming.

Movieexample: Eng: Immortals Ger: Krieg der Götter Folder: Immortal (2011)

**Comment by maxcore** [comment]
Same for me

**Comment by galli-leo** [comment]
@Err0r0815 You need to set the folders to be dynamic of existing movies.

**Comment by maxcore** [comment]
Leo what mean put folder dynamic?

**Comment by Err0r0815** [comment]
@galli-leo this 2 options will completly fuck up radarr.
at the moment i cant add any movie cause of an "Request Failed: Error: NameResolutionFailure" Error.

**Comment by galli-leo** [comment]
@maxcore When you edit a movie, you can set whether the path is static (like it is now) or dynamic (Radarr will automatically rename on every import and disk scan if enabled).

@Err0r0815 What exact issues are you having with those two options? A few people are using it without issues.

**Comment by silv3r23** [comment]
hello, this are my settings which create a "wanted-language" named folder name after a download or daily refresh movie/manual library update. thanks @galli-leo 
![image](https://user-images.githubusercontent.com/28316411/37680319-ce13d6c6-2c83-11e8-8b5c-ee1cdf04ecc5.png)

![image](https://user-images.githubusercontent.com/28316411/37680420-21b73ee4-2c84-11e8-9087-7c8811ccdfdf.png)


Version: 0.2.0.995
