### ISSUE TITLE
[Feature request] Multiple categories

### ISSUE THREAD

**Issue by Zignature** [Radarr/Radarr#1358]
I keep animation movies (for my daughter) and "normal" movies in separate root folders.
I'd like to be able to select which root folder the movie should be imported to when adding files to the download cue.
Maybe this could be automated with the use of multiple categories for download clients...

**Comment by galli-leo** [comment]
You can already select different root folders when adding the movies? Not sure what you want besides that?

**Comment by Zignature** [comment]
Forgive me my ignorance. You're absolutely right...
Didn't have enough coffee yet 😆

**Comment by Zignature** [comment]
You might as well delete this one...
