### ISSUE TITLE
Updates tab hangs when 403 returned from update server

### ISSUE THREAD

**Issue by stuntguy3000** [Radarr/Radarr#1359]
![image](https://cloud.githubusercontent.com/assets/1522389/24904703/73dbfa72-1ef0-11e7-8f7a-24f6a0e45dbb.png)

![image](https://cloud.githubusercontent.com/assets/1522389/24904718/7f27f4d0-1ef0-11e7-8761-96d8d3286acd.png)

**Comment by bchobrut** [comment]
disconnect your vpn

**Comment by stuntguy3000** [comment]
@bchobrut Not an option
