### ISSUE TITLE
Existing movies shown as missing

### ISSUE THREAD

**Issue by bigbasec** [Radarr/Radarr#136]
Using the linux version, added a few existing movies just to test things out, and they all show "Missing".  I had it download a movie just to test and that movie did update to "Downloaded".  

Logs show : 
17-1-10 23:24:11.4|Info|DiskScanService|Scanning disk for Moviename
17-1-10 23:24:11.4|Warn|ParsingService|Unable to parse movie info from path /mnt/movies2/Movies/movieFolder [1999]/movieName [1999].mp4
17-1-10 23:24:11.4|Info|DiskScanService|Completed scanning disk for Moviename
17-1-10 23:24:11.5|Error|EventAggregator|ExtraService failed while processing [MediaCoversUpdatedEvent]

[v0.2.0.61] System.NullReferenceException: Object reference not set to an instance of an object
  at NzbDrone.Core.Extras.ExtraService.Handle (NzbDrone.Core.MediaCover.MediaCoversUpdatedEvent message) <0x42009b00 + 0x00030> in <filename unknown>:0 
  at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent] (NzbDrone.Core.Messaging.Events.TEvent event) [0x000c3] in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Events\EventAggregator.cs:56 

17-1-10 23:24:11.5|Error|EventAggregator|SeriesModule failed while processing [MediaCoversUpdatedEvent]

[v0.2.0.61] System.NullReferenceException: Object reference not set to an instance of an object
  at NzbDrone.Api.Series.SeriesModule.Handle (NzbDrone.Core.MediaCover.MediaCoversUpdatedEvent message) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Api\Series\SeriesModule.cs:239 
  at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent] (NzbDrone.Core.Messaging.Events.TEvent event) [0x000c3] in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Events\EventAggregator.cs:56

**Comment by danielrw89** [comment]
I have the same issue with *some* files and the same error in the logs on the Windows build. 
Others are showing fine.

**Comment by galli-leo** [comment]
The issue is that the parser is unable to parse the movie files because of the [] in the title.

**Comment by danielrw89** [comment]
I'm seeing movies without square brackets having the issue as well. 

https://i.imgur.com/1CjHSna.png

**Comment by galli-leo** [comment]
Yea the parser here also has an issue as it at the moment needs a date in the title.

**Comment by danielrw89** [comment]
Confirmed that fixed it.. 👍

**Comment by bigbasec** [comment]
So the fix is to remove the [] characters?

**Comment by craigdabbs** [comment]
had the same error, make sure the movie has a **profile**. 

 Probably one that is set to a low quality to start with so it dont go mad and try downloading lots of new version.

**Comment by DennisH95** [comment]
i'm having this issue... 
/share/DiskX/Movies/Movie name (year)/

That's what i could find in the log, after adding the movie

17-10-3 21:05:34.2|Info|MovieService|Linking [Movie name (year).mkv] > [[tt0109254][Movie name (year)]]
17-10-3 21:05:34.2|Info|RefreshMovieService|Updating Info for 1408
17-10-3 21:05:34.5|Info|MovieService|Linking [Movie name (year).mkv] > [[tt0109254][Movie name (year)]]
17-10-3 21:05:35.0|Info|DiskScanService|Scanning disk for 1408
17-10-3 21:05:35.1|Info|DiskScanService|Completed scanning disk for 1408

Using Radarr on qnap
Radarr Version
0.2.0.696
Mono Version
4.6.2

**Comment by fbicknel** [comment]
I'm running `0.2.0.910` and even after Radarr downloaded and processed (moved) the movie, it still lists it as missing.

Is it going to try to download it again?

**Comment by galli-leo** [comment]
@fbicknel See issue #2195 It's just a sorting issue.
