### ISSUE TITLE
Incorrect Name Grabbed from Jackett

### ISSUE THREAD

**Issue by fevkalbeser** [Radarr/Radarr#1360]
When trying to search for a movie, the letter "I"(capital i) is not grabbed from Jackett, resulting in erroneous importing of the movie and failure to download. 

I am using Jackett to search from indexers such as IPTorrents and Katcr. The search from within the app itself lists correct results. However, when I use Radarr to search, the "I" (if it is at the beginning of the word) is deleted from the movie name and therefore Radarr says it does not match the wanted movie and the button to download is missing. 
![radarr3](https://cloud.githubusercontent.com/assets/26334331/24907661/cabbdacc-1ec5-11e7-8945-ad62ec6ee9fd.JPG)
As you can see, Rarbg search is correct, since it is done by Radarr itself. However the search via Jackett (both IPTorrents and Katcr) are incorrect and missing the "I" of Island. 
I actually checked to see if this was the case in Sonarr, and yes, TV shows including a word beginning with "I" are incorrectly grabbed.

Radarr Version: 0.2.0.588

Logs:
17-4-11 14:29:16.5|Info|NzbSearchService|Searching 3 indexers for [Kong: Skull Island]
17-4-11 14:29:19.2|Info|DownloadDecisionMaker|Processing 27 releases
17-4-11 14:31:29.8|Info|PreDBService|Starting PreDB Sync
17-4-11 14:31:30.2|Warn|PreDBService|Non 200 StatusCode Forbidden encountered while searching PreDB.

**Comment by galli-leo** [comment]
In that case shouldn't you open an issue with Jackett?

**Comment by fevkalbeser** [comment]
@galli-leo But Jackett lists the movie names correctly. My impression is that Radarr and Sonarr are having trouble grabbing from that list. If you strongly suggest that this is Jackett's issue, then sure I will also open an issue on its page.

**Comment by galli-leo** [comment]
@fevkalbeser I don't know. But if Radarr and Sonarr both give the same result I think Jackett's the culprit here. Additionally my Jackett displays the one Kong Island release it has correctly.
