### ISSUE TITLE
Radarr ¨Sort¨ defaults on alphabetical 

### ISSUE THREAD

**Issue by ximox69** [Radarr/Radarr#1370]
**Description:**

Radarr resets to alphabetical order (in table view): 
when I select to sort by Date Added (which is I guess the most important view to review new titles) after 2 clicks it goes to the right sort but when changing page or clicking any link it reverts to alphabetical order, would it be possible to make it remember the last setting/view used?

Thanks.

**Comment by Quiksmage** [comment]
It should remember this. I see it remembering on my side.
I have seen it reset after updates, though.

If it's not saving at all for you, there may be something deleting your cache/cookies?

Try a separate browser and see if your settings stick there.

**Comment by galli-leo** [comment]
Maybe you are using Radarr in incognito view?

**Comment by ximox69** [comment]
In Edge doesn't work, but in chrome does, annoying as I use edge only for sonarr radarr and nzbget :). many thanks . if I solve it ill leave a note
