### ISSUE TITLE
Rejected because it's larger than 0B

### ISSUE THREAD

**Issue by Firemad03** [Radarr/Radarr#1371]
Screenshot :

![image](https://cloud.githubusercontent.com/assets/24792889/24984131/a4be1fb6-1fb9-11e7-85a1-1271567b0772.png)

Build: 0.2.0.610

**Comment by Firemad03** [comment]
Here my configuration:

![image](https://cloud.githubusercontent.com/assets/24792889/24984177/de232b48-1fb9-11e7-88b2-a2aea3282b3c.png)

Everything is standard :)

**Comment by galli-leo** [comment]
Yeah, the problem here is that TMDB does not have a runtime for this movie in French, so it just sends us 0 minutes. IMO that should be handled better by TMDB, but I want to add a default runtime anyways.
