### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Firemad03** [Radarr/Radarr#1372]
I got a few errors.

> Couldn't process tracked download Boyka.Undisputed.2016.1080p.WEBRip.AAC.2.0.x264-FGT: Object reference not set to an instance of an object
> 
> System.NullReferenceException: Object reference not set to an instance of an object
>   at NzbDrone.Core.Download.CompletedDownloadService+<>c.<Import>b__9_3 (NzbDrone.Core.MediaFiles.EpisodeImport.ImportResult v) [0x0000b] in <01a01534ab254490843603b5157a1a87>:0 
>   at System.Linq.Enumerable+WhereSelectListIterator`2[TSource,TResult].MoveNext () [0x00064] in <2392cff65f724abaaed9de072f62bc4a>:0 
>   at System.Linq.Buffer`1[TElement]..ctor (System.Collections.Generic.IEnumerable`1[T] source) [0x00087] in <2392cff65f724abaaed9de072f62bc4a>:0 
>   at System.Linq.Enumerable.ToArray[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00011] in <2392cff65f724abaaed9de072f62bc4a>:0 
>   at NzbDrone.Core.Download.CompletedDownloadService.Import (NzbDrone.Core.Download.TrackedDownloads.TrackedDownload trackedDownload) [0x00102] in <01a01534ab254490843603b5157a1a87>:0 
>   at NzbDrone.Core.Download.CompletedDownloadService.Process (NzbDrone.Core.Download.TrackedDownloads.TrackedDownload trackedDownload, System.Boolean ignoreWarnings) [0x00127] in <01a01534ab254490843603b5157a1a87>:0 
>   at NzbDrone.Core.Download.TrackedDownloads.DownloadMonitoringService.ProcessClientItems (NzbDrone.Core.Download.IDownloadClient downloadClient, NzbDrone.Core.Download.DownloadClientItem downloadItem) [0x00042] in <01a01534ab254490843603b5157a1a87>:0 

This one is when I was using Trakt.tv list

> 
> Couldn't evaluate decision on Kong.Skull.Island.2017.DVDRiP.XviD-cSM.part05, with spec: DelaySpecification: Object reference not set to an instance of an object
> 
> System.NullReferenceException: Object reference not set to an instance of an object
>   at NzbDrone.Core.DecisionEngine.Specifications.RssSync.DelaySpecification.IsSatisfiedBy (NzbDrone.Core.Parser.Model.RemoteMovie subject, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) [0x00097] in <01a01534ab254490843603b5157a1a87>:0 
>   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker.EvaluateSpec (NzbDrone.Core.DecisionEngine.IDecisionEngineSpecification spec, NzbDrone.Core.Parser.Model.RemoteMovie remoteMovie, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteriaBase) [0x00000] in <01a01534ab254490843603b5157a1a87>:0 

> Couldn't evaluate decision on Kong.Skull.Island.2017.DVDRiP.XviD-cSM.part05, with spec: LanguageSpecification: Object reference not set to an instance of an object
> 
> System.NullReferenceException: Object reference not set to an instance of an object
>   at NzbDrone.Core.DecisionEngine.Specifications.LanguageSpecification.IsSatisfiedBy (NzbDrone.Core.Parser.Model.RemoteMovie subject, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) [0x00010] in <01a01534ab254490843603b5157a1a87>:0 
>   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker.EvaluateSpec (NzbDrone.Core.DecisionEngine.IDecisionEngineSpecification spec, NzbDrone.Core.Parser.Model.RemoteMovie remoteMovie, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteriaBase) [0x00000] in <01a01534ab254490843603b5157a1a87>:0 

> Couldn't evaluate decision on Kong.Skull.Island.2017.DVDRiP.XviD-cSM.part03, with spec: DelaySpecification: Object reference not set to an instance of an object
> 
> System.NullReferenceException: Object reference not set to an instance of an object
>   at NzbDrone.Core.DecisionEngine.Specifications.RssSync.DelaySpecification.IsSatisfiedBy (NzbDrone.Core.Parser.Model.RemoteMovie subject, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) [0x00097] in <01a01534ab254490843603b5157a1a87>:0 
>   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker.EvaluateSpec (NzbDrone.Core.DecisionEngine.IDecisionEngineSpecification spec, NzbDrone.Core.Parser.Model.RemoteMovie remoteMovie, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteriaBase) [0x00000] in <01a01534ab254490843603b5157a1a87>:0

> Couldn't evaluate decision on Kong.Skull.Island.2017.DVDRiP.XviD-cSM.part03, with spec: QualityAllowedByProfileSpecification: Object reference not set to an instance of an object
> 
> System.NullReferenceException: Object reference not set to an instance of an object
>   at NzbDrone.Core.DecisionEngine.Specifications.QualityAllowedByProfileSpecification.IsSatisfiedBy (NzbDrone.Core.Parser.Model.RemoteMovie subject, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteria) [0x00042] in <01a01534ab254490843603b5157a1a87>:0 
>   at NzbDrone.Core.DecisionEngine.DownloadDecisionMaker.EvaluateSpec (NzbDrone.Core.DecisionEngine.IDecisionEngineSpecification spec, NzbDrone.Core.Parser.Model.RemoteMovie remoteMovie, NzbDrone.Core.IndexerSearch.Definitions.SearchCriteriaBase searchCriteriaBase) [0x00000] in <01a01534ab254490843603b5157a1a87>:0 

I stopped because I got a lot more ;) hope it's helping to correct something :)

**Comment by Firemad03** [comment]
Build: 0.2.0.610

**Comment by Firemad03** [comment]
Ok first one I restarted Radarr and it fixed itself.

Second one for Trakt it's because the Quality Profile was missing. I was drunk or stupid and I forgot it so to correct the problem I did a mass edit to my list to add the profile manually.

I suggest that you force people to choose a list instead of leaving it blank and trow a red error to select a Quality profile or it won't add it because the field is missing.

I had a heart attack when I saw the logs with all the errors lol ;)

**Comment by geogolem** [comment]
yes - we ran into a similar issue before.... The reason we couldn't validate a profile exists directly when a user edit's or saves a list is because the user could specify a profile that exists... and then later remove that profile from the available profiles.... which would cause a similar problem despite the user actually specifying a profile initially...

I think you are right though and perhaps we need some better error handling like an assertion that a profile is set and if a profile is not set abort the list importing and spit out an appropriate message indicating that a profile is not set and should be....

**Comment by Firemad03** [comment]
Your the man of the month :) +9000 , yes you understood correctly the situation 👍 

I agree with all your ideas.

I wanted to raise a flag about this issue because it took me an hour to understand what happened :) and because the error message was really bad I didn't know what I did wrong.

**Comment by Firemad03** [comment]
[radarr1.txt](https://github.com/Radarr/Radarr/files/921210/radarr1.txt)
[radarr2.txt](https://github.com/Radarr/Radarr/files/921211/radarr2.txt)

I added the other errors that I got with my english and french radarr.

Build: 0.2.0.614

**Comment by Firemad03** [comment]
I confirm that I don't see this bug anymore :) with latest build.
