### ISSUE TITLE
Unable to connect to Radarr after changing SSL

### ISSUE THREAD

**Issue by Aesculapius** [Radarr/Radarr#1374]
Using the latest radarr version on a linux ubuntu machine, I've enabled SSL and accidentally entered the same port as on which the non-ssl was running...

Now I cannot access radarr anymore and I don't know how to revert this change. Cannot find any appropriate config files in /opt/Radarr/

Maybe the GUI should have warned (or prohibited) me that setting SSL port to the same nr as the current is not a smart idea :-)

Any idea how to resolve this?

**Comment by galli-leo** [comment]
There should be a file called config.xml either inside /opt/Radarr or ~/.config/Radarr There you can set the ssl port.

**Comment by Aesculapius** [comment]
thanks, that made it available again - although SSL still isn't working (and I can seem to find the place to set the path to my letsencrypt certificate...)

**Comment by animosity22** [comment]
It's probably better/easier to just reverse proxy it.

I just use a line like this:
```
# Radarr
ProxyPass /radarr/ http://127.0.0.1:7878/radarr/
ProxyPassReverse /radarr/ http://127.0.0.1:7878/radarr/
```

I have bunch of things so I just use an overall forms based authentication to lock down all that stuff. Since letsencrypt/certbot plugs right into apache, you can have all the renew stuff easily automated as well.

**Comment by soccermax** [comment]
Same problem here, I enabled SSL in the config file, but it's not possible to connect.

**Comment by bumperboy** [comment]
Same problem here. Different ports but I cannot connect using the SSL port.

**Comment by galli-leo** [comment]
@bumperboy Have you tried running Radarr as admin once (after the change)?

**Comment by bumperboy** [comment]
Noob here. How do you run Radarr as admin?

**Comment by galli-leo** [comment]
@bumperboy If you are running windows, right click -> run as administrator on the exe. If you are not on windows, something else is causing a problem.

**Comment by bumperboy** [comment]
Ok thanks. Going to check that later.
