### ISSUE TITLE
Can't Load Radarr in Google Chrome

### ISSUE THREAD

**Issue by theebanka** [Radarr/Radarr#1378]
Hey there I am really hoping this is a simple issue and I am just missing something silly but this is happening with both radarr and sonarr. Recently (not sure on exact date) I became unable to load either site in Google Chrome. The login page would come up but after hitting log in it will endlessly stay on the loading bubbles going from side to side. Nothing in my settings for either app has changed and I don't have any issues opening either one up in Safari on the same computer.

Like I said I hope this is a stupid mistake on my end and will gladly welcome any responses that may help fix it!

**Comment by geogolem** [comment]
have you tried clearing the cache, or running in incognito mode.. I'm using Chrome and havent had any issues with sonarr or radarr....

**Comment by theebanka** [comment]
@geogolem odd i have cleared the cache multiple times without any luck but i hadnt tried incognito mode until now and it worked perfectly.. will need to investigate further

**Comment by galli-leo** [comment]
@theebanka Try clearing cookies & local storage as well. Sometimes something can get stuck there and confuse the server.
