### ISSUE TITLE
Size tag shows 0 bytes

### ISSUE THREAD

**Issue by mooop12** [Radarr/Radarr#1379]
I'm 90% sure it was working before I updated to the latest version a few days ago.

Here's what I mean:
![screenshot_20170413_192259](https://cloud.githubusercontent.com/assets/20934112/25016261/805e217c-207f-11e7-972f-e1ecc2913450.png)

**Comment by Eventyret** [comment]
I can confirm this as well running nightly on 0.2.0.614
