### ISSUE TITLE
wrong name in error after failed import into NZBGet & broken nzbget error handling?

### ISSUE THREAD

**Issue by mgladwin** [Radarr/Radarr#138]
I use NZBGet and got this error in Radarr:-
![radarr](https://cloud.githubusercontent.com/assets/25048879/21836474/64d98c46-d815-11e6-97e9-a30bfa94c2d6.jpg)
NZBGet log shows this:-
"    Skipping duplicate xXx.2002.MULTi.1080p.BluRay.x264-MUxHD, found in history with exactly same content"
Should Radarr handle this automatically and blacklist this nzb and remove from queue?
Also should this error have Radarr or NZBGet in it (not sonarr)?

**Comment by galli-leo** [comment]
This should be fixed in the latest release.
