### ISSUE TITLE
Failed to connect to qBitTorrent

### ISSUE THREAD

**Issue by zarnexx** [Radarr/Radarr#1381]
> 17-4-14 00:23:32.7|Warn|HttpClient|HTTP Error - Res: [POST] http://localhost:8116/command/upload: 500.InternalServerError
> Error: Could not add torrent to session.
> 17-4-14 00:23:32.7|Fatal|NzbDroneErrorPipeline|Request Failed
> 
> [v0.2.0.614] NzbDrone.Core.Download.Clients.DownloadClientException: Failed to connect to qBitTorrent, check your settings. ---> NzbDrone.Common.Http.HttpException: HTTP request failed: [500:InternalServerError] [POST] at [http://localhost:8116/command/upload]
>    at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 99
>    at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxy.ProcessRequest[TResult](HttpRequestBuilder requestBuilder, QBittorrentSettings settings) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxy.cs:line 163
>    --- End of inner exception stack trace ---
>    at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxy.ProcessRequest[TResult](HttpRequestBuilder requestBuilder, QBittorrentSettings settings) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxy.cs:line 179
>    at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxy.AddTorrentFromFile(String fileName, Byte[] fileContent, QBittorrentSettings settings) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxy.cs:line 84
>    at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrent.AddFromTorrentFile(RemoteMovie remoteMovie, String hash, String filename, Byte[] fileContent) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrent.cs:line 58
>    at NzbDrone.Core.Download.TorrentClientBase`1.DownloadFromWebUrl(RemoteMovie remoteEpisode, String torrentUrl) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 269
>    at NzbDrone.Core.Download.TorrentClientBase`1.Download(RemoteMovie remoteMovie) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 125
>    at NzbDrone.Core.Download.DownloadService.DownloadReport(RemoteMovie remoteMovie) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\DownloadService.cs:line 119
>    at NzbDrone.Api.Indexers.ReleaseModule.DownloadRelease(ReleaseResource release) in C:\projects\radarr-usby1\src\NzbDrone.Api\Indexers\ReleaseModule.cs:line 73
>    at NzbDrone.Api.Indexers.ReleaseModule.<.ctor>b__8_0(Object x) in C:\projects\radarr-usby1\src\NzbDrone.Api\Indexers\ReleaseModule.cs:line 47
>    at CallSite.Target(Closure , CallSite , Func`2 , Object )
>    at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)
> 
> 17-4-14 00:28:10.3|Info|NzbSearchService|Searching 1 indexers for [Fast & Furious 6]
> 17-4-14 00:28:10.6|Info|DownloadDecisionMaker|Processing 14 releases
> 17-4-14 00:28:12.6|Warn|HttpClient|HTTP Error - Res: [POST] http://192.168.10.30:8116/command/upload: 500.InternalServerError
> Error: Could not add torrent to session.
> 17-4-14 00:28:12.6|Fatal|NzbDroneErrorPipeline|Request Failed
> 
> [v0.2.0.614] NzbDrone.Core.Download.Clients.DownloadClientException: Failed to connect to qBitTorrent, check your settings. ---> NzbDrone.Common.Http.HttpException: HTTP request failed: [500:InternalServerError] [POST] at [http://192.168.10.30:8116/command/upload]
>    at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 99
>    at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxy.ProcessRequest[TResult](HttpRequestBuilder requestBuilder, QBittorrentSettings settings) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxy.cs:line 163
>    --- End of inner exception stack trace ---
>    at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxy.ProcessRequest[TResult](HttpRequestBuilder requestBuilder, QBittorrentSettings settings) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxy.cs:line 179
>    at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrentProxy.AddTorrentFromFile(String fileName, Byte[] fileContent, QBittorrentSettings settings) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrentProxy.cs:line 84
>    at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrent.AddFromTorrentFile(RemoteMovie remoteMovie, String hash, String filename, Byte[] fileContent) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrent.cs:line 58
>    at NzbDrone.Core.Download.TorrentClientBase`1.DownloadFromWebUrl(RemoteMovie remoteEpisode, String torrentUrl) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 269
>    at NzbDrone.Core.Download.TorrentClientBase`1.Download(RemoteMovie remoteMovie) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 125
>    at NzbDrone.Core.Download.DownloadService.DownloadReport(RemoteMovie remoteMovie) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\DownloadService.cs:line 119
>    at NzbDrone.Api.Indexers.ReleaseModule.DownloadRelease(ReleaseResource release) in C:\projects\radarr-usby1\src\NzbDrone.Api\Indexers\ReleaseModule.cs:line 73
>    at NzbDrone.Api.Indexers.ReleaseModule.<.ctor>b__8_0(Object x) in C:\projects\radarr-usby1\src\NzbDrone.Api\Indexers\ReleaseModule.cs:line 47
>    at CallSite.Target(Closure , CallSite , Func`2 , Object )
>    at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)
> 

Connection is successful when testing.
running version 0.2.0.614 on Windows Server 2016

**Comment by galli-leo** [comment]
What version of qBittorrent are you using?

**Comment by zarnexx** [comment]
was running 3.3.10, updated to 3.3.12 too see if it helped.

**Comment by Quiksmage** [comment]
I'll jump in a little.

I haven't had any issues with Qbittorrent on Radarr thus far.

I am running Qbittorrent 3.3.7 64bit on Windows Server 2012

I should probably update to the newest 3.3.12, but if you have time to check if 3.3.7 is working for you, this might shed more light on what the problem is.

If the torrent client already has the torrent it's trying to add, it does return an error to the requester. Can you check that it wasn't already added? (I assume it wasn't, just throwing it out there.)

**Comment by Quiksmage** [comment]
I just tested updating my existing install to 3.3.12 and was successfully able to grab a torrent using radarr.

**Comment by zarnexx** [comment]
Thanks for your answers.
I tried to downgrade to 3.3.7...did not help.
Also tried to delete and re-add 'download client'
I took some screenshots to better explain the problem.
1, 
![2017-04-15 23_09_02- radarr](https://cloud.githubusercontent.com/assets/26191930/25066787/0f05f410-2231-11e7-8aef-e36ab710589f.png)
1.
![2017-04-15 23_13_29-settings - radarr](https://cloud.githubusercontent.com/assets/26191930/25066796/46882f0c-2231-11e7-86da-c52f839216dd.png)

**Comment by zarnexx** [comment]
OK, it look like downloading is working but not for my chosen profile (?)...in my profile I want 1080p/bluray and first picture shows radarr did not reject it but is unable to download.

Below I´m able to download 720P version
![2017-04-15 23_29_11- radarr](https://cloud.githubusercontent.com/assets/26191930/25066890/76d18f12-2233-11e7-92a8-1d66e6239e53.png)
....

OK, just tried to download another movie and it worked fine....so don´t know whats wrong...
mods can probably close this issue(?)

**Comment by zarnexx** [comment]
This issue can be closed.
Is was as @Quiksmage said, I previously downloaded the torrent(s) without radarr, after searching one more I found the torrents in qBittorrent. 

Feature request: Maybe a message IF a torrent already is in torrent client?

But anyways....sorry for the mistake!
