### ISSUE TITLE
Pb search with torrent9.biz 

### ISSUE THREAD

**Issue by thebest28** [Radarr/Radarr#1383]
Hello,
I search french movie with jackett  and torrent9 indexer but Torrent9.biz name the movie title with the wrong year of the movie.(this is the year where the torrent was create :( and this is for all the title movie)
Ex for  Fantastic Beasts ,it find:
Les Animaux fantastiques FRENCH BluRay 720p 2017
Radarr found  nothing because it search with 2016.
Is it possible to have a option under Radarr  to modify the year or not put  the year to the search ?
or there  is an another solution?
Thank you for  your  help.

**Comment by galli-leo** [comment]
2016 is the correct year according to imdb. I would tell your indexer to correct their mistakes. Nothing much we can do :/
