### ISSUE TITLE
Original title fetch

### ISSUE THREAD

**Issue by Jorman** [Radarr/Radarr#1384]
Hi, I just installed Radarr on my qnap, is very very beautifull, I love the sonarr style!!!

Btw I've only a little request, is also possible to search the original title on imdb?

I mean, when I add a movie, for example Incarnate
both imdb and The MovieDB have the original title and the title in my country (italy)
Incarnate: Non potrai nasconderti

So, the information is reported in english even if on The MovieDB is italian, but this's not the "real" problem.

The actual problem is that the research on various indexer is with the original title, not with the title in my country that is
Incarnate: Non potrai nasconderti

And no release was found :)

So, maybe I do something wrong.

Any idea about that?

**Comment by jOOc** [comment]
Maybe vote on this
http://feathub.com/Radarr/Radarr/+140

**Comment by Jorman** [comment]
Hi, tnx for the info, I'll!

Maybe my idea is wrong, but on Radarr I can set a language for my profile, that in this case is italian, so on adding phase Radarr can check the title, like it does actually on The MovieDB, also on imdb. If in both case the "local" title is available Radarr take the default one, if only one of 2 have the "local" title Radarr take the one that is present, and if both don't have any "local" title Radarr take the original one.

Btw, I edited the title on The MovieDB, I added the italian title and the I refresh Radarr, but the title is still the original one.

Any idea?

**Comment by galli-leo** [comment]
@Jorman I think it takes a few hours for TMDB info to be updated and available on the api. If you set the language of the profile, Radarr will already automatically try to pull the italian title & description. So in that case, am I correct that this solves your issue?

**Comment by Jorman** [comment]
This solve the issue only because I edited the title on TMDB. But better than nothing.

IMHO I think that can be a good function check also the title on imdb and catch it if missing from TMDB, but maybe is only mine this idea.

What do you think?

**Comment by galli-leo** [comment]
@Jorman No chance for that since the only provider of a free imdb api just closed down :/ However, Radarr does search with up to 5 additional titles as well now, so gonna close this issue.

**Comment by Jorman** [comment]
Hi @galli-leo sorry for the late reply!

So is not possible to take the title "only parsing" the page data? I think you prefer the API so you can do that in a quicker way.

**Comment by galli-leo** [comment]
@Jorman Its not that it would be quicker, but more thta the imdb page layout can change anytime rendering the parsing corrupt. It would also prolly double or triple the time it takes for the movie to be refreshed.
