### ISSUE TITLE
Sample file ended up in final folder

### ISSUE THREAD

**Issue by ochompsky** [Radarr/Radarr#1385]
Downloaded a movie and the folder contained a 6gb mp4 and a sample 30mb mp4.  Only the sample file ended up in the final folder.

**Comment by geogolem** [comment]
this has happened to me before -- couldnt figure out why.. but there is definitely an issue where this happens.. It hasnt happened to me recently but if/when it does Iwill try to collect more info regarding the specific situation. If you could provide any more info about the movie and release etc and your environment that might be helpful.

**Comment by galli-leo** [comment]
@ochompsky What is the runtime shown in the radarr ui? How long is the runtime of the sample file?

**Comment by some-guy-23** [comment]
I'm having this same issue occur. In my case, the problem seems to be that the sample file's metadata (incorrectly) shows the full movie runtime.

**Comment by galli-leo** [comment]
@some-guy-23 We maybe should do something like that, though not sure why a sample would report a false runtime. Seems kinda dumb to me.

**Comment by some-guy-23** [comment]
@galli-leo yeah, seems to be an issue with how they encoded the sample or something? Not sure, but it has happened a couple of times.
