### ISSUE TITLE
Folder names always created in english, file name gets changed to selected language

### ISSUE THREAD

**Issue by wdghub** [Radarr/Radarr#1386]
**Description:**

When you add a not yet existing movie to the library, Radarr always creates the movie Folder with the original movie title. The movie itself - when downloaded - gets renamed correctly in the selected language. Radarr should use the same title (english, german, French, whatever) for the Folder Name too, if the rename Option is enabled.

Example:
I have a root Folder for all movies starting with "K". Now i add "Kampf der Titanen (2010) to the library and select the root Folder ...movies\K". But Radarr crates the Folder "...movies\K\Clash of Titans (2010).

**Radarr Version:**
0.2.0.596

**Comment by galli-leo** [comment]
This is fixed on a seperate branch and has actually to do with some underlying structural things from Sonarr, namely that Movie (Series) folders aren't changed unless the user does so manually.
