### ISSUE TITLE
Discover movies

### ISSUE THREAD

**Issue by woble** [Radarr/Radarr#139]
Have a way of discovering new movies, based on your current library and just a general by genre and/or year (appears to be possible via TMDB API). Perhaps adding a new button next to Calendar, or in case recommended movies a new tab in the movie page with recommended/similar movies.

**Comment by donldmn** [comment]
Something similar to this thread? https://github.com/Radarr/Radarr/issues/114

**Comment by woble** [comment]
Isn't #114 about supporting more sources rather than having an actual interface to discover new movies?

**Comment by simonk83** [comment]
Agreed, this is very handy in CP.  I often add movies from the "movies in theatres" and "suggestions" lists.

**Comment by fedoranimus** [comment]
This is a feature I want as well; it will require significant UI enhancement and back-end work. I'm looking into various methods of recommendation and data aggregation.

**Comment by Mirabis** [comment]
When considering this request,would it be possible to add a few extra otions?

Only download current (or X configurable) years movies. This helps when you use a watchlist to automate downloading but don't want it to backfill movies from 2014 still on your list.

**moved**

**Comment by markhaines** [comment]
Would be great if Radarr could replicate the Couch feature to regularly poll a user's public IMDB movie watchlist and automatically add these movies to the 'wanted' list.

As well as being an easy way to add new movies it also acts as a sort of backup. If I were to lose all my movies due to disk failure I can just reinstall Radarr, point it at IMDB and it can go and hunt them down again.

**moved**

**Comment by blackley** [comment]
User sets up a specific list called "Radarr" - if found Radarr imports the list to internal wanted list and removes the listed movies from the "Radarr" trakt list.

**Comment by woble** [comment]
Just want to add that this feature request has nothing to do with lists. This is more related to the TMDB discover page where one could browse new and upcoming movies and add them manually.

**Comment by onedr0p** [comment]
With the new lists for tmdb does this cover it? I use the tmdb discover api to get movies.

**Comment by galli-leo** [comment]
#1450 This should help a lot. Also with the db on our server, we can add metadata to all lists, which should allow us to display additional info for all lists.
