### ISSUE TITLE
Old Movies Before the Availability Feature have NULL Availabilty

### ISSUE THREAD

**Issue by ajslater** [Radarr/Radarr#1391]
Movies that existed in the Radarr database before the recent (magnificent, excellent, wonderful) availability feature have a null availability setting. These should be updated to the default availability setting, so `PreDB` in most cases.

I haven't looked at the schema, but something along the rough lines of:

`UPDATE movie SET availability = 'PreDB' WHERE availability IS NULL;`

Should probably be run once on the update Radarr install script.

Version 0.2.0.596
Mono Version 4.8.0 (Stable 4.8.0.524/9d74414 Thu Apr 6 19:26:41 BST 2017)

**Comment by galli-leo** [comment]
IIRC Physical/Web is automatically used if availability is NULL. Will have to check tomorrow though.

**Comment by ajslater** [comment]
Its good to hear that you have a crawler backup/default value 😃 . But It'd be nice to constrain NOT NULL in the  schema after setting it to the default value, if only for a less confusing UI.
