### ISSUE TITLE
Can't find movies moved into another search path

### ISSUE THREAD

**Issue by ajslater** [Radarr/Radarr#1393]
Enhancement.

If a movie is missing from its file path. Search the "recent folders" or other known library search paths to see if it was moved there before declaring it missing.

This would support all kinds of organizational workflows including inboxes for new movies.

Version 0.2.0.596
Mono Version 4.8.0 (Stable 4.8.0.524/9d74414 Thu Apr 6 19:26:41 BST 2017)

**Comment by Quiksmage** [comment]
+1 one thing i loved about couchpotato was that i never had to change the filepaths if i moved movies around since it checked specific folders for movies on every  library update (usually once per 24 hours).

**Comment by eyeofmaat** [comment]
+1
just found this out after moving a bunch of stuff around. Would love it if I didn't have to update the location of every movie that was moved

**Comment by ltjdym** [comment]
+1

**Comment by ltjdym** [comment]
+1

**Comment by bobby-tables-2048** [comment]
+1

**Comment by smathev** [comment]
+1 :)

I love Radarr and consider it the best and prime way of searching for new releases, however - as I'm not a fan of RAID, and prefer JBOD'ing my storage - so I have multiple movie folders, and also they are sorted after whether I want to keep it or if it's a "temp-download" IE. a movie I just want to watch and delete. 

In short, this feature is sorely missed and critical for a really perfect Radarr installation for me.

BUT! I wanted to say, I love the software - it works perfect in terms of acquiring new releases, etc. and I want to thank all developers for the hard work they are doing - and if I in anyway can help implement this feature I would love to help! :)

**Comment by smathev** [comment]
Any news on this or anything that I/we can do that would speed the implementation along? :)
