### ISSUE TITLE
Movies in deluge queue doesn't show up in activity/queue

### ISSUE THREAD

**Issue by jOOc** [Radarr/Radarr#1394]
**Description:**

When adding a movie it gets added to the queue in Deluge but Radarr does not add it to the activity/queue. Therefore Radarr task searches for the movie multiple times and multiple movies gets added to Deluge

As seen in the screenshot below I have a lot of movies/tv-series in my queue. Sonarr does have all tv-series waiting to be downloaded its queue but not Radarr.

![image](https://cloud.githubusercontent.com/assets/9382342/25066709/87e950aa-222e-11e7-846a-b70d4ef84a82.png)

**Radarr Version:**

Radarr Ver. 0.2.0.626 - nightly

**Logs:**

**Comment by galli-leo** [comment]
@jOOc Pretty sure I just fixed this :)

**Comment by jOOc** [comment]
@galli-leo yeah now when I woke up and radarr had updated it worked :+1: 
Thank you!

**Comment by a5m0** [comment]
I am seeing this on 0.2.0.654 - Apr 18 2017  develop.
