### ISSUE TITLE
Radarr going crazy and deleting movies and downloading again all over...

### ISSUE THREAD

**Issue by Giantdouche33** [Radarr/Radarr#1395]
Radarr has started to download releases and delete old ones all over the place. its kinda going crazy.

Its gotten so bad I've had to kill radarr and leave it off

Version
0.2.0.535
Mono Version
4.8.0 (Stable 4.8.0.495/e4a3cf3 Wed Feb 22 18:30:58 UTC 2017)
[radarr.txt](https://github.com/Radarr/Radarr/files/923944/radarr.txt)

**Comment by Firemad03** [comment]
See #1390  and #555

**Comment by galli-leo** [comment]
Radarr does not delete movies unless it imports a better quality. Are you sure Radarr is doing the deleting? Also you are running a pretty outdated version (current one is .596) can you update?

**Comment by galli-leo** [comment]
As I see in the logs, Radarr is correctly deleting the movie before upgrading it, so that the old file can be replaced by a better quality.

**Comment by Giantdouche33** [comment]
definately radarr doing it...
RecycleBinProvider	Recycling Bin has not been configured, deleting permanently. /home/giantdouche/media/movies/Catfight (2017)/Catfight (2016) Bluray-720p.mkv

I've updated to .596


But it is upgrading EVERY film.... to the exact same quality. Its deleted 20+ films now.

**Comment by Firemad03** [comment]
@galli-leo I think it's related to the #555 because before you did the fix the English version didn't had this problem and after the title fix now both my english and french got this problem but he is right about Radarr redownloading for the same quality. I never checked it out about that in my french version but right now it's crazy so I stopped too both my radarr.

**Comment by Firemad03** [comment]
@galli-leo I had 50 jobs in my sabnzbd about the same movies that radarr already downloaded and he was trying again every time that the task is starting. I have no choice but to stop radarr completely.

I didn't have this bug before the title fix except in my french version (I confirmed it I didn't see it before because I never thought to check it out.)

**Comment by Giantdouche33** [comment]
I've updated to the latest nightly. and its still deleting. It cant be just upgrading as its doing it to my entirely library. I've set my entirely library to not monitored yet it still deleted. Shouldn't attempt to upgrade if its not monitored should it?

17-4-16 00:43:14.0|Info|MovieService|Linking [Boyka Undisputed IV (2016) WEBDL-1080p.mkv] > [[tt3344680][Boyka: Undisputed IV]]
17-4-16 00:43:14.1|Info|MovieService|Linking [Boyka Undisputed IV (2016) WEBDL-1080p.mkv] > [[tt3344680][Boyka: Undisputed IV]]
17-4-16 00:44:30.4|Info|MovieService|Linking [The Crash (2017) HDTV-720p.mkv] > [[tt3297382][The Crash]]
17-4-16 00:44:30.4|Info|MovieService|Linking [The Crash (2017) HDTV-720p.mkv] > [[tt3297382][The Crash]]
17-4-16 00:44:33.0|Info|RecycleBinProvider|Recycling Bin has not been configured, deleting permanently. /home/giantdouche/media/movies/Burning Sands (2017)/Burning Sands (2017) DVD.mkv

**Comment by galli-leo** [comment]
@Giantdouche33 Interestingly did it delete those files and add it back again? As it seems to do that from the logs?

@Firemad03 The only problem is he is on .596 which does not have the problems from #1390. 
So radarr also deleted those files for you.

**Comment by galli-leo** [comment]
@Giantdouche33 Try enabling the recycling bin.

**Comment by galli-leo** [comment]
@Giantdouche33 Also can you enable trace logging? It's going to be difficult to trace it without that, since I cannot reproduce it.

**Comment by Giantdouche33** [comment]
how do i enable trace logging please?

**Comment by galli-leo** [comment]
Settings -> General -> Logging

**Comment by Firemad03** [comment]
@galli-leo Your right it was deleting fine the file just for some reasons it was going crazy to redownload again. I see that you corrected the #1390 with the latest build. I'll upgrade maybe it will fix my problem.

**Comment by Giantdouche33** [comment]
ok after enabling recycling bin its stopped removing films all the time however now getting the following error...

Message
Couldn't process release.: SQL logic error or missing database
near "WHERE": syntax error

Exception
System.Data.SQLite.SQLiteException (0x80004005): SQL logic error or missing database
near "WHERE": syntax error
  at System.Data.SQLite.SQLite3.Prepare (System.Data.SQLite.SQLiteConnection cnn, System.String strSql, System.Data.SQLite.SQLiteStatement previous, System.UInt32 timeoutMS, System.String& strRemain) [0x0033c] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
  at System.Data.SQLite.SQLiteCommand.BuildNextCommand () [0x00068] in <61a20cde294d4a3eb43b9d9f6284613b>:0 

[radarr.trace.txt](https://github.com/Radarr/Radarr/files/923975/radarr.trace.txt)

**Comment by galli-leo** [comment]
@Giantdouche33 There should be a new update up in a few minutes fixing that issue.

**Comment by Firemad03** [comment]
@galli-leo latest patch corrected my problems btw.

**Comment by Giantdouche33** [comment]
fixed. thankyou :)
