### ISSUE TITLE
Added Password and can't log in now 

### ISSUE THREAD

**Issue by rickjames334** [Radarr/Radarr#1397]
**Description:**
Added a simple password and now I can't log in or figure out how to reset it. Can't seem to find the config file on linux. Also the failed login attempts don't seem to be hitting my log 

**Radarr Version:**
Linux/Latest

**Comment by animosity22** [comment]
It's in the home directory of your user that it is running as:

~/.config/Radarr

You can shut it down and fix the config.xml and start it back up to change the auth method:
```
  <AuthenticationMethod>None</AuthenticationMethod>
```

**Comment by galli-leo** [comment]
Alternatively it might be in /opt/Radarr. Check out the wiki entry for the AppData directory.

**Comment by bkuri** [comment]
Changing `AuthenticationMethod` to `None` doesn't seem to change anything as of `v0.2.0.1344`. Is there any other way to reset login details?
