### ISSUE TITLE
Star Wars: The Last Jedi (2017) is being marked as "Released"

### ISSUE THREAD

**Issue by xoniq** [Radarr/Radarr#1400]
Quite impossible.

**Comment by hotio** [comment]
Are you sure?

**Comment by galli-leo** [comment]
Just added it myself and it marks it correctly as announced. Can you try updating the movie info?

**Comment by xoniq** [comment]
It's on the search section where it is marked as released:

![](https://drive.qinox.nl/public-share/c9fHAlThtAKZgE0/preview?path=/&mode=thumbnail&size=medium)

**Comment by hotio** [comment]
![jedi](https://cloud.githubusercontent.com/assets/26902309/25074427/97531d6a-22fa-11e7-8f81-4a9fc1d9ba50.png)

Only on your setup

**Comment by xoniq** [comment]
I just found out there was an update available which fixed this. I guess the install guide for Linux does not show the latest version available; so I ended up with a version of march.

I was not that sharp on it; this can be closed.
