### ISSUE TITLE
High use of RAM

### ISSUE THREAD

**Issue by juanchristian** [Radarr/Radarr#1401]
I noticed that Raddar consumes a whole lot of RAM, compared to other usenet tools.

![image](https://cloud.githubusercontent.com/assets/4141392/25074230/de973dce-22cc-11e7-9e9f-81f8e4aa9157.png)

![image](https://cloud.githubusercontent.com/assets/4141392/25074233/f5b88daa-22cc-11e7-8a24-cc3164d086e9.png)

![image](https://cloud.githubusercontent.com/assets/4141392/25074235/fcf0c902-22cc-11e7-9eac-acca2dd1b5fb.png)

![image](https://cloud.githubusercontent.com/assets/4141392/25074236/0307acd4-22cd-11e7-95c9-1eae050a4aaa.png)

When I took those SS I didn't have any downloads/scans in action.

**Radarr Version:** 0.2.0.596
**Mono Version:** 4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4)

**Logs:**

- https://gist.github.com/jcchristian/1195eed4ff641f8090f665a4859cfdb0
- https://gist.github.com/jcchristian/bafbbd568e33b7d66591a597f8f04404

**Comment by galli-leo** [comment]
How many movies do you have? How many movies do you have added in your queue?

**Comment by jcchristian** [comment]
@galli-leo 

Total Record: 24
Wanted Missing: 5
Wanted Cutoff Unmet: 3

**Comment by galli-leo** [comment]
Yeah probably because of all the errors in the log. Exceptions can take up quite a bit of memory. If you want to get rid of those I suggest updating to the nightly.

**Comment by jcchristian** [comment]
Yeah, I saw those errors, but I didn't set to download/search for any of the movies listed there.

**Comment by galli-leo** [comment]
@jcchristian Radarr will try to match them nonetheless. Another option is to clear out your downloaders history.

**Comment by jcchristian** [comment]
I'll clean NZBGet history and see if that fix

**Comment by jcchristian** [comment]
I believe that deleting them solved the issue:

![image](https://cloud.githubusercontent.com/assets/4141392/25074404/4d58317a-22d0-11e7-9167-2f8766dd5a0a.png)

**Comment by jcchristian** [comment]
Not really, it's back again, the same annoying `17-4-16 19:06:15.6|Error|DownloadMonitoringService|Couldn't process tracked download Automoto.26-03-2017.h264.1080p.TNTRip.mp4`

RAM Use:
![image](https://cloud.githubusercontent.com/assets/4141392/25254709/55ff25ba-25fd-11e7-8e6c-18c28f8dbb64.png)

**Comment by LSL1337** [comment]
not sure about the others, but my radarr docker uses 700-900MB RAM, i have around 200 movies added, half of it monitored (not sure why does it have to do anything with RAM usage)
is this normal?
i use the linuxserver IO docker btw

**Comment by juanchristian** [comment]
Quite some time passed since I opened this ticket. I ended up reinstalling radarr and now it seems OK. I have 21 monitored, where 20 are downloaded and 1 is pending. RAM usage is 150-170MB, CPU usage is 0.2%

**Comment by galli-leo** [comment]
@juanchristian @LSL1337 There’s another issue open for this where we found out it’s most likely due to a large logs db, that gets mapped into ram by the os. If you encounter higher usage again, please try deleting the logs db.

**Comment by juanchristian** [comment]
@galli-leo Good to know, I erased all my logs just to be safe, thanks :)

**Comment by juanchristian** [comment]
So, after I did that it went downhill. Now my CPU is always 8%+ and RAM is 500MB. WTF!?

linux.io container

Version
0.2.0.980
Mono Version
5.8.0.127 (tarball Wed Feb 21 16:43:57 UTC 2018)

**Comment by juanchristian** [comment]
Didn't do anything, but it's back to normal, so I'm closing this.

151MB RAM and 0.2% CPU
