### ISSUE TITLE
Can't Manually Import Movies

### ISSUE THREAD

**Issue by kushfest** [Radarr/Radarr#1405]
**Description:**
I used bulk import to add the folder on the external drive that holds all my movies. It appears everything was added, but many of the movies are labeled Wanted because the mp4 files on the drive weren't associate with the movies (yes, everything is in its own folder). I'm trying to use the Manual Import function on the Wanted tab to clean things up, but when I try to manually import films  the import fails every time . Initially I could only import single films at a time and would only get the error when I tried to important multiple films, but now I get it every time.

Any suggestions? Also, is there a better way to do this? It's going to take me forever to manually select the mp4 files for all of the movies that are currently listed as Wanted, but are already in my collection.

**System:**
Radarr 0.2.0.596
Ubuntu 16.04
Mono 4.8.1

**Logs:**
CommandExecutor	Error occurred while executing task ManualImport: Value can not be null. Parameter name: profile	8:29am
ArgumentValidator	Value can not be null.	8:29am

**Comment by se7ensinsman** [comment]
Hi,
I have the same issue but I don’t understand how you fixed it. CAN you explain to me ? Thank you !

**Comment by kushfest** [comment]
Admittedly, I'm failing to totally remember how I solved this. I believe I bulk updated the profile for my films by using Movie Editor on the main page of Radarr. Just select the films you want to update and use the popups at the bottom of the page to make bulk changes. I believe this helped fix the error, but I still had to do a fair amount of manual importing. Let me know if that helps.
