### ISSUE TITLE
Filter by text on homepage

### ISSUE THREAD

**Issue by Aesculapius** [Radarr/Radarr#1406]
When I'm trying to look at my current collection with the means of completing it, there doesn't seem to be an intuitive way of showing what's in my collection. I cannot group on genre, type, language, running time, whatever... nor can I just show the results of my search query. I have to select on of the items from the dropdown menu directly.

For example star wars; looking at completing that, but I cannot say if things are complete because of the total lack of overview:

![image](https://cloud.githubusercontent.com/assets/617061/25095637/c959c276-239c-11e7-8f46-600df92806e9.png)

Now, showing the posters along each other would help at least because they would show me which episode which movie is. Unless I'm missing something, I don't seem to be able to get to such screen...

**Comment by fryfrog** [comment]
Can you not just scroll down in the list or poster view to Star Wars?

**Comment by Aesculapius** [comment]
that list contains over 1000 movies and lacks ways to sort or filter... that makes it quite a hassle...

**Comment by galli-leo** [comment]
There should be sort & filter options on the top of the page.

**Comment by Aesculapius** [comment]
Correct, but no filter by text string....maybe that is what I'm looking for as feature request then :-)
