### ISSUE TITLE
[Feature] Allow torrents with key words to be selected

### ISSUE THREAD

**Issue by stuntguy3000** [Radarr/Radarr#1408]
Just a suggestion, i would love for a way to make it so that any torrents that contain a key word (e.g. the 4 letter acronym of a certain movie provider) to be auto selected over anything else.

**Comment by fryfrog** [comment]
Make it a preferred word on the quality profile you want. And for the love of god, I hope that 4 letter word isn't YIFY. :/

**Comment by galli-leo** [comment]
Yup this can be done with preferred words / tags.

**Comment by stuntguy3000** [comment]
I must of missed that. Cheers @galli-leo 

@fryfrog :)

**Comment by stuntguy3000** [comment]
Hi @galli-leo 

I don't think this works as expected. I've included **SITENAME** as one of the preferred tags but Radarr is still picking other torrents and missing the ones with **SITENAME** in them.

What am I doing wrong?
Cheers.

**Comment by galli-leo** [comment]
Movies with better quality will still be selected over movies with preferred words. E.g. a movie in remux quality without preferred words is better in the eyes of radarr than a web-dl with your preferred words. Also a lot of times movies with preferred words only come out after releases with them. Radarr first downloads the one without which could cause problems.

You can set words to be required in Settings -> indexers -> restrictions, but then Radarr will only download releases with those tags.

**Comment by stuntguy3000** [comment]
Hmm,

Is it possible to change the prioritization of tags over qualities?

**Comment by galli-leo** [comment]
@stuntguy3000 Currently No.
