### ISSUE TITLE
No movies load at localhost

### ISSUE THREAD

**Issue by pikachukaki** [Radarr/Radarr#1412]
After the latest update when i open the app from my shortcut it loads at http://localhost:7878 but i can't see any of my monitored movies and when i press the update DB key it stuck there for ever.
I saw that you can load the app thru 127.0.0.1 and there all my movies are showed correctly.
Whats the problem and how can i change the app to open at 127 and not at localhost?

> 17-4-18 22:43:59.4|Warn|StaticResourceModule|Couldn't find handler for /movies/images/ui-bg_highlight-soft_75_cccccc_1x100.png
17-4-18 22:43:59.6|Warn|StaticResourceModule|Couldn't find handler for /movies/images/ui-bg_flat_75_ffffff_40x100.png
17-4-18 22:44:15.2|Warn|StaticResourceModule|Couldn't find handler for /images/ui-bg_flat_75_ffffff_40x100.png
17-4-18 22:44:15.2|Warn|StaticResourceModule|Couldn't find handler for /images/ui-bg_highlight-soft_75_cccccc_1x100.png
17-4-18 22:44:26.6|Info|MovieService|Adding Movie [][Bond] Path: [D:\Movies\Bond (2009)]
17-4-18 22:44:26.6|Info|MediaCoverService|Downloading Poster for [][Bond] http://image.tmdb.org/t/p/original/pC4ZAZiMl5qcyB90vmTv98o51SU.jpg
17-4-18 22:44:26.6|Info|RefreshMovieService|Updating Info for Bond
17-4-18 22:44:27.9|Warn|PreDBService|Non 200 StatusCode Forbidden encountered while searching PreDB.
17-4-18 22:44:27.9|Info|DiskScanService|Scanning disk for Bond
17-4-18 22:44:27.9|Info|MovieScannedHandler|[Bond] was recently added, performing post-add actions
17-4-18 22:44:28.1|Info|MediaCoverService|Downloading Banner for [tt2783968][Bond] http://image.tmdb.org/t/p/original
17-4-18 22:44:28.5|Warn|HttpClient|Failed to get response from: http://image.tmdb.org/t/p/original The remote server returned an error: (404) Not Found.
17-4-18 22:44:28.5|Warn|MediaCoverService|Couldn't download media cover for [tt2783968][Bond], likely the cover doesn't exist for this movie. The remote server returned an error: (404) Not Found.
[v0.2.0.596] System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at System.Net.WebClient.DownloadFile(String address, String fileName)
   at NzbDrone.Common.Http.HttpClient.DownloadFile(String url, String fileName) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 174
   at NzbDrone.Core.MediaCover.MediaCoverService.DownloadCover(Movie series, MediaCover cover) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaCover\MediaCoverService.cs:line 175
   at NzbDrone.Core.MediaCover.MediaCoverService.EnsureCovers(Movie movie, Int32 retried) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaCover\MediaCoverService.cs:line 128>

**Comment by fryfrog** [comment]
Try in an incognito window.
