### ISSUE TITLE
Add Fan Edit as an edition

### ISSUE THREAD

**Issue by fryfrog** [Radarr/Radarr#1414]
There are a *lot* of crappy movies that have been made better via fan edits. It'd be nice to be able to label them, a bit like the Despecialized versions of the Star Wars movies.

An example is `A9 Prometheus.1080p.Special Edition.FanEdit.BRRip.x264.AAC-m2g` but I'm sure there are more.

**Comment by galli-leo** [comment]
I wouldn't call Prometheus crappy 😛 But yea that seems like a good addition to the editions.

**Comment by galli-leo** [comment]
Better edition regex: `^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*\(?(?<edition>(((Extended.|Ultimate.)?(Director.?s|Collector.?s|Theatrical|Ultimate|Final|Extended|Rogue|Special|Despecialized).(Cut|Edition|Version)|Extended|Uncensored|Remastered|Unrated|Uncut|IMAX)))\)?.(?<year>(19|20)\d{2}(?!p|i|\d+|\]|\W\d+)))+(\W+|_|$)(?!\\)`

**Comment by galli-leo** [comment]
Even better edition regex: `^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*\(?(?<edition>(((Extended.|Ultimate.)?(Director.?s|Collector.?s|Theatrical|Ultimate|Final|Extended|Rogue|Special|Despecialized).(Cut|Edition|Version).(Extended|Uncensored|Remastered|Unrated|Uncut|IMAX|FanEdit)?)))\)?.(?<year>(19|20)\d{2}(?!p|i|\d+|\]|\W\d+)))+(\W+|_|$)(?!\\)`

**Comment by galli-leo** [comment]
Link to test regex: https://regex101.com/r/CC2KVX/1
@fryfrog Can you try breaking the above regex?

**Comment by hotio** [comment]
I broke it, sorta:
`X-Men.Apocalypse.2016.UltraHD.BluRay.2160p.HEVC.BT2020.DTS-HD.MA.7.1`

also sometime you get releases with `-scrambled-obfuscated` or `-scrambled` at the end, the don't get the correct group.

**Comment by galli-leo** [comment]
@hotio That one's fine, since it will get captured by another regex. That regex is just for editions.

**Comment by galli-leo** [comment]
e.g. `X-Men.Apocalypse.Ultimate.Edition.2016.UltraHD.BluRay.2160p.HEVC.BT2020.DTS-HD.MA.7.1` Will get matched perfectly fine

**Comment by fryfrog** [comment]
I couldn't break it :)

**Comment by jOOc** [comment]
What about these editions?
Anniversary
Restored

**Comment by galli-leo** [comment]
@jOOc Anniversary needs a bit more work, since those usually come with a number.

**Comment by distinguished-git** [comment]
You should add OAR and Open Matte, as well.
