### ISSUE TITLE
Trakt.tv UserWatchList gets imported with root path "C:\Windows\System32"

### ISSUE THREAD

**Issue by xandian** [Radarr/Radarr#1415]
**Description:**

I've noticed that when the net importer is used for my Trakt.tv UserWatchList, the root path gets set to "C:\Windows\System32", which is not the root path that is set on this import item in Settings -> Lists.

I have other Trakt lists set up to import as well, but these work fine and as expected.

Workaround which worked for me was to create a new list with the exact same parameters, which solved the problem.

I figured I add it as an issue here anyway, in case it occurs for somebody else.

**Radarr Version:**
0.2.0.654

**Logs:**

**Comment by galli-leo** [comment]
Yeah this can happen if you forget to choose a path when setting up a list. There's already an issue open that we should do more validation, which we definitely should do.

**Comment by galli-leo** [comment]
This may also occur if you delete the root path you added the list with.

**Comment by xandian** [comment]
Thank you.
The open issue for this problem, which one is that? I cannot find it.

I have updated the [wiki page Common Problems](https://github.com/Radarr/Radarr/wiki/Common-Problems) with this problem.
I hope this is okay? I edited the wiki page directly. Maybe you prefer that a new branch is created and then create a pull request for the changes on the page?

**Comment by galli-leo** [comment]
@xandian Yep sure that's totally fine. Thank you :). Regarding the issue atm I also cannot find it, especially, since I am on a phone. I will try to locate it, but it was in the direction of better list validation.

**Comment by nibble4bits** [comment]
I'm having this same issue, and I'm trying the workaround from the Wiki and paying special attention to make sure I set the path on the creation of the list. The path is NOT saving and it's blank after I create it.
