### ISSUE TITLE
Wrong Year Still?

### ISSUE THREAD

**Issue by animosity22** [Radarr/Radarr#1417]
**Description:**
I thought this was an issue related to a NZB, but I'm not sure now. I keep seeing Split 2017 match the 2016 version and it grabs the NZB. I can't tell if that's a DogNZB issue or something in Radarr.

**Radarr Version:**
0.2.0.654 - Apr 18 2017  develop Installed
**Logs:**
Logs are attached.

Screenshot looks like:
http://i.imgur.com/Tet1Hr7.png
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/934723/radarr.debug.txt)

**Comment by galli-leo** [comment]
Probably because it was actually released in 2016 http://www.imdb.com/title/tt4972582/?ref_=nv_sr_1. Have you looked at the movie file to see if it is the correct version? If not, we cannot really do much, since we don't know which Split the movie is by just looking at the name. That should be your indexer who does that.

**Comment by animosity22** [comment]
Except when you add it into Radarr, it shows 2017.

Here is the other image. I pasted the wrong one.

http://i.imgur.com/Kq5CxP7.png

**Comment by animosity22** [comment]
Both Split versions:

http://i.imgur.com/3zfY5FX.png

**Comment by animosity22** [comment]
I'm guessing it because you are pulling from TMDB which has 2017 listed while IMDB has 2016.

**Comment by galli-leo** [comment]
@animosity22 Yeah the search view displays the year TMDB returns not the year we afterwards actually use (the earliest we get). If you e.g. search for split afterwards on your homepage, you will se the correct year appear in brackets.

**Comment by animosity22** [comment]
I just fixed the TMDB release date. Works fine now as it's putting the right year in the movie and matching right.
