### ISSUE TITLE
Add Release Qualities for Movies

### ISSUE THREAD

**Issue by vortexrap** [Radarr/Radarr#142]
Currently, Radarr has some movie qualities (1080p WEB-DL, Blu-Ray, etc.) but are missing some early release qualities such as CAM, Screener, TS, TC, etc.

There is a Wikipedia link on the interwebs you can check to see the naming convention and quality types.

Also, it would be great to see options of of audio bit-rate qualities as well.

**Comment by woble** [comment]
Wiki in question: https://en.wikipedia.org/wiki/Pirated_movie_release_types
