### ISSUE TITLE
List import loses path

### ISSUE THREAD

**Issue by astlaurent** [Radarr/Radarr#1420]
**Description:**
I have set the path several times in my list imports (stevenlu, and trakt anticipated) and it seems that at some point it loses the path, when i go into these lists the path section is blank and when i look at a movie that the lists brought in it has a default windows path which is not correct. see screenshot
![2017-04-19 18_10_43-96 souls - radarr](https://cloud.githubusercontent.com/assets/11797070/25204557/043c8884-252c-11e7-888e-891470955913.png)
![2017-04-19 18_14_34-settings - radarr](https://cloud.githubusercontent.com/assets/11797070/25204567/134dd77e-252c-11e7-8b50-8d070363336b.png)

**Radarr Version:**
0.2.0.660
**Logs:**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by galli-leo** [comment]
This can happen if you delete that root folder path. We already have an issue open for better validation and I agree that this shouldn't happen. Though the UI is also a bit bugged, in that it will try to display the last selected root folder for lists.

**Comment by astlaurent** [comment]
@galli-leo I think there is more of an issue then. I have not deleted the root folder, I have tons of movies going into the root folder that I manually added. Something else must be happening to cause the path field to disappear, maybe certain updates?

**Comment by xandian** [comment]
@astlaurent Try creating a new list where you select the path before clicking on Save. I had a similar problem the other day and creating a new list solved the problem. It is still an issue, but at least you can work around it.

**Comment by galli-leo** [comment]
@astlaurent Can you try what @xandian suggested and report back?

**Comment by 4getit** [comment]
I had the same issue a few times and had to update the DB manually afterwards. I think it happens when you edit an existing list and then hit save again.
Now, I try to always click the directory again before clicking save and this seems prevent it from happening.

**Comment by staraxis** [comment]
I have a similar issue and can't seem to find it elsewhere. I have 2 lists setup with different paths. One should have a folder as A:\Kids Movies the other should have a folder B:\Movies (not real paths). The issues is that whenever I change the folder for one list the other automatically changes as well. I can't seem to have unique folder paths setup. If I change one the other changes and vice versa in a never ending loop.

**Comment by junestu** [comment]
I have the same issue as staraxis. 
Two TMDB list of the same type (Theaters) the difference being one excludes genre ids 10751,16 while the other includes them.  Unable to set different folders due to the issue described by staraxis above.

**Comment by galli-leo** [comment]
@staraxis @junestu This is just a visual glitch. If you change the path on one list and click save the path is correct. The dialog just shows the wrong path.

**Comment by werkkrew** [comment]
In my case the path does not visually disappear and it always appears correct, but anything added from certain lists gets downloaded into a different path regardless of how I set it.  In the docker image this seems to default to /opt/radarr/ instead of /movies/

**Comment by dcplaya** [comment]
I have the same issue for lists as well as movies that have been added via Ombi. I am running it in a Docker too (didnt have the issue running outside Docker)

**Comment by cswelin** [comment]
👍  Having the same issue as @werkkrew

**Comment by flease** [comment]
I'm having a similar issue. Radarr attempts to move movies added from the Trakt watchlist to root "/" after download rather than the expected /path/to/movies/movie (2017). This move fails as radarr doesn't have permissions. 

If I inspect the path in the movie interface it is "/". If I change this to the correct path, moving the movie succeeds. 

When inspecting nzbdrone.db/Netimport the RootFolderPath is correctly specified as /path/to/movies/.

**Comment by hang10z** [comment]
I am also having this issue.   When I try and create a list and click save the path disappears.  Movies are downloaded to the correct location via nzbget, however the path to the movie is in media management is \

**Comment by galli-leo** [comment]
@hang10z Yeah. This is fixed on the latest nightly / does not happen in safari or edge.

**Comment by andycarver101** [comment]
Me too. I can’t even find the setting to set paths amymore.  It’s defaulting to the download client preference.
