### ISSUE TITLE
Radarr sorts items into pages of 10

### ISSUE THREAD

**Issue by theebanka** [Radarr/Radarr#1421]
This may have always been a thing in which case think of this more as a request and less like a bug. 

Currently Radarr no matter the sort view only shows pages of 10 items instead even in poster view instead of having a scrolling list. This is not how Sonarr handles these sorting views so I wasnt sure if this was an intended feature or a bug but personally it seems to detract from the experience (at least for me)

**Comment by delphiactual** [comment]
`Settings` -> `UI` -> `Page Size`

**Comment by galli-leo** [comment]
^

**Comment by theebanka** [comment]
@galli-leo Thanks for pointing that out as its not a setting I remember seeing when I set this up... that being said I have it set to 1000 but am still getting pages of 10 (also 10 isnt even an option) so i think there is still a bug here...

**Comment by galli-leo** [comment]
@theebanka Can you try setting it to 500 and then saving? Also can you try clearing your browser data?

**Comment by theebanka** [comment]
@galli-leo Swapping it to 500 saving then swapping it back to 1000 worked like a charm! thanks
