### ISSUE TITLE
Movies that don't get selected automatically wont import

### ISSUE THREAD

**Issue by SuperGaco** [Radarr/Radarr#1422]
Radarr Ver. 0.2.0.660

After I select the Movie it still highlighted in red. And it says import complete right away (without it actually importing) I don't find this problem with movies that get automatically imported.
I would include my logs, but getting this forever.
![image](https://cloud.githubusercontent.com/assets/25994857/25244030/1b704f76-25cd-11e7-9010-9e3f07b503d6.png)

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by galli-leo** [comment]
@SuperGaco Regarding the logs. This is probably your adblocker blocking the page from loading. You can also access them via the AppData directory, see wiki for where that's located.
Does this still occur on the latest develop release?
