### ISSUE TITLE
Manually adding torrents to queue fail [POST] /api/release: 500.InternalServerError

### ISSUE THREAD

**Issue by spuniun** [Radarr/Radarr#1423]
Radarr version (exact version): 0.2.0.596
Mono version: 4.8.1 (Stable 4.8.1.0/22a39d7 Wed Apr 12 12:00:40 UTC 2017)
OS: Ubuntu 14.04.5 LTS
Debug logs: https://hastebin.com/uducurizut.rb
Description of issue: 
Recently I've noticed that when trying to add a torrent to download queue manually from search page it fails. When radarr is adding torrents from the same provider (I only have one) via automatic search it works fine.

**Comment by Quiksmage** [comment]
Which torrent client are you using?
Which provider are you using?

**Comment by galli-leo** [comment]
From the logs it seems like a timeout error on your end? Are you perhaps doing this from outside your local network?

**Comment by spuniun** [comment]
I am using rtorrent (remote) and PTP as the provider.
I would agree that this is a network issue accept that the timeout is internal to the /api/release call which should be on http://localhost:8080/api/release - at least this is how the logs show any other internal API call, and automatic search torrent snatches also work fine. With some suggestion by @fryfrog I added PTP as a torznab jacket search provider and those manual snatches work fine as well.
If the manual add to queue button is trying to POST to the api via public network connection (e.g. https://1.2.3.4/api/release) that clearly would not work cause Radarr is in a subdirectory of the reverse proxy and would need to include the URL Base value.
Since I'm having the same issue in Sonarr I expect it has to be some issue with the way that manual download is POSTing to the API (shared codebase and all). I have debug logging enabled now in both so I can get a same of logs from when auto-searching successfully adds a torrent to the seedbox to compare to when these manual ones fail.

**Comment by galli-leo** [comment]
Oh yeah. We are definitely using the public api in our ui. Since these calls are made from your browser that proly means it goes through 1.2.3.4/api. As for the url base, you can set that in the General Settings. Can you try that and report back?

**Comment by spuniun** [comment]
The URL base is already set.
I access all my tools thru a single https reverse proxy e.g. https://sub.domain.tld/radarr
It is configured thus in settings. Everything works fine excepting this manual add to download queue, but it is new behavior. It used to work fine in both Sonarr & Radarr. I only noticed this happening about a week ago, two at most.

**Comment by spuniun** [comment]
So after collecting my debug logs all night to prove that it was working on automatic searches (which it still is), then retesting the manual add it was suddenly working again in both Sonarr and Radarr... dunno wtf
