### ISSUE TITLE
After finish movie handle

### ISSUE THREAD

**Issue by pikachukaki** [Radarr/Radarr#1425]
I config radarr to download movies to my D drive in a folder called movies nothing to fancy
utorrent starting to download movies to download folder after finishing download the movie copied to d:movies but they still exist to download folder too how can i fix this?

**Comment by galli-leo** [comment]
The movie is not actually copied. It's just a hardlink, meaning it won't take up more space. We have to do this since we don't want to remove the movie from your torrent client so that you can still seed your torrents.
