### ISSUE TITLE
Imported movies without year in title show as missing

### ISSUE THREAD

**Issue by CrispinP** [Radarr/Radarr#1426]
**Description:**

- I've switched from CP to Radarr
- Loads of imported movies without year in title
- Profile in Radarr says "{Movie Title} ({Release Year})" as is my want
- After updating library Radar finds the movie and metadata but shows file as missing.
- If I update the folder name to include the year and rescan it shows it as valid.

Desired:

- The folder name is missing the year but it recognises that the folder is a movie. It should then also look inside the folder for a movie.
- Allow an automated way of renaming or correcting folders to match the profile.

Check first that your problem is not listed in our wiki section:
* https://github.com/Radarr/Radarr/wiki/Common-Problems
* https://github.com/Radarr/Radarr/wiki/FAQ

Provide a description of the feature request or bug here, the more details the better. 
Please also try to include the following if you are reporting a bug

**Radarr Version:**
0.2.0.654 - Apr 18 2017

**Logs:**
Failed:
![image](https://cloud.githubusercontent.com/assets/27884877/25303148/be66372c-2744-11e7-95fd-0ba712073519.png)

After renaming:
![image](https://cloud.githubusercontent.com/assets/27884877/25303151/e33ab32a-2744-11e7-96d8-038594641421.png)

Apologies if this is a duplicate.

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by galli-leo** [comment]
Yeah we should update the code to add movie files without a year regardless. Nevertheless, it's always a good idea to name your movie files with name and year. A program such as filebot would make it very easy for you to rename them quickly and include the correct. Also an issue for this is already open, though I cannot currently link it, since I am on mobile.

**Comment by CrispinP** [comment]
thanks for the tip. I'll try update them all.

Good work on the app!
