### ISSUE TITLE
Add "{ORGINAL}" to folder nameing scheme

### ISSUE THREAD

**Issue by jkaberg** [Radarr/Radarr#1427]
I'd like to see an option where Radarr uses the release name (eg. Torrent/Usenet name) as folder name when creating folders.

Cocuhpotato example:

Deluge
![image](https://cloud.githubusercontent.com/assets/613363/25303390/5acbac20-2752-11e7-82db-9fca6ba09b26.png)

Couchpotato
![image](https://cloud.githubusercontent.com/assets/613363/25303381/1488d4d6-2752-11e7-85ab-566c4278f394.png)

Result
![image](https://cloud.githubusercontent.com/assets/613363/25303398/83bcd7bc-2752-11e7-9e89-8ce624af799b.png)
The last picture might be confusing but is actully correct as the .mkv file (in the torrent) was named differently

**Comment by galli-leo** [comment]
This is already working on a seperate branch and should find its way into the nightlies over the next few days. However, I would recommend using this instead: "{Movie.Title.}{.Year.}{.Edition.Tags.}{.Quality.Full.}{.MediaInfo.Simple}{-ReleaseGroup}". This way you can make sure the folder contains all info needed and is representative of Scene Standards. It will also show you whether the movie is for example a Director's cut.

**Comment by jkaberg** [comment]
Thanks @galli-leo, diden't know! Awesome work 😄
