### ISSUE TITLE
Unable to connect to indexer

### ISSUE THREAD

**Issue by kniffs** [Radarr/Radarr#143]
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 322

Radarr Ver. 0.2.0.61

Message : Unable to connect to indexer: Sequence contains no elements

I am using Torznab as Indexer in Radarr to be able to add a custom Tracker that does not have official support.

The chain from there is Radarr -> Jackett -> Torrentleech

I've tried category 2000 which is "movies".

I would like to add that i've used the exact same settings, API, Indexer settings as i do in Sonarr which works.

**Comment by onedr0p** [comment]
Use torrentpotato indexer instead, report back if you're still having problems.
