### ISSUE TITLE
File named/marked incorrectly on manual import.

### ISSUE THREAD

**Issue by helofrends** [Radarr/Radarr#1433]
When importing a 1080p bluray, the file is incorrectly named with 720p quality at the end of the file name. Media info says 1080p; however, radarr operates as if this is still a 720p file (cutoff not met if set to 1080p or bluray).  Organize will not work to fix the filename unless the 720p component is deleted after which organize then correctly renames and labels the file.

Check first that your problem is not listed in our wiki section:
* https://github.com/Radarr/Radarr/wiki/Common-Problems
* https://github.com/Radarr/Radarr/wiki/FAQ

Provide a description of the feature request or bug here, the more details the better. 
Please also try to include the following if you are reporting a bug

**Radarr Version:**

**Logs:**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by helofrends** [comment]
-1- The first part of the issue is that it seems to always label manually imported files as 720p regardless.

-2- Second issue is that it will not "organize" the file name once a quality label, whether false or not, is in the file name.  Basically, if the file name has all the requested attributes, organize will believe it is correct and not provide the option to organize the name properly.

**Comment by galli-leo** [comment]
Can you provide a way for me to test the file? Or can you post the complete media info output? Also, what's the full filename? We run mediainfo on importing and correct the quality label. So not sure how that can happen. But yes, once a file is imported into your Radarr library we wont constantly scan it again to verify it has changed.

**Comment by helofrends** [comment]
Thanks for the response.  It is only when manually importing a file that doesn't already have detailed in the filename.  For example, if I use makemkv to produce a file and then manually import the file (which has no labels on it), it will always default the file name to 720p even though media info correctly says 1080p.  Radarr will still see the file as not meeting the 1080p cutoff.  I'll see if I can get a screenshot later today to show you what I mean.  Thanks again!

**Comment by helofrends** [comment]
<img width="897" alt="capture after changing name of file only" src="https://user-images.githubusercontent.com/27927714/26942747-1493638c-4c38-11e7-9131-495cd07ab424.PNG">
<img width="920" alt="capture" src="https://user-images.githubusercontent.com/27927714/26942748-1493d40c-4c38-11e7-86ab-9e0f62b1e236.PNG">

Hopefully these uploaded correctly.  Post makemkv conversion of iso or bdmv to mkv, the media info is correct; however, radarr automatically names and labels the files as 720p.  This also still leaves these as still wanted due to not meeting cutoff.

**Comment by galli-leo** [comment]
Do you have analyse media files enabled under Settings -> Media management?

**Comment by helofrends** [comment]
Yes

**Comment by galli-leo** [comment]
@helofrends Can you post some logs of Radarr importing the file?
