### ISSUE TITLE
In Movie Editor, 'tick all' not working

### ISSUE THREAD

**Issue by dzg** [Radarr/Radarr#1434]
If I tick the 'select all' box, only the first item gets selected.

**Radarr Version:** 0.2.0.654

**Comment by D34DC3N73R** [comment]
Does this happen for you with a cleared browser cache? Your browser probably has an old js file cached which is causing the issue.

**Comment by raspdealer** [comment]
but still, selecting only the first page...

**Comment by D34DC3N73R** [comment]
I think a more consistent approach would be to add a 'movies per page' setting similar to the bulk import movies page. The multi-select button ultimately has more control if it's set to select visible results, and the number of results is able to be specified.

**Comment by galli-leo** [comment]
@D34DC3N73R You control the page size of the movie editor by the page size set in Settings -> UI. I don't think we want to select all items on all pages. That would only confuse users.

**Comment by galli-leo** [comment]
@dzg Can you verify that you still experience the issue (even in incognito mode)?

**Comment by D34DC3N73R** [comment]
@galli-leo Awesome I didn't know setting existed. Over the last couple of versions my results page has been swinging from 10-1000. I'm assuming the separate setting in the bulk importer is for ease of use? I can see the benefit considering it's most used by new users with new installations that may not have seen the settings yet.

**Comment by galli-leo** [comment]
@D34DC3N73R Yeah exactly. Also Bulk import you probably want to be low, since it takes a lot of time for even a small amount of movies. However, if you have a good connection, page size can be relatively high.

**Comment by mrbipbip** [comment]
This issue seems to be the same as #1522
