### ISSUE TITLE
Modify movie files not working in movie screen

### ISSUE THREAD

**Issue by ProphetSe7en** [Radarr/Radarr#1435]
When I press the "modify movie files" button nothing happes.

Running v0.2.0.654

**Comment by Pitchshift** [comment]
I am having the same issue. 

Running v0.2.0.995

**Comment by Qstick** [comment]
I think all that really needs to be done here is to remove the button. We allow these edits to be done down below in the files tab (quality change and delete) thus this button is really not needed. @galli-leo would you agree?

**Comment by galli-leo** [comment]
Agreed

**Comment by Qstick** [comment]
Fixed in https://github.com/Radarr/Radarr/commit/a2fa8c459449192f2c0e91d9d55be0cfacee2bce.
