### ISSUE TITLE
Movies incorrectly showing up as CUTOFF UNMET 

### ISSUE THREAD

**Issue by powertowerpro** [Radarr/Radarr#1436]
**Description:**
Wanted -> Cutoff Unmet shows movies where the cutoff is actually already met

**See unmet movies here:**
![image](https://cloud.githubusercontent.com/assets/5577598/25322564/068b25de-286d-11e7-84e2-5d7d4549b114.png)

**See Profile for select movie here (NOTE: HD-1080p):**
![image](https://cloud.githubusercontent.com/assets/5577598/25322576/114e9fdc-286d-11e7-8306-22ddd33a3cd6.png)

**See Profle Setting here:**
![image](https://cloud.githubusercontent.com/assets/5577598/25322595/34ae54f4-286d-11e7-9654-f2c82bfd28ec.png)

None of these movies should be showing up here.

**Radarr Version:**
Version
0.2.0.660

**Comment by galli-leo** [comment]
Qualities are ordered from bottom to top
Currently HTDV is considered better than Bluray in your settings
So naturally Radarr thinks these are cutoff unmet.
