### ISSUE TITLE
Movies are recognized but set to 'Missing'

### ISSUE THREAD

**Issue by remkovdz** [Radarr/Radarr#1437]
Hi, I just installed Radarr (was already using Sonarr) and I imported my existing movies. This went great at first: Radarr recognized every movie I had and listed them in 'Movies'. 

The problem: although Radarr recognized all Movies, it also set some of them to 'Missing'. This is strange behavior of course, since they ARE on in the correct folder etc., which is why Radarr put them in the 'Movies' list in the first place.

I'm not a developer so I can't bring anything other than to bring up the issue.

Hopefully this can be fixed. Thanks.

**Comment by galli-leo** [comment]
Sonarr doesn't handle movies, only Radarr does. Did you mix up the names in your post? If yes what is the naming of those movies Radarr does not recognize?

**Comment by remkovdz** [comment]
Oops, I mixed up the names, I meant Radarr!

Examples are Birdman and American Sniper.

**Comment by fryfrog** [comment]
Check the path for the movie. You may have it as "American Sniper" and Radarr is expecting "American Sniper (1928)".

Also, check permissions. Radarr has to be able to read the dirs and files.

And really, provide more details.

What OS are you on? What version of Radarr? What is your setup?

**Comment by galli-leo** [comment]
@remkovdz Also for now your movie files need the year in them, so you have to name them American Sniper 2016.mkv

**Comment by remkovdz** [comment]
Thanks!

The folder has the year in it: **Birdman (2014)**. However the filename did not: **birdman.wmv**, I renamed it to **birdman 2014.wmv** and rescanned everything under System > Tasks but that doesn't help. To be honest I'm not sure if this is the problem: I have several files in in the movie map without years in the file name and Radarr managed to process them well.

I now always include years, but didn't in the past.

Some more details:
- NAS is Synology
- Working with Radarr and NZBget, works great
- I don't use postprocessing in NZBget, I don't think it's needed?
- Permissions are ok
Version: 0.2.0.654
Mono Version: 4.6.2 (Stable 4.6.2.7/08fd525 Wed Jan 11 16:08:56 CET 2017)

Thanks again.

**Comment by galli-leo** [comment]
@remkovdz Can you go into System -> Tasks and run the houskeeper task? Also if that does not fix it. Can you try to remove ad readd the movie?

**Comment by remkovdz** [comment]
Thanks, running Housekeeper does not work.
Removing and adding the movie will definitely work (already tried it with other movies) but I figured that's not the way it should be?

In other words: I'll live with this issue (can fix it by removing/adding) but it looks like a bug?

**Comment by fryfrog** [comment]
I see this same issue occasionally on movies and remove/re-add is the only thing that has fixed it. Haven't had any luck figuring out the actual problem. :/

**Comment by galli-leo** [comment]
@fryfrog @remkovdz Yeah I have also been able to find the issue on my local dev environment. It should not happen. No idea why it does. I have a few things that could circumvent that, but no real solution yet :/

**Comment by galli-leo** [comment]
But this issue was already raised here #657, So I am going to close this as a duplicate.
