### ISSUE TITLE
Multi-part movies not deleted

### ISSUE THREAD

**Issue by yuljk** [Radarr/Radarr#1438]
**Running the latest version of Radarr as a Windows service - I have imported my existing movies. When updating a standard definition movie which is in two parts only one part is deleted.:**

Multi-part movie - only one file is deleted after updating to a better quality release.  This means I need to manually delete the file, remove the movie from my library and add back in.

Much appreciated

**0.2.0.654:**

**Comment by yuljk** [comment]
Example multi-part movies in my library.

Aliens.CD1
Aliens.CD2

Only one file will be deleted after downloading a higher quality release of the movie.

If the movie is a single file Radarr deletes it without issue and replaces with a newer quality release.

Hope that helps!

**Comment by fryfrog** [comment]
FWIW, I think it also fails to move multipart downloads if you accidentally download one :/

**Comment by galli-leo** [comment]
@yuljk Yeah we don't handle multipart movies yet. Flagging this as a duplicate since there's already an issue open for handling duplicate movies at #145
