### ISSUE TITLE
Can't reverse proxy into radarr using caddyserver - Bad Request

### ISSUE THREAD

**Issue by julestop** [Radarr/Radarr#144]
Getting following message:

Bad Request - Invalid Hostname

HTTP Error 400. The request hostname is invalid.

**Comment by onedr0p** [comment]
Are you sure this isn't a problem with your configuration? I have a reverse proxy working just fine with nginx.

**Comment by galli-leo** [comment]
Try running it as an administrator or copy the files to the Program Files folder and run it from their.

**Comment by mgladwin** [comment]
also running fine for me using nginx

**Comment by julestop** [comment]
OK, I moved it to program files and it still didn't work... but then I ran serviceinstall.exe and after that it fired right up... Sorry, I'm not well seasoned in reverse proxy, but it works now :D

**Comment by galli-leo** [comment]
No problem. It isn't actually a reverse proxy problem. Windows doesn't allow other devices to connect to an application not running as admin.

**Comment by chansearrington** [comment]
I actually had the same problem and resolved it by running Radarr as administrator. Just a note. I didn't have to do this with Sonarr. Or at least, I have no memory of having to do it. It just worked.

**Comment by iambdud** [comment]
Any chance we can re-open this? I'm experiencing the same. I have Radarr setup identically to how I setup Sonarr. I have no issues accessing Sonarr, but get the "bad request" for Radarr. The issue goes away if I launch Radarr as admin. However, I don't have to do that same thing with Sonarr... so I'm not sure what the difference is.

**Comment by galli-leo** [comment]
@iambdud You would have to had to do that with Sonarr, unless you where extremely lucky somehow. Before Windows allows us to bind to any address (meaning to let other devices connect to Radarr) we need admin access. Nothing we can do here.

**Comment by iambdud** [comment]
Mine is working now... It seems that after I ran it once as administrator (after i moved it to ProgramData), subsequent launches can be non-elevated and I can access it from other machines without issues...

Maybe this is what I was supposed to do, but the instructions said to "extract anywhere, run as admin once, then copy to programdata".

Anyway, it's working. Thank you.
