### ISSUE TITLE
Movies with ä,ö,ü which are not used as german umlauts cannot be parsed.

### ISSUE THREAD

**Issue by jooncheez** [Radarr/Radarr#1441]
![image](https://cloud.githubusercontent.com/assets/10760947/25401813/12cd4314-29f7-11e7-9d3a-0775743a30b8.png)

This release is rejected because of "Unknown movie. Movie found does not match wanted movie.". However, title seems to be the same. Only thing I can see is that the accents are missing.

**Comment by bakerboy448** [comment]
foreign language support is improved in v3

if this is still an issue please open a new issue and fill out the template
