### ISSUE TITLE
Add Base URL to Deluge Settings

### ISSUE THREAD

**Issue by entropydo** [Radarr/Radarr#1442]
**Description:**

Check first that your problem is not listed in our wiki section:
* https://github.com/Radarr/Radarr/wiki/Common-Problems
* https://github.com/Radarr/Radarr/wiki/FAQ

Under host, I am trying to add the base folder for deluge to connect via SSL. It states that "must be valid Host without http://"

My set up:
Host: domain.tld/deluge
Port: 443
Password: PW
Use SSL: Yes

The set up works perfectly without SSL enabled and the correct web port WITHOUT base folder.
Current working set up:
Host: domain.tld
Port: 1234
Password: PW
Use SSL: No

**Radarr Version: 0.2.0.654**

**Logs:**
HTTP request failed: [403:Forbidden] [POST] at [https://domain.tld:443/json]: HTTP request failed: [403:Forbidden] [POST] at [https://domain.tld:443/json]

The request fails because missing base folder for reverse SSL proxy.

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by ngeraedts** [comment]
This issue occurs when attempting to add a Sabnzbd download client as well.

**Comment by RyanEwen** [comment]
This is an issue with NZBGet as well, which lacks the advanced "Url Base" option present in Sonarr.

I can't connect to my NZBGet instance which is behind NGINX :(
