### ISSUE TITLE
Radarr downloading episodes.

### ISSUE THREAD

**Issue by Davst** [Radarr/Radarr#1444]
Was greeted to an episode of The Flash, s03e19 or something. 

Image reference: http://puu.sh/vwYfO/ba5668c147.jpg

Version
0.2.0.654

**Logs:**

```


17-4-26 09:32:58.4|Warn|DownloadedMovieImportService|Unable to process folder that is mapped to an existing show
17-4-26 09:33:28.5|Warn|DownloadedMovieImportService|Unable to process folder that is mapped to an existing show
17-4-26 09:33:58.7|Warn|DownloadedMovieImportService|Unable to process folder that is mapped to an existing show
17-4-26 09:34:28.6|Info|RssSyncService|Starting RSS Sync
17-4-26 09:34:28.7|Warn|DownloadedMovieImportService|Unable to process folder that is mapped to an existing show
17-4-26 09:34:29.2|Info|DownloadDecisionMaker|Processing 100 releases
17-4-26 09:34:29.3|Info|AcceptableSizeSpecification|[tt0439572][The Flash (2018)] has no runtime information using median movie runtime of 110 minutes.
17-4-26 09:34:40.8|Info|DownloadService|Report sent to Deluge. The Flash 2014 S03E19 1080p HDTV x264-CRAVERS
17-4-26 09:34:40.9|Info|RssSyncService|RSS Sync Completed. Reports found: 100, Reports grabbed: 1
17-4-26 09:34:58.8|Warn|DownloadedMovieImportService|Unable to process folder that is mapped to an existing show
17-4-26 09:35:28.8|Warn|DownloadedMovieImportService|Unable to process folder that is mapped to an existing show
17-4-26 09:35:58.8|Warn|DownloadedMovieImportService|Unable to process folder that is mapped to an existing show
17-4-26 09:36:28.9|Warn|DownloadedMovieImportService|Unable to process folder that is mapped to an existing show
17-4-26 09:36:58.9|Warn|DownloadedMovieImportService|Unable to process folder that is mapped to an existing show
17-4-26 09:37:28.9|Warn|DownloadedMovieImportService|Unable to process folder that is mapped to an existing show
```

**Comment by galli-leo** [comment]
It is extremely likely that your indexer mistakenly tagged that release with the imdbid of the movie you are monitoring. We have had that in the past and it should try to only add if the year matches too. What I suspect is that because it's an episode we couldn't parse the year and therefore matched it anyways. I will try to repro it though if I have time.

**Comment by Davst** [comment]
Probably. I'm thinking that it would likely be safe to check a node for what parts of Sonarr that might be left in Radarr which derives that it might be an episode. (or just vs the pattern of eXX sXXeXX or similar) which would indicate that it is an epsidode, unless the unlikely event that there was a movie named Movie s21e19 or such.

**Comment by galli-leo** [comment]
Yeah just checked the imdbid your indexer gave was for the Flashpoint 2020 movie. Anyways, while we could check for episode / season naming pattern, imo not worth the effort since this is so rare.
