### ISSUE TITLE
file name from 4k remaster won't process

### ISSUE THREAD

**Issue by Quiksmage** [Radarr/Radarr#1446]
Example file name: Bad.Boys.II.2003.4K.BluRay.Remux.1080p.AVC.DTS-HD.MA.5.1-BMF

4k remaster encodes/remuxes tend to be named such as this. I can get around the problem by manually importing from within radarr.

**Comment by galli-leo** [comment]
Interesting. So is this a 1080p or 4K release? Never seen this before.

**Comment by Quiksmage** [comment]
1080p release off of a 4k remaster.

**Comment by Quiksmage** [comment]
it would be good to add this as an edition tag if this hasn't been already.

**Comment by Qstick** [comment]
We seem to parse this correctly in v3
