### ISSUE TITLE
Email alert

### ISSUE THREAD

**Issue by eyeofmaat** [Radarr/Radarr#1449]
For a feature request, sending an email when a movie is downloaded would be good.

For example, when adding newly announced movie, this can stay there for large periods of time (years or months)
When it eventually gets released then downloaded for the first time, an email alert to say "xxxx movie has been successfully downloaded" would be nice.

same for times when quality has been updated. I would like to know when something has been upgraded.

**Comment by MeltedLux** [comment]
This is already a thing in both Sonarr and Radarr.
![](https://i.hatethe.uk/qasXhAFMJqGQ.png)
