### ISSUE TITLE
Unable to parse movie info from path

### ISSUE THREAD

**Issue by Jorman** [Radarr/Radarr#1452]
Hi Radarr succesfully find and downloaded a movie but now can't parse the movie itself, I don't have much details, this is the error

`Unable to parse movie info from path /share/CACHEDEV1_DATA/Download/automatics/complete/radarr/[Xvid - ITA] Deuce Bigalow - Puttano In Saldo.avi`

Any idea?
Tnx, Jo

**Comment by galli-leo** [comment]
You need to have the year in the movie filename right after the movie title. Additionally, you cannot have the [...] stuff in front of the movie name. You have to put that after the year.

**Comment by Jorman** [comment]
Tnx for the reply, I've no problem to manually rename the file, but this is the name that the releaser gave to the release, so radarr grabbed that file, and now can't import in the movie.

So, Is maybe a kind of implementation that radarr will have? not all release are correctly formatted when released

**Comment by galli-leo** [comment]
@Jorman Yeah there should be an issue already open for that. But 99% of the releases are in a format that Radarr understands so it's not really a high priority getting that in right now.

**Comment by galli-leo** [comment]
@Jorman Yeah there should be an issue already open for that. But 99% of the releases are in a format that Radarr understands so it's not really a high priority getting that in right now.

**Comment by Jorman** [comment]
Ok, tnx for the clarification! Got it! Actually is an old release, so, I will stop the torrent once the ratio is grantee and I'll import it manually.

Only one things, is possible, on searching phase, to "normalize" all the character? I mean I've a movie that contain the ò character but all the release was made with the normal o not the ò, so any search can't return the movie title. What option I've in this case? Radarr in future will search both movie title, with and without the particular character? Or is better to manually add some kind of second title on the movie format in Radarr?

Sorry if I bother you, I only need to learn.
Jo

**Comment by galli-leo** [comment]
Well Radarr will (IIRC) exchange these characters already, since almost all indexers will return the desired results even if you search with o instead of ò.

**Comment by Jorman** [comment]
Ok, tnx so much for all this info but maybe I'm wrong, but I think there's some kind of problem here, maybe I've to open a new issue?
Look at this:
The movie title is:
`Deuce Bigalow - Gigolò Per Sbaglio`
And on Jacket logs I've this:
```
Apr 28, 2017 06:10:43 PM	Info	
Found 0 releases from TorrentBytes for: deuce bigalow gigolò per sbaglio 1999
Apr 28, 2017 06:10:24 PM	Info	
Found 0 releases from Torrentz2 for: deuce bigalow gigolò per sbaglio 1999
Apr 28, 2017 06:10:08 PM	Info	
Found 0 releases from The Pirate Bay for: deuce bigalow gigolò per sbaglio 1999
Apr 28, 2017 06:10:07 PM	Info	
Found 0 releases from Shareisland for: deuce bigalow gigolò per sbaglio 1999
Apr 28, 2017 06:10:06 PM	Info	
Found 0 releases from TNTVillage for: deuce bigalow gigolò per sbaglio 1999
Apr 28, 2017 06:10:03 PM	Info	
Found 0 releases from LimeTorrents for: deuce bigalow gigolò per sbaglio 1999
Apr 28, 2017 06:09:42 PM	Info	
Found 0 releases from AlphaRatio for: deuce bigalow gigolò per sbaglio 1999
Apr 28, 2017 06:09:41 PM	Info	
Found 0 releases from Il Corsaro Nero for: deuce bigalow gigolò per sbaglio 1999
```
On Radarr logs I've this:
`Searching 9 indexers for [Deuce Bigalow - Gigolò per sbaglio]`

Why I see ò instead o?
On Il Corsaro Nero, with o there's a release, but with ò not.

Maybe is the indexer?

Sorry If I bother you

**Comment by Jorman** [comment]
A little update for you, that correct a little my previous post:

If I search directly on Il Corsaro Nero, for example, seems that the problem is the year, not the char, correct me if I wrong, but I think that I've saw once, that Radarr search with and without the year, is only one my allucination?

So if I search on Corsaro Nero
[With the year](http://ilcorsaronero.info/argh.php?search=deuce+bigalow+gigol%C3%B2+per+sbaglio+1999)
0 results
But if I search
[Without the year](http://ilcorsaronero.info/argh.php?search=deuce+bigalow+gigol%C3%B2+per+sbaglio)

So maybe is a problem of the indexer!
