### ISSUE TITLE
Edition Tags not working on existing media

### ISSUE THREAD

**Issue by the-misterlas** [Radarr/Radarr#1453]
**Description:**

Edition Tags do not seem to be working for existing media.  I have adjusted the naming schema as follows, but cannot make use of it yet:

http://i.imgur.com/qNmJ2S7.png

Adjusted the filename manually and attempted a scan, no change.

Deleted and re-added the movie and let it re-scan, and the Edition is not being flagged.

http://i.imgur.com/lwvPUdL.png

Confirmed with a few redditors that it does work on freshly downloaded media, but I am trying to get it working with my existing rip.   

Thanks in advance for any assistance!

**Radarr Version:**

0.2.0.654

**Logs:**

The log from radarr.txt after I deleted and re-added the movie and let it scan.

```
17-4-27 16:45:14.5|Info|MovieService|Adding Movie [][The Lord of the Rings: The Fellowship of the Ring (2001)] Path: [/mnt/media/Movies/The_Lord_of_the_Rings_The_Fellowship_of_the_Ring_(2001)]
17-4-27 16:45:14.5|Info|MediaCoverService|Downloading Poster for [][The Lord of the Rings: The Fellowship of the Ring (2001)] http://image.tmdb.org/t/p/original/bxVxZb5O9OxCO0oRUNdCnpy9NST.jpg
17-4-27 16:45:14.5|Info|RefreshMovieService|Updating Info for The Lord of the Rings: The Fellowship of the Ring
17-4-27 16:45:14.7|Info|DiskScanService|Scanning disk for The Lord of the Rings: The Fellowship of the Ring
17-4-27 16:45:14.8|Info|MovieService|Linking [The_Lord_of_the_Rings_The_Fellowship_of_the_Ring_(2001)_Extended_Edition_[Bluray-1080p].mkv] > [[tt0120737][The Lord of the Rings: The Fellowship of the Ring (2001)]]
17-4-27 16:45:14.8|Info|MovieService|Linking [The_Lord_of_the_Rings_The_Fellowship_of_the_Ring_(2001)_Extended_Edition_[Bluray-1080p].mkv] > [[tt0120737][The Lord of the Rings: The Fellowship of the Ring (2001)]]
17-4-27 16:45:14.8|Info|DiskScanService|Completed scanning disk for The Lord of the Rings: The Fellowship of the Ring
17-4-27 16:45:14.8|Info|MovieScannedHandler|[The Lord of the Rings: The Fellowship of the Ring] was recently added, performing post-add actions
17-4-27 16:45:15.2|Info|MediaCoverService|Downloading Banner for [tt0120737][The Lord of the Rings: The Fellowship of the Ring (2001)] http://image.tmdb.org/t/p/original/pIUvQ9Ed35wlWhY2oU6OmwEsmzG.jpg
```

**Comment by galli-leo** [comment]
Can you try naming it The Lord of the Rings The Fellowship of the Ring (2001) Extended Edition etc.?

**Comment by the-misterlas** [comment]
Per /u/fryfrog on reddit (and @galli-leo was on the same train of thought), I replaced the underscores with 
 spaces in the filename and re-scanned.  This time it worked.

http://i.imgur.com/0awKkF2.png


So it appears to be an issue with using underscores.

**Comment by galli-leo** [comment]
@the-misterlas Yeah, I fixed that on the latest nightly. But that's not in the latest develop release. So I am going to close the issue for now :)

**Comment by galli-leo** [comment]
So with the next release you should be able to keep your underscores.

**Comment by the-misterlas** [comment]
Thanks so much @galli-leo!   You guys had it fixed before I even reported it... great devs!  Totally earned a second donation from me!

**Comment by galli-leo** [comment]
@the-misterlas Well fryfrog already reported that the other day and I quickly patched it, but thank you very much for your support :)
