### ISSUE TITLE
[Feature Request] On Upgrade Output deleted relative movie path like sonarr

### ISSUE THREAD

**Issue by ryanmurray** [Radarr/Radarr#1455]
Sonarr outputs to path variables during an upgrade
could radarr be set up to output just like sonarr this would enable me to better write my script which has a cache directory for cloud people and would enable me to delete the real file.
a bonus would be a
$radarr_movie_filename
$radarr_deleted_movie_filename
that would be really really helpful

**Comment by mattmac24** [comment]
This would be great to have.

**Comment by arddor** [comment]
I would also appreciate it

**Comment by danjames92** [comment]
@ryanmurray would you mind sharing your script? i'm interested to compare to my current.

**Comment by onedr0p** [comment]
I believe this is done in v3

https://github.com/Radarr/Radarr/blob/aphrodite/src/NzbDrone.Core/Notifications/CustomScript/CustomScript.cs#L91
