### ISSUE TITLE
Not Saving Indexers/Lists on Error

### ISSUE THREAD

**Issue by Watison** [Radarr/Radarr#1456]
**Description:**

When saving a new list or indexer it tests the connection, then doesn't save if an error is returned. It should save regardless of an error being returned, and shouldn't need to test the connection unless prompted.

**Radarr Version:**

0.2.0.654

**Logs:**

Invalid request Validation failed: 
 -- Unable to connect to indexer. Request limit reached (26/25)

**Comment by fryfrog** [comment]
![screen shot 2017-04-28 at 10 08 13 am](https://cloud.githubusercontent.com/assets/87748/25539146/a627901a-2bfa-11e7-9579-148d95d4fd04.png)

Works fine for me, I changed this one to fail test and saved it over and over and over again.

**Comment by Watison** [comment]
Just checked again and it's working for me now too. Guess I'll close this...
