### ISSUE TITLE
'Downloaded' Sort/Filter Field 

### ISSUE THREAD

**Issue by Watison** [Radarr/Radarr#1457]
**Description:**

When sorting your movie list by 'Downloaded', it hides the missing movies rather than moving them to the top/bottom of the list. A 'Downloaded' filter button should be added rather than the sort field hiding movies.

**Radarr Version:** 0.2.0.654

**Logs:** Nil

**Comment by galli-leo** [comment]
This unfortunately is a limitation of how we filter by downloaded. This should be addressed when we update our UI. However, if you filter by downloaded, surely you don't want to look at not downloaded movies?
