### ISSUE TITLE
Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by Tenzinn3** [Radarr/Radarr#1463]
17-4-29 22:14:14.9|Info|NzbSearchService|Searching 4 indexers for [Hwasangorae]
17-4-29 22:14:14.9|Warn|SecurityProtocolPolicy|Disabled Tls1.2 due to remote certificate error.
17-4-29 22:14:15.1|Warn|Rarbg|Rarbg  The request was aborted: Could not create SSL/TLS secure channel.

It also happens with other trackers. When I test them they all connect, this happens on and off, it has worked on other days.

Running Windows Server 2012 R2

**Comment by galli-leo** [comment]
This can either be because of a too old version of .NET, windows or due to the indexers.

The underlying reason is that the tls version Radarr is trying to use is not compatible with the indexers. Nothing we can do.
