### ISSUE TITLE
Missing MediaInfo parsing after download

### ISSUE THREAD

**Issue by dariosm** [Radarr/Radarr#1465]
When download is complete and Parser starting doing its work given "Standard Movie Format" expression, fails to process MediaInfo fields, but there aren't neither error on logs nor information that MediaInfo is actually being processed.
I'm using the following expression: `{Movie CleanTitle} {(Release Year)} {Edition Tags} [{Quality Full}] [{MediaInfo Video} {MediaInfo Audio}] [{Release Group}]`
An example: for the file name `'The.Accountant.2016.REMUX.1080p.BluRay.AVC.DTS-HD.MA7.1-iFT'`, the following are correctly parsed:
```
Language parsed: English
Quality parsed: Remux-1080p v1
Release Group parsed: iFT

```
The resulting file name is: `The Accountant (2016) [Remux-1080p] [ ] [iFT]`
Clearly there is something going on since MediaInfo is missing.

I can confirm it works just fine by manually triggering rename (Organize & Rename function, in movie page). MediaInfo is correctly generated in this case.

Radarr Ver. 0.2.0.654 develop
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/966291/radarr.debug.txt)

**Comment by dariosm** [comment]
Another movie just got downloaded and correctly renamed automatically: `99 Homes (2014) [Bluray-1080p] [x264 DTS-HD MA] [EPiC].mkv`
I checked out the logs and see a debug msg from `VideoFileInfoReader`. I'm not familiar with the src, but I can guess it is the responsible for getting MediaInfo. 
The only think I changed from the first post till now, is turning off hard links, since download path and movie root and in different filesystems.
Could the hard link failure (present in the original log) be preventing the organizing and renaming process to complete?
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/966310/radarr.debug.txt)

**Comment by PnoT** [comment]
I am experiencing the same issue with the mediainfo not populating properly but specifically the audio portion {Mediainfo.Simple}.  On download the move is named and only after I do a rescan of the movie file and a rename will the proper info be put into the file name.

**Comment by galli-leo** [comment]
@dariosm What version of media info are you using? It seems like it has something to do with Remuxes

**Comment by PnoT** [comment]
mono 4.8.1 / latest radarr / mediainfo v0.7.96

I reported some odd issues as well which may or may not be a part of this one on #1571

**Comment by dariosm** [comment]
@galli-leo 
```
~$ mediainfo --version
MediaInfo Command line, 
MediaInfoLib - v0.7.82

```
