### ISSUE TITLE
Add Czech language to profiles

### ISSUE THREAD

**Issue by gregorij89** [Radarr/Radarr#1467]
Hi,

please add the Czech language to profile settings. For example, The Da Vinci Code on Czech indexers looks like this:

Šifra mistra Leonarda / The Da Vinci Code (Extended Cut) (2006)(CZ/EN)[1080pHD] (Radarr is unable to recognize the movie name, it says Unknown movie. Movie found does not match wanted movie.)
or
The.Da.Vinci.Code.2006.Extended.Cut.BDRip.XviD.AC3.CZ-Starcross (more convenient naming, it is recognized)

Valid language tags are CZ, CS, CZE, CZECH.

It would be also great if the library could be localized, or at least use localized names in alternatives better. The current behavior cause problems with originally Czech movies (and I suppose it is the same with any other language than English). For example, the movie Lída Baarová is added as Devil's Mistress (that is official movie name in English), but no one uses that. It has also the Czech name as an alternative. But during searching, no results are found, even though there is valid result named Lida.Baarova.2016.720p.BluRay.DD5.1.x264.CZ-TreZzoR. Maybe Radarr is not handling alternative names well, or maybe it is caused by accents that are used in the alternative name but not in the release name (Lída Baarová vs. Lida Baarova). I know it is a lot of work to do, but it would really help with processing non-English movies. The universal solution to this could solve the same problem with Slovak, German etc.

**Comment by galli-leo** [comment]
I already have a PR for the second problem (Radarr would then search with the additional titles as well.) For the first part, yeah I have to think about movies which have both, original and translated title in their name as well.

**Comment by gregorij89** [comment]
Oh, I am glad to hear that. The downside of it is that Raddar will do a lot more searching (there are movies that have 4 or more alternative names) but that´s the cost. It doesn´t matter in a torrent part of the world, it could be a problem only with NZB indexers. It could also be reasonable to change every accented character into its ASCII form (eg. á => a, č => c, ü=> u etc.) There is a custom (at least at many Czech sites) that accented characters are not used in filenames. It causes troubles with encodings etc. The best would be to use both forms as searching titles, but again, it will increase the queries generated by one movie search.

Or would it be difficult to let the user choose which name should be used as main movie name and for searching? I suppose that the movie name is not used as an ID in the database, or is it?

**Comment by galli-leo** [comment]
@gregorij89 If your indexer is even a little bit smart about it (which I assume most of them are), then they will treat e.g. à the same as a when searching. You could also tell your indexer to make searching by imdbid a thing. Then you don't have to worry about messed up titles :)

Also I made the PR sucht that we query less pages per title, if more titles are used.

**Comment by gregorij89** [comment]
Ok. perfect. You are right about the smartness of the indexers. I somehow forgot about it :).
