### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by soccermax** [Radarr/Radarr#1478]
Hey guys, 

I switched from CP to Sonarr and I've got the problem that I cant connect via ssl to the GUI. My Server is located in a datacenter, therefore without ssl is no way to connect. Anything I can do? Thanks

**Comment by onedr0p** [comment]
Try to set up a reverse proxy using nginx, there are a lot of tutorials online.

**Comment by soccermax** [comment]
Is that also possible with apache?

**Comment by galli-leo** [comment]
@soccermax Yeah should be similar.

**Comment by animosity22** [comment]
My proxy with apache is pretty straight forward:

```
# Radarr
ProxyPass /radarr/ http://127.0.0.1:7878/radarr/
ProxyPassReverse /radarr/ http://127.0.0.1:7878/radarr/
```

You can lock it down via a login as well. I personally use a forms based page, but that's me.

**Comment by soccermax** [comment]
@animosity22 I used this settings too, the problem was that when I call the Radarr Webinf  a lot of files are missing. Then I passed also http://127.0.0.1:7878/Content via the proxy,  which resolve a lot of errors but there are also a lot of files which are locate in the root directory (https://my.dyndns.org/(missingfile)) The right URI must be (https://my.dyndns.org/radarr/(missingfile)) because of the proxy path. Do you know what I mean?

**Comment by galli-leo** [comment]
@soccermax You have to set the base url in the settings of Radarr, IIRC under Settings -> General. Then restart Radarr. Then you do not have to proxy pass the Content dir.

**Comment by animosity22** [comment]
So sorry, yes I have Base Url:

```
/radarr
```

As I have multiples apps reverse proxied.

**Comment by soccermax** [comment]
Thank you guys. Perfect, I didn't know that this option is available. Anyone knows where the relevant configfile is located because I cant reach the webinf at the moment.

**Comment by galli-leo** [comment]
@soccermax Depends on your system. See radarr.video/config for the location of your config and database files.

**Comment by soccermax** [comment]
I set the the Base URL to
`<Config>
  <LogLevel>Info</LogLevel>
  <Port>7878</Port>
  <UrlBase>/radarr</UrlBase>
  <BindAddress>*</BindAddress>
  <SslPort>8989</SslPort>
  <EnableSsl>False</EnableSsl>
  <ApiKey>b7c6c975c73b42169900b050b9e39484</ApiKey>
  <AuthenticationMethod>Forms</AuthenticationMethod>
  <Branch>develop</Branch>
  <LaunchBrowser>False</LaunchBrowser>
  <SslCertHash></SslCertHash>
  <UpdateMechanism>BuiltIn</UpdateMechanism>
  <AnalyticsEnabled>False</AnalyticsEnabled>
</Config>`

And set the reverse Proxy in Apache2 to:
`
ProxyRequests Off
        <Proxy *>
                Order deny,allow
              Allow from all
        </Proxy>
        ProxyPass /radarr/ http://127.0.0.1:7878/radarr
        ProxyPassReverse /radarr/ http://127.0.0.1:7878/radarr
`

The problem with the missing files is still there. Connecting to radarr via ssh tunnel works but that sucks.

**Comment by galli-leo** [comment]
Sorry for not responding, must have missed the notification. If you still have errors, feel free to keep commenting here, but I would suggest you head over to our Discord or Subreddit where we handle support.
