### ISSUE TITLE
Movie editor Does Not Uncheck after Saving changes

### ISSUE THREAD

**Issue by hoovdizz** [Radarr/Radarr#1479]
**Description:**
I Recently Migrated from one server to another. 
I had to adjust the paths to a network style from the original E: drive
After adding the new root path. I would highlight what needs to be moved via movie editor, use the drop down and click save. 
The movies would update with the new path, but stay checked and since I was sorting by path, it would move the movies that got checked 100s of pages away. It was easier to refresh the page, wait for it to query then repeat the process. then try and find the movies to uncheck them. 

I combed through all ten pages of your Issues, nothing related to the unchecking after a save in movie editor could be found. 

I have been bitten by this before when changing movie profiles and monitoring status before I moved servers. 

I have tried this in both chrome and IE, also tried clearing cache and using it in incognito mode. 

I don't have this issue in sonarr. 

**Radarr Version:**
Radarr Ver. 0.2.0.654

**Comment by galli-leo** [comment]
Well a lot of people want to keep the movies checked when they change something. So I don't think we are going to change that anytime soon. Anyways, you can just refresh the page.
