### ISSUE TITLE
Radarr stops loading at safari

### ISSUE THREAD

**Issue by cyberb0b** [Radarr/Radarr#1481]
**Description:**
Radarr stops loading in Safari. I see the loading screen but thats all I see.
If I check out the source of the page, I see timeouts on 

http://192.168.1.2:8310/api/movie?page=1&pageSize=1000&sortKey=sortTitle&sortDir=asc&filterKey=null&filterValue=null

And a timeout error DOM exception 23.

At the moment there are 294 items in my database. 
I noticed that in the beginning it worked, till I started to add movies.
- clearing history does not work
- private window does not work.
(chrome browser does work)

Radarr Version: 2.0.645
Safari Version 10.1: (12603.1.30.0.34)

**Logs:**
Where are those from the webserver? 

![screen shot 2017-05-02 at 00 06 03](https://cloud.githubusercontent.com/assets/669659/25596760/2c1dfdbc-2ecb-11e7-8d1b-04ff10dace01.png)
![screen shot 2017-05-02 at 00 06 18](https://cloud.githubusercontent.com/assets/669659/25596761/2c1e966e-2ecb-11e7-9b9c-9ea3ffb28dd7.png)

**Comment by SJ50** [comment]
I had same change the page size from developer menu it works.
https://github.com/Radarr/Radarr/issues/1197#issuecomment-297401995
Once in developer menu click "Show Web Inspector" than Storage and follow the instruction from above link.
