### ISSUE TITLE
Radarr doesn't properly parse movie with "Final" in the name

### ISSUE THREAD

**Issue by fryfrog** [Radarr/Radarr#1482]
A release like `Resident.Evil.The.Final.Chapter.2016.1080p.BluRay.DTS.x264-PriMaLHD` or `Resident.Evil.The.Final.Chapter.2016.MULTI.BluRay.1080p.x264.AAC-Plex2U English` doesn't properly parse because it thinks "Final" is an addition.

![screen shot 2017-05-02 at 12 24 58 pm](https://cloud.githubusercontent.com/assets/87748/25635745/13db69f6-2f34-11e7-965d-57e9e4248503.png)

**Comment by galli-leo** [comment]
Fixed in nightly.
