### ISSUE TITLE
Torznab (Jackett) Karagarga - No results found

### ISSUE THREAD

**Issue by vendeka** [Radarr/Radarr#1483]
Hi,

When I try to search movie through Torznab Karagarga indexer, I always get no results found.

I checked logs in detail and the problem seems like the search query used doesn't include the, of etx and also includes movie year. For example, I added 'The Memory of Justice' and the query string is 'memory justice 1976'.

Radarr Ver. 0.2.0.654

**Logs:**
17-5-3 02:23:26.8|Info|NzbSearchService|Searching 1 indexers for [The Memory of Justice]
17-5-3 02:23:26.8|Trace|HttpClient|Req: [GET] http://localhost:9117/torznab/karagarga/api?t=caps&apikey=(removed)
17-5-3 02:23:26.8|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
17-5-3 02:23:29.5|Trace|HttpClient|Res: [GET] http://localhost:9117/torznab/karagarga/api?t=caps&apikey=(removed) 200.OK (2693 ms)
17-5-3 02:23:29.5|Debug|Torznab|Downloading Feed http://localhost:9117/torznab/karagarga/api?t=search&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060,100001&extended=1&apikey=(removed)&offset=0&limit=100&q=memory%20justice%201976
17-5-3 02:23:29.5|Trace|HttpClient|Req: [GET] http://localhost:9117/torznab/karagarga/api?t=search&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060,100001&extended=1&apikey=(removed)&offset=0&limit=100&q=memory%20justice%201976
17-5-3 02:23:29.5|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
17-5-3 02:23:37.5|Trace|HttpClient|Res: [GET] http://localhost:9117/torznab/karagarga/api?t=search&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060,100001&extended=1&apikey=(removed)&offset=0&limit=100&q=memory%20justice%201976: 200.OK (8017 ms)
17-5-3 02:23:37.6|Debug|NzbSearchService|Total of 0 reports were found for [The Memory of Justice] from 1 indexers
17-5-3 02:23:37.6|Info|DownloadDecisionMaker|No results found

**Comment by galli-leo** [comment]
Can you copy the query url and delete the year and see if it works that way?

**Comment by vendeka** [comment]
Hi,
Movie name: The Memory of Justice

Original query made through Radarr is (w/o 'the', 'of' and with 1976)
[URL]&q=memory%20justice%201976

The query works is (with 'the', 'of' and w/o 1976)
[URL]&q=the%20memory%20of%20justice

To sum up, when I search manually with 'the' and 'of' and without year, it works.

**Comment by galli-leo** [comment]
@vendeka Can you verify that searching with the and of, but no year still works?

**Comment by vendeka** [comment]
**WORKING Queries:**
[URL]&q=memory%20of%20justice
[URL]&q=the%20memory%20of%20justice

**NON-WORKING Queries:**
[URL]&q=memory%20justice%201976
[URL]&q=memory%20of%20justice%201976
[URL]&q=the%20memory%20of%20justice%201976

**Comment by maciekb** [comment]
I have the same problem with query
Movie "To the Bone"

Working:
&q=to%20the%20bone

Not working (sent by Radarr to Jackett):
&q=to%20bone

**Comment by galli-leo** [comment]
@maciekb that's a different error. The ops query are not working because of the year. Your issue seems to be related to the the being removed. I would try contacting your indexer about that, since titles should be searchable without the the.
