### ISSUE TITLE
Movie file not recognized

### ISSUE THREAD

**Issue by milika** [Radarr/Radarr#1485]
**Description:**
Bunch of movies are not recognized as present (video files), even thought they are definitely there.
Movie is present in Radarr list, but shown as not downloaded.

**Radarr Version:**
0.2.0.654

**Logs:**
For hatefull 8:
17-5-3 03:53:41.3|Debug|DiskScanService|Scanning 'D:\Share\Filmovi\Hateful Eight, The' for video files
17-5-3 03:53:41.3|Debug|DiskScanService|1 video files were found in D:\Share\Filmovi\Hateful Eight, The
17-5-3 03:53:41.3|Trace|DiskScanService|Finished getting episode files for: [tt3460252][The Hateful Eight (2015)] [00:00:00.0617266]
17-5-3 03:53:41.4|Debug|DiskScanService|[tt3460252][The Hateful Eight (2015)] Cleaning up media files in DB
17-5-3 03:53:41.4|Debug|ImportDecisionMaker|Analyzing 1/1 files.
17-5-3 03:53:41.5|Debug|Parser|Parsing string 'The Hateful Eight.mkv'
17-5-3 03:53:41.5|Debug|Parser|Unable to parse The Hateful Eight.mkv
17-5-3 03:53:41.5|Debug|Parser|Attempting to parse episode info using directory and file names. Hateful Eight, The
17-5-3 03:53:41.5|Debug|Parser|Parsing string 'Hateful Eight, The The Hateful Eight.mkv'
17-5-3 03:53:41.6|Debug|Parser|Unable to parse Hateful Eight, The The Hateful Eight.mkv
17-5-3 03:53:41.6|Debug|Parser|Attempting to parse episode info using directory name. Hateful Eight, The
17-5-3 03:53:41.7|Debug|Parser|Parsing string 'Hateful Eight, The.mkv'
17-5-3 03:53:41.7|Debug|Parser|Unable to parse Hateful Eight, The.mkv
17-5-3 03:53:41.7|Warn|ParsingService|Unable to parse movie info from path D:\Share\Filmovi\Hateful Eight, The\The Hateful Eight.mkv
17-5-3 03:53:41.8|Trace|DiskScanService|Import decisions complete for: [tt3460252][The Hateful Eight (2015)] [00:00:00.3958220]

**Comment by galli-leo** [comment]
You need to add the year of the movie to the filename or folder name (best is both)

**Comment by Systemshark** [comment]
I've got this problem. but manually editing 300 films is not going to work for me, why does it need a year, surely it's part of the radarr choice to offer the match as we correct it and if it's a single film with a single name why does the year make a difference,  personally I think it should complete the match regardsless
