### ISSUE TITLE
BAD, Radarr import non wanted movies!

### ISSUE THREAD

**Issue by ghost** [Radarr/Radarr#1487]
Hello,

As soon as I mapped it with my deluge label previously used for CouchPotato, it imported EVERYTHING... 
30 movies not in my wanted list :(

Thanks for fix

**Comment by galli-leo** [comment]
So it imported movies that you have not added to Radarr?

**Comment by raspdealer** [comment]
Not in the wanted list!

**Comment by fryfrog** [comment]
Where they maybe in the Wanted -> Cutoff Unmet?
