### ISSUE TITLE
Movie Editor | Change All Movies To Monitored Not Working

### ISSUE THREAD

**Issue by Fiala06** [Radarr/Radarr#1488]
I'm trying to bulk edit my movie collection and change every movie to monitored. Right now I have some that are not monitored and some that are. 

When using the movie editor, it doesn't seem to be working and I'm not seeing anything the log files. It does work on random files but a majority of the time it doesn't.

Would be nice also if you could see what each movie is currently set to on this page without clicking every single one.

http://i.imgur.com/Sx9WTrm.png

Radarr Ver. 0.2.0.654

Most recent logs and I've clicked bulk edit multiple times in this timeframe. 
`17-5-4 13:00:02.6|Info|PreDBService|Starting PreDB Sync
17-5-4 13:02:53.2|Info|MovieService|Linking [Return of the Jedi (1983) Bluray-1080p Proper.mkv] > [[tt0086190][Return of the Jedi (1983)]]
17-5-4 13:02:53.2|Info|MovieService|Linking [Return of the Jedi (1983) Bluray-1080p Proper.mkv] > [[tt0086190][Return of the Jedi (1983)]]
17-5-4 13:25:03.6|Info|RssSyncService|Starting RSS Sync
17-5-4 13:25:10.3|Warn|Torznab|Indexer RevolutionTT rss sync didn't cover the period between 5/4/2017 7:24:36 PM and 5/4/2017 8:25:10 PM UTC. Search may be required.
17-5-4 13:25:12.9|Info|DownloadDecisionMaker|Processing 108 releases
17-5-4 13:25:27.5|Info|RssSyncService|RSS Sync Completed. Reports found: 108, Reports grabbed: 0
17-5-4 13:35:34.7|Info|RecycleBinProvider|Recycling Bin has not been configured, deleting permanently. F:\Movies\Star Wars Episode II - Attack of the Clones (2002)\Star Wars- Episode II - Attack of the Clones (2002).avi
17-5-4 13:41:29.2|Info|MovieService|Linking [Star Wars Episode II - Attack of the Clones (2002) Bluray-1080p.mkv] > [[tt0121765][Star Wars: Episode II - Attack of the Clones (2002)]]
17-5-4 13:41:29.2|Info|MovieService|Linking [Star Wars Episode II - Attack of the Clones (2002) Bluray-1080p.mkv] > [[tt0121765][Star Wars: Episode II - Attack of the Clones (2002)]]
17-5-4 13:48:01.0|Info|MovieService|Linking [Star Wars The Force Awakens (2015) Bluray-1080p.mkv] > [[tt2488496][Star Wars: The Force Awakens (2015)]]
17-5-4 13:48:01.0|Info|MovieService|Linking [Star Wars The Force Awakens (2015) Bluray-1080p.mkv] > [[tt2488496][Star Wars: The Force Awakens (2015)]]
17-5-4 14:00:04.8|Info|PreDBService|Starting PreDB Sync
17-5-4 14:25:35.8|Info|RssSyncService|Starting RSS Sync
17-5-4 14:25:44.4|Info|DownloadDecisionMaker|Processing 111 releases
17-5-4 14:25:59.2|Info|RssSyncService|RSS Sync Completed. Reports found: 111, Reports grabbed: 0
17-5-4 14:39:36.3|Info|HousekeepingService|Running housecleaning tasks
17-5-4 14:39:36.4|Info|Database|Vacuuming Log database
17-5-4 14:39:36.6|Info|Database|Log database compressed
17-5-4 14:39:39.8|Info|Database|Vacuuming Main database
17-5-4 14:39:40.0|Info|Database|Main database compressed
17-5-4 15:00:07.2|Info|PreDBService|Starting PreDB Sync
17-5-4 15:26:08.3|Info|RssSyncService|Starting RSS Sync
17-5-4 15:26:18.5|Info|DownloadDecisionMaker|Processing 107 releases
17-5-4 15:26:32.6|Info|RssSyncService|RSS Sync Completed. Reports found: 107, Reports grabbed: 0
17-5-4 16:00:09.7|Info|PreDBService|Starting PreDB Sync
17-5-4 16:26:40.6|Info|RssSyncService|Starting RSS Sync
17-5-4 16:26:49.8|Warn|Torznab|Indexer RevolutionTT rss sync didn't cover the period between 5/4/2017 9:25:44 PM and 5/4/2017 11:26:49 PM UTC. Search may be required.
17-5-4 16:26:49.8|Info|DownloadDecisionMaker|Processing 108 releases
17-5-4 16:27:04.4|Info|RssSyncService|RSS Sync Completed. Reports found: 108, Reports grabbed: 0
17-5-4 16:55:22.3|Info|NzbSearchService|Searching 5 indexers for [Star Wars: Episode III - Revenge of the Sith]
17-5-4 16:55:33.7|Info|DownloadDecisionMaker|Processing 31 releases
17-5-4 16:55:34.3|Info|MovieSearchService|Movie search completed. 0 reports downloaded.
17-5-4 16:56:55.7|Info|NzbSearchService|Searching 5 indexers for [Star Wars: Episode III - Revenge of the Sith]
17-5-4 16:56:59.5|Info|NzbSearchService|Searching 5 indexers for [Star Wars: Episode III - Revenge of the Sith]
17-5-4 16:57:04.1|Info|DownloadDecisionMaker|Processing 31 releases
17-5-4 16:57:14.1|Info|DownloadDecisionMaker|Processing 31 releases
17-5-4 16:57:16.6|Info|DownloadService|Report sent to Blackhole. Star Wars Episode III Revenge Of The Sith 2005 1080p BluRay DTS-HD MA 6 1 x264-LEGi0N
17-5-4 16:57:20.0|Info|MovieSearchService|Movie search completed. 1 reports downloaded.
17-5-4 17:00:11.9|Info|PreDBService|Starting PreDB Sync`

**Comment by Grimeton** [comment]
Hi,

if in doubt, use the force:

```
curl -H 'X-Api-Key: YOUR_API_KEY_HERE' -X GET http://your_server/api/movie \
| jq -c '.[] | if .monitored == false then .monitored = true else empty end' \
| while read line; do 
    curl -H 'X-Api-Key: YOUR_API_KEY_HERE' -X PUT --data "$line" http://your_server/api/movie; 
done

```

cu

**Comment by galli-leo** [comment]
Can you verify this issue is still occuring on the latest version?

**Comment by Fiala06** [comment]
Looks like its working now. Thanks
