### ISSUE TITLE
Increase the default RSS Sync Interval

### ISSUE THREAD

**Issue by onedr0p** [Radarr/Radarr#149]
In Sonarr it defaults to 15 minutes, which makes sense, TV episodes are released more often. I think the default time for movies should be higher, perhaps a minimum of 6 hours with a default set to 12 hours.

Wuddyathink?

**Comment by galli-leo** [comment]
I think 15-30 minutes is fine. It does not use much data and does not slow down anything.

**Comment by galli-leo** [comment]
Anyway, I hope to integrate PreDB sometime soon, so RSS sync is not that important anymore.

**Comment by onedr0p** [comment]
I was think about how we're hammering the indexers with requests, we should be nice to them.

**Comment by fryfrog** [comment]
The RSS feeds from indexers only contain a certain number of recent listings, as you increase the time you increase the chance of missing a release. Using the RSS feed is just 1 query every 15 minutes, far better than something like CP which has to search for literally every movie it wants.

**Comment by fryfrog** [comment]
If you do change the default, 30-60 minutes is probably far better than 8-12 hours.
