### ISSUE TITLE
rutorrent movies always "pausing"

### ISSUE THREAD

**Issue by darknessgp** [Radarr/Radarr#1490]
I've got radarr setup to point to my rutorrent. But anytime it grabs a movie, whether manual or automatically, the torrent is stuck in "pausing" in rutorrent. It is labelled correctly. Stopping, starting, force recheck, update trackers, saving to a different location, or doing file recreation never gets it able to actually download. I have to just delete it and manually add it to rutorrent.

The rutorrent integration works great on Sonarr. Is there something I'm missing about Radarr's setup?

![image](https://cloud.githubusercontent.com/assets/1521243/25758505/6c60a9f8-3194-11e7-809f-908f935d0cdc.png)

**Comment by Pingblue** [comment]
A paused torrent in rutorrent normally indicates a problem with the specified download folder.

Right click the paused torrent in rutorrent and choose the "Save to" option to check the download location.

**Comment by darknessgp** [comment]
Yep... That's exactly what it was... Though around casing. part of my path was "/movies" but the real folder is "/Movies"
