### ISSUE TITLE
When deleting movie the files still exist

### ISSUE THREAD

**Issue by gregcbrown** [Radarr/Radarr#1493]
When deleting a movie from RADARR, the movie is deleted from database, but the files still exist on disk. The movie I deleted is La La Land.
RADARR Version; 0.2.0.654
Log:
17-5-6 10:55:12.0|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\A.Kind.of.Murder.2016.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR.cp(tt2726552)
17-5-6 10:55:12.5|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\Live.by.Night.2016.BluRay.1080p.DTS.x264-CHD.cp(tt2361317)
17-5-6 10:55:45.7|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\A.Kind.of.Murder.2016.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR.cp(tt2726552)
17-5-6 10:55:46.1|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\Live.by.Night.2016.BluRay.1080p.DTS.x264-CHD.cp(tt2361317)
17-5-6 10:56:12.1|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\A.Kind.of.Murder.2016.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR.cp(tt2726552)
17-5-6 10:56:12.5|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\Live.by.Night.2016.BluRay.1080p.DTS.x264-CHD.cp(tt2361317)
17-5-6 10:56:42.4|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\A.Kind.of.Murder.2016.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR.cp(tt2726552)
17-5-6 10:56:42.9|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\Live.by.Night.2016.BluRay.1080p.DTS.x264-CHD.cp(tt2361317)
17-5-6 10:57:12.3|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\A.Kind.of.Murder.2016.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR.cp(tt2726552)
17-5-6 10:57:12.9|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\Live.by.Night.2016.BluRay.1080p.DTS.x264-CHD.cp(tt2361317)
17-5-6 10:57:41.0|Info|RssSyncService|Starting RSS Sync
17-5-6 10:57:44.5|Info|DownloadDecisionMaker|Processing 490 releases
17-5-6 10:57:46.1|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\A.Kind.of.Murder.2016.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR.cp(tt2726552)
17-5-6 10:57:46.8|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\Live.by.Night.2016.BluRay.1080p.DTS.x264-CHD.cp(tt2361317)
17-5-6 10:58:12.7|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\A.Kind.of.Murder.2016.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR.cp(tt2726552)
17-5-6 10:58:13.6|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\Live.by.Night.2016.BluRay.1080p.DTS.x264-CHD.cp(tt2361317)
17-5-6 10:58:27.1|Info|RssSyncService|RSS Sync Completed. Reports found: 490, Reports grabbed: 0
17-5-6 10:58:42.6|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\A.Kind.of.Murder.2016.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR.cp(tt2726552)
17-5-6 10:58:43.2|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\Live.by.Night.2016.BluRay.1080p.DTS.x264-CHD.cp(tt2361317)
17-5-6 10:59:12.4|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\A.Kind.of.Murder.2016.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR.cp(tt2726552)
17-5-6 10:59:13.2|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\Live.by.Night.2016.BluRay.1080p.DTS.x264-CHD.cp(tt2361317)
17-5-6 10:59:46.1|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\A.Kind.of.Murder.2016.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR.cp(tt2726552)
17-5-6 10:59:46.6|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\Live.by.Night.2016.BluRay.1080p.DTS.x264-CHD.cp(tt2361317)
17-5-6 11:00:12.6|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\A.Kind.of.Murder.2016.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR.cp(tt2726552)
17-5-6 11:00:13.1|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\Live.by.Night.2016.BluRay.1080p.DTS.x264-CHD.cp(tt2361317)
17-5-6 11:00:42.3|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\A.Kind.of.Murder.2016.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR.cp(tt2726552)
17-5-6 11:00:42.8|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\Live.by.Night.2016.BluRay.1080p.DTS.x264-CHD.cp(tt2361317)
17-5-6 11:01:12.2|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\A.Kind.of.Murder.2016.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR.cp(tt2726552)
17-5-6 11:01:12.6|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\Live.by.Night.2016.BluRay.1080p.DTS.x264-CHD.cp(tt2361317)
17-5-6 11:01:45.9|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\A.Kind.of.Murder.2016.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR.cp(tt2726552)
17-5-6 11:01:46.5|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\Live.by.Night.2016.BluRay.1080p.DTS.x264-CHD.cp(tt2361317)
17-5-6 11:02:12.4|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\A.Kind.of.Murder.2016.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR.cp(tt2726552)
17-5-6 11:02:12.9|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\Live.by.Night.2016.BluRay.1080p.DTS.x264-CHD.cp(tt2361317)
17-5-6 11:02:42.4|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\A.Kind.of.Murder.2016.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR.cp(tt2726552)
17-5-6 11:02:42.8|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\Live.by.Night.2016.BluRay.1080p.DTS.x264-CHD.cp(tt2361317)
17-5-6 11:03:12.3|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\A.Kind.of.Murder.2016.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR.cp(tt2726552)
17-5-6 11:03:12.8|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\Live.by.Night.2016.BluRay.1080p.DTS.x264-CHD.cp(tt2361317)
17-5-6 11:03:45.9|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\A.Kind.of.Murder.2016.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR.cp(tt2726552)
17-5-6 11:03:46.4|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\Live.by.Night.2016.BluRay.1080p.DTS.x264-CHD.cp(tt2361317)
17-5-6 11:04:04.6|Warn|MediaCoverMapper|File C:\ProgramData\Radarr\MediaCover\140\poster.jpg not found
17-5-6 11:04:12.5|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\A.Kind.of.Murder.2016.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR.cp(tt2726552)
17-5-6 11:04:13.0|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\Live.by.Night.2016.BluRay.1080p.DTS.x264-CHD.cp(tt2361317)
17-5-6 11:04:42.5|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\A.Kind.of.Murder.2016.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR.cp(tt2726552)
17-5-6 11:04:42.9|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\Live.by.Night.2016.BluRay.1080p.DTS.x264-CHD.cp(tt2361317)
17-5-6 11:05:12.6|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\A.Kind.of.Murder.2016.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR.cp(tt2726552)
17-5-6 11:05:13.0|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\Live.by.Night.2016.BluRay.1080p.DTS.x264-CHD.cp(tt2361317)
17-5-6 11:05:42.3|Warn|MediaCoverMapper|File C:\ProgramData\Radarr\MediaCover\140\poster.jpg not found
17-5-6 11:05:46.0|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\A.Kind.of.Murder.2016.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR.cp(tt2726552)
17-5-6 11:05:46.5|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\Live.by.Night.2016.BluRay.1080p.DTS.x264-CHD.cp(tt2361317)
17-5-6 11:06:12.6|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\A.Kind.of.Murder.2016.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR.cp(tt2726552)
17-5-6 11:06:13.1|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\Live.by.Night.2016.BluRay.1080p.DTS.x264-CHD.cp(tt2361317)
17-5-6 11:06:42.8|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\A.Kind.of.Murder.2016.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR.cp(tt2726552)
17-5-6 11:06:43.3|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\Live.by.Night.2016.BluRay.1080p.DTS.x264-CHD.cp(tt2361317)
17-5-6 11:07:12.8|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\A.Kind.of.Murder.2016.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR.cp(tt2726552)
17-5-6 11:07:13.4|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\Live.by.Night.2016.BluRay.1080p.DTS.x264-CHD.cp(tt2361317)
17-5-6 11:07:46.4|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\A.Kind.of.Murder.2016.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR.cp(tt2726552)
17-5-6 11:07:46.8|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\Live.by.Night.2016.BluRay.1080p.DTS.x264-CHD.cp(tt2361317)
17-5-6 11:08:12.6|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\A.Kind.of.Murder.2016.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR.cp(tt2726552)
17-5-6 11:08:13.0|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\Live.by.Night.2016.BluRay.1080p.DTS.x264-CHD.cp(tt2361317)
17-5-6 11:08:41.6|Info|RssSyncService|Starting RSS Sync
17-5-6 11:08:42.7|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\A.Kind.of.Murder.2016.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR.cp(tt2726552)
17-5-6 11:08:43.2|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\Live.by.Night.2016.BluRay.1080p.DTS.x264-CHD.cp(tt2361317)
17-5-6 11:08:45.0|Info|DownloadDecisionMaker|Processing 490 releases
17-5-6 11:09:12.9|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\A.Kind.of.Murder.2016.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR.cp(tt2726552)
17-5-6 11:09:13.5|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\Live.by.Night.2016.BluRay.1080p.DTS.x264-CHD.cp(tt2361317)
17-5-6 11:09:20.9|Info|RssSyncService|RSS Sync Completed. Reports found: 490, Reports grabbed: 0
17-5-6 11:09:42.7|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\A.Kind.of.Murder.2016.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR.cp(tt2726552)
17-5-6 11:09:43.1|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\Live.by.Night.2016.BluRay.1080p.DTS.x264-CHD.cp(tt2361317)
17-5-6 11:10:16.3|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\A.Kind.of.Murder.2016.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR.cp(tt2726552)
17-5-6 11:10:16.8|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\Live.by.Night.2016.BluRay.1080p.DTS.x264-CHD.cp(tt2361317)
17-5-6 11:10:42.8|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\A.Kind.of.Murder.2016.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR.cp(tt2726552)
17-5-6 11:10:43.2|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\Live.by.Night.2016.BluRay.1080p.DTS.x264-CHD.cp(tt2361317)
17-5-6 11:11:12.9|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\A.Kind.of.Murder.2016.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR.cp(tt2726552)
17-5-6 11:11:13.4|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\Live.by.Night.2016.BluRay.1080p.DTS.x264-CHD.cp(tt2361317)
17-5-6 11:11:43.0|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\A.Kind.of.Murder.2016.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR.cp(tt2726552)
17-5-6 11:11:43.5|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\Live.by.Night.2016.BluRay.1080p.DTS.x264-CHD.cp(tt2361317)
17-5-6 11:12:11.8|Info|PreDBService|Starting PreDB Sync
17-5-6 11:12:11.8|Info|NetImportSearchService|No lists are enabled for auto-import.
17-5-6 11:12:16.5|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\A.Kind.of.Murder.2016.BluRay.1080p.DTS-HD.MA.5.1.AVC.REMUX-FraMeSToR.cp(tt2726552)
17-5-6 11:12:16.9|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: I:\Users\Greg\SABnzbd\Complete\Live.by.Night.2016.BluRay.1080p.DTS.x264-CHD.cp(tt2361317)

**Comment by gregcbrown** [comment]
I believe the movie was originally downloaded via couchpotato and sabnzb, but imported into RADARR...

**Comment by galli-leo** [comment]
Yeah known issue, I did not yet implement that. But there's already an issue open on here for that :)
