### ISSUE TITLE
Movie import will not work

### ISSUE THREAD

**Issue by nriley2** [Radarr/Radarr#1495]
**Description:**
No matter what I change any movies in the drone factory folder won't work and causes an error on rescanning the drone factory, as well as import and bulk import don't do anything at all whereas downloading movies works perfect, the error is always the same and is below.
Message
`Request Failed: Sequence contains no matching element`

Exception
```
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at NzbDrone.Api.Commands.CommandModule.StartCommand(CommandResource commandResource) in C:\projects\radarr-usby1\src\NzbDrone.Api\Commands\CommandModule.cs:line 43
   at NzbDrone.Api.REST.RestModule`1.<set_CreateResource>b__41_0(Object options) in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:line 161
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)
```

**Radarr Version:**
0.2.0.654
**Logs:**
Attatched
[radarr.txt](https://github.com/Radarr/Radarr/files/981316/radarr.txt)
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/981317/radarr.debug.txt)

**Comment by galli-leo** [comment]
For bulk import, how is your movie folder structured?

**Comment by nriley2** [comment]
Fur the bulk import they're structured just freely out of folders but I've tried putting 5 in folders with the proper naming scheme, and when I do a manual import from the wanted tab every movie comes up but all are unknown movie

**Comment by galli-leo** [comment]
@nriley2 For bulk import movies have to be in seperate folders each. For manual import, what was the naming scheme of those movies which showed up unknown?

**Comment by nriley2** [comment]
For the bulk import I always tried it with movies I put in folders with the naming scheme Movie Title (Year) for folders and the same but with quality for the files, and for the manual import/the drone factory folder 90% of them go by Title (year) (quality) and after the 90% process I would make sure the others were named correctly and found

**Comment by nriley2** [comment]
@galli-leo Any updates on a solution yet? I am hopeful to get this up and working finally

**Comment by galli-leo** [comment]
@nriley2 Can you try it on a different browser or in an incognito window? I cannot reproduce the issue, for me the command is executed fine. Also what exact issues are you having with bulk import?

**Comment by nriley2** [comment]
@galli-leo I've tried it via my dynamic DNS from many different locations and different browsers, and have even just installed it on my laptop to test it out and the 'Rescan Drone Factory' button throws that error in the log and the manual import will list all movie files but refuses to match any of them to movies with the 'unknown movie' on all of them, Bulk import started working but intermittently stops working just in general misses some gets others. not quite sure what causes it it is quite puzzling

**Comment by galli-leo** [comment]
@nriley2 Can you try and update Radarr to the nightly version. Maybe the fix I am thinking of is not yet in the develop release.

**Comment by nriley2** [comment]
@galli-leo after updating to the nightly the error has not occurred, however for the video files (not in individual folders) in the drone factory folder still come up as unknown movie for all of them, I believe I just have to put them in folders but was unsure if it's supposed to be intended or not as they're all labeled to format

**Comment by galli-leo** [comment]
@nriley2 It should theoretically work, though drone factory is not really the recommended work flow.

**Comment by nriley2** [comment]
@galli-leo I assume the recommended workflow is to have them put into folders then bulk import?

**Comment by jonfroese55** [comment]
I'm having the same issue with drone factory how do I update to nightly edition? It was working before?

Request Failed: Sequence contains no matching element

System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at NzbDrone.Api.Commands.CommandModule.StartCommand(CommandResource commandResource) in C:\projects\radarr-usby1\src\NzbDrone.Api\Commands\CommandModule.cs:line 43
   at NzbDrone.Api.REST.RestModule`1.<set_CreateResource>b__41_0(Object options) in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:line 161
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)
