### ISSUE TITLE
Need an Add All button

### ISSUE THREAD

**Issue by atwright147** [Radarr/Radarr#1498]
**Description:**

I think you need an "Add All" button at the bottom (maybe top too) of the **"Import Existing Movies On Disk"** screen. For anybody with an sizeable existing collection, clicking each add button in turn is no fun.

For anybody who also found this problem, you can open the dev tools in Chrome (probably other browsers too) and type the following after everything has downloaded and is visible:

```js
$$('.x-add').forEach(item => { item.click() })
```

The above will find all of the add buttons and click each one individually.

**Radarr Version:**

`0.2.0.654`

**Logs:**

N/A

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by atwright147** [comment]
Hmmm, or did I use the wrong screen?

What is the difference between **"Bulk Import Movies"** and **"Import Existing Movies On Disk"**?

**Comment by galli-leo** [comment]
Import Existing Movies On Disk Is kinda deprecated. (Button is removed on the latest nightly). Correct way would be to use Bulk Import. There you can have a nice overview over x items, so you can verify everything is correct for them and then import them.
