### ISSUE TITLE
Update status for Qnap

### ISSUE THREAD

**Issue by Jorman** [Radarr/Radarr#1499]
Hi, just an information.

I installed the qnap qpkg of sonar, I set it up to autoupdate and to use the develop branch

I've the 0.2.0.654 version and I see some commit after the version that I've, so I checked the update log but no trace of any logs, so I manually downloaded the qpkg and I decompress it into a folder and I noticed that I my installation miss one folder NzbDrone.Update. So I copied this folder on right place on nas but for now any new update.

Is normal or I miss somethings?

Tnx a lot, Chry

**Comment by galli-leo** [comment]
Currently 0.2.0.654 is the latest stable version, so you are not missing something. We do have nightly versions, but those can be a bit unstable sometimes. I do not know much about qnap, but maybe you could ask the package author to add the nightly versions?

**Comment by Jorman** [comment]
Tnx for the info, you mean also the develop version, right?
I think, but for more info I need to ask to owner of qpkg, that the qupk install only the Radarr and don't interfere with the normal update process.

I ask this because I set develop into the settings -> general -> updates
with automatic and built-in process, and on system -> updates I've this
0.2.0.654 - 18 Apr 2017  develop Installed

But you said that the latest stable is also the same as the develop

All right?

**Comment by galli-leo** [comment]
Yeah latest stable is the same as develop. If you would use nightly, you would get the commits as they pour into the repo.

**Comment by Jorman** [comment]
Ok tnx, so don't matter how many commit I'll see, for example this is the last you made into the develop
Latest commit fccd02a  32 minutes ago @galli-leo galli-leo Merge remote-tracking branch 'origin/develop' into develop

I've to wait the release.
Sorry but I don't know how the update process works, I always thought was a kind of git pull on develop branch

**Comment by galli-leo** [comment]
Correct. This way we can ensure that our commits do not break anything major.
