### ISSUE TITLE
Importing from TMDB gives number instead of root folder

### ISSUE THREAD

**Issue by CInk-Ibrahim** [Radarr/Radarr#1500]
**Description:**

I have added my movie list from themovidedb and also made sure to set correct root folder in list settings. Whenever I import a movie, it writes `/1/` instead of my root folder (`/volume2/CInkstone/Videos, Movies`) depending on which selection I did. (I have 4 root folders and it puts different number for each folder.) 

Trakt list import is working correctly so this only happens for TMDb lists.  Mind that metadata is fetched correctly so only problem is because of the root folder.

You can search for "`Movies' root folder (/1) doesn't exist.`" errors inside the log.

My system is Synology DSM 6.0.

**Radarr Version:**
0.2.0.654

**Logs:**
[radarr.txt](https://github.com/Radarr/Radarr/files/987310/radarr.txt)

**Comment by galli-leo** [comment]
Can you please go into your list settings (for TMDB lists) select another path for each list, save, then edit again, select the correct path, then save again? This is probably because of a known UI issue where the list paths are very finicky (Basically you currently have to deselect and then reselect the list path every time you view them). This will only apply to new movies, so could you try and add a movie to your lists?

**Comment by CInk-Ibrahim** [comment]
Ok, tried two ways;

- I opened each list and set them to something else. Then one by one I set them to correct paths. (By the way I realized the selection seems to say same going from one list to another. Is that what you are talking about?)

- I opened the tmdb set it to something else. Then opened and set it back to the correct path.

In both cases adding new movie from the list ended up with `/5/Adams Doctor Atomic (2008) [imdb-tt1350243]`. 

(I use `{IMDB Id}` for movie folder format. I tried removing it but the problem doesn't go away. )

**Comment by galli-leo** [comment]
@CInk-Ibrahim Ok, maybe it's something else then. Would you be able to open the Radarr database using an sqlite browser (e.g. sqlitebrowser.org, located in AppData directory (http://radarr.video/config) and named nzbdrone.db) and post a picture of the NetImport table?

**Comment by CInk-Ibrahim** [comment]
Here:

<img width="1302" alt="screen shot 2017-05-09 at 23 22 41" src="https://cloud.githubusercontent.com/assets/1660681/25870899/6ea3e39c-350e-11e7-945a-e527341f0b8c.png">

Right now the TMDb set folder name as `/5/`. I guess it cannot convert it properly.

**Comment by galli-leo** [comment]
@CInk-Ibrahim That's kinda bad :/ I will have to investigate that.
