### ISSUE TITLE
Radarr updater flagged as ransom ware

### ISSUE THREAD

**Issue by thezoggy** [Radarr/Radarr#1501]
![radarr](http://zoggy.net/SavUI_2017-05-09_13-55-58.png)
> SONAR.Ransom!gen15 is a heuristic detection designed to detect known variants of the Trojan.Ransomlock family of threats. 

Using: Symantec Endpoint Protection 12.1.6

**Comment by galli-leo** [comment]
Well our updater definitely is not Ransomware. Could you submit it to them here: https://submit.symantec.com/false_positive/?

**Comment by thezoggy** [comment]
submitted for review

**Comment by galli-leo** [comment]
Thank you very much :)

**Comment by thezoggy** [comment]
So far their test came back inconclusive, they want me to submit more Radarr related files now to inspect.

**Comment by galli-leo** [comment]
@thezoggy Can you maybe send them a link to this github page? I mean it's open source so it should be no problem to scan if we do anything bad (which we don't)

**Comment by galli-leo** [comment]
Did you ever hear back from them?

**Comment by thezoggy** [comment]
About the May submission, they came back with:
`Having reviewed the information provided we are unable to reproduce or confirm the issue described.`

To note that I did run into a similar issue again on Nov 6th,
![radarr](http://zoggy.net/SavUI_2017-11-06_15-09-11.png)
> Heur.AdvML.C is a heuristic detection designed to generically detect malicious files using advanced machine learning technology.

I did not submit it for review.
