### ISSUE TITLE
Mark download as failed if no video file is found.

### ISSUE THREAD

**Issue by sm1ddy** [Radarr/Radarr#1502]
Hi All

I'm sure others have encountered this but I can't find a way to fix it.

I've noticed that Radarr has a behaviour where when a download successfully completes (but a video file isn't found), the files will just be left in the download folder. One example is where I had a movie sitting in my download folder but it was a whole bunch of .par files.

I know in Couchpotato that this doesn't occur, I guess it just deletes all those files and tries another release. Anyway can this can be added into Radarr? It's a problem because Radarr eventually fills up the download folder with a bunch of orphaned files.

**Comment by galli-leo** [comment]
IMO and after having this discussed with other people, your download client should be responsible for clearing up files not used by Radarr (I don't know which one you use, but pretty much everyone has this feature). It knows best about the files it downloaded and thus should be responsible.

However, we should look into marking the download as failed, if we do not find a video file and thus try another release.

**Comment by sm1ddy** [comment]
I disagree.

As far as the download client is concerned, it has successfully downloaded the file that Radarr requested. It is then up to Radarr to handle post-processing including the scenario that the files are incompatible and should be discarded.

**Comment by galli-leo** [comment]
AFAIK Sab certainly has that feature. You can set those Sab settings just for the Radarr label as far as I am aware.

**Comment by sm1ddy** [comment]
I've taken a look inside Sab and can't find it.

On the movies category, I've set Processing to +delete but it doesn't seem to remove the files. Maybe there is something else but I can't think of what the logic here should be?
Are we trying to remove any files that aren't video files? Or maybe force sab to completely delete all files after post-processing (which doesn't seem to work)?

Just my 2 cents but I still think radarr should be handling any release that it has requested and has been successfully downloaded. It should be part of radarr's post-processing to look at the files and throw away what it can't handle. Personally, I don't see how it makes sense to define these error handling post-processing rules in whatever download manager is being used. Particularly when it is not a download error but radarr requesting something it can't import.

Thanks for radarr though, it's an awesome bit of software.

**Comment by Grimeton** [comment]
![grafik](https://cloud.githubusercontent.com/assets/2773919/25973814/0de92744-36a6-11e7-9b64-889be75343b1.png)

So according to Radarr the job should fail as there is no video. Then the job should be removed from history and the files should be gone. 

If that doesn't work, you want a post processing script.

Cu

**Comment by sm1ddy** [comment]
Thanks for the tip mate.

I do have Completed Download Handling on (with no post-processing script) but it doesn't seem to do the cleanup in some circumstances.

Still, I think Radarr could handle this more elegantly than mucking around with downloader settings or a custom post-processing script. Never had this problem in Sonarr or CP.

Instead, I've just opted to create a scheduled script that wipes the download folder of old files.
