### ISSUE TITLE
Special char during search phase

### ISSUE THREAD

**Issue by Jorman** [Radarr/Radarr#1505]
Hi, in my country we use some extra char like ' so a movie like

> Allied

In my country the title is

> Allied: Un'ombra nascosta

Radar during a search remove the : but remove also the ' and don't insert a blank space so the search this

> Found 0 releases from Demonoid for: allied unombra nascosta 2016

But need to search

> allied un'ombra nascosta 2016

or

> allied un ombra nascosta 2016

I don't know what is better

Chry

**Comment by galli-leo** [comment]
When you search on Demonoid yourself do you get the same results with allied un'ombra nascosta 2016 and allied un ombra nascosta 2016?

**Comment by Jorman** [comment]
Yep, same results with or without ' not only on Demonoid.
Demonoid was just an example :D

So : is removed and ' must be replaced with a space?

**Comment by galli-leo** [comment]
@Jorman Yeah I should probably add that ' is replaced by a space

**Comment by Jorman** [comment]
Tnx man!

**Comment by djoole** [comment]
Yeah replacing apostrophe by a space instead of removing it should to the trick.
