### ISSUE TITLE
Movie List - Empty

### ISSUE THREAD

**Issue by davidbonnici1984** [Radarr/Radarr#1506]
I filtered the movies to Missing and I deleted the only one I had and this happened.

![image](https://cloud.githubusercontent.com/assets/905774/25910743/c05275ac-35b1-11e7-9a0c-4698a16c7c14.png)

Version: Radarr Ver. 0.2.0.654

Logs: No logs related to this issue...

**Comment by davidbonnici1984** [comment]
![image](https://cloud.githubusercontent.com/assets/905774/25911083/d9412774-35b2-11e7-9569-666789af2709.png)

I fixed it by deleted the entry in the local storage set as "Missing". 

![image](https://cloud.githubusercontent.com/assets/905774/25911113/f462e236-35b2-11e7-8fd4-ef5ac3e31094.png)

**Comment by galli-leo** [comment]
Yeah this is a known issue, there's an issue already open on here (can't currently find it though :/), so gonna close this as a duplicate.

**Comment by edsai** [comment]
Ran into this just now. Clearing cookies fixed it.

**Comment by rodalpho** [comment]
Same here, clearing cookies fixed it. For a minute there I thought I had accidentally deleted my entire library!
