### ISSUE TITLE
Deleted Movie Added Back to my list

### ISSUE THREAD

**Issue by champs777** [Radarr/Radarr#1507]
**Description:**
I add a movie I want.  I click add and search.  Radarr finds it.  Perfect!  Movie is downloaded.  I move the movie to another location.  I open Radarr and delete the movie from my list.  I no longer need it ( i now have it) .  Later that day it just gets readded back in.

Question:
Once I get a movie I want, how do i remove it so it no longer downloads?  I think I am doing something wrong.

Thank you for your help!

**Radarr Version:**
0.2.0.654

**Logs:**
I think this might be a user error.

**Comment by champs777** [comment]
Radarr is really amazing BTW!  I love it!

**Comment by Grimeton** [comment]
Hi,

are you pulling in some rss lists containing movies to be downloaded? Maybe it's on one of those lists?

Is the movie still in the list of your movies? And if yes, is it still monitored? If that's the case and the file vanishes, radarr downloads it again.

cu

**Comment by champs777** [comment]
All good questions!  Thanks for the follow up!

1.  The only place I am pulling movies from is my IMDB watchlist.  The movies that I have been having issues with are old movies.  Nothing that are on the IMDB watchlist.
2.  I don't have any other RSS feeds.
3.  As soon as the movie finishes downloading, I go to my Radarr folder.  I cut and move the movie from here to my movies folder.  As soon as I move the movie, I delete it from my list of movies.  Since I have it I don't want it again.  Within the day, it is back again.  The only way I have found to prevent this is to enable "Exclude movie from Auto List Import?".  If I do this, it prevents it from coming back.

**Comment by galli-leo** [comment]
@champs777 In that case Radarr is working as intended. The movie get's added back because it is on one of your lists. Radarr does not know which movies you don't want imported from the lists unless you tell it to exclude specific movies (which you can do via 3.).

**Comment by champs777** [comment]
Ok.  Let me make sure I understand this.

**Scenario 1**
I add, MovieA. IMDB watchlist
MovieA gets imported (automatically).
MovieA gets downloaded.
I move MovieA to my movies folder. 
Do I need to now remove it from my IMDB watchlist so it doesn't get imported again?
I guess my other option is to Exclude movie from Auto List Import?

**Scenario 2**
This movie is not added to my IMDB Watchlist
I add MovieA directly through Radarr.
MovieA gets downloaded.
I move MovieA to my movies folder. 
How do I prevent MovieA from being downloaded again?  Currently the only way is to add it to Exclude movie from Auto List Import.

Hopefully this is clear.  Let me know.

Thank you again for your help!  I really love and appreciate all the hard work on the application!

**Comment by Grimeton** [comment]
The basic idea here is that Radarr manages the folder that contains all the movies you have and that those movies are marked in Radarr as available and remain in that folder and in Radarr's database.

So if you use Radarr in a totally different way and move the file out of the way, then just delete the movie from Radarr's database. Once that's done and it shows up again then we either have a bug - which I doubt, as you wouldn't be the only one complaining - or it is in one of your RSS feeds and gets readded again because of that.

Cu

**Comment by champs777** [comment]
Thank you Grimeton for your assistance.  I really do appreciate you answering my questions.

So what you are saying above it point Radarr to my "Movies" folder.  Have it download, put in this folder, and manage it?  Here is a question then.  If I download a movie and have it saved to this folder.  I watch the movie and then no longer want it, do I then remove it from Radarr?  If I just delete it, then Radarr will just re download right?

I want to use Radarr the way the tool is intended, however, I am trying to figure out exactly how it is intended.

Thanks for the help.

**Comment by Grimeton** [comment]
Hi,

when you delete a movie in radar you can also delete the files. They're either thrown away or end up in your recycle folder (if set). Anyway. They're gone. The thing is: If the movie is again pulled in via RSS sync, it will show up again, so it's a good idea to either delete the movie from the rss list, OR delete the file from the disk, and mark the movie as unmonitored and leave it in Radarr's database.

Both ways exist, but deleting it everywhere and from the rss list seems much more clean to me.

Cu
