### ISSUE TITLE
Cant Update App - Looks to be Permission? 

### ISSUE THREAD

**Issue by Parkie** [Radarr/Radarr#1508]
I am trying to do an update on the app. I am using the nightly updates. I am currently on Radarr Ver. 0.2.0.654 and trying to go to the latest nightly. When I go to do the update I get the following in my logs and the app never updates. 

[2017.05.10-16.52.txt](https://github.com/Radarr/Radarr/files/991217/2017.05.10-16.52.txt)

**Comment by Grimeton** [comment]
Hi,

yeah that's a permission problem. The updater should be run as root (admin) with elevated rights or else it is not able to overwrite the files. 

Where did this app package come from? Can't you just update the package and go on?

Cu

**Comment by Parkie** [comment]
I downloaded this from GitHub, for OS X and moved it into the Applications folder. I am an admin on the computer. Now sure what you mean update the package and go on? I am trying to update it and getting the errors. Sorry I am a bit new to this.

**Comment by Grimeton** [comment]
Hi,

I meant you just download the new release and copy it to your Applications folder.

Also. Just being admin on OS X doesn't mean the process runs elevated. That only happens when the username/password window pops up when you start something. 

Cu

**Comment by Parkie** [comment]
I downloaded developer, then changed it to the nightly branch. I am trying to update now that way but it won't... where can I just grab that update manually? I didn't see it under branches on the GH site.

**Comment by Grimeton** [comment]
I'm not sure if it's part of the bigger plan to update the .app package in place.

You could try to run the .app elevated and then start the updater. Let's see how that goes.

cu

**Comment by Parkie** [comment]
I tried that, I used terminal and ran it with Sudo I still can't seem to update this, it used to work I really don't know what I am missing here.

**Comment by Grimeton** [comment]
Hi,

frankly: me neither.

Cu

**Comment by Parkie** [comment]
I appreciate your help... anyone else having this? What permissions should I make the app? I am half tempted to install this on a linux virtual instead of dealing with OS X.

**Comment by galli-leo** [comment]
@Parkie Can you try and move the Radarr app to your Applications folder in your home directory? (So under /Users/yourusername/Applications). Then start it from there and try to update?

**Comment by galli-leo** [comment]
Maybe your /Applications folder has some strange permissions

**Comment by Parkie** [comment]
Tried it, I moved it to just my user folder. I am back these errors: 

17-5-11 17:34:59.7|Trace|DiskProvider|Checking path /Users/~/Radarr.app/Contents/MacOS/Sonarr for symlink returned error ENOENT, assuming it's not a symlink.

**Comment by Grimeton** [comment]
Is it just me or does /Users/~/ look odd?

**Comment by Parkie** [comment]
Sorry I used ~ in place of my real username. /Users/admin/....

**Comment by Grimeton** [comment]
Can you please provide a fresh log?

**Comment by Parkie** [comment]
[2017.05.11-18.45.txt](https://github.com/Radarr/Radarr/files/994604/2017.05.11-18.45.txt)

**Comment by Grimeton** [comment]
So there is something going on here.

When stuff is downloaded it's placed in /var.
When the updater checks for the files it checks in /private/var.

Not sure if that's a symlink or something but this cannot work.

**Comment by galli-leo** [comment]
@Grimeton Shouldn't be as the call that fails is only at the very end, when it tries to set the execute flag for the OSX binary.

**Comment by galli-leo** [comment]
@Parkie Can you try and run this in a terminal?:
`sudo chmod +x /Path/To/Radarr.app/Contents/MacOS/Radarr`

**Comment by Parkie** [comment]
I tried, however, I don't have a "radarr" in the MacOS Directory, I know they are EXE's but this all runs when I double click radarr.app... I have: 
Radarr.exe
Radarr.exe.config
Radarr.exe.mdb

I do have a "sonarr" file with no extension in that directory, should I run it on that?

**Comment by galli-leo** [comment]
@Parkie Yeah try running it on that (I thought we renamed the binary before the release you are currently on)

**Comment by Parkie** [comment]
I did that, I attached the new log file. It didn't update. 

[2017.05.12-10.33.txt](https://github.com/Radarr/Radarr/files/997015/2017.05.12-10.33.txt)

**Comment by Vortec4800** [comment]
FWIW I am having a similar issue. I've attached my log file as well. Seems to be the exact same problem.

[2017.05.12-13.54.txt](https://github.com/Radarr/Radarr/files/997663/2017.05.12-13.54.txt)

**Comment by psi70y** [comment]
I have a similar problem.  MacOSX and have v0.2.0.654 installed.
Trying to install 0.2.0.696 on develop branch and here is my log which fails

> 17-5-13 09:07:29.3|Info|InstallUpdateService|Deleting old update files
17-5-13 09:07:29.3|Info|InstallUpdateService|Downloading update 0.2.0.696
17-5-13 09:07:40.2|Info|InstallUpdateService|Verifying update package
17-5-13 09:07:40.5|Info|InstallUpdateService|Update package verified successfully
17-5-13 09:07:40.5|Info|InstallUpdateService|Extracting Update package
17-5-13 09:07:41.6|Info|InstallUpdateService|Update package extracted successfully
17-5-13 09:07:41.6|Info|BackupService|Starting Backup
17-5-13 09:07:41.9|Info|InstallUpdateService|Preparing client
17-5-13 09:07:41.9|Info|InstallUpdateService|Starting update client /var/folders/y2/dq9mkxx56w70z6sl5pmxn_n00000gn/T/radarr_update/Radarr.Update.exe
17-5-13 09:07:41.9|Info|InstallUpdateService|Radarr will restart shortly.
17-5-13 09:07:42.0|Info|InstallUpdateService|Updater Arguments: 1059 /var/folders/y2/dq9mkxx56w70z6sl5pmxn_n00000gn/T/radarr_update /Applications/Radarr.app/Contents/MacOS/Radarr.exe /nobrowser
17-5-13 09:08:09.9|Info|Bootstrap|Starting Radarr - /Applications/Radarr.app/Contents/MacOS/Radarr.exe - Version 0.2.0.654
17-5-13 09:08:14.5|Info|MigrationLogger|*** Migrating data source=/Users/<username>/.config/Radarr/nzbdrone.db;cache size=-10485760;datetimekind=Utc;journal mode=Truncate;pooling=True;version=3;Full FSync=True ***
17-5-13 09:08:14.7|Info|MigrationLogger|*** Migrating data source=/Users/<username>/.config/Radarr/logs.db;cache size=-10485760;datetimekind=Utc;journal mode=Truncate;pooling=True;version=3;Full FSync=True ***

**Comment by galli-leo** [comment]
@psi70y @Parkie @Vortec4800 Pretty sure what's happening now. We changed the binary name (from Sonarr to Radarr) in .692. This causes osx to be confused because it's still searching for the binary called Sonarr. The only current workaround is to redownload the application bundle from the releases page. I will try to come up with a fix, but I don't know if that's possible. Sorry about the inconvenience :/ (@Parkie the best way to test this is to actually download .692 bundle and see if you can upgrade to .696 from that)

**Comment by Vortec4800** [comment]
The weird thing is that I actually did download the latest bundle from the releases page and installed it directly and I'm still having the error launching the app. Is there a launchd cache I need to clear or something?

**Comment by lyrad87** [comment]
@Vortec4800 May not be related at all but have you tried clearing your local storage? It sounds like an issue I've encountered in the past and that fixed it for me. But once again, I have no idea if that is even the issue you are having.

**Comment by galli-leo** [comment]
@Vortec4800 Oh yeah, the latest two bundles got slightly corrupted by our build system, so the binary is missing the executable permissions. You have to execute: ’chmod +x /path/to/Radarr.app/Contents/MacOS/Radarr’

**Comment by galli-leo** [comment]
@Vortec4800 @Parkie @psi70y I fixed the updater problem on the latest nightly. If you do not want to manually download the new update, set branch to nightly in Settings -> General and then update to the new version (live in a few minutes).
