### ISSUE TITLE
Renaming existing files does not change folder name

### ISSUE THREAD

**Issue by ChrisColotti** [Radarr/Radarr#1509]
**Description:**

I am playing with the latest release and as a fan of Sonarr it's great to have TV and movie apps look and feel the same!

I am testing renaming existing files and the re-name works, but it stays relative to the original folder name.  Unlike a new download where the folder name and file name are re-written existing ones only re-write the movie file.  It would be great if it also updated the folder name too.

Also a library wide rename might be cool too.

Check first that your problem is not listed in our wiki section:
* https://github.com/Radarr/Radarr/wiki/Common-Problems
* https://github.com/Radarr/Radarr/wiki/FAQ

Provide a description of the feature request or bug here, the more details the better. 
Please also try to include the following if you are reporting a bug

**Radarr Version:**
Latest

**Logs:**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by galli-leo** [comment]
Are you on nightly or develop branch in settings? We had to introduce this as a new feature, since Series folders (Movie folders) aren't supposed to change in Sonarr.

**Comment by ChrisColotti** [comment]
Since I am using the Docker version it was set to "Develop" with a warning about not using that for docker  LOL!

I can update to develop or should I wait for a new docker image and then update?

BTW I think this branch is an awesome idea to have UI/usability synergy between movies and TV apps!

**Comment by galli-leo** [comment]
@ChrisColotti You would have to switch the Docker image. The problem with docker is and the reason for the warning, that every time you restart the image, it resets the executable files to the version of the docker image. So if you update the docker image the exes get updated, but stay that way only until you restart your image. Normally this would not be that big of a deal, but if we change the database layout between version (which we did), the old exes restored by your docker image cannot be read anymore. So you would have to switch to the "nightly" docker image by hotio (you can find a link under the settings). Though I want to push the feature to develop later today anyways, so you can just wait a bit.

**Comment by ChrisColotti** [comment]
Cool....I can just wait a bit for the develop update.  Currently I loaded the "latest" docker image so not sure if that is updated based on the regular "develop" branch which would = latest docker.

**Comment by ChrisColotti** [comment]
I just installed the update and the rename preview does not appear to be changing the folder name while I am testing.

See below it shows the Folder naming pattern but it is not adjusting the folder name to be as indicated.  I'm not sure if this is actually working or not

Your movie may be moved; see the paths below
Folder Naming pattern: {Movie Title} ({Release Year})
Naming pattern: {Movie.Title}.({Release Year}).{Quality.Title}.{MediaInfo.Simple}

 /media/Movies/Collateral.Beauty.2016.1080p.Blu-ray.DTS/Collateral.Beauty.2016.1080p.Blu-ray.DTS.mkv
 /media/Movies/Collateral.Beauty.2016.1080p.Blu-ray.DTS/Collateral.Beauty.(2016).Bluray-1080p.x264.DTS.mkv

**Comment by galli-leo** [comment]
@ChrisColotti You have to change the path of the movie to be dynamic. You can do that when you edit the movie.
