### ISSUE TITLE
Unable to add movies with special characters like : ,  or '

### ISSUE THREAD

**Issue by teshiburu** [Radarr/Radarr#151]
I am currently unable to add movies with special characters, rogue one worked but some others ive tried havent e.g.

http://www.imdb.com/title/tt5471574/
http://www.imdb.com/title/tt4789048/

I have tried to add these via both name or imdb:tt5471574 and still no joy :( 

Im not sure what causes them to fail but rogue one worked? maybe because i only searched for "rogue one"?

**Comment by onedr0p** [comment]
Both of those movies have `Status: Pitch` on their IMDB page.
