### ISSUE TITLE
Radarr can't browse network drive even though UNC is used

### ISSUE THREAD

**Issue by piejanssens** [Radarr/Radarr#1511]
Radarr Version: v0.2.0.654
Platform: Windows
Running as a service

When doing Bulk import or import all existing movies I cannot use my network path.

![image](https://cloud.githubusercontent.com/assets/829098/25944641/53714d4e-3644-11e7-89ea-4e76c2b96896.png)

**Comment by piejanssens** [comment]
https://github.com/Sonarr/Sonarr/wiki/FAQ#why-cant-nzbdrone-see-my-files-on-a-remote-server

**Comment by Canberra2005** [comment]
Hello,
I seem to have the same problem:
I am running WIN 10 and my movies are on a network QNAP NAS.
The path I am putting in is:
\qnap-koorong\multimedia\video\movies

I keep getting the same error message: path does not exist

Any ideas?
