### ISSUE TITLE
{Original Title} as Movie Folder Format does not work as expected

### ISSUE THREAD

**Issue by desimaniac** [Radarr/Radarr#1513]
**Description:**
Was expecting the folder name to be `The.Space.Between.Us.2017.1080p.BluRay.H264.AAC-RARBG` like in the example shown, but instead it was `The Space Between Us 2017` (the format tag does work for filenames).

![image](https://cloud.githubusercontent.com/assets/5501908/26018425/b1021e72-3723-11e7-80c7-f725b8c6a4a9.png)

**Radarr Version:** 0.2.0.696

**Logs:**
Both debug and trace logs: https://gist.github.com/desimaniac/a38075a12b8fefb11f3e3097f7feef41

PS. {Original Filename} tag gives an error even though it's listed on the wiki.

**Comment by galli-leo** [comment]
You need to enable a few things for that to work:
1. Automatically Rename Folders
2. And change the Movie Paths of these movies to dynamic
(optional, but preferable) 3. Disable Movie Paths Default to Static
This way new movies have automatically dynamic paths.
