### ISSUE TITLE
Folder Re-Naming not working as expected

### ISSUE THREAD

**Issue by ChrisColotti** [Radarr/Radarr#1514]
**Description:**
I just installed the update and the rename preview does not appear to be changing the folder name while I am testing.  The previous question I had on this was closed but it does not appear to be working.

See below it shows the Folder naming pattern but it is not adjusting the folder name to be as indicated. I'm not sure if this is actually working or not

Your movie may be moved; see the paths below
Folder Naming pattern: {Movie Title} ({Release Year})
Naming pattern: {Movie.Title}.({Release Year}).{Quality.Title}.{MediaInfo.Simple}

/media/Movies/Collateral.Beauty.2016.1080p.Blu-ray.DTS/Collateral.Beauty.2016.1080p.Blu-ray.DTS.mkv
/media/Movies/Collateral.Beauty.2016.1080p.Blu-ray.DTS/Collateral.Beauty.(2016).Bluray-1080p.x264.DTS.mkv

Once the rename runs the file name still changes but the folder does not.

Check first that your problem is not listed in our wiki section:
* https://github.com/Radarr/Radarr/wiki/Common-Problems
* https://github.com/Radarr/Radarr/wiki/FAQ

Provide a description of the feature request or bug here, the more details the better. 
Please also try to include the following if you are reporting a bug

**Radarr Version:**
0.2.0.696

   ###**Logs:**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by ChrisColotti** [comment]
Forget it....did not see the "Static Path" option....

**Comment by desimaniac** [comment]
You can click "close ticket" at the bottom if you figured it out.
