### ISSUE TITLE
Empty folders not being removed and incomplete renames

### ISSUE THREAD

**Issue by desimaniac** [Radarr/Radarr#1515]
**Description:**
Two issues here but related:

1. With "create empty folder" option selected, a temporary folder (`Get.Out.2017.-Radarr`) is created. But after download occurs to another folder (`Get.Out.2017.720p.Bluray.x264.AAC-RARBG`), the first folder is not removed.

2. Decided to tweak the movie folder format a bit and ran a rename on the same movie. During rename function, a new folder (`Get.Out.2017.720p.Bluray.x264.AAC-RARBG`) was created but the file was never moved to it. 

**Radarr Version:** 0.2.0.696

**Logs:**
Both debug and trace logs: https://gist.github.com/desimaniac/334d829c03c162de7bd52a3a61667de1

**Comment by galli-leo** [comment]
@desimaniac Regarding 1., did you have any other files besides the video file in the original folder? We do not delete folders unless they are empty.
Regarding 2., the two folders seem to be the same?

**Comment by mattya802** [comment]
Is deleting other nonsense files in the original folders something that could be done? There's almost never JUST the mkv/mp4 in there.

**Comment by galli-leo** [comment]
@mattya802 That is definitely something that can be done, but not something I want to do without significant safeguards. Will probably come once we implement moving additional files (such as subtitles or .nfo)

**Comment by desimaniac** [comment]
I think we can close this, as the new folder renaming options in Radarr are actually working well. Just one point to note, though, is that when changes are made to folder renaming enabled/disabled, Radarr must be restarted, or else the changes don't take.
