### ISSUE TITLE
RSS Feed Handling 

### ISSUE THREAD

**Issue by jun6lee** [Radarr/Radarr#1516]
Attempting to parse an rss feed [e.g.; zooqle search results], the below error is encountered. I don't know if it's the feed not being shaped right, or an error, but the feed looks okay.

Some of the log shows reference to directories that don't seem right (not relative paths).
Since I'm running Radarr on a QNAP, this too may be adding complication.

For the below example, I've added a search of vppv to zooqle.com and sorted by time so that the latest is on top. https://zooqle.com/search?q=vppv&s=dt&v=t&sd=d&fmt=rss 

I've since then added Realive to Radarr, it gets picked up by hourly sync, but stalls at:
"Couldn't add report to download queue. Realive (2016) 1080p BrRip x264 - VPPV: Invalid torrent file specified"

Full log file attached below:

**Radarr Version:**
latest-develop [0.2.0.696 at time of post]

**Logs:**
https://pastebin.com/6Js8tnKP

**Comment by galli-leo** [comment]
I don't see the error with the RSS feed? the only error I see is that the TorrentFile is broken, which would explain why it couldn't get added.

**Comment by jun6lee** [comment]
Interesting.
 https://zooqle.com/download/w3daz.torrent
For that example, I've tested manually that the torrent in the RSS feed is valid.
