### ISSUE TITLE
The application “Radarr” can’t be opened.

### ISSUE THREAD

**Issue by realdannys** [Radarr/Radarr#1518]
I'm getting "The application “Radarr” can’t be opened." on macOS. Have tried turning off gatekeeper and resetting permissions of app but neither having any affect. Found old reports for this but stated it was fixed.

I have tried the last two releases

**Comment by galli-leo** [comment]
@realdannys Can you open a terminal and run the following command:
`sudo chmod +x /Path/to/Radarr.app/Contents/MacOS/Radarr`.

**Comment by realdannys** [comment]
That got it, thanks Leonardo!

**Comment by galli-leo** [comment]
Sorry about that, but our build system sometimes doesn't add the executable permissions to the osx binary :/

**Comment by fabriziobertoglio1987** [comment]
just for future reference

you downloaded `Radarr.develop.0.2.0.1450.osx-app.zip`

You unzipped the file and moved `Radar` folder to the `~/Applications` folder

then you need to `cd ~/Applications/Radarr.app/Contents/Macos` and `sudo chmod +x Radarr` to make the file executable. 

Thanks for the awesome project
