### ISSUE TITLE
Add G_Scene to indexer flags. Makes it possible to ignore / require or even upgrade to scene releases

### ISSUE THREAD

**Issue by roquemore92** [Radarr/Radarr#1519]
I'm using Radarr to grab movies primarily from PassThePopcorn. I prefer to get P2P releases, since they are typically better quality and eventually can become Golden Popcorn, while Scene releases almost never do. The problem is that Scene releases usually come out before P2P releases, but since Radarr has already grabbed the Scene release, it will completely ignore the P2P release.

Looking at the options under PTP in Radarr, I can Prefer Golden Popcorn, Prefer Scene, Require Approved, and Require Golden Popcorn. Would it be possible to add a switch "Ignore Scene?" I don't want to "Require Golden Popcorn" because usually it can take several months for a movie to get Golden Popcorn, and some movies never get a GP release at all, but I would still prefer the P2P release since it is typically a higher quality.

**Comment by galli-leo** [comment]
There is an option to not prefer scene, but if it's the only release it will be downloaded regardlessly. Your best bet is to add a delay profile (Settings -> Profiles, in combination with not prefer scene), so that Radarr waits x amount of hours before downloading the scene release regardlessly.

**Comment by roquemore92** [comment]
I would like to ask that this not be closed, and added as a feature request. Sometimes there can be delays of hours, or sometimes days or weeks between Scene and P2P releases. It is not something that can easily be fixed by adding the delay to the profile since there is no set time that it would need to wait. Manually downloading everything would be a better option than setting a delay.

Radarr is already detecting whether the release is Scene, and can require certain flags, this would just be another option based on the flags that are already read from the torrent. I'm guessing just another If statement in the GetRequest function in PassThePopcornRequestGenerator.cs. Adding something to the filter to to ignore Scene releases just like there is a filter to ignore everything except GoldenPopcorn.

Playing with the PTP URLs, it looks like setting filter = "&scene=0" should remove Scene releases from the list. Not 100% sure, but that's what it looks like.

**Comment by galli-leo** [comment]
Gotcha. Sorry I though you meant it to work across all indexers not only PTP.

**Comment by roquemore92** [comment]
Thank you very much!

**Comment by Grimeton** [comment]
What about using certain keywords in the "must contain" and "must not contain" sections of the indexer?

**Comment by roquemore92** [comment]
Whoops...hit the close button instead of comment.

For the "must not contain" list, I do have a bunch of groups in there, but I can't seem to find a fully up to date list anywhere. Even if I did, the "must not contain" list would probably have to be manually updated every week or so. Since most private trackers have a special flag if a release is Scene, that is probably the easier method.

**Comment by Quiksmage** [comment]
It'd be great to integrate "scene" into the profiles eventually. So that someone could make a custom profile that uses scene as a quality, with a cutoff of goldenpopcorn, for instance.
web-dl (hc subbed) < 720p BluRay <scene 1080p bluray < P2P 1080p bluray < 720p Goldenpopcorn < 1080p Goldenpopcorn 

@galli-leo Is this a possibility with the new profile manager i saw a video of a while back?

**Comment by galli-leo** [comment]
@Quiksmage Yeah that is the idea. (I also want to integrate scene as an indexer flag.) With rhe profilinator you could maybe add scores for the individual flags an set a minimum score before cutoff is met.

**Comment by Quiksmage** [comment]
I'm excited for that scoring idea :)

**Comment by roquemore92** [comment]
@galli-leo until this gets implemented, is there anything I can do on my end to change that filter? If I could even just change the the "Require Golden" option to have &scene=0 instead of &scene=2 as a temporary workaround that would be great. I'm running on Windows from the .exe installer. I can find where in the source to edit this, but not in the compiled and installed files.

Thanks!

**Comment by galli-leo** [comment]
@roquemore92 You cannot really edit the files. I could add an extra parameters field to all indexers though.

**Comment by jtpavlock** [comment]
I would like to input my own personal workaround: PassThePopcorn has lists of scene groups in their wiki, and I noticed all scene encodes usually end with .x264-SCENEGROUP or something similar. Thus, with that info and a little vim magic I create the following list to add to the "must not contain" section

`-0MNiDVD, -0TV, -1920, -2HD, -2PaCaVeLi, -420RipZ, -433, -4FR, -4HM, -4kHD, -7SinS, -A4O, -aAF, -AaS, -ABEZ, -ABD, -ACCLAIM, -ADHD, -ADMiRALS, -AEGiS, -AEN, -AEROHOLiCS, -AFO, -aGGr0, -AiRFORCE, -AiRWAVES, -ALDi, -ALLiANCE, -AMIABLE, -AMBiTiOUS, -AMSTEL, -ANARCHY, -aNBc, -ANGELiC, -ANiHLS, -ANiVCD, -ApL, -AQUA, -ARCHiViST, -Argon, -ARiGOLD, -ARiSCO, -ARiSCRAPAYSiTES, -ARROW, -ARTHOUSE, -ASAP, -AsiSter, -aTerFalleT, -ATS, -AVCDVD, -AVCHD, -AVS720, -aWake, -AzNiNVASiAN, -AZuRRaY, -BaCKToRG, -BaCo, -BAJSKORV, -BAKED, -BaLD, -BALLS, -BAND1D0S, -BARGE, -BATV, -BAVARiA, -BAWLS, -BBDvDR, -BDA, -BDGRP, -BDP, -BestHD, -BeStDivX, -BETAMAX, -BFF, -BiA, -BiEN, -BiERBUiKEN, -BiFOS, -BiGBruv, -BiGFiL, -BiRDHOUSE, -BLooDWeiSeR, -BountyHunters, -BOSSLiKE, -BOW, -BRASTEMP, -BRDC, -BREiN, -BrG, -BRICKSQUaD, -BRiGANDBiL, -BRMP, -BRUTUS, -BULLDOZER, -BURGER, -BWB, -c0nFuSed, -C4TV, -CAMELOT, -CAMERA, -CarVeR, -CBGB, -CCAT, -CDP, -Centropy, -CFE, -CFH, -CG, -Chakra, -CHaWiN, -CHRONO, -CiA, -CiELO, -CiNEFiLE, -Cinemaniacs, -CiNEMATiC, -CiNEVCD, -CiPA, -CiRCLE, -CiTRiN, -CLASSiC, -CLiX, -CLUE, -CME, -CNHD, -cNLDVDR, -COALiTiON, -COCAIN, -COMPRISED, -COMPULSiON, -CONDITION, -CONSCiENCE, -Counterfeit, -CoWRY, -CRiMSON, -CROSSBOW, -CROOKS, -CRUCiAL, -CTU, -CULTXviD, -CYBERMEN, -D0PE, -D3Si, -DAA, -DAH, -DASH, -DATA, -DcN, -DCP, -DDX, -DEADPiXEL, -DEADPOOL, -DEAL, -DeBCz, -DeBijenkorf, -DEFACED, -DEiMOS, -DEiTY, -DEMAND, -DEPRAViTY, -DERANGED, -DFA, -DGX, -DHD, -DiAMOND, -DiCH, -DIE, -DigitalVX, -DIMENSION, -DioXidE, -DiSPLAY, -DiSPOSABLE, -DivBD, -DiVERGE, -DiVERSE, -DiVXCZ, -DMT, -DNA, -DnB, -DNR, -DOCUMENT, -DOMiNATE, -DOMiNiON, -DOMiNO, -DoNE, -DoR2, -DOWN, -DPiMP, -DRABBITS, -DREAMLiGHT, -DROiDS, -DTFS, -DvF, -DVL, -DvP, -EDRP, -EDUCATiON, -ELiA, -EMERALD, -EPiSODE, -ERyX, -ESPiSE, -ESPN, -ETACH, -EViLISO, -EVOLVE, -EwDp, -EXiLE, -EXIST3NC3, -EXT, -EXViD, -EXViDiNT, -FA, -FADE, -FAiLED, -FAIRPLAY, -FEVER, -FFM, -FFNDVD, -FiCO, -FiHTV, -FilmHD, -FIXIT, -FL, -FLAiR, -FLAiTE, -FLAME, -FliK, -FmE, -FoA, -FORBiDDEN, -FoV, -FQM, -FRAGMENT, -FSiHD, -FTC, -FTP, -FUA, -FULLSiZE, -FUtV, -FZERO, -GAYGAY, -GDR, -GECKOS, -GeiWoYIZhangPiAOBA, -GENESIDE, -GENUiNE, -GERUDO, -GFW, -GiMCHi, -GL, -GM4F, -GMB, -GOOGLE, -GORE, -GreenBlade, -GUYLiAN, -GZP, -HACO, -HAGGiS, -HAFVCD, -HALCYON, -HANNIBAL, -HD_Leaks, -HD1080, -HD4U, -HDCLASSiCS, -HDCP, -HDEX, -HDi, -HDMI, -HLS, -HooKah, -HTO, -hV, -iFN, -iFPD, -iGNiTE, -iGNiTiON, -iHATE, -iKA, -iLG, -iLLUSiON, -iLS, -iMBT, -IMMERSE, -iMMORTALS, -iMOVANE, -iNCiTE, -iNCLUSION, -iNFAMOUS, -iNGOT, -iNjECTiON, -INSECTS, -iNSPiRE, -iNSPiRED, -iNTiMiD, -iSG, -iVL, -Jackal, -JACKVID, -JAG, -Japhson, -JAR, -JFKXVID, -JKR, -JMT, -JoLLyRoGeR, -JUMANJi, -KAFFEREP, -KaKa, -KAMERA, -KART3LDVD, -KEG, -KILLERS, -KJS, -KON, -KSi, -KuDoS, -KYR, -LAJ, -LAP, -Larceny, -LAZERS, -LCHD, -LD, -LEViTY, -LiGHTNiNG, -LiNE, -LMG, -LOGiES, -LOL, -LRC, -LUSO, -LPD, -M14CH0, -MainEvent, -MANGACiTY, -MATCH, -MaxHD, -MEDDY, -MEDiAMANiACS, -MELBA, -MELiTE, -METiS, -MHQ, -MHT, -MIDDLE, -MiNDTHEGAP, -MoA, -MoF, -MoH, -MOMENTUM, -MOTION, -MOVEiT, -MVM, -MVN, -MVS, -NANO, -NaWaK, -nDn, -NDRT, -NeDiVx, -NEPTUNE, -NewMov, -NGB, -NGR, -NHH, -NJKV, -NLSGDVDr, -NODLABS, -NoLiMiT, -NORDiCHD, -NOSCREENS, -o0o, -OEM, -OMERTA, -OMiCRON, -OPiUM, -OPTiC, -ORC, -ORCDVD, -ORENJi, -ORiGiNAL, -OSiRiS, -OSiTV, -OUIJA, -P0W4, -P0W4DVD, -PARASiTE, -PARTiCLE, -PaTHe, -PCH, -PFa, -PHASE, -PiRATE, -PiX, -PostX, -PoT, -PREMiER, -PRiNCE, -PROGRESS, -PROMiSE, -PROVOKE, -PROXY, -PSYCHD, -PTi, -PTWINNER, -PUKKA, -PUZZLE, -PVR, -QCF, -QiM, -QiX, -QRUS, -R3QU3ST, -RCDiVX, -RedBlade, -REFiNED, -REGEXP, -REiGN, -RELEASE, -Replica, -REPRiS, -Republic, -REQ, -RETRO, -REVEiLLE, -REVOLTE, -REWARD, -RF, -RFtA, -RiFF, -RiTALiN, -RiTALiX, -RiVER, -ROOR, -ROUNDROBIN, -ROVERS, -RRH, -RTA, -RUBY, -RUNNER, -RUSTED, -RUSTLE, -SAiMORNY, -SAiNTS, -SAPHiRE, -SATIVA, -SBC, -SCARED, -SChiZO, -SCREAM, -SD6, -SECTOR7, -SEMTEX, -SEPTiC, -SERUM, -SFM, -SHOCKWAVE, -SHORTBREHD, -SiNNERS, -SKA, -SLeTDiVX, -SomeTV, -SONiDO, -SPARKS, -SPLiNTER, -SPRiNTER, -SQUEEZE, -SRP, -ss, -SSF, -STRONG, -StyleZz, -SUBTiTLES, -SUM, -SUPERiER, -SuPReME, -SVD, -SVENNE, -sweHD, -SYS, -TAPAS, -TARGET, -TASTE, -TBZ, -TDF, -TEKATE, -TELEViSiON, -TENEIGHTY, -TFE, -TGP, -TheBatman, -ThEdEaDLiVe, -TheFrail, -TheWretched, -TiDE, -Tiggzz, -TiiX, -TLA, -tlf, -TNAN, -ToF, -TOPAZ, -TRG, -TrickorTreat, -TRiPS, -TRUEDEF, -TrV, -TUBE, -TURKiSO, -TVP, -TWCiSO, -TWiST, -TWiZTED, -TXF, -TxxZ, -UBiK, -ULF, -UltraHD, -UMF, -UNiQUE, -UNRELiABLE, -UNSKiLLED, -UNTOUCHABLES, -UNTOUCHED, -URTV, -USi, -VALiOMEDiA, -VALUE, -VAMPS, -(banned), -VCDVaULT, -Vcore, -VETO, -VEXHD, -VH-PROD, -VideoCD, -ViLD, -ViRA, -ViTE, -VoMiT, -vRs, -VST, -VxTXviD, -W4F, -WAF, -WaLMaRT, -WastedTime, -WAT, -watchHD, -WAVEY, -waznewz, -WHEELS, -WHiSKEY, -WHiZZ, -WhoKnow, -WiDE, -WiKeD, -Wizeguys, -WPi, -WRD, -x0DuS, -XanaX, -xCZ, -XMF, -XORBiTANT, -XPERT_HD, -XPRESS, -XR5, -xSCR, -XSTREEM, -XTV, -xV, -XviK, -YCDV, -YesTV, -ZZGtv`

**Comment by galli-leo** [comment]
Not sure if there's more we can do either (besides implementing that list inside Radarr), since AFAIK most indexers don't return if the torrent is scene. Not even sure if PTP does.

**Comment by roquemore92** [comment]
PTP does actually do this. As I mentioned above, currently if you select "Require Scene" it adds the flag "&scene=2" to the search. I tested it a bit and changing that to "&scene=0" does what we're trying to do.

**Comment by galli-leo** [comment]
You are right it is in the response of PTP. I am gonna add it as an Indexer Flag, so you can globally ban it on a profile. (Or upgrade to / from it, or require it, whatever you like)

**Comment by roquemore92** [comment]
Thank you very much!

**Comment by roquemore92** [comment]
With these flags would it also be possible to have the option to upgrade to GP? Or would that be a lot more effort? Just being able to filter out the scene releases would be more than enough.

**Comment by galli-leo** [comment]
It would be the exact same process: You create a custom format, with e.g. Bluray-1080p as a basis (S_Bluray, R_1080), called e.g. Bluray-1080p Golden. Then you could add the golden popcorn flag: I_PTP_Golden. Now you can add that custom format to your quality profile, above the normal Bluray-1080p quality. Radarr will then try to upgrade to Bluray-1080p Golden.

**Comment by galli-leo** [comment]
If you want to know more about how this works, see the pdf in the description of the Metis Project.

**Comment by roquemore92** [comment]
Awesome! Thanks for all the great work you do on this project!

**Comment by mmcdole** [comment]
The ability to set a profile that specifies "I_PTP_Golden" would be a dream!  Very much looking forward to this.

**Comment by jtpavlock** [comment]
To add to this, does radarr only use RSS to find new releases? Or will it periodically also search missing profiles? I say this because things like golden popcorn status are added to an existing movie and I don't believe are announced on the RSS feed as a new torrent (I could be wrong here).

**Comment by xombiemp** [comment]
@galli-leo  I read through the Metis pdf and I'm wondering how one would reject a release based on a flag?  In this context how would one reject scene releases?
I saw that there will be a RE_ prefix that makes a flag absolutely required.  Maybe there could be another prefix that means absolutely rejected. RJ_ maybe.  This would be on the quality definition level.

At the profile level right now I see Preferred Tags.  Will we also be able to define Preferred Flags, Required Flags, Rejected Flags at the profile level?  Just trying to wrap my head around this.

**Comment by galli-leo** [comment]
@xombiemp You can negate any tag with N_ prefix so doing REN_ will work like what you have in mind

**Comment by galli-leo** [comment]
You will be able to add tags to the profile. Preferred tags will be deprecated for advanced users with metis

**Comment by jtpavlock** [comment]
Will these features become available in the develop branch as they are finished? Or are you planning on releasing Metis all at once? Considering following the custom-format branch until it gets merged in...

**Comment by SJ50** [comment]
@galli-leo now that this feature is in latest release, is it possible to snatch scene release and replace it with GoldenPopcorn when available.
