### ISSUE TITLE
Radarr thinks 1080p movies are 720p

### ISSUE THREAD

**Issue by lunarboy** [Radarr/Radarr#1521]
**Description:**
Radarr is not detecting movie resolution correctly. It's labeling 1080p files as 720p, and then wants to--of course--download another 1080p release, which it won't detect correctly either, resulting in many, many downloads of the same movie. Has happened in the last few days to at least 2-3 movies.

**Radarr Version:**
0.2.0.696

**Comment by galli-leo** [comment]
@lunarboy Are you sure they are not actually 720p files? Radarr uses media info to read the dimensions of the file and guess quality based on that. Could you give examples of such movies (file name, logs and media info of the video files in question)?

**Comment by lunarboy** [comment]
Yup, sure. Plex says they're 1080p.

**Comment by galli-leo** [comment]
@lunarboy Do you have Analyse video files disabled under Settings -> Media Management.

**Comment by lunarboy** [comment]
I do not. It's on. 

(Sent you PM btw.)

**Comment by fryfrog** [comment]
Do you have `libmediainfo` package installed? Can you pastebin an `mkvinfo` on the file?

**Comment by lunarboy** [comment]
I did not have the `libmediainfo` package installed.

Here's a pastbin of the `mkvinfo` of a recent file that this happened to: https://pastebin.com/TPByfK9e

**Comment by galli-leo** [comment]
Do you know the release name of that file? Also did it happen to that file before you installed libmediainfo?

**Comment by lunarboy** [comment]
I didn't have `libmediainfo` installed before, no. But now I do. And _post_-installation, it's still happening, as evidenced here (with release names this time): https://pastebin.com/CkgQjEru
I did rename them "Bluray" but they were originally tagged as HDTV-720p or HDTV-1080p.

Now one thing I just realized is that the download client renamed them first to simply `{Movie Title} ({Release Year}).mkv`. That _might_ have something to do with this?

**Comment by galli-leo** [comment]
That might certainly be the problem. Can you turn that off?

**Comment by hmgnsd** [comment]
I have this problem as well, is Radarr reading the vertical resolution of files instead of the horizontal? Most encoders would ignore black borders to save space, correct?

**Comment by galli-leo** [comment]
@hmgnsd It should use the horizontal one. Can you run a media info of a file this is happening to?

**Comment by hmgnsd** [comment]
If I'm running Radarr in a Docker on unRAID, how would I do that?

**Comment by galli-leo** [comment]
Can you execute commands via unraid?

**Comment by hmgnsd** [comment]
I can SSH into the docker container (binhex-radarr) but it says 'libmediainfo: command not found'

**Comment by galli-leo** [comment]
Ah that may e problem. Try using a docker container which has the libmediainfo installed. (Though IIRC the commandline is called mediainfo)

**Comment by hmgnsd** [comment]
OK, figured out the container was based on Arch Linux and got MediaInfo installed, what's the command and file path format to get what you need?

**Comment by galli-leo** [comment]
`mediainfo --Output=HTML your_file.mkv`

**Comment by hmgnsd** [comment]
I'm sorry, I'm not very good with terminal :(

mediainfo --Output=HTML my file (2017).mkv 

gets me 

bash: syntax error near unexpected token `('

**Comment by hmgnsd** [comment]
ok, can run the command without error I think, but argh I don't know where it's outputting the result, it's not gone into my appdata folder!?

**Comment by hmgnsd** [comment]
Aaanyway, on all the movies that's being mis labelled as 720p; according to VLC media info they have a horizontal resolution of 1920 but a vertical resolution of 800, and they're all 2.35:1. Plex correctly identifies them as 1080p

**Comment by tretneo** [comment]
I'm also having this issue, when I check the mediainfo output I see something interesting. There is a space in the width and height values, could this cause an issue with Radarr correctly obtaining the resolution?

Note: The movie I ran this on was incorrectly identified as HDTV-720p and of course was re-downloaded multiple times.

`
  <tr>
    <td><i>Width :</i></td>
    <td colspan="3">1 920 pixels</td>
  </tr>
  <tr>
    <td><i>Height :</i></td>
    <td colspan="3">1 080 pixels</td>
  </tr>
`

**Comment by fryfrog** [comment]
I learned a week or two ago that everything I know about `libmediainfo` and Sonarr/Radarr's usage of it is wrong. It parses resolution from the file name, not the metadata.

Use something like filebot or whatever to put the resolution into the file name. :(

**Comment by galli-leo** [comment]
@fryfrog We actually do use mediainfo when determining resolution, just not in every case. Anyways op's issue is fixed so closing.
