### ISSUE TITLE
Movie editor only selects a maximum of 37 movies

### ISSUE THREAD

**Issue by Ginotuch** [Radarr/Radarr#1522]
**Description:**

When on the Movie Selector page, when loaded more than 37 results, when clicking the select all button, it only selects 37 results.
(I have also set the amount of movies to be loaded to 1000 on the UI settings page)
Video: https://www.youtube.com/watch?v=BLsW8UDY6ow

p.s. I did try to search to see if this issue is already known but couldn't find anyone else mentioning it, sorry if I missed it.

**Radarr Version:** 0.2.0.700

**Comment by galli-leo** [comment]
Can you try a different browser / incognito window? Works fine for me.

**Comment by GenericPolarBear** [comment]
@galli-leo It seems to be only with chrome, I did try it with firefox and it works fine. I'm thinking there might be something cached on my chrome that is causing some issues, but even when doing a hard reload it still doesn't fix it. I'll do some more testing.

**Comment by D34DC3N73R** [comment]
@GenericPolarBear I've had varying results when attempting a hard refresh in chrome. Try an incognito window to rule out your local cache, or actually delete your cache. It's most likely an old js file.

**Comment by GenericPolarBear** [comment]
I deleted my old cache, along with all history of Radarr, and all cookies. This seems to have solved the issues for now. But I do wonder what caused it in the first place.

**Comment by mrbipbip** [comment]
I had the same issue.
The selection seems to stop on the first non-downloaded file (same on the video above).
