### ISSUE TITLE
Feature Request : Archived status

### ISSUE THREAD

**Issue by Ninjouz** [Radarr/Radarr#1526]
Hey guys,

In order to reduce api calls on external cloud storage services, it would be nice to have an archived status for movies that will prevent the automated RefreshMovieService from scanning for files and analyzing them daily.

Or consider that a "Downloaded" movie with cutoff met should not be scanned / analyzed.

then would only have to tweak this https://github.com/Radarr/Radarr/blob/7db92c6bcfd9fad57e3f6ad368ce8cd0d35e4c68/src/NzbDrone.Core/Tv/RefreshMovieService.cs#L122

Thanks :)

**Comment by Qstick** [comment]
Option in v3 to prevent scan after refresh, don’t see need for this now.
