### ISSUE TITLE
Radarr doesn't download movies

### ISSUE THREAD

**Issue by estimadarocha** [Radarr/Radarr#1529]
I have been having some problems with Radarr not downloading movies already release and in predb... 

Taking the example of "The Great Wall" if i make a manual search i have this results:

http://prntscr.com/f7z18f

but the filme doesn't get download automatic... any hint?

by the way i have the Minimum Availability set to predb!

this are the logs

 Refresh  Clear Logs    
Component	Message	Time
MovieSearchService	Movie search completed. 0 reports downloaded.	8:43am
DownloadDecisionMaker	Processing 78 releases	8:43am
NzbSearchService	Searching 1 indexers for [The Great Wall]	8:43am
DownloadDecisionMaker	Processing 78 releases	8:42am
NzbSearchService	Searching 1 indexers for [The Great Wall]	8:42am
DownloadDecisionMaker	Processing 78 releases	8:41am
NzbSearchService	Searching 1 indexers for [The Great Wall]

**Comment by galli-leo** [comment]
The problem is predb is currently not working so it's the same as Physical / Web. However, to Radarr the Physical copy is not yet out, so it won't download it. Please see this wiki page: https://github.com/Radarr/Radarr/wiki/Minimum-Availability and use the recommended settings from there.

**Comment by estimadarocha** [comment]
@galli-leo will predb return in a near future?

and thanks for the help

**Comment by galli-leo** [comment]
@estimadarocha No concrete plans yet, they just straight out blocked us :/
