### ISSUE TITLE
Movies Display Page shows only 10 movies per page

### ISSUE THREAD

**Issue by gregcbrown** [Radarr/Radarr#1533]
When first accessing the "Movies" page, when I switch to "table" mode, it only displays 10 movies per page even though I have it set to 250 per page in UI settings.. I have to go to UI settings and "save" without changing anything and then it works properly.
I am using Firefox 53.0.2 on Windows 10.

**Comment by fryfrog** [comment]
That setting is client side, so when you save it... it kicks in. When you update, your local cache will get flushed and you'll have to do it again. :/

**Comment by gregcbrown** [comment]
Not sure what this comment is supposed to mean, it's an issue. I don't have this issue with SONARR...

**Comment by galli-leo** [comment]
@gregcbrown Sonarr also doesn't have paging. Are you on the nightly branch?

**Comment by gregcbrown** [comment]
No, I am on develop.

**Comment by galli-leo** [comment]
@gregcbrown In that case we should not clear out the paging parameters. I will have to investigate this further.

**Comment by gregcbrown** [comment]
Will there be an update coming any time soon to the develop branch? I have 0.2.0.696 - May 12 2017.

**Comment by gregcbrown** [comment]
GREAT to see an update, thank you for that. Unfortunately this issue still persists in the new "develop" release.

**Comment by galli-leo** [comment]
@gregcbrown Can you try using a different browser?

**Comment by gregcbrown** [comment]
I can but HATE IE or EDGE or CHROME. But will try for the team...

**Comment by gregcbrown** [comment]
I tried IE 11 and EDGE, same problem. I am using CCleaner to clean up browsers when they close. Is there a location or file I should be excluding from the cleanup?

**Comment by galli-leo** [comment]
@gregcbrown Ah, that's the problem in that case. We store the page size setting in the local storage of your browser. Not sure if you can exclude that though.

**Comment by gregcbrown** [comment]
OK, so do we need to limit the number of movies per page at all? SONARR lists them all? Works fine for me. Just show ALL movies on the page(s) and let us filter them if we need a different view??

**Comment by galli-leo** [comment]
You don't have to, you can just set the page size to 1000 movies. But after you have over 300-500 movies the UI will start to lag and some browser wont even load the page anymore. Which is why I set a default of 250. (Not sure why it defaults to 10 for you though, could be something weird CCleaner is doing)

**Comment by gregcbrown** [comment]
It's definitely CCleaner. When I turn it off all's well. I'll have to dork around with it a bit. Thanks.
