### ISSUE TITLE
Not all files deleted when replacing multi-cd movies

### ISSUE THREAD

**Issue by Loafdude** [Radarr/Radarr#1535]
My file structure is
/movies/Heartbreakers (2001)/vite-divx-hb.cd1.avi
/movies/Heartbreakers (2001)/vite-divx-hb.cd2.avi

Radarr is replacing the movie with a new version

Log:
```
17-5-16 19:15:30.0|Info|RecycleBinProvider|Recycling Bin has not been configured, deleting permanently. /movies/Heartbreakers (2001)/vite-divx-hb.cd2.avi
17-5-16 19:17:13.3|Info|MovieService|Linking [Heartbreakers.2002.1080p.BluRay.x264.mkv] > [[tt0125022][Heartbreakers (2001)]]
```

As you can see I am left with
/movies/Heartbreakers (2001)/vite-divx-hb.cd1.avi
/movies/Heartbreakers (2001)/Heartbreakers.2002.1080p.BluRay.x264.mkv

which is bad

**Comment by galli-leo** [comment]
Yeah we currently do not handle multi disk movies very well.  But there's already an issue open for that :) #145
