### ISSUE TITLE
ENHANCEMENT - Plex Refresh/Scan

### ISSUE THREAD

**Issue by qazero** [Radarr/Radarr#1536]
Once a newly downloaded movie has finished being post processed, it triggers a plex library scan. Instead of rescanning the entire library and all sections, would it be possible to have Radarr only trigger a scan for the directory of the newly added movie (similar to how Sonarr triggers plex)? Scanning the entire plex library including all sections is extremely inefficient especially when dealing with large libraries stored in the cloud.

**Comment by ochompsky** [comment]
What does this have to do with Radarr?  

You need to setup Plex properly.  Look at server->library.  There is an option:

Run a partial scan when changes are detected
When changes to library folders are detected, only scan the folder that changed.

**Comment by rnyberg** [comment]
I came here wondering the same thing. It has to do with Radarr has the Plex connection possibility with `Update library` toggle. This toggle will cause a full library refresh which takes a long time for large libraries, and having it trigger for each DL/Upgrade/Rename globally instead locally per movie folder is problematic.

The setting in Radarr: [https://vgy.me/XwQgAM.png](url)

It's not a big deal and a big priority though.

**Comment by fhscholl** [comment]
This is fixed with my code cleanup for notifications a few weeks ago.

In the current release it will always trigger a full library refresh. Since a recent nightly (896?) it tries to refresh a single title and fails back to the full library just like Sonarr.
