### ISSUE TITLE
Completed downloads not always getting moved

### ISSUE THREAD

**Issue by warbrd** [Radarr/Radarr#1538]
**Description:**

Movies are not always getting moved from NZBGets completed dir to the movie dir.
Radarr settings:
http://imgur.com/P1Ql9FW

**Radarr Version:**
v0.2.0.696

**Logs:**
https://pastebin.com/TS5ZRt9u

The error from line 15 and downwards keeps repeating over and over

**Comment by galli-leo** [comment]
@warbrd Have you verified that the file actually exists?

**Comment by warbrd** [comment]
@galli-leo yes I did. I also manually created a "Das Boot (1981)" folder, moved the file into it and refreshed in radarr, upon which it was recognized. The file in question is pretty big, 24.8 gb, Don't know if that is relevant.

**Comment by warbrd** [comment]
Here are the complete logs
[radarr.txt](https://github.com/Radarr/Radarr/files/1008609/radarr.txt)
[radarr.0.txt](https://github.com/Radarr/Radarr/files/1008610/radarr.0.txt)

**Comment by galli-leo** [comment]
@warbrd What are the permissions on this file? Maybe Radarr cannot read it.

**Comment by warbrd** [comment]
@galli-leo I'm on windows, and all users have read access. The file in question was marked read-only though

**Comment by galli-leo** [comment]
@warbrd Well that may explain it. Can you set permissions to windows equivalent of 777 and try again?
