### ISSUE TITLE
Do not allow profile to be deleted if in use with lists.

### ISSUE THREAD

**Issue by blackwhattack** [Radarr/Radarr#1540]
**Description:**
I add a movie in Trakt. I get home and it gets loaded, no problem. But the profile is null, there is nothing under the profile category. Because of that the movie can't be found, searched; it just doesn't work. That's probably because I deleted the 'Any' profile. Why? Well I hoped that the first profile in the list would be set as the default so I changed the 'Any' profile for another. What I'm asking for is to: fix this, and possibly add a default profile selection, so new movies are automatically added with a **chosen one**.

**Radarr Version:**
0.2.0.696

**Comment by galli-leo** [comment]
@blackwhattack We already use a default profile value, namely the one you set in the list. After you delete that profile, Radarr cannot find it anymore and thus uses no Profile. I agree we maybe should just use the next available profile in that case.

**Comment by fryfrog** [comment]
Or maybe lists w/o valid profiles should disable and show an error in System?

**Comment by galli-leo** [comment]
@fryfrog That may also be an option. Or just prevent profiles that are set for a list to be deleted (How it's done for series in sonarr.
