### ISSUE TITLE
Radarr can't see my NAS via UNC or Mapped Drive

### ISSUE THREAD

**Issue by jdchandler** [Radarr/Radarr#1543]
**Description:**
I have tried running it as a service and the application as an Administrator.

The movies file share I have is mapped at Z:\ but can also be found at \\LeetBox\Movies

Neither work when trying to import into Radarr. It shows both formats with 0 bytes available and says there are no file there. Sonarr which is running as a service can see this same exact path with both formats.

**Radarr Version:**
0.2.0.696
Windows Server 2012 R2

**Logs:**
[Fatal] NzbDroneErrorPipeline: Request Failed

[v0.2.0.696] System.IO.DirectoryNotFoundException: \\leetbox\movies
   at NzbDrone.Windows.Disk.DiskProvider.GetAvailableSpace(String path) in C:\pr
ojects\radarr-usby1\src\NzbDrone.Windows\Disk\DiskProvider.cs:line 33
   at NzbDrone.Core.RootFolders.RootFolderService.Get(Int32 id) in C:\projects\r
adarr-usby1\src\NzbDrone.Core\RootFolders\RootFolderService.cs:line 213
   at NzbDrone.Api.Movie.MovieBulkImportModule.Search() in C:\projects\radarr-us
by1\src\NzbDrone.Api\Movies\MovieBulkImportModule.cs:line 60
   at NzbDrone.Api.Movie.MovieBulkImportModule.<.ctor>b__6_0(Object x) in C:\pro
jects\radarr-usby1\src\NzbDrone.Api\Movies\MovieBulkImportModule.cs:line 49
   at CallSite.Target(Closure , CallSite , Func`2 , Object )
   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, Cance
llationToken context)

**Comment by fryfrog** [comment]
Make sure the service is running as *you*, not SYSTEM. Check your Sonarr service to confirm. Are you sure Sonarr is running as a service? It might just be running at startup which would make it naturally run as you.

I also assume your UNC paths are correct and github is just eating your missing `\`. Should be `\\server\share` of course.

**Comment by jdchandler** [comment]
Thanks for the response.

I do have the service running as ME (local administrator user), the SAME user the Sonarr service is running as and has no issues finding my files using the \\server\share format. You were correct GitHub truncating the other \.

I try to go to the logs page under System and it never loads. I got the previous error when running it in a command window and I was able to copy it out.

Suggestions?

**Comment by jdchandler** [comment]
Ok I found the logs in the GUI, I was on that Table section that was loading forever.

17-5-18 14:07:33.3|Warn|SkyHookProxy|Couldn't map movie 1960s to a movie on The Movie DB. It will not be added :(

[v0.2.0.696] System.Net.WebException: The underlying connection was closed: The connection was closed unexpectedly.
   at System.Net.HttpWebRequest.GetResponse()
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 74
   at NzbDrone.Common.Http.Dispatchers.FallbackHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\Dispatchers\FallbackHttpDispatcher.cs:line 58
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 63
   at NzbDrone.Common.Http.HttpClient.Get[T](HttpRequest request) in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:line 191
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewMovie(String title) in C:\projects\radarr-usby1\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 506
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.MapMovieToTmdbMovie(Movie movie) in C:\projects\radarr-usby1\src\NzbDrone.Core\M


I now see the issue I THINK.

Underneath my share "movies" is 5 more directories organizing by decade (1960s, 1970s,etc) and I see its trying to match those folders as movies. Do I need to add each PARENT folder and there should be NO folders beneath it?

**Comment by jdchandler** [comment]
Well that didn't work either, I now added a folder where ONLY movies are beneath that parent and still says, "No movies found in folder \\leetbox\movies\2000s\. Have you already added them?

There was also no new log output (I cleared before it).

It shows how much free space there is, and as I type a path, it auto suggests folders.

I am not sure why it can't see the files.

With Sonaar I literally gave it the top level parent TV Shows and it sees all files within all respective folders for each show. Was expecting that here and trying to get it to work!

**Comment by jdchandler** [comment]
To clarify, I am trying to do the Bulk Import.

**Comment by fryfrog** [comment]
When you import, you should aim it at `\\leetbox\movies\2000s`. And in this directory should be a bunch of folders named after the movie like `Movie Title (Year)` and inside the directory should be the movie file, hopefully w/ quality in it like `Movie Title (Year)/Movie Title (Year) [1080p-Bluray].ext` so Radarr can get the quality right.

**Comment by jdchandler** [comment]
It looks like my problem then is that Radarr expects each movie to be in its own folder?

Where I have everything organized by decade folder, and have each movie file beneath it, in bulk. 

Does this REALLY have to have this directory structure? 
I don't maintain multiple quality video files (as Plex can maintain that for me, but don't really use that feature often anyway). 

I find it redundant to put 1 movie file in its own parent directory for over 5000 movies.

With Sonarr and TV shows it makes more sense as each show with have a season folder with 10+ items in each season folder. But a movie is just 1 movie (unless its a series or trilogy - where I do maintain folders to keep them together).

I really want to replace CouchPotato but if I have to make folders for EVERY movie, then I can't use Radarr haha but I would love to as I am a big fan of Sonarr.

Thanks for the help

**Comment by jdchandler** [comment]
Is there anyway to customize the path Radarr expects? 

Look for direct movie filenames rather than a parent folder?

**Comment by ghanjaemu** [comment]
No, each movie has to have its own root directory.  This is standard "release group convention" anyway.  The answer is in the Wiki as well as the solution.

**Comment by galli-leo** [comment]
We plan to change that, though it's not very easy as we are a fork of Sonarr.

**Comment by jdchandler** [comment]
Hi galli-leom

Thanks for the response.

Glad to hear that this feature is coming.

Is there a priority set or eta for roadmap for this feature?

Thanks!

(I will close issue after response - or lack there of after awhile)

**Comment by galli-leo** [comment]
No eta yet as I have no idea how difficult it will be to implement. It is definitely planned for the first release (0.2) Though.

**Comment by jdchandler** [comment]
Thanks! Will be looking forward to testing it when it releases!

**Comment by gmtillman** [comment]
wow...first of all Im lost...I love the idead of Radarr and Sonarr but I cant access my NAS Folder...changing services? Egh...Seriously guys please make it simple for us to follow.
Before I was able to access my NAS from Sonarr and Radarr...what happened?

**Comment by fryfrog** [comment]
@gmtillman: This is a really poor way to try and get support. I suggest you join the Discord server and get real time help there.
