### ISSUE TITLE
Cant install latest update

### ISSUE THREAD

**Issue by theebanka** [Radarr/Radarr#1545]
Hey guys I am hoping this is something stupid that i am missing but for some strange reason I have been unable to install the latest update. I have been using Radarr for months without many issues (definitely not with the update process) but suddenly with this most recent one it is having trouble. Here is a bit of the Update Log that i was able to grab. If you need any more info from logs just let me know where to look and I will grab what I can for you

> 17-5-17 16:18:55.8|Info|StartNzbDrone|Starting Radarr.exe
17-5-17 16:18:55.8|Debug|ProcessProvider|Starting mono --debug /Applications/Radarr.app/Contents/MacOS/Radarr.exe /nobrowser
17-5-17 16:18:55.8|Fatal|UpdateApp|An error has occurred while applying update package.

>[v0.2.0.696] NzbDrone.Mono.Disk.LinuxPermissionsException: Error setting file permissions: ENOENT

**Comment by Geezus42** [comment]
I've have the same problem. I'm stuck on version 0.2.0.707.

**Comment by theebanka** [comment]
oh wow I am even behind that. I am on 0.2.0.692  of the develop branch.... 0.2.0.696 is what I was having issues updating to and it doesnt show anything newer for me

**Comment by Geezus42** [comment]
I'm on nightlies, the develope branch is behind that.

**Comment by fryfrog** [comment]
Check permissions of the directory, looks like Radarr isn't able to modify its own permissions from your error message.

**Comment by Geezus42** [comment]
Just had time for a quick look but everything shows radarr:radarr and the one has rw on files, rwx on folders. I could change to group permissions to match the owner but that shouldn't be necessary.

**Comment by galli-leo** [comment]
@Geezus42 Yeah we changed the way the osx app is structured which messed with the updater :(. You can either redownload the latest app package or update to the latest nightly build where we fixed auto updating for osx.

**Comment by Geezus42** [comment]
I'm running Linux not OSX, though I understand there is some similarly with both being Unix-like. Do you consider the entire in-app update process the auto-updater? I don't have auto updates turned on, I go to task and click update.

**Comment by galli-leo** [comment]
@Geezus42 Well in that case, it's something different (since this issue is osx specific). Can you open a new Github issue for that?

**Comment by Geezus42** [comment]
Yeah

**Comment by theebanka** [comment]
@galli-leo So i swapped over to the nightly build and was able to update no problem (Thank you) so now if I switch back to the Develop branch will I be able to download the most recent? or do I need to stay on nightly for a little while?

**Comment by galli-leo** [comment]
@theebanka Well the nightly is the most recent. And no you won't be able to download the latest develop update, since it's considered to be a downgrade to the current version. I would advise to set it back and wait on the latest develop release.

**Comment by theebanka** [comment]
Okay thanks!
