### ISSUE TITLE
Movie The Space Between Us has two years

### ISSUE THREAD

**Issue by fryfrog** [Radarr/Radarr#1547]
The movie `The Space Between Us` is listed with 2016 in trakt and themoviedb, but 2017 on imdb and scene releases. What do? :/

**Comment by Popsikill** [comment]
I also have this - I believe it's causing Radarr to search on the 2016 year, where all of the releases are 2017, thus Radarr displays the message "Unknown movie. Movie found does not match wanted movie." and won't allow a grab.

**Comment by fryfrog** [comment]
It *seems* like the right fix is to get tmdb and trakt to match imdb, is that feasible? There wasn't any real way to do that via edit on tmdb. :/

**Comment by galli-leo** [comment]
@fryfrog Yes and no. IIRC you said that the Australia release date was in 2016? We should improve the logic which handles which date we pick for the cinemas release date.

**Comment by fsign** [comment]
Well its finding releases in search, but you get the error message "Unknown movie. Movie found does not match wanted movie." instead of the button that forces the download. If it were just able to be forced, it would solve the problem.

**Comment by galli-leo** [comment]
@fsign If you were to download the movie, Radarr would just have problems at the import, because it still cannot match it. That's why downloading is disabled for these movies. However, someone fixed the date on this movie, so it should be good to go now.

**Comment by fletchto99** [comment]
Perhaps it would be possible to add a force manual download button for issues like this?

**Comment by galli-leo** [comment]
@fletchto99 See my above comment. That wouldn't work as Radarr couldn't import it anyways afterwards. I am thinking of adding a better system, so Radarr remembers bad matches and thus should be able import it.

**Comment by galli-leo** [comment]
Closing as TMDB now has the correct year.
