### ISSUE TITLE
Import of downloaded movie failed

### ISSUE THREAD

**Issue by sheepsskullcity** [Radarr/Radarr#1549]
I have local web server with generated rss feed items: {Movie_Title} ( {Year} ) + download torrent link.

Radarr successfuly grab release and send it to torrent client.

If downloaded movie have not standart name (h6sdh8sfadh.avi for example) Radarr parser will not process file.

If i manually move movie file to "/path/to/download/{Movie_Title} ( {Year} )" folder during download then parser can process it.

But if movie file moved with torrent client on-complete-script(get here {Movie_Title} ( {Year} ) was a trick) radarr only remove all files and import **failed**.

Here grab event:
```
Name: Beauty and the Beast (2017) CamRip
Indexer: RSS
Download Client: Transmission
```
Successefull import after file mannualy moved.
```
Name: Beauty and the Beast
Source: /media/download/radarr/Beauty and the Beast(2017)/B.n.B.2O17.D.CAMRip.avi
Imported To: /media/videos/Beauty and the Beast (2017)/Beauty and the Beast (2017) CAM.avi
```

Possible solutions:
* option to add {Movie_Title} ( {Year} ) variable to download path.
* add Environment Variable radarr_torrent_hash for On Grab event in Radarr.
* fix Radarr parser.
* use Drone Factory folder with torrent client scripts.

**Comment by galli-leo** [comment]
> But if movie file moved with torrent client on-complete-script(get here {Movie_Title} ( {Year} ) was a trick) radarr only remove all files and import failed.
Could you elaborate a bit more on what you mean with that. I don't quite understand what happened :/

**Comment by sheepsskullcity** [comment]
> Could you elaborate a bit more on what you mean with that. I don't quite understand what happened :/

Transmission execute post processing script which create folder with correct name and move torrent data inside ( /media/download/radarr/Beauty and the Beast(2017)/ ). But import will never happen.

Here some log.

```
17-5-19 19:15:39.2|Trace|HttpClient|Response content (306 bytes): {"arguments":{"torrents":[{"downloadDir":"/media/download/radarr/","errorString":"","eta":-1,"hashString":"49fc9f8dacf6f8cdd770f3a944ba1951f8812429","id":19,"isFinished":true,"leftUntilDone":0,"name":"KrasoTka.i.CHudisCHe.2O17.D.CAMRip.avi","status":0,"totalSize":1467613184}]},"result":"success"}

17-5-19 19:15:39.2|Trace|EventAggregator|Publishing DownloadCompletedEvent
17-5-19 19:15:39.2|Trace|EventAggregator|DownloadCompletedEvent -> DownloadEventHub
17-5-19 19:15:39.3|Debug|DownloadEventHub|[KrasoTka.i.CHudisCHe.2O17.D.CAMRip.avi] Removing download from Transmission history
17-5-19 19:15:39.3|Trace|HttpClient|Req: [POST] http://localhost:9091/transmission/rpc: torrent-remove(...)
17-5-19 19:15:39.3|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
17-5-19 19:15:43.6|Trace|HttpClient|Res: [POST] http://localhost:9091/transmission/rpc: 200.OK (4268 ms)
17-5-19 19:15:43.6|Trace|HttpClient|Response content (36 bytes): {"arguments":{},"result":"success"}
```

But if i move torrent data before DownloadCompletedEvent radarr parser will check parent folder name of downloaded file, import it to library and clear Transmission history.

**Comment by galli-leo** [comment]
Yeah seems like transmission does not give us the folder name after the script executed but only the filename. (Which is obfuscated, so of course Radarr cannot parse it) I don't think there's much we can do here.

**Comment by sheepsskullcity** [comment]
Is there any way to get hash for grabbed torrent except api/history because it's give me "unauthorized access" error with all paging an token parameters?

**Comment by sheepsskullcity** [comment]
So i stopped on Drone Factory folder + Radarr On Grab scripts method.


```
#!/bin/sh
nohup python /scripts/radarr_on_grab.py "${radarr_movie_imdbid}" 2>> /dev/null >> /dev/null &
```

```
#!/usr/bin/env python

import json, requests, subprocess, os, sys, re
from subprocess import call, check_output

URL = 'http://localhost:7878/api/history?apikey=XXXXXXXXXXXXXXXXXXXX&pageSize=10&page=1&sortKey=date&sortDir=desc'
ID = sys.argv[1]
global HASH
global TITLE
global YEAR
DONEDIR = 'done'
USER = 'user'
PASSWORD = 'password'

data = requests.get(URL).json()

for h in data['records']:
	if h['eventType'] == 'grabbed' and h['movie']['imdbId'] == ID:
		TITLE = h['movie']['title']
		YEAR = h['movie']['year']
		HASH = h['downloadId'].lower()
		break

to_remove = '\/:*?"<>|'
table = {ord(char): None for char in to_remove}
finalName = TITLE.translate(table) + ' ('+ str(YEAR) + ')'

outStr = check_output(['transmission-remote' , '-t' +  HASH, '-n' , USER + ':' + PASSWORD , '-i']).decode("utf-8")
folderPath = os.path.join(re.search(' Location: (.+)', outStr).group(1), DONEDIR, finalName)
strEnd = check_output(['transmission-remote' , '-t' +  HASH, '-n' , USER + ':' + PASSWORD , '--move' , folderPath]).decode("utf-8")
```
