### ISSUE TITLE
Unable to add movies when the file names start with the year

### ISSUE THREAD

**Issue by deathbybandaid** [Radarr/Radarr#155]
My movie files are named (Year) TheNameOfMovie

During import, the movies don't import until I remove the year from the title to search for.

The import feature should be able to handle various naming schemes like this,

**Comment by captcrunch1001** [comment]
I had a similar issue when adding existing movies.  All of my folders are named Movie (Year).  If you remove the year from the search it will find it.

Another thing I noticed movies are not searching with the year.  For instance Arrival 2016 keeps finding releases for Arrival (2013).  Something to look into.

**Comment by deathbybandaid** [comment]
I'm still having issues with this. I even deleted the program completely.

This is what I see for thousands of movies.
![image](https://cloud.githubusercontent.com/assets/18010545/22209753/a78b5274-e155-11e6-9b4a-493bcd664904.png)

This is what I see, if I remove the year number.
![image](https://cloud.githubusercontent.com/assets/18010545/22209839/c2f100a4-e155-11e6-8184-9e73cdb7e8ea.png)

When the issue was closed, was the fix just for brackets? Or should it have also worked for parenthesis?

**Comment by galli-leo** [comment]
Should have been fixed for parenthesis. It works for me at least.

**Comment by deathbybandaid** [comment]
Odd, because, I left the parenthesis, and just removed the numbers

**Comment by galli-leo** [comment]
What happens when you use [2016] Zootopia or 2016 Zootopia?

**Comment by deathbybandaid** [comment]
![image](https://cloud.githubusercontent.com/assets/18010545/22210356/8a14ec1c-e157-11e6-8fe7-671861cacf9a.png)


![image](https://cloud.githubusercontent.com/assets/18010545/22210376/a457dc92-e157-11e6-94e8-7f8627b7a774.png)

**Comment by deathbybandaid** [comment]
However, it works if the number is after the movie instead of in front

![image](https://cloud.githubusercontent.com/assets/18010545/22210435/d3140c22-e157-11e6-9922-8e7e9e6d40d3.png)

![image](https://cloud.githubusercontent.com/assets/18010545/22210470/ee08bac8-e157-11e6-9284-5ad803a2e096.png)

**Comment by galli-leo** [comment]
The exact same folder name works fine for me. Can you enable Trace logging and post the result here?

**Comment by deathbybandaid** [comment]
17-1-23 10:58:40.5|Trace|Http|Req: 1479 [GET] /api/movie??sort_by=sortTitle&order=desc
17-1-23 10:58:40.5|Trace|Http|Res: 1479 [GET] /api/movie??sort_by=sortTitle&order=desc: 200.OK (18 ms)
17-1-23 10:58:40.5|Debug|Api|[GET] /api/movie??sort_by=sortTitle&order=desc: 200.OK (18 ms)
17-1-23 10:58:41.6|Trace|Http|Req: 1480 [GET] /api/profile
17-1-23 10:58:41.6|Trace|Http|Req: 1481 [GET] /api/rootfolder
17-1-23 10:58:41.6|Trace|Http|Res: 1480 [GET] /api/profile: 200.OK (14 ms)
17-1-23 10:58:41.6|Debug|Api|[GET] /api/profile: 200.OK (14 ms)
17-1-23 10:58:41.6|Debug|RootFolderService|Generating list of unmapped folders
17-1-23 10:58:42.6|Debug|RootFolderService|1171 unmapped folders detected.
17-1-23 10:58:42.6|Debug|RootFolderService|Generating list of unmapped folders
17-1-23 10:58:42.7|Debug|RootFolderService|1 unmapped folders detected.
17-1-23 10:58:42.7|Trace|Http|Res: 1481 [GET] /api/rootfolder: 200.OK (1056 ms)
17-1-23 10:58:42.7|Debug|Api|[GET] /api/rootfolder: 200.OK (1056 ms)
17-1-23 10:58:44.4|Trace|Http|Req: 1482 [GET] /api/movies/lookup??term=(2016)+Zootopia
17-1-23 10:58:44.4|Debug|Parser|Parsing string '(2016).Zootopia'
17-1-23 10:58:44.4|Trace|Parser|^(?<title>.+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(19|20)\d{2}(?!p|i|\d+|\]|\W\d+)))+(\W+|_|$)(?!\\)
17-1-23 10:58:44.4|Debug|Parser|Movie Parsed. ( - 0 
17-1-23 10:58:44.4|Debug|Parser|Language parsed: English
17-1-23 10:58:44.5|Debug|QualityParser|Trying to parse quality for (2016).Zootopia
17-1-23 10:58:44.5|Debug|Parser|Quality parsed: Unknown v1
17-1-23 10:58:44.5|Debug|Parser|Release Group parsed: 
17-1-23 10:58:44.5|Trace|HttpClient|Req: [GET] https://api.themoviedb.org/3/search/movie?api_key=1a7373301961d03f97f853a876dd1212&query=(&year=2016&include_adult=False
17-1-23 10:58:44.5|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
17-1-23 10:58:44.8|Trace|HttpClient|Res: [GET] https://api.themoviedb.org/3/search/movie?api_key=1a7373301961d03f97f853a876dd1212&query=(&year=2016&include_adult=False: 200.OK (281 ms)
17-1-23 10:58:44.8|Trace|Http|Res: 1482 [GET] /api/movies/lookup??term=(2016)+Zootopia: 200.OK (375 ms)
17-1-23 10:58:44.8|Debug|Api|[GET] /api/movies/lookup??term=(2016)+Zootopia: 200.OK (375 ms)

**Comment by deathbybandaid** [comment]
[trace.txt](https://github.com/Radarr/Radarr/files/724216/trace.txt)

**Comment by galli-leo** [comment]
@deathbybandaid Should be fixed on the latest nightly branch.

**Comment by deathbybandaid** [comment]
It works great now!! Thanks!!
