### ISSUE TITLE
Add ability to remove root folder e.g. from add move list

### ISSUE THREAD

**Issue by RlndVt** [Radarr/Radarr#1550]
**Description:**
When you add a movie at the path selection, you can add extra root folders, but you can not remove old ones. 

(Sonarr has a small cross next to the paths for this.)

**Radarr Version:**
0.2.0.696

**Comment by galli-leo** [comment]
<img width="815" alt="screen shot 2017-05-19 at 17 04 33" src="https://cloud.githubusercontent.com/assets/5339762/26253941/450b723a-3cb5-11e7-8f49-c3e336f450d6.png">
We do have that as well?

**Comment by RlndVt** [comment]
I meant in the pop-down menu where, when adding a movie, you choose where the movie needs to be saved to.

Good to know you can do it there though, thanks!

**Comment by galli-leo** [comment]
@RlndVt Yeah, but Sonarr doesn't have one there either. I want to add root folders to one of the settings pages anyways, so that should help with that.

**Comment by RlndVt** [comment]
👍
