### ISSUE TITLE
Offer To Add Sequels To Wanted List

### ISSUE THREAD

**Issue by AnoNunga** [Radarr/Radarr#1554]
**Description:**
When using TMDB's [get movie details](https://developers.themoviedb.org/3/movies/get-movie-details) method, check the **belongs_to_collection** field and if the movie does belong to a collection, call the [collection details](https://developers.themoviedb.org/3/collections/get-collection-details) to get the other films from the collection. Add any IDs that are not already in Radarr to a Collections list from which the user can then select to add to Wanted list or ignore. Travis Bell from TMDB outlined how the process could work [here](https://www.themoviedb.org/talk/586d2524925141087c0085ad). Radarr gets around the problem the user in that post had because it starts with a valid movie ID.

**IRL Scenario**
User has the Bourne films with Matt Damon but hasn't heard of The Bourne Legacy nor the planned sequel there to. During a routine scan of existing movies following a Radarr update that adds this feature, the application agent sees these related items and adds them to Collections list. Next time user accesses Radarr, they see a movie is readily available for download from a franchise they like and a future title to add to their Wanted list. Consider the same scenario for Star Wars, X-Men, Shrek, etc.

**Thoughts**
While users can add lists from third parties, this would be a handy self contained feature for those who don't stay abreast of movie news. Similar to Recommendations but more focused, like showing missing episodes or a new season if it were a TV Show. Could sit next to Discover New or there under next to Recommendations in the UI? Opt-in notifications for when a new title is announced in any of the collections that the user's movies belong to in TMDB would be a nice to have addition.

Thanks for your consideration.

**Comment by galli-leo** [comment]
I think a big part of this is covered in the new discovery feature. It will automatically recommend you films based on others you have in your library. (e.g. If you have a lot of bourne and james bond films, it will probably recommend you more bourne and james bond films along with mission impossible, etc.). However, we also want to add collections as a whole to Radarr. This would allow a user (similarely to series in Sonarr) to add a collection and then have Radarr auto download all sequels, prequels, etc. This is already a feature request (#112), so I am going to close this as a duplicate.
