### ISSUE TITLE
Add 'per xx minutes' info to 'Size Limit' tooltip

### ISSUE THREAD

**Issue by Karyudo** [Radarr/Radarr#1560]
It's ludicrous that the tooltip help text for 'Size Limit' under 'Quality' doesn't indicate what the size is based on (8.79 GB to 13.67 GB per HOW MUCH TIME?).

Sure, that info is available elsewhere (IIRC it's 90 minutes?), but why isn't it shown right where it's most needed? The tooltip under 'Media Management | Folders | Automatically Rename Folder' is several times longer... and that's for an alpha feature! 'Size Limit' should be at least as robust!

I know this is probably something legacy from Sonarr, but that doesn't mean it shouldn't be fixed....

**Comment by galli-leo** [comment]
As soon as you hover over the size limits that information appears:? https://imgur.com/gallery/pOL9Q That's also the way it is in Sonarr?

**Comment by Karyudo** [comment]
Huh. So, you figure it's enough to put this information someplace where it's not obvious, and where you could use the tool correctly without ever seeing it? Why not put it with the little warning triangle information, where users know to go for information, instead of someplace non-intuitive and—dare I say—dumb?
