### ISSUE TITLE
Show MPAA rating on Add Movies Screens

### ISSUE THREAD

**Issue by smidley** [Radarr/Radarr#1561]
The MPAA rating of a movie should be shown on all the Add Movies screens.

**Comment by galli-leo** [comment]
We could only implement that when using the discovery feature, since search does not give us the MPAA rating :/

**Comment by alxlaxv** [comment]
Thanks for pointing this our for my request " Add MPAA rating in the Metadata NFO for Kodi #2734 "
What can we do to help you to move on?

For example, this information could be retrieved from OMDb API like below:
```
{"Title":"Westworld","Year":"2016–","Rated":"TV-MA","Released":"02 Oct 2016","Runtime":"62 min","Genre":"Drama, Mystery, Sci-Fi","Director":"N/A","Writer":"N/A","Actors":"Evan Rachel Wood, Thandie Newton, Jeffrey Wright, James Marsden","Plot":"Set at the intersection of the near future and the reimagined past, explore a world in which every human appetite can be indulged without consequence.","Language":"English","Country":"USA","Awards":"Nominated for 3 Golden Globes. Another 29 wins & 75 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMTEyODk5NTc2MjNeQTJeQWpwZ15BbWU4MDQ5NTgwOTkx._V1_SX300.jpg","Ratings":[{"Source":"Internet Movie Database","Value":"8.9/10"}],"Metascore":"N/A","imdbRating":"8.9","imdbVotes":"258,792","imdbID":"tt0475784","Type":"series","totalSeasons":"2","Response":"True"}
````

**Comment by galli-leo** [comment]
@alxlaxv If you know either python or php you could help me building the V3 API. We don't need OMDb, TMDB or IMDB already provides rating information.

**Comment by alxlaxv** [comment]
OK.
I have checked that yes.
We will have to deal with several countries which have different ratings.

To get the list of available ratings per country
> https://api.themoviedb.org/3/certification/movie/list?api_key=

Get the list of certification (rating) for a movie based on release date and country
> https://api.themoviedb.org/3/movie/269149/release_dates?api_key=

**Comment by alxlaxv** [comment]
Anyone able to work on that?

**Comment by DavidAdams** [comment]
Posted over here: https://feathub.com/Radarr/Radarr/+100

But yes, The Movie DB provides a simple API for this, granted there are multiple countries, but if we could start with something like {us-certification} that would be great. This is a blocker for the rename function for many of us that sort our media by ratings.

Thanks!

**Comment by alxlaxv** [comment]
Hey stale bot 🥇 
Yes this is still open :)
