### ISSUE TITLE
missing movies still showing up in library even thou they have been deleted - refresh not working

### ISSUE THREAD

**Issue by maZuFC** [Radarr/Radarr#1562]
hi

ive been giving radarr a test drive and im liking what i see so far.. i use sonarr for my tv shows and its been great.

with radarr im currently seeing a whole bunch of movies showing up as 'missing' in red.
even when i refresh the library it does not pick up movies that have been deleted ages ago... an entry remains in radarr. 
i can confirm that the folder / file are not on the nas.
please note that there are also a lot of movies showing up as downloaded and are reporting correctly.

i am using a network share for my movies folder so i ran radarr using administrator and i was able to browse to the M: share
im also able to browse using the nas IP number and unc path \\nas\movies

one thing that ive noticed is that when i go to System
i cannot see M: in the Disk Space area.

in Sonarr, this location shows all volumes/shares that im using.
so im not sure why radarr is not showing the same ?

so how do i remove all the movies that are tagged as missing?
i have around 187 of these... 

let me know if you need any logs or any more info 

appreciate the great work !

cheers

m.

**Comment by maZuFC** [comment]
also ive noticed that radarr keeps grabbing the movies again that i have deleted...

it just happened then..

i deleted batman vs superman ages ago but it just tried to download
the avengers as well

:/

**Comment by onedr0p** [comment]
Do you guys have the setting for unmonitor deleted movies enable in settings? That should stop the movie from continuing to download.

**Comment by maZuFC** [comment]
im not sure... which setting is this?

**Comment by maZuFC** [comment]
i really dont get whats happening here

i did a fresh reinstall of radarr so that my movies list is accurate.

now im seeing a massive amount of movies showing up as missing... 
ive lost count how many times ive had to delete batman vs superman and avengers from my movies list

theres definitely 20 or so movies that missing which i never added in.. 

any ideas?

**Comment by raysguy** [comment]
I think I have the same issue.  I have the option enabled to un-monitor deleted movies but when I delete a movie in Plex then Radarr does not un-monitor the movie.  It recognises the file is missing but then started to download a new copy.  This makes it a bit difficult to manage the library.

I had previously tried it the other way around (don't know if this part should be logged as a separate issue).  Actually delete a movie within Radarr and toggle the "delete all files" option when doing so.  However Radarr never actually deletes the actual files so they still show up in Plex.  So either way I have to delete movies twice.  I should point out I don't have any other files in my individual movie folders except the movie file itself.

**Comment by maZuFC** [comment]
yep sounds about right.

ive also found that the option 'Exclude movie from Auto List Import?' doesnt work very well
ive excluded those movies i mentioned a number of times yet they still show up.

ive removed all my lists for now and will add movies in manually as i learn about them.

im also having strange results when it comes to extracting rar files and then sorting the movie into its destination location.
sometimes it does it.. other times it doesnt... i havent been able to identify a pattern as to what is happening.

hopefully as the updates keep coming these little bugs will get resolved.

**Comment by humani1** [comment]
I just installed Radarr and downloaded three movies, then deleted them. They still show up as missing even though I toogled the option to unmonitor deleted movies.

**Comment by scope999** [comment]
This seemed to be fixed for a while with deleted movies being marked unmonitored but now it is back to marking deleted movies as missing and redownloading. Can this be permanently fixed please? It works for sonarr the episoded is recorded as missing from disk and not redownloaded.

**Comment by galli-leo** [comment]
This should be resolved in the latest update.
