### ISSUE TITLE
Torrentpotato stopped working with Cardigann

### ISSUE THREAD

**Issue by brimur** [Radarr/Radarr#1565]
I've been getting this error for the past week or two. Before that Cardigann worked great. I had been using torrentpotato via Cardigann with Radarr. Now, in Radarr I get no results and the following error...

````
HTTP Error - Res: [GET] http://localhost:5060/torrentpotato/thepiratebay?passkey=(removed)&user=&imdbid=tt0167260: 502.BadGateway
{
"error": "Status Code 401 received from IMDB"
}
````

Also seeing these errors
http://i.imgur.com/Sx8QQQF.png

If I do a test search on Cardigann it will return expected results.

I also posted this issue in Cardigann because Im not sure what might have changed.

Any help appreciated

**Comment by onedr0p** [comment]
Cardigann is not being actively developed anymore (only definition updates), join us in the ranks of jackett :)

**Comment by brimur** [comment]
@onedr0p I wasnt aware Jackett supported torentpotato. Does it now?

**Comment by onedr0p** [comment]
yes it does 👍 torznab is the better API thou :)

**Comment by galli-leo** [comment]
Also it is very likely related to Omdb (the api cardigann uses) going private (hence the 401 and nothing we can do)
