### ISSUE TITLE
Remote Path Mapping 

### ISSUE THREAD

**Issue by NathanTheGr8** [Radarr/Radarr#1568]
Remote Path Mapping is not listed as an option under NzbGet. 
http://imgur.com/a/mNncW

This is an option in Sonarr and I see several issues reports that this was a feature in Radarr. Am I missing something or was it taken out? I have found [reddit threads](https://www.reddit.com/r/radarr/comments/5qvjg9/import_failed_path_does_not_exist_or_is_not/) and tried making the docker volume be
-v /storage/downloads/complete:downloads/complete \
-v /storage/downloads/complete:downloads/
and a few other variations.

What I realized was that I needed the storage part of the path, because duh it didn't realize it was on a different host
-v /storage/downloads/complete:/storage/downloads/complete \

So my question is what happened to the remote path mapping option for nzbget?

Version
0.2.0.696
Mono Version
5.0.0 (Stable 5.0.0.100/9667aa6 Thu May 11 14:33:04 UTC 2017)

**Logs:**
17-5-24 20:28:49.8|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: /storage/downloads/complete/movies/Beauty.and.the.Beast.2017.1080p.BluRay.DTS.x264-ZQ
17-5-24 20:28:49.8|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: /storage/downloads/complete/movies/Logan.2017.NOIR.EDITION.1080p.BluRay.x264-SNOW
17-5-24 20:28:51.0|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: /storage/downloads/complete/movies/How.to.pay.for.your.Sites.EXTENDED.2015.1080p.x264.BluRay-AN0NYM0US
17-5-24 20:28:51.0|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: /storage/downloads/complete/movies/John Wick Chapter 2 2017 720p WEB-DL X264 AC3-EVO

**Comment by galli-leo** [comment]
Remote Path Mappings are found under Settings -> Download Clients (Advanced Settings have to be shown)
