### ISSUE TITLE
Movie renaming on Remux files (audio type)

### ISSUE THREAD

**Issue by Quiksmage** [Radarr/Radarr#1571]
I'm on the latest Develop, 0.2.0.696  
  
I'm finding that Remux files aren't incorporating the audio type into the file naming.  
  
For instance,  
I Am Sam.2001.1080p.Blu-ray.h.264 Remux.DTS-HD MA-decibeL  
gets renamed to  
I Am Sam (2001) [Remux-1080p ]-decibeL.mkv  
using the following "standard movie format"
{Movie Title} ({Release Year}) [{Quality Title} {MediaInfo Simple}]-{Release Group}  
All other files correctly become similar to the below example  
The Movie Title (2010) [Bluray-1080p x264 DTS]-EVOLVE  
  
I was expecting the name to end up like  
"I Am Sam (2001) [Remux-1080p h264 DTS-HD MA]-decibeL"  

Is this something that can be added or was there a design philosophy behind this?

Thanks!

**Comment by galli-leo** [comment]
I think it's just mediainfo screwing up or something. I have to take a look at that.

**Comment by PnoT** [comment]
I'm having a similar issue and not sure if it's related but it's also with remux files on two different systems.

The first system is a Synology with the radarr package installed:
mono 4.6.2 / latest radarr / mediainfo v0.7.93
TEST.(2017).Remux-1080p.x264.Atmos.TrueHD-GRP.mkv
TEST.(2016).Remux-1080p.Proper.x264.DTS-HD.MA-GRP.mkv

My second system is a FreeNAS jail and an install using ports vs. pkg:
mono 4.8.1 / latest radarr package / mediainfo v0.7.96
TEST.(2017).Remux-1080p.x264.TrueHD-GRP.mkv
TEST.(2016).Remux-1080p.Proper.x264.DTS-GRP.mkv

You can see that it strips off some of the mediainfo for the audio portion and there's nothing in the logs (debug or trace) that point to any errors.

**Comment by Quiksmage** [comment]
To add,

if you use the rename functionality in radarr after it makes its original incorrect rename,
it will rename it properly.
http://i.imgur.com/pVue2JB.png
So, it's specifically the initial import rename that is having problems.
