### ISSUE TITLE
Radarr not finding file after Torrent is downloaded - INTERMITTENTLY

### ISSUE THREAD

**Issue by Lusiphur** [Radarr/Radarr#1572]
**Description:**
Radarr grabbed 2 films at the roughly the same time.

One file is copied into the right path and the other isn't.

I have a torrent blackhole set up that is looking for files under

/mnt/md0/SonarrWatch/Complete/Movies

ls -lrt /mnt/md0/SonarrWatch/Movies/Complete/Movies/John.Wick.Chapter.2.2017.720p.WEB-DL.X264.AC3-EVO/
total 2715028
-rw-rw---- 1 lusiphur lusiphur        707 May 23 20:16 John.Wick.Chapter.2.2017.720p.WEB-DL.X264.AC3-EVO.nfo
-rw-rw---- 1 lusiphur lusiphur 2780179539 May 23 20:17 John.Wick.Chapter.2.2017.720p.WEB-DL.X264.AC3-EVO.mkv

This file is continually ignored.

Logs ..

17-5-25 20:06:22.1|Info|RssSyncService|RSS Sync Completed. Reports found: 50, Reports grabbed: 0
17-5-25 20:34:09.2|Info|NzbSearchService|Searching 1 indexers for [John Wick: Chapter 2]
17-5-25 20:34:09.7|Info|DownloadDecisionMaker|Processing 17 releases
17-5-25 20:34:23.9|Info|RefreshMovieService|Updating Info for John Wick: Chapter 2
17-5-25 20:34:24.7|Info|DiskScanService|Scanning disk for John Wick: Chapter 2
17-5-25 20:34:31.0|Info|NzbSearchService|Searching 1 indexers for [John Wick: Chapter 2]
17-5-25 20:34:31.6|Info|DownloadDecisionMaker|Processing 17 releases

However, another movie (Logan) grabbed at roughly the same time works ok.

**Radarr Version:**

Version
    0.2.0.696
Mono Version
    4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4)

**Logs:**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by galli-leo** [comment]
The log is not actually for the import of the file, can you find that log?

**Comment by gustavohw** [comment]
Same, grabbed Oblivion.2013.BluRay.1080p.DTS.x264-CHD for testing on Radarr\downloads\, downloads fine but upon completion it says there's no file
![image](https://cloud.githubusercontent.com/assets/9591142/26616538/d497038a-45a5-11e7-822b-e85c7d45191e.png)

Even when there's clearly a file on the following folder structure: Radarr\downloads\Oblivion.2013.BluRay.1080p.DTS.x264-CHD [PublicHD]

**Comment by galli-leo** [comment]
What are your docker path mappings for Radarr?

**Comment by gustavohw** [comment]
Host | Container
------------ | -------------
/home/gustavo/samba/wd2tb/Radarr/config | /config
/home/gustavo/samba/wd2tb/Radarr/downloads | /downloads
/home/gustavo/samba/wd2tb/Radarr/movies | /movies

**Comment by galli-leo** [comment]
Yeah, I think the problem is, that Radarr sees the path as /downloads, but your download client tells radarr to search in /home/gustavo/samba/wd2tb/Radarr/downloads. Obviously Radarr then fails. See here for how to get that fixed: https://forums.sonarr.tv/t/how-to-determine-remote-path-settings/10645/15

**Comment by gustavohw** [comment]
Got it working as galli-leo instructed using the following configuration.

If any Docker users have this problem when using **Radarr as a container** and a **torrent client running on the host**, this can solve the issue:

![image](https://cloud.githubusercontent.com/assets/9591142/26702999/e428a21e-46fd-11e7-85ab-5943bb96e433.png)
