### ISSUE TITLE
"Import failed, path does not exist or is not accessible by Radarr "

### ISSUE THREAD

**Issue by nuentes** [Radarr/Radarr#1574]
I have Radarr running through Mono in Ubuntu 16.04. When files are downloading from NZBget, I'm seeing tons of the titular error message. This is because the NZBget download directory is within my user folder (/home/username/), which Radarr does not have access to. I searched open and closed threads and the Common Problems page, but couldn't find an answer of how to do this. I feel this is because most linux users would actually know what to do, but I'm not the best with linux.

Lastly, as I write this, I realize I have a 2nd issue. NZBget automatically renames and moves my movies. I'm planning to let NZBget retain that function. However, Radarr again can't find the files when they are moved, and I believe it is because I do not put the movies into individual subfolders. This is a setup that I prefer, and I'd rather not mess with. I assume that this is expected, and the answer is "suck it up and change", but I want to check if I have an alternative.

**Comment by galli-leo** [comment]
Regarding the first issue, something like `chmod 777 /home/username/PATH/TO/DOWNLOAD/LOCATION` should work.

Regarding the second issue, why would you have NZBGet rename the file if Radarr does that too for you? Also, we want to add support for all movies in one folder, but for now you would have to change that.

**Comment by hotio** [comment]
I hate to be the bad guy here, but "suck it up and change"

Make sure that radarr can access the files in `/home/username/PATH/TO/DOWNLOAD/LOCATION` like galli-leo said, this means radarr wil also need proper rights for `/home/username` or any other folder above the final location.

**Comment by nuentes** [comment]
Ok, I've done the chmod, and hope that takes care of it. That would be nice if you added support for all movies in one folder - I'll just deal with it for now. I have what appears to be a unique system - movies that I haven't watched are all in a single folder and kodi scans using external data, and movies that I've watched and like are archived to a different path where I manually download local data for kodi to use. These are neatly placed in subfolders. So I maintain a messy system alongside a very neat system.

I already had NZBget renaming files, and I got that configured just how I like it a while ago, so I don't have an interest in teaching Radarr how to name/move the files. My current system is configured to cover all my bases at once - manual downloads get renamed and moved using the same rules as automated downloads. It's a system that I like.

**Comment by hotio** [comment]
Well if you don't like how radarr operates/or its features, there's not much to say than it would be better for your use case to not use it, instead stick to your current setup.

**Comment by nuentes** [comment]
Hey dude, that's not productive. I'm not complaining about anything, and I'm happy with Radarr, I was just trying to get help with an issue and answer the question galli-leo asked while I was here.

**Comment by hotio** [comment]
Sorry about that, I don't really see the point of why somebody would want to use an app if he's going out of his way to bypass the main feature set of that app...according to me that's called not being productive.
