### ISSUE TITLE
Filtering issues on Home Page

### ISSUE THREAD

**Issue by AD-CLE** [Radarr/Radarr#1575]
love the app, thank you all for your work.  

I am using version: 0.2.0.696 & have 800+ movies added
**The All | Monitored | Missing | .. Filter on the home page doesn't do anything**
this used to work before when i had only ~100-200 movies in the database.

Sorry of this is a dupe, its my first time and i wasn't able to find the issue

**Comment by hotio** [comment]
Works fine with:

Radarr Ver. 0.2.0.719
Total movies: 383

Perhaps you should have some more patience for it to adjust the layout?

**Comment by delphiactual** [comment]
@AD-CLE What are you sorting your movie list by?

**Comment by galli-leo** [comment]
Try clearing cache and cookies as well.

**Comment by AD-CLE** [comment]
Patience is not an issue i think 1 hour is plenty time to filter and sort through 800 lines of data

 All | Monitored | Missing all 3 result in the same list of All movies.

Tried clear Cache, also tried Incognito.  

Any other suggestions?

**Comment by galli-leo** [comment]
Can you open Chrome Dev Console and then start filtering? You should see some errors. Could you post them here?

**Comment by AD-CLE** [comment]
I am not an expert but from what I can tell it keeps timing out and doesn't know what to do next.  

4vendor.js:25334 sync received, re-fetching collection
vendor.js:24909 Config: [Radarr.series.filterMode] => [monitored]
3vendor.js:25334 sync received, re-fetching collection
Config.js:56 Config: [Radarr.series.filterMode] => [all]
19backbone.signalr.mixin.js:15 sync received, re-fetching collection
Config.js:56 Config: [Radarr.series.filterMode] => [monitored]
backbone.signalr.mixin.js:15 sync received, re-fetching collection

**Comment by galli-leo** [comment]
That is probably what's happening. Have you tried setting the page size lower?

**Comment by AD-CLE** [comment]
I changed it from 250 to 50 still no change.

it feels odd that i am the only one with this issue

**Comment by galli-leo** [comment]
Can you post a screenshot of your chrome dev console?

**Comment by AD-CLE** [comment]
consol:

![image](https://user-images.githubusercontent.com/28768487/26927258-19538c6c-4c1f-11e7-8ade-cd79886a860b.png)


main screen with the filters:

![image](https://user-images.githubusercontent.com/28768487/26927284-3db47ac6-4c1f-11e7-9fa5-040af2531f62.png)

please let me know if there is something else i can share

**Comment by galli-leo** [comment]
Can you try a different browser? This has sometimes worked in the past.

**Comment by mbedouet** [comment]
I see this problem too, but only when the movies are sorted by "downloaded".

**Comment by AD-CLE** [comment]
Thats it!!! Thank you.  
Cant believe I didn't realize that sooner.

**Comment by hotio** [comment]
I wouldn't close this issue, because it seems we have a sorting bug going on...
Perhaps edit the title to reflect the real issue and re-open?

**Comment by galli-leo** [comment]
There should be already an issue open for this. Basically, we can only have one filter active and sortng by downloaded acts as one filter. So this currently behaves as it should. I have some plans ln correcting this though.
