### ISSUE TITLE
[Feature Request] Import Extra Files ala Sonarr 

### ISSUE THREAD

**Issue by danjames92** [Radarr/Radarr#1577]
Couldn't see this requested yet so thought I'd post. I rely on this feature with sickbeard_mp4_automator to transcode and move an original copy to a new location via the Import Extra Files option. Would be fantastic to see this in Radarr. 

Thanks for the brilliant work so far.

**Comment by hotio** [comment]
So you want a copy/paste of the following Sonarr feature?
![naamloos](https://cloud.githubusercontent.com/assets/26902309/26520250/f2d45908-42ce-11e7-9d54-80cc773aefbf.png)

**Comment by danjames92** [comment]
Yes that's exactly it. I use it to populate it with .mkv and .srt which allows the converted mp4 and the original .mkv to be moved into the same location.

**Comment by desimaniac** [comment]
+1

**Comment by galli-leo** [comment]
Sorry only noticed it now, this is a duplicate of #121
