### ISSUE TITLE
Need some help

### ISSUE THREAD

**Issue by pikachukaki** [Radarr/Radarr#1578]
Firstly how can i setup the wanted so when i press search all it doesn't search all my movies specially the ones that didnt even release in cinemas?

Also how i can properly setup so when a movie is downloaded utorrent download it to users/downloads and after completion it moves it to my D drive but still keeps the file in users/downloads?

**Comment by hotio** [comment]
1) Filter by: Released Only

2) Radarr should by default copy it and not remove them, if "Remove" is set to NO
