### ISSUE TITLE
"Forget" old root folders?

### ISSUE THREAD

**Issue by janipewter** [Radarr/Radarr#1579]
Is there a way to make radarr "forget" previously used folders?

I moved my radarr install from one server to another, and due to the set up of my shared storage, the file paths changed slightly. Example:

old setup, movies were located like:
/mnt/films

new setup, movies are located like:
/media/films

When I moved radarr to the new machine I simply imported the old config in, then did a mass edit of the movie paths to change them from /mnt/films to /media/films. It works fine.

However, radarr seems to "remember" the old path, /mnt/films, and when adding new movies, it always uses that as the default root folder.

What I want to do is make radarr completely forget that /mnt/films exists at all (because it doesn't, from the point of view of this server). Is it possible to do this?

**Comment by hotio** [comment]
The only real way to completely get rid of them all is by editing the database directly AFAIK.

**Comment by RomRider** [comment]
You can use "add movie" -> "bulk import", then you'll have a pupop with your old folder (and also the new one), just click the red cross on the right and its reference will be deleted from Radarr.

**Comment by galli-leo** [comment]
Or everywhere you can add a new path (e.g. lists, adding new movies, etc.)

**Comment by jfairham1** [comment]
I have the same issue after importing from a backup on a new machine. All the paths on the existing movies have been amended to /media/movies in movie editor. I have done "bulk add movies" and deleted the old path /home/media/movies, also checked adding new movies, so no reference to the old root path exist. When radarr imports a movie, it still tries to import to the old path, even though it doesn't exist anywhere now and obviously fails the import. 
![image](https://user-images.githubusercontent.com/6381600/42418736-5be13136-829e-11e8-9015-e5e7c81821e4.png)

**Comment by Qiyamatawil** [comment]
only i still get an alert under system saying "missing root folder" even when its not in the list under import anymore.

**Comment by galli-leo** [comment]
@Qiyamatawil Make sure you do not have any movies with that path still in your library.

**Comment by Qiyamatawil** [comment]
> @Qiyamatawil Make sure you do not have any movies with that path still in your library.

scanned thru my near 2k movies via movie editor till my eyes hurt then just decided to select all and change "root folder" to the only location i am now using. did a restart and it seems to have cleared it up.  thanks.

(this would have been much more difficult if i used more than 1 location though id assume)

**Comment by dylanjboyd** [comment]
For anyone that comes across this and still has this issue, I had to set a new `RootFolderPath` for all rows in the `NetImport` table. 

Until doing so, all newly added movies from lists would download to an old path irrespective of whether they appeared to be correctly set in the Lists tab.

**Comment by TheManchineel** [comment]
Reporting here, I had to change the path in Ombi, otherwise all new movies requested would set themselves as stored in the old root. After changing the root in Ombi, relocating all the dangling movies I had not ripped yet to the proper root and restarting Radarr, the warning is gone!

**Comment by fryfrog** [comment]
@dylanjboyd: To fix it coming from lists, I think you need to save the list with a *different* path, then re-save it w/ the *right* path. But if you only have one root folder, that isn't possible. I *think* the UI is pre-selecting the new root folder because it is the *only* one, which makes it look right. I'm not sure what happens when you save in this case.
