### ISSUE TITLE
King Arthur: legend of the sword finding wrong movie 

### ISSUE THREAD

**Issue by lessthantom** [Radarr/Radarr#1581]
Keeps finding some other film from same year King Arthur and the knights of the round table

**Comment by onedr0p** [comment]
It's usually because your indexer assigned it the wrong imdbid.

**Comment by lessthantom** [comment]
I have a few indexers loaded so I'll bin off a few and do some testing cheers bud

**Comment by raysguy** [comment]
I was having the same issue.  Assigned the movie a custom tag [kingarthur] then in indexer settings I added a restriction to apply only to the [kingarthur] tag with "Must contain" [sword], "Must not contain" [table].  Seems to have done the trick and stopped it trying to grab the other movie repeatedly.

**Comment by lessthantom** [comment]
Cheers raysguy ive done that and it seems to be blacklisting all those, thanks for the heads up
