### ISSUE TITLE
Wanted List 'Search All' function Failing

### ISSUE THREAD

**Issue by fluffythecat** [Radarr/Radarr#1582]
Greetings. I've been a user of Radarr for a while and something has happened that I haven't experienced before. This started this morning and the issue I am having is that the 'search all' in the 'Wanted' tab seems to be broken. Using the 'search all' will notify as usually that a search is started but, flashes quickly of all the titles with a result if 0. However, if I manually select a movie and use the 'search selected' button it will search the index and grab the movie for download. I tested this a few times adding up to 5 manually selected movies that failed during the 'search all' but were found using 'search selected'.

I have attached the log file, any help is greatly appreciated. Thank you!

[radarr.txt](https://github.com/Radarr/Radarr/files/1033778/radarr.txt)

**Comment by galli-leo** [comment]
From the logs, it seems Rargb.to is goofing and claiming that Toy Story Toons: Hawaiian Vacation (imdb: tt1850374) does not exist on IMDB. I would suggest either removing that movie, contacting rargb about it (though I am sure it's just due to cache so it should start working after a while) or manually downloading it.

**Comment by fluffythecat** [comment]
> I would suggest either removing that movie, contacting rargb about it (though I am sure it's just due to cache so it should start working after a while) or manually downloading it.

I have removed the movie from my list and searched it manually. Sure enough it actually was not available on rarbg, however it still seems to be failing on the 'search all' button. 

"[v0.2.0.696] NzbDrone.Core.Indexers.Exceptions.IndexerException: Indexer API call returned error 10: Cant find imdb in database. Are you sure this imdb exists?
   at NzbDrone.Core.Indexers.Rarbg.RarbgParser.ParseResponse(IndexerResponse indexerResponse) in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\Rarbg\RarbgParser.cs:line 38
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 297
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchReleases(IndexerPageableRequestChain pageableRequestChain, Boolean isRecent) in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 154

17-5-28 10:16:07.9|Info|DownloadDecisionMaker|No results found
17-5-28 10:16:07.9|Info|NzbSearchService|Searching 0 indexers for [Skyfall]
17-5-28 10:16:07.9|Info|DownloadDecisionMaker|No results found
17-5-28 10:16:07.9|Info|NzbSearchService|Searching 0 indexers for [Spectre]
17-5-28 10:16:07.9|Info|DownloadDecisionMaker|No results found
17-5-28 10:16:08.0|Info|NzbSearchService|Searching 0 indexers for [The Birdcage]
17-5-28 10:16:08.0|Info|DownloadDecisionMaker|No results found
17-5-28 10:16:08.0|Info|MovieSearchService|Movie search completed. 0 reports downloaded.
17-5-28 10:17:09.7|Error|DetectSample|[Z:\Completed Downloads\Sonarr Library\James Bond Diamonds Are Forever (1971)\~uTorrentPartFile_38454E49.dat] has a runtime of 0, is it a valid video file?
17-5-28 10:18:09.2|Info|RssSyncService|Starting RSS Sync
17-5-28 10:18:09.2|Warn|FetchAndParseRssService|No available indexers. check your configuration.
17-5-28 10:18:09.2|Info|DownloadDecisionMaker|No results found
17-5-28 10:18:09.2|Info|RssSyncService|RSS Sync Completed. Reports found: 0, Reports grabbed: 0
17-5-28 10:18:58.5|Info|MovieService|Linking [Diamonds Are Forever (1971) Bluray-720p.mp4] > [[tt0066995][Diamonds Are Forever (1971)]]
17-5-28 10:18:58.5|Info|MovieService|Linking [Diamonds Are Forever (1971) Bluray-720p.mp4] > [[tt0066995][Diamonds Are Forever (1971)]]
17-5-28 10:18:58.5|Warn|DownloadedMovieImportService|Unable to parse file on import: [Z:\Completed Downloads\Sonarr Library\James Bond Diamonds Are Forever (1971)\~uTorrentPartFile_38454E49.dat]
17-5-28 10:19:39.2|Warn|HttpClient|HTTP Error - Res: [GET] http://localhost:41611/gui/?token=(removed)&list=1&cid=1379288156: 400.BadRequest
17-5-28 10:20:40.2|Error|DetectSample|[Z:\Completed Downloads\Sonarr Library\James Bond GoldenEye (1995) [1080p]\~uTorrentPartFile_76A30941.dat] has a runtime of 0, is it a valid video file?"

For Skyfall, just to test it out, I manually searched it on rarbg and it was available in the profile quality I have set. Any idea what could be causing it?

**Comment by galli-leo** [comment]
What is the log message before this one?:
[v0.2.0.696] NzbDrone.Core.Indexers.Exceptions.IndexerException: Indexer API call returned error 10: Cant find imdb in database. Are you sure this imdb exists?
at NzbDrone.Core.Indexers.Rarbg.RarbgParser.ParseResponse(IndexerResponse indexerResponse) in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\Rarbg\RarbgParser.cs:line 38
at NzbDrone.Core.Indexers.HttpIndexerBase1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 297 at NzbDrone.Core.Indexers.HttpIndexerBase1.FetchReleases(IndexerPageableRequestChain pageableRequestChain, Boolean isRecent) in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 154

**Comment by galli-leo** [comment]
Fixed on latest release.
