### ISSUE TITLE
Support sub directories in movie naming

### ISSUE THREAD

**Issue by radeonorama** [Radarr/Radarr#1583]
Currently with Couch Potato I have each movie renamed and moved to a quality folder then within that, the movie title. 

for example
c:\movies[1080p]\some movie name\some movie name.mkv
c:\movies[720p]\some other movies name\some other movie name.mlv

I just do this in the Folder Naming setting within couch potato. 

This enabled me to setup distinct movie libraries within my front end (plex and emby) without needing to use filters etc, i.e. they're already filtered by which folder they get placed in

I was really hoping that Razarr would allow me to do the same but it doesn't want to accept the slashes and is converting them to +. Is this something i can do or would it be a feature request?
Cheers

**Comment by galli-leo** [comment]
We will be only supporting the folder structures also officially supported by Plex:
`C:\Movies\My Movies\My Movie.mkv`
`C:\Movies\My Movie.mkv`
Maybe in the future we will revisit this request, but for now, this creates just too much confusion and (IMO) is completely unnecessary if you have a decent front end (such as Plex).

**Comment by radeonorama** [comment]
That structure still is supported by plex, I use it in my current configuration. 

I'll be a shame if you can't support it as Radarr looks good but it makes it a deal breaker for me.

**Comment by radeonorama** [comment]
Hi, has there been any change here? It's literally the only thing stopping me from moving over to Radarr :-(

**Comment by CBers** [comment]
+1

**Comment by CBers** [comment]
It seems that Radarr has a bug with substituting a \ with a + in the Movie Folder name.

If you set:

Movies[{Quality Title}]\[{Movie Title}] ({release year})

You get:

Movies[Bluray-1080p]+[The Movie Title] (2010)

**Comment by radeonorama** [comment]
As its all done within the the same Movie Folder Format field there isn't really much to confuse the user. Basically I just want to have [{Quality Title}]\\{Movie Title} ({Release Year}) [{Quality Title}] but the slash after [{Quality Title}] is being changed to a + (plus).

Can't the slash just be allowed?

**Comment by drwyrm** [comment]
Please reconsider. With a lot of movies it gets very sluggish to list the root folder. It would be great to have my collection in {release year} subfolders.
