### ISSUE TITLE
Question : having multiple "look here for new movies" folders

### ISSUE THREAD

**Issue by Symbiot78** [Radarr/Radarr#1585]
As topic..

can Radarr look in more than 1 location for new movies?

I've setup so I get new animation movies in a folder called "animation"
new "normal" movies in a folder called "movies" 
etc etc
I then would like to process movies in "animation" and add them to a "processed" folder called "animation"

same with movies etc.

possible?

**Comment by galli-leo** [comment]
Radarr cannot even do what you request with one folder. Not sure if we ever are going to support that (since matching movies can go wrong more often than not). But there already is an issue open for this feature, so closing this as a duplicate.
