### ISSUE TITLE
Bulk insert identifying trailer video files

### ISSUE THREAD

**Issue by bobby-tables-2048** [Radarr/Radarr#1586]
On bulk import, Radarr is selecting trailer video files when a proper movie file exists in the folder. I can't see any pattern to it's selections or any reference to "trailer" in the logs.

Radarr version 0.2.0.696 on Ubuntu Server.

screenshot - wrong files selected
![image](https://cloud.githubusercontent.com/assets/26698587/26527498/6af86fc8-43d8-11e7-9b1a-7f7146df68f8.png)

**screenshot - typical movie folder
![image](https://cloud.githubusercontent.com/assets/26698587/26527525/23707226-43d9-11e7-815f-df3cb30a50fb.png)

**Comment by galli-leo** [comment]
That will not be a problem. We just choose the first movie Radarr can find for the bulk import to give a rough overview of the user's collection. Upon importing the files will be verified to not be trailers.
