### ISSUE TITLE
Radarr can't parse a filename it generated

### ISSUE THREAD

**Issue by mooop12** [Radarr/Radarr#1587]
Filename: `Back to the Future - 1080p Bluray VC-1 DTS-HD MA FGT.mkv`

Logs:

```
17-5-28 13:36:17.0|Debug|Parser|Parsing string 'Back to the Future - 1080p Bluray VC-1 DTS-HD MA FGT.mkv'
17-5-28 13:36:17.0|Debug|Parser|Unable to parse Back to the Future - 1080p Bluray VC-1 DTS-HD MA FGT.mkv
17-5-28 13:36:17.0|Debug|Parser|Attempting to parse episode info using directory and file names. Back to the Future (1985)
17-5-28 13:36:17.0|Debug|Parser|Parsing string 'Back to the Future (1985) Back to the Future - 1080p Bluray VC-1 DTS-HD MA FGT.mkv'
17-5-28 13:36:17.0|Debug|Parser|Movie Parsed. Back to the Future - 1985 
17-5-28 13:36:17.0|Debug|Parser|Language parsed: English
17-5-28 13:36:17.0|Debug|QualityParser|Trying to parse quality for Back to the Future (1985) Back to the Future - 1080p Bluray VC-1 DTS-HD MA FGT.mkv
17-5-28 13:36:17.0|Debug|Parser|Quality parsed: Bluray-1080p v1
17-5-28 13:36:17.0|Debug|Parser|Release Group parsed: HD
```

Radarr version: 0.2.0.696

**Comment by galli-leo** [comment]
Yeah, if the filename does not contain the year we cannot parse it. We probably should prevent people from not putting the year in the format.

**Comment by mooop12** [comment]
There's one more thing it seems, Radarr thinks that the `HD` part of `DTS-HD MA` audio description is the release group of the movie. I added the year to the movie name and it parsed the movie itself properly but the release group was still `HD`.

**Comment by galli-leo** [comment]
Yeah, it will always take the last -SOMETHING as a release group. Not much we can do about that, except tell people to include release group in their naming.

**Comment by Qstick** [comment]
@galli-leo is this issue open just to add validation to require year in naming scheme?

**Comment by onedr0p** [comment]
This is an old issue tagged with UI, this is very likely fixed in v3. Please let us know otherwise (and even if you want this feature in v3) and we will reopen the issue.
