### ISSUE TITLE
Radarr - Directory and movie Name

### ISSUE THREAD

**Issue by Nibeck1309** [Radarr/Radarr#1588]
Hello,

My videotheque is organized in the following way:

- Movie Saga
         - Film1_ (Year)
              - movie file
         - Film2_ (Year)
              - movie2 file
         - etc ...
Or If no Saga for the film concern

- Movie title_ (Year)
      - movie file

In Raddar I can't Name The Saga in 
Settings -> Media Management -> Movie Folder Format

Is there a way for this?

Thks

**Comment by galli-leo** [comment]
Currently no. We plan on adding collections of movies (e.g. James Bond, LOTR, etc.) But that's currently not possible :/ There's an issue already open for this ( #112 ), so gonna close this as a duplicate.
