### ISSUE TITLE
Remove space from AHD api key

### ISSUE THREAD

**Issue by tman012** [Radarr/Radarr#1589]
The way Radarr passes a torrent from AHD (Awesome-HD) to the client (in my case, Deluge) the tracker URL is being sent with a space before 'announce'. This is causing the tracker status to report Error: Malformed announce.
 
The tracker URL for example is: http://moose.awesome-hd.me/##xxxxxxxxxxxxxx /announce
You can see in that URL there is a space before the /announce, this is causing the error. The URL should be http://moose.awesome-hd.me/##xxxxxxxxxxxxx/announce and when manually editing the URL within the client to remove the space, everything works correctly.

Is there something in the configuration file for the AHD indexer that is incorrect and causing that space? I haven't tested any other Radarr dockers and I'm on the latest version for both linuxserver Radarr and linuxserver Deluge. I've tried sending the file both ways, directly to the client, and to a blackhole where it is picked up - both give the same space in the URL causing an error.

**Comment by tman012** [comment]
I tested with another docker, the binhex repository and it appears to be working correctly using that docker. I'm assuming this is mainly limited to the linuxserver docker itself. So I don't know if this should be deleted then, or stay for visibility.

**Comment by MisterSkilly** [comment]
I have this exact same error on the latest develop release.

**Comment by tman012** [comment]
Can you be more specific? Where did you get to that setting? I'd like to fix this because I'm still mainly just modifying manually for now whenever it happens to grab from AHD.

**Comment by MisterSkilly** [comment]
There was a space where the yellow rectangle is, remove that and then click save.
