### ISSUE TITLE
API endpoint for Add+Search?

### ISSUE THREAD

**Issue by dubstrike** [Radarr/Radarr#1591]
I made a Telegram bot for adding movies to the Radarr library but unfortunately they aren't grabbed even when available. I have to manually trigger the search through the Web UI.

**Is there a way to force the search when adding a movie through the API?**

That's what I'm POST-ing:
```
{
  "title": "${movieTitle}",
  "path": "../${movieTitleYear}",
  "qualityProfileId": 6,
  "images": [{
    "coverType": "poster",
    "url": "https://image.tmdb.org/t/p/w1280/${posterURL}"
  }],
  "monitored": true,
  "titleSlug": "",
  "minimumAvailability": "announced",
  "imdbId": "${imdbID}",
  "tmdbId": "${tmdbID}"
}
```

**Comment by galli-leo** [comment]
You can set the addOptions to get the desired effect:

```
{
...
    "addOptions" : {
        "searchForMovie" : true
    }

...
}

```

**Comment by dubstrike** [comment]
Awesome, thanks!

**Comment by SpencerCurtis** [comment]
Was also looking for this! The API's documentation doesn't seem to mention any of the addOptions. Is there an endpoint to see them all, or would you perhaps be able to add a list of them to the documentation for future reference?

**Comment by galli-leo** [comment]
@SpencerCurtis You can edit the documentation yourself :) I don‘t plan on really expanding the documentation, especially with the new UI probably requiring some new endpoints. However, ususally the chrome dev tools give you the information needed for replicating the functionality of Radarr itself. I don‘t think we have any more add options than are used in the WebInterface. Another way to get this info, is just looking through the code.

**Comment by SpencerCurtis** [comment]
Sounds great, I'll submit a PR then. Thanks!

**Comment by pugson** [comment]
@galli-leo Any chance this option might have stopped working with recent updates?
