### ISSUE TITLE
discription "title and comments" removal or adjustment for mp4

### ISSUE THREAD

**Issue by Nukem51** [Radarr/Radarr#1596]
currently movies collected from certain locations include data in the title and comments for the file's properties. this additional information causes plex to add a bunch of special characters to to the movie's name. it would be nice to have radarr automatically remove this information. this problem is also present in sonarr. so the solution would be to delete this information in the renaming process or just change it to the movie name with no special information.

**Comment by galli-leo** [comment]
@fedoranimus @onedr0p Do we want to do this? Isn't it the job of plex to choose not to use that data? 

@Nukem51 You can set plex to ignore local assets, this way the titles from online sources are used.

**Comment by Nukem51** [comment]
I was in aware of that. It just was getting obnoxious with all the periods and scene release names populating threw.

**Comment by galli-leo** [comment]
Well since fedoranimus and onedrop are not responding, I am deciding this is not our job and you can either solve this via scripts or tell Plex to stop looking at local metadata.
