### ISSUE TITLE
[Feature Request]: Match of "Movie File Not Found" files on Bulk import

### ISSUE THREAD

**Issue by JohanPotgieter** [Radarr/Radarr#1598]
When you Bulk import many movies are marked as "Movie File Not Found". The reason for me is that all my older movies don't contain the year in the name. The folder may be called "A Nightmare On Elm Street 1" and the file will be called "A Nightmare On Elm Street 1.mp4". The Tmdb Id is found by Radarr but the file in the directory is not associated.

My suggestion would be to have a option to associate any video file with that Tmdb Id. So instead of being so strict that the movie "A Nightmare On Elm Street" must be called "A Nightmare On Elm Street (1984)" just associate the video file in the folder with the Tmdb Id you are about to import. This makes perfect sense if there is only one file in the folder. If you don;t want to make that assumption then at least give us the option to select the file as the correct one for the movie in question.

This will help out a lot of people. Most of us have been collecting movies for a long time and to go back and fix old files is just not a option for most. I already did this work when I added my collection to Plex a few years ago.

![radarr example](https://cloud.githubusercontent.com/assets/12456610/26574958/c0b4596a-4566-11e7-807e-fa0a0fe31267.JPG)

**Radarr Version:**
0.2.0.696

**Comment by oskarhart** [comment]
I have some .m4v files that the same happens, it seams to be that the filename is ok but not the extension

**Comment by JohanPotgieter** [comment]
It may be a good idea to have a tick "associate and rename". If this is selected then the file is renamed using the rename option preferred by Radarr. This will also solve future issues with this file.

**Comment by XeonNAS** [comment]
I would have hoped that when importing it would use the existing folder/file renaming logic to do the match between the movie file and folder and imdb id. So if you renamer is set to rename to {Move Title} then that is all it matches on, year becomes irrelevant in this case. Ditto for folder naming standards, could have {Movie Name ({Release Year})} for the folder, yet all would still match.
