### ISSUE TITLE
[Radarr] select whitch indexer used for better movie information

### ISSUE THREAD

**Issue by Nibeck1309** [Radarr/Radarr#1602]
Hello,
I'm french user of radarr and i love it.
Congratulation for your works

Is it possible to create a checkbox for the parameters to select which indexer to use for movies information and search

I've add Raid Dingue Movie and 
- for imdb it's 2016 film
- for trakt it's 2017 film
- for tmdb it's 2017 film

the good answer is 2017 film.

Thks

**Comment by galli-leo** [comment]
Fixed with alternative year and force downloading.
