### ISSUE TITLE
Movie Editor: Checking box for all movies only selects 3 movies

### ISSUE THREAD

**Issue by brimur** [Radarr/Radarr#1603]
Ive tried restarting the service numerous times and selecting just "missing" but no matter what I do, when I select all movies (checkbox at the top next to Title) it only selects three movies.

https://i.imgur.com/livr33Q.png

Radarr Ver. 0.2.0.696
develop

**Comment by galli-leo** [comment]
Can you try clearing cache & cookies, incognito window and another browser?

**Comment by brimur** [comment]
Thank you that worked!
