### ISSUE TITLE
Movies not showing up in Activity Queue

### ISSUE THREAD

**Issue by deliverer33** [Radarr/Radarr#1607]
**Description:**

Bug.  Since upgrading to 0.2.0.724, movies downloaded do not appear in the activity queue while downloading.  The history shows the file was sent to nzbget.  Nzbget completes the download and places in the complete directory.  Radarr doesn't complete the rename and move process.

Not much in logging.

17-6-1 09:25:21.5|Info|NzbSearchService|Searching 3 indexers for [Star Trek Beyond]
17-6-1 09:25:28.2|Info|DownloadDecisionMaker|Processing 167 releases
17-6-1 09:25:40.8|Info|Nzbget|Adding report [Star.Trek.3.Beyond.2016.1080p.BluRay.DTS.x264-CyTSuNee] to the queue.
17-6-1 09:25:41.2|Info|DownloadService|Report sent to local.nzbget. Star.Trek.3.Beyond.2016.1080p.BluRay.DTS.x264-CyTSuNee
17-6-1 09:34:21.4|Info|PreDBService|Starting PreDB Sync

I also restarted radarr to see if that would resolve the problem.  It did not.

**Comment by galli-leo** [comment]
Can you enable debug logging and post the logs?

**Comment by deliverer33** [comment]
An update on this issue.  This appears to be an issue only when I click Wanted -> Select a single or all movies missing and click Search Selected.  Automatic movies searched by the system are importing correctly.

**Comment by deliverer33** [comment]
[logs.txt](https://github.com/Radarr/Radarr/files/1049110/logs.txt)

Adding logs in debug mode

**Comment by galli-leo** [comment]
Seems like this is because the release names do not match what Radarr has stored. Not much we can do about that.

**Comment by ThomasDalla** [comment]
Well, this is happening on downloads that Radarr itself has sent to NZBGet...

**Comment by deltathing** [comment]
Had this same problem, resolved when I noticed that after the update the category listed in the sab download client settings had changed. Could be something to check if you have this issue.
