### ISSUE TITLE
PLEX MEDIA SERVER Connect - Does Not Update Movies

### ISSUE THREAD

**Issue by teshiburu** [Radarr/Radarr#161]
It would appear that the PLEX MEDIA SERVER connector - still updates Series type libraries, 

I believe the change needs to be made to this file 

https://github.com/Radarr/Radarr/blob/develop/src/NzbDrone.Core/Notifications/Plex/PlexServer.cs

Can this please be looked at :)

**Comment by onedr0p** [comment]
fixed in #163
