### ISSUE TITLE
radarr not extracting downloaded movies, movie stuck in activities tab

### ISSUE THREAD

**Issue by maZuFC** [Radarr/Radarr#1610]
hi

im finding that radarr will not always process a snatched movie.
so the latest movie it hasnt done it for is The Lego Batman Movie

it snatched the movie fine and put it into uTorrent.
downloaded successfully but now the movie is stuck in the activity tab and not being processed.
i had the same issue with john wick 2

if i manually extract the movie from its rar files radarr seems to kick in then.. it will sort the file out and move it to its final destination. 

looking at the logs i cannot see any details there as to why it hasnt processed the rar files.

i am running the following version of radarr.

Version
0.2.0.696

was wondering if this is a known bug or am i missing something in my config?

thanks

z

**Comment by galli-leo** [comment]
Radarr does not do any unpacking. That is the job of your downloader. I think there are a number of scripts for uTorrent to do that.
