### ISSUE TITLE
Auto import from list - Wrong folder !

### ISSUE THREAD

**Issue by jaydee99** [Radarr/Radarr#1612]
**Description:**

Hi,

I'm having a problem with the auto-import from list feature.

I use StevenLu's list. The folder for importing movies is set to "/nfs/video/Movies" in the settings but when a movie is auto added, folder is set to "/1/video/Movies". I tried with my other path which is "/nfs/video/Animes" and then with auto add it becomes "/2/video/Animes"...

Thanx for helping !

Check first that your problem is not listed in our wiki section:
* https://github.com/Radarr/Radarr/wiki/Common-Problems
* https://github.com/Radarr/Radarr/wiki/FAQ

Provide a description of the feature request or bug here, the more details the better. 
Please also try to include the following if you are reporting a bug

**Radarr Version:**

**Logs:**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by galli-leo** [comment]
Yeah sorry about that :/ You have to delete the list and create a new one. It is fixed on the latest nightly however.

**Comment by jaydee99** [comment]
Hi,


Thanx for the answer, that dit it !


See you !


________________________________
De : Leonardo Galli <notifications@github.com>
Envoyé : vendredi 2 juin 2017 22:53
À : Radarr/Radarr
Cc : jaydee99; Author
Objet : Re: [Radarr/Radarr] Auto import from list - Wrong folder ! (#1612)


Yeah sorry about that :/ You have to delete the list and create a new one. It is fixed on the latest nightly however.
