### ISSUE TITLE
features missing like in CP?

### ISSUE THREAD

**Issue by ward0** [Radarr/Radarr#1614]
IMDB watchlist, download client in synology,...

**Comment by galli-leo** [comment]
You can add your imdb watchlist? And the synology download client should be able to be added.

**Comment by ward0** [comment]
so i add the CP list? and in my CP list i have IMDB? I only see a blackhole option..

**Comment by galli-leo** [comment]
No just add your imdb watchlist. It's a preset under RSS List.

**Comment by ward0** [comment]
ye well can't seem to find a way to make it work with a rss watchlist..
