### ISSUE TITLE
Feature Request: Bulk Tag Editing

### ISSUE THREAD

**Issue by rustymyers** [Radarr/Radarr#1616]
**Description:**

Include tags in the bulk Movie Editor for quick updating/removing of tags. Created this script to work around the lack of bulk tag adding:
https://gist.github.com/rustymyers/a68f405909224e023088c8cac6834c32

**Comment by galli-leo** [comment]
I will have to see how we could implement this. The movie editor is already crammed full of options :/

**Comment by mrbipbip** [comment]
+1 For the Bulk tag adding feature!
It would be very helpful for update a big library.

**Comment by bidulle95** [comment]
Hello I would like to know how to install this and how it is run on a nas? thank you

**Comment by rustymyers** [comment]
@bidulle95 Run Radarr or the python script to tag movies?
