### ISSUE TITLE
Feature Request: Manual Import Defaults

### ISSUE THREAD

**Issue by Quiksmage** [Radarr/Radarr#1618]
Currently "manual import" defaults to move with no ability to change the default.
I'd like to request the ability to change the default selection for manual imports, either from a setting option, or from remembering the last selection used.

I requested the same thing on Sonarr, here. https://github.com/Sonarr/Sonarr/issues/1949

**Comment by Qstick** [comment]
This should be remembered in browser cache in v3 now.
