### ISSUE TITLE
Indicate which results have been previously grabbed

### ISSUE THREAD

**Issue by bnevets27** [Radarr/Radarr#1619]
Having the results in the search tab colour coded would make it easier to determine what release was snatched and which files are preferred over the others. 

Something like how medusa has it laid out:
http://i.imgur.com/dSSh17f.jpg

**Comment by galli-leo** [comment]
You can already see which files radarr prefers by clicking on the header of the column with the download button.

**Comment by bnevets27** [comment]
Well that's definitely something I didn't know was there its also only just sorting by preference. 

I would prefer to sort by size and see why radarr is disregarding some releases. I also would like to see in that list which files radarr has grabbed. Right now you have to go back and forth between the history tab
