### ISSUE TITLE
Support for Brazilian Portuguese (pt-br)

### ISSUE THREAD

**Issue by dyorgio** [Radarr/Radarr#1626]
Portuguese (pt) and Brazilian Portuguese (pt-br) are different languages.
Currently Radarr only supports the first one to make **Quality Profiles**.

Movies like "Moana" are renamed in "pt" as "Viana", but in "pt-br" the name is equals the original ("Moana").

Movies,TV Shows, Games, any media, are translated to "pt-br" to be consumed in Brazil nobody consumes "pt" media here, when "pt-br" is not available we prefer "en" (English) version with subtitles.

**Comment by galli-leo** [comment]
What are releases with this language usually named like? For french e.g. it would be Moana.2016.French.BDRIP-rlsgroup

**Comment by dyorgio** [comment]
must have tag words: pt-br (100%)
preferred tag words: dublado (50%), ptb(25%).

**Comment by marcelobt** [comment]
Hi... Any news about it? I'm experiencing the same issue here

**Comment by dyorgio** [comment]
No, no news, I'm running last version (master branch) and have problems with "Despicable Me 3".
Radarr use pt-pt (Portugal) name to work ("Gru - O Maldisposto 3") and no pt-br version ("Meu Malvado Favorito 3 ").
All theses versions are available on TMDB (That handles EN, PT_PT and PT-BR languages different).

Maybe a easy temp solution is allow user to add manual Titles or edit current to correct.

**Comment by Koynonia** [comment]
Hi!
In Brazil the terms 'DUAL AUDIO' or simply 'DUAL' are also used a lot ...

**Comment by dyorgio** [comment]
Just include pt-br as a new language guys, come on.

**Comment by rafaelrabaco** [comment]
@galli-leo  The brazilian portuguese (pt-br) releases usually named it like e.g. 

> `Quatro Vidas de um Cachorro 2017 (1080p) DUBLADO `
> `Quatro.Vidas.De.Um.Cachorro.2017.720p.Bluray.Dublado`
> for: https://www.themoviedb.org/movie/381289-a-dog-s-purpose

> `Feito na América 2017 (1080p) DUBLADO`
> `Feito.na.América.2017.1080p.Bluray.Dublado`
> for: https://www.themoviedb.org/movie/337170-american-made

**Comment by ems21** [comment]
Dubbed releases in pt-br (Brazil) have titles translated
For pt-pt (Portugal) there are no releases with title translated

The titles of the films are very different

For example:
The Lego Movie 2: The Second Part (2019)
https://www.themoviedb.org/movie/280217-the-lego-movie-2

In pt-br:
Uma Aventura Lego 2 (2019)
https://www.themoviedb.org/movie/280217-the-lego-movie-2?language=pt-BR

In pt (for themoviedb pt = pt-pt):
O Filme LEGO 2 (2019)
https://www.themoviedb.org/movie/280217-the-lego-movie-2?language=pt
https://www.themoviedb.org/movie/280217-the-lego-movie-2?language=pt-pt


Probably just change the string "pt" to "pt-br" in the file isoLanguages.cs or create a new language (Portuguese Brazil).

Real examples releases:
Uma Aventura Lego 2 2019 (1080p) [DUAL] THEPIRATEFILMES.TV 
Uma Aventura Lego 2 2019 (720p) [DUBLADO] THEPIRATEFILMES.TV 
Uma.Aventura.Lego.2.2019.1080p.Bluray.Dublado.WWW.TPF.GRATIS 
[WWW.BLUDV.TV] Uma Aventura Lego 2 2019 (720p - X265) Acesse o ORIGINAL WWW.BLUDV.TV 
[ACESSE COMANDOTORRENTS.COM] Uma Aventura Lego 2 2019 [1080p] [BluRay] [DUAL] 
[ACESSE COMANDOTORRENTS.COM] Uma Aventura Lego 2 2019 [720p] [BluRay] [DUBLADO]

**Comment by geovanent** [comment]
Just include pt-br as a new language guys, Please.

**Comment by dyorgio** [comment]
I did some modifications on isoLanguages.cs (and other files), just do start to support pt-br. tks @ems21 to point the lang file.

**Comment by hygorfragas** [comment]
Please how do I modify in my radar then? I think the torrent in ptr but the system does not let me download. Speaks that my profile is in English! But it is not! I moved to Portuguese and used tags. Or a way to remove this if, else to authorize to feel it is not the native language

**Comment by alpe12** [comment]
Come on, just add it already... :(

**Comment by Qstick** [comment]
I have this added in #4480, but I need a lot more example release names for the tests and parser... Please provide releases titles if you guys want this in. Thanks!

**Comment by alpe12** [comment]
Rise of the Guardians = A Origem dos Guardiões
X-Men: Days of Future Past = X-Men: Dias de um Futuro Esquecido
Spider-Man: Homecoming = Homem-Aranha: De Volta ao Lar
Coco = Viva: A Vida é uma Festa
The Lion King = O Rei Leão
Big Hero 6 = Operação Big Hero 6
The Odd Life of Timothy Green = A Estranha Vida de Timothy Green
Arrival = A Chegada
Meet the Robinsons = A Família do Futuro
Interstellar = Interestelar
Rat Race = Tá Todo Mundo Louco!
Changeling = A Troca
The Nightmare Before Christmas = O Estranho Mundo de Jack
Edward Scissorhands = Edward Mãos de Tesoura
The Dark Knight = Batman: O Cavaleiro das Trevas
Zombieland = Zumbilândia
Charlie St. Cloud = A Morte e Vida de Charlie
Secondhand Lions = Lições para Toda Vida
Men in Black = MIB: Homens de Preto
Scrooged = Os Fantasmas Contra Atacam
Saving Mr. Banks = Walt nos Bastidores de Mary Poppins
Lord of War = O Senhor das Armas
The Golden Compass = A Bússola de Ouro
Inception = A Origem
The Hitchhiker's Guide to the Galaxy = O Guia do Mochileiro das Galáxias
Shaun of the Dead = Todo Mundo Quase Morto
Ferris Bueller's Day Off = Curtindo a Vida Adoidado
50 First Dates = Como se Fosse a Primeira Vez
School of Rock = Escola de Rock

**Comment by Qstick** [comment]
I'm not looking for translations, I'm looking for scene release name examples, examples of releases that are identified as brazilian so that we know how to identify them in the parser. 

Like `Quatro Vidas de um Cachorro 2017 (1080p) DUBLADO`

**Comment by alpe12** [comment]
Sorry.
These are the groups I most commonly come around.

- Homem-Aranha - De Volta ao Lar 2017 [BluRay] (1080p) DUBLADO
- 
- Homem.Aranha.De.Volta.ao.Lar.2017.720p.BluRay.6CH.x264.DUBLADO-WWW.BLUDV.COM.mp4
- Homem-Aranha - De Volta ao Lar 2017 [BluRay - x265] (720p) WWW.BLUDV.COM
- Pantera Negra 2018 (1080p) DUBLADO WWW.BLUDV.COM
- {WWW.BLUDV.COM} Vingadores - Guerra Infinita 2018 (1080p) [BluRay] Acesse o ORIGINAL WWW.BLUDV.COM 
- Jogador Nº 1 2018 (1080p) DUBLADO Acesse o ORIGINAL WWW.BLUDV.COM
- {WWW.BLUDV.COM} Vingadores - Guerra Infinita 2018 (720p) [BluRay] Acesse o ORIGINAL WWW.BLUDV.COM 
- [WWW.BLUDV.TV] Vingadores - Ultimato 2019 (1080p - BluRay) Acesse o ORIGINAL WWW.BLUDV.TV 
- 
- Homem.Aranha.De.Volta.ao.Lar.2017.1080p.Bluray.Dublado.WWW.TPF.GRATIS
- Liga.da.Justiça.2018.1080p.Bluray.Dublado.WWW.TPF.GRATIS 
- 
- Homem-Aranha - De Volta ao Lar (2017) [1080p] DUBLADO - LAPUMiAFiLMES.COM
- Vingadores – Guerra Infinita 2018 (720p) [NEW PROPER HDCAM] WWW.LAPUMiAFiLMES.COM 
- Duas Vidas (2000) [720p] [BluRay 5.1] DUBLADO - WWW.LAPUMiAFiLMES.COM 
- O Menino do Pijama Listrado 2008 5.1 (1080p) LAPUMiA 
- Um Lugar Silencioso 2018 (720p) [HC HDRip] WWW.LAPUMiAFiLMES.COM
- LAPUMiA.Org - Star Wars - A Ascensão Skywalker 2020 5.1 (720p-Mp4) 
- 
- Homem-Aranha De Volta ao Lar 2017 [BluRay] [1080p] [DUAL] COMANDOTORRENTS.COM 
- [COMANDOTORRENTS.COM] O Rei Leão 2019 [720p] [BluRay] [DUBLADO] 
- [COMANDOTORRENTS.ORG] Pressagio 2020 [720p] [DUAL] 
- [ACESSE COMANDOTORRENTS.COM] Vingadores - Ultimato 2019 [1080p] [BluRay] [DUAL] 
- [COMANDOTORRENTS.COM] Coringa 2019 [720p] [HDCAM] [DUBLADO OFICIAL]
- Vingadores - Guerra Infinita 2018 [BluRay] [1080p] [DUAL] BAIXE NO COMANDOTORRENTS.COM 
- 
- Aladdin Blu-Ray 2019 Dublado - WWW.DTORRENT.COM.BR 
- X-Men Evolution 2ª Temporada (2000 a 2003) HDTV 720p Dublado - WWW.DTORRENT.COM.BR 
- Toy Story 4 Dublado Blu-Ray 2019 - WWW.DTORRENT.COM.BR 
- A Era do Gelo O Big Bang (2016) Blu-Ray 720p Dublado - WWW.DTORRENT.COM.BR
- 
- COMANDO.TO - Emma. 2020 [720p] [DUBLADO] 
- COMANDO.TO - Juízo Final 2008 [1080p] [DUBLADO]

**Comment by alpe12** [comment]
Any progress? I'm on _nightly_ and still no pt-br option.

**Comment by dyorgio** [comment]
@alpe12 maybe you need to use aphrodite branch...
3 years... I gave up, its a shame 250 milions of brazilian people just be ignored or put in low priority, Raddar team really don't care to have more users...

**Comment by alpe12** [comment]
I was on aphrodite until yesterday when I saw a notice basically saying to change to nightly.

I think you should leave the issue open, so that they know it's still not solved.

**Comment by timartinelli** [comment]
As this request goes, friends, it is something great for us Brazilians.

**Comment by austinwbest** [comment]
> Sorry.
> These are the groups I most commonly come around.
> 
> * Homem-Aranha - De Volta ao Lar 2017 [BluRay] (1080p) DUBLADO
> * Homem.Aranha.De.Volta.ao.Lar.2017.720p.BluRay.6CH.x264.DUBLADO-WWW.BLUDV.COM.mp4
> * Homem-Aranha - De Volta ao Lar 2017 [BluRay - x265] (720p) WWW.BLUDV.COM
> * Pantera Negra 2018 (1080p) DUBLADO WWW.BLUDV.COM
> * {WWW.BLUDV.COM} Vingadores - Guerra Infinita 2018 (1080p) [BluRay] Acesse o ORIGINAL WWW.BLUDV.COM
> * Jogador Nº 1 2018 (1080p) DUBLADO Acesse o ORIGINAL WWW.BLUDV.COM
> * {WWW.BLUDV.COM} Vingadores - Guerra Infinita 2018 (720p) [BluRay] Acesse o ORIGINAL WWW.BLUDV.COM
> * [WWW.BLUDV.TV] Vingadores - Ultimato 2019 (1080p - BluRay) Acesse o ORIGINAL WWW.BLUDV.TV
> * Homem.Aranha.De.Volta.ao.Lar.2017.1080p.Bluray.Dublado.WWW.TPF.GRATIS
> * Liga.da.Justiça.2018.1080p.Bluray.Dublado.WWW.TPF.GRATIS
> * Homem-Aranha - De Volta ao Lar (2017) [1080p] DUBLADO - LAPUMiAFiLMES.COM
> * Vingadores – Guerra Infinita 2018 (720p) [NEW PROPER HDCAM] WWW.LAPUMiAFiLMES.COM
> * Duas Vidas (2000) [720p] [BluRay 5.1] DUBLADO - WWW.LAPUMiAFiLMES.COM
> * O Menino do Pijama Listrado 2008 5.1 (1080p) LAPUMiA
> * Um Lugar Silencioso 2018 (720p) [HC HDRip] WWW.LAPUMiAFiLMES.COM
> * LAPUMiA.Org - Star Wars - A Ascensão Skywalker 2020 5.1 (720p-Mp4)
> * Homem-Aranha De Volta ao Lar 2017 [BluRay] [1080p] [DUAL] COMANDOTORRENTS.COM
> * [COMANDOTORRENTS.COM] O Rei Leão 2019 [720p] [BluRay] [DUBLADO]
> * [COMANDOTORRENTS.ORG] Pressagio 2020 [720p] [DUAL]
> * [ACESSE COMANDOTORRENTS.COM] Vingadores - Ultimato 2019 [1080p] [BluRay] [DUAL]
> * [COMANDOTORRENTS.COM] Coringa 2019 [720p] [HDCAM] [DUBLADO OFICIAL]
> * Vingadores - Guerra Infinita 2018 [BluRay] [1080p] [DUAL] BAIXE NO COMANDOTORRENTS.COM
> * Aladdin Blu-Ray 2019 Dublado - WWW.DTORRENT.COM.BR
> * Toy Story 4 Dublado Blu-Ray 2019 - WWW.DTORRENT.COM.BR
> * A Era do Gelo O Big Bang (2016) Blu-Ray 720p Dublado - WWW.DTORRENT.COM.BR
> * COMANDO.TO - Emma. 2020 [720p] [DUBLADO]
> * COMANDO.TO - Juízo Final 2008 [1080p] [DUBLADO]

What a train-wreck of release names... I see a small handful that would parse the group properly lol

**Comment by timartinelli** [comment]
I don't quite understand how it works, when can we test this functionality?

**Comment by austinwbest** [comment]
The ticket is still open, you'll need to wait until it is merged which means it has been fully added and usable.

Q still has a couple things to do to get it in there fully

**Comment by timartinelli** [comment]
got it friend, thank you very much for the information.
