### ISSUE TITLE
Radarr starts but immediately crashes before loading the web interface.

### ISSUE THREAD

**Issue by erylflynn** [Radarr/Radarr#1628]
Currently I can start Radarr and if you status it quick you see it started, but immediately crashes and restarts.  Was working before I rebooted and have the box currently updated.  Of note I have a current version of Sonarr running on the same box and it works fine.  Logs do not seem very helpful.  Unsure where to go from here. Why it stopped, and what I can do to fix it.

Also having trouble adding things from systemctl, they are interpreted as code.  Below are the errors from systemctl status radarr

● radarr.service - Radarr Service
   Loaded: loaded (/usr/lib/systemd/system/radarr.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2017-06-05 17:52:43 PDT; 11min ago
  Process: 459 ExecStart=/usr/bin/mono --debug /usr/lib/radarr/Radarr.exe -nobrowser -data=/var/lib/radarr (code=exited, status=1/FAILURE)
 Main PID: 459 (code=exited, status=1/FAILURE)

Jun 05 17:52:42 Sonarr systemd[1]: Started Radarr Service.
Jun 05 17:52:43 Sonarr systemd[1]: radarr.service: Main process exited, code=exited, status=1/FAILURE
Jun 05 17:52:43 Sonarr systemd[1]: radarr.service: Unit entered failed state.
Jun 05 17:52:43 Sonarr systemd[1]: radarr.service: Failed with result 'exit-code'.
Jun 05 17:52:43 Sonarr systemd[1]: radarr.service: Service hold-off time over, scheduling restart.
Jun 05 17:52:43 Sonarr systemd[1]: Stopped Radarr Service.
Jun 05 17:52:43 Sonarr systemd[1]: radarr.service: Start request repeated too quickly.
Jun 05 17:52:43 Sonarr systemd[1]: Failed to start Radarr Service.
Jun 05 17:52:43 Sonarr systemd[1]: radarr.service: Unit entered failed state.
Jun 05 17:52:43 Sonarr systemd[1]: radarr.service: Failed with result 'exit-code'.

`17-6-5 12:57:41.4|Info|MigrationLogger|*** Migrating data source=/var/lib/radarr/logs.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
17-6-5 12:57:41.5|Info|Router|Application mode: Interactive
17-6-5 12:57:41.5|Info|OwinHostController|Listening on the following URLs:
17-6-5 12:57:41.5|Info|OwinHostController|  http://*:7878/
17-6-5 12:57:41.7|Info|NancyBootstrapper|Starting NzbDrone API
17-6-5 12:58:15.3|Info|RssSyncService|Starting RSS Sync
17-6-5 12:58:16.0|Info|Bootstrap|Starting Radarr - /usr/lib/radarr/Radarr.exe - Version 0.2.0.696
17-6-5 12:58:16.4|Info|AppFolderInfo|Data directory is being overridden to [/var/lib/radarr]
17-6-5 12:58:18.1|Info|MigrationLogger|*** Migrating data source=/var/lib/radarr/nzbdrone.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
17-6-5 12:58:18.2|Info|MigrationLogger|*** Migrating data source=/var/lib/radarr/logs.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
17-6-5 12:58:18.3|Info|Router|Application mode: Interactive
17-6-5 12:58:18.3|Info|OwinHostController|Listening on the following URLs:
17-6-5 12:58:18.3|Info|OwinHostController|  http://*:7878/
17-6-5 12:58:18.4|Info|NancyBootstrapper|Starting NzbDrone API
17-6-5 12:58:51.4|Info|RssSyncService|Starting RSS Sync
17-6-5 12:58:52.0|Info|Bootstrap|Starting Radarr - /usr/lib/radarr/Radarr.exe - Version 0.2.0.696
17-6-5 12:58:52.4|Info|AppFolderInfo|Data directory is being overridden to [/var/lib/radarr]
17-6-5 12:58:54.1|Info|MigrationLogger|*** Migrating data source=/var/lib/radarr/nzbdrone.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
17-6-5 12:58:54.2|Info|MigrationLogger|*** Migrating data source=/var/lib/radarr/logs.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
17-6-5 12:58:54.3|Info|Router|Application mode: Interactive
17-6-5 12:58:54.3|Info|OwinHostController|Listening on the following URLs:
17-6-5 12:58:54.3|Info|OwinHostController|  http://*:7878/
17-6-5 12:58:54.4|Info|NancyBootstrapper|Starting NzbDrone API
17-6-5 12:59:26.9|Info|RssSyncService|Starting RSS Sync
17-6-5 12:59:27.5|Info|Bootstrap|Starting Radarr - /usr/lib/radarr/Radarr.exe - Version 0.2.0.696
17-6-5 12:59:27.8|Info|AppFolderInfo|Data directory is being overridden to [/var/lib/radarr]
17-6-5 12:59:29.6|Info|MigrationLogger|*** Migrating data source=/var/lib/radarr/nzbdrone.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
17-6-5 12:59:29.7|Info|MigrationLogger|*** Migrating data source=/var/lib/radarr/logs.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
17-6-5 12:59:29.7|Info|Router|Application mode: Interactive
17-6-5 12:59:29.7|Info|OwinHostController|Listening on the following URLs:
17-6-5 12:59:29.7|Info|OwinHostController|  http://*:7878/
17-6-5 12:59:29.9|Info|NancyBootstrapper|Starting NzbDrone API
17-6-5 13:41:49.6|Info|Bootstrap|Starting Radarr - /usr/lib/radarr/Radarr.exe - Version 0.2.0.696
17-6-5 13:41:50.0|Info|AppFolderInfo|Data directory is being overridden to [/var/lib/radarr]
17-6-5 13:41:51.8|Info|MigrationLogger|*** Migrating data source=/var/lib/radarr/nzbdrone.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
17-6-5 13:41:51.9|Info|MigrationLogger|*** Migrating data source=/var/lib/radarr/logs.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
17-6-5 13:41:52.0|Info|Router|Application mode: Interactive
17-6-5 13:41:52.0|Info|OwinHostController|Listening on the following URLs:
17-6-5 13:41:52.0|Info|OwinHostController|  http://*:7878/
17-6-5 13:41:52.2|Info|NancyBootstrapper|Starting NzbDrone API
17-6-5 13:42:24.9|Info|RssSyncService|Starting RSS Sync
17-6-5 13:42:25.5|Info|Bootstrap|Starting Radarr - /usr/lib/radarr/Radarr.exe - Version 0.2.0.696
17-6-5 13:42:25.9|Info|AppFolderInfo|Data directory is being overridden to [/var/lib/radarr]
17-6-5 13:42:27.7|Info|MigrationLogger|*** Migrating data source=/var/lib/radarr/nzbdrone.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
17-6-5 13:42:27.8|Info|MigrationLogger|*** Migrating data source=/var/lib/radarr/logs.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
17-6-5 13:42:27.8|Info|Router|Application mode: Interactive
17-6-5 13:42:27.8|Info|OwinHostController|Listening on the following URLs:
17-6-5 13:42:27.8|Info|OwinHostController|  http://*:7878/
17-6-5 13:42:28.0|Info|NancyBootstrapper|Starting NzbDrone API
17-6-5 13:42:30.8|Info|NetImportSearchService|No lists are enabled for auto-import.
17-6-5 13:42:52.0|Info|Bootstrap|Starting Radarr - /usr/lib/radarr/Radarr.exe - Version 0.2.0.696
17-6-5 13:42:52.4|Info|AppFolderInfo|Data directory is being overridden to [/var/lib/radarr]
17-6-5 13:42:53.3|Info|Bootstrap|Starting Radarr - /usr/lib/radarr/Radarr.exe - Version 0.2.0.696
17-6-5 13:42:53.7|Info|AppFolderInfo|Data directory is being overridden to [/var/lib/radarr]
17-6-5 13:42:55.1|Info|MigrationLogger|*** Migrating data source=/var/lib/radarr/nzbdrone.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
17-6-5 13:42:55.2|Info|MigrationLogger|*** Migrating data source=/var/lib/radarr/logs.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
17-6-5 13:42:55.3|Info|Router|Application mode: Interactive
17-6-5 13:42:55.3|Info|OwinHostController|Listening on the following URLs:
17-6-5 13:42:55.3|Info|OwinHostController|  http://*:7878/
17-6-5 13:42:55.4|Info|NancyBootstrapper|Starting NzbDrone API
17-6-5 13:43:28.2|Info|RssSyncService|Starting RSS Sync
17-6-5 13:43:32.2|Info|DownloadDecisionMaker|Processing 100 releases
17-6-5 13:43:33.9|Info|RssSyncService|RSS Sync Completed. Reports found: 100, Reports grabbed: 0
[bpeckin@Sonarr logs]$ tail radarr.txt
17-6-5 13:42:53.7|Info|AppFolderInfo|Data directory is being overridden to [/var/lib/radarr]
17-6-5 13:42:55.1|Info|MigrationLogger|*** Migrating data source=/var/lib/radarr/nzbdrone.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
17-6-5 13:42:55.2|Info|MigrationLogger|*** Migrating data source=/var/lib/radarr/logs.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
17-6-5 13:42:55.3|Info|Router|Application mode: Interactive
17-6-5 13:42:55.3|Info|OwinHostController|Listening on the following URLs:
17-6-5 13:42:55.3|Info|OwinHostController|  http://*:7878/
17-6-5 13:42:55.4|Info|NancyBootstrapper|Starting NzbDrone API
17-6-5 13:43:28.2|Info|RssSyncService|Starting RSS Sync
17-6-5 13:43:32.2|Info|DownloadDecisionMaker|Processing 100 releases
17-6-5 13:43:33.9|Info|RssSyncService|RSS Sync Completed. Reports found: 100, Reports grabbed: 0
`

Radarr Version 0.2.0.696
Mono Version 5.0.0 
Arch Linux 64bit

**Comment by galli-leo** [comment]
Can you try doing as suggested over here?: https://github.com/Radarr/Radarr/issues/1528

**Comment by erylflynn** [comment]
Thanks, tried that and still not starting.  Sonarr is still working. Mono version is 4.8. Below is a snip from journalctl after downgrading and rebooting filtered for radarr.  I am not seeing anything that helps me understand what is failing.

Jun 06 06:40:58 Sonarr sudo[7721]:  bpeckin : TTY=pts/0 ; PWD=/var/cache/pacman/pkg ; USER=root ; COMMAND=/usr/bin/systemctl start radarr
Jun 06 06:40:59 Sonarr systemd[1]: radarr.service: Main process exited, code=exited, status=1/FAILURE
Jun 06 06:40:59 Sonarr systemd[1]: radarr.service: Unit entered failed state.
Jun 06 06:40:59 Sonarr systemd[1]: radarr.service: Failed with result 'exit-code'.
Jun 06 06:41:00 Sonarr systemd[1]: radarr.service: Service hold-off time over, scheduling restart.
Jun 06 06:41:00 Sonarr systemd[1]: radarr.service: Main process exited, code=exited, status=1/FAILURE
Jun 06 06:41:00 Sonarr systemd[1]: radarr.service: Unit entered failed state.
Jun 06 06:41:00 Sonarr systemd[1]: radarr.service: Failed with result 'exit-code'.
Jun 06 06:41:01 Sonarr systemd[1]: radarr.service: Service hold-off time over, scheduling restart.
Jun 06 06:41:02 Sonarr systemd[1]: radarr.service: Main process exited, code=exited, status=1/FAILURE
Jun 06 06:41:02 Sonarr systemd[1]: radarr.service: Unit entered failed state.
Jun 06 06:41:02 Sonarr systemd[1]: radarr.service: Failed with result 'exit-code'.
Jun 06 06:41:02 Sonarr systemd[1]: radarr.service: Service hold-off time over, scheduling restart.
Jun 06 06:41:03 Sonarr systemd[1]: radarr.service: Main process exited, code=exited, status=1/FAILURE
Jun 06 06:41:03 Sonarr systemd[1]: radarr.service: Unit entered failed state.
Jun 06 06:41:03 Sonarr systemd[1]: radarr.service: Failed with result 'exit-code'.
Jun 06 06:41:03 Sonarr systemd[1]: radarr.service: Service hold-off time over, scheduling restart.
Jun 06 06:41:04 Sonarr systemd[1]: radarr.service: Main process exited, code=exited, status=1/FAILURE
Jun 06 06:41:04 Sonarr systemd[1]: radarr.service: Unit entered failed state.
Jun 06 06:41:04 Sonarr systemd[1]: radarr.service: Failed with result 'exit-code'.
Jun 06 06:41:04 Sonarr systemd[1]: radarr.service: Service hold-off time over, scheduling restart.
Jun 06 06:41:04 Sonarr systemd[1]: radarr.service: Start request repeated too quickly.
Jun 06 06:41:04 Sonarr systemd[1]: radarr.service: Unit entered failed state.
Jun 06 06:41:04 Sonarr systemd[1]: radarr.service: Failed with result 'exit-code'.
Jun 06 06:41:13 Sonarr sudo[7813]:  bpeckin : TTY=pts/0 ; PWD=/var/cache/pacman/pkg ; USER=root ; COMMAND=/usr/bin/systemctl status radarr
Jun 06 06:42:10 Sonarr systemd[1]: radarr.service: Main process exited, code=exited, status=1/FAILURE
Jun 06 06:42:10 Sonarr systemd[1]: radarr.service: Unit entered failed state.
Jun 06 06:42:10 Sonarr systemd[1]: radarr.service: Failed with result 'exit-code'.
Jun 06 06:42:11 Sonarr systemd[1]: radarr.service: Service hold-off time over, scheduling restart.
Jun 06 06:42:11 Sonarr systemd[1]: radarr.service: Main process exited, code=exited, status=1/FAILURE
Jun 06 06:42:11 Sonarr systemd[1]: radarr.service: Unit entered failed state.
Jun 06 06:42:11 Sonarr systemd[1]: radarr.service: Failed with result 'exit-code'.
Jun 06 06:42:12 Sonarr systemd[1]: radarr.service: Service hold-off time over, scheduling restart.
Jun 06 06:42:12 Sonarr systemd[1]: radarr.service: Main process exited, code=exited, status=1/FAILURE
Jun 06 06:42:12 Sonarr systemd[1]: radarr.service: Unit entered failed state.
Jun 06 06:42:12 Sonarr systemd[1]: radarr.service: Failed with result 'exit-code'.
Jun 06 06:42:13 Sonarr systemd[1]: radarr.service: Service hold-off time over, scheduling restart.
Jun 06 06:42:14 Sonarr systemd[1]: radarr.service: Main process exited, code=exited, status=1/FAILURE
Jun 06 06:42:14 Sonarr systemd[1]: radarr.service: Unit entered failed state.
Jun 06 06:42:14 Sonarr systemd[1]: radarr.service: Failed with result 'exit-code'.
Jun 06 06:42:14 Sonarr systemd[1]: radarr.service: Service hold-off time over, scheduling restart.
Jun 06 06:42:15 Sonarr systemd[1]: radarr.service: Main process exited, code=exited, status=1/FAILURE
Jun 06 06:42:15 Sonarr systemd[1]: radarr.service: Unit entered failed state.
Jun 06 06:42:15 Sonarr systemd[1]: radarr.service: Failed with result 'exit-code'.
Jun 06 06:42:15 Sonarr systemd[1]: radarr.service: Service hold-off time over, scheduling restart.
Jun 06 06:42:15 Sonarr systemd[1]: radarr.service: Start request repeated too quickly.
Jun 06 06:42:15 Sonarr systemd[1]: radarr.service: Unit entered failed state.
Jun 06 06:42:15 Sonarr systemd[1]: radarr.service: Failed with result 'exit-code'.
Jun 06 06:43:19 Sonarr sudo[769]:  bpeckin : TTY=pts/0 ; PWD=/home/bpeckin ; USER=root ; COMMAND=/usr/bin/systemctl status radarr

**Comment by galli-leo** [comment]
Does Radarr have write access to /var/lib/radarr?

**Comment by erylflynn** [comment]
That was the last piece.  I believe I needed to downgrade mono, but I allowed an update from the AUR to see if that helped, and I thought I fixed all the permissions but missed that one.  

Chalk this up to mono version.  I blocked mono in pacman.conf from updating like I do for both Radarr and Sonarr.  Thanks.
