### ISSUE TITLE
Large number of titles has performance issues on page loads for search bar filter

### ISSUE THREAD

**Issue by shushry** [Radarr/Radarr#1629]
Running on Radarr v0.2.0.724 Nightly

With a particularly large collection (7k+ titles) the javascript/ajax loader that populates the movie search bar at the top of every page in Radarr can take a long time to load, and delay the loading of other UI elements like the "select path" box when trying to add a new title.

It's a nice feature to have except as I said, a large number of elements will really drag down the loading of a page.   

As a feature request I'd like to add a toggle to have this javascript/ajax loading of titles OR a traditional hit-search-and-get-results style option.   Otherwise, it's alot of work to run on every page load.  

Unless - any hints to improving this on my own installation?

**Comment by galli-leo** [comment]
The search bar does not do an ajax call to the server to get the movies matching. So not sure what we could improve here. It just waits for all your movies being loaded into the radarr ui (which we have to do for a few things anyways) so not sure if we can disable that.

**Comment by shushry** [comment]
I've learned to work around this by making sure i'm working in the same browser/tab, loaded once, then navigate around.  Avoiding page refreshing or opening new tabs helps.   Once loaded, it's great, but she's definitely a resource consumer with 7,000+ titles :)
