### ISSUE TITLE
 Discover New Movies Recommendations stopped working.

### ISSUE THREAD

**Issue by jaycedk** [Radarr/Radarr#1630]
**Description:**
This issue started yesterday, and har been working great. 
When trying to add movie, from "Discover New Movies" Recommendations.
I only see the dots dancing back and forth.
Currently Popular Movies and Upcoming is working.

Have tried Restart of radarr, reboot server. different browser. Clear browser cache.

**Radarr Version:**
Radarr Ver. 0.2.0.696

**Logs:**
Error occured while searching for new movies.: String was not recognized as a valid DateTime.

System.FormatException: String was not recognized as a valid DateTime.
   at System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.MapMovie(MovieResult result) in C:\projects\radarr-usby1\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 566

**Comment by galli-leo** [comment]
Could you enable debug logging? (and post a more detailed log)

**Comment by jaycedk** [comment]
Will do. Will be back home tomorrow, then i will send the log. 


Sendt med Boxer

**Comment by jaycedk** [comment]
Hi here is the debug log.

17-6-6 21:22:34.8|Debug|Api|[GET] /api/log/file: 200.OK (1 ms)
17-6-6 21:22:34.8|Debug|Api|[GET] /api/log/file: 200.OK (2 ms)
17-6-6 21:22:34.8|Debug|Api|[GET] /api/log/file: 200.OK (1 ms)
17-6-6 21:22:34.9|Debug|Api|[GET] /api/log/file/radarr.debug.txt: 200.OK (1 ms)
17-6-6 21:22:34.9|Debug|Api|[GET] /api/log/file/radarr.debug.txt: 200.OK (1 ms)
17-6-6 21:22:42.3|Debug|RootFolderService|Generating list of unmapped folders
17-6-6 21:22:42.3|Debug|Api|[GET] /api/profile: 200.OK (5 ms)
17-6-6 21:22:42.6|Debug|RootFolderService|1 unmapped folders detected.
17-6-6 21:22:42.7|Debug|RootFolderService|Generating list of unmapped folders
17-6-6 21:22:42.8|Debug|RootFolderService|2 unmapped folders detected.
17-6-6 21:22:42.9|Debug|SabnzbdProxy|Url: http://192.168.1.30:9090/api?mode=queue&start=0&limit=0&apikey=(removed)&output=json
17-6-6 21:22:42.9|Debug|SabnzbdProxy|Url: http://192.168.1.30:9090/api?mode=history&start=0&limit=30&category=radarr&apikey=(removed)&output=json
17-6-6 21:22:42.9|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (30 ms)
17-6-6 21:22:43.1|Debug|RootFolderService|Generating list of unmapped folders
17-6-6 21:22:43.3|Debug|RootFolderService|0 unmapped folders detected.
17-6-6 21:22:43.3|Debug|RootFolderService|Generating list of unmapped folders
17-6-6 21:22:43.6|Debug|RootFolderService|1 unmapped folders detected.
17-6-6 21:22:43.6|Debug|RootFolderService|Generating list of unmapped folders
17-6-6 21:22:43.9|Debug|RootFolderService|0 unmapped folders detected.
17-6-6 21:22:43.9|Debug|RootFolderService|Generating list of unmapped folders
17-6-6 21:22:44.1|Debug|RootFolderService|0 unmapped folders detected.
17-6-6 21:22:44.1|Debug|RootFolderService|Generating list of unmapped folders
17-6-6 21:22:44.2|Error|SkyHookProxy|Error occured while searching for new movies.

[v0.2.0.696] System.FormatException: String was not recognized as a valid DateTime.
   at System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.MapMovie(MovieResult result) in C:\projects\radarr-usby1\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 566

17-6-6 21:22:44.2|Debug|Api|[GET] /api/movies/discover/recommendations: 200.OK (974 ms)
17-6-6 21:22:44.4|Debug|RootFolderService|0 unmapped folders detected.
17-6-6 21:22:44.4|Debug|RootFolderService|Generating list of unmapped folders
17-6-6 21:22:44.6|Debug|RootFolderService|0 unmapped folders detected.
17-6-6 21:22:44.6|Debug|RootFolderService|Generating list of unmapped folders
17-6-6 21:22:44.9|Debug|RootFolderService|1 unmapped folders detected.
17-6-6 21:22:44.9|Debug|RootFolderService|Generating list of unmapped folders
17-6-6 21:22:45.1|Debug|RootFolderService|4 unmapped folders detected.
17-6-6 21:22:45.1|Debug|RootFolderService|Generating list of unmapped folders
17-6-6 21:22:45.4|Debug|RootFolderService|1 unmapped folders detected.
17-6-6 21:22:45.4|Debug|RootFolderService|Generating list of unmapped folders
17-6-6 21:22:45.6|Debug|RootFolderService|1 unmapped folders detected.
17-6-6 21:22:45.7|Debug|RootFolderService|Generating list of unmapped folders
17-6-6 21:22:45.9|Debug|RootFolderService|0 unmapped folders detected.
17-6-6 21:22:45.9|Debug|RootFolderService|Generating list of unmapped folders
17-6-6 21:22:46.1|Debug|RootFolderService|0 unmapped folders detected.
17-6-6 21:22:46.1|Debug|RootFolderService|Generating list of unmapped folders
17-6-6 21:22:46.4|Debug|RootFolderService|0 unmapped folders detected.
17-6-6 21:22:46.4|Debug|RootFolderService|Generating list of unmapped folders
17-6-6 21:22:46.6|Debug|RootFolderService|2 unmapped folders detected.
17-6-6 21:22:46.6|Debug|RootFolderService|Generating list of unmapped folders
17-6-6 21:22:46.9|Debug|RootFolderService|0 unmapped folders detected.
17-6-6 21:22:46.9|Debug|RootFolderService|Generating list of unmapped folders
17-6-6 21:22:47.1|Debug|RootFolderService|0 unmapped folders detected.
17-6-6 21:22:47.1|Debug|RootFolderService|Generating list of unmapped folders
17-6-6 21:22:47.4|Debug|RootFolderService|1 unmapped folders detected.
17-6-6 21:22:47.4|Debug|RootFolderService|Generating list of unmapped folders
17-6-6 21:22:47.6|Debug|RootFolderService|0 unmapped folders detected.
17-6-6 21:22:47.6|Debug|RootFolderService|Generating list of unmapped folders
17-6-6 21:22:47.8|Debug|RootFolderService|0 unmapped folders detected.
17-6-6 21:22:47.9|Debug|RootFolderService|Generating list of unmapped folders
17-6-6 21:22:48.1|Debug|RootFolderService|2 unmapped folders detected.
17-6-6 21:22:48.1|Debug|RootFolderService|Generating list of unmapped folders
17-6-6 21:22:48.6|Debug|RootFolderService|4 unmapped folders detected.
17-6-6 21:22:48.6|Debug|RootFolderService|Generating list of unmapped folders
17-6-6 21:22:48.8|Debug|RootFolderService|0 unmapped folders detected.
17-6-6 21:22:48.8|Debug|RootFolderService|Generating list of unmapped folders
17-6-6 21:22:49.0|Debug|RootFolderService|0 unmapped folders detected.
17-6-6 21:22:49.1|Debug|RootFolderService|Generating list of unmapped folders
17-6-6 21:22:49.3|Debug|RootFolderService|1 unmapped folders detected.
17-6-6 21:22:49.3|Debug|RootFolderService|Generating list of unmapped folders
17-6-6 21:22:49.5|Debug|RootFolderService|0 unmapped folders detected.
17-6-6 21:22:49.5|Debug|RootFolderService|Generating list of unmapped folders
17-6-6 21:22:49.7|Debug|RootFolderService|0 unmapped folders detected.
17-6-6 21:22:49.8|Debug|RootFolderService|Generating list of unmapped folders
17-6-6 21:22:50.0|Debug|RootFolderService|1 unmapped folders detected.
17-6-6 21:22:50.0|Debug|Api|[GET] /api/rootfolder: 200.OK (7705 ms)
17-6-6 21:22:56.4|Debug|Api|[GET] /api/health: 200.OK (1 ms)
17-6-6 21:22:56.4|Debug|Api|[GET] /api/diskspace: 200.OK (3 ms)
17-6-6 21:22:56.5|Debug|Api|[GET] /api/health: 200.OK (1 ms)
17-6-6 21:22:56.5|Debug|Api|[GET] /api/diskspace: 200.OK (3 ms)
17-6-6 21:22:58.0|Debug|Api|[GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc&filterType=equal: 200.OK (83 ms)
17-6-6 21:22:58.0|Debug|Api|[GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc&filterType=equal: 200.OK (6 ms)
17-6-6 21:23:00.3|Debug|Api|[GET] /api/log/file: 200.OK (1 ms)
17-6-6 21:23:00.3|Debug|Api|[GET] /api/log/file/radarr.debug.txt: 200.OK (1 ms)
17-6-6 21:23:03.0|Debug|Api|[GET] /api/log/file/radarr.debug.txt: 200.OK (1 ms)
17-6-6 21:23:12.9|Debug|SabnzbdProxy|Url: http://192.168.1.30:9090/api?mode=queue&start=0&limit=0&apikey=(removed)&output=json
17-6-6 21:23:12.9|Debug|SabnzbdProxy|Url: http://192.168.1.30:9090/api?mode=history&start=0&limit=30&category=radarr&apikey=(removed)&output=json
17-6-6 21:23:18.1|Debug|Api|[GET] /api/log/file/radarr.debug.txt: 200.OK (2 ms)
17-6-6 21:23:18.1|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (5 ms)
17-6-6 21:23:31.4|Debug|Api|[GET] /api/log/file/radarr.debug.txt: 200.OK (1 ms)

**Comment by galli-leo** [comment]
Can you try out the latest nightly? Should be fixed there.

**Comment by jaycedk** [comment]
Hi again.
Changed to Nightly, but can test it.
Same issue as https://github.com/Radarr/Radarr/issues/1639

**Comment by jaycedk** [comment]
Ok rolled back to Radarr Ver. 0.2.0.740
And the issue is fixed :) Thank you.

**Comment by mattispantone81** [comment]
I'm having same issue. Will try rollback
