### ISSUE TITLE
movie with "Ultimate" in title not recognized when searching

### ISSUE THREAD

**Issue by RealTabman** [Radarr/Radarr#1632]
**Description:**
When searching for the movie **The Ultimate Warrior (1975)** every found movie is marked as _"Unknown movie. Movie found does not match wanted movie."_ and the edition is always _"Ultimate"_.    

See this [Screenshot](http://i.imgur.com/ovGWkHh.jpg) of search results.

Radarr Version 0.2.0.696

**Comment by galli-leo** [comment]
Linked to #1676

**Comment by RealTabman** [comment]
Nice.
Much appreciated :)
