### ISSUE TITLE
Movie Names with numbers in name can cause 'Manual Search' download issues

### ISSUE THREAD

**Issue by peterf1972** [Radarr/Radarr#1634]
**Description:**

The Movie 'Gone In Sixty Seconds' lists the correct movies:
- Gone In Sixty Seconds
- Gone In 60 Seconds

The 'Add to download queue' button does not show for the movies named 'Gone In 60 Seconds' though.

![screen shot 06-06-17 at 09 41 18 am](https://cloud.githubusercontent.com/assets/26253/26832134/7ac23a72-4a9c-11e7-9a4a-7c642c6962d6.PNG)

The button should also be available for those movies, in fact it should be available for all results listed under Manuel search.

**Radarr Version:**
Radarr Ver. 0.2.0.696

**Logs:**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by galli-leo** [comment]
The problem is, that the name is "Gone in Sixty Seconds" in TMDB. If you add the second variant to TMDB yourself (and wait a few hours) Radarr should correctly recognize it. Working on a system for allowing you to download it anyways though.
