### ISSUE TITLE
No releases found (Jackett) 

### ISSUE THREAD

**Issue by gurabli** [Radarr/Radarr#1636]
Latest Radarr and Jackett, movie search doesn't return any hits. I'm using a private tracker, but tries Rarbg too. It worked few weeks ago. In Jackett I can search for a movie and all the results are there, but from Radarr nothing. The logs show 0 results found. Sonarr works perfectly fine. 

Any ideas?

**Comment by onedr0p** [comment]
Are you on the latest Jackett release? I have no problem with jackett and radarr finding releases.

**Comment by gurabli** [comment]
Yes, Jackett Version 0.7.1477.0
Don't know why. Maybe a specific tracker I use? Which one to try that works for sure (public)?

**Comment by onedr0p** [comment]
I don't use any public trackers with jackett but I can try, rarbg gives you problems?

**Comment by gurabli** [comment]
I tries rarbg just to test, I use only one private tracker (nCore). 
For example, I try Prometheus and no results for 1080p. But none of the movies work, no results at all. Searching in Jackett returns many releases.

**Comment by onedr0p** [comment]
I just added RarBG and I see a lot of results. You see nothing for this movie?

![image](https://user-images.githubusercontent.com/213795/26848961-52911198-4ad0-11e7-9b35-2c3052097172.png)

**Comment by onedr0p** [comment]
Also, I use torznab not potato.

**Comment by gurabli** [comment]
Nothing. Wonder what can it be.

**Comment by gurabli** [comment]
Torznab did the trick, as it is so often, a user error, I should have used torznab. Thank you for your help!
