### ISSUE TITLE
Case sensitive XML parsing leads to Newz-Complex indexer error

### ISSUE THREAD

**Issue by AnthraxLeprosyPi** [Radarr/Radarr#1638]
Hello everybody,

I'm using Newz-Complex - a german indexer - and currently experiencing the  following problem: 

17-6-6 21:06:45.8|Debug|Api|[POST] /api/indexer/test: 200.OK (1059 ms)
17-6-6 21:06:58.1|Debug|NewznabCapabilitiesProvider|Failed to parse newznab api capabilities for https://newz-complex.org/www/rss?t=0&dl=1&i=7460&r=XXXXXXXXXXXXXXXXXXXX.

[v0.2.0.696] System.Xml.XmlException: 'doctype' is an unexpected token. The expected token is 'DOCTYPE'. Line 1, position 3.
 

As far as I understand this the xml is 'malformed' (lowercase doctype) and therefore everything breaks :(

Any chance for an easy fix?

regards
Anthrax

**Comment by galli-leo** [comment]
Tell your indexer to fix their xml? I mean as you correctly stated, the xml is malformed, so not sure how much we can do about that.

**Comment by AnthraxLeprosyPi** [comment]
Hey galli-leo,

already did (in fact I did this first ;-))...
I just hoped for a hidden switch to tell the parser not to be that strict...

nevermind.

Anthrax

**Comment by galli-leo** [comment]
No, IIRC we use the parser provided by microsoft, so no options there.

**Comment by AnthraxLeprosyPi** [comment]
Well thanx again for your time. It was fixed overnighton behalf of the indexer guys.


cheers
Anthrax

PS: I used to parse very ugly XML in my first job years ago - and let me tell you there are a lot of switches to sanitize streams like that deep down in the .Net libs. But this is a dark place to poke around in ;-)

So I'm all for fixing the root problem not fix around it.
