### ISSUE TITLE
Movie names formatting

### ISSUE THREAD

**Issue by woble** [Radarr/Radarr#164]
Not really sure if Sonarr was already doing it by default behind the scene.

1. Implement something similar as below. Although I imagine since the data is already fetched from reliable sources, the naming would be correct.
![image](https://cloud.githubusercontent.com/assets/494873/21861129/e170401a-d833-11e6-8e29-4ba0bb244f47.png)

2. Toggle for `The Movie` vs `Movie, The`. This, besides Movie Naming settings, I imagine would also have to be reflected in the Movies list.

**Comment by woble** [comment]
Perhaps merge this and #193 into one feature request issue regarding Movie Naming.

**Comment by onedr0p** [comment]
I fixed sorting movies in https://github.com/Radarr/Radarr/commit/f198ca2b775a9f1165ff1002612434ffd9c4427b

**Comment by woble** [comment]
Related to nr 2 as far as sorting goes. However that being part of the naming settings would be a new feature still.

**Comment by woble** [comment]
Nr. 2 has been implemented.

**Comment by Shwaffle** [comment]
It seems you'd like this one to be the issue for movie naming suggestions.

With the 'Quality' dropdown, there are a number of options, but none of them are just a simple {quality} to make (1080p). The closest option right now is {Quality-Full} which seems to indicate that it will do something along the lines of (1080p-Proper).

**Comment by onedr0p** [comment]
Closing, seems to be working fine as is. Upper and lower should be handled based on the movie name.
