### ISSUE TITLE
Renaming a movie folder creates a new folder instead.

### ISSUE THREAD

**Issue by firedomain** [Radarr/Radarr#1641]
While testing Radarr thoroughly before importing all my movies I realized that using the rename feature was making a new folder & moving the movie there instead of renaming the current folder.
That leaves all my metadata (nfo, poster, clearart, fanart, etc...) in the old folder.

Windows 10
Radarr Ver. 0.2.0.696

**Comment by galli-leo** [comment]
Yes, this is a known issue, since we do not currently handle metadata. There should be an issue on here about that though, so closing as duplicate.

**Comment by firedomain** [comment]
ok, cool. sorry, i searched but didnt find it.

**Comment by galli-leo** [comment]
Well there isn't one issue specifically for this problem, but metadata in general (which will solve this :).)

**Comment by firedomain** [comment]
Ah ok, I did try testing this with no other files in the folder (only .mkv file) & a new folder was still created with the old one left behind.
But fingers crossed this will be sorted in time. This issue & the metadata being renamed are the only 2 things stopping me from switching.
