### ISSUE TITLE
Renaming Metadata NFO

### ISSUE THREAD

**Issue by firedomain** [Radarr/Radarr#1642]
When renaming a movie the nfo file name does not change.
This causes Emby to detect the renamed file as a new movie, it then tries to identify it & in this case it is incorrectly identified.
I presume this would be a bigger issue if it happened during a quality upgrade when i dont notice it happening.

nfo example:
somefile (2017) 1080p Bluray.mkv
somefile (2017) 1080p Bluray.nfo

I'm sorry if this is a duplicate again (im sure it is somewhere, but i couldn't find an open issue), if it is can you please redirect me to the thread.

Thanks for the amazing work, this is really coming together. just a few more minor issues to resolve & i'll be ready to switch.

**Comment by galli-leo** [comment]
Yeah, again duplicate :): #167 or #121

**Comment by firedomain** [comment]
how the hell did i miss that?!
sorry for wasting your time! & thanks!
