### ISSUE TITLE
With latest nightly update Radarr don't work.

### ISSUE THREAD

**Issue by rickytin** [Radarr/Radarr#1643]
With last  nightly update Radarr start but it stay with the ball bouncing side by side.
So I download Radarr Ver. 0.2.0.696 nightly and it works again.

**Comment by galli-leo** [comment]
Fixed on the latest nightly

**Comment by oliroe** [comment]
Any idea how I can update to the latest nightly if I now can't get to the front end? I don't really want to reinstall a backup if I don't have to

Thanks

**Comment by rickytin** [comment]
I don't know if this help Oliroe but when I have the problem I download Radarr Ver. 0.2.0.696 and install it and then it work, all my movies where there and then Radarr did update to the latest nightly version and for me it's working.

**Comment by oliroe** [comment]
Thanks for the replies, it's the restoring of my backup that I'm worried about
[http://ewoutreinders.com/index.php/sharing-the-appstore-folder-synology-nas/](url)
This link may help others, should give direct access to the backup folder and allow a backup to be restored easily
