### ISSUE TITLE
macOS app not starting

### ISSUE THREAD

**Issue by viki53** [Radarr/Radarr#1646]
**Description:**

The app won't start on my Mac, even though I tried different methods (app drawer and `open` command). 

At first I didn't get any more information, just that no process started and the Web server didn't respond.

I then tried the #745 fix and now I get the following error:

> LSOpenURLsWithRole() failed with error -10810 for the file /Applications/Radarr.app.

**Radarr Version:** v0.2.0.696

**Logs:** Don't know if there are any nor where to find them

**Comment by galli-leo** [comment]
So you tried the chmod +x command? Can you try directly calling the binary via `/Applications/Radarr.app/Contents/MacOS/Radarr`?

**Comment by viki53** [comment]
Here is where it goes sideways:

```
[Info] add_import_exclusions_table: Starting migration to 137 
[Error] MigrationLogger: database disk image is malformed
database disk image is malformed
While Processing:
"CREATE TABLE "ImportExclusions" ("Id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "TmdbId" INTEGER NOT NULL, "MovieTitle" TEXT, "MovieYear" INTEGER)" 

[v0.2.0.696] System.Exception: database disk image is malformed
database disk image is malformed
```

I guess the update went wrong somehow…

**Comment by galli-leo** [comment]
Might just be macOS shenanigans: https://github.com/Sonarr/Sonarr/wiki/FAQ#i-use-sonarr-on-a-mac-and-it-suddenly-stopped-working-what-happened

Can you try that and see if it fixes it?

**Comment by viki53** [comment]
Nope, same error.

I tried with the last two backups after deleting the logs. Nothing changes.

**Comment by galli-leo** [comment]
@viki53 Can you try moving all the db files out of the config directory (The one for Radarr not NzbDrone) and then rerunning Radarr?

**Comment by viki53** [comment]
Removed:

* logs.db
* logs.do-journal
* nzbdrone.db
* nzbdrone.db-journal

Still the same error…

**Comment by galli-leo** [comment]
Are you sure, you are removing the files in ~/.config/Radarr? Because it should regenerate the databases if they are not there.

**Comment by viki53** [comment]
Yes, I moved them to the Trash, then started Radarr (first the app, then directly the binary).

**Comment by galli-leo** [comment]
Can you get the full logs located in the same directory and post them?

**Comment by viki53** [comment]
Oops, my bad!

I was in `~/.config/NzbDrone` as per [the doc you cited](https://github.com/Sonarr/Sonarr/wiki/FAQ#i-use-sonarr-on-a-mac-and-it-suddenly-stopped-working-what-happened). Removing the `nzbdrone.log` file in `~/.config/Radarr` did the trick.

The [Radarr FAQ](https://github.com/Radarr/Radarr/wiki/FAQ) should probably be updated. 😉 

Issue can be closed.

**Comment by galli-leo** [comment]
@viki53 Seems like a migration did not complete correctly. Can you try restoring from a backup? Radarr should have done one right before upgrading.
And yeah, we should prolly update the FAQ.

**Comment by viki53** [comment]
As I deleted the files, I did put a backup instead. But now they're gone, they've been replaced by a single new zip…

**Comment by viki53** [comment]
Okay, I tried with a different backup and it finally worked. Don't really know what went wrong this time either…

Thanks!

**Comment by galli-leo** [comment]
Good to hear. Might be that the db got corrupted while Radarr was running migrations? Anyways, gonna close the issue for now and we can open it again, if it pops back up.
