### ISSUE TITLE
Movie is not snatched at all even though there are releases out

### ISSUE THREAD

**Issue by Rockapella** [Radarr/Radarr#1647]
After adding a movie to Radarr, I performed a manual search and saw that a bunch of releases for this specific movie came out less than 48 hours ago. I tried to do the automatic search using the magnifying glass and it won't snatch any of the newly released versions. There is no red exclamation mark next to the releases to indicate that there is anything wrong and the quality profile fits what I have set in Radarr, however it still does not snatch it. Other (older) movies that I add are snatched fine. FYI the movie is "Life (2017)".

Radarr Version: 0.2.0.696

Logs: Nothing in logs related to issue

**Comment by gregcbrown** [comment]
I had the same issue with a movie called "The Shack"...

**Comment by rustyshackleford36** [comment]
I have also had this issue. The release had been out for about two weeks, and met my file size criteria. I had to manually search and select a file.

**Comment by galli-leo** [comment]
@rustyshackleford36 @gregcbrown You probably have set the minimum availability for the movie to "PreDB". See this wiki page for more information and our recommended settings: https://github.com/Radarr/Radarr/wiki/Minimum-Availability

**Comment by Rockapella** [comment]
Ok, so changing the minimum availability seems to have worked. I can't figure out how to change the minimum availability for all future movies. It seems every time a new movie is requested, it automatically selects preDB.

**Comment by galli-leo** [comment]
@Rockapella Yeah, we should prolly set a new default.

**Comment by gregcbrown** [comment]
That is quite likely. I do a mass edit occasionally because I forget to change to Physical Web instead of PreDB.
