### ISSUE TITLE
Display loading indicator when loading movies for movie editor. (Also maybe a message that it can take a long time)

### ISSUE THREAD

**Issue by majora2007** [Radarr/Radarr#1650]
Upon trying to navigate to the movie editor ( /movieeditor) a blank screen shows up. Nothing ever loads. 

Check first that your problem is not listed in our wiki section:
* https://github.com/Radarr/Radarr/wiki/Common-Problems
* https://github.com/Radarr/Radarr/wiki/FAQ

Provide a description of the feature request or bug here, the more details the better. 
Please also try to include the following if you are reporting a bug

**Radarr Version:** 0.2.0.696 

**Logs:** 
[radarr.txt](https://github.com/Radarr/Radarr/files/1065844/radarr.txt)

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by galli-leo** [comment]
Can you try opening the chrome dev console and seeing if any errors are there? (Might be a timeout issue)

**Comment by majora2007** [comment]
No errrors on the console :(

**Comment by galli-leo** [comment]
@majora2007 Can you checkout the network tab in the chrome dev console and see if anything timesout? Also can you try a different browser?

**Comment by majora2007** [comment]
You're right. If you wait some time, it finally loads. The polls are taking about 30 secs after the fact and initial API call resolves in 30 secs. I have just over 2000 movies. 

So maybe this should be a feature enhancement to speed up response time or show some loading indicator?

**Comment by galli-leo** [comment]
Yeah, btw what page size have you set? (Since it should use paging)

**Comment by majora2007** [comment]
Page size is 10,000 lol

**Comment by galli-leo** [comment]
@majora2007 Ah yeah, now it makes sense why it takes so long to load.

**Comment by majora2007** [comment]
How can I change the pagination?

**Comment by galli-leo** [comment]
Settings -> UI -> Page Size
