### ISSUE TITLE
Dont find some movies, but the movies still there on the indexers

### ISSUE THREAD

**Issue by D3ltorohd** [Radarr/Radarr#1657]
Hello guys,

i have some problems with radarr.
i hope someone can help me
i use radarr for some weeks. but it works not 100 % perfect
some movies he found some not
but for the most he didn't found are there at my indexer
radarr found nothing @ manual search when i go to the website from the indexer and search there he found 5-7 movie qualitys for this movie.

And the other point is, sometimes he found some movie, but tells me unknown movie and i cant add it to nzbget, there was no button to send the nzb.

Greet's

**Comment by galli-leo** [comment]
Are you using the indexers via Jackett or directly within Radarr? What are the indexers? Can you attach some logs?

**Comment by D3ltorohd** [comment]
oh sry i forgot it. Here are the logs. I use the indexers directly in radarr. 
Can you see wich indexers from the log ?
[radarr.txt](https://github.com/Radarr/Radarr/files/1066700/radarr.txt)

**Comment by galli-leo** [comment]
I don't really see the indexers from the logs. Can you try enabling debug logging (System -> General), search for the movie in question and post the logs again?

**Comment by D3ltorohd** [comment]
Ok, here a clean log. I hope you can see something. I try to use this indexer

https://wizznab.tk/

On the website there i found some movies - example Ghost in the Shell. On Radarr he search 2 seconds and found nothing.

[radarr Log.txt](https://github.com/Radarr/Radarr/files/1069060/radarr.Log.txt)

**Comment by galli-leo** [comment]
So there are probably two factors playing here:

1. We search the indexer by imdbid, sometimes your indexer might not label the movies correctly or at all, so they wont show up when we search. Nothing we can really do about that :/
2. (From the logs of Ghost in the Shell search) Release groups on your indexers do not seem to include the year after the title. This is currently necessary for Radarr to get where the title of the movie ends and tags, such as Bluray, begin. So if no year is found, we currently just ignore the release. However, there is a pr open for this that will fix this :)

**Comment by effy39** [comment]
@D3ltorohd Now how to join wizznab? I am looking for an invite for a long time.
Thank you.
