### ISSUE TITLE
Unknown movie. Movie found does not match wanted movie.

### ISSUE THREAD

**Issue by madisonprep** [Radarr/Radarr#1658]
**Description:**

When I go search for Free Fire, it pulls only from one indexer and shows the error "Unknown movie. Movie found does not match wanted movie." 

**Radarr Version:**  0.2.0.696

**Logs:**

[Info] NzbSearchService: Searching 3 indexers for [Free Fire]
[Info] DownloadDecisionMaker: Processing 9 releases

After searching manually on the other indexers, they all have the movie. IMDB states that this is a 2016 movie and everywhere else has this movie in 2017. From other errors similar, I've seen that even if the option to force download through the client was allowed, it wouldn't import anyway due to conflict or scene compatibility but in this case it looks like if I could force the download, it would in fact import it. Any help is appreciated.

![capture](https://user-images.githubusercontent.com/29357863/27013457-e4e35efe-4e98-11e7-85dd-d93b0394bfbf.PNG)

**Comment by galli-leo** [comment]
Yeah, IMDB year is 2016, so nothing we can do about that (for now, currently working on alleviating that, see projects for an overview). Scene rules say IMDB year is deciding.

**Comment by galli-leo** [comment]
See also the other issue titled the same.
