### ISSUE TITLE
Doesn't ignore hidden folders (.Trashes, etc)

### ISSUE THREAD

**Issue by loftydan** [Radarr/Radarr#166]
When importing Movies, the hidden folders starting with a dot should be ignored (on a Mac volume for example, .Trashes, .Spotlight-V100, and .Fseventsd)

Other OSes likely have other files at the root of a volume that should be ignore too.

**Comment by luxferro** [comment]
I have an empty .grab folder that showed in my import list when scanning existing movies folder.

**Comment by fryfrog** [comment]
I have a .sync directory for Resilio Sync and it thought it was a movie called Sync. It would be nice to not see .hidden directories. :)

**Comment by tyblu** [comment]
Also `.AppleDouble` folders.

**Comment by galli-leo** [comment]
@tyblu Wtf is that?

**Comment by tyblu** [comment]
Some OSX indexing helper file on some filesystems. I have an iMac and used to have a Macbook on the network, and they must have dropped `.AppleDouble` files into some directories on my NAS volumes while browsing or indexing. It's a complete copy of the real file/folder tree, but each file is just a few KB (must just be a description). Some other software programs pick it up as the real files, too. I actually just deleted all of them with a `find . -name ".AppleDouble" -type d -exec rm -r "{}" \;`, or I'd show you their exact structure, but I'm sure they're still around for others. Here's the [Wiki description](https://en.wikipedia.org/wiki/AppleSingle_and_AppleDouble_formats): 

> macOS revived the use of AppleDouble; on file systems such as NFS and WebDAV that don't natively support resource forks, Finder information, or extended attributes...
