### ISSUE TITLE
Radarr not setting correct priority in SABnzbd based on air date

### ISSUE THREAD

**Issue by SgtBatten** [Radarr/Radarr#1660]
I am trying to set priority to low for anything that is not a new release. 
For testing purposes i have set films with air dates within the last 14 days to be priority high and films greater than 14 days set to priority low.

a film was automatically added to my queue last night. it aired in the 80's according to radarr. It was added with priority high instead of low.
I manually searched for this film again and added two more to the queue myself, one uploaded 7 days ago and one uploaded 900 days ago. Both were given high priority.

In all these cases they should be given low priority.
I have tested with other older films too and so far none have been given low priority.

**Radarr Version:**
0.2.0.696

**Logs:**
I cant see anything in the logs about priority at all.

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by galli-leo** [comment]
Yeah, currently priority is not implemented (see #229)
