### ISSUE TITLE
Movie not removed from queue

### ISSUE THREAD

**Issue by pven** [Radarr/Radarr#1661]
**Radarr Version:**
Version: 0.2.0.696
Mono Version: 4.6.2 (Stable 4.6.2.7/08fd525 Wed Jan 11 15:46:26 CET 2017)

**Logs:**
```
17-6-10 13:18:56.3|Info|Sabnzbd|Adding report [Nice.Movie.2017.HDCAM.x264-DiRG] to the queue.
17-6-10 13:18:57.9|Info|DownloadService|Report sent to SABnzbd. Nice.Movie.2017.HDCAM.x264-DiRG
```

**Problem:**
Radarr finds a movie I want, and sends it to SabNZBD. When SABnzbd is finished, Radarr does not see it is finished.

When I check activity in Radarr it shows the movie is still in the queue. When I check SABnzbd it shows the download is finished. Somehow Radarr is not picking this up. When I check the activity history in Radarr it shows the download for this movie is pushed to SABnzbd.

What is needed so Radarr will pick up the download is finished?

**Comment by galli-leo** [comment]
Is the movie marked as still downloading or is it yellow?

**Comment by pven** [comment]
I am getting confused. It looks like it is about a movie I downloaded twice: one automatically by using Radarr and the other manually to the same download-folder.

To be sure: can both downloads being picked up by Radarr?

**Comment by galli-leo** [comment]
It should, though movies appearing in drone factory are handled differently. Maybe you did not set a downloaded movies scan interval in settings? Then drone factory is disabled and movies in the drone factory folder are not processed.

**Comment by pven** [comment]
When I use the drone factory the movie trigger by Radarr and downloaded by SABnzbd is not processed any further. The message I see in the queue is: 'Intermediate Download path inside drone factory, Skipping.'

**Comment by galli-leo** [comment]
@pven Yeah, that's what I meant. You cannot have the movie inside the drone factory folder and have it processed by our "Automatic Import via Download Clients". It would have to be handled by drone factory, which is probably disabled in your install.

**Comment by pven** [comment]
Ok, clear. Let me create a special radarr-category and radarr-folder, I'll get to this asap.

**Comment by pven** [comment]
It works. Thanks for the support! :-)
