### ISSUE TITLE
Radarr looks confused when using several movie-folders

### ISSUE THREAD

**Issue by pven** [Radarr/Radarr#1662]
**Description:**
I have several movie-folders in Radarr, lets call it:
Movies (main folder)
Classic (sub-directory under Movies)
Docu (seperate folder)

When already downloaded movies are in Movies it works as expected.  But when movies are in one of the two other folders, the base-folder is somehow set to Movies. So Radarr 'thinks' those movies are missing while they are on disk. When I change the folder manually to Classic or Docu and force a rescan it works again. But since this is a lot of work, I prefer to do this automatically.

Can I somehow fix this automatically?

**Radarr Version:**
Version: 0.2.0.696
Mono Version: 4.6.2 (Stable 4.6.2.7/08fd525 Wed Jan 11 15:46:26 CET 2017)

**Comment by galli-leo** [comment]
How did you add the movies?

**Comment by pven** [comment]
I used Bulk Import for each folder

**Comment by galli-leo** [comment]
And how did you import the movies in the Classic sub folder? Did you select the Classic sub folder when doing the bulk import?

**Comment by pven** [comment]
Yes, I did.

When I first select Movies it finds the Classic-folder and tries to find a movie for that folder. I unchecked it. After this I've added the Classic-folder and did the import again.

**Comment by galli-leo** [comment]
Have you tried redoing the bulk import for the movies in the subfolder? Something seems to have gone wrong here.

**Comment by pven** [comment]
Unfortunately that does not work: 'Disabled movies are possible duplicates. If the match is incorrect, update the Tmdb Id cell to import the proper movie.'. The Tmdb Id is correct, but since the movie is already in Radarr it won't update it. I can delete the movies before, but that are a lot of movies. Or can I force it to import it?

**Comment by schumi2004** [comment]
Just reading a few issues on the side and stumbled on this one. 
For my understanding, your importing movies already in Radarr regardless of the folder they are in? 
You find it strange Radarr does not import existing movies? 
What else do you expect? 

My apologies for freaking out here but seriously, is this your issue? 
Movies not being imported that already exists? 
Imo this works as designed.

**Comment by pven** [comment]
No schumi, please try to understand my problem ....

I import movies from sub-folders, but Radarr imports them and administrates the wrong folder. When I try to import again, it is not possible. Since it is about a lot of movies, I don't want to remove them one-by-one to retry the same import, or change the folder manually.

**Comment by galli-leo** [comment]
@pven Can you try removing one movie and importing it again? Just to see if it's reproducable.

**Comment by pven** [comment]
That works, thanks.

Should I delete all wrongly registered movies and re-import, or is there some kind of fix/workaround for this?

**Comment by galli-leo** [comment]
@pven You should be able to edit  the root folder of all the movies in the Movie Editor (Change it to the Classics subfolder)

**Comment by pven** [comment]
I see a nice bug: lets say my Classic-folder is /Movies/Classic. In Radarr this folder has the exact same name. But when my movie is added, the folder for this movie is set to /volume/Movies/ClassicNiceMovie. Where is the last slash? I am going to update my root-folders to include a slash. FYI: I've selected those folders by using browse (instead of typing). I guess this is probably the cause of my problem.

**Comment by galli-leo** [comment]
@pven Good catch!

**Comment by pven** [comment]
Should I log a new issue for that?

**Comment by pven** [comment]
It was some work, but I change the root-folder for all the movies to the right folder.  :-)

To be sure: what if a movie is in Movies, and I move it to ie Classic? Should I update Radarr manually?

**Comment by galli-leo** [comment]
@pven Depends. If you do a lot at a time, I would suggest using Movie Editor and bulk changing the Root Folder. If it's just a few in between, I would suggest just doing it manually.

**Comment by galli-leo** [comment]
Also, I already opened an issue for that one :)

**Comment by pven** [comment]
Thanks for all the support!

I suggest we close this issue?

**Comment by galli-leo** [comment]
Yup.
