### ISSUE TITLE
Unable to connect to SSL - SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by evakq8r** [Radarr/Radarr#1663]
Hi,

I have been unable to connect to Radarr via SSL using the same certificate that works without issue on Sonarr.

**Radarr Version:** 0.2.0.696

**Logs:** No errors in the logs; logs suggest the SSL certificate has registered successfully with the correct thumbprint ID:

> 17-6-12 18:39:59.8|Debug|netsh.exe|Starting netsh.exe http show sslcert ipport=0.0.0.0:<ssl_port>
17-6-12 18:39:59.8|Debug|netsh.exe|SSL Certificate bindings: 
17-6-12 18:39:59.8|Debug|netsh.exe|------------------------- 
17-6-12 18:39:59.8|Debug|netsh.exe|    IP:port                      : 0.0.0.0:<ssl_port>
17-6-12 18:39:59.8|Debug|netsh.exe|    Certificate Hash             : *redacted*
17-6-12 18:39:59.8|Debug|netsh.exe|    Application ID               : *redacted*
17-6-12 18:39:59.8|Debug|netsh.exe|    Certificate Store Name       : (null)
17-6-12 18:39:59.8|Debug|netsh.exe|    Verify Client Certificate Revocation : Enabled
17-6-12 18:39:59.8|Debug|netsh.exe|    Verify Revocation Using Cached Client Certificate Only : Disabled
17-6-12 18:39:59.8|Debug|netsh.exe|    Usage Check                  : Enabled
17-6-12 18:39:59.8|Debug|netsh.exe|    Revocation Freshness Time    : 0
17-6-12 18:39:59.8|Debug|netsh.exe|    URL Retrieval Timeout        : 0
17-6-12 18:39:59.8|Debug|netsh.exe|    Ctl Identifier               : (null)
17-6-12 18:39:59.8|Debug|netsh.exe|    Ctl Store Name               : (null)
17-6-12 18:39:59.8|Debug|netsh.exe|    DS Mapper Usage              : Disabled
17-6-12 18:39:59.8|Debug|netsh.exe|    Negotiate Client Certificate : Disabled
17-6-12 18:39:59.8|Debug|netsh.exe|    Reject Connections           : Disabled
17-6-12 18:39:59.9|Info|OwinHostController|Listening on the following URLs:
17-6-12 18:39:59.9|Info|OwinHostController|  http://*:<non-ssl_port>/
17-6-12 18:39:59.9|Info|OwinHostController|  https://*<ssl_port>/

I can see a similar issue reported here: https://github.com/Radarr/Radarr/issues/1374 - however that was after changing to SSL. SSL works fine locally (via localhost), however does not work externally.

I know the issue is not port forwarding/firewall related as the SSL port is open and works on other applications. I've even moved the Sonarr and Radarr SSL ports around, and the issue is isolated to Radarr only.

Any help would be appreciated.

**Comment by galli-leo** [comment]
Can you try launching Radarr as admin (if you are on windows)?

**Comment by evakq8r** [comment]
I have, and it didn't make any difference. (sorry, forgot to put that in the troubleshooting I had tried).

**Comment by galli-leo** [comment]
What's the ssl port you are using?

**Comment by evakq8r** [comment]
9507

**Comment by galli-leo** [comment]
This seems really weird as it works on localhost, so it is most likely firewall related. Are you running Radarr as a service?

**Comment by evakq8r** [comment]
I agree it's weird, and I thought it was firewall related as well... but identical configuration on the Sonarr installation does not yield this result; it is only Radarr, no matter which port I try (and I know the SSL certificate isn't the issue as it was only purchased yesterday (Comodo) and works fine for any other application I apply it to (SABnzbd, Sonarr, etc)

Radarr wasn't installed as a service, however is now. I have rebooted the server in the process and the results are exactly the same :(

**Comment by evakq8r** [comment]
So... turns out I'm an idiot.

In my finite wisdom, when I added the port mapping to my firewall I inadvertently had a loop going on (was setup to forward from 9507 ->9506 then back again.. all because of one character.

Redone the port mapping as what it should be, and viola!

Thanks for your help @galli-leo - apologies for the rigmarole this caused.

**Comment by galli-leo** [comment]
No problem :)
