### ISSUE TITLE
Enhancement: Timeframe filter for lists

### ISSUE THREAD

**Issue by jobrien2001** [Radarr/Radarr#1664]
Hello,

It would be great to have a filter for movie age (year filter doesn't accomplish this).

Example filters:  
Time since Cinema release: 8 months
OR 
Time since Blu ray release: 2 months

When combined with the cleanup option, it would be easier to keep a new movies only library.

Thanks

**Comment by galli-leo** [comment]
Not sure this is possible with the tmdb lists interface. (And it sure is not possible with any of the others).

**Comment by jobrien2001** [comment]
Can it be coded into Radarr when the list are being parsed to skip those movies that dont fit the criteria?

**Comment by galli-leo** [comment]
It could be, but I would rather not. Because else, Radarr may get info for 100 movies and only actually add 5 of them because all other's do not fit your criterions.

**Comment by jobrien2001** [comment]
That would be the desired outcome.  Maybe place below the list options itself a  counter of number of "ignored records on last sync due user filters"?

Also, this functionality would enable other many more possibilities to filter content than the providers give us through their api.

**Comment by galli-leo** [comment]
Yeah, but I would rather have them filtered out on the server side to save time and bandwidth of the user.

**Comment by jobrien2001** [comment]
That can still be true.

I am proposing additional (not replace) optional filters to what Raddar already offers through their list options.

I understand your response because that scenario would be ideal if the APIs would provide us with more functionality.  Unfortunately they do not, or they cost money in the case of Trakt.

**Comment by galli-leo** [comment]
@jobrien2001 I might, however, implement this feature on our server side (See Radarr Proxied Lists on current nightly).

**Comment by jobrien2001** [comment]
Thank you for taking my suggestion into consideration.  I can see many people taking advantage of this.  

May i ask where the nightly branch is? I can only see develop

**Comment by galli-leo** [comment]
Well "nightly" branch is the develop branch on github, while develop branch (in Radarr settings) is the pre-releases released on github.

**Comment by jobrien2001** [comment]
Maybe in next version? :D
