### ISSUE TITLE
Feature Request: Column for Audio type in Table View

### ISSUE THREAD

**Issue by Coolmanchambers** [Radarr/Radarr#1665]
Check around and didn't see a specific request for this, but it would be amazing to see the audio quality/type on the table view in an additional column.  Would love to see at a glance if something is in surround sound or not so i can work to update if needed.

Would love see the table view customization in the future as well, where you can remove columns you don't need.

Thanks, love it so far!

**Comment by galli-leo** [comment]
I might add a table just for media info (So Audio and Video quality)

**Comment by Coolmanchambers** [comment]
This would be great! Are you also able to get more detailed on the audio portion detail by chance like Plex does?

**Comment by galli-leo** [comment]
Idk, probably.

**Comment by sbels** [comment]
Just coming to Radarr from CP... Looking great!!

One battle that I'm always fighting is getting movies in 7.1 surround sound to take full advantage of my setup. It would be great if we could have a full-blown quality setting for Audio as well. In CP, I have it prefer certain keywords that tend be used for 7.1 but there's no way to automatically re-download if one of those keywords become available later.

Thanks for listening.

**Comment by Qstick** [comment]
Done in Aphrodite
