### ISSUE TITLE
With latest update all my indexers URL were deleted

### ISSUE THREAD

**Issue by rickytin** [Radarr/Radarr#1666]
With latest update all my indexers URL were deleted.

**Comment by galli-leo** [comment]
Yeah, sorry about that, forgot to include a migration after changing some stuff :/

**Comment by rickytin** [comment]
Don't worry, so should I wait for update or do I have to add URL manually.

**Comment by galli-leo** [comment]
I think an update could work on existing installations of the broken update, though you would have to wait at least a day.

**Comment by galli-leo** [comment]
Fix should be live on nightly in a few minutes.

**Comment by nate1280** [comment]
There's an extra comma on line 24 of src/NzbDrone.Core/Datastore/Migration/139_fix_indexer_baseurl.cs causing the migration to crash.
