### ISSUE TITLE
Metadata not created for newly added movie

### ISSUE THREAD

**Issue by ShanDestromp** [Radarr/Radarr#167]
Added a new movie (desired, not existing) to my system, Radarr properly scanned the indexers and downloaded it (as an aside, such download never appeared under activity>Queue though once done it did properly import and appear in Activity>History).

In Settings > Metadata I have Kodi enabled with all options set to "Yes" however nothing appears to get scraped.  No metadata, posters disc-art etc.

On the movies individual page it does have the cover-art and synopsis however.

**Comment by onedr0p** [comment]
I believe this hasn't been updated to work with movies yet. @galli-leo can correct me if I'm wrong

**Comment by galli-leo** [comment]
@onedr0p Yup that's correct.

**Comment by homeskool2** [comment]
ahh thats why 

would be nice to have a note somewhere that this isnt supported yet :( is there an eta?

**Comment by onedr0p** [comment]
We're getting to it, could use some help! lol

**Comment by woble** [comment]
I can't be of any technical help, but perhaps I can point in the right direction. I personally use MediaElch, which in its own time uses Fanart.tv, The Movie DB and IMDB as sources to fetch all the metadata and images. The nice thing about it is that it allows selecting where to fetch specific data from, e.g. rating from IMDB and tagline from TMDB, essentially allowing you to setup your own configuration of metadata scraping. Works really great, albeit a manual process. Having that flexibility with the added automated process in Radarr would be really great, including updates of stream details whenever a new release has been acquired.

**Comment by Buster14** [comment]
I'm not sure if this could be any help but, i frequently generate metadata using script from filebot. 
Here's what i use:
https://drive.google.com/drive/folders/0Bwc1KPPVNa_9Y3lkTkZCTDdsZTQ?usp=sharing
You only need to change the path in movie_download.bat

**Comment by Buster14** [comment]
Hi any progress on this? really looking forward for this.. thanks

**Comment by woble** [comment]
Editing, fetching and managing manually metadata would be really great. Fully relying on automated process can sometimes yield undesired results.

**Comment by Buster14** [comment]
I forgot there is an easier method, although i'm not sure how it applies to radarr..
Simply install filebot and run the script mentioned here:
https://www.filebot.net/forums/viewtopic.php?f=4&t=5#p205
Maybe integrate this with radarr?

**Comment by Buster14** [comment]
So any ETA for this? Been looking forward for this since last year..

**Comment by galli-leo** [comment]
No eta, I know it sounds lazy, but for know you can use custom scripts to achieve the same thing.

**Comment by ShanDestromp** [comment]
@galli-leo can we at least get the nfo file generation built in?  I mean the data is already being scraped and stored since it shows up on the detail page.  Part of the reason I switched to radarr was because it was supposed to be sonarr but for movies and how I wouldn't HAVE to do a bunch of extra steps like with Couch potato et al.

**Comment by euphoria360** [comment]
Any update on this?
By looking to above Issue, Seems they fixed it 3 days ago and merged it with main branch. Have any of you had any luck after new changes?

**Comment by galli-leo** [comment]
@euphoria360 It wasn't merged (and will be later today), hence why it still say "Open" in green. Also you need to use the nightly, else you have to wait for a release.

**Comment by euphoria360** [comment]
Thanks @galli-leo . In [releases ](https://github.com/Radarr/Radarr/releases)page you mentioned to change the branch to "develop". Should I choose nightly instead?

Also there seems to be no button to start manual update, should I change branch and enable automatic update?

**Comment by galli-leo** [comment]
Change it to nightly, and go to the updates tab. You should see the new changes in a few minutes there, when it finishes building (just merged).
