### ISSUE TITLE
Movies Files not recogenised... 

### ISSUE THREAD

**Issue by Systemshark** [Radarr/Radarr#1675]
**Description:**

Unable to parse movie info from path D:\Media\Parents_Films\300\300.mp4

Radarr is saying this file doesn't exist.  but it's located the file and therefore should match the file. I've looked at the related issue below but renaming films with years is not acceptable for over 300 films. 
Given it know the info about the film, whty doesn't it include it into the database and mark as downloaded not missing. 

related issue : Movie file not recognized #1485

**Radarr Version:**
Version 0.2.0.696 

**Logs:**

7-6-12 18:01:54.4|Info|DiskScanService|Scanning disk for 300
17-6-12 18:01:54.4|Warn|ParsingService|Unable to parse movie info from path D:\Media\Parents_Films\300\300.mp4
17-6-12 18:01:54.4|Info|DiskScanService|Completed scanning disk for 300
17-6-12 18:01:54.5|Error|MediaCoverService|Couldn't download media cover for [tt0416449][300 (2006)]

**Comment by galli-leo** [comment]
Yeah, I am working on adding support for movies without year, but it's a good idea to rename them anyways (check out the wiki for programs that do it automatically). A lot of media software will be much happier with years. Anyways, this is a duplicate issue, so closing this.

**Comment by galli-leo** [comment]
https://github.com/Radarr/Radarr/wiki/Create-a-Folder-for-Each-Movie#filebot
