### ISSUE TITLE
Feature Request: Add "MPAA" option to folder naming

### ISSUE THREAD

**Issue by imadunatic** [Radarr/Radarr#1677]
Long time CP (and Sonarr) user, first time Radarr user... Curious if it's possible to add an option of "MPAA" to folder naming? 

Use case: Pseudo semi-autonomous parental controls on new movies. I use this so I can filter what my kids automatically have access to by controlling which folders are connected to their Emby account. 

This is how I have my Movie folder options set in cp:
```
<mpaa_only>\<thename> (<year>)
```
Is this possible? 

If not, nbd, just dipping my toe in currently.... Thanks in advance either way.

**Comment by galli-leo** [comment]
Currently not possible. Also not sure if we will ever support it. IMO this is much better solved via software (emby, plex), rather than via folders.

**Comment by imadunatic** [comment]
Thanks. 3 Years ago, when I set this up, parental controls in everything was almost non-existent so this was my workaround. I have users set up in both Plex and Emby so it shouldn't be too tough, I'll research that and let CP do the renaming in the meantime.
