### ISSUE TITLE
Unable to add movies

### ISSUE THREAD

**Issue by ofurpesi** [Radarr/Radarr#1679]
Hi there

I am unable to add existing and new movies

Radarr Version: 0.2.0.696

Running on Server 2012 R2

Logs:
![errors](https://user-images.githubusercontent.com/8067418/27087597-ef592dc0-5044-11e7-9e0d-ced0f1b3482c.PNG)

**Comment by galli-leo** [comment]
That looks like a dns issue. Can you make sure you can ping api.themoviedb.org / radarr.video from a command line?

**Comment by ofurpesi** [comment]
Thank you so much and sorry for wasting your time. Turns out my server was having a DNS stroke

**Comment by galli-leo** [comment]
No problem, happy to help :)
