### ISSUE TITLE
Option to remove current download when manually downloading a new torrent.

### ISSUE THREAD

**Issue by jhfry** [Radarr/Radarr#1683]
I hope this hasn't been suggested before, though I know it has been discussed regarding Sonarr.

Currently, radarr doesn't appear to take into account the number of seeds/peers when selecting a torrent, and you may end up with one with a single peer and less than 100% availability (I have two just today).

I propose two changes to fix this:
1. Allow a minimum threshold for peers/seeds.  I know that the peer/seed data is not always accurate, but it's better than nothing.

The argument against this over on the Sonarr project was that it's not uncommon for a show to only have a single seed minutes after airing, but it will grow from there.  Reasonable argument, especially on a private tracker.  But for movies, especially on public trackers, there are a lot of stale torrents out there.

2. Provide the ability to do a manual search and selecting a different file (torrent or nzb) to replace a current download.  It should automatically cancel the existing download in progress.

Currently, I just get an error if I try to manually start a new download.  If I first fail the existing download, it automatically picks another, and I may have to go through several to find one that will work.

**Comment by onedr0p** [comment]
1 is already in the develop branch.

2 is a bit tricky because some clients don't allow you to remove the torrent thru API calls.

**Comment by galli-leo** [comment]
Also Radarr will always take into account how much seeds a torrent has. If a release with same quality (e.g. Bluray) is present, Radarr should choose the one with more seeders.

**Comment by jhfry** [comment]
Glad to hear that there will be some features coming to somewhat optimize the torrent experience.  I'm sure there is some logic there, but in my case it chose the same "proper" twice from two indexes, then chose the non-proper release of the same torrent from both indexers.  I suspect it was because it was tagged with all of the "good" stuff, like AAC and H265, and yada yada yada.  Anyway, it completely ignored several far more available torrents of the same resolution (1080p).

As far as #2 is concerned, I completely appreciate that some clients may not be compatible... but that could be adjusted for.  In one case you initiate a manual or automatic download and it asks "Another download is in progress for this movie, would you like to cancel it and download this release instead?".   If the client doesn't provide the ability to terminate a download, it could simply prompt "This release will not begin downloading until you manually terminate the download in progress in <client>"

**Comment by galli-leo** [comment]
@jhfry Regarding 1., I plan on adding a system by which the seeders count is more important than other stuff.
Regarding 2., not sure if that is really necessary. You should be able to already remove items via the queue or history tab.

**Comment by jhfry** [comment]
RE #2.... it isn't very clear what the best way to do this is.  If you fail the download, it will search for another.  It won't let you start a new download while one is in progress (at least I couldn't), and killing the download in my client either leaves it in limbo or causes it to fail at which point it selects another.  I'm sure there is a way to do it, but its not intuitive and likely requires work outside of radarr which should be avoided if at all possible.

**Comment by bakerboy448** [comment]
Closing
v0.2 is no longer being actively developed.

If this is still an issue/request on recent v3 builds, please open a new issue.

Seeders have been factored in to rankings
