### ISSUE TITLE
Movie folder issue

### ISSUE THREAD

**Issue by X-static** [Radarr/Radarr#1688]
Hi, when radarr creates the movie folder it's using the format "movie name (year)". But it is expecting just the movie name. For example,  the movie The Driver is on folder:

D:\Filmes\The Driver(1972)

But on radarr, on the movie page:

D:\Filmes\The Driver

So stays as missing on radarr. I'm using the default movie and folder naming.

**Comment by galli-leo** [comment]
How did you add this movie?

**Comment by X-static** [comment]
From the android app radarrlink, I think.

**Comment by X-static** [comment]
I made a test and I think it my be because of the app.

**Comment by galli-leo** [comment]
@X-static That would be my guess as well, since we should use the correct naming scheme when adding a movie without a path. Could be that the dev of Radarr link already sends us a path and thus we do not set it again.
