### ISSUE TITLE
Can't connect to destination movie folder

### ISSUE THREAD

**Issue by MountaingoatCT** [Radarr/Radarr#1689]
I have had a problem where Radarr doesn't move downloaded movies from the completed folder to my NAS.  I use Sonarr as well and I don't have the issue there.

With a pit of research on Github, I realised the issue was I wasn't using the UNC path.  Checked on my Sonarr and realised okay that is true.  So I tried to change the directory path to UNC exactly like I have it on Sonarr, but to a movie directory.  As follows:

Sonarr path is:  \\NASFEACFA3\My TV\Series
Used this path on Radarr \\NASFEACFA3\My TV\Movies, but Radarr keeps saying path not found

What am I missing here.  I have attached some screen shots of Radarr, Sonarr, and directory folder structure to help.

I even tried the path to "Series" and Radarr says invalid

THanks
![folder](https://user-images.githubusercontent.com/13812287/27217356-d486e88e-5279-11e7-9d79-bd5486bf71a5.PNG)
![radarr](https://user-images.githubusercontent.com/13812287/27217357-d487049a-5279-11e7-9c36-c676f46cebb9.PNG)
![sonarr](https://user-images.githubusercontent.com/13812287/27217358-d487567a-5279-11e7-838f-41c257ee0deb.PNG)

**Comment by galli-leo** [comment]
Are you using Radarr as a service?

**Comment by MountaingoatCT** [comment]
Yes I am

Paul Benn (AdvDipBPM,DipBA)
Project Manager/ IT Business Analyst
Cell: 083 300 9541. Linkedin : https://za.linkedin.com/in/pbennct
_________________________________________________________________________________
Solving Business problems

**Comment by galli-leo** [comment]
@MountaingoatCT Try running the Radarr exe normally (so not as a service). Also try running the Radarr exe as admin. Services have problem accessing networked drives in Windows.

**Comment by MountaingoatCT** [comment]
@galli-leo sorry for my ignorance, but do you not run as a service?
When I launch I run the exe.  Under Task Manager I see it running as a service

**Comment by MountaingoatCT** [comment]
@galli-leo I figured out how to run as administrator.  Right click and run as administrator
Tried again and same issue File path not found

**Comment by MountaingoatCT** [comment]
OKay some more playing around and reading.  So I created a shortcut in startup and I can now see the mapped drive e.g. W:\Movies\Hell or High Water (2016) - and I can see all movies under that directory through Radarr, however, I can't map the UNC path from this as i get a path not found error.

Not sure if this is a break through or is going to work

**Comment by galli-leo** [comment]
Yeah, the service is usually run under a special account, which usually does not have access to networked drives. Maybe, the admin account also does not have access to the networked drive? That would explain why it only worked when you put the exe in the startup folder, since only then did Radarr run under the account with the correct permissions. Mapped paths should be fine.

**Comment by MountaingoatCT** [comment]
Tested and moving to startup solved the issue.
Thanks for the help
