### ISSUE TITLE
Unable to add movie after correcting Tmdb Id

### ISSUE THREAD

**Issue by Cam-Corp** [Radarr/Radarr#1690]
Hey all,
I am migrating from CP and have been able to add most of my movies but there are a few that will not add. There were all incorrectly identified, so I have updated the Tmdb Id as it says to do and they now show correctly but the selection checkbox is still grayed out, see below. Am I missing something? 

CC

![radarr_before](https://user-images.githubusercontent.com/29487719/27235498-e456fa46-5275-11e7-95d7-d5c5a87c3f78.PNG)
![radarr_after](https://user-images.githubusercontent.com/29487719/27235508-ecebc9a2-5275-11e7-9ff7-a8c155893eea.PNG)

**Comment by galli-leo** [comment]
IIRC this should be fixed on the latest nightly. Can you try upgrading to that?

**Comment by Cam-Corp** [comment]
Thank you that was it, am running Radarr on a QNAP so was on the develop branch, changed to nightly and updated to 0.2.0.779 and its all working fine.
