### ISSUE TITLE
'English is wanted, but found Dutch'

### ISSUE THREAD

**Issue by pven** [Radarr/Radarr#1691]
A lot of release are rejected due to 'English is wanted, but found Dutch'. Can I somewhere tell Radarr the dutch is preferred?

In the indexer-configuration I've added dutch to 'Whitelisted Subtitle Tags', but it looks like that does not help.

**Radarr Version:**
Latest

**Comment by galli-leo** [comment]
What is the release named like? Also you can set the language in the Profile.

**Comment by pven** [comment]
Fixing the profile solved it. Thanks!
