### ISSUE TITLE
[Feature Request] Allow Symlinking instead of Copy

### ISSUE THREAD

**Issue by Magic815** [Radarr/Radarr#1693]
**Description:**

So I realize that Radarr was simply forked from Sonarr, which didn't have symlinking ability, but I wanted to put in a feature request for Radarr anyways.

For all of us torrent users, who belong to private trackers and need to worry about permaseeding, the only option right now is hardlinking. However, between using Sonarr and Radarr, this means that I need to have all of my downloaded torrents, all of my shows, and all of my movies all fit on one hard drive. My largest drive is 6TB, and is currently 95% full, so hardlinking will soon run out of space.

Instead, if there was a way to have symlinking as a choice, I could much more easily spread out the files across hard drives.

**Comment by galli-leo** [comment]
You could still split up movies and tv-shows into two hard drives. That's what I am currently doing for seeding. We are probably not gonna implement this, until Sonarr do.

**Comment by lattedesu** [comment]
Related issue on Sonarr as a referrence for discussion.

https://github.com/Sonarr/Sonarr/issues/967

Also, here's a commit on a fork of Radarr for symlink feature from @elegant996 , which may be helpful:

https://github.com/Elegant996/Radarr/commit/15bdaa8f11f134ea141c8af001abc3199f7cd180

**Comment by Qstick** [comment]
Closing this, when Sonarr implements an issue will be created automatically to pull it over.
