### ISSUE TITLE
Radarr will not start on OS X Sierra but does run in the activity monitor.

### ISSUE THREAD

**Issue by RicardoMontabon** [Radarr/Radarr#1694]
Running OS X Sierra on a Mac Mini with Safari. Radarr was working fine until today when I attempted to start the program and I see that it was running in my activity monitor; however, I try and connect to localhost:7878 and I get the message that Safari cannot connect to server. I've replicated the problem multiple OS X computers and multiple browsers (to include firefox). The issue does not affect my Windows 10 machines as they all run it just fine. No changes have been made to the computer and it is up to date. Any idea why this would have broke all of a sudden and if so how do I fix it? i cannot even access the logs to see why it's not starting up. Many thanks in advance.

**Comment by galli-leo** [comment]
Logs should still be visible under ~/.config/Radarr/. Can you look there and post them?
