### ISSUE TITLE
Feature Request: Support running as non root user on Freenas Jails

### ISSUE THREAD

**Issue by Aghassi** [Radarr/Radarr#1698]
**Description:**
Currently, the wiki states that to setup Radarr in a jail on Freenas, the `rc.d` file is run through `mono`. The way this service is setup, in its basic form, runs as user `root` with group id `wheel`. However, this is problematic for users like me who have a specific `media` group and user. While I have mapped the storage required for the jail so Radarr can see it, it currently doesn't work due to permissions since `root` doesn't reside in `media` group (and I don't plan on adding it currently). As such, I'd like to request a better way for this to be run. For example, Sonarr runs from the jail as its own user `sonarr` (which I can find via `cat /etc/passwd`) and is in group `sonarr` (which can be found via `cat /etc/group`). As such, I would like to see Radarr do the same as above. This way, I can create a user `radarr` on my Freenas server, and augment it with group `media`. 

Thank you in advance for considering this.

Check first that your problem is not listed in our wiki section:
* https://github.com/Radarr/Radarr/wiki/Common-Problems
* https://github.com/Radarr/Radarr/wiki/FAQ

Provide a description of the feature request or bug here, the more details the better. 
Please also try to include the following if you are reporting a bug

**Radarr Version:**
Pre-Release v0.2.0.696

**Logs:**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by galli-leo** [comment]
See here: https://www.reddit.com/r/radarr/comments/5qht69/guide_on_how_to_install_radarr_as_a_servicedaemon/dhh0c4y/

**Comment by Aghassi** [comment]
Gah, alright I'll give that another go. I've tried that, but when I reboot the service isn't starting so I'm trying to debug it to figure out how to fix that.

**Comment by JoeB99** [comment]
I've done this, but it's still running as root as shown by `ps - aux`
