### ISSUE TITLE
add cat for uhd -- omg

### ISSUE THREAD

**Issue by thezoggy** [Radarr/Radarr#1699]
omg category `Movies: UHD` is id 31

**Comment by Vortec4800** [comment]
Wanted to add a +1 on this, the omg uhd category is getting pretty good but Radarr isn't able to find anything in it at the moment. Would be great to open this up to the indexer.

**Comment by ags131** [comment]
+1 to this, a temporary workaround is to select omg from the Newzabs presets and change categories to 15,16,17,31

**Comment by thezoggy** [comment]
still valid

**Comment by galli-leo** [comment]
@thezoggy  Are you using nightly? I think I merged a pr that added these cats

**Comment by galli-leo** [comment]
Yeah see #2764
