### ISSUE TITLE
Add indexer: Pass The PopCorn

### ISSUE THREAD

**Issue by tymanthius** [Radarr/Radarr#17]
I don't have an invite to send you, or I would.  But I can help test it.  :)

Edit: Removed boilerplate message

**Comment by galli-leo** [comment]
That's great, but for really implementing it I would have to have a login. Else I don't see how I can debug it :/

**Comment by tymanthius** [comment]
Gotcha.  If I get an invite, I'll let you know.  :)

BTW, I did find a work around - Jackett supports PTP, and that works with sonarr & Radarr.

**Comment by galli-leo** [comment]
The latest release should include a working Torznab indexer. Thus you should be able to connect Jackett with Radarr. (However, it searches using a query at the moment, so not ideal)

**Comment by onedr0p** [comment]
Search is working, and you are able to download them in PR #64 

I am thinking about adding `Golden / Scene / Checked` flags somewhere to be shown on the search page, but need to think about where to put them.

**Comment by evulhotdog** [comment]
Ideally there would be an option for require AND preferred of both Golden and Checked.

For example, my preference is requiring checked torrents, and preferring Golden releases.

**Comment by onedr0p** [comment]
I believed I worked this into the logic now, I also added indicators for golden / approved. I think there will be more to add to this in the future but for now I am happy with it.

![image](https://cloud.githubusercontent.com/assets/213795/21765307/fee523f4-d635-11e6-86f0-4b95c042284c.png)

![image](https://cloud.githubusercontent.com/assets/213795/21765287/dd957d52-d635-11e6-8873-12d431ca2130.png)

**Comment by evulhotdog** [comment]
That's awesome @onedr0p! Now we just need to change the star to a popcorn kernel ;P

**Comment by galli-leo** [comment]
@onedr0p @evulhotdog You could probably change it to the Popcorn emoji: 🍿

**Comment by onedr0p** [comment]
Done :)

**Comment by galli-leo** [comment]
Fixed by #64

**Comment by theotherp** [comment]
Could you provide some help with the Cookie? I added PHPSESSID, _cfduid and session in this format:

`_cfduid=<alphanumeric>; session=<base64perhaps?endingwith==>; PHPSESSID=<alphanumeric>`

But I get 

`Unable to connect to indexer. Unexpected response status Redirect code from API request`

**Comment by onedr0p** [comment]
Are you able to access this page in your browser?

https://passthepopcorn.me/torrents.php?json=noredirect

**Comment by theotherp** [comment]
Yep.

**Comment by evulhotdog** [comment]
@theotherp all I needed was 
`session=xxxxxxx`

**Comment by onedr0p** [comment]
Is where you are running Radarr, behind any VPN or double NAT?

**Comment by onedr0p** [comment]
@evulhotdog it let you do that? 

I have a rule that says otherwise (unless my regex fails me)

```csharp
            RuleFor(c => c.Cookie)
                .Matches(@"__cfduid=[0-9a-f]{43}", RegexOptions.IgnoreCase)
                .WithMessage("Wrong pattern")
                .AsWarning();
```

**Comment by theotherp** [comment]
I can enter what I want for the cookie.

**Comment by onedr0p** [comment]
For some reason or other you're getting a `301 Moved Permanently` response code from PTP.

Going to the URL do you get a 200 response in your browser?
https://passthepopcorn.me/torrents.php?json=noredirect

![image](https://cloud.githubusercontent.com/assets/213795/21821214/b365e7d6-d740-11e6-9ecf-2ce163b969ec.png)

**Comment by theotherp** [comment]
Alright, I copied the Cookie from the "Headers" tab in Firefox (previously I stitched the string together using the "Request Cookies" in the "Cookies" tab) and now it encoded the cookie. Not sure if that's the difference that made it work, but it does work now. Thanks for the help!

**Comment by onedr0p** [comment]
awesome :)

**Comment by standardcake** [comment]
Can anyone help me with the cookie?  I tried all of the suggestions above, but I'm having no such luck.  

I tried using Jackett instead but it seems the search functionality is not working.  I'm running Radarr on my QNAP so the latest version I have is 0.2.0.99

**Comment by onedr0p** [comment]
Goto PTP and press `crtl+shift+i` and then follow the highlighted... copy then entire cookie, everything after **cookie:**

![image](https://cloud.githubusercontent.com/assets/213795/22005216/6544e234-dc2f-11e6-964b-25e25c51eb62.png)

**Comment by standardcake** [comment]
Yep, that's what I did.  Still getting: 

Unable to connect to indexer, check the log for more details

Hmmmm...

**Comment by standardcake** [comment]
System.Net.WebException: Curl Error 77 for Url https://passthepopcorn.me/torrents.php?json=noredirect&searchstr=, issues with your operating system SSL Root Certificate Bundle (ca-bundle).
  at NzbDrone.Common.Http.Dispatchers.CurlHttpDispatcher.GetResponse (NzbDrone.Common.Http.HttpRequest request, System.Net.CookieContainer cookies) <0xee0600e8 + 0x0072b> in <filename unknown>:0 
  at NzbDrone.Common.Http.Dispatchers.FallbackHttpDispatcher.GetResponse (NzbDrone.Common.Http.HttpRequest request, System.Net.CookieContainer cookies) <0xf2800e68 + 0x001ef> in <filename unknown>:0 
  at NzbDrone.Common.Http.HttpClient.Execute (NzbDrone.Common.Http.HttpRequest request) <0xf281d9a8 + 0x00180> in <filename unknown>:0 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].FetchIndexerResponse (NzbDrone.Core.Indexers.IndexerRequest request) <0xf08edeb0 + 0x00131> in <filename unknown>:0 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].FetchPage (NzbDrone.Core.Indexers.IndexerRequest request, IParseIndexerResponse parser) <0xf08ede70 + 0x0001a> in <filename unknown>:0 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].TestConnection () <0xf01271e8 + 0x0009e> in <filename unknown>:0

**Comment by standardcake** [comment]
Fixed the problem by installing QPerl and QCACert as referenced here:

https://forum.qnap.com/viewtopic.php?t=122407#top

Thanks!

**Comment by jra3** [comment]
This is cool, but instead of grabbing the cookie, this should take the username, password and passkey (the passkey is used by clients like this to disable captchas) and go through a login. look at how this is done in couchpotato

https://github.com/CouchPotato/CouchPotatoServer/blob/b538f9a08db9a0be1af2f298727834edeafa322e/couchpotato/core/media/_base/providers/torrent/passthepopcorn.py

I can try to get a dev environment set up to send a PR, but I probably wont have time. I never do C# development

**Comment by theotherp** [comment]
Jackett and/or Cardigann uses username and passkey as well.


Check https://github.com/Jackett/Jackett/blob/master/src/Jackett/Indexers/BroadcastTheNet.cs and https://github.com/Jackett/Jackett/blob/master/src/Jackett/Indexers/PassThePopcorn.cs

**Comment by onedr0p** [comment]
To everyone, I will make PTP work without cookies. Please understand I did it that way to save time and get other bugs fixed. I will update the code in the future.
