### ISSUE TITLE
Resolution of movie not discovered correctly

### ISSUE THREAD

**Issue by fryfrog** [Radarr/Radarr#170]
I have a movie with a resolution of 1920x800 as displayed by mkvinfo, but a rename calls it 720p.

https://ptpb.pw/SRiI

What other information can I provide?

**Comment by galli-leo** [comment]
Can you post the exact name of the file as well as a trace log?

**Comment by fryfrog** [comment]
File was: 10 Cloverfield Lane (2016).mkv

Is now: 10 Cloverfield Lane (2016) [HDTV-720p].mkv

Do you want a trace log of literally running the rename?

**Comment by galli-leo** [comment]
Yea that would be great.

**Comment by galli-leo** [comment]
If the quality is not in the movie, it must be the media info fails. I will have to investigate, but if that's the case, there is not much we can do :/

**Comment by fryfrog** [comment]
> 17-1-11 13:47:33.7|Debug|RenameMovieFileService|Renaming movie file: [834] 10 Cloverfield Lane.mkv
17-1-11 13:47:33.7|Debug|MovieFileMovingService|Renaming movie file: [834] 10 Cloverfield Lane.mkv to /cold/videos/Movies/10 Cloverfield Lane (2016)/10 Cloverfield Lane (2016) [HDTV-720p].mkv
17-1-11 13:47:33.7|Debug|DiskTransferService|Move [/cold/videos/Movies/10 Cloverfield Lane (2016)/10 Cloverfield Lane.mkv] > [/cold/videos/Movies/10 Cloverfield Lane (2016)/10 Cloverfield Lane (2016) [HDTV-720p].mkv]

**Comment by fryfrog** [comment]
I'm not seeing anything in the logs that looks like a read into the video's metadata in anyway.

**Comment by fryfrog** [comment]
At the very least, surely it is feasible to discover the resolution of a file... right?

**Comment by woble** [comment]
Kodi sees it as 1080.

**Comment by galli-leo** [comment]
Is there anything in the log with MediaInfo? Or could you send me a link to the file in question via reddit pm? It's difficult to find out what's behind this without the file.

**Comment by fryfrog** [comment]
Effectively all of my movies are 1080p, but none of them are named with quality or resolution in their name. So just "Movie (Year).ext". I ran the renamer on the first 5 in my list and they all end up w/ 720p incorrectly (HDTV as quality, which I find no fault with).

I *think* you could just pick a random 1080p movie in your collection, name it "Movie (Year).ext" and the run an organize on it.

**Comment by galli-leo** [comment]
Ok I will try that.

**Comment by julestop** [comment]
I have a similar issue, not sure if the exact same or I should create a new issue... but I added a movie in 1080P as the cutoff. It downloaded a 720P version, and classified it as 1080P and stopped looking for any more.

![screen shot 2017-01-11 at 6 45 20 pm](https://cloud.githubusercontent.com/assets/1585230/21871123/19a6fa6a-d82e-11e6-90bd-72e5f3c66d7d.png)

**Comment by galli-leo** [comment]
This issue should be resolved in the feature/file-info branch.
