### ISSUE TITLE
Error 500 and disabled indexers on non-standard IMDB IDs

### ISSUE THREAD

**Issue by Dopefish123** [Radarr/Radarr#1703]
**Description:**
Any added movies of a non-standard imdb type (tv, video, in development, shorts etc.) will trow a 500 error and disable the indexer.
The 500 error is from Jackett and is fine per say, the big problem is Radarr disabling the indexer. 

**Radarr Version:**
0.2.0.696
0.2.0.775

**Logs:**
HTTP Error - Res: [GET] http://localhost:9117/torznab/rarbg/api?t=movie&cat=100046,100042,100017,100044,100045,100014,100048,2030,2040,2060&extended=1&apikey=(removed)&offset=0&limit=100&imdbid=2732654: 500.InternalServerError
RARBG HTTP request failed: [500:InternalServerError] [GET] at [http://localhost:9117/torznab/rarbg/api?t=movie&cat=100046,100042,100017,100044,100045,100014,100048,2030,2040,2060&extended=1&apikey=(removed)&offset=0&limit=100&imdbid=2732654]

**Comment by galli-leo** [comment]
That seems to be more an issue with Jackett than with Radarr? Did you open an issue over on the Jackett page? There shouldn't be a 500 error just because we gave Jackett an imdbid it did not expect. Also why would you add tv shows to Radarr?

**Comment by Dopefish123** [comment]
I'm going post it there as well, just didnt have time earlier today.

My point was that there should be some type of check to see if there the error codes are persistent or ones of. Expecting 3. party services to return a good code 100% of the time is unrealistic and disabling them for this isn't good.

> Also why would you add tv shows to Radarr?

It not shows but movies released on tv marked with (TV) on imdb, for example:
http://www.imdb.com/title/tt0109868/reference
Plus the others listed above.

**Comment by Dopefish123** [comment]
https://github.com/Jackett/Jackett/issues/1486

**Comment by galli-leo** [comment]
Yeah, but a 500 usually means there is something wrong with the server, which is why we disable it. Maybe they should return a 422, indicating that our request was bad?

**Comment by Dopefish123** [comment]
They should, but at the same time maybe you can implement 5 bad in a row = disable or something to verify that is is down and not just have a temp issue.

**Comment by galli-leo** [comment]
That's not really trivial to implement and I am sure there is a reason why the Sonarr folks did it this way.

**Comment by Dopefish123** [comment]
It probably was. Quick question haven’t tested it, but will the indexer be disabled forever if you do not reactivate it or will Radarr retry it at a later stage? How about a setting toggle to active “Always try indexer/never disable”

**Comment by galli-leo** [comment]
It should be reenabled after a set time IIRC.

**Comment by Dopefish123** [comment]
Okay, thanks will test it, have not had the patience so far. Btw good work, really appreciate the software. Tip; publish a bitcoin address for some donations.

**Comment by galli-leo** [comment]
See linked Jackett issue.
