### ISSUE TITLE
DownloadedMovieImportService Unable to process folder that is mapped to an existing show

### ISSUE THREAD

**Issue by kvanbiesen** [Radarr/Radarr#1704]
**Description:**
The Log keeps getting spammed with the same message. Some movies dont throw the warning but most of them do. Radarr seems to work fine, other than that. But the log files get huge for no reason
![](https://i.imgur.com/qLpHIus.png)

**Radarr Version:**
Version:
0.2.0.696

Mono Version:
5.0.1.1 (2017-02/5077205 Thu May 25 09:16:53 UTC 2017)

**Logs:**
17-6-20 07:57:49.0|Warn|DownloadedMovieImportService|Unable to process folder that is mapped to an existing show
17-6-20 07:57:49.0|Debug|Parser|Parsing string 'The.Lego.Batman.The.Movie.2017.720p.WEB-DL.H264.AC3-EVO'
17-6-20 07:57:49.0|Trace|Parser|^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(19|20)\d{2}(?!p|i|\d+|\]|\W\d+)))+(\W+|_|$)(?!\\)
17-6-20 07:57:49.0|Debug|Parser|Movie Parsed. The Lego Batman The Movie - 2017 
17-6-20 07:57:49.0|Debug|Parser|Language parsed: English
17-6-20 07:57:49.0|Debug|QualityParser|Trying to parse quality for The.Lego.Batman.The.Movie.2017.720p.WEB-DL.H264.AC3-EVO
17-6-20 07:57:49.0|Debug|Parser|Quality parsed: WEBDL-720p v1
17-6-20 07:57:49.0|Debug|Parser|Release Group parsed: EVO
17-6-20 07:57:49.0|Trace|ConfigService|Using default config value for 'downloadedmoviesfolder' defaultValue:''
17-6-20 07:57:49.0|Debug|Parser|Parsing string 'The.Lego.Batman.The.Movie.2017.720p.WEB-DL.H264.AC3-EVO'
17-6-20 07:57:49.0|Trace|Parser|^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(19|20)\d{2}(?!p|i|\d+|\]|\W\d+)))+(\W+|_|$)(?!\\)
17-6-20 07:57:49.0|Debug|Parser|Movie Parsed. The Lego Batman The Movie - 2017 
17-6-20 07:57:49.0|Debug|Parser|Language parsed: English
17-6-20 07:57:49.0|Debug|QualityParser|Trying to parse quality for The.Lego.Batman.The.Movie.2017.720p.WEB-DL.H264.AC3-EVO
17-6-20 07:57:49.0|Debug|Parser|Quality parsed: WEBDL-720p v1
17-6-20 07:57:49.0|Debug|Parser|Release Group parsed: EVO
17-6-20 07:57:49.0|Warn|DownloadedMovieImportService|Unable to process folder that is mapped to an existing show
17-6-20 07:57:49.0|Debug|Parser|Parsing string 'Moana.2016.720p.BRRip.X264.AC3-EVO'
17-6-20 07:57:49.0|Trace|Parser|^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(19|20)\d{2}(?!p|i|\d+|\]|\W\d+)))+(\W+|_|$)(?!\\)
17-6-20 07:57:49.0|Debug|Parser|Movie Parsed. Moana - 2016 
17-6-20 07:57:49.0|Debug|Parser|Language parsed: English
17-6-20 07:57:49.0|Debug|QualityParser|Trying to parse quality for Moana.2016.720p.BRRip.X264.AC3-EVO
17-6-20 07:57:49.0|Debug|Parser|Quality parsed: Bluray-720p v1
17-6-20 07:57:49.0|Debug|Parser|Release Group parsed: EVO
17-6-20 07:57:49.0|Trace|ConfigService|Using default config value for 'downloadedmoviesfolder' defaultValue:''
17-6-20 07:57:49.0|Debug|Parser|Parsing string 'Moana.2016.720p.BRRip.X264.AC3-EVO'
17-6-20 07:57:49.0|Trace|Parser|^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(19|20)\d{2}(?!p|i|\d+|\]|\W\d+)))+(\W+|_|$)(?!\\)
17-6-20 07:57:49.0|Debug|Parser|Movie Parsed. Moana - 2016 
17-6-20 07:57:49.0|Debug|Parser|Language parsed: English

**Comment by galli-leo** [comment]
Seems like you pointed the movies in question to the folder from your dl client. Thus Radarr will not process them. Either delete those items from your dl clients history or hardlink them to somewhere else.
