### ISSUE TITLE
Folder names for downloaded movies not including Quality, MediaInfo

### ISSUE THREAD

**Issue by shobhitsinghal624** [Radarr/Radarr#1708]
**Radarr Version:**
0.2.0.778 develop

**Description:**
I have folder naming set to: `{Movie Title} ({Release Year}) [{Quality.Full}.{MediaInfo.Full}.{Release.Group}]`
But all the folders are being named as `{Movie Title} ({Release Year}) []`

Same config works well for renaming movie files.

**Comment by galli-leo** [comment]
@shobhitsinghal624 You need to enable automatic folder renaming as well as change you movies paths to be dynamic.
