### ISSUE TITLE
IMDB list: Folder is not saved

### ISSUE THREAD

**Issue by yeroentje** [Radarr/Radarr#1709]
**Description: The folder option within the IMDB list is not saved. It was already a problem within the previous version, but with the update to v0.2.0.778 the folder isn't even saved anymore and the field is just left blank, after saving**

Check first that your problem is not listed in our wiki section:
* https://github.com/Radarr/Radarr/wiki/Common-Problems
* https://github.com/Radarr/Radarr/wiki/FAQ

Provide a description of the feature request or bug here, the more details the better. 
Please also try to include the following if you are reporting a bug

**Radarr Version: 0.2.0.778**

**Logs: Nothing is written in the logs, once the IMDB list is saved**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by galli-leo** [comment]
Are you sure the path is not saved? Because it just becomes blank for me too, but is actually saved correctly.

**Comment by yeroentje** [comment]
Yes, seems to work. Better than previous version actually. So it's just a GUI thing. Can be closed.
