### ISSUE TITLE
Sorting by status does... nothing?

### ISSUE THREAD

**Issue by fryfrog** [Radarr/Radarr#171]
Sorting by Title works, Profile may or may not (only one profile in use on mine), In Cinemas kind of works. But by Status doesn't seem to work at all.

In Cinemas:
![screen shot 2017-01-11 at 2 07 24 pm](https://cloud.githubusercontent.com/assets/87748/21868396/6f2514f8-d807-11e6-9410-2e80ce59f32b.png)

Status One Way:
![screen shot 2017-01-11 at 2 05 15 pm](https://cloud.githubusercontent.com/assets/87748/21868339/2f9c4fcc-d807-11e6-9182-eb1941a43747.png)

Status The Other:
![screen shot 2017-01-11 at 2 05 31 pm](https://cloud.githubusercontent.com/assets/87748/21868342/31809e06-d807-11e6-88b9-27575db68167.png)

**Comment by galli-leo** [comment]
Yea currently on my todo list.

**Comment by chrisallen** [comment]
Related/Dupe: https://github.com/Radarr/Radarr/issues/128
