### ISSUE TITLE
After edit movie path > falls back to wrong/another earlier edited movie

### ISSUE THREAD

**Issue by Anakim** [Radarr/Radarr#1710]
Hallo,

i have a Problem with my Radarr Installation on a qnap. I use the latest Version.
Here my Problem:
When i edit a movie path and save it, Radarr falls back to another movie that i edited earlier and not to the movie i actual edited.

When i try to search the movie over the search bar an klick on the movie it doesn't turn to the wanted movie. To come back to my movie i must use the movie or wanted button and use the search bar to find my movie.

The wrong movie he falls back change after some time.

Sorry for my poor English ;-)

Anakim

**Comment by galli-leo** [comment]
Yeah noticed that as well. Not sure yet why it happens though :/

**Comment by Anakim** [comment]
thanks i think you will find solution ;-)

**Comment by Anakim** [comment]
Hy galli-leo,

today it works somehow better .. i edit some movies today and he jumps after edit to the movie i start
i don't know what i do differently today ? .. 

Can it be that the update has corrected the error?

Anakim

**Comment by galli-leo** [comment]
@Anakim I did not fix the error specifically, so something might have fixed it. Though I suspect it's something else.

**Comment by Anakim** [comment]
Ok .. yesterday i made more Tests .. Error is still present but very rare at the moment
It might be a special Kombination of things
I continue to test and try to narrow it down

Anakim

**Comment by c0rnflake** [comment]
Pretty sure this is more or less the same issue as #1729

**Comment by Anakim** [comment]
I close the ticket because it did not happen anymore and think the problem was fixed.

thx for help
