### ISSUE TITLE
'Folder' field no longer being saved in Lists

### ISSUE THREAD

**Issue by nifharv** [Radarr/Radarr#1711]
**Description:**

Since my installation upgraded to 0.2.0.778 my lists no longer retain the 'Folder' field (it is blank and will not save any changes if you try and revert to the root of one of my library folders). Instead, anything automatically snatched from one of these lists is instead downloaded to C:\ProgramData\Radarr\bin. 

This is the same for all of the following list types (both existing ones and any new ones I create):
- RSS
- TMDb
- Trakt

**Radarr Version:**
0.2.0.778 
**Logs:**
[radarr.trace.txt](https://github.com/Radarr/Radarr/files/1091811/radarr.trace.txt)

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by galli-leo** [comment]
Can you verify that the issue with movies being set to C:\ProgramData\Radarr\bin occurs with a brand new list, where the path is correctly selected? (Only opened once) From what I have seen that is only a visual glitch and the path is not actually empty.

**Comment by piret28** [comment]
hi guys!!i dont know where to write...i download some days ago trakt and it doesnt open!!of course exodus doesnt authorize now trakt....thats why i try to work trakt without exodus involved...i spoke with support of trakt and they help me giving instructions...when i download it and try to open i couldnt...

**Comment by nifharv** [comment]
Hi galli-leo, this issue affects both existing and brand new lists. Just to be clear though, the 'Folder' field in the lists is blank rather than set explicitly to C:\ProgramData\Radarr\bin; this path is auto set in each added movie from the lists and therefore is where the movie gets downloaded to (like it is a default path for the app or something). 

When you and try and correct the 'Folder' field in one of the lists to one of the movie root folders it doesn't save the setting (remains blank).

I also noticed when looking at the NetImport table in nzbdrone.db that the values for 'RootFolderPath' do not match those that you see in the web UI - out of 9 lists 2 do actually have correct paths but the rest are blank whereas all are blank in the UI. 

Any ideas?

**Comment by galli-leo** [comment]
@nifharv Yeah, each time you save they go back to being blank, but the value stored in the db is the correct one. You prolly did not save all of them yet.

**Comment by nifharv** [comment]
they weren't updating the db for some reason but I found that if you change another setting at the same time (I toggled 'Enable Automatic Sync') it would update the db. However, if you subsequently change another setting (with the 'Folder' field blank) it will then blank the 'RootFolderPath' field in the db.

**Comment by galli-leo** [comment]
@nifharv Yeah, you have to reselect the folder path each time.

**Comment by mizled** [comment]
@galli-leo This definitely is not just a visual glitch. Any movie that gets added via a list, it sets the root directory to "/" instead of "/path/to/my/Movies". I have tried editing the list and deleting it and re-adding and neither work. The value for "Folder" is always blank. WHen the movie goes to download it fails on the import because it can't write to root.

`Couldn't import movie /mnt/Plex/incomplete/movies/Smurfs.The.Lost.Village.2017.1080p.WEB-DL.DD5.1.H264-FGT/Smurfs.The.Lost.Village.2017.1080p.WEB-DL.DD5.1.H264-FGT/S.L.V.2017.1080p.WEB-DL.DD5.1.H264-FGT.mkv: Access to the path "/Smurfs The Lost Village (2017)" is denied.`

**Comment by christiga** [comment]
Same problems here :
- on the list setting
- on path of the movie

**Comment by galli-leo** [comment]
@mizled At least on all installs I have tried it's just a visual glitch. Can you make sure that the path is still wrong when you select the correct path (and change another setting for it to be saved), then not open the list again?

**Comment by mizled** [comment]
@galli-leo When I change another setting on the list page and select the correct path it still shows blank for me after I save. However, I am confused by your comment about "not open the list again". How would I verify that the correct setting is kept if I can't open the list again?

**Comment by galli-leo** [comment]
@mizled Add a movie from the list and then check its path. Yeah, folder will show up blank again (no idea why yet) but it's actually correct (at least for me).

**Comment by galli-leo** [comment]
Sorry did not mean to close it, hit the wrong button :)

**Comment by jeramie72** [comment]
i'm having this issue too now.. i couldn't figure out what was going on.. had everything running fine then all of a sudden my imdb watchlist added items were not being moved into their correct folder.  i went and looked and for some reason the imdb watchlist "list" folder field in radarr was blank, did some googling and decided to delete that radarr list and create a new one.. even tho that older list had worked fine for a while now.. anyway.. i deleted the old.. created a new one.. set the folder.. saved it.. the field remains blank. BUT.. it does in fact work fine now.. so for my situation it does appear to be a visual issue where the folder filed doesn't appear to be pulling the variable forward from the db, so be careful to reselect the correct folder before saving if you make changes in there.

**Comment by galli-leo** [comment]
Interestingly, this works fine for me on safari.

**Comment by ward0** [comment]
issue still open?

**Comment by galli-leo** [comment]
@ward0 What Radarr version are you on?

**Comment by ward0** [comment]
@galli-leo latest DEV it seems...

**Comment by galli-leo** [comment]
@ward0 Can you try clearing cache & cookies as well as trying a different browser? It works fine on my end.

**Comment by ward0** [comment]
already done, tried from edge to ie11 to chrome...

**Comment by galli-leo** [comment]
@ward0 Just to be sure, what's the exact Radarr version you are using? (Should be displayed at the bottom of the page)

**Comment by ward0** [comment]
@galli-leo  DEV 0.2.0.870

**Comment by AntaeusNar** [comment]
Radarr Ver. 0.2.0.892 nightly - I am seeing the same problem for all of my IMDB Watchlists.  

The Log Error is : Couldn't import movie /mediaLV/Downloads/The Blues Brothers (1980) [1080p]/The.Blues.Brothers.1980.1080p.BrRip.x264.bitloks.YIFY.mp4: Access to the path "/The Blues Brothers (1980)" is denied.

Attempting to change the root folder setting on either the IMDB Watchlist settings, or using the mass movie editor does nothing.

Changing the root folder movie by movie after they have been added seems to work.

**Comment by galli-leo** [comment]
@AntaeusNar Yeah changing the path of the List afterwards wont change the already added Movies.

**Comment by AntaeusNar** [comment]
Yeah, I ment to say that changing it in the lists doesn't seem to
hold/affect new additions.

**Comment by simonvpe** [comment]
I'm experiencing the same thing. Additionally I have two different disks for movies, /movies & /movies2. /movies2 does'nt show up in the drop down either so I had to save, copy the sen't http request and change the folder to /movies2 and re-send manually. This worked, added IMDb List movies now end up in /movies2.

**Version** 0.2.0.910
**Mono Version** 5.4.1.6 (tarball Wed Nov 8 20:37:08 UTC 2017)
**OS** Fedora 26

**Comment by Rouzax** [comment]
Same issue here
![image](https://user-images.githubusercontent.com/4103090/43963374-725db732-9cba-11e8-967c-4d33ad7c589c.png)
Have 2 folders
![image](https://user-images.githubusercontent.com/4103090/43963388-7ed3233a-9cba-11e8-95a9-d6393cc66d12.png)

Version: 0.2.0.1120
OS: Windows 2016
Browser: Firefox 61 64bit
