### ISSUE TITLE
Mapped Network drives not recognized

### ISSUE THREAD

**Issue by coberajoe** [Radarr/Radarr#1712]
**Description:**
Mapped network drives not recognized.  Only shows C Drive in lists for both Drone folders as well as media management recycling bin.

**Radarr Version:**
0.2.0.778 - Jun 20 2017
Tuesday, June 20 2017 4:30am

**Logs:**
Nothing shown in logs

**Comment by galli-leo** [comment]
Have you tried manually starting the exe and launching it as admin?

**Comment by gregcbrown** [comment]
I use **Task Scheduler** to start **Radarr.Console.exe** "when I log in" and give it admin permissions. Apparently you can't launch a task in STARTUP with admin priveledges...

**Comment by rschmetzer** [comment]
Same here.  Radarr installed as a service can't see the mapped network drive but initiated downloads are successful via SABnzbd.

**Comment by galli-leo** [comment]
@rschmetzer Yeah networked drives do not play nicely with services.

**Comment by rschmetzer** [comment]
If I wanted to deinstall Radarr as a service and reinstall as a "normal" program so it can see my mapped drive, how would I go about that?

**Comment by galli-leo** [comment]
@rschmetzer There should be a ServiceUninstall.exe file beside the Radarr.exe file. Then I would create a link to the Radarr.exe file in your startup folder.

**Comment by rschmetzer** [comment]
That worked!  Thanks!

**Comment by gregcbrown** [comment]
Worked for me too, Thanks.
