### ISSUE TITLE
Local Newznab server failing to test or add.

### ISSUE THREAD

**Issue by coberajoe** [Radarr/Radarr#1713]
**Description:**
I run a localized Newznab server and Radarr fails test when trying to connect.  Settings taken from Sonarr do not seem to work.  I also attempted to use ip and host name along with generating a new API key.
Checked Newznab server logs and does not show the connection attempt.

**Radarr Version:**
0.2.0.778 - Jun 20 2017
Tuesday, June 20 2017 4:30am

**Logs:**
[errorlog.txt](https://github.com/Radarr/Radarr/files/1092384/errorlog.txt)
[radarr.txt](https://github.com/Radarr/Radarr/files/1092390/radarr.txt)

**Comment by galli-leo** [comment]
Pretty sure that's because your local indexer does not support searching by imdbid. You should be able to add it anyways (should work fine) by either clicking add and save or disabling both rss sync and searching, adding then reenabling both again.

**Comment by coberajoe** [comment]
I can add it, however it still will not test or function.   I'm pretty sure that Newznab supports searching by imdbid.
Thanks anyways.

**Comment by galli-leo** [comment]
Did you manually search for a movie? It may just not have that movie present (Because we are testing with Star Wars).
