### ISSUE TITLE
Can't see mapped drives again

### ISSUE THREAD

**Issue by MountaingoatCT** [Radarr/Radarr#1714]
Hi
A few days ago I submitted an issue where I can't access a mapped drive.
I then found a shortcut in the startup folder which worked and movies copied across to the mapped drive.

Then rebooted my laptop yesterday and that shortcut was missing in the startup folder.
No problem created a new one....but now I can't see the mapped drive in Radarr and movies once again don't transfer.....
Is there a trick or something I am missing in creating the shortcut.  Copying the exe into start folder also doesn't work as it cant launch if not in the /bin folder.

**Comment by galli-leo** [comment]
You have to create a shortcut to the exe.
