### ISSUE TITLE
[Request] Expand Grabbed email info

### ISSUE THREAD

**Issue by pietervw** [Radarr/Radarr#1715]
I would like to see the email notifications for when a movie is grabbed, to also include a link to the source from where the film was grabbed, similar to what can be seen when hovering over a file under the Info button.

This will allow users to follow the link in the email to immediately open the torrent info screen on the respective indexer to view information like size and seeds/peers and comments.

**Comment by bakerboy448** [comment]
Closing
v0.2 is no longer being actively developed.

If this is still an issue/request on recent v3 builds, please open a new issue.
