### ISSUE TITLE
Improve discovery error handling.

### ISSUE THREAD

**Issue by galli-leo** [Radarr/Radarr#1719]
Discovery error handling should be improved, i.e. when no movies are present in library, tell user to add new movies, instead of telling him, that discovery found no movies.

Errors from web service could be relayed somehow to web UI maybe.

**Comment by onedr0p** [comment]
This is an old issue tagged with UI, this is very likely fixed in v3. Please let us know otherwise (and even if you want this feature in v3) and we will reopen the issue.
