### ISSUE TITLE
Incorrect github page summary

### ISSUE THREAD

**Issue by Sup3rLativ3** [Radarr/Radarr#172]
Hi,

Just a small change to the top of the project page. It currently reads:

"Smart PVR for newsgroup and bittorrent users. https://sonarr.tv"

It should read:

"A fork of Sonarr to work with movies à la Couchpotato. https://github.com/radarr/radarr"

**Comment by woble** [comment]
Related to #115

**Comment by galli-leo** [comment]
Fixed.
