### ISSUE TITLE
MissingMovieSearch does not seem to run regularly

### ISSUE THREAD

**Issue by ChrisColotti** [Radarr/Radarr#1720]
**Description:**
It seems that the missingmoviesearch is not working automatically.   I cannot find a task in the task list for it, but there are movies there that I've been waiting for and only if I click "search all" under wanted/missing will it then grab them.  Sonarr processes missing episodes automatically and I would have thought that Radarr would as well, but it never seems to be working.

Maybe related to this:  https://github.com/Radarr/Radarr/issues/548

Just seems like anything "monitored" is not functioning like Sonarr does where it's hands off and processed automatically on a regular basis for the better quality or if it's missing all together.

Check first that your problem is not listed in our wiki section:
* https://github.com/Radarr/Radarr/wiki/Common-Problems
* https://github.com/Radarr/Radarr/wiki/FAQ

Provide a description of the feature request or bug here, the more details the better. 
Please also try to include the following if you are reporting a bug

**Radarr Version:**
0.2.0.778

**Logs:**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by galli-leo** [comment]
Sonarr does not search for missing episodes actively. See here for an explanation: https://github.com/Sonarr/Sonarr/wiki/FAQ#how-does-sonarr-find-episodes

Though we want to add a backlog search functionality to Radarr. (It's on feathub)

**Comment by ChrisColotti** [comment]
I guess for me first search is good if the movie is already in RSS, but if it's not there is no re-seach mechanism.  I just posed on FeatHub but all we really need is a system task that kicks off "MissingMovieSearch" once a day.  As I have found it, anything not found on initial search goes into Missing, and is never searched again via the normal RSS process if monitored.  I always have to go into missing and click "search all"....which is a little silly when a system task could do it.

**Comment by galli-leo** [comment]
@ChrisColotti If the rss sync does not pick it up, either the rss sync interval is too high or the rss of your indexer is messed up. For me, rss sync works really well. Though as I said, we do plan on integrating backlog search in the future.

**Comment by ChrisColotti** [comment]
I just started playing around with MinAvail.  my indexerrs are good (nbz.su and OMG) but I think it was set to PreDB

**Comment by galli-leo** [comment]
@ChrisColotti Ah yeah that may have been it too. See the wiki for what we recommend.

**Comment by ChrisColotti** [comment]
Yep!  Read it after we started this chat :).  RTFM I guess....HAHAHA.  Changed off PreDB and will see how that works.
