### ISSUE TITLE
Trouble with NZBGet priorities determined by Radarr

### ISSUE THREAD

**Issue by nemchik** [Radarr/Radarr#1723]
**Description:** I have Radarr configured with NZBGet as my (only) download client, and I have it set to Recent Priority: Very High and Older Priority: Normal. The description claims Recent Priority should only be applied to items that have aired in the past 14 days, however I am seeing movies added to NZBGet with High Priority from Radarr and the movies were released MANY years ago.

**Radarr Version:** 0.2.0.778

**Logs:** Looking in the Logs Table doesn't seem to show me much about the Priority.
MovieSearchService	Movie search completed. 1 reports downloaded.	6:58am
DownloadService	Report sent to NZBGet. [REMOVED]	6:58am
Nzbget	Adding report [REMOVED] to the queue.	6:58am

**Comment by galli-leo** [comment]
Yeah, that's not implemented yet. There is an open issue to do it though, and I should get around to it eventually.

**Comment by nemchik** [comment]
I should also note that not EVERYTHING is added at high priority (considered recent). I'll have it mark a movie from 1994 as high priority (recent) but then mark something from 2014 as normal.

**Comment by nemchik** [comment]
Ok, great! I looked but I did not find that issue anywhere else, can we reference it here and close this issue? Hopefully if others search they will find one or the other!

**Comment by galli-leo** [comment]
#229 :)
