### ISSUE TITLE
Radarr with not connect.

### ISSUE THREAD

**Issue by raynotroy** [Radarr/Radarr#1726]
**Description:**

I cannot get Radarr to run from the Drobo5N.  Sonarr works just fine.  I'm not sure if this is related to trying to run both of them on the same system or not.  I have already tried deleting the config directory and restarting my device.  Any help would be greatly appreciated.

**Radarr Version:**

v0.2.0778

**Logs:**

[radarr 0.2.0.778.txt](https://github.com/Radarr/Radarr/files/1096956/radarr.0.2.0.778.txt)

**Comment by galli-leo** [comment]
What version of mono are you using? What download did you choose? Also what's Drobo5N?

**Comment by hotio** [comment]
He seems to be using mono-4.0.4, which is almost 2 years old...

**Comment by raynotroy** [comment]
The version of mono that I am using is the latest available for my device.  The Drobo5N is a NAS unit with officially supported apps like mono.  I have Sonarr running on my Drobo5N so I don't think there's a problem with mono.

**Comment by galli-leo** [comment]
Well there's nothing I can do here, since I don't have such a NAS. I would recommend upgrading the mono version.
