### ISSUE TITLE
Radarr service won't start

### ISSUE THREAD

**Issue by BurningTheSky** [Radarr/Radarr#1727]
Hi,

I did an install yesterday using the latest version and it seemed to work, today when I restarted the box I am getting an issue starting. Does anyone know what could be causing this?

```
burningsky@ubuntu:~$ service radarr status
● radarr.service - Radarr Daemon
   Loaded: loaded (/etc/systemd/system/radarr.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: exit-code) since Fri 2017-06-23 12:24:11 BST; 1s ago
  Process: 1280 ExecStart=/usr/bin/mono --debug /opt/Radarr/Radarr.exe --nobrowser (code=exited, status=2)
 Main PID: 1280 (code=exited, status=2)

Jun 23 12:24:10 ubuntu systemd[1]: radarr.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jun 23 12:24:10 ubuntu systemd[1]: radarr.service: Unit entered failed state.
Jun 23 12:24:10 ubuntu systemd[1]: radarr.service: Failed with result 'exit-code'.
Jun 23 12:24:11 ubuntu systemd[1]: radarr.service: Service hold-off time over, scheduling restart.
Jun 23 12:24:11 ubuntu systemd[1]: Stopped Radarr Daemon.
Jun 23 12:24:11 ubuntu systemd[1]: radarr.service: Start request repeated too quickly.
Jun 23 12:24:11 ubuntu systemd[1]: Failed to start Radarr Daemon.
```

**Comment by galli-leo** [comment]
Can you post some logs from Radarr?

**Comment by BurningTheSky** [comment]
I am a bit of a linux newbie, could you guide me to where they would be? I looked in /home/NzbDrone/.config/Radarr/Logs but they don't seem to be updating.

I got told something had changed and I needed to run "systemctl daemon-reload" this time when I tried to start the service, but that didn't seem to make a difference.

**Comment by galli-leo** [comment]
@BurningTheSky They should be in that location. Can you try executing the `/usr/bin/mono --debug /opt/Radarr/Radarr.exe --nobrowser` command yourself in a terminal?

**Comment by BurningTheSky** [comment]
Should I be running it as the user that's in the service config or won't that work?

On 23 Jun 2017, at 21:21, Leonardo Galli <notifications@github.com<mailto:notifications@github.com>> wrote:


@BurningTheSky<https://github.com/burningthesky> They should be in that location. Can you try executing the /usr/bin/mono --debug /opt/Radarr/Radarr.exe --nobrowser command yourself in a terminal?

**Comment by BurningTheSky** [comment]
I worked out the issues, mix of linux inexperience and just not thinking! Firstly, I changed the UID of the NzbDrone to match that on my NAS so I could get NFS share working and didn't think about folder permissions not updating. Then I realised sonarr and radarr have the same default SSL port so they were fighting over it and radarr was losing. I disabled on sonarr, restarted and both came back live. Have updated them to be on different ports. So in summary, pebkac!

**Comment by bramdsgn** [comment]
I'm on windows, and Radarr service won't start, 
note: netstat cmd indicates that 7878 port is in use

any suggestions ?

**Comment by ThePrankMonkey** [comment]
In case anyone finds this, I resolved my issue by ensuring my radarr user had a home and recursively owned all files under (for me) /opt/radarr.

**Comment by murdock-commits** [comment]
Had the same issue. Solved it by using this article : [https://www.htpcguides.com/install-radarr-on-debian-8-jessie/](url)
