### ISSUE TITLE
If I change the path of a movie file it saves sometimes not

### ISSUE THREAD

**Issue by Anakim** [Radarr/Radarr#1729]
I have another problem.
Sometimes i edit the path of a movie because the path has changed.

Problem 1
for example the wrong Name is: Insidious Chapter 2 (2013). When i change the wright path to Insidious - Chapter 2 (2013) in the line where the path and movie name exists, the path won't be save. In this dialog he shows me with a little popup that he found the new paht. When i edit it again the wrong path although exist.

Problem 2
in this example i changed the path over the Dropdown Menu and select the path from my NAS. Does not work either. The path is always wrong.

Solution for me is that i delete the movie without delete the files an reimport the movie.

Is this a bug or wanted?

Greetings
Anakim

**Comment by c0rnflake** [comment]
No idea why this isn't a higher priority, i'm sure it's frustrating everyone.

Just to add that these movies are often marked as missing, and if they are available radarr is continually downloading them and not marking them as found.

Also, when using Chrome and editing a movie the "Static" switch will auto move to Yes when you save the updated path etc.

**Comment by Anakim** [comment]
I close the ticket because it did not happen anymore and think the problem was fixed.

thx for help
