### ISSUE TITLE
Minimum Availability Default in Radarr from OMBI

### ISSUE THREAD

**Issue by davemanster** [Radarr/Radarr#1731]
When requesting movies from OMBI that is connected to Radarr, there is no availability set. This is causing a bunch of fakes to be downloaded. I have already submitted a bug report/feature request to OMBI on GitHub.

The latest nightly added the ability to have default request levels, but it requires a user to choose one while logged into Radarr. This does not seem to save from OMBI. The bug is that it is not saved when added from an API. 

Check first that your problem is not listed in our wiki section:
* https://github.com/Radarr/Radarr/wiki/Common-Problems
* https://github.com/Radarr/Radarr/wiki/FAQ

Provide a description of the feature request or bug here, the more details the better. 
Please also try to include the following if you are reporting a bug

**Radarr Version:0.2.0.779**

**Logs:**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by galli-leo** [comment]
It is not supposed to be carried over to the API. This is the responsibility user of the API imo (same with root folders or series settings in Sonarr)
