### ISSUE TITLE
Change File Date Issue

### ISSUE THREAD

**Issue by nathan951** [Radarr/Radarr#1732]
Change file date works as expected, but if set to "Physical" or "Cinemas"  it causes ill effects with Kodi and others only WHEN date is a FUTURE date (ie 2 days or 2 weeks from now...)

Suggestion if "Change File Date" is set to "Physical" or "Cinemas", have a check box displayed "Set future dates to current date/time"

or just have any future dates save as current date&time

**Comment by michaelarnauts** [comment]
It should be fine to have folders with a date in the future. I guess a fix is needed in Kodi if it can't handle those.

**Comment by bakerboy448** [comment]
Closing
v0.2 is no longer being actively developed.

If this is still an issue/request on recent v3 builds, please open a new issue.

Kodi should be able to handle those....not an ARR issue
