### ISSUE TITLE
[request] Movie DB/IMDB info portal on movie page.

### ISSUE THREAD

**Issue by gstrange42** [Radarr/Radarr#1733]
One thing that might be useful on the individual movie pages, is to have a tab for the movie info site of your choice. A the moment it just starts with the History tab, and it might be nice to have the first tab being the movie info. 

I'd be happy with an iframe or other systems that just showed the movie site of the users choice. As developing a layout the data from other sites might take longer.

**Comment by galli-leo** [comment]
You already have the links there, so not sure why you would need that. Also we only pull info from TMDB so no point in adding a tab for more info.

**Comment by gstrange42** [comment]
It just gives you more info on the individual movie page, rather than having to go to a different site.  Also, it makes the page a little more interesting than just a series of lists.

**Comment by galli-leo** [comment]
Yeah, but we cannot provide more info than we already give, since we only use TMDB. So just opening the imdb page in a new tab is equally effective.
