### ISSUE TITLE
[Bug] When using lists existing unmonitored (manually) gets re-added as monitored

### ISSUE THREAD

**Issue by weikinhuang** [Radarr/Radarr#1734]
**Description:**

I'm currently using the StevenLu list and several TMDB lists, and am manually marking movies I don't want by adding them and then marking as unmonitored, however when the movie appears in the list, it is always re-marked as monitored and will be attempted to be downloaded. Is there a way to not re-monitor a movie if it already exists in an unmonitored state?

**Radarr Version:** v0.2.0.696

**Comment by galli-leo** [comment]
There should be a new develop release out. Can you verify that the bug exists there as well?

**Comment by weikinhuang** [comment]
Seems like this has been resolved in the latest, I'll close and continue to monitor. Thanks!
