### ISSUE TITLE
Minimum Seeders not saving in developer version

### ISSUE THREAD

**Issue by jonesb63** [Radarr/Radarr#1736]
Minimum Seeders not saving in developer version,

**Comment by galli-leo** [comment]
All indexers, just a few, which one's have you tried?

**Comment by theCheek** [comment]
wow fast work :) To answer your question it was for torznab, but I can see you already figured that one out.

**Comment by eenewbie** [comment]
Hi - the minimum seeders still not saving in v 0.2.0.778 for torznab. Is this working for anyone else?

**Comment by galli-leo** [comment]
@eenewbie The fix is not on develop yet. Only on nightly

**Comment by EridianBrian** [comment]
@galli-leo any idea when it will make it onto production? I keep getting really poor torrents, some with no seeds/peers at all...

**Comment by jamesmacwhite** [comment]
@EridianBrian It will be when the next release is created from the `develop` branch. A workaround currently would be to manually set the required int value into the appropriate field in the SQLite DB. You'd need to have a little knowledge about SQL queries however.

**Comment by EridianBrian** [comment]
@jamesmacwhite all good, I have updated it though the database, thanks :)
