### ISSUE TITLE
Lists wont save Folder path

### ISSUE THREAD

**Issue by nawo69** [Radarr/Radarr#1737]
Whenever i add a new list and set the Folder path as soon as i save it the folder option is blanked so movies default to C:\Windows\System32. Tried re-adding the lists and still the same

Also my StevenLu list sudden changed from working fine to having the folder path to blank too; think it was when i pressed the save button as just done it on another working list (without changing any settings) and that has blanked the Folder path too. This is happening on 2 setups

**Radarr Version:** 0.2.0.779

**Comment by galli-leo** [comment]
See #1711, it's just a visual glitch, make sure you are not saving an empty path and when you open the list you have to change something else besides the path, so that the correct path is saved.
