### ISSUE TITLE
No-Rename functionality not working/working unexpectedly

### ISSUE THREAD

**Issue by pannal** [Radarr/Radarr#1738]
**Description:**
I'm using radarr with all movie rename options disabled to mimic the behaviour of CouchPotato, which took the NZB name or release name and created a folder accordingly.

In radarr this doesn't seem to work as expected, as radarr creates a `Moviename (Year)` folder and puts the file inside. When I click `Preview rename for movie` on that particular movie, it shows the expected correct folder as rename target (`MovieReleaseName-GROUP`), which I'd expect radarr to use in the first place when grabbing the movie.

After clicking the rename/organize button, radarr renames the folder correctly, but doesn't update its own records, thus marking the movie `missing`. I have to manually specify the new folder radarr itself renamed afterwards, to make it see the movie file again.

**Radarr Version:**
0.2.0.778

**Logs:**
```
17-6-27 03:06:39.0|Info|RefreshMovieService|Updating Info for The Moviename
17-6-27 03:06:39.9|Info|RenameMovieFileService|[tt1212428][The Moviename (2016)]'s movie should be /xxxx/yyyyy/movies/The Moviename 2016 according to your naming config.
17-6-27 03:06:39.9|Info|DiskScanService|Scanning disk for The Moviename
```

**Comment by pannal** [comment]
Also Radarr seems to default to "Static Path" even though the option isn't enabled.

**Comment by pannal** [comment]
1 month bump!

**Comment by galli-leo** [comment]
It's working for me. Is the path set to dynamic for the movie? Do you have automatic folder renaming enabled?

**Comment by pannal** [comment]
Renaming is off altogether. Paths are non-static by default. But somehow after downloading a movie, radarr saves it in `Moviename (year)` folder and sets the path to static automatically.

I also tried to turn rename on and use `{Original Title}` as the format, but that didn't work either.

**Comment by pannal** [comment]
In short: I want the original release name as the folder name, no renaming of the files itself, like CouchPotato did it by default.

**Comment by silv3r23** [comment]
> In short: I want the original release name as the folder name, no renaming of the files itself

Hello, I want the original release name as the folder name too! Complete Download Handling and renaming are off. But Radarr leaves the original folder with files like sample, nfo, ... and moves the movie file into "Moviename (Year)" after the download.

![image](https://user-images.githubusercontent.com/28316411/28798567-221d7d58-7645-11e7-9a60-197945eea30d.png)

v. 0.2.0.778

**Comment by galli-leo** [comment]
@pannal Can you post a screenshot of your Media Management Settings?

**Comment by pannal** [comment]
![image](https://user-images.githubusercontent.com/1359593/28820078-8f17fcd8-76b0-11e7-8ac6-d35144304cb7.png)

**Comment by pannal** [comment]
Did that help @galli-leo or do you need more?

**Comment by pannal** [comment]
This seems to work now, with the newest release. Can you confirm, @silv3r23?

**Comment by silv3r23** [comment]
@pannal yes, the last downloads have the correct release name with my settings.

**Comment by pannal** [comment]
Thank you!

**Comment by silv3r23** [comment]
hello, found the problem with renaming and not deleting the old movie folders. [https://github.com/Radarr/Radarr/issues/1738#issuecomment-319199133](see my previous comment)
if there are sample video files after extracting, radarr will leave the old moviefolder as shown.
my workaround is to enable "ignore samples" in sabnzbd.

`18-1-2 15:19:44.6|Debug|MovieFileMovingService|Moving movie file: /mnt/nas/Saw.I.DC.2004.BDRip.AC3.German.XviD-POE/poe-sawI.avi to /mnt/nas/Saw (2004)/Saw.I.DC.2004.BDRip.AC3.German.XviD-POE.avi
18-1-2 15:19:44.6|Debug|DiskTransferService|Move [/mnt/nas/Saw.I.DC.2004.BDRip.AC3.German.XviD-POE/poe-sawI.avi] > [/mnt/nas/Saw (2004)/Saw.I.DC.2004.BDRip.AC3.German.XviD-POE.avi]
18-1-2 15:19:44.9|Info|MovieService|Linking [Saw.I.DC.2004.BDRip.AC3.German.XviD-POE.avi] > [[tt0387564][Saw (2004)]]
18-1-2 15:19:45.1|Debug|DiskScanService|Scanning '/mnt/nas/Saw.I.DC.2004.BDRip.AC3.German.XviD-POE' for video files
18-1-2 15:19:45.1|Debug|DiskScanService|1 video files were found in /mnt/nas/Saw.I.DC.2004.BDRip.AC3.German.XviD-POE
18-1-2 15:19:45.1|Debug|Parser|Parsing string 'poe-sawI-sample.avi'
18-1-2 15:19:45.2|Debug|Parser|Unable to parse poe-sawI-sample.avi
18-1-2 15:19:45.2|Warn|DownloadedMovieImportService|Unable to parse file on import: [/mnt/nas/Saw.I.DC.2004.BDRip.AC3.German.XviD-POE/poe-sawI-sample.avi]`

the method "DeleteFolder" will never be called if there is one more video files after moving the moviefile to its new folder. please fix it in case of movies which are splitted into two files (disc one and disc two).

**Comment by gammelgaard52** [comment]
Any solution to this one? It's still a problem in the latest releases.
