### ISSUE TITLE
Radarr importing from Featurettes folder..

### ISSUE THREAD

**Issue by Zero0Q** [Radarr/Radarr#1742]
Radarr is importing from Featurettes folder in some movies.
Name:
2001: A Space Odyssey
Source:
/share/Public/2001 - A Space Odyssey 1968 (1080p Bluray x265 HEVC 10bit AAC 5.1 Tigole)/Featurettes/2001 - The Making of a Myth.mkv
Imported To:
/share/Multimedia/Movies/2001 A Space Odyssey (1968)/2001 A Space Odyssey (1968) [Bluray-1080p] [x265.AAC.2.0-Radarr].mkv

Different release: Importing EXTRAS
Name:
2001: A Space Odyssey
Source:
/share/Public/2001 A Space Odyssey 1968 (1080p x265 10bit Joy)/Extras/Kubrick Interview by Jeremy Bernstein 1966 Audio Only.mkv
Imported To:
/share/Multimedia/Movies/2001 A Space Odyssey (1968)/2001 A Space Odyssey (1968) [HDTV-1080p] [x265.AAC.2.0-Radarr].mkv

Radarr Ver. 0.2.0.778 develop 

Log: 
DownloadedMovieImportService
Non-sample file detected: [/share/Public/2001 - A Space Odyssey 1968 (1080p Bluray x265 HEVC 10bit AAC 5.1 Tigole)/2001 - A Space Odyssey 1968 (1080p x265 10bit Tigole).mkv]
11:47am

MovieService
Linking [2001 A Space Odyssey (1968) [Bluray-1080p] [x265.AAC.2.0-Radarr].mkv] > [[tt0062622][2001: A Space Odyssey (1968)]]
11:46am

MovieService
Linking [2001 A Space Odyssey (1968) [Bluray-1080p] [x265.AAC.2.0-Radarr].mkv] > [[tt0062622][2001: A Space Odyssey (1968)]]
11:46am

ParsingService
Unable to parse movie info from path /share/Public/2001 - A Space Odyssey 1968 (1080p Bluray x265 HEVC 10bit AAC 5.1 Tigole)/Featurettes/What is Out There.mkv
11:46am

ParsingService
Unable to parse movie info from path /share/Public/2001 - A Space Odyssey 1968 (1080p Bluray x265 HEVC 10bit AAC 5.1 Tigole)/Featurettes/Trailer.mkv
11:46am

ParsingService
Unable to parse movie info from path /share/Public/2001 - A Space Odyssey 1968 (1080p Bluray x265 HEVC 10bit AAC 5.1 Tigole)/Featurettes/Look - Stanley Kubrick.mkv
11:46am

ParsingService
Unable to parse movie info from path /share/Public/2001 - A Space Odyssey 1968 (1080p Bluray x265 HEVC 10bit AAC 5.1 Tigole)/Featurettes/FX and Early Conceptual Artwork.mkv
11:46am

ParsingService
Unable to parse movie info from path /share/Public/2001 - A Space Odyssey 1968 (1080p Bluray x265 HEVC 10bit AAC 5.1 Tigole)/Featurettes/A Look Behind the Future.mkv

**Comment by galli-leo** [comment]
I don't think there is much we can do. We could try looking at the path, but that's not going to be reliable. We check the runtime of the files usually, but they seem to be ok here. Also this seems like a very isolated case, since I haven't had a report else for this. So gonna put it on hold for now.

**Comment by Zero0Q** [comment]
Thank you for looking into that . I just wanted to let you know that error exist. If it can be fixed fine, otherwise leave it be. This seems to be the only movie affected so far. An oddity if anything.

**Comment by zductiv** [comment]
This is partially why I brought up #604 because of UTR releases which have sizable extras.
