### ISSUE TITLE
Unable to get free space for '/pathto/media/', unable to find suitable drive

### ISSUE THREAD

**Issue by philsynek** [Radarr/Radarr#1745]
**Description:**

Hi,
I am running Radarr on a freenas 11 and installed it like it's described [here](https://github.com/Radarr/Radarr/wiki/Installation#freebsd-jail). Unfortunately the adding of existing movies is not working. It says `No movies found in folder /media/filme/. Have you already added all of them?` and I see `Unable to get free space for '/media/filme/', unable to find suitable drive` in the debug logs. Radarr is running as root
`root  54300  0.0  0.7 245404 143904  -  SJ   16:13   0:06.01 /usr/local/bin/mono /usr/local/Radarr/Radarr.exe (mono-sgen)`
and the folder has 777 permissions:
`drwxrwxrwx   root  wheel   542B Jun 28 16:33 filme`

I already reinstalled the whole jail and radarr, but it didn't help.

**Radarr Version:** 0.2.0.778

**Logs:** https://pastebin.com/Pv6efMAn

Any help is highly appreciated!

Thanks,
Phil

**Comment by galli-leo** [comment]
What version of mono are you using?

**Comment by philsynek** [comment]
mono-4.8.1.0_1

**Comment by philsynek** [comment]
Are there any updates to this? It is preventing me from using radarr... :(

**Comment by galli-leo** [comment]
Sorry not really familiar with freenas. Can you try running radarr outside of a jail?

**Comment by philsynek** [comment]
I'll try to run it in a vm and report back!

**Comment by PnoT** [comment]
I just installed Radarr about a week ago using the guide above and customizing the rc script to my liking and it works great.  The error you mentioned is in my logs as well but there's nothing that doesn't work or any side effects because of it.  I'd check your permissions, the log file from Radarr, and the rc file and try to start the service.

**Comment by philsynek** [comment]
Yeah... I am sorry. This is resolved! I did not know, that my moviel folder has to contain every single movie file in an own folder... Changed this and it works now. Although I am running Radarr in a VM now.
