### ISSUE TITLE
Movie not being searched for with success

### ISSUE THREAD

**Issue by gregcbrown** [Radarr/Radarr#1746]
I added a movie about a week ago, "Whiplash". The movie came out in 2014. I noticed today that it hasn't been pulled yet. I looked back at the logs and it is part of each RSSsync but never gets pulled. I went to the movie and did a automatic scan and there were Tons of releases and it pulled one. What would cause movies not to be pulled during RSSsync if there are releases available and they fall within my quality group??

17-6-28 08:26:43.8|Info|DiskScanService|Scanning disk for Terry Fator: Live from Las Vegas
17-6-28 08:26:43.8|Info|DiskScanService|Completed scanning disk for Terry Fator: Live from Las Vegas
17-6-28 08:26:43.9|Info|RefreshMovieService|Updating Info for To Kill a Mockingbird
17-6-28 08:26:44.1|Info|DiskScanService|Scanning disk for To Kill a Mockingbird
17-6-28 08:26:44.7|Info|MovieService|Linking [To Kill a Mockingbird cd2.avi] > [[tt0056592][To Kill a Mockingbird (1962)]]
17-6-28 08:26:44.8|Info|MovieService|Linking [To Kill a Mockingbird cd2.avi] > [[tt0056592][To Kill a Mockingbird (1962)]]
17-6-28 08:26:44.8|Info|DiskScanService|Completed scanning disk for To Kill a Mockingbird
17-6-28 08:26:44.9|Info|RefreshMovieService|Updating Info for Top Gun
17-6-28 08:26:45.2|Info|DiskScanService|Scanning disk for Top Gun
17-6-28 08:26:45.2|Info|DiskScanService|Completed scanning disk for Top Gun
17-6-28 08:26:45.2|Info|RefreshMovieService|Updating Info for Transformers: The Last Knight
17-6-28 08:26:45.4|Info|DiskScanService|Scanning disk for Transformers: The Last Knight
17-6-28 08:26:45.5|Info|RefreshMovieService|Updating Info for Trolls
17-6-28 08:26:45.7|Info|DiskScanService|Scanning disk for Trolls
17-6-28 08:26:45.8|Info|DiskScanService|Completed scanning disk for Trolls
17-6-28 08:26:45.8|Info|RefreshMovieService|Updating Info for Underworld: Blood Wars
17-6-28 08:26:46.0|Info|DiskScanService|Scanning disk for Underworld: Blood Wars
17-6-28 08:26:46.0|Info|DiskScanService|Completed scanning disk for Underworld: Blood Wars
17-6-28 08:26:46.1|Info|RefreshMovieService|Updating Info for War for the Planet of the Apes
17-6-28 08:26:46.3|Info|DiskScanService|Scanning disk for War for the Planet of the Apes
**17-6-28 08:26:46.4|Info|RefreshMovieService|Updating Info for Whiplash
17-6-28 08:26:46.6|Info|DiskScanService|Scanning disk for Whiplash**
17-6-28 08:26:46.6|Info|RefreshMovieService|Updating Info for The Whole Truth
17-6-28 08:26:46.9|Info|DiskScanService|Scanning disk for The Whole Truth
17-6-28 08:26:46.9|Info|DiskScanService|Completed scanning disk for The Whole Truth
17-6-28 08:26:46.9|Info|RefreshMovieService|Updating Info for Why Him?
17-6-28 08:26:47.2|Info|DiskScanService|Scanning disk for Why Him?
17-6-28 08:26:47.2|Info|DiskScanService|Completed scanning disk for Why Him?
17-6-28 08:26:47.2|Info|RefreshMovieService|Updating Info for The Witness for the Prosecution
17-6-28 08:26:47.5|Info|DiskScanService|Scanning disk for The Witness for the Prosecution
17-6-28 08:26:47.5|Info|DiskScanService|Completed scanning disk for The Witness for the Prosecution
17-6-28 08:26:47.6|Info|RefreshMovieService|Updating Info for Wonder Woman
17-6-28 08:26:47.8|Info|DiskScanService|Scanning disk for Wonder Woman
17-6-28 08:26:47.9|Info|RefreshMovieService|Updating Info for xXx: Return of Xander Cage
17-6-28 08:26:48.2|Info|DiskScanService|Scanning disk for xXx: Return of Xander Cage
17-6-28 08:26:48.2|Info|DiskScanService|Completed scanning disk for xXx: Return of Xander Cage
17-6-28 08:35:20.3|Info|RssSyncService|Starting RSS Sync
17-6-28 08:35:25.1|Info|DownloadDecisionMaker|Processing 500 releases
17-6-28 08:36:06.4|Info|RssSyncService|RSS Sync Completed. Reports found: 500, Reports grabbed: 0
17-6-28 08:51:22.8|Info|RssSyncService|Starting RSS Sync
17-6-28 08:51:27.5|Info|DownloadDecisionMaker|Processing 500 releases
17-6-28 08:52:13.1|Info|RssSyncService|RSS Sync Completed. Reports found: 500, Reports grabbed: 0
17-6-28 09:07:24.9|Info|RssSyncService|Starting RSS Sync
17-6-28 09:07:29.7|Info|DownloadDecisionMaker|Processing 500 releases
17-6-28 09:08:23.5|Info|RssSyncService|RSS Sync Completed. Reports found: 500, Reports grabbed: 0
17-6-28 09:10:55.3|Info|NetImportSearchService|No lists are enabled for auto-import.
17-6-28 09:11:55.4|Info|PreDBService|Starting PreDB Sync
17-6-28 09:23:26.6|Info|RssSyncService|Starting RSS Sync
17-6-28 09:23:31.3|Info|DownloadDecisionMaker|Processing 500 releases
17-6-28 09:24:14.3|Info|RssSyncService|RSS Sync Completed. Reports found: 500, Reports grabbed: 0
17-6-28 09:39:27.7|Info|RssSyncService|Starting RSS Sync
17-6-28 09:39:32.4|Info|DownloadDecisionMaker|Processing 500 releases
17-6-28 09:40:17.9|Info|RssSyncService|RSS Sync Completed. Reports found: 500, Reports grabbed: 0
17-6-28 09:55:28.7|Info|RssSyncService|Starting RSS Sync
17-6-28 09:55:33.4|Info|DownloadDecisionMaker|Processing 500 releases
17-6-28 09:56:16.8|Info|RssSyncService|RSS Sync Completed. Reports found: 500, Reports grabbed: 0
17-6-28 10:09:23.4|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Either 'Must contain' or 'Must not contain' is required
17-6-28 10:11:00.5|Info|NetImportSearchService|No lists are enabled for auto-import.
17-6-28 10:11:30.5|Info|RssSyncService|Starting RSS Sync
17-6-28 10:11:35.3|Info|DownloadDecisionMaker|Processing 500 releases
17-6-28 10:12:00.6|Info|PreDBService|Starting PreDB Sync
**17-6-28 10:12:16.1|Info|NzbSearchService|Searching 5 indexers for [Whiplash]
17-6-28 10:12:18.9|Info|DownloadDecisionMaker|Processing 190 releases
17-6-28 10:12:20.6|Info|RssSyncService|RSS Sync Completed. Reports found: 500, Reports grabbed: 0
17-6-28 10:13:09.2|Info|RefreshMovieService|Updating Info for Whiplash
17-6-28 10:13:09.5|Info|DiskScanService|Scanning disk for Whiplash
17-6-28 10:13:13.8|Info|NzbSearchService|Searching 5 indexers for [Whiplash]
17-6-28 10:13:16.9|Info|DownloadDecisionMaker|Processing 190 releases
17-6-28 10:13:29.5|Info|Sabnzbd|Adding report [Whiplash.2014.1080p.BluRay.DTS.x264-HDAccess] to the queue.
17-6-28 10:13:32.0|Info|DownloadService|Report sent to SABNZBD. Whiplash.2014.1080p.BluRay.DTS.x264-HDAccess
17-6-28 10:13:32.3|Info|MovieSearchService|Movie search completed. 1 reports downloaded.**

**Comment by galli-leo** [comment]
Because the releases aren't actually in the RSS Sync. RSS Sync only includes the latest 100 releases from your indexer. And Whiplash's releases are all prolly over that. This is why I suggest always adding movies with add and search.
