### ISSUE TITLE
Indexers not functioning after RSS sync interval change

### ISSUE THREAD

**Issue by ericreinsmidt** [Radarr/Radarr#1748]
**Description:**

I changed the RSS sync interval from 60 to 10, and as soon as I saved the changes I got two warnings and one error:

<img width="651" alt="screen shot 2017-06-28 at 3 24 07 pm" src="https://user-images.githubusercontent.com/735251/27656154-f66ef66c-5c15-11e7-9d7a-7e707ce0bd91.png">

After that happened I cannot add a new indexer (custom NewzNab). In addition, if I look at the settings for my current indexers, after about a second the values for Name, URL, and API Key all change from the values I entered to the default values, i.e. NZBGet, localhost, and 6789 respectively.

I've tried a restart and the problem persists. This reminds of the issue with using newer versions of Mono, although I am using the current preferred version as far as I know, version info below.

**Radarr Version:**
0.2.0.778

**Mono Version**
4.2.4 (explicit/71b88f3 Thu May 5 17:25:51 EDT 2016)

**Logs:**
17-6-28 15:14:05.0|Info|RssSyncService|Starting RSS Sync
17-6-28 15:14:05.1|Warn|FetchAndParseRssService|No available indexers. check your configuration.
17-6-28 15:14:05.1|Info|DownloadDecisionMaker|No results found
17-6-28 15:14:05.1|Info|RssSyncService|RSS Sync Completed. Reports found: 0, Reports grabbed: 0
17-6-28 15:24:09.0|Info|RssSyncService|Starting RSS Sync
17-6-28 15:24:09.0|Warn|FetchAndParseRssService|No available indexers. check your configuration.
17-6-28 15:24:09.0|Info|DownloadDecisionMaker|No results found
17-6-28 15:24:09.0|Info|RssSyncService|RSS Sync Completed. Reports found: 0, Reports grabbed: 0

**Comment by galli-leo** [comment]
Well, that mono version seems very outdated. Currently IMO 4.8 is preferred. Anyways, it states that your indexers are unavailable due to failures, meaning they have failed searching for your movies, thus were disabled. What happens when you test them? Also the change of values in the indexer settings is probably related to your browser autocompleting stuff. Can you try Radarr in an incognito window?

**Comment by ericreinsmidt** [comment]
I bumped up to 4.8, and also had to use a different browser than chrome to resave my indexers. It was indeed an autocomplete issue. Thanks for the suggestions. I'm guessing it changed the values in the hidden fields for the indexers when I altered the RSS sync interval and when I saved, it saved those hidden values.
