### ISSUE TITLE
Make search tab default 

### ISSUE THREAD

**Issue by evulhotdog** [Radarr/Radarr#175]
I believe the "Search" tab should be the default when the movie page is opened. I'm not sure how relevant history, unless you are explicitly looking for that information. 

![image](https://cloud.githubusercontent.com/assets/365456/21871000/6b640ccc-d82d-11e6-8c33-8921ecfe70d8.png)

**Comment by fryfrog** [comment]
I'd prefer it default to a list of files in the directory, with History and Search as places you go after.

I think the problem w/ that is that every page load of a movie would trigger a search.

**Comment by ShanDestromp** [comment]
I agree with @fryfrog; having search the default would hammer my indexers anytime I was poking around my movies.

**Comment by evulhotdog** [comment]
I agree with @fryfrog as well, thinking about all the api calls. 

I just feel like there is all that usable space there that can be put to good use, instead of the history, which users would rarely want to view.

**Comment by teshiburu** [comment]
What about a "media info" report for the file in question if one is present?

**Comment by galli-leo** [comment]
@teshiburu That sounds like a good addition. Maybe a list of files with MediaInfo on every one of them. Can you make a seperate issue?
