### ISSUE TITLE
Deleting a movie does not delete files

### ISSUE THREAD

**Issue by pven** [Radarr/Radarr#1750]
When I delete a movie and slide 'Delete all files' to 'Yes' the files are not deleted. However: when a better quality for a existing movie is found, it will delete the old movie.

**Radarr Version:**
Latest

**Logs:**
(not sure if sufficient, I don't see more related log)

```
17-6-29 10:33:38.7|Trace|Http|Res: 2027 [DELETE] /api/movie/33?deleteFiles=true&addExclusion=false: 200.OK (524 ms)
17-6-29 10:33:38.7|Debug|Api|[DELETE] /api/movie/33?deleteFiles=true&addExclusion=false: 200.OK (524 ms)
17-6-29 10:33:38.8|Trace|EventAggregator|MovieDeletedEvent <~ MediaFileService
17-6-29 10:33:38.9|Trace|EventAggregator|MovieDeletedEvent <~ BlacklistService
```

**Comment by galli-leo** [comment]
Yeah, did not yet have time to implement that. But there is an issue already open for that, so closing this one.

**Comment by pven** [comment]
Ok ,thanks :)
