### ISSUE TITLE
Information Popup or Textbox on first visiting "Add Movies"

### ISSUE THREAD

**Issue by Wyall** [Radarr/Radarr#1754]
I'd like to propose something like a information popup or a dismissable textbox shown on the first visit of the "Add movies" page. Maybe but an "Understood" button at the bottom and make it disappear after clicking.

"Once you 'add' (+Sign here) a movie to radarr with monitoring enabled, radarr will check all **future** releases on your indexers for that movie and download a release once all conditions are met. The 'add and Search for movie' button triggers an immediate search for the movie on your indexers, including **older**, already existing releases. After that, radarr will check new releases once they appear on your indexer"

One could also think about adding something like this somewhere on the Indexer page, explaining the difference between rss (new releases) vs. search (already exisiting).

**Comment by onedr0p** [comment]
Not sure what benefit this would add. Adding movies in v3 looks a lot better...
