### ISSUE TITLE
Trakt list import: There Was An Error Searching For ''.

### ISSUE THREAD

**Issue by Qwatuz** [Radarr/Radarr#1756]
**Description:**

I am trying to import a user list from Trakt and I receive this error:

There Was An Error Searching For ''.
If the movie title contains non-alphanumeric characters try removing them, otherwise try your search again later.

Screenshot of the list settings: http://i.imgur.com/mDvjscl.png

I can successfully import lists that are ~200 movies - is there a limit to how many can be on the list?

**Radarr Version:**

Version 0.2.0.696
Mono Version 5.0.1.1 (2017-02/5077205 Thu May 25 09:16:53 UTC 2017)

**Logs:**

https://pastebin.com/ushUX8sL

**Comment by galli-leo** [comment]
Did you already add all of the movies on these lists?

**Comment by Qwatuz** [comment]
@galli-leo nope, there are over 800 movies more in the list than my library. This strange error is happening to a few people i've had try add a huge list.

This is the list i've been trying (as well as others): https://trakt.tv/users/necrul/lists/all-u-s-released-movies-1972-2016-593a64b5-ebdd-4414-bd08-59d6cf9d3836 - 9652 movies.

**Comment by galli-leo** [comment]
The link to the list would be good.

**Comment by SlothCroissant** [comment]
https://trakt.tv/users/slothcroissant/watchlist

**Comment by galli-leo** [comment]
Could it be that you have already added all of them to your library? That "error" will appear if you have that.

**Comment by galli-leo** [comment]
@Qwatuz I am thinking your list is simply too large and causes a request timeout. Can you open chrome dev console, retry the list and then look out for red errors?

**Comment by SCCAP53** [comment]
I have the latest issue and this is still an issue

**Comment by Stephonomon** [comment]
I have the latest version and this is still an issue

**Comment by rsoutar** [comment]
Try increase your limit in Radarr > settings > List > Trakt
