### ISSUE TITLE
[Request] Tagged Restrictions override Non-tagged (ie default) Restrictions. 

### ISSUE THREAD

**Issue by desimaniac** [Radarr/Radarr#1757]
#### Description:
For example, I have a Restriction, with no tags, that restricts 3D. As I want the default for all movies to not be 3D. 

Then I have a restriction that has a tag "3D" that must contain 3D.

I'd assume that the tagged restriction would override the non-default (ie non-tagged) one. But when I label a movie with the "3D" tag, the searches show that both movie titles with 3D and without 3D are being ignored.

**Comment by Qstick** [comment]
Closing, this is how releases work.
