### ISSUE TITLE
Ignore punctuation when determining whether a movie is marked "downloaded" or "missing"

### ISSUE THREAD

**Issue by Grace1313** [Radarr/Radarr#1758]
When you have a movie in your library, but it isn't named exactly as the one in Radarr, the movie shows as "missing".
Example: Let's Be Cops   -   Lets Be Cops
Would be nice if the apostrophe was ignored.

**Comment by galli-leo** [comment]
Can you post the full filename? We are already doing that.

**Comment by Grace1313** [comment]
Radarr had it listed as Let's Be CopsOn my computer it was E:\ Movies\ Lets Be Cops\ Lets Be Cops.mkv




On Sunday, July 2, 2017, 5:46 AM, Leonardo Galli <notifications@github.com> wrote:


Can you post the full filename? We are already doing that.

**Comment by galli-leo** [comment]
Ah. The problem is that currently Radarr needs a year in either the folder or filename for it to be recognised. There is an issue already open for this though.
