### ISSUE TITLE
Movies being set to unmonitored unexpectedly. 

### ISSUE THREAD

**Issue by pummra** [Radarr/Radarr#1759]
**Description:**
I have set up Radaar to have a cut-off of 1080p-Remux. I would expect movies to become 'unmonitored' once that profile has been downloaded. However I often find movies which haven't hit that profile yet marked as unmonitored. 

Example I have just updated two items in my list one was 1080p-BluRay and the other was DVD. 

I think this may occur when I specifically choose an item to download from a manual search or when I refresh the item after updating the filename or similar on disk. 

**Radarr Version:**
0.2.0.778

**Comment by galli-leo** [comment]
Items do not become unmonitored after the cutoff is met. Seems like something else is changing the monitored status. Might it be the browser autofilling that field? Also might those movies be on a list or something?

**Comment by hugolapointe** [comment]
Same thing happen to me. I check, this is not the browsser autofilling.

**Comment by pummra** [comment]
I had this happen to me yesterday. 

I had to change the folder path for one of my movies as it had been renamed. After I pointed Radaar at the new location and updated the movie was set to be unmonitored.
