### ISSUE TITLE
Including media source as a renaming option

### ISSUE THREAD

**Issue by pummra** [Radarr/Radarr#1760]
**Description:**
This is a feature request. Would it be possible to include source as a renaming option? For example I would like the following renaming pattern: 

Remuxes:
Movie Title (Release Year) Remux-1080p BluRay

Non-Remuxes:
Movie Title (Release Year) 1080p BluRay

I use TinyMediaManager to help manage my media and it would be useful to include BluRay in the filename for both remuxes and non-remuxes so it can detect the source.

**Comment by galli-leo** [comment]
You can just rename the Remux-1080p quality to something like Remux-1080p / Bluray or something to achieve the same effect.

**Comment by pummra** [comment]
Didn't realise I could do that. Sorry!
