### ISSUE TITLE
What library/binary is used to create the releases packages

### ISSUE THREAD

**Issue by aonez** [Radarr/Radarr#1762]
Just referencing to #745 and https://github.com/aonez/Keka/issues/2#issuecomment-312139985, p7zip is not retaining the execute bit on this project releases (at least on Unix).

Just wanted to know if you can tell me what library/binary is used to create those releases (only zip archives). This one [https://gith...8/Radarr.develop.0.2.0.778.osx-app.zip](https://github.com/Radarr/Radarr/releases/download/v0.2.0.778/Radarr.develop.0.2.0.778.osx-app.zip) I've checked reproduces the issue.

Thanks a lot for your time!

**Comment by galli-leo** [comment]
We are using cake to create the zip file (build script is located at root and called build-appveyor.cake) and I am pretty sure that it's actually not retaining the execute bit. If you take a look at the latest comment on this #745, it seems that the default osx file utility actually adds that bit to all files, so prolly not your fault, but actually ours :/

Nevertheless, maybe you could add this functionality to keka to mimic the default behaviour?
