### ISSUE TITLE
Network drives not showing

### ISSUE THREAD

**Issue by Transcend01** [Radarr/Radarr#1763]
In Sonarr. Network drives show, no problems there. In Radarr network drives do not show. 

O.S.  Windows 10. Running as a service.

This should work out of the box, as it did with Sonarr.

**Comment by galli-leo** [comment]
Try one of these things:
1. Not running Radarr as a service (put a link in the startup folder, if desired)
2. Change the account the Radarr service is run under to the one with the correct permissions to the drive
3. Change the permissions of the network drive, so that the Radarr service account has access.

**Comment by Transcend01** [comment]
Running Radarr.exe does not give network drives. So i have disabled the service. Start Radarr.exe no network drives. Sonarr does see the network drive.

**Comment by galli-leo** [comment]
Try running it as admin or giving the network drive permissions for everyone

**Comment by Transcend01** [comment]
The drive does not show in System, Status, Disk space. But i can add the drive. So my problem is no longer there. But it is strange the drive does not show in Disk space.

**Comment by facted** [comment]
I have the same issue. Running as console. The folders work, but it's not shown in disk space.

**Comment by Canberra2005** [comment]
Hello,
I seem to have the same problem:
I am running WIN 10 and my movies are on a network QNAP NAS.
The path I am putting in is:
\\qnap-koorong\multimedia\video\movies

I keep getting the same error message: path does not exist

Any ideas?

**Comment by ianfriend** [comment]
Running the service as my local user seemed to fix this for me.  Still doesnt show up under in the drives list but at least it would recognise the network path i.e. \\location\

**Comment by galli-leo** [comment]
IIRC Windows doesn't give use networked drives back, when we ask for all mountpoints, so not much we can do.

**Comment by Canberra2005** [comment]
Thanks for the help...
i am running as an administrator but it still will not recgognise any path name. what am I doing wrong.
drivrs are mapped

**Comment by galli-leo** [comment]
Try not running Radarr as admin, but by just double clicking the exe. Also try using UNC paths \\\\Share\\\\Server or whatever

**Comment by Canberra2005** [comment]
thank you all fr the help, I appreciate it.
but it is still not working. 
should bu UNC path look like this:
\qnap-koorong\multimedia\video\movies
for QNAP with one data Volume?
I have tried Z:\ and \\QNAP-KOOROOG\ Etc
All with no joy. i think i am doing something wrong any other good ideas?

**Comment by galli-leo** [comment]
@Canberra2005 Have you tried shutting radarr down, then just double clicking the exe?

**Comment by Canberra2005** [comment]
Hi,

I did get it to work. But about a week ago all the network drives has disappeared?
Very strange.

**Comment by Canberra2005** [comment]
Yes I have done all the suggestions. It did work for abour a week, now I can not find them. Very frustrating.

**Comment by galli-leo** [comment]
@Canberra2005 Are you sure Radarr is not running as a service again? And have the drives just disappeared from System -> Status or can you also not add new movies with folders there?

**Comment by nnicolao** [comment]
To resolve the issue go to **Services** and find the **Radarr service**. Right click and select **Properties**. Go to **Log On** and select **This Account** and manually insert the Local Username and Password that are also assigned to your NAS credentials.
