### ISSUE TITLE
Prevent BDMV downloading

### ISSUE THREAD

**Issue by Cam-Corp** [Radarr/Radarr#1764]
Hey Everyone,
Is there anyway to get Radarr to Exclude BDMV downloads from its list. I know I can turn them into a MKV file but its just an extra step.

Radarr Version: 0.2.0.779

Thanks, 
C

**Comment by galli-leo** [comment]
Not possible, since we only know the files after downloading. I would look into your dl client doing that. usually they can cancel / fail a download pretty immediately when they see blacklisted file types.
