### ISSUE TITLE
Minor correction: {Movie CleanTitle} replaces ampersand ('&') to 'And' instead of 'and'

### ISSUE THREAD

**Issue by desimaniac** [Radarr/Radarr#1767]
Can we have `&` replaced by lowercase `and`, instead of `And`? Lowercase 'and' is the style TMDB uses for movies (e.g. [Beauty and the Beast](https://www.themoviedb.org/movie/321612-beauty-and-the-beast)).

Thanks.

---

Radarr Ver. 0.2.0.778

**Comment by desimaniac** [comment]
Thanks

**Comment by desimaniac** [comment]
@galli-leo Can we also look to remove `!` and convert `@` to `at` ?. Thanks.

**Comment by galli-leo** [comment]
@desimaniac Sure thing.

**Comment by desimaniac** [comment]
One more I found :p ---> `Romeo + Juliet (1996)` stays the same with clean title tag.

**Comment by desimaniac** [comment]
Also can we remove accented letters as well? 

For example, `Déjà Vu (2006)`. This is how it looks in linux over sftp: ![image](https://user-images.githubusercontent.com/5501908/29499219-1219cd7a-85d2-11e7-8157-77d33d08f349.png)

**Comment by galli-leo** [comment]
@desimaniac Are you sure that's not your sftp program guessing the encoding wrong? IIRC accents worked for me. Anyways, I thought clean title did that, I will have to check.

**Comment by desimaniac** [comment]
I agree, the sftp program was showing it that way, but within Ubuntu the accents were there; it was still `Déjà Vu (2006)`. I had to manually rename it to `Deja Vu`.

**Comment by desimaniac** [comment]
Still an issue. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by desimaniac** [comment]
Does this still need to be open ?
