### ISSUE TITLE
Cannot connect to radarr UI using SSL

### ISSUE THREAD

**Issue by n1nj4888** [Radarr/Radarr#1768]
I can connect to the radarr web UI using normal HTTP without issue but, after clicking "Use SSL" in the web UI and restarting the radarr server, the web UI is no longer accessible until changed back to HTTP through the radarr config file?

I'd normally expect options to specify, if SSL, what's the path to the ssl certificates but there appears to be no such options so not sure where to place the SSL certificates (or what to name them)?

**Comment by n1nj4888** [comment]
For extra information, I'm running radarr 0.2.0.696 (served via linuxserver-io docker container on Synology NAS)

**Comment by galli-leo** [comment]
See https://github.com/Sonarr/Sonarr/wiki/SSL#linux--os-x for how to setup SSL with Sonarr (or here Radarr). Seems like you need to do a lot of stuff to get it to work on linux. I would recommend just using a reverse proxy.
