### ISSUE TITLE
Icons do not populate for MatterMost (Slack)

### ISSUE THREAD

**Issue by seanvree** [Radarr/Radarr#1769]
**Description:**

Icons do not populate when sending to notifications to MatterMost (Local Slack server)

**Radarr Version:**
Radarr v 0.2.0.778 - Develop
OS:  Windows 10E x64 1703
Python 2.7

**Logs:**

No errors in logs for Radarr or MatterMost

**Background**

I moved to MatterMost from slack, and the icons no longer work for Radarr, Sonarr, Plexpy, etc all work.   (See screenshot)

I've also tried emojjis and those don't work either.  

![picture1](https://user-images.githubusercontent.com/8906637/27904907-20602008-61f3-11e7-9b27-0f5b1625d46c.png)

**Comment by jamesmacwhite** [comment]
@seanvree Sonarr made some improvements to this in July. I have ported over the changes to Radarr, but would like them tested. Are you in a position to be able to test the code changes at all, if this is something you are comfortable with?

If not I can test vanilla Slack easily enough, but would have to setup a local Mattermost instance in VM, as I don't use it.

**Comment by jamesmacwhite** [comment]
I've done basic testing with Slack and confirmed both emoji and absolute image URL paths work. If OP or anyone in the community wants to test Mattermost, please report!

**Comment by seanvree** [comment]
Works!

![image](https://user-images.githubusercontent.com/8906637/29253364-4734c530-802f-11e7-8b4a-c8b986fc573b.png)

**Comment by seanvree** [comment]
@jamesmacwhite  - minor follow up question. If I "upgrade" to Nightly, and then "downgrade" to develop, do I loose all the code changes? I thought I somewhere it won't revert.

**Comment by jamesmacwhite** [comment]
@seanvree  If you downgrade you'll lose the code fixes.

You can change the branch back to the develop while having the current nightly build installed. Essentially you'll then be ahead of latest develop and hence the updater won't let you downgrade through the Web UI. Once a new release from `develop` is pushed, Radarr will update as normal.

**Comment by seanvree** [comment]
okay, got it. thx
