### ISSUE TITLE
Quality (resolution) doesn't match media info

### ISSUE THREAD

**Issue by Redundant1** [Radarr/Radarr#1772]
**Description:**

I've noticed that Radarr seems to take the filename quality as gospel, disregarding the media info Radarr parses.  For example, I have a file which Radarr grabbed and marked as "Bluray-1080p", which matches what the filename shows as "1080p.BluRay". However, the media info in Radarr itself shows the actual resolution as 1918x1040, which matches reality.

In this situation, my preference would be for Radarr to label the file as "Bluray-720p", since 1040 doesn't meet the 1080 requirement. This should cause Radarr to continue trying to obtain higher quality/resolution versions.

Similarly, I'd also suggest that if the resolution of this file were actually 1918x1080 or 1920x1040, that the file still be marked as "Bluray-720p", since neither of those meet the full requirements for 1080p either.

**Radarr Version:**
0.2.0.778

**Comment by galli-leo** [comment]
Most 1080p releases I have seen are not full 1920x1080 releases (mostly because no black bars). So not gonna "downgrade" those releases. Also for the one with a few pixels "missing". Not gonna downgrade either, since those are considered 1080p by most people.

**Comment by Redundant1** [comment]
I understand that reasoning for 1080p, but would you consider doing so just for BR-DISK qualities? I'd think people who are going through the trouble of downloading the largest files out there are actually wanting the most complete version available; I know that's why I do. Otherwise, I'd stop at Bluray-1080p.

**Comment by galli-leo** [comment]
A BR-DISK is a full disk rip. So That's the max resolution you are gonna get.

**Comment by Redundant1** [comment]
LOL! If only that were true. I regularly get supposed BR-DISKs with cropped video. Files flagged as BR-DISKs are often in MKV format, which I've found to be regularly edited from the original. I have yet to see an ISO be edited, but I don't often wind up with those. I have yet to see Radarr grab a BR-DISK in the day or so I've been running it, so we'll see what happens.
