### ISSUE TITLE
Backslash character in result set breaks succeeding search results.

### ISSUE THREAD

**Issue by YipYup** [Radarr/Radarr#1774]
**Description:** When doing a manual search for a title, and the result set has a character such as a backslash in it, the actionable "Send-to Downloader" icon will not appear for succeeding results.

**Radarr Version:** 0.2.0.778
**Mono Version:** 4.2.3 (Stable 4.2.3.4/832de4b Wed Mar 16 13:19:08 UTC 2016)
**AppData directory:**/home/radarr/.config/Radarr
**Startup directory:** /opt/Radarr
**Distro:** Ubuntu Server 16.04 LTS x86-64

**Logs:**
- [radarr.txt](https://github.com/Radarr/Radarr/files/1132661/radarr.txt)
- [radarr.debug.txt](https://github.com/Radarr/Radarr/files/1132662/radarr.debug.txt)
- [radarr.trace.txt](https://github.com/Radarr/Radarr/files/1132664/radarr.trace.txt)

![slash_download_missing](https://user-images.githubusercontent.com/1251419/27981578-399c5074-634b-11e7-9198-d6f09b8aba13.jpg)

**Comment by galli-leo** [comment]
Are you sure that's the issue? What do the rejections say? (red exclamation mark)
