### ISSUE TITLE
Profile cutoff quality not being enforced

### ISSUE THREAD

**Issue by rschmetzer** [Radarr/Radarr#1775]
I have a profile defined with most hi-def qualities included and specifying BluRay-720 as the cutoff.  When adding a new movie that has all qualities available, Radarr selects the BluRay 1080p version.

**Radarr Version:**  0.2.0.778

**Comment by galli-leo** [comment]
Yeah, Radarr will always choose the highest quality available. Profile cutoff means, when this quality is reached Radarr will stop automatically upgrading the qualities.

**Comment by galli-leo** [comment]
You prolly want to reorder qualities to have Bluray-720p on top.

**Comment by rschmetzer** [comment]
Will do.  Just checked Sonarr config and I already had the 720 above the
1080.  No wonder it worked the way I expected. :)
