### ISSUE TITLE
Show genre on list and discovery pages

### ISSUE THREAD

**Issue by wifiuk** [Radarr/Radarr#1776]
**Description:**
At the moment you have , FILMNAME (2017) [Released] [6.2] [Trailer]
I propose to have FILMNAME (2017) **[FILM GENRE]** [Released] [6.2] [Trailer]

**Radarr Version:**
_0.2.0.778_

**Comment by galli-leo** [comment]
Well first we would have to store the genres, but thats something I plan on adding.

**Comment by wifiuk** [comment]
Ok cool. I think it would be handy when looking for a new film...
