### ISSUE TITLE
[Bug] 1080p downloads are categorized as 720p

### ISSUE THREAD

**Issue by kappaknight** [Radarr/Radarr#1779]
**Description:**

1080p downloads are constantly being recategorized as 720p, resulting in multiple attempts/downloads of the same file over and over again.

Radarr either needs to do a better job of categorizing the media metadata correctly, or blacklist the files it has already downloaded in the past (regardless of success or failure) so that it does not repeatedly download the same file 50+ times.

**Radarr Version:**

0.2.0.778

**Logs:**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by nemchik** [comment]
I've had this happen on Sonarr a lot lately.

**Comment by hotio** [comment]
And I can take a look at all the logs where exactly?

**Comment by galli-leo** [comment]
Could you provide us with some examples? Without that we won't be able to fix this issue.

**Comment by nemchik** [comment]
http://imgur.com/a/V42ks

I know logs are more helpful, but I'm not even sure where this would be in my logs. If I turn on trace and rescan disk will that tell us anything?

**Comment by hotio** [comment]
Unless you provide some log files that contain the reason for why Radarr thinks it's a HDTV-720p, this issue isn't going anywhere.

How lovely those Plex screenshot images are, they are kinda useless, since this isn't Plex.

**Comment by kappaknight** [comment]
How do I pull the logs? This is what's happening all day everyday on mine.

<img width="1138" alt="screenshot 2017-07-17 22 56 24" src="https://user-images.githubusercontent.com/1387666/28298805-602991f2-6b43-11e7-8587-7fec1dc66df2.png">

**Comment by hotio** [comment]
Could you show the history overview for the movie itsself and offcourse the log.

**Comment by kappaknight** [comment]
I'm not sure what the logs mean... but here is the section with the timestamp:

<img width="984" alt="screenshot 2017-07-18 07 12 53" src="https://user-images.githubusercontent.com/1387666/28315780-025a2dd4-6b8e-11e7-8023-8dcf268f5ebf.png">
<img width="991" alt="screenshot 2017-07-18 07 13 46" src="https://user-images.githubusercontent.com/1387666/28315781-040dbc54-6b8e-11e7-90d8-9b69451d19fa.png">

                               !C2017-07-12 05:33:07.812753Z)k
!C2017-07-12 05:33:07.833351Z)k!C2017-07-12 05:33:07.845258Z)k!C2017-07-12 05:33:08.175224Z)k!C2017-07-12 05:33:08.183705Z)k!C2017-07-12 05:33:08.194955Z)k!C2017-07-12 05:33:08.747526Z)k A2017-07-12 05:33:08.94729Z)k!C2017-07-12 05:33:08.993787Z)k!C2017-07-12 05:33:09.034442Z)k!C2017-07-12 05:33:09.075655Z)k!C2017-07-12 05:33:09.681795Z)k!C2017-07-12 05:33:36.503394Z)k!C2017-07-12 05:33:36.580055Z)k!C2017-07-12 05:33:36.595612Z)kC2017-07-12 05:33:36.644368Z)k A2017-07-12 05:33:36.68274Z)k!C2017-07-12 05:33:36.722446Z)k!C2017-07-12 05:33:36.765049Z)k!C2017-07-12 05:33:36.781274Z)k !C2017-07-12 05:33:36.789995Z)k!!C2017-07-12 05:33:36.805434Z)k"!C2017-07-12 05:33:36.851397Z)k#!C2017-07-12 05:33:36.864634Z)k$
JJl????8Z{???$Fh????4Vx???!C2017-07-12 05:33:37.791791Z)k&!C2017-07-12 05:33:37.804347Z)k'!C2017-07-12 05:33:37.837598Z)k(!C2017-07-12 05:33:37.853157Z)k)!C2017-07-12 05:33:37.862051Z)k*!C2017-07-12 05:33:37.870881Z)k+!C2017-07-12 05:33:37.880316Z)k,!C2017-07-12 05:33:37.894662Z)k- A2017-07-12 05:33:37.90513Z)k. A2017-07-12 05:33:38.28539Z)k/!C2017-07-12 05:33:38.298852Z)k0!C2017-07-12 05:33:38.307891Z)k1!C2017-07-12 05:33:38.913835Z)k2!C2017-07-12 05:33:39.142718Z)k3!C2017-07-12 05:33:39.185728Z)k4!C2017-07-12 05:33:39.234413Z)k5!C2017-07-12 05:33:39.281458Z)k6!C2017-07-12 05:34:03.132125Z)k7!C2017-07-12 05:34:03.445606Z)k8!C2017-07-12 05:34:03.457433Z)k9!C2017-07-12 05:34:06.517717Z)k:!C2017-07-12 05:34:06.583379Z)k;!C2017-07-12 05:34:06.594883Z)k<!C2017-07-12 05:34:06.643785Z)k=!C2017-07-12 05:34:06.677827Z)k>!C2017-07-12 05:34:06.715703Z)k?!C2017-07-12 05:34:06.757036Z)k@!C2017-07-12 05:34:06.772249Z)kA

**Comment by nemchik** [comment]
Ok, I DO know what logs are, and how to turn on trace and I'll send them in, no problem. What I need to know is how can I force Sonarr to re-detect the quality? (I have this issue with Sonarr, haven't noticed it in Radarr yet).

Can I rescan disk for those files? Do I have to remove them from their folder and reimport? 

When does quality detection happen?

**Comment by kappaknight** [comment]
Interesting... I don't think I'm seeing this issue in Sonarr at all, granted I haven't really dived into the logs to make sure. However, I am noticing a pattern. 

In Radarr, I decided to include the quality of the release into the renaming job - and I'm wondering if that may be triggering some job with an outdated mediainfo parser. I think I still had this issue even when I didn't include the quality in the filename, but not sure if it's part of the problem since I believe it was on by default.

I'm not doing this in Sonarr, but I noticed the person above with the screenshot is for his TV collection.

**Comment by nemchik** [comment]
I have quality included in the file names, and the names in the files seem to match the quality sonarr determines about the files (does not match the quality plex sees). I really don't think the file names has much to do with the detection of media quality, but I could be wrong. mediainfo might be a more believable culprit here, but I don't know how to determine that. If someone tells me what to look for I'll grab logs in a heartbeat.

**Comment by hotio** [comment]
It seems that upgrading is failing because Radarr has no write permission to delete the olde file and move the new file. So obviously it will keep downloading and trying again and again.

@nemchik What is the point of barging in on @kappaknight his issue talking about Sonarr? Incredibly rude if you ask me.

**Comment by nemchik** [comment]
The issue seems to be the same to me. Sonarr and Radarr are very similar. I definitely don't have a permissions issue, but I was hoping that if someone else was tracking the same issue that exists in both Sonarr and Radarr then I could help provide logs and get the issue resolved.

**Comment by hotio** [comment]
They've got plenty of support channels of their own: https://sonarr.tv/#support

**Comment by galli-leo** [comment]
@kappaknight Can you post the filename before it is moved & renamed by radarr. E.g. by looking at your dl client? Without that, I won't be able to help much. Also what is the actual resolution of the downloaded file?
