### ISSUE TITLE
QueueService failed while processing [TrackedDownloadRefreshedEvent]

### ISSUE THREAD

**Issue by zerrikan** [Radarr/Radarr#178]
Downloaded some movies. Was getting the No files found are eligible for import in <download_folder> error (159) Noticed there was an update available so I updated. After a restart I dont see that error anymore but my movies have disappeared from the Activity area and the logs are showing this.

QueueService failed while processing [TrackedDownloadRefreshedEvent]: Object reference not set to an instance of an object

[sonarr.txt](https://github.com/Radarr/Radarr/files/700406/sonarr.txt)

Currently on 0.2.0.85

**Comment by zerrikan** [comment]
Ok so now that error is gone and I see the movies back in Activity but still get the No files found are eligible for import in <download_folder> error. Not sure if I should close this or not.

**Comment by galli-leo** [comment]
Keep it open, I am currently investigating this.
