### ISSUE TITLE
[Feature Request] Faster move process (Ubuntu)

### ISSUE THREAD

**Issue by desimaniac** [Radarr/Radarr#1781]
It seems as if it is copying the file over then deleting it vs just moving the file, which takes quite a long time for large movie files, especially when you have other tasks lined up. 

Radarr Ver. 0.2.0.778

**Comment by galli-leo** [comment]
Is this on the same drive?

**Comment by desimaniac** [comment]
It is the same drive. But I think I had a recycle_bin turned on and that was going to another drive as like a backup you can say. I think that was slowing it down. 

But to clarify, same drive transfers are instantaneous?

**Comment by galli-leo** [comment]
Should be if Radarr tried moving the file (only usenet)

**Comment by desimaniac** [comment]
Ok. I guess this isnt an issue then. Thanks!

**Comment by desimaniac** [comment]
To update on this issue: it was still occurring with recycle bin off. Finally realized it was because I had soft-raid enabled on the server and it was probably moving it across drives which is why it wasn't instant.
