### ISSUE TITLE
Radarr picks up Trailer file instead of the actual Movies.

### ISSUE THREAD

**Issue by kelemvor33** [Radarr/Radarr#1784]
**Description:**
Not sure if this is technically a bug but I've heard of other people having the issue.  Some of my movie folders have the main movie file and a second file containing the trailer for the movie.
E.g.  Avatar.mkv and Avatar-trailer.flv

Radarr is picking up the Trailer file as the movie file instead of the actual movie file.  (See screenshot)

Simple fix might be to have an option to Ignore files that end with "trailer" in the name or something like that.

**Radarr Version:**
0.2.0.778

Thanks.

![radarr trailer](https://user-images.githubusercontent.com/4562045/28099351-a466b988-6681-11e7-9dba-ce009bc2f2b7.jpg)

**Comment by galli-leo** [comment]
Try importing a few of them. Bulk import is not that sophisticated when choosing the files to display. It will work correctly afterwards.

**Comment by kelemvor33** [comment]
Ah ok, thanks.  I imported some but it showed the Trailer as the movie file.  I then did an Update Library and then it found the proper file.  I'll keep an eye on it.
