### ISSUE TITLE
Bulk Import Issue on new install

### ISSUE THREAD

**Issue by TitanArchon** [Radarr/Radarr#1785]
Trying to import my library using Bulk Import and running into some weird behavior. The importer finds the movies, matches them perfectly, but when i add them the folder rename doesnt take place but in Radarr, its showing it did. Example is, bulk import he movie Epic with the folder structure Epic/Epic.mkv. The movie matched perfect and import goes through, but afterwards in Radarr it reports the folder path is Epic (year). When i go to the folder it is still Epic/Epic.mkv and the only way i can get it to do it correctly is manually edit the folder and file name to be what i have it set up as.  Below are a few examples. I have about 225 of these and would really like to not have to do them manually. Thanks and awesome work on this! Keep it up! Current settings are attached.  Logs are pasted below, first is info, second is debug.
![capture](https://user-images.githubusercontent.com/30101327/28101219-0f2ef272-6695-11e7-908e-dd377cde7bc1.PNG)

17-7-11 23:02:22.3|Warn|ParsingService|Unable to parse movie info from path M:\Movies\Ender's Game\Ender's Game.mkv
17-7-11 23:02:22.5|Warn|ParsingService|Unable to parse movie info from path M:\Movies\Enemy\Enemy.mp4
17-7-11 23:02:23.1|Warn|ParsingService|Unable to parse movie info from path M:\Movies\Epic\Epic.mp4
17-7-11 23:02:24.1|Warn|SkyHookProxy|Couldn't map movie Equilibrium to a movie on The Movie DB. It will not be added :(
17-7-11 23:02:24.4|Warn|ParsingService|Unable to parse movie info from path M:\Movies\Escape from Planet Earth\Escape from Planet Earth.avi
17-7-11 23:02:24.5|Warn|ParsingService|Unable to parse movie info from path M:\Movies\Eurotrip\Eurotrip.mkv
17-7-11 23:02:25.9|Warn|ParsingService|Unable to parse movie info from path M:\Movies\Exodus Gods and Kings\Exodus Gods and Kings.mkv

Below is debug logs from adding one called Fanboys/Fanboys.avi
17-7-11 23:55:29.0|Debug|Api|[PUT] /api/movie/import: 202.Accepted (268 ms)
17-7-11 23:55:29.0|Info|MediaCoverService|Downloading Poster for [tt0489049][Fanboys (2009)] http://image.tmdb.org/t/p/original/ywI92p2x7D96nuEayGVOMll35SF.jpg
17-7-11 23:55:29.0|Debug|HttpClient|Downloading [http://image.tmdb.org/t/p/original/ywI92p2x7D96nuEayGVOMll35SF.jpg] to [C:\ProgramData\Radarr\MediaCover\296\poster.jpg]
17-7-11 23:55:29.0|Info|RefreshMovieService|Updating Info for Fanboys
17-7-11 23:55:29.3|Debug|RefreshMovieService|Finished movie refresh for Fanboys
17-7-11 23:55:29.3|Debug|HttpClient|Downloading Completed. took 0s
17-7-11 23:55:29.3|Debug|MediaCoverService|Resizing Poster-500 for [tt0489049][Fanboys (2009)]
17-7-11 23:55:29.4|Debug|MediaCoverService|Resizing Poster-250 for [tt0489049][Fanboys (2009)]
17-7-11 23:55:29.4|Info|MediaCoverService|Downloading Banner for [tt0489049][Fanboys (2009)] http://image.tmdb.org/t/p/original/89udmMtxl8AuQHYoFdSgB5e6xYs.jpg
17-7-11 23:55:29.4|Debug|HttpClient|Downloading [http://image.tmdb.org/t/p/original/89udmMtxl8AuQHYoFdSgB5e6xYs.jpg] to [C:\ProgramData\Radarr\MediaCover\296\banner.jpg]
17-7-11 23:55:29.5|Info|DiskScanService|Scanning disk for Fanboys
17-7-11 23:55:29.5|Debug|DiskScanService|Scanning 'M:\Movies\Fanboys' for video files
17-7-11 23:55:29.5|Debug|DiskScanService|1 video files were found in M:\Movies\Fanboys
17-7-11 23:55:29.5|Debug|DiskScanService|[tt0489049][Fanboys (2009)] Cleaning up media files in DB
17-7-11 23:55:29.5|Debug|ImportDecisionMaker|Analyzing 1/1 files.
17-7-11 23:55:29.5|Debug|Parser|Parsing string 'Fanboys.avi'
17-7-11 23:55:29.5|Debug|Parser|Unable to parse Fanboys.avi
17-7-11 23:55:29.5|Debug|Parser|Attempting to parse episode info using directory and file names. Fanboys
17-7-11 23:55:29.5|Debug|Parser|Parsing string 'Fanboys Fanboys.avi'
17-7-11 23:55:29.5|Debug|Parser|Unable to parse Fanboys Fanboys.avi
17-7-11 23:55:29.5|Debug|Parser|Attempting to parse episode info using directory name. Fanboys
17-7-11 23:55:29.5|Debug|Parser|Parsing string 'Fanboys.avi'
17-7-11 23:55:29.5|Debug|Parser|Unable to parse Fanboys.avi
17-7-11 23:55:29.5|Warn|ParsingService|Unable to parse movie info from path M:\Movies\Fanboys\Fanboys.avi
17-7-11 23:55:29.5|Debug|ImportApprovedMovie|Decisions: 1
17-7-11 23:55:29.5|Info|DiskScanService|Completed scanning disk for Fanboys
17-7-11 23:55:29.6|Debug|Api|[GET] /api/system/task?sort_by=name&order=asc: 200.OK (4 ms)
17-7-11 23:55:29.6|Debug|Api|[GET] /api/system/task?sort_by=name&order=asc: 200.OK (4 ms)
17-7-11 23:55:29.6|Debug|HttpClient|Downloading Completed. took 0s
17-7-11 23:55:29.6|Debug|MediaCoverService|Resizing Banner-70 for [tt0489049][Fanboys (2009)]
17-7-11 23:55:29.7|Debug|MediaCoverService|Resizing Banner-35 for [tt0489049][Fanboys (2009)]
17-7-11 23:55:36.1|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (16 ms)
17-7-11 23:55:36.1|Debug|Api|[GET] /api/system/task?sort_by=name&order=asc: 200.OK (5 ms)
17-7-11 23:55:36.1|Debug|Api|[GET] /api/system/task?sort_by=name&order=asc: 200.OK (3 ms)
17-7-11 23:55:37.2|Debug|Api|[GET] /api/health: 200.OK (1 ms)
17-7-11 23:55:37.3|Debug|Api|[GET] /api/diskspace: 200.OK (10 ms)
17-7-11 23:55:37.4|Debug|Api|[GET] /api/health: 200.OK (7 ms)
17-7-11 23:55:37.4|Debug|Api|[GET] /api/diskspace: 200.OK (6 ms)
17-7-11 23:55:39.0|Debug|Api|[GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc&filterType=equal: 200.OK (22 ms)
17-7-11 23:55:39.1|Debug|Api|[GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc&filterType=equal: 200.OK (6 ms)
17-7-11 23:55:41.6|Debug|Api|[GET] /api/log/file: 200.OK (1 ms)

**Comment by galli-leo** [comment]
You currently have to have the year in the filename, even when bulk importing. There is an issue already open for this.

**Comment by HitsvilleUK** [comment]
Hi galli-leo
Could you tell me exactly what you mean by this?
All my files are in their own folders.
All folders are named as such
2 Guns (2013)
the files 
2 Guns (2013) plus quality iin some cases. 

<img width="359" alt="capture" src="https://user-images.githubusercontent.com/9288228/28816073-6135eb5a-769b-11e7-928b-d4957ea5a1ab.PNG">

All I have to do is click  the spanner for all the missing  bulk imported movies below and then hit save.
So in theory I'm not changing anything as far as I can see? 

<img width="547" alt="capture 1" src="https://user-images.githubusercontent.com/9288228/28816223-f9b43c56-769b-11e7-8b8f-18413fc80f71.PNG">

After that an update library will pick up those movies. Before that nothing. 
The trouble is I say "ALL I have to do" .... I need to add several hundred movies.

**Comment by galli-leo** [comment]
Yeah, after bulk import, Radarr needs an update library to pick up all the existing movie files. (Bulk import just adds the movies with the correct path to the wanted list, does not actually inform Radarr about the movie files).

> The trouble is I say "ALL I have to do" .... I need to add several hundred movies.

You should be able to add them all easily using a bulk import? Then just click update library once (though Radarr should do that on its own after finishing the bulk import)
