### ISSUE TITLE
Automation Lists Not Saving Specified Folder

### ISSUE THREAD

**Issue by xzKinGzxBuRnzx** [Radarr/Radarr#1786]
**Description:**

Just noticed this today but my automation list folder that I've specified as /mnt/NAS/Movies is blank. When attempting to save it again it resets back to blank.

As a result it's been importing new movies into / and filled my poor SSD.

**Radarr Version:**
0.2.0.778

**Logs:**
N/A

**Comment by galli-leo** [comment]
Yeah this is fixed on latest nightly. Blame chrome :/ (it worked on safari)
