### ISSUE TITLE
[Feature Request] Manual moves

### ISSUE THREAD

**Issue by BobOkisama** [Radarr/Radarr#1787]
I know the system already has automated moves, but I would like a way to do a manual move. 

Scenario: I have a Requests directory that I fill my requests into. After a certain period of time if I want to keep that movie I would like to be able to force a move to a different directory, such as Comedy and out of requests. Another use would be In Theater movies, be able to manually move them to a different folder after they are out of theaters.

**Comment by galli-leo** [comment]
So basically allowing to change the rootfolder?

**Comment by BobOkisama** [comment]
Not just change root folder, but change root folder and have it move the files as well. I know I can manually move the data then edit the root folder (sometimes works, othertimes tries to say root already exists, sonarr does that too), but this should be something that can be done through the GUI without manual intervention on the backend.

**Comment by Ashkaan** [comment]
This is the number one thing I need right now.  I have 2x Plex libraries: Beta and Collection.  I don't want to poison my Collection with things that need a first or revisited viewing.  When I watch something in Beta, I want to be able to tell Radarr to move it to my Collection.

**Comment by BobOkisama** [comment]
Still looking to get this request filled. I will be posting this in sonarr as well. I just moved a TON of TV shows, and I had to delete them from Sonarr, move the directories, then manually readd them to sonarr to do this. There should be a much easier way.

**Comment by Ashkaan** [comment]
You shouldn't have to delete them from Sonarr.  You can just change the directory.  Although I'm with you, it would be much nicer if we could just tell Sonarr/Radarr to move the files for us.

**Comment by BobOkisama** [comment]
That does not work for me, when I try to do that, it tries to add that as a root path to the system.

Example if I move Deadpool from /media/requests/deadpool to /media/action/deadpool I will show /media/action/deadpool as a root group now (if it even works) or it will error stating that this is already a root path and you cannot duplicate it.

I think it would be much better to just have the UI allow you to change the default directory and then a move button and the system will move the entire directory for you.

**Comment by Ashkaan** [comment]
Sonarr (v3) does this right now.  Is this on the roadmap?
