### ISSUE TITLE
Bad Attitude

### ISSUE THREAD

**Issue by Ronald-James** [Radarr/Radarr#1788]
Ive been using your product for some time now, but I cannot help but wonder what the reason is for sarcasm and the way you guys treat people!

I would truly consider donating money to the cause, but in no way am I going to donate when you treat people like shit or with sarcasm!!

**Description:**

Check first that your problem is not listed in our wiki section:
* https://github.com/Radarr/Radarr/wiki/Common-Problems
* https://github.com/Radarr/Radarr/wiki/FAQ

Provide a description of the feature request or bug here, the more details the better. 
Please also try to include the following if you are reporting a bug

**Radarr Version:**

**Logs:**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by danjames92** [comment]
# Are you special?
## Are you special?
### Are you special?

**Comment by hotio** [comment]
Here I was thinking you could donate for the development of radarr and server costs. Damn! All this time it was for making people feel good.

Can I get me moneyz back? Just sent all the bitcoins my way...thanks

**Comment by onedr0p** [comment]
@Ronald-James what are you talking about? Ignore the haters.
