### ISSUE TITLE
Radarr issues after downloading better quality movies

### ISSUE THREAD

**Issue by paulcrossan1982** [Radarr/Radarr#1789]
Hi,

I have recently installed Radarr (latest version) on Windows 10 

I have configured Radarr to download 1080P versions of my existing files.
This works great but the issue arrises after download Radarr creates a new folder with the movie name (but doesnt add the movie year which is specified to add)

The folders it should be creating already exist (due to replacing the file with a better quality)

Has anyone come across this issue? the system is specified to create new folders and name

![image](https://user-images.githubusercontent.com/30124648/28130958-613f74b0-6730-11e7-9c00-dc3b63d373db.png)

![image](https://user-images.githubusercontent.com/30124648/28131010-7b63bd1a-6730-11e7-877b-2c92806af28f.png)

**Comment by galli-leo** [comment]
Could you provide some screenshots of some examples?

**Comment by paulcrossan1982** [comment]
Hey thanks for your reply please see below

Oldest folder is the original (with year in folder name) and newest is the folder created by Radarr

![image](https://user-images.githubusercontent.com/30124648/28150916-8e8b11d6-678f-11e7-90a4-2c822d8b9b8a.png)

I see this in the logs 

![image](https://user-images.githubusercontent.com/30124648/28150939-a982a170-678f-11e7-915d-132782bfa015.png)

**Comment by galli-leo** [comment]
That looks very strange. Can you post your log file?
