### ISSUE TITLE
RemoteCertificateChainErrors when using StevenLu list

### ISSUE THREAD

**Issue by dingsbums** [Radarr/Radarr#1790]
17-7-12 19:44:15.2|Debug|StevenLuImport|Downloading List https://s3.amazonaws.com/popular-movies/movies.json
17-7-12 19:44:15.4|Debug|X509CertificateValidationPolicy|Certificate validation for https://s3.amazonaws.com/popular-movies/movies.json failed. RemoteCertificateChainErrors
17-7-12 19:44:15.7|Debug|NetImportSearchService|Found 10 movies from list(s) StevenLu
17-7-12 19:44:15.7|Debug|Api|[GET] /api/netimport/movies?listId=6: 200.OK (558 ms)
17-7-12 19:44:17.8|Debug|Api|[GET] /api/log/file: 200.OK (1 ms)
17-7-12 19:44:17.8|Debug|Api|[GET] /api/log/file/radarr.debug.txt: 200.OK (2 ms)

it's not adding anything from the 10 movies found

Version 0.2.0.778
Mono Version 4.8.0 (Stable 4.8.0.520/8f6d0f6 Wed Mar 15 16:18:35 UTC 2017)

**Comment by galli-leo** [comment]
Works fine for me. What are you trying to do?

**Comment by dingsbums** [comment]
I just want to fetch the list. ;)

Here's the trace log.

17-7-12 19:51:46.4|Trace|Http|Req: 1163 [GET] /api/netimport/movies?listId=6
17-7-12 19:51:46.4|Debug|StevenLuImport|Downloading List https://s3.amazonaws.com/popular-movies/movies.json
17-7-12 19:51:46.4|Trace|HttpClient|Req: [GET] https://s3.amazonaws.com/popular-movies/movies.json
17-7-12 19:51:46.4|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
17-7-12 19:51:46.6|Debug|X509CertificateValidationPolicy|Certificate validation for https://s3.amazonaws.com/popular-movies/movies.json failed. RemoteCertificateChainErrors
17-7-12 19:51:46.9|Trace|HttpClient|Res: [GET] https://s3.amazonaws.com/popular-movies/movies.json: 200.OK (472 ms)
17-7-12 19:51:46.9|Debug|NetImportSearchService|Found 10 movies from list(s) StevenLu
17-7-12 19:51:46.9|Trace|Http|Res: 1163 [GET] /api/netimport/movies?listId=6: 200.OK (519 ms)
17-7-12 19:51:46.9|Debug|Api|[GET] /api/netimport/movies?listId=6: 200.OK (519 ms)
17-7-12 19:51:48.0|Trace|Http|Req: 1164 [GET] /api/log/file/radarr.trace.txt

**Comment by galli-leo** [comment]
So via the List Import UI? What does the UI say?

**Comment by dingsbums** [comment]
> Sorry. We Couldn't Find Any Movies Matching ''
> Why can't I find my movie?

**Comment by galli-leo** [comment]
Are you sure you do not have imported all movies on that list already? Because that message will show in that case

**Comment by dingsbums** [comment]
OM...G. Now I feel stupid. I swear.... and ...  and so on. :P

Sorry for wasting your time. ;)

**Comment by galli-leo** [comment]
Ah no problem. The message is really misleading and I should really change it

**Comment by jeanpoelie** [comment]
6 months later, message still here, its really confusing at this point.
