### ISSUE TITLE
404 when clicking on wanted movie

### ISSUE THREAD

**Issue by wifiuk** [Radarr/Radarr#1791]
go to the wanted menu. see list of wanted movies there
Click on one of the movies get a 404 page with a demented angry bird pig.

Right click on the movie in the list and open in new window, loads up the movie page as expected.

**Comment by hotio** [comment]
Try clearing all of your browser cache

**Comment by wifiuk** [comment]
same issue

**Comment by hotio** [comment]
Which version are you running?
Does it happen in an Incognito window too?

**Comment by wifiuk** [comment]
Version
0.2.0.778

same issue in incognito window

**Comment by galli-leo** [comment]
duplicate of #1196

**Comment by highwaycat** [comment]
In my case the 404 happened because I added the movie on another language before. If you do this you have to search for it by it's original title.
