### ISSUE TITLE
3D Quality Profile

### ISSUE THREAD

**Issue by Darkknight33** [Radarr/Radarr#1793]
Radarr doesn't check for 3D tags, or have a separate quality profile for it. I could block the tag, but I do desire some movies in 3D making it a chore to manage in Radarr as some titles are mistakenly downloaded in 3D, while others that I want in 3D I have to get manually.

Related; 3D comes in Full/Half SBS (Side by side) and Top/Bottom. Radarr should know the difference between these 3 formats and only download the correct one. 

**Radarr Version:**
Radarr Ver. 0.2.0.778

**Logs:**
N/A

**Comment by mscodemonkey** [comment]
For me, something as simple as adding the 3D flag in the renamer would be a good interim measure.  Ideally there would be a flag to force 3D or force NOT 3D.  Unfortunately the preferred with a tag just doesn't work.

**Comment by galli-leo** [comment]
Try using restrictions. These are located under Settings -> Indexers.

Separate 3d handling is planned.
