### ISSUE TITLE
[Feature Request] Only download .mkv

### ISSUE THREAD

**Issue by wifiuk** [Radarr/Radarr#1794]
At the moment if i set my Profile to High Quality, that i have created it downloads BluRay's with .m2ts and .iso.
Many films i have on the torrents trackers i use are also classed a BlueRay but are using .mkv files

Can i have an option that only downloads .mkv files unless there is no other option?

**Comment by onedr0p** [comment]
While Radarr is searching for a release it won't know what the extension is because it only has the torrent / nzb name. Radarr won't know what the file extension is until after it downloads the file and during the import. The best way to accomplish your goal is to only set required words to scene groups that normally release mkvs.

**Comment by wifiuk** [comment]
Yeah I guess you have a point....




On Thu, Jul 13, 2017 at 7:08 PM +0100, "Devin Buhl" <notifications@github.com> wrote:












While Radarr is searching for a release it won't know what the extension is because it only has the torrent / nzb name. Radarr won't know what the file extension is until after it downloads the file and during the import. The best way to accomplish your goal is to only set required words to scene groups that normally release mkvs.

**Comment by onedr0p** [comment]
If there are any keywords in those release names (like DVD9, PAL, NTSC, BDISK) or whatever, restrict those in the settings.

**Comment by wifiuk** [comment]
Unfortunately not. I'll just have to work around it..






On Thu, Jul 13, 2017 at 7:15 PM +0100, "Devin Buhl" <notifications@github.com> wrote:












If there are any keywords in those release names (like DVD9, PAL, NTSC, BDISK) or whatever, restrict those in the settings.

**Comment by wifiuk** [comment]
i have managed to sort it by removing the BlueRay category on the indexer, while still being able to download the REMUX, 720p, 1080p etc that stull have the word BluRay in, it just wont download the BlueRay disks
