### ISSUE TITLE
Change configuration folder path

### ISSUE THREAD

**Issue by Firemad03** [Radarr/Radarr#1795]
Hi,

I don't know where I can find this information and I searched everywhere.

Does something like this exist?

`/usr/bin/mono --debug /appz/Radarr/Radarr.exe --nobrowser --config /newpath/config.ini`

If I'm using this:` /usr/bin/mono --debug /appz/Radarr/Radarr.exe --nobrowser` as root the configuration is always in` /root/.config/Radarr` but I want it somewhere else ?

Note: I'm using Debian

**Comment by galli-leo** [comment]
--data=/here
