### ISSUE TITLE
sabnzbd priority doesn't work well

### ISSUE THREAD

**Issue by Firemad03** [Radarr/Radarr#1796]
Hi,

The priority for the aired time doesn't work well in sabnzbd in the download clients tab.

![image](https://user-images.githubusercontent.com/24792889/28236233-7b6ca2e4-68ee-11e7-9b70-ed623a118143.png)

Everything is in high priority and it doesn't detect well the older release for a lesser priority.

This settings is working fine in Sonarr.

![image](https://user-images.githubusercontent.com/24792889/28236247-c58b0208-68ee-11e7-88fc-6c98e7512da3.png)

**Comment by galli-leo** [comment]
Well not implement yet actually. See #229
