### ISSUE TITLE
Quality profile 2160p minimum size make it a bigger value

### ISSUE THREAD

**Issue by Firemad03** [Radarr/Radarr#1797]
Hi,

The 2160p for the minimum size can you make it a lot more bigger for the value ?

I want to add only minimum 50 GB but I can't because the maximum is 17.58 GB

![image](https://user-images.githubusercontent.com/24792889/28236273-dac41460-68ef-11e7-9a6e-88653af1a3c7.png)

**Comment by streat90** [comment]
I see there have been a few subsequent issues referencing this one. I am aware there is an option to manually edit the database but is there any ETA on a UI update such as this?

**Comment by Firemad03** [comment]
+1 lots of 4k are superior of the maximum of 27.34GB. I'm ok with this setting but I will prefer to move it at 30GB because I miss some release and I don't want 60GB and I'm not comfortable enough to use the database.
