### ISSUE TITLE
LSOpenURLsWithRole() failed with error -10810.

### ISSUE THREAD

**Issue by bgunsberger** [Radarr/Radarr#1799]
In the last week or so I've been unable to launch Radarr for MacOS either from Finder or the command-line.

Running from with command line with:

> open /Applications/Radarr.app/

gives

LSOpenURLsWithRole() failed for the application /Applications/Radarr.app/Contents/MacOS/Radarr with error -10810.

Running from Finder gives nothing (including no errors).

I get the same issues with v0.2.0.696 and v0.2.0.778.

I'm running it on MacOS 10.12.5 on a 2010 Mac Mini with 8gb RAM.

**Comment by galli-leo** [comment]
Are you using keka or anpther thirdpaty zip utility? Can you try chmod +x /Applications/Radarr.app/Contents/MacOS/Radarr ?

**Comment by bgunsberger** [comment]
No, I'm just using Chrome to download the app and MacOS unzips it automatically.

The chmod didn't help.

**Comment by galli-leo** [comment]
@bgunsberger Can you try running the binary directly? (so /Applications/Radarr.app/Contents/MacOS/Radarr in a terminal)

**Comment by bgunsberger** [comment]
I got the page of error text mentioning a corrupted DB. I followed those instructions and got it working again.

Thanks.
