### ISSUE TITLE
Trakt List - Radarr move movies in /

### ISSUE THREAD

**Issue by Firemad03** [Radarr/Radarr#1800]
Hi,

I don't know why Radarr is moving the movie in / temporary or not... 

I checked all my settings and I don't understand why he always do that.

![image](https://user-images.githubusercontent.com/24792889/28241639-61395584-6966-11e7-9878-03cd7eb8f889.png)

My downloaded movies is on another NFS path and the final path too for Plex.

Why Radarr need to move it at the / ?

Can we change the default location of it if it's needed ?

![image](https://user-images.githubusercontent.com/24792889/28241654-ae20c80a-6966-11e7-9604-c5a045524b3a.png)

**Comment by Firemad03** [comment]
The main reason I'm asking this and I found this problem is because my VM is a small VM with 10GB of disk but if Radarr always move it in the / I will get a big problems for space issues...

**Comment by Firemad03** [comment]
Omg I found it! It's the Trakt list and I didn't set the folder path... I corrected my problem but I suggest that you add it as a required field :) !!!

**Comment by Firemad03** [comment]
I set the folder path but every time that it's checking the Trakt list it's always changing my path to the / instead of the folder path variable that I set correctly this time.

I guess I found a bug ;)

**Comment by DFDC** [comment]
This is the same issue as #1780 #1786 and a few others.

**Comment by Firemad03** [comment]
@DFDC I already have the latest nightly :) and the bug is still there. Maybe you mean another fix will there soon ?

**Comment by galli-leo** [comment]
@Firemad03 Currently on latest nightly and it works for me. Try clearing cache / an incognito window.
