### ISSUE TITLE
Radarr Ver. 0.2.0.778: Bulk Import Parsing from Folder Name

### ISSUE THREAD

**Issue by SetTheCat** [Radarr/Radarr#1801]
After wishing for a branch of Sonarr that can manage my movie library I was ecstatic when a coworker told me about Radarr. As soon as I got home yesterday I ripped out my old Couch Potato install and started my Radarr setup. After playing with it for a few hours I noticed something...

I have categorized my movies a specific way for a mix of Kodi compatibility and Source tracking. I keep the original file name on the folder, and name the media file with the movie name only. For example:

.\Star Wars Episode IV A New Hope 1977 Despecialized 720p BluRay AC3 x264-Harmy [tt0076759]\Star Wars, Episode IV - A New Hope (1977) [tt0076759].mkv

When doing bulk imports of my movie library, I noticed that Radarr only parses the media file name for quality and release group. Using the example above, the movie gets imported as HDTV-720p and no release group is found. If I apply the folder name to the file name then it will parse properly and understand that the file is BluRay-720p released by Harmy.

My question is, what is the status of folder name parsing? Was it planned but not quite working yet, investigated but decided against, or simply overlooked?

On a side note, does the bulk import parsing process look for an IMDB ID to identify the movie, or only look for name/year? This question just popped into my head while writing this post, so I honestly haven't looked for an answer yet.

**Comment by hotio** [comment]
Use this as a folder name `Movie Title (2017)`, as a filename you can use the original name or something else that contains all required info. From personal experience the following naming convention, is compatible with just about everything, like radarr, kodi, plex, guessit, autosub, ....

```
Movie Title (2017)/Movie Title (2017) - movie.title.2017.1080p.bluray.ac3.5.1.x264-group.mkv
```

**Comment by galli-leo** [comment]
We use imdbid when found in the folder name. Not really looking to add quality parsing to the folder name, since you are probably the first person on here to only add the release quality to the folder but not the file.
