### ISSUE TITLE
IMDB List Downloads landing in C:/Windows/Syswow64 Instead of specified directory

### ISSUE THREAD

**Issue by musthaveit** [Radarr/Radarr#1803]
Hi 

I see others have posted similar issues, although they are running different OS by the looks so thought I should post this also.  I have specified Directory D:/Downloads/Movies in my IMDB list settings, yet when I click on movies added to Radarr from this list it is showing the download location as C:/Windows/System32.   And indeed, each download is landing in my system folder and cluttering up my smallest hard drive.

An update on if this is going to be fixed soon for the Windows version would be much appreciated.

Thanks, I love Radarr, its amazing.

**Comment by galli-leo** [comment]
As you may have seen, this issue is due to the path selection when setting up lists being glitchy. Whenever you reopen a list an empty path will show. This is fixed on the latest nightly.
