### ISSUE TITLE
Option {Clean.Title} didn't remove accent

### ISSUE THREAD

**Issue by zobi** [Radarr/Radarr#1804]
All is in the Title for example : 

Rise.of.the.Guardians.(2012)/Les.cinq.légendes.2012.HDTV-720p.mkv

The é is not replace by e

In System configurator i choose : {Movie.CleanTitle}.{Release.Year}.{Quality.Title} 

Thanks a lot

**Comment by ScottBurfieldMills** [comment]
This is interesting because one of the existing test cases for this covers making sure that the "é" in Beyoncé remains.

**Comment by Algedi13** [comment]
Hello,
For the Movie Folder Format in french it's the same thing there is always an accent even with the option {Movie CleanTitle}

**Comment by s0mm3rb** [comment]
+1 for this
in my opinion the clean title option should remove any special chars in the name
but sonarr keeps unicode chars in the name too
apperantly they don't think they need to be removed
I strongly disagree on that
especially when working through cli on headless servers any non ascii chars always cause issues

@Qstick:
you've reopend this on 21 May 2018
is there a chance this gets (or is being) implemented?

thanks regards
