### ISSUE TITLE
Weird log error - Import failed, path does not exist or is not accessible by Radarr: /downloads/incomplete/radarr/Filename/

### ISSUE THREAD

**Issue by fc0712** [Radarr/Radarr#1806]
Hey

I have encountered this error for a week or so:

Import failed, path does not exist or is not accessible by Radarr: /downloads/incomplete/radarr/Filename/

It reports that to log every minute. Radarr works fine when downloading and moving files to media drive. 

I have no knowledge of any movies named "filename" I have a movie named a similarname that has been moved to my media drive and is playable in Plex. What should one do to stop this error from occurring. 

I'm running Radarr Docker by linuxserver (latest) 

<img width="577" alt="skaermbillede 2017-07-16 kl 21 18 06" src="https://user-images.githubusercontent.com/25506722/28250579-4bdadcb0-6a6c-11e7-80ee-40d44db7768e.png">

**Comment by hotio** [comment]
Remove the entry from your download client, or change its label.

**Comment by fc0712** [comment]
Thanks :) Found out that there was an old history in my SAB client. Hopefully that fixed it :)

**Comment by hotio** [comment]
If it's fixed close this issue, save the devs a lot of time.

**Comment by fc0712** [comment]
I Will monitor the issue the next hour and close the issue if solved
