### ISSUE TITLE
General/UI Language Setting.

### ISSUE THREAD

**Issue by supremacy2k** [Radarr/Radarr#1807]
Hi.

I noticed, that Radarr pulls Movie synopsis in whatever language is set in the  selected Profile.
I prefer everything in English, but since I'm danish, and requires Danish Subs, both Sonarr and Radarr mistakenly sees the audio as Norwegian, making it ignore the release.

In Sonarr, i can just select Norwegian language in profile, and movie synopsis is still in english, and it grabs whatever release it can find.

Can we please get a general language setting under Settings -> General or Settings -> UI?
It's pretty annoying, reading the synopsis in Norwegian, when everything else is in English.

**Comment by supremacy2k** [comment]
Any updates?

**Comment by JBCn1** [comment]
Its still not working.
Fore example:
Just added Annihilation yesterday, and my profile was ENG. Today I was wondering why Radarr didnt download it and did a manual search. It didn't download the movie becaurse it saw it as Norwegian.

Its fully updated Radarr.
