### ISSUE TITLE
[Feature Request] Be able to delete from the Movie editor

### ISSUE THREAD

**Issue by reavenm** [Radarr/Radarr#1808]
It would be easier than running the script if we could delete and bulk delete unwanted grabbed movies by list for example, from the Movie editor itself

**Comment by hotio** [comment]
http://feathub.com/Radarr/Radarr/+3

Is known a long time, asking this several times a day is probably going to have the opposite effect...

**Comment by galli-leo** [comment]
This is in the latest release.
