### ISSUE TITLE
[ Feature Request ] - Failed or Aprrove Icon with Auto Download

### ISSUE THREAD

**Issue by monkeyslapper** [Radarr/Radarr#1810]
In the movie Details, you have auto search icon ( Magnify Glass ). When you press it, the icon changes to a spinning icon ( searching ). When the searching finish it goes back to ( Magnify Glass). I would like a  failed (x) and aprrove (check mark) icon. Then at least i know i will have to do a manual check and see what did not make the cut and why.

Other then that. I am loving it so far. Alot to setup and trial and error. Hard to confirm to the program, but I am getting better. 

Thanks for a great program

Monkeyslapper

**Comment by hotio** [comment]
If after pressing search you don't see something come up under activity, you can be certain, you'll have to do a manual search to see what did not make the cut.

**Comment by galli-leo** [comment]
Also there should be a message in the ui along the lines of "Search completed. 1 Download added to DL Client."
