### ISSUE TITLE
Failed to map movie

### ISSUE THREAD

**Issue by gprime44** [Radarr/Radarr#1811]
Hello,

I use Radarr with Jacket to do search on YGGTorrent, but radarr can't map movie  after manual search

![image](https://user-images.githubusercontent.com/18438018/28276714-0cae15f0-6b18-11e7-9e24-0d4e8d91392b.png)

The first result must match, but I have this error message :

![image](https://user-images.githubusercontent.com/18438018/28276797-4906caf6-6b18-11e7-9520-a7354904ca0f.png)

Another sample 

![image](https://user-images.githubusercontent.com/18438018/28277045-fbb56824-6b18-11e7-999e-9b6cb704d8ca.png)

Thx ;-)

**Comment by hotio** [comment]
That's because the year isn't in the right place, go complain at your indexer.

**Comment by gprime44** [comment]
Okay thx, So where the date must be ? At the end ?

**Comment by hotio** [comment]
Movie.Title.Year.All.The.Rest-Rest.mkv

**Comment by wifiuk** [comment]
i have a similar issue
![image](https://user-images.githubusercontent.com/3785545/28743133-46206254-743a-11e7-98d1-b3f38c7eb238.png)

**Comment by galli-leo** [comment]
@wifiuk Your problem is that as far as radarr is concerned 1/3 and the 1/3 symbol are not the same. There is an issue already open for this (Lion King 1/2 iirc).
