### ISSUE TITLE
[ Feature request ] Rename movie folder, not the file

### ISSUE THREAD

**Issue by pven** [Radarr/Radarr#1812]
I only want to rename the movie folder, not the file in it. It looks like this is not possible at this moment. When I enable rename movies, the file must be renamed. Or can I override this setting?

**Comment by hotio** [comment]
What you want is already possible.

**Comment by pven** [comment]
How?

**Comment by hotio** [comment]
`{Original Title}`

**Comment by pven** [comment]
Thanks!

What is the differnece with {Original Filename}? I can not use {Original Filename} because it tells me the movie-name must be in it. But I need the filename lookup subs.

**Comment by hotio** [comment]
{Original Filename} does not exist

**Comment by galli-leo** [comment]
Try looking at issues with title rename folder to see how you can do it (would link, but currently on mobile)
