### ISSUE TITLE
Do not prioritize Indexer Flags over Protocol

### ISSUE THREAD

**Issue by hotio** [Radarr/Radarr#1814]
At the moment the option `Prefer Special Indexer Flags` has a higher priority then the protocol.

So when using `Prefer Usenet` and `Prefer Special Indexer Flags` set to `Yes`, torrents that are `Freeleech` for example are picked instead of Usenet (nzb).

If there is a preference for Usenet, why should we download a torrent (just because it's freeleech)?

I believe the Usenet vs Torrent has a bigger weight in the decision and all indexer flags should prioritize by keeping it inside the protocol. Right now the indexer flags are stepping outside of the protcol boundaries.

**Comment by suckerfish** [comment]
Still an issue. Just happened to me which prompted me to search for this behavior and I found this issue.

**Comment by sharkone** [comment]
Could one way of fixing that would be to only consider Usenet as Freeleech?

**Comment by dmemedo** [comment]
Any news about this ? Maybe it's fixed in Aphrodite ?
