### ISSUE TITLE
Release with SE in there name is not parsed properly

### ISSUE THREAD

**Issue by Fredrik81** [Radarr/Radarr#1815]
**Description:**
Releases with SE in name is not detected as Special Edition and in some cases parsed improperly so can't be downloaded.

Release examples not working and not detected as "Special Edition":
Fantasia.2000.SE.1999.1080p.BluRay.H264.AAC-RARBG
Fantasia.2000.SE.1999.1080p.BluRay.x264-THUGLiNE
Fantasia.2000.SE.1999.1080p.BluRay.x264-THUGLiNE

Release that is parsed correctly and working:
Fantasia.2000.1999.720p.BluRay.H264.AAC-RARBG

So only the SE in between the name and year will break it + not flagged correctly with edition

**Radarr Version:**
Latest nightly

**Logs:**
The releases that do not work show this under the red !
Failed to map movie, found title Fantasia, expected one of: Fantasia 2000, Fantasia 2000, Fantasia '99, Fantasia/2000, Fantasia Continued

**Comment by bakerboy448** [comment]
Closing
v0.2 is no longer being actively developed.

If this is still an issue/request on recent v3 builds, please open a new issue.
