### ISSUE TITLE
Calendar view is empty

### ISSUE THREAD

**Issue by mmozeiko** [Radarr/Radarr#1816]
After adding a lot of movies my Calendar view is empty. Initially it was showing some movies.

**Radarr Version:** 0.2.0.778

**Logs:** Here's a log from Chrome devtools: https://gist.github.com/mmozeiko/d4fe4a9099aadcd3529c4e7449e2fd8b

**Comment by galli-leo** [comment]
Can you try clearing cache and cookies? Also a different browser? Works for me.

**Comment by mmozeiko** [comment]
It worked for me when I had 10-20 movies. After importing all my ~2k movies fit doesn't show up. Same thing with different browsers or clearing cache.

Here's output from Firefox Web Console.

    template render failed for calendar/upcomingitemview TypeError: this.series is undefined  vendor.js:19262
    <unavailable>  vendor.js:19263
    TypeError: this.series is undefined  vendor.js:23068:10
    TypeError: element.getStatus(...) is undefined  main.js:18584:19
