### ISSUE TITLE
Radarr hangs and doesn't respons

### ISSUE THREAD

**Issue by mitchelp** [Radarr/Radarr#1819]
**Description:**

Got radarr hanging, it starts but during the library refresh at startup it just hangs.
And doesn't respons anymore. Below the last lines of the debug log.

Anybody a idea what this could be? What I do notice is that its always hanging on the same release (check the log below). Is there a way to manually remove it from Radarr?

**Radarr Version:**
Latest develop version

**Logs:**

17-7-19 09:08:35.7|Debug|RootFolderService|Generating list of unmapped folders
17-7-19 09:08:35.7|Info|DiskScanService|Scanning disk for The Adjustment Bureau
17-7-19 09:08:35.7|Debug|DiskScanService|Scanning '/plex/acdPlex/media/plex/Movies/The Adjustment Bureau (2011)' for video files
17-7-19 09:08:35.7|Debug|DiskScanService|2 video files were found in /plex/acdPlex/media/plex/Movies/The Adjustment Bureau (2011)
17-7-19 09:08:35.7|Debug|DiskScanService|[tt1385826][The Adjustment Bureau (2011)] Cleaning up media files in DB
17-7-19 09:08:35.7|Debug|ImportDecisionMaker|Analyzing 1/2 files.
17-7-19 09:08:35.7|Debug|Parser|Parsing string 'The.Adjustment.Bureau.2011.720p.BluRay.x264-SiNNERS.avi'
17-7-19 09:08:35.7|Debug|Parser|Movie Parsed. The Adjustment Bureau - 2011
17-7-19 09:08:35.7|Debug|Parser|Language parsed: English
17-7-19 09:08:35.8|Debug|QualityParser|Trying to parse quality for The.Adjustment.Bureau.2011.720p.BluRay.x264-SiNNERS.avi
17-7-19 09:08:35.8|Debug|Parser|Quality parsed: Bluray-720p v1
17-7-19 09:08:35.8|Debug|Parser|Release Group parsed: SiNNERS
17-7-19 09:08:35.8|Debug|ImportDecisionMaker|Size: 2897780736
17-7-19 09:08:35.8|Debug|VideoFileInfoReader|Getting media info from /plex/acdPlex/media/plex/Movies/The Adjustment Bureau (2011)/The.Adjustment.Bureau.2011.720p.BluRay.x264-SiNNERS.avi
17-7-19 09:08:37.4|Debug|Api|[GET] /api/movies/lookup?term=The+Adjustment+Bureau: 200.OK (1803 ms)
17-7-19 09:08:37.4|Debug|Parser|Parsing string 'The Adjustment Bureau'
17-7-19 09:08:37.4|Debug|Parser|Unable to parse The Adjustment Bureau
17-7-19 09:08:37.6|Info|TMDbImport|Found more than 3 pages, skipping the 13 remaining pages
17-7-19 09:08:37.6|Debug|TraktImport|Downloading List https://api.trakt.tv/movies/boxoffice?years=&genres=&ratings=0-100&certifications=nr,g,pg,pg-13,r,nc-17&limit=100
17-7-19 09:08:37.7|Debug|RSSImport|Downloading List http://rss.imdb.com/list/ls057823854/
17-7-19 09:08:37.8|Debug|Api|[GET] /api/movies/lookup?term=The+Adjustment+Bureau: 200.OK (405 ms)

**Comment by hotio** [comment]
Try running on local content only.

**Comment by mitchelp** [comment]
thanks @hotio got it fixed.
