### ISSUE TITLE
Disable existing items when Importing from Disk

### ISSUE THREAD

**Issue by bigbasec** [Radarr/Radarr#182]
Feature request to not show existing items when importing.  

When you have several thousand movies and are trying to add them, obviously doing it in one sitting can be very time consuming.  So I guess it's just a request that there maybe be a checkbox or something at the top to "Don't Show Existing", so you can just keep on continuing to add movies without seeing the ones you already did.

**Comment by simonk83** [comment]
Agreed

**Comment by onedr0p** [comment]
I believe this will be handle in #150

**Comment by bigbasec** [comment]
But I'm not sure if I want to "Import All", I'd just like a way to not see the files I have already done.  We'll see what they come up with, seems like things are on the right path.

**Comment by onedr0p** [comment]
I think it shouldn't allow you to import a movie again, so it shouldn't be there on the dialog.

**Comment by bigbasec** [comment]
Agreed.  It won't let you import it again, it just shows "Existing".  But it shouldn't be there at all in my opinion.  I guess it will likely add some load to the process, as now the DB needs to be checked for each file prior to display.

**Comment by onedr0p** [comment]
Exactly, I believe we can cross check in the database if the sub-folder/file is already imported and omit it .

**Comment by bigbasec** [comment]
It's be nice.  For now I've stopped importing, as it's not really doing anything for me and it's a painful process.  I'd be happy to test if a change it made.

**Comment by onedr0p** [comment]
Made a note in #150 thanks 👍

**Comment by onedr0p** [comment]
Added :)
https://github.com/Radarr/Radarr/commit/c2d40051d4f9a188097936f91f8853b55854802b
