### ISSUE TITLE
Failed to find movie title in release name

### ISSUE THREAD

**Issue by savahu** [Radarr/Radarr#1820]
**Description:**
Radarr can't find the movie title in a title that is exactly the movie title.
See screenshot:
![schermafbeelding 2017-07-19 om 22 42 02](https://user-images.githubusercontent.com/14197530/28388697-dd2c8132-6cd3-11e7-9c62-c22140f26875.png)

**Radarr Version:**
0.2.0.778

**Logs:**
17-7-19 22:31:46.6|Info|MovieService|Adding Movie [][The Swedish Theory of Love (2016)] Path: [/media/union/media/movies/The Swedish Theory of Love (2016)]
17-7-19 22:31:46.6|Info|RefreshMovieService|Updating Info for The Swedish Theory of Love
17-7-19 22:31:47.1|Info|DiskScanService|Scanning disk for The Swedish Theory of Love
17-7-19 22:31:47.2|Info|MovieScannedHandler|[The Swedish Theory of Love] was recently added, performing post-add actions
17-7-19 22:31:47.2|Info|MediaCoverService|Downloading Poster for [tt4716560][The Swedish Theory of Love (2016)] http://image.tmdb.org/t/p/original/6Zmyz5kyoc4DYmM6FHTd1l68hP3.jpg
17-7-19 22:31:47.2|Info|NzbSearchService|Searching 8 indexers for [The Swedish Theory of Love]
17-7-19 22:31:47.3|Info|MediaCoverService|Downloading Banner for [tt4716560][The Swedish Theory of Love (2016)] http://image.tmdb.org/t/p/original/rpQgR0OVjKPEVVIYva3QK8MqWxl.jpg
17-7-19 22:32:13.6|Info|DownloadDecisionMaker|Processing 3 releases
17-7-19 22:32:13.6|Info|MovieSearchService|Movie search completed. 0 reports downloaded.

**Comment by savahu** [comment]
I guess Radar thinks the movie is released in 2016.
Therefore it won't pick the one released in 2015, and it doesn't pick the ones without year in title at all..

I thought I read something about  Radarr choosing the lowest year returned from TMDb though.

**Comment by Fredrik81** [comment]
This is not a problem with Radarr. The film was incorrectly put as released in 2016 in TheMovieDB.
I fixed the release dates so it should work next time radarr checks it.

**Comment by savahu** [comment]
Okay thank you.

Would be nice if Radarr checked the IMDb returned from the Torznab indexer though.

**Comment by brando56894** [comment]
I'd like to reopen this because I'm seeing the same thing for Auqa Teen Hunger Force Colon Movie Film For Theaters. Both my NZB and Torrent sources say this, and the release date of 2007 matches on both IMDB and TMDB. I'm not sure if another issue is related to this but once the torrent downloaded from PassThePopcorn it wouldn't post-process it, stating that there was no movie file matching the title, even though the MKV was right there, uncompressed.

**Comment by s0mm3rb** [comment]
same issue from time to time and on different indexers

![grafik](https://user-images.githubusercontent.com/38328575/50497330-c4561b80-0a36-11e9-835b-d14ed6429f11.png)

Debug Logs: 
[https://pastebin.com/hhfZzrZR](https://pastebin.com/hhfZzrZR)
[https://pastebin.com/AKAfcUkd](https://pastebin.com/AKAfcUkd)

regards

**Comment by s0mm3rb** [comment]
> ![grafik](https://user-images.githubusercontent.com/38328575/50497330-c4561b80-0a36-11e9-835b-d14ed6429f11.png)

ok found the solution here [Radarr issue #3000 ](https://github.com/Radarr/Radarr/issues/3000#issuecomment-417580772)
the reason for this is the missing year in the release title
solve it by changing the parser settings to lenient mapping:
enable advanced settings -> goto indexers -> options -> parser leniency -> change it to lenient mapping
