### ISSUE TITLE
Add torrent in pause state

### ISSUE THREAD

**Issue by Celedhrim** [Radarr/Radarr#1825]
**Description:**
My downloader is a transmission daemon ( I have only have remote access) and when radarr add a torrent ( find a release) the torrent stay pause and I must start it manually using transmission remote

I know it's radarr because never add that issue with couchpotato or sickrage.

Is it an expected behaviour ?

**Radarr Version:**

 0.2.0.778

**Comment by hotio** [comment]
No, it is not an expected behaviour.

**Comment by Celedhrim** [comment]
Sonarr do the same.

So I have a script to start all torrent in state pause and percent less than 100.

I think radarr/sonarr just add the torrent.

Sickrage add and start

```python
...
'paused': 1 if sickrage.srCore.srConfig.TORRENT_PAUSED else 0,
...
```
