### ISSUE TITLE
Anyway to disable daily Update Movie task?

### ISSUE THREAD

**Issue by ghost** [Radarr/Radarr#1826]
With over 10k movies, this is extremely painful and takes a very long time.  Is there anyway to disable this?

**Comment by galli-leo** [comment]
I am planning on adding different time intervals for the states movies are in. E.g. In Cinemas movies are refreshed every 24 hours, Downloaded movies are refreshed every 128 hours, etc.

**Comment by jonesb63** [comment]
Thanks, I know that you have a lot to do, but it is currently not possible for me to add  new movies to radarr because all radarr does is scan, since the scan can never finish because I have over 10k movies and 15k monitored movies.  It would be nice if this wasn't a thing to begin with, I don't think to many people want there libraries constantly scanned, even if it was once a week.  There is no use to doing this,

**Comment by shushry** [comment]
I'll +1 this and offer up testing.   Library is 7k+ and frequently runs into performance issues over the evolution of the project.

**Comment by galli-leo** [comment]
@shushry So I disabled the movie refresh for movies that are over 30 days past their release date (They should only refresh every 30 days or so). That should help, right?

**Comment by shushry** [comment]
I saw that commit - I'll test the refresh process and time it on my collection.   Would the same limit be in place if one manually hits the refresh movies button, or only during the scheduled job?

**Comment by galli-leo** [comment]
@shushry Currently only during a scheduled job, because if you manually trigger it, you usually want to do a full refresh.

**Comment by jammin84** [comment]
Was this added in the 2.0 release?

**Comment by binarylimited** [comment]
im on the latest nightly/ build and it still wants to update the library every 24hrs

**Comment by Qstick** [comment]
Makes sense given the issue is still open

**Comment by zapras** [comment]
Any word on this? I have over 20k movies and it just refreshes all the time now.

**Comment by fryfrog** [comment]
You could edit the DB if you want instant gratification. I assume you've already turned off the analyze media settings?

**Comment by zapras** [comment]
It's actually far from as bad as what I thought. Takes just a couple of hours. Just so happens I check it at around the same time each day and saw it refreshing. It's an rclone mount so I was a bit pessimistic it would handle it, but it's fine. Just the RAM for Radarr takes a lot compared to Sonarr. But with 32GB ddr4, it's fine.

**Comment by B-Mqn** [comment]
once it has downloaded the movie and got the posters/art and details it doesnt need to refresh it again. whats it actually doing when it refreshes?

**Comment by airship-david** [comment]
I had this problem too. If anyone wants an instant fix they can do exactly what @fryfrog suggested. In the ScheduledTasks table inside the database you can set the interval (frequency in minutes) that Radarr should fire the RefreshMovieCommand. I changed mine to 10080 (weekly). Quick and easy.

**Comment by B-Mqn** [comment]
how do you edit the database?

**Comment by Aethaeran** [comment]
@B-Mqn 
Download and install DB Browser (SQLite)
Browse to your nzbdrone.db for radarr and open with DB Browser (SQLite)
Click Browse Data tab
Select ScheduledTasks table from the dropdown list
Select the interval column for which task you want to modify the interval of (0 = disabled)
Change the value on the right side of the application
Click Write Changes 
Close the app

**Comment by B-Mqn** [comment]
ok so i set mine to disabled....
just to confirm this only disables refreshing movies in your already downloaded list and not stops you from monitored movies that haven't downloaded yet?

**Comment by Aethaeran** [comment]
@B-Mqn 
As far as I know, monitored movies is grabbed via the 'Rss Sync' task.

**Comment by Aethaeran** [comment]
@airship-david @fryfrog @B-Mqn 
Just noticed that my intervals inside the database are returning to default whenever Radarr is restarted. Anyone else having this issue? or know how to rectify it?

**Comment by B-Mqn** [comment]
Hmm did/do you have to disable the service before editing?

**Comment by Aethaeran** [comment]
The opposite seems to be true. I can edit it while the service is running, and can disable it at that time. Unfortunately, the next time I restart the computer or even just Radarr itself, the intervals for all tasks are reset.

**Comment by Aethaeran** [comment]
Nevermind.
Found a workaround for those wanting to disable tasks, and are having their intervals reset on restart.
Set the LastExecution of the task you want to disable to 1000 years in the future. Since you'll likely never see this time, the task never triggers.

/win

![image](https://user-images.githubusercontent.com/33813964/70961501-d3165380-2036-11ea-824e-fc3e3ab0e7c4.png)

**Comment by B-Mqn** [comment]
Just dont accidently do a manual refresh or you will have to reset it again.

Mine had reverted back. I dont know if it was because it was set to disable or it just doesnt save the setting

**Comment by Qstick** [comment]
This is much improved in v3, no plans to allow disabling

**Comment by mytvpro** [comment]
> This is much improved in v3, no plans to allow disabling

sonarr v3 allows disabling. why not also allow it? i would really prefer not to have to hack the db like everyone is. many of use using rclone and drive api gets hammered by large database refresh that isn't necessary so frequently...

**Comment by fryfrog** [comment]
https://i.imgur.com/quzM88J.png

^ This is the only control I know of and it exists in both Sonarr and Radarr. What makes you think you can disable *Sonarr's* daily update task?

**Comment by mytvpro** [comment]
> https://i.imgur.com/quzM88J.png
> 
> ^ This is the only control I know of and it exists in both Sonarr and Radarr. What makes you think you can disable _Sonarr's_ daily update task?

Wait this is what I'm talking about. I don't see it in radarr...

**Comment by B-Mqn** [comment]
What is the actual benefit to refreshing this?
For someone who once the movie is imported doesnt want a better quality?

**Comment by mytvpro** [comment]
> What is the actual benefit to refreshing this?
> For someone who once the movie is imported doesnt want a better quality?

Radarr should know if the movie is there or not and details so it knows to download or not

**Comment by fryfrog** [comment]
@mytvpro, it is in v3. I wouldn't generally recommend it, but if this is a very important feature to you... it'd be worth trying and maybe using.

**Comment by gitowok** [comment]
> https://i.imgur.com/quzM88J.png
> 
> ^ This is the only control I know of and it exists in both Sonarr and Radarr. What makes you think you can disable _Sonarr's_ daily update task?

@fryfrog That control looks like exactly what we need to prevent disks spinning up every day. Do you think that would work?

**Comment by bob454522** [comment]
> > https://i.imgur.com/quzM88J.png
> > ^ This is the only control I know of and it exists in both Sonarr and Radarr. What makes you think you can disable _Sonarr's_ daily update task?
> 
> @fryfrog That control looks like exactly what we need to prevent disks spinning up every day. Do you think that would work?

Where is this option in the gui ? (i cant find that)  

there is no reason that we are forced to have a scan every 24h  (or hack the DB which keeps reverting, so you have to hack the last execution date??)  i have 20k + movies and all radarr does is scan over and over.

**Comment by Qstick** [comment]
![6EA048D6-F832-4783-9E86-942B1A0E12D7](https://user-images.githubusercontent.com/376117/87847752-699a4400-c8a8-11ea-843b-8a1068594eca.jpeg)

**Comment by bob454522** [comment]
@Qstick  - i couldnt find that option at all,  but now i see that there is a alpha release of radarr v3 (Aphrodite) ,  so some of this makes a bit of sense now.   I assumed i was on the latest Radarr (v0.2.0.1504 - "pre-Release")  since it auto updates and im on the "develop" Branch.  but i now see im on v2.x and there is a  v3.x "Branch: aphrodite (very-unstable)" -   
As i have a massive movie library im a bit concerned on moving to v3.x ("very-unstable").
![image](https://user-images.githubusercontent.com/60830628/87858571-6dec4e80-c8f4-11ea-9f3e-a6594028c545.png)

quick questions:
**1- Do you have any input on how to disable the tasks->"Refresh Movie".  Ive done both the Interval and the "LastExecution + 100 years" changes to the nzbdron.db file (both while radarr running, and while its fully shutdown)  and any time i restart radarr it reverts back to 1 day (and/or continues to run).  however before radarr restart the web gui does properly reflect the db changes i make (so restart is reseting it - see below pls) ** 

**2- how unstable (or stable) has v3.x aphrodite been for you / others?  (at this time i dont have an easy way to snapshot all of my pools to test it, unfortunately)**

thank you!

![image](https://user-images.githubusercontent.com/60830628/87858652-0e427300-c8f5-11ea-8498-5f9503a3dfa3.png)
![image](https://user-images.githubusercontent.com/60830628/87858658-1a2e3500-c8f5-11ea-8e08-cf492bf434f6.png)
keeps reverting on restart :(

**Comment by Qstick** [comment]
I wouldn't call it very-unstable, I think we've graduated to just unstable. 

Modifying the scheduled task table will do nothing, you must set the movie last refresh times to future if you want to do the DB route

**Comment by bob454522** [comment]
Thanks Qstick,  
i actually did set it to 2050 (year) and it properly showed in the web gui "next execution" in 30 years and wasnt running. 

However today (about 2 days later, i log in to see that is has again reverted, and actually reverted yesterday as it shows last execution was "a day ago"
(db also shows last run took 23hours :( 

any ideas?  also does yours still remain off even now (or even though the forced updates?)

thanks

**Comment by Qstick** [comment]
I don't set mine like that, I run v3 with scanning after refresh off... my average daily refresh is 2 minutes 30 seconds

**Comment by bob454522** [comment]
I see,  well i may consider trying out v3 (maybe via a vm snapshot, and zfs manual snapshot to cover potential issues).

that said-  i can say for sure, that even setting Refresh Movie (on v2) to a 20yr + future "Next Execution date" via db, no longer works.  as i did this again yesterday morning, and today when i checked it,  it has again reverted (and shows:)

![image](https://user-images.githubusercontent.com/60830628/88413279-851db700-cda0-11ea-86b6-cae2127bf62a.png)

Its ridiculous that i have two choices;  
1- Upgrade to alpha-ware that could effect a collection ive spent alot of time on
or 
2- live with v2 (which is great! btw, but for my massive disk array being constantly thrashed / IO slammed ~ 20 hours a day.
(all over a setting that is being forced upon us, and could very easily be changed to allow for user control)

**Comment by Qstick** [comment]
Option 3. Use couchpotato until you feel comfortable using Radarr V3. (We have 5-8k users using it as their daily driver and are close to beta)

There are always choices.

**Comment by Kru83** [comment]
> @Qstick - i couldnt find that option at all, but now i see that there is a alpha release of radarr v3 (Aphrodite) , so some of this makes a bit of sense now. I assumed i was on the latest Radarr (v0.2.0.1504 - "pre-Release") since it auto updates and im on the "develop" Branch. but i now see im on v2.x and there is a v3.x "Branch: aphrodite (very-unstable)" -
> As i have a massive movie library im a bit concerned on moving to v3.x ("very-unstable").
> ![image](https://user-images.githubusercontent.com/60830628/87858571-6dec4e80-c8f4-11ea-9f3e-a6594028c545.png)
> 
> quick questions:
> **1- Do you have any input on how to disable the tasks->"Refresh Movie". Ive done both the Interval and the "LastExecution + 100 years" changes to the nzbdron.db file (both while radarr running, and while its fully shutdown) and any time i restart radarr it reverts back to 1 day (and/or continues to run). however before radarr restart the web gui does properly reflect the db changes i make (so restart is reseting it - see below pls) **
> 
> **2- how unstable (or stable) has v3.x aphrodite been for you / others? (at this time i dont have an easy way to snapshot all of my pools to test it, unfortunately)**
> 
> thank you!
> 
> ![image](https://user-images.githubusercontent.com/60830628/87858652-0e427300-c8f5-11ea-8498-5f9503a3dfa3.png)
> ![image](https://user-images.githubusercontent.com/60830628/87858658-1a2e3500-c8f5-11ea-8e08-cf492bf434f6.png)
> keeps reverting on restart :(

Try this start up script.

https://discourse.linuxserver.io/t/script-after-container-start-to-disable-daily-refresh/1361

**Comment by bakerboy448** [comment]
https://wiki.servarr.com/Radarr_FAQ#Can_I_disable_the_refresh_movies_task

**Comment by Qstick** [comment]
@Kru83 Yep V3 is stable, use it. We've got people with 100k+ that don't have issues with this task on v3....

**Comment by Kru83** [comment]
> @Kru83 Yep V3 is stable, use it. We've got people with 100k+ that don't have issues with this task on v3....

yes,  Just found out about the new setting in the V3.
