### ISSUE TITLE
Un-hide an entry for the 'Add Movie' section

### ISSUE THREAD

**Issue by dalgibbard** [Radarr/Radarr#1827]
Radarr Version: 0.2.0.778

Hi all,
Having a bit of a moment; I've accidentally clicked on 'hide' for one of the listed movies when performing a search in the 'Add Movie' section -- how to I un-hide it? :)
I had a look around documentation (FAQ etc) and couldn't find anything.

Thanks in advance!

**Comment by galli-leo** [comment]
Ah, that's currently not implemented I think. Try looking under Settings > Lists > Import exclusions for the movie. Maybe there is an x next to it?

**Comment by galli-leo** [comment]
Yeah there you can unhide movies :)

**Comment by dalgibbard** [comment]
Yeap, perfect thanks! Sorry for the stupid question :)

**Comment by galli-leo** [comment]
No problem, should prolly be marked better
