### ISSUE TITLE
[Feature Request]  Option to blacklist and remove releases that failed import

### ISSUE THREAD

**Issue by ghost** [Radarr/Radarr#1828]
Option to blacklist and remove releases that failed importing.

Bonus option: choose what errors on import you want to blacklist on

**Comment by cornuwel** [comment]
With the recent flood of encrypted releases, this option is starting to sound very good.
Cleaning up the "No files found are eligible for import..." every day is pretty annoying.

**Comment by Qstick** [comment]
Available in v3
