### ISSUE TITLE
Bulk Edit of movies created by List

### ISSUE THREAD

**Issue by stempest** [Radarr/Radarr#1830]
I have setup a number of Trakt lists and all the movies have imported with a static path of:

c:\windows\system32\(Movie Name)

And also all are set to unmonitored

Is there a way I can bulk update to monitored and change the path to the correct path and set it to not static?

When I added the trakt lists i had chosen a UNC path but i still goes to the c:\windows path so not sure what is happening there.

When the movies download I have the download client/drone setting set and it seems to delete the moves as they are not in the c:\windows\system32 folder at all and are not in the UNC path where they should be.

Any advice would be appreciated.

Cheers

Steve

**Description:**

Check first that your problem is not listed in our wiki section:
* https://github.com/Radarr/Radarr/wiki/Common-Problems
* https://github.com/Radarr/Radarr/wiki/FAQ

Provide a description of the feature request or bug here, the more details the better. 
Please also try to include the following if you are reporting a bug

**Radarr Version:**

**Logs:**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by galli-leo** [comment]
Try sorting in movie editor by path :)

**Comment by galli-leo** [comment]
And yeah, the wrong path issue is fixed on latest nightly. Or on develop if you are using safari or edge.
