### ISSUE TITLE
mac os sierra wont work

### ISSUE THREAD

**Issue by paulelder** [Radarr/Radarr#1831]
**Description:**
Hi 

I hope i am posting in  the correct section i have a mac running os sierra 10.12.5
running Radarr version  0.2.0.778, It has been working fine but now no matter what i do it wont connect to the local host, I dont have logs as I cant access Radarr. I also have sonarr as well and that is working fine, any pointers would be appreciated Check first that your problem 
*

**Comment by galli-leo** [comment]
Try looking at the log files under your appdata directory: https://github.com/Radarr/Radarr/wiki/AppData-Directory#os-x

**Comment by paulelder** [comment]
[radarr.txt](https://github.com/Radarr/Radarr/files/1176517/radarr.txt)
Hi I have attached the file I am not sure what to look for it looks like it has failed, is there anyway to just delete it and start again. I have tried but it does not seem to work, I have sonarr as well and that is working fine

**Comment by paulelder** [comment]
i followed the link and i deleted the folder and reinstalled and its working again, thanks for that. I will keep that handy just in case

**Comment by galli-leo** [comment]
Good to hear you sorted it out :)
