### ISSUE TITLE
Removing movie from disk should remove it alltogether

### ISSUE THREAD

**Issue by webbson** [Radarr/Radarr#1832]
When I'm done with movies I often remove them if I don't think I want to re-watch them later.

However, removing them causes them to stay in Radarr as Missing & Unmonitored, I would like them to disappear from Radarr completely to get rid of unnecessary clutter in the UI. 
There should be a checkbox to allow for this to be done.

**Comment by hotio** [comment]
https://github.com/Radarr/Radarr/pull/1413
