### ISSUE TITLE
Invalid request Validation failed:   -- Either 'Must contain' or 'Must not contain' is required

### ISSUE THREAD

**Issue by myfrontpocket** [Radarr/Radarr#1834]
Radarr 0.2.0.778. Adding a Restriction with just "Must not contain" filled in results in the above warning being logged. However, it seems as though it's still saved.

**Comment by galli-leo** [comment]
Can you post the full error? I am not able to reproduce this :/

**Comment by myfrontpocket** [comment]
NzbDroneErrorPipeline	Invalid request Validation failed: -- Either 'Must contain' or 'Must not contain' is required

I can reproduce it if I delete it, and then read from a clean slate.

**Comment by galli-leo** [comment]
What browser are you using?

**Comment by myfrontpocket** [comment]
Chrome Beta on my Nexus 6P. I haven't tried an actual desktop yet.

**Comment by myfrontpocket** [comment]
and then recreate*
