### ISSUE TITLE
Not picking up rarbg RSS (but Usenet workign)

### ISSUE THREAD

**Issue by nicopolous** [Radarr/Radarr#1838]
Hi.  I have had a movie in my list for a long time.  Set to Physical Release with a small delay.  I have both Usenet and rarbg as indexers. Usenet preferred, but both Usenet and rarbg indexers all live and working fine.

My profile is set up to get BluRay and REMUX with REMUX as the cutoff.

A recent movie was picked up by Radarr and downloaded through Usenet in 1080p BluRay format.  However, there is a REMUX version available on rarbg which it didn't get - and it appears (without an exclamation mark) in the search results.  Also, in the search results, it shows that the rarbg release is very recent.

I don't understand why it wasn't picked up and downloaded.  The movie now appears in my "Cutoff Unmet" list, so Radarr knows it hasn't got the best quality.

Any ideas?  Is it possible that the rarbg release WAS posted to the RSS feed, but at the time Radarr didn't consider it released, and therefore ignored it.  Then by the time Radarr considered it released, it was no longer in the RSS feed (as it contains only the last 100 releases).  

**Radarr Version:**  0.2.0.778

**Logs:**  The log only shows the NZB RSS release being picked up.

**Comment by galli-leo** [comment]
When was the rarbg release posted? And what is the physical release date of the movie? Also try searching the logs if rargb had an error. They might have had their servers down.

**Comment by nicopolous** [comment]
Thanks for replying so quickly 

I couldn't see any errors in the logs for rarbg, but I know their servers go down so I agree that could have been it.

The physical release date was today (the issue above occurred yesterday, as expected because I have a -(minus) 2 day availability delay set up.

In terms of expected behaviour, I’m a bit confused how RSS works with the availability delay.  Say, for example, there is only one release on rarbg.  My understanding is that it would appear on the RSS feed fairly briefly because the feed only shows the latest 100 releases.  What happens if it is on the RSS feed BEFORE Radarr considers it “released”?

**Comment by galli-leo** [comment]
As you correctly assumed, it won't be downloaded. However, seeing as with the delay, Radarr should consider it available since two days ago, it should have downloaded it. Maybe the seed count was 0 while the release was on the Rss feed?

**Comment by nicopolous** [comment]
Thanks for the info - that clears it up nicely for me :)  Solution - make the availability delay a much bigger negative number to avoid missing the RSS.

**Comment by galli-leo** [comment]
Cool. Will close the issue for now. Let us know if it happens again :)
