### ISSUE TITLE
.

### ISSUE THREAD

**Issue by super94i** [Radarr/Radarr#1839]
.

**Comment by galli-leo** [comment]
It would probably be easiest if you asked the indexers that the primary Audio Language must be included in the release name.

**Comment by super94i** [comment]
@galli-leo that option is not there.. 

I'm using Jackett + Torznab

**Comment by super94i** [comment]
I can avoid this issue, since mostly the torrents less 20 seeders are the Russian ones. But I can't seem to save the minimum seeders for each indexer. I can't find it in ".config/Radarr/" either..

**Comment by super94i** [comment]
Hey, Could you please delete this issue? I would really appreciate it!

**Comment by galli-leo** [comment]
Cannot delete issues as far as I know
