### ISSUE TITLE
Random movies listed that don't exist

### ISSUE THREAD

**Issue by BurningTheSky** [Radarr/Radarr#1841]
I'm not sure what happened but I think it is to do with adding lists. I currently have a load of movies listed in Radarr that don't actually exist. While my movies are all in /nfs/media/etc/etc/ if I go into movie editor the erroneous movies all show as being at root, e.g. /Film Title, which doesn't exist.

How can I clear these out? I am looking at the mass deletion method and wondering if the seq command can be used to filter any that don't have path: '/nfs? Or am I going to have to do it manually?

**Comment by galli-leo** [comment]
You have been hit by the #1420 bug. This is fixed on the latest nightly, but I would suggest editing the paths via the movie editor. Try sorting by path, so that all the wrong paths are grouped together.

**Comment by BurningTheSky** [comment]
I don't want to edit, I want to delete as they are a bunch of random movies I don't want. I can't edit from the movie editor can I?

**Comment by galli-leo** [comment]
No you currently can't. I should have that feature ready for the next develop release.

**Comment by BurningTheSky** [comment]
Ok, is there a way I can get their IDs to use the mass delete method to remove them in the mean time?

**Comment by galli-leo** [comment]
Probably with a bash or python script, by getting all movies and getting ids without /nfs in the path.
