### ISSUE TITLE
{RELEASE.GROUP} not naming files properly

### ISSUE THREAD

**Issue by desimaniac** [Radarr/Radarr#1844]
**Description:**

I have tried different variations of the release tag and I like the all caps one with a dot in the middle, since it actually does name it in all caps, but unfortunately, it is naming it just RADARR or MOVIENAME as the release group.

**Radarr Version:** 0.2.0.778 (Mono 5.0.1.1)

**Logs:**
https://gist.github.com/desimaniac/57ffcf10aca4b4f4b783e1a1e4a0c19a

---

**Update:** 
I cleared the logs and tested same movie download with {Release.Group} tag and same issue. 

**Logs:** 
https://gist.github.com/desimaniac/67363c5968900576ada836a34c34f8da

**Comment by galli-leo** [comment]
The problem is the filename. Radarr takes the last -word as the release group, but also considers the movie folder and movie filename so it thinks -armageddon is the release group.

**Comment by desimaniac** [comment]
I think it got the release group fine until it started looking at the sample file and changed the reasee group to Armageddon.

**Comment by galli-leo** [comment]
@desimaniac Nah, the sample file has nothing to do with that.

**Comment by DesktopMan** [comment]
Same issue here, would also prefer an option to read all information from the folder name. Doesn't it already do that for the other fields?

**Comment by joaomconde** [comment]
same issue
