### ISSUE TITLE
Indexer is disabled when Rarbg returns "Invalid imdb"

### ISSUE THREAD

**Issue by phil-lavin** [Radarr/Radarr#1845]
**Description:**

I have 2 indexers (Rarbg and Nyaa). If I "Search All" on the Wanted page, it starts to work through missing movies. If it hits a movie which Rarbg says is "Invalid IMDB", Rarbg seems to be disabled and not used for future searches. The only way I seem to be able to get it to work again is to delete the indexer and re-add it. A Radarr restart doesn't seem to sort it.

See in the below logs it goes from searching 2 indexers to searching 1 indexer after the error.

**Radarr Version:**

```
Version
0.2.0.795
Mono Version
5.0.1.1 (2017-02/5077205 Thu May 25 09:19:47 UTC 2017)
```

**Logs:**

```
17-7-29 14:16:46.1|Info|NzbSearchService|Searching 2 indexers for [War and Games]
17-7-29 14:16:47.5|Warn|Rarbg|Indexer API call returned error 9: Invalid imdb - https://torrentapi.org/pubapi_v2.php?mode=search&search_imdb=&ranked=0&category=movies&limit=100&token=(removed)&format=json_extended&app_id=Radarr

[v0.2.0.795] NzbDrone.Core.Indexers.Exceptions.IndexerException: Indexer API call returned error 9: Invalid imdb
  at NzbDrone.Core.Indexers.Rarbg.RarbgParser.ParseResponse (NzbDrone.Core.Indexers.IndexerResponse indexerResponse) [0x000e7] in <8dff63499f794620a2f78139e790800d>:0 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].FetchPage (NzbDrone.Core.Indexers.IndexerRequest request, NzbDrone.Core.Indexers.IParseIndexerResponse parser) [0x00008] in <8dff63499f794620a2f78139e790800d>:0 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].FetchReleases (NzbDrone.Core.Indexers.IndexerPageableRequestChain pageableRequestChain, System.Boolean isRecent) [0x0008e] in <8dff63499f794620a2f78139e790800d>:0 

17-7-29 14:16:47.5|Info|DownloadDecisionMaker|No results found
17-7-29 14:16:47.6|Info|NzbSearchService|Searching 1 indexers for [War Games: The Dead Code]
17-7-29 14:16:47.6|Info|DownloadDecisionMaker|No results found
17-7-29 14:16:47.6|Info|NzbSearchService|Searching 1 indexers for [War Horse]
17-7-29 14:16:47.6|Info|DownloadDecisionMaker|No results found
```

**Comment by MrKuba** [comment]
i seemed to hit the same issue, looks like the torrent api is not recognizing the imdb titles at all. manually using the api renders same error. looks like an issue with torrentapi

**Comment by phil-lavin** [comment]
I don't think the issue here is with torrentapi per se. The issue is that, if torrentapi doesn't recognise a title (whether it should recognise it or not is another matter), then Radarr disables the indexer.

**Comment by galli-leo** [comment]
IMO this is an error with the torrent api as the IMDB Id is fine, but Rargb just doesn’t know about it. In this case a 404 should be returned.
