### ISSUE TITLE
No icon in system tray on Windows

### ISSUE THREAD

**Issue by TwoLeaves** [Radarr/Radarr#1847]
Is it possible to get an icon to show up in the system tray in Windows? With Sonarr, I can do this by running the executable directly (as opposed to the Windows service) with the "/icon" flag. This doesn't seem to work with Radarr however. Cheers.

**Comment by galli-leo** [comment]
It should by default. At least it does for me. Have you tried rebooting your machine?

**Comment by TwoLeaves** [comment]
Yes I have. I have tried running it as a system service as described on the
wiki. I have also tried making a shortcut to the executable and then
placing this shortcut in the Windows startup folder. In both cases the
program starts fine but no icon is present.

**Comment by zero77** [comment]
I am getting the same problem in Ubuntu Linux desktop.

**Comment by galli-leo** [comment]
@zero77 There is not system tray on linux?

**Comment by zero77** [comment]
@galli-leo I mean the linux system tray equivalent, some desktops have it along the top like GNOME and some on the bottom like KDE.

**Comment by galli-leo** [comment]
Interesting. Well Radarr only shows there for windows, as most linux systems don't have that.

**Comment by cmaart** [comment]
Still an issue

**Comment by MrGundum** [comment]
also experiencing this.

**Comment by eirek1234** [comment]
Still experiencing this as well. I've tried to reinstall, add as service, shortcut in start menu. I can get it to auto open on startup, but there is no icon if I close the tab.

**Comment by BUGBEAR7** [comment]
Having the same issue as well . 
Tried fresh reinstall (deleting the Program Data/Radarr folder) , put it in startup folder, nothing seems to work along with that I can not access it on any LAN computers . localhost:7878 seems to work even if tray icon is not running .

**Comment by igobythisname** [comment]
I've had this issue 2 times; what I've done to get the system tray icon back is I 'Shutdown' the program completely (go to System>Shutdown icon at the top right), wait for the program to shutdown, then re-open it. The system tray icon should appear. Very strange that this still needs to be done even if I reboot my computer, but at least there is some solution to the issue. Hope this helps!

**Comment by Digital-Trucker** [comment]
I'm having this issue constantly on a Windows 10 box.

**Comment by Neipas09** [comment]
I too am having this problem.
The Sonarr icon shows up with no issues when i reboot my PC, and when i check Task Manager i see Sonarr running in the Processes tab.

But to see Radarr, i have to expand the Nzbdrone and i see it as a sub-service.
I then have to kill it (Nzbdrone), and then run Radarr.exe, to get the systray icon to show up.

**Comment by mejico** [comment]
I'm having the same problem since upgrading to v 0.2.0.1480.  I have tried bouncing the service, uninstalling and reinstalling, stopping the nzbdrone and starting the exe, but none of this has fixed it.

**Comment by V3LPO** [comment]
Damn, is there really no fix for this in Windows 10?

**Comment by razordynamics** [comment]
Hello, I'd like to confirm this issue as well, I'm having it on Radarr and Sonarr. Shutting down the app via the System -> Shutdown option and then restarting it results in the icon showing in the tray again. On PC restart, Radarr and Sonarr are auto-launched as services however the tray icons do not appear.

Windows 10 Pro 64-bit 1909 (fresh install, build 18363.815), Radarr version 0.2.0.1480, Sonarr version 2.0.0.5344, SABnzbd 2.3.9.

**Comment by ta264** [comment]
Tray icon is not supposed to appear if run as a service, only if you run the tray app version
