### ISSUE TITLE
german skipped in nzbindexer

### ISSUE THREAD

**Issue by cschnack24** [Radarr/Radarr#1848]
I try to search NZBFinder.ws for a movie with german language and profile set to any 
(doesn't matter, which profile is set).
If I do it manually on their website the qualities (1080p) I want can be found easily.
Using NZBHydra, so api search, also no problem.

But if radarr has to search, automatically or manually it exclouds exactly these movies where "german" is in the name.

Am I doing anything wrong?

**Comment by galli-leo** [comment]
What do you mean by excludes? They don't show up or they show up with a red exclamation mark? (Manual Search). If it's the former, what search term are you using on your indexers site, if it's the latter, what does the red exclamation mark say?

**Comment by galli-leo** [comment]
Can you try searching "allied year", where you replace year with the imdb year of the movie? Because that is what radarr searches for.

**Comment by cschnack24** [comment]
makes no different, I can still see the german release in NZBHydra or on the website of the indexer.

**Comment by galli-leo** [comment]
Can you enable debug logging, search in Radarr and then post the debug logs here?

**Comment by cschnack24** [comment]
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/1191370/radarr.debug.txt)

**Comment by galli-leo** [comment]
What version of Radarr are you using?

**Comment by cschnack24** [comment]
0.2.0.778

**Comment by cschnack24** [comment]
any ideas?

**Comment by galli-leo** [comment]
Sorry was on holidays. Is the movie tagged with the correct imdbid on your indexer?

**Comment by cschnack24** [comment]
That's it, most of the german content is not tagged correctly. 
Is it possible to use radarr with not correctly tagged files?

**Comment by galli-leo** [comment]
Usually, yes, but since Radarr will search your indexer by imdbid, nothing much that it can do since your indexer will not return those movies :/ I want to add an option to search by movie title though.

**Comment by cschnack24** [comment]
Any idea when this function will be released?

**Comment by galli-leo** [comment]
No idea yet. Haven't started working on it.

**Comment by galli-leo** [comment]
This is in the latest release of Radarr now!
