### ISSUE TITLE
Mystery movies autodownloading

### ISSUE THREAD

**Issue by tmattoneill** [Radarr/Radarr#1849]
**Description:**
Radarr is downloading random movies and storing them (often many copies of the same film) in my download/incomplete/radarr directory. These aren't movies I've requested, they don't show up in my UI and there is no history of them in my SABNZB history. I also don't see any history of them in the Radarr 'History' section. However, I do see errors fired up in the Bug List.

This is what it looks like: http://imgur.com/a/xbiPU

**Radarr Version:**
Ver. 0.2.0.778

**Logs:**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by galli-leo** [comment]
Unfortunately you have been hit by this: #1717. not much we can do about that :/
