### ISSUE TITLE
Trakt List - Radarr move movies in root folder

### ISSUE THREAD

**Issue by Gromak123** [Radarr/Radarr#1851]
Hi,
I have the same issue than the issue #1800.
Im in the latest nightly, the list are saving my folder fine, but when it dowloand one release it's import in / and not in the folder i have previously set.
when i try to edit a list my folder are correctly set/save.

How can i solve this ? (i have already try do delete and re create list but same bug.)

Thank you.

**Comment by Gromak123** [comment]
for information i have the problem just whith the trakt list, with imdb or tmdb list it's work fine.

**Comment by galli-leo** [comment]
See https://github.com/Radarr/Radarr/wiki/Common-Problems#root-path-for-movies-imported-from-lists-becomes-cwindowssystem32-or-other-weird-paths for why it happens and how to solve it.
