### ISSUE TITLE
Unable to remove movie titles

### ISSUE THREAD

**Issue by suckmykiss182** [Radarr/Radarr#1852]
Hey! I'm having trouble deleting titles that are synced from the movie database for some reason. I had the lists set for popular, upcoming, etc and I have since turned them off. I have a lot of movie titles that were imported because of this -unmonitored- and now as I am trying to delete the ones I don't want, nothing happens. Any suggestions? On Mac OS Sierra.

**Radarr Version:** Newest version

**Comment by galli-leo** [comment]
How are you trying to delete them? Via the web ui?

**Comment by suckmykiss182** [comment]
Yes. I will be the first to admit that I am not ovelrytech savy, the back end stuff is over my head. But I've never had troubles deleting from the web UI.

I don't know if this helps, but the program started acting weird a few days ago and not loading, even after restarting. It kept giving me an error message. So yesterday I went to the radaar site and downloaded a new install, which allowed me to open it through local host 7878.

That's when I started noticing a bunch of movie titles that had imported that I do not want. I started deleting them, but I would say more than half of them it would not let me delete. I went into the lists and saw I had checked popular and new releases from the movie data base, so I deleted both of those lists, restarted radaar and proceeded to try to delete again. No dice. I click on delete and it just spins, it never deletes.

I also verified that none of these movies are on my IMDB watch list, which is synced with Radaar.

I restarted my computer, tried again, still doesn't delete. I went onto my hard drive and deleted all of the empty folders Radaar had created for the unwanted movies, restarted Raddaar, tried to delete, still no results. Went into settings and unchecked the option to create empty folders, hoping that would take care of it. Nope. :(

Went ahead and updated library, thinking since I had removed all of the empty folders off my hard drive that maybe it would sync them out of Radaar, but the only thing it did was put them all back.

I spent about 3 hours working on all of this yesterday and I am just at a complete loss. I LOVE LOVE LOVE LOVE the program, and I am so appreciative of all the work you have put into it and I will definitely continue to use it. 

I just need to figure out how to get delete these dang titles!

**Comment by galli-leo** [comment]
Can you try a different browser? And disabling adblock?

**Comment by suckmykiss182** [comment]
I normally use chrome and just tried it in Safari, still didn't work. Turned off add block on both browsers, also didn't work.

**Comment by suckmykiss182** [comment]
Any additional ideas? :(

**Comment by suckmykiss182** [comment]
I am still having this issue. Is there a way I can delete my whole library in Radarr and start over? It's really frustrating. :(

**Comment by galli-leo** [comment]
Sorry for not responding, I have been kinda busy the last few weeks :/ What version are you on? .778 or nightly? Also if you really want to start over, you can delete (I would suggest just renaming) ~/.config/Radarr/nzbdrone.db
