### ISSUE TITLE
No Result with Torrentpotato

### ISSUE THREAD

**Issue by se7ensinsman** [Radarr/Radarr#1853]
Hi everyone !
I’ve got the last version (0.7.1622) and I have no result with torrentpotato. the manual search is working and send me many results.
Here is the request sent by CP : http://127.0.0.1:9117/potato/torrent9?imdbid=tt4979860&user=&passkey=xxx
All my settings seem to be good with the API in passkey and the user leaved with a blank.
Any ideas ? Thanks for your help !
Benjamin

**Comment by galli-leo** [comment]
Seems like your issue occurs in Couchpotato? This Github is for Radarr, not CP. Anyways, because the free API for IMDB shutdown, Torrentpotato is kinda deprecated.
