### ISSUE TITLE
Bogus Copies Being Downloaded

### ISSUE THREAD

**Issue by dmods** [Radarr/Radarr#1854]
**Description:**

I have noticed with new movies malicious copies are being uploaded to various newsgroups and indexers. Usually it will be tagged as an HD or BluRay copy when the movie simply isn't available in that quality. They come with a bogus video file that doesn't play, a readme that says to install the codec if it doesn't play and an executable file in a codec folder. 

Obviously no one in their right mind would see this as legitimate and Radarr does a good job of not moving them into my media folder and sometimes deleting them and not re-downloading them.

That being said I would still prefer for them to not be downloaded period and for the malicious executables not never touch my server just in case. I may just not be aware of the options I have to mitigate this but is there a way to have Radarr exclude any copies or versions of a movie that contain an executable? Can I block or blacklist these bogus copies automatically or is detection for these copies something the dev team would consider adding? Can I do this some other way externally to Radarr if not?

Thanks for the help!

**Radarr Version:**

0.2.0.778

**Comment by weirdcrap** [comment]
What news reader do you use? 

NZBGET has an add on script that can detect these types of fake downloads as long as they are not double archived IIRC: https://github.com/nzbget/FakeDetector/blob/master/README.md

**Comment by jamesmacwhite** [comment]
Typically this down to the indexers/download client and not software like Radarr, as mentioned above. Clients like NZBGet and SABnzbd have configuration options available to prevent such malicious releases getting through, but even those aren't 100% bulletproof. Radarr is generally led by what indexers provide.

You do have a couple of options in Radarr to potentially mitigate though. 

* Set Radarr to only search on physical/web release, avoids the fakes long before any release
* Set minimum filesizes on the quality profiles to avoid such releases. 

If you wanted to go full out defensive, you could setup some form of policy on your file server which outright blocks .exe (or any other file extension) from being written to the share where your media is. How you achieve this is dependant on your server's OS.

**Comment by david-nedved** [comment]
Just thought I'd comment here for anyone who's come across this post from a Google Search - I've written a script to actually identify any such videos and flag for removal (you can setup to post-process within Radarr) - See: https://github.com/ultimate-pms/fake-video-detector

**Comment by jlim0930** [comment]
ned-kelly - GREAT WORK!

i got it installed and working however I am a bit confused on how to setup the post-process within Radarr.  I know its under connect in the settings and will most likely need a shell script but do you have any screenshots or examples ?

> 
> 
> Just thought I'd comment here for anyone who's come across this post from a Google Search - I've written a script to actually identify any such videos and flag for removal (you can setup to post-process within Radarr) - See: https://github.com/ultimate-pms/fake-video-detector
