### ISSUE TITLE
Manual Import Issues

### ISSUE THREAD

**Issue by evakq8r** [Radarr/Radarr#1855]
**Description: Unable to complete updates to some movies within Radarr**

**Radarr Version: 0.2.0.778 (develop)**

I'm having weird issues trying to complete mass updates in my movie library. I've recently imported ~20 movies from another file path that Radarr doesn't usually interact with (but is on the same server as the Radarr installation), and I'm now trying to update those movies attributes via Movie Editor (ie. Monitored Status, Min Availability, Profile, Static Path, Root Folder).

For some reason, the movies being selected in the Movie Editor are not being treated correctly. 

These are some of the movies I'm trying to process. When I select them, I am unable to update the values listed above until I select a movie that's already processed and working fine. IE:

Selecting only the ones I want to edit:

![image](https://user-images.githubusercontent.com/14250328/28835261-f51c3ad0-7723-11e7-9e87-e21de3dc0a73.png)

Including one that is already processed:

![image](https://user-images.githubusercontent.com/14250328/28835217-c7d0d734-7723-11e7-96dd-61ee713c8ead.png)

It now recognises that multiple movies are selected, BUT when I update the values to what I want them to be and press Save, nothing happens - no narrations in the logs, nada. If I try one at a time, the 'x movies selected' counter does not go up; this remains at 0 until I select a movie from the file path with other movies already processed.

I'm at a loss as to what's causing this... is the different file paths not playing nice? Or is it just something that can't be done/I'm doing wrong?

Any help would be appreciated. TIA

**Comment by evakq8r** [comment]
bump

**Comment by galli-leo** [comment]
Did you solve this? Or why did you close?

**Comment by evakq8r** [comment]
I closed it as I don't think it's an issue yet can be fixed. It seems Radarr has a limit of how many items it can update in its database at the same time, as I can update up to 10 at a time, but after that it stops responding and nothing works properly without restarting the Radarr service.
