### ISSUE TITLE
Bulk Import Monitor setting works as global setting

### ISSUE THREAD

**Issue by squarefrog** [Radarr/Radarr#1858]
**Description:**

When bulk importing existing movies, the Monitor dropdown works as a global setting. For example I have two movies:

- Movie A
- Movie B

I want to monitor `Movie B` but not `Movie A`. I change `Movie B` to be monitored, and all other rows are updated to `monitored: yes`.

Additionally, the same behaviour is found when changing Profile settings.

**Workaround**
Perform two bulk import actions, to import the two movies.

**Environment**

Safari browser 10.1.2 client, Radarr host running on [linuxserver.io/docker-radarr](https://github.com/linuxserver/docker-radarr) Docker container.

**Radarr Version:**
0.2.0.778

Is this intended behaviour or a bug?

**Comment by galli-leo** [comment]
Yes that is the intended behaviour. If you have 1000 movies to import, you wouldn't want to set each one of them unmonitored?

**Comment by squarefrog** [comment]
Ok but what if you didn't want all of them monitored. Suppose out of those 1000 you don't want to monitor 50?

Why not a global drop down then per movie overrides.

**Comment by galli-leo** [comment]
You can just not select those, import the ones selected, change monitored, select the 50 and import them.

**Comment by squarefrog** [comment]
Sure, I understand that, I was just trying to suggest a more elegant solution.
