### ISSUE TITLE
Radarr not Blacklisting failed released

### ISSUE THREAD

**Issue by danielrw89** [Radarr/Radarr#186]
Radarr doesn't seem to be correctly blacklisting failed downloads with Sabnzbd

See the below where it is constantly retrying the same release. 
https://i.imgur.com/omZUKun.png

I've tried manually marking the release as failed - but this also doesn't stop it.

**Comment by scalda** [comment]
Blacklisting isn't implemented yet

**Comment by julestop** [comment]
FYI - Also happening in NZBGet with me.

**Comment by thaiceman** [comment]
Who do I need to bribe to get the blacklist working :P just had to kill a download that has tried all day long to download lol.

**Comment by danielrw89** [comment]
Mine seems to be working to some degree in the newest release - downloads that fail are being skipped over automatically - at least on my linux server - haven't tested the windows one lately.
This all happened automatically 
https://i.imgur.com/9XpJbas.png

**Comment by julestop** [comment]
Oh wow!!! Stoked to try and see if it works on mine!
Yeah, I would consider this a high priority as well thaiceman.

**Comment by galli-leo** [comment]
Fixed in latest release

**Comment by julestop** [comment]
Awesome!! This is big for me!
