### ISSUE TITLE
HD4Free.xyz torznab preset doesn't work

### ISSUE THREAD

**Issue by BattleKat** [Radarr/Radarr#1860]
The same preset with identical credentials works with Sonarr, not Radarr.

Radarr Ver. 0.2.0.795
Mono: 5.0.1.1 (2017-02/5077205 Thu May 25 09:19:18 UTC 2017)
Log:
```
17-8-2 15:43:19.2|Warn|Torznab|Unable to connect to indexer

[v0.2.0.795] System.InvalidOperationException: Sequence contains no elements
  at System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00010] in <26aedeede9534b948c539f8734c8492d>:0 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].TestConnection () [0x0000e] in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:325 

17-8-2 15:43:19.2|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Unable to connect to indexer, check the log for more details
```
Saw it mentioned on reddit and I've replicated with same result

**Comment by galli-leo** [comment]
Probably because the Indexer does not support movie search. Either ask them to enable searching by imdbid or disable both searching and RSS, add the Indexer and then reenable both searching and RSS

**Comment by BattleKat** [comment]
Thanks for the quick response You are right.  I was messing with the torznab api and read **=caps** gives you the categories. No Movie support, which is very odd considering it's a gold mine of content and home of a very popular quality focused encoding group, which would be ideal use for Radarr to upgrade releases. It does support imdbid. I'm very new there but will ask around and see what their stance is.

````
<caps>
<server appversion="1.0" version="0.1" title="HD4Free" strapline="HD4Free Torznab API" email="info@hd4free.xyz" url="https://hd4free.xyz" image="https://hd4free.xyz/favicon.ico"/>
<limits max="100" default="100"/>
<registration available="yes" open="no"/>
<searching>
<search available="yes"/>
<tv-search available="yes"/>
<movie-search available="no"/>
</searching>
<categories>
<category id="5000" name="TV">
<subcat id="5040" name="TV HD"/>
</category>
</categories>
</caps>
````

**Comment by Baraddon** [comment]
You can use Jackett for movies with HD4Free. It works fine with me. Sonarr works fine with the preset.
