### ISSUE TITLE
Downloading HC titles eventhough turned off in settigns

### ISSUE THREAD

**Issue by Keeperjoey** [Radarr/Radarr#1864]
**Description:**

Download any file that only has HC titles available and it wont ignore them

**Radarr Version:**

0.2.0.778

**Logs:**

https://pastebin.com/crAG56YR

**Comment by galli-leo** [comment]
As per discord discussion: en is whitelisted as Tag, which is also contained in our "Generic Hardcoded Subs" for HC releases. Thus the release is whitelisted.
