### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by Cybermunk** [Radarr/Radarr#1865]
Hi.

My search always comes up empty.

I have tested both trackers with success.

I use cardigann with piratebay and kickass torrents.

When i do a manual search on each of the torrentsites theres plenty of results.

They both worked 1 month ago, and i have changed nothing, and everything is up to date.

Any way to fix this?

**Comment by hotio** [comment]
Use jackett

**Comment by galli-leo** [comment]
Yup, unfortunately cardigann is outdated. (Also some logs would be helpful)

**Comment by hotio** [comment]
Don't worry @galli-leo , he tested both trackers with success, uses no longer maintained software and forgot to read the entire piece of text before deleting it when creating the issue.

So logically it must be a radarr bug... no? Does my logic fail?

I have some serious respect for you @galli-leo , that you can keep your head cool and stay so polite, when around 80% of all reported issues, is utter bullshit and stupidity. RESPECT.
