### ISSUE TITLE
Failed to map movie, if title contains "Special"

### ISSUE THREAD

**Issue by DooPlex** [Radarr/Radarr#1867]
Minor issue: tried to download "Midnight Special (2016)" but radarr failed to map movie name, found only "Midnight", because taught that the release type is "Special"

**Radarr Version:**
Radarr Version
0.2.0.778
Mono Version
5.0.1.1

**Logs:**
Was looking for 720p ENG, this match would be good, but rejected:

17-8-4 02:32:28.5|Debug|Parser|Parsing string 'Midnight.Special.2016.720p.BluRay.x264-GECKOS'
17-8-4 02:32:28.5|Debug|Parser|Movie Parsed. Midnight - 2016
17-8-4 02:32:28.5|Debug|Parser|Language parsed: English
17-8-4 02:32:28.5|Debug|QualityParser|Trying to parse quality for Midnight.Special.2016.720p.BluRay.x264-GECKOS
17-8-4 02:32:28.5|Debug|Parser|Quality parsed: Bluray-720p v1
17-8-4 02:32:28.5|Debug|Parser|Release Group parsed: GECKOS
17-8-4 02:32:28.5|Debug|ParsingService|No matching movie Midnight
17-8-4 02:32:28.5|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] Failed to map movie, found title Midnight, expected one of: Midnight Special, Midnight Special17-8-4 02:32:28.5|Debug|Parser|Parsing string 'Midnight.Special.2016.BDRip.x264-GECKOS'

**Comment by Qstick** [comment]
Same problem as #1676 edition regex and first parse regex are causing the issue
