### ISSUE TITLE
Movie Filters Sometimes Fail on Navigation

### ISSUE THREAD

**Issue by Qw-in** [Radarr/Radarr#1868]
**Description:**
Sometimes when navigating to the `movies` view the `missing` filter will appear to be applied but will show all the movies in Radarr instead. Only tested on `missing` filter but may apply to more. See gif

<img src="https://i.gyazo.com/c4e146d02bb643bd1082cc0a12b880a9.gif" />

**Radarr Version:**
0.2.0.778 / 5.0.1.1

**Logs**
Can provide if needed

**Comment by galli-leo** [comment]
Can you try a different browser? Also try opening the chrome dev console, going to the network tab and posting a screenshot of that, after you go back to the movies view.

**Comment by Qw-in** [comment]
It seems to have been an issue with something cached in my browser. Clearing storage seems to have fixed it. Before that I was getting a strange backbone error which made no sense as I couldn't reproduce it in Firefox or incognito
