### ISSUE TITLE
Trakt List setting does not store folder

### ISSUE THREAD

**Issue by DataBitz** [Radarr/Radarr#1869]
When adding Trakt list, then selecting a preferred folder. The folder setting is not retained when opening the list to view the settings.
When movies are added as wanted they are added without a folder path.

Radarr Version: 0.2.0.778

**Comment by TheRealShiz** [comment]
Appears to be the case with TMDB lists as well

**Comment by galli-leo** [comment]
This is fixed on the latest nightly (or when using Safari or edge).
