### ISSUE TITLE
IMDB Movie List Import Support

### ISSUE THREAD

**Issue by markhaines** [Radarr/Radarr#187]
Would be great if Radarr could replicate the Couch feature to regularly poll a user's public IMDB movie watchlist and automatically add these movies to the 'wanted' list.

As well as being an easy way to add new movies it also acts as a sort of backup.  If I were to lose all my movies due to disk failure I can just reinstall Radarr, point it at IMDB and it can go and hunt them down again.

**Comment by Mirabis** [comment]
When considering this request,would it be possible to add a few extra otions?

- Only download current (or X configurable) years movies. This helps when you use a watchlist to automate downloading but don't want it to backfill movies from 2014 still on your list.

**Comment by galli-leo** [comment]
Duplicate of #139. Please move your discussion to there.
