### ISSUE TITLE
Unable to access the Radarr web gui even localhost.

### ISSUE THREAD

**Issue by ksbansal** [Radarr/Radarr#1871]
**Description:**

Check first that your problem is not listed in our wiki section:
* https://github.com/Radarr/Radarr/wiki/Common-Problems
* https://github.com/Radarr/Radarr/wiki/FAQ

Provide a description of the feature request or bug here, the more details the better. 
Please also try to include the following if you are reporting a bug

**Radarr Version:**
Pre-Release v0.2.0.778
**Logs:**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

When trying to access the radarr web gui i get the following page:

{
  "message": "NotFound"
}

I am unable to acess my instance of radarr from any page. I always get the above text.

**Comment by evanrich** [comment]
you might want to post helpful info such as...OS, debug logs, etc if you want anyone to try and help @ksbansal

**Comment by hotio** [comment]
Where is the proof for being called a bug? Did you try in an incognito window? If you wanna throw big words around, at least give some evidence to back your bold claims. Saves you the embaresment later on...

**Comment by ksbansal** [comment]
Sorry I meant no offence.
My server is running on windows 7 and as for the logs, where can I access them? Also would they include any sensitive information?

**Comment by hotio** [comment]
As far as I know the log does not contain your social security number.

**Comment by ksbansal** [comment]
@hotio Haha your funny.

Here are my logs:
https://drive.google.com/open?id=0B5_pV-tEMUmMemlIR19IbUhhOE0

As I said previously stated I'm running Windows 7.

Here is a similar issue which occurred on Sonarr:
https://forums.sonarr.tv/t/message-notfound-error-after-upgrade-to-develop/3481

**Comment by hotio** [comment]
You already tried an incognito windows?

**Comment by hotio** [comment]
Does the file exist? Has radarr permissions?

`17-8-9 18:31:34.5|Warn|LoginHtmlMapper|File C:\ProgramData\Radarr\Bin\UI\login.html not found`

**Comment by ksbansal** [comment]
@hotio yes incognito produces the same results. I also had a look at the logs and the problem seems to be that the login.html file isn't being picked up by Radarr.

This line is in the logs at the end:
17-8-9 18:31:34.5|Warn|LoginHtmlMapper|File C:\ProgramData\Radarr\Bin\UI\login.html not found
and the file does exist in that path

**Comment by ksbansal** [comment]
@hotio sorry didn't see your message lol.

**Comment by hotio** [comment]
9/10 another permissions issue

**Comment by ksbansal** [comment]
@hotio any ideas on how i can fix this issue?

**Comment by jamesmacwhite** [comment]
So recap. Radarr appears to be at least "running", given the JSON message not found error is returned.

As hotio as referenced, its likely a permissions issue on the folder where Radarr has installed to. Make sure the user you run Radarr under has appropriate access to both the AppData and Startup directory. To confirm this, have you checked to see if `C:\ProgramData\Radarr\Bin\UI\login.html` exists on the filesystem? If it does, its more than likely a permissions issue. If it doesn't, you've got a borked install.

**Comment by ksbansal** [comment]
@jamesmacwhite the login.html file does exist. I have installed radarr as admin meaning the right permissions should be there?
What I find odd is if I install Radarr as a service it runs fine, but as I am using an external NAS for my movies I don't have a choice but to run Radarr as a standard program.

**Comment by jamesmacwhite** [comment]
Permissions issue for sure then.

Whatever user you ran the installer under should have the ability to run Radarr accordingly.

The Radarr service is run under the LocalSystem Account by default. You can modify the user the service runs under if needed. Some Windows based setups have to if they require Radarr to have network access to local network shares. This is because the LocalSystem Account does not provide anonymous network access.

**Comment by ksbansal** [comment]
I figured out what it was.
<SslCertHash></SslCertHash>
The line above was added to config.xml. Removing it fixed the issue.
