### ISSUE TITLE
Pre-Release v0.2.0.778 on Mac shows Sonarr

### ISSUE THREAD

**Issue by desimaniac** [Radarr/Radarr#1877]
When you extract the app, it show's up as Sonarr. Inside the info.plist is incorrectly set to show Sonarr.

**Comment by jamesmacwhite** [comment]
This is already fixed in the latest nightly.

https://github.com/Radarr/Radarr/commit/668ef336fbeeb076d1edb19b28c1559d16ee4573

**Comment by desimaniac** [comment]
Oh ok. Thanks.

**Comment by jamesmacwhite** [comment]
No worries. Next release from develop branch will have the fix.
