### ISSUE TITLE
[feature] Movie rename ans metadata

### ISSUE THREAD

**Issue by Nibeck1309** [Radarr/Radarr#1878]
Hello all,

My Collection Movies are order in 

- Collection Movies directory (ex : /media/media/Films)
          - Movies Saga title directory (ex : Fast & Furious)
                        - Movie,the title_[years] directory (ex : Tokyio_Drift_[2002] )
                                      - Movie,the_[years] files (video file, nfo, img...) (Tokyio_Drift_[2002].mp4, Tokyio_Drift_[2002].nfo,etc...)
 
I don't found in Radarr how to rename patern for respect my video organsation.

and Have you any information when metadata are add ?

Have you a idea for this ?

thanks

**Comment by hotio** [comment]
At the moment you either adhere to how radarr likes to do it or don't use at all.

Metadata can take a while, nobody seems really interested in that feature, rightly so... It's not a vital part.

**Comment by galli-leo** [comment]
Currently you cannot add collections (though that's something which is planned). Also the naming scheme should be settable in the Media Management Settings.
