### ISSUE TITLE
S02E64 - erroneous movie import

### ISSUE THREAD

**Issue by alfablac** [Radarr/Radarr#1879]
**Description:**
Some files are being exported as Season 2 Episode 64 being unable to be properly parsed to the respective movie.
As far as I could test, only those name as H 264, H264 or H.264 are being wrongly imported.
Movies that have x 264, x264 or x.264 doesn't seem to have this problem.

**Radarr Version:**
0.2.0.778
**Logs:**
`17-8-7 11:22:15.0|Warn|ParsingService|Unable to parse movie info from path XXXX\The Farthest\Season 2\S02E64 - PreBS.mkv
`
File is: The.Farthest.2017.1080p.WEBRip.AAC2.0.H.264-PreBS

**Comment by hotio** [comment]
What are you trying to do? Radarr is for movies not tvshows.

**Comment by alfablac** [comment]
As I said, I tried to download the movie:
`The.Farthest.2017.1080p.WEBRip.AAC2.0.H.264-PreBS`

This occured on another WEB-DL that had H.264 on the filename.
Radarr proceeds to import it as The Farthest Season **2** Episode **64**, clearly indicating it's something with the codec tag.
I can't even manually import the file as a movie after Radarr tries to import it as S02E64.
I'm rather inclined to believe there's some Sonarr leftover on the code that is causing this.
