### ISSUE TITLE
Radarr wont move movie after download?

### ISSUE THREAD

**Issue by Gershy13** [Radarr/Radarr#1884]
What option do i have to select to move movie after download? And also remove from utorrent? I tried downloading a test movie, and it works perfectly, other than it wont remove it from utorrent and move it to my movies folder.
Any ideas?
Thanks Gershy13

**Comment by galli-leo** [comment]
Radarr won't remove files from utorrent, since that would prevent utorrent from seeding the torrent. You should set utorrent to remove the file & torrent once you are satisfied with your ratio.
