### ISSUE TITLE
Can't connect after IP address change

### ISSUE THREAD

**Issue by nuentes** [Radarr/Radarr#1885]
I installed a new DNS/DHCP server today, and so many of my devices are using new IP addresses. My NAS moved from 192.168.1.6 to 192.168.1.219, and I'm just trying to get all my services back online. I was having this exact same issue with headphones and nzbget, and I resolved it by changing the control IP in the config files and then rebooting my NAS. However, with Radarr, I found my URLBase field was blank when I pulled up the config.xml file. So I entered the new address anyway, and I still cannot pull up the page locally from the server, or from any remote devices. I really can't find any other config file I may need to edit for Radarr. Any ideas?

**Comment by hotio** [comment]
Urlbase is not for an ip adress.

**Comment by nuentes** [comment]
hm - perhaps I wasn't clear. I was unable to connect before changing UrlBase. That's the only reason why I made an attempt at changing the field. I'm quite clear that it wasn't the field I needed to change. I am looking for guidance on how to update the URL from 192.168.1.6 to 192.168.1.219, as I'm unable to connect to Radarr on the local device from:

192.168.1.6:7878
192.168.1.219:7878
localhost:7878
127.0.0.1:7878

And yes, I know that's the correct port.

**Comment by hotio** [comment]
As far as I can tell this has nothing to do with radarr...by default radarr binds to all available interfaces.

**Comment by jamesmacwhite** [comment]
What OS is Radarr running on?

You'll need to establish if Radarr is actually binding to any interface. You can do this via `netstat` but depending on the OS, the syntax for the command will differ. Let me know your OS.

**Comment by nuentes** [comment]
I'm running on ubuntu.

So it appears that Radarr simply wasn't opening at startup. I manually opened it, and now I'm in. Which is strange, since I swear that startup command was working before. So I suppose I need to look into why that is happening, but certainly not Radarr's fault or problem. Sorry, and thanks for the help!

**Comment by jamesmacwhite** [comment]
No worries, sometimes things appear like they are broken when its actually something else.

For future reference, if you wanted to confirm Radarr was actually binding to any interface, run something like:

```
netstat -plnt | grep ':7878
```

This will report if anything is bound to 7878 (Radarr's default port)
