### ISSUE TITLE
Movie search - no result because of bad release year

### ISSUE THREAD

**Issue by leloki** [Radarr/Radarr#1886]
Hi,

I have a pretty regular issue when to find some movies.
I use Radarr with Jackett and 3 different indexers.

If my indexers have the movie in their database with a different year no movie release will be found. I think this is due to the difference between imdb release year and the release year in different country (France for me). 
I have a example : 
Kingsman - Services Secrets, imdb release year 2014 but referenced in my indexers in 2015.
So no results at all in Radarr though the movie is found with manual search in Jackett with 2015 instead of 2014.

Could it possible ot edit the year for search movies or ignore it ? I do not know the best way.

Loki

**Radarr Version:**
Radarr Ver. 0.2.0.778
develop

**Comment by hotio** [comment]
Be patient, a solution is in the works...

**Comment by leloki** [comment]
oh yes ? What solution ? What do you know ? When the solution will be available you think ? Could I use something in between to help me ?
Thans for your answer.

**Comment by hotio** [comment]
Yes
Alternative titles
A lot
No ETA
No

**Comment by leloki** [comment]
LOL what an effective way to answer ! Thanks anyway, I hope this will arrive soon. :-)

**Comment by hotio** [comment]
![unknown 1](https://user-images.githubusercontent.com/26902309/29135141-6db3a58a-7d39-11e7-804d-3a8bf350fefa.png)
![unknown](https://user-images.githubusercontent.com/26902309/29135142-6dcbf8d8-7d39-11e7-9adc-1fa8d2c27fdd.png)

**Comment by galli-leo** [comment]
ETA: today when appveyor recovers.

**Comment by leloki** [comment]
that's really great guys that you take time to answer me. But sorry but I do not know what is appveyor.
And your screenshot hotio seems great but I can not edit or your site : https://mappings.radarr.video/movie/207703 (Loading....). 

My problem seems to be adressing in some point but could you explain it to me please ? I am sorry I am pretty new in the community and I apologize if I am asking some newbie question.

**Comment by galli-leo** [comment]
@leloki No problem (Not sure why the site is not loading, currently you cannot edit it anyways).

The poing being, from now on when the year does not match, you can force a download. Radarr will then add the year as a secondary year to the mappings website mentioned above. (You will need to upgrade to nightly for that feature though. It might be unstable).

**Comment by leloki** [comment]
@galli-leo Thanks for your response, sorry I just came back from holidays :)
I updated to nightly : 
Radarr Ver. 0.2.0.827
nightly
But I do not have (or find) the possibility to "force a download", how could I do that please in this version ?

**Comment by galli-leo** [comment]
@leloki Currently you can't. You could open an issue on https://github.com/Radarr/RadarrWEB.Mappings for that. However I added an option today, to omit the year from searches, so bad release years shouldn't be that big of a problem anymore.

**Comment by leloki** [comment]
thanks @galli-leo that should be great !
