### ISSUE TITLE
MediaInfo could not be loaded libmediainfo.so.0

### ISSUE THREAD

**Issue by raspdealer** [Radarr/Radarr#1887]
Hello,

I have this warning for the very first time in my Status tab.
MediaInfo could not be loaded libmediainfo.so.0

Can you please help me?

Version    0.2.0.778
Mono Version    5.0.1.1 (2017-02/5077205 Thu May 25 10:07:22 UTC 2017)

Thanks!

**Comment by hotio** [comment]
Install it

**Comment by raspdealer** [comment]
I never add to. Is that new? This is why all my new movies are detected as Sample?
Any installation recommendation?

**Comment by galli-leo** [comment]
apt-get install libmediainfo for example.

**Comment by raspdealer** [comment]
https://github.com/Sonarr/Sonarr/issues/1488

**Comment by raspdealer** [comment]
This change is related to a recent release because I never had it  before.
apt-get install libmediainfo0 solved it. Will be good to document changes like that.
Thanks.

**Comment by hotio** [comment]
There's nothing to document, it's a problem on your end.

**Comment by Gjhx** [comment]
Hello, 

I have the same problem on Qnap HS251+. 

How i can put the same command on ssh to install it ?

**Comment by fryfrog** [comment]
Google for "qnap mediainfo" and see what turns up.

**Comment by jwildman16** [comment]
How would one install libmediainfo0 to a macOS Radarr installation?
