### ISSUE TITLE
Radarr cannot see current downloads in qbittorrent (Activity page is empty).

### ISSUE THREAD

**Issue by mrangryoven** [Radarr/Radarr#1889]
**Description:**
So, i assume this issue may be known of but i cant see any other issues that are the same as mine.

The activity page is empty and there is movies being added to qbittorrent by Radarr.

It happened since I updated to the latest version of qbittorrent, however I cannot downgrade because Sonarr does not work with the older version as the qbittorrent API has changed.

Provide a description of the feature request or bug here, the more details the better. 
Please also try to include the following if you are reporting a bug

**Radarr Version:** 0.2.0.778

**Logs:** Not sure which log I need to attach.

**Comment by jamesmacwhite** [comment]
Possibly related, a recent API change  in qBittorrent meant the specific label designated in Radarr was not being added to torrents.

https://github.com/Radarr/Radarr/pull/1872

This has been implemented and fixed in the nightly.

**Comment by Qstick** [comment]
Should this be closed?
