### ISSUE TITLE
Won't delete old lower resolution video when a completed new one downloads

### ISSUE THREAD

**Issue by scalda** [Radarr/Radarr#189]
I had a newer 1080p version of angels in the outfield download last night but radarr didn't delete the old sd version of the film. below is the snippet of my debug log where it moves the file from my downloads folder and renames and such before it moves onto the next thing. If you want the trace log let me know and i will go through and find the correct one

> 17-1-12 00:44:46.6|Debug|DownloadedMovieImportService|Angels.in.the.Outfield.1994.1080p.WEBRip.x264-STARS-Chamele0n folder quality: WEBDL-1080p v1
17-1-12 00:44:46.6|Debug|DiskScanService|Scanning 'x:\Downloads\Movies\Angels.in.the.Outfield.1994.1080p.WEBRip.x264-STARS-Chamele0n' for video files
17-1-12 00:44:46.7|Debug|DiskScanService|1 video files were found in x:\Downloads\Movies\Angels.in.the.Outfield.1994.1080p.WEBRip.x264-STARS-Chamele0n
17-1-12 00:44:46.8|Debug|ImportDecisionMaker|Analyzing 1/1 files.
17-1-12 00:44:46.8|Debug|QualityParser|Trying to parse quality for x:\Downloads\Movies\Angels.in.the.Outfield.1994.1080p.WEBRip.x264-STARS-Chamele0n\a685f36fe130442d93f8de8f1a83e13c.mkv
17-1-12 00:44:46.9|Debug|QualityParser|Trying to parse quality for a685f36fe130442d93f8de8f1a83e13c.mkv
17-1-12 00:44:46.9|Debug|ImportDecisionMaker|Using quality from folder: WEBDL-1080p v1
17-1-12 00:44:46.9|Debug|ImportDecisionMaker|Size: 7463621444
17-1-12 00:44:46.9|Debug|VideoFileInfoReader|Getting media info from x:\Downloads\Movies\Angels.in.the.Outfield.1994.1080p.WEBRip.x264-STARS-Chamele0n\a685f36fe130442d93f8de8f1a83e13c.mkv
17-1-12 00:44:47.1|Debug|Parser|Parsing string 'Angels.in.the.Outfield.1994.1080p.WEBRip.x264-STARS-Chamele0n'
17-1-12 00:44:47.1|Debug|Parser|Episode Parsed. Angels in the Outfield - Season 01 
17-1-12 00:44:47.2|Debug|Parser|Language parsed: English
17-1-12 00:44:47.3|Debug|QualityParser|Trying to parse quality for Angels.in.the.Outfield.1994.1080p.WEBRip.x264-STARS-Chamele0n
17-1-12 00:44:47.3|Debug|Parser|Quality parsed: WEBDL-1080p v1
17-1-12 00:44:47.4|Debug|Parser|Release Group parsed: Chamele0n
17-1-12 00:44:47.4|Debug|VideoFileInfoReader|Getting media info from x:\Downloads\Movies\Angels.in.the.Outfield.1994.1080p.WEBRip.x264-STARS-Chamele0n\a685f36fe130442d93f8de8f1a83e13c.mkv
17-1-12 00:44:47.7|Debug|DetectSample|Runtime is over 90 seconds
17-1-12 00:44:47.8|Debug|ImportApprovedMovie|Decisions: 1
17-1-12 00:44:47.8|Debug|Parser|Parsing string 'Angels.in.the.Outfield.1994.1080p.WEBRip.x264-STARS-Chamele0n'
17-1-12 00:44:47.9|Debug|Parser|Episode Parsed. Angels in the Outfield - Season 01 
17-1-12 00:44:47.9|Debug|Parser|Language parsed: English
17-1-12 00:44:48.0|Debug|QualityParser|Trying to parse quality for Angels.in.the.Outfield.1994.1080p.WEBRip.x264-STARS-Chamele0n
17-1-12 00:44:48.0|Debug|Parser|Quality parsed: WEBDL-1080p v1
17-1-12 00:44:48.1|Debug|Parser|Release Group parsed: Chamele0n
17-1-12 00:44:48.2|Debug|MovieFileMovingService|Moving movie file: x:\Downloads\Movies\Angels.in.the.Outfield.1994.1080p.WEBRip.x264-STARS-Chamele0n\a685f36fe130442d93f8de8f1a83e13c.mkv to X:\Kids movies\Angels in the Outfield (1994)\Angels in the Outfield (1994).mkv
17-1-12 00:44:48.3|Debug|DiskTransferService|Move [x:\Downloads\Movies\Angels.in.the.Outfield.1994.1080p.WEBRip.x264-STARS-Chamele0n\a685f36fe130442d93f8de8f1a83e13c.mkv] > [X:\Kids movies\Angels in the Outfield (1994)\Angels in the Outfield (1994).mkv]
17-1-12 00:44:48.3|Debug|MediaFileAttributeService|Setting last write time on series folder: X:\Kids movies\Angels in the Outfield (1994)
17-1-12 00:44:48.3|Warn|MovieFileMovingService|Unable to set last write time
[v0.2.0.85] System.IO.IOException: The process cannot access the file 'X:\Kids movies\Angels in the Outfield (1994)' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.OpenHandle(String path)
   at System.IO.Directory.SetLastWriteTimeUtc(String path, DateTime lastWriteTimeUtc)
   at NzbDrone.Common.Disk.DiskProviderBase.FolderSetLastWriteTime(String path, DateTime dateTime) in C:\projects\radarr-usby1\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 242
   at NzbDrone.Core.MediaFiles.MediaFileAttributeService.SetFolderLastWriteTime(String path, DateTime time) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\MediaFileAttributeService.cs:line 75
   at NzbDrone.Core.MediaFiles.MovieFileMovingService.TransferFile(MovieFile movieFile, Movie movie, String destinationFilePath, TransferMode mode) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\MovieFileMovingService.cs:line 125
17-1-12 00:44:48.4|Debug|MovieService|Linking [Angels in the Outfield (1994).mkv] > [[tt0109127][Angels in the Outfield]]
17-1-12 00:44:48.5|Debug|DiskScanService|Scanning 'x:\Downloads\Movies\Angels.in.the.Outfield.1994.1080p.WEBRip.x264-STARS-Chamele0n' for video files
17-1-12 00:44:48.6|Debug|DiskScanService|0 video files were found in x:\Downloads\Movies\Angels.in.the.Outfield.1994.1080p.WEBRip.x264-STARS-Chamele0n
17-1-12 00:44:48.6|Debug|DownloadedMovieImportService|Deleting folder after importing valid files>

**Comment by galli-leo** [comment]
Can you try the latest release and see if upgrade works?

**Comment by ltjdym** [comment]
This problem is still happening with me.

**Comment by ltjdym** [comment]
I think it may have to do with "Change File Date" w different year so I changed that option to "none"
