### ISSUE TITLE
HD4Free  Failed to find movie title in release name

### ISSUE THREAD

**Issue by HitsvilleUK** [Radarr/Radarr#1896]
For a few days I have been getting the above message and the below screenshot for every search of HD4Free (using Jackett)
![capture hd4free](https://user-images.githubusercontent.com/9288228/29154244-f7ce5b1a-7d8a-11e7-8b3c-42444a990b8c.PNG)

This is on three different Linux seedboxes all with different providers. 
Coincidentally Sonarr works fine with the tracker on all 3 installs.
Plus while doing some troubleshooting I installed Jackett on my Windows PC at home. 
It picks up the movies correctly there.

**Comment by HitsvilleUK** [comment]
Apologies guys....Actually this looks like its possibly a Jackett issue.

**Comment by s0mm3rb** [comment]
@HitsvilleUK were you able to solve the Jackett issue?
I'm having the same issue, some releases are not grabbed cause it didn't find the movie title in the release name

thanks

**Comment by HitsvilleUK** [comment]
Is that soecifically with HD4Free? 
If so will check in the morning. But last I looked it was resolved.

**Comment by s0mm3rb** [comment]
> Is that soecifically with HD4Free?
> If so will check in the morning. But last I looked it was resolved.

No, sorry, I'm having it with a different indexer, but I found your post and thought that it could be related
thanks
