### ISSUE TITLE
It won't start, problem with latest update.

### ISSUE THREAD

**Issue by rickytin** [Radarr/Radarr#1897]
CorruptDatabase when Radarr restart from update.
I did the step,
Re-install Sonarr
Run Sonarr once to get the AppData directory location
Stop Sonarr
Delete the config.xml & nzbdrone.db* files (Including the .db-wal/.db-journal files if they exist)
Extract the backup zip file & restore the files extracted from the zip
Start Sonarr 
It won't start using my backup files.
It works if I delete config.xml & nzbdrone.db but there is no way to import settings.
It works if I install Radarr.develop.0.2.0.778 but when it update it won't start.

**I did a text, I install Radarr.develop.0.2.0.778 then stop Radarr find backup config.xml & nzbdrone.db and restore the files but before I starting Radarr I change from nightly to develop in config.xlm and now is working because is not updating to latest version.
Any help would be appreciated.** 

![radarr](https://user-images.githubusercontent.com/4860538/29155635-5b60c37c-7d6b-11e7-849f-bd2f54d3332e.PNG)

**Comment by fevkalbeser** [comment]
Same here. It seems there is a problem with the latest nightly update. Any suggestions?

**Comment by mrbipbip** [comment]
Same here on a Qnap system

**Comment by hotio** [comment]
It seems that error message needs updating...still mentioning sonarr.

Oh, these small hicups can be expected when running nightly, all part of the game. IIRC gallileo is aware of the problem and you can find a workaround when you read through the discord chat...

**Comment by gold007eye** [comment]
Same here.. and as a side note as you can see from the error screenshot it actually is still referencing Sonarr's github page instead of Radarr.

**Comment by hotio** [comment]
On the radarr discord server

**Comment by galli-leo** [comment]
Fixed on latest nightly.
