### ISSUE TITLE
Feature Request: Do not delete old movie files.

### ISSUE THREAD

**Issue by dweidenfeld** [Radarr/Radarr#1898]
Hi there,

I am using Radarr in the latest develop version (0.2.0.778) and it seems that the custom script function is completely broken.

I am running Radarr inside a Docker container with full RW access to /config.
I added this script (/config/scripts/test.sh) with full execution rights for every user (chmod a+x test.sh):
```bash
#!/bin/bash
echo "test" >> /config/logs/test.log
```

Whenever I execute the script either by `/bin/bash /config/scripts/test.sh` or `/config/scripts/test.sh` it works. 
If I execute the "test" command in Radarr it won't get executed.

There is no debug info in the radarr logs even if I turn on trace level.

Some idea?

**Comment by dweidenfeld** [comment]
One addition:

Custom scripts are not executed when pressing "test".
Custom scripts are executed when triggering "on grab".
Custom scripts are not executed when triggering "on download" or the other actions.

**Comment by dweidenfeld** [comment]
Another addition:

"on download" is executed... but not on download, but after it tried to move the file.... this is a problem, because my script want's to preprocess the target destination before it moves the download.

or maybe there should be an option to make radarr not to try to remove existing movies.

**Comment by vertigo235** [comment]
The On Download fires after the file is moved because that event is intended to notify when the file is available, like to refresh plex, or notify you that you can watch it etc.

**Comment by vertigo235** [comment]
If you're looking to pre-process before radarr you might want to look at a post process script from your downloader instead? nzbget or sab should be able to execute your script for you before the download is marked complete.

**Comment by dweidenfeld** [comment]
Actually I need to be in the process, where the final file name is clear but the moving has not been started.

**Comment by galli-leo** [comment]
So I marked this as a feature request, since the custom script function does work correctly (Test does not execute the script is intended, same in Sonarr). What exactly do you need to do with the target destination? Maybe you could use the recycle bin provider?

**Comment by vertigo235** [comment]
Maybe you could just do a unionfs mount with your recycle bin.

**Comment by dweidenfeld** [comment]
Okay I've found a workaround, so that I don't need the script anymore. But I think we should let the ticket opened by now, because it is always good to have the possibility to hook in the process ;)

**Comment by gbonk** [comment]
@dweidenfeld   What is your work around ?

**Comment by dweidenfeld** [comment]
> @dweidenfeld What is your work around ?

Actually I have none. I switched to a stable fs solution and played with lots of health checks. So whenever a dependency is broken everything restarts immediately. 

So I don't need that feature anymore. Decide yourself if you want to leave the issue open or not.
