### ISSUE TITLE
Trouble with auto-updating Radarr

### ISSUE THREAD

**Issue by S10t** [Radarr/Radarr#1899]
I've been having trouble with auto updating radarr.
A quick glance at the log, explained whats going on. 

Im am using a VPN, which i understand is causing the problem. And i have no problem disconnecting the vpn now and then to update radarr.
But a disconnect from the vpn (Checked by WAN ip) is not solving the problem. 
The issue resides.
is there a way to manually update radarr?

**Radarr Version:**
Radarr Ver. 0.2.0.778
develop
Running on debian

**Logs:**

`

NzbDroneErrorPipeline | Request Failed: Unable to access radarr.aeonlucid.com, blocked by CloudFlare CAPTCHA. Likely due to shared-IP VPN. | 12:44
-- | -- | --
  | NzbDroneErrorPipeline | Request Failed: Unable to access radarr.aeonlucid.com, blocked by CloudFlare CAPTCHA. Likely due to shared-IP VPN. | 12:44
  | NzbDroneErrorPipeline | Request Failed: Unable to access radarr.aeonlucid.com, blocked by CloudFlare CAPTCHA. Likely due to shared-IP VPN. | 12:38
  | NzbDroneErrorPipeline | Request Failed: Unable to access radarr.aeonlucid.com, blocked by CloudFlare CAPTCHA. Likely due to shared-IP VPN. | 12:38
  | TaskExtensions | Task Error: Unable to access radarr.aeonlucid.com, blocked by CloudFlare CAPTCHA. Likely due to shared-IP VPN. | 12:38
  | LifecycleService | Restart requested.

`

**Comment by hotio** [comment]
Offcourse you can manually update radarr.
Just repeat what you did to install it.

**Comment by S10t** [comment]
Ah that simple :-)

But regarding the problem with not being able to update from within Radarr, although im not using a vpn.
Is my Radarr install blacklisted or something, because i cant understand why my public ip is being rejected by radarr.aeonlucid.com.

**Comment by hotio** [comment]
Perhaps you got flagged for some reason, perhaps try getting another ip altogheter.

**Comment by galli-leo** [comment]
I would also suggest restarting your router to get a new ip. Sadly not something we can control well.
