### ISSUE TITLE
Less movies on /api/movie call with "downloadQuality" sortKey

### ISSUE THREAD

**Issue by AeonLucid** [Radarr/Radarr#1902]
**Description:**

sortKey downloadedQuality causes it to show less movies on the /api/movie call.

**Radarr Version:**

0.2.0.798 nightly

**Comment by galli-leo** [comment]
Yeah "intended" behaviour. Sorting by downloadedQuality automatically filters out all non downloaded movies (because of how we do the query).

**Comment by galli-leo** [comment]
Will fix this when redoing paging.
