### ISSUE TITLE
The at the beginning of titles is not removed for Clean Titles leading to mapping problems.

### ISSUE THREAD

**Issue by i3laze** [Radarr/Radarr#1907]
I'm using Jackett with RuTracker and have a mapping issue. 
In Radarr's Settings-Indexers mapping is already set to "lenient".

Titles on the tracker ought to have director's name in (round brackets) right after film's title. Mapping is failing here.
I see that parser is ignoring Cyrillic, but it should better ommit all content in brackets ( ) [ ]:

**UPD:** it was **The** at the beginning that doing mess.
> **Title:**
>  Затерянный город Z / The Lost City of Z (Джеймс Грэй / James Gray) [2016, США, боевик, драма, приключения, биография, история, BDRip] Dub + Sub Eng + Original Eng 
> **Seen in Radarr's manual search:**
> Z / The Lost City of Z ( / James Gray) [2016, , , , , BDRip-AVC] Dub + Original (eng) + Sub (eng)
> **Error:**
> Failed to map movie, found title Z / The Lost City of Z ( / James Gray) [, expected one of: The Lost City of Z, The Lost City of Z 

> **Title:**
> Мумия / The Mummy (Алекс Куртцман / Alex Kurtzman) [2017, США, фэнтези, боевик, триллер, WEB-DLRip-AVC] Dub + Sub (rus)
> **Seen in Radarr's manual search:**
> / The Mummy ( / Alex Kurtzman) [2017, , , , , WEB-DLRip-AVC] Dub + Sub (rus)
> **Error:**
> Failed to map movie, found title / The Mummy ( / Alex Kurtzman) [, expected one of: The Mummy, The Mummy, The Mummy 3D

Here's another problem. With ":"

> **Title:**
> Джон Уик 2 / John Wick: Chapter Two (Чад Стахелски / Chad Stahelski) [2017, США, боевик, триллер, криминал, BDRip 720p] Dub (iTunes) + Sub Rus, Eng + Original Eng
> **Seen in Radarr's manual search:**
> 2 / John Wick: Chapter Two ( / Chad Stahelski) [2017, , , , , BDRip 720p] Dub (iTunes) + Sub Rus, Eng + Original Eng
> **Error:**
> Failed to map movie, found title 2 / John Wick Chapter Two ( / Chad Stahelski) [, expected one of: John Wick: Chapter 2, John Wick: Chapter 2, John Wick 2, John Wick: Chapter Two

Ideas?
How about giving a regular user an ability to tweak parser behavior?

**Comment by hotio** [comment]
It's not feasible I think to keep making up workarounds for trackers that refuse to correctly name their releases. What's next the name of their grandma in double {{ brackets?

**Comment by i3laze** [comment]
Any IETF RFC on naming torrents? :)
I bet there was no tracker convention to decide which naming is a gold standard.

All i'm asking is additional Switch in GUI for ever more lenient mapping/skipping sections in brackets.
I guess I have to open the hood of Jackett and fix naming in the air.

**Comment by hotio** [comment]
Ever heard of scene rules?

**Comment by GeorgeLubaretsi** [comment]
Having the same issue here

**Comment by i3laze** [comment]
Added one more issue with : in title.

**Comment by Cheaterdev** [comment]
Still not solved? Maybe try finding by substring rather than by equalness?
Removing brackets as a option to indexer will really help us. Or as enviroment parameter if you dont want to make changes for non-rutracker users. Any solution will give us a reason to use Radarr as we don't have other good torrent-trackers like rutracker to pair Radarr with.

**Comment by TiraelSedai** [comment]
I can confirm, it's basically the only real source.

**Comment by bakerboy448** [comment]
is this still an issue in v3? @i3laze @Cheaterdev @TiraelSedai

**Comment by TiraelSedai** [comment]
I stopped using Radarr for that reason, let me install it later today.

**Comment by TiraelSedai** [comment]
So what is v3? latest release I see in this repo is Pre-Release v0.2.0.1504

**Comment by bakerboy448** [comment]
V3 is beta

The download links are on the readme, no formal release yet.
