### ISSUE TITLE
Movies marked as missing if year is not in folder/filename

### ISSUE THREAD

**Issue by nutski** [Radarr/Radarr#191]
I've imported all my movies but quite a few still show as 'Missing'
It appears that every movie where the folder has the year in brackets has imported correctly, if the folder isn't in this format it fails.

17-1-12 09:30:58.1|Debug|RefreshMovieService|Finished movie refresh for Alice in Wonderland
17-1-12 09:30:58.1|Trace|EventAggregator|Publishing MovieUpdatedEvent
17-1-12 09:30:58.1|Trace|EventAggregator|MovieUpdatedEvent -> DiskScanService
17-1-12 09:30:58.1|Info|DiskScanService|Scanning disk for Alice in Wonderland
17-1-12 09:30:58.1|Trace|EventAggregator|Publishing CommandUpdatedEvent
17-1-12 09:30:58.1|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
17-1-12 09:30:58.1|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
17-1-12 09:30:58.1|Debug|DiskScanService|Scanning '/movies/Alice in Wonderland' for video files
17-1-12 09:30:58.1|Debug|DiskScanService|1 video files were found in /movies/Alice in Wonderland
17-1-12 09:30:58.1|Trace|DiskScanService|Finished getting episode files for: [tt1014759][Alice in Wonderland] [00:00:00.0016471]
17-1-12 09:30:58.1|Debug|DiskScanService|[tt1014759][Alice in Wonderland] Cleaning up media files in DB
17-1-12 09:30:58.1|Debug|ImportDecisionMaker|Analyzing 1/1 files.
17-1-12 09:30:58.1|Debug|Parser|Parsing string 'Alice.in.Wonderland.bluray.mkv'
17-1-12 09:30:58.1|Debug|Parser|Unable to parse Alice.in.Wonderland.bluray.mkv
17-1-12 09:30:58.1|Debug|Parser|Attempting to parse episode info using directory and file names. Alice in Wonderland
17-1-12 09:30:58.1|Debug|Parser|Parsing string 'Alice.in.Wonderland.Alice.in.Wonderland.bluray.mkv'
17-1-12 09:30:58.1|Debug|Parser|Unable to parse Alice.in.Wonderland.Alice.in.Wonderland.bluray.mkv
17-1-12 09:30:58.1|Debug|Parser|Attempting to parse episode info using directory name. Alice in Wonderland
17-1-12 09:30:58.1|Debug|Parser|Parsing string 'Alice.in.Wonderland.mkv'
17-1-12 09:30:58.1|Debug|Parser|Unable to parse Alice.in.Wonderland.mkv
17-1-12 09:30:58.1|Warn|ParsingService|Unable to parse movie info from path /movies/Alice in Wonderland/Alice in Wonderland.bluray.mkv
17-1-12 09:30:58.1|Trace|DiskScanService|Import decisions complete for: [tt1014759][Alice in Wonderland] [00:00:00.0056507]

**Comment by seanvree** [comment]
Yeah, I'm having this too. I imported all my 1200 movies manually, but about 20% found the movie folder, but it's marked at "missing".

**Comment by mrowlinson** [comment]
Is there a timeframe for the 0.3 release? Really sucks not being able to import my library and start managing it in Radarr until this is fixed. I'd also love an option to be able to just bulk import everything so I don't have to hit the plus button on every item for the over 2000 movies I have in my library.

**Comment by OUBeaver** [comment]
In my opinion, while it can be very tedious, all this "issue" does for me is force me to organize (rename) my movies better.  Radarr (and Sonarr) are much happier when naming is spot on.

For the record, my naming is as follows and I do not have issues any more:
X:\Batman Begins (2005)\Batman Begins.mkv

Also...Radarr is in BETA.  Going to have to deal with stuff ya'll.  ;)

**Comment by seanvree** [comment]
I also found that if you remove the movies that were not imported, then drop them in the drone folder, then manually import them from the drone folder, it picked up 90% of the movies that weren't found after the initial import.

**Comment by jons1n** [comment]
It doesn't make sense to me that an individual movie file has to be in it's own directory; it's not a TV show. None of my movies have imported because they're in a single Movies directory. Do people actually organize a single movie into it's own directory?

**Comment by onedr0p** [comment]
Why yes, yes we do. Why would I want the movie and the movies metadata (subs, artwork, NFO etc) all in one directory for all movies?

**Comment by jons1n** [comment]
Well, I put all of my movies in one dir, with one subdir for subs. I must be missing the benefit of keeping NFO files and artwork for each movie vs letting the client (kodi for me) manage the metadata.

**Comment by mrowlinson** [comment]
Why was this closed? This still isn't working for me on the latest update.

**Comment by onedr0p** [comment]
Folder should have year in it to process correctly..

**Comment by mrowlinson** [comment]
So the answer is to just not fix the issue and tell everyone too bad?

**Comment by onedr0p** [comment]
As was said in a previous post.. Radarr (and Sonarr) are much happier when naming is spot on. We cannot hold everyone's hand and appease every request made. It's a standard to have movie name and year in folder and filename in order to get an exact match from TMDb. Leaving out year may cause problems further down the road for you when the movie titles are ambiguous.

**Comment by mrowlinson** [comment]
Or you could just make a best guess, which usually works with everything else that's uses TMDb, and allow the user to fix an incorrect match themselves.

**Comment by onedr0p** [comment]
I think we need to agree on a standard for minimum requirements for a movie file and folder name and that includes title and year. Is that too much to ask?

**Comment by onedr0p** [comment]
Moreover all the developers have agreed to support the same folder/files that Plex does: https://support.plex.tv/hc/en-us/articles/200381023-Naming-Movie-files

**Comment by mrowlinson** [comment]
They strongly recommend those naming standards which I can understand. Plex will still try to match them even if they're not though. They don't say if they're not named to that standard too bad, we're just going to ignore those and say those things are missing.

**Comment by onedr0p** [comment]
Plex has a team of paid developers and a QA team to make sure things work correctly, this is a FOSS project with only a few devs. We aren't looking at creating a guessing module when it's easier for the user just to follow a standard naming convention.

**Comment by Paradoxum** [comment]
So is plex naming convention support in the pipeline or? I'm surprised you can't just completely customize it

**Comment by samsonious** [comment]
It already successfully guessed the movie to import it and determine it was missing, it shouldn't need to make another guess to know the file named the same as the folder it managed to guess might just be the same movie.
