### ISSUE TITLE
Option to search indexer by movie title.

### ISSUE THREAD

**Issue by tchit** [Radarr/Radarr#1912]
When I add a French movie, with the language French selected in the profile, the movie is only suggested to me with the English title. I add it to monitored movies and then when I use the search option in Radarr, I can find my movie with its French title.
But then, when I search for a release, I only get results with the English title.

Example with the French movie : "La fille inconnue"
Radarr suggests I add "The unknown girl" (English title).
When I search for the movie in Radarr, I can find it by typing "La fille inconnue" so it looks like it's considered as French, but when I search for the release through indexers I only get results with "The unknown girl". It should search for "la fille inconnue".
What am I missing?
Thanks a lot!

**Comment by galli-leo** [comment]
Do your indexers have french releases? Does Radarr show the english title when displaying the movie?

**Comment by tchit** [comment]
Yes, my Hydra install can find a French release with the French title.
Radarr shows the English title when it displays the movie but when I search for the movie in the Radarr search box I have to type the title in French!
Also, the search is performed in English (English title) but the results are not downloaded because not in the specified language (French).

**Comment by supremacy2k** [comment]
might be related to this: 
https://github.com/Radarr/Radarr/issues/1807

**Comment by tchit** [comment]
Not sure my issue is so complicated!

**Comment by galli-leo** [comment]
@tchit Can you provide logs for the search?

**Comment by tchit** [comment]
@galli-leo :
These are the logs from the moment I add the movie up to the manual search :

17-8-13 14:13:34.0|Info|RssSyncService|Starting RSS Sync
17-8-13 14:13:38.9|Info|DownloadDecisionMaker|Processing 200 releases
17-8-13 14:15:39.8|Info|RssSyncService|RSS Sync Completed. Reports found: 200, Reports grabbed: 0
17-8-13 14:36:00.0|Warn|MediaCoverMapper|File /usr/local/radarr/var/.config/Radarr/MediaCover/150/poster.jpg not found
17-8-13 14:36:16.8|Warn|MediaCoverMapper|File /usr/local/radarr/var/.config/Radarr/MediaCover/82/poster.jpg not found
17-8-13 14:36:18.3|Warn|MediaCoverMapper|File /usr/local/radarr/var/.config/Radarr/MediaCover/90/poster.jpg not found
17-8-13 14:36:21.5|Warn|MediaCoverMapper|File /usr/local/radarr/var/.config/Radarr/MediaCover/58/poster.jpg not found
17-8-13 14:36:32.4|Info|MovieService|Adding Movie [][The Unknown Girl (2016)] Path: [/volume1/video/FILMS HD/The Unknown Girl (2016)]
17-8-13 14:36:32.7|Info|MediaCoverService|Downloading Poster for [][The Unknown Girl (2016)] http://image.tmdb.org/t/p/original/o7UivjQSOHq936L4dUg2ZQq7MqA.jpg
17-8-13 14:36:32.9|Info|RefreshMovieService|Updating Info for The Unknown Girl
17-8-13 14:36:33.8|Info|DiskScanService|Scanning disk for La Fille inconnue
17-8-13 14:36:34.0|Info|MovieScannedHandler|[La Fille inconnue] was recently added, performing post-add actions
17-8-13 14:36:34.2|Info|MediaCoverService|Downloading Poster for [tt4630550][La Fille inconnue (2016)] http://image.tmdb.org/t/p/original/qAjCCpjKFA35PtIBCaXwfEL5E8.jpg
17-8-13 14:36:34.5|Info|MediaCoverService|Downloading Banner for [tt4630550][La Fille inconnue (2016)] http://image.tmdb.org/t/p/original/6Wk5o322fO3ITObGqOV5whxc4Px.jpg
17-8-13 14:37:08.6|Warn|MediaCoverMapper|File /usr/local/radarr/var/.config/Radarr/MediaCover/150/poster.jpg not found
17-8-13 14:37:08.9|Warn|MediaCoverMapper|File /usr/local/radarr/var/.config/Radarr/MediaCover/90/poster.jpg not found
17-8-13 14:37:08.9|Warn|MediaCoverMapper|File /usr/local/radarr/var/.config/Radarr/MediaCover/82/poster.jpg not found
17-8-13 14:37:08.9|Warn|MediaCoverMapper|File /usr/local/radarr/var/.config/Radarr/MediaCover/58/poster.jpg not found
17-8-13 14:37:56.0|Warn|MediaCoverMapper|File /usr/local/radarr/var/.config/Radarr/MediaCover/150/poster.jpg not found
17-8-13 14:37:56.4|Warn|MediaCoverMapper|File /usr/local/radarr/var/.config/Radarr/MediaCover/58/poster.jpg not found
17-8-13 14:37:56.4|Warn|MediaCoverMapper|File /usr/local/radarr/var/.config/Radarr/MediaCover/82/poster.jpg not found
17-8-13 14:37:56.4|Warn|MediaCoverMapper|File /usr/local/radarr/var/.config/Radarr/MediaCover/90/poster.jpg not found
17-8-13 14:38:12.5|Info|NzbSearchService|Searching 2 indexers for [La Fille inconnue]
17-8-13 14:38:14.1|Info|DownloadDecisionMaker|Processing 12 releases


The 12 releases have the title "The unknown girl" instead of the French one.

**Comment by tchit** [comment]
(Also I see in the logs that the French poster link is found but it's never updated in Radarr, it always shows the English one.)

**Comment by galli-leo** [comment]
@tchit Can you enable trace logging and search again?

**Comment by tchit** [comment]
15:19:42.1|Info|NzbSearchService|Searching 2 indexers for [La Fille inconnue]
17-8-13 15:19:42.2|Debug|Newznab|Downloading Feed https://api.nzbplanet.net/api?t=movie&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060&extended=1&apikey=(removed)&offset=0&limit=100&imdbid=4630550
17-8-13 15:19:42.2|Debug|Newznab|Downloading Feed http://192.168.0.24:5075/api?t=movie&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060&extended=1&apikey=(removed)&offset=0&limit=100&imdbid=4630550
17-8-13 15:19:42.2|Trace|HttpClient|Req: [GET] https://api.nzbplanet.net/api?t=movie&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060&extended=1&apikey=(removed)&offset=0&limit=100&imdbid=4630550
17-8-13 15:19:42.2|Trace|HttpClient|Req: [GET] http://192.168.0.24:5075/api?t=movie&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060&extended=1&apikey=(removed)&offset=0&limit=100&imdbid=4630550
17-8-13 15:19:42.2|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
17-8-13 15:19:42.2|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
17-8-13 15:19:42.6|Trace|HttpClient|Res: [GET] https://api.nzbplanet.net/api?t=movie&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060&extended=1&apikey=(removed)&offset=0&limit=100&imdbid=4630550: 200.OK (489 ms)
17-8-13 15:19:42.7|Trace|NewznabRssParser|Parsed: The.Unknown.Girl.2016.BRRip.HebSubs.XviD.AC3-Uploadil
17-8-13 15:19:42.7|Trace|NewznabRssParser|Parsed: the.unheard.woman.2016.dvdrip.x264-bipolar
17-8-13 15:19:42.7|Trace|NewznabRssParser|Parsed: the.unheard.woman.2016.dvdrip.x264-bipolar
17-8-13 15:19:42.7|Trace|NewznabRssParser|Parsed: The.Unknown.Girl.2016.1080p.BluRay.DD5.1.x264-DON
17-8-13 15:19:42.7|Trace|NewznabRssParser|Parsed: the.unknown.girl.2016.limited.1080p.bluray.x264-usury
17-8-13 15:19:42.7|Trace|NewznabRssParser|Parsed: the.unknown.girl.2016.limited.bdrip.x264-bipolar
17-8-13 15:19:43.2|Trace|HttpClient|Res: [GET] http://192.168.0.24:5075/api?t=movie&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060&extended=1&apikey=(removed)&offset=0&limit=100&imdbid=4630550: 200.OK (1067 ms)
17-8-13 15:19:43.2|Trace|NewznabRssParser|Parsed: The.Unknown.Girl.2016.BRRip.HebSubs.XviD.AC3-Uploadil
17-8-13 15:19:43.2|Trace|NewznabRssParser|Parsed: the.unheard.woman.2016.dvdrip.x264-bipolar
17-8-13 15:19:43.2|Trace|NewznabRssParser|Parsed: the.unheard.woman.2016.dvdrip.x264-bipolar
17-8-13 15:19:43.2|Trace|NewznabRssParser|Parsed: The.Unknown.Girl.2016.1080p.BluRay.DD5.1.x264-DON
17-8-13 15:19:43.2|Trace|NewznabRssParser|Parsed: the.unknown.girl.2016.limited.1080p.bluray.x264-usury
17-8-13 15:19:43.2|Trace|NewznabRssParser|Parsed: the.unknown.girl.2016.limited.bdrip.x264-bipolar
17-8-13 15:19:43.2|Debug|NzbSearchService|Total of 12 reports were found for [La Fille inconnue] from 2 indexers
17-8-13 15:19:43.2|Info|DownloadDecisionMaker|Processing 12 releases
17-8-13 15:19:43.2|Trace|DownloadDecisionMaker|Processing release 1/12
17-8-13 15:19:43.2|Trace|ConfigService|Using default config value for 'parsingleniency' defaultValue:'Strict'
17-8-13 15:19:43.2|Debug|Parser|Parsing string 'The.Unknown.Girl.2016.BRRip.HebSubs.XviD.AC3-Uploadil'
17-8-13 15:19:43.2|Trace|Parser|^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(19|20)\d{2}(?!p|i|(19|20)\d{2}|\]|\W(19|20)\d{2})))+(\W+|_|$)(?!\\)
17-8-13 15:19:43.3|Debug|Parser|Movie Parsed. The Unknown Girl - 2016 
17-8-13 15:19:43.3|Debug|Parser|Language parsed: English
17-8-13 15:19:43.3|Debug|QualityParser|Trying to parse quality for The.Unknown.Girl.2016.BRRip.HebSubs.XviD.AC3-Uploadil
17-8-13 15:19:43.3|Debug|Parser|Quality parsed: DVD v1
17-8-13 15:19:43.3|Debug|Parser|Release Group parsed: Uploadil
17-8-13 15:19:43.3|Trace|ConfigService|Using default config value for 'allowhardcodedsubs' defaultValue:'False'
17-8-13 15:19:43.3|Trace|ConfigService|Using default config value for 'whitelistedhardcodedsubs' defaultValue:''
17-8-13 15:19:43.3|Debug|DownloadDecisionMaker|Testing: System.String[]
17-8-13 15:19:43.3|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] Hardcoded subs found: hebsubs
17-8-13 15:19:43.3|Trace|DownloadDecisionMaker|Processing release 2/12
17-8-13 15:19:43.3|Trace|ConfigService|Using default config value for 'parsingleniency' defaultValue:'Strict'
17-8-13 15:19:43.3|Debug|Parser|Parsing string 'the.unheard.woman.2016.dvdrip.x264-bipolar'
17-8-13 15:19:43.3|Trace|Parser|^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(19|20)\d{2}(?!p|i|(19|20)\d{2}|\]|\W(19|20)\d{2})))+(\W+|_|$)(?!\\)
17-8-13 15:19:43.3|Debug|Parser|Movie Parsed. the unheard woman - 2016 
17-8-13 15:19:43.3|Debug|Parser|Language parsed: English
17-8-13 15:19:43.3|Debug|QualityParser|Trying to parse quality for the.unheard.woman.2016.dvdrip.x264-bipolar
17-8-13 15:19:43.3|Debug|Parser|Quality parsed: DVD v1
17-8-13 15:19:43.3|Debug|Parser|Release Group parsed: bipolar
17-8-13 15:19:43.3|Debug|AcceptableSizeSpecification|Beginning size check for: the.unheard.woman.2016.dvdrip.x264-bipolar
17-8-13 15:19:43.3|Debug|AcceptableSizeSpecification|Item: the.unheard.woman.2016.dvdrip.x264-bipolar, meets size constraints.
17-8-13 15:19:43.3|Trace|DownloadDecisionMaker|Spec AnimeVersionUpgradeSpecification does not care about movies.
17-8-13 15:19:43.3|Trace|DownloadDecisionMaker|Spec FullSeasonSpecification does not care about movies.
17-8-13 15:19:43.3|Debug|LanguageSpecification|Checking if report meets language requirements. English
17-8-13 15:19:43.3|Debug|LanguageSpecification|Report Language: English rejected because it is not wanted, wanted French
17-8-13 15:19:43.3|Debug|ReleaseRestrictionsSpecification|Checking if release meets restrictions: the.unheard.woman.2016.dvdrip.x264-bipolar
17-8-13 15:19:43.3|Debug|ReleaseRestrictionsSpecification|[the.unheard.woman.2016.dvdrip.x264-bipolar] No restrictions apply, allowing
17-8-13 15:19:43.3|Debug|QualityAllowedByProfileSpecification|Checking if report meets quality requirements. DVD v1
17-8-13 15:19:43.3|Trace|ConfigService|Using default config value for 'minimumage' defaultValue:'0'
17-8-13 15:19:43.3|Debug|MinimumAgeSpecification|Minimum age is not set.
17-8-13 15:19:43.3|Trace|ConfigService|Using default config value for 'retention' defaultValue:'0'
17-8-13 15:19:43.3|Debug|RetentionSpecification|Checking if report meets retention requirements. 156
17-8-13 15:19:43.3|Trace|DownloadDecisionMaker|Spec SameEpisodesGrabSpecification does not care about movies.
17-8-13 15:19:43.3|Trace|DownloadDecisionMaker|Spec DailyEpisodeMatchSpecification does not care about movies.
17-8-13 15:19:43.3|Trace|DownloadDecisionMaker|Spec EpisodeRequestedSpecification does not care about movies.
17-8-13 15:19:43.3|Trace|DownloadDecisionMaker|Spec SeasonMatchSpecification does not care about movies.
17-8-13 15:19:43.3|Debug|SeriesSpecification|Checking if movie matches searched movie
17-8-13 15:19:43.3|Trace|DownloadDecisionMaker|Spec SingleEpisodeSearchMatchSpecification does not care about movies.
17-8-13 15:19:43.3|Debug|DelaySpecification|Ignoring delay for user invoked search
17-8-13 15:19:43.3|Debug|HistorySpecification|Skipping history check during search
17-8-13 15:19:43.3|Debug|MonitoredEpisodeSpecification|Skipping monitored check during search
17-8-13 15:19:43.3|Debug|AvailabilitySpecification|Skipping availability check during search
17-8-13 15:19:43.3|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] French is wanted, but found English
17-8-13 15:19:43.3|Trace|DownloadDecisionMaker|Processing release 3/12
17-8-13 15:19:43.3|Trace|ConfigService|Using default config value for 'parsingleniency' defaultValue:'Strict'
17-8-13 15:19:43.3|Debug|Parser|Parsing string 'the.unheard.woman.2016.dvdrip.x264-bipolar'
17-8-13 15:19:43.3|Trace|Parser|^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(19|20)\d{2}(?!p|i|(19|20)\d{2}|\]|\W(19|20)\d{2})))+(\W+|_|$)(?!\\)
17-8-13 15:19:43.3|Debug|Parser|Movie Parsed. the unheard woman - 2016 
17-8-13 15:19:43.3|Debug|Parser|Language parsed: English
17-8-13 15:19:43.3|Debug|QualityParser|Trying to parse quality for the.unheard.woman.2016.dvdrip.x264-bipolar
17-8-13 15:19:43.3|Debug|Parser|Quality parsed: DVD v1
17-8-13 15:19:43.3|Debug|Parser|Release Group parsed: bipolar
17-8-13 15:19:43.3|Debug|AcceptableSizeSpecification|Beginning size check for: the.unheard.woman.2016.dvdrip.x264-bipolar
17-8-13 15:19:43.4|Debug|AcceptableSizeSpecification|Item: the.unheard.woman.2016.dvdrip.x264-bipolar, meets size constraints.
17-8-13 15:19:43.4|Trace|DownloadDecisionMaker|Spec AnimeVersionUpgradeSpecification does not care about movies.
17-8-13 15:19:43.4|Trace|DownloadDecisionMaker|Spec FullSeasonSpecification does not care about movies.
17-8-13 15:19:43.4|Debug|LanguageSpecification|Checking if report meets language requirements. English
17-8-13 15:19:43.4|Debug|LanguageSpecification|Report Language: English rejected because it is not wanted, wanted French
17-8-13 15:19:43.4|Debug|ReleaseRestrictionsSpecification|Checking if release meets restrictions: the.unheard.woman.2016.dvdrip.x264-bipolar
17-8-13 15:19:43.4|Debug|ReleaseRestrictionsSpecification|[the.unheard.woman.2016.dvdrip.x264-bipolar] No restrictions apply, allowing
17-8-13 15:19:43.4|Debug|QualityAllowedByProfileSpecification|Checking if report meets quality requirements. DVD v1
17-8-13 15:19:43.4|Trace|ConfigService|Using default config value for 'minimumage' defaultValue:'0'
17-8-13 15:19:43.4|Debug|MinimumAgeSpecification|Minimum age is not set.
17-8-13 15:19:43.4|Trace|ConfigService|Using default config value for 'retention' defaultValue:'0'
17-8-13 15:19:43.4|Debug|RetentionSpecification|Checking if report meets retention requirements. 156
17-8-13 15:19:43.4|Trace|DownloadDecisionMaker|Spec SameEpisodesGrabSpecification does not care about movies.
17-8-13 15:19:43.4|Trace|DownloadDecisionMaker|Spec DailyEpisodeMatchSpecification does not care about movies.
17-8-13 15:19:43.4|Trace|DownloadDecisionMaker|Spec EpisodeRequestedSpecification does not care about movies.
17-8-13 15:19:43.4|Trace|DownloadDecisionMaker|Spec SeasonMatchSpecification does not care about movies.
17-8-13 15:19:43.4|Debug|SeriesSpecification|Checking if movie matches searched movie
17-8-13 15:19:43.4|Trace|DownloadDecisionMaker|Spec SingleEpisodeSearchMatchSpecification does not care about movies.
17-8-13 15:19:43.4|Debug|DelaySpecification|Ignoring delay for user invoked search
17-8-13 15:19:43.4|Debug|HistorySpecification|Skipping history check during search
17-8-13 15:19:43.4|Debug|MonitoredEpisodeSpecification|Skipping monitored check during search
17-8-13 15:19:43.4|Debug|AvailabilitySpecification|Skipping availability check during search
17-8-13 15:19:43.4|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] French is wanted, but found English
17-8-13 15:19:43.5|Trace|DownloadDecisionMaker|Processing release 4/12
17-8-13 15:19:43.5|Trace|ConfigService|Using default config value for 'parsingleniency' defaultValue:'Strict'
17-8-13 15:19:43.5|Debug|Parser|Parsing string 'The.Unknown.Girl.2016.1080p.BluRay.DD5.1.x264-DON'
17-8-13 15:19:43.5|Trace|Parser|^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(19|20)\d{2}(?!p|i|(19|20)\d{2}|\]|\W(19|20)\d{2})))+(\W+|_|$)(?!\\)
17-8-13 15:19:43.5|Debug|Parser|Movie Parsed. The Unknown Girl - 2016 
17-8-13 15:19:43.5|Debug|Parser|Language parsed: English
17-8-13 15:19:43.5|Debug|QualityParser|Trying to parse quality for The.Unknown.Girl.2016.1080p.BluRay.DD5.1.x264-DON
17-8-13 15:19:43.5|Debug|Parser|Quality parsed: Bluray-1080p v1
17-8-13 15:19:43.5|Debug|Parser|Release Group parsed: DON
17-8-13 15:19:43.5|Trace|Owin|SQLite error (5): database is locked

17-8-13 15:19:43.6|Trace|Owin|SQLite error (5): database is locked

17-8-13 15:19:43.6|Trace|Owin|SQLite error (5): database is locked

17-8-13 15:19:43.7|Trace|Owin|SQLite error (5): database is locked

17-8-13 15:19:43.8|Debug|AcceptableSizeSpecification|Beginning size check for: The.Unknown.Girl.2016.1080p.BluRay.DD5.1.x264-DON
17-8-13 15:19:43.8|Debug|AcceptableSizeSpecification|Item: The.Unknown.Girl.2016.1080p.BluRay.DD5.1.x264-DON, Size: 17171151230 is greater than maximum allowed size (13661791869 for La Fille inconnue), rejecting.
17-8-13 15:19:43.8|Trace|DownloadDecisionMaker|Spec AnimeVersionUpgradeSpecification does not care about movies.
17-8-13 15:19:43.8|Trace|DownloadDecisionMaker|Spec FullSeasonSpecification does not care about movies.
17-8-13 15:19:43.9|Debug|LanguageSpecification|Checking if report meets language requirements. English
17-8-13 15:19:43.9|Debug|LanguageSpecification|Report Language: English rejected because it is not wanted, wanted French
17-8-13 15:19:43.9|Debug|ReleaseRestrictionsSpecification|Checking if release meets restrictions: The.Unknown.Girl.2016.1080p.BluRay.DD5.1.x264-DON
17-8-13 15:19:43.9|Debug|ReleaseRestrictionsSpecification|[The.Unknown.Girl.2016.1080p.BluRay.DD5.1.x264-DON] No restrictions apply, allowing
17-8-13 15:19:43.9|Debug|QualityAllowedByProfileSpecification|Checking if report meets quality requirements. Bluray-1080p v1
17-8-13 15:19:43.9|Trace|ConfigService|Using default config value for 'minimumage' defaultValue:'0'
17-8-13 15:19:43.9|Debug|MinimumAgeSpecification|Minimum age is not set.
17-8-13 15:19:43.9|Trace|ConfigService|Using default config value for 'retention' defaultValue:'0'
17-8-13 15:19:43.9|Debug|RetentionSpecification|Checking if report meets retention requirements. 182
17-8-13 15:19:43.9|Trace|DownloadDecisionMaker|Spec SameEpisodesGrabSpecification does not care about movies.
17-8-13 15:19:43.9|Trace|DownloadDecisionMaker|Spec DailyEpisodeMatchSpecification does not care about movies.
17-8-13 15:19:43.9|Trace|DownloadDecisionMaker|Spec EpisodeRequestedSpecification does not care about movies.
17-8-13 15:19:43.9|Trace|DownloadDecisionMaker|Spec SeasonMatchSpecification does not care about movies.
17-8-13 15:19:43.9|Debug|SeriesSpecification|Checking if movie matches searched movie
17-8-13 15:19:43.9|Trace|DownloadDecisionMaker|Spec SingleEpisodeSearchMatchSpecification does not care about movies.
17-8-13 15:19:43.9|Debug|DelaySpecification|Ignoring delay for user invoked search
17-8-13 15:19:43.9|Debug|HistorySpecification|Skipping history check during search
17-8-13 15:19:43.9|Debug|MonitoredEpisodeSpecification|Skipping monitored check during search
17-8-13 15:19:43.9|Debug|AvailabilitySpecification|Skipping availability check during search
17-8-13 15:19:43.9|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] 16.0 GB is larger than maximum allowed 12.7 GB (for La Fille inconnue), [Permanent] French is wanted, but found English


And so on...

**Comment by tchit** [comment]
"French is wanted, but found English" of course because it looks for the translated English title :(

**Comment by galli-leo** [comment]
Nah, from the logs it seems Radarr is searching your indexers by imdbid of the movie. Am I correct in the assumption that the french versions on your indexer are not tagged with the imdbid?

**Comment by tchit** [comment]
I guess you are right, I would like Radarr to just search for release by name instead of imdbid when it's a non-English movie. Is there a way to do this?
Thanks a lot!

**Comment by galli-leo** [comment]
Currently not, that's something I want to add in the future though.

**Comment by tchit** [comment]
That would be awesome. Many specific releases (foreign language movies for example) can't be found by imdbid tag on the big indexers but are available on Binsearch for example. Thanks a lot for your amazing work.
