### ISSUE TITLE
Add Year Filter to Movie Editor [Feature Request]

### ISSUE THREAD

**Issue by sammykins12** [Radarr/Radarr#1915]
Add the ability to filter or sort by year to the movie editor

**Comment by JoeB99** [comment]
Use case:
Someone imports a bunch of movies from couch potato wanted lists; and it has set all the quality profiles to HD. Some of the movies were released in the 80's and 90's and probably dont have a HD version, so there needs to be a way to sort by year. Then the user can tick down the list everything before 2000, and bulk set them to SD.

**Comment by jj-uk** [comment]
Stale? Can we reopen this ? I'd really like to see it implemented.

**Comment by jj-uk** [comment]
I have a significant amount of movies that are pre-90's that could really do with being marked as SD profile. A sort on release date would be helpful.

**Comment by Cyno01** [comment]
Nother thing this would be useful for... splitting between drives when you run out of space. Movies (d:) is full, so add Movies 2 (f:), move and change root drive of everything <1990 to Movies 2 so things are at least still that organized on the backend.

**Comment by Cyno01** [comment]
Is this implemented in any version yet? I need to do exactly what i said i wanted to do and was prepared to do it the hard way, but if the feature is done and i dont have to...

**Comment by ta264** [comment]
Its done in Aphrodite (V3)
