### ISSUE TITLE
Sort by downloaded not working.

### ISSUE THREAD

**Issue by rickytin** [Radarr/Radarr#1919]
I have Radarr Ver. 0.2.0.816 nightly and sort by downloaded not working.

**Comment by rickytin** [comment]
Radarr Ver. 0.2.0.827 and still sort by downloaded not working.

**Comment by galli-leo** [comment]
"Intentionally done". Will hopefully get fixed once I sort out the issues with db queries.

**Comment by galli-leo** [comment]
Though I might just disable it and move this to Better Filtering options.
