### ISSUE TITLE
Unrated Releases Treated as Incorrect

### ISSUE THREAD

**Issue by teshiburu** [Radarr/Radarr#192]
Hi Guys, 

It would seem something is suspect with the REGEX for identifying releases, and it would seem that Unrated is being treated as part of the film name, so the movie isnt grabbed. 

![image](https://cloud.githubusercontent.com/assets/7904118/21888461/4a1ad980-d8bc-11e6-956d-85989be82c11.png)

**Comment by teshiburu** [comment]
OK - i can confirm that it is indeed tripping up with the "unrated" comment

I edited the index entry, removed the Unrated text, and it grabbed it happily

![image](https://cloud.githubusercontent.com/assets/7904118/21889824/bca44b8e-d8c2-11e6-8ec2-9315b76f4298.png)

**Comment by onedr0p** [comment]
@galli-leo Unrated should go into the edition column?
