### ISSUE TITLE
Supporting Jackett API v2.0

### ISSUE THREAD

**Issue by zero77** [Radarr/Radarr#1920]
Hi
Jackett has just upgraded their API to v2 and now Radarr doesn’t seam to work with the latest Jackett versions.

**Comment by supremacy2k** [comment]
zero77, If you keep the old url to jackett, radarr will work.
Just tested on an indexer with the new url, and it failed, but works fine with the old one.

http://URL:PORT/torznab/TRACKER

**Comment by zero77** [comment]
Thanks, but its not working for me, what version are you using.

**Comment by hotio** [comment]
I was also not able to get it to work with using the old url, not in radarr and not in sonarr. Had to rollback Jackett for the time being.

**Comment by hotio** [comment]
Jackett version 0.8.40.0 works OK again.

**Comment by supremacy2k** [comment]
I'm using Radarr version 0.2.0.778, Sonarr version 2.0.0.4949 with Jacket version 0.8.26.0
Old url works on both. (havent updated since i wrote that last comment)

**Comment by zero77** [comment]
It seems to working again in the new Jackett.
