### ISSUE TITLE
Radarr - wont download files automatically

### ISSUE THREAD

**Issue by Lusiphur** [Radarr/Radarr#1924]
Like it says in the title. I can search and tell it to download a file manually but if I add a new movie with eligible downloads it will not download them until I do it manually. Same with new releases.

Version
0.2.0.778
Mono Version
5.0.1.1 (2017-02/5077205 Thu May 25 09:19:47 UTC 2017)**

Nothing relevant in logs.

[radarr.txt](https://github.com/Radarr/Radarr/files/1220021/radarr.txt)

**Comment by jamesmacwhite** [comment]
There are reports of Mono 5.0 causing various problems. Have you recently upgraded Mono or tried downgrading to 4.8?

**Comment by alz41** [comment]
Same problem on Windows10, Radarr Ver. 0.2.0.820

**Comment by galli-leo** [comment]
@Lusiphur @alz41 How are you guys adding movies? Radarr (same as Sonarr) does not "actively" search for your movies. It watches the latest releases of your indexers and then downloads them if they match a movie you want. This is why you should add a movie with the add and search button. This way it will certainly be downloaded.

**Comment by Lusiphur** [comment]
So that’s understandable for older releases. However, the same thing happens for new releases. For example, I added King Arthur (crap film) months ago but had to manually search for it two days after it was available on my indexer to get it.

Note, I also have Sonarr on the same box and it behaves fine for new releases of TV shows and ofc it pulls many more releases.

**Comment by galli-leo** [comment]
@Lusiphur What minimum availability setting did you set King arthur to?

**Comment by Lusiphur** [comment]
Everything is set to minimum availability announced.

**Comment by galli-leo** [comment]
That seems like a strange occurrence. Did you have this with every new film?

**Comment by Lusiphur** [comment]
So far, since I installed Radarr on this new server about 2 months back. It’s hard to test because obviously I have to choose a film that has yet to be released on the scene. I have a couple coming up in the next monthish so I should be able to verify.

I mean I could just add something just released but as you say that will still require a manual search.

**Comment by galli-leo** [comment]
What interval do you have RSS Sync set at and do you have radarr running 24/7?

**Comment by Lusiphur** [comment]
RSS Sync is hourly and Radarr is in a Ubuntu 16.04 VM on my home server that is up 24x7.

**Comment by galli-leo** [comment]
@Lusiphur Can you search your log for messages similar like this one?: Indexer ... rss sync didn't cover the period between ... and ...

**Comment by Lusiphur** [comment]
No such messages found in radarr.txt under ~/./config/Radarr/logs.

**Comment by Peng82** [comment]
Lusiphur if you add something at the top of an indexers movie list and then go to the System > Tasks tab and refresh the RSS Sync task it will do an immediate check and because you chose something at the top it will be in the 100 fetched by the rss sync.  This would allow you to test things a little easier.

**Comment by galli-leo** [comment]
@Lusiphur ^This might be a good Idea. I suspect the rss sync interval is too low, so it missed some releases.

**Comment by Lusiphur** [comment]
That actually worked fine. So I should set the rss sync interval to 15 mins like Sonarr? I just left it at the default 1 hour.

Note I am piping to the indexer (IPT) through Jackett so full search is available.

**Comment by Peng82** [comment]
Glad that worked for you :) Mine is set to 30 mins and it works fine.  I don't think I have ever seen 100 posts in 30 mins. But just experiment a little to find your sweet spot

**Comment by galli-leo** [comment]
Yeah 30 minutes seems like a sensible interval.
