### ISSUE TITLE
Extra rename options

### ISSUE THREAD

**Issue by Eikelman** [Radarr/Radarr#193]
Would it be possible to add more rename options for the folder and file?

For example adding 'Quality' to the folder name and 'Original Folder Name' for the file, just like in CP?

Thanks.

**Comment by c0rnflake** [comment]
{Original_Folder_Name} would be nice for both the directory and video file {Original_Folder_Name}/{Original_Folder_Name}.{ext} etc

**Comment by DTrace001** [comment]
Something like this would be nice as well. Similar to filebots capability:
```
{n.replaceAll(/:\?/,'-').replacePart('')} ({y})/{n.replaceAll(/:\?/,'-').replacePart('')} ({y}){' - part'+pi}{' ('+fn.match(/Extended/)+')'} {'['+certification+']'}{genres.take(3)}[{vf}{'.'+source}{'.'+vc}{'.'+BITDEPTH+'Bit'}{'.'+af}{'.'+ac}{'.'+fn.match(/DD5.1/)}{'.'+fn.match(/IMAX/)}]{'.'+lang}"
```
MyMovie (2016) [R][Drama, History, War][1080p.BluRay.x264.8Bit.6ch.AC3].mkv
