### ISSUE TITLE
Timestamp otion to use file creation date

### ISSUE THREAD

**Issue by ptr727** [Radarr/Radarr#1934]
I am migrating from Couchpotato to Radarr.

I have a post-processing script that prepares the files for use in Plex (sets language, remux, etc.).
The script stores some file history, so that it does not process unmodified files on startup, and it uses the file modified timestamp as trigger, i.e. if the file is modified after the cache timestamp then process the file again.

Since I switched to Radarr, the script is not triggered when Radarr replaces a file, e.g. 720p with 1080p.
Unlike Couchpotato, Radarr seems to preserve the timestamp from the archive, and the script breaks.

Please add an option to set the timestamp to the current time, i.e. Change File Date: None, In Cinemas, Physical Release Date, Current Date

Radarr Version: 0.2.0.778
OS: Windows Server 2016, running as console

**Comment by hotio** [comment]
Let your downloader reset the datetime of the files for now...

**Comment by ptr727** [comment]
I tried to find an option on sabnzbd to do this, could not find anything, do you know of such an option?

**Comment by io-node** [comment]
I would also like an option to have it use the current date. This also for processing, and also for Kodi so the Recently Added list even shows older files at the top.

**Comment by bakerboy448** [comment]
Closing
v0.2 is no longer being actively developed.

If this is still an issue/request on recent v3 builds, please open a new issue.
