### ISSUE TITLE
Drone Factory folder is not handled?

### ISSUE THREAD

**Issue by pven** [Radarr/Radarr#1936]
Radarr Version: latest

Logs:
There is nothing in the log

Sometimes I download well known movies by myself. When the download is completed, it is in a specific directory on my NAS. I mentioned this directory in the drone factory. But Radarr never picks them up.

What can I do so Radarr will pick them up?

**Comment by pven** [comment]
When debugging I see:
```
17-8-14 10:16:24.7|Debug|Parser|Parsing string 'Kings_Bay_(2017)_1080p_BRRemux'
17-8-14 10:16:24.7|Debug|Parser|Movie Parsed. Kings Bay - 2017
17-8-14 10:16:24.7|Debug|Parser|Language parsed: English
17-8-14 10:16:24.7|Debug|QualityParser|Trying to parse quality for Kings_Bay_(2017)_1080p_BRRemux
17-8-14 10:16:24.7|Debug|Parser|Quality parsed: HDTV-1080p v1
17-8-14 10:16:24.7|Debug|Parser|Release Group parsed:
```
But the file is still where it was.

**Comment by weirdcrap** [comment]
I have no idea if I am right or not, this is just speculation but I know upstream the Sonarr team has deprecated drone factory as a feature due to it being unreliable and technically superseded by the manual import wizard: https://github.com/Sonarr/Sonarr/wiki/Health-checks#drone-factory-is-deprecated

Maybe there have been some initial steps taken by the Radarr team to follow suit and deprecate the Drone Factory functionality?

**Comment by jamesmacwhite** [comment]
Its probably a good idea to also start displaying the Bootstrap alert on Drone Factory as Sonarr is doing this as it is being deprecated, likewise for the HealthCheck message as well when its enabled.

**Comment by pven** [comment]
Ah ... let me disable the drone factory

For my view: importing manually is the way to go?

**Comment by jamesmacwhite** [comment]
Yes. As @weirdcrap stated, its being deprecated.

https://github.com/Radarr/radarr/wiki/Health-Checks#drone-factory-is-deprecated

**Comment by galli-leo** [comment]
Nah it should still work. However, it will only import movies already added to Radarr, which I am guessing is why it isn't working here.

**Comment by pven** [comment]
@galli-leo is right: the movie was not added in Radarr
