### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by tidusjar** [Radarr/Radarr#194]
Hi,

There have been a few requests to add Radarr support into Ombi.

Where can I find the API Documentation?

**Comment by onedr0p** [comment]
Unfortunately we aren't at the point yet. It's close to sonarr's API. If you want you can poke around logging XHR requests in the Chrome console and test using a client like [insomnia](https://insomnia.rest/)

**Comment by galli-leo** [comment]
To add to what onedr0p said. You can just start Radarr and open the Chrome Dev tools. Go to Network and you should see all API calls. Most of the stuff is very similar to Sonarr, except it has movie instead of series.

**Comment by galli-leo** [comment]
If you have further questions, you can just come and hop on our discord: https://discord.gg/NWYch8M

**Comment by Keelan** [comment]
Hopefully Plex Requests/Ombi incorporate this .

**Comment by tidusjar** [comment]
I know that Radarr is still not on Stable, but I have been bitten before around integrating with a product too early.

Are there any planned changes for the API? Do you plan to version the API to stop any API changes breaking other applications?

**Comment by MartinAyla** [comment]
Does the Radarr API offer a way to add a movie based on a IMDb ID?

**Comment by tidusjar** [comment]
It requires TheMovieDbId

**Comment by galli-leo** [comment]
@tidusjar The idea is to keep the existing API exactly like it is today. So we don't break any applications using the API. However, we will probably add new endpoints to the API.

**Comment by tidusjar** [comment]
@galli-leo That's good to know! 

I was just worried that I do all this work, go live and then you guys change how one of your existing endpoints work!

**Comment by galli-leo** [comment]
@tidusjar I think we will keep this open for now.

**Comment by tidusjar** [comment]
@Keelan This is now in the Early Access Preview version of Ombi

**Comment by Keelan** [comment]
You guys are awesome. I'll check it out and report back.

**Comment by tidusjar** [comment]
Man stale bot you are killing me here!

**Comment by galli-leo** [comment]
@tidusjar Haha, sorry :P It should stop now

**Comment by jurpeedurp** [comment]
Is there a new discord? that link is dead.

**Comment by Qstick** [comment]
Seems to work fine here

**Comment by Qstick** [comment]
Swagger docs started for V3

**Comment by austinwbest** [comment]
For v3 users, https://radarr.video/docs/api/ is where the documentation is located. The v3 docs are **ongoing updates and not final**.

**Comment by Qstick** [comment]
Closing this done, most useful 3rd party popular endpoints are documented
