### ISSUE TITLE
QNAP won't start

### ISSUE THREAD

**Issue by turkeyphant** [Radarr/Radarr#1941]
**Description:**
No indexers or downloaders were appearing in my install so tried to press the restart button. Never came back. 
Stopped and started through QNAP App Center. Never came back.
Now installed again from scratch through QNAP App Center. Still won't load.

Any ideas?

**Radarr Version:**
0.2.0.696
QMono 4.8.1.0

**Comment by galli-leo** [comment]
Can you try getting logs? Without them I won't be able to help much :/

**Comment by turkeyphant** [comment]
Not sure where they are stored on the QNAP. In the end I managed to remove the QPKG, install an older QPKG. Delete files. Install the newer QPKG over the top. Then update through the web interface...
