### ISSUE TITLE
Sort movies by popularity

### ISSUE THREAD

**Issue by king8084** [Radarr/Radarr#1947]
not sure what happened, i have two lists, my watchlist and popular list...before i had movies on my watchlist show first, then popular list show in order of rank in imdb

but now the list is in alphabetical order randomly

what happened?

[AB#900](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/900)

**Comment by galli-leo** [comment]
Seems to work fine for me. Can you try again?

**Comment by king8084** [comment]
I tried everything but its not working, only thing i did today was add PTP indexer and download station download client

I deleted the list now and will add it back in few hours to try again

**Comment by king8084** [comment]
deleting and adding the list back does not fix it, still sort them by alphabetical 

note i am on Synology if it matters
here is a gif i made to highlight the issue
http://i.imgur.com/QSvG2yL.gifv

**Comment by galli-leo** [comment]
Ah. That's after you have imported them. Currently you cannot sort your movies by popularity. So I am gonna go ahead and convert this into a feature request.

**Comment by king8084** [comment]
Weird. They were sorted exactly like they were on imdb for 3 days tho

**Comment by galli-leo** [comment]
Strange. Did you maybe sort by the added date?

**Comment by king8084** [comment]
How do u even do that? They were sorted by popularity like on imdb and randomly stopped when i enabled torrent download

**Comment by galli-leo** [comment]
You should have a button called sort at the top of the page.

**Comment by king8084** [comment]
hmmmm i never recall ever touching that but i see that it was on "title" i made it "profile" and it fixed it

my synology shutdown everyday for 8 hours, could it be after it restart it default to title? i will report back tomorrow

otherwise thank you
