### ISSUE TITLE
Options to improve releases search

### ISSUE THREAD

**Issue by leloki** [Radarr/Radarr#1950]
Hi,

related with : 
#334 
#1912 
or
#1886 

I think a lot of people have issues to find the good releases they want in their indexers (that is the main goal of Radarr after all) because of the way the releases are searched.

Personally, I think the search tool (in add a new movie) is perfect even in foreign language (french for me). Radarr does find in the tmdb/imdb the right movie.

The problem is the way it tries to find releases. The https://mappings.radarr.video site is a first step to improve it. But unfortunatly this new feature is useless if Radarr does not find any result in the indexers (because of bad search title or year for example).

Is it possible to add in "Edit Movie" a way to manually add : 
- alternative titles (list)
- alternative years (list)

If these fields are not empty, Radarr will try to search, after the default releases search, these new terms.

Maybe even a way to be more precise like the Movie Naming section of Media Management options, to define the Release Search Format ?

Thank you for your great app !

Loki

**Radarr Version:**
Radarr Ver. 0.2.0.831

**Comment by leloki** [comment]
Hi guys,

what do you think ?

**Comment by galli-leo** [comment]
Personally I agree we could do a lot more with the new alternative titles system. I surely want to flesh it out more over the coming months.

A few things:
Settings such as release search format should probably be on a per indexer basis.
Also, ask your indexer to support searching by imdbid. Then you don't have to watch out for titles anymore :)

**Comment by Qstick** [comment]
Not planning to allow manual adding titles.
