### ISSUE TITLE
WebDL gets marked as Remux

### ISSUE THREAD

**Issue by MisterSkilly** [Radarr/Radarr#1954]
**Description:**

http://i.imgur.com/8pdDi3q.png

Radarr thinks (at torrent/nzb search process) a WebDL (with Remux in the title) is a Remux. This might be exclusive to AwesomeHD, as they mark non-WebRIPs as h.264 Remux WebDLs. 
Luckily, when importing the files using Torrent Blackhole Radarr assumes they're WebDL again. (and as such downloads the next wrongly matched WebDL 'Remux'  😛 )

**Radarr Version:** 0.2.0.778

**Comment by Quiksmage** [comment]
+1 if that can be fixed. I was hesitant to post it here since Remux IS in the title, haha.
