### ISSUE TITLE
Bug: Going to any page then back to homepage screws up the sorting

### ISSUE THREAD

**Issue by king8084** [Radarr/Radarr#1955]
so i finally know how to reproduce this https://github.com/Radarr/Radarr/issues/1947

basically going to any tab then back to homepage change the sorting to title, even if you have it set at profile, this is what happens to imdb popular list using a gif

http://i.imgur.com/rMykx0f.gifv

as you can see, first it is sorting threads based on imdb popular sorting, but if i go to any tab then back it screws it up and it shows them sorted by title, this is reproducable 100%, please note that me having "announced" only has nothing to do with the bug, i did that to easily show the situation, this happens even during "all"

**Comment by king8084** [comment]
im on synology latest build 0.2.0.778

**Comment by king8084** [comment]
108

**Comment by king8084** [comment]
not sure if you did something from your side, but now its working fine (after my synology restarted tho i doubt it had something to do with it)

now heres a gif showing its working fine
http://i.imgur.com/6A3CPs9.gifv

as you can see the sorting does not change anymore going from one tab to back to homepage

**Comment by king8084** [comment]
can this get fixed?

it is so annoying....

https://i.imgur.com/DrcQJk3.gifv

**Comment by galli-leo** [comment]
It's kinda hard to fix, if I can't reproduce it.

**Comment by king8084** [comment]
Are you using imdb popular list? It should be reproduced 100% of the time with it

**Comment by galli-leo** [comment]
Is this still happening on the latest version of Radarr? Still unable to reproduce even with the exact steps provided.

**Comment by king8084** [comment]
No this was fixed a while ago
