### ISSUE TITLE
Folder path is automatically removed from lists

### ISSUE THREAD

**Issue by julienki** [Radarr/Radarr#1961]
Hello,

When I try to configure a new list (for ex : StevenLu) I select the folder but as soon as i click save the folder is automatically removed from the config.

I have tried to delete all saved folders and add again them in a new list but it is the same.

It happens only when I configure new lists, old ones keep their configured folders.

Thanks for your help

**Comment by hotio** [comment]
Version??

**Comment by julienki** [comment]
0.2.0.778

**Comment by tomsommer** [comment]
Can confirm

**Comment by galli-leo** [comment]
Fixed on latest nightly or with Safari and Edge.

**Comment by djzeratul** [comment]
Looks like @danjames92 is experiencing this in both regular and incognito mode of Firefox Quantum, so I am reopening to investigate

**Comment by galli-leo** [comment]
@danjames92 Apparently, firefox needs to have select tags (dropdowns) inside a form, for the selected attribute to work. Since these are technically not form and generated, not much we can do besides not using firefox :P
