### ISSUE TITLE
Allow Movie Editor to Change 'Downloaded' Quality Label (Not Just Desired Profile) Request

### ISSUE THREAD

**Issue by hmgnsd** [Radarr/Radarr#1962]
Allow Movie Editor to Change 'Downloaded' Quality Label (Not Just Desired Profile). 

As Radarr in my case and others incorrectly identifies the resolution quality of the files I've added, it occasionally downloads movies I don't need as it thinks a better quality file is available. We can currently bulk select movies and change the 'monitored' status or the 'profile', but we can only go entry by entry, one by one, to change the actual 'Downloaded' file status with 'edit information bout this file'. And then when going back to the list of movies in the library the page jumps back to the top when it refreshes.

Thank you for your time :)

Radarr Version: 0.2.0.778
Mono Version 4.8.0 (Stable 4.8.0.495/e4a3cf3 Mon Feb 27 08:30:18 UTC 2017)

**Comment by Diluted22** [comment]
This would be very nice as I have imported a lot of movies. I have a spread sheet with all of their resolutions and can edit them all my self and since I don't want to rename the files to have the resolution on it. Please and thank you

p.s. love your app thank you so much

**Comment by chansearrington** [comment]
+1

Is there any other way to do this in bulk?

**Comment by bonfire62** [comment]
+1. Would greatly appreciate this

**Comment by Qstick** [comment]
In v3 Radarr reads resolution to set quality if not in file, not planning on creating a bulk quality editor
