### ISSUE TITLE
Trakt anticipated list issues

### ISSUE THREAD

**Issue by astlaurent** [Radarr/Radarr#1965]
**Description:**
Hi 

I am so in love with radarr. Thank you for such a great product.
I am not sure if I did something wrong but I am not sure the trakt anticipated list is working properly. I am getting very obscure movies in my radarr. When I go to the trakt anticipated web site I see movies on the first page that I would think would get imported but they did not. 
For example I got a movie named ice cream truck but yet the new Jurassic World is not there.

Thank you for any assistance

**Radarr Version:**
Latest nightly
**Logs:**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by darthShadow** [comment]
Still facing the same issue. Any possible fixes?

> Version
> 0.2.0.1067
> Mono Version
> 5.12.0.226 (tarball Thu May 3 09:48:32 UTC 2018)
