### ISSUE TITLE
XMLRPC requests to rTorrent time out, but NOT test requests.

### ISSUE THREAD

**Issue by tynan-cr** [Radarr/Radarr#1967]
**Description:**

What is currently working:
I am connecting to rTorrent via ruTorrent's `rpc.php` plugin, using `https` as well as username and password authentication. Running a _download client test_ from the GUI returns successfully, and I can see `200` statuses in the nginx logs in response to a POST request to the `rpc.php` url. I also see output in the rTorrent `xmlrpc` logs.

What is not working:
When I add _some_ movies from PTP, the only tracker I can test with, the download queueing spinner spins for a long time, until I get a `Request timed out` from NZB drone in my logs. 

NOTE: This happens for some specific .torrent files, and never resolves for those files, even with a restart.

Thanks for any help. If anyone knows how I can intercept the xmlrpc request for debugging without editing/recompiling the source code for radarr, please let me know.

**Radarr Version:**
```
Version
0.2.0.778
Mono Version
4.8.1 (Stable 4.8.1.0/22a39d7 Wed Apr 12 12:00:40 UTC 2017)
```

**Logs:**
```
System.Net.WebException: The request timed out
  at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x00052] in <5641e4edad4f4464ba58c620a7b8ea48>:0 
  at System.Net.HttpWebRequest.GetResponse () [0x0000e] in <5641e4edad4f4464ba58c620a7b8ea48>:0 
  at CookComputing.XmlRpc.XmlRpcClientProtocol.GetWebResponse (System.Net.WebRequest request) [0x00002] in <9d687fb9c46d481292a78781773c6116>:0
```

**Comment by galli-leo** [comment]
Does this happen in sonarr too?

**Comment by tynan-cr** [comment]
I am not sure, I have never used Sonarr, sorry. (I know, its hard to help when your user only has one tracker and one program!).

I occasionally get a very similar (same?) error with the Download Monitoring service as seen below
Error:
```
Unable to retrieve queue and history items from rTorrent: The request timed out
```
Stacktrace:
```
System.Net.WebException: The request timed out
  at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x00052] in <5641e4edad4f4464ba58c620a7b8ea48>:0 
  at System.Net.HttpWebRequest.GetResponse () [0x0000e] in <5641e4edad4f4464ba58c620a7b8ea48>:0 
  at CookComputing.XmlRpc.XmlRpcClientProtocol.GetWebResponse (System.Net.WebRequest request) [0x00002] in <9d687fb9c46d481292a78781773c6116>:0
```
Thank you

**Comment by tynan-cr** [comment]
It may be possible that there is some issue on rTorrent's end with repeatedly serving a download history request when every single download is seeding (and the response is unchanging): as is the case when this error appears most frequently (approximately every 2 minutes).

However, this does not explain why the PTP .torrent XMLRPC times out every time, without success.

**Comment by galli-leo** [comment]
Yeah seems kinda weird. How many torrents do you have in rTorrent? Can you also try going over normal http?

**Comment by tynan-cr** [comment]
Disabling SSL and going through port 80 completely solved this problem. Thanks! I would love to investigate this when I have a chance (can't clone the repo on my current internet connection). 

Any ideas why SSL is being troublesome? Since rutorrent's configuration does not change and sits behind the nginx server, it seems to be an issue with nginx config or SSL contexts in CookComputing XMLRPC library.

**Comment by tynan-cr** [comment]
Nginx configuration differences below (The HTTPS config comes from [pimp-my-box](https://github.com/pyroscope/pimp-my-box/blob/1a44673c1c6a558c795e391ff61e0ef229955095/roles/rutorrent/templates/nginx-rutorrent.con)f:
HTTPS:
```
server {
    listen              443 default_server;
    listen              [::]:443 default_server ipv6only=on;
    server_name         ubuntu-seedbox;
    server_tokens       off;

    root                /usr/share/nginx/htdocs;
    index               index.html;

    # Master for these settings:
    #   https://mozilla.github.io/server-side-tls/ssl-config-generator/
    #   ?server=nginx-1.4.6&openssl=1.0.1f&hsts=yes&profile=modern

    # Certs sent to the client in "SERVER HELLO" are concatenated in `ssl_certificate`.
    ssl                 on;
    ssl_certificate     /etc/nginx/ssl/cert.pem;
    ssl_certificate_key /etc/nginx/ssl/cert.key;
    ssl_session_timeout 1d;
    ssl_session_cache   shared:SSL:50m;

    # Diffie-Hellman parameter for DHE ciphersuites, recommended 2048 bits.
    ssl_dhparam         /etc/nginx/ssl/dhparam.pem;

    # Modern configuration. Tweak to your needs.
    ssl_protocols       TLSv1.1 TLSv1.2;
    ssl_ciphers         'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!3DES:!MD5:!PSK';
    ssl_prefer_server_ciphers on;

    # HSTS (`ngx_http_headers_module` is required; 15768000 seconds = 6 months)
    add_header          Strict-Transport-Security max-age=15768000;

    ### OCSP Stapling - fetch OCSP records from URL in ssl_certificate and cache them.
    ##ssl_stapling        on;
    ##ssl_stapling_verify on;

    # Verify chain of trust of OCSP response using Root CA and intermediate certs.
    ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;
```


Altered for HTTP:
```
server {
    listen              80 default_server;
    listen              [::]:80 default_server ipv6only=on;
    server_name         ubuntu-seedbox;
    server_tokens       off;

    root                /usr/share/nginx/htdocs;
    index               index.html;

    # Master for these settings:
    #   https://mozilla.github.io/server-side-tls/ssl-config-generator/
    #   ?server=nginx-1.4.6&openssl=1.0.1f&hsts=yes&profile=modern

    # Certs sent to the client in "SERVER HELLO" are concatenated in `ssl_certificate`.
    ssl                 off;

    # HSTS (`ngx_http_headers_module` is required; 15768000 seconds = 6 months)
    add_header          Strict-Transport-Security max-age=15768000;
```

**Comment by galli-leo** [comment]
Maybe 1d for ssl_session_timeout is an invalid value and it defaults to something to low? Can you try commenting out all unneeded ssl_* config stuff?

**Comment by mtehonica** [comment]
Looks like I've been getting the same errors and it is not happening with Sonarr...

>17-8-24 13:07:14.5|Warn|DownloadMonitoringService|Unable to retrieve queue and history items from Whatbox
[v0.2.0.832] System.Net.WebException: The request timed out
  at System.Net.HttpWebRequest.GetRequestStream () <0x41494be0 + 0x0016b> in <filename unknown>:0 
  at CookComputing.XmlRpc.XmlRpcClientProtocol.Invoke (System.Object clientObj, System.Reflection.MethodInfo mi, System.Object[] parameters) <0x4147eb40 + 0x0023d> in <filename unknown>:0 
  at CookComputing.XmlRpc.XmlRpcClientProtocol.Invoke (System.Reflection.MethodInfo mi, System.Object[] Parameters) <0x4147eb00 + 0x00027> in <filename unknown>:0 
  at XmlRpcProxy78284195-effb-4ff4-aeab-ad7df9fc0cd2.TorrentMulticall (System.String[] parameters) <0x4147e920 + 0x00097> in <filename unknown>:0 
  at NzbDrone.Core.Download.Clients.RTorrent.RTorrentProxy.GetTorrents (NzbDrone.Core.Download.Clients.RTorrent.RTorrentSettings settings) <0x41472d70 + 0x002dc> in <filename unknown>:0 
  at NzbDrone.Core.Download.Clients.RTorrent.RTorrent.GetItems () <0x41470910 + 0x000cd> in <filename unknown>:0 
  at NzbDrone.Core.Download.TrackedDownloads.DownloadMonitoringService.ProcessClientDownloads (IDownloadClient downloadClient) <0x415ca910 + 0x00141> in <filename unknown>:0

**Comment by galli-leo** [comment]
One thing you can try is increasing the nginx timeout.
