### ISSUE TITLE
Sample File Being Moved As Movie

### ISSUE THREAD

**Issue by kylerw** [Radarr/Radarr#197]
When a download includes a sample file, It is being moved in place of the actual movie file.

**Comment by galli-leo** [comment]
That should not happen. Can you post a log? How long is your sample file?

**Comment by kylerw** [comment]
Yeah, it happened on two separate movies. Let me grab the logs. Since I didn't realize that's what happened I redownloaded a different release and I don't see anything in the log about it happening. Let me do some digging to see what I can find.

**Comment by galli-leo** [comment]
Do you know the runtime of these sample files?

**Comment by kylerw** [comment]
I've since deleted them but the one I played showed a run time of 1 hour and 40 minutes in the player but was actually only about 4 minutes, it appeared. So this may have been a fluke based on something in the release/sample that was included.

**Comment by galli-leo** [comment]
Yeah that confused Radarr. It checks the runtime and if it's longer than 6 minutes assumes it's a movie.

**Comment by kylerw** [comment]
@galli-leo would it make sense to add a secondary check on the name of the file?

**Comment by galli-leo** [comment]
We could. But as long as the sample file is not corrupted while downloading, the length should show up fine. So for now, it does not make much sense.

**Comment by madvtak** [comment]
Mine only moves the movie but keeps the sample file in the original download folder and throws an eorror. 

![image](https://cloud.githubusercontent.com/assets/18261123/21973992/ff15298a-db78-11e6-917c-8f069f511526.png)

**Comment by kylerw** [comment]
Happened again for two movies. Hacksaw Ridge and Bad Santa 2.

**Comment by galli-leo** [comment]
What are the runtime of those samples?

**Comment by onedr0p** [comment]
@kylerw you need to post logs and the sample runtimes if you expect the problem to be solved. Thanks.

**Comment by 4getit** [comment]
Same issue here. It happens a lot for me.

Here's an example:

Nzbget downloaded the 5.6GB file and Radarr wrote the 27MB sample file instead of the actual file.

The runtime of this sample was 1:01 (1 minute and 1 second)

```
17-2-26 18:58:11.7|Info|NzbSearchService|Searching 6 indexers for [Star Wars: The Force Awakens]
17-2-26 18:59:55.9|Info|RssSyncService|Starting RSS Sync
17-2-26 19:00:20.6|Info|RefreshMovieService|Updating Info for Star Wars: The Force Awakens
17-2-26 19:00:21.2|Warn|DiskScanService|Series' root folder (/home/user/CompletedRD) is empty.
17-2-26 19:00:52.8|Info|MovieService|Adding Movie [][Star Wars: The Force Awakens] Path: [/home/user/CompletedRD/Star Wars The Force Awakens (2015)]
17-2-26 19:00:52.8|Info|MediaCoverService|Downloading Poster for [][Star Wars: The Force Awakens] http://image.tmdb.org/t/p/original/weUSwMdQIa3NaXVzwUoIIcAi85d.jpg
17-2-26 19:00:52.9|Info|RefreshMovieService|Updating Info for Star Wars: The Force Awakens
17-2-26 19:00:53.2|Warn|DiskScanService|Series' root folder (/home/user/CompletedRD) is empty.
17-2-26 19:00:53.2|Info|MovieScannedHandler|[Star Wars: The Force Awakens] was recently added, performing post-add actions
17-2-26 19:00:53.5|Info|NzbSearchService|Searching 6 indexers for [Star Wars: The Force Awakens]
17-2-26 19:00:53.7|Info|MediaCoverService|Downloading Banner for [tt2488496][Star Wars: The Force Awakens] http://image.tmdb.org/t/p/original/njv65RTipNSTozFLuF85jL0bcQe.jpg
17-2-26 19:05:29.0|Info|DownloadDecisionMaker|Processing 497 releases
17-2-26 19:05:32.2|Info|RssSyncService|RSS Sync Completed. Reports found: 497, Reports grabbed: 0
17-2-26 19:06:32.7|Info|DownloadDecisionMaker|Processing 747 releases
17-2-26 19:06:57.0|Info|Nzbget|Adding report [Star.Wars.Episode.VII.The.Force.Awakens.2015.BRRip.x264.1080p-NPW] to the queue.
17-2-26 19:06:57.5|Info|DownloadService|Report sent to Nzbget. Star.Wars.Episode.VII.The.Force.Awakens.2015.BRRip.x264.1080p-NPW
17-2-26 19:06:57.6|Info|MovieSearchService|Movie search completed. 1 reports downloaded.
17-2-26 19:07:05.6|Info|DownloadDecisionMaker|Processing 847 releases
17-2-26 19:10:30.9|Warn|DownloadedMovieImportService|Non-sample file detected: [/home/user/nzbget/downloads/completed/Movies/Star.Wars.Episode.VII.The.Force.Awakens.2015.BRRip.x264.1080p-NPW/Star Wars Episode VII The Force Awakens 2015 BRRip x264 1080p-NPW.mp4]
```
