### ISSUE TITLE
Cannot add category 2010

### ISSUE THREAD

**Issue by sahara101** [Radarr/Radarr#1973]
Hello, 

i am using radarr on qnap. Currently not able to add filelist as my indexer. I want it with only ID 2010 which according to jackett it is Movies/Foreign. Filelist.cs looks like this:

AddCategoryMapping(19, TorznabCatType.MoviesForeign); //Movies HD-RO
https://github.com/Jackett/Jackett/blob/master/src/Jackett/Indexers/FileList.cs

Error in radarr is No results were returned from your indexer, please check your settings.
It is like the ID is incorrect, how can I find the correct one for HD-RO? 

Thank you

**Description:**

Check first that your problem is not listed in our wiki section:
* https://github.com/Radarr/Radarr/wiki/Common-Problems
* https://github.com/Radarr/Radarr/wiki/FAQ

Provide a description of the feature request or bug here, the more details the better. 
Please also try to include the following if you are reporting a bug

**Radarr Version:**

**Logs:**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by galli-leo** [comment]
Did you try force adding the indexer by disabling search & rss sync, adding the indexer and then reenabling them?

**Comment by sahara101** [comment]
Thank you! It is working now. Don't know if force adding it solved the issue or updating radarr (forgot after install).
