### ISSUE TITLE
An exception should be made for titles containing "Multisub" since they are usually not hardcoded.

### ISSUE THREAD

**Issue by djmixman** [Radarr/Radarr#1974]
Multisub is being detected as hardcoded subs. An exception should be made for this since Multisub is usually not hardcoded.

[image](https://user-images.githubusercontent.com/491274/29500716-e6898206-85e8-11e7-9796-70be7ab17eef.png)

**Comment by galli-leo** [comment]
What do you mean by usually? Have you come across one which was hardcoded? Btw. you can do this yourself via Settings -> Indexers -> Whitelisted Subtitle Tags.

**Comment by djmixman** [comment]
I have not ran across one that was hardcoded. I use usually just to cover my ass in the rare instance of that one. However, I never noticed the whitelist subtitles... Problem solved!
