### ISSUE TITLE
Radarr not restarting via dashboard intermittently 

### ISSUE THREAD

**Issue by sumoyoshikai** [Radarr/Radarr#1975]
hey guys,

really struggling with this. I've set everything up perfectly and it all works perfectly fine, then I will reboot it via the software and it doesn't open again but only intermittently, as sometimes it works sometimes it doesn't.... which makes no sense at all

I can reboot the ubuntu server and it will be fine and I can tick reboot, it will restart radarr..... then magically a few hours later I can do the same thing only for it to not even come back up again without rebooting the machine

any ideas how to fix this PERMANENTLY because it's just becoming a huge pain in the right now

when I try and force it to start via systemd I get it "active" and then it seems a few seconds later it's dead

nas@nas:~/.config/Radarr/logs$ systemctl status radarr.service
● radarr.service - Radarr
Loaded: loaded (/etc/systemd/system/radarr.service; enabled; vendor preset: enabled
Active: inactive (dead) since Mon 2017-08-21 14:31:17 AEST; 6min ago
Process: 25092 ExecStart=/usr/bin/mono /opt/radarr/Radarr.exe -nobrowser (code=exite
Main PID: 25092 (code=exited, status=0/SUCCESS)
Aug 21 14:31:06 nas systemd[1]: Started Radarr.

I can kill the pid and use sudo systemctl start radarr.service and it does start back up. this is not something I wish to have to do every time I want to restart radarr...

**Comment by hotio** [comment]
This is not really an issue with radarr......

**Comment by sumoyoshikai** [comment]
so it's an issue with what exactly? because sonarr, etc all work fine... I've formatted, reinstalled, changed all permissions, sometimes it works... sometimes it doesnt

rebooting it works every single time. restarting from the dashboard works ~30% of the time

so in your best thoughts my system is configured incorrectly 70% of the time when no changes are made and 30% of the time it just... happens to magically reconfigure itself to work again?

**Comment by hotio** [comment]
Its hard to tell without logs

**Comment by sumoyoshikai** [comment]
the only things log show is this - 

17-8-21 14:31:06.9|Info|Bootstrap|Starting Radarr - /opt/radarr/Radarr.exe - Version 0.2.0.778
17-8-21 14:31:17.6|Info|SingleInstancePolicy|1 instance(s) of Sonarr are running
17-8-21 14:31:17.6|Warn|SingleInstancePolicy|Another instance of Radarr is already running.
17-8-21 14:31:17.6|Info|Bootstrap|Application is being terminated. Reason : Another instance is already running
17-8-21 14:41:14.8|Info|Bootstrap|Starting Radarr - /opt/radarr/Radarr.exe - Version 0.2.0.778
17-8-21 14:41:35.8|Info|MigrationLogger|*** Migrating data source=/home/nas/.config/Radarr/nzbdrone.db;cache size=-10485760;datetimekind=Utc;journal$
17-8-21 14:41:36.5|Info|MigrationLogger|*** Migrating data source=/home/nas/.config/Radarr/logs.db;cache size=-10485760;datetimekind=Utc;journal mod$
17-8-21 14:41:37.1|Info|Router|Application mode: Interactive
17-8-21 14:41:37.1|Info|OwinHostController|Listening on the following URLs:
17-8-21 14:41:37.1|Info|OwinHostController|  http://*:7878/
17-8-21 14:41:38.1|Info|NancyBootstrapper|Starting NzbDrone API
17-8-21 14:44:16.8|Info|PreDBService|Starting PreDB Sync
17-8-21 14:44:56.4|Warn|MediaCoverMapper|File /home/nas/.config/Radarr/MediaCover/94/poster.jpg not found
17-8-21 14:44:56.4|Warn|MediaCoverMapper|File /home/nas/.config/Radarr/MediaCover/101/poster.jpg not found
17-8-21 14:44:56.4|Warn|MediaCoverMapper|File /home/nas/.config/Radarr/MediaCover/111/poster.jpg not found
17-8-21 14:44:56.5|Warn|MediaCoverMapper|File /home/nas/.config/Radarr/MediaCover/107/poster.jpg not found
17-8-21 14:44:56.5|Warn|MediaCoverMapper|File /home/nas/.config/Radarr/MediaCover/110/poster.jpg not found
17-8-21 14:44:56.5|Warn|MediaCoverMapper|File /home/nas/.config/Radarr/MediaCover/84/poster.jpg not found
17-8-21 14:44:56.5|Warn|MediaCoverMapper|File /home/nas/.config/Radarr/MediaCover/93/poster.jpg not found
17-8-21 14:45:17.9|Info|LifecycleService|Restart requested.
17-8-21 14:45:19.5|Info|Bootstrap|Starting Radarr - /opt/radarr/Radarr.exe - Version 0.2.0.778
17-8-21 14:45:26.8|Info|SingleInstancePolicy|1 instance(s) of Sonarr are running
17-8-21 14:45:26.8|Warn|SingleInstancePolicy|Another instance of Radarr is already running.
17-8-21 14:45:26.8|Info|Bootstrap|Application is being terminated. Reason : Another instance is already running

my system doesnt magically change settings 30% of the time when I click the reboot button in the dashboard

**Comment by hotio** [comment]
No it does not change settings 30% of the time, it only messea up 30% of the time. Why are you starting radarr multiple times?

**Comment by sumoyoshikai** [comment]
why would I start radarr multiple times. as I mentioned in my original post, I reboot the system and it works. I click "reboot" in the dashboard and it fails to start back up 70% of the time. it does start back up sometimes.

I can kill the processes instead of using "reboot" in the dashboard and launch  via sudo systemctl start radarr.service and it works. clicking reboot in the dashboard then fails again.

having to reboot my whole system just to restart radarr is my bug. "not having anything to do with radarr" it has everything to do with radarr.

**Comment by hotio** [comment]
It says so that you are starting up multiple instances in the log....

**Comment by hotio** [comment]
But normally you should only restart with systemd

**Comment by sumoyoshikai** [comment]
great, I guess they can remove the reboot button in the dashboard then if that's the incorrect way of rebooting radarr...

**Comment by hotio** [comment]
You should figure out with what command lines radarr restarts itself and how systemd reacts to the restart.

**Comment by sumoyoshikai** [comment]
that's the whole purpose of posting this in the "issues" section, to have someone who knows what they are talking about hopefully explain how this can be fixed.

Radarr working fine on rebooting my system here, press reboot button in dashboard and this is the log:

17-8-21 17:34:16.0|Info|LifecycleService|Restart requested.
17-8-21 17:34:18.4|Info|Bootstrap|Starting Radarr - /opt/radarr/Radarr.exe - Version 0.2.0.778
17-8-21 17:34:29.3|Info|SingleInstancePolicy|1 instance(s) of Sonarr are running
17-8-21 17:34:29.3|Warn|SingleInstancePolicy|Another instance of Radarr is already running.
17-8-21 17:34:29.3|Info|Bootstrap|Application is being terminated. Reason : Another instance is already running

Doesn't come back up automatically so kill the process still lingering and use command:

sudo systemctl start radarr

17-8-21 17:38:42.6|Info|Bootstrap|Starting Radarr - /opt/radarr/Radarr.exe - Version 0.2.0.778
17-8-21 17:38:51.1|Info|MigrationLogger|*** Migrating data source=/home/nas/.config/Radarr/nzbdrone.db;cache size=-10485760;datetimekind=Utc;journal$
17-8-21 17:38:51.6|Info|MigrationLogger|*** Migrating data source=/home/nas/.config/Radarr/logs.db;cache size=-10485760;datetimekind=Utc;journal mod$
17-8-21 17:38:51.9|Info|Router|Application mode: Interactive
17-8-21 17:38:51.9|Info|OwinHostController|Listening on the following URLs:
17-8-21 17:38:51.9|Info|OwinHostController|  http://*:7878/
17-8-21 17:38:52.5|Info|NancyBootstrapper|Starting NzbDrone API

and now it works. but restart via dashboard completely broken. I will wait for someone who knows what they are talking about to hopefully offer some assistance.

**Comment by sumoyoshikai** [comment]
yeah well I mean restarting via the UI is better than having to try and manually find and then kill the PID or shut down the whole system just to restart one service.

seems to be similar problems with posts I found on Sonarr pages:

https://forums.sonarr.tv/t/wont-load-thinks-multiple-instances-are-loaded/3585
https://www.reddit.com/r/sonarr/comments/5vjou5/another_instance_is_already_running_ubuntu/
https://forum.openmediavault.org/index.php/Thread/13611-Sonarr-another-instance-is-running-Webgui-will-not-load/

and this on Radarr github even:

https://github.com/Radarr/Radarr/issues/29

**Comment by jamesmacwhite** [comment]
You can restart Radarr via the systemd daemon, if things go really bad, no need to reboot the whole system or looks for PIDs. Looks like you've got a radarr.service setup, so running either should workaround the issue, saving any full restart or `top` activity!

```
systemctl stop radarr.service
systemctl start radarr.service
```

OR

```
systemctl restart radarr.service
```

The linked issue on here, shouldn't be a problem more. That was back when Radarr forked Sonarr early on and a lot of stuff will have pointed to Sonarr specific areas i.e. ports, handlers etc, you can run Sonarr and Radarr independently now as far as I know.

Do you also run Sonarr? If so do you experience similar restart issues via the UI also? Just trying to get some background.

**Comment by sumoyoshikai** [comment]
Linux nas 4.10.0-32-generic #36~16.04.1-Ubuntu SMP Wed Aug 9 09:19:02 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

'nas' user is just the only user I created on Ubuntu 16.04, it's only used to share files on my network is all. That's cool, I can leave it open. It just means I will have to do a full system shut down automatically each night to make sure it continues running or manually start and stop the process. 

thanks for your help mate

**Comment by jamesmacwhite** [comment]
Cool, that's easier to test if its just Ubuntu on a Linux box.

If you've setup the radarr.service in the same way as sonarr.service and that works OK, then might have to look at the codebase to investigate.

**Comment by jamesmacwhite** [comment]
Might also be worth sharing your systemd file for Radarr and Sonarr if possible, just to understand how the daemon has been configured.

**Comment by galli-leo** [comment]
Is systemctl configured to automatically restart killed processes? Might be a race condition.

**Comment by danjames92** [comment]
Sounds like QuickBox is being used but not explicitly said, maybe @sumoyoshikai can clarify.

If so, there's a github of how the systemd services are configured and by default radarr isn't set to auto restart...

**Comment by sumoyoshikai** [comment]
sorry here are the service files.

[Unit]
Description=Radarr
After=syslog.target network.target

[Service]
User=nas
Group=nas

Type=simple
ExecStart=/usr/bin/mono /opt/radarr/Radarr.exe -nobrowser
TimeoutStopSec=20
KillMode=process
Restart=on-failure

[Install]
WantedBy=multi-user.target

[Unit]
Description=Sonarr
After=syslog.target network.target

[Service]
User=nas
Group=nas

Type=simple
ExecStart=/usr/bin/mono /opt/NzbDrone/NzbDrone.exe -nobrowser
TimeoutStopSec=20
KillMode=process
Restart=on-failure

[Install]
WantedBy=multi-user.target

at the moment a user online gave me a bash script that he uses to keep it running and that script is 

https://pastebin.com/mp5DSzHs (change the name of the process to whatever it is obviously) and that works

**Comment by danjames92** [comment]
So you are or aren't using Quickbox?

**Comment by sumoyoshikai** [comment]
I have no idea what quickbox is so I'm going to say no plus I never once even mentioned whatever that is anywhere here. Anyway, I've setup an automatic full system restart at 6am every morning so if it fails at any time during the day it's only going to be down for upto 24 hours. Not at all ideal, rendering it effectively useless if i'm away from home for that period of time.

the bash script I was given works ok, I guess since this is not fixable no point leaving this open
