### ISSUE TITLE
[Feature Request] The ability to wipe file details/properties when Radarr is moving/copying files into their destination

### ISSUE THREAD

**Issue by RonGeorge** [Radarr/Radarr#1976]
Several release groups add Title and Comment into files before torrenting them. When they are downloaded, and then moved, they retain these details. Plex, among other programs, uses these details as trump cards over metadata and will populate the titles with what is found in the file properties.

The result: If you ever get a release from RARBG, you have to go into file explorer and right click, remove details, save the file, then refresh metadata.

**Comment by jamesmacwhite** [comment]
@RonGeorge You can adjust the priority of how Plex treats the metadata in files within Plex itself.

Basically in the agent settings move "Local Media Assets" down or just disable entirely for the indexer you use i.e. TMDb, thus avoiding Plex using the title embedded in the metadata.

In terms of removing it, you can batch process a library with tools mp4box (MP4) or mkvtoolnix (MKV) to remove the metadata itself.

**Comment by RonGeorge** [comment]
I just unchecked each of the local media assets under Agents and hopefully that will fix that. Thanks guys.

**Comment by RonGeorge** [comment]
Close #1976

**Comment by RonGeorge** [comment]
“Closed”
