### ISSUE TITLE
Multiple of one type downloaded

### ISSUE THREAD

**Issue by tommy-b-10** [Radarr/Radarr#1979]
**Description:**
I am trying to download a movie (doesnt matter which one) and it will begin downloading multiple copies of the movie with slightly different qualities.

I have my profiles set as below
![profiles](https://user-images.githubusercontent.com/7692933/29565740-535fadee-8786-11e7-8d53-3cc599a2f5fa.PNG)

And when found, I get three BluRay 1080p versions downloading in qBittorrent as shown
![torrents](https://user-images.githubusercontent.com/7692933/29565763-6c217128-8786-11e7-8f47-59a59d35e3e3.PNG)

Any help? I only ever want one version of a movie downloaded.

**Radarr Version:**
0.2.0.778

**Logs:**
`

  | MovieSearchService | Movie search completed. 0 reports downloaded. | 10:00pm
-- | -- | -- | --
  | ProcessDownloadDecisions | Couldn't  add report to download queue. Batman.Begins.2005.BluRay.1080p.x264-CHD:  Unexpected character encountered while parsing value: O. Path '', line  0, position 0. | 10:00pm
  | ProcessDownloadDecisions | Couldn't  add report to download queue.  Batman.Begins.2005.1080p.BluRay.x264.DTS-FGT: Unexpected character  encountered while parsing value: O. Path '', line 0, position 0. | 10:00pm
  | ProcessDownloadDecisions | Couldn't  add report to download queue.  Batman.Begins.2005.1080p.BluRay.H264.AAC-RARBG: Unexpected character  encountered while parsing value: O. Path '', line 0, position 0. | 10:00pm
  | DownloadDecisionMaker | Processing 9 releases | 10:00pm
  | NzbSearchService | Searching 1 indexers for [Batman Begins] | 10:00pm
  | MovieScannedHandler | [Batman Begins] was recently added, performing post-add actions | 9:59pm
  | DiskScanService | Scanning disk for Batman Begins | 9:59pm
  | RefreshMovieService | Updating Info for Batman Begins | 9:59pm
`

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by hotio** [comment]
First start with configuring your profile properly...

**Comment by hotio** [comment]
Oh and update to the latest version if using qbittorrent.

**Comment by galli-leo** [comment]
Or downgrade qbittorrent. Yeah an update to qbittorrent broke the api integration. Hopefully the fix will be released to develop in a few days.
