### ISSUE TITLE
Filmaffinity's list

### ISSUE THREAD

**Issue by nelbu** [Radarr/Radarr#1981]
www.filmaffinity.com is a huge database and rating system in the hispanic world, maybe the biggest IMDb competitor. It has list's functionality, you can see one of them here: [Arquitectura y cine](https://www.filmaffinity.com/es/mylist.php?list_id=1001)

Could be possible to add Filmaffinity to the list settings? #

**Comment by galli-leo** [comment]
Do they have an api?

**Comment by galli-leo** [comment]
Or rss feed?

**Comment by Meiden-fc** [comment]
Useful? https://github.com/dsantosmerino/filmaffinity-api

**Comment by galli-leo** [comment]
@Meiden-fc Not really, it's unofficial and only provides the title (not even the year of the movie).

**Comment by Meiden-fc** [comment]
Well, shamefully, FA doesn't provide any official API so I think that this feature can't be developed.
