### ISSUE TITLE
"Prefer special indexer flags" overrides "Prefer Usenet" in auto-search priority

### ISSUE THREAD

**Issue by desimaniac** [Radarr/Radarr#1983]
If I have the setting "Prefer special indexer flags" ON, this will ignore "Prefer Usenet" under Delay Profiles and will result in torrents being listed at the top of auto-search priority. 

![image](https://user-images.githubusercontent.com/5501908/29590716-c2d71cb4-8760-11e7-85e5-2d1f203ddf6f.png)

Radarr version: 0.2.0.840
nightly

**Comment by hotio** [comment]
Is already a known issue...

**Comment by hotio** [comment]
https://github.com/Radarr/Radarr/issues/1814

**Comment by desimaniac** [comment]
Yup your right, I missed that.

**Comment by galli-leo** [comment]
Duplicate of #1814
