### ISSUE TITLE
Radarr keeps trying to import movies that have been deleted from the downloads folder

### ISSUE THREAD

**Issue by desimaniac** [Radarr/Radarr#1985]
Some time ago I had some movies on the downloads folder that I didnt want anymore. I deleted them from the folder. But radarr still "sees" them, somehow, even after multiple restarts, and keeps trying to import them..

![image](https://user-images.githubusercontent.com/5501908/29590920-e1771e7a-8761-11e7-98b4-1452f1d8c07c.png)

Radarr version: 0.2.0.840
nightly

**Comment by hotio** [comment]
Remove from download client

**Comment by desimaniac** [comment]
Thanks that worked. I removed it from NZBGet's History, and it stopped trying to import them. 

Is this a bug?

**Comment by hotio** [comment]
Not sure, does it happen always? It can occasionally ocur, iirc it happens with sonarr too.

**Comment by desimaniac** [comment]
Don't think it happened before until them most recent nightly. Not seeing it happen with Sonarr right now.

**Comment by hotio** [comment]
I had it happen perhaps 3 times over 6 months...

**Comment by desimaniac** [comment]
Perhaps I wasn't seeing it before because I periodically would clean up the history.
