### ISSUE TITLE
small bug if you have IMDB watchlist and IMDB popular lists enabled

### ISSUE THREAD

**Issue by king8084** [Radarr/Radarr#1986]
so

if you have IMDB watchlist set to "monitor" and IMDB popular list to "unmonitor" a small annoying bug happens, if you are browsing IMDB and decide to add a movie to your watchlist, it does not become "monitored" if it is on IMDB popular list, it stays as "unmonitored"

**Comment by galli-leo** [comment]
As a workaround, make sure you delete both lists and add back your personal watchlist first.
