### ISSUE TITLE
Wanted -> Cutoff Unmet never loads

### ISSUE THREAD

**Issue by fryfrog** [Radarr/Radarr#1987]
**Description:** Trying to visit Wanted -> Cutoff Unmet results in balls going back and forth forever. Behavior is the same via Incognito window, also reproduced by someone in #support on Discord.

![screen shot 2017-08-23 at 11 09 44 am](https://user-images.githubusercontent.com/87748/29631422-73dd2894-87f4-11e7-81af-70201fcc42f8.png)

**Radarr Version:** 0.2.0.840

**Logs:** https://ptpb.pw/WbvN

**Comment by mocram** [comment]
This is a known bug, already known by @galli-leo

**Comment by galli-leo** [comment]
Duplicate issue. (On mobile so cant link)
