### ISSUE TITLE
Add Movie -> Discover New Movies lost "more" expander at bottom

### ISSUE THREAD

**Issue by fryfrog** [Radarr/Radarr#1988]
**Description:** The Discover New Movies now only shows 10 movies and has no expander at the bottom like it used to.

![screen shot 2017-08-23 at 11 14 09 am](https://user-images.githubusercontent.com/87748/29631404-642da5cc-87f4-11e7-8794-4cd0d7622ab7.png)

**Radarr Version:** 0.2.0.840

**Logs:** https://ptpb.pw/Wte9

**Comment by desimaniac** [comment]
+1. See the same issue.

**Comment by jamesmacwhite** [comment]
Should be resolved latest nightly. Changes reverted.
