### ISSUE TITLE
Case sensitive paths are made pretty

### ISSUE THREAD

**Issue by fryfrog** [Radarr/Radarr#1989]
**Description:** Paths are case sensitive and thus should *not* be made pretty. In display, existing paths are made pretty. Unsure of case where new paths are added.

![screen shot 2017-08-23 at 11 17 47 am](https://user-images.githubusercontent.com/87748/29631560-e1e2a6ca-87f4-11e7-8b59-3c1d5962e86b.png)

In the above example, the *actual* path is `/cold/videos/Movies` but is displayed as `/Cold/Videos/Movies` instead.

**Radarr Version:** 0.2.0.840

**Comment by jamesmacwhite** [comment]
Should be resolved latest nightly. Changes reverted.

**Comment by fryfrog** [comment]
Indeed, closing.
