### ISSUE TITLE
Radarr web ui stop responding

### ISSUE THREAD

**Issue by BurningTheSky** [Radarr/Radarr#1990]
The Radarr web ui service keeps freezing and I'm not sure what is happening or how to diagnose it as I'm not sure when it starts. Other processes with a web ui on the same machine still run, like sonarr. 

Running on Ubuntu 16.04, Version 0.2.0.778 and Mono Version 5.0.1.1

**Comment by galli-leo** [comment]
Can you try incognito window and different browser? Also how does it freeze? Temporarily or the whole session? How many movies do you have?

**Comment by BurningTheSky** [comment]
It just happened again so I have tried incognito mode and it made no difference. Same with another browser. I'm not sure what you mean by temp or session? The web page doesn't load at all but when I restart the service the logs suggest that it has still been running in the background. I think around 600

**Comment by piejanssens** [comment]
I have a similar issue: https://github.com/Radarr/Radarr/issues/2388
@BurningTheSky Did you get yours solved?

**Comment by seanvree** [comment]
Yeah, I"m getting this problem as well. 

OS: Windows 10E 1709 FCU
Radarr Ver. 0.2.0.912

Seems that it's sending Downloads to the client (i'm using both Deluge and Sabnzbd) but then it doens't report their status in the WebUI, or import them when they are done?  No errors in the logs

**Comment by BurningTheSky** [comment]
Unfortunately it solved itself so I'm not much help, sorry

On 2 Jan 2018, at 10:48, Pieter Janssens <notifications@github.com<mailto:notifications@github.com>> wrote:


I have a similar issue: #2388<https://github.com/Radarr/Radarr/issues/2388>
@BurningTheSky<https://github.com/burningthesky> Did you get yours solved?
