### ISSUE TITLE
Request: Show links to IMDB, TMBD, and Rotten Tomatoes when adding movies

### ISSUE THREAD

**Issue by desimaniac** [Radarr/Radarr#1992]
Can we add Rotten Tomatoes to the links on the "Movie" page, and also add those links to the "Adding Movies" page? This will allow us to quickly look up ratings for the movie we are about to add. 

Example:
![image](https://user-images.githubusercontent.com/5501908/29646223-c9e9d266-8847-11e7-8501-2e6def299f4b.png)

with..

![image](https://user-images.githubusercontent.com/5501908/29646234-ddc19a94-8847-11e7-8d53-6d58691ee529.png)

Edit: I know clicking the thumbnail can take you to TMDB, but that's not obvious. Took me a while to figure it out myself :p.

**Comment by BinaryJay** [comment]
A link to RT would still be helpful.
