### ISSUE TITLE
DroneFactory Import - Incorrect Quality

### ISSUE THREAD

**Issue by SlothCroissant** [Radarr/Radarr#2001]
**Issue** 
When using DroneFactory import, movies are being properly recognized under "Media Info", but not in "Quality. Movies are processed by FileBot AMC script before import, so the filename is `MovieName (year)`.

For example, moments after import:

Title: Blade Runner (1982).mkv
Media Info: AVC (1920x800) (01:57:36) DTS (English)
Size: 12.4GB
Quality: HDTV-720p

**Version**
0.2.0.778
Mono Version
5.2.0.215 (tarball Mon Aug 14 15:46:12 UTC 2017)

**Logs:**
I can't get the logs page on the WebUI to load properly - it just spins forever, and the logfiles (`/radarr/logs/radarr.txt`) doesn't show anything of value:

```
17-8-25 08:50:35.1|Info|MovieService|Linking [Blade Runner (1982).mkv] > [[tt0083658][Blade Runner (1982)]]
17-8-25 08:50:35.1|Info|MovieService|Linking [Blade Runner (1982).mkv] > [[tt0083658][Blade Runner (1982)]]
```

If there are more verbose logs somewhere, do let me know and I can grab them.

**Comment by hotio** [comment]
Use proper naming scheme that includes quality and disable adblocker...

**Comment by SlothCroissant** [comment]
Thanks for the tip regarding the AdBlock - that did the trick.

Regarding the "proper" naming convention - Radarr *does* recognize the file quality - it knows it's AVC (1920x800) (01:57:36) DTS (English) because I have media analysis enabled. Can it not use this to determine quality? Everyone's naming convention is `\Movie (year)\Movie (year).ext`. Thus why FileBot is set up to rename to this. It's a simple change in the naming structure of FileBot to make this work, but just curious as to why Radarr isn't able to glean the quality info.

Side note - if I move the renamed media to the proper folder myself, then "update" the library for that item to rescan the disk, it works as expected - quality gets determined as it should.

Will pull some logs comparing the two processes, and report back my findings.

**Comment by galli-leo** [comment]
It should actually do that. At least it did for me a few releases back on the bulk import. Maybe the process for manual import is different. I will have to take a look at that logic someday anyways.
