### ISSUE TITLE
Feature Request: Minimum Movie Size

### ISSUE THREAD

**Issue by mccorkled** [Radarr/Radarr#2002]
I was hoping you guys could add a minimum movie size.  Several of my providers are snatching "720p" movies that are 700GB which is obviously horrible. CP has a feature where you can set min and max which works great. I have my max set in Radarr but cannot set a min for anything other than min size for 90 minute movie. 

Thanks :)

**Comment by hotio** [comment]
A 700GB movie file should look great... Is it 8k?

**Comment by gregcbrown** [comment]
How about MAXIMUM movie size...

**Comment by galli-leo** [comment]
I think he meant 700MB ;). Anyways, the minimum movie size is not only for 90 minute movies. It is calculated per minute of movie runtime. The 90 minute one is just an example.

**Comment by mccorkled** [comment]
Yes I meant 700MB. Basically DVD quality. I have to keep manually going through and removing them rather than just setting something like "only grab movies between 3000 - 7000 MB

**Comment by hotio** [comment]
Then why don't you set it like that?

**Comment by mccorkled** [comment]
I did not see that you could slide the bar from the left side as well.
