### ISSUE TITLE
Feature Request : Monitored and Not Monitored

### ISSUE THREAD

**Issue by JWMutant** [Radarr/Radarr#2003]
I have looked high and low for a setting that may suit my needs and maybe I have missed it.

If you have a movie set to monitored it will automatically search for a movie that fits your search parameters then start to download it. Once its download it will rename it if you so choose and move it to the folder you choose. All is great at this point in time.

But can we have a option that automatically changes it to Not Monitored if thats what we want to do.

Otherwise if I understand it correctly if its finds the same movie but a slightly better version it will start to download it.

Manually changing it from Monitored to Not Monitored is an option, but I have 1400 1080p movies and am always adding to the list so manually changing it will get rather old rather quickly.

**Comment by galli-leo** [comment]
Thats what profile cutoff is for. When Radarr reaches this quality with a lovie it will stop downloading better releases.
