### ISSUE TITLE
Feature Request : Metadata definitions

### ISSUE THREAD

**Issue by JWMutant** [Radarr/Radarr#2004]
Just a small thing but my OCD get twitchy every time I look at the metadata tab.

Can we change the definitions to be movie specific?

Generally speaking movies dont have episodes and seasons.

Something along the lines of  

Movie Metadata
Folder Images
Back Drop Images  ( With a minimum or maximum amount of back drops)

I understand this is a port of Sonarr but understanding what I am trying to grab on the meta data side is a plus.

**Comment by galli-leo** [comment]
Thats not implemented yet. Gonna close this issue as one is already open for that.
