### ISSUE TITLE
[BUG] Radarr attempts to delete downloaded movie after deleting original file.

### ISSUE THREAD

**Issue by danjames92** [Radarr/Radarr#2009]
Radarr v 0.2.0.846 - Nightly

Original file was called Aliens (1986).mkv tagged as HDTV-1080p. Upgraded to remux. 

17-8-27 21:02:13.6|Info|RefreshMovieService|Updating Info for Aliens
17-8-27 21:02:14.2|Info|DiskScanService|Scanning disk for Aliens
17-8-27 21:02:22.4|Info|MovieService|Linking [Aliens (1986) [Remux-1080p.LAZY].mkv] > [[tt0090605][Aliens (1986)]]
17-8-27 21:02:22.4|Info|DiskScanService|Completed scanning disk for Aliens
17-8-27 21:03:33.2|Info|MovieService|Linking [A Dog's Purpose (2017) [Remux-1080p.BMF].mkv] > [[tt1753383][A Dog's Purpose (2017)]]
17-8-27 21:03:33.2|Info|RecycleBinProvider|Recycling Bin has not been configured, deleting permanently. /mnt/media/Movies/Aliens (1986)/Aliens (1986) [Remux-1080p.LAZY].mkv

**Comment by galli-leo** [comment]
No idea what's happening here, would need a debug or trace log to find out.

**Comment by bojanrajkovic** [comment]
This is happening to me as well. It's a little hard to get a debug or trace log when Radarr is _destroying all your files_. It seems to be related to having the download client configured.
