### ISSUE TITLE
Not auto finding/recognizing movie that has finished downloading (seems weird character issue?)

### ISSUE THREAD

**Issue by tr1plus** [Radarr/Radarr#2010]
**Description:**
My movie renamer/copy works, however I seem to have issues for 1 movie: Sword Art Online The Movie: Ordinal Scale
This movie just stays in my downloaded folder from transmission

I noticed that the name in the path is in korean/japanese/chinese/whatever as can be seen in the screenshot below. It may have to do something with that?

![image](https://user-images.githubusercontent.com/7044850/29788882-73304a36-8c34-11e7-8c71-701e89485b4b.png)

**Radarr Version:**
0.2.0.778

**Logs:**
N/A

**Comment by galli-leo** [comment]
That may definitely be the issue. Can you try renaming the path via edit movie to the english name?

**Comment by tr1plus** [comment]
@galli-leo Hey, still no luck; Path is now: /share/Elements/Movies/Sword Art Online The Movie: Ordinal Scale (2017)
Movie is named Sword Art Online the Movie: Ordinal Scale (2017).mkv in download folder with permissions rwxrwxrwx (so should not be an issue)

I just verified if it still works by re-copying another movie in downloaded folder and it took that up no problem

Thanks for looking into this

**Comment by kmlucy** [comment]
I'm also having an issue with this, but mine doesn't have any weird characters: `Wonder Woman (2017).mkv`

**Comment by kmlucy** [comment]
Actually, it looks like mine is a separate issue. I'm going to open a separate bug report.

**Comment by galli-leo** [comment]
Can you take a look at your logs and see if there is anything there regarding the download?

**Comment by tr1plus** [comment]
Hey
When I crtl+f the log file for part of the movie name only the following comes up
`17-8-30 19:49:46.2|Info|RefreshMovieService|Updating Info for Sword Art Online The Movie: Ordinal Scale
17-8-30 19:49:46.7|Info|DiskScanService|Scanning disk for Sword Art Online The Movie: Ordinal Scale`

So It seems it is trying but no luck.
I attached my 2 most recent logs for your information
[radarr.0.txt](https://github.com/Radarr/Radarr/files/1264759/radarr.0.txt)
[radarr.txt](https://github.com/Radarr/Radarr/files/1264760/radarr.txt)

**Comment by tr1plus** [comment]
@galli-leo Hey, have you been able to check some things out? If you want I can provide more information/details.

Thanks

**Comment by galli-leo** [comment]
Sorry for not coming back to you sooner, must have missed the notification :/ Anyways, not seeing anything in the logs regarding a failed import, so not much I can do. Maybe a permissions issue?
