### ISSUE TITLE
Naming all movies _unpack 

### ISSUE THREAD

**Issue by alkiax** [Radarr/Radarr#2013]
**This didn't start happening until today I'm guessing during the update. All movies get named to unpack and don't get named correctly or moved to the correct folder.:**

Check first that your problem is not listed in our wiki section:
* https://github.com/Radarr/Radarr/wiki/Common-Problems
* https://github.com/Radarr/Radarr/wiki/FAQ

Provide a description of the feature request or bug here, the more details the better. 
Please also try to include the following if you are reporting a bug

**0.2.0.846:**

**Couldn't import movie \\server\folder\movies\movie.mkv: The process cannot access the file because it is being used by another process.
:**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by fryfrog** [comment]
The `_unpack` convention is generally something from the downloader. What are you using? Torrents or Usenet? Which downloader?
