### ISSUE TITLE
[Request] Option to hide the Add button

### ISSUE THREAD

**Issue by sigboe** [Radarr/Radarr#2014]
**Description:**

Please add an option to hide the `Add` button. So that the only button when adding the movie is `Add and search for movie`. Maybe these two icons would be combined if this option was selected.

Reason is that the wife sometimes hits the add button, and dont realize why i it doesn't work.

**Radarr Version:** 

Nightly

**Logs:**

Not needed

**Comment by hotio** [comment]
Perhaps add it to feathub, if a million people want it... Maybe, who knows.

**Comment by sigboe** [comment]
@hotio Thanks, I didnt know about that page.

**Comment by hotio** [comment]
Perhaps it would be a good idea to replace the add button with a add+manual search popup...

**Comment by fryfrog** [comment]
I'd +1 something that'd make the buttons clearer, but hiding one of them is a poor idea. They both have fairly equally important uses. If you're adding a movie that is already available for download, add + search is idea. But if you're adding a movie that *isn't*, just adding is ideal. If you used add + search in this case, at best you'll get nothing and at *worst* you'll end up with some lame fake or cam or who knows what.

**Comment by hotio** [comment]
radarr could also do this:

1 button, when adding, do a search if it is released according to minimum availability, if not , just add it.

Then again, I like just adding them and doing a manual search.

**Comment by jwvanderbeck** [comment]
Does that button even serve a purpose? I am talking about the big + button on the main toolbar as it were.  That is something that doesn't exist in Sonarr.  If I want to add a new movie I can easily do some from the Add button in the movies page, same way I would in Sonarr by going to the Series page.

**Comment by onedr0p** [comment]
This is an old issue tagged with UI, this is very likely fixed in v3. Please let us know otherwise (and even if you want this feature in v3) and we will reopen the issue.
