### ISSUE TITLE
Radarr unable to match all movies

### ISSUE THREAD

**Issue by jkaberg** [Radarr/Radarr#2016]
I got 1180 movies in my library, however Radarr only finds 1065 of these.

I've gathered the folder names in a list, perhaps you can run the list against the parser in Radarr and filter out what it can't match? The UI doesn't tell me.

https://pastebin.com/mxVXQacc

**Comment by Logvin** [comment]
You should consider using an application like FileBot to rename the files into better file name format.

**Comment by hotio** [comment]
Kinda useless list without the folders.

**Comment by jkaberg** [comment]
@Logvin Yes, that will probably solve the problem however; most subtitle downloaders can't (or don't) hash the media file when looking for subtitles (this mitigates the nameing problem), instead in most cases they match subtitles based on filename and size. So when you rename you're entire library to a name standard which doesn't identify the origins of the media file, you lose the possibility of being able to re-search for subtitles later on.

This is the very reason why I haven't renamed my library (except for a few movies which Radarr just recently downloaded - ignoring my setting to keep original folder name).

**Comment by jkaberg** [comment]
@hotio that list contains only folder names. However here is a list of foldername -> contents, https://cloud.eth0.im/s/WUpIOOvOldyaMhn

**Comment by hotio** [comment]
Ah sorry, what happens when you use a folder structure like recommended?

**Comment by jkaberg** [comment]
Radarr actully matched everything now. Problem was my nginx proxy timed out against Radarr (as Radarr was takeing a long time matching all movies).

Solved it with increasing the timeout, my apologizes 😄
