### ISSUE TITLE
Movie-folder is not recognized

### ISSUE THREAD

**Issue by pven** [Radarr/Radarr#2020]
On disk I have a nice movie in a folder /volume1/remote/media/Movies/Nice Movie (2017) WEBDL-720p x264.AAC

I configured the following:
![2017-08-30 12_16_52-settings - radarr](https://user-images.githubusercontent.com/671621/29867902-5135f670-8d7d-11e7-891d-2b89b1361d65.jpg)

When I edit a movie and change the path to the path mentioned in the first line the log shows:
```
17-8-30 12:14:50.2|Info|RefreshMovieService|Updating Info for Nice Movie
17-8-30 12:14:51.2|Info|RenameMovieFileService|[tt4703048][Nice Movie (2017)]'s movie should be /volume1/remote/media/Movies/Nice Movie (2017) according to your naming config.
17-8-30 12:14:51.2|Info|DiskScanService|Scanning disk for Nice Movie
17-8-30 12:14:51.5|Info|MovieService|Linking [Nice.Movie.2017.720p.WEB-DL.mkv] > [[tt1234567][Nice Movie (2017)]]
17-8-30 12:14:51.6|Info|DiskScanService|Completed scanning disk for Nice Movie
```

Did I miss some configuration?

**Comment by pven** [comment]
After enabling 'Automatically Rename Folders' it renames the folders automatically, and it looks like the error is gone. But somehow I have the feeling this is not the way it should go?

**Comment by galli-leo** [comment]
This is how the feature is intended to work. Now radarr will dynamically change the movie folder every time a disk refresh occurs.
