### ISSUE TITLE
|Trace|Owin|SQLite warning (284): automatic index on AlternativeTitles(MovieId)

### ISSUE THREAD

**Issue by Cykle** [Radarr/Radarr#2023]
Hi there.
Im using radarr+deluge and get this sql error.
I tried all sort of things but cant get anything in radarr working but bulk importing, that works flawlessly btw.  mover and activity is a no go :(

[radarr.trace.txt](https://github.com/Radarr/Radarr/files/1265128/radarr.trace.txt)
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/1265129/radarr.debug.txt)

Radarr :0.2.0.846
Unraid : 6.3.5

**Comment by galli-leo** [comment]
That isn't an error though? Not sure what you mean by mover and activity. Also what other things are not working?

**Comment by Cykle** [comment]
So ive reinstalled both utorrent and radarr and still same error in the log.
These error come when updating radarr within the docker from past version to newest.
Neither versions will move files/folders.

What i mean is that radarr does not move/copy files to the movie dir.

Theres nothing showing up in the "Activity" fane even though log says radarr is parsing the files.
Enabling and Running the drone factory on dirs will end up with a message saying 0 movie files found even that there is very valid movie in directoryes.

I really dont know how to preogress from this point.

**Comment by galli-leo** [comment]
Sorry for not getting back to you, must have missed the notification.

Anyways, since this is a support question, closing this for now. You can still comment. Did you ever figure this out? Also please use the Subreddit or Discord for support in the future.
