### ISSUE TITLE
Download completed and renamed by Radarr, however the interface says the item is still missing.

### ISSUE THREAD

**Issue by ChiefZigZag** [Radarr/Radarr#2026]
Using NZBGet and Radarr v0.2.0.846, During the download process.. the download completes, Radarr Renames the file and moves to the appropriate directory, however the movie still remains in the wanted section. I click on the movie and click search and nothing happens. I notice there are error logs.. since Radarr continually keeps trying to download the same releases.

Warn|ImportApprovedMovie|Couldn't import movie /incoming/complete/Movies/The.Lost.City.of.Z.2016.1080p.BluRay.DTS-HDMA.5.1.x264/462x.1.5.AMDH-STD.yaRulB.p0801.6102.Z.fo.ytiC.tsoL.ehT.mkv
[v0.2.0.846] System.IO.IOException: Destination already exists [/media/Movies/The Lost City of Z (2016)/The Lost City of Z (2016) Bluray-1080p.mkv]

**Comment by galli-leo** [comment]
Unfortunately this is a known bug and I have no idea why it occurs. You can either try running the housekeeping task or rename the movie file and rescan disk.
