### ISSUE TITLE
Add AHD_Internal Flag

### ISSUE THREAD

**Issue by jrsdead** [Radarr/Radarr#203]
Would it be possible to add an AHD indexer? There is a search api available at 
`https://awesome-hd.me/searchapi.php?action=imdbsearch&passkey=%s&imdb=%s&internal=%s`
In this passkey is the users passkey, imdb is the IMDb ID int he form tt1234567 and internal is a boolean that will set the results to only include AHD internals if true or all releases if false or not included.

This will return the following for a search for Bride of Chucky (IMDb ID tt0144120)

```
<?xml version="1.0"?>
<searchresults>
<authkey>AUTHKEY REMOVED</authkey>
<torrent>
<id>18809</id>
<groupid>9687</groupid>
<time>2014-03-18 22:29:33</time>
<userid>33249</userid>
<size>22661245411</size>
<snatched>35</snatched>
<seeders>1</seeders>
<leechers>0</leechers>
<releasegroup>HiFi</releasegroup>
<resolution>1080p</resolution>
<media>Blu-ray</media>
<format>MKV</format>
<encoding>VC-1 Remux</encoding>
<audioformat>DTS-HD MA</audioformat>
<audiobitrate>Variable</audiobitrate>
<audiochannels>6</audiochannels>
<subtitles>English, French, Spanish</subtitles>
<encodestatus>AHDGolddxva</encodestatus>
<freeleech>0.50</freeleech>
<cover>
http://image.tmdb.org/t/p/w342/mAAWRvrTQJQa5EFevZ67MgCVylI.jpg
</cover>
<smallcover>
http://image.tmdb.org/t/p/w154/mAAWRvrTQJQa5EFevZ67MgCVylI.jpg
</smallcover>
<year>1998</year>
<name>Bride of Chucky</name>
<imdb>tt0144120</imdb>
<type>Movie</type>
<plotoutline>
Chucky, the doll possessed by a serial killer, discovers the perfect mate to kill and revive into the body of another doll.
</plotoutline>
</torrent>
<torrent>
<id>17500</id>
<groupid>9687</groupid>
<time>2014-02-02 06:07:05</time>
<userid>37948</userid>
<size>22661245137</size>
<snatched>6</snatched>
<seeders>0</seeders>
<leechers>0</leechers>
<releasegroup>User-Upload</releasegroup>
<resolution>1080p</resolution>
<media>Blu-ray</media>
<format>MKV</format>
<encoding>VC-1 Remux</encoding>
<audioformat>DTS-HD MA</audioformat>
<audiobitrate>Variable</audiobitrate>
<audiochannels>6</audiochannels>
<subtitles>English, Spanish, French</subtitles>
<encodestatus>AHDGolddxva</encodestatus>
<freeleech>0.50</freeleech>
<cover>
http://image.tmdb.org/t/p/w342/mAAWRvrTQJQa5EFevZ67MgCVylI.jpg
</cover>
<smallcover>
http://image.tmdb.org/t/p/w154/mAAWRvrTQJQa5EFevZ67MgCVylI.jpg
</smallcover>
<year>1998</year>
<name>Bride of Chucky</name>
<imdb>tt0144120</imdb>
<type>Movie</type>
<plotoutline>
Chucky, the doll possessed by a serial killer, discovers the perfect mate to kill and revive into the body of another doll.
</plotoutline>
</torrent>
</searchresults>
```

The download link for the above then would be 
`https://awesome-hd.me/torrents.php?action=download&id=%s&authkey=%s&torrent_pass=%s'`
the authkey and id are returned in the search results above and the torrent_pass is the passkey as used earlier.

**Comment by galli-leo** [comment]
Without an account so one of us can properly test it, it's going to be very difficult.

**Comment by onedr0p** [comment]
Thanks for all the information when I find time I'll add this.

**Comment by xelra** [comment]
@onedr0p Can you add a switch to only get internals?

**Comment by galli-leo** [comment]
@xelra That would have to be handled at a deeper level than only from the indexer. It should also be added for other indexers. Can you open a feature request on feathub?

**Comment by jrsdead** [comment]
@galli-leo @onedr0p its just a matter of adding internal=1 to the api call.  The api will then only return internals.  This is the same idea as the way the ptp indexer handles gp releases

**Comment by onedr0p** [comment]
Do you want the button switch to require only internals or just prefer them?

**Comment by galli-leo** [comment]
@jrsdead Gotcha, in that case much more easier to implement.

**Comment by galli-leo** [comment]
@onedr0p Only internals for now

**Comment by xelra** [comment]
I think it would be great to have the button read something like "Limit RSS to internals".

Then it would RSS autograb internals, but the search would still show everything.

I think that's what most users would want.

**Comment by jrsdead** [comment]
well that switch will only return internals and wont return noninternals

**Comment by onedr0p** [comment]
I think prefer internals is what you guys want.

**Comment by xelra** [comment]
@onedr0p 
What I was suggesting is to use the `internal=1` url for RSS, when the switch is set, but for manual search use the url that returns everything.

**Comment by onedr0p** [comment]
We cannot do that without changing code outside of the indexers. It would have to reside in the download dicision code. I don't see that happening anytime soon.

**Comment by xelra** [comment]
Then I think require will have the same effect. Will it still show non-internals in the manual search though?

**Comment by onedr0p** [comment]
I can add the option to only grab internals, but note it will effect both RSS sync and searching.

**Comment by onedr0p** [comment]
I added a PR for this. There's an option to only include internal releases.

https://github.com/Radarr/Radarr/pull/449/files

**Comment by xelra** [comment]
Thank you.

**Comment by Quiksmage** [comment]
on the lastest develop, I'm getting the following when testing.
I also got a 6 hour ban from PTP for failed logins from radarr as well. Not exactly sure what happened on this release. My Jackett torznabs are working fine.

```
17-4-11 16:28:48.3|Debug|AwesomeHD|Downloading Feed https://awesome-hd.me/searchapi.php?action=latestmovies&passkey=(removed)
17-4-11 16:28:49.6|Warn|AwesomeHD|Unable to connect to indexer

[v0.2.0.596] NzbDrone.Core.Indexers.Exceptions.IndexerException: An error occurred while processing feed, feed invalid
   at NzbDrone.Core.Indexers.AwesomeHD.AwesomeHDRssParser.ParseResponse(IndexerResponse indexerResponse) in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\AwesomeHD\AwesomeHDRssParser.cs:line 89
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 297
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 324

17-4-11 16:28:49.7|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Unable to connect to indexer. An error occurred while processing feed, feed invalid
17-4-11 16:28:49.7|Debug|Api|[POST] /api/indexer/test: 400.BadRequest (1375 ms)
17-4-11 16:28:51.8|Debug|Api|[GET] /api/health: 200.OK (0 ms)
17-4-11 16:28:51.8|Debug|Api|[GET] /api/health: 200.OK (0 ms)
17-4-11 16:28:53.0|Debug|Api|[GET] /api/diskspace: 200.OK (1216 ms)
17-4-11 16:28:53.2|Debug|Api|[GET] /api/diskspace: 200.OK (218 ms)
17-4-11 16:28:54.2|Debug|Api|[GET] /api/log/file: 200.OK (15 ms)
```

**Comment by njunxuan** [comment]
Sorry to revive this issue. It seems that @onedr0p's code was removed in commit '861962d06c0bc10eb3b4f08ef78b0693b9d92cc6'. Is there any intention to reintroduce this feature?

Thank you.

**Comment by xelra** [comment]
I cannot find the commit that you linked. On release version 0.2.0.1067 AHD is still a supported indexer.

**Comment by njunxuan** [comment]
My apologies that I was unclear. I meant that the code for the option to only download internal releases provided by onedr0p seems to have been removed. I am unable to find the option to prefer internal releases on my indexer settings.

**Comment by galli-leo** [comment]
@njunxuan No you only have to put the indexer flag you want, in your case AHD_Internal. Though it seems like, I havent added a flag for that.

**Comment by xelra** [comment]
I think that doesn't have the intended effect anymore. I had a look at the indexer flags and tried to recreate my usecase, but I didn't know how.

I wanted it to only automatically download internals from AHD and not just prefer. I wanted it to wait until there is an internal release.

**Comment by njunxuan** [comment]
@galli-leo I see, I must have missed this out somewhere in the documentation. Thank you so much for your work on this, looking forward to the flag being implemented!

**Comment by galli-leo** [comment]
@xelra When you edit your indexers setting you now have a new field "Required Indexer Flags". There you can add Indexer Flags (such as PTP_Golden or AHD_Internal, which doesn't exist yet), that are required for that indexer (and not just preferred).

**Comment by xelra** [comment]
@galli-leo Thanks, that makes sense. Where are the flags documented? I couldn't find anything in the tooltips. Or is this some secret code? ;)

**Comment by galli-leo** [comment]
@xelra They are defined here in code:
https://github.com/Radarr/Radarr/blob/433ae019ded8ee70819a61d38611f77a2c547fb6/src/NzbDrone.Core/Parser/Model/ReleaseInfo.cs#L97-L106

If you have some spare time, maybe you could add a wiki page :)?

**Comment by jonatronnn** [comment]
Hi galli-leo is this fixed now or is there a way I can add the flags myself in the mean time?

**Comment by galli-leo** [comment]
@jonatronnn No to both.

**Comment by xelra** [comment]
I think these need to somehow be documented directly in the UI. Maybe with a tooltip.

**Comment by jrsdead** [comment]
@galli-leo let me know if you need me to update anything on our end.  We have 25% and 75% freeleech as well as 50% and 100% so those might need to be added to the flags too.

**Comment by galli-leo** [comment]
@jrsdead Could you add an xml element for whether a torrent is an internal release or not? Freeleech stuff, should be fine.

**Comment by jrsdead** [comment]
@galli-leo I added both internal and userrelease.  We don't mark torrents as scene i'm afraid.

**Comment by galli-leo** [comment]
Thank you both, it's integrated now :)
