### ISSUE TITLE
Offering Help:  No drone factory / auto-extracting torrents [win]

### ISSUE THREAD

**Issue by seanvree** [Radarr/Radarr#2031]
Hey guys, 

Previously, with use of the drone factory, there were multiple methods to auto-extract/PP, and import using the drone factory.  Since you guys are also retiring the drone factory, I was wondering if you've thought about how to accomplish this?  To my knowledge, there is NO method to auto-extract and auto-import releases that are .RARed, at least for windows users. This is a HUGE deal for us lowly windows users.  Ref this thread which will prob bring back nightmares for @Taloth 

https://forums.sonarr.tv/t/drone-factory-is-deprecated-unrar/15063?source_topic_id=15260

With sonarr, it's a pretty easy fix using the guide I wrote below.  However, it's dependant on two things. 1) The use of a command "EPPISODESCANN" which can be called from external scripts, AND  2) the use of the below tool, which auto-extracts everything, moves the media around, but uses the EPISODESCAN command to invoke an import. (although this tool does NOT specifically mention Radarr, it will work (as I've tested) IF there's a way to make Radarr scan and import a defined directory from a script such as this.

https://github.com/clinton-hall/nzbToMedia

 So, with help from @Taloth  and some other dudes, I wrote a pretty extensive guide to help users get around the ".rar extraction" issue while NOT using the drone factory.   I've been using it for a couple weeks now, and is a game changer:

https://forums.sonarr.tv/t/unrar-win-new-guide-to-auto-process-rar-torrents-via-sonarr-w-o-drone-factory-edit-01-sep-17/15381

I'm totally willing to edit this and/or create a new one for use with Radarr.  Just wanted your thoughts first.  I know once the drone factory goes away, it's gonna break a lot dudes rigs with respect to automation. 

Final note:

Thanks for all you guys do.  I know there's a lot of entitled people out there, but just wanted to offer some help. 

thanks,

SV

**Comment by hotio** [comment]
There is no unrar issue while not using drone factory. CDH can be used just fine when a script extracts rar archives.

**Comment by galli-leo** [comment]
The 'DownloadedMoviesScan' command should work the same way here on Radarr :) Additionally, as Hotio pointed out, downloaders can extract the rars as well and then you would not need a script (except for in the dl client, if they do not support it natively)

**Comment by galli-leo** [comment]
See https://github.com/Radarr/Radarr/wiki/API:Command#downloadedmoviesscan for more info

**Comment by seanvree** [comment]
@hotio  - CDH  ?  Not sure what that stands for?

**Comment by hotio** [comment]
Completed Download Handling

**Comment by seanvree** [comment]
@hotio , @galli-leo 

Thanks for the info the DownloadMovieScan  that will work. 

Also,  Yes, I'm aware there are many extractor plugings and scripts out there.  However, there are multiple problems with these:

1 - MOST of these plugins only allow you to extract to ONE directly.  So, if you have one directy for "TV", "movies", etc, it won't work. Ref:
https://github.com/cvarta/deluge-extractor/issues/2

2 - MOST of the extractor plugins will not work if you have your torrents downloading to one directory and seeding from another. Ref:
http://forum.deluge-torrent.org/viewtopic.php?f=9&t=54167

3 - MOST of the extract plugins do NOT support labels.  So, they will only extract on ONE label. 

So, that's why the NZBtoMedia is clutch, because it executes AFTER the torrent has been moved by the client and puts the media file in a completely different directory for Sonarr/Radarr to import. 

Again, depending on your environment, you may not have this issue, but if you look at the link below, you'll see MANY people have this issue, and found ways around it, but only using the drone factory. 


https://forums.sonarr.tv/t/drone-factory-is-deprecated-unrar/15063?source_topic_id=15260


I guess since there is a command to use, I'm going to give this a GO to duplicate what I've been using for Sonarr that has been working great.  

Thanks for the input.

**Comment by hotio** [comment]
Most people don't know what they are doing and search for a solution, eventually they find a bad solution and keep on sharing that solution. This is the reason for a lot of people crying when sonarr put the warning up regarding drone factory. There is no reason ever to still use drone factory, everything can be done with CDH. This however does not mean you can't use drone while it lasts, but there's no point in helping people keep using it.

**Comment by seanvree** [comment]
Completely agree @hotio that was the point of this .  But because of the issues I pointed out above, some people (like myself) were forced to use it.  I spent a lot of time writing the guide so that people didn't have to use it.  With "DownloadedMoviesScan" hopefully, we don't have to anymore. 

Thanks,

**Comment by hotio** [comment]
DownloadedMoviesScan is kinda the same as Drone Factory, it's just called from a script instead of a timer. IIRC

**Comment by seanvree** [comment]
@hotio welp, unless you have a better idea. I guess we'll go with that then.

**Comment by hotio** [comment]
Deluge for instance can extract perfectly fine to different folders based on labels, with a few lines of code. However for CDH this is not even required, all tv/movie files can be thrown into one folder just fine.

**Comment by seanvree** [comment]
@hotio  well, then, enlighten me (us) with this code you speak of.

**Comment by hotio** [comment]
Did you not read the Wiki?

https://github.com/Radarr/Radarr/wiki/Common-Problems#unpack-torrents

Shall I hunt down the part of python code to get the label from Deluge?

**Comment by seanvree** [comment]
"NOTE: This guide applies only to Linux systems." ?

**Comment by hotio** [comment]
Yes, therefor my remark about porting a few lines to powershell and the irrelevance of how it gets extracted to CDH.

**Comment by seanvree** [comment]
not trying to get into an argument here, but the information is obviously not readily avalible.

**Comment by hotio** [comment]
Not trying to argue either....but

>If you have a better suggestion, please comment below, however, ensure that your suggestions address all the objectives listed above. If you say, “but bro, just download a Linux docker and you’ll be golden bro.” I’m going to find you and poop in your beer.

Yes, instead of calling an outdated API command use CDH. :-) I feel comfortable that you will not poop in my beer.

**Comment by seanvree** [comment]
I guess that answers my question then.

**Comment by hotio** [comment]
Just to be clear, there's nothing wrong with your guide and used scripts, but you can skip the API call and setup CDH with Remote Path Mappings to lett radarr look wherever you want, while using a feature that will be supported and maintaned for years to come.

When using CDH and letting radarr send to Deluge, you also get activity monitoring in Radarr and failed download handling, although that is only for NZB, torrent should not fail.

**Comment by seanvree** [comment]
a lot of caveats you forgot there brother.

**Comment by hotio** [comment]
Please do tell

**Comment by seanvree** [comment]
we're good. 

Appricate your time.

**Comment by hotio** [comment]
Yes, but I have a feeling, it's wasted time on my end. You seem not very interested in learning better ways of doing things...but that is your right.

**Comment by seanvree** [comment]
@hotio , galli-leo 

Huge update.  A proper plug-in has been developed by @levic92

https://github.com/levic92/LCExtractor


Tested and works amazingly.  

Cheers.

**Comment by jiBYo** [comment]
@levic92 

I have installed your script but it is not extracting the files, can you please give me details on what settings I should be using?

**Comment by levic92** [comment]
@jiBYo I have had no reports of it not working. Deluge seems to have a lot of bugs in the GUI. Check your config files and make sure the LCExtractor plugin is actually enabled. All the information on setup and configuration are detailed in the README

**Comment by elpamyelhsa** [comment]
Wow, this does sound like an improvement.

So DF is a simple one line config that works perfectly. And we should all move to CDH, as long as you love to fight with technicalities to setup some complicated, script editing, plugin using, convoluted, non-obvious label path-y thing. But now you cannot support manual drop in files without manual triggering, or extracted downloads without lables.

Unless I'm missing something, someone quoted about a better way to get from A > B but suggests a setup that needs a white paper written on it. Can someone explain how this is a better way or has someone lost sight of the simple advantages?

Radarr DF has more uses than just what is common. It can be used for sorting and renaming not just Radarr triggered downloads but all files as a very handy tool.
