### ISSUE TITLE
Radarr service won't launch after user is changed

### ISSUE THREAD

**Issue by Sevenon7** [Radarr/Radarr#2033]
**Description:**
In Linux after updating /var/packages/radarr/scripts/start-stop-status to change the Radarr service USER, the service no longer launches successfully. There are no errors in the log file /var/packages/radarr/target/var/.config/Radarr/logs/radarr.txt.

Exact details of the change are as follows:
```
#!/bin/sh

# Package
PACKAGE="radarr"
DNAME="Radarr"

# Others
INSTALL_DIR="/usr/local/${PACKAGE}"
PATH="${INSTALL_DIR}/bin:${PATH}"
# USER="${PACKAGE}"
USER="apps"
PID_FILE="${INSTALL_DIR}/var/.config/Radarr/nzbdrone.pid"
```

Attempting to launch manually:
`
admin@Blue:/var/packages/radarr/scripts$ ./start-stop-status start

Starting Radarr ...
admin@Blue:/var/packages/radarr/scripts$ `

**Radarr Version:**
Version: 0.2.0.846
Mono Version: 4.6.2 (Stable 4.6.2.7/08fd525 Wed Dec 7 19:48:05 CET 2016)

**Comment by galli-leo** [comment]
Can you try looking for logs in ~/.config/Radarr or other folders listed in http://radarr.video/config

**Comment by Sevenon7** [comment]
Hi Leonardo,

I did, unfortunately there isn’t any generated for launch errors. Any other
thoughts?

Best.


From: Leonardo Galli <notifications@github.com> <notifications@github.com>
Reply: Radarr/Radarr
<reply@reply.github.com>
<reply@reply.github.com>
Date: September 10, 2017 at 2:35:39 AM
To: Radarr/Radarr <radarr@noreply.github.com> <radarr@noreply.github.com>
Cc: Genesis <sevenon7@gmail.com> <sevenon7@gmail.com>, Author
<author@noreply.github.com> <author@noreply.github.com>
Subject:  Re: [Radarr/Radarr] Radarr service won't launch after user is
changed (#2033)

Can you try looking for logs in ~/.config/Radarr or other folders listed in
http://radarr.video/config

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Radarr/Radarr/issues/2033#issuecomment-328331128>, or mute
the thread

**Comment by galli-leo** [comment]
Sorry for not getting back to you sooner, but honestly not much I can do here. I would check permissions on all Radarr exe files, it may be related to that.
