### ISSUE TITLE
Superman II download not appearing in activity (probably II vs 2 issue)

### ISSUE THREAD

**Issue by vdefender** [Radarr/Radarr#2034]
**Description:**

I added Superman II to Radarr. A suitable torrent was found and was sent to deluge successfully. However after it's sent to Deluge, Radarr looses track of it and it doesn't show up in the Activity queue. When the download completes, Radarr does not find it or rename it or copy it. 

I think it has to do with the 'II' vs '2' in the name? I've reproduced this several times.

**Radarr Version:**

0.2.0.846

**Logs:**
17-9-2 10:11:00.5|Info|NzbSearchService|Searching 1 indexers for [Superman II]
17-9-2 10:11:04.0|Info|DownloadDecisionMaker|Processing 7 releases
17-9-2 10:11:25.9|Info|PreDBService|Starting PreDB Sync
17-9-2 10:11:57.3|Info|NetImportSearchService|No lists are enabled for auto-import.
17-9-2 10:13:01.2|Info|RssSyncService|Starting RSS Sync
17-9-2 10:13:04.9|Info|DownloadDecisionMaker|Processing 100 releases
17-9-2 10:13:07.1|Info|RssSyncService|RSS Sync Completed. Reports found: 100, Reports grabbed: 0
17-9-2 10:22:11.4|Info|RefreshMovieService|Updating Info for Superman II
17-9-2 10:22:13.4|Info|DiskScanService|Scanning disk for Superman II
17-9-2 10:22:28.5|Info|NzbSearchService|Searching 1 indexers for [Superman II]
17-9-2 10:22:28.9|Info|DownloadDecisionMaker|Processing 7 releases
17-9-2 10:38:23.6|Info|NzbSearchService|Searching 1 indexers for [Superman II]
17-9-2 10:38:27.1|Info|DownloadDecisionMaker|Processing 7 releases
17-9-2 10:38:27.2|Info|MovieSearchService|Movie search completed. 0 reports downloaded.
17-9-2 10:45:13.5|Info|NzbSearchService|Searching 1 indexers for [Superman II]
17-9-2 10:45:13.9|Info|DownloadDecisionMaker|Processing 7 releases
17-9-2 10:45:14.1|Info|MovieSearchService|Movie search completed. 0 reports downloaded.
17-9-2 10:45:24.7|Info|NzbSearchService|Searching 1 indexers for [Superman II]
17-9-2 10:45:25.6|Info|DownloadDecisionMaker|Processing 7 releases
17-9-2 10:45:34.1|Info|NzbSearchService|Searching 1 indexers for [Superman II]
17-9-2 10:45:34.5|Info|DownloadDecisionMaker|Processing 7 releases
17-9-2 10:45:34.6|Info|MovieSearchService|Movie search completed. 0 reports downloaded.
17-9-2 11:05:48.5|Info|RefreshMovieService|Updating Info for Superman II
17-9-2 11:05:49.8|Info|DiskScanService|Scanning disk for Superman II
17-9-2 11:07:13.8|Info|NzbSearchService|Searching 1 indexers for [Superman II]
17-9-2 11:07:17.2|Info|DownloadDecisionMaker|Processing 7 releases
17-9-2 11:07:17.7|Info|DownloadService|Report sent to Deluge. Superman.2.1980.1080p.BluRay.x264.DTS-FGT
17-9-2 11:07:17.8|Info|MovieSearchService|Movie search completed. 1 reports downloaded.
17-9-2 11:11:46.3|Info|PreDBService|Starting PreDB Sync
17-9-2 11:12:17.0|Info|NetImportSearchService|No lists are enabled for auto-import.
17-9-2 11:13:17.4|Info|RssSyncService|Starting RSS Sync
17-9-2 11:13:17.9|Info|DownloadDecisionMaker|Processing 100 releases
17-9-2 11:13:20.0|Info|RssSyncService|RSS Sync Completed. Reports found: 100, Reports grabbed: 0

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by galli-leo** [comment]
Whats the exact title appearing in deluge? We should be replacing 2 with II and vice versa for matching.
