### ISSUE TITLE
Allow read-only paths?

### ISSUE THREAD

**Issue by djl** [Radarr/Radarr#2035]
**Description:**

As of 67ff871cf655c9a4bc10452b8195f95b2c840438, Radarr requires that new paths be writable by the user running Radarr. This may not always be desirable.

In my case I use Radarr only for fetching movies while NZBGet and some custom scripts handle post-processing. Since Radarr doesn't need write access to my movies directory just to fetch new movies I want to mount it read-only.

Can we add an option to skip this verification for those of us who don't need it?

**Radarr Version:**

0.2.0.778

**Logs:**

N/A

**Comment by hotio** [comment]
Flexget

**Comment by galli-leo** [comment]
Yeah, while you are free to open a feature request on feathub, I am kot going to implement this unless a few people want / need it

**Comment by jj-uk** [comment]
I want / need this. I have a large amount of media that I ripped from DVD / blueRay discs. I want to add them Read-only to Radarr so i dont end up with duplicate movies.

**Comment by djl** [comment]
> Radarr doesn't and shouldn't need write access to my dvd rips.

That's another reason I'd like this.

With read-only folders it's _impossible_ for Radarr to lose data - something I'm paranoid about since another, similar application decided to delete some of my data without warning (I'm sure you can guess which one :wink:).

Not that I _expect_ Radarr to eat my data but bugs happen. And user error happens more.

**Comment by galli-leo** [comment]
If you’re paranoid you can always just use the recycle bin provider.

**Comment by jj-uk** [comment]
I'd rather the folders were readonly.

**Comment by WestSmith** [comment]
Also could benefit from this feature. Especially for those using Plexdrive. Recently switched back from Sonarr to Sickrage because Sickrage could monitor read-only folders but Sonarr cannnot.

**Comment by eiddor** [comment]
I'm in the same boat as WestSmith, though I haven't switched from Radarr/Sonarr because of this.  I move downloads to a permanent storage to save space on my active drives, and I have to go in and Unmonitor each movie/TV show so they don't keep downloading.
