### ISSUE TITLE
How to configure deletion of downloaded movies in Transmission?

### ISSUE THREAD

**Issue by msdos** [Radarr/Radarr#2036]
The movies are being downloaded to `/var/media/my-drive/transmission/downloads` and after the download is complete they are correctly copied to `/var/media/my-drive/` but aren't deleted from `/var/media/my-drive/transmission/downloads`. Is this a misconfiguration from my part or a bug?

**Radarr Version:**

Version
0.2.0.778
Mono Version
5.0.1.1 (2017-02/5077205 Wed May 31 10:51:59 BST 2017)

**Comment by hotio** [comment]
Are they still seeding?

**Comment by msdos** [comment]
Not all of them. Are they supossed to be deleted after they stop seeding? I have movies that stopped seeding after a 1:1 ratio, but are still in my `downloads` folder...

**Comment by hotio** [comment]
It only gets deleted when its done seeding, have no idea if it works with transmission however...

**Comment by galli-leo** [comment]
Yeah you have to enable an option in your dl client for them to be deleted.

**Comment by msdos** [comment]
There's an option in "Download Client" in "Completed Download Handling" called "Remove" with the following docs:

`Remove imported downloads from download client history`

When I set it to yes, it actually does what I need: after seeding the ratio I defined in Transmission, it removes from Transmission list and from Transmission's download folder.

These posts  (and @hotio's hint) helped me trying this setting:

https://forums.sonarr.tv/t/sonarr-does-not-remove-torrent-from-transmission-list-after-it-finishes-the-import/4746

https://forums.sonarr.tv/t/changed-downloader-to-transmission-and-now-sonarr-will-not-delete-finished-downloads-after-rename/9696/3

https://forums.sonarr.tv/t/transmission-not-deleting-torrents/7644/2

I really think the message `Remove imported downloads from download client history` can be improved to something like `Remove completed downloaded movies from download client download list and disk after defined seeding ratio` or something like that.

**Comment by rcdailey** [comment]
Problem with the "Remove" option is that it also affects NZB handling as well. In nzbget's case, it removes it from the history tab which I *do not* want. There should be a variation of this option specific to torrent protocol only.
