### ISSUE TITLE
Built-In Updater does not work correct

### ISSUE THREAD

**Issue by silv3r23** [Radarr/Radarr#2037]
System: Debian
Updating from v0.2.0.778 to v0.2.0.846 with the Built-In option in WebUI does not work. The updater starts the backup and the download of the new version. Then all files where extracting by updater to /tmp/radarr_update/Radarr but Radarr is located in /opt/Radarr. Tried multiple times without success and then I have done a **manual** update with success (extracted the new .tar.gz to /opt/Radarr)

![image](https://user-images.githubusercontent.com/28316411/30049488-39aa53e6-921b-11e7-9e86-ba2c4193bdaa.png)
![image](https://user-images.githubusercontent.com/28316411/30049509-52959532-921b-11e7-89ac-2c57a630d11e.png)

**Comment by galli-leo** [comment]
Seems like Radarr doesn't have permissions to the /opt/Radarr folder? Can you post the updater logs?

**Comment by silv3r23** [comment]
`17-9-4 20:23:53.6|Info|UpdateApp|Starting Radarr Update Client
17-9-4 20:23:54.8|Debug|UpdateApp|NzbDrone process ID: 30093
17-9-4 20:23:54.8|Debug|UpdateApp|Arguments:
17-9-4 20:23:54.8|Debug|UpdateApp|  30093
17-9-4 20:23:54.8|Debug|UpdateApp|  /tmp/radarr_update
17-9-4 20:23:54.8|Debug|UpdateApp|  /opt/Radarr/Radarr.exe
17-9-4 20:23:54.8|Debug|UpdateApp|  /nobrowser
17-9-4 20:23:54.8|Debug|UpdateApp|Using executing application: /opt/Radarr/Radarr.exe
17-9-4 20:23:54.8|Debug|UpdateApp|Executable location: /opt/Radarr/Radarr.exe
17-9-4 20:23:54.8|Info|InstallUpdateService|Installation Folder: /opt/Radarr
17-9-4 20:23:54.8|Info|InstallUpdateService|Updating Radarr from version 0.2.0.778 to version 0.2.0.846
17-9-4 20:23:54.8|Info|InstallUpdateService|Verifying requirements before update...
17-9-4 20:23:54.9|Debug|ProcessProvider|Finding process with Id:30093
17-9-4 20:23:54.9|Warn|ProcessProvider|Unable to find process with ID 30093
17-9-4 20:23:54.9|Fatal|UpdateApp|An error has occurred while applying update package.

[v0.2.0.846] System.ArgumentException: Process with ID doesn't exist 30093
  at NzbDrone.Update.UpdateEngine.InstallUpdateService.Verify (System.String targetFolder, Int32 processId) [0x000c3] in C:\projects\radarr-usby1\src\NzbDrone.Update\UpdateEngine\InstallUpdateService.cs:78 
  at NzbDrone.Update.UpdateEngine.InstallUpdateService.Start (System.String installationFolder, Int32 processId) [0x00032] in C:\projects\radarr-usby1\src\NzbDrone.Update\UpdateEngine\InstallUpdateService.cs:85 
  at NzbDrone.Update.UpdateApp.Start (System.String[] args) [0x00010] in C:\projects\radarr-usby1\src\NzbDrone.Update\UpdateApp.cs:58 
  at NzbDrone.Update.UpdateApp.Main (System.String[] args) [0x00031] in C:\projects\radarr-usby1\src\NzbDrone.Update\UpdateApp.cs:43 
`

**Comment by galli-leo** [comment]
Seems like the radarr process vanishes before the updater can start.

**Comment by gpvelzen** [comment]
I have it also (running radarr on a qnap) no update problems before or with sonarr

**Comment by gilly65** [comment]
I also have it on a Qnap NAS, it will not update for me.

here is the entries in the log when I try.
> 
  | CommandExecutor | Error  occurred while executing task ApplicationUpdate:  ApplicationName='mono', CommandLine='--debug  /tmp/radarr_update/Radarr.Update.exe 13703 /tmp/radarr_update  /share/CACHEDEV1_DATA/.qpkg/Radarr/Radarr/Radarr.exe ',  CurrentDirectory='', Native error= Cannot find the specified file | 6:48am
-- | -- | -- | --
  | InstallUpdateService | Updater Arguments: 13703 /tmp/radarr_update /share/CACHEDEV1_DATA/.qpkg/Radarr/Radarr/Radarr.exe | 6:48am
  | InstallUpdateService | Radarr will restart shortly. | 6:48am
  | InstallUpdateService | Starting update client /tmp/radarr_update/Radarr.Update.exe | 6:48am
  | InstallUpdateService | Preparing client | 6:48am
  | BackupService | Starting Backup | 6:48am
  | InstallUpdateService | Update package extracted successfully | 6:48am
  | InstallUpdateService | Extracting Update package | 6:48am
  | InstallUpdateService | Update package verified successfully | 6:48am
  | InstallUpdateService | Verifying update package | 6:48am
  | InstallUpdateService | Downloading update 0.2.0.852 | 6:48am
  | InstallUpdateService | Deleting old update files | 6:48am
>

**Comment by mccaya** [comment]
Same issue.

**Comment by mccaya** [comment]
If i want to update manually what files should i take from repository.

**Comment by galli-leo** [comment]
@gilly65 Seems like either Radarr has no access to the files or mono isn't in your path.
@mccaya You can find the downloads on the Releases page.
@silv3r23 Did you ever get this working? Seems like something kills Radarr after it started the updater and the updater fails because it can't kill the old process.

**Comment by silv3r23** [comment]
@galli-leo 
I reinstalled the entire server and switched from Debian 8 to Debian 9. I did a clean install of v0.2.0.870 and updated successful to v0.2.0.910 with the internal updater. (I guess I had an error with the mono version before)
Today I updated to v0.2.0.935, the update did work fine, but now I am getting loop at the updatepage:

![image](https://user-images.githubusercontent.com/28316411/35939262-e859a91e-0c4b-11e8-9cd4-861a37bc04d9.png)

![image](https://user-images.githubusercontent.com/28316411/35939292-028de48a-0c4c-11e8-91b2-fc87aa97fd64.png)

Request Failed: Sequence contains more than one matching element

```
System.InvalidOperationException: Sequence contains more than one matching element
  at System.Linq.Enumerable.SingleOrDefault[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x0009d] in <63992662b765477a898ef49cdcc99ee2>:0 
  at NzbDrone.Api.Update.UpdateModule.GetRecentUpdates () [0x00064] in <92e44cf0cba247ec9190b9feca8cc39b>:0 
  at NzbDrone.Api.REST.RestModule`1[TResource].<set_GetResourceAll>b__32_0 (System.Object options) [0x00006] in <92e44cf0cba247ec9190b9feca8cc39b>:0 
  at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)
  at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, System.Threading.CancellationToken context) [0x00049] in <63c44d6f8d7e4f339a987bf9eb94d931>:0 
```

Version: 0.2.0.935
Mono Version: 4.6.2 (Debian 4.6.2.7+dfsg-1)

**Comment by galli-leo** [comment]
@silv3r23 Yeah that's fixed now. Was a problem with the update server.
