### ISSUE TITLE
CentOS7 systemd service won't start

### ISSUE THREAD

**Issue by Sup3rLativ3** [Radarr/Radarr#204]
Hi,

I've installed the latest version yesterday and confirmed that it works by running it from bash. when I try to get it to run as a service though it fails and I'm unable to determine why.

I've used the same service file as my sonarr install and I'm currently using the one provided by the radarr wiki but same issue.

systemctl status output
```
â— radarr.service - Radarr Daemon
   Loaded: loaded (/etc/systemd/system/radarr.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2017-01-13 08:48:47 AEDT; 3min 16s ago
  Process: 3238 ExecStart=/usr/bin/mono /usenet/radarr/Radarr.exe -nobrowser (code=exited, status=1/FAILURE)
 Main PID: 3238 (code=exited, status=1/FAILURE)

Jan 13 08:48:46 Dingo systemd[1]: Started Radarr Daemon.
Jan 13 08:48:46 Dingo systemd[1]: Starting Radarr Daemon...
Jan 13 08:48:47 Dingo mono[3238]: Press enter to exit...
Jan 13 08:48:47 Dingo systemd[1]: radarr.service: main process exited, code=exited, status=1/FAILURE
Jan 13 08:48:47 Dingo systemd[1]: Unit radarr.service entered failed state.
Jan 13 08:48:47 Dingo systemd[1]: radarr.service failed.
```

journal -xe output
```
Jan 13 08:58:41 Dingo systemd[1]: Started Radarr Daemon.
-- Subject: Unit radarr.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit radarr.service has finished starting up.
--
-- The start-up result is done.
Jan 13 08:58:41 Dingo systemd[1]: Starting Radarr Daemon...
-- Subject: Unit radarr.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit radarr.service has begun starting up.
Jan 13 08:58:41 Dingo polkitd[661]: Unregistered Authentication Agent for unix-process:3585:153815 (system bus name :
Jan 13 08:58:42 Dingo mono[3591]: Press enter to exit...
Jan 13 08:58:42 Dingo systemd[1]: radarr.service: main process exited, code=exited, status=1/FAILURE
Jan 13 08:58:42 Dingo systemd[1]: Unit radarr.service entered failed state.
Jan 13 08:58:42 Dingo systemd[1]: radarr.service failed.
```

Current service file
```
[root@dingo radarr]# systemctl cat radarr
# /etc/systemd/system/radarr.service
[Unit]
Description=Radarr Daemon
After=syslog.target network.target

[Service]
User=_usenet
Group=_usenet_group

Type=simple
ExecStart=/usr/bin/mono /usenet/radarr/Radarr.exe -nobrowser
TimeoutStopSec=20


[Install]
WantedBy=multi-user.target
```

If there is any more info you need please don't hesitate to let me know

**Comment by onedr0p** [comment]
Mine is below, I believe you might need the `-data=/var/lib/radarr` flag.

```
[Unit]
Description=Radarr Service
After=syslog.target network.target

[Service]
User=radarr
Group=radarr
ExecStart=/usr/bin/radarr -nobrowser -data=/var/lib/radarr
Type=simple
TimeoutStopSec=20
KillMode=process
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

**Comment by Sup3rLativ3** [comment]
I notice you're not running mono in your exec start? 

My sonarr has a custom datadir but my understanding was that it's not required. I added the data dir back in and no change. I considered changing my execstart to the way you have it but I feel like you've modified it as you're not even pointing to the exe. Is this a full working service file? If so how does it know how to start with mono and where/which exe to run?

```
[root@Dingo radarr]# systemctl status radarr
â— radarr.service - Radarr Daemon
   Loaded: loaded (/etc/systemd/system/radarr.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2017-01-13 09:21:24 AEDT; 10s ago
  Process: 4371 ExecStart=/usr/bin/mono /usenet/radarr/Radarr.exe -nobrowser -data=/usenet/radarr_data (code=exited,
status=1/FAILURE)
 Main PID: 4371 (code=exited, status=1/FAILURE)

Jan 13 09:21:22 Dingo systemd[1]: Started Radarr Daemon.
Jan 13 09:21:22 Dingo systemd[1]: Starting Radarr Daemon...
Jan 13 09:21:23 Dingo mono[4371]: Press enter to exit...
Jan 13 09:21:24 Dingo systemd[1]: radarr.service: main process exited, code=exited, status=1/FAILURE
Jan 13 09:21:24 Dingo systemd[1]: Unit radarr.service entered failed state.
Jan 13 09:21:24 Dingo systemd[1]: radarr.service failed.
```

thanks

**Comment by onedr0p** [comment]
My service file is from Arch, sorry or the confusion. I'm curious if there is anymore information you could fine as to why it isn't starting. Isn't there a flag for `systemctl status` that can?

**Comment by Sup3rLativ3** [comment]
Not that I'm aware of. I've looked through the commands available and run what I thought would show me info but I find journalctl is the best tool to figure out issues. There are no debug logs for radarr that I can find. I referenced the sonarr wiki and had a look but no *.txt or *.log files in the radarr or radarr data dir.

In reference to your service file, why does it matter that you're on arch if we're both using systemd? How does it know to run mono and which exe?

**Comment by onedr0p** [comment]
My `/usr/bin/radarr` is:

```
#!/bin/sh
exec mono /usr/lib/radarr/Radarr.exe "$@"
```

But I don't think that will fix your problem.  

What does `journalctl -u radarr.service` output for you?

**Comment by Sup3rLativ3** [comment]
`Jan 13 08:48:46 Dingo systemd[1]: Started Radarr Daemon.
Jan 13 08:48:46 Dingo systemd[1]: Starting Radarr Daemon...
Jan 13 08:48:47 Dingo mono[3238]: Press enter to exit...
Jan 13 08:48:47 Dingo systemd[1]: radarr.service: main process exited, code=exited, status=1/FAILURE
Jan 13 08:48:47 Dingo systemd[1]: Unit radarr.service entered failed state.
Jan 13 08:48:47 Dingo systemd[1]: radarr.service failed.
Jan 13 08:58:41 Dingo systemd[1]: Started Radarr Daemon.
Jan 13 08:58:41 Dingo systemd[1]: Starting Radarr Daemon...
Jan 13 08:58:42 Dingo mono[3591]: Press enter to exit...
Jan 13 08:58:42 Dingo systemd[1]: radarr.service: main process exited, code=exited, status=1/FAILURE
Jan 13 08:58:42 Dingo systemd[1]: Unit radarr.service entered failed state.
Jan 13 08:58:42 Dingo systemd[1]: radarr.service failed.
Jan 13 09:21:22 Dingo systemd[1]: Started Radarr Daemon.
Jan 13 09:21:22 Dingo systemd[1]: Starting Radarr Daemon...
Jan 13 09:21:23 Dingo mono[4371]: Press enter to exit...
Jan 13 09:21:24 Dingo systemd[1]: radarr.service: main process exited, code=exited, status=1/FAILURE
Jan 13 09:21:24 Dingo systemd[1]: Unit radarr.service entered failed state.
Jan 13 09:21:24 Dingo systemd[1]: radarr.service failed.
Jan 13 09:27:15 Dingo systemd[1]: Started Radarr Daemon.
Jan 13 09:27:15 Dingo systemd[1]: Starting Radarr Daemon...
Jan 13 09:27:16 Dingo mono[4598]: Press enter to exit...
Jan 13 09:27:16 Dingo systemd[1]: radarr.service: main process exited, code=exited, status=1/FAILURE
Jan 13 09:27:16 Dingo systemd[1]: Unit radarr.service entered failed state.
Jan 13 09:27:16 Dingo systemd[1]: radarr.service failed.`

**Comment by fryfrog** [comment]
When you say you've run it from bash... I assume you've su - <user that runs radarr> to do it? If you've run it as root or yourself, you may have created some files that can't be read as <user that runs radarr>.

**Comment by onedr0p** [comment]
Could also be a mono thing what version are you running?

**Comment by Sup3rLativ3** [comment]
@fryfrog I thought I had run this but I guess not. When I first ran it, it complained about not having a home dir but that could have been because I didn't set the data dir. Once I created the home dir it runs fine under that user.

```
[root@Dingo sup3rlativ3]# su _usenet
bash-4.2$ whoami
_usenet
bash-4.2$ mono /usenet/radarr/Radarr.exe -nobrowser
[Info] Bootstrap: Starting Sonarr - /usenet/radarr/Radarr.exe - Version 0.2.0.85
[Info] MigrationLogger: *** Migrating data source=/home/_usenet/.config/Radarr/nzbdrone.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
[Info] MigrationLogger: *** Migrating data source=/home/_usenet/.config/Radarr/logs.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
[Info] Router: Application mode: Interactive
[Info] OwinHostController: Listening on the following URLs:
[Info] OwinHostController:   http://*:7878/
[Info] NancyBootstrapper: Starting NzbDrone API
```

@onedr0p My mono version is 4.6.2. Sonarr works with this version so unless there is some difference I'm not aware of it should be fine.

```
Mono JIT compiler version 4.6.2 (Stable 4.6.2.16/ac9e222 Tue Jan  3 11:51:14 UTC 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen
```

I really appreciate the help guys. This one has me stumped.

**Comment by Sup3rLativ3** [comment]
So I decided to check the permissions on all the folders again and found the data dir did not have the correct permissions. Once I used setfacl to set the correct permissions the service started.

Thanks you all for the help.
