### ISSUE TITLE
Alternative Titles is displaying multiple alt-titles for some titles

### ISSUE THREAD

**Issue by djzeratul** [Radarr/Radarr#2040]
**Description:**

For example, Wonder Woman has 4 mappings for Torrent9-tv-Wonder-Woman

They all point to the same mappings URL: https://mappings.radarr.video/mapping/433

**Radarr Version:**

Radarr Ver. 0.2.0.846
nightly

**Logs:**
See attached screenshots
![screen shot 2017-09-05 at 12 27 32 pm](https://user-images.githubusercontent.com/1778738/30079811-56088074-9236-11e7-8ba9-7a490f764b9e.png)
![screen shot 2017-09-05 at 12 33 52 pm](https://user-images.githubusercontent.com/1778738/30079857-7ffe5dcc-9236-11e7-8e7a-7a764923948f.png)

**Comment by magiin** [comment]
Additional movies w said issue:

![termin1](https://user-images.githubusercontent.com/25332158/30080884-35549c9c-9253-11e7-8393-0c0c74275587.jpg)
![termin2](https://user-images.githubusercontent.com/25332158/30080887-385e54fa-9253-11e7-9174-ee02c9598f15.jpg)

**Comment by djzeratul** [comment]
![the_hitman_s_bodyguard_-_radarr-1](https://user-images.githubusercontent.com/1778738/30244596-2e4f6334-9576-11e7-9251-81adb32b8e8c.png)

**Comment by magiin** [comment]
Atomic Blonde is another one by the way.  I dont have the movie in radarr, just recently removed it, but noticed a ton of repeated titles.

**Comment by djzeratul** [comment]
![screencapture-192-168-0-29-7878-radarr-movies-atomic-blonde-341013-1505005098360](https://user-images.githubusercontent.com/1778738/30245274-9edeb868-9588-11e7-823d-a1da0e5bfe6c.png)

**Comment by galli-leo** [comment]
Have you guys been using the nightly builds? Cannot seem to replicate this with the latest build and the movies in question (Though I have seen it on my own install as well).

**Comment by magiin** [comment]
I'm on dev, not nightly.

**Comment by galli-leo** [comment]
Hmmm. What happens when you remove & re-add those movies?

**Comment by djzeratul** [comment]
Just to chime in, I'm on nightly. I removed and re-added Atomic Blonde and the issue resolved.
![atomic_blonde_-_radarr](https://user-images.githubusercontent.com/1778738/30250946-d15ad726-960b-11e7-84a6-bde13cf02817.png)

However for existing movies with downloaded files, I would need to reimport if I found they had these issues correct?

**Comment by djzeratul** [comment]
Next day, and one additional heh:

![screen shot 2017-09-11 at 6 33 03 pm](https://user-images.githubusercontent.com/1778738/30303931-b19fbd06-971f-11e7-83b7-b39964d1db1c.png)

**Comment by djzeratul** [comment]
As suspected... kicked off a manual "Refresh Movie" task (the 24 hour one):
![system_-_radarr](https://user-images.githubusercontent.com/1778738/30304191-1e376e9a-9721-11e7-982b-3ad80b15f9a6.png)

Waited for movie to refresh:
![screen shot 2017-09-11 at 6 40 29 pm](https://user-images.githubusercontent.com/1778738/30304130-c9903ebc-9720-11e7-9664-0d8358af2511.png)

and got a third:
![screen shot 2017-09-11 at 6 44 34 pm](https://user-images.githubusercontent.com/1778738/30304220-47c13282-9721-11e7-9b7c-86e741a570b4.png)

**Comment by galli-leo** [comment]
Interesting. So it only happens on the 24h task? At least I should be able to repro that now.

**Comment by djzeratul** [comment]
@galli-leo appears to be the case, have a 4th after today's scan:

![screen shot 2017-09-12 at 2 47 46 pm](https://user-images.githubusercontent.com/1778738/30349884-65173978-97c9-11e7-9151-c7b3d92e5829.png)

**Comment by magiin** [comment]
Not that this thread needs added examples, but just in case it does, this one is also completely out of hand in terms of AKA's  
![firefox_2017-09-18_19-55-10](https://user-images.githubusercontent.com/25332158/30570956-82e9ea70-9cb2-11e7-8d87-60d315e297da.png)

**Comment by danjames92** [comment]
Also affects release matching UI (might want to add some sort of scrolling box at a max size?)

![firefox_2017-09-18_19-57-53](https://user-images.githubusercontent.com/16107603/30578932-3a5b2d80-9d0e-11e7-95c8-00f7e11b3314.png)

**Comment by galli-leo** [comment]
@magiin That one's actually kinda funny 😬 Should be fixed with the next nightly update.

**Comment by danjames92** [comment]
@galli-leo if you're talking about 0.2.0.858, it's not fixed in that one.

**Comment by galli-leo** [comment]
Na should be fixed in .859

**Comment by djzeratul** [comment]
Nice, I see your commit also has a migration script to clean the dupes too! Thanks!
