### ISSUE TITLE
FIXED --- Impossible to start :/ on OSX...

### ISSUE THREAD

**Issue by Eldoc62** [Radarr/Radarr#2041]
SOLUTION 👍
-------------------
On go , to folder ... Paste : 

~/.config/Radarr

Trash : 

logs.db, logs.db-journal
nzbdrone.db, nzbdrone.db-journal

Great ;)

-----------------

**Description:**

Hi,

I've a problem on radarr... Impossibl to start, there is my logs

I don't understand

**Radarr Version:** 0.2.0.846 

**Logs:**

> Info] Bootstrap: Starting Radarr - /Volumes/Macintosh 2TO/Log's/Apple/Mac/Radarr/Radarr.exe - Version 0.2.0.846 
> [Info] MigrationLogger: *** Migrating data source=/Volumes/HDD_1/.config/Radarr/nzbdrone.db;cache size=-10485760;datetimekind=Utc;journal mode=Truncate;pooling=True;version=3;Full FSync=True *** 
> 
> 
> [Fatal] ConsoleApp: EPIC FAIL! 
> 
> [v0.2.0.846] NzbDrone.Core.Datastore.CorruptDatabaseException: Database file: /Volumes/HDD_1/.config/Radarr/nzbdrone.db is corrupt, restore from backup if available. See: https://github.com/Radarr/Radarr/wiki/FAQ#i-use-radarr-on-a-mac-and-it-suddenly-stopped-working-what-happened ---> System.Data.SQLite.SQLiteException: database disk image is malformed
> database disk image is malformed
>   at System.Data.SQLite.SQLite3.Prepare (System.Data.SQLite.SQLiteConnection cnn, System.String strSql, System.Data.SQLite.SQLiteStatement previous, System.UInt32 timeoutMS, System.String& strRemain) [0x0033c] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
>   at System.Data.SQLite.SQLiteCommand.BuildNextCommand () [0x000f6] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
>   at System.Data.SQLite.SQLiteCommand.GetStatement (System.Int32 index) [0x00008] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
>   at (wrapper remoting-invoke-with-check) System.Data.SQLite.SQLiteCommand:GetStatement (int)
>   at System.Data.SQLite.SQLiteDataReader.NextResult () [0x0011e] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
>   at System.Data.SQLite.SQLiteDataReader..ctor (System.Data.SQLite.SQLiteCommand cmd, System.Data.CommandBehavior behave) [0x00090] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
>   at (wrapper remoting-invoke-with-check) System.Data.SQLite.SQLiteDataReader:.ctor (System.Data.SQLite.SQLiteCommand,System.Data.CommandBehavior)
>   at System.Data.SQLite.SQLiteCommand.ExecuteReader (System.Data.CommandBehavior behavior) [0x0000c] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
>   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery (System.Data.CommandBehavior behavior) [0x00006] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
>   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery () [0x00006] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
>   at System.Data.SQLite.SQLiteConnection.Open () [0x00959] in <61a20cde294d4a3eb43b9d9f6284613b>:0 
>   at FluentMigrator.Runner.Processors.GenericProcessorBase.EnsureConnectionIsOpen () [0x00014] in <137fb96feee44f379d6a8fba4e172d1c>:0 
>   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.Exists (System.String template, System.Object[] args) [0x00000] in <137fb96feee44f379d6a8fba4e172d1c>:0 
>   at FluentMigrator.Runner.Processors.SQLite.SQLiteProcessor.TableExists (System.String schemaName, System.String tableName) [0x00000] in <137fb96feee44f379d6a8fba4e172d1c>:0 
>   at FluentMigrator.Runner.VersionLoader.get_AlreadyCreatedVersionTable () [0x0001c] in <137fb96feee44f379d6a8fba4e172d1c>:0 
>   at FluentMigrator.Runner.VersionLoader.LoadVersionInfo () [0x00028] in <137fb96feee44f379d6a8fba4e172d1c>:0 
>   at FluentMigrator.Runner.VersionLoader..ctor (FluentMigrator.Runner.IMigrationRunner runner, FluentMigrator.Infrastructure.IAssemblyCollection assemblies, FluentMigrator.IMigrationConventions conventions) [0x00077] in <137fb96feee44f379d6a8fba4e172d1c>:0 
>   at FluentMigrator.Runner.MigrationRunner..ctor (FluentMigrator.Infrastructure.IAssemblyCollection assemblies, FluentMigrator.Runner.Initialization.IRunnerContext runnerContext, FluentMigrator.IMigrationProcessor processor) [0x00175] in <137fb96feee44f379d6a8fba4e172d1c>:0 
>   at FluentMigrator.Runner.MigrationRunner..ctor (System.Reflection.Assembly assembly, FluentMigrator.Runner.Initialization.IRunnerContext runnerContext, FluentMigrator.IMigrationProcessor processor) [0x00007] in <137fb96feee44f379d6a8fba4e172d1c>:0 
>   at NzbDrone.Core.Datastore.Migration.Framework.MigrationController.Migrate (System.String connectionString, NzbDrone.Core.Datastore.Migration.Framework.MigrationContext migrationContext) [0x000b5] in <79ef4b111ab349828cc9175dd534046a>:0 
>   at NzbDrone.Core.Datastore.DbFactory.Create (NzbDrone.Core.Datastore.Migration.Framework.MigrationContext migrationContext) [0x00048] in <79ef4b111ab349828cc9175dd534046a>:0 
>    --- End of inner exception stack trace ---
>   at NzbDrone.Core.Datastore.DbFactory.Create (NzbDrone.Core.Datastore.Migration.Framework.MigrationContext migrationContext) [0x00120] in <79ef4b111ab349828cc9175dd534046a>:0 
>   at NzbDrone.Core.Datastore.DbFactory.Create (NzbDrone.Core.Datastore.Migration.Framework.MigrationType migrationType) [0x00010] in <79ef4b111ab349828cc9175dd534046a>:0 
>   at NzbDrone.Core.Datastore.DbFactory.RegisterDatabase (NzbDrone.Common.Composition.IContainer container) [0x00006] in <79ef4b111ab349828cc9175dd534046a>:0 
>   at Radarr.Host.Bootstrap.Start (Radarr.Host.ApplicationModes applicationModes, NzbDrone.Common.EnvironmentInfo.StartupContext startupContext) [0x0003d] in <8cf11bf8d2d048caa48fc3d370cccee4>:0 
>   at Radarr.Host.Bootstrap.Start (NzbDrone.Common.EnvironmentInfo.StartupContext startupContext, Radarr.Host.IUserAlert userAlert, System.Action`1[T] startCallback) [0x00075] in <8cf11bf8d2d048caa48fc3d370cccee4>:0 
>   at NzbDrone.Console.ConsoleApp.Main (System.String[] args) [0x00013] in <7703792651f34f7e9625feb02306b903>:0 
> 
> Press enter to exit...
> 
> 
>

**Comment by galli-leo** [comment]
See the link in the error message.

**Comment by Eldoc62** [comment]
Hi,

Sorry but i would test this :

```
Most likely this is due to a MacOS bug which caused one of the Sonarr databases to be corrupted. Follow these steps to resolve:

In the Finder, select the Go menu, and the option Go to Folder...
Enter ~/.config/NzbDrone and click the Go button to open Radarr's data folder
Move the following files to Trash: logs.db, logs.db-journal
Attempt to launch Radarr and see if it works. If so, congrats!
If not, then the log DB didn't get corrupted, and it might have been the primary database. You will need to restore from backup.
Move the following files to Trash: nzbdrone.db, nzbdrone.db-journal
Open the Backups folder you see and find the .zip archive with the most recent date. Decompress it. Move everything from the resulting folder into the main Sonarr data folder, over-writing any files.
Attempt to launch Radarr and see if it works. If it does not work, you'll need further support, you can report the issue through the issue tracker
```

But in go, if i past ~/.config/NzbDrone i have no result ...

If i cherch 

logs.db, logs.db-journal > No result
nzbdrone.db, nzbdrone.db-journal > no result

**Comment by galli-leo** [comment]
Try .config/Radarr

**Comment by Eldoc62** [comment]
No, they open just my desktop...

I cherch on : 

right clic on Radarr (icon app) and select : view the contents of the package

In there... There is nothing config :/



![capture d ecran 2017-09-06 a 17 25 08](https://user-images.githubusercontent.com/31630516/30120180-6b6db04a-9328-11e7-9a04-a398d6a5f1a4.png)

Are these hidden files?

**Comment by Eldoc62** [comment]
[Capture d’écran 2017-09-06 à 17.24.44.pdf](https://github.com/Radarr/Radarr/files/1281681/Capture.d.ecran.2017-09-06.a.17.24.44.pdf)

**Comment by galli-leo** [comment]
Yes but they should still show up. Did you add the ~/ before .config ?

**Comment by Eldoc62** [comment]
Ohhhh   !!!!

Ok ;)

~/.config/Radarr

I trash first : 

logs.db, logs.db-journal

And after try no good...

But after erase 

nzbdrone.db, nzbdrone.db-journal

IS VERY GOOD 

Big thanks :))  👍
