### ISSUE TITLE
Bookmark to add a movie to RADARR while looking at IMDB, etc.

### ISSUE THREAD

**Issue by gregcbrown** [Radarr/Radarr#2044]
Similar to Couchpotato. Bookmark in browser allows movie that is being looked at in browser to be added to RADARR movies database...

**Comment by galli-leo** [comment]
There is a chrome extension that does exactly this called Pulsarr.

**Comment by gregcbrown** [comment]
Well that's great if I used chrome, which I don't and never will. Couchpotato works with firefox, which I use.
