### ISSUE TITLE
Radarr doesn't find movies in spotweb at NAS DS216play

### ISSUE THREAD

**Issue by marthijn009** [Radarr/Radarr#2047]
Hello,

I installed radarr and spotweb at my NAS. Spotweb is working. 
But it radar doesn't find any movie at my spotweb server. The connection is ok when I test in the settings.
When I checked a movie what is actually in spotweb and I try to find this movie with Radarr it doesn't find it. 
So I added this specific movie, and I do a manual search and it doesn't find it.

In the log: 

DownloadDecisionMaker | No results found | 11:15pm
NzbSearchService | Searching 1 indexers for [The Mummy] | 11:14pm

Kind regards and thanks for helping.

**Comment by hotio** [comment]
Not sure, but I think spotweb is not supported.

**Comment by galli-leo** [comment]
Did you try searching on spotweb with title and year?

**Comment by marthijn009** [comment]
Thanks for the tip, I put usenet crawler in te indexers and now it is working. So i think spotweb is not supported well.

Offtopic: any advise for good indexers for sonarr/radarr

**Comment by hotio** [comment]
I recommend getting a few and adding them to NZBHydra, add NZBHydra to Radarr. Filter the results (duplicates), cleanup the release names (obfuscated) with NZBHydra, perhaps also filter by retention.

pfmonkey, nzbgeek, drunkenslug, bindex.one, to just name a few
