### ISSUE TITLE
Organize movie does rename folder but does only move the movie file and leaves the old folder

### ISSUE THREAD

**Issue by mrvonwyl** [Radarr/Radarr#2048]
**Description:**
I think this i a bug. When I rename a movie via organize including the folder name (static path off) then the old folder is not deleted. And other file such as subtitle, coverart and so on are left in the old folder.

Example:
I have "Movie A (2017)/Movie A (2017).mkv" and "Movie A (2017)/Movie A (2017).srt" 
The new name is Movie B.
The result is "Movie B (2017)/Movie B (2017).mkv" and "Movie A (2017)/Movie A (2017).srt"

I actually do not mind if the srt (or whatever other file) is not renamed. But it should be moved to the new folder and the old folder should be deleted. Otherwise you would have lots of old folders with files belonging to movies, which you would have to clean up manually.

**Radarr Version:**
Radarr Ver. 0.2.0.846
develop

**Comment by mrvonwyl** [comment]
@galli-leo so has this been fixed?

**Comment by galli-leo** [comment]
Yes on the latest nightly
