### ISSUE TITLE
NZBGet is running on NFS, Radarr isn't - Is this causing my problems?

### ISSUE THREAD

**Issue by jwvanderbeck** [Radarr/Radarr#2049]
I am having basically all sorts of issues with Radarr just plain not working.  It isn't making the empty folders for added movies, it isn't downloading available movies.  It did find a single movie and sent it to NZBGet, and NZBGet did download it, but Radarr still thinks it is waiting on NZBGet.

So I started to dig into things to troubleshoot before crying for help, and I saw this on the Wiki "A key point to remember is that Radarr (and Sonarr) get path information from the downloader, so you'll also need to setup NZBGet, SABNzbd or any other downloader to use UNC paths too."

Does that mean in my situation where NZBGet is running on the NFS (In my case a Drobo) but Radarr is not, that it won't work because the paths will look different to each?

I also use Sonarr, but that is running on the NFS so it works perfect.  Radarr is new so best I can tell is not available as a Drobo app so I am just running it on my Windows machine for the moment.

**Comment by galli-leo** [comment]
What exactly is NFS / Drobo? Also most likely Remote Path Mapping is what you would need to set.

**Comment by jwvanderbeck** [comment]
That is exactly what I needed but it took me 3 passes through the settings to notice it there down at the bottom so thank for pointing it out!
