### ISSUE TITLE
Importing existing movies - unable to get info

### ISSUE THREAD

**Issue by stumueller** [Radarr/Radarr#2051]
I have been using Radarr for a couple of weeks now. It has been finding movies and moving and renaming them fine. I am not using network drives.

I decided to import my existing movies, around 600 of them. it has ran through and imported them, I can see posters for them all, but its not pulling any other metadata for them and its not finding them on disc. no matter how often I click rescan. I get an error in the logs saying:

Error occurred while executing task RefreshMovie: Unable to connect to the remote server
Updating Info for MOVIE

I have restarted Radarr but still no luck.

I have since added a couple more movies that it didn't pick up hte first time round, and again I have posters for them but its not finding the files on disc.

My naming convention is M:\Movies\MOVIE (YEAR)\MOVIE - QUALITY - (YEAR).ext

Radarr has no problem with this for movies it has pulled from my IMDB list and that it has snatched and renamed. Its existing movies that are the problem.

Check first that your problem is not listed in our wiki section:
I have checked the wiki and this problem isn't mentoned. I have also searched the error message on your issues list and again it is not mentioned.

**Radarr Version:** 0.2.0.846

**Logs:** attached latest log file
[radarr.txt](https://github.com/Radarr/Radarr/files/1289838/radarr.txt)

Thanks for any help you can give

**Comment by galli-leo** [comment]
The radarr mapping server was down for a few hours. This is resolved now.
