### ISSUE TITLE
Movies copying to destination folder but removing after file finishes copying

### ISSUE THREAD

**Issue by Chadthedj** [Radarr/Radarr#2052]
So starting, my same install has been working great for months. However, something within the last 2-3 weeks has caused my automatic and manual file importing/copying to stop working. Every movie I download attempts to move the file (I see in the downloads folder it makes the backup file and the destination file is showing the file copying). However right when it finishes, it disappears and reattempts until it gives up. Checked my PGID and PUID settings and are fine. I can move the file manually using another machine and using the organize feature to rename the file tool so I can't imagine the folder is locked out by Radarr . Manual import feature does the same same like the auto import.

I started noticing some permission denied errors popping up but my Synology environment hasn't changed nor anything on docker container was modified:

```
/Downloads/complete/[SOME MOVIE]
 
[v0.2.0.846] System.UnauthorizedAccessException: Access to the path is denied.
```

[As quoted thanks for some people helping me out in the Radarr community] Its like the link to the inode (the filename basically) is being created for a split second, then file exists so it tries to overwrite, but since there is a file lock since the copy hasn't "finished" it errors:

`at System.IO.File.Move (System.String sourceFileName, System.String destFileName) [0x00116] in <204f770036d441bb8dfd3daba3550e83>:0
  at NzbDrone.Common.Disk.DiskProviderBase.MoveFile (System.String source, System.String destination, System.Boolean overwrite) `

Radarr Version: Radarr Ver. 0.2.0.846

Logs: [radarr.txt](https://github.com/Radarr/Radarr/files/1290087/radarr.txt)

**Comment by djzeratul** [comment]
watching this issue

**Comment by hotio** [comment]
Perhaps you could try adding something unique to the filename like release group, to see if it only shows up when the names are identical....

**Comment by Chadthedj** [comment]
Updated to Radarr Ver. 0.2.0.852, still an issue. 

@hotio are you asking to change the folder name so the file name changes?

**Comment by djzeratul** [comment]
I think @hotio meant to change the file naming convention in Media Management tab of settings to add something that might not be in the original filename, like release group.

**Comment by Chadthedj** [comment]
@hotio Same result testing that idea

**Comment by Chadthedj** [comment]
As a test, I ran radarr as root with the same issue/error as above. Visually, it copies the files but when it finishes it disappears. On the logs, it's stating a file lock issue and just deleting it.

**Comment by galli-leo** [comment]
Does this still occur on the latest version? Because if yes, I think your out of luck as I have no clue why this would occur, unless you have a broken drive or filesystem.

**Comment by eschizoid** [comment]
I am still having this problem with version `Ver. 0.2.0.1293`

**Comment by jfairham1** [comment]
Me too now same version ;(

**Comment by Bokun23** [comment]
I've got the same problem with my freenas plugin
