### ISSUE TITLE
Movie Linking Timeframe

### ISSUE THREAD

**Issue by myfrontpocket** [Radarr/Radarr#2053]
I used to use Radarr/NZBGet on a Raspberry Pi setup not so long ago, but the pi didn't have enough oomph for me, so I built a better machine and chose to go with Windows 7 (64-bit). Now I can download and unpack in about five minutes, give or take, depending on the file size. This is fantastic... buuuuut I have noticed something a bit off. For instance, this evening I found a movie I wanted... Radarr sent it off to NZBGet at 8:41pm (EST). Download and unpack took about eight and a half minutes. So, that puts completion time around, let's say, 8:50. I checked the download status about four minutes after it had completed; this is when I found the whole process took the eight and a half minutes, and it was done. On a whim, I checked my library and saw that the movie folder and movie, in it's full size, were there and properly named (Radarr is setup to handle this). That tells me that Radarr had indeed picked it up from NZBGet and imported it, but checking the Activity tab in Radarr shows it as paused. Radarr didn't actually link the movie until 8:57. OnDownload notifications were sent off at 8:59.

I don't really understand why that whole process took nearly 9 minutes after the download completed. If the Check For Finished Download task executes every thirty seconds (I think it's thirty), then I would think that this all should have happened and finished a LOT sooner. It couldn't have been from moving the movie file from download location to library location, because like I said, that happened within four minutes of download/unpack  completion.  This isn't the first time either. Is this a real issue, or am I just missing something?

**Comment by hotio** [comment]
Usually when it shows up as paused in activity, it is either paused or radarr is busy copying the movie file.
I never saw anything really out of the ordinary...

4-9 minutes however is indeed a lonng time, perhaps you are running really slow hardware, given that you are using such an outdated OS.

**Comment by galli-leo** [comment]
It could also indicate a failing harddrive or a hd needing some defragmentation. This would explain why radarr took so long to move the file.

**Comment by myfrontpocket** [comment]
I think you misread part of my statement. The movie didn't take long to move at all. I checked NZBGet (using nzb360 on Android) maybe around 8:54; it said it completed the process four minutes ago. When I saw this, I checked my library and the movie was already there in it's entirety. So within that four minutes window it was moved and renamed. It didn't get linked until three minutes afterward 8:57).

I don't think it's a hardware issue either. Here's my setup:

Kingston SV300S37A 240GB SSD
AMD A8-7600
4GB Corsair PC3-10600 DDR3 RAM
MSI A68HI motherboard

Like I said, I can download and unpack in about five minutes on average; versus an hour for the raspberry pi system I had.

Does Radarr preallocate the space for the copy/move? This would explain that I saw the movie in my library, but it wasn't actually linked until some time afterward.

**Comment by hotio** [comment]
it's done when radarr says it's done, what more is there to say? And an unpack of 5 minutes is slow, unless we talking 50gb files. A core i3 2120 does it in 1.5 minutes for around 6-8gb, a ryzen 1600 in seconds...

**Comment by myfrontpocket** [comment]
Download and unpack, together, is an AVERAGE of five minutes. That's just me estimating. In this instance unpack was 1:59 for 13GB. Download an unpack was about eight and a half minutes together, as I stated.

I understand Radarr "says it's done when it's done". My concern is, though, why is that state of done so long after it's been downloaded, unpacked, and apparently imported and renamed? If it's a hardware thing or some mechanism that I'm not aware of that's the culprit, then that's all well and good. All I'm doing here is bringing up that concern in case it is Radarr related. I mean, you don't think it's a little odd that, if the download/unpack was completed around 8:50 and sometime between then and 8:54 Radarr picked that up and moved/renamed it, that the movie wasn't actually linked until 8:57?

**Comment by hotio** [comment]
Not much to troubleshoot without any log files or something else. The few times I saw radarr move a file it all updated right after done copying...

**Comment by myfrontpocket** [comment]
Right, and that's what I expect to happen, and that's what I've seen before. That's the reason I find it odd that for the delay. I'll see if I can find anything in the logs.

**Comment by myfrontpocket** [comment]
Looks like I'm mistaken. I have an external attached to my R7000 router for NAS capabilities, which is where my library sits. Looks like Windows preallocates the space on the drive for the move, so what I thought I was seeing as a complete transfer was really just a "placeholder" (I didn't see this happen when using Raspbian). So the transfer took that long, and Radarr did indeed link the movie as soon as it was finished. Apparently the R7000 isn't all that great at Samba transfers, from my research. This is something I'll just have to live with until I can get a true NAS. Thanks, guys.

**Comment by hotio** [comment]
Routers and what you call a true NAS are all shit, just a heads up. Nothing beats your own hardware build combined with a linux server os.
