### ISSUE TITLE
{   "message": "NotFound" } Radarr & Sonarr on same machine

### ISSUE THREAD

**Issue by keppo070** [Radarr/Radarr#2055]
**Description:**   "message": "NotFound" in radarr on win10x64 when Sonarr is used on same machine

Both application are started bij starting the executable by an non admin user. In testing it looks like to coexist both applications, Radarr should be running as a service. Then both application are accessble through the webpages.

**Radarr Version:** 0.2.0.846
**Sonarr Version:** 2.0.0.4949

**Logs:**
[Warn] IndexHtmlMapper: File C:\programdata\radarr\bin\UI\index.html not found

**Comment by galli-leo** [comment]
Try starting as an admin / reinstalling Radarr.

**Comment by keppo070** [comment]
Just installed the latest version 0.2.0.852. Seems to work now.

**Comment by OverlordQ** [comment]
I'm getting this issue with 0.2.0.1120, It will work for a few days, then stop working. 

This is when running as my user account in C:\Radarr
