### ISSUE TITLE
Mediacover Poster are not shown in radarr

### ISSUE THREAD

**Issue by keppo070** [Radarr/Radarr#2056]
**Description:**
File C:\ProgramData\Radarr\MediaCover\18\poster-250.jpg not found

Mediacover poster jpg's are present on the location. Cannot be read by radarr. Open in a jpgviewer confirms the right movie. All black rectangle where movie poster should be standing

**Radarr Version:**  0.2.0.852 develop
**Logs:** File C:\ProgramData\Radarr\MediaCover\18\poster-250.jpg not found

**Comment by weirdcrap** [comment]
So to be clear, Radarr's log says the file isn't there but you have verified that \18\poster-250.jpg exists and can be viewed in photo viewer?

This sounds like a file/folder permissions issue on one of the directories in your Radarr install or possibly on the files themselves. 

Can you verify that C:\ProgramData\Radarr\ and it's subfolders are at the very least readable by the user Radarr runs as on your system?

**Comment by keppo070** [comment]
Radarr runs under win10x64. It's a non-admin user. I start radarr under the same non-admin user. 
![image- 2017_09_11-21_09_12](https://user-images.githubusercontent.com/8713528/30293284-427305a4-9739-11e7-9640-1f928f94cfb2.png)
![image- 2017_09_11-21_09_48](https://user-images.githubusercontent.com/8713528/30293288-483ab400-9739-11e7-84a5-83c6d5119ff0.png)

I can create and delete a file in the folder. The same for some font files. The fonts are there on the location but the log says they are not

**Comment by jamesmacwhite** [comment]
The font issue, were aware of, see: https://github.com/Radarr/Radarr/issues/2065. A fix has been submitted, awaiting a merge.

The MediaCover stuff, either its a permissions issue or could be related to a recent find in Sonarr relating to case sensitivity on Windows.

https://github.com/Sonarr/Sonarr/commit/50b01d8d00be3daa6cc840e76d7da5560d45d82b

**Comment by keppo070** [comment]
I switched to a linux/docker solution with radarr. I can't confirm because I don't use radarr anymore on windows. Sorry

**Comment by galli-leo** [comment]
No worries. It works fine for me on windows, might have been permissions
