### ISSUE TITLE
Filtering does not work

### ISSUE THREAD

**Issue by keppo070** [Radarr/Radarr#2057]
**Description:** Filtering does not work

In the movie overview selecting all, monitored or any other status does not change the view

**Radarr Version:** 0.2.0.852

**Logs:**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by weirdcrap** [comment]
Are there any errors in the log? If so please post a full copy of your debug log so the developers can take a look at what is going on. Without a log it is extremely difficult to figure out exactly what is going wrong.

You can download your logs from the System > Logs > Files menu in the web interface. Please be sure to check the log for any personally identifiable information (PII) like API keys, usernames, passwords, etc before posting.

**Comment by keppo070** [comment]
No, there are no errors in the log. Besides the ones that its missing C:\ProgramData\Radarr\MediaCover\33\poster-250.jpg files. And some font files C:\ProgramData\radarr\bin\UI\Content\fonts\opensans-semibold.woff2

But that cannot be related to the filtering option...can it?

**Comment by keppo070** [comment]
Narrowed it a bit down. Win10x64 + Chrome Version 61.0.3163.79 (Official Build) (64-bit)
-Filtering works on the machine where radar is installed. 
-Filtering works in private mode on a remote machine
-Filtering in normal mode on a remote machine does not work. Disabling all extensions does not help

Firefox seems to work.

**Comment by weirdcrap** [comment]
Are the two remote machines you mention the same machine? If it is and it works in private mode it sounds like a cache issue to me...

**Comment by galli-leo** [comment]
Yeah definitely sounds like a caching issue.

**Comment by keppo070** [comment]
I cleared browsing data from the beginning of time and it resolved the issue. Filtering works! thnx
