### ISSUE TITLE
Unable to add dbkitty as usenet indexer

### ISSUE THREAD

**Issue by Mikrz** [Radarr/Radarr#2059]
**Description:**

When adding dbkitty.club as an indexer, the error: `Unable to connect to indexer: Sequence contains no elements` is thrown. While searching the issues, it seems this is *supposed* to be because the indexer does not support imdbid lookup, however dbkitty explicitly does per it's api docs with this example: `?t=movie&imdbid=0023010`

**Radarr Version:**
0.2.0.852

**Logs:**
``System.InvalidOperationException: Sequence contains no elements
  at System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0006c] in <2392cff65f724abaaed9de072f62bc4a>:0 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].TestConnection () [0x0001a] in <dfb697aa5b854737b83dd060079816eb>:0 ``

**Comment by djzeratul** [comment]
The workaround for this is to add a copy of an indexer you already have, hit save, and then edit the indexer to use dbkitty.club's url and api key. This should "trick" it into adding successfully.

**Comment by galli-leo** [comment]
Or add the indexer with search turned off. (It might also be the case when your indexer does not have any results for star wars)
