### ISSUE TITLE
OSX - Error occurred while executing task ApplicationUpdate: Startup folder not writable by user 'itsMe'

### ISSUE THREAD

**Issue by Eldoc62** [Radarr/Radarr#2060]
Hi everybody,

I am on OSX and radarr turns well, thanks for everything.
This morning I want to update but this fault appears:

Error occurred while executing task ApplicationUpdate: Startup folder not writable by user 'itsMe'

The radarr application is in a "software" folder, I have the right to write and read. I do not understand...

**Comment by Eldoc62** [comment]
I need to have a legal problem because it does not rename files ... Does not create folders etc ...

**Comment by Eldoc62** [comment]
if i make : 
sudo chown 777 /dir...

I've in return : 

Read-only file system

**Comment by galli-leo** [comment]
You need to do sudo chmod 777 /dir for changing permissions. chown is for changing owner (like sudo chown itsMe /dir

**Comment by Eldoc62** [comment]
Oh ok thanks, but where is the startup folder please ?
Because i test with the icon app and no change :/

**Comment by galli-leo** [comment]
You probably have to do it recursively (for every folder). So sudo chmod 777 -R /Path/To/Radarr.app

**Comment by Eldoc62** [comment]
:/

Mac-de-user:~ user$ sudo chmod 777 -R /Volumes/HDD_1/Log\'s/Apple/Mac/Sonarr.app 
chmod: -R: No such file or directory
Mac-de-user:~ user$

**Comment by galli-leo** [comment]
You have to use Radarr.app. Also whoops got my arguments the wrong way around: sudo chmod -R 777 /Volumes/HDD_1/Log's/Apple/Mac/Radarr.app
