### ISSUE TITLE
Manual Import not setting movie title

### ISSUE THREAD

**Issue by ChrisDurham** [Radarr/Radarr#2061]
When I run the manual import from the wanted tab, the system lists all the movies to be imported and internally parses the filename correctly because it gives warnings about quality not being better or movies that are not already in Radarr, however it does not fill in the movie name in the Movie column - this means that I have to manually search for each movie and link it which is time consuming and unnecessarily annoying. I'm sure this used to work in an earlier release but it hasn;t worked for some time.

 
<img width="1152" alt="manualimport" src="https://user-images.githubusercontent.com/29458969/30266039-ff344356-96d5-11e7-9283-4bef77d2534e.png">

**Comment by ChrisDurham** [comment]
Debug log sample 

17-9-11 09:39:23.2|Debug|DetectSample|Runtime is over 90 seconds
17-9-11 09:39:23.2|Debug|Parser|Parsing string 'Die Another Day (2002)'
17-9-11 09:39:23.2|Debug|Parser|Movie Parsed. Die Another Day - 2002 
17-9-11 09:39:23.2|Debug|Parser|Language parsed: English
17-9-11 09:39:23.2|Debug|QualityParser|Trying to parse quality for Die Another Day (2002)
17-9-11 09:39:23.2|Debug|Parser|Quality parsed: Unknown v1
17-9-11 09:39:23.2|Debug|Parser|Release Group parsed: 
17-9-11 09:39:23.3|Debug|ImportDecisionMaker|Analyzing 1/1 files.
17-9-11 09:39:23.3|Debug|Parser|Parsing string 'Die Another Day (2002) Bluray-1080p Proper REAL.mkv'
17-9-11 09:39:23.3|Debug|Parser|Movie Parsed. Die Another Day - 2002 
17-9-11 09:39:23.3|Debug|Parser|Language parsed: English
17-9-11 09:39:23.3|Debug|QualityParser|Trying to parse quality for Die Another Day (2002) Bluray-1080p Proper REAL.mkv
17-9-11 09:39:23.3|Debug|Parser|Quality parsed: Bluray-1080p v2 Real:1
17-9-11 09:39:23.3|Debug|Parser|Release Group parsed: 
17-9-11 09:39:23.3|Debug|ImportDecisionMaker|Size: 11741208186
17-9-11 09:39:23.3|Debug|VideoFileInfoReader|Getting media info from Z:\Uploads\Film\Die Another Day (2002)\Die Another Day (2002) Bluray-1080p Proper REAL.mkv
17-9-11 09:39:23.6|Debug|ImportDecisionMaker|Checking quality for this video file to make sure nothing mismatched.
17-9-11 09:39:23.6|Debug|ImportDecisionMaker|Quality (Bluray-1080p v1) of the file is different than the one we have (Bluray-1080p v2 Real:1)
17-9-11 09:39:23.6|Debug|Parser|Parsing string 'Die Another Day (2002)'
17-9-11 09:39:23.6|Debug|Parser|Unable to parse Die Another Day (2002)
17-9-11 09:39:23.6|Debug|VideoFileInfoReader|Getting media info from Z:\Uploads\Film\Die Another Day (2002)\Die Another Day (2002) Bluray-1080p Proper REAL.mkv
17-9-11 09:39:23.7|Debug|DetectSample|Runtime is over 90 seconds


As you can see from the debug log it parses the movie title, year and quality correctly but just doesn't set the Movie in the UI

**Comment by hotio** [comment]
Manual import = manual labor

**Comment by majora2007** [comment]
This is a problem I've been facing for the past month. What's worse is on a large library (2k+ movies), the search interface is very slow to load and doesn't work all the time.

**Comment by GenericPolarBear** [comment]
I also have this issue, it's very annoying because I've seen a few uploaders always name their files "yay.mp4" or something like that, no matter the actual movie name.

**Comment by hotio** [comment]
This is a function to be used very rarely when radarr is stuck, if you need to use this regularly, you are doing it wrong.
