### ISSUE TITLE
The new movie title "IT" is not mapping properly

### ISSUE THREAD

**Issue by deecypher** [Radarr/Radarr#2063]
Sorry if this has already been reported, but the upcoming movie "IT" (2017) is not mapping correctly. Please see screenshot below.

**Radarr Version: Radarr Ver. 0.2.0.852 (develop)

**Logs: [radarr.txt](https://github.com/Radarr/Radarr/files/1292362/radarr.txt)

![it](https://user-images.githubusercontent.com/9927271/30272544-29ecfa5e-971f-11e7-9b7c-56861f53c254.jpg)

**Comment by galli-leo** [comment]
Try refreshing movie info. This should be fixed as of the latest release.
