### ISSUE TITLE
Manual Import does not handle Propers Properly

### ISSUE THREAD

**Issue by ChrisDurham** [Radarr/Radarr#2064]
When a movie is imported through the Manual Import wizard it does not handle propers ie
(500) Days of Summer (2009) Bluray-1080p Proper.mkv is imported as Bluray-1080p quality and the Proper quality is dropped. This causes the system to try and download a Proper for the film. 
I have 2 Radarr systems - 1 has a decent internet connection which I use for downloading but the other has the disk space and TV attached so I copy movies onto an external drive and then import them.

**Comment by bakerboy448** [comment]
likely fixed in v3

if it still exists in v3 please open a new GHI and fill out the template
