### ISSUE TITLE
Fresh install of 0.2.0.852 is missing fonts

### ISSUE THREAD

**Issue by switchpants** [Radarr/Radarr#2065]
A fresh install of 0.2.0.852 is missing the opensans fonts.  They are not present in the tar (Linux) or zip (Windows) release archive.   The fonts were included in 0.2.0.846 (and prior?) releases.

When Radarr starts, it logs several warnings about the missing fonts:

> |Info|NancyBootstrapper|Starting NzbDrone API
> |Warn|StaticResourceMapper|File /opt/radarr/UI/Content/fonts/opensans-light.woff2 not found
> |Warn|StaticResourceMapper|File /opt/radarr/UI/Content/fonts/opensans-regular.woff2 not found
> |Warn|StaticResourceMapper|File /opt/radarr/UI/Content/fonts/opensans-light.woff not found
> |Warn|StaticResourceMapper|File /opt/radarr/UI/Content/fonts/opensans-regular.woff not found
> |Warn|StaticResourceMapper|File /opt/radarr/UI/Content/fonts/opensans-light.ttf not found
> |Warn|StaticResourceMapper|File /opt/radarr/UI/Content/fonts/opensans-regular.ttf not found
> |Warn|StaticResourceMapper|File /opt/radarr/UI/Content/fonts/opensans-semibold.woff2 not found
> |Warn|StaticResourceMapper|File /opt/radarr/UI/Content/fonts/opensans-semibold.woff not found
> |Warn|StaticResourceMapper|File /opt/radarr/UI/Content/fonts/opensans-semibold.ttf not found

**Comment by galli-leo** [comment]
@ja

**Comment by galli-leo** [comment]
@ja

**Comment by jamesmacwhite** [comment]
@galli-leo. That's very odd. The recent WOFF2 change only adds an additional font file and hasn't touched any of the other fonts. Is Ubuntu Mono missing as well?

**Comment by galli-leo** [comment]
Maybe it searches for the different styles in individual files?

**Comment by jamesmacwhite** [comment]
Looking into it now.

**Comment by jamesmacwhite** [comment]
Is it fresh installs we think this isolated to? I'm running the latest maintenance release and the fonts are OK, I'm on Windows though.

**Comment by jamesmacwhite** [comment]
Actually scratch that, they are displaying as the fall back. I was cached. Investigating

**Comment by jamesmacwhite** [comment]
@galli-leo Hang on. All of sudden in the source, all of the fonts files except for the woff2 fonts are present. My commit didn't remove the existing fonts?!

**Comment by jamesmacwhite** [comment]
@galli-leo I've created a PR which should fix the issue and merge the existing fonts back into the correct "Fonts" folder. Bizarre.

**Comment by jamesmacwhite** [comment]
This might also be relevant

https://github.com/Sonarr/Sonarr/commit/50b01d8d00be3daa6cc840e76d7da5560d45d82b

**Comment by vivienney** [comment]
Having the same issue under unRAID where Radarr is hosted in a docker.

**Comment by pven** [comment]
Getting a simular warning after upgrading on my Synology:
```
17-9-12 15:25:53.6|Warn|StaticResourceMapper|File /volume1/@appstore/radarr/share/Radarr/UI/Content/fonts/opensans-light.woff2 not found
17-9-12 15:25:53.6|Warn|StaticResourceMapper|File /volume1/@appstore/radarr/share/Radarr/UI/Content/fonts/opensans-regular.woff2 not found
```

**Comment by pven** [comment]
Can I somehow push this PR to my Synology? Or should I just wait until a new updates shows up in the UI?

**Comment by jamesmacwhite** [comment]
@pven Do you have SSH/Command line access to your synology? If so, you can just add the fonts to the correct directory:

Guidance here:

https://1drv.ms/f/s!Alt7MxbfstovyPUJAoNSpxOZOXILTw

**Comment by pven** [comment]
Thanks! I had to create the fonts-directory (Fonts already existed, with fonts in it). It looks like it is working now.

**Comment by jamesmacwhite** [comment]
Yeah, at the moment there are two font directories. "fonts" and "Fonts" this is where the issue occurred and the font files diverged. For now, all fonts need to be in the "fonts" directory and the "Fonts" (not the capital) directory needs to be removed.

When this is merged the actual folder will become "Fonts" to be consistent with everything else and all fonts contained within. Paths updated accordingly.

**Comment by Sevenon7** [comment]
Confirming the last comment, I noticed on my installation the error that is being generated is for the path `Warn|StaticResourceMapper|File /volume1/@appstore/radarr/share/Radarr/UI/Content/**fonts**/opensans-light.woff2 not found`, which doesn't exist. However, there is a `/volume1/@appstore/radarr/share/Radarr/UI/Content/**Fonts**/opensans-light.woff2`. I created a symbolic link, restarted and that fixed the issue.
