### ISSUE TITLE
Change Default Availability

### ISSUE THREAD

**Issue by stumueller** [Radarr/Radarr#2067]
Hi

I was searching on Reddit and your issue list and could only find one article that relates to this, but it was for OMBI.

So I set a min availability of 'In Cinema' for all my movies. Any new movie added through the GUI will remember this, along with path settings, monitor or not, and profile.

However I have Radarr also import my watch list from IMDB. When doing this it picks up the path and profile fine, even the monitor status, but it defaults the min availability to 'physical release' rather than 'in cinema'.

Is it possible to get IMDB imported lists to auto set to 'In Cinema' without going through the movie editor?

Is it an option that can be added in?

Thanks for your time

Stuart

**Comment by djzeratul** [comment]
When you add the list, simply select the default in the settings dialog:

![settings_-_radarr](https://user-images.githubusercontent.com/1778738/30304606-26770ec4-9723-11e7-9f4c-d17c5aa37fd1.png)
