### ISSUE TITLE
Renaming issue (Movie TitleThe) 

### ISSUE THREAD

**Issue by panicacid** [Radarr/Radarr#2068]
Running latest development branch

I've set movie file names and folder names to TitleThe this works perfect for the file itself but the folders are still being named The Movie Name not Move Name, The.

Sorry on mobile at the minute so the best I could do.

**Comment by panicacid** [comment]
Also this is duplicating movies for example I already have Dark Crystal, The but it's created The Dark Crystal.

**Comment by djzeratul** [comment]
You need to turn static path off for the movie in question, and enable folder renaming in settings. Then it will rename the folder properly.

![mad_max__fury_road_-_radarr](https://user-images.githubusercontent.com/1778738/30304478-905b5efe-9722-11e7-8565-bdbef0e31f63.png)

![settings_-_radarr](https://user-images.githubusercontent.com/1778738/30304481-930d5d5a-9722-11e7-8684-429a843fe08e.png)

**Comment by nathan951** [comment]
I have the same issues.
{Movie TitleThe} does NOT place "The", "A" at end. 
Also will not recognize  "Movie Title, The" as a movie, so it will re-download it. 
It will even re-download when I change static dir of  "The Movie Title" to "Movie Title, The"

**Comment by panicacid** [comment]
Nathan, since confirming my media management settings are the same as above (I. E. Disable static folder naming) I then had to delete all of my media library disable my lists and then re import all of my movies.

This resolved the issue for me., The and, As all worming fine.

**Comment by djzeratul** [comment]
Re-importing the entire library likely wasn't necessary... you can use the Movie Editor to select all of your movies to set the Static Path variables to "No", and then use "Organize" to rename the folders and files in question.

**Comment by glardian** [comment]
@djzeratul 

Has the movie editor / organize option been updated to actually rename the existing folder? Or does it still create a duplicate and leave a bunch of orphaned folders?

Issue #353 more deeply explains what I mean.

**Comment by djzeratul** [comment]
@glardian No, currently it moves the files to a new directory, the remaining files are then orphaned in the old folder.

**Comment by galli-leo** [comment]
This is fixed in the latest nightly.
