### ISSUE TITLE
[feature] find orphan directories

### ISSUE THREAD

**Issue by pven** [Radarr/Radarr#2071]
I have no idea if this is possible, but I like the idea so I just ask it. ;-)

I have all my movies in one big directory. It is possible there is some old stuff in there that is not managed by Radarr. Is it possible to add some kind of orphan check to find the unmanaged directories / movies?

**Comment by hotio** [comment]
`find /onebigdirectory -iname *oraphan*` will find all the directories containing `oraphan`.

How long it takes depends on the size of your big directory.

**Comment by pven** [comment]
I mean 'orphan' ;-)

**Comment by pven** [comment]
Good idea? ;-)

**Comment by pven** [comment]
Anyone? :-)

**Comment by galli-leo** [comment]
You should be able to do that using Bulk import.
