### ISSUE TITLE
List sync error with clean library level = wipe on internet outage

### ISSUE THREAD

**Issue by pawi** [Radarr/Radarr#2072]
Description:
Had an internet outage today an Radarr couldn't sync with my trakt list. I activated "Clean Library Level: Remove & Delete Files" and Radarr decided that even with an error on list sync to process the (empty) list.

Radarr Version: Version 0.2.0.852
Logs:
```
RSS Sync Completed. Reports found: 100, Reports grabbed: 1
Error occurred while executing task ApplicationUpdate: Error: NameResolutionFailure
Trakt List https://api.trakt.tv/users/foolala/watchlist/movies?limit=100 Error: NameResolutionFailure
[ttn][xxx] was in your library, but not found in your lists --> Removing from library and deleting files
```
Expected behavior: If TraktImport fails don't process the results.

**Comment by galli-leo** [comment]
Fixed in the latest version
