### ISSUE TITLE
Radarr Not Automatically Pulling New Movies Released

### ISSUE THREAD

**Issue by jeff15110168** [Radarr/Radarr#2073]
**Description:**

So I just moved an install over of Radarr (and Sonarr) from my laptop to a new desktop pc. I moved all the data in Radarr (and nzbdrone for Sonarr) folder from C:/programdata (as well as Plex data from local %appdata%), and now both Sonarr and Radarr seem to be giving me issues with automatically pulling files and/or downloading files with RSS sync.

I think it may be some sort of authentication error, but I'm not too sure. I saw this in the trace log for sonarr and Radarr did not capture the most recent PreDB release of Pirates Carribean Dead Men Tell No Tales.

17-9-12 01:24:17.6|Debug|X509CertificateValidationPolicy|Certificate validation for https://192.168.0.185:32400/identity failed. RemoteCertificateNameMismatch
17-9-12 01:24:17.6|Trace|PlexServerProxy|Version response: {"MediaContainer":{

Is there some permission error or something I need to change since I moved data over? Manual search and automatic grab when in the movie work fine, but the RSS sync auto-download doesn't seem to be working currently.

**Radarr Version:** 0.2.0.852

**Comment by jeff15110168** [comment]
hmm, so i went into indexer options and changed the delay to -28 days, and then the movies recently released automatically queued into the torrent client.

Looks like it may have been an issue with the physical being released in october, but the scene release already being out.  Since all the miovies are currently set to preDB minimum availability (the default before that stopped working, so it is now preDB=physical release).

Is it recommended to use Physical or Announced minimum availability? I use a mix of private and public trackers, mostly I pull scene release (AMIABLE, SPARKS etc.) from public sites (they have RSS enabled), then for movies I like I pull higher quality releases from PTP/AHD/HDT (those are not RSS enabled and I manually search them).

**Comment by djzeratul** [comment]
If you're pulling scene releases and want them to come down as soon as they are verified as "released", use PreDB and set a quality profile that prevents CAM or TS from coming down (unless you want CAM or TS, then by all means keep them in your profile).

**Comment by jeff15110168** [comment]
PreDb is deprecated, it switches to physical. I changed it to announce for now with negative 45 days and disabled TS, HDTS and CAM.

On Sep 14, 2017, at 1:54 AM, Michael Klass <notifications@github.com<mailto:notifications@github.com>> wrote:


If you're pulling scene releases and want them to come down as soon as they are verified as "released", use PreDB and set a quality profile that prevents CAM or TS from coming down (unless you want CAM or TS, then by all means keep them in your profile).

**Comment by galli-leo** [comment]
This is what we recommend: https://github.com/Radarr/Radarr/wiki/Minimum-Availability
