### ISSUE TITLE
[Request] A way to simply add a custom complex usenet RSS feed

### ISSUE THREAD

**Issue by RonGeorge** [Radarr/Radarr#2075]
I have several pay indexers and they allow you to create custom RSS feeds. These feeds have your api, # of items, categories, etc already listed in them. The problem is there is no place to put them inside any of the programs that handle automation. Hydra wont, Jackett wont, and Radarr wont. Radarr allows for a custom .torrent RSS, but not for Usenet. I've tried to add it as a custom newznab, but I get XML errors. I then tried to pull out the API and put it as a custom newznab, but still got errors. It might even be cool to add it to "Lists" or another Tab based on the lists functionality. Here's a sample. 

https://rss.omgXXXXXX.me/rss-download.php?catid=16,20&user=XXXXXXXX&api=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&eng=1&nuke=1&nodupe=1&limit=200

This gives XML errors, but pulling it via the browser works fine.

**Comment by hotio** [comment]
And what would be the use-case? Seems pointless to me, since you can already filter categories.

**Comment by RonGeorge** [comment]
Good question.

This would be around managing several RSS feeds for usenet some of which may be from the same indexer. With Usenet indexers you have the ability to create your own custom RSS feed, based on specific categories, flags, recommendations, size, etc. Indexers are very different from each other, more than just general categories like TV vs Movies. Perhaps one indexer is good at niche foreign films or whatever. Perhaps some indexers are much more active than others, so you want to be able to hit 200-300 every hour (their time limit) to be closer to seeing everything they see. Being able to create that RSS and just paste it in somewhere would be beneficial. Instead of just adding the general categories under Indexer and hope that it finds what you need. The other great thing about something like this would be being able to add specific curated RSS lists, such as omg's most popular list or some geek's most wanted list. At least allow them to enter the search results so they can be curated within Radarr. I see it acting like the Lists tab. Just post your RSS feeds in a list format and they automatically get pulled when you do an RSS sync.

**Comment by galli-leo** [comment]
Well without a concrete rss feed (i.e. an account on such a site) nothing I can implement.
