### ISSUE TITLE
Failure to import/Missing root folders

### ISSUE THREAD

**Issue by ghost** [Radarr/Radarr#2076]
I'll apologize first because a lot of this is going to be from memory, and there are no logs currently available.  I'm also not sure if this is the right place either as it seems to involve more than just Radarr, but I had to start somewhere.

I'm running a Synology NAS with DSM 6.1.3-15152 Update 4.  All packages are installed without Docker as it's currently unsupported on my my NAS model.  

I first started by installing Sonarr, and when that was fully setup/configured how I wanted it, it ran with no issues for at least two days; episodes were being found, grabbed, downloaded, imported etc.

I then installed Radarr, configured each setting for that too, and then imported my existing files.  It successfully grabbed some wanted movies, and sent them to the download client.  

For the very first movie that was completed, I believe it was imported.  Certainly a folder was created, and a hardlink created.  All subsequent downloads failed to be imported with the "Import failed, path does not exist or is not accessible by Radarr" error.  That error seems to be well documented, and is usually assigned to permission problems.  Everything I could see was telling me that sc-media group had r/w permissions to the relevant folders.  I checked permissions on individual sub-folders, and files too.  I set the permissions again, and changed them to explicit rather than inherited.  Neither could I import any of the files manually as I would be told no video files existed in the folder.  I could also mention that during this time, the first movie which was imported continued showing as missing.

Eventually, I decided to try a re-install of Radarr.  I did this making sure yet again about access permissions.  I configured it, and imported my library again.  Even though it wasn't tested by grabbing, downloading, and importing a movie, I believe I was now able to complete a manual import so I believed it was all fixed now.

However, the next time I went to Sonarr, it was reporting that the root folders were missing.  I followed instructions I found for removing old root folders, but when I went to assign them again the folders were no longer visible below the parent folder.

The current situation is that I uninstalled everything, and then put Mono, and Sonarr back which is working again.  I would like to put Radarr back, but am feeling reluctant to do so as I'm getting the impression that one is breaking the other.

I was running updated versions of both Sonarr, and Radarr; master branch for the first and developer for the second.  I also have the latest version of Mono I believe.

I'm presuming a problem with folder structure wouldn't allow me to set up the root folders and import my library at all.  But inn case it is a problem the structure runs:  volume/video/Films with individual movie folders underneath.  Video is the shared folder that was automatically created by the media server package when it was installed.  Sonarr uses a similar structure with Anime, and TV as the root folders within video.

Any help on this at all would be greatly appreciated as it's become incredibly frustrating.

**Comment by galli-leo** [comment]
Sorry for such a late response, but Radarr and Sonarr shouldn't interfere in anyway (unless you set Radarr or Sonarr to set permissions of folders? But they shouldn't use the same folders anyways). Also without any logs, this is almost impossible to debug.
