### ISSUE TITLE
Bulk Import Won't Import Movies Anymore

### ISSUE THREAD

**Issue by ranlien** [Radarr/Radarr#2079]
**Bulk Import:**

I have movies in Folders that are named for the Movie Type (Drama, Science Fiction, ...).  My Science Fiction folder has 248 Folders in it.  One for each movie as outlined in the FAQ.

I attempted to Bulk Import because I added a new movie and Radarr was unable to find the movie.  Then copied the movie to my Western folder which only has fifteen movies.  Bulk Import found and imported the movie without issue.  Then I edit the File location of the movie and removed the movie from my Western folder.

There seems to be a file or folder limit.  I have 1278 movies imported from several folders so far.  This will be an issue moving forward.  I still my Comedies and Family folders to import.  The Comedies will have over 300 folders.

I think I need to audit the database so that I can find out if all movies have been imported.

Radarr Version: 0.2.0.852
Mono Version: 5.2.0.215 (tarball Mon Aug 14 15:46:12 UTC 2017):**

**Logs:**

[radarr.txt](https://github.com/Radarr/Radarr/files/1304227/radarr.txt)

**Comment by Cryson** [comment]
I am on 0.2.0.852 as well, and it will not import any movies. The folders and files are correct but it's not detecting anything.

**Comment by jtrott** [comment]
Bulk import not working for me on 0.2.0.910 either.

**Comment by Aesculapius** [comment]
Same problem here, missing a lot of movies this way on 0.2.0.910

**Comment by galli-leo** [comment]
Sorry for the late response, but without a debug log this is impossible to pin-point. I am guessing either the folder was not correctly named or something else was off.

@Cryson @jtrott @Aesculapius Please open a new issue with a debug or trace log while doing the bulk import. I won't be able to help otherwise.
