### ISSUE TITLE
BUG in Bulk Movie Importing setting monitoring to No

### ISSUE THREAD

**Issue by oziee** [Radarr/Radarr#2082]
When i chose to import movies already in the file system, i changed the first row movie item listed for Monitoring to NO.. (all other rows changed to NO as they should) 

However when the movies imported into Radarr.. ALL the movies imported were added as monitored instead of not monitored

Radarr Ver. 0.2.0.852 - develop (new install - changing from CP)

**EDIT**
On a side note with this problem.. is there a way to select multiple movies and bulk change their monitored status??

**Comment by galli-leo** [comment]
Movie editor is used for bulk editing.

**Comment by oziee** [comment]
ahh thank you.. that is what I was looking for

but the bug still remains when the items are imported to begin with

**Comment by FirstRulez** [comment]
Same issue applies with the profile selector - change one visually changes all. Does this want logging as a separate bug

**Comment by galli-leo** [comment]
@FirstRulez That is intended to work this way.

**Comment by FirstRulez** [comment]
In that case would be much more intuitive as a UI to have the Monitored and Profile sleectors once near the Add Selected button and remove them from each individual row. imo.

**Comment by boshuda** [comment]
Where I think there is a bug is when doing a bulk-import -- if any of the movies' 'Monitor' dropdown is changed, then the Monitor value changes for ALL of the movies.  Even for unselected movies.  Related is that when a selected movie's Monitor dropdown is changed from 'Yes' to 'No' that movie is then unselected.  If an unselected movie's Monitor value is changed from No to Yes that movie is NOT likewise selected.  This is inconsistent.  This might require a new issue report.

If changing one movie's 'Monitor' value changes all 'Monitor' values is the desired behavior then I feel it should be removed from the individual movie's line and placed as a single item above the entire list.  That way at least the intended behavior is clear.

**Comment by PeterPan669** [comment]
This issue is still present as of today.
