### ISSUE TITLE
radarr not recognizing remux

### ISSUE THREAD

**Issue by sahara101** [Radarr/Radarr#2084]
I am using radarr for qnap, no issues until know. 
I added latest pirates of the Caribbean and it does not recognize the remux file.

    30.3 GB is larger than maximum allowed 16.3 GB (for Pirates of the Caribbean: Dead Men Tell No Tales)
    HDTV-1080p is not wanted in profile
File is actually Pirates.of.the.Caribbean.Dead.Men.Tell.No.Tales.2017.1080p.BluRay.REMUX.AVC.DTS-HD.MA.7.1.RoSubbed-playBD

Not even this is recognized: Pirates.of.the.Caribbean.Dead.Men.Tell.No.Tales.2017.1080p.Blu-ray.AVC.DTS-HD.MA.7.1-PCH

Same error, tracker is filelist.
In profile I have HD-BR; Remux 1080; Bluray 1080; Web-DL 1080

Thank you

**Description:**

Check first that your problem is not listed in our wiki section:
* https://github.com/Radarr/Radarr/wiki/Common-Problems
* https://github.com/Radarr/Radarr/wiki/FAQ

Provide a description of the feature request or bug here, the more details the better. 
Please also try to include the following if you are reporting a bug

**Radarr Version:**

**Logs:**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by galli-leo** [comment]
Can you provide some trace logs?

**Comment by sahara101** [comment]
https://pastebin.com/ggXyEWm3

I used manual search for the log, hope it helps.
Also the movie IT is downloading It comes at night..which is another movie. If I use manual search, nothin is found. Then why is it automatically downloading a wrong movie?

Thanks.

**Comment by sahara101** [comment]
Help?

**Comment by galli-leo** [comment]
According to the logs there is no release containing Remux in the title. What indexer are you using?

**Comment by sahara101** [comment]
Filelist

**Comment by galli-leo** [comment]
Yeah so after consulting the logs a second time, seems like your indexer does not give us the full release name and cuts off the quality information. I would suggest talking to your indexer staff about that.
