### ISSUE TITLE
"{IMDb Id}" in movie folder format ignored

### ISSUE THREAD

**Issue by rickatnight11** [Radarr/Radarr#2086]
## Description

I have `{IMDb Id}` in my **Movie Folder Format**, but it gets ignored when adding new movies to the watch list.

## Reproduce

My format string is:

```
{Movie TitleThe} ({Release Year})[{IMDb Id}]
```

...which the UI suggests is correct:

![image](https://user-images.githubusercontent.com/76622/30500615-2aa27f08-9a2d-11e7-8149-f24949d42beb.png)

...however when I add a movie like **Transformers: Age Of Extinction**, Radarr creates the following destination folder:

```
/movies/Transformers Age of Extinction (2014)[]
```

## Radarr Version

0.2.0.846

## Logs

None relevant that I can find.

**Comment by KBlixt** [comment]
have you tried go to advanced settings in media management and turn on "Automatically Rename Folders"?

**Comment by rickatnight11** [comment]
This affects new movies added to the watch list, so there aren't folders to rename from the start. As soon as I add the movie, I can see that the destination Radarr _will_ use once a download is found and completed is wrong.

**Comment by KBlixt** [comment]
yes or no? have you read the explanation for that option? maybe it could help.

**Comment by rickatnight11** [comment]
I have not set it, because I don't yet want to rename all of my existing movie folders are this time. I'm in the middle of changing my movie folder scheme, but if I change them all right now, this will wreak havoc on my backups (the directory names will be different, so the next full backup would sync tons of duplicates).

If that feature is the only way that this is supposed to work, then I'd say that violates the principle of least surprise.  I would expect that feature (by name and description) to affect existing folders on disk. I would not expect it to have any bearing on the naming of _new_ folders.

**Comment by rickatnight11** [comment]
Hm, here's what the explanation for that setting says:

![20170916_074652](https://user-images.githubusercontent.com/76622/30512023-534103b8-9ab3-11e7-9c20-37dd64d5e4ba.png)

This suggests that this will automatically name folders on each disk scan, which I don't want, and further suggests that this setting has no bearing on the issue in seeing anyway.

Again, I'm reporting an issue with along a new movie to Radarr that hasn't been downloaded yet. The destination movie folder string is being rejected _except_ for the IMDB id.

**Comment by KBlixt** [comment]
Well, I'm a fairly new user, but wouldn't the files and folder stay the same unless you actively told the movie to search and scan disk or use the bulk organize in the  movie editor? you'd have to have the movie not monitored though. But you should already have that on movies you don't want to change so it shouldn't be an issue. just be careful not to press the search and scan for all movies...

**Comment by rickatnight11** [comment]
Thanks for the help!  I'm pretty sure this is a bug, though, and the setting you're referring to shouldn't be related.

**Comment by rickatnight11** [comment]
I think I found the culprit:

https://github.com/Radarr/Radarr/blob/7db92c6bcfd9fad57e3f6ad368ce8cd0d35e4c68/src/NzbDrone.Core/Organizer/FileNameBuilder.cs#L615-L621

**Comment by Qstick** [comment]
That method isn't called for folder names. If the example is working the issue is likely not in filenamebuilder. Does the movie you are trying to rename have a IMDb Id stored in the db? (Is there a link to IMDb on the movie detail page?)

**Comment by rickatnight11** [comment]
Gotcha.  Yes, it does!  Every time I add a new movie, I confirm the IMDb ID is missing from the folder name, then open the IMDB link from the same page, copy the ID from the URL, and manually edit the movie to insert it into the destination folder.

**Comment by rickatnight11** [comment]
I just added a new movie as an example:

![screenshot from 2017-09-16 20-31-17](https://user-images.githubusercontent.com/76622/30517008-45179a20-9b1e-11e7-868c-7e411a77fc03.png)

**Comment by calexandre** [comment]
Hello, just wondering...but could this be related to  #2089 ?

**Comment by galli-leo** [comment]
You need to enable automatic folder renaming. Radarr will only rename if the path is off (e.g. new quality, new imdbid, new year, etc.) This is because we create the path before we get metadata from TMDB. Thus we only have the imdbid after we set the path.

**Comment by rickatnight11** [comment]
Hey, @galli-leo, can we we-open this as a feature request instead of a bug, then?

I can confirm that enabling automatic folder renaming does fix this behavior, but I wouldn't expect it to be necessary, and I'm still not convinced it's not going to mess with the rest of my existing movie library.

Also, can you clarify what you mean by:

> ...you have to set the movie paths to be dynamic for this to work...

**Comment by galli-leo** [comment]
Movie paths can either be static (like it is now, they are set in stone when the movie gets added) or dynamic (they get adjusted when a file is import or when a disk scan is issued (provided the automatic rename option is turned on). You can set the default for new movies to be dynamic by disabling the Movie Paths default to Static option. Existing movies will still have a static path so they should not be renamed. You may see a RenameMovieFolder message show up in the UI, but that will get executed regardless of your options, because it will check to see if the path needs changing / is dynamic and if not "complete" successfully.

Regarding opening a feature request, it would have to be along the lines of "Redo the whole movie folder thing" to get "real" dynamic paths. This is something I would like to do in the future, but I currently don't have enough time to do that.

**Comment by rickatnight11** [comment]
Gotcha.  Confirmed that enabling *Automatically Rename Folders* and disabling *Movie Paths Default to Static* fixed the behavior!  New movies show the IMDB Id in their destination path!

Understood regarding level of effort towards revamping how this works.  Is there room for better documenting this behavior in the UI/Wiki?  It certainly did not follow the principle of least surprise 😃
