### ISSUE TITLE
Not an issue, just information and celebration

### ISSUE THREAD

**Issue by sparklyballs** [Radarr/Radarr#2088]
The radarr image on our [Container list](https://tools.linuxserver.io/dockers) just hit the no2 spot behind sonarr in excess of 9.6m pulls, which although it includes refreshes and update checks in that figure is still pretty impressive

**Comment by hotio** [comment]
Yeah, I myself have about 181k for hotio/suitarr, but I have noticed it is the most useless metric there is. For all I know it could just as easily have come from just 5 users. After a user mentioning they started using it with watchtower I saw the usage/pulls ramp up fast...

**Comment by sparklyballs** [comment]
yeah you can't correlate the figure to actual users but you can say there is a higher probability that a  higher growth rate between two images would indicate more users

**Comment by hotio** [comment]
I'm surprised people are still creating PullRequests for CouchPotato. Is kinda like this...
![klaagmuur](https://user-images.githubusercontent.com/26902309/30513932-768065b8-9b0c-11e7-90fa-546393b71217.jpg)

**Comment by galli-leo** [comment]
Kinda late (:|), but thanks for making those images!
