### ISSUE TITLE
Radarr is renaming moveis even if I set to not rename

### ISSUE THREAD

**Issue by msdos** [Radarr/Radarr#2089]
**Description:**

In Settings -> Media Management -> Movie Naming -> Rename Movies is set to *no*, but Radarr is renaming the folders and the movie files when is handling the download from transmission folder to my HD folder.

`/var/media/my-drive/transmission/downloads/My-Movie (2011) [1080p]/My.Movie.2011.1080p.BRrip.x264.YIFY.mp4` became `/var/media/my-drive/My Movie (2011)/My-Movie (2011) [1080p].mp4`

**Radarr Version:**
Version
0.2.0.852
Mono Version
5.2.0.215 (tarball Wed Aug 23 15:31:59 BST 2017)

**Comment by calexandre** [comment]
Also happening to me!

Using Radarr 0.2.0.852 - Sep 10 2017 on Windows 10

**Comment by galli-leo** [comment]
Radarr will import movie files into the path listed in the movie details page. If you want to preserve the original folder name you will have to enable automatic folder renaming and use {Original Title} for your folder naming scheme.

**Comment by calexandre** [comment]
Hello galli-leo, could you please re-open this issue?
I believe the op is also telling that the movie is getting renamed when it should not be.
I can also confirm this issue, and it has nothing to do with folder renaming...

**My settings:**
![image](https://user-images.githubusercontent.com/1485193/30721258-1899a0c0-9f23-11e7-8be2-f6f13347b6af.png)

**If I try to download, my qbittorrent will show a renamed version, even when I explicitly set Radarr not to rename:**
![image](https://user-images.githubusercontent.com/1485193/30721362-8cbae630-9f23-11e7-85c7-c5c7be9666f6.png)

**You can check the original source:**
![image](https://user-images.githubusercontent.com/1485193/30721388-b6a02fb4-9f23-11e7-9fd8-fda1b50a9b6e.png)


This behavior was not happening on the previous release **0.2.0.846 - Aug 28 2017**.

**Comment by calexandre** [comment]
Okay, I did some further testing and apparently this is only happening on YIFY releases (I believe it may be related to multiple trackers having different names for the same release).
I tested with other releases, such as RARBG, etc...and everything works as expected.

However, the YIFY thing does not seem right, and maybe theres something going on...
I can confirm that I downloaded the one with the name "**Transformers (2007) 1080p Bluray x268 - 1.8GB - YIFY**" and it got renamed to **Transformers (2007) [1080p]**.

**Here's a screenshot of my download sources:**
![image](https://user-images.githubusercontent.com/1485193/30723069-ba964a50-9f2c-11e7-8bbd-d91e60e9c9d1.png)

**Comment by msdos** [comment]
> If you want to preserve the original folder name you will have to enable automatic folder renaming and use {Original Title} for your folder naming scheme.

And do I do if I want to preserve the original *movie filename*? That's what I'm trying to do but even setting everything to "dont rename" in Radarr it still renames it.

> I believe the op is also telling that the movie is getting renamed when it should not be.

Precisely @calexandre.

![selection_001](https://user-images.githubusercontent.com/489034/30723202-0b29f0f0-9f0c-11e7-8fce-09ee009b702e.png)

Maybe it's something with "Completed download handling"?

![selection_002](https://user-images.githubusercontent.com/489034/30723205-114e062e-9f0c-11e7-9182-f04290bee7dd.png)

**Comment by calexandre** [comment]
@msdos check my post above. Can you please test with another release (something not YIFY)?

**Comment by msdos** [comment]
Indeed, `My.Movie.2010.1080p.BluRay.x264-UNTOUCHABLES.mkv` the folder was renamed but not the movie file.

**Comment by calexandre** [comment]
@galli-leo could you please look into this? Its fairly easy to reproduce...just add two or more trackers hosting the same torrent, then try to start a download (a YIFY title for example).
The downloaded movie will get renamed even if I set all options to not rename...

**Comment by bobbintb** [comment]
I think I am getting this as well. I have a file with the release group name at the front of the file and it renamed it with the name at the end. It also changed the case on another file that was all lowercase.
