### ISSUE TITLE
Detected Quality is Incorrect

### ISSUE THREAD

**Issue by houdini3009** [Radarr/Radarr#209]
I decided to test out Radarr. I added a few existing movies in my library. Radarr seemed to go out and download a copy of each one of these movies, regardless of whether it needed to or not. For instance I have a 1080p copy of a movie. Radarr went out to download a 720p copy of the same movie.

Is this a known issue? How does Radarr determine the current quality of a movie in your library? It doesn't look like it's shown anywhere in the UI.

**Comment by julestop** [comment]
This is related to https://github.com/Radarr/Radarr/issues/170

**Comment by onedr0p** [comment]
yep #170 will track this
