### ISSUE TITLE
Can't add any Torznab feed

### ISSUE THREAD

**Issue by aaronson2012** [Radarr/Radarr#2091]
Hello,

I can't seem to add any Torznab feed into Radarr. I have added them in the past and currently added Torznab feeds still work, but I cannot add ant new feeds. After I click test it says testing failed.

Also, adding Torznab feeds in Sonarr works fine.

Can someone try to replicate this? If you are able to successfully add one, It could be an issue with my version of Mono. Maybe?

Radarr Version: 0.2.0.852

Logs: Attached
[radarr.txt](https://github.com/Radarr/Radarr/files/1308749/radarr.txt)

**Comment by hotio** [comment]
Are you running Mono X Limited Edition?

**Comment by aaronson2012** [comment]
No, I an not.

**Comment by hotio** [comment]
It's really hard to rule out if your mono version is the cullprit, if you are so hell bent on keeping it a secret.

**Comment by hotio** [comment]
Ah found it: mono-5.4.0.56

**Comment by aaronson2012** [comment]
Is there a recommended version of Mono i should be using? Just curious.

**Comment by galli-leo** [comment]
The torznab feed you are adding probably does not support searching by imdbid.
Try asking the authors of the feed to enable that or add the indexer by disabling searching and then reenabling it. Then we will just search by title.
