### ISSUE TITLE
Rename blue missing to unreleased.

### ISSUE THREAD

**Issue by FlynnLives** [Radarr/Radarr#2092]
When a new movie is added to the library that has been announced/still in theater/not released/not on predb, it shows in the "Missing Only" filter. I did not see an existing bug for this. 

With Sonarr when you add a TV show that has not aired and the show is monitored it will not show up in missing as it is not missing, it just hasn't been released in any form yet. 

This is a mix of a bug report and as well an enhancement request. It would be nice to have missing only only show items that are truly missing either due to intentional deletion or other failure.

![screen shot 2017-09-16 at 7 21 08 pm](https://user-images.githubusercontent.com/5238672/30517174-481d8540-9b14-11e7-8ba4-6946c3b6d6fe.png)

Version 0.2.0.852
Mono Version 5.2.0.215 (tarball Mon Aug 14 15:50:54 UTC 2017)
Debian 9 x64

**Comment by hotio** [comment]
So you wanna rename a blue Missing to Unreleased?

**Comment by FlynnLives** [comment]
That is a good way to put it, thanks @hotio

**Comment by FlynnLives** [comment]
This is still a issue and should be fixed

**Comment by FlynnLives** [comment]
still a needed feature

**Comment by FlynnLives** [comment]
oh look at that, still a bleeping issue

**Comment by geogolem** [comment]
lol.. -- sorry - im just laughing at the comment on Sep 25 "still a bleeping issue"

 I came across this and think it might be beneficial also

"Missing, Monitored, but not yet considered available" is what the legend says for Blue..

![image](https://user-images.githubusercontent.com/23205277/47770329-5bac2600-dcb5-11e8-9db8-3339b8606877.png)

Maybe we should change the text in Missing and orange to "Ignored" 
leave missing and red as "Missing"
and change the text in Missing and Blue to "Unreleased"

the colors would stay the same, just the text on the colours in the table.

I also think the legend should remain the same as well as it would also describe what "Ignored" and "Unreleased" mean in that context..
@FlynnLives - do you see any issue with what I proposed? Does anybody object to these changes?

**Comment by FlynnLives** [comment]
Sounds good to me, but there should be also a way to filter it, so one can see things that are truly missing versus what is essentially not available yet

**Comment by FlynnLives** [comment]
Sounds good to me, but there should be also a way to filter it, so one can see things that are truly missing versus what is essentially not available yet

**Comment by geogolem** [comment]
Sort of like the filter on the Wanted Page, 

![image](https://user-images.githubusercontent.com/23205277/47786649-d0e22000-dce2-11e8-89ab-1284e6464924.png)

I'm kind of unsure about which filters to add specifically...

Maybe we should just have a colour icon corresponding to each case..
