### ISSUE TITLE
[Feature Request]Do Not Delete Original When Manually Importing

### ISSUE THREAD

**Issue by octophetus** [Radarr/Radarr#2093]
I want to suggest that when you manually import it doesn't delete the original file. I let my client handle the removing of my torrents. Normally Radarr just makes a copy and leaves the original alone. But if it doesn't make the proper connection for some reason and I have to manually import it, every time the original then gets deleted. Could we have manual imports behave similarly to how our normal torrents are set up?

**Comment by hotio** [comment]
Something wrong with copying?

![imp](https://user-images.githubusercontent.com/26902309/30522892-ad5452c2-9bd7-11e7-8bc1-096fdabb308b.png)

**Comment by octophetus** [comment]
Wow. I feel sooooo dumb. I've been using this for a while now and I've literally never noticed that option.
