### ISSUE TITLE
Camel Casing UI screwup

### ISSUE THREAD

**Issue by hotio** [Radarr/Radarr#2095]
This one is for you @jamesmacwhite 
I think you missed another one, when gallileo reverted the commit.

See the path /torrents -> /Torrents

![imp](https://user-images.githubusercontent.com/26902309/30522934-68e579f8-9bd8-11e7-9b7d-1453f8fa150a.png)

**Comment by jamesmacwhite** [comment]
@hotio Hmmm. The UI consistency attempt was reverted as far as I was aware. There shouldn't be anything I have committed still present as it was under one PR, which was reverted.

It would appear the camel case has been set on `h3` for some time, even in Sonarr. 

https://github.com/Sonarr/Sonarr/blob/develop/src/UI/Content/Overrides/browser.less#L14

**Comment by hotio** [comment]
OK, Could very well be that it's been in there a long time, just noticed it and thought of you :-)

**Comment by jamesmacwhite** [comment]
@hotio Thank you for thinking of me ;)

As far as I know that should only be cosmetic, it won't cause issues with paths that are lower case, or at least shouldn't. All of my changes that caused issues with form values/path based stuff got reverted.
