### ISSUE TITLE
Full support for fuse filesystems 

### ISSUE THREAD

**Issue by Nottt** [Radarr/Radarr#2096]
- Why

To be able to use radarr entirely on fuse filesystems, downloading and processing stuff on different servers than the ones that run radarr. Making Radarr a "brain" that can control and fully operate  "slaves" all over WAN/not being running in the same server

To support fuse filesystems I think only a few changes need to be done :

- Remove the write check 

Rclone mounts allow writing files ( although only reliable for really small files ), supports moving/renaming/creating/deleting. 

Plexdrive mounts allow moving/renaming/deleting/creating. 

The only thing both shouldn't be doing is directly writing a file inside the mount, anything else is fine. So both should be fine if you are using a fully fuse setup, even if you can't "write" on it. 

Both should allow you to move/rename files on it if you use a source /path already inside your mount, that's expected and fine for this kind of setup.

Example : 

You upload your file to your cloud storage, it will appear on /mnt/rclone/downloads, radarr will import it to /mnt/rclone/movies/, so it should perform a server-side rename and move on your cloud storage if properly executed. Radarr not necessarily has to be involved in making the file appear on your rclone mount and that's okay.  

- Emulate `mkdir` and `mv`  when importing/post-processing with fuse filesystems

If you use the terminal, you can create folders, move files between folders while at same time renaming it, rename files and delete folders/files all using the commands `mkdir` and `mv` and `rm` .

However Radarr by itself can't do this as I suspect it will write a copy to the folder it wants to import, when it could just use that commands internally or emulate them somehow to do it server-side on cloud storage/fuse filesystems. 

I think this would be a great addition to Radarr, as it would be able to act as fully central "brain" to as many places you want to download/process stuff you want and also proper support cloud storage.  I hope I have been clear on my request and what could be done to achieve this. I did a lot of testing myself and I'm willing to be a guinea pig for this feature too.

**Comment by galli-leo** [comment]
I haven't really worked with the underlying move & copy stuff as that was luckily already in sonarr, so I can't really say how much changes would have to be made. I will mark this issue as a feature request, but I doubt I will ever get around to implement this. In theory if you are using DownloadedMoviesScan command radarr should only do a move if the underlying disk stuff sees source and destination folders are on the same drive. So maybe you wouldn't have to change anything beyond allowing readonly paths.

**Comment by Wyall** [comment]
I'm hijacking this request: For me a great first step would be the ability to add plexdrive mounts to a list of watched folders. Only letting radarr watch for movies there, nothing else.

Reason: Sometimes I just move movies from my main drive to google drive and that's mounted for plex via plexdrive. The movie is still available, but radarr can't see it and I can't add the plexdrive folder as a normal DL destination folder, as writing is not allowed. I'd be great to tell Radarr "Also look in this folder for movies, but don't allow DL there".
I can give further information, but the main point is that mounting gdrive via plexdrive is the best option for plex streaming (gdrive has API limit), but the folder is not and won't be writeable.

**Comment by galli-leo** [comment]
@Wyall What I do with my setup (all movies in gdrive after an initial 6 hours):
1. Have a union drive between local filesystem and plexdrive /mnt/union. Radarr imports files there. Thus they get saved on the local drive, since only that is readwrite
2. Have a script that runs periodically, uploading older files to gdrive. Since the path stays the same (/mnt/union/Movies/Movie 2017/Movie 2017.mkv), Radarr doesn't care and doesn't even need a disk refresh.

**Comment by Wyall** [comment]
@galli-leo Interesting idea, didn't know this exists. Will look into it.
I also think that I didn't understand Radarr's scanning process. Each movie has a folder assigned where the movie is or is expected to be, so Radarr won't scan other folders and maybe find the movie there (and possibly change that specific path). Thanks!
