### ISSUE TITLE
[Feature] Custom & Multiple Edition 

### ISSUE THREAD

**Issue by Vitriia** [Radarr/Radarr#2099]
Hi, 
I have two feature request :

- The ability to add manually custom Edition (for exemple Black & Chrome edition for Mad Max Fury Road)
- The ability to had multiple Edition at same time (?) (for exemple had Normal and Black & Chrome edition for Max Max Fury Road)

P.S: Thx for all your awesome work ! 

[AB#901](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/901)

**Comment by galli-leo** [comment]
This will probably have to wait for TMDB to support listing / adding editions.

**Comment by Ashkaan** [comment]
Any chance we can just manage it manually?  It's kind of rare anyway.

**Comment by Silent-Remux** [comment]
@Qstick is this coming in v3?

I'd love to see the following foe example, in the same folder managed by radarr, along with upgrades etc.

Theatrical Remux
Unrated Edition Remux
Director's Cut Remux

**Comment by Qstick** [comment]
>For example, there could be a place where we can type in the edition of the movie right from Radarr.

This part is in v3 now

**Comment by bakerboy448** [comment]
- The ability to add manually custom Edition (for exemple Black & Chrome edition for Mad Max Fury Road)
  -  Per Q this was added in v3 - https://github.com/Radarr/Radarr/commit/e52288bd67f52855de9c2b537d5715b80910f66a
- The ability to had multiple Edition at same time (?) (for exemple had Normal and Black & Chrome edition for Max Max Fury Road)
  - Closing as a dup of https://github.com/Radarr/Radarr/issues/1910
