### ISSUE TITLE
"Downloaded" column shows wrong values

### ISSUE THREAD

**Issue by dawtmaytrikx** [Radarr/Radarr#210]
As can be seen on the screenshot below, the downloaded column takes on some wrong values for certain qualities. All my DVD quality releases are displayed as 1080p, and SDTV and WEBDL-1080p releases are labelled with names of profile's I've set up. Other qualities (BluRay-720p/1080p, WEBDL-480p, HDTV-720p/1080p) however are displayed correctly.

![2017-01-10 23_21_58-add movie - radarr](https://cloud.githubusercontent.com/assets/3049190/21912952/98156066-d929-11e6-9997-d24ac8572f1d.png)

**Comment by galli-leo** [comment]
Yea I messed up in the latest release. Should be an easy fix.

**Comment by kieranlee1970** [comment]
Rebuilt Radarr library, still showing lots of movies as WebDL-1080p even though the filename has correct quality of Bluray-1080p

**Comment by kieranlee1970** [comment]
Perhaps its because I put the quality before the year in the title instead of after, is it possible to parse for this?
