### ISSUE TITLE
Folder naming issue when adding a movie via API 

### ISSUE THREAD

**Issue by gb160** [Radarr/Radarr#2102]
Hi,
Ive put together a very basic Kodi addon, when using the API to add a movie I'm using the options

        'addOptions': {
             'ignoreEpisodesWithFile': 'false',
             'ignoreEpisodesWithoutFiles': 'false',
             'searchForMovie': 'true'

the correct movie gets added, then downloaded fine, but there is a slight issue with the folder naming.
The folder gets the correct movie name but the year is (0), although the actual movie file gets renamed correctly.

example:

movie (2007).mkv
ends up in folder:
movie (0)/movie (2007).mkv

Ive checked I'm passing all the required parameters when adding the movie, and if i change the option to:

                'searchForMovie': 'false',

and then leave it a while, then trigger the search manually, the folder gets created as it should:
movie (2007)/movie (2007).mkv

I appreciate this is a small issue but thought id bring it up.
Happy to provide logs etc if that would help.

**Comment by tdorsey** [comment]
I ran into this issue as well, but you can get the year from the search endpoint and pass it as part of the payload in the movie POST, and it will set properly.

**Comment by galli-leo** [comment]
Yeah, since we generate the folder path before we get metadata from TMDB you have to pass the correct year to the add endpoint.

**Comment by gb160** [comment]
Ah, that makes sense.
Works fine now, cheers.
