### ISSUE TITLE
Unable to toggle off movies to be unmonitored. 

### ISSUE THREAD

**Issue by abarber229** [Radarr/Radarr#2107]
**Description:**

Check first that your problem is not listed in our wiki section:
* https://github.com/Radarr/Radarr/wiki/Common-Problems
* https://github.com/Radarr/Radarr/wiki/FAQ

Provide a description of the feature request or bug here, the more details the better. 
Please also try to include the following if you are reporting a bug

**Radarr Version:** 
0.2.0.855

**Logs**
Attached to issue

Issue Description:
Sometimes when movies download, I have to manually click rescan hard drive on that movie for it to pick up that it has been downloaded. As a workaround which is more tedious but works, is that I would untoggle the movie to unmonitored so that it would not down another copy instead of clicking on rescan disk. However, now when I click the icon to monitor/I monitor nothing happens. It acts like it wants to change but stays monitored. I have tried to uninstall and reinstall Radarr but that didn’t work. I could say which version this started on. Any help or pointed in the right direction would be helpful. 
[radarr_logs.txt](https://github.com/Radarr/Radarr/files/1323831/radarr_logs.txt)

**Comment by galli-leo** [comment]
Is this still an issue on the latest version of Radarr? (Note you might have to refresh your browser, for the file to be correctly displayed in the UI)

**Comment by Fyb3roptik** [comment]
This is still an issue!!!

## About
```markdown
### Version
0.2.0.1293
### Mono Version
5.20.1.19 (tarball Thu Apr 11 09:07:22 UTC 2019)
```
