### ISSUE TITLE
Manual search: Titles double URL encoded then "Failure to find movie title in release name."

### ISSUE THREAD

**Issue by MikeRatcliffe** [Radarr/Radarr#2108]
**STR**
- Configure NZBGeek as your search provider (it may happen with all providers, I don't know).
- Add "Clifford's Really Big Movie"
- Click on the movie then on the search tab.

The following is displayed along with the error "Failure to find movie title in release name":
`Clifford&amp;039;s.Really.Big.Movie.DVDRip.XviD.720.x.416.HeB.DubbeD-DDL-IL.ReUp`

![urlencoding issue](https://user-images.githubusercontent.com/116941/30747254-8bb071b6-9fa4-11e7-8fb8-22d2cae9f688.png)

The apostrophe (') appears to have been double-URL encoded.

**Radarr Version:**
0.2.0.852

**Logs:**
Nothing useful but for the sake of compliance:
```
17-9-22 14:37:05.9|Info|NzbSearchService|Searching 2 indexers for [Clifford's Really Big Movie]
17-9-22 14:37:07.6|Info|DownloadDecisionMaker|Processing 2 releases
```

**Comment by galli-leo** [comment]
Does this happen with every movie?

**Comment by MikeRatcliffe** [comment]
You mean every movie with an ampersand? I don't know but I can check.
