### ISSUE TITLE
The 0.2.0.852 Linux pre-release archive unpacks a Windows version

### ISSUE THREAD

**Issue by wsw70** [Radarr/Radarr#2109]
**Description:**

This is the first time I am using Radarr so apologies if I am missing something obvious but when downloading the **Linux** pre-release at https://github.com/Radarr/Radarr/releases/download/v0.2.0.852/Radarr.develop.0.2.0.852.linux.tar.gz (the link is in the pre-relase description at https://github.com/Radarr/Radarr/releases/tag/v0.2.0.852), the archive unpacks to something which furiously looks like the Windows version (plenty of `.dll` and a `Radarr.exe` executable:

```
root@tor:~/Radarr# file Radarr.exe
Radarr.exe: PE32 executable (console) Intel 80386 Mono/.Net assembly, for MS Windows
```

**Radarr Version:** 0.2.0.852 (Linux)

**Comment by hotio** [comment]
Yeah, it's the radarr mono release...

**Comment by galli-leo** [comment]
Yeah you have to run it using mono (`mono Radarr.exe`)
