### ISSUE TITLE
Add IMDB Ratings to Radarr

### ISSUE THREAD

**Issue by king8084** [Radarr/Radarr#2115]
upon investigating this issue https://github.com/Radarr/Radarr/issues/1940   it seems possible easily with
http://www.omdbapi.com/

which is still active, you just need to join their patron here
https://www.patreon.com/bePatron?u=5038490

for 10$ a month for unlimited API calls server, i would be willing to handle the 10$ cost monthly as long as we finally get this running

this will allow us to start using radarr as even a search engine to search movies based on ratings...etc, this will kick radarr to the next level

[AB#858](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/858)

**Comment by galli-leo** [comment]
The problem isn't the $10 cost, but integrating this with our existing metadata provider TMDB. Btw you can already search by rating using TMDB lists. While not really that intuitive searching by rating year genre, etc. will peobably have to wait on the new ui, so more metadata won't really help.

Also if this feature is something a lot of people want, I can integrate it into the Radarr API. We wouldn't need OMDB integration then.

**Comment by king8084** [comment]
it is in the top 10 most wanted feature on the feathub, so i assume lots of people want it, currently you have to click IMDB icon on the front page, 1 by 1...imagine having them all within radarr and you can actually even search movies by ratings, this is game changing feature that will totally shit on CP (not that radarr isnt already superior)

**Comment by king8084** [comment]
so any chance to get this?

**Comment by galli-leo** [comment]
Definitely not in the "old" ui. I might add it to the radarr api over the next few weeks.

**Comment by king8084** [comment]
any ETA for this?

**Comment by apcrcom** [comment]
Any progress?

**Comment by galli-leo** [comment]
No eta and no progress

**Comment by galli-leo** [comment]
For progress on this issue see the Radarr API v3 project

**Comment by king8084** [comment]
thank the lord there is a progress

pls god let this happen

**Comment by king8084** [comment]
link is broken tho

**Comment by galli-leo** [comment]
Works for me, that’s the wrong project

**Comment by king8084** [comment]
![image](https://user-images.githubusercontent.com/9740702/35876839-a300df76-0b84-11e8-8b1a-733ac5c35541.png)

**Comment by galli-leo** [comment]
Hmm they seem invisible for non Radarr Team members :(

**Comment by euphoria360** [comment]
any updates on this?

**Comment by bonesoul** [comment]
any updates?

**Comment by Qstick** [comment]
In progress

**Comment by immanuelfodor** [comment]
The PR seems to be stuck in Draft state since Oct, please push this feature forward :)

**Comment by Qstick** [comment]
It'll go after 3.0.2

**Comment by triksmelb** [comment]
any chance the ratings could be available from various sources i.e. Rotten Tomatoes, IMDB Trakt like they are in the links within each movie?

**Comment by designgears** [comment]
Any chance of this going out soon since 3.0.2 is out now? @Qstick

**Comment by bakerboy448** [comment]
It will go in when it goes in

spamming the issue asking when it'll go in or asking for updates does not make it go in any faster...could be the opposite in fact ;)

**Comment by thracyturnix** [comment]
> 
> 
> It will go in when it goes in
> 
> spamming the issue asking when it'll go in or asking for updates does not make it go in any faster...could be the opposite in fact ;)

Theres no need to be snarky with them. A single bump is hardly spamming.

**Comment by designgears** [comment]
> It will go in when it goes in
> 
> spamming the issue asking when it'll go in or asking for updates does not make it go in any faster...could be the opposite in fact ;)
> 
> edit:
> a single bump no; but numerous and repeated bumps over the life of the issue is a problem

Yeah, no response would be better than lashing out. Deleting the offending comments and locking the thread outside of contributors with a non-hostile note would be a better approach. 👍

**Comment by Qstick** [comment]
> Any chance of this going out soon since 3.0.2 is out now? @Qstick 

It shouldn't be long after 3.1 goes to master. It's on the short list after that

**Comment by eevlogiev** [comment]
@Qstick ,
where can I find the IMDB rating on the new ver 4.0? I see only TMDB one showing by default:
<img width="1326" alt="Screenshot 2022-01-31 at 12 09 32" src="https://user-images.githubusercontent.com/27862102/151774952-d6ebe74a-9821-490a-bea2-4df9b50b30de.png">


Thanks!

**Comment by Nakda** [comment]
> @Qstick , where can I find the IMDB rating on the new ver 4.0? I see only TMDB one showing by default: <img alt="Screenshot 2022-01-31 at 12 09 32" width="1326" src="https://user-images.githubusercontent.com/27862102/151774952-d6ebe74a-9821-490a-bea2-4df9b50b30de.png">
> 
> Thanks!

I also though it was a setting somewhere to switch to Imdb, but it turns out all rating sources are enabled. You just need to hit the "Refresh & Scan" button from a movie page, or "Refresh all" from the movies list, so Radarr can fetch the ratings.

**Comment by eevlogiev** [comment]
@Nakda, that worked. Also when adding new movie, it's getting all 3 rating sources visualised properly. Thanks for hint!

@Qstick, 
great job here. Thanks a tone!

**Comment by Nakda** [comment]
> @Nakda, that worked. Also when adding new movie, it's getting all 3 rating sources visualised properly. Thanks for the hint!
> 
> @Qstick, great job here. Thanks a tone!

Yeah I guess the default behaviour is to fetch all ratings, but you need to manually update the info for movies that were added prior to the update.

**Comment by bakerboy448** [comment]
The next scheduled refresh after the update will update the ratings as well.

The metadata cache should be more or less cleared at this point, so the only movies that wouldn't have IMDb ratings showing at this point after a refresh are missing their IMDb Id on TMDb. After adding the Id to the entry on TMDb, a refresh of the movie in Radarr should take care of it.

**Comment by euphoria360** [comment]
How these IMDB ratings reflect on Kodi metadata's saved by Radarr as NFO files?

Will IMDB ratings get saved there too?

**Comment by bakerboy448** [comment]
the XMBC provider will use both

the MediaBrowser provider will only use TMDb

**Comment by Paelsmoessan** [comment]
I know this issue is now closed but it would be awesome if there was a checkbox in the metadata section to select IMDB-ratings as default. This way Kodi will present them in the skin without hassle. 

```
  <ratings>
    <rating name="themoviedb" max="10">
      <value>5.8</value>
      <votes>2279</votes>
    </rating>
    <rating name="imdb" max="10" _**default="true"**_>
      <value>5.7</value>
      <votes>53097</votes>
    </rating>
  </ratings>
```
