### ISSUE TITLE
Do not re-download a deleted file

### ISSUE THREAD

**Issue by pven** [Radarr/Radarr#2116]
When I delete a file manually in a directory that is maintained by Sonarr I see  'Sonarr was unable to find the file on disk so it was removed' in activity and it will not re-download the file. When I do the same for Radarr it says the file is missing and will re-download it.

Is it possible to prevent this re-downloading in Radarr?

**Comment by KBlixt** [comment]
just go to history and press "x" on the most resent grab.

**Comment by pven** [comment]
Most of the times I am too late to click the 'x' and the film is back again on my disk.

**Comment by sicusr** [comment]
i would like to know if this is possible too

**Comment by galli-leo** [comment]
There is a setting that will unmonitor movies when Radarr detects a deleted file. Check that.

**Comment by pven** [comment]
I don't want to unmonitor it, I want to delete it automatcally in Radarr.

**Comment by galli-leo** [comment]
But if it’s monitored it will get downloaded again.
