### ISSUE TITLE
API Minimum Availability default value

### ISSUE THREAD

**Issue by Ginotuch** [Radarr/Radarr#2117]
**Description:**
Sorry if this has already been suggested, I searched and could not find a similar github issue.

Can we please set a default value for minimum availability on API requests as programs such as Ombi (Plex requests) do not allow you to configure this, and with Ombi there is no update in the near future as they're rebuilding the entire program from scratch.

This has caused a lot of fakes to be downloaded for popular movies which have not yet been released in theaters or DVD/web.

If this feature is already implemented please direct me as to where, as the only place I can see something like this is on the lists page.

**Radarr Version:** 0.2.0.859

[AB#857](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/857)

**Comment by geogolem** [comment]
@Ginotuch What value would you like to be the default? I am thinking RELEASED, or PreDB (mosly same as RELEASED)

**Comment by austinwbest** [comment]
Pretty sure predb was removed in v3

**Comment by bakerboy448** [comment]
> Pretty sure predb was removed in v3

it still exists in the GUI...probably needs to be replaced/updated?
![image](https://user-images.githubusercontent.com/55419169/91497056-de3aa800-e882-11ea-9a1e-d3f3d8e3b651.png)

**Comment by geogolem** [comment]
ok good to know - i will look into cleaning that up too, but, I guess Released should be the default for the API?

**Comment by bakerboy448** [comment]
that would seem reasonable to me

**Comment by austinwbest** [comment]
> > Pretty sure predb was removed in v3
> 
> it still exists in the GUI...probably needs to be replaced/updated?
> ![image](https://user-images.githubusercontent.com/55419169/91497056-de3aa800-e882-11ea-9a1e-d3f3d8e3b651.png)
> 

Residual, pretty sure.

**Comment by austinwbest** [comment]
> ok good to know - i will look into cleaning that up too, but, I guess Released should be the default for the API?

That would make most sense, yes.

**Comment by Ginotuch** [comment]
> ok good to know - i will look into cleaning that up too, but, I guess Released should be the default for the API?

I agree released should be default, otherwise predb can get you a lot of fakes if you don't use private trackers (at least that's how it used to be, haven't looked into it much as of late). I made this issue 3 years ago and to be honest haven't had many fakes since then and not really sure how it currently works with Ombi.

**Comment by geogolem** [comment]
I will remove preDB and change the default to released

**Comment by bakerboy448** [comment]
preDB removed in https://github.com/Radarr/Radarr/commit/4d2a311e40d84ba6bf55130bfb6552a797912616
