### ISSUE TITLE
Sort search results by peers

### ISSUE THREAD

**Issue by rourke** [Radarr/Radarr#2118]
I want to suggest an improvement: sort search results by peers, or improve the auto-search prioritisation.

I don't fully understand the auto-search prioritisation but it's doing a bad job in my opinion. Most of the time I see a couple of non-rejected search results but the one with a worse seeders/leechers ratio gets priority. So I just sort by peers and get the top one that has no rejection.

This can also be applied to Sonarr by the way.

**Comment by gobanana66** [comment]
Agree with this. It's especially an issue in Radarr when trying to get older movies. It seems to keep picking a result with less than optimal peers, which leads to a hung download. Meanwhile, doing a manual search and selecting the highest seeded result gives me a quick download.

**Comment by galli-leo** [comment]
This will probably be implemented across all tables when we do a new ui. So the sorting option you choose for every table will be remembered for that table (same goes for filtering)

@fedoranimus What do you think?

**Comment by rourke** [comment]
A great example is Dawn of the Planet of the Apes (2014). I even have "Sparks" in my Preferred Tags in the profile.

![image](https://user-images.githubusercontent.com/2820753/32021773-ab08a5ca-b9d4-11e7-8f6f-936e31123afc.png)

**Comment by galli-leo** [comment]
@rourke That's because PROPER will always be above other releases of the same quality.

**Comment by rourke** [comment]
Ah I see. Is there a way to disable that? I don't see why it should do that with movies. Especially since the Sparks release is newer.

**Comment by rourke** [comment]
I think this is probably a good example then. The Amiable release has better Seeders/Peers ratio.

![image](https://user-images.githubusercontent.com/2820753/32078622-dc4e2f28-baa7-11e7-9e6d-728ec9d86833.png)

**Comment by rourke** [comment]
It still doesn't sort the way I prefer it, or save it the way I want it. I usually sort by size and pick the one that meets my size requirements and has the best seeder/peers ratio.

**Comment by cmeyertons** [comment]
It would be great if this mimicked behavior of sites like TPB -- sorted by seeds.

**Comment by mattpurnell** [comment]
i 100% agree, EVERY time I do a search I have to click the seeds twice, as the first time it is in ascending order :)
