### ISSUE TITLE
unable to delete movie from movielist.

### ISSUE THREAD

**Issue by KBlixt** [Radarr/Radarr#2122]
so I'm trying to delete "the hunger games" from my list. it dosen't have a movie folder/file yet and should be to problem to delete. but when check its box in movie editor and i cklick delete selected nothing happens. also when i check its box I cant interact with the toolbar in the lower part of the screen as if haven't got anything selected. if i add another movie then the toolbar works again. 
furthermore, If i go to the movie page i get an 404 response. if i go to the "wanted section" I can see it listed there since it haven't got a movie file yet even though it should be deleted.

If i try to add the movie I get the "+" sign beside the movie as if it's possible to add it but when i click it I get "This movie has already been added" in red a red box above the search results.

I have no clue what's going on so I asume it's a rare bug.

**Versions:**
radarr: 0.2.0.852
ubuntu: 16.04
mono: 5.2.0.215 (tarball Mon Aug 14 15:50:54 UTC 2017)

**Logs:**
I get this in the logs whenever i click to add the movie:
Invalid request Validation failed: 
 -- This movie has already been added

(I've got to admit, the name is nice)

Now, I have a few suspicions on what could have caused this peculiar situation: a few days ago i relocated all my drives because I needed to reorganize my media. so in doing that I changed the root folder file for each movie obviously and mostly it worked well. but apparently not for this movie. I'm not sure if it was there before the "move" or appeared after but that's all "unusual" activity I've been doing that I'm aware of.

**Comment by EddiaYauMean** [comment]
Hi,

Just wanted to confirm that I am seeing the same issue.

Same error message in the log but unlike above I have not moved/changed my storage location or mount points.

I have had the movies in the past and deleted them a while back but have re-added for 4k which does save in to a different root folder to before.

2 of the 3 files I am trying to import were in my autoimport block list but have been removed and symptoms persist.

Version
0.2.0.852
Mono Version
5.0.0 (Stable 5.0.0.100/9667aa6 Wed Jul 12 17:00:30 UTC 2017)

Thanks, Bob.

**Comment by KBlixt** [comment]
the issue seems to sort itself out after a long time or a system reset, unsure of which. the issue with the original movie was fixed by not doing anything although I've had similar issues with other movies. maybe it have something to do with re adding a movie that have been deleted from the library previously or shortly before re adding it.

**Comment by galli-leo** [comment]
This is fixed on the latest develop release.
