### ISSUE TITLE
Radar downloading movies that exists in other directories 

### ISSUE THREAD

**Issue by bhelgeson** [Radarr/Radarr#2123]
**Description:**

Check first that your problem is not listed in our wiki section:
* https://github.com/Radarr/Radarr/wiki/Common-Problems
* https://github.com/Radarr/Radarr/wiki/FAQ

Provide a description of the feature request or bug here, the more details the better. 
Please also try to include the following if you are reporting a bug

**Radarr Version:**

Version
0.2.0.852
Mono Version
4.6.2 (Stable 4.6.2.7/08fd525 Wed Dec 7 20:01:26 CET 2016)
AppData directory
/usr/local/radarr/var/.config/Radarr
Startup directory
/volume1/@appstore/radarr/share/Radarr

Synology 1815+

Movies that were imported from subdirectories all of a sudden are being downloaded again creating duplicates.

**Comment by galli-leo** [comment]
1. Does Radarr know about these movies?
2. Are these better quality ones?
