### ISSUE TITLE
Load Times For Massive Libraries

### ISSUE THREAD

**Issue by Chas3down** [Radarr/Radarr#2124]
So, when I load up radarr, it takes over 10 minutes before I am able to search my library, because it takes so long for all the movies to be cached in.  (Over 8000 movies).  I know this is in an insane amount, but it's getting to the point where radarr is becoming next to unusable.  I know making radarr work better with big libraries was on the to do list, just wondering if there is any progress there?

**Comment by hotio** [comment]
progress? no

work around, remove "cutoff met" movies from radarr

**Comment by galli-leo** [comment]
Have you tried using paging? Also are you connecting to radarr on localhost or via a remote client?

**Comment by Chas3down** [comment]
@galli-leo I do use paging, however, I can't pay through 8000 movies, my only option is the search bar, and that is what takes forever to load.  (All the search drop downs / etc, don't load for like 10 minutes)  I am using a remote client, but it is not the issue.  I have a 10gbps business line and it is being hosted on a very expensive 10gbps dedicated server, both have plenty of hardware, so that's not the issue.

@hotio Thanks for the suggestion, but if I remove cutoff met movies from radarr, and I import a new list, I have to do the same thing over and over.  Basically, all I do is add massive movie lists and hope some movies pop in that I don't already have.  If I remove cuttoff met movies, this would cause movies I already own to be added from the new list and redownloaded.

**Comment by galli-leo** [comment]
Hmm. It shouldn't take 10 minutes to load 8000 movies, especially with a 10GBPS line. Can you try loading Radarr on localhost? Also would you be willing to share your Radarr db with me on discord? That would make it much easier for me to profile such issues (I already have a suspicion what the culprit might be.

**Comment by galli-leo** [comment]
@Chas3down So the latest nightly should have some improvements for large library loading. Can you try it out and report back?

**Comment by dany20mh** [comment]
@galli-leo I tried to run the source for macOS but I couldn't figure it out how, do you mind helping me on this ?

**Comment by dany20mh** [comment]
@galli-leo 
So adding still take long time, if I select in the list for example to add 100 movie (out of 8000) that I have, it will download 40Mb or so of each file one by one in each folder and it take very long time to bring the list backup again.

If there was an option for example you could add your folder (main folder) and desired quality and it scan and add each of them automatically and not you select them one by one.

**Comment by galli-leo** [comment]
@dany20mh Sorry for the late response. Adding existing movies is a different issue, so closing this one.
