### ISSUE TITLE
Don't move even when uTorrent isn't seeding

### ISSUE THREAD

**Issue by primaeval** [Radarr/Radarr#2126]
"Use Hardlinks instead of Copy" just moves the file for me on Win7 64bit, same volume, ntfs.

"Completed Download Handling" is enabled. "remove" is off.

**Comment by djzeratul** [comment]
Are you sure it isnt making hardlinks? A hardlink would appear to be a copy of a file to windows explorer unless you use the following command and it returns multiple paths for the file:

`fsutil.exe hardlink list c:\path\to\movie.mkv`

**Comment by primaeval** [comment]
fsutil just shows the original path in the list.
Sickrage makes hardlinks ok on the same machine. There are two paths in the fsutil hardlink list.

**Comment by primaeval** [comment]
I can get it to work now if either I turn on Debug logging or set uTorrent to continue seeding. I had uTorrent to stop immediately after download so I can manually Force Start. I'm using the latest uTorrent and connecting directly, not blackhole.

Is there a check to see if seeding is Finished before it chooses to do a Hardlink or Move?

**Comment by Dnkhatri** [comment]
From what I have experienced this is how the feature works radarr\sonarr hard-links the file if the torrent is still being seeded otherwise it moves it.

**Comment by primaeval** [comment]
I'd really like it to not do that if possible so I can restart the torrents I'm obliged to keep seeding.
