### ISSUE TITLE
Unable to map existing movies with periods in their titles

### ISSUE THREAD

**Issue by pproba** [Radarr/Radarr#2129]
I'm having trouble with some of my movies not being imported. After looking for a pattern I've noticed one: whenever one of my movies has a period in its name (e.g. "The Man from U.N.C.L.E" or "Stirb langsam 4.0" - the German version of "Live Free or Die Hard") it's being found and analyzed but can't be mapped to a movie on themoviedb.

Example:
D:\MOVIES\The Man from U.N.C.L.E. (2015)\The.Man.from.U.N.C.L.E..(2015).Bluray-1080p.mkv

The log entries for this during the bulk import are:

> 17-10-1 01:29:19.3|Debug|Parser|Parsing string 'The Man from U.N.C.L.E. (2015)'
17-10-1 01:29:19.3|Trace|Parser|^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(19|20)\d{2}(?!p|i|(19|20)\d{2}|\]|\W(19|20)\d{2})))+(\W+|_|$)(?!\\)
17-10-1 01:29:19.3|Debug|Parser|Movie Parsed. The Man from U N.C.L.E. - 2015 
17-10-1 01:29:19.3|Debug|Parser|Language parsed: English
17-10-1 01:29:19.3|Debug|QualityParser|Trying to parse quality for The Man from U.N.C.L.E. (2015)
17-10-1 01:29:19.3|Debug|Parser|Quality parsed: Unknown v1
17-10-1 01:29:19.3|Debug|Parser|Release Group parsed: 
17-10-1 01:29:19.3|Debug|DiskScanService|Scanning 'D:\MOVIES\The Man from U.N.C.L.E. (2015)' for video files
17-10-1 01:29:19.3|Debug|DiskScanService|1 video files were found in D:\MOVIES\The Man from U.N.C.L.E. (2015)
17-10-1 01:29:19.3|Debug|ImportDecisionMaker|Analyzing 1/1 files.
17-10-1 01:29:19.3|Debug|Parser|Parsing string 'The.Man.from.U.N.C.L.E..(2015).Bluray-1080p.mkv'
17-10-1 01:29:19.3|Trace|Parser|^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(19|20)\d{2}(?!p|i|(19|20)\d{2}|\]|\W(19|20)\d{2})))+(\W+|_|$)(?!\\)
17-10-1 01:29:19.3|Debug|Parser|Movie Parsed. The Man from U.N.C.L.E. - 2015 
17-10-1 01:29:19.3|Debug|Parser|Language parsed: English
17-10-1 01:29:19.3|Debug|QualityParser|Trying to parse quality for The.Man.from.U.N.C.L.E..(2015).Bluray-1080p.mkv
17-10-1 01:29:19.3|Debug|Parser|Quality parsed: Bluray-1080p v1
17-10-1 01:29:19.3|Debug|Parser|Release Group parsed: 
17-10-1 01:29:19.3|Debug|ImportDecisionMaker|Size: 8206928701
17-10-1 01:29:19.3|Debug|VideoFileInfoReader|Getting media info from D:\MOVIES\The Man from U.N.C.L.E. (2015)\The.Man.from.U.N.C.L.E..(2015).Bluray-1080p.mkv
17-10-1 01:29:19.3|Trace|MediaInfo|Read file offset 0-49152 (49152 bytes)
17-10-1 01:29:19.3|Trace|MediaInfo|Read file offset 8206883560-8206899944 (16384 bytes)
17-10-1 01:29:19.3|Trace|MediaInfo|Read a total of 65536 bytes (0,0%)
17-10-1 01:29:19.3|Debug|ImportDecisionMaker|Checking quality for this video file to make sure nothing mismatched.
17-10-1 01:29:19.3|Trace|ConfigService|Using default config value for 'skipfreespacecheckwhenimporting' defaultValue:'False'
17-10-1 01:29:19.3|Debug|FreeSpaceSpecification|Skipping free space check for existing episode
17-10-1 01:29:19.3|Debug|VideoFileInfoReader|Getting media info from D:\MOVIES\The Man from U.N.C.L.E. (2015)\The.Man.from.U.N.C.L.E..(2015).Bluray-1080p.mkv
17-10-1 01:29:19.3|Trace|MediaInfo|Read file offset 0-49152 (49152 bytes)
17-10-1 01:29:19.3|Trace|MediaInfo|Read file offset 8206883560-8206899944 (16384 bytes)
17-10-1 01:29:19.3|Trace|MediaInfo|Read a total of 65536 bytes (0,0%)
17-10-1 01:29:19.3|Debug|DetectSample|Runtime is over 90 seconds
17-10-1 01:29:19.3|Debug|NotUnpackingSpecification|D:\MOVIES\The Man from U.N.C.L.E. (2015)\The.Man.from.U.N.C.L.E..(2015).Bluray-1080p.mkv is in series folder, skipping unpacking check
17-10-1 01:29:19.3|Debug|Parser|Parsing string 'The Man from U N.C.L.E. 2015'
17-10-1 01:29:19.3|Trace|Parser|^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(19|20)\d{2}(?!p|i|(19|20)\d{2}|\]|\W(19|20)\d{2})))+(\W+|_|$)(?!\\)
17-10-1 01:29:19.3|Debug|Parser|Movie Parsed. The Man from U N C.L.E. - 2015 
17-10-1 01:29:19.3|Debug|Parser|Language parsed: English
17-10-1 01:29:19.3|Debug|QualityParser|Trying to parse quality for The Man from U N.C.L.E. 2015
17-10-1 01:29:19.3|Debug|Parser|Quality parsed: Unknown v1
17-10-1 01:29:19.3|Debug|Parser|Release Group parsed: 
17-10-1 01:29:19.3|Trace|HttpClient|Req: [GET] https://api.themoviedb.org/3/search/movie?api_key=1a7373301961d03f97f853a876dd1212&query=the%2Bman%2Bfrom%2Bu%2Bn%2Bc%2Bl%2Be%2B&year=2015&include_adult=False
17-10-1 01:29:19.3|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
17-10-1 01:29:19.7|Trace|HttpClient|Res: [GET] https://api.themoviedb.org/3/search/movie?api_key=1a7373301961d03f97f853a876dd1212&query=the%2Bman%2Bfrom%2Bu%2Bn%2Bc%2Bl%2Be%2B&year=2015&include_adult=False: 200.OK (363 ms)
17-10-1 01:29:19.7|Warn|SkyHookProxy|Couldn't map movie The Man from U N.C.L.E. to a movie on The Movie DB. It will not be added :(

Allow me to analyze:
First part of the problem is within the parsed movie name: 
"17-10-1 01:29:19.3|Debug|Parser|Movie Parsed. The Man from U N C.L.E. - 2015". 
Notice the replaced periods in "U.N.C.L.E.".

The second part of the problem is the request to themoviedb, which is:
"the+man+from+u+n+c+l+e+" (the%2Bman%2Bfrom%2Bu%2Bn%2Bc%2Bl%2Be%2B)
instead of:
"the+man+from+u.n.c.l.e." (the%2Bman%2Bfrom%2Bu%2En%2Ec%2El%2Ee%2E)

If you replace the queries as suggested above, there is a match on themoviedb.

The same is true for "Stirb langsam 4.0 (2007)" which is parsed as "Stirb Langsam 4 0 - 2007" and the query is "stirb%2Blangsam%2B4%2B0" returning no matches.

I've already tried disabling "Replace Illegal Characters" without success.

**Radarr Version: 0.2.0.852
**OS: Windows 10 Pro 64bit

If you need any additional information, please let me know.

**Comment by pproba** [comment]
Could someone please confirm that this is a bug and that I'm not the only one with these problems?

**Comment by hotio** [comment]
I'm not able to replicate this...works just fine for me.

```
17-11-19 15:05:59.7|Debug|Parser|Parsing string 'The Man from U.N.C.L.E. (2015)'
17-11-19 15:05:59.7|Trace|Parser|^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(19|20)\d{2}(?!p|i|(19|20)\d{2}|\]|\W(19|20)\d{2})))+(\W+|_|$)(?!\\)
17-11-19 15:05:59.7|Debug|Parser|Movie Parsed. The Man from U N.C.L.E. - 2015 
17-11-19 15:05:59.7|Debug|Parser|Language parsed: English
17-11-19 15:05:59.7|Debug|QualityParser|Trying to parse quality for The Man from U.N.C.L.E. (2015)
17-11-19 15:05:59.7|Debug|Parser|Quality parsed: Unknown v1
17-11-19 15:05:59.7|Debug|Parser|Release Group parsed: 
17-11-19 15:05:59.7|Debug|DiskScanService|Scanning '/storage/movies/The Man from U.N.C.L.E. (2015)' for video files
17-11-19 15:05:59.7|Debug|DiskScanService|1 video files were found in /storage/movies/The Man from U.N.C.L.E. (2015)
17-11-19 15:05:59.7|Debug|ImportDecisionMaker|Analyzing 1/1 files.
17-11-19 15:05:59.7|Trace|ConfigService|Using default config value for 'parsingleniency' defaultValue:'Strict'
17-11-19 15:05:59.7|Debug|Parser|Parsing string 'The.Man.from.U.N.C.L.E..(2015).Bluray-1080p.mkv'
17-11-19 15:05:59.8|Trace|Parser|^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(19|20)\d{2}(?!p|i|(19|20)\d{2}|\]|\W(19|20)\d{2})))+(\W+|_|$)(?!\\)
17-11-19 15:05:59.8|Debug|Parser|Movie Parsed. The Man from U.N.C.L.E. - 2015 
17-11-19 15:05:59.8|Debug|Parser|Language parsed: English
17-11-19 15:05:59.8|Debug|QualityParser|Trying to parse quality for The.Man.from.U.N.C.L.E..(2015).Bluray-1080p.mkv
17-11-19 15:05:59.8|Debug|Parser|Quality parsed: Bluray-1080p v1
17-11-19 15:05:59.8|Debug|Parser|Release Group parsed: 
17-11-19 15:05:59.8|Debug|ImportDecisionMaker|Size: 15972462338
17-11-19 15:05:59.8|Debug|VideoFileInfoReader|Getting media info from /storage/movies/The Man from U.N.C.L.E. (2015)/The.Man.from.U.N.C.L.E..(2015).Bluray-1080p.mkv
17-11-19 15:05:59.8|Trace|MediaInfo|Read file offset 0-376832 (376832 bytes)
17-11-19 15:05:59.8|Trace|MediaInfo|Read file offset 15972218581-15972234965 (16384 bytes)
17-11-19 15:05:59.8|Trace|MediaInfo|Read file offset 15972459043-15972462338 (3295 bytes)
17-11-19 15:05:59.8|Trace|MediaInfo|Read a total of 396511 bytes (0.0%)
17-11-19 15:05:59.8|Debug|ImportDecisionMaker|Checking quality for this video file to make sure nothing mismatched.
17-11-19 15:05:59.8|Trace|ConfigService|Using default config value for 'skipfreespacecheckwhenimporting' defaultValue:'False'
17-11-19 15:05:59.8|Debug|FreeSpaceSpecification|Skipping free space check for existing episode
17-11-19 15:05:59.8|Debug|VideoFileInfoReader|Getting media info from /storage/movies/The Man from U.N.C.L.E. (2015)/The.Man.from.U.N.C.L.E..(2015).Bluray-1080p.mkv
17-11-19 15:05:59.8|Trace|MediaInfo|Read file offset 0-376832 (376832 bytes)
17-11-19 15:05:59.8|Trace|MediaInfo|Read file offset 15972218581-15972234965 (16384 bytes)
17-11-19 15:05:59.8|Trace|MediaInfo|Read file offset 15972459043-15972462338 (3295 bytes)
17-11-19 15:05:59.8|Trace|MediaInfo|Read a total of 396511 bytes (0.0%)
17-11-19 15:05:59.8|Debug|DetectSample|Runtime is over 90 seconds
17-11-19 15:05:59.8|Debug|NotUnpackingSpecification|/storage/movies/The Man from U.N.C.L.E. (2015)/The.Man.from.U.N.C.L.E..(2015).Bluray-1080p.mkv is in series folder, skipping unpacking check
17-11-19 15:05:59.8|Debug|Parser|Parsing string 'The Man from U N.C.L.E. 2015'
17-11-19 15:05:59.8|Trace|Parser|^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(19|20)\d{2}(?!p|i|(19|20)\d{2}|\]|\W(19|20)\d{2})))+(\W+|_|$)(?!\\)
17-11-19 15:05:59.8|Debug|Parser|Movie Parsed. The Man from U N C.L.E. - 2015 
17-11-19 15:05:59.8|Debug|Parser|Language parsed: English
17-11-19 15:05:59.8|Debug|QualityParser|Trying to parse quality for The Man from U N.C.L.E. 2015
17-11-19 15:05:59.8|Debug|Parser|Quality parsed: Unknown v1
17-11-19 15:05:59.8|Debug|Parser|Release Group parsed: 
17-11-19 15:05:59.8|Trace|HttpClient|Req: [GET] https://api.themoviedb.org/3/search/movie?api_key=1a7373301961d03f97f853a876dd1212&query=the%2Bman%2Bfrom%2Bu%2Bn%2Bc%2Bl%2Be%2B&year=2015&include_adult=False
17-11-19 15:06:00.3|Trace|HttpClient|Res: [GET] https://api.themoviedb.org/3/search/movie?api_key=1a7373301961d03f97f853a876dd1212&query=the%2Bman%2Bfrom%2Bu%2Bn%2Bc%2Bl%2Be%2B&year=2015&include_adult=False: 200.OK (494 ms)

```

**Comment by pproba** [comment]
Thanks @hotio for trying this.
Miraculously, I was able to import The man from U.N.C.L.E. today.
I still have remaining issues with "G.I. Joe - Die Abrechnung (2013)\G.I.Joe.-.Die.Abrechnung.(2013).Bluray-1080p".
I've tried strict and lenient parsing, but I can't get it to be parsed correctly during bulk import.

However, if I manually add this movie and scan the disk, it's getting picked up. I've tried renaming (or 'organizing') it then, but there were no changes to the file or directory name, so it seems to already be to Radarr's liking.
Removing the movie from Radarr again and trying to bulk import once more leads to the same result, it won't be picked up.

**Comment by webpeon** [comment]
I am experiencing this same issue with movies with dots or periods in their title name.  I can bulk import all my movies and then use lists to look for what is missing.  Even though Radarr shows I have the move, such as "The man from U.N.C.L.E.", it still adds it to my wanted list and downloads another copy of it, not matching what I already have, even though its identical.   

Does radarr only look at folder/title names when importing? If so, is there a way to have it read the existing .nfo files, and use the TMDB IDs so it ignores all other factors as a first check?
