### ISSUE TITLE
Radarr doesn't track download status

### ISSUE THREAD

**Issue by PotatoQuality** [Radarr/Radarr#2130]
**Description:**

Sonarr is sending the nzb file to sabnzbd, after the download is finished, its look like radarr doesn't tracj monitor the status of the movie.

The activity tab is empty
![image](https://user-images.githubusercontent.com/2944704/31050676-5d2700bc-a652-11e7-889e-496b8ea5fbd2.png)

In the overview page, its give the status "sending to download client"

![image](https://user-images.githubusercontent.com/2944704/31050691-e85322c4-a652-11e7-837e-1ab431a03e56.png)

I have this problem only with this movie:
Harry.Potter.8.and.the.Deathly.Hallows.Part.2.2011

Check first that your problem is not listed in our wiki section:
* https://github.com/Radarr/Radarr/wiki/Common-Problems
* https://github.com/Radarr/Radarr/wiki/FAQ

Provide a description of the feature request or bug here, the more details the better. 
Please also try to include the following if you are reporting a bug

**Radarr Version:**

2.0.0.4949

**Logs:**

https://pastebin.com/gxAdPRzS

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by Paradoxx2015** [comment]
I also have this Issue now with the 0.2.0.870 version on synologyNAS. The previous version worked fine, but not the "Activity" is emty, but NZBget downloads the file correct.

**Comment by galli-leo** [comment]
This is because the Release Title is not a known AKA for the movie.
