### ISSUE TITLE
Errors in MediaCoverService choking Radarr 

### ISSUE THREAD

**Issue by isaacag** [Radarr/Radarr#2132]
I've been having issues for a couple of weeks with Radarr. Suddenly out of nowhere while running on the background the service starts choking the CPU, the logs show endless recent entries like this:

```
MediaCoverService | Couldn't download media cover for [tt5580390] The underlying connection was closed: The connection was closed unexpectedly.: The underlying connection was closed: The connection was closed unexpectedly.
MediaCoverService | Retrying for the 1. time in ten seconds. 
MediaCoverService | Couldn't download media cover for [tt2345759] The underlying connection was closed: The connection was closed unexpectedly.: The underlying connection was closed: The connection was closed unexpectedly. 
MediaCoverService | Retrying for the 1. time in ten seconds.
MediaCoverService | Retrying for the 1. time in ten seconds.
MediaCoverService | Retrying for the 1. time in ten seconds.
MediaCoverService | Retrying for the 1. time in ten seconds.
```
Repeats this for most movies in the Library filling entire logs. The only way to make it stop is to restart the service, but a few hours later the problem returns until service is killed. Is this a bug?

Version
0.2.0.852

**Comment by hotio** [comment]
Do not think it is a bug, rather a problem with your system, connection or on the remote.

**Comment by alex-w-k** [comment]
I had this problem as well. I had to restart radarr to get it to work again. It almost seems like rate limiting from tmdb? This happened when I tried to import about 1k movies

**Comment by galli-leo** [comment]
There is error handling in this process, hence the "Retrying for the 1. time in ten seconds" message.

Regarding op. This seems an issue with your installation (The underlying connection was closed). This could be an issue with your version of mono or libcurl. What version of those do you have installed?

**Comment by isaacag** [comment]
Curl 1.0.6462.25311
Mono 0.0.0.0 (??)
I'm also inclining for the TMDb explanation since this behavior has not been repeated in a couple of days. However, Radarr should handle this better instead of just falling in a loop of endless errors.

**Comment by galli-leo** [comment]
Rate limiting on TMDB is also respected in Radarr. Furthermore, we do not do an endless loop after 5 retries we just "give up". Regarding the mono version, is that what Radarr reports?
