### ISSUE TITLE
Radarr seeing 4K bluray as 720p Bluray

### ISSUE THREAD

**Issue by lordhippos** [Radarr/Radarr#2134]
On Radarr version 0.2.0.852.

The search name parser sees this as a 720p Bluray release for some reason!

Movie.Name.Year.Version.UHD.BluRay.HDR.x265.Atmos.Eng.De-RLSGRP

Where Version = "Extended" or "DC" or similar.

**Comment by hotio** [comment]
Try adding 2160p

**Comment by lordhippos** [comment]
Hi, thanks for the response, but it's a search result term I don't have any control over the label it has. For file name parsing on a manual import or something that would probably work though.
