### ISSUE TITLE
HDBits require internal not working

### ISSUE THREAD

**Issue by jaydee99** [Radarr/Radarr#2136]
**Description:**

Hi,

I'd like to use the "Require internal" feature on HDBits but it doesn't seem to work as intended.

I checked both "Prefer internal" and "Require internal" on HDBits indexer settings. It still grabs non internal releases. And when i do a manual search, non internal releases are not rejected.

Is there any way to fix this please ?

Thanx !

**Radarr Version:**
0.2.0.860

**Logs:**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by tsubus** [comment]
I thought that was intended behavior, it enforces internal releases only on new releases grepped from RSS, otherwise it doesn't. I modified it locally, if you're interested. Just cherry-pick this commit: https://github.com/tsubus/Radarr/commit/ab0b40022d232440bcb3ecad4b4aee75e1eb04aa

**Comment by galli-leo** [comment]
Yeah require internal is only for RSS, since you still want to see them in manual search. However, this feature is kinda deprecated and will be replaced soon ™️
