### ISSUE TITLE
Trak List Path not editable

### ISSUE THREAD

**Issue by sideoutdude16** [Radarr/Radarr#2139]
i'm not able to select or edit folder path on all lists.

<img width="2560" alt="untitled" src="https://user-images.githubusercontent.com/4198697/31189121-5cd6433a-a8f4-11e7-8db4-f7926f3c3e3f.png">

**Radarr Version: 0.2.0.852**

**17-10-4 10:53:03.4|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Unable to connect to list, check the log for more details
17-10-4 10:55:42.4|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Invalid Path
17-10-4 10:55:43.0|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Invalid Path
17-10-4 10:58:10.3|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Invalid Path
17-10-4 10:58:12.3|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Invalid Path

**Comment by sideoutdude16** [comment]
i checked and i was able to see those files in the /UI/Content/Fonts/ where the log said these files were not found but is listed in the file explorer and terminal. 

**update, it is not just trak.tv but it is happening on each list when asking for path to be added.

**Comment by sideoutdude16** [comment]
looks like it was tied to bug 1420 i think (i closed the link after succeeding the instructions)  it only happens when you have a NEW radarr computer.   you have to add a movie FIRST then the path will show up on all lists now. 

closing ticket

**Comment by ward0** [comment]
@sideoutdude16 So i have to download a manual movie first? and then Radarr will know my paths?

**Comment by sideoutdude16** [comment]
Go to movies and then add a movie then it’ll ask you to save the path.

**Comment by ward0** [comment]
seems like buggy to me...

**Comment by sideoutdude16** [comment]
If it’s buggy then it should be fixed . Maybe add the path in the initial setup then go from there
