### ISSUE TITLE
The movie title "La folle histoire de Max et Léon" is not mapped properly

### ISSUE THREAD

**Issue by ToXinE** [Radarr/Radarr#2142]
This movie is somehow linked to a wrong Movie ("Les têtes de l'emploi"). It should not be mapped to "Les Têtes de l'emploi "

http://www.imdb.com/title/tt5091538/
There is no radarr mapping for this movie on this site https://mappings.radarr.video/movie/445765
nor in radarr
![image](https://user-images.githubusercontent.com/6205053/31226285-cd9e2196-a9d5-11e7-93c2-94c5bac7b1ad.png)

![image](https://user-images.githubusercontent.com/6205053/31226209-956703ec-a9d5-11e7-88ec-7a33a15d5db7.png)

**Radarr Version:**
Radarr Ver. 0.2.0.852
develop
**Logs:**

  | MovieSearchService | Movie search completed. 1 reports downloaded. | 13:23
-- | -- | -- | --
  | DownloadService | Report sent to Sabnzbd. Les.Tetes.De.L.Emploi.2016.FRENCH.720p.BluRay.x264-PKPTRS | 13:23
  | Sabnzbd | Adding report [Les.Tetes.De.L.Emploi.2016.FRENCH.720p.BluRay.x264-PKPTRS] to the queue. | 13:23
  | DownloadDecisionMaker | Processing 10 releases | 13:23
  | NzbSearchService | Searching 2 indexers for [La Folle histoire de Max et Léon] | 13:23

**Comment by galli-leo** [comment]
This is probably because your indexer mistagged the imdbid. Can you confirm that?

**Comment by ToXinE** [comment]
how can i confirm such a thing ?

**Comment by galli-leo** [comment]
Either go to your indexer and look at the release. Most indexers should have an imdb link or imdbid somewhere. You can also ask your indexer staff if that was the case.

**Comment by ToXinE** [comment]
this is a public indexer : https://www.usenet-crawler.com/details/1a50c195540d441f2eb469452aa82a69/La-Folle-Histoire-de-Max-et-L%3Fon-%5B2015%5D
there is no references to imdb or imdbid...

Can i bypass mappings if some mappings are wrong or should i ignore this indexer ?

**Comment by galli-leo** [comment]
Sorry for the late response, you can bypass the mappings, but I would suggest ignoring this indexer if you can.
