### ISSUE TITLE
MacOS: titles with accent or umlaut keep showing up on bulk import

### ISSUE THREAD

**Issue by dkids** [Radarr/Radarr#2145]
**Description:**

All of these movies are available from search.   The movie file is listed as downloaded.   They keep showing up on bulk import.   There are 3 sets: directory first page and second page, plus a different directory.   

This is a headless Mac Mini and I don't know how to do screenshots without using Shift-Command-4.

This is not harmful but it's a little annoying.   Thanks for Radarr!

Disabled movies are possible duplicates. If the match is incorrect, update the Tmdb Id cell to import the proper movie.
        Movie   Path    Tmdb Id Monitor Profile Quality
        Café Society (2016)     /Volumes/PORT4TB/parents/Café Society (2016)
 Café Society (2016) 720p.mp4                           HDTV-720p
        Fotbollskrönikan VM 2010 (2010) /Volumes/PORT4TB/parents/Fotbollskrönikan Vm 2010 (2010)
 Fotbollskrönikan VM 2010 (2010) 352p.mp4                               SDTV
        Joyeux Noël (2005)      /Volumes/PORT4TB/parents/Joyeux Noël (2005)
 Joyeux Noël (2005) 720p.mp4                            HDTV-720p
        Les Misérables (2012)   /Volumes/PORT4TB/parents/Les Misérables (2012)
 Les Misérables (2012) 720p.mp4                         HDTV-720p
        My Dinner with André (1981)     /Volumes/PORT4TB/parents/My Dinner With André (1981)
 My Dinner with André (1981) 720p.mp4                           HDTV-720p

Disabled movies are possible duplicates. If the match is incorrect, update the Tmdb Id cell to import the proper movie.
        Movie   Path    Tmdb Id Monitor Profile Quality
        Pouponnières du IIIe Reich, Les (2013)  /Volumes/PORT4TB/parents/Pouponnières Du Iiie Reich, Les (2013)
 Pouponnières du IIIe Reich, Les (2013) 720p.mp4                                HDTV-720p
        Quimby: Aréna 2011 (2012)       /Volumes/PORT4TB/parents/Quimby - Aréna 2011 (2012)
 Quimby - Aréna 2011 (2012) 272p.mp4                            SDTV
        Suite Française (2014)  /Volumes/PORT4TB/parents/Suite Française (2014)
 Suite Française (2014) 720p.mp4                                HDTV-720p

Disabled movies are possible duplicates. If the match is incorrect, update the Tmdb Id cell to import the proper movie.
        Movie   Path    Tmdb Id Monitor Profile Quality
        Pokémon: Zoroark: Master of Illusions (2010)    /Volumes/PORT4TB/kid_movies/Pokémon - Zoroark - Master Of Illusions (2010)
 Pokémon - Zoroark - Master of Illusions (2010) 400p.mp4                                SDTV

**Radarr Version:**

Version
    0.2.0.852
Mono Version
    5.2.0.224 (d15-3/14f2c81 Thu Aug 24 10:33:52 EDT 2017)

**Logs:**

**Comment by bakerboy448** [comment]
Closing
v0.2 is no longer being actively developed.

If this is still an issue/request on recent v3 builds, please open a new issue.
