### ISSUE TITLE
current release for linux actually downloads a windows version

### ISSUE THREAD

**Issue by brunoamaral** [Radarr/Radarr#2149]
I followed the instructions in the wiki, ran ` 2019  wget $( curl -s https://api.github.com/repos/Radarr/Radarr/releases | grep linux.tar.gz | grep browser_download_url | head -1 | cut -d \" -f 4 )` and the result was a folder with EXE files.

**Comment by galli-leo** [comment]
Yes. Radarr uses mono and thus exe files on linux. Try looking at the installation guide on the wiki.
