### ISSUE TITLE
Not properly grabbing golden popcorns

### ISSUE THREAD

**Issue by alex-w-k** [Radarr/Radarr#2152]
**Description:**

Radarr is not grabbing golden popcorns when told it is required. It grabs the remux instead.

**Radarr Version:**

Radarr Ver. 0.2.0.852

**Logs:**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by galli-leo** [comment]
Known issue with all the Required / Preferred switches. They are kinda deprecated currently and will be soon ™️ replaced by a better system.
