### ISSUE TITLE
Why so much required to add via API

### ISSUE THREAD

**Issue by brimur** [Radarr/Radarr#2155]
Hi, this is more of a curiosity than an issue. In the GUI I can add a movie via the IMDB id, I enter the id in the search box, a single result is returned and I click Add. There will always only be a single result when using the IMDB Id so I was wondering why the API cannot add the same way instead of requiring so many fields? 
It would be great to be able to do something like this with all the defaults...
````
http://server:7878/api/movie/add?imdb=tt12345&apikey=xxxxxxx
````
instead of needing all the following
````
Required:
	title (string)
	qualityProfileId (int)
	titleSlug (string)
	images (array)
	tmdbId (int)
	rootFolderPath (string)

Optional: monitored (bool) addOptions (object)

````

**Comment by galli-leo** [comment]
Images and titleSlug are not needed. The other stuff is just need for Radarr to work correctly, e.g. Quality Profile and The path where to store the movie files. Title (and year!) is needed, because Radarr creates the path when you add the movie, before fetching any info about the movie.
