### ISSUE TITLE
Radarr auto starting downloading.. I don't want that...

### ISSUE THREAD

**Issue by ward0** [Radarr/Radarr#2156]
Can i disable this behavior? I don't want auto downloads.. but like in CP where you can snatch the release you want...

**Comment by Micha3lvd** [comment]
Just set monitor to no, then radarr will not check automatically for (better) versions

**Comment by galli-leo** [comment]
Alternatively you can set the RSS Sync interval to 0.

**Comment by ward0** [comment]
@Micha3lvd , this should do it?:

![image](https://user-images.githubusercontent.com/15545810/31411932-7fd4817a-ae13-11e7-9353-0296f5203ede.png)

@galli-leo Not finding any RSS sync option? Do you mean this option? 'List Update Interval'

**Comment by galli-leo** [comment]
No under Indexers there should be that option. You may have to enable advanced settings.

**Comment by Micha3lvd** [comment]
For single movie disable the monitoring when adding a movie:
![image](https://user-images.githubusercontent.com/1392150/31431698-b5c49ac0-ae74-11e7-8f0d-d2190b3d7241.png)
rss sync for all future movies added edit indexers:
![image](https://user-images.githubusercontent.com/1392150/31431768-ecfe531e-ae74-11e7-95da-cea5587c9c1b.png)

**Comment by ward0** [comment]
Hello @Micha3lvd and @galli-leo 

I tested this many times now..

setting this:

![image](https://user-images.githubusercontent.com/15545810/31568497-f401c4be-b074-11e7-831a-c42bfbc7c62a.png)

will cause me not to get any results in movie > details > search(i should presume that you will see the searched results there..)

when i set Monitored to YES > Radarr will start an auto download = i don't want that!!!

I have these indexer options as adviced:

![image](https://user-images.githubusercontent.com/15545810/31568571-5c5f3988-b075-11e7-8fdc-de9509e7bb7b.png)

should i set RSS sync to 0?:

![image](https://user-images.githubusercontent.com/15545810/31568578-69818152-b075-11e7-80f3-7f155c00eb5a.png)

it should be not so hard not to auto download torrents right???...

**Comment by ward0** [comment]
ok so un update > when going trough wanted > search all.. Radarr doesn't care about my non monitored status.. it will just send a torrent to the downloader :( :( I just want it to search my torrents and show it to me in movies > movie details > search.

that search list should be updated with results from the auto search or when you manual search for a movie. 

Now to accomplish my goal i would have to manually search movie by movie and then go into search details of that movie to see the torrent Radarr has found...


@galli-leo any toughts about that pls?

**Comment by FlyingPersian** [comment]
Any news on that? I also prefer to have it just search automatically and show me the options to download, but don't download automatically. Just like in CP,
