### ISSUE TITLE
Dont use pageSize=-1 on Manual Import

### ISSUE THREAD

**Issue by EnorMOZ** [Radarr/Radarr#2160]
**Description:**
When you try to manually import a movie and you type in the name of the movie nothing changes in the movie list to select the movie to import as.
Manual Import - Select Movie list 

pageSize=-1 is being used

When setting pageSize=10 or any other number than -1 proper results are returned.

**Radarr Version:**

Radarr Ver. 0.2.0.871

**Logs:**

17-10-10 10:53:43.3|Debug|Api|[GET] /api/movie?page=1&pageSize=-1&sortKey=sortTitle&sortDir=asc&filterKey=title&filterValue=Cube&filterType=contains: 200.OK (890 ms)

**Comment by EnorMOZ** [comment]
Not sure if it was clear or not but this basically does not allow an user to manual import movies. So manual import currently is broken. Wonder if this is more of an issue with folks with large movie libraries.

**Comment by weirdcrap** [comment]
I have noticed this issue as well. Since the list doesn't auto narrow shrink based on what you have typed I have been using Ctrl+F in my browser to search for the movie I want in the manual import list. Then I can select it and begin the import as normal.

**Comment by EnorMOZ** [comment]
Unfortunately at times the movies are not even listed for me even though they are in the main movie list.

**Comment by weirdcrap** [comment]
Curious, how large is your library exactly? I have not experienced the movie list not populating yet and my library is just a few hundred shy of 3,000 titles.

**Comment by EnorMOZ** [comment]
I am about 3x that amount. The list show up (at times) and when it did if you scrolled through it didn't show the movie. Your "Find" solution on the page actually worked. Will try the next nightly possibly tomorrow or day after to confirm the code fix.

**Comment by galli-leo** [comment]
Note this fix will always only list 20 movies for performance reasons. Filtering works again though

**Comment by EnorMOZ** [comment]
Works great no issues so far.
