### ISSUE TITLE
Issue with Remote Path Mappings - Mac Host/Windows Guest

### ISSUE THREAD

**Issue by evanl81** [Radarr/Radarr#2161]
Hi - I'm having an issue with Remote Path Mappings. I know there are a lot of people with various issues, but I haven't seen any with this specific setup:

I have Radarr running on a Mac and Qbittorrent running on a Windows Virtual Box on the Mac. I have a folder shared between the Mac and the VM. On the Mac it's:

/Users/evanl81/Downloads

On the VM it's:

\\vboxsrv (that's a double backslash but it's not displaying)

The full path to my completed downloads folder is /Users/evanl81/Downloads/complete/radarr and 
\\vboxsrv\complete\radarr (same about double backslash), respectively.

My settings in Remote Path Mappings are as such:

Host: 192.168.0.199 (IP of the VM)
Remote Path: \\vboxsrv (same about double backslash)
Local Path: /Users/evanl81/Downloads

But completed handling isn't working. I have Qbit setup so that torrents are stopped and removed after they hit my ratio. But the files just stay in that completed downloads folder. I see a fix that includes changing the user Radarr is running under, but I'm not sure how to/if I can do that on a Mac and Google has been no help. Sorry for the long post - just trying to be thorough. Thanks.

**Comment by galli-leo** [comment]
Can you include some logs?

**Comment by evanl81** [comment]
Sorry this is a stupid question - but what log should I include? None of my logs seem to include any info about this. Unless I'm not looking in the right place.

**Comment by hotio** [comment]
You telling us that radarr gives no error/warning nowhere at all that it is unable to import anything? Be it in the UI, logs or debug logs...

**Comment by evanl81** [comment]
Sorry this is what I get in the log for the full process for Guardians 2:

Searching 2 indexers for [Guardians of the Galaxy Vol. 2]
17-10-13 11:56:08.7|Info|DownloadDecisionMaker|Processing 59 releases
17-10-13 11:56:09.8|Info|DownloadService|Report sent to Qbit. Guardians.of.the.Galaxy.Vol.2.2017.1080p.BluRay.x264-SPARKS
17-10-13 11:56:09.8|Info|MovieSearchService|Movie search completed. 1 reports downloaded.
17-10-13 12:28:23.3|Info|PreDBService|Starting PreDB Sync
17-10-13 12:28:23.4|Info|NetImportSearchService|No lists are enabled for auto-import.

**Comment by hotio** [comment]
You missed the relevant part...

**Comment by evanl81** [comment]
That's all that's there. Nothing in warn or error. Can you tell me what else I'd be looking for?

**Comment by weirdcrap** [comment]
Under settings > general what is your logging level set at?

**Comment by galli-leo** [comment]
Sorry for the late response.
If you don't see any errors in Radarr and the movie file is correctly imported (i.e. it shows up as downloaded) this must be the fault of Qbit.
