### ISSUE TITLE
Radarr wont update to latest version

### ISSUE THREAD

**Issue by thousandbuckle** [Radarr/Radarr#2166]
Hello all, I have radarr installed inside of a FreeNas Jail and I am unable to update radarr to the latest version showing which is 0.2.0.870. I have tried clicking on the install latest blue button from radarr web ui but it fails. I have also tried updating from FreeBSD operating system side for the jail using pkg update && pkg upgrade but that does not seem to work either. Was hoping someone might be able to help guide me on what the issue is and how to get to the latest update.

Error log from radarr when attempting to do Web UI update:
Error occurred while executing task ApplicationUpdate: ApplicationName='mono', CommandLine='--debug /tmp/radarr_update/Radarr.Update.exe 69840 /tmp/radarr_update /root/Radarr/Radarr.exe ', CurrentDirectory='', Native error= Cannot find the specified file

Installed Radarr Version: 0.2.0.535
Mono Version: Mono Version 4.8.1 (4.8.1.0 Sun Oct 8 01:30:56 UTC 2017
FreeNAS Version: FreeNAS-9.10.2-U4 (27ae72978

**Comment by Paradoxx2015** [comment]
I have updated to the latest version, but not the "update" section just loads and loads and does not show anything.

**Comment by weirdcrap** [comment]
I am unsure if your issue is related to the OP but I am experiencing the same issue as you. I have made a thread dedicated to the issue here: https://github.com/Radarr/Radarr/issues/2174

**Comment by galli-leo** [comment]
I think the problem is, that mono is not in your path, so Radarr cannot launch the updater.
