### ISSUE TITLE
Import/Upgrade Movies from PlexMediaServer

### ISSUE THREAD

**Issue by mike2246** [Radarr/Radarr#2167]
Current setup has Radarr and all other services setup on a Cloud Server, My Plex Server is on my Home Server. Is there anyway to add all the movies from Plex to Radarr so I can upgrade any 720P to 1080 or 4K?

In Radarr I was able to make a connection to Plex Server but no movies showed up.

**Comment by hotio** [comment]
bulk import

**Comment by mike2246** [comment]
How do I bulk import if not on the same network?

**Comment by ktrinkner** [comment]
Are your movies stored on the same machine as the Plex server? If so, what OS? You may be able to forward the ports needed via your home router, but exposing those ports is a security risk.

**Comment by mike2246** [comment]
yes movies are on same machine as Plex Server, I don't mind temporarily opening ports to do a batch import. How would I do that and what ports?

**Comment by ktrinkner** [comment]
It wouldn't just be temporary, right? Radarr doesn't actually import the movie files, just links to them where they are stored on your server.

**Comment by weirdcrap** [comment]
Radarr is going to want to monitor your movie collection as part of its processing abilities so you will need to get it file system access to your library through some method like NetDrive, ExpanDrive, SSHFS, etc.
