### ISSUE TITLE
Movie editor no option to set monitored to no?

### ISSUE THREAD

**Issue by ward0** [Radarr/Radarr#2169]
![image](https://user-images.githubusercontent.com/15545810/31519154-d3f33708-afa1-11e7-9115-91eacf9530f9.png)

Trying to follow this 'guide':

https://www.reddit.com/r/radarr/comments/60ez1r/mass_mark_completeddownloaded_movies_as_not/

Version
0.2.0.870

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by hotio** [comment]
Try reading the guide... The option is there, right were it says it should be.
