### ISSUE TITLE
Manual Import Recent Root Path takes priority over Bulk Import with no option to remove

### ISSUE THREAD

**Issue by BernCarney** [Radarr/Radarr#2171]
**Description:**
Radarr adds movies (from Ombi) and uses the wrong root path. I tracked down what seems to be the problem, it will use the last manual import folder as the default root directory instead of the root directory defined from the 'Bulk Import Movies' dialog window. The problem is, there is not option to remove directories from the manual import dialog window so the only way to get it fixed is to re-set the correct root path in the manual imports.

Took me a while to get this straightened out and was a real pain to track down since root paths don't really have a set area where they are defined but instead are defined in multiple locations. I would suggest linking the manual and bulk import recent paths lists or doing one of the below solutions. I can look through the code tomorrow or sunday and issue a PR if I can figure it out on my end.

**2 possible solutions:**

1. Add an configuration option to set a root path that takes priority over all other paths from import dialogue windows.
2. Allow paths in manual import dialogue to be removed in a similar fashion to Bulk Import Dialogue.

**Radarr Version:**
0.2.0.870

**Bulk Import Screen**
![image](https://user-images.githubusercontent.com/18447002/31573455-f7cb6208-b079-11e7-9c69-7dbbe95c4866.png)

**Manual Import Screen**
![manualimport](https://user-images.githubusercontent.com/18447002/31573550-6fe84e6c-b07b-11e7-8999-8b8042b33fbe.png)

**Log Entry**
Adding Movie [][Jumanji (1995)] Path: [/mnt/video/Jumanji (1995)]

**Comment by tusharbhutt** [comment]
I must be going blind.  Where is the manual import option?  I am on 0.2.0.877

**Comment by BernCarney** [comment]
@tusharbhutt  Wanted > Missing > Manual Import

**Comment by tusharbhutt** [comment]
Ah, thanks!

**Comment by galli-leo** [comment]
Sorry for the late response, but this seems to be an issue with Ombi? Have you set your rootfolder there? Because this only happens for movies added via ombi right?
