### ISSUE TITLE
System/Updates tab hangs after update to 0.2.0.870

### ISSUE THREAD

**Issue by silentmiles** [Radarr/Radarr#2172]
**Description:**

I've just updated to version 0.2.0.870 (on Synology). Now, when I visit the System/Updates tab it hangs (the loading animation never stops). I've restarted Radarr again, but the  problem still occurs. Relevant debug logs below.

**Radarr Version:**

0.2.0.870

**Mono Version:**

4.6.2 (Stable 4.6.2.7/08fd525 Wed Jan 11 15:57:54 CET 2017)

**Logs:**

> 17-10-14 12:28:25.7|Fatal|NzbDroneErrorPipeline|Request Failed
> 
> [v0.2.0.870] System.InvalidOperationException: Sequence contains more than one matching element
>   at System.Linq.Enumerable.SingleOrDefault[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x00098] in /spksrc/native/mono/work-native/mono-4.6.2/mcs/class/referencesource/System.Core/System/Linq/Enumerable.cs:1131 
>   at NzbDrone.Api.Update.UpdateModule.GetRecentUpdates () [0x00064] in C:\projects\radarr-usby1\src\NzbDrone.Api\Update\UpdateModule.cs:34 
>   at NzbDrone.Api.REST.RestModule`1[TResource].<set_GetResourceAll>b__32_0 (System.Object options) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:111 
>   at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)
>   at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, System.Threading.CancellationToken context) [0x00049] in <63c44d6f8d7e4f339a987bf9eb94d931>:0 
> 
> 17-10-14 12:28:25.7|Fatal|NzbDroneErrorPipeline|Request Failed
> 
> [v0.2.0.870] System.InvalidOperationException: Sequence contains more than one matching element
>   at System.Linq.Enumerable.SingleOrDefault[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x00098] in /spksrc/native/mono/work-native/mono-4.6.2/mcs/class/referencesource/System.Core/System/Linq/Enumerable.cs:1131 
>   at NzbDrone.Api.Update.UpdateModule.GetRecentUpdates () [0x00064] in C:\projects\radarr-usby1\src\NzbDrone.Api\Update\UpdateModule.cs:34 
>   at NzbDrone.Api.REST.RestModule`1[TResource].<set_GetResourceAll>b__32_0 (System.Object options) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:111 
>   at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)
>   at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, System.Threading.CancellationToken context) [0x00049] in <63c44d6f8d7e4f339a987bf9eb94d931>:0 
> 
> 17-10-14 12:28:25.8|Debug|Api|[GET] /api/update: 500.InternalServerError (381 ms)
> 17-10-14 12:28:25.8|Debug|Api|[GET] /api/update: 500.InternalServerError (387 ms)

**Comment by galli-leo** [comment]
Please also search closed issue. This is a server side issue.

**Comment by silentmiles** [comment]
#2157
