### ISSUE TITLE
Radarr Library Movies disappearing after refreshing page

### ISSUE THREAD

**Issue by sideoutdude16** [Radarr/Radarr#2175]
I am not sure but I am seeing 14 movies in my Radarr collection right now.

When I click on view options including Monitored, Missing, Released, Announced, In Cinema... the movie collection doesn't change or refresh. it remains at 14 movies (like nothing was updating or change when i click.

When i click on Update Library, it finally show all of the movies (140 movies) that I added to monitor then i refreshed the page and it went back to 14 movies again!

what gives!?

**Comment by LaurentDumont** [comment]
I seem to have the same issue. I see Downloaded and Monitored: 60 at the bottom but it's telling me to add a library. If I search for a movie that's in the library, it shows up fine.

**Comment by CasperH2O** [comment]
Experiencing the same issue with Radarr Ver. 0.2.0.870.

The last thing I did was remove some already downloaded movies from the list. Now when I view the Movies page it states I should add them, however underneath it shows 20 moves as missing. When I go to the Wanted page, all the movies are there.

Things done:
- Restart Radarr
- Hard refresh browser (firefox ctrl-F5)
- Run the refresh movie task. This seems to help, when I go to the Movies page it gets live updated and I see movies getting added and can change the view (list, grid etc), however upon refresh of this page, the whole list is gone again.

**Comment by CasperH2O** [comment]
Still running the same version but after doing a computer restart and playing with the filter settings (going back and forth), all the movies are shown again. Odd, still running the same version.

**Comment by galli-leo** [comment]
You probably didn't wait long enough for the filters to update in the original post. Regardless, when running the refresh movie tasks, movies will be updated and added to the movie list. Not much we can do with the current state of the UI code so this will be closed.
