### ISSUE TITLE
Question regarding movie details > search tab

### ISSUE THREAD

**Issue by ward0** [Radarr/Radarr#2184]
Hello,

I was wondering if could confirm me what i'm thinking, the tab below:

![image](https://user-images.githubusercontent.com/15545810/31589071-4bafce9a-b1fb-11e7-877c-8dc1e14d9dc8.png)

it is created by DB lookup and previous searches? Or each time a call is send to indexers to search for it?

**Comment by galli-leo** [comment]
Everytime a new call is made to indexers.

**Comment by galli-leo** [comment]
For future reference: please use discord for such questions.
