### ISSUE TITLE
[Feature Request] Required Tags

### ISSUE THREAD

**Issue by highwaycat** [Radarr/Radarr#2189]
**Description:**

In some cases I only want to download a 3D version of a movie, and in these cases the now present "Preferred Tags" won't wait until the given tags are in the release.

I would like to ask a stricter restriction possibility, such as "Required Tags" for this, so when I give the tags: 3D and OU it'll only download a release when it contains these words in some form.

**Radarr Ver.:** 0.2.0.870

**Comment by galli-leo** [comment]
Indexers -> Restrictions
