### ISSUE TITLE
Question: Post Processing Hooks

### ISSUE THREAD

**Issue by blackley** [Radarr/Radarr#219]
Hi all,

just doing some testing and development of a sickbeard_mp4_automator script to work with Radarr - is the post-processing hooks method as follows...

- Browse to the Settings>Download Client tab and enable advanced settings [Show].
- Set the Drone Factory Interval' to 0 to disable it, and disable 'Completed Download Handling' in Radarr settings. The script will trigger a specific path re-scan, allowing the mp4 conversion to be completed before Sonarr starts moving stuff around. This step is optional if you do not desire any processing between the downloading by whichever downloader you choose (NZB or Torrent), but is required if you wish to convert the file to an MP4 before it is handed back to Sonarr.
- Setup the postSonarr.py script via Settings > Connect > Connections > + (Add)
   * name - postSonarr
   * On Grab - No
   * On Download - Yes
   * On Upgrade - Yes
   * On Rename - No
   * Filter Series Tags - optional
   * Windows Users
      - Path - Full path to your python executable
      - Arguments - Full path to postSonarr.py
   * Nonwindows Users
      - Path - Full path to postSonarr.py
      - Arguments - Leave blank

If the hooks are not active yet - would you please let me know when they are so we can continue the dev and test on the new script 👍 

Cheers,
Darren

**Comment by vertigo235** [comment]
I think the whole "connect" functionality is not ready yet.  

https://github.com/Radarr/Radarr/issues/200

Notifications and custom scripts will not work until the download event is updated to support movies instead of series.

**Comment by onedr0p** [comment]
This should be working, please refer to the wiki on the flags we set up for you.
