### ISSUE TITLE
[BUG] Unexpected movie search stop.

### ISSUE THREAD

**Issue by KBlixt** [Radarr/Radarr#2190]
**Description:**
so I recently discovered that if I did a large search (<100) of a part of my missing movies it always stopped searching approximately halfway through. and thought it was a bug about maximum api limit, but then i tried to remove a few of the movies I wanted to search for and it stoped searching at the same movie. 

I found out that after it tried to search for the movie "Kerintha" it broke and quit the search. so I deleted the movie and re-added but still the same error.

    HTTP Error - Res: [GET] https://api.nzbgeek.info/api?t=movie&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060&extended=1&apikey=(removed)&offset=0&limit=100&imdbid=0473075.: 500.InternalServerError

followed by 

    NZBGeek HTTP request failed: [500:InternalServerError] [GET] at [https://api.nzbgeek.info/api?t=movie&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060&extended=1&apikey=(removed)&offset=0&limit=100&imdbid=0473075.]

now, I did some digging and I quickly found out that the imdb-id for 0473075 is Prince of Persia. and that kerintha haven't got an imdb-id at all so i suspect that this is the core issue here. now, the movie is not interesting to me and was added to my library by accident somehow. But I'd expect the entire search list to be searched through and not stop at an item with an erroneous imdb-id. 

**Radarr Version:**

0.2.0.870

**Logs:**

relevant logs are in the description

**Comment by weirdcrap** [comment]
Shouldn't Radarr fall back to title based searches if the IMDB search fails?

**Comment by KBlixt** [comment]
that's why this is a bug. it associate a movie with the wrong imdb-ID and thus stops searching.

**Comment by weirdcrap** [comment]
Ah, I get it now. Does this only happen with NZBGeek? I have API access there as well and I have not experienced this bug yet (but I have Hydra handle usenet indexers).

I will add NZBGeek to Radarr and see what happens.

**Comment by KBlixt** [comment]
not sure about other usernets but try add the movie with the indexer you use. in theory it shouldn't be an issue with the indexer but rather the radarr adding algorithm.

**Comment by galli-leo** [comment]
This is an error on your indexer's side. It should not return a 500 just because of a wrong imdbid. We can do nothing about that, since we disable indexers with errors to not use up your api quota for requests to only end in errors.

**Comment by KBlixt** [comment]
no, this is clearly an bug in radarr. if i manually do the exact same api request then i get a bunch of good and valid results. it's just about the wrong movie.
