### ISSUE TITLE
Notification: ... not a valid application for this OS ...

### ISSUE THREAD

**Issue by pminnebach** [Radarr/Radarr#2191]
**Description:**
I'm trying to send notifications using a custom PowerShell script. But every time it gives me the following errors in the logs for on grab, download, etc.

**Radarr Version:**
0.2.0.870

**Logs:**
***Message:***
`Unable to send OnGrab notification to: Test_Powershell: The specified executable is not a valid application for this OS platform.`

***Exception:***
```
System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at NzbDrone.Common.Processes.ProcessProvider.Start(String path, String args, StringDictionary environmentVariables, Action`1 onOutputDataReceived, Action`1 onErrorDataReceived) in C:\projects\radarr-usby1\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 167
   at NzbDrone.Common.Processes.ProcessProvider.StartAndCapture(String path, String args, StringDictionary environmentVariables) in C:\projects\radarr-usby1\src\NzbDrone.Common\Processes\ProcessProvider.cs:line 199
   at NzbDrone.Core.Notifications.CustomScript.CustomScript.ExecuteScript(StringDictionary environmentVariables) in C:\projects\radarr-usby1\src\NzbDrone.Core\Notifications\CustomScript\CustomScript.cs:line 111
   at NzbDrone.Core.Notifications.CustomScript.CustomScript.OnGrab(GrabMessage message) in C:\projects\radarr-usby1\src\NzbDrone.Core\Notifications\CustomScript\CustomScript.cs:line 46
   at NzbDrone.Core.Notifications.NotificationService.Handle(MovieGrabbedEvent message) in C:\projects\radarr-usby1\src\NzbDrone.Core\Notifications\NotificationService.cs:line 174
``` 

***Note:***
Radarr is running in a windows container on Windows Server 2016.

**Comment by MoltenTesseract** [comment]
What's your external script syntax?

**Comment by pminnebach** [comment]
The script itself is merely an enumeration of the $env:radarr_* variables to find out what the syntax is and how to incorporate them in a new larger script with different functionality?

Running the script manually from within the container works fine. Although the $env:radarr_ variables are all empty.

    # ON GRAB
    
    $eventtype = $env:radarr_EventType	                # Grab
    $movie_id = $env:radarr_Movie_Id	                # Internal ID of the movie
    $movie_title = $env:radarr_Movie_Title	            # Title of the movie
    $imdb_id = $env:radarr_Movie_ImdbId	                # imdb id for the movie
    $release_title = $env:radarr_Release_Title	        # NZB/Torrent title
    $release_indexer = $env:radarr_Release_Indexer	    # Indexer where the release was grabbed
    $release_size = $env:radarr_Release_Size	        # Size of the release reported by the indexer
    $release_group = $env:radarr_Release_ReleaseGroup	# Release Group, will not be set if it is unknown
    
    # ON DOWNLOAD / UPGRADE
    
    $eventtype = $env:radarr_EventType	                                # Download
    $movie_id = $env:radarr_Movie_Id	                                # Internal ID of the movie
    $movie_title = $env:radarr_Movie_Title	                            # Title of the movie
    $Movie_Path = $env:radarr_Movie_Path	                            # Full path to the movie
    $Movie_ImdbId = $env:radarr_Movie_ImdbId	                        # IMDB ID for the movie
    $MovieFile_Id = $env:radarr_MovieFile_Id	                        # Internal ID of the movie file
    $MovieFile_RelativePath = $env:radarr_MovieFile_RelativePath	    # Path to the movie file relative to the movie' path
    $MovieFile_Path = $env:radarr_MovieFile_Path	                    # Full path to the movie file
    $MovieFile_Quality = $env:radarr_MovieFile_Quality	                # Quality name from Radarr
    $MovieFile_QualityVersion = $env:radarr_MovieFile_QualityVersion	# 1 is the default, 2 for proper, 3+ could be used for anime versions
    $MovieFile_ReleaseGroup = $env:radarr_MovieFile_ReleaseGroup	    # Release group, will not be set if it is unknown
    $MovieFile_SceneName = $env:radarr_MovieFile_SceneName	            # Original release name
    $MovieFile_SourcePath = $env:radarr_MovieFile_SourcePath	        # Full path to the episode file that was imported
    $MovieFile_SourceFolder = $env:radarr_MovieFile_SourceFolder	    # Full path to the folder the episode file was imported from
    
    # ON RENAME
    
    $EventType = $env:radarr_EventType	        # Rename
    $Movie_Id = $env:radarr_Movie_Id	        # Internal ID of the movie
    $Movie_Title = $env:radarr_Movie_Title	    # Title of the movie
    $Movie_Path = $env:radarr_Movie_Path	    # Full path to the movie
    $Movie_TvdbId = $env:radarr_Movie_TvdbId	# TVDB ID for the movie
    
    # INFO
    
    $hostname = $env:COMPUTERNAME
    $title = "Radarr Test"
    
    $body = @"
        Radarr Movie env_variables
    
        ON GRAB
    
        EventType:        $eventtype
        Movie Id:         $movie_id
        Movie Title :     $movie_title
        IMDB Id :         $imdb_id
        Release Title :   $release_title
        Release Indexer : $release_indexer
        Release Size :    $release_size
        Release Group :   $release_group
    
        ON DOWNLOAD UPGRADE
    
        EventType:                 $eventtype
        Movie Id:                  $movie_id
        Movie Title :              $movie_title
        Movie Path :               $Movie_Path
        Movie ImdbId :             $Movie_ImdbId
        MovieFile Id :             $MovieFile_Id
        MovieFile RelativePath :   $MovieFile_RelativePath
        MovieFile Path :           $MovieFile_Path
        MovieFile Quality :        $MovieFile_Quality
        MovieFile QualityVersion : $MovieFile_QualityVersion
        MovieFile ReleaseGroup :   $MovieFile_ReleaseGroup
        MovieFile SceneName :      $MovieFile_SceneName
        MovieFile SourcePath :     $MovieFile_SourcePath
        MovieFile SourceFolder :   $MovieFile_SourceFolder
    
        ON RENAME
    
        Event Type :   $EventType
        Movie Id :     $Movie_Id
        Movie Title :  $Movie_Title
        Movie Path :   $Movie_Path
        Movie TvdbId : $Movie_TvdbId
    "@
    
    $params = @{
        SmtpServer = "xxx"
        To = "xxx"
        From = "xxx"
        Subject = $title
        Body = $body
    }
    
    Send-MailMessage @params

**Comment by MoltenTesseract** [comment]
Sorry, I wasn't clear enough.

In the Radarr UI, What's your external script config set as? I have a custom PushBullet PowerShell module I wrote that sends me notifications with more details than the built-in one.

My UI looks like:

Path: C:\Windows\System32\WindowsPowershell\v1.0\powershell.exe
Arguments: -ExecutionPolicy Bypass -File C:\Scripts\Send-RadarrPushbullet.ps1

**Comment by pminnebach** [comment]
The path was directly to the script itself.

I wrongly assumed that it would be smart enough to use PowerShell to run the script.

I changed it to how you posted it, and now it works.
