### ISSUE TITLE
3D videos qualify as regular video

### ISSUE THREAD

**Issue by sambostock** [Radarr/Radarr#2193]
## Description

3D videos qualify are downloaded as if they are normal video, but are not actually watchable using standard programs.

Perhaps 3D should be a different category (similar to definition)?

#### Radarr Version: `0.2.0.778`

**Comment by hotio** [comment]
Filter out 3D release yourself, last I heard there aren't any major plans to fully support 3D files, since it's dead anyway. 3D was a flop.

**Comment by galli-leo** [comment]
Duplicate issue
