### ISSUE TITLE
[BUG?] sorting wanted cut off by quality removes the quality listings.

### ISSUE THREAD

**Issue by KBlixt** [Radarr/Radarr#2194]
**Description:**
When sorting cut off unmet wanted movies by quality, the text indicating what quality the movie is downloaded in disappears.
 
**Radarr Version:**

Version
linux 16.04

radarr
0.2.0.870

Mono Version
5.2.0.224 (tarball Tue Oct 3 19:51:58 UTC 2017)

browser:
linux firefox and windows chrome.

**Logs:**
nothing in the logs regarding this issue.

**Comment by hotio** [comment]
I can confirm this.

**Comment by erreib** [comment]
I am currently experiencing this issue when sorting by Downloaded/Not Downloaded.

**Comment by galli-leo** [comment]
Duplicate of #2195
