### ISSUE TITLE
Unable to RSS sync or Search with Mono 5.4.0.201

### ISSUE THREAD

**Issue by nphil** [Radarr/Radarr#2198]
Just upgraded mono and I'm unable to search or refresh my RSS. Running latest Mono 5.4.0.201 and 0.2.0.870 Radarr. Crashes right after I try.

stacktrace:
https://pastebin.com/SEGxyvQy

log from radarr:

https://pastebin.com/cVW0WQ7M

I should also mention that I'm running radarr on an Odroid XU4, Debian Jessie.

Thanks!

**Comment by galli-leo** [comment]
What mono version were you using before 5.4?
