### ISSUE TITLE
After bulk import, files in movie folders are added without trailing slashes and fail to import

### ISSUE THREAD

**Issue by AndersJpg** [Radarr/Radarr#2199]
**Description:**

I made a little video that shows the problem perfectly
the problem could sound a bit like:
https://github.com/Radarr/Radarr/issues/1682

in the video when I add the few movies, I, of course, let it refresh, update all that jazz before going into one of the missing movies and doing it manually, I just cut that off to save some time for you :)

video:
https://streamable.com/vqxm4

**Radarr Version:**

0.2.0.882 (nightly) (the one seen in the video is the latest develop version that came out  10/09/2017)

**Logs:**
[radarr.txt](https://github.com/Radarr/Radarr/files/1393825/radarr.txt)

**Comment by galli-leo** [comment]
Actually, if you look at your video, in the end it removes the trailing slash again. The Problem is, you didn't select a Profile.
