### ISSUE TITLE
[Fearture request] Automation  like couchpotato

### ISSUE THREAD

**Issue by SJ50** [Radarr/Radarr#220]
Please add the Automation like Couchpotato does.

**Comment by woble** [comment]
Might be related to #139

**Comment by galli-leo** [comment]
Can you be a bit more specific?

**Comment by SJ50** [comment]
It adds movie to wanted list if requirement is fulfilled.

![IMDB](http://i.imgur.com/A5RaBPV.png)
![requirements](http://i.imgur.com/2wm8iDr.png)

**Comment by SJ50** [comment]
Please also add language option in requirements as well, so it adds movie from certain language only added to wanted list.

**Comment by galli-leo** [comment]
Duplicate of #114 please comment on there if you have more suggestions.
