### ISSUE TITLE
Feature Request: Workaround for ISO/unsupported formats. Treat as failed, grab next release.

### ISSUE THREAD

**Issue by snifflezak** [Radarr/Radarr#2202]
Could we instead of halting the movie search  at unsupported file format, to instead have a switch to auto-mark-unsupported-file-formats as failed? 

I don't want ISO formats in my collection either and it's just as easy to 'fail' pull the next release. 

Not all releases are flagged in such a way that I can blacklist those formats, had about 5 of them today.

**Comment by hotio** [comment]
You might consider getting a proper tracker/index that allows to filter the crap out.

If radarr would fail for ISO/unsupported formats, it probably would mark as failed too for not unrarred movies, which seems to pop up according to some (double rar'ed). Just some thoughts to consider.

Is there no way for your downloader to mark the download as failed with the use of a postprocessing script? IIRC this should be possible when using NZBGet for example...

**Comment by snifflezak** [comment]
>If radarr would fail for ISO/unsupported formats, it probably would mark as failed too for not unrarred movies,

That's a good point, perhaps a better suggestion than failing just 'everything-unsupported' then a user-defined file-types that should be treated as failed, that way you'd be able to atleast command radarr to "fail if ,iso ,m2ts" which it would then continue to pull the next release instead of halting the process.

Yes in SABnzbd you can set filetypes to pause/abort on detection but the trouble is it's not linked with catagory so if the user wants to download a .iso later on they must first remove the extension from the 'abort if detected' field.

**Comment by hotio** [comment]
Can't the script detect the category and act accordingly?

**Comment by galli-leo** [comment]
This is something you should tell your downloadclient to do, since Radarr will not know anything about the files inside your download client until it imports them. Your DL client should be able to fail them as soon as the download starts.
