### ISSUE TITLE
Movie tags disappear after browser page refresh

### ISSUE THREAD

**Issue by rustymyers** [Radarr/Radarr#2204]
**Description:**
After the latest release updated, tags seem to disappear after refreshing movie.
Steps to reproduce:
1. Visit movie page
2. Click Edit Movie button
3. enter tags, allow autocomplete or force new entry, hit return
4. Save edit
5. Refresh page and tag disappears

Using the API seems to have similar issue. Adding tags through API will show them when first visiting page, but they disappear after refreshing in browser. 
Code used to add tags: https://gist.github.com/rustymyers/a68f405909224e023088c8cac6834c32

**Radarr Version:**
0.2.0.870

**Logs:**
Logs don't seem to contain any relevant lines. Please advise on increasing logging or which logs to provide.

**Comment by schwarld** [comment]
I am also having the exact same issue.

**Comment by unique-username313** [comment]
Same issue as well

**Comment by fana13** [comment]
Same issue, it's very uncomfortable.
Thanks in advance for fix

**Comment by deromemont** [comment]
Same issue
All my english movie is replaced by french version
Thx for the fix

**Comment by deromemont** [comment]
Any news from this bug
This is very frustrating, all my movies is replaced

**Comment by foux** [comment]
Same issue here. Movie tags are not saved. Rendered Radarr basically unusable for me.

**Comment by foux** [comment]
Any news on this issue?

**Comment by galli-leo** [comment]
Sorry havent had time to work in radarr in the last few weeks due to work :/ Can you guys try clearing cache and cookies? Seems like it’s not setting the tags properly if a simple browser refresh clears them.

**Comment by galli-leo** [comment]
Also some trace logs would be cool to gave

**Comment by fana13** [comment]
Same thing with any browser.
No trace in logs unfortunately

**Comment by rustymyers** [comment]
Here's a trace log. I reloaded the page, selected the movie, hit edit, added the tag, saved, then navigated to the logs to download the trace log. The tag remains if I visit the movie page again until the page/site is reloaded: [radarr.trace.txt](https://github.com/Radarr/Radarr/files/1448054/radarr.trace.txt)

**Comment by chuccck** [comment]
I am still having this problem as well.  Any updates?

**Comment by fana13** [comment]
@galli-leo Some news with the trace logs provided by @rustymyers ?
This problem make Radarr totally useless to lot of people.
Thanks.
