### ISSUE TITLE
English is wanted, Dutch is found

### ISSUE THREAD

**Issue by hlugt** [Radarr/Radarr#2206]
Hi, re-raising this issue, since I think the core problem is not addressed. When hardcoded subs are found in the title like “nlsubs”, it is incorrectly interpreted as audio language flag. But is is a subtitle flag. Two different configuration subjects. Changing the profile, like many suggest, from English to Dutch, surpasses the issue that the audio language should be English and nót Dutch, while hard coded NL subtitles should be allowed.

**Comment by galli-leo** [comment]
Can you give an example of the release name?

**Comment by hlugt** [comment]
Hi, of course, from debug log: 17-10-23 20:21:00.0|Debug|AcceptableSizeSpecification|Item: Cars.3.2017.1080p.WEB-DL.DD2.0.x264.NLSubs, meets si
ze constraints.
17-10-23 20:21:00.1|Debug|LanguageSpecification|Checking if report meets language requirements. Dutch
17-10-23 20:21:00.1|Debug|LanguageSpecification|Report Language: Dutch rejected because it is not wanted, wanted
 English

**Comment by Dessie69** [comment]
I think I found the problem, but can not test it. I have to rebuild everything to test is and I do not have a development environment. I will check if there is a wiki entry which describes how to create a development environment.

But...

In src/NzbDrone.Core/Parser/LanguageParser.cs:
[...]
private static readonly Regex LanguageRegex = new Regex(@"(?:\W|_)(?<italian>\b(?:ita|italian)\b)|(?<german>german\b|videomann)|(?<flemish>flemish)|(?<greek>greek)|(?<french>(?:\W|_)(?:FR|VOSTFR|VO|VFF|VFQ|VF2|TRUEFRENCH)(?:\W|_))|(?<russian>\brus\b)|(?<dutch>nl\W?subs?)|(?<hungarian>\b(?:HUNDUB|HUN)\b)|(?<hebrew>\bHebDub\b)|(?<czech>\bCZ|SK\b)",
                                                                RegexOptions.IgnoreCase | RegexOptions.Compiled);
[...]

I do not think this is correct for Dutch. It searches for 'nlsubs' with perhaps space between 'nl' and 'subs'. If it is found, it sets the language of the movie to Dutch. But the search was a subtitle! 
So an English movie with NLSubs will be detected as Dutch language.
I think this should change to searching for 'dutch|nederlands' for the language.

**Comment by Dessie69** [comment]
> _I am not sure if `nlsubs` means that the dutch subtitles are hardcoded, which means it should probably stay in the regex_

No, the `nlsubs` just means that the movie has dutch subtitles. I am not aware of _any_ movies which have hardcoded dutch subtitles. 

To find a movie with Dutch language search for `dutch|nederlands`

**Comment by stefandevo** [comment]
+1 for a fix

Also, I tried to add "Preferred Tags" like "NL" "NLSUBS" "NL.SUB" "NL.SUBS" but there are not recognized over the initial language bug.

Any change to add this bug higher then low.

You could also change the language detection AFTER the preferred tags. That way a user can choose to include the TAGS over the wanted language.

**Comment by galli-leo** [comment]
@stefandevo The latest develop release provides workarounds for this issues. Take a look at custom formats and setting profile to Any language. An overhaul of the language system is planned, but no concrete date yet.

**Comment by frechp** [comment]
Similar problem here. Preferred adding comment here instead of creating a new issue. I've got my profile set to English, but the RegEx excludes movies such as The.French.Connection.2.1975.720p.BluRay(...) or The.Italian.Job.2003.1080p.HDDVD.x264(...). I know it's only a file name to go on and this is complex to resolve, but usually, there seems to be a naming convention where the year is present. Wondering if the regex could check the language after what would appear like a date range, e.g. 1950-2050.

**Comment by JBou** [comment]
> Similar problem here. Preferred adding comment here instead of creating a new issue. I've got my profile set to English, but the RegEx excludes movies such as The.French.Connection.2.1975.720p.BluRay(...) or The.Italian.Job.2003.1080p.HDDVD.x264(...). I know it's only a file name to go on and this is complex to resolve, but usually, there seems to be a naming convention where the year is present. Wondering if the regex could check the language after what would appear like a date range, e.g. 1950-2050.

This exact issue should be resolved by [this commit](https://github.com/Radarr/Radarr/commit/fca6eeb62d8f5703e1d3f31762f771786e5c50f4) which is going to be merged with PR #4274 once it has been approved.

**Comment by Qstick** [comment]
@JBou didnt see you had fixed this, I pushed something similar this week to Aphrodite.
