### ISSUE TITLE
Disable adblock to view logs

### ISSUE THREAD

**Issue by mow4cash** [Radarr/Radarr#2209]
I noticed adblock is blocking the "log viewer" and the "add from list" . Could a notice be put somewhere to disable your adblocker or something changed so it is adblocker friendly? Maybe this is common knowledge but it had me stumped for a bit and there is not much info about the issue.

**Comment by Dnkhatri** [comment]
Thanks for the hint I have been wondering why i can see the logs for months on sonarr and radarr

**Comment by jamesmacwhite** [comment]
I can confirm that this does occur with uBlock Origin and probably others.

It looks like the `/api/log` request is being picked up by the EasyPrivacy list, based on checking the logs in uBlock Origin.

Getting it removed is probably not an option as it looks to be a generic regex rule. In theory the page name/request could be changed to be something else, but maybe adding info alert on that page might be an idea.

**Comment by jamesmacwhite** [comment]
An alert box could be added into the log table, to warn users like this, if you think that's acceptable.

![image](https://user-images.githubusercontent.com/8067792/31895028-07d43aea-b808-11e7-98ff-667a1774f02a.png)
