### ISSUE TITLE
Clean Library ignores IMDB ids

### ISSUE THREAD

**Issue by TChilderhose** [Radarr/Radarr#2215]
**Description:**

"Clean Library Level" option seems to ignores IMDB watchlist as a list. I have the "Clean Library Level" set to "Log Only" and when the list syncs, the log is filled with

> [ID][NAME] was in your library, but not found in your lists --> You might want to unmonitor or remove it

for every movie in my library.

All movies in my library were added via the same IMDB watchlist except for one, which I am using as a test for the "Clean Library Level" to see if it removes it.

Let me know if any more info is needed.

**Radarr Version: 0.2.0.889**

**Comment by TChilderhose** [comment]
Would it be possible to change 

 Radarr/src/NzbDrone.Core/NetImport/NetImportSearchService.cs

```
164     private void CleanLibrary(List<Movie> movies)
165            {
            ...

171                        foreach (var listedMovie in movies)
172                        {
173                             if (movie.TmdbId == listedMovie.TmdbId)
174                             {
175                                 foundMatch = true;
176                                 break;
177                             }
178                         }
           ...

```

to 

```
164     private void CleanLibrary(List<Movie> movies)
165            {
            ...

171                        foreach (var listedMovie in movies)
172                        {
173                             if (movie.TmdbId == listedMovie.TmdbId || movie.ImdbId == listedMovie.TmdbId)
174                             {
175                                 foundMatch = true;
176                                 break;
177                             }
178                         }
           ...

```

**Comment by galli-leo** [comment]
How are you using your imdb watchlist? Via Radarr Lists or RSS?

**Comment by TChilderhose** [comment]
It is a RSS feed of my IMDb watchlist, http://rss.imdb.com/user/ur38429534/watchlist

**Comment by TChilderhose** [comment]
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/1421984/radarr.debug.txt)

There is a debug log of me running the Net Import Sync Task. If you pay attention to one of the "Bourne" movies you can see it that it parses it from the list and then says later that its in my library but not on a list.

**Comment by galli-leo** [comment]
Ah. Try using the Radarr Lists instead. RSS Lists are deprecated.

**Comment by TChilderhose** [comment]
Okay. I take it I'm out of luck trying to use my wishlist on imdb then? Looks like only custom lists with a listid are supported?

**Comment by galli-leo** [comment]
Na just use your userid, that should work fine.

**Comment by TChilderhose** [comment]
Cool, that worked. Thanks for the help!

**Comment by ewascome** [comment]
@galli-leo Do you have a suggestion re. the StevenLu list which uses IMDB ID instead of Tmdb
