### ISSUE TITLE
Bulk Import not seeing files on one drive out of 3

### ISSUE THREAD

**Issue by Tokkolosh** [Radarr/Radarr#2219]
Hey Guys 

I just found Radarr a couple of days ago and love the service.
All is working great except for 1 problem.
I have 3 drives on a nas what hold my movies...x, y, and z
I added x and did a bulk import for movies. It gave me 15. Being unfamiliar with the prog I added them and moved on to y and z on which I added several hundred movies by changing the amount displayed etc. no prob.

I go back to x to import the rest of the movies on the drive. It tells me they have all been added and there is nothing new there.  I even deleted all x drive listing and tried to bulk import again fresh... nope... all has been added no movies here. 
Radarr can access x drive and can save to it and set it as the location of new movies but will not search for new movies on it. I even remapped "x" to "Q", same thing nothing there, all added.

x and y are on the same nas same config and setup. The only diff is x is 4tb and y is 2tb.

Any advice/ideas?

Thanks

**Comment by jtrott** [comment]
Nope, but I have a similar issue where no movies are found, and subsequent scans don't even look at movies that should be identified - according to the logs.

Radarr version: 0.2.0.910

**Comment by galli-leo** [comment]
Can you provide debug logs? (Settings -> General)
