### ISSUE TITLE
Request: 3D

### ISSUE THREAD

**Issue by daanvb** [Radarr/Radarr#222]
Is it possible to include a 3D quality profile to be able to search and differentiate for 3D films? I sometimes have both versions of a film so a separate area to list 3D films would also be cool

**Comment by hstamas** [comment]
Second this request. I usually try to obtain both versions of a film and not having to leave Radarr and manually search for the 3D version would be very convenient.

**Comment by onedr0p** [comment]
Moved discussion to http://feathub.com/Radarr/Radarr/+31
