### ISSUE TITLE
Newbie To Plex : Invalid request Validation failed: -- Incorrect username or password

### ISSUE THREAD

**Issue by deviloruim** [Radarr/Radarr#2223]
[radarr.txt](https://github.com/Radarr/Radarr/files/1422138/radarr.txt)
![plex passwd](https://user-images.githubusercontent.com/33154996/32105564-f4afc526-bb39-11e7-9e5c-fb8b1c6dadcc.jpg)
Greetings People !

I am a newbie to Radarr/Sonarr and I am having the same issue .

Issue : 
---------
Both are throwing me error whenever I test the initial connection to Plex.

The error has to do with invalid credentials , I have used all combination from my plex account (Picture attached) , it is this account Im suppose to use?

Logs (Attached) shows the same error and nothing else is mentioned . or at least didnt find much sense in the rest of the log.

Could anyone gimme a hand to get this working?

Im running radarr sonarr plex , on a centos 7 minimal .

Thanks in advance guys !

**Comment by weirdcrap** [comment]
You should use the username (not email) and password that you use to sign in to the plex web interface either locally or at https://plex.tv

So Maiso***** something and whatever your password is. Looking through the log quickly that sounds like your only issue. Are you copy/pasting to prevent any typos? 

Be sure you don't copy any extra spaces or anything like that. I once fought a router for an hour trying to figure out why I couldn't get in and it was because there was a space at the end of what I was copying.

**Comment by deviloruim** [comment]
@weirdcrap  Thank you a lot for getting back to me .

Let me give you some more details then : 

1) I have attached the full trace 
2) I think this is the part that is failing (From the trace)

17-10-28 10:40:14.5|Debug|PlexServerService|Getting sections from Plex host: 5.9.152.209
17-10-28 10:40:14.5|Error|PlexServerService|Unable to connect to Plex Server

[v2.0.0.4949] NzbDrone.Core.Notifications.Plex.PlexAuthenticationException: Invalid Token - Update your username and password
  at NzbDrone.Core.Notifications.Plex.PlexServerProxy.GetAuthenticationToken (NzbDrone.Core.Notifications.Plex.PlexServerSettings settings) [0x00061] in <e8ad39d438bc4c448bfbd968b0f74ec6>:0 
  at NzbDrone.Core.Notifications.Plex.PlexServerProxy.GetPlexServerRequest (System.String resource, RestSharp.Method method, NzbDrone.Core.Notifications.Plex.PlexServerSettings settings) [0x00026] in <e8ad39d438bc4c448bfbd968b0f74ec6>:0 
  at NzbDrone.Core.Notifications.Plex.PlexServerProxy.GetTvSections (NzbDrone.Core.Notifications.Plex.PlexServerSettings settings) [0x00000] in <e8ad39d438bc4c448bfbd968b0f74ec6>:0 
  at NzbDrone.Core.Notifications.Plex.PlexServerService.GetSections (NzbDrone.Core.Notifications.Plex.PlexServerSettings settings) [0x00016] in <e8ad39d438bc4c448bfbd968b0f74ec6>:0 
  at NzbDrone.Core.Notifications.Plex.PlexServerService.Test (NzbDrone.Core.Notifications.Plex.PlexServerSettings settings) [0x00000] in <e8ad39d438bc4c448bfbd968b0f74ec6>:0 

17-10-28 10:40:14.5|Trace|NzbDroneErrorPipeline|Handling Exception
17-10-28 10:40:14.5|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Incorrect username or password
17-10-28 10:40:14.5|Trace|Http|Res: 666 [POST] /api/notification/test: 400.BadRequest (19 ms)
17-10-28 10:40:14.5|Debug|Api|[POST] /api/notification/test: 400.BadRequest (19 ms)
17-10-28 10:40:15.8|Trace|Http|Req: 667 [POST] /api/notification/test
17-10-28 10:40:15.8|Debug|PlexServerService|Getting sections from Plex host: 5.9.152.209
17-10-28 10:40:15.8|Error|PlexServerService|Unable to connect to Plex Server
 
3) I used the Maison username , and doing it manually check logging with same credentials manually over plex to make sure they work.

4) This is my setup exactly https://deviantengineer.com/2015/06/usenet-centos7/ 

I have followed up this document which was very straightforward , i just added something for sonarr part (Which is adding a firewall exceptions and that's it) Radarr didnt complain 

[sonarr.debug.txt](https://github.com/Radarr/Radarr/files/1424075/sonarr.debug.txt)
[sonarr.trace.txt](https://github.com/Radarr/Radarr/files/1424076/sonarr.trace.txt)

- I did not loose hope yet and will NOT switch the server to a windows server :( 

Thanks for taking the time looking into this dude.


Best Regards

**Comment by weirdcrap** [comment]
Is this your plex server address you are attempting to connect too:  5.9.152.209 ?
If PMS is on the same server as sonarr/radarr try using localhost or 127.0.0.1 instead of the actual network address. I only use the full numeric IP in my screenshot above because all my stuff runs in dockers.

What does plex say your internal IP and port number are under the settings > Remote access section:
![screen shot 2017-10-28 at 8 53 16 am](https://user-images.githubusercontent.com/22824785/32135033-d31bbb3e-bbbd-11e7-9c9c-514a565729a2.png)

**Comment by deviloruim** [comment]
@weirdcrap  That was it !

Your picture made me realize what to expect from the Plex Settings , and when i realized I do not have those tabs.
- I had to check if accessing Plex from my Laptop Windows , can see the plexmediaserver service on the Centos Machine .

The fix was (Found on the web) 

- To tunnel my Laptop connection and bind it to the 32400 port (Using a putty )
- Exact command you should run on a putty from your laptop.

(ssh ipofyourserver -L 8888:localhost:32400)

* So that was not a radarr issue per say
Thanks a lot man for your support , your screenshot did the trick !

**Comment by weirdcrap** [comment]
Glad you got it figured out! @galli-leo this can be closed.

**Comment by darknessgp** [comment]
As a strange aside... I recently ran into this after the last plex update. I have to now put in my email for the username rather than just the username, Like I said, was fine before the update but after it only the full email address works.
