### ISSUE TITLE
[BUG] Bulk import - profile changes for all movies when changing one

### ISSUE THREAD

**Issue by DangerIsGo** [Radarr/Radarr#2224]
**Description:**

When doing a bulk import and change the quality profile for a single movie, the quality profile ends up changing for all movies both before and after the movie in question.  I can't tell if this is a feature since I did a search in the issues and only came across #1005 but from the comments it didnt seem as if it was the same thing.  Not to mention, I remember it being a bug on the previous Radarr version when I tried it a few weeks ago.  Most, if not all, of the movies I import I'm going to have my 1080p profile on, but there may have been a handful where I would want a lower profile.  I think the only way around this would be to change the profile on the one movie, import it, and then change profile back on the next movie to affect the rest of them. This works fine if I'm importing the movies one by one but doesn't if I'm scrolling down the list and changing the profiles individually without importing any previous movies.

**Radarr Version:**
0.2.0.870

**Comment by galli-leo** [comment]
This is a feature. When we will update our ui, we may consider changing this, but for now, you can just import most of your movies with a 1080p profile and then redo for all leftover movies.
