### ISSUE TITLE
any eta on when Preferred Tags will be working

### ISSUE THREAD

**Issue by aniel300** [Radarr/Radarr#2225]
**so i have this issues where i have Preferred Tags as follow:  hevc, x265, h265, x.265, h.265, 265, 10bit, utr, Tigole, UTR, xxxpav69, but it keep download x264 movies etc :**

**0.2.0.890-aesednnn:**

**n/a:**

**Comment by galli-leo** [comment]
Yeah preferred tags only make releases containtning those tags, more preferred other releases are still downloaded. What you are looking for, might be Restrictions under Indexers -> Restrictions.

**Comment by AnthraxLeprosyPi** [comment]
If I might join, is there any way to have the x264 version being download but not meet the cut-off and then when a smaller x265 (imho more preferable) version comes out have it download this and replace the x264 one?

Would be the last part of the puzzle for me ;-)

cheers
Anthrax

**Comment by galli-leo** [comment]
Will come with custom qualities

**Comment by AnthraxLeprosyPi** [comment]
Nice! How to know when it works - is there a seperate issue for it?

didn't find one...

Anyway thank you for being awesome!
Anthrax

**Comment by galli-leo** [comment]
See Project Metis (under the Project Tab). There are a lot of issues pertaining to the full concept.
