### ISSUE TITLE
Javascript error in movie editor

### ISSUE THREAD

**Issue by fruxi** [Radarr/Radarr#2226]
After updating to the latest build (0.2.0.889) I'm not able to make changes with the movie editor.
After clicking SAVE button I'm getting following javascript error:
![image](https://user-images.githubusercontent.com/33173105/32132465-6cc3558e-bbc4-11e7-9235-49b33b995498.png)

**Radarr Version:**
Radarr Ver. 0.2.0.889
Docker: hotio/suitarr

**Comment by galli-leo** [comment]
Fixed in latest release.
