### ISSUE TITLE
Feature Request: Import from Movie page

### ISSUE THREAD

**Issue by 4getit** [Radarr/Radarr#2228]
Especially when having a large library (25K+), the Manual Import function is painly slow to work with.
And since a few updates ago, the filtering doesn't seem to work anymore. (The white popup modal when searching for the title to assign to the file being imported. If you type in a part of the title, it just sits there and doesn't show the filtered results anymore).

For single file imports... Instead of selecting a file and then searching for the title, I suggest having something that works the other way around.

I suggest an icon on the Movie Page itself (next to Modify, Update, Preview rename, Search etc.) called Manual Import. 
When clicked, a modal that allows to select the video file.

I think this is much simpler and works much faster.

**Comment by galli-leo** [comment]
Hmm that does sound like a good idea. Though when I fix the manual import thingy, it should be very fast again, so maybe this is not needed.

**Comment by 4getit** [comment]
Oh of course. It would be great if the manual import was fixed (and a bit faster :)).

But sometimes it's just easier to stand on the movie page that has the poster, description etc.. The manual import often make me doubt if I'm picking the right one if multiple titles are similar or slightly different from the file name.
But maybe low on the list as a low priority feature request then. :)
Thanks!

**Comment by talentedmrripley** [comment]
I second the vote to have the ability to import from the movie page.

**Comment by galli-leo** [comment]
Shouldn't be that much of an issue with the latest release, since it automatically matches movies (when it can)
