### ISSUE TITLE
Can't manually search for Movies

### ISSUE THREAD

**Issue by antigravity83** [Radarr/Radarr#2234]
I can no longer manually search for movies. Just loads and eventually stops searching. But although results are found in the logs, they're never displayed in the GUI for manual selection and download.

Auto search seems to work ok. It's as if it gets the results, but never displays them. 

Logs: https://zerobin.net/?ad9efbda6981a5fb#WNcgTcdfGn+83LECyprBIookQ89sjefoQZoVUhD+WtA=

Radarr Version: 0.2.0.793

**Comment by galli-leo** [comment]
Is this still an issue on the latest release? Cannot load the logs.

**Comment by Crenor** [comment]
I still have this issue. Radarr does not seem to search for much of anything for me...

**Comment by 88fingerslukee** [comment]
I have this issue. It just started recently. The logs don't state anything and I have them set to trace.

**Comment by freedomischaos** [comment]
I am having the same issue. For some reason, it seems the imdb search is timing out based on what little I get from logs.
