### ISSUE TITLE
Sorting by "Downloaded" under Cutoff Unmet sorting by alphabetical instead.

### ISSUE THREAD

**Issue by Aurailious** [Radarr/Radarr#2235]
**Description:**

Sorting by "Downloaded" under Cutoff Unmet sorting by alphabetical instead.  At least while by descending, unsure what is occurring while ascending.  Both circumstances does not display the downloaded type.

I would like to sort by downloaded type and select to search for lower quality items.

**Radarr Version:**
0.2.0.870

**Comment by galli-leo** [comment]
Duplicate of #2195
