### ISSUE TITLE
Radarr System Status Disk Space - does not see OSX new APFS Volumes

### ISSUE THREAD

**Issue by paulodell** [Radarr/Radarr#2237]
## Bug Report
Radarr System Status Disk Space - does not see OSX new APFS Volumes

### System Information/Logs
**Description:**
Since changing my drives to use APFS they are not visible on the Disk Space page of Radarr, the Drive selection and link to data is fine, just the useful Disk Space feature does not show the drives at all

**Radarr Version:**

Version 0.2.0.870

Mono Version 5.2.0.224 (d15-3/14f2c81 Thu Aug 24 10:33:52 EDT 2017)

**Comment by galli-leo** [comment]
Have you tried updating mono? AFAIK this is something we get from mono.

**Comment by paulodell** [comment]
Yes I just tried it and still no luck

Mono Version
5.4.0.201 (2017-06/71277e78f6e Thu Sep 21 19:22:55 EDT 2017)

**Comment by paulodell** [comment]
Please see here, Sonarr have fixed this in their code...

https://github.com/Sonarr/Sonarr/issues/2261#issuecomment-349067021

https://github.com/Sonarr/Sonarr/commit/0a690eb4d8f2a7faba0c5e97e302bde852aa20aa

**Comment by galli-leo** [comment]
Fixed in nightly
