### ISSUE TITLE
Main page: Filters not working + Files reported missing

### ISSUE THREAD

**Issue by matmuilwijk** [Radarr/Radarr#2241]
**Description:**
On the main page, the filter (Monitored/Announced/Etc) doesn't work. Whichever option is picked, the list does not change. (Even after reboots, restarting Radarr, etc)

At the same moment this started, Radarr stopped seeing a lot of files. On the main page, they're listed as missing, while at the movie page the file is visible, and can be interacted with (Deleted, renamed, etc)

**Radarr Version:**
0.2.0.870 (Develop)
**Logs:**

[Radarr-debug-log.txt.txt](https://github.com/Radarr/Radarr/files/1443038/Radarr-debug-log.txt.txt)

**Comment by galli-leo** [comment]
Can you try clearing cache and cookies?

**Comment by matmuilwijk** [comment]
Tried that before I started this issue.

However, I've noticed that it does work in another browser.

**Comment by matmuilwijk** [comment]
Did a clean reinstall of the browser, and works fine now.

Met vriendelijke groet,

Matthijs Muilwijk
van Slingelandtshof 5
3311 NJ Dordrecht

P. +316-13321539
E. matthijsmuilwijk@gmail.com

2017-11-05 15:04 GMT+01:00 Matthijs Muilwijk <matthijsmuilwijk@gmail.com>:

> Tried that before I started this issue.
>
> However, I've noticed that it does work in another browser.
>
