### ISSUE TITLE
Optimize Root Folder API Call

### ISSUE THREAD

**Issue by deathbybandaid** [Radarr/Radarr#2242]
**Description:**
Accessing the API for root folders takes too long and gives a 504 error. I have tested other API access such as /system/status without issue. I checked my sonarr API access to verify I am accessing at the correct address. This causes a major issue when trying to setup Ombi.

Address I'm Using
http://MYIPADDRESS:7878/radarr/api/rootfolder?apikey=MYRADARRAPIKEY

Additional info:
I'r running radarr within a Proxmox container, with nothing else running in the container.
The container has 8GB ram, 3 CPU cores, and 2GB swap space. The container is running debian stretch.

Side Note:
Everything about Radarr works great aside from this API access.
I believe part of the problem might be the amount of root folders I have.
(I organize my movies into sub-folders for movie-series)

**Radarr Version:**
Version 0.2.0.870

**Logs:**
I moved my log file to radarr.txt.old , and created a new radarr.txt , the new file did not populate any information when recreating the issue.

**Comment by deathbybandaid** [comment]
I am accessing it directly with the IP address on the same local network (and since I'm using proxmox, literally the same hardware)

**Comment by galli-leo** [comment]
Strange since AFAIK we do not throw 504 errors.

**Comment by galli-leo** [comment]
Can you do a traceroute to the ip address?

**Comment by deathbybandaid** [comment]
````
root@ombi:~# traceroute 192.168.1.212 7878
traceroute to 192.168.1.212 (192.168.1.212), 30 hops max, 7878 byte packets
 1  192.168.1.212 (192.168.1.212)  0.256 ms  0.023 ms  0.021 ms
````

**Comment by deathbybandaid** [comment]
All other responses to and from Radarr seem to work very well, it seems to be just with getting the root folders.

**Comment by qazero** [comment]
Any update regarding this? I'm experiencing the same issues.

**Comment by galli-leo** [comment]
@qazero This should be improved in the next release.

**Comment by drwyrm** [comment]
Hi, any updates on this? With 50 root folders this is what I get:
`$ time curl -q 'http://localhost:7878/radarr2/api/rootfolder' -H 'cookie: ........ --compressed > /dev/null

real    2m27.937s
user    0m0.016s
sys     0m0.028s

`
