### ISSUE TITLE
Feature Request: Multiple names for movies and Cyrillic support

### ISSUE THREAD

**Issue by Mavrag** [Radarr/Radarr#2243]
hey , is it possible for someone to add support for Cyrillic and Multiple names for movies cause the tracker has the Russian movies are titled only in Russian unlike English movies that have both English and Russian name in the title . This is the only thing that;s stopping me from full automation

**Comment by hotio** [comment]
Is the tracker just translating movie names or are the official movie names missing from themoviedb?

**Comment by galli-leo** [comment]
^ You can add alternative titles via the movie database.

**Comment by Mavrag** [comment]
hey im testing with this movie https://www.themoviedb.org/movie/62276-bumer, as you can see it has the name in russian , but radarr names it Bummer and searches for it the same way

**Comment by Mavrag** [comment]
even on imdb it has both russian and english names http://www.imdb.com/title/tt0381936/?ref_=nv_sr_2
