### ISSUE TITLE
Feature Request: Manual search with a custom name for the movie

### ISSUE THREAD

**Issue by Mavrag** [Radarr/Radarr#2244]
Hello , could you guys add like a search bar when manually searching for movies so that  the user can edit the name before searching .

**Comment by hotio** [comment]
Radarr uses all the known movie titles to search/map, what would be the benefit of this for automation? I'm sure your indexer supports manual searches, no?

**Comment by galli-leo** [comment]
^ and see the other issue.

**Comment by Mavrag** [comment]
i need it to search for russian movies in russian. cause the titles of the movie are in russian.

**Comment by Mavrag** [comment]
maybe add like a dropdown list of all the names of the movie in different languages , i think couchpotato had something like that

**Comment by galli-leo** [comment]
Radarr already uses the russian titles if available.

**Comment by Mavrag** [comment]
I think it uses Russian only if there are no English titles available. So that doesnt help me much.

**Comment by Tryum** [comment]
Some movies are not findable because of accents, silly release names no one uses, or relases mismatching release year.
Providing a one-time-per movie customizable search would really help in those edge cases.
