### ISSUE TITLE
Movie API endpoint add sceneName

### ISSUE THREAD

**Issue by pannal** [Radarr/Radarr#2245]
Hey,

I'm the developer of the [Sub-Zero plugin](https://github.com/pannal/Sub-Zero.bundle) for the Plex Media Server environment.

SZ relies on detecting certain information about a media file partially from the filename itself. People like renaming their media files automatically using Radarr, though.

Sonarr provides the `sceneName` property in results of its `episodeFile` API endpoint.
This property contains the downloaded pre-postprocessed/renamed original filename.

Would it be possible to implement the same in Radarr?

Thank you

**Comment by hotio** [comment]
Many thanks from me, for what is the best subtitle solution out there and the reason I started using Plex.

**Comment by Nottt** [comment]
I support anything that @pannal needs. SubZero is awesome and anything that can increase the % of correct matches is worth doing.

**Comment by pannal** [comment]
<3

**Comment by pannal** [comment]
@galli-leo how come the `sceneName` isn't always set? It seems to be linked to the `iNTERNAL` tag inside a filename. If that's there, `sceneName` isn't set.
