### ISSUE TITLE
Select movies in Manual Import are not sorted by name

### ISSUE THREAD

**Issue by Cyriltra** [Radarr/Radarr#2247]
Hello,

in Wanted -> Manual Import -> after selecting a folder -> click Manual Import button -> "click to select movie"

The movies are not sorted by name, nor by year. it seems to be sorted by added date (in Radarr) => very difficult to find the right movie in large database

The "filter movies" input is not working either

**Radarr Version:**
0.2.0.870

Thank you

**Comment by galli-leo** [comment]
Fixed on latest nightly.
