### ISSUE TITLE
Queue filling up with old, already downloaded and imported movies

### ISSUE THREAD

**Issue by jsgiacomi** [Radarr/Radarr#2248]
Under "Activity" in the "Queue" tab movies that have been previously downloaded and successfully imported are starting to show up again and erroring out because the path is no longer valid. The path is no longer valid because the movies have already been imported and removed from the download folder (see picture). I suspect it is because SABNZB is retaining the history and Radarr is not correctly identifying that the movie was already imported (just a guess). It seems to select movies at random however so I am not sure what is really going on. It is critical for me to retain all history in SABNZB so triggering the option to "remove imported downloads history from the download client" is not an option for me. This has been working great for the last 8 months, not sure why the sudden change. 
Radarr Version (nightly): 0.2.0.892
SABNZB Version: 2.3.1 [f1695ec] 

<img width="721" alt="screen shot 2017-11-05 at 8 39 49 am" src="https://user-images.githubusercontent.com/5577598/32416954-98286e9c-c206-11e7-913d-f0518dad3aef.png">
<img width="1143" alt="screen shot 2017-11-05 at 8 26 43 am" src="https://user-images.githubusercontent.com/5577598/32416955-983c1e38-c206-11e7-8457-c01f56431a70.png">
<img width="979" alt="screen shot 2017-11-05 at 8 23 19 am" src="https://user-images.githubusercontent.com/5577598/32416956-98501f8c-c206-11e7-8713-07ae938668ab.png">

`17-11-5 07:59:14.9|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: F:\SAB_NZBd Downloads\Movies\Jackie 2016 DVDScr XVID AC3 HQ Hive CM8
17-11-5 07:59:15.0|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: F:\SAB_NZBd Downloads\Movies\Operation Avalanche 2016 1080p BluRay x264-ROVERS-Obfuscated\
17-11-5 07:59:15.0|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: F:\SAB_NZBd Downloads\Movies\Jack Reacher Never Go Back 2016 1080p BluRay x264 DTS-HD MA\
17-11-5 07:59:15.1|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: F:\SAB_NZBd Downloads\Movies\Patriots Day 2016 DVDSCREENER-P2P-Obfuscated\
17-11-5 07:59:15.1|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: F:\SAB_NZBd Downloads\Movies\The Birth of a Nation 2016 1080p BluRay DD5 1 x264 1-SA89-Ob.1\570f2cc370704b9093781bdcbf5fa03e.mkv
17-11-5 07:59:15.2|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: F:\SAB_NZBd Downloads\Movies\The Birth of a Nation 2016 1080p BluRay DD5 1 x264 1-SA89-Ob\
17-11-5 07:59:15.2|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: F:\SAB_NZBd Downloads\Movies\Fences 2016 DVDSCREENER XVID AC3-FrangoAssado
17-11-5 07:59:15.3|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: F:\SAB_NZBd Downloads\Movies\Florence Foster Jenkins 2016 1080p BluRay DTS x264-CyTSuNee-\`

**Comment by hotio** [comment]
Make sure radarr can no longer see the history of those files in your download client to fix this.

**Comment by gthicks** [comment]
@hotio How would you do that, assuming you don't want to delete everything from your sabnzb history?

**Comment by hotio** [comment]
category change
