### ISSUE TITLE
"release rejected - quality of file on disk is better" but it isn't

### ISSUE THREAD

**Issue by breadcan** [Radarr/Radarr#225]
"Quality for existing file on disk is of equal or higher preference: Bluray-1080p v1"

![image](https://cloud.githubusercontent.com/assets/416166/21937546/20d3ede4-d9b8-11e6-95e5-581563ce56f9.png)

![image](https://cloud.githubusercontent.com/assets/416166/21937575/2cee46f6-d9b8-11e6-876b-a2bc7a1110fd.png)

![image](https://cloud.githubusercontent.com/assets/416166/21937602/3ffcf814-d9b8-11e6-81e5-7718bbf1c0df.png)

**Comment by galli-leo** [comment]
It is equal. So that's why it wont download another one.
