### ISSUE TITLE
Series folder name

### ISSUE THREAD

**Issue by zoinksa** [Radarr/Radarr#2252]
I have looked around and have seen some debate about this problem, but not any really answers, so I take my chance here.

When I go to media management, and into episode naming and to the series folder name. This always comes up in this format "Seriename (year)"  is there no way to remove the year in the folder so that it would only say for eksample " The big bang theory"  and nothing more  (ofc without the "")

**Comment by hotio** [comment]
Radarr doesn't do series, only movies are supported.

It is not recommended to removie the year from a movie's folder name, although possible.
