### ISSUE TITLE
Still searching indexers on unmonitored movies imported from list

### ISSUE THREAD

**Issue by rourke** [Radarr/Radarr#2256]
**Description:**
When Radarr adds movies from my IMDB watchlist it searches my indexers even though I specifically add them unmonitored. I can see this in the Radarr popups in the bottom right corner, but the Jackett logs also return results.

(Sorry for the titlegore. I couldn't think of a way to keep it clean.)

**Radarr Version:**
0.2.0.870 (latest atm)

**Logs:**
NA

![image](https://user-images.githubusercontent.com/2820753/32581217-3ffac7e8-c4e9-11e7-90ee-38c5a72ab5e3.png)

**Comment by galli-leo** [comment]
I think this issue was raised before. Anyways, I can add a toggle to the lists whether to search for movies added by it or not. Also I would suggest switching your rss list to Radarr Lists. RSS lists are deprecated.

**Comment by rourke** [comment]
That toggle would be nice and would save me some api hits to certain private trackers. I wasn't aware of the Radarr lists feature. I switched to that now. Thanks!
