### ISSUE TITLE
Change {[MediaInfo Full]} format output

### ISSUE THREAD

**Issue by Nottt** [Radarr/Radarr#2257]
Currently `{[MediaInfo Full]}` creates something like `[x264 DTS-HD MA[EN+PT]] `.

This confuses tools that search for subtitles using the framework guessit. It's easy to fix this. You just need to either lose the double brackets so it's `[x264 DTS-HD MA EN+PT] ` or `[x264 DTS-HD MA] [EN+PT] `.

Any chance of getting this implemented?

**Comment by pannal** [comment]
@Nottt this will become redundant once sceneName is integrated into the Radarr API, though. At least for Sub-Zero users :)
