### ISSUE TITLE
Feature request: Bluray remuxed but not full bluray

### ISSUE THREAD

**Issue by breadcan** [Radarr/Radarr#226]
Would be nice to download remuxed bluray mkv but skip "complete bluray".

not sure if this is possible to detect. for now I set "iso, m2ts, mpls" as unwanted extensions in sabnzbd to halt the download.
And had "remuxed" as preferred in couchpotato to push the release score.

**Comment by KrunchMuffin** [comment]
I tried to add my own quality for remux under unknown, but the sliders are still set for TV shows. This is exciting tho. finally get rid of CP!

**Comment by breadcan** [comment]
i guess it would be possible with preferred tags. #227
