### ISSUE TITLE
Torznab Add issue

### ISSUE THREAD

**Issue by vinchi007** [Radarr/Radarr#2263]
**Description:**
I'm having a problem adding Torznab Cardigan. Same configuration works on SOnarr but fails on Radarr.

**Radarr Version:**
Radarr Version (latest): 0.2.0.870
Mono Version: 3.10.0 (tarball Thu Feb 4 00:22:52 PST 2016)

**Logs:**
```
17-11-13 14:15:03.9|Warn|Torznab|Unable to connect to indexer

[v0.2.0.870] System.InvalidOperationException: Sequence contains no elements
  at System.Linq.Enumerable.First[IndexerPageableRequest] (IEnumerable`1 source) [0x0005b] in /usr/wrkdirprefix/usr/ports/lang/mono/work/mono-3.10.0/mcs/class/System.Core/System.Linq/Enumerable.cs:848
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[NzbDrone.Core.Indexers.Torznab.TorznabSettings].TestConnection () [0x0000e] in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:325

17-11-13 14:15:03.9|Warn|NzbDroneErrorPipeline|Invalid request Validation failed:
 -- Unable to connect to indexer, check the log for more details

```

**Comment by vinchi007** [comment]
![image](https://user-images.githubusercontent.com/2197609/32744619-1f41ebc4-c87e-11e7-8a3e-6ef09de46025.png)

**Comment by vinchi007** [comment]
I've done trace from both Radarr and Sonarr, it seems you're handling this differently. The problem was actually with my Cardigan API which had all its indexers dead. You can close this as non issue, but might want to enhance output/logging a bit

**Comment by tcheronneau** [comment]
Hi @vinchi007,

I've the same issue but with Jackett. 
For the same indexer sonarr is working but not radarr and I can't find any issue in my config. 
How did you solved your issue ?

Thanks.

**Comment by galli-leo** [comment]
@vinchi007 Yeah we have an open issue for that. @tcheronneau Try disabling search, adding the indexer then enabling. This forces radarr to use it.
