### ISSUE TITLE
[Feature Request] Cutoff Unmet Checks Quality as well as File size 

### ISSUE THREAD

**Issue by NuGundam** [Radarr/Radarr#2265]
Say you import movies the come up as your Blu-ray 1080p and that is your Cutoff but their file size is smaller than the quality you want in your quality definitions.
 
So is it possible for it to check the file size as well?

**Comment by onedr0p** [comment]
This is an old issue tagged with UI, this is very likely fixed in v3. Please let us know otherwise (and even if you want this feature in v3) and we will reopen the issue.

**Comment by fryfrog** [comment]
I don't think it is, but this is something that'd be covered by a Custom Format anyway.
