### ISSUE TITLE
[Feature Request] use multiple download clients depending on indexer

### ISSUE THREAD

**Issue by wikkixwikki** [Radarr/Radarr#2266]
**Description:**
Could you add a way to direct an Indexer to use a specific download client?
Example, UseNet Indexer downloads use NZBGet download client and another Indexer uses Deluge download client.

Provide a description of the feature request or bug here, the more details the better. 
Please also try to include the following if you are reporting a bug

**Radarr Version:**
Version
0.2.0.870
Mono Version
5.4.1.6 (tarball Wed Nov 8 20:37:08 UTC 2017)

[AB#860](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/860)

**Comment by galli-leo** [comment]
Torrent indexers already use a torrent client while usenet indexers use a usenet client.

**Comment by iVirus** [comment]
This would be useful to have different torrent indexers using different torrent clients. It’s a feature I’ve been silently hoping to see.

**Comment by mawvius** [comment]
Another vote here - being able to select a different download client or automatically based on criteria, would be amazing!

**Comment by alexvnesta** [comment]
I'd also really like to see this feature. Is there any workaround? I want to have one transmission instance for seeding private stuff forever and another for deleting public stuff after I reach my ratio.

**Comment by BEisem** [comment]
This feature would be great, for usenet as well. Perfect case for me, I have a server (seedbox) that I use for downloading large REMUX files, but I download smaller versions at home. 

Since the seedbox is faster, I want to have the Usenet download client on the seedbox download only REMUXes. It would be great to have Radarr send REMUX download requests to one download client (on the seedbox) while other download requests are sent to the download client on my local computer.

**Comment by tarek369** [comment]
I would like to have this too

**Comment by TMTYD** [comment]
Hi guys,

Look at my thread #4437, i think it's a very nice feature

**Comment by TheTomCanuck** [comment]
This would be great. I have to manually enable a client and disable another (rinse and repeat as i go through indexers) every time i wanna use interactive search

**Comment by bakerboy448** [comment]
A simple +1 on the OP will do

Please don’t comment unless you have something productive and beneficial to add
