### ISSUE TITLE
"Also Known As" is frequently full of repeating entries

### ISSUE THREAD

**Issue by Logvin** [Radarr/Radarr#2267]
**Description:**

Many of my movies have a ton of extra "Also Known As" entries, usually the same ones repeating.

This image was taken just now for the Thor: Ragnarok movie.
https://imgur.com/D23Ao1L

Like to the mapping:
https://mappings.radarr.video/movie/284053

It seems to me there is some process that is fetching the same enteries and appeneding them without checking for duplicates first.

**Radarr Version:**
Version
0.2.0.846
Mono Version
4.6.2 (Debian 4.6.2.7+dfsg-1ubuntu1)

**Comment by galli-leo** [comment]
This is fixed in .870
