### ISSUE TITLE
Unable to connect to indexer / Jackett / YGGtorrent

### ISSUE THREAD

**Issue by jrozelle** [Radarr/Radarr#2269]
**Description:**

I can't add YGGtorrent with Jackett
"Unable to connect to indexer, check the log for more details"
Am I the only one with this trouble ?

**Radarr Version:**
Radarr Ver. 0.2.0.870
develop

**Logs:**
17-11-16 14:51:17.8|Warn|Torznab|Unable to connect to indexer

[v0.2.0.870] System.InvalidOperationException: Sequence contains no elements
  at System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00010] in <26aedeede9534b948c539f8734c8492d>:0
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].TestConnection () [0x0000e] in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:325

17-11-16 14:51:17.8|Warn|NzbDroneErrorPipeline|Invalid request Validation failed:
 -- Unable to connect to indexer, check the log for more details
17-11-16 14:51:17.8|Debug|Api|[POST] /api/indexer/test: 400.BadRequest (164 ms)

**Comment by fluxtendu** [comment]
Same problem on my side.
I don't have issue with all other jackett 0.8.402.0 indexers I have tested and I can add the jackett  YGGtorrent indexer on sonarr 2.0.0.5054 .

**Comment by tcheronneau** [comment]
Hi, same here. Jackett Version 0.8.402.0. Radarr : 0.2.0.870 (tried also with 0.2.0.852). 
Working with sonarr too.

**Comment by jrozelle** [comment]
Yes, it's the same behavior !

**Comment by galli-leo** [comment]
This is the case when the indexer does not support searching by imdbid. Either tell the maintainer of the Indexer to fix it or Disable Searching, Add the indexer, then enable searching.

**Comment by jrozelle** [comment]
Thank you !

**Comment by jimsaye** [comment]
Thank's , now i can had ygg but the search does not work.

TTP Error - Res: [GET] https://(removed)/api/v2.0/indexers/yggtorrent/results/torznab/api?t=search&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060&extended=1&apikey=(removed)&offset=0&limit=100&q=amityville%20horror%20lost%20tapes%202017: 400.BadRequest
<Error><Message>yggtorrent does not support the requested query.</Message></Error>
