### ISSUE TITLE
File Management Issue - Modified Date Times Are In The Future?

### ISSUE THREAD

**Issue by ghost** [Radarr/Radarr#2272]
When using the file management feature to copy files to a specific location (after download completes), the modified date times of the files are in the future by about 6 hours?  Created and Accessed times are correct.

**Radarr Version:**  0.2.0.870

**Logs:**  https://pastebin.com/Va6JRbkS

**Comment by galli-leo** [comment]
Since we don't change the file date unless you tell radarr too (e.g. Cinemas Date or Physical Release Date), it must be some other application doing it. (Or maybe windows / mono is just being funny?)
