### ISSUE TITLE
Radarr wont delete lower quality files

### ISSUE THREAD

**Issue by smaiderman** [Radarr/Radarr#2274]
Hello there. 
First of all, thank you for the project.

I have an issue:
Radarr is not deleting lower quality files when it downloads a better one.

How can I configure it to remove lower quality files?

Thanks!

**Radarr Version:**
Radarr Ver. 0.2.0.870
develop

**Logs:**

EDIT:
Just found that it deletes the files in the "history" tab, but the files are still there.
I don't have a log.

**Comment by PeterFragon** [comment]
Yes it needs to delete movies replaced by cutoff quality etc..

**Comment by smaiderman** [comment]
Yes, I know. But it doesn't

**Comment by galli-leo** [comment]
Try enabling debug logging, since without I wont be able to help. If it deletes the file in the history tab, but it's still there, it could be permissions issue.
