### ISSUE TITLE
Issues with logs with different browsers

### ISSUE THREAD

**Issue by nzbtuxnews** [Radarr/Radarr#2276]
Using Firefox 55 on Linux Mint 17

In Radarr when I go to the logs section (table) I see nothing except the four gray/black dots dancing around indefinitely.  The only way to see the logs is to click on "Files" to see "radarr.txt".

Using Chromium 62.0.3202.62 55 on Linux Mint 17

The table section of the logs works, but the button "Clear logs" doesnt.  When I click on it it grays out with a spinning circle of dots and never finishes.

Radarr Ver. 0.2.0.870

**Comment by hotio** [comment]
You having an adblocker active?
