### ISSUE TITLE
TMDb Include Genre Ids

### ISSUE THREAD

**Issue by crhammock** [Radarr/Radarr#2278]
In the TMDb lists options for Include Genre Ids (and Exclude Genre Ids).  It specifies that the genres should be comma separated however comma separated means a logical AND statement which means a film must belong to all of the listed genres to make the list.  However testing with the TMDb API shows that separating Genres with a pipe "|" will mean a logical OR statement is used and so the list will include any movies from one of the listed genres.  However the textbox within the App only allows commas to be used.

I suggest this is changed to allow the pipe "|" also and the help is updated to reflect this.

Check first that your problem is not listed in our wiki section:
* https://github.com/Radarr/Radarr/wiki/Common-Problems
* https://github.com/Radarr/Radarr/wiki/FAQ

Provide a description of the feature request or bug here, the more details the better. 
Please also try to include the following if you are reporting a bug

**Radarr Version: 0.2.0.870**

**Logs: None**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by crhammock** [comment]
Just in case it helps below is the API call made by Radarr using comma separated genre IDs

`https://api.themoviedb.org/3/discover/movie?api_key=1a7373301961d03f97f853a876dd1212&primary_release_date.gte=2017-11-19&primary_release_date.lte=2018-02-19&with_genres=28,35,878&without_genres=10749&with_original_language=en&page=1`

The below is the same call using pipe separated Genre IDs

`https://api.themoviedb.org/3/discover/movie?api_key=1a7373301961d03f97f853a876dd1212&primary_release_date.gte=2017-11-19&primary_release_date.lte=2018-02-19&with_genres=28|35|878&without_genres=10749&with_original_language=en&page=1`

Obviously the latter returns more values as it is looking for movies containing any of the genre IDs rather than all of the genre IDs like the first call.

It seems that TMDb API is rather advanced.  Would it be possible to add an advnaced option in the in the TMDb list so you can free hand your API calls including using your own API key so you can query things such as your watchlist or private lists etc?

**Comment by galli-leo** [comment]
I could take a look at that.

**Comment by crhammock** [comment]
Many Thanks, let me know if you need any assistance with testing or troubleshooting further.

While you are looking at the code for API calls I also notice that when trying to add an RSS List Preset for IMDB Watchlist it fails with a log which says 404 error.  Although I haven't yet done a PCAP, my firewall suggests the connection was completed successfully and when I attempt to access the URL by copy and pasting from the radarr.txt log it responds fine with the correct content and no errors.

**Comment by galli-leo** [comment]
RSS Lists are deprecated. Try using Radarr lists instead.

**Comment by crhammock** [comment]
Thanks galli-leo, I have taken a look in the WIKI and found the query for IMDB watchlists path as /imdb/list?listId=ur1236576 (which looks a little wrong).  I tried this (replacing with my userID) but still got an error.  However I don't want to detract from the original request.  I will raise this as a separate issue to avoid confusion.  Please let me know when the TMDb pipe characters are ready to be tested.

**Comment by crhammock** [comment]
Just update to 0.2.0.910.  Still can't define pipes in between Genre Tags.  Any idea when this maybe implemented?

Thanks
