### ISSUE TITLE
TorrentPotato TBP BadRequest

### ISSUE THREAD

**Issue by vaxo101** [Radarr/Radarr#2281]
Have linked up Radarr with TPB TorrentPotato indexer in Jackett.
When testing indexer in Radarr it tests correctly, however when searching for a specific title it will push out an error:

> HTTP Error - Res: [GET] http://localhost:9117/api/v2.0/indexers/thepiratebay/results/potato/?passkey=(removed)&user=&imdbid=tt1790809.400.BadRequest{Message":"thepiratebay does not support the requested query."}

**Actions taken to resolve**
- Confirmed Jackett can do a manual search inside the provided admin dashboard

Performing the above action to me makes me think that this may be more related with Radarr.

**Comment by hotio** [comment]
My guess: tpb does not support searching by imdbid

**Comment by galli-leo** [comment]
TorrentPotato is not supported anymore. Please use torznab
