### ISSUE TITLE
HC Releases categorised as WEBDL720p

### ISSUE THREAD

**Issue by matmuilwijk** [Radarr/Radarr#2282]
**Description:**
Even though I have the option open to download HC releases, they're categorized as WEBDL's, and not HC's. I think this is because releases used to be called Movie.Name.HC.HDRIP.720p.Releasegroup.mkv what changed to be Movie.Name.720p.HC.HDRIP.mkv.

Any way to fix this? This kind of ruins my automation, since releases are now meeting cutoff with just a premature, mostly not that elegant quality, HC-release. 

**Radarr Version:**
0.2.0.870
**Logs:**

**Comment by galli-leo** [comment]
But these are WEBDL's aren't they? I am working on a system where you could make HC releases considered lower than other WEBDL's but there's an issue open for this already.
