### ISSUE TITLE
Radarr not connecting with AHD anymore

### ISSUE THREAD

**Issue by king8084** [Radarr/Radarr#2283]
i did not change anything from my side, but radarr stopped connecting with AHD, giving not connecting error

**Comment by king8084** [comment]
tho it keep giving me failure message in system, it actually appears in the searching so i guess its fine?

kinda annoying to keeping seeing the (1) tho

**Comment by matmuilwijk** [comment]
Tried to do a manual health check from the Tasks tab? This usually works for me when TPB has been down for a few hours... It only checks health once every 6 hours, and I'm also annoyed by notification-numbers...

**Comment by galli-leo** [comment]
Can you post some logs? Maybe it had a short period where it failed, and it just takes it time to update the health checks.

**Comment by galli-leo** [comment]
@king8084 Sorry for the orthodox way of contacting you :P, but I don't know of any other way. Does the AHD API give any info on whether a release is internal or not / what makes an AHD release internal?

**Comment by king8084** [comment]
you can leave me your email and i can email you if you want

but i will ask im not sure if their api does that, i just checked few movies marked internal in their site but not on radarr

**Comment by king8084** [comment]
follow up: quick search on their forums says that any 75% freeleech on any movie means its Internal Encodes and 50% for Internal/User Remuxes.
