### ISSUE TITLE
Edition Tags Optimization

### ISSUE THREAD

**Issue by Ashkaan** [Radarr/Radarr#2284]
Can we make Edition Tags only apply when the movie is non-normal?

For example, all of my movies look like this:

Dune (1984) [].Bluray-1080.mkv
Dune (1984) [Extended Edition].Bluray-1080.mkv

They should look like:

Dune (1984).Bluray-1080.mkv
Dune (1984) [Extended Edition].Bluray-1080.mkv

Thanks

**Comment by hotio** [comment]
Use the correct way to add the tag.

```
{[EDITION TAGS]}
```
