### ISSUE TITLE
Ability to view more than 10 movies at a time in movie editor [Feature Request]

### ISSUE THREAD

**Issue by shpanky73** [Radarr/Radarr#2285]
**Description**

Add a drop-down that increases the number of movies shown at a time in the movie editor.  Currently, we see only 10 at a time.  Please add a drop-down that includes 10, 20, 50, 100 movies in a list view.

**Comment by galli-leo** [comment]
Settings -> UI -> Page Size

**Comment by shpanky73** [comment]
This only works for the main page...not the movie editor.

**Comment by galli-leo** [comment]
It works for the movie editor for me

**Comment by galli-leo** [comment]
Try clearing cache and cookies
