### ISSUE TITLE
Movies not yet in cinemas "Missing, Monitored and considered Available"

### ISSUE THREAD

**Issue by dannyt66** [Radarr/Radarr#2286]
The movie "Star Wars: The Last Jedi" is being shown by Radarr as "Missing, Monitored and considered Available" despite not being yet in cinemas. This is acknowledged by Radarr, which correctly shows "In Cinemas: December 2017". 

**Radarr Version:**
0.2.0.870

**Comment by galli-leo** [comment]
What minimum availability did you set?

**Comment by dannyt66** [comment]
Sorry for the delay. Apparently I'd set the minimum as Announced, hence this issue. Apologies for taking up your time. Fixed by correctly setting the minimum availability.
