### ISSUE TITLE
When Importing Movie From Cloud Storage It Is Downloaded Even If Analyse Is Disabled

### ISSUE THREAD

**Issue by rrbailey89** [Radarr/Radarr#2287]
**Description:**
When importing a movie that is on cloud storage (probably local one too) the file is downloaded even if analyze is not enabled. This behavior is not expected since Sonarr does not do this.

Check first that your problem is not listed in our wiki section:
* https://github.com/Radarr/Radarr/wiki/Common-Problems
* https://github.com/Radarr/Radarr/wiki/FAQ

Provide a description of the feature request or bug here, the more details the better. 
Please also try to include the following if you are reporting a bug

**Radarr Version:**
0.2.0.870
**Logs:**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by galli-leo** [comment]
With importing do you mean manual import / import a finished download / bulk importing?

**Comment by jtrott** [comment]
I have this same issue on bulk import.

Radarr Version:
0.2.0.910

**Comment by rrbailey89** [comment]
I meant any sort of import, manual or bulk

**Comment by galli-leo** [comment]
Duplicate of #1328
