### ISSUE TITLE
[Feature Request] Add support for labelplus plugin in Deluge as well as current "label" plugin

### ISSUE THREAD

**Issue by Panderine** [Radarr/Radarr#2288]
Radarr only works with deluge categories if you have "label" plugin enabled.  I wan't to use "labelplus" plugin instead (since I cannot set share ratio to 0 on standard "label" plugin thus radarr never deletes my downloads). 

Labelplus plugin allows me to set it to 0 (plus a bunch of other stuff like sub categories, dynamic labels for regex, etc.)  as well as the basic "label plugin" functionality. So regarding radarr categories, labelplus plugin should be equally fine. 

Is this doable? or is a major overhaul??

**Comment by Panderine** [comment]
FYI. Anybody wanting to set share ratio to 0 using the default "label" plugin can do so, editing the label.conf file by hand (not using GUI). For each label change "stop_ratio": 0,

**Comment by galli-leo** [comment]
Not really sure what we would have to do. Isn't there an option to set the same labelplus label when the torrent has a label from the default label package?

**Comment by Panderine** [comment]
You mean on deluge? You can have the same label but im nota sure who
manages what. Ill test and report back.

**Comment by jOOc** [comment]
@Panderine I have only the label plugin and it works for me.
Just right click the label and choose label option, then set the ratio to 0 and remove at ratio.
![image](https://user-images.githubusercontent.com/9382342/34020681-e4eabf7a-e135-11e7-8f62-d69c84e8a00f.png)
