### ISSUE TITLE
Re-implement Priority in download clients

### ISSUE THREAD

**Issue by onedr0p** [Radarr/Radarr#229]
(Maybe we don't need to, does anyone find this useful for adding movies to your download clients (the ones that support it)?)

Definitely planning on implementing this, once I get around to it.

**Comment by fryfrog** [comment]
Yes, upping the priority on new content is helpful in combatting DMCA take downs. If your queue is full, you'd generally want to download the newest stuff first.

**Comment by jamma007** [comment]
I agree,  there is a need to download newer stuff first vs items that you are downloading to backfill content/adding old movies

**Comment by kieranlee1970** [comment]
I agree - I see currently that if you set priority as high for recent, it sets it high for all - priority adjustments means you can not only priorities new vs old movies but also those movies relative TV if you are using the client for TV and other content also

**Comment by Hossy** [comment]
I agree with @kieranlee1970.  I'm using sonarr and radarr and with "recent" set to high, all movie downloads get priority over sonarr.  Recent movies should definitely be prioritized over non-recent like @fryfrog suggested.  Not just for usenet, but torrent age/seed availability too.

**Comment by SgtBatten** [comment]
Sorry I missed this open one.

I am all for this being implemented if it can be.

My use case is that I get unlimited downloads in a 6 hour window each day and I want to force all my "backfill" content to low priority which sabnzbd limits to downloading in that window.
New releases I still want to download asap for DMCA reasons as stated by others above.

**Comment by ladude626** [comment]
I routine use priorities frequently for NZBGet but would love to have it on ruTorrent and Deluge! Thanks.

**Comment by desimaniac** [comment]
+1 for this feature.

**Comment by cdemi** [comment]
Just another +1 :)

**Comment by kalyway** [comment]
Yes, definitely still an issue for me as well. I add movies from lists and everything gets high priority. Not JUST the movies that have recently aired/been released within the last 14 days. If it could work where movies released via Physical release (or most recent moves) get High priority than that would be great.

At the moment, everything gets it in radarr...
