### ISSUE TITLE
System.DllNotFoundException: libmediainfo.so.0 on Fedora 26 error refers to a windows location.

### ISSUE THREAD

**Issue by thisbejeffe** [Radarr/Radarr#2293]
I just started seeing libmediainfo.so.0 over the last week. I am running Fedora 26 and noticed the error is referring to a windows directory structure. I confirmed libmediainfo is installed and up to date. I do not see this issue in Sonarr.

Radarr set to develop
Version
0.2.0.870
Mono Version
4.8.0 (Stable 4.8.0.520/8f6d0f6 Wed Mar 15 15:23:40 UTC 2017)

Details
Message
mediainfo is required but was not found: libmediainfo.so.0

Exception
System.DllNotFoundException: libmediainfo.so.0
  at (wrapper managed-to-native) NzbDrone.Core.MediaFiles.MediaInfo.MediaInfo:MediaInfo_New ()
  at NzbDrone.Core.MediaFiles.MediaInfo.MediaInfo..ctor () [0x00006] in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\MediaInfo\MediaInfoLib.cs:69 
  at NzbDrone.Core.MediaFiles.MediaInfo.VideoFileInfoReader.GetMediaInfo (System.String filename) [0x00021] in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\MediaInfo\VideoFileInfoReader.cs:39

**Comment by galli-leo** [comment]
The windows dir structure is just where the error occurs. Has nothing to do with the os Radarr runs on. Make sure libmediainfo is in a path where radarr can see it. Maybe it’s permission issues?

**Comment by thisbejeffe** [comment]
Looks like doing my system updates libmediainfo.so.0 was upgraded in libmediainfo-17.10-1.fc26.x86_64 from libmediainfo-0.7.96-1.fc26.i686. This can be closed. Thanks for your response galli-leo.

**Comment by galli-leo** [comment]
What are the permissions on the file?

**Comment by thisbejeffe** [comment]
ya I was able to resolve late last night by uninstalling the newer version
of libmediainfo and reinstalling the old version. However I like your fix
better just using a symlink.

On Nov 29, 2017 8:44 AM, "tazmad" <notifications@github.com> wrote:

I had the same issue (running the same OS too) - noticed that I only had
libmediainfo.so.17 and libmediainfo.so.17.10 in /usr/lib64. Created a
symlink for libmediainfo.so.0 to the libmediainfo.so.17 and the error went
away. Hope that helps!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Radarr/Radarr/issues/2293#issuecomment-347921171>, or mute
the thread
