### ISSUE TITLE
Treat RAR as movie

### ISSUE THREAD

**Issue by rubdos** [Radarr/Radarr#2296]
**Description:**

Certain Scene distributes their content as a set of RAR archives (i.e., `.rar` + `.r01` + `.r02` + ... + `.rxx`). Certain media players (Kodi) play RAR files as is; *it treats them as video*.

Currently, I have a script in the downloader that unpacks the `.rar` archives immediately after download. However, it would be nice if the archives were just hardlinked to the Kodi directory, since this  **saves a lot** of hard drive space (i.e. unpacking *doubles* the amount of disk usage).

**References:**

Sickrage has a [broken](https://github.com/SickRage/SickRage/issues/3674) [implementation](https://github.com/SickRage/SickRage/pull/3271) of this; it only links the `.rar` and not its successors.

Note that this feature request is different from #1771, since that requests unpacking of RARs inside Radarr.

Note that usually, the sequence `.rar` + `.r01` + `.r02` + ... + `.rxx` is used, however, I have seen releases that use `.part01.rar` + `.part02.rar` + ... + `.partxx.rar`.

[AB#862](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/862)

**Comment by galli-leo** [comment]
Probably won't happen in the near future.

**Comment by DjRicko** [comment]
Indeed would be nice to have an option that just moves any scene release untouched, the whole directory and treats it correctly as downloaded, even tho it's in rars. Both Kodi and Plex have ways to play directly from rars, so absolutely no point in unrar'ing, just to have to re-rar (using rescene and srr) if you have to reupload at some point in original form.

**Comment by fryfrog** [comment]
I didn't know Plex could do it, or are you talking about pairing it w/ something like rarfs?

I don't think this is likely in either Sonarr or Radarr because they make a lot of use of `mediainfo` and it probably doesn't poke into `.rar` files.

**Comment by rubdos** [comment]
> I don't think this is likely in either Sonarr or Radarr because they make a lot of use of mediainfo and it probably doesn't poke into .rar files.

That's exactly what this issue is about: finding out what needs to be done for Sonarr and Radarr to support this.

**Comment by fryfrog** [comment]
Wait, like you're going to work on the feature? That'd be fantastic! How would you imagine it working in Sonarr, where the episodes are all in one season folder at best or just in one folder at worst? Just a big hot mess of `.rar` files?

**Comment by rubdos** [comment]
> Wait, like you're going to work on the feature?

No, I don't have time nor enough C# experience. If the `mediainfo` util needs help (which is in C(++) I think), I could help out a bit.

> That'd be fantastic!

Yes :-)

> How would you imagine it working in Sonarr, where the episodes are all in one season folder at best or just in one folder at worst? Just a big hot mess of `.rar` files?

Honestly, for me that'd be enough, and I imagine any sane person that stores `.rar`'s instead of extracts to think the same. Those people use Kodi/Plex/whatever as their media center anyway, no?

**Comment by fryfrog** [comment]
I concur. I've also only ever seen Kodi users care about reading from `.rar` files. I don't know how you get it working in Plex or if it is even possible.

But unless some developer takes an interest in this super niche feature... it seems unlikely it'll happen. In the two years since it was created, learning .NET would have been feasible. :)

**Comment by rubdos** [comment]
> I concur. I've also only ever seen Kodi users care about reading from `.rar` files. I don't know how you get it working in Plex or if it is even possible.

Wouldn't know, it's the first time I hear that Plex would do it too. I feel like Kodi users usually are a bit more technically inclined, since Kodi's main appeal is its customizability.

> But unless some developer takes an interest in this super niche feature... it seems unlikely it'll happen. In the two years since it was created, learning .NET would have been feasible. :)

Fair point. Please keep this open though. When I start being really annoyed by it, I might as well learn .NET. Note that one of my first programming languages was C# with .NET, but that's like 10 years ago. In the previous 10 years, I *unlearned* .NET :-)

**Comment by rubdos** [comment]
Another year passed, but I think some things changed. #4534 is coming up and #809 is more-or-less fixed. Both should give me enough inspiration to fix this issue eventually.
