### ISSUE TITLE
Downloads are left in ProgramData\Radarr\bin

### ISSUE THREAD

**Issue by BO45** [Radarr/Radarr#2297]
My downloader (sabnzbd) and Radarr (0.2.870) reside on the same machine. 
Most of the downloads (some make it) end up in ProgramData\Radarr\bin and aren't copied into my movies folder.

**Comment by galli-leo** [comment]
Are the paths for the movies correctly set in Radarr?

**Comment by BO45** [comment]
As far as I can see they are set by the movies category / path of sabnzbd. Where would I set additional movie paths?

**Comment by galli-leo** [comment]
When you open the details page to a movie, you can set the movie path by editing the movie (via the wrench icon). Seems like you have a list configured with an empty path. Thus try changing the path for the list.

**Comment by BO45** [comment]
Thanks that did the trick. The path entry was empty.
