### ISSUE TITLE
[Bug] page size option not saving

### ISSUE THREAD

**Issue by zero77** [Radarr/Radarr#2301]
Whenever I set the page size option to something different, after the browser is restarted, the option is reset to default.

**Comment by galli-leo** [comment]
Are you using incognito mode?

**Comment by zero77** [comment]
No but, i use some firefox addons to clear cookies.

**Comment by galli-leo** [comment]
Well thats the issue then. Radarr stores that info in local application storage which will be cleared by that extension.
