### ISSUE TITLE
Preferred tags not working ?

### ISSUE THREAD

**Issue by alxdc9** [Radarr/Radarr#2303]
**Description:**
My profiles are all using a single preferred tag 'multi' in order to download multi + VF instead of VF only.

However, it quite often downloads a VF only version while a multi version was available.

Here is what my profiles look like:
![image](https://user-images.githubusercontent.com/33397242/33479818-c6e86808-d68e-11e7-8b46-982146e76534.png)

With this profile, how would radarr behave if it finds a Bluray-720p release without multi and a Bluray-1080p release with multi ? Will it download the 720p version as it is higher in the list and thus ignore the multi preferred tag ?

**Radarr Version:**
Version
    0.2.0.870
Mono Version
    5.4.1.6 (tarball Wed Nov 8 20:37:08 UTC 2017)

**Comment by galli-leo** [comment]
It will download the Bluray-720p since it is highest.
