### ISSUE TITLE
Bluray-1080p Quality Bluray Profile

### ISSUE THREAD

**Issue by kevindd992002** [Radarr/Radarr#2304]
**Description:** I'm using Plex and it doesn't recognized ISO or BDMV folders. I want the highest quality MKV file for my downloads (usually Remux 1080p or Bluray-1080p non-BDMV). I removed BR-Disk from my quality profile so ISO's won't be a problem. Now for Bluray-1080p, its default quality definition is up to "Unlimited" which means Radarr will still pickup BDMV downloads if available. 

What limit should I set the Bluray-1080p quality definition to so that I can avoid BDMV releases?

**Radarr Version:** 0.2.0.870

**Logs:** N/A

**Comment by kevindd992002** [comment]
BUMP!

**Comment by galli-leo** [comment]
Depends, I would set them at around 20GB depending on what max quality you want for your releases. You can also try setting your downloader to cancel downloads with bdmv folders & iso files.

**Comment by kevindd992002** [comment]
Sorry for the very late response since I was on a vacation. Do you know of any way on how to set SAB to do the cancellation? I was checking the different options available to me in SAB and all it checks are extensions. So an ISO can be ignored but not a BDMV folder. Any ideas?

**Comment by galli-leo** [comment]
BDMV folders usually have .mt2s files in them. So you could block that. Try browsing the wiki, I rember seeing a post about that there.
