### ISSUE TITLE
[Feature] Add tags to movies according to list membership

### ISSUE THREAD

**Issue by tomHaum** [Radarr/Radarr#2306]
I think it would be nice right now to be able to add tags to movies based on what list they are a part of. 

So for example I have two lists, "Denzel Washington movies" and "Chloë Grace Moretz Movies." and they have the tags of "Denzel" and "Chloë" respectively. So Fences would only get the "Denzel" tag and Kick-ass would get the "Chloë" tag but The Equalizer would be tagged with both "Chloë" and "Denzel"

I mostly want to do this because right now I have it set up that I monitor a bunch of my friends IMDB watch lists and I want to be able to send them personal notifications when their movie is added downloaded. 

I know that is probably overlaps with the end result of using PlexRequests or some other app but it seems like a nice way to make tags a bit more robust.

I am going to try to look into implementing this myself, but I want some input on whether or not this sounds useful to anyone else.

**Comment by CurtisFeatures** [comment]
I would also like this feature so i can email people bases on movies that have been downloaded from their own IMDB watch list.

**Comment by foux** [comment]
Clearly want that 👍

**Comment by raspdealer** [comment]
+1

**Comment by galli-leo** [comment]
Instead of comments like me too or +1, please use the thumbs up emojis on the top most comment. (This way my notification feed isn’t cluttered 😬)

**Comment by drwyrm** [comment]
It would be great to have the ability to tag also depending on indexer. Indexer+list tagging would make tag restrictions very useful.

**Comment by pbrink231** [comment]
As an addon to this.  Possibly have an icon to say which list added the movie to radarr if it was added by a list.

**Comment by Qstick** [comment]
This is done
