### ISSUE TITLE
Synology Download Station Will Not Connect

### ISSUE THREAD

**Issue by Ltek** [Radarr/Radarr#2309]
I just installed Radarr for the first time on my Synology NAS.

I also have both CouchPotato & Sonarr for many years and they work fine with my Syno DS app.  I'm using the exact settings in all apps to connect to DS.  

With both Sonarr & CP I'm using port 5000, not SSL. With Radarr I tried both normal & SSL (port 5000 & 5001) and I always get these errors (at the same time)...

Failed to get the list of torrents: Failed to login. Reason: No such account or incorrect password
Unknown exception: Failed to login. Reason: No such account or incorrect password

Does this work or is it broken / know issue?

thx

**Comment by stevekr** [comment]
You need to login to DSM with same user and set default download folder in DS.
