### ISSUE TITLE
Bulk Import does not find movies for one folder, works on another just fine

### ISSUE THREAD

**Issue by Ltek** [Radarr/Radarr#2310]
Just installed Radarr for first time.

I added 2 folders to the 'Movies' using "Bulk Import" . Both folders are on the NAS where Radarr is running and the account has admin rights on both folders

I added 
/volume1/movies/
and
/volume1/kids movies/

'kids movies' works perfectly, importing all 173 movies.

Several tried, even restarted Radarr but 'movies' throws this error...
"No movies found in folder /volume1/movies/. Have you already added all of them?"
... there are 205 movies in this folder.

the folder permissions are fine as Couch Potato has recently moved several movies there.

thx for the help!

**Comment by matmuilwijk** [comment]
Are the movies in sub-folders? Otherwise Radarr won't be able to see/handle them. Ran into the same issue while starting for the first time on Radarr. Used Filebot to put everything in subfolders, and worked like a charm! (And, most media-players like Kodi/Plex/Emby don't have any issues with this additional structure)

**Comment by Ltek** [comment]
Each movie is in its own folder. 

@galli-leo  ... This looks like a bug. I dont see any reason why it works on the folder 'Kids Movies' and not 'Movies' ... they have the exact same perms

please let me know. trace log attached
[radarr.trace.txt](https://github.com/Radarr/Radarr/files/1544284/radarr.trace.txt)

**Comment by galli-leo** [comment]
Seems like there is a recycle folder in /volume1/movies which causes an error: System.UnauthorizedAccessException: Access to the path "/volume1/movies/#recycle" is denied.

Try either deleting that folder or giving Radarr the correct permissions.
