### ISSUE TITLE
Monitoring ALL Movies after Bulk Import?  How to disable this?

### ISSUE THREAD

**Issue by Ltek** [Radarr/Radarr#2313]
I did a bulk import and it is now monitoring ALL my movies - which makes no sense since all the movies already are in the folders.

How can I select all 170+ movies and tell Radarr to NOT monitor them?

thx

**Comment by Droidem** [comment]
open up the movies tab and then select "Movie Editor." Select the ones you want to change, and at the bottom of the screen, you can change the Monitored Status, Min Availability, Profile, Static path and the Root Folder all at once. Give it time after you select it depending on how many files you are changing.
