### ISSUE TITLE
Manual Import Search/Sort Issue

### ISSUE THREAD

**Issue by DrSeussFreak** [Radarr/Radarr#2315]
**Description:**

If you go to the manual import page and select a directory with a movie in it.   When you select that file, and you try and pick the the corresponding movie (since it does not seem to auto-detect the movie for you), the list of every movie in your collection comes up, and you cannot sort by name.  Also, if you try to search by entering the moving name in the field, nothing happens.

I have tried this on multiple browsers on different laptops (all OSX 10.11 or 10.12)

**Radarr Version:**

0.2.0.870

**Comment by hotio** [comment]
try the latest build

**Comment by DrSeussFreak** [comment]
so, I am running this on Windows, and do not see any update available

**Comment by galli-leo** [comment]
It's only on nightly branch. But it's fixed there.
