### ISSUE TITLE
Few issues with bulk import and renaming feature

### ISSUE THREAD

**Issue by steve1977** [Radarr/Radarr#2317]
I have a few issues with Radarr:

1) I downloaded "Mein.Blind.Date.mit.dem.Leben.2017.1080p.BluRay.DTS.x264-E1" through Radarr/Sabnzbd+. It was directly put through Radarr into the download queue and download compeleted. Unfortunately, it wasn't "processed". Probably some issue around the name. What I really struggle with though is how to manually add it. Relabel myself or not? How to mark it completed? How to avoid it being downloaded again? How to secure higher quality levels still being uploaded? etc. The routine for these cases is not clear to me.

2) I also struggle with language. It changes folder and file name to the original movie name. Possible to select what language it will be relabeled. Some movies show in Japanese characters now, which is a part irritating.

3) Is there a function that allows to spot movies that are in the Radarr "library" (list of movies), but have been deleted since adding. Or manually renamed after adding.  I have some cases and this is quite an annoyance.

Thanks again for the development. This is really great!

**Comment by hotio** [comment]
1) manual import
2) try changing the language in radarr movie settings.
3) showing missing and available on the wanted tab gives a rough version, but it is not what you want exactly.

**Comment by steve1977** [comment]
Big thanks for your quick reply.

re 2 - it's set to English. The issue is that I still have some non-English movies. When Radarr renames the folder and file, it uses the original movie name from IMDB (not the English name).

re 3 - indeed not what I am looking for. I am talking about the example that I add a movie to Radarr, it downloads it and is then part of the movie list (not wanted as the movie is downloaded already). When I am now manually deleting the file (not in Radarr, but in the movie list). I'd like to either have the movie be removed from the list in Radarr or change status to "missing" or "wanted" or something like this.

**Comment by steve1977** [comment]
re 1 - what is the feature to manually import? I tried to use "bulk-import", but it is greyed out. Is there a dedicated feature to manually import in radarr?

**Comment by ludoloco** [comment]
I have also have some issues with auto processing movies. Radarr tracks the movie just fine, but won't automatictly rename and copy to the destination folder. Mostly they are foreign movies like 'The.Spirit.Of.The.Beehive.1973.1080p.BluRay.x264.DTS-SARTRE.mkv' wich translates to 'El espíritu de la colmena' as original title. Or the other way around 'El.Faro.De.Las.Orcas.2016.FRENCH.720p.WEBRip.x264-BRiNK' wich translates to 'The Lighthouse Of The Orcas' as displayed english title.

Of course you can manual import them (Wanted->Manual Import), but that is just a work around, they issue still remains.

**Comment by steve1977** [comment]
i think there is a separate bug report that radarr follows a different logic picking up movies from indexers versus identifying the movie in the download queue. this should address your issue.

my first one may not be a bug thoug, but i may not be familiar enough with radarr. how do you use manual import? i didnt find it and bulk-import didn’t work. i just went ahead and copied the file over from my download folder to my movie folder manually. issue is that i still keep getting error messages in radarr of not finding the file in download folder. do i now have to delete the file?

i did some digging. it looks #2 should be a feature request. it’s not yet possible to set a different language for individual movies or to change the renaming language away from “original language”.

#3 is my biggest issue. i renamed some movie folders or deleted some movie folders. how do i make sure radarr “knows” this?

**Comment by ludoloco** [comment]
@steve1977
- "bulk-import" is for importing movies into the library that already have been processed/renamed and are **not** listed in your current "radarr library".
- "manual-import" is for movies that **are** listed in your current library but are missing from disk. (Wanted->Manual Import)

**Comment by steve1977** [comment]
Thanks. Not sure I fully understand though:

* When you refer to radarr library, do you mean the movie folder or the radarr movie list (incl. all movies incl. missing, wanted, etc.)

* If I have a movie in my download folder that has not been renamed and not moved to my movie folder yet, what would I use? Does "manual import" move the file to the movie folder and renames it?

* I have some files that are not in my radarr movie library yet, but I manually moved into the movie folder. These are already nicely named, but sometimes don't 100% follow the renaming of radarr (e.g., renaming was historically done by CP that follows different renaming convention). When I use bulk-import, it renames them again, but only moves the movie folder (not the metadata associated with it). I have a lot of movies, so this will take ages

* What exactly is what Radarr calls "missing"? I am looking for a way to identify movies that are no longer in my movie folder, but still in my radarr library (e.g., I deleted a movie folder manually)

**Comment by ludoloco** [comment]
@steve1977 

- Radarr movie list
- Manual import; it will rename the file/folder and copy from the download folder to the destination folder
- I did recently moved from CP to Radarr and noticed that some movies were copied to new folders by the rules off the Radarr renamer. Most of my movies (around 250) were already the right format, so it wasn't a real problem for me. Maybe if you check "settings->media management->movie naming" (with advanced settings: show) and set "movie folder format" to what your movie folders look like now, it will not copy them to new ones?! Movie files imported this way were not renamed.
- "missing" is no movies files on disk (in the folder that is set for the movies, you can check this at the movie->edit movie. Also check at settings->media management->file management->ignore deleted movies, if set "yes" it will remove the movie from radarr's library/list if the folder is not found.
