### ISSUE TITLE
Incorrect image for movie

### ISSUE THREAD

**Issue by dpyy** [Radarr/Radarr#2318]
**Description:**
For some reason the movie poster does not match the movie

**Radarr Version:**
0.2.0.870

<img width="1224" alt="screen shot 2017-12-05 at 9 39 58 pm" src="https://user-images.githubusercontent.com/19830772/33641761-e24e6cfe-da04-11e7-9672-b99458c8e26f.png">

**Comment by hotio** [comment]
try an incognito window.

**Comment by galli-leo** [comment]
You might also try deleting the image under AppDataDir/MediaCovers

**Comment by dpyy** [comment]
I already deleted .config in my mac user and reinstalled radarr, same thing.

**Comment by galli-leo** [comment]
@dpyy Definitely a caching issue then.
