### ISSUE TITLE
Download problems

### ISSUE THREAD

**Issue by Specimen1334** [Radarr/Radarr#2319]
**Radarr Version: 0.2.0.870**
Hi there,
So i've run into a problem.
My radarr wont auto-download things, i have to manually select the movie and hit download.
Yes similar to many other posts and not that much of a problem really, BUT here is where it gets annoying.
After every approx 4 downloads it just stops working, it says that there are not files for any of the movies i want, even when i go in and take a look in the search section within each movie, it says no files exist, so i go to indexers and test them, success, so i go back and now that same movie suddenly appears and is working again and will download... about 4 or 5 downloads later it does the same thing and so yeah.. i constantly have to go back and retest the indexer to get it to reactivate, otherwise it says it searches but instantly comes back with nothing rather than taking a few moments and finding stuff.

Any ideas?
I have searched through the log and there is nothing of help in there, just says search no results found for each movie it was supposed to be searching for and nothing else, not even the usual other stuff.

**Comment by hotio** [comment]
Not a lot of info to work with, but try doing the api calls manually to see if your indexer is rate limiting you.

**Comment by undead9786** [comment]
Same exact issue. I noticed that if I search and get no results anything I search after that then immediately gets the same results. If I go back to the Indexer, test it, then go back and search for it manually I see results (but not the original one that shows no results as there were actually no results).

**Comment by galli-leo** [comment]
Enable trace logging, search and post those logs.

**Comment by Specimen1334** [comment]
Apologies for the slow response have had a busy few days.
i was unsure exactly how to present the log results, so i just copied them.

  | Component | Message | Time
-- | -- | -- | --
  | MovieSearchService | Movie search completed. 0 reports downloaded. | 11:31am
  | DownloadDecisionMaker | No results found | 11:31am
  | NzbSearchService | Searching 0 indexers for [Passengers] | 11:31am
  | DownloadDecisionMaker | No results found | 11:31am
  | NzbSearchService | Searching 0 indexers for [Van Helsing] | 11:31am
  | DownloadDecisionMaker | No results found | 11:31am
  | NzbSearchService | Searching 0 indexers for [Star Trek Beyond] | 11:31am
  | DownloadDecisionMaker | No results found | 11:31am
  | NzbSearchService | Searching 0 indexers for [Warcraft] | 11:31am
  | DownloadDecisionMaker | No results found | 11:31am
  | NzbSearchService | Searching 0 indexers for [Night Guards] | 11:31am
  | DownloadDecisionMaker | No results found | 11:31am
  | NzbSearchService | Searching 0 indexers for [Power Rangers] | 11:31am
  | DownloadDecisionMaker | No results found | 11:31am
  | NzbSearchService | Searching 0 indexers for [The Matrix] | 11:31am
  | DownloadDecisionMaker | No results found | 11:31am
  | NzbSearchService | Searching 0 indexers for [Ghost in the Shell] | 11:31am
  | DownloadDecisionMaker | No results found | 11:31am
  | NzbSearchService | Searching 0 indexers for [The Nightmare Before Christmas] | 11:31am
  | DownloadDecisionMaker | No results found | 11:31am
  | NzbSearchService | Searching 0 indexers for [The Lord of the Rings: The Fellowship of the Ring] | 11:31am
  | DownloadDecisionMaker | No results found | 11:31am
  | NzbSearchService | Searching 0 indexers for [The Lord of the Rings: The Return of the King] | 11:31am
  | DownloadDecisionMaker | No results found | 11:31am
  | NzbSearchService | Searching 0 indexers for [X-Men: Days of Future Past] | 11:31am
  | DownloadDecisionMaker | No results found | 11:31am
  | NzbSearchService | Searching 0 indexers for [X-Men: First Class] | 11:31am
  | DownloadDecisionMaker | No results found | 11:31am
  | NzbSearchService | Searching 0 indexers for [Wonder Woman] | 11:31am
  | DownloadDecisionMaker | No results found | 11:31am
  | NzbSearchService | Searching 0 indexers for [The Lego Batman Movie] | 11:31am
  | Database | Log database compressed | 11:30am
  | Database | Vacuuming Log database | 11:30am

**Comment by pamisoni** [comment]
View in github

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by galli-leo** [comment]
Please post the trace log file.

**Comment by Specimen1334** [comment]
oh i thought thats what i had done.. il take another look, but currently unsure how to find that which you ask.

**Comment by galli-leo** [comment]
System -> Logs -> Files

**Comment by Specimen1334** [comment]
here we go, it broke during this search, i visually could see it happen. (it started searching normally for the first few and was processing them, then just jumped to the end and said nothing found)
yeah i'm aware lots of these films aren't out yet, but that's not the problem :P it was doing the same thing when filled with only movies that do exist already (i've just manually grabbed some of those)

17-12-13 11:49:20.7|Info|Database|Vacuuming Log database
17-12-13 11:49:20.7|Info|Database|Log database compressed
17-12-13 11:49:46.5|Info|MovieSearchService|Performing missing search for 70 movies
17-12-13 11:49:46.5|Info|NzbSearchService|Searching 1 indexers for [Captain Marvel]
17-12-13 11:49:48.2|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:48.2|Info|NzbSearchService|Searching 1 indexers for [Marvel One-Shot: The Consultant]
17-12-13 11:49:49.4|Warn|Rarbg|Indexer API call returned error 10: Cant find imdb in database. Are you sure this imdb exists? - https://torrentapi.org/pubapi_v2.php?mode=search&search_imdb=tt2011118&ranked=0&category=movies&limit=100&token=(removed)&format=json_extended&app_id=Radarr

[v0.2.0.870] NzbDrone.Core.Indexers.Exceptions.IndexerException: Indexer API call returned error 10: Cant find imdb in database. Are you sure this imdb exists?
   at NzbDrone.Core.Indexers.Rarbg.RarbgParser.ParseResponse(IndexerResponse indexerResponse) in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\Rarbg\RarbgParser.cs:line 38
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 297
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchReleases(IndexerPageableRequestChain pageableRequestChain, Boolean isRecent) in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 154

17-12-13 11:49:49.4|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:49.4|Info|NzbSearchService|Searching 0 indexers for [Marvel One-Shot: Item 47]
17-12-13 11:49:49.5|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:49.5|Info|NzbSearchService|Searching 0 indexers for [Marvel One-Shot: Agent Carter]
17-12-13 11:49:49.5|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:49.5|Info|NzbSearchService|Searching 0 indexers for [Inhumans: The First Chapter]
17-12-13 11:49:49.5|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:49.5|Info|NzbSearchService|Searching 0 indexers for [Marvel One-Shot: A Funny Thing Happened on the Way to Thor's Hammer]
17-12-13 11:49:49.6|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:49.6|Info|NzbSearchService|Searching 0 indexers for [Thor: Ragnarok]
17-12-13 11:49:49.6|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:49.6|Info|NzbSearchService|Searching 0 indexers for [Team Thor]
17-12-13 11:49:49.6|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:49.6|Info|NzbSearchService|Searching 0 indexers for [Team Thor: Part 2]
17-12-13 11:49:49.6|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:49.7|Info|NzbSearchService|Searching 0 indexers for [Avengers: Infinity War]
17-12-13 11:49:49.7|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:49.7|Info|NzbSearchService|Searching 0 indexers for [Untitled Avengers Movie]
17-12-13 11:49:49.7|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:49.7|Info|NzbSearchService|Searching 0 indexers for [The Batman]
17-12-13 11:49:49.7|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:49.7|Info|NzbSearchService|Searching 0 indexers for [The Lego Movie]
17-12-13 11:49:49.7|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:49.8|Info|NzbSearchService|Searching 0 indexers for [X-Men: First Class]
17-12-13 11:49:49.8|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:49.8|Info|NzbSearchService|Searching 0 indexers for [X-Men: Days of Future Past]
17-12-13 11:49:49.8|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:49.8|Info|NzbSearchService|Searching 0 indexers for [The Lord of the Rings: The Fellowship of the Ring]
17-12-13 11:49:49.8|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:49.9|Info|NzbSearchService|Searching 0 indexers for [X-Men]
17-12-13 11:49:49.9|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:49.9|Info|NzbSearchService|Searching 0 indexers for [The Incredible Hulk]
17-12-13 11:49:49.9|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:49.9|Info|NzbSearchService|Searching 0 indexers for [The Lord of the Rings: The Two Towers]
17-12-13 11:49:49.9|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:50.0|Info|NzbSearchService|Searching 0 indexers for [Underworld: Endless War]
17-12-13 11:49:50.0|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:50.0|Info|NzbSearchService|Searching 0 indexers for [The Princess Bride]
17-12-13 11:49:50.0|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:50.0|Info|NzbSearchService|Searching 0 indexers for [The Craft]
17-12-13 11:49:50.0|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:50.1|Info|NzbSearchService|Searching 0 indexers for [Fantastic Beasts: The Crimes of Grindelwald]
17-12-13 11:49:50.1|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:50.1|Info|NzbSearchService|Searching 0 indexers for [Spider-Man 2]
17-12-13 11:49:50.1|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:50.1|Info|NzbSearchService|Searching 0 indexers for [Pirates of the Caribbean: Dead Man's Chest]
17-12-13 11:49:50.1|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:50.1|Info|NzbSearchService|Searching 0 indexers for [Spider-Man 3]
17-12-13 11:49:50.1|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:50.2|Info|NzbSearchService|Searching 0 indexers for [Pirates of the Caribbean: At World's End]
17-12-13 11:49:50.2|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:50.2|Info|NzbSearchService|Searching 0 indexers for [Power Rangers]
17-12-13 11:49:50.2|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:50.2|Info|NzbSearchService|Searching 0 indexers for [Night Guards]
17-12-13 11:49:50.3|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:50.3|Info|NzbSearchService|Searching 0 indexers for [Lara Croft Tomb Raider: The Cradle of Life]
17-12-13 11:49:50.3|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:50.3|Info|NzbSearchService|Searching 0 indexers for [Man of Steel]
17-12-13 11:49:50.3|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:50.4|Info|NzbSearchService|Searching 0 indexers for [Star Trek Beyond]
17-12-13 11:49:50.4|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:50.4|Info|NzbSearchService|Searching 0 indexers for [Star Wars: The Last Jedi]
17-12-13 11:49:50.4|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:50.4|Info|NzbSearchService|Searching 0 indexers for [Solo: A Star Wars Story]
17-12-13 11:49:50.4|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:50.5|Info|NzbSearchService|Searching 0 indexers for [Howl's Moving Castle]
17-12-13 11:49:50.5|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:50.5|Info|NzbSearchService|Searching 0 indexers for [On Your Mark]
17-12-13 11:49:50.5|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:50.5|Info|NzbSearchService|Searching 0 indexers for [The Secret World of Arrietty]
17-12-13 11:49:50.6|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:50.6|Info|NzbSearchService|Searching 0 indexers for [Porco Rosso]
17-12-13 11:49:50.6|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:50.6|Info|NzbSearchService|Searching 0 indexers for [Nausicaä of the Valley of the Wind]
17-12-13 11:49:50.6|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:50.7|Info|NzbSearchService|Searching 0 indexers for [FernGully 2: The Magical Rescue]
17-12-13 11:49:50.7|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:50.7|Info|NzbSearchService|Searching 0 indexers for [My Neighbor Totoro]
17-12-13 11:49:50.7|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:50.7|Info|NzbSearchService|Searching 0 indexers for [The Girl Who Leapt Through Time]
17-12-13 11:49:50.7|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:50.8|Info|NzbSearchService|Searching 0 indexers for [Castle in the Sky]
17-12-13 11:49:50.8|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:50.8|Info|NzbSearchService|Searching 0 indexers for [Liar Liar]
17-12-13 11:49:50.8|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:50.8|Info|NzbSearchService|Searching 0 indexers for [Spun]
17-12-13 11:49:50.8|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:50.8|Info|NzbSearchService|Searching 0 indexers for [X-Men: Dark Phoenix]
17-12-13 11:49:50.8|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:50.9|Info|NzbSearchService|Searching 0 indexers for [Elektra]
17-12-13 11:49:50.9|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:50.9|Info|NzbSearchService|Searching 0 indexers for [Ghost Rider: Spirit of Vengeance]
17-12-13 11:49:50.9|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:50.9|Info|NzbSearchService|Searching 0 indexers for [Deadpool 2]
17-12-13 11:49:51.0|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:51.0|Info|NzbSearchService|Searching 0 indexers for [Black Panther]
17-12-13 11:49:51.0|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:51.0|Info|NzbSearchService|Searching 0 indexers for [The New Mutants]
17-12-13 11:49:51.0|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:51.1|Info|NzbSearchService|Searching 0 indexers for [Venom]
17-12-13 11:49:51.1|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:51.1|Info|NzbSearchService|Searching 0 indexers for [Ant-Man and the Wasp]
17-12-13 11:49:51.1|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:51.1|Info|NzbSearchService|Searching 0 indexers for [Silver & Black]
17-12-13 11:49:51.1|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:51.2|Info|NzbSearchService|Searching 0 indexers for [Justice League]
17-12-13 11:49:51.2|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:51.2|Info|NzbSearchService|Searching 0 indexers for [Aquaman]
17-12-13 11:49:51.2|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:51.2|Info|NzbSearchService|Searching 0 indexers for [Shazam!]
17-12-13 11:49:51.2|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:51.2|Info|NzbSearchService|Searching 0 indexers for [Maze Runner: The Death Cure]
17-12-13 11:49:51.3|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:51.3|Info|NzbSearchService|Searching 0 indexers for [Ascendant]
17-12-13 11:49:51.3|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:51.3|Info|NzbSearchService|Searching 0 indexers for [Passengers]
17-12-13 11:49:51.3|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:51.3|Info|NzbSearchService|Searching 0 indexers for [House of Flying Daggers]
17-12-13 11:49:51.3|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:51.4|Info|NzbSearchService|Searching 0 indexers for [Willow]
17-12-13 11:49:51.4|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:51.4|Info|NzbSearchService|Searching 0 indexers for [Lost Boys: The Tribe]
17-12-13 11:49:51.4|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:51.4|Info|NzbSearchService|Searching 0 indexers for [The Gamers]
17-12-13 11:49:51.4|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:51.5|Info|NzbSearchService|Searching 0 indexers for [Dungeons & Dragons: Wrath of the Dragon God]
17-12-13 11:49:51.5|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:51.5|Info|NzbSearchService|Searching 0 indexers for [Perfect Blue]
17-12-13 11:49:51.5|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:51.5|Info|NzbSearchService|Searching 0 indexers for [Sample People]
17-12-13 11:49:51.5|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:51.5|Info|NzbSearchService|Searching 0 indexers for [Anchorman 2: The Legend Continues]
17-12-13 11:49:51.5|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:51.6|Info|NzbSearchService|Searching 0 indexers for [Anchorman: The Legend of Ron Burgundy]
17-12-13 11:49:51.6|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:51.6|Info|NzbSearchService|Searching 0 indexers for [Wake Up, Ron Burgundy: The Lost Movie]
17-12-13 11:49:51.6|Info|DownloadDecisionMaker|No results found
17-12-13 11:49:51.6|Info|MovieSearchService|Completed missing search for 70 movies. 0 reports downloaded.

**Comment by galli-leo** [comment]
Problem here is that rargb reports a not found imdbid as an error. Will try to fix that.
