### ISSUE TITLE
Is it possible to add a movie via imdb id / tmdb id from the radarr API?

### ISSUE THREAD

**Issue by Chas3down** [Radarr/Radarr#2320]
So, I am trying to add a movie and then search for that added movie via the radarr API.

I've been looking at https://github.com/Radarr/Radarr/wiki/API:Movie using PUT, however, right now I have tmdb and imdb id for my movie.    Is it not possible to add the movie with just the ID with the radarr API(needs to be with the api, because I am basically creating my own list functionality)? Or do I need to make a requests to the movie db, get the title and year, then pass that to radarr? Seems like that is very error-prone if I have to do it that way.

**Comment by hotio** [comment]
You mention PUT, however you are trying to add a movie????? I think you should start with POST and you have to add all the info. It's an api to add a movie, not an api to search for a movie.

**Comment by galli-leo** [comment]
See https://github.com/Radarr/Radarr/wiki/API:Movie#post for how to add a movie. You can get all the information for the Search API endpoint. Look at how the Web UI does it if there is still unclear stuff.
