### ISSUE TITLE
Rename existing movie file names

### ISSUE THREAD

**Issue by Romijn** [Radarr/Radarr#2321]
Hi,

I have the following issue. My current library is filled with a lot of movies but all have been named movie title only, after doing a bulk import of just a few I've noticed Radarr likes the year added to the filename.

In the renamer I've set it to:

Standard Movie Format  {Movie Title} ({Release Year})
Movie Folder Format {Movie Title}

When I click Preview rename for movie it says

Folder Naming pattern: {Movie Title}
Naming pattern: {Movie Title} ({Release Year})
Success! My work is done, no files to rename.

When I rename the file manually the movie will be picked up and show up as downloaded.

I'm running radarr on a Synology, in the log I do see ParserService warnings 

DiskScanService	Completed scanning disk for 12 Years a Slave	17:49
ParsingService	Unable to parse movie info from path /volume1/video/Movie/12 Years a Slave/12 Years a Slave.mkv	17:49
DiskScanService	Scanning disk for 12 Years a Slave	17:49
RefreshMovieService	Updating Info for 12 Years a Slave

Or is it somehow possible to not need the year behind the movie title for it to be seen?

**Comment by Romijn** [comment]
After adding the year manually:

DiskScanService	Completed scanning disk for 12 Years a Slave	17:56
MovieService	Linking [12 Years a Slave (2013).mkv] > [[tt2024544][12 Years a Slave (2013)]]	17:56
DiskScanService	Scanning disk for 12 Years a Slave	17:56
RefreshMovieService	Updating Info for 12 Years a Slave

**Comment by hotio** [comment]
https://github.com/Radarr/Radarr/wiki/Setup-Guide#movie-naming

**Comment by Romijn** [comment]
hotio, thanks for the link but I've correctly setup the renamer as I stated in my first post:

In the renamer I've set it to:

Standard Movie Format {Movie Title} ({Release Year})
Movie Folder Format {Movie Title}

When I click Preview rename for movie it says

Folder Naming pattern: {Movie Title}
Naming pattern: {Movie Title} ({Release Year})
Success! My work is done, no files to rename.

It doesn't rename the file because for some reason it cannot find the file however if I add the year to the file manually it is being picked up.

**Comment by hotio** [comment]
You should put the year in the folder.

**Comment by Romijn** [comment]
So can you explain to me when I manually rename the file name with (year) it does see the file whilst not renaming the folder?

**Comment by Romijn** [comment]
DiskScanService | Completed scanning disk for 13 Hours: The Secret Soldiers of Benghazi | 19:26
-- | -- | --
  | ParsingService | Unable to parse movie info from path /volume1/video/Movie/13 Hours The Secret Soldiers of Benghazi/13 Hours The Secret Soldiers of Benghazi.mkv | 19:26
  | DiskScanService | Scanning disk for 13 Hours: The Secret Soldiers of Benghazi

Folder Naming pattern: {Movie Title} ({Release Year})
Naming pattern: {Movie Title} ({Release Year})
Success! My work is done, no files to rename.

Renamer both set with {Movie Title} ({Release Year})

**Comment by hotio** [comment]
Put the year in both the file and the folder, otherwise expect problems. I'm not going to explain this for the x number of times.....

Movie Title (2017)/Movie Title (2017) - bluray-1080p.................mkv
After that a bulk import.
After that try your problem again, if you still have the issue we can talk again.

**Comment by hotio** [comment]
See https://github.com/Radarr/Radarr/wiki/Sorting-and-Renaming#naming-schemes for a proper naming scheme, ragarding the file name, because emmitting the quality is going to bite you in the ass sooner or later.

**Comment by Romijn** [comment]
Okay I was hoping for Radarr to do the renaming for me since we're talking about 350+ movies.

**Comment by hotio** [comment]
Radarr can do the renaming, BUT only after it has fully imported the movie and knows exactly whow it is named and where it is stored.

So it is heavily recommended to do a proper rename (most use filebot) before doing a bulk import, after that you can renaming adjustments, but beware, only the movie is renamed, subtitles or metadata is ignored.

**Comment by Romijn** [comment]
Alright, yeah dont' really care about the external files, I'll take a look at file bot, or just not import my existing movies, cheers.
