### ISSUE TITLE
10 movies per page

### ISSUE THREAD

**Issue by dpyy** [Radarr/Radarr#2322]
**Description:**
10 movies per page is shown, even though in settings, it's set to 250. 

**Radarr Version:**
Latest version

**Comment by Firelfy** [comment]
Check your web browser cache, clearing that may fix your problems.

[Firefox](https://support.mozilla.org/en-US/kb/how-clear-firefox-cache)
[Chrome](https://support.google.com/googleplay/answer/32050?hl=en-GB)

**Comment by dpyy** [comment]
I already used incognito mode and its the same thing. It shows 10 pages in grid view and list view. 

Tried a different browser, same thing. Safari and chrome

**Comment by galli-leo** [comment]
@dpyy Try changing the setting. The UI default and the actual default in code might be different.
