### ISSUE TITLE
Issue with Files not being tracked or imported by Radarr.

### ISSUE THREAD

**Issue by 64Hz** [Radarr/Radarr#2323]
Hi there!

I'm not sure what has changed but recently any files I add to Radarr are not tracked when they become active downloads. They are added into the 'history' but do not show up under 'Activity'.

After they are downloaded by my torrent client they are also not imported to the correct path as is with the usual working method.

I'm not very sure what I should be looking for in the logs and I did not want to post potentially incorrect extracts. If you could point me in the correct direction of what to look for I will get it posted.

**Comment by roblandry** [comment]
Bump.

Radarr Ver. 0.2.0.910
develop

New update broke nzb handling also.
Gets added to nzbget. In radarr, the download is added to history, not queue.
Once complete. Nothing happens. Must manually add to radarr.

**Comment by 64Hz** [comment]
After I updated today the issue still persists. As @roblandry has said - it goes straight to history and not queue.

**Comment by mikemathewson** [comment]
Having the same issue with version 0.2.0.910

Download progress no longer shows for files added to NZBGet and nothing is imported after the download finishes.

**Comment by mikemathewson** [comment]
I was having the same issue and then I realized that my category name in NZBGet was "movies" but in Radarr it was "Movies" (capital M). The inconsistency was causing this issue for me. However I am not sure how it was working previously.

**Comment by fryfrog** [comment]
What torrent client? It sounds like it isn't getting the right label or isn't communicating w/ it properly.

**Comment by 64Hz** [comment]
Sorry should have said - qBittorent.

I didn't think that would matter as it's Radarr that seems to not be changing it's actions.

**Comment by pamisoni** [comment]
Mute the thread

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by fryfrog** [comment]
I use rTorrent and it all works fine. I did see someone mention qBittorrent in the channel the other day, maybe there are issues w/ the current release. Can you try downgrading? Or does it work w/ Sonarr?

**Comment by 64Hz** [comment]
Works perfectly with Sonarr. That's what makes me believe Radarr is at fault.

**Comment by roblandry** [comment]
I dont think this is limited to torrent programs. I am having the same issue with nzbget. Also the category in both programs is identical.

**Comment by fryfrog** [comment]
@64Hz: For qBittorrent, I'm guessing something changed and Sonarr already updated / fixed it. You could confirm this by downgrading or trying another torrent client. The fact my rTorrent works means it isn't *all* torrent clients, even if something in Radarr needs fixing. It might help to narrow things down.

@roblandry: NZBGet is my primary and works fine. At update, It *did* flip my tag from `movies` to `Movies` (I think in both rTorrent and NZBGet settings in Radarr), but after fixing that it has all been fine. I suggest you make a different issue for your NZBGet issues, it seems unlikely they're related to this. :(

**Comment by 64Hz** [comment]
@fryfrog I have just installed Deluge and connected Radarr to that instead and the issue still persists. I'm unsure what else to try to rule out a Radarr issue.

**Comment by 64Hz** [comment]
I *believe* I have fixed my issue.

In the System tab, there is a tab called Tasks.

In there I noticed that the "Check for finished downloads" and a few other tasks were set to next execute in 64 Years. After manually telling them to run standard operating procedure kicked in and seems okay for now.
