### ISSUE TITLE
Error during RSS Sync: Unable to connect to the remote server

### ISSUE THREAD

**Issue by gregcbrown** [Radarr/Radarr#2325]
Could I get a little help on this? Not sure why I am getting this error, or what it means.

RADARR version 0.2.0.870
[radarr.txt](https://github.com/Radarr/Radarr/files/1540914/radarr.txt)

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by galli-leo** [comment]
Seems like one of your indexers has issues.

**Comment by gregcbrown** [comment]
Thanks much. It was NZB.IS, looks like they are dead.
