### ISSUE TITLE
Deluge test passes, but getting "object reference not set" error in Radarr

### ISSUE THREAD

**Issue by Magic815** [Radarr/Radarr#2329]
**Description:**

I am running Radarr on a Windows 8.1 machine, and am having communication issues with Radarr and Deluge.

So this first sign of an issue is that Radarr constantly has a system message showing:
```Unable to communicate with Deluge. Object reference not set to an instance of an object.```

However, these are my Deluge settings, and when I click "Test," it always passes.
https://i.imgur.com/xqYCVZX.png

When I add a movie, and select a torrent file (from PTP, which is the only torrent indexer I have linked to Radarr), the movie properly gets added to Deluge with the 'radar' label. However, Radarr never pulls the completed torrent in. I always have to manually import the file myself.

The logs show the below message, on repeat. Any insight into what might be going wrong? I've seen previous issues on Radarr with PTP specifically - could it be related to one of those?

**Radarr Version:**
0.2.0.870

**Logs:**
```17-12-9 17:25:44.4|Warn|DownloadMonitoringService|Unable to retrieve queue and history items from Deluge

[v0.2.0.870] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Download.Clients.Deluge.Deluge.GetItems() in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\Deluge\Deluge.cs:line 99
   at NzbDrone.Core.Download.TrackedDownloads.DownloadMonitoringService.ProcessClientDownloads(IDownloadClient downloadClient) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\TrackedDownloads\DownloadMonitoringService.cs:line 86```

**Comment by galli-leo** [comment]
So I tried to do a blind fix, if the latest nightly (or next develop release) does not fix your issue, I would suggest checking your deluge config, because it shouldn't fail on that line.
