### ISSUE TITLE
Dot (.) in Movie name creates invalid/not working URL

### ISSUE THREAD

**Issue by hotio** [Radarr/Radarr#233]
When clicking on a movie that contains a dot in the title, from main page goes OK, but after refreshing or using "Open in new tab/window" the response is:

```
{
  "message": "NotFound"
}
```

Log message:

````
Component
StaticResourceModule

Message
Couldn't find handler for /movies/guardians-of-the-galaxy-vol.-2-2017
````

**Comment by onedr0p** [comment]
Do you have a example movie?

**Comment by hotio** [comment]
````
Guardians Of The Galaxy Vol. 2
M.S. Dhoni: The Untold Story
````

**Comment by onedr0p** [comment]
Yep I'm getting that too.

**Comment by onedr0p** [comment]
I can confirm Sonarr strips out periods, we should to:

`Check It Out! With Dr. Steve Brule`
`/sonarr/series/check-it-out-with-dr-steve-brule`
