### ISSUE TITLE
Add + or add and search 

### ISSUE THREAD

**Issue by marc0janssen** [Radarr/Radarr#2331]
I have question

What is the difference between the " Add +" feature and the " add and search" feature?

Is the add feature just to add the movie and it only gets downloaded when you explicitly make it search!? Or does it get downloaded eventually!!?

I am a bit confused!!?

**Comment by galli-leo** [comment]
Add and Search: Adds the movie and immideately searches for it on all your indexer (useful for already released movies)
Add: Adds the movie, but only looks on your Indexers RSS feeds for new releases (useful for future movies)

**Comment by galli-leo** [comment]
Please also keep in mind this issue board is only for bugs and features. Please use the discord for support questions.

**Comment by marc0janssen** [comment]
Thanks for explaining!! 

Verstuurd vanaf mijn iPhone

**Comment by marc0janssen** [comment]
Sorry you are totally right. 

Verstuurd vanaf mijn iPhone
