### ISSUE TITLE
Unambiguous "Week Column Header"  [Enhancement]

### ISSUE THREAD

**Issue by frm1001xplrr** [Radarr/Radarr#2332]
**Description:**

The "Settings"->"UI"->"Week Column Header" setting allows for viewing dates as either "month/day" or "day/month", but which is which? 

is 03/05 the third of May?
or 
is 03/05 the fifth of March?

Sonarr related: https://forums.sonarr.tv/t/unambiguous-week-column-header-section-of-settings-ui/13123

**Solution**
Change the example month to something above 12, to make it clear which number is the month. 
Fx. Change "03/05" / "05/03"  to  "25/03" or "25/05", making it easy to see which is the month.

Ex. Sonarr: https://i.imgur.com/RmrepUg.png, ie "25/03"

**Radarr Version:**
All

**Comment by Qstick** [comment]
Was fixed #2165
