### ISSUE TITLE
All movies deleted from list

### ISSUE THREAD

**Issue by steve1977** [Radarr/Radarr#2333]
I had around 1,000 movies in my movie list in radarr. In the movie editor, I selected "missing" and then clicked "delete". This was supposed to delete the around 80 movies that were selected as "missing".

Unfortunately, it instead deleted all my 1,000 movies from the list. The movie list now shows "you are new around here" and not a single movie. However, it still says "952 downloaded and monitored" movies in green. But no movies are shown.

Also, I can not re-add the movies, but they are also not being used anymore to move from download folder to movie folder.

This feels like a very major bug. Any chance to get a fix and thought on a work-around? I somehow need to either get my library back or fully nuke it that I can re-add from my watch-list and re-import from my movie folder.

Any thoughts?

**Comment by fryfrog** [comment]
You're stuck in the missing view and you can't see the controls, they're not actually deleted.
