### ISSUE TITLE
Cutoff unmet when it is not?

### ISSUE THREAD

**Issue by dpyy** [Radarr/Radarr#2334]
**Description:**

I have a movie that is already in 1080 and the profile is set at "HD0180p". But it shows up as cutoff unment. 

**Radarr Version:**
Latest version
<img width="1209" alt="screen shot 2017-12-10 at 1 08 45 pm" src="https://user-images.githubusercontent.com/19830772/33807868-45fc0d98-ddab-11e7-8bb3-69db58e20506.png">

**Comment by galli-leo** [comment]
Can you post a picture of your profile settings?

**Comment by dpyy** [comment]
<img width="1111" alt="screen shot 2017-12-10 at 3 08 02 pm" src="https://user-images.githubusercontent.com/19830772/33808908-ed8ee52a-ddbb-11e7-8461-3c4e7eb5c1e3.png">

**Comment by galli-leo** [comment]
So the cutoff set in the profile is set to Bluray 1080p, meaning that only then will the movie be set to cutoff met.

**Comment by dpyy** [comment]
ok but what does the grey and blue mean?

**Comment by galli-leo** [comment]
Blue means cutoff unmet here. Grey means nothing special.
