### ISSUE TITLE
Bulk-import reads trailer instead of movie

### ISSUE THREAD

**Issue by steve1977** [Radarr/Radarr#2335]
For some of my movies, the trailer file (<name>-trailer.ext) is being picked up by radarr instead of the movie file (<name>.ext).

I assume that this may lead to an issue when upgrading as the trailer would be deleted and not the movie file? Any other impact from this?

Would be great to see a fix. Also, could I exclude flv-extenstion as work-around for the time until a proper fix will be included? If so, how?

**Comment by fryfrog** [comment]
Probably the trailer is big enough to meet the bar of *not* being a Sample. :/
