### ISSUE TITLE
Can't create a Radarr List from IMDB Watchlist

### ISSUE THREAD

**Issue by mgleason2002** [Radarr/Radarr#2338]
**Description:**
I just noticed my RSS lists configured against my RSS IMDB watch lists are no longer working with Radarr. I saw that these are deprecated now in Radarr, so I set up a Radarr List per the Wiki instructions.

However, I'm unable to connect to my public watchlist (http://www.imdb.com/user/ur7173741/watchlist) using my IMDB username:

/imdb/list?listId=ur7173741

When I create a new list in IMDB and use the list ID, I can connect, but all of my movies are in my watchlist and that's the easiest way for me and my family to add them right now. Test list:

/imdb/list?listId=ls027600649

Provide a description of the feature request or bug here, the more details the better. 
Please also try to include the following if you are reporting a bug

**Radarr Version:**
0.2.0.870

**Logs:**
17-12-11 15:52:43.1|Warn|RadarrLists|Unable to connect to list

[v0.2.0.870] NzbDrone.Core.MetadataSource.RadarrAPI.RadarrAPIException: Error while calling api: Unprocessable Entity! Parameter listId has one or more errors.
Full error(s): Unprocessable Entity! Parameter listId has one or more errors. (422, RayId: abedd147-6892-4db7-b6f0-f8f0ce7dd649), Details: The following errors happened while processing the request parameter listId: The format of the listId given is invalid!
  at NzbDrone.Core.NetImport.Radarr.RadarrParser.PreProcess (NzbDrone.Core.NetImport.NetImportResponse indexerResponse) [0x00029] in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\Radarr\RadarrParser.cs:60 
  at NzbDrone.Core.NetImport.Radarr.RadarrParser.ParseResponse (NzbDrone.Core.NetImport.NetImportResponse importResponse) [0x0000d] in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\Radarr\RadarrParser.cs:34 
  at NzbDrone.Core.NetImport.HttpNetImportBase`1[TSettings].FetchPage (NzbDrone.Core.NetImport.NetImportRequest request, IParseNetImportResponse parser) [0x00008] in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:110 
  at NzbDrone.Core.NetImport.HttpNetImportBase`1[TSettings].TestConnection () [0x0000e] in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:145 

17-12-11 15:52:43.1|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Unable to connect to list, check the log for more details

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by galli-leo** [comment]
Seems like I forgot that userIds can be below 8 characters so the API thinks it's invalid. Will try to get this fixed soon.

**Comment by mgleason2002** [comment]
Great, thank you!

**Comment by fun4stuff** [comment]
I think I'm having a similar problem. I get the following error when trying to test the connection "unable to connect to indexer. Indexer responded with HTML content. Site is likely blocked or unavailable."

**Comment by galli-leo** [comment]
@fun4stuff This can happen when using RSS IMDB lists. Please use the Radarr IMDB lists instead.

**Comment by fun4stuff** [comment]
@galli-leo : thanks! That fixed it. Hadn't checked those settings in awhile.

**Comment by galli-leo** [comment]
Change is now live.

**Comment by mgleason2002** [comment]
@galli-Leo, thanks I can confirm it’s working now with my 7 digit IMDB user name.

**Comment by CanonCan** [comment]
I have two lists. one works other did once upon a time and now wont connect

working username is ls023263032

one not working is ur33918291

I checked the logs and just get this



  | Component | Message | Time
-- | -- | -- | --
  | NzbDroneErrorPipeline | Invalid request Validation failed:   -- Unable to connect to list, check the log for more details | 12:06am
  | RadarrLists | Unable to connect to list: Error while calling api: Internal Server Error Full error(s): Internal Server Error (500, RayId: d00db131-d42c-4117-b38d-0dc8a5e91ded), Details: An error has occurred and this resource cannot be displayed.

**Comment by Blisk** [comment]
I have the same problem IMDB rss preset lists doesn't work.
Radarr lists>Preset>IMDB Top 250
I get error connecting
