### ISSUE TITLE
Token needs to be renewed every few hours

### ISSUE THREAD

**Issue by mattman86** [Radarr/Radarr#234]
Every few hours, I get a message in the log that 0 indexers were searched. Upon investigation, I find several messages stating:

`Indexer API call returned error 4: Invalid token. Use get_token for a new one! - https://torrentapi.org/pubapi_v2.php?mode=search&search_imdb=tt0357668&category=movies&limit=100&token=(removed)&format=json_extended&app_id=Sonarr: Indexer API call returned error 4: Invalid token. Use get_token for a new one!`

**Comment by onedr0p** [comment]
Have you tried this?

https://github.com/Sonarr/Sonarr/issues/1410#issuecomment-238063582
