### ISSUE TITLE
Movies auto-added from Trakt Watchlist Don't have Cover Art

### ISSUE THREAD

**Issue by kianrafiee** [Radarr/Radarr#2340]
**Radarr Version:**
0.2.0.870

**Logs:**
https://pastebin.com/LW52VppW

I'm not sure if this issue crops up when adding movies manually. But I am pretty sure I added Valerian(the new sci fi movie) before I uninstalled Sonarr weeks ago manually and the cover art was there. 

But this time I added a Trakt Watch List to Lists area and have it set to auto-add the movies to Radarr. Well I had Valerian in the list and when it was added, along with some other movies, none of them have cover art. But they do have wallpapers when you go to the movie page in Radarr.

I know this isnt a Chrome cache issue because I used Safari which I never used to browse Radarr and it has the same issue.

**Comment by quincarter** [comment]
My problem is that the movies are added and the album art is there, but it is the WRONG album art. See screenshot. 

![capture](https://user-images.githubusercontent.com/18407074/34786929-2dc4bcb2-f5fb-11e7-9d48-6be289c53fa5.PNG)

Some info from the logs:

HttpClient | Failed to get response from: http://image.tmdb.org/t/p/original The remote server returned an error: (404) Not Found. | Last Saturday
-- | -- | --
  | MediaCoverService | Couldn't download media cover for [tt5028340][Mary Poppins Returns (2018)], likely the cover doesn't exist for this movie. The remote server returned an error: (404) Not Found.: The remote server returned an error: (404) Not Found. | Last Saturday
  | HttpClient | Failed to get response from: http://image.tmdb.org/t/p/original The remote server returned an error: (404) Not Found. | Last Saturday
  | MediaCoverService | Couldn't download media cover for [][M:I 6 - Mission Impossible (2018)], likely the cover doesn't exist for this movie. The remote server returned an error: (404) Not Found.: The remote server returned an error: (404) Not Found. | Last Saturday
  | HttpClient | Failed to get response from: http://image.tmdb.org/t/p/original The remote server returned an error: (404) Not Found. | Last Saturday
  | MediaCoverService | Couldn't download media cover for [tt4912910][M:I 6 - Mission Impossible (2018)], likely the cover doesn't exist for this movie. The remote server returned an error: (404) Not Found.: The remote server returned an error: (404) Not Found. | Last Saturday
  | Rarbg | Indexer API call returned error 10: Cant find imdb in database. Are you sure this imdb exists? - https://torrentapi.org/pubapi_v2.php?mode=search&search_imdb=tt4912910&ranked=0&category=movies&limit=100&token=(removed)&format=json_extended&app_id=Radarr: Indexer API call returned error 10: Cant find imdb in database. Are you sure this imdb exists? | Last Saturday
  | HttpClient | Failed to get response from: http://image.tmdb.org/t/p/original The remote server returned an error: (404) Not Found. | Last Saturday
  | MediaCoverService | Couldn't download media cover for [][Robin Hood: Origins (2018)], likely the cover doesn't exist for this movie. The remote server returned an error: (404) Not Found.: The remote server returned an error: (404) Not Found. | Last Saturday
  | HttpClient | Failed to get response from: http://image.tmdb.org/t/p/original The remote server returned an error: (404) Not Found. | Last Saturday
  | MediaCoverService | Couldn't download media cover for [tt4532826][Robin Hood: Origins (2018)], likely the cover doesn't exist for this movie. The remote server returned an error: (404) Not Found.: The remote server returned an error: (404) Not Found. | Last Saturday
  | HttpClient | Failed to get response from: http://image.tmdb.org/t/p/original The remote server returned an error: (404) Not Found. | Last Saturday
  | MediaCoverService | Couldn't download media cover for [tt4532826][Robin Hood: Origins (2018)], likely the cover doesn't exist for this movie. The remote server returned an error: (404) Not Found.: The remote server returned an error: (404) Not Found. | Last Saturday
  | FetchAndParseRssService | No available indexers. check your configuration. | Last Saturday
  | HttpClient | Failed to get response from: http://image.tmdb.org/t/p/original The remote server returned an error: (404) Not Found. | Last Saturday
  | MediaCoverService | Couldn't download media cover for [tt4799066][Midnight Sun (2018)], likely the cover doesn't exist for this movie. The remote server returned an error: (404) Not Found.: The remote server returned an error: (404) Not Found. | Last Saturday
  | Rarbg | Indexer API call returned error 10: Cant find imdb in database. Are you sure this imdb exists? - https://torrentapi.org/pubapi_v2.php?mode=search&search_imdb=tt5461956&ranked=0&category=movies&limit=100&token=(removed)&format=json_extended&app_id=Radarr: Indexer API call returned error 10: Cant find imdb in database. Are you sure this imdb exists? | Last Saturday

**Comment by quincarter** [comment]
On the flip side, in nzb360 on my phone, the album art is there for Radarr and it is correct. But they may be storing it locally and not pulling from the Radarr DB on my server.

**Comment by galli-leo** [comment]
Try clearing browser cache. If your app is displaying the correctly this is probably the issue.

**Comment by quincarter** [comment]
That actually worked for me. Wouldn't have thought it was a cache issue.

**Comment by galli-leo** [comment]
This is fixed on the latest release. (try clearing cache and cookies as well as refreshing movies).
