### ISSUE TITLE
Radarr adding download that's unrelated to search in any way. Does not track the download.

### ISSUE THREAD

**Issue by Routhinator** [Radarr/Radarr#2343]
**Description:**
Radarr keeps adding this film "Guy Martins Wall of Death" when searching for Deadpool in 720p. The download has a correct naming schema. No associated download is listed in Radarr. Radarr acts like it did not get any results, and yet it sent this download to sabnzbd. Happens every time the title is searched. Actions are logged.

![screenshot from 2017-12-13 20-05-35](https://user-images.githubusercontent.com/727535/33975239-1f31cc22-e042-11e7-97ab-33c93d303992.png)

![screenshot from 2017-12-13 20-05-42](https://user-images.githubusercontent.com/727535/33975231-15bdb642-e042-11e7-950f-741c3b388e4a.png)

**Radarr Version:**
0.2.0.870

**Logs:**
![screenshot from 2017-12-13 20-12-07](https://user-images.githubusercontent.com/727535/33975235-19641f20-e042-11e7-90dc-727a31a05f6d.png)

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by Routhinator** [comment]
Looks like this is actually a bad IMDB id on the download. Unfortunate that Radarr adds it anyway.

**Comment by galli-leo** [comment]
Unfortunately not much we can do here. Usually bad imdbids do not get added, because we still check the year, but seems you got unfortunate with this (same year).
