### ISSUE TITLE
API: `sceneName` property rarely available

### ISSUE THREAD

**Issue by pannal** [Radarr/Radarr#2344]
Linked to: #2245 

Even with recently added movies I rarely see the `sceneName` property set in the API response, even though `releaseGroup` is set (and has obviously been detected).

Some movies have the property set, most don't.

As this property is crucial for the matching of subtitles, could this issue please be investigated?

Thank you

Update: I've checked, Sonarr seems to always set the property.

**Comment by galli-leo** [comment]
I don't see the sceneName anywhere in Sonarr or Radarr code. If you could provide a sample API response from both where they are present that would help very much.

**Comment by pannal** [comment]
@galli-leo you merged that PR: https://github.com/Radarr/Radarr/pull/2250, so you should see sceneName inside your code.

**Comment by galli-leo** [comment]
Ah this isn't in the History API.

**Comment by galli-leo** [comment]
We have the exact same logic as Sonarr when checking for Scene Names. Maybe your episodes are just better named? As soon as there are Spaces in the filename, it's not considered "scene" anymore.

**Comment by pannal** [comment]
Yeah you're right, as sceneName was added later to the API, most of the movies didn't have one set in my library. Duh me.
