### ISSUE TITLE
Easy fix for foreign users

### ISSUE THREAD

**Issue by nuhll** [Radarr/Radarr#2346]
Hi, im using the latest radarr version since some weeks now.

Much thanks so far. I love it!

But it could be better for foreign users.

Add just one thing for us NON English ppl, **let us add something to the title.**

BECAUSE all film on this world, which are not in english, have country added.

Moviename -> if its english
Moviename **german** -> if its german
Moviename **italia** -> if its italia (i dont know how italian movies are named, but i think u get that part xD)

I would suggest to add one checkbox at: 

Restrictions -> "must contain" -> e.g. -> "german" -> **checkbox** -> _"Do you want to add this to the search querrys"_?

Its that easy. At the moment its pretty much unusable (or lets say, it could be much better without effort)  and torrent e.g. is complete broken for foreign users.

Please add this also for sonarr. Its an easy fix and would help all NON english speaking ppl in the world 💃

**Comment by galli-leo** [comment]
First of all, this won't be an easy fix, as the indexer part is seperated from the restrictions part entirely (as it should be). If you disable searching by imdbid as well as adding the year to the search query, there is no reason why Moviename german would produce different results than Moviename alone. If it does, I suggest you complain to your indexer staff. I won't be adding any options to customize the search query more as it only unecessary complicates Radarr.
