### ISSUE TITLE
Unable to connect to indexer / Error occurred while executing task ApplicationUpdate (POINT_IS_NOT_ON_CURVE)

### ISSUE THREAD

**Issue by rradar** [Radarr/Radarr#2350]
**Description:**

After a fresh radarr install I can't connect to any indexer and I can't update the version of radarr. Resulting that I'm not able to do anything useful with radarr. It's related to a issue with https and the cause is the same for both errors. I do don't know how to solve this problem. Any help is appreciated. Thank's a lot!

**Platform**
arm64 (orange pi pc 2)
Debian 8.10 jessie (armbian+openmediavault)
kernel 4.14.4-sunxi64 (bleeding edge)
mono-5.4.1.6 (via official repo: http://www.mono-project.com/download/#download-lin-debian)

**Radarr Version:**
v0.2.0.299 (from openmediavault repo)

**Logs:**

> 17-12-15 19:30:45.1|Warn|Newznab|Unable to connect to indexer

```
[v0.2.0.299] System.Net.WebException: Error: SecureChannelFailure (One or more errors occurred.) ---> System.AggregateException: One or more errors occurred. ---> System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> Mono.Btls.MonoBtlsException: Ssl error:0f000078:elliptic curve routines:OPENSSL_internal:POINT_IS_NOT_ON_CURVE
  at /build/mono-5.4.1.6/external/boringssl/crypto/ec/ec.c:835

```

> 17-12-15 19:21:41.7|Error|CommandExecutor|Error occurred while executing task ApplicationUpdate

```
[v0.2.0.299] System.Net.WebException: Error: SecureChannelFailure (One or more errors occurred.) ---> System.AggregateException: One or more errors occurred. ---> System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> Mono.Btls.MonoBtlsException: Ssl error:0f000078:elliptic curve routines:OPENSSL_internal:POINT_IS_NOT_ON_CURVE
  at /build/mono-5.4.1.6/external/boringssl/crypto/ec/ec.c:83
```

**Comment by rradar** [comment]
I think it's related to mono and a SSL problem. How can I debug further?

**Comment by galli-leo** [comment]
There’s an issue already open for this, where workarounds are posted. Sorry, cannot link because I am on mobile.

**Comment by rradar** [comment]
to bad - I search the whole repository and there is nothing but my issue related to POINT_IS_NOT_ON_CURVE

Would be happy if someone is pointing to the workaround! Thank's

**Comment by rradar** [comment]
Found some old issues where there is problems with a 'SecureChannelFailure'. Eventhough it's not the problem I have the suggestion was to install/update libcurl3 or libcurl4

I have libcurl3 installed, libcurl4 is not available on my system.

Still I can not connect to indexer nor update radarr. Problem unsolved - please reopen the issue. Thanks

**Comment by rradar** [comment]
i also think it's important that my system is **not** a x86 but a arm64!

**Comment by galli-leo** [comment]
See https://github.com/Jackett/Jackett/issues/2173, apparently it's a mono issue with arm64. You have to downgrade mono.

**Comment by rradar** [comment]
Thank's for the information! Do you have any idea how I can downgrade mono? they don't have a 4.x repository and I like to get updates if they come available.

**Comment by rradar** [comment]
I found the right way: http://www.mono-project.com/docs/getting-started/install/linux/#accessing-older-releases

And hint **which version** of mono to use? 3.x? 4.x?

**Comment by galli-leo** [comment]
Something like 5.3 is probably fine too

**Comment by rradar** [comment]
I went with 5.2 as there are no snapshots for 5.3 available.

The following steps I'm going to do now:

- stop radarr
- remove mono-complete (to get rid of all dependencies)
- install mono-complete in v.5.2
- start radarr and be happy again - let's see!

**Comment by rradar** [comment]
So did fresh os install and everything. Now I started with mono 5.2 and it's working out of the box.
