### ISSUE TITLE
Component: NzbSearchService (log) but i only have torrent indexer

### ISSUE THREAD

**Issue by valantislevas** [Radarr/Radarr#2351]
**Description:**

Radarr Ver. 0.2.0.910
develop

**Logs:**

On log i see that componenet: NzbSearchService on manual search of movie and doesnt find the movie.. on indexers pages i have only torrent trackers with jackett and it works ..

can someone tell me what i am doing wrong or if that is bug..

thanks.

**Comment by galli-leo** [comment]
Nothing wrong, the component that searches indexers is just callled that.
