### ISSUE TITLE
Folder Keeps Re-appearing....?

### ISSUE THREAD

**Issue by darrenclimienewman** [Radarr/Radarr#2352]
Hi,

I have an issue with a Movie folder keep re-appearing in my Movies folder, regardless of whether i have it in my list of Movies in Radarr.

The setting of 'Create Missing Movie Folder' is DISABLED, yet every time i delete the folder it keeps re-appearing. I've deleted the MOVIE i have including the folder, so i have no record of it. I've even removed ALL of my movies from Radarr, so there is nothing for it to check against, yet it keeps re-appearing.

Everytime i delete the folder, i move to another folder, come back to the Movies folder, and its re-appeared!

Please advise how i resolve this?

Thnaks

**Comment by galli-leo** [comment]
Are you sure Radarr is doing this? Radarr only creates folders when a disk scan is executed. Also some logs would be very helpful (best would be trace).

**Comment by darrenclimienewman** [comment]
Yes I'm pretty sure it's Radarr, I've never seen it before until I turned on the 'create folders for missing Movies'.

I've since sorted it out by moving my movie files to the folders that have been created (most because Radarr had most missing due to not having naming scheme correct). Then I deleted the original folders.

If it does it again for anything, I grab a log/trace if I can.

-------- Original message --------

**Comment by darrenclimienewman** [comment]
I've just noticed that a film I downloaded a couple of nights ago has 2 identical folders both with identical files in them.

**Comment by matmuilwijk** [comment]
Just thinking: Are you on Linux? If so, it could be that a piece of software you're using is still locking the file you've deleted. Linux replaces it with a hidden file for the time being, and removes it as soon as the program releases it's lock. I've had these issues with Plex before, and one or 2 with Radarr and Sonarr as well. Try rebooting either the system, or the applications that might use the file.

**Comment by darrenclimienewman** [comment]
Hi,


I'm running Radarr, Sonarr and Plex on a QNAP TS-453A, which is based on Linux, so i guess it could be that. I've only had the issue with Radarr so far, and it started when i enabled the 'Create Folders for Missing Movies', which from memory (at work at the moment), is an Alpha Feature.


I'm pretty sure my QNAP NAS has been rebooted since the issue appeared, but i'll do it again tonight just to be sure, obviously rebooting the NAS will by default restart Radarr.


Thanks


________________________________

**Comment by galli-leo** [comment]
This is definitely not a radarr issue. If you have deleted all movies from Radarr, there is no way Radarr creates the folders again.
