### ISSUE TITLE
Failed to rollback upgrade on Synology DS

### ISSUE THREAD

**Issue by cuki** [Radarr/Radarr#2354]
**Description:**
Yesterday I ran the update through UI and application was not responsive and didn't think much of it at the time, considering it usually takes some time to start the application.
Today I noticed it failed to update when checking the logs, due to it could not find the following file:
- __/tmp/radarr_update/Radarr/UI/Content/Images/touch/144.png__

However it attempted to run an automatic rollback of the update and then it also was unable to find __/tmp/radarr_update/radarr_backup__ directory.

**Radarr Version:**
From version 0.2.0.870 to version 0.2.0.910.
Installed on Synology DS216j.

**Logs:**
This was the only log file in the __/var/services/homes/radarr/.config/Radarr/UpdateLogs__ directory.
[2017.12.15-22.28.txt](https://github.com/Radarr/Radarr/files/1564762/2017.12.15-22.28.txt)

**Comment by cuki** [comment]
I managed to resolve it by [manually re-installing](https://github.com/Radarr/Radarr/wiki/Installation#manually-install-radarr) latest version in the package by executing the following commands through SSH using the admin account.

```bash
cd /volume1/\@appstore/radarr/share/
# Cleanup previous broken/corrupted installation of Radarr
sudo rm -rf Radarr/
# Download and extract the latest release from GitHub
sudo wget $( curl -s https://api.github.com/repos/Radarr/Radarr/releases | grep linux.tar.gz | grep browser_download_url | head -1 | cut -d \" -f 4 )
sudo tar -xvzf Radarr.develop.*.linux.tar.gz
# Change owner of Radarr installation to work with associated package user/owner
sudo chown -R radarr Radarr/
# Cleanup downloaded archive
sudo rm Radarr.develop.0.2.0.910.linux.tar.gz
```

Not sure what kind of consequences this will have by manually installing Radarr in a Synology package, in case there are any alternative solutions to fix this problem, please let me know.

**Comment by galli-leo** [comment]
If you are using a synology package, I suggest you disable updating and wait for the package itself to be updated.
