### ISSUE TITLE
Unable to add any indexer

### ISSUE THREAD

**Issue by digitalface** [Radarr/Radarr#2356]
Hi,

I've had Radarr working on 3 other Pi's, but I'm having trouble with this one. It's installed alongside Sonarr  (which works wonderfully so we assume no DNS issue), but when I go to add an indexer (any indexer) Radarr fails after about 30 seconds with "testing X failed". These same indexers work with Sonarr AND on my other Pi's that have Radarr installed.

If I add a new indexer and put completely invalid credentials, it'll take  30secs~ to time out. If I put no info, it's the same. And I don't get the "check logs" banner across the top like I do on my other installs. It's literally like the Indexer check isn't working at all.

If I do the above on my other working Radarr box, I'll get a 'success' or 'fail' within seconds. 

I've checked the logs, trace, debug etc and there's no evidence that the Indexer is even being queried. I've uninstalled and reinstalled Radarr, no difference.

Are you able to offer assistance or anything else I can try? It's clearly an issue with my install but I just cant figure it out.

**Radarr Version:**
0.2.0.910
**Stretch**

**Comment by equiliym** [comment]
will have to bump this thread, installed radarr today on my RPi3, running alongside sonarr as well, not a single indexer is working or even connecting, has a little timeout when testing and says unable to connect, even if i hit save, does the same thing.. tried with jackett, which works well with sonarr and gives errors on radarr.. downloaded pre-release version of radarr from github.. nothing really comes to mind anymore about trying to connect to indexers

Radarr Ver. 0.2.0.910 - develop

**Comment by galli-leo** [comment]
Can you guys share some logs? Also what mono version are you using (on the working as well as not working pis)? This is very likely due to a configuration issue, so closing this, but feel free to comment and I can see how I can help.
