### ISSUE TITLE
Migration from windows to synology: can't change root path

### ISSUE THREAD

**Issue by piejanssens** [Radarr/Radarr#2357]
Up to now I was running Radarr on a windows PC and the movies stored on my Synology NAS.
I now migrated radarr to my Syno and want to change the path of the movies from a network path to a local path. I'm using the bulk editor to change the path of my movies.
I can find the local path when I use the browse button, but when I confirm the path I get a message 
![image](https://user-images.githubusercontent.com/829098/34148671-8a28def8-e4a2-11e7-8470-cb7b35cca406.png)

The existing path for the movies is `\\192.168.1.2\video\movie` and I want to change it into `/video/movie/`.

**Comment by woble** [comment]
Below the input box there should be a list of paths. The one you are changing to should already be in that list, try just selecting it.

**Comment by piejanssens** [comment]
It wasn't. Meanwhile I have solved it by replacing all paths using sqllitebrowser in the db.
