### ISSUE TITLE
Custom RSS List

### ISSUE THREAD

**Issue by spencercharest** [Radarr/Radarr#2358]
**Description:**
I'm trying to develop some custom RSS feeds for the lists section. Some movies are not being picked up and I believe it is because Radarr is not able to get an exact match by searching for the given title. Is there any property I can include in the RSS feed to help guarantee a match? For instance, could I include an IMDB ID or maybe a TMDB ID?

Check first that your problem is not listed in our wiki section:
* https://github.com/Radarr/Radarr/wiki/Common-Problems
* https://github.com/Radarr/Radarr/wiki/FAQ

Provide a description of the feature request or bug here, the more details the better. 
Please also try to include the following if you are reporting a bug

**Radarr Version:**
0.2.0.910
**Logs:**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by galli-leo** [comment]
You could take a look at the rss list parser source code. Don’t remember that much, but you probably have to include the imdb id in either link or title attribute.

Closing this as it’s a question, but feel free to comment still.
