### ISSUE TITLE
New qualities needed

### ISSUE THREAD

**Issue by BEisem** [Radarr/Radarr#2360]
I've noticed a few new quality indicators used in filenames lately that aren't being picked up by Radarr, and as such, they are imported incorrectly with an HDTV quality:

WebUHD, which I assume is a web download in ultra HD, and
DCPRip, which I had to look up... 

https://en.wikipedia.org/wiki/Digital_Cinema_Package

I've seen several downloads appearing with both of these in the filename, and as I said, since Radarr doesn't recognize them, it is importing them as HDTV.

**Comment by onedr0p** [comment]
This is fixed in v3, still it is wise to rename your files accordingly before importing.
