### ISSUE TITLE
Download complete, but one particular movie does not want to move

### ISSUE THREAD

**Issue by bartdesign** [Radarr/Radarr#2362]
**Description:**
When downloading the movie Victoria's Secret Fashion Show 2017 (2017), it finds the movie fine but after downloading it stays in the download directory. I can playback to movie in VLC without any problems. Other movies download and get moved without any problems. 

**Radarr Version:**
Latest, 0.2.0.910
**Logs:**
17-12-21 20:59:38.9|Trace|ConfigService|Using default config value for 'downloadclienthistorylimit' defaultValue:'30' 17-12-21 20:59:38.9|Trace|ConfigService|Using default config value for 'parsingleniency' defaultValue:'Strict' 17-12-21 20:59:38.9|Debug|Parser|Parsing string 'The.Victoria's.Secret.Fashion.Show.2017 (h264-15mbps)' 17-12-21 20:59:38.9|Trace|Parser|^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(19|20)\d{2}(?!p|i|(19|20)\d{2}|\]|\W(19|20)\d{2})))+(\W+|_|$)(?!\\) 17-12-21 20:59:38.9|Debug|Parser|Movie Parsed. The Victoria's Secret Fashion Show - 2017 17-12-21 20:59:38.9|Debug|Parser|Language parsed: English 17-12-21 20:59:39.0|Debug|QualityParser|Trying to parse quality for The.Victoria's.Secret.Fashion.Show.2017 (h264-15mbps) 17-12-21 20:59:39.0|Debug|Parser|Quality parsed: Unknown v1 17-12-21 20:59:39.0|Debug|Parser|Release Group parsed: 15mbps 17-12-21 20:59:39.0|Trace|Owin|SQLite warning (284): automatic index on AlternativeTitles(MovieId) 17-12-21 20:59:39.0|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId) 17-12-21 20:59:39.0|Trace|Owin|SQLite warning (284): automatic index on AlternativeTitles(MovieId) 17-12-21 20:59:39.0|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId) 17-12-21 20:59:39.0|Trace|Owin|SQLite warning (284): automatic index on AlternativeTitles(MovieId) 17-12-21 20:59:39.0|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId) 17-12-21 20:59:39.0|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId) 17-12-21 20:59:39.0|Trace|Owin|SQLite warning (284): automatic index on AlternativeTitles(MovieId) 17-12-21 20:59:39.0|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId) 17-12-21 20:59:39.0|Trace|Owin|SQLite warning (284): automatic index on AlternativeTitles(MovieId) 17-12-21 20:59:39.0|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId) 17-12-21 20:59:39.1|Trace|Owin|SQLite warning (284): automatic index on AlternativeTitles(MovieId) 17-12-21 20:59:39.1|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId) 17-12-21 20:59:39.1|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId) 17-12-21 20:59:39.1|Trace|ConfigService|Using default config value for 'parsingleniency' defaultValue:'Strict' 17-12-21 20:59:39.1|Trace|ConfigService|Using default config value for 'parsingleniency' defaultValue:'Strict' 17-12-21 20:59:39.1|Debug|Parser|Parsing string 'The.Victoria's.Secret.Fashion.Show.2017 (h264-15mbps)' 17-12-21 20:59:39.1|Trace|Parser|^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(19|20)\d{2}(?!p|i|(19|20)\d{2}|\]|\W(19|20)\d{2})))+(\W+|_|$)(?!\\) 17-12-21 20:59:39.1|Debug|Parser|Movie Parsed. The Victoria's Secret Fashion Show - 2017 17-12-21 20:59:39.1|Debug|Parser|Language parsed: English 17-12-21 20:59:39.1|Debug|QualityParser|Trying to parse quality for The.Victoria's.Secret.Fashion.Show.2017 (h264-15mbps) 17-12-21 20:59:39.1|Debug|Parser|Quality parsed: Unknown v1 17-12-21 20:59:39.1|Debug|Parser|Release Group parsed: 15mbps 17-12-21 20:59:39.1|Trace|Owin|SQLite warning (284): automatic index on AlternativeTitles(MovieId) 17-12-21 20:59:39.1|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId) 17-12-21 20:59:39.1|Trace|Owin|SQLite warning (284): automatic index on AlternativeTitles(MovieId) 17-12-21 20:59:39.1|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId) 17-12-21 20:59:39.1|Trace|Owin|SQLite warning (284): automatic index on AlternativeTitles(MovieId) 17-12-21 20:59:39.1|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId) 17-12-21 20:59:39.1|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId) 17-12-21 20:59:39.2|Trace|Owin|SQLite warning (284): automatic index on AlternativeTitles(MovieId) 17-12-21 20:59:39.2|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId) 17-12-21 20:59:39.2|Trace|Owin|SQLite warning (284): automatic index on AlternativeTitles(MovieId) 17-12-21 20:59:39.2|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId) 17-12-21 20:59:39.2|Trace|Owin|SQLite warning (284): automatic index on AlternativeTitles(MovieId) 17-12-21 20:59:39.2|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId) 17-12-21 20:59:39.2|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId) 17-12-21 20:59:39.2|Trace|ConfigService|Using default config value for 'parsingleniency' defaultValue:'Strict' 17-12-21 20:59:39.2|Trace|ConfigService|Using default config value for 'downloadedmoviesfolder' defaultValue:'' 17-12-21 20:59:39.2|Trace|ConfigService|Using default config value for 'parsingleniency' defaultValue:'Strict' 17-12-21 20:59:39.2|Debug|Parser|Parsing string 'The.Victoria's.Secret.Fashion.Show.2017 (h264-15mbps)' 17-12-21 20:59:39.2|Trace|Parser|^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(19|20)\d{2}(?!p|i|(19|20)\d{2}|\]|\W(19|20)\d{2})))+(\W+|_|$)(?!\\) 17-12-21 20:59:39.2|Debug|Parser|Movie Parsed. The Victoria's Secret Fashion Show - 2017 17-12-21 20:59:39.2|Debug|Parser|Language parsed: English 17-12-21 20:59:39.2|Debug|QualityParser|Trying to parse quality for The.Victoria's.Secret.Fashion.Show.2017 (h264-15mbps) 17-12-21 20:59:39.2|Debug|Parser|Quality parsed: Unknown v1 17-12-21 20:59:39.2|Debug|Parser|Release Group parsed: 15mbps 17-12-21 20:59:39.3|Trace|Owin|SQLite warning (284): automatic index on AlternativeTitles(MovieId) 17-12-21 20:59:39.3|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId) 17-12-21 20:59:39.3|Trace|Owin|SQLite warning (284): automatic index on AlternativeTitles(MovieId) 17-12-21 20:59:39.3|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId) 17-12-21 20:59:39.3|Trace|Owin|SQLite warning (284): automatic index on AlternativeTitles(MovieId) 17-12-21 20:59:39.3|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId) 17-12-21 20:59:39.3|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId) 17-12-21 20:59:39.3|Trace|Owin|SQLite warning (284): automatic index on AlternativeTitles(MovieId) 17-12-21 20:59:39.3|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId) 17-12-21 20:59:39.3|Trace|Owin|SQLite warning (284): automatic index on AlternativeTitles(MovieId) 17-12-21 20:59:39.3|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId) 17-12-21 20:59:39.3|Trace|Owin|SQLite warning (284): automatic index on AlternativeTitles(MovieId) 17-12-21 20:59:39.3|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId) 17-12-21 20:59:39.3|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId) 17-12-21 20:59:39.3|Trace|Owin|SQLite warning (284): automatic index on AlternativeTitles(MovieId) 17-12-21 20:59:39.3|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId) 17-12-21 20:59:39.3|Trace|Owin|SQLite warning (284): automatic index on AlternativeTitles(MovieId) 17-12-21 20:59:39.3|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId) 17-12-21 20:59:39.3|Trace|Owin|SQLite warning (284): automatic index on AlternativeTitles(MovieId) 17-12-21 20:59:39.4|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId) 17-12-21 20:59:39.4|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId) 17-12-21 20:59:39.4|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId) 17-12-21 20:59:39.4|Trace|ConfigService|Using default config value for 'parsingleniency' defaultValue:'Strict' 17-12-21 20:59:39.4|Debug|Parser|Parsing string 'The.Victoria's.Secret.Fashion.Show.2017 (h264-15mbps)' 17-12-21 20:59:39.4|Trace|Parser|^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(19|20)\d{2}(?!p|i|(19|20)\d{2}|\]|\W(19|20)\d{2})))+(\W+|_|$)(?!\\) 17-12-21 20:59:39.4|Debug|Parser|Movie Parsed. The Victoria's Secret Fashion Show - 2017 17-12-21 20:59:39.4|Debug|Parser|Language parsed: English 17-12-21 20:59:39.4|Debug|QualityParser|Trying to parse quality for The.Victoria's.Secret.Fashion.Show.2017 (h264-15mbps) 17-12-21 20:59:39.4|Debug|Parser|Quality parsed: Unknown v1 17-12-21 20:59:39.4|Debug|Parser|Release Group parsed: 15mbps 17-12-21 20:59:39.4|Trace|Owin|SQLite warning (284): automatic index on AlternativeTitles(MovieId) 17-12-21 20:59:39.4|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId) 17-12-21 20:59:39.4|Trace|Owin|SQLite warning (284): automatic index on AlternativeTitles(MovieId) 17-12-21 20:59:39.5|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId) 17-12-21 20:59:39.5|Trace|Owin|SQLite warning (284): automatic index on AlternativeTitles(MovieId) 17-12-21 20:59:39.5|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId) 17-12-21 20:59:39.5|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId) 17-12-21 20:59:39.5|Trace|Owin|SQLite warning (284): automatic index on AlternativeTitles(MovieId) 17-12-21 20:59:39.5|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId) 17-12-21 20:59:39.5|Trace|Owin|SQLite warning (284): automatic index on AlternativeTitles(MovieId) 17-12-21 20:59:39.5|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId) 17-12-21 20:59:39.5|Trace|Owin|SQLite warning (284): automatic index on AlternativeTitles(MovieId) 17-12-21 20:59:39.5|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId) 17-12-21 20:59:39.5|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId) 17-12-21 20:59:39.5|Trace|Owin|SQLite warning (284): automatic index on AlternativeTitles(MovieId) 17-12-21 20:59:39.5|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId) 17-12-21 20:59:39.5|Trace|Owin|SQLite warning (284): automatic index on AlternativeTitles(MovieId) 17-12-21 20:59:39.5|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId) 17-12-21 20:59:39.5|Trace|Owin|SQLite warning (284): automatic index on AlternativeTitles(MovieId) 17-12-21 20:59:39.5|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId) 17-12-21 20:59:39.5|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId) 17-12-21 20:59:39.5|Debug|DownloadedMovieImportService|Unknown Movie The.Victoria's.Secret.Fashion.Show.2017 (h264-15mbps) 17-12-21 20:59:39.5|Trace|ConfigService|Using default config value for 'parsingleniency' defaultValue:'Strict' 17-12-21 20:59:39.5|Debug|Parser|Parsing string 'PSArips.com..Flatliners.2017.720p.BrRip.2CH.x265.HEVC-PSA' 17-12-21 20:59:39.6|Trace|Parser|^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(19|20)\d{2}(?!p|i|(19|20)\d{2}|\]|\W(19|20)\d{2})))+(\W+|_|$)(?!\\) 17-12-21 20:59:39.6|Debug|Parser|Movie Parsed. PSArips com Flatliners - 2017 17-12-21 20:59:39.6|Debug|Parser|Language parsed: English 17-12-21 20:59:39.6|Debug|QualityParser|Trying to parse quality for PSArips.com..Flatliners.2017.720p.BrRip.2CH.x265.HEVC-PSA 17-12-21 20:59:39.6|Debug|Parser|Quality parsed: Bluray-720p v1 17-12-21 20:59:39.6|Debug|Parser|Release Group parsed: PSA 17-12-21 20:59:39.6|Trace|Owin|SQLite warning (284): automatic index on AlternativeTitles(MovieId) 17-12-21 20:59:39.6|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId) 17-12-21 20:59:39.6|Trace|Owin|SQLite warning (284): automatic index on AlternativeTitles(MovieId) 17-12-21 20:59:39.6|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId) 17-12-21 20:59:39.6|Trace|Owin|SQLite warning (284): automatic index on AlternativeTitles(MovieId) 17-12-21 20:59:39.6|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId) 17-12-21 20:59:39.6|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId) 17-12-21 20:59:39.6|Trace|Owin|SQLite warning (284): automatic index on AlternativeTitles(MovieId) 17-12-21 20:59:39.7|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId) 17-12-21 20:59:39.7|Trace|Owin|SQLite warning (284): automatic index on AlternativeTitles(MovieId) 17-12-21 20:59:39.7|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId) 17-12-21 20:59:39.7|Trace|Owin|SQLite warning (284): automatic index on AlternativeTitles(MovieId) 17-12-21 20:59:39.7|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId) 17-12-21 20:59:39.7|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId)

**Comment by galli-leo** [comment]
The Problem is that the Movie title parsed by radarr does not match what radarr has stored for that movie. Not much we can do, try manual import.
