### ISSUE TITLE
Nzbget category reset after upgrade to v0.2.0.910 from v0.2.0.870

### ISSUE THREAD

**Issue by mike-tesch** [Radarr/Radarr#2363]
**Description:**

After upgrading, Radarr stopped processing movies after they were downloaded. They were successfully sent to the client, but afterwards Radarr did nothing. I noticed the download category was set to "Movies" when the actual category in Nzbget is "movies".

I opened the sqlite db from a backup and it had this:
`{
  "host": "nzbget",
  "port": 6789,
  "username": "",
  "password": "",
  "tvCategory": "movies",
  "recentTvPriority": 0,
  "olderTvPriority": 0,
  "useSsl": false,
  "addPaused": false
}`

Once I changed the setting in Radarr back to "movies" everything began processing correctly.

I suspect the fix for #2211 caused it to fall back to the default when the json is loaded with the old property name.

**Radarr Version:**
v0.2.0.910

**Logs:**
N/A

**Comment by fryfrog** [comment]
I saw this when I updated too.

**Comment by galli-leo** [comment]
Unfortunately not much we can do now that we already published the update :(
