### ISSUE TITLE
Radarr can't find certain anime movies; it should try and search using alternate names

### ISSUE THREAD

**Issue by yunyunls** [Radarr/Radarr#2364]
**Description:**

radarr is unable to find some anime movies. Perfect example of this is "Your Name". Now the issue is radarr doesn't check for movies with alternate names. What I mean is if after it searched for "Your Name" and I had no results it should check for "Kimi no na wa" which is the Japanese name for "Your Name" and it will have plenty of results for the movie.

Check first that your problem is not listed in our wiki section:
* https://github.com/Radarr/Radarr/wiki/Common-Problems
* https://github.com/Radarr/Radarr/wiki/FAQ

**Radarr Version:**
0.2.0.910
**Logs:**
Movie search completed. 0 reports downloaded.

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by yunyunls** [comment]
also since its probably will obviously be slow to search movies using different anime it would be bad to do this for every movie, so it could be an option to tell Radarr that the movie is an anime movie and it should use alternate names when searching for releases.

**Comment by woble** [comment]
No issues finding it here. Same radarr version.

**Comment by yunyunls** [comment]
Then I guess it must be something with my settings. I'll reset everything and check again.

**Comment by woble** [comment]
Check log for potential errors first.

**Comment by galli-leo** [comment]
Yeah Radarr already searches alternate names, however, if your indexer supports searching by imdbid, it will do that instead. So I am guessing the movies are not correctly tagged with the imdbid on your indexer. You can turn off searching by imdbid though.
