### ISSUE TITLE
Calender - Week Column Header - dd/mm setting doesnt apply to the calender.

### ISSUE THREAD

**Issue by dan-the-man-nz** [Radarr/Radarr#2365]
**Description:**
In radarr settings -> UI -there is a setting to change the Week Column Header from mm/dd to dd/mm.
changing this to Tue 25/3 or Tue 25/03  makes no difference to the calendar at all, it will keep on using mm/dd
It has never worked in Radarr for me since i started using it not long after the first release.

(in sonarr, this setting works correctly)

![image](https://user-images.githubusercontent.com/906806/34311170-dc4372b8-e7c0-11e7-8f0c-c2b89331c994.png)

![image](https://user-images.githubusercontent.com/906806/34311194-149eff74-e7c1-11e7-9964-33f9c5537435.png)

**Radarr Version:**  0.2.0.912 - Win 10 - Chrome and Firefox tested same issue

**Comment by galli-leo** [comment]
Duplicate issue (sorry on mobile so cannot link). Anyways I never reimplemented this option, since I updated the calendar lib sonarr uses.
