### ISSUE TITLE
Original title not picked form TMDB

### ISSUE THREAD

**Issue by matejzero** [Radarr/Radarr#2366]
**Description:**

When adding non-US movies, original title from TMDB is not added to Titles. Since search returns original titles (so I guess Radarr does search with original name as well), files are downloaded but not added to Radarr, since the title is not listed as part of the movie.

Example:

- Two is a family (original title Demain tout commence)
- Penny Pinch! (original title Radin!)

**Radarr Version:**
0.2.0.910

**Comment by galli-leo** [comment]
Original titles are not added since they are for a different language than your profile. They get added anyways because we usually search indexers using imdbid. We will probably redo what alt titles get added etc., but closing this for now because there’s one already open with a similar problem.

**Comment by matejzero** [comment]
Great! Thanks for info.
