### ISSUE TITLE
IMDB Lists not working

### ISSUE THREAD

**Issue by wouterverduin** [Radarr/Radarr#2370]
Guys  i would like to add movies through IMDB lists.
I used the following urls:
http://rss.imdb.com/user/urXXXX/watchlist
http://rss.imdb.com/list/lsXXXXX

The error i receive is: Unable to connect to indexer. Indexer responded with html content. Site is likely blocked or unavailable.

Anyone know a solution?

**Radarr Version: 0.2.0.852**

**Comment by GCsabi** [comment]
Hi there,
the same issue here.

**Radarr Verson: 0.2.0.910**

**Comment by galli-leo** [comment]
Please search existing issues, this is already addressed in another one.
