### ISSUE TITLE
All that is shown is Radarr Ver.

### ISSUE THREAD

**Issue by ckersey2** [Radarr/Radarr#2373]
All that is shown when opening the browser in the Mac OSX version is Radarr Ver.

![8af4b002-8fbf-4f81-999f-47317ecca66d](https://user-images.githubusercontent.com/13756203/34426421-51b549ee-ec04-11e7-8198-3a88e479c7d1.jpeg)

I don’t know how to get logs without getting into the web app

Check first that your problem is not listed in our wiki section:
* https://github.com/Radarr/Radarr/wiki/Common-Problems
* https://github.com/Radarr/Radarr/wiki/FAQ

Provide a description of the feature request or bug here, the more details the better. 
Please also try to include the following if you are reporting a bug

**Radarr Version:**

v0.2.0.910

**Logs:**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by galli-leo** [comment]
See the wiki for how to get to your log dir. I am guessing your db is corrupted based on you being on osx. If you see something like that in the log, there is also a wikipage for that.
