### ISSUE TITLE
Radar ignoring Quality Limits???

### ISSUE THREAD

**Issue by darrenclimienewman** [Radarr/Radarr#2374]
Hi All,

Is there a known issue with Radarr ignoring the quality limits set?

I've set my maximum file size for all profiles to 6GB, I've woke up this morning to an email from PlexPy telling me it's added a monitored movie that is 12.2GB?!

I've checked the file itself, and it is indeed 12.2GB.

Is this a known issue?

**Comment by galli-leo** [comment]
How long is the movie? This is either because the movie is long (Radarr calculates the max file size per minute of movie runtime) or because your indexer gave wrong info about the filesize. Regardlessly, Radarr is functioning correctly in this regard so closing.

**Comment by darrenclimienewman** [comment]
Hi.

I disagree. It's a 1080p movie and is 2hrs 15mins long. 

I have the max for a 90min movie set to 4.47GB and a 140min movie is 6.96GB. The movie falls 5mins short of the 140min limit set, yet still downloaded a 12.2GB file?

I have all of my profile qualities set to the same, so nothing should be anywhere near 12.2GB surely??

Thanks

**Comment by galli-leo** [comment]
Then your indexer had an error when reporting the filesize to Radarr. I can assure you that this part of Radarr has always worked unless your indexer does something wrong.
