### ISSUE TITLE
bulk change via Movie Editor does not work for Static Path

### ISSUE THREAD

**Issue by firex2** [Radarr/Radarr#2375]
**Description:**
if i want to edit all my movies, the setting is not saved to my movies. For example, if i want to bulk change Static Path from Yes to No via the Movie Editor it does not apply the new setting to my movies. It does work if i set the setting individually per movie.

**Radarr Version:**
0.2.0.910

**Comment by galli-leo** [comment]
Works for me. Have you verified that you selected No instead of No Change (difficult to see on small screens). Also do you have any debug logs available?

**Comment by janscarton** [comment]
Can confirm that this isn't working for me in v2.0.0.5252.

Steps to repro:

1. fire up movie editor at /movieeditor
2. check movie(s)
3. select Static Path: No option at bottom of screen
4. press the Organize button

**Comment by DeKemp** [comment]
Still broken.

**Comment by Qstick** [comment]
Nothing will change on this on v0.2, it's already handled in v3
