### ISSUE TITLE
Amend the FreeNAS Jail guide in your Wiki 

### ISSUE THREAD

**Issue by conanius** [Radarr/Radarr#2377]
Hi All,

Apologies if this is wrong to put down as an issue or not - first time githuber.

Trying to install Radarr v0.2.0.910 on FreeNAS-11.1-RELEASE

I followed the guide listed https://github.com/Radarr/Radarr/wiki/Installation however noticed it wouldn't let me connect to the web GUI.

After SSH'ing into the Jail and trying to manually start the service, I kept getting:

root@radarr_1:/etc/rc.d # srvice radarr start
[Info] Bootstrap: Starting Radarr - /usr/local/Radarr/Radarr.exe - Version 0.2.0.910
[Info] Router: Application mode: Interactive
[Info] MigrationLogger: *** Migrating data source=/.config/Radarr/nzbdrone.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
/usr/local/lib/libsqlite3.so: Undefined symbol "fdatasync"

Looking around, this is being caused by the latest version of sqlite3, and the best option is to add the following to the very top of your FreeNAS guide for now:
pkg lock sqlite3

That seems to work - Information found on redit here - 
https://www.reddit.com/r/freenas/comments/7l2wao/radarr_wont_start_in_freenas_111/
credit to Ebbb for posting the fix there

Happy to try some other fixes if it helps, so I'll keep that Jail active.

**Comment by galli-leo** [comment]
You can edit the wiki as well :)

**Comment by conanius** [comment]
Aha superb - I’ll put it in with a comment tomorrow 👍

**Comment by emckenna** [comment]
Added new section to wiki about upgrading Radarr jail and recovering from the sqlite version update.

https://github.com/Radarr/Radarr/wiki/Installation#manually-update-radarr-from-within-jail
