### ISSUE TITLE
Information regarding JSON response format for custom list

### ISSUE THREAD

**Issue by cwhite92** [Radarr/Radarr#2378]
**Description:**

I'm trying to develop my own API that returns a JSON document that I can then add to Radarr as a list, but I'm having trouble finding any documentation on what kind of JSON representation my API needs to return to be compatible with Radarr.

I had a look at the preset Radarr IMDB top 250 list as an example: https://api.radarr.video/v2/imdb/top250

but this has a lot of fields that I won't be able to provide (`clean_title`, `genres` etc).

Is there any documentation at all for this?

**Radarr Version:** 0.2.0.910

**Comment by galli-leo** [comment]
You can take a look at the RadarrAPI.TMDB source code. Most of it isn’t necessary, but some stuff is nice to have like poster urls.

Closing this as it is not an issue. Feel free to keep the conversation up though.
