### ISSUE TITLE
problem on snatch with caps letter

### ISSUE THREAD

**Issue by valantislevas** [Radarr/Radarr#2379]
**Description:**
Problem on snatch with caps letters 

**Version
    0.2.0.910
Mono Version
    5.4.1.6 (tarball Wed Nov 8 20:37:08 UTC 2017)**

**Logs:**

http://prntscr.com/hujn0c

**Comment by galli-leo** [comment]
The Problem is that the title is twice before the year. Either enable lenient mapping or force download the movie.
