### ISSUE TITLE
Folder rename uses wrong language, does not use rename pattern

### ISSUE THREAD

**Issue by murrayju** [Radarr/Radarr#2382]
**Description:**
The folder rename is using a foreign (non-english) language for some (but not all) movies. Also, no matter how I configure the folder rename pattern, the result is always the same.

Here's a screenshot:
![image](https://user-images.githubusercontent.com/508461/34464166-960aa5cc-ee42-11e7-8704-03b119326688.png)

**Radarr Version:**
0.2.0.910

**Comment by galli-leo** [comment]
This is fixed in the latest release.

**Comment by galli-leo** [comment]
(Wont automatically rename the folder though)

**Comment by murrayju** [comment]
@galli-leo is there any way to force a rename on these? I still have tons of folders in foreign languages. Clicking the preview rename button doesn't do much:

![image](https://user-images.githubusercontent.com/508461/42551415-56496778-8494-11e8-9d5f-568df40223b3.png)
