### ISSUE TITLE
Force Download not working

### ISSUE THREAD

**Issue by cutzenfriend** [Radarr/Radarr#2384]
As soon as I want to force download something I click the button but nothing happens. Console gives me this error 500. The Movies is not added to DL Client :( 

<img width="811" alt="bildschirmfoto 2018-01-01 um 12 36 13" src="https://user-images.githubusercontent.com/1510611/34467404-efbe040c-eef0-11e7-953b-6809978cc5aa.png">

{
  "message": "Movie with ID 0 does not exist",
  "description": "NzbDrone.Core.Datastore.ModelNotFoundException: Movie with ID 0 does not exist\n  at NzbDrone.Core.Datastore.BasicRepository`1[TModel].Get (System.Int32 id) [0x0009d] in C:\\projects\\radarr-usby1\\src\\NzbDrone.Core\\Datastore\\BasicRepository.cs:79 \n  at NzbDrone.Core.Tv.MovieService.GetMovie (System.Int32 movieId) [0x00000] in C:\\projects\\radarr-usby1\\src\\NzbDrone.Core\\Tv\\MovieService.cs:142 \n  at NzbDrone.Api.Movie.AlternativeTitleModule.AddTitle (NzbDrone.Api.Movie.AlternativeTitleResource altTitle) [0x00007] in C:\\projects\\radarr-usby1\\src\\NzbDrone.Api\\Movies\\AlternativeTitleModule.cs:44 \n  at NzbDrone.Api.REST.RestModule`1[TResource].<set_CreateResource>b__41_0 (System.Object options) [0x00000] in C:\\projects\\radarr-usby1\\src\\NzbDrone.Api\\REST\\RestModule.cs:161 \n  at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)\n  at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, System.Threading.CancellationToken context) [0x00049] in <63c44d6f8d7e4f339a987bf9eb94d931>:0 "
}

System: Debian Stretch
Version: 0.2.0.910 - 14 Dec 2017

**Comment by lattedesu** [comment]
Same issue here.

I had the exact same issue with the movie "Much Ado About Nothing".

Using on Debian 9 with mono. Everything else works so far.

**Comment by lattedesu** [comment]
Here's the screenshot of my issue:

![image](https://user-images.githubusercontent.com/20868080/35197367-61d515e0-feef-11e7-9c3e-46dda6a17b96.png)

Here's the request payload to /api/alttitle:

```json
{"movieId":0,"title":"Much Ado About Nothing","language":"english"}
```




Here's the response to /api/alttitle endpoint:


```json
{
  "message": "Movie with ID 0 does not exist",
  "description": "NzbDrone.Core.Datastore.ModelNotFoundException: Movie with ID 0 does not exist\n  at NzbDrone.Core.Datastore.BasicRepository`1[TModel].Get (System.Int32 id) [0x0009c] in <884e16c464ab4f8e8e8fa9d52993441e>:0 \n  at NzbDrone.Core.Tv.MovieService.GetMovie (System.Int32 movieId) [0x00000] in <884e16c464ab4f8e8e8fa9d52993441e>:0 \n  at NzbDrone.Api.Movie.AlternativeTitleModule.AddTitle (NzbDrone.Api.Movie.AlternativeTitleResource altTitle) [0x00013] in <739da39f7b5b4c67aa99a3b2da6037bc>:0 \n  at NzbDrone.Api.REST.RestModule`1[TResource].<set_CreateResource>b__41_0 (System.Object options) [0x0000d] in <739da39f7b5b4c67aa99a3b2da6037bc>:0 \n  at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)\n  at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, System.Threading.CancellationToken context) [0x00049] in <63c44d6f8d7e4f339a987bf9eb94d931>:0 "
}
```

So I'm guessing something is wrong on the client side before sending the AJAX request.

I'd appreciate if this could be checked.

Thanks in advance,

**Comment by galli-leo** [comment]
Force downloading doesn’t work when there isn’t a year in the filename. (That’s why no icon is there, it should not be clickable that’s a UI bug, but it’s already tracked.

**Comment by kronnnnnn** [comment]
Have a similar issue with Force Download and this ones has a year in the filename. 

![image](https://user-images.githubusercontent.com/5401067/35205047-f189bfa8-fef7-11e7-9fa5-34fd6339511a.png)

**Comment by biscuitboy1980** [comment]
Same issue here.  Filename has a date that is a year before the movie came out.
![force download](https://user-images.githubusercontent.com/8532358/36998748-3ba432ea-207b-11e8-9770-741ac5e8bc05.png)

**Comment by galli-leo** [comment]
@kronnnnnn Can you please provide some logs? No idea what's going wrong without them...

@biscuitboy1980 Well currently the api is down, so no wonder it's not working :/

**Comment by koper89** [comment]
Same issue:

  | NzbDroneErrorPipeline | Request  Failed: Error while calling api: Unprocessable Entity Full error(s): Unprocessable Entity (422, RayId:  dd0fbb20-7580-4611-8400-f0390f7e5bf9), Details: The movie with the given  tmdbid could not be found! | 2:36am
-- | -- | -- | --
  | NzbDroneErrorPipeline | Request  Failed: Error while calling api: Unprocessable Entity Full error(s): Unprocessable Entity (422, RayId:  66e0798e-4d87-427c-ac2d-4ce6a8f46c55), Details: The movie with the given  tmdbid could not be found! | 2:36am
  | NzbDroneErrorPipeline | Request  Failed: Error while calling api: Unprocessable Entity Full error(s): Unprocessable Entity (422, RayId:  d7a41e5d-3b8f-4362-80bc-7a982d5e4a71), Details: The movie with the given  tmdbid could not be found! | 2:36am
  | DownloadDecisionMaker | Processing 2 releases | 2:36am


``
