### ISSUE TITLE
File both downloaded & missing simultaneously

### ISSUE THREAD

**Issue by arette** [Radarr/Radarr#2385]
When I download movies, everything works great but, at the end, Radarr seems to be confused as to the state of the final file on disk (see images below showing it knows it renamed to /Movies so it should show under Files then).  If I force a 'update movie info and scan disk', it then finds it but I'd expect this to be automatic unless there is some sort of race condition here.  Note that I am using copy rather than hardlink if it matters.

![2018-01-01 09_56_06-movies - radarr](https://user-images.githubusercontent.com/12751515/34468635-2372283e-eedb-11e7-8d35-976fd37d324a.png)
![2018-01-01 09_58_31-21 jump street - radarr](https://user-images.githubusercontent.com/12751515/34468636-24c2754a-eedb-11e7-93de-21ba0b9aa011.png)
![2018-01-01 09_56_25-21 jump street - radarr](https://user-images.githubusercontent.com/12751515/34468638-2616af42-eedb-11e7-9482-d00c738dbd59.png)

**Comment by arette** [comment]
something may be buried in one of these:
[radarr.trace.1.txt](https://github.com/Radarr/Radarr/files/1596136/radarr.trace.1.txt)
[radarr.trace.txt](https://github.com/Radarr/Radarr/files/1596137/radarr.trace.txt)
[radarr.trace.0.txt](https://github.com/Radarr/Radarr/files/1596138/radarr.trace.0.txt)

**Comment by arette** [comment]
think I solved this by changing 'Movie Paths Default to Static' setting back to 'yes'.  I guess this makes some sense; it means that if you want to customize folder names, you will have to explicitly scan disk to find files even when the renamer knows all the details.  Maybe a feature request in there somewhere...not a big deal for me since I stick with default folder names.

**Comment by galli-leo** [comment]
This should be fixed on the latest release. Also make sure you give your browser a refresh, since it won't update on the details page else.
