### ISSUE TITLE
Allow multiple versions of movies (extended, director's cut, 3D)

### ISSUE THREAD

**Issue by thejacer87** [Radarr/Radarr#2387]
just stumbled across this [multi-version naming convention for emby](https://github.com/MediaBrowser/Wiki/wiki/Movie%20naming#multi-version-movies)

I was just thinking about LOTR, I have the extended versions. But thought that my users might not really want 4hrs per movie lol. Also I have some other versions of star wars movies (anti-cheese edit). I know some would like different quality types too, which i assume this would cover as well. Although I feel like transcoding is better than the wasted disk space. but just thought the naming convention was good (I assume Plex is similar) **edit:** ya just checked, plex is the same. but i thought maybe a setting could be "Multiple Version Separator" where the user would enter it (` - ` by default)

if there is a branch with some work on this already, please link it and it can try to lend a hand.

**Comment by fryfrog** [comment]
This is already a feature request on https://feathub.com/Radarr/Radarr/+129, comment and vote for it there. I'd suggest this issue can be closed as a duplicate.

**Comment by galli-leo** [comment]
There is also a GitHub issue already.
