### ISSUE TITLE
Radarr stops working few minutes after starting without any issues showing up in the log

### ISSUE THREAD

**Issue by piejanssens** [Radarr/Radarr#2388]
**Description:**
When the Radarr package is started it first seem to work fine, any page loads up. There is no functionality that is not working or that is producing an error in the logs. It seems as if after a certain time (minutes) it suddenly stops loading the web pages and when I press refresh I eventually get "504 Gateway Timeout" errors over and over until I stop and start Radarr again.

**Radarr Version:** 
Synology: DSM 6.1
Mono: Stable 4.2.1.124
Radarr: 0.2.0.910

**Logs:**
[radarr.trace.txt](https://github.com/Radarr/Radarr/files/1597347/radarr.trace.txt)

**Comment by galli-leo** [comment]
Do you have a reverse proxy?

**Comment by piejanssens** [comment]
Yes (dsm 6 built in). Meanwhile I have worked my way around it. I installed mono 5.4 and it's now running Ok. I do suffer from the net socket error when it's polling nzbget. I read somewhere that this would be fixed in mono 5.4.x, so that is at least for me not the case.

**Comment by galli-leo** [comment]
Hmm seems like an issue with mono then. Maybe timeout on your reverse proxy is too low and after a few minutes requests to the Radarr backend just take a little bit too long.

**Comment by piejanssens** [comment]
Are there any known issues with the built in DSM 6.x reverse proxy?
I just started importing my existing movies (300-something) and after just a couple I saw the Radarr message "connection to backend lost" after that I did reload and now I see a "504 gateway time-out".
Just when I thought everything was a-okay again.

**Comment by piejanssens** [comment]
@galli-leo I can see from tailing the log that it's downloading posters, so it's probably still doing the bulk import. Could this be the cause of the web UI not being able to load up?
There is something very strange though, I notice at least for a few movies that it's downloading the (same?) poster again and again. I'll leave it running and hope that it will finish sometime. 
Kindly ask you to reopen for now.
This is the log so far: 
[radarr.txt](https://github.com/Radarr/Radarr/files/1602880/radarr.txt)

FYI the timeout for the http requests that you see is related to https://bugzilla.xamarin.com/show_bug.cgi?id=19913 - 

```
In .NET, the timeout value on a request is not in effect until the request gets sent. Therefore you see some calls to GetResponse() taking longer than the configured timeout if the request can't be made for a while due to heavy load.

In Mono on the other hand, the timeout is in effect as soon as GetResponse is called. So if a request needs to wait for a while, you could see a timeout error before the request gets sent, or at least sooner than you would see it in .NET.
```

Because Radarr retries to download it is not a problem, unless there is a bug and Radarr keeps retrying even though it does download it correctly at one time? That could explain why I keep seeing some movie posters for the same movies being downloaded again and again.

**Comment by piejanssens** [comment]
There is definitively some bug in Radarr, while it keeps downloading (some) posters without any error. The size of the MediaCover directory is not changing. This means it's not downloading any new covers that do not exist on the filesystem yet. But for some reason it keeps trying to download them over and over.

**Comment by piejanssens** [comment]
OK, so the 'some reason' part is because there is another HTTP request taking place which is not being traced/catched. https://github.com/Radarr/Radarr/blob/7cfa0531dc81dbb28d966c9c99b811e8dcc04ccd/src/NzbDrone.Core/MediaCover/CoverAlreadyExistsSpecification.cs#L40
If that fails the poster should not be downloaded at this time IMO.

**Comment by piejanssens** [comment]
The poster.jpg files all seem to have size 0... 
That could be a mono issue, but anyway the retry limit of 3 is not working as it should and that is a Radarr bug.
