### ISSUE TITLE
Also Known As Multiple Entries On Some Movies

### ISSUE THREAD

**Issue by RyanAStrouse** [Radarr/Radarr#2390]
**Description:**
I noticed that for some movies there are repeated entries for "Also Known As" section. I can manually go into the database file and remove them, but it would be a lot easier if I could do it from somewhere in the app. Either way, figured it should be reported. I'm not sure when it started happening though. Picture is included!

<img width="962" alt="radarr issue" src="https://user-images.githubusercontent.com/4588529/34522179-74c7b476-f05f-11e7-9355-55b4a8b0ecf8.png">

**Radarr Version:**
Version 0.2.0.852

**Comment by galli-leo** [comment]
Try upgrading your Radarr version. This was fixed a month or so ago. (Even removing old akas)

**Comment by RyanAStrouse** [comment]
Ah yes, that did the trick. I use dockers and don't always notice when they go out of date :/
