### ISSUE TITLE
WebUI does not show status of downloads after nightly update

### ISSUE THREAD

**Issue by seanvree** [Radarr/Radarr#2391]
**Environment**:
OS:  Windows 10E x64 1709 FCU
Radarr version:  Radarr Ver. 0.2.0.910 (develop)  / Radarr.0.912 (nightly) 
- Was on the nightly build, I rolled back assuming it was a bug in the nightly, but the develop branch is also doing it. 

**Description:**

As per conversion on Discord w/ @fryfrog 

Radarr is not showing the status of downloads.  Just started happening today, 1/3 after the nightly update.    Radarr is still snatching releases and post-processing them, however, the status of those downloads will never show in the status window . . . history tab is fine.  

Downloaders:  Sabnzbd, Deluge.   Both test fine. Have tried both SSL and NON-SSL.

Tested the web UI on two diff machines, both incognito. 

![radarr](https://user-images.githubusercontent.com/8906637/34543696-20b9299a-f097-11e7-853e-73c04787acec.PNG)

![radarr5](https://user-images.githubusercontent.com/8906637/34543701-26500df6-f097-11e7-8d70-bdffe0f5e656.PNG)

![radarr3](https://user-images.githubusercontent.com/8906637/34543834-cc6dc368-f097-11e7-92c5-ea81feb0a2f2.PNG)

**Logs:**

https://gist.github.com/seanvree/6d760e471ae2b98447dc8c64a075a204

**Comment by galli-leo** [comment]
Nothing really helpful in the logs. Maybe the Scan for finished downlod command is stuck? Can you try removing that from the ScheduledTasks Table?

**Comment by seanvree** [comment]
@galli-leo  so the weird thing is that it is still processing the releases in the background as normal. SO it appears to be just a UI thing? 

![image](https://user-images.githubusercontent.com/8906637/34576412-b41cd5ba-f132-11e7-8165-cae6e0400220.png)

**Comment by seanvree** [comment]
OKay, I"m not sure WTF is going on, but it's working now.  Srsly. that was weird.  Happened for like 48 hours straight.
