### ISSUE TITLE
CouchPotato List Import Invalid Path

### ISSUE THREAD

**Issue by Verminaardd** [Radarr/Radarr#2392]
Hello

I have an existing CouchPotato list. Trying to import. "Test" says connection successful but when I try to save and add, this is what I see:
![image](https://user-images.githubusercontent.com/35092565/34552567-3ebfd88e-f133-11e7-9d64-c4f509e1c626.png)
Under the pull down menu for the folder there is nothing to choose.

**This is how it looks like in the logs:**
![image](https://user-images.githubusercontent.com/35092565/34552535-12ecf7f0-f133-11e7-85bc-a468dacf8645.png)

**Current Config**
Radarr Version: 0.2.0.910
Windows 7 Ultimate x64
Chrome Version 63.0.3239.108 (Official Build) (64-bit)
Everything is installed and running on the same (this) computer.

-----------------------------------------------------------------------------------------

**Comment by dny238** [comment]
I have the same issue

**Comment by galli-leo** [comment]
Well you have to set a path there for the movies to go.

**Comment by Verminaardd** [comment]
> Well you have to set a path there for the movies to go.

Seriously? How? It's a pull down menu and there's nothing there.

**Comment by galli-leo** [comment]
You first have to search for any movie and add the path there. It's unintuitive, I know. It's on my list of things to fix.
