### ISSUE TITLE
Cutoff Unmet but it should be met

### ISSUE THREAD

**Issue by themana** [Radarr/Radarr#2395]
Cutoffs Unmet showing for files labeled Blu-Ray 1080p when cutoff is Blu-Ray 720p

Screenshots attached

**Radarr Version:0.2.0.910**

![image](https://user-images.githubusercontent.com/35144562/34617123-f8980c0a-f1ff-11e7-82a9-649622ff5e95.png)

![image](https://user-images.githubusercontent.com/35144562/34617203-3825c7c2-f200-11e7-841c-5ca6347b3fe7.png)

**Comment by fryfrog** [comment]
Your profile looks good w/ 720p below 1080p. All are checked. Your screen shot has the solid gray for the quality that indicates cutoff is met. Where are you seeing it say cutoff *isn't* met for this?

**Comment by themana** [comment]
Because it still shows up as Quality Unmet in the list.

![image](https://user-images.githubusercontent.com/35144562/34739309-7db6949e-f541-11e7-8e91-a7a703c96e59.png)

**Comment by themana** [comment]
Found another file I had from a previous version of the movie, it was probably seeing that and adding it to the cutoff list even though the profile showed it had met the cutoff. Once I deleted the other file it stopped showing up in the Cutoff Unmet List. This can be closed.

Thank you

**Comment by fryfrog** [comment]
Ah yeah, having multiple versions of a movie file really confuses Radarr :/
