### ISSUE TITLE
Year in file name different to year in folder name

### ISSUE THREAD

**Issue by mattmac24** [Radarr/Radarr#2397]
When trying to add the movie "The Cure for Wellness", something strange is going on with the year. The file name and path Radarr creates is ".../The Cure for Wellness (2017)/The Cure for Wellness (2016).mkv"

https://www.themoviedb.org/movie/340837-a-cure-for-wellness

This is causing me some problems and I don't understand why/how it is doing this. I have deleted the movie in Radarr and reimported the file and the same thing is happening. If I manually change the folder name to match tMDB then radarr thinks the movie has been deleted and attempts to redownload.

Whats going on?
 
Radarr Version: 0.2.0.910
Mono Version: 5.4.1.6
<img width="1364" alt="screenshot 2018-01-06 22 28 36" src="https://user-images.githubusercontent.com/3910627/34644274-867b5868-f333-11e7-90ad-b908cf6a419f.png">

**Comment by Qwatuz** [comment]
Different databases report different release dates. It came out in Feb 2017, but first showed at a film festival or premiered in Dec 2016.

**Comment by mattmac24** [comment]
Yes, I think that is where the issue is coming from. But, I do not actually care which one it uses, as long as it is consistent within Radarr. As you can see in the screenshot it is using 2017 for the folder name but 2016 for the file name, which is causing issues.

**Comment by galli-leo** [comment]
Problem here is that when we first set the path in Radarr we use the TMDB year, which isn’t the earliest one. The earliest release year is only known to Radarr later when we rename the file. This is already discussed in another issue, not sure when or if we will fix this.

**Comment by mattmac24** [comment]
Are you talking about this [thread](https://github.com/Radarr/Radarr/issues/2394)? If not can you please show me the correct issue?

This issue came up again for me today with the movie [mother!](https://www.themoviedb.org/movie/381283-mother) in a slightly different way. I wind up with a folder having a capital M and a movie name with a lowercase m which is causing my scripts to break.

Is there no easy way Radarr can be fixed to be consistent in the way it names movies?

Thanks
