### ISSUE TITLE
Import Fails

### ISSUE THREAD

**Issue by Bannister3000** [Radarr/Radarr#2398]
Fresh Install, on machine with content, but unable to import ANY files into DB.

Version  0.2.0.910

ParsingService | Unable to parse movie info from path D:\Movies\*blah*..........
SkyHookProxy | Couldn't map movie *blah*....................

So having looked around on here unable to see any info about this.

This is a new user, fresh install, and unable to get any content to mount.
The above to lines show in the log several times over.

Any pointers welcome.  If i've missed some info need please let me know, and thanks in advance!

**Comment by fryfrog** [comment]
If you've setup Radarr as a service, it is probably running as SYSTEM and might be better running as yourself. Maybe it can't read the files?

Are your movies in the structure Radarr expects? Needs to be `Movie Title (Year)/Movie Title (Year).ext` and I *strongly* recommend going further w/ the file name being more like `Movie Title (Year) Edition [Quality-Resolution].ext`. You can use filebot to get your existing collection into good shape, there is even a wiki article about it.

**Comment by Bannister3000** [comment]
Hi ya FryFrog, Thanks for the reply.  

Good point, yes its running as a service and confirmed as such. But have tried it as a app and as a service it has seemed to make a difference.

Any content has been run through filebot as it happens already. Using the 2nd format Title (Year)....

With this in mind kinda why I thought to ask... I can't seem to figure out whats happening!

**Comment by fryfrog** [comment]
Running as a service is fine, just make sure you change the *user* the service runs as from SYSTEM to *your* username. It'll make your life easier.

I don't understand your file naming content. Every movie *file* has to be in a *folder* named after the movie and year. You can't have a Movies directory full of movie *files*. Instead, you have a Movies folder full of movie *folders* with a single movie *file* in each one. Know what I mean?

Support is better on the Discord, I'd suggest going there.

**Comment by Bannister3000** [comment]
LOL as you said it, the penny dropped.

It's my fault - nothing we've done.  But it is the formatting thats the issue.

1 folder with all the files in, not movies root folder - folder of movie - movie

Its a shame you need a folder for every film - not just one with all of them in... But found out why!  

Thanks FryFrog glad I've found the reason now!
