### ISSUE TITLE
Movies added to Deluge don't automatically start

### ISSUE THREAD

**Issue by rlambert27** [Radarr/Radarr#2401]
**Description:**

Hello, I just switched to Radarr from CouchPotato and I love it. I've just run into one issue and no searching has found any solution.

I use Deluge on Ubuntu 16.04. Radarr is connected to Deluge and has no issues. However when it adds torrents (using torrent files) they don't auto-start. They just sit there and eventually they will start but I don't know why or how.

I did a test and restarted my Raspberry Pi 3 that hosts the Deluge service and if I reboot the device the torrents suddenly start downloading.

I also tested by manually adding a torrent file and it will start right away downloading, it's only torrents sent to Deluge from Radarr that don't auto-start.

I started comparing the info and the only difference I can see with, SickRage torrents, for example is that in Deluge it is not adding the "Private" flag. I'm not sure if this is the issue.

**Radarr Version:**
Version
0.2.0.910

Deluge version is 1.3.15.

I'm on Ubuntu 16.04.

Thoughts?

**Comment by fryfrog** [comment]
Are the torrents literally being added in a paused state? If so, double check your downloader settings and make sure you don't have it set to add paused or something like that.

If they're *stalled*, then I'm not sure... but I occasionally see it even on my rTorrent setup. A restart of my rTorrent docker container often solves it and life is better again. Super frustrating that there isn't an NZBGet or SABnzbd quality torrent daemon. :/

**Comment by Quiksmage** [comment]
if it's a private site, and private isn't ticked, that is indeed going to be a problem.

However, I cannot reproduce this myself. I'm using deluge without issue on the same version of radarr.

Can you try renaming your deluge config folder to a .old and see if the problem still persists?

**Comment by galli-leo** [comment]
I am too using Deluge with Radarr and haven't seen any such problems. Maybe your Radarr label defaults to add torrents as paused?
