### ISSUE TITLE
[Feature] Custom download directory setting for Deluge

### ISSUE THREAD

**Issue by h0lylag** [Radarr/Radarr#2403]
Hello everyone,

I would like to request to be able to set a custom download directory with Deluge. I see that it is an option existing with a few other clients already. The ability to download movies in their own folder named after the title of the movie like Media/Movies/{Movie TitleThe} ({Release Year}) would be great. 

Thank you for all the hard work.

**Comment by galli-leo** [comment]
Radarr will do that automatically after deluge downloaded it.

**Comment by h0lylag** [comment]
Hi, 

I'm not tralking about post processing. In fact I want to skip post processing by doing this. I want Deluge to be fed custom download directories per each torrent, that have the title of the film in the path.

**Comment by galli-leo** [comment]
But why? Just let Radarr do it, this will never get added anyways.
