### ISSUE TITLE
nginx reverse proxy

### ISSUE THREAD

**Issue by justlookingaround12** [Radarr/Radarr#2404]
**Description:**
So i've set up nginx for sonarr and i am doing the same for radarr reverse proxy. I followed the wiki and although the nginx config was a little different than my sonarr config i copied that exactly. however now when i go to mydomain.com/radarr, i get a 404 Not Found error. if i go to mydomain.com:port/radarr it works just fine. I have even edited the service so that it is run as root and that didn't seem to fix the issue either. Any ideas?
Check first that your problem is not listed in our wiki section:
* https://github.com/Radarr/Radarr/wiki/Common-Problems
* https://github.com/Radarr/Radarr/wiki/FAQ

Provide a description of the feature request or bug here, the more details the better. 
Please also try to include the following if you are reporting a bug

**Radarr Version:**
latest
**Logs:**
non

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by galli-leo** [comment]
You need to set your url base in the general settings.
