### ISSUE TITLE
Repeated "[renamemoviefolder] completed" messages

### ISSUE THREAD

**Issue by markpud** [Radarr/Radarr#2405]
Hi, I'm seeing a stream of messages from radarr saying "[renamemoviefolder] completed", even though I have the rename movies option turned off. I'm not clear why this is happening?

Using ver 0.2.0.910

Screenshot attached, here is a snippet of the logs:

17-12-31 09:28:30.3|Info|DiskScanService|Scanning disk for The Magnificent Seven
17-12-31 09:28:30.7|Info|DiskScanService|Completed scanning disk for The Magnificent Seven
17-12-31 09:28:30.7|Info|RefreshMovieService|Skipping refresh of movie: Man on a Ledge
17-12-31 09:28:30.8|Info|RenameMovieFileService|Renaming movie folder for Man on a Ledge
17-12-31 09:28:31.4|Info|DiskScanService|Scanning disk for Man on a Ledge
17-12-31 09:28:32.4|Info|DiskScanService|Completed scanning disk for Man on a Ledge
17-12-31 09:28:32.4|Info|RefreshMovieService|Skipping refresh of movie: The Man Who Fell to Earth
17-12-31 09:28:32.4|Info|RenameMovieFileService|Renaming movie folder for The Man Who Fell to Earth
17-12-31 09:28:34.1|Info|DiskScanService|Scanning disk for The Man Who Fell to Earth
17-12-31 09:28:35.0|Info|DiskScanService|Completed scanning disk for The Man Who Fell to Earth
17-12-31 09:28:35.1|Info|RefreshMovieService|Skipping refresh of movie: The Man with the Golden Arm
17-12-31 09:28:35.1|Info|RenameMovieFileService|Renaming movie folder for The Man with the Golden Arm
17-12-31 09:28:35.7|Info|DiskScanService|Scanning disk for The Man with the Golden Arm
17-12-31 09:28:35.9|Info|DiskScanService|Completed scanning disk for The Man with the Golden Arm
17-12-31 09:28:35.9|Info|RefreshMovieService|Skipping refresh of movie: The Man with the Iron Fists
17-12-31 09:28:36.0|Info|RenameMovieFileService|Renaming movie folder for The Man with the Iron Fists
17-12-31 09:28:36.6|Info|DiskScanService|Scanning disk for The Man with the Iron Fists
17-12-31 09:28:37.0|Info|DiskScanService|Completed scanning disk for The Man with the Iron Fists
17-12-31 09:28:37.0|Info|RefreshMovieService|Skipping refresh of movie: The Man with the Iron Fists 2
17-12-31 09:28:37.0|Info|RenameMovieFileService|Renaming movie folder for The Man with the Iron Fists 2
17-12-31 09:28:37.6|Info|DiskScanService|Scanning disk for The Man with the Iron Fists 2
17-12-31 09:28:37.9|Info|DiskScanService|Completed scanning disk for The Man with the Iron Fists 2
17-12-31 09:28:37.9|Info|RefreshMovieService|Skipping refresh of movie: Maniac
17-12-31 09:28:37.9|Info|RenameMovieFileService|Renaming movie folder for Maniac
17-12-31 09:28:38.7|Info|DiskScanService|Scanning disk for Maniac
17-12-31 09:28:39.0|Info|DiskScanService|Completed scanning disk for Maniac
17-12-31 09:28:39.0|Info|RefreshMovieService|Skipping refresh of movie: Margin Call
17-12-31 09:28:39.0|Info|RenameMovieFileService|Renaming movie folder for Margin Call
17-12-31 09:28:39.6|Info|DiskScanService|Scanning disk for Margin Call
17-12-31 09:28:40.1|Info|DiskScanService|Completed scanning disk for Margin Call
17-12-31 09:28:40.1|Info|RefreshMovieService|Skipping refresh of movie: The Martian
17-12-31 09:28:40.1|Info|RenameMovieFileService|Renaming movie folder for The Martian
17-12-31 09:28:40.7|Info|DiskScanService|Scanning disk for The Martian
17-12-31 09:28:41.1|Info|DiskScanService|Completed scanning disk for The Martian
17-12-31 09:28:41.1|Info|RefreshMovieService|Skipping refresh of movie: Martyrs
17-12-31 09:28:41.1|Info|RenameMovieFileService|Renaming movie folder for Martyrs
17-12-31 09:28:41.7|Info|DiskScanService|Scanning disk for Martyrs
17-12-31 09:28:42.0|Info|DiskScanService|Completed scanning disk for Martyrs

![rename](https://user-images.githubusercontent.com/18395709/34721574-18ce3a10-f53b-11e7-8b0e-ac62f22c809a.PNG)

**Comment by galli-leo** [comment]
Command just checks if you have it enabled (which you don’t) so it exits successfully hence displaying the message. I know this is confusing but the whole system will be revamped anyways.
