### ISSUE TITLE
ical not working after move to https

### ISSUE THREAD

**Issue by arette** [Radarr/Radarr#2407]
running latest linuxserver docker container on synology ds1515+.  ical link was working with google calendar and HTCP manager, but I now don't see any events (monitored or unmonitored) after moving to https.  I've tried both http and https with internal and external URLs but no combination(s) appear to be working.  Note that, for what it's worth, Sonarr & Lidarr both continued to work after updating the ical addresses to https

**Comment by galli-leo** [comment]
Did you maybe change your api key? Also are you using a reverse proxy or the integrated ssl stuff?

**Comment by arette** [comment]
api key matches; I'm using reverse proxy

**Comment by galli-leo** [comment]
Can you try increasing timeout & payload size in your reverse proxy settings?
