### ISSUE TITLE
RSS sync didn't cover the period

### ISSUE THREAD

**Issue by dkids** [Radarr/Radarr#2408]
18-1-8 10:05:34.3|Info|RssSyncService|Starting RSS Sync
18-1-8 10:05:38.5|Warn|Torznab|Indexer Demonoid - Jackett rss sync didn't cover the period between 1/8/2018 5:38:13 PM and 1/8/2018 6:05:38 PM UTC. Search may be required.
18-1-8 10:05:39.6|Warn|Torznab|Indexer Torrentz2 - Jackett rss sync didn't cover the period between 1/8/2018 5:31:02 PM and 1/8/2018 5:54:44 PM UTC. Search may be required.
18-1-8 10:05:50.0|Warn|Torznab|Indexer Idope - Jackett rss sync didn't cover the period between 1/8/2018 3:16:42 PM and 1/8/2018 6:05:50 PM UTC. Search may be required.

Should RSS be turned off for these indexers?

Version
    0.2.0.910
Mono Version
    5.4.1.6 (2017-06/1f4613aa1ac Wed Oct 18 09:31:57 EDT 2017)

**Comment by fryfrog** [comment]
It is just letting you know that it missed some data. What is your RSS sync interval? Was your computer off?

**Comment by galli-leo** [comment]
Closing as it is a support question. Please use discord for things like this. Feel free to discuss this issue more here though.
