### ISSUE TITLE
[Enhancement] 4k Remaster added to edition tags

### ISSUE THREAD

**Issue by Quiksmage** [Radarr/Radarr#2409]
Hi,

I think that 4k Remaster should be added as an edition tag. It is the newest way of releasing old content that has been remastered from their original source. I know it isn't necessarily the same as uncut or extended, but there is value in knowing if you have the 4k Remaster as it's likely the newest release of a movie.

Files will have it in their name similar to editions
Taxi.Driver.1976.4K.Remaster.BluRay.Remux.1080p.AVC.DTS-HD.MA.5.1-HiFi.mkv
Spider-Man.3.2007.BluRay.Remux.4K.Remaster.1080p.AVC.DTS-HD.MA.5.1-PJX.mkv

![image](https://user-images.githubusercontent.com/12449533/34803100-43a3036a-f626-11e7-9237-75082d52aa95.png)

edit: It looks like "remastered" already exists. Maybe we should add "4k remaster" or "remaster" as being enough of a trigger to tag it as "remastered"?

**Comment by bakerboy448** [comment]
use custom formats for specifics, but I _think_ this has been fixed long ago in v3
