### ISSUE TITLE
[Feature Request] Search/Filter/Sort by Tag

### ISSUE THREAD

**Issue by Quiksmage** [Radarr/Radarr#2410]
It would be great to be able to search your tags or filter to them on the main page.
Adding an optional column there could be enough.

Thanks!

**Comment by eltharynd** [comment]
ehm.. reopen this??? it's a must needed feature imo

**Comment by Qstick** [comment]
Look at the label, it's done in Aphrodite (V3) thus the reason why it's closed

**Comment by eltharynd** [comment]
my bad :P sorry
