### ISSUE TITLE
[Feature Request] Custom Kodi Tags

### ISSUE THREAD

**Issue by arette** [Radarr/Radarr#2411]
Kodi metadata is already supported; I'd love to see support for adding custom <tag></tag> field(s) into kodi's movie.nfo file as described here: http://kodi.wiki/view/NFO_files/Movies#Movie_nfo_Tags.  This allows custom sorting of your database within kodi ui and is a really nice feature (e.g. "Disney Shorts", "Christmas", are a few I like to use).  Thanks in advance!

**Comment by arette** [comment]
also for plex collections

**Comment by bakerboy448** [comment]
Closing
v0.2 is no longer being actively developed.

If this is still an issue/request on recent v3 builds, please open a new issue.
