### ISSUE TITLE
Allow quality size cutoffs to ignore runtimes.

### ISSUE THREAD

**Issue by m4tta** [Radarr/Radarr#2412]
Can we get a checkbox to enable the option to allow the quality size cutoffs to ignore the 90min/140m thing? If i set a 10GB max size. I don't want a 6GB/10GB cuttoff. I want 10GB.

**Comment by galli-leo** [comment]
This will not happen for a few reasons:

1. Sonarr has it this way too, and it works for them.
2. Movies can have various runtimes, from a quick 20 minute animated movie to 4 hour long LOTR Extended Cuts. Obviously a 4GB copy of the animated movie will be of a far different quality than the LOTR Extended Cut.
