### ISSUE TITLE
trakt authentication not working

### ISSUE THREAD

**Issue by farfromrefug** [Radarr/Radarr#2413]
I can't get my private watchlist to be synced with radarr.
I correctly see my Auth Token and Refresh Token in radarr (won't put a screenshot ;))

My list setup is like this.
<img width="840" alt="screen shot 2018-01-12 at 14 32 26" src="https://user-images.githubusercontent.com/655344/34877218-7854a5a2-f7a5-11e7-8498-b7ebd3bbfec0.png">
And this is why i get in the log:
```
18-1-12 14:26:50.3|Warn|HttpClient|HTTP Error - Res: [GET] https://api.trakt.tv/users/farfromrefuge/watchlist/movies?limit=100: 401.Unauthorized
18-1-12 14:26:50.3|Warn|TraktImport|Unable to connect to list

[v0.2.0.910] NzbDrone.Common.Http.HttpException: HTTP request failed: [401:Unauthorized] [GET] at [https://api.trakt.tv/users/farfromrefuge/watchlist/movies?limit=100]
  at NzbDrone.Common.Http.HttpClient.Execute (NzbDrone.Common.Http.HttpRequest request) [0x001a2] in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:103 
  at NzbDrone.Core.NetImport.HttpNetImportBase`1[TSettings].FetchNetImportResponse (NzbDrone.Core.NetImport.NetImportRequest request) [0x00057] in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:131 
  at NzbDrone.Core.NetImport.HttpNetImportBase`1[TSettings].FetchPage (NzbDrone.Core.NetImport.NetImportRequest request, NzbDrone.Core.NetImport.IParseNetImportResponse parser) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:108 
  at NzbDrone.Core.NetImport.HttpNetImportBase`1[TSettings].TestConnection () [0x0000e] in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:145 
```

**Comment by TheDSCMan1968** [comment]
I am also having this same issue.  No matter how I configure Radarr, I always get this issue.  I've renewed my Auth and refresh keys several times to no avail.

Log:

RssSyncService | Starting RSS Sync | 9:05pm
-- | -- | --
  | NzbDroneErrorPipeline | Invalid request Validation failed:    -- Unable to connect to list, check the log for more details | 9:05pm
  | TraktImport | Unable  to connect to list: HTTP request failed: [401:Unauthorized] [GET] at  [http://radarr.aeonlucid.com/v1/trakt/refresh?refresh=<removed>] | 9:05pm
  | HttpClient | HTTP  Error - Res: [GET]  http://radarr.aeonlucid.com/v1/trakt/refresh?refresh=<removed>:  401.Unauthorized {"message":"Invalid refresh token specified.","messageTrakt":"error on  refreshing oauth access token, error: invalid_grant, description: "}

**Comment by evilvibes** [comment]
Profile on Private?

**Comment by farfromrefug** [comment]
@evilvibes what do you mean?

**Comment by TheDSCMan1968** [comment]
So I did get it to work... finally.  I had spent about 3 hours and kept getting the above errors.  I had originally set up Trakt in Radarr a year or so ago and had deleted it.  I decided to give it another try and after refreshing the tokens and attempting to add my UserWatchList, it would never use the new tokens for the API calls.  It would always use the old ones even though the new ones were showing under the List page.  

After writing my post, I decided to slow down and just save everything after every config change.  That ended up fixing it and saving the tokens.  I still couldn't connect my list, but I was at least using the correct tokens.  

 I could never get it to work using UserWatchList.  Does the UserWatchList setting even work?   I found an old post by someone and followed their list creation advise and created a new public list and moved everything from my default watchlist to the public one.  I used UserCustomList with the new list name and now it works and allows me to import the movies into what I want to see.

**Comment by galli-leo** [comment]
@TheDSCMan1968 Yeah the ui is kinda unintuitive (just struggled with it as well :/). You first have to save, when you refresh the tokens, for the new tokens to be used. Anyways I got my UserWatchList to work fine, did you have any errors for that?

@farfromrefug Have you tried refreshing the trakt auth tokens? And then clicking save? Because sometimes they get invalidated for some reason.

**Comment by evilvibes** [comment]
@farfromrefug If you have your Profile (trakt.tv/users/farfromrefuge) on Private trakt will not work. 

Turn Private off under settings and trakt will work.

**Comment by farfromrefug** [comment]
@evilvibes yes my profile is private. But why wouldn't it work with auth token?  I know i can get my profile or watchlist with my access_token. I

**Comment by geogolem** [comment]
it should work with the tokens... I dont seem to have any issues... I do believe the pop up on successful authentication says you need to click the save button.. but, i havent touched or changed my setup in a while.

**Comment by farfromrefug** [comment]
Just tested it again and i found why it did not work. Once you ve logged in on trakt, you need to hit save before adding the trakt list
