### ISSUE TITLE
Manual Import -> 'Import File(S) Automatically' not working

### ISSUE THREAD

**Issue by Neaox** [Radarr/Radarr#2414]
**Description:** When I select a folder I know has movies in it ready for import and click 'Import File(S) Automatically' nothing happens.

On another note, if I select `Manual import` all the files are listed but everything has "Click to select Movie" It has the quality listed correctly, but not the movie. According to the logs, it parsed the movie title correctly (albeit as a tv season -- see the logs below). I seem to remember it normally pre-selects the movie if it can, but allows you to change it.

I was attempting to import movies from `T:\Inbox\Torrents\movies`

**Radarr Version:** 0.2.0.910

**'Import File(S) Automatically' Logs:**
```
18-1-13 09:59:31.9|Debug|Parser|Parsing string 'movies'
18-1-13 09:59:31.9|Debug|Parser|Unable to parse movies
```

**'Manual Import' Logs:** 

Notice below that it's parsing the movie as season 1 of a TV show, perhaps this is why its not auto matching the movie?
```
18-1-13 10:04:39.4|Debug|ImportDecisionMaker|Analyzing 1/1 files.
18-1-13 10:04:39.5|Trace|ConfigService|Using default config value for 'parsingleniency' defaultValue:'Strict'
18-1-13 10:04:39.5|Debug|Parser|Parsing string 'mhq-zodiac.2007.dc.1080p.x264.mkv'
18-1-13 10:04:39.5|Trace|Parser|^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(19|20)\d{2}(?!p|i|(19|20)\d{2}|\]|\W(19|20)\d{2})))+(\W+|_|$)(?!\\)
18-1-13 10:04:39.5|Debug|Parser|Movie Parsed. mhq-zodiac - 2007 
18-1-13 10:04:39.5|Debug|Parser|Language parsed: English
18-1-13 10:04:39.6|Debug|QualityParser|Trying to parse quality for mhq-zodiac.2007.dc.1080p.x264.mkv
18-1-13 10:04:39.6|Debug|Parser|Quality parsed: HDTV-1080p v1
18-1-13 10:04:39.6|Debug|Parser|Release Group parsed: zodiac
18-1-13 10:04:39.6|Debug|ImportDecisionMaker|Size: 7840318620
18-1-13 10:04:39.6|Debug|VideoFileInfoReader|Getting media info from T:\Inbox\Torrents\movies\Zodiac.2007.Directors.Cut.iNTERNAL.1080p.BluRay.x264-MHQ\mhq-zodiac.2007.dc.1080p.x264.mkv
18-1-13 10:04:39.7|Trace|MediaInfo|Read file offset 0-32768 (32768 bytes)
18-1-13 10:04:39.7|Trace|MediaInfo|Read file offset 7840183825-7840318620 (134795 bytes)
18-1-13 10:04:39.8|Trace|MediaInfo|Read a total of 167563 bytes (0.0%)
18-1-13 10:04:39.8|Debug|ImportDecisionMaker|Checking quality for this video file to make sure nothing mismatched.
18-1-13 10:04:39.8|Trace|ConfigService|Using default config value for 'skipfreespacecheckwhenimporting' defaultValue:'False'
18-1-13 10:04:39.8|Debug|Parser|Parsing string 'Zodiac.2007.Directors.Cut.iNTERNAL.1080p.BluRay.x264-MHQ'
18-1-13 10:04:39.8|Trace|Parser|^(?<title>.+?)?(?:(?:[-_\W](?<![()\[!]))*(?<year>(?<!e|x)\d{4}(?!p|i|\d+|\)|\]|\W\d+)))+(\W+|_|$)(?!\\)
18-1-13 10:04:39.8|Debug|Parser|Episode Parsed. Zodiac - Season 01 
18-1-13 10:04:39.8|Debug|Parser|Language parsed: English
18-1-13 10:04:39.9|Debug|QualityParser|Trying to parse quality for Zodiac.2007.Directors.Cut.iNTERNAL.1080p.BluRay.x264-MHQ
18-1-13 10:04:39.9|Debug|Parser|Quality parsed: Bluray-1080p v1
18-1-13 10:04:39.9|Debug|Parser|Release Group parsed: MHQ
18-1-13 10:04:39.9|Debug|VideoFileInfoReader|Getting media info from T:\Inbox\Torrents\movies\Zodiac.2007.Directors.Cut.iNTERNAL.1080p.BluRay.x264-MHQ\mhq-zodiac.2007.dc.1080p.x264.mkv
18-1-13 10:04:40.0|Trace|MediaInfo|Read file offset 0-32768 (32768 bytes)
18-1-13 10:04:40.0|Trace|MediaInfo|Read file offset 7840183825-7840318620 (134795 bytes)
18-1-13 10:04:40.0|Trace|MediaInfo|Read a total of 167563 bytes (0.0%)
18-1-13 10:04:40.1|Debug|DetectSample|Runtime is over 90 seconds
18-1-13 10:04:40.1|Trace|ConfigService|Using default config value for 'downloadclientworkingfolders' defaultValue:'_UNPACK_|_FAILED_'
18-1-13 10:04:40.1|Trace|Http|Res: 114 [GET] /api/manualimport?folder=T%3A%5CInbox%5CTorrents%5Cmovies%5C&sort_by=qualityWeight&order=desc: 200.OK (57260 ms)
```

**Comment by majora2007** [comment]
I've had this issue for a long time as well.

**Comment by SJPower** [comment]
Same issue here. Unable to parse movies.

**Comment by galli-leo** [comment]
import automatically isn't thought to import all files in a subfolder, it's import a single movie. Thus selecting /path/to/downloads/ or something like that won't work. It's the same behaviour in Sonarr.

**Comment by majora2007** [comment]
@galli-leo If a folder contains just the movie, should "manual import -> import automatically" import the movie into the system?

If the folder contains other files, should "manual import -> import automatically" import just the movie and leave the rest of the files? 

Because as of now, my Radarr is not doing either of those. Only through manual import (for which movies are not matched with their titles (ever)) will work to import the file into Radarr.

**Comment by Neaox** [comment]
@galli-leo I don't believe this is the case in Sonarr. Please see my attached gif. In Sonarr you are able to select a root folder which contains subfolders containing different media, even when selecting manual import it will attempt to pre-select the tv show, season and episode if it is able.
![screen](https://user-images.githubusercontent.com/13699847/35584539-2e2f6eda-065a-11e8-8c89-70c2d96441db.gif)
