### ISSUE TITLE
Increase Maximum File Size Selection In Quality Definition

### ISSUE THREAD

**Issue by ghost** [Radarr/Radarr#2419]
More of a feature request than a problem but I would like an increase in the maximum file size available for selection in the quality definition settings.

For qualities like BluRay 2160p and such the maximum size selectable is around 27GB which means that if you want a file with a maximum of say, 35GB, you cannot set that maximum. Its 27GB or unlimited which can get awfully large for 2160p files. As we see an increase in the availability of these files I think this would be beneficial.

**Comment by julestop** [comment]
Has this been resolved? I cannot go past 27GB
