### ISSUE TITLE
Directory MediaCover: can I clean it?

### ISSUE THREAD

**Issue by pven** [Radarr/Radarr#2426]
The directory MediaCover contains around 600M. Oldest file is from may 2017. Can I delete all files older than ie 30 days? (FYI: I create backups, and this directory is quite big when backupped multiple times.)

**Comment by M0UL** [comment]
al you really need to backup are raddarr database and the config file.  everything else is not needed.

about the mediacover folder this contains the covers used the webinterface. and wil be recreated when you update your library.
