### ISSUE TITLE
File being renamed correctly but not file properties

### ISSUE THREAD

**Issue by CrazyLittleBunny** [Radarr/Radarr#2430]
When renaming and moving files everything seems to be fine but when playing a file it shows the title as the original download title. Then when checking the title and comments in the file properties it has the original file name.

Is there any way to change this that it replaces the title with the correct file name and clear the comments?

This is with using SABNZBD and Windows 10.

**Comment by galli-leo** [comment]
No this is not something we plan on implementing.
