### ISSUE TITLE
Expose matching terms for quality in the settings page, allow adding of quality settings.

### ISSUE THREAD

**Issue by on2valhalla** [Radarr/Radarr#2433]
I was planning on submitting this as a pull request, but ran out of time trying to pipe the strings through. I don't think this should be that difficult, basically replace the match terms with universally stored strings.

This would easily enable *codec* defined quality settings instead of the more general resolution defined settings that are available currently (which are only one component of quality. This would allow you to say filter quality on say, something I filter on all the time: '10Bit 1080p H265'

Thanks for the hard work guys, and if I get a second I'll try and take another pass at it

**Comment by galli-leo** [comment]
This and more is exactly what I had in mind when making the "Proposal Metis" (https://cdn.discordapp.com/attachments/264387956343570434/392791668513964044/Proposal_Metis.pdf).

**Comment by fbartho** [comment]
I too would like this feature -- specifically I want to blacklist the VC-1 codec but support others as that's the one that has been repeatedly problematic for Plex to transcode for various devices.

**Comment by casperse** [comment]
Would this also resolve this: [https://feathub.com/Radarr/Radarr/+4](https://feathub.com/Radarr/Radarr/+4)

**Comment by galli-leo** [comment]
Yes

**Comment by Xebozone** [comment]
Can you not already do this with "Custom Formats"?
