### ISSUE TITLE
Inconsistency in linux autostart directions

### ISSUE THREAD

**Issue by kaysond** [Radarr/Radarr#2434]
The auto start on linux section of the wiki suggests creating the service file with the command `/usr/bin/mono --debug /opt/Radarr/Radarr.exe --nobrowser`

The radar status section, however, shows the command `/usr/bin/mono --debug /usr/lib/radarr/Radarr.exe -nobrowser -data=/var/lib/radarr`, where nobrowser has a single dash instead of double, and the `-data` switch has been added.

Which is correct? What do nobrowser and data flags do?

**Comment by galli-leo** [comment]
No idea, probably double dash. --nobrowser just tells radarr to not open your browser and loading the radarr page.

**Comment by kaysond** [comment]
Assuming mono passes the arguments without change, looks like its a single dash (or a forward slash)
https://github.com/Radarr/Radarr/blob/develop/src/NzbDrone.Common/EnvironmentInfo/StartupContext.cs

The data flag appears to change where the app data is stored
https://github.com/Radarr/Radarr/blob/develop/src/NzbDrone.Common/EnvironmentInfo/AppFolderInfo.cs

I'm happy to update the wiki for you

**Comment by galli-leo** [comment]
Yeah that's correct, we use the same params as Sonarr. If you can update the wiki that would be great!
I think single and double dash don't matter, both should work.
