### ISSUE TITLE
Movie poster issue on FirefoxDeveloperEdition

### ISSUE THREAD

**Issue by romanar** [Radarr/Radarr#2437]
I use FirefoxDeveloperEdition for accessing radarr, sonarr, etc and I'm seeing different cover art only on FirefoxDeveloperEdition (same on chrome, safari, nzb360) and its size is also not right when the browser is in fullscreen mode.
Restarted radarr (docker container) > update movie info and scan disk > Clear Site Data. Fixed the issue for some movies by change the move poster to the one that was showing up in chrome.
FirefoxDeveloperEdition
![screen shot 2018-01-20 at 12 04 35 pm](https://user-images.githubusercontent.com/32021606/35186093-afc04838-fddc-11e7-9981-6dac116a2b3e.png)
FirefoxDeveloperEdition (fullscreen)
![screen shot 2018-01-20 at 12 03 37 pm](https://user-images.githubusercontent.com/32021606/35186098-bb05dd84-fddc-11e7-8633-649899872fb8.png)
Chome
![screen shot 2018-01-20 at 12 08 30 pm](https://user-images.githubusercontent.com/32021606/35186102-c08b2e8a-fddc-11e7-83f7-c84409321ee3.png)
Nzb360
![2018-01-20 12 34 01](https://user-images.githubusercontent.com/32021606/35186195-3fcca876-fdde-11e7-8482-cebf8b921903.jpg)
- Radarr
Version: 0.2.0.910
Mono Version: 5.4.1.6 (tarball Wed Nov 8 20:37:08 UTC 2017)
- FirefoxDeveloperEdition
Version: 59.0b2
Build ID: 20180117222144
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:59.0) Gecko/20100101 Firefox/59.0
- Chrome
Version: Version 63.0.3239.132 (Official Build) (64-bit)

**Comment by galli-leo** [comment]
This is a caching issue. Clear cache with Firefox.
