### ISSUE TITLE
Manual Import very slow - often doesn't even work

### ISSUE THREAD

**Issue by Tadimsky** [Radarr/Radarr#2438]
If I run manual import on the folder where my movies are stored (since some are not showing up correctly), it takes a very, very long time.

```
18-1-20 16:42:42.3|Debug|Api|[GET] /api/manualimport?folder=%2Fmedia%2Fmediashare%2FMovies%2F&sort_by=qualityWeight&order=desc: 200.OK (1827860 ms)
```

That's over 30 minutes. This generally results in the Web UI not actually showing the results as it seems to timeout or something.

Is there any way this could be made faster / paginated or something?

**Comment by galli-leo** [comment]
It could probably be paginated, but the idea is not to manually import a whole movie folder. So gonna mark this as wont fix for now.

**Comment by galli-leo** [comment]
Using bulk import. Then Radarr will auto add the movies too
