### ISSUE TITLE
Trakt not synching anymore

### ISSUE THREAD

**Issue by Bavich** [Radarr/Radarr#2442]
Hi,

Since few weeks ago trakt list is not importing new movies to Radarr. It was working without any issue previously.

Please note:
- it's a public list
- I tried with private lists as well (activated Trakt Authentication)
- I deleted the list from Radarr and added it again. Didn't solve the issue.
- After every change I made, I click saved > restart Radarr > and activated manually Net Import Sync
- I also tried adding a list with TMDB and it worked.

Please advice,

Thank you !

**Comment by Bavich** [comment]
up ...

**Comment by galli-leo** [comment]
Do the movies show up when you manually list them using the List Import GUI

**Comment by Bavich** [comment]
Not anymore. 
When I test the connection between Trakt and Radarr it says is OK.

**Comment by galli-leo** [comment]
Can you post the list in question?

**Comment by Bavich** [comment]
This is the trakt list: https://trakt.tv/users/nvm/watchlist
I also attached a .csv
[movies trakt.zip](https://github.com/Radarr/Radarr/files/1680833/movies.trakt.zip)

**Comment by Bavich** [comment]
Does the the info help ?

**Comment by galli-leo** [comment]
Hmm do you have auto sync enabled for the trakt list?

**Comment by Bavich** [comment]
Yes I do
<img width="795" alt="screen shot 2018-02-06 at 11 36 22" src="https://user-images.githubusercontent.com/9332889/35854938-0da17c30-0b32-11e8-80e7-7d5b0cf16378.png">

**Comment by galli-leo** [comment]
Ah, I found it. You need to up the limit parameter since you have more than 100 movies on your watchlist (I would recommend setting it to something like 500)

**Comment by Bavich** [comment]
Hi,
It's me again :).
I'm having the same issue. I double-checked ant the limit is set to 10.000. 
Thank you

**Comment by Qstick** [comment]
Start a new issue

**Comment by Bavich** [comment]
I tried to Revoke Trakt Tokens and set up the list again, but nothing has changed.
The connection between Trakt and Radarr works.

**Comment by Bavich** [comment]
up

**Comment by Bavich** [comment]
anyone? please :)

**Comment by bakerboy448** [comment]
as Q said, start a new issue and provide some logs.

**Comment by Bavich** [comment]
Thank you for your answer.
I've just start a new issue.
