### ISSUE TITLE
Prevent deleting files on upgrade

### ISSUE THREAD

**Issue by sho-87** [Radarr/Radarr#2449]
when radarr upgrades a film to a "better" release I believe it deletes the previous version. Is there a way to prevent this behaviour?

Sometimes a particular file is preferred (better visual/audio quality, dubbed vs subbed) and you dont want to lose that file after an upgrade.

Ideally we can just prevent automatic downloads/searches/upgrades altogether so things like this dont happen, but is there at least a way to keep the old versions?

**Comment by galli-leo** [comment]
Enable the recycle bin. Old files will get sent there instead. Alternatively you can just set your cutoff very low so Radarr won't upgrade automatically.

**Comment by sho-87** [comment]
how is quality priority determined? is it just by the ranking of the list? I dont want to include a low cutoff and have radarr download that quality if higher quality versions are available
