### ISSUE TITLE
File extension restrictions

### ISSUE THREAD

**Issue by rhymist2000** [Radarr/Radarr#2452]
- Radarr continually downloads fake video with .avi extension.
- Added "avi" and ".avi" to restrictions in indexers but the fake avi files are still downloaded.
- Prefer file types .mp4, and .mkv as a alternative.

Need file extension management as addition filter

**Comment by galli-leo** [comment]
See previous issues regarding this feature. We don’t know the file extension, because the indexer does not tell us that. You have to configure this in your dl client.

**Comment by rhymist2000** [comment]
Thanks for the heads up. 
That's unfortunate, because µTorrent does not offer this as a feature.
Definitely a tracker issue.

**Comment by galli-leo** [comment]
I would suggest switching dl clients in that case.
