### ISSUE TITLE
Can't add new movies!

### ISSUE THREAD

**Issue by deecypher** [Radarr/Radarr#2453]
When attempting to add a new movie, the "add" and "add and search for movie buttons" appear to have no effect.

**Radarr Version:**
0.2.0.910
Mono Version 5.2.0.224 (d15-3/14f2c81 Thu Aug 24 10:33:52 EDT 2017)

**Logs:**
Attached
[radarr.txt](https://github.com/Radarr/Radarr/files/1670130/radarr.txt)

**Comment by galli-leo** [comment]
Your database seems to be corrupt. Try reading the wiki on what to do or head over onto our discord for support.
