### ISSUE TITLE
No movie found when quote in title

### ISSUE THREAD

**Issue by Nico87LBS** [Radarr/Radarr#2457]
Hello,

Radarr do not find any file when searching for a title containing quote (for example: _Rock'n Roll_)
The quote is deleted, radarr is looking for _rockn roll_, so the movie is never find.

I'm am using Jackett, and if I search for rock'n roll it is working.

Radarr version, the latest 0.2.0.910

Thank you

**Comment by galli-leo** [comment]
Unfortunately I will have to close this as wontfix. Most trackers remove special chars such as these, hence we have to remove them from the search result as well. Try asking your tracker if they could add an option to search by imdbid. This way it wouldn't be an issue.
