### ISSUE TITLE
Can't update radarr through the web ui

### ISSUE THREAD

**Issue by chq81** [Radarr/Radarr#2461]
**Description:**

Hi guys,
maybe someone is able to help me. I have a Synology DS216j and installed SynoCommunity package of radarr. When I go to the Update section in "Settings", I just get the message "No updates are available".
Is there any possibility how I can update radarr through the app itself?

**Radarr Version:**
0.2.0.267

**Mono Version:**
4.6.2 (Stable 4.6.2.7/08fd525 Wed Jan 11 15:40:32 CET 2017)

**Comment by galli-leo** [comment]
Probably not the best Idea when you are using a package system. Can you post some logs?

**Comment by chq81** [comment]
I had a look a the commits and found out that the tags wheren't set on the master branch, but the development branch. So when I changed the tracked branch to "develop", the updates showed up. Any idea why the tags are not set in the master branch? Or why the tagged versions are not merged in the master branch?

**Comment by galli-leo** [comment]
Ah because the master branch will only get releases once we get out of "beta". Basically when we finished implementing everything we want the first version to have (see readme) and get rid of some hacky stuff.

**Comment by chq81** [comment]
Thanks for the quick feedback!
