### ISSUE TITLE
Cant delete movie

### ISSUE THREAD

**Issue by Viper911** [Radarr/Radarr#2462]
Running latest version, chrome and have several movies (only some of them) where I can not delete the entry and files.  Looking at the log I am getting:   Any ideas?

NzbDroneErrorPipeline | Request Failed: constraint failed UNIQUE constraint failed: ImportExclusions.TmdbId | 7:11am
-- | -- | --
  | NzbDroneErrorPipeline | [DELETE /api/movie/1187]: constraint failed UNIQUE constraint failed: ImportExclusions.TmdbId | 7:11am
  | MediaCoverMapper | File /home/htpc/.config/Radarr/MediaCover/671/poster.jpg not found | 7:10am
  | MediaCoverMapper | File /home/htpc/.config/Radarr/MediaCover/923/poster.jpg not found | 7:10am
  | MediaCoverMapper | File /home/htpc/.config/Radarr/MediaCover/670/poster.jpg not found | 7:10am

**Comment by Viper911** [comment]
Seems to be related to the fact these movies are already in my exclude list and I am checking to add it to the exclude list when deleting.  Can you add a check in there to make sure the name isn't already in the exclude list before trying to add it again.

**Comment by galli-leo** [comment]
Fixed in latest nightly. For now you can just not add the exclusion when deleting.
