### ISSUE TITLE
Radarr creates folders that are not Roman characters

### ISSUE THREAD

**Issue by majora2007** [Radarr/Radarr#2465]
**Description:**

Radarr consistently creates folders for movies in non-roman characters. 

I didn't see any way to force roman characters in the settings. 

For example:

From Track List:
N:\Movies\愛のコリーダ (1976) for the movie In The Realm Of The Senses (1976)

Manually Added:
N:\Movies\冷たい熱帯魚 (2010) for the movie Cold Fish (2010)

This not only is annoying, but causes Plex to not match metadata due to metadata providers favoring Roman characters. 

**Radarr Version:**
0.2.0.923

**Logs:**
[log.txt](https://github.com/Radarr/Radarr/files/1685360/log.txt)

**Comment by galli-leo** [comment]
Hmm I just added both those movies and it didn't for me. What profile are you using (i.e. what language) and do you have dynamic paths on?

**Comment by galli-leo** [comment]
I have the same problem sometimes with my Radarr install at home, but I haven't found a reliable way of reproducing it.

**Comment by majora2007** [comment]
Yeah this is a hard to reproduce bug, it has happened a few times for me.

My Language is English and Static Paths are on.

**Comment by galli-leo** [comment]
When did you add those two movies? Because what I think is happening, is that you added them before someone added the english titles.

**Comment by galli-leo** [comment]
@majora2007 How confident are you that the second movie was added via a trakt list?

**Comment by majora2007** [comment]
Looking into it, it looks like both movies were added via a Trakt list (2 different lists).

**Comment by majora2007** [comment]
The list for that Realm of Senses movie is this:
https://trakt.tv/users/bigfella/lists/102-most-controversial-films

**Comment by galli-leo** [comment]
Good in that case I have fixed it. It only occurs when adding the movies via a list.

**Comment by majora2007** [comment]
Good to hear. :)
