### ISSUE TITLE
Running sonarr with radarr importing fails

### ISSUE THREAD

**Issue by Dreamersoul** [Radarr/Radarr#2466]
I have sonarr and radarr running on Windows 10, both programs fail to import episodes/movies

It keeps saying access denied
Both of the programs are importing from the same download folder

**Comment by galli-leo** [comment]
Have you checked permissions? Are you using docker?

(Since this is a support question, I will close the issue. Feel free to comment though. For the future please use either the discord or subreddit for support questions.)
