### ISSUE TITLE
Issues related to Automatically Rename Folders

### ISSUE THREAD

**Issue by RoChess** [Radarr/Radarr#2470]
It is listed in the common issues that folders need to be used like "Title (Year)", and the Automatically Rename Folders option is marked as alpha, but I wanted to make sure the issues I'm running into are aware. Feel free to merge this issue into another, or delete/close if needed.

Movie Folder Format = "{Movie Title} ({Release Year}) - {Quality.Full}"

Create empty movie folders = NO
Automatically Rename Folders = YES
Movie Paths Default to Static = NO
Ignore Deleted Movies = YES

Behavior:

1) When upgraded qualities are added, the existing file is removed, but the empty folder remains
2) When folder+file are moved to a different location the entry switches to 'missing' instead of the expected grey color switch to indicate it is now unmonitored
3) On a manual import the folder+files are not moved to a default folder. After manually moving the files and doing a mass-edit on the base folder the entries become messed up and steps to correct them was to turn Static path on, refresh media to have Radarr detect files again, and then set it back to static off and turn monitor on. When viewing the path it appears Radarr gets totally confused by the "{Movie Title} ({Release Year}) - {Quality.Full}" format, and would show ""{Movie Title} ({Release Year}) " instead (space at the end, but nothing else). Manually browsing to the correct folder would only further corrupt entries.

**Comment by galli-leo** [comment]
1. Fixed in latest release.
2. Fixed in latest release.
3. Probably also fixed in latest release, since it worked fine for me when I tested the changes.

**Comment by RoChess** [comment]
1. Confirmed fixed
2. Confirmed fixed
3. This issue still exists, but I am fine with the workaround. Used to CouchPotato being able to move imports from a different folder to a new base folder, but perhaps I'm using the updating of base-path and organize feature incorrect.

Getting 1+2 fixed makes things a lot easier already.

**Comment by galli-leo** [comment]
By manual import do you mean manually putting the files inside the folder Radarr currently searches for?

**Comment by RoChess** [comment]
I used the bulk import, browsed to the folder that had existing media before installing Radarr. Mass selected all the movies to import, and they flawlessly imported (After I first moved them into individual folders). However, they did not 'move' and remained stuck with say "D:\Existing" as base path and not "D:\Movies" for all the others Radarr managed (CP does this part automatically when you bulk import, but sounds like for Radarr I should have dropped the files in the folder that's being monitored; reason why I didn't do that is because that's on an SSD and I wanted to avoid the delay/wear).

I then used the movie editor to select all the movies with "D:\Existing" and updated their base path. Then used the organize button to actually move the files (or at least expected it to work like that).

That failed, and I then proceeded to manually move the files, but then sunk deeper into the rabbit hole.

It works slightly better now in latest version, but the moment I change base path Radarr marks them all as unmonitored which probably relates to your no.2-fix.

Switching to static path, selecting correct folder individually, save, refresh scan, and then restoring it back to dynamic solves it. Optionally I can do an organize to sort out any file rename if needed.

With all those existing ones sorted I don't have a need for this anymore, so don't feel bothered to fix it if your preferred method is to place new imports in the monitored folder.

It would be potentially awesome for others if there was a global "base path" option, because initially when I did the bulk import on existing media, all subsequent "add movie" entries immediately wanted to use that path as well and I didn't pay attention to that and got confused when movies didn't appear in the folder I expected them.

Was tempted to switch back to CP, but you've got a rapid pace of commits, so I'd rather assist this project in solving issues, and suggest features that will hopefully benefit others. Perhaps in the future I can contribute more directly, but I'm struggling to find time for my own projects sometimes.

Happy to provide feedback though :)

**Comment by RoChess** [comment]
Darn, 2 was confirmed fixed yesterday on multiple tests, but today a few of the movies that automatically changed to 'not monitored' showed up missing, and some others went back to green 'downloaded' even though the folder + file are clearly gone.

**Comment by RoChess** [comment]
Still an issue, but I've adjusted my Radarr settings slightly to mitigate and would need to recreate reproducible steps if needed.

**Comment by RoChess** [comment]
still an issue
