### ISSUE TITLE
Connection refused: localhost:7878, cannot open radarr or sonarr

### ISSUE THREAD

**Issue by BigStank11** [Radarr/Radarr#2472]
I have been using radarr well for a couple months. today I ran avast cleanup. afterward, neither sonarr o radarr worked. When i would click on them i would get a message saying the config.xml was corrupt and needed to be deleted (and automatically replaced). So I deleted it, now when I click on radarr I get taken to a page saying "Connection refused: localhost:7878" I tried reinstalling radarr, but get the same problem.

**Comment by galli-leo** [comment]
Try getting the log from the app data dir / cleaning out the whole app data dir (See the wiki for where to find that)

Since this is a support question I am closing this issue. Feel free to comment though. For the future please use the Subreddit or the Discord server for support questions.

**Comment by alisilavi-web** [comment]
http://localhost:127.0.0.1/9909
