### ISSUE TITLE
[Feature Request] Collect and share information on blacklisted releases

### ISSUE THREAD

**Issue by p3v9d5ui** [Radarr/Radarr#2473]
More and more recently, I've been downloading bogus releases -- they usually contain a "codec" to install, which I presume installs a Trojan, or has a link to a codec/Trojan to download in the readme. Of course, the "movie" itself is bogus. When this happens, I remove the download from Radarr and mark the source as blacklisted.

I think it would be awesome if Radarr collected information on which torrents/files have been blacklisted by its users, so that this information could be used when deciding on which version to grab. E.g., if enough people have blacklisted a certain title, then Radarr could be configured to ignore it. 

It would also be good if users could supply a reason a title is being blacklisted, as I assume in some cases people are blacklisting due to reasons other than a bogus movie (perhaps too large, etc.).

**Comment by galli-leo** [comment]
Probably not gonna happen. Last time I implemented a similar system (for alternative titles) it was a major pita to get it up and running.

**Comment by bakerboy448** [comment]
no plans for this at this time
