### ISSUE TITLE
Problems with Google pagespeed mod for apache

### ISSUE THREAD

**Issue by AndyPeepsJR** [Radarr/Radarr#2474]
# Google pagespeed causes problems loading Radarr with transmission as download client on Debian

Basically, Radarr stopped on the loading screen, with the dot-scanner continually moving. The log seemed to show that it had trouble accessing Transmission. Google Chrome debug gave the following:

```
calendar:94 Uncaught ReferenceError: mod_pagespeed_2dV8$cPr25 is not defined at calendar:94
calendar:95 Uncaught ReferenceError: mod_pagespeed_4dd1xWl$QS is not defined at calendar:95
```

So I tried turning pagespeed off for the virtual server (in it's config added the line `ModPagespeed Off`) and all was fine. Next I'll try telling pagespeed to leave javascript alone (didn't work, css was all off).

Radarr Ver. 0.2.0.910 (develop)

**Comment by galli-leo** [comment]
The dl client shouldn't have anything to do with that. Also not sure why this is an issue? If ModPagespeed is messing with the js files, nothing we can do.
