### ISSUE TITLE
[Feature Request] Add option for indexer to download only when doing a manual search

### ISSUE THREAD

**Issue by hbooo** [Radarr/Radarr#2481]
Hi, 

I have some indexers that I can't rely to for automatic downloads : 
Languages aren't retrieve through the API of the website so I got movies in languages I don't want sometimes. But they still got releases I want to get. 

It could be usefull to add an option when configuring indexing
![image](https://user-images.githubusercontent.com/242125/35814098-7bc4372c-0a95-11e8-9fd8-5a8be4b7366c.png)
to allow automatic download or not.

With this option disable, I could be able to search manually for a release and download it from Radarr, but indexer won't be used for an automatic search. If the option is enable, the current behaviour would occurs

**Comment by galli-leo** [comment]
Just disable rss sync. Unless you click the magnifying glass (automatic search) no releases will be downloaded from that indexer.
