### ISSUE TITLE
Manual Import - Files not rejected when file is not an upgrade for a file already on disk

### ISSUE THREAD

**Issue by Neaox** [Radarr/Radarr#2482]
Thanks for the great work on getting the auto-matching working in manual import!

**Description:** Sonnar will reject files (with a red icon in the rejections column) if the file is not an upgrade for, or is the same size of, the file already on disk. It would be great if radarr could do this too.

**Radarr Version:** 0.2.0.935

![screen](https://user-images.githubusercontent.com/13699847/35877692-f0807e5e-0bda-11e8-81aa-df6b48937ce4.png)

![screen2](https://user-images.githubusercontent.com/13699847/35877819-4facbc4e-0bdb-11e8-8a09-858000e6a0a3.png)

**Comment by Qstick** [comment]
I’ll toss up the “same size” part of this, will wait till after Metis for the upgrade spec.

**Comment by galli-leo** [comment]
This is possibly already fixed on metis.
