### ISSUE TITLE
calender dates incorrect

### ISSUE THREAD

**Issue by kieran989** [Radarr/Radarr#2486]
On the calender, movies are shown as downloaded on incorrect dates. Many movies showing as downloaded in the future.

Dates shown in Activity > History are correct

**Comment by galli-leo** [comment]
The calendar shows the movies in their current state, so if they are downloaded, they will show up as such.

**Comment by kieran989** [comment]
yes but movies are showing as downloaded in the future??

ie one movie showing in calender as downloaded on 20/02/18??

**Comment by galli-leo** [comment]
Yeah it's already downloaded. If it's already downloaded it will show in that color.

**Comment by kieran989** [comment]
yes I understand it will show in that colour but it does not explain why the dates have changed. ie Thor ragnarok showing as downloaded on the 6th of march????

**Comment by galli-leo** [comment]
Yes and Thor Ragnarok releases ro dvd on that date, which is why the calender shows it there.
