### ISSUE TITLE
API: add `originalName`

### ISSUE THREAD

**Issue by pannal** [Radarr/Radarr#2489]
Related to #2344 #2245 - Sub-Zero could use the original name regardless of it having been successfully parsed into `sceneName`. 

It uses advanced filename information using the guessit library and would greatly benefit from you adding something like `originalName` to the movie API in all cases, which would be the original filename of the movie file, before it gets renamed.

**Comment by pannal** [comment]
Sonarr is going to implement it like this: https://github.com/Sonarr/Sonarr/issues/2336#issuecomment-363909321

**Comment by Qstick** [comment]
Added in aphrodite
