### ISSUE TITLE
uTorrent on Linux error

### ISSUE THREAD

**Issue by blackley** [Radarr/Radarr#249]
uTorrent on Linux is throwing this following error

HTTP Error - Res: [GET] http://127.0.0.1:8082/gui/?token=(removed)&list=1&cid=730467690: 400.BadRequest
 
Radarr 
Version
0.2.0.99
Mono Version
4.6.2 (Stable 4.6.2.16/ac9e222 Tue Jan 3 11:48:26 UTC 2017)
AppData directory
/home/plex/.config/Radarr
Startup directory
/opt/Radarr

I have tested the download client configuration and it is reporting 'successful' for ut

**Comment by onedr0p** [comment]
> uTorrent on Linux
Well there's your problem 😄

**Comment by blackley** [comment]
@onedr0p I see your point, however, i like utserver and I have looked at qbittorrent and deluge... don't like deluge...

**Comment by galli-leo** [comment]
The problem here is, that we (and Sonarr) only support the uTorrent API of version 3.0 onwards.

**Comment by onedr0p** [comment]
Have you looked into rtorrent? It's the best for performance on Linux systems.
