### ISSUE TITLE
How to build latest version

### ISSUE THREAD

**Issue by Nico87LBS** [Radarr/Radarr#2491]
Hello

I am trying to build Radarr.
I have monodevelop, git and node.js installed.

I am following the instructions of the readme:
- Make sure all the required software mentioned above are installed
- Clone the repository into your development machine (info)
- Grab the submodules git submodule init && git submodule update
- Install the required Node Packages npm install
- Start gulp to monitor your dev environment for any changes that need post processing using npm start command.

Then in the console I launch
`sh build.sh`
Radarr is built without error.

But when starting Radarr with `mono ~/Radarr/_output/Radarr.exe --nobrowser` a window is opening and the Radarr version started is 0.1.0.33490 and not the latest one !

How can I build the latest one?

I am using Ubuntu, the latest mono-develop, ...

Thanks

**Comment by galli-leo** [comment]
That is probably the latest one. The development versions don't have the correct version, since that's patched by our build version.
