### ISSUE TITLE
Feature Request: Removing 0 seeder torrents

### ISSUE THREAD

**Issue by mccorkled** [Radarr/Radarr#2494]
Is there a way to add the removing of torrents if they haven't done anything after X amount of hours or day? I am using some site that search many providers and they sometimes grab torrents with 0 seeders and then Transmission just sits there, and Radarr waits for them to complete rather than going out and searching again for a different listing. 

Thanks

**Comment by galli-leo** [comment]
Turn on advanced settings, set minimum seeders to anything other than 0

**Comment by mccorkled** [comment]
I have 3 seeders set for all indexers and it's still grabbing 0 seeder torrents.

**Comment by galli-leo** [comment]
Then your indexer is returning wrong information.

**Comment by mccorkled** [comment]
It's a generic indexer that pulls from many. This was a feature requested in Sonarr as well.

https://github.com/Sonarr/Sonarr/issues/958

**Comment by galli-leo** [comment]
Try setting your dl client up to remove stalled torrents then, I can open the issue again, but this will probably never get implemented. (So I don't really see the point in leaving the issue open, as minimum seeders works for almost all users)

**Comment by mccorkled** [comment]
I am using Transmission through Docker and that is not an option. Even if it were, Radarr would just grab the same torrent again. It may be working for most people, but when I have over 50 0 seeder torrents getting grabbed, I would suspect many are having this issue as well.

**Comment by galli-leo** [comment]
Radarr should try another release when your dl client errors it. Anyways, I will open it again, but as I said probably not gonna be implemented. I would suggest talking to your indexer staff about correctly reporting seeders count.
