### ISSUE TITLE
[Feature Request] Add extra rename options

### ISSUE THREAD

**Issue by RoChess** [Radarr/Radarr#2495]
Probably low demand for this, but I believe it would be relatively easy to add.

{MediaInfo Width}  -- example: 1920
{MediaInfo Height) -- example: 1080
{MediaInfo AudioBitrate} -- example: 640 (from "640 Kbps" value MediaInfo GUI reports)
{Profile} -- string of the Radarr profile used for the respective movie

**Comment by bakerboy448** [comment]
Closing
v0.2 is no longer being actively developed.

If this is still an issue/request on recent v3 builds, please open a new issue.

various improvements have been made in v3
