### ISSUE TITLE
Epic Fail - BadImageFormatException

### ISSUE THREAD

**Issue by DeathByDentures** [Radarr/Radarr#2508]
Been looking into this issue that showed up a few days ago. I cannot launch Radarr at all. I ran the console and enabled logging as it stated. No effect. Screenshots below. Can anyone lend some expertise?

Radarr 0.2.0.935
Windows 10

![radarrerror0](https://user-images.githubusercontent.com/20209970/36076611-2cdac624-0f24-11e8-8e61-c6991194b102.PNG)

![radarrerror](https://user-images.githubusercontent.com/20209970/36076616-36eef7de-0f24-11e8-987d-a2d2ffe049b6.PNG)

![radarrerror1](https://user-images.githubusercontent.com/20209970/36076618-3a88b416-0f24-11e8-8c3c-503abb21d0d2.PNG)

**Comment by galli-leo** [comment]
Try reinstalling using the installer on our website. Seems like you lost a dll (Could be due to an antivirus deleting it).

**Comment by DeathByDentures** [comment]
Thanks! All back up and running. I restored my config and data base files from my backup and I'm back where I left off!
