### ISSUE TITLE
Movie Editor - Profile change not sticking

### ISSUE THREAD

**Issue by wjhanna** [Radarr/Radarr#2509]
When in the Movie Editor, I'll select all movies and try to change the profile (in this case, to Any). It will reflect as completed successfully in the Movie Editor, but the actual movie has not been updated.

I've tried the UI count as: 1000, 250, 100, and 25 and none of them are working. 

From what I can tell, there aren't any log entries at all regarding the change (or not change, in this case)

Radarr Version: 0.2.0.935
Windows Server 2016
Running as VM
4 vCPU
2gb ram
60gb SSD
*VERY* large library, 7100 entries

**Comment by galli-leo** [comment]
Did you get a message saying "Done Saving"? It works for me on the latest release.

**Comment by wjhanna** [comment]
Looks like it could be two issues, one being user error. I wasn't waiting for the "Done Saving" message box, but once you click the Save button it moves to the next page so I made the assumption the task was completed.

It looks like the smaller scopes (250 and below) are working with 250 taking about 40 seconds to complete. I'm either not waiting long enough (unlikely, it's been sitting at 10 minutes for a 500 movie edit), or there's something getting stopped up in the large edits.

**Comment by galli-leo** [comment]
Hmm that could be the case, I will try to take a look, but for now 250 movies are ok.
