### ISSUE TITLE
Custom torznab indexer doesn't let you configure the API path

### ISSUE THREAD

**Issue by coaxial** [Radarr/Radarr#2510]
**Description:**

When I add a torznab indexer, it doesn't let me configure the API path. As a result, it will try whatever URL I enter and append `/api`. This doesn't work for Jackett where it should use `http://<jackett host>/torznab/all`.

Sonarr has a field to configure this:
![screenshot from 2018-02-11 20-11-20](https://user-images.githubusercontent.com/2927869/36081058-d115bd0a-0f67-11e8-9925-4ee6b14d276c.png)

But Radarr doesn't and assumes `/api`:
![screenshot from 2018-02-11 20-12-34](https://user-images.githubusercontent.com/2927869/36081062-f0d5818e-0f67-11e8-814c-d1f1099c9103.png)

**Radarr Version:** 0.2.0.910 - 14 Dec 2017 

**Mono Version:** 5.4.1.6 (tarball Wed Nov 8 20:37:08 UTC 2017)

**Debug Logs:**
```
Unable to connect to indexer: Uri didn't match expected pattern: http://torrent_aggregator:9117/aggregator/torrent/torznab/all/api?t=caps&apikey=(removed): Uri didn't match expected pattern: http://torrent_aggregator:9117/aggregator/torrent/torznab/all/api?t=caps&apikey=secret
```

**Comment by galli-leo** [comment]
That’s because a torznab indexer (per spec) has all requests on /api. I can add an exception for Jackett, but honestly you should tell Jackett to conform to the spec.

**Comment by galli-leo** [comment]
Requests need to go to /api. Don’t know why radarr is complaining will take a look.

**Comment by fryfrog** [comment]
Careful w/ the "all" Jackett feed, it has some weird limitations and behaviors.

**Comment by coaxial** [comment]
@fryfrog what do you mean?

**Comment by fryfrog** [comment]
Which part? It has been awhile since I looked a Jackett's all feed and when I did, there were some oddities. I *think* it could only be used for one thing, either feeds or searches (I don't remember which). And because torrent indexers do weird things with categories, also issues.

So you should add each one individually. Or use nzbhydra2 to aggregate them. Jackett's aggregation isn't great.

**Comment by biship** [comment]
FYI http://<jackett host>/torznab/all works perfectly (for me) with Sonarr. I'd love you guys to add this! 👍

**Comment by galli-leo** [comment]
@biship /all should work fine with Radarr as well, at least it does for some people (It shouldn't be any different than other indexers).

**Comment by biship** [comment]
Hi @galli-leo 
"All The Money In The World"
Search within Jackett: 304 results
Search from Radarr: 15 results
Radarr's results seems to be a mix of Jackett's Trackers (I don't see a pattern).
I'm searching with the same categories in both apps. 1+ seeders, 

Radarr Log:
```
18-3-26 09:00:14.1|Info|NzbSearchService|Searching 1 indexers for [All the Money in the World]
18-3-26 09:00:58.2|Info|DownloadDecisionMaker|Processing 15 releases
```

Radarr indexer config for Jackett:
```
http://localhost:9117/torznab/all/
2000,2020,2030,2040,2045,2050,7000,7010,8000,8010
Search by title: NO
Minimum seeders: 1
```

What type of additional log do you need?

**Comment by galli-leo** [comment]
@biship Try enabling search by title. Probably not all of your indexers support searching by imdbid, so they will not return a result when Radarr searches.

**Comment by biship** [comment]
Hi @galli-leo 
Before I do that, I changed my jacket/all indexer url to just one indexer:
`http://htpc:9117/api/v2.0/indexers/1337x/results/torznab/`
Leaving all other settings the same, Radarr returned 20 results (jackett app also returned 20!). (good!)
When using searching in Radarr using jackett/all not one of the 15 results were from 1337x.

**Comment by galli-leo** [comment]
@biship If you look the the debug logs, Radarr will probably have searched by title on its own. Jackett usually tells Radarr whether searching by imdbid is supported or not. I am guessing it does not do the same for the all indexer.

**Comment by biship** [comment]
For jackett/all Radarr debug log shows:
```
18-3-26 09:49:15.6|Info|NzbSearchService|Searching 1 indexers for [All the Money in the World]
18-3-26 09:49:15.6|Debug|Torznab|Downloading Feed http://localhost:9117/torznab/all/api?t=movie&cat=2000,2020,2030,2040,2045,2050,7000,7010,8000,8010&extended=1&apikey=(removed)&offset=0&limit=1000&imdbid=5294550
18-3-26 09:49:48.3|Debug|NzbSearchService|Total of 15 reports were found for [All the Money in the World] from 1 indexers
```
Which if I use that link myself, returns 15 hits.

For jackett/1337x Radarr debug log shows:
```
18-3-26 09:56:52.8|Info|NzbSearchService|Searching 1 indexers for [All the Money in the World]
18-3-26 09:56:52.8|Debug|Torznab|Downloading Feed http://htpc:9117/api/v2.0/indexers/1337x/results/torznab/api?t=search&cat=2000,2020,2030,2040,2045,2050,7000,7010,8000,8010&extended=1&apikey=(removed)&offset=0&limit=100&q=all%20money%20in%20world%202017
18-3-26 09:57:05.0|Debug|NzbSearchService|Total of 20 reports were found for [All the Money in the World] from 1 indexers
```
Which if I use that link myself, returns 20 hits.

So it looks like when using /all, it's using t=movie & imdbid, otherwise when using just jackett/1337x it uses t=search (by name)(even though I have it set NOT search by name).

Changing jackett/all to search by title returns 300+ hits.

**Comment by galli-leo** [comment]
Yup so my assumptions was correct. Gonna open an issue on Jacketts side for this.

**Comment by biship** [comment]
Nice, thanks for helping work this out.

**Comment by kaso17** [comment]
@biship can you please try getting an APIkey for OMDB (http://www.omdbapi.com/) and configuring it in jackett (at the bottom of the page), it might fix your issue.

**Comment by ldexterldesign** [comment]
FYI

Hey all,

Hope you're well

Thanks for software

Adding an OMBD API key appears to fix this issue for me

Keep up great work

Regards

**Comment by ldexterldesign** [comment]
``http://127.0.0.1:9117/torznab/all`` has stopped working for me in the past few days (i.e. unable to retrieve any search results), both with and without the use of OMBD key. If I add individual indexers then I see search results.

The only reasoning I have for this issue is that one of the indexers is limiting my search(es) and so brings down the whole ``/all`` feed - would I be punctilious in assuming this is what's going on?:

If no, please can anyone suggest other reasons

If yes, how can I check which indexer is limiting me - will this show in logs

NB I updated to latest OSX mono (5.12.0.226), jackett (0.8.1106.0), radarr (0.2.0.1120) today

Hope this is clear/useful and to hear back

Yours faithfully

**Comment by kaso17** [comment]
@ldexterldesign have a look at the jackett/radarr logs to see why the all feed fails. using individual indexers is recommended anyway. The all feed will not return more results than the individual feeds.

**Comment by fryfrog** [comment]
Like @kaso17 says, the `/all` feed has a handful of issues that make it impractical to use. Switch to individually setting them up. If you want to aggregate them, use nzbhydra2 to pull them in individually and then feed *that* into radarr/sonarr.

If you want to persist in using `/all`, you'll need to figure out which of your torrent indexers is causing the problem. If you can't figure it out from the logs, just disable or delete them one at a time until the issue goes away.

**Comment by ldexterldesign** [comment]
Hey @kaso17 @fryfrog,

Thanks for reply

> https://github.com/theotherp/nzbhydra2/#how-to-run

Individual indexers it is then!

Cheers

**Comment by sircod** [comment]
So why was this closed? Sonarr has a couple torznab presets with an api path other than /api which don't work in radarr. Is there any way to make this work?

As seen in sonarr:
thubusercontent.com/2597002/43759840-50781280-99d5-11e8-899e-6c7850931d9b.JPG)

**Comment by sircod** [comment]
Hey @animetosho do you know how to get your torznab feed working in radarr? Preset from sonarr seems to be out of date, although it works there. Does not seem to work on radarr no matter how I tweak things around.

**Comment by animetosho** [comment]
I'm sorry that I haven't used Radarr, but https://feed.animetosho.org/api works as an API endpoint now, if that helps.  
Otherwise, what information can you provide about it not working?

**Comment by sircod** [comment]
Thanks, that is working for me now. I didn't have anything in the normal categories section, I thought anime categories would be all that is needed.

**Comment by ldexterldesign** [comment]
FYI

Currently using http://localhost:9117/api/v2.0/indexers/all/results/torznab/ without issue

If you have any issues (e.g. questions/queries) happy to help

Hope this helps!

Regards

**Comment by kaso17** [comment]
@lukyjay which torznab feed are you trying to add?

E.g. jackett will accept requests to the corresponding indexers with or without a tailing /api.

@ldexterldesign The error you're seeing is due to incorrect API usage. Have a look at the RSS links generated by jackett to see valid API usage examples.

**Comment by kaso17** [comment]
@ldexterldesign: no the API endpoint is correct but you've to add some required parameters, e.g.: 
http://127.0.0.1:9117/jackett/api/v2.0/indexers/all/results/torznab/?apikey=XXX&t=search

Added some disadvantages for /all via https://github.com/Jackett/Jackett/commit/25ddcb10bbf6e395a6cb33a8d10785c085e363ba#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by ldexterldesign** [comment]
@kaso17

Thanks, clearer on the API now after having a little http://getpostman.com session, although still unclear about the ``t`` param/values and ``configured`` param

Param default values would be worthy additions to the README

Yours hopefully

**Comment by Badooka** [comment]
For anyone else looking for the answer and doing hours of Googling, here it is:

for the URL, put http://10.0.0.23:9117/api/v2.0/indexers/kickasstorrent/results/torznab/

And the API just use your same API key.

Thanks

**Comment by Qstick** [comment]
In Aphrodite
