### ISSUE TITLE
Error on movie import

### ISSUE THREAD

**Issue by stevekr** [Radarr/Radarr#2514]
After movie is downloaded and movie file is imported, remaining files are not deleted and job is not removed from download client. Log shows ImportApprovedMovie warning
> Couldn't import movie /volume1/Downloads/Movie.2017.1080p.WEBRip.DDP5.1.x264-GROUP/Movie.2017.1080p.WEBRip.DDP5.1.x264-GROUP.mkv: Could not find a part of the path '/volume1/Media/Movies/Movie 2017'.

Create empty movie folders setting is off, so no “Movie 2007” folder exists. This issue started after last update.

**Radarr Version:** 0.2.0.935

**Mono Version:** 5.4.1.6

**Comment by galli-leo** [comment]
Do you have dynamic paths on? If so this is fixed on the latest nightly.

**Comment by stevekr** [comment]
Yes, Movie Paths Default to Static setting is off.
