### ISSUE TITLE
Response to preflight request doesn't pass access control check

### ISSUE THREAD

**Issue by davidloiret** [Radarr/Radarr#2516]
When using the API from a browser client, I have CORS issues on OPTIONS (aka preflight request)
For example:
OPTIONS `http://192.168.1.15:8310/api/movie`
Give the following error: `Response to preflight request doesn't pass access control check : No 'Access-Control-Allow-Origin' header is present on the requested resource.`
If I understand correctly the `Access-Control-Allow-Origin` header is set to `*` on GET, POST, PUT, DELETE requests but not on OPTIONS.
Setting `Access-Control-Allow-Origin: *` on OPTIONS should fix the problem.

Thanks

**Comment by AeonLucid** [comment]
Perhaps a switch to enable / disable CORS would be better. Don't want to open up everything by default.

Is this really a necessary enhancement though?
