### ISSUE TITLE
Add transparency to Radarr icon for Join notifications

### ISSUE THREAD

**Issue by jwildman16** [Radarr/Radarr#2518]
I'm not certain this is the issue but I think if transparency is added to the Radarr logo in the areas that are currently white, the logo would show correctly in the notification bar on Join notifications, instead of showing as a solid circle. 

[Here is how the icon currently looks (4th icon in from the top left](https://i.imgur.com/t6mo16H.png). 

[Here's a version of the Radarr logo with a transparent interior](https://i.imgur.com/WfcxC8g.png). 

https://github.com/Radarr/Radarr/blob/b3e46d02c6cc03cf812c384fe6edf330cd3f07bd/src/NzbDrone.Core/Notifications/Join/JoinProxy.cs#L90

**Comment by galli-leo** [comment]
Did you try it out with the transparent interior? If it works, you could open a pr with your fixes.
