### ISSUE TITLE
Download status on movielist and moviepage

### ISSUE THREAD

**Issue by jOOc** [Radarr/Radarr#252]
I just added a movie and started downloading it. In the movie list and on the movie info it still shows up as missing (from disk I assume).

Suggestion
Make the status downloading instead. In a huge list of missing movies, this is a nice status to have.

**Comment by joelm3103** [comment]
Commenting to find back issue later. (Can't (or can't seem to find at least) filter issues by subscriptions)

**Comment by jaxjexjox** [comment]
I see my request rightfully closed as a duplicate and I'm fine with that.

However, I see the referenced ticket (this one) is ALSO closed.

Can I clarify is this is a "nice to have" one day, or a "denied"?  Or what?
(Sorry, I can't see any notes here clarifying this?

**Comment by jaxjexjox** [comment]
Thanks I appreciate it.

**Comment by jaxjexjox** [comment]
So we're finally going to see more than just 'missing'?  I have 6 films right now, in my download package / queue but they're still 'missing'  be nice if 'downloading'  'queued' 'incoming' etc.

**Comment by djoole** [comment]
+1

Something like that : 
![screen]
(https://imgur.com/a/84u2JZG)
And ability to filter

**Comment by jaxjexjox** [comment]
You can't continue to close all the jobs that reference this original job *and* keep this job closed.

At some point you'll have to acknowledge one of them - ideall this one.

All people want is a 'snatched' status. I don't even use Radarr anymore but stumbling across this thread and seeing it closed again, ain't good.

**Comment by Qstick** [comment]
When there is a large green label next to the issue that reads OPEN, that should be a good indicator that this issue is not closed or being kept closed @jaxjexjox. Also the fact that we have a confirmed label on it would indicate we have acknowledged this.
