### ISSUE TITLE
Movies Added Through Plex Request Do Not Search When Added

### ISSUE THREAD

**Issue by speedyflipper** [Radarr/Radarr#2524]
I've noticed that movies that are added using plex requests do not search when they are added. Instead the search usually happens overnight. 

I'm not sure if this is a setting I am missing, a radarr issue or a plex requests issue. 

It isn't too much of an issue since I rarely plan to watch the movies immediately but thought I'd ask/mention it.

**Comment by galli-leo** [comment]
This is an issue with plex requests. When doing the add movie api call, you can specify whether you want to add and search or only add
