### ISSUE TITLE
[Feature request] No language select or language priority.

### ISSUE THREAD

**Issue by razlebol** [Radarr/Radarr#2526]
It would be nice if you could make a profile that doesn't use a language requirement. 

Why? Because I like to download my movies in 2 languages. (French and English). Those releases do not have the english or french tag in the name. They instead have the MULTI tag which makes radarr thinks the movie is in English. 

Well just choose the English language you say. Well sometimes the release do have French in the name and Radarr doesn't pick it up.

My first suggestion would be to be able to either not select any language at all and have radarr choose releases with the prefered tags I added. For example, my prefered tags are MULTI, French, VFQ, x265, HEVC.

My second suggestion would be to add 2 language selections instead of 1 and prioritize one.  That way I could select French and IF it doesn't find anything (with my prefered tags too) than look for it in English (also with the tags).

My third one would be just to add MULTI as a language selection.

Thank you for taking the time to read my suggestion. 
Have a nice day

**Comment by galli-leo** [comment]
See all other issues made on this topic. If you want a good overview click on projects -> Project Metis. This is actively being worked on, and most of the work is actually alreqdy complete (e.g. selecting what multi means if Radarr doesn’t find enough language tags) I would link it but currently on mobile
