### ISSUE TITLE
Not finding all possible matches from rarbg

### ISSUE THREAD

**Issue by Slider1385** [Radarr/Radarr#2527]
I'm just setting everything up for the first time here.  The only indexer I'm using is rarbg (I wish I could get private trackers, but i've had the best luck with it over the years even being public), but it seems like all the available torrents aren't available??

For instance, I'm just starting to upgrade to UHD videos.  If I search on rarbg for the latest TMNT movie I get the version I want to download https://rarbg.to/torrent/zgpwkfd , but when I manually search in radarr, this version won't show.  This is the third or fourth movie I've tried this way but hasn't found these 4k releases I'd like to get.

Like I said, I'm new to radarr, sorry if it's an easy fix or if I should have included a log or something with my post.  Thanks for the help!

**Comment by weirdcrap** [comment]
Please use the [Discord](https://discord.gg/u3x3Kp8) or [Subreddit](https://www.reddit.com/r/radarr/) for issues that are not bugs (or are not yet confirmed to be bugs).

**Comment by galli-leo** [comment]
Seems like this is an issue with rargb's api. I cannot seem to find the specific release, regardless of which search parameters I use (text or imdbid). Maybe they haven't opened x256 or hdr categories for api usage yet? Anyways I would talk to them.
