### ISSUE TITLE
Add the ability for List Imports to update existing Movie Profiles/Tags etc.

### ISSUE THREAD

**Issue by enchained** [Radarr/Radarr#2529]
Right now when you add a movie to a list, it looks like it just gets ignored if it already exists in Radarr. Wouldn't reapplying the list settings for a movie make more sense in some cases? Preferably, as a list option - "Override existing movies settings", off by default. 

For example, if the movie in Radarr is not monitored, and has 720p profile, adding the same movie to a list with settings "monitored" and "1080p" would apply those to an existing movie.

[AB#864](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/864)

**Comment by Womick** [comment]
not sure if this is the same issue but I have set up my default directory naming structure for movies and is working well.

To organise my movies, I have created another directory for a series of movies eg: /James Bond/.
When i try to get Radarr to scan /James Bond/ and include the movies in that directory, it returns an error "Invalid request Validation failed:  -- Path is an ancestor of an existing path"

Can this be a request for the next bug/fix release please

**Comment by enchained** [comment]
@Womick How is this related to the list NetImports exactly? This issue is not about existing files/directories import at all. It's about IMDB watchlists etc.

**Comment by galli-leo** [comment]
I marked this as a feature request, but it's gonna be a very low priority.

**Comment by galli-leo** [comment]
@Womick Where are you trying to add /James Bond/ that you get that message? Also that's a support question, more suited for subreddit or discord.

**Comment by Womick** [comment]
@galli-leo I have defalt /Movies directory.  I have a sub directory "/Movies/James Bond".  I have a movie "1962 - Dr. No.mkv" movie that Radarr doesnt pick up and i get the "Invalid request Validation failed: -- Path is an ancestor of an existing path" error when trying to do an import.

.....and apologies for the mis-post, still working my way through the support maze.

**Comment by Womick** [comment]
yes

**Comment by Womick** [comment]
yes of the /Movies directory and all sub directories

**Comment by galli-leo** [comment]
@Womick How does the full path to 1962 - Dr. No.mkv look like?

**Comment by Womick** [comment]
/Movies/James Bond/1962 - Dr. No.mkv

The movie is a file not a directory.  Makes it easy for navigating on the TV

**Comment by galli-leo** [comment]
Well in that case, it won't currently work. You need each movie file in it's seperate folder (with a year too)

**Comment by Mushin** [comment]
I think this would be a very useful feature. Firstly, for going through the list of existing movies with cutoff unmet and deciding what to do with them, doing this systematically by lists would be much easier than manually checking each one. Secondly, it would be great for example in top rated movies where I'd put them in a 1080p profile, then a 2160p version gets released. These would otherwise stay at 1080p unless I manually changed the profiles.

**Comment by bakerboy448** [comment]
When an update is made; available an update will be made.

The main development team is split across 3 apps: Radarr, Readarr, and Lidarr.
There are only 3 or 4 active developers who work on this, and of those 3 or 4 exactly zero work on this fulltime. Exactly zero of any members involved (developers / support) get paid to do this. Everyone of us has fulltime real jobs. Everyone of us has kids and family. Everyone of us works on more than just this project.

**Comment by Mushin** [comment]
@bakerboy448 Thanks for the info - I appreciate all your efforts (and have contributed to the projects). I just wanted to check if the situation might have changed, as this issue was created before v3 (and some new list functionality came in for additional radarr instances).

**Comment by Mrpink200** [comment]
id like also to have this feature added. for example, i would like to apply tags to a list of films i would created (or grabbed) from trakt to add this tag to the file movie naming (i would like plex to add the file name filter available ... but it is a long long story). At this pont all the movie not already in radarr is imported and apply the tag i put in the trakt list in radarr ... but does nothing for the movies i already have ... so sad

**Comment by IzaacJ** [comment]
This would be an awesome addition! I've wanted something like this myself since I started using Radarr/Sonarr a few weeks ago.

**Comment by Qstick** [comment]
No plans for this right now
