### ISSUE TITLE
importing current library

### ISSUE THREAD

**Issue by mafiatiez36** [Radarr/Radarr#253]
When trying to import my current library Radarr doesn't see my media.  I think the problem is that they are all in a couple of directories, not folders.  Is there a workaround for that?  I really don't want to have to put over 1000 movies into folders.

A current CouchPotato user that really wants to love this product!!

**Comment by onedr0p** [comment]
Related #153, Radarr is only set up currently to handle movies files that have their own folder, for example: `Movie name/Movie name.mkv`

**Comment by onedr0p** [comment]
Also there are a few programs that can automate moving the moviefiles into their own folder, I heard therenamer can do it.

**Comment by mafiatiez36** [comment]
OK thank you, do you know if that will change?  Or do I have to change? :)

**Comment by onedr0p** [comment]
If I were you I would change because it's a standard a lot of people have. However you aren't alone wanting to have custom folder structure feature added to radarr.

**Comment by onedr0p** [comment]
Closing per #153
