### ISSUE TITLE
Organising movies doesn't update the Path

### ISSUE THREAD

**Issue by CodaAmok** [Radarr/Radarr#2534]
Movie static path: yes
Settings > Media Mgmt > Automatically Rename Folders: yes
Settings > Media Mgmt > Movie Paths Default to Static: no

Movie Editor > Select all > Static Path: No

Movie Editor > Select all > Organise: all files and folders rename appropriately, carrying additional files that were also in the original directory, however the "Path" does not update; still points to old location on disk.

**Comment by CodaAmok** [comment]
Did you really want this closed @galli-leo ?

**Comment by goldenpipes** [comment]
i think the bot just closed it due to inactivity
