### ISSUE TITLE
Import Exclusions -- bulk action?

### ISSUE THREAD

**Issue by thezoggy** [Radarr/Radarr#2536]
settings > list > Import Exclusions
I can check off one/everything but there is no button to perform a bulk action on...
![radarr](http://zoggy.net/firefox_2018-02-18_17-12-11.png)
...
![radarr2](http://zoggy.net/firefox_2018-02-18_17-15-17.png)
also to note, the 'Title' column acts like it should be sortable, but it does do anything.

On Nightly branch // Radarr Ver. 0.2.0.964

**Comment by webpeon** [comment]
I am seeing the same issue with no action to perform after one selects all.   This is under Settings -> Lists -> Import Exclusions.  I am using Radarr version 0.2.0.1120 / June 10 2018 on Windows.
