### ISSUE TITLE
Bulk Import - uncheck on sort / non-sortable columns

### ISSUE THREAD

**Issue by thezoggy** [Radarr/Radarr#2539]
Add movies > Bulk Import
Select all/some movies, then sort list by Monitor or Profile, it unchecks everything. Is this by design?
![radarr](http://zoggy.net/firefox_2018-02-18_17-48-03.png)

Seems quite odd that you can even sort on these fields.. because if I change the profile or monitor, it changes all of them. Thus the sort is invalidated as all the selected column data is the same.

Would be nice to be able to sort by Movie/Path/Quality on this page..

**Comment by galli-leo** [comment]
Problem is, we only load the second page when you hit the pager. Thus we aren't really able to sort anything. We will probably change that with the new ui and an overhauled bulk import.
