### ISSUE TITLE
AlternativeTitles remain for movies even after removing them

### ISSUE THREAD

**Issue by thezoggy** [Radarr/Radarr#2542]
nightly //  Radarr Ver. 0.2.0.965

AlternativeTitles remain for movies even after deleting movie from radarr.

I used the movie editor and deleted all the movies in my db. Radarr shows I have no movies, shutdown db and copied db so I can view it in another app. Started radarr back up to compare against.

Browsing db copy:
![radarr](http://zoggy.net/DB%20Browser%20for%20SQLite_2018-02-18_18-16-35.png)

**Comment by thezoggy** [comment]
With radarr shut down, I renamed nzbdrone.db to nzbdrone-old.db, started it up.. prompting me to login but wont accept anything. That .db has 0 users.. tried another browser.. still wont let me in. Tried a space for username+pw, it throws the error:

```
{
message: "The string can't be left empty, null or consist of only whitespaces. Parameter name: resource.Username",
description: "System.ArgumentException: The string can't be left empty, null or consist of only whitespaces. Parameter name: resource.Username at NzbDrone.Common.EnsureThat.EnsureStringExtensions.IsNotNullOrWhiteSpace(Param`1 param) in C:\projects\radarr-usby1\src\NzbDrone.Common\EnsureThat\EnsureStringExtensions.cs:line 16 at NzbDrone.Api.Authentication.AuthenticationModule.Login(LoginResource resource) in C:\projects\radarr-usby1\src\NzbDrone.Api\Authentication\AuthenticationModule.cs:line 27 at NzbDrone.Api.Authentication.AuthenticationModule.<.ctor>b__2_0(Object x) in C:\projects\radarr-usby1\src\NzbDrone.Api\Authentication\AuthenticationModule.cs:line 21 at CallSite.Target(Closure , CallSite , Func`2 , Object ) at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)"
}
```

**Comment by galli-leo** [comment]
Will have to add a housekeeper for the alternative titles, forgot about that. Regarding sonarr tables, will probably clean that up in a migration before 1.0 is released.

To be fair, the last point is not really an issue. If a user just deletes the db without clearing the config file too, that's on them. (Also easily fixable).

**Comment by Qstick** [comment]
@galli-leo I think you already have a housekeeper for alt titles, it likely didn't have a chance to run in this instance if it was shutdown right after delete. We likely need a event handler in alt titles service to delete right when a movie deleted event is thrown. Then the house keeper is just there to clean up unclean deletion

**Comment by galli-leo** [comment]
@Qstick Hmm, is that necessary in that case? i.e. does movie file have that?

**Comment by thezoggy** [comment]
Also though, easy enough to show a warning on the logo n screen if there are 0 users to auth against...

**Comment by Qstick** [comment]
@galli-leo Yep, movieFile does that in media file service on a movie deleted event. Though it's been modified to only do it when delete files checkbox is checked, which I'm not sure makes sense given the house keeper is always going to clean them anyway. It should clean them from the db either way I would say. It's not actually deleting the files there
