### ISSUE TITLE
Import failed -- different path being used than instructed on import

### ISSUE THREAD

**Issue by thezoggy** [Radarr/Radarr#2545]
Using my existing radarr db but all movies had been nuked out (so I could keep my indexer/downloader/notifications/etc).

Using bulk import, adding movies from `M:\Movies-HD`. 
Selected the first 15 and told it to add.

I see that it added the movie "A Silent Voice" but then failed later on.
Looking at the logs on why it failed, it is because its trying to import it from an invalid path.. different than what I told the radarr to import from.

Logs:
```
18-2-18 23:13:14.1|Debug|DiskScanService|Scanning 'M:\Movies-HD\A.Silent.Voice.2016.Blu-ray.720p.DTS.x264-MTeam' for video files
18-2-18 23:13:14.2|Debug|DiskScanService|1 video files were found in M:\Movies-HD\A.Silent.Voice.2016.Blu-ray.720p.DTS.x264-MTeam
18-2-18 23:13:14.2|Debug|ImportDecisionMaker|Analyzing 1/1 files.
18-2-18 23:13:14.2|Debug|Parser|Parsing string 'movie.mkv'
18-2-18 23:13:14.2|Debug|Parser|Unable to parse movie.mkv
18-2-18 23:13:14.2|Debug|Parser|Attempting to parse episode info using directory and file names. A.Silent.Voice.2016.Blu-ray.720p.DTS.x264-MTeam
18-2-18 23:13:14.2|Debug|Parser|Parsing string 'A.Silent.Voice.2016.Blu-ray.720p.DTS.x264-MTeam movie.mkv'
18-2-18 23:13:14.2|Debug|Parser|Movie Parsed. A Silent Voice - 2016 
18-2-18 23:13:14.2|Debug|Parser|Language parsed: English
18-2-18 23:13:14.2|Debug|QualityParser|Trying to parse quality for A.Silent.Voice.2016.Blu-ray.720p.DTS.x264-MTeam movie.mkv
18-2-18 23:13:14.2|Debug|Parser|Quality parsed: Bluray-720p v1
18-2-18 23:13:14.2|Debug|Parser|Release Group parsed: MTeam
18-2-18 23:13:14.2|Debug|ImportDecisionMaker|Size: 8623076654
18-2-18 23:13:14.2|Debug|VideoFileInfoReader|Getting media info from M:\Movies-HD\A.Silent.Voice.2016.Blu-ray.720p.DTS.x264-MTeam\movie.mkv
18-2-18 23:13:14.3|Debug|ImportDecisionMaker|Checking quality for this video file to make sure nothing mismatched.
18-2-18 23:13:14.3|Debug|GrabbedReleaseQualitySpecification|No download client item provided, skipping.
18-2-18 23:13:14.3|Debug|SameFileSpecification|No existing movie file, skipping
18-2-18 23:13:14.3|Debug|FreeSpaceSpecification|Skipping free space check for existing episode
18-2-18 23:13:14.3|Debug|VideoFileInfoReader|Getting media info from M:\Movies-HD\A.Silent.Voice.2016.Blu-ray.720p.DTS.x264-MTeam\movie.mkv
18-2-18 23:13:14.3|Debug|DetectSample|Runtime is over 90 seconds
18-2-18 23:13:14.3|Debug|NotUnpackingSpecification|M:\Movies-HD\A.Silent.Voice.2016.Blu-ray.720p.DTS.x264-MTeam\movie.mkv is in series folder, skipping unpacking check
18-2-18 23:13:14.3|Debug|Parser|Parsing string 'A Silent Voice 2016'
18-2-18 23:13:14.3|Debug|Parser|Movie Parsed. A Silent Voice - 2016 
18-2-18 23:13:14.3|Debug|Parser|Language parsed: English
```
...
```
18-2-18 23:20:39.5|Debug|Parser|Parsing string 'A.Silent.Voice.2016.Blu-ray.720p.DTS.x264-MTeam'
18-2-18 23:20:39.5|Debug|Parser|Movie Parsed. A Silent Voice - 2016 
18-2-18 23:20:39.5|Debug|Parser|Language parsed: English
18-2-18 23:20:39.5|Debug|QualityParser|Trying to parse quality for A.Silent.Voice.2016.Blu-ray.720p.DTS.x264-MTeam
18-2-18 23:20:39.5|Debug|Parser|Quality parsed: Bluray-720p v1
18-2-18 23:20:39.5|Debug|Parser|Release Group parsed: MTeam
18-2-18 23:20:39.5|Debug|Parser|Parsing string 'A.Silent.Voice.2016.Blu-ray.720p.DTS.x264-MTeam'
18-2-18 23:20:39.5|Debug|Parser|Movie Parsed. A Silent Voice - 2016 
18-2-18 23:20:39.5|Debug|Parser|Language parsed: English
18-2-18 23:20:39.5|Debug|QualityParser|Trying to parse quality for A.Silent.Voice.2016.Blu-ray.720p.DTS.x264-MTeam
18-2-18 23:20:39.5|Debug|Parser|Quality parsed: Bluray-720p v1
18-2-18 23:20:39.5|Debug|Parser|Release Group parsed: MTeam
18-2-18 23:20:39.5|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: d:\sab-movies\A.Silent.Voice.2016.Blu-ray.720p.DTS.x264-MTeam\
```

Does Radarr query the downloader history to check if its been downloaded with it? If so, how can I disable this.. especially for Bulk Import.
As this is the only thing I can come up with how its trying to do another path:
![sab](http://zoggy.net/firefox_2018-02-18_23-37-26.png)

Additionally, the error  `Import failed, path does not exist or is not accessible by Radarr...` is repeating over and over for the item filling up my logs/table.
![radarr](http://zoggy.net/firefox_2018-02-18_23-33-54.png)

Then this also resulted in the actual Movie to be a 404:
![radarr2](http://zoggy.net/firefox_2018-02-18_23-45-45.png)

Looks like the issue caused 'Update Library' to hang as its still disabled/pending 30+ mins later:
![radarr3](http://zoggy.net/firefox_2018-02-18_23-47-21.png)

**Comment by thezoggy** [comment]
restarting radarr, now it shows that movie queue like I just had it grab it (confirmed nothing in radarr history):
![radarr](http://zoggy.net/firefox_2018-02-18_23-50-28.png)

**Comment by galli-leo** [comment]
Radarr will query your dl client for downloaded movies. So if it shows up in your sab history, Radarr will try to import it (if it didn't already import it). If you nuked your install, Radarr doesn't know it already imported it a few months ago, so it tries again. Easiest solution is to nuke your history in sab. Regarding the 404, an update library needs to happen for the correct url slug to be set. Not sure why update library wasn't running correctly, but probably gonna be difficult to reproduce.

**Comment by thezoggy** [comment]
I just told radarr to use a different category in Sab, that solves the history lookup issue. Personally I feel that bulk import should not be querying on bulk import. As radarr can (as it did) get bad/stale info. Also, that's a lot of unneeded hits to Sab API..

**Comment by galli-leo** [comment]
@thezoggy It doesn't hit sab on bulk import, it just does so every 30 seconds or so.

**Comment by thezoggy** [comment]
I thought maybe it was quering per import, but it just looked at history for that category.. which has less than 30 items.. so 1.5 years ago that item is in it.. thus it cock-blocked bulk import because it just happened to be in the sab history while its being imported..
