### ISSUE TITLE
Radarr quits after booting

### ISSUE THREAD

**Issue by BorisKamp** [Radarr/Radarr#2546]
Hi guys,

I've been unable to use Radarr for a while now. When I start radarr from the applications folder it shows up in my activity monitor, however it disappears shortly after. I've followed this https://github.com/Radarr/Radarr/wiki/FAQ and removed the files, restored from different backups but it's still not working.

Any help would be great.

**Radarr Version: latest, updated 19/02/2018**

**Mono Version:**

**Debug Logs:**
[sonarr.txt](https://github.com/Radarr/Radarr/files/1735917/sonarr.txt)

Please use the search bar and make sure you are not submitting an already submitted issue.

**Comment by galli-leo** [comment]
That's a Sonarr log.

**Comment by BorisKamp** [comment]
Sorry for the Sonarr log, this is however due to the fact that the FAQ needs to be updated. I followed the docs and went to the `~/.config/NzbDrone` folder, that where the log is from as well.
The docs should say to go to the `~/.config/Radarr` folder. I've only noticed because you told me it's a Sonarr log (looked over the name).

I followed the FAQ with this path and now it works after restoring a backup! tx!

I know you did not release an update today, I just said I updated today. the release date if feb 6th I see.

Anyway, everything works again, tx!

**Comment by galli-leo** [comment]
Should be correct here: https://github.com/Radarr/Radarr/wiki/AppData-Directory, what wiki page did say ~/.config/NzbDrone?

**Comment by BorisKamp** [comment]
Ah I see, When Google-ing for 'Radarr FAQ' I ended up here: https://github.com/Radarr/Radarr/wiki/FAQ

I probably won't be the only one (-:

**Comment by galli-leo** [comment]
Thanks edited. (Probably forgot to after copying it from Sonarr).

**Comment by BorisKamp** [comment]
Great! you're welcome. Thank you for the great piece of software!
