### ISSUE TITLE
Improve matching from Media Info (Parser Refactor)

### ISSUE THREAD

**Issue by dgauche** [Radarr/Radarr#2549]
I believe that after downloading / importing a movie Radarr scans the file to extract the quality of the video.

I have noticed that  a 1920x800 is recognized as a 720p movie. 

However I believe that movies are almost never shot in 16:9, which is the "default" resolution for 1080p, or 1920x1080.  The result is that movie aspect ratio causes a 1080p movie to have a Y resolution of 800 or something close instead of what Radarr is expecting.

The correct classification of a 1920x800 movie should therefore be 1080p even though the Y resolution is not 1080.

**Comment by galli-leo** [comment]
For now you can just put the correct resolution in the filename. This is almost fixed on the metis branch.
