### ISSUE TITLE
alt titles - question

### ISSUE THREAD

**Issue by thezoggy** [Radarr/Radarr#2550]
does radarr 'skyhook' have the ability to add scene exceptions/alternative titles? or does it only pull them from tmdb?

Movie: `Afro Samurai`, alt title: `Afro.Samurai.The.Movie`
![radarr](http://zoggy.net/firefox_2018-02-19_14-30-40.png)

added alt title to tmdb,
https://www.themoviedb.org/movie/62931-afro-samurai

**Comment by galli-leo** [comment]
It also pulls from https://mappings.radarr.video (currently no way to manually add titles) Titles are auto added when you do a force download (hence the orange download icon).

**Comment by thezoggy** [comment]
Yeah, I was just seeing if I should have submitted it via some googleform (like sonarr), or via github (like sickbeard) or what :)

**Comment by galli-leo** [comment]
Do you think a manual form would be useful? If so it would probably only take a few minutes to whip up a bootstrap form over at https://github.com/Radarr/RadarrWEB.Mappings
