### ISSUE TITLE
Feature Request: add nfo file with imdb id

### ISSUE THREAD

**Issue by breadcan** [Radarr/Radarr#256]
I'm using Plex and it would be great if Radarr adds a .nfo file with the imdb id in it (like CP does) so plex has the exact match for the movie.

https://forums.plex.tv/discussion/232808/wrong-movie-metadata-showing-up

And the original nfo file of the release could be moved too as "moviefilename.orig.nfo".

**Comment by ShanDestromp** [comment]
As of now metadata isn't being generated at all; probably safe to consider this a dupe of #167

**Comment by onedr0p** [comment]
Yes it is thanks!
