### ISSUE TITLE
poster view - info links extend outside container

### ISSUE THREAD

**Issue by thezoggy** [Radarr/Radarr#2561]
example:
![radarr](http://zoggy.net/firefox_2018-02-20_17-50-55.png)

can easily be fixed by using `min-height` instead of a fixed height.
whatever height you use isnt going to really be normalized when you can have a variable amount of info links.. but lets assume 4 is the norm (which is what you targetted towards), the height 382 is slightly off with radarr padding.. should be 386. so lets do a min-height of that, and we can see:

![radarr2](http://zoggy.net/firefox_2018-02-20_17-58-24.png)

**Comment by thezoggy** [comment]
which also brings me to the chaotic order of info links. 
![radarr3](http://zoggy.net/firefox_2018-02-20_18-00-57.png)

it looks like trakt/tmdb/imdb are the most common.. so those should go first to keep things static/predictable. then leave the rest at the end.. to keep things similar as before but to make it look cleaner.. you do homepage before trailer. should make things look cleaner...

**Comment by thezoggy** [comment]
and those buttons are so stark against the white bg.. and also blend in on the movies page.. perhaps using the primary label class would also be good:
![radarr5](http://zoggy.net/firefox_2018-02-20_18-12-32.png)

**Comment by galli-leo** [comment]
Yeah the links are a mess. I would like to replace them with icons and also have the ratings on hover or something
