### ISSUE TITLE
[Feature Request] Let Torrent Client Manage Download Path

### ISSUE THREAD

**Issue by zero77** [Radarr/Radarr#2567]
Can you please add the option to let the download client manage the download path instead of setting a path when adding a film. 
Thanks

**Comment by galli-leo** [comment]
The download client already manages the download path.

**Comment by zero77** [comment]
Radarr also seems to set a path which is selected when you add a new film, how can I stop this.

Because, I end up with two copy’s one from radar that’s inside a directory named the same as the film and one from the download client.

**Comment by galli-leo** [comment]
Enable hardlinks or setup your dl client to delete the seeding copy.

**Comment by zero77** [comment]
I have already done that, I am getting two copies one from the client and one from Radarr.

But, I may have found a fix when using rutorrent.

**Comment by galli-leo** [comment]
Yeah hardlinking will „create two copies“, but they only take up the space of one copy (unless they are on different drives).

**Comment by zero77** [comment]
I may not be explaining this very well but, what I mean is by setting a path at the time you add a film like “/home/user/Downloads/name of film 2018” and having a path set in the download client.

You end up with two copy’s like the renamed copy from radarr “/home/user/Downloads/name of film 2018” and the one from the client before any hardlinking, moving or removing takes place “/home/user/Downloads/name.of.film.2018.1080p” thus I end up with two copy’s at the end.

**Comment by galli-leo** [comment]
If you want to keep your setup the old way, I am afraid, you are probably better off not using Radarr and just manually downloading releases.

The point of Radarr is that it takes downloaded releases and imports it into a seperate media location, e.g. /home/user/Movies

Again, it will look like two copies, but it actually isn't.

**Comment by zero77** [comment]
Ok, I think I see what you mean.

Although, will the second file and directory’s created by radarr automatically be removed once the original has been moved or deleted?

**Comment by galli-leo** [comment]
No.

**Comment by zero77** [comment]
ok, thanks.
