### ISSUE TITLE
Poster sliding issues in 0.2.0.980

### ISSUE THREAD

**Issue by rcork** [Radarr/Radarr#2568]
with the latest update, when in Posters view, you can no longer select update or edit directly from the Poster because when you mouse over the icon, the poster slides up and clicking takes you into the movie. 

Also when in Poster view, if you move the mouse over the poster and down over the status (ie. Missing/Downloaded), the poster continually shifts up, down, up, down, etc.

**Comment by Qstick** [comment]
This may have been result of movie page depending on some of the series style pages we cleaned, I can take a look at this tonight
