### ISSUE TITLE
Activity/Queue

### ISSUE THREAD

**Issue by TTLucian** [Radarr/Radarr#2569]
Add a "source title" (torrent file name) column to Activity/Queue and Activity/History pages. This will allow quick checking/viewing of downloaded/downloading files/releases without checking individual movies pages or torrent client.
Also, in the same place, one column containing source indexers names (like in search page of individual movie) would be great.

**Comment by onedr0p** [comment]
Should we close this?

**Comment by Qstick** [comment]
Yes I say so
