### ISSUE TITLE
Movies Tab not showing requested movies

### ISSUE THREAD

**Issue by bcpletcher** [Radarr/Radarr#2572]
**Description:**
I am running Radarr in unRAID via docker and am having an issue with the main screen/Movies Tab. When I go to said tab, no movies appear and I a blank screen. It says in the bottom portion however that I do have movies and tells me what ones are downloaded/released and so on. I can also view them in the Wanted Tab, however I cannot manage them else wise since I cant access the Movie Editor. Any thoughts? I have also removed the docker and the appdata folder for a clean install and still receive the same error.
<img width="1368" alt="screen shot 2018-02-24 at 4 59 27 pm" src="https://user-images.githubusercontent.com/11952245/36635621-7490948c-1986-11e8-8ad0-2e27b8f58c84.png">

**Radarr Version:**
unRAID v0.2.0.980

**Mono Version:**

**Debug Logs:**
`
-------------------------------------
_ ()
| | ___ _ __
| | / __| | | / \
| | \__ \ | | | () |
|_| |___/ |_| \__/

Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donations/
-------------------------------------
GID/UID
-------------------------------------

User uid: 99
User gid: 100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[Info] Bootstrap: Starting Radarr - /opt/radarr/Radarr.exe - Version 0.2.0.980

[Info] AppFolderInfo: Data directory is being overridden to [/config]
[Info] Router: Application mode: Interactive
[Info] MigrationLogger: *** Migrating data source=/config/nzbdrone.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
[Info] MigrationLogger: *** Migrating data source=/config/logs.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
[Info] OwinHostController: Listening on the following URLs:
[Info] OwinHostController: http://*:7878/radarr/
[Info] OwinHostController: http://*:7878/
[Info] NancyBootstrapper: Starting NzbDrone API
[Info] NzbSearchService: Searching 5 indexers for [Who Framed Roger Rabbit]
[Info] DownloadDecisionMaker: Processing 61 releases
[Info] NzbSearchService: Searching 5 indexers for [Who Framed Roger Rabbit]
[Info] DownloadDecisionMaker: Processing 61 releases
[Info] DownloadService: Report sent to DelugeVPN. Who Framed Roger Rabbit (1988) 1080p DD5.1 - 2.0 x264 Phun Psyz
[Info] MovieSearchService: Movie search completed. 1 reports downloaded.
[Info] Nzbget: Adding report [Who Framed Roger Rabbit 1988 HDTV 720p h264.20-40] to the queue.
[Info] DownloadService: Report sent to NzbGet. Who Framed Roger Rabbit 1988 HDTV 720p h264.20-40
[Info] MovieService: Linking [Who Framed Roger Rabbit 1988 HDTV 720p h264.20-40.mp4] > [[tt0096438][Who Framed Roger Rabbit (1988)]]
[Info] RefreshMovieService: Updating Info for Fifty Shades Freed
[Info] DiskScanService: Scanning disk for Fifty Shades Freed
[Info] RefreshMovieService: Updating Info for Who Framed Roger Rabbit
[Info] MetadataService: Movie folder does not exist, skipping metadata creation
[Info] DiskScanService: Scanning disk for Who Framed Roger Rabbit
[Info] DiskScanService: Completed scanning disk for Who Framed Roger Rabbit
[Info] ExistingMetadataImporter: Found 0 existing metadata files
[Info] ExistingSubtitleImporter: Found 0 existing subtitle files
[Info] ExistingOtherExtraImporter: Found 0 existing other extra files
[Info] ExistingExtraFileService: Found 0 extra files`

**Comment by galli-leo** [comment]
Have you tried a different browser? Also can you open the chrome dev console and see if any errors are there?

**Comment by bcpletcher** [comment]
Hey, it was actually a weird issue with the Sort filter dropdown, It automatically chooses 'Downloaded' and when I change it to 'Title', they all appear. Whats even more odd, that might prove to be a bug is that when its sorted by Title the movies that are downloaded show the green downloaded status, however when I switch back to the 'Downloaded' filter, it shows the ones that are downloaded but the status shows as missing.

**Comment by galli-leo** [comment]
Yeah sort by downloaded is broken. Not sure why it defaulted to that, but there’s not much I can do until we have a new UI. Since we currently sort on the client side, sorting by downloaded is kinda impossible via sql

**Comment by maxcore** [comment]
i have the same problem with chrome

**Comment by maxcore** [comment]
@galli-leo fix for me with your lastest update 
Version 0.2.0.995 

BIG thx !
