### ISSUE TITLE
[Feature] Bulk import titles out of a txt

### ISSUE THREAD

**Issue by ghost** [Radarr/Radarr#2575]
**Description:**
Bulk import titles out of a txt
**Radarr Version:**
 Radarr Ver. 0.2.0.980
**Mono Version:**
?!?!?
**Debug Logs:**
None

**Comment by fryfrog** [comment]
If you want to achieve this right meow, you could use the text to create a dir and file structure, perhaps w/ a file named like `Movie Title (Year)/Movie Title (Year) DVD-480p.ext`. That way, they'll all import at low quality. Once they're in, delete the files and refresh.

**Comment by DafsCode** [comment]
@fryfrog I've done that, the script I used is on my profile :)

**Comment by bakerboy448** [comment]
No plans; easy work around
