### ISSUE TITLE
wrong poster when import and/or add new movies

### ISSUE THREAD

**Issue by drumstick77** [Radarr/Radarr#2577]
Hi All,

I can't seems to find the solution for this.
I'm running this in docker and whenever I add new movie or import from the one I had, it kept showing wrong poster.
I've tried the following and still to no avail:

- Tried the recommendation I found from another article to remove and re-adding by using the imdbid
- Tried by removing and readding the movie by title

Then I tried these steps
- stopped radarr within docker
- remove Mediacover folder with its content 
- restarted Radarr

I've also tried
- stopped and removed radarr 
- removed everything out of config folder that includes config.xml, nzbdrone.db
- Recreated Radarr

I'm not sure what else I should try as everything I can think of does not seems to be fixing the problem

Thanks in advance

**Comment by galli-leo** [comment]
MediaCovers are cached by your browser. Try clearing cache and cookies.

**Comment by drumstick77** [comment]
Still a no go. I tried different browser that I haven't used. still the same thing.
I've removed all cookies, still the same issue.

**Comment by drumstick77** [comment]
Thanks for that. how odd. Firefox seems to be working when I deleted the cookies but not chrome. Any idea why?

**Comment by drumstick77** [comment]
nevermind, it's working now. thanks!
