### ISSUE TITLE
Bulk Organize / rename

### ISSUE THREAD

**Issue by drumstick77** [Radarr/Radarr#2579]
Hi All,

Is there a way to bulk organise / rename files? or do I have to do one at a time?

thanks

**Comment by Qstick** [comment]
Use Movie Editor, select movies you want, hit organize.

**Comment by drumstick77** [comment]
aishhh....sorry bud, thanks for that. some bloody amateur I am. 
I kept looking for the button on the top, but the button is on the bottom bar.
thanks for that
