### ISSUE TITLE
Radarr - After import /dev/sda1 size keeps growing

### ISSUE THREAD

**Issue by drumstick77** [Radarr/Radarr#2580]
Hi Guys,

I just imported a bunch of movies in my radarr and i noticed that my /dev/sda1 drive keep growing in size.
does anyone knows why or maybe can suggest a treesize like for linux that I can install?
I've got the Radarr running in docker.

Cheers

**Comment by galli-leo** [comment]
By how much is it growing? A few megabytes for each movie? That's normal, since Radarr downloads the media covers for each movie.

**Comment by drumstick77** [comment]
/dev/sda1 from 3GB all the way up to 9GB
this morning, it went down to 7.5GB
and now it's gone back up to 8GB.

not sure what it is doing
wondering if there's a treesize like that I can use to find out what's what?

**Comment by galli-leo** [comment]
Something like `ncdu` could be used. How many movies did you add?

**Comment by drumstick77** [comment]
80 odd, but what confuses me is why is it going up and down.

**Comment by galli-leo** [comment]
Yeah, that is odd, could be a different program as well though. Or could be the logs growing and shrinking.
