### ISSUE TITLE
iCal content has an invalid format

### ISSUE THREAD

**Issue by someCynic** [Radarr/Radarr#2581]
The contents of the iCal response appears to not be valid in some scenarios, which breaks integration with Google Calendar (gCal hangs while fetching the content).
I've also validated the contents against [iCalendar validator](https://icalendar.org/validator.html) and believe I have identified the cause of the use issue in the code.

For movies that are "Announced", no dates are emitted to the output, so a partial calendar entry is generated with the following content:

```
BEGIN:VEVENT
DTSTAMP:20180225T024035Z
SEQUENCE:0
STATUS:TENTATIVE
UID:NzbDrone_movie_7
END:VEVENT
``` 

That entry causes the following problem in the validator:

> Missing DTSTART property in VEVENT near line # 6

In `CalendarFeedModule`, within the iteration of movies, the `switch` statement case for "Announced" movies just has a `continue;` statement, which causes the Event to be included without any dates.
In fact, at least in my case, the movie actually DID have InCinemas dates, but they are ignored for this status.

If "Announced" movies are to be excluded from the results, then the check should come prior to:
`var occurrence = calendar.Create<Event>();`

**Comment by galli-leo** [comment]
Should we add two events, in cinemas and physical (if we have both) for the ical feed?
