### ISSUE TITLE
kodi nfo file wrongly formatted field - premiered

### ISSUE THREAD

**Issue by hfunder** [Radarr/Radarr#2582]
premiered field is currently formatted as "7/18/2017 4:00:00 PM"

For the import it needs to be formatted as "2017-07-18"

Aside from that there is nfo missing:
genre
actor + thumbnails

**Comment by galli-leo** [comment]
Regarding the missing info, that will come with V3 for the Radarr API, since we currently don't store that data.

**Comment by Qstick** [comment]
@galli-leo I’ll knock this one out

**Comment by euphoria360** [comment]
Any News on this. Radarr is creating wrong nfo's which causes Kodi to show all movie's year as 1969!
As @hfunder said the format of "premiered" is wrong.
Also year is good to be included but the date displayed in Kodi comes from the <premiered> tag.
The best place to look for Kodi'd nfo structure is Kodi's Wiki for [Movie NFO's](https://kodi.wiki/view/NFO_files/movies).

Also, adding these fields would be great too:
`<outline>`   - A single line plot
`<votes>`   - Vote number of rating
`<tagline>`   - Short movie slogan
`<mpaa>`   - mpaa rating system
`<runtime>`   - Movie runtime. Minutes only
`<credits>`   - Name of writers. one for each writer
`<director>`   - Name of director
`<genre>`   - Genre of the movie. one for each genre
`<country>`   - Country of origin
`<tag>`   - Movie tags
```
<actor>
  <name></name>
  <role></role>
  <thumb></thumb>
</actor>
```

Anyway the Kodi plugin is a new addition and I'm sure it will be perfected in time.

**Comment by Qstick** [comment]
I’ll pr it tonight. Been out of down all weekend, just got back.
