### ISSUE TITLE
Systemd service won't start after mono update

### ISSUE THREAD

**Issue by kaysond** [Radarr/Radarr#2585]
Mono just got updated to 5.10.0.140 on Ubuntu 17.10. Now my radarr service doesn't start. The log says
```
Feb 27 13:00:16 fserver systemd[1]: Started Radarr Daemon.
Feb 27 13:00:16 fserver mono[4859]: Press enter to exit...
```
If I run `/usr/bin/mono /opt/Radarr/Radarr.exe -nobrowser -data=/var/lib/radarr` in a terminal, I get the same "Press enter to exit..." message

I have Radarr v0.2.0.980.

Obviously I can just roll back the mono version, but I'm wondering if this can be fixed...

**Comment by animosity22** [comment]
There is a similar issue over here:

https://github.com/Sonarr/Sonarr/issues/2431

I just rolled back my mono version for now.

**Comment by galli-leo** [comment]
According to taloth, an issue with NLog (always NLog 🤦‍♂️)

**Comment by Taloth** [comment]
@galli-leo Not always. Jackett is having some Autofac issue on mono 5.10 :smile:

Btw. I pushed our (Sonarr's) fix to our develop branch, but gonna let it stay there for a day or two before I get it out to master.
I also put up a single file download at https://download.sonarr.tv/hotfixes/regression-mono-5.10/NLog.dll.gz  but that's only for power users, ppl should stick with mono 5.8 till now.
The updated NLog version, seems to work for Sonarr _and_ Radarr in docker container I used for the smoke tests, but don't know about actual usage.

**Comment by galli-leo** [comment]
Ah thanks a ton for the testing and downloads!

**Comment by dutch2005** [comment]
thnx, used the NLog.dll , tested with 5.10 and 5.13 (nightly) and sonarr is working once more, once again ;)

**Comment by moster78** [comment]
Just a heads up that the NLog.dll isn't working with Mono 5.10 and Radarr on Ubuntu for me. Works just fine for Sonarr, thankfully! Thanks!

**Comment by Taloth** [comment]
@galli-leo fyi I just released to Sonarr master. I'll reply if issues come up.

**Comment by symbios24** [comment]
Hello i installed also both radarr and sonarr in latest DietPi stretch in a raspberryPi 3
Sonarr web interface loads fine but Radarr web interface is not loading can this be fixed manual?

Thanks

**Comment by galli-leo** [comment]
@Taloth Thanks! Just pushed a change, this should show up on nightly shortly.

**Comment by erickgrau** [comment]
Any chance anyone know how to request this update gets to Synology?  I can't start Sonarr and it as well as Mono are running latest available versions.  I think mono was updated and it broke Sonarr.

Help Please !

Synology 6.1.5-15254 Update 1
Versions grabbed from Package Center
Mono 5.8.0.108-11
Sonarr 20170106-9

Thanks,

Erick

**Comment by fryfrog** [comment]
Mono 5.8 is fine for both Sonarr and Radarr, I've been using it for ages. This issue is specific to 5.10.

**Comment by fryfrog** [comment]
@galli-leo: Fwiw, I don't see the fix coming through to nightly. Last one is Feb 28.

**Comment by betterbuckleup** [comment]
@galli-leo @fryfrog I second that, the update isn't showing up for me either

**Comment by attzonko** [comment]
You can manually grab NLog.dll until the fix arrives.

In the directory where you have Radarr installed just run:
`wget -O - http://download.sonarr.tv/hotfixes/regression-mono-5.10/NLog.dll.gz | gunzip -c > NLog.dll`

**Comment by samsepiol59** [comment]
@galli-leo how does your fix work? I mean, do I need to update radarr or something?! There's no new release!

**Comment by fryfrog** [comment]
The fix didn't build, so it was reverted. Still needs to be done and released. :(

**Comment by samsepiol59** [comment]
Ah ok, well thanks for the quickest answer ever! :)

**Comment by galli-leo** [comment]
Well it's fixed now (at least on nightly)

**Comment by samsepiol59** [comment]
Stupid question, I installed everything with atomic toolkit and set the develop branch for updates... How can I update to the latest nightly without being able to enter the gui?!

PS hope I'm not testing your patiences too much!
