### ISSUE TITLE
Auto problem

### ISSUE THREAD

**Issue by pikachukaki** [Radarr/Radarr#2586]
While the nzb daemon is running my settings are correct my client is open no movies are being downloaded. i have to manually enter the interface and press "search all" to start searching and then downloading files. is there an option while in the background when the daemon will search for releases?

**Comment by galli-leo** [comment]
See https://github.com/Radarr/Radarr/wiki/Common-Problems#movie-added-but-not-searched

Use add and search for adding older movies.

**Comment by pikachukaki** [comment]
I have all my movies on search maybe my problem was i have them on availability at physical release not sure yet!
