### ISSUE TITLE
Tag for movies still in Cinema or not yet released

### ISSUE THREAD

**Issue by daanvb** [Radarr/Radarr#259]
Would it be possible to add the tag "In cinemas" and/or "Not Yet Released" to the movie list for unreleased movies instead of missing. When I keep scrolling throuygh my list to find films I am missing I keep stopping at films still in the cinema.

**Comment by onedr0p** [comment]
The icon on the left represents that., we should remove the paused icon to be in threatres thou

**Comment by onedr0p** [comment]
![image](https://cloud.githubusercontent.com/assets/213795/21957355/6fbc8e70-da62-11e6-8179-a6fe6d0bfe88.png)

**Comment by daanvb** [comment]
That's cool, never noticed that. Is it possible to also do the same for the text on the right as well?

**Comment by onedr0p** [comment]
I think the status column should only say if it's missing or downloaded.

**Comment by galli-leo** [comment]
Also missing but not yet released is shown in blue.
