### ISSUE TITLE
Import Failure Path does not exist (Its pucking up a wrong path)

### ISSUE THREAD

**Issue by behold81** [Radarr/Radarr#2592]
I have an issue where movies are not being imported. the path is c:\xxxxx\complete\mov\name\file

but radarr is trying to import C:\xxxxx\complete\mov\file

This fails the import and I can't identify any flaws in how its setup. Either I am missing something obvious or this is a bug. 

Help

**Comment by fryfrog** [comment]
Radarr gets the path from your downloader, so your downloader is reporting it wrong. What downloader are you using?

**Comment by behold81** [comment]
Nzbget. I use videosort as a post process as I had issues with file/Path length. 

But before processing the file is in a folder. So still don’t get why it’s missing on pass through.

**Comment by behold81** [comment]
I am. Only not removing on completed.

**Comment by fryfrog** [comment]
Can you disable videosort and see if it helps? What do you mean you have path too long issues? Can you reduce your path some to help w/ that?

**Comment by behold81** [comment]
I can try that to see. 

Reason I added it is nothing would import due to file/Path being to long. It’s in a short Path at the moment but some file names are huge now days and also full of special characters. 

I’ll disable it and retry.
