### ISSUE TITLE
Downloading Propers

### ISSUE THREAD

**Issue by Bannister3000** [Radarr/Radarr#2593]
Version 0.2.0.910

Hi guys, 

I've had a look through pass comments and seen a few things but nothing seemed to scream at me for an answer so - I am wondering if someone can help here.  I've noticed a slight change lately in how Radarr is managing my content.  I'm not sure why.  It is scanning like I'd expect - but is seems to think some files are missing and/or downloading proper's despite being set to disabled and moving the originals to the bin.

I've left some details below, but it seems to be generally the same quality file, in same cases a different format, was x265 replaced with x264 - But all the libary is set the same and it's on;y now and then, and I'm not sure why.  I thought with Proper's set to no it would not check these and only look for the "Missing, Monitored and considered Available" items and check to see if "Missing, Monitored, but not yet considered Available" has changed/updated for any reason.

Any pointers here would be welcomed!

Ignore Deleted Movies Yes
Download Propers No
Analyse video files Yes

Monitored Yes
Enable RSS Sync Yes
Enable Search Yes
RSS Sync Interval 720

**Comment by fryfrog** [comment]
Propers only applies for a few days and only for things named Propers, this probably isn't your problem.

**Comment by fryfrog** [comment]
But myself and others have seen weird behavior where movies will download, but Radarr won't know they downloaded and gets another one. And another one.

Start by updating to the latest version at least, there were some fixes for issues like this.

**Comment by Bannister3000** [comment]
Hi Fry,  

Thanks for taking the time to reply.  It's much appreciated!  

I've been checking the updates tab and assumed this also was working - and again just checked and no updates!  I'll go now - and manually update to the new version!

Thanks for the advice.  I wasn't too sure about changing from monitored and unmonitored ect.   Let's see what the update does!

**Comment by galli-leo** [comment]
What is your quality profile like? What are the qualities of the downloaded movies like?

**Comment by Bannister3000** [comment]
Its comparing the quality to the profile and meeting the requirements, 1080p for example.  But it's a like for like, and in some cases its the same file that I re-encoded from x264 to x265 anyway! So in another it's making it worse as its adding a bigger file when not required!!

**Comment by galli-leo** [comment]
What exact quality profile are you using? What is the exact quality that Radarr has detected your existing files as and what is the exact quality of the new files downloaded?

**Comment by fryfrog** [comment]
Give us a screen shot of the quality profile assigned to the movie and of the history of that movie. Maybe also a screen shot of the movie showing the profile it is using.

**Comment by fryfrog** [comment]
Radarr can *only* compare the quality it *knows* and it gets *that* from the file it downloaded. If it downloaded a web-dl and you converted it, then a bluray came out... it'd over write it. Or if you download a bluray and convert it and somehow cause Radarr to not know what quality it is, it'll default to HDTV 720p (because Radarr doesn't look at resolution from file) and *that* would cause it to get replaced too.

Make *sure* you store Quality and resolution in the filename.

**Comment by Bannister3000** [comment]
Hi Guys,

So to answer your points, and thanks for checking....

Pick something at random - Airplane! (1980) - x265 1080p

It'll check this, and then delete to download the same/original file Airplane! (1980) - x265 1080p - or in some cases where it's been changed from x264 to x264 it'll download the original file that was in x264 so I end up with Airplane! (1980) - x264 1080p

Yep I get the need for the details to be in the file name, everything should be as - Airplane! (1980) - x265 1080p

Using a custom profile in this case. 
![screenshot-2018-3-18 settings - radarr](https://user-images.githubusercontent.com/35036019/37565232-34737694-2a9d-11e8-94da-38e822943bbf.png)

Sorry for the delay, but the continued input and help is welcomed.  Interesting and fantastic system this and it's helped me no end to clean up, organize everything.  10/10

**Comment by galli-leo** [comment]
Can you tell us what Radarr recognized the original file as? Because I am pretty sure it recognized it as HDTV (since you only have 1080p in the filename) and then upgraded it to a "better" Bluray rip when it found one.

**Comment by Bannister3000** [comment]
Radarr seems to be only finding and changing certain ones at random.  The file name contains the resolution as you'd expect.  The new file - the only difference has been the codec - it's replaced a x265 with a x264 - same resolution - and nothing has changed otherwise.
