### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by jimmyok** [Radarr/Radarr#2595]
Add the ability to remove multiple movies quickly via a checklist.

Today my radarr added about 100 movies to download due to a list i had added, removing them is a major pain. It would be a lot better if you could select all and delete.

**Comment by tusharbhutt** [comment]
You should be able to under the movie editor in some of the newer builds.

**Comment by fryfrog** [comment]
Yeah, Movie Editor has check boxes and a delete button. I *think* this is new-ish, as of a few versions?
