### ISSUE TITLE
Unable to update to: 0.2.0.980

### ISSUE THREAD

**Issue by mrchops1024** [Radarr/Radarr#2596]
**Description:**
I attempted to udpate both Sonarr and Radarr (running on Ubuntu 14.04.5 LTS) a couple days ago and noticed that Radarr failed. Did some research and it looked related to the TLS changes in GitHub. Updated to the latest version of mono and then had an issue starting up. Copied over an updated NLog.dll which allowed it to startup fine. Now when I try to update I don't receive any errors, it just doesn't update. I enabled trace logging and I'm not seeing any errors or anything that indicates a failure.

**Radarr Version:**
0.2.0.910

**Mono Version:**
5.10.0.140

**Debug Logs:**

`18-3-2 10:28:32.9|Trace|Http|Req: 547 [POST] /api/command
18-3-2 10:28:32.9|Trace|CommandQueueManager|Publishing ApplicationUpdate
18-3-2 10:28:32.9|Trace|CommandQueueManager|Checking if command is queued or started: ApplicationUpdate
18-3-2 10:28:32.9|Trace|CommandQueueManager|Inserting new command: ApplicationUpdate
18-3-2 10:28:32.9|Trace|CommandExecutor|ApplicationUpdateCommand -> InstallUpdateService
18-3-2 10:28:32.9|Trace|Http|Res: 547 [POST] /api/command: 201.Created (77 ms)
18-3-2 10:28:32.9|Trace|CommandQueueManager|Marking command as started: ApplicationUpdate
18-3-2 10:28:32.9|Debug|Api|[POST] /api/command: 201.Created (77 ms)
18-3-2 10:28:33.0|Trace|EventAggregator|Publishing CommandUpdatedEvent
18-3-2 10:28:33.0|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
18-3-2 10:28:33.0|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
18-3-2 10:28:33.0|Debug|InstallUpdateService|Checking for updates
18-3-2 10:28:33.0|Trace|EventAggregator|Publishing CommandUpdatedEvent
18-3-2 10:28:33.0|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
18-3-2 10:28:33.0|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
18-3-2 10:28:33.0|Trace|HttpClient|Req: [GET] http://radarr.aeonlucid.com/v1/update/develop?version=0.2.0.910&os=linux
18-3-2 10:28:33.0|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
18-3-2 10:28:33.1|Trace|HttpClient|Res: [GET] http://radarr.aeonlucid.com/v1/update/develop?version=0.2.0.910&os=linux: 200.OK (159 ms)
18-3-2 10:28:33.1|Info|InstallUpdateService|Deleting old update files
18-3-2 10:28:33.2|Info|InstallUpdateService|Downloading update 0.2.0.980
18-3-2 10:28:33.2|Trace|EventAggregator|Publishing CommandUpdatedEvent
18-3-2 10:28:33.2|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
18-3-2 10:28:33.2|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
18-3-2 10:28:33.2|Debug|InstallUpdateService|Downloading update package from [https://github.com/Radarr/Radarr/releases/download/v0.2.0.980/Radarr.develop.0.2.0.980.linux.tar.gz] to [/tmp/radarr_update/Radarr.develop.0.2.0.980.linux.tar.gz]
18-3-2 10:28:33.2|Debug|HttpClient|Downloading [https://github.com/Radarr/Radarr/releases/download/v0.2.0.980/Radarr.develop.0.2.0.980.linux.tar.gz] to [/tmp/radarr_update/Radarr.develop.0.2.0.980.linux.tar.gz]
18-3-2 10:28:34.1|Debug|HttpClient|Downloading Completed. took 0s
18-3-2 10:28:34.1|Info|InstallUpdateService|Verifying update package
18-3-2 10:28:34.1|Trace|EventAggregator|Publishing CommandUpdatedEvent
18-3-2 10:28:34.1|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
18-3-2 10:28:34.1|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
18-3-2 10:28:34.3|Info|InstallUpdateService|Update package verified successfully
18-3-2 10:28:34.3|Info|InstallUpdateService|Extracting Update package
18-3-2 10:28:34.3|Trace|EventAggregator|Publishing CommandUpdatedEvent
18-3-2 10:28:34.3|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
18-3-2 10:28:34.3|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
18-3-2 10:28:34.3|Debug|ArchiveService|Extracting archive [/tmp/radarr_update/Radarr.develop.0.2.0.980.linux.tar.gz] to [/tmp/radarr_update/]
18-3-2 10:28:34.7|Debug|ArchiveService|Extraction complete.
18-3-2 10:28:34.7|Info|InstallUpdateService|Update package extracted successfully
18-3-2 10:28:34.7|Info|BackupService|Starting Backup
18-3-2 10:28:34.7|Trace|EventAggregator|Publishing CommandUpdatedEvent
18-3-2 10:28:34.7|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
18-3-2 10:28:34.7|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
18-3-2 10:28:34.7|Trace|DiskProviderBase|Deleting file: /tmp/radarr_backup/config.xml
18-3-2 10:28:34.7|Trace|DiskProviderBase|Deleting file: /tmp/radarr_backup/nzbdrone.db
18-3-2 10:28:34.7|Debug|BackupService|Cleaning up old backup files
18-3-2 10:28:34.7|Debug|BackupService|Finished cleaning up old backup files
18-3-2 10:28:34.7|Debug|BackupService|Backing up config.xml
18-3-2 10:28:34.7|Trace|EventAggregator|Publishing CommandUpdatedEvent
18-3-2 10:28:34.7|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
18-3-2 10:28:34.7|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
18-3-2 10:28:34.7|Debug|DiskTransferService|Copy [/home/plex/.config/Radarr/config.xml] > [/tmp/radarr_backup/config.xml]
18-3-2 10:28:34.7|Trace|DiskProvider|Checking path /tmp/radarr_backup/config.xml for symlink returned error ENOENT, assuming it's not a symlink.
18-3-2 10:28:34.7|Debug|BackupService|Backing up database
18-3-2 10:28:34.7|Trace|EventAggregator|Publishing CommandUpdatedEvent
18-3-2 10:28:34.7|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
18-3-2 10:28:34.7|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
18-3-2 10:28:34.7|Debug|DiskTransferService|Copy [/home/plex/.config/Radarr/nzbdrone.db] > [/tmp/radarr_backup/nzbdrone.db]
18-3-2 10:28:34.7|Trace|DiskProvider|Checking path /tmp/radarr_backup/nzbdrone.db for symlink returned error ENOENT, assuming it's not a symlink.
18-3-2 10:28:34.7|Debug|BackupService|Creating backup zip
18-3-2 10:28:34.7|Trace|EventAggregator|Publishing CommandUpdatedEvent
18-3-2 10:28:34.7|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
18-3-2 10:28:34.7|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
18-3-2 10:28:35.2|Trace|Http|Req: 548 [GET] /logfile/radarr.trace.txt
18-3-2 10:28:35.2|Trace|Http|Res: 548 [GET] /logfile/radarr.trace.txt: 200.OK (1 ms)
18-3-2 10:28:35.2|Debug|BackupService|Backup zip created
18-3-2 10:28:35.2|Trace|EventAggregator|Publishing CommandUpdatedEvent
18-3-2 10:28:35.2|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
18-3-2 10:28:35.2|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
18-3-2 10:28:35.2|Info|InstallUpdateService|Preparing client
18-3-2 10:28:35.2|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/CurlSharp.dll] > [/tmp/radarr_update/CurlSharp.dll]
18-3-2 10:28:35.2|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/CurlSharp.dll.mdb] > [/tmp/radarr_update/CurlSharp.dll.mdb]
18-3-2 10:28:35.2|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/ICSharpCode.SharpZipLib.dll] > [/tmp/radarr_update/ICSharpCode.SharpZipLib.dll]
18-3-2 10:28:35.2|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/LogentriesCore.dll] > [/tmp/radarr_update/LogentriesCore.dll]
18-3-2 10:28:35.2|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/LogentriesCore.dll.mdb] > [/tmp/radarr_update/LogentriesCore.dll.mdb]
18-3-2 10:28:35.2|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/LogentriesNLog.dll] > [/tmp/radarr_update/LogentriesNLog.dll]
18-3-2 10:28:35.2|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/LogentriesNLog.dll.mdb] > [/tmp/radarr_update/LogentriesNLog.dll.mdb]
18-3-2 10:28:35.2|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/NLog.dll] > [/tmp/radarr_update/NLog.dll]
18-3-2 10:28:35.2|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/Newtonsoft.Json.dll] > [/tmp/radarr_update/Newtonsoft.Json.dll]
18-3-2 10:28:35.2|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/NzbDrone.Common.dll] > [/tmp/radarr_update/NzbDrone.Common.dll]
18-3-2 10:28:35.2|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/NzbDrone.Common.dll.mdb] > [/tmp/radarr_update/NzbDrone.Common.dll.mdb]
18-3-2 10:28:35.2|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/NzbDrone.Mono.dll] > [/tmp/radarr_update/NzbDrone.Mono.dll]
18-3-2 10:28:35.2|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/NzbDrone.Mono.dll.mdb] > [/tmp/radarr_update/NzbDrone.Mono.dll.mdb]
18-3-2 10:28:35.2|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/Org.Mentalis.dll] > [/tmp/radarr_update/Org.Mentalis.dll]
18-3-2 10:28:35.2|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/Radarr.Update.exe] > [/tmp/radarr_update/Radarr.Update.exe]
18-3-2 10:28:35.2|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/Radarr.Update.exe.config] > [/tmp/radarr_update/Radarr.Update.exe.config]
18-3-2 10:28:35.2|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/Radarr.Update.exe.mdb] > [/tmp/radarr_update/Radarr.Update.exe.mdb]
18-3-2 10:28:35.2|Debug|DiskTransferService|Move [/tmp/radarr_update/Radarr/NzbDrone.Update/SocksWebProxy.dll] > [/tmp/radarr_update/SocksWebProxy.dll]
18-3-2 10:28:35.2|Info|InstallUpdateService|Starting update client /tmp/radarr_update/Radarr.Update.exe
18-3-2 10:28:35.2|Info|InstallUpdateService|Radarr will restart shortly.
18-3-2 10:28:35.2|Trace|EventAggregator|Publishing CommandUpdatedEvent
18-3-2 10:28:35.2|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
18-3-2 10:28:35.2|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
18-3-2 10:28:35.2|Info|InstallUpdateService|Updater Arguments: 5323 /tmp/radarr_update /opt/Radarr/Radarr.exe 
18-3-2 10:28:35.2|Debug|mono|Starting mono --debug /tmp/radarr_update/Radarr.Update.exe 5323 /tmp/radarr_update /opt/Radarr/Radarr.exe 
18-3-2 10:28:35.2|Trace|CommandQueueManager|Updating command status
18-3-2 10:28:35.3|Trace|EventAggregator|Publishing CommandUpdatedEvent
18-3-2 10:28:35.3|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
18-3-2 10:28:35.3|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
18-3-2 10:28:35.3|Trace|EventAggregator|Publishing CommandExecutedEvent
18-3-2 10:28:35.3|Trace|EventAggregator|CommandExecutedEvent -> TaskManager
18-3-2 10:28:35.3|Trace|TaskManager|Updating last run time for: NzbDrone.Core.Update.Commands.ApplicationUpdateCommand
18-3-2 10:28:35.3|Trace|EventAggregator|CommandExecutedEvent <- TaskManager
18-3-2 10:28:35.3|Trace|EventAggregator|CommandExecutedEvent -> TaskModule
18-3-2 10:28:35.3|Trace|EventAggregator|CommandExecutedEvent <- TaskModule
18-3-2 10:28:35.3|Trace|CommandExecutor|ApplicationUpdateCommand <- InstallUpdateService [00:00:02.2842740]
18-3-2 10:28:38.2|Trace|Http|Req: 549 [GET] /logfile/radarr.trace.txt
18-3-2 10:28:38.2|Trace|Http|Res: 549 [GET] /logfile/radarr.trace.txt: 200.OK (4 ms)`

**Comment by coreflake1** [comment]
I have the same issue. Same situation. 
Logs say : Updater Arguments: 7899 /tmp/radarr_update /opt/Radarr/Radarr.exe /nobrowser

**Comment by daniel-loader** [comment]
Has Radarr received the patch sonarr put out to make it work with mono 5.10?

**Comment by betterbuckleup** [comment]
@daniel-loader having the same issue with not being able to update Radarr to the version compatible with mono v5.10.0.140

**Comment by daniel-loader** [comment]
Guess we'll need to wait till it's a release tarball to overwrite.

**Comment by RonnieBlaze** [comment]
Same issue here, radarr seems to be running but then stops, updated to mono 5.10.0.140

**Comment by jtrosper** [comment]
Here's what I did to fix it.  I don't know much about the root cause, so this is definitely workaround territory.

When I ran Radarr directly via "mono Radarr.exe", I got this console output:

```
XXX@XXX:/opt/Radarr$ mono Radarr.exe
[Info] Bootstrap: Starting Radarr - /opt/Radarr/Radarr.exe - Version 0.2.0.980
[Info] Router: Application mode: Interactive
[Info] MigrationLogger: *** Migrating data source=/home/XXX/.config/Radarr/nzbdrone.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
[Info] MigrationLogger: *** Migrating data source=/home/XXX/.config/Radarr/logs.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
[Info] OwinHostController: Listening on the following URLs:
[Info] OwinHostController:   http://0.0.0.0:7878/
[Info] OwinHostController:   http://localhost:7878/
[Info] NancyBootstrapper: Starting NzbDrone API


[Fatal] ConsoleApp: Address already in use. This can happen if another instance of Radarr is already running another application is using the same port (default: 7878) or the user has insufficient permissions
Press enter to exit...
```

I edited ~/.config/Radarr/config.xml from:

`<BindAddress>0.0.0.0</BindAddress>`

to 

`<BindAddress>1.2.3.4</BindAddress>`

Where 1.2.3.4 = the IP address of the machine.

This allowed Radarr to start successfully.  However, this is unexpected behavior.  Radarr should be able to bind to all interfaces when instructed to do so.  It's worth noting also, that the 0.0.0.0 configuration worked fine until the mono 5.10 update.

Hope this helps.

**Comment by jtrosper** [comment]
An additional update.  I compared config.xml against Sonarr, and found that Sonarr was bound using an asterisk * to bind to all interfaces.  I edited Radarr's config.xml to reflect this, and it was able to successfully start then.

**Comment by RonnieBlaze** [comment]
I followed the instructions on this reddit page i found, it worked for my except that i cannot update to 0.2.0.980, so i manually updated by downloading the zip file and extracted it to my /opt/Radarr folder, and i had to put the updated NLog.dll back in.

**Comment by betterbuckleup** [comment]
@jtrosper I just compared the config.xml file for both Sonarr and Radarr and they both have the bonded asterisk *
Although I noticed that launch browser was set to True for Radarr. This value in the sonarr config file is set to False. I changed it to match the Sonarr config, but to no avail

**Comment by mrchops1024** [comment]
@jtrosper It sounds like maybe your issue was slightly different. Radarr runs just fine for me. The only issue is that the update appears to fail without any indication as to why.

@RonnieBlaze I may resort to a manual upgrade if nobody can figure out why it won’t update from the UI.

**Comment by RonnieBlaze** [comment]
@mrchops1024  Mine would not update from the UI either, i was on the 0.2.0.935 build, once i got it back up and running from the mono update with the new NLog.dll, i tried to update via the UI and it did nothing.. that why i did the manual update.. ill have to wait to see if it update when a new one comes out

**Comment by emcniece** [comment]
Reporting in from an auto-updating Docker container - the newest tag (`linuxserver/radarr:92`, Radarr v0.2.0.980) gets stuck in a startup loop printing something like "Press enter to exit...". Reverting to `linuxserver/radarr:91` works fine.

**Comment by galli-leo** [comment]
For the op: downgrade mono to 5.8 since the updater also uses nlog it won’t work :/

**Comment by Sportsmaniac13** [comment]
@emcniece Thanks for that tip, worked perfectly.  Though I'm sure the Linuxserver team will have an update out in no time.

**Comment by darrenclimienewman** [comment]
Any idea where i can get the 5.8 for QNAP? I've searched and can't find the QPKG.

Thanks

**Comment by init-penguin** [comment]
I cannot update to 0.2.0.995 from the UI, too:
Radarr v0.2.0.45
Mono v4.2.3
It fails on `HttpClient: Failed to get response from: https://github.com/Radarr/Radarr/releases/download/v0.2.0.995/Radarr.develop.0.2.0.995.linux.tar.gz Error: SendFailure (Error writing headers)`

**Comment by galli-leo** [comment]
@init-penguin Read my comment

**Comment by init-penguin** [comment]
@galli-leo thanks, it worked quite well.
