### ISSUE TITLE
[UI] "Update" and "Edit" buttons unusable

### ISSUE THREAD

**Issue by djoole** [Radarr/Radarr#2599]
**Description:**

Problem appeared on version 0.2.0.980, in poster view.

Before, when hovering on a poster, buttons "update" and "edit" were appearing and one could click on it.

Now, the buttons are displayed on top of the poster, and when hovering they disappear.
https://i.imgur.com/C3hnRkz.png

**Radarr Version:** 0.2.0.980

**Mono Version:** 5.2.0.215

**Debug Logs:** on demand

**Comment by galli-leo** [comment]
Duplicate issue, fixed on nightly
