### ISSUE TITLE
Password protected archives in usenet?

### ISSUE THREAD

**Issue by kaysond** [Radarr/Radarr#2601]
Does radarr have any support for password protected archives in usenet downloads? It looks like newznab supports a password attribute, but only to indicate that a password exists not what it is. Does radarr just ignore these? Or is there a way to send the password to the nzb client

**Comment by fryfrog** [comment]
Your nzb downloader should be able to maintain a list of passwords, but I don't know of anything that'll automate the getting of passwords and sending them to downloader. If Radarr can tell it is password protected, it'll probably ignore it. But most aren't indicated and you'll need to do something in your downloader to punt or try them. Probably punt.
