### ISSUE TITLE
1992 movies in directories but only 1222 records after import to radarr

### ISSUE THREAD

**Issue by MattTwinkleToes** [Radarr/Radarr#2607]
I posted this over on reddit but the more i think about it, the more i think that it could be a bug so i´m logging it here too.

Radarr only detects 1222 movies when there are ~1992 movies available in the two directories that my library is in. I know that there are this many movies because plex see´s them all.

Radarr s running as a normal user but the directories in question have 777 permissions so I don´t think that it a permissions problem, if it is, I don´t know what I can do since they already have 777.

The library directories are mounted as an NFS share from a synology NFS server on a Linux Mint 18.3 client.

eg:

nas03:/volume1/store /home/matt/mnt/nas03 nfs _netdev,auto,user, 0 0

The permissions are like this (due to some synology problem with using NFSv4, more secure permissions are not currently working)

drwxrwxrwx 622 1024 users 69632 Mar 5 12:14 movies

and

drwxrwxrwx 1 matt matt 95180 Mar 5 11:16 movies

That plex can see them all tells me that it is most likely not a problem with the file server. Sonarr also uses the same server and has no trouble seeing the files there.

Any idea what the problem might be?

I am running Version 0.2.0.995 Mono Version 5.10.0.140 (tarball Sat Feb 24 15:33:47 UTC 2018)

**Comment by galli-leo** [comment]
What are movie dirs and files named like? Especially the ones you are missing?

**Comment by MattTwinkleToes** [comment]
I have not yet worked out a practical way of building a list of what Radarr can see vs what it can not, I just see that the number of total records in the movie section on the UI says 1222.

Have you a way for me to get a list in a text file or csv of ever movie in my library from radarr´s database?  I can then do a diff on it easily enough.

I am a little overwhelmed by activity at the moment, It is upgrading the quality of a lot of movies (hundreds) and I fear that it is downloading things that I already have at a lesser quality.  Not to mention that it is creating hundreds of duplicates but i am removing those one by one.

But, almost all of it was named by couch potato a while ago with this

Folder
<namethe>.(<year>)

File
<thename><cd>.<ext>

Radarr
{Movie.Title}.({Release Year}).{Quality Full}
{Movie.Title} ({Release Year})

Radarr is doing something different so forgive the escape characters :)

Examples
Dark\ City.\(1998\Dark City.mkv

The\ Death\ of\ Stalin\ \(2017\)/The.Death.of.Stalin.(2017).Bluray-1080p.mkv

Inferno.\(2016\)/Inferno.(2016).720p.mkv

**Comment by MattTwinkleToes** [comment]
I´m just looking in the database now and will compare it against my plexpy database and post back

**Comment by galli-leo** [comment]
> I´m just looking in the database now and will compare it against my plexpy database and post back

Would have suggested the same.

> Folder
> .()
> 
> File
> .

Not sure what happened here, how did CP rename the movies?

Also you might want to look out for the year missing in the file & folder name.

**Comment by MattTwinkleToes** [comment]
Unfortunately the plex database has a different naming convention to the radarr db so a diff is not really producing anything useful.

I think git thought I was talking to it when I pasted the CP naming convention, it interprets the tags every time i type it in.

folders
`<namethe>.(<year>)`

files
`<thename><cd>.<ext>`

**Comment by MattTwinkleToes** [comment]
I took a list of titles from the plex _metadata_items_ table and compared it with the nzbdrone.db _Movies_ table and did a visual comparison to try to identify some missing titles.

Sure enough, there are many missing titles.

For example, plex has Personal Shopper while Radarr does not.

I then went to the Radarr UI to search for Personal Shopper to see if there was a result and it was there, showing up with no problems.

I then thought, perhaps the database has been updated since I took a copy of it but the number in Movies > Total records remains unchanged at 1222.

I am thoroughly confused after several hours of this and don´t trust any of the the data that I have about any of my media assets.

**Comment by MattTwinkleToes** [comment]
OK i eventually found one example.  This exists in plex but not in radarr.

(500) Days of Summer.(2009)/ (500) Days of Summer.(2009).720p.mkv

**Comment by galli-leo** [comment]
Just to be clear: If you search for them they don't exist at all, or they just show up as missing?

If the former is the case, try doing a bulk import again, maybe tmdb was having issues at the time.

**Comment by MattTwinkleToes** [comment]
Yeah they don't show up at all.

I'll try another import

**Comment by MattTwinkleToes** [comment]
Leo while I have you here mate, Since i went live with Radarr today it was been busy downloading higher quality versions of everything.  The trouble is that it is not removing the lower quality files so I am ending up with lots of duplicates.  At the rate it is going at now, I am in danger of filling my NAS within the next couple of day´s until I can manually delete the dupes.

I cannot see a setting anywhere, am i missing something?

**Comment by galli-leo** [comment]
Do you have any errors showing in your logs? Not sure why it wouldn't overwrite them. Also does Radarr know about the existing files?

**Comment by MattTwinkleToes** [comment]
I have 57 pages of errors in my logs! :).  Lol.

I noticed that it is creating new directories for the duplicate files as the naming expression is different to my old cp convention but I thought that Radarr would still know where everything was?

The re-import seems to be working, new movies are being added but there are loads of errors and failures to import, it looks as though I have a bunch of 0 byte .mkv´s at looking at the first page of logs.

My system is at 100% CPU and has a big disk queue of jobs coming in waiting to be processed, i think it is best to leave it to run overnight and settle down and i´ll start picking through the logs later.

**Comment by galli-leo** [comment]
@MattTwinkleToes That shouldnt be a problem if you do a bulk import. Radarr should take over the old paths. Unless you messed with dynamic paths.
