### ISSUE TITLE
Radarr keeps grabbing a TV show called "Click.UK"

### ISSUE THREAD

**Issue by chuckkay** [Radarr/Radarr#2608]
This happened a few months ago many times, and now it's happening again.. probably a indexer sites mistake... 
BUT THE PROBLEM IS - there is no way for me to tell from the log file what movie it thinks it downloaded or which rss list it got it from...... 

I put the term 'Click' & 'Click.UK' in the Indexers Must Not Contain list... but strangely that did not stop the problem. 

See the  log below this is the most recent time it happened...  and if i delete the download from Sabnzbd it will download another version again later..... 

18-3-5 15:19:57.0|Info|RssSyncService|Starting RSS Sync
18-3-5 15:19:57.5|Warn|HttpClient|HTTP Error - Res: [GET] https://nzbfinder.ws/api?t=movie&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060&extended=1&apikey=(removed)&offset=0&limit=100: 429.429
<?xml version="1.0" encoding="UTF-8"?>
<error code="429" description="Request limit reached (26/25)"/>

18-3-5 15:19:57.5|Warn|Newznab|API Request Limit reached for NZBFinder
18-3-5 15:20:22.3|Info|DownloadDecisionMaker|Processing 597 releases
18-3-5 15:20:39.3|Info|RssSyncService|RSS Sync Completed. Reports found: 597, Reports grabbed: 0
18-3-5 15:50:28.1|Info|PreDBService|Starting PreDB Sync
18-3-5 16:20:59.1|Info|RssSyncService|Starting RSS Sync
18-3-5 16:21:31.5|Info|DownloadDecisionMaker|Processing 597 releases
18-3-5 16:21:45.7|Info|Sabnzbd|Adding report [Click.UK.03.03.2018.Web-DL.x264.AAC-TVC] to the queue.
18-3-5 16:21:45.8|Info|DownloadService|Report sent to Sabnzbd. Click.UK.03.03.2018.Web-DL.x264.AAC-TVC
18-3-5 16:21:45.8|Info|RssSyncService|RSS Sync Completed. Reports found: 597, Reports grabbed: 1
Radarr Ver. 0.2.0.997

**Comment by galli-leo** [comment]
I would suggest taking it up with your indexer. If it is telling us a wrong imdbid not much we can do. Try blacklisting this particular release.

**Comment by chuckkay** [comment]
please read whole post before closing.......

"THE PROBLEM IS - there is no way for me to tell from the log file what
movie it thinks it downloaded or which rss list it got it from...... "

**Comment by galli-leo** [comment]
You should be able to in the history tab.

**Comment by chuckkay** [comment]
you are correct, that was the first place i looked, it wasn't there... but know it is.... needed to hit refresh... thanks
