### ISSUE TITLE
https://api.radarr.video/v2 not working

### ISSUE THREAD

**Issue by Natteverf** [Radarr/Radarr#2611]
https://api.radarr.video/v2 is not working

![image](https://user-images.githubusercontent.com/25325710/37020480-2f0dea02-211c-11e8-939b-da712b31b8c9.png)

**Comment by galli-leo** [comment]
I know

**Comment by Natteverf** [comment]
Anything i can do to help?

**Comment by galli-leo** [comment]
Nah, currently moving webhosts, so gonna take some time.

**Comment by Natteverf** [comment]
Ok, np :-)

**Comment by romanoh** [comment]
It is not working for me: (thank you for your grest work)
https://i.imgur.com/ox1YJm9.png
