### ISSUE TITLE
Login prompt to authenticate with https://radarr.video

### ISSUE THREAD

**Issue by jimgrove1985** [Radarr/Radarr#2612]
I've just upgraded to version 0.2.0.995 (from version 0.2.0.980)
My Mono version is: 5.10.0.140

[radarr.txt](https://github.com/Radarr/Radarr/files/1785571/radarr.txt)

Since doing so, when accessing Radarr from a browser I have a window popping up asking me to log in / authenticate with https://radarr.video.

I can click cancel and then continue to use radarr without any problem, but it's definitely still a bug that was not present with the previous version.

For the record, I don't have any authentication settings enabled within my radarr settings

**Comment by galli-leo** [comment]
Duplicate issue

**Comment by jimgrove1985** [comment]
Sorry, I couldn't find another report of this issue.

Or is it related to this somehow? https://github.com/Radarr/Radarr/issues/2611

**Comment by galli-leo** [comment]
It is related. Try searching closed issues, I am on mobile so cannot link issues :/
