### ISSUE TITLE
Radarr does not download automatically.

### ISSUE THREAD

**Issue by Jamyz** [Radarr/Radarr#2615]
Hello, Radarr does not download automatically. By cons in manual mode I have the choice. How to put in auto mode.

Radarr Version: 0.2.0.995

Mono Version: 5.8.0.108 (tarball Sat Feb 24 09:55:00 UTC 2018)

Debug Logs:
DownloadDecisionMaker: Processing 3 releases
MovieSearchService: Movie search completed. 0 reports downloaded.

Thanks you !!

**Comment by galli-leo** [comment]
First of all, those are not debug logs.

Second of all, Radarr "only" looks out for new releases of a movie via RSS. So you have to add already released movies using add&search.

See https://github.com/Radarr/Radarr/wiki/Common-Problems#movie-added-but-not-searched

**Comment by Jamyz** [comment]
@galli-leo I try with add&search but doesn't work..
You want logs.....
`[Info] MovieService: Adding Movie [][The Disaster Artist (2017)] Path: [/volume1/Movies/The Disaster Artist (2017)]
[Info] MediaCoverService: Downloading Poster for [][The Disaster Artist (2017)] http://image.tmdb.org/t/p/original/jj84nF5vYRD0HUTowBKcrKk8hZP.jpg
[Info] RefreshMovieService: Updating Info for The Disaster Artist
[Info] MetadataService: Movie folder does not exist, skipping metadata creation
[Info] DiskScanService: Scanning disk for The Disaster Artist
[Warn] MediaCoverMapper: File /volume1/@appstore/radarr/var/.config/Radarr/MediaCover/11/banner.jpg not found
[Info] MovieScannedHandler: [The Disaster Artist] was recently added, performing post-add actions
[Info] NzbSearchService: Searching 1 indexers for [The Disaster Artist]
[Info] MediaCoverService: Downloading Poster for [tt3521126][The Disaster Artist (2017)] http://image.tmdb.org/t/p/original/pUAiTAtUQliI6ofT0uidgtBISXv.jpg
[Info] MediaCoverService: Downloading Banner for [tt3521126][The Disaster Artist (2017)] http://image.tmdb.org/t/p/original/bAI7aPHQcvSZXvt7L11kMJdS0Gm.jpg
[Info] DownloadDecisionMaker: Processing 2 releases
[Info] MovieSearchService: Movie search completed. 0 reports downloaded.
`

**Comment by galli-leo** [comment]
Dows manual mode have any errors on the right side?

**Comment by Jamyz** [comment]
No error that's work very fine its only add&search......
I dont understand why with add&search with "any" quality don't snatch and with manual it's good...

**Comment by galli-leo** [comment]
Can you post a screenshot of your manual search?

**Comment by Jamyz** [comment]
ADD & SEARCH
![sans titre-1](https://user-images.githubusercontent.com/6177824/37198137-93558e44-237d-11e8-8365-9c149403af1d.jpg)
![sans titre-2](https://user-images.githubusercontent.com/6177824/37198138-939130c0-237d-11e8-97cb-6089e7ba540c.jpg)

MANUAL
![sans titre-3](https://user-images.githubusercontent.com/6177824/37198183-bef52492-237d-11e8-90f0-942fd0ece7e8.jpg)
![sans titre-4](https://user-images.githubusercontent.com/6177824/37198188-c12b06f0-237d-11e8-8c33-bfb7e1a9c041.jpg)

**Comment by galli-leo** [comment]
Well you do have errors for the manual search. Hover over the red exclamation mark to find out why Radarr didn’t grab that release manually

**Comment by Jamyz** [comment]
I don't have error for manual search (half error). In my indexer i remove search by year because somes movies have an **incorrect year of the movie in the indexer** . The red exclamation is "Failed to map movie, expected year 2017, but found 2018". It's why i remove in the indexer "search by year".
Maybe is the fail of auto & add. I think, maybe the team of the Radarr Project can insert in indexer a feature like "Search betwen years" - Min year and Max year. What do you think ?

**Comment by galli-leo** [comment]
You do have a rejection for that release. If a release has a rejection, Radarr won't auto download it. Hence you have to hover over the release and find out why it is not downloaded.

The remove year from search only affects what we send to the indexer. Not how we map movies afterwards. You have force downloading for that. Min year max year, is imo not a good solution, as you will find much more erroneous downloads. And you will only find a few releases with the wrong year.
