### ISSUE TITLE
Required Flags tagging

### ISSUE THREAD

**Issue by Azno** [Radarr/Radarr#2619]
**Radarr Version:**
0.2.0.995 - Mar 4 2018  develop

I couldn't find anything on this so hopefully, I've not missed it...
When trying to add a Required Flag to a custom Torznab indexer it doesn't save and it looks like it glitches out. I'm assuming its supposed to do the same as when you add it to individual movies.

As a workaround, I've added another indexer and added a tag to all torrents added but the indexer I actually want to mainly use doesn't include there "brand" name within their torrents, so these always get ignored.

Thanks. 

![image](https://user-images.githubusercontent.com/6459559/37128630-ef237bca-2272-11e8-853f-62063be366db.png)
![image](https://user-images.githubusercontent.com/6459559/37128656-0baef9ea-2273-11e8-858a-03e42bcf7293.png)

**Comment by galli-leo** [comment]
This is not what that field is for. In the Required Flags field you add what Indexer Flags (e.g. Freeleech) are required for that indexer. If you want to apply restrictions you need to add that tag to the movie (or just don’t use a tag at all)
