### ISSUE TITLE
Copy and paste into add movie field does not work

### ISSUE THREAD

**Issue by turkeyphant** [Radarr/Radarr#2621]
**Description:**
When copying and pasting into add movie field, search is not initiated until extra keypresses are added.

**Steps to reproduce**

- Visit http://server-ip:7878/addmovies
- Copy and paste a movie name or fragment of into the add movies field. Nothing happens.
- Typing any other character that matches a movie title or deleting the last character for example triggers the search.
- It appears pasting text into the field doesn't trigger a search, instead you have to add additional keypresses every single time.

**Radarr Version:**
Version 0.2.0.870 (But issue has existed for all versions I've used)

**Mono Version:**
4.8.1 (Stable 4.8.1.0/22a39d7 jeudi 27 avril 2017, 14:32:02 (UTC+0200))

**Debug Logs:**
n/a

**Comment by galli-leo** [comment]
Fixed in latest nightly
