### ISSUE TITLE
movies being saved to /opt/Radarr and /home/user erroneously 

### ISSUE THREAD

**Issue by MattTwinkleToes** [Radarr/Radarr#2624]
**Description:**
During a bulk movie download (it started downloading a couple of hundred movies, upgrading, finding new ones etc..) I noticed that my /home was full.  

The paths that I use are NFS mounts to some NAS´s.

Since these movies were mostly imported form a CP library, I have not made any manual inputs to the root path for these movies, I have never told it to use /opt/Radarr or /home/user.

I am manually moving things around now but if ever I have found a bug then this seems to be it.
I have attached the debug logs and a screen shot of the UI for clarification.

To be clear, I have never configured either /opt or /home/matt as root folders before, the only valid paths as far as I am aware should be /home/matt/nas02/video/movies and /home/matt/mnt/nas03/video/movies.

Movies that are affected are:

Baby Driver
Annihilation
The Beguiled went to /opt/Radarr
Black Panther went to /home/matt
Dunkirk (2017) went to /home/matt
Every.Day (2018) went to /home/matt
Game Night (2018) went to /home/matt
etc..

And as I am writing this and working through the problem I have realised that  can sort by path column in the UI...doh!

/opt/Radarr/Transformers The Last Knight (2017)
/opt/Radarr/Rough Night (2017)
/home/matt/War for the Planet of the Apes (2017)
/home/matt/Valerian and the City of a Thousand Planets (2017)
/home/matt/Spider-Man Homecoming (2017)

Some of these movies are not available yet and are just placeholders (empty folders - even though I have create empty dirs disabled)

Version
0.2.0.995
Mono Version
5.10.0.160 (tarball Wed Mar 7 15:25:20 UTC 2018)

[radarr.debug.txt](https://github.com/Radarr/Radarr/files/1799552/radarr.debug.txt)
[radarr.debug.0.txt](https://github.com/Radarr/Radarr/files/1799553/radarr.debug.0.txt)
![screenshot from 2018-03-10 17-11-55](https://user-images.githubusercontent.com/21276950/37244259-6766d90a-2486-11e8-8ad8-83daa9e6a403.png)

**Comment by galli-leo** [comment]
Are you using firefox and are you also using lists?

**Comment by MattTwinkleToes** [comment]
I use chrome and yes I have an imdb list and also the Steven LU list had somehow become enabled (not by me) and i only noticed when i investigated why my server was full of terrible movies.

I have disabled the SteveLu list because it is terrible but the imdb list is still enabled.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by galli-leo** [comment]
You need to correct the path for the list in your list setting. There is a bug in some browsers that sometimes, the path dropdown in lists can be empty. Resulting in an empty root path (hence Radarr just importing it into home / install location).

**Comment by MattTwinkleToes** [comment]
it is set correctly, hundreds of movies were handled correctly yesterday with just the ones i mentioned being handled incorrectly.

I have fixed this manually this time, I am not asking for your help, i just thought that you might want to know that there is something weird happening.
