### ISSUE TITLE
German Umlaut Movie Name when moved and renamed

### ISSUE THREAD

**Issue by fuuss** [Radarr/Radarr#2628]
Movies with Umlauts when moved and renamed get some weird Names

Exemple 
DrachenzÃ¤hmen leicht gemacht 2 (2014) [Bluray-720p].mkv

instead of 
Drachenzaehmen leicht gemacht 2 (2014) [Bluray-720p].mkv

The Nas running Radarr is Qnap where Umlaute are not working . I would be nice that 
ä would be converted in ae 
ü in ue
and so on  or an option where this could be enabled or not

**Comment by galli-leo** [comment]
This is most likely a result of a filesystem error. (IIRC I have seen that before on here, not sure what the solution was). Have you tried using CleanTitle instead of MovieTitle for the renaming?

**Comment by fuuss** [comment]
Yes I only used {Movie CleanTitle}  ({Release Year}) .

**Comment by bakerboy448** [comment]
Closing
v0.2 is no longer being actively developed.

If this is still an issue/request on recent v3 builds, please open a new issue.

v3 has had significant foreign language improvements
