### ISSUE TITLE
Folders not being renamed upon import

### ISSUE THREAD

**Issue by kjac3585** [Radarr/Radarr#2629]
**Radarr Version:** 0.2.0.995

**Debug Logs:**[radarr logs.zip](https://github.com/Radarr/Radarr/files/1805242/radarr.logs.zip)

I've been having this issue since around the March 4th update I believe. I don't think I've changed any settings either. The filenames are being renamed correctly however their respective folders are not, they remain original. I've got the default folder rename format "{Movie Title} ({Release Year})" and Radarr is set to rename folders as well.

Also, I should clarify that this happens to some movies, not all, but I had never had this problem before.

EDIT: I forgot that the logs aren't in DEBUG mode, so I'll have to post some new ones after they fill up.

EDIT2: I'm not getting much information from the debug logs, this is a snippet of one movie folder that was not named correctly:

`18-3-12 22:10:06.3|Debug|MovieFileMovingService|Moving movie file: X:\_NZBGet\intermediate\radarr\Gasland.2010.LIMITED.DOCU.NTSC.DVDR-Uzuri\title00.mkv to L:\_MOVIES\GasLand 2010\Gasland (2010).mkv
18-3-12 22:10:06.3|Debug|DiskTransferService|Move [X:\_NZBGet\intermediate\radarr\Gasland.2010.LIMITED.DOCU.NTSC.DVDR-Uzuri\title00.mkv] > [L:\_MOVIES\GasLand 2010\Gasland (2010).mkv]
18-3-12 22:10:26.9|Debug|MediaFileAttributeService|Setting last write time on series folder: L:\_MOVIES\GasLand 2010`

It names the movie file correctly, but the folder name is wrong.

**Comment by hotio** [comment]
So it forgets to add the brackets `()`?

**Comment by kjac3585** [comment]
I've never changed the folder format. The renaming issue isn't limited to the paraenthesis, it reuses the original folder name when I downloaded it. I've also seen it downloading the same movie twice, once to the correct directory and sometimes another download for the original folder name.

**Comment by hotio** [comment]
We can only work with the info you provide in the logs, wich is very little at this moment, just a couple of missing `()`.

Show some screenshots of your settings, from your movie details page, just some info to work with, a bunch of "Info" logs and three lines of "Debug" logs are of little use.

**Comment by kjac3585** [comment]
[logs.zip](https://github.com/Radarr/Radarr/files/1823279/logs.zip)

I thought the problem resolved itself, but it's back. I have debug logging enabled, however it seems like it only keeps debug logs for one day? The video in question was downloaded last night, so I don't know if it's in there "DEFCON The Documentary.2013.WEB.x264" and "Roger and Me 1989" are the only ones I see that are misnamed in the Radarr import directory. I could be completely wrong, but it seemed like it was only doing the renaming issue on movies I downloaded that were not wanted in my quality profiles. If I had it set to 1080p only and then manually downloaded a dvd rip for example.

```
Name: DEFCON: The Documentary

Source: X:\_NZBGet\intermediate\radarr\DEF.CON.20.2013.Docu.HDRip.X264.AC3-FooKaS\DEF CON 20 2013 Docu HDRip X264 AC3-FooKaS\DEF CON 20 2013 Docu HDRip X264 AC3-FooKaS.mkv

Imported To: L:\_MOVIES\DEFCON The Documentary.2013.WEB.x264\DEFCON The Documentary (2013).mkv
```

```
Name: Roger & Me

Source: X:\_NZBGet\intermediate\radarr\Roger.&.Me.(1989).1080p.WEB-DL.AAC2.0.H.264-TrollHD\Roger & Me (1989) 1080p WEB-DL AAC2.0 H.264-TrollHD.mkv

Imported To: L:\_MOVIES\Roger and Me 1989\Roger & Me (1989).mkv
```

![screencapture-localhost-38083-settings-mediamanagement-2018-03-18-18_49_17](https://user-images.githubusercontent.com/7411003/37572733-726cad36-2add-11e8-9bc3-b4d4e883b511.png)

**Comment by galli-leo** [comment]
Can you show us some screenshots of the movie details page in question?

**Comment by kjac3585** [comment]
I have since deleted the movie and had it redownload correctly, so that's why these screenshots don't show the directory I posted earlier.

![screencapture-localhost-38083-movies-defcon-the-documentary-211830-2018-03-19-18_52_38](https://user-images.githubusercontent.com/7411003/37628300-e2e76988-2ba6-11e8-8cd8-f3b4c9936924.png)
![screencapture-localhost-38083-movies-defcon-the-documentary-211830-2018-03-19-18_53_00](https://user-images.githubusercontent.com/7411003/37628301-e2f77684-2ba6-11e8-92f7-cd0504390ebe.png)
