### ISSUE TITLE
Make URI validation less restrictive or remove entirely

### ISSUE THREAD

**Issue by mueslo** [Radarr/Radarr#2632]
**Description:** Using a hostname with an underscore results in "Uri didn't match expected pattern" (at the very least for Sabnzbd)

Erroneous line of code: https://github.com/Radarr/Radarr/blob/520836f475cd5ed79e72b663c8b3cceb820a5f4f/src/NzbDrone.Common/Http/HttpUri.cs#L11

Relevant quote from Wikipedia:

> While a hostname may not contain other characters, such as the underscore character (_), other DNS names may contain the underscore.

**Edit**: Overall this Regex is just a bad idea. Another case where it fails (I'm guessing due to the double slashes *which radarr generated*:

`Unable to connect to list: Uri didn't match expected pattern: http://192.168.1.55:80/couchpotato//api/someapikey/movie.list/?status=active`

Just try the query, and if it fails, tell the user. Works for radarr. Don't try to build every corner case into a hideous regex.

**Radarr Version:** 0.2-910. Can't update to later version because of the TLS 1.2 bug.

**Mono Version:** 4.8.1

**Comment by Qstick** [comment]
Underscore issue is fixed here for sonarr: https://github.com/Sonarr/Sonarr/commit/1b6d6c26d5b8b0585a2fea4d79db02b77294bf4b

**Comment by Qstick** [comment]
Issue 2 is a bug in CouchPotatoRequestGenerator.cs, it should trim trailing slash from BaseUrl before building the request URL. ex. `Settings.UrlBase.TrimEnd('/')` this is how its handled for indexers.

**Comment by galli-leo** [comment]
I think the idea behind validating the url, is that users might not immediately see what's wrong, when we just test the url and say it failed.
