### ISSUE TITLE
Unable to load UI in Safari

### ISSUE THREAD

**Issue by thepaleone** [Radarr/Radarr#2636]
After updating to 0.2.0.995 I am no longer able to load the UI in Safar (latest version on latest version of Mac OS). It works fine on FIreFox, but Safari simply shows the loading gif and backgrouind.

I see the following in my developers console.

SyntaxError: Unexpected EOF
(anonymous function) - vendor.js:53933

ReferenceError: Can't find variable: webpack.jsonp
Global Code - main.js1

When I view vendor.js at that line it looks corrupted.
`this.colHeadFormat = this.view.opt('columnFormatif (evthis.computeColHeadFormat();`

In FireFox it does not look like that.

**Radarr Version:** 0.2.0.995

**Mono Version:** 5.10.0.140

**OS Version:** macOS High Sierra v 10.13.3

**Safari Version:** 11.0.3 (13604.5.6)

-Joel

**Comment by hikaricore** [comment]
While I don't have a comparable setup with the version number to test, I do have a Mac running the same OS/Safari version at my disposal, and can confirm this is not occurring in 0.2.0.998. 

While you wait for a reply from the devs, you may want to try making a new user account, to see if the issue occurs there as well: https://support.apple.com/en-us/HT204443

**Comment by galli-leo** [comment]
Try clearing cache and cookies. Might be old stale js still around.
