### ISSUE TITLE
Update fails due to decryption error

### ISSUE THREAD

**Issue by sereeth** [Radarr/Radarr#2645]
**Description:**
Failed to get response from: https://github.com/Radarr/Radarr/releases/download/v0.2.0.995/Radarr.develop.0.2.0.995.linux.tar.gz Error: SecureChannelFailure (The authentication or decryption has failed.)

**Radarr Version:**
0.2.0.980

**Mono Version:**
4.6.2 (Stable 4.6.2.7/08fd525 Tue Dec 27 10:49:36 UTC 2016)

Running radarr in freenas 11.

**Comment by galli-leo** [comment]
Duplicate issue.

**Comment by sereeth** [comment]
The other issue has no solution in it.  Sonarr works just fine so this is definitely a radarr issue.

**Comment by galli-leo** [comment]
You need to update mono to between 4.8 and 5.8. Since your version doesn't support tls 1.2 which Github is using.

**Comment by sereeth** [comment]
Ok so i rebuilt my freebsd jail and am now running mono 5.2 and this error still happens, sonarr upgrades just fine.  Ideas?

SecureChannelFailure (The authentication or decryption has failed.)

**Comment by Guegs** [comment]
Have you found a solution to this sereeth? I have my mono version at 5.2 and still get this error message.

**Comment by galli-leo** [comment]
@Guegs Try mono 5.8 or force enabling the new tls provider (should be on by default though)

**Comment by sereeth** [comment]
@Guegs , nope I can't upgrade automatically due to the requirement for > mono 5.2 which is NOT supported in freenas.  Freshports only has 5.2 (https://www.freshports.org/lang/mono/).  If all of this pain was for taking a reference to NLOG, there are MUCH better loggers out there.  Sonarr does not require > mono 5.2 to function.

**Comment by MaximV93** [comment]
Mono 5.10.1.47 is available since yesterday in Freshports. I also had to install[ this port ](https://www.freshports.org/graphics/libdrm) or the build failed.

The update of radarr is still failing though with the same error :(

**Comment by shawndewet** [comment]
Am running Radarr inside a FreeBSD Jail on FreeNAS.
Am also on Mono 5.10.1.47 (had to apply the hoftix to downgrade(?) the NLog.dll to get it to work), but the update of radarr is still failing though with the same error as the OP.

Is there a way to upgrade Radarr manually?  The Installation page of the wiki just says to run pgk update  & pkg upgrade, but I have done so (that's how I got my Mono updated to 5.10), but Radarr does not update.

**Comment by MaximV93** [comment]
PKG repo's are usually outdated. 

Follow [these instructions](https://github.com/Radarr/Radarr/wiki/Installation#freebsd-jail) to manually install Radarr. Make sure to update the RC script with the path where you installed Radarr.

Currently I'm on the latest development update so I can't check if the updater works.  I assume it will still fail because in this jail I'm still on 5.2.x mono install. (So the call to git will fail because of TLS 1.2)

However I think it should be possible to extract the zip containing the update over the path where you installed Radarr. Haven't tried that though

**Comment by shawndewet** [comment]
Thanks the extraction of the zip containing the update over the path where Radarr is installed worked.

**Comment by ryanschmidt** [comment]
Did I make a mistake by updating to the latest version of mono?
