### ISSUE TITLE
CheckForFinishedDownload never finishes, new downloads don't show up in "activity"

### ISSUE THREAD

**Issue by phiresky** [Radarr/Radarr#2646]
**Description:**

New downloads are not added to the "Activity" window anymore, and they are not moved on completion, even though the NZBget successfully downloads the files.

I enabled trace logs, and found that `CheckForFinishedDownload` is started once but then never completes.

**Radarr Version:** 0.2.0.995

**Mono Version:** 5.4.1.7

**Debug Logs:** I cleared the log files before restarting radarr and adding "Matrix" (which is correctly sent to NZBget but then never changes from "Missing" in radarr) so the noise in the logs is hopefully minimal. [logs.zip](https://github.com/Radarr/Radarr/files/1823074/logs.zip)

**Comment by phiresky** [comment]
Actually, it looks like this issue fixed it self after I deleted that row from the Commands table in the sqlite database (which had been there for five days), and then let it move all the pending files (which took over an hour). Kind of weird that the activity view does not update during moving of files which can take a long time.

This whole thing might also have been caused by my disks being extremely slow at moving during the last few weeks (~1MB/s), which together with the fact that radarr apparently does not update its pending list correctly during moves caused a buildup of duplicate downloads and even more imports.

**Comment by galli-leo** [comment]
@phiresky I actually had the same problem occur for me (It took about 3 days to move all pending files, ~1TB in total). Radarr does the move at the same time as it refreshes info from your download client, so you won't get an updated queue. We would need to do a lot of refactoring to get this working correctly, so we probably won't do it for now.
