### ISSUE TITLE
Remove empty folder feature

### ISSUE THREAD

**Issue by Indochild56** [Radarr/Radarr#2647]
Please add a remove empty folder feature like sonarr. # # #

**Comment by Viserius** [comment]
This feature would solve the issue of having hundreds of empty folders on your disk.
This can be confusing, as you might not know what movies are and aren't actually there.

Also looking forward to this feature.

**Comment by wifiuk** [comment]
yes, i really would love to had this added, when i have downloaded a file, it copies the movie, but leaves the folder.. so annoying

**Comment by Viserius** [comment]
I have proposed a solution in #3418
