### ISSUE TITLE
Trailer being used for cutoff determination

### ISSUE THREAD

**Issue by LesKent** [Radarr/Radarr#2650]
With some research and experimentation I was able to verify that the quality of a trailer file is being used to determine the cutoff for a movie. I was trying to figure out why a profile with an HDTV-1080p cutoff was showing existing downloaded movies with Bluray-1080P quality in the Cutoff Unmet list. I verified if the trailer is SDTV quality for example it will show up. If I delete the trailer and re-scan the movie then it will no longer show up in the Cutoff Unmet list.

**Comment by galli-leo** [comment]
Are you sure, Radarr didn't just misidentify the trailer as the actual movie file? i.e. did the trailer show up under the files tab?

**Comment by LesKent** [comment]
I did specifically verify that. I did find some instances where the trailer was misidentified as the the movie. It would only work correctly when the trailer file was gone from the MovieFiles table completely if it was of 
a lessor quality.

**Comment by LesKent** [comment]
I imported my library into radarr a few months back and about a quarter of the movies had existing trailer files properly named. I saw that the MovieFiles table had the trailer files all listed with a ReleaseGroup of "trailer". If I would remove a single trailer file from the disk and re-scan the trailer database entry would disappear from MovieFiles table. Today I just moved all the trailers out of the directories. and re-scanned I now notice that when I put a single trailer back and re-scan it does not get put back in the database or show up in the MovieFiles list anymore. 

I'm not really sure how the database got populated with the trailers in the first place nor at this point how a trailer is supposed to get populated since they now seem to be ignored. So for me the problem appears resolved as the trailers are just ignored now.

I see in the debug log:
18-3-19 12:05:07.9|Info|DiskScanService|Scanning disk for #Horror
18-3-19 12:05:07.9|Debug|DiskScanService|Scanning 'D:\Media\Videos\Library\Movies\#Horror (2015)' for video files
18-3-19 12:05:07.9|Debug|DiskScanService|2 video files were found in D:\Media\Videos\Library\Movies\#Horror (2015)
18-3-19 12:05:07.9|Debug|DiskScanService|[tt3526286][#Horror (2015)] Cleaning up media files in DB
18-3-19 12:05:07.9|Debug|ImportDecisionMaker|Analyzing 1/2 files.
18-3-19 12:05:07.9|Debug|Parser|Parsing string '#Horror (2015)-trailer.mp4'
18-3-19 12:05:07.9|Debug|Parser|Movie Parsed. #Horror - 2015 
18-3-19 12:05:07.9|Debug|Parser|Language parsed: English
18-3-19 12:05:07.9|Debug|QualityParser|Trying to parse quality for #Horror (2015)-trailer.mp4
18-3-19 12:05:07.9|Debug|Parser|Quality parsed: SDTV v1
18-3-19 12:05:07.9|Debug|Parser|Release Group parsed: trailer
18-3-19 12:05:08.0|Debug|ImportDecisionMaker|Size: 17957565
18-3-19 12:05:08.0|Debug|VideoFileInfoReader|Getting media info from D:\Media\Videos\Library\Movies\#Horror (2015)\#Horror (2015)-trailer.mp4
18-3-19 12:05:08.0|Debug|ImportDecisionMaker|Checking quality for this video file to make sure nothing mismatched.
18-3-19 12:05:08.0|Debug|ImportDecisionMaker|Quality (Bluray-720p v1) of the file is different than the one we have (SDTV v1)
18-3-19 12:05:08.0|Debug|GrabbedReleaseQualitySpecification|No download client item provided, skipping.
18-3-19 12:05:08.0|Debug|FreeSpaceSpecification|Skipping free space check for existing episode
18-3-19 12:05:08.0|Debug|VideoFileInfoReader|Getting media info from D:\Media\Videos\Library\Movies\#Horror (2015)\#Horror (2015)-trailer.mp4
18-3-19 12:05:08.0|Debug|DetectSample|[D:\Media\Videos\Library\Movies\#Horror (2015)\#Horror (2015)-trailer.mp4] appears to be a sample. Runtime: 00:01:39.6830000 seconds. Expected at least: 1080 seconds
18-3-19 12:05:08.0|Debug|NotUnpackingSpecification|D:\Media\Videos\Library\Movies\#Horror (2015)\#Horror (2015)-trailer.mp4 is in series folder, skipping unpacking check
18-3-19 12:05:08.0|Debug|ImportApprovedMovie|Decisions: 1
18-3-19 12:05:08.0|Info|DiskScanService|Completed scanning disk for #Horror
18-3-19 12:05:08.0|Debug|ExistingExtraFileService|Looking for existing extra files in D:\Media\Videos\Library\Movies\#Horror (2015)
18-3-19 12:05:08.0|Debug|DiskScanService|Scanning 'D:\Media\Videos\Library\Movies\#Horror (2015)' for non-video files
18-3-19 12:05:08.0|Debug|DiskScanService|12 non-video files were found in D:\Media\Videos\Library\Movies\#Horror (2015)
18-3-19 12:05:08.0|Debug|ExistingMetadataImporter|Looking for existing metadata in D:\Media\Videos\Library\Movies\#Horror (2015)
18-3-19 12:05:08.0|Debug|Parser|Parsing string 'None'
18-3-19 12:05:08.0|Debug|Parser|Unable to parse None
18-3-19 12:05:08.0|Debug|Parser|Parsing string 'None'
18-3-19 12:05:08.0|Debug|Parser|Unable to parse None
18-3-19 12:05:08.0|Debug|Parser|Parsing string 'None'
18-3-19 12:05:08.0|Debug|Parser|Unable to parse None
