### ISSUE TITLE
Please add a file size cap to quality settings.

### ISSUE THREAD

**Issue by puzl** [Radarr/Radarr#2652]
**Description:**

I can tweak my quality settings to give me a pretty good chance of ensuring that all files are under this limit but at the cost of quality on a normal length movie.

For example, if I set the limit of a 1080p bluray 140 minute movie to 15GB then all movies up to 140 minutes will copy to the cloud properly. However, if movies longer than 140 minutes will not.

So now I can tweak my quality settings to, say, 10GB for a 140 minute movie and sure enough all movies up to ~210 minutes will copy up properly. 210 minutes should about cover everything, or enough of everything that manual intervention isn't a big deal.

However, this tweak has caused almost all of my normal movies to be limited to 10GB/140m which is obviously sub optimal.

Now, if there was a global setting "Maximum file size:" I could set this to 15GB and then set my quality to what I want. radarr could then start dropping down through the matching releases until it finds the first one that is under 15GB that satisfies the specific quality setting.

**Radarr Version:**
0.2.0.778

**Mono Version:**
5.4.1.6 (tarball Wed Nov 8 20:35:02 UTC 2017)

Sonarr added an equivalent feature here:

https://github.com/Sonarr/Sonarr/pull/2367

**Comment by fryfrog** [comment]
This is super specific and would only be useful to a very small number of people, I wouldn't hold my breath for it.

Instead, why don't you create a new quality like 1080p-long that has the reduced size and then leave the normal 1080p how you want. When you add a long movie, just use the other profile.

**Comment by puzl** [comment]
I agree that it is super specific, but I would have thought it would be a reasonably straight forward change and given that it is already implemented on sonarr would give you a great starting point.

However, I accept that you have limited resources and have to be clever about which features you select for each version, so thank you for considering my request and giving me an honest answer.

I'll use your suggestion for now, thanks.

**Comment by puzl** [comment]
It hasn't made its way to master yet on sonarr.  I linked it at the bottom of my original request.

**Comment by fryfrog** [comment]
Nice!
