### ISSUE TITLE
Radarr Lists, Folder dropdown menu is empty

### ISSUE THREAD

**Issue by iAmRenzo** [Radarr/Radarr#2654]
I run Radarr in a Docker container on Synology.

I wanted to add my IMDb Watchlist to Radarr. I need to select a path for the Folder setting, but the dropdown menu is empty. What is this path?
Do I need to map something in Docker, but to what?

**Comment by galli-leo** [comment]
You need to go to add movie, search for anything (like star wars). Then you can select add path, for any movie appearing in the search results. There you can add the path where you want Radarr to store your movies. You can then select that path in the lists menu.

**Comment by tiagoboldt** [comment]
@galli-leo I keep using this issue as reference. Because the issue still exists. This is not intuitive at all. shouldn't this be reopened to create a fix that becomes intuitive for the user?

**Comment by fryfrog** [comment]
The Sonarr v3 UI finally adds root folders to Settings. The *Radarr* port of that to v2 includes it. Yay.
