### ISSUE TITLE
 automatically ignore movie files with size between 750 and 760mb

### ISSUE THREAD

**Issue by jb2210** [Radarr/Radarr#2659]
I found myself having to set all quality definitions with a size smaller than 800mb as not useful. A few months ago there started to appear files with the size of 753.3 mb containing only a video telling you to install a certain decoder on torrent sites. 

![capture](https://user-images.githubusercontent.com/25897516/37705119-43b93368-2cfb-11e8-9de5-ff6e228c05cb.PNG)

all of those files do not contain anything useful like the movie itself or something like that. It just shows you a box telling you to download decoding software in order to watch the movie.

therefor I propose to have an option available to ignore all files with a certain size, since the file size of this particular misleading file may be changed after adding this feature.

**Comment by galli-leo** [comment]
You can already set a minimum size
