### ISSUE TITLE
Mislabeling on Bulk (initial) Import

### ISSUE THREAD

**Issue by Vacant0mens** [Radarr/Radarr#2663]
**Description:**
After I imported my library into Radarr, I noticed some of my movies got the label of `HDTV-1080p` or `HDTV-720p` when, in fact, the file came from a BluRay. Some are even encoded in such a way that the .mkv files are 8gb+, some as large as 12 or 13gb.

How does Radarr determine the source of a video file? 

**Radarr Version:**
Version
0.2.0.995

**Mono Version:**
Mono Version
5.10.0.160 (tarball Wed Mar 7 15:30:00 UTC 2018)

**Comment by Vacant0mens** [comment]
Just tried a new version of a movie.
I had it set to upgrade a few of my movies. It downloaded a full 4k BluRay rip (>80gb) and even said that the thing that was downloading was a `BluRay-2160p`. It wasn't able to import it since there weren't any video container files, so I used a program to package the movie into an mkv, then I imported it using Radarr's manual import from the same directory as the download. After I imported it, I had to tell it to update the information about the movie and scan the disk again (which I would think should happen automatically). When it was done loading, it marked the new version of the movie as `HDTV-2160p`.

What's going on?

**Comment by galli-leo** [comment]
Radarr uses mostly the filename for determining the source and resolution for now. So if you don't specify a source in the filename, it won't know what it is and thus presumes it to be the worst quality (HDTV). This will become better in a future release, but it is strongly recommended to always have the source in your filename, as there is no way of knowing if a 12 GB file is a bluray or webdl.
