### ISSUE TITLE
[Feature] Use folder name for Original Title if Original Title is shit.

### ISSUE THREAD

**Issue by DesktopMan** [Radarr/Radarr#2664]
Currently it looks like bulk import is using the file name for information, including original title. In many cases the folder has a better, more informative name than the file(s).

Here's an actual example from Radarr 0.2.0.995 that illustrates the problem (with folder renaming enabled, which is also affected):

```
Your movie may be moved; see the paths below
Folder Naming pattern: {Original Title}
Naming pattern: {Original Title}

 /data/testmovies/Test.Movie.One.2001.DVDRip.XViD-GROUP/g-tmo.avi
 /data/testmovies/g-tmo/g-tmo.avi
```
Clearly using the folder name would have been much better in cases like this. Radarr also thinks that the group is "tmo" due to the naming of the file which would mess up any rename rule using the group name. An option to use the folder name for everything would fix all of these issues.

**Comment by belsander** [comment]
Same problem here, but with downloaded movies. Movie file names are hashes, but the folder name is the actual movie name.
It does however work when I use "Manual Import". But this requires a manual action from the user side every time. So +1 for me!

Environment:
Docker: linuxserver/radarr
Radarr version:   0.2.0.1120
Mono Version: 5.12.0.226 (tarball Thu May 3 09:48:32 UTC 2018)

**Comment by bakerboy448** [comment]
Closing
v0.2 is no longer being actively developed.

If this is still an issue/request on recent v3 builds, please open a new issue.
