### ISSUE TITLE
Radarr does not find moviefile

### ISSUE THREAD

**Issue by tigertim08** [Radarr/Radarr#2667]
Hello everyone, I have a problem since a couple auf my film files are not found? Does anyone already hat the same issue?
![2018-03-23_18-34-56](https://user-images.githubusercontent.com/24661102/37846427-df13453c-2ecd-11e8-9a8c-7f5590025f5f.jpeg)

**Comment by galli-leo** [comment]
Bulk import doesn't do the same scan as when you actually import it, so you are probably fine.
