### ISSUE TITLE
Movie API does not persist Quality updates

### ISSUE THREAD

**Issue by jlikens** [Radarr/Radarr#2675]
Radarr Version: 0.2.0.995

When using the PUT /api/movie method to update the quality for movies, the update accepted but is lost immediately.  Interestingly, if the page for the movie that is being updated is open, a SignalR event does get broadcast and it flips the quality on the page correctly.  However, after refreshing the page or calling GET /api/movie/{id}, the quality reverts to its original value.  This occurs with various combinations of original and updated qualities.

**Comment by galli-leo** [comment]
You need to PUT to /api/moviefile (with the correct moviefile id), else the change won't be saved in the db.

**Comment by jlikens** [comment]
Got it, thank you.
