### ISSUE TITLE
[Feature Request] Add {Localized movie title} as a Rename option

### ISSUE THREAD

**Issue by i3laze** [Radarr/Radarr#2676]
Subject.

Seems, “standard movie format” file name is the same in the list of a download client (e.g. Transmission). It would be nice for the filename to contain Russian title (or whatever language was set in movie properties) to match the localized title displayed on Radarr’s main page.

I use movie.nfo metadata for Kodi, so a localized file title won’t heavily affect anything else.

**Comment by Ghostaunt** [comment]
I agree that ! It's very needed !!

**Comment by iFredOS** [comment]
When this will happen? You check IMDB original title. 😉

**Comment by ejalal** [comment]
This will solve a problem I'm currently having with French indexers, as all of them use the English movie title in torrent file name, Radarr can still find the movie based on the search query but when it finds the correct movie with an English title, it simply ignores it as the title doesn't match.
