### ISSUE TITLE
[Request] Multiple Secondary Cutoff Support

### ISSUE THREAD

**Issue by zero77** [Radarr/Radarr#2677]
Can you please add support for multiple secondary cutoff options.

For example, I am looking for 1080p webdl and I end up with lots of the same downloads, for shows with only 1080p hdtv or webrip and not webdl downloads.
Thanks

**Comment by galli-leo** [comment]
See https://github.com/Radarr/Radarr/projects/1
This will allow you to add custom qualities (such as webrip) and make webdl be above webrip in your profile.

**Comment by zero77** [comment]
ok thanks
