### ISSUE TITLE
Show more Metadata/ Poster on add from List Page

### ISSUE THREAD

**Issue by Johan-A-M** [Radarr/Radarr#2679]
Hi,

I'd like to see the following enhancement: When I add movies from a list, I obviously first select a list and click Fetch List. Would it be possible to get more information, such as poster? I find the resulting list with titles a bit uninteresting to pick from. Most of the time, I select a list like StevenLu to get inspired and pick a few good ones, but I usually don't know in advance which ones to pick. If we were to see the same information as we do when we pick Discover New Movies, it would be a lot easier.

Anyway, thanks for a fantastic app!

**Comment by galli-leo** [comment]
This is unfortunately not currently possible, since most list providers only give us back the year and title. However, with the new API and maybe the new UI this could be implemented.

**Comment by Johan-A-M** [comment]
Thanks for answering!
