### ISSUE TITLE
Can't match The Man from U.N.C.L.E. (2015)

### ISSUE THREAD

**Issue by karirafn** [Radarr/Radarr#268]
Probably because of the periods?

Path is \The Man from U.N.C.L.E. (2015)\The Man from U.N.C.L.E. (2015).mkv

**Comment by onedr0p** [comment]
Any errors in the logs for that?

**Comment by karirafn** [comment]
Which one? (sorry I'm new). I enabled the trace log and this is the only mention I found:

> 17-1-14 15:14:11.5|Debug|Parser|Parsing string 'The Man from U.N.C.L.E. (2015)'
17-1-14 15:14:11.5|Debug|Parser|Unable to parse The Man from U.N.C.L.E. (2015)
17-1-14 15:14:11.5|Debug|DiskScanService|Scanning '/movies/The Man from U.N.C.L.E. (2015)/' for video files
17-1-14 15:14:11.5|Debug|DiskScanService|1 video files were found in /movies/The Man from U.N.C.L.E. (2015)/
17-1-14 15:14:11.5|Debug|Parser|Parsing string 'The.Man.from.U.N.C.L.E..(2015).mkv'
17-1-14 15:14:11.5|Trace|Parser|^(?<title>.+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(19|20)\d{2}(?!p|i|\d+|\]|\W\d+)))+(\W+|_|$)(?!\\)
17-1-14 15:14:11.5|Debug|Parser|Movie Parsed. The Man from U N C L E - 0 
17-1-14 15:14:11.5|Debug|Parser|Language parsed: English
17-1-14 15:14:11.5|Debug|QualityParser|Trying to parse quality for The.Man.from.U.N.C.L.E..(2015).mkv
17-1-14 15:14:11.5|Debug|Parser|Quality parsed: HDTV-720p v1
17-1-14 15:14:11.5|Debug|Parser|Release Group parsed: 
17-1-14 15:14:11.8|Debug|Parser|Parsing string 'The.Man.from.U.N.C.L.E..(2015).mkv'
17-1-14 15:14:11.8|Trace|Parser|^(?<title>.+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(19|20)\d{2}(?!p|i|\d+|\]|\W\d+)))+(\W+|_|$)(?!\\)
17-1-14 15:14:11.8|Debug|Parser|Movie Parsed. The Man from U N C L E - 0 
17-1-14 15:14:11.8|Debug|Parser|Language parsed: English
17-1-14 15:14:11.8|Debug|QualityParser|Trying to parse quality for The.Man.from.U.N.C.L.E..(2015).mkv
17-1-14 15:14:11.8|Debug|Parser|Quality parsed: HDTV-720p v1
17-1-14 15:14:11.8|Debug|Parser|Release Group parsed:

Other than that I didn't find anything in the logs.

**Comment by galli-leo** [comment]
Did you see anything other, like movie not found or something? You can also just post the full log.

**Comment by karirafn** [comment]
If I clear all logs from System - Logs after enabling the debug log and then try to manually import the movie this is all that's in the debug log:

> 17-1-14 15:31:27.5|Debug|Api|[PUT] /api/config/host: 202.Accepted (19 ms)
17-1-14 15:31:27.7|Debug|Api|[GET] /api/health: 200.OK (0 ms)
17-1-14 15:31:31.1|Debug|Api|[GET] /api/wanted/missing??page=1&pageSize=15&sortKey=airDateUtc&sortDir=desc&filterKey=monitored&filterValue=true: 200.OK (6 ms)
17-1-14 15:31:31.1|Debug|Api|[GET] /api/wanted/missing??page=1&pageSize=15&sortKey=airDateUtc&sortDir=desc&filterKey=monitored&filterValue=true: 200.OK (6 ms)
17-1-14 15:31:35.2|Debug|Parser|Parsing string 'The Man from U.N.C.L.E. (2015)'
17-1-14 15:31:35.2|Debug|Parser|Unable to parse The Man from U.N.C.L.E. (2015)
17-1-14 15:31:35.2|Debug|DiskScanService|Scanning '/movies/The Man from U.N.C.L.E. (2015)/' for video files
17-1-14 15:31:35.2|Debug|DiskScanService|1 video files were found in /movies/The Man from U.N.C.L.E. (2015)/
17-1-14 15:31:35.2|Debug|Parser|Parsing string 'The.Man.from.U.N.C.L.E..(2015).mkv'
17-1-14 15:31:35.2|Debug|Parser|Movie Parsed. The Man from U N C L E - 0 
17-1-14 15:31:35.2|Debug|Parser|Language parsed: English
17-1-14 15:31:35.2|Debug|QualityParser|Trying to parse quality for The.Man.from.U.N.C.L.E..(2015).mkv
17-1-14 15:31:35.2|Debug|Parser|Quality parsed: HDTV-720p v1
17-1-14 15:31:35.2|Debug|Parser|Release Group parsed: 
17-1-14 15:31:35.5|Debug|Parser|Parsing string 'The.Man.from.U.N.C.L.E..(2015).mkv'
17-1-14 15:31:35.5|Debug|Parser|Movie Parsed. The Man from U N C L E - 0 
17-1-14 15:31:35.5|Debug|Parser|Language parsed: English
17-1-14 15:31:35.5|Debug|QualityParser|Trying to parse quality for The.Man.from.U.N.C.L.E..(2015).mkv
17-1-14 15:31:35.5|Debug|Parser|Quality parsed: HDTV-720p v1
17-1-14 15:31:35.5|Debug|Parser|Release Group parsed: 
17-1-14 15:31:35.8|Debug|QualityParser|Trying to parse quality for /movies/The Man from U.N.C.L.E. (2015)/The Man from U.N.C.L.E. (2015).mkv
17-1-14 15:31:35.8|Debug|Api|[GET] /api/manualimport??folder=%2Fmovies%2FThe+Man+from+U.N.C.L.E.+(2015)%2F&sort_by=qualityWeight&order=desc: 200.OK (567 ms)
17-1-14 15:31:45.5|Debug|Api|[GET] /api/queue??sort_by=timeleft&order=asc: 200.OK (2 ms)

**Comment by macbean101** [comment]
It does seem to have to do with the periods.  When I imported mine, i got the same issue where it would not match anything.  but when I removed the periods (UNCLE) it matched right away.  

I got the same behaviour from "Escape from L.A." and R.I.P.D. 

In all three cases, removing the . allowed them to match

**Comment by nullredvector** [comment]
worked fine for me with periods

**Comment by karirafn** [comment]
This one still doesn't work.

**Comment by galli-leo** [comment]
@karirafn Can you post more logs? Works perfectly fine for me with the exact filename you have.
