### ISSUE TITLE
Feature Request - Centralized authentication (LDAP) and SSO (SAML/OATH)

### ISSUE THREAD

**Issue by rickatnight11** [Radarr/Radarr#2680]
## Feature Request

Support for centralized authentication (i.e. LDAP) and SSO (i.e. SAML/OATH) provides several benefits:

1. Multiple user accounts without password sharing
2. Don't store admin credentials in plaintext config
3. Use same credentials/sessions across apps in this space ( i.e Sonarr, NZBGet, Tautulli, etc)
4. Opens the door for user permissions (authorization) down the road
5. Improve security by offloading AuthN/AuthZ to services designed for these purposes

**Comment by galli-leo** [comment]
If I had unlimited development time, this would of course be nice to implement, but this will never happen. If you want a multi user setup, take a look at ombi, I think it does handle that very nicely, especially for non techaffine friends and family members.
