### ISSUE TITLE
Many downloads started if same name is carried by different trackers.

### ISSUE THREAD

**Issue by GroupMaster** [Radarr/Radarr#2681]
I am finding when a movie search is done, automatically or by using the search tab to select one manually, my torrent client is sometimes getting clobbered. This is on a new install with the latest version (0.2.0.995 - Mar 4 2018). I have quite a few private trackers via jackett available in radarr. Several times now I have had many (3-10) additional torrents with the identical name also load all from different sources (PS, this makes a hell-o-mess!). It seems that when a download is selected it not only uses the one from the tracker listed at time of selection but from all trackers that have the exact same torrent. With the fact that no one else has mentioned this issue I am strongly led to believe this is due to the use of jackett.

For anyone that is not familiar with jackett, the URLs used are all very similar. The only difference between URLs are the "[TRACKER]" part.... Maybe this is relevant, maybe it's not...
http://127.0.0.1:9117/api/v2.0/indexers/[TRACKER]/results/torznab/

**Comment by galli-leo** [comment]
Can you post a screenshot of your history tab for a movie with such downloads?

**Comment by GroupMaster** [comment]
Fun, I've had way too much activity since, proverbial needle in a haystack.  I'll have to make it happen again so the logs aren't buried. I'll post as soon as it triggers.

**Comment by galli-leo** [comment]
If you still know what movie it was, you should be able to see the history on its detail page.
