### ISSUE TITLE
Indexer rss sync didn't cover the period between 3/27/2018 11:56:58 AM and 3/27/2018 12:12:59 PM UTC. Search may be required.

### ISSUE THREAD

**Issue by biship** [Radarr/Radarr#2682]
**Radarr Version:**  0.2.0.1020
I am getting this error for demonoid via Jackett every 15mins:
`
Torznab | Indexer j.demonoid rss sync didn't cover the period between 3/27/2018 11:56:58 AM and 3/27/2018 12:12:59 PM UTC. Search may be required. | 8:12am

Torznab | Indexer j.demonoid rss sync didn't cover the period between 3/27/2018 11:40:57 AM and 3/27/2018 11:56:58 AM UTC. Search may be required. | 7:56am

Torznab | Indexer j.demonoid rss sync didn't cover the period between 3/27/2018 11:24:56 AM and 3/27/2018 11:40:57 AM UTC. Search may be required. | 7:40am
`
Jackett is running on same host (htpc), on port 9117.

Indexer setup in Radarr:
`http://htpc:9117/api/v2.0/indexers/demonoid/results/torznab/`
Test works fine in Radarr

Indexer setup in Jackett:
`https://www.demonoid.pw/`
(with user & pass)
Test works fine in Jackett

RSS feed from Jackett to Demoid returns results:
`http://htpc:9117/api/v2.0/indexers/demonoid/results/torznab/api?apikey=<apikey>&t=search&cat=&q=
`
I do not get this with other Jacket indexers set up in Radarr.

**Comment by galli-leo** [comment]
Please post some debug logs of the rss sync.
