### ISSUE TITLE
Calendar is completely blank

### ISSUE THREAD

**Issue by majora2007** [Radarr/Radarr#2683]
**Description:**
My Calendar is completely blank. This is a new issue that has occurred. From the console, it seems that Radarr is pointing to old Series code. I have done a hard refresh and also attempted to use Incognito, but the issue still persists. This issue persists through develop releases. 

This is what is found in the console:

backbone.marionette.templates.js:30 template render failed for calendar/upcomingitemview TypeError: Cannot read property 'id' of undefined

Object
added
:
"2017-09-09T22:19:51.3210973Z"
alternativeTitles
:
[]
cleanTitle
:
"readyplayerone"
deleted
:
false
downloaded
:
false
end
:
"2018-03-28T07:20:00.000Z"
episodeCount
:
0
episodeFileCount
:
0
folderName
:
"N:\Movies\Ready Player One (2018)"
genres
:
[]
hasFile
:
false
id
:
3083
images
:
(2) [{…}, {…}]
imdbId
:
"tt1677720"
inCinemas
:
"2018-03-28T05:00:00Z"
isAvailable
:
false
isExisting
:
false
lastInfoSync
:
"2018-03-27T01:20:13.4596199Z"
minimumAvailability
:
"released"
monitored
:
true
overview
:
"When the creator of a popular video game system dies, a virtual contest is created to compete for his fortune."
path
:
"N:\Movies\Ready Player One (2018)"
pathState
:
"static"
profileId
:
4
qualityProfileId
:
4
ratings
:
{votes: 34, value: 8.3}
runtime
:
140
saved
:
false
secondaryYearSourceId
:
0
sizeOnDisk
:
0
sortTitle
:
"ready player one"
status
:
"announced"
studio
:
"Amblin Entertainment"
tags
:
[]
title
:
"Ready Player One"
titleSlug
:
"ready-player-one-333339"
tmdbId
:
333339
website
:
"http://readyplayeronemovie.com"
year
:
2018
youTubeTrailerId
:
"cSp1dM2Vj48"
__proto__
:
Object

Uncaught TypeError: Cannot read property 'id' of undefined
    at QueueCollection.js:25
    at Function.find (lodash.underscore.js:1843)
    at child.findEpisode (QueueCollection.js:24)
    at Object.<anonymous> (Episode.js:19)
    at Object.main (templates.js?h=5t8UaKjIqBVvF1g6QCj+NQ:183)
    at ret (handlebars.runtime.js?h=VR1gUKhkPyiPuEfway9bag:558)
    at backbone.marionette.templates.js:27
    at Object.render (backbone.marionette.js:1190)
    at child.render (backbone.marionette.js:1422)
    at child.bound [as render] (lodash.underscore.js:665)

And if we jump into QueueCollection.js at the line above, we see:

findEpisode : function(episodeId) {
        return _.find(this.fullCollection.models, function(queueModel) {
>            return queueModel.get('episode').id === episodeId;
        });
    },

**Radarr Version:** Radarr Ver. 0.2.0.1020

**Mono Version:** N/A

**Debug Logs:** UI only issue, nothing relevant in logs

**Comment by galli-leo** [comment]
Actually, can you try upgrading to the latest version and trying maybe a different browser? This works for me on the custom-formats branch (which is up to date with develop).

**Comment by majora2007** [comment]
@galli-leo I heard that custom-formats branch may cause issues on my db (per the discord). How can I update to latest on develop? Per the commit history and update log, I'm up to date. 

Tried with FF, no luck.

**Comment by galli-leo** [comment]
@majora2007 hmm, in that case, try manually reinstalling, maybe one of the js files is goofed

**Comment by Qstick** [comment]
Is it possible that this is a cache issue?

**Comment by Qstick** [comment]
Hmm, Does look like there is some series code left in queue collection, probably need to clean that up.
