### ISSUE TITLE
Cannot use apostrophes within searches or the movie is not found.

### ISSUE THREAD

**Issue by clivecrous** [Radarr/Radarr#2684]
Attempting to find the movie:

"The House With A Clock In It's Walls"

You cannot search for: "The House With A Clock In It's Walls" (apostrophe)
You have to search for: "The House With A Clock In Its Walls" (without apostrophe)

... otherwise it does not find it

Version 0.2.0.995

**Comment by hotio** [comment]
Isn't that normal considering the first with ' is the wrong movie name, why would they even write their name with bad spelling?
