### ISSUE TITLE
[Feature Request] Identify Missing Movies with Rejections

### ISSUE THREAD

**Issue by crhammock** [Radarr/Radarr#2686]
When waiting for releases I found myself constantly having to check movie details search tab to identify if files are available which don't meet my criteria.  Would it be possible either via a different status (Missing -Available or Missing - Unavailable) or by a hover message when you hover over the missing label to identify if there are files with rejections for that movie?

**Comment by bakerboy448** [comment]
No plans at this time; limited use case
