### ISSUE TITLE
Bug list Trakt

### ISSUE THREAD

**Issue by Algedi13** [Radarr/Radarr#2687]
Hello,

**Description :**

- For trakt when I enter a second list with a different folder location than the first one when the save does not consider this location and replace it with a blank. 

**Edit :** oops I did not pay attention to this old issue [#1711](https://github.com/Radarr/Radarr/issues/1711)

- With the list trakt whether Minimum Availability "PreDB" or "In Cinemas" the directories are created in the select folder whereas normally they should be once they are on "PreDB" or "In Cinemas"

**Radarr Version container :** 0.2.0.995 (linuxserver/radarr)

**Mono Version :** 5.10.1.4 (tarball Wed Mar 21 10:51:27 UTC 2018)

**Debug Logs :**

[Bug list Trakt create folder](https://pastebin.com/C4hETJfs)

[Bug Trakt second list folder](https://pastebin.com/Fbu9mXaT) #1711

**Comment by Algedi13** [comment]
Nop for the second issue :

- 
With the list trakt whether Minimum Availability "PreDB" or "In Cinemas" the directories are created in the select folder whereas normally they should be once they are on "PreDB" or "In Cinemas"

**Comment by galli-leo** [comment]
Ah I get the issue now. Well that's working as intended. Radarr will create empty directories from the beginning if you set it to create empty directories.

**Comment by Algedi13** [comment]
Ah ok with the option "Folders Create empty movie folders"? It will not impact the creation of future folders for movies that do not have one?
