### ISSUE TITLE
BR-DISK labeled as Bluray 1080p

### ISSUE THREAD

**Issue by bobbintb** [Radarr/Radarr#2688]
It seems anything that should be BR-DISK is labeled as Bluray 1080p. I use PTP as my tracker, if that matters. I assume BR-DISK translates to BD50 or BD25. This has resulted in some rather large downloads. Any time I manually search for a file on the movie's page in Radarr it will also show any BR-DISK torrents as Bluray 1080p. I tried adjusting the quality settings of BR-DISK to as high as I could get them and it still labels those torrents as Bluray 1080p.

**Radarr Version:**
0.2.0.995
**Mono Version:**
5.10.1.4

**Comment by galli-leo** [comment]
This is fixed on the custom formats branch
