### ISSUE TITLE
Radarr is randomly deleteing my movies

### ISSUE THREAD

**Issue by topcat30** [Radarr/Radarr#2689]
**Description:**
After importing setting up etc i leave and come back and almost all the kids movies are deleted and some of mine.
Its the second time its happened in a couple of days, luckily this time i setup the recycle bin.

I have set the service to disabled until there is a fix? or hopefully someone can explain why its happening.
[radarr.txt](https://github.com/Radarr/Radarr/files/1865270/radarr.txt)

**Comment by galli-leo** [comment]
You have clean library enabled. This means if a movie isn’t in your lists, it will get deleted. You can disable that setting under Settings-> Lists
