### ISSUE TITLE
UserCustomList Trakt List - Rating Field Not Working

### ISSUE THREAD

**Issue by Chudz** [Radarr/Radarr#2694]
**Description:**

When setting up a **UserCustomList** type Trakt List for import, Radarr ignores the **Rating** field and will just import everything in the list. It works fine when you setup **Trending** or **Popular** type Trakt Lists it only effects **UserCustomList**

**Radarr Version:**

Radarr Ver. 0.2.0.995
Using Docker

**Comment by rinslee** [comment]
Correct, UserCustomList ignores filters. Hovering over the '?' next to the username field should give a little note about the ignore.

**Comment by galli-leo** [comment]
Yeah, if you have a custom list we assume that you want every item on that, since you need to manually add them. Also not sure if the trakt api would even support filtering there.
