### ISSUE TITLE
[Bug] Only Showing 10 Per Page When It Set To 250

### ISSUE THREAD

**Issue by zero77** [Radarr/Radarr#2700]
Radarr only seems to be showing 10 per page when its set to 250.

i am using ubuntu

**Radarr Version:**
    0.2.0.995
**Mono Version:**
5.10.1.20
**Debug Logs:**

**Comment by galli-leo** [comment]
It's only a visual bug. You need to set the page size to something else, save, set it back.

**Comment by zero77** [comment]
@galli-leo 
It keeps happening, is there something more permanent I can do so I don’t have to keep doing this.
Thanks

**Comment by JRussell** [comment]
Why is this closed? A visual bug is still a bug. This only happens in Radarr, not Sonarr and it's pretty annoying.

**Comment by Prime-Omega** [comment]
This is still an issue to date and having to change the UI settings every time you login is kind of cumbersome. Any update?

**Comment by Qstick** [comment]
Yea it's fixed in v3... No plans to fix in 0.2

**Comment by Prime-Omega** [comment]
Wasn't even aware there was a completely new version, my bad...
