### ISSUE TITLE
Colored filters according to index

### ISSUE THREAD

**Issue by SeyedGH** [Radarr/Radarr#2701]
Radarr v. 0.2.0.995

Is there any way to implement this in the filter system in the movie section.
![radarr](https://user-images.githubusercontent.com/8275308/38415464-e8b1d7f6-3991-11e8-8dfa-d05fb0b6829a.jpg)

This way we have quick buttons to the index at the button as filters.
![radarr2](https://user-images.githubusercontent.com/8275308/38415646-6e22e222-3992-11e8-9d86-8a7d0918023f.jpg)

It would make live so much more easy to edit items at mass level.

**Comment by fedoranimus** [comment]
I like this, I'll apply the idea to the new UI designs.
