### ISSUE TITLE
Transmission timeout slow down all other operations

### ISSUE THREAD

**Issue by andyts93** [Radarr/Radarr#2702]
Some days ago I started having problems with radarr, sometimes every operation (adding a film, adding an indexer, change a movie folder and so on) is very very slow and most of the times nothing happens. Yesterday I was not able to open the web ui at all. I'm running the latest linuxserver docker so I tried to delete the config folder and recreate the containr, I found out that the problem is transmission.
When I add it to the download clients (the test is successfull) I keep getting timeout errors and all the operations slow down. 
I don't think it's a transmission problem because I have it configured in sonarr with the same information and it works fine
[radarr timeout errors.log](https://github.com/Radarr/Radarr/files/1886421/radarr.timeout.errors.log)

**Comment by melari** [comment]
Exact same issue here: I add the transmission integration and it says the test is successful, but then logs get flooded with timeout errors and the entire app becomes unusable to the point that I can't even disable the transmission integration anymore

**Comment by Tadimsky** [comment]
I've had it take > 5 minutes to load the information for one movie. I'm using Transmission too, so maybe similar issue.
The WebUI often hangs so much I get 502s through my reverse proxy..
