### ISSUE TITLE
Interpunct

### ISSUE THREAD

**Issue by keldian** [Radarr/Radarr#2704]
Some movie titles in TMDB are stylized with an interpunct (e.g. WALL·E), however trackers and newsgroups typically do not use that to name releases, but a dash or period instead, and as a result Radarr searches find no matches where they should. Treating interpuncts the same way colons are treated should solve the problem I think.

**Radarr Version:**
0.2.0.995
**Mono Version:**
5.10.1.20

**Comment by keldian** [comment]
Still an issue.

**Comment by afalahi** [comment]
this is an issue for me as well
