### ISSUE TITLE
Quality Definitions

### ISSUE THREAD

**Issue by SeyedGH** [Radarr/Radarr#2706]
Radarr v. 0.2.0.995

I have noticed that the quality definition has a maximum of 17.36 GB for 90min or 27gb for 140min.
this should really be higher considering we are talking about Remux 2160p those max should be around 55GB for 90 min and 80GB for 140min.

So this should really be considered fixing to be able to use this option for radarr.
![q1](https://user-images.githubusercontent.com/8275308/38524820-3b1870de-3c50-11e8-8c8e-3d0c10e47f49.jpg)

**Comment by galli-leo** [comment]
Duplicate issue
