### ISSUE TITLE
All Movies Disappeared Temporarily

### ISSUE THREAD

**Issue by kaysond** [Radarr/Radarr#2708]
**Description:**

This is one of those horrible things that's probably impossible to find/reproduce, but I figured someone else might've seen it before. I haven't changed any config, packages, etc, and I logged onto the web interface to find that all of my movies were gone! Checked the logs, didn't see anything. Restarted the systemd service, then found this in my syslog:

```
Apr 11 14:06:47 fserver systemd[1]: radarr.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 11 14:06:47 fserver systemd[1]: radarr.service: Unit entered failed state.
Apr 11 14:06:47 fserver systemd[1]: radarr.service: Failed with result 'exit-code'.
```

No idea why. The systemd file hasn't changed either. Doing a `systemctl stop` then `systemctl start` seemed to work.

Digging into the radarr logs after the restart, I noticed that the RefreshMovieService seemed to come up empty for every single movie in my list. I also noticed an issue with binding to the port which has never happened before. I'm guessing this is related to the service not starting.

```
18-4-11 03:55:58.5|Info|RefreshMovieService|Skipping refresh of movie: Your Name.
18-4-11 03:55:58.5|Info|DiskScanService|Scanning disk for Your Name.
18-4-11 03:55:58.5|Info|DiskScanService|Completed scanning disk for Your Name.
18-4-11 03:55:58.5|Info|ExistingMetadataImporter|Found 0 existing metadata files
18-4-11 03:55:58.5|Info|ExistingSubtitleImporter|Found 0 existing subtitle files
18-4-11 03:55:58.5|Info|ExistingOtherExtraImporter|Found 0 existing other extra files
18-4-11 03:55:58.5|Info|ExistingExtraFileService|Found 0 extra files

18-4-11 14:06:46.8|Fatal|ConsoleApp|Address already in use. This can happen if another instance of Radarr is already running another application is using the same port (default: 7878) or the user has insufficient permissions
```

So I finally got the service to restart, and still no movies. Did a second restart, bam!, movies. ???

**Comment by sereeth** [comment]
I have the same problem, this is a bug somewhere.  I've lost the movie list 3 times now, and have had to re-bulk import eveything

**Comment by sereeth** [comment]
This is what i see when this happens:  

![image](https://user-images.githubusercontent.com/16249946/38784796-478e0182-40e5-11e8-932a-d086a84a8c85.png)

The movies are there, just not visible, if I search for a movie it is found and can be viewed in radarr.  Very wierd.

**Comment by kaysond** [comment]
That's what I see too!

**Comment by kaysond** [comment]
In my case, the files are all local.

**Comment by sereeth** [comment]
Updated to latest code, cleared cache, checked and the drive is accessible by radarr, if i search for the movies they are there its just the main list.  What logs are do you want?

**Comment by galli-leo** [comment]
@sereeth Did you also clear cookies and application data? Debug logs.

**Comment by sereeth** [comment]
Heya @galli-leo yeah so i figured a ctrl shift r reload in chrome would suffice, apparently not... I had to dump my entire browser cache to get it to function which seems extremely odd.
