### ISSUE TITLE
Radarr deleting poster images from movie directory when higher quality found

### ISSUE THREAD

**Issue by Singularity222** [Radarr/Radarr#2710]
I did quite a bit of searching about Radarr's functionality but haven't found anything to answer my question. I use Radarr in conjuntion with Plex and I try to keep everything pretty neat. One thing I do is include an image in the folder of each movie that Plex will display as the poster art.

What I've noticed is if Radarr downloads a version of the movie with a higher quality the image in the folder is deleted. So alot of my movies that  once had poster art saved in the directory are now gone. Is clearing out the movie directory of all files intetional? I assume if poster art is being deleted, people who set up their own subtitles for Plex that are included in the same directory are being deleted as well. Unless this is just affecting images.

Using Radarr version 0.2.0.995 and I have the option "Import Extra Files" under imports enabled. Could be a coincidence, but I feel like this may have started happening when I enabled this option.

**Comment by Singularity222** [comment]
Has this been released yet? Because my poster images are still being deleted.

**Comment by wapplegate** [comment]
It's been a while since I've posted this. The issue doesn't seem to be fixed either. Could anyone let me know what I need to enable or disable to stop this?
