### ISSUE TITLE
Additional list provider

### ISSUE THREAD

**Issue by hr1232** [Radarr/Radarr#2713]
This is not a bug, but a feature request.

As the default TMDB lists only give you a few movies and do not allow the user to export the entire database, those lists suck. I've created my own app that has their entire database and allows to import the **entire** db into Radarr (with or without filters). New additions to TMDB are added daily into my database, information about existing movies is updated once per month.

As a special feature the result will include complete collections. If only parts of a collection fit the query parameters the result will still contain the entire collection. Of course, anyone who doesn't want that feature can disable it, so results will only contain those movies that fit the search parameters.

Currently the following filters are available:
- original language (parameter lang=xx)
- maximum rating (parameter maxvote=n)
- minimum rating (parameter minvote=n)
- minimum year (parameter minyear=nnnn)
- maximum year (parameter maxyear=nnnn)
- no porn (parameter adult=0)
- only porn (parameter adult=1)
- complete collections (parameter collections=1)
- only movies that fit the search criteria (parameter collections=0)

The base URL is https://www.heikorichter.name/movies.php, parameters can but do not have to be added. If no parameters are given, these are the ones used by default:
?adult=0&collections=1

File format is JSON and fits the SteveLu parser. The movie title given in the result will always be the original title (original language).

I would like to offer the list to everybody and would therefor welcome if it could be added to Radarr with a nice frontend (the the TMDB lists) that lets users select the parameters listed above. If any are missing please tell me, I'm happy to add them.

**Comment by galli-leo** [comment]
Hi hr1232,
Thank you for setting up such an endpoint!

However, with Radarr API V3 it probably will not be necessary anymore, since that will have a lot of filtering options. See https://github.com/Radarr/RadarrAPI.TMDB/tree/release/3.0 for the work done so far and see [Radarr API V3.pdf](https://github.com/Radarr/Radarr/files/1913552/Radarr.API.V3.pdf) for what I have in mind.

Additionally, I don't want to get your server run over 😬 (not sure what your server can handle, but the Radarr API get's about 2 Million requests a day from about 10-40k users).

Nevertheless, how do you create the tmdb mirror? You can see my approach in the pdf above, and will release the script as well as daily (or hourly db dumps) in the future. Furthermore, would you like to help me build out the API V3? Not sure if you are familiar with laravel (the API is written using it), but I can always use a helping hand :)

**Comment by hr1232** [comment]
When I come home tonight I will give you the source.

**Comment by hr1232** [comment]
Here it is: https://ftp.heikorichter.name/tmdb/

The entire thing consists of 3 tiny scripts and a little database:
- cron-daily.txt is a crnjob running daily to import tmdb dumps
- cron-hourly.txt is a cronjb running hourly to do updates through the api
- movies.txt is the php script queried by Radarr
- movies.sql the database structure

**Comment by hr1232** [comment]
Also my problem is not so much about your API, in fact your API doesn't have anything to do with it as it concerns manual searches and not auto-import-lists.

My problem is the impossibility to use "the worlds history of film" as a basis for auto-import feature. I have a quite huge movie collection and I'd like to have **all** movies ever made (and also any future movies) as a basis for automatic imports. Also I like to watch Movies in their original language so the lists have to distinguish that and give me the possibility to import German movies with my profile 'German', English movies with my profile 'English' and so on. As long as those possibilites don't exist the best filter API is worth **nothing**. With my TMDB mirror one can automatically import **ANY** movie ever made as long as it fits the search criteria and automatically assign it to the correct language profile.

Also collections are automatically filled even if not all movies fit your search criteria. Think of The Matrix collection. First movie was great, second got worse, third was complete crap. But even if just the first one fit my criterea (lang=en und minvote=6), I still want to have the complete colletion without lowering my minvote parameter.

**Comment by ThePOO** [comment]
hr1232.     I'm testing the following with great success:

I chose the StevenLu list and modified as follows ...

Name:  hr1232
Enable Automatic Sync:  Yes
Add Movies Monitored:  Yes
Minimum Availablilty:  Announced
Quality Profile:  Custom
Folder:  M:\Movies
URL:   https://www.heikorichter.name/movies.php?lang=en&minyear=2013

This has worked great in my testing.

Will this resource be available for a very long time?

**Comment by hr1232** [comment]
That is just the way i use it (except for the minyear parameter as I want to have everything).

Initially I wrote that app for myself and therefor have no plans of shutting it down.

Be aware, that the initial API sync is at about 10% at the moment. It is planned to finish within 20 days so the database will increase by about 750000 movies Düring that time (including the porn movies which are filtered out by default). Depending on which filters you use, Radarr might fill up you harddrive very quickly......

**Comment by ThePOO** [comment]
Changes:

After testing I decided to implement two list --- the first will add and monitor non-adult selections, the second will add and NOT monitor adult selections.


Name: hr1232
Enable Automatic Sync: Yes
Add Movies Monitored: Yes
Minimum Availablilty: Announced
Quality Profile: Custom
Folder: M:\Movies
URL: https://www.heikorichter.name/movies.php?lang=en&collections=0&adult=0&minyear=2013


Name: hr1232 adult
Enable Automatic Sync: Yes
Add Movies Monitored: No
Minimum Availablilty: Announced
Quality Profile: Custom
Folder: M:\Movies
URL: https://www.heikorichter.name/movies.php?lang=en&collections=0&adult=1&minyear=2013

In both list items, above, I used the parameter collections=0, having seen the error in my ways (many added items I really didn't need).

I suspect there won't be too many items I'll be interested in after this 2013+ load (whew, lots more items than I imagined were out there) .... my database grew from about 700 items to 3,800+.     In all fairness I had a LOT of the items in my collection already so they will not be downloaded again.     But, there are hundreds of items I DID NOT have that are currently downloading.

When this finished this wave of activity I'll have quite a collection -- something for everyone.     Plex will has plenty to offer my family members.

Once all this catches up I will restrict my scrape of your list --- which, by the way, is incredibly fast!!!!! (whether your're allowing the full 28,000+ items or 120+ items the Json list comes over extremely fast.)  ---   I will change the minyear to a value of 2017 so I limit the file size I download from you.

What I'd like to see is a complete list of your parameters and use.

Would also like to see a new parameter that lets one select items based on the number of days prior to today's date ......    something like &daysbt=#####   (number of days before today)  so you could calculate the minimum date for the submitted request.     This way a sliding window of "X" days would always be evaluated day by day   <smile>.

Other than the &daysbt suggestion I can't really think of anything else to add ----- GREAT JOB FELLA !!!!!!!!!!         And, a hearty Thank You.

And, thanks to the folks providing this forum, otherwise I'd not have enhanced my Radarr so nicely with hr1232's offering.

P.S.:     Is there any other name I should/could be using for hr1232?

**Comment by hr1232** [comment]
You can use whatever name you want as it is just a cosmetic alias.

The filter adult=1 will not give you movies rated for adults. It will give you porn. By default it is deactivated because who wants Radarr to download 300000 porn movies? By default the list will just give you the 550000 non-porn movies.

**Comment by hr1232** [comment]
As the request made sense and needed only minimal changes I just changed the defaut behaviour.

If neither minyear nor maxyear are provided, the script will not hand out the entire database anymore. It will just give you the current year. The strain on my database and webserver don't really change but as many people have Radarr running on fairly low-powered systems it will not force them to parse 880000 movies unless they eplicitely request the have the entire file.

If one wants the entire Database in their Radarr installation just send something like _minyear=1900_ and you will still be able to do so.

**Comment by ThePOO** [comment]
yep, yep, and porn it was, when I was testing, as I figured out very quickly when Debbie does this and that, etc.     <smile>

But, MASTER (that be your cosmetic name now), I just saw your additional post about minyear ..... great change.

Any luck with something like &daysbt=##### parameter so your end can calculate a date before today offset?

**Comment by hr1232** [comment]
Making the current year the default parameter for minyear is the best solution I can offer for that request right now. In the current database layout there is no complete publishing date, it's just the year. So filtering movies by a complete date is not possible. It also woudn't be practical as the minimal savings in bandwidth would be burnt up by calculation time. This will actually slow down the process of building the json file so it doesn't really help. It's far easier just to hand out the entire year and let Radarr do the rest.

**Comment by ThePOO** [comment]
Hey!     Now I understand, given all you have to work with is year.     And so it is, minyear=2016 right now and I'll be happy with that.      I turned everything loose on my system with a 2013 minyear and the system is still searching indexers .... taking a loooong time, as I have 13 indexers.     So far over 500 have been queued for download.      I sure am glad I have a lot of capacity --- right now 76TB.

**Comment by galli-leo** [comment]
> But I think it will not give you accurate updates for the popularity parameter. This one doesn't only change with updates but also takes into account the number of website accesses and API calls. Furthermore it decreases by itself over time. I think it's best to work with both systems. If a movie gets changed it is updated through changes api, but one should also do regular queries for mvies that don't change that often...

Yeah popularity get's ingested with the daily id dump (that contains up to date popularity info for all movies).

> Also my problem is not so much about your API, in fact your API doesn't have anything to do with it as it concerns manual searches and not auto-import-lists.
> 
> My problem is the impossibility to use "the worlds history of film" as a basis for auto-import feature. I have a quite huge movie collection and I'd like to have all movies ever made (and also any future movies) as a basis for automatic imports.

Adding a /movies endpoint that returns all movies in the db (paged obviously and with the ability to filter like all other endpoints) is pretty trivial. So gonna definitely add that.

> Also I like to watch Movies in their original language so the lists have to distinguish that and give me the possibility to import German movies with my profile 'German', English movies with my profile 'English' and so on.

I plan on adding a "Original" language that you can set for your profiles or custom formats. This way Radarr would only download (or prefer depending on how you have set it up) the original language of the film. That would extremely simplify your setup.

> Also collections are automatically filled even if not all movies fit your search criteria. Think of The Matrix collection. First movie was great, second got worse, third was complete crap. But even if just the first one fit my criterea (lang=en und minvote=6), I still want to have the complete colletion without lowering my minvote parameter.

That's a great idea and probably also easy to add to the API. So gonna probably add that.

Also regarding minyear=1900, be careful, there are some movies release in 1840 IIRC (not sure if they are on TMDB).

**Comment by ThePOO** [comment]
@hr1232  (MASTER)    I'm really liking what your list has provided me ... huge thank you.  

current use:   https://www.heikorichter.name/movies.php?lang=en&collections=1&adult=0&minyear=2016&maxyear=2018

minyear is filling in huge gaps and missing items ... and keeping me fed with "new arrivals" for older titles.
maxyear had to be defined to avoid a lot of "yet to be" items that will come my over time.

My thoughts are now that I will bump up minyear and maxyear by one year about January 1 each new year.

==============================

@galli-leo    It would be nice to have an option for Radarr to monitor my movies storage and when I delete a movie that the associated item in Radarr be removed from the library and added to the exclusions list.     It would further be nice to have an option in Radarr that once a movie has its cutoff satisfied that the title be removed from the library and added to the exclusions list.

In all fairness you have the "Clean Library Level" option but no clear information about the ramifications of the options use.    I can guess at some, but some clear explanation would be great.    I just haven't had the time to, frankly, play with that option yet.

**Comment by galli-leo** [comment]
@ThePOO Clean library level is for when movies are deleted from your lists, not when deleted from storage. Also, not sure why you would remove a movie once cutoff is reached, Radarr won’t download that one anymore.

Regarding, removal of movie from library on file / folder deletion, that is something that is planned.

**Comment by hr1232** [comment]
@ThePOO @galli-leo 
Removal on delete from storage is already there. It's called 'Ignore Deleted Movies'. You can find it on the Media Management tab in your settings.

@ThePOO 
There's no need to set maxyear=2018. Just set 'Minimum Availability' in the list properties to 'Physical/Web'. That way all those future movies are added to Radarr but they will be ignored until their DVD/BluRay release date. If you want screeners you can also set that option to 'In Cinemas'.

**Comment by hr1232** [comment]
@ThePOO 

Done, your request from 4 days ago can be done by setting these options:

1. Activate the Option 'Ignore Deleted Movies' on Media Management tab
2. Add list /movies.php?lang=en&collections=1&adult=0&maxage=2
3. Set Option 'Library Cleanup Level' to 'Remove & Delete Files' on Lists tab
4. To keep the really good ones add a second list: movies.php?lang=en&collections=1&adult=0&minyear=0&minvote=8
5. Change minyear and minvote in the second list to whatever values you want (or replace minyear by something like maxage=10 to delete the really good ones at a later date).
6. Of course you can stack as many lists as you want - e.g. all movies of the last 2 years, everything made in the last 10 years and voted 6 or above, everything ever made and voted 8 and above........

**Comment by ThePOO** [comment]
@hr1232 

I'm getting "Internal Server Error" when attempting 
https://www.heikorichter.name/movies.php?lang=en&collections=0&adult=0&maxage=1
It looks like this has been the case for several days?

I hope everything is ok with your server and becomes available again --- I miss your fine list.

**Comment by hr1232** [comment]
Sorry about the outage I had a few toubles moving my site to Cloudflare and didn't really notice that the list was also impacted. Things should be working again.

**Comment by ThePOO** [comment]
Working great!    Love the list --- Here's to it never going away!    Thank you for creating and maintaining the list ....

**Comment by hr1232** [comment]
List is Wirkung fine, just checked it.

**Comment by ThePOO** [comment]
I just checked and, indeed, the list is working great.     
Is there a time frame I should avoid when the servers may be doing maintenance or something?

**Comment by ThePOO** [comment]
@hr1232

Here is what I'm using in my list:

name  hr1232
enable automatic sync  yes
add movies monitored  yes
minimum availability  physical/web
quality profile  custom
folder  m:\movies\
url  https://www.heikorichter.name/movies.php?lang=en&collections=0&adult=0&maxage=1

I checked my logs and noticed this in my log:

Commandexecutor           Error occurred while executing task NetImportSync: Value cannot be null.
 Parameter name: input   

Nothing from the list appears to be imported any longer, just wondering what's up with this.

Thanks.

**Comment by hr1232** [comment]
The list is working and hasn't been changed for quite some time.

Maybe something was changed in Radarr....

**Comment by hr1232** [comment]
Just checked, it's working fine for me. I'm using Radarr version 0.2.0.1120.

**Comment by hr1232** [comment]
Nice too hear that it's working again for you, too.

About those SkyHookProxy messages:
Those happen whenever movies were deleted from TMDB and my db mirror hasn't caught uo with that change yet. People often add duplicates of existing movies and my mirror will import them. As detetions are only mirrored once/day, there is a chance that the list data contains movies that are no longer available on TMDB. Just ignore those messages, they will solve themselves.

https://github.com/Radarr/Radarr/issues/1182

**Comment by ThePOO** [comment]
Way Cool !!!!      Stuff I can ignore ... I'm all up for that.      Yay!
Good to know about the deletions only happening once a day.     I will now set my NetImport interval to 1440 to hopefully get timely items and also avoid the duplicates --- a win-win I say.
Hey!    Thanks again.     
Oh, by the way, how many are using your list these days, if that's appropriate to share?

**Comment by timc6896** [comment]
I just stumbled across this and I have to say, it is pretty amazing :)  Works really well!

**Comment by ThePOO** [comment]
Exact-o-mundo!!!!!    The list works perfectly ... still using it every day.     Enjoy ..... MANY THANKS TO HR1232

**Comment by etetlow** [comment]
Hey. Stumbled upon this whilst looking for more info on how to bulk add movies using the api. But this solved my problem and put me onto the best endpoint in existence.

I was wondering if there was any way genre could be added to the filters. Reason being is that I'm looking for the top 50 films of each year for the last 20 years. At the moment I'm using minvote=8 but I'm finding that a lot of the results are music videos when I'm looking strictly for movies. Maybe not even genre, but category as in, Music Video, Documentary, Cinema Movie etc.

**Comment by Qstick** [comment]
Closing this as this list works with customer StevenLu on v3 and there is nothing else we really need to do from a Radarr perspective.
