### ISSUE TITLE
.partial~ files, and other problems with MovieFileMovingService

### ISSUE THREAD

**Issue by rbhalla** [Radarr/Radarr#2714]
**Radarr Version:**
0.2.0.995
**Mono Version:**
5.10.1.20 (tarball Thu Mar 29 10:44:58 UTC 2018)

I'm running radarr in a docker container, the folder it's referencing is a unionfs mount. Both the downloads and movies folder are writable/readable. 

I've seen references to these problems elsewhere with the issue eventually going away, but I've seen it reoccur for many movies now on the latest version in the last hour. The two problems I've seen occur when a download has finished:

1) .partial~ files
2) hanging `Check For Finished Download` (where 10min+ with the refreshing icon still spinning)

I've seen 2 error messages so far:

```
DiskTransferService: Failed to completely transfer [/downloads/spider-man.homecoming.2017.1080p.bluray.x264-sparks.mkv] to [/movies/Spider-Man Homecoming (2017)/Spider-Man Homecoming 2017.mkv], retrying [1/2]
```

This first spammed the logs with a fail message. After a restart I got this message once, and then it worked on the second pass (with a hard link).

I tried it for a second movie, and got a different error (same result, .partial~ files)

```
 Couldn't import movie /downloads/Logan.2017.1080p.BluRay.DD5.1.x264-DON/Logan.2017.1080p.BluRay.DD5.1.x264-DON.mkv
radarr     |
radarr     | [v0.2.0.995] System.IO.IOException: Could not create file "/downloads/Logan.2017.1080p.BluRay.DD5.1.x264-DON/Logan.2017.1080p.BluRay.DD5.1.x264-DON.mkv" or "/movies/Logan (2017)/Logan 2017.mkv.partial~". File already exists.
radarr     |   at System.IO.File.Copy (System.String sourceFileName, System.String destFileName, System.Boolean overwrite) [0x00192] in <65984520577646ec9044386ec4a7b3dd>:0
```

I shutdown radarr, removed any files that existed in the /movies folder and restarted. Then I got this:

```
radarr     | [Error] MovieFileMovingService: Unable to create directory: /movies/Logan (2017)
radarr     |
radarr     | [v0.2.0.995] System.IO.IOException: Lock violation on path /movies/Logan (2017)
radarr     |   at System.IO.Directory.CreateDirectoriesInternal (System.String path) [0x0005e] in <65984520577646ec9044386ec4a7b3dd>:0
radarr     |   at System.IO.Directory.CreateDirectory (System.String path) [0x0008f] in <65984520577646ec9044386ec4a7b3dd>:0
radarr     |   at NzbDrone.Common.Disk.DiskProviderBase.CreateFolder (System.String path) [0x00048] in C:\projects\radarr-usby1\src\NzbDrone.Common\Disk\DiskProviderBase.cs:203
radarr     |   at NzbDrone.Core.MediaFiles.MovieFileMovingService.CreateFolder (System.String directoryName) [0x0007a] in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\MovieFileMovingService.cs:223
radarr     |
```

While it says it failed to create the folder, the folder did actually create, a .partial~ file exists inside it. At the this time radarr is using a lot of cpu but not saying anything in logs. Task has been running for about 20min.

As a final attempt, I shutdown radarr, deleted files in /movies (not /downloads) and started back up. Logs are quiet (no errors about directory creation) and the task is still running. It's been about 30min since last execution. The folder was recreated with the .partial~ inside, but nothing in logs to indicate that's what happened. These are the last lines in the log:

```
radarr     | [Info] OwinHostController: Listening on the following URLs:
radarr     | [Info] OwinHostController:   http://*:7878/radarr/
radarr     | [Info] OwinHostController:   http://*:7878/
radarr     | [Info] NancyBootstrapper: Starting NzbDrone API
```

Any help here is much appreciated.

**Comment by glassbase** [comment]
.partial file is the movie being moved (copied) to movie folder. You can watch the partial file get larger by refreshing folder and checking file size or using command: ls-alh (on Linux). After the copy completes it renames it and removes the .partial. Check finished downloads is running because it is copying the newly download movie file over as a part of its process. Continues to run until movie copy finishes. Depending on file size, can take quite awhile to complete the copy and use lots of CPU

**Comment by rbhalla** [comment]
Apologies for the late reply, you're right. A combination of unionfs and slow disk meant the long delays I was seeing was purely IO bound. I've since moved away from unionfs to use hardlinks, and it's much better. Thanks for your help!
