### ISSUE TITLE
Movies not being added to download. 

### ISSUE THREAD

**Issue by 07stuntar1** [Radarr/Radarr#2716]
I have added a bunch of movies to my download list. But when the movie comes available it doesn’t add to my download client to be downloaded. 
I check manually download and there is no exlimation ! Next to the files found. So min requirements are being met. There are more then 1 seeder and if I manually download it works fine. I can’t figure out why.

**Comment by 07stuntar1** [comment]
Update today may have fixed it. Everything started downloading after update

**Comment by dawtmaytrikx** [comment]
I started having this issue last night, a few hours after updating to the newest version from v0.2.0.910. Here's what I see in the logs: https://pastebin.com/raw/DZBEJcyE

Happens with rtorrent, NZBGet seems to be working fine.

**Comment by dawtmaytrikx** [comment]
I fixed my issue by setting MONO_TLS_PROVIDER=legacy on my docker container: https://github.com/linuxserver/docker-radarr/issues/17
