### ISSUE TITLE
v0.2.0.1066 broke the web gui 18 hours ago (9:30pm eastern 03-17-2018)

### ISSUE THREAD

**Issue by ThePOO** [Radarr/Radarr#2718]
Radarr Pre-Release v0.2.0.1066 updated last night about 18 hours ago (9:30pm eastern 03-17-2018) and now the web gui just displays the dancing-dots endlessly?

Radarr is still checking for movies and scheduling them for download, etc. ..... it just appears that the web gui is broken.

It would be my guess that the software will be repaired and another update fix the issue ------ and THANKS TO THE DEVELOPERS for a great program!

**Comment by galli-leo** [comment]
You need to clear cookies in your browser (or local appdata if you know what that is). If you want to be Sorry, forgot to add a safety feature, will try to push a hotfix in the next 24 hours.

For future reference, try including a debug log, else the issue will be closed.
