### ISSUE TITLE
A huge thank you to Leonardo Galli

### ISSUE THREAD

**Issue by ThePOO** [Radarr/Radarr#2720]
Leonardo ... thank you for the informative email you sent me (#2718).     Sorry I didn't provide all the needed information.      Nonetheless, you indicated you will be pushing a hotfix in the next 24 hours --- YAY!       I'm sure you are a very busy person and I highly appreciate your efforts --- **_THANKS_**.

**Comment by galli-leo** [comment]
Thank you!
