### ISSUE TITLE
Option {Clean.Title} didn't remove accent

### ISSUE THREAD

**Issue by Algedi13** [Radarr/Radarr#2722]
Hello,

For the Movie Folder Format it's the same thing there is always an accent even with the option {Movie CleanTitle}. "é" is not ASCII basic character. It should simply add option for remove no ASCII and replaces with ASCII basic.

```
Version 0.2.0.1067 (docker)
Mono Version 5.10.1.20 (tarball Thu Mar 29 10:44:58 UTC 2018)
```

Related issue #1804 (having had no answer i redo an issue)

**Comment by Qstick** [comment]
Reopened #1840, close this as dup.
