### ISSUE TITLE
Omgwtfnzbs api categories search need to be fix

### ISSUE THREAD

**Issue by Kartikai** [Radarr/Radarr#2724]
some of the categories for movies for API search for omgwtfnzbs are missing 
right now it only search on catid=15,16,17
but need to search on all of those:

All = movie
SD = 15
HD = 16
UHD = 31
FullBR = 35
DVD = 17
Other = 18

Nead to change line #32 in OmgwtfnzbsRequestGenerator.cs
for something like this :

url.AppendFormat("{0}?catid=movie,15,16,17,31,35,18&user={1}&api={2}&eng=1&delay={3}", BaseUrl, Settings.Username, Settings.ApiKey, Settings.Delay);

Radarr Ver. 0.2.0.1067

**Comment by Qstick** [comment]
As a workaround you can use the newznab indexer preset with OMG now that they have a newznab compliant API up.
