### ISSUE TITLE
Radarr stopped working with DS after last update (Error 119)

### ISSUE THREAD

**Issue by king8084** [Radarr/Radarr#2730]
radarr stopped working with last update on Synology (it wont commuincate with DS)

Unable to communicate with DS. Failed to get serial number. Reason: 119 - Unknown error

**Comment by king8084** [comment]
well fuck...

i tried to "stop" the app then "run" it again, and radarr refuses to run anymore

**Comment by Qstick** [comment]
This may have been from https://github.com/Radarr/Radarr/pull/968. I can take a look.

**Comment by king8084** [comment]
restarting synology seems to fix it so far...
