### ISSUE TITLE
API: Search by Movie name endpoint

### ISSUE THREAD

**Issue by imran0** [Radarr/Radarr#2731]
Similar to Sonarr's [SeriesLookup](https://github.com/Sonarr/Sonarr/wiki/Series-Lookup) callout, can we have a MovieLookup endpoint in Radarr? 

I'm not sure how Radarr searches for movies in its search, I am trying to build a companion app to Radarr, if this could be made available via the API that would be great.

**Comment by galli-leo** [comment]
We already have that endpoint (/movies/lookup or /movie/lookup). It’s just not documented yet. Feel free to add the documentation yourself.

**Comment by lamarios** [comment]
I've been using this endpoint for a while, but it stopped working. 
https://myserver/api/movies/lookup?apikey=myapikey&term=star+wars

Getting the following response:
{
  "message": "NotFound"
}

**Comment by galli-leo** [comment]
@lamarios Yeah, we cleaned up the api a while back, and transitioned all endpoints to /movie instead of /movies. Should probably have mentioned that somewhere.

**Comment by lamarios** [comment]
I’ve added the documentation to the wiki.  In API:Movie Lookup
