### ISSUE TITLE
radarr packaged as snap

### ISSUE THREAD

**Issue by Alculete** [Radarr/Radarr#2735]
I had few issues installing Radarr last time that I opted to use [AtoMiC-ToolKit](https://github.com/htpcBeginner/AtoMiC-ToolKit) because of some dependencies not satisfied.
Snap packages allows applications to have all dependencies inside the package reducing the work the end user would have to install or update the app.
Is there any change to package Radarr as snap?
By the way you are doing a great job

**Comment by galli-leo** [comment]
Probably not from us. We will setup a ubuntu repo when version 1.0 is released. If you don't want to have a hassle with dependencies you can use docker for now.
