### ISSUE TITLE
Unable to parse movie info from path /mnt/media/transmission/complete/movies-fr/Transformers - L'âge de l'Extinction [1080p][True HD - AC3][VO-VFF].mkv

### ISSUE THREAD

**Issue by Firemad03** [Radarr/Radarr#2737]
I got a: Unable to parse movie info from path /mnt/media/transmission/complete/movies-fr/Transformers - L'âge de l'Extinction [1080p][True HD - AC3][VO-VFF].mkv

I think it's because of the ' . In french the ' can be there in the title so maybe that is the cause of the problem ? Or maybe the character for the a ?

Build: 0.2.0.1067

**Comment by galli-leo** [comment]
Movies need a year somewhere in the name to be correctly parsed. You can enable lenient mapping, but I wouldn't recommend it.
