### ISSUE TITLE
Radarr forgets -data parameter on restarts

### ISSUE THREAD

**Issue by Vorror** [Radarr/Radarr#2740]
Currently I'm running 2 Radarr instances to keep my 1080p and 4k libraries separate. I'm using the `-data`  parameter to manually specify the data directory for each instance. Everything is working great  except when a Radarr instance has to restart(either via the button or update). 

Issue:

When Radarr restarts it doesn't remember the -data directory that was passed in from the previous launch. Which can cause any number issues since it's pointing to the wrong directory

**Comment by Vorror** [comment]
Actually I thought I had both running but it seems radarr detects itself as running already and doesn't allow another instance to run. Maybe the already running check should also check if the data directories are different?

**Comment by galli-leo** [comment]
Can you post the exact commands you are using as well as some logs?
