### ISSUE TITLE
[Feature Request] Filter Movies after list import

### ISSUE THREAD

**Issue by crhammock** [Radarr/Radarr#2744]
As I use Radarr more and more I find I have multiple lists setup to grab different movies from different sites.  Each site supports its own filters like genre, rating votes etc.  However they are not all consistent.

Would it be possible to add filters to the imported movie list which removes movies which don't match the filter.  This would allow movies to be imported from Trakt, IMDB and RSS lists but only for example movies with a TMDB rating of over 5.0 and over 100 votes with genre of Action to be kept and downloaded?

**Comment by thedelph** [comment]
Can this be re-opened?
