### ISSUE TITLE
Filter state is not applied on the table after refreshing the ui.

### ISSUE THREAD

**Issue by rubencausyn** [Radarr/Radarr#2745]
**Description:**
When reloading the overview The filter buttons state is correct but the filter state is not always correctly applied on the results table and shows all movies.

**Radarr Version:**
Radarr Ver. 0.2.0.1067
develop

**Mono Version:**
Mono Version
5.8.0.108 (tarball Sat Feb 24 09:55:00 UTC 2018)

**Comment by JesseWV** [comment]
I'm having the same issue. I have movies sorted by descending (newest on top) Cinema Date. After closing the browser and reopening or refreshing the page they are instead sorted by ascending (oldest on top) Cinema Date. I should note that the sort direction arrow still indicates it's in descending order but it's just not. Clicking the sort order again changes the arrow to show that it's ascending, which it still is, and clicking it again finally correctly sorts in descending order. This has been "bugging" me for quite some time. :)

**Comment by toddrob99** [comment]
Similar issue here. I keep it sorted by Date Added descending, to see what's been added most recently. When I refresh the page, it has the correct 10 (most-recently-added) movies listed, but they are in reverse order. I have to click the column header twice to get it to sort properly.

Radarr Ver. 0.2.0.1067
develop

**Comment by toddrob99** [comment]
This issue still exists in version 0.2.0.1120. The correct 10 items are listed, but in the reverse order. Clicking the column header twice puts them in the proper order, and then with a page refresh they are backward again.
