### ISSUE TITLE
unable to add pixar short films

### ISSUE THREAD

**Issue by AcidRain999** [Radarr/Radarr#275]
i tried to add a bunch of the pixar movies to radarr, and a lot show up missing even though they are there. it looks like radarr is expecting the movie to be longer than it is. the file is complete and plays properly (just confirmed before posting, has complete credits on it aswell)

here is the log file to go with it

17-1-14 23:22:04.4|Debug|Api|[GET] /api/log/file: 200.OK (12 ms)
17-1-14 23:22:04.4|Debug|Api|[GET] /api/log/file: 200.OK (6 ms)
17-1-14 23:22:04.5|Debug|Api|[GET] /api/log/file/radarr.debug.txt: 200.OK (6 ms)
17-1-14 23:22:06.5|Debug|Api|[GET] /api/log/file: 200.OK (4 ms)
17-1-14 23:22:06.5|Debug|Api|[GET] /api/log/file/radarr.debug.txt: 200.OK (6 ms)
17-1-14 23:22:08.5|Debug|SabnzbdProxy|Url: http://localhost:2004/api?mode=queue&start=0&limit=0&apikey=(removed)&output=json
17-1-14 23:22:08.5|Debug|SabnzbdProxy|Url: http://localhost:2004/api?mode=history&start=0&limit=30&category=movies&apikey=(removed)&output=json
17-1-14 23:22:08.6|Debug|Api|[GET] /api/queue??sort_by=timeleft&order=asc: 200.OK (5 ms)
17-1-14 23:22:13.9|Debug|Api|[GET] /api/movie??sort_by=this&order=desc: 200.OK (984 ms)
17-1-14 23:22:14.9|Debug|Api|[POST] /api/command: 201.Created (91 ms)
17-1-14 23:22:15.0|Info|RefreshMovieService|Updating Info for Air Mater
17-1-14 23:22:15.2|Debug|RefreshMovieService|Finished movie refresh for Air Mater
17-1-14 23:22:15.2|Info|DiskScanService|Scanning disk for Air Mater
17-1-14 23:22:15.2|Debug|DiskScanService|Scanning '/storage/movies/Pixar/Air Mater/' for video files
17-1-14 23:22:15.2|Debug|DiskScanService|1 video files were found in /storage/movies/Pixar/Air Mater/
17-1-14 23:22:15.2|Debug|DiskScanService|[tt2100093][Air Mater] Cleaning up media files in DB
17-1-14 23:22:15.2|Debug|ImportDecisionMaker|Analyzing 1/1 files.
17-1-14 23:22:15.2|Debug|Parser|Parsing string 'Air.Mater.(2011).mkv'
17-1-14 23:22:15.2|Debug|Parser|Movie Parsed. Air Mater - 0 
17-1-14 23:22:15.2|Debug|Parser|Language parsed: English
17-1-14 23:22:15.2|Debug|QualityParser|Trying to parse quality for Air.Mater.(2011).mkv
17-1-14 23:22:15.2|Debug|Parser|Quality parsed: HDTV-720p v1
17-1-14 23:22:15.2|Debug|Parser|Release Group parsed: 
17-1-14 23:22:15.2|Debug|ImportDecisionMaker|Size: 288829799
17-1-14 23:22:15.2|Debug|VideoFileInfoReader|Getting media info from /storage/movies/Pixar/Air Mater/Air Mater (2011).mkv
17-1-14 23:22:15.3|Debug|FreeSpaceSpecification|Skipping free space check for existing episode
17-1-14 23:22:15.3|Debug|VideoFileInfoReader|Getting media info from /storage/movies/Pixar/Air Mater/Air Mater (2011).mkv
17-1-14 23:22:15.3|Debug|DetectSample|[/storage/movies/Pixar/Air Mater/Air Mater (2011).mkv] appears to be a sample. Runtime: 00:05:12.9800000 seconds. Expected at least: 360 seconds
17-1-14 23:22:15.3|Debug|NotUnpackingSpecification|/storage/movies/Pixar/Air Mater/Air Mater (2011).mkv is in series folder, skipping unpacking check
17-1-14 23:22:15.3|Debug|ImportApprovedMovie|Decisions: 1
17-1-14 23:22:15.3|Info|DiskScanService|Completed scanning disk for Air Mater
17-1-14 23:22:15.7|Error|EventAggregator|ExtraService failed while processing [MediaCoversUpdatedEvent]

[v0.2.0.134] System.NullReferenceException: Object reference not set to an instance of an object
  at NzbDrone.Core.Extras.ExtraService.Handle (NzbDrone.Core.MediaCover.MediaCoversUpdatedEvent message) <0x40d7a750 + 0x00030> in <filename unknown>:0 
  at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent] (NzbDrone.Core.Messaging.Events.TEvent event) [0x000c3] in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Events\EventAggregator.cs:56 

17-1-14 23:22:15.7|Error|EventAggregator|SeriesModule failed while processing [MediaCoversUpdatedEvent]

[v0.2.0.134] System.NullReferenceException: Object reference not set to an instance of an object
  at NzbDrone.Api.Series.SeriesModule.Handle (NzbDrone.Core.MediaCover.MediaCoversUpdatedEvent message) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Api\Series\SeriesModule.cs:239 
  at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent] (NzbDrone.Core.Messaging.Events.TEvent event) [0x000c3] in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Events\EventAggregator.cs:56 

17-1-14 23:22:16.6|Debug|Api|[GET] /api/health: 200.OK (5 ms)
17-1-14 23:22:16.6|Debug|Api|[GET] /api/health: 200.OK (9 ms)
17-1-14 23:22:16.6|Debug|Api|[GET] /api/diskspace: 200.OK (28 ms)
17-1-14 23:22:16.6|Debug|Api|[GET] /api/diskspace: 200.OK (13 ms)
17-1-14 23:22:17.7|Debug|Api|[GET] /api/log??page=1&pageSize=50&sortKey=time&sortDir=desc: 200.OK (13 ms)
17-1-14 23:22:17.7|Debug|Api|[GET] /api/log??page=1&pageSize=50&sortKey=time&sortDir=desc: 200.OK (5 ms)
17-1-14 23:22:19.3|Debug|Api|[GET] /api/log/file: 200.OK (11 ms)

**Comment by galli-leo** [comment]
What's the smallest runtime of such a movie? Because the specs decide what a sample based on if the runtime does not exceed 6 minutes.

**Comment by AcidRain999** [comment]
they average around 5 min. i can make a list of all the ones i have that didnt get detected if you would like

**Comment by dawnerd** [comment]
Would it be possible to pull the runtime from imdb/moviedb/wherever and check against that?

**Comment by galli-leo** [comment]
@dawnerd The runtime is already pulled from the movie db. Should be as easy as adding a few lines to check for runtime below 20 minutes and then lower the sample runtime.
