### ISSUE TITLE
Indexer Name in Activity Page

### ISSUE THREAD

**Issue by redxtech** [Radarr/Radarr#2750]
Would it be possible to add a tab on the activity page to see what indexer the movie currently downloading was grabbed from?

Right next to the quality option would be perfect in my opinion.

Thanks,
Gabe.

**Comment by YipYup** [comment]
Even better if it can be nzbHydra aware, capable of displaying the indexer when used via  [nzbHydra 2](https://github.com/theotherp/nzbhydra2)
