### ISSUE TITLE
Feature Request - Multiple trackers

### ISSUE THREAD

**Issue by IllMethods** [Radarr/Radarr#2751]
If possible, which would be good for people like me who have multiple private trackers, I would like to see when Radarr downloads a release that is on multiple trackers to add the trackers that release is on to each download. That way it will download and seed to multiple trackers. Over all it should see your upload ratio go up on each tracker the release is on

**Comment by galli-leo** [comment]
So you want radarr to add the other trackers to the torrent file?

**Comment by IllMethods** [comment]
yes, if it finds the same release on several trackers, if possible

**Comment by hotio** [comment]
So, you wanna turn radarr into a private tracker ratio pumper?

**Comment by IllMethods** [comment]
no, just have it put all the trackers into the same torrent when it finds the same release on more than one tracker

**Comment by galli-leo** [comment]
We won’t add support for this, as torrent sites usually arent to keen on us editing the torrent file. Additionally, it could have a security risk, as it may expose your private key of one trackers to others.
