### ISSUE TITLE
Radarr rejects release because it "will only be considered available 0 days after PreDB" although on PreDB

### ISSUE THREAD

**Issue by theotherp** [Radarr/Radarr#2752]
Version 0.2.0.998. I know that "PreDB" as minimum availability is not recommended according to https://github.com/Radarr/Radarr/wiki/Minimum-Availability. But I only found that out today because I was wondering why some movies were not downloaded with some releases already out. I switched to "Announced" in the meantime.

I enabled debug (and trace logging) and ran the RSS sync and got this line in the debug log:
`18-5-2 12:38:43.9|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] Movie [tt1234567][Some movie (2018)] will only be considered available 0 days after PreDB`

But I know for a fact that that release had been on https://predb.me for at least 10 hours. My availability delay is set to 0.

Is this expected behavior? I could try setting the delay to -1 but that seems like a dirty hack.

Thanks.

**Comment by galli-leo** [comment]
Read the wiki page again. Predb is the same as physical web now, meaning an entry on predb means nothing. Radarr looks at the bluray release date.

**Comment by theotherp** [comment]
Shit, sorry... I actually managed to read the beginning and end of that paragraph and skipped the middle...

**Comment by galli-leo** [comment]
No worries, support for PreDB will come back with API v3, but thats still some ways out.
