### ISSUE TITLE
Feature: Hide external link buttons

### ISSUE THREAD

**Issue by JesseWV** [Radarr/Radarr#2757]
Please add the ability to hide any of the following buttons under the movie posters.

Trakt, The Movie DB, IMDB, Trailer

**Comment by JesseWV** [comment]
Issue still exists and it really clutters the grid UI layout. Recommend making one row of clickable icons under each movie poster. As shown in the example below, this would look really nice.

Alternatively just adding toggle check boxes to enable each button in Settings/UI would also work.

Example: 
<img src="https://i.ibb.co/SwnNCHL/Radarr-Movie-Poster-Icons.jpg" alt="Radarr-Movie-Poster-Icons" border="0">

**Comment by galli-leo** [comment]
@JesseWV Agreed, should come with the new UI.
