### ISSUE TITLE
Issue with file renaming

### ISSUE THREAD

**Issue by alxlaxv** [Radarr/Radarr#2759]
Hello,

I have a weird behaviour using Radarr times to times.
I have set the Media Renaming to TRUE because I only want the folder to be renamed.
The standard movie format is set to {Original Title} because I want the title unchanged.

BUT when the movie imported by Radarr is part of a folder, Radarr rename the file with the same name as the folder instead of keeping it untouched.

**Example:**
Possessions.2011.FRENCH.1080p.BluRay.x264-LOST/lost-poss.1080p.mkv
**is imported like that:**
Possessions (2012)/Possessions.2011.FRENCH.1080p.BluRay.x264-LOST.mkv
**instead of** 
Possessions (2012)/lost-poss.1080p.mkv

I have then tried to delete the imported file and made a manual import... and now it's correct.

What can I do to have it correctly done by the recurrent task automatically?

Thanks!!

**Comment by galli-leo** [comment]
Original Title uses the nzb title. If you want the original filename, use original filename
