### ISSUE TITLE
API method for Queue like Sonarr?

### ISSUE THREAD

**Issue by JosephShenton** [Radarr/Radarr#2761]
**Description:**
Hi, I am building a tool to manage Sonarr and Radarr in one and I really need to get the current Queue from Radarr. Sonarr already does this so I assumed Radarr would as well.

**Radarr Version:**

2.0.0.5163

**Mono Version:**

5.8.1.0

**Comment by galli-leo** [comment]
We already have such a method. It's probably just not documented on the wiki. It should be very similar to the one in Sonarr.
