### ISSUE TITLE
Radarr adds TV shows via imdb list

### ISSUE THREAD

**Issue by petwri** [Radarr/Radarr#2763]
**Description:**

I have the issue, that Radarr adds TV shows from my imdb watchlist. For instance, I have the show tt5189670 in my watchlist, which Radarr then adds as if it was a movie. Definitely undesired behaviour.

**Radarr Version:** 
0.2.0.1067
**Mono Version:**
5.10.1.20

**Comment by galli-leo** [comment]
This is an issue with The Movie DB. It seems to have an entry for a movie for that imdb id. Nothing we can do. You can request the deletion of that movie over on their website themoviedb.org
