### ISSUE TITLE
Torrent search for movie returning incorrect movies

### ISSUE THREAD

**Issue by onedr0p** [Radarr/Radarr#2766]
Looks like for manually searching for a movie it's not using imdbid and instead returning recently uploaded movies. I've noticed this for PassThePopcorn and AwesomeHD trackers. Usenet indexers and Jackett indexers are working as expected. This just started happening recently, anyone else notice this?

@galli-leo did something happen to `searchParameters` this recently?

```csharp
            if (searchParameters != null)
            {
                yield return new IndexerRequest($"{Settings.BaseUrl.Trim().TrimEnd('/')}/searchapi.php?action=imdbsearch&passkey={Settings.Passkey.Trim()}&imdb={searchParameters}", HttpAccept.Rss);
            }
            else
            {
                yield return new IndexerRequest($"{Settings.BaseUrl.Trim().TrimEnd('/')}/searchapi.php?action=latestmovies&passkey={Settings.Passkey.Trim()}", HttpAccept.Rss);
}

**Comment by galli-leo** [comment]
@onedr0p What branch are you using and what version? PTP works fine for me on latest develop.

**Comment by onedr0p** [comment]
Restarted my docker container and everything is well... Very odd. I didn't even upgrade my docker image.
