### ISSUE TITLE
BUG: Movies are being stored with year (0)

### ISSUE THREAD

**Issue by majora2007** [Radarr/Radarr#2772]
**Description:**
I manually add a movie that has not yet released. The year is shown as 2018. The movie downloads once it is released. Radarr creates the new folder as Movie (0)/ instead of Movie (2018).

Even if I rename this manually, Radarr will keep an eye out for a new release and recreate the (0) folder with the newly downloaded file. 

See image here:
![image](https://user-images.githubusercontent.com/735851/39956660-be147eec-55aa-11e8-8938-cb2a86a9d88b.png)

**Radarr Version:** Nightly

**Mono Version:** N/A

**Debug Logs:** https://pastebin.com/smTbaXtb

**Comment by galli-leo** [comment]
The problem is either the way you added the film (some programs don't send the year with the initial add request) or that it didn't have a release date when you added it. Radarr set's the folder to use from the start. You can change it using dynamic paths though.

**Comment by majora2007** [comment]
When I added the movie, at the time, there was no year aka 0. However, the metadata changed and when downloaded and processed by Radarr, the metadata showed the correct year. Shouldn't Radarr have created the folder with the correct year when it was processing? Or does Radarr not check with the metadata provider for new information after adding?
