### ISSUE TITLE
Feature Request - Regex support in restrictions

### ISSUE THREAD

**Issue by Jorman** [Radarr/Radarr#2775]
Hi, is possible to have this function in Radarr?

Maybe like Sonarr version, see here for more about this
https://github.com/Sonarr/Sonarr/pull/2361

Thank you

Jorman

**Comment by galli-leo** [comment]
Already implemented with custom formats on that branch.

**Comment by Jorman** [comment]
Ok thank you.
Actually I'm on develop branch, I don't know the difference between those two branch.

My native language is not English so do you think that custom format is a better choice?

J
