### ISSUE TITLE
404 loading index

### ISSUE THREAD

**Issue by OverlordQ** [Radarr/Radarr#2777]
**Description:**
Trying to load web UI returns 404.

**Radarr Version:** Version 0.2.0.1067

**Debug Logs:**

Info] Router: Application mode: Interactive 
[Debug] Router: Console selected 
[Info] MigrationLogger: *** Migrating data source=C:\ProgramData\Radarr\nzbdrone.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 *** 
[Debug] MigrationLogger: Took: 00:00:00.2148638 
[Info] MigrationLogger: *** Migrating data source=C:\ProgramData\Radarr\logs.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 *** 
[Debug] MigrationLogger: Took: 00:00:00.0345169 
[Info] OwinHostController: Listening on the following URLs: 
[Info] OwinHostController:   http://localhost:7878/ 
[Debug] OwinAppFactory: Attaching NzbDroneVersionMiddleWare to host 
[Debug] OwinAppFactory: Attaching SignalRMiddleWare to host 
[Debug] OwinAppFactory: Attaching NancyMiddleWare to host 
[Info] NancyBootstrapper: Starting NzbDrone API 
[Info] BrowserService: Starting default browser. http://localhost:7878 
[Info] ProcessProvider: Opening URL [http://localhost:7878] 
[Debug] QualityDefinitionService: Setting up default quality config 
[Warn] IndexHtmlMapper: File C:\programdata\radarr\bin\UI\index.html not found 
[Debug] NotificationFactory: Initializing Providers. Count 20 
[Debug] DownloadClientFactory: Initializing Providers. Count 15 
[Debug] NetImportFactory: Initializing Providers. Count 6 
[Debug] IndexerFactory: Initializing Providers. Count 11 
[Debug] MetadataFactory: Initializing Providers. Count 4 
[Debug] SabnzbdProxy: Url: http://localhost:8080/api?mode=get_config&apikey=xxx&output=json

**Comment by OverlordQ** [comment]
Uninstalled, reinstalled, nothing changed. 

Not installed as a service.

**Comment by weirdcrap** [comment]
This pops out at me: [Warn] IndexHtmlMapper: File C:\programdata\radarr\bin\UI\index.html not found

Have you verified that file exists and is accessible by the user radarr is running under?
