### ISSUE TITLE
Radarr DownloadMovieImportService retrying to import a file that doesn't exist every minute

### ISSUE THREAD

**Issue by ghallford** [Radarr/Radarr#2779]
**Description:**

Radarr DownloadMovieImportService retrying to import a file that doesn't exist every minute. The movie also does not exist as a requested movie. 

Import failed, path does not exist or is not accessible by Radarr: E:\Downloads\DownloadedMoviesRadarr\Merlins-portal.Net]-Hall.Pass.2011.RERiP.DVDRip.XviD-DEFACED-

**Radarr Version:** 0.2.0.1097

**Mono Version:**

**Debug Logs:** 

18-5-16 11:09:17.9|Debug|Parser|Parsing string 'Merlins-portal.Net]-Hall.Pass.2011.RERiP.DVDRip.XviD-DEFACED-'
18-5-16 11:09:17.9|Debug|Parser|Movie Parsed. Merlins-portal Net]-Hall Pass - 2011 
18-5-16 11:09:17.9|Debug|Parser|Language parsed: English
18-5-16 11:09:17.9|Debug|QualityParser|Trying to parse quality for Merlins-portal.Net]-Hall.Pass.2011.RERiP.DVDRip.XviD-DEFACED-
18-5-16 11:09:17.9|Debug|Parser|Quality parsed: DVD v2
18-5-16 11:09:17.9|Debug|Parser|Release Group parsed: DEFACED
18-5-16 11:09:17.9|Debug|Parser|Parsing string 'Merlins-portal.Net]-Hall.Pass.2011.RERiP.DVDRip.XviD-DEFACED-'
18-5-16 11:09:17.9|Debug|Parser|Movie Parsed. Merlins-portal Net]-Hall Pass - 2011 
18-5-16 11:09:17.9|Debug|Parser|Language parsed: English
18-5-16 11:09:17.9|Debug|QualityParser|Trying to parse quality for Merlins-portal.Net]-Hall.Pass.2011.RERiP.DVDRip.XviD-DEFACED-
18-5-16 11:09:17.9|Debug|Parser|Quality parsed: DVD v2
18-5-16 11:09:17.9|Debug|Parser|Release Group parsed: DEFACED
18-5-16 11:09:17.9|Debug|Parser|Parsing string 'Merlins-portal.Net]-Hall.Pass.2011.RERiP.DVDRip.XviD-DEFACED-'
18-5-16 11:09:17.9|Debug|Parser|Movie Parsed. Merlins-portal Net]-Hall Pass - 2011 
18-5-16 11:09:17.9|Debug|Parser|Language parsed: English
18-5-16 11:09:17.9|Debug|QualityParser|Trying to parse quality for Merlins-portal.Net]-Hall.Pass.2011.RERiP.DVDRip.XviD-DEFACED-
18-5-16 11:09:17.9|Debug|Parser|Quality parsed: DVD v2
18-5-16 11:09:17.9|Debug|Parser|Release Group parsed: DEFACED
18-5-16 11:09:18.0|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: E:\Downloads\DownloadedMoviesRadarr\Merlins-portal.Net]-Hall.Pass.2011.RERiP.DVDRip.XviD-DEFACED-

**Comment by Budman1758** [comment]
I have the same issue. 
Import failed, path does not exist or is not accessible by Radarr: E:\Movies\Black Water 2018 720p WEB-DL.2
This message is logged 6 times per minute. Going on for days according to the log.
That movie is not anywhere on my system. Not wanted or already existing. Have never typed in into the wanted list or anything. How do you stop Radarr from looking for it?

**Comment by waxill** [comment]
I also have the same issue.
I realised early on that a mapped drive would not work so changed it to a URL and used a service account with permissions. Now my logfile is filled with a loop looking at the mapped drive letter, but there is no reference to it in any of my configuration.

18-8-6 08:54:20.6|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: G:\SabNZB\Complete\Movies\Source.Code.2011.BluRay.720p.H264.cp(tt0945513)

18-8-6 08:54:20.7|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: G:\SabNZB\Complete\Movies\reservoir.dogs.1992.internal.720p.bluray.x264-moovee.cp(tt0105236)

http://i106.photobucket.com/albums/m280/waxil/sab%20config_zpsndik4y1l.jpg

http://i106.photobucket.com/albums/m280/waxil/drone_zpsnaybhths.jpg

http://i106.photobucket.com/albums/m280/waxil/naming_zpsuhq5beoj.jpg

http://i106.photobucket.com/albums/m280/waxil/sab%20config2_zpszaycw7br.jpg

http://i106.photobucket.com/albums/m280/waxil/completed%20handling_zpsgytbnclt.jpg

**Comment by Budman1758** [comment]
The only reason its stale is because the developers have not bothered to answer it.....

**Comment by woody3000** [comment]
Clearing out the offending history items in my download client seems to have cleared it up for me too!

**Comment by Budman1758** [comment]
The only reason its stale is because the developers have not bothered to answer it.....

**Comment by galli-leo** [comment]
@Budman1758 Sorry, this issue seems to have slipped my feed multiple times.

However, the fix is quite simple, just remove the "offending" download from your download clients history. Alternatively, you can also just change the label of that download.

The issue arises when either Radarr looses its import history or you connect it to a download client with already imported downloads. Radarr will try to import all previous downloads, but some of them might have already been moved / deleted / etc. So it will fail.

**Comment by jennec** [comment]
This behaviour still seems to happen.  For me it happens every other movie.  The movie downloads, gets imported by Radarr from the Downloader and moved to the right root folder. All files and folders are cleaned up from the download folder, but Radarr does not remove it from the Downloader App or its won activity queue and continues to try and import it generating errors that the folder does not exist.  

But some apps will get imported and the movie removed from the downloader app and activity queue.
