### ISSUE TITLE
Customize title used for movie renaming

### ISSUE THREAD

**Issue by foXaCe** [Radarr/Radarr#2782]
Hello

is it possible to rename folders after updating the metadata in the search language? the repertoires always have the name of the film in VO.

**Comment by galli-leo** [comment]
No unfortunately not currently

**Comment by guim31** [comment]
This is a GREAT function to add :) 

I have about 500 movies in my radarr collection, every folder is set with the original name. I would like to rename all the folders in the french name of the movie.

Is some option like this coming ?

**Comment by galli-leo** [comment]
@guim31 https://blog.radarr.video/development/update/2018/11/11/roadmap-update.html
