### ISSUE TITLE
[Feature Request] Fix Match on Movie

### ISSUE THREAD

**Issue by WeirDave** [Radarr/Radarr#2784]
It would come in handy I think if a movie was downloaded and then incorrectly identified to have a way to edit the movie to rematch it to the correct movie.

Example:

I downloaded both:  
Downfall (2004) [tt0363163]
Death in the Bunker: The True Story of Hitler's Downfall (2004) [tt0773136]

It identified them backwards and I couldn't figure out an easy way to fix the match.

[AB#866](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/866)

**Comment by galli-leo** [comment]
So you want to tell Radarr the file belongs to a different movie and have it move it?

**Comment by WeirDave** [comment]
Yes, sort of. It identified the movies incorrectly because they are similarly named and same year and there isn't a way to fix this currently.

**Comment by fryfrog** [comment]
Did they import wrong or did they get stuck in Activity, not able to be identified? Can you post the exact names of the releases?

**Comment by WeirDave** [comment]
They imported in incorrectly. It kept trying to import both in as Downfall

**Comment by fryfrog** [comment]
So your feature request is basically file management inside of Radarr. That sounds like a large project that would end up being confusing, as well as duplicating something that every OS already has. :(

**Comment by Qstick** [comment]
#355
