### ISSUE TITLE
SQL logic error or missing database

### ISSUE THREAD

**Issue by Fribb** [Radarr/Radarr#2787]
**Description:**

Docker Version: 17.12.1-ce, build 7390fc6
Docker-compose Version: 1.17.0, build ac53b73
Container version number: Linuxserver.io version:- 81 Build-date:- January-19-2018-23:15:29-UTC

after rebuilding the container with docker-compose I got an endless loading screen when visiting the WebUI.

The log file is showing an exception whenever I load the WebUI

`[v0.2.0.910] System.Data.SQLite.SQLiteException (0x80004005): SQL logic error or missing database
no such table: Series` (full log file below)

which is strange since it worked flawlessly without any problems prior to the rebuild (and no new version of the container was pulled from the docker hub).

**Radarr Version:**  Version 0.2.0.910

**Mono Version:**

**Debug Logs:**

https://pastebin.com/2QqgLb88

**Comment by galli-leo** [comment]
You updated inside the container. You cannot do that, to fix pull the latest image and make sure to turn off automatic updates.

**Comment by Fribb** [comment]
I don't have automatic updates but I did do it manually a few times without issues.

But I did use the latest image from the docker hub, which means the version is incompatible which is actually current?!

**Comment by galli-leo** [comment]
The error shows, the image you pulled was an old version, which is incompatible with the database migrated from your new version.

**Comment by Fribb** [comment]
That is strange since docker-compose should pull the newest image.

I deleted the image with `docker image rm linuxserver/radarr` and pulled it again with `docker pull linuxserver/radarr`

Now it works. Thanks.
