### ISSUE TITLE
Feature request: more metadata support for file/folder naming schemas such as MPAA rating / other TMDB info

### ISSUE THREAD

**Issue by tastyratz** [Radarr/Radarr#2788]
I'd like to suggest the ability to have more extensive & flexible metadata schemas to inject in file naming. If we're scraping tmdb I'm sure some would find value with further leveraging it.

Primary example would be support for MPAA ratings (such as pg-13, R, etc. )

This is very helpful if you have children in the home and control via ntfs permissions outside of kodi/etc. parental controls since it's easy to break out with basic share navigation.

**Comment by CelagentT3** [comment]
I really need this as well to sort to folders for children to not be able to get to pg-13, R or beyond. Maybe even if it auto tagged with the rating then read that to sort to folders. Thank you for the amazing software!

**Comment by Qstick** [comment]
Done in V3
