### ISSUE TITLE
Not grabbing movies due to glitch?

### ISSUE THREAD

**Issue by PepeAnto** [Radarr/Radarr#2792]
When I search for a movie it doesn't start downloading it, so I click on the manual search and the information given says that it exceeds the maximum size. I have checked my settings and 10 Mb is not my maximum size...
**To Reproduce**
1. Go to movies tab
2. Click on the manual search button
3. See error

**Expected behavior**
x GB is too big, maximum size is 10.0MB

**Screenshots**
![radarr](https://user-images.githubusercontent.com/33628161/40282782-7b23b62c-5c74-11e8-8419-4e651fbdd21c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser and Version Chrom
 - Version 66.0.3359.181 (Official Build) (64-bit)

**Debug Logs**
[radarr.txt](https://github.com/Radarr/Radarr/files/2020629/radarr.txt)

**Comment by galli-leo** [comment]
Please provide debug logs as well as the movie in question. It probably has a very small runtime.

**Comment by PepeAnto** [comment]
The full log should be there, also it's not one particular movie, it's
every movie...

**Comment by galli-leo** [comment]
No those aren't debug logs.

**Comment by PepeAnto** [comment]
Eh, I just uninstalled it and reinstalled it. seems to be working now. Thank you though :D
