### ISSUE TITLE
Multiple torrents added for same movie

### ISSUE THREAD

**Issue by bpear** [Radarr/Radarr#2794]
I have Jackett setup with IpTorrents and 1337x along with Rarbg through the standard Radarr indexer. I've had this issue with 3 movies. The Disaster Artist, Blade Runner, and Blade Runner 2049

What happens according to the log is that downloading the torrent from IPT failed. However, the torrent is added to my RTorrent client. I have a seedbox which I have setup in Radarr, a watch folder is not used. 

Here is the log 
![image](https://user-images.githubusercontent.com/561739/40283673-05b42c42-5c50-11e8-9f2c-7f26f11f00f5.png)

[radarr.txt](https://github.com/Radarr/Radarr/files/2020705/radarr.txt)

**Comment by bpear** [comment]
![image](https://user-images.githubusercontent.com/561739/40283695-5d46eb48-5c50-11e8-8748-5ddd1607f89e.png)

It looks like Jackett is getting a server load message from IPT. It's strange that the torrent is still grabbed and successfully added to Rtorrent though.

**Comment by hotio** [comment]
```
Bug report
Support requests will be closed immediately, if you are unsure go to our Discord or Subreddit first. Exceptions do not mean you found a bug!
```

**Comment by cj0r** [comment]
Still an issue fyi and same behavior exhibited for me with IPT and Deluge.

**Comment by Surgikill** [comment]
Same issue. It just flooded my deluge with 51 torrents and I only added 5 movies.

**Comment by Surgikill** [comment]
I just looked at my deluge and none of the added files have labels. Maybe that could be the problem?

**Comment by austinwbest** [comment]
Thanks for organizing Qstick, hopefully will get some sort of answers for this
