### ISSUE TITLE
Radarr on QNAP doesn't start

### ISSUE THREAD

**Issue by RenVilo** [Radarr/Radarr#2804]
I installed QMono V5.12.0.266 on my QNAP and now Radarr doesn't start automatically. I use this command to manually start it (it did work before with this command:

/share/HDA_DATA/.qpkg/Radarr/Radarr.sh start

Then I get the following:

Segmentation fault
Illegal instruction
Radarr is disabled.

**Radarr Version:** This is with Radarr (V0.2.0.995)

**Mono Version:** QMono V5.12.0.266

**Debug Logs:** Can't provide as I can't log into Radarr

**Comment by hotio** [comment]
See https://blog.radarr.video/blog/post/1-year-of-radarr
>Github Issues and Support

Lots of people on reddit or discord, that are happy to help.

**Comment by Tdotsown** [comment]
im having the same issue, and the link above doesnt work. i have to manually stop radarr and re-enable it to work again after restarting my QNAP
