### ISSUE TITLE
Delete root movies folder causes file sync problems

### ISSUE THREAD

**Issue by Kevintjeb** [Radarr/Radarr#2805]
**Describe the bug**
When deleting the root folder where all movies are getting synced to it causes radarr to not update the status from the movies. All movies keep the status downloaded. 

When manually deleting the movie files from within Radarr and then syncing, it says downloaded as well. The 'file' that is non existing also gets put back in the files section of the movie. 

**To Reproduce**
1. Remove root folder
2. Click on sync library
3. Watch as all movies are still 'downloaded'

**Expected behavior**
All movies are set to unmonitored as they are not available anymore.

**Debug logs**

  | MetadataService | Movie folder does not exist, skipping metadata creation | 11:22am
-- | -- | -- | --
  **| DiskScanService | Movies' root folder (/volume1/downloads/complete/Movies) is empty. | 11:22am**
  | MetadataService | Movie folder does not exist, skipping metadata creation | 11:22am
  | RefreshMovieService | Updating Info for Thor: Ragnarok | 11:22am
  | DiskScanService | Movies' root folder (/volume1/downloads/complete/Movies) is empty. | 11:22am
  | MetadataService | Movie folder does not exist, skipping metadata creation | 11:22am
  | RefreshMovieService | Updating Info for Super Troopers 2 | 11:22am
  | DiskScanService | Movies' root folder (/volume1/downloads/complete/Movies) is empty. | 11:22am
  | MetadataService | Movie folder does not exist, skipping metadata creation | 11:22am
  | RefreshMovieService | Updating Info for Star Wars: The Last Jedi | 11:22am
  | DiskScanService | Movies' root folder (/volume1/downloads/complete/Movies) is empty. | 11:22am
  | MetadataService | Movie folder does not exist, skipping metadata creation | 11:22am
  | RefreshMovieService | Updating Info for Spider-Man: Homecoming | 11:22am
  | DiskScanService | Movies' root folder (/volume1/downloads/complete/Movies) is empty. | 11:22am
  | MetadataService | Movie folder does not exist, skipping metadata creation | 11:22am

**RUnning on:**
 - OS: DSM
- System: Synology DS718+
 - Mono Version: 5.8.0.108
 - Version: 0.2.0.1067

**What works in the mean time : **
If I create an empty folder, for one of the monitored movies, Radarr understands everything is gone and sets everything to unmonitored.

**Fix?**
If I can find some spare time, I will fork the repo and propose a solution.

**Comment by hotio** [comment]
Isn't it advisable that when the entire root folder is gone, to NOT take drastic steps and assume it's a temporary fuckup? What if the root path is not online or temporarly unmounted, I wouldn't want radarr to trash the db.

**Comment by Kevintjeb** [comment]
True. 

I think that Radarr should notify the user and give the option to ignore / cancel, as they know it was a fuckup or let Radarr construct the root folder again itself so everything can be readjusted.

**Comment by Qstick** [comment]
We have a health check that notifies user of missing root folder.

**Comment by Kevintjeb** [comment]
How does the user get notified, in my case I wasn't?
