### ISSUE TITLE
Restrictions not working probely

### ISSUE THREAD

**Issue by KennyVB** [Radarr/Radarr#2807]
Want to make a restrictions in indexer: **MUST NOT CONTAIN** = "Blur", "BLUR" 
how ever it will then not download "BluRay" even tho it says case sensative..

even tried to have **Must not contain** = "Blur", "BLUR"
and then **must contain** = "BluRay" but no dice..

**Comment by galli-leo** [comment]
It says case insensitive

**Comment by KennyVB** [comment]
Ahh my bad. 
But nevertheless it doesn't work probably. Or do you have a idea on what to do ?

**Comment by galli-leo** [comment]
@KennyVB Add your words with both spaces and dots on both sides, this way it will only match if they are a whole word
