### ISSUE TITLE
Radarr not cleaning up after importing movies

### ISSUE THREAD

**Issue by ThePOO** [Radarr/Radarr#2808]
My monitored downloads folder is getting movies recognized and added to my movies folder just great.   (once in a while I might have to correct a movie year or some spelling, then it gets processed)
What seems hit and miss is removal of the item in the downloads folder afterward?

Windows 7 SP1

There aren't any issues evident in the logs?

**Comment by hotio** [comment]
Radarr cleans up fine when used with usenet, for torrents it only cleans up when the torrent client tells radarr it has done seeding (=/= downloading).

But as requested by the devs, keep support questions for discord or reddit, only use github issues for actual bugs/issues.

**Comment by ThePOO** [comment]
I'm using the Transmission headless daemon ... I will investigate interaction between it and Radarr -- maybe I can determine whats happening.

Thank you for your comment -- gives me some things to think about.
