### ISSUE TITLE
Small UI issue in Bulk Import, only showing 14 movies

### ISSUE THREAD

**Issue by mgray88** [Radarr/Radarr#2811]
**Describe the bug**
Basically what the title says. On the bulk import page, the dropdown selector shows 15, however only 14 movies are displayed. It took me a while to notice it, but the notifications that kept say "Importing 14 movies...." tipped me off to something weird. Sure enough, only 14 movies are displayed in the list

**To Reproduce**
Open Bulk Import and select a folder that has 15 movies or more.
Ensure the dropdown shows '15'
Movies list only displays 14

**Expected behavior**
Expected 15

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Mono Version: 4.6.2
 - Browser and Version: Firefox 60.0.1 (64-bit)
 - Version: 0.2.0.1067

**Comment by Qstick** [comment]
Got screenshot? Mine shows 15
