### ISSUE TITLE
Drone folder Imports attempting to send to root if movie added via List

### ISSUE THREAD

**Issue by JonSingleton** [Radarr/Radarr#2817]
**Describe the bug**
I have several watch lists in Radarr. When a movie is added via the list function (just automatically with no user intervention), after the download completes, rather than using the folder listed in the List's settings, Radarr attempts to move the file to the root (/) movies title (/RenamedMovieTitle).

I am using done factory as my Radarrinstance is local while my torrent client is remote (seedbox), the file is then synced via Syncthing. Conveniently syncthing uses an invalid name (to Radarr) during sync, and Radarr finds the movie properly after the sync has completed.

This had worked smoothly for some time, but just recently started occurring. 

**To Reproduce**
1. have a movie added from a list
2. See if movie tries to move to root instead of set folder in list settings.

**Expected behavior
Movie should be moved to defined folder, not root.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Mono Version:4.2.3 (Stable 4.2.3.4/832de4b Wed Mar 16 13:19:08 UTC 2016)
 - Browser and Version not applicable
 - Version [e.g. 22] 0.2.0.1120

**Debug Logs**
http://pasted.co/53de6ef7

**Comment by hotio** [comment]
Does switching to completed download handling fix the issue?
