### ISSUE TITLE
[Feature]: don't suggest movies I've already watched

### ISSUE THREAD

**Issue by danielb2** [Radarr/Radarr#2822]
**Is your feature request related to a problem? Please describe.**

There are many suggestions for movies that I've already watched when it's making suggestions for movies to add.

**Describe the solution you'd like**

Use trakt.tv for example, and pull from what I've already watched.

**Describe alternatives you've considered**

Import a plaintext file with a list of movies

**Comment by hotio** [comment]
Workaround: import them, unmonitor

**Comment by danielb2** [comment]
> Workaround: import them, unmonitor

that will make my list very spammy, and it's very time consuming. Not really a reasonable thing to do 
 as I've watched over 1000 movies.

**Comment by hotio** [comment]
Spammy, ok, time consuming, doesn't have to. Either way the option is there, until the feature is implemented.

**Comment by galli-leo** [comment]
Current possiblities to do it relatively easily:

1. Import movies via list (make sure to set it to unmonitored). Go to Movie Editor. Select all imported movies. Click delete selected and make sure to select Exclude movies from auto list import?

2. Write a script that pulls the tmdbids from trakt and writes them to the database into the import exclusions db.

**Comment by danielb2** [comment]
How is option 1 "relatively easy" when I have 1198 imported movies to "select" ?

anyway, option 2 is at least realistic so thanks for the suggestion. can you tell me where the database and what db is used? Sqlite ?
