### ISSUE TITLE
List priority

### ISSUE THREAD

**Issue by thedelph** [Radarr/Radarr#2823]
Lets say I have two lists:

List1 - "Highest Rated Movies Of All Time" - Profile UltraHD
List2 - "Top Movies Of 2018" - Profile 1080p

It's possible that a movie in list 2 is also in list 1. Currently, I don't know which list would win. So it's possible the movie could be downloaded in either 1080p or 4K/UHD.

I would like to be able to set a numeric priority value (either highest or lowest wins) against each list so that if an item is in multiple lists it will be taken from the highest priority list.

Say it was lowest wins, I could set List1 to priority 1, and List2 to priority 2. That way if a movie is in both lists, it will download from List1, not List2.

**Comment by Qstick** [comment]
This is not reliable as it may show up on one list sooner. We would have to handle upgrades to quality if it shows up later. This gets messy.

**Comment by thedelph** [comment]
Failing that, allow the movie to be on multiple lists and download it multiple times in multiple qualities.

That way at least I'll end up with 2 versions of the movie (1080p and 4K) instead of potentially just the lesser quality version.
