### ISSUE TITLE
Renaming and Plex name detection

### ISSUE THREAD

**Issue by The1Authority** [Radarr/Radarr#2824]
Hi,
I have a problem I think with the renaming function and Plex name detection. When I download a movie (RARBG) the movie download fine and is renamed with the parameters I entered but the movie title name is wrong in plex.

Let's say I download a movie named The.Disaster.Artist.2017.1080p.BluRay.H264.AAC-RARBG
After the download process is complete, the file is renamed The Disaster Artist 2017 Bluray-1080p.mp4

The thing is, Plex see the movie name as The.Disaster.Artist.2017.1080p.BluRay.H264.AAC-RARBG

What i've found is the title name in the movie parameters is wrong.
Right-click on movie / Parameters /  Details tab / Title parameter.

If I remove or change the name there, Plex pick it up just fine.
I dont know if this problem occur in the renaming process OR it's a problem with RARBG but it happens every time except if the movie is a .mkv for some reason.

**Comment by hotio** [comment]
Why would you ask a plex misconfiguration support question on another project their bug reports issue tracker?

Adjust your plex movie agent to not use local metadata as first priority.
