### ISSUE TITLE
Customized email notification's subject and body

### ISSUE THREAD

**Issue by henkin67** [Radarr/Radarr#2825]
I'm using the email notification to monitor easly what happen on Radarr.
But there is no way to customize the email's subject nor body.

For example, I would like to add the title of the movie in the email's subject.
When we are creating custom script, we have access to a various of variable.
It should be great to have a screen when you can wrote the subject and body of the email and to have the capacity to add variable value (using %%<variable>%% for example).

Of course this is a nice to have feature, but I don't know the complexity to put that in place.

In any case, thanks a lot for your hard work on that marvelous application!

**Comment by Qstick** [comment]
You can do something like this https://forums.sonarr.tv/t/custom-email-and-sms-notifications/14401 with custom script notification until this is expanded.

**Comment by Hansaplast** [comment]
+1
