### ISSUE TITLE
Option to specify temporary move naming pattern or at least keep the original extension.

### ISSUE THREAD

**Issue by mattheys** [Radarr/Radarr#2826]
**Is your feature request related to a problem? Please describe.**
I have an rclone mount to Google Drive, when a file gets copied or moved over to that mount, Google will attempt to determine the mime type based on the file extension, this means all Sonarr/Radarr processed files are on as Binary File (application/octet-stream) and you don't get the video preview inside Google Drive. 

**Describe the solution you'd like**
I would like an option to override the default of appending .partial~ to a filename either the ability to specify my own template or at the very least an option to keep the original file extension .mp4/.mkv etc. This way Google Drive will recognize it as a video and will generate the online streaming version of the file as well as the correct mime type.

**Describe alternatives you've considered**
I thought about using Radarr to move to a temporary location and then use rclone move to Google Drive, but this would mean Radarr wouldn't be able to track and upgrade existing files.

**Comment by hotio** [comment]
Why would radarr be changing the extension? Never have I seen radarr change the extension.

**Comment by mattheys** [comment]
It changes the extension to .partial~ while moving then renames it afterwards back to the original but the damage is done by then, if it moves the file with the original extension like .partial.mkv then the video preview in Google drive should work.

**Comment by hotio** [comment]
I understand now...
