### ISSUE TITLE
4K Movies Not Showing Up In Radarr Search, But Can See Them On Indexer Directly

### ISSUE THREAD

**Issue by 1liminal1** [Radarr/Radarr#2828]
**Describe the bug**
4K Movies Not Showing Up In Radarr Search, But Can See Them On Indexer Directly

Is this a category tagging issue?

**To Reproduce**
Search indexer, can see 4K movie
Manual search Radar, movie doesn't show. (no 4k movies show at all)

**Expected behavior**
To see and download 4k movies

**Desktop (please complete the following information):**
 - OS: Server 2016
 - Mono Version: [e.g. Mono 5.8] (Only needed under Linux and Mac, found under System -> Status)
 - Browser and Version [e.g. chrome, safari] (Only needed for UI issues)
 - Version [e.g. 22] 0.2.0.1067

**Comment by 1liminal1** [comment]
I'm getting a lot of strange errors;

Couldn't evaluate decision on Star.Wars.The.Last.Jedi.2017.1080p.BRRip.X264, with spec: QueueSpecification: Value can not be null.
Parameter name: profile

**Comment by mrzoops** [comment]
Most likely this is due toi not having the correct categories set up. Are you using Jackett? Make sure to add the UHD movies category.

**Comment by Qstick** [comment]
Hit discord for setup support
