### ISSUE TITLE
AltHub doesn't work with Radarr?

### ISSUE THREAD

**Issue by CKyle22** [Radarr/Radarr#283]
I can't get the indexer AltHub to work with Radarr. It's worked with Sonarr and CouchPotato just fine and I used the exact same settings. I'm using Radarr in Windows.

The logs just say it cannot connect to the indexer.

**Comment by galli-leo** [comment]
If you are using Jackett, please add anything to the username field.

**Comment by galli-leo** [comment]
Also please use TorrentPotato with Jackett instead of Torznab.

**Comment by CKyle22** [comment]
Apologies for not mentioning this in my OP, AltHub is a usenet indexer and I don't use Jackett or Torznab. It's a Newznab indexer.

**Comment by onedr0p** [comment]
Althub needs to add movie search support to theirs caps api. I am a member there and will try to get in touch with their staff.

**Comment by CKyle22** [comment]
Oh cool, thanks.

**Comment by onedr0p** [comment]
I have sent them an email too add it to their RSS feed, that's all we can do.

**Comment by onedr0p** [comment]
![image](https://cloud.githubusercontent.com/assets/213795/22048265/c511707c-dcf9-11e6-83a2-3421fa09feba.png)

**Comment by CKyle22** [comment]
Thanks so much!!
