### ISSUE TITLE
Radarr not starting/crash on launch

### ISSUE THREAD

**Issue by Adrian-at-CrimsonAuzre** [Radarr/Radarr#2830]
**Describe the bug**
Radarr crashes within seconds of launch. I've wiped my config foler (/usr/local/radarr/), and reinstalled Radarr. I noticed it stopped working just after trying to connect Organizr, there was probably an hour window between when I last used it and when I tried to connect it.

**To Reproduce**
service radarr start && top -P
mono-sgen quits out in a few seconds

**Expected behavior**
Radarr _should_ run.

**Desktop (please complete the following information):**
 - OS: FreeBSD 11.1 Jail (Freenas 11.1)
 - Mono Version: mono-5.2.0.215_1
 - Version: radarr-0.2.0.1067

**Debug Logs**

     18-6-4 11:27:14.1|Debug|ProcessProvider|Found 0 processes with the name: Radarr.Console
     18-6-4 11:27:14.1|Debug|ProcessProvider|Found 0 processes with the name: Radarr
     18-6-4 11:27:14.2|Info|Router|Application mode: Interactive
     18-6-4 11:27:14.2|Debug|Router|Console selected
     18-6-4 11:27:14.4|Info|MigrationLogger|*** Migrating data source=/usr/local/radarr/nzbdrone.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
This is all radarr.debug.txt has in it.

**Comment by robertsm85** [comment]
I'm seeing the same issue, started this morning. Radarr is working fine this yesterday.

**Describe the bug**
Radarr crashes within seconds of launch.

**To Reproduce**
run "systemctl start radarr.service" mono starts in system monitor and then closes after a few seconds.

**Expected behavior**
Radarr should run.

**Desktop (please complete the following information):**

    OS: Ubuntu 17.10
    Mono Version: mono-5.12.0.226
    Version: unknown, maybe 1 or 2 versions back

**Debug Logs**
Not sure how to get these w/ radarr not running.

**Comment by Adrian-at-CrimsonAuzre** [comment]
I ended up nuking my jail and reinstalling. I noticed my server logs had a message about an unexpected restart (power went out and UPS I was using was garbage) right before Radarr stopped working. So I'm going to attribute this to an unexpected shutdown.

**Comment by galli-leo** [comment]
Probably one of the assemblies was corrupted or something like that.
