### ISSUE TITLE
Profile cut-off met but movie still monitored 

### ISSUE THREAD

**Issue by mikec25** [Radarr/Radarr#2833]
**Describe the bug**
Profile cut-off met but movie still monitored 

**Expected behavior**
When cut-off met, movie should change state from Downloaded and Monitored --> Downloaded, but not Monitored

**Screenshots**
![image](https://user-images.githubusercontent.com/11380049/41126069-a7d1499a-6ae9-11e8-84b7-c8314d3da6f7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 - latest
 - Browser and Version FireFox - latest
 - Version     0.2.0.1067

**Comment by Qstick** [comment]
The movie stays monitored Incase of propers, etc. Is there an issue with it being monitored if it doesn’t download anything else?

**Comment by mikec25** [comment]
Fair enough.
