### ISSUE TITLE
Peers "999/999"  ??

### ISSUE THREAD

**Issue by peaton** [Radarr/Radarr#2834]
What does it mean when in the manual movie manual search page, the Peers column is listed as 999/999 ??

**Comment by hotio** [comment]
When I create a new issue, I have to pick between `Bug report` and `Feature request`, this is none of those. How did you do it?

**Comment by DanielHHowell** [comment]
Were you ever able to figure this out? This is definitely a bug, I very regularly encounter torrents showing 999/999 peers and seeds that are often in actuality 0/0
