### ISSUE TITLE
Unable to update pre release Radarr version

### ISSUE THREAD

**Issue by sideoutdude16** [Radarr/Radarr#2836]
I can't update Radarr from the application UI and from terminal manually. 

I get error every time I try to update.

**Debug Logs**
18-6-10 11:37:10.3|Debug|SabnzbdProxy|Url: http://192.168.1.81:9610/api?mode=get_config&apikey=(removed)&output=json
18-6-10 11:37:10.4|Debug|Api|[PUT] /api/config/host: 202.Accepted (154 ms)
18-6-10 11:37:10.5|Debug|Api|[GET] /api/health: 200.OK (0 ms)
18-6-10 11:37:16.6|Debug|Api|[GET] /api/health: 200.OK (0 ms)
18-6-10 11:37:16.6|Debug|Api|[GET] /api/diskspace: 200.OK (20 ms)
18-6-10 11:37:16.6|Debug|Api|[GET] /api/health: 200.OK (0 ms)
18-6-10 11:37:16.7|Debug|Api|[GET] /api/diskspace: 200.OK (9 ms)
18-6-10 11:37:21.6|Debug|Api|[GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc&filterType=equal: 200.OK (3 ms)
18-6-10 11:37:21.7|Debug|Api|[GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc&filterType=equal: 200.OK (3 ms)
18-6-10 11:37:26.9|Debug|Api|[GET] /api/update: 200.OK (188 ms)
18-6-10 11:37:27.1|Debug|Api|[GET] /api/update: 200.OK (334 ms)
18-6-10 11:37:29.0|Debug|Api|[POST] /api/command: 201.Created (4 ms)
18-6-10 11:37:29.0|Debug|InstallUpdateService|Checking for updates
18-6-10 11:37:29.1|Info|InstallUpdateService|Deleting old update files
18-6-10 11:37:29.1|Info|InstallUpdateService|Downloading update 0.2.0.1067
18-6-10 11:37:29.1|Debug|InstallUpdateService|Downloading update package from [https://github.com/Radarr/Radarr/releases/download/v0.2.0.1067/Radarr.develop.0.2.0.1067.linux.tar.gz] to [/tmp/radarr_update/Radarr.develop.0.2.0.1067.linux.tar.gz]
18-6-10 11:37:29.1|Debug|HttpClient|Downloading [https://github.com/Radarr/Radarr/releases/download/v0.2.0.1067/Radarr.develop.0.2.0.1067.linux.tar.gz] to [/tmp/radarr_update/Radarr.develop.0.2.0.1067.linux.tar.gz]
18-6-10 11:37:29.3|Warn|HttpClient|Failed to get response from: https://github.com/Radarr/Radarr/releases/download/v0.2.0.1067/Radarr.develop.0.2.0.1067.linux.tar.gz Error: SendFailure (Error writing headers)
18-6-10 11:37:29.3|Error|CommandExecutor|Error occurred while executing task ApplicationUpdate

[v0.2.0.935] System.Net.WebException: Error: SendFailure (Error writing headers) ---> System.Net.WebException: Error writing headers ---> System.IO.IOException: The authentication or decryption has failed. ---> Mono.Security.Protocol.Tls.TlsException: The authentication or decryption has failed.
  at Mono.Security.Protocol.Tls.RecordProtocol.EndReceiveRecord (IAsyncResult asyncResult) <0x41bde400 + 0x00103> in <filename unknown>:0 
  at Mono.Security.Protocol.Tls.SslClientStream.SafeEndReceiveRecord (IAsyncResult ar, Boolean ignoreEmpty) <0x41bde340 + 0x0002b> in <filename unknown>:0 
  at Mono.Security.Protocol.Tls.SslClientStream.NegotiateAsyncWorker (IAsyncResult result) <0x41bdba80 + 0x00223> in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at System.Net.WebConnection.EndWrite (System.Net.HttpWebRequest request, Boolean throwOnError, IAsyncResult result) <0x41ace620 + 0x00207> in <filename unknown>:0 
  at System.Net.WebConnectionStream+<SetHeadersAsync>c__AnonStorey1.<>m__0 (IAsyncResult r) <0x41acdf00 + 0x00143> in <filename unknown>:0 
  --- End of inner exception stack trace ---
  --- End of inner exception stack trace ---
  at System.Net.WebClient.DownloadFile (System.Uri address, System.String fileName) <0x41bd48b0 + 0x003bf> in <filename unknown>:0 
  at System.Net.WebClient.DownloadFile (System.String address, System.String fileName) <0x41bd4420 + 0x0003b> in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.Net.WebClient:DownloadFile (string,string)
  at NzbDrone.Common.Http.HttpClient.DownloadFile (System.String url, System.String fileName) [0x00056] in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:167 

18-6-10 11:37:29.4|Debug|Api|[GET] /api/system/task?sort_by=name&order=asc: 200.OK (2 ms)
18-6-10 11:37:29.4|Debug|Api|[GET] /api/system/task?sort_by=name&order=asc: 200.OK (7 ms)
18-6-10 11:37:36.9|Debug|SabnzbdProxy|Url: http://192.168.1.81:9610/api?mode=queue&start=0&limit=0&apikey=(removed)&output=json

**Comment by hotio** [comment]
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Mono Version: [e.g. Mono 5.8] (Only needed under Linux and Mac, found under System -> Status)
 - Browser and Version [e.g. chrome, safari] (Only needed for UI issues)
 - Version [e.g. 22]

**Debug Logs**
Turn on debug logs under Settings -> General and wait for the bug to occur again. **Upload the full log file here (or another site and link it). Issues will be closed, if they do not include this!**

**Comment by hotio** [comment]
My wildest guess, for this support question. `mono/version/certificates`

**Comment by sideoutdude16** [comment]
bug: cannot update Radarr
reproduce: check for update (application update failed). terminal manual update: cannot resolve proxy.
expected behavior: update to the latest version

debug copy and pasted above in my original response.

**Comment by hotio** [comment]
Update mono

**Comment by galli-leo** [comment]
Yeah update mono

**Comment by sideoutdude16** [comment]
ok next question is.. 5.8 or 5.10/5.12? I have 5.12 installed and now im getting "Press enter to exit"
