### ISSUE TITLE
[Feature Request] Movie Editor window allows editing of individual paths for movies.

### ISSUE THREAD

**Issue by damnjuhl** [Radarr/Radarr#2838]
On the Movie Editor screen I'm able to see the paths associated with each movie, and can change the root path with the drop down menus at the bottom but I suggest having each movie path be editable. It is much easier to see which ones are pointing to the wrong folder and reduces the amount of clicks needed to update to the correct path by 3 or 4 for each movie.

Example: 
```
Bad Boys II    S:\MOVIES MASTER\Bad Boys II (2003)                                      [EDIT]
Bad Santa      S:\MOVIES MASTER\Bad Santa 2003  720p BluRay  cp(tt0307987)              [EDIT]
Bad Santa 2    S:\MOVIES MASTER\Bad Santa 2 2016  XviD  cp(tt1798603)                   [EDIT]
Bad Taste      S:\MOVIES MASTER\Bad Taste (1987)                                        [EDIT]
```
Should be edited to
```
Bad Boys II    S:\MOVIES MASTER\Bad Boys II (2003)                                      [EDIT]
Bad Santa      S:\MOVIES MASTER\Bad Santa (2003)                                        [EDIT]
Bad Santa 2    S:\MOVIES MASTER\Bad Santa 2 (2016)                                      [EDIT]
Bad Taste      S:\MOVIES MASTER\Bad Taste (1987)                                        [EDIT]
```
You can see which movies don't fit the right naming scheme - Name (Year)

Solution: Add edit button to far right side of each path in the movie editor page, allowing you to edit each one, when editing have a confirm or deny option similar to how the pop up menu works on the movie page. 

Alternatives I've considered were giving access to a text file with the Title and Path associations on it and make that editable in a text application.

**Comment by hotio** [comment]
Click 'Organize'.
