### ISSUE TITLE
Support Compression

### ISSUE THREAD

**Issue by jiBYo** [Radarr/Radarr#284]
Hello,

I am asking that Radarr gains support for Unrar or any sort of file compression. 

Thankyou for your time

**Comment by onedr0p** [comment]
You want Radarr to be able to extract files after they download?

**Comment by jiBYo** [comment]
Yes please

**Comment by ShanDestromp** [comment]
Usenet downloaders already handle this natively (at least, any of the good ones); and it's been a long time since I've encountered a compressed media _torrent._

**Comment by jiBYo** [comment]
Yes they do, I use both SABnzbd and Transmission.  I have come across quite a few using torrents, and even though the majority aren't compressed it's annoying to know you've been waiting for a movie to download for a few days then notice that it was done ages ago but couldn't process because it was zipped...

**Comment by onedr0p** [comment]
This likely won't be supported at least anytime soon, your torrent client should handle unarchiving zips file one way or another.

**Comment by jiBYo** [comment]
I've attempted to use scripts to do it in the past but I ran into problems with Sonarr trying to import files that were only partially extracted... So I pretty much ended up only using btn since I know that tracker never has any zipped files on it.

**Comment by ShanDestromp** [comment]
@jiBYo If I'm not mistaken, NZBGet doesn't mark a file as "complete" until after it's been extracted.  The caveat being the rare case when a release is compressed, and then compressed again (eg you extract all of the r* files, and wind up with another .rar).  To be fair in my _personal experience_, all of those releases are fakes / junk / malicious uploads; although I'm sure legitimate ones exist.

As for torrent handling, a "quick" work-around would be to use a torrent blackhole setup (see https://github.com/Sonarr/Sonarr/wiki/Supported-DownloadClients#torrentblackhole).  Basically Sonarr will grab the .torrent and place it in a "watch" folder; your torrent client of choice needs to support watching folders for new torrent files AND support putting completed downloads in a specific folder (different from the normal "working" folder); and Radarr then watches this "complete" folder to then import the media file.

So long as your "complete" folder isn't setup weird (eg a network folder on a system different from where your media is typically stored), you shouldn't have any cases of Sonarr / Radarr importing files that haven't been completely moved.

A further stop-gap would be to put ALL downloads (torrent and NZB) into an intermediary folder (that Sonarr/Radarr don't know about); and using a small bash script to check that folder.  If it finds a media file, move it to your dronefactory folder for importing; if it finds an archive, extract it and THEN move it to the dronefactory folder.

**Comment by jiBYo** [comment]
Yes I know NZBGet and SABnzbd have built in extraction, it is the torrent side I am getting at. I think file extraction being a part of the program would be best, people that do not know what they are doing so well would probably leave to couchpotato or sickrage just for something like this. You need to remember not everyone is computer savvy or actually knows their way around an os properly, and one of the biggest selling points people look for with technology is how user friendly it is. I know this is free but the point still stands. I'm sure it wouldn't be such a hard thing to add and it would save people a lot of time in the long run.

**Comment by tymanthius** [comment]
I've had so few issues with this, I think it would be better handled with scripts. I use torrents exclusively now.

However, there may well need to be some interesting tweaks/settings done per torrent client.

**Comment by jkaberg** [comment]
IMHO yes, the (torrent) client should handle this. But so very few does (only Deluge does this out of the box AFAIK, and poorly at best)

I hope this get's added some day

**Comment by kniffs** [comment]
I would recommend SimpleExtractor for Deluge, it works better than the built-in function in my experience.

**Comment by onedr0p** [comment]
Closing this request, use the custom script in the connection settings to do this, or your download client

**Comment by Quiksmage** [comment]
where is the "custom script in the connection settings" in radarr? 

Or am I misreading what you said there? It seemed like your message implied to handle it in the torrent client or somewhere else. 

What or where is this "custom script in the connection settings" if not in the torrent client?

Thanks!

**Comment by onedr0p** [comment]
![image](https://cloud.githubusercontent.com/assets/213795/24473586/c8e31b62-1497-11e7-895f-ceec13d7f2e2.png)

**Comment by Quiksmage** [comment]
Thanks for pointing that out for me :)

**Comment by jkaberg** [comment]
I've added an guide for his @ [the wiki](https://github.com/Radarr/Radarr/wiki/Common-Problems#unpack-torrents).

**Comment by Quiksmage** [comment]
If you want to add this to your guide, this will work on qbittorrent.

check the box that says "run external program on torrent completion" and enter the line below into the client. It will unpack the torrent into a folder of the torrent name

"C:/Program Files/WinRAR/WinRAR.exe" x -ibck -inul "%F/*.rar" "%F/"

change path to winrar.exe as necessary

**Comment by mwoodson** [comment]
@jkaberg 
I would like to add a comment here.  In the [wiki](https://github.com/Radarr/Radarr/wiki/Common-Problems#unpack-torrents), there is a problem.  I keep getting partially created files in my movie dir.  I think what is happening is this:

* Deluge Finishes
* Deluge starts extracting
* Radarr sees the partially created file, creates a hard link
* Radarr links it to the right place
* radarr thinks it's done, but it is still extracting.
* radarr deletes the partially extracted file. 
* unhappy watcher of movie cause it's only partially there.

I looked to see if Deluge could wait until things are extracted before being "done".  This isn't possible. 

I added a really hacky fix in the script, a sleep to wait to delete.  So far this is working for me.  My new cleanup script looks like this:

```
#!/bin/bash

if [ -d "$radarr_moviefile_sourcefolder" ] && [ "$(basename $radarr_moviefile_sourcefolder)" = "deluge_extracted" ] ; then

    sleep 300  # This needs to be adjusted to how long the extract takes on the system.  5 minutes is fine here, but if a slower cpu/storage, this might need to be increased.
    /bin/rm -rf $radarr_moviefile_sourcefolder
fi
```

**Comment by levic92** [comment]
@mwoodson @kniffs @jkaberg 

I have made my own plugin for Deluge to better support Sonarr and Radarr, feel free to try it out. It has been working great for me. I am toggling torrent properties so that it doesn't get imported while the extraction is happening.

https://github.com/levic92/LCExtractor

**Comment by jkaberg** [comment]
@mwoodson Haven't seen any issues like that in my setup, but the wiki is open for everyone to edit.

@levic92 Nice work. You should add it to the official plugin list @ deluge website
