### ISSUE TITLE
Profile don't save

### ISSUE THREAD

**Issue by lilp69** [Radarr/Radarr#2841]
Hello,
Version
0.2.0.1051
Mono Version
4.6.2 (Debian 4.6.2.7+dfsg-1)
OS version : Debian

On radarr, I create some profile, but when I click on Save, and refresh the page, I lost my new profile.

Here it's debug log : [v0.2.0.1067] Marr.Data.DataMappingException: The DataMapper was unable to load the following field: 'Cutoff' value: '12'. ID does not match a known quality Parameter name: id ---> System.ArgumentException: ID does not match a known quality Parameter name: id at NzbDrone.Core.Qualities.Quality.FindById (System.Int32 id) [0x00029] in C:\projects\radarr-usby1\src\NzbDrone.Core\Qualities\Quality.cs:189 at NzbDrone.Core.Qualities.Quality.op_Explicit (System.Int32 id) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Core\Qualities\Quality.cs:194 at NzbDrone.Core.Datastore.Converters.QualityIntConverter.FromDB (Marr.Data.Converters.ConverterContext context) [0x00013] in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\Converters\QualityIntConverter.cs:18 at Marr.Data.Mapping.MappingHelper.LoadExistingEntity (Marr.Data.Mapping.ColumnMapCollection mappings, System.Data.Common.DbDataReader reader, System.Object ent, System.Boolean useAltName) [0x00061] in C:\projects\radarr-usby1\src\Marr.Data\Mapping\MappingHelper.cs:66 --- End of inner exception stack trace --- at Marr.Data.Mapping.MappingHelper.LoadExistingEntity (Marr.Data.Mapping.ColumnMapCollection mappings, System.Data.Common.DbDataReader reader, System.Object ent, System.Boolean useAltName) [0x000a8] in C:\projects\radarr-usby1\src\Marr.Data\Mapping\MappingHelper.cs:79 at Marr.Data.Mapping.MappingHelper.CreateAndLoadEntity (System.Type entityType, Marr.Data.Mapping.ColumnMapCollection mappings, System.Data.Common.DbDataReader reader, System.Boolean useAltName) [0x00012] in C:\projects\radarr-usby1\src\Marr.Data\Mapping\MappingHelper.cs:40 at Marr.Data.Mapping.MappingHelper.CreateAndLoadEntity[T] (Marr.Data.Mapping.ColumnMapCollection mappings, System.Data.Common.DbDataReader reader, System.Boolean useAltName) [0x00000] in C:\projects\radarr-usby1\src\Marr.Data\Mapping\MappingHelper.cs:25 at Marr.Data.DataMapper.Query[T] (System.String sql, System.Collections.Generic.ICollection`1[T] entityList, System.Boolean useAltName) [0x0008d] in C:\projects\radarr-usby1\src\Marr.Data\DataMapper.cs:577 at Marr.Data.QGen.QueryBuilder`1[T].ToList () [0x00052] in C:\projects\radarr-usby1\src\Marr.Data\QGen\QueryBuilder.cs:279 at NzbDrone.Core.Datastore.BasicRepository`1[TModel].All () [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\BasicRepository.cs:62 at NzbDrone.Core.Profiles.ProfileService.All () [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Core\Profiles\ProfileService.cs:57 at NzbDrone.Api.Profiles.ProfileModule.GetAll () [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Api\Profiles\ProfileModule.cs:53 at NzbDrone.Api.REST.RestModule`1[TResource].<set_GetResourceAll>b__32_0 (System.Object options) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:111 at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object) at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, System.Threading.CancellationToken context) [0x00049] in <63c44d6f8d7e4f339a987bf9eb94d931>:0 18-6-11 06:20:55.9|Debug|Api|[GET] /api/profile: 500.InternalServerError (8 ms) 18-6-11 06:20:55.9|Debug|Api|[GET] /api/movie?page=1&pageSize=250&sortKey=inCinemas&sortDir=asc&filterKey=downloaded&filterValue=false: 200.OK (35 ms) 18-6-11 06:20:56.1|Debug|Api|[GET] /api/command: 200.OK (1 ms) 18-6-11 06:20:56.1|Debug|Api|[GET] /api/language: 200.OK (1 ms) 18-6-11 06:20:56.1|Debug|Api|[GET] /api/tag: 200.OK (2 ms) 18-6-11 06:20:56.2|Debug|Api|[GET] /api/movie?page=1&pageSize=-1&sortKey=inCinemas&sortDir=asc&filterKey=filterKey&filterValue=filterValue&filterType=filterType: 200.OK (103 ms) 18-6-11 06:20:56.3|Debug|Api|[GET] /api/movies/discover/lists: 200.OK (6 ms) 18-6-11 06:20:56.3|Debug|Api|[GET] /api/series: 200.OK (1 ms) 18-6-11 06:20:56.4|Debug|Api|[GET] /api/config/mediamanagement: 200.OK (1 ms) 18-6-11 06:20:56.5|Debug|Api|[GET] /api/config/naming: 200.OK (2 ms) 18-6-11 06:20:56.5|Debug|Api|[GET] /api/config/indexer: 200.OK (1 ms) 18-6-11 06:20:56.5|Debug|Api|[GET] /api/config/downloadclient: 200.OK (2 ms) 18-6-11 06:20:56.5|Debug|Api|[GET] /api/config/host: 200.OK (4 ms) 18-6-11 06:20:56.5|Debug|Api|[GET] /api/notification: 200.OK (8 ms) 18-6-11 06:20:56.6|Debug|Api|[GET] /api/config/ui: 200.OK (1 ms) 18-6-11 06:20:56.6|Debug|Api|[GET] /api/config/netimport: 200.OK (1 ms) 18-6-11 06:20:56.7|Debug|Api|[GET] /api/health: 200.OK (1 ms) 18-6-11 06:20:56.7|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (1 ms) 18-6-11 06:20:56.8|Debug|Api|[GET] /api/config/naming/samples?renameEpisodes=true&replaceIllegalCharacters=true&colonReplacementFormat=delete&standardMovieFormat=%7BMovie.Title%7D.%7BRelease.Year%7D.%7BQuality.Title%7D&movieFolderFormat=%7BMovie+Title%7D+(%7BRelease+Year%7D)&multiEpisodeStyle=0&includeSeriesTitle=false&includeEpisodeTitle=false&includeQuality=false&replaceSpaces=false&id=1: 200.OK (9 ms) 18-6-11 06:20:56.8|Debug|Api|[GET] /api/delayprofile: 200.OK (3 ms) 18-6-11 06:20:56.8|Fatal|NzbDroneErrorPipeline|Request Failed [v0.2.0.1067] Marr.Data.DataMappingException: The DataMapper was unable to load the following field: 'Cutoff' value: '12'. ID does not match a known quality Parameter name: id ---> System.ArgumentException: ID does not match a known quality Parameter name: id at NzbDrone.Core.Qualities.Quality.FindById (System.Int32 id) [0x00029] in C:\projects\radarr-usby1\src\NzbDrone.Core\Qualities\Quality.cs:189 at NzbDrone.Core.Qualities.Quality.op_Explicit (System.Int32 id) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Core\Qualities\Quality.cs:194 at NzbDrone.Core.Datastore.Converters.QualityIntConverter.FromDB (Marr.Data.Converters.ConverterContext context) [0x00013] in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\Converters\QualityIntConverter.cs:18 at Marr.Data.Mapping.MappingHelper.LoadExistingEntity (Marr.Data.Mapping.ColumnMapCollection mappings, System.Data.Common.DbDataReader reader, System.Object ent, System.Boolean useAltName) [0x00061] in C:\projects\radarr-usby1\src\Marr.Data\Mapping\MappingHelper.cs:66 --- End of inner exception stack trace --- at Marr.Data.Mapping.MappingHelper.LoadExistingEntity (Marr.Data.Mapping.ColumnMapCollection mappings, System.Data.Common.DbDataReader reader, System.Object ent, System.Boolean useAltName) [0x000a8] in C:\projects\radarr-usby1\src\Marr.Data\Mapping\MappingHelper.cs:79 at Marr.Data.Mapping.MappingHelper.CreateAndLoadEntity (System.Type entityType, Marr.Data.Mapping.ColumnMapCollection mappings, System.Data.Common.DbDataReader reader, System.Boolean useAltName) [0x00012] in C:\projects\radarr-usby1\src\Marr.Data\Mapping\MappingHelper.cs:40 at Marr.Data.Mapping.MappingHelper.CreateAndLoadEntity[T] (Marr.Data.Mapping.ColumnMapCollection mappings, System.Data.Common.DbDataReader reader, System.Boolean useAltName) [0x00000] in C:\projects\radarr-usby1\src\Marr.Data\Mapping\MappingHelper.cs:25 at Marr.Data.DataMapper.Query[T] (System.String sql, System.Collections.Generic.ICollection`1[T] entityList, System.Boolean useAltName) [0x0008d] in C:\projects\radarr-usby1\src\Marr.Data\DataMapper.cs:577 at Marr.Data.QGen.QueryBuilder`1[T].ToList () [0x00052] in C:\projects\radarr-usby1\src\Marr.Data\QGen\QueryBuilder.cs:279 at NzbDrone.Core.Datastore.BasicRepository`1[TModel].All () [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\BasicRepository.cs:62 at NzbDrone.Core.Profiles.ProfileService.All () [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Core\Profiles\ProfileService.cs:57 at NzbDrone.Api.Profiles.ProfileModule.GetAll () [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Api\Profiles\ProfileModule.cs:53 at NzbDrone.Api.REST.RestModule`1[TResource].<set_GetResourceAll>b__32_0 (System.Object options) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:111 at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object) at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, System.Threading.CancellationToken context) [0x00049] in <63c44d6f8d7e4f339a987bf9eb94d931>:0

**Comment by Qstick** [comment]
Looks like you are on an older version of custom format branch which is bleeding edge. Either switch to the latest if you are interested in testing, or switch to develop builds if you want something stable.
