### ISSUE TITLE
Missing root folder

### ISSUE THREAD

**Issue by Ashkaan** [Radarr/Radarr#2842]
**Describe the bug**
That message shows under health even though I've removed that root folder from the "Add Movies" > "Bulk Import" window.

**To Reproduce**
1. Add a root folder that exists
2. Delete that root folder so it ceases to exist
3. Remove the entry in Radarr from the "Add Movies" > "Bulk Import" window
4. See error under System > Status

**Expected behavior**
That message should go away (like it did in Sonarr).

**Desktop (please complete the following information):**
 - OS: Docker
 - Mono Version: 5.4.1.6
 - Version: 0.2.0.1120

**Debug Logs**
[radarr.txt](https://github.com/Radarr/Radarr/files/2103495/radarr.txt)

**Comment by hotio** [comment]
Did you change the root folder for your movies using movie editor?

**Comment by Ashkaan** [comment]
Oh damn.  How embarrassing.  That was the answer.  There is no bug.

**Comment by MindyP679** [comment]
I've had this same issue... removed from bulk import and changed in movie editor... still getting message... :/
