### ISSUE TITLE
Error converting value \"@{id=9; name=HDTV-1080p}\" to type 'NzbDrone.Core.Qualities.Quality'.

### ISSUE THREAD

**Issue by MikeBlueIce** [Radarr/Radarr#2843]
**Describe the bug**
Error on PUT  /api/movie/{id}
"Error converting value \"@{id=9; name=HDTV-1080p}\" to type 'NzbDrone.Core.Qualities.Quality'. Path 'movieFile.quality.quality'

**To Reproduce**
Steps to reproduce the behavior (sample using powershell):
$requrl='http://servername/api/movie/ID_NO?apikey=APIKEY'
$movieNewEntryStr=Invoke-WebRequest $requrl -Method Get -ContentType 'application/json'
$movieNewEntry=$movieNewEntryStr.Content| ConvertFrom-Json
$newPath='/newserver/newpath'
$movieNewEntry.folderName=$newPath
$movieNewEntry.path=$newPath
$body=$movieNewEntry | ConvertTo-Json -Compress
$result = Invoke-WebRequest -Uri $requrl -Method Put -Body $body -ContentType 'application/json' 

**Expected behavior**
Should be no error.  If the GET returns with no 'movieFile' field.

**Desktop (please complete the following information):**
 - OS: Windows10 (client), Synology DS916+ (Server)
 - Mono Version: 
5.8.0.108
 - Browser and Version N/A
 - Version 0.2.0.995
**Debug Logs**
Request Failed: Error converting value "@{id=9; name=HDTV-1080p}" to type 'NzbDrone.Core.Qualities.Quality'. Path 'movieFile.quality.quality', line 1, position 1501.

**Comment by galli-leo** [comment]
Please read the wiki. When you put you need to post all of the json retreived by get https://github.com/Radarr/Radarr/wiki/API:Movie
