### ISSUE TITLE
Radarr Periodically Crashes

### ISSUE THREAD

**Issue by mattangelofdeth** [Radarr/Radarr#2848]
Hello,
I have a small issue with Radarr. It appears to be crashing periodically. 

Logs are attached

OS is Server 2012 R2 Standard Edition

Thankyou for your assistance
[radarr.txt](https://github.com/Radarr/Radarr/files/2108832/radarr.txt)

**Comment by hotio** [comment]
Your DB is locked. Did you not read the log?

Also, did you not read this?
```
Bug report
Support requests will be closed immediately, if you are unsure go to our Discord or Subreddit first. Exceptions do not mean you found a bug!
```

**Comment by mattangelofdeth** [comment]
My bad, apologies.
I'm running this on Server 2012 R2 with 16GB RAM
(Thanks for your help)
