### ISSUE TITLE
Unable to manually import movies

### ISSUE THREAD

**Issue by reagw83** [Radarr/Radarr#2849]
Hi, I am new to radarr. I have read the guide on Github and searched online for a few days now and still can’t get it to work, so thought that I’d ask and see if someone can help me.

For starters, I have two folders:
N:\Videos\Movies
N:\Videos\Movies (old)

(Reason for the two folders is because all my collection of movies over the years are in Movies (old), but it is unorganized – some within a folder structure and some not, also the naming is wrong – so I was going to use radarr’s manual import to rename the files while I import. All my new movies and structures will go to \Movies. This is also where all my new movies’ path is pointed to.)

Here goes the questions (bare in mind, I haven’t imported any movies into my \Movies folder yet):

1.	When click “Movies” tab (at the top of the page) on the homepage, I am seeing some 400 odd movies (that I didn’t select nor imported, and some that I don’t even want to watch). Where did this list come from? I am assuming from my List setting, is this correct? (currently I have added IMDB list, popular & top 250 in my list). How do I get this to show only movies that I have, and also movies that I want to monitor and download in the future?

2.	This is the more important question that I want to solve. As mentioned, I want to move my existing movies from one folder (\Movies (old)) to new folder (\Movies) by using Manual import. But when I use the manual import, although it finds the movies, 1. It doesn’t automatically match it to any movies, then 2. When I click to select a movie, the list that I am presented with, is the list that I have in (1) above from the “Movies” tab. For example, my “Movies” tab list doesn’t show “American Pie”, but I have a copy of that movie, and when I want to manually import it, it doesn’t automatically pick the movie up, and I cannot select it from the list, since it’s not part of my “Movies” tab list.

Can someone please help me? Is there a way to get all the movies from imdb? I’d hate having to add the name of each movie I have into the “Movies” tab list individually before I can import it properly.

Note: I also tried using Bulk Import Movies pointing to \Movies (old), but the response is that “No Movies found in folder” – even though I have almost 1,000 movies under that folder.

**Comment by hotio** [comment]
FYI

```
Bug report
Support requests will be closed immediately, if you are unsure go to our Discord or Subreddit first. Exceptions do not mean you found a bug!
```

**Comment by Qstick** [comment]
Use discord for support per @hotio comment
