### ISSUE TITLE
Cookie(s) same as Sonarr

### ISSUE THREAD

**Issue by hotio** [Radarr/Radarr#285]
Radarr is using the same cookie name(s) as Sonarr, so whenever you switch between the two, you'll have to keep logging back in.

**Comment by Wreave** [comment]
How do you access radarr and sonarr? I use a proxy though nginx and do not have this issue. Just wondering the scope of reproducing your issue.

**Comment by hotio** [comment]
http://server:7878
http://server:8989

In my case the domain (server) stays the same, normally with traditional websites we would have different domains, etc.

**Comment by baltoaca** [comment]
I have the same problem. I have an Apache reverse proxy like this:

http://domain/sonarr
http://domain/radarr

Besides the login I also get the movies overview settings in radarr that I set in sonarr and the other way around (table, overview list or posters).

**Comment by Abzie** [comment]
If you keep the tabs open / suspend your system keeping the browser open, you do not run into the cookie issue.

I run nginx reverse proxy with same locations as baltoaca, but to reproduce:
Refresh sonarr to login, then switch to radarr, refresh + login again and switch back and forth f5'ing while being greeted with login prompts.

**Comment by mattman86** [comment]
I'm also seeing that if I make changes such as sorting or day/week/month toggle in the calendar, the change carries over to Sonarr.

**Comment by mmozeiko** [comment]
I have setup like @baltoaca and see exactly same issue as @mattman86. Calendar keeps settings same between sonarr and radarr - view monitored only vs all, month vs week vs day vs list view.

**Comment by Peap0d** [comment]
The values being mentioned above (calendar view, movie sorting) are actually stored using HTML5 web storage, not cookies. The ones I can find the could conflict are:

advancedSettings (used in src/UI/Config.js and src/UI/Settings/SettingsLayout.js)
calendar.view (line 15 in src/UI/Calendar/CalendarView.js)
seriesViewMode (line 192 in both src/UI/Movies/Index/MoviesIndexLayout.js and src/UI/Movies/Index/SeriesIndexLayout.js)

Changing each of these to a distinct value should be the fix.

**Comment by Taloth** [comment]
You only need to deal with it in https://github.com/Radarr/Radarr/blob/develop/src/UI/Config.js.
That's the central spot for all the localStorage stuff. Adding a prefix 'radarr.' in getValue, getValueJson, setValue should be enough.

As mentioned, it only happens when you have a reverse proxy for both sonarr & radarr.

**Comment by galli-leo** [comment]
@Taloth Thanks for the tip!

**Comment by Taloth** [comment]
On a second note, that's different than the auth cookie. So it's actually two separate issues.
