### ISSUE TITLE
Unable to match made for tv movies

### ISSUE THREAD

**Issue by webpeon** [Radarr/Radarr#2851]
I just imported all my movies I already own into Radarr.  I noticed most of them imported and matched correctly to tmdb flawlessly.  It works really well!  There was about a dozen I had to fix by hand because of incorrect matches (less than 1% of my collection), which left me with about a dozen I still could not match to tmdb.  These movies were mainly made for tv movies, or movies that aired in a short series, ie part 1, 2, and 3, on TV and then were released on DVD as a single movie.  I was able to find them in tmdb and put the IDs in Radarr.  However, tmdb categorizes them under the tv category and not movies which has its own IDs.  This causes problems for Radarr.

Some movies would match correctly with their TV id, but Radarr would say the file could not be found.  While others would use the TV tmdb ID and match it to the movie tmdb ID instead.   

Here is a sample of some of the movies that have problems:

- Dr. Horrible's Sing-Along Blog
- Marry Me (2010)
- Police Squad! (1982)
- Shackleton (2002)

Any suggestions?  Thanks

**Comment by galli-leo** [comment]
Unfortunately those cannot be supported, since we rely on tmdb for metadata. Maybe you can add them to the movies there as well?
