### ISSUE TITLE
({Release Year}) is incorrect in filename, but not in folder

### ISSUE THREAD

**Issue by Ashkaan** [Radarr/Radarr#2854]
**Describe the bug**
Radarr automatically renames and folders each release and my setting for this is:

Standard Movie Format: {Movie Title} { [Edition Tags]} ({Release Year}).{Quality Title}
Movie Folder Format: {Movie Title} ({Release Year})

For example, the movie Isle of Dogs (2018) is set to be organized in this way:
Isle of Dogs (2018)/Isle of Dogs (2018).Bluray-2160p.mkv

In some rare cases, Radarr puts the wrong year in the filename, but not the folder, like:
Keloid (2013)/Keloid (2012).WEBDL-1080p.mov

**To Reproduce**
1. Set Folder Settings As Above
2. Import Movie
3. Observer Filename

**Expected behavior**
I would expect that that movie show as:
Keloid (2013)/Keloid (2013).WEBDL-1080p.mov

**Desktop (please complete the following information):**
 - OS: Docker
 - Mono Version: 5.4.1.6
 - Version: 0.2.0.1120

**Comment by galli-leo** [comment]
Reported multiple times already, it's due to the year being only corrected after we get the metadata from tmdb, which is after we create the path.

**Comment by Ashkaan** [comment]
Damn, I'm sorry.  I searched to try to find this and I couldn't find it in the open tickets.  How do we solve; just run a reorganize after?

**Comment by galli-leo** [comment]
Yes, but you also have to use dynamic paths instead of static. If I were you, I just wouldn't care until the new importing system comes along.

**Comment by Ashkaan** [comment]
Thank you!
