### ISSUE TITLE
Radarr won't able automatically grab

### ISSUE THREAD

**Issue by bazza13** [Radarr/Radarr#2855]
Hello I am so close yet so far. I just need one more step to be complete. 
When I add a movie to radarr the only way I can get to download is by pressing the spy glass icon. I can add the movie it will show what it is ment to download and what not to download due to my settings. But won't automatically download. If I manually download it works perfectly.

Using jackett so can get to 4 K movies but even when I wasn't using jackett still wouldn't automatically download...

Radarr version
0.2.0.1120
Mono Version
5.12.0.226 (tarball Thu May 3 10:14:47 UTC 2018)

**Debug Logs:**

# Do not remove anything from your logs and post the full logs! If not everything fits in here use a service like https://pastebin.com to upload them.

**Comment by hotio** [comment]
Do you have RSS Sync/Search enabled?

Radarr does not do auto searching. You either click 1 time on the spy glass or do a manual search, if nothing comes up, radarr will keep on monitoring the RSS Sync for new releases.

**Comment by bazza13** [comment]
Hello. Thanks for the response. 
Yes RSS sync is enabled. 

So for example if I have added a movie to be monitored it recognises that it is missing from my library it will never download untill I have pressed the spyglass at least once?
After I have pressed the spy glass if not movie found it will then monitor the RSS untill available. 
If a release then becomes available after that point it will be hen automatically grab the release as long as it meets my specific profile?

**Comment by hotio** [comment]
If the movie isn't released yet, there's no real need for pressing the spyglass, it also doesn't hurt. For already released movies for which you think there might be releases it is adviced to press it atleast once.

Radarr does not do traditional searches as couchpotato does, when cp would do a search it would fire up a 1000 searches for a 1000 movies, resulting in a 1000 API hits. Radarr just checks every xx couple of minutes the latest releases from your indexer, resulting in 1 API hit.

**Comment by bazza13** [comment]
So technically if I added a movie to be monitored and there is a release available it will be pick up in the RSS syn and grab when the RSS sync time has been meet in my settings?

And this means I would not need to press the spy glass icon.

If that is correct mine is not grabbing it.

But if the spy glass has to be pressed when adding the movie for the first time I may be using the program wrong. 

I have a friend who only has to press the + button to make the movie monitored and radarr will pick the movie up in the RSS automatically and then download.
