### ISSUE TITLE
FEATURE : Auto map folder during "completed download handling" task using user-defined tags.

### ISSUE THREAD

**Issue by Buster14** [Radarr/Radarr#2856]
**Is your feature request related to a problem? Please describe.**
I have huge library based on country released, genre and alphabet 
I constantly have to direct new movies to the correct folder. 
e.g :

Bleeding Steel,

country of release : China

First letter of movie : B

For my library collection, this goes to Asian Movies / B / Bleeding Steel

**Describe the solution you'd like**

The cleanest way is to integrate this with "completed download handling task"
with additional settings page for auto-map folder.
Something like this 
https://i.imgur.com/XIzR9RB.png
The conditions are based on metadatas from tmdb (genres, country released, etc as long as its limited list i guess) and first letter of the movie (a-z and "the" cause i separate "the")

Users can generate as many conditions as they wish..

After a movie is downloaded, 
radarr queries tmdb for complete movie tags, then simply move the media file to the correct folder based on the predefined automap rules.

I dont mind opening a bounty for this, but apparently bounty is just for bugs?

**Comment by hotio** [comment]
This might be of interest for you.
https://github.com/Radarr/Radarr/projects/6

**Comment by Buster14** [comment]
So.. from those posts,, i'd assume it requires alot of reworking on the codes?
Anyway to start a bounty for this feature? I'm willing to donate some and i'm sure alot of people are interested too

**Comment by Qstick** [comment]
Metis needs to be merged first.

**Comment by Buster14** [comment]
I just noticed metis is merged already, so thats what it does, very useful!
But i have a question about the language lookup, does it only match the release name or will it also lookup into tmdb language tags?
If it's the former i'm afraid it wont be useful to my case,
alot of asian and foreign films don't use language name in their release names

**Comment by fryfrog** [comment]
I think language most likely is from the file itself.

**Comment by Buster14** [comment]
If you mean by file name then not all releases have language names on it.

**Comment by fryfrog** [comment]
Most don't, and are thus assumed to be English (unless you change that assumption). Audio tracks usually have the language specified.

But in any case, your request is a long standing request that is much more difficult than I think anyone besides the developers really understands.

This issue should be closed and you should comment on the feathub request.

**Comment by Buster14** [comment]
Querying from tmdb properties could also work right? Well thats about the only way i see possible

**Comment by fryfrog** [comment]
I guess it depends on what you're talking about. If you want to literally sort by the language of the movie, you clearly have to get that directly from the movie.

But if you wanted to sort by the *original* language of the movie, sure that could come from tmdb.

But this is a lot of detailed discussion about something that I honestly don't think will ever happen. It is a very niche feature that only a select few would use and it will be very developmentally expensive. If this is important to you, your best chance of getting it would be to learn .NET and work w/ the Radarr/Sonarr developers to do this in an acceptable way and get it upstreamed to sonarr and then into radarr.
