### ISSUE TITLE
Radarr won't able automatically grab

### ISSUE THREAD

**Issue by bazza13** [Radarr/Radarr#2857]
Still having issues. Last ticket closed 2855 

Just need one more step to be complete.
When I add a movie to radarr the only way I can get to download is by pressing the spy glass icon. I can add the movie it will show what it is ment to download and what not to download due to my settings. But won't automatically download. If I manually download it works perfectly.
I can select the movie to be monitored it will show missing from the selected location. I can press refresh library refresh RSS sync won't auto grab. If I manually search I can see the release to grab but will only download if I click download. 
Even if I change the quality setting to a higher resolution it won't auto grab the upgraded version. 

I am having the same problem with sonarr as well.

Using jackett so can get to 4 K movies but even when I wasn't using jackett still wouldn't automatically download...

Raspberry pi running

Radarr version
0.2.0.1120
Mono Version
5.12.0.226 (tarball Thu May 3 10:14:47 UTC 2018)

**Comment by hotio** [comment]
There's a reason it got closed, please read the rules. Do not spam.

**Comment by Qstick** [comment]
Go to discord for support if you are still having issues with this
