### ISSUE TITLE
'Ignore subfolders' option for Manual Import

### ISSUE THREAD

**Issue by DarkwaterV3** [Radarr/Radarr#2858]
When I point Radarr (or Sonarr for that matter) to a folder that has both video files in its root as well as in its subfolders, Radarr can take substantially longer to analyze the folders than it would take to analyze a folder containing, for example, only one video file and no subfolders. This additional wait time is frustrating when I want Radarr to import a video file that I know is in the root of the folder.

QBitTorrent is known to not create a subfolder for torrent downloads that contain only one file. 2+ files do get a folder, even if the torrent itself does not have one but the option to add one is enabled in QB. If QB would put even single-file torrents in their own subfolders, this would not be an issue for me.

I'd like to see an option added to ignore subfolders. Seeing as the need to include or exclude subfolders can vary between individual import actions, it makes sense to me that an 'include subfolders' checkbox would be placed in the 'Manual Import - Select Folder' dialog window.

I suppose an alternative would be to temporarily move the video file I want to import to a more 'secluded' location and move it back when I'm done importing. But this would substitute a frustrating wait with a frustrating extra action on the user's part, when the proposed feature seems, in my humble opinion, relatively simple to implement.

Thanks.

**Comment by hotio** [comment]
If it is such a frustating thing for the user to take extra action, I can't imagine the frustation a developer must undergo to implement such a simple feature.

Vital info is missing...Why does it take long? How many torrents are there?

**Comment by DarkwaterV3** [comment]
2.26 TB, 9696 files, 298 folders, ~170 torrents. Scan for import takes between 6 and 7 minutes. Storage medium is an external hard disk drive connected via USB 2.

For comparison, with the same setup but scanning a folder with 20 video files and nothing more, scanning takes less than 10 seconds.

**Comment by hotio** [comment]
Probably the USB 2 part being the problem

**Comment by DarkwaterV3** [comment]
I'll run a test with the drive hooked up via Sata 3 when I get home. I'll defragment it before the test while I'm at it. 

In the meantime, I'd be interested to hear your reasoning for that assumption. You cannot deny the drive has a large amount of varied content.

**Comment by hotio** [comment]
Usb2 is incredibly slow, it is indeed a fair amount, but it is also a feature you only rarely need.

**Comment by DarkwaterV3** [comment]
I don't think the usb 2 bandwidth is the issue here. The folder contains 2.26 TB of data, yes, but all that data doesn't need to pass through the cable during the folder analysis we're talking about. All Radarr needs are filenames and filesizes. So we're not talking about sequential read operations, which would easily max out the bandwidth, but instead we're talking about random read operations, fetching that metadata, which is less bandwidth-heavy and concentrates the workload on the read head of the drive, which is moving all over the place to catalogue all the content. The interface to the pc is left largely unused while it waits for the read head.

That's why, at least with SSDs nowadays, specs pages include both sequential and random r/w speeds. We're talking about the latter, not the former.

While I was writing this comment, I double-checked that real quick. Copying a 1.5 GB file from that drive to the internal SSD, read speeds went up as high as 39 MB/s. Not too shabby for USB 2, I must say, but that's beside the point. After that, I repeated the Manual Import action we're talking about. Task Manager showed read speeds topping out at a paltry 100 KB/s, with a K. So I fail to see how the use of USB 3's added bandwidth would make a difference.

I'll do a check over USB 3 later today to verify, but I'm pretty certain what I said here is accurate.

And aside from that, of course better hardware would improve performance, but an ounce of prevention is still worth a pound of cure. I would appreciate more a more powerful import tool and I'm positive I'm not the only one.

**Comment by hotio** [comment]
You are probably right, most of the time will be spent by radarr looking up the file in the database to make a match. But, there is already a powerful import tool, manual import is a last resort.

**Comment by DarkwaterV3** [comment]
And this last resort option has a mildly serious shortcoming, which is why I submitted an issue.

Hell, Bulk Import Movies, which is the powerful import tool I believe you're talking about, could use the same added feature for the same reason: it saves a large amount of time when it's needed.

**Comment by hotio** [comment]
No, Completed Download Handling is what I mean, 99.99 succesrate. But if you created a proper Feature Request issue, I'm sure it'll get added to the list. Just don't get your hopes up it'll be on the top.

**Comment by DarkwaterV3** [comment]
Completed download handling is of no use to new Radarr users with a pre-existing media library. That's referring to a different use case. Past versus future downloads.

I was under the impression that this was the place to submit a feature request, but I see there's [https://feathub.com/Radarr/Radarr](https://feathub.com/Radarr/Radarr) for that. That means that the 'Feature Requests' link under 'Settings > Status > More Info' is wrong, seeing as it points to [https://github.com/Radarr/Radarr/issues](https://github.com/Radarr/Radarr/issues), which is here.

I'll head there, then.

Another thing. You brought snark to this conversation right out of the gate. That's annoying and there's no need for it. If you found something about the tone in my original post offensive, just come out and say that. Escalating a situation with sarcasm is juvenile and doesn't communicate why you're frustrated. I suspect you're mature enough to choose not be a dick. So please, for the sake of everyone you interact with, be a little more kind and patient.

**Comment by hotio** [comment]
New users shouldn't even be using Manual Import. Only Bulk Import.

If people read what they have to do when creating a new issue and follow it, there's no need for getting snarky (not that I am), this just isn't the place to hold everybody's hand. You file a proper bug report/feature request and get out.

I'm sorry if me not saying what you would've liked to hear came across as "snarky".

An issue needs to get to the point real quick, and should contain all of the info required to solve it, nobody cares about your "frustration".

Happy coding!

**Comment by galli-leo** [comment]
I would recommend trying to disable analyze video files. It probably won't help (since mediainfo is ran anyways), it is worth a try.

**Comment by bakerboy448** [comment]
Closing
v0.2 is no longer being actively developed.

If this is still an issue/request on recent v3 builds, please open a new issue.
