### ISSUE TITLE
[Feature Request] Sort by Status

### ISSUE THREAD

**Issue by Electronickss** [Radarr/Radarr#2861]
**Is your feature request related to a problem? Please describe.**
So when looking at Movies in the table, there are filters for `released` and `missing only` however there is no way to do both. This would be useful to be able to see what movies are missing **and** available to download

**Describe the solution you'd like**
I would like to be able to sort by status so that I can see them together

**Describe alternatives you've considered**
Being able to export the movie table to CSV

**Comment by Electronickss** [comment]
This is similar to Sonarr, where you can sort by the amount of episodes that have been downloaded vs how many are being monitored

**Comment by hotio** [comment]
![avail](https://user-images.githubusercontent.com/26902309/42085290-4e12082e-7b90-11e8-998a-c24aa3dd7791.png)

**Comment by Electronickss** [comment]
I suppose from the `Wanted` section instead of `Movies` is good enough
