### ISSUE TITLE
[Feature Req] When deleting a movie in Plex, Delete and ignore in Radarr

### ISSUE THREAD

**Issue by injector22** [Radarr/Radarr#2862]
When using lists and having a non-tech friendly family something annoying tends to happen. Someone in the family will use the Plex UI to delete a movie which removes the source files, then Radarr does a scan detects the files are missing but the title is still monitored it will then re-download the title. Even having an option to un-monitor after a successful download would be better than nothing.

**Comment by hotio** [comment]
Ignore deleted...

Turn it on
