### ISSUE TITLE
Can't add Couchpotato list

### ISSUE THREAD

**Issue by oopsydaisy74** [Radarr/Radarr#2863]
**Describe the bug**
When trying to add Couchpotato list, it tests fine. I can't seem to select a folder, so when I try to save I get "Invalid Path".

**To Reproduce**
1. Go to 'Settings/Lists'
2. Click on 'Add/Couchpotato'
3. Fill in info. Can't select folder as the field/dropdown won't allow typing and it doesn't bring up a finder navigator.
4. When trying to save, get "Invalid Path" and the list can't be saved.

**Expected behavior**
Should be able to select or type in a directory path.

**Screenshots**
![screen shot 2018-06-29 at 1 23 47 pm](https://user-images.githubusercontent.com/40699695/42105826-d23a8608-7b9f-11e8-986e-148895222418.png)
![screen shot 2018-06-29 at 1 24 20 pm](https://user-images.githubusercontent.com/40699695/42105835-dacc5e22-7b9f-11e8-8f68-58a91237094f.png)

**Desktop (please complete the following information):**
 - OS: MacOS 10.13.5
 - Mono Version: 5.12.0.226
 - Browser and Version Safari 11.1.1
 - Version 0.2.0.1120

**Debug Logs**
[radarr.txt](https://github.com/Radarr/Radarr/files/2150305/radarr.txt)

**Upload the full log file here (or another site and link it). Issues will be closed, if they do not include this!**

**Comment by hotio** [comment]
Import one movie, before you start using a list.
