### ISSUE TITLE
Media management settings keep resetting

### ISSUE THREAD

**Issue by oopsydaisy74** [Radarr/Radarr#2865]
**Describe the bug**
After changing the settings in Media management tab and saving, after a few minutes, the settings will return to default. Specifically the movie naming, analyse video files and file import.

**To Reproduce**
Go to Settings/Media Management.
Enable Rename Movie. Default settings.
Enable Import Extra Files. Add idx, sub, mov, nfo.
Disable Analyse Video files.
Save.
Go to Wanted.
Go back to Settings/Media Management.

**Expected behavior**
Settings should remain after saving and navigating to other sections.

**Screenshots**
![screen shot 2018-06-30 at 10 09 18 am](https://user-images.githubusercontent.com/40699695/42125966-217f73dc-7c4e-11e8-88f9-9952623db054.png)
![screen shot 2018-06-30 at 10 09 55 am](https://user-images.githubusercontent.com/40699695/42125970-27692c8e-7c4e-11e8-8f24-31717d4adac0.png)

https://www.dropbox.com/s/sby7cj8jpkkkh7q/Settings.mov?dl=0

**Desktop (please complete the following information):**
 - OS: MacOS 10.13.5
 - Mono Version: 5.12.0.226
 - Browser and Version Safari 11.1.1
 - Version 0.2.0.1120

**Debug Logs**
[radarr.txt](https://github.com/Radarr/Radarr/files/2151788/radarr.txt)

**Comment by Qstick** [comment]
I'm unable to reproduce this, it's working fine for me. Are you seeing any JS errors in console? Can you a different browser or incognito mode to make sure its not some kind of cache issue.

Also the logs you provided are info level and not debug level.
