### ISSUE TITLE
[Feature Request] Add custom movie titles

### ISSUE THREAD

**Issue by IhToN** [Radarr/Radarr#2866]
As a Spanish user, there are a lot of movies which has their own Spanish Title, already recognized on TheMovieDB or IMDB but, for some reason, Radarr can find them on my indexers (private trackers which doesn't have IMDB search but Title search).

I guess a really nice solution, as sometimes the movie titles in other languages are not picked automatically, is the possibility to add custom movie titles to the serie in the "Titles" tab.

I've checked this is happening on some movies such as Moana/Vaiana and The Dark Knight/El caballero oscuro:
![imagen](https://user-images.githubusercontent.com/16889094/42128782-9cf0efcc-7cb3-11e8-884d-4b90a2cc20bd.png)
![imagen](https://user-images.githubusercontent.com/16889094/42128787-aa739578-7cb3-11e8-952e-d3f2e27921ed.png)

So having a little icon to add custom movies to the Titles to search for would be really nice.

Thanks in advance.

**Comment by IhToN** [comment]
The problwm is still the same, it's not able to find any chapter.

Also I think that there is already a method to add custom titles but only
when a file is found but the name is not exactly the same.

**Comment by flcowboy7** [comment]
+1 from me. Where does Radarr get it's alternative titles from as shown in the OP's screenshot? I was just looking at Harry Potter and the Philosopher's Stone, which is the original title, but was titled as Harry Potter and the Sorcerer's Stone in the US. The alternate title is listed on TMDB, but Radarr isn't picking it up.

Alternative Feature Request from the OP: Allow users to add alternate titles based on some pre-existing database list (such as TMdb).

If neither feature request can be implemented, I'd really like to know where Radarr grabs the alternate titles from, so I can suggest the additional alternate title to the source.

**Comment by galli-leo** [comment]
@flcowboy7 It gets the alternative titles from tmdb, not sure why it‘s not showing up for you, I would take a look at the logs.

In the future, I would like users to be able to add metadata to the tmdb data. But that‘s still some time off

**Comment by flcowboy7** [comment]
I just tried refreshing it and the two US alternate titles magically appeared (no pun intended). But there doesn't seem to be a way to choose the default tile from the list. So I am stuck using the default title as listed by tmdb :(

**Comment by galli-leo** [comment]
@flcowboy7 Yes that's something that will come in the future with api v3

**Comment by theerror** [comment]
just adding my point to this, as just wanted to create the same request. 

- possiblity of eddit / update alternative names
- fix loading also other languages, other then default one (ex. I'm czech, however there is not czech language at all, even, that such exists in TMDB DB)
- it would be fine to be able to set, which title will be used in search, if all possible aren't. As I know, that there is such title in original language (Swedish) and in Czech, but not in english, so clicking on search will not show all possible results and there is no way, how to change it.

**Comment by bakerboy448** [comment]
Closing
v0.2 is no longer being actively developed.

If this is still an issue/request on recent v3 builds, please open a new issue.

V3 has significant language improvements
