### ISSUE TITLE
Critical: subfolder with same name as main folder removes all files

### ISSUE THREAD

**Issue by Mizio66** [Radarr/Radarr#2867]
I have (had ...) a folder named Italian Movies, main one, with several subfolder with movies. One of these subfolder/movie was named Italian Movies (2012).
When importing the movies from that main folder, ALL movies in subfolders (but not the subfolders) were deleted... i saw in teh log several actions on Italian Movies being removed for upgrade.

Can this be fixed (I removed that freaking movie in the while I redownload all of them).

thanks

**Comment by hotio** [comment]
```
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Mono Version: [e.g. Mono 5.8] (Only needed under Linux and Mac, found under System -> Status)
 - Browser and Version [e.g. chrome, safari] (Only needed for UI issues)
 - Version [e.g. 22]

**Debug Logs**
Turn on debug logs under Settings -> General and wait for the bug to occur again. **Upload the full log file here (or another site and link it). Issues will be closed, if they do not include this!**

```

**Comment by Mizio66** [comment]
1. Create a folder
2.Create some subfolder, create files in the subfolders.
3. Create a subfolder with teh same name as the main folder (i.e. main Italian, sub italian)
3. Go to Add movies, bulk import, select Main folder and then all subfolders/files
4. import all
5. all files will be gone (at least happened to me)

**Expected behavior**
Movies imported

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: synology 6.2
 - Mono Version: 5.8
 - Version 0.2.0.1120

**Debug Logs**
Won't test it again, sorry.

This is the log, several times, each time for a file, i imagine:
18-7-2 17:09:04.8|Info|MovieService|Linking [Italian Movies.avi] > [[tt1942929][Italian Movies (2013)]]
18-7-2 17:09:06.1|Info|RecycleBinProvider|Recycling Bin has not been configured, deleting permanently. /volume1/video/Italian Movies/Italian movies/Italian Movies.avi

**Comment by Mizio66** [comment]
Why was this closed?
Giving no reason doesn't help for the next time (apart the fact I think this is an issue)

thanks

**Comment by galli-leo** [comment]
> Upload the full log file here (or another site and link it). Issues will be closed, if they do not include this!

Even if you don‘t have a debug log you still need to upload the full file.

**Comment by Mizio66** [comment]
ok. This attached is the log at the moment, I think. thanks and sorry.
I exported from the log.db as it was > 2 days ago- starts at line 55490 and less.
https://drive.google.com/open?id=1SUXIOCpYwDZ_IAvT6_508rLvY27ID52D
