### ISSUE TITLE
How does download matching work?

### ISSUE THREAD

**Issue by TehWardy** [Radarr/Radarr#2871]
When i ask Radarr to find movies it does a great job on the few sources I have configured, it finds them, downloads them and then looks inside the containing folder and denies the existence of what I deem a perfectly good match both in naming and quality.

How does the matching work? 
Is there a way I can tune / configure it?

It's really frustrating having to do the last part of the process manually all the time (checking and then import in to my media library).

Further to that ... it seems to not want to take items off the list (presumably because of that) so I end up downloading the same thing over and over again.
Kinda fun with a 300mbps connection ... 

Having had another look around ... there's no way i can set any paths to things like my download destination folder (for complete downloads) or my library folder(s).

I have sonarr setup to issue instructions to my download clients (and radarr in this case) and the download client pulls in to an "in progress" folder locally, once complete the download client pushes the complete download to a network share on a nas where sonarr picks them up and does the rename and add to my library but Radarr doesn't for some reason.

...

I should also add the following (from the docs) ...
  1. I'm running the service using the network service account
  2. I'm hopefully using UNC paths but there doesn't appear to be any UI to check that
  3. My network shares are open to guest read and write access

**Comment by TehWardy** [comment]
Having had another look around ... there's no way i can set any paths to things like my download destination folder (for complete downloads) or my library folder(s).

I have sonarr setup to issue instructions to my download clients (and radarr in this case) and the download client pulls in to an "in progress" folder locally, once complete the download client pushes the complete download to a network share on a nas where sonarr picks them up and does the rename and add to my library but Radarr doesn't for some reason.

**Comment by Qstick** [comment]
Provide debug logs please, and all other info requested in the issue template. Also this is better suited for discord support
