### ISSUE TITLE
[Bug] Localized search doesn't update after change profile

### ISSUE THREAD

**Issue by ivandelabeldad** [Radarr/Radarr#2873]
**Describe the bug**
After add a movie to Radarr using the desired profile, Radarr will throw searchs using original titles and localized titles depending on the desired profile. However, if after a movie is added you manually change the profile (to another language), Radarr will continue using the original language for searchs.

**To Reproduce**
1. Create multiple profiles with different languages.
2. Add a movie using as profile **Language 1**
3. Make a search for it and see how works like a charm.
4. Change the profile to another with **Language 2**.
5. Make a search and it'll continue searching using **Language 1**.

**Expected behavior**
After change between profiles with different languages, Radarr will change it's searches using the new language instead get stuck with the first one.

**Screenshots**

**Desktop:**
 - **OS:** Windows 10 and Linux Ubuntu 18.04 (Dockerized)
 - **Version:** 0.2.0.1120

**Debug Logs**
[https://gist.github.com/ivandelabeldad/ba406c5fa7e84eab3128d4ae0841a0f3](https://gist.github.com/ivandelabeldad/ba406c5fa7e84eab3128d4ae0841a0f3)

I've not seen information about profiles in logs, but between searches I changed the profile of the movie.

**Adittional Information**
The language of the movie (title and description) doesn't update as well.

**Comment by galli-leo** [comment]
You need to refresh movie metadata. Click the refresh icon.
