### ISSUE TITLE
Downloading movies that are not the right length

### ISSUE THREAD

**Issue by ghallford** [Radarr/Radarr#2880]
Description: Radarr has been downloading movies that are not the right length continuously. We have have our DVD quality set at 1GB for a 90 minute movie and 1.75GB for max 90 minute. It is downloading movies that are actually 1.5 - 2 hours long but the actual NZB it downloads has a 45 - 60 minute movie in it. Not the correct move because it is not the correct length but based on it being a 60 minute video and only 690GB it downloads it. This is really getting frustrating. Has been an issue now for a month or so. 

Radarr Version: Nightly

**Comment by Qstick** [comment]
Radarr works by using the known runtime for a movie and multiplying it by the min and max mb/min value that you set for each quality. It then looks for releases in that size range. 

We never actually know what the movie file in the download is until we finish the download and look at the metadata. Thus we are not checking length prior to download, only size based on known length.

Hit discord for help in setting up your profiles to prevent movies you don't want
