### ISSUE TITLE
Batch-Adding Movies

### ISSUE THREAD

**Issue by nickk024** [Radarr/Radarr#289]
Is there any plans to add a feature to batch-add movies that already exist in a folder? The current method is OK for a couple of files, but definitely gets a bit tedious with larger libraries. Loving the fork so far, you guys all rule!

Provide a description of the feature request or bug, the more details the better.
When possible include a log!

Please use our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by onedr0p** [comment]
duplicate #150 please discuss there
