### ISSUE TITLE
[Feature Request] Automatic search for releases where subtitles exist on sub-websites

### ISSUE THREAD

**Issue by lokolako** [Radarr/Radarr#2901]
Hi,

I struggle with automatic search. I have Plex and use Sub-Zero to find subs.
But often it doesn't find any or wrong subs. 

It would be a cool idea to scrape popular sub-websites for subs in specific languages when radarr automatic search on the indexer. 

It's really easy to find releases manually that I know have subs with a quick search on subscene or opensubtitles.

Another thing could be specifing a prioritied releasegroup I know usually have subs in my language. 

The feature would be great under "profiles"

**Comment by Qstick** [comment]
You can use preferred tags to prioritize a release group. As far as prioritizing a release based on existence of subs. Not sure that’s going to be a high priority.

**Comment by lokolako** [comment]
I can't really seam to get preferred tags to work. I put in the name of the release group but it still picks another one. The release criteria should be fine for the profile

**Comment by galli-leo** [comment]
Already possible with custom formats and we won't be adding something that scrapes sub-websites.
