### ISSUE TITLE
Possibility to add the same movie, but with a different language profile

### ISSUE THREAD

**Issue by wsw70** [Radarr/Radarr#2902]
**Is your feature request related to a problem? Please describe.**

I only have the possibility to add one copy of a movie. This is a problem when I want to have several language versions.

**Describe the solution you'd like**

The possibility to add duplicates of a movie with a different profile (in that case - the preferred language). Currently a movie is marked as "Already Exists"

**Describe alternatives you've considered**

The alternate solutions to look for multi-language movies (with several language tracks) but these are not always available.

**Comment by fryfrog** [comment]
Radarr and Sonarr only support one version of a file. They do really odd things when there are multiple. This feature request already exists, find it and comment on it and upvote it. Then close this issue. It'll probably be about multiple versions (like theatrical or directors cut) or multiple resolutions (like 1080p and 4k), but would apply equally to multiple audio versions.

As a terrible, by hand solution... you could rip the audio *out* of another movie and stuff it into the english mkv of the one you already have. Maybe?

**Comment by galli-leo** [comment]
Already requested multiple times.
