### ISSUE TITLE
Preferred tags dont work properly

### ISSUE THREAD

**Issue by lokolako** [Radarr/Radarr#2905]
I use preferred tags to prioritize specific release groups.

Fx I am very interested in en releases from EVO. An example could be:
A.Fake.Movie.2019.720p.BRRip.X264.AC3-EVO

I then use the prefered tag "EVO" (without "-marks) in one of my profiles.
But very often it don't pick the EVO release. The release is fine based on the profile/quality settings and should be picked. I have also tried the tag "AC3-EVO". 

It works sometimes, and sometimes it don't. I have no idea why and when.

Am I doing something wrong?

**Comment by Qstick** [comment]
What are some examples of releases that it picked instead of EVO? A better quality or quality version (proper or repack) will trump preferred words.
