### ISSUE TITLE
Lists - Clean Library Level - 'Keep but Unmonitor' doesn't work

### ISSUE THREAD

**Issue by jusher00** [Radarr/Radarr#2906]
**Describe the bug**
The _Keep but Unmonitor_ option in the Clean Library Level dropdown is broken. The log shows that Radarr finds all the movies that are in my library but not on any of my lists, but they aren't actually unmonitored.

**To Reproduce**
1. Create a list (should work with any, I use a Radarr List)
2. Set the Clean Library Level to _Keep but Unmonitor_
3. Make sure there is at least one movie in your Radarr library that is not on your list
4. Run task _NetImport Sync_
5. Check log, those movies that are not on your list should show with a log message (e.g. `[tt4820284][Obit (2016)] was in your library, but not found in your lists --> Keeping in library but Unmonitoring it`
6. Check the monitored status of the movie, it will still be monitored

**Expected behavior**
When a movie in my Radarr library is not on one of my lists, it should be unmonitored.

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Mono Version: 5.10.1.47
 - Version: 0.2.0.1120

**Debug Logs**
I think logs are not necessary here. If the issue can't be reproduced, I'll gladly provide.

**Ideas**
The associated code can be found in the `NetImportSearchService` class. The logging happens in line 201, and the unmonitoring should be happening in line 202. However, for some reason that doesn't work. I saw elsewhere in the code that a movie is updated after executing changes, e.g. with the `UpdateMovie` method from the `MovieService` class. Might that be the problem? Otherwise I don't get what could be wrong with such a simple statement.

**Comment by Qstick** [comment]
Dupe of #2584 closed by stale bot
