### ISSUE TITLE
Postprocess (import) of file, without quality, Radarr check file content

### ISSUE THREAD

**Issue by jaxjexjox** [Radarr/Radarr#2910]
I would like Radarr to import a file called
"Moviename (Year).ext"  but I would like it to NOT assume it's 720p.
Best if it check the file content, for vertical or horizontal resolution.

I am under the impression (discord discussion) that the package DOES have the code to scan for file CONTENT at the bulk import process.

Example:
A file with this resolution 
1920x1080
With this filename
"Moviename (Year) - LOL-BLAHBLAH-OOPS-WE-FORGOT-QUALITY.mkv"
Should import with
"Moviename (Year) - 1080p.mkv"

(NOTE: the movie which is stinging me, in this particular instance is a resolution of "2.40:1 " NOT 16:9
1920x800  :    I want it to stop importing as "720p"  )

Yes, I could just name it myself, be nice if the package CHECK CONTENT, upon instance of filename not giving it away.
Thanks for your time and effort, appreciated.  I can clarify if required.

**Comment by jaxjexjox** [comment]
To be clear, this is almost a bug.


When a file is imported with a basic filename (no resolution defined) it's making an assumption, instead of just checking the file content, which the package is apparently able to do.

**Comment by Qstick** [comment]
I believe this was recently added in Sonarr and parts have been pulled into custom formats branch. @galli-leo would know for sure though

**Comment by galli-leo** [comment]
This is already implemented on master and correctly implemented on custom formats.

**Comment by jaxjexjox** [comment]
I'm confused, I did this less than 4 days ago and it didn't work?

I'm on
Radarr Ver. 0.2.0.1120


Should I wait X weeks and it'll be fixed?

**Comment by fryfrog** [comment]
It only works in bulk import.

**Comment by jaxjexjox** [comment]
Thank you fryfrog:

That is my point, I feel this should be used at all times or *AT LEAST* used when the filename is not clear.
Fall back to using the 'content.actual.resolution.check' code that exists for bulk import, please.    

Do not wish to import poorly named movies (my fault) with incorrect resolution.

**Comment by galli-leo** [comment]
Yeah sorry should have explained it better, but as fryfrog said, the code is already there, just not used at all times. However, on the custom formats branch, it is used whenever it can be.

**Comment by jaxjexjox** [comment]
So can we consider making use of this code for day to day file imports (in instances of missing qualities in source filename) It would be really nice :)

**Comment by fryfrog** [comment]
@jaxjexjox, if I'm reading right, that'll come with the new custom formats.

**Comment by jaxjexjox** [comment]
Sorry to bug you again,

So to clarify it will come?  
I just want to know an import of
"Really old movie (1945).mkv"  with a crap filename, gets scanned for resolution before rename.

(I admit, this will be a rare occurrence ,but I do get stuff like this, from time to time)

**Comment by fryfrog** [comment]
It is merged now, maybe give it a try? :)

**Comment by jaxjexjox** [comment]
Which version?  I can do some testing.

**Comment by fryfrog** [comment]
Probably makes the most sense to test on the latest nightly, which is 0.2.0.1164.

**Comment by jaxjexjox** [comment]
I'm unsure how to force my install to try nightly train.   Currently have : 

Radarr Ver. 0.2.0.1120

**Comment by fryfrog** [comment]
Somewhere in settings you change a field to "nightly" I think. Shouldn't be too hard.

**Comment by jaxjexjox** [comment]
Ok I just did a test

Put a 1080p movie file in my pre-process folder.
Resolution: (1920x816)

Named it simply
"Moviename (Year).mkv"
Program imported it with:

"So I Married an Axe Murderer - (1993) (Unknown) [tt0108174]"

Why (Unknown) instead of (1080p) ?

**Comment by fryfrog** [comment]
Did @galli-leo maybe mean you'd need to use a custom format and then it'd work? :/

**Comment by galli-leo** [comment]
@jaxjexjox It’s on the latest nightly. Also maybe you dont have media info installes? Thats needed for detecting resolution
