### ISSUE TITLE
[Feature] Table Request view, add column for year, or "Movie Title, Year"

### ISSUE THREAD

**Issue by jaxjexjox** [Radarr/Radarr#2912]
Subject covers all elements of request.  Some enthusiasts have big libraries and there are many films out there, with the same title but you can tell, at a glance if it's the modern or original old version.

etc

Thank you.

**Comment by jaxjexjox** [comment]
Example image to make things easier for development.

https://i.imgur.com/NQEmFg1.png

**Comment by jaxjexjox** [comment]
Yes please consider this it honestly doesn't sound too far either!

Xx thanks

**Comment by jaxjexjox** [comment]
Really? It's such a basic feature...................

**Comment by Qstick** [comment]
Is a column for release date good enough, or do we need one specific to year?

**Comment by jaxjexjox** [comment]
All I need is a way to differentiate films like "True Grit" (new / old) for example.
You could just literally list the films with the year in the title by combining the two.

"Ghostbusters (1984)"  as a movie title
or
"Ghostbusters | 1984" as 2 fields
