### ISSUE TITLE
Feature request: Quality definition maximum size greater range, manual size entry

### ISSUE THREAD

**Issue by tastyratz** [Radarr/Radarr#2914]
Currently, the quality definition slider is adjustable up to 17.57/27.33gb 1 tick before unlimited.

 With UHD/HDR flicks I don't feel that gives me enough adjustment range. I don't want unlimited space and would like to cap downloads myself at 25 or 30gb for a 90 minute, just a little above. I don't want 40gb movies filling my drive, but I'm missing out on a lot of 21/22gb viable options.
The current scale doesn't give sufficient range for larger downloads. 
It would be much easier if I could click an estimate field and type my preferred min/max without using the slider and having the rest calculate.

If not that, I think extending the maximum slider range to 40gb would probably cover the typical encounter in the wild.

**Comment by fryfrog** [comment]
I'm 99.9% sure this is already a feature request, I'd find the existing issue or feathub and comment/upvote it. Once you find it, close this issue.

**Comment by tastyratz** [comment]
You were right, I didn't see it before. It's not quite the way I explained it but is similar enough to this one:

https://github.com/Radarr/Radarr/issues/978
