### ISSUE TITLE
Radarr just deleted 600 movies overnight.

### ISSUE THREAD

**Issue by tusharbhutt** [Radarr/Radarr#2916]
I moved the file locations for the movies in Radarr from referencing a UNC to the drive letter itself (i..e, the files were not physically moved, just the reference to it).

This was done via the Movie Editor and then the new locaiton was confirmed by looking at the updated path.  At 12:40 this morning, Radarr deleted 597 movies.  All of the .NFO and jpg files were moved to the trash bin, but not the movies themselves.  File recovery software couldn't pull the files from the disks, so I'm at a bit of a loss as to where everything went.

I had a look at the log file and this is all I see:

8-7-25 01:12:26.0|Info|RefreshMovieService|Skipping refresh of movie: Zoom and Bored
18-7-25 01:12:26.1|Info|DiskScanService|Scanning disk for Zoom and Bored
18-7-25 01:12:27.1|Info|DiskScanService|Completed scanning disk for Zoom and Bored
18-7-25 01:12:27.3|Info|ExistingMetadataImporter|Found 0 existing metadata files
18-7-25 01:12:27.3|Info|ExistingSubtitleImporter|Found 0 existing subtitle files
18-7-25 01:12:27.3|Info|ExistingOtherExtraImporter|Found 0 existing other extra files
18-7-25 01:12:27.3|Info|ExistingExtraFileService|Found 0 extra files

The only other interesting error I see in the logs is this:

18-7-25 01:12:24.7|Info|RefreshMovieService|Skipping refresh of movie: Zookeeper
18-7-25 01:12:24.7|Info|DiskScanService|Scanning disk for Zookeeper
**18-7-25 01:12:24.8|Error|VideoFileInfoReader|Unable to parse media info from file: B:\Regnum Aegypti\Family Movies\Zookeeper (2011)\Trailers\Zookeeper (2011) 1080p Bluray (2011)-trailer.mov**

[v0.2.0.1135] System.IO.FileNotFoundException: Unable to find the specified file.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.ReadCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.FileStream.Read(Byte[] array, Int32 offset, Int32 count)
   at NzbDrone.Core.MediaFiles.MediaInfo.MediaInfo.Open(Stream stream) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\MediaInfo\MediaInfoLib.cs:line 207
   at NzbDrone.Core.MediaFiles.MediaInfo.VideoFileInfoReader.GetMediaInfo(String filename) in **C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\MediaInfo\VideoFileInfoReader.cs:line 55**

18-7-25 01:12:24.8|Error|ImportDecisionMaker|Couldn't import file. B:\Regnum Aegypti\Family Movies\Zookeeper (2011)\Trailers\Zookeeper (2011) 1080p Bluray (2011)-trailer.mov

[v0.2.0.1135] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.MediaFiles.MovieImport.ImportDecisionMaker.GetDecision(String file, Movie movie, DownloadClientItem downloadClientItem, ParsedMovieInfo folderInfo, Boolean sceneSource, Boolean shouldUseFolderName, Boolean shouldCheckQuality) in **C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\MovieImport\ImportDecisionMaker.cs:line 123**

18-7-25 01:12:24.9|Info|DiskScanService|Completed scanning disk for Zookeeper

I don't have a path called **C:\Projects**, nor am I sure why Radarr is trying to figure out the media data for a trailer.

This is really scary.  I've turned Radarr off because I don't want to lose more movies, and I'll have to do some other work to try to get those files back, but I suspect they're gone.

If anyone has suggestions for what to change and how to recover files, I'd appreciate it.

 OS: Windows 10 Pro 64 bit
Version: Radarr Ver. 0.2.0.1135 (nightly)

**Comment by galli-leo** [comment]
Please post the full log file.

Also am I correct that all movie files were deleted as well? Not only the nfo and jpg files? From what I can tell in the short log snippet, Radarr likely wasn‘t the culprit, since it would have something like, deleting x.mov since no RecycleBin configured. Additionally, it seems it didn‘t even have access to the path?

The C:\project is from the build server and just relates to where the source files are stored.

**Comment by tusharbhutt** [comment]
The .nfo files and .jpg stayed, and the recycle bin is set up.  But you're right, it was not Radarr

It's all good, turns out StableBit DrivePool needed a kick in the nether regions because a drive disconnected and it didn't notify me :)

Thanks for the fast response though and an awesome product.
