### ISSUE TITLE
Allow longer threshold for RSS Sync

### ISSUE THREAD

**Issue by edru** [Radarr/Radarr#292]
Requesting the intervals be converted to hours, or allow the time to be set up to 24-48 hours. TV was a bit more reasonable to search every 15 minutes, but I dont think anyone needs to be hitting every 15 minutes (as default) for movies. I had mine set to 6 hours in CouchPotato, but it seems the max here is 120 minutes.

Settings > Indexers > Option > RSS Sync Interval

**Comment by onedr0p** [comment]
I bought this up in a earlier GH issue glad I'm not the only one who thinks this.

I do think 2 hours should be the minimum and 6 horus the maximum settings.

**Comment by onedr0p** [comment]
I really believe this should be a discussion. I just heard a user from PTP say he reached his api limit. 

Does everyone agree 2 hour minimum, 6 hour maximum?

**Comment by edru** [comment]
I would put an even higher maximum. Honestly I only need to search 2-4 times a day. Personally 24 hour maximum would be my preference.

**Comment by schumi2004** [comment]
I would increase it to 24h max then everyone can decide for themselves

**Comment by onedr0p** [comment]
What about 6 hours minimum (4 times a day) and a 24 hour maximum?

**Comment by edru** [comment]
i like minimum of 4 and max of 24

**Comment by galli-leo** [comment]
But with 6 hours minimum you might miss a lot of releases

**Comment by edru** [comment]
Are you speaking about DMCA? Because with movies I find it's a lot slower, if not at all. We all know when these release to theater and home, so something could even be built around like that similar to CP.

CouchPotato's defaults are basically 8 hours and it works perfectly fine. As said I always have kept mine at 6-12 hour scans and I find literally everything I'm looking for, new or old.

Also, may be apples to oranges, but with something like Mylar where comics only release 1 day a week, I had my scanning set as long as possible because in reality it only had to start looking Wednesday when they were out, and had them all by the end of the day.

TV shows can be anwhere from a 15 minute time slot, to a 2 hour time slot, and new shows drop, literally, that quick. It makes sense to scan quite often, but even then it takes into account "whats newly dropped, and whats already dropped" in it's scans.

So to make a long comment even longer, maybe something is built around release date. If its in the theater it scans X amount of time, if its been released at home it scans X amount of times, and if its been release at home for longer than XXX time, maybe it only scans once a day. I believe sonarr is like this where it knows whats coming because of the calendar and can search quickly for those, where as backlog stuff is only done periodically.

**Comment by vertigo235** [comment]
If it's more than 2 hours you may also want to look into increasing the amount of RSS feed from 100 to something higher.  Wouldn't it be possible for more than 100 releases to occur in 24 hours?  Or does radarr / sonarr already pull more than 100 if it's been a while since an RSS sync has occurred?  I know or does when it has been offline for a while.

**Comment by vertigo235** [comment]
Maybe since movies are different an active search should be performed once or twice a day instead.

**Comment by hotio** [comment]
Please, don't go setting a hard minimum of something like 4-6 hours, that will make Radarr useless for torrents. It should be between 1 and indefinite minutes, a default value of 4-6 hours is OK, but let people who know what they are doing decide for themselves and go low enough, perhaps via advanced settings. If they annoy their indexer, they'll know soon enough.

PS: Is the following api active and working in Radarr?
http://server:7878/api/release/push

**Comment by darzur** [comment]
Up to 12 hours will be OK. It will help all those who have API hit limits and for movies 100 releases should be enough too. Just checked DogNZB and found about 70 releases every 24h.
