### ISSUE TITLE
Radarr / Jackett - No 2160p parsing

### ISSUE THREAD

**Issue by Goofyguf** [Radarr/Radarr#2923]
**Describe the bug**
Unable to parse 2160p movies from Jackett to Radarr.
Manually searching Jackett for 2160p movies turns out fine.
Radarr not able to parse any 2160p movies, highest quality is 1080p REMUX.
Quality in Radarr set to unlimited and profil has Any (also tried with only 2160p).

**To Reproduce**
Add Jackett as indexer and turn on search

**Expected behavior**
Listing 2160p movies

**Screenshots**
Jackett:
http://i67.tinypic.com/2qmq3ox.png

Radarr:
http://i64.tinypic.com/2ynlaif.png

Profiles:
http://i65.tinypic.com/256tzyu.png

Quality:
http://i67.tinypic.com/30bgxgl.png

**Desktop (please complete the following information):**
 - OS: Synology NAS (DSM 6.2-23739 Update 2)
 - Mono Version: 5.8.0.108-11
 - Version: Radarr Ver. 0.2.0.1120 develop

**Debug Logs**
No debug logs to show, since its not showing any bug/error.

**Comment by galli-leo** [comment]
Please always include full log files. Additionally, read the wikipages on FAQ and Common Problems, your issue is explained there.
