### ISSUE TITLE
Index parser and import parser not resolving movie name the same

### ISSUE THREAD

**Issue by obelisk3847** [Radarr/Radarr#2924]
The NZB Jurassic.World.2018.1080p.HC.HDRip.X264.AC3-EVO is correctly being resolved as Jurassic World : Fallen Kingdom and added to the downloader. However when it comes time to import the completed movie the importer is resolving the movie as Jurassic World (2015).

Name: Jurassic World
Source: /home/bergang/radarr_stage/Jurassic World 2018 1080p HC HDRip X264 AC3-EVO/Jurassic.World.2018.1080p.HC.HDRip.X264.AC3-EVO.mkv
Imported To: /home/bergang/movies_gh/Jurassic World (2015)/Jurassic World (2015) - [WEBDL-1080P][AC3 2.0].mkv

![radarrcapture](https://user-images.githubusercontent.com/5290482/43371087-d00bd28a-9358-11e8-83af-bb57cd9b9360.JPG)

Running in Docker on Ubuntu 18.04
Version 0.2.0.1120
Mono Version 5.12.0.301 (tarball Wed Jul 25 15:47:18 UTC 2018)

**Comment by galli-leo** [comment]
Please post your full log files as well as your parser settings
