### ISSUE TITLE
Notify on available

### ISSUE THREAD

**Issue by Tiwas** [Radarr/Radarr#2926]
I don't like to download anything automatically, so I would love to be able to fire off an email to myself whenever a release not already downloaded (or a proper) becomes available. Is this something that could be added?

On another note - the applications looks awesome. Just installed it today to see if it can replace CP.

**Comment by jemus42** [comment]
What I like most about CP is that its dashboard automatically tells me what's available, which is also the feature I'm missing most from Radarr so far.

**Comment by galli-leo** [comment]
You would be better of using something like https://squawkr.io/ for notifications of when releases become available.

@jemus42 Have you tried using the activity / history page? Or are you referring to releases not downloaded by Radarr?
