### ISSUE TITLE
Erroneous sorting

### ISSUE THREAD

**Issue by Tiwas** [Radarr/Radarr#2927]
**Describe the bug**
When sorting by date (at least under wanted) the sorting is incorrectly done, or there's a missing option. If I select to sort by physical release date it will either show releases without a date first (date=blank) or the release which is furthest away. The natural (in my view) way to sort this would be to have the next release on top, not bottom.

**To Reproduce**
1. Go to 'Wanted'
2. Click on 'Physical Release'

**Screenshots**
![capture](https://user-images.githubusercontent.com/17053402/43443016-069309de-94a0-11e8-86a7-9e788fb21930.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10 x64 (both client and server)
 - Browser: Chrome 68.0.3440.75 (Official Build) (64-bit)
 - Version 0.2.0.1120

**Comment by galli-leo** [comment]
This is due to the sorting being done by sql, nothing that can be done until a new ui.
