### ISSUE TITLE
4k UHD is hit & miss

### ISSUE THREAD

**Issue by edru** [Radarr/Radarr#293]
http://imgur.com/a/URulp

Seems it's catching some, and not others.

**Comment by donldmn** [comment]
I think the real issue here is uploading a 4K movie with 2 channel stereo sound.

But really... it seems to be the keywords. Looks like it detects 2160p but not UltraHD or 4K. Seems to be an issue with naming standards.

**Comment by galli-leo** [comment]
If you could provide a full list of movies that weren't matched, it would be very helpful. This way we can more easily test the parser.

**Comment by edru** [comment]
So far it's been anything I throw at it. 

Deadpool
The Martian (doesnt even find any though they are there)
Batman v Superman

(this is all on NZBgeek)

**Comment by galli-leo** [comment]
Sorry I meant to say a full list of movie file names, e.g. Deadpool.2016.4k.UHD.x264-Whatevs

**Comment by cirkator** [comment]
Movies that didn't get picked up by radarr

Deadpool 2016 2160p 4K UltraHD DTS-HD MA 7 1 x264-Whatevs
Deadpool 2016 2160p 4K UltraHD BluRay DTS-HD MA 7 1 x264-Whatevs 
Deadpool 2016 4K 2160p UltraHD BluRay AAC2 0 HEVC x265

The Revenant 2015 2160p UHD BluRay DTS x264-Whatevs 
The Revenant 2015 2160p UHD BluRay FLAC 7 1 x264-Whatevs 

The Martian 2015 2160p Ultra HD BluRay DTS-HD MA 7 1 x264-Whatevs 


Movies that do get picked up
Deadpool 2016 DTS DUAL 2160p Ultra HD BluRay 10bit x265-Whatevs

The names have been changed to protect the guilty... 

I am on version 0.2.0.182

Thank you for this long awaited and much appreciated wonderful piece of software!

**Comment by edru** [comment]
@cirkator thanks for the list. I've been busy lately and hadn't had time to generate one myself. Thats basically the same list I would have used too.

**Comment by cirkator** [comment]
No problem, happy to help out!

**Comment by cirkator** [comment]
Getting picked up:

Into the Inferno (2016) 2160p Netflix WEBRip DD5.1 x264-Whatevs 

The Hateful 8 2015 DTS Dual 4K 2160p DCPRip x264-Whatevs 

Not getting picked up:

Into the Inferno 2016 2160p Netflix WEBRip DD5 1 x264-Whatevs 
TimeScapes 2012 4K 2160p CineForm DTS 5 1 x264-Whatevs

**Comment by galli-leo** [comment]
@cirkator Are you sure the names you provided are exactly as they are displayed in the manual search? Each of them seems to be parsed fine on my end.

**Comment by cirkator** [comment]
They are NOT displayed by the manual search at all. I copied the names from the indexer directly (dognzb) 
They don't show up via automatic or manual search.

**Comment by galli-leo** [comment]
Do you have any logs maybe? I passed the parser exactly the names you gave me and it parses those fine.

**Comment by galli-leo** [comment]
Oh wait I think I see the problem.

**Comment by galli-leo** [comment]
@cirkator Should be fixed in latest nightly (.196)

**Comment by cirkator** [comment]
Thx, that was quick. I am on linuxserver.io docker. Whenever they update, I will test it on my end.
