### ISSUE TITLE
Profile don't save

### ISSUE THREAD

**Issue by lilp69** [Radarr/Radarr#2930]
Hello, since few time, I save my profile but when I refresh page, profile disapear, so Radarr don't DL any movie cause it's doesn't have any save profile. log: https://pastebin.com/dDvnwV8r and https://pastebin.com/yCs9PCJd

Version :  0.2.0.1122 develop
OS : Debian 9.0 on Proxmox

**Comment by galli-leo** [comment]
Were you previously using custom formats branch or metis?

**Comment by lilp69** [comment]
Yes, I use a few metis.

**Comment by galli-leo** [comment]
That is probably the issue then, since I changed how it works. You either have reset the db to something before metis, or manually delete all profiles from the db directly.

**Comment by lilp69** [comment]
How connect to the db? What are credentials default?

**Comment by galli-leo** [comment]
It's an sqlite file, no password needed. sqlitebrowser.org is my preferred choice of editor. It can be found at https://github.com/Radarr/Radarr/wiki/AppData-Directory (nzbdrone.db)
