### ISSUE TITLE
API Command RefreshMovie Not Working

### ISSUE THREAD

**Issue by jt70471** [Radarr/Radarr#2932]
**Describe the bug**
I'm using the radarr API to refresh a movie after I have finished transcoding it. The URL I'm using is http://192.168.1.8:7878/api/command?name=RescanMovie&movieId=499&apikey=xxxxxxxxxx and I receive a 200 OK response, however, the movie is not rescanned and RescanMovie is not shown in the system log output.

**To Reproduce**
1. Issue API command to RescanMovie for a particular movieId
2. Look at movie file in radarr to see if the new file name is updated
3. Check radarr system log for presence of RescanMovie command and it's not found

**Expected behavior**
radarr performs a RescanMovie and the new filename is reflected in the files tab of the movie info.

**Screenshots**
Movie info in radarr before file is transcoded and file type is changed from mkv to mp4:

![image](https://user-images.githubusercontent.com/1010453/43613280-78f69ee8-9674-11e8-87bf-d030263f6a90.png)

Movie info after manually clicking "Update movie info and scan disk":

![image](https://user-images.githubusercontent.com/1010453/43613468-0e8ddcd2-9675-11e8-88ba-780b103140ae.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.13.5
 - Mono Version: 5.12.0.301 (tarball Wed Jul 25 15:47:18 UTC 2018)
 - Browser and Version N/A
 - Version [e.g. 22] Radarr version 0.2.0.1120

**Debug Logs**

[radarr.debug.txt](https://github.com/Radarr/Radarr/files/2255299/radarr.debug.txt)

**Comment by galli-leo** [comment]
The command info must be specified as a json post body.
