### ISSUE TITLE
Sort movies by data added?

### ISSUE THREAD

**Issue by douglas24** [Radarr/Radarr#2946]
Right now the only dropdown sort options are: Title, Downloaded, Profile, In Cinemas

Could you please add an option in the dropdown menu for sorting by Date Added to radarr? The only way to do it at the moment is from table view.

**Comment by galli-leo** [comment]
Already asked in other issues, will come with the new UI.

**Comment by hechz** [comment]
@galli-leo would you be willing/able to direct us to more details on the new UI?

**Comment by galli-leo** [comment]
http://blog.radarr.video/development/update/2018/11/11/roadmap-update.html
