### ISSUE TITLE
RequiredIndexerFlagsSpecification: Value cannot be null. Parameter name: source

### ISSUE THREAD

**Issue by Buster14** [Radarr/Radarr#2947]
**Describe the bug**

whenever i'm trying to search any movies exclamation mark pops up on releases showing

" RequiredIndexerFlagsSpecification: Value cannot be null. Parameter name: source" a bug?

**Desktop (please complete the following information):**
  Windows server 2012 r2
 - Version 0.2.0.1148

**Comment by galli-leo** [comment]
Please post the full log file

**Comment by Buster14** [comment]
https://drive.google.com/file/d/1KYwgZ7I-UsdqxH2nMrCuj5yn2RcBcARt/view?usp=sharing
