### ISSUE TITLE
Searching is a bit too exact

### ISSUE THREAD

**Issue by edru** [Radarr/Radarr#295]
When searching for a movie that is of the same name, but has sequels, it seems if you arent very specific it wont find it.

ie. Back to the Future only pulls the 1 of the 3. It's not until you search for Back to the Future 2, does it find only 2, and so on.

**Comment by galli-leo** [comment]
Since we rely on the movie db API here, there is nothing much we can do :/

**Comment by edru** [comment]
No way to adjust how it searches via API? It seems CouchPotato will pull a handful of request. (if this is impossible excuse my ignorance).

**Comment by galli-leo** [comment]
I am pretty sure there is no way :/ Couchpotato uses its own API.
