### ISSUE TITLE
Prefered Tags are duplicated

### ISSUE THREAD

**Issue by Rouzax** [Radarr/Radarr#2952]
**Describe the bug**
Somehow my Preferred tags are duplicating. I try to remove one all of that instance are removed.

**To Reproduce**
1. Go to Profiles
2. Click on the profile

**Expected behavior**
Only one instance of the tag

**Screenshots**
![image](https://user-images.githubusercontent.com/4103090/43959105-f9b8272e-9cad-11e8-8662-a3af25e8f526.png)

**Desktop (please complete the following information):**
 - OS: Windows 2016
 - Browser and Version:  Firefox 61.0.1 (64-bit)
 - Version 0.2.0.1120

**Comment by galli-leo** [comment]
Just tried to reproduce, and couldn't. Try clearing cache and cookies as well as using another browser.

**Comment by Rouzax** [comment]
@galli-leo Different browser (Chrome) with no chace has the same issue. I think it has something to do with the space in for instance `DTS-HD MA`

**Comment by Rouzax** [comment]
@galli-leo have been testing with this and it looks like they are actually entered duplicate but when I delete a tag all instances are removed from the GUI but not the backend.
So now I delete 1 tag, save the console, close the browser. When I go back the duplicated tags will be back but 1 less.

**Comment by galli-leo** [comment]
The tags are stored in the Sqlite db, take a look at the wiki on where to find that. It's in the profiles table.

Do they immediately appear duplicate upon entering, or only after saving and then reopening the profile edit? A short video demonstration might clear this up as well.

**Comment by Rouzax** [comment]
I don't know for sure how I got the duplicates (might be with copy pasting from CouchPotato), this video shows the deletion of the duplicates and the way it removes all of them and after saving and refreshing having all of them back minus 1.
![radarr](https://user-images.githubusercontent.com/4103090/44990525-8fa6eb80-af91-11e8-89b9-82ac224481f9.gif)
