### ISSUE TITLE
Turning Torrents & Usenet On and Off

### ISSUE THREAD

**Issue by mccorkled** [Radarr/Radarr#2954]
It would be great if there was an option under 'download clients' to turn off torrents or usenet completely. I frequently disable one or the other of my clients but this does not stop searching all of my indexers which can jam up my api calls. It is a pain to have to go through and disable 15+ indexers when a single switch could disable indexers and client at once. 

Thank you

**Comment by bakerboy448** [comment]
Closing
v0.2 is no longer being actively developed.

If this is still an issue/request on recent v3 builds, please open a new issue.

Try Profiles -> Delay Profiles -> {Usenet|Torrents} Only
