### ISSUE TITLE
Make filtering in lists more consistent with each other.

### ISSUE THREAD

**Issue by Rouzax** [Radarr/Radarr#2955]
**Is your feature request related to a problem? Please describe.**
I recently migrated from CouchPotota and one thing that is missing from Radarr is a good way to automate the addition of movies. There are lists that can be used but each source has its own filtering options

Currently these are the options:

TMDB:
- Minimum Vote Average
- Minimum Number of Votes
- Certification
- Include Genre Ids
- Exclude Genre Ids
- Original Language

IMDB:
- No filtering available

StevenLu:
- No filtering available

Trakt:
- Rating
- Certification
- Genres
- Years

**Describe the solution you'd like**
It would be really helpful if each list has the same filtering option

Proposed
- Minimum Vote Average
- Minimum Number of Votes
- Certification
- Include Genre Ids
- Exclude Genre Ids
- Original Language
- Release Years

[AB#869](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/869)

**Comment by galli-leo** [comment]
This will be possible with API v3

**Comment by Rouzax** [comment]
In addition, could you add the following list from IMDB?
[New Movies In Theaters](https://www.imdb.com/movies-in-theaters/)

**Comment by galli-leo** [comment]
@Rouzax I probably will rather add our own, that just looks at release dates, but I can try.

**Comment by Rouzax** [comment]
First of all happy new year to all 🎆 
Curious how far along this is along on the roadmap?

**Comment by galli-leo** [comment]
https://blog.radarr.video/development/update/2018/11/11/roadmap-update.html So no change at all

**Comment by Rouzax** [comment]
I didn't know about that page, thank you.

**Comment by Rouzax** [comment]
Since we are another year 🎆 further 😉 I was wondering if this is still in the pipeline?

**Comment by Qstick** [comment]
Closing for #1576
