### ISSUE TITLE
Specify Download Location for 'Cutoff Unmet' Downloads

### ISSUE THREAD

**Issue by flcowboy7** [Radarr/Radarr#2957]
I just started using Radarr, but am starting to fall in love with it. I really love the cutoff unmet option, as Radarr is now suddenly finding and downloading better quality videos than I previously had. However, it's downloading the new video files to the existing directory where the original movie resides. I guess that makes logical sense, because the system needs to be able to remove the old file and update the database with "cutoff met" or update the quality.

My issue is that I prefer to do manual post processing on every single download. I literally run all my movies through Handbrake, before adding them to my Plex. I have sab configured to always download new movies to a separate directory that is not included in my Plex library (/Movies - New/), so I can process them first. I have HB add a suffix to the movie's filename, so I know that file has been processed. Then I delete the original file and move the processed file to the main movie directory used for one of my libraries in Plex (/Movies/).

With Radarr auto-downloading when cutoff is unmet, there is no longer a method for me to check files that need to be post processed in HB (since they aren't downloaded to a separate directory). I would have to search through every movie sub-directory manually, one by one, which is obviously not efficient.

+++++
**REQUEST:**
I would like the option to set a custom directory for movies downloaded because of cutoff unmet. Then a way to manually mark those downloads as completed or not completed (so Radarr doesn't attempt to keep downloading the same file when it's not found in the same directory as the original).
+++++

As it is right now, I've configured Radarr with a custom directory for the recycle bin (/Moves - Deleted/). So at least I can check that directory for deleted video files, cross-reference the new file and post process it.

+++++
**SUGGESTION:**
I would also think that the specified recycle bin path in Radarr should be set to a default path when Radarr is installed. I would have been very unhappy if I hadn't set that path - only to have all of my long hours worth of post processing magically vanish because Radarr thought it was helping me out by downloading better quality files.
+++++

+++++
**ALTERNATIVE REQUEST:**
In the Activity > History area, I can filter the list by movies that were deleted. So an alternative would be to have the ability to filter the list by movies that were upgraded due to cutoff unmet. If I could easily see that a new movie was downloaded because the previous file didn't meet the cutoff quality, I could quickly scan my local files and post-process them with HB.

Actually, it looks like the list already shows that information, when you click the "i" to see more about the deleted action. Perhaps just adding the "reason" to the list and then being able to filter by reason, would be enough?

![image](https://user-images.githubusercontent.com/42279189/44004694-95d41186-9e34-11e8-8cd4-3be2b25df2ab.png)

However, how long is the activity log saved? I assume it auto-purges records older than a certain time or after the log fills up to a certain point? If so - that could be detrimental, as I download A LOT (I have a movie problem, I know). Just yesterday I probably downloaded a TB worth of files.
+++++

**Comment by galli-leo** [comment]
This will probably not be implemented, as it's a very specific use case.

However, when proteus is complete (still far off), you could have two profiles and two locations:

1. Profile where the cutoff is the lowest quality you want.
2. Profile where the cutoff is the highest quality you want.

This way, Radarr would first download any quality it finds to the first location. Then, when it finds an upgrade, it will download that, but import it into the second location.

Activity history should be stored forever, though I haven't actively checked (I still have activity from the very first day I installed Radarr).
