### ISSUE TITLE
[Feature Request] Add "Device" option for Pushover connection

### ISSUE THREAD

**Issue by ceptonit** [Radarr/Radarr#2959]
**Is your feature request related to a problem? Please describe.**
If you have multiple devices on your Pushover account, using the "Device" option lets us choose on which device(s) we'd like to receive the Radarr notifications.
Without this option, all the devices will receive the notifications.

**Describe the solution you'd like**
Pushover has the device API option already set up.
To push a notification, Pushover API requires token, user, title and message; device is optional, but if specified, the specified device(s) only, will get the notifications.
[https://pushover.net/api#messages](https://pushover.net/api#messages)

So maybe add an extra field under the "User Key" field named "Device(s) (optional)" for Pushover connections?

**Describe alternatives you've considered**
Currently using a custom script connection instead (in this example, for the "on grab" event) to send the notification to my android phone and ipad only:
```
#!/bin/bash

function push {
   curl -s -F "token=abcdefghijklmnopq1234" \
   -F "user=abcdefg0987654321" \
   -F "device=ipad,phone" \
   -F "title=$1" \
   -F "message=$2" https://api.pushover.net/1/messages.json
}

push "Movie on its way..." "${radarr_movie_title} [${radarr_moviefile_quality}] is currently downloading."
```

**Comment by Qstick** [comment]
https://github.com/Sonarr/Sonarr/commit/11acada1ced86aabee8068aa9399443906290769
https://github.com/Sonarr/Sonarr/commit/f2919d371ed17a193099711897ac1f6a7e964c18
