### ISSUE TITLE
Status indication for downloaded movie, but not full quality

### ISSUE THREAD

**Issue by edru** [Radarr/Radarr#296]
Can we make the green "downloaded" button in the status column a different color (orange?) when there is a version of the movie downloaded, but not the final quality.

ie. 
Have movie set to download in 4k, but has only downloaded 1080p, so downloaded button is orange (or whatever color).

**Comment by julestop** [comment]
I would also like to see this. It would give the user confirmation/assurance that Radarr is still looking for the better quality.

**Comment by edru** [comment]
To add, maybe even a purple "Downloading" button to indicate it's actually in progress of downloading.

**Comment by edru** [comment]
This doesnt seem to be an "issue" just a feature request put on hold. BOT

**Comment by Qstick** [comment]
Done in V3 branch
