### ISSUE TITLE
[FEATURE] Force moving file option in Download Handling settings

### ISSUE THREAD

**Issue by hergonoway** [Radarr/Radarr#2961]
**Is your feature request related to a problem? Please describe.**
Download handling feature is very all-in-one server oriented. I've got few seedbox, once a file is downloaded on the distant server it's harlinked into a folder then Syncthing gather this file to the local server, then radarr pickup the file. But since it sticks to the seed logic, it doesn't allow any options like moving the file instead of copying it, which makes sense if you use a distant mounted volume or if your torrent client on the same server. 

In my case my torrent server rules ratio and what to do if it's a private tracker or a public tracker, I'd like to keep that logic to the torrent server side. I sync back to my local server an hardlinked copy of the seeded file once it's downloaded, but since radarr doesn't "move" files, it implies that from time to time I have to purge the sync folder to keep it cleaned. 

**Describe the solution you'd like**
Adding an option to "force moving" the file in Download Handling options or better an option to force delete moved and unused files for these kind of cases. Of course with a "warning" icon explaining the risk if its not duplicated files like other features in settings for uncommon cases.

**Describe alternatives you've considered**
Using a mounted volume, but it's not as flexible as a sync file solution outside the perimeter of radarr. And by experience its not safier nor more reliable than a sync file solution.

I've already checked the hardlink copy mode in media management setting tab in radarr, but I'd really like to keep a sync folder clean when is not used to pass file from a server to another.

**Comment by galli-leo** [comment]
I have marked it as a feature request, but it‘s unlikely to be implemented. I would suggest making a script that periodically cleans up your sync drive

**Comment by fryfrog** [comment]
Use a post processing script that removes the file after import.

https://gist.github.com/fryfrog

^ This pair of scripts is for removing video files from packed torrents and also creating symlinks, should give good examples of how to do what you want (which is super simple in comparison).

**Comment by pryorda** [comment]
+1

**Comment by bakerboy448** [comment]
Closing
v0.2 is no longer being actively developed.

If this is still an issue/request on recent v3 builds, please open a new issue.
