### ISSUE TITLE
Qnap Download

### ISSUE THREAD

**Issue by foXaCe** [Radarr/Radarr#2964]
Hello,

Is it possible to have support for the QNAP Download Station client as a Download Client ?

https://github.com/cyclotron3k/qnap-download_station

**Comment by fryfrog** [comment]
In both Sonarr and Radarr, there is a download client called "Download Station". Is this not what you're hoping for?

I strongly suggest using a mainstream client instead, nzbget or sabnzbd for usenet or deluge, rtorrent or qbittorrent for torrents.

**Comment by Laim** [comment]
Radarr has Download Station in it's current version

https://imgur.com/pAbiyX9

This feature request should probably be closed? @galli-leo

**Comment by fryfrog** [comment]
I *think* maybe Synology and QNAP both named their download client "Download Station", but that they're actually different. :/

**Comment by nfn04308** [comment]
I wanted to confirm that Synology and QNAP both named their download client "Download Station" so this is an open issue. The current "Download Station" in both Sonarr and Radarr seem to only support Synology. I received the error "Unknown exception: HTTP request failed: [404:NotFound] [GET] at [http://10.0.0.200:8080/webapi/query.cgi?api=SYNO.API.Info&version=1&method=query&query=SYNO.API.Auth%2CSYNO.DownloadStation.Task]" when trying to setup Radarr to use the QNAP version of Download Station. Notice the "SYNO.API reference, which is believe is for only Synology. Any help would be greatly appreciated.

**Comment by Laim** [comment]
That would make sense, actually.  It could be the case that the Download Station doesn’t have the same API idea as the Synology one?

Either way - I’d recommend **qTransmission** anyway, I use that and it works amazingly.

**Comment by nfn04308** [comment]
I looked at qTransmission, but I am not able to configure it to work with Keep Solid's VPN Unlimited. QNAP's Download Station allows you to select a VPN Client for all traffic, which makes for an easy setup.

**Comment by Laim** [comment]
@nfn04308 not sure if this will help but from a brief read it might... 

https://www.reddit.com/r/qnap/comments/8l1mv1/i_have_qvpn_running_how_can_i_limit_the_apps_it/

**Comment by nfn04308** [comment]
Thanks for sending, but it seems in the end there was no resolution. There was confusion that the "connect with" feature in QNAP works with qTransmission but it doesn't. Putting your entire QNAP Server on your VPN connection was also a solution mentioned, but not for me or some others as we only want the torrent down loader to be on VPN.

**Comment by Laim** [comment]
@nfn04308 definitely agree not putting the entire qnap on the VPN connection, mildly annoying that the first option didn't work though.  Have you tried looking at the other download options available as well, taking your VPN requirement into account obviously?  The only one I ever tried was qT so one of the others **might** support...

**Comment by nfn04308** [comment]
It seems Transmission in docker (Container Station in QNAP) supports Open VPN connections like Keep Solid's VPN Unlimited so that what I plan to use until the QNAP native Download Station is an option.

**Comment by bakerboy448** [comment]
No plans at this time; plenty of other clients are available. 

...also NAS clients tend to have various issues...
