### ISSUE TITLE
Second manual import before first finishes just disappears

### ISSUE THREAD

**Issue by fbicknel** [Radarr/Radarr#2965]
**Describe the bug**
If a manual import involving moving files is running, and you arrange for another manual import and click 'import' before the first import completes, your second import will silently disappear and never happens.

**To Reproduce**
1. Go to 'Wanted -> Manual Import'
2. Perform a manual import that moves files - this import must run long enough for you to have time to arrange for the next manual import, so you may need to add more than one movie to this first import.
3. Click Import - to begin your manual import.
4. Now repeat the process for a _different_ movie. 
5. Click Import - to begin your second manual import while the first one is still in progress.
6. See - well, nothing. Nothing acknowledges that you have completed the process other than returning to the previous screen. When the first manual import completes, the second does not start.

**Expected behavior**
One of two things:

-   Ideally, my second import is queued so that it will complete when the first one finishes.
-   If that's impossible for some reason, then don't let me close the second import (maybe gray out the import button with a hover prompt saying another import is in progress?) I should be able to cancel my second import, but I should be notified that all my picking and choosing of files and movies will be discarded.

**Screenshots**
If applicable, add screenshots to help explain your problem. <- I didn't think this was necessary.

**Desktop (please complete the following information):**
 - OS: Linux
 - Mono Version: 5.14.0.177 (tarball Mon Aug 6 09:13:43 UTC 2018) --- btw, this is found under System -> About, not System -> Status.
 - Browser and Version chrome
 - Version 0.2.0.1120

**Debug Logs**
https://pastebin.com/0CXqqyLP

**Comment by fbicknel** [comment]
The exception that occurs at line 7715 of the [Debug Logs](https://pastebin.com/0CXqqyLP) occurred about the same time as I whacked 'Import' on the second import.

**Comment by galli-leo** [comment]
Manual Imports should already be queued up. Not sure why the exception there happens though

**Comment by galli-leo** [comment]
I cannot reproduce it on my machine :/ Can you enable trace logging and start Radarr as follows:

/path/to/mono --debug Radarr.exe --debug ?

This way I get an exception stack trace and should be able to look at the manual import command.

**Comment by galli-leo** [comment]
So while I haven't been able to reproduce it, I am pretty sure what the bug is (it's also present in Sonarr). They said, they would fix it and we will pull in the fix. If you could still maybe get the stacktrace and trace log, just to be sure that we are on the right track.

**Comment by fbicknel** [comment]
Assuming this is somehow different than using the trace logs in System->General->Logging->Log Level... I'm off to give it a try.

**Comment by fbicknel** [comment]
Ok - it seems that you _do_ have to turn trace logs on even with the funny startup you mentioned. It also seems that something in that startup method "fixes" the issue: the second operation was queued up and the movie moved as expected.

I'll try restarting through the service and see if it still does it - with trace logs on. This will have to wait until next week.

However, an exception still occurs, so I've [included the logs anyway](https://pastebin.com/AmRWzd41)
