### ISSUE TITLE
FIles are not deleted in ruTorrent after move / renaming

### ISSUE THREAD

**Issue by bilyboy785** [Radarr/Radarr#2968]
**Description:**

FIles are not deleted in ruTorrent after completed renaming / moving.
It's possible ?

Radarr Ver. 0.2.0.1120
LinuxServer Docker Image
ruTorrent v3.8 / rTorrent 0.9.6/0.13.6

**Comment by fryfrog** [comment]
No, and there is even a warning in the download client settings for rTorrent.

![screen shot 2018-08-20 at 3 27 00 pm](https://user-images.githubusercontent.com/87748/44370077-898f1600-a48d-11e8-85a7-43efa2626dcb.png)

You'll use rTorrent to handle the deletion of torrents, by using Ratio Rules and Ratio Groups.
