### ISSUE TITLE
Added a wanted movie that's not released yet, marked as downloaded with a different movie on my disk

### ISSUE THREAD

**Issue by simonk83** [Radarr/Radarr#297]
See screenshot ;)

This is the only movie I've added (I haven't added any of my existing movies either).

Running in a Docker:

Version
0.2.0.152

Mono Version
4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4)

[radarr.txt](https://github.com/Radarr/Radarr/files/710035/radarr.txt)

**Comment by simonk83** [comment]
![img_5964](https://cloud.githubusercontent.com/assets/518440/22008151/94b86282-dccc-11e6-9213-6d3db638de46.PNG)

**Comment by onedr0p** [comment]
What indexer? and please post some logs pertaining to it.

**Comment by simonk83** [comment]
Logs are in the first post ;)

No indexer involved, it didn't download anything, it just scanned my disk and decided that this was the movie I was looking for :D

**Comment by simonk83** [comment]
Want me to enable debug or trace and try it again?

**Comment by galli-leo** [comment]
Did you change the folder for this movie? Because right now it points at the root folder of your movies. Because of that it takes any files in there and assumes they belong to the movie.

**Comment by simonk83** [comment]
Hmm.  I hadn't added a folder at all, so when I went to add the movie I chose "add a different path" in the Path dropdown (as that was the only option).  I then chose my Movies folder.

**Comment by simonk83** [comment]
Something's definitely wonky ;)  I just added another wanted movie and again it marked it as downloaded and chose the same movie (The Unbelievers) ;)

**Comment by simonk83** [comment]
This was my fault, I used {original_folder} in the folder renaming, thought that was enabled 😬
