### ISSUE TITLE
Disable tasks

### ISSUE THREAD

**Issue by Qwatuz** [Radarr/Radarr#2975]
Being able to disable tasks with a simple switch would be great. I could then manually do it when I see fit.

Main issue currently is the Refresh Movie scan takes almost an entire day to complete due to a large movie library. During this time the entire radarr program will become sluggish (mono issues?).

For example adding a new movie, it will rarely load the folder paths even after leaving the page for 20 minutes, as I assume it is still trying to load the data from the database.

https://i.imgur.com/Na9Gx0m.png

**Comment by danjames92** [comment]
I concur, this would be very useful especially given my 33K library.

**Comment by fryfrog** [comment]
Did you disable analyzing files? Are you using cloud storage?

**Comment by danjames92** [comment]
Yes and yes but I'm not sure that it's relevant here.

Options are nice. And changing when scans run definitely has a valid use case.

On 23 Aug 2018, at 15:40, Donald Webster <notifications@github.com<mailto:notifications@github.com>> wrote:


Did you disable analyzing files? Are you using cloud storage?

**Comment by fryfrog** [comment]
I'd love to be able to enable/disable tasks and to set their interval. I'm 98% sure this feature request already exists, I suggest you find it and +1 it or up vote it or comment on it and then close this duplicate.

**Comment by danjames92** [comment]
I've searched but I can't find it...

**Comment by danjames92** [comment]
there is this...

https://github.com/Radarr/Radarr/issues/888

**Comment by fryfrog** [comment]
A quick search of feathub doesn't turn anything up either. Based on the reply in the issue you linked, they're probably not going to want to allow disabling tasks. ;)

**Comment by galli-leo** [comment]
For now try using the THREAD_LIMIT env variable (only works on nightly and is not supported in any way!)

**Comment by fryfrog** [comment]
What does it default to? And what would you suggest? I'm guessing +1?

**Comment by galli-leo** [comment]
@fryfrog 2, there is a max enforced of 10. I suggest number of virtual cores / 2

**Comment by azumukupoe** [comment]
Can't tasks be done simultaneously? It'd be better than disabling in my opinion.

**Comment by azumukupoe** [comment]
I think that multi-threading and running tasks simultaneously would be better than disabling

**Comment by galli-leo** [comment]
@azumukupoe That’s what we are already doing

**Comment by azumukupoe** [comment]
@galli-leo shouldn't the title be changed, then?

**Comment by galli-leo** [comment]
@azumukupoe no why? You cannot disable tasks currently and that’s the feature requested by this issue. But we already execute tasks in parallel and with nightly you can increase the number of concurrent tasks.

**Comment by BanditBanditBandit** [comment]
I am also trying to fix this same issue, the library scans are not wanted as most of my files have been unmonitored but it still goes and fiddles with the movie files. would love to only scan for new files and not movies that are unmonitored.

**Comment by samplethief** [comment]
Agree that we need this. Its unnecessary.

**Comment by tkdrob** [comment]
Any progress made on this?

**Comment by t3knical** [comment]
Give me five days, i should be able to get this sorted, cause scanning my thousands of movies everyday is just not right. you're killing my poor HDD.

**Comment by Qstick** [comment]
This is much improved in Aphrodite. Closing as we have no plans to allow fully disabling tasks at this time.
