### ISSUE TITLE
Feature Request: Ability to add tmdb Collections as Listd

### ISSUE THREAD

**Issue by n1nj4888** [Radarr/Radarr#2977]
Feature Request:

tmdb lists are currently able to be added (popular, list with List ID etc) but it would also be good to have the ability to add tmdb “Collections” as a tmdb list type (format = https://www.themoviedb.org/collection/<COLLECTION_ID>) which would work in the same way as standard tmdb lists work at the moment (format = https://www.themoviedb.org/list/<LIST_ID>)

**Comment by Maximus97** [comment]
As awesome Radarr is I was surprised when I realised this was not a feature.

**Comment by nmbrg** [comment]
any update on this? would be an awesome future not having to manually add every upcoming movie. and instead just add the collection and get every new movie in a series of movies (like avatar, avatar 2, avatar 3 etc..)

**Comment by Qstick** [comment]
It's in process right now.
