### ISSUE TITLE
Additional information in notification titles

### ISSUE THREAD

**Issue by psilynt1** [Radarr/Radarr#2980]
Is it possible to update the notification titles to be more descriptive of what was grabbed/downloaded? Right now, titles are a simple static value which means you have to open your notifications app to see what actually downloaded. It would be super helpful if the title of the notifications included the movie name and possibly the quality instead of it being only in the body of the notification. 

I know enough to be able to poke around in the source code but not enough to really be able to make a real pull request. I believe I found an example of where the notification titles are defined (on a per service basis).

```
/src/NzbDrone.Core/Notifications/Boxcar/Boxcar.cs

const string title = "Movie Downloaded";
```

I think I also found where the body of the notifications are defined.

```
/src/NzbDrone.Core/Notifications/NotificationService.cs

`downloadMessage.Message = GetMessage(message.Movie.Movie, message.Movie.Quality);`
```

Maybe something like this would work?

`string title = "Movie Downloaded - message.Movie.Movie \(message.Movie.Quality\)";`

**Comment by galli-leo** [comment]
Ideally, we would have some sorts of templating engine, like movie naming.

I encourage you to try and make a pull request, since I wont be working on this anytime soon.
