### ISSUE TITLE
FolderQuality is always used, since file quality isn't parsed anymore. Take a look at Sonarr's approach and maybe copy parts of that.

### ISSUE THREAD

**Issue by Maximus97** [Radarr/Radarr#2981]
**Describe the bug**
The bug is that the movie doesn't automatically get imported after download so one has to do a manual import. This happens because Radarr parses the quality or the release as Bluray when searching for the release, but when it begins downloading it parses the release as WEBDL so in the end the file quality does not match the quality of the grabbed release.

**To Reproduce**
1. Grab any movie from YTS.AG
2. Wait for the finish to download
3. Go to activity and see how the movie is stuck there

**Expected behavior**
Get automatically imported

**Screenshots**
![image](https://user-images.githubusercontent.com/42326685/44558846-ba4da480-a746-11e8-8506-f190ff61e92b.png)
![image](https://user-images.githubusercontent.com/42326685/44559886-2c28ec80-a74d-11e8-9ad7-604b3ca7a2a2.png)

The movie gets stuck here so one has to manual import

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Mono Version: 5.14.0.177 (tarball Mon Aug 6 09:07:45 UTC 2018)
 - Version: 0.2.0.1168

**Debug Logs**
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/2316646/radarr.debug.txt)

**Comment by galli-leo** [comment]
After further inspection, it seems like the latest nightly does not parse the file quality correctly. The file you posted should be correctly identified as a BluRay.

**Comment by Qstick** [comment]
This should be resolved in v3
