### ISSUE TITLE
[Feature Request] Download REPACKS for only the release group already downloaded

### ISSUE THREAD

**Issue by Silent-Remux** [Radarr/Radarr#2983]
**Describe the solution you'd like**
If I download a FRaMeSToR release, I don't want a repack from PmP to overwrite it. especially given it's not the same cut.

Here's an example.

![chrome_2018-08-25_12-14-02](https://user-images.githubusercontent.com/16107603/44617754-a6966100-a860-11e8-9c7a-ad3f0a17e54b.png)

**Comment by RoChess** [comment]
Was just about to comment the same after another file got replaced with an incorrect repack.

**Comment by Qstick** [comment]
Just as a reference https://github.com/Sonarr/Sonarr/issues/946
