### ISSUE TITLE
[Feauture Request] - More control over the filter options for shown movies 

### ISSUE THREAD

**Issue by Rouzax** [Radarr/Radarr#2985]
**Is your feature request related to a problem? Please describe.**
It is sometimes hard to filter out movies and do maintenance

**Describe the solution you'd like**
I would like to be able to filter movies on more than is possible now.
Currently I have the options:
* All
* Monitored Only
* Missing Only
* Released
* Announced
* In Cinemas

I would like to do combinations of these, for instance:
* Show me all Missing & Not Monitored
* Show me all Missing & Monitored
* Show me all Not Missing & Not Monitored
* Show me all Not Missing & Monitored

**Comment by galli-leo** [comment]
Already multiple issues open for this. You can get some of those using the wanted tab.

**Comment by Rouzax** [comment]
Sorry, they did not appear in myself search.
