### ISSUE TITLE
'Manual Import' improvements

### ISSUE THREAD

**Issue by 0xdevalias** [Radarr/Radarr#2990]
Recently re-discovered this section of Radarr, and had a few ideas about what would make it more useful:
* Add filters that allow multiple selection, these should all be able to be toggled on/off in any combination. These would help simplify things when working with a large collection (such as importing content from an old/unsorted/unmanged collection). The most immediately obvious to me would be:
  * show/hide rejected
  * show/hide 'unknown/ movie'
* Allow movies to be added. Currently if a movie is unknown, the 'click to select movie' option is available, which brings up the 'Manual Import - Select Movie' dialog, and shows existing entries. It would be useful if this dialog had an 'inline' way of adding new movies, so that the entire collection could be 'created' while processing a single 'manual scan'. It seems perhaps the 'bulk import movies' feature could be combined with this somehow to simplify things the UX? 

I will update this with any other thoughts I have while exploring this feature

**Comment by galli-leo** [comment]
While I have marked this as a feature request, the first one should really be done using bulk import instead.

The second one is already requested in other issues.

**Comment by 0xdevalias** [comment]
Does the bulk import create them as well? I’m always a little hesitant to let fully automated things loose without being able to manually confirm it’s doing what I expect.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by galli-leo** [comment]
@0xdevalias You have to manually confirm them with bulk import.

**Comment by 0xdevalias** [comment]
Good to know. I think I may have tried bulk import originally, and because it failed to identify basically any of the files (due to weird/random naming, unsorted directory structures, etc) I deemed it not really usable in it's current state for my purpose, which is what lead to this issue being created.

**Comment by Zer0Nin3r** [comment]
While I don't have a problem with the naming of the files, Radarr fails to recognize/scan the quality of the file after a bulk import. Everything shows up as _Unknown_. However, when you look a the file path, you can see the codec and the resolution i.e., 1920x1080. Although, the resolution may not be perfect, because Handbrake may apply cropping; nonetheless, you can tell what the resolution is.

**Comment by bakerboy448** [comment]
Closing
v0.2 is no longer being actively developed.

If this is still an issue/request on recent v3 builds, please open a new issue.
