### ISSUE TITLE
Getting "You must be new around here" but "Downloaded and Monitored" is non-zero

### ISSUE THREAD

**Issue by LandonStewart** [Radarr/Radarr#2991]
**Describe the bug**
When clicking "Movies" I see the text `You must be new around here, before you start adding movies you may want to check out the following links on our wiki:` but there are movies in the database and on disk.

See screen shot section...

It works in incognito mode (got this idea from the FAQ).

**To Reproduce**
1. Go to 'Movies'
2. Select UnMonitored from the buttons on the upper right
3. Delete ALL of the ones that are UnMonitored
4. Click on 'Movies' again or refresh the page
5. No movies are listed but the database does have information...
6. Cannot see the menu to change from UnMonitored to All or Monitored etc.
```
Movies 40
Released 24
In Cinemas 12
Announced 4
Downloaded 26
Monitored 40
```

**Expected behavior**

**Screenshots**
<img width="1516" alt="screen shot 2018-08-26 at 12 22 55 am" src="https://user-images.githubusercontent.com/2685312/44625804-7ed9e400-a8c6-11e8-860d-2069f1f42ff5.png">

**Desktop (please complete the following information):**
 - OS: Linux (Ubuntu 16.04.5 LTS (Xenial Xerus))
 - Mono Version: 5.10.1.20
 - Browser and Version: Safari
 - Version: 12.0 (14606.1.36.1.6)

**Comment by galli-leo** [comment]
See previous issues raised about this, this happens when you select a filter that shows no movies. Clear cache and cookies, and all should be good.

**Comment by LandonStewart** [comment]
I see this issue as "Under Investigation" but the stale bot closed the issue.

https://github.com/Radarr/Radarr/issues/1244
