### ISSUE TITLE
Extras, shorts and intros support

### ISSUE THREAD

**Issue by schmittyd** [Radarr/Radarr#2993]
I would like to see support for extras, shorts and intros added to Radarr. Currently, I have to manually move/copy such directories and files to the title's directory, without file renaming.

Perhaps Radarr could detect these directories, and also detect patterns in the filenames, eg. Title.Extra, Title.Short, Title.Intro.

**Comment by bakerboy448** [comment]
No plans at this time.

Various other imports covered under other FR
