### ISSUE TITLE
Grab internal release when available, even if relase of same quality already exist

### ISSUE THREAD

**Issue by intelligence** [Radarr/Radarr#2997]
**Describe the solution you'd like**
I'd love to see an option that forces Radarr to download internal releases even though they've already been grabbed in the same quality. 

Often the first release in any given quality will be of lower quality than the internals subsequently released later on. While getting a release as quick as possible is great, the option to "upgrade" to a better encode when they become available would be appreciated!

**Comment by galli-leo** [comment]
Possible using custom formats
