### ISSUE TITLE
[Enhancement] {Edition Tags} look weird sometimes.

### ISSUE THREAD

**Issue by danjames92** [Radarr/Radarr#2999]
**Describe the bug**

For example I rename my files as follows:
```The Movie Title (2010) [Bluray-1080p - X264 - 8bit - 5.1ch - DTS - EVOLVE - Director's Cut].mkv```

If there is no official directors cut, super cut etc.. I end up with a file name like this

```The Movie Title (2010) [Bluray-1080p - X264 - 8bit - 5.1ch - DTS - EVOLVE - ].mkv```

The space before the end separator looks a bit strange, maybe there could be a default edition or conditional tags i.e. if exists use this, if not don't use?

**Comment by galli-leo** [comment]
Use {- Edition Tags}

Sidenote: I would put the edition tags right after the year (scene naming). Makes it easier for Radarr to parse.

**Comment by danjames92** [comment]
Yes but if there's no edition you still get the weird spacing no?

**Comment by galli-leo** [comment]
@danjames92 No, works with all other tags too, if you include spacing chars inside the braces, you won’t get them on an empty string

**Comment by galli-leo** [comment]
@danjames92 It should auto remove any unecessary spaces. Additionally, you can tuck that into the release group

**Comment by galli-leo** [comment]
I would ask fryfrog on discord, he told me that this was even a possibility
