### ISSUE TITLE
Add Space when replacing ':' with '-'.

### ISSUE THREAD

**Issue by galli-leo** [Radarr/Radarr#30]
This is just a minor annoyance I found.

**Comment by fedoranimus** [comment]
What are the current and expected behaviors?

**Comment by galli-leo** [comment]
Movie Name example: Jack Reacher: No Way Back
Current Behavior: Jack Reacher- No Way Back (Folder name)
Expected: Jack Reacher - No Way Back

Not really important though.

**Comment by AeonLucid** [comment]
This idea works as long as a title doesn't start / end with `:`. Is it safe to assume that doesn't happen?

**Comment by matthewhochler** [comment]
TBH, I think this is a fix that should go into Sonarr proper. It's always annoyed me.

**Comment by galli-leo** [comment]
@AeonLucid I think that's a very safe assumption. In any case, we can just add a quick check.

**Comment by woble** [comment]
In case of `{Movie.Title}` or `{Movie.CleanTitle}` no extra space should be added, i.e. `Movie Title: Something` would be `Movie.Title-Something`.

**Comment by fedoranimus** [comment]
Closing as no longer relevant.
