### ISSUE TITLE
Does not recognize movie quality

### ISSUE THREAD

**Issue by p3s** [Radarr/Radarr#3000]
**Describe the bug**
When searching the movies the same does not identify the category / quality of the movie using private tracke

**To Reproduce**
1. Go to Any movie
2. Click on manual search
3. Scroll down and click on search

**Expected behavior**
Identify the quality of files available for download

**Screenshots**
http://prntscr.com/kow8xh

**Desktop (please complete the following information):**
 - OS: Runing in docker on openmediavault
 - Mono Version: 5.14.0.177
 - Browser and Version [e.g. chrome, safari] (Only needed for UI issues)
 - Version 0.2.0.1120

**Debug Logs**
18-8-30 23:08:23.1|Debug|Api|[GET] /api/log/file: 200.OK (2 ms)
18-8-30 23:08:23.1|Debug|Api|[GET] /api/log/file: 200.OK (3 ms)
18-8-30 23:08:23.3|Debug|Api|[GET] /api/system/task?sort_by=name&order=asc: 200.OK (13 ms)
18-8-30 23:08:23.3|Debug|Api|[GET] /api/system/task?sort_by=name&order=asc: 200.OK (20 ms)
18-8-30 23:08:23.4|Debug|Api|[GET] /api/log/file/radarr.debug.txt: 200.OK (3 ms)
18-8-30 23:08:27.5|Info|NzbSearchService|Searching 1 indexers for [Inception]
18-8-30 23:08:27.5|Debug|Torznab|Downloading Feed http://192.168.1.134:9117/api/v2.0/indexers/bjshare/results/torznab/api?t=search&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060&extended=1&apikey=(removed)&offset=0&limit=100&q=inception
18-8-30 23:08:28.8|Debug|NzbSearchService|Total of 7 reports were found for [Inception] from 1 indexers
18-8-30 23:08:28.8|Info|DownloadDecisionMaker|Processing 7 releases
18-8-30 23:08:28.8|Debug|Parser|Parsing string 'Inception [MKV / H.265 / AC3/DTS / Blu-ray / Dual Áudio / Inglês / 2160p]'
18-8-30 23:08:28.8|Debug|Parser|Unable to parse Inception [MKV / H.265 / AC3/DTS / Blu-ray / Dual Áudio / Inglês / 2160p]
18-8-30 23:08:28.8|Debug|DownloadDecisionMaker|Inception [MKV / H.265 / AC3/DTS / Blu-ray / Dual Áudio / Inglês / 2160p] could not be parsed :(.
18-8-30 23:08:28.8|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] Failed to find movie title in release name Inception [MKV / H.265 / AC3/DTS / Blu-ray / Dual Áudio / Inglês / 2160p]
18-8-30 23:08:28.8|Debug|Parser|Parsing string 'Inception [MKV / H.264 / DTS / Blu-ray / Legendado / Inglês / 1080p]'
18-8-30 23:08:28.8|Debug|Parser|Unable to parse Inception [MKV / H.264 / DTS / Blu-ray / Legendado / Inglês / 1080p]
18-8-30 23:08:28.8|Debug|DownloadDecisionMaker|Inception [MKV / H.264 / DTS / Blu-ray / Legendado / Inglês / 1080p] could not be parsed :(.
18-8-30 23:08:28.9|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] Failed to find movie title in release name Inception [MKV / H.264 / DTS / Blu-ray / Legendado / Inglês / 1080p]
18-8-30 23:08:28.9|Debug|Parser|Parsing string 'Inception [MKV / H.264 / AC3/DTS / Blu-ray / Dual Áudio / Inglês / 1080p / 3D]'
18-8-30 23:08:28.9|Debug|Parser|Unable to parse Inception [MKV / H.264 / AC3/DTS / Blu-ray / Dual Áudio / Inglês / 1080p / 3D]
18-8-30 23:08:28.9|Debug|DownloadDecisionMaker|Inception [MKV / H.264 / AC3/DTS / Blu-ray / Dual Áudio / Inglês / 1080p / 3D] could not be parsed :(.
18-8-30 23:08:28.9|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] Failed to find movie title in release name Inception [MKV / H.264 / AC3/DTS / Blu-ray / Dual Áudio / Inglês / 1080p / 3D]
18-8-30 23:08:28.9|Debug|Parser|Parsing string 'Inception [MP4 / H.264 / AAC / BRRip / Dual Áudio / Inglês / 1080p]'
18-8-30 23:08:28.9|Debug|Parser|Unable to parse Inception [MP4 / H.264 / AAC / BRRip / Dual Áudio / Inglês / 1080p]
18-8-30 23:08:28.9|Debug|DownloadDecisionMaker|Inception [MP4 / H.264 / AAC / BRRip / Dual Áudio / Inglês / 1080p] could not be parsed :(.
18-8-30 23:08:28.9|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] Failed to find movie title in release name Inception [MP4 / H.264 / AAC / BRRip / Dual Áudio / Inglês / 1080p]
18-8-30 23:08:28.9|Debug|Parser|Parsing string 'Inception [MP4 / H.264 / AAC / BRRip / Legendado / Inglês / 1080p]'
18-8-30 23:08:28.9|Debug|Parser|Unable to parse Inception [MP4 / H.264 / AAC / BRRip / Legendado / Inglês / 1080p]
18-8-30 23:08:28.9|Debug|DownloadDecisionMaker|Inception [MP4 / H.264 / AAC / BRRip / Legendado / Inglês / 1080p] could not be parsed :(.
18-8-30 23:08:28.9|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] Failed to find movie title in release name Inception [MP4 / H.264 / AAC / BRRip / Legendado / Inglês / 1080p]
18-8-30 23:08:28.9|Debug|Parser|Parsing string 'Inception [MKV / H.264 / AC3/DTS / Blu-ray / Dual Áudio / Inglês / 1080p]'
18-8-30 23:08:28.9|Debug|Parser|Unable to parse Inception [MKV / H.264 / AC3/DTS / Blu-ray / Dual Áudio / Inglês / 1080p]
18-8-30 23:08:28.9|Debug|DownloadDecisionMaker|Inception [MKV / H.264 / AC3/DTS / Blu-ray / Dual Áudio / Inglês / 1080p] could not be parsed :(.
18-8-30 23:08:28.9|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] Failed to find movie title in release name Inception [MKV / H.264 / AC3/DTS / Blu-ray / Dual Áudio / Inglês / 1080p]
18-8-30 23:08:28.9|Debug|Parser|Parsing string 'Inception [AVI / XviD / AC3 / BRRip / Dual Áudio / Inglês / 720p]'
18-8-30 23:08:28.9|Debug|Parser|Unable to parse Inception [AVI / XviD / AC3 / BRRip / Dual Áudio / Inglês / 720p]
18-8-30 23:08:28.9|Debug|DownloadDecisionMaker|Inception [AVI / XviD / AC3 / BRRip / Dual Áudio / Inglês / 720p] could not be parsed :(.
18-8-30 23:08:28.9|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] Failed to find movie title in release name Inception [AVI / XviD / AC3 / BRRip / Dual Áudio / Inglês / 720p]
18-8-30 23:08:28.9|Debug|Api|[GET] /api/release?movieId=3&sort_by=releaseWeight&order=asc: 200.OK (1502 ms)
18-8-30 23:08:31.3|Debug|Api|[GET] /api/log/file: 200.OK (7 ms)

**Comment by galli-leo** [comment]
Those movies don’t have the year in the title

**Comment by galli-leo** [comment]
Use lenient mapping
