### ISSUE TITLE
Kodi NFO Show ID Improvement

### ISSUE THREAD

**Issue by Redundant1** [Radarr/Radarr#3001]
Radarr creates NFO files like this:

```
<movie>
  <title>Testament</title>
  <rating>6.5</rating>
  <plot>[...snip...]</plot>
  <id>tt0086429</id>
  <year>1983</year>
[...snip...]
```
However, some features require a little bit more info (as described on the [Kodi Wiki](https://kodi.wiki/view/NFO_files#Troubleshooting)), such as the [Lite IMDB Ratings Update](https://forum.kodi.tv/showthread.php?tid=316342) addon.

In this instance, it’s looking for a **uniqueid** field for either IMDB or TMDB.  If the **tmdb** field contains a TMDB identifier, then the **uniqueid** field should be as follows:

```
  <tmdb>21259</tmdb>
  <uniqueid type="tmdb" default="true">21259</uniqueid>
```

If the **id** field contains an IMDB identifier, then the **uniqueid** field should be as follows:

```
  <id>tt0086429</id>
  <uniqueid type="imdb" default="true">tt0086429</uniqueid>
```

Sonarr just implemented code to similarly handle this:  https://github.com/Sonarr/Sonarr/commit/3d7c59bc3bfda8cee274edde5a80d1f98abedf5f

**Comment by Redundant1** [comment]
Do I need to do anything (e.g. reply here) because this was marked as stale by the bot?  I see it's still on the 1.0 milestone, but didn't know what effect the stale flag might have.

**Comment by Qstick** [comment]
#3095 likely needs to be merged first as it’s same files
