### ISSUE TITLE
Radarr stoped working after 1 1/2year. And "pkg install radarr" dosent work

### ISSUE THREAD

**Issue by Melotron** [Radarr/Radarr#3002]
Radarr have been working with out any problems for 1 1/2 year. But 2 days ago it just stopped working. Its runing on a Freenas jail.

When I go in the the jail and manually start Radarr it starts and then noting more:

```
root@Radarr:/.config/Radarr # service radarr onestart 
Press enter to exit...
```

Radarr are not runing when I'am lookin in top
The log are 2 days old with nothing in it that tells me why its not working.

```
Aug 29 20:29 radarr.txt 18-8-29 20:29:17.5|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: "Link to file's." 
18-8-29 20:29:45.7|Info|BackupService|Starting Backup
```

After that the logs just stops. Nothing new radarr.txt after I start it manually.

When I try to reinstall it in a new jail

pkg install radarr

So am I getting an error :

`18-8-31 16:27:16.3|Info|Bootstrap|Starting Radarr - /usr/local/share/radarr/Radarr.exe - Version 0.2.0.1120 18-8-31 16:27:16.8|Info|AppFolderInfo|Data directory is being overridden to [/usr/local/radarr] 18-8-31 16:27:16.9|Info|Router|Application mode: Interactive 18-8-31 16:27:17.1|Info|MigrationLogger|*** Migrating data source=/usr/local/radarr/nzbdrone.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***`

I dont care about my old jail. 
But I do want to find a way to get either the new jail ruining with Radarr or get the old one working.

Could anyone point me in the right direction on how to install and get radarr working again ?? =)

I've tried with locking the sqlite3 but hat dosent help.
`pkg lock sqlite3
pkg update && pkg upgrade`

**Comment by galli-leo** [comment]
> So am I getting an error :

> 18-8-31 16:27:16.3|Info|Bootstrap|Starting Radarr - /usr/local/share/radarr/Radarr.exe - Version 0.2.0.1120 18-8-31 16:27:16.8|Info|AppFolderInfo|Data directory is being overridden to [/usr/local/radarr] 18-8-31 16:27:16.9|Info|Router|Application mode: Interactive 18-8-31 16:27:17.1|Info|MigrationLogger|*** Migrating data source=/usr/local/radarr/nzbdrone.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***

This is not an error, please post the full logs when you go on discord or the Subreddit.
