### ISSUE TITLE
Feature request : Import my watchlist from TheMovieDB

### ISSUE THREAD

**Issue by alexandregregoire** [Radarr/Radarr#3003]
Hey guys,

As a TheMovieDB user I would like to import my watchlist instead of first adding a movie to my watchlist and then to an import list.

Apparently there is a new API (v4) for themoviedb.org and it is possible to get the watchlist using the following url : 
https://api.themoviedb.org/4/account/{ACCOUNT_ID}/movie/watchlist

Thanks for your consideration!
Regards,
Alexandre

**Comment by galli-leo** [comment]
That's already possible with TMDB lists, they have to be public though.

**Comment by alexandregregoire** [comment]
@galli-leo 

That's the problem : I do not want to use lists, I want to use my watch list !

**Comment by Zeusy123** [comment]
I too would like ability to import TMDB WATCHLIST.
REason for this is you cant import into general lists.  You can only import into watchlist or faviouites, which do not have a listid, but only a URL.
