### ISSUE TITLE
BeyondHD states 100% Freeleech

### ISSUE THREAD

**Issue by Metigoth** [Radarr/Radarr#3004]
**Describe the bug**

**To Reproduce**
1. Go to '...' Search
2. Click on '....' Results
3. Scroll down to '....' a release indexed by BeyondHD
4. See error to down arrows indicating 100% freeleech.
BeyondHD used to be ratioless, but it hasn't been for about a year.

Remove the false freeleech from indexer file
 - OS: [e.g. Windows] Debain 9
 - Mono Version: [e.g. Mono 5.8] (Only needed under Linux and Mac, found under System -> Status)Mono JIT compiler version 5.14.0.177 (tarball Mon Aug  6 09:13:21 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          yes(3.6.0svn-mono-/)
        GC:            sgen (concurrent by default)
 - Browser and Version [e.g. chrome, safari] (Only needed for UI issues)

**Comment by galli-leo** [comment]
This is an issue with Jackett
