### ISSUE TITLE
UPDATE INSTALL INSTRUCTIONS

### ISSUE THREAD

**Issue by nickmacwiz** [Radarr/Radarr#3007]
Hey guys,

If the install instructions could be updated under FreeBSD jail install a note to the top could be added. FreeNAS 11.1 or newer users need to do the manual install for jails and must run `pkg lock sqlite3` before continuing install otherwise the install doesn't work. I personally spent a week on this and figured it out by surfing through dozens of forums and would like to save others the time I spent.

**Comment by galli-leo** [comment]
You can edit the wiki pages yourself.
