### ISSUE TITLE
Separate Video Quality from language

### ISSUE THREAD

**Issue by janlimpens** [Radarr/Radarr#3008]
Mangling two complete different concerns such as video quality and language makes no sense at all, it only leads to the repetitious spamming of the same quality setting. After all, who would want a completely different quality for one language than the other?

I currently have to create the same quality setting over and over again, just to be able to get a movie in its original language.

The solution is extremely simple: Remove the language drop down from quality settings and put it into the add movie dialog.

**Comment by galli-leo** [comment]
I think you mean your profile?

If that’s the case, not going to happen but will work better with custom formats and sometime in the future Original Language as Language.

**Comment by janlimpens** [comment]
You are right, I was talking about profiles.

That's a shame because it is terribly user unfriendly to leave it the way it is. But I got to accept that. Thanks anyway for the work you put into this on many accounts marvelous piece of software.
