### ISSUE TITLE
Sharing Indexer and Download Configurationwith Xarr 

### ISSUE THREAD

**Issue by hughesjs** [Radarr/Radarr#3010]
Describe the problem
It's a pain in the ass if you're running Radarr, Lidarr and Sonarr to go around and adjust your indexer and download client settings on each one separately when, in all likelihood, they're nigh identical (except maybe categories).

Describe any solutions you think might work
Either store these settings in an XML file and add a configuration option to set which file to load these configs from or add an export/import indexers mechanic.

Additional context
Sonarr Issue: Sonarr/Sonarr#2725
Lidarr Issue: https://github.com/lidarr/Lidarr/issues/479

**Comment by galli-leo** [comment]
The maintainers of the other Xarr repos have already said everything I have to say about this.
