### ISSUE TITLE
Insufficient Logging

### ISSUE THREAD

**Issue by dale2507** [Radarr/Radarr#3012]
**Is your feature request related to a problem? Please describe.**

I am running Radarr in a docker container. It had been working fine but is now stuck at startup. I believe it is stuck in an infinite loop but it is extremely difficult to tell that cause of the problem.

**Describe the solution you'd like**

More logging available (and at the correct level) so that I can more easily determine the problem or path through the code.

Also it would be good if the logging levels could be checked in PRs somehow.

**Describe alternatives you've considered**

I have increased the logging level to Debug but it is still very difficult to trace the path through the code.

**Additional context**

This is a separate issue (which I am still debugging) but highlights the issue:

No UI is available, the loop appears to be running on the startup thread.

Debug logs from the container:

![image](https://user-images.githubusercontent.com/3359745/45257291-996a8d80-b39b-11e8-8b30-041af6583448.png)
(Redacted text repeats)

As you can see, the loop appears to be occurring when parsing downloaded items but the only logging is from the parser which determines the title, quality, language, etc from the filename. There are no messages to say "Starting discovery of downloaded items in X directory." or "Found downloaded file x, beginning parsing". Messages which I would expect at Info level.

**Comment by galli-leo** [comment]
Radarr will parse movies from your dl client every minute, so that isn‘t actually an issue. Furthermore, you can set the logging level using the config.xml file.

**Comment by dale2507** [comment]
Understood that the loop here is probably the 1 minute polling. I still think there is an issue with insufficient logging though. I changed the logging to debug and still had no idea what was starting the parsing. It seems that the actual title parsing is logged well but the processes which start it need more. A log message of "Starting detection of downloaded movies" even at debug level would have saved me a few hours of trying to work out what was going on.
