### ISSUE TITLE
Indexer issue

### ISSUE THREAD

**Issue by lurcheous** [Radarr/Radarr#3023]
This is probally a silly bug however I have noticed that on NZB that radarr does not search 3020 (Music videos) for Music Films and so it misses music vids that are reconized as film

Ubuntu 18.04 Lts
Full Patched with latest kernel

**Comment by galli-leo** [comment]
Have you tried manually adding that category via advanced settings?

**Comment by lurcheous** [comment]
yes doesn't always index
