### ISSUE TITLE
Adding IMDb watchlist not working

### ISSUE THREAD

**Issue by maddhin** [Radarr/Radarr#3024]
Hi,

I just tried to add my IMDb watchlist but I only get the following error message:

"Unable to connect to indexer. Indexer responded with html content. Site is likely blocked or unavailable."

Is there anything I do wrong or where could the error be?

**Comment by fryfrog** [comment]
I believe IMDb blocked a bunch of the types of lists you could use in Radarr. Hopefully someone who knows more can comment. Wouldn't be a bad idea to hop on Discord and ask.

**Comment by galli-leo** [comment]
Please post your full debug log file. Seems you have issues connecting to the Radarr API.
