### ISSUE TITLE
More control on the max size sliders

### ISSUE THREAD

**Issue by shareonline** [Radarr/Radarr#3025]
As more and more of us are beginning to use 4K videos more, it would be nice if the max sliders could go beyond 30gb.
Either as a slider up to 150gb or the choice to manually enter the max size. 

Would you implement this?

**Comment by galli-leo** [comment]
You can enter the max size yourself on the latest nightly

**Comment by shareonline** [comment]
Nice! Looking forward to public release 😊👍

**Comment by shareonline** [comment]
Hehe any idea when this feature will make it to the develop branch? 😊

**Comment by galli-leo** [comment]
Hopefully in a week or two
