### ISSUE TITLE
Question about API endpoint POST /movie parameter images

### ISSUE THREAD

**Issue by Brianbrifri** [Radarr/Radarr#3026]
**Description:**
Hello, I am using your api for movies. I have a question about one of the parameters: `images`. What exactly goes in here? A url?

**Radarr Version:**
Latest

**Comment by Brianbrifri** [comment]
So I see from the GET that images look like this:
```
"images": [
      {
        "coverType": "poster",
        "url": "/radarr/MediaCover/1/poster.jpg?lastWrite=636200219330000000"
      },
      {
        "coverType": "banner",
        "url": "/radarr/MediaCover/1/banner.jpg?lastWrite=636200219340000000"
      }
    ],
```
My question now is do those images need to exists when when I make the post? And what is the lastWrite value?

**Comment by galli-leo** [comment]
No you don't need to post the images, Radarr will download them itself.
