### ISSUE TITLE
Set Trakt list max limit to 2000

### ISSUE THREAD

**Issue by azumukupoe** [Radarr/Radarr#3028]
Because it's the current limit set by Trakt for each list.

**Comment by rfgamaral** [comment]
@azumukupoe You can ser your own limit to 2000. What exactly are you requesting here?

**Comment by azumukupoe** [comment]
Or maybe show a warning regarding the cap?

**Comment by fryfrog** [comment]
If you add more details and make this a useful issue, please re-open. :)
