### ISSUE TITLE
manually insert magnet link/torrent

### ISSUE THREAD

**Issue by icf20** [Radarr/Radarr#3030]
**Is your feature request related to a problem? Please describe.**

well there are plenty of trackers that are not english and are not supported by radarr or jackett

**Describe the solution you'd like**

radarr is awesome at cleaning and renaming stuff so i would like to still use it for that while i manually insert a magnet/torrent link to item that have the missing tag and let the automation do the dirty work :)   

maybe the profile need to automatically be changed to any

**Describe alternatives you've considered**
downloading everything manually then import stuff in radarr

**Comment by fryfrog** [comment]
Radarr and Sonarr will happily import anything in your download client w/ the right label as long as they can parse the title from it. If the title of the download doesn't match, you can change it there so it does or just do a manual import after it finishes and pick which movie it is.

**Comment by icf20** [comment]
@fryfrog hmmmm so the year is a must to work correctly and simply placing imdb id ttxxxxx wont work

**Comment by fryfrog** [comment]
I believe so, but maybe a decent little feature request would be to use tt in file name to do lookup! :)
