### ISSUE TITLE
When I add a new movie from say upcoming, it scrolls back to top!

### ISSUE THREAD

**Issue by seitzbg** [Radarr/Radarr#3031]
**Is your feature request related to a problem? Please describe.**
When I add a new movie from say upcoming, it scrolls back to top so I have to scroll back down to where I was in the list!

**Describe the solution you'd like**
Do not scroll back to the top after adding the movie.

**Describe alternatives you've considered**
None, ideas welcome.

**Additional context**
N/A.

**Comment by galli-leo** [comment]
Duplicate of #2781
