### ISSUE TITLE
[Feature] Edit original title

### ISSUE THREAD

**Issue by DesktopMan** [Radarr/Radarr#3033]
I use original title for file and folder renaming. Sometimes there are some minor errors in these, but to correct these I have to remove the movie from Radarr, rename file/folder, then re-import it.

It would be very nice if there was an option on the movie page to edit original title so you can fix these. The next scan (for folders) and rename (files) would then use the updated original title automatically.

**Comment by galli-leo** [comment]
Already possible using Automatically rename movie folders & Dynamic Paths.

**Comment by DesktopMan** [comment]
I guess I wasn't clear enough. I wish to be able to edit the original title from the import to fix it. How can I do that with the current UI? Yes Radarr can rename folders and files but that's not what the feature request is about.

**Comment by galli-leo** [comment]
Well that's currently not possible, but there are already open issues for this.

**Comment by DesktopMan** [comment]
If I understood that request correctly it's about editing the movie title. This request is about editing the original title, e.g. the release name. Or does the other request also cover that use case?

**Comment by galli-leo** [comment]
The request would also cover your use case, since we use the display name as the name to rename files.

**Comment by DesktopMan** [comment]
Is that also the case for {original.title}? I can't see the release name presented as the name in any UI. The UI still uses the title from TMDB.

**Comment by galli-leo** [comment]
Ah no that's using the name as it originally appeared in your download client.
