### ISSUE TITLE
Would you accept a pull request to make the header more consistent with Sonarr?

### ISSUE THREAD

**Issue by rfgamaral** [Radarr/Radarr#3034]
Hi,

Would you accept a pull request to to change Radarr header to be more consistent with Sonarr's like this:

![image](https://user-images.githubusercontent.com/96476/45599572-d2cb7a80-b9e5-11e8-929a-f72dede47d67.png)

❓

**Changes:**
- Removed `Add Movies` from the header toolbar (feels kinda redundant to me) and adapted spacing between them.
- Swapped `film` icon with `play` icon (consistent with Sonarr).
- Reduced `min-width` on the page container (consistent with Sonarr and personally I thought it was too big).

**Comment by galli-leo** [comment]
I don't think so, multiple people requested the Add Movies header. I kinda like the other icon.

Reducing min-width is probably not the best idea, since there is already far too much content to show on the table view.

**Comment by rfgamaral** [comment]
Maybe Radarr should dial down the "too much content"? Don't take this the wrong way but IMO there's actually too much going on with Radarr. You should aim to keep things much more simple, like Sonarr, but that's just my opinion.

**Comment by galli-leo** [comment]
@rfgamaral Definitely, but I don't plan on changing the content much with the current UI. (Honestly I would like to change as little as possible, since we are gonna rewrite it anyways).

The new UI will definitely feature less content as well as the ability to customize the displayed content.

**Comment by rfgamaral** [comment]
@galli-leo Are you going to rewrite Radarr based on Sonarr v3 or something entirely different?

**Comment by galli-leo** [comment]
@rfgamaral We will certainly try to keep a similar visual style, but currently we want to use a different UI framework (Vue).

**Comment by rfgamaral** [comment]
My question was more like if you guys are going to write it from scratch or not. You can use Vue or whatever and still have an exact same look and feeling as Sonarr. Not saying that you should aim for that if it's not what you want :)

Just don't pull a CouchPotato please, if you know what I mean 😎

**Comment by galli-leo** [comment]
@rfgamaral Ah we will be using a ui toolkit to help with some basic stuff, but everything else is probably from scratch.

> Just don't pull a CouchPotato please, if you know what I mean 😎

Haha yeah, before we start working on anything UI related, we will definitely ask the community for feedback.
