### ISSUE TITLE
[Feature Request] Filter movies by lists in the Movie Editor

### ISSUE THREAD

**Issue by azumukupoe** [Radarr/Radarr#3039]
**Is your feature request related to a problem? Please describe.**
Let's say you have a movie on two lists; B List has Add Movies Monitored turned on but the other, A list doesn't.
I suppose Radarr automatically adds movies from lists in alphabetical order, so it respects A list's preference of not monitoring movies.

**Describe the solution you'd like**
If you can filter movies by list you can select all movies after filtering to bulk change their Monitered status.

**Describe alternatives you've considered**
Add a setting to priotize lists manually. But isn't this more complicated?

**Comment by fryfrog** [comment]
I don't really understand your overall goal or reason for this feature request, can you go into more detail about the higher level problem you're trying to solve?

**Comment by fryfrog** [comment]
Could you not solve this by using alphabetical ordering to force the right order?

**Comment by azumukupoe** [comment]
Do you mean I should rename the lists?

**Comment by fryfrog** [comment]
I mean, if it is alphabetical like you claim... just name them 0 - Name and 1 - Name. I *actually* suspect they're ordered based on when they were added, but even if that is true you could just re-order them by deleting one.

**Comment by azumukupoe** [comment]
I feel they are automatically reordered in alphabetical order and processed in the order.

**Comment by fryfrog** [comment]
That wouldn't surprise me and it'd be easy to prove by just naming the list differently... is that not possible? I don't use lists.

**Comment by azumukupoe** [comment]
I'm probably going to...

**Comment by Qstick** [comment]
This is possible in Aphrodite. Attach unique tags to the lists so that movies added from that list get a tag in Radarr. You can then filter by tag in index and editor.
