### ISSUE TITLE
Failed download repeats over and over again

### ISSUE THREAD

**Issue by Anijake** [Radarr/Radarr#304]
![screen shot 2017-01-17 at 9 26 30 am](https://cloud.githubusercontent.com/assets/25043155/22024905/93ecc2f4-dc99-11e6-8893-7d2f73ddf545.png)

Download fails, does not get blacklisted and just keeps trying the same release over and over again. Even if I manually delete and mark as blacklisted, same results. 

And just a note my blacklist is empty even after adding a few releases to it manually.

**Comment by deiniolj** [comment]
#186
