### ISSUE TITLE
option to set path in profile

### ISSUE THREAD

**Issue by icf20** [Radarr/Radarr#3040]
**Is your feature request related to a problem? Please describe.**
the current step is ok if all the file in one mail folder but is a pain if the folder are sorted by quality and/or language 

**Describe the solution you'd like**
a option in /settings/profiles to "force path"
example 
if  i got a profile called any english then the path path /bla bla/any/eng

if i change the profile to any spanish then the path /bla bla/any/esp

if i change the profile to any spanish blueray 1080 then the path /bla bla/blu_ray_1080/esp

**Describe alternatives you've considered**
doing this by hand changing the path each time the profile is changed

**Comment by fryfrog** [comment]
This is a long standing request, see issue #153 and probably one on feathub too.
