### ISSUE TITLE
[Feature Request] Exclude films from auto import by genre

### ISSUE THREAD

**Issue by niftyapple** [Radarr/Radarr#3042]
**Is your feature request related to a problem? Please describe.**
The auto import is pulling any movie that appears on my frequented RSS lists. While I quite enjoy most of what is imported, there are some genres of film that I don't particularly fancy. 

**Describe the solution you'd like**
Add a system level or created list level ignore auto import by genre option, Ex: Deny all Horror

**Describe alternatives you've considered**
Genre based searches or data doesn't seem to be implemented as of yet, at least as it relates to my searches for this particular feature req. 

**Additional context**
This could also be applied as a filter to Discover New Movies function.

**Comment by fryfrog** [comment]
If you want something like this now, use a list the more accurately represents what you want.

**Comment by Rouzax** [comment]
Similar to existing request:
https://github.com/Radarr/Radarr/issues/2955

**Comment by Qstick** [comment]
Closing in lieu of #2955
