### ISSUE TITLE
Why do I have files in the "disk space" list of free/total space?

### ISSUE THREAD

**Issue by rfgamaral** [Radarr/Radarr#3045]
I'm not sure if this is a bug per-se...

![image](https://user-images.githubusercontent.com/96476/45894777-4a731e00-bdc7-11e8-9f1f-e8b04ba45388.png)

I'm wondering why do I have `/etc/resolv.conf`, `/etc/hostname` and `/etc/hosts` on the disk space, they're files, not folders...

In comparison, this is from Sonarr:

![image](https://user-images.githubusercontent.com/96476/45894835-78586280-bdc7-11e8-9249-fef391e1ea67.png)

Both instances are running inside Docker containers, if that's relevant.

Thoughts?

**Comment by fryfrog** [comment]
It is showing you mounts, inside the Docker everything you pass in is a bind mount. You're passing in those 3 files to Radarr and not to sonarr. If you don't want them to show up on a list of mounts, don't pass them in. Since the Sonarr one is working w/o them, the Radarr one probably will too.

**Comment by rfgamaral** [comment]
> You're passing in those 3 files to Radarr and not to sonarr. If you don't want them to show up on a list of mounts, don't pass them in.

Thing is, I'm passing the exact same thing for both containers...

**Comment by rfgamaral** [comment]
Indeed... I'm going to open a PR with this.
