### ISSUE TITLE
Moving Symbolic Link to Movie File Creates a Hardlink Instead

### ISSUE THREAD

**Issue by ElBob** [Radarr/Radarr#3046]
**Describe the bug**
When executing a DownloadedMoviesScan API call with importMode=Move, and a downloadClientId={uppercase infohash}, if the path passed contains a symbolic link, instead of moving the symbolic link, radarr creates a hardlink to the original file.

**To Reproduce**
1. Create a symbolic link to the downloaded movie file
2. Call the DownloadedMoviesScan with importMode=Move, downloadClientId={uppercase infohash}, path={path to folder containing symbolic link}
3. Compare the inode of the file created by radarr and the inode of the original file.

**Expected behavior**
Radarr should move the symbolic link, rather than creating a new hardlink

**Comment by fryfrog** [comment]
Why would you use symlinks if hard links work? They're far superior and have none of the drawbacks a symlink has.

But given the api usage, I'd expect a move to be a move no matter what and agree w/ your expected behavior.

**Comment by galli-leo** [comment]
Please provide debug logs as well as what download client you are using.

If you are using torrents, that's the intended way it should work.
