### ISSUE TITLE
[Feature Request] Minimize poster space usage 

### ISSUE THREAD

**Issue by Silent-Remux** [Radarr/Radarr#3048]
On a 34K database, posters take up almost 14GB of space. If this were avoidable, it would save me lots of space for the 4 Radarr instances I run.

Maybe a shared cache folder would be a reasonable compromise between losing posters and saving space?

**Comment by fryfrog** [comment]
A file system that supports deduplication would also help.

**Comment by Qstick** [comment]
Problem with a shared directory between instances is that image cache is saved in folders by db Id which is different for each instance. Solution here is getting multiple version support so don’t need multiple instances. To the original issue, we are caching images in 3 sizes I believe, maybe there is some opportunity to compress the reduced size images we keep, but it would likely slow down the process.... storage is cheap :)

**Comment by Qstick** [comment]
Closing this with no plans of change for now
