### ISSUE TITLE
Torrent9 Indexer

### ISSUE THREAD

**Issue by BluPixal** [Radarr/Radarr#305]
Would it be possible to add Torrent9 as an indexer.

It's a torrent site with a lot of French content and I think it could be great to have a French indexer for French person.

http://www.torrent9.biz/

**Comment by onedr0p** [comment]
Just posting some information to help someone if they want to add this to Radrr
We will need to parse the HTML at: 
http://www.torrent9.biz/torrents_films.html

I found a PR over at SickRage that did it for series:
https://github.com/magicseb/SickRage/pull/2/files

**Comment by galli-leo** [comment]
While I too would like a french Indexer, without an API we are not going to implement one. Even if somebody did create a working scraper, we decided that supporting it would be incredibly laborious. Therefore, we will not implement indexers without an API

**Comment by Ta0uf19** [comment]
If you are still interested I have recently made a scraper for Torrent9.
