### ISSUE TITLE
Missing path whenever I try to add movies

### ISSUE THREAD

**Issue by aporzio1** [Radarr/Radarr#3055]
**Describe the bug**
Whenever I go to add a movie the path field is blank and takes about 5 minutes to populate. If i refresh the page they are all missing again.

**To Reproduce**
1. Click Add Movie
2. Search for movie
3. Wait and eventually the paths will populate

**Expected behavior**
paths should already be populated after searching for movie to ass

**Screenshots**
![image](https://user-images.githubusercontent.com/7033289/46042716-1f007400-c0e4-11e8-8e94-89fc78f04449.png)

**Desktop (please complete the following information):**
 - OS: MacOS 10.13.6
 - Mono Version: 4.6.2
 - Browser and Version: All
 - Version:0.2.0.1120

**Debug Logs**
[radarr.debug (1).txt](https://github.com/Radarr/Radarr/files/2417064/radarr.debug.1.txt)

**Comment by fryfrog** [comment]
Did you try it in an incognito window?

**Comment by aporzio1** [comment]
Yes and the same thing happens, It also happens in all browsers on different computers as well as NZB360 on android.

**Comment by fryfrog** [comment]
Oh, can you just go ahead and run it with a modern version of Mono? Yours is super old. You need something 5.8 or higher, suggest 5.14 which is current. I'm surprised Radarr starts up, honestly. :)

**Comment by aporzio1** [comment]
updated to 5.14.0.177 and same issue @fryfrog

**Comment by fryfrog** [comment]
Dang!

Turn logging up to trace and reproduce, attach that portion of the log? :/

**Comment by aporzio1** [comment]
[radarr.trace.txt](https://github.com/Radarr/Radarr/files/2430168/radarr.trace.txt)

Here it is

**Comment by fryfrog** [comment]
And here it is in a [pastebin](https://ptpb.pw/eFKQ) for ease of consumption! :)

**Comment by fryfrog** [comment]
Do you have a *TON* of history in your download client? It looks like you have a handful of movies that are unprocessed, but maybe also a ton of movies in your history? That log is basically all just queue processing, I think. At least, I can't visually discern anything useful from it due to the sheer volume of unrelated lines.

**Comment by fryfrog** [comment]
I also see TV stuff, are you not using categories?

**Comment by aporzio1** [comment]
by download client history do you mean completed downloads? There are 402 items in there.

Also I am using categories. All of the Radarr stuff comes in tagged as movies and goes into the movies folder.

**Comment by fryfrog** [comment]
That doesn't sound too bad, but can you delete the ones you don't need in history anymore? It also really looks like it is parsing TV stuff, but maybe it gets everything and then narrows down? Is your total history 402 items or just movies?

**Comment by aporzio1** [comment]
That was the entire history. I just cleared it

**Comment by fryfrog** [comment]
Okay, this time the logs should be much simpler! Also, I don't think you're going to see anything.

Might be time to pull out the developer console in your browser? :/

**Comment by aporzio1** [comment]
https://pastebin.com/raw/mfnevPeC

new logs

**Comment by fryfrog** [comment]
That is 100x easier to read, but I don't see anything about the paths in there. I'm not actually even sure if we should. :(

**Comment by galli-leo** [comment]
What happens if you try to add the path again?

**Comment by aporzio1** [comment]
@galli-leo Same thing happens

**Comment by qazero** [comment]
I'm having the same issue :(
