### ISSUE TITLE
Feature Request: Kodi addon 

### ISSUE THREAD

**Issue by aenima99x** [Radarr/Radarr#306]
Request to create a Kodi addon that allows for integration with Radarr similar to what the "CouchPotato Manager" addon (http://forum.kodi.tv/showthread.php?tid=159274&highlight=couchpotato) currently does. Viewing of movie library and adding wanted movies from Apple Movie Trailers addon being the main features requested.

**Comment by onedr0p** [comment]
This will be a project in itself separate from Radarr. We definitely need someone who can help make it.

**Comment by Abzie** [comment]
We need some documentation on api endpoints, and the api authentication is not working as of v0.2.0.152 when trying to access /api/system/status. Results in:
`{
  "error": "Unauthorized"
}`

**Comment by galli-leo** [comment]
@Abzie As for docs you can just open the Chrome Dev Console and go to the network tab 😄. Should be pretty easy to get a grasp of important methods. Regarding authentication, did you correctly set the API key Header?

**Comment by schumi2004** [comment]
This shouldn't be to hard to accomplish. If we do a 1:1 from CP manager then we just need to modify CP manager code slightly to accomplish this.

I'll have a play with it but can't promise anything ;)

**Comment by onedr0p** [comment]
I am closing this issue as it's outside of the scope of this project. For any developer feel free to work on it and link to a github project!
