### ISSUE TITLE
[Feature Request] Include actors etc in movie library

### ISSUE THREAD

**Issue by shareonline** [Radarr/Radarr#3060]
It would be nice if Radarr also scrabed actors and other stuff from TMDB/IMDB when adding/refreshing a movie. It would enhance the view of a movie in Radarr with more details.
This way (for us app developers), we could also get this via the Radarr api, and not be forced to include different api requests in ou apps.

**Comment by fryfrog** [comment]
I can't imagine this is a unique feature request, see if you can dig up a previous one and give it a +1 or vote or something.

**Comment by galli-leo** [comment]
Already asked multiple times, please use the search function :). Is something planned for new UI and API V3
