### ISSUE TITLE
radar dont redirect correctly if there are two languages 

### ISSUE THREAD

**Issue by icf20** [Radarr/Radarr#3062]
**Describe the bug**

![image](https://user-images.githubusercontent.com/17784575/46204674-64a88100-c31e-11e8-9b81-1845396927a5.png)

**To Reproduce**
have two profile based on language

search and add a movie for example and add it using ANY es-ES profile
then search and the same movie using the english title and you will have the 
![image](https://user-images.githubusercontent.com/17784575/46204771-a76a5900-c31e-11e8-9cb1-4c8828bdd322.png)

but if you click on it you get the 404 page 

the ![image](https://user-images.githubusercontent.com/17784575/46204771-a76a5900-c31e-11e8-9cb1-4c8828bdd322.png) give you the URL for the title in english instead of the title in other leanguage

**Comment by fryfrog** [comment]
Can you try to reproduce this in an incognito window, just to eliminate cache issues? And can you copy/paste the URLs given by the Already Exists button/link?

I think they're going to need more details to look into and fix this.

**Comment by icf20** [comment]
yes is the same on incognito
test using the following metadata https://www.imdb.com/title/tt0031679/

> Caballero sin espada (1939)
> Mr. Smith Goes to Washington (original title)

http://snip:7878/movies/mr-smith-goes-to-washington-3083
http://snip:7878/movies/caballero-sin-espada-3083

**Comment by galli-leo** [comment]
This won‘t be fixed in the current UI of Radarr.
