### ISSUE TITLE
Radarr not searching the "good" movie name with jackett

### ISSUE THREAD

**Issue by Warrneff** [Radarr/Radarr#3064]
**Describe the bug**
I added Solo a Star Wars story to radarr, I use rargb and jackett as indexers, when doing a research for release it does find release on rargb but not on jackett.

look at logs show that radarr does not search "solo a Star Wars story" but "solo star wars story" that make the indexer research fail.

**To Reproduce**

1. Add rargb indexer in default setting
2. Add indexer (like yggtorrent) through jackett, no specific settings ethier
3. Add Solo A Star Wars Story in radarr
4. Do manual Search
5. Only rargb release show up

**Expected behavior**
A list of rargb and YGG releases

**Logs
Radarr logs
<img width="555" alt="capture d ecran 2018-09-30 a 10 49 50" src="https://user-images.githubusercontent.com/43719374/46255573-c98ae500-c49e-11e8-82d3-dfeeedaf9b12.png">

Jacket logs : 
<img width="577" alt="capture d ecran 2018-09-30 a 10 50 41" src="https://user-images.githubusercontent.com/43719374/46255570-c98ae500-c49e-11e8-8d0e-3bf753a78316.png">
<img width="577" alt="capture d ecran 2018-09-30 a 10 50 55" src="https://user-images.githubusercontent.com/43719374/46255571-c98ae500-c49e-11e8-97ff-5d93af47cb6d.png">
<img width="597" alt="capture d ecran 2018-09-30 a 10 51 18" src="https://user-images.githubusercontent.com/43719374/46255572-c98ae500-c49e-11e8-96dd-afa0382cdd5f.png">

We see radarr search for each titles but not the "main" one 

** Environnement **
I'm running Radarr and jackett as docker on Synology and Debian server (everything up to date)
Saw this little bug only for the movie at this moment.

**Debug Logs**
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/2431392/radarr.debug.txt)

**Comment by fryfrog** [comment]
> "solo a Star Wars story" but "solo stars wars story"

^ Is the "stars" there a typo or is that what it really searched for?

**Comment by Warrneff** [comment]
> > "solo a Star Wars story" but "solo stars wars story"
> 
> ^ Is the "stars" there a typo or is that what it really searched for?

yeah typo, thanks 
Screenshots give the real text

**Comment by galli-leo** [comment]
Use indexers that support searching by imdbid.

Alternatively, there are other issues open already about this.
