### ISSUE TITLE
Add Discord As Notification Connection Option

### ISSUE THREAD

**Issue by ThePieMonster** [Radarr/Radarr#3065]
**Describe the solution you'd like**
Add the ability for users to add a Radarr Discord bot to their Discord server in which the bot would provide the notifications to a configured channel.

**Comment by galli-leo** [comment]
Use Slack webhooks instead.

**Comment by ThePieMonster** [comment]
I am trying to save a new slack connection in which I provided the name, webhook url, and username but I can't get it to save the connection. When I reload the page there are no connections. Tried restarting also. 

Looked in the logs and it seems when you go to save or test a connection there is no text value being populated with a test message so it fails. 

`HTTP Error - Res: [POST] https://discordapp.com/api/webhooks/#############/###########################: 400.BadRequest
{"code": 50006, "message": "Cannot send an empty message"}`

**Comment by mryogihbear** [comment]
This worked for me =)

https://blog.tiga.tech/discord-notifications-for-sonarr-radarr-and-lidarr/
