### ISSUE TITLE
Movies show as missing, System.NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by LesKent** [Radarr/Radarr#3066]
This has been an ongoing issue for a while for me but I decided I would dig in deeper. I've got many dozens of movies that show as "Missing" yet a good media file exists in the proper directory. 

Previously many times I had seen random movies fail to import with the same "System.NullReferenceException: Object reference not set to an instance of an object" error. If I deleted the old existing file first then the import process will succeed.

I was noticing that just tonight that when the Refresh Movies task was running I'm seeing many "Error|ImportDecisionMaker|Couldn't evaluate decision on ..." errors that highlighted all the movies that are in this improper state of incorrectly showing "Missing" with the media file present. 

Here is an example relevant log messages from the regular, debug, and trace logs for one movie that has this issue: 

Radarr.txt
18-10-1 03:05:29.8|Info|RefreshMovieService|Skipping refresh of movie: A Very Long Engagement
18-10-1 03:05:29.9|Info|DiskScanService|Scanning disk for A Very Long Engagement
18-10-1 03:05:30.1|Error|ImportDecisionMaker|Couldn't evaluate decision on D:\Movies\A Very Long Engagement (2004)\A Very Long Engagement (2004) - [BLURAY-1080P][DTS 5.1][X264].mkv

[v0.2.0.1120] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.MediaFiles.MovieImport.Specifications.SameFileSpecification.IsSatisfiedBy(LocalMovie localMovie, DownloadClientItem downloadClientItem) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\MovieImport\Specifications\SameFileSpecification.cs:line 30
   at NzbDrone.Core.MediaFiles.MovieImport.ImportDecisionMaker.EvaluateSpec(IImportDecisionEngineSpecification spec, LocalMovie localMovie, DownloadClientItem downloadClientItem) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\MovieImport\ImportDecisionMaker.cs:line 306

18-10-1 03:05:30.2|Info|DiskScanService|Completed scanning disk for A Very Long Engagement
18-10-1 03:05:30.2|Info|ExistingMetadataImporter|Found 0 existing metadata files
18-10-1 03:05:30.2|Info|ExistingSubtitleImporter|Found 0 existing subtitle files
18-10-1 03:05:30.2|Info|ExistingOtherExtraImporter|Found 0 existing other extra files
18-10-1 03:05:30.3|Info|ExistingExtraFileService|Found 0 extra files

radarr.debug.txt:
18-10-1 03:05:29.8|Info|RefreshMovieService|Skipping refresh of movie: A Very Long Engagement
18-10-1 03:05:29.9|Info|DiskScanService|Scanning disk for A Very Long Engagement
18-10-1 03:05:29.9|Debug|DiskScanService|Scanning 'D:\Movies\A Very Long Engagement (2004)' for video files
18-10-1 03:05:29.9|Debug|DiskScanService|1 video files were found in D:\Movies\A Very Long Engagement (2004)
18-10-1 03:05:29.9|Debug|DiskScanService|[tt0344510][A Very Long Engagement (2004)] Cleaning up media files in DB
18-10-1 03:05:29.9|Debug|ImportDecisionMaker|Analyzing 1/1 files.
18-10-1 03:05:29.9|Debug|Parser|Parsing string 'A Very Long Engagement (2004) - [BLURAY-1080P][DTS 5.1][X264].mkv'
18-10-1 03:05:29.9|Debug|Parser|Movie Parsed. A Very Long Engagement - 2004 
18-10-1 03:05:29.9|Debug|Parser|Language parsed: English
18-10-1 03:05:29.9|Debug|QualityParser|Trying to parse quality for A Very Long Engagement (2004) - [BLURAY-1080P][DTS 5.1][X264].mkv
18-10-1 03:05:29.9|Debug|Parser|Quality parsed: Bluray-1080p v1
18-10-1 03:05:29.9|Debug|Parser|Release Group parsed: 
18-10-1 03:05:29.9|Debug|ImportDecisionMaker|Size: 11742229544
18-10-1 03:05:29.9|Debug|VideoFileInfoReader|Getting media info from D:\Movies\A Very Long Engagement (2004)\A Very Long Engagement (2004) - [BLURAY-1080P][DTS 5.1][X264].mkv
18-10-1 03:05:30.1|Debug|ImportDecisionMaker|Checking quality for this video file to make sure nothing mismatched.
18-10-1 03:05:30.1|Debug|GrabbedReleaseQualitySpecification|No download client item provided, skipping.
18-10-1 03:05:30.1|Error|ImportDecisionMaker|Couldn't evaluate decision on D:\Movies\A Very Long Engagement (2004)\A Very Long Engagement (2004) - [BLURAY-1080P][DTS 5.1][X264].mkv

[v0.2.0.1120] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.MediaFiles.MovieImport.Specifications.SameFileSpecification.IsSatisfiedBy(LocalMovie localMovie, DownloadClientItem downloadClientItem) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\MovieImport\Specifications\SameFileSpecification.cs:line 30
   at NzbDrone.Core.MediaFiles.MovieImport.ImportDecisionMaker.EvaluateSpec(IImportDecisionEngineSpecification spec, LocalMovie localMovie, DownloadClientItem downloadClientItem) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\MovieImport\ImportDecisionMaker.cs:line 306

18-10-1 03:05:30.1|Debug|FreeSpaceSpecification|Skipping free space check for existing movie
18-10-1 03:05:30.1|Debug|VideoFileInfoReader|Getting media info from D:\Movies\A Very Long Engagement (2004)\A Very Long Engagement (2004) - [BLURAY-1080P][DTS 5.1][X264].mkv
18-10-1 03:05:30.1|Debug|DetectSample|Runtime is over 90 seconds
18-10-1 03:05:30.1|Debug|NotUnpackingSpecification|D:\Movies\A Very Long Engagement (2004)\A Very Long Engagement (2004) - [BLURAY-1080P][DTS 5.1][X264].mkv is in movie folder, skipping unpacking check
18-10-1 03:05:30.2|Debug|ImportApprovedMovie|Decisions: 1
18-10-1 03:05:30.2|Info|DiskScanService|Completed scanning disk for A Very Long Engagement
18-10-1 03:05:30.2|Debug|ExistingExtraFileService|Looking for existing extra files in D:\Movies\A Very Long Engagement (2004)
18-10-1 03:05:30.2|Debug|DiskScanService|Scanning 'D:\Movies\A Very Long Engagement (2004)' for non-video files
18-10-1 03:05:30.2|Debug|DiskScanService|0 non-video files were found in D:\Movies\A Very Long Engagement (2004)
18-10-1 03:05:30.2|Debug|ExistingMetadataImporter|Looking for existing metadata in D:\Movies\A Very Long Engagement (2004)
18-10-1 03:05:30.2|Info|ExistingMetadataImporter|Found 0 existing metadata files
18-10-1 03:05:30.2|Debug|ExistingSubtitleImporter|Looking for existing subtitle files in D:\Movies\A Very Long Engagement (2004)
18-10-1 03:05:30.2|Info|ExistingSubtitleImporter|Found 0 existing subtitle files
18-10-1 03:05:30.2|Debug|ExistingOtherExtraImporter|Looking for existing extra files in D:\Movies\A Very Long Engagement (2004)
18-10-1 03:05:30.2|Info|ExistingOtherExtraImporter|Found 0 existing other extra files
18-10-1 03:05:30.3|Info|ExistingExtraFileService|Found 0 extra files

radarr.trace.txt:
18-10-1 03:05:29.8|Trace|ShouldRefreshMovie|Movie A Very Long Engagement came out long ago, should not be refreshed.
18-10-1 03:05:29.8|Info|RefreshMovieService|Skipping refresh of movie: A Very Long Engagement
18-10-1 03:05:29.8|Trace|CommandQueueManager|Publishing RenameMovieFolder
18-10-1 03:05:29.8|Trace|CommandQueueManager|Checking if command is queued or started: RenameMovieFolder
18-10-1 03:05:29.9|Trace|CommandQueueManager|Inserting new command: RenameMovieFolder
18-10-1 03:05:29.9|Info|DiskScanService|Scanning disk for A Very Long Engagement
18-10-1 03:05:29.9|Trace|EventAggregator|Publishing CommandUpdatedEvent
18-10-1 03:05:29.9|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
18-10-1 03:05:29.9|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
18-10-1 03:05:29.9|Debug|DiskScanService|Scanning 'D:\Movies\A Very Long Engagement (2004)' for video files
18-10-1 03:05:29.9|Debug|DiskScanService|1 video files were found in D:\Movies\A Very Long Engagement (2004)
18-10-1 03:05:29.9|Trace|DiskScanService|Finished getting movie files for: [tt0344510][A Very Long Engagement (2004)] [00:00:00.0012470]
18-10-1 03:05:29.9|Debug|DiskScanService|[tt0344510][A Very Long Engagement (2004)] Cleaning up media files in DB
18-10-1 03:05:29.9|Debug|ImportDecisionMaker|Analyzing 1/1 files.
18-10-1 03:05:29.9|Trace|ConfigService|Using default config value for 'parsingleniency' defaultValue:'Strict'
18-10-1 03:05:29.9|Debug|Parser|Parsing string 'A Very Long Engagement (2004) - [BLURAY-1080P][DTS 5.1][X264].mkv'
18-10-1 03:05:29.9|Trace|Parser|^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(19|20)\d{2}(?!p|i|(19|20)\d{2}|\]|\W(19|20)\d{2})))+(\W+|_|$)(?!\\)
18-10-1 03:05:29.9|Debug|Parser|Movie Parsed. A Very Long Engagement - 2004 
18-10-1 03:05:29.9|Debug|Parser|Language parsed: English
18-10-1 03:05:29.9|Debug|QualityParser|Trying to parse quality for A Very Long Engagement (2004) - [BLURAY-1080P][DTS 5.1][X264].mkv
18-10-1 03:05:29.9|Debug|Parser|Quality parsed: Bluray-1080p v1
18-10-1 03:05:29.9|Debug|Parser|Release Group parsed: 
18-10-1 03:05:29.9|Debug|ImportDecisionMaker|Size: 11742229544
18-10-1 03:05:29.9|Debug|VideoFileInfoReader|Getting media info from D:\Movies\A Very Long Engagement (2004)\A Very Long Engagement (2004) - [BLURAY-1080P][DTS 5.1][X264].mkv
18-10-1 03:05:30.0|Trace|MediaInfo|Read file offset 0-98304 (98304 bytes)
18-10-1 03:05:30.0|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId)

18-10-1 03:05:30.1|Trace|MediaInfo|Read file offset 11742068540-11742229544 (161004 bytes)
18-10-1 03:05:30.1|Trace|MediaInfo|Read a total of 259308 bytes (0.0%)
18-10-1 03:05:30.1|Debug|ImportDecisionMaker|Checking quality for this video file to make sure nothing mismatched.
18-10-1 03:05:30.1|Debug|GrabbedReleaseQualitySpecification|No download client item provided, skipping.
18-10-1 03:05:30.1|Error|ImportDecisionMaker|Couldn't evaluate decision on D:\Movies\A Very Long Engagement (2004)\A Very Long Engagement (2004) - [BLURAY-1080P][DTS 5.1][X264].mkv

[v0.2.0.1120] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.MediaFiles.MovieImport.Specifications.SameFileSpecification.IsSatisfiedBy(LocalMovie localMovie, DownloadClientItem downloadClientItem) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\MovieImport\Specifications\SameFileSpecification.cs:line 30
   at NzbDrone.Core.MediaFiles.MovieImport.ImportDecisionMaker.EvaluateSpec(IImportDecisionEngineSpecification spec, LocalMovie localMovie, DownloadClientItem downloadClientItem) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\MovieImport\ImportDecisionMaker.cs:line 306

18-10-1 03:05:30.1|Trace|ConfigService|Using default config value for 'skipfreespacecheckwhenimporting' defaultValue:'False'
18-10-1 03:05:30.1|Debug|FreeSpaceSpecification|Skipping free space check for existing movie
18-10-1 03:05:30.1|Debug|VideoFileInfoReader|Getting media info from D:\Movies\A Very Long Engagement (2004)\A Very Long Engagement (2004) - [BLURAY-1080P][DTS 5.1][X264].mkv
18-10-1 03:05:30.1|Trace|MediaInfo|Read file offset 0-98304 (98304 bytes)
18-10-1 03:05:30.1|Trace|MediaInfo|Read file offset 11742068540-11742229544 (161004 bytes)
18-10-1 03:05:30.1|Trace|MediaInfo|Read a total of 259308 bytes (0.0%)
18-10-1 03:05:30.1|Debug|DetectSample|Runtime is over 90 seconds
18-10-1 03:05:30.1|Debug|NotUnpackingSpecification|D:\Movies\A Very Long Engagement (2004)\A Very Long Engagement (2004) - [BLURAY-1080P][DTS 5.1][X264].mkv is in movie folder, skipping unpacking check
18-10-1 03:05:30.2|Trace|DiskScanService|Import decisions complete for: [tt0344510][A Very Long Engagement (2004)] [00:00:00.2198550]
18-10-1 03:05:30.2|Debug|ImportApprovedMovie|Decisions: 1
18-10-1 03:05:30.2|Info|DiskScanService|Completed scanning disk for A Very Long Engagement
18-10-1 03:05:30.2|Trace|EventAggregator|Publishing MovieScannedEvent
18-10-1 03:05:30.2|Trace|EventAggregator|MovieScannedEvent -> MovieScannedHandler
18-10-1 03:05:30.2|Trace|EventAggregator|MovieScannedEvent <- MovieScannedHandler
18-10-1 03:05:30.2|Trace|EventAggregator|MovieScannedEvent -> UpdateMovieFileService
18-10-1 03:05:30.2|Trace|ConfigService|Using default config value for 'filedate' defaultValue:'None'
18-10-1 03:05:30.2|Trace|EventAggregator|MovieScannedEvent <- UpdateMovieFileService
18-10-1 03:05:30.2|Trace|EventAggregator|MovieScannedEvent -> UpdateMediaInfoService
18-10-1 03:05:30.2|Trace|ConfigService|Using default config value for 'enablemediainfo' defaultValue:'True'
18-10-1 03:05:30.2|Trace|EventAggregator|MovieScannedEvent <- UpdateMediaInfoService
18-10-1 03:05:30.2|Trace|EventAggregator|MovieScannedEvent -> ExistingExtraFileService
18-10-1 03:05:30.2|Debug|ExistingExtraFileService|Looking for existing extra files in D:\Movies\A Very Long Engagement (2004)
18-10-1 03:05:30.2|Debug|DiskScanService|Scanning 'D:\Movies\A Very Long Engagement (2004)' for non-video files
18-10-1 03:05:30.2|Debug|DiskScanService|0 non-video files were found in D:\Movies\A Very Long Engagement (2004)
18-10-1 03:05:30.2|Debug|ExistingMetadataImporter|Looking for existing metadata in D:\Movies\A Very Long Engagement (2004)
18-10-1 03:05:30.2|Info|ExistingMetadataImporter|Found 0 existing metadata files
18-10-1 03:05:30.2|Debug|ExistingSubtitleImporter|Looking for existing subtitle files in D:\Movies\A Very Long Engagement (2004)
18-10-1 03:05:30.2|Info|ExistingSubtitleImporter|Found 0 existing subtitle files
18-10-1 03:05:30.2|Debug|ExistingOtherExtraImporter|Looking for existing extra files in D:\Movies\A Very Long Engagement (2004)
18-10-1 03:05:30.2|Info|ExistingOtherExtraImporter|Found 0 existing other extra files
18-10-1 03:05:30.3|Info|ExistingExtraFileService|Found 0 extra files

**Comment by galli-leo** [comment]
What version of Radarr are you using?

**Comment by LesKent** [comment]
Version 0.2.0.1120 which is shown in the exception error:

[v0.2.0.1120] System.NullReferenceException: Object reference not set to an instance of an object.
 at NzbDrone.Core.MediaFiles.MovieImport.Specifications.SameFileSpecification.IsSatisfiedBy(LocalMovie localMovie, DownloadClientItem downloadClientItem) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\MovieImport\Specifications\SameFileSpecification.cs:line 30
 at NzbDrone.Core.MediaFiles.MovieImport.ImportDecisionMaker.EvaluateSpec(IImportDecisionEngineSpecification spec, LocalMovie localMovie, DownloadClientItem downloadClientItem) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\MovieImport\ImportDecisionMaker.cs:line 306

**Comment by galli-leo** [comment]
Make sure the movie has a valid path set. Else I don‘t see anything in that file that could cause issues, I fixed a similar error in nightly, so the next develop release could also fix your issue.
