### ISSUE TITLE
Trakt RSS feed won't import in Radarr

### ISSUE THREAD

**Issue by 3-stan** [Radarr/Radarr#3067]
Hi guys
Following a quite nasty NAS crash, i am trying to rebuild a bit of my collection.
I have an up-to date VIP trakt account, so i thought i would create a list with all collected items. However, when i generate the rss link and paste it in the RSS section of the Radarr list creation, the message test rss failed appears. Is it because the link is https ?

an example of the link --> https://trakt.tv/users/xxxxxxxxxxx/collection/movies/added.atom?slurm=406fb9aff97de86dd5092da9130af034

![capture d ecran 2018-10-02 00 48 49](https://user-images.githubusercontent.com/43765802/46320083-f0e7cc00-c5dc-11e8-8a47-eff2e38be3fa.png)

Maybe I did something stupid. If so, please forgive me as i am very new to all this.

Many thank for all the work

**Comment by galli-leo** [comment]
Use the Trakt list directly, RSS feeds of trakt are not supported.

**Comment by 3-stan** [comment]
Thank you very much. At least i did not do anything too dumb.
Per any chance, any idea as how to create a list with all my collection on trakt. It seems there is no easy way ?.
Thank you again for your time

**Comment by kieppie** [comment]
Can this ticket be reassessed, please?

Various Trakt lists import OK, but not the ability to import my pre-existing Collection (as opposed to primary Watchlist), i.e. https://trakt.tv/users/$USERNAME$/collection/movies/added
