### ISSUE TITLE
 How to use configure Radarr and Jackett to download movies in the desired audio language?

### ISSUE THREAD

**Issue by Drigoo** [Radarr/Radarr#3069]
Hello,

I'm using Radarr some time along with Jackett.
The issue is that I live in Brazil, and it is more intentative for me to download the films in audio pt. The private trackers added in Jackett use the dual audio format so we have the audio in pt-br, so I would like to know how I can configure Radarr and Jackett to consider only the dual audio format for download.

Thank you for your help and forgive me for the bad English.

**Comment by fryfrog** [comment]
If there is something in the releases names, you can key off of that with preferred words, required words and even the new custom formats. If there isn't something in the release names, you'll need to make Radarr realize everything on your tracker is pt-BR, I don't have much experience there though. Maybe if you set the language for your Radarr instance? Or maybe each indexer has a language preference?
