### ISSUE TITLE
Make Radarr validate a path on his side and return boolean

### ISSUE THREAD

**Issue by morpheus65535** [Radarr/Radarr#3070]
**Is your feature request related to a problem? Please describe.**
In Bazarr, we do path mapping to be sure Bazarr can access a movie file even if he doesn't access it trough the same path. I would like to be able to do a API call to validate what the user have entered in a text field to be a valid path for Radarr.

**Describe the solution you'd like**
A new API endpoint?

**Describe alternatives you've considered**
Cross my finger and expect the user to make it right ;-)

**Additional context**
Thanks! :-)

**Comment by galli-leo** [comment]
We already do some basic validation. I don’t think additional validation would help in any way. Feel free to open a pr though.
