### ISSUE TITLE
Release dates are incorrect

### ISSUE THREAD

**Issue by diedrichg** [Radarr/Radarr#3071]
**Describe the bug**
When looking at the calendar of releases, nearly all movies being shown as released to DVD have the wrong date. Example - Ant-Man and the Wasp show as October 1 on my Radarr Calendar, however both Metacritic https://www.metacritic.com/browse/dvds/release-date/coming-soon/date and DVD Release Dates https://www.dvdsreleasedates.com/ agree that the actual release date is October 16. This inaccuracy is true for nearly all movies on my Radarr Calendar.

**Expected behavior**
What service is providing the release dates? Is there a way we can change the provider? Could you find a provider with more accurate release dates?

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 0.2.0.1120

**Debug Logs**
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/2444509/radarr.debug.txt)

**Comment by galli-leo** [comment]
Physical release can either mean dvd, bluray or web release. So the dates are correct.
