### ISSUE TITLE
New color for calendar DVD release date

### ISSUE THREAD

**Issue by diedrichg** [Radarr/Radarr#3072]
**Is your feature request related to a problem? Please describe.**
It's difficult, and sometimes confusing, to see the same color for "In Cinemas" and Released to DVD (light blue) on the calendar view.

**Describe the solution you'd like**
It would be much more helpful and distinctive to have separate colors for "In Cinemas" and "Released to DVD" in the calendar view. As seen in the mock-up, I have colored the upcoming DVD releases in orange.
![capture](https://user-images.githubusercontent.com/9559987/46450118-a93c7e00-c75d-11e8-9ab7-e4b75fba75c5.PNG)

**Comment by galli-leo** [comment]
Discussed already in other issues, will be done with the new ui
