### ISSUE TITLE
Bulk import ignores qualities and/or profiles

### ISSUE THREAD

**Issue by monkiibiz** [Radarr/Radarr#3075]
**Describe the bug**
When doing a bulk import of files without a quality in the naming, Radarr ignores the size limits defined in Quality.

**To Reproduce**
1. Change size settings in quality
2. Bulk import movie files without quality in file name
3. All MKV containers will either default to HDTV 720p or HDTV 1080p, regardless of size not matching quality setting. AVI containers will default to SDTV, despite that quality not being present in the selected profile

**Expected behavior**
If quality can't be determined based on file name, video resolution should be read from codec, and file size should be a tie-breaker to determine type based on quality. In either case, file size limits defined in quality should be respected.

**Screenshots**
![quality](https://user-images.githubusercontent.com/4595037/46472619-1263d600-c7de-11e8-8efa-f4819a1f4595.PNG)
![bulk import](https://user-images.githubusercontent.com/4595037/46472620-1263d600-c7de-11e8-9ef4-5672318b8f93.PNG)
![profile](https://user-images.githubusercontent.com/4595037/46472622-12fc6c80-c7de-11e8-80ac-70e52caa87b1.PNG)

**Desktop (please complete the following information):**
 - OS: Synology DSM 6.2
 - Mono Version: 5.8.0.108 (tarball Sat Feb 24 09:55:00 UTC 2018)
 - Version: 0.2.0.1120

**Debug Logs**
[radarr.log](https://github.com/Radarr/Radarr/files/2446285/radarr.log)

**Comment by galli-leo** [comment]
This is fixed in nightly
