### ISSUE TITLE
Failed download handling & nzbget: a job marked as 'bad' isn't recognized as 'failed'

### ISSUE THREAD

**Issue by l-t-k** [Radarr/Radarr#3076]
**Describe the bug**
Radarr should treat nzbget jobs that are marked as 'bad' in the same as it should handle jobs marked as 'failure'. Right now, radarr isn't sending a new nzb to the dl client.

Jobs are marked as 'bad' if this script is recognizing a bad file format:
https://github.com/nzbget/FakeDetector/blob/master/FakeDetector.py

**Screenshots**
![1](https://user-images.githubusercontent.com/3150962/46494989-84571200-c814-11e8-9b4f-687ff8fff655.jpg)

![2](https://user-images.githubusercontent.com/3150962/46495074-c1bb9f80-c814-11e8-91a8-80a88419708a.jpg)

![3](https://user-images.githubusercontent.com/3150962/46495146-e9126c80-c814-11e8-8535-2132aa549931.jpg)

**Debug Logs**
Turn on debug logs under Settings -> General and wait for the bug to occur again. **Upload the full log file here (or another site and link it). Issues will be closed, if they do not include this!**

**Comment by galli-leo** [comment]
Can you provide the json response of Nzbget‘s api for this item?

**Comment by l-t-k** [comment]
https://pastebin.com/WZ7AtaGC

**Comment by galli-leo** [comment]
@markus101 This should be relatively easy right? Just adding BAD to the delete failed statuses should be enough?

**Comment by markus101** [comment]
Yeah, that'll do it.
