### ISSUE TITLE
Imported files do not appear to get scanned by mediainfo

### ISSUE THREAD

**Issue by jemus42** [Radarr/Radarr#3077]
All my files I imported after a certain date in September do not have video codec information associated with them. I verified this by exporting all movie files via the API and sorting by `file_dateAdded`.

Somehwere around that time I made some changes to my system, so it's either related to a freeBSD upgrade and newer mediainfo version, or it's a bug in the current dev version of Radarr (I've been using the continuous downloads for a while now).

TL;DR
The files imported since about a month ago don't have proper mediainfo, so e.g. renaming doesn't properly work as I use `videoCodec` in my naming scheme. `audioCodec` works though.

**To Reproduce**
Not sure.  
Install the latest version [from appveyor](https://ci.appveyor.com/project/galli-leo/radarr-usby1/branch/develop/artifacts) and import some files?

**Expected behavior**
Properly scanned media info and it's availability in the API data and through renaming

**Screenshots**

**Server:**
 - FreeBSD 11.2-STABLE
- Radarr Version: 0.2.0.1198
- Mono Version: 5.10.1.57 (5.10.1.57 Tue Sep 4 02:48:30 UTC 2018)
- `mediainfo --version`: MediaInfoLib - v18.08.1

**Debug Logs**
- [debug log](https://paste.xinu.at/fzfq/) I deleted and reimported a movie for testing just now.

**Comment by Bastien42** [comment]
i maybe have a similar issue when all my movies when they are added are show so that their downloaded quality is Unknown odd behaviour.

**Comment by Bastien42** [comment]
though personally the video info are scrapped

**Comment by jemus42** [comment]
> i maybe have a similar issue when all my movies when they are added are show so that their downloaded quality is Unknown odd behaviour.

Probably unrelated, as "quality", i.e. "bluray 1080p" etc is parsed from the file name, so you that doesn't work for you make sure your filenames contain the source (web-dl, bluray, dvd…) and resolution (720p, ...), then it should recognize it just fine.

My issue refers to the mediainfo, or video codec recognition specifically. That requires `mediainfo` to analyze the files and gives e.g. `x.265 AAC` for renaming.

**Comment by galli-leo** [comment]
According to the debug log and the fact that audio codec is working, seems like something else is wrong here. Is the video info showing up under media info in the files tab on the details page? What’s the output of mediainfo cli for those files? Anyhow, I suggest you hop on discord for support.
