### ISSUE TITLE
[Feature Request] Maintain a database listing languages per film.

### ISSUE THREAD

**Issue by keith555** [Radarr/Radarr#3082]
Searching for movies with a particular language soundtrack is difficult.  Many indexers don't list all of the languages available for a particular move. Blu-ray rips and remuxes often have many languages tracks but it is not always easy to search on them.

I'm wondering if Radarr could solve that problem. With the user's permission, Radarr could run mediainfo to get a list of language and subtitle tracks for every movie downloaded. That information would then be sent back to a central database. Over time, Radarr would build a database of language data for all films downloaded by Radarr users.  Of course the data sent back would be anonymous.

After the first person has downloaded a particular file, the language information would be immediately available in subsequent searches  for everyone.

**Comment by fryfrog** [comment]
I can't imagine this is something Radarr (or Sonarr) would ever do, it sounds like an entire *huge* project all on its own. [Open Subtitles](https://www.opensubtitles.org) is already doing this for subtitles, kind of. You might find more interested people there.

I'll leave this open, but @galli-leo will almost certainly close it as something Radarr isn't interested in doing. :)

**Comment by keith555** [comment]
> I can't imagine this is something Radarr (or Sonarr) would ever do, it sounds like an entire _huge_ project all on its own. [Open Subtitles](https://www.opensubtitles.org) is already doing this for subtitles, kind of. You might find more interested people there.

I'm wasn't meaning that the subtitles would be uploaded. I'm just thinking of a simple index:
<Movie ID>: <language codes>.  I maybe shouldn't have used the word database. I'm thinking maybe a hashkey or the movie name, and then list of language codes. 
That information is available to Radarr every time it downloads a movie, so it would just be a case of sending a few bytes to the server and maintaining the index.

The purpose is just to make it easier to search for films based on audio tracks and/or subtitle tracks. At the moment in most cases that is impossible. Many Blu-ray's have several audio and subtitle tracks, but there is usually no way of knowing what they are from the title.

**Comment by fryfrog** [comment]
I understand what you mean, it'd be pretty crazy to actually upload the audio track!

I see how this would be awesome, but it is also clearly its own project. It'd also be useful to any other movie downloader like CouchPotato.

**Comment by keith555** [comment]
Exactly. It would be useful to all kinds of people in all kinds of scenarios. To me it doesn't sound as though it would be all that difficult to implement, but I know those are famous last words!

**Comment by fryfrog** [comment]
Nothing ever is, but this is clearly a stand alone project of its own. It'd need someone *interested* in it to create and own it. Radarr only has a couple developers, it is pretty easy to predict this is outside the scope of what they want to work on.

Great ideas are plentiful, you need to find someone to work on them. Things like OpenSubtitles are already doing a *lot* of what you're talking about, I'm not suggesting they'll do this... but at the very least, you'll have a higher chance of finding someone interested.

I'm not gonna close this, but I'm sure it'll get closed by a developer. ;)

**Comment by keith555** [comment]
Okay. Thanks for leaving it open. Other than than OpenSubtitles, another great source would be Plex. If Plex users could be offered a simple scanner that would pull this information from their libraries, the index could be populated very quickly. I think the information would be available through the existing Plex API.

**Comment by fryfrog** [comment]
¯\_(ツ)_/¯

^ I Googled the shrug emoji so I could paste it here. :)

**Comment by keith555** [comment]
:)

**Comment by galli-leo** [comment]
The idea is great (I might actually do something like it for our own predb), but it wouldn‘t really work, since you couldn‘t really identify whether the release is exactly the same as other people that downloaded it.

In other words, it would only really work for you, if another user has downloaded the exact same release from the same website (else release name will be different).

Additionally, it will be difficult to map a file to a release after downloading with absolute certainty. 

For torrents it could be easier, since you can compare the torrent hash, no idea if there is something similar for nzb.

**Comment by bakerboy448** [comment]
Closing
v0.2 is no longer being actively developed.

If this is still an issue/request on recent v3 builds, please open a new issue.

v3 has had significant language improvement
