### ISSUE TITLE
[Feature Request] pyLoad real-debrid download torrent

### ISSUE THREAD

**Issue by Floflobel** [Radarr/Radarr#3083]
Hello,

PyLoad recently added the ability to download torrents via files or magnets. Would it be possible to add pyLoad as a "download client".

The ticket reference is pyload/pyload#3223

This would be a huge step forward for me as I could ditch the conversion work at real-debrid and reduce my CPU load on my torrent server.

If you need an account for your tests do not hesitate to contact me.

Thank you very much.

**Comment by fryfrog** [comment]
You'll *probably* have to find someone interested in pyLoad to do the work. A quick glance looks like it is more for http upload sites like megaupload or whatever. Am I missing something?

**Comment by Floflobel** [comment]
Actually basic is more for http like mega. But they have just added a feature that is torrent download through the real-debrid site. Indeed it is a very particular case. But it would be a real advance for Radarr IF the http link was supported.

**Comment by stereoa** [comment]
+1

**Comment by quadcom** [comment]
I would be more than satisfied if debrid support simply passed the DL to the torrent app. Being able to scan through debrid sources would be a game-changer.

**Comment by bakerboy448** [comment]
No plans at this time....edge use case
