### ISSUE TITLE
Label from specific indexers

### ISSUE THREAD

**Issue by xiaodoudou** [Radarr/Radarr#3086]
Hi,

I would like to know if it's possible to tag with label some specific indexers so when they are pushed to Deluge or SABNzbd we could get the source of it.

It helps to track the wrong configuration or when seed needs to be preserved for a longer time.

I was thinking we could use the extra parameter field for that but couldn't find any configuration example.

Cheers,

**Comment by galli-leo** [comment]
This won’t be implemented, since only a handful of people would use it. You could configure deluge to detect the trackers of a torrent instead, that’s usually way more important than where the torrent originated from.

**Comment by xiaodoudou** [comment]
Thank you for the tips.

Found my way here; https://forum.deluge-torrent.org/viewtopic.php?t=42629

Cheers,

**Comment by beyondunreal79** [comment]
If I have two indexers, which does it download from?
