### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by ntrmpls** [Radarr/Radarr#3091]
Please add the ability to automatically add all moves “like” a move just added.

**Comment by ntrmpls** [comment]
Yes please.  I would also love the ability to move moves from 1 storage location to another, and to check for duplicates.

Nick

**Comment by geogolem** [comment]
would you like radarr to make breakfast for you too? based on your breakfast choices in recent history?!  LOL - I'm just kidding... but I'm not too sure how smart radarr can be about finding similar movies.. i.e. similar title, similar genre, similar rating.. the variables are endless... but i get what you are suggesting.. 

I personally dont use radarr for "discovery" .. i use trakt for that and i only really add movies via trakt and have radarr import my trakt list.. 

Anyway, you might want to add more details in the title of this feature request...

**Comment by ntrmpls** [comment]
ha ha. Sounds good.  Will do.  I do love Trakt it works well.

**Comment by fryfrog** [comment]
+ Add Movies -> Discover New Movies

Go wild.

Find a list that matches your likes.

Go wild.

Or edit your original title and body to be better.
