### ISSUE TITLE
"MSUBS" is interpreted as hardcoded subs

### ISSUE THREAD

**Issue by crafty35a** [Radarr/Radarr#3092]
If a release contains the text "MSUBS" it is interpreted as hardcoded subs and rejected ("Hardcoded subs found: msubs"). As far as I know, "msubs" is the same as "multisub," so this should not be happening.

Thanks!

**Comment by fryfrog** [comment]
![screen shot 2018-11-13 at 3 48 37 pm](https://user-images.githubusercontent.com/87748/48450577-9ef9a080-e75b-11e8-9a4b-e8aa8e779f84.png)

^ I think you can fix this yourself in Settings -> Indexers
