### ISSUE TITLE
Consider torrents with highest seeds on the same category

### ISSUE THREAD

**Issue by alculete** [Radarr/Radarr#3093]
**Is your feature request related to a problem? Please describe.**
Sometimes when I'm downloading a file I noticed that there are files with better seeds than the one being downloaded

**Describe the solution you'd like**
Files should be searched and consider first the high seeds value

**Comment by alculete** [comment]
> Increase your minimum seed requirements as a solution _right now_.

Used for a while a long time ago and couldn't get some torrents because not all torrents have seeds above, for example, 10 seeds

**Comment by alculete** [comment]
> Radarr prioritizes quality and preferred words over seed always. I’m not sure there is an issue here unless you have an instance of that not being the case.
yes I know, but I think would be better if it could prioritize quality and then if possible  on that quality category prioritize the one with more seeds in descending order

**Comment by Qstick** [comment]
This is already the case
