### ISSUE TITLE
Radarr only uses Blackhole - no other Clients

### ISSUE THREAD

**Issue by Ltek** [Radarr/Radarr#3094]
Radarr has failed to try to use my Syno DL Station once I added Black Hole. I just added BH so I know Snyo was working fine. The log also shoes the Radarrs is not even trying Syno... even with magnets which are not even supported on BH!?

![radarr_blackhole3](https://user-images.githubusercontent.com/1626802/46911250-36789300-cf13-11e8-99db-6b5f2e895744.JPG)
![radarr_blackhole](https://user-images.githubusercontent.com/1626802/46911251-36789300-cf13-11e8-86a3-7107a4b32747.JPG)
![radarr_blackhole2](https://user-images.githubusercontent.com/1626802/46911252-36789300-cf13-11e8-90b4-64dea81f45e4.JPG)
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/2475972/radarr.debug.txt)
[radarr.debug.1.txt](https://github.com/Radarr/Radarr/files/2475973/radarr.debug.1.txt)
[radarr.debug.0.txt](https://github.com/Radarr/Radarr/files/2475974/radarr.debug.0.txt)

3 major problems I see...

1.  No way to tell Radarr which order to try use the Clients.
2. Radarr doesnt try another client when the first one fails
3. Seems there is no smarts to only send magnets to supported Clients!?

screenshots attached.

**Comment by Ltek** [comment]
I figured out what is going on... definitely a bug and lack of proper errr tpping/logging

Radarr is not trap this condition (at all?) correctly and is not checking to ensure when using a magnet that the loader is magnet compatible   I did have 2 down loaders config'd (Syno DL Station and Blackhole) but the one that processes magnets (DL station) was not connecting (wrong credentials) without an error in the log.  But Radarr still tried to pass the magnet to Blackhole, poor form.

What should be happening...
1. log an error that that the provider that does support magnets is failing to connect.
2. log a failure to find a working provider to process the magnet.

**Comment by fryfrog** [comment]
I'm going to leave this for @galli-leo to look at, but I'd suggest using better clients. Nobody should need to use black hole in this day and age. And Synology's Download Station is far worse than pretty much any usenet or torrent client I can think of.
