### ISSUE TITLE
Update Wanted Tab for Movies.

### ISSUE THREAD

**Issue by galli-leo** [Radarr/Radarr#31]

**Comment by fedoranimus** [comment]
How should this be updated? What are the requirements?

**Comment by woble** [comment]
@fedoranimus 
I imagine renaming, removing and perhaps adding new headers to the table. And making it work.

**Comment by fryfrog** [comment]
Right now, the Wanted tab shows nothing for me. Is that expected behavior? Will it ever list the Wanted movies? It seems like all the movies listed as 'missing' should show up here.

**Comment by galli-leo** [comment]
@fryfrog It is currently unchanged from the Sonarr version, so it would show series (which are not there anymore). I will update the wanted tab once I have time.

**Comment by julestop** [comment]
Getting Cutoff Unmet working would also be required as part of this.

**Comment by coltsfan95** [comment]
> Getting Cutoff Unmet working would also be required as part of this.
Was about to post an issue for this. I will second that the Cutoff Unmet tab still needs to be changed from the Sonarr TV versions like the Missing tab was.

**Comment by schumi2004** [comment]
Isn't this resolved already and improved with this commit? https://github.com/Radarr/Radarr/commit/1aae3ae2b5ccc15e24d65a598670b037f86a7cdb
