### ISSUE TITLE
raspberrypi 3 runs out of memory

### ISSUE THREAD

**Issue by mrmkrs** [Radarr/Radarr#3100]
**Describe the bug**
When I install Radarr, configure one indexer and add a RSS list, an out of memory error occours when I start the "Net import" task, and Radarr is unsuable. This started after I updated Mono and Radarr to the latest versions. I don't know what version I was on first. I used to have more movies in the library.

**To Reproduce**
First I removed the Radarr folder in ~/.config/Radarr. After the first start of Radarr, I change the UrlBase in de xml to /radarr

1. Donload latest radarr release, untar
2. In Radarr, add an rss list, mine has 5 items
3. Add one Indexer, I have used Jackett
4. Start the Net Import Sync task

I can repeat this every time with the same result.

**Expected behavior**
I should see the 5 imported movies. I think it fails when on resizing the posters.

**Desktop (please complete the following information):**
```
uname -a
Linux os 4.14.26-2-osmc #1 SMP PREEMPT Thu Mar 15 18:20:26 UTC 2018 armv7l GNU/Linux
```
```
mono --version
Mono JIT compiler version 5.14.0.177 (tarball Mon Aug  6 10:22:46 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       normal
        Notifications: epoll
        Architecture:  armel,vfp+hard
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          yes(3.6.0svn-mono-/)
        GC:            sgen (concurrent by default)
```

```
 free -mh
              total        used        free      shared  buff/cache   available
Mem:           730M        370M        247M         44M        113M        267M
Swap:            0B          0B          0B
```

**Debug Logs**
radarr logs:
[radarr.txt](https://github.com/Radarr/Radarr/files/2477987/radarr.txt)
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/2477988/radarr.debug.txt)

output from journal:
[journal.txt](https://github.com/Radarr/Radarr/files/2477989/journal.txt)

**Comment by fryfrog** [comment]
Might be worth trying 5.16 or 5.12 or 5.10 :/

**Comment by fryfrog** [comment]
I'm gonna close this and suggest you pile on to #3157.
