### ISSUE TITLE
On movie delete, shows info about number of files being deleted initially, while the toggle is set to No

### ISSUE THREAD

**Issue by silentw** [Radarr/Radarr#3102]
**Describe the bug**
When you are deleting a movie from your list, shows the info about how many files will be deleted initially.

**To Reproduce**
1. Go to **Movie Details**
2. Click on **Edit Movie**
3. Click on **Delete** button on bottom left of dialog.
4. See screenshot

**Expected behavior**
The information about how many files will be deleted should only appear when you switch to **yes** the **Delete all files** toggle.

**Screenshots**
![bug](https://user-images.githubusercontent.com/881115/46958059-dc9dd780-d090-11e8-9782-6aa2281e4fdd.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser and Version: Microsoft Edge 42.17134.1.0 (Microsoft EdgeHTML 17.17134)
 - Version: 0.2.0.1120

**Comment by fryfrog** [comment]
If there are more files in the folder, does toggling the Delete all files option increase the number?

**Comment by stuntguy3000** [comment]
@fryfrog without answering your question, OP's initial problem is no longer an issue.

**Comment by silentw** [comment]
As of version *0.2.0.1217* it's fixed.
