### ISSUE TITLE
Manually import downloaded movie not present in a list

### ISSUE THREAD

**Issue by monkiibiz** [Radarr/Radarr#3105]
**Is your feature request related to a problem? Please describe.**
Currently not able to manually import a movie file, unless the movie is already present in the collection.

**Describe the solution you'd like**
Need ability to manually import a downloaded movie without it being present in collection. Currently, if the movie is not present as wanted or already downloaded, the manual import option prompts me to select a movie, but only allows me to select from what is already in the collection. Ideally, the movie would import automatically if only one hit is found in TMDB, or otherwise prompt me to select the right movie, regardless of it being in the collection as wanted or not.
![image](https://user-images.githubusercontent.com/4595037/47084769-df293a00-d214-11e8-84ac-7c2bfb305dd9.png)

**Comment by monkiibiz** [comment]
Somwhat similar to https://github.com/Radarr/Radarr/issues/3098

**Comment by fryfrog** [comment]
This is a long standing request, but I'm having trouble finding it. Can you have a look around on https://feathub.com/Radarr/Radarr and see if you can find it? When you do, give it an upvote and close this.

**Comment by bakerboy448** [comment]
no plans to add movies to radarr via activity
