### ISSUE TITLE
Issues with bulk import movies

### ISSUE THREAD

**Issue by rfgamaral** [Radarr/Radarr#3106]
Regarding this discussion: https://github.com/Radarr/Radarr/pull/3057#issuecomment-430316924

I have now upgraded my Radarr instance and observed that the file name below the path is not working but the quality badge still doesn't show. I'm not sure how to fix this but it shouldn't be hard, right?

Also, a couple more tiny issues on that screen:
- There's a space before the file name (actually `&nbsp` characters in `MoviePathTemplate.hbs`). Are these intentional?
- The ellipsis when the file name is bigger than the available space is in a different color than the file name itself. This needs a bit of work on the HTML/CSS to fix.

I can open a PR to fix those two small issues if you want, unless they are intended to look that way (personally, I'd fix them). I'll wait for your input @galli-leo.

**Comment by rfgamaral** [comment]
Tried a few things about the main issue and reverting this change fixes it: https://github.com/Radarr/Radarr/commit/77f146b262c5678adc3a56c01481800cb9c2c745#diff-a9811681ce7211c77664c0caff0a3ef0

But I'm not sure this is the right approach... Waiting for feedback.

**Comment by galli-leo** [comment]
Definitely not the right approach, will probably have to debug quite a bit to find the error

**Comment by rfgamaral** [comment]
> 
> 
> Definitely not the right approach, will probably have to debug quite a bit to find the error

My best guess is that `movieFile.quality` does not contain a `qualityDefinition` as expected. I initially tried to add that field but wasn't able to correctly populate it with the right value.

**Comment by rfgamaral** [comment]
Another question though... How did that change came to be? I mean, it doesn't seem to come from anywhere, like a dependency on some other changes on that commit. It feels a standalone change that shouldn't have been done, but why was it?
