### ISSUE TITLE
Convert to netcore

### ISSUE THREAD

**Issue by ghost** [Radarr/Radarr#3107]
**Is your feature request related to a problem? Please describe.**
Mono is dead, long live .netcore.

**Describe the solution you'd like**
.netstandard makes it possible to target multiple platforms while sharing as much as you can.
.netcore is faster than mono, 

I have experience converting fullframework to netstandard/netcore.  The conversion to netstandard / new csjproj format is digestible.

**Describe alternatives you've considered**
Rebasing on Sonarr/v3 first!?

**Additional context**
It's a good resume booster too :).

**Comment by rfgamaral** [comment]
> Rebasing on Sonarr/v3 first!?

Not likely to happen, Sonarr and Radarr code bases have diverged a lot AFAIK.
