### ISSUE TITLE
Add "URL Base" to NZBGet (and possibly others), as Sonarr has.

### ISSUE THREAD

**Issue by RyanEwen** [Radarr/Radarr#3109]
**Is your feature request related to a problem? Please describe.**
When NZBGet is behind NGINX, Radarr cannot connect to it since there is nowhere to type in the base URL. 

Eg: https://my.host.com/nzbget -> http://my.host.com:5056 (not exposed to public)

This has been requested for other download clients as well:
https://github.com/Radarr/Radarr/issues/1442

**Describe the solution you'd like**
Same as implemented in Sonarr, which has an advanced "URL Base" input for the NZBGet Download Client settings.

**Comment by chadberg** [comment]
This issue needs to be reopened. Possible there was a reversion in a later release. #3380 purportedly added URL Base, but it is no longer there.

**Comment by Qstick** [comment]
Seems to be there, did you turn on advanced settings? Or is it not working?

![Screenshot_20201204-180257](https://user-images.githubusercontent.com/376117/101223976-56232600-365b-11eb-94c3-7cad33e0764c.png)
