### ISSUE TITLE
Feature request: add a MovieChat link

### ISSUE THREAD

**Issue by Sarkasper** [Radarr/Radarr#3114]
**Description:**

Is it possible to add it next to the Trakt, The Movie DB, IMDB and Trailer buttons?
It would be nice to have a shortcut to the discussions.

MovieChat uses the same codes as IMDB 
For example: https://www.imdb.com/title/tt0837563/ becomes https://moviechat.org/tt0837563/

**Radarr Version:**

0.2.0.1120

**Mono Version:**

5.14.0

**Comment by geogolem** [comment]
many people complain that there are too many links. I personally also use Justwatch links in my private build...

I think it would be useful to add a small section in the UI settings page that enables/disables various links - if that were the case, then it wouldn't be too difficult to add other links that would simply be disabled by default and make all the links optional to be toggled on or off so people can customize/minimize based on their usage/preference etc.
