### ISSUE TITLE
ability to filter out "postbot" and properly rename to include group name

### ISSUE THREAD

**Issue by corwinx** [Radarr/Radarr#3115]
Various releases are now appending "postbot" after the release group name:
\<movietitle>.1080p.WEB-DL.DD5.1.H264-FGT-postbot

with file format options:
{Movie Title} ({Release Year}) - {[EDITION TAGS]}{[QUALITY FULL]}{[MEDIAINFO AUDIOCODEC}{ MEDIAINFO AUDIOCHANNELS]}{[MEDIAINFO VIDEOCODEC]}{-RELEASE GROUP}

resulting in a rename to:
\<movietitle> (2018) - [WEBDL-1080P][AC3 5.1][X264]-POSTBOT

**Expected behavior**
{RELEASE GROUP} should return "FGT", not "POSTBOT"
\<movietitle> (2018) - [WEBDL-1080P][AC3 5.1][X264]-FGT

Believe this sort of behaviour already exists for the word "Obfuscated", is there a way to add additional words like this to get filtered out?

**Comment by anotb** [comment]
Obfuscated is not being filtered out anymore.

**Comment by talisto** [comment]
This isn't working for me.  I've updated to 0.2.0.1293 but my files are still ending up with POSTBOT for the release group.  Is there something I need to do to enable this?  Or is it indexer or downloader specific?  I'm using SABnzbd with NzbHydra.
