### ISSUE TITLE
Radarr not finding downoaded movies

### ISSUE THREAD

**Issue by jbass007** [Radarr/Radarr#3120]
Hey guys, I know this has been discussed before and i have read them all and tried all the steps on many posts. But I had radarr running on a VM and all movies were found no issues. Long story short had to get rid of the VM and do a new setup on a different machine. Re-installed raddar and pointed at the drive and it found most of my movies except 134 of them. I even let it re-download them and it still says missing! the names are right on the file and the movie. the re-name tool sees the file but still says its missing. i'v tried many different names for the file and movie, its in the same format as every thing else it found, did a different browser, cleared cache and cookies ect...

**Comment by fryfrog** [comment]
Try deleting one and re-adding it, does that work? I had a similar problem and this fixed it, but I only had 4-5 movies doing it. Even if that works, I'd hop on Discord and work on this in real time. Deleting and re-adding 130 movies would be a pain in the ass. :/
