### ISSUE TITLE
De-Clutter Disk Usage

### ISSUE THREAD

**Issue by Martidjen** [Radarr/Radarr#3122]
The disk usage list on the system page is a bit cluttered with /snap locations right now (running Radarr on ubuntu 18.04). I would like to see just the "/" location and possible external hard drives

When running df on the terminal on my machine i'm getting the same cluttered list. But when i run "df /dev/sd*" I am only seeing the locations I want to see. I am not sure how the list is generated within Radarr, but this might work.

![df-devsd](https://user-images.githubusercontent.com/7113819/47424434-fb365980-d787-11e8-8a64-bfc6f45e8057.PNG)
![df-h](https://user-images.githubusercontent.com/7113819/47424435-fb365980-d787-11e8-87e3-8e8de138e7e5.PNG)
![diskspace](https://user-images.githubusercontent.com/7113819/47424436-fb365980-d787-11e8-8413-755eea06882a.PNG)

**Comment by Martidjen** [comment]
Found an issue on the Sonarr project to solve this:
https://github.com/Sonarr/Sonarr/issues/2743

**Comment by rfgamaral** [comment]
This was already being fixed by #3050.
