### ISSUE TITLE
Proxy settings not respected while downloading box arts and/or posters

### ISSUE THREAD

**Issue by falahati** [Radarr/Radarr#3126]
**Describe the bug**
Proxy settings not respected while downloading box arts and/or posters

**To Reproduce**
1. Set proxy settings (in my case HTTPS without username and password)
2. Add a movie and refresh
3. Go to logs
4. See error:

**Expected behavior**
Should use proxy settings to download files from the internet. It seems that now all it does is use it to access API endpoints.

**Screenshots**
![image](https://user-images.githubusercontent.com/2479372/47536777-ee704d80-d8ce-11e8-97d1-06cbfe23e11e.png)

**Desktop (please complete the following information):**
 - OS: FreeNas
 - Mono Version: 5.10.1.57 (5.10.1.57 Tue Sep 25 02:06:50 UTC 2018)
 - Version: 0.2.0.1120

**Debug Logs**

> 18-10-26 03:25:04.1|Warn|HttpClient|Failed to get response from: http://image.tmdb.org/t/p/original/tGLO9zw5ZtCeyyEWgbYGgsFxC6i.jpg The remote server returned an error: (404) Not Found.
> 18-10-26 03:25:04.1|Warn|MediaCoverService|Couldn't download media cover for [tt0407887][The Departed (2006)], likely the cover doesn't exist for this movie. The remote server returned an error: (404) Not Found.
> 
> [v0.2.0.1120] System.Net.WebException: The remote server returned an error: (404) Not Found.
>   at System.Net.WebClient.DownloadFile (System.Uri address, System.String fileName) [0x000ad] in /wrkdirs/usr/ports/lang/mono/work/mono-5.10.1.57/mcs/class/referencesource/System/net/System/Net/webclient.cs:413 
>   at System.Net.WebClient.DownloadFile (System.String address, System.String fileName) [0x0000e] in /wrkdirs/usr/ports/lang/mono/work/mono-5.10.1.57/mcs/class/referencesource/System/net/System/Net/webclient.cs:382 
>   at (wrapper remoting-invoke-with-check) System.Net.WebClient.DownloadFile(string,string)
>   at NzbDrone.Common.Http.HttpClient.DownloadFile (System.String url, System.String fileName) [0x0009b] in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:238 
>   at NzbDrone.Core.MediaCover.MediaCoverService.DownloadCover (NzbDrone.Core.Movies.Movie movie, NzbDrone.Core.MediaCover.MediaCover cover) [0x00039] in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaCover\MediaCoverService.cs:137 
>   at NzbDrone.Core.MediaCover.MediaCoverService.EnsureCovers (NzbDrone.Core.Movies.Movie movie, System.Int32 retried) [0x0004e] in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaCover\MediaCoverService.cs:98 
>

**Comment by falahati** [comment]
This is still a problem with the latest version.

**Comment by falahati** [comment]
Yep, Still an issue as far as I can check.

There is a workaround tho. Setting the environment variables before starting the service seems to do the trick to force the app to use the proxy.

**Comment by MrClayPole** [comment]
I have the same issue. If I set the HTTP proxy with authentication then it fails to download graphics.

  | CommandExecutor | Error occurred while executing task RefreshMovie: The request timed out | 18:57
  | MediaCoverMapper | File /usr/local/radarr/MediaCover/190/poster.jpg not found | 18:57
  | StaticResourceMapper | File /usr/local/share/radarr/UI/Content/Images/favicon/manifest not found | 18:57
  | MediaCoverMapper | File /usr/local/radarr/MediaCover/190/poster.jpg not found | 18:57
  | MediaCoverMapper | File /usr/local/radarr/MediaCover/190/poster.jpg not found

Radarr also doesn't download the torrent. The Proxy logs show radarr make authenticated and unauthenticated proxy requests that fail.

If I disable to proxy or set the proxy not to require authentication then this is not an issue

**Comment by fryfrog** [comment]
Does Proxy work in Sonarr? Sonarr's v3? If possible, maybe test in Radarr's v2 (just don't actually switch to it, only bring it up in a test location)?

**Comment by Qstick** [comment]
Yes, they fixed this, but there fix creates other issues for us. Same with Lidarr and why we haven't pulled it

**Comment by falahati** [comment]
Well the change with Sonarr V3 solved it for me. Radarr is still broken tho.
It seems that the build-in update functionality also fails as it uses the `NzbDrone.Common.Http.HttpClient.DownloadFile()` method just like the code for getting box arts.

This commit seems to be responsible:
https://github.com/Sonarr/Sonarr/commit/b0415299ca2f81b9f7d7d430e1c0c5e9a01f0958

If we can cherry-pick it for the next release that would be great.
While doing that, the following commit should also be interesting:

https://github.com/Sonarr/Sonarr/commit/b19d66581716d97e79de2ed52672ed1feed4e985

**Comment by Qstick** [comment]
This is not going to get fixed in v0.2, again there are issues with the fix for us and update processing. We have already added the restsharp proxy commit in Aphrodite.

**Comment by falahati** [comment]
Well if using `HTTPDispatcher` is not an option, it still can be monkey patched until a better fix is available:

https://github.com/Radarr/Radarr/blob/f02fa629ccbd79b1ee9489370f112a89f70fe830/src/NzbDrone.Common/Http/Dispatchers/ManagedHttpDispatcher.cs#L148

`
        public virtual void AddProxy(WebClient client)
        {
            var proxySettings = _proxySettingsProvider.GetProxySettings();
            if (proxySettings != null)
            {
                client.Proxy = _createManagedWebProxy.GetWebProxy(proxySettings);
            }
        }
`

https://github.com/Radarr/Radarr/blob/aphrodite/src/NzbDrone.Common/Http/HttpClient.cs#L249

`webClient.Proxy = _httpDispatcher.AddProxy()`

Should I go for a PR? Or you rather have the right fix in place?

BTW, It is not super important, it's just annoying to me personally.

**Comment by Qstick** [comment]
Feel free to submit a PR to Aphrodite for v3
