### ISSUE TITLE
Additional search language and a few bugs

### ISSUE THREAD

**Issue by Grohnheit** [Radarr/Radarr#3129]
Hi.
I am using the new custom formats.
1 problem that I cant solve is to search for foreign movies (Danish movies in my example) when using the "Any" language setting in the profile.

If I add a movie with a profile that has the "Any" language setting, only English title is search for.
I think this could be solved in 2 ways.
1. When "Any" is selected, another dropdown box appears, enabling the user to select a 2. search language.
2. When "Any" is selected, it uses the search languages from the ticked custom formats.

I know you are supposed to choose "Danish" in the profile, when searching for Danish movies, but that gives a lot of other issues. 

A few bugs that are kind of related:
1. If you select a profile with "Any" language when adding the movie, and later changes the profile to a profile with "Danish" selected, the search language is not changed. You have to delete the movie and add it with the right profile.

2. https://prnt.sc/lb1ysw  this must be do to danish letters ÆØÅ.
These are most of the time translated in to English letters. Could you fix the mapping?
Æ = AE
Ø = OE
Å = AA

Keep up the good work :)

**Comment by galli-leo** [comment]
> 1 problem that I cant solve is to search for foreign movies (Danish movies in my example) when using the "Any" language setting in the profile.

This is something I have thought about some and I haven't really come up with a good solution. It is covered by other issues already though.

API V3 will definitely be necessary here though.

> If you select a profile with "Any" language when adding the movie, and later changes the profile to a profile with "Danish" selected, the search language is not changed. You have to delete the movie and add it with the right profile.

You only need to refresh the movie metadata. This will also be reworked with API V3

> https://prnt.sc/lb1ysw this must be do to danish letters ÆØÅ.
> These are most of the time translated in to English letters. Could you fix the mapping?
> Æ = AE
> Ø = OE
> Å = AA

Yeah this is a known issue, also haven't found a good solution for that yet. Other issues already cover this.
