### ISSUE TITLE
Movie Editor bulk update static path

### ISSUE THREAD

**Issue by aerialace** [Radarr/Radarr#3132]
When i attempt to use the movie editor to bulk update my library and set the static path for all movies to no it does not seem to take effect, when i go in and edit just a single move that static path is still set to yes. It does change if i manually do it one by one just not in bulk

Radarr Ver. 0.2.0.1120

Mono JIT compiler version 4.6.2 (Debian 4.6.2.7+dfsg-1ubuntu1)

Don't get anything in logs other then just the info level of the files being renamed

**Comment by fryfrog** [comment]
I just used Movie Editor on mine to change 2 movies and it worked fine, though was a lot slower than I'd expect.

Your version of mono is quite old, it seems unlikely to be the problem... but 5.12, 5.14 or 5.16 would be worth trying.

**Comment by fryfrog** [comment]
Also, turn logging up to trace and capture more details.

**Comment by aerialace** [comment]
Looks like updating my version of mono resolved this issue for me Thanks for the assistance fryfrog

**Comment by janscarton** [comment]
Having this problem on a new install on a Synology DS918+

Radarr Version 0.2.0.1217

Mono Version 5.8.0.108
