### ISSUE TITLE
Custom Formats bug or wrong regex?

### ISSUE THREAD

**Issue by Jorman** [Radarr/Radarr#3134]
Hi, I'm using the latest Custom Formats version and I made a simple rule
`C_N_RX_\B(LD|MD|SUB.?ITA)\B`
So no ld no md or sub ita
During the insertion I insert the string on lower case, so I insert ... \b(LD|MD|SUB.?ITA)\b then the form transform it to upper case. Is possible that this make the problem happen?
Because Radarr just grabbed this
`A-X-L Un Amicizia Extraordinaria (2018).mkv MD MP3 720p WEBRip iTA`
That contain MD and must not be grabbed
![regex](https://user-images.githubusercontent.com/5203988/47621504-32df3180-daf9-11e8-8f3e-acf9cfd214f2.PNG)

What I miss?

**Comment by Jorman** [comment]
A little update, I'm trying to understand why matches, so I'm removing one char at time and I found that the 8 inside the () do the trick!
![reg2](https://user-images.githubusercontent.com/5203988/47621828-b864e080-dafd-11e8-9ac4-a8d8c5f814aa.PNG)
To start I removed all (2018) and the match disappear, so I tried removing the last ) but match again then the 8 and don't match, so I put back the ) and I discovered that the 8 make it match or not. Then I tried to remove other text and I found that till there's some before the (2018) the regex continue matching, if I remove all before the (2018) the match disappear
![reg3](https://user-images.githubusercontent.com/5203988/47621889-46d96200-dafe-11e8-8aba-0aa90d39144c.PNG)

**Comment by galli-leo** [comment]
You have to use NRX not N_RX. All modifiers should be written together.

**Comment by galli-leo** [comment]
Did you edit your profile accordingly? You need to tell your profile, to only download releases iwth the No MD LD and Sub format.

**Comment by Jorman** [comment]
Each profile has this
![vvv](https://user-images.githubusercontent.com/5203988/47638607-51781380-db5f-11e8-850f-471cb93c6807.PNG)

I don't remember if I activated it or by default I found it activated but I've this activated

This happens when I do a manual search
![sssssssss](https://user-images.githubusercontent.com/5203988/47639508-bd5b7b80-db61-11e8-8e25-c8de6c9ba367.PNG)

What I wrong?
Do you need more log?

**Comment by galli-leo** [comment]
You need to disable None. Else releases with MD are still downloaded

**Comment by Jorman** [comment]
Ok, I tried, seem to work!

![ok](https://user-images.githubusercontent.com/5203988/47650074-65cc0880-db7f-11e8-8b5e-ee641a2649fa.PNG)

Thanks!

So also none was considered, good to know
