### ISSUE TITLE
Alternative to multiple quality/copy request: Ignore manually retrieved files

### ISSUE THREAD

**Issue by cr08** [Radarr/Radarr#3135]
So I won't go into full details why I'd throw my hat into the ring to the overall request to allow multiple files/qualities to be downloaded for a single title. I have also read all the comments as to why it is infeasible at this time.

Here's my suggestion as hopefully an alternative:

Rather than automate the whole process of finding, downloading, and keeping more than a single quality of a title, focus on the single copy as Radarr does now, including trying to aim for and upgrade to the best quality it can based on the profile selected by the user.

Once that has been met, ignore any additional files that appear for that title or if we decide to do a manual search and grab from within Radarr, ignore that as well and do not try to delete the original or mess with it in any way. Just worry about what it does on its own either via its regular searches or an automatic search on a given title/wanted page. The latter is completely optional. I'd be happy with finding the second quality on my own outside of Radarr but currently within the same library folder it will see that and delete it if a higher quality within my selected profile exists.

As an additional optional request to tack on to this if it is picked up: Maybe on the main Movies page, add a quality indicator to each title so we know what quality it has picked up currently.

**Comment by galli-leo** [comment]
Unfortunately, this would not be easy to setup. It is much easier to actually add multiple file support to Radarr.
