### ISSUE TITLE
Sorting on main page using quality and screen size

### ISSUE THREAD

**Issue by Dnkhatri** [Radarr/Radarr#3136]
The sorts on the main page use name for sorting Profile and Downloaded I think it's better for it to be based on screen size then quality.  For Example all the 720p qualities then 1080 qualities.
It can also be made dynamic  by allowing to people to arrange the profiles  to get the sort like they want but that would probably result in a performance penalty for people with huge libraries.

**Comment by galli-leo** [comment]
Not possible with the current UI. There are already issues open for this though.
