### ISSUE TITLE
Remove movie from watchlist in IMDB when imported into Radarr

### ISSUE THREAD

**Issue by pven** [Radarr/Radarr#3139]
When I see a nice movie, I add it to my watchlist in IMDB. This list is read every few hours by Radarr. When it meets the tresholds, it will import the movie into Radarr. But the movie is not removed from the watchlist in IMDB. I know I can add it to the ignore-list, but I want it to be removed from the watchlist in IMDB.

**Comment by geogolem** [comment]
The feature requested here is a special case or another usage of the feature requested in: 
 https://github.com/Radarr/Radarr/issues/1362 

Now that I have referenced that issue I am going to close this issue - if you have anything further to add please mention in the other issue.
