### ISSUE TITLE
Each time a movie is refreshed, and extra entry is shown in the preview rename modal

### ISSUE THREAD

**Issue by chrisallen** [Radarr/Radarr#314]
Each time you click `Update movie info and rescan disk` another entry is shown in the renaming preview when clicking `preview rename for movie`

![image](https://cloud.githubusercontent.com/assets/203867/22041699/ad8855b0-dd6c-11e6-9c63-6a4300258ba2.png)

**Comment by fedoranimus** [comment]
Fixed. However, the multiple entries will remain unless you remove the movie and re-add it.
