### ISSUE TITLE
Movies imported under Radarr installation dir

### ISSUE THREAD

**Issue by blastbeng** [Radarr/Radarr#3145]
**Describe the bug**
Hi guys, after 1 year of 100% working Radar, i think i've found the first issue.    I have two folders (i'm on linux) /home/user/film (where transmission-daemon download my films) and /opt/Radarr (where radarr is installed) , after downloading the film Radarr imports it but it is not renaming and importing in /home/user/film , it is importing the files into subfolder under its installation dir !! for example i expected to have /home/user/film/Inception (2010) , but i've found it under /opt/Radarr/Inception (2010. What the hell is happening!? :smile: :smile: :smile: :smile:

**To Reproduce**
I don't know how to reproduce it

**Expected behavior**
The film should be imported in the same dir of the download client /home/user/film

**Screenshots**
Unfortunately i've deleted these films from my library because i have /opt on another partition and it was almost full

**Desktop (please complete the following information):**
 - OS: Linux
 - Mono Version: Mono 5.16.0.179
 - Version 2.0.0.5252

**Debug Logs**
This is all i've found in the logs, i'll attach more if i find something else!

> 18-11-2 01:01:47.7|Warn|ImportApprovedMovie|Couldn't import movie /home/user/film/Operation.Finale.2018.ITA.Bluray.1080p.CB01HD.mp4

> [v0.2.0.1120] System.IO.DirectoryNotFoundException: Could not find a part of the path.
>   at System.IO.File.Move (System.String sourceFileName, System.String destFileName) <0x7f500bdcdaa0 + 0x0028d> in <3833a6edf2074b959d3dab898627f0ac>:0 
>   at NzbDrone.Common.Disk.DiskProviderBase.MoveFile (System.String source, System.String destination, System.Boolean overwrite) [0x000e3] in C:\projects\radarr-usby1\src\NzbDrone.Common\Disk\DiskProviderBase.cs:245 
>   at NzbDrone.Common.Disk.DiskTransferService.TryMoveFileTransactional (System.String sourcePath, System.String targetPath, System.Int64 originalSize, NzbDrone.Common.Disk.DiskTransferVerificationMode verificationMode) [0x0008f] in C:\projects\radarr-usby1\src\NzbDrone.Common\Disk\DiskTransferService.cs:477 
>   at NzbDrone.Common.Disk.DiskTransferService.TransferFile (System.String sourcePath, System.String targetPath, NzbDrone.Common.Disk.TransferMode mode, System.Boolean overwrite, NzbDrone.Common.Disk.DiskTransferVerificationMode verificationMode) [0x003c2] in C:\projects\radarr-usby1\src\NzbDrone.Common\Disk\DiskTransferService.cs:299 
>   at NzbDrone.Common.Disk.DiskTransferService.TransferFile (System.String sourcePath, System.String targetPath, NzbDrone.Common.Disk.TransferMode mode, System.Boolean overwrite, System.Boolean verified) [0x0000e] in C:\projects\radarr-usby1\src\NzbDrone.Common\Disk\DiskTransferService.cs:183 
>   at NzbDrone.Core.MediaFiles.MovieFileMovingService.TransferFile (NzbDrone.Core.MediaFiles.MovieFile movieFile, NzbDrone.Core.Movies.Movie movie, System.String destinationFilePath, NzbDrone.Common.Disk.TransferMode mode) [0x0012b] in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\MovieFileMovingService.cs:120 
>   at NzbDrone.Core.MediaFiles.MovieFileMovingService.MoveMovieFile (NzbDrone.Core.MediaFiles.MovieFile movieFile, NzbDrone.Core.Parser.Model.LocalMovie localMovie) [0x00052] in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\MovieFileMovingService.cs:82 
>   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeMovieFile (NzbDrone.Core.MediaFiles.MovieFile movieFile, NzbDrone.Core.Parser.Model.LocalMovie localMovie, System.Boolean copyOnly) [0x000b0] in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\UpgradeMediaFileService.cs:69 
>   at NzbDrone.Core.MediaFiles.MovieImport.ImportApprovedMovie.Import (System.Collections.Generic.List`1[T] decisions, System.Boolean newDownload, NzbDrone.Core.Download.DownloadClientItem downloadClientItem, NzbDrone.Core.MediaFiles.MovieImport.ImportMode importMode) [0x0026e] in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\MovieImport\ImportApprovedMovie.cs:110 
>

**Comment by fryfrog** [comment]
This is coming from a list. Go to your lists and change them to the *wrong* root folder. Save it. Go back, change it to the *right* one and then save it. Never save again.

This is a long standing bug that should already have reports in various places and is at least well known by @galli-leo. Closing :(
