### ISSUE TITLE
SABnzbd api URL doesn't meet documentation of SABnzbd

### ISSUE THREAD

**Issue by theerror** [Radarr/Radarr#3146]
According to [API documentation](https://sabnzbd.org/wiki/advanced/api) of SABnzbd, API should be running on http://host:port/sabnzbd/api however, when I added SABnzbd in configuration, In logs I get:

```
Nov  2 11:04:30 vps1 radarr[5481]: [Warn] HttpClient: HTTP Error - Res: [GET] https://server.com:443/api?mode=version&apikey=xxxxxxxxxxxxxxxxxx&output=json: 404.NotFound
Nov  2 11:04:30 vps1 radarr[5481]: [Error] Sabnzbd: Unable to connect to SABnzbd, please check your settings
```
even, when https://server.com:443/sabnzbd/api is normally accessible without issue. When adding SABnzbd configuration, there should be possible enter context url (server.com**/something**) or it should match documentation correctly.

**To Reproduce**
1. Setup your SABnzbd downloader and allow access according documentaion on http://host:port/sabnzbd/api
2. Go to configuration and add new SAnzbd
2. Fill in host, port etc.
3. Click on test
4. See error, that connection failed.

**Expected behavior**
There should be possible change / add context, or requested API should mach documentation

**Comment by thezoggy** [comment]
are you asking if you can configure the api endpoint because you are running it through a reverse proxy? 
sonarr added this setting as `urlbase`
example:
![sab](http://zoggy.net/firefox_2018-11-05_12-01-33.png)

**Comment by thezoggy** [comment]
now if you are talking about the sab side of it, you can configure that url_base via config > specials. default is: `/sabnzbd` which would match up with the docs.

![sab2](http://zoggy.net/firefox_2018-11-05_12-06-31.png)

**Comment by thezoggy** [comment]
and just to add that in sab we have the default mounts of, `/api` and `/%s/api` with %s being whatever the user sets as the url_base.
https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/interface.py#L252

so if the api endpoint isnt working for you.. its most likely because your sab is not exposed/reachable.
check to see if sab is running and if you bind it to the correct adapter and if you expose it as you expect (and port forward if needed).

**Comment by theerror** [comment]
From where did you get those options? When I click Setting > Download Client > PLUS button > SABnzbd I can see dialog like this one, without any option selecting/adding of url base.
![sabnzbd](https://user-images.githubusercontent.com/4508328/48023729-e8843300-e13e-11e8-8d49-7ed4d9462a6a.png)

the fix for me was just adding of simply api :) as context, it's not that hard, I'm just wondering, that I can't see the conf parameter and it also doesn't much the default from documentation.

**Comment by Qstick** [comment]
Related to #3109
