### ISSUE TITLE
Add physical release date column

### ISSUE THREAD

**Issue by mariotacke** [Radarr/Radarr#3151]
**Is your feature request related to a problem? Please describe.**
I'd like to see, at a glance, when certain media will be available on disc in the movies overview.

**Describe the solution you'd like**
On the movies list screen, I'd like an additional column "On disc"/"Physical" (or similar) to indicate when a movie is available on Blu Ray. Optionally, this information could also be displayed in the calendar view as an additional colored entry (Just like "In Cinemas", and "Announced") as "Physical".

**Describe alternatives you've considered**
I usually click on the "The Movie DB" link per movie which contains a physical release date. Some movies do not have this information. This is an optional data point.

Maybe this feature already exists, but I cannot find it. Would love to hear your thoughts on this. :)

**Comment by henryschade** [comment]
> this information could also be displayed in the calendar view as an additional colored entry (Just like "In Cinemas", and "Announced") as "Physical".

I too would like to see this feature.  
While adding this I suggest/ask adding a "Digital" flag as well.
