### ISSUE TITLE
Possible select/add titles in other languages in rename template

### ISSUE THREAD

**Issue by theerror** [Radarr/Radarr#3154]
I rename template, I would like to have option, to include titles in other local languages. 

For example folder & movie name 
{Movie Title} - {Movie Title:CZ} ({Release Year})
Land of Mines - V písku – Příslib svobody (2015)

as for now, there is only some languages (based on UI) and original name. No possible to select CZ (Czech) for example. 

Thank you.

**Comment by s0mm3rb** [comment]
+1 for this feature
I need this
I'd really prefer to have the files and folders named in english instead of the media language (like sonarr does)
plex sometimes has issues with german titles, even though the name format includes the year

@fryfrog do you plan to implement this?

thanks

**Comment by fryfrog** [comment]
I'm not a developer, sorry :(

**Comment by s0mm3rb** [comment]
@fryfrog oh, right, sorry I didn't check

**Comment by Lonli-Lokli** [comment]
Is there any plans to implement this? Seems like https://github.com/Radarr/Radarr/issues/3559 closed as stale.

**Comment by Qstick** [comment]
Yes, it's in the plan
