### ISSUE TITLE
twitter options

### ISSUE THREAD

**Issue by jamesmay07** [Radarr/Radarr#3155]
could we possibly get some twitter options like:

1. Show [Radarr] infront of each post: Yes/No
2. Show quality: Yes/No
3. Custom Msg Syntex: other

Just a little bit more customization so that we can pretty it up a bit please :) love your work btw its awesome.
Kind Regards
james

**Comment by thezoggy** [comment]
posting illegally downloaded content to a public site like twitter just sounds like a bad idea?

**Comment by fryfrog** [comment]
I think Tautulli might do some of this for you?
