### ISSUE TITLE
Same quality title for multiple download qualities

### ISSUE THREAD

**Issue by Rajackar** [Radarr/Radarr#3156]
I have my downloaded movies stored in separate folders based on quality like "2160p / 1080p" etc. 
Radarr will nicely use the quality titel set in the quality settings but it will only allow each title to be used once.
I now have to create all the folders like -Bluray-1080p / Remux-1080p etc manually.
If possible I would really like to use one title for all related qualities. Like 1080p in the example above. This would result in one folder being used for all related content.
Right now when I the same title for multiple quality settings I get an error telling me the settings for that quality can't be saved.
I hope this is possible, thanks!

**Comment by fryfrog** [comment]
Radarr only supports one movie file per folder.

If you want to have say 4k and 1080p, you'll need a second instance of Radarr and you'll need to use different root folders, like `./Movies` and `./Movies 4k`. RadarrSync is a program that makes it easier.

**Comment by Rajackar** [comment]
Just to add, it is possible to create subfolders in Radarr so when set correctly it will put a movie in .\quality\title
This only works if the folder exists and then Radarr will create a fodler with the movie title there and process the movie. Maybe this behaviour is unintended but it works. 
If the change I requested is made then it would be possible to have a folder like 2160p or 1080p and have all movies be put in subfolders there.
I managed to get something working by manually removing the index contrain from the sqlite database and set all the labels there manually. This is now working perfectly and was only a very small change.

**Comment by fryfrog** [comment]
Could you clarify what you mean? Are you talking about Settings -> Media Management?

![screen shot 2018-11-14 at 8 18 55 am](https://user-images.githubusercontent.com/87748/48496022-fe9c8e00-e7e5-11e8-9bbc-4827c1376d7b.png)

I don't think you can do what you want there, so I don't think that is what you mean.

But you could *totally* add a root folder called `1080p` and `4k` and set that for each movie you add, but it won't let you have *two* copies of the movie *in* Radarr. You could use that and two profiles to end up w/ two copies, but only one would actually be in Radarr.

Is that something like what you mean? If not, can you go into a little more detail? Maybe some screen shots?
