### ISSUE TITLE
add list of movies from csv

### ISSUE THREAD

**Issue by e2pluginss** [Radarr/Radarr#3160]
I have a list of movies and there tmdb and imdb id's these have all been renamed but i have a file that lists all titles and id's i want to import all and mark as downloaded

how can i import this its tab seporated csv
Thor                             tt0800369                            imdb
Superman                     1924                                   tmdb

**Comment by fryfrog** [comment]
Easiest I can think of would be to use that list to create a folder full of folders named after the movies w/ a simple bash loop. Then bulk import, they'll all show up as missing.

There are probably other ways to do it too, like getting it into trakt and adding a trakt list.
