### ISSUE TITLE
New user Love it, various feature requests

### ISSUE THREAD

**Issue by Th3MadHatter** [Radarr/Radarr#3161]
If it's possible I'd love to see the following, I'll follow the request form but with multiple requests.

**Is your feature request related to a problem? Please describe.**
Migrated from Couchpotato, worked well, everything got re-snatched better migration? For example couchpotato liked to you "something (the) 2000" instead of "The something (2000)" which makes it miss a lot of things.

Option to Add genre filter for each list based on api (clickable buttons or drop down add instead of %20 %12 which doesn't work well if you have a lot of filters!)
To open that issue up a bit further, if you dislike musical but do like comedy,
dumb example
If Musical
and Comedy is 0 "ignore"
and Comedy is 1 "add"

Add button to globally stop redownloading after initial snatch (checkbox)

Add genres in movie info and/or in list (wanted/library)
(example, A strange thing is lurking in the shadows, only our heroes will find out what it is.... what's the genre? could be horror, could be adventure, comedy, mix?)

My library tab showing just your library without wanted.

Youtube-no-cookie? Maybe more expansive info on each tab through api's without going to the sites?

Mass edit lists based on year, genre etc. 

**Describe the solution you'd like**
I'd like to see it working exactly as i want being completely natural for me... of course it doesn't work that way so anything that's able to be added is just another +1 on a great project.

**Describe alternatives you've considered**
The things i could do I tried to do manually, which is tough, especially for genres and giant lists of things you already have or don't want.

**Additional context**
Nothing, thanks for making a great program!

**Comment by fryfrog** [comment]
I hate to do this, but I don't understand most of what you're asking for. Could you break each feature request down and check that it isn't already requested (either here or at feathub) and then create individual feature requests for each feature?

**Comment by Th3MadHatter** [comment]
Of course, thanks for the reply @fryfrog
