### ISSUE TITLE
Import Wikipedia Table

### ISSUE THREAD

**Issue by Zachary24** [Radarr/Radarr#3164]
**Is your feature request related to a problem? Please describe.**
Premade IMBd list are ok, but most of the time they aren't complete and don't get updated. Wikipedia pages are updated daily, and allow for anyone to add to them.. Helps when trying to archive all movies of a specific genre/type. 

**Describe the solution you'd like**
Allow for importing Wikipedia table/Page

**Comment by galli-leo** [comment]
This will not be done, as there is no clear api available. We would have to scrape the corresponding pages, which we have said we won‘t do for any lists. Feel free to implement something your self though. This is relatively straight forward, you just have to output your stuff in a format for one of the supported lists.
