### ISSUE TITLE
Impossible to access to Radarr from Synology DSM

### ISSUE THREAD

**Issue by Nemrod7** [Radarr/Radarr#3165]
**Describe the bug**
I downloaded Radarr, it's launched but I can't access to. Indeed, there isn't any mention on how to access it. I'm a Sonarr user, so I tried localhost:7878. Nothing

**To Reproduce**
1. Go to 'localhost:7878.'

**Expected behavior**
I'm expecting to access to Radarr

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: DSM 6.2.1-23824 Update 1
 - Mono Version: 5.8.0.108
 - Browser and Version Safari 12.01
 - Version

**Debug Logs**
No access, no logs

**Comment by M0UL** [comment]
you need to use port 8310
