### ISSUE TITLE
When upgrading a movie's quality, add option for a delayed deletion of older file - Feature Request

### ISSUE THREAD

**Issue by an303042** [Radarr/Radarr#3168]
I'm suggesting this feature because of the Plex "recently added" issue that has been discussed many times before, but was never resolved. 
The way I see it, if you add an option for a delayed deletion of older quality, Plex will see both files, you will have a duplicate for a minute, and then when radarr deletes the older quality, Plex will remain with the new/better quality but with the original added date. This should be optional as it seems some people like to have a new quality in the "recently added" (i don't).

All it takes is that radarr will wait a minute or two, really.

Hope you consider this! Thanks

Edit: I see it was considered here - https://github.com/Radarr/Radarr/issues/1829 But I don't know what happened with it...

**Comment by galli-leo** [comment]
It is certainly not trivial to implement this in radarr. Hence, I will not implement this (in the near future anyway). Feel free to throw up a pr, though.

**Comment by an303042** [comment]
I really wish I had the knowledge to take a crack at it myself, but I'm afraid my liberal arts degree isn't contributing as much in these fields :)
Thanks for considering it, anyway!

**Comment by bakerboy448** [comment]
Closing
v0.2 is no longer being actively developed.

If this is still an issue/request on recent v3 builds, please open a new issue.

it sounds like plex_autoscan may help with this?
