### ISSUE TITLE
Consider using similar method to FileBot for detecting Release Group

### ISSUE THREAD

**Issue by chrisallen** [Radarr/Radarr#317]
FileBot maintains a list of regular expressions to match Release Groups in filenames. When writing the groovy expressions you can check that {group} is not in the movie name by doing this same
` {n.findMatch(group) ? null : '-'+group}`

it would be awesome if Radarr could get permission to use this list (if needed) --> https://github.com/filebot/data/blob/master/release-groups.txt and use it along with regex checking the movie name, so we get better releasegroup detection.

FileBot forum thread: https://www.filebot.net/forums/viewtopic.php?f=5&t=4

**Comment by onedr0p** [comment]
moved discussion to http://feathub.com/Radarr/Radarr/+13
