### ISSUE TITLE
Jackett results are not the same

### ISSUE THREAD

**Issue by kaiserssosse** [Radarr/Radarr#3170]
Hi,
I am using Radarr with Jackett and the result for the movie Ant-Man y la Avispa are totally different.
In Jacket I have valid results, but in Radarr I have 4-6 results and no one is related to this movie. I don't know if the parse is not doing well or the movie title is not taking appropriately.

I've tried to find the reason but nothing found.

**Comment by galli-leo** [comment]
https://github.com/Radarr/Radarr/wiki/Common-Problems#jackett-shows-more-results-than-radarr-when-manually-searching
