### ISSUE TITLE
Changing movie types with multiple > single pages doesn't show results

### ISSUE THREAD

**Issue by spitcool** [Radarr/Radarr#3171]
When viewing movies in a list (Say, "announced" or "all) that has multiple pages, if you are on a page that doesn't exist in the next list you select, the list will not change (but it will indicate that it did). 

**To Reproduce**
1) go to "all" on the main radarr page
2) go to page 2 or 3, or a page that doesn't exist in another list
3) select another list (say, "in theaters") that only has 1 page (or fewer than the page number you selected on the previous list)
4) --note how the list does NOT change, yet it indicates that it does based on the list selector
5) to fix, return to page 1, then re-select the list you wanted to change to

**Expected behavior**
When switching lists, page returns to 1, not keeping page number from previous list

**Screenshots**
http://share.chrisspitler.com/3c033ddae8ad

**Desktop (please complete the following information):**
 - OS: Mac OSX 10.13.6 for client, server running on synology DS. Client is Google Chrome 
70.0.3538.77 (Official Build) (64-bit)

Version
0.2.0.1120
Mono Version
5.8.0.108 (tarball Sat Feb 24 09:55:00 UTC 2018)

**Debug Logs**
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/2569660/radarr.debug.txt)

**Comment by galli-leo** [comment]
This won't be fixed in the current version of the UI. It's only a small visual bug.
