### ISSUE TITLE
Unable to manually force download a movie

### ISSUE THREAD

**Issue by kylemart** [Radarr/Radarr#3173]
**Describe the bug**
Automatic downloading of The Pit and the Pendulum doesn't work because all available torrents use the title 'Pit and the Pendulum' and according to Radarr the title 'Pit And The Pendulum' could not be found amongst the alternative titles of the movie. However, when trying to manually force download a torrent, nothing happens.

**To Reproduce**
1. Click on 'Add Movies'
2. Type in 'The Pit and the Pendulum (1961)'
3. Set 'Monitor' to 'No', and 'Profile' to 'Any'
4. Click on the 'Add' button
5. Click on 'Go to movie'
6. Click on the 'Search' tab
7.  Find a torrent with the following rejection: 'Failed to map movie, found title Pit and the Pendulum, expected one of: The Pit and the Pendulum, Edgar Allan Poe's Pit and the Pendulum' and click on the 'Force add to download queue' button
8. Click on the 'Force Download' button

**Expected behavior**
The forced download should complete.

**Desktop:**
 - OS: macOS (However, Sonarr is running in a Docker container on a Debian-based machine)
 - Mono Version: 5.10.1.20 (tarball Thu Mar 29 10:44:58 UTC 2018)
 - Browser and Version: Chrome, 70.0.3538.102
 - Version: 0.2.0.1120

**Debug Logs**
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/2569964/radarr.debug.txt)
[radarr.txt](https://github.com/Radarr/Radarr/files/2569965/radarr.txt)

**Comment by galli-leo** [comment]
Seems like the main issue is that your Radarr instance cannot communicate with the mappings service. While this shouldn't cause the force download to fail, as a workaround I suggest you look into fixing that.

**Comment by xFilosofx** [comment]
I have some issie on windows server 2019. 
In Log files: 
18-11-20 18:23:00.6|Info|RefreshMovieService|Unable to communicate with Mappings Server.

**Comment by xFilosofx** [comment]
It's not enhancement, it's critically bug. People with non-english tracker can't download movie. @galli-leo can you help us with this issue?

**Comment by xFilosofx** [comment]
I can solution for my situation. I started communicate to mapping service with Proxy in onther country and all work now.
