### ISSUE TITLE
Radarr wont start

### ISSUE THREAD

**Issue by Firetv344** [Radarr/Radarr#3179]
did a pkg upgrade in freenas 11.2....beta 3 and now radarr and sonnar wont start....cant access the webgui...any help is appreciated

**Comment by stuntguy3000** [comment]
Do you have any console errors or a log of some kind?

**Comment by Firetv344** [comment]
im not getting any error....how would i see the logs

**Comment by stuntguy3000** [comment]
I have never used FreeNAS so I can't provide help on that front sorry - perhaps Google around.

**Comment by Firetv344** [comment]
ok...thanks

**Comment by Firetv344** [comment]
any help
