### ISSUE TITLE
Integrate RadarrSync into Radarr (i.e. add a list for other Radarr instances)

### ISSUE THREAD

**Issue by edsai** [Radarr/Radarr#3180]
When adding another Radarr server as a List source, movies are retrieved with the right title but the wrong TMDBid and trakt.tv ID. This means movies can't be added from other Radarr instances because they've got the wrong ID. In Trak.tv the movie IDs end up referencing the wrong movie entirely.

**To Reproduce**
1. On destination Radarr instance, go to Settings -> Lists -> Add list (+ sign)
2. Select Custom under Radarr Lists
3. Enter in http://<radarr source server name or ip:port>/radarr/api under "Radarr API URL" and /movie?apikey=<api key of remote server> under "Path to list"
4. Click test and save new entry
5. Click "Add Movies" in main menu bar and then click "Add Movies from Lists"
6. Select list for source server from "List" drop down and click "Fetch"
7. Click any movie title and it will go to the TMDB movie link with the source Radarr server's collection movie ID as the TMDBid or the trakt.tv ID. For example, "10 Cloverfield Lane" has the url of 
https://www.themoviedb.org/movie/1 as the TMDB link. 

**Expected behavior**
Movie IDs for Radarr lists from other Radarr servers have the correct TMDBid and Trakt.tv list ID allowing them to be added and monitored.

**Desktop (please complete the following information):**
 - OS: linuxserver.io docker container
 - Mono Version: 5.16.0.179
 - Browser: Safari on Mac OS X Mojave
 - Version 0.2.0.1217 and before

**Debug Logs**
Here's an example of trying to import 10 Cloverfield Lane.
Message
Couldn't map movie 10 Cloverfield Lane to a movie on The Movie DB. It will not be added :(: Movie with imdbid Movie not found. was not found, it may have been removed from IMDb.

Exception
NzbDrone.Core.Exceptions.MovieNotFoundException: Movie with imdbid Movie not found. was not found, it may have been removed from IMDb.
  at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.GetMovieInfo (System.Int32 TmdbId, NzbDrone.Core.Profiles.Profile profile, System.Boolean hasPreDBEntry) [0x0081e] in C:\projects\radarr-usby1\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:311 
  at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.MapMovieToTmdbMovie (NzbDrone.Core.Movies.Movie movie) [0x0000b] in C:\projects\radarr-usby1\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:680

**Comment by fryfrog** [comment]
I've never heard of anyone doing this, is it supposed to be possible?

**Comment by edsai** [comment]
I'm not sure. The use case is mirroring two Radarr libraries between sites. It's more efficient to have Radarr sync movie IDs instead of syncing the content itself. I (maybe wrongly) assumed that the ability to add a Radarr instance as a Radarr list would work.

**Comment by fryfrog** [comment]
[RadarrSync](https://github.com/Sperryfreak01/RadarrSync) might be just what you're looking for.

**Comment by edsai** [comment]
I saw that and there are a couple issues with it. The first is that the root paths are identical between servers and second was weird issues with the python modules requiring ImageMagick. I tried to alter the script a bit but gave up. Was hoping that the built-in Radarr list functionality would just work.

**Comment by fryfrog** [comment]
My *guess* is that this was never intended to work, but I'll leave it for an actual developer to confirm/deny.

At the very least, it is an interesting use and seems reasonable to get working *if* it isn't too much work. :)

**Comment by galli-leo** [comment]
@Qstick or @rfgamaral Do you think, one of you would have time to look at this? Shouldn‘t be that hard, just add a new list that reads from the API of a second Radarr instance.

**Comment by Qstick** [comment]
@rfgamaral you want to take this one since you have been in list code as of late?

**Comment by rfgamaral** [comment]
Sorry guys, I don't have time for this right now :(

**Comment by Morktral** [comment]
In my opinion super helpful!

Just one case where it might be more then helpful:

Some people don´t download with there macvhione at hoime they rather use a seedbox somewhere in the net, but this seedbnoxy doesn´t see your local files and is downloading the same file over and over again because you already copied the version to your local PC.

So one Radar instance could be installed locally looking for the moviues and qualities you have and telling thze other one "yes this is needed"....

**Comment by fryfrog** [comment]
You don't need that, just remote mount your seedbox w/ something like sshfs.

**Comment by danialmoghaddam** [comment]
Very useful feature in my opinion.

"Many Plex servers choke if you try to transcode 4K files. To address this a common approach is to keep a 4k and a 1080/720 version in seperate libraries." - from **Sperryfreak01/RadarrSync**

**Comment by gokou340** [comment]
Would also find great value to this feature.

As @edsai stated, RadarrSync isn't an option most people want to use, as I personally won't want my Root Paths to be the same on my 4K stuff.

**Comment by fryfrog** [comment]
I think only the "new" version of RadarrSync added that same root paths thing. It was a symptom of the author using Docker and just not realizing other uses. It isn't likely to be actually required...

Except of course that development of it has stopped. :(
