### ISSUE TITLE
"unable to process file" error when doing manual import

### ISSUE THREAD

**Issue by sch1308** [Radarr/Radarr#3182]
![image](https://user-images.githubusercontent.com/7896067/48523309-e3636a00-e849-11e8-98b3-b3397a87d292.png)

![image](https://user-images.githubusercontent.com/7896067/48523330-01c96580-e84a-11e8-85c1-cf6c68da3f22.png)

![image](https://user-images.githubusercontent.com/7896067/48523354-1e659d80-e84a-11e8-8ac2-a17f8e078dce.png)

unraid 6.6.5
Radarr Ver. 0.2.0.1217

all video files can be played via VLC on the network drive I know they are valid video files. (.mkv) 
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/2583256/radarr.debug.txt)

**Comment by galli-leo** [comment]
Can you please give a trace log? There is nothing inside this debug log file that would indicate an error. (Have you provided the log file without any modifications? Seems quite empty for a debug log)

**Comment by sch1308** [comment]
[radarr.trace.txt](https://github.com/Radarr/Radarr/files/2591233/radarr.trace.txt)
when i select the movie from the dropdown, then select the quality as 1080p when i click import it will say "manually importing movie" i screenrecorded the error. 
https://youtu.be/DCLSHF0FZYA
