### ISSUE TITLE
Show highest quality available on search page (preview)

### ISSUE THREAD

**Issue by Zachary24** [Radarr/Radarr#3183]
**Is your feature request related to a problem? Please describe.**
I feel setting a Profile is (almost) useless since there is no easy way to see the highest quality/available qualities.

**Describe the solution you'd like**
Show the highest quality for that movie (within your indexers), just like the state of production (announced, released, etc) and rating

**Comment by galli-leo** [comment]
This is not only very hard to do, but would put a lot of unnecessary stress on your indexers. I have planned a feature for the new API to return what qualities a movie can be found on general indexers (i.e. just if the movie is available in a given quality).
