### ISSUE TITLE
Indexers: limit number of API requests

### ISSUE THREAD

**Issue by Jarcol** [Radarr/Radarr#3184]
**Is your feature request related to a problem? Please describe.**
A large number of NZB Indexers are limited by a maximum of API requests per 24 hours. This results in stressed Indexers and a large number of log-entries

**Describe the solution you'd like**
It would be nice to add api-request-limits to the Indexers so that these won't get stressed and the warnings in the log table will be less too.

**Describe alternatives you've considered**
Limit the amount of times Radarr searches

**Additional context**
none.

**Comment by galli-leo** [comment]
Change your RSS sync interval or use something like nzbhydra to have greater control over your indexer.
