### ISSUE TITLE
Option to add global genre block or allow

### ISSUE THREAD

**Issue by Th3MadHatter** [Radarr/Radarr#3188]
**Is your feature request related to a problem? Please describe.**
Right now you need to add genre blocks for each list, that is fine BUT, they often error out, even if you add them as their true values (e.g. %20 for drama on).
A global block would solve this with a "ignore global block" checkbox on each list you manually add.

**Describe the solution you'd like**
List blocks don't work if you add multiple block values, if this is because of the api or the app? No idea but it often errors out. 
A global block list of things people don't like (e.g. Western, Comedy or Action) could easily be added and automatically converted into the right syntax for the API's added by the user.
Adding a "don't use blocklist for this list" box prevents any form of issues for the user.

**Describe alternatives you've considered**
Add exact forms of block list entries for each API, which will be a lot more work, it would be cool though!.

**Additional context**
None, i love radarr.

**Comment by bakerboy448** [comment]
Closing
v0.2 is no longer being actively developed.

If this is still an issue/request on recent v3 builds, please open a new issue.
