### ISSUE TITLE
Add a box, do not search after grab/mark as unmonitored

### ISSUE THREAD

**Issue by Th3MadHatter** [Radarr/Radarr#3189]
**Is your feature request related to a problem? Please describe.**
Not too much to say about this, I've been working with it for a while but i'm really missing this feature, sometimes I want propers and that part  is covered but sometimes I want it to be completely unmonitored afterwards. I would love to see a checkbox marking everything as unmonitored after meeting a certain requirement (e.g. PTP gold star 1080p = done, TPB 720p = upgrade, this is way too much work but a general example so just, if you use the option to prefer a certain release mark it as unmonitored once grabbed after you check the global box)
 
**Describe the solution you'd like**
You could monitor each thing, check for proper improvement, if yes upgrade, if new release is added grab IF it matches A, B and C options (e.g. A. Quality. B release date, C. Release Group) but that's a lot more work. This should cover most peoples needs.

**Describe alternatives you've considered**
I think I messed this post up, my alternate solution is above this one but I hope you guys get it.

**Additional context**
None, Radarr <3

**Comment by galli-leo** [comment]
This is already the case when cutoff is met. This can be done with either just qualities or the new custom formats to set cutoff once a movie reaches e.g. 720p PTP Gold

**Comment by Th3MadHatter** [comment]
I gave that a try but no dice, i'll try again.
