### ISSUE TITLE
A "my library" tab

### ISSUE THREAD

**Issue by Th3MadHatter** [Radarr/Radarr#3190]
**Is your feature request related to a problem? Please describe.**
A new tab showing everything you got instead of the general list where it shows everything included downloaded.

**Describe the solution you'd like**
Nothing that's the problem.

**Describe alternatives you've considered**
None, look at couchpotato (OLD).

**Additional context**
Radarr is great, yet again.

**Comment by galli-leo** [comment]
Not sure what you want here, there is already the general list, where you can filter by downloaded, so you should have everything there.

**Comment by Th3MadHatter** [comment]
A general TAB, that shows only those videos available in your library, e.g. Library tab.

**Comment by Th3MadHatter** [comment]
Ok let me put it this way,

You have My Library, everything in that is just what you have, that gets a nice poster view, good scraping of genres and the files you have, quality and so on. Not unlike couchpotato.

Your current wanted tab becomes a true wanted tab. Got it? Don't want it improved? Removed until rechecked in My Library.

This makes it more organized, easier to view what you really have and what it's all about and allows you to quickly remove or opt for an upgrade, it isn't that its IMPOSSIBLE to see your movies in the current list but its a mess, even if organized you eventually end up going through your wanted files while you're browsing, at least that's the problem I stumble into constantly,

It's a feature request, a minimal one that shouldn't make too much impact but I think a lot of people will like the feature (a lot of people did in couchpotato too because it's neat and organized).

**Comment by galli-leo** [comment]
@Th3MadHatter How is that different from the current wanted tab? You can either select missing, which only shows movies with no files or all movies that haven‘t met the quality you would like. If you want to have the same views as the main page, that will come with a new UI. Additionally, you can just sort by downloaded, then you should have all movies with no files grouped together.

**Comment by Th3MadHatter** [comment]
It is different in the way that it's not easy to manage. You can't clean just your library, look in just your library or see detailed information about your library right from hitting your tab.
I don't know if you have ever seen the Library used in Couchpotato but it's hard to explain the benefits of it without actually seeing it in action.
The same thing goes for my "scrape genres" request that got denied because it's already there. It's KIND OF there but it really isn't, e.g. I can see genres just fine if I go to the poster and click on imdb but I can't see them scraped in the boxes in the post menu or in the sorted portrait set up so it's missing a quick overview where you have to read the entire description and guess the genre instead of "Biography, music? Don't want that anymore".. 
I'm just using that as an example because it might be easier to explain that one then the library one but a new tab adds for a more organized view that's easier to maintain and manage.
But if this is already planned for the new UI the feature request is filled already, I just have to wait :smile: 

_Also, this is off topic and most likely something i'm doing wrong so I'm adding it as a side note instead of making a whole new topic for it.
If something is done in e.g. 1080 WEB-DL and i'm fine with that, propers are off, and it matches one of the DL criteria, it STAYS MONITORED, i tried every option available but I have to toggle them all manually, am I missing something or is it just a feature that isn't there?.
Don't usually add a question to a feature request but saves yet another topic._
