### ISSUE TITLE
Genre ID's in list

### ISSUE THREAD

**Issue by Th3MadHatter** [Radarr/Radarr#3191]
**Is your feature request related to a problem? Please describe.**
If you click a movie it shows perfect information, name, date, what its about and even a few pics, what it doesn't show is GENRES, This can be extremely confusing for, lets say a video with the following title and description.

"Blue water

A great reaf! but what would happen if you put 5 people in it?"

It could be a horror, it could be a comedy, it could be a drama, it could be all of the genres mentioned before.

**Describe the solution you'd like**
It doesn't show that unfortunately so I'd love to see that scraped from imdb or trakt.

**Describe alternatives you've considered**
None I can think of.

**Additional context**
Same thing, Radarr is awesome 👍

**Comment by galli-leo** [comment]
This is something that is planned for the new UI and API v3, but there are already issues open for this.

**Comment by Th3MadHatter** [comment]
Sorry I searched for similar things but so many genre issues popped up I must have missed it.
Thank you.
