### ISSUE TITLE
Use Youtube-no-cookie for trailers

### ISSUE THREAD

**Issue by Th3MadHatter** [Radarr/Radarr#3192]
**Is your feature request related to a problem? Please describe.**
Right now we don't have a proper trailer viewing option, it's great for privacy but most people click youtube anyway.

**Describe the solution you'd like**
Use intergrated youtube no cookie solution (see duckduckgo or old couchpotato or disconnect) to view the trailer INSIDE the app but only after clicking it.

**Describe alternatives you've considered**
None I can think of. build an independent youtube? 👅 

**Additional context**
None.

**Comment by bakerboy448** [comment]
No Plans for this at this time
