### ISSUE TITLE
Mass edit list

### ISSUE THREAD

**Issue by Th3MadHatter** [Radarr/Radarr#3193]
**Is your feature request related to a problem? Please describe.**
Right now we can organize on date and manually edit one by one.
What if we don't want anything from 1900 and there are 600 entries of it?
We need to go one by one editing them to unmonitored and remove.

**Describe the solution you'd like**
Add an option in the management that you can mass select and delete, asking to unmonitor, for everything you selected or based on a year or genre.

**Describe alternatives you've considered**
A lot of different options but whatever you guys think would be best, i'm not into the code enough to do a PR for it :)

**Additional context**
none

**Comment by galli-leo** [comment]
Already available with the movie editor.

**Comment by Th3MadHatter** [comment]
It isn't, if it is it doesn't work, else i wouldn't have requested it. 
Please look into my specific request, not the general topic.

**Comment by Th3MadHatter** [comment]
Excellent, looking forward to it! The only things I really miss in radarr are the My Library tab couchpotato had to give a good view and easy edit of your owned content, and a well working genre filter that just accepts everything you throw at it (I tried things like Drama, Biography and even searched for the exact %20, %116 numbers but it always errors out in most lists.. but I digest.. lol

**Comment by skidaddl3** [comment]
Yes, I have the problem of running out of individual HDD space and have Radarr seeing multiple "root" folders (i.e. drives). The movies which are still being monitored are still attempting to go to the full drive(s), therefore I would like to point them to a new root folder in a "Mass Edit" mode. At least the ones that show up with the yellow "not enough free space" icon in the Activity page. The other filtered, wanted and missing movies should also therefore be modified and if you have a lot being tracked, it's annoying doing that individually. Defeats the purpose of the management system in the first place...
![activity queue](https://user-images.githubusercontent.com/13662868/54806986-b6c5d000-4ccb-11e9-903d-5d179a59ec9a.png)
