### ISSUE TITLE
Feature Request: Expose System and Activity alerts via API

### ISSUE THREAD

**Issue by jeremysherriff** [Radarr/Radarr#3196]
**Is your feature request related to a problem? Please describe.**
It can be frustrating to log in to the web UI and find that the Radarr system is in error state for some reason.   Screenshot:
![image](https://user-images.githubusercontent.com/1082213/48683269-3ace5500-ec11-11e8-9e85-93b9033e0c0e.png)

**Describe the solution you'd like**
I'd love to see this status exposed via API.  There is already a system status API end-point ("/system/status") which could be extended to include new fields, or an additional API (or two) could be added that exposes system alert status and activity status.  By using an API endpoint, advanced users can leverage scripts to poll the API whenever they want, and expose the state via a unified web interface such as Organizer or HTPC-Manager, or send notifications via email or however suits them best.  A basic bash or powershell script can be included in the Radarr documentation as a recipe for getting started.

**Describe alternatives you've considered**
Notifications via the Connect setup may also be a viable way to bring attention to faults with the system, however then thought must be given to how often to notify on faults that have been in place a while.  

**Additional context**
The API endpoint would need to expose a number of attributes about the fault situation, similar to what the web UI icon badge does now; severity (currently done via colour), number of faults (currently done via a counter on the badge), and potentially a full list of the current faults or indexed access to each of the fault details.  All of this information is currently available via the web UI so the logic to retrieve this information is already in place.

**Comment by jeremysherriff** [comment]
Noe that this is equally applicable to Sonarr and Lidarr.

**Comment by galli-leo** [comment]
There is an api already there, else the web ui wouldn‘t have the ability to poll this data. The documentation just is not there.

The endpoint can be found at: /api/health
