### ISSUE TITLE
"Update Custom Formats" doesn't seem to do anything

### ISSUE THREAD

**Issue by hergonoway** [Radarr/Radarr#3197]
Hello, 

(currently running the latest version of linuxserver.io image, with Version
0.2.0.1217 of Radarr)

I've tested Custom Formats, and so far it does the job for new movies, but I've got 2 issues when I try to update my existing movies with the "Update Custom Formats" button in Movie Editor. 
- [1] : randomly whatever the amount of movies to process it's simply don't want to work, returning this : 
<img width="179" alt="image" src="https://user-images.githubusercontent.com/8405448/48728237-b55c9c00-ec34-11e8-992e-ab7be77397d8.png">

and in the logs : 
```Error occurred while executing task UpdateMovieFileQuality: Expected query to return 221 rows but returned 220.```
also if I process 6 files for example, the notifications says "Updating quality for X/5" instead of "Updating quality for X/6" 

- [2] : went it runs (so, not in case [1]) everything seems to process fine, but when I check the file tab in a processed movie, the Custom Formats doesn't appears. I've tried with the default "x264", added it to my main profile, and all my files tested are in x264 with "[X264]" in their filename. it's problematic because it redownload the movie in x264 even if it's already in x264 when rssSync run. **BUT** everything is back to what is expected if I resfresh&scan the movie afterward. Shouldn't it be updated automatically ?

**Comment by hergonoway** [comment]
Support thread created : 
[on /r/radarr](https://www.reddit.com/r/radarr/comments/9yqoz5/update_custom_formats_doesnt_seem_to_do_anything/)

**Comment by Davst** [comment]
I have the same issue. Query in UI returns the incorrect number of issues when selecting all items for update.
