### ISSUE TITLE
Can't add a movie after playing with custom tags and quality profiles

### ISSUE THREAD

**Issue by WSHaRK993** [Radarr/Radarr#3198]
Hello,

Version : 0.2.0.1217
Mono Version : 5.16.0.179 (tarball Thu Oct 4 10:20:38 UTC 2018)
Latest Ubuntu LTS

I did some tests with custom tags and quality profiles but I can't remember exactly what. I can't add a new movie anymore. Here is the error log every time I try to add a movie in any ways (monitor on/off, tried all the quality profiles)

```
Request Failed: The DataMapper was unable to load the following field: 'Quality' value: '{
  "quality": 7,
  "customFormats": [
    9
  ],
  "revision": {
    "version": 1,
    "real": 0
  }
}'. The given key '9' was not present in the dictionary.
```

I suspect the error comes from when I added a custom tag, included it in a quality profile, and deleted the custom tag. I tried to recreate a custom tag, modify all my quality profiles by unchecking all the custom tags or selecting only 'none'... no way to avoid the error.

**Comment by WSHaRK93** [comment]
I solved my issue by inserting a new line with Id=9 in the CustomFormats table.

There's probably an issue when you delete a custom format, but I don't know when and where it happens.

**Comment by fryfrog** [comment]
Could you also maybe have edited the profiles in question and saved them with new/different tag/custom format?

(I can't tell if you're talking about tags or custom formats, you mention both)

**Comment by galli-leo** [comment]
@WSHaRK93 Do you remember your exact steps after deleting the custom format? Did you keep the browser window open? Did you add a new format? Did you delete a profile? Did you delete a movie? etc. There should be safeguards for everything, but it seems that something must have slipped through.

**Comment by WSHaRK93** [comment]
Sorry I don't remember the exact steps. Operations I'm pretty sure I did : 

- Create new Custom Formats
- Modify Custom Formats (Change name, add/remove Format Tags)
- Delete Custom Formats

- Add a new movie
- Change the profile of existing movies

- Create new profiles
- Modify profiles (change name, un/checking Custom Formats, modify order of Custom Formats)

I didn't delete a movie or a profile.

I'm pretty sure I left my browser window opened all the time.

The steps could have been : create new custom formats, add them to new profiles, add new movies with those new profiles, and while it searches for releases I modify/delete custom formats ? 

According to my logs, the first occurence of the error (field missing) appeared right after a linking
![capture](https://user-images.githubusercontent.com/45203755/48826587-0373bb80-ed6b-11e8-87cb-791f15059cd6.PNG)
