### ISSUE TITLE
Update Calendar Tab for Movies

### ISSUE THREAD

**Issue by fedoranimus** [Radarr/Radarr#32]

**Comment by galli-leo** [comment]
We should also implement the release dates endpoint of The Movie DB for use in the calendar.

**Comment by woble** [comment]
Consider adding a `year` view — easier to get an overview what to expect when.
Default view should be `month`.
Views `week` and `day` don't make much sense for movies, so perhaps remove it.

**Comment by onedr0p** [comment]
I concur @woble

**Comment by jOOc** [comment]
Nice work, but upcoming list on the left side is still empty.

**Comment by galli-leo** [comment]
@jOOc But do we still need that with the year list though?

**Comment by jOOc** [comment]
@galli-leo No, but then maybe have the list use the whole width
