### ISSUE TITLE
Newz-Complex Indexer

### ISSUE THREAD

**Issue by kaplannn** [Radarr/Radarr#320]
Hi Guys,

Newz-Complex is probably one of the biggest **german** usenet indexer. its based on newznab.

A lot of german people would really appreciate it, if you could add this Indexer: https://newz-complex.org/www/

the admins already know about this and they configured what i could find in this issue: https://github.com/Radarr/Radarr/issues/4#issuecomment-271985127

> Again, this is not a issue we can solve. Please get in touch with you indexers staff and ask them if they can add the following flag to their 
> 
> Code:
> /api?t=caps
> 
>  RSS feed. Most support searching movies but don't have this flag set.
> Code:
> movie-search available="yes" supportedParams="q,imdbid"
> 
> Thanks.

But it's still not working. Maybe some additional stuff must be changed?

Thanks in advance.

**Comment by kaplannn** [comment]
Sorry, but i was too quick. it took some time, to refresh the changes. 

> movie-search` available="yes"

This did the job. now it's working fine. Thanks :)

**Comment by MoeJoe87** [comment]
@kaplannn can you contact me, i have a question about the indexer....moli@tibners.ch
