### ISSUE TITLE
OMG 404 not found

### ISSUE THREAD

**Issue by arsenicks** [Radarr/Radarr#3202]
**Description of the bug**
A movie was requested thru ombi, ombi interface is in english, the language in the quality profile that ombi set is in french.

I see the movie has been added, because if I want to add it again in radarr, it says already exist. But if I click the "Already Exist" link I get a 404, the uri of the page contain the movie name in english, I've found another link if I go to the wanted page and click the movie name there I get the correct url which contain the movie name in french..

I tried all the suggested workaround I've found, clearing cache, restarting service(container)

**To Reproduce**
1. Go to Ombi, request a film, aprove.
2. Try to find movie in Radar library, can't
3. Search the movie name to add a new movie, it's mark as Already Exist, click the button
4. See 404 error

**Expected behavior**
I mean I expect all link to point at the right place, obviously something's wrong!

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux, Firefox
Using latest linuxserver.io docker image

**Debug Logs**
From the web console in firefox:
XML Parsing Error: no element found
Location: http://XXXXXX:7878/radarr/signalr/poll?transport=longPolling&connectionToken=nj%2F3bWkjQWEe4dIc8auczhKTgQkRlWkWe3Ax45%2B123sENm59uPGcCPE5g5hvOPSMHg5Wp1B4aehJGetaJD5VbL%2F1ARu0dwhyluawPNEZJzYn90vn5nkZpb5nqb12W%2FN04XXXXXXXXXXXXXXXXXXXXlH7%2F4e%2FutBRMG2y3QnmKgklNdqAMYWg95lyKTVd2fW5QGexpIJeFJjY%2F8ctjWj2HB3bfBuk4j43XL%2BIYBBbiFBkZlMH11wWN279JDb%2Fv5g4Pp5CHCf%2BSzUQ2ubUou6RiXRopS%2F&messageId=d-3B220528-B%2C26&apiKey=06f7f433408b4df592f6f46951e57410&tid=1&_=1542854622196
Line Number 1, Column 1:

**Comment by galli-leo** [comment]
This is already reported multiple times, and won‘t be fixed with the current UI.
