### ISSUE TITLE
Multi release not detected as english in custom formats

### ISSUE THREAD

**Issue by hbooo** [Radarr/Radarr#3203]
**Describe the bug**
Hi, 
I'm french and all my indexers have releases in french or multi with original language and french audio. My goal is to have 2 custom formats to cover both cases.

**To Reproduce**
I have set 2 custom formats like this
![image](https://user-images.githubusercontent.com/242125/48895614-caf4e000-ee45-11e8-9cf9-5441b9ff678f.png)
But I have this release
Megamind.2010.MULTi.WiTH.TRUEFRENCH.1080p.BluRay.x264-HOLiDAYS
that matches my FR custom format 
![image](https://user-images.githubusercontent.com/242125/48895759-26bf6900-ee46-11e8-88a0-edc93236a6e9.png)
I have set all my indexers with only 
![image](https://user-images.githubusercontent.com/242125/48895826-50789000-ee46-11e8-9aeb-7678af6e4296.png)
As I understand the custom format should not match since release contains MULTI and should be analysed as English?
**Expected behavior**
Multi term in a release should be considered as english 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Unraid
 - Version  :0.2.0.1217
 - Mono Version : 5.16.0.179 (tarball Thu Oct 4 10:29:10 UTC 2018)

**Debug Logs**

**Comment by galli-leo** [comment]
First of all, your FR format is wrong. You have to write the modifiers together like `L_NRQ_ENGLISH`

Second of all, the release seems to match fine according to your screenshots. Also the multi languages is not used for the testing area, as it is indexer specific.

**Comment by hbooo** [comment]
My mystake was on L_NRQ_ENGLISH, it works now,

Thanks for your time
