### ISSUE TITLE
Won't launch on MacOS

### ISSUE THREAD

**Issue by jgillman** [Radarr/Radarr#3206]
**Describe the bug**
The app will not launch. Turns out it was not executable.

**Desktop (please complete the following information):**
 - OS: MacOS Mojave (10.14)

**Debug Logs**
LSOpenURLsWithRole() failed with error -10810

**Additional context**
The only solution to the problem was to run `chmod +x /Applications/Radarr.app/Contents/MacOS/Radarr`

Exactly the same issue as Sonarr (https://github.com/Sonarr/Sonarr/issues/2818) which makes sense 😄

**Comment by galli-leo** [comment]
There is an issue already open for this. The main cause seems to be the zip client though. If you use the built-in zip utility of macOS, the permissions are assigned fine.

**Comment by formerandroider** [comment]
@galli-leo I've experienced this issue using only the build in macOS Archive Utility.
