### ISSUE TITLE
Move "The" to the end of Folder Titles

### ISSUE THREAD

**Issue by wkupike2000** [Radarr/Radarr#321]
Unless it's key word of the title which is pretty rare, leaving "The" at the start of movie folders makes sorting and finding movies very difficult. "The Angry Birds" shouldn't be in the T's but the A's. Examples are endless. All of my existing movies are correct but I'm noticing anything Radarr downloads leaves it at the start causing issues. 

Provide a description of the feature request or bug, the more details the better.
When possible include a log!

Please use our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by simonk83** [comment]
I'd prefer this as an option rather than a blanket change ;)

**Comment by wkupike2000** [comment]
Good thinking. :-)

**Comment by tymanthius** [comment]
Secondary option: leave 'the' off entirely for folder names.

**Comment by Elfman72** [comment]
Having this as an option would be great!

**Comment by Forbes256** [comment]
Excellent suggestion and much needed. I actually looked for this when setting the renamer up for the first time. Figured it would come in time. 👍🏻

**Comment by woble** [comment]
Similar request to #164

**Comment by PhAzE-Variance** [comment]
I'm actually mostly just waiting for this option before I move away from CP. This way I can keep my movies/folders in line with the rest of my collection.

**Comment by SX86** [comment]
I'm for this change too! It makes it look some much clean, and easier to browse your actual movies folder.

**Comment by wkupike2000** [comment]
This shows that it's been added in the latest release but I don't see it in the Settings and I'm updated to the latest?

**Comment by galli-leo** [comment]
@wkupike2000 Not shown in the settings, but you can use {Movie TitleThe}

**Comment by PhAzE-Variance** [comment]
Just to confirm, there is not a space between Title and The right?

**Comment by fedoranimus** [comment]
Correct. You can copy/paste what galli-leo wrote and it will work.

The next version should have this option available in the settings dropdown under Movie Title

**Comment by PhAzE-Variance** [comment]
Ok, thanks. I think the docker I'm using isn't up to date enough, which is the problem.

**Comment by fedoranimus** [comment]
#359 adds this functionality, closing.
