### ISSUE TITLE
Keep movie titles in English

### ISSUE THREAD

**Issue by gurabli** [Radarr/Radarr#3210]
I prefer dual audio releases, so I have qualitiy set to Hungarian. The problem is that Radarr changes movie names to Hungarian and grabs Hungarian description. Is it possible to change this, if yes, how? I would like to have all my movies in English (or original) title in databse. Thanks

**Comment by fryfrog** [comment]
There aren't a ton of multi-language users, but hop on Discord and ask there. You'll get a better response there, I think.
