### ISSUE TITLE
Discover New Movies -> Lists -> Showing only TMDb lists

### ISSUE THREAD

**Issue by Augeaz** [Radarr/Radarr#3211]
**Describe the bug**
Discover New Movies -> Lists -> Showing only TMDb lists

**To Reproduce**
1. Go to 'Discover New Movies'
2. Click on 'Lists'
4. See error -> Showing only TMDb lists

**Expected behavior**
To my understanding any lists added whether "StevenLu" or "Trakt List" should show as well.

**Screenshots**
Screenshots added.
![2018-11-24_21-06-59](https://user-images.githubusercontent.com/45319990/48973053-e111c480-f02e-11e8-86a6-0a43a4566a46.png)
![2018-11-24_21-14-43](https://user-images.githubusercontent.com/45319990/48973055-e40cb500-f02e-11e8-991a-4763f10a9321.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Mono Version: 5.10.1.57 (5.10.1.57 Thu Oct 25 02:40:45 UTC 2018)
 - Browser Chrome 70.0.3538.102 (Official Build) (64-bit)
 - Version Radarr 0.2.0.1217

**Debug Logs**
Turn on debug logs under Settings -> General and wait for the bug to occur again. **Upload the full log file here (or another site and link it). Issues will be closed, if they do not include this!**
[radarr.debug.txt.zip](https://github.com/Radarr/Radarr/files/2612601/radarr.debug.txt.zip)

**Comment by galli-leo** [comment]
This is intentional

**Comment by fabriziobertoglio1987** [comment]
https://github.com/Radarr/Radarr/issues/139
