### ISSUE TITLE
Error occurred while executing task RefreshMovie: Value cannot be null.

### ISSUE THREAD

**Issue by a92nj2efnfsa** [Radarr/Radarr#3212]
**Describe the bug**
Radarr Ver. 0.2.0.1217 - develop - can no longer add movies. Either new movies or importing movies from disk. Gives error: Error occurred while executing task RefreshMovie: Value cannot be null.
Parameter name: source

**To Reproduce**
Try to add any movie, either new or import. "RefreshFailed" error.

**Expected behavior**
Movie should be added.

**Desktop (please complete the following information):**
 - OS: Win7
 - Mono Version: N/A

**Debug Logs**
https://pastebin.com/Dy5JzLAf

**Comment by Cyborgmatt** [comment]
Having the same issue, just started today.

**Comment by TinTin192** [comment]
Yep. Me too :(

**Comment by Qstick** [comment]
This was due to a services or tmdb issue, looks to be fixed now
