### ISSUE TITLE
Add a Paused priority option for NzbGet

### ISSUE THREAD

**Issue by simonk83** [Radarr/Radarr#322]
Was just discussing this in chat.  Sab already has this option in Radarr, but it's missing for NzbGet.  Apparently Watcher has this as an option though so it must be possible.    

Is it OK to have this added?   I'd like to send everything to NzbGet paused for a while just while we test what Radarr is grabbing, and work on preferred/ignored words etc.  I have data caps so can't have 10GB files downloading willy nilly unfortunately :D

**Comment by vertigo235** [comment]
Here is the nzbget Api info, "AddPaused" = "True" in the append method. 

https://github.com/nzbget/nzbget/wiki/API-Method-%22append%22

**Comment by vertigo235** [comment]
I created a pull request to add the functionality.
