### ISSUE TITLE
Extras files not being hardlinked / imported into Radarr?

### ISSUE THREAD

**Issue by n1nj4888** [Radarr/Radarr#3225]
**Description:**
Extras files not being hardlinked / imported into Radarr...

Hi Guys,

I have the following setup:

(1) Radarr requests download from Deluge with a label “radarr”.
(2) Deluge recognises the label “radarr” and, at the end of the download moves the content to completed/radarr. The structure of the downloaded content is then say:

completed/radarr/MOVIE_FOLDER_NAME
- file.txt
- file.nfo
- MOVIE_FILE_NAME.ext
- Subs
   - sub.srt
   - sub.idx

(3) Although “Hard Link instead of Copy”, and “Import Extra Files” are set to on, with “srt,sub,idx,nfo,txt” set in “Extra File Extensions”, when Radarr actually hardlinks  the content from completed/radarr to say movies/MOVIE_FOLDER_NAME, it only has the following structure:

completed/radarr/MOVIE_FOLDER_NAME
- MOVIE_FILE_NAME.ext

Ie the only file hardlinked (and imported) is the movie file itself, no subs directories or any other files are hardlinked / imported?

**Radarr Version:**
0.2.0.1217

**Mono Version:**
5.16.0.179 (tarball Thu Oct 4 10:29:10 UTC 2018)

**Comment by HarryS** [comment]
Have the same issue. See also: https://github.com/Radarr/Radarr/issues/1958

**Comment by fryfrog** [comment]
Your post is better, but #1958 is older so I'm nuking this.
