### ISSUE TITLE
Import movies from Letterboxd watchlist

### ISSUE THREAD

**Issue by jeffbyrnes** [Radarr/Radarr#3228]
I’d love it if there was an integration to the (currently forthcoming) Letterboxd API for adding movies from a Letterboxd watchlist.

Letterboxd has an RSS feed of each user’s diary, but not their watchlist. Per #114 (specifically [this comment](
https://github.com/Radarr/Radarr/issues/114#issuecomment-274924784), scraping web pages is not desirable, so this is not a valid alternative.

* * * 

I’m submitting this merely as an issue to track the desired functionality. I’ve requested access to Letterboxd’s API beta, and, if they grant me access, I’ll see about building this feature myself!

**Comment by petekblaz** [comment]
This would be an awesome feature to have. +1

**Comment by screeny05** [comment]
Shameless plug: I've built a connector myself out of frustration.

https://www.reddit.com/r/radarr/comments/bta9x6/connect_letterboxdcom_to_your_radarrinstance/

**Comment by bakerboy448** [comment]
screeny provided a way to integrate this....closing

**Comment by azumukupoe** [comment]
> 
> 
> screeny provided a way to integrate this....closing

but it's not working right now...

**Comment by austinwbest** [comment]
It wouldn't be added without a functional api from letterboxd & from what I've read their api is beta & people who have been requesting api keys are not getting any response. So as it stands this is a no go. Feel free to try other ways or comment back if they get their act together with api keys.

**Comment by screeny05** [comment]
> but it's not working right now...
Check again. Has been updated
