### ISSUE TITLE
Use Nzb Name for {Original Title} renamer option rather than File Name

### ISSUE THREAD

**Issue by simonk83** [Radarr/Radarr#323]
Had a few movies download now with obfuscated filenames, so the resulting .mkv is named likewise.  This seems relatively common with file names, but I'm not sure I've ever seen a really badly named NZB file.   Does it make more sense to base {Original Title} on Nzb Name rather than File Name?

**Comment by judhat2** [comment]
related to https://github.com/Radarr/Radarr/issues/103#issuecomment-272718083
