### ISSUE TITLE
Add Radarr_Download_Id to 'On Grab' in custom scripts

### ISSUE THREAD

**Issue by unknown--** [Radarr/Radarr#3232]
I've noticed that Sonarr offers this environment variable in both 'On Grab' and 'On Download' but Radarr only offers it for 'On Download'.

Part of my script determines if the hard drive Transmission will be downloading to has enough space and if not it changes the path to another drive. To do this you need to have the torrent's internal ID or its hash. Having the hash provided in a variable from Radarr would be a better solution that those I've come up with as a workaround.

**Comment by lsnow2017** [comment]
Seconding this, I use this feature with Sonarr to uniquely identify a download to my post processing scripts for my downloaders. I can't do this in Radarr unless it provides this variable on 'On Grab'
