### ISSUE TITLE
Move entire download folder as is, no renaming/deletion of files

### ISSUE THREAD

**Issue by douglas24** [Radarr/Radarr#3238]
I may have missed some complex way to set this already, but could a feature be added for moving completed downloads that: 1) doesn't rename the folder or any files in the folder 2) moves the entire folder to the library destination?

This way the files can still be seeded later without needing duplication/wasted disk space.

**Comment by douglas24** [comment]
For instance a RARBG download will have a folder named Title.2008.1080p.BluRay.H264.AAC-RARBG and the movie files/extra files are within that folder. I'd like to be able to move that folder (without renaming it) along with all the files in it (without renaming/deleting them) to my radarr destination folder. In short, I'd like everything in and including the downloaded folder to be moved without renaming anything.

As far as I know, radarr can't do that yet?

**Comment by fryfrog** [comment]
This isn't something Radarr does and I doubt it ever will.

Setup your file system so that hard links will work, the large movie file will not use up extra space. The extra cruft w/ the torrent can stay where it was downloaded.
