### ISSUE TITLE
Unknown Movie when parsing file downloaded by radarr

### ISSUE THREAD

**Issue by Arcanaeum** [Radarr/Radarr#3240]
Hello,

I added a movie (Fellowship of the ring) to my library and radarr searched my indexers and downloaded a release. However it refuses to import the release giving the following logs:

```
18-12-9 07:49:43.0|Debug|Parser|Parsing string 'The.Fellowship.of.the.Ring.2001.PROPER.Extended.1080p.BluRay.DTS-ES.x264-HiDt'
18-12-9 07:49:43.0|Debug|Parser|Movie Parsed. The Fellowship of the Ring - 2001 
18-12-9 07:49:43.0|Debug|DownloadedMovieImportService|Unknown Movie The.Fellowship.of.the.Ring.2001.PROPER.Extended.1080p.BluRay.DTS-ES.x264-HiDt
```

Is the filename somehow malformed? Why can it not be matched?

**Comment by galli-leo** [comment]
Please fill out the issue template fully.
