### ISSUE TITLE
Feature Request: Organize Current/Completed Database

### ISSUE THREAD

**Issue by Th3MadHatter** [Radarr/Radarr#3242]
**Is your feature request related to a problem? Please describe.**
I just noticed my renamer was turned off half way tweaking the settings and now it started to organize everything neatly with a lot of info I don't want in the end title/nfo title.
I'm sure this could be useful is someone decides to changes file names because a specific device doesn't support his current file name structure or they just decided they want year behind it as well, just to give a few examples
I went through every option I could find but I couldn't find one that lets me rename my current files anywhere! 

**Describe the solution you'd like**
Add a task or option to "Organize Database", since it is used automatically with new grabs, a simple task in the task scheduler or option that pops up once you changed the structure would be more then enough

**Describe alternatives you've considered**
Doing it by hand and throwing my screen out of the window half way through lol

**Additional context**
None, (would be nice to have that for auto unmonitor things that are done too but I drift off topic). :+1:

**Comment by arkayenro** [comment]
try this

movies > movie editor > view all (the circle icon) > select all (the tick box, not the button) > organize > organize (scroll to the bottom)
