### ISSUE TITLE
Only execute clean library on downloaded / cutoff met movies.

### ISSUE THREAD

**Issue by rkmfl** [Radarr/Radarr#3244]
**Describe the bug**
There is a new problem in Radarr that appears to have started in version 0.2.0.1217, possibly as a result of attempting to fix another issue (#2584). 

The #2584  fixed a problem where movies would get _**re**-downloaded_ if it had already been downloaded then appeared again in a monitored _"List"_ (eg TMDB, IMDB, Trakt Top Movie lists, etc).

When that fix was implemented, there was another strange functionality added where movies that are **missing from "lists"** become **unmonitored**.

This is the _exact opposite_ functionality intended.

Note:  This is based on using the setting _Keep but unmonitor_ for lists.  (If you choose to delete, perhaps the movies would be deleted as well -- I haven't tested this)

**To Reproduce**
1. Settings > Lists > Options > Clean Library Level > "Keep but unmonitor"
2. Allow a "List" to add a movie as "Monitored"
3. When that movie falls-off the list, _even if it has not been downloaded_, Radarr will set as "Not Monitored".

This is an error.  Movies falling-off a list should never cause the movie to be unmonitored.  It's the movie being _downloaded_ that causes it to be _unmonitored_.

_For example:_ some lists are "In Theaters", movies fall-off the list _long before_ they are available for download, in most casts.  

Lists are used to add movies, not to remove them.  There is no benefit to removing movies that are no longer included in lists.  If this was a desired feature, it would have to be enabled separately as it would serve an extremely rare interest, because this is not how people use lists.

_IMPORTANT NOTE:_ The fix to #2584 worked by removing movies that have _already_ been downloaded but later _re-appears_.  In other words:  A movie has been downloaded, then re-appears on a list, and it was downloaded again.  That was an error that has been fixed.

**Expected behavior**
When falling-off a list, nothing at all should happen.  The entire event/functionality should be removed.

**Version**
Radarr version 0.2.0.1217

**Log File Example**
 18-12-7 06:36:52.8|Info|NetImportSearchService|[Aquaman (2018)][tt1477834, 297802] was **in your library**, but **not found in your lists** --> Keeping in library but **Unmonitoring** it

**Comment by galli-leo** [comment]
This is the intended functionality of the setting. As soon as a movie falls of all of your lists, the action specified by the setting you mentioned is triggered. If you do not want that functionality, you have to select None for that option.

**Comment by rkmfl** [comment]
@galli-leo Thank you, I understand.  I was under a different impression from the implementation in prior versions of Radarr.  

You may recall that you recommended switching to "Keep but unmonitor" to prevent files from re-downloading, a problem with an earlier release.

It made more sense that **"library cleaning" was related to movies that had been downloaded** (versus movies that fall off lists).

In other words, it's intuitive to think that people might want the option to _unmonitor movies_ once they are downloaded -- but it's not anywhere near as valuable to unmonitor movies when they are no longer on monitored lists.

After all, if something shows in your custom-configured list, it qualified as something you wanted -- and there would be no reason to remove it once it was no longer the top movie of the week, etc.  Rather, it would make sense to remove it once it had been downloaded.

In other words -- although it's my misunderstanding, wouldn't it make more sense to **"clean library"** once downloaded -- _or_ offer that as one of the options rather than pruning the library once no longer the day's top movie, etc?

Thanks again!

**Comment by galli-leo** [comment]
@rkmfl Well the original idea behind clean library was that you could synchronize your Radarr library with other online sources, e.g. your IMDB watchlist, not necessarily download all popular movies from IMDb. Hence you would want to delete / unmonitor a movie from Radarr even if it wasn‘t yet downloaded. I think you could just use a custom script to fix your issue for now. In other words, just unmonitor the movie on download using an API call, but I can reopen as a feature request to only „execute“ clean library for already downloaded / cutoff met movies.

**Comment by bakerboy448** [comment]
Closing
v0.2 is no longer being actively developed.

If this is still an issue/request on recent v3 builds, please open a new issue.
