### ISSUE TITLE
Feature Request: Upgrade Custom Formats in Wanted

### ISSUE THREAD

**Issue by Chudz** [Radarr/Radarr#3246]
I would like to upgrade existing media through the "Wanted > Cutoff Unmet" using the new Custom Formats. I can do a manually search and the upgrade shows up there and I think they upgrade via RSS also but not a "Wanted > Cutoff Unmet" search.

Maybe add a new tab to the Wanted section for "Cutoff Unmet - Custom Formats"

**Comment by xombiemp** [comment]
+1
A movie should appear in the Cutoff Unmet tab if it's Custom Formats cutoff is not met.

**Comment by Maximus97** [comment]
Agree with xombiemp

**Comment by valatave** [comment]
+1 This is exactly what i'm waiting for!

**Comment by Brando47** [comment]
chiming in with a +1

**Comment by mikerozwadowski** [comment]
+1 exactly what I’m looking for

**Comment by ta264** [comment]
Now custom formats are dynamically calculated in Aphrodite (which brings many benefits) this is unfortunately now going to be possible since it'll be too slow
