### ISSUE TITLE
Movie names containing an apostrophe in magnet links not properly escaped when sent to transmission

### ISSUE THREAD

**Issue by bubske4** [Radarr/Radarr#3256]
**Describe the bug**
Movie names containing an apostrophe in magnet links not properly escaped when sent to Transmission. Not sure if Radarr related or indexer related.

**To Reproduce**
1. Setup Radarr with Transmission as download client
2. Download a suitable release for a title that contains an apostrophe
3. Get error

**Expected behavior**
Expected the magnet link to be properly encoded and accepted by Transmission. Special characters (`'`) in link are html-encoded (`&#309;`) instead of URL encoded (`%27`).

`magnet:?xt=urn:btih:redacted&dn=REDACTED TITLE WITH APOSTROPHE BETWEEN HERE &#039; AND HERE&tr=redacted`

**Desktop (please complete the following information):**
 - OS: docker image (linuxserver/radarr) on linux
 - Mono Version: 5.16.0.220 (tarball Mon Nov 26 17:22:46 UTC 2018)
 - Version 0.2.0.1217 ~develop

**Debug Logs**
`Failed to parse magnetlink for movie 'REDACTED TITLE WITH APOSTROPHE BETWEEN HERE 'AND HERE': 'magnet:?xt=urn:btih:redacted&dn=REDACTED TITLE WITH APOSTROPHE BETWEEN HERE &#039;AND HERE&tr=redacted': A field-value pair of the magnet link contain more than one equal'.`

`System.FormatException: A field-value pair of the magnet link contain more than one equal'.
  at MonoTorrent.MagnetLink.ParseMagnetLink (System.String url) [0x002b0] in C:\projects\radarr-usby1\src\MonoTorrent\MagnetLink.cs:93 
  at MonoTorrent.MagnetLink..ctor (System.String url) [0x00022] in C:\projects\radarr-usby1\src\MonoTorrent\MagnetLink.cs:32 
  at NzbDrone.Core.Download.TorrentClientBase 1[TSettings].DownloadFromMagnetUrl (NzbDrone.Core.Parser.Model.RemoteMovie remoteMovie, System.String magnetUrl) [0x00004] in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\TorrentClientBase.cs:203`

**Comment by galli-leo** [comment]
What indexer are you using? Does this occur on every indexer? Can you please post the full debug log files?

From scanning the code, it seems like your indexer is wrongly encoding this.

**Comment by matthewaaronthacker** [comment]
This was closed as stale, but I've found another instance of this issue. I thought maybe it was an issue with Transmission, but if I copy and paste the link directly from a Jackett search, transmission accepts it just fine. I took the link out of the error and the link directly from Jackett and compared them in a text editor and they are identical, so I suspect there is some issue in the way Radarr is sending the link to Transmission.

Full text of the error:
Failed to parse magnetlink for movie 'A Knight's Tale 2001 1080p Bluray x265 10Bit AAC 5.1 - GetSchwift...': 'magnet:?xt=urn:btih:08B8F1BBB2DCFB01FDAB16C9F417B497596682AF&dn=A Knight&#039;s Tale 2001 1080p Bluray x265 10Bit AAC 5.1 - GetSchwifty&tr=udp://tracker.coppersurfer.tk:6969/announce&tr=udp://tracker.opentrackr.org:1337/announce&tr=udp://tracker.torrent.eu.org:451/announce&tr=http://tracker.tfile.me:80/announce&tr=http://t.nyaatracker.com:80/announce&tr=http://retracker.mgts.by:80/announce&tr=http://tracker.yoshi210.com:6969/announce&tr=udp://tracker.zer0day.to:1337/announce&tr=udp://tracker.leechers-paradise.org:6969/announce&tr=udp://coppersurfer.tk:6969/announce': A field-value pair of the magnet link contain more than one equal'.

Magnet link as reported by Jackett:
magnet:?xt=urn:btih:08B8F1BBB2DCFB01FDAB16C9F417B497596682AF&dn=A Knight&#039;s Tale 2001 1080p Bluray x265 10Bit AAC 5.1 - GetSchwifty&tr=udp://tracker.coppersurfer.tk:6969/announce&tr=udp://tracker.opentrackr.org:1337/announce&tr=udp://tracker.torrent.eu.org:451/announce&tr=http://tracker.tfile.me:80/announce&tr=http://t.nyaatracker.com:80/announce&tr=http://retracker.mgts.by:80/announce&tr=http://tracker.yoshi210.com:6969/announce&tr=udp://tracker.zer0day.to:1337/announce&tr=udp://tracker.leechers-paradise.org:6969/announce&tr=udp://coppersurfer.tk:6969/announce

**Comment by GunbleR** [comment]
Happened to me today and couple of months ago.
Radarr failed to grab movies:  Charlie's angels, Fast & Furious.
Only happens when using jackett. when grabbing from indexer directly everything works fine.

logs:
```
20-2-16 23:55:01.2|Error|Transmission|Failed to parse magnetlink for movie 'Charlie's Angels (2019) [1080p] [WEBRip] [5.1] [YTS] [YIFY]': 'magnet:?xt=urn:btih:650958899666E87108B7ABC1061210EB7612959D&dn=Charlie&#039;s+Angels+(2019)+[1080p]+[WEBRip]+[5.1]+[YTS]+[YIFY]&tr=udp://tracker.coppersurfer.tk:6969/announce&tr=udp://9.rarbg.com:2710/announce&tr=udp://p4p.arenabg.com:1337&tr=udp://tracker.internetwarriors.net:1337&tr=udp://tracker.opentrackr.org:1337/announce&tr=udp://tracker.zer0day.to:1337/announce&tr=udp://tracker.leechers-paradise.org:6969/announce&tr=udp://coppersurfer.tk:6969/announce': A field-value pair of the magnet link contain more than one equal'.

[v0.2.0.1450] System.FormatException: A field-value pair of the magnet link contain more than one equal'.
  at MonoTorrent.MagnetLink.ParseMagnetLink (System.String url) [0x00071] in <c2fb3d347dd84ecfbde623dbf08022ab>:0 
  at MonoTorrent.MagnetLink..ctor (System.String url) [0x00022] in <c2fb3d347dd84ecfbde623dbf08022ab>:0 
  at NzbDrone.Core.Download.TorrentClientBase`1[TSettings].DownloadFromMagnetUrl (NzbDrone.Core.Parser.Model.RemoteMovie remoteMovie, System.String magnetUrl) [0x00004] in <c4a0b0b5f87743f0b17e9fc8429ff92c>:0 

20-2-16 23:55:01.2|Info|DownloadService|Report sent to Freenas TR. Charlie's Angels (2019) [720p] [WEBRip] [YTS] [YIFY]

```

Version
    0.2.0.1450
Mono Version
    5.10.1.57

**Comment by esfomeado** [comment]
This problem still exists in the latest version.

**Comment by leha007** [comment]
Issues still exist:
**Message**
{Failed to parse magnetlink for release 'Arctic Monkeys - Tranquility Base Hotel & Casino (2018) Mp3 (320 kbps) [Hunter]': 'magnet:?xt=urn:btih:5AC3D859E9F6A9DAF341D48A58FD96D963359A5A&dn=Arctic+Monkeys+-+Tranquility+Base+Hotel+&amp;+Casino+(2018)+Mp3+(320+kbps)+[Hunter]&tr=udp://tracker.coppersurfer.tk:6969/announce&tr=udp://tracker.pirateparty.gr:6969/announce&tr=udp://tracker.leechers-paradise.org:6969/announce&tr=udp://public.popcorn-tracker.org:6969/announce&tr=udp://tracker.zer0day.to:1337/announce&tr=udp://tracker.opentrackr.org:1337/announce&tr=udp://eddie4.nl:6969/announce&tr=udp://eddie4.nl:6969/announce&tr=udp://tracker.cypherpunks.ru:6969/announce&tr=udp://inferno.demonoid.pw:3418/announce&tr=udp://thetracker.org:80/announce&tr=udp://thetracker.org:80/announce&tr=udp://9.rarbg.com:2710/announce&tr=udp://pubt.in:2710/announce&tr=udp://tracker.zer0day.to:1337/announce&tr=udp://tracker.leechers-paradise.org:6969/announce&tr=udp://coppersurfer.tk:6969/announce': A field-value pair of the magnet link contain more than one equal'.}

**Exception**
System.FormatException: A field-value pair of the magnet link contain more than one equal'.
  at MonoTorrent.MagnetLink.ParseMagnetLink (System.String url) [0x00071] in <d9801d666ea44c6ba32bf744d2df7bc4>:0 
  at MonoTorrent.MagnetLink..ctor (System.String url) [0x00022] in <d9801d666ea44c6ba32bf744d2df7bc4>:0 
  at NzbDrone.Core.Download.TorrentClientBase`1[TSettings].DownloadFromMagnetUrl (NzbDrone.Core.Parser.Model.RemoteAlbum remoteAlbum, System.String magnetUrl) [0x00004] in <f339569e234a4fc1add8b9dab7a33d21>:0 

Using Lidarr (I know it's radarr repo but still feels the same problem)
Using latest Jackett - {Linuxserver.io version:- v0.13.625-ls56 Build-date:- 2020-03-12T06:14:51+00:00}

**Comment by Jeff254** [comment]
Anyone find a solution The problem still exists. Tried downloading Molly's Game and I get failed to parse magnet link error

**Comment by juhenriquez** [comment]
Same Issue Here, 

Failed to parse magnetlink for episode 'Greys Anatomy S16E03 (1080p AMZN WEB-DL x265 HEVC 10bit AC3 5.1 Qman) [UTR]': 'magnet:?xt=urn:btih:A5071876B564C40E97F0397E2070FC767254D804&dn=Grey&#039;s+Anatomy+S16E03+(1080p+AMZN+WEB-DL+x265+HEVC+10bit+AC3+5.1+Qman)+[UTR]&tr=udp://9.rarbg.com:2710/announce&tr=udp://tracker.opentrackr.org:1337/announce&tr=udp://tracker.torrent.eu.org:451/announce&tr=udp://tracker.leechers-paradise.org:6969/announce&tr=udp://tracker.coppersurfer.tk:6969/announce&tr=udp://tracker.zer0day.to:1337/announce&tr=udp://tracker.leechers-paradise.org:6969/announce&tr=udp://coppersurfer.tk:6969/announce': A field-value pair of the magnet link contain more than one equal'.

Exception
System.FormatException: A field-value pair of the magnet link contain more than one equal'.
  at MonoTorrent.MagnetLink.ParseMagnetLink (System.String url) [0x00071] in <d901b6c0bcc94442a130658e78fd88a4>:0 
  at MonoTorrent.MagnetLink..ctor (System.String url) [0x00022] in <d901b6c0bcc94442a130658e78fd88a4>:0 
  at NzbDrone.Core.Download.TorrentClientBase`1[TSettings].DownloadFromMagnetUrl (NzbDrone.Core.Parser.Mode

**Comment by pkishino** [comment]
Same as above
```
Failed to parse magnetlink for movie 'The Emperor's New Groove (2000) 1080p BrRip x264 - YIFY': 'magnet:?xt=urn:btih:1AFD05429FAFAE920FFC947961601FF66D1FF73F&dn=The+Emperor&#039;s+New+Groove+(2000)+1080p+BrRip+x264+-+YIFY&tr=udp://tracker.yify-torrents.com/announce&tr=udp://open.demonii.com:1337&tr=udp://exodus.desync.com:6969&tr=udp://tracker.istole.it:80&tr=udp://tracker.publicbt.com:80&tr=udp://tracker.openbittorrent.com:80&tr=udp://tracker.leechers-paradise.org:6969&tr=udp://9.rarbg.com:2710&tr=udp://p4p.arenabg.ch:1337&tr=udp://p4p.arenabg.com:1337&tr=udp://tracker.coppersurfer.tk:6969&tr=udp://tracker.zer0day.to:1337/announce&tr=udp://tracker.leechers-paradise.org:6969/announce&tr=udp://coppersurfer.tk:6969/announce': A field-value pair of the magnet link contain more than one equal'.

```

**Comment by algha4** [comment]
Another example. Please correct:
12.04.2020 23:13:10[Error] Deluge: Failed to parse magnetlink for movie 'A Dog s Journey 2019 WEBRip 1080p YTS YIFY': 'magnet:?xt=urn:btih:3D51E290D1FEDC02F9B66C1C6846DEAE2779A131&dn=A+Dog&#039;s+Journey+(2019)+[WEBRip]+[1080p]+[YTS]+[YIFY]&tr=udp://tracker.coppersurfer.tk:6969/announce&tr=udp://9.rarbg.com:2710/announce&tr=udp://p4p.arenabg.com:1337&tr=udp://tracker.internetwarriors.net:1337&tr=udp://tracker.opentrackr.org:1337/announce&tr=udp://tracker.zer0day.to:1337/announce&tr=udp://tracker.leechers-paradise.org:6969/announce&tr=udp://coppersurfer.tk:6969/announce'
12.04.2020 23:13:10
12.04.2020 23:13:10[v0.2.0.1450] System.FormatException: A field-value pair of the magnet link contain more than one equal'.
12.04.2020 23:13:10  at MonoTorrent.MagnetLink.ParseMagnetLink (System.String url) [0x002b0] in C:\projects\radarr-usby1\src\MonoTorrent\MagnetLink.cs:93
12.04.2020 23:13:10  at MonoTorrent.MagnetLink..ctor (System.String url) [0x00022] in C:\projects\radarr-usby1\src\MonoTorrent\MagnetLink.cs:32
12.04.2020 23:13:10  at NzbDrone.Core.Download.TorrentClientBase`1[TSettings].DownloadFromMagnetUrl (NzbDrone.Core.Parser.Model.RemoteMovie remoteMovie, System.String magnetUrl) [0x00004] in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\TorrentClientBase.cs:203

**Comment by Telandriq** [comment]
Same issue with Howl's moving castle

Failed to parse magnetlink for movie 'Howl s Moving Castle 2004 BluRay 1080p YTS YIFY': 'magnet:?xt=urn:btih:7C7A5296A370A5D8067C712DA5146BF5A868E846&dn=Howl&#039;s+Moving+Castle+(2004)+[BluRay]+[1080p]+[YTS]+[YIFY]&tr=udp://tracker.coppersurfer.tk:6969/announce&tr=udp://9.rarbg.com:2710/announce&tr=udp://p4p.arenabg.com:1337&tr=udp://tracker.leechers-paradise.org:6969&tr=udp://tracker.internetwarriors.net:1337&tr=udp://tracker.opentrackr.org:1337/announce&tr=udp://tracker.zer0day.to:1337/announce&tr=udp://tracker.leechers-paradise.org:6969/announce&tr=udp://coppersurfer.tk:6969/announce': A field-value pair of the magnet link contain more than one equal'.



System.FormatException: A field-value pair of the magnet link contain more than one equal'.
   at MonoTorrent.MagnetLink.ParseMagnetLink(String url) in C:\projects\radarr-usby1\src\MonoTorrent\MagnetLink.cs:line 50
   at MonoTorrent.MagnetLink..ctor(String url) in C:\projects\radarr-usby1\src\MonoTorrent\MagnetLink.cs:line 32
   at NzbDrone.Core.Download.TorrentClientBase`1.DownloadFromMagnetUrl(RemoteMovie remoteMovie, String magnetUrl) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\TorrentClientBase.cs:line 203

**Comment by pkishino** [comment]
Please reopen this issue..

**Comment by ImMaury** [comment]
I'm also experiencing this issue. This is especially problematic with trackers that only with magnetic links, such as 1337x, which makes them nearly useless. Hasn't anybody found a workaround yet?

**Comment by EmilioRivera** [comment]
As stated, the issue is simply because the magnet links provided by some trackers contain some HTML encoded values instead of URI encoded, when the magnet links reaches Radarr, the magnetURL contains sequences like `&#039;` or other similarly escaped values that are displayed only correctly when in HTML. If you copy the magnet link directly and paste it into the client, eg: Transmission, it seems to work out fine.

I've changed a few lines to HTML decode if the parsing fails and it seems to be working out correctly so far for all titles that have this problem.

File `src/NzbDrone.Core/Download/TorrentClientBase.cs`:
```
private string DownloadFromMagnetUrl(RemoteMovie remoteMovie, string magnetUrl)
        {
            string hash = null;
            string actualHash = null;
            string htmlDecodedMagnetUrl = null;

            try
            {
                hash = new MagnetLink(magnetUrl).InfoHash.ToHex();
            }
            catch (FormatException ex)
            {
                _logger.Error(ex, "Failed to parse magnetlink for movie '{0}': '{1}'", remoteMovie.Release.Title, magnetUrl);
                _logger.Error("Trying experimental parser for magnet url '{0}'", magnetUrl);
                try
                {
                    htmlDecodedMagnetUrl = ExperimentalUrlDecode(magnetUrl);
                    hash = new MagnetLink(htmlDecodedMagnetUrl).InfoHash.ToHex();
                }
                catch (FormatException fex)
                {
                    _logger.Error(fex, "Experimental parser yielded unparseable string for '{0}': '{1}'", magnetUrl, htmlDecodedMagnetUrl);
                    return null;
                }
            }

            if (hash != null)
            {
                actualHash = AddFromMagnetLink(remoteMovie, hash, htmlDecodedMagnetUrl ?? magnetUrl);
            }

            if (actualHash.IsNotNullOrWhiteSpace() && hash != actualHash)
            {
                _logger.Debug(
                    "{0} did not return the expected InfoHash for '{1}', Radarr could potentially lose track of the download in progress.",
                    Definition.Implementation, remoteMovie.Release.DownloadUrl);
            }

            return actualHash;
        }

        private string ExperimentalUrlDecode(string potentiallyMalformedUrl)
        {
            // TODO: Check if we should replace the string

            // Hack: Decode HTML encoded urls
            // or: .Replace("&#039;", "'");
            return WebUtility.HtmlDecode(potentiallyMalformedUrl);
        }
    }
```

This code obviously only tries to HTMLDecode if the original pasing failed; I'm reticent to HTMLDecode right off the bat, at it seems to be an error that magnet links are incorrectly encoded. Also, I'm not sure if it would be better just to replace problematic tokens, such as apostrophes. Not sure whether this should be an option in the settings or just to leave it like that.

**Comment by pkishino** [comment]
That looks good as a WA..could propose it as a PR?
