### ISSUE TITLE
Add UHD BR-DISK quality

### ISSUE THREAD

**Issue by lps-rocks** [Radarr/Radarr#3257]
**Is your feature request related to a problem? Please describe.**
Currently Radarr does not differentiate between UHD BR-DISK and 1080p BR-DISK. Being able to differentiate would be beneficial. 

**Describe the solution you'd like**
Add 4K (UHD) BD-DISK quality

**Describe alternatives you've considered**
Custom Formats - However, it makes more sense to make it a main feature.

**Comment by galli-leo** [comment]
We have talked about this and came to the conclusion that custom formats would be the preferred way to go.

IMO a BR-DISK quality indicates that it's a 1:1 copy of the bluray disc and hence the quality is kinda irrelevant. You get the quality that's on the bluray disc. Therefore, I don't think it makes much sense to split it up into multiple qualities. If you really want to automate getting the best BR-DISK (i.e. if there are multiple available), you can use custom formats.

**Comment by lps-rocks** [comment]
I understand the reasoning for a BR-DISK quality being a 1:1 mapping - However my thought process was more and more movies are released in multiple versions that have very different qualities (and codecs). UHD Bluray is a completely different quality from 1080p BluRay. 

It does look like the project's long term goal is to stop using hard-coded Qualities and instead allow the user to define them since there's so many out there. So it makes sense to go that way.

Thanks for the consideration! Much appreciated.
