### ISSUE TITLE
Remove “obfuscated” from release group

### ISSUE THREAD

**Issue by anotb** [Radarr/Radarr#3262]
Radarr is adding “obfuscated” as the release group whenever the file name from nzb contains the word obfuscated at the end. Could that functionality be modified to excluded the word obfuscated from the regex so the proper release group is tagged? 

(Develop branch)

**Comment by galli-leo** [comment]
Can you post an example? The test case we have still passes.

**Comment by Qstick** [comment]
Obfuscated is in the cleanReleaseGroup regex, so it should be cleaned prior to release group being parsed, agree we need a sample release this is happening on

**Comment by StabbyPancake** [comment]
@galli-leo @Qstick here are my latest from today, to add to what I posted yesterday:

A.Star.is.Born.2018.720p.BluRay.x264.1.DD5.1-Manning-Obfuscated
becomes
A Star Is Born (2018).BLURAY-720P.AC3.5.1.X264-OBFUSCATED

Revenge.of.the.Sith.2005.720p.BRRip.XviD.AC3-FLAWL3SS-Obfuscated
becomes
Star Wars Episode III - Revenge of the Sith (2005).DVD.AC3.5.1.XVID-OBFUSCATED

**Comment by StabbyPancake** [comment]
Further down the rabbit hole if you need more examples:

The.Sisters.Brothers.2018.1080p.BluRay.x264.1-MkvCage-Obfuscated
The.Phantom.Menace.1999.720p.BRRip.XviD.AC3-FLAWL3SS-Obfuscated
Star.Wars.Episode.VI.The.Return.of.the.Jedi.1983.Despecialized.Edition.720p.BRRiP.XViD.AC3-LEGi0N-Obfuscated

**Comment by Chudz** [comment]
Here are some other words which could do with removing if  possible:

-4P
-Scrambled
-RP
-SirUppington
-AsRequested
-WhiteRev
-postbot

Or maybe a new feature that allows us to remove specific words from renaming?

**Comment by Qstick** [comment]
@galli-leo the issue here is that on import it Radarr uses `simpleReleaseTitle` to try and parse the Release Group instead of using the release title. Because `simpleReleaseTitle` is the `release title / filename` ex. `Jurassic.World.2015.720p.BluRay.x265-NtB-Obfuscated QaQV3WK3z2mUI0YY19xcP1VKqN` the regex fails to clean as it looks for keyword (Obfuscated/pre/et..) at end of string. 

To fix we likely need to use the original release title and not the simple release title for parsing of release group. Agree?

**Comment by StabbyPancake** [comment]
-BUYMORE is another one that I haven't seen mentioned

**Comment by Chudz** [comment]
I ran this when inside my Movies folder to rename all files in the folder and sub-folders. I am a n00b though so test it first or just dont use it! it might blow your server up or something but it worked for me.

`find . -iname "*postbot*" -exec rename s/"-postbot.mkv"/".mkv"/g '{}' \; && \
find . -iname "*ObfuscatedPostBot*" -exec rename s/"-ObfuscatedPostBot.mkv"/".mkv"/g '{}' \; && \
find . -iname "*Obfuscated*" -exec rename s/"-Obfuscated.mkv"/".mkv"/g '{}' \; && \
find . -iname "*obfuscated*" -exec rename s/"-obfuscated.mkv"/".mkv"/g '{}' \; && \
find . -iname "*Scrambled*" -exec rename s/"-Scrambled.mkv"/".mkv"/g '{}' \; && \
find . -iname "*RP*" -exec rename s/"-RP.mkv"/".mkv"/g '{}' \; && \
find . -iname "*SirUppington*" -exec rename s/"-SirUppington.mkv"/".mkv"/g '{}' \; && \
find . -iname "*AsRequested*" -exec rename s/"-AsRequested.mkv"/".mkv"/g '{}' \; && \
find . -iname "*Chamele0n*" -exec rename s/"-Chamele0n.mkv"/".mkv"/g '{}' \; && \
find . -iname "*WhiteRev*" -exec rename s/"-WhiteRev.mkv"/".mkv"/g '{}' \; && \
find . -iname "*Rakuvfinhel*" -exec rename s/"-Rakuvfinhel.mkv"/".mkv"/g '{}' \; && \
find . -iname "*RakuvFIN*" -exec rename s/"-RakuvFIN.mkv"/".mkv"/g '{}' \; && \
find . -iname "*RakuvDE*" -exec rename s/"-RakuvDE.mkv"/".mkv"/g '{}' \; && \
find . -iname "*Rakuv01*" -exec rename s/"-Rakuv01.mkv"/".mkv"/g '{}' \; && \
find . -iname "*Rakuv*" -exec rename s/"-Rakuv.mkv"/".mkv"/g '{}' \; && \
find . -iname "*4P*" -exec rename s/"-4P.mkv"/".mkv"/g '{}' \;
find . -iname "*BUYMORE*" -exec rename s/"-BUYMORE.mkv"/".mkv"/g '{}' \;`

**Comment by StabbyPancake** [comment]
This is still an issue, running v0.2.0.1293

**Comment by corwinx** [comment]
This is still happening, currently running radarr v0.2.0.1358

Movie naming string: {Movie Title} ({Release Year}) - {[EDITION TAGS]}{[QUALITY FULL]}{[MEDIAINFO AUDIOCODEC}{ MEDIAINFO AUDIOCHANNELS]}{[MEDIAINFO VIDEOCODEC]}{-RELEASE GROUP}

Example:
Hellboy.2019.720p.WEB-DL.AC-3.H.264-CMRG-Obfuscated
becomes...
Hellboy (2019) - [WEBDL-720P][AC3 2.0][H264]-OBFUSCATED

**Comment by simbasamba** [comment]
Any update on this? Still happening on  0.2.0.1480

**Comment by Qstick** [comment]
Not getting fixed in v0.2.... test on V3 if it's a deal breaker and report back

**Comment by StabbyPancake** [comment]
If you are using SABnzbd or nzbget, you can fix this yourself by running a pre-queue script:  https://forums.sabnzbd.org/viewtopic.php?f=2&t=24748
