### ISSUE TITLE
Gate file deletion in clean library level behind warning and/or recycle bin requirement

### ISSUE THREAD

**Issue by fryfrog** [Radarr/Radarr#3267]
The Clean Library Level in Settings -> Lists -> Options is setup in such a way that it would be *very* easy to entirely nuke your library. The delete files option should at *least* be gated behind a warning, possibly even a requirement that recycle bin be enabled.

https://i.imgur.com/vtowZCm.png

From this reddit thread: https://old.reddit.com/r/radarr/comments/aa2dzi/radarr_started_randomly_downloading_extended/ecof0l3/

**Comment by RhinoRhys** [comment]
The interface is fairly clear that this setting should only be enabled if you are certain you know what you are doing. If you hover over the yellow warning triangle next to this setting it warns you "Disable unless you are sure. Enabling Recycling bin before this is reccomended". Also hovering over the regular help question mark informs you exactly what will happen, "Movies in library will be removed or unmonitored if not found in your lists." And then having to manually pick the option "remove & delete files" should give you a hint as to what is going to happen. I agree maybe an "are you sure you know what you are turning on" dialogue could be useful to idiot-proof it but requiring that Recycle bin is enabled entirely ruins the point of lists and automation and would require I go in and manually empty the recycle bin. If people can't be bothered to read the help bubbles located next to a setting, especially one with a warning triangle, and are just changing settings haphazardly they need to learn the hard way. They'll only do it once.
