### ISSUE TITLE
Can't bulk update movies when there are a large numbers of movies in library

### ISSUE THREAD

**Issue by cbulock** [Radarr/Radarr#3269]
**Describe the bug**
When there are a large number of movies, using "Select All" in the movie editor doesn't allow saving.  I'm trying to update 775 movies at once.  The PUT request to `/api/movie/editor` returns a 413 response `Request Entity Too Large`.

**To Reproduce**
1. Go to Movies page, click "Movie Editor"
2. Click "Select All" and update the profile.
3. Click "Save"

**Expected behavior**
A message should appears saying "Done saving" and the profiles should be updated.

**Desktop (please complete the following information):**
 - OS: Ubuntu 17.10
 - Mono Version: 5.16.0.220
 - Browser and Version: Chrome 71

**Debug Logs**
Turned on debug logs, but nothing is logged when this occurs

**Comment by galli-leo** [comment]
This is very likely due to using a reverse proxy that sets that limitation. AFAIK Radarr doesn’t have that.
