### ISSUE TITLE
Quality Definitions need adjusted file size limits

### ISSUE THREAD

**Issue by emko** [Radarr/Radarr#327]
for example Bluray-1080p is set to Unlimited file size and the highest you can set it to is 12GB, so i ended up with a few remux 30-40gb movies. We need to be able to adjust these values past 12GB and also i think we need another Bluray-1080p profile for people who do want the full rips.

**Comment by simonk83** [comment]
Definitely need to come up with some good defaults for all categories

**Comment by theotherp** [comment]
Kind of a duplicate of #110

**Comment by onedr0p** [comment]
It is a duplicate :)
