### ISSUE TITLE
API PUT does not persist data for .movieFile.quality.quality

### ISSUE THREAD

**Issue by obelisk3847** [Radarr/Radarr#3270]
**Describe the bug**

Similar issue to [Movie API does not persist Quality updates](https://github.com/Radarr/Radarr/issues/2675) although I am setting more than just the quality and only the quality is not persisting.

I have a couple thousand movies in my system that are incorrectly identified as HDTV-1080p rather than Bluray-1080p in their downloaded quality value. I am attempting to automate setting them to the correct value using bash with curl and jq to change these values. I am updating the Profile for the Movie and the Quality for the downloaded movie simultaneously but only the profile is persisting even though they both update in a static web page until I hit refresh.

**To Reproduce**
1. Retrieve the json information for a movie into a file (radarr.json for me)
2. Update with jq and save to a new file (jq '.profileId=8 | .qualityProfileId=8 | .movieFile.quality.quality.id=7 | .movieFile.quality.quality.name="Bluray-1080p" | .movieFile.quality.quality.source="bluray"' radarr.json  > tmp.$$.json)
3. Update the movie in radarr with curl and the API PUT command using the new json file for the payload.
4. With the movie page already open in a browser observe both the Profile and the Quality values are updated in the browser to new values.
5. Hit refresh on the browser and observe only the Profile data persists while quality is set back to the old value.
6. Alternately pull the json data for the movie again and observe the Quality information is not updated.

**Expected behavior**
Both Profile and Quality are updated and persist

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 / Docker 0.0.0-20181213123650-d79e916
 - Mono Version: 5.16.0.220 (tarball Mon Nov 26 17:22:46 UTC 2018)
 - Browser and Version n/a
 - Version 0.2.0.1217

**Debug Logs**
Turn on debug logs under Settings -> General and wait for the bug to occur again. **Upload the full log file here (or another site and link it). Issues will be closed, if they do not include this!**

Seems the API does not generate hardly any logs here is all it did...
[Debug] Api: [GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (6 ms)
[Debug] Api: [GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (6 ms)
[Debug] Api: [PUT] /api/movie?apikey=de8e6ff4c8be4bb6b74bbedacd139b91: 202.Accepted (3940 ms)
[Debug] Api: [GET] /api/extrafile?movieId=233&sort_by=relativePath&order=asc: 200.OK (19 ms)

I have also attached the original json I started with (radarr.json) and the updated json I am sending with the PUT command (tmp.19642.json)

[radarr.json.txt](https://github.com/Radarr/Radarr/files/2715619/radarr.json.txt)
[tmp.19642.json.txt](https://github.com/Radarr/Radarr/files/2715620/tmp.19642.json.txt)

**Comment by galli-leo** [comment]
You need to PUT it to /api/moviefile. The movie endpoint does not update the moviefile. You can take a look at your browsers dev tools to see how we do it (or the js source code).

**Comment by obelisk3847** [comment]
Your API documentation in the Wiki does not list movieFile as an endpoint. I'll check into it. Thanks for the info.

**Comment by obelisk3847** [comment]
Thought I would add this if anyone attemts the same thing... 

To get the moviFile ID which is necessary for the api call you can use the folllowing command;

curl -sS http://RADARRIP:RADARRPORT/api/movie?get --header "X-Api-Key:YOURKEY" --compressed| jq -rs '.[]| .[] | select(.path==PATHTOMOVIE) | .movieFile.id '

Then pull the movieFile information to a file;

curl -sS -X GET "http://RADARRIP:RADARRPORT/api/moviefile/MOVIEFILEID?apikey=YOURKEY" > moviefile.json

You can then edit the file as necessary and PUT it back to the api to update the movie.

**Comment by dmwyatt** [comment]
> You can then edit the file as necessary and PUT it back to the api to update the movie.

Just to expand on this, you can PUT back to `http://RADARRIP:RADARRPORT/api/moviefile` without the `{ID}` on the end since the data you're PUT'ing includes the moviefile id within.
