### ISSUE TITLE
There's an error with localized movie names if you use {Original Filename} as Folder format

### ISSUE THREAD

**Issue by krisz-gemini** [Radarr/Radarr#3272]
**Describe the bug**
1. RenameMovieFileService renames the folder to Hungarian name of the movie: Get Out (2017) -> Tűnj el! (2017)
2. DiskScanService doesn't found the folder
3. Processing stopped, and the movie won't be sent to download client
4. Another aspect of the bug: Why did RenameMovieFileService rename the folder to Hungarian title of the move, when the setting's {Original Filename}.

**To Reproduce**
I think these are the important options:

Standard Movie Format: {Original Filename}
Movie Folder Format: {Original Filename}
Movie Paths Default to Static: NO
Automatically Rename Folders: YES
Use Hardlinks instead of Copy: NO

This bug can be reproduced with any movie with translated title in TMDB. 

**Expected behavior**
1. DiskScanService use the renamed folder (if rename happened)
2. RenameMovieFileService keep the {Original Filename} 

**Desktop (please complete the following information):**
 - OS: [Windows 10
 - Version: 0.2.0.1217
[radarr.debug.1.txt](https://github.com/Radarr/Radarr/files/2715937/radarr.debug.1.txt)
[radarr.debug.2.txt](https://github.com/Radarr/Radarr/files/2715938/radarr.debug.2.txt)

**Debug Logs**

Relevant parts:
18-12-26 21:35:10.9|Info|RefreshMovieService|Updating Info for Get Out
18-12-26 21:35:11.0|Debug|HttpClient|Downloading Completed. took 0s
18-12-26 21:35:11.0|Debug|MediaCoverService|Resizing Poster-500 for [Get Out (2017)][, 419430]
18-12-26 21:35:11.4|Debug|MediaCoverService|Resizing Poster-250 for [Get Out (2017)][, 419430]
18-12-26 21:35:11.8|Debug|CleanExtraFileService|Cleaning missing metadata files for movie: Get Out
18-12-26 21:35:11.8|Info|MetadataService|Movie folder does not exist, skipping metadata creation
18-12-26 21:35:12.7|Debug|RefreshMovieService|Finished movie refresh for Tűnj el!
18-12-26 21:35:12.7|Info|RenameMovieFileService|[Tűnj el! (2017)][tt5052448, 419430]'s movie folder changed to: M:\_Radarr_\Tűnj el! 2017
18-12-26 21:35:12.7|Error|EventAggregator|DiskScanService failed while processing [MovieUpdatedEvent]

[v0.2.0.1217] System.IO.DirectoryNotFoundException: Nem található a következő elérési út egy része.: „M:\_Radarr_\Get Out 2017”.
   a következő helyen: System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   a következő helyen: System.IO.Directory.InternalMove(String sourceDirName, String destDirName, Boolean checkHost)
   a következő helyen: NzbDrone.Common.Disk.DiskProviderBase.MoveFolder(String source, String destination, Boolean overwrite) hely: C:\projects\radarr-usby1\src\NzbDrone.Common\Disk\DiskProviderBase.cs, sor: 264
   a következő helyen: NzbDrone.Core.MediaFiles.RenameMovieFileService.RenameMoviePath(Movie movie, Boolean shouldRenameFiles) hely: C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\RenameMovieFileService.cs, sor: 155
   a következő helyen: NzbDrone.Core.MediaFiles.DiskScanService.Scan(Movie movie) hely: C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\DiskScanService.cs, sor: 75
   a következő helyen: NzbDrone.Core.MediaFiles.DiskScanService.Handle(MovieUpdatedEvent message) hely: C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\DiskScanService.cs, sor: 198
   a következő helyen: NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event) hely: C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Events\EventAggregator.cs, sor: 56

**Comment by galli-leo** [comment]
{Original Filename} will use the standard movie title if you have no files. While this shouldn't happen, it shouldn't matter that much either. Just ignore it and click download once more. This wont be fixed, as the system will be reworked anyways.
