### ISSUE TITLE
Add an 'Update All Indexers' Button When There Are Indexer Errors In System Tab (Like Lidarr)

### ISSUE THREAD

**Issue by Neltherion** [Radarr/Radarr#3275]
a small button that when clicked, would test all indexers at the same time. We have something like this in Lidarr whenever there are errors with the indexers or the download client: [Link to Image](https://imgur.com/a/nL53UbF)

This helps when you have a lots of indexers and they have errors and you have to go to each of them, open them and then click the 'Test' button.

**Comment by Neltherion** [comment]
Well... It still hasn't been added...

**Comment by savahu** [comment]
This would be really useful
