### ISSUE TITLE
unable to add iptorrents rss indexer

### ISSUE THREAD

**Issue by nonrider** [Radarr/Radarr#3279]
Describe the bug
I am attempting to use IPtorrents.
When I try to test or save the URL provided by IPtorrents, Sonarr complains that the 'Base Url' is not in the correct format.

To Reproduce

Navigate to IPTorrents
Go to RSS
Configure the RSS options, select download link (in lieu of web link), select appropriate movie categories
IPtorrents produces URL in following format:
https://iptorrents.com/t.rss?u=userid;tp=apikey;96;48;38;download
where96, 48, and 38 are the  different categories for movies.
Copy and paste URL into Radarr's Add Indexer settings
Hit Test connection
See error.

**Screenshots**
![image](https://user-images.githubusercontent.com/29699052/50554561-a254d700-0c8a-11e9-8883-067d14cfb11a.png)
![image](https://user-images.githubusercontent.com/29699052/50554583-17c0a780-0c8b-11e9-89a5-721b037b6ee5.png)

**Desktop (please complete the following information):**
 - windows 10
 - Version 0.2.0.1217
this seems to be related to a change that IPtorrents made to the RSS url.
see post from the Lidarr forum
https://github.com/lidarr/Lidarr/issues/561

**Debug Logs**
Turn on debug logs under Settings -> General and wait for the bug to occur again. **Upload the full log file here (or another site and link it). Issues will be closed, if they do not include this!**

**Comment by fryfrog** [comment]
Consider using Jackett instead, it will proxy a huge number of torrents into torznab feeds, which Radarr and Sonarr will happily parse for both search and "rss".

**Comment by nonrider** [comment]
[radarr.trace.txt](https://github.com/Radarr/Radarr/files/2781336/radarr.trace.txt)

**Comment by henryschade** [comment]
Having the same issue.
Sonarr does NOT require the use of Jackett, and in my simple setup so far I would rather NOT use Jacett at this time.

**Comment by henryschade** [comment]
And here are my log files:
[radarr.trace.txt](https://github.com/Radarr/Radarr/files/2800280/radarr.trace.txt)
[radarr.txt](https://github.com/Radarr/Radarr/files/2800281/radarr.txt)
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/2800282/radarr.debug.txt)

I noticed in my Trace file (while editing out my encrypted pass) that when my test passes, I am getting results.

**Comment by henryschade** [comment]
Thank you for the info Qstick.
I had noticed a slight difference between the URL IPT was giving me for Movies and the URL I have had in Sonarr for about a year now, but figured it was because of the different "categories".

So updating the URL IPT is giving me for Movies to be more like the one from Sonarr does appear to be working.

Original Movie URL:
https://iptorrents.com/t.rss?u=xxxxx;tp=xxxxx;77;89;90;6;48;54;62;7;download;new
Updated Movie URL:
https://iptorrents.com/torrents/rss?u=xxxxx;tp=xxxxx;77;89;90;6;48;54;62;7;download;new

**Comment by nonrider** [comment]
I tried making the change as stated above and I still got the error that the base url is not in the correct format.

**Comment by henryschade** [comment]
Just being an end user, that should work for you if it did for me.
Here is more specific info about my setup and what I did.
Radarr ver 0.2.0.1217  (from the System tab in the About section)

To setup my IPT Indexer:
Settings -> Indexers

Click the big plus sign.
Click "Custom" in the "IP Torrents" box.
Enter a name.   i.e.  "IPT (Movies)"
Leave "Enable RSS Sync" at "Yes".
Leave "Enable Search" at "No".  (Can't change it anyway.)
Enter the IPT Feed URL in the "Feed URL" field.
Leave "Multi Languages" and "Required Flags" empty.
Update "Minimum Seeders" from 1 to 5.

Click the "Test" button.  Testing 'IPT (Movies)' failed.  
Update URL from IPT.
Click the "Test" button.  Testing 'IPT (Movies)' succeeded.
Click the "Save" button.  (The window closes.)

**Comment by nonrider** [comment]
so I was able to add it but now getting an error that it cannot connect
[radarr.trace.txt](https://github.com/Radarr/Radarr/files/2834815/radarr.trace.txt)
![image](https://user-images.githubusercontent.com/29699052/52319990-8e437a00-299a-11e9-82b3-6ff44d12a1db.png)

**Comment by henryschade** [comment]
I notice in your logs you have:
https://iptorrents.com/rss?u=
it should be:
https://iptorrents.com/torrents/rss?u=

**Comment by ivlovric** [comment]
try this format: https://rss.iptorrents.com/torrents/rss?u=<all the rest>
