### ISSUE TITLE
Add weights to custom format tags

### ISSUE THREAD

**Issue by norbertgaal** [Radarr/Radarr#3283]
[FEATURE REQUEST]

Hi guys,

Thank you for the custom formats it's really useful and I am using it excessively. It would be awesome if I could add a weight to various tags. 

In my example I have a long list of preferred release groups but I would like to prioritise this list. If more releases are found on the list I'd like to chose which one is getting downloaded (higher priority)

Same could apply to languages, if both X and Y are available I'd like to prioritise them.

A simple solution would be more than enough here, like the option of adding a rank or some score to every custom format and if more found the higher scores would weight more.

Thanks you

**Comment by galli-leo** [comment]
If you want format tags to weigh more, make another custom format with those and put it higher in your profile.
