### ISSUE TITLE
Incorrect url

### ISSUE THREAD

**Issue by G4Zz0L1** [Radarr/Radarr#3286]
I've some problems with the urls of movies with non standard char in name, like 'The Naked Gun 2½: The Smell of Fear' or 'Naked Gun 33⅓: The Final Insult', they all return 404.

![image](https://user-images.githubusercontent.com/13220636/50635955-92701800-0f54-11e9-82e1-64e8ad2edc16.png)
![image](https://user-images.githubusercontent.com/13220636/50635968-9e5bda00-0f54-11e9-8cec-fd147e533008.png)

 - OS: Arch Linux
 - Mono Version: 5.16.0 (makepkg/bb3ae37d71a Sat Dec 8 13:21:35 CET 2018)
 - Browser and Version: Chrome 73.0.3642.0
 - Radarr Version: 0.2.0.1217

**Comment by G4Zz0L1** [comment]
It's not a support request, it's an url created by radarr based on the name of the movie that returns a 404. What information you lack/need? I'll try to provide them.

**Comment by galli-leo** [comment]
I have both movies in my radarr library as well (and working fine), that‘s why I marked it as support. Can you clarify where exactly those links are? (It is expected that those characters are missing, they get removed, since we cannot have them in urls).
