### ISSUE TITLE
Ignore terms should not be applied to movie titles

### ISSUE THREAD

**Issue by lonelyfairie** [Radarr/Radarr#3287]
**Is your feature request related to a problem? Please describe.**
I have created a list of ignored terms in order to better filter the releases that are downloaded, but many times I will realize that a movie isn't being downloaded because a term i.e: CAM is part of the movie title, so I have to manually select a release for download. 
**Describe the solution you'd like**
Radarr should be able to tell what a movie title is and exclude that part of the file/torrent name in order to match the rest to the ignore list. 

**Describe alternatives you've considered**
Unfortunately there aren't many, since the ignore terms aren't long words many times just 2/3 letters at most it is likely that the combination will appear in a word, for example I don't want portuguese releases so I exclude PT, since the ignore term is just two letters and it doesn't matter if it is part of a word often times releases will get ignored. So I've had to remove terms like CAM and PT in order for radarr to work as the automatic downloader is intended to be. 

**Additional context**
Not much else to add, here is my ignore list in case it helps:

dual dublado doblado leak leaked PDVD dubbed swesub korsub dksubs vain HDTC blurred TC720P HQHDTS DVDScr HDCAM MD SCR 3D trailer Blurred

I have removed a lot of terms (as PT and CAM) in order to avoid movies getting stuck when I realized it was preventing automatic downloads too often, but would like a solution so I can add them back and have better control over what releases are pulled.

**Comment by galli-leo** [comment]
First of all, I recommend you remove anything related to qualities and hardcoded subs from your ignore list. Radarr already handles that stuff for you. Next, you can use the new custom formats to fix this. Not only can you use regexes instead of just words, but they also won‘t mach the movie title.
