### ISSUE TITLE
Radarr hangs a long time on retrieving non-existent Root Path

### ISSUE THREAD

**Issue by irritatedcone** [Radarr/Radarr#3291]
**Describe the bug**
I switched file-servers a few weeks back and added my new path as the new root folder.
Everytime I went to request something it would take a long time to show me the paths I could use (manually adding them gave me the "already configured as root path" message).
When I removed the no longer existing path everything was near instant again.

It takes too long for Radarr to stop trying to reach that path.
It also doesn't show you ANY path until it times out, and it doesn't say it's still searching for paths.

This issue is in Sonarr, Radarr and in Lidarr, so I'll create a bug report in all.

**To Reproduce**
1. Have existing root path
2. Switch root path to new server / folder
3. Make sure old path is dead
4. Attempt to request something

**Expected behavior**
It shows you what paths you have instantly, instead of after 7-8 minutes.

**Screenshots**
![root paths](https://user-images.githubusercontent.com/44037605/50725133-46120d00-10f9-11e9-964d-bcb2706025fd.PNG)
0b = dead fileserver
12.5TB = new fileserver

**Server**
 - OS: Windows Server 2016
- Radarr version: 0.2.0.1217

**Debug Logs**
I have removed the path - since it no longer exists I cannot re-add this to generate the logs :(

**Comment by fryfrog** [comment]
Click the little red x and remove it.
