### ISSUE TITLE
Movie editor: add year and movie rating columns

### ISSUE THREAD

**Issue by robertbaker** [Radarr/Radarr#3292]
I would like the movie editor to be able to sort by movie rating and year.

I added a bunch of low rated crap and want an easy way to prune it without having to go through and then open tabs on 3,000 movies to check rating and description.

**Comment by fryfrog** [comment]
Sounds like something that could be part of a new ui, if it ever comes. Sonarr's phantom branch has some great sorting (though I don't think year and rating are part of it).

**Comment by galli-leo** [comment]
This has been requested in other issues already, and will be implemented alongside the new ui.
