### ISSUE TITLE
"... indexers have deprecated settings and should be updated" message links to wrong wiki page

### ISSUE THREAD

**Issue by theotherp** [Radarr/Radarr#3293]
How to reproduce: Add PTP as indexer, enter the deprecated settings, save. Wait, I guess?

The "Wiki" link refers to https://github.com/Radarr/Radarr/wiki/Health-checks#the-following-<indexername>-indexers-have-deprecated-settings-and-should-be-updated-<indexername> which 
can't be found.

Version 0.2.0.1291

**Comment by galli-leo** [comment]
We cannot link to the correct page since the message contains the names of your ptp indexers. Which is different for all users

**Comment by theotherp** [comment]
Yes, I saw that from the link ;-)

Couldn't you recognize this and link to a general entry for deprecated
options?

**Comment by theotherp** [comment]
I understand. All good.
