### ISSUE TITLE
Enhancement: Deluge Completed Download Override

### ISSUE THREAD

**Issue by krugster** [Radarr/Radarr#3294]
Would be helpful to have an improvement on the Deluge client settings (within Radarr) to set the "completed download location".  Deluge supports overriding the location that it will move a file to after it has been downloaded.

**Comment by fryfrog** [comment]
I'd suggest improving your OP by adding more information, point at api or any documentation about it. Maybe point out other software that uses it.

**Comment by Dnkhatri** [comment]
> Would be helpful to have an improvement on the Deluge client settings (within Radarr) to set the "completed download location". Deluge supports overriding the location that it will move a file to after it has been downloaded.

I don't see the usefulness in this unless you can set each movie completed location otherwise just using deluge builtin label move completed does the same. Just set radarr label move completed to the directory you want in deluge. Radarr will wait for the file to be moved before importing it.

**Comment by Terebi42** [comment]
@Dnkhatri  Radarr has a root folder, and then will automatically make a folder for each movie.  If you pass that directory to deluge (or other torrent client), you can skip the "move" all together, and just download directly to your destination folder.  Flexget and several of the other older automation apps support that workflow.

**Comment by fryfrog** [comment]
Don't download into your movie library. Radarr is designed to manage your library folder, moving things from where your download client downloads too. If you're seeding, use hard links.

**Comment by Terebi42** [comment]
@fryfrog hardlinks do not work across drives, and require double maintenance of files to recover space when you want to delete.

**Comment by fryfrog** [comment]
Downloading to your library folder will have the same issue and end up a
hot mess because it'll still copy, only finished torrents import w/ move.

**Comment by Terebi42** [comment]
It will not still copy, if you disable post processing, which was the OPs assertion to start this thread.

**Comment by fryfrog** [comment]
Then it isn't going to know a movie was successfully downloaded and if it shows up in feeds in the future, it'll re-download.

Radarr does *not* do well if it isn't managing the library.

I think CP will do a better job in that role.

**Comment by jonm802** [comment]
> @fryfrog hardlinks do not work across drives, and require double maintenance of files to recover space when you want to delete.

use black hole torrent in radarr, in deluge use the auto add plugin, set your download folders up so the movie related folders are on the same drive
