### ISSUE TITLE
"Allow Hardcode Subs" as a Quality parameter.

### ISSUE THREAD

**Issue by RhinoRhys** [Radarr/Radarr#3298]
I think the option to allow or disallow hardcoded subs is a great feature but I think it would be brilliant if Radarr kept a note of the files with hardcoded subs and bloody amazing if it were set up to handle this as a quality setting and consider the cutoff as unmet, regardless of actual quality, until a version is found without hardcoded subs.

Currently, if I come across a film in my library with hardcoded subs I will just log into the Radarr web UI and then perform a manual search for a new version or downgrade the quality setting associated with the file to force it under the cutoff.

**Comment by McGriddle** [comment]
What you are looking for is 'custom formats'. It's just a way to label various releases with your own types. One of the default types is for releases with hardcoded subs. You can setup profiles to have a cutoff AND a custom format cutoff. Both must be met. 

The profile in this screenshot will look for all releases between webdl-1080p and regional. Each release that meets one of those must also match to 'None' (all) or one with hardcoded subs. The cutoff is WEBDL-1080p. If a movie is found of that quality, the movie won't be considered satisfied unless it doesn't have hardcoded subs.

You can see custom formats in the history. 

![image 2019-01-08 at 6 47 55 pm](https://user-images.githubusercontent.com/5432956/50866524-3e13d080-1378-11e9-9623-908f70f92b56.png)
![image 2019-01-08 at 6 57 42 pm](https://user-images.githubusercontent.com/5432956/50866529-42d88480-1378-11e9-8423-8cea3352c9a2.png)
![image 2019-01-08 at 6 53 23 pm](https://user-images.githubusercontent.com/5432956/50866532-45d37500-1378-11e9-8acc-85f1b36cc4fc.png)

**Comment by RhinoRhys** [comment]
Ah right, I've heard a little bit about them on Reddit but I haven't found the settings to have a play yet. Seeing your screenshot, I've just realised this is part of the update I haven't managed to install yet. I shall have to work out why my pooter won't let me update. Muchas gracias!
