### ISSUE TITLE
Issue with Import from IMDB 

### ISSUE THREAD

**Issue by UsamaWaheed** [Radarr/Radarr#3301]
When I create a new List with IMDB in radarr and click test, it says successful. However when I click Add Movies -> Add Via List I get the following error:

> Sorry. We Couldn't Find Any Movies Matching ''

Settings for IMDB LIST
Radar API URL: https://api.radarr.video/v2
Path to list: Tired both options
-  /imdb/list?listId=urXXXXXXXX
-  /imdb/list?listId=lsYYYYYYYYY

Radarr: 0.2.0.1217

There is absolutely no log created when I click on fetch list.

**Comment by viewphoria6** [comment]
i have the same issue now, although when originally setup my lists were working fine

Radarr: 0.2.0.1217

**Comment by jaysel** [comment]
I am seeing the same issue. If I create a list with 1 new film in it, the import works ok. 
However, my usual lists do not work. 
I have read that this may occur if there are films in the List that already exist in Radarr. But suely there is a better way round this, than for me to manually check my IMDB list against my Radarr list
Am I missing something here?

**Comment by UsamaWaheed** [comment]
Anyone from the Radar team looked into this? Any help will be appreciated.

**Comment by TheDogg** [comment]
I'm having the same issue.  I added the IMDB top 250 list, I was able to load the list once, I added 2 movies form that list.  Then I went back to load the list again and all I'm getting now is "Sorry. We Couldn't Find Any Movies Matching ''"

I tried removing the list and adding it back, same error. Nothing shows up in the logs

**Comment by galli-leo** [comment]
Please post your list ids, I cannot really help otherwise. Also we did some server stuff, so it should work a lot smoother now.

**Comment by UsamaWaheed** [comment]
Hi galli-leo,

thanks for trying to help out. Please find the list details as below:
https://www.imdb.com/list/ls020502677/

So the way I had it configured was 
Availability: In Cinemas
Profile: Any
Folder:\\myfolder\Movies
API: https://api.radarr.video/v2
Path to list:/imdb/list?listid=ls020502677

tried multiple options with path to list.

**Comment by galli-leo** [comment]
@UsamaWaheed Works fine for me. Make sure you use `listId` (capital i) and you haven't added all movies from your list. Radarr will show the error you have if all movies from the list were added.

**Comment by viewphoria6** [comment]
I can confirm that despite the Add Movies -> Add Via List shows an error, movies that are added to the imdb lists still get added to Radarr

**Comment by UsamaWaheed** [comment]
@galli-leo Did what you said. Deleted the movie in my IMDB list from Radarr and then run the list. It works great i,e, no error. 

But the issue is lets say I run import and 2 movies are imported, then after lets say 30 minute I add one more movie to the list and wait for the time sync of list, it doesn't import it as long as there is any match :( so we have to keep clearing IMDB watch list. Is there any way to fix this? can this be a feature request?

**Comment by galli-leo** [comment]
@UsamaWaheed IMDB lists are cached, you need to wait more than that for them to show up in the list. You also shouldn‘t need to clean the list, just wait for the cache to be cleared and the list auto sync to happen.

**Comment by UsamaWaheed** [comment]
@galli-leo Whats the cache time? Can you kindly do a favor and try this again:

https://www.imdb.com/list/ls020502677/

So the way I had it configured was
Availability: In Cinemas
Profile: Any
Folder:\myfolder\Movies
API: https://api.radarr.video/v2
Path to list:/imdb/list?listid=ls020502677

![link](https://user-images.githubusercontent.com/35238840/53350220-1c76a480-3938-11e9-90d5-9da00726df20.PNG)
