### ISSUE TITLE
Add Movie title to email subject in notification

### ISSUE THREAD

**Issue by Rouzax** [Radarr/Radarr#3304]
**Is your feature request related to a problem? Please describe.**
When Radarr sends a email notification that a movie is downloaded it only uses `Radarr [Movie] - Downloaded` in the subject.
As a result gmail just aggregates the mails in 1 conversation.

![image](https://user-images.githubusercontent.com/4103090/51076452-de2f6980-1698-11e9-9d2f-d3cb0dcb9353.png)

**Describe the solution you'd like**
If the movie title would be added this would solve the problem.

**Comment by galli-leo** [comment]
This is part of a more general feature request that would allow templating both the message and title for any notification.
