### ISSUE TITLE
Main Folder Free Lists?

### ISSUE THREAD

**Issue by jamesmay07** [Radarr/Radarr#3305]
Hi there, When we use lists, we have to determine where they will be put before we can see the list, it would be great if we could set the location to add the movie, like we would when searching for a movie normally, most lists have a mix of different types of movies and as some one that has a complicated folder scheme having to choose one location for an entire list just makes things long winded.

love radarr hope i put this in the right place :)

**Comment by fryfrog** [comment]
As a work-a-round, consider making a list for each category and selecting just that genre or what ever your folders are arranged by.

Or don't use an overly complicated root folder structure.
