### ISSUE TITLE
Request: Ability to filter out 3D results.

### ISSUE THREAD

**Issue by jtrosper** [Radarr/Radarr#3307]
Currently, Radarr will find and locate items solely based on display resolution.  This often causes SBS 3D versions of the media to be downloaded, which is potentially unwanted behavior.  The ability to filter out SBS 3D (or any 3D, really) would be useful.

**Comment by randellhodges** [comment]
If all the files are tagged, with, say Half-SBS, under indexers, you can add a "Must Not Contain" restriction. That should fix that. You might need to add other variations. A generic "3D" might work, but that might be too loose of a match.

**Comment by galli-leo** [comment]
Use custom formats.
