### ISSUE TITLE
[Bug] qBittorrent 404 Error (Changed In 4.1+ Removed in 4.2)

### ISSUE THREAD

**Issue by zero77** [Radarr/Radarr#3309]
When trying to test the connection or send torrents to qBittorrent it doesn't work and instead gets a 404 error.
I think this maybe because qBittorrent nightly has dropped support for their old API.

Also, i am using the most up to date nightly vershon of Radarr.

> HTTP request failed: [404:NotFound] [POST] at [http://163.172.39.74:9000/login]

API Documentations:
https://github.com/qbittorrent/qBittorrent/wiki#webui-related

Related:
https://github.com/Radarr/Radarr/pull/3356

**Comment by zero77** [comment]
@teejo75 
Do you just mean change this from "/version/api" to "/version/api/v2/"

> https://github.com/Radarr/Radarr/blob/develop/src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentProxy.cs#L47

**Comment by teejo75** [comment]
Looks like ALL calls will need to be prefixed with /api/v2:

From https://github.com/qbittorrent/qBittorrent/wiki/Web-API-Documentation#general-information

> All API methods are under /api/v2/APIName/methodName, where APIName is a certain subgroup of API methods whose functionality is related.

**Comment by zero77** [comment]
@teejo75 
Thanks, i have had a look through the documentation and submitted a PR:
https://github.com/Radarr/Radarr/pull/3328

**Comment by teejo75** [comment]
I don't think those calls in your PR are correct. Not all of those commands are under the /app endpoint. I also don't think changing the version call to using webapiVersion will work as expected.

**Comment by zero77** [comment]
> I don't think those calls in your PR are correct. Not all of those commands are under the /app endpoint.

Ok, I will have another look through the document.
> I also don't think changing the version call to using webapiVersion will work as expected.

I will change it then.
> I'm not sure just changing the calls is the right way to go about it. We need to be cognisant of when the V2 API came in to effect. Changing the calls to the new API calls will break for people using older versions of qbittorrent.

Unless i am mistaken, qBittorrent has supported API v2 for a while but, the next stable update will be dropping the older APIs and moving to v2 completely.

**Comment by zero77** [comment]
Moved To #3356

**Comment by itsbebbo** [comment]
Initial testing against V2 of the qBittorrent API appears to be successful (Adding, removing, reading torrent list etc). Probably needs fully testing to ensure priority changes, category association etc all work as well. Finally, it was tested against v4.1.5 of qBit and needs running against v4.2.0.

**Comment by Arathen** [comment]
This issue is still problematic. The current version of Radarr does not work with development builds of QBT since the legacy API was dropped in https://github.com/qbittorrent/qBittorrent/pull/10145 on January 12th.

**Comment by Arathen** [comment]
Its still broken. If it could be fixed ( https://github.com/Radarr/Radarr/pull/3356 ), that would be awesome because Radarr cant be used by anybody running qbittorrent from master source since January.
