### ISSUE TITLE
Radarr adding torrent but is only adding Hash, doesn't download

### ISSUE THREAD

**Issue by sean1604** [Radarr/Radarr#3311]
**Describe the bug**
Trying to download Trainspotting torrent file. It is finding and automatically adding files to Deluge but every time it does it is only showing the Hash file on Deluge and doesn't download. 
This happens when manually searching and adding a file or auto searching. I will show screenshots below. This has happened with 4 separate torrent files now. 
What's more confusing is the first time I added the movie it added fine however it go stuck on 50% downloaded. Therefore I marked it as failed and removed the file. 
I then added another movie "The Fighter" and it downloaded the movie with no issues. 
It seems as though Radarr believes it has passed the file over to Deluge fine but Deluge gets the file and just has the Hash as you will see in the screenshots. 

**To Reproduce**
Search for Transpotting. Add to download client. Either auto or manual search.  

**Expected behavior**
Add the torrent file and download it.

**Screenshots**
![image](https://user-images.githubusercontent.com/46625044/51179999-039dbc80-18bf-11e9-8da5-cf0ebde5d125.png)

![image](https://user-images.githubusercontent.com/46625044/51180020-1a441380-18bf-11e9-917b-c4576f9003ac.png)

![image](https://user-images.githubusercontent.com/46625044/51180053-2cbe4d00-18bf-11e9-8262-d486143cff55.png)

![image](https://user-images.githubusercontent.com/46625044/51180123-655e2680-18bf-11e9-997d-610e9c1100ea.png)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Version 0.2.0.1217

**Debug Logs**
19-1-15 09:15:06.7|Info|DownloadDecisionMaker|Processing 52 releases
19-1-15 09:15:08.5|Info|RssSyncService|RSS Sync Completed. Reports found: 52, Reports grabbed: 0
19-1-15 09:24:11.9|Info|PreDBService|Starting PreDB Sync
19-1-15 09:24:11.9|Info|NetImportSearchService|No lists are enabled for auto-import.
19-1-15 10:15:14.0|Info|RssSyncService|Starting RSS Sync
19-1-15 10:15:22.2|Warn|Torznab|Indexer torznab_katcrs rss sync didn't cover the period between 15/01/2019 09:00:47 and 15/01/2019 09:15:22 UTC. Search may be required.
19-1-15 10:15:22.2|Info|DownloadDecisionMaker|Processing 42 releases
19-1-15 10:15:23.9|Info|RssSyncService|RSS Sync Completed. Reports found: 42, Reports grabbed: 0
19-1-15 10:24:14.3|Info|PreDBService|Starting PreDB Sync
19-1-15 10:24:14.3|Info|NetImportSearchService|No lists are enabled for auto-import.
19-1-15 11:15:46.1|Info|RssSyncService|Starting RSS Sync
19-1-15 11:15:53.4|Warn|Torznab|Indexer torznab_katcrs rss sync didn't cover the period between 15/01/2019 10:05:22 and 15/01/2019 10:40:53 UTC. Search may be required.
19-1-15 11:15:53.4|Info|DownloadDecisionMaker|Processing 36 releases
19-1-15 11:15:54.5|Info|RssSyncService|RSS Sync Completed. Reports found: 36, Reports grabbed: 0
19-1-15 11:22:40.2|Info|NzbSearchService|Searching 4 indexers for [Trainspotting]
19-1-15 11:22:47.2|Info|DownloadDecisionMaker|Processing 116 releases
19-1-15 11:22:49.3|Info|MovieSearchService|Movie search completed. 0 reports downloaded.
19-1-15 11:24:16.5|Info|PreDBService|Starting PreDB Sync
19-1-15 11:24:16.5|Info|NetImportSearchService|No lists are enabled for auto-import.
19-1-15 11:24:58.2|Info|NzbSearchService|Searching 4 indexers for [Trainspotting]
19-1-15 11:25:04.4|Info|DownloadDecisionMaker|Processing 115 releases
19-1-15 11:26:23.7|Info|DownloadService|Report sent to Deluge. Trainspotting 1996 (1080p Bluray x265 HEVC 10bit AAC 5 1 Tigole)
19-1-15 11:34:36.2|Info|MovieService|Adding Movie [The Fighter (2010)][, 45317] Path: [F:\Films\The Fighter (2010)]
19-1-15 11:34:36.2|Info|MediaCoverService|Downloading Poster for [The Fighter (2010)][, 45317] http://image.tmdb.org/t/p/original/ytGIpdxYyvXwch5QILfquSTMA9f.jpg
19-1-15 11:34:36.3|Info|RefreshMovieService|Updating Info for The Fighter
19-1-15 11:34:36.9|Info|MetadataService|Movie folder does not exist, skipping metadata creation
19-1-15 11:34:37.2|Info|DiskScanService|Scanning disk for The Fighter
19-1-15 11:34:37.2|Info|MovieScannedHandler|[The Fighter] was recently added, performing post-add actions
19-1-15 11:34:37.3|Info|NzbSearchService|Searching 4 indexers for [The Fighter]
19-1-15 11:34:37.4|Info|MediaCoverService|Downloading Fanart for [The Fighter (2010)][tt0964517, 45317] http://image.tmdb.org/t/p/original/43fnzmOMO5zOUFH3EzyuwSh87IS.jpg
19-1-15 11:34:43.6|Info|DownloadDecisionMaker|Processing 97 releases
19-1-15 11:34:46.7|Info|DownloadService|Report sent to Deluge. The Fighter (2010) (1080p BluRay x265 HEVC 10bit AAC 5 1 Tigole) [QxR]
19-1-15 11:34:46.8|Info|MovieSearchService|Movie search completed. 1 reports downloaded.
19-1-15 11:39:56.1|Info|NzbSearchService|Searching 4 indexers for [Trainspotting]
19-1-15 11:40:05.3|Info|DownloadDecisionMaker|Processing 115 releases
19-1-15 11:40:07.5|Info|MovieSearchService|Movie search completed. 0 reports downloaded.
19-1-15 11:40:28.7|Info|NzbSearchService|Searching 4 indexers for [Johnny English Strikes Again]
19-1-15 11:40:35.0|Info|DownloadDecisionMaker|Processing 145 releases
19-1-15 11:40:41.6|Info|NzbSearchService|Searching 4 indexers for [Johnny English Strikes Again]
19-1-15 11:40:47.8|Info|DownloadDecisionMaker|Processing 145 releases
19-1-15 11:43:47.6|Info|NzbSearchService|Searching 4 indexers for [Trainspotting]
19-1-15 11:43:55.1|Info|DownloadDecisionMaker|Processing 116 releases
19-1-15 11:56:01.0|Info|DownloadService|Report sent to Deluge. [Devil-TorrentS pl]Trainspotting 1996 480p BRRip x264 AC3-HcI
19-1-15 11:56:09.0|Warn|MovieFileMovingService|Unable to set last write time

**Comment by sean1604** [comment]
edit/update;

It did eventually download the last file I tried which was a 480p rip. I'm assuming perhaps deluge does this if there are no seeders to get the information from would that be correct? I had left some of the files for a while (one overnight) before deleting them, perhaps I should have left the other ones longer to see if it worked.

**Comment by fryfrog** [comment]
A torrent that looks like a hash is a magnet link. Your torrent client will turn it into a real name after it connects w/ some peers. If there are no peers, it'll never resolve.
