### ISSUE TITLE
Radarr not importing foreign titles movies

### ISSUE THREAD

**Issue by neepz** [Radarr/Radarr#3314]
I'm having some trouble with foreign titles movies not importing after completing the download.
The indexers are searched correctly and the torrent is downloaded just fine but it won't import from my rtorrent default download folder to /home/xxxx/Movies where my library is pointed to. 

For exemple: Le rayon vert 1986 576p BluRay DD1.0 x264-EA
It finds and downloads the movie just fine but it won't mark as downloaded (therefore creating a hardlink of the movie on the proper folder).
I have to go to rutorrent and manually save the torrents on the empty folder with almost every foreign titled torrent - it also happens with files with the original title and the respective AKA english title.

It imports all other movies with english titles just fine but it happens almost 99% of the time with foreign titles.

Here are my configurations:

https://i.imgur.com/ZC9KIPd.png?2
https://i.imgur.com/0jhXWnH.png (it also happens with language set to any)
https://i.imgur.com/UuOYW0Q.png

**Comment by fryfrog** [comment]
I bet they're not even showing up in Activity, right?

I don't know of a great *solution* to this, but you can at least do things manually by going to Wanted -> Manual import and aiming at the torrent folder. It won't recognize the movie, but you can pick the right movie. Set it to Copy for the import and if you have hard links turned on (and they'll work), it'll be a hard link.

**Comment by fryfrog** [comment]
Can you turn your logging up to Trace and capture the spew around where it scans all the downloads from the torrent client? You'll probably see it there, but you'll see it parse and fail to match or match but still not show up for some reason.

**Comment by neepz** [comment]
> I bet they're not even showing up in Activity, right?
> 
> I don't know of a great _solution_ to this, but you can at least do things manually by going to Wanted -> Manual import and aiming at the torrent folder. It won't recognize the movie, but you can pick the right movie. Set it to Copy for the import and if you have hard links turned on (and they'll work), it'll be a hard link.

It works fine when I link the file with the movie manually (one thing that is weird is that the movie does not show as missing after the match but when I try to manually import other titles the ones I already linked still show as missing).


I don't really know how to run the log specifically for what you're asking. Could you help me out on this one?

**Comment by fryfrog** [comment]
Settings, General, Log Level. Change it to trace. Make your thing happen, then open the log file and copy/paste a big chunk of it into a pastebin like [ptpb](https://ptpb.pw/f).

**Comment by Piottreck** [comment]
Exactly the same for Usenet Downloads.
The Problem occurs for me with movies in German language and therefore differing German titles.
Movies are found and downloaded but radarr doesnt recognice them in the next step for the import.
My workaround at the moment is to rename the movies in the sabnzbd queue to match the original English title.
Did I maybe configure something wrong?

**Comment by Piottreck** [comment]
Using Custom Formats by the way (which seem to work perfectly fine)
German and English
else German
else English

http://prntscr.com/ml9ydn
http://prntscr.com/ml9y0o

**Comment by galli-leo** [comment]
Yes this is a "known issue". I plan on making Radarr remember movies that are mapped by imdbid when downloading, but that's already tracked here: https://github.com/Radarr/Radarr/projects/2

**Comment by inasua** [comment]
is there a workaround for that so i can download movies with ombi?
