### ISSUE TITLE
Radarr crashes randomly hardly reproducible 

### ISSUE THREAD

**Issue by Bastien42** [Radarr/Radarr#3321]
my situation i'm running radarr, sonarr, plex, jackett, all on the same computer all of my drive are local 5 of them two 8Tb two 3Tb. I've now about 4000 movies on them for an average of 4-10gb per movie. Anyhow my issue is that Radarr crashes, the most complex part is that it's random, each and every time. I'll provide the full trace and debug log, to my eye nothing there i've windows logs that make a little more sense. But the last time I shared them galileo told me that it was irrelevant since it's not radarr. Anyway even though the crashes are randoms i'll try to tell you how and what.

[radarr.trace.txt](https://github.com/Radarr/Radarr/files/2775426/radarr.trace.txt)
[radarr.txt](https://github.com/Radarr/Radarr/files/2775427/radarr.txt)
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/2775428/radarr.debug.txt)

at first i had 26k movie on radarr for months everything worked good then one day radarr crashed to that i can say that when i did a full clean install which mea, i didn't keep my settings nore movie library after i imported my movie library sothe 4000 movies it took radarr 1 or 2 hours to crash but it did

**Comment by fryfrog** [comment]
We've been doing some support on Discord, I don't think this is ready for an issue... but it can always be re-opened.

**Comment by galli-leo** [comment]
If this is the crashes I have seen some talk on discord about (where windows sometimes complains about SQLITE), I would makes sure that you are using an up to date version of sqlite. From googling around, it can be that you have installed an old SQLITE dll inside e.g. system32 which is used instead the one we use, which then can cause issues.

**Comment by Bastien42** [comment]
could it be corrupted database which sounds highly unlikely since i've done a full uninstall and library / settings wipes and therefore creating brand new SQLITE3 DLL when reinstalling and batch importing my movie and Trakt list
