### ISSUE TITLE
Store sorting order

### ISSUE THREAD

**Issue by jbrodriguez** [Radarr/Radarr#3322]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when i switch pages the come back to the home page and it doesn't remember the sorting order.
I want order by date in cinemas descending and it defaults to ascending

**Describe the solution you'd like**
I'd like the interface to store (localStorage?) the sorting order I prefer.

**Describe alternatives you've considered**
Can't think of any

**Additional context**
N/a

**Comment by Zachary24** [comment]
It'd be nice if it also stored the viewing option, and mainly the page count in the settings, it constantly goes from 1,000 down to 250.
