### ISSUE TITLE
Folder renaming not working properly?

### ISSUE THREAD

**Issue by AquaRelliux** [Radarr/Radarr#3325]
**Describe the bug**
I have changed my settings under advanced to also include quality on folders like this:
{Movie Title} ({Release Year}) {Quality Title}
However when new movies are added they stick to the original format like this:
{Movie Title} ({Release Year})

**To Reproduce**
1. Go to 'Settings -> Media Management -> Select view advanced'
2. Change the folder setting from {Movie Title} ({Release Year}) -> {Movie Title} ({Release Year}) {Quality Title}
2. Import a movie and see the wrong format being used

**Expected behavior**
I expect new movies that are being imported uses this format:
{Movie Title} ({Release Year}) {Quality Title}

**Screenshots**
N/A

**Desktop (please complete the following information):**
-unRAID docker linuxserver.io latest version as of today

**Debug Logs**
Can be added if needed I just wanted to make sure I am not misunderstanding anything here

**Comment by fryfrog** [comment]
You'll need to enable dynamic paths, I *think* by disabling the static paths setting. Then you'll need to go to Movie Editor and change *all* your existing movies to not use static paths. *Then* I think you'll need to do the movie refresh System Task.

I'm gonna go ahead and mildly suggest you *don't* include changing data in the folder name, put it in the file instead.
