### ISSUE TITLE
Refactor Search Attribute for Indexer into Automatic vs Interactive Search

### ISSUE THREAD

**Issue by rg9400** [Radarr/Radarr#3326]
**Is your feature request related to a problem? Please describe.**
I want to use certain indexers only for an "Interactive Search" as it is called in Sonarr V3. This is where I see the list of matched releases and select one to grab. I currently can enable a provider for "Search" and "RSS Sync", so while I could disable a provider for the RSS feed, it would still be used for a manually triggered "Automatic Search" via the UI or API (where I do not get to select the release, but Radarr chooses the best release automatically).

This creates frustration as I want to use my torrent indexer for the interactive search, but any "automated" search, e.g. adding the movie to Ombi, uses this indexer as well, which is not wanted.

**Describe the solution you'd like**
Copy Sonarr V3

![image](https://user-images.githubusercontent.com/39887349/51487820-a2b42f80-1d69-11e9-9ad6-054c4ec8a917.png)

**Describe alternatives you've considered**
I've considered just disabling the torrent indexer and manually searching for the movie in NZBHydra when I want to look at torrent releases as well. This is, of course, more cumbersome. If an automated search fails to grab a good release, I should be able to trigger this interactive search from Radarr itself.

**Comment by behold81** [comment]
has there been an update when this is coming? This is something I would really like to see.

**Comment by rafaelreis-r** [comment]
Hey guys. Did this make it into the master branch? Really uselful feature. Thanks

**Comment by ta264** [comment]
No only aphrodite (V3)
