### ISSUE TITLE
Renaming with an option to replace spaces with underscores.

### ISSUE THREAD

**Issue by msigler-cb** [Radarr/Radarr#3327]
**Is your feature request related to a problem? Please describe.**
Renaming with an option to replace spaces with underscores.

**Describe the solution you'd like**
Media Mgmt > Movie naming 
Replace Spaces > Yes
> Separator
Option for underscore '_'

**Describe alternatives you've considered**
Not replacing spaces or using period, or not renaming.

**Additional context**

**Comment by Qstick** [comment]
This is already possible, use tokens with underscores instead of standard tokens. Ex. `{Movie_Title}` instead of `{Movie Title}`
