### ISSUE TITLE
Filter not sticking in Movie Editor

### ISSUE THREAD

**Issue by KrunchMuffin** [Radarr/Radarr#3329]
**Describe the bug**
When in Movie Editor, I click a filter for Monitored. If I go click the unmonitor flag for a movie, the page resets to default without filter sticking.

**To Reproduce**
1. Go to Movie Editor
2. Click on any filter
3. Scroll down to any monitored or unmonitored movie
4. Click flag to monitor or unmonitor.

**Expected behavior**
Page should keep filter, or better yet, not refresh

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser and Version: Chrome 71
- Version: 0.2.0.1217 develop

**Debug Logs**
Don't think this is necessary.

**Comment by fryfrog** [comment]
I reproduced this in my Radarr too. I agree, the filtering should not change and the toggled item should probably disappear.
