### ISSUE TITLE
Problem with tor-proxy and indexer

### ISSUE THREAD

**Issue by Anakim** [Radarr/Radarr#3331]
**Description:**

**Radarr Version:**
0.2.0.1217 (docker image)
**Mono Version:**
5.16.0.179 (tarball Thu Oct 4 10:29:10 UTC 2018)
**Debug Logs:**

# Do not remove anything from your logs and post the full logs! If not everything fits in here use a service like https://pastebin.com to upload them.

Hy

I use a nzb indexer with  tor-proxy server (docker image) over an apikey. This works fine with Sickchill. But in Radarr i have the same settings. IP, Port API-Key but it doesn't work. I can't see details in the logfile. It's not possivel to connect.

Where can i see what the indexer does? I use the newznab Profile same as Sickchill.

Anakim

**Comment by fryfrog** [comment]
Turn your logging up to Trace, try to add the indexer and use the test button. Pastebin the results around that time and get some help on Discord.

**Comment by fryfrog** [comment]
The error says `Either 'Categories' or 'Anime Categories' must be provided`, what have you got there?

**Comment by Anakim** [comment]
i have the same catagorie used as in Sickchill .. 5000. Sickchill connect to the indexer and shows me 3 available Categories. 5000 ist the right one. But now i think, Radarr can't find Movies in Categorie 5000. 5020,5030 shows me this error

19-1-28 19:44:56.9|Warn|Newznab|nzb.to does not support the following categories: 5020. You should probably remove them.
19-1-28 19:44:56.9|Warn|NzbDroneErrorPipeline|Invalid request Validation failed:

Mybe my indexer is not compatible to radarr although i can download movies there.
What do you think?

**Comment by fryfrog** [comment]
You need the categories it does support. I'd just remove `5020` and see what you see. Turn logging up to trace and you can see the actual url hit hits, copy paste that and fiddle w/ the url parameters until you get it working.

What indexer?

**Comment by Anakim** [comment]
ok i set logging under 'General' to trace, but radarr shows me only the two entries  above.. and no url ?
is there another way to trace?

my indexer is nzb.to and i use the tor browser here from github
[https://github.com/cytec/nzb.to-nZEDb](url)
