### ISSUE TITLE
Radarr Icons Not Loading in Chrome

### ISSUE THREAD

**Issue by neuman1812** [Radarr/Radarr#3332]
**Description:**
In Google Chrome on Linux,  the Radar Icons do not load correctly,  however they do function.
![radarr](https://user-images.githubusercontent.com/9267886/51648366-3c3c3680-1f4e-11e9-822c-e8a5bb3565e6.png)

**Radarr Version:**
Radarr Ver. 0.2.0.1217 develop

Logs- No errors shown in logs that I can find.  

***Chrome Version *******
```
Google Chrome | 71.0.3578.98 (Official Build) (64-bit)
-- | --
Revision | 15234034d19b85dcd9a03b164ae89d04145d8368-refs/branch-heads/3578@{#897}
OS | Linux
JavaScript | V8 7.1.302.31
Flash | 32.0.0.114 /home/walter/.config/google-chrome/PepperFlash/32.0.0.114/libpepflashplayer.so
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
Command Line | /usr/bin/google-chrome-stable --flag-switches-begin --flag-switches-end
Executable Path | /opt/google/chrome/google-chrome
```

Troubleshooting:
- Clearned Cache/History/Bookmarks
- Reinstalled
- Tested on the same machine with Firefox, No issue.

**Comment by jamesmacwhite** [comment]
Running any plugins in Chrome that block ads or JS at all?

**Comment by neuman1812** [comment]
Just ublock orgin.  I'll try it with it disabled.

**Comment by neuman1812** [comment]
I actually use uBlock Plus Adblocker   and that was what it was.  Sometimes its the simple things we miss.

I added it to my whitelist.  Working correctly now.
