### ISSUE TITLE
Notification of problems

### ISSUE THREAD

**Issue by Yaff1e** [Radarr/Radarr#3334]
**Is your feature request related to a problem? Please describe.**
I use Radarr with NZBHydra. Occasionally NZBHydra becomes unreachable and Radarr warns about the indexer not being available. The problem is that unless I log in to Radarr I'm not aware there's a problem

**Describe the solution you'd like**
I'd like for any problems including Indexer availability to be notified in the same way as successful grabs/downloads ie Pushbullet / Join

**Comment by fryfrog** [comment]
I agree w/ this. I don't use notifications because I generally don't care when a movie was downloaded, upgraded or whatever. But I *would* like to know when things are stuck in the queue or indexers fail or ...

**Comment by Qstick** [comment]
@fryfrog this would be same as #1265 wouldn’t it?

**Comment by fryfrog** [comment]
Yup, closing.
