### ISSUE TITLE
Custom Format Cutoff isn't been followed or ignored

### ISSUE THREAD

**Issue by TRaSH-** [Radarr/Radarr#3335]
**Describe the bug** + **To Reproduce** + **Screenshots**
I use several custom profiles for my preference,
![image](https://user-images.githubusercontent.com/6155095/51696799-97316480-2006-11e9-9c43-128df73dc848.png)
i prefer TrueHD over DTS-HD
that's why i put it above DTS-HD
Radarr finds a movie with TrueHD and it get's downloaded and moved.
but a few hours later it get's deleted and replaced with a version that uses both.
![image](https://user-images.githubusercontent.com/6155095/51697040-2b9bc700-2007-11e9-8ca8-0857f9628eb3.png)

This is my used profile
![image](https://user-images.githubusercontent.com/6155095/51697138-60a81980-2007-11e9-9331-f7082f032e49.png)

**Expected behavior**
I would expect that if a higher placed format in this example TrueHD it wouldn't be replaced by something that's lower in the list.
like the quality profile

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS (Radarr running in container)
 - Mono Version: 5.18.0.240 (tarball Wed Jan 16 09:13:03 UTC 2019)
 - Version: 0.2.0.1217 

**Debug Logs**
https://paste.ee/p/faxKC

added my Custom formats
![image](https://user-images.githubusercontent.com/6155095/51703506-c6e86880-2016-11e9-972e-9df6340a8fcb.png)

The remux is more a placeholder for the separation of the full blurays (iso, BDMV)

**Comment by fryfrog** [comment]
Talked on Discord, I think this happens because the Remux custom format is very lax and is ranked above TrueHD and DTS. I think that means *any* Remux would have replaced it, it is just a coincidence this one had both TrueHD *and* DTS.

**Comment by fryfrog** [comment]
We solved this so I'm closing it.
