### ISSUE TITLE
File naming format : include Custom format as tag

### ISSUE THREAD

**Issue by hergonoway** [Radarr/Radarr#3337]
**Is your feature request related to a problem? Please describe.**
French people like me often struggle with French language between audio from Canada and audio from France. Most of the time this distinction is set in the original filename with tag like "TRUEFRENCH", "VFF", "VF2", "VFQ", etc. 

With the arrival of Custom Format, now I can easily search and upgrade a movie till it reaches the non-canadian audio (my preference) with a cutoff Custom Format like this :
`C_RXRQ_\B(TRUEFRENCH|VFF|VF2|VFI|FR2)\B `

but this "knowledge" of canadian audio or true french audio is lost during file rename process since there's no rename option (option like {Edition Tags} {MediaInfo Audio} {MediaInfo AudioLanguages}, etc) which could handle this distinction. The only trace which could persist is related to the custom format applied to the release processed by radarr (Media Info can't be used unfortunatly ... ). It'll be very convenient to able to make this distinction persistent outside the radarr DB, within the filename by adding a dedicated label.

I took the example which is the best for me, but "HARDCODED_SUB" is also a case which could benefit from this feature.

**Describe the solution you'd like**
There are multiple way to approach this issue, but the most straight forward would be something like {Custom Format} where it list all Custom Format matching the corresponding release.

That way I'll be able to have "[TRUEFRENCH]" in the filename by adding the naming option {[CUSTOM FORMAT]} and my custom format above just named "truefrench"

**Comment by fryfrog** [comment]
I think it'd also need to be able to parse the custom format *from* this tag too.

**Comment by kiwijunglist** [comment]
Yes I'm very keen on this too.

I have two custom formats
[C_KORSUB] = "KORSUB"
and
[N_C_KORSUB] = ""

I'd like to include that in the filename or file directory too so I can separate out the early Korean releases in my library.

**Comment by hergonoway** [comment]
Please make it happen

**Comment by galli-leo** [comment]
The problem I see, is that we would need to somehow make them standout in the filename, such that Radarr can parse them again. Something like `C_{NAME}_C`.

**Comment by hergonoway** [comment]
Technically if it matches the first time, you may keep the trigger you use in the target filename. So else we mark the file with a dedicated format to match the custom group name, else we add a trigger that resolves the targeted custom format. ( I consider that MediaInfo data is scrubbed by radarr so I'm talking about trigger not in the MediaInfo)

In my first post it would be adding "VFF" to the filename.

**Comment by galli-leo** [comment]
@hergonoway It will not be easy to keep the trigger in the filename, especially, since a lot of custom format stuff is not necessarily in the filename (e.g. filesize). Furthermore, triggers can be in the release name but not the downloaded filename.

**Comment by hergonoway** [comment]
> @hergonoway It will not be easy to keep the trigger in the filename, especially, since a lot of custom format stuff is not necessarily in the filename (e.g. filesize). Furthermore, triggers can be in the release name but not the downloaded filename.

It's a matter of perspective, the point of adding the custom format in the filename is mainly in case of data lost between the downloaded file name and the file renamed, else it can be scrapped again. Of course being able to tag the filename to be more informative outside radarr through the filename is a also a plus.

If I name my cutom format after one of the trigger, it'll be defacto in the filename, so can be scrapped again.

**Comment by henkin67** [comment]
For my point fo view, the easiest way should be to propose the name of the highest custom format which match in the profil furing the grab.
You ensure that you know which custom format group trigger the grab.

**Comment by hergonoway** [comment]
> For my point fo view, the easiest way should be to propose the name of the highest custom format which match in the profil furing the grab.
> You ensure that you know which custom format group trigger the grab.
> By the way there is an other issue related to that topice I think: #3628

I think that you may encounter cases where multiple custom format match, that a bit the downfall of this system since they're priorised between each other instead existing under a weight system with points. But that's another subject :)

Sonarr V3 has quite good approach regarding this "kinda" mechanic of tagging filename with an option "Include Preferred when Renaming" or each Release Profile (<-- which may be assimilated as a custom format). It basically lets you use the variable {Preferred Words} in filerenaming which will be filled accordingly to each match Release Profile with this option enable.

**Comment by Mushin** [comment]
I think this would be quite a useful feature for extending the renaming capabilities beyond what Radarr can detect automatically.

**Comment by Qstick** [comment]
Done in v3

**Comment by hergonoway** [comment]
will current Custom Format or at least its info be kept when switching to v3 ?

**Comment by hergonoway** [comment]
@Qstick : thanks ! this is perfect, it's even a better than Sonarr V3's
