### ISSUE TITLE
Support for alternative movie titles for foreign movies

### ISSUE THREAD

**Issue by onedr0p** [Radarr/Radarr#334]
For example when searching for foreign movies, when you search my name you won't return any results.

Here's an example for the movie Deepwater Horizon:
http://www.imdb.com/title/tt1860357/releaseinfo?ref_=tt_dt_dt#akas

**Comment by galli-leo** [comment]
Not quite sure what you want here? So when you add a new movie that alternative titles are also searched for?

**Comment by aktavor69** [comment]
Or may be, as Couchpotato, the possibility to choose the title from our country.
'Cause Jackett can't search with IMDB url or whatever. So, if I can choose "Deepwater" instead "Deepwater Horizon" for this example, Jackett will grab the release. ATM, it's not working.

**Comment by onedr0p** [comment]
@galli-leo if you are searching for a foreign movie the title of the name is different. If you are searching by title you will never get a release in another language. I propose a way to toggle the movie name to an alternative title after it is added to Radarr, via the movie edit modal.

**Comment by galli-leo** [comment]
@onedr0p Does TMDB support search with alternate titles?

**Comment by onedr0p** [comment]
Yes, you can search by alternative title, I tested it out in radarr and it works. For example search "la vida" will yield "the secret life of pets".

I think we would add a option on the add movie page for the user to select the title they want, but also make it configurable in the edit movie modal.

**Comment by onedr0p** [comment]
We have awhile to think this through, however I don't think adding it would take long.

**Comment by galli-leo** [comment]
Isn't this implemented now?

**Comment by weirdcrap** [comment]
I would like to see this as well, is it implemented? For example when I add the movie ["Arbor Demon"](http://www.imdb.com/title/tt4375268/) it has an alternative (original) title of Enclosure. By default Radarr chose the original title of Enclosure and when it searches it returns a list of completely irrelevant movies, even though I know there are [releases](https://rarbg.to/torrents.php?search=Arbor%20Demon%202016%20720p%20WEB-DL%20XviD%20AC3-FGT) out for this film.

**Comment by foux** [comment]
When a show has alternate names, Sonarr allready search for all the alternate names today. Couldn't Radarr do the same thing (i.e. : launch 3 searches if the movie has 3 alternate names)

**Comment by silentmiles** [comment]
Any chance we can get the priority of this bumped up? I'd think it would be easy to implement, and it's probably affecting a lot of people (those who often search for foreign language films).

**Comment by galli-leo** [comment]
Radarr now searches for up to 5 alternative titles. This should fix this issue.

**Comment by Jakst** [comment]
@galli-leo I wouldn't consider it solved.

I currently run version 0.2.0.870, and when I add the movie **Look Who's Back (2015)** Radarr cannot find it, even though I know it exists on one of my connected trackers in many versions of the correct quality by its original name - **Er ist wieder da (2015)**.

My suggestion is to let the user choose which language should be the primary when searching for the title, and then on top of that search for 5 alternate titles.

I watch a lot of non-american movies, and I always want the movie cataloged in its original language, not in english. Letting the user choose which language is primary (or just respect the **Original title** attribute of TMDB) would both make movies easier to search for and improve the cataloging process.

**Comment by nuhll** [comment]
Guys, you forget the easyiest thing in the world.

Add just one thing, let us add something to the title. Maybe realize it over 

BECAUSE all film on this world, which are not in english, have country added.

Moviename -> if its   english
Moviename german -> if its german
Moviename italia -> if its italia

I would suggest to add one checkbox at "restrictions" "must contain" "german" "Do you want to add this to the title"?

Its that easy. At the moment its pretty much unusable and torrent e.g. is complete broken for foreign users.

**Comment by silentmiles** [comment]
> BECAUSE all film on this world, which are not in english, have country added.

I wish this was true. Unfortunately it's not. There are a LOT of films that have Russian over-dub, which are not indicated in the title. Some other non-English films are not tagged correctly.
