### ISSUE TITLE
Can't access radarr after deleting custom profile

### ISSUE THREAD

**Issue by espilsad** [Radarr/Radarr#3340]
**Describe the bug**
Upon trying to access the WebUI it's only loading.

**Desktop (please complete the following information):**
 - OS: Unraid
 - Browser and Version Chrome, Firefox. I tried incognito mode on both.

**Debug Logs**
[v0.2.0.1217] Marr.Data.DataMappingException: The DataMapper was unable to load the following field: 'Quality' value: '{
  "quality": 5,
  "customFormats": [
    1,
    2,
    3
  ],
  "revision": {
    "version": 1,
    "real": 0
  }
}'. The given key '3' was not present in the dictionary. ---> System.Collections.Generic.KeyNotFoundException: The given key '3' was not present in the dictionary.

**Comment by galli-leo** [comment]
Can you post debug logs of you deleting the custom format? Did you wait for the request to complete when hitting delete? Do you have any more information on how this could have happened? Anyways, the quickest way to get Radarr to load again, is to unfortunately restore from a backup of your Radarr database

**Comment by espilsad** [comment]
Thanks for your answer, I couldn't find it in my logs (only had normal logs enabled) and decided to just restore it (which was way easier than I expected tbh).
After this I didn't delete the profile but changed it so I achieved what I wanted without risking another restore.
