### ISSUE TITLE
Feature Request: Automated deletion after <x> days/months

### ISSUE THREAD

**Issue by LaurenceMillward** [Radarr/Radarr#3341]
Hi, 

Would be great if Radarr had the ability to remove and delete movies automatically as at the moment it's very much a manual task. 

IE: Every week a job runs that removes entries from Radarr and deletes it's files depending on a user inputted number, like 24 months. That way we storage space is automatically managed once it gets into a nice cycle of deleting/downloading. 

Alternatively (and potentially quicker) would be to include the "Date added" to the movie editor so we're able to mark the oldest 15 movies and quickly delete them through there. At the moment there's no way to tell in the movie manager when a film was downloaded or added. 

Purely for storage saving reasons. 

Thanks

**Comment by mtcdood** [comment]
How would you accomplish this with a "script?"

**Comment by LaurenceMillward** [comment]
@mtcdood  - I've got it working in a 2 step process. Step 1 and 2 is fully automated. Last step is manual but takes about 10 seconds. 

1/ In Radarr under Media Management > File Management theres an  "ignore deleted movies" which automatically sets any deleted movies to "UnMonitored". 

2/ In your OS setup a scheduled task to run a command that deletes any folders/files within your movies location thats over X amount of days old.
I use Windows so use this: 
`ForFiles /P "Z:\Movies" /D -365 /C "CMD /C if @ISDIR==TRUE echo RD /Q @FILE &RD /Q /S @FILE"`

What the above does is: Every month a few movies get deleted by Windows, and Radarr automatically marks it as UnMonitored so they don't re-download. Then I just make a habit of going into Radarr once every couple months to "select all" Unmonitored movies and hit delete.

**Comment by mtcdood** [comment]
How do you "select all" in Radarr? I didn't realize there was supposed to be that feature.

**Comment by LaurenceMillward** [comment]
@mtcdood -- Movies > Movie Editor.. In there on the right hand side you can sort by category, so for me "UnMonitored" as these are the ones which have been deleted from the OS. 

At the moment there's 70 in there, hit "Select all", and even though 10 movies display in the list by default it actually selects all 70, or however many you have unmonitored.

**Comment by bakerboy448** [comment]
you can script this easily.

no plans; closing
