### ISSUE TITLE
Import rejected: Not an upgrade for existing episode file(s) (existing:1080p remux, process:2160p remux)

### ISSUE THREAD

**Issue by piejanssens** [Radarr/Radarr#3342]
I did not set the profile to 2160p , instead I did a manual search and picked a 2160p remux version. 
Radarr didn't auto import becuase `Not an upgrade for existing episode file(s)`.

**Comment by fryfrog** [comment]
Can you show us the full error, both from Activity and maybe from logs? A screen shot of the movie's page showing what it thinks it currently is would be nice.

My *guess* would be that it actually imported the 2160p and is trying to do it again.

It might also not be detecting the 2160p correctly or could involve Custom Formats.

But either way, you're going to provide a *lot* more information. And you should start w/ support instead.
