### ISSUE TITLE
New multi-arch docker images by linuxserver.io

### ISSUE THREAD

**Issue by aptalca** [Radarr/Radarr#3343]
Hi, I'm a member of the linuxserver.io team.

I just wanted to give you a heads up that we migrated radarr over to our new builder and we are now providing multi-arch docker images through a single repo at https://hub.docker.com/r/linuxserver/radarr

The separate arm and aarch64 repos have been deprecated.

In the future, users can simply pull `linuxserver/radarr` and it should automatically download the correct docker image for their arch.

Also, our new images are tagged with specific versions, for both the stable and the nightly branch releases.

`linuxserver/radarr:latest` will follow the stable github releases and `linuxserver/radarr:nightly` will follow the nightly branch releases

You can see the concise builds on github: https://github.com/linuxserver/docker-radarr/releases
and all available docker image tags are right here: https://hub.docker.com/r/linuxserver/radarr/tags

Feel free to update the radarr readme to point out the changes.

And lastly, our jenkins now queries the github and radarr.aeonlucid.com endpoints to check for new releases, so we no longer need the webhooks.

Thanks so much and keep up the good work ;)

**Comment by galli-leo** [comment]
Thanks will update readme!
