### ISSUE TITLE
Enable Jackett to submit quoted phrases

### ISSUE THREAD

**Issue by hechz** [Radarr/Radarr#3344]
It would be nice if there were an option to submit a film title to a Jackett tracker as a quoted phrase. 

There are some trackers that do not match on sub-strings via Jackett, but do return them in a manual search.
For example, in Manual search in Jackett '"Love Simon"' returns the correct list of films, but if it is submitted as 'Love Simon' matches containing Love or Simon are returned

**Comment by fryfrog** [comment]
Instead of using imdbid? Or instead of `the+movie+title` or something? Edit your OP to provide more details and re-open. Why would this be nice? Should it be the default or an option? Do you literally want to submit text through Radarr to Jackett? Or?

**Comment by hechz** [comment]
@fryfrog I have updated the OP, but lack rights to reopen the issue

**Comment by fryfrog** [comment]
But it doesn't matter that results for "Love" and "Simon" are returned, because Radarr will parse *those* results for "Love Simon". It does mean there are *more* results, but there is a better chance of something that is almost a match showing up.

Are you seeing a problem due to this behavior?

**Comment by hechz** [comment]
I am, when I search in the Radarr UI for "The History Boys" I get completely un-related results from some trackers.  

I'll PM the details.

**Comment by bakerboy448** [comment]
Closing
v0.2 is no longer being actively developed.

If this is still an issue/request on recent v3 builds, please open a new issue.
