### ISSUE TITLE
Tag-and-deal: a 4k/1080p compromise

### ISSUE THREAD

**Issue by tc60045** [Radarr/Radarr#3345]
Mods: this is a proposal for some work *around* Radarr that involves zero coding by Radarr devs and is intended to be a pragmatic, easy bridge for a common and frustrating issue

Radarr users:  you want 4k and 1080p versions to live in harmony.  Doing this with Plex and Radarr (harmoniously) isn't perfect right now, but keep hope alive: [here](https://github.com/Radarr/Radarr/issues/1910) and [here - roadmap](https://blog.radarr.video/development/update/2018/11/11/roadmap-update.html).

Until then, I'm thinking of a very simple workaround that I may code:
1. Run two instances of radarr via docker (easy; one for 4k, one for <=1080p)
2. Have plex keep each separate, you decide whether or not to share 4k (me=not! cpu killer!)
3. Cron a sync process (borrowing from Radarrsync) that identifies which movies exist in both libraries
4. Add a visual indicator to the poster.jpg in the 1080p library that there exists a 4k version.
5. That's it 
*6. Note that this presumes that (or makes) your 1080p library is your "go to" library, so with this process, you just browse it 100% of the time and let the flags lead you to your 4k library only as indicated.  It stops the back / forth entirely.  This is what I want, but YMMV*

I created a lime green box with text "4k>" in the lower left and added it to the upper right of the existing poster.  Doing this via python is trivial.  The original poster files can be kept (or archived) and undo is trivial.  I made it square to accommodate the "unplayed" triangle that Plex adds -- this will show under the triangle, and of course show when the triangle disappears.  It doesn't indicate that the version *is* 4k, it is intended to indicate that there is a 4k version (so switch libraries, if you are the owner).  

Best: if you don't share your 4k library, you can never get CPU hammered with a transcode
Oh, and this could work for Sonarr, too (help will be needed)

See gorgeous artwork below
![by default 2019-02-01 at 10 13 20 am](https://user-images.githubusercontent.com/2856318/52135833-54761a80-260c-11e9-902a-8fdab0d48835.jpg)
![by default 2019-02-01 at 10 13 48 am](https://user-images.githubusercontent.com/2856318/52135837-5b049200-260c-11e9-9cf6-f9b307724847.jpg)

Thoughts and collaboration welcome

**Comment by fryfrog** [comment]
If you're willing to do development, why not work on adding the native ability to Radarr?

**Comment by galli-leo** [comment]
Feel free to code it and add this info to the wiki page, but this is the wrong place to post this.
