### ISSUE TITLE
 RssSyncService high cpu long duration

### ISSUE THREAD

**Issue by samkatakouzinos** [Radarr/Radarr#3351]
**Describe the bug**
Radarr has high CPU usage and long process time during RSS Sync.
RSS Sync took approximately 45 minutes.

**To Reproduce**
1. Go to web interface '/system/tasks'
2. Go to 'RSS Sync'
3. Click on 'Execute RSS Sync'
4. Observe RSS Sync notification counting up to total, then staying on total
5. Observer high CPU usage (17% in my case)
6. Wait for RSS Sync to finish
7. Observe low CPU usage 

**Expected behavior**
Expect low CPU usage during RSS Sync.
Expect low process time for RSS Sync.

**Screenshots**
High CPU usage: https://imgur.com/uXk9Xdd 
Processing count increment: https://imgur.com/PjMyeGm 
Processing count hang: https://imgur.com/zB862A5

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 1809 17763.253
 - Mono Version: Not applicable
 - Browser and Version: Chrome Stable Version 72.0.3626.81 (Official Build) (64-bit)
 - Version: 0.2.0.1293 - 03 Feb 2019  develop Installed

**Debug Logs** 
Debug Log: https://pastebin.com/n4XwHvRq

**Comment by galli-leo** [comment]
How many movies do you have added to Radarr? What kind of machine is this running on. Do you have other programs open that have high cpu usage?

I strongly recommend turning off debug logging if you are concerned with performance, it is detrimental to RSS sync and the like. Also 17% doesn't seem like a high cpu usage to me, especially if you are running this on a lower end system.

**Comment by samkatakouzinos** [comment]
Q. How many movies do you have added to Radarr? A. 1284 
Q. What kind of machine is this running on. A. Intel i7 3770, 16GB RAM
Q. Do you have other programs open that have high cpu usage? A. No

You say "I strongly recommend turning off debug logging if you are concerned with performance."
I enabled debug log because of your Bug Report Template requirement; "**Debug Logs** Turn on debug logs under Settings -> General and wait for the bug to occur again. **Upload the full log file here (or another site and link it). Issues will be closed, if they do not include this!**" 

Apparently if I don't turn on debug logs the issue will be closed automatically. 
I agree with "I strongly recommend turning off debug logging if you are concerned with performance, it is detrimental to RSS sync and the like"

"Also 17% doesn't seem like a high cpu usage to me, especially if you are running this on a lower end system."
Is an Intel i7 3770, 16GB RAM system a low end system?
A high end system with 1284 movies should take how long? I ask because I have no other system to compare to.
