### ISSUE TITLE
Configurable number of items per page on all list views

### ISSUE THREAD

**Issue by antigravity83** [Radarr/Radarr#3354]
The wanted page only shows 50 movies at a time, regardless of what is selected in the "Page Size" option in UI Settings. 

Is it possible to change how many movies are shown in the wanted section to match the "Page Size" selection in UI Settings?

I'm currently adding and searching movies one letter at a time, and it's difficult and time consuming to do this when only a small number of movies appear on the wanted screen

**Comment by fryfrog** [comment]
I've always wish these pages had configurable pagination, like the main page does.
