### ISSUE TITLE
Radarr unable to import movie Climax

### ISSUE THREAD

**Issue by theotherp** [Radarr/Radarr#3355]
**Describe the bug**
Radarr successfully downloaded NZBs for the movie Climax (2018) but is unable to import the movie. The debug log says:

```
19-2-6 22:17:27.2|Info|MetadataService|Movie folder does not exist, skipping metadata creation
19-2-6 22:17:27.3|Debug|DownloadedMovieImportService|Unknown Movie Climax.2018.1080p.AMZN.WEB-DL.DD5.1.H.264-NTG
19-2-6 22:17:27.3|Debug|Parser|Parsing string 'Climax.2018.1080p.AMZN.WEB-DL.DD5.1.H.264-NTG'
19-2-6 22:17:27.3|Debug|Parser|Movie Parsed. Cl - 2018
19-2-6 22:17:27.3|Debug|ParsingService|Language(s) parsed: 
19-2-6 22:17:27.3|Debug|QualityParser|Trying to parse quality for A Movieimax.2018.1080p.AMZN.WEB-DL.DD5.1.H.264-NTG
19-2-6 22:17:27.3|Debug|ParsingService|Quality parsed: WEBDL-1080p v1 (None)
19-2-6 22:17:27.3|Debug|Parser|Parsing string 'Climax.2018.1080p.AMZN.WEB-DL.DD5.1.H.264-NTG'
19-2-6 22:17:27.3|Debug|Parser|Movie Parsed. Cl - 2018 
```

**Expected behavior**
Should correctly parse the movie. The result was that the movie was downloaded a couple of times because Radarr was unable to import the result after it initiated the download.

Version 0.2.0.1293

**Debug Logs**
See above.

**Comment by fryfrog** [comment]
I bet it hung up on "imax" :(

**Comment by theotherp** [comment]
Yes, that was my theory too.

**Comment by M1kep** [comment]
Having the same issue, can't reproduce it with the various REGEX testers, but IMAX wax my guess too

**Comment by ToXinE** [comment]
![image](https://user-images.githubusercontent.com/6205053/53526283-0dccf080-3ae4-11e9-998c-b7bff81744e4.png)

**Comment by Qstick** [comment]
What build are you on @ToXinE ?

**Comment by ToXinE** [comment]
Radarr Ver. 0.2.0.1293
develop

**Comment by Qstick** [comment]
This was just fixed in nightly so it won't be in a release from a month ago

**Comment by ToXinE** [comment]
no problem thank you! 

Le 28 février 2019 13:54:20 GMT+01:00, "Qstick - notifications@github.com" <github.toxine.9de3121d53.notifications#github.com@ob.0sg.net> a écrit :
>This was just fixed in nightly so it won't be in a release from a month
>ago
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/Radarr/Radarr/issues/3355#issuecomment-468261974

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.
