### ISSUE TITLE
Movie Lookup API "downloaded" always false

### ISSUE THREAD

**Issue by Treverr** [Radarr/Radarr#3359]
**Describe the bug**
Movie Lookup API shows  downloaded : false even though the movie pages badge shows "downloaded"

**To Reproduce**
1. Add an item and download it
2. Query the Movie Lookup API via tmdbid

**Expected behavior**
downloaded should return true for downloaded items

**Screenshots**
<img width="684" alt="screen shot 2019-02-09 at 4 03 03 pm" src="https://user-images.githubusercontent.com/5624521/52527845-449dac80-2c84-11e9-8355-f06ef1b489ae.png">
<img width="1150" alt="screen shot 2019-02-09 at 4 03 15 pm" src="https://user-images.githubusercontent.com/5624521/52527846-46677000-2c84-11e9-9a07-ad8d9303c46f.png">

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] Mac OS
 - Mono Version: [e.g. Mono 5.8] (Only needed under Linux and Mac, found under System -> Status) NA
 - Browser and Version [e.g. chrome, safari] (Only needed for UI issues) NA
 - Version [e.g. 22] 0.2.0.1293

**Debug Logs**
[logs.db.zip](https://github.com/Radarr/Radarr/files/2848407/logs.db.zip)

**Comment by galli-leo** [comment]
This is the expected behaviour
