### ISSUE TITLE
Radarr is running more than one movie refresh / scan at the same time causing dupe downloads

### ISSUE THREAD

**Issue by danjames92** [Radarr/Radarr#3362]
See attached screenshot. Latest nightly 0.2.0.193.

Grabbing the same release more than once to the queue. I've stopped and started my radarr docker to no success.

![firefox_2019-02-11_07-23-54](https://user-images.githubusercontent.com/16107603/52550034-352a7a80-2dce-11e9-9dda-e93a6df0c628.png)

**Comment by fryfrog** [comment]
The refresh doesn't trigger downloads, something else is the source of your problem. You need good ol' support.
