### ISSUE TITLE
Cannot add movie through API: error 409, constraint failed: Movies.Images (NOT NULL)

### ISSUE THREAD

**Issue by truenicoco** [Radarr/Radarr#3363]
**Describe the bug**
I cannot add a new movie using the API

**To Reproduce**
I'm using the `requests` python library like this:
```
requests.post(
    'http://localhost:7878/api/movie?apikey=xxx',
    json={
        'title': 'Get Out',
        'qualityProfileId': 7,
        'titleSlug': 'get-out-419430',
        'tmdbId': 419430,
        'year': '2017',
        'rootFolderPath': '/medias/Films'})
```
This returns a 409 error with this payload:
`{'message': 'constraint failed\nNOT NULL constraint failed: Movies.Images'}`

**Expected behavior**
The movie should be added… or maybe the wiki API information is outdated?

**Desktop (please complete the following information):**
 - OS: debian testing
 - Mono Version: 5.18.0.240 (Debian 5.18.0.240+dfsg-1 Fri Jan 18 17:30:45 UTC 2019)
 - Version: 0.2.0.1293

**Debug Logs**
```
19-2-11 10:06:50.5|Trace|Http|Req: 546 [POST] /api/movie?apikey=(removed)
19-2-11 10:06:50.5|Trace|Owin|SQLite warning (284): automatic index on AlternativeTitles(MovieId)

19-2-11 10:06:50.5|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId)

19-2-11 10:06:50.5|Trace|ConfigService|Using default config value for 'pathsdefaultstatic' defaultValue:'True'
19-2-11 10:06:50.5|Info|MovieService|Adding Movie [Get Out (2017)][, 419430] Path: [/medias/Films/Get Out (2017)]
19-2-11 10:06:50.5|Trace|Owin|SQLite error (1299): abort at 42 in [INSERT INTO [Movies] ([TmdbId],[ImdbId],[Title],[CleanTitle],[SortTitle],[Status],[Overview],[Monitored],[MinimumAvailability],[ProfileId],[LastInfoSync],[Runtime],[Images],[TitleSlug],[Website

19-2-11 10:06:50.5|Trace|NzbDroneErrorPipeline|Handling Exception
19-2-11 10:06:50.5|Trace|Http|Res: 546 [POST] /api/movie?apikey=(removed) 409.Conflict (65 ms)
19-2-11 10:06:50.5|Debug|Api|[POST] /api/movie?apikey=(removed) 409.Conflict (65 ms)
```
I don't understand what is happening here. There seem to be a conflict. Was the movie partially added by my previous attempts? It appears neither in the UI nor in the movie list return by `GET /api/movie`.

Any help is greatly appreciated. I am trying to set up a simple python script to automagically add movies by actors, directors, writers and producers and will be happy to share it when it works.

**Comment by RhinoRhys** [comment]
I've replied on reddit too but for completeness please double check the Wiki and post all the required arguments.

> Required:
> 
> title (string)
> qualityProfileId (int)
> titleSlug (string)
> images (array)
> tmdbId (int)
> year (int) release year. Very important needed for the correct path!
> path (string) - full path to the movie on disk or rootFolderPath (string) - full path will be created by combining the rootFolderPath with the movie title

You're not giving it the images array, which can be sourced from a movie/lookup endpoint
