### ISSUE TITLE
Large TMDb lists only partly imported with NetImport Sync

### ISSUE THREAD

**Issue by jusher00** [Radarr/Radarr#3365]
**Describe the bug**
I have a TMDb list with >2000 movies. When running NetImport Sync, only a fraction of that is added to my library. I'm pretty sure that the problem lies within the TMDb v3 API, which only returns 1000 movies for a list, no pagination possible. An upgrade to v4 would solve the problem, as that version supports pagination.

**Comment by geogolem** [comment]
I once did some work getting tmdbv4 Authentication working .. My intention was to add TMDB private lists support which was something the v4 api supported, but the v3 api did not (if i remember correctly)

Anyway, I havent looked at this in a while so i dont remember much about it. I need to rebase the branch and see what its state was of if the tmdb api changed at all

but I remember running into problems with the tmdb v4 API and I had to actually reach out to TMDB and they fixed them.

My branch is here: https://github.com/geogolem/Radarr/tree/tmdbv4Auth

note - this branch did not touch the netimport list functionality but was a first step in getting private lists support added. 

Based on this issue it looks like changing to tmdb api v4 is something that should be done (at some point) and when that happens, private list support can probably be handled at the same time....

**Comment by jusher00** [comment]
Since recently, the v3 API has only been returning 500 items of a list. Hoping the switch to v4 is on somebody's radar (pun intended), as this might now be affecting more people than before.

**Comment by 123Venom** [comment]
Don't hold your breath.  Recently TMDb started dropping titles from custom lists and refuse to respond on forum about the issue. v3 or v4 api both with issues.  Simple test I did with v4 api and "object_ids" responds with 64 items in list for "118017" but detailed response cuts it to 32 items.  Starting to believe Tivo owned TMDb is useless rubbish and break more than they fix.
