### ISSUE TITLE
{radarr_movie_id} variable wont work in CURL

### ISSUE THREAD

**Issue by antigravity83** [Radarr/Radarr#3368]
I have a post processing script that converts a recently downloaded AVI or MP4 to MKV, and I need Radarr to "RescanMovie" once the script has completed to make sure the correct extension appears in Radarr. 

According to the WIKI, Post Processing Variables can be used in a CURL API command, and I'm trying to use {radarr_movie_id} to tell Radarr which movie to "RescanMovie".

Here is the CURL command that I'm trying to use:

`curl -s http://localhost:XXXX/radarr/api/command&apikey=XXXX -d '{name: "RescanMovie", movieId: "$radarr_movie_id}"}' -H "Content-Type: application/json" -X POST`

However I'm getting the following debug error in Radarr:

> "message": "Could not convert string to integer: ${radarr_movie_id}

When I substitute the ${radarr_movie_id} variable with a hardcoded ID, it works fine. But the variable doesn't. 

The error is stating that the variable isn't an integer. But shouldn't it be returning an integer?

**Comment by galli-leo** [comment]
You’re missing an opening bracket

**Comment by antigravity83** [comment]
That was just a typo when typing it into GitHub. The bracket isn't the issue. 

The command works when entering in a hardcoded ID, so the syntax etc is correct. 

But it seems the Post Processing variable doesn't work as described in the wiki (where it says it can be used to populated an API command. )

**Comment by galli-leo** [comment]
@antigravity83 Ah i see now, you cannot use the double quotes, else it counts as a string

**Comment by antigravity83** [comment]
Thank you, works perfectly now.
