### ISSUE TITLE
Radarr is not marking download as "Downloaded" if external renamer is used.  

### ISSUE THREAD

**Issue by Satalink** [Radarr/Radarr#3369]
**Description:**

Whatever justification you may think quantify the necessity to avert this function, it needs to be UNDONE and RECTIFIED IMMEDIATELY.   

:: I can tolerate ignorance, but stupidity is another thing entirely.

**Radarr Version:**

**Mono Version:**

**Debug Logs:**

# Do not remove anything from your logs and post the full logs! If not everything fits in here use a service like https://pastebin.com to upload them.

**Comment by fryfrog** [comment]
It'll work properly if your external rename tool leaves the file in the download folder for Radarr to import it, just make sure your downloader doesn't mark it as finished until after the renamer runs.

Alternatively, tune the naming Radarr uses to what you want and stop using the external renamer.

*If* the external renamer puts it into the folder Radarr expects, the daily-ish refresh will find it eventually.

If this doesn't satisfy, you're welcome to develop a good solution and make a pull request. Or another tool might work better for you, maybe Couch Potato.
