### ISSUE TITLE
Option to enable plex notification on rename only

### ISSUE THREAD

**Issue by tkdrob** [Radarr/Radarr#3372]
Sometimes plex adds my movies on notification before the renaming is complete. This leaves periods in the movie name on plex which does not change even after radarr has renamed them. I am using moviedb agent as the first priority. I think allowing people to only notify plex when the movie has been renamed would be a good feature to have. Another idea is an option to add a delay from when the movie has been downloaded before plex is notified

0.2.0.1217

**Comment by fryfrog** [comment]
Sounds like you're pointing Plex at your download folder? Or your download and library are the same? The file that Radarr/Sonarr copies/moves into place will already be named correctly when it gets there.
