### ISSUE TITLE
Download directly to destination without move/copy/rename

### ISSUE THREAD

**Issue by Terebi42** [Radarr/Radarr#3373]
I (as well as others I believe) would like to have radarr download directly to the library destination folder, without any move/copy/hardlink/rename.  This facilitates long term seeding and space maintenance.  This feature is available in other competing projects like flexget etc.

For very large libraries, where there are multiple root directories, spread across multiple drives, the current implementation is very lacking.  The same download directory is used for all movies downloaded by radarr, meaning that space cannot be distributed across multiple drives. Additionally, if the library path is not on the same drive as the download drive, hardlinking doesn't work, and space is consumed twice. Even if both locations are on the same drive to allow hardlinking, having two "copies" of the content complicates management. If you wish to recover the space, you have to go delete it from both locations.

So I propose to make this change (me personally, I will code this, and submit the PR), assuming you do not have philosophical objection to the feature being implemented. (At least for qbittorrent, I may leave implementation of other download clients)

* Add a new IDirectDownloadClient interface with an enabled flag
* Add a radio button to the download client configuration screen to enable the feature, describing the caveats below
* In subclasses of TorrentClientBase, implement IDirectDownloadClient, and if enabled, when adding a download to the client, set the download directory to the library destination (root folder + movie name etc) 
*For QBittorrent in particular, this would require modifying the IQBittorrentProxy interface and classes to implement the call from the webapi. Similar changes would be needed for each download client : https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-Documentation#set-torrent-location
* In (???) (Need help identifying proper place) when download completed, if IDirectDownload is set, skip move/copy and just import the file directly in current location (similar to manual import)

Caveats : 
* No rename (although this could in fact be implemented, it causes way too much complexity, and breaks cross seeding)
* For single file movie torrents, everything is as normal
* For multiple file (folder) torrents, Radarr will create a folder for the movie, and the torrent's own folder will be nested inside.  
* Upgrade/propers would live side by side in the library folder, not be replaced

Thoughts?

**Comment by fryfrog** [comment]
This is a *huge* departure from how Sonarr and Radarr work. If you're willing to work with the devs and do it in a way they approve of, you'd make some number of people quite happy. I'd talk to the Sonarr and Radarr devs on IRC / Discord quite a bit to see how they think it could work and if they'd merge it if written.

But you're going to have to do a *really* good job and *everything* about Sonarr / Radarr is going to be working against you.

And I don't think you need *this* solution to actually solve your problem. All you really need to do is make sure the download client sends to the same disk the show / movie lives on and then use hard links. You should be able to achieve this a few different ways already.

You could also use a merge file system, but then hard links don't work.

I'm skeptical this can be done well enough that it would get merged into Sonarr/Radarr. :/

**Comment by Terebi42** [comment]
@galli-leo  : @fryfrog suggested I ping you to get feedback on what you think of this idea.    I am also on discord if you would prefer to discuss there.
