### ISSUE TITLE
Support for Tixati, because of tracker issues with QBT/libtorrent

### ISSUE THREAD

**Issue by dday4thedeceiver** [Radarr/Radarr#3374]
It would be great to have support for Tixati, because the otherwise leading tracker QBT as well as Deluge (both using libtorrent), fails to connect to many trackers Tixati has no issues with, resulting in much fewer connections and lower download speeds.

**Comment by galli-leo** [comment]
Unfortunately, it does not seem that Tixati has an API, so this will be impossible.
