### ISSUE TITLE
Webhook Improvements

### ISSUE THREAD

**Issue by tidusjar** [Radarr/Radarr#3375]
**Describe the solution you'd like**
What would be very useful is if we could have options for the following in the Webhook section:
 - Movie Added
- Movie Deleted
- Movie Monitored Change

**Describe alternatives you've considered**
None, I think webhooks would be the most sensible way to do it, but I am open to other suggestions

**Additional context**
The reason for this request is so Ombi wouldn't have to poll Radarr to get updates, Ombi could consume the webhook for any updates to content making the process simpler and cleaner.

**Comment by Qstick** [comment]
@tidusjar were you going to try to use SignalR instead of this?

**Comment by tidusjar** [comment]
No plans yet. I know that is an option though. Feel free to close this if that is your solution
