### ISSUE TITLE
Clicking on unmonitored, shows none, then refresh and filter bar disappears so now stuck on "start up" page

### ISSUE THREAD

**Issue by mikec25** [Radarr/Radarr#3377]
**Describe the bug**
Clicking on unmonitored, shows none which is true but then if the page is refreshed or reopened when browser restarts then the filter bar disappears and shows the "start up" page "_You must be new around here, before you start adding movies you may want to check out the following links on our wiki: "_
I have to add a new movie to force the UI back and show all movies.

**To Reproduce**
As described above.

**Desktop (please complete the following information):**
 - OS: win10
 - Browser : FF, Chrome

**Comment by galli-leo** [comment]
Known issue, will be fixed with new ui.
