### ISSUE TITLE
Movie File Not Found

### ISSUE THREAD

**Issue by tokra** [Radarr/Radarr#3379]
**Describe the bug**
I am using custom renaming format: 
Standard Movie Format: {Movie Title}
Movie Folder Format: ({Release Year}) {Movie Title}

However when i want to Bulk Import my previous movies, it says Movie File Not Found.

**Screenshots**
![image](https://user-images.githubusercontent.com/2188084/53288666-869e1680-378b-11e9-9c29-c82a9620177a.png)

![image](https://user-images.githubusercontent.com/2188084/53288673-94539c00-378b-11e9-92a1-f7eb906e516f.png)

**Desktop (please complete the following information):**
 - OS: Unraid 6.5.0
- Version: 0.2.0.1217 
- Branch: develop
- Mono Version: 5.18.0.240 (tarball Wed Jan 16 09:13:03 UTC 2019)

**Comment by tokra** [comment]
One thing I found is that if file is with original name, its found: 
![image](https://user-images.githubusercontent.com/2188084/53288965-eeeef700-378f-11e9-868f-3dcc9427e529.png)

Then what is the sense of RENAMING when renamed file cannot be imported ?
Thanks

**Comment by galli-leo** [comment]
Don't trust bulk import, it uses a less resource intensive mechanism. But you should probably add the year in the filename just to be sure. Furthermore, I strongly advice you to put the quality in the filename, as Radarr will have no way to determine that and probably just set it to unknown or WEB-DL. See the wiki for how to do that automatically.
