### ISSUE TITLE
Some sort of scene group guide, or ranking

### ISSUE THREAD

**Issue by simonk83** [Radarr/Radarr#338]
We were talking in chat and thought it would be really handy to integrate some sort of ranking or suggestions for scene groups.

Eg:  Sparks - usually quick but middling quality
Hdmaniacs - Generally larger file sizes and good quality
Etc

Give people a little guide to help with eventual integration with a preferred words list or something similar.

Would take a little maintaining, and not sure if there's a similar listing somewhere on the net (probably).

**Comment by vortexrap** [comment]
Related to #227

**Comment by Qstick** [comment]
Out of scope for Radarr, someone is free to start something like this in the wiki, we’d probably be open to linking to it.
