### ISSUE TITLE
Radarr - Mono Consuming CPU Resources Constantly

### ISSUE THREAD

**Issue by bigverm23** [Radarr/Radarr#3386]
**Describe the bug**
2 instances of Radarr is causing the top 2 processes running on my Ubuntu 18 machine to run at approx 60% of cpu combined constantly.

**To Reproduce**
View system running processes from Ubuntu desktop.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/17554438/53300848-46d24000-381a-11e9-8dc9-5abccf69b67e.png)

**Desktop (please complete the following information):**
 - OS: Docker-Compose 1.23.2 build 1110ad01
 - Mono Version: 5.18.0.240 (tarball Wed Jan 16 09:13:03 UTC 2019)
 - Version 0.2.0.1293

**Debug Logs**
19-2-24 09:57:18.1|Debug|Api|[PUT] /api/config/host: 202.Accepted (71 ms)
19-2-24 09:57:18.2|Debug|SabnzbdProxy|Url: http://192.168.1.99:8085/api?mode=get_config&apikey=(removed)&output=json
19-2-24 09:57:18.4|Debug|Api|[GET] /api/health: 200.OK (0 ms)
19-2-24 09:57:41.5|Debug|Parser|Parsing string 'Tron 1982 1080p Bluray x265 10Bit AAC 5.1 - GetSchwifty.mkv'
19-2-24 09:57:41.5|Debug|Parser|Movie Parsed. Tron - 1982 
19-2-24 09:57:41.5|Debug|ParsingService|Language(s) parsed: 
19-2-24 09:57:41.5|Debug|QualityParser|Trying to parse quality for A Movie 1982 1080p Bluray x265 10Bit AAC 5.1 - GetSchwifty
19-2-24 09:57:41.5|Debug|ParsingService|Quality parsed: Bluray-1080p v1 (x265v2, x265)
19-2-24 09:57:41.5|Debug|Parser|Parsing string 'Kevin Hart What Now 2016 1080p 10bit BluRay 6CH x265 HEVC-30nama'
19-2-24 09:57:41.5|Debug|Parser|Movie Parsed. Kevin Hart What Now - 2016 
19-2-24 09:57:41.5|Debug|ParsingService|Language(s) parsed: 
19-2-24 09:57:41.5|Debug|QualityParser|Trying to parse quality for A Movie 2016 1080p 10bit BluRay 6CH x265 HEVC-30nama
19-2-24 09:57:41.5|Debug|ParsingService|Quality parsed: Bluray-1080p v1 (x265v2, x265)
19-2-24 09:57:41.5|Debug|Parser|Parsing string 'La La Land 2016 (1080p Bluray x265 HEVC 10bit AAC 7.1 Tigole)'
19-2-24 09:57:41.5|Debug|Parser|Movie Parsed. La La Land - 2016 
19-2-24 09:57:41.5|Debug|ParsingService|Language(s) parsed: 
19-2-24 09:57:41.5|Debug|QualityParser|Trying to parse quality for A Movie 2016 (1080p Bluray x265 HEVC 10bit AAC 7.1 Tigole)
19-2-24 09:57:41.5|Debug|ParsingService|Quality parsed: Bluray-1080p v1 (x265v2, x265)
19-2-24 09:57:41.5|Debug|Parser|Parsing string 'Jurassic World - Fallen Kingdom (2018) (1080p BluRay x265 HEVC 10bit AAC 7.1 Tigole)'
19-2-24 09:57:41.5|Debug|Parser|Movie Parsed. Jurassic World - Fallen Kingdom - 2018 
19-2-24 09:57:41.5|Debug|ParsingService|Language(s) parsed: 
19-2-24 09:57:41.5|Debug|QualityParser|Trying to parse quality for A Movie (2018) (1080p BluRay x265 HEVC 10bit AAC 7.1 Tigole)
19-2-24 09:57:41.5|Debug|ParsingService|Quality parsed: Bluray-1080p v1 (x265v2, x265)
19-2-24 09:57:41.5|Debug|SabnzbdProxy|Url: http://192.168.1.99:8085/api?mode=queue&start=0&limit=0&apikey=(removed)&output=json
19-2-24 09:57:41.5|Debug|SabnzbdProxy|Url: http://192.168.1.99:8085/api?mode=history&start=0&limit=30&category=movies&apikey=(removed)&output=json
19-2-24 09:57:41.6|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (3 ms)
19-2-24 09:58:01.7|Debug|Api|[GET] /api/health: 200.OK (0 ms)
19-2-24 09:58:01.8|Debug|Api|[GET] /api/health: 200.OK (0 ms)
19-2-24 09:58:02.2|Debug|Api|[GET] /api/diskspace: 200.OK (492 ms)
19-2-24 09:58:02.2|Debug|Api|[GET] /api/diskspace: 200.OK (477 ms)
19-2-24 09:58:02.6|Debug|Api|[GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc&filterKey=level&filterValue=Error&filterType=equal: 200.OK (61 ms)
19-2-24 09:58:02.6|Debug|Api|[GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc&filterKey=level&filterValue=Error&filterType=equal: 200.OK (37 ms)
19-2-24 09:58:04.9|Debug|Api|[GET] /api/log/file: 200.OK (8 ms)
19-2-24 09:58:04.9|Debug|Api|[GET] /api/log/file/radarr.debug.txt: 200.OK (9 ms)
19-2-24 09:58:07.7|Debug|Api|[GET] /api/log/file/radarr.debug.txt: 200.OK (1 ms)
19-2-24 09:58:33.4|Debug|Api|[GET] /api/log/file: 200.OK (2 ms)
19-2-24 09:58:33.5|Debug|Api|[GET] /api/log/file/radarr.debug.txt: 200.OK (1 ms)
19-2-24 09:58:34.7|Debug|Api|[GET] /api/log/file: 200.OK (1 ms)
19-2-24 09:58:34.7|Debug|Api|[GET] /api/log/file/radarr.debug.txt: 200.OK (1 ms)
19-2-24 09:58:40.6|Debug|Api|[GET] /api/log/file/radarr.txt: 200.OK (5 ms)
19-2-24 09:58:53.1|Debug|Api|[GET] /api/log/file/radarr.debug.txt: 200.OK (5 ms)
19-2-24 09:59:01.2|Debug|Api|[GET] /api/log/file/radarr.debug.txt: 200.OK (1 ms)

**Comment by galli-leo** [comment]
How many movies do you have? How many download clients do you have? How many downloads do you have? What system is this running on? How many indexers? Have you tried turning debug logging off?

30%CPU usage is pretty ok imho, if you have a not so beefy system as well as a lot going on in Radarr.

**Comment by bigverm23** [comment]
500 movies, 2 download clients per Radarr instance, 0 running downloads at the time of high CPU usage (thats 60% CPU total during this instance), roughly 12-15 indexers.

**Comment by arch1mede** [comment]
I also have the same problem, I have radarr/sonarr and both combined are running 60+% cpu usage
