### ISSUE TITLE
Auto-update failed, folder empty

### ISSUE THREAD

**Issue by d2dyno** [Radarr/Radarr#339]
I triggered the update to 0.2.0.182 from 0.2.0.166. Web ui never came back up. I went to check the directory of Radarr's installation and only 'UI' and 'NzbDrone.Update' folders exist, with few files in each. What went wrong? I had installed radarr as a service, could that be it? Anyways, grabbed latest pre-compiled zip, put it into the install folder and all is working now.

The log doesn't offer much:
17-1-18 19:16:20.7|Info|InstallUpdateService|Downloading update 0.2.0.182
17-1-18 19:16:22.3|Info|InstallUpdateService|Verifying update package
17-1-18 19:16:22.5|Info|InstallUpdateService|Update package verified successfully
17-1-18 19:16:22.5|Info|InstallUpdateService|Extracting Update package
17-1-18 19:16:23.8|Info|InstallUpdateService|Update package extracted successfully
17-1-18 19:16:23.8|Info|BackupService|Starting Backup
17-1-18 19:16:24.0|Info|InstallUpdateService|Preparing client
17-1-18 19:16:24.0|Info|InstallUpdateService|Starting update client C:\WINDOWS\TEMP\radarr_update\Radarr.Update.exe
17-1-18 19:16:24.0|Info|InstallUpdateService|Radarr will restart shortly.
17-1-18 19:16:24.0|Info|InstallUpdateService|Updater Arguments: 1928 C:\WINDOWS\TEMP\radarr_update C:\Users\d2dyn\Radarr\Radarr.Console.exe 
17-1-18 19:16:24.9|Info|NzbDroneServiceFactory|Attempting to stop application.
17-1-18 19:16:24.9|Info|OwinHostController|Attempting to stop OWIN host
17-1-18 19:16:25.1|Info|OwinHostController|Host has stopped
17-1-18 19:16:25.1|Info|NzbDroneServiceFactory|Application has finished stop routine.
17-1-18 19:16:25.1|Info|ConsoleApp|Exiting main.

**Comment by galli-leo** [comment]
There should be an UpdateLogs folder. Can you take a look at the newest file?

**Comment by d2dyno** [comment]
Sure. I copied what appears to be the relevant portion of the log:

http://pastebin.com/8xEBmsn1

**Comment by edru** [comment]
Mine doesn't seem to work either, nor does it delete the previous file when I manually tell it to download a better quality copy.

(at work or i'd get some logs)

**Comment by onedr0p** [comment]
Does this still error for you? Did u try the latest version?
