### ISSUE TITLE
Allow selecting more than 1 filter on Movies list

### ISSUE THREAD

**Issue by Junglur** [Radarr/Radarr#3391]
**Is your feature request related to a problem? Please describe.**
The list of movies has filters for All, Monitored, Unmonitored, Missing, Released, Announced and In Cinemas and it only allows you to select one at a time. This is annoying when I want to see the missing movies that have been released so that I can check to see if they need a manual search or something.

**Describe the solution you'd like**
This could be done two ways. Make it so you can select multiple filters at a time, like a toggle on and off option for each filter.
Or split the options out into two sections "Monitored, Unmonitored, Missing" and "Released, Announced, In Cinemas" That way I can select for example that I want to see Missing movies that have been Released.

![image](https://user-images.githubusercontent.com/20409470/53305226-ad6f6080-38e3-11e9-8ba6-b7dc1428f55b.png)

**Comment by Qstick** [comment]
Same as #2011
