### ISSUE TITLE
Stuck after log in

### ISSUE THREAD

**Issue by turkeyphant** [Radarr/Radarr#3397]
**Describe the bug**
Unable to load Radarr site in web browsers. The login page will come up immediately but after hitting log in it will endlessly stay on the loading bubbles going from side to side. Nothing in my settings has changed.

Have tried other browsers.
Have tried clearing cache.
Have tried incognito.
Have stopped/restarted service multiple times.

**To Reproduce**
As above.

**Expected behavior**
Load any of the screens after log in.

**Screenshots**

**Desktop (please complete the following information):**
 - Qnap qpkg
 - QMono Version: 4.8.1.0
- Jackett 0.7.1437

**Comment by turkeyphant** [comment]
What further information do you need?

**Comment by galli-leo** [comment]
The issue template was not filled out correctly.

Radarr Version and Debug Logs are missing

**Comment by turkeyphant** [comment]
Sorry how can I provide that information without being able to access the Web UI?

It's the latest version of Radar as I updated about a week ago.

There's no sign of any log files without going into Radar settings. There's nothing in /share/CACHEDEV1_DATA/.qpkg/Radarr/

**Comment by galli-leo** [comment]
If log files are not there, then you need to look somewhere else. Anyways, looks like either your database file got corrupted (see wiki pages for more info) or you really do have a full disk (could be that the config is on something else, IIRC some nas have a ramdisk for that). Anyways definitely a support issue.

**Comment by turkeyphant** [comment]
Is the intended behaviour really an infinite loading screen with no indication of error or way of accessing logs?

**Comment by galli-leo** [comment]
If the app crashes completely as it did in your case, yes, how else would you handle that? Also you can still access the logs and most of the times that‘s actually the preferred way of retrieving them.

**Comment by turkeyphant** [comment]
It didn't completely crash. I guess I'm used to start up scripts having error catching and user feedback and if the web UI works enough to load and show a blank version to be able to show the actual version or even some troubleshooting...
