### ISSUE TITLE
[Feature Request] Allow to omit categories filter in indexer queries for newznab/torznab 

### ISSUE THREAD

**Issue by AndrewSav** [Radarr/Radarr#3398]
**Is your feature request related to a problem? Please describe.**
Currently, the list of categories senе to newznab/torznab indexers is [hardcoded](https://github.com/Radarr/Radarr/blob/4aec27890c3b37f27e5ca427bdc2f38314bb5185/src/NzbDrone.Core/Indexers/Newznab/NewznabSettings.cs#L64). Unfortunately some sites place movie content in whatever category they fancy. This leads to Radarr not being able to find content on such websites. 

**Describe the solution you'd like**
I would like an option to skip the `cat` portion of the indexer query, which will return results unfiltered by category.

**Describe alternatives you've considered**
Ask the websites to tag the movie with different categories? Unlikely to succeed. Put a proxy between radarr and the indexer that would strip the `cat` part of the query? Could work but will only help myself. Nothing else comes to mind.

**Additional context**
Sonarr has a field that allows to specify categories. It somewhat alleviate this problem in Sonarr, yet it does not remove it completely, since Sonarr does not allow suppressing the `cat` part of the query either. So you end up entering a loooooong line of all possible categories there. Please let me know if I could clarify my problem further.

**Comment by galli-leo** [comment]
You can enter categories in Radarr as well. You can probably just search all of them if you leave it blank, but yeah else you just have to add all categories

**Comment by AndrewSav** [comment]
@galli-leo the form to add those indexers does not have the category field. Could you please clarify where I can enter them?
![image](https://user-images.githubusercontent.com/658865/53473829-57134500-3ad0-11e9-9d5f-b381bbfa2d14.png)

**Comment by oatssss** [comment]
Some indexers have releases that don't get put into a category, how do we include these? In Jackett, I can see some results without a category, and Radarr is unable to see them if I manually search using the same query.
