### ISSUE TITLE
[BUG] API for adding Custom Formats to existing movieFile

### ISSUE THREAD

**Issue by DirtyCajunRice** [Radarr/Radarr#3400]
**Describe the bug**
When using `PUT /api/movie`
I am appending a dict to the customFormats list to update pre-existing movies with relevant tags. This works in the UI as it will show the tag, but re-pulling the same movie shows it as an empty list again and a disk refresh removes the tag. When it is entered from the UI it stays as expected

**To Reproduce**
Here is my quick script snippit
https://bin.cajun.pro/oyijaciwud.py

**Expected behavior**
for it to apply the changes permanently

**Screenshots**
Gif of it happening, starting after the PUT request https://bin.cajun.pro/images/VRGep6FqGd.gif

**Desktop (please complete the following information):**
Docker install.

**Debug Logs**
even on trace the logs show nothing.

**Comment by galli-leo** [comment]
IIRC you need to post to /api/moviefile

**Comment by DirtyCajunRice** [comment]
happen to have an example? (nothing in the wiki about that endpoint) ill dig through the code in the meantime to see if i can sort it out myself.

**Comment by galli-leo** [comment]
@DirtyCajunRice Just look at the chrome dev console and see what Radarr itself does

**Comment by dmwyatt** [comment]
@DirtyCajunRice There's info in #3270
