### ISSUE TITLE
Preferred score

### ISSUE THREAD

**Issue by Supergamer1337** [Radarr/Radarr#3401]
**Current problem with preferred tags**
The thing with preffered tags, is that they only matter when at first download files (or atleast it is for me). So, if my preferred release group uploads a little later than other, radarr picks the other release, and doesn't upgrade to the preferred release.

**My recommended solution**
Perhaps you could add something like a "preferred score" so that different releases have this score to go from. So, when a release with a higher score is released, it will download it instead.

Quality always take precidence.

**Comment by galli-leo** [comment]
Use custom formats
