### ISSUE TITLE
DB corrupting - System.Data.SQLite.SQLiteException (0x80004005): database or disk is full

### ISSUE THREAD

**Issue by turkeyphant** [Radarr/Radarr#3402]
**Describe the bug**
It appears the database keeps corrupting rendering the install of Radar unuseable. I can load the log in screen but afterwards it's stuck on the moving dots.

Before the issue started Radarr itself reported 7TB free on the disk. There are no quotas or other limits in place. The old DB file was larger in size than this one before it corrupted. The corrupting is resulting in the "database or disk is full" error and various error 500s through the API.

**To Reproduce**
1.Using Radarr, can't log in one day
2. Complete fresh install of Radarr
3. Update Mono
4. Delete DB and reset config.xml
5. Add movies or otherwise use
6. In my case I added ~800 movies from disk
7. Logs started showing errors and could no longer access Radarr.

**Example log errors**
```
19-3-1 18:11:50.8|Error|CommandExecutor|Error occurred while executing task RefreshMovie

[v0.2.0.1293] System.Data.SQLite.SQLiteException (0x80004005): database or disk is full
database or disk is full
```

```
19-3-1 18:11:35.0|Info|DiskScanService|Completed scanning disk for Line of Sight
19-3-1 18:11:35.0|Error|EventAggregator|CalendarModule failed while processing [MediaCoversUpdatedEvent]

[v0.2.0.1293] System.Data.SQLite.SQLiteException (0x80004005): database or disk is full
database or disk is full
```

```
19-3-1 18:38:43.8|Error|NzbDroneErrorPipeline|[GET /api/movies/bulkimport]

[v0.2.0.1293] System.Data.SQLite.SQLiteException (0x80004005): database or disk is full
database or disk is full
```

```
[Trace] Http: Res: 2119 [GET] /api/movies/bulkimport?id=1&folder=%2Fshare%2FCACHEDEV1_DATA%2Fvideo%2Ffilms%2F&page=1&per_page=15&sort=sortTitle&direction=NaN: 500.InternalServerError (718 ms)
[Debug] Api: [GET] /api/movies/bulkimport?id=1&folder=%2Fshare%2FCACHEDEV1_DATA%2Fvideo%2Ffilms%2F&page=1&per_page=15&sort=sortTitle&direction=NaN: 500.InternalServerError (718 ms)
[Trace] Scheduler: Pending Tasks: 0
[Fatal] NzbDroneErrorPipeline: Request Failed
-sh: [Fatal]: command not found
[/share/CACHEDEV1_DATA/.qpkg/Radarr/Home/.config/Radarr] #
<.config/Radarr] # [v0.2.0.1293] System.Data.SQLite.SQLiteException (0x80004005): database or disk is full
-sh: syntax error near unexpected token `('
<.config/Radarr] # database or disk is full[Fatal] NzbDroneErrorPipeline: Request Failed
-sh: database: command not found
[/share/CACHEDEV1_DATA/.qpkg/Radarr/Home/.config/Radarr] #
<.config/Radarr] # [v0.2.0.1293] System.Data.SQLite.SQLiteException (0x80004005): database or disk is full
-sh: syntax error near unexpected token `('
[/share/CACHEDEV1_DATA/.qpkg/Radarr/Home/.config/Radarr] # database or disk is full
```

**Expected behaviour**
Used to work perfectly for months. Can handle small 4MB db 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 7, macOS 10.11.6, Android
- Mono Version: 5.18.0.240 (tarball Mon Feb 4 20:36:13 CET 2019)
 - Browser and Version: Chrome, Firefox, Safari, IE)
 - Version 0.2.0.1293
 - AppData directory: /share/CACHEDEV1_DATA/.qpkg/Radarr/Home/.config/Radarr
- Startup directory: /share/CACHEDEV1_DATA/.qpkg/Radarr/Radarr

**Debug Logs**
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/2920684/radarr.debug.txt)
[radarr.trace.txt](https://github.com/Radarr/Radarr/files/2920693/radarr.trace.txt)

**Comment by galli-leo** [comment]
This still isn't a bug in Radarr, but rather a support issue. Since this is an exception in the SQLite library, there could maybe be a bug there, but that's also extremely unlikely.

A few likely causes are:

1. Config is on a different disk (e.g. ramdisk) than other stuff and that has ran out of space.
2. Disk is failing and config is on a bad sector.
3. logs.db is the corrupt one and you didn't delete that
4. Config is on a network drive and sqlite fails to correctly write the journal files.

**Comment by turkeyphant** [comment]
Have been to support over the last few days and they are clueless why it's happening or how to find out more from the logs.

1. Config and all files all on the same disk with 7TB free.
2. Volume is ext4 and has recently been checked and verified.
3. Only get DB errors when updating movies not logs
4. As above, config and everything else all local.
