### ISSUE TITLE
Does not recognize / import movies unless they are on "Wanted" list

### ISSUE THREAD

**Issue by Ltek** [Radarr/Radarr#3403]
**Problem***
If you try to Manually Import a ripped movie, you cannot unless it is already in the "Wanted" list. 

**Expected behavior**
Radarr should be "smart", not dumb... if it doesnt see the movie as 'wanted' it should do a quick internet search to do a match and ask the user if this is the movie they want to import. 

Why a bug you ask...
1. Radarr clearly has function to do this already built-in (since it searches and renames files all the time) 
2. I'll assume this should be working. If it was not implemented, I'll assume this was an oversight of a basic feature that was intended to be built-in. If the intent is not to do this, please explain why not. I'm sure 99.9% of users would want this built-in for if/when they dont have something on the wanted list.

**Comment by fryfrog** [comment]
This is how Wanted -> Manual Import do. The Bulk Import is more like what you want.

**Comment by fryfrog** [comment]
This is also a known thing and I'm 99% sure there are other issues or feathub requests about this, including for Sonarr too. Find one of them and thumbs up it instead.
