### ISSUE TITLE
add movies search generates broken "already exists" links for foreign movies

### ISSUE THREAD

**Issue by kaso17** [Radarr/Radarr#3405]
**Describe the bug**
If a movies is already in the movie database using a foreign language profile the "Already Exists" links generated by the "add movie" search won't work (if the movies foreign title differs from the English one). The add movie search will always use the english title to generate the title slug/"Already Exists" URL. The English title will result in a 404 error

#1196 might be related but clearing cache/cookies/restarting doesn't work.

**To Reproduce**
I'll use the movie Annihilation (English title)/Auslöschung (German title) as an example.
1. Add the Movie "Annihilation" with a profile using Language=German
2. The movie will be added with German title including a german title slug (`/movies/auslschung-300668` in this case).
3. now go to add movie and search the movie again. The Add buttons won't be available now. instead it shows a "Already exists" button/link. This link uses the english title slug (`/movies/annihilation-300668`)
4. Clicking on the link will result in a 404 error.

**Expected behavior**
Working already exists links.

I would suggest to extract the TMDB ID from the URL and use that for the /movies/ lookup instead of the complete title+TMDB.

**Desktop (please complete the following information):**
 - OS: ArchLinux
 - Mono Version: 5.18
 - Browser and Version: chrome 72
 - Version: 0.2.0.1293

**Debug Logs**
shouldn't be needed

**Comment by galli-leo** [comment]
Known issue and will be fixed when the new ui comes / languages are reworked.

**Comment by nicklayb** [comment]
Is there any workaround for this? I have a lot of movies in such cases.

**Comment by r5464y75** [comment]
Also keen to know of a workaround, please.  Even a way to delete altogether
