### ISSUE TITLE
Parse error when click add for specific movie

### ISSUE THREAD

**Issue by pbrink231** [Radarr/Radarr#3407]
**Describe the bug**
A specific movie, RBG (2018), giving a log error when clicking either + or search icon.
error:
Request Failed: Error parsing boolean value. Path 'addOptions.searchForMovie', line 1, position 1451.

**To Reproduce**
1. Go to 'Add Movie'
2. Search 'RBG'
3. Click + or search for movie RBG (2018)
4. button blips for half a second.  No pop ups.  Go to log to see error

**Expected behavior**
Do what it normally does.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Mono Version: 5.18.0.240 (tarball Wed Jan 16 09:13:03 UTC 2019)
 - Browser and Version: Chrome, Version 72.0.3626.119
 - Version: 0.2.0.1293

**Debug Logs**
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/2932596/radarr.debug.txt)

**Comment by galli-leo** [comment]
Works fine for me, make sure you clear your cache and cookies.

**Comment by pbrink231** [comment]
its strange and only happens externally.  I think the api gets disconnected and the cache makes it look like its all working.
