### ISSUE TITLE
Custom Formats leads to existing movies being snatched

### ISSUE THREAD

**Issue by DominicMe** [Radarr/Radarr#3410]
Ever since I added some Custom Formats Radarr is snatching existing releases. These releases comply with Custom Formats. The issue is that Radarr should not be snatching these releases at all Regardless of Any Custom Formats. All duplicate snatches are for items marked as downloaded.

It is very similar to this issue: https://github.com/Radarr/Radarr/issues/3172 My setup is simpler though.

**To Reproduce**
1. Add custom Formats
2. Wait or run Downloaded Movies Scan

**Expected behavior**
Radarr should not snatch existing releases regardless of Custom Formats.

**Desktop (please complete the following information):**
 - OS: Fedora 19
 - Mono Version: 4.8.1 (Stable 4.8.1.0/22a39d7 Wed May 3 05:57:18 UTC 2017)
 - Browser and Version: Chrome
 - Version: 0.2.0.1318

**Debug Logs**
Logs literally only show the releases as being searched for and snatched same as any other release.

**Comment by galli-leo** [comment]
Make sure you set the cutoff correctly as well as use the movie editor to rescan all custom formats.

**Comment by galli-leo** [comment]
The recommendation is to use a different profile for custom formats for new movies.
