### ISSUE TITLE
Feature request: change to radarr_eventtype

### ISSUE THREAD

**Issue by Alexdc-12** [Radarr/Radarr#3411]
Hi
I have written a custom script for use with notifications. For the on download/upgrade I am not able to differentiate between a new download or an upgrade event.
Would it be possible to add 'Upgrade' as the radarr_eventtype for a quality upgrade and leave 'download' for a new download event
Thanks

**Comment by darthShadow** [comment]
You can use the `radarr_isupgrade` flag for differentiating between a Download or an Upgrade event. I just noticed that its missing from the wiki but it is indeed populated since I have been using it for quite some time now. It's basically a boolean value indicating whether its an Upgrade or not.

**Comment by Alexdc-12** [comment]
That's brilliant, exactly what I needed!

**Comment by darthShadow** [comment]
I just added it to the wiki page too.
