### ISSUE TITLE
Downloading multiple copies

### ISSUE THREAD

**Issue by seanhouser** [Radarr/Radarr#3412]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Mono Version: [e.g. Mono 5.8] (Only needed under Linux and Mac, found under System -> Status)
 - Browser and Version [e.g. chrome, safari] (Only needed for UI issues)

**Debug Logs**
Turn on debug logs under Settings -> General and wait for the bug to occur again. **Upload the full log file here (or another site and link it). Issues will be closed, if they do not include this!**

**Comment by seanhouser** [comment]
I'm doing my best to learn this system but it's very confusing. I'm not sure what is needed.

**Comment by seanhouser** [comment]
Oh and now

**Comment by seanhouser** [comment]
Having a blast with this system

**Comment by seanhouser** [comment]
Aaaaand closed

**Comment by seanhouser** [comment]
I'd love to delete this issue since I'm learning the system. Help text tells me under "Notifications" on the right I should have a delete option. I do not. I have an Unsubscribe option only. I suppose this learning thread is forever.

**Comment by Qstick** [comment]
It’s forever 😁
