### ISSUE TITLE
Custom Format Codec Templates [Request]

### ISSUE THREAD

**Issue by RhinoRhys** [Radarr/Radarr#3419]
Please could the custom format templates for x264 and x265 be updated from `(X|H)` to `(X|H(|.))` to also include h.264 and h.265 by default. 

Also as I'm here I think that {quality} should also be in the renamer by default to ensure less experienced users do not lose valuable metadata.

Many thanks for all your hard work.

**Comment by fryfrog** [comment]
I think `(X|H)\.?` is actually clearer and simpler, if it is going to be updated... might as well be to that instead.
