### ISSUE TITLE
Missing codeset 28595

### ISSUE THREAD

**Issue by turtlehead** [Radarr/Radarr#342]
After installing the newest version, 0.2.0.182, whenever I try to search for a movie, I get the following error:
Error occured while searching for new movies.: Encoding 28595 data could not be found. Make sure you have correct international codeset assembly installed and enabled.

with backtrace:
System.NotSupportedException: Encoding 28595 data could not be found. Make sure you have correct international codeset assembly installed and enabled.
  at System.Text.Encoding.GetEncoding (System.Int32 codepage) [0x0025f] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.Text.Encoding.GetEncoding (System.String name) [0x00015] in <8f2c484307284b51944a1a13a14c0266>:0 
  at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.ToUrlSlug (System.String value) [0x00008] in <a2331ea161da4a55bc4b2369420f04d8>:0 
  at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.MapMovie (NzbDrone.Core.MetadataSource.SkyHook.Resource.MovieResult result) [0x00036] in <a2331ea161da4a55bc4b2369420f04d8>:0 

This is fedora 25 and mono 4.6.2.  Previous versions of Radarr worked fine

**Comment by turtlehead** [comment]
After digging around, found a mono-locale-extras package that fixed this

**Comment by BlueBackbite** [comment]
For whatever reason, got the same issue (different encoding data number) and mono-locale-extras package does not exist in Debian stretch.

Came here after after googling. What fixed the error for me was installing mono-complete.

**Comment by eNeRGy164** [comment]
For those that only want to resolve this dependency, it's part of libmono-i18n-other4.0-cil in Debian

**Comment by ragmanii** [comment]
The package I had to install on Ubuntu was: libmono-i18n4.0-all

**Comment by twdkeule** [comment]
On Rasbian I had to install libmono-i18n4.0-all, because libmono-i18n-other4.0-cil was not sufficient

**Comment by ChristopherJHart** [comment]
I observed this issue after updating Mono to 6.8.0 to troubleshoot a separate Sonarr issue on CentOS 7. I resolved it by installing the `mono-complete` library via `yum` and restarting the Radarr service.

```
[root@media logs]# yum list installed | grep mono-complete
mono-complete.x86_64                  6.8.0.123-0.xamarin.2.epel7     @download.mono-project.com_repo_centos_
```
