### ISSUE TITLE
Do NOT download or process ISO or VOB

### ISSUE THREAD

**Issue by pven** [Radarr/Radarr#3428]
Sometimes it happens that a ISO (or DVD-VOB) is downloaded. Can I somehow configure I don't wan't that? I know there is a DVD-option in the profile, but when I am right that has nothing to do with ISO.

**Comment by Xandernomics** [comment]
https://github.com/Radarr/Radarr/wiki/How-to-make-sure-Radarr-doesnt-snatch-Full-BluRays
