### ISSUE TITLE
Low size Bluray-2160p encodes do not get picked up in search for torrents

### ISSUE THREAD

**Issue by WiseMMO** [Radarr/Radarr#3429]
I do not know if it's a bug or a configuration error on my part, but I'm on a fresh install of the latest version of Radarr and I remember having this same issue a while back.

 

It could be an issue on torrentapi's side, but here's the deal:

Some 4K torrents do not get picked up by Radarr from RARBG, for example:

I see this: https://i.imgur.com/ltvmFM6.png

 

This is a bluray ENCODE (Not a full bluray, not a remux, not a web-dl) for Mortal Engines in 4K HDR x265. It's 12GB and I really couldn't care less to get a remux for a 4K movie, so that's what I want Radarr to monitor for.

 

But whenever it auto searches, it only picks up those selected as "Remux-2160p" or SOME "Bluray-2160p" that also have very high file size.

Manual search isn't different, it scans successfully but only shows this:

https://i.imgur.com/LFbQviY.png

 

As you can see they are ordered by file size and the 12GB torrent I showed earlier present on RARBG isn't picked up. This happens with every movie I search in 4K.

I don't have filters set up right now, my quality size slider for 2160p-Bluray is set to 9GB minimum and I have web-dls disabled.

 

So if we follow this logically, Radarr searches for torrents by tags inside the name and then it categorizes them.

If Remux-2160p is a BluRay Remux (An untouched bluray video and audio tracks MUXED inside one video container) A Web-Dl is the classic web downloaded video file

 

Then what is Bluray-2160p? It MUST be referring to encodes and I think this is correct, because I got one encode showing, but it's... 80GBs? Although when I download it, the name of the torrent changes to FULL UHD BLURAY

 

https://i.imgur.com/uA2EI5n.png <- See "COASTER"

 

(so the bluray in files format)

So is Bluray-2160p a FULL BLURAY instead? That would mean encodes are completely ignored, but why should that be? You can find easily all 1080p encodes, why not 2160p?

 

It seems like it only picks up a certain file size for 4K blurays and ignores those lower than it even tho it's actually in 4K.

This is a huge bummer because it would force me to download 30-50-80GBs for a 4K remux movie because it can only picks up those.

Can anyone help me with this? So far I haven't been able to find a solution anywhere.

**Comment by WiseMMO** [comment]
I was able to fix this using Jackett and the default categories. This is still very weird, why does Jackett show all torrents from a search but Jackett doesn't?

**Comment by galli-leo** [comment]
IIRC the last time I looked at this, rargb wasnt returning certain releases for whatever reason from their API. Could be because they are tagged without an IMDBid or because that category is not part of movies somehow.

**Comment by galli-leo** [comment]
Yep, just took a look, that movie is not returned by the API, so nothing we can do.
