### ISSUE TITLE
Allow Additional Movie Naming Options For Movie Folders

### ISSUE THREAD

**Issue by vortexrap** [Radarr/Radarr#343]
Currently, Radarr limits the renaming convention of Movie Folders to {Movie Title}{Release Year}{IMDB ID}. I think it would be beneficial to all to expand that list to match the Standard Movie Format which also includes Quality, Release, Media Info.

Sonarr had the same limitation - but it makes sense for TV Series, as the underlying seasons could have varying qualities. Movies generally have one movie with one quality profile per folder.

This feature is very useful for media management, as I am able to scan through my movies and see what qualities, resolution, file source, etc. from the folder.

**Comment by galli-leo** [comment]
We have already discussed this at length on our discord. In the near future we wont be supporting that as it does not make much sense. Everytime a new quality is downloaded a new folder would have to be created, which doesn't make much sense.

**Comment by galli-leo** [comment]
One thing you could do is create root folders with the quality.
