### ISSUE TITLE
How to not create sub-folder for each movie Movie

### ISSUE THREAD

**Issue by ferllings** [Radarr/Radarr#3430]
Hello,

More a question than a bug.
How can I not create a sub folder for each movie, when it is copied on the final destination?

Thanks

**Comment by hotio** [comment]
You can't.

**Comment by galli-leo** [comment]
Duplicate issue

**Comment by ferllings** [comment]
Sorry for the duplicate. Which one is it? I couldn't find it.

**Comment by galli-leo** [comment]
#153

**Comment by ferllings** [comment]
Thanks, I now understand the reason for this subfolder.
