### ISSUE TITLE
Add ability to identify movie based on title and imdb id

### ISSUE THREAD

**Issue by skydiverscott** [Radarr/Radarr#3433]
**Is your feature request related to a problem? Please describe.**
I am trying to import a library in the naming format of Movie Title, The.tt123456789\Movie Title, The.tt123456789.mkv and cannot.

**Describe the solution you'd like**
Add a setting for use with Bulk Movie Import that can use the IMDB id in the folder or file name to allow bulk import of movies missing the movie year

**Describe alternatives you've considered**
I considered using Couchpotato to rename my library adding the year to the folder name but that would mean I would lose 8 years of watching history in Kodi

**Comment by galli-leo** [comment]
We already do this, however you need a year in the folder and filename to get Radarr to parse movies in the first place. Kodi shouldn‘t loose your watch history because of renaming files.
