### ISSUE TITLE
No result with yggTorrent & Jackett

### ISSUE THREAD

**Issue by jfperrin** [Radarr/Radarr#3439]
**Describe the bug**
Hello, here is my issue. On jacket when I manualy search for ***Harry Potter and the Chamber of Secrets*** it gives 60 results. 

On radarr in log files i've got this :
```
19-3-22 15:39:11.8|Info|NzbSearchService|Searching 1 indexers for [Harry Potter and the Chamber of Secrets]
19-3-22 15:39:18.1|Info|DownloadDecisionMaker|No results found
```

Files returned in jackett are under the file limits, and quality is ok. 

The version of radarr is Ver. 0.2.0.1293 
The version of mono is 5.18.0.268 (tarball Tue Mar 12 14:22:34 UTC 2019)

**Comment by jfperrin** [comment]
The problem seems to come from the query send to jackett

This return no result
```https://media.atraxi.eu/jackett/api/v2.0/indexers/yggtorrent/results/torznab/api?t=search&cat=102183,102145,2000,2010,2020,2030,2040,2045,2050,2060&extended=1&apikey=removed&offset=0&limit=100&q=harry%20potter%202%20chamber%20secrets%202002``` 

this one does
```
https://media.atraxi.eu/jackett/api/v2.0/indexers/yggtorrent/results/torznab/api?t=search&cat=102183,102145,2000,2010,2020,2030,2040,2045,2050,2060&extended=1&apikey=pil38zflaajo9gdejigyee5f2j4t2sag&offset=0&limit=100&q=potter```

**Comment by DamienLevel** [comment]
I have the same problem with Spider-Man: Into the Spider Verse...
The request made with Radarr is "spider man into spider verse 2018" but I've no result.
If I add "the" in the request "spider man into **the** spider verse 2018", I have results.

Is it a Radarr issue ?

Radarr Version : 0.2.0.1293
Mono Version : 5.18.0.240 (tarball Wed Jan 16 09:13:03 UTC 2019)

**Comment by galli-leo** [comment]
https://github.com/Radarr/Radarr/wiki/Common-Problems#jackett-shows-more-results-than-radarr-when-manually-searching there are some plans to make this work better
