### ISSUE TITLE
Missing root folder

### ISSUE THREAD

**Issue by pven** [Radarr/Radarr#3441]
I have no idea where it comes from, but in System I got a red remark tellig me: 'Missing root folder: /volume1/remote/media/Movies/_Classic'. But that folder exists, and it is accessible. The wiki points to https://github.com/Radarr/Radarr/wiki/Health-checks#missing-root-folder , that is about Series !? Andit does not help me, since my folder exists.

How can I get rid of this error?

Version: 0.2.0.1293
Mono Version: 5.8.0.108 (tarball Sat Feb 24 10:26:45 UTC 2018)
NAS: Synology DS214+
OS: Synology (DSM, newest)

**Comment by pven** [comment]
And now the error is gone. Is this fixing itself?

**Comment by pven** [comment]
Hm, the same error is back. Help? :)

**Comment by pven** [comment]
It did not pop up for some days. Lets just close it ...

**Comment by mishac** [comment]
There's a couple of issues here:
1) This error keeps coming up periodically for me, even though I"ve done all the steps in the wiki.  I want to avoid mucking in the sqlite db manually but I'm willing to if I have to!

2) The wiki steps are still written for Sonarr, so need to be updated to avoid confusion.
