### ISSUE TITLE
Sort by Rating (IMDB/TMDB Critic/Viewer)

### ISSUE THREAD

**Issue by brunott** [Radarr/Radarr#3443]
I would like to know if there is any plan to implement a “Sort by (Critic/Viewer) Rating” option in the Movies section ?
I would love to sort that way to know what Movies are so bad I can just nuke them, thereby saving valuable space and maintaining a fairly decent set of movies.

**Comment by tiedtoastar** [comment]
Wouldn't it be better to prevent movies you don't want downloaded from being downloaded in the first place?

**Comment by brunott** [comment]
Well, yes, of course and at the same time it would be convenient, when you hit a list of 2000 items and start running out of disk space, that one can just sort by rating and select a list of those at the lower end of the scale for deletion.
I can’t say I always select movies of good viewing quality (my fault I guess) and I don’t spend hours maintaining the list although sort by rating would help.

**Comment by fryfrog** [comment]
I don't think genre or rating are even stored, so I doubt this would happen w/o a lot of work. I'll let someone else close it though.

**Comment by galli-leo** [comment]
Duplicate issue and already planned.
