### ISSUE TITLE
Trumped torrent- Download Freeleech after cutoff has been met

### ISSUE THREAD

**Issue by steamyRayV** [Radarr/Radarr#3448]
On PTP, downloads get trumped and if not checked daily, the freeleech period for the new torrent will be missed. Then you have a torrent that you can't get ratio back for. Is there a way to get Radarr to download the updated torrent while it is freeleech, even though the quality cutoff for that movie has been met? If this already exists, I'm sorry I didn't figure it out on my own. I figure I can't be the only one.

Thanks!

**Comment by fryfrog** [comment]
Nothing already does this and if PTP doesn't make that data available via API, I don't see how it could be reasonably possible. It also sounds like a fair amount of work to support this for just *one* indexer. I'll leave it open, but I wouldn't expect a whole lot from this. :/

**Comment by steamyRayV** [comment]
Thanks for responding! Here's what I was thinking.
Radarr already recognizes PTP freeleech and some others. 
Basically it would be exactly like "Download propers", except with freeleech that meets the cutoff.
"Download freeleech at cutoff quality even if cutoff has been met."

**Comment by galli-leo** [comment]
You can use custom formats for that.

**Comment by steamyRayV** [comment]
Thanks, that's great news. Sometimes the source gets upgraded several times in the first week of a release. I think I just need a little push in the right direction with this though. The wiki says, "Upgrading stops when at least one Custom Format match is above the profile cutoff." 
So if I set my quality cutoff to "Bluray-1080p" and Custom Format Cutoff to a profile with only "I_GFreeleech," Seems like that will only upgrade my source a single time since the freeleech tag has been matched. What I would like is to keep upgrading the source until I un-monitor it. 

If I get this going, I will relay the way to do it to PTP forum. The only response I got was a person who does this manually in Radarr, not caring about freeleech. That user didn't care about ratio but would also benefit by automating the source upgrade that they already manually do, in my opinion. A new freeleech seems to always designate an upgrade, so it's not JUST ratio at stake.

Sorry if I'm being a bother with this, and thanks again.

**Comment by fryfrog** [comment]
I agree, I don't think custom formats can accomplish this because I don't think the trumped release will come down the pipes and free leech doesn't *always* indicate a trumped release. And of course, the first free leech would meet the custom format cutoff anyway.

I don't think there is any graceful way to accomplish this, but if you want to try... hop on Discord and work w/ whomever is around to create a custom format.
