### ISSUE TITLE
See Status or be able to filter in Movie Editor

### ISSUE THREAD

**Issue by rterblanche** [Radarr/Radarr#345]
Way to easily change the monitored status of multiple movies. 

In the Movie Editor I cannot see which which movies have already been download. Might even be help if I can see the status in the Movie Editor or just be able to Sort or Filter in the Movie Editor by status.

I can then multi select the movies I want to update.

Please use our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by onedr0p** [comment]
You can see downloaded quality in movie editor, should be sufficient for now until a new UI gets released.
