### ISSUE TITLE
Updating an existing movie deletes all images - unnecessarily?

### ISSUE THREAD

**Issue by jordy1955** [Radarr/Radarr#3450]
Updating an existing movie deletes all images - unnecessarily?

In the wiki I found  this: The Import Process

Radarr does a number of checks to verify that the download is acceptable for importing, including:
Sample file check (run time is longer than 90 seconds)
Upgrade for existing movie file (if any)
Not being unpack by the download client (UNPACK in SABnzbd)
Enough free space exists at the destination
**Once a file has passed all those checks it is imported, if there is an existing file it is deleted,** otherwise the movie file is moved and renamed (according to your naming rules). Once the file has been moved it removes the source folder as long as it is less than 70MB in size). If no files are imported nothing is deleted.

I have discovered that Radarr not only deletes the existing Movie file but also deletes any images - poster, landscape, etc. 
 Is this intended? if so why, Radar is only upgrading the existing movie of the same name, It shouldn't be necessary to do anything with pre-downloaded images - .nfo and .xml files yes because they need to be update anyway but posters etc - I don't see why.

Can deletion of images in the Import process be an option, or removed altogether please?

**Radarr Version: 0.2.0.1293**

**Mono Version: ? Windows 10pro (v1809)*

See time stamp : 19-3-25 03:38:43.2
Deletion of Movie and associated files for Bruce Almighty (2003)

**Debug Logs:**

[radarr.0.txt](https://github.com/Radarr/Radarr/files/3007306/radarr.0.txt)

thanks  jordy

**Comment by feerlessleadr** [comment]
This has been an active bug for a while. See the following:

https://github.com/Radarr/Radarr/issues/2639

https://github.com/Radarr/Radarr/issues/3209

**Comment by jordy1955** [comment]
Just to be specific here, based on the comments on #2639 and #3209.

radarr is deleting  the following files:
logo.png
poster.jpg
landscape.jpg
fanart.jpg

However, it might be important to note that it does not do this for all movie upgrades. About 50% of the time it leaves the image files alone, but when it does delete them, it deletes all image files as above.

thanks

**Comment by feerlessleadr** [comment]
That hasn't been my experience. Every time I have a movie upgraded, all of the related image files are deleted.

**Comment by Qstick** [comment]
Closing for #3209

**Comment by AwesomeAustn** [comment]
Why was this closed? It's not fixed. It's annoying. I'm glad I have the recycle bin setup.

**Comment by AwesomeAustn** [comment]
This is still happening and I'm on version 3.0.0.3964.

**Comment by bakerboy448** [comment]
@AwesomeAustn please don't comment on closed, 1.5yr old issues
