### ISSUE TITLE
Manual search on main page

### ISSUE THREAD

**Issue by jiantjon** [Radarr/Radarr#3451]
**Is your feature request related to a problem? Please describe.**
It is frustrating to have to go into the details of each movie to perform a manual search. 

**Describe the solution you'd like**
It would be nice to have a manual search button next to the auto-search button on the main 
movie list.

**Describe alternatives you've considered**
I can't think of any alternative solutions. I currently go into each movie's detail page and perform the search there. 

**Additional context**
None.  Please feel free to contact me if you have any questions or need me to describe this further.

**Comment by bakerboy448** [comment]
No plans for this at this time.
