### ISSUE TITLE
Post-processing with radarr, nzbget and nzbToMedia

### ISSUE THREAD

**Issue by elmero1** [Radarr/Radarr#3454]
I use radarr, nzbget and the nzbToMedia scripts.
In radarr I can add the movies and the download in nzbget works (connection between radarr and nzbget is fine). After the download is finished, the post-processing script (nzbToRadarr) will be executed and I can see the message:
nzbToRadarr: Radarr: Successfully post-processed <Movie-Name>
Post-process-script nzbToMedia/nzbToRadarr.py for <Movie-Name> successful

But in Radarr the movie is still missing. I've a problem between nzbget, radarr and nzbToMedia. Do you have an idea, where exactly the problem is? Which log files do you need for analysis? 
Thanks in advance.

**Comment by fryfrog** [comment]
Literally don't use nzbToMedia, it isn't needed.
