### ISSUE TITLE
Incorrect year on some titles, causes failure to map downloads.

### ISSUE THREAD

**Issue by schmittimillian** [Radarr/Radarr#3455]
**Describe the bug**
Some movies are listed with the incorrect year, which causes the automatic search to reject releases as ``Failed to map movie, expected year <INCORRECT_YEAR>, but found <CORRECT_YEAR>``.  
I've seen this happen on multiple movies, but this report will just have one release as an example.
The movie this bug report is in relation to is _The Grudge 3_ (2009). 

**To Reproduce**
1. Add movie through Radarr (Add Movies > Search for movie > Click ``+``). Notice it has **correct year** in this search.
2. Go to page for movie in Radarr
3. See the release year next to the title as the **wrong year**.
4. Click on the ``Search`` tab.
5. See that it finds releases in the Search, but flags them with the&nbsp;![image](https://user-images.githubusercontent.com/22268708/55087658-d02a9b80-5080-11e9-963b-50075d32e65a.png) symbol.
6. Hover over this to see the error message.

**Expected behavior**
Movies should have their correct release year, or if it's unclear what the correct release year is, it should have multiple possible years that it will accept.

**Screenshots**
Movie with correct year in movie search:  
![image](https://user-images.githubusercontent.com/22268708/55090304-40d3b700-5085-11e9-868d-f082c8978e47.png)

Movie with incorrect year on movie page, also shows search finding releases, but not mapping the year:
![image](https://user-images.githubusercontent.com/22268708/55090757-0a4a6c00-5086-11e9-82fd-af731fa447c5.png)

Error message for why it sees it as an invalid release:
![image](https://user-images.githubusercontent.com/22268708/55087800-09630b80-5081-11e9-80e8-45a679820379.png) 

**Desktop (please complete the following information):**
 - OS: Windows Server 2019 Datacenter (Desktop Experience) Version 1809 Build 17763.379
 - Version Radarr Version 0.2.0.1293

**Debug Logs**
the full log is attached here: [radarr.txt](https://github.com/Radarr/Radarr/files/3013917/radarr.txt), but the relevant information is extracted and pasted below:  
```
19-3-27 11:16:26.0|Info|Bootstrap|Starting Radarr - C:\ProgramData\Radarr\bin\radarr.console.exe - Version 0.2.0.1293
19-3-27 11:16:26.4|Info|Router|Application mode: Service
19-3-27 11:16:26.6|Info|MigrationLogger|*** Migrating data source=C:\ProgramData\Radarr\nzbdrone.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
19-3-27 11:16:26.7|Info|MigrationLogger|*** Migrating data source=C:\ProgramData\Radarr\logs.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
19-3-27 11:16:26.8|Info|OwinHostController|Listening on the following URLs:
19-3-27 11:16:26.8|Info|OwinHostController|  http://*:7878/
19-3-27 11:16:27.0|Info|NancyBootstrapper|Starting NzbDrone API
19-3-27 11:16:27.7|Info|CommandExecutor|Starting 2 threads for tasks.
19-3-27 11:16:41.1|Info|MovieService|Deleted movie [The Grudge 3 (2008)][tt1053859, 1977]
19-3-27 11:17:01.8|Info|MovieService|Adding Movie [The Grudge 3 (2009)][, 1977] Path: [H:\movies\The Grudge 3 (2009)]
19-3-27 11:17:01.9|Info|RefreshMovieService|Updating Info for The Grudge 3
19-3-27 11:17:02.0|Info|MediaCoverService|Downloading Poster for [The Grudge 3 (2009)][, 1977] http://image.tmdb.org/t/p/original/vYCVXrk7K5BaFdz3kxdsC8515gQ.jpg
19-3-27 11:17:02.5|Info|DiskScanService|Scanning disk for The Grudge 3
19-3-27 11:17:02.5|Info|MovieScannedHandler|[The Grudge 3] was recently added, performing post-add actions
19-3-27 11:17:02.5|Info|MediaCoverService|Testing: NzbDrone.Core.Messaging.Commands.CommandQueueManager, 1521
19-3-27 11:17:02.6|Info|MetadataService|Movie folder does not exist, skipping metadata creation
19-3-27 11:17:03.9|Warn|MediaCoverMapper|File C:\ProgramData\Radarr\MediaCover\1521\fanart.jpg not found
19-3-27 11:17:08.3|Info|NzbSearchService|Searching 1 indexers for [The Grudge 3]
19-3-27 11:17:10.9|Info|DownloadDecisionMaker|Processing 6 releases
19-3-27 11:17:28.7|Info|RssSyncService|Starting RSS Sync
19-3-27 11:17:37.0|Info|DownloadDecisionMaker|Processing 972 releases
```

**Comment by geogolem** [comment]
tagging for future reference:
this may be related to: https://github.com/Radarr/Radarr/issues/3353

**Comment by bnflix** [comment]
Just saw this issue again with Starfish.2019.720p.AMZN.WEB-DL.DDP5.1.H.264-NTG. The tracker has the corrected date, but the filename itself is wrong. Since those filenames will never change, maybe the search should include the year metadata from the site rather than the filename.

**Comment by bnflix** [comment]
For now here's a workaround:

1.  Delete the movie in Radarr
2.  Go to the movie in IMDB and find the year on the same line near the top where it lists certification, length, genre, etc. (not the year right after the title)
3. Go to the movie at themoviedb.org and click on Edit (you have to be logged in). Then, click on Release Information and add the release that matches the filename you are trying to download. It seems to usually be a film festival or something. On the note I have been adding the film festival name. 
4. Save, and try to add the movie again in Radarr.

**Comment by joaonl** [comment]
Same issue is occuring now for The Gentlemen. I removed a wrong row in themoviedb.org but it didn't solve it.

**Comment by sub-atomic** [comment]
Same issue for The Women (1939). Radarr thinks it should be 1938 even though it's 1939 on every site.

**Comment by danharner1** [comment]
I am seeing this also, Force Download does not work either. 
I was able to change the year in tmdb and eventually the movie search changed from 2019 to 2020 (in cinemas) but as soon as i add the movie, it updates to 2019 again. I've cleared my browser cache and attempted again with no changed results. I am seeing about 10 movies doing this same thing.

**Comment by danharner1** [comment]
After a few hours, I went back to the same movie to try again and it seems to have updated. I was now able to add it with the correct year and it did not update to the incorrect year after being added. Perhaps just some patience is what it needed.

**Comment by jacquesdupontd** [comment]
It happens nearly on every movie i try to download, often the movie was release in cinema in 2019 and released in torrent in 2020. This is so annoying, Radarr is loosing all its purpose if i have to manually search and force download. I find it amazing that you cannot tell it to not include the year in the search for matches or even tell it to include a search for the year before and the year after. Maybe i'm missing something ?

**Comment by austinwbest** [comment]
Give v3 a spin. If you still have an issue, open your own ticket and fill in the template with the information it asks for and we can go from there.

**Comment by jacquesdupontd** [comment]
So i tried v3 and i don't see much of a difference except the UI. I'll create a ticket but i'm not sure this can be classified as issue, it is more of a requested feature. Thought it could be possible with the custom format but you in fact you can't tell it to accept a date that is a year early or in the future, you can only affinate selection from what has already been validated, thus having the correct Year of theatrical release and the Year of torrent release.

**Comment by ta264** [comment]
The handling of years has been improved in v3. If you have some logs of it not working open a new issue please.

**Comment by jacquesdupontd** [comment]
I don't understand how they have been improved in my case, if you search for a movie that on imdb is XXX 2019 and that the results in the torrent are XXX 2020 then it will "failed to map movie, expected year 2019, but found 2020".

**Comment by austinwbest** [comment]
K, well if you are having an issue then I'd recommend doing what was suggested and opening a ticket that is current and related to your situation. Thanks.

**Comment by jacquesdupontd** [comment]
Ok Thanks guys. So i created an issue https://github.com/Radarr/Radarr/issues/5264
