### ISSUE TITLE
Add filter to Wanted list

### ISSUE THREAD

**Issue by brimur** [Radarr/Radarr#3456]
Rather than scrolling page to page could you add a filter/ search bar to the Wanted page similar to the search bar at the top so that we can type a name, check its box and then type the next name, check its box etc etc. It would be handy for searching collections like Fast and Furious, so you could just type Furious which would then list all the movies and you could check all the boxes and hit search.

**Comment by fryfrog** [comment]
Personally, I think this would clutter the UI w/o adding much benefit. The Wanted -> Missing and Cutoff Unmet is about mass searches and doesn't really even need to be used much.

**Comment by Dnkhatri** [comment]
@qstick I don't see the wanted tab on my aphrodite install am I missing some setting. 

Linux mint 19
Version 2.0.0.2067
Mono Version 6.0.0.334
DB Migration 156

**Comment by Qstick** [comment]
Nope, it's all built into one view. There is no seperate page
