### ISSUE TITLE
Any idea about porting code to .Net Core

### ISSUE THREAD

**Issue by jindaxia** [Radarr/Radarr#3457]
https://docs.microsoft.com/en-us/dotnet/core/porting/

https://stackify.com/net-core-vs-net-framework/

**Comment by fryfrog** [comment]
If you're interested in helping, maybe hop on the Sonarr and Radarr Discord and talk to the developers. If you're just wondering about when/if they're going to do it... my guess is who knows.

**Comment by galli-leo** [comment]
Yes we have discussed this but it would take a lot of effort, so we will look at it in the future.
