### ISSUE TITLE
MediaInfo: Audio Format 'DTS ES XLL' not detected as DTS-HD MA

### ISSUE THREAD

**Issue by chrisallen** [Radarr/Radarr#3459]
**Describe the bug**
Media with DTS-HD MA audio that is listed with a format of `DTS ES XLL` in MediaInfo is reported as `DTS` in Radarr

**To Reproduce**
1. Add a movie with DTS-HD HD audio that has a format of `DTS ES XLL`
2. Ensure your renaming tokens config includes `{MediaInfo.AudioCodec}`
3. Attempt to rename the media
4. See that DTS-HD.MA becomes DTS

**Expected behavior**
DTS EX XLL format DTs should be tagged as DTS-HD MA

**Screenshots**
```
Ocean's.Eight.2018.BluRay.1080p.DTS-HD.MA.7.1.x264.dxva-FraMeSToR
```
![image](https://user-images.githubusercontent.com/203867/55210005-41697a80-524a-11e9-846c-cd03e04a4952.png)

**Desktop (please complete the following information):**
 - OS: Unraid (Docker)
 - Mono Version: 5.18.0.268 (tarball Thu Feb 28 15:29:06 UTC 2019)
 - Browser and Version Google Chrome 73.0.3683.86
 - Version 0.2.0.1331

**Debug Logs**
I don't have debug logs sorry as this is a MediaInfo detection issue.

I think the fix would be to change the DTS portion here: https://github.com/Radarr/Radarr/blob/develop/src/NzbDrone.Core/MediaFiles/MediaInfo/MediaInfoFormatter.cs

to

```cs
            if (audioFormat.EqualsIgnoreCase("DTS"))
            {
                if (audioAdditionalFeatures.StartsWithIgnoreCase("XLL"))
                {
                    if (audioAdditionalFeatures.EndsWithIgnoreCase("X"))
                    {
                        return "DTS-X";
                    }

                    return "DTS-HD MA";
                }

                if (audioAdditionalFeatures.StartsWithIgnoreCase("ES"))
                {
                    if (audioAdditionalFeatures.EndsWithIgnoreCase("XLL"))
                    {
                        return "DTS-HD MA";
                    }

					return "DTS-ES";
                }

                if (audioAdditionalFeatures.EqualsIgnoreCase("XBR"))
                {
                    return "DTS-HD HRA";
                }

                return "DTS";
            }
```

**Comment by fryfrog** [comment]
https://www.lifewire.com/what-is-dts-es-1846890

^ In case anyone was wondering wtf DTS-ES is... it is a 6th channel.

**Comment by chrisallen** [comment]
here is the media info for the source file

```
RELEASE INFO

Source               : BluRay-CHDBits (Thanks!)
DXVA                 : Compliant
Chapters             : Numbered (01-12)
File Size            : 11.1 GiB
Duration             : 01:50:09 (h:m:s)
Overall Bitrate      : 14.4 Mb/s
Encoded date         : UTC 2018-09-06 23:24:11
IMDb                 : https://www.imdb.com/title/tt5164214/
Genre                : Action | Comedy | Crime | Thriller
Encoder              : Sandra Bullock

VIDEO INFO

Container            : Matroska (MKV)
Codec                : x264
Format Profile       : High@L4.1
Bit Rate             : 10 207 Kb/s
Resolution           : 1 920 x 804
Aspect Ratio         : 2.40:1
Framerate            : 23.976 fps

AUDIO INFO

Format               : DTS
Format profile       : Master Audio / ES Matrix / Core
Bitrate              : 4 040 kb/s / 1 509 kb/s / 1 509 kb/s
Channel(s)           : 8 channels / 7 channels / 6 channels
Sampling Rate        : 48.0 KHz
Bit Depth            : 24 bits
Language             : English
```

**Comment by chrisallen** [comment]
@galli-leo Could we get this fixed and merged?

**Comment by Qstick** [comment]
Should be fixed in Aphrodite now

**Comment by chrisallen** [comment]
Confirmed fixed in Aphrodite
