### ISSUE TITLE
ISO files not being recognized

### ISSUE THREAD

**Issue by schumi2004** [Radarr/Radarr#346]
I added a existing movie that has a ISO file as source but Radarr failed to determine runtime and therefore doesn't see a file for it.

[/volume2/movies/Ciske.de.Rat.1984.DVDR-NL-2Lions-Team/Ciscke.de.Rat.1984.dvdr-nl-2lions.iso] has a runtime of 0, is it a valid video file?

I could convert it to mkv but should Radarr be capable of handling ISO files to begin with?

**Comment by fedoranimus** [comment]
Radarr should not be capable of handling ISO files. An ISO file is a disk image, which is not actually a video file. There is no way to determine what the ISO file represents without mounting it and inspecting the contents.

**Comment by onedr0p** [comment]
ISO files are usually around for DVD-R rips or BRDISKs. They should be handled as @fedoranimus said, we cannot parse video runtime of those, without some way of extracting the image and running mediainfo over the .vods or whatever.
