### ISSUE TITLE
Radarr free space check on Windows is incompatible with NTFS junctions/symlinks/mounts

### ISSUE THREAD

**Issue by CollinChaffin** [Radarr/Radarr#3460]
I see closed issue #1743, but since it is closed and really does not contain much detail and not specific to Windows I am opening a new issue on this as I am a long-time Sonarr user new to Radarr and have not found any workaround for this issue.  It is a critical issue for anyone utilizing very common junctions in their Windows libraries.

## Summary

It is common practice to utilize mount points in just about every modern OS to add disk space to a structure when drive/volume expansion and other methods are unavailable or undesirable.

Radarr utilizes a method in Windows that is currently incompatible with junctions.

## Detail

To reproduce this issue, we use the following example.  In this scenario, the first root media drive/volume is set up, with a single root folder for `Movies01` (for Radarr) and `TV01` (for Sonarr).

Later, as the volume/drive approaches full, to maintain existing compatibility with Plex, Sonarr, and other working apps, additional disk/volume is added as a NTFS folder junction under the original root now as `Movies02` (for Radarr) and `TV02` (for Sonarr).

To reproduce, the following structure is created:

```
\\SERVER\Share$ = Root share (1st set up)
\\SERVER\Share$\Movies01 = Disk01 folder (1st set up)
\\SERVER\Share$\Movies02 = Disk02 junction to different volume (added later)
\\SERVER\Share$\Movies03 = Disk03 junction  to different volume (added later)
```

Free space check from windows and other apps checking target space properly:

```
\\SERVER\Share$ = 500mb (FULL)
\\SERVER\Share$\Movies01 = 500mb (FULL)
\\SERVER\Share$\Movies02 = 100gb
\\SERVER\Share$\Movies03 = 200gb
```

The issue arises when Radarr attempts to utilize `Movies2` or `Movies03` folder as a target for movies.  Instead of `100gb` and `200gb` Radarr only performs a quick check of the root share of `\\SERVER\Share$` returns `500mb` which in this case is insufficient for any additional movies, and fails.

Sonarr, Plex, and other apps continue to work properly and return the actual disk space of the immediate parent to the target folder being created.

## Workaround

There is no current workaround for Windows users as only the Linux version contains a flag to override the free space check.

## Additional Information

This exact structure has been used without issue for years in Sonarr (as well as Plex and other apps), with "TV" folders/junctions along side of the Movies, with the existing established movie library already in place.

Given this is a nzbdrone fork I have only begun to perform a code review of both Sonarr and Radarr, but have quickly determined some differences.

Sonarr's RootFolderService has changes, but I believe this issue may stem from lack of the updates in Radarr that were made in Sonarr with GetFreeSpace().

Sonarr's GetFreeSpace():
```
public List<DiskSpace> GetFreeSpace()
        {
            var importantRootFolders = GetSeriesRootPaths().Distinct().ToList();

            var optionalRootFolders = GetFixedDisksRootPaths().Except(importantRootFolders).Distinct().ToList();

            var diskSpace = GetDiskSpace(importantRootFolders).Concat(GetDiskSpace(optionalRootFolders, true)).ToList();

            return diskSpace;
        }
```

Radarr's same GetFreeSpace():

```
 public List<DiskSpace> GetFreeSpace()
        {
            var diskSpace = new List<DiskSpace>();
            diskSpace.AddRange(GetMovieFreeSpace());
            diskSpace.AddRange(GetDroneFactoryFreeSpace());
            diskSpace.AddRange(GetFixedDisksFreeSpace());

            return diskSpace.DistinctBy(d => d.Path).ToList();
        }
```
Particularly the "rootpaths" calls in Sonarr which appear to be post-fork but I have not confirmed exactly when they were added.

Being a direct fork it is requested that Sonarr's free space check method that is junction compatible be adopted in Radarr moving forward,  as it has already been tested and proven with this codebase for Sonarr.  Either way, this is critical to anyone with large existing libraries that rely on NTFS junctions/symlinks/mounts.

**Comment by fryfrog** [comment]
Great research, did you blame out who made the changes in Sonarr? Maybe they'd help port them to Radarr? Can you point out some of the commits and files in Sonarr?

@galli-leo, this might just need a pull request from Sonarr?

**Comment by Qstick** [comment]
@CollinChaffin, is this fixed in v3? Code is same now so I’d assume so.

**Comment by bakerboy448** [comment]
Closing
v0.2 is no longer being actively developed.

If this is still an issue/request on recent v3 builds, please open a new issue.
