### ISSUE TITLE
Quality Requirements not parsing correctly?

### ISSUE THREAD

**Issue by ChrisWeiss** [Radarr/Radarr#3465]
**Describe the bug**
Radarr is not correctly identifying movie quality information returned by Hydra.
It appears to find several versions of the movie, but rejects them as not meeting my Quality Requirements even though several of the results should.

**Expected behavior**
It should grab the highest-quality result matching my preferences.

**Screenshots**
![image](https://user-images.githubusercontent.com/419818/55293199-d7b3b280-53a8-11e9-83dd-21812be9b297.png)

**Desktop (please complete the following information):**
Docker Container: 
linuxserver/sonarr:latest | 2019-03-25 21:00:38

Version
0.2.0.1293
Mono Version
5.18.1.0 (tarball Fri Mar 15 20:45:47 UTC 2019)
AppData directory
/config
Startup directory
/opt/radarr

**Debug Logs**
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/3027012/radarr.debug.txt)

**Comment by ChrisWeiss** [comment]
Radarr is not behaving according to the documentation: https://github.com/Radarr/Radarr/wiki/Setup-Guide#qualities

That would count as a bug?

**Comment by galli-leo** [comment]
You have restricted your profile to not download anything conforming to the custom format None. Every release gets the custom format none, since you haven‘t added any, hence no release is downloaded. This is also explained in the log files and in the UI.
