### ISSUE TITLE
Language: Nordic matches with Norwegian

### ISSUE THREAD

**Issue by niXta1** [Radarr/Radarr#3466]
**Describe the bug**
Filename with Nordic gets identified as Norwegian

**To Reproduce**
Search for a file with Nordic in the name.

**Expected behavior**
Nordic should preferably not be recognized at all, or recognized as Swedish, Norwegian, Danish and Finnish.

**Desktop (please complete the following information):**
 - OS: DSM, Synology
 - Mono Version: Docker
 - Version :latest

**Comment by fryfrog** [comment]
There is a huge thread about this, please dig it up and see if it is what you're talking about.

**Comment by everlof** [comment]
I think this is the issue that @fryfrog is referring to #1352

I've made a PR that changes the definition of `nordic`: https://github.com/Radarr/Radarr/pull/4546
