### ISSUE TITLE
No automatic movie download.

### ISSUE THREAD

**Issue by Reemster** [Radarr/Radarr#3469]
**Describe the bug**
Movie don't get grapped/ downloaded.

So, i wait for the movie Glass. If i do a manual search i see a big list without recjection icons. So why don't radarr download the movie? its set it to "Monitored yes" "Minimum Availability : Physical/Web" what is going wrong? if i check the radarr.txt (errors) logs for "glass" i see this: 

19-4-2 17:17:16.4|Info|NzbSearchService|Searching 4 indexers for [Glass]
19-4-2 17:17:16.4|Error|NzbSearchService|Error while searching for [Glass]

**Error while searching for [Glass]: Unexpected XML**

System.Xml.XmlException: Unexpected XML
   bij NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.ParseCapabilities(HttpResponse response) in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\Newznab\NewznabCapabilitiesProvider.cs:regel 98
   bij NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.FetchCapabilities(NewznabSettings indexerSettings) in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\Newznab\NewznabCapabilitiesProvider.cs:regel 73
   bij NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.<>c__DisplayClass4_0.<GetCapabilities>b__0() in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\Newznab\NewznabCapabilitiesProvider.cs:regel 36
   bij NzbDrone.Common.Cache.Cached`1.Get(String key, Func`1 function, Nullable`1 lifeTime) in C:\projects\radarr-usby1\src\NzbDrone.Common\Cache\Cached.cs:regel 81
   bij NzbDrone.Core.Indexers.Newznab.NewznabCapabilitiesProvider.GetCapabilities(NewznabSettings indexerSettings) in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\Newznab\NewznabCapabilitiesProvider.cs:regel 36
   bij NzbDrone.Core.Indexers.Torznab.Torznab.get_PageSize() in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\Torznab\Torznab.cs:regel 24
   bij NzbDrone.Core.Indexers.Torznab.Torznab.GetRequestGenerator() in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\Torznab\Torznab.cs:regel 28
   bij NzbDrone.Core.Indexers.HttpIndexerBase`1.GetRequestChain(SearchCriteriaBase searchCriteria) in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:regel 64
   bij NzbDrone.Core.Indexers.HttpIndexerBase`1.Fetch(MovieSearchCriteria searchCriteria) in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:regel 59
   bij NzbDrone.Core.IndexerSearch.NzbSearchService.<>c__DisplayClass6_0.<MovieSearch>b__0(IIndexer indexer) in C:\projects\radarr-usby1\src\NzbDrone.Core\IndexerSearch\NzbSearchService.cs:regel 52
   bij NzbDrone.Core.IndexerSearch.NzbSearchService.<>c__DisplayClass8_1.<Dispatch>b__0() in C:\projects\radarr-usby1\src\NzbDrone.Core\IndexerSearch\NzbSearchService.cs:regel 84

 
But why if i do an manual search i can find it, and download the movie...

**Comment by fryfrog** [comment]
https://github.com/Sonarr/Sonarr/wiki/FAQ#How-does-Sonarr-find-episodes

Radarr doesn't work how you think it works.

For your error, you've probably added a newznab indexer as torznab (or the reverse).
