### ISSUE TITLE
Remove (or modify) Filter Series Tags from Connection Notifiers

### ISSUE THREAD

**Issue by schumi2004** [Radarr/Radarr#347]
When adding connection notifiers they contain a field for: Filter Series Tags
This should either be removed or changed to: Filter Movie Tags

![filter](https://cloud.githubusercontent.com/assets/968545/22107022/fe450bc6-de4b-11e6-8856-22a61cf2555c.PNG)

**Comment by onedr0p** [comment]
Yes, notifications need to be changed to work with movies. Duplicate #200
