### ISSUE TITLE
Deluge 1.3.15 'loses' connection to Radarr and Sonarr

### ISSUE THREAD

**Issue by yuljk** [Radarr/Radarr#3471]
Hi guys - I'm running Deluge 1.3.15 as a service on Windows Server 2019 Core. I've noticed over a period of time that both Sonarr and Radarr (also running as services on the same VM) lose connection to Deluge. When hitting the test button in Radarr or Sonarr I get the following in my logs.

19-4-4 15:47:44.5|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
-- Unknown exception: Failed to connect to Deluge daemon.

If I connect to the Deluge Web interface and then connect to the instance through connection manager, Radarr and Sonarr start communicating again.

Any ideas why this is happening? (I've also tried creating a scheduled task each day to stop and restart the deluged, delugeweb, radarr and sonarr services - however this doesn't help)

Many thanks

**Comment by Dnkhatri** [comment]
radarr and sonarr use the delugeweb to connect to deluge. Your problem is that deluge-web loses it connection to deluged. Try to find out why that happens if you can fix that your problem will be solved

**Comment by yuljk** [comment]
Thanks - I've also posted on the deluge forums to see if they have an answer.
