### ISSUE TITLE
Connection refused - Radarr stopped working

### ISSUE THREAD

**Issue by penzinho** [Radarr/Radarr#3477]
**Describe the bug**
Out of the blue, Radarr stopped working. I can't access it through web UI. At first, I thought it has something to do with ports but they are ok. Found some errors in the log which is attached. I am not skilled enough to interpret them.

**To Reproduce**
I don't know, it was sudden onset.

**Expected behavior**
I expected it to work as it used to.

**Screenshots**
![radarr](https://user-images.githubusercontent.com/17112029/55751051-097de680-5a45-11e9-8e29-ef785ee4244f.png)

**Desktop (please complete the following information):**
Linux 18.04. LTS

**Debug Logs**
Can't turn on debug logs as I can't start Radarr.

Here are logs from appdata/logs - https://pastebin.com/m5e6JaDz

**Comment by galli-leo** [comment]
Your logs seem to indicate Radarr is listening on another port than 7878
