### ISSUE TITLE
Special characters not considered in search results (Amélie)

### ISSUE THREAD

**Issue by malventano** [Radarr/Radarr#3478]
**Describe the bug**
Special characters not considered in search results. Movies with special characters in the name do not appear until that special character has been typed. If the full name is typed without special characters, the search also fails.

**To Reproduce**
Attempt to search 'Amélie' by typing 'Am'

**Expected behavior**
Amélie should show in results if that movie is present. Also, special characters should also be considered as their standard characters in searches (e.g. searching for 'amelie' should also succeed).

**Screenshots**
https://i.imgur.com/5O3PVZ7.png

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome
 - Radarr Ver. 0.2.0.1331 (nightly)

**Debug Logs**
N/A

**Comment by galli-leo** [comment]
https://github.com/Radarr/Radarr/wiki/Common-Problems#jackett-shows-more-results-than-radarr-when-manually-searching There are plans to make this work better and issues already open about this.
