### ISSUE TITLE
Wanted page only shows 15 records, does not increase past this

### ISSUE THREAD

**Issue by nutski** [Radarr/Radarr#348]
I saw a couple of people on Discord say they have 15 movies on their wanted list, mine was the same so I tested by adding more wanted movies.
The movies I add appear in the list, the quantity remains at 15 and it remains at page 1/1.

Provide a description of the feature request or bug, the more details the better.
When possible include a log!

Please use our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by WallaWallaWA** [comment]
Same here, plus Search Selected (one movie or multiple movies) returns an error:
Component	Message	Time
CommandExecutor	Error occurred while executing task EpisodeSearch: Episode with ID 92 does not exist	6:20am
CommandExecutor	Error occurred while executing task EpisodeSearch: Episode with ID 70 does not exist	6:20am
CommandExecutor	Error occurred while executing task EpisodeSearch: Episode with ID 68 does not exist	Yesterday
CommandExecutor	Error occurred while executing task EpisodeSearch: Episode with ID 70 does not exist	Yesterday
CommandExecutor	Error occurred while executing task EpisodeSearch: Episode with ID 68 does not exist	Yesterday
