### ISSUE TITLE
Radarr is removing the torrent data unexpectedly

### ISSUE THREAD

**Issue by cybersteel8** [Radarr/Radarr#3481]
**Describe the bug**
After downloading a torrent successfully, Radarr is importing the movie into my library successfully but it is also removing the torrent data.

**To Reproduce**
1. Start a download via Radarr
2. When the download completes, Radarr imports the movie
3. Import is complete
4. Data does not exist in original download location.

**Expected behavior**
The data should remain in the original download folder because I have explicitly set the "Remove" option to "No" for my torrent client's "Completed Download Handling" section. I also have the "Use Hardlinks instead of Copy" option set to "Yes" in the "Media Management" screen.

This issue happened with Transmission, so I switched to QBittorrent to see if the problem persists, and it does, therefore it isn't an issue with my torrent client. The entry in my torrent client is not removed, so Transmission/QBittorrent expects the data to remain and throws an error when trying to seed or verify the data.

I suspect this issue is also happening in Sonarr.

**Screenshots**
![image](https://user-images.githubusercontent.com/17291212/55927348-145c9500-5c58-11e9-8695-75a697772731.png)

![image](https://user-images.githubusercontent.com/17291212/55927353-1cb4d000-5c58-11e9-91b5-c3eba66e3270.png)

![image](https://user-images.githubusercontent.com/17291212/55927362-23dbde00-5c58-11e9-8f80-3054aac7e57d.png)

**Desktop (please complete the following information):**
 - OS: Fedora 27
 - Mono Version 5.12.0.301 (tarball Fri Jul 20 15:09:05 UTC 2018)
 - Radarr Version 0.2.0.1293
 - Transmission 2.92 (14714)
 - qBittorrent-nox v4.0.4

**Comment by galli-leo** [comment]
Please provide debug logs in our support channels. Also Radarr will never remove torrent data files, so you might have another program doing this

**Comment by fryfrog** [comment]
*Sonarr* will *move* torrents that are finished, so *Radarr* probably will too. And both should send a remove to clients when seed time/ratio goals are met and some clients will remove data for that.

But I agree, this doesn't sound like Radarr doing it.

**Comment by cybersteel8** [comment]
Ah, that might be what's happening - I do have seed time/ratio values set, so Sonarr & Radarr are is probably deleting those files before I get a chance to access them. Is this behaviour that I can disable? I require access to the files even if I have finished seeding them, since often they contain subtitle files that aren't automatically grabbed and I have to get them from the torrent data myself.
