### ISSUE TITLE
Questions/Advices on how to deal with languages in Radarr

### ISSUE THREAD

**Issue by GeoCookie** [Radarr/Radarr#3482]
Hello everyone,

I would like your opinions and advices on how to use Radarr because I am facing problems with language management.

I am French and I like watching movies in their native language. So I created several profiles with different languages. For English movies, no problem, everything works fine. But it gets complicated when I want to download a foreign movie. The main problem is the misinterpretation (in my opinion) of Radarr on terms related to the movie language and subtitles.

Some examples that I met:
• If no term indicates the language of the movie in the name of the torrent, Radarr assumes that the movie is in English. In fact, most of the time, this means that the file is in the original language of the movie.
(the movie below is in french, but found english by Radarr)
![Radarr - sans info](https://user-images.githubusercontent.com/43962716/56033407-d7aa9f80-5d24-11e9-97c7-5277f68936df.png)

• The problem also arises for the term "VO". If Radarr finds the word VO, he considers the file as English, which is not the case. A torrent with VO for an Italian movie means that it is in Italian, not in English
(i have no exemple right now)

• Some terms are misinterpreted as "VOSTFR" or "Multi".
(the movie below is in dutch, but found french by Radarr)
![Radarr - vostfr](https://user-images.githubusercontent.com/43962716/56033420-ded1ad80-5d24-11e9-8b04-9695b6019c72.png)
(the movie below contains french language, but found english by Radarr)
![Radarr - multi](https://user-images.githubusercontent.com/43962716/56033447-ed1fc980-5d24-11e9-8093-80a342fd4d7d.png)

How do you manage these situations? I tried to play with Custom Profiles but to have a functional system, I ended up with a real labyrinth.

Some ideas that I have that could simplify things:
• One thing that would be great would be for Radarr to manage the download of movies in their original language. For example, we can set "Original language" on the profile and Radarr gets the language from the metadata (TheMovieDB has this information). It will reduce the numer of used profiles. 
• It would be nice if we could edit the terms associated with a language. For example, that I can delete "VOSTFR" of the French language terms.

Many thanks for your work, Radarr have really simplified my download process! :)

**Comment by YeungKC** [comment]
I like watching movies in their native language too…

**Comment by guim31** [comment]
I'm facing the exact same issues... as I'm french too and I have to verify everytime which file Radarr should download for me, I'm never sure it will be the right one.

Thanks geocookie for this detailled issue as I'm not sure I'd have enough motivation to write it !!

**Comment by ToXinE** [comment]
"VOSTFR" stands for "Version Originale Sous Titrée FRançais" so definitly not Dutch...

**Comment by ToXinE** [comment]
"VOSTFR" stands for "Version Originale Sous Titrée FRançais" so definitly not French Audio track but with French Subtitles... So it depends on what you expect :
Filtering movies **before** downloading them to check if the movie is REALLY in his native language is not possible but Radarr can have a nice feeling if it check the name of the file.

For "Multi" movies it's a different story: You need to specify which language it represent by indexer.

**Comment by Qstick** [comment]
Original Language is added in V3

**Comment by jt196** [comment]
@Qstick came here as I had the same issue. Can I suggest the 'Original' option get moved up the menu to the top above the other languages? I only found it as I was looking for it. Personally I think this should be the default option, and 'Any' second on the menu, with all the other languages below. 

If you think it's best to open a new issue for this I've no problem with that.

**Comment by Qstick** [comment]
> @Qstick came here as I had the same issue. Can I suggest the 'Original' option get moved up the menu to the top above the other languages? I only found it as I was looking for it. Personally I think this should be the default option, and 'Any' second on the menu, with all the other languages below. 
> 
> If you think it's best to open a new issue for this I've no problem with that. 

Yes please make a new issue
