### ISSUE TITLE
Movie Manual Import Sets Original Filename & Title Fields Incorrectly

### ISSUE THREAD

**Issue by 0aeonnoea0** [Radarr/Radarr#3483]
**Description:**

When a movie is manually imported, the original filename is not correctly filled in with the original filename as imported, but instead with the filename after the import is complete.

Let's use the following example: A Standard movie format of `{Movie Title} ({Release Year}){ [Original Filename]}`, and we are trying to import a copy of `Finding Dory (2016)` that has a filename `Finding Dory 2016 Example.mkv`

This will correctly rename the movie file to `Finding Dory (2016) [Finding Dory 2016 Example].mkv` however if you try checking `Preview rename for movie` you end up with the following suggestion: `Finding Dory (2016) [Finding Dory (2016) [Finding Dory 2016 Example]].mkv`

It seems what's happened is the wrong filename is being saved to the database.

Regarding Original Title - it seems from my searching of other issues that this should be the name given to the torrent in the download client - if this is the case then when manually importing this should probably just be set to the same as the original filename, or am I getting the wrong idea here?

**Radarr Version:** 0.2.0.1293

**Mono Version:** 5.18.0.240 (tarball Wed Jan 16 09:10:16 UTC 2019)

**Debug Logs:**

I don't have any direct logs from when something like this has happened, as I've only just switched to this new naming scheme.

**Comment by fryfrog** [comment]
Dear lord, original file name *in* the file?

In the future when you do need to make use of the data preserved by keeping the original file name, life is going to be *weird*.

I think this deserves looking at to fix, but...

I can't see any good reason to both use a neat name *and* preserve the file name. Instead, why not use the *folder* to preserve a nice name and just use original name only inside?

**Comment by jojogrosso** [comment]
This sounds similar to an issue I'm having.

I like to keep the original folder name and then rename the file to "Move (Year).mkv"

When the settings are set to use the original folder name, it changes the folder name to "A Madea Family Funeral.2019.-Radarr" instead of keeping the original folder name "A.Madea.Family.Funeral.2019.1080p.WEB-DL.DD5.1.H264-FGT"

PS: Thank you so much for making Radarr work with original folder names :)
