### ISSUE TITLE
Too many movies selected in MovieEditor gives invisible 413 error

### ISSUE THREAD

**Issue by Mech0z** [Radarr/Radarr#3484]
**Describe the bug**
If I add 100+ movies (I would presume it varies depending on what ID's the movies you have in your library have, high IDs might fail with fewer entries if they are part of the URL header) in the Movie editor (To mass edit change profile) and click save nothing will happen. But if I F12 and look at the response it shows a 413

413 Request Entity Too Large
nginx/1.15.11

So maybe only an issue with Nginx (Nginx and Radarr running in a docker container on Ubuntu)

So maybe show an error if 413 is thrown

**Comment by M1kep** [comment]
I ran into the same issue recently and was able to work around it by just doing it in chunks.(I also use nginx)

I can't test right now, but this fix seems like it would work:

https://www.cyberciti.biz/faq/linux-unix-bsd-nginx-413-request-entity-too-large/

**Comment by fryfrog** [comment]
If your reverse proxy is throwing an error, you'll need to address this in your reverse proxy.
