### ISSUE TITLE
movies fail to map with special characters in the title

### ISSUE THREAD

**Issue by schmittimillian** [Radarr/Radarr#3487]
**Describe the bug**
a movie with a special character does not accept releases/torrents that are missing the special character. this report is for one specific movie, `I'm a Cyborg, But That's OK`. This movie fails to map when it sees releases without the apostrophes (`'`) and comma (`,`).

**To Reproduce**
1. Go to movie page (in this case, it's `/movies/im-a-cyborg-but-thats-ok-5488`)
2. Click on 'Search'
3. See that it finds movies, but none of them map, all have the red exclamation point symbol.
4. Hover over ![image](https://user-images.githubusercontent.com/22268708/56236093-c5976c80-6056-11e9-9bc5-94f739343406.png), see that it fails to map because the release does not include the comma.

**Expected behavior**
movies should not care about special characters in the title since most releases will remove special characters from the release title.

**Screenshots**
This screenshot shows the release rejection message. You can see the highlighted title is the one it's looking for, but it finds one that is the exact same, just without the special characters.  
![image](https://user-images.githubusercontent.com/22268708/56236284-3a6aa680-6057-11e9-9317-dfc805020410.png)

**Desktop (please complete the following information):**
 - OS: Windows Server 2019
 - Browser and Version: n/a
 - Version: 0.2.0.1293

**Debug Logs**
I've attached the radarr.txt log here. Let me know if you want other logs.
[radarr.txt](https://github.com/Radarr/Radarr/files/3086453/radarr.txt)

**Comment by fryfrog** [comment]
https://i.imgur.com/Ova02K4.png

I think it is more complicated than just the `'`. I have a bunch of results for this movie and *most* of the ones with a `'` are fine. In the screen shot above, all those red ! are for incorrect resolution or language, except the one I hover and maybe one other. At the top, you can see a totally fine match w/ a `'`.

Can you turn logging up to trace and repeat the search and pastebin the section around the search? We don't need the whole thing, that'll be huge.

**Comment by jasimancas** [comment]
Maybe like this?
![image](https://user-images.githubusercontent.com/15717847/56674492-71c1fe80-66ba-11e9-859b-b2cf2e2649c2.png)

**Comment by fryfrog** [comment]
Can you trace logs of that search?

**Comment by jasimancas** [comment]
This?
[radarr.trace.txt](https://github.com/Radarr/Radarr/files/3113188/radarr.trace.txt)

**Comment by fryfrog** [comment]
If it contains the search, yup! All we need is the search and some context around it though, trace logs are huge. :)

**Comment by jasimancas** [comment]
I use Jackett with NEWPCT indexer. Wait a moment please.

**Comment by fryfrog** [comment]
You don't need to force it, I think the 10-20 lines about why it gets rejected should be useful enough to a developer to figure out. :)

**Comment by fryfrog** [comment]
I mean, if you *want* it you can just queue that download up yourself in your download client, give it the same label radarr uses and it *might* import it too.

**Comment by jasimancas** [comment]
> I mean, if you _want_ it you can just queue that download up yourself in your download client, give it the same label radarr uses and it _might_ import it too.

Really? Umm, i cant try this...

**Comment by fryfrog** [comment]
Sure you can, just get the torrent / nzb directly from the indexer, add it to your client the old fashioned way.

**Comment by fryfrog** [comment]
To be clear, that suggestion *isn't* for testing, its just so you can get the movie in your library if you want it.

**Comment by jasimancas** [comment]
I have the file.torrent, i add to qbitorrent with category "radarr", download finished, but dont import the movie.

**Comment by fryfrog** [comment]
Oh well, Wanted -> Manual Import it and pick the right movie. It was worth a try, but not surprising. It couldn't parse it accurately to queue it up.

**Comment by jasimancas** [comment]
> 19-4-24 18:01:37.0|Trace|DownloadDecisionMaker|Processing release 4/120
19-4-24 18:01:37.0|Trace|ConfigService|Using default config value for 'parsingleniency' defaultValue:'Strict'
19-4-24 18:01:37.0|Debug|Parser|Parsing string 'El regreso de Mary Poppins .4K UHDmicro.2160p.HDR.DTS 5.1 AC3 5.1 Castellano-AC3 5.1-Ingles+Subs.ES-EN.Spanish'
19-4-24 18:01:37.0|Debug|Parser|Unable to parse El regreso de Mary Poppins .4K UHDmicro.2160p.HDR.DTS 5.1 AC3 5.1 Castellano-AC3 5.1-Ingles+Subs.ES-EN.Spanish
19-4-24 18:01:37.0|Debug|DownloadDecisionMaker|El regreso de Mary Poppins .4K UHDmicro.2160p.HDR.DTS 5.1 AC3 5.1 Castellano-AC3 5.1-Ingles+Subs.ES-EN.Spanish could not be parsed :(.
19-4-24 18:01:37.0|Trace|ConfigService|Using default config value for 'parsingleniency' defaultValue:'Strict'
19-4-24 18:01:37.1|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] Failed to find movie title in release name El regreso de Mary Poppins .4K UHDmicro.2160p.HDR.DTS 5.1 AC3 5.1 Castellano-AC3 5.1-Ingles+Subs.ES-EN.Spanish

**Comment by jasimancas** [comment]
More problem:
![image](https://user-images.githubusercontent.com/15717847/57060944-7c345780-6cbb-11e9-8dde-bc9669efe455.png)

**Comment by galli-leo** [comment]
@jasimancas All the screenshots you sent indicate there is no year in the release name. Radarr needs a year in the release name, to find out where the movie title ends and other information starts. You can circumvent this requirement by setting your parsing leniency to mapping lenient in settings.
