### ISSUE TITLE
Per Indexer Seed Time/Ratio from Sonarr

### ISSUE THREAD

**Issue by davidjirovec** [Radarr/Radarr#3488]
I would like to see this feature from Sonarr

![seed ratio](https://user-images.githubusercontent.com/1950225/56244134-796f1b00-609c-11e9-9076-8ef1d06e1969.png)

also in Radarr. Any plans on this?

**Comment by fryfrog** [comment]
I think this would be cool too, I wonder how hard it would be to merge what ever commits added it. :)

**Comment by jeff15110168** [comment]
would love to see this as well

**Comment by Dnkhatri** [comment]
> would love to see this as well, the sonarr implementation works extremely well

It is already added in the v3/aphrodite builds I dont think it will be backported to v2

**Comment by jeff15110168** [comment]
hmm, im on the develop 0.2.0.1358 version, is there a version i can update to or is that v3/aphrodite still in the works?
