### ISSUE TITLE
Set default profile when adding movies

### ISSUE THREAD

**Issue by mariotacke** [Radarr/Radarr#3489]
When adding a movie, the UI provides a drop down with profiles which defaults to "Any" in a new browser. The selection is saved in between page reloads in local storage via `Radarr.RadarrDefaultProfileId`. It is frustrating to set the default profile id every time I use a new device.

I'd like to mark a given profile "default" from the profile edit modal and have that setting persist for new users and new devices.

I suppose I could remove all other profiles or modify the "Any" profile, but that only seems to be a hack around the issue.

I could take a stab at this if you are open to review my PR / point me in the right direction where to best implement it.

**Comment by fryfrog** [comment]
Both Sonarr and Radarr behave this way and I suspect there is not a strong desire to deviate from it. You'd be adding a *bunch* of options somewhere just to set a default for new browsers.

**Comment by fryfrog** [comment]
Also, this is probably already an existing feature request, maybe search issues and feathub.

**Comment by Qstick** [comment]
No plans on persisting this beyond local cache
