### ISSUE TITLE
nCore indexer request

### ISSUE THREAD

**Issue by Noorbertt** [Radarr/Radarr#349]
Hi guys,

Maybe there is a way to import this (see the link) CouchPotatoProvider ? 
https://github.com/gala132/nCoreCouchPotatoProvider

Many Thanks :)

**Comment by onedr0p** [comment]
What is it, there is no description, I don't even know what ncore is.

**Comment by Noorbertt** [comment]
https://github.com/Sonarr/Sonarr/issues/1632

I can invite you :) But they do not have API (yet)

**Comment by onedr0p** [comment]
Do they have a RSS feed? If so we can allow RSS Sync, but they won't have search support.

**Comment by Noorbertt** [comment]
I will ask them, maybe they going to do something with API , fingers crossed :)

**Comment by onedr0p** [comment]
Feel free to get ahold of me when they do, you can message me on discord if you want to invite me.

**Comment by hotio** [comment]
I think you can use Jackett for this, it's listed as supported.
https://github.com/Jackett/Jackett
