### ISSUE TITLE
Explaining connecting a service in Radarr

### ISSUE THREAD

**Issue by StreetDenizer** [Radarr/Radarr#3490]
I have spend a whole day to figure it out why I can't connect my Plex Media Server to Radarr in the 'connect' form.
But I got my findings. Right here and right now for you who is in the same trouble.

**For who?**
When you have setup a manual username in Plex settings, and you already got a linked account. (like Google of something), with different passwords, you need to make them match!

**In what case?**

You got a Gmail address linked to my Plex account. But you have also set up a username in the Plex settings and adjust a different password. Your Gmail-address has another password set. 
Now you can login through two different ways:
- With your Google Gmail-address and different password
- With your username and password

But, the 'connect' tab will not handle two different passwords!

**Wat do you need to do?**
1. Make sure you absolutely know your linked email-address password
2. Make sure you have setup an easy username in your Plex account settings
3. Change the password in the Plex account settings exactly like your e-mail-address password.

Depending on the other settings, this will work! 
In my case I restarted Plex and Radarr first.

**Radarr Version:**
0.2.0.1293

**Debug Logs:**

> PlexServerService
Unable to connect to Plex Server: Invalid Token - Update your username and password: Invalid Token - Update your username and password

> NzbDroneErrorPipeline
Invalid request Validation failed: 
 -- Incorrect username or password

Good luck!

**Comment by StreetDenizer** [comment]
**Update:**

I am now setting up Sonarr too, and I notice that I can't use the username I choosed in the situation I just wrote in the topic.

Solution: I used in Sonarr the full e-mail address and same password as the situation I described above.

**Comment by fryfrog** [comment]
Honestly, the only thing you get from connecting Sonarr/Radarr to Plex is a library update trigger. Which they can do better w/ their own built in folder monitoring. On Linux, it uses the kernel's inotify system. On Windows, it uses something similar.
