### ISSUE TITLE
Feathub entry redirects to blog post in chinese

### ISSUE THREAD

**Issue by rrd911** [Radarr/Radarr#3492]
When clicking on an enhancement request I get redirected to a Chinese blog post

https://feathub.com/Radarr/Radarr/

Select the tip entry

Using my cellphone and opening in chrome

**Comment by fryfrog** [comment]
There is no "enhancement request", I think maybe you have something weird on your phone?

https://feathub.com/Radarr/Radarr/features/new

https://i.imgur.com/PNmIGMt.png

**Comment by rrd911** [comment]
Did you try clicking on any of the requests? Like 
https://feathub.com/Radarr/Radarr/+29
