### ISSUE TITLE
Media info not working for imported movies

### ISSUE THREAD

**Issue by kaplannn** [Radarr/Radarr#3493]
hey guys, so i started a new radarr instance and imported few movies from my existing library. If i go to the movie page and press on „file“, the Media info is empty. That also mean i can‘t rename my movies according to the mediainfo naming tags.
If i download a movie and import, the media info just works fine.

I run mediainfo manually to the imported movie files, that works good.

 - OS: ubuntu 16.04
 - Mono Version: 5.20
 - Radarr: nightly
 - mediainfo: latest, v18.12

https://imgur.com/a/hV3UUDV (Bulk imported movie, empty media info)
https://imgur.com/a/DsvQJot ( naming not working with media info tag)

As i said, if i download a movie, it gets imported, that works fine with the mediainfo.

**Comment by hotio** [comment]
Did you enable `Analyse video files` under `File Management` on the `Media Management` tab. It's an advanced setting.

**Comment by kaplannn** [comment]
Omg im soooo stupid 😤😤😤 thanks tho 👍
