### ISSUE TITLE
Import TMDB Watchlist

### ISSUE THREAD

**Issue by Zeusy123** [Radarr/Radarr#3496]
Hi guys, thanks for all your great work, but I think this is something many will want and would be extremely useful.

Currently radarr allows us to import our own user lists.  Which have unuqie numbers in the url.
These user lists do NOT allow us to import our movies lists into them.

We can only import movies into TMDB Watchlist & Favourites.  Both of which I cant import into radarr.

I spokje to TMDB and they said the api is same on there watchlists and would be very easy for radarr to allow watchlists if they can already import from user lists.

So if possible, how can we import from TMDB watch list inot our radarr installs?

Thanks in advance.

**Comment by elChapoSing** [comment]
https://developers.themoviedb.org/4/account/get-account-movie-watchlist
`get/account/{account_id}/movie/watchlist`

https://developers.themoviedb.org/4/account/get-account-favorite-movies
`get/account/{account_id}/movie/favorites`

This would also require a slight change to the UI for TMDB lists as the user would need to enter its account.

**Comment by elChapoSing** [comment]
I'm happy to help code it into the API but could someone point me in the right direction ?

**Comment by skuid87** [comment]
Any updates on this? I have my entire favourite list on TMDb and would love to get this into radarr
