### ISSUE TITLE
Define specific language for movies information

### ISSUE THREAD

**Issue by GeoCookie** [Radarr/Radarr#3497]
Hi there,

Is it possible to deal separately with languages used in profiles and languages used to download movies information?
I downloaded a Japanese movie with Japanese language define in the associated profile. Result, the movies page and the filename are in Japanese.
![Radarr - Problem language](https://user-images.githubusercontent.com/43962716/56717252-86df7180-673c-11e9-937a-3b52b08339c3.png)

It would be good if we could define a specific language for the movies information.

Thank you

**Comment by alxlaxv** [comment]
+1

**Comment by ToXinE** [comment]
moreover, if you select a profile with the language "**Any**", this leads to no informations at all.
see #3406

**Comment by jfml** [comment]
I would love this feature, I'm having problems with telling which anime is which only from judging by the movie posters (which are also Japanese most of the time) ^__^
