### ISSUE TITLE
Unable to search for movies, fresh install

### ISSUE THREAD

**Issue by cooljimy84** [Radarr/Radarr#3498]
Unable to search for any movies. I've tried a new install and even this shows the same issue in the web front end.
    There was an error searching for 'batman'.
normal log shows
    |Fatal|NzbDroneErrorPipeline|Request Failed
    System.Net.WebException: The request timed out

Provide a description of the feature request or bug here, the more details the better. 
Please also include the following if you are reporting a bug. If you do not include it, the issue will probably be closed as we cannot help you. -->

Radarr Version: 0.2.0.1293

Mono Version: Debian 4.6.2.7+dfsg-1ubuntu1

I've tried the following machines, ubuntu server 18.04 (fresh install, unpatched)
ubuntu server 18.04 (fresh install, fully patched)
ubuntu server 16.04 (fresh install, unpatched)
ubuntu server 16.04 (fresh install, fully patched)
I even though maybe i was being blocked for querys on IMDB, so created a new machine on my work machine to go via there public ip....

[radarr.debug.txt](https://github.com/Radarr/Radarr/files/3116323/radarr.debug.txt)
[radarr.trace.txt](https://github.com/Radarr/Radarr/files/3116324/radarr.trace.txt)

**Comment by fryfrog** [comment]
TMDb has disabled TLS 1.0. You need a modern version of Mono and to *not* use the `legacy` tls provider.

If you're using Docker, update to the latest version of the image you use to get Mono updated. If you're not, you should use Mono's own site to keep your's up to date, follow their instructions.

For both, you'll need to make sure you're not setting the `MONO_TLS_PROVIDER=legacy` environment variable. This *can* be set in many places, but for Docker it's probably a `-e` option to your `docker <run|create>` command or an Environment Variable in what ever Docker manager you use. On normal Linux systems, it'll probably be an `Environment=` in your `radarr.service` systemd file.

https://www.mono-project.com/download/stable/#download-lin
