### ISSUE TITLE
Cannot change filters after bulk deleting movies.

### ISSUE THREAD

**Issue by mtcdood** [Radarr/Radarr#3499]
**Describe the bug**
When all movie for a given filter are deleted it is impossible to switch to another view because the library acts like there are no movies.

**To Reproduce**
1. Go to Movies and select UnMonitored in the filter list
2. Go to Movies > Movie Editor and delete all UnMonitored movies
3. Go to Movies and the view will still be filtered to UnMonitored with no easy way to change it

**Expected behavior**
When there are no movies for a given filter you should still be able to change the filter unless there are no movies for ANY filter.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser and Version: Google Chrome 73.0.3683.103
 - Version: 0.2.0.1293

**Debug Logs**
Close the issue if you want. I'm not reproducing this bug because I have no idea how I fixed my interface and don't want to go through the unpleasantness of losing my whole list again.

**Comment by fryfrog** [comment]
I think the even lower level problem is that *some* filters in Movie Editor are just not available in the normal Movies view. If you go back to Movie Editor, you can do what you need right?

**Comment by mtcdood** [comment]
Nope. You can't get back to the movie editor view because the interface acts as though there are no movies period.

**Comment by fryfrog** [comment]
Yikes, so gotta flush browser cash / switch to incognito window?

**Comment by mtcdood** [comment]
Shift+F5 didn't work nor did restarting Radarr. I don't know if flushing the browser cache or starting with an incognito window would have removed the selected filter.

**Comment by fryfrog** [comment]
It should, all that stuff is stored browser side I believe. The incognito mode would work, but wouldn't fix it. Just quick and useful to see if browser cache flushing would "fix" it. :/

I'll try to reproduce it just to confirm. :/

**Comment by mtcdood** [comment]
To be clear when you have movies in your list normally you see the buttons to change the filters:
![image](https://user-images.githubusercontent.com/42127748/56817388-1a7f7380-680b-11e9-8b9d-b10a36c0cd86.png)
This bug report is for when that doesn't happen and you get the "no movies" page instead.

**Comment by fryfrog** [comment]
Things that *don't* reproduce it:

Movie Editor, filter by Unmonitored (have *no* unmonitored), go tack to Movies.

**Comment by fryfrog** [comment]
I think the last thing I did is what you're reporting, but it isn't doing it for me. :/

**Comment by mtcdood** [comment]
Weird. If you can't reproduce it that's technically a good thing.
