### ISSUE TITLE
Radarr insisting on downloading locally and not with seedbox

### ISSUE THREAD

**Issue by ColeBBB** [Radarr/Radarr#3500]
**Describe the bug**
I setup my seedbox as the only Download Client and enabled it. However, when I search for a movie to download (my clicking Add Movies), it demands a local path when I want it to use the seedbox. When I give it a path and check the status, it shows that it will be creating the files for the movie at the specified path. 

**Expected behavior**
I expect it to simply be downloaded by the seedbox. I do not want it to be on my machine locally.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 0.2.0.1293

**Comment by fryfrog** [comment]
Sonarr/Radarr expect downloads to go to one place and the library to be another. As long as they're both accessible, it doesn't really matter where this is. But does matter that there are two. It sounds like you just want Radarr to queue stuff up in your download client. It doesn't work like that, but maybe some other software does.

In a normal seedbox setup, your library would live locally and the seedbox might be remote mounted w/ something like sshfs. After download, Radarr would import the file to your local, well organized library. From there, the download client is free to do w/ the torrent as it wishes. Usually removing after seed time/ratio goals are met.
