### ISSUE TITLE
[Req] Replace Mono with .NET Core

### ISSUE THREAD

**Issue by ngosang** [Radarr/Radarr#3502]
Recently, the [Jackett](https://github.com/Jackett/Jackett) project changed the package distribution for Linux replacing Mono with .NET Core. This has 2 advantages:
- There is no need to install Mono, the binary contains all dependencies. Can be tricky to install because it's not in the official repositories.
- We saw a 32% memory reduction in Jackett (and will be greater in the next major version of .NET Core) => https://github.com/Jackett/Jackett/issues/4720

I'm not a C# programmer so I can't help.
What do you think about?

PD: I asked the same question to the Sonarr team => https://github.com/Sonarr/Sonarr/issues/3087
More info: https://stackoverflow.com/a/39740592

**Comment by fryfrog** [comment]
From looking at the Sonarr issues, you probably know that this would be a *huge* task for Sonarr, Radarr and Lidarr.

I hope it happens, but w/o someone interested in driving it... I don't see how it will.

**Comment by Qstick** [comment]
Same as #3457... Maybe one day but I don't know there is any reason to keep this issue open now
