### ISSUE TITLE
Support seed ratio setting for Transmission client

### ISSUE THREAD

**Issue by 2fst4u** [Radarr/Radarr#3505]
**Is your feature request related to a problem? Please describe.**
Radarr doesn't pass a seed ratio to Transmission

**Describe the solution you'd like**
It would be preferable to have this at the download client level, at least as an option, so all downloads for transmission had a target seed ratio passed to them.

**Describe alternatives you've considered**
The alternative is using Transmission's built in seed ratio but this applies to all downloads including those outside Radarr (or Sonarr).

**Additional context**
Sonarr has this feature available. I'm unsure how difficult it would be to implement. I also not some issues are open for seed ratios at the indexer level and this would be good too, but ideally both options should exist.

**Comment by fryfrog** [comment]
I think the solution here is for someone to port the Sonarr feature to Radarr. I *swear* @Qstick and I discussed it on Discord, but maybe it was @ta264?

In the mean time, pretty much *all* the other torrent clients have better seed time/ratio criteria support built in.

**Comment by Qstick** [comment]
Yea I mentioned I would, but got lazy and only did on Aphrodite I'll knock it out this weekend for current version.

**Comment by Qstick** [comment]
Same as #3488
