### ISSUE TITLE
Related to ticket #2107

### ISSUE THREAD

**Issue by Fyb3roptik** [Radarr/Radarr#3506]
https://github.com/Radarr/Radarr/issues/2107

This is still an issue. Please reopen this ticket. I have added the details there

**Comment by fryfrog** [comment]
Then just re-open the issue? You should be able to do that.

**Comment by fryfrog** [comment]
That isn't even your issue. You just need support, you're doing something wrong (as was the post of that issue I'm sure).

**Comment by Fyb3roptik** [comment]
I know how to toggle movies properly. What I am saying is ever since updating it no longer toggles the movies off!
