### ISSUE TITLE
Radarr will not download due to size issues

### ISSUE THREAD

**Issue by ak2766** [Radarr/Radarr#3507]
**Describe the bug**
I have an item listed in the manual search as being 2.5GB in size.  I have quality settings to allow a BluRay item of upto 3GB.  However, Radarr indicates that the 2.5GB item is > than my set limit of 2.3GB - I'm not sure where the 2.3GB number is coming from.

**To Reproduce**
1. Select the item in Radarr calendar
2. Click the manual search icon
3. Hover over the red exclamation

**Expected behavior**
I expected that the item will be available to be downloaded since it is far below my upper limit of 3GB.

**Screenshots**
![radarr](https://user-images.githubusercontent.com/6629646/57174027-37efb580-6e7b-11e9-8139-63baca48f579.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04.6 LTS
 - Mono Version: Radarr is running as a docker container - https://hub.docker.com/r/linuxserver/radarr/

**Debug Logs**
[radarr-debug.log](https://github.com/Radarr/Radarr/files/3144020/radarr-debug.log)

PS: Please let me know if you need anything else to help troubleshoot the issue.

**Comment by jalim** [comment]
I am seeing the exact same behaviour at the moment.  I have all 1080p qualities set to unlimited file size but this isn't being respected and a random value is being used as the max instead!

**Comment by ak2766** [comment]
I pushed my upper limit to 4.40GB and now that particular item doesn't have the exclamation.  However, it still will not download automatically!

**Comment by fryfrog** [comment]
There is an absolute size limit in indexer settings, I believe.

And size limit is scaled by play time.

And the automatic downloading doesn't work like you think. Just click the search button for automated search, or use the search tab and pick the one you want.
