### ISSUE TITLE
IMDb watchlists not working

### ISSUE THREAD

**Issue by Hezkore** [Radarr/Radarr#3508]
I'm no longer able to add any IMDb lists.
It doesn't work via "Radarr Lists" nor "RSS List".

I'm guessing this is related to Issue #3504

My IMDb list is public:
![image](https://user-images.githubusercontent.com/1727541/57185228-da358a80-6ec7-11e9-9dac-510453dfa594.png)

Here's the list being added via the Radarr API:
![image](https://user-images.githubusercontent.com/1727541/57185233-f3d6d200-6ec7-11e9-88e2-484dec765aa9.png)
And failing.

Here's the list being added via RSS IMDd List:
![image](https://user-images.githubusercontent.com/1727541/57185234-fe916700-6ec7-11e9-8248-7b1b83f1c6c9.png)
And failing.

Here's the list being added via RSS IMDb Watchlist:
![image](https://user-images.githubusercontent.com/1727541/57185238-0cdf8300-6ec8-11e9-8ca7-92f68f8dfd5a.png)
And failing.

 - OS: Debian 4.9.130-2
 - Mono Version: 5.18.0.240 (tarball Wed Jan 16 09:10:58 UTC 2019)
 - Version 0.2.0.1293

Logs:
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/3144887/radarr.debug.txt)

**Comment by Krandor1** [comment]
Known issue.  IMDB has blocked the current radarr API requests.

**Comment by davenicoll** [comment]
So, uh, what's the plan @Krandor1? Is this temporary, do radarr's settings need to be less aggressive, should there requests be proxied to avoid coming from a single IP? Happy to help, if needed.

**Comment by galli-leo** [comment]
API is back up for now, we are working on less temporary solutions.

**Comment by georgecarstoiu** [comment]
Issue is back. Cannot retrieve IMDB watchlist

**Comment by fidelix** [comment]
API seems is down again.
