### ISSUE TITLE
Searching for a movie without an IMDB ID associated with its TMDb entry returns unrelated results

### ISSUE THREAD

**Issue by Vxrl** [Radarr/Radarr#3509]
**Describe the bug**
Searching for a movie without an IMDB ID associated with its TMDb entry returns unrelated results.

For example, the movie [Ari Shaffir: Paid Regular](https://www.themoviedb.org/movie/318974-ari-shaffir-paid-regular) has no IMDB ID linked to it, which can be confirmed by vising the ["External IDs" edit page](https://www.themoviedb.org/movie/318974-ari-shaffir-paid-regular/edit?active_nav_item=external_ids).

When searching for the movie, Radarr uses nothing (an empty string) as the query.
For this movie, debug logs show Radarr querying `https://passthepopcorn.me/torrents.php?action=advanced&json=noredirect&searchstr=`. Notice that the value of `searchstr` is nothing.

For a movie such as [Guardians of the Galaxy](https://www.themoviedb.org/movie/118340-guardians-of-the-galaxy) with an IMDB ID associated with its TMDb entry, Radarr correctly queries (`https://passthepopcorn.me/torrents.php?action=advanced&json=noredirect&searchstr=tt2278388`). Notice that the value of `searchstr` is `tt2278388`.

**Extra information**
When the movie "Ari Shaffir: Paid Regular" is added, trace logs show Radarr getting metadata from the following URLs:
`https://api.themoviedb.org/3/movie/318974?api_key=REDACTED&append_to_response=alternative_titles%2Crelease_dates%2Cvideos&language=EN`
`https://api.radarr.video/v2/mappings/find?tmdbid=318974`
In both responses, `imdb_id` is set to the empty string.

**To Reproduce**
1. Add the movie "Ari Shaffir: Paid Regular" in Radarr
2. Go to the movie page and click "Search"
3. See the totally unrelated search results, which are a result of the search being performed without any query

**Expected behavior**
Radarr should display an error message indicating that the search cannot be performed, because the IMDB ID is not known. Ideally, Radarr could attempt to find the IMDB ID elsewhere (by searching IMDB, for example), or it could allow the user to manually specify it.

**Screenshots**
Unrelated search results for the movie "Ari Shaffir: Paid Regular":
![https://i.imgur.com/z35tB0K.png](https://i.imgur.com/z35tB0K.png)

Logs for the search, showing the empty `searchstr`:
![https://i.imgur.com/TvMQIog.png](https://i.imgur.com/TvMQIog.png)

No IMDB ID associated with the TMDb entry:
![https://i.imgur.com/ZOUBqXP.png](https://i.imgur.com/ZOUBqXP.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 0.2.0.1293

**Debug Logs**
Below are logs for a search for the movie "Ari Shaffir: Paid Regular". The results are totally unrelated to the movie.
[https://pastebin.com/raw/Y9DzmVJ5](https://pastebin.com/raw/Y9DzmVJ5)

**Comment by Qstick** [comment]
Shouldn’t we fallback to search by name in this case?

**Comment by jalmansor** [comment]
> Shouldn’t we fallback to search by name in this case?

I've wondered why that isn't the default behavior myself, and why the options in the indexer settings for search by title and search without year always confused me. Especially when using something like NZBHydra, where not having that fallback means certain indexers don't get hit at all.

It's also possible I have no clue what I'm talking about.
