### ISSUE TITLE
Quality Size not set in GB

### ISSUE THREAD

**Issue by grego31430** [Radarr/Radarr#3513]
**Describe the bug**
The quality size is not set correctly

**To Reproduce**
1. Go to 'Movie'
2. Click on 'a Movie'
3. Click on Search

**Screenshots**
![image](https://user-images.githubusercontent.com/22960003/57372439-f8380f00-7195-11e9-9567-48008e087496.png)

**Desktop (please complete the following information):**
 - OS: Windows 10/Host: Debian 9
 - Mono Version: 5.18 (Only needed under Linux and Mac, found under System -> Status)
 - Browser and Version last firefox
 - Version 0.2.0.1344

**Debug Logs**
I don't know where is the Log file ?

**Comment by tkdrob** [comment]
Have you looked at your Quality Settings? You need to adjust the sliders

**Comment by grego31430** [comment]
Oups, I have forgot the Quality screenshot ....
So there is my quality settings 
![image](https://user-images.githubusercontent.com/22960003/57537802-50624300-7347-11e9-8bbb-455db22cfd98.png)

**Comment by tkdrob** [comment]
Movie database says its 1 minute in length so its not a Radarr issue. I'm not sure how you can change that. Perhaps someone else here can let you know

**Comment by fryfrog** [comment]
If the run time is wrong, fix it. Info comes from TMDb.
