### ISSUE TITLE
Trakt Box Office list - ratings not working

### ISSUE THREAD

**Issue by zatdin** [Radarr/Radarr#3522]
**Describe the bug**
Fetching Trakt Box Office list with ratings 75-100 returns movies with lower than specified ratings. Tested with trending and popular and they both work as expected. Checked logs that the query string is correct. Not sure if it's Radarr, or Trakt issue.

**Screenshots**
Only 1 of these movies have ratings >75% from Trakt Box Office page
![image](https://user-images.githubusercontent.com/50505882/57563375-d4f8a400-73cf-11e9-8318-40f8f89add80.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Radarr Version 0.2.0.1344

**Debug Logs**
[FetchTraktBoxOffice.txt](https://github.com/Radarr/Radarr/files/3168498/FetchTraktBoxOffice.txt)

**Comment by galli-leo** [comment]
This is something on Trakt's side then.
