### ISSUE TITLE
No Movies infos (not when adding nor refreshing)

### ISSUE THREAD

**Issue by ToXinE** [Radarr/Radarr#3524]
**Describe the bug**
Not getting any informations about movies when adding them or when refreshing information but there is some descriptions in TMDB (in french and in english).
I'm French maybe it's related to my browser language ?

**To Reproduce**
1. Add a movie
2. No movies informations displayed

![image](https://user-images.githubusercontent.com/6205053/55060148-1841c200-5071-11e9-9cfc-1a5a303818c9.gif)

1. Search for a movie already added in Radarr
2. click refresh 
2. No movies informations displayed

**Expected behavior**
Movies informations should be displayed when accessing a movie.

**Desktop (please complete the following information):**
 - Radarr Version 0.2.0.1344
 - OS: Ubuntu 18.04.2 LTS
 - Mono Version: 5.20.1.19 (tarball Thu Apr 11 09:02:17 UTC 2019)
 - Browser and Version Firefox Quantum 60.6.3esr (64 bits)

**Debug Logs**
![log](https://i.imgur.com/xxI0hhG.png)

**Comment by galli-leo** [comment]
no logs

**Comment by ToXinE** [comment]
``9-5-30 20:55:25.2|Info|DownloadDecisionMaker|Processing 345 releases
19-5-30 20:55:38.2|Info|RssSyncService|RSS Sync Completed. Reports found: 345, Reports grabbed: 0
19-5-30 21:10:25.0|Warn|StaticResourceMapper|File /opt/Radarr/UI/Content/Images/favicon/manifest not found
19-5-30 21:10:36.2|Warn|MediaCoverMapper|File /var/lib/radarr/.config/Radarr/MediaCover/1378/poster.jpg not found
19-5-30 21:12:35.9|Warn|StaticResourceMapper|File /opt/Radarr/UI/Content/Images/favicon/manifest not found
19-5-30 21:13:25.7|Info|MovieService|Deleted movie [Veronica Mars (2014)][tt2771372, 177494]
19-5-30 21:13:29.4|Warn|MediaCoverMapper|File /var/lib/radarr/.config/Radarr/MediaCover/1378/poster.jpg not found
19-5-30 21:14:20.1|Info|MovieService|Adding Movie [Veronica Mars (2014)][, 177494] Path: [/media/NAS/Films/Veronica Mars (2014)]
19-5-30 21:14:20.2|Info|RefreshMovieService|Updating Info for Veronica Mars
19-5-30 21:14:22.9|Info|DiskScanService|Scanning disk for Veronica Mars
19-5-30 21:14:23.7|Info|MovieService|Linking [Veronica Mars.(2014).WEBDL-480p.XviD.AC3-NIKOo.avi] > [[Veronica Mars (2014)][tt2771372, 177494]]
19-5-30 21:14:23.7|Info|DiskScanService|Completed scanning disk for Veronica Mars
19-5-30 21:14:23.7|Info|MovieScannedHandler|[Veronica Mars] was recently added, performing post-add actions
19-5-30 21:14:23.9|Info|NzbSearchService|Searching 5 indexers for [Veronica Mars]
19-5-30 21:14:23.9|Info|ExistingMetadataImporter|Found 1 existing metadata files
19-5-30 21:14:23.9|Info|ExistingSubtitleImporter|Found 0 existing subtitle files
19-5-30 21:14:24.0|Info|ExistingOtherExtraImporter|Found 0 existing other extra files
19-5-30 21:14:24.0|Info|ExistingExtraFileService|Found 0 extra files
19-5-30 21:14:24.2|Info|MediaCoverService|Testing: NzbDrone.Core.Messaging.Commands.CommandQueueManager, 2657
19-5-30 21:14:24.3|Info|MediaCoverService|Downloading Poster for [Veronica Mars (2014)][tt2771372, 177494] http://image.tmdb.org/t/p/original/nS3L07mQfcNJcisLEKgi8fWoBS1.jpg
19-5-30 21:14:24.8|Info|MediaCoverService|Downloading Fanart for [Veronica Mars (2014)][tt2771372, 177494] http://image.tmdb.org/t/p/original/s8891Ox7a5O7Gk0SbPUOY6EKiGN.jpg
19-5-30 21:15:30.0|Info|DownloadDecisionMaker|Processing 82 releases
19-5-30 21:15:35.7|Info|Sabnzbd|Adding report [Veronica.Mars.2014.LIMITED.MULTi.1080p.BluRay.x264-LOST] to the queue.
19-5-30 21:15:36.8|Info|DownloadService|Report sent to Sabnzbd. Veronica.Mars.2014.LIMITED.MULTi.1080p.BluRay.x264-LOST
19-5-30 21:15:36.8|Info|MovieSearchService|Movie search completed. 1 reports downloaded.

**Comment by ToXinE** [comment]
is that enough ?
