### ISSUE TITLE
Build 0.2.0.1344 has network error (not in prior releases)

### ISSUE THREAD

**Issue by rkmfl** [Radarr/Radarr#3525]
I have **Radarr**, **Sonarr** and **sabnzbd** running on **Win10 Pro**

(Radarr dev build# 0.2.0.1344 ... Win10 v1803)

&#x200B;

Radarr has been working fine for some time.  When the  May 5th 0.2.0.1344 build was released, all movie NZB searches stopped working on my system.

&#x200B;

My first assumption was that a dependency had become corrupt/stomped-on/etc.  I then tried re-installing Radarr from a fresh download (I did keep the same config).  That had no effect.

&#x200B;

**Trace-level debug of boot:**  [https://pastebin.com/tVDvGncc](https://pastebin.com/tVDvGncc)

&#x200B;

Or if it saves you time, the error I notice in those logs:

>**There are no more endpoints available from the endpoint mapper. (Exception from HRESULT: 0x800706D9).**  
>  
>at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)  
>  
>at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)  
>  
>at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)  
>  
>at System.Activator.CreateInstance(Type type, Boolean nonPublic)  
>  
>at System.Activator.CreateInstance(Type type)  
>  
>at Radarr.Host.AccessControl.FirewallAdapter.IsFirewallEnabled() in C:\\projects\\radarr-usby1\\src\\[NzbDrone.Host](https://NzbDrone.Host)\\AccessControl\\FirewallAdapter.cs:line 103

&#x200B;

This implies a firewall issue.  For reference, my Windows Filtering (WFP) is on (I use Simplewall as a more effective manager of the intrinsic *Windows Filtering Platform (WFP)*).

&#x200B;

Later there are also issues with core & LINQ on this system.

&#x200B;

Finally, there are a few SQLite messages in that pastebin, showing locked.  I have nothing else on this system that utilizes SQLite.  In fact the system is pretty vanilla / not much else other than **Sonarr** & **sabnzbd**.

&#x200B;

Thanks you!

**Comment by galli-leo** [comment]
The network error can be ignored, it's just a warning. The other error seems to stem from an invalid Language format tag inside a custom format. make sure those are correct.
