### ISSUE TITLE
Organize is not moving movie folder content.

### ISSUE THREAD

**Issue by Mrpink200** [Radarr/Radarr#3526]
Hello

I find something strange : When in movie editor, assigning a new created path to a movie, then clickin on save then organize  does not move the movie content to the new path.
An empty new path (foder) is well created, but the movie files are not move.

The logs does not show any error

Anyone else ? Is it normal ?
I would like to move all my son movies to a dedicated path  ...

**Comment by galli-leo** [comment]
This is currently not implemented, but there already exist issues for requesting this feature.
