### ISSUE TITLE
Parse fails to find movie

### ISSUE THREAD

**Issue by devolution2409** [Radarr/Radarr#3532]
**Describe the bug**
Parser fails to find movie when two names are inside the title

Search for "L'enfant du passé" using the indexer torrent9.

You'll find movies named like this: Hjemsøkt (L'enfant du passe) 2018 FRENCH WEBRIP 1080p
Parser fails instead of adding the movie automatically.

**Expected behavior**
Movie should be added to download queue, and language should be french

**Screenshots**
![image](https://user-images.githubusercontent.com/7950325/57987658-c885e280-7a84-11e9-8ce5-d7467dd3e777.png)

**Desktop (please complete the following information):**
 - Radarr docker version. Image provided by linuxserver.io 
 - Radarr version 0.2.0.1293
 - Mono version 5.20.1.19 (tarball Thu Apr 11 09:09:21 UTC 2019)

**Comment by devolution2409** [comment]
Also, forcing add the torrent didn't work, i had to add it manually using deluge web ui.

AND manual import won't work. The movie shows up in the "wanted" section, but when i manual import it, it fails saying "movie should be chosen for each selected file"

But it doesn't appear in the list..

![image](https://user-images.githubusercontent.com/7950325/57987868-d426d880-7a87-11e9-8a74-bfaf7229242a.png)

**Comment by galli-leo** [comment]
Only 20 movies show up in the list. You need to filter for it. The problem is the title isn't matching, since it has both alternative titles in it. Radarr is expecting either one, but not both.
