### ISSUE TITLE
Reorder qualities in profiles

### ISSUE THREAD

**Issue by Wdavery** [Radarr/Radarr#3533]
Due to storage constraints I prefer to keep all media at 1080p, but some releases may only be found (or successfully downloaded) in 4k. Radarr currently prioritizes higher resolutions if I have them enabled, with no way to reorder them.

Sonarr has a very useful feature where you can reorder qualities within each profile.

Such as ordering 720 -> 2160 -> 1080, so it will download 1080 if available and only use 2160 as a backup.

**Comment by shaggyblue** [comment]
This can already be done.  Just make sure you switch "Advanced Settings" to shown.
