### ISSUE TITLE
Radarr activity queue from Sonarr

### ISSUE THREAD

**Issue by shudack** [Radarr/Radarr#3536]
Hi,

In activity queue of Radarr, show the info from Sonarr... It's normal?

**Printscreen:**
![image](https://user-images.githubusercontent.com/17851196/58369701-f8563f80-7ef5-11e9-8ffd-e4cc78e501ed.png)

**Software:**
- Radarr version 0.2.0.1344
- Sonarr version 2.0.0.5322
- OS: Linux 4.9.177-28 aarch64-with-Ubuntu-18.04-bionic

Best regards,
Shudack

**Comment by hotio** [comment]
That happens when you don't setup categories in the download client.

**Comment by shudack** [comment]
Thanks!
