### ISSUE TITLE
Add an option to switch behaviour for release group name grabbing

### ISSUE THREAD

**Issue by MoeJoe87** [Radarr/Radarr#3537]
**Is your feature request related to a problem? Please describe.**
The problem is about the grabbing of the {Release Group} tag. I would like to have my pattern as follow for movie filenames: 

{Movie.Title}.{Release Year}.German.{Edition.Tags}.{Quality.Full}.{MediaInfo VideoCodec}{-Release Group}

But the problem is that still a lot release groups name their files wrong...with the release group at the beginning and thats ending in wrong {Release Group} Tag. For now i have a workaround recommend by somebody on Discord to use just: {Original Title} as the Movie filename. Now it is grabbing the whole filename from the search title. That looks ok but results in other issue like foldername is German Movie Title but Movie filename is English, cause some Release Groups name it like that. 

Other Issue is when make a manual download, then there isnt a search title and it is importing the weird filename.

**Describe the solution you'd like**
For now it is grabbing the {Release Group} from filename, would be nice to have an option to switch that behaviour to grab it from the download folder, where radarr is searching for the files to import. In every case i had the folder name which is being downloaded, is named correctly with the release group at the - end. Would also work for manually downloaded files for the auto import later.

**Describe alternatives you've considered**
Otherwise you could switch with an option that it only grabs the release group name from the search title instead of using the {Original Title} tag. But then it would not work for manually donwloaded movies as the search title is not available. 

**Additional context**
I like the first option better, cause its would work also for manually downloaded movies. Radarr is looking already on the right place for the files, so why not grab the info from the foldername which was downloaded. With that option i could use my above mentioned pattern for movie filenames and my problems are gone.

**Comment by Qstick** [comment]
Dupe #2909
