### ISSUE TITLE
movie not sorted and shows as missing

### ISSUE THREAD

**Issue by inasua** [Radarr/Radarr#3539]
**Describe the bug**
german dubbed movies dont get renamed and moved after the download finished and they are displayed as missing

**To Reproduce**
1. set profile language to german
2. go to add movies
3. add a movie
4. movie gets downloaded but not renamed and moved to the selected path

**Expected behavior**
movie should be moved to the select path with the correct name (this works fine if english is selected as language)

**Screenshots**
![Screenshot_2019-05-28 Der Herr der Ringe - Die Gefährten - Radarr](https://user-images.githubusercontent.com/50951133/58470869-e5847a80-8142-11e9-9dff-16927e4def91.png)

radarr movies
![Screenshot_2019-05-28 Movies - Radarr](https://user-images.githubusercontent.com/50951133/58470870-e61d1100-8142-11e9-9ca9-46be1040a90e.png)

sabnzbd completed download
![Screenshot_2019-05-28 SABnzbd](https://user-images.githubusercontent.com/50951133/58470866-e5847a80-8142-11e9-904d-456ee5db7db9.png)

**Desktop (please complete the following information):**
 - Mono Version: 5.10.1.20 (tarball Thu Mar 29 10:48:35 UTC 2018)
 - Version: 0.2.0.1344

**Debug Logs**

- trace https://paste.ee/p/L53zE
- debug https://paste.ee/p/d5E8Z
- log https://paste.ee/p/drlfm

**Comment by galli-leo** [comment]
Movie is not named properly once downloaded. (Contains extraneous SEE)
