### ISSUE TITLE
Wrong movies gets downloaded

### ISSUE THREAD

**Issue by Dragao75** [Radarr/Radarr#3542]
I have Shazam! in my queue/searchlist and the wrong movies gets downloaded (Captain Marvel) 

I first though this was just because of the naming but on a remove movie the same file was downloaden.

I can't see why. Everywhere I look I see Captain Marvel... 

What I did notice was under Titles the name Captain Marvel pops up. (source TMDB) following that link brings me to.. Shazam! .. 

No idea what goes wrong.

How to resolve this?

**Comment by M1cr0M1nd** [comment]
Shazam! is called Captain Marvel, very confusing I know, but the only one to blame is DC.

**Comment by fryfrog** [comment]
Wut?

**Comment by fryfrog** [comment]
Oh shit, it totally is...

`Also known as: "Billy Batson and the Legend of Shazam!", "Captain Marvel", "Franklin" and "York".`

**Comment by ff4500** [comment]
Hah. Just had this happen to me too. And it was both the 4k and 1080p version.

Is there a way to blacklist a title from a list of filenames, like on failed downloads? Not sure how often this is going to come up, but it's sure annoying.

**Comment by henryschade** [comment]
So it is not justy me.  :)

**Comment by alaneo** [comment]
Hi people. I have identical problem but with Dark Phoenix movie. Radarr says that this move is **Also known as: "Teen Spirit", "X-Men: Dark Phoenix" and "X-Men: Supernova". **, and of course the movie Teen Spirit is downloaded instead - how frustrating. Is there a way to tell Radarr to **not** use **Also known as:** titles? Or maybe add this feature to next release? Would be very helpful. Many thanks... Alan

**Comment by ff4500** [comment]
@alaneo Just checked my downloads and I have the same problem. First Shazam/Captain Marvel, now Dark Phoenix/Teen Spirit. I agree, the option to exclude aka titles would be helpful. Maybe in advanced preferences?

**Comment by jayntguru** [comment]
Same issue here with Dark Phoenix.
