### ISSUE TITLE
Searching for new Movie results in ALL results found being sent to downloader

### ISSUE THREAD

**Issue by Mizerka** [Radarr/Radarr#3547]
**Describe the bug**
Added 4 movies through reccomended, correct path, physical, add and search. Left it for a bit to run through indexers etc (jackett) and found deluge dead, restarted and died because radarr decided to add over 100 torrents at once, 4 movies, each with 20+ versions. Once deluge was back up, radarr reported only single file being downloaded in activity and in the files tab of movie itself.

**Expected behavior**
A single version/best match is downloaded on search and only updates once better/proper release is added until cutoff

**Screenshots**
![image](https://user-images.githubusercontent.com/45487386/58796730-0262f700-85f6-11e9-8c3e-7fc0d1075d04.png)

**Desktop (please complete the following information):**
 - OS: Unraid Docker

 Version

- Mono Version 5.16.0 (makepkg/bb3ae37d71a Sat Dec 8 13:21:35 CET 2018)

- Version 0.2.0.1344

**Debug Logs**
not in debug mode, not replicated since, logs clearly show its just keep trying to add more releases

info logs - 
[radarr.txt](https://github.com/Radarr/Radarr/files/3247175/radarr.txt)
[radarr.0.txt](https://github.com/Radarr/Radarr/files/3247176/radarr.0.txt)
[radarr.1.txt](https://github.com/Radarr/Radarr/files/3247177/radarr.1.txt)
[radarr.2.txt](https://github.com/Radarr/Radarr/files/3247178/radarr.2.txt)

**Comment by Mizerka** [comment]
wiped torrents state instead of wasting hours cleaning up, couldn't replicate when searching again for wanted movies

**Comment by fryfrog** [comment]
I think I've seen this reported for usenet too, when the download client was unreachable it just kept queuing up downloads. I think this is a real bug, but I'm not sure what it is.

**Comment by Qstick** [comment]
I think this should be fixed on v2 branch but need to confirm, as @fryfrog mentioned I think it has something to do with pending release handling when client is unavailable
