### ISSUE TITLE
add support for {ReleaseGroup} to detect QxR encoders in movie naming

### ISSUE THREAD

**Issue by joaomconde** [Radarr/Radarr#3550]
**Is your feature request related to a problem? Please describe.**
Most of QxR encoders (Tigole, FreetheFish, Silence, afm72, etc) add their name without the "-" so it doesnt get parsed as a {ReleaseGroup} resulting in a "file name (radarr)" instead of "file name (Tigole)" for example.

Im asking for support on this issue because I think QxrR are becoming the main x265 content encoders.

**Describe the solution you'd like**
Id like to have the encoder properly added as a {ReleaseGroup}. Maybe for started add a list of known encoders that do this and if radarr detects them, add them to the filename.

**Describe alternatives you've considered**
An even better option would be leaving this to the user choice, maybe by implementing some sort of conditional naming option. For example let users have the option to add certain different things to the filename if some conditions are met.

Sorry if this has been discussed before or if what im asking is too much to implement, Im just trying to suggest something i think would be usefull for the project.

Thank you

**Comment by TheCatLady** [comment]
This is also an issue for UTR encodes (e.g., Joy).

**Comment by bakerboy448** [comment]
no plans at this time to customize for groups that do not follow scene rules

**Comment by bakerboy448** [comment]
PR will handle releases formatted as follows:

"GroupName)" for the following:

Tigole
Joy
YIFY
YTS.MX
FreetheFish
afm72

"GroupName" Exact Name without a trailing ")" for the following:
KRaLiMaRKo
E.N.D

Others will need to be suggested and added by hand going forward

**Comment by TheCatLady** [comment]
Other encoders which should be matched with a trailing ")":

- Bandi
- Ghost
- ImE
- Kappa
- MONOLITH
- Qman
- RCVR
- RZeroX
- SAMPA
- Silence
- t3nzin
- Vyndros

**Comment by bakerboy448** [comment]
@TheCatLady have some release names that can be used as test cases? :)

**Comment by TheCatLady** [comment]
@bakerboy448 I can help put together a list, but just searching for [QxR] or [UTR] will yield results for all but Vyndros, who releases independently and not as part of a group.

**Comment by pound1324** [comment]
@bakerboy448 I'm new to radarr, and looking for a way to only download [QxR] uploads. Does this allow for creating a custom format to download to do that?

**Comment by bakerboy448** [comment]
@pound1324 you don’t need this to do that with a custom format.

Actually you can just take the RegEx I’m using in my commit and create a custom format with it, that should work

**Comment by pound1324** [comment]
@bakerboy448 is there a way to do it through the WebUI?

**Comment by bakerboy448** [comment]
@pound1324 

https://trash-guides.info/Radarr/V3/Collection-of-Custom-Formats-for-RadarrV3/

And

https://trash-guides.info/Radarr/V3/How-to-importexport-Custom-Formats-and-truly-make-use-of-it/

Questions like this are best suited for Reddit or discord tho

**Comment by pound1324** [comment]
@bakerboy448 Okay, thanks for the help
