### ISSUE TITLE
[Feature Request] Movie Folder Format - Empty String

### ISSUE THREAD

**Issue by Pantar2205** [Radarr/Radarr#3554]
Settings > Media Management > Movie Naming > Movie Folder Format

Unable to leave the string empty and just simply not use Movie Folders at all.

(or to add a string that gives the same affect)

I don't think this is a duplicate of #153 as that's looking for custom folder profiles which I would presume is a lot more complicated to implement (?)

**Comment by Qstick** [comment]
Nah, it’s pretty nunchucks #153, Radarr relies on a movie folder, both requests rely on breaking that link. Going to close this and just leave that one open.
