### ISSUE TITLE
Bad Request (Invalid host) when accessing Radarr via hostname instead of IP

### ISSUE THREAD

**Issue by glc650** [Radarr/Radarr#3555]
**Describe the bug**
I have Radarr installed on a 2018 Mac Mini with VLANs setup under macOS (so multi-homed).  I have one of the IPs from the VLANs setup in Settings > General > Bind Address.  When I access Radarr via this IP everything is fine but when I try to access via a hostname that resolves to that same IP I get the following error:

Bad Request (Invalid host)

**To Reproduce**
1. Try accessing Radarr via hostname instead of IP from any browser/client (I've tried Safari, Chrome & FF on macOS/Win 10 & Safari & FF on iOS).

**Expected behavior**
The hostname resolves to the IP specified in Radarr's settings so I would expect it to work the same as when I access via IP.

**Desktop (please complete the following information):**
 - Mono Version: 5.20.1.19; installed on the Mac Mini where Radarr is installed
 - Browser: Safari/Chrome/Firefox
 - Version: latest versions of all 3

**Comment by LordMike** [comment]
I use hostnames always. Could you try binding to `0.0.0.0` ?

Your hostname may also resolve to an IPv6 address, which you haven't bound to, so that wouldn't work.

**Comment by glc650** [comment]
I ended up binding to * and adding pf firewall rules to allow access to the desired ip and block access to the other.
