### ISSUE TITLE
Multi-language Rename

### ISSUE THREAD

**Issue by zpengcom** [Radarr/Radarr#3559]
Hello, I am Chinese

 I want to use multiple languages ​​to set the folder name for the movie: 
**Chinese movie name. English movie name (year)**

such as...
Standard Movie Format：{Movie Title_ZH} {Movie Title_EN} ({Release Year}) 
Movie Example: 电影名 The Movie Title（2019）

**Comment by Mrpink200** [comment]
Great Idea. I would like something similar to unlick search profile language from the movie rename language. I search all movie language on a dedicated french tracker but i would like to have my movies renamed in french not in the default english language. the feature explained by zpengcom would suit the need perfectly !!

**Comment by zpengcom** [comment]
I can implement the naming I want in TinyMediaManager, but it will conflict with the radar naming.
if let radar define a display language for the movie, so that {Movie Title} gets the localized movie name from www.themoviedb.org, not just English.
I believe the feature will be great.
