### ISSUE TITLE
Auto group movie series in parent folder

### ISSUE THREAD

**Issue by jababda** [Radarr/Radarr#3560]
Had a look and don't think this is currently possible but I'd love Radarr to auto group movie series together. I.e. Iron Man 1,2,3 to all be a in a parent folder call Iron Man Collection (or similar).

Right now manually create the folders and point Radarr at the relevant folder so its tracked correctly.

Small thing but it would be really cool if this was possible :).

**Comment by Qstick** [comment]
Needs #112 to be implemented
