### ISSUE TITLE
Set interval times / option to disable tasks

### ISSUE THREAD

**Issue by wessel145** [Radarr/Radarr#3563]
#840 made it possible to change the interval time "Check For Finished Downloads Interval".
I would love to have more control over the other tasks as well. An option to set a custom interval, timing or even disable the task.

Reason: Radarr is spinning up my array once a day to scan the files, this is fine, but the timing isn't controllable. All other daily tasks on the machine run at a specific time so my system is energy efficient, unfotunately radarr doesn't support adjustments in the tasks.

**Comment by jalmansor** [comment]
I'm all for this, though regarding checking for finished downloads, I think the effort to move to a websocket would be a better solution (though I have no idea yet how feasible that is with the existing download clients).

**Comment by mr-honest** [comment]
I believe these task running intervals are hardcoded into the code.
It should quite easily be something that could be changed in the config.xml file. 
And if nothing is there, it should revert to default values hardcoded in the source code. 
Or even better, in the gui, a possibility to change the values. I cannot believe this issue can be so difficult to implement. And if I could do it myself, I would have. 
![image](https://user-images.githubusercontent.com/2685211/62944783-b5618500-bddd-11e9-98b4-b62097d54d50.png)

**Comment by fryfrog** [comment]
This sounds like a great way for people who have no idea what they're doing to make their Sonarr/Radarr not work right and I kind of hope it doesn't happen. Or at least, if it does it should have constraints that keep the limits w/in normal tolerances and doesn't allow actual disabling.

**Comment by Qstick** [comment]
I'm not too keen on doing this either, sounds like a great way to create a ton of support requests

**Comment by Qstick** [comment]
Closing in lieu of #2975 and #3556
