### ISSUE TITLE
Torrent keyword option

### ISSUE THREAD

**Issue by akbasemre1** [Radarr/Radarr#3565]
Hey,

As everyone knows there are so many rips like webdl netflix rip amazon rip etc. I really prefer amzn rips when it's  available so if there is a option like adding a keyword so radarr download torrents included that keyword. Same for excluding some keywords to avoid some group releases etc. I tried to make it possible with limiting file size but couldn't work it out. I am open for suggestions.

**Comment by LordMike** [comment]
You should be able to do this with Custom Formats, @akbasemre1 ... I considered doing it myself, but decided regular operations was ok for me. ..

I should do it though.. as my TV prefers certain audio/video codecs..

**Comment by Qstick** [comment]
Yep, custom formats
