### ISSUE TITLE
Move files instead of copy.

### ISSUE THREAD

**Issue by Cookiezzz** [Radarr/Radarr#3566]
I'd like Radarr being able to move files on a mounted drive without having to download them and then reupload.

I have a seedbox, and my radarr location is on a server at home.

Seedbox layout:
/
/gdrive (Mounted Google Drive with rclone)
/gdrive/movies
/gdrive/files

![image](https://user-images.githubusercontent.com/2996654/59385391-80e13680-8d64-11e9-803e-236a9c88a2a3.png)

Homeserver:
Seedbox /root mounted with Netdrive over SFTP and assigned drive H:
![image](https://user-images.githubusercontent.com/2996654/59385342-67d88580-8d64-11e9-871d-362b4157414b.png)

Whenever rtorrent has downloaded a file, it puts it in the /gdrive/files/ directory.
Radarr is configured to put the file in the /movies/nameofmovie/ folder.

Whenever it does this it downloads the file from the seedbox, and then reuploads it. (Copy and delete I assume)
This causes unneeded traffic, and since my internet is 200/20 (Mbit) the uploading part takes ages.

If I however perform a simple move in cmd/powershell. The move is done within seconds.
Example:
![image](https://user-images.githubusercontent.com/2996654/59385490-bdad2d80-8d64-11e9-93a7-3be3188554d1.png)

Previous issues about this or a similar issue:
https://github.com/Radarr/Radarr/issues/949
https://github.com/Radarr/Radarr/issues/2800

Issue 949 says this could be solved with using a Custom Script. True, but the custom script gets triggered after Radarr has downloaded and uploaded the file to the right location.
Script example that should work.

> $movie_path = $env:radarr_movie_path
$movie_title = $env:radarr_movie_title
$movie_file = $env:radarr_moviefile_path
$sourcefile_path = $env:radarr_moviefile_sourcepath
$source_folder = $env:radarr_moviefile_sourcefolder
$logfile = "C:\debug.txt"
#Debug
#write-output "$movie_path $movie_title $movie_file $sourcefile_path $source_folder" | add-content $logfile
move $sourcefile_path $movie_path

My topic on Rclone about this issue:
https://forum.rclone.org/t/rclone-on-seedbox-gdrive-local-sonarr-radarr/10424

If anything about this is unclear, feel free to say so and I'll try to clarify.

**Comment by Cookiezzz** [comment]
Or perhaps a different solution: give us the option to run custom import scripts whenever the download clients reports the download is finished, but don't have radarr import it automatically.

**Comment by fryfrog** [comment]
Arrange your paths better or get rclone to do it better. This isn't a Radarr thing.

**Comment by fryfrog** [comment]
Does rclone / gdrive support hard links?

Deep in Sonarr/Radarr/Lidarr is the torrent behavior of *copy* for seeding torrents, only *moving* finished ones. I doubt this will ever change.

**Comment by Cookiezzz** [comment]
Rclone can't create hardlinks. It can read them without any issues.

Since you're saying it will move finished ones. If I have rtorrent copy the downloaded file to /gdrive/files and then stop the torrent. Any chance it will move the file from /gdrive/files to /gdrive/movies/nameofmovie/

**Comment by fryfrog** [comment]
There are some things Radarr/Sonarr can't do w/ rTorrent, I'm honestly not sure what'll happen if the torrent is paused/stopped when it imports. You'd probably need to hide the file from Sonarr and flip it to stopped/paused *before* revealing the file because there is a brief time when the torrent is *finished*, but hasn't moved, then stops and moves and restarts. I have to do this in my rTorrent setup. :/

**Comment by Cookiezzz** [comment]
I stopped the torrent as soon as it was done now, but it still did a copy (meaning down & upload). Not even sure about what could be a 'fix' anymore.

> 
> 
> Or perhaps a different solution: give us the option to run custom import scripts whenever the download clients reports the download is finished, but don't have radarr import it automatically.

Any idea if this would be a possibility for a feature request? When using the env variables I can whip up a script that will do the actual move, but then I'd need Sonarr/Radarr to not touch the file.

**Comment by Lonli-Lokli** [comment]
Is it possible to move this feature on top?
I am not too happy with current setup - now all my movie files can either be copied or hardlinked.
I prefer case when movies moved to Movie folder with stopped torrent, then hardlink created in Downloads folder and then if needed torrent seeding can be activated.
Is it doable?

**Comment by fryfrog** [comment]
No, and it doesn't matter which way you form a hard link. You're thinking
of a symlink.

**Comment by fryfrog** [comment]
If this ever happens, it'll probably come to Sonarr first and get ported to Radarr.

**Comment by agneevX** [comment]
[I have this same issue](https://forum.rclone.org/t/contd-file-is-written-twice-to-remote/14039) with qBittorrent but I am not seeding at all. Its downloading to 100%, then the state is changed to `Completed`, yet Sonarr/Radarr copies the file (`*.partial~`) instead of moving it, to the rclone mount. Because of this, twice the upload bandwidth ends up being used, which becomes an issue when there are monthly quotas.
