### ISSUE TITLE
[REQ] Bulk import of indexers from Jackett

### ISSUE THREAD

**Issue by backsofangels** [Radarr/Radarr#3569]
**Feature description**
The main issue of indexers adding is the absence of the possibility to have a bulk import from a file produced by Jackett

**Possible solution**
Of course this can be solved adding the possibility to import indexers from a JSON/similar file produced by Jackett, with a workflow similar to this one

- Add indexers to Jackett
- Hit the "Export indexers list" in Jackett
- Creation of a JSON file readable by Sonarr/Radarr
- Hit the "Import indexers from file" button in Sonarr/Radarr

Already submitted the request to Jackett and Sonarr.

**Comment by Qstick** [comment]
Jackett can use API to add

**Comment by hadim** [comment]
Would you reconsider this feature? Please see https://github.com/Jackett/Jackett/issues/5493#issuecomment-573713503 and https://github.com/Jackett/Jackett/issues/5493#issuecomment-573713503 for details.

**Comment by hadim** [comment]
According to a Jackett contributor, using the API directly in Jackett could be an option: https://github.com/Jackett/Jackett/issues/5493#issuecomment-573729775
