### ISSUE TITLE
Notifications to Rocket.Chat and Discord

### ISSUE THREAD

**Issue by Ulisses1478** [Radarr/Radarr#3570]
**Is your feature request related to a problem? Please describe.**
No, just features

**Describe the solution you'd like**
It will be cool have discord and rocket.chat on radarr

**Describe alternatives you've considered**
none

**Comment by Qstick** [comment]
What exactly are you asking for, Radarr already has notifications on downloads

**Comment by Ulisses1478** [comment]
> What exactly are you asking for, Radarr already has notifications on downloads

can you show me?

**Comment by Ulisses1478** [comment]
I just find it but i still want Rockett.chat and Discord notifications

**Comment by Qstick** [comment]
You can use slack for discord notification

**Comment by LeeThompson** [comment]
Just putting this in here in case someone wants to work on it.

Rocket.Chat's webhooks are JSON based:

https://rocket.chat/docs/developer-guides/rest-api/chat/postmessage/
