### ISSUE TITLE
Plans for Radarr v3 / preferred text in the title like Sonarr v3 handles them

### ISSUE THREAD

**Issue by Endda** [Radarr/Radarr#3573]
So I just got around to installing the new v3 preview of Sonarr and am loving it (have been using Lidarr with it as well).

Something I have noticed with this version 3 is that I can set a preferred tag or piece of text in the title of an entry and it will give that NZB bonus points (making it preferred).

Radarr has this feature as well but where Sonarr v3 is different is that as long as that item stays 'wanted' then it will grab a new copy of the item (from a new upload via an RSS update, for example) if the one I had doesn't have the preferred word/tags in it.

I like this because it will download the early copies that are uploaded but then continue looking for the 'better' one that I prefer (from a specific group, certain audio, etc.)

However, the current version of Radarr doesn't do this. It does let me put in preferred words/tags, but if I prefer something from a specific group (prefer, not require, which is the better method as not all groups release everything) the current version of Radarr will download the early release (as long as it fits the profile, like Bluray-1080p).

But if group A release a Bluray-1080p version, the current version of Radarr will grab it (even though it doesn't match the preferred group tag) like it's supposed to. . .but will then mark the entire thing has downloaded and stop looking for it.

The way Sonarr v3 handles things though. It will grab the early version and then keep looking for one that matches the preferred tag/text even though it's been marked as downloaded.

So I'm curious about if Radarr will end up upgrading to the Sonarr/Lidarr v3 fork. . .or if it will ever begin working the way those new versions work?

The way I see it. . .the only way for me to get this working is to create two separate profiles in the current version of Radarr and then being forced to switch from one to the other after it has grabbed the early copy

Sorry if this post comes off as a complaint or something. I love Radarr and would much rather use it in its current state than Couch Potato. I'm just hoping it evolves like the others in the scene.

__________________

More discussion from the community seen here
 - https://www.reddit.com/r/radarr/comments/c1mxeo/plans_for_radarr_v3_preferred_text_in_the_title/

**Comment by galli-leo** [comment]
Use custom formats
