### ISSUE TITLE
Cannot see movies on home page

### ISSUE THREAD

**Issue by jurpeedurp** [Radarr/Radarr#3574]
**Describe the bug**
Cannot see movies on home page

**To Reproduce**
Go to home page

**Expected behavior**
Should see movies on home page

**Screenshots**
<img width="490" alt="Screen Shot 2019-06-17 at 6 11 00 PM" src="https://user-images.githubusercontent.com/46579599/59645009-ccad2a80-912c-11e9-91aa-184140c0f380.png">

**Desktop (please complete the following information):**
 - OS: Docker
 - Mono Version: 5.20.1.19 (tarball Thu Apr 11 09:02:17 UTC 2019)
 - Browser and Version: chrome, safari, firefox
 - Version 0.2.0.1344

**Debug Logs**
[log.txt](https://github.com/Radarr/Radarr/files/3299301/log.txt)

**Comment by fryfrog** [comment]
You've gotten yourself stuck in a filter view that doesn't show any movies. Flush your local cache or try in an incognito window. I'm pretty sure there is an issue for this already, I'd suggest finding it, bumping it w/ a thumbs up and closing this one.

**Comment by jurpeedurp** [comment]
Yup, that was it.  Thanks.
