### ISSUE TITLE
Refreshing movie info does not remove alternative titles

### ISSUE THREAD

**Issue by n-shay** [Radarr/Radarr#3579]
**Issue Description:**
In my specific case, a certain movie added had a few alternative titles of completely different movies (probably by a troll). Radarr added them in the "Titles" tab and showed their source as TheMovieDB (TMDB). When I realized that a couple of weeks later, I checked the source and those alternative titles where removed.

An "update movie info" did not remove those titles.

**Workaround:**
I resulted to removing the movie completely and adding it back.

**Screenshots:**
Unfortunately I can't provide any screenshots or steps to reproduce.

**Environment:**
 - OS: Rasp Pi (Debian 9)
 - Mono Version: 5.20.1.19
 - Version: 0.2.0.1344

**Comment by Qstick** [comment]
Fixed in 8e43f5c4ae5d6d339775e9a69ab5f1f9b01b293b
