### ISSUE TITLE
email alert notification to multiple people

### ISSUE THREAD

**Issue by wifiuk** [Radarr/Radarr#3580]
can we have the ability to send email notification to more than one person?

So generally i would get all the alerts, but for specific movies, can it be sent to more than one person.

**Comment by pietervw** [comment]
I don't think that specifying email recipients per movie is really feasible. 
It would be more feasible to have multiple email recipients set up system-wide, but even then its quite a specific use case and not something the vast majority of users would need.

**Comment by Qstick** [comment]
You can control which movies use which notification with tags. In terms of multiple recipients, should be doable. But you can already do the above, just create two copies of the email notification, one should have no tag and be to your address (you will get all) the others should have a tag that correlates to the movies you want it sent for and then add the other recipients

**Comment by Casper042** [comment]
1) Is there a way to email multiple people now with the generic Email Notification option?  ; and , both give me errors about being able to send a test email.
Note that I don't care about Per Movie as being discussed above, just multiple recipients i general.

2) Can we have an option to send as BCC instead?  Don't want to expose peoples emails to each other if at all possible.  Thinking you either add BCC as an option or have an alternate drop down for distribution type: TO, CC, BCC as types.

Thx
