### ISSUE TITLE
Question about lists and skipping movies already in my library in Radarr

### ISSUE THREAD

**Issue by abarber229** [Radarr/Radarr#3581]
When adding a new list to radarr, will the new list added skip those movies that are already in my library and monitored if grabbed, or will they get remarked as monitored, and download again? I want to say that happened to me in the past, but before I add a new list again, I wanted to double check. I looked at github and browsed through reddit on r/radarr, but didn't see much regarding my question. Thank you in advance!

**Comment by majora2007** [comment]
If you add a list and it contains a movie already added to your Radarr instance, Radarr will not "re-download". It will just skip over it.

**Comment by Qstick** [comment]
Correct, it gets skipped/filtered
