### ISSUE TITLE
Update custom format/quality tags from file info

### ISSUE THREAD

**Issue by tbotcotw** [Radarr/Radarr#3586]
**Is your feature request related to a problem? Please describe.**

Source titles frequently don't contain audio info in them, so a release that has an AC3 or DTS track doesn't have AC3 or DTS marked in the title. I've built a custom format that prefers releases that have surround info in the title, which leads to files being "upgraded" from a release that has surround audio (but no tags in the title) to a second release that is (quality-wise) exactly the same... but its title calls out that it has a surround audio track.

**Describe the solution you'd like**

I'd like the quality tag on files to get automatically updated if a surround audio track is found in the file during file analysis. Radarr is already renaming the file based on how many tracks are found in the actual file, so this should be possible.

**Describe alternatives you've considered**

Currently, I update the custom format manually when I notice a file doesn't match.

If this is already possible, I apologize, I couldn't figure out how. I also searched your issues, so I don't think this is a duplicate, but if it is, I apologize again.

**Comment by lunks** [comment]
@Qstick could this one be reopened or should I open another feature request?

**Comment by bakerboy448** [comment]
Custom formats are calculated on the fly now in v3.

**Comment by bakerboy448** [comment]
> @Qstick could this one be reopened or should I open another feature request?

Let's see a 1 year + old issue that is CLOSED
And has no comments on it.

What do you think lol?

Regardless, likely a non-issue given the improvements with custom formats in v3

**Comment by lunks** [comment]
> > @Qstick could this one be reopened or should I open another feature request?
> 
> Let's see a 1 year + old issue that is CLOSED
> And has no comments on it.
> 
> What do you think lol?
> 
> Regardless, likely a non-issue given the improvements with custom formats in v3

This case is still an issue -- Sometimes the filename is missing i.e. Atmos support. But Radarr shows it just file under "Audio info". I'd like to be able to detect it from there instead of only the filename.

**Comment by bakerboy448** [comment]
So then create a custom format and included it in your renaming...?

**Comment by lunks** [comment]
> So then create a custom format and included it in your renaming...?

So there's no willing to support custom formats based on file info? Sometimes the torrent release name is also missing this information.

**Comment by bakerboy448** [comment]
Dude, did you bother to check out the link to trash's custom formats? If not.. look there. If you're confused after that, -> discord.

GitHub is not for support related issues. Custom formats are now calculated on the fly. There are no plans to force customize those.  Every GitHub comments spams whoever is subscribed with a notification.

**Comment by lunks** [comment]
> Dude, did you bother to check out the link to trash's custom formats? If not.. look there. If you're confused after that, -> discord.
> 
> Did you even bother to look at custom formats in v3? Clearly not. Otherwise you wouldn't be here commenting on this issue and would realize how powerful and flexible custom formats are.
> 
> GitHub is not for support related issues. Custom formats are now calculated on the fly. There are no plans to force customize those. Every GitHub comments spams whoever is subscribed with a notification.

I've read the guide to setup my own custom formats and I've been using them for a while. I've just reread to see if I missed something that's more recent, but it doesn't look like. Custom formats are using `ReleaseTitleSpecification` which, correct me if I'm wrong, use the title of the release instead of the downloaded file metadata (like audio info) which is what I'm after.

**Comment by Qstick** [comment]
Correct you'd have to get it in the filename using the naming tokens for mediainfo, CF should then pick it up.
