### ISSUE TITLE
Radarr with postprocessing script changes API behavior

### ISSUE THREAD

**Issue by A-Alhashem** [Radarr/Radarr#3591]
**Describe the bug**
I'm using bazarr to fetch subtitles from both Sonarr and Radarr. Which basically gets the scene name from these apps that is stored in their API and fetches a matching subtitle based on scene names.

Now I also use SABnzbd download client (usenet) along with a post processing script called [Sickbeard_mp4_automator](https://github.com/mdhiggins/sickbeard_mp4_automator). Reason for this is to change my mkv media file containers to mp4 for universal support on different media player clients (using Plex).

With Sonarr, even after using post processing script mp4, it still stores the original scene name (unless the filename was manipulated/renamed before sonarr grabs it).

With Radarr, without any post processing. It stores the scene name. With the post processing script, it somehow changes behavior, and bazarr could not locate the sceneName API from radarr anymore.

**To Reproduce**
Radarr stores the scene name without any post processing script.
When using pp script like mp4 (using it only to change containers mkv to mp4), it will not store scene name anymore.

Have tried using post processing script on download client, and tried using it on Radarr side. Both times it fails to store the scene name from the media file name.
(The file name has not been tampered or changed when testing).

**Expected behavior**
Radarr should also store the original file's scene name before radarr renames it. This way, other apps like bazarr could grab the scene name from its API to match it to the correct subtitle. Similar to how sonarr behaves atm.

**Screenshots**
![Radarr](https://user-images.githubusercontent.com/44728397/60356135-d78f7700-99d8-11e9-9f00-aec7697cee42.PNG)

**Additional Info**
I had also opened an issue with bazarr before this one, [link is here](https://github.com/morpheus65535/bazarr/issues/482),  I know little to none about how Radarr/bazarr communicates. But on bazarr's side, it looks like radarr changes its behavior when using pp scripts. Radarr's history of the media file import is still the same as original name (job name) as shown with the screenshot above.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Radarr Version: 0.2.0.1344
 - Sonarr Version: 2.0.0.5322
 - Bazarr Version: 0.8

**Debug Logs**
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/3340016/radarr.debug.txt)

**Comment by fryfrog** [comment]
The conversion should be done by the download client and in a way that it isn't complete until *after* it finishes. That way, the initial import will just work.

Also, transmuxing from `.mkv` to `.mp4` is a waste, this is something that even Plex running on a potato can do virtually for free. You'd be better served just not doing it entirely, unless you're literally putting the files onto iDevices that'll *only* play `.mp4` files. But you're using Plex, so you're not.

**Comment by kocane** [comment]
@A-Alhashem did you ever get this fixed someone? I have the exact same issue.
