### ISSUE TITLE
Radarr for Asustor not working

### ISSUE THREAD

**Issue by SoterDarkknight** [Radarr/Radarr#3592]
**Describe the bug**
Radar is not adding videos from folders on asustor NAS. Videos is in each separate folder.

**To Reproduce**
1. Go to 'movies'
2. Click on 'bulk import movies'
3. select folder with movies

**Expected behavior**
adding movies

**Desktop (please complete the following information):**
 - Asustor OS: 3.3.1.RIH2
 - Mono Version: 5.8.1.0.r9
 - Browser and Version Chrome- latest
 - Radarr ver. 1.0.0 from https://www.asustor.com/app_central/app_detail?id=642&type=6&model=

**Debug Logs**
Don't know where to find logs on Asustor

**Comment by fryfrog** [comment]
My guess is that Mono 5.8 is too old for TLS 1.2, which TMDB started enforcing fairly recently. I want to say 5.12 or 5.14 is the new minimum. Also, make sure you're not doing `MONO_TLS_PROVIDER=legacy`.

**Comment by fryfrog** [comment]
Also, there is no Radarr version 1.0.0.
