### ISSUE TITLE
Trakt Additional Parameters not working for user lists

### ISSUE THREAD

**Issue by jobrien2001** [Radarr/Radarr#3593]
**Describe the bug**
Trakt Additional Parameters only apply to trakt official lists and not trakt user generated lists.  

I am using this list as a source https://trakt.tv/users/pixelhunterprime/lists/netflix?sort=added,asc

A parameter "&X-Sort-By=added" on the "popular" list is correctly queried
```Debug|TraktImport|Downloading` List https://api.trakt.tv/movies/popular?years=2019-2020&genres=&ratings=&certifications=nr,g,pg,pg-13,r,nc-17&limit=1000&X-Sort-By=added```

A parameter "&X-Sort-By=added" on a user list is not queried
```Debug|TraktImport|Downloading List https://api.trakt.tv/users/pixelhunterprime/lists/netflix/items/movies?limit=100```

Also, none of the other filters such as years or certifications seem to work either.  Is this an API limitation and intended by design or bug?

**To Reproduce**
1. add the "popular" trakt list ass 
2. Add additional parameter &X-Sort-By=added
3. Click test and check log
4. Add a user list trakt list 
5. user = "pixelhunterprime", list name = "netflix"
6. Add additional parameter &X-Sort-By=added
7. Click test and check log

**Expected behavior**
If Parameter "&X-Sort-By=added" is added to atrackt user list this url should be queried
`https://api.trakt.tv/users/pixelhunterprime/lists/netflix/items/movies?limit=100&X-Sort-By=added`

**Desktop (please complete the following information):**
 - OS: Unraid
 - linuxserver docker
 - Version 0.2.0.1358

**Debug Logs**
```
19-6-29 04:51:15.9|Debug|TraktImport|Downloading List https://api.trakt.tv/movies/popular?years=2019-2020&genres=&ratings=&certifications=nr,g,pg,pg-13,r,nc-17&limit=100&X-Sort-By=added
19-6-29 04:51:16.4|Debug|Api|[POST] /api/netimport/test: 200.OK (677 ms)
19-6-29 04:51:58.9|Debug|DiskScanService|Scanning '/downloads/blackhole.radarr/' for video files
19-6-29 04:51:58.9|Debug|DiskScanService|0 video files were found in /downloads/blackhole.radarr/
19-6-29 04:51:59.4|Debug|Api|[GET] /api/system/task?sort_by=name&order=asc: 200.OK (13 ms)
19-6-29 04:51:59.8|Debug|Api|[GET] /api/system/task?sort_by=name&order=asc: 200.OK (17 ms)
19-6-29 04:52:29.5|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (15 ms)
19-6-29 04:52:29.8|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (13 ms)
19-6-29 04:52:30.0|Debug|Api|[GET] /api/system/task?sort_by=name&order=asc: 200.OK (17 ms)
19-6-29 04:52:30.1|Debug|Api|[GET] /api/system/task?sort_by=name&order=asc: 200.OK (13 ms)
19-6-29 04:53:05.4|Debug|TraktImport|Downloading List https://api.trakt.tv/users/pixelhunterprime/lists/netflix/items/movies?limit=100
19-6-29 04:53:05.6|Debug|Api|[POST] /api/netimport/test: 200.OK (308 ms)
```

**Comment by jobrien2001** [comment]
i looked at the code on src/NzbDrone.Core/NetImport/Trakt/TraktRequestGenerator.cs

`link = link + $"/users/{Settings.Username.Trim()}/lists/{listName}/items/movies?limit={Settings.Limit}"; `

Can it be changed to:
`link = link + $"/users/{Settings.Username.Trim()}/lists/{listName}/items/movies?limit={Settings.Limit}{Settings.TraktAdditionalParameters}"; `
or
`link = link + $"/users/{Settings.Username.Trim()}/lists/{listName}/items/movies" + filtersAndLimit;`

**Comment by fryfrog** [comment]
If you hover over the ? for username, it says filters don't apply. I imagine there is a reason for this. Did you try your change to see if it actually worked?

https://i.imgur.com/oxK7MM5.png
