### ISSUE TITLE
Importing Movies / Renaming Folders and Movies

### ISSUE THREAD

**Issue by davorbn** [Radarr/Radarr#3595]
**Describe the bug**
Its simple, i add the movie to Radarr, it sends a request via a NZBD indexer, which sends a request to SABnzbd. Once SABnzbd is done downloading it, it notifies Radarr. Radarr is having issues importing and renaming the files/folders. Now i would conclude that this is a permissions issue if it occurred with every movie, but it only occurred with some and i haven;t been able to see a pattern. I have enabled debugging and will link it to this post. 

**Desktop (please complete the following information):**
 - OS: Synology NAS with latest version.
 - Mono Version: 5.18.0.240-12
 - Version: 0.2.0.1344

**Debug Logs**
[dbn_radarr_debug.txt](https://github.com/Radarr/Radarr/files/3347552/dbn_radarr_debug.txt)

**Comment by Qstick** [comment]
Logs show System.UnauthorizedAccessException: Access to the path is denied... Permissions

**Comment by davorbn** [comment]
> Logs show System.UnauthorizedAccessException: Access to the path is denied... Permissions

![2019-07-03_6-31-37](https://user-images.githubusercontent.com/20574371/60544545-59c2c700-9d5c-11e9-85a6-ca86233a2ee5.png)

That's what i have at the moment. What should it be if its permission realated?

**Comment by Qstick** [comment]
Jump on Discord and someone can help
