### ISSUE TITLE
Add additional language to download

### ISSUE THREAD

**Issue by greganka** [Radarr/Radarr#3598]
Hi,

It would be nice to have an additional language when it is searching for movies. I have 2 public and 2 private trackers one of them which is Hungarian. However all the movies I download from there 1080/2160 do have English track on them also. This is true for remuxes as well.

It'd be nice to have multiple language field so we could download x OR y OR z etc...
If we could add additional languages to preferred ones that'd be nice.

Edit: adding context

**Comment by Qstick** [comment]
You can use custom formats for this
