### ISSUE TITLE
Radarr movie search results showing only 1 peer for all results

### ISSUE THREAD

**Issue by VillanCaustic** [Radarr/Radarr#3599]
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/3357018/radarr.debug.txt)
**Describe the bug**
For every movie I search for across various indexers via Jackett, all results come back with 1/1 peers showing
This makes it impossible to order by peers and pick the best to download. It seems to show 1 peer even when the tracker has hundreds and also when the tracker has 0.

The same Jackett config and indexers are in use for TV episodes in Sonarr and that works perfectly

 - OS: Windows
 - Browser and Version All Browsers

debug log attachedl

**Comment by fryfrog** [comment]
You'll need to do some digging and due diligence, Radarr is just showing what your indexers are saying via Jackett. Try setting logging to Trace and then get the search URL used from Jackett, then looking directly at that output for seeders. It'll probably be the same 1/1. From there, dig beyond Jackett and see why they're wrong (or right).

Many *public* indexers lie or don't have correct info about number of seeders.
