### ISSUE TITLE
Radarr Ubuntu 19 mediainfo unknown

### ISSUE THREAD

**Issue by h3xx3r** [Radarr/Radarr#3600]
every film shows unknown quallität.
whether under movies or manual import.

os: Ubuntu 19 x64 (latest updates)
mediainfo: MediaInfoLib - v19.04
Mono:
Mono JIT compiler version 5.20.1.19 (tarball Thu Apr 11 09:02:17 UTC 2019) from www.mono-project.com
radarr: latest (Radarr Ver. 0.2.0.1358 devel)

If I use `#mediainfo $moviename`
It works in the console.

debug: `|Debug|Parser|Quality parsed: Unknown v1`

I've already tried the previous radarr version without success.
What can I do?
Thank you
reguards from germany

**Comment by Qstick** [comment]
Please post a debug log

**Comment by h3xx3r** [comment]
Thanks for your answer.
here is the log
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/3360227/radarr.debug.txt)
thanks

**Comment by Qstick** [comment]
Radarr uses naming to parse quality currently, this will be updated to include mediainfo in Aphrodite. How are your files named?

**Comment by Qstick** [comment]
Example, one of your files is `/mnt/gdrive/upload/radarr/Predators (2010).mkv`. Radarr has no clue what the quality is from that
