### ISSUE TITLE
Calendar empty, import error? Database issue?

### ISSUE THREAD

**Issue by 11001010111111101011101010111110** [Radarr/Radarr#3601]
My calendar is mostly empty, cursory search on the error messages point to duplicate movie names?

Is there a way from me to figure out what’s causing the error, whether that might cause the calendar to never fill up and how to solve it?

Error occurred while executing task NetImportSync: constraint failed UNIQUE constraint failed

![FC724192-6111-4A7B-81CF-EA29997C78C1](https://user-images.githubusercontent.com/14227452/60723785-a516da00-9f02-11e9-98a9-d97aaace186d.jpeg)
![A7981797-6EE3-4E2F-95D9-A7814E3B17EA](https://user-images.githubusercontent.com/14227452/60723786-a516da00-9f02-11e9-8bc5-a648b1875baa.jpeg)
![D11A067D-1326-4AF6-844B-BC2D23E2D42E](https://user-images.githubusercontent.com/14227452/60723787-a516da00-9f02-11e9-8f9c-ba4e796b398f.jpeg)

**Comment by Qstick** [comment]
A list is trying to add a duplicate movie, I believe this occurs because we check for existing before doing the tmdb mapp.... same as described in #3265
