### ISSUE TITLE
Ignore alternative titles of "working title" type

### ISSUE THREAD

**Issue by pettazz** [Radarr/Radarr#3602]
**Is your feature request related to a problem? Please describe.**
For example, the movie Dark Phoenix has a few working titles associated with it, one of which is actually another existing film title:
![dp](https://user-images.githubusercontent.com/690841/60764566-50867280-a05a-11e9-8fb2-aeca26684e70.jpg)

So Radarr keeps fetching "Teen Spirit" and adding it to my library incorrectly under Dark Phoenix. This has happened with a few different movies.

**Describe the solution you'd like**
[TheMovieDB API endpoint for alternative titles](https://developers.themoviedb.org/3/movies/get-movie-alternative-titles) has a "type" parameter in the response, so it should be possible to ignore any of type "working title", like 
`{"title"=>"Teen Spirit", "type"=>"working title", "iso_3166_1"=>"US"}`. I can't imagine a scenario where we'd actually prefer a working title search over one using an actual title.

**Describe alternatives you've considered**
Adding exclusion rules for individual movies isn't going to work in the long run if we keep having working titles associated with movies as alternative titles. 

[AB#877](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/877)

**Comment by dshokouhi** [comment]
Honestly ignoring "working title" does not seem to be ideal.  These values are all editable by any user.  The issue for dark phoenix is the same user submitting the incorrect AKA.  They even updated the actual title of the film to "working title" so in that case radarr may ignore the actual title of the film?

https://www.themoviedb.org/movie/320288-dark-phoenix/changes?language=en-US

There must be a better way to ignore these incorrect edits in particular.  Peopel make edits for the shear fact of making an edit whether it is correct or not.  If its possible to match TMDB to the IMDB that may be best.

**Comment by pettazz** [comment]
Every entry has an actual title field, separate from the alt titles, so even if someone added "Dark Phoenix" as a working title, we'd still be searching Dark Phoenix as the original title anyway. I don't think the edits are the problem, they're technically correct and usually any errors get moderated away before they exist long enough to appear in Radarr. 

I can't think of any scenario in which searching with Radarr for something's working title would actually be useful, only that it'll add confusion with names totally unrelated to the actual movie, so why not just exclude them?

**Comment by tombomb** [comment]
Just bumping up my support for a fix for this, same movie same problem

**Comment by Qstick** [comment]
In Aphrodite you will be able to select which titles get used for searching/parsing

**Comment by dshokouhi** [comment]
@Qstick does that mean we can choose to ignore working titles altogether (for all titles) or is this going to be on a per title basis?

**Comment by Qstick** [comment]
Per title basis is the plan.

**Comment by dshokouhi** [comment]
@Qstick ok just thinking outloud here, I am not sure if that would solve the issue some have been seeing with alternative titles.  We would still have to catch the incorrect movie being downloaded first in order to ignore it.  I would personally vote for a global setting as the issue with Dark Phoenix was that an alternative title was added for an already existing movie causing all users with that title in their library downloading an incorrect movie.  In the past I have seen this too where alternative titles were causing false downloads.

**Comment by Qstick** [comment]
I agree with you, how about an option so that titles are not used by default? Then they can be toggled on when needed instead of the other way.

**Comment by dshokouhi** [comment]
I think that would allow the best of both worlds here, then we can just warn users they may get some fakes if they turn it on :)  Kinda falls in line with how HC subs are treated :)

**Comment by Qstick** [comment]
No plans for this in near future
