### ISSUE TITLE
0.2.0.1377 breaks wanted page filters

### ISSUE THREAD

**Issue by christronyxyocum** [Radarr/Radarr#3605]
**Describe the bug**
Filters on the Wanted page do not work with 0.2.0.1377. Rolling back to the 0.2.0.1374-ls23 tag for the LSIO Docker image resolves the issue.

**To Reproduce**
1. Update to latest nightly, 0.2.0.1377
2. Click on Wanted
3. Try to use the filters

**Expected behavior**
Filters work as expected.

**Screenshots**
https://chrisyocum.com/Images/ShareX/2019-07-08_11-31-44.gif

**Desktop (please complete the following information):**
LSIO Docker image.

**Comment by fryfrog** [comment]
Mine behaves the same as yours, with the only difference being the Unmonitored (which shows none) and literally all the others showing the same ones.

**Comment by Qstick** [comment]
Fixed
