### ISSUE TITLE
You can’t open the application “Radarr.app” because it may be damaged or incomplete.

### ISSUE THREAD

**Issue by MarvensBastien** [Radarr/Radarr#3607]
I went to the file and launch it... it prompts me this message "You can’t open the application “Radarr.app” because it may be damaged or incomplete. " any ideas?

**Comment by Qstick** [comment]
Where did you download from?

**Comment by fryfrog** [comment]
Sounds like it may be damaged, based on the message about it "may be damaged". Try deleting or renaming what you downloaded, then re-download it. Make sure you're getting it from github.

**Comment by MarvensBastien** [comment]
https://github.com/Radarr/Radarr

**Comment by Qstick** [comment]
I would venture to say you downloaded the source package instead of the binaries

**Comment by galli-leo** [comment]
I think the more likely option is, that you didn’t use ArchiveUtility to extract the zip file. Archive utility chmods everything to 777 when unzipping. Other tools sometimes either don’t or don’t preserve permissions. Hence the executable inside the .app packe doesn’t have the necessary permissions to work.

**Comment by Qstick** [comment]
https://github.com/lidarr/Lidarr/issues/842 we just had similar issue, which is why I suggested that

**Comment by fabriziobertoglio1987** [comment]
I have the same issue, but if I go to `/Applications/Radarr.app/Contents/MacOS` and run `./Radarr` it starts.

so I found out that I made some confusion on macos folder, between ~/Applications and /Applications
