### ISSUE TITLE
Missing movies

### ISSUE THREAD

**Issue by Griphiny** [Radarr/Radarr#3619]
When adding movies that have multiple brackets in folder name radarr doesnt seem to rename anymore it seems to only work when theres one word in bracket like so [hello] also when trying to include release group in rename config that doesnt seem to work either it just replaces release group with Radarr instead dunno if thats due to release group being inside brackets from original folder that radarr might not be able to read it and apply to renaming?

**Comment by fryfrog** [comment]
You gotta stick to some standard patterns for that sort of stuff to work, which is `-GrouP` at the end. In TV, Sonarr handles `[Group]` at the beginning and *sometimes* end for Anime, but I doubt Radarr does.

**Comment by Griphiny** [comment]
Not entirely sure what you mean,ive tried -{group} in rename config and that didnt help,if its how the folder itself is named i guess ill have to just manually download then as its less work,isnt it possibel to add support for multiple brackets? If i remember correct support for bracket was added some years ago just dont understand how it cant work with multiple brackets though,all my downloads are from same source and contain multiple brackets so its kind of a deal breaker though

**Comment by fryfrog** [comment]
Let's see some examples and logs. I thought you were saying you had a bunch of existing files that you'd added a bunch of `[Bracket]` type text too, not releases coming down w/ lots of `[]`.

**Comment by Griphiny** [comment]
> 
> 
> Let's see some examples and logs. I thought you were saying you had a bunch of existing files that you'd added a bunch of `[Bracket]` type text too, not releases coming down w/ lots of `[]`.

Ok its for release coming down and movies moved into the folder present in radarr
Its really hard to figure out as the logs doesnt have any errors in it or anything related to renaming either, though normally shouldnt there be an entry saying "renaming filename something" for each renamed file? Ive enabled Rename Movies and set formats accordingly and also i got Automatically Rename Folders enabled. Heres the log part containing anything related to the file though but it only shows the movie added and nothing more seems, the log seems to list the movie wrong though it says 
[ReleaseGroup] Phar Lap (1983) 1080p BRRip while the actual folder name is Phar Lap (1983) [BluRay] [1080p] [ReleaseGroup] i dunno if thats relevant though?

19-7-14 20:28:53.8|Info|MovieService|Adding Movie [Phar Lap (1983)][, 36527] Path: [/disk/Phar Lap.1983]
19-7-14 20:28:53.8|Info|RefreshMovieService|Updating Info for Phar Lap
19-7-14 20:28:56.0|Info|DiskScanService|Scanning disk for Phar Lap
19-7-14 20:28:56.0|Info|MovieScannedHandler|[Phar Lap] was recently added, performing post-add actions
19-7-14 20:28:56.0|Info|MediaCoverService|Testing: NzbDrone.Core.Messaging.Commands.CommandQueueManager, 1061
19-7-14 20:28:56.1|Info|MediaCoverService|Downloading Poster for [Phar Lap (1983)][tt0086102, 36527] http://image.tmdb.org/t/p/original/1sIFVIAoGQJ1sNsVnVLE3qam086.jpg
19-7-14 20:28:56.2|Info|NzbSearchService|Searching 1 indexers for [Phar Lap]
19-7-14 20:28:57.0|Info|MediaCoverService|Downloading Fanart for [Phar Lap (1983)][tt0086102, 36527] http://image.tmdb.org/t/p/original/vWYGm5VfrL96KXltrkB7CmF1uf8.jpg
19-7-14 20:28:57.2|Info|MetadataService|Movie folder does not exist, skipping metadata creation
19-7-14 20:28:58.4|Info|DownloadDecisionMaker|Processing 2 releases
* 19-7-14 20:28:58.5|Info|DownloadService|Report sent to disk. [ReleaseGroup] Phar Lap (1983) 1080p BRRip
19-7-14 20:28:58.5|Info|MovieSearchService|Movie search completed. 1 reports downloaded.
19-7-14 20:30:58.4|Info|Database|Vacuuming Log database
19-7-14 20:30:58.4|Info|Database|Log database compressed
19-7-14 20:40:22.9|Info|BackupService|Starting Backup
19-7-14 20:45:53.1|Info|RssSyncService|Starting RSS Sync
19-7-14 20:45:54.1|Info|DownloadDecisionMaker|Processing 100 releases
19-7-14 20:45:56.1|Info|RssSyncService|RSS Sync Completed. Reports found: 100, Reports grabbed: 0
19-7-14 21:06:24.0|Info|RssSyncService|Starting RSS Sync
19-7-14 21:06:25.4|Info|DownloadDecisionMaker|Processing 100 releases
19-7-14 21:06:27.6|Info|RssSyncService|RSS Sync Completed. Reports found: 100, Reports grabbed: 0

**Comment by fryfrog** [comment]
I'm not groking it, hop on Discord and get some real time troubleshooting.
