### ISSUE TITLE
Support movie folder renaming after first import

### ISSUE THREAD

**Issue by tommyalatalo** [Radarr/Radarr#3623]
**Is your feature request related to a problem?**
As radarr works now it's very frustrating and illogical that you might import a movie, the renaming result isn't what you want, so you delete the library copy, change the renaming scheme, and try importing again from "Wanted", but the library folder is still named the same as the first import. This seems to be because the first import locks in the path for the movie in the library folder for any future re-imports of the same movie.

**Describe the solution you'd like**
Expected behavior should be something like this:

1. Import a missing movie automatically or from Wanted list, creating a new movie folder in the library.
2. The naming scheme isnt what you wanted  (lets say "MovieName" - I'm missing the year)
3. I delete the MovieName folder from my library
4. I change the folder name in renaming settings to "MovieName (Year)"
5. I go to Wanted again and import the movie a second time
6. The resulting folder is now "MovieName (Year)"

Meaning that the path written into history on the first import is overwritten if the renaming format is changed after the first import happened.

**Describe alternatives you've considered**
Alternatively implement a "Refresh Library Folders" function which would allow the user to update all the folder names in the library folder to a new naming format by clicking a button.

In this case the procedure would be more like:
1. Import a missing movie automatically or from Wanted list, creating a new movie folder in the library.
2. The naming scheme isnt what you wanted  (lets say "MovieName" - I'm missing the year)
3. I change the folder name in renaming settings to "MovieName (Year)"
4. Click "Refresh Library Folders"
5. The folder is now updated to "MovieName (Year)"

**Additional context**
The important thing to implement is to get the settings naming format to always match the library output, as radarr works now, that's not always the case, which is confusing and illogical.

**Comment by fryfrog** [comment]
Turn static paths *off* for existing movies and the default. Make your template how you like. Run the thing that renames folders. Use organize to rename files.
