### ISSUE TITLE
Add BroadcastheNet

### ISSUE THREAD

**Issue by TrollWarlord** [Radarr/Radarr#3627]
**Is your feature request related to a problem? Please describe.**
No problem. 

**Describe the solution you'd like**
Add support for BroadcastheNet

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Qstick** [comment]
I'm not familiar with BTN, but are movies available?

**Comment by fryfrog** [comment]
It doesn't make much sense for BTN to be in Radarr not PTP in Sonarr.
