### ISSUE TITLE
Custom format in movie naming

### ISSUE THREAD

**Issue by CaptAintHere** [Radarr/Radarr#3628]
**Is your feature request related to a problem? Please describe.**
For French languages, dubbing can come from different countries, like Quebec or France. Movies are often tagged with VFF or Truefrench when dubbing is from France and VFQ for Quebec. Custom formats are the best way to download movies with proper languages : one can combine a custom format in order to have a movie in multiple languages (like English and French for example) and the dubbing you want. But you can't know if a movie was downloaded with specific custom format when viewing the file.

**Describe the solution you'd like**
It would be nice to have the possibility, depending on a custom format, to rename files accordingly. We could for example add a new text field in custom format definition, and add the possibility to use custom format in movie naming. The new field will be use and the text will be added to the file name.

**Describe alternatives you've considered**
There is not alternative for the moment.

**Additional context**
/

**Comment by TheCatLady** [comment]
This isn't just an issue for French languages, either.  I use custom formats to prefer certain encoders over others, and would like to be able to include this in filenames.

**Comment by henkin67** [comment]
The easiest way could be to propose an output variable which represents the highest custom format in the profil which match during the grab.
By this way we could use it in renaming function and also in custom script.
