### ISSUE TITLE
A small logo error on the login page for the preview version

### ISSUE THREAD

**Issue by Goatoverlordwastaken** [Radarr/Radarr#3629]
**Description:**The logo of sonarr was displayed on the radarr login page
https://cdn.discordapp.com/attachments/529476212863664146/601387563760222223/unknown.png

I know this is silly of me, but I wanted to drop it. :)

**Radarr Version:**2.0.0.1404

**Mono Version:**5.20.1.19

**Debug Logs:**

# Do not remove anything from your logs and post the full logs! If not everything fits in here use a service like https://pastebin.com to upload them.

**Comment by Qstick** [comment]
Thanks

**Comment by Qstick** [comment]
Fixed
