### ISSUE TITLE
Radarr Aphrodite - Search

### ISSUE THREAD

**Issue by shadowtor** [Radarr/Radarr#3630]
Search Wanted/Search All does not seem to work, need something similar to Sonarr's Wanted menu item

Radarr:
![Radarr Search Missing](https://i.imgur.com/gfJMDmg.png)
Sonarr:
![Sonarr Wanted](https://i.imgur.com/fmkCfGa.png)

Expected the 'search all' to run through and scan for missing items

 - OS: Debian
 - Mono Version: 5.20.1.19)
 - Browser and Version Firefox:68
 - Version 2.0.0.1404

**Comment by galli-leo** [comment]
Aphrodite is not in a state yet where everything should work.
