### ISSUE TITLE
Whole slew of unknown movies showed up in my list overnight

### ISSUE THREAD

**Issue by jwvanderbeck** [Radarr/Radarr#3633]
**Description:**
Sometime overnight nearly a hundred were added to my Radarr list that I know nothing about.  The only lists I have auto-import are from Trakt and none of these are on that list.  Furthermore they are movies that would have never been in that list.  Many of the movies that were added are movies I wouldn't watch with a gun to my head, like Angry Birds or The Emoji Movie.

**Radarr Version:**
0.2.0.1358

**Mono Version:**

**Debug Logs:**

# Do not remove anything from your logs and post the full logs! If not everything fits in here use a service like https://pastebin.com to upload them.

I'm not sure which part of the logs would be relevant and they are HUGE.  Radarr made 3 logs between now and yesterday.  Won't fit on Pastebin.  If you want me to look for specific keywords or specific sections I can do that.

**Comment by jwvanderbeck** [comment]
BTW This also seems to have exposed another bug in that these new movies got added to my downloader multiple times.  What I mean is for one movie, say Angry Birds, about 4 or 5 releases of that movie were all added to NZBGet at once which is ludicrous.  There were over 300 entries in NZBGet this morning.  Even if a movie was added legitimately, shouldn't it try to download ONE source and wait to see if its good before continuing to add more downloads?

**Comment by Qstick** [comment]
Please post the full log

**Comment by jwvanderbeck** [comment]
> 
> 
> Please post the full log

Did you read what I said? If you really want the full relevant log, which is three whole log files, please tell me where you'd like the files posted because its too big for pastebin.

**Comment by jwvanderbeck** [comment]
Ok I've uploaded them to Dropbox:

https://www.dropbox.com/s/w60zgmcac8j6p8b/radarr.txt?dl=0
https://www.dropbox.com/s/56cjb87re9mpr53/radarr.0.txt?dl=0
https://www.dropbox.com/s/4xmpqjqi0xq6ywd/radarr.1.txt?dl=0

**Comment by Qstick** [comment]
From what I heard trakt had some API issues which likely caused this
