### ISSUE TITLE
radarr.db corrupted beyond readable in sqlite cli

### ISSUE THREAD

**Issue by maartenzuidland** [Radarr/Radarr#3634]
**Describe the bug**
After running for a few minutes, at the stage where I am still importing my existing movies from disk, Radarr seems to corrupt the radarr.db file.

[v0.2.0.1358] System.Data.SQLite.SQLiteException (0x80004005): database disk image is malformed
database disk image is malformed
  at System.Data.SQLite.SQLite3.Prepare (System.Data.SQLite.SQLiteConnection cnn, System.String strSql, System.Data.SQLite.SQLiteStatement previous, System.UInt32 timeoutMS, System.String& strRemain) [0x0033c] in <61a20cde294d4a3eb43b9d9f6284613b>:0 

The radarr.db file is no longer readable in the sqlite cli or any other SQLite DB Browser

This issue does not show up in Aphrodite branch, this issue does not show up in my Sonarr install (currently using Sonarr V3 for a month or longer, which is why I tried the Aphrodite branch earlier this week, but was advised in Discord to return to "normal" version).

**My setup**
* MacOS 10.14.5 with Parallels 14 as VM, running Fedora 30 (kernel 5.1.18)
* Latest docker-ce running
* linuxserver/radarr image in docker
* shared disk with movies and config, shared through Parallels file share
(https://pastebin.com/93NH7Ch3 result of df -h, files in /media/psf/My Book/ ; line 14)

**To Reproduce**
1. delete all previous radar config files
2. recreate docker container
3. import all 621 files in my movie directory
4. system auto-starts library refresh
5. While refresh is running: config the indexer, config the downloader, config IMDB list, config plex server
6. Wait to crash

**Expected behavior**
Not corrupt the file

**Screenshots**
UI freezes up, no longer responds. Mostly see log and traces below.

**Desktop (please complete the following information):**
 - OS: Docker on Fedora 30 in a VM in Parallels MacOS 10.14.5 (Image I use is Linuxserver.io's Radarr)
 - Mono Version: https://pastebin.com/pus4DpbS
 - Version v0.2.0.1358

**Debug Logs**
The system seems to have autogenerated these logs:
https://pastebin.com/9iLuvypz -> radarr.txt
https://pastebin.com/Zsyn4hdJ -> radarr.trace.txt
https://pastebin.com/eF0DBzDq -> radarr.debug.txt

**Comment by galli-leo** [comment]
Problem is very likely related to the disk setup. Put your config folder somewhere that’s a real physical drive and not any kind of network share or special file system

**Comment by maartenzuidland** [comment]
Then why does the same issue not happen with Sonarr or the Aphrodite release? I rule out the disk setup due to this.
(Also, the Support at Discord told me they did not want to help, and I should create a bug report.)
