### ISSUE TITLE
/api/profile returns language list instead of single language object

### ISSUE THREAD

**Issue by raidenlal** [Radarr/Radarr#3635]
Describe the bug
-new development radarr/api/profile API now returns list of profiles and in each profile it returns a LIST of languages
-bazarr expected radarr to supply only one language per profile, not a list (https://github.com/morpheus65535/bazarr/blob/development/bazarr/get_movies.py#L222 - here it fails with AttributeError: \dict\ object has no attribute \capitalize)

To Reproduce

get latest development version of radarr and bazarr from dockerhub
try to sync movies from radarr
Expected behavior
Movies get synced from radarr to bazarr

Screenshots
n/a

Software (please complete the following information):

Bazarr: 0.8
Radarr version 2.0.0.1404
Sonarr version 3.0.2.537-ls102 by linuxserver.io
OS: Linux-4.9.125-linuxkit-x86_64-with (docker on windows)
Additional context
https://www.reddit.com/r/radarr/comments/cfz9v2/radarr_api_language_list_per_profile_bug/
https://www.reddit.com/r/bazarr/comments/cfz3a6/changed_api_in_radarr_develop_branch/
https://github.com/morpheus65535/bazarr/issues/496 bazarr

**Comment by Qstick** [comment]
Aphrodite is not ready for non-developer testing. But, There are heavy API changes which will be communicated when it's ready

**Comment by morpheus65535** [comment]
@Qstick Thanks! Please keep me informed when it's going to be "almost" stable so I can start integrating those change to Bazarr.
