### ISSUE TITLE
8 digit imdb ids

### ISSUE THREAD

**Issue by currently-off-my-rocker** [Radarr/Radarr#3637]
IMDB ids can now be 8 digits long. Like https://www.imdb.com/title/tt10001870/

At least one regex expects only 7 digits and will not match or truncate these ids.
`ReportImdbId = new Regex(@"(?<imdbid>tt\d{7})"`

https://github.com/Radarr/Radarr/blob/7756b03555c836e5a6a7dc9ead18e9552898241c/src/NzbDrone.Core/Parser/Parser.cs#L99

**Comment by Iristyle** [comment]
Searching on `imdb:tt9573980` is also not working for me. Not sure why.

**Comment by tvebax** [comment]
Confirmed.
This is still an issue with imdb ids in the api.radarr.video feed. No 8 digit imdb ids get included here.

**Comment by mamminimal** [comment]
Using latest Aphrodite 3.0.0.3083, Radarr is still not importing list entries with 8-digit IMDB IDs.

Steps to reproduce:

1. In Settings > Lists, create an IMDB list for auto import, with a movie that has an 8 digit IMDB ID f.e. "Countdown" https://www.imdb.com/title/tt10039344/?ref_=wl_li_tt
2. In Settings > Lists, set the "Clean Library Level" to "Log Only".
3. In Movies > Add New, add the movie "Countdown" to Radarr.
4. In System > Tasks, run a manual "Net Import Sync".
5. Search your log for this line: NetImportSearchService|[Countdown (2019)][tt10039344, 599975] was in your library, but not found in your lists --> You might want to unmonitor or remove it

**Comment by Qstick** [comment]
It's an issue with the api, not Radarr most likely. It's currently being replaced in v3
