### ISSUE TITLE
Coming Soon to Blu-ray lists only german movies

### ISSUE THREAD

**Issue by Speaktomenow** [Radarr/Radarr#3639]
When looking for Coming Soon to Blu-ray movies, I no longer see any movies except these two German movies.

Ella Schön - Ferien Von Den Eltern
Vernau - Totengebet

Where did Radarr get the idea I want german releases from and how can I change this setting to show english releases?

**Radarr Version:** 0.2.0.1391 (nightly)

**Mono Version:** 5.20.1.19

**Comment by fryfrog** [comment]
Try flipping your branch between `nightly` and `develop` in Settings -> General and see if that makes it any different, the end point changes based on that. Don't update though. When you're finished testing, set it back to what it was. Tell us.

**Comment by Speaktomenow** [comment]
I swapped to develop. No change. I restarted with but my version remains at
Radarr Ver. 0.2.0.1438 nightly

When going into 'updates' it says you can't install the latest develop
version over a more recent nightly.

So no changes swapping from nightly to develop.

Blu-ray releases upcoming shows no content still.

**Comment by fryfrog** [comment]
Thanks for checking. Guess we need some logs now. Turn logging up to trace, repeat it and then pastebin a big chunk of the logs from around when you do it.

**Comment by Speaktomenow** [comment]
Thanks, the relevant section of the logs when trying to pull Upcoming Bluray Releases. Not that recommendations works fine, but as for 'Popular' and 'Upcoming Release dates/movies' I get nothing:

19-9-6 09:32:44.8|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId)
19-9-6 09:32:44.8|Trace|Owin|

19-9-6 09:32:44.9|Trace|HttpClient|Req: [POST] https://staging.api.radarr.video/discovery/recommendations
19-9-6 09:32:44.9|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
19-9-6 09:32:46.3|Trace|HttpClient|Res: [POST] https://staging.api.radarr.video/discovery/recommendations: 200.OK (1491 ms)
19-9-6 09:32:46.3|Trace|Http|Res: 156 [GET] /api/movies/discover/recommendations: 200.OK (1557 ms)
19-9-6 09:32:46.3|Debug|Api|[GET] /api/movies/discover/recommendations: 200.OK (1557 ms)
19-9-6 09:32:48.1|Trace|Http|Req: 157 [GET] /api/movies/discover/popular
19-9-6 09:32:48.1|Trace|Owin|SQLite warning (284): automatic index on AlternativeTitles(MovieId)
19-9-6 09:32:48.1|Trace|Owin|

19-9-6 09:32:48.1|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId)
19-9-6 09:32:48.1|Trace|Owin|

19-9-6 09:32:48.1|Trace|HttpClient|Req: [POST] https://staging.api.radarr.video/discovery/popular
19-9-6 09:32:48.1|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
19-9-6 09:32:49.8|Trace|HttpClient|Res: [POST] https://staging.api.radarr.video/discovery/popular: 200.OK (1733 ms)
19-9-6 09:32:49.8|Trace|Http|Res: 157 [GET] /api/movies/discover/popular: 200.OK (1798 ms)
19-9-6 09:32:49.8|Debug|Api|[GET] /api/movies/discover/popular: 200.OK (1798 ms)
19-9-6 09:32:50.6|Trace|Http|Req: 158 [GET] /api/movies/discover/upcoming
19-9-6 09:32:50.6|Trace|Owin|SQLite warning (284): automatic index on AlternativeTitles(MovieId)
19-9-6 09:32:50.6|Trace|Owin|

19-9-6 09:32:50.6|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId)
19-9-6 09:32:50.6|Trace|Owin|

19-9-6 09:32:50.7|Trace|HttpClient|Req: [POST] https://staging.api.radarr.video/discovery/upcoming
19-9-6 09:32:50.7|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
19-9-6 09:32:52.2|Trace|HttpClient|Res: [POST] https://staging.api.radarr.video/discovery/upcoming: 200.OK (1500 ms)
19-9-6 09:32:52.2|Trace|Http|Res: 158 [GET] /api/movies/discover/upcoming: 200.OK (1566 ms)
19-9-6 09:32:52.2|Debug|Api|[GET] /api/movies/discover/upcoming: 200.OK (1566 ms)
19-9-6 09:32:53.8|Trace|Http|Req: 159 [GET] /api/health
19-9-6 09:32:53.8|Trace|Http|Res: 159 [GET] /api/health: 200.OK (1 ms)
19-9-6 09:32:53.8|Debug|Api|[GET] /api/health: 200.OK (1 ms)
19-9-6 09:32:53.8|Trace|Http|Req: 160 [GET] /api/diskspace
19-9-6 09:32:53.8|Trace|Owin|SQLite warning (284): automatic index on AlternativeTitles(MovieId)
19-9-6 09:32:53.8|Trace|Owin|

19-9-6 09:32:53.8|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId)
19-9-6 09:32:53.8|Trace|Owin|

19-9-6 09:32:53.9|Trace|Http|Req: 161 [GET] /api/health
19-9-6 09:32:53.9|Trace|Http|Res: 161 [GET] /api/health: 200.OK (1 ms)
19-9-6 09:32:53.9|Debug|Api|[GET] /api/health: 200.OK (1 ms)
19-9-6 09:32:53.9|Trace|ConfigService|Using default config value for 'downloadedmoviesfolder' defaultValue:''
19-9-6 09:32:53.9|Trace|Http|Res: 160 [GET] /api/diskspace: 200.OK (61 ms)
19-9-6 09:32:53.9|Debug|Api|[GET] /api/diskspace: 200.OK (61 ms)
19-9-6 09:32:53.9|Trace|Http|Req: 162 [GET] /api/diskspace
19-9-6 09:32:53.9|Trace|Owin|SQLite warning (284): automatic index on AlternativeTitles(MovieId)
19-9-6 09:32:53.9|Trace|Owin|
