### ISSUE TITLE
Request: Maximum file size per quality definition

### ISSUE THREAD

**Issue by RandomNinjaAtk** [Radarr/Radarr#3640]
**Description:**
I would like a new setting added per quality definition that replicates the already included: "Maximum Size" in the indexer settings page.

I know dynamic slider is available that limits it based on runtime length, but its not the easiest to adjust and I think the new version coming is going to help some with that. However, I really enjoy using the maximum setting on the indexer page and it works great. Except the only issue with it is that it applies to all categories... So if you want to make the maximum 15 GB for Bluray 1080p rips, it would not be possible to impose a larger limit like 30 GB for remux's and vice versa. 

So I would preferably want to be able to set a hard limit for file size based on the quality.... I hope I explained this well enough...

Edit: I know you may consider custom formats as a way to solve it. And it could for the most part, but I'd have to re-create every quality definition to make that work. As of right now I use 3 custom formats to sort/prioritize which release to choose and it's working perfectly. But to implement what I'm looking for would require replication every quality type as a custom format..

**Radarr Version:** Linuxserver.io docker nightly

**Mono Version:** Linuxserver.io docker

**Debug Logs:**

**Comment by henkin67** [comment]
Hello,
I'm not sure why you want to limit the size of a quality.
If a movie is 3h length, you cannot have the same size compare with a 1h movie length.

For my point of view, the slider is the best way to ensure good release selection regarding size constraints.
Regards.

**Comment by RandomNinjaAtk** [comment]
Limiting the size is currently a global option under the indexer settings. I just want to move/make that as an option per quality type for more granular control.

**Comment by fryfrog** [comment]
Honestly, the maximum size in the indexer setting should just be removed. It causes more support issues than it helps anyone. An absolute size limit isn't a great feature overall.
