### ISSUE TITLE
Failed to find movie title in release name

### ISSUE THREAD

**Issue by dposs** [Radarr/Radarr#3642]
**Describe the bug**
Radarr isn't able to identify movie title in a specific case.

**To Reproduce**
1. Set up an Indexer that does not use quality, language, and year in the release name.
2. Add a movie.
3. Do a search.

**Expected behavior**

I did all the following configurations...
- Radarr set up to use "Lenient Mapping" as Parser Leniency.
- Indexer set up to Search by title.
- Indexer set up to Remove year from search string
- Quality profile set up to allow Unknown quality.
- Quality profile set up to allow Any language.

... so, a release with only the movie title should be found.

**Screenshots**

Trying to find "Hellboy" movie. The indexer returned some results, all of them with the title "Hellboy", but Radarr wasn't able to identify movie title.

![Hellboy](https://i.imgur.com/pyyiTDH.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Chrome 75.0.3770.142 64 bits
 - Version 0.2.0.1358

**Debug Logs**
```
19-7-25 02:04:32.4|Trace|DownloadDecisionMaker|Processing release 15/21
19-7-25 02:04:32.4|Debug|Parser|Parsing string 'Hellboy'
19-7-25 02:04:32.4|Debug|Parser|Unable to parse Hellboy
19-7-25 02:04:32.4|Debug|DownloadDecisionMaker|Hellboy could not be parsed :(.
19-7-25 02:04:32.4|Debug|DownloadDecisionMaker|Release rejected for the following reasons: [Permanent] Failed to find movie title in release name Hellboy
```

**Comment by fryfrog** [comment]
You're missing a *year*, it just isn't likely to work.

**Comment by dposs** [comment]
And how about this option?

![Year Config](https://i.imgur.com/ucNTk6c.png)

Shouldn't radarr search work without year when I enabled it?

**Comment by Krandor1** [comment]
There are two movies called hellboy.  Without a year how is Radarr to know which one it is?

**Comment by dposs** [comment]
Just mark both as accepted releases. Instead of "Release Rejected".

"Remove year from search string" option must be there for some reason.

**Comment by Krandor1** [comment]
It stills needs to tie the download to a movie. It can’t tie  it to two. I have no idea how you expect this to work. 

If there is only one version of a movie by that name then I’d expect remove year to work but not when there are two movies of the same name in different years. At this point without year you can’t tell them apart so I don’t know what movie this is would be the appropriate response because it doesn’t and can’t know.

**Comment by Lonli-Lokli** [comment]
Problem usually occurs because Radarr expecting {Movie Name} {Movie Year} format only, while trackers (and indexers with Jackett as well) list film as {Movie Name} ( {Producer Name} ) {Movie Year} so release will be rejected.

**Comment by dposs** [comment]
I understood that Radarr won't be able to identify what "Hellboy" movie is the correct in this case, because there is a 2004 release and a 2019 release, with the same movie name.

But, in the manual Search (see the screenshot below), Radarr is showing all Hellboy movies (2004 and 2019 releases). Which is fine, because I set up to ignore release Year. So it's showing to me all Hellboy movies regardless of year:

![Radarr](https://camo.githubusercontent.com/1161f90b6e19649cc62f734b1590c6ff29a1d860/68747470733a2f2f692e696d6775722e636f6d2f707979695444482e706e67)

But.. Radarr don't let me download any of them.
As it is a manual search, I want to tell Radarr which of these versions I want to download.

**Comment by Krandor1** [comment]
Then you should open a request for that feature then.

**Comment by Krandor1** [comment]
But even if you could it still isn’t going to be able to import the movie either for the same reasons.

**Comment by dposs** [comment]
For me It still a bug, because I set up Radarr to ignore the year. It's telling me that I can't download "Hellboy" because it is different of "Hellboy".

But ok, maybe some day I'll open a feature request, as you said.

Anyway, thanks for you attention.
Regards.

**Comment by Krandor1** [comment]
Open it as a bug then but either way your original request in this one wasn’t clear that you wanted a manual download button on a search like this. It read like you expected Radarr to auto grab it which it can’t. 

So if you want your “bug” fixed you need to be more specific on what you want.

**Comment by Qstick** [comment]
This is already allowed in v2 Aphrodite, however to Krandors point you'll have to manually download and manually import because there is no possible way for Radarr to know if it's ignoring the year.

**Comment by dposs** [comment]
Qstick, I can't manually download it. This is the reason why I opened this issue. Radarr is blocking the manual download.

**Comment by fryfrog** [comment]
Qstick is saying that it is (or will be) possible in v2, but that even *there* you'll need to manually download it and manually import it.

**Comment by sliddjur** [comment]
@Qstick I tried to manually add UFC 242

**Comment by sliddjur** [comment]
@Qstick I added movie https://www.themoviedb.org/movie/625957 to radarr v2 "aphrodite".

When I search for it, I successfully get some results, because I am searching without release year. So far so good. But radarr wont add the movie to deluge.

I manually press search result and I get this.

`Radarr was unable to determine which movie this release was for. Radarr may be unable to automatically import this release. Do you want to grab 'UFC 242 Inside The Octagon Khabib vs Poirier 720p WEBRip h264-TJ [TJET]'?`

Then I press `grab`. And the cloud icon changes to tooltip `Value can not be null. (Parameter 'remoteMovie.Movie')`. Is this supposed to work to add to deluge?

**Comment by Qstick** [comment]
Thanks, I'll look at this tonight. Manual grabs was one thing I hadn't looked at yet
