### ISSUE TITLE
extra

### ISSUE THREAD

**Issue by Joleun** [Radarr/Radarr#3645]
**Describe the bug**
Hope I'm posting this in the correct place, and that it hasn't already been raised.  I did try to check on the latter, but most of what I found was regarding the introduction of the feature.

The problem is with extra files, specifically sub files in my case, not being imported despite this being set in the Media Management settings.  I believe Sonarr has the exact same problem, but it's more apparent with Radarr as it happens more often.  I could be wrong but I think it's caused by either of two things: the sub files not already being named after the movie (eg. 2_Eng.srt), or that they are located in a subfolder of the folder containing the movie being imported.

While raising this issue, I'd also like to say it would be great to be able to specify which subtitle languages to import.  Although, it's nothing major, I only require the english subtitles; quite often the can be a couple of english versions, and a number of others that I'll just not require.  

**To Reproduce**
Appears to happen every time.  Unfortunately, I don't have an example in mind of where the sub files are successfully imported, but I have a strong feeling that it works when they're not in a subfolder.

**Desktop (please complete the following information):**
 - OS: Synology NAS DSM 6.2
 - Mono Version: 5.18.0.240
 - Version 20190320-8 (hope this is accurate - getting it from within DSM rather thsan Radarr)

**Comment by Qstick** [comment]
Similar to#1958

**Comment by Joleun** [comment]
Ah, yes.  Sorry, I didn't find that one when I was trying to check if it had already been raised.
