### ISSUE TITLE
Radarr timeouts if indexer is down but doesnt detect the down state

### ISSUE THREAD

**Issue by ndoty** [Radarr/Radarr#3646]
**Description:**

When manually searching for a movie the operation would timeout. Sonarr is reporting an indexer as down while Radarr does not. This causes Radarr to go into this odd state as Mono will report the timeout in the Radarr logs but Radarr appears to not handle the report well and hangs and with endlessly show the loading dots in the UI. I lend my thanks to FryFrog in the Discord room to help diagnose this.

**Radarr Version:** 0.2.0.1358

**Mono Version:** 6.0.0.313

**Debug Logs:** https://pastebin.com/Q9w2wWTb

# Do not remove anything from your logs and post the full logs! If not everything fits in here use a service like https://pastebin.com to upload them.

**Comment by fryfrog** [comment]
The indexer is nzb.cat and was down for me, @ndoty and downforeveryoneorjustme.com. I couldn't ping it and it didn't respond to `httping` or `tcptraceroute` to 80 or 443.

**Comment by ndoty** [comment]
Manually disabling nzb.cat indexer allowed Radarr to display the movie search results and fetch accordingly.
