### ISSUE TITLE
Save Drone Factory Folder Scan

### ISSUE THREAD

**Issue by MollyBe** [Radarr/Radarr#3648]
So I messed up, and deleted everything in Folder A/Folder B  and Folder A/Folder C . Together they were around 60TB. I managed to get the files back, but only the files and almost no folders (Movie Year 1999). 

First, I tried to get the files to match back up with Wanted - Manual Import - Automatically Import, and left it all night, I came back and other than slowing radarr down it had done nothing else,  I also tried manual import, and left it for sometime but the screen never loaded. 

I then pointed the Drone Factory to the folder and hit save, and then triggered Wanted - Rescan Drone Factory Folder. 2 Minutes later it actually started matching movies back up and moving them to where they should be. So even though drone factory is being deprecated it seems to be the higher functioning function, in this regard.

Because Drone Factory functions where Manual Import does not, we should not depreciate it until Manual Import functions as well as Drone Factory - in this regard.

**Comment by Qstick** [comment]
It likely won't be removed until v2 (which it is already removed in)

**Comment by MollyBe** [comment]
Yes I understand it is being purged in v3. This is a feature request to keep it in v3, as it's replacement cannot perform the functions that drone factory can, atleast that is the case in v2.

Can we leave this thread open for discussion?

**Comment by Kija** [comment]
With the upgrade to v3, Dronefactory seems definitely gone. Your "remote paths" are not an option for me. My remote download clients push files back to radarr on their own, and I'm not willing to reconfigure this piece. Sounds like I'll be looking for a Radarr replacement 👎

**Comment by bakerboy448** [comment]
> With the upgrade to v3, Dronefactory seems definitely gone. Your "remote paths" are not an option for me. My remote download clients push files back to radarr on their own, and I'm not willing to reconfigure this piece. Sounds like I'll be looking for a Radarr replacement 👎

@Kija 
hop on [Discord](https://discord.gg/r5wJPt9)

let's discuss your use case.

good luck finding any actively developed, not broken replacements :P

**Comment by Kija** [comment]
Thank you for helping me out on Discord. I was wrongly assuming that remote paths were effectively mountpoints, but they are not. I was able to use Remote Paths in place of the Drone Factory folder scan.
