### ISSUE TITLE
IMDB Watchlist Not Adding

### ISSUE THREAD

**Issue by Vortec4800** [Radarr/Radarr#3650]
I’m trying to add an IMDB Watchlist using the Radarr API. I’ve tried the ur ID and the ls ID, neither of which are working. Both return a 404 error. Here is the API URL I’m trying to use, you can see the 404 error there.

https://api.radarr.video/v2/imdb/list?listId=ur105994242

I’ve double-checked the IDs are correct. Any insight?

**Comment by Qstick** [comment]
Clicking that link works for me

**Comment by Shifaat** [comment]
I just noticed that radarr has stopped adding movies from imdb list.

Logs show this message:

> An error occurred while processing feed. https://api.radarr.video/v2/imdb/list?listId=ur20274100: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

And that link gives me "502 Bad Gateway"

**Comment by galli-leo** [comment]
@Shifaat Fixed now

**Comment by Shifaat** [comment]
Yes it is. Thank you.
