### ISSUE TITLE
[Bug] aphrodite Not Updating

### ISSUE THREAD

**Issue by zero77** [Radarr/Radarr#3651]
**Describe the bug**
I am using aphrodite and whenever i try to update nothing happens.
There are no errors but nothing seems to happen.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Mono Version: 5.10.1.20
 - Browser and Version [e.g. chrome, safari] (Only needed for UI issues)
 - Version:   2.0.0.1404

**Debug Logs**
https://pastebin.com/raw/X6ePFfjQ

**Comment by Qstick** [comment]
It's not yet supported as an official branch, thus there is no need for it to update. Use docker if you want it to update.

**Comment by Qstick** [comment]
Fixed

**Comment by zero77** [comment]
@Qstick 
So once i install the latest aphrodite build from appveyor, aphrodite should update automatically like the stable build ?

**Comment by Qstick** [comment]
We are using azure pipelines now, but your current appveyor build should update as long as your branch is set to Aphrodite in settings

**Comment by zero77** [comment]
Thanks, also does the wiki need to be updated.

**Comment by Qstick** [comment]
No not yet, since we officially don't support people using Aphrodite, it's got alot things still broken
