### ISSUE TITLE
Priority over lists

### ISSUE THREAD

**Issue by danz1995** [Radarr/Radarr#3652]
I have lists which are user-based (watchlists and alike) and also organic changing lists (box office, popular movies and etc). The first ones are the most important ones, while the other is more for "random" content. 

Since HDD memory is limited, an order of priority on which list should be fully searched and grabbed, at least from what is available atm, would be very appreciated.

**Comment by Qstick** [comment]
Not sure I understand what you are wanting here? All lists are synced on every list sync.

**Comment by danz1995** [comment]
I want Radarr to confirm that it got all movies that are from the highest priority list (or at least searched and nothing returned), then going to do that for the following list in the "priority queue".

**Comment by Qstick** [comment]
So you want Radarr not to look at the next list until all movies are grabbed from the first? Not sure I see a benefit in that.
