### ISSUE TITLE
Set Monitored state to unmonitored when cutoff is downloaded

### ISSUE THREAD

**Issue by Rouzax** [Radarr/Radarr#3653]
It would be nice option when a movie is downloaded in the cutoff quality that the movie state is set to unmonitored afterwards. 
At this moment I need to do this manually.

This would help me to have an easy overview of movies that Radarr still need to do something with.
![image](https://user-images.githubusercontent.com/4103090/62121162-540cc280-b2c3-11e9-87a1-59f3bfe3120f.png)

**Comment by TheCatLady** [comment]
If this is implemented, I would prefer that it is an option rather than the only behavior.  I like to leave all my movies monitored, in case there is a PROPER/REPACK released later on.

**Comment by Rouzax** [comment]
I agree with that, maybe even an option to set after how many days to set unmonitored

**Comment by fryfrog** [comment]
This is in v2.

Also, needing it strongly indicates a mistake in your setup.

**Comment by Rouzax** [comment]
@fryfrog where is this in v2, I don't see it.
Even when the cutoff is reached it will still be monitored and will still be in the monitored filtering list.
