### ISSUE TITLE
Cutoff doesn't seem to be working - aphrodite

### ISSUE THREAD

**Issue by h2xtreme** [Radarr/Radarr#3657]
I'm running the latest artifact of aphrodite and the cutoff for the quality profiles doesn't seem to be working at all.

Also when a new version of the movie is downloaded the file are being added instead of replacing the old version. I end up with the ,720p. 1080p Web-DL and 1080p Bluray for example.

**Comment by Qstick** [comment]
Can you expand on the cutoff not working bit? Do you mean the view, or do you mean it doesn't look at cutoff when downloading?

**Comment by h2xtreme** [comment]
The second one.

For example with Avengers End Game I set the profile to HD-1080p only and the cutoff to Bluray 1080p.

It downloaded 5 or 6 different Bluray 1080p. Happened with other movies too (El Chicano, Captain Marvel for example). From what I could tell after downloading a bluray it didn't go back downloading WEB-DL or HDTV.

The second issue its connected to this one. When a new version gets downloaded it doesn't delete the old ones.

**Comment by Qstick** [comment]
Should hopefully be fixed with latest commit.

**Comment by h2xtreme** [comment]
@Qstick I deployed the latest artifact with the last commits and doing a manual search the results returned already show the cutoff has been met warning (this didn't happen before). So far I would say its fixed.

Will add a few movies and test it out. If I found any issue related to this I'll comment here.

Thanks!
