### ISSUE TITLE
File size - I want the biggest.

### ISSUE THREAD

**Issue by Chris230291** [Radarr/Radarr#3659]
Hi. Is it possible to have Radarr choose the biggest file available at the desired quality?
Modifying the file size sliders for a given quality is not a solution. Some 1080p blu ray rips are tiny if they are old movies which have been up scaled or whatever. Newer movies with all of the fancy audio tracks, HDR and all that stuff are enormous. I just want the best available, which is the biggest file 99% of the time.

Seen this mentioned a few times. Some say it should already do this and its a bug if it doesnt. Other places say to adjust the minimum size sliders. But I already said why that isn't a solution.

Cheers,
Chris

**Comment by majora2007** [comment]
I agree with this feature. Generally higher file sizes for a given quality will have better audio quality. Bumping the minimum can work, but can also exclude a lot of releases. I think it would be best if this was an option on the Profile.

**Comment by TheCatLady** [comment]
You might want to just download remuxes whenever available, in that case.

**Comment by majora2007** [comment]
I disagree on remuxes. Remuxes are generally much, much larger file sizes. The point is larger file sizes at certain quality profiles generally have better bit-rate/audio.

**Comment by fryfrog** [comment]
The biggest file *does* win in the case of a tie. But you can't literally just select the biggest file. Come up w/ a good Custom Format that keys off the big, good quality items. I'd suggest good *sound* is a good indicator of the bigger, good downloads. I use `C_RXRQ_DTS(\-|\.)(HD|X)( |\.|\-)|TRUEHD|ATMOS|DD(\+|P)(|\-|\.)([5-9])|EAC3(\-|\.)([5-9])` to get the good stuff.

**Comment by Chris230291** [comment]
Thanks for the reply. 
Do I just add that in a custom format and enable the custom format in my profile?

**Comment by fryfrog** [comment]
Yeah, though you may also want to limit it to 264 or 265 like `C_RXRQ_(X|H).?264` or `C_RXRQ_(X|H).?265|HEVC`.

**Comment by Chris230291** [comment]
Thanks. Had no idea you could do this and use regex. Working great already.

**Comment by majora2007** [comment]
Thanks @fryfrog, I've been needing this badly. Kept having to intervene to make sure best rip was grabbed.
