### ISSUE TITLE
Private NZBs

### ISSUE THREAD

**Issue by rschmetzer** [Radarr/Radarr#366]
Radarr will retrieve NZBs flagged as private which then fail when added to SAB download queue.

Ex.  	[PRiVATE] Annie.Claus.is.Coming.to.Town.2011.Hallmark.HDrip.720p.X264.Solar-newz[NZB] [b4e9414a77f727] [newzNZB] [01/11] - "[08e222a16b]_[newzNZB]_Annie.Claus.is.Coming.to.Town.2011.Hallmark.HDrip.720p.X264.Solar.mp4"

Please use the search bar and make sure you are not submitting an already submitted issue.

Provide a description of the feature request or bug, the more details the better.
When possible include a log!

Please use our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by rschmetzer** [comment]
Well, it was marked private as part of the name but SABnzbd gave a fatal
error trying to process it.  It came from NZB.ag

**Comment by simonk83** [comment]
I didn't even know private NZB's was a thing, never seen it before :)

**Comment by galli-leo** [comment]
If the download fails, Radarr should now add it to the blacklist anyways and try the next one. I am closing this therefore.

**Comment by rschmetzer** [comment]
The download does not exactly fail.  SABnzbd gives an error and the item
sits in the download queue but doesn't fail or run.  Perhaps this should be
a SABnzbd issue.

**Comment by Fossil01** [comment]
These are just obfuscated posts, nothing fancy.

**Comment by rschmetzer** [comment]
Okay but what would normally decode them, Radarr or SABnzbd?

**Comment by Fossil01** [comment]
The indexer
