### ISSUE TITLE
Add ability to edit Release Group

### ISSUE THREAD

**Issue by theimmortal68** [Radarr/Radarr#3664]
**Is your feature request related to a problem? Please describe.**
Currently Radarr doesn't parses the Release Group if it is not formatted in a particular way (with a dash or brackets I think are the only two supported), which results in some movies missing the release group in the name. Currently the only want to add the release group is to edit the file name manually. This also includes older movies that were imported before this naming convention was used/available.

**Describe the solution you'd like**
Add the ability to edit/add the release group from the Files screen. Currently, if you click on the Quality, it brings up a window to select a new quality from a drop down box. I suggest another column that includes the Release Group that when you click on it brings up a window with a a text box that can be typed into. Then we can add/change the release group in the same manner as changing the quality.

**Comment by fryfrog** [comment]
For now, you can just edit the file name and tack a `-GrouP` to the end and refresh.
