### ISSUE TITLE
QueueSpecification: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Coryrichter94** [Radarr/Radarr#3665]
**Description:**
None of my movies added download. I get the following error on the search tab. 

> Release Rejected
> QueueSpecification: Object reference not set to an instance of an object
> 

**Radarr Version:** 2.0.0.1413

**Mono Version:** 5.14.0.177

**Debug Logs:**
https://pastebin.com/7CFqxZ1z part 1
https://pastebin.com/cBGdm1xN part 2

# Do not remove anything from your logs and post the full logs! If not everything fits in here use a service like https://pastebin.com to upload them.

**Comment by Qstick** [comment]
You are using an unsupported build with known issues. Aphrodite is not ready for mainstream use.
