### ISSUE TITLE
AutoUpdate does not update Info.plist file on macOS

### ISSUE THREAD

**Issue by core-code** [Radarr/Radarr#3666]
1.) download a old version of Radarr (e.g. 0.2.0.1293)
2.) use the built-in AutoUpdate function to update it to the newest version (currently 0.2.0.1358)
3.) verify the auto update has worked correctly by observing the new version string in the webinterface
4.) select the updated app in the Finder and view the version information by using GetInfo/QuickLook/ColumnView

**expected result**: i expect the updated app to show the correct updated version information in the Finder (i.e. currently 0.2.0.1358)
**actual result**: in the Finder you'll see the version information of the initially downloaded version (e.g. 0.2.0.1293)

**regression**: the problem happens because the auto-update updates all the binaries but forgets to update the Info.plist file which contains the version information viewable from the macOS Finder

**Comment by core-code** [comment]
the problem still occurs in the latest version of Radarr, nothing has been fixed yet.

**Comment by oziee** [comment]
mine is exactly the same.. and shows no new updates to get and stuck at 0.2.0.1293
yes i see in github there is newer version for dev version

**Comment by core-code** [comment]
the problem still occurs in the latest version of Radarr, nothing has been fixed yet.

**Comment by Qstick** [comment]
The previous comment is not getting updates because branch is set to master instead of develop

**Comment by oziee** [comment]
not true... bottom of page says 
`Radarr Ver. 0.2.0.1293
develop`

in `settings / general / update / branch` it is set to `develop`

log file says 
```
19-10-20 14:37:44.3|Warn|HttpClient|HTTP Error - Res: [GET] https://radarr.aeonlucid.com/v1/update/master?version=0.2.0.1358&os=osx: 404.NotFound
{"errorMessage":"Latest update not found."}
```

i deleted the install and all the settings, and reinstalled to get the latest develop working and its currently running the latest 0.2.0.1450

**Comment by ta264** [comment]
You say it's set to develop but the URL it's erroring on is master...

**Comment by oziee** [comment]
Yes.. I say it is.. because it is, that would be why I posted it as a problem. Because it’s a problem. As stated the settings and page both reflected ‘develop’ yet it was not looking at the develop URL for updates.. 

But I have sorted my end because I deleted my install and installed the latest code and it’s working and up to date.. that does not mean it’s fixed for others that first posted this problem

**Comment by core-code** [comment]
the last few comments don't seem to have any connection to the actual bug report. if there are other, additional issues, please open additional bug reports.

**Comment by ta264** [comment]
As far as I can tell it doesn't update the plist as you say. Does it make any difference? Without a Mac to test on in reluctant to mess with it

**Comment by ta264** [comment]
I'm not convinced it's a regression, I suspect it's never worked as you hope

**Comment by ta264** [comment]
I also suspect it doesn't work in sonarr

**Comment by core-code** [comment]
the problem still occurs in the latest version of Radarr, nothing has been fixed yet.

**Comment by ourcore** [comment]
I use Radarr and MacUpdater and would really appreciate the info.plist being updated from 2.0 to the actual version (Sonarr has the same issue). Thanks!

**Comment by Qstick** [comment]
Believe in v3 this is fixed to where we update info.plist with actual version in our azure build pipeline. @ta264 is this correct?

**Comment by ourcore** [comment]
> Believe in v3 this is fixed to where we update info.plist with actual version in our azure build pipeline. @ta264 is this correct?

Will v3 be a direct update to v2 or a separate install?

**Comment by ta264** [comment]
I don't think we do edit the plist. Sonarr doesn't either I don't think. I think my view is that we should just wait until it's implemented in sonarr since getting this right will not be easy without a Mac to test on, and my understanding is that it's just a minor UI irritation rather than anything serious

**Comment by Qstick** [comment]
https://github.com/Radarr/Radarr/blob/c7dfd9dcf1a21431f5428f0cf22cecb8e7be7c23/build.sh#L24

**Comment by Qstick** [comment]
We do it in Aphrodite and Lidarr, but I have no clue if it’s working correctly without someone testing it.

**Comment by ta264** [comment]
I think that only makes it into the app bundle package though and is then never touched by the updater, so it's always stuck at the version you originally installed

**Comment by core-code** [comment]
thanks for making progress here. i'd be happy to test anything to help resolve this.

> sed -i'' -e "s/<string>10.0.0.0<\/string>/<string>$RADARRVERSION<\/string>/g" macOS/Radarr.app/Contents/Info.plist 

how will this work if the installed version is not 10.0.0.0?

**Comment by Qstick** [comment]
> I think that only makes it into the app bundle package though and is then never touched by the updater, so it's always stuck at the version you originally installed

Ah yea, I think we discussed that previously.

> how will this work if the installed version is not 10.0.0.0?

The 10.0.0.0 is just a placeholder in the repo info.plist, That line sets the actual version string over that placeholder during build. As @ta264 mentioned though, we have issues with it making it to you via updates etc..

**Comment by core-code** [comment]
any updates?

**Comment by ta264** [comment]
No. If the only issue is it showing the wrong version in finder I'm not sure it's worth the effort / risk of messing with it. Lobby sonarr if it really bothers you, I think it's broken there too.

**Comment by Stanzilla** [comment]
How do you even update to aphrodite these days?
