### ISSUE TITLE
"global Exception Handlers" Task Error: 

### ISSUE THREAD

**Issue by sch1308** [Radarr/Radarr#3668]
Unraid version 6.7.2

radarr version 0.2.0.1358 june 29

[radarr.trace.txt](https://github.com/Radarr/Radarr/files/3469951/radarr.trace.txt)
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/3469952/radarr.debug.txt)
[radarr.txt](https://github.com/Radarr/Radarr/files/3469954/radarr.txt)

![image](https://user-images.githubusercontent.com/7896067/62504782-111d8400-b7c8-11e9-9d29-d710b961e2c5.png)

**Comment by fryfrog** [comment]
I have no idea what this is, feel free to re-open after editing the description to provide more information about what is broken.
