### ISSUE TITLE
Added movies create a map that the movie don't get to after finished downloading

### ISSUE THREAD

**Issue by thu3n** [Radarr/Radarr#3670]
It's hard to explain. I will get you A example.

If i add the movie "Hunter 2019" radarr will make a path to \\server\popcorntime\Hunter(2019)
But the torrent it self create a folder that is named like **Hunter.Killer.2019.1080p.WEB-DL.DD5.1.H264-FGT** so when the torrent is finished, radarr doesn't detect the movie cause it thinks it should be laying in \\server\popcorntime\Hunter(2019) folder. 

How do i change so that radarr go to the correct named movie folder?

**Comment by Qstick** [comment]
Someone can help you out on discord, sounds like your setup is a bit wonky
