### ISSUE TITLE
Increase TMDB Import List limit from 3 pages to no limit

### ISSUE THREAD

**Issue by RandomNinjaAtk** [Radarr/Radarr#3671]
**Is your feature request related to a problem? Please describe.**
Yes, currently it seems the TMDB import list function is limited to a maximum of 3 pages. So I created a very large list of titles for auto import and 5 of the 8 pages are entirely skipped. This does not seem to be an issue with Trakt list importing because you can customize it.

**Describe the solution you'd like**
Add an option similar to the Trakt list integration to allow customization of import size limit

**Describe alternatives you've considered**
Not sure, kinda frustrated cause I just spent a very long time creating a list with over 1800 titles in it and can't use...

**Additional context**
![image](https://user-images.githubusercontent.com/8386416/62713203-56a99f00-b9ca-11e9-8154-864f6abcbd01.png)

**Comment by RandomNinjaAtk** [comment]
After reviewing the code, this is a hard coded limit:

Source file: https://github.com/Radarr/Radarr/blob/develop/src/NzbDrone.Core/NetImport/TMDb/TMDbRequestGenerator.cs

Line 19 <-> 22
```
        public TMDbRequestGenerator()
        {
            MaxPages = 3;
        }
```

So if we can either make this a setting that can be changed via GUI or just up the default limit. I can easily write a pull request to set the number to larger limit, but that's about the extent of my skillset...

**Comment by fryfrog** [comment]
I *thought* the way this worked was that it would chug through them until they all got processed. So every time a movie gets added, the list goes down by one and more are shown. Is this not the case? How long did you let it go?

**Comment by RandomNinjaAtk** [comment]
@fryfrog I wish that was the case, does not appear to be that way in Aphrodite or older...

**Comment by Qstick** [comment]
API v4 should be returning all results now for TMDb lists.

**Comment by RandomNinjaAtk** [comment]
How do I test this? When I re-trigger net import sync, its still not picking up the list items.

**Comment by Qstick** [comment]
Aphrodite was reverted back to v3 API for user lists thus it should be picking up everything on the list... the only thing that is page limited now is the popular lists.

**Comment by RandomNinjaAtk** [comment]
Thx for the update, I'll give it a try again. Last time I checked, I know it wasn't working but that was months ago at this point.

**Comment by RandomNinjaAtk** [comment]
We discussed this, v3 api is limited to 500 results. So this is an issue, but not an easy fix. The only method to pull all is to use v4 api with paging, according to TMDB support forums...

**Comment by rcodehub** [comment]
Not sure if this is a related topic but when searching for new movies to add to Radarr if there are more than (X) number of similar titles you can never add all the movies if you don't specifically know what title to search for.

For example, if you wanted to add every Scooby Doo movie in existence by searching for them in the "Add Movies" search tab, it will bring up a bunch of movies, but will never show you every title because it always shows the same titles that have already been added.

**Comment by Qstick** [comment]
@rcodehub sounds like a completely separate issue, feel free to open another GitHub issue

**Comment by RobinDadswell** [comment]
TMDb lists in Radarr support as many pages as they are made up of as part of this commit https://github.com/Radarr/Radarr/commit/bfc969c45caf528cad1955903e498759bd141a76
