### ISSUE TITLE
Radarr post processing does not understand DVD images

### ISSUE THREAD

**Issue by LeeThompson** [Radarr/Radarr#3672]
If Radarr selects a DVD image release it does not understand the folder/file structure of a DVD and randomly picks one of the VOB files, renames that and calls it a day.  This unfortunately renders the download useless.

If it is intended to support raw DVD (and presumably BluRay) images, it should know to handle it differently than other rips.

For DVD it should keep the VIDEO_TS files/folder intact as is.  

( Unfortunately to calculate the feature length is not a trivial process as you need to actually parse the video title set, determine which is the main feature and calculate that chain's length etc.)

For BluRay it's similar - keep the folders/files intact (all of them).   BluRay uses playlists instead of title sets but they work largely the same way.  Again there's the issue of determining which is the main feature and parsing out the running time.

**Comment by fryfrog** [comment]
Radarr doesn't support DVD or Bluray folder nor `.iso` files. This isn't the first report, feel free to find an older one and give it a thumbs up or comment or link to this one.
