### ISSUE TITLE
Movie Renaming is not keeping the original Folder

### ISSUE THREAD

**Issue by jojogrosso** [Radarr/Radarr#3673]
**Describe the bug**
Movie Renaming - Keeping Original Title for Movie Folder Format - doesn't seem to be working correctly for me.
SS 1 shows my settings
SS 2 shows how the folder gets renamed and moved to my Movies folder
SS 3 is the folder the movie downloads as

I would think it should be the same as how it downloads (like it shows in the "Movies Folder Example in SS 1).  Should my settings be changed for that to happen?

**To Reproduce**
Have the settings like mine and then download a movie to see if it keeps the same folder it downloads as when it gets renamed/moved.

**Expected behavior**
For the movie folder to be the same as the downloaded folder (with the quality & rip group)

**Screenshots**
SS 1: 
![Movie Renaming Settings](https://user-images.githubusercontent.com/25140527/62817352-20bc0600-bb03-11e9-8906-59dbc4be6a11.PNG)
SS 2:
![How the movie gets renamed](https://user-images.githubusercontent.com/25140527/62817374-84deca00-bb03-11e9-9976-f7b96fe41c4b.PNG)
SS 3:
![How the movie downloads](https://user-images.githubusercontent.com/25140527/62817382-9031f580-bb03-11e9-9983-f0c00294925c.PNG)

**Desktop (please complete the following information):**
 - OS: Synology
 - Mono Version: Mono v. 5.18.0.240-12
 - Browser and Version [e.g. chrome, safari] (Only needed for UI issues)
 - Version [e.g. 22] Sonarr Version is 0.2.0.1358

**Debug Logs**
The last movie downloaded was Ode to Joy when debug logging was enabled. Around 12:17AM 8/10.
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/3488514/radarr.debug.txt)

**Comment by fryfrog** [comment]
You need to enable dynamic movie folder names, the option is confusingly named and in two places. In one place, you set the default for *new* movies and then in movie editor you need to set it on all your *existing* movies.

And if Radarr doesn't know the original name/release folder for some reason, it probably won't work right either. And that includes when a file gets changed a little in its movie folder, like if you rename it yourself or have post processing that transmuxes it into `.mp4` which looks like a new file.

Hop on Discord and troubleshoot your issue.
