### ISSUE TITLE
Manual Import - File(s) not being listed

### ISSUE THREAD

**Issue by delize** [Radarr/Radarr#3675]
**Describe the bug**
When having a folder with ~2.5 TB of Movies (Roughly 143 movies in total), Manual Import sits and does not list movies to process. When checking trace, debug, or info logs, there doesn't appear to be relevant information surrounding the folder path being shown in the logs or the logs are not getting written to disk when the operation occurs. 

I have let it sit for 30 minutes and it still does not finish showing the list to process.

This is on a network share using nfs with 1 Gbps line.

I assume this is due to too many files, but since some files do not come in folders and radarr scans all sub-folders, I can't pick out the ones that need manual processing due to them being in the root folder to begin with.

**To Reproduce**
1. Go to `radarr/wanted/missing`
2. Click on `Manual Import`
3. Select a directory
4. Wait forever

**Expected behavior**
A list of movies is shown for processing.

**Screenshots**
![image](https://user-images.githubusercontent.com/4028612/62840641-cf229100-bc52-11e9-9776-1ba7b400042d.png)

**Desktop (please complete the following information):**
 - OS: 

```
Linux Ubuntu 18.04 LTS
```

 - Mono Version: 

```
ii  mono-runtime                                                6.0.0.319-0xamarin2+ubuntu1804b1                            amd64        Mono runtime - default version
ii  mono-runtime-common                                         6.0.0.319-0xamarin2+ubuntu1804b1                            amd64        Mono runtime - common files
ii  mono-runtime-sgen                                           6.0.0.319-0xamarin2+ubuntu1804b1                            amd64        Mono runtime - SGen
ii  mono-utils                                                  6.0.0.319-0xamarin2+ubuntu1804b1                            amd64        Mono utilities
ii  mono-xbuild                                                 6.0.0.319-0xamarin2+ubuntu1804b1                            all          MSBuild-compatible build system for Mono

```
 - Browser and Version [e.g. chrome, safari] (Only needed for UI issues)

```
Version 76.0.3809.87 (Official Build) (64-bit)
Windows 10 X64 Client
```

```
Version
0.2.0.1358
```

**Debug Logs**
Turn on debug logs under Settings -> General and wait for the bug to occur again. **Upload the full log file here (or another site and link it). Issues will be closed, if they do not include this!**
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/3490550/radarr.debug.txt)

**Comment by fryfrog** [comment]
There is probably a reason this is happening, hop on Discord and troubleshoot w/ someone to narrow it down. I don't think 2.5T / ~150 movies should be a big deal for Wanted -> Manual import. But you can always bust it down bisect style until you find the size/number it is happier with.
