### ISSUE TITLE
Automated Search For English Movies

### ISSUE THREAD

**Issue by AnythingOldSkewl** [Radarr/Radarr#3676]
I ran into an issue where Radarr automatically downloaded a movie with Chinese audio. Is there a way to prevent this? I see there is a "custom format area," but this looks like it only checks for titles. Therefor I could be eliminating legitimate results. Can Radarr/Sonarr read MediaInfo? Is there away to get around this?

**Comment by henkin67** [comment]
Hello,
What was the name of the release file ?
Did specify it any language ?

**Comment by AnythingOldSkewl** [comment]
> 
> 
> Hello,
> What was the name of the release file ?
> Did specify it any language ?

Oh, I deleted it already. I am almost positive that it was called "Believer." What was even a bigger issue for me tho, was the fact that it also had Chinese characters in the release name. I would have rather that result be omitted entirely. I guess maybe it's harder to programmatically do those type of releases. I was kind of hoping it could read the media info in the file, but then I realize even if Radarr could, I'd still have to download it first.

**Comment by fryfrog** [comment]
There isn't much tuning that can be done w/o the release name and how the indexer described it.
