### ISSUE TITLE
Bulk import: Display Search result issue

### ISSUE THREAD

**Issue by tcntad** [Radarr/Radarr#3677]
**Describe the bug**
When bulk importing movies it finds every movie I have in that folder.
At the very bottom it displays correct number unless I choose to display 1000 movies per page it looses 7 movies, displaying 748 results instead of 755.

If I switch back to 100 or 500 it display every object untill I go to the next page then it loses 7 movies again

**To Reproduce**
1. Go to ' Add movies' > 'Bulk import movies' > 'Pick a folder with roughly 755 movies like I have

**Expected behavior**
I obviously expect every movie to show up nomatter how many results per page I choose
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/3491863/radarr.debug.txt)

**Screenshots**
https://imgur.com/a/KfxY9Zc

**Desktop (please complete the following information):**
 - OS: Windows Server 2019
 -Browser: Latest Chrome.

**Debug Logs**
Turn on debug logs under Settings -> General and wait for the bug to occur again. **Upload the full log file here (or another site and link it). Issues will be closed, if they do not include this!**

EDIT 1:  12/8 13:25
I have renamed the problematic folders and files to fit name scheme, now it displays 686 results with 500 per page

EDIT 2: 15:16
I renamed the files again and now it seems to be working

**Comment by fryfrog** [comment]
I wonder if maybe there are 7 movies it can't match? When you're only displaying the partial list, those 7 aren't in it. When you display *all* of them or flip to the page w/ them, they don't match and don't get shown?

Maybe you'll get lucky and this is already fix in v2.

**Comment by Qstick** [comment]
Would be good to test, but hopefully it is fixed in v2

**Comment by tcntad** [comment]
Yea it count map those 7 movies to TMDB.  It did display all of them att first but as soon as I changed page ord changed movies to display per page it would loose those 7.

I had to manually rename them. One of them movies were The man from U.N.C.L.E (2015) 
I removed the dots and it worked, however radarr wants to rename the movie and it woudnt be able to map it. 

Im thinking its too many characters
