### ISSUE TITLE
Movie Quality Setting

### ISSUE THREAD

**Issue by qweasdzxc787** [Radarr/Radarr#368]
It would be nice if we could set the quality setting for existing movies like we can with TV episodes on Sonarr. Right now it is identifying files as HDTV-1080p when they are Blu-ray re-encodes.

**Comment by benjmd** [comment]
Covered in #326.

**Comment by TheRealShiz** [comment]
Is it covered though?  Because #326 seems to be focused on Radarr ignoring the monitored state.  In addition, we can't manually set the quality of a movie so all Bluray re-encodes are get imported as HDTV-1080p and there is no way to change it.

**Comment by benjmd** [comment]
Yeah, I said that in #326.
