### ISSUE TITLE
Test all indexers

### ISSUE THREAD

**Issue by ljmerza** [Radarr/Radarr#3680]
**Is your feature request related to a problem? Please describe.**
When jackett goes down radarr says all my indexers are down. to get them back up i either have to restart radarr or test each indexer to let radarr know it works again. I'd like a button to just test all indexers. 
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Qstick** [comment]
Same as #3549 and #3275
