### ISSUE TITLE
Redirect from /login if user is logged in

### ISSUE THREAD

**Issue by brunobraga** [Radarr/Radarr#3683]
**Is your feature request related to a problem? Please describe.**
Yes. The main /login page shows up the form for login, but once you submit the form, it returns to the login screen, on an infinite loop. if you go to the root (/) site, you can see you are logged in.
e.g.: http://localhost:7878/login
once you log in, it returns to the same page:
http://localhost:7878/login?returnUrl=
and so on...
But if you hit http://localhost:7878/, it shows you are actually logged in.

**Describe the solution you'd like**
Automatically redirect to root if you are logged in (essentially you shouldn't access the login form if you are logged in)

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by brunobraga** [comment]
More context, I found the solution here:
https://www.reddit.com/r/radarr/comments/6bo7ok/login_issue/

**Comment by bakerboy448** [comment]
doesn't appear to be an issue in v3 anymore
