### ISSUE TITLE
Import of IMDB lists missing some movies out

### ISSUE THREAD

**Issue by renzzla** [Radarr/Radarr#3684]
**Describe the bug**
I noticed that certain movies on my IMDB watchlist were not being imported into Radarr. Further investigation shows they are not in the data supplied by the call to api.radarr.video
**To Reproduce**
One affected movie is "A Dog's Journey" - https://www.imdb.com/title/tt8385474
1. I created a test list on IMDB called "testlist" - https://www.imdb.com/list/ls090537501/
2. I added "A Dog's Journey" to it. I also added a movie that is unaffected by this problem, "The Sun Is Also A Star" - https://www.imdb.com/title/tt6423362
3. Checking the list on IMDB shows both movies added.
4. If I then call https://api.radarr.video/v2/imdb/list?listId=ls090537501 from my browser,  it only shows "The Sun Is Also A Star" - there is no info for "A Dog's Journey".
5. Going through my Watchlist, I have found a few other movies that also don't appear on api.radarr.video, such as "Black and Blue" (https://www.imdb.com/title/tt7390646), "Escape Room 2" (https://www.imdb.com/title/tt9844522), "Fatherhood" (https://www.imdb.com/title/tt4733624)

**Expected behavior**
All movies on a list should be imported

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Mono Version: N/A as this is not a problem with Radarr
 

**Debug Logs**
Turn on debug logs under Settings -> General and wait for the bug to occur again. **Upload the full log file here (or another site and link it). Issues will be closed, if they do not include this!**
[api.txt](https://github.com/Radarr/Radarr/files/3497120/api.txt)
api.txt shows what is returned from call to api.radarr.video. No debig logs as this is not a Radarr issue.

**Comment by BMWfan** [comment]
@renzzla  i had the same issue as you describe. But i could resolve this by taking many movies in the list and delete the first one from it.. Then magic happens and all other movies are present.

**Comment by renzzla** [comment]
Doesn't sound the same. All the other movies in the list appear in the data from api.radarr.video just fine - it's just certain movies that don't, no matter where they are in the list, and removing or adding others makes no difference.

**Comment by deepfriedmind** [comment]
I'm having the same issue. Any news?

**Comment by thenetbug** [comment]
I am having the same issue. https://www.imdb.com/list/ls069398953/ (added in Radarr as /imdb/list?listId=ls069398953) has content that is not being pulled in the API call. I am attaching the results of the API call.
[list.txt](https://github.com/Radarr/Radarr/files/5180098/list.txt)

**Comment by ta264** [comment]
This is a known issue with 0.2 and will not be fixed

**Comment by thenetbug** [comment]
Forgive me... what is 0.2? Is that the version of Radarr? Is there a workaround? Should I be updating something?

**Comment by ta264** [comment]
It's the version of Radarr you are using. V3 is still in aloha and will fix this. You probably don't want to update yet, see the discord channel for details.
