### ISSUE TITLE
All indexers unavailable due to failures - mono issue?

### ISSUE THREAD

**Issue by Jorman** [Radarr/Radarr#3687]
Hi, I'm on debian buster with
Radarr version -> 0.2.0.1391
Mono Version -> 6.0.0.319 (tarball Fri Aug 9 16:27:44 UTC 2019)

I've some problem, I think with mono, but is strange because the same issue is no present on Sonarr.
After a while, about 2 days of running, all indexer stop working, Jackett is installed on the same machine so all requests are made by localhost.

Can I provide some log or other or do you already know this problem and maybe do you know a good workaround?

**Comment by willmcginnis** [comment]
https://github.com/Sonarr/Sonarr/issues/2802

I forget if there's an open bug for this on Radarr but Sonarr spent a looong time with it and just really recently fixed it.
