### ISSUE TITLE
Radarr forgetting set password on service restart

### ISSUE THREAD

**Issue by mbaran5** [Radarr/Radarr#3688]
**Describe the bug**
When a password it set on Radarr, it works temporarily until the service is restarted. Once the service is restarted, I cannot log into Radarr. 

**To Reproduce**
Set a forms or popup password. Log out and in. Stop/Start Radarr service. Cannot log in. Only way in is to disable auth in config file. Sometimes it will hold the correct password until a server reboot, in which then it no longer works. It's not entirely predictable. 

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Mono Version: Mono 6.0.0.319
 - Browser and Version Chrome latest

**Debug Logs**
Password errors are not being logged... Nothing to upload.

**Comment by Bartalos** [comment]
i have it even worse. suddenly i couldnt log in and i DIDNT have a password set. I see none in config.xml and i cant figure out how to log in

**Comment by fryfrog** [comment]
This sounds like your Radarr isn't reading config / db from where you think it should be or maybe you're not preserving config some how. Are you using Docker?

**Comment by mbaran5** [comment]
I am not using docker, and this is not a support request. When the service ends non gracefully, the password is corrupted and you cannot log back in. I can repeatedly reproduce this. Kill the service non-gracefully and a forms based password login will not work. Ubuntu 18.04.

**Comment by fryfrog** [comment]
That seems super weird. The password should be set *once*, when you save it. How would an abnormal exit corrupt it? Re-opened for investigation.

Can you capture some trace logs from doing an abnormal kill and also the post kill startup?

**Comment by mbaran5** [comment]
Yes. I was just about to log in and come up with a definitive way to reproduce it. Will update with anything I can gather. I don't have a password set as of now.
