### ISSUE TITLE
Recognise subfolders, multi-movie folders.

### ISSUE THREAD

**Issue by jaxjexjox** [Radarr/Radarr#3690]
**Is your feature request related to a problem? Please describe.**
Spent 6 hours trying to scan my movies, program unable to recognise for example

\\fileserver\media\movies\movie 01.mkv
\\fileserver\media\movies\movie 02.mkv
\\fileserver\media\movies\movie 03.mkv

program is ALSO unable to recognise

\\fileserver\media\movies\**action**\movie folder\movie file 01.mkv
\\fileserver\media\movies\**action**\movie folder\movie file 02.mkv
\\fileserver\media\movies\**horror**\movie folder\movie file 01.mkv
\\fileserver\media\movies\**horror**\movie folder\movie file 02.mkv

**Describe the solution you'd like**
Recognise movies within subfolders (and subfolders within those)
Recognise multiple movies in a single folder

**Describe alternatives you've considered**
Couchpotato, Kodi, Plex, Media Browser, all capable of working with this

**Additional context**
This has been complained about, across the internet, multiple times, I had to google to find out this doesn't support this.

**Comment by azza10** [comment]
Radarr and sonarr both default to a file/folder structure that is fairly universally compatible. What exactly about those structures do you prefer over radarrs //root/movies/{title}/file.xxx?

**Comment by jaxjexjox** [comment]
I don't care if Radarr decides the /import/ (destination) library ends up being neatly filed correctly - this is what couchpotato does.

I *do* very much care, that Radarr is incapable of scanning a folder, containing movies, 'below it' in any capacity - if Plex, Kodi, Emby, Media Browser (and more) can all scan subfolders, AND this problem has been asked about, multiple times across the web from baffled people, it seems to me it should be added to scan this content in.

**Comment by azza10** [comment]
So I reread your post as I believe I misunderstood your issue... You're saying Radarr doesn't scan subfolders?

This is not the case in my experience. Add your movies directory (not media) as a root for in Mass media import.
E.g.
F:\media\MOVIES\title\files.xxx
OR
F:\media\MOVIES\files.xxx
NOT
F:\MEDIA\movies\title\files.xxx
OR
F:\MEDIA\movies\files.xxx

Reason being, radarr is designed to be paired up with sonarr, radarr handling movies, sonarr TV.
Radarr and sonarr are expecting to be pointed to your movies or TV directory. If they're pointed to your main media directory they can get confused.

**Comment by azza10** [comment]
Alternatively, use filebot to quickly restructure before importing.
Radarr probably isn't liking the root directory you're giving it.
I doubt the devs will be willing to code in this functionality given a free tools can fix this issue in a matter of minutes.

**Comment by jaxjexjox** [comment]
I can not restructure my files, for multiple reasons, including, I simply do not want to.


Also no free tool will fix the complexity of my file structure.
Furthermore, some types of people may decide to store in wacky wages

Movies\1990s\
Movies\2000s\
Movies\2010s\


etc

Some of us have VERY big libraries and Radarr isn't the ony thing we work with.

This is pretty standard functionality.

**Comment by insolentgeek** [comment]
I just began to use radarr and ran into this very poor design flaw.

> Radarr and sonarr both default to a file/folder structure that is fairly universally compatible.

Sure, because one typically wants a TV series of 20+ directly related files in a more organized manner. This tool is mandating a single movie file be contained in it's own directory, that's pure nonsense.

**Comment by fryfrog** [comment]
This is a long standing feature request, find it and +1 one it and comment on it if you wish.
