### ISSUE TITLE
Failed Update (Debian/UI) - Cannot Load/Use Radarr - No Debug Log to share :(

### ISSUE THREAD

**Issue by squirrelboot** [Radarr/Radarr#3693]
**Describe the bug**
Updated via the WebUI (running on a Debian box). Update got stalled/stuck.
Tried pressing update again. Nothing happened. Restarted.
Radarr will no longer run/load.

**Expected behavior**
It would update and reload as it had in the past. 

**Desktop (please complete the following information):**
 - OS: Debian
 - Mono Version: 6.0.0.319
 - Browser and Version [e.g. chrome, safari] (Only needed for UI issues)
 - Version of Radarr is the one before the current one I guess. 

**Debug Logs**
I cannot get a debug log, because it requires using the webui. Which does not open/work because of this bug causing it to not load in the first place.

**Comment by squirrelboot** [comment]
I am looking for CLI commands which I can run to get it working again. Any help is welcome

**Comment by h2xtreme** [comment]
What branch are you running on?

A git pull inside the radarr directory should put everything in place.

**Comment by squirrelboot** [comment]
> What branch are you running on?
> 
> A git pull inside the radarr directory should put everything in place.
> 
> EDIT: If not downloading the latest release tar.gz and unpacking it over the old one will do the trick

Thank you. That resolved it. 
I followed the instructions for my distro (Debian) from here: https://github.com/Radarr/Radarr/wiki/Installation#manually-install-radarr
