### ISSUE TITLE
Search from russian index

### ISSUE THREAD

**Issue by Anzic23** [Radarr/Radarr#3700]
**Describe the bug**
1. During the search, the name is searched for in English or Russian. The tracker gives the name in both languages and the radar cannot add a file for download.
Failed to map movie, found title Перелом / Fracture, expected one of: Перелом, Fractured
2. There are still times when a film finds out, but he writes that the language is not the same, although the title has the name of the film in Russian
Russian is wanted, but found English for `Пленницы / Prisoners (2013) BDRip 1080p от New-Team`

**Expected behavior**
I would like to be able to set a template for several languages, with a "/" for example, as in this case.

 - OS: Docker
 - Mono Version: 5.20.1.34

**Comment by Mavrag** [comment]
CouchPotato has this 
![32657834-3fbd3bb8-c628-11e7-8fc9-13a9b34c12cd](https://user-images.githubusercontent.com/19551962/63722576-1d8f7c80-c85c-11e9-8c1f-d3441f4fabed.png)
![32657981-eafd81b8-c628-11e7-963f-220dd6faa41c](https://user-images.githubusercontent.com/19551962/63722577-1d8f7c80-c85c-11e9-9bce-de4cfffc5af3.png)
Have been wanting this for years now.

**Comment by Mavrag** [comment]
Having the same problem, would be really awesome if someone can fix this.

**Comment by SleeplessSloth** [comment]
Yes, it's still an issue and a pretty big one. (Almost) all Russian trackers use the `Russian title / Original title (The author in Russian / The author in the original language) [year, country, genres, quality] language1 + language2 + language3` format, e.g. `Человек-паук: Вдали от дома / Spider-Man: Far from Home (Джон Уоттс / Jon Watts) [2019, США, фантастика, боевик, приключения, BDRip 1080p] Dub + Ukr + Sub (Rus, Ukr, Eng) + Original Eng`, and Radarr just can't deal at all with titles like these

Radarr Ver. 0.2.0.1480
