### ISSUE TITLE
Movie year error

### ISSUE THREAD

**Issue by romanoh** [Radarr/Radarr#3701]
**Describe the bug**
The movie is from 2018, and it dont auto download because the file says 2019
Release rejected: "Fail to map movie, expect year 2018, found 2019"

**Screenshots**
https://i.imgur.com/0GSDq2E.png

Radarr Ver. 0.2.0.1358

**Comment by Zindaar** [comment]
This may be related 
When bulk importing a movie:
![Bulk Import](https://user-images.githubusercontent.com/54102325/63499540-53350e00-c4c8-11e9-91a5-c3bbfa5454c7.JPG)
The 1976 movie matches to a 2011 TMDB release 
https://www.themoviedb.org/movie/991-the-man-who-fell-to-earth
EXCEPT!
![TMDB](https://user-images.githubusercontent.com/54102325/63499614-7364cd00-c4c8-11e9-971a-c048ce4e5c6c.JPG)
The TMDB release is for the 1976 version, but the bulk importer is showing the latest release date (and I would assume matching on it for downloads, as described in the original issue)
