### ISSUE TITLE
Randomly crashing

### ISSUE THREAD

**Issue by PJGitHub9** [Radarr/Radarr#3702]
**Describe the bug**
When searching for movie files, radarr randomly crashes (to be specific, T0y St0ry 4). Other movies the feature works fine with

**To Reproduce**
1. Add movie
2. Click on movie title then "files"
3. Let it load

Radarr crashes

**Expected behavior**
Movie results should load

**Screenshots**

**Desktop (please complete the following information):**
- OS: Windows 10

**Debug Logs**
Dont show any error at all.

**Comment by PJGitHub9** [comment]
Heres my trace file 
[radarr.trace.txt](https://github.com/Radarr/Radarr/files/3518045/radarr.trace.txt)

**Comment by Qstick** [comment]
I Imagine something is off about that file. It is reading size as `-9223372036854775808`
