### ISSUE TITLE
Radarr Grabs a movie shows it in iCal and in history, but the movie page doesn't exist.(with video)

### ISSUE THREAD

**Issue by luluhoc** [Radarr/Radarr#3705]
**Describe the bug**
Radarr Grabs a movie shows it in iCal and in history, but the movie page doesn't exist when clicked from the history it shows 404 and it does not show up in search.
Movies are grabbed from the lists, this error occurs only with some movies most of the movies are added correctly. 
**To Reproduce**

**Expected behavior**

**Screenshots**
https://www.youtube.com/watch?v=7xeLcn2Acps&feature=youtu.be

**Desktop (please complete the following information):**
linuxserver/radarr:latest on docker

Linuxserver.io version:- 0.2.0.1343-ls15 Build-date:- 2019-05-03T10:52:14-04:00
--

**Debug Logs**
for someone to search in the logs, the movies wrongly added 
El Chicano
The Last Black Man in San Francisco
Family
Driven
that I know of.
https://pastebin.com/LsaQtRN0
I've enabled debug logs now so I'll update when it will occur

**Comment by fryfrog** [comment]
Try outside of Organizr and try in an Incognito Window. Try getting the actual URL from the link.
