### ISSUE TITLE
Site Status monitoring is not catching obvious downtimes

### ISSUE THREAD

**Issue by Zopieux** [Radarr/Radarr#3706]
**Describe the bug**

At this moment, both https://mappings.radarr.video/ and https://api.radarr.video/v2/ are down with 5xx errors but the monitoring page states that everything's fine and green:

![image](https://user-images.githubusercontent.com/81353/63295069-13093c00-c2cc-11e9-93cb-26046810da43.png)

Keeping things up & running can be difficult, but please make sure the monitoring is bit more reliable when downtimes happen.

**Comment by Qstick** [comment]
Mapping main page has been down a bit, but the service still works from Radarr
