### ISSUE TITLE
AND on Custom Format

### ISSUE THREAD

**Issue by ferllings** [Radarr/Radarr#3708]
Hello,

I'm trying to write a Custom Format to filter for x265 and exclude VFQ lang.
But I have difficulties to understand how to filter for BOTH at the same time.

I've tried to associate both filters in a single CF.
If I separate the filters the group still validate if only one is valid.
And adding "AND" in the filter doesn't seems to work.
<img width="922" alt="Screenshot 2019-08-20 at 08 53 45" src="https://user-images.githubusercontent.com/2118130/63327061-cb1b0100-c32d-11e9-9465-0fe42f785ac6.png">

Thanks for your help.

**Comment by henkin67** [comment]
Hello,
Did you try with C_RXRQ_.... and C_RXRQN?
The RQ specify that the label is mandatory and then the test has to be true to put the group at true.
My understanding is that if you don't specify RQ, if one custom format match, in the group will match.

**Comment by ferllings** [comment]
Thanks That was it !
