### ISSUE TITLE
Profile quality

### ISSUE THREAD

**Issue by Hatzz** [Radarr/Radarr#3709]
Description:
I want to reorder the qualites in profiles but it is not possible since there are no reordering icons.
I was using firefox without addons and it did not work, neither did chrome with ublock origin. I found that it works on chrome without any addons.

I don’t know what could cause this but thought I would report it since it is probably a common problem.

**Comment by henkin67** [comment]
Hello,
Same behavior on my side.
I have disable uBlock Origin on the domain name where my Radarr instance is installed.
