### ISSUE TITLE
Option to send propers as paused 

### ISSUE THREAD

**Issue by emko** [Radarr/Radarr#371]
Problem is P2P is using the proper/repacks tags and this causes a problems if you have already downloaded a scene release and you are happy with it and it has no issues there is no need to now replace it with a useless proper for no reason, so i think it would be helpful if all propers get paused in nzbget or what ever download software a user uses so we can decide if its needed or not. Also auto download repack if its a repack from the group you already downloaded other wise ignore it.

or do something with a predb to check, not sure how that would work out

what do you guys think?

**Comment by simonk83** [comment]
I mean they're propered for a reason.  Repacks I understand.

**Comment by emko** [comment]
@simonk83 clearly you don't understand what propers are, in the scene you can release a proper for something that another group released but didn't follow the rules,bad encode, etc so yes of course if you have only scene releases you would be fine to just auto download the propers since its fixing a issue, but since now you have to deal with P2P groups who also for some reason release propers why would you want to replace a perfectly fine copy with another for no reason? or vise versa 

here is a example Raddar grabs a scene released movie perfectly fine copy, now some P2P group releases a repack for their copy and Raddar grabs this and replaces your perfectly fine copy for no reason, same deal with proper because we have to deal with p2p and scene releases we get this mix up so for people who don't have unlimited bandwidth a option to send propers to be paused and auto download repacks only if same group.

**Comment by vertigo235** [comment]
I had to turn off propers download, not sure if it's going to be worth using for movies given how many different releases there are for movies.

**Comment by onedr0p** [comment]
Moved to http://feathub.com/Radarr/Radarr/+10

**Comment by desimaniac** [comment]
@vertigo235 I did the same. I wish there was a way for Radarr to check predb sites for OK'd propers so that it would not pick up any random one.
