### ISSUE TITLE
Torrents queued and not yet started have "time left" set as 00:00:00

### ISSUE THREAD

**Issue by henkin67** [Radarr/Radarr#3711]
Hello,
I'm using Deluge as torrent client.
In Radarr, when the torrents are queued but not yet started to download their "time left" are set to 00:00:00 in the Activity section, queue tab.
There is two issues with that: 
1. it has no sense to have "time left" set at 0 minutes if the download didn't begin
2. when I'm sorting the movies to know when the firsts will be finished to be downloaded, the "0 minute left" are showing first but I know that is not true. And when I have 20+ movies queued, I cannot see which movies will be finish on the first page.

The easiest way is to not put time left (or a text like "unknown") for the ones "queued" and be sure that "no time left" is the highest value for sorting purpose.

![image](https://user-images.githubusercontent.com/29369709/63407414-bbaebd00-c3ec-11e9-9a38-cfe59d347167.png)

**Desktop:**
 - OS: Windows
 - Mono Version: 5.20.1.34
 - Browser: Chrome
 - Radarr version 0.2.0.1358

**Comment by fryfrog** [comment]
My *guess* is that Radarr is just reporting what the download client says.
