### ISSUE TITLE
Conditional Renaming

### ISSUE THREAD

**Issue by millercentral** [Radarr/Radarr#3712]
**Is your feature request related to a problem? Please describe.**
File renaming patterns that depend on conditions are needed.

**Describe the solution you'd like**
It would be great to have support for conditionals in the file renaming templates. For example:
{if:mediainfo.HDR="HDR"}.HDR.{endif}   // don't add ".HDR." to rename string if file is not HDR.
{if:mediainfo.AudioCodec="TrueHD" + mediainfo.AudioChannels="7"}.Atmos.{endif}  

**Describe alternatives you've considered**
I looked at trying to run a script after download to fixup the filenames based on conditions, but it was too cumbersome.
 
**Additional context**
Doesn't need to be overly complex. {elseif} and {else} would be nice but not required, =, != for variable value eval (maybe "~" for "contains" if you are feeling ambitious), and "+" to test multiple variables. Fine to assume all variables are strings.

Thank you for considering!

**Comment by fryfrog** [comment]
This is a pretty cool idea that you should suggest to Sonarr and get ported to Radarr/Lidarr. :)

**Comment by fryfrog** [comment]
And from Discord, @Taloth says `{.MediaInfo.VideoDynamicRange}` should do what you want for HDR at least.

**Comment by millercentral** [comment]
I think the problem with the HDR one is the name would be left with extra dots around where "HDR" should be. (ie,  "Cool Movie (2019)..MKV" instead of "Cool Movie (2019).HDR.MKV"), no?

**Comment by Taloth** [comment]
The renamer already strips out double dots. But you can also use the format fry posted. The delimiters within {} are omitted if the value is empty.

**Comment by millercentral** [comment]
Aha, I did not know that, thank you. An alternate solve then for my specific issue would be if "AudioCodec" reported "atmos" or "dtsx" for media files containing spatial audio. The latest versions of mediainfo.dll do report this I believe.

**Comment by Taloth** [comment]
See, you should've asked for that rather than inventing a scripting language. Issue "Radarr/Sonarr doesn't detect this specific Atmos file properly".    
Post the mediainfo output for the file to confirm.  :smile:

**Comment by bakerboy448** [comment]
sounds like this was fixed in the aforementioned commits
