### ISSUE TITLE
Problems with Catalina Beta even when using command line

### ISSUE THREAD

**Issue by dkids** [Radarr/Radarr#3714]
Since updating to Catalina Beta, Radarr has not been able to import movies on my system.   Sonarr has a similar [issue](https://github.com/Sonarr/Sonarr/issues/3168) where starting it from the command line works (television shows are recognized and imported).

Version
0.2.0.1358
Mono Version
6.0.0.313 (2019-02/9d7bbcffa75 Thu Jul 11 13:01:58 EDT 2019)

PS: I'm not thrilled to be running a beta on a "production system" (an old Mac Mini in a basement corner that just serves media) but upgrading stopped the system from crashing every day for no apparent reason, as it was doing with Mojave.

**Comment by fryfrog** [comment]
Not a lot of useful information here.
