### ISSUE TITLE
Ignore/Hide incorrect download listings

### ISSUE THREAD

**Issue by TheFiZi** [Radarr/Radarr#3715]
**Is your feature request related to a problem? Please describe.**
From time to time the indexer I use (and I'm sure other indexers) list the wrong files with the wrong movie. I have a movie right now with 7 incorrect listings associated with it.

**Describe the solution you'd like**
The ability to mark items in the 'search' tab of a movie as 'Ignored' or 'Incorrect'

**Describe alternatives you've considered**
Ignoring them myself but if I manually run the scan process, or eventually the backlog process runs, it's going to try and download a bunch of incorrect files.

**Additional context**
Happy to provide it if required.

**Comment by fryfrog** [comment]
You can black list releases. There is no automatic backlog search. Report the issue to your indexer.
