### ISSUE TITLE
"Missing Only" filter also includes "Not monitored" movies

### ISSUE THREAD

**Issue by TheFiZi** [Radarr/Radarr#3717]
**Describe the bug**
When looking at my list of Movies and I click the filter button to only show "Missing Only" moves that are "Not Monitored"

![image](https://user-images.githubusercontent.com/1762426/63642790-9bdff900-c679-11e9-96be-6a85e5fb4351.png)

![image](https://user-images.githubusercontent.com/1762426/63642793-a8645180-c679-11e9-8ae6-92676cad37c8.png)

I believe the 'UnMonitored' filter is meant to display these and don't believe they should be listed under "Missing Only"

![image](https://user-images.githubusercontent.com/1762426/63642801-cc279780-c679-11e9-992e-3b6a5af3c5a6.png)

**To Reproduce**
1. Login to Radarr
2. Click 'Movies'
3. Click 'Missing only'
4. Scroll through list and 'Not Monitored movies are listed along with the 'Missing' movies

**Expected behavior**
Only 'Missing' movies should be displayed

**Screenshots**
Screenshots woven into my amazing description of the issue :D

**Desktop (please complete the following information):**
 - OS: CentOS 7.6.1810 64-bit
 - Mono Version: 4.6.2.16/ac9e222
 - Browser and Version: 76.0.3809.100 (Official Build) (64-bit)
 - Version: 0.2.0.1358 - 2019-06-29

**Debug Logs**
N/A

**Comment by fryfrog** [comment]
I think the Sonarr v3 -> Radarr v2 port adds some much better filtering options, so fingers crossed on that. Maybe try Sonarr v3 and confirm it works more like what you'd want?
