### ISSUE TITLE
Display current quality of movie when importing existing

### ISSUE THREAD

**Issue by kieranlee1970** [Radarr/Radarr#372]
This would be handy, for instance if you only want to monitor movies that are currently SD to grab HD versions when available.

Also adding 3D to descriptions and download options would be useful so can choose this for those rare movies worth grabbing in 3D

Thanks

**Comment by galli-leo** [comment]
@fedoranimus We could add this in the multi import table view.

**Comment by fedoranimus** [comment]
Yup, makes sense.

**Comment by onedr0p** [comment]
Moved to http://feathub.com/Radarr/Radarr/+9
