### ISSUE TITLE
QMono and Radarr on QNAP

### ISSUE THREAD

**Issue by Pseudomax** [Radarr/Radarr#3721]
There seems to be an unstable connection/relationship between the packages:
Qmono_5.20.1.19_x86_64.qpkg
Radarr_0.2.0.1067.qpkg

I have a QNAP TS-453A and have been using CouchPotato until about a month ago when it failed to start. I therefore found Radarr and already use Sonarr so this is looking a good fit! However when I update the Radarr app from within the settings/system it seems to cause an issue with QMono. Certainly I have had to remove and reinstall both packages to get this working again.

**Comment by fryfrog** [comment]
I'm not sure what you expect anyone to be able to do w/ literally no useful information.
