### ISSUE TITLE
this.sync is not a function

### ISSUE THREAD

**Issue by vinz243** [Radarr/Radarr#3723]
**Describe the bug**

I am unable to save any settings with the latest pre-release on Firefox, Chrome works fine

**To Reproduce**
1. Modify "Rename Movies" settings
2. Save, nothing happens
3. Open dev tools

**Expected behavior**
Settings saved

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows but server on linux
 - Mono Version: 5.18.0.240 (Debian 5.18.0.240+dfsg-2ubuntu2 Wed Apr 17 23:39:09 UTC 2019)
 - Browser and Version: Firefox 68.0.2
 - Version: 0.2.0.1358

**Debug Logs**

```
TypeError: this.sync is not a function backbone.js:492
    save Backbone
    saveSettings SettingsModelBase.js:16
    Backbone 2
    _save SettingsLayout.js:268
    _save self-hosted:1003
    jQuery 2
```

**Comment by pete-oconnell** [comment]
Has anyone investigated this yet? I've got the same issue.

**Comment by pete-oconnell** [comment]
I've found the cause of this - if you've started Radarr and turned on authentication the website will continue to work as expected however when it comes to saving settings etc this issue happens. If you close the browser and reopen, it will ask for login details and then the settings will save correctly.

An enhancement request should be raised to alert the user to not be logged in, or alternatively once the user enables authentication it throws them back to the login screen.

**Comment by vinz243** [comment]
I never changed anything about the authentication... where is this parameter?
