### ISSUE TITLE
Import existing movie folders/files without adding new root folder(s)

### ISSUE THREAD

**Issue by douglas24** [Radarr/Radarr#3724]
**Is your feature request related to a problem? Please describe.**
When bulk importing movies, they're added with new root folders for their current location instead of adding and moving them from their current location into the current root folder.

**Describe the solution you'd like**
An option when bulk importing movies to 'Use current root folder pattern' so that the importing behaves like if I had added the movie to the database and then it had downloaded it: folder is created in root folder location and movie file(s) are moved there/renamed.

**Describe alternatives you've considered**
Current method involves bulk importing, moving the imported movie folders/files to another directory, changing their root folders in radarr to the main root folder, then doing a manual import from the missing tab so that the files end up in the correct root location.

**Comment by Qstick** [comment]
Why not just have them in the main root folder to begin with? Have a staging root folder and a main root folder seems like more work

**Comment by fryfrog** [comment]
Sounds like you want a combination of Wanted -> Manual Import and Bulk Import. It isn't a crazy idea and would be useful, often you might find yourself w/ a big folder full of movies you may or may not already have. You don't want to import them like that, but you do want them in your collection.

In the mean time, your best *actual* solution would be to use Filebot to take them from your messy folder and put them into your library folder in nice neat `./Movie Title (Year)/original.file.name.ext` format.

**Comment by bakerboy448** [comment]
No plans at this time.
