### ISSUE TITLE
Magnet Link Import With Movie Title with Apostrophe Error

### ISSUE THREAD

**Issue by afreels1995** [Radarr/Radarr#3727]
**Describe the bug**
Issue where Magnet link will not send to transmission correctly when containing an apostrophe. 
Jackett sends back correct magnet link that works via transmission, but when Radarr adds it to transmission (my download client) it wont work. 

```
Error: Failed to parse magnetlink for movie 'Molly's Game (2017) (1080p BluRay x265 HEVC 10bit AAC 7.1 Tigole) [QxR]': 'magnet:?xt=urn:btih:0F64D88506845DDFA502F3CBB72A171D9A32084A&dn=Molly&#039;s Game (2017) (1080p BluRay x265 HEVC 10bit AAC 7.1 Tigole) [QxR]&tr=udp://tracker.torrent.eu.org:451/announce&tr=udp://tracker.opentrackr.org:1337/announce&tr=udp://tracker.coppersurfer.tk:6969/announce&tr=udp://tracker.zer0day.to:1337/announce&tr=udp://tracker.leechers-paradise.org:6969/announce&tr=udp://coppersurfer.tk:6969/announce': A field-value pair of the magnet link contain more than one equal'.
```

**To Reproduce**
1. Add movie with apostrophe in title

**Desktop (please complete the following information):**
- Docker Jackett 11.655

**Debug Logs**
Turn on debug logs under Settings -> General and wait for the bug to occur again. **Upload the full log file here (or another site and link it). Issues will be closed, if they do not include this!**

```
19-8-29 15:20:23.2|Error|Transmission|Failed to parse magnetlink for movie 'Molly's Game (2017) (1080p BluRay x265 HEVC 10bit AAC 7.1 Tigole) [QxR]': 'magnet:?xt=urn:btih:0F64D88506845DDFA502F3CBB72A171D9A32084A&dn=Molly&#039;s Game (2017) (1080p BluRay x265 HEVC 10bit AAC 7.1 Tigole) [QxR]&tr=udp://tracker.torrent.eu.org:451/announce&tr=udp://tracker.opentrackr.org:1337/announce&tr=udp://tracker.coppersurfer.tk:6969/announce&tr=udp://tracker.zer0day.to:1337/announce&tr=udp://tracker.leechers-paradise.org:6969/announce&tr=udp://coppersurfer.tk:6969/announce'

[v0.2.0.1358] System.FormatException: A field-value pair of the magnet link contain more than one equal'.
  at MonoTorrent.MagnetLink.ParseMagnetLink (System.String url) [0x002b0] in C:\projects\radarr-usby1\src\MonoTorrent\MagnetLink.cs:93 
  at MonoTorrent.MagnetLink..ctor (System.String url) [0x00022] in C:\projects\radarr-usby1\src\MonoTorrent\MagnetLink.cs:32 
  at NzbDrone.Core.Download.TorrentClientBase`1[TSettings].DownloadFromMagnetUrl (NzbDrone.Core.Parser.Model.RemoteMovie remoteMovie, System.String magnetUrl) [0x00004] in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\TorrentClientBase.cs:203 

19-8-29 15:20:23.2|Info|DownloadService|Report sent to Transmisison-FreelsServer. Molly's Game (2017) (1080p BluRay x265 HEVC 10bit AAC 7.1 Tigole) [QxR]
```

**Comment by dkage** [comment]
I got the same issue with Radarr on Windows trying to download "Howl's Moving Castle". Got the error 

`Failed to parse magnetlink for movie 'Howl's Moving Castle (2004) [BluRay] [1080p] [YTS] [YIFY]': 'magnet:?xt=urn:btih:7C7A5296A370A5D8067C712DA5146BF5A868E846&dn=Howl&#039;s Moving Castle (2004) [BluRay] [1080p] [YTS] [YIFY]&tr=udp://tracker.coppersurfer.tk:6969/announce&tr=udp://9.rarbg.com:2710/announce&tr=udp://p4p.arenabg.com:1337&tr=udp://tracker.leechers-paradise.org:6969&tr=udp://tracker.internetwarriors.net:1337&tr=udp://tracker.opentrackr.org:1337/announce&tr=udp://tracker.zer0day.to:1337/announce&tr=udp://tracker.leechers-paradise.org:6969/announce&tr=udp://coppersurfer.tk:6969/announce': A field-value pair of the magnet link contain more than one equal'.`

Also using Jackett as indexer.

**Comment by fryfrog** [comment]
I hope this gets corrected, but I don't think I've ever seen anyone w/ this sort of issue from qBittorrent, Deluge or rTorrent. I <3 Transmission, but it just isn't the best for automation.

**Comment by jackmeat** [comment]
I have this exact same issue with 1337x as the indexer through jackett v0.12.1732.0 in radarr Version
    0.2.0.1450. It seems the movie needs to have a quote to trigger this problem, as I tried both Jacob's Ladder and The Warrior's Way, and both turned back Failed to parse magnetlink for movie 'The Warrior's Way (2010) 720p BluRay [Dual Audio]-[Hindi + English] - ESubs 800MB - MovCr': 'magnet:?xt=urn:btih:C630CCBE26AD5F5AF4D33E8203B75DE352BD6666&dn=The+Warrior&#039;s+Way+(2010)+720p+BluRay+[Dual+Audio]-[Hindi+++English]+-+ESubs+800MB+-+MovCr&tr=udp://tracker.leechers-paradise.org:6969/announce&tr=udp://tracker.internetwarriors.net:1337/announce&tr=udp://tracker.opentrackr.org:1337/announce&tr=udp://tracker.coppersurfer.tk:6969/announce&tr=udp://tracker.pirateparty.gr:6969/announce&tr=udp://9.rarbg.to:2730/announce&tr=udp://9.rarbg.me:2720/announce&tr=udp://tracker.tiny-vps.com:6969/announce&tr=udp://tracker.torrent.eu.org:451/announce&tr=udp://tracker.open-internet.nl:6969/announce&tr=udp://open.stealth.si:80/announce&tr=udp://explodie.org:6969/announce&tr=udp://denis.stalker.upeer.me:6969/announce&tr=udp://tracker.zer0day.to:1337/announce&tr=udp://tracker.leechers-paradise.org:6969/announce&tr=udp://coppersurfer.tk:6969/announce': A field-value pair of the magnet link contain more than one equal'.

**Comment by dportuesi** [comment]
+1 with jackmeat, also getting this error when i try to download Howl's moving castle

**Comment by Jeff254** [comment]
Am also getting a similar error with Molly's Game
