### ISSUE TITLE
Radarr aphrodite fail to add Indexer 

### ISSUE THREAD

**Issue by arlllk** [Radarr/Radarr#3731]
**Description:**
When I try to add a Indexer in Radarr it always fail, I have try with jackett and try to add RARBG, both fail in the same way

**Radarr Version:**
2.0.0.1422
**Mono Version:**
6.0.0
**Debug Logs:**
https://pastebin.com/B9wcNzci

**Comment by Qstick** [comment]
Thanks for reporting

**Comment by HLFH** [comment]
Same issue with 1434 version of Radarr Aphrodite with TorrentLeech.
