### ISSUE TITLE
Metadata deleted when downloading movie again

### ISSUE THREAD

**Issue by andyd0** [Radarr/Radarr#3733]
**Describe the bug**
Movies that already exist with metadata but are selected to be downloaded again (say for a different quality profile) gets metadata wiped out - meaning any images and other files are gone after redownload

**To Reproduce**
1. Download a movie
2. Add metadata
3. Download movie again

**Expected behavior**
Don't delete metadata 

**Desktop (please complete the following information):**
 - OS: Linux / Docker container
 - Mono Version: 5.20.1.34 (tarball Tue Jul 16 22:52:32 UTC 2019)
 - Version: 0.2.0.1358

**Comment by Qstick** [comment]
Same as 3209
