### ISSUE TITLE
Column headers don't match up with data in queue

### ISSUE THREAD

**Issue by tehniemer** [Radarr/Radarr#3735]
**Describe the bug**
The populated fields don't match up with the header of the column. Oddly this seems to only affect the queue, history and blacklist show up correctly. 

**To Reproduce**
1. Go to activity queue
2. have items in queue
3. See error

**Expected behavior**
Columns and populated data match up.

**Screenshots**
Queue (incorrect)
![Image 1567288870](https://user-images.githubusercontent.com/11021632/64069644-3a88ce80-cc13-11e9-9207-ccf94cccdb10.png)

History (correct)
![Image 1567289994](https://user-images.githubusercontent.com/11021632/64070393-1e415d80-cc24-11e9-95b1-103d47ec223e.png)

**Desktop (please complete the following information):**
 - OS: Docker (linuxio container)
 - Mono Version: 5.20.1.34
 - Version: 2.0.0.1427
 - Browser: Firefox 68.0.2

**Debug Logs**
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/3562962/radarr.debug.txt)

**Comment by tehniemer** [comment]
@Qstick why was this closed?

**Comment by Qstick** [comment]
We don't track Aphrodite issues as open issues given its so early and there are so many. I'll change label to "done Aphrodite" when it gets fixed
