### ISSUE TITLE
File quality does not match quality of the grabbed release

### ISSUE THREAD

**Issue by tehniemer** [Radarr/Radarr#3736]
**Describe the bug**
File quality is listed correctly in download queue but doesn't import because of the error "File quality does not match quality of the grabbed release" when a manual import is initiated the quality listed in the manual import dialog is different. This is seemingly only affecting downloads marked as ```Bluray-1080p```, ```Bluray-720p``` are importing normally.

**To Reproduce**
1. Send movie to downloader
2. Movie completes and sent back to Radarr
3. See error

**Expected behavior**
The movie is correctly identified and imported

**Screenshots**
![Image 1567288156](https://user-images.githubusercontent.com/11021632/64069560-a0745680-cc11-11e9-9363-a6b9957701d1.png)

![Image 1567288149](https://user-images.githubusercontent.com/11021632/64069563-aec27280-cc11-11e9-858b-2c5cf864b921.png)

**Desktop (please complete the following information):**
 - OS: Docker (linuxio container)
 - Mono Version: 5.20.1.34
 - Version: 2.0.0.1427

**Debug Logs**
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/3562963/radarr.debug.txt)

**Comment by tehniemer** [comment]
@Qstick why was this closed? Is there a different place to report Aphrodite issues?

**Comment by Qstick** [comment]
No, they are just tracked by label for now. I'll look into this, seems a bit strange, I suspect it is not looking at folder name for some reason and just relying on mediainfo resolution

**Comment by KnottyDyes** [comment]
Here is the sequence that's happening during my parsing phase, resulting in this error:
`19-9-7 13:23:12.7|Debug|Parser|Parsing string 'Waterworld.1995.1080p.BluRay.x264.1.AC3-BUYMORE-Obfuscated'
19-9-7 13:23:12.7|Debug|Parser|Movie Parsed. Waterworld - 1995 
19-9-7 13:23:12.7|Debug|ParsingService|Language(s) parsed: 
19-9-7 13:23:12.7|Debug|QualityParser|Trying to parse quality for A Movie.1995.1080p.BluRay.x264.1.AC3-BUYMORE-Obfuscated
19-9-7 13:23:12.7|Debug|ParsingService|Quality parsed: Bluray-1080p v1 (None)
19-9-7 13:23:12.7|Debug|Parser|Parsing string 'Waterworld.1995.1080p.BluRay.x264.1.AC3-BUYMORE-Obfuscated'
19-9-7 13:23:12.7|Debug|Parser|Movie Parsed. Waterworld - 1995 
19-9-7 13:23:12.7|Debug|ImportDecisionMaker|Analyzing 1/1 files.
19-9-7 13:23:12.7|Debug|Parser|Parsing string 'Waterworld (1995).mp4'
19-9-7 13:23:12.7|Debug|Parser|Movie Parsed. Waterworld - 1995 
19-9-7 13:23:12.7|Debug|VideoFileInfoReader|Getting media info from /downloads/complete/movies/Waterworld (1995)/Waterworld (1995).mp4
19-9-7 13:23:12.8|Debug|ParsingService|Language(s) parsed: 
19-9-7 13:23:12.8|Debug|QualityParser|Trying to parse quality for A Movie (1995)
19-9-7 13:23:12.8|Debug|ParsingService|Quality parsed: Unknown v1 (None)
19-9-7 13:23:12.8|Debug|ImportDecisionMaker|Size: 4296731407
19-9-7 13:23:12.8|Debug|GrabbedReleaseQualitySpecification|Quality for grabbed release (Bluray-1080p v1 (None)) does not match the quality of the file (Unknown v1 (None))
`
I see two weird things happening here.  First, it is parsing the quality of the reformatted name, which doesn't exist anymore, and therefore fails.  Second, it keeps subbing in 'A Movie' as the title on pretty much every movie it parses.

**Comment by Qstick** [comment]
Thanks Let me try and reproduce.

**Comment by KnottyDyes** [comment]
@DaveidWeba, my issue was I didn't have the obfuscation script running after download completion.  Make sure your scripts directory is set correctly, and set the deobfuscate.py script to run after download complete.

**Comment by DaveidWeba** [comment]
You probably can't tell because I blurred the filename, but both the directory and the filename are perfectly named with the title of the movie, year, and quality. All of them come in as HDTV on Radar v3 though. I'm gonna try downgrading soon because it's been a chore manually importing everything.

**Comment by Qstick** [comment]
Latest update fixes some of that. Also it's about what mediainfo says vs the name. If they contradict each other it will not import.

**Comment by tehniemer** [comment]
@Qstick So far so good today.

**Comment by HeroXx** [comment]
Also getting this on Aphrodite :(

**Comment by bakerboy448** [comment]
@HeroXx 

This issue was fixed and closed years ago.

Also Aphrodite is dead, upgrade to nightly.

Lastly

Support Requests -> [Reddit](https://www.reddit.com/r/radarr/) or [Discord](https://discord.gg/GS7jgXv)
