### ISSUE TITLE
Update NLog from BETA / RC to official version

### ISSUE THREAD

**Issue by snakefoot** [Radarr/Radarr#3737]
Update from 4.5.0-rc06:

https://github.com/Radarr/Radarr/blob/df068e9f0a93a43ecfc658f84b5f577475b16858/src/NzbDrone.Core/packages.config#L8

Suggest NLog 4.5.11 (or newer): https://www.nuget.org/packages/NLog/

**Comment by Qstick** [comment]
This is already done in v2/Aphrodite. Not sure if we will bump in V1
