### ISSUE TITLE
Fetaure to rename / create folders can't be disabled

### ISSUE THREAD

**Issue by ciberboy** [Radarr/Radarr#3738]
**Describe the bug**
Existing option to disable the rename of movies, can't be disabled. I currently have all rename option disabled, and Radarr keeps renaming the folders:
![image](https://user-images.githubusercontent.com/1254472/64109220-d3842a80-cd76-11e9-8c08-fb218db13392.png)

**To Reproduce**
1. Disable all rename options
2. Add a new movie or choose a file to be downloaded
3. After download is complete, confirm that there's an original folder with downloaded file and another one with the "link" to the downloaded file, with the renamed name

**Expected behavior**
With all rename / create folders options disabled, my expectation is that downloaded files aren't moved or renamed

**Screenshots**
![image](https://user-images.githubusercontent.com/1254472/64109014-50fb6b00-cd76-11e9-88ad-f4a10b389e0a.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Mono Version: 5.10.1.20 (tarball Thu Mar 29 10:48:35 UTC 2018)
 - Browser and Version Chrome
 - Version 0.2.0.1358

**Debug Logs**
[radarr.txt](https://github.com/Radarr/Radarr/files/3565676/radarr.txt)

**Comment by ciberboy** [comment]
👍

**Comment by fryfrog** [comment]
This is how it works, don't download to your library folder and don't library folder in your download folder.
