### ISSUE TITLE
High/Excessive CPU Usage

### ISSUE THREAD

**Issue by kennyparsons** [Radarr/Radarr#3739]
**Describe the bug**
A ridiculous amount of CPU usage at random times.

**To Reproduce**
I cannot reproduce, I can only notice it. There seems to be no patterns (no high usage when processing new movies or downloads, etc.)

**Expected behavior**
Not this much CPU usage. 

**Screenshots**
Screenshots on imgur: https://imgur.com/a/vPgEnio

**Desktop (please complete the following information):**
 - OS: Debian
 - Version 0.2.0.1358

**Debug Logs**
[radarr.0.txt](https://github.com/Radarr/Radarr/files/3566672/radarr.0.txt)
[radarr.txt](https://github.com/Radarr/Radarr/files/3566673/radarr.txt)

**Comment by majora2007** [comment]
This is normal behavior for larger libraries and a disk scan (aka scanning library for changes) occurs. How large is your library?

**Comment by kennyparsons** [comment]
~800 items. 

How can I put a cpu limit on the container? I used the -cpus flag but it did nothing. 

- Kenny Parsons

**Comment by fryfrog** [comment]
I use systemd, looks something like:

```
# /etc/systemd/system/bazarr.service.d/override.conf
[Service]
CPUAccounting=true
CPUQuota=50%
```

You'll need to dig into your container software's documentation to get it right. Google "docker cpu limit" maybe.

**Comment by fryfrog** [comment]
Turn logging up to Trace and when you're seeing high CPU usage, see what is going on.
