### ISSUE TITLE
Discovery (Discover New Movies) is not updating

### ISSUE THREAD

**Issue by charlesmanser** [Radarr/Radarr#3740]
The API calls to https://api.radarr.video/v2/discovery/upcoming only list three upcoming movies.

The other API calls for discovery also appear stale, for example, https://api.radarr.video/v2/discovery/popular

**Comment by fryfrog** [comment]
See if you're on `nightly` or `develop`, then switch to the *opposite* one and save. Check the results, are they different? Your branch determines which of the stable or testing servers you hit, so might be different. After you test, flip back to the right branch for you and report here.

**Comment by seven4ka** [comment]
I'm having a similar issue.
imdb lists not working, movie search (add) as well as RefreshMovieService are not working at all and will timeout.

Tried both nighlty + develop


> RefreshMovieService | Couldn't refresh info for [2001: A Space Odyssey (1968)][tt0062622, 62]: The operation has timed out.: 'https://api.themoviedb.org/3/movie/62?api_key=1a7373301961d03f97f853a876dd1212&append_to_response=alternative_titles%2Crelease_dates%2Cvideos&language=EN'
> -- | --




> Request Failed: The operation has timed out.: 'https://api.themoviedb.org/3/search/movie?api_key=1a7373301961d03f97f853a876dd1212&query=police%2Bstory&year=&include_adult=False'

> System.Net.WebException: The operation has timed out.: 'https://api.themoviedb.org/3/search/movie?api_key=1a7373301961d03f97f853a876dd1212&query=police%2Bstory&year=&include_adult=False' ---> System.Net.WebException: The operation has timed out.
>   at System.Net.HttpWebRequest.RunWithTimeoutWorker[T] (System.Threading.Tasks.Task`1[TResult] workerTask, System.Int32 timeout, System.Action abort, System.Func`1[TResult] aborted, System.Threading.CancellationTokenSource cts) [0x000f8] in <f62d843bc8f04cc48580b577d5f0a74e>:0 
>   at System.Net.HttpWebRequest.GetResponse () [0x00016] in <f62d843bc8f04cc48580b577d5f0a74e>:0 
>   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse (NzbDrone.Common.Http.HttpRequest request, System.Net.CookieContainer cookies) [0x0011b] in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:82 
>    --- End of inner exception stack trace ---
>   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse (NzbDrone.Common.Http.HttpRequest request, System.Net.CookieContainer cookies) [0x001cf] in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:113 
>   at NzbDrone.Common.Http.Dispatchers.FallbackHttpDispatcher.GetResponse (NzbDrone.Common.Http.HttpRequest request, System.Net.CookieContainer cookies) [0x0009d] in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\Dispatchers\FallbackHttpDispatcher.cs:47 
>   at NzbDrone.Common.Http.HttpClient.ExecuteRequest (NzbDrone.Common.Http.HttpRequest request, System.Net.CookieContainer cookieContainer) [0x0007e] in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:121 
>   at NzbDrone.Common.Http.HttpClient.Execute (NzbDrone.Common.Http.HttpRequest request) [0x00008] in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:57 
>   at NzbDrone.Common.Http.HttpClient.Get (NzbDrone.Common.Http.HttpRequest request) [0x00007] in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:267 
>   at NzbDrone.Common.Http.HttpClient.Get[T] (NzbDrone.Common.Http.HttpRequest request) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\HttpClient.cs:272 
>   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewMovie (System.String title) [0x00275] in C:\projects\radarr-usby1\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:509 
>   at NzbDrone.Api.Movies.MovieLookupModule.Search () [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Api\Movies\MovieLookupModule.cs:48 
>   at NzbDrone.Api.Movies.MovieLookupModule.<.ctor>b__2_0 (System.Object x) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Api\Movies\MovieLookupModule.cs:22 
>   at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)
>   at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, System.Threading.CancellationToken context) [0x00049] in <63c44d6f8d7e4f339a987bf9eb94d931>:0
>

**Comment by reloxx13** [comment]
is this fixed? im on nighty and its not updating

0.2.0.1448 on windows
