### ISSUE TITLE
Feature Request: Unmonitor movie once downloaded 

### ISSUE THREAD

**Issue by blindguy** [Radarr/Radarr#3743]
I keep having issues were a 'new' lesser quality of a movie replaces a fine HQ version. 
For Instance, today I lost a 15GB MKV version of a move for a wonderful 450meg AVI version.

**Describe the solution you'd like**
Can there be a flag so that once a movie is DL'ed it will not DL'it again?
I understand all about the quality feature of Radarr but sometimes I want to grab a special or custom version and do not want it upgraded no matter what the automation thinks.

I understand that you think my quality setting need to be updated and that I need to modify other things but my quality setting work fine for the first download it is just the second and additional downloads that I want to stop.

**Comment by fryfrog** [comment]
This generally indicates a mistake in your setup that should be fixed. Also, you should turn on the recycle bin! :)

**Comment by Qstick** [comment]
Agree with fryfrog on setup, also Aphrodite will have an option to never upgrade in quality profiles
