### ISSUE TITLE
Email Notification filters

### ISSUE THREAD

**Issue by zaggash** [Radarr/Radarr#3745]
**Describe the bug**
I added a tag on a movie in the "Tags" filed.
Then I created an email notification andd set the same tag in "Filter Movies Tags"
Whenever someting happen on that movie, there is no notifications even tho I checked "on Download", "On Upgrade", ...

I tested the mail connection and it works fine.

**Expected behavior**
I expected the mail notification to be sent when some actions are performed on the movies with the tag I put.

**Desktop (please complete the following information):**
OS: Linux
Version
0.2.0.1358
Mono Version
5.20.1.34 (tarball Tue Jul 16 22:52:32 UTC 2019)

**Debug Logs**
Waiting on debug logs, I have another movie that will be updated, I should receive a notification soon.

**Comment by fryfrog** [comment]
To be clear, a movie w/ the tag downloaded or got upgraded, right?

**Comment by zaggash** [comment]
both : none of the opt in function is working.

**Comment by fryfrog** [comment]
Turn logging up to Trace and capture a big chunk around when the email should be sent, put it in a pastebin.

And in the mean time, you might find Tautulli better at this sort of thing. Its whole purpose is notifications and news letter and data.

**Comment by zaggash** [comment]
I have the Trace output.
There is data in it I rather prefer not to share publicly !

I see the 2 others notification services activated : Plex Update and Slack but there is nothing about email.
Not even, a single mention of it.

Here is an extract of the interesting parts.
We can see the `NotificationService` lines and action below except for the latest one, there is no action below `NotificationService|Notification and movie have one or more matching tags.`
``` 
19-9-5 10:43:51.0|Trace|EventAggregator|MovieImportedEvent <- MovieModule
19-9-5 10:43:51.0|Trace|EventAggregator|MovieImportedEvent -> CalendarModule
19-9-5 10:43:51.1|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId)

19-9-5 10:43:51.1|Trace|EventAggregator|MovieImportedEvent <- CalendarModule
19-9-5 10:43:51.1|Trace|EventAggregator|Publishing MovieDownloadedEvent
19-9-5 10:43:51.1|Trace|EventAggregator|MovieDownloadedEvent -> NotificationService
19-9-5 10:43:51.1|Trace|Http|Req: 1352 [GET] /api/extrafile?movieId=76&sort_by=relativePath&order=asc
19-9-5 10:43:51.2|Debug|NotificationService|No tags set for this notification.
19-9-5 10:43:51.2|Debug|PlexServerService|Sending Update Request to Plex Server

[---]

19-9-5 10:43:52.4|Trace|PlexServerProxy|No response body returned, no error detected
19-9-5 10:43:52.4|Debug|NotificationService|No tags set for this notification.
19-9-5 10:43:52.4|Trace|HttpClient|Req: [POST] https://hooks.slack.com/services/[...]

[---]

19-9-5 10:43:52.5|Trace|HttpClient|Res: [POST] https://hooks.slack.com/services/[...]: 200.OK (154 ms)
19-9-5 10:43:52.5|Debug|NotificationService|Notification and movie have one or more matching tags.
19-9-5 10:43:53.2|Trace|EventAggregator|MovieDownloadedEvent <- NotificationService
19-9-5 10:43:53.2|Trace|EventAggregator|MovieDownloadedEvent -> MovieCutoffModule
19-9-5 10:43:53.2|Trace|EventAggregator|MovieDownloadedEvent <- MovieCutoffModule
19-9-5 10:43:53.2|Trace|EventAggregator|MovieDownloadedEvent -> MovieMissingModule
19-9-5 10:43:53.2|Trace|EventAggregator|MovieDownloadedEvent <- MovieMissingModule
19-9-5 10:43:53.2|Trace|EventAggregator|Publishing DownloadCompletedEvent
19-9-5 10:43:53.2|Trace|EventAggregator|DownloadCompletedEvent -> DownloadEventHub
19-9-5 10:43:53.2|Trace|ConfigService|Using default config value for 'removecompleteddownloads' defaultValue:'False'
19-9-5 10:43:53.2|Trace|EventAggregator|DownloadCompletedEvent <- DownloadEventHub
19-9-5 10:43:53.2|Trace|ConfigService|Using default config value for 'removecompleteddownloads' defaultValue:'False'
19-9-5 10:43:53.2|Trace|EventAggregator|Publishing TrackedDownloadRefreshedEvent
19-9-5 10:43:53.2|Trace|EventAggregator|TrackedDownloadRefreshedEvent -> QueueService
```
