### ISSUE TITLE
Movie Snatch title english with other language

### ISSUE THREAD

**Issue by valantislevas** [Radarr/Radarr#3747]
Hello its possible somehow snatch Movie with english title but also another language

Greek trackers uses Greek Language and also English Language on Title..
like the image below
Its possible somehow make the Radarr download the file base on his english title and ignore the other or something/...?

I see that couchpotato can scan the movies in english and ignore the greek or foreign language text and make the snatch..
thanks and this will be great.
my radarr version:

Radarr Ver. 0.2.0.1358
develop

![download](https://user-images.githubusercontent.com/5359581/64438250-75d24400-d0d0-11e9-885c-7716753a3572.png)

**Comment by fryfrog** [comment]
This seems similar to #3748, though this example doesn't have the easy to key off of `AKA`.

**Comment by bakerboy448** [comment]
Closing
v0.2 is no longer being actively developed.

If this is still an issue/request on recent v3 builds, please open a new issue.

v3 has significant language improvements
