### ISSUE TITLE
Unable to import movie with 'AKA' in the title

### ISSUE THREAD

**Issue by SF4L** [Radarr/Radarr#3748]
**Describe the bug**
Movies with 'AKA' in the title/filename do not get imported into Radarr after being downloaded.

I am able to add a movie (The Taste of Money 2012 -- https://www.imdb.com/title/tt2106670/) and download it from the indexer. The torrent client successfully downloads it, however cannot be imported and automatically added to Radarr. It does not appear in the 'Activity' tab, although in 'History' for the movie I can see it was downloaded.

**To Reproduce**
1. Add The Taste of Money (2012) to Radarr
2. Download the release Do-nui.mat.AKA.The.Taste.of.Money.2012.576p.BluRay.x264-HANDJOB from PTP
3. Observe that it does download, but is unable to be imported into Radarr. It must be manually imported, even with Lenient Mapping.

**Expected behavior**
I expected the release to automatically be imported into Radarr after downloading the torrent file.

**Screenshots**
![image](https://user-images.githubusercontent.com/36459489/64445701-1448b000-d0a5-11e9-80cd-443d05c952ac.png)
![image](https://user-images.githubusercontent.com/36459489/64445714-1b6fbe00-d0a5-11e9-821b-a156eda9ebbe.png)
![image](https://user-images.githubusercontent.com/36459489/64445733-21659f00-d0a5-11e9-89a9-439b0b72c2a9.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Mono Version: 5.18.1.0 (tarball Fri Mar 15 20:45:47 UTC 2019)
 - Version: 0.2.0.1293

**Debug Logs**
Trace logs: https://pastebin.com/LdpGRgG8

[AB#879](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/879)

**Comment by fryfrog** [comment]
Thanks!

**Comment by bnflix** [comment]
It seems like this and other related name-matching issues shouldn't even exist considering that Radarr knows the filename and the movie details when it initiates the download.

**Comment by fryfrog** [comment]
The thing that decides on the download is one black box, it has all the indexer data and makes the choice and sends the download to the download client. The thing that watches the download client is another black box, all it has to look at is the data from the download client. Don't forget that you can queue things up in your download client yourself and Sonarr/Radarr will happily ingest them if they're known. This just be how it be, right now.

If you're a .NET developer, I know making that has been a long time interest in both Sonarr and Radarr. They'd be happy of some help working on it.

**Comment by bnflix** [comment]
> If you're a .NET developer, I know making that has been a long time interest in both Sonarr and Radarr. They'd be happy of some help working on it.

Yeah I took a look, what's up with no comments anywhere?

Anyway, could you throw the filename in the AlternativeTitles table?

**Comment by fryfrog** [comment]
I don't think that solves it, alternate titles come from TMDB. The problem is that the movie effectively has *two* titles. I think it needs to know to split at the `AKA` and look at both or either.

**Comment by bnflix** [comment]
This issue goes beyond the AKA problem. Another related issue is a non-English title that has accents, umlauts, and other diacritics, but the release uses an ASCII title. For example the file Hundraaringen.Som.Klev.Ut.Genom.Fonstret.Och.Forsvann.2013.720p.BluRay.DD5.1.x264-TayTO.mkv when the movie entry on TMDB is Hundraåringen som klev ut genom fönstret och försvann.2013.720p.BluRay.DD5.1.x264-DON. 

Another issue is when the filename does not have a year, even though the movie matches fine and there is only one movie with that title.

**Comment by SF4L** [comment]
When it's missing the year entirely, it won't even let you download it with 'force download' so you can later manually import it. Gotta fully manually do that one.

In addition to no years, another type of filename it has issues matching is when the movie year appears twice accidentally (for example, the release: Lucky.Day.2019.2019.720p.AMZN.WEB-DL.DDP5.1.H.264-NTG had to be manually imported).

**Comment by 0aeonnoea0** [comment]
Have set up an initial PR (#4453) that allows the parser to pick up the additional names specified by the AKA. Specifically not going to try to address the accent or missing year issues described above as they're separate issues themselves imo - only aiming to allow automatic import of titles with AKA in them.
