### ISSUE TITLE
Disk / Volume Utilisation at 100% when Radarr running

### ISSUE THREAD

**Issue by netpanic** [Radarr/Radarr#3754]
I am having an issue where when Radarr is running my disk / volume utilisation is at 100% and the whole system slows down and becomes unresponsive. I also noticed that the RAM usage is very high, I then limited it to 2GB in docker and restarted the container and it has just instantly maxed out the 2GB. 

When I turn the container off the Disk / Volume utilisation drops back down very low, as soon as I turn it back on it goes back up to 100% and stays there.

I have attached a photo showing the processing being run on the container and also one showing the graph shoot up when the container starts.

I have also attached my logs for reference.

I am running it on a Synology DS918+ NAS as a docker image. 

Radarr Version: Latest (will confirm later)
Docker Version: 18.09.0-0505

Logs - https://filebin.net/aef6qxov9xu2r8k8/radarr.html?t=y4qdx4k9

**Comment by fryfrog** [comment]
Turn logging up to trace and see what it is doing. It does scan the file system once or twice a day, so it could just be doing that. Hop on Discord for some support.
