### ISSUE TITLE
Don’t open on macOS Catalina 

### ISSUE THREAD

**Issue by osnipassos** [Radarr/Radarr#3755]
**Describe the bug**
Don’t open on macOS Catalina GM

PS: I tried to allow "undefined developers”, but is not that

**To Reproduce**
1. Go to ‘Applications'
2. Click on ‘Radarr'
3. See error

**Expected behavior**
Open :)

**Screenshots**
<img width="1440" alt="Screen Shot 2019-09-11 at 13 05 55" src="https://user-images.githubusercontent.com/711222/64714504-2061b280-d495-11e9-8a9d-24bdea4390d1.png">

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Mono Version: -
 - Browser and Version -

**Debug Logs**
-

**Comment by galli-leo** [comment]
You need to right click then click open

**Comment by osnipassos** [comment]
I tried but didn’t work.

**Comment by MozkaTeacher** [comment]
It's because radarr is a 32 bit app and macOS Catalina only run 64 bit app

**Comment by fryfrog** [comment]
Radarr is a .NET app, so that might mean your *Mono* needs to be 64bit?

**Comment by galli-leo** [comment]
@osnipassos Sorry for the late reply, but did you try extracting the zip file with the built in Archive Utility?

**Comment by galli-leo** [comment]
@MozkaTeacher Radarr definitely works on Catalina, so that’s not the reason why.

**Comment by osnipassos** [comment]
> @osnipassos Sorry for the late reply, but did you try extracting the zip file with the built in Archive Utility?

I download the Radarr.develop.0.2.0.1358.osx-app.zip, unzip, put into applications folder and didn't work.
I have a clean install of Catalina right now and the same problem continues.

I've tried with Sonnar app and the same problem occurs. I think this help you.

**Comment by gabemunro** [comment]
I ran into the same issue, but running it from the command line (or as a launch agent) works, but there's still the issue with not being able to move files without granting sh full disk access.

**Comment by matthewtroup1983** [comment]
So has this been solved yet?

**Comment by schinsue** [comment]
@osnipassos I had the same problem, it seems that the "Archive Utility" was the problem when extracting. I extracted with "The Unarchiver" and now it opens correctly.

**Comment by SageBrushes** [comment]
chmod +x /Users/USERNAME/Downloads/Radarr.app/Contents/MacOS/Radarr should fix that error

**Comment by osnipassos** [comment]
> @osnipassos I had the same problem, it seems that the "Archive Utility" was the problem when extracting. I extracted with "The Unarchiver" and now it opens correctly.
> 
> Note: I'm currently on Catalina 10.15 (19A583)

Thanks. Works like charm with your tip.

**Comment by darthdooty** [comment]
> @osnipassos I had the same problem, it seems that the "Archive Utility" was the problem when extracting. I extracted with "The Unarchiver" and now it opens correctly.
> 
> Note: I'm currently on Catalina 10.15 (19A583)
I just bought a new Mac and I have been working on this issue for a few hours now.  
Thanks, this was my issue.
Really appreciate it.

**Comment by houdini3009** [comment]
Sonarr fixed this properly. Is Radarr going to implement the same fix? The **chmod** command recommended in here is a bad practice from a security perspective. https://github.com/Radarr/Radarr/issues/4753

**Comment by ta264** [comment]
It's fixed in v3.
