### ISSUE TITLE
Unable to find exact quality for UNKNOWN and R2160P. Using HDTV-2160p as fallback

### ISSUE THREAD

**Issue by LooseSeal2** [Radarr/Radarr#3758]
**Description:**
Unable to find exact quality for UNKNOWN and R2160P. Using HDTV-2160p as fallback
Unable to find exact quality for UNKNOWN and R1080P. Using HDTV-1080p as fallback

I'm getting this error after every download with Aphrodite. I have to manually set the quality and language. I did a clean install with no existing appdata.

**Radarr Version:**
2.0.0.2051
**Mono Version:**
5.20.1.34
**Debug Logs:**
```
[v2.0.0.2051] System.InvalidOperationException: Sequence contains more than one matching element
  at System.Linq.Enumerable.SingleOrDefault[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x0004a] in <798dd06330af4ca3886d7d2be5573af7>:0
  at NzbDrone.Core.Qualities.QualityFinder.FindBySourceAndResolution (NzbDrone.Core.CustomFormats.Source source, NzbDrone.Core.CustomFormats.Resolution resolution) [0x00014] in <3f38b038195c468ab2d4d01fcba79332>:0
  at NzbDrone.Core.MediaFiles.MovieImport.Aggregation.Aggregators.AggregateQuality.Aggregate (NzbDrone.Core.Parser.Model.LocalMovie localMovie, System.Boolean otherFiles) [0x0014b] in <3f38b038195c468ab2d4d01fcba79332>:0
  at NzbDrone.Core.MediaFiles.MovieImport.Aggregation.AggregationService.Augment (NzbDrone.Core.Parser.Model.LocalMovie localMovie, System.Boolean otherFiles) [0x000a6] in <3f38b038195c468ab2d4d01fcba79332>:0

[Warn] MediaInfoFormatter: Unable to format audio channels using 'AudioChannelPositions', with a value of: '3/2/0.2.1'

[v2.0.0.2051] System.FormatException: Input string was not in a correct format.
  at System.Number.ThrowOverflowOrFormatException (System.Boolean overflow, System.String overflowResourceKey) [0x0001a] in <254335e8c4aa42e3923a8ba0d5ce8650>:0
  at System.Number.StringToNumber (System.ReadOnlySpan`1[T] value, System.Globalization.NumberStyles styles, System.Number+NumberBuffer& number, System.Globalization.NumberFormatInfo info, System.Boolean parseDecimal) [0x00045] in <254335e8c4aa42e3923a8ba0d5ce8650>:0
  at System.Number.ParseDecimal (System.ReadOnlySpan`1[T] value, System.Globalization.NumberStyles styles, System.Globalization.NumberFormatInfo info) [0x00010] in <254335e8c4aa42e3923a8ba0d5ce8650>:0
  at System.Decimal.Parse (System.String s, System.IFormatProvider provider) [0x00018] in <254335e8c4aa42e3923a8ba0d5ce8650>:0
  at NzbDrone.Core.MediaFiles.MediaInfo.MediaInfoFormatter+<>c.<FormatAudioChannelsFromAudioChannelPositions>b__6_1 (System.String s) [0x00006] in <3f38b038195c468ab2d4d01fcba79332>:0
  at (wrapper delegate-invoke) System.Func`2[System.String,System.Decimal].invoke_TResult_T(string)
  at System.Linq.Enumerable.Sum[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] selector) [0x00034] in <798dd06330af4ca3886d7d2be5573af7>:0
  at NzbDrone.Core.MediaFiles.MediaInfo.MediaInfoFormatter.FormatAudioChannelsFromAudioChannelPositions (NzbDrone.Core.MediaFiles.MediaInfo.MediaInfoModel mediaInfo) [0x000d0] in <3f38b038195c468ab2d4d01fcba79332>:0

[Warn] MediaInfoFormatter: Unable to format audio channels using 'AudioChannelPositions', with a value of: '3/2/0.2.1'
```

**Comment by LooseSeal2** [comment]
In the activity queue it shows the correct quality but it fails to import and when manually importing it falls back.

There seems to be a .Single() call instead of a First () as it complains about more than 1 element in the sequence.

**Comment by LooseSeal2** [comment]
Also https://radarr.aeonlucid.com/v1/update/aphrodite/changes?os=linux is not being updated with the latest changes

**Comment by LooseSeal2** [comment]
@Qstick please fix the auto import and the release feed asap as radarr Aphrodite has been unusable for days.

**Comment by LooseSeal2** [comment]
Is anyone else having this problem?

This bug is causing me to babysit radarr and manually importing is becoming tedious. I have a PR that will probably fix this issue.

**Comment by chrisallen** [comment]
I am seeing this issue myself. The same thing will happen if you rename the file on disk and then refresh the movie, It will detect it as HDTV 1080p, even if it has `bluray.1080p` in the filename.

**Comment by Nixon506E** [comment]
Same issue here, been having it since the Custom Quality PR was merged in, I also see a lot of messages in the log where no Custom Quality was found so it "falls back" to the default Qualities

**Comment by Qstick** [comment]
Can anyone check if this is still happening in build 2.0.0.2070?

**Comment by Nixon506E** [comment]
It is, just updated to 2.0.0.2070 and still showing the same errors in the logs

**Comment by Qstick** [comment]
Can you post a trace log?

**Comment by Nixon506E** [comment]
[radarr.trace.txt](https://github.com/Radarr/Radarr/files/3647668/radarr.trace.txt)

**Comment by Nixon506E** [comment]
More specifically this is the failed parsing section:

`19-9-24 10:23:25.0|Trace|ConfigService|Using default config value for 'parsingleniency' defaultValue:'Strict'
19-9-24 10:23:25.0|Debug|Parser|Parsing string 'The.Shining.1980.2160p.UHD.BluRay.Remux.HDR.HEVC.DTS-HD.MA.5.1-PmP.mkv'
19-9-24 10:23:25.0|Trace|Parser|^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(1(8|9)|20)\d{2}(?!p|i|(1(8|9)|20)\d{2}|\]|\W(1(8|9)|20)\d{2})))+(\W+|_|$)(?!\\)
19-9-24 10:23:25.0|Debug|Parser|Movie Parsed. The Shining - 1980 
19-9-24 10:23:25.0|Debug|ParsingService|Language(s) parsed: 
19-9-24 10:23:25.0|Debug|QualityParser|Trying to parse quality for The.Shining.1980.2160p.UHD.BluRay.Remux.HDR.HEVC.DTS-HD.MA.5.1-PmP
19-9-24 10:23:25.0|Debug|ParsingService|Quality parsed: Remux-2160p v1 (None)
19-9-24 10:23:25.0|Trace|Owin|SQLite warning (284): automatic index on AlternativeTitles(MovieId)

19-9-24 10:23:25.0|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId)

19-9-24 10:23:25.1|Trace|ConfigService|Using default config value for 'parsingleniency' defaultValue:'Strict'
19-9-24 10:23:25.1|Debug|Parser|Parsing string 'The.Shining.1980.2160p.UHD.BluRay.Remux.HDR.HEVC.DTS-HD.MA.5.1-PmP.mkv'
19-9-24 10:23:25.1|Trace|Parser|^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(1(8|9)|20)\d{2}(?!p|i|(1(8|9)|20)\d{2}|\]|\W(1(8|9)|20)\d{2})))+(\W+|_|$)(?!\\)
19-9-24 10:23:25.1|Debug|Parser|Movie Parsed. The Shining - 1980 
19-9-24 10:23:25.1|Trace|Owin|SQLite error (5): database is locked

19-9-24 10:23:25.2|Trace|Owin|SQLite warning (284): automatic index on AlternativeTitles(MovieId)

19-9-24 10:23:25.2|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId)

19-9-24 10:23:25.2|Debug|ImportDecisionMaker|Analyzing 1/1 files.
19-9-24 10:23:25.2|Debug|Parser|Parsing string 'The.Shining.1980.2160p.UHD.BluRay.Remux.HDR.HEVC.DTS-HD.MA.5.1-PmP.mkv'
19-9-24 10:23:25.2|Trace|Parser|^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(1(8|9)|20)\d{2}(?!p|i|(1(8|9)|20)\d{2}|\]|\W(1(8|9)|20)\d{2})))+(\W+|_|$)(?!\\)
19-9-24 10:23:25.2|Debug|Parser|Movie Parsed. The Shining - 1980 
19-9-24 10:23:25.2|Debug|VideoFileInfoReader|Getting media info from /downloads0/The.Shining.1980.2160p.UHD.BluRay.Remux.HDR.HEVC.DTS-HD.MA.5.1-PmP.mkv
19-9-24 10:23:25.2|Trace|MediaInfo|Read file offset 0-245760 (245760 bytes)
19-9-24 10:23:25.2|Trace|MediaInfo|Read file offset 85161955913-85161972297 (16384 bytes)
19-9-24 10:23:25.2|Trace|MediaInfo|Read file offset 85163566553-85163576477 (9924 bytes)
19-9-24 10:23:25.2|Trace|MediaInfo|Read a total of 272068 bytes (0.0%)
19-9-24 10:23:25.2|Debug|DetectSample|Runtime is over 90 seconds
19-9-24 10:23:25.2|Debug|Parser|Parsing string 'The.Shining.1980.2160p.UHD.BluRay.Remux.HDR.HEVC.DTS-HD.MA.5.1-PmP.mkv'
19-9-24 10:23:25.2|Trace|Parser|^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(1(8|9)|20)\d{2}(?!p|i|(1(8|9)|20)\d{2}|\]|\W(1(8|9)|20)\d{2})))+(\W+|_|$)(?!\\)
19-9-24 10:23:25.2|Debug|Parser|Movie Parsed. The Shining - 1980 
19-9-24 10:23:25.2|Debug|VideoFileInfoReader|Getting media info from /downloads0/The.Shining.1980.2160p.UHD.BluRay.Remux.HDR.HEVC.DTS-HD.MA.5.1-PmP.mkv
19-9-24 10:23:25.2|Trace|MediaInfo|Read file offset 0-245760 (245760 bytes)
19-9-24 10:23:25.2|Trace|MediaInfo|Read file offset 85161955913-85161972297 (16384 bytes)
19-9-24 10:23:25.2|Trace|MediaInfo|Read file offset 85163566553-85163576477 (9924 bytes)
19-9-24 10:23:25.2|Trace|MediaInfo|Read a total of 272068 bytes (0.0%)
19-9-24 10:23:25.2|Debug|AggregateLanguage|Using language: English
19-9-24 10:23:25.2|Trace|AggregateQuality|Finding quality. Source: UNKNOWN. Resolution: R2160P
19-9-24 10:23:25.2|Warn|QualityFinder|Unable to find exact quality for UNKNOWN and R2160P. Using HDTV-2160p as fallback
19-9-24 10:23:25.2|Debug|AggregateQuality|Using quality: HDTV-2160p v1 (None)
19-9-24 10:23:25.2|Debug|FreeSpaceSpecification|Skipping free space check when importing
19-9-24 10:23:25.2|Debug|GrabbedReleaseQualitySpecification|Quality for grabbed release (Remux-2160p v1 (None)) does not match the quality of the file (HDTV-2160p v1 (None))
19-9-24 10:23:25.2|Debug|VideoFileInfoReader|Getting media info from /downloads0/The.Shining.1980.2160p.UHD.BluRay.Remux.HDR.HEVC.DTS-HD.MA.5.1-PmP.mkv
19-9-24 10:23:25.2|Trace|MediaInfo|Read file offset 0-245760 (245760 bytes)
19-9-24 10:23:25.2|Trace|MediaInfo|Read file offset 85161955913-85161972297 (16384 bytes)
19-9-24 10:23:25.2|Trace|MediaInfo|Read file offset 85163566553-85163576477 (9924 bytes)
19-9-24 10:23:25.3|Trace|MediaInfo|Read a total of 272068 bytes (0.0%)
19-9-24 10:23:25.3|Debug|DetectSample|Runtime is over 90 seconds
19-9-24 10:23:25.3|Trace|ConfigService|Using default config value for 'downloadclientworkingfolders' defaultValue:'_UNPACK_|_FAILED_'
19-9-24 10:23:25.3|Debug|ImportDecisionMaker|File rejected for the following reasons: [Permanent] File quality does not match quality of the grabbed release
19-9-24 10:23:25.3|Debug|ImportApprovedMovie|Decisions: 1`

**Comment by Nixon506E** [comment]
Makes me think that the media info check on the file itself is overriding the quality check on the name that is successful

**Comment by Qstick** [comment]
Yea, that needs to be adjusted, I meant are we at least not seeing the System.InvalidOperationException anymore

**Comment by LooseSeal2** [comment]
@Qstick so far radarr is importing fine with the correct quality.

**Comment by LooseSeal2** [comment]
As for the issue with No custom quality, edit your quality profile and check the box "None" under custom qualities at the bottom

**Comment by Nixon506E** [comment]
@LooseSeal2 None is checked on all of my profiles, should it be unchecked?

**Comment by Nixon506E** [comment]
Hoping to leave this bug open until the aggregation of the media info with parsed info works

**Comment by arpitgupta** [comment]
Whats the solution for this? I have been similar exceptions in the following version
```
Version
2.0.0.2094
Mono Version
5.20.1.34
Docker
True
DB Migration
156
AppData directory
/config
Startup directory
/opt/radarr
Mode
Console
Uptime
09:52:14
```

**Comment by chillyshackk** [comment]
Same here, and I only noticed after running a full renaming of my movies, now 90-95% of my movies are named with hdtv-1080p instead of webdl or bluray, it also got rid of most of the release groups and changed them to "radarr".

**Comment by fryfrog** [comment]
When that happens, it is because Radarr lost track of that information. Which is why you should store it in the file name. It could happen if the file disappeared and then re-appeared for some reason. It can happen when people transmux things from `.mkv` to `.mp4` for example.

**Comment by BinsonBuzz** [comment]
I'm having this problem.  I've been importing existing folders into 2.0.0.2096 and it never adds anything higher than HD1080 for 1080p files, even if the existing filename has remux in it e.g. 12 Years a Slave (2013) Remux-1080p AVC DTS-HD MA [EN+ES+FR+Chinese] tt2024544.  

To stop radarr trying to upgrade I've created a new temp profile with a HD1080 upgrade cutoff until resolved.

For new files that radarr downloads and imports the hit rate is better and it gets the quality right most of the time, but I still have to check to be sure.

**Comment by fryfrog** [comment]
Turn logging up to trace and do a refresh on that movie, capture a big chunk of context and show us. Your file name looks perfect for detecting 1080p Remux.

**Comment by BinsonBuzz** [comment]
Thanks for having a look as my imported qualities are all over the place and I've disabled upgrading now as it was adding files I've already got and then not importing them as the quality was coming up as an error e.g. saying HDTV when the download is a bluray the same size/quality as the file that's already there

Trace below includes when I manually scanned the 12 years file above:

[debug.txt](https://github.com/Radarr/Radarr/files/3736554/debug.txt)

**Comment by BinsonBuzz** [comment]
Here's another trace for a UHD file.  The file imported from my old non-beta radarr docker is named Bad Boys II (2003) Remux-2160p h265 DTS-HD MA [EN+HR+CS+DA+NL+FI+FR+DE+EL+HU+IT+NB+PL+PT+RO+RU+ES+SV+TR] tt0172156.mkv but the beta instance tags it as HD2160

[debug2.txt](https://github.com/Radarr/Radarr/files/3737963/debug2.txt)

**Comment by arpitgupta** [comment]
Keep running into this. Can one downgrade from aprodite to the older release from develop branch?

**Comment by Qstick** [comment]
Nope, need an old DB backup

**Comment by arpitgupta** [comment]
> Nope, need an old DB backup

Ah. Should have kept the old back up around for a bit longer lol. Will wait it out and see if this gets fixed in the next couple of weeks. Run into this pretty frequently.

**Comment by Sytanek** [comment]
It looks like there is an extra method called when a download occurs vs when a manual import happens.  I found that during parsing if you pass the movie into ParseMinimalMovieTitle() then it actually does pick up the quality from the file name.

**Comment by Qstick** [comment]
Should be good in build 2143

**Comment by arpitgupta** [comment]
Awesome. Time to do the upgrade again :). Thanks for the fix folks.

**Comment by BinsonBuzz** [comment]
Should 2143 fix the quality on previous imports as well?  I've just rescanned existing remux2160 library files that were mistakenly labelled as HD2160 and they are still being identified as HD2160

**Comment by Qstick** [comment]
Depends on how they were named, but if they are already in system as hd Radarr is not going to change them arbitrarily.

**Comment by BinsonBuzz** [comment]
> Depends on how they were named, but if they are already in system as hd Radarr is not going to change them arbitrarily.

ok that's a shame as a lot of my library was imported by v2 with the wrong quality e.g. _Ocean's Eight (2018) Remux-2160p DTS [EN+FR+IT+ES+PT+DA+FI+NB+RU+SV] tt5164214.mkv_ was identified as HDTV-2160p and I was hoping a refresh & scan would eventually fix old mistakes

**Comment by Qstick** [comment]
Remove and readd should work if the correct quality is in the file names

**Comment by BinsonBuzz** [comment]
Thanks -  Just did a handful and it worked.  I imported my 18k library, so I need to have a thing about which ones to fix in batches.  Thanks for fixing this - loving V2 overall
