### ISSUE TITLE
Radarr ignores G_Freeleech required flag in indexer settings

### ISSUE THREAD

**Issue by cryodream** [Radarr/Radarr#3769]
### Description
PTP indexer has a `G_Freeleech` **required** flag. When manually picked usenet download failed, Radarr auto-grabbed a torrent from PTP - **without** a `G_Freeleech` flag.

### Steps to reproduce the behavior:
1. Added an old movie.
2. Did a Manual Search.
3. Hand-picked an nzb.
4. NZBGet download failed.
5. Radarr auto-grabbed a torrent from PTP.

### Expected behavior
I would expect Radarr to honour the required `G_Freeleech` flag in PTP indexer settings. It should **never** grab a non-freeleech torrent by itself.

### Solution... for now?

* **Q1:** Would disabling the **Redownload** option in **Failed Download Handling** fix this problem, at least for now?
* **Q2:** Maybe there is a better solution?

![2019-09-15_16-09-15__chrome](https://user-images.githubusercontent.com/844036/64931814-0283ad00-d809-11e9-85bb-05c60f45109c.png)

### Additional questions
I would really appreciate some answers about how does the **Redownload** algorithm pick the next nzb/torrent to grab?

* **Q3:** There were 2 other nzbs of the same `CtrlHD` release. Did Radarr ignore those, because the failed download got blacklisted, and those other two have exactly same name (except the messed up letter-casing).
* **Q4:** I have the default **Prefer Usenet** delay profile. Why did Radarr ignore the (same quality) `TiMELORDS` nzb, at this point? Is it because I have **Prefer Special Indexer Flags** enabled?
* **Q5:** Or is Radarr looking for the exactly same release, that has failed? That would explain grabbing the torrent at this point.
* **Q6:** How did Radarr pick the torrent from PTP over HDBits? I mean, both have 1 internal flag. The only difference is hdbits torrent is matching a custom format, and I do not use this custom format for the **default** profile, that movie set to... Does this have any impact on Radarr picking PTP over HDBits here?

### System
 - OS: unRAID
 - Docker: [linuxserver/radarr](https://hub.docker.com/r/linuxserver/radarr/)
 - Mono Version: 5.20.1.34 (tarball Tue Jul 16 22:52:32 UTC 2019)
 - Version 0.2.0.1358

**Debug Logs**
Do you really need logs for this?

### Screenshots

![2019-09-15_18-43-15__chrome](https://user-images.githubusercontent.com/844036/64931817-031c4380-d809-11e9-87e6-c757b0440d84.png)

![2019-09-15_16-14-22__chrome](https://user-images.githubusercontent.com/844036/64931816-0283ad00-d809-11e9-9f79-24a1920b3e1e.png)

![2019-09-15_18-47-13__chrome](https://user-images.githubusercontent.com/844036/64931818-031c4380-d809-11e9-9fdf-c9e8a4180bbd.png)

![2019-09-15_18-47-28__chrome](https://user-images.githubusercontent.com/844036/64931819-031c4380-d809-11e9-989e-96fa756a2075.png)

This the **default** profile, that is used for this movie
![2019-09-15_18-47-57__chrome](https://user-images.githubusercontent.com/844036/64931820-031c4380-d809-11e9-95be-dd291d084a2b.png)

Nothing but default...
![2019-09-15_20-50-07__chrome](https://user-images.githubusercontent.com/844036/64931821-031c4380-d809-11e9-993d-3524edfe43ae.png)

Indexers global options
![2019-09-15_20-52-00__chrome](https://user-images.githubusercontent.com/844036/64931822-031c4380-d809-11e9-8ee3-8129114d65f9.png)

**Comment by galli-leo** [comment]
Yes we absolutely need debug logs

**Comment by cryodream** [comment]
Oh, sorry, I had log level set on `Info` only.
I assumed, that it is obviously not a simple situation, where I could enable Debug or Trace logging and recreate what happened. For this reason I tried to provide all the possible related info with screenshots. I honestly thought it will be enough info.

I my be wrong, but I really do not think, this is a "only-on-my-machine" type of bug. I mean, I honestly thought this is a write-a-test type of bug.

Well, just in case, here are the `Info` log. Although I don't see anything useful in it.
```
19-9-13 15:08:58.2|Info|MovieService|Adding Movie [The Full Monty (1997)][, 9427] Path: [/media/movies/radarr/The.Full.Monty.(1997)]
19-9-13 15:08:58.3|Info|RefreshMovieService|Updating Info for The Full Monty
19-9-13 15:08:58.7|Info|DiskScanService|Scanning disk for The Full Monty
19-9-13 15:08:58.7|Info|MovieScannedHandler|[The Full Monty] was recently added, performing post-add actions
19-9-13 15:08:58.8|Info|MediaCoverService|Testing: NzbDrone.Core.Messaging.Commands.CommandQueueManager, 521
19-9-13 15:08:58.8|Info|MediaCoverService|Downloading Poster for [The Full Monty (1997)][tt0119164, 9427] http://image.tmdb.org/t/p/original/xkMiZv2FPrhIAtxvEcN1jAbkHRY.jpg
19-9-13 15:08:58.9|Info|MediaCoverService|Downloading Fanart for [The Full Monty (1997)][tt0119164, 9427] http://image.tmdb.org/t/p/original/mAaSPfGA4ixiKSXYydNpbwZswi6.jpg
19-9-13 15:08:59.0|Info|MetadataService|Movie folder does not exist, skipping metadata creation
19-9-13 15:09:02.4|Info|NzbSearchService|Searching 4 indexers for [The Full Monty]
19-9-13 15:09:04.0|Info|DownloadDecisionMaker|Processing 36 releases
19-9-13 15:10:06.3|Info|Nzbget|Adding report [The.Full.Monty.1997.1080p.BluRay.DTS.x264-CtrlHD] to the queue.
19-9-13 15:10:06.6|Info|DownloadService|Report sent to NZBGet. The.Full.Monty.1997.1080p.BluRay.DTS.x264-CtrlHD
19-9-13 15:13:49.2|Info|RssSyncService|Starting RSS Sync
19-9-13 15:13:50.2|Info|DownloadDecisionMaker|Processing 250 releases
19-9-13 15:13:58.3|Info|RssSyncService|RSS Sync Completed. Reports found: 250, Reports grabbed: 0
19-9-13 15:22:49.5|Info|NzbSearchService|Searching 4 indexers for [The Full Monty]
19-9-13 15:22:51.1|Info|DownloadDecisionMaker|Processing 36 releases
19-9-13 15:22:52.6|Info|DownloadService|Report sent to Transmission. The.Full.Monty.1997.1080p.BluRay.DTS.x264-CtrlHD
19-9-13 15:22:52.6|Info|MovieSearchService|Movie search completed. 1 reports downloaded.
19-9-13 15:23:49.4|Info|PreDBService|Starting PreDB Sync
19-9-13 15:29:19.6|Info|RssSyncService|Starting RSS Sync
19-9-13 15:29:20.5|Info|DownloadDecisionMaker|Processing 250 releases
19-9-13 15:29:28.2|Info|RssSyncService|RSS Sync Completed. Reports found: 250, Reports grabbed: 0
19-9-13 15:43:50.1|Info|MovieService|Linking [The.Full.Monty.1997.1080p.BluRay.DTS.x264-CtrlHD.mkv] > [[The Full Monty (1997)][tt0119164, 9427]]
```

**Comment by fryfrog** [comment]
Can you reproduce the error? If so, do it while you have logging set to Trace and put the logs in a pastebin for us.

**Comment by cryodream** [comment]
This is still happening. I cannot reproduce it on demand, obviously. The only way is to always run with debug logs enabled, which I cannot do atm.

Either way, IMHO this needs some test(s) to be written, not logs.

**Comment by ga3a** [comment]
Ran into the same issue. PTP is configured with the G_Freeleech but still pulled a version that was not FL 

https://gist.github.com/ga3a/c217c77b8abb366a817fe02ceaf2670c
