### ISSUE TITLE
Support AwesomeHD User Release Indexer Flag

### ISSUE THREAD

**Issue by mpeleshenko** [Radarr/Radarr#3770]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Support AHD_UserRelease indexer flag for AHD user releases. There is currently no way to distinguish between AHD user releases and non-user releases that are not Internal, and user releases are held to a higher standard.

**Additional context**
The AHD search API already exposes <userrelease>1</userrelease> in the search results, so this should be similar in implementation to the AHD_Internal flag.
Sample
```xml
<searchresults>
    ...
    <torrent>
        ...
        <internal>1</internal>
        <userrelease>0</userrelease>
        ...
    </torrent>
</searchresults>
```

**Comment by fryfrog** [comment]
Is this something like PTP's Golden Popcorn?

**Comment by mpeleshenko** [comment]
It is indeed similar to PTP’s Golden Popcorn.
