### ISSUE TITLE
Setting the torrent history to be deleted in download client breaks copying / hardlinking

### ISSUE THREAD

**Issue by polishboi** [Radarr/Radarr#3773]
**Describe the bug**
If I set in qbittorrent to delete the torrent after downloading I get this in my logs:
```
Unknown download state: missingFiles
```
This log is repeated 4 times every minute **all the time**.
As a result after download different versions are being downloaded even though the download was successful!

**To Reproduce**
1. Go to your particular download client `after-download-management section`:
   - in qbitorrent:
 
![image](https://user-images.githubusercontent.com/48173986/65167487-f71bc600-da42-11e9-844b-d959c7db45ba.png)

**Expected behavior**
Some info to not do this **in the UI** or otherwise circumvent this unwanted behavior.

**Desktop (please complete the following information):**
 - OS: Windows

 - Version
0.2.0.1358

**Debug Logs**
I will not wait for something that infuriates me to happen again, sorry but I changed my settings and already I'm not looking forward to manually copying, deleting duplicates and renaming tens of movies and TV show episodes 👿 

BTW Awesome project guys!

**Comment by fryfrog** [comment]
I'm not totally sure what you're asking for here. Do you just want a warning somewhere to *not* configure your download client to remove the torrents?

**Comment by fryfrog** [comment]
Or maybe you don't understand how to use Radarr/Sonarr w/ torrents and removal? In Complete and Failed Download Handler, turn on Remove (might have to toggle advanced). Setup your seed time/ratio goals where ever (your torrent client for Radarr, in Sonarr it can be set per indexer) and then just setup your torrent client to pause/stop torrents that are finished seeding. Then Sonarr/Radarr will *remove* them after import.
