### ISSUE TITLE
API endpoint to Change a Movie's root folder

### ISSUE THREAD

**Issue by jd4883** [Radarr/Radarr#3774]
** Feature idea overview**:
I would like to have the ability to programmatically change the root folder of a given movie. The way I run my plex server, I have several root folders and am working on engineering a solution to do the following:
# Read in all root folders from Radarr and checks available space. This will be stored for use later.
# reads in all movies and adds a tag for each genre that is stored. This should be accomplishable using the current API functionality for tagging along with a movie_lookup
# compares names of tags to definitions I'll apply to the different root folders read in
# if a root folder that matches any of a movies tags has a larger quantity of available space, I want to automatically change the root folder.

For my setup, I use different disks to represent different genres because of how large my library has gotten. I can manually accomplish what I've outlined above, but cannot accomplish this programmatically (at least I don't think it is possible without being very clunky if at all with the current API)

**Is your feature request related to a problem? Please describe.**
This is not a problem but a supplemental request for a feature that exists in the GUI to be able to be used programmatically with the API (or for the functionality to be added directly to Radarr in the future).

Without an API endpoint or other method to accomplish this, I do not see a good way to change the root folder and use Radarr itself to handle the actual transitions. I could definitely do it manually but that seems really silly when Radarr is really good at changing root folders in the GUI.

**Describe the solution you'd like**
Given my overview, I would like API endpoint options where I can leverage Radarr to read in a root folder and change it. Bonus points if Radarr implements a way to load balance content across root folders as I am trying to accomplish. More bonus points if an easier method than the current tag API endpoint can be made available for adding tags based on genres stored in Radarr's database

**Describe alternatives you've considered**
# Not bothering with an automated tool and continuing this process manually, which is time consuming and not a precise method.
# trying to read in the root folder with a get request via the API, adjust the output to the desired root folder, and feed it back. I'd script a method of moving all the contents to the correct root folder so Radarr doesn't have to do this. This feels like a lot of extra programming when Radarr already is really good at handling root folder migrations.
# have a feature introduced to allow manipulation of ones library based on criteria set in Radarr to keep a multi drive setup like mine running smoothly

**Additional context**
I think I accomplished this in my overview. Please let me know if I can clarify anything better. For now I'd be perfectly happy just to be able to use the API to change a movie root folder exactly as I can in the GUI including moving all files and folders and renaming appropriately.

Thanks again for developing an awesome program, I use it every day. I would love to see more automation oriented API options become available

**Comment by Qstick** [comment]
This can be done in Aphrodite with movie/editor endpoint

**Comment by jd4883** [comment]
Thank you @Qstick I look forward to trying this out. Out of curiosity, are there a list of all endpoints currently available in this release I can reference? This version looks awesome and I look forward to giving this a shot this week!

Cheers,

Jacob

**Comment by Qstick** [comment]
No list or API docs as of yet for V2 (Aphrodite)
