### ISSUE TITLE
Blacklist movies from movie editor

### ISSUE THREAD

**Issue by wessel145** [Radarr/Radarr#3775]
It's pretty simple: when deteling a movie (by clicking on it), you get the option to blacklist the movie from automated lists. You don't get this option when you bulk delete movies using the movie editor.

**Describe the solution you'd like**
An option to blacklist multiple movies at once using the movie editor.

**Additional context**
I'm actually on the preview docker branch, so I know it isn't meant to be stable, but this function may help a lot of people :)

**Comment by fryfrog** [comment]
Did you try the delete dialog? I don't think it is there, but this would be a really great place for it. Delete a movie and optionally delete the files (exists) and optionally blacklist.

**Comment by wessel145** [comment]
The normal "delete" button is available, which gives the option to delete the movie from radarr, there is a checkbox for deleting the files as well (that works like charm), but the blacklist option isn't there (it is when I delete a single movie. When the list is updated in radarr, it adds the movie right back again.
