### ISSUE TITLE
Cannot combine OsPaths of different platforms

### ISSUE THREAD

**Issue by Bastien42** [Radarr/Radarr#3776]
my issue is that when Radarr grabs this movie from : [1337x ](https://1337x.to/torrent/3727088/Arachnophobia-1990-1080p-H265-HEVC/)
it triggers that error in the log you've already partially talked about that in another issue but here i give you a files that you can try to debug.

radarr 0.2.0.1358 running on windows 10 pro 1903 everything runs from the same computer all local.

so the isse is that it grabbed the torrent great but then the / in the naming of the folder structure of the torrents triggers that issue from what i understand thanks for your time and for this soft :)

**Comment by Bastien42** [comment]
full log sorry 

[v0.2.0.1358] System.Exception: Cannot combine OsPaths of different platforms ('E:\Downloads\radarr1337\' + 'Arachnophobia (1990) [1080p] [H265/HEVC]')
   at NzbDrone.Common.Disk.OsPath.op_Addition(OsPath left, OsPath right) in C:\projects\radarr-usby1\src\NzbDrone.Common\Disk\OsPath.cs:line 283
   at NzbDrone.Core.Download.Clients.QBittorrent.QBittorrent.GetItems() in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\Clients\QBittorrent\QBittorrent.cs:line 103
   at NzbDrone.Core.Download.TrackedDownloads.DownloadMonitoringService.ProcessClientDownloads(IDownloadClient downloadClient) in C:\projects\radarr-usby1\src\NzbDrone.Core\Download\TrackedDownloads\DownloadMonitoringService.cs:line 86

**Comment by Bastien42** [comment]
[radarr.txt](https://github.com/Radarr/Radarr/files/3633216/radarr.txt)

**Comment by Bastien42** [comment]
also a temporary fix is to rename the torrent file name but i'm afraid Radarr is no longer going to be able to recogniize it.

**Comment by fryfrog** [comment]
Is it the `/` in `[H265/HEVC]`?

**Comment by Bastien42** [comment]
yes when i erase it in the torrent naming it works sort of or it just makes radarr dismiss i dunno

**Comment by Qstick** [comment]
Same as #1761

**Comment by Bastien42** [comment]
yes it's the same but galileo ask for a torrent to troubleshoot to the issue because it was not properly fixed

**Comment by Qstick** [comment]
it's fine if you just reply to that issue instead of opening a new one.

**Comment by Bastien42** [comment]
okay i was not sure since the other one was closed thanks

**Comment by Qstick** [comment]
Other issue is not closed
