### ISSUE TITLE
Adding Movie Genre to "Search Movies"

### ISSUE THREAD

**Issue by matthewtroup1983** [Radarr/Radarr#3777]
Currently you can search keywords such as "storm" and movies with storm in the title show, however it would be nice to search by Genre. I understand this could be completed by importing a movie list "sorta" but it would be super nice to be able to search for "movie ideas" based on movie Genre's within the application. I feel if this can be completed we can then pass this along to Ombi development so users can search and find movie ideas with better ease.

**Comment by fryfrog** [comment]
I'd dig around for an existing issue, I'm pretty sure there is more than one w/ this as a similar request. I recall one about being able to search by many things like director, actor, writer, etc. Find it and give it a thumbs up and maybe link your request to it too.
