### ISSUE TITLE
Unable to get trakt auth

### ISSUE THREAD

**Issue by xybydy** [Radarr/Radarr#3779]
When I try to get trakt authentication I could not get trakt auth key. I get the error 

> This radarr.aeonlucid.com page can’t be found 
> "http://radarr.aeonlucid.com/v1/trakt/redirect?target=http://[MYPAGE].com/settings/netimport
> 

**Desktop (please complete the following information):**
 - OS: RPI3b+ dockerized by linuxserver/radarr
 - Mono Version: 5.20.1.34

**Comment by AeonLucid** [comment]
Yeah this was on purpose because the update api kept crashing with trakt support enabled. 
I'll re-add this very soon.

**Comment by xybydy** [comment]
Great to hear that! Thanks

**Comment by AeonLucid** [comment]
@xybydy can you test if it works now?

**Comment by xybydy** [comment]
Nope, not working :/

The error I got now is 

> radarr.aeonlucid.com is currently unable to handle this request.

to the url 

> http://radarr.aeonlucid.com/v1/trakt/redirect?target=http://[RADARR_URL]/settings/netimport

I think something is wrong with target parameter handling

**Comment by x-DodgyBob-x** [comment]
Hi folks,

Just adding my 2cents!

So yes, in Radarr v0.2.0.1358 (installed on my Synology NAS, accessed from Local PC), I go Settings > Lists > Trakt Authentication > hit the red 'Reset Trakt Tokens' button > and a popup displays...
![image](https://user-images.githubusercontent.com/53667144/65396189-f38f9280-dde6-11e9-96e8-8784c8460324.png)
...I hit OK, then:

 * In IE - I'm taken here > http://radarr.aeonlucid.com/v1/trakt/redirect?target=http://x.x.x.x:yyyy/settings/netimport < but get a HTTP 500 error

 * In FF - I'm taken here > http://radarr.aeonlucid.com/v1/trakt/redirect?target=http://x.x.x.x:yyyy/settings/netimport < but left with a blank webpage
 and

 * In Chrome - I'm taken here > http://radarr.aeonlucid.com/v1/trakt/redirect?target=http://x.x.x.x:yyyy/settings/netimport < but get a HTTP 500 error

Nothing is shown in System > Logs

Let me know if you want me to test anything or send through any other information.

Kind regards,
Dodgy Bob

**Comment by BodingClockchian** [comment]
Im having the same issue with version 0.2.0.1358 and mono 5.20.1.34. Also using the docker.
Error in log: `Trakt List HTTP request failed: [500:InternalServerError] [GET] at [http://radarr.aeonlucid.com/v1/trakt/refresh?refresh=XXXXXXXXXXXXX`

Also not able to refresh the token because aeonlucid seems to be down

**Comment by AeonLucid** [comment]
I think it's fixed now, can anyone confirm?

**Comment by xybydy** [comment]
Unfortunately it does not work.

Something in post-process the auth is weird when I check network logs.

It successfully redirected with link below
> https://api.trakt.tv/oauth/authorize?response_type=code&client_id=[CLIENT_CODE_WAS_HERE}&redirect_uri=http%3A%2F%2Fradarr.aeonlucid.com%2Fv1%2Ftrakt%2Fcallback&state=412e640a-c98d-4136-999c-c56803d9b827

and then got the log below,

> http://radarr.aeonlucid.com/v1/trakt/callback?code=[THE_CODE]&state=412e640a-c98d-4136-999c-c56803d9b827

But the url after the one above is below,

> http://localhost:7878/settings/netimport?access=&refresh=

I think access and refresh variables should have been with the codes.

**Comment by AeonLucid** [comment]
@xybydy Try again please, I actually tested and fixed it this time.

**Comment by geogolem** [comment]
seems to be working for me now! Thanks!
