### ISSUE TITLE
Add Year to Title on page, manual import selection

### ISSUE THREAD

**Issue by LooseSeal2** [Radarr/Radarr#3781]
**Is your feature request related to a problem? Please describe.**
The year should be added when selecting a movie during a manual import process. There are many movies with the same name now. The year should always be displayed next to the title. The movie page doesn't have the year clearly visible either, (should be in title).

It makes it a guessing game when using the search bar or when you have to manually import.

**Describe the solution you'd like**
When displaying a movie title, always display the year too.

**Additional context**
Using Aphrodite

**Comment by Qstick** [comment]
Fixed by 923db777516353aa14fb639489e3fe2da9464c5e
