### ISSUE TITLE
Add - Trakt List "Unable to connect to list: HTTP request failed"

### ISSUE THREAD

**Issue by x-DodgyBob-x** [Radarr/Radarr#3783]
### **Describe the bug...**
When adding a "UserCustomList" Trakt List, testing fails and 3 entries are written to the logs

### **To Reproduce...**
1. Navigate to and login to https://trakt.tv/auth/signin
2. Go to Lists, then 'ADD LIST'
3. Add _Name_ (no spaces), Privacy to _Public_, Comments to _No_, Default Sorting to _Title_, Click _SAVE LIST_
4. Search for movie in Trakt and add to list created in Step.3
5. Login to Radarr
6. Go to Settings > Lists > Lists > click '+' button > click 'Trakt List' button
7. Change _Name_, Add Movies Monitored to _Yes_, Quality Profile to _Custom_, Folder to _movies folder on NAS_, List Type to _UserCustomList_, Username to _Trakt Username_, List Name to _Name from Step.3_, Click _Test_
8. See screenshots and log for what happens next!

### **Expected behavior...**
Radarr will access and import the Trakt Custom User List successfully for downloading.

### **Screenshots...**
![image](https://user-images.githubusercontent.com/53667144/65396865-4ae53100-ddee-11e9-90ff-2d87dd05bf7b.png)

![image](https://user-images.githubusercontent.com/53667144/65396868-56d0f300-ddee-11e9-8201-551cc0f21113.png)

### **Desktop (please complete the following information)...**
 - OS: Windows 7
 - Mono Version: 5.18.0.240-12
 - Browser and Version: IE (32bit) 11.0.9600.19463 | FF (64bit) 69.0.1 | Chrome (64bit) 76.0.3809.132
 - Version: 0.2.0.1358

### **Debug Logs...**
see here --> [radarr.debug.txt](https://github.com/Radarr/Radarr/files/3640364/radarr.debug.txt)

**Comment by Qstick** [comment]
Believe this is related to #3779

**Comment by x-DodgyBob-x** [comment]
I was wondering if it was, however, since this issue is happening in another area of Radarr I thought it might be good to bring it up all the same.

I guess, suffice it to say then that _all_ Trakt integration with the current version of Radarr is broken then??

**Comment by AeonLucid** [comment]
I don't think this is related to the other issue.
