### ISSUE TITLE
Release Group isn't Parsed Correctly During Renaming

### ISSUE THREAD

**Issue by GautierT** [Radarr/Radarr#3784]
**Describe the bug**
Release Group is not correctly picked up by Radarr.

**To Reproduce**
1. Set Standard Movie Format to : `{Movie.CleanTitle}.{Release.Year}.{EDITION.TAGS}.{QUALITY.REAL}.{QUALITY.PROPER}.{Quality.Title}.{MediaInfo.VideoCodec}-{RELEASE.GROUP}`
2. Select a movie and click on "Preview Name for movie"

**Expected behavior**
` /movies/The Wolf of Wall Street (2013)/The.Wolf.of.Wall.Street.2013.1080p.BluRay.x264.YIFY.mp4`
should be renamed to 
`/movies/The Wolf of Wall Street (2013)/The.Wolf.of.Wall.Street.2013.Bluray-1080p.x264-YIFY.mp4`

**Screenshots**
![image](https://user-images.githubusercontent.com/6089653/65414240-964e0e00-ddf3-11e9-9e91-011bd041f124.png)

**Version**
Version : 0.2.0.1358
Mono Version : 5.20.1.34 (tarball Tue Jul 16 22:52:32 UTC 2019)

**Comment by Qstick** [comment]
This issue is already open somewhere, can't seem to find it now though

**Comment by fryfrog** [comment]
You might want to use `{-Release Group}`. Also, it means that Radarr hasn't stored the group. Doesn't it look for `-GrouP` or `[GrouP]`?

**Comment by GautierT** [comment]
@fryfrog : what is the difference between {Release Group} and {-Release Group} ?

**Comment by Qstick** [comment]
Adding the dash inside the tag makes it conditional

**Comment by fryfrog** [comment]
Though if Radarr doesn't have the group, it just calls it `Radarr`, so having the `-` inside the `{}` doesn't *really* matter.

**Comment by GautierT** [comment]
@fryfrog : Do you have an idea why Radarr doesn't pick YIFY in the name ?
An other example with this settings : 
`{Movie.CleanTitle}.{Release.Year}.{EDITION.TAGS}.{QUALITY.REAL}.{QUALITY.PROPER}.{Quality.Title}.{MediaInfo.VideoCodec}-{RELEASE.GROUP}`

```Name:
WALL-E (2008) [1080p]
Source:
/downloads/torrents/deluge/WALL-E (2008) [1080p]/WALL-E.2008.1080p.BrRip.x264.YIFY.mp4
Imported To:
/movies/WALL·E (2008)/WALL·E.2008.Bluray-1080p.x264-RADARR.mp4
```

Thanks

**Comment by fryfrog** [comment]
Yeah, YIFY doesn't do their group names in a way that look like groups. See how it is `.YIFY.` in your example instead of `-YIFY`?

**Comment by GautierT** [comment]
Okay. Is their something i can do to fix this ? Each time i download a yify movie i have this problem. How other person do ? Thanks @fryfrog

**Comment by fryfrog** [comment]
Everyone else blocks `YIFY` and `YTS`, they're trash. If you can find some way to change `.YIFY` or `.YTS` to `-YIFY` and `-YTS` in your download client, that'd side step it. You might be able to reach out to them and fix their release naming.

**Comment by GautierT** [comment]
aha ! Okay thanks a lot @fryfrog  !
