### ISSUE TITLE
API: Editing Movie Results in Error 500 Request Failed

### ISSUE THREAD

**Issue by bifa2** [Radarr/Radarr#3787]
**Describe the bug**
Executing a `PUT` against `/api/movie/{id}` to set `monitored` to false results in an Error 500 response to end client, and the following `NZBDroneErrorPipeline` component error reporting `Request Failed: Error converting value "@{id=6; name=Bluray-720p; source=bluray; resolution=r720P; modifier=none}" to type 'NzbDrone.Core.Qualities.Quality'. Path 'movieFile.quality.quality', line 71, position 126.`

**To Reproduce**
Uncertain - the same commands (as per the API: get movie data first, modify, and put back) work to mark other movies as unmonitored. The problem happens with this movie (possibly others) and I can't determine why.

**Expected behavior**
Movie is marked as unmonitored.

**Desktop (please complete the following information):**
 - OS: Windows 10
- Radarr Version: 0.2.0.1358

**Debug Logs**
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/3643063/radarr.debug.txt)

**Comment by bifa2** [comment]
It appears as though this happens when the data returned by a `GET` request for a movie, has a `movieFile` property (i.e. it has data). It does not matter whether the movieFile exists on disk (or has been deleted or moved). Attempting to update the monitored status of these fails with the same error.

**Comment by AdnanC** [comment]
I am getting the same error as well. For now, i just set .movieFile.quality = "" and it works. Not the ideal solution but I just wanted to update the monitor status didn't really care about the file info. Though it doesn't seem like removing the quality object makes any difference, when I do a get again on the movie it is still there and the monitored field has updated.

**Comment by Brando47** [comment]
I'm having a similar-ish issue, however I can successfully modify with the API things like monitored or the path. However I'm specifically trying to update the quality information for a movieFile. Every time I PUT the modified json, I get a 202 response but the response body indicates none of the qualities have been changed. I have been testing using the exact json retrieved by GET after manually changing the quality profile for that file in radarr, changing it back and then attempting to change it again via the API without success.
