### ISSUE TITLE
Different search query

### ISSUE THREAD

**Issue by WaZz2** [Radarr/Radarr#3788]
I currently have 5 indexers set in Jackett. All can be queried with a different query.

I am looking for `La course des tuques (2018)` which has the `Also known as: "La course des tuques 3D". `

here is the log:
`19-9-23 22:32:48.2|Debug|Torznab|Downloading Feed http://192.168.0.142:9117/api/v2.0/indexers/gktorrent/results/torznab/api?t=search&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060&extended=1&apikey=(removed)&offset=0&limit=100&q=la%20course%20des%20tuques%203d
19-9-23 22:32:48.2|Debug|Torznab|Downloading Feed http://192.168.0.142:9117/api/v2.0/indexers/sharewood/results/torznab/api?t=search&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060&extended=1&apikey=(removed)&offset=0&limit=100&q=la%20course%20des%20tuques%203d%202018
19-9-23 22:32:48.2|Debug|Torznab|Downloading Feed http://192.168.0.142:9117/api/v2.0/indexers/cpasbienclone/results/torznab/api?t=search&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060&extended=1&apikey=(removed)&offset=0&limit=100&q=la%20course%20des%20tuques%203d%202018
19-9-23 22:32:48.2|Debug|Torznab|Downloading Feed http://192.168.0.142:9117/api/v2.0/indexers/yggtorrent/results/torznab/api?t=search&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060&extended=1&apikey=(removed)&offset=0&limit=100&q=la%20course%20des%20tuques%203d%202018
19-9-23 22:32:48.2|Debug|Torznab|Downloading Feed http://192.168.0.142:9117/api/v2.0/indexers/torrent9clone/results/torznab/api?t=search&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060&extended=1&apikey=(removed)&offset=0&limit=100&q=la%20course%20des%20tuques%203d%202018
19-9-23 22:32:48.7|Debug|Torznab|Downloading Feed http://192.168.0.142:9117/api/v2.0/indexers/gktorrent/results/torznab/api?t=search&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060&extended=1&apikey=(removed)&offset=0&limit=100&q=la%20course%20des%20tuques
19-9-23 22:32:53.3|Debug|Torznab|Downloading Feed http://192.168.0.142:9117/api/v2.0/indexers/cpasbienclone/results/torznab/api?t=search&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060&extended=1&apikey=(removed)&offset=0&limit=100&q=la%20course%20des%20tuques%202018
19-9-23 22:32:54.8|Debug|Torznab|Downloading Feed http://192.168.0.142:9117/api/v2.0/indexers/sharewood/results/torznab/api?t=search&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060&extended=1&apikey=(removed)&offset=0&limit=100&q=la%20course%20des%20tuques%202018
19-9-23 22:32:54.8|Debug|Api|[GET] /api/log/file: 200.OK (1 ms)
19-9-23 22:32:54.9|Debug|Api|[GET] /api/log/file/radarr.debug.txt: 200.OK (1 ms)
19-9-23 22:32:55.3|Debug|Torznab|Downloading Feed http://192.168.0.142:9117/api/v2.0/indexers/yggtorrent/results/torznab/api?t=search&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060&extended=1&apikey=(removed)&offset=0&limit=100&q=la%20course%20des%20tuques%202018
19-9-23 22:33:06.8|Debug|Torznab|Downloading Feed http://192.168.0.142:9117/api/v2.0/indexers/torrent9clone/results/torznab/api?t=search&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060&extended=1&apikey=(removed)&offset=0&limit=100&q=la%20course%20des%20tuques%202018
`

so `q=la%20course%20des%20tuques%202018` was triggered for 4 indexers
`q=la%20course%20des%20tuques%203d%202018` was also triggered for the same 4
`q=la%20course%20des%20tuques` was triggered for only 1 indexer

All of those 3 different queries are valid, but why aren't they triggered on all 5 indexers?

**Desktop (please complete the following information):**
 - OS: ubuntu 19.04
 - Mono Version: 5.18.0.240 (Debian 5.18.0.240+dfsg-2ubuntu2 Wed Apr 17 23:39:09 UTC 2019)
 - Version 0.2.0.1358

**Comment by Qstick** [comment]
Likely you have remove year from search string enabled for one indexer. Hop on Discord if you need some help getting it changed.
