### ISSUE TITLE
Manual Search Never Loads

### ISSUE THREAD

**Issue by Ryonez** [Radarr/Radarr#3789]
**Describe the bug**

**To Reproduce**
1. Go to a movie. 
2. Click on search tab
3. Wait and enjoy the bouncing dots.
5. Extra: It may work fine on movies, but not others. Hell sometimes it'll be intermittent on the same movie.

**Expected behavior**
For a list of results I can use to appear.

**System (please complete the following information):**
 - OS: Unraid
 - Docker: binhex/arch-radarr
 - Mono Version: 5.20.1
 - Version 0.2.0.1358

**Debug Logs**
https://pastebin.com/Y6JvxHaf

**Comment by Qstick** [comment]
I don’t see any issues in your log. The api call appears to return results after 13 seconds in that case. This loading can take longer for different movies depending on how many indexers you have and how many results are on each indexer.

**Comment by Ryonez** [comment]
I have two indexers, and I didn't get any results shown to me.

Closing this was premature. @Qstick

**Comment by Ryonez** [comment]
Here's a log for a search that's been going for about 6 mins:
https://pastebin.com/x8YAzNRU

I didn't navigate away from the page like I did with the last one when I got the log.

**Comment by Ryonez** [comment]
Here's a log for a search that's been going for about 12ish mins (Went and had a shower):
https://mega.nz/#!oJwX0QaL!jAp5PtTTY4ZxeD0wL1Hh9IH7KQMrVjhra7qG9eVQx0g
*Set to Mega as Pastebin has a limit.*

I didn't navigate away from the page like I did with the last one when I got the log.

**Comment by Qstick** [comment]
In that log it appears the search call returns in about 17sec, and then a rss sync is triggered right after, those are the other non related results you are seeing in the log.

**Comment by Qstick** [comment]
Have you tried the nightly version? 0.2.0.14xx. it has some fixes for jackett related timeout issues.

**Comment by Ryonez** [comment]
I haven't, and I'm not sure that there's a nightly build for the docker image.

I'd also appreciate it if you reopened this, this is an actual issue.

**Comment by fryfrog** [comment]
Hop on Discord or post on Reddit, we'll help you figure it out. If it ends up being a real bug, you can add details to this and re-open it.

**Comment by Ryonez** [comment]
I'm sorry, I fail to see the support aspect of this. Unless there's a setting somewhere called "Actually display results if I have them", this would appear to be a bug.

I'm not exactly keen to go somewhere else when I know I'm going to just end right back here.

**Comment by Ryonez** [comment]
Posting this in case anyone else finds this and has my issue.

I was using two proxies, letsencrypt and keycloak-gatekeeper. A user would get to letsencrypt, which forwards them to the keycloak-gatekeeper which handles authentication.

However, gatekeeper had some tight timeouts I wasn't aware of. This cause a few issues, however I've narrowed down the changes needed to extend the timeout for what's needed. You can add the following to your gatekeeper config:
```
upstream-response-header-timeout: 240s
server-read-timeout: 240s
server-write-timeout: 240s
server-idle-timeout: 240s
```
This will allow for searches to return their results.

**Comment by Krandor1** [comment]
Good info and good to know it wasn’t actually a bug in Radarr.

**Comment by Ryonez** [comment]
That's a fair jab >.<
