### ISSUE TITLE
Cross-contamination of missing queue sort settings from Radarr to Sonarr

### ISSUE THREAD

**Issue by rodti** [Radarr/Radarr#379]
I noticed that the Missing tab of the Wanted section in my Sonarr install isn't loading.  In the Sonarr logs I receive the following error:

Request Failed: Instance property 'inCinemas' is not defined for type 'NzbDrone.Core.Tv.Episode'

The 'inCinemas' part of this error seemed more relevant to Radarr.

I went into my Radarr install and changed the Missing sort order to by physical release.  Sonarr now gives this error:

Request Failed. GET /api/wanted/missing: Instance property 'physicalRelease' is not defined for type 'NzbDrone.Core.Tv.Episode'

The detail from the trace log for these is:

logs/sonarr.trace.txt:17-1-22 11:56:07.6|Trace|Http|Req: 206 [GET] /api/wanted/missing??page=1&pageSize=15&sortKey=inCinemas&sortDir=desc&filterKey=monitored&filterValue=true
logs/sonarr.trace.txt:[v2.0.0.4472] System.ArgumentException: Instance property 'inCinemas' is not defined for type 'NzbDrone.Core.Tv.Episode'

It looks like somehow these sort settings are leaking out of Radarr or being pulled into Sonarr and breaking the latter.

Develop build 2.0.0.4545 for Sonarr and develop build 0.2.0.196 for Radarr.

**Comment by galli-leo** [comment]
This has to do with #285

**Comment by rodti** [comment]
Good spot. I'd been searching and searching and couldn't find anything relevant.
