### ISSUE TITLE
Set to developer branch, correct that there hasn't been a pre-release since June?

### ISSUE THREAD

**Issue by piejanssens** [Radarr/Radarr#3791]
On the last release I noticed the message  "To receive further Pre-Release updates, please change the branch to develop. (Settings -> General (Show Advanced Settings) -> Updates -> Branch)"
I was already on the dev branch. Just curious if the dev branch is still based on github releases, so that I know it's normal the last one was June.

**Comment by Dnkhatri** [comment]
The devs are working on v3 radarr. It still has many bugs but if you want to try change branch to aphrodite

**Comment by Qstick** [comment]
June is the last release that is correct, should be another develop branch release soon. Don't try Aphrodite (V2) unless you are willing to provide high quality bug reports.
