### ISSUE TITLE
1080p movies incorrectly identified as 720p

### ISSUE THREAD

**Issue by azza10** [Radarr/Radarr#3792]
**Describe the bug*
1080p movies are being incorrectly labelled as 720p
especially when the titles only says something like 1080 instead of 1080p or when there is no quality specified in the title.

This causes an error on import as it expects 720p.
**To Reproduce*
Find a nzb or torrent that specifies no quality or something like

Lilo & Stitch.2002.1080.BluRay.x264.DTS-NoGroup

It is labelled 720p in radarr

**Expected behavior*
resolution is labelled correctly as 1080p or if no quality is specified then labelled as unknown.

running windows 10
radarr 

version 0.2.0.1358

**Debug Logs**
[radarr.txt](https://github.com/Radarr/Radarr/files/3665525/radarr.txt)

**Comment by fryfrog** [comment]
I think the right fix for this is for Radarr to pull the resolution from the file at import or warn when they miss-match and allow for human intervention.

**Comment by Qstick** [comment]
Yep, that's already implemented in Aphrodite, likely not going to back port it.

**Comment by azza10** [comment]
It already does that check on import, which is good.

But it would be better if it worked properly in the first place. No reason to identify something as 720p when there is literally no 720 in any form in the title, and sometimes 1080.

This is obviously a bug.

**Comment by fryfrog** [comment]
What about a movie w/ "720" or "1080" in the title? I don't think it makes sense to blindly assume. If there is deviation from what is expected, showing them w/ an orange icon and allowing the user to evaluate is the better decision.

**Comment by azza10** [comment]
Then you would parse that as the title... Radarr knows the movie title.

The problem is releases are being tagged incorrectly. I have had a couple of movies download that had no quality in the title, just the movie title. Radarr labelled them as 720p, not unknown.

I had a couple of movies download with 810p in the title (file was 1080p), tagged as 720p by radarr.

I had a couple download with *.1080.* in the title. Radarr labelled as 720p. Maybe it shouldn't be tagged 1080p, but a sure shouldn't be tagged 720p.

My point is if radarr isn't able to 100% identify the quality it should be labelled unknown. Not labelled any random quality.

I'd much rather have nothing autodownload and have to manually grab an "unknown" than be deleting incorrectly identified releases all the time.

**Comment by azza10** [comment]
In the mean time I have set 720p as a preferred word for the profile. Working well so far, but radarr shouldn't be labelling things this way.

If quality cannot be determined, label as unknown. Not 720p.

**Comment by fryfrog** [comment]
Ah, I see what you mean and I think I mostly agree.

If resolution from the file itself and the release match, I'd like it to process as normal.

If resolution of the file itself and the release *don't* match, I would prefer it didn't make assumptions and left it in Activity for the human to decide. It should list the resolution from the file, to ease that choice.

If the *quality* isn't in the release name, I'm not sure what the right choice is. I don't think "Unknown" is exactly right. I don't think blindly processing it to *any* quality is quite right. Using what came from the indexer *and* orange icon in Activity would be ideal. Or more likely, just orange icon it and let the human import.

**Comment by kstlouis** [comment]
This was closed because it was stale, but should be open, as it's definitely still a problem. 

I had the same issue today, with an item being marked as 720p by Radarr when "1080" (but not "1080p") was in the filename. 

I get it's probably the missing p that's the issue here, but it's still something that should be fixed.

**Comment by azza10** [comment]
Yep. I really have no idea why the original repliers failed to grasp what the issue was... Very quick to dismiss me.

I just ended up putting a required word of 720p in for 720p profile. A workaround, but it solved the problem in the mean time.
