### ISSUE TITLE
Radarr marking .avi files as missing

### ISSUE THREAD

**Issue by Starminder** [Radarr/Radarr#3794]
Correctly named movie folders and files.  Radarr sees all the "other" files in the folder, but does not recognize the .avi extension as being the movie file.

**To Reproduce**
Checked folders and files with .avi extension.  They are shown as missing in Radarr.

**Expected behavior**
Radarr should recognize these files as existing and not download them again (and again and again)

**Screenshots**
Attached

**Desktop (please complete the following information):**
 - OS: Windows 10.  Radarr running on WHS 2011.  Files on Asustor NAS.

**Debug Logs**
Attached

![2019-09-29](https://user-images.githubusercontent.com/22886986/65835094-2b4b7e00-e2b0-11e9-8675-cdcd56a08862.png)

![2019-09-29 (3)](https://user-images.githubusercontent.com/22886986/65835117-52a24b00-e2b0-11e9-9ea0-d69dbde3c796.png)
[radarr.debug.2.txt](https://github.com/Radarr/Radarr/files/3667582/radarr.debug.2.txt)
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/3667583/radarr.debug.txt)
[radarr.debug.0.txt](https://github.com/Radarr/Radarr/files/3667584/radarr.debug.0.txt)
[radarr.debug.1.txt](https://github.com/Radarr/Radarr/files/3667585/radarr.debug.1.txt)

**Comment by Qstick** [comment]
Wait for the full refresh to finish, click refresh for just that movie, then send logs. Logs attached don’t show the import of this movie

**Comment by Starminder** [comment]
@Qstick - Hi, these are missing after an initial bulk import.

**Comment by Starminder** [comment]
Did another bulk add - one movie showed up "A Serbian Film (2010)"
[radarr.txt](https://github.com/Radarr/Radarr/files/3668315/radarr.txt)
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/3668316/radarr.debug.txt)
So - same as hundreds of others.  The folder is recognized.  The "other" files are recognized.  But Radarr thinks the movie (.avi) file is missing.

**Comment by fryfrog** [comment]
Turn logging up to trace, do the same thing Qstick said to do and then pastebin the whole chunk around the refresh. I've looked at a few individual movies that didn't detect like this in the past and honestly couldn't figure it out... but deleting and re-adding worked just fine. It was frustrating, but it only happen to ~5 out of 1000 movies, so I just lived w/ that solution. :(

**Comment by fryfrog** [comment]
Also, it doesn't help much but I did wonder if `.avi` was something Radarr accepted. I was *pretty* sure it did and I have a small handful of them in my library, so it must.

**Comment by Starminder** [comment]
There's absolutely no consistency.  It downloaded a bunch of dupes I already had, now it recognizes some but not others.  I turned off monitoring for anything I got a dupe for just to save my sanity.  I'll send a log soonest, once it seems like there is something specific to look for.

**Comment by Starminder** [comment]
[radarr.trace.0.txt](https://github.com/Radarr/Radarr/files/3680960/radarr.trace.0.txt)
[radarr.trace.1.txt](https://github.com/Radarr/Radarr/files/3680961/radarr.trace.1.txt)
[radarr.trace.2.txt](https://github.com/Radarr/Radarr/files/3680962/radarr.trace.2.txt)
[radarr.trace.3.txt](https://github.com/Radarr/Radarr/files/3680963/radarr.trace.3.txt)
[radarr.trace.4.txt](https://github.com/Radarr/Radarr/files/3680964/radarr.trace.4.txt)

Here are some more logs, there are a ton if you want more. :)
Saw anomalies with Ender's Game, The Apple Dumpling Gang Rides Again, the Beast of War, and the Bigamist this morning.  In some cases it downloaded a file, but then did not move it or rename it, in other cases it did but Radaar still says the movie is not there.

**Comment by Starminder** [comment]
On a side note:  Windows explorer reports 7,626 items.  Plex says 7,608 movies.  Radarr says 4,883.

**Comment by Qstick** [comment]
Logs seem to show runtime 0 detected by mediainfo, likely it’s related to this #764
