### ISSUE TITLE
Radarr cant get Video file due to folder have no year on it

### ISSUE THREAD

**Issue by dancingafro** [Radarr/Radarr#3797]
the video file cant get due to folder have no year on it.

example: 

Cell
->Cell.mp4
Chappie (2015)
->Chappie.mp4

Cell cant get video files
![example 1-1](https://user-images.githubusercontent.com/21032058/66036504-f6edf100-e53f-11e9-99e4-05e43b5a3b35.JPG)
![example 1-2](https://user-images.githubusercontent.com/21032058/66036519-fce3d200-e53f-11e9-8838-d85410c2b5eb.JPG)

But Chappie (2015) can get video file
![example 2-1](https://user-images.githubusercontent.com/21032058/66036525-040ae000-e540-11e9-9ba9-1ac582b14454.JPG)
![example 2-2](https://user-images.githubusercontent.com/21032058/66036526-0705d080-e540-11e9-9eea-ac1bd0f632e5.JPG)

**Comment by fryfrog** [comment]
Yeah, the folder and file will need the year.
