### ISSUE TITLE
API: need endpoint for manual search

### ISSUE THREAD

**Issue by georgemcc** [Radarr/Radarr#3798]
**Is your feature request related to a problem? Please describe.**
I'm having trouble figuring out how the API can return a list of manual search results for NZBs for a particular movie

**Describe the solution you'd like**
I'd like to have an API endpoint that returns a list of the NZB manual search results.  Similar to Sonarr's /release endpoint.

**Describe alternatives you've considered**
I tried Commands, MovieSearch but that doesn't return what I need.  

**Additional context**

**Comment by fryfrog** [comment]
Is this in Sonarr's v3? If so, it might come as part of the port of Sonarr's v3 -> Radarr.

**Comment by georgemcc** [comment]
I believe the API Endpoint for Sonarr is /release (https://github.com/Sonarr/Sonarr/wiki/Release).  Although the parameters for it are not well documented.  One would need the Sonarr episodeId as well as the seriesId to make it work.  It would be nice to be able to manually select a particular release and send it to the download client.

**Comment by Qstick** [comment]
Should be same in current Radarr, what response are you getting.

**Comment by Qstick** [comment]
Confirmed release endpoint is in current version and used by UI, so it works. Let us know how you are using it and we can offer support
