### ISSUE TITLE
Request - Log user authentication / failed logins

### ISSUE THREAD

**Issue by dannyhanes** [Radarr/Radarr#3799]
**Description:**
Please consider writing information about user authentication to the log file. Ideally the following should be logged. 

* User [username] logged in
* Incorrect password for user [username]
* Failed login  for username: [username] not found

I am using Zabbix to monitor my other servers and I am parsing the logs to get notifications about failed / successful logins. This would help ensure that if there is a break-in attempt, I am notified.

**Comment by fryfrog** [comment]
I think Sonarr recently got something for fail2ban, that could make it over to Radarr's v2 maybe?

**Comment by Qstick** [comment]
Already in Aphrodite
