### ISSUE TITLE
add VFi in search of the French language

### ISSUE THREAD

**Issue by Floflobel** [Radarr/Radarr#3800]
Hello,
I have a movie that doesn't want to download automatically for the following reason: "French is wanted, but found English".
My language is set to French but it doesn't detect VFi and thinks it's English.

Example movie name: "Vert.Emeraude.2016.VFi.1080P.mHD.X264.AC3-ROMKENT"

VFi (International French version) = VFF = Truefrench

Is it possible to add this tag to the search list?

Best regards,

**Comment by fryfrog** [comment]
Kind of related to #3337 and #3296.

**Comment by Qstick** [comment]
Added to Aphrodite: 5f396a53c3d55cb95ea7ae93622555748fb02298
