### ISSUE TITLE
Radarr reports wrong time in the UI - Time zone/daylight savings issue..?

### ISSUE THREAD

**Issue by 4C3T** [Radarr/Radarr#3809]
**Describe the bug**
For some reason it's displaying events one hour ahead of the actual hour
This I noticed under a movie that had been downloaded under history tab in the column Date.
I can't find any settings for time zones, so I can only assume that either I've missed something, or there's a bug somewhere.
I'm located in Sweden and we're on daylight savings time, and otherwise we're at +1 hour CET, I think. Not sure about which zone, but Stockholm is always referenced for time adjustments.

So, I'm hoping anyone could clarify why I'm having this issue..?

**I have Radarr version 0.2.0.1358 - Jun 29 2019 installed**

**Desktop (please complete the following information):**
 **- OS: Windows 10.0.18362.388
![Weird times](https://user-images.githubusercontent.com/29127941/66402370-05775500-e9e5-11e9-827d-c178559ba41d.PNG)
**
 
 - Browser and Version [e.g. chrome, safari] (Only needed for UI issues)
**-Firefox 69.0.2 (64-bits)**

Thank you

**Comment by fryfrog** [comment]
I assume you're sure your time zone and dst and time are all set correctly?

**Comment by 4C3T** [comment]
Sorry, sorry, completely forgot to answer you... If you mean in my OS, so yes. It's Windows 10 so it does this automatically.
If you mean in Radarr - Where the hell are those settings??? I can't find them

**Comment by fryfrog** [comment]
No timezone settings in Radarr, it'll come from the system. Your screen shot doesn't really show the time is wrong, btw. Just that when you took the screen shot it was 15:54 and when it imported it was 04:23.

**Comment by 4C3T** [comment]
Well, it took me a while until I noticed it, and also took a while for me to make the write the post and then making the screen shot (I was busy with other stuff - Had a ton of stuff running).
But the time was off non the less. By an hour.
