### ISSUE TITLE
Ignore additional tags in movie folder/filenames once the movie has been matched

### ISSUE THREAD

**Issue by c0rnflake** [Radarr/Radarr#381]
Ignore additional tags in movie folder/filename once the movie has been match ie.

##th.Anniversary, #in#, Alternate.Ending, DC, Directors.Cut, DL, DOCU, EXTENDED, INTERNAL, LIMITED, MULTI, PROPER, PRODUCERS.CUT, REMASTERED, REPACK, RERIP, The.Ultimate.Cut, Theatrical, Theatrical.Cut, UNCUT, UNRATED, WS

**Comment by galli-leo** [comment]
Can you verify that this is still a problem on the latest version of Radarr? This should be fixed by now.

**Comment by c0rnflake** [comment]
No longer an issue 👍
