### ISSUE TITLE
Multiple downloads for same torrent (unresolved #2794)

### ISSUE THREAD

**Issue by austinwbest** [Radarr/Radarr#3810]
So the previous bug (originally from 5/2018) that still had activity as of 6 months ago is still an issue. I added 8 movies and ended up with 31 torrents downloading. Some had 4 and 5 versions of the same movie!

One thing i did notice as the last comment on #2794 mentioned, not a single one of those 31 had the radarr label.

I deleted them ALL and added just one, and it worked perfect. It found 1 copy, labeled it as radarr and processed.

The first time there was a process running though which may have had something to do with it. Radarr was processing 14 movies from the Wanted section and was on 10/14 when i then added the 8 new movies (Add Movie > Search for it > Click Add + Search). So possibly while the system is running the wanted process it mis-handled the new ones or throwing 8 movies at it in to fast of succession caused the issue? I'm not sure. 

Either way, this is still an issue.

Radarr Ver. 0.2.0.1358
develop

**Comment by austinwbest** [comment]
OS is Windows 10 by the way..

Error log...
`[v0.2.0.1358] NzbDrone.Core.Download.Clients.DownloadClientException: Unable to connect to Deluge, please check your settings ---> System.Net.WebException: The request was aborted: The operation has timed out.`

Log file is basically that over and over. So it cant connect to Deluge but yet it successfully sent & added all 8 movies 31 times total.

**Comment by Qstick** [comment]
Closing as duplicate, will reopen old
