### ISSUE TITLE
Browser crashes when trying to download logs. 

### ISSUE THREAD

**Issue by tehniemer** [Radarr/Radarr#3811]
**Describe the bug**
When the link to a debug log is right clicked to "save link as" the browser crashes

**To Reproduce**
1. Go to logs
2. Right click on one of the log download links
3. Scroll down to "save link as"

**Expected behavior**
Logs can be downloaded through the browser dialog.

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser and Version: Firefox 69.0.2
 - Version 2.0.0.2090

**Debug Logs**
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/3707571/radarr.debug.txt)

**Comment by Qstick** [comment]
I get no error, works fine for me. What error are you seeing?

**Comment by tehniemer** [comment]
I don't get an error in radarr, the browser crashes and has to be restarted after the save dialog box pops up. This behavior seems to be specific to radarr, going through the same motions in sonarr or lidarr doesn't cause it.

**Comment by Qstick** [comment]
Closing, as this works fine for me in Firefox 69.0.3 and latest chrome.
