### ISSUE TITLE
Radarr not seeing soft-link (symlink) movies create by filebot

### ISSUE THREAD

**Issue by Teslenkon** [Radarr/Radarr#382]
Movie was successfully downloaded, but Radarr is still telling me in red text 'missing' for that movie after a few refreshes. Here is the log for it: 
[https://imgur.com/a/VZIcy](url)

I have 'completed download handler' and 'Drone Factory' both disabled because I have filebot setup with my seedbox/stream-box to automatically do all that for: torrents snatched myself, Sonarr and now Radar. Talking in Discord Support Chat I found out that Radarr might have issues with recognizing symlinks.

Here is the file structure I am using:
Download location: ~/torrents/data/
Media/symlink location: ~/media/Movies/

**Comment by kai23** [comment]
Hi, I get the exact same error, how did you do Teslenkon ?

**Comment by Teslenkon** [comment]
Sorry, haven't used radarr in many months. I don't remember if I fixed this or not. Sorry I can't be of more help.
