### ISSUE TITLE
Radarr lost activity list... Sort of

### ISSUE THREAD

**Issue by 4C3T** [Radarr/Radarr#3820]
**Describe the bug**
Hi.
I just restarted Radarr since it behaved a little sluggish. This was done via the UI, so I wasn't expecting any loss of data. I thought so somewhere in the back of my mind anyways.

Strangest thing happened; After reloading the Activity page I found this totally void of any info. Which is normal, for everything from a few seconds to about a minute perhaps.
I waited several minutes - Nothing.
I went to "System" and tasks, and clicked a few, hoping to kick-start it a bit.
Still nothing. Checked the logs and didn't find anything that would indicate an error or 50.
But, since I also have Kodi, and having Radarr report sending update info to it, it started to chime about something.
I looked and sure enough, a finished movie download was reported and it started to update it's list.
A look at the logs indicated that it had indeed done something:

> Linking [xxx.xyz.xyz.1234.1080p.BluRay.H264.AAC-RARBG.mp4] > [[xyz xyz xyz (1234)][tt1234567, 708]]

And.... Nevermind.... It just got it's sh!t together and plastered the whole list where it's supposed to be. Only took about 15 minutes for it to do this...

This can't be normal???

Granted, my machine has been up for 9 days now, restart pending from Windows bleeding Update, CPU-load 80-100% for at least a day.
Got 2x4 Core Xeon-processors, 32 GB of RAM and plenty of juice left for other programs.
Occasionally a bit slow, but usually it's only for a few seconds before it's operating normally.

Meh... Computers can drive one nuts, that's for damn sure!

**Comment by fryfrog** [comment]
The Activity view comes from your download client(s), the minutely-ish download client scan.
