### ISSUE TITLE
Can't add Torznab indexer to V2.0.0.2096

### ISSUE THREAD

**Issue by BinsonBuzz** [Radarr/Radarr#3821]
**Describe the bug**
I can't add a torznab indexer from nzbhydra2.  It works fine in older versions of radarr (and the sonarr beta). When I click check it always fail.

I've also tried with Jackett so the problem isn't related to nzbhydra2.

**To Reproduce**
- add new custom torznab, enter url and API and click check.

**Expected behavior**
Successful new indexer
I'm running linuxerver docker on unraid 

Version 2.0.0.2096
Mono Version 5.20.1.34
Docker True
DB Migration 156

[radarr.debug.txt](https://github.com/Radarr/Radarr/files/3733590/radarr.debug.txt)

**Comment by Qstick** [comment]
Same as #3713
