### ISSUE TITLE
Completed backup job ID does not match what's returned when backup job is kicked off

### ISSUE THREAD

**Issue by fender4645** [Radarr/Radarr#3826]
**Describe the bug**
If you kick off a backup using the API, the returned json has an 'id' property. When you then query the /api/system/backup endpoint to get info on the completed backup(s), the ID is different in the returned payload.

**To Reproduce**
1. Initiate a backup using the following curl command: curl -H "X-Api-Key: <my_api_key>" -H 'Content-type: applicaiton/json' -X POST --data '{"name": "Backup"}' "https://my_url/api/command"
2. In the returned json, note the value of the "id" key
3. Run the following curl command to get info on the known backups: curl -H "X-Api-Key: <my_api_key>" -H 'Content-type: applicaiton/json' -X GET https://my_url/api/system/backup
4. Note that in the returned json from the above command, the "id" in the completed backup is different than what was in the initial returned json.

This makes it difficult to find the actual backup that you initiated.

**Expected behavior**
The "id" key should be consistent from initiation to completion.

**Returned Payloads**
***When Backup is Initiated***
    {
        "name": "Backup",
        "body": {
        "type": "manual",
        "sendUpdatesToClient": true,
        "updateScheduledTask": false,
        "completionMessage": "Completed",
        "name": "Backup",
        "trigger": "manual"
      },
      "priority": "normal",
      "status": "queued",
      "queued": "2019-10-17T16:15:53.130783Z",
      "trigger": "manual",
      "state": "queued",
      "manual": true,
      "startedOn": "2019-10-17T16:15:53.130783Z",
      "sendUpdatesToClient": true,
      "updateScheduledTask": false,
      "id": 387130
    }
***When Backup is Completed***
{
    "name": "radarr_backup_2019.10.17_16.15.53.zip",
    "path": "/backup/manual/radarr_backup_2019.10.17_16.15.53.zip",
    "type": "manual",
    "time": "2019-10-17T16:15:53.800546Z",
    "id": 219804115
  }

**Desktop (please complete the following information):**
N/A

**Comment by Qstick** [comment]
Radarr version?

**Comment by Qstick** [comment]
Also you are looking at two different things, the payload returned from the first is a command, thus you are seeing the command id. The second is the actual backup. You are not going to get the backup id from the command call given it hasn't actually run the backup command yet and added to the DB.
