### ISSUE TITLE
Custom Format Regex doesn't match '+' (plus)

### ISSUE THREAD

**Issue by jluce50** [Radarr/Radarr#3827]
**Describe the bug**
When creating a Custom Format, trying to match a release with '+' in the name doesn't work. 

**To Reproduce**
1. Create a new "Custom" Custom Format.
2. Enter a tag with something like "C_RX_DTS\\-?(HD|X)|DD(\\+|P)(5|7)".
3. Enter "A.Movie.2018.Directors.Cut.2160p.UHD.BluRay.REMUX.HDR.HEVC.DD+7.1.EPSiLON" for the Release Title.
4. Click Test

**Expected behavior**
Results should show a match. Changing "DD+" to "DDP" in the Release Title will produce a match. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser and Version: Chrome 77.0.3865.120
 - Version: 0.2.0.1358

**Debug Logs**
I don't believe there's anything helpful in the log, but I uploaded in just in case.
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/3741231/radarr.debug.txt)

**Comment by Qstick** [comment]
I was able to reproduce this in the edit modal, however if you go ahead and add it and test in main testing area it seems to work. I think it should also work in practice. Seems to an issue with just the test function in the edit dialog

**Comment by jluce50** [comment]
I did some further testing and you are correct. The problem does seem to be limited to the edit dialog.

**Comment by vertan** [comment]
Hello! I'd like to try and work on this.

**Comment by Qstick** [comment]
Sure thing @vertan

**Comment by vertan** [comment]
Kept it simple in this [PR](https://github.com/Radarr/Radarr/pull/3839), but it fixes the problem!

**Comment by ta264** [comment]
The testing stuff will be removed in Aphrodite in favour of a simpler UI
