### ISSUE TITLE
Main Movie Page does not dynamically update

### ISSUE THREAD

**Issue by chipsharpdotcom** [Radarr/Radarr#3828]
When browsing the main movie listing page, if a scan is performed and a movie file is found by the scanner, the 'Missing'/'Downloaded' tag does not dynamically update. It requires that a full page refresh be performed. (Or browse to another page and come back...essentially the same thing.) 

This may not be an actual bug, and could possibly just be the way things are, and that's ok. It's a minor thing at worst, but I wanted to report it nonetheless. 

--C#

**Comment by Qstick** [comment]
Please fill out the bug report template with all info
