### ISSUE TITLE
[Aphrodite] add root path

### ISSUE THREAD

**Issue by TRaSH-** [Radarr/Radarr#3834]
Add root path to the Movie title screen like Sonarr has.
![image](https://user-images.githubusercontent.com/6155095/67496249-67d68380-f67c-11e9-9cf8-1f9bab493b2c.png)

As suggestion where to place it you might merge the links to one location like Sonarr has if you think it's getting to cluttered.
But I let that option to the dev/designers

**Comment by onedr0p** [comment]
Done in commit 
https://github.com/Radarr/Radarr/commit/99509e61d38c5539675a37e8694abea7aab1d4bc

**Comment by onedr0p** [comment]
Added Year next to title too

![image](https://user-images.githubusercontent.com/213795/68088104-ac56e180-fe29-11e9-8db0-9cf64b01f4f2.png)
