### ISSUE TITLE
Move movie editor to the dropdown list 

### ISSUE THREAD

**Issue by TRaSH-** [Radarr/Radarr#3835]
move movie editor to the dropdown list like Sonarr so you can set also another selected preferred view (for normal movie view posters and for movie editor the table list being that folder view in my opinion is useless when you want to edit something)

![image](https://user-images.githubusercontent.com/6155095/67497064-b0db0780-f67d-11e9-925e-5b13ec7a5b90.png)

[AB#882](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/882)

**Comment by Qstick** [comment]
This needs to a discussion, not sure I'm totally for this. Are you just wanting it to save the view default for editor vs index mode?
