### ISSUE TITLE
[Aphrodite] please don't Deprecated Custom Format Tags Type "M_" and "S_" 

### ISSUE THREAD

**Issue by TRaSH-** [Radarr/Radarr#3838]
Reading the wiki and i noticed some Custom Format Tag Type will be Deprecated.

**Is your feature request related to a problem? Please describe.**

I use the following custom formats tags `M_N_REMUX` and `S_N_WEBDL` as a part of my full custom format.

![image](https://user-images.githubusercontent.com/6155095/67510510-65ccee80-f695-11e9-942f-1f11cee2f3cb.png)

I used this option so it would mark certain releases as BR-DISK and would be ignored.
BR-DISK in the filename is actually hardly used anymore for a full bluray disc.
If removed Radarr would see this as a bluray-1080p and download it.

![image](https://user-images.githubusercontent.com/6155095/67510711-c0664a80-f695-11e9-9dbe-30f3093b8ec4.png)

**Describe the solution you'd like**

If this Custom Format Tag Type wouldn't be removed the following will happen

![image](https://user-images.githubusercontent.com/6155095/67510806-eb509e80-f695-11e9-8cba-d6fe51ee11c5.png)

And it will be ignored and not downloaded.

**Describe alternatives you've considered**

I've considered playing with the filesize.
But changing the file size doesn't work.
Because I've seen small factor BR-DISK and also 20GB+ bluray-1080p

**Additional context**

All added above

**Comment by Qstick** [comment]
I'm not sure what the plan was for why this was being depreciated, but as of now I have no intention to depreciate it

**Comment by Qstick** [comment]
Looking closer at this those releases, wouldn’t this custom format work the same if you only had the first part and not the m_n_remux? What’s the point in the m modifier use?

**Comment by TRaSH-** [comment]
No because a remux has those codecs in it.
So then those would be ignored also if you want remuxes
In the meanwhile I even added another custom format tag to it being that we're getting WEB-DL from streaming sites with HEVC in the release name.
Will edit my first post tonight

**Comment by TRaSH-** [comment]
Tested it with `C_N_REMUX` and that doesn't work,
I also added the extra tag we added because of the new 4k streaming services in the opening post.

**Comment by Qstick** [comment]
Closing as there is no plan to do this right now.

**Comment by reloxx13** [comment]
why is it marked as deprecated in the wiki?
the available list is also missing in wiki :/
