### ISSUE TITLE
Synology port installed as :8310, but docs say it should be :7878

### ISSUE THREAD

**Issue by brandonscript** [Radarr/Radarr#3842]
**Describe the bug**
When installing the native Synology package (20190320-8), for some reason it installed under port :8310 - had to go digging in the log to find that. Not sure if this is dynamically assigned or not, but it is not on par with :7878 from the docs. If it's a static port for Synology, worth updating the documentation or the Synology package readme?

**Comment by fryfrog** [comment]
This will be on the Synology packager, you'll need to figure out how the heck to contact them.

Honestly, on Synology I strong suggest using Docker. And to avoid their Docker, I'd probably run an Ubuntu VM, let it get a LAN IP and run Docker on *that*.
