### ISSUE TITLE
On import (not from downloader) doesn't read or set qualities auto on preview (aphrodite)

### ISSUE THREAD

**Issue by Prolesious** [Radarr/Radarr#3849]
**Describe the bug**
On file import, the quality of movies is not being read and defaults to 1080p hdtv.
**To Reproduce**
Remux a movie (ie use MKVTOOLNIX) to a separate directory.
Go run import on the directory (selecting manual import)
doesn't fill in quality settings so have to select them manually.

**Expected behavior**
Importing should parse the file name to pick up it's quality, ie bluray remux 1080p

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Mono Version: .NET Core - Yes  doesn't tell me what version, sorry)
 - Browser and Version [e.g. chrome, safari] (Only needed for UI issues)

**Debug Logs**

19-11-1 03:55:33.7|Debug|QualityParser|Trying to parse quality for A Movie.2018.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-FGT
19-11-1 03:55:33.7|Debug|ParsingService|Quality parsed: Remux-1080p v1 (Surround, Best, Good Surround)
19-11-1 03:55:36.1|Debug|Api|[POST] /api/v2/command: 201.Created (13 ms)
19-11-1 03:55:36.1|Debug|Parser|Parsing string '2 Fast 2 Furious (2003) - [BLURAY-1080P][DTS-HD.MA. 5.1][X265][tt0322259].mkv'
19-11-1 03:55:36.1|Debug|Parser|Movie Parsed. 2 Fast 2 Furious - 2003 
19-11-1 03:55:36.1|Debug|VideoFileInfoReader|Getting media info from /import/2 Fast 2 Furious (2003) - [BLURAY-1080P][DTS-HD.MA. 5.1][X265][tt0322259].mkv
19-11-1 03:55:36.1|Debug|AggregateLanguage|Using language: English
19-11-1 03:55:36.1|Warn|QualityFinder|Unable to find exact quality for UNKNOWN,  R1080P, and NONE. Using HDTV-1080p as fallback
19-11-1 03:55:36.1|Debug|AggregateQuality|Using quality: HDTV-1080p v1 (None)
19-11-1 03:55:36.1|Debug|ImportApprovedMovie|Decisions: 1
19-11-1 03:55:36.1|Debug|MovieService|Detaching movie 1 from file.
19-11-1 03:55:36.1|Debug|MovieFileMovingService|Moving movie file: /import/2 Fast 2 Furious (2003) - [BLURAY-1080P][DTS-HD.MA. 5.1][X265][tt0322259].mkv to /movies/2 Fast 2 Furious (2003)/2 Fast 2 Furious (2003) - [HDTV-1080P][DTS. 5.1][X265][tt0322259].mkv
19-11-1 03:55:36.1|Debug|DiskTransferService|Move [/import/2 Fast 2 Furious (2003) - [BLURAY-1080P][DTS-HD.MA. 5.1][X265][tt0322259].mkv] > [/movies/2 Fast 2 Furious (2003)/2 Fast 2 Furious (2003) - [HDTV-1080P][DTS. 5.1][X265][tt0322259].mkv]
19-11-1 03:55:36.1|Debug|RecycleBinProvider|Attempting to send '/movies/2 Fast 2 Furious (2003)/2 Fast 2 Furious (2003) - [BLURAY-1080P][DTS-HD.MA. 5.1][X265][tt0322259].png' to recycling bin

**Comment by Qstick** [comment]
Same as #3758
