### ISSUE TITLE
[Aphrodite] Mass delete movies from Movie editor doesnt work

### ISSUE THREAD

**Issue by babos123** [Radarr/Radarr#3851]
I was start testing Traktarr and i mess up adding 10000 movies to radarr.
Trying to delete them from movie editor didnt work.
I was able to select all those movies and press delete and then in the next windows i check Also delete folder and files and again i pressed delete. Then it goes to previous windows without doing anything or deleting the movies.

Ubuntu 18.04.3 LTS

**Debug Logs**
Trying to solve this problem i try to downgrade to previous version and i mess up.
So now i have the old radarr version from backup. I only have aphrodite 

log from last night.
I deleted logs and i enable degub log and i reproduce all above steps.
Hope it helps.....
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/3800330/radarr.debug.txt)

**Comment by Qstick** [comment]
Thanks, what version are you on?

**Comment by babos123** [comment]
sorry dont remember i remove aphrodite and install old redarr.
Propably the latest cause i first install a week ago.
Version
2.0.0.2140  ???

**Comment by Qstick** [comment]
I can't reproduce this, delete from editor works fine for me.

**Comment by robert-corlett** [comment]
Definitely reproducible here on aphrodite v3.0.0.2910. I can't delete more than 500 movies at once. Am trying to delete missing movies that I dont want in the database any longer. The error that we are getting is:

```
Status Code: 	**414 URI Too Long**

Request URL: 	http://192.168.29.177:7878/api/v3/movie/editor?movieIds=20547&movieIds=20574&...and so on for 2870 movies in total…&deleteFiles=false&addNetImportExclusion=false

Form Data: 	{"movieIds":[20547,20574,20578,20580,20582,20586,20590...and so on for 2870 movies in total…],"deleteFiles":false,"addNetImportExclusion":false}: 

Request Method: 	DELETE
Status Code: 		**414 URI Too Long**
Remote Address: 	192.168.29.177:7878
Referrer Policy: 	no-referrer-when-downgrade
Connection: 		close
Content-Length: 	0
Date: 				Wed, 06 May 2020 19:43:32 GMT
Server: 			Kestrel
Accept: 			application/json, text/javascript, */*; q=0.01
Accept-Encoding: 	gzip, deflate
Accept-Language: en-US,en;q=0.9
Connection: 		keep-alive
Content-Length: 	17284
Content-Type: 		application/x-www-form-urlencoded; charset=UTF-8
Cookie: 			Auth-Type=form; Auth-Token=FVrcSbIGDn64XVAT9z9jhzVX11Ag7a1LuBOWfQVXe2GHvuGi; SID=rrDWBj4pHmsD3BhjklyU4pv43LQLW8lH; 
Host: 				192.168.29.177:7878
Origin: 				http://192.168.29.177:7878
Referer: 			http://192.168.29.177:7878/
sec-ch-ua: 		"Google Chrome";v="83"
sec-ch-ua-mobile: ?0
Sec-Fetch-Dest: 	empty
Sec-Fetch-Mode: 	cors
Sec-Fetch-Site: 	same-origin
User-Agent: 		Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.7 Safari/537.36
X-Api-Key: 		********************************
X-Requested-With: XMLHttpRequest
```

**Comment by Qstick** [comment]
The movieIds shouldn't be appended to the URL anymore, but instead sent only in form data.. I'll look back at this to make sure I didn't botch something on the fix.

**Comment by Qstick** [comment]
This change clearly removes the query parameters, so I'll have to test. You have tried in incognito, or with cache cleared?

9ccdb4871d626068e0ef2425dd45e23e0811d0a9
