### ISSUE TITLE
Please fix Manual Import to match as good as Bulk Import Movies matches

### ISSUE THREAD

**Issue by douglas24** [Radarr/Radarr#3855]
**Is your feature request related to a problem? Please describe.**
When I have a bunch of movies that I want to add to my existing library, I will use Bulk Import Movies and nearly all get a match and added. I then edit my library so that the newly added movies have the same location as my current library (instead of split between two different library folders). I then use Manual Import to import those new movies so radarr moves/renames them into the current library location.

**Describe the solution you'd like**
When using Manual Import, a lot of the movies (30-40%) fail to find a match despite having been matched successfully with Bulk Import Movies. I'm not sure why one works better at matching than the other, but could Manual Import be fixed so that it works the same as/as well as whatever mechanism is used for Bulk Import Movies?

**Describe alternatives you've considered**
I don't know of any alternative besides letting Manual Import continue to function worse than how Bulk Import Movies works for matching.

**Additional context**
A quick fix to Manual Import would be to make it use the same matching mechanics that Bulk Import Movies uses. I'm really not sure why Manual Import is less successful at matching movies to existing movies/names in the library.

**Comment by Qstick** [comment]
Need specific examples, logs, and version info

**Comment by Qstick** [comment]
Closing for lack of info
