### ISSUE TITLE
Support automatically downloading trumped movies

### ISSUE THREAD

**Issue by dippynark** [Radarr/Radarr#3856]
**Is your feature request related to a problem? Please describe.**
My torrent client (rtorrent) often reports errors such as `Unregistered torrent: Trump: ...` when a torrent has been replaced on a particular tracker and provides the URL for the new download

**Describe the solution you'd like**
I would like to be able to tell Radarr to download the new file and delete the unregistered torrent

**Describe alternatives you've considered**
I have tried parsing the URL of the new torrent and uploading it manually to the torrent client, but this doesn't scale well for multiple indexers and I feel should be handled by Radarr to not reimplement logic that is already there

**Comment by bakerboy448** [comment]
Closing
v0.2 is no longer being actively developed.

If this is still an issue/request on recent v3 builds, please open a new issue.
