### ISSUE TITLE
thexem -- erronous hits

### ISSUE THREAD

**Issue by thezoggy** [Radarr/Radarr#386]
I'm seeing the radarr useragent hitting thexem.. which is odd since xem is used for tv series nothing to do with movies... I assume you just have old code left in causing this.

`[22/Jan/2017:23:37:38 +0000] "GET /map/allNames?seasonNumbers=True&origin=tvdb HTTP/1.1" 200 55038 "-" "Radarr/0.2.0.134 (Linux 4.4)"`

**Comment by galli-leo** [comment]
Yep we do. Is this a major problem?

**Comment by thezoggy** [comment]
as radarr is for movies... seems pretty pointless to hit xem for tv stuff?

**Comment by hotio** [comment]
Maybe they should add some Movie stuff? :)

**Comment by thezoggy** [comment]
I have no plans to add movies to xem

**Comment by thezoggy** [comment]
this isnt resolved.. keep this open until XEM is removed from radarr..

**Comment by onedr0p** [comment]
That is prolly because of older versions of radar that people are still running.

**Comment by onedr0p** [comment]
With that said I've removed Xem form the source code just in case.
