### ISSUE TITLE
Not a UX guy, favorite icon is distorted on bookmarks bar

### ISSUE THREAD

**Issue by garlandkr** [Radarr/Radarr#3862]
So, I'm not into UX at all but adding Radarr to my favorites in Chrome distorts the icon in my bookmarks bar. Sonarr's icon looks fine for example.

<img width="59" alt="Screen Shot 2019-11-04 at 3 46 55 PM" src="https://user-images.githubusercontent.com/44636/68157174-29ae4f00-ff1b-11e9-8b05-afb745a80710.png">

**Comment by hotio** [comment]
This is not a bug, just an optical illusion.

<img width="1000" alt="68157174-29ae4f00-ff1b-11e9-8b05-afb745a80710" src="https://user-images.githubusercontent.com/26902309/69491848-34655f80-0e9b-11ea-8023-b1c05004aeab.png">
