### ISSUE TITLE
Blacklisting a Release DOES NOT BLACKLIST A RELEASE...

### ISSUE THREAD

**Issue by MikeFalcor** [Radarr/Radarr#3863]
As the title states, blacklisting a release, does not, in fact, blacklist the RELEASE. Sure, perhaps it MAY not download the same torrent from the exact same indexer, but blacklisting a RELEASE, by definition, should blacklist ANY torrent with the same name.

**To Reproduce**
1. Blacklist any release.
2. Search for same movie.
3. Watch as same release from another index starts downloading.

**Expected behavior**
If I blacklist, say "A.Host.of.Sparrows.2018.1080p.WEB.H264-OUTFLATE", I should NEVER have to verify that the exact same torrent from another index would still download,

**Screenshots**
![Blacklist](https://user-images.githubusercontent.com/11777545/68176919-73a72d00-ff3b-11e9-852b-2571ab433255.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 1903 (Latest Updates)
 - Version: 0.2.0.1358

**Debug Logs**
*ATTACHED*
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/3807167/radarr.debug.txt)

Thanks for your help!

**Comment by fryfrog** [comment]
I wouldn't be surprised if *torrents* are blacklisted by torrent hash, not name. It makes sense too, since you might blacklist a torrent for multiple reasons. Too few seeders could be solved w/ the same torrent w/ a different hash. :/

**Comment by MikeFalcor** [comment]
> 
> 
> I wouldn't be surprised if _torrents_ are blacklisted by torrent hash, not name. It makes sense too, since you might blacklist a torrent for multiple reasons. Too few seeders could be solved w/ the same torrent w/ a different hash. :/

If that were the case, then I believe an option should be presented when blacklisting 'releases' OR the option should not be called that - Blacklist TORRENT instead.

Perhaps splitting the option would be best: A toggle for blacklisting the torrent AND a toggle for blacklisting the release (which would then prevent the same torrent NAME).

**Comment by TheFrenchGhosty** [comment]
The problem is still here... It's even destroying the whole point of using Radarr since I have to check everyday if a release had enough seeders to be downloading... It's literally easier to manage everything by hand.

The problem is even worse because after it's been added to the blacklist 2-3 times, it will try to get another release but keeps adding the blacklisted one.

See this gif:

![bug](https://user-images.githubusercontent.com/47571719/75708897-995dfc00-5cb9-11ea-8d54-e61c766c2c4e.gif)

**Comment by fryfrog** [comment]
Can you capture some trace level logs of it happening?

**Comment by TheFrenchGhosty** [comment]
There is nothing in the log:

```
2020-3-2 20:04:39.5|Info|MovieService|Adding Movie [The Terror (1963)][, 31655] Path: [/path/to/media/The Terror (1963)]
2020-3-2 20:04:39.5|Info|RefreshMovieService|Updating Info for The Terror
2020-3-2 20:04:41.1|Warn|MediaCoverMapper|File /var/lib/radarr/MediaCover/389/poster.jpg not found
2020-3-2 20:04:42.4|Info|NzbSearchService|Searching 7 indexers for [The Terror]
2020-3-2 20:04:54.6|Info|DownloadDecisionMaker|Processing 36 releases
2020-3-2 20:04:54.6|Warn|AcceptableSizeSpecification|[The Terror (1963)][, 31655] has no runtime information using median movie runtime of 110 minutes.
2020-3-2 20:05:11.1|Info|DiskScanService|Scanning disk for The Terror
2020-3-2 20:05:11.1|Info|MovieScannedHandler|[The Terror] was recently added, performing post-add actions
2020-3-2 20:05:11.1|Info|MediaCoverService|Testing: NzbDrone.Core.Messaging.Commands.CommandQueueManager, 389
2020-3-2 20:05:11.2|Warn|MediaCoverMapper|File /var/lib/radarr/MediaCover/389/fanart.jpg not found
2020-3-2 20:05:11.2|Info|NzbSearchService|Searching 7 indexers for [The Terror]
2020-3-2 20:05:11.2|Warn|MediaCoverMapper|File /var/lib/radarr/MediaCover/389/poster.jpg not found
2020-3-2 20:05:11.2|Info|MediaCoverService|Downloading Poster for [The Terror (1963)][tt0057569, 31655] http://image.tmdb.org/t/p/original/ryAszNMDEQqlRdqwEYiELpKog36.jpg
2020-3-2 20:05:27.9|Info|MediaCoverService|Downloading Fanart for [The Terror (1963)][tt0057569, 31655] http://image.tmdb.org/t/p/original/1WVAOJv6FDurj0TklTMyAIQK8jZ.jpg
2020-3-2 20:05:28.0|Info|MetadataService|Movie folder does not exist, skipping metadata creation
2020-3-2 20:05:35.3|Info|DownloadDecisionMaker|Processing 85 releases
2020-3-2 20:05:36.3|Info|DownloadService|Report sent to Deluge. The.Terror.1963.Bluray.1080p.DTS-HD-2.0.x264-Grym
2020-3-2 20:05:36.4|Info|MovieSearchService|Movie search completed. 1 reports downloaded.
2020-3-2 20:06:56.8|Info|NzbSearchService|Searching 7 indexers for [The Terror]
2020-3-2 20:07:21.3|Info|DownloadDecisionMaker|Processing 85 releases
2020-3-2 20:07:22.4|Info|DownloadService|Report sent to Deluge. The.Haunting.1963.1080p.BluRay.X264-AMIABLE [PublicHD]
2020-3-2 20:07:22.4|Info|MovieSearchService|Movie search completed. 1 reports downloaded.
2020-3-2 20:07:24.5|Info|NzbSearchService|Searching 7 indexers for [The Terror]
2020-3-2 20:07:48.7|Info|DownloadDecisionMaker|Processing 90 releases
2020-3-2 20:07:49.8|Info|MovieSearchService|Movie search completed. 0 reports downloaded.```

**Comment by fryfrog** [comment]
So you've added some torrents to the blacklist in the past, you *remove* `The Terror (1963)` entirely, re-add it and re-search for it and it just snatches the same Blacklisted torrent?

**Comment by TheFrenchGhosty** [comment]
No:

- I add a Movie
- Radarr find a release
- I blacklist this release
- Redarr will add this release again even though it's blacklisted + (not everytime) it will get another release

**Comment by TheFrenchGhosty** [comment]
I just did some more testing:

It looks like it's not reading the torrent in the client, it's only reading it to radarr but looks like it's correctly adding a new release to both radarr and the torrent client everytime.
