### ISSUE TITLE
Allow processing movie packs added manually in download client

### ISSUE THREAD

**Issue by ejalal** [Radarr/Radarr#3866]
**Is your feature request related to a problem? Please describe.**
I'm trying to upgrade a whole bunch of movies manually and most of the time I find the best sources like 
```
The Lord of the Rings Trilogy Extended Complete 1080p BluRay x264 AAC 5 1-POOP
The Hobbit Complete Trilogy Extended [10GB][Selective Download][1080p H265][MP3 5.1 Ch]
Whatever Quadrilogy, Petalogy thing...
```
Well, the problem with this is that Radarr can't link the completed movies to their matches in Radarr, I know that linking all movies while they are being downloaded is propably impossible, but at least link them once they are all downloaded by scanning the completed folder.

**Describe the solution you'd like**
Radarr should scan all downloads tagged with "radarr" tag and try to process them even if it can't link the downloaded torrent to a single known movie.

**Describe alternatives you've considered**

**Additional context**

[AB#878](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/878)

**Comment by fryfrog** [comment]
In the mean time, you can either queue up individual movies in your download client w/ the category you use for Radarr *or* use Wanted -> Manual Import on the folder after download.

This is such a niche use case, I don't think I'd hold my breath for it ever becoming a feature.

**Comment by onedr0p** [comment]
What savages package movies that way? Like you said Radarr only knows there's at most 1 movie file and some extra files like subs in a single download.

You can filter out `Trilogy` keyword and you shouldn't get those auto downloaded anymore.

**Comment by ejalal** [comment]
I totally agree with you guys, I could totally sort them out with filebot but I like the way it's done with Radarr by creating hardlinks instead of moving the files (so I can keep them shared)
Any ways, it could be a nice feature to have.

**Comment by talondnb** [comment]
Even an additional setting on the Wated > Manual Import page to periodically perform a manual import of the defined movie folder, i.e. Enable periodic scan of folder, default 5 minutes.

**Comment by jonathan-dejong** [comment]
There are closed trackers that create these kind of "packs" which become free leech and are encouraged to download instead of standalone movies (usually a movie franchise). 

Right now there's not way for me to get a download like that started in radarr. I don't think this is such an edge case tbh :)

**Comment by GordonFreemanK** [comment]
If what you care about is the hard linking, in case you're looking for a workaround it's no magic, you can do it yourself: download the pack manually, then for each downloaded movie file:
- go to bash, run `ln <path-to-downloaded-movie-file.xxx> <path-to-radarr-individual-movie-folder\whatever_name.xxx>`
- delete any pre-existing lower quality movie in the destination radarr movie folder
- scan the movie folder in radarr.
- optional: rename in radarr.

I know for dozens of films that would be tedious, but if it's just a few that's not going to be a big job.

**Comment by fryfrog** [comment]
You don't even need to do it manually. Just aim Wanted -> Manual Import at the movie pack folder and be sure to pick copy / hard link as the import option (not move), it'll just do it right.

**Comment by Qstick** [comment]
No plans to expand this support
