### ISSUE TITLE
Cannot add movies on Firefox on Android

### ISSUE THREAD

**Issue by mikebollandajw** [Radarr/Radarr#3867]
**Describe the bug**
Pressing add just wipes the screen

Also happens on firefox beta for android

**To Reproduce**
1. Add film
2. Doesnt add film

**Expected behavior**
Add film ok like it does on chrome for android

**Comment by fryfrog** [comment]
Turn logging up to trace, repeat. Anything useful in the logs?

**Comment by Qstick** [comment]
Also fill out the entire issue template, we need version info.

**Comment by mikebollanddp** [comment]
0.2.0.1358

(image linuxserver/radarr)

**Comment by Qstick** [comment]
We can't guarantee things will always work with beta versions of browsers. does this work with standard Firefox for android?
