### ISSUE TITLE
"Cut-Off Unmet" filter not working

### ISSUE THREAD

**Issue by Drawmonster** [Radarr/Radarr#3868]
"Cut-Off Unmet" filter not working

**To Reproduce**
1. Go to main "Movie" library page
2. Click on 'Filter'
3. Choose "Cut-off Unmet" filter
4. "All movies are hidden due to the applied filter." is always displayed instead of showing movies matching the filter.

**Expected behavior**
Selecting filter should display list of movies that have not met the quality profile cut-off.

![chrome_EkhUNOiV80](https://user-images.githubusercontent.com/32946029/68334576-84bd7e80-00a0-11ea-909e-ba8db1ee11a9.png)

 - OS: Unraid
- Radarr Aphrodite Version: 2.0.0.2152

**Comment by Qstick** [comment]
Fixed 89fec7841ca4283f05cce5309b50f384e18f5bb5
