### ISSUE TITLE
Radarr shows wrong (previous) movie after hitting save button.

### ISSUE THREAD

**Issue by furx** [Radarr/Radarr#3869]
I think since I started using Radarr over a year ago I have periodically this issue.

I handle my downloads by myself, so after I moved the folder from the download folder to my movie folder, I manually add the path to Radarr and set monitoring to off. 

Recently - again - after hitting the save button Radarr shows me the movie page from the previous edited movie. URL stays the same, but movie shown is the wrong one.

Video: https://i.imgur.com/kkc6uki.mp4

Issue is basically the same as #1710

Cheers

**Comment by fryfrog** [comment]
Refresh your browser? Also... why bother using Radarr at all?

**Comment by furx** [comment]
> Refresh your browser? Also... why bother using Radarr at all?

What kind of answer ist that?

This is obviously a bug, and refreshing the browser each time should be a solution?

Thanks for nothing.

**Comment by fryfrog** [comment]
Fair enough! :)

**Comment by paolovador** [comment]
I also noticed this since at least 4-5 month maybe more: when setting monitoring to off on a movie page, radarr is redirected to previous edited movie.
Since browser url is still the expected one, refreshing browser page and everything goes back to normal.
