### ISSUE TITLE
[BUG] Can't add TorrentPotato endpoint from Jackett (Searches for 'The' and gets 0 results)

### ISSUE THREAD

**Issue by karbowiak** [Radarr/Radarr#387]
Hi there, it seems that when using Jackett as the middle man for some torrent trackers, that you can't add them with TorrentPotato, simply because it searches for 'the'.

This yields 0 results on some trackers.

I know of atleast one where it happens, IPTorrents.

```
01-23 01:36:24 Info Found 0 torrentpotato releases from IPTorrents for: the
```

Would probably be better to search for something different when adding, or redoing the adding stuff (Maybe add a Force Add)

**Comment by hotio** [comment]
IPTorrents works perfectly fine with Jackett and Radarr.

Are you using an old version of Jackett perhaps? Or old version of Radarr?

**Comment by karbowiak** [comment]
Quite possibly an outdated version of jackett, lemme update and i'll reply back! :)

**Comment by karbowiak** [comment]
You were indeed correct @hotio it was jackett that was too old..

Actually thought it updated itself automatically, guess i was wrong in that assumption :D
Thanks!

Closing the issue since there is no issue /o\
