### ISSUE TITLE
bug?  RSS feed limited to first 100 entrie?

### ISSUE THREAD

**Issue by Bigdesertdon** [Radarr/Radarr#3872]
I am converting over from Couch Potato, and have several IMDB watch lists configured in Couch Potato.    All of these lists are over 100 entries, and it seems like when I import the list I see it counting up to 100.   Which makes me think it's only reading the 100 last added or newest entries from the RSS feed.    In an IMDB list that has been accumulated for years -- this won't work well.   

Is this a bug?  Or am I not understanding how RSS entries are imported?   In other apps when I add a new rss feed, I'm usually presented with an option to import all entries the first time it reads the list, and then from that point on it is limited to a much lower number.  
 
I guess my overall question is how do I get my watch lists from IMDB into radarr when the watch lists have like 1368 items on it... (that's a real example of my primary watch list).

**Comment by fryfrog** [comment]
That be how it is. Indexers that *don't* support pagination are limited to 100 entries. Those that *do* can go to 1000. Set your RSS interval to a fairly quick 15 minutes.

For *lists*, I think what happens is it adds them in batches and works its way up. So it'll add 100, then add the next 100, then keep going. But I could be wrong, I don't use lists. :(

**Comment by Bigdesertdon** [comment]
It doesn't work it's way through the list.  Just keeps reading the same first 100 every time.   I use other software with lists for different needs and usually they have a 'delete after reading' option. which Radarr does not.   SOmething that actually gets through the list, instead of adding the same 100 over and over.   Basically what your saying is Radarr supports IMDB lists/watch lists, but they must be under 100 items.   That seems unrealistic.   Is there a process to request this be addressed?   I mean, I've had my IMDB watch list tied to my downloader for years.  Certainly there are items in the list that I've already downloaded, but a huge inconvienence to have to go through and manage the watch list manually and purge out once it's been downloaded.      Any work arounds?    I don't have a problem with 100 at a tiem, but it needs to be able to work through a list eventually.   Right now it's stuck on the first 100 forever repeating the process on the same entries.

**Comment by Bigdesertdon** [comment]
And I do consider this a bug, versus support....

**Comment by fryfrog** [comment]
Ah dang, I agree.

**Comment by bakerboy448** [comment]
Closing
v0.2 is no longer being actively developed.

If this is still an issue/request on recent v3 builds, please open a new issue.
