### ISSUE TITLE
Filter "Add Movies --> Recommendations / Popular" by Ratings

### ISSUE THREAD

**Issue by R8s6** [Radarr/Radarr#3874]
**Is your feature request related to a problem? Please describe.**

Most of the movies in the Recommendations/Popular section have lower than a rating of 8.0, most of which I would like to ignore. To ignore them, I need to spend a lot of time explicitly mark them as ignored; otherwise, they would continue to show up.

**Describe the solution you'd like**

To set a filter in "Add Movies --> Recommendations/Popular", such that movies below certain rating will not show up.

Thank you very much.

**Comment by Qstick** [comment]
Done in Aphrodite
