### ISSUE TITLE
Unknown download state: metaDL

### ISSUE THREAD

**Issue by ljmerza** [Radarr/Radarr#3875]
**Describe the bug**
getting Unknown download state: metaDL warning for QBittorrent every 20 seconds clogging up the logs so they become unusable.

**To Reproduce**
I assume the state 'downloading metadata' from QBittorrent (v4.19.1) is causing this error. Torrents that dont have any seeds/leechers are stuck in the downloading metadata state on qbittorrent.

**Expected behavior**
make this a valid state so it doesnt over flow the logs

**Screenshots**

**Desktop (please complete the following information):**
docker linuxio Radarr Ver. 0.2.0.1358

**Debug Logs**
```

QBittorrent | Unknown download state: metaDL | 8:46pm
-- | -- | --
  | QBittorrent | Unknown download state: metaDL | 8:46pm
  | QBittorrent | Unknown download state: metaDL | 8:46pm
  | QBittorrent | Unknown download state: metaDL | 8:46pm
  | QBittorrent | Unknown download state: metaDL | 8:46pm
  | QBittorrent | Unknown download state: metaDL | 8:46pm
  | QBittorrent | Unknown download state: metaDL | 8:45pm
  | QBittorrent | Unknown download state: metaDL | 8:45pm


```

**Comment by Qstick** [comment]
Already fixed in develop branch and on nightly build
