### ISSUE TITLE
Specify source

### ISSUE THREAD

**Issue by delphiactual** [Radarr/Radarr#388]
Add the ability to view/specify source (e.g. CAM, SCR, DVD, etc..)

Please use the search bar and make sure you are not submitting an already submitted issue.

Provide a description of the feature request or bug, the more details the better.
When possible include a log!

Please use our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by galli-leo** [comment]
Not quite sure what you mean by specify source.
We will be adding more qualities such as CAM, Screener, etc. (Covered in #66)
