### ISSUE TITLE
3D movie filter

### ISSUE THREAD

**Issue by soulvoid86** [Radarr/Radarr#3884]
**Description:**

**Radarr Version:**0.2.0.1358

**Mono Version:** Not sure what this is.

**Debug Logs:** Feature request, no logs needed

# Do not remove anything from your logs and post the full logs! If not everything fits in here use a service like https://pastebin.com to upload them.

I was wondering if we could get a filter option to choose if we want 3D releases of movies. I do not want to have 3D movies grabbed, and Radarr is always grabbing them, or upgrading current movies with their 3D versions.

Thanks!

**Comment by fryfrog** [comment]
This already exists, just put `3D` and `SBS` (side by side) in must not contain if you never want them. Or you can give them tags and apply those tags to movies or profiles.

Another common term is `OU` (over under), but that would match too many non-3D movies to be reasonably used. :(

**Comment by soulvoid86** [comment]
Perfect, I never messed with that option, so it never came to mind! I've never see ou in any of the releases on my indexer either, so I'll skip that one. :) Thanks!
