### ISSUE TITLE
Folder is not writable by user

### ISSUE THREAD

**Issue by gjunkie** [Radarr/Radarr#3887]
**Describe the bug**
I'm running Radarr as a service on macOS 10.15.1. I am unable to select my external hard drive as my Movie folder. I can confirm that `mono` and `radarr` services are both running under the same user, the same user that owns my external volume. The volume is listed under the System section of the app, and Im able to drill into in when attempting to select a `movies` directory in that drive. However, no folders show up in my Server drive.

As a side note, I had previously been running Radarr in Docker and was able to see these folders no problem. Perhaps docker did something funky?

**To Reproduce**
1. Attempt to select an external hard drive as the Movies location.
2. No child directories are visible.

**Expected behavior**

**Screenshots**
![Screen Shot 2019-11-22 at 3 47 28 PM](https://user-images.githubusercontent.com/626628/69468126-da03bc00-0d3f-11ea-9f92-fb27bb4da2c5.png)

![Screen Shot 2019-11-22 at 3 47 51 PM](https://user-images.githubusercontent.com/626628/69468129-de2fd980-0d3f-11ea-856a-0e87c8582994.png)

![Screen Shot 2019-11-22 at 3 48 04 PM](https://user-images.githubusercontent.com/626628/69468132-e25bf700-0d3f-11ea-880a-70ffb8c86f23.png)

![Screen Shot 2019-11-22 at 3 48 48 PM](https://user-images.githubusercontent.com/626628/69468138-e556e780-0d3f-11ea-978a-d3c2dadf4fed.png)

![Screen Shot 2019-11-22 at 3 51 46 PM](https://user-images.githubusercontent.com/626628/69468170-07e90080-0d40-11ea-8800-d6042e544a81.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.15.1
 - Mono Version: 6.4.0.198 (2019-06/fe64a4765e6 Wed Sep 18 14:14:51 EDT 2019)
 - Browser and Version [e.g. chrome, safari] (Only needed for UI issues)
 - Version 0.2.0.1358

**Debug Logs**
just lots of this:
![Screen Shot 2019-11-22 at 4 03 07 PM](https://user-images.githubusercontent.com/626628/69468694-facd1100-0d41-11ea-99d0-883f931bd38d.png)

**Comment by gjunkie** [comment]
I've found the issue. It is macOS Catalina that is the problem. In order to solve this issue, I had to grant full disk access to `/bin/sh`:

- Open System Preferences
- Choose Security & Privacy
- Go to Privacy tab
- Select Full Disk Access.
- Click the +
- Browse to your system disk volume and then \bin\sh (If you don’t see a bin folder you might need to press Shift+Command+. to toggle visibility of hidden files)
- Click Open

Restart Radarr and you should be set.

**Comment by omnicr0n** [comment]
Just wanted to add that I've been having this exact problem since I updated to macOS Catalina 10.15.3. It occurred on Sonarr, but not Radarr. This fixed it.

**Comment by chrisgmbishop** [comment]
Is there a more suitable, more secure way of fixing this? Opening your hard drive up to malicious scripts doesn't seem like an ideal solution
