### ISSUE TITLE
Zombieland

### ISSUE THREAD

**Issue by mosath-s** [Radarr/Radarr#3889]
**Describe the bug**
I got title from jackett: `Z: Zombieland: Double Tap (2019) CAMRip [H.264/720p-LQ] [MVO] [AD]`
but radarr cant parse it with error:
`Failed to map movie, found title Z Zombieland Double Tap, expected one of: Zombieland: Double Tap, Zombieland 2, Zombieland 2: Double Tap`
can we fix it?

**Desktop:**
 - OS: [Windows]
 - Version [0.2.0.1358]

**Comment by fryfrog** [comment]
This is just badly named, manually import it.
