### ISSUE TITLE
Hydra

### ISSUE THREAD

**Issue by estimadarocha** [Radarr/Radarr#389]
Is there any special setup to radarr work with hydra? i am testing it and it doesn't return any results... and if i make the same search directly on hydra it does return results!

**Comment by Benni-chan** [comment]
I'm using Hydra and added it as a custom Newznab Indexer (with API Key and correct URL).
Works fine so far.

**Comment by estimadarocha** [comment]
@Benni-chan i also added it as custom with all the info needed i make the test its sucessfull but on searchs at least for me is not working

**Comment by schumi2004** [comment]
It seems to work fine here for manual search i'm 100% sure.
My history only shows 1 entry and that must be a automatic grab since i only have Hydra as provider.
So i'm 99,99% sure it works for automatic grabbing also.

**Comment by estimadarocha** [comment]
@schumi2004 if i go to nzbhydra history i see the request... but radarr doesn't report any result on manual or auto.

But if i make the search internal on hydra it does report results for the same movie!

**Comment by estimadarocha** [comment]
DownloadDecisionMaker	No results found	10:13am
NzbSearchService	Searching 1 indexers for [The Accountant]	10:12am

**Comment by vertigo235** [comment]
Mine is working fine with hydra

**Comment by estimadarocha** [comment]
@vertigo235 and the others using hydra... can you guys say what indexers you are using in hydra?

i use dognzb...nzb.su and nzb.is... currently dognzb dammm slow and sometimes with problems and nzb.is also not working good!

**Comment by schumi2004** [comment]
@estimadarocha I'm using the same indexers. Are you using ignore words maybe and made it to strict?
