### ISSUE TITLE
API KEY is Showing

### ISSUE THREAD

**Issue by jean-paullizotte** [Radarr/Radarr#3890]
**Describe the bug**
API calls to TMDB have radarr's api key in plain text for all to see.
I think it's supposed to be secret.
I've tested it and it can be used.

**To Reproduce**
1. Go to 'System->Logs->Files'
2. Click on 'Radarr.txt'
3. Fino a  'TMDbImport|Importing TMDb movies from'

**Expected behavior**
The occurences of the API key should be masked (with ********)

 Server is freebsd (FREENAS)

**Debug Logs**
19-11-24 12:10:41.3|Info|Database|Vacuuming Log database
19-11-24 12:10:41.5|Info|Database|Log database compressed
19-11-24 12:14:08.0|Info|MovieService|Linking [Insidious The Last Key (2018).mkv] > [[Insidious: The Last Key (2018)][tt5726086, 406563]]
19-11-24 12:15:10.6|Info|TMDbImport|Importing TMDb movies from: https://api.themoviedb.org/3/discover/movie?api_key=1a7373301961d03f97f853a876dd1212&sort_by=popularity.desc&vote_count.gte=1&vote_average.gte=5&with_genres=&without_genres=&with_original_language=en&page=1
19-11-24 12:15:10.7|Info|TMDbImport|Importing TMDb movies from: https://api.themoviedb.org/3/discover/movie?api_key=1a7373301961d03f97f853a876dd1212&sort_by=popularity.desc&vote_count.gte=1&vote_average.gte=5&with_genres=&without_genres=&with_original_language=en&page=2
19-11-24 12:15:12.8|Info|TMDbImport|Importing TMDb movies from: https://api.themoviedb.org/3/discover/movie?api_key=1a7373301961d03f97f853a876dd1212&sort_by=popularity.desc&vote_count.gte=1&vote_average.gte=5&with_genres=&without_genres=&with_original_language=en&page=3
19-11-24 12:15:14.8|Info|TMDbImport|Found more than 3 pages, skipping the 496 remaining pages
19-11-24 12:17:26.6|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: /media/MovieProcessing/Completed/The Sting 1973 1080p BluRay DUAL DD5.1 10bit  x265-FRDS
19-11-24 12:18:30.8|Info|NetImportSearchService|Found 2 movies on your auto enabled lists not in your library
19-11-24 12:18:30.9|Info|NetImportSearchService|PK (pk-297222) will not be added since it was found on the exclusions list
19-11-24 12:18:32.1|Info|NetImportSearchService|Barbie: Dolphin Magic (barbie-dolphin-magic-476631) will not be added since it was found on the exclusions list

**Comment by fryfrog** [comment]
The TMDB api key would have to be right there in the source, showing it in the logs doesn't matter. This isn't like your personal indexer/download client api key.
