### ISSUE TITLE
RSS error: Invalid request Validation failed

### ISSUE THREAD

**Issue by FilmjunkieGF** [Radarr/Radarr#3891]
**Describe the bug**
When testing a custom RSS list with this RSS Link:
https://www.xrel.to/feeds/atom/releases-movie-hdtv.xml

it wont work and gives this error:
Invalid request Validation failed: -- No results were returned from your list, please check your settings.

But there are titles in this RSS list. So what is the problem here?

**To Reproduce**
Try to create a list with the given RSS link

**Expected behavior**
Parsing the titles of the RSS list.

**Debug Logs**

19-11-25 01:07:16.3|Debug|RSSImport|Downloading List https://www.xrel.to/feeds/atom/releases-movie-hdtv.xml
19-11-25 01:07:25.7|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- No results were returned from your list, please check your settings.
19-11-25 01:07:25.8|Debug|Api|[POST] /api/netimport/test: 400.BadRequest (9559 ms)

**Comment by Qstick** [comment]
Please include Radarr version in your post. You are trying to use a list with release titles in net import, which was mostly designed to import from add movies from an IMDB rss feed. The RSS Import list looks for items with `item` node, your list uses `entry`. Long story short its not made to use that type of rss list for adding movies.
