### ISSUE TITLE
Regression on aphrodite about folders name

### ISSUE THREAD

**Issue by sarakha63** [Radarr/Radarr#3895]
**Describe the bug**
When postprocessed the file gets the correct local name but the folder gets the us name.
On radar 0.2 the Dynamic folder name was an acceptable work around. The feature disapeared but the issue IS Still ther

**To Reproduce**
1. Go to add a mobile (finding nemo -- french locale gives le monde de nemo
2. Wait post process
3. The file will be in Root folder/finding nemo 2013/ le monde de nemo 2013.mkv

**Expected behavior**
As of radar 0.2 i expect the final file to be in
Root folder/le monde de nemo 2013/ le monde de nemo 2013.mkv

The Idea is to get back the Dynamic folder workaround

Or better : define movie path at the same Time the name IS catched ans defined (when WE add a movie)

**Comment by Qstick** [comment]
Please include your naming settings and your exact version of Radarr

**Comment by sarakha63** [comment]
Movie name : {Movie Title} ({Release Year}) {Quality Title} {MediaInfo HDR} {MediaInfo VideoBitDepth}bit {MediaInfo 3D} {MediaInfo VideoCodec} {MediaInfo AudioCodec} {MediaInfo AudioChannels} [{IMDb Id}]


Folder name : {Movie Title} ({Release Year})


Aphrodite version : 2.0.0.2193
