### ISSUE TITLE
Cant add blank category

### ISSUE THREAD

**Issue by mosath-s** [Radarr/Radarr#3896]
**Describe the bug**
Jackett manual search output results with no category
how can I use this results in search in radarr?
Settings.indexers.Torznab.categories with such value not working: 2000,2010,2020,2030,2035,2040,2045,2050,2060,""

**Desktop:**
 - OS: [Windows]
 - Version [0.2.0.1358]

**Comment by Qstick** [comment]
Not planning on opening this up to blank due to the amount of non parse-able results that you would get from an average indexer from every other category.
