### ISSUE TITLE
Add the ability to sort movies by file size in Movies tab/table view

### ISSUE THREAD

**Issue by ejalal** [Radarr/Radarr#3897]
**Is your feature request related to a problem? Please describe.**
It would be nice if there's a new column and button on the Movies tab to sort out the movies by file size. This will help a lot in determining the largest ones and maybe help decide to manually search for a smaller version.

**Describe the solution you'd like**
Add a new sortable column in the Movies tab/table to display the file size and a button to allow sorting the list by file size.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Qstick** [comment]
I'll will add this to Aphrodite, but not back to develop branch
