### ISSUE TITLE
Cannot Bulk Import Over 100 Titles

### ISSUE THREAD

**Issue by BzowK** [Radarr/Radarr#3898]
**Describe the bug**
Selecting "Bulk Import" then selecting network share eventually displays 15 titles to import.  If I select 500 or 1000 from dropdown, search takes place but no results are listed.  In addition, I confirmed in logs that a few seconds after the search for 500/1000 ends, Radarr continues searching all folders in designated path without showing any UI message or progress indicator.

**To Reproduce**
1. Select "Bulk Import"
2. Select network share
3. Wait for the default of 15 titles to be displayed with matches
4. Select 500 or 1000 from dropdown list and wait for it to complete

**Expected behavior**
A list of 500/1000 titles with matches displayed for confirmation and adding to DB

**Desktop (please complete the following information):**
 - OS: Windows 10 x64 1809
 - Browser and Version: Chrome (Latest)
 - Version: "Bulk Import"

**Debug & Trace Logs**
I deleted logs prior to following steps so that I could submit ones which only included relevant data.  Below is a timeline for choices made and results viewed for reference:

- 19-11-27 10:45:01 - Bulk Import selected and Network Share Selected
- 19-11-27 10:45:51 - Initial Result ends displaying 15 results
- 19-11-27 10:46:50 - Selected "500" from dorpdown
- 19-11-27 10:47:50 - Search ends with 0 results
- 19-11-27 10:48:14 - Without doing / clicking anything in UI, the search mysteriously continues in logs
- 19-11-27 10:50:44 - Without waiting for mystery search to complete, choose to restart Radarr
- 19-11-27 10:50:58 - Choose to Shut down Radarr via browser (Meant to do that instead of restarting at 10:50:44)
[radarr.trace.0.txt](https://github.com/Radarr/Radarr/files/3897974/radarr.trace.0.txt)
[radarr.trace.txt](https://github.com/Radarr/Radarr/files/3897975/radarr.trace.txt)
[radarr.txt](https://github.com/Radarr/Radarr/files/3897976/radarr.txt)
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/3897977/radarr.debug.txt)

**Note**
I only noticed the mystery search since I saw a lot of CPU & Network usage for Radarr in task manager which happened to be open at the time.  During an earlier search, I let the mystery search run for ~15 minutes.  I didn't let it finish as it had more to go, but left the UI at the 0 results page and it never changed.

Please advise - Thank You

**Comment by fryfrog** [comment]
I've imported far more than 100 titles via Bulk Import and know of many others who have too. Hop onto Discord and get some real time help. :)
