### ISSUE TITLE
Radarr not grabbing movies until days after released...

### ISSUE THREAD

**Issue by austinwbest** [Radarr/Radarr#3901]
Radarr Ver. 0.2.0.1358
Branch: develop

https://ibb.co/dj9FCPf

As seen, the movie has been available for over 7 hours. No error symbol on the right. This has always been an issue with radarr that it takes days before it "finds" it automatically. The "RSS Sync Interval" is set to recheck every 30 minutes.

In the Tasks section: Rss Sync - 30 minutes - 11 minutes ago - in 19 minutes

So it is running but simply not grabbing movies?

**Comment by fryfrog** [comment]
Use movie editor to set *all* your movies to availability of `Physical/Web`, in Settings also make that the new default. Find the availability delay setting and set it to `-28` or so. This will start allowing movies that come down RSS feed to be downloaded if they're up to 4 weeks *before* the release date. It covers early release, but is enough to prevent most spam.
