### ISSUE TITLE
[Aphrodite] Other issue with language Title and download detection

### ISSUE THREAD

**Issue by sarakha63** [Radarr/Radarr#3904]
**Describe the bug**
With language Title handling there are lots of issues. The first one exposed here https://github.com/Radarr/Radarr/issues/3895 is about folder which will ALWAYS be based on original title and so on. But there is another one very annoying. When a movie is searched on indexers it searches with all alternative titles (french and us in my case) which is good. But once the file is sent to Download Client the activity and the post processor will only search with the original title.This results on file being downloaded choosen by Radarr and not even recognized by itself on download client and post processor

**To Reproduce**
1. Go to add a movie (be sure to have a local not US in my example Locale set to french)
2. Search for l'âge de glace (its ice age)
3. The movie will be added and automatically the title and the plot will be in french (good)
4. Notice the root folder being set to ICE AGE  (us title) first issue https://github.com/Radarr/Radarr/issues/3895 as this will never be changed even when the post processing will be done
5: search on releases manually pick up a choosen release with Ice age in its name
6: notice in activity the download not being visible (unless you choose options shows unknown
7: wait the end of download
8: notice the download wont be processed as the movie altough was sent by radarr is unknown

(repeat same step and chose a release with l'age de glace in it) everything works perfectly

**Expected behavior**
As original title are used to search indexers, those same titles should be used to determine the activity and post process the file and as of issue 3895 the folder name shouldnt be fixed to orignal title and should be set to the right name during post processing

No logs for now as i know the issue realtive to language title is known on your side. But can provide some if needed

**Comment by stephaneSBO** [comment]
> **Describe the bug**
> With language Title handling there are lots of issues. The first one exposed here #3895 is about folder which will ALWAYS be based on original title and so on. But there is another one very annoying. When a movie is searched on indexers it searches with all alternative titles (french and us in my case) which is good. But once the file is sent to Download Client the activity and the post processor will only search with the original title.This results on file being downloaded choosen by Radarr and not even recognized by itself on download client and post processor
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to add a movie (be sure to have a local not US in my example Locale set to french)
> 2. Search for l'âge de glace (its ice age)
> 3. The movie will be added and automatically the title and the plot will be in french (good)
> 4. Notice the root folder being set to ICE AGE  (us title) first issue #3895 as this will never be changed even when the post processing will be done
>    5: search on releases manually pick up a choosen release with Ice age in its name
>    6: notice in activity the download not being visible (unless you choose options shows unknown
>    7: wait the end of download
>    8: notice the download wont be processed as the movie altough was sent by radarr is unknown
> 
> (repeat same step and chose a release with l'age de glace in it) everything works perfectly
> 
> **Expected behavior**
> As original title are used to search indexers, those same titles should be used to determine the activity and post process the file and as of issue 3895 the folder name shouldnt be fixed to orignal title and should be set to the right name during post processing
> 
> No logs for now as i know the issue realtive to language title is known on your side. But can provide some if needed

Same problem
Easy to reproduce
If it's possible to make a fix on the multilingual part

**Comment by lejacobroy** [comment]
Same problem for me on the latest version.

I have no idea how the multilanguage is supposed to work in Radarr if we cannot grab movies by it's original title in a non-english language.

**Comment by Qstick** [comment]
Folder and file naming are separate from UI language. You need to change naming settings if you want foreign files and folders

**Comment by lejacobroy** [comment]
Thanks for the reply.
I know folder & file naming is separate from UI language.
What I want to know is how can we change the naming settings to support foreign files AND english files?

**Comment by weinberz** [comment]
Hi, still running into this issue. I'm indifferent to folder naming, but radarr needs to be able to search for alternate names in the download client. Just today:

1. Added Amélie (2001) to radarr.
2. Radarr successfully searched indexer and picked up "Le.Fabuleux.Destin.d'Amélie.Poulain" (alternate title) and sent to download client.
3. Download completed in client, but radarr never picked it up for post-processing.

This is pretty regular occurrence for foreign films.

**Comment by Qstick** [comment]
We are going to need some more info, release name, some logs, etc. Feel free to open a new issue with case details
