### ISSUE TITLE
Ability to Reimport/Modify Existing Titles from RSS Lists

### ISSUE THREAD

**Issue by seemslegit7** [Radarr/Radarr#3905]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
The ability for Radarr to account for changes in preexisting RSS lists.

**Describe alternatives you've considered**
I looked into the ability to forcibly reimport titles from a list, but this would not seem possible.

**Additional context**
The need for this solution arose upon importing a certain list from IMDB into Radarr, specifically a list of non-native English titles. My particular handling of them involves, among other things, applying to them a "foreign" tag which would exclude various keywords from the filename. In this instance, when I first set up the above list I forgot to include my "foreign" tag. Thus, all titles were imported without this tag.

My current workaround has involved the following steps:

- Import each IMDB list into a separate folder path so as to be able to distinguish between them

- Go into the Movie Editor

- Sort by path

- Locate the relevant path

- Bulk delete all titles from that path

- Let Radarr reimport all titles from the IMDB list, this time with the desired settings.

Another potential use case would be when moving a number of preexisting Radarr titles from one IMDB list to another in which instance, ideally, the respective titles in Radarr would be modified to reflect the new list settings versus me having to individually locate them within the Movie Editor and bulk edit them, tags excluded.

No clue if such an idea would be remotely feasible and/or worth the time investment (probably not), but I thought I would mention it regardless. Other less cumbersome workarounds would be welcomed as well.

**Comment by bakerboy448** [comment]
Closing
v0.2 is no longer being actively developed.

If this is still an issue/request on recent v3 builds, please open a new issue.

foreign languages are  improved in v3
