### ISSUE TITLE
Radarr Snatching the same or previously snatched quality

### ISSUE THREAD

**Issue by Rouzax** [Radarr/Radarr#3907]
**Describe the bug**
Even though a 2160p Remux is already downloaded it will grab another one
![image](https://user-images.githubusercontent.com/4103090/69898100-e77b0080-1354-11ea-8cdb-65232ab2f550.png)

![image](https://user-images.githubusercontent.com/4103090/69898107-f792e000-1354-11ea-873a-67c53ac0fe84.png)

![image](https://user-images.githubusercontent.com/4103090/69898170-d252a180-1355-11ea-83ab-0646122f09a0.png)

**Desktop (please complete the following information):**
 - OS: Windows 2019
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/3906911/radarr.debug.txt)

**Debug Logs**
Turn on debug logs under Settings -> General and wait for the bug to occur again. **Upload the full log file here (or another site and link it). Issues will be closed, if they do not include this!**

**Comment by Rouzax** [comment]
And another one
![image](https://user-images.githubusercontent.com/4103090/69905564-93eccf00-13b5-11ea-9ad2-421f9930e5a6.png)
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/3907490/radarr.debug.txt)

**Comment by fryfrog** [comment]
Start by switching from preferred tags to custom formats. The preferred tags don't work very well because they only apply when there are *many* results to pick from, like during a triggered search. They won't help in normal operation via RSS feed.

Turn logging up to Debug or Trace so you can see why it is making these decisions.

**Comment by Rouzax** [comment]
> Start by switching from preferred tags to custom formats. The preferred tags don't work very well because they only apply when there are _many_ results to pick from, like during a triggered search. They won't help in normal operation via RSS feed.
> 
> ~Turn logging up to Debug or Trace so you can see why it is making these decisions.~
> 
> Edit: Duh, you've done that. :)

The problem with the custom formats is that they are counted as an individual download.
My wish is:

1. Remux-2160p
2. Remux-1080p
3. Bluray-1080p

Every release has a Bluray-1080p, most a Remux-1080p and some a Remux-2160p.
If a movie has a Remux-2160p right now, most of the times I already download it 3 times since in general the releases start with the lower qualities first.
With Custom Formats they are treated as an individual releases while not all for instance Remux-2160p releases have HDR which will result in me downloading maybe first the `Remux-2160p` and then the `Remux-2160 HDR` bringing the total to 4 downloaded

**Comment by fryfrog** [comment]
As long as you know your preferred words are *only* helping anything in the case of a search, but *not* during the normal operation via RSS... you're fine. You could achieve similar by making HDR/whatever *optional* for one custom format and *disabling* the `None` custom format. At least it'd apply during RSS *and* search.

Also, I'd maybe suggest that the edition is something you probably don't want to hard code anyway.

I had a quick look through the logs, but there is a *lot* there. Do you know for sure if you caught the moment when it came down RSS and was selected?

**Comment by Rouzax** [comment]
Yes I understand the limitation of the tags.

Yes it should have captured that.
Once upon a Time was added for the third time at: 9:32:43
It Chapter Two was added (in a lower quality) at: 20:31:50

**Comment by Rouzax** [comment]
Managed to retrieve it again from a backup
[radarr.debug.29.txt](https://github.com/Radarr/Radarr/files/3910068/radarr.debug.29.txt)

It looks to be the same weird error that it coudn't reach the qBittorent client, but that still does not explain why it would want to add it anyway.
qBittorrent was running.
This is the log of qBittorrent.
```
(N) 2019-11-30T19:47:40 - Torrent: Once.Upon.a.Time.in.Hollywood.2019.UHD.BluRay.2160p.DTS-HD.MA.7.1.HEVC.REMUX-FraMeSToR, running external program, command: C:\Scripts\TorrentScript.cmd &quot;C:\TEMP\Torrent\Downloads&quot; &quot;Once.Upon.a.Time.in.Hollywood.2019.UHD.BluRay.2160p.DTS-HD.MA.7.1.HEVC.REMUX-FraMeSToR&quot; &quot;Radarr&quot;
(N) 2019-11-30T19:54:22 - Torrent: It.Chapter.Two.2019.UHD.BluRay.2160p.TrueHD.Atmos.7.1.HEVC.REMUX-FraMeSToR, running external program, command: C:\Scripts\TorrentScript.cmd &quot;C:\TEMP\Torrent\Downloads&quot; &quot;It.Chapter.Two.2019.UHD.BluRay.2160p.TrueHD.Atmos.7.1.HEVC.REMUX-FraMeSToR&quot; &quot;Radarr&quot;
(N) 2019-11-30T20:26:58 - WebAPI login success. IP: ::ffff:192.168.2.12
(N) 2019-11-30T20:31:50 - Download first and last piece first: Off, torrent: 'It.Chapter.Two.2019.1080p.Bluray.Atmos.TrueHD.7.1.x264-EVO'
(N) 2019-11-30T20:31:50 - 'It.Chapter.Two.2019.1080p.Bluray.Atmos.TrueHD.7.1.x264-EVO' added to download list.
(N) 2019-11-30T20:33:08 - Torrent: It.Chapter.Two.2019.1080p.Bluray.Atmos.TrueHD.7.1.x264-EVO, running external program, command: C:\Scripts\TorrentScript.cmd &quot;C:\TEMP\Torrent\Downloads&quot; &quot;It.Chapter.Two.2019.1080p.Bluray.Atmos.TrueHD.7.1.x264-EVO&quot; &quot;Radarr&quot;
(N) 2019-11-30T21:07:17 - WebAPI login success. IP: ::ffff:192.168.2.12
``` 
So the Remux-2160p was finished at: 19:54:22 after which it was post processes and picked up by Radarr at: 20:31:26
Which also seems to be the time it decided to download the Bluray-1080p again

**Comment by Rouzax** [comment]
It just looks like it randomly decided to download the Bluray-1080p.
At 19-11-30 20:31:46.1 it gets the release in RSS.
Which gets rejected at: 19-11-30 20:31:46.3 since `Existing file meets cutoff: Remux-2160p`
Then at: 19-11-30 20:31:47.4 it tries to add it from TorrentDay which fails somehow because qBittorrent wasn't listening (which it was)
Then immediately it adds the same torrent but now from DigitalCore

**Comment by Rouzax** [comment]
Just had another happening, currently on mobile so can't capture the debug logs.
In this case it downloaded the Remux-2160p and while it got the API call to import it, it decide to start another download of the Bluray-1080p (which was already there before the Remux-2160p)
I think it might have to do with a timeout between the download finishing in qBittorrent and when it is actually ready to be imported by Radarr.
It needs to be unpacked etc.
At the end I do a Radarr API call to do the import from the final location.

**Comment by fryfrog** [comment]
If Radarr/Sonarr think sending the torrent to the client *failed* and it really was successful, I'm not sure what you can do besides solve that. Are you using black hole or direct connection? Does it *see* them while they're downloading? That is the weird part to me, even though it "failed" the send... they are *there* and should show up, but I'm not sure if Sonarr/Radarr check items in the download client. They must not? Are the "failed" torrents getting the right category?

**Comment by Rouzax** [comment]
I'll post a complete overview of my setup later.
Using direct connection and Radarr does see the download progress.
So I think it is getting itchy when qBittorrent has completed but Radarr does not yet get to import anything.

**Comment by Rouzax** [comment]
Here is the debug log and screenshots, don't have time to post my entire flow.

![image](https://user-images.githubusercontent.com/4103090/70371588-400e4880-18d5-11ea-967d-c366f0c923d8.png)
![image](https://user-images.githubusercontent.com/4103090/70371596-66cc7f00-18d5-11ea-9cde-5962e0e4e540.png)
[radarr.debug.33.txt](https://github.com/Radarr/Radarr/files/3934882/radarr.debug.33.txt)

**Comment by Rouzax** [comment]
Here is my Radarr settings, I don't let Radarr auto import. I give it an import command through the API when the download is finished

![image](https://user-images.githubusercontent.com/4103090/70374752-c1c29e00-18f6-11ea-947a-1aab3d12dab4.png)
![image](https://user-images.githubusercontent.com/4103090/70374762-d2731400-18f6-11ea-9806-10fc3935e759.png)

My flow:

1. Radarr uses Jackett in the backend to add movies
2. Movie is added to qBittorrent with Label Radarr.
3. Radarr see the download in qBittorrent under the Activity tab
4. qBittorrent downloads in C:\TEMP\Torrent\Downloads
5. When download finishes I kick of a script in qBittorrent to do processing
6. This script does a few things
7. Unpack or copy to C:\TEMP\Torrent\PROCD\Radarr\MOVIENAME
8. Stripout any unwanted subtitles languages
9. Lastly it does an Radarr API call to pick it up: 

```  
    url = protocol + host + ":" + port + web_root + "api/command"
    payload = {'name': 'DownloadedMoviesScan', 'path': dir_to_process}
    headers = {'X-Api-Key': apikey}
```

**Comment by Rouzax** [comment]
Proof that Radar does see download activity
![image](https://user-images.githubusercontent.com/4103090/70390582-898d8f00-19cc-11ea-9fe9-c2497595a5a0.png)

**Comment by Rouzax** [comment]
And it happened again, and snatched a 1080 Remux while the 2160 Remux was already there.
![image](https://user-images.githubusercontent.com/4103090/72004667-2487bc00-324c-11ea-8959-e4ac1e914bd0.png)

![image](https://user-images.githubusercontent.com/4103090/72004683-310c1480-324c-11ea-9657-49a802d9c52c.png)
[radarr.debug.1.txt](https://github.com/Radarr/Radarr/files/4036690/radarr.debug.1.txt)
[radarr.debug.2.txt](https://github.com/Radarr/Radarr/files/4036691/radarr.debug.2.txt)
[radarr.debug.3.txt](https://github.com/Radarr/Radarr/files/4036692/radarr.debug.3.txt)
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/4036693/radarr.debug.txt)
[radarr.debug.0.txt](https://github.com/Radarr/Radarr/files/4036694/radarr.debug.0.txt)

**Comment by Rouzax** [comment]
To test I've also disabled failed download handing
![image](https://user-images.githubusercontent.com/4103090/72006767-995cf500-3250-11ea-95c5-da81310d2775.png)

**Comment by Rouzax** [comment]
With Redownload Setting disabled it just happened again.
It snatched the 1080-Remux while Radarr was processing the 2160-Remux
![image](https://user-images.githubusercontent.com/4103090/73588083-f8670000-44c4-11ea-818e-9f6a61b7aad9.png)
[radarr.debug.8.txt](https://github.com/Radarr/Radarr/files/4142243/radarr.debug.8.txt)
[radarr.debug.7.txt](https://github.com/Radarr/Radarr/files/4142244/radarr.debug.7.txt)

**Comment by Rouzax** [comment]
Happened again.
![image](https://user-images.githubusercontent.com/4103090/74085187-d21e0300-4a76-11ea-8131-3440fa5c5470.png)
![image](https://user-images.githubusercontent.com/4103090/74085193-eeba3b00-4a76-11ea-98f1-672ea01ed39f.png)

Should I still upload my debug logs?

**Comment by Rouzax** [comment]
Happened again.
![image](https://user-images.githubusercontent.com/4103090/76624587-db970100-6535-11ea-9d26-1cbdcaa422e4.png)

![image](https://user-images.githubusercontent.com/4103090/76624625-f23d5800-6535-11ea-9bfa-673de9e166ca.png)

It might have something to do with the way I pick it up.
Always did a https://github.com/Radarr/Radarr/wiki/API:Command#downloadedmoviesscan to pick up the download.
When it happens I also see in the logging that Radarr cannot see which DownloadId it was, so I'm no adding that to the downloadedmoviesscan API call.
