### ISSUE TITLE
I fail to update the preview Radarr install

### ISSUE THREAD

**Issue by ratnose** [Radarr/Radarr#3908]
**Describe the bug**
Radarr docker preview complains it cant update due to this error:
Cannot install update because startup folder '/opt/radarr' is not writable by the user 'abc'.

**To Reproduce**
Insatll Docker, run Linuxserver/raddar:preview

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu serve 19.10
 - Mono Version: [e.g. Mono 5.8] (Only needed under Linux and Mac, found under System -> Status)
 - Browser and Version [e.g. chrome, safari] (Only needed for UI issues)

**Debug Logs**
Turn on debug logs under Settings -> General and wait for the bug to occur again. **Upload the full log file here (or another site and link it). Issues will be closed, if they do not include this!**

**Comment by fryfrog** [comment]
Don't update Radarr *inside* a Docker container. Update your Docker image instead.

**Comment by erosenberg** [comment]
I am getting this issue as well. @fryfrog - I can't speak for the OP, but I'm never attempting to update inside the Docker container. It's an error that appears immediately on startup, and doesn't appear to go away. To make matters worse, when I try to import movies manually or when a downloading completes, I get permissions errors, and I'm pretty sure it's related to Radarr being run by user `abc`. I'm suspecting that this is an issue with the docker container and not by radarr itself though.

**Comment by ta264** [comment]
What version? I suspect you're out of date and it's trying to update itself inside the container and failing

**Comment by ta264** [comment]
Ps your import issue is user error - you haven't set guid and haven't got your permissions correct on the mounted directories

**Comment by erosenberg** [comment]
@ta264 - I believe the build was `3.0.0.2325`. I'm using `linuxserver/radarr`'s docker container with the `preview` tag so I'm suspecting it's related to that. I am setting the PUID and GUID with docker so the container might be broken.

**Comment by martimarkov** [comment]
I'm seeing the exact same behavior for a few weeks now. Also using `linuxserver/radarr`.

**Comment by ta264** [comment]
There is an issue causing the warning to appear but it's harmless

**Comment by martimarkov** [comment]
@ta264 I just opened a separate issue about the uploads at LS but I feel it might be more of a Radarr issue.

**Comment by ta264** [comment]
The permissions are correct, you should not be able to update within the container. The issue is that the built in updater can trigger itself if the settings are wrong and we need to override that
