### ISSUE TITLE
statusMessage at /api/queue is "Sample"

### ISSUE THREAD

**Issue by Gestas** [Radarr/Radarr#3909]
This is not a feature ask for ISO media support. I'm writing a post-processing script, I believe that the error message currently being delivered via the API is the result of a bug. 
 
**Describe the bug**
Using the API, movies in the queue that are in the ```"status": "Completed", "trackedDownloadStatus": "Warning"``` state the error is ```"Sample"``` -
```
$ curl https://radarr.home/api/queue?apikey=XXXXXXXXXXXXXXXX
<excerpt> ...
"status": "Completed",
    "trackedDownloadStatus": "Warning",
    "statusMessages": [
      {
        "title": "My movie.iso",
        "messages": [
          "Sample"
        ]
      }
    ]
...
```
**To Reproduce**
To reproduce the behaviour we need to put a movie in the Warning state -
1. Add a movie without performing an automatic search.
2. Perform a manual search, choose a download that contains a file type not supported by Radarr.
3. Wait for the download to complete. 
4. GET the queue via the API -
    ``` curl https://radarr.home/api/queue?apikey=XXXXXXXXXXXXXXXX```
5. Find the the status array in the results. 

**Expected behaviour**
[Per the documentation](https://github.com/Radarr/Radarr/wiki/API:Queue) the error message should be something like -
```
"status": "Completed",
    "trackedDownloadStatus": "Warning",
    "statusMessages": [
      {
        "title": "Mowgli (2018) Web-Dl 1080p x264 AC3-NoTag.mkv",
        "messages": [
          "No files found are eligible for import in /home/usr/download/movies/Mowgli (2018) Web-Dl 1080p x264 AC3-NoTag.mkv"
        ]
      }
    ]
```
**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 using the linuxserver/radarr container.
 - Radarr Version 0.2.0.1358
 - Mono Version 5.20.1.34 (tarball Tue Jul 16 22:52:32 UTC 2019)

**Debug Logs**
Attached. Also attached is the full JSON output from /api/queue.
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/3907621/radarr.debug.txt)
[radarr.queue.json.txt](https://github.com/Radarr/Radarr/files/3907620/radarr.queue.json.txt)

**Comment by Qstick** [comment]
Radarr thinks file is a sample, likely because runtime can’t be read

**Comment by Qstick** [comment]
#809
