### ISSUE TITLE
Not finding file | Plex Optimized Version interfering?

### ISSUE THREAD

**Issue by SupFrost** [Radarr/Radarr#391]
I think Radarr is having some problems with Plex Optimized Versions? It seems to ignore my main file which is a 4K mp4 file.

![image](https://cloud.githubusercontent.com/assets/7328317/22204592/1077428a-e173-11e6-80cf-4974382c5d8b.png)

**Comment by hotio** [comment]
I don't believe, multiple files is supported at this moment.

**Comment by galli-leo** [comment]
Multiple files are not supported at the moment.

**Comment by vertigo235** [comment]
The sonarr guys recently changed sonarr to ignore the plex optimized folders, may want to take a look at that

**Comment by vertigo235** [comment]
https://github.com/Sonarr/Sonarr/commit/c6eb19c04d6a5ea01d0f471f1359c8ef51e90cd1

and 

https://github.com/Sonarr/Sonarr/commit/54dd527f011daf35339c299c21a73d2e73abab96

**Comment by hotio** [comment]
Or pick the biggest file

**Comment by onedr0p** [comment]
I think ignoring Plex folder is the way forward.

**Comment by onedr0p** [comment]
Fix incoming
