### ISSUE TITLE
Deluge category doesn't allow for numeric Category label

### ISSUE THREAD

**Issue by rcork** [Radarr/Radarr#3910]
**Description:**
When trying to set a Category for Deluge that contains a numeric value (ie. 4k-movies), i receive an error that says "Allowed characters a-z and -". I have Deluge installed with Label plugin and i have a label called 4k-movies. I know that Deluge supports numeric values as i have Sonarr v3 with Deluge configured to use 4k-tv as the category and it works as expected. 

**Radarr Version:**
0.2.0.1358
**Mono Version:**
5.12.0.226
**Debug Logs:**

# Do not remove anything from your logs and post the full logs! If not everything fits in here use a service like https://pastebin.com to upload them.

**Comment by fryfrog** [comment]
I'd give it a try in Radarr v2 if you want to be helpful, but don't *switch* to it. In the mean time, you could use `radarr-uhd` instead.

**Comment by Qstick** [comment]
Was added to Aphrodite here https://github.com/Radarr/Radarr/commit/634697af2df4647e0651083f13cf14d5106f8710
