### ISSUE TITLE
Completed Downloads Not Removed

### ISSUE THREAD

**Issue by Weggy** [Radarr/Radarr#3912]
I've done as much googling and looking at the logs as I can, I can't seem to fix this issue so I'm going to assume it's a bug.

**Describe the bug**
I have the following setting:
Completed Download Handling > Remove > Yes
However, once downloads are completed (I've waited a day to see if they do finally remove), the download is not cleared from Transmission. This leaves two copies of the download, one in the Download Client location and once in the move location. I have checked the logs and I cannot see any permissions issues.

**To Reproduce**
1. Using setting "Completed Download Handling > Remove > Yes"
2. Download an item
3. Wait for it to complete
4. See that the item is not cleared/removed once downloaded

**Expected behavior**
Once an item has downloaded the magnet/torrent link should be removed from transmission and once a copy is made to the download path defined in Radarr all of the files that are within the download client (transmission) download folder should be removed.

**Desktop (please complete the following information):**
 - Rapidseedbox
 - OS: Ubuntu 16.04 LTS
 - Mono Version: Mono JIT compiler version 6.4.0.198

**Debug Logs**
[log.txt](https://github.com/Radarr/Radarr/files/3908109/log.txt)

New log...
[sonarr.debug.txt](https://github.com/Radarr/Radarr/files/3908793/sonarr.debug.txt)

**Comment by fryfrog** [comment]
Do you have your seed time/ratio goals set?
