### ISSUE TITLE
Option to prefer smaller movies

### ISSUE THREAD

**Issue by dippynark** [Radarr/Radarr#3913]
**Is your feature request related to a problem? Please describe.**
Currently Radarr prefers larger downloads (in 200MB chunks). This can sometimes lead to extremely high quality downloads.

**Describe the solution you'd like**
An option to prefer smaller downloads with everything else equal (i.e. an option to change `CompareBy ` to `CompareByReverse ` in the `CompareSize` function like [this](https://github.com/dippynark/Radarr/pull/2/files#diff-9d0f5acc73ecde85aa4916831af51a76)) - the TODO comment suggests this would be beneficial in some cases.

**Describe alternatives you've considered**
- You can flip all the quality types around giving you a good change of picking the smallest download, but I'd want that choice within each quality band - the linked change above works really nice for me and picks the smallest download of my highest allowed quality
- I could limit the maximum size allowed, but this might risk not downloading the highest quality because it's too large - this way I always pick the highest quality but with the smallest size available

**Comment by fryfrog** [comment]
I'm 98% sure there is an existing request like this, I see if you can search and mention it or +1 it. Might also be on feathub. In the mean time, you can use Custom Formats to achieve an imperfect version of this.

**Comment by fryfrog** [comment]
#3338 is one, for example.
