### ISSUE TITLE
Update the Linux installation instruction to prevent file ownership issues?

### ISSUE THREAD

**Issue by NoobieNewb** [Radarr/Radarr#3921]
**Is your feature request related to a problem? Please describe.**
Currently, the manual installation instruction on the site is as follows:
> cd /opt
curl -L -O $( curl -s https://api.github.com/repos/Radarr/Radarr/releases | grep linux.tar.gz | grep browser_download_url | head -1 | cut -d \" -f 4 )
tar -xvzf Radarr.develop.*.linux.tar.gz

In Ubuntu 18.04 (I'm not sure about other distros), commands executed in the /opt directory must be run under root, so when the user extracts the tar file, they will run it using the sudo command, which will result in every file in the Radarr directory to be owned by root.

When the mono --debug /opt/Radarr -nobrowser command is run, this will cause issues because non-root Radarr cannot access the files under .config/Radarr (as described in [this Reddit post.](https://old.reddit.com/r/radarr/comments/9ptgwi/can_only_run_radarr_as_root_in_ubuntu/))

**Describe the solution you'd like**
Update the instruction to something similar to:
> curl -L -O $( curl -s https://api.github.com/repos/Radarr/Radarr/releases | grep linux.tar.gz | grep browser_download_url | head -1 | cut -d \" -f 4 )
tar -xvzf Radarr.develop.*.linux.tar.gz
mv Radarr /opt

This ensures that all Radarr files are owned by the user, and only the act of moving the Radarr directory requires the privilege escalation.

**Describe alternatives you've considered**
1. The user can run the command using
> sudo mono --debug /opt/Radarr/Radarr.exe -nobrowser

2. or if they are using the systemd autostart, by changing the user and group to root. However, I do not think that this is good practice.

**Additional context**
I am running on Ubuntu 18.04

**Comment by fryfrog** [comment]
It is a wiki, feel free to improve that documentation! :)
