### ISSUE TITLE
Missing scroll bar and/or auto fit on Movie Details page

### ISSUE THREAD

**Issue by EnorMOZ** [Radarr/Radarr#3926]
**Describe the bug**
On a movie search result it does not auto fit the page width. Nor does it have a scroll bar to view the entire title of results ie; quality, peers, language etc

**To Reproduce**
1. Go to a Movie page
2. Click on Search

**Expected behavior**
To be able to see the entire search results with row titles; Quality, Language, Peers etc and be able to scroll through them. 

**Screenshots**
![](https://user-images.githubusercontent.com/13998170/70329361-3a4b3100-1809-11ea-93cc-802c695a1a20.png)

**Desktop (please complete the following information):**
-  Radarr Version: 3.0.0.2239
 - OS: Ubuntu 18.04.3
 - Mono Version: [e.g. Mono 5.8] (Only needed under Linux and Mac, found under System -> Status)
 - Browser and Version : All
 - Version: All

**Comment by jes1417** [comment]
Still seeing this issue on mobile

**Comment by vkadam** [comment]
Labels not visible on mobile

**Comment by TheSpad** [comment]
Happens on desktop too if horizonal resolution isn't high enough. I'm seeing it with a 1440p portrait setup (1440 pixel width).

**Comment by jasonla** [comment]
Also seeing this issue on Desktop. Browser resolution is 1280x1024

**Comment by Tharic99** [comment]
@Qstick I'm still seeing this same issue in Radar 3.1.0.4634 on Desktop. Both Google Chrome and Firefox browsers running on an Ubuntu client with a 1280x1024 resolution size.

The right hand results of the search are cut off, no horizontal scroll-bar appears and the only way to get to the columns are to zoom the browser out to 90% or 80%.

**Comment by bakerboy448** [comment]
@Tharic99 the issue was closed  and had mitigating action taken with #5428

the scroll bar appears if you scroll all the way down

the primary issue is the tiny screen size.

this PR will help a bit more
https://github.com/Radarr/Radarr/pull/5928

**Comment by Tharic99** [comment]
So when #5928 is merged in, this issue will be resolved?
