### ISSUE TITLE
Renamer is not working.

### ISSUE THREAD

**Issue by darzur** [Radarr/Radarr#393]
Version  0.2.0.210
Mono Version  3.10.0 (mono-3.10.0-branch/ce003f4 Tue Nov 25 20:18:29 UTC 2014)
System Raspbian on RPi 1

Renamer set to {Original Title} leaves files not renamed. Last example:

```
Episode Imported
Name:    The Accountant

Source:    /mnt/NSA320/Downloads/NZBget/Movies Radarr/The.Accountant.2016.1080p.BluRay.DTS.x264-DON/kRxJbTgWuvSuOZ02.mkv

Imported To:    /mnt/NSA320/Filmy/The Accountant (2016)/kRxJbTgWuvSuOZ02.mkv
```

Expected filename is The.Accountant.2016.1080p.BluRay.DTS.x264-DON.mkv.

**Comment by simonk83** [comment]
Same behaviour with Jack Reacher the other day.

What does {original title} use and what does {original filename} use to rename devs?

**Comment by deathbybandaid** [comment]
For me, renamer is working for the files, but not the folders. I would also be nice if it ignored the "Behind The Scenes" extra folder that plex allows for extras

**Comment by darzur** [comment]
How is it possible that it works for some while not for the others?

**Comment by galli-leo** [comment]
This is fixed on the latest release.
