### ISSUE TITLE
[Aphrodite] Broken Checkbox in movie editor

### ISSUE THREAD

**Issue by wessel145** [Radarr/Radarr#3931]
**Describe the bug**
The checkbox to select multiple movies in the movie editor is broke. It disappeared in the poster view, it still shows when changing the view to table.

**To Reproduce**
1. Go to movies
2. Click on movie editor
3. Try to select movie

**Expected behavior**
It's expected that you can select multiple movies in the movie editor. 

**Screenshots**
Checkbox not seen in poster view:
![image](https://user-images.githubusercontent.com/18014192/70449199-e9099e80-1aa1-11ea-8d98-76fcad72ac0a.png)

Checkbox available in table view:
![image](https://user-images.githubusercontent.com/18014192/70449496-62a18c80-1aa2-11ea-92dc-ea4b1ff7995d.png)

**Desktop (please complete the following information):**
 - OS: Docker - Ubuntu server 19.04
 - Mono Version: none shown under status (probably bc on docker?)
 - Firefox 71
 - Version 3.0.0.2268 (aphrodite)

**Debug Logs**
Enabled debugging, no debug logs found that are related to this issue

**Comment by Qstick** [comment]
Fixed in 318e05ddbad777fb9d9ac80b3a3689c54fa90e71
