### ISSUE TITLE
Duplicate movies when using naming scheme 

### ISSUE THREAD

**Issue by douglas24** [Radarr/Radarr#3934]
**Description:** When using the movie folder format {Original Title} radarr sometimes doesn't delete an old move when it finds and upgrades to the better version according to profile (e.g. it isn't deleting a 720p movie and movie folder, but is grabbing and naming the 1080p movie and folder correctly).

**Radarr Version:**10.0.0.32193

**Debug Logs:** There aren't any error logs about it.

**Comment by Qstick** [comment]
You version indicates you are not running a supported build, you are either running from source or someone else’s build. We need a bit more info and a trace log of this happening, additionally what branch you are using
