### ISSUE TITLE
Srt subtitles are not being renamed and copied

### ISSUE THREAD

**Issue by luizfeliperc** [Radarr/Radarr#3935]
**Describe the bug**

After upgrading to the latest version, no subtitles are being renamed and imported into the destination folder, only the standalone video file if it is in the parent or subfolder. This occurs in the Windows and Linux version. What I noticed is that this updated regex is only working for most downloaded RARGB files and only if the subtitle has a language, for example English.srt or Portuguese.srt
If it has only .srt in the name it is not identified and is not imported.
Since most files are uploaded this way: Movie 2019.mkv and Movie 2019.srt end up affecting subtitle import.
In this case, the regex should be corrected to be able to accept any subtitles that had only .srt.

OS: Ubuntu 18.04 Server

Version 0.2.0.1450 (Docker)

Mono Version 5.20.1.34

Browser Version: All

![image](https://user-images.githubusercontent.com/29809390/70466851-d2177c00-1aa2-11ea-8e01-579c1558a816.png)

**Debug Logs**

https://pastebin.com/TNzw4ZSc

**Comment by Qstick** [comment]
Reverted in nightly until fix can be applied

**Comment by jpogs** [comment]
Hi @luizfeliperc , could you please confirm whether the revert resolved this issue? Based on what I can remember srt subtitles without language in the top level folder should still work so I just want to confirm whether the revert did resolve the issue before spending more time reviewing the code changes...

**Comment by Qstick** [comment]
@jpogs got feedback on discord that it was working like before after revert. I haven’t had any time looking into, but feel free to go back at it.. may be better suited to push into Aphrodite where are moving a bit quicker with pushing in features and testing things... then if we get it working nicely we can port back
