### ISSUE TITLE
[Aphrodite] Sorting on movie search view does not work

### ISSUE THREAD

**Issue by EnorMOZ** [Radarr/Radarr#3938]
Version: 3.0.0.2282

**Describe the bug**
Sorting by size, peers, Indexers etc does not work. All columns. 

**To Reproduce**
1. Go to any movie page
2. Click on search
3. Try to sort by Size or Peers etc

**Expected behavior**
It should sort 

**Screenshots**
<img width="98" alt="Screen Shot 2019-12-10 at 8 49 47 AM" src="https://user-images.githubusercontent.com/13998170/70534927-0bdf9580-1b2a-11ea-95df-ce01cd102151.png">
<img width="106" alt="Screen Shot 2019-12-10 at 8 49 31 AM" src="https://user-images.githubusercontent.com/13998170/70534929-0eda8600-1b2a-11ea-92db-322c59e56052.png">

Don't see any browser console error.

**Comment by Qstick** [comment]
Source, Age, Title, Indexer, Size, Peers sort fine for me in 2282. Only Language, Quality, and Formats are not working (known). Which browser are you using and have you tried in an incognito window? could very well be cache.

**Comment by EnorMOZ** [comment]
Tested on osx chrome incognito, safari, mobile ios chrome incognito and ios safari. I can get you specific versions of each tomorrow.

Sent from a mobile device.

________________________________

**Comment by EnorMOZ** [comment]
The same occurs on 3.0.0.2285. Tried private/incognito mode on all browsers.
Chrome Version: 79.0.3945.79 
Firefox: 71.0 
Safari: Version 13.0.3 (15608.3.10.1.4)

What seems to happen is it tries to sort but does not sort properly.

**Comment by EnorMOZ** [comment]
Was some strange issue regarding indexers. Closing for now.
