### ISSUE TITLE
Can't add torznab feed with Radarr torznab indexer

### ISSUE THREAD

**Issue by PastaGringo** [Radarr/Radarr#394]
Hello,

I can't add a tornzab feed into Radarr's torznab indexer from this custom application : https://github.com/KiLMaN/T411-Torznab.

That works with Sonarr, this is the only thing which miss me before using Radarr! 👍 
Thanks !

**Comment by onedr0p** [comment]
What error is in your log?

**Comment by PastaGringo** [comment]
Hello @onedr0p,

Thanks for your help!
When I click on the "test" button : 

```
17-1-23 20:18:00.7|Warn|Torznab|Unable to connect to indexer

[v0.2.0.210] System.Net.WebException: Error: NameResolutionFailure
  at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x00064] in <5071a6e4a4564e19a2eda0f53e42f9bd>:0 
  at System.Net.HttpWebRequest.GetResponse () [0x0000e] in <5071a6e4a4564e19a2eda0f53e42f9bd>:0 
  at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse (NzbDrone.Common.Http.HttpRequest request, System.Net.CookieContainer cookies) [0x000fe] in <90c79779f710497198253ba19d4cf41d>:0 

17-1-23 20:18:00.7|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Unable to connect to indexer, check the log for more details
```

Don't hesitate if you need more infos 👍

**Comment by galli-leo** [comment]
What do you have in the url field?

**Comment by galli-leo** [comment]
Wait, it seems like a spelling mistake. Url should be localhost, not localhot

**Comment by PastaGringo** [comment]
Hello @galli-leo, you're right... thanks.
I tried so many times that I did not look before posting it ...

With "localhost" : http://pastebin.com/7GxrUZDB
Thanks

**Comment by PastaGringo** [comment]
You closed the issue ? Because it's still not working even with "localhost". You can see in the pastbin posted above. Thanks

**Comment by galli-leo** [comment]
Oh sorry missed that part. I was on my phone.

**Comment by galli-leo** [comment]
Yeah that occurs when the Indexer tells us movie search is disabled. We can still try it with a normal search query. Just add the indexer anways. Additionally, you can tell the hoster of the repo above to include the movie search enabled parameter in the caps endpoint. Also you should ask him if searching by imdbid will be supported.

**Comment by PastaGringo** [comment]
Due to modifications in the application https://github.com/KiLMaN/T411-Torznab, it's now working! 
Thanks for your help! @galli-leo @onedr0p 👍 :1st_place_medal:
