### ISSUE TITLE
File dates options / incorrect file dates

### ISSUE THREAD

**Issue by jscottdouglas** [Radarr/Radarr#3940]
It appears files are keeping the original file dates from where the file came from for example if i downloaded the file today but the file was create 3 months ago, i am getting the 3 month ago date.  Can this be updated to make the file date the same as the completed/downloaded date to the library.  This is causing issues for my automation script, or add an option to the settings to set the file date to the download date, the two options available not useless for me as they only include the cinema and release dates.  

using 0.2.0.1453 - 09 Dec 2019  nightly 
Linux debian, transmission/sabnzbd

Note: now that i've realized the issue i did add to ignore Unrar dates to sabnzbd so that it doesn't happen in the future.

**Comment by fryfrog** [comment]
Setting the date of the file to the download client is pretty squarely a download client thing. Sounds like you already figured out and did that.
