### ISSUE TITLE
scan incorrect 

### ISSUE THREAD

**Issue by pepitopajas** [Radarr/Radarr#3941]
I have my series named in Spanish, from TMDb. When I do a scan, he recognizes them in English. Why ?

**Comment by Qstick** [comment]
This is Radarr, we do movies 😁

**Comment by pepitopajas** [comment]
- Sonarr Version: 2.0.0.5338
 - Operating System: Debian 10 
 - mono : 5.18.0.240

Sorry it's for movies, I wrote it wrong

my problem is :

I have my movies named in Spanish, from TMDb. When I do a scan, he recognizes them in English. Why ?
