### ISSUE TITLE
scan folder error language

### ISSUE THREAD

**Issue by pepitopajas** [Radarr/Radarr#3942]
Sonarr Version: 2.0.0.5338
Operating System: Debian 10
mono : 5.18.0.240
Sorry it's for movies, I wrote it wrong

my problem is :

I have my movies named in Spanish, from TMDb. When I do a scan, he recognizes them in English. Why ?

**Comment by Qstick** [comment]
You gave a Sonarr version, there are no logs. If you want to change the language then modify your profile default language, I believe that also controls UI language. Head to discord for support.
