### ISSUE TITLE
Support Directories In Movie Renamer Options

### ISSUE THREAD

**Issue by javaisbetterthanpython** [Radarr/Radarr#3943]
**Is your feature request related to a problem? Please describe.**
In the option to rename the movie after download, any slashes are replaced with a "+" symbol.
Slashes should be allowed to allow for the creation of subdirectories, for example, grouping movies under the year they were published by allowing for something like {Movie Year}/{Movie Title} ({Movie Year})

**Describe the solution you'd like**
Allow for slashes to be used to denote a directory and create those directories if they don't exist.

**Comment by Qstick** [comment]
Believe you can already do this if you add them to file naming token instead of directory naming token

**Comment by fryfrog** [comment]
Also, this feature request almost certainly already exists. I'd search and find it and add your opinion and +1 it.

**Comment by javaisbetterthanpython** [comment]
> Believe you can already do this if you add them to file naming token instead of directory naming token

My apologies, where do I see this? I'm on version 0.2.0.1450 from Dec 2, 2019.
 Right now I'm setting this under Settings -> Media Management -> Movie Naming -> Movie Folder Format and I cannot put a slash symbol in that field. I can put it in the field above, named "Standard Movie Format" but that is just generating errors, "Couldn't import movie...Root folder <folder> was not found."





> Also, this feature request almost certainly already exists. I'd search and find it and add your opinion and +1 it.

I searched for it and did not find this feature request before posting this.

**Comment by Qstick** [comment]
#153

**Comment by fryfrog** [comment]
Right, @Qstick means do it in the *file* name template. Its a cludge, a bug / feature probably. Since the other issue exists, I'm closing this one.
