### ISSUE TITLE
[Bug] allow hardcoded subs missing from aphrodite v3

### ISSUE THREAD

**Issue by Silent-Remux** [Radarr/Radarr#3947]
**Description:**

In the "Indexers" section, `allow hardcoded subs` option is missing in aphrodite v3 . (screenshot from v2)

![0DHYQ6i](https://user-images.githubusercontent.com/16107603/70853578-8f411400-1ea7-11ea-8e08-ee5d35ecb49e.png)

**Radarr Version:** 

3.0.0.2285

**Comment by Qstick** [comment]
Fixed
