### ISSUE TITLE
'Display Existing Movies' Toggle not working

### ISSUE THREAD

**Issue by mattman86** [Radarr/Radarr#395]
It appears that the 'Display Existing Movies' toggle when adding movies already on the disk isn't working.

When toggled to 'No' before searching the disk, nothing is changed.
When toggled to 'No' after a search, the poster and details go away but the entry for the movie remains in the list.

**Comment by fedoranimus** [comment]
This behaves as designed; it's just a bad design.

**Comment by Flippage** [comment]
This is slightly annoying as you have to wait for Radarr to scrape ALL of the movie posters and details, before you can actually hide them. So if you're just trying to re-add 1 movie, within a folder of 100+ movies you've already added, it still has to load the whole lot.

+1 for re-designing this one

**Comment by onedr0p** [comment]
Moved to http://feathub.com/Radarr/Radarr/+7
