### ISSUE TITLE
handle manual import on connects

### ISSUE THREAD

**Issue by sarakha63** [Radarr/Radarr#3952]
The idea is simple. If we configured a webhook or a script as a connect. We may would like to do something on a manual import (for example a manually added movie to radarr for 3D or whatever reason we didnt let radarr download the movie but add it to the radarr collection)

I suggest to have an option among  "on grab" "on import" and so on such as "manual import"

And maybe a best idea something like "On Button click". We can imagine having a button on movie page which on click will call all the connects that have "on click". and if we manually click on the button it will call our connects.

So both ideas will be a good improvements on connects (specially for webhooks and scripts)

Regards

[AB#883](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/883)

**Comment by fryfrog** [comment]
I have *no idea* what you're asking for. Can you expand and clarify your request?

Also, you know that you can queue up a download in your download client w/ the category Radarr uses and it'll be processed?

Also, all the connect scripts are *post processing* scripts... which means they run *after* the import. So you can't have a post processing script that does an import. But maybe I'm not reading what you're after right.

**Comment by sarakha63** [comment]
in fact to make it simple :

On the Connects Objects we have "On grab" "On import" "On rename". I was just asking for the interest of adding "On manual import". Actually when manually importing "Clicking import and so on" nothing is triggered "even with On import checked.


The second idea was to add on a movie page 
![image](https://user-images.githubusercontent.com/2008029/70983830-afe0b800-20b9-11ea-9c24-2c72b16837e0.png)

A kind of button to trig an event on Connections configured with a "On click event". Could be really usefull

**Comment by fryfrog** [comment]
Ah, I see! Since the on download and on upgrade don't run from Wanted -> Manual Import tasks, right? But I believe they *do* run when you "manual import" on one in Activity. From Wanted, there would be a bunch of variables what *couldn't* be passed in though.

**Comment by sarakha63** [comment]
Yep exactly. But unfortunately on manual import they do not run even with "on import" checked.

I Guess this is wanted to avoid triggering all the connectors on a Big manual import (first one for example) thats why i was asking more for another option "on manual import" among the existing ones.

Concerning the variables i Guess if it runs After the end of the import most of the variables and json should be complete.

**Comment by Lonli-Lokli** [comment]
@fryfrog btw this sentence is not always true
### Also, you know that you can queue up a download in your download client w/ the category Radarr uses and it'll be processed?

I have added movie to the download client deluge, assigned radarr label and this movie did not appear in Queue Activity even after refresh

**Comment by bakerboy448** [comment]
@Lonli-Lokli please don't dig up stale feature requests with unrelated comments.

You need to have the movie added to radarr for it to detect it in queue and then be imported.

**Comment by Lonli-Lokli** [comment]
@bakerboy448 sorry for that.
Actually I've added movie first. I will try to raise a separate bug then with logs.

**Comment by fryfrog** [comment]
You don't need to file a bug, you need to do regular old support via Discord or reddit.

**Comment by Qstick** [comment]
#https://github.com/Radarr/Radarr/commit/a1e622a3630c477f58aa2b775d189b32766594dc
