### ISSUE TITLE
Custom format cutoff doesn't seem to work when quality cutoff is reached

### ISSUE THREAD

**Issue by Knuta86** [Radarr/Radarr#3954]
**Describe the bug**
I prefer EPSiLON and FraMeSToR Remux releases (for no particular reason really)

I had custom formats set up in "old" Radarr which would upgrade any 1080p remux from other groups to EPSiLON or FraMeSToR Remux if they appeared. Same thing with 2160p remux.

In Aphrodite I have it set up the same way, but if a 2160p remux from for example PlayBD exists, it refuses to automatically upgrade to EPSiLON or FraMeSToR Remux. Instead saying "Existing file meets cutoff: Remux-2160p - 31"

**To Reproduce**
1. Have an existing movie that meets quality cutoff, but not custom formats cutoff.
2. Do a search and find a release that matches a higher custom formats quality.
3. See that the release is rejected.

**Expected behavior**
Radarr would see the release which meets a higher custom formats quality and not reject it.

**Screenshots**
![new radarr custom formats](https://user-images.githubusercontent.com/11705857/70943794-f6023100-2051-11ea-8763-fbe7c9180198.png)
![new radarr existing file info](https://user-images.githubusercontent.com/11705857/70943795-f6023100-2051-11ea-9c4d-7b084173b7fc.png)
![new radarr profile](https://user-images.githubusercontent.com/11705857/70943797-f6023100-2051-11ea-8ad2-d7890a99c3ee.png)
![new radarr search](https://user-images.githubusercontent.com/11705857/70943798-f69ac780-2051-11ea-82cf-c96ca1b9bac3.png)
![new radarr search rejected reason](https://user-images.githubusercontent.com/11705857/70943800-f69ac780-2051-11ea-8738-a1cd175957e9.png)
![old radarr custom formats](https://user-images.githubusercontent.com/11705857/70943801-f69ac780-2051-11ea-973b-e9a0294d3587.png)
![old radarr existing file info](https://user-images.githubusercontent.com/11705857/70943802-f69ac780-2051-11ea-85ff-bcea793a073f.png)
![old radarr profile](https://user-images.githubusercontent.com/11705857/70943803-f69ac780-2051-11ea-9a38-528f3bf307fc.png)
![old radarr search](https://user-images.githubusercontent.com/11705857/70943805-f7335e00-2051-11ea-880f-1ceb133d192f.png)

**Desktop (please complete the following information):**
 - OS: Not sure. Running in docker on Unraid using linuxserver docker container
 - Mono Version: Not sure. Not available under System > Status

**Debug Logs**
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/3970167/radarr.debug.txt)

**Comment by TRaSH-** [comment]
i got the same issue that radarr is ignoring the custom format cut-off
![image](https://user-images.githubusercontent.com/6155095/70945174-e7694900-2054-11ea-9818-38bd22ccff99.png)

[trace_log](https://pastebin.com/cnc2Ye7e)
[debug_log](https://pastebin.com/VjZPxANy)

![image](https://user-images.githubusercontent.com/6155095/70945388-5e064680-2055-11ea-9c75-a6c7fa9f5c60.png)

**Comment by Qstick** [comment]
Nice bug report! Wish they were all like this
