### ISSUE TITLE
Tasks Trigger External App (Downloader) to Pause

### ISSUE THREAD

**Issue by Hawkinzzz** [Radarr/Radarr#3967]
Today while downloading I noticed high IO waits and this caused my server to slow to a halt (I have two NVME drives set up in raid 0). I realised it was trying to do too much at the same time. I noticed that while downloading and unpacking, Radarr decided it was time for a "Refresh Movie". This can take a few hours sometimes and so I have had to manually pause my download queue.

What I would like is a way to automate this. When Radarr decides its time to refresh the whole library, it at least pauses my downloader before doing so and then resumes downloads once complete. Maybe this could be done with an external script but I'm not sure how to talk to Radarr or how signals will be sent once a task is started (unless I Sync a cron job approximately with the timed tasks). 

It may also be good (I don't know if this is possible or not at the moment) if I could control the times of these tasks and change it from say once daily, it would be once every week or every month.

**Comment by Qstick** [comment]
Don't think this is something we are going to do anytime in the near future. If you want to have a go at something like this you could poll the API to see when the task is running or the next run time and fashion something up to pause your client based on if the task is running in Radarr.
