### ISSUE TITLE
[Bug] Missing static / dynamic folder path options in aphrodite

### ISSUE THREAD

**Issue by Silent-Remux** [Radarr/Radarr#3969]
**Describe the bug**

Missing options to manage static / dynamic folders in aphrodite. 

`3.0.0.2322`

![Franz_YtibsjQHew](https://user-images.githubusercontent.com/16107603/71128863-1fec5c80-21e6-11ea-95fe-b312adb00af2.png)

**Comment by Qstick** [comment]
Do we really need these? If we allow folder rename in editor similar to Sonarr, the need for these extra settings goes away imo. These options are just confusing to most users... my proposal make paths static and allow users to explicitly rename folders in editor when required.

**Comment by Qstick** [comment]
Yea, agree there are some year processing issues, we can look at those as separate issues. I’m not sure how much of that stems back to tmdb and how much is our fault

**Comment by brandonscript** [comment]
Another reason to have this feature back is if you change your folder naming scheme, you have to manually edit every film in your library. What we really need is an option when renaming (or bulk renaming) to rename folders, files, or both.

**Comment by Qstick** [comment]
Just go to editor select all you want renamed and change root folder to the same root folder... It will also rename the folders.

**Comment by brandonscript** [comment]
Fair workaround, but that's not exactly an obvious feature :)
