### ISSUE TITLE
Radarr is not removing completed downloads from transmission

### ISSUE THREAD

**Issue by jasperrooduijn** [Radarr/Radarr#397]
Completed Download Handling:
Enable -> YES
Remove -> YES

In transmission all my torrents have a seed ratio of one and get paused/stopped afterwards. This is where Sonarr normally cleans the download. But in Radarr it doesn't seem to work.

![screen shot 2017-01-23 at 18 25 54](https://cloud.githubusercontent.com/assets/1854745/22214820/63a1e67e-e199-11e6-8e97-885db0d61f74.png)

**Comment by ShanDestromp** [comment]
You need to set "Remove" to "YES" in completed handling; you have it set to "NO" in the above screenshot.

**Comment by jasperrooduijn** [comment]
owww wow. Thats really stupid :-). Not sure what i was thinking. Thanks!

**Comment by ShanDestromp** [comment]
@jasperrooduijn No biggy, we've all done it before; but please go ahead and close the bug so the devs know it's "fixed"

**Comment by batitou81** [comment]
Hello,
I have this issue, even if "Remove" is set to "YES".
Is there anything else I have to do ?
