### ISSUE TITLE
Negative number in "Time grabbed"

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [Radarr/Radarr#3970]
**Describe the bug**
When doing an RSS sync from PTP, a negative number was put in for the Grabbed at time in History.

**To Reproduce**
n/a (I don't know)

**Expected behavior**
A non-negative number to be added

**Screenshots**
![gnug20cr](https://user-images.githubusercontent.com/15848969/71132304-19012200-21c5-11ea-8513-4dda31d76da8.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Mono Version: 6.6.0.161
 - Version 0.2.0.1457

**Comment by pikanewghacc** [comment]
Still an issue.

**Comment by ThatNerdyPikachu** [comment]
@Qstick Do you know if this is an issue with PTP in v3?

**Comment by Qstick** [comment]
Have not seen any reports, but very possibly still there
