### ISSUE TITLE
radarr convert special caracters ö to oe and ü to ue

### ISSUE THREAD

**Issue by mkay1905** [Radarr/Radarr#3975]
Hello,
I'm currently using radarr to get Turkish movie.
Some title are not correcty searched on jacket for example :

- Ölümlü Dünya become oeluemlue duenya

And movie is not found.

Do you have any workaround who can allow me to bypass this issue please?

**Comment by v0l** [comment]
https://github.com/thomasgalliker/Diacritics.NET ?

**Comment by mkay1905** [comment]
> https://github.com/thomasgalliker/Diacritics.NET ?

Thanks you so much.
I have done some test and it's exactly what i'm looking for.
Any chance to implement it on radarr ?

**Comment by bakerboy448** [comment]
@mkay1905 is this still an issue on the recent v3 builds? Significant improvements were made on v3 this year.
