### ISSUE TITLE
Status in web ui doesn't update while adding first movie

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [Radarr/Radarr#3976]
**Describe the bug**
When adding your first movie in the Web UI, the progress updates stop coming in after ``Updating <movie name>``, and an error is displayed in console. The movie updates and searches fine though, and subsequent adds do not have this issue.

**To Reproduce**
1. Add a movie to a fresh library

**Expected behavior**
Status messages to continue coming in

**Screenshots**
n/a

**Desktop (please complete the following information):**
- OS: Linux
- Mono Version: 6.6.0.161
- Version 0.2.0.1457

**Logs**
```
Error: The specified `itemViewContainer` was not found: #x-movie-list backbone.marionette.js:465
    Backbone 13
    add MoviesCollection.js:254
    Backbone 3
    appInitializer SignalRBroadcaster.js:36
    jQuery 13
```

**Comment by pikanewghacc** [comment]
Still an issue.

**Comment by ThatNerdyPikachu** [comment]
Still an issue.

**Comment by Qstick** [comment]
Don't think this is an issue in v3

**Comment by ThatNerdyPikachu** [comment]
Probably not.
