### ISSUE TITLE
Impossible to add "cpasbien" from jackett indexer

### ISSUE THREAD

**Issue by sam37git** [Radarr/Radarr#3978]
**Describe the bug**
Impossible to add "cpasbien" from jackett indexer

1. Go to Indexers
2. Click on add
3. Click on Torznab
4. Add a name
5. URL: http://127.0.0.1:9117/api/v2.0/indexers/cpasbien/results/torznab/
6. API KEY: API Key of Jackett
7. On test or save, i have: No results were returned from your indexer, please check your settings.

On jackett the test is a success, I can search or download.

 - OS: Windows 10
 - Radarr Ver. 0.2.0.1450

[radarr.txt](https://github.com/Radarr/Radarr/files/3988117/radarr.txt)

**Comment by Qstick** [comment]
Radarr will fail the test if there are no movie results returned during the test

**Comment by sam37git** [comment]
But on jackett i have results

**Comment by Qstick** [comment]
Are they movies? and are they identified as movies from Jackett? Hop on discord for help
