### ISSUE TITLE
Renaming -> "Standard movie format" vs "Movie folder format" and using file name for movie folder

### ISSUE THREAD

**Issue by theotherp** [Radarr/Radarr#398]
1. I guess the "Standard Movie Format" is for the file name? If so, perhaps you could mention that in the explanation and add a file ending like ".mkv" to the example. If it's not the file name, what is it?

2. Please add the original file name of the movie / NZB to the movie folder options. I prefer to keep folders like "Movie.Title.2010.1080p.BluRay.DTS.x264-EVOLVE".
Actually, all my movies are in folders like "Movie.Title.2010.1080p.BluRay.DTS.x264-EVOLVE" which contain files like "Movie.Title.2010.1080p.BluRay.DTS.x264-EVOLVE.mkv".

Thanks, guys.

**Comment by onedr0p** [comment]
The problem with Original filename is some are obfuscated, and if we allows that option it would create other issues in the future. e.g. "Why is my movie called 7h843ghsg47wgh7g4hw8s2pfh.mkv"

**Comment by theotherp** [comment]
CP allows using the "original folder" and "original filename". I'm not aware there have been too many (or any) complaints about "weird filenames".

I understand not implementing features that could lead to issues (I've had a lot of those with NZBHydra) but as renaming is an "advanced" feature anyway I'd hope you could implement it anyway. Until then I'll need to disable downloaded file handling and let CP do the renaming.

**Comment by theotherp** [comment]
Well, looking at #393 I understand your hesitation. Still... ;-)

**Comment by c0rnflake** [comment]
I've asked for more or less the same option for folders, I also keep all my movies in a scene named folder pretty much identical to the OP.  I also migrated from CP and don't recall ever having the issue with obfuscated release names, although I'm sure that happened occasionally, but at a low percent.

Would it make sense to add the option as the original nzb name then? or compare the two before creating the folder?

**Comment by galli-leo** [comment]
Fedoranimus is currently rewriting the Movie folder renaming so that we could potentially rename it with qualities. That should open the way for using original title in the folder name.

**Comment by Metigoth** [comment]
Scene naming would be more like this:
Movie.Title.2010.1080p.BluRay.DTS.x264-EVOLVE.mkv

Renamer has them coming out like this
{Movie.Title}.{Release Year}.{Quality.Title}.{MediaInfo.Simple}-{Release.Group}
Movie.Title.2010.BluRay-1080p.DTS.x264-EVOLVE.mkv

It is ignoring choice in a separator.

Otherwords 720p or 1080p should be before Bluray.

**Comment by galli-leo** [comment]
@Metigoth You can change the quality title in settings. So you could change BluRay-1080p to 1080p.Bluray

**Comment by Metigoth** [comment]
That doesn't fix the naming issue if they are not all 1080p.Bluray.

**Comment by galli-leo** [comment]
@Metigoth Not quite sure I understand? You can just change it for every other quality.

**Comment by Metigoth** [comment]
What good is automated system with a renamed if I keep having to manually set or rename the files. Please fix the renamer or give more options for it to rename correctly.

Thank you

**Comment by galli-leo** [comment]
@Metigoth I think you misunderstood. You only need to change the Quality title in settings once. Then it will be set for all your files. (Settings -> Quality)
<img width="679" alt="screen shot 2017-02-23 at 15 25 30" src="https://cloud.githubusercontent.com/assets/5339762/23262846/5f90e64c-f9dc-11e6-82a7-bc058ee14281.png">

**Comment by Metigoth** [comment]
Thanks, that makes since now.

**Comment by Metigoth** [comment]
Will you please, add the edition as an option in the renamer settings?

{Movie.Title}.{Release Year}**.{Edition}**.{Quality.Title}.{MediaInfo.Simple}-{Release.Group}

**Comment by galli-leo** [comment]
@Metigoth Already in there using {Edition.Tags} :) Just not in the ui options.

**Comment by galli-leo** [comment]
2. of the original request is now possible.
