### ISSUE TITLE
Release Profiles

### ISSUE THREAD

**Issue by samip5** [Radarr/Radarr#3981]
**Is your feature request related to a problem? Please describe.**
Yes, it's related to not wanting CAM rips and having specific release group releases have higher priority and/or those which have 5.1 audio at least.

**Describe the solution you'd like**
Something similar to Sonarr's Release Groups, if not the exact same.

**Additional context**
![image](https://user-images.githubusercontent.com/1703002/71284783-3ae8d900-236c-11ea-9ce6-8c08ac3822d9.png)
![image](https://user-images.githubusercontent.com/1703002/71284794-45a36e00-236c-11ea-890d-abf28c29d440.png)

**Comment by ta264** [comment]
Radarr has custom formats, it's very unlikely to get release profiles

**Comment by samip5** [comment]
@ta264 What if I do that myself and do a PR for it?

**Comment by ta264** [comment]
Removing custom formats isn't really an option, since so many people use it, and I don't think you'd be able to make release profiles and custom format coexist nicely.   They mostly duplicate each other's functionality.  If you're serious about doing it then jump on the discord to discuss but I think there'd be reluctance to have two features that did the same thing.

**Comment by ta264** [comment]
> **Describe the solution you'd like**
> Something similar to Sonarr's Release Groups, if not the exact same

^^ You're describing custom formats here

**Comment by Sipherdrakon** [comment]
Everyone is right that this is custom formats in a nut shell, but maybe make custom formats more user friendly. If that's the case then I'm all for it. I love the release profile option on sonarr. It's super easy to understand and implement. But radarr custom formats looks very intimidating and can be pretty hard for some people to wrap their heads around.

**Comment by ta264** [comment]
They have been improved in v3
