### ISSUE TITLE
Can't use 2000 category in Jackett

### ISSUE THREAD

**Issue by logos88** [Radarr/Radarr#3986]
**Description:**
I can't put inside the indexer Jackett the category 2000. When I add this category and press test button says "Unable to connect to indexer, check the log for more details"
This category is needed for some indexer like MejorTorrent or Elitetorrent which use it for almost everything.

**Radarr Version:** v3.0.0.2325

**Mono Version:** 6.4.0.198-1

**Debug Logs:**
https://pastebin.com/T6z469Hb

**Comment by Qstick** [comment]
Logs appear to show errors coming back from Jackett, you should likely get with them on this.
