### ISSUE TITLE
Feature Request: Multi language

### ISSUE THREAD

**Issue by Noorbertt** [Radarr/Radarr#399]
Multi language profiles possible?

Example if there is no language (A) on the list wait unil (X) days and if not there do the (B) language.

**Comment by onedr0p** [comment]
Moved discuss to http://feathub.com/Radarr/Radarr/+4

**Comment by tac00** [comment]
+1 for this option. Most of my movies cant be auto downloaded because some contains the words NORDiC etc. And then Radarr thinks the torrent is in Norwegian language but its wrong its still in english.

**Comment by galli-leo** [comment]
@tac00 Can you post examples of release names like that?

**Comment by tac00** [comment]
@galli-leo, you can see these two releases. Its the same movie released by two different groups/torrent sites.:
![](https://i.imgur.com/4Bm6ci9.png)
![](https://i.imgur.com/EueeR0G.png)

**Comment by casperse** [comment]
Yes same problem here +1 for a workaround to this.... putting NORDiC in a tag dosent help...

**Comment by jimlei** [comment]
I hope this get added, and in a way that will getting multiple languages. For non english countries it makes sense to get the local language for kids, but larger kids (aka adults) may want those movies in their original languages. Lots of animated movies do a great job entertaining both audiences :)

**Comment by kyppo** [comment]
I second this feature request.

Feathub is down, so can't show my support there.

**Comment by galli-leo** [comment]
This is now implemented with custom formats.
