### ISSUE TITLE
Support xattr - using Flexget + Filebot + Radarr

### ISSUE THREAD

**Issue by stevezau** [Radarr/Radarr#3992]
Will radarr ever support xattr source/quality in a file? See here for more info https://www.filebot.net/forums/viewtopic.php?f=8&t=11363

My setup
1. Flexget listens to RSS feeds and auto-download things.
--- I am using flexget as it is extremely flexible and meets several of my adv logic/requirements.
--- Also allows me to send things to pending approval, ie high rated items not on my lists

2. Flexget sends to tor downloader..

3. Filebot picks the download extracts and renames.
--- file names do not include the quality.

4. Scripts is run to auto add new path to radarr.

This all mostly works ok. I use Radarr for ad-hoc and upgrades. The problem is Radarr is not picking up the quality. This is because the quality is not in the name, instead, filebot adds them to xattrs.

I want to get the quality imported into radarr somehow. I'm fine to script a write just not sure it is even possible?

Any suggestions?
Top

**Comment by ta264** [comment]
If you want support for the attribute then you'll probably have to write it yourself.

Radarr can only detect source from file name at the moment so you'll need to add it to your naming schema.

You may be able to achieve what you want via custom formats and get rid of filebot. Radarr isn't really designed for what you want it to do

**Comment by stevezau** [comment]
Hi @ta264,

Thanks for your reply.

Are you able to point me in the right direction if i wanted to add support? I haven't ever touched the radarr code base. I had a quick look, feels daunting getting started. 

I had a look at custom formats.. I didn't think it was valid for my use case?

NOTE: I would consider replacing filebot with Radarr but it appears radarr cannot do "renames" out of band. 

Thanks for your support / advice!

**Comment by ta264** [comment]
I'd suggest jumping on the discord channel to discuss further

**Comment by stevezau** [comment]
I posted there first in #support

**Comment by ta264** [comment]
Workaround discussed in discord
