### ISSUE TITLE
[Bug, Aphrodite] Renaming files on cloud mounts result in downloading and reuploading files

### ISSUE THREAD

**Issue by Silent-Remux** [Radarr/Radarr#3994]
**Describe the bug**
Renaming files on cloud mounts result in downloading and re-uploading files.

**To Reproduce**

```
ExecStart=/usr/bin/mergerfs \
  -o category.create=ff,async_read=false,cache.files=partial \
  -o dropcacheonclose=true,use_ino,minfreespace=0 \
  -o xattr=nosys,statfs_ignore=ro,allow_other,umask=002,noatime,nonempty \
  /mnt/local=RW:/mnt/remote=NC:/mnt/remote2=NC:/mnt/movies=NC /mnt/unionfs
ExecStop=/bin/fusermount -u /mnt/unionfs
```

According to mergerfs wiki, `NC will exclude those paths from create policies (you can't create but you can change / delete).`

Sonarr does **not** have this issue, it renames without downloading and re-uploading so this is a Radarr specific problem.

1. Go to a movie
2. Click on 'Preview Rename'
3. Click on 'Organize'
4. Watch the file download via `ncdu /mnt/local/Media` and then reupload.

**Expected behavior**
File to be renamed by not downloading the file.

**Comment by LooseSeal2** [comment]
@Silent-Remux  This is not an issue with Radarr. This is an issue with how you have your docker volumes defined. This is a cloudbox issue.

**Comment by Silent-Remux** [comment]
> 
> 
> @Silent-Remux This is not an issue with Radarr. This is an issue with how you have your docker volumes defined. This is a cloudbox issue.

Sonarr does server-side moves with the same mount. Explain that.

**Comment by Silent-Remux** [comment]
To provide further clarification, this is how I have my path mappings set.

![firefox_tbcuPjle9R](https://user-images.githubusercontent.com/16107603/71424546-734d2780-268a-11ea-99e1-27b7642dbcc0.png)

**Comment by robertbaker** [comment]
If you had proper volume definitions you wouldn't need those mappings.

Each docker volume listed, in cloudbox it's at least 1 volume for downloads, 1 for media, 1 for unionfs, etc. You cannot hardlink/rename/move between separate docker volumes.

**Comment by ta264** [comment]
I disagree, I think this is a legitimate issue with net core being too timid with rename and falling back to copy/delete too easily.  See #3999

**Comment by ta264** [comment]
See #3999

**Comment by Qstick** [comment]
Fixed in https://github.com/Radarr/Radarr/commit/10fc0b071fae9807fa456144b0708d95574d17ff
