### ISSUE TITLE
Upgraded movies are treated as deleted ones and get unmonitored.

### ISSUE THREAD

**Issue by translit** [Radarr/Radarr#4006]
**Describe the bug**
Upgraded movies are treated as deleted ones and get unmonitored.

**To Reproduce**
1. Enable 'Unmonitor Deleted Movies' in 'Settings/Media Management'.
2. Upgrade an existing movie, e.g. 720P to 1080P. The 720P version will get deleted. So far so good.
3. Now go to 'Movies' and see the movie 'unmonitored'. This is unexpected.

**Expected behavior**
Upgraded movies should not be equated with deleted ones and should stay monitored even when 'Unmonitor Deleted Movies' is on.

**Desktop (please complete the following information):**
 - OS: Synology DSM, Docker
 - Version 0.2.0.1450

**Comment by gibxxi** [comment]
I agree with the OP, but *ONLY* for scenarios where the cutoff quality is still unmet. If the movie has been upgraded to the final (requested) quality, then it *SHOULD* be unmonitored IMHO.

**Comment by fryfrog** [comment]
I know it is super late, but I've used unmonitor deleted in both sonarr and radarr for *ages* and movies/episodes being upgraded *doesn't* trigger them to be unmonitored. You've got something else going on and need support.
