### ISSUE TITLE
[Bug] Webhooks keep changing from POST to PUT

### ISSUE THREAD

**Issue by Silent-Remux** [Radarr/Radarr#4019]
**Describe the bug**
I use a webhook to trigger a scan on a remote box.

I do use a password manager and while it tries to hit autofill, I do remove that data before I hit save on the webhook.

**Expected behavior**
The webhook to set as POST and stay as POST when I hit save.

**Screenshots*

![firefox_L3odHLbvIe](https://user-images.githubusercontent.com/16107603/71633558-c5eb8e00-2c0c-11ea-80f8-ad84bffa49a7.png)

**Comment by Silent-Remux** [comment]
Haven't seen this for a while.

**Comment by Qstick** [comment]
I'm wondering if it's a migration thing... We can open it back up if someone else complains about it. Thanks
