### ISSUE TITLE
Movies added through Ombi are moved and renamed twice

### ISSUE THREAD

**Issue by VanCityGuy** [Radarr/Radarr#402]
Radarr Version:
0.2.0.210

Operating System:
Mac OSX 10.11.4

Mono Version (only if your not on windows)
4.6.2

Problem Description:

After using an old plex request channel and couchpotato for movies, today
I updated to Radarr and Ombi. I tested Radarr first, downloaded a few
movies, and it moved it from my completed folder out of Sabnzbd to my media
drive, and renamed it as I specified in the settings. Then I added the
latest version of Ombi to equation, and I am able to add a request, have it
add it to Radarr, download and complete. The issue now is that when the
movie goes through Ombi, it seems to duplicate the move and rename process.
It now comes with two directories of the movie: one has I have it in the settings: {Movie Title} ({Release Year}), and second mystery version: {Movie Title} (0):

Eg:
/Volumes/Media_Movies/Movies:
    /Moonrise Kingdom (2012)
        Moonrise Kingdom.mkv
    /Moonrise Kingdom (0)
        Moonrise Kingdom.mkv

It seems like they move simultaneously as sometimes if Radarr finished with one of the renames first it will remove the original downloaded files, as it should and will leave an orphaned version in one of the two folders, something like this: Moonrise Kingdom~.partial

I submitted this issue to the Ombi Github, but the dev basically said that Ombi will never move or rename media, so I am wondering if something about having a movie sent to it by Ombi is causing Radarr to double the rename and move post-process?

Reproduction Steps:

Add a movie from Ombi with only Radarr configured in the settings

Ombi sends the request to Radarr

Radarr snags the request, downloads it, sends it to Sabnzbd, and moves the
completed files to my media drive.

Ombi also seems to be doing the move and rename step.

This only happens when I use Ombi to send a request to Radarr. Movies added directly within Radarr do not have this issue.

**Comment by fedoranimus** [comment]
I'm unable to get my Ombi to connect to the my debug version of Radarr, but I will try again tomorrow.

Could you provide Radarr logs for when a movie you added via Ombi finishes?

**Comment by VanCityGuy** [comment]
So silly me, the reason it was duplicating is because I still had Couchpotato running and the renamer turned on so it was doubling up. I disabled the CP renamer and now it just creates one version. however it is the incorrect version with (0) in the movie name. Here is an example with logs. This is what I ended up with: /Volumes/Media_Movies/Movies/Aladdin (0)/Aladdin.mkv

Here are the logs:

```
[v0.2.0.210] System.NullReferenceException: Object reference not set to an instance of an object
  at NzbDrone.Core.Extras.ExtraService.Handle (NzbDrone.Core.MediaCover.MediaCoversUpdatedEvent message) [0x00007] in C:\projects\radarr-usby1\src\NzbDrone.Core\Extras\ExtraService.cs:106 
  at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent] (TEvent event) [0x000c3] in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Events\EventAggregator.cs:56 

17-1-23 20:05:45.1|Info|RefreshMovieService|Updating Info for Aladdin
17-1-23 20:05:45.7|Info|DiskScanService|Scanning disk for Aladdin
17-1-23 20:05:45.7|Info|MovieScannedHandler|[Aladdin] was recently added, performing post-add actions
17-1-23 20:05:45.7|Info|MediaCoverService|Downloading Poster for [tt0103639][Aladdin] http://image.tmdb.org/t/p/original/qsHpmqekgeQKMKL8PWnFsrXTXGs.jpg
17-1-23 20:05:45.8|Info|NzbSearchService|Searching 2 indexers for [Aladdin]
17-1-23 20:05:46.3|Info|MediaCoverService|Downloading Banner for [tt0103639][Aladdin] http://image.tmdb.org/t/p/original/oZN5w508NSlrmcMql1wohhsQGIg.jpg
17-1-23 20:05:46.9|Error|EventAggregator|ExtraService failed while processing [MediaCoversUpdatedEvent]

[v0.2.0.210] System.NullReferenceException: Object reference not set to an instance of an object
  at NzbDrone.Core.Extras.ExtraService.Handle (NzbDrone.Core.MediaCover.MediaCoversUpdatedEvent message) [0x00007] in C:\projects\radarr-usby1\src\NzbDrone.Core\Extras\ExtraService.cs:106 
  at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent] (TEvent event) [0x000c3] in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Events\EventAggregator.cs:56 

17-1-23 20:05:55.9|Info|DownloadDecisionMaker|Processing 26 releases
17-1-23 20:06:01.1|Info|Sabnzbd|Adding report [Aladdin.1992.720p.BRRip.x264.AC3-MAJESTiC-Obfuscated] to the queue.
17-1-23 20:06:01.5|Info|DownloadService|Report sent to Sabz. Aladdin.1992.720p.BRRip.x264.AC3-MAJESTiC-Obfuscated
17-1-23 20:06:01.5|Info|MovieSearchService|Movie search completed. 1 reports downloaded.
17-1-23 20:11:33.5|Warn|UpgradeMediaFileService|The existing movie file was not lazy loaded.
17-1-23 20:12:14.6|Error|EventAggregator|MovieMissingModule failed while processing [MovieDownloadedEvent]

[v0.2.0.210] System.NullReferenceException: Object reference not set to an instance of an object
  at NzbDrone.Api.NzbDroneRestModuleWithSignalR`2[TResource,TModel].BroadcastResourceChange (NzbDrone.Core.Datastore.Events.ModelAction action, System.Int32 id) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Api\NzbDroneRestModuleWithSignalR.cs:38 
  at NzbDrone.Api.Wanted.MovieMissingModule.Handle (NzbDrone.Core.MediaFiles.Events.MovieDownloadedEvent message) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Api\Wanted\MovieMissingModule.cs:74 
  at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent] (TEvent event) [0x000c3] in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Events\EventAggregator.cs:56 

```

**Comment by fedoranimus** [comment]
Okay, that makes this a lot more reasonable of an issue. Thanks for the update.

**Comment by SuperPotatoMen** [comment]
@VanCityGuy can you update your Ombi version in the eap branch. We have patched the issue on our side

**Comment by VanCityGuy** [comment]
All fixed after updating to the latest eap commit of Ombi. Thanks everyone, both the Radarr and Ombi dev teams are awesome, thanks for the great support and excellent apps!
