### ISSUE TITLE
cant start the app to begin setup

### ISSUE THREAD

**Issue by ramymounir** [Radarr/Radarr#4020]
I have A Qnap system with Plex, sabnzbd, Qsonarr installed and working
I installed Radarr but I cant begin to set it up. this is the message I get on safari when I click the app icon..
Safari cant open the page "192.168.1.100:7878" because safari can connect to server 192.168.1.100

all the other apps I have on Qnap are working fine. I can also run Qsonarr on 192.168.1.100:8989

**Comment by Qstick** [comment]
This is most likely a setup issue, and we don’t officially support qnap. Jump on discord and I’m sure someone can help, but your version maybe ancient depending on where you are getting it.
