### ISSUE TITLE
[Aphrodite] Queue does not empty after files deleted

### ISSUE THREAD

**Issue by Silent-Remux** [Radarr/Radarr#4022]
**Describe the bug**

Files older than 60 minutes are deleted if they cannot be imported on my server using a script.

Right now in aphrodite, if a file has been deleted, the queue does not clear like in Sonarr v3.

Happens with all downloads so don't think log is necessary here.

**Expected behavior**

The queue to clear after a while.

**Screenshots**
![T6JCPNpDAp](https://user-images.githubusercontent.com/16107603/71685346-ec860200-2d8f-11ea-8ef6-55044d0369d9.png)

**Desktop (please complete the following information):**
 - OS: `Ubuntu 18.04.3 LTS`
- Radarr: `3.0.0.2440`

**Comment by ta264** [comment]
A log of it happening in sonarr and not happening in Radarr would give us a place to start looking

**Comment by fryfrog** [comment]
The queue shows everything in your download client that matches the category you've set. Is that item still in your download client?

**Comment by Silent-Remux** [comment]
Ignore me, I think I spoke too soon.
