### ISSUE TITLE
Easy disk swap

### ISSUE THREAD

**Issue by DecipherIt** [Radarr/Radarr#4027]
**Is your feature request related to a problem? Please describe.**

It's so frustrating that you can't swap disks easily, I have 2 full disks and when I try to switch to the 3rd I have to google (and even make a topic here) to find out how it works.
Maybe i'm missing something because I can't get it to work but either way it's not easy to do/find!

**Describe the solution you'd like**

In system allow to swap all current "Disk A" to "Disk B" while leaving previous settings alone. A sort of new disk feature that isn't RAID, click and select a new one and you're done.

**Describe alternatives you've considered**

Throwing out the computer but that doesn't help :P

**Comment by fryfrog** [comment]
Just use Movie Editor and change root folders.

Even better, use a merge file system so you don't even have to worry about disks at a high level.

**Comment by DecipherIt** [comment]
Some of us can't afford a proper running nas @fryfrog that's not fair to mention.

I just finished using movie editor by hand, I started an hour before I posted this and I just finished. That's 5 hours of no automation...

I wouldn't write this off as closed while it's not impossible to add a feature to fix this without that much work for you.

**Comment by fryfrog** [comment]
You don't need a NAS to use a merge file system. If you're using Linux, mergerfs is free. If you're using Windows, StableBit's DrivePool is not very expensive. They work w/ any number of disks, it is worth doing even if you only have two disks.

In Radarr/Sonarr's v3 interface, the movie editor will offer to *physically* move the files too, when you change them in Movie Editor. So it'll be easier and faster in the future. But even now, it shouldn't have taken you that long. Just physically move the files and then adjust the ones you moved. If you have movies on multiple disks, they'll be in multiple root folders, right? So sort by root folder and only edit the ones that matter. Or if you're moving only some of them, do it based on something that you can easily sort by. Remember you can tick and then shift-tick to select a range.

**Comment by DecipherIt** [comment]
All drives are encrypted and mount one at a time on an old windows system (DIY NAS very badly done) so that doesn't merge with StableBit unfortunately, but thanks for the suggestion :)

I wasn't moving anything, that's the problem. The disk is full and now it's a "full, next please" kind of situation. The select all function dragged all monitored and unmonitored files at once so I was just fast enough to stop that and the same happened when I selected just unmonitored (I still hate that monitored system, I love radarr but upgrade once if yes vs monitoring... personal opinion maybe) and the only other way to do it was sorting the files already snatched, marking them, 10 at a time, as "needs to be on old disk" and marking the rest as "for new disk".
It was a 100 pages so it was a lot of work to do manually haha.

**Comment by fryfrog** [comment]
There is a UI setting to show more items on a page, in General I think.

I don't use Windows for this, nor DrivePool so I'll take your word for it.

**Comment by DecipherIt** [comment]
That would make things easier because it took forever.

I don't know what v3 will look like but maybe you could look into a quick switch method (everything that is done stays where it is and new stuff will go to new directory) to make it easy for people using PC's with multiple HDD's and not accidentally move everything or screw things up otherwise.

Honestly the biggest feature request I can think of is "if downloaded and processed mark unmonitored" but that's something I wanted to see since v1, it would save so much time in setups like I have.

**Comment by ta264** [comment]
Isn't the solution to your monitoring issue to just set the quality cutoff to the lowest quality you allow? Then it'll download once and not upgrade.

**Comment by DecipherIt** [comment]
I did that but that doesn't mark it as unmonitored, it's done but keeps checking.

Upgrade once is say you want 4k proper but watching 1080p is fine too it snatches 1080p because that is first available and then waits for 4k, after that it marks it as complete.

Monitor looks for your lowest quality, snatches and adds to your collection, then 4k becomes available and it snatches that but after that it keeps monitoring, it's never done monitoring unless you manually stop it.

**Comment by fryfrog** [comment]
I think you maybe don't understand how Sonarr/Radarr find things. In a correctly setup library w/ correctly setup profiles, *everything* should be Monitored. No matter what. Let's stop teaching in this issue, hop on Discord and talk w/ a few people to help you understand how Radarr works and how to use it and how to set it up correctly.
