### ISSUE TITLE
Aphrodite: Seed ratio config not being saved after upgrade to 3.0.0.2461

### ISSUE THREAD

**Issue by arpitgupta** [Radarr/Radarr#4031]
Before i upgraded to the latest preview version i was using the seed ration setting for indexers. However after upgrade to the latest version the value i had entered does not show up when i view advanced settings for an indexer.

I tried adding it again and saving it and it does not get presisted. There are no errors in trace logs either when i try to save the seed ratio setting so not sure what could be happening.

I am trying this on Chrome browser.

Version
3.0.0.2461
.NET Core
Yes
Docker
Yes
DB Migration
163

**Comment by Qstick** [comment]
Which indexer? Also what version were you previously on?

**Comment by arpitgupta** [comment]
These are torznab indexers via Jackett.

Don't recall the earlier version. Last update I did was about 25-26 days
ago. Is the version upgrade info persisted any where? I did another one
today to confirm if the newer version had the same issue or not. I had done
an update yesterday and I saw the issue come up.


--
Arpit

**Comment by Qstick** [comment]
Thanks I’m able to reproduce, will figure out when it was broken and see about a fix.
