### ISSUE TITLE
Add notification option for importing from list

### ISSUE THREAD

**Issue by mrchops1024** [Radarr/Radarr#4038]
**Is your feature request related to a problem? Please describe.**
I use the StevenLu list but choose to not automatically monitor movies. Instead I like to only monitor the ones that I plan on watching. Currently I have enabled automatic sync for the list and I have to remember to check the UI every so often for new movies.

**Describe the solution you'd like**
I would like a notification option (perhaps when configuring a connection) that will allow me to send a notification when a movie is imported via a list. For example, I use Pushover to send me notifications when grabbing a new movie. Perhaps there could be an option to enable 'On Import' and then specify a list.

**Describe alternatives you've considered**

**Additional context**

[AB#884](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/884)

**Comment by Qstick** [comment]
So what if 70 movies get added at once from various lists, you want 70 notifications? I could see implementing this and doing one notification per list sync (1 per batch of movies added), but not sure about spamming on every movie added.

**Comment by mrchops1024** [comment]
1 notification per sync is actually ideal.

**Comment by ricreis394** [comment]
> So what if 70 movies get added at once from various lists, you want 70 notifications? I could see implementing this and doing one notification per list sync (1 per batch of movies added), but not sure about spamming on every movie added.

This is ideal if thinking only for lists, but we could make it more generic. For example, in my case I have a need to have custom post processing just after adding a movie, not only from lists, but in general. In my setup I don't choose the rootpath, the post processing script will do it based on movie genre, but I prefer to have that filter on import/added not on grab.
The temporary solution I made is, when it grabs a movie it call the script, and it checks the history length of the movie, if is 1 then it takes a action else ignores. 1 means it is the first grab of that movie

**Comment by chrisjohnson00** [comment]
This would be helpful to me as well.  I wrote my own proxy to Stephen Lu's list which does filtering by genre and rating, and in the end sends push notifications for new movies that are found.
