### ISSUE TITLE
I don't think it's a bug, but it's an issue.

### ISSUE THREAD

**Issue by AnythingOldSkewl** [Radarr/Radarr#4043]
****Radarr Version:**
0.2.0.1450
**Mono Version:**
5.14.0.177
**Debug Logs:**

http://www.filedropper.com/radarrdebug**

No matter what I do, occasionally, the BLURAY profile picks up whole disc images instead of MKV files. It's especially a problem when using PLEX, because it does not read whole images, and most times I'm not even aware it's on my seedbox until I look. I tried lowering the size, but Sonarr still sends sizes in the 40GB range and up!  Today it happened with the following movie--->> 

Boy.Erased.2018.MULTi.COMPLETE.BLURAY

Logs attached. 
--

**Comment by AnythingOldSkewl** [comment]
No, it id not a support issue. This is a problem. Is it possible for the developers to programmatically only allow MKV files in the "bluray" profile? That is the only solution I can think of that would solve this.

**Comment by AnythingOldSkewl** [comment]
That bot sucks... I wish we can go back to a time when human beings monitored tickets.

**Comment by fryfrog** [comment]
*Before* the download, Radarr has *no idea* what is in the download. You need to watch for these "bad" releases and find their commonality and *ban* them. If you don't mind *not* having Remuxes, I'd disable those. I *think* `BRDISK` is a common one too. In your example, it looks like you could ban `COMPLETE` too. And maybe use the size tuning to limit them as well.

@Qstick *is* the human monitoring tickets and I agree w/ his determination that this is a support issue.

**Comment by AnythingOldSkewl** [comment]
> 
> 
> _Before_ the download, Radarr has _no idea_ what is in the download. You need to watch for these "bad" releases and find their commonality and _ban_ them. If you don't mind _not_ having Remuxes, I'd disable those. I _think_ `BRDISK` is a common one too. In your example, it looks like you could ban `COMPLETE` too. And maybe use the size tuning to limit them as well.
> 
> @Qstick _is_ the human monitoring tickets and I agree w/ his determination that this is a support issue.

I thought about that. I've done it a few times with those annoying XBIT cams (whatever their called). However, this is different. blocking queried keywords is not going to guarantee that I won't still be getting those whole images. Also, I can't select webDL either because quite a few devices using PLEX does not support EAC-3.
