### ISSUE TITLE
Release Group Renaming as "Radarr"

### ISSUE THREAD

**Issue by mogodon** [Radarr/Radarr#4044]
Recently noticed that Radarr is renaming some of my movies with a release group name of "radarr" despite the file clearly stating the release group.

My format is: {Movie Title} ({Release Year}) [{Quality Title}][{MediaInfo AudioCodec} {MediaInfo AudioChannels}][{MediaInfo Video}]-{Release Group}

Example being:

Night.Comes.On.2018.1080p.WEBRip.x264-[YTS.LT] ---> 
Night Comes On (2018) [WEBDL-1080p][AAC 2.0][x264]-Radarr.mp4

Wrong.Turn.4.Bloody.Beginnings.UNRATED.2011.1080p.BRrip.x264.YIFY ---> 
Wrong Turn 4 Bloody Beginnings (2011) [Bluray-1080p][AAC 2.0][x264]-Radarr.mp4

It's not all of them though, the RARBG one's seem to be fine:

Airport.1975.1974.1080p.BluRay.H264.AAC-RARBG --> 
Airport 1975 (1974) [Bluray-1080p][AAC 2.0][x264]-RARBG.mp4

So could be a YTS/YIFY thing I guess.

Any ideas? Is "radarr" the default fallback for any movie without a recognised release group?

Radarr Version
0.2.0.1450

Mono Version
5.20.1.19
[Radarr_Logs_20200108.zip](https://github.com/Radarr/Radarr/files/4035101/Radarr_Logs_20200108.zip)

**Comment by fryfrog** [comment]
The scene standard is `-GrouP`, but I believe YIFY/YTS break that w/ their whole `[YTS]` thing. Could you give issues a search to make sure this isn't already reported? Also, I'm not sure this is an exception Radarr developers will want to program in. :/

**Comment by mogodon** [comment]
Stupidly I'd only searched the open issues. Indeed there was a bug reported for this back in Sept last year which was basically saying what you've just said. In fact it might have been you!

No worries I can manually fix any non -group entries,
