### ISSUE TITLE
Updates Page Won't Load

### ISSUE THREAD

**Issue by WeirDave** [Radarr/Radarr#4048]
**Describe the bug**
Have a QNAP with Radarr version 0.2.0.1067 . The page won't load I just get the "dots". All other pages load and the program appears to be working great!

**To Reproduce**
1. Go to System-> Updates
2. Pages does not load

**Expected behavior**
The page should load with current versions

**Screenshots**
![image](https://user-images.githubusercontent.com/798425/72028479-a679e400-3250-11ea-8ee8-e0eea258301a.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] - QNAP NAS Firm: 4.4.1.1146
 - Mono Version: [e.g. Mono 5.8] (Only needed under Linux and Mac, found under System -> Status) - V 5.20.1.19
 - Browser and Version [e.g. chrome, safari] (Only needed for UI issues) Tried Firefox and Chrome and both in private mode as well
 - Version [e.g. 22] - FF v22.0.1 - Chrome: Version 79.0.3945.117 
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/4038047/radarr.debug.txt)

**Debug Logs**
Turn on debug logs under Settings -> General and wait for the bug to occur again. **Upload the full log file here (or another site and link it). Issues will be closed, if they do not include this!**

**Comment by Qstick** [comment]
What is your branch set to under Settings/General? It should be “develop”. Also your version is quite old

**Comment by WeirDave** [comment]
> 
> 
> What is your branch set to under Settings/General? It should be “develop”. Also your version is quite old

Yes it is old but no one has updated the QNAP version and I can't do it myself. I have it set to "develop"
