### ISSUE TITLE
Importing samples instead of movies

### ISSUE THREAD

**Issue by Cetarik** [Radarr/Radarr#4050]
Recently radarr started to fail during the importing of movies. Everything goes well, it grabs the movie downloads but when there is sample downloaded, radarr takes the sample file size about 30MB insted of 3GB file and saves it in the final folder. In web GUI the filesize is good 3GB but in folder where it was imported there is only 30MB file...

**To Reproduce**
just let it grab some release with sample inside.

**Expected behavior**
Not to import samples - for example have some filters in options what not to import

**Debug Logs**
Will upload as it occures again...

**Comment by fryfrog** [comment]
What version of Radarr? There is a size for samples, I *swear* it was in the 100MB range though. Be sure to turn logging up to Debug so they're more useful. And make a note of what gets imported, the size of the sample and the video.

If you're using SMB/CIFS and Mono, this *could* also be a partial import. :/

But until you have useful details, this is support.
