### ISSUE TITLE
"The request was aborted: Could not create SSL/TLS secure channel." connecting to indexer

### ISSUE THREAD

**Issue by MarkekJankowski** [Radarr/Radarr#4051]
I am getting an error: "The request was aborted: Could not create SSL/TLS secure channel." when trying to test connection to an indexer.... Indexer supports both TLS 1.1 and 1.2 (Running Windows version 7)

**Comment by MarkekJankowski** [comment]
Disregard....   On Windows Radarr is trying to connect to Indexer using TLS 1.1... and Indexer was just updated to use TLS 1.2... Thats why I was getting that error...

Setting a default for >NET in registry fixes the issue...
[HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\.NETFramework\v4.0.30319]

"SchUseStrongCrypto"=dword:00000001


[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework\v4.0.30319]

"SchUseStrongCrypto"=dword:00000001

 

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework\v2.0.50727]

"SystemDefaultTlsVersions"=dword:00000001

 

[HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\.NETFramework\v2.0.50727]

"SystemDefaultTlsVersions"=dword:00000001

**Comment by fryfrog** [comment]
Thanks for figuring out and solving it, but I wonder why more haven't run into it? More and more sites are enforcing higher versions of TLS. :/

**Comment by DanielRTRD** [comment]
This fixed the issue for me too! Running Windows 10. Maybe create a "common problems"-topic in the wiki?

**Comment by traintrax** [comment]
I am so glad I stumbled across this.  It fixed the same issue for me on Windows 2012R2 server. @MarkekJankowski thank you.
