### ISSUE TITLE
Foreign movies now use foreign alphabet

### ISSUE THREAD

**Issue by Buster14** [Radarr/Radarr#4052]
**Radarr Version:** 0.2.0.1459

**Mono Version:**

**Debug Logs:**

Hi, with the recent version, when i try to add asian and indian movies,
radarr now uses non-roman alphabet when creating the folder and the movie itself.
e.g
When i try to add "svaha the sixth finger",

Radarr creates this folder 사바하 (2019)

I'm not sure if it's related, but now all links to my asian and indian movies are broken.
And secondly, my indexer couldn't grab the correct movie anymore, i suspect because of this behavior as well.

I don't see any option on rename movies to default to roman alphabet..  any thoughts?

**Comment by Qstick** [comment]
Dupe #4046
