### ISSUE TITLE
Log entries have 2-digit years, confusing certain log-viewers

### ISSUE THREAD

**Issue by wirerydr** [Radarr/Radarr#4053]
**Describe the bug**
Radarr emits log entries that possess 2-digit dates, and 1-2 digit days/months.  For example
````
│20-1-9 21:29:12.9|Info|ExistingSubtitleImporter|Found 0 existing subtitle files                                    │
│20-1-9 21:29:13.0|Info|ExistingOtherExtraImporter|Found 0 existing other extra files                               │
│20-1-9 21:29:13.0|Info|MediaCoverService|Testing: NzbDrone.Core.Messaging.Commands.CommandQueueManager, 18         │
````

This has the effect of confusing several (admittedly boneheaded) log-viewers, such as multitail and lnav.  For example, lnav displays the following:
````
│20-1-9 21:29:13.2|Info|MediaCoverService|Testing: NzbDrone.Core.Messaging.Commands.CommandQueueManager, 58         │
                          ┌──── Last message: over 48 years ago; Files:  1; Error rate: 0.00/min; Time span:  ────┐ │
````

**To Reproduce**
1. Generate some logging
2. Verify that the log-entry dates start with something like **20**
3. Verify that ```lnav``` mistakenly reports _Last message: over 48 years ago_
4. Edit the last line in the log file such that the year now shows as _**2020**_ and not _20_
5. Re-verify that lnav now correctly reports the elapsed time since the last message.

**Expected behavior**
Dates in Radarr's log should be in 4-digit form, to avoid ambiguity and help boneheaded log-parsers do their jobs properly.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Fedora 64-bit
 - Mono Version: 5.20.1.34
 - Version 0.2.0.1450

**Debug Logs**
_(See logging example output above.)_

**Comment by Qstick** [comment]
https://github.com/Radarr/Radarr/blob/06b56db67c7fbccc7bd060967fd5154970bdcb4e/src/NzbDrone.Common/Instrumentation/NzbDroneLogger.cs#L15
