### ISSUE TITLE
Media Scanner doesn't always detect changes within files when re-encoded (even manually)

### ISSUE THREAD

**Issue by marshalleq** [Radarr/Radarr#4055]
**Describe the bug**
After encoding an existing movie referenced by the library to a new format (hevc / h265), the media scanner doesn't always detect the new codec, nor the new file size.

**To Reproduce**
1. Re-encode existing file to h265 / hevc with tdarr
2. Scan the movie(s) for changes by either 
 2a Clicking update movie info and scan disk or
 2b Clicking update library on main screen
3 New media codec is 
 3a Not detected by Radarr within the movie under files, media info
 3b New Media size is not detected under movie, files size
4 Permissions set to 777 and correct user / group for testing purposes

**Expected behavior**
Correct media codec information shows up and file size is reported correctly

**Desktop (please complete the following information):**
 - OS:  Docker
- Radarr Version 0.2.0.1450
 - Mono Version: 5.20.1.34
 - Browser and Version Firefox / Safari

**Debug Logs**
20-1-12 08:58:48.5|Debug|Api|[GET] /api/extrafile?movieId=1055&sort_by=relativePath&order=asc: 200.OK (7 ms)
20-1-12 08:58:48.5|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (2 ms)
20-1-12 08:59:02.2|Debug|Api|[POST] /api/command: 201.Created (8 ms)
20-1-12 08:59:02.2|Info|RefreshMovieService|Updating Info for Kingsman: The Secret Service
20-1-12 08:59:03.3|Debug|RefreshMovieService|Finished movie refresh for Kingsman: The Secret Service
20-1-12 08:59:03.3|Debug|MediaInfoFormatter|Formatting audio channels using 'AudioChannelPositions', with a value of: '3/2/2.1'
20-1-12 08:59:03.7|Info|DiskScanService|Scanning disk for Kingsman: The Secret Service
20-1-12 08:59:03.7|Debug|DiskScanService|Scanning '/movies/High Definition/Kingsman The Secret Service (2014)' for video files
20-1-12 08:59:03.7|Debug|DiskScanService|1 video files were found in /movies/High Definition/Kingsman The Secret Service (2014)
20-1-12 08:59:03.7|Debug|DiskScanService|[Kingsman: The Secret Service (2014)][tt2802144, 207703] Cleaning up media files in DB
20-1-12 08:59:03.7|Debug|ImportDecisionMaker|Analyzing 0/1 files.
20-1-12 08:59:03.7|Debug|ImportApprovedMovie|Decisions: 0
20-1-12 08:59:03.7|Info|DiskScanService|Completed scanning disk for Kingsman: The Secret Service
20-1-12 08:59:03.7|Debug|ExistingExtraFileService|Looking for existing extra files in /movies/High Definition/Kingsman The Secret Service (2014)
20-1-12 08:59:03.7|Debug|DiskScanService|Scanning '/movies/High Definition/Kingsman The Secret Service (2014)' for non-video files
20-1-12 08:59:03.7|Debug|DiskScanService|0 non-video files were found in /movies/High Definition/Kingsman The Secret Service (2014)
20-1-12 08:59:03.7|Debug|ExistingMetadataImporter|Looking for existing metadata in /movies/High Definition/Kingsman The Secret Service (2014)
20-1-12 08:59:03.8|Info|ExistingMetadataImporter|Found 0 existing metadata files
20-1-12 08:59:03.8|Debug|ExistingSubtitleImporter|Looking for existing subtitle files in /movies/High Definition/Kingsman The Secret Service (2014)
20-1-12 08:59:03.8|Info|ExistingSubtitleImporter|Found 0 existing subtitle files
20-1-12 08:59:03.8|Debug|ExistingOtherExtraImporter|Looking for existing extra files in /movies/High Definition/Kingsman The Secret Service (2014)
20-1-12 08:59:03.8|Info|ExistingOtherExtraImporter|Found 0 existing other extra files
20-1-12 08:59:03.8|Info|ExistingExtraFileService|Found 0 extra files
20-1-12 08:59:03.8|Info|MediaCoverService|Testing: NzbDrone.Core.Messaging.Commands.CommandQueueManager, 1055
20-1-12 08:59:04.1|Debug|CleanExtraFileService|Cleaning missing metadata files for movie: Kingsman: The Secret Service
20-1-12 08:59:10.6|Debug|Api|[GET] /api/config/ui: 200.OK (1 ms)
20-1-12 08:59:10.7|Debug|Api|[GET] /api/system/status: 200.OK (12 ms)
20-1-12 08:59:10.7|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (3 ms)
20-1-12 08:59:10.7|Debug|Api|[GET] /api/profile: 200.OK (6 ms)
20-1-12 08:59:10.7|Debug|Api|[GET] /api/health: 200.OK (1 ms)
20-1-12 08:59:10.8|Debug|Api|[GET] /api/movie?page=1&pageSize=250&sortKey=path&sortDir=asc&filterKey=downloaded&filterValue=false: 200.OK (64 ms)
20-1-12 08:59:10.8|Debug|Api|[GET] /api/command: 200.OK (1 ms)
20-1-12 08:59:10.8|Debug|Api|[GET] /api/language: 200.OK (1 ms)
20-1-12 08:59:10.8|Debug|Api|[GET] /api/tag: 200.OK (3 ms)
20-1-12 08:59:10.8|Debug|Api|[GET] /api/series: 200.OK (1 ms)
20-1-12 08:59:10.9|Debug|Api|[GET] /api/movies/discover/lists: 200.OK (15 ms)
20-1-12 08:59:10.9|Debug|Api|[GET] /api/health: 200.OK (1 ms)
20-1-12 08:59:10.9|Debug|Api|[GET] /api/movie/titleslug/kingsman-the-secret-service-207703: 200.OK (28 ms)
20-1-12 08:59:10.9|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (3 ms)
20-1-12 08:59:11.1|Debug|Api|[GET] /api/history?page=1&pageSize=15&sortKey=date&sortDir=desc&movieId=1055: 200.OK (13 ms)
20-1-12 08:59:11.4|Debug|Api|[GET] /api/movie?page=1&pageSize=-1&sortKey=path&sortDir=asc&filterKey=filterKey&filterValue=filterValue&filterType=filterType: 200.OK (636 ms)
20-1-12 08:59:12.2|Debug|Api|[GET] /api/history?page=1&pageSize=15&sortKey=date&sortDir=desc&movieId=1055: 200.OK (14 ms)
20-1-12 08:59:14.8|Debug|Api|[GET] /api/extrafile?movieId=1055&sort_by=relativePath&order=asc: 200.OK (6 ms)
20-1-12 09:00:17.3|Debug|SabnzbdProxy|Url: http://192.168.43.10:8080/api?mode=queue&start=0&limit=0&apikey=(removed)&output=json
20-1-12 09:00:17.4|Debug|SabnzbdProxy|Url: http://192.168.43.10:8080/api?mode=history&start=0&limit=30&category=movies&apikey=(removed)&output=json
20-1-12 09:00:17.6|Debug|Parser|Parsing string 'The.Fellowship.of.the.Ring.2001.Extended.Edition.Part2.BluRay.1080p.DTS-HD.MA6.1.AVC.REMUX-FraMeSToR-4P'
20-1-12 09:00:17.6|Debug|Parser|Movie Parsed. The Fellowship of the Ring - 2001 
20-1-12 09:00:17.6|Debug|ParsingService|Language(s) parsed: 
20-1-12 09:00:17.6|Debug|QualityParser|Trying to parse quality for The.Fellowship.of.the.Ring.2001.Extended.Edition.Part2.BluRay.1080p.DTS-HD.MA6.1.AVC.REMUX-FraMeSToR-4P

**Comment by ptr727** [comment]
I'm experiencing similar problems of Radarr not detecting file content changes.

Radarr imports VC-1 BD 34GB Remux MKV.
Through background automation 34GB VC-1 is re-encoded to 12GB H264.
Radarr says file is still VC-1, and still says file is 34GB.
Click refresh, same, Radarr does not detect that the file changed.
File has to be removed or renamed, then refresh, then rename back, then refresh.

I expect Radarr to refresh the file metadata and size when the old size no longer matches the new size.

Trace while clicking refresh:
```
2020-6-1 08:00:24.7|Trace|Http|Req: 1680 [POST] /api/command
2020-6-1 08:00:24.7|Trace|CommandQueueManager|Publishing RefreshMovie
2020-6-1 08:00:24.7|Trace|CommandQueueManager|Checking if command is queued or started: RefreshMovie
2020-6-1 08:00:24.7|Trace|CommandQueueManager|Inserting new command: RefreshMovie
2020-6-1 08:00:24.7|Trace|CommandExecutor|RefreshMovieCommand -> RefreshMovieService
2020-6-1 08:00:24.7|Trace|Http|Res: 1680 [POST] /api/command: 201.Created (17 ms)
2020-6-1 08:00:24.7|Trace|CommandQueueManager|Marking command as started: RefreshMovie
2020-6-1 08:00:24.7|Debug|Api|[POST] /api/command: 201.Created (17 ms)
2020-6-1 08:00:24.8|Trace|EventAggregator|Publishing CommandUpdatedEvent
2020-6-1 08:00:24.8|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
2020-6-1 08:00:24.8|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
2020-6-1 08:00:24.8|Trace|EventAggregator|Publishing MovieRefreshStartingEvent
2020-6-1 08:00:24.8|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId)

2020-6-1 08:00:24.8|Info|RefreshMovieService|Updating Info for The Bourne Identity
2020-6-1 08:00:24.8|Trace|EventAggregator|Publishing CommandUpdatedEvent
2020-6-1 08:00:24.8|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
2020-6-1 08:00:24.8|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
2020-6-1 08:00:24.8|Trace|HttpClient|Req: [GET] https://api.themoviedb.org/3/movie/2501?api_key=1a7373301961d03f97f853a876dd1212&append_to_response=alternative_titles%2Crelease_dates%2Cvideos&language=EN
2020-6-1 08:00:24.9|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2020-6-1 08:00:24.9|Trace|HttpClient|Res: [GET] https://api.themoviedb.org/3/movie/2501?api_key=1a7373301961d03f97f853a876dd1212&append_to_response=alternative_titles%2Crelease_dates%2Cvideos&language=EN: 200.OK (36 ms)
2020-6-1 08:00:24.9|Trace|HttpClient|Req: [GET] https://api.radarr.video/v2/mappings/find?tmdbid=2501
2020-6-1 08:00:24.9|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2020-6-1 08:00:25.2|Trace|HttpClient|Res: [GET] https://api.radarr.video/v2/mappings/find?tmdbid=2501: 200.OK (293 ms)
2020-6-1 08:00:25.2|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId)

2020-6-1 08:00:25.2|Trace|EventAggregator|Publishing MovieEditedEvent
2020-6-1 08:00:25.2|Trace|EventAggregator|MovieEditedEvent -> MovieEditedService
2020-6-1 08:00:25.2|Trace|EventAggregator|MovieEditedEvent <- MovieEditedService
2020-6-1 08:00:25.2|Trace|EventAggregator|MovieEditedEvent -> MovieModule
2020-6-1 08:00:25.3|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId)

2020-6-1 08:00:25.3|Trace|EventAggregator|MovieEditedEvent <- MovieModule
2020-6-1 08:00:25.3|Trace|EventAggregator|MovieEditedEvent -> CalendarModule
2020-6-1 08:00:25.3|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId)

2020-6-1 08:00:25.4|Trace|EventAggregator|MovieEditedEvent <- CalendarModule
2020-6-1 08:00:25.4|Debug|RefreshMovieService|Finished movie refresh for The Bourne Identity
2020-6-1 08:00:25.4|Trace|EventAggregator|Publishing MovieUpdatedEvent
2020-6-1 08:00:25.4|Trace|EventAggregator|MovieUpdatedEvent -> DiskScanService
2020-6-1 08:00:25.4|Debug|MediaInfoFormatter|Formatting audio channels using 'AudioChannelPositions', with a value of: '3/2/0.1'
2020-6-1 08:00:26.0|Info|DiskScanService|Scanning disk for The Bourne Identity
2020-6-1 08:00:26.0|Trace|EventAggregator|Publishing CommandUpdatedEvent
2020-6-1 08:00:26.0|Trace|EventAggregator|CommandUpdatedEvent -> CommandModule
2020-6-1 08:00:26.0|Trace|EventAggregator|CommandUpdatedEvent <- CommandModule
2020-6-1 08:00:26.0|Debug|DiskScanService|Scanning '/media/Movies/The Bourne Identity (2002)' for video files
2020-6-1 08:00:26.0|Debug|DiskScanService|1 video files were found in /media/Movies/The Bourne Identity (2002)
2020-6-1 08:00:26.0|Trace|DiskScanService|Finished getting movie files for: [The Bourne Identity (2002)][tt0258463, 2501] [00:00:00.0058402]
2020-6-1 08:00:26.0|Debug|DiskScanService|[The Bourne Identity (2002)][tt0258463, 2501] Cleaning up media files in DB
2020-6-1 08:00:26.0|Debug|ImportDecisionMaker|Analyzing 0/1 files.
2020-6-1 08:00:26.0|Trace|DiskScanService|Import decisions complete for: [The Bourne Identity (2002)][tt0258463, 2501] [00:00:00.0041887]
2020-6-1 08:00:26.0|Debug|ImportApprovedMovie|Decisions: 0
2020-6-1 08:00:26.0|Info|DiskScanService|Completed scanning disk for The Bourne Identity
2020-6-1 08:00:26.0|Trace|EventAggregator|Publishing MovieScannedEvent
2020-6-1 08:00:26.0|Trace|EventAggregator|MovieScannedEvent -> MovieScannedHandler
2020-6-1 08:00:26.0|Trace|EventAggregator|MovieScannedEvent <- MovieScannedHandler
2020-6-1 08:00:26.0|Trace|EventAggregator|MovieScannedEvent -> UpdateMovieFileService
2020-6-1 08:00:26.0|Trace|ConfigService|Using default config value for 'filedate' defaultValue:'None'
2020-6-1 08:00:26.0|Trace|EventAggregator|MovieScannedEvent <- UpdateMovieFileService
2020-6-1 08:00:26.0|Trace|EventAggregator|MovieScannedEvent -> UpdateMediaInfoService
2020-6-1 08:00:26.0|Trace|ConfigService|Using default config value for 'enablemediainfo' defaultValue:'True'
2020-6-1 08:00:26.1|Trace|EventAggregator|MovieScannedEvent <- UpdateMediaInfoService
2020-6-1 08:00:26.1|Trace|EventAggregator|MovieScannedEvent -> ExistingExtraFileService
2020-6-1 08:00:26.1|Debug|ExistingExtraFileService|Looking for existing extra files in /media/Movies/The Bourne Identity (2002)
2020-6-1 08:00:26.1|Debug|DiskScanService|Scanning '/media/Movies/The Bourne Identity (2002)' for non-video files
2020-6-1 08:00:26.1|Debug|DiskScanService|1 non-video files were found in /media/Movies/The Bourne Identity (2002)
2020-6-1 08:00:26.1|Debug|ExistingMetadataImporter|Looking for existing metadata in /media/Movies/The Bourne Identity (2002)
2020-6-1 08:00:26.1|Debug|Parser|Parsing string 'The Bourne Identity (2002).PlexCleaner'
2020-6-1 08:00:26.1|Trace|Parser|^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(1(8|9)|20)\d{2}(?!p|i|(1(8|9)|20)\d{2}|\]|\W(1(8|9)|20)\d{2})))+(\W+|_|$)(?!\\)
2020-6-1 08:00:26.1|Debug|Parser|Movie Parsed. The Bourne Identity - 2002 
2020-6-1 08:00:26.1|Debug|Parser|Parsing string 'The Bourne Identity (2002).PlexCleaner'
2020-6-1 08:00:26.1|Trace|Parser|^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(1(8|9)|20)\d{2}(?!p|i|(1(8|9)|20)\d{2}|\]|\W(1(8|9)|20)\d{2})))+(\W+|_|$)(?!\\)
2020-6-1 08:00:26.1|Debug|Parser|Movie Parsed. The Bourne Identity - 2002 
2020-6-1 08:00:26.1|Debug|Parser|Parsing string 'The Bourne Identity (2002).PlexCleaner'
2020-6-1 08:00:26.1|Trace|Parser|^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(1(8|9)|20)\d{2}(?!p|i|(1(8|9)|20)\d{2}|\]|\W(1(8|9)|20)\d{2})))+(\W+|_|$)(?!\\)
2020-6-1 08:00:26.1|Debug|Parser|Movie Parsed. The Bourne Identity - 2002 
2020-6-1 08:00:26.1|Info|ExistingMetadataImporter|Found 0 existing metadata files
2020-6-1 08:00:26.1|Debug|ExistingSubtitleImporter|Looking for existing subtitle files in /media/Movies/The Bourne Identity (2002)
2020-6-1 08:00:26.1|Info|ExistingSubtitleImporter|Found 0 existing subtitle files
2020-6-1 08:00:26.1|Debug|ExistingOtherExtraImporter|Looking for existing extra files in /media/Movies/The Bourne Identity (2002)
2020-6-1 08:00:26.1|Info|ExistingOtherExtraImporter|Found 0 existing other extra files
2020-6-1 08:00:26.2|Info|ExistingExtraFileService|Found 0 extra files
2020-6-1 08:00:26.2|Trace|EventAggregator|MovieScannedEvent <- ExistingExtraFileService
2020-6-1 08:00:26.2|Trace|EventAggregator|MovieUpdatedEvent <- DiskScanService
2020-6-1 08:00:26.2|Trace|EventAggregator|MovieUpdatedEvent -> MovieModule
2020-6-1 08:00:26.2|Trace|Owin|SQLite warning (284): automatic index on MovieFiles(MovieId)
```
