### ISSUE TITLE
Movie files not renamed to match new codec on disk scan or any other automated trigger

### ISSUE THREAD

**Issue by marshalleq** [Radarr/Radarr#4056]
**Describe the bug**
File is not renamed to match new media codec (h265/hevc)
Sometimes media codec is not found and file is not showing up to date information (see bug [here](https://github.com/Radarr/Radarr/issues/4055) for that).  This ticket is for when it IS updated correctly.

**To Reproduce**
1. Re-encode existing file to h265 / hevc with tdarr
2. Scan the movies for changes by either 
2a Clicking update movie info and scan disk or
2b Clicking update library on main screen
3 New media codec is detected by Radarr within the movie under files, media info
4 File is not renamed

It is stated under Settings, Media Management, Auto Rename (tooltip) for folders that folders are auto renamed at each disk scan.  It is not clear when a file is renamed as this is not stated.  Only that it will be renamed.  My assumption is that this should also be triggered via a disk scan and for some reason is broken.

**Expected behavior**
I expect a regular check of files to see that they match the naming scheme if auto rename is on and static path is off.

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  Docker
- Radarr Version 0.2.0.1450
 - Mono Version: 5.20.1.34
 - Browser and Version Firefox / Safari

**Debug Logs**
I will add these when I get a re-ocurrence.

**Comment by fryfrog** [comment]
I think I saw in Sonarr chat the other day that if the *file name* doesn't change, the info won't be refreshed. If you're transcoding underneath Radarr, try changing the name some how.
