### ISSUE TITLE
Indexer request Filelist.ro

### ISSUE THREAD

**Issue by mnmlsv** [Radarr/Radarr#4061]
Filelist.ro added an api to the tracker as it was rss only before , is it possible to get them integrated into radarr? If the devs need invites I can provide them.

This is the news posted about the API:

"Before we go on to the subject from the title which is mainly targeted at developers, we wish to bring to your attention something that impacts all users. A few days ago we made some improvements to how searching torrents works, more exactly:

Torrents are now indexed in real time. Meaning that you can find it via search right after it's uploaded;
We made some improvements to the way words are analyzed for indexing. To be more specific the search will now return much more accurate results;
We have also greatly improved the algorithm which handles word positioning in the search engine, you can now find much shorter words and the relevance of the results is higher;

Let's go on with a short list of 'good-to-know' things for the API:

You can find the API at: https://filelist.ro/api.php ;
A 150 requests/hour/user limit is enforced;
All API calls have to be sent as a GET request;
The authentication is made using your username and passkey;
The API can return responses as JSON as well as XML;
At this moment there are two endpoints: search-torrents and latest-torrents;
latest-torrents works the same way as the current RSS feed with the added benefit of being able to filter by IMDb;"

For more info visit: https://filelist.ro/forums.php?action=viewtopic&topicid=120435&page=last

*FIleList staff offers a bounty for who manages to do this: permanent VIP and Special Rank Status.

**Comment by majora2007** [comment]
Wouldn't this be better through Jackett rather than in Radarr itself?
