### ISSUE TITLE
Stop grabbing release when Free Space is less than set percentage.

### ISSUE THREAD

**Issue by azumukupoe** [Radarr/Radarr#4064]
**Is your feature request related to a problem? Please describe.**
Radarr keeps grabbing releases even when there's no remaining disk space.

**Describe the solution you'd like**
An option to set a percentage for Free Space to stop grabbing. 

**Describe alternatives you've considered**

**Additional context**

**Comment by Qstick** [comment]
This is already implemented in V3, not planning to backport. It’s a user configurable min free space setpoint. In V0.2 this is implemented as a hard coded value of 100mb.

**Comment by azumukupoe** [comment]
@Qstick Thanks for the info.
