### ISSUE TITLE
manually rename files

### ISSUE THREAD

**Issue by ljmerza** [Radarr/Radarr#4065]
**Is your feature request related to a problem? Please describe.**
I cross seed a lot and the problem I run into is I have to rename files to cross seed but I can't do that in radarr so I have sftp into my server, find the files, then rename them to what I want. Then I have to go to radarr and sync with the new file name.

**Describe the solution you'd like**
I'd like to be able to rename files to whatever I want manually. In the files tab of a movie there's already a setting cog to manually set the quality, tags, etc, I'd like an input there to rename the file as well.

**Describe alternatives you've considered**
there's no alternatives in radarr, you can set a way for all movies to be renamed to a preset format but I don't want to break seeding. Generating hard links from radarr would be cool too but I'd rather have file renaming capability.

**Additional context**
![image](https://user-images.githubusercontent.com/4085765/72399862-6bc2f080-3715-11ea-9982-c5ff17101b62.png)

input here to rename a file and auto sync with the new file names

**Comment by bakerboy448** [comment]
hardlinks exist if your file system supports it

no plans for manual renaming.
