### ISSUE TITLE
Old files are not being deleted, when storage server comes back online

### ISSUE THREAD

**Issue by eeyoredk** [Radarr/Radarr#4066]
Version: 0.2.0.1450
Windows 10 Pro

Hi
This is the same bug I had on Sonarr some time ago.

When my storage server goes offline, Radarr will continue to delete files, but it does not verify that the files are actually deleted (which they are not).

When the storage server comes back online, Radarr will move the files from SABnzbd to the storage server, but does not delete the old file, since it thinks that this was already done.

This was fixed in Sonarr version 2.0.0.5049
https://forums.sonarr.tv/t/old-files-not-deleted-when-using-offline-storage/16420

Extract fro log:
https://pastebin.com/7EbUHxYP

**Comment by Qstick** [comment]
Thanks
