### ISSUE TITLE
Renaming extra files like srt files get a .1.en.srt added?

### ISSUE THREAD

**Issue by casperse** [Radarr/Radarr#4067]
**Describe the bug**
After updating files get renamed like this

ORG FILES:
Smokey.and.the.Bandit.Part.3.1983.NORDiC.1080p.BluRay.x264.mkv
Smokey.and.the.Bandit.Part.3.1983.NORDiC.1080p.BluRay.x264.fi.srt
Smokey.and.the.Bandit.Part.3.1983.NORDiC.1080p.BluRay.x264.da.srt
Smokey.and.the.Bandit.Part.3.1983.NORDiC.1080p.BluRay.x264.no.srt
Smokey.and.the.Bandit.Part.3.1983.NORDiC.1080p.BluRay.x264.nfo

RENAMED FILES: (ONLY SRT FILES GETS THE .1. )
Smokey and the Bandit Part 3 (1983) [Bluray.1080p.x264.8Bit.DTS.2.0].mkv
Smokey and the Bandit Part 3 (1983) [Bluray.1080p.x264.8Bit.DTS.2.0].1.fi.srt <-----
Smokey and the Bandit Part 3 (1983) [Bluray.1080p.x264.8Bit.DTS.2.0].1.da.srt <-----
Smokey and the Bandit Part 3 (1983) [Bluray.1080p.x264.8Bit.DTS.2.0].1.no.srt <-----
Smokey and the Bandit Part 3 (1983) [Bluray.1080p.x264.8Bit.DTS.2.0].nfo-orig

**Expected behavior**
Just renaming like before without the ".1"

the naming scheme:
{Movie Title} ({Release Year}) [{Quality Title}.{MediaInfo.VideoCodec}.{MediaInfo.VideoBitDepth}Bit.{MediaInfo.AudioCodec}.{MediaInfo AudioChannels}]

**Comment by casperse** [comment]
I can reproduce it by adding the naming scheme I am running 0.2.0.1450 - Dec 3 2019
Tuesday, December 3 2019 03:13

**Comment by casperse** [comment]
This is still a problem do you need any logs then please let me know :-)

**Comment by casperse** [comment]
Still a problem now running version:
Version
0.2.0.1450
Mono Version
5.20.1.34
AppData directory
/config
Startup directory
/opt/radarr

**Comment by fryfrog** [comment]
Might be worth trying `nightly`, there have been a small number of updates. But I don't think a fix for this was one of them.

If you're *really* feeling up to it, spinning up a second instance using v3 and checking to see if it is fixed there would be groovy.

**Comment by casperse** [comment]
What do I have to write to run this V3 ":beta" as a docker I am currently on "latest"
This Bug is driving me nuts - new error is now that it dosent take all the subtitles just the first two...Havent found a pattern on why it sometime only takes some subtitles and other times take them all? :-)

**Comment by fryfrog** [comment]
It depends on what Docker image you're using, I think LSIO uses `:preview` and hotio may use `:phantom` or `:sonarrv3`? But their Docker hub pages/github should have details. If you use your v0.2 config, be sure to have a backup. It isn't quite ready for most users, so I'd only try it to see if this issue is still in it.

**Comment by casperse** [comment]
I am using the Linux server docker.... is there anyway to roolback to see when it broke?
(I am looking into another docker that have v3...)
I just spend 2 days manually copying and pasting missing subtitles by hand

**Comment by casperse** [comment]
Ok I just installed V3 and so far the renaming have been working 100%!
Many other things are not but this seem to work! :-)

**Comment by casperse** [comment]
One strange thing - Is Radarr V3 only in english? it seem to change my danish movies to english translation renaming folders and file names? (Is this language set anywhere?)

**Comment by casperse** [comment]
I can report that the new v3 Radarr only seem to have problems with renaming and moving the .nfo --> nfo-orig? - Looks like subtitles are all there now!

**Comment by jpogs** [comment]
@casperse this was introduced as fix for #1958 to support multiple subtitles from RARBG. This was reverted since December due to another bug but the corrected fix is on its way to develop branch. Is this going to be an issue? I know that this naming convention is supposed to be supported by players...

**Comment by casperse** [comment]
@jpogs not sure its the same issue #1958 talks about suddirs, my nfo file is not in any sub dir its in the same folder as the media file
I know there is only one nfo file I am not sure if the filename is 100% the same as the media file have to check.
The subtitles seem to be imported correct now (some small issues where they are labeled dk.srt instead of da.srt and they are ignored again (Would be great to use them both for every country)
Where some people name country by the 2 letter country ID and not the sub country ID

**Comment by jpogs** [comment]
@casperse it is working now because it was reverted in December, now once the update is approved it will go back to appending the suffix 1 -- this is necessary as RARBG usually has multiple subs with the same language. Was wondering if this is going to be an issue with your player or if this is more of a cosmetic concern?

**Comment by casperse** [comment]
I think if the first is normal and the second gets a number then it doesn't matter
Most in Europe use and have subs included for each country only the extra  HI (Hearing empaired is sometimes double) Plex and Emby have a standard strict naming rule Where [Language_Code] is defined by the ISO-639-1 (2-letter) or ISO-639-2/B (3-letter) standard so no numbers! so this might be a problem have to test
https://support.plex.tv/articles/200471133-adding-local-subtitles-to-your-media/
