### ISSUE TITLE
remove from download client when seed ratio met

### ISSUE THREAD

**Issue by arpitgupta** [Radarr/Radarr#4069]
Appreciate the feature that has been added where i can set the seed ratio per indexer. 

Would be great if the download was removed from the download client once the seed ration was met. Today for torrents in transmission it is greyed out and shows 'seeding complete'. 

So i have to manually remove these from transmission. I have the same setup running with sonarr v3 and it removes the download from the client once seed ration is met.

**Comment by Qstick** [comment]
Need Logs and Radarr version you are using. 

Given the see ratio feature is only in Aphrodite, I would assume you are using V3, in which case behavior should function similar to Sonarr, given it differs thats where the logs requirement comes in.

**Comment by arpitgupta** [comment]
Yup on V3. This might be a pebkac. I was comparing sonarr and radarr settings i noticed under download client settings i did not have the flag enabled to remove completed downloads like i had in sonarr. Closing this out.
