### ISSUE TITLE
Movie Year

### ISSUE THREAD

**Issue by SunSpotSigma** [Radarr/Radarr#4074]
Hi,

I know there are loads of posts about incorrect year in searches, but having spent a while looking I can't find a solution to my issue.

I am trying to add Ex Machina (2015) to my movie list. When I search for it, it comes up 2015, but when added it changes to show Ex Machina (2014). Even in the description it shows the release date as 2015, and manual searches come up with 2015 and a wrong year warning. I've downloaded manually but it always shows the file up as missing as it obviously won't reconcile.

Any ideas?

S

**Comment by Qstick** [comment]
Closing this as you didn't follow the issue template, will reopen if you provide all required data.
