### ISSUE TITLE
Add Score options to rank higher/lower downloads based on keywords

### ISSUE THREAD

**Issue by scs3jb** [Radarr/Radarr#4076]
**Is your feature request related to a problem? Please describe.**
At the moment, Radarr works on a hard hit or miss based on quality profiles and tags. i.e. do not get movies with MULTi, do get movies with FRENCH, however this means that when MULTi is the only options, or the movie is French, it would not download the only options.  Instead of working in a direct hit approach, it would be good to reduce the 'score' of MULTi and FRENCH releases.

With custom formats, this follows the same approach of direct hits, and instead of saying boost this word, say DTS-HD, and handicap this word, say FRENCH, it is more of a filtering option and will lead with complex overlays of profiles for each keyword, instead of a globally applicable boost list that can be applied on top of the 1080p, etc. profiles.

**Describe the solution you'd like**
I would like the ability to provide a list of words to boost the score of a download option, and a list of words to handicap the score of a download option.  This could be a simple list of words that boost a ranking and one that handicaps, that is filtered to the download list to sort it, ideally displaying the overall points calculation when doing the search 'manually'.

![example](https://user-images.githubusercontent.com/2076285/72663364-54745380-39f2-11ea-8636-b123c1cf692f.png)

**Describe alternatives you've considered**
A list of preferred words if its easier, although a list of handicaps would make this feature better/more accurate.

**Additional context**
I am trying to download native, original language rips of movies from around the world fed in from multiple lists, and I see MULTI language or DL language rips being grabbed over the undubbed versions, meaning I have to go in and process the videos.  The issue is if i ban MULTi or DL, in some cases these are the only options.  Similarly, some ripping crews are preferred over others, and there isn't an easy global way to apply to all quality profiles.  I also want to downrank AVC for example, but if I get them don't bother downloading another profile (see it as cutover)

**Comment by Cookie-Monster-Coder** [comment]
+1 Having something like Sonarr V3 is much Superior than custom formats. I have Sonarr working perfectly. Radarr is always or hit a miss when selecting a release. With and without custom formats.

**Comment by Qstick** [comment]
Done in v3
