### ISSUE TITLE
Fails to recognise Trakt username with space

### ISSUE THREAD

**Issue by shnabz** [Radarr/Radarr#4080]
When adding 'UserWatchList' for Trakt, if there is a space in the username when pressing 'test' we will get error "Username is required when using User Trakt Lists". If we remove the space from Trakt and account and repeat, it will succeed.

**To Reproduce**
1. Go to 'Add Trakt List'
2. Select 'UserWatchList'
3. Put username with space

**Expected behavior**
Test should succeed.

**Desktop (please complete the following information):**
 - OS: Raspian Buster Lite
 - Mono Version: 6.8.0.96
 - Version: Radarr Ver. 0.2.0.1450

**Debug Logs**
20-1-18 17:55:35.3|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Username is required when using User Trakt Lists
20-1-18 17:55:35.3|Debug|Api|[POST] /api/netimport/test: 400.BadRequest (119 ms)

**Comment by Qstick** [comment]
Fixed in https://github.com/Radarr/Radarr/commit/5d4ec1272dda6fc9494ea7aff1df28b748ab197a
