### ISSUE TITLE
Assign Multiple Profiles

### ISSUE THREAD

**Issue by shnabz** [Radarr/Radarr#4081]
**Is your feature request related to a problem? Please describe.**
The problem is that by default the 'cutoff' feature will remove inferior quality releases, but what if we want multiple releases of varying quality?

I use Plex on numerous TV's throughout the house, and I serve to external Plex accounts also. If a 4K release overwrites a 1080p release, some devices wont be able to view at all due to transcode limitations, not only that but why use more bandwidth than you have to?

Plex has functionality for the user to select which version of the content they would like to watch and we use it regularly.

**Describe the solution you'd like**
I would like there to be a little [+] icon beside the profile dropdown select that inserts another dropdown below it, where we can select a 2nd profile. The cutoff off rule will still work exactly the same, but independantly of the other profiles.

**Describe alternatives you've considered**
Perhaps an option in the settings that modifies the behaviour of cutoff, so that inferior releases aren't removed when we manually download an alternate release.

**Comment by shnabz** [comment]
I've just discovered the recycle bin, I could use that as a separate source in my Plex library.

**Comment by Qstick** [comment]
I think this is covered by #1910 and #2203 which are for keeping multiple quality versions and storing multiple versions in different places. For now the only way to do this is running multiple versions of Radarr. There is a external program that syncs up the versions with each other called Radarr Sync

**Comment by FlyingPersian** [comment]
> I think this is covered by #1910 and #2203 which are for keeping multiple quality versions and storing multiple versions in different places. For now the only way to do this is running multiple versions of Radarr. There is a external program that syncs up the versions with each other called Radarr Sync

According to the projects page, Project Proteus, which involves having multiple profiles (aka multiple qualities) for a movie, is done, right? At least there is no "To-Do" anymore. Am I seeing this wrong?

Source: https://github.com/Radarr/Radarr/projects/6

**Comment by Qstick** [comment]
It's not complete
