### ISSUE TITLE
Debug|NewznabRssParser|Failed to parse Url

### ISSUE THREAD

**Issue by Ninjouz** [Radarr/Radarr#4085]
Hello,

One of my indexer returns NZB URL like this : 
https://domain.name//requestUri 

Double slash is not handled by the regexp (url parsing)
`^(?:(?<scheme>[a-z]+):)?(?://(?<host>[-A-Z0-9.]+)(?::(?<port>[0-9]{1,5}))?)?(?<path>(?:(?:(?<=^)|/)[^/?#\r\n]+)+/?|/)?(?:\?(?<query>[^#\r\n]*))?(?:\#(?<fragment>.*))?$`

Could you support this ? 

`^(?:(?<scheme>[a-z]+):)?(?://(?<host>[-A-Z0-9.]+)(?::(?<port>[0-9]{1,5}))?)?(?<path>(?:(?:(?<=^)|/)[^/?#\r\n]+)+/?|/)/?(?:\?(?<query>[^#\r\n]*))?(?:\#(?<fragment>.*))?$`

works

**Comment by fryfrog** [comment]
Is it `domain.name` or `domain.name/` in Settings? Might be worth trying w/o the ending `/` if you have it there... but it probably isn't there. Would also be worth a quick note to the indexer, if it really is happening at the indexer.

Also, seems reasonable to deal w/ it here too. Is it a TV indexer too? Does it do the same in Sonarr?

**Comment by Ninjouz** [comment]
It's domain.name in my Indexer Settings. It's really my indexer that returns double slash in xml file. Don't know why.
It's a movie indexer only, I can't search with t=tvsearch.

**Comment by Ninjouz** [comment]
Still to be done

**Comment by fryfrog** [comment]
What version of Radarr is this happening on?

**Comment by Ninjouz** [comment]
Version
0.2.0.1480
Mono Version
6.8.0.105

**Comment by Diazole** [comment]
If that's an issue with your indexer returning double slashes, maybe you should get them to fix it?

**Comment by Ninjouz** [comment]
it's a simple regex change on radarr side. I even posted the regex

**Comment by Diazole** [comment]
> it's a simple regex change on radarr side. I even posted the regex.
> Sanitize what Radarr receive

It's a simple change for the indexer to fix the source of the problem. If the data being provided to Radarr is wrong, why should Raddarr fix it?

**Comment by Ninjouz** [comment]
because you can't control what an API (provider) sends but the client can ?

**Comment by fryfrog** [comment]
Personally, I think it is both reasonable to fix it in Radarr *and* ask the indexer to not do something stupid. ;)

**Comment by bakerboy448** [comment]
Closing
v0.2 is no longer being actively developed.

If this is still an issue/request on recent v3 builds, please open a new issue.
