### ISSUE TITLE
Preferred words weight / mechanics

### ISSUE THREAD

**Issue by PeterPan669** [Radarr/Radarr#4086]
Version
0.2.0.1450
Mono Version
5.18.0.240

**Is your feature request related to a problem? Please describe.**
When using preferred words, e.g. "EXTENDED" and "DUTCH", I now have the feeling that Radarr will sometimes download EXTENDED, and sometimes DUTCH containing releases. However, I would like to take EXTENDED over DUTCH. Right now it seems that I sometimes get a DUTCH release, while it is not taking an EXTENDED release.
Correct me if I'm wrong on this assumption how the mechanics work.

**Describe the solution you'd like**
Sonarr v3 offers the solution by setting preferred words, and assigning a weight to them, e.g.:
- EXTENDED: 20 points
- DUTCH: 10 points
This results in EXTENDED being taken over DUTCH, and a release with both EXTENDED + DUTCH will gain 30 points, being taken overall. If no EXTENDED exists, DUTCH releases are preferred.

**Describe alternatives you've considered**
Since I'm running on 0.2.0.1450, I have no idea if there is a newer version / branch that already includes this functionality (or any other improvements), that I would certainly like to try.

EDIT: I just stumbled on Aphrodite; I'm running a Synology DSM6; Any way to inplace upgrade the current .SPK version?

**Additional context**
From Sonarr v3:

![image](https://user-images.githubusercontent.com/59241040/72715896-9f68a500-3b71-11ea-94b4-f25e1055ba46.png)

**Comment by fryfrog** [comment]
The Sonarr v3 port to Radarr v3 does *not* include preferred words. And the preferred words in Radarr v0.2 don't work very well because they really only apply to searches rather than RSS. But you *can* achieve what you want with Custom Formats, though it won't look as neat.
