### ISSUE TITLE
Square Brackets [ ] in filename make RADARR unable to see movie file. 

### ISSUE THREAD

**Issue by bing281** [Radarr/Radarr#409]
If a movie file name has Square Brackets [ ] in it Radarr cannot see the movie file.  

**Found by using organizer with the following tag settings:** 
`{Movie TitleThe} ({Release Year}) [{MediaInfo Full}]`

After Files were renamed Radarr reported they were all missing.  Removing the Square Brackets [ ] and running update on Radarr found the files.  

**Reproduce by renaming a filename to include Square Brackets [ ] and running update.**  

_Also just to note that the tag settings allows you to put in a  PIPE character | and that is definitely not ok for most file systems._  

Thanks you all for the hard work ;)

**Comment by galli-leo** [comment]
Can you give me an example of the filename?

**Comment by bing281** [comment]
I already fixed all my files, however one was like this 

Arrival (2016) [x264 aac [es]].mkv

**Comment by fryfrog** [comment]
FWIW, all my files are named Movie (Year) [Quality Resolution].ext and they work fine. Maybe it is the nested [[]]?

**Comment by edru** [comment]
the [rec] series would be something that you could look up too.

**Comment by bing281** [comment]
hmm that is interesting.  To help you out this is running on a docker container by linuxserver.io on an UnRaid box.  The containers config is on the cache drive pool which is running on btrfs and the media itself is on the array which is running xfs filesystems.

**Comment by lordjynx** [comment]
Little tidbits:

I used to do this with sonarr about 1.5 years ago like this: 'release-name [quality]', changed it to 'release-name (quality)'.  I haven't had an issue since.  This might be left-over from Sonarr code as I'm not sure it was ever fixed.

**Comment by galli-leo** [comment]
@bing281 Are you still experiencing this issue? Works fine for me on the latest develop release.

**Comment by bing281** [comment]
I have not set it to do this however I believe you may close it :) thanks for looking at it.
