### ISSUE TITLE
Manual Import quality list in mobile does not scroll

### ISSUE THREAD

**Issue by beyondmeat** [Radarr/Radarr#4095]
**Describe the bug**
When using a mobile screen size, and you need to manually import an item, when choosing a quality for a movie, the list does not scroll. This makes it impossible to choose qualities not visible on the screen.

**To Reproduce**
1. Go to manual import
2. Click on quality
4. See that you can't sroll.

**Expected behavior**
The quality list scrolls in mobile view

**Screenshots**
![image](https://user-images.githubusercontent.com/51850644/72846186-54c45700-3c5d-11ea-8415-216bc87eb556.png)

**Desktop (please complete the following information):**
 - OS: Docker
 - Mono Version:
 - Browser and Version: Version 79.0.3945.130 (Official Build) (64-bit)
 - Version: Aphrodite

**Debug Logs**
N/A

**Comment by beyondmeat** [comment]
Reopen still valid issue

**Comment by bakerboy448** [comment]
@beyondmeat is this any better on the newer v3 releases?
