### ISSUE TITLE
mono --debug cpu usage

### ISSUE THREAD

**Issue by ohmaxx** [Radarr/Radarr#4096]
Hello,

I recently install radarr with docker but the task :
mono --debug Radarr.exe -nobrowser -data=/config 

is using my all cpu wich is i5-6600 thats not normal. Someone on redit have the same problem there is solution ? 

 [https://imgur.com/UJyAgdQ](url)

Thanks you if you can help

**Comment by fryfrog** [comment]
If this turns out to be a real bug, we can re-open it. But you'll need to provide more information like version of Radarr and Mono at least. And did you test w/o `--debug`? Trace logs. Useful stuff like that.
