### ISSUE TITLE
Custom Filter for Custom Format

### ISSUE THREAD

**Issue by leloberg** [Radarr/Radarr#4101]
**Is your feature request related to a problem? Please describe.**
Not a problem, but I want to see all movies that have met the Custom Format I've set

**Describe the solution you'd like**
The possibility to add a custom filter on Custom Formats. Also in the overview view, it would be nice to add the possibility for a column for Custom Format

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by ta264** [comment]
I think this is unlikely to happen since custom formats are no longer stored in the database and calculating for all movies at once for the frontend is too slow.
