### ISSUE TITLE
Fix MacOS package for Aphrodite

### ISSUE THREAD

**Issue by ta264** [Radarr/Radarr#4106]
**Describe the bug**
The macos package is still set up to call mono, but we only produce net core builds for macos now.

**Comment by ta264** [comment]
Actually I think this might be ok, just that there's an old mono file in the repo that's no longer used. Leaving open til we have confirmation it works from a macos user

**Comment by Qstick** [comment]
Did @Taloth test a build (or was that Readarr?) are we good on this?

**Comment by Taloth** [comment]
I didn't test it (Readarr package), but dotnet core has it's own native binary as entrypoint, not a shell script so the problems we had with mono doesn't apply to it.

**Comment by ta264** [comment]
I think we just need to remove that script to tidy up (it's not used) and update develop to be able to start the net core updater if found
