### ISSUE TITLE
Radarr copies completed torrents instead of moving them

### ISSUE THREAD

**Issue by agneevX** [Radarr/Radarr#4108]
Radarr is copying the downloaded torrent instead of moving it.

[Related post on Rclone forums](https://forum.rclone.org/t/contd-file-is-written-twice-to-remote/14039)

I'm running a rclone mount with qBittorrent as the download client. I'm not using cache or VFS, because of storage constraints, so the files are being written directly to Google Drive.

For all the torrents this issue has impacted, none of them seeded after 100% of download; All of them had their state changed to `Completed`, so I'm not sure why this behavior is taking place. 

This results in more upload bandwidth than expected. For e.g. I'm receiving consistent 403s after 587GB of effective upload.

**Expected behavior**
Radarr should **move** the video files to the root folder, not copy, when not seeding. If its seeding, there should be an option to move the files after it finishes seeding.

Even if Radarr should decide to copy, against all odds, _this_ way of rather _inflating_ the files by copying it with `.partial~` in tow, should be substituted for `cp` or better yet, `rclone copy`. 

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 amd64
 - Mono Version: 6.8.0.96
 - Version: 0.2.0.1450

**Debug Logs**
Can't obtain until the restriction is lifted :(

**Comment by fryfrog** [comment]
This isn't how Sonarr/Radarr work w/ torrents.

Torrents that are *done* seeding at time of import will move, but this is rare. Torrents that *haven't* meet their seed time/ratio criteria will copy or hard link (if enabled and possible).

Turn on Remove under Completed and Failed Download Handler. Make sure you're setting seed time/ratio goals, Sonarr can do this as a per indexer setting, but Radarr's v0.2 can't. The new v3 *can*, but I don't suggest using it yet. So you'll need to set them in your download client. And set your download client to pause or stop the torrent when seed time/ratio goals are met. Then Sonarr/Radarr will remove them.

**Comment by fryfrog** [comment]
Also, use a local cache. Trying to do this right to GDrive is going to be a very poor experience.

**Comment by agneevX** [comment]
@fryfrog Radarr/Sonarr is copying it to the rclone mount and removing it from the download client, so it knows that the torrents aren't seeding.


> Also, use a local cache. Trying to do this right to GDrive is going to be a very poor experience.

That basically halves my storage space, which is around 150GB.
