### ISSUE TITLE
Bulgarian language support

### ISSUE THREAD

**Issue by b0ril** [Radarr/Radarr#4111]
Hello,

I know that Bulgarian language is not spoken by many people but I like movies which I download for my kids to be with Bulgarian audio, 
There is no Bulgarian language in profile list.
Thank you very much.

**Comment by Qstick** [comment]
Need examples of torrent/Usenet release names that have Bulgarian audio so that we know how to parse

**Comment by b0ril** [comment]
Hi Qstick,

magnet:?xt=urn:btih:f965c17f427a3da220bcc090715ef6765f397253&dn=Hall.Pass.2011.BGAUDIO.NTSC.DVD5-AVS-ArenaBG
magnet:?xt=urn:btih:7e4b28182f2a861f019d924ed913ba3cb9616fe2&dn=New.Amsterdam.S02.HDTV.1080i.x264.BGAUDiO-4PLAY-ArenaBG
magnet:?xt=urn:btih:a88cebece4356a090ee6b4339cbe0ff9841d760a&dn=Run.All.Night.2015.BRRip.x264.AC3.BGAUDiO-SiSO&tr=http://tracker.zamunda.net/announce.php?passkey=4f71df0bf18a
magnet:?xt=urn:btih:de10430099df4ab99c14e3bf1775707d300d4d7a&dn=Raw+Deal+1986.J.1080p.BluRay.BG+Audio.MadMax+%26+T12+%26+Goredolo&tr=http://tracker.zamunda.net/announce.php?passkey=4f71df0bf18a1fb803bda92f08ed0db8

please let me know if those are fine ?
