### ISSUE TITLE
Quality Size Definitions, Change Megabytes per minute to Megabit per second

### ISSUE THREAD

**Issue by RandomNinjaAtk** [Radarr/Radarr#4119]
**Is your feature request related to a problem? Please describe.**
Currently Megabytes per minute does not simply translate well to average video bitrate because videos are typically handled in mbps rates. So you have to use a separate conversion calculation to be able to set a min/max to average video bitrate

**Describe the solution you'd like**
Change the default calculation to use typical average video bitrate calculation and terminology. This should allow easier configuration because you can just specify the desired overall average video bitrate.

**Describe alternatives you've considered**
Using conversion calculators online to calculate the desired setting to configure the tool as required.

**Comment by ta264** [comment]
I would argue a lot of people are only interested in setting the file size rather than an encoding bitrate and having to figure what that means in real life

**Comment by Qstick** [comment]
I would agree, we only did this on music because people know bitrates as the standard.... I feel like on video size that's not the case for 95% of users, they only care about size.

**Comment by fryfrog** [comment]
![Screen Shot 2020-02-03 at 10 58 10 AM](https://user-images.githubusercontent.com/87748/73681886-158e0100-4674-11ea-89bd-62754bcf66d2.png)

You could compromise and just add it as an additional bit of info on the hover, at the top you could put like `1000mbit/sec`.

**Comment by Qstick** [comment]
Was thinking about making it a view option or something to pick the units. However total file "bitrate" will depend on both audio bitrate, video bitrate, and number of video and audio streams right? so I don't really see how this is that useful if you are trying to use it to get certain video bitrates to download?

**Comment by bakerboy448** [comment]
Edgecase and would confuse most users; closing
