### ISSUE TITLE
[Request] Add Indexers using Jackett API

### ISSUE THREAD

**Issue by zero77** [Radarr/Radarr#4120]
**Is your feature request related to a problem? Please describe.**
When using a number indexers in Jackett it can take a wile to add them all into Radarr.

**Describe the solution you'd like**
Use Jackett API to find the enabled indexers and import them into Radarr.

**Additional context**
API Path: `/api/v2.0/indexers/`

![Screenshot from 2020-01-19 21 02 53](https://user-images.githubusercontent.com/16563034/72688435-1dd82f00-3aff-11ea-9bba-2ede9ddf355d.png)

**Comment by bakerboy448** [comment]
https://github.com/Radarr/Radarr/pull/5092

**Comment by zero77** [comment]
> #5092

This was closed due to other plans, is there a PR or issue or something else explaining the plans for this.
