### ISSUE TITLE
Configurable Colon Replacement UI Missing

### ISSUE THREAD

**Issue by beyondmeat** [Radarr/Radarr#4122]
**Describe the bug**
Radarr V2 has a option where you can customize the colon replacement behavior.

I noticed on a clean Aphrodite 4k install that it drops the colon and doesn't replace it with anything.

On my 1080p Aphrodite upgrade (used existing appdata) it does respect the setting I had (even though no UI) and use space dash space.

```
Movie Title:
Star Wars: Episode III - Revenge of the Sith

Aphrodite upgrade (using space dash space from old radarr):
Star Wars - Episode III - Revenge of the Sith

Aphrodite Clean Install:
Star Wars Episode III - Revenge of the Sith
```

Is this option coming back to Aphrodite?

Sonarr won't make it customizable, but they do have a different default as described in 
https://github.com/Sonarr/Sonarr/issues/3544#issuecomment-580895423

**To Reproduce**
1. Go to Media Management
2. Click on Advanced Settings
3. No colon replacement settings.

**Expected behavior**
Colon replacement settings UI is present or consider changing the default behavior to match with sonarr.

**Workarounds**
Edit the radarr.db manually, set the colon replacement column in naming config table from 0 to 3.

**Comment by xcorlett** [comment]
I still can't see it on 3.0.0.2719
