### ISSUE TITLE
Pull in latest Activity Queue code from Sonarr

### ISSUE THREAD

**Issue by onedr0p** [Radarr/Radarr#4123]
Gathered a couple commits here if anyone wants a go at it.

New: Queue remains up to date while importing file from remote file system
Fixed: Failed downloads still in queue won't result in failed search

https://github.com/Sonarr/Sonarr/commit/3916495329ff111e0e125ebf873372f8c0c3f806#diff-197500c5a96bf39d2f230c7f4181a5e4

New: Option to not remove item from download client when removing from queue

https://github.com/Sonarr/Sonarr/commit/c6ea7d7e630cbcff73b02fa36cbd97aa178246b9

**Comment by Qstick** [comment]
Already issue for this, #4068
