### ISSUE TITLE
"Enable Completed Download Handling" Bug

### ISSUE THREAD

**Issue by Ashkaan** [Radarr/Radarr#4126]
**Describe the bug**
Radarr is asking me to "Enable Completed Download Handling if possible" even though it's already enabled.

**To Reproduce**
1. Go to 'System'
2. Click on 'Status'
3. Look at 'Messages'
4. See 'Enable Completed Download Handling if possible (Multi-Computer unsupported)'

**Expected behavior**
That message shouldn't be there.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Docker
<img width="839" alt="Screen Shot 2020-02-04 at 10 16 32 AM" src="https://user-images.githubusercontent.com/5667978/73773651-6dda0700-4737-11ea-8b20-2e05301cc384.png">
<img width="595" alt="Screen Shot 2020-02-04 at 10 16 46 AM" src="https://user-images.githubusercontent.com/5667978/73773680-75011500-4737-11ea-8af0-631672abe957.png">

**Comment by ta264** [comment]
Version? In the template for a reason :)

**Comment by Ashkaan** [comment]
So sorry!

Version: 3.0.0.2609

**Comment by Qstick** [comment]
I think this is because we don't have the migration to explicitly add it anymore, it defaults to true but the health check is checking if it's actually defined in the config.

**Comment by Qstick** [comment]
If you in uncheck save and recheck enable complete download handling it should go away

**Comment by Ashkaan** [comment]
That worked!!
