### ISSUE TITLE
Permissions of /var/lib/radarr inconsistent after reboot

### ISSUE THREAD

**Issue by p5-f20w18k** [Radarr/Radarr#4128]
**Describe the bug**

For my use case I had to change the ownership or /var/lib/radarr to my own user with the "chown -R" command. This is because I am mounting drives on my network to write data to, and can only mount them as my own user for myself to access them. After rebooting the ownership of /var/lib/radarr has changes back to radarr:radarr.

**To Reproduce**
Run the radarr.service as your own user, change permissions of /var/lib/radarr to your own user and group and reboot your system and check if it has changed the permissions of /var/lib/radarr back to radarr:radarr

- This may be an isolated case as I have had this running as my own user in the past with no issues.

**Expected behavior**
I expected to have radarr start at boot, as it's enabled through systemctl after changing the permissions of the directory to my own user.

**Desktop (please complete the following information):**
 - OS: Arch Linux 5.5.2-arch1-1
 - Mono Version: 6.4.0
 - Browser and Version: Firefox
 - Version: 72

**Debug Logs**
Turn on debug logs under Settings -> General and wait for the bug to occur again. **Upload the full log file here (or another site and link it). Issues will be closed, if they do not include this!**

Debug log does not contain details of this error as the program will fail to start.

**Comment by fryfrog** [comment]
This has nothing to do w/ Radarr, rather it is my AUR package. Check out the sysfiles file and override it.
