### ISSUE TITLE
Always sorted by 'date added'

### ISSUE THREAD

**Issue by JBFUK** [Radarr/Radarr#4129]
Movies are always sorted by 'date added' as the first and primary parameter regardless of what is set via the 'Sort' button at the top of the page.

Having just imported a folder of movies managed elsewhere beforehand, I was only able to bulk import 1 page at a time, so the 'date added' of various titles varies by a few minutes, as I imported in blocks of 20 or so at a time.

Going to the 'Movies' page, in all views (Posters, Overview List or Table) with 'Sort' set to 'Title' it seems to first sort by 'date added' and then sort by title as a secondary parameter.  This results in a very random looking library which is by no means sorted by title.

In table view you can rectify this by clicking on the 'Title' column header at which point it sorts all items correctly by title.  However this is not correct behaviour and is also not possible in 'Posters' or 'Overview' views.

**Comment by fryfrog** [comment]
What version of Radarr? What OS?

**Comment by Qstick** [comment]
This is fixed in v3, also you blitzed the template... closing until you can provide template info.

**Comment by JBFUK** [comment]
The full template really isn't required to describe this simple issue.

Linuxserver.io Docker image
Version
0.2.0.1450
Mono Version
5.20.1.34

Until v3 is the recommended stable release it may as well not exist from the point of view of the average user.  So saying it's fixed in v3 isn't helpful at all.

It's sounds like nothing is being fixed in v0.2 anymore so I guess it's a waste of time having any bug reports open for it anyway.
