### ISSUE TITLE
Consider support for filtering movie list based on "Path"

### ISSUE THREAD

**Issue by chrisallen** [Radarr/Radarr#413]
This would allow users such as myself who have movies in multiple paths, to filter the list into just one of the paths, allowing me to quickly manage movies from a specific path.

This `Path` filter dropdown could have something like this,

```
- All Paths
- "/mnt/Media/Movies/English"
- "/mnt/Media/Movies/HIndi"
- "/mnt/Media/Movies/French"
```

![image](https://cloud.githubusercontent.com/assets/203867/22247153/28b5c026-e29d-11e6-8d80-01a6205215c5.png)

**Comment by onedr0p** [comment]
Moved discussion to http://feathub.com/Radarr/Radarr/+6
