### ISSUE TITLE
Implement a search selected items option from the movie index page

### ISSUE THREAD

**Issue by EnorMOZ** [Radarr/Radarr#4130]
**Is your feature request related to a problem? Please describe.**
Search will search for the entire movies list on the page vs the ability to select individual movies

**Describe the solution you'd like**
Have the ability to select multiple movies at once to search. Basically a search selected items option. 

**Describe alternatives you've considered**
Write an external script to parse out the movie list and hit the api.

**Comment by software2Daniel** [comment]
mortuary science is a very important career in our society
If you want to know all the job opportunities in this career, go to the next article

https://sites.google.com/aprendizajesignificativo.org/cmortuoria/p%C3%A1gina-principal

**Comment by MollyBe** [comment]
You can 'select' individual movies to search via the movies list page. You can enable this by going to the movies list page > options > and ticking show search button on hover. 

**Issues with this implementation**
It is difficult to click the search button on hover.

The select on click implementation in the movie editor is as difficult to click as each search button.

I would expand on **Describe the solution you'd like**
An easy to click select on click hitbox
 - 90% of the poster, leaving the bottom right corner for opening a movie page.
Perhaps the movie editor hitbox can be improved and the search all function could be changed to search selected when the movie editor is opened.
