### ISSUE TITLE
Sort films by duration on Index

### ISSUE THREAD

**Issue by logos88** [Radarr/Radarr#4131]
I am using Radarr v3 and often I only have a specific frame of time to watch a movie so maybe I can't watch a movie with a duration of 3 hours but I can watch one of a duration of 1 hour and a half. That's why I think it would be very useful to add the option to **sort films by their time duration** (besides Title, Studios, ...).

**Comment by Qstick** [comment]
We can add this, but this being in Radarr doesn’t really help your case given you are not playing files from Radarr.

**Comment by logos88** [comment]
I don't play them there, but is where I see what films I do have and then I decide which one I whatch
