### ISSUE TITLE
bulk import bug

### ISSUE THREAD

**Issue by phyzical** [Radarr/Radarr#4133]
Hey! love sonar, first time trying out radarr and i just noticed a bulk with bulk import

**Describe the bug**
When you re-import a folder and the first page i.e page of 15 doesn't have an unmapped movie it returns a result suggesting everything is all done but changing to say 1000 will return the movies that have not been scrapped

**To Reproduce**
set a folder of 20 items set size to 15,
import all the first page,
refresh and it re import and it will say all done, change the amount to more than 15 and it will return the additional items

**Expected behavior**
re running import should correctly return the unimported files

**Desktop (please complete the following information):**
linux running in docker

So i had a verrry quick look at the code cause well ive been looking for a new project to contribute to so ill try to have a crack at this when i get a chance :) anyway i think what is happening is we get the current page i.e 15 items but unmapped actually contains all the folders rather than just the unmapped ones (total guess until i get it running dev wise) and because the first 15 movies are found it returns no results, whereas if you set a size of 1000 it checks them all and finds the unscraped movies.

`var paged = unmapped.GetRange(min, max - min);

            var mapped = paged.Select(f =>
            {
                 Core.Movies.Movie m = null;
                
                // i think its this
                var mappedMovie = _mappedMovies.Find(f.Name);

                if (mappedMovie != null)
                {
                    return mappedMovie;
                }`

**Comment by ta264** [comment]
This is fixed in v3, not going to backport to 0.2
