### ISSUE TITLE
Snatching the same quality from 2 different providers

### ISSUE THREAD

**Issue by Rouzax** [Radarr/Radarr#4134]
**Describe the bug**
Added 7 movies and 1 of those got snatched in 2160p-remux quality from 2 different providers.
Might be similar or related to: https://github.com/Radarr/Radarr/issues/3907

**Screenshots**
![image](https://user-images.githubusercontent.com/4103090/74100814-17076f80-4b33-11ea-8b01-78250bd3e3a9.png)
![image](https://user-images.githubusercontent.com/4103090/74100819-2a1a3f80-4b33-11ea-82e3-86c1ca6d1277.png)

**Desktop (please complete the following information):**
 - OS: Windows 2019
 - Version 0.2.0.1450

**Debug Logs**
[radarr.debug.3.txt](https://github.com/Radarr/Radarr/files/4176760/radarr.debug.3.txt)

**Comment by fryfrog** [comment]
The only thing in your History is the submission to the download client, no import. To Radarr, neither download finished or imported.

**Comment by Rouzax** [comment]
Thanks, I see if the logs haven't filled over yet.

**Comment by fryfrog** [comment]
Its pretty sure to happen again, so set logging to debug to have a little extra info when it does! :)

**Comment by Rouzax** [comment]
I already have logging set to debug but unfortunately it rolled over already.
But the snatch time is in the debug log and that is where the logic is when it chooses which downloads, right?

**Comment by fryfrog** [comment]
You're not having a choosing which download issue. You're having a *seeing* existing downloads and importing them issue. If Radarr doesn't see the download and doesn't import it, it doesn't exist from its perspective. So it is *always* going to queue up a release that comes down RSS. All it knows is that it *submitted* something to download, but it never showed up and imported.

Actually, you should really see those downloads in the minutely-ish download client scan, hopefully w/ some obvious error about why they're not showing up.

**Comment by Rouzax** [comment]
What do you mean with the last paragraph, do I need to look in a different log?

**Comment by fryfrog** [comment]
No, same log. Just watch for the scan of the download client, should be obvious.

**Comment by Rouzax** [comment]
Next time I'll upload my entire log folder 😉
