### ISSUE TITLE
Activity Queue doesn't show items sent to DL client? [Windows + Deluge]

### ISSUE THREAD

**Issue by seanvree** [Radarr/Radarr#414]
Windows 10U
Radarr Ver. 0.2.0.210 develop
Deluge 1.3.13 + Webui & Thin Client

Radarr sends the item to the DL client (Deluge) and sets label just fine, DL Client picks it up and downloads it just fine

However, I'm not seeing the DL in the activity queue?  I can run a test on the DL client and it's successful

See screenshot:

http://imgur.com/J9uz6Ae

So why am I not seeing the currently downloading items? I have the exact same setup with Sonarr, and it works great. 

THX

**Comment by galli-leo** [comment]
Do you have any logs you could provide us?

**Comment by seanvree** [comment]
@galli-leo - there's literally nothing in the logs as far as errors for this issue that I can see. However, here's my latest log file:

https://drive.google.com/file/d/0B7OujkYtbxFNWFZSbC11U3FNM3c/view?usp=sharing

**Comment by seanvree** [comment]
nevermind, I rebooted and it started working. 

THX
