### ISSUE TITLE
Parser suddenly fails to recognize movie

### ISSUE THREAD

**Issue by r2binx** [Radarr/Radarr#4140]
**Describe the bug**
I've been experiencing this problem for a while now only with german titles and not all of them are affected. Radarr grabs the correct one but somehow fails to show it in the queue (history only) and won't import it because it suddenly doesn't recognize the movie anymore. Manual import will show that it's a unknown movie.

**To Reproduce**
Monitor Dolittle with german language.

**Expected behavior**
Import previously recognized and grabbed release.

**Desktop (please complete the following information):**
 - OS: docker: linuxserver/radarr:preview
 - Version 3.0.0.2609 & 0.2.0.1474

**Debug Logs**
https://pastebin.com/raw/ZdFZE9Xc

**Comment by JBou** [comment]
I'm using version 3.0.0.2746 and can't confirm this issue.
`Die.fantastische.Reise.des.Dr.Dolittle.2020.German.DL.LD.1080p.BluRay.x264-PRD` is being successfully linked to the correct movie in queue. 

For the other german releases, PR #4274 should fix them.

**Comment by r2binx** [comment]
Yes it seems to be working fine now!
