### ISSUE TITLE
Kodi (XBMC) / Emby Metadata skipping movies.

### ISSUE THREAD

**Issue by saltydk** [Radarr/Radarr#4145]
**Describe the bug**
Enabling "Kodi (XBMC) / Emby Metadata" on a radarr (3.0.0.2615) instance that has movies in it prior to the settings change and refreshing all movies causes radarr to only generate .nfo files for 40-45% of my movies. There seems to be no logic to which movies are skipped and which get .nfo files created as the option is supposed to do. From what I can tell newly imported files (upgrades) trigger the creation of .nfo files on movies that got ignored by the refresh.

**To Reproduce**
Have a library with files already imported.
Settings -> Metadata -> Enable "Kodi (XBMC) / Emby Metadata".
Hit refresh movies.

**Expected behavior**
Creation of .nfo files for every movie with an imported media file.

**Screenshots**
Not applicable.

**Desktop (please complete the following information):**
Version
3.0.0.2615
.NET Core
Yes
Docker
Yes
DB Migration
167
AppData directory
/config/app
Startup directory
/app
Mode
Console

**Debug Logs**
Logs don't really show anything about the metadata when skipping movies.

**Comment by Qstick** [comment]
Need trace logs

**Comment by saltydk** [comment]
Went through that with ta264 on discord and seemed to show no useful info. https://pastebin.com/txHqascU

**Comment by ta264** [comment]
Maybe needs https://github.com/Sonarr/Sonarr/commit/e2ff089232765b876719b324e0543441e0bd1521

**Comment by Qstick** [comment]
Already pulled over 363be4ca

**Comment by Qstick** [comment]
Though it seems that's after OP version, try updating @saltydk
