### ISSUE TITLE
Movies imported/added with lists do not use the default RootFilePath

### ISSUE THREAD

**Issue by faultoverload** [Radarr/Radarr#4146]
**Describe the Feature**
When troubleshooting this issue I found a [old bug report](https://github.com/Radarr/Radarr/issues/1579#issuecomment-504216947) that references this same issue. Currently you can change the RootFilePath for all movies that are added manually or already existing in your library but it appears that lists simply use the default at the time of creation and do not update or change the file path after creation. Either the custom lists should always use the default file path set by the user or allow for that file path to be set in the interface to edit lists after creation.

**To Reproduce**
1. Create a new list
2. Change the default root file path to something different
3. Look at the NetImport table row RootFolderPath

I am proposing that this functionality by added to the client so users do not need to go through the effort of manually editing the database or recreating all their lists every time a file path changes.

**Comment by fryfrog** [comment]
There is no default root folder, when you're adding a movie and select one, it is remembered by the browser.

Each list has a root folder drop down setting, you'll need to pick it when you add the list and you'll need to change it when it needs changing. Sometimes it does goof up, maybe especially if you remove a root folder and then weird things happen, like they go to `system32` for Windows users or somewhere in your `~` for Linux users.

https://i.imgur.com/OUXbdVR.png

^ This is from v3, but v0.2 is similar.

**Comment by faultoverload** [comment]
![image](https://user-images.githubusercontent.com/43043100/74540055-1abd3c80-4f0d-11ea-8e5e-316486b0d3b6.png)
The database does store those values in the pictured table and I am suggesting that the custom lists either use the first row in that table by default or allow you to edit them as well.

![image](https://user-images.githubusercontent.com/43043100/74540303-869fa500-4f0d-11ea-97cb-e9906d0b80ff.png)

As you can see here the NetImport table stores its own values for where newly added movies get added and that value is currently only possible to be changed by remaking the list or manually editing the DB.

**Comment by fryfrog** [comment]
Wait, are you saying you *don't* see a drop down to edit the root folder that a list uses? You should totally be able to pick the root folder a list uses, and that list should be populated w/ the list of root folders. Can you show a screen shot? Maybe toggle on advanced if it isn't already?

If I were making up a new thing for lists and root folders, it would be a warning when a list is set to an invalid root folder. Using a "random" root folder for a list is almost as bad as using what ever gets used when the root folder for a list gets removed. Movies will go to the wrong place, but if you choose some default... they'll go to a hard to find wrong place.

**Comment by fryfrog** [comment]
Keep in mind this is v3, *not* v0.2... but I just went through the add screen for *all* the lists and they *all* have a drop down selector for root folder.

![Screen Shot 2020-02-14 at 8 23 54 AM](https://user-images.githubusercontent.com/87748/74548827-6c60c980-4f03-11ea-96cb-617d4198b21c.png)
![Screen Shot 2020-02-14 at 8 23 42 AM](https://user-images.githubusercontent.com/87748/74548829-6d91f680-4f03-11ea-96c1-575563cd3b4b.png)
![Screen Shot 2020-02-14 at 8 23 31 AM](https://user-images.githubusercontent.com/87748/74548832-6e2a8d00-4f03-11ea-958a-9486f2ed65f9.png)
![Screen Shot 2020-02-14 at 8 23 21 AM](https://user-images.githubusercontent.com/87748/74548835-6f5bba00-4f03-11ea-99bd-71a99f860249.png)
![Screen Shot 2020-02-14 at 8 23 11 AM](https://user-images.githubusercontent.com/87748/74548836-6f5bba00-4f03-11ea-9307-00fbbc95c304.png)
![Screen Shot 2020-02-14 at 8 22 59 AM](https://user-images.githubusercontent.com/87748/74548839-6ff45080-4f03-11ea-938f-a1e851573df2.png)
![Screen Shot 2020-02-14 at 8 22 47 AM](https://user-images.githubusercontent.com/87748/74548841-6ff45080-4f03-11ea-8b94-0670ffc02276.png)
![Screen Shot 2020-02-14 at 8 22 37 AM](https://user-images.githubusercontent.com/87748/74548843-708ce700-4f03-11ea-8b25-cec70ad71cbf.png)
![Screen Shot 2020-02-14 at 8 22 23 AM](https://user-images.githubusercontent.com/87748/74548845-71257d80-4f03-11ea-895b-73d6096fcbce.png)
![Screen Shot 2020-02-14 at 8 22 11 AM](https://user-images.githubusercontent.com/87748/74548846-71257d80-4f03-11ea-9502-1240f1b1a74e.png)
