### ISSUE TITLE
Disable Cannot install update because startup folder is not writable by the user

### ISSUE THREAD

**Issue by dannymichel** [Radarr/Radarr#4147]
Can we please have a way to disable the ``Cannot install update because startup folder is not writable by the user`` warning on docker?

**Comment by fryfrog** [comment]
How can an application know it is running inside Docker?

**Comment by dannymichel** [comment]
lidarr and plex know when it's docker ``docker detected``

**Comment by saltydk** [comment]
https://stackoverflow.com/questions/20010199/how-to-determine-if-a-process-runs-inside-lxc-docker

**Comment by fryfrog** [comment]
What version of Radarr are you using? If Lidarr already knows, I wonder if that has already made it into Radarr v3? @Qstick, @ta264, can you guys port that to Radarr v3? Heck, maybe Sonarr v3 if they're open to it (or maybe it already is?)

**Comment by Qstick** [comment]
Radarr v3 is docker aware, I would venture to say this doesn’t occur in v3 if we brought all the Lidarr stuff over (I can’t recall)

**Comment by dannymichel** [comment]
i'm using v3. this feature request is *for* v3

**Comment by fryfrog** [comment]
Super, your original post didn't really give any details so...

**Comment by ta264** [comment]
I think I've taken a quick look at this before and the writable check is happening before the docker one or something. Its totally benign apart from the warning so never gotten around to fixing properly...

**Comment by dannymichel** [comment]
> I think I've taken a quick look at this before and the writable check is happening before the docker one or something. Its totally benign apart from the warning so never gotten around to fixing properly...

ok thanks
