### ISSUE TITLE
Colon ( : ) in title fails to map movie

### ISSUE THREAD

**Issue by hellcry37** [Radarr/Radarr#4148]
**Description:**
If a movie has a colon ( : )  in title fails to map the movie properly
"Failed to map movie, found title Ip Man 4 The Finale, expected one of: Ip Man 4: The Finale, Ip Man 4"
As you can see it expects colon in the title and that is not actually possible, it will fail to map the movie and skip it.

**Radarr Version:**
0.2.0.1450
**Mono Version:**
5.20.1.34
**Debug Logs:**
no logs regarding this issue
it might be related to: https://github.com/Radarr/Radarr/issues/4122

**Comment by fryfrog** [comment]
Movies w/ colons work fine, I've got a bajillion of them. Without debug or trace logs, there pretty much isn't anything to do. Turn your logging up to trace, reproduce and put the relevant context in a pastebin.
