### ISSUE TITLE
Radarr renames movies eventhough its disabled

### ISSUE THREAD

**Issue by dreamer81** [Radarr/Radarr#4150]
Version 0.2.0.1450
Rename movies is disabled in settings.
When grabbing a new movie its downloaded correctly, but afterwards its copied to a renamed folder.

It looks like the renamed directory is created from the beginning of the process
![chrome_IBJKHoaSd7](https://user-images.githubusercontent.com/13866164/74532155-c2973200-4f2e-11ea-97d4-b2395ba73f6c.png)
![chrome_mMNXugmdM4](https://user-images.githubusercontent.com/13866164/74532156-c32fc880-4f2e-11ea-9742-b9d47c4bce50.png)
![chrome_br6vBwmhsQ](https://user-images.githubusercontent.com/13866164/74532158-c460f580-4f2e-11ea-8573-0b75042ec659.png)

**Comment by fryfrog** [comment]
You haven't shown a rename. The first thing you highlighted is Radarr "linking" the movie in the db w/ the right imdbid. The second is it just adding the movie folder.
