### ISSUE TITLE
[Request] Update Library needs more user control.

### ISSUE THREAD

**Issue by jiantjon** [Radarr/Radarr#4151]
**Is your feature request related to a problem? Please describe.**
I find it infuriating that the Update Library is so limited in how it's controlled.

**Describe the solution you'd like**
I would love it if you could add additional controls and options to it.  The following options would make the Radarr experience infinitely better:
1: Add a "Stop Update" button
2: In settings, have the ability to only update Monitored and/or missing items.
3: Have the ability to schedule the update to run when the user chooses, including both time and frequency.
4: For managing a large library, give the ability to update a specific range (E through G, for example), or update based on a chosen profile.  I expect this one to be a longshot, but I can see the benefit.

**Describe alternatives you've considered**
The only workaround that I can see at the moment for any of this is to stop the scan by restarting Radarr, but that doesn't always seem to work.  If the scan is in the middle of a scheduled scan, it seems to start scanning again. If the scan was kicked off manually, then restarting Radarr seems to work. 

**Other Ideas (unrelated)**
One other thought that I have that is unrelated would be to add multi-level filtering (Show all missing, unmonitored movies, etc). This would be a great help in the Edit section as well.  It would also be super cool to be able to filter out movies by profile, but I can work without that relatively easily. 

Thanks in Advance!

**Comment by bakerboy448** [comment]
Better covered under
https://github.com/Radarr/Radarr/issues/4407

and @geogolem is working on various filter and UI changes across a few PRs
