### ISSUE TITLE
Change Path / Rename not working through movie editor

### ISSUE THREAD

**Issue by mikemurk** [Radarr/Radarr#4155]
Folders/Files held in download location, not being copied to storage location - despite selecting change to root path.  Log shows selected path not being recorded - attempting to move/rename to current location.  Attempting to edit path through movie properties creates folder - but doesn't respect folder naming settings 

**To Reproduce**
Download movie using SABNZBD+ to download complete folder
Bulk import download folder
Select movie in movie editor (check-box)
Select new root folder (e:\serverfolders\Films) at bottom of screen - and click "organise".
App reports organise complete - however path not altered. Folder not renamed.
Log shows that request received to rename file with same name / location

Organise through the movie information also not working.

**Expected behavior**
moved to e:\serverfolders\films- folder renamed to MOVIE (2019), file renamed to MOVIE (2019).mkv

**Screenshots**
<img width="663" alt="Annotation 2020-02-15 184521" src="https://user-images.githubusercontent.com/26260976/74593500-b2ad4a00-5023-11ea-8e27-4520819e35cd.png">

**Desktop (please complete the following information):**
 - OS: Win Server 2008 R2
 - Version 0.2.0.1450 - 03 Dec 2019

**Debug Logs**
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/4208880/radarr.debug.txt)
*

**Comment by ta264** [comment]
Changing root folder doesn't move the files unless you have static path turned off for those movies.
