### ISSUE TITLE
Posters missing when restoring backup from Synology v2 to docker v3

### ISSUE THREAD

**Issue by enchained** [Radarr/Radarr#4157]
**Describe the bug**
2020-2-16 16:18:14.9|Warn|MediaCoverMapper|File /config/app/MediaCover/567/poster.jpg not found
<...>

The MediaCover folder was missing from the config/app/ completely.
To fix it I had to ssh to DSM and copy MediaCover folder from v2 to my v3's mounted volume:
cp -r /usr/local/radarr/var/.config/Radarr/MediaCover /volume1/docker/radarr_v3/app/MediaCover

I know this is a preview, but I think on a backup restore it should trigger the poster redownload, or offer to include posters when making a v2 backup (I didn't update v2 for a while so I'm sorry if it's already there).
My current v3 version is 3.0.0.2622

**Comment by Qstick** [comment]
Including posters in backup will result in huge backup files. On a normal v2 to v3 migration this would work fine as the data folder would be the same. I don't know if we want to do this.

**Comment by ta264** [comment]
Agreed, backing up the media covers (and keeping 7 different backups like we currently do) isn't a good idea in my opinion.  They'll just get re-downloaded on next refresh.

**Comment by enchained** [comment]
@ta264 If they indeed were going to just be redownloaded on refresh, maybe it's a good idea to trigger that refresh right after the restore if all the images were missing? I'm guessing Synology users of native dsm package moving to docker to test v3 is not a very rare case.
