### ISSUE TITLE
Option to see the filename and add "downloaded"/"missing" custom filter

### ISSUE THREAD

**Issue by enchained** [Radarr/Radarr#4158]
I just installed v3 and getting myself familiar with it. In v2 I always could filter by Monitored and sort by Downloaded to see which movies were downloaded already and decide whether I like the release and do I want to stop monitoring. I couldn't find the option to do that in v3. 

I know there's a Cutoff unmet filter, but there are cases when a BluRay is out, it's downloaded, and in about a week I have to manually replace it with a hevc release of my choice (manually - cause the other way the featurettes won't get imported (unless something changed?) and if I rely on radarr movie auto-import and add Featurettes folder that's left in downloads manually later, Plex won't recognize featurettes until I re-add the movie folder completely and rescan). 

I'm not sure if the latter problem is going to get addressed, but adding a column and a filter is an adequate request I guess.

**Comment by Qstick** [comment]
You can still filter by monitored and sort by downloaded (status). Or filter by monitored and size > 0 or some other custom filter. There are a few ways about this in v3

Also, please use the template when you post an issue, if not we will auto close it.

**Comment by enchained** [comment]
@Qstick Thank you so much, for some reason I was thinking that column was a profile, not the downloaded quality (maybe cause it was unstyled in v2, an here it's styled like a tag). And the Status in the custom filters confused me more, cause it contains another set of values, not the "downloaded/missing/etc", so I didn't look back to the status column after looking through the filters. 

And is it possible to display the movie filename already, or maybe it is something that's planned? 

I edited the description structure to conform to the template and added new information, sorry about before.
