### ISSUE TITLE
Different Year usage

### ISSUE THREAD

**Issue by devbrian** [Radarr/Radarr#4161]
In Radarr movie search(When attempting to add a new movie) and folder name for downloaded movies, radarr uses the main year from TMDB.  For the internal radarr year used for the movie file, radarr uses `movie.Year = lowestYear.Min()`.     This should all be consistent and I would vote to simply use the TMDB year for everything.

This is how you end up getting `Movie_Name (2015)/Movie Name (2014).mkv` . 

This may have a small impact on most people, but it causes me some serious issues with my decade setup.

**Comment by Qstick** [comment]
This is an issue in both versions, but marking Aphrodite for priority
