### ISSUE TITLE
Radarr Not Renaming and Moving Files on Organize

### ISSUE THREAD

**Issue by tehshaz** [Radarr/Radarr#4167]
I have two places that I keep movies,  a local folder on my unraid server and cloud location for archiving older movies.  According to feature request #2606, Radarr now moves the file as well as change the info.  I have tried this with multiple movies in the Movie Editor and both the UI and the logs say renaming and then immediately say renaming completed.  Even though there is no error, the folder location in the Radarr UI does not change and the files remain in the current folder. 

Radarr Version: 0.2.0.1480
Mono Version: 6.4.0
Docker: binhex/arch-radarr

Debug Logs:
2020-02-18 10:49:30,362 DEBG 'radarr' stdout output:
[Info] RenameMovieFileService: Renaming movie files for Resident Evil: Vendetta

2020-02-18 10:49:30,381 DEBG 'radarr' stdout output:
[Info] RenameMovieFileService: All movie files renamed for Resident Evil: Vendetta

**Comment by ta264** [comment]
#2606 says it's done in v3, you're on v0.2 

V3 isn't recommended for use just yet.
