### ISSUE TITLE
Trakt usersnames containing '.' characters not accepted when adding a 'UserWatchList'.

### ISSUE THREAD

**Issue by userrrrrrrr** [Radarr/Radarr#4168]
**Describe the bug**
When adding a Trakt 'UserWatchList' you are required to enter a username. If this username contains a '.' character the following errors is thrown:
Username is required when using User Trakt Lists

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Lists'
3. Click on '+'
4. Select 'Trakt List'
5. Select List Type 'UserWatchList'
6. Enter a username containing a '.'

Error 'Username is required when using User Trakt Lists' 

**Expected behavior**
Successfully added list

**Screenshots**
N/A

**Desktop (please complete the following information):**
Radarr version: 0.2.0.1480
Edge browser

**Debug Logs**
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/4221131/radarr.debug.txt)

**Comment by Diazole** [comment]
Trakt replaces the full stop with a hyphen.
