### ISSUE TITLE
A LOT of false positives when using Torrent Indexers

### ISSUE THREAD

**Issue by seanvree** [Radarr/Radarr#417]
Just a few examples:

 Wanted: The Mountain (2102)  http://www.imdb.com/title/tt2471640/
downloaded: The Mountain 1956 720p BluRay FLAC1 0 x264-EbP

Wanted:  Beauty and the Beast (2016) http://www.imdb.com/title/tt2771200/
Downloaded:  Beauty.And.The.Beast.1991.EXTENDED.1080p.BluRay.x264.DTS-MUxHD

Wanted: The One that Got Away (1996) http://www.imdb.com/title/tt0117250/
downloaded:  The.One.That.Got.Away.1957.720p.BRRip.x264-x0r

FYI, CouchPotato had this problem with not parsing the YEAR in addition to the title. They fixed it a couple weeks ago by adding a line in the torrent searcher.  Not sure if their code applies to yours. See here:

https://github.com/CouchPotato/CouchPotatoServer/commit/5b659f85933899b388f634a25502587c6ed4b5b6

**Comment by galli-leo** [comment]
This should only be the case with indexers that do not support imdbid. However, I will add a fix that requires title and year to match for an automatic download.

**Comment by seanvree** [comment]
Thanks! Keep up the good work gents!

**Comment by Kryptonit3** [comment]
False positives.
NZB - DogNzb
![false positive](https://i.snag.gy/riudGE.jpg)
