### ISSUE TITLE
Download client has reported an error. Retry failed downloads?

### ISSUE THREAD

**Issue by cubagithub** [Radarr/Radarr#4177]
I'm using Radarr on a Windows physical PC with qBittorrent as my download client on the same host, and downloads are sent to a powered USB hard disk. 

I get regular IO errors logged by Windows when accessing the disk, but the data is not corrupted.
```
An error was detected on device \...\DR1 during a paging operation.
```
Nevertheless, qBittorrent encounters an error and notifies Radarr, which marks the download as failed accordingly. If I re-check the torrent it will continue, but Radarr will not recognise that it's recovered and will either download a duplicate (if 'Re-Download' is enabled) or it will grab a different release and the progress of the recovered torrent is lost, and the torrent itself is unmanaged.

My ask: is there any retry/recover logic at the moment to recover from this situation, either manual or automatic in Radarr that I can try? Restarting Radarr or triggering the scheduled tasks don't appear to help i.e. 're-scanning' the failed downloads or querying the torrent client.

![image](https://user-images.githubusercontent.com/34730232/75000793-85ddb480-54b3-11ea-8f79-ad3fa8937f26.png)

**Comment by ta264** [comment]
Radarr already tries to grab a different release and retry if the download fails as you've discovered.

There's no logic to retry the exact same failed download or recover after the download has been marked as failed and I don't think we have any interest in adding that.  You need to fix your host so it doesn't randomly fail.

**Comment by cubagithub** [comment]
Thanks for responding @ta264 . I realise the root cause of my problem is my host/disk. 

This is a feature request for Radarr functionality to update torrent status from the download client. Currently, once Radarr sees it is failed, it stays failed without the option to refresh the status if the torrent is actually repaired or resumed. I can see value in this option outside my specific issue - there are various reasons a torrent could be marked as failed temporarily but is in reality not irrecoverable.

What I'm envisioning is, for example, a retry button next to failed downloads, like so:
![image](https://user-images.githubusercontent.com/34730232/75010343-fd6e0c80-54d0-11ea-8d4f-140d40282ff7.png)

Would like to know your thoughts.

**Comment by ta264** [comment]
What are the other reasons a torrent could temporarily fail?

**Comment by cubagithub** [comment]
> What are the other reasons a torrent could temporarily fail?

Any issues with reaching the download location, for example; storage, network, power failure - it would be even more frequent and common where the download client is not on the same host.

What I'm getting at is; a status of 'Failed' returned to Radarr from a download client is not necessarily a permanent or final status on every case. Radarr is able to poll the client for status updates during download for progress - why can't it also update status in cases where a torrent was failed, transiently?
