### ISSUE TITLE
Blacklist feature not working

### ISSUE THREAD

**Issue by Moletrix** [Radarr/Radarr#4178]
**Describe the bug**
I tried to remove and blacklist a movie from the activity queue.

**To Reproduce**
I tried to remove and blacklist a movie from the activity queue.

**Expected behavior**
Radarr blocks the torrent that torrent and searches for another one.

**Desktop (please complete the following information):**
 - OS: Linux Docker
 - Mono Version: 3.0.0.2622

**Debug Logs**
https://pastebin.com/VA1n919K

**Comment by Qstick** [comment]
Blacklist only blocks a specific release, not the entire movie. Unmonitor or remove the movie from Radarr.

**Comment by Moletrix** [comment]
Yes, I know but it always send the same specific release to my torrent client.
