### ISSUE TITLE
[Request] Make TMDb not required for adding movies via API

### ISSUE THREAD

**Issue by Abzie** [Radarr/Radarr#418]
Currently, via testing and creating the Wiki pages, I stumbled across this - the API expects both imdbId and tmdbId as an integer when adding a movie via the API, I guess most people will use one or the other, or neither, when adding a movie.

Would it be possible to make these optional, rather than required?

**Comment by galli-leo** [comment]
The IMDb ID shouldn't be needed. At least our UI only gets the IMDb id after adding the movie.

**Comment by galli-leo** [comment]
Also thanks for adding the docs!

**Comment by Abzie** [comment]
Nps, here's a response from an empty request, so you can see all of what is required:
```[
  {
    "propertyName": "ProfileId",
    "errorMessage": "'Profile Id' must be greater than '0'.",
    "attemptedValue": 0,
    "errorCode": "greaterthan_error",
    "formattedMessageArguments": [],
    "formattedMessagePlaceholderValues": {
      "propertyName": "Profile Id",
      "propertyValue": 0,
      "comparisonValue": 0
    },
    "resourceName": "greaterthan_error"
  },
  {
    "propertyName": "ProfileId",
    "errorMessage": "Profile does not exist",
    "attemptedValue": 0,
    "formattedMessageArguments": [],
    "formattedMessagePlaceholderValues": {
      "propertyName": "Profile Id",
      "propertyValue": 0
    }
  },
  {
    "propertyName": "Path",
    "errorMessage": "Invalid Path",
    "formattedMessageArguments": [],
    "formattedMessagePlaceholderValues": {
      "propertyName": "Path",
      "propertyValue": null
    }
  },
  {
    "propertyName": "RootFolderPath",
    "errorMessage": "Invalid Path",
    "formattedMessageArguments": [],
    "formattedMessagePlaceholderValues": {
      "propertyName": "Root Folder Path",
      "propertyValue": null
    }
  },
  {
    "propertyName": "Title",
    "errorMessage": "'Title' should not be empty.",
    "errorCode": "notempty_error",
    "formattedMessageArguments": [],
    "formattedMessagePlaceholderValues": {
      "propertyName": "Title",
      "propertyValue": null
    },
    "resourceName": "notempty_error"
  },
  {
    "propertyName": "TmdbId",
    "errorMessage": "'Tmdb Id' should not be empty.",
    "attemptedValue": 0,
    "errorCode": "notempty_error",
    "formattedMessageArguments": [],
    "formattedMessagePlaceholderValues": {
      "propertyName": "Tmdb Id",
      "propertyValue": 0
    },
    "resourceName": "notempty_error"
  }
]```

**Comment by Abzie** [comment]
Welp, seems it's just TMDb it requires.

**Comment by galli-leo** [comment]
But if we don't have a TMDb ID we cannot get any data. If you want to add a movie just from the name, you first have to do a /movie/lookup?The+Movie and then choose which one you want.

**Comment by Abzie** [comment]
It doesn't scrape any info, just appears in Radarr's movie listing with the parameters given in the request.

**Comment by galli-leo** [comment]
No afterwards we search the movie db with the provided info and propagate other metadata such as alternative titles. Without a TMDb id we cannot do that.

**Comment by Abzie** [comment]
Ah yes, I see what I did now. Originally, I mistakenly used the Resident Evil Collection ID (17255), rather than Resident Evil ID (1576), which must've confused Radarr's scraper and not added any info 👍
