### ISSUE TITLE
Connection - Emby # On delete

### ISSUE THREAD

**Issue by lelamamalgache** [Radarr/Radarr#4181]
Hello,

**Is your feature request related to a problem? Please describe.**
When a movie is deleted from radarr, the emby connection doesn't offer to update the library of emby or jellyfin, so the movie is deleted from radarr, but still present on emby or jellyfin

**Describe the solution you'd like**
Add tick button "On delete" Be notified when movies are deleted
Change Update Library Update Library on Download & Rename & Delete

[AB#1842](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1842)

**Comment by lelamamalgache** [comment]
Hello,
 Jellyfin has an option like emby which names "Enable real time monitoring" changes to files will be processed immediately, on supported file systems.

Tr@sh did a test on his radarr and emby, the movie is deleted from radarr and emby
i did a test on radarr and jellyfin : the movie is deleted from radarr but not jellyfin

i'm closing this ticket and open a new one to jellyfin.

Sorry

**Comment by lelamamalgache** [comment]
Real time monitoring doesn't work on all filesystems

so i have two solutions : 
use a wrapper file system
radarr  devs  implement the checkbox "on delete"

Could you implement "On delete" ?

**Comment by neo-neo1** [comment]
Discovered this by searching regarding this same issue. My use case also requires for Radarr delete notifications for Jellyfin to work. Not a dev but I'm currently looking at the code. Doubt my attempt will end up successful, but who knows. Perhaps someone else will be able to assist.

**For the non-familiar: Why this functionality is crucial:** 
On Jellyfin/Emby if your media library is connected via NFS/SMB/etc.. real time monitoring doesn't work on Jellyfin/Emby and thus the solution involves Radarr to send notifications upon media imports & deletes to Jellyfin/Emby to update it's library. However, currently delete notifications don't function as the [checkboxes are greyed out.](https://i.imgur.com/QIyXE3J.png)
