### ISSUE TITLE
System/Status Disk-Space (UUID)

### ISSUE THREAD

**Issue by TMTYD** [Radarr/Radarr#4182]
Hi guys,

Since I also use Sonarr, I noticed the following under System / Status (Disk Space).

With Sonarr the UUID of the hard disk is not shown, see screenshoot:

![grafik](https://user-images.githubusercontent.com/29516076/75104671-3c54ad00-560c-11ea-8baf-0229e5833c66.png)

With Radarr already, see Screenshoot:

![grafik](https://user-images.githubusercontent.com/29516076/75104665-2fd05480-560c-11ea-9c0a-6f685ff5f7a5.png)

So I started looking for what it could be because it looks nicer without a UUID. Then I came across the following.

I compared the following file main.js from Radarr and Sonarr, the Sonarr main.js says the following:

```
className : 'disk-space-path-cell',

render : function() {
    this.$el.empty();


    var path = this.model.get('path');
    var label = this.model.get('label');

    var contents = path;

    if (label && label !== path && !label.startsWith("UUID=")) {
        contents += ' ({0})'.format(label);
    }
```
The Radarr main.js says the following:

```
className : 'disk-space-path-cell',

 render : function() {
     this.$el.empty();

     var path = this.model.get('path');
     var label = this.model.get('label');

     var contents = path;

     if (label) {
         contents += ' ({0})'.format(label);
     }
```
So I have the same what is written in the main.js of Sonarr from if in the Radarr main.js. A new start made by Radarr and lo and behold, no UUID is displayed, looks a little nicer ;-)

![grafik](https://user-images.githubusercontent.com/29516076/75104740-f0eece80-560c-11ea-865e-5a554ce35820.png)

**Comment by Qstick** [comment]
This is fixed in V3, will accept PR for V0.2, but no plans to backport otherwise. Here it is if you want to give it a go https://github.com/Sonarr/Sonarr/commit/c659ba1c1090b2fca5b97816ab613f11f7a46373
