### ISSUE TITLE
Movies stay "missing" even though they should be "downloaded"

### ISSUE THREAD

**Issue by miniliQuid** [Radarr/Radarr#4183]
**Describe the bug**
Movies already available being ignored (or simply not noticed) and staying as "missing" then when found get downloaded again (often same file/release).

**To Reproduce**
1. Add movie.
2. Wait for download.
3. Update list in radarr.
4. Have movie still "missing" (it's rare though, have it with 4 or 5 movies)

**Expected behavior**
"missing" changes to "downloaded"

**Screenshots**
![radarr](https://user-images.githubusercontent.com/46374109/75113719-66c85980-5650-11ea-8b03-cbd4da2c1ab5.jpg)
This is the best example since I cannot get this to change to downloaded. I do however have more than this one (The Shining, Snow White and the Seven Dwarfs, etc.) but those get recognized after resaving to the same folder the movie file is in (which is weird, it already states the correct location) and then refreshing and doing it again. However next automated movie list update scan they often go to "missing" again and I have to do it again odd enough (at least I think it's the update scan that scrambles it).

**Desktop (please complete the following information):**
 - Windows 10
 - Firefox 73.0.1
 - Version 0.2.0.1480

**Debug Logs**
Not sure if it helps in this particular occasion, but here are the logs:
[radarr.txt](https://github.com/Radarr/Radarr/files/4241403/radarr.txt)

**Comment by miniliQuid** [comment]
Oh I notice the screenshot is off. I added a dash in movie & folder name, and then in radarr to see if that would solve anything. It didn't but I notice I hadn't changed it back yes in radarr.

Updates screenshot:
![radarr](https://user-images.githubusercontent.com/46374109/75113885-fcb0b400-5651-11ea-8429-95423a28fe12.jpg)

**Comment by Qstick** [comment]
This has been an issue for a while and isn’t likely to get fixed on v0.2. It shouldn’t be a problem on v3
