### ISSUE TITLE
Delete library / Aphrodite

### ISSUE THREAD

**Issue by mattystorey** [Radarr/Radarr#4186]
Hi, under Movie editor 2279 movies selected selecting delete and committing to the delete (do not delete files or exclude) fails with no error and simply sits there. Selecting smaller number of movies is fine.

**Comment by mattystorey** [comment]
Selecting 250 movies worked fine.

**Comment by ta264** [comment]
Please fill out the template

**Comment by mattystorey** [comment]
There appears to be a limit of circa 575-600 movies allowed to be selected. Anything over and the command is not registered.

As there is no way to limit the number of items per page like the last version under UI it makes using the movie editor challenging.
