### ISSUE TITLE
Moving movies between directories - Aphrodite

### ISSUE THREAD

**Issue by mattystorey** [Radarr/Radarr#4187]
Firstly, thank you for implementing this feature.

I've moved several movies using the movie editor from one directory to another directory. It has worked and then moved the .mkv + other files, additionally it has update the movie directory location from directory X to directory Y.  Directory name is not changed, file name is not changed. 

However, Radarr v3 can not find the movie. Running update/update all does not find the .mkv file. Deleting the directories (but not the contents) and then re-importing fails with 'duplicate' movies.

Running the most recent version.

**Comment by ta264** [comment]
Most recent is not a version, the template is there for a reason!

This was done in v3 so not sure why you're talking about v2

**Comment by mattystorey** [comment]
Version 3.0.0.2432

**Comment by ta264** [comment]
Latest is 3.0.0.2651.

What does Radarr V2 have to do with this issue?

**Comment by mattystorey** [comment]
Radarr V2 was a mistake between keyboard and chair.  And my docker container is showing that an update is needed to 3.0.0.2651.

**Comment by Qstick** [comment]
We need debug logs of a move, as @ta264 said the template is there for a reason. We can reopen when you provide everything
