### ISSUE TITLE
Url base missing from Deluge download client

### ISSUE THREAD

**Issue by CarlB86** [Radarr/Radarr#420]
I'm on the latest pre-release, Radarr.develop.0.2.0.210.windows.

When adding deluge download client the ability to set a URL base is not there. It is present on the rtorrent setup. I'm not able to add the full DNS entry for my seedbox without the url base, as it throws an error if I place the full path into the host.

Thanks

**Comment by hotio** [comment]
In verson 0.2.0.219 it's still there, nobody removed it, so...

**Comment by CarlB86** [comment]
That did it. Thanks!
