### ISSUE TITLE
Error Parsing Magnet Link From YTS/YIFY

### ISSUE THREAD

**Issue by HardlyAnonymous** [Radarr/Radarr#4202]
**Description:**
I receive the following error in my Radarr logs when attempting to grab a movie from YTS/YIFY's site (yts.mx).  This occurs with all YTS torrents to my knowledge.  If I add the torrent manually to my torrent client (Transmission), it works.  Please be aware that Radarr, Jackett, and Transmission are running in dockerized containers all running the latest versions to my knowledge.  I believe the YTS url used to be yts.lt and was changed to yts.mx fairly recently.

Example:
[Error] Transmission: Failed to parse magnetlink for movie 'Pokémon: Mewtwo Strikes Back - Evolution (2019) [1080p] [WEBRip] [5.1] [YTS] [YIFY]': 'magnet:?xt=urn:btih:598EA26E55A94EA064466D6B909B01D2A670DD64&dn=Pok&eacute;mon:+Mewtwo+Strikes+Back+-+Evolution+(2019)+[1080p]+[WEBRip]+[5.1]+[YTS]+[YIFY]&tr=udp://tracker.coppersurfer.tk:6969/announce&tr=udp://9.rarbg.com:2710/announce&tr=udp://p4p.arenabg.com:1337&tr=udp://tracker.internetwarriors.net:1337&tr=udp://tracker.opentrackr.org:1337/announce&tr=udp://tracker.zer0day.to:1337/announce&tr=udp://tracker.leechers-paradise.org:6969/announce&tr=udp://coppersurfer.tk:6969/announce'

**Radarr Version:**
v0.2.0.1450

**Mono Version:**
v5.20.1.34

**Debug Logs:**
DownloadService | Report sent to TransmissionVPN. Pokémon: Mewtwo Strikes Back - Evolution (2019) [1080p] [WEBRip] [5.1] [YTS] [YIFY] | 9:56am
-- | -- | --
  | Transmission | Failed  to parse magnetlink for movie 'Pokémon: Mewtwo Strikes Back - Evolution  (2019) [1080p] [WEBRip] [5.1] [YTS] [YIFY]':  'magnet:?xt=urn:btih:598EA26E55A94EA064466D6B909B01D2A670DD64&dn=Pok&eacute;mon:+Mewtwo+Strikes+Back+-+Evolution+(2019)+[1080p]+[WEBRip]+[5.1]+[YTS]+[YIFY]&tr=udp://tracker.coppersurfer.tk:6969/announce&tr=udp://9.rarbg.com:2710/announce&tr=udp://p4p.arenabg.com:1337&tr=udp://tracker.internetwarriors.net:1337&tr=udp://tracker.opentrackr.org:1337/announce&tr=udp://tracker.zer0day.to:1337/announce&tr=udp://tracker.leechers-paradise.org:6969/announce&tr=udp://coppersurfer.tk:6969/announce':  A field-value pair of the magnet link contain more than one equal'.

Free Pastebin account doesn't allow excessive sized files so I trimmed down the logs a bit that I'm hopeful includes the most necessary data.
https://pastebin.com/SmVBNQRF

**Comment by sentry07** [comment]
I'm seeing this on every torrent. Nothing downloads anymore. I'm on Radarr v0.2.0.1480.
