### ISSUE TITLE
Import Extra Files: Files in subfolders are not imported

### ISSUE THREAD

**Issue by jordi-j** [Radarr/Radarr#4207]
The Import Extra Files feature is not copying files in a subfolder(s) of the downloaded movie. 
E.g. consider the following structure for a downloaded movie and an import extra file setting of "txt,srt":

The Movie/
..The Movie.mkv
..Readme.txt <-- this file is picked up
..Subs/
....The Movie.eng.srt <-- this file is ignored

Expected behavior is that the extra files should be imported even if they are stored in subfolders.
This issue seems to be a regression of https://github.com/Radarr/Radarr/issues/1958.

System details: 
Radarr 3.0.0.2704 running on docker 5:19.03.6-3-0-ubuntu-bionic on Ubuntu 18.04.4 LTS

**Comment by fryfrog** [comment]
I'm also pretty sure this is a known problem on both v0.2 and v3, let me see if I can dig up another issue so I can close this one as a duplicate.

**Comment by fryfrog** [comment]
See #1958 and #3225.

**Comment by ryancurrah** [comment]
@fryfrog the issues you linked to are all closed. And the change that supposedly fixed this problem was reverted in December. I'd suggest re-opening this one or the original issue as it is not resolved

**Comment by superfish-lu** [comment]
I'd also suggest reopening.

**Comment by JBou** [comment]
I would also suggest to reopen it, this issue is not resolved yet.

**Comment by gacpac** [comment]
I noticed it was happening to me as welll. But I'm using a docker container from linuxserver 

Version
0.2.0.1480
Mono Version
5.20.1.34
