### ISSUE TITLE
Manual Import issue

### ISSUE THREAD

**Issue by daveyboy37** [Radarr/Radarr#421]
Guys, in the few days that I have been using Radarr, I haven't done any manual importing until today, so
I'm not really sure what I should be seeing but every movie gives the little pop-up in the bottom right.
I read that there has been issues with manual importing previously (before my time with radarr), but that they should be fixed on the latest, which I'm running...Any ideas?

<img width="567" alt="capture99" src="https://cloud.githubusercontent.com/assets/9288228/22252434/10b645f6-e246-11e6-9d25-96696f404ac1.PNG">
<img width="353" alt="capture98" src="https://cloud.githubusercontent.com/assets/9288228/22252441/15437328-e246-11e6-8872-b24c41267ca5.PNG">

**Comment by r1nzl3r9991** [comment]
Same here, I am getting this issue for any movie I download. Nothing will automatically import or manually import with the same "movie file must be chosen" error.

**Comment by Benni-chan** [comment]
click on the empty area left to the quality (right to the filename)
you should get a popup, where you can select the correct movie. (the movie needs to be added first)
then you need to mark the checkbox of the movie you want to manually import.

**Comment by daveyboy37** [comment]
Thanks, Benni
