### ISSUE TITLE
Add all folders to list with Bulk Importer

### ISSUE THREAD

**Issue by kahn10** [Radarr/Radarr#4211]
**Is your feature request related to a problem? Please describe.**
When importing films I have to constantly look at the logs and figure out where folder names went wrong and try to correct them to get Radarr to recognize them.

**Describe the solution you'd like**
I'd like for every unadded folder in the specified Movie repository to get an entry in the Bulk import Movies section, then I can go through the ones with greyed out checkmarks and add the TMDB number to those. It would also be good if there were a color or symbol that distinguishes them from duplicates.

**Comment by fryfrog** [comment]
Isn't that how it works? You Bulk Import your library and do a run through and import everything that matches properly... then you can do a second pass and hand match things that didn't? But it isn't going to fix the existing folders.

Bulk Import is intended to be aimed at an already well organized library, something roughly in the form of `./Movie Title (Year)/Movie Title (Year).ext` (or even better if file name has `Edition Quality-GrouP`.

**Comment by kahn10** [comment]
It is not how it currently works. Currently it only lists a folder if it matches to something whether it is correct or not. Which means something which is slightly off (e.g. off by one year, minor misspelling, etc.), Doesn't show up, it just adds a line to the log file. Wwen you're dealing with hundreds of films it's better to have it match what it can and fix the remainder. But rather than having to look at the log, look up the movie on TMDB, try to diagnose what went wrong, run the program again, and repeat, it would be so much easier to add the tmdbid and let the program rename it for you.

**Comment by fryfrog** [comment]
Ah, gotcha. I can't totally disagree w/ you. It would be nice. And in v3, I think the renaming of movie folders and root path moving might work better so maybe it is realistic.

**Comment by bakerboy448** [comment]
@kahn10 is this still an issue on the recent v3 builds?
