### ISSUE TITLE
lists ignoring original language

### ISSUE THREAD

**Issue by mbc0** [Radarr/Radarr#4215]
Using TMDb Popular lists when specifying original language (en) radarr pull foreign spoken movies.

**To Reproduce**
1. Go to 'settings'
2. Click on 'lists'
3. Scroll down to 'original lanuguage'

**Expected behavior**
I would expect radarr to import Movies spoken in English

![image](https://user-images.githubusercontent.com/19304467/76310552-e6982a00-62c6-11ea-9355-d74168abe978.png)

![image](https://user-images.githubusercontent.com/19304467/76310567-ef88fb80-62c6-11ea-8bd4-e28938672084.png)

Unriad Docker radarr V2 & V3

**Comment by Qstick** [comment]
Both movies in your screenshot have English as original language on TMDB, don’t see the issue with Radarr.

**Comment by mbc0** [comment]
Apologies, I never noticed that, this is obviously an error in tmdb not radarr as they are certainly not English spoken movies.  I will raise a request to add "allowed countries" like traktarr.

Thank you
