### ISSUE TITLE
UX - Modal Closes When Highlighting Text

### ISSUE THREAD

**Issue by ImSeaWorld** [Radarr/Radarr#4216]
**Is your feature request related to a problem? Please describe.**

When a modal is open (Like adding an indexer) when highlighting, upmouse triggers the modal to close. So while I was testing my indexer, I highlighted to remove something then the modal closed because I went out of bounds. This happened to me a lot and it was very frustrating to re-input all that information again.

**Describe the solution you'd like**

There's a close button in the top right of the modal, maybe restrict the modal close to only the close button when editing something?

**Comment by fryfrog** [comment]
Oh man, this gets me too. Usually when I'm trying to highlight something and I bump my mouse or something and bam, dialog gone. :/

**Comment by Qstick** [comment]
What version are you on?

**Comment by Qstick** [comment]
Per @markus101 this should not happen in V3, Unless this can be reproduced in v3 aphrodite, it likely will not be fixed. Marking v0.2 for closure unless can be verified in V3

**Comment by ImSeaWorld** [comment]
@Qstick 0.2.0.1480 develop

**Comment by Qstick** [comment]
Closing fixed in v3, not planning to fix back in v0.2
