### ISSUE TITLE
Missing files showing as available

### ISSUE THREAD

**Issue by alculete** [Radarr/Radarr#4217]
**Describe the bug**
When restoring a backup it shows movies as downloaded even if they are not available

**To Reproduce**
I've made a fresh install of my system and radarr after saving the backups.
after I restored the db backups and before I restored the media, I noticed that all the movies that I have downloaded showed as downloaded while there was no file available yet on the folder 

**Expected behavior**
This should mark my previous downloaded movies at least as not monitored since I enabled **delete unmonitored**

**Desktop:**
 - OS:  OS: Ubuntu 18.04.4 LTS x86_64
 - Mono Version:     5.20.1.34
 - Version 0.2.0.1480

**Comment by Qstick** [comment]
Unless this can be reproduced in v3 aphrodite, it likely will not be fixed. Marking v0.2 for closure unless can be verified in V3

**Comment by alculete** [comment]
I've moved to aphrodite and I can't reproduce it her. Thank you
