### ISSUE TITLE
Qualities are used more than once in profile.

### ISSUE THREAD

**Issue by tehniemer** [Radarr/Radarr#4218]
**Describe the bug**
A profile that has duplicate qualities and is unable to be modified or deleted. This profile has been abandoned and is not referenced anywhere that I can see, yet I still am unable to delete it. 

**To Reproduce**
Honestly, I have no idea. Maybe this happened during the upgrade from stable to Aphrodite.

**Expected behavior**
Qualities to only show up once, allow duplicates to be removed, or allow the profile to be deleted.

**Screenshots**
![image](https://user-images.githubusercontent.com/11021632/76415462-3f1f0400-6367-11ea-8571-8c3ba9ec8a4d.png)

**Desktop (please complete the following information):**
 - OS: Docker
 - Version: 3.0.0.2712

**Debug Logs**
Bug isn't triggered by anything, it's constant, but log attached.
[debug.log](https://github.com/Radarr/Radarr/files/4318172/debug.log)

**Comment by Qstick** [comment]
When did you migrate? Is the profile referenced by a list?

This was due to a bad migration that was fixed in https://github.com/Radarr/Radarr/commit/0d2660ee6c43e41c16fc6189d8de4d00689af966. You will have to delete the profile manually from the DB... Joys of alpha software! :D This shouldn't happen on any new migration.

**Comment by tehniemer** [comment]
It was a loooooooong time ago, it wasn't causing any problems so it fell to the bottom of my to-do list. It ended up being a list that was referencing it that I missed. I was able to delete it without having to edit the database. 

Aphrodite has been stable enough for me, sure feels like a solid beta.

**Comment by Qstick** [comment]
Solid Beta if we would quit breaking things :P. I would agree its nice compared to current "stable"
