### ISSUE TITLE
Trash Active Downloads when Deleting Movie

### ISSUE THREAD

**Issue by dannyvfilms** [Radarr/Radarr#4219]
If I remove a movie from Radarr while there is an active transfer in my download client, that download is not canceled when I delete the movie. If Radarr was able to cancel active downloads when a film is released, that would help a lot.

Right now my only solution is to have Transmission open to see if a movie is downloading in the event I want to delete something from Radarr. Doing it once might be fine, but doing it in bulk would be a mess.

**Comment by Qstick** [comment]
Dupe #3918
