### ISSUE TITLE
[Bug] Remove tvrage and tvdb from API History response

### ISSUE THREAD

**Issue by Abzie** [Radarr/Radarr#422]
See [API:History](https://github.com/Radarr/Radarr/wiki/API:History).

Both "tvdbId" and "tvRageId" are being returned in responses, presumably from:
https://github.com/Radarr/Radarr/blob/develop/src/NzbDrone.Core/History/HistoryService.cs#L164-L165

**Comment by onedr0p** [comment]
That's okay, we will clean it up over time. Not a big deal now.
