### ISSUE TITLE
Expose file creation date on upgrades

### ISSUE THREAD

**Issue by uchagani** [Radarr/Radarr#4220]
**Describe the problem**
Media servers often use the file creation date to show users the Latest Movies.  On upgrades in Radarr, the file is newer so it shows up as a new video in the Latest TV section.  By exposing the file creation date a user could run a script to change their upgraded file's creation date to match the old file thus preventing the file from showing up in the Latest Movies section in Plex/Jellyfin.

**Describe any solutions you think might work**
Add a new environment variable that is exposed on upgrades that contains the file creation date of the old file.

**Additional context**
This would also be nice as a radarr feature itself but exposing the date could be the easiest thing to do at the moment without having to do any UI updates.  

[AB#835](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/835)

**Comment by Qstick** [comment]
Lets track in #4913
