### ISSUE TITLE
Custom filter not case sensitive

### ISSUE THREAD

**Issue by Mizio66** [Radarr/Radarr#4225]
**Description:**
Th custom filter in Filter from Movies is not case sensitive, it should be.

**Radarr Version:**

3.0.0.2719

**Mono Version:**

5.18.0.240

**Debug Logs:**
N/a

**Comment by EnorMOZ** [comment]
Trace logs please

**Comment by Qstick** [comment]
What's the reason you think they should be case sensitive? I'm sure most users would prefer the opposite
