### ISSUE TITLE
"Add a movie" search not working in Windows

### ISSUE THREAD

**Issue by ahsenq** [Radarr/Radarr#4229]
**Describe the bug**
The "add a movie" search times out.

**To Reproduce**
1. Go to `Add Movie`
2. Type anything in the search bae
3. Appears to be searching but times out
4. See error: `2020-3-16 19:25:03.8|Debug|Api|[GET] /api/movie/lookup?term=rise+of+: 500.InternalServerError (100950 ms)`

**Expected behavior**
The search results are displayed

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Mono Version: N/A
 - Browser and Version:
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/4341216/radarr.debug.txt)
 Chrome
 - Version: 0.2.0.1480

**Debug Logs**
Turn on debug logs under Settings -> General and wait for the bug to occur again. **Upload the full log file here (or another site and link it). Issues will be closed, if they do not include this!**

**Comment by ahsenq** [comment]
Screenshot:
![image](https://user-images.githubusercontent.com/39447696/76816993-ec0ddc80-67be-11ea-825e-a3135918a5e1.png)

**Comment by ArtisanByteCrafter** [comment]
Same here, but ubuntu LXC container.

A glance at the log is showing that

```
Request Failed: Site responded with browser content instead of api data. This disruption may be temporary, please try again later. 
```

Looks like the API is having issues.

going to https://api.themoviedb.org/3/search/movie reveals an invalid certificate CA, so not sure whats going on there,

**Comment by ahsenq** [comment]
What's interesting is that it looks like Sonarr is using the same search and it is working fine.

**Comment by ahsenq** [comment]
I rebooted my modem and the problem has not come back for a day now. Closing the issue.
