### ISSUE TITLE
Kodi library cleanup not working

### ISSUE THREAD

**Issue by wessel145** [Radarr/Radarr#4230]
**Describe the bug**
When kodi is connected to radarr in the connect tab, cleanup after import can be selected, but is never executed.

**To Reproduce**
1. Have a connection with kodi in the connections tab with cleanup enabled
2. Upgrade a movie
3. The Kodi library gets updated
4. The Old movie gets removed from disk by Radarr, but still exists in Kodi

**Expected behavior**
The Kodi library will be updated and cleaned after a download

**Desktop (please complete the following information):**
 - OS: Docker (Ubuntu Server)
 - Version: 3.0.0.2719 (Aphrodite)

Trace log :

```
2020-3-17 12:33:58.2|Debug|XbmcService|Movie [Seberg (2019)][tt1780967, 510298] doesn't exist on XBMC host: 192.168.1.2:8082, Updating Entire Library
2020-3-17 12:33:58.2|Trace|XbmcJsonApiProxy|Response: {"id":10,"jsonrpc":"2.0","result":"OK"}
2020-3-17 12:33:58.2|Trace|XbmcJsonApiProxy|Looking for error in response, {"id":10,"jsonrpc":"2.0","result":"OK"}
```

Edit: the cleanup works using normal rpc commands
```
curl --data-binary '{ "jsonrpc": "2.0", "method": "VideoLibrary.Clean", "id": "mybash"}' -H 'content-type: application/json;' http://kodi:kodi@<kodiIP>:<KodiPort>/jsonrpc
```

**Comment by wessel145** [comment]
Issue is still persisting, Sonarr v3 does work tho.

**Comment by Qstick** [comment]
I'll try and look at this while I have Kodi installed from the last fix. What version are you on?

**Comment by wessel145** [comment]
I've ran some extra tests:
- Enabled trace
- Grabbed a 720p release (& wait for finish ofcourse)
- Checked in kodi headless if the movie gets added, unfortunately it doesn't
[Trace Error](https://pastebin.com/6qduEmsE)



I'm no magician when it comes to log interpreting but it looks like the wrong variables are passed?

Versions I'm using:
```
Version:    3.0.0.2955
Package Version:    3.0.0.2955-ls6 by linuxserver.io 
.NET Core:    Yes
Docker:    Yes (image: linuxserver/radarr:preview)
DB Migration:    172
```

My kodi setup is: 1 kodi-headless docker (which maintains the database, and thus receives the library.Scan commands and updates etc etc), with multiple kodi players throughout the house which use the same database as the 'master' server. 

These are my connection settings for the kodi connection in radarr
![image](https://user-images.githubusercontent.com/18014192/82294783-f90d9e80-99ae-11ea-8e35-e30276057383.png)

Please let me know if additional information might help fixing this bug ;)

Thanks!
