### ISSUE TITLE
Some invalid quality detections

### ISSUE THREAD

**Issue by segator** [Radarr/Radarr#4232]
I supose this is going to help to imrpove quality detection:

This one should be 1080p and is a mkv (detected as 2160p, I supose because the weird resolution)
AVC (1924x1040) (01:36:01) AC-3 (Spanish / English) |   | 3.8 GB | WEBDL-2160p 

This one should be 480p and is a mkv  (Detected as unknown)
AVC (720x552) (01:14:12) AC-3 (Spanish / English) |   | 1.5 GB | Unknown

this one should be a 1080p and is a mkv (Detected as unknown)
AVC (1920x800) (02:20:59) AC-3 (Spanish / English) |   | 4.3 GB | Unknown

this one should be a 576p and is a mkv  (Detected as unknown)
AVC (540x576) (01:35:41) AC-3 (Spanish / German) |   | 2.1 GB | Unknown

if you need more examples I have around 100 invalid detections,

btw This app is amazing!!

**Comment by Qstick** [comment]
Closing as the issue template was not followed, once all requested bug report info is added this can be opened.
