### ISSUE TITLE
Search missing movies

### ISSUE THREAD

**Issue by agneevX** [Radarr/Radarr#4234]
**Is your feature request related to a problem? Please describe.**
Yes. I want to prioritize the download of movies that are more relevant to me, in a sea filled with hundreds of stuff that aren't an immediate priority. 

**Describe the solution you'd like**
A search parameter like `is:missing` to search missing movies instead of all movies, in general or advanced search options with various parameters relating to various states that a movie might have.

**Comment by ta264** [comment]
This is already present via the filters no?

**Comment by agneevX** [comment]
That glitches half the time, yes.

**Comment by ta264** [comment]
Feel free to file a bug report (with the temokete filled out this time!)
