### ISSUE TITLE
Calendar BlueRay/DVD release

### ISSUE THREAD

**Issue by tiagoboldt** [Radarr/Radarr#4235]
**Is your feature request related to a problem? Please describe.**
It would be great if the DVD/Blueray release data would be added to the calendar. 

**Describe the solution you'd like**
Add a new label to the calendar with the BlueRay/DVD date. Selecting BlueRay/DVD/other would possibly be an option of preferred release medium from the settings.

**Additional details**
BlueRay has a release feed at https://www.blu-ray.com/rss/newsfeed.xml.

**Comment by bakerboy448** [comment]
exists in v3
