### ISSUE TITLE
Trakt WatchList not syncing

### ISSUE THREAD

**Issue by achmetinternet** [Radarr/Radarr#4237]
**Describe the bug**
I have not changed my Trakt list entries but when I test it now I get an error.

**To Reproduce**
Input your trakt credentials under the section "lists" in settings.

**Expected behavior**
Radarr fetches movies from my watchlist that are not in my library yet.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: FreeNAS
- Mono Version: 5.10.1.47
 - Browser and Version [e.g. chrome, safari] (Only needed for UI issues)
 - Version 0.2.0.1480

**Debug Logs**
see file attached.
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/4350614/radarr.debug.txt)

**Comment by geogolem** [comment]
I am not personally having any issues. Did you try re-auithenticating with trakt?

**Comment by achmetinternet** [comment]
Here you go, please delete if info in there is not for the regular user.
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/4366746/radarr.debug.txt)

**Comment by achmetinternet** [comment]
Why was this closed?

**Comment by Qstick** [comment]
It's been confirmed working, jump on discord and someone can help diagnose what is happening on your instance
