### ISSUE TITLE
Bulk Imports needs ability to scan subfolders

### ISSUE THREAD

**Issue by BermudaLamb** [Radarr/Radarr#4238]
**Is your feature request related to a problem? Please describe.**
I'm trying to do a bulk import of my existing movies. However, my movies are organized n folders.

**Describe the solution you'd like**
When I select a folder for bulk import, I would like the ability to scan subfolders recursively to find the video files. Currently, it is importing the folder itself, rather the video files in the folders.

**Describe alternatives you've considered**
It would be extensive rework on my part to reorganize my video library.

**Additional context**
Nothing else to add.

**Comment by Qstick** [comment]
Dupe #1170
