### ISSUE TITLE
Mockup for issues #403 (Enhance the links below movie posters)

### ISSUE THREAD

**Issue by hotio** [Radarr/Radarr#424]
![bitmap](https://cloud.githubusercontent.com/assets/25102010/22257612/d7b3ea42-e25e-11e6-8c4c-f8e5d7f1b8e0.png)

**Comment by jcchristian** [comment]
It seems you stopped raging and actually did a good thing, congratulations. It's indeed way better. You see, it didn't hurt at all, you critique and give a better option/solution, so much better!

**Comment by onedr0p** [comment]
Moved to http://feathub.com/Radarr/Radarr/+5
