### ISSUE TITLE
Allow Bulk Import to import duplicates and if chosen, update movie info with duplicate file data

### ISSUE THREAD

**Issue by esteencanto** [Radarr/Radarr#4240]
**Is your feature request related to a problem? Please describe.**
Some of us choose or need to manually manage final folder naming and folder allocation after Radarr helps with search and download. When upgrading existing movies or adding movies that are on wanted list, you have to manually update each movie's folder location and this takes a lot of time and could be easily solved by proposed solution described below.

**Describe the solution you'd like**
When doing Bulk Imports, Radarr correctly identifies duplicate movies. Right now, I don't think there is a way to "force-import" of the duplicate. Radarr should allow importing of duplicates (default should remain disabled as is) and update the movie info with the duplicate data (location, file size, format, etc), overriding the existing info. This would make manual organization and movie upgrading much easier and efficient. 

**Describe alternatives you've considered**
The only current alternative is manually updating existing movies with updated file location.

**Comment by fryfrog** [comment]
I'll let someone else close this as "won't do", but Radarr is about *automation* and making some mechanism to allow *manual* management of folder or file names would totally defeat the purpose. If that is your goal, I'd suggest another tool. You could just queue up torrents in your torrent client and do your manual file/folder management from there.

Radarr also doesn't support two copies of a movie, so if that is what you mean by duplicates... it is a long standing feature request, but doesn't work for now.

And it will allow you to import and replace existing movies too, so if that is what you mean by duplicates it works fine. You'll get a warning if it is lower quality or the same size, but if it is an upgrade, it'll replace it.

Bulk Import itself is meant to be run on a *well organized* library. If this is mainly what you're having issues w/, you should use another tool like Filebot to get it organized *first*.
