### ISSUE TITLE
Movies are having issues with years for 2019/2020

### ISSUE THREAD

**Issue by ajhong2** [Radarr/Radarr#4248]
**Description:**

Auto creating folder and file name. But the years are mismatching on some of the movies. Examples so far include The Hunt (2020) and The Banker (2020).

![image](https://user-images.githubusercontent.com/31233783/77398880-8ba21080-6d65-11ea-9ec8-2b4b19abb41e.png)

**Radarr Version:** 0.2.0.1480

**Mono Version:** 5.20.1.34

**Debug Logs:**

# Do not remove anything from your logs and post the full logs! If not everything fits in here use a service like https://pastebin.com to upload them.

**Comment by ajhong2** [comment]
![image](https://user-images.githubusercontent.com/31233783/77399065-dcb20480-6d65-11ea-8479-69f1e769e35d.png)

**Comment by ta264** [comment]
This is fixed in v3, won't be backported to v0.2 I don't think
