### ISSUE TITLE
Radarr is translating to english all my searches and titles of movies

### ISSUE THREAD

**Issue by SrOscuro** [Radarr/Radarr#4249]
**Describe the bug**
Hi! I don't know why but radarr translates the titles of movies in the searches...
For example: I search (in spanish) for "Harry Potter y las Reliquias de la muerte", in the description all appear good (in spanish as my search). But the search is made in english, and the results in English are first and with error "Spanish wanted", and Spanish results (if appear any) are on the end with errors like "Spanish is wanted, but found
Unknown is not wanted in profile"
![image](https://user-images.githubusercontent.com/21374449/77554728-b94a9f00-6eb6-11ea-942d-692309913522.png)

**To Reproduce**
1. Look for a movie writting the tittle in spanish
2. Click on the movie (Tittle and description appear here in spanish)
3. Click on "Search" button
4. All results in English first, with issue "found english, wanted spanish". In some movies at the end of the last results sometimes appear any result on spanish with errors like "Failed to find movie title in release name los simpsons la pelicula dvdscreener" or "Spanish is wanted, but found Unknown is not wanted in profile".
4.1. If I search for a movie that only exists with language spanish, radarr finds and downloads it very fast (with language spanish, since that film was only produced at spanish and does not exist in any other language) but the title is also translated to english and appears on Plex with the tittle on english and not at spanish, also the folder and movie file have their tittles on english and not spanish.

**Expected behavior**
Radarr stop translating my searches and the tittles of the films, if I want a movie at spanish radarr looks for the movie with the tittle I give it and not the translated one, also if I download a spanish film (with audio in spanish) maintain the original tittle and don't translate it.

**Screenshots**
![image](https://user-images.githubusercontent.com/21374449/77555699-d9c72900-6eb7-11ea-8ca3-017dcdf83ac6.png)

![image](https://user-images.githubusercontent.com/21374449/77555836-0418e680-6eb8-11ea-87d6-aeec26f2cbc3.png)

![image](https://user-images.githubusercontent.com/21374449/77555942-1f83f180-6eb8-11ea-9153-ce355a5ca26b.png)

![image](https://user-images.githubusercontent.com/21374449/77555977-290d5980-6eb8-11ea-9109-f20dd3cf5b9b.png)

**Desktop (please complete the following information):**
 - OS: Radarr is installed on a Debian 10 server
 - Mono Version: 5.18.0.240
 - Radarr Version: 0.2.0.1480
 - Browser and Version: Tested under various versions of Chrome, Firefox, Edge and Safari
 - Version -----

**Debug Logs**

[Radarr_Error.txt](https://github.com/Radarr/Radarr/files/4381948/Radarr_Error.txt)

**Comment by SrOscuro** [comment]
By the way, I almost forgot ...
I have a Spanish language in all profiles:
![image](https://user-images.githubusercontent.com/21374449/77557555-2e6ba380-6eba-11ea-9a1a-14494f07300e.png)

**Comment by pauloloks** [comment]
I found the same problem

**Comment by Syanelys** [comment]
Indeed, i experienced the same issue.
Very problematic.

**Comment by Yeka44** [comment]
same here

**Comment by fryfrog** [comment]
Great bug report, such detail and screen shots!

But your log file is not very useful. It is full of import errors because your history must have something old in it.

Can you follow the Sonarr [searches, indexers and trackers](https://github.com/Sonarr/Sonarr/wiki/Searches-Indexers-and-Trackers) troubleshooting article and put some *relevant* logs in a pastebin?

A key thing to keep in mind is that on *good* indexers, sonarr/radarr *aren't* searching by "Text". They're searching by imdbid or tvdbid. So you'll get results in *all* languages.
