### ISSUE TITLE
Add top billed cast list to movie detail page

### ISSUE THREAD

**Issue by brandonscript** [Radarr/Radarr#4250]
**Is your feature request related to a problem? Please describe.**
I'd love to be able to see the cast on a film's detail page. Useful when adding from a list, and you might not know anything about the film. Currently you have to link out to IMDb to figure it out.

**Describe the solution you'd like**
Something like this:

<img width="1436" alt="Screen Shot 2020-03-25 at 10 16 27 AM" src="https://user-images.githubusercontent.com/1480253/77565687-d0bb6500-6e81-11ea-844c-a6ca082b4abf.png">

**Comment by ta264** [comment]
Done in v3
