### ISSUE TITLE
Adult content  

### ISSUE THREAD

**Issue by Hollapayback** [Radarr/Radarr#4254]
**Is your feature request related to a problem? Please describe.**
Radarr seem to not be able to find adult content 

**Describe the solution you'd like**
I would like to see the option to turn adult content on and off

**Comment by Hollapayback** [comment]
Does this mean its beening worked on

**Comment by Qstick** [comment]
Yea, It's pretty straightforward, just need to decide on one thing...

**Comment by Hollapayback** [comment]
whats that

**Comment by Hollapayback** [comment]
and what might that one thing be

**Comment by Qstick** [comment]
If we are going to include it in the Radarr package as an option, or compile it as a separate program

**Comment by Hollapayback** [comment]
I would say make it a option so that people don't have to load a another program

**Comment by Animizio** [comment]
Hey anything new about that?

**Comment by Qstick** [comment]
It'll likely be a separate program, just need to come up with a clever name

**Comment by Hollapayback** [comment]
How about Ndarr or Adarr or periscope or viewfinder j

**Comment by Animizio** [comment]
Porns = slang "prons" + arr = Pronarr

**Comment by Hollapayback** [comment]
nice

**Comment by Qstick** [comment]
Something that somewhat fits the theme going with the others, and us a bit more sophisticated.. 😛

**Comment by Animizio** [comment]
Come on, just release it finally :dancing_women:  hahaha

**Comment by amarcum** [comment]
My personal preference would be just to have it as an advanced option in Radarr... I think there has been several attempts to make a fork for this purpose that haven't gone anywhere like the following. If someone wants an instance of Radarr that is only used for adult content then they can run a second instance on the same machine (for example 2 docker containers).
https://github.com/bonarr/Bonarr
https://github.com/klassicstudios/Bonarr

**Comment by Animizio** [comment]
I prefer a new program. Just to split the normal stuff from the Porns and also have some optimations for it

**Comment by Hollapayback** [comment]
So if we go with a new program all together are we just waiting for a sophisticated name that goes with the naming scheme of the others like raddar and sonarr  what about Exparr

**Comment by Qstick** [comment]
@Hollapayback That could work, the only other one I've gotten wasn't cheesy was Extracurricularr (lengthy, not really with the scientific terms theme, but sort of fits the bill for said program)

**Comment by Tharic99** [comment]
Pornarr?
Adultarr?
Eroticarr?

**Comment by jes1417** [comment]
Vadarr

**Comment by evendude7763** [comment]
Thermarr? (Thermal Imaging)

**Comment by bobbintb** [comment]
> Porns = slang "prons" + arr = Pronarr
> 
> Or just XXXarr 👯
> 
> Or Load&Come 😂😂😂😂😂

pr0narr. Don't forget the 0.

**Comment by Justahobby01** [comment]
Would this be a branch strictly for adult content or Radarr with an adult option for one stop shop? 

Keeping with the theme of  object detection technology:

Thermarr -  thermal imaging
X-Radarr - x-ray
Infraredarr - infrared

**Comment by austinwbest** [comment]
It would not be part of radarr at all is where it is headed (if created) it would be its own *arr

**Comment by jaydenthorup** [comment]
https://www.utopiacompression.com/technologies/monocular_passive_ranging.php

m2parr

**Comment by Thirrian** [comment]
Here's my vote for Wankarr 😄
(I know, doesn't fit the theme)

**Comment by FevLoad** [comment]
Wankarr is the name
I remember hearing this name in a British comedy show called the midnight beast

**Comment by bakerboy448** [comment]
This will be a different program and not supported in Radarr
