### ISSUE TITLE
Sort Defaults to Reverse Alphabetical

### ISSUE THREAD

**Issue by willmonahan** [Radarr/Radarr#426]
The default sort when I open the homepage is reverse alphabetical, starting with Z and working through to A. Is there any way to change the default sort to display forwards instead of backwards? Thanks!

**Comment by galli-leo** [comment]
You should be able to just click on the title header and the order should switch. It should stay the same when using this browser from now on.

**Comment by benbar21** [comment]
@galli-leo But wouldn't it make sense for the default to be A-Z instead of Z-A? Both because A-Z is, well, the natural order of letters but also because there are way more movies that start with early letters than later letters?

**Comment by willmonahan** [comment]
@galli-leo Thanks for the quick response! I realized that I can change the sort order for my browser, but I think that it might be even better if it defaults to an A-Z sort, both for new users and for when my cache is cleared (which resets the sort to Z-A)

**Comment by galli-leo** [comment]
@benbar21 Yes of course. I just said that so he knows how to change it.
