### ISSUE TITLE
Bulk import shows movie as disabled

### ISSUE THREAD

**Issue by danielb2** [Radarr/Radarr#4260]
**Describe the bug**

Bulk import doesn't allow me to import movie and it's disabled. Only way around this seems to be to manually copy the movie which defeats the purpose of the feature.

**To Reproduce**
1. bulk import
2. choose folder with movie

**Expected behavior**
Expect to  be able to import the movie

**Actual behavior**

Movie is disabled from import

**Screenshots**
<img width="948" alt="Screen Shot 2020-03-29 at 16 20 55" src="https://user-images.githubusercontent.com/26678/77866046-2a0af780-71e6-11ea-999f-dfe78ffca777.png">

**Desktop (please complete the following information):**
 - OS: Freebsd
 - Mono Version: 5.10.1.57
 - Browser and Version: Brave | 1.5.112 Chromium: 80.0.3987.132 (Official Build) (64-bit)

 - Version Radarr: Ver. 0.2.0.1480

**Debug Logs**
this problem didn't generate anything in the log files

**Comment by danielb2** [comment]
OK, so I figured out the problem. The problem was that the movie is already in the DB, but the movie file is missing, which is why I wanted to import it.

I think this can be fixed by radarr being smarter to see if the movie is, while being in the DB, actually present in the folder before rejecting the import.

Flow:

1. check if movie is in the DB already
  1. if it's not in the DB, just import
1. if movie is in DB, see if the movie file exists
  1. if it doesn't exist, import into existing folder as set

**Comment by danielb2** [comment]
Please change label from BUG to ENHANCEMENT

**Comment by Qstick** [comment]
This isn't going to get changed in v0.2. Its been re-done in v3
