### ISSUE TITLE
Radarr parser for Rarbg x265 movies

### ISSUE THREAD

**Issue by cimeiro** [Radarr/Radarr#4261]
When searching manual, so you can see the results, the list of results for a movie using the rarbg movie indexer, isn't showing the x265 movie files.
At least the simple ones, because some of the larger ones or the 4k ones are showing.

**Comment by Qstick** [comment]
Follow the bug report template and we will reopen this

**Comment by Dwayneson** [comment]
Hello,
Pardon my potential ignorance, but did this get resolved? I am having the same issue, and cannot find an open bug for it.
Thank you

**Comment by bakerboy448** [comment]
This issue is closed.
Come to the discord or Reddit for assistance troubleshooting first.

Then if it is still a bug and not user error Follow the issue template and provide all the details.

FYI v0.2 is in a critical bug fix state only. All development effort is going into v3
