### ISSUE TITLE
Not downloading profile even though its selected

### ISSUE THREAD

**Issue by gbdavidx** [Radarr/Radarr#4266]
**Describe the bug**
Not downloading profile even though its selected
<img width="466" alt="Screen Shot 2020-03-31 at 8 48 24 PM" src="https://user-images.githubusercontent.com/26369204/78097842-3f248980-7392-11ea-9137-3a714e672987.png">
<img width="1354" alt="Screen Shot 2020-03-31 at 8 58 00 PM" src="https://user-images.githubusercontent.com/26369204/78097926-7f840780-7392-11ea-958a-9efc1339e6eb.png">

**To Reproduce**
1. Add movie
2.  Expect it download version

**Expected behavior**
Download the 1080p version

**Screenshots**
See below
**Desktop (please complete the following information):**
it is on unraid / docker radarr v3 3.0.0.2747

**Debug Logs**
2020-3-31 17:54:51.7|Info|NzbSearchService|Searching 2 indexers for [Interstellar]
2020-3-31 17:54:51.9|Info|MediaCoverService|Downloading Fanart for [Interstellar (2014)][tt0816692, 157336] http://image.tmdb.org/t/p/original/xu9zaAevzQ5nnrsXN6JcahLnG4i.jpg
2020-3-31 17:54:52.6|Info|MetadataService|Movie folder does not exist, skipping metadata creation
2020-3-31 17:54:55.8|Info|DownloadDecisionMaker|Processing 128 releases
2020-3-31 17:55:07.0|Info|Nzbget|Adding report [Interstellar.2014.UHD.BluRay.2160p.DTS-HD.MA.5.1.HEVC.REMUX-FraMeSToR-Scrambled] to the queue.
2020-3-31 17:55:42.2|Info|DownloadService|Report sent to NZBget1. Interstellar.2014.UHD.BluRay.2160p.DTS-HD.MA.5.1.HEVC.REMUX-FraMeSToR-Scrambled
2020-3-31 17:55:42.2|Info|MovieSearchService|Movie search completed. 1 reports downloaded.
2020-3-31 17:55:54.0|Info|MovieService|Adding Movie [The Goonies (1985)][, 9340] Path: [/data/Movies/The Goonies (1985)]
2020-3-31 17:55:54.1|Info|RefreshMovieService|Updating Info for The Goonies
2020-3-31 17:55:55.0|Info|MediaCoverService|Downloading Poster for [The Goonies (1985)][tt0089218, 9340] http://image.tmdb.org/t/p/original/bZUbpjwnarSHJK40W9sGpyedWhx.jpg
2020-3-31 17:55:55.0|Info|DiskScanService|Scanning disk for The Goonies
2020-3-31 17:55:55.0|Info|DiskScanService|Completed scanning disk for The Goonies
2020-3-31 17:55:55.0|Info|MovieScannedHandler|[The Goonies] was recently added, performing post-add actions
2020-3-31 17:55:55.1|Info|NzbSearchService|Searching 2 indexers for [The Goonies]
2020-3-31 17:55:55.1|Info|MediaCoverService|Downloading Fanart for [The Goonies (1985)][tt0089218, 9340] http://image.tmdb.org/t/p/original/qKeyO9gXaaK0g87tvvqOPK1siwc.jpg
2020-3-31 17:55:55.4|Info|RssSyncService|Starting RSS Sync
2020-3-31 17:55:55.8|Info|MetadataService|Movie folder does not exist, skipping metadata creation
2020-3-31 17:55:57.0|Info|DownloadDecisionMaker|Processing 37 releases
2020-3-31 17:55:57.2|Info|MovieSearchService|Movie search completed. 0 reports downloaded.
2020-3-31 17:55:58.4|Info|DownloadDecisionMaker|Processing 200 releases
2020-3-31 17:55:59.4|Info|RssSyncService|RSS Sync Completed. Reports found: 200, Reports grabbed: 0
2020-3-31 18:06:25.5|Info|RssSyncService|Starting RSS Sync
2020-3-31 18:06:26.7|Info|DownloadDecisionMaker|Processing 200 releases
2020-3-31 18:06:27.7|Info|RssSyncService|RSS Sync Completed. Reports found: 200, Reports grabbed: 0

**Comment by ta264** [comment]
I'm going to guess you have the wrong profile set for the goonies

**Comment by gbdavidx** [comment]
it still does it for other releases

**Comment by Qstick** [comment]
Need some screenshots showing the profile you have set for a given movie, the profile settings for that same profile, and an example of a release failing that profile check.

**Comment by Qstick** [comment]
Closing for no response provided to info query
