### ISSUE TITLE
Subtitle files incorrectly renamed

### ISSUE THREAD

**Issue by kdbruin** [Radarr/Radarr#4267]
**Describe the bug**
When importing external subtitle files (SRT) they get named incorrectly. Instead of including a language code they are numbered sequentially.

**To Reproduce**
1. Add a new movie and go to movie page
2. Copy files to the new directory, including movie.mp4, 6_English.srt, 16_Dutch.srt
3. Update movie info and scan files
4. Preview rename for movie and apply

**Expected behavior**
The subtitle files should be named movie.en.srt and movie.nl.srt instead of movie.1.srt and movie.2.srt.

**Desktop**
 - OS: Linux Ubuntu 19.10
 - Mono Version: 5.20.1.34
 - Version 0.2.0.1480
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/4416136/radarr.debug.txt)

**Debug Logs**
Turn on debug logs under Settings -> General and wait for the bug to occur again. **Upload the full log file here (or another site and link it). Issues will be closed, if they do not include this!**

[AB#837](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/837)

**Comment by D3nn3** [comment]
Subtitles in Radarr are a mess to be honest, sorry to be so blunt.

I'm not a Radarr dev but I just looked over the code yesterday because I have also problems with subtitles and if I'm not mistaken Radarr checks only for the language iso codes that's why it doesn't recognize the languages.

If some dev is willing to takle all subtitle issues at once (language detection, sub directories, forced subtitles) I'm willing to help. Since I'm not primarily a C# dev and don't know the Radarr code base at all I don't think I'd be able to do it myself/alone.

**Comment by Qstick** [comment]
@D3nn3 Still around?

**Comment by D3nn3** [comment]
Of course @Qstick :) What do you need?

**Comment by hashworks** [comment]
This is still an issue.

**Comment by wsegatto** [comment]
Same as #5268 and still bugging me. :(

**Comment by bakerboy448** [comment]
this still an issue on the newer versions of v3?

**Comment by ArabCoders** [comment]
@bakerboy448 Indeed it still happens not sure about other language but it does for Arabic subtitles files. 

When renaming using Radarr GUI movie.year.ar.srt become movie.year.srt

**Comment by tehniemer** [comment]
This is still an issue. Additionally, it's not preserving `forced` subtitles and changing three letter code languages to two letter code. Example below.

```
move Multimedia/Movies/2012\ \(2009\)/2012\ \(2009\)\ Bluray-1080p\ \(tt1190080\).mkv -> Multimedia/Movies/2012\ \(2009\)/2012\ \(2009\)\ \[imdb-tt1190080\]\[Repack+Proper\]\[Bluray-1080p\ Proper\]\[8bit\]\[x264\]\[DTS\ 5.1\]-METIS.mkv
move Multimedia/Movies/2012\ \(2009\)/2012\ \(2009\)\ Bluray-1080p\ \(tt1190080\).eng.forced.srt -> Multimedia/Movies/2012\ \(2009\)/2012\ \(2009\)\ \[imdb-tt1190080\]\[Repack+Proper\]\[Bluray-1080p\ Proper\]\[8bit\]\[x264\]\[DTS\ 5.1\]-METIS.1.en.srt
move Multimedia/Movies/2012\ \(2009\)/2012\ \(2009\)\ Bluray-1080p\ \(tt1190080\).eng.srt -> Multimedia/Movies/2012\ \(2009\)/2012\ \(2009\)\ \[imdb-tt1190080\]\[Repack+Proper\]\[Bluray-1080p\ Proper\]\[8bit\]\[x264\]\[DTS\ 5.1\]-METIS.2.en.srt
```

**Comment by mvanbaak** [comment]
On rename, some subtitles are not renamed correctly.

I had .pt-BR.srt subtitle, and it lost the pt-BR part on rename. See screenshots.

Radarr version 4.0.0.5745

Right before rename: https://ptpimg.me/5aq73z.png
Right after rename: https://ptpimg.me/d051gh.png

**Comment by d3kstr0za** [comment]
I've also had issues with `.hr.srt`, `.bs.srt`, and `.sr.srt` getting replaced with numbers (e.g `.1.srt`) after I've changed my Movie Name pattern and ran a massive rename.

**Comment by tehniemer** [comment]
This PR in Sonarr may be worth looking into as a fix for this issue. I'm not good with code so I won't be much help past here. 
https://github.com/Sonarr/Sonarr/pull/4924
