### ISSUE TITLE
[Aphrodite] Remove everything when theirs a upgrade.

### ISSUE THREAD

**Issue by TRaSH-** [Radarr/Radarr#4268]
**Is your feature request related to a problem? Please describe.**
I had a few upgrades and i noticed that the downloaded subs didn't get removed

**Describe the solution you'd like**
Remove everything related to the old release

**Describe alternatives you've considered**
Manual removing :(

**Additional context**
None

**Comment by Qstick** [comment]
Is this resolved or still happening?

**Comment by TRaSH-** [comment]
had to do some searching,
my last one with left overs is from the 5th
![image](https://user-images.githubusercontent.com/6155095/82839411-9137e600-9ecf-11ea-9726-d15b14c3fbf4.png)

**Comment by Qstick** [comment]
There was a few fixes related to deleting that may have taken care of it. Figured I'd ask.

**Comment by TRaSH-** [comment]
I'll keep a eye on it,
Kinda busy at the moment with other things so I almost forgot.
So thnx for the ping

**Comment by TRaSH-** [comment]
This is fixed and works like it should.
with a upgrade also the later added subs get moved/deleted to the recycle-bin.
