### ISSUE TITLE
I would like to prioritize NZB over Torrents

### ISSUE THREAD

**Issue by gjannece** [Radarr/Radarr#4279]
**Is your feature request related to a problem? Please describe.**
I like to search for rare movie and sometimes torrents get picked first and they never finish downloading, so I need to go through my active downloads and manually run a research for each of the movies. 

**Describe the solution you'd like**
I would like an option under either "Indexers" or "Download Clients" to have use prioritize NZBs first then Torrents and / or a way to put a timer on the torrents and run a search and grab a different torrent while keeping the running one and remove them both when either one finishes.
  
**Example**
1)Add movie "Bad 80's monster movie"
2)Radarr searches for "Bad 80's monster movie"  
3)Radarr finds 3 under index
4) Radarr grabs NZB version first
5) Radarr NZB fails to download
6) Radarr grabs 1 of 2 torrent found
7) Radarr torrent doesn't finish downloading for 4 days
8) Radarr sees this this and grabs 2 of 2 torrent
9) Radarr torrent 2 of 2 finishes
10) Radarr removes 1 of 2 torrent because 2 of 2 finished

Thanks!

**Comment by Qstick** [comment]
You can already do this with delay profiles.
