### ISSUE TITLE
Movie adding with the wrong year (even after using IMDB code)

### ISSUE THREAD

**Issue by joelm3103** [Radarr/Radarr#4282]
**Describe the bug**
Been trying to add Dolittle (2020) and it keeps scraping as 2019, which is messing up my Kodi.

**To Reproduce**
1. Download movie
2. Check Info (which is wrong)
3. Delete movie, rename folder to correct year
4. Used IMDB code to redownload movie, point it to correct folder

**Expected behavior**
Movie year should be corrected to website and folder

**Screenshots**
Shows the correct date on IMDB and TMDB
https://i.imgur.com/nIrPkCk.png

**Desktop (please complete the following information):**
 - OS: Windows 10

**Debug Logs**
Turn on debug logs under Settings -> General and wait for the bug to occur again. **Upload the full log file here (or another site and link it). Issues will be closed, if they do not include this!**

**Comment by Qstick** [comment]
Fixed in v3, not likely to get fixed in v0.2
