### ISSUE TITLE
cant change static path for more than 250 movies

### ISSUE THREAD

**Issue by stumpyofpain** [Radarr/Radarr#4288]
**Describe the bug**
if you try to change the static path for more than 250 movies, nothing happens.

**To Reproduce**
1. Go to "movies - movie editor"
2. mark more than 250 movies
3. change "static path" to either yes or no
4. klick "save"
5. he does nothing.

Same problem if you change 250 movies and try to change 250 movies again without reloading the page.
1. Go to "movies - movie editor"
2. mark 250 movies
3. change "static path" to either yes or no
4. klick "save"
5. it works.
6. mark 250 other movies
7. change "static path" to either yes or no
8. klick "save"
9. he does nothing.

**Expected behavior**
i expected to change all my 1 000 movies together.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 18363
 - Firefox 74.0.1

**Comment by ta264** [comment]
This is all changed in v3 (and static paths option is gone). Unlikely to be fixed in v0.2
