### ISSUE TITLE
Movie folder in local language

### ISSUE THREAD

**Issue by Jorman** [Radarr/Radarr#4289]
Hi, in these days I'm trying aphrodite version and is very good!

I've a little request, is possible that during import, or renaming or managing, the have the movie folder in local language?
I mean, for example I add `Escape from New York (1981)` but in my local language the title is `1997: Fuga da New York`
Radarr recognize that and search and download the good version, but the folder name after the download still remain `Escape from New York (1981)`

Do you think is possible?

**Comment by Qstick** [comment]
Duplicate
