### ISSUE TITLE
Activity Queue Shows Blacklisted Releases Until Refreshed

### ISSUE THREAD

**Issue by tkdrob** [Radarr/Radarr#4290]
**Describe the bug**
Whenever I blacklist a release, it shows up at the top of the current activity queue page. Changing the page doesn't make it go away. Only an F5 or clicking one of the other sidebar items removes the phantom item. 

**To Reproduce**
1. Blacklist a release
2. Move page down or page up

**Expected behavior**
The blacklisted item does not reappear at the top of the list.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Docker
 - Browser and Version: Chrome 80
 - Version 3.0.0.2756

**Debug Logs**
Turn on debug logs under Settings -> General and wait for the bug to occur again. **Upload the full log file here (or another site and link it). Issues will be closed, if they do not include this!**

**Comment by Qstick** [comment]
Thanks for cleaning this up
