### ISSUE TITLE
Radarr /movie api

### ISSUE THREAD

**Issue by bobmagnuson** [Radarr/Radarr#4292]
I'm trying to use the API to get a movie by ID.  Trying in both 3.0.0.2794 and 0.2.0.1484.  The API references the ability to get a movie by id...  https://github.com/Radarr/Radarr/wiki/API:Movie#getid  but using the URL formatted as such http://192.168.0.143:7879/api/movie/?id=419704&apikey=44d48f6422424dffb464730b7e75c6d4 returns all movies, not the specific one.  Is what I'm trying to do possible or does the API not match the docs?  Incorrectly formatted URL?

**Comment by ta264** [comment]
http://192.168.0.143:7879/api/movie/419704&apikey=44d48f6422424dffb464730b7e75c6d4

**Comment by Qstick** [comment]
Should be with a `?` not an `&` :)

`http://192.168.0.143:7879/api/movie/419704?apikey=44d48f6422424dffb464730b7e75c6d4`
