### ISSUE TITLE
Let us give Radarr the Option to use the Folder Name for renaming

### ISSUE THREAD

**Issue by Youhbi** [Radarr/Radarr#4295]
**Radarr grabs the wrong Release Group**

**Is your feature request related to a problem? Please describe.**
Yes. Radarr only falls back to use the Foldername for renaming if the Movie File can not be assigned at all. A lot of releases are assignable, but are far from being correct. Radarr then tries it's best to find the correct Release Group and fails.

**Describe the solution you'd like**
It would be greate to get an option to tell Radarr to always use the Folder Name, which in my case is always the correct Release Name.

**Describe alternatives you've considered**
There really are none. :/

**Additional context**
Here are some examples:
https://pastebin.com/ejT3ftCA

**Comment by D3nn3** [comment]
I can confirm that especially german release groups have a really weird file name convention which does not provide any information and is therefore unusable for Radarr.

Radarr doesn't even need to use the folder name it can just use the release name it found (which afaik is the folder name anyway?).

**Comment by Youhbi** [comment]
Just using the release name would do the trick, since the folder has the same name anyway. This also shouldn't give any errors for other users.

**Comment by wormoworm** [comment]
+1 for this. There should definitely be an option to use the original release name as the folder nsme. This would result in the movie folder having the same name as if the torrent were added manually.

**Comment by bakerboy448** [comment]
the pastebin has been removed.

Can we get some examples here?
Is this still needing addressing on the latest v3 builds?

**Comment by Youhbi** [comment]
There you go. I'm not running v3 yet.
Radarr Ver. 0.2.0.1504 develop

Title EN:	The Perfect Host
Title DE:	Dinner For One – Eine mörderische Party
Folder:	Dinner_for_One_Eine_moerderische_Party_2010_German_DL_1080p_BluRay_x264-RSG_
File:		rsg-dinner-1080p.mkv
Release:	Dinner for One Eine moerderische Party 2010 German DL 1080p BluRay x264-RSG_

**Comment by bakerboy448** [comment]
Is this still an issue in v3?
V0.2 is no longer supported

**Comment by wormoworm** [comment]
This is still an issue in v3.0.2.4552.
What I (we?) would find useful is an option to use the original release name (as fetched from the tracker via Jackett) as a token when renaming movies and movie folders. Something like this would be perfect:
![image](https://user-images.githubusercontent.com/4249537/107958380-d3431380-6f99-11eb-878c-0a03aaa40ceb.png)

**Comment by bakerboy448** [comment]
Dynamic properties of the file or the release name are not supported in the folder name in v3

the folder is only related to the movie and can only use movie properties not release or file properties.

@wormoworm i am not sure that’s what the FR is.

my very rough understanding  given the absence of logs is that if the release name is not parsable then the folder name should be fallen back to for naming the file on import. In theory that should be what’s occurring, but no one has provided evidence to prove otherwise

closing pending additional info of the actual problem that is needed to be solved and confirmation that the issue actually exists in v3

**Comment by Youhbi** [comment]
Good morning bakerboy, hope your doing well.

Sorry for my late reply.
I actually do have the feeling it got much better. I believe to remember I had it once or twice in the last couple of weeks, but it surely got much better. 

If other people could provide some examples, which didn't work out that'd be great, because as of right now, I do not have any.

Right now I do have 2 movies which are stuck in my download folder tho, one even got downloaded 7 times in the end, because it couldn't be renamed. I have no idea why tho. The name, of the folder and the mkv itself, was perfectly fine and should've easy be used to assign to it's correct movie.

"Import failed, path does not exist or is not accessible by Radarr: /mnt/unionfs/sabnzbd/movies/Fast.Color.Die.Macht.in.Dir.2018.German.DL.AC3D.720p.BluRay.x264-GSG9.1/Fast.Color.Die.Macht.in.Dir.2018.German.DL.AC3D.BluRay.x264-GSG9.mkv. Ensure the path exists and the user running Radarr has the correct permissions to access this file/folder"

This seems like another problem, so irrelevant to this one here.

Thanks!
