### ISSUE TITLE
Dialog box loses focus when adding movie title in manual import

### ISSUE THREAD

**Issue by tusharbhutt** [Radarr/Radarr#4297]
If a movie is downloaded but not matched, the user is given the option to select a movie title after selecting manual import.  As you enter the title, the dialog box loses focus on every keystroke as the titles are filtered.

To reproduce:
1. Go to manual import
2. Select "Relative Path" checkbox 
3. Select "Select Movie" from the drop down in the lower left of the dialog box
4. The next dialog box lists all movies.
5. Start typing in the the "search movie"s field
6. The box loses focus and you have to click in in again to type the next letter

**Expected behavior**
The users should be able to type continuously in the title and select a movie without the field or dialog box losing focus

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Mono Version: N/A
 - Browser and Version: Firefox 74 
 - Version 3.0.2799
[debug.txt](https://github.com/Radarr/Radarr/files/4453322/debug.txt)

**Comment by Qstick** [comment]
Thanks, been meaning to add an issue for this and keep forgetting!
