### ISSUE TITLE
[Aphrodite] case insensitive (/i) set by default for all regex expression ?

### ISSUE THREAD

**Issue by hergonoway** [Radarr/Radarr#4298]
Hello, 

It seems that /i (ignore case sensitivity) is set as default for all regex expression in custom format. Is it a bug, something temporary or is it by design ? ... or worse did I miss something :) ?

if its (and will stay) the default behavior should I go for (?-i) to force case sensitivity ?

**Comment by Qstick** [comment]
Closing, no full bug template
