### ISSUE TITLE
Drag and Drop Files

### ISSUE THREAD

**Issue by jbrady21** [Radarr/Radarr#4299]
**Is your feature request related to a problem? Please describe.**

> As a user, when cleaning up files on the system that are not handled automatically I would like to have an easy and quick way to link files to a database show and have the system perform the processes required for importing.

**Describe the solution you'd like**

> Within the operating system (in my case Windows), I would like to select the file from windows explorer then drag and drop the file onto the shows information webpage (in my case chrome).

**Describe alternatives you've considered**

> Using the manual import option within the wanted page a user can manually select the desired show to import to.

**Additional context**

> ![DragAndDrop](https://user-images.githubusercontent.com/10509362/78902371-53761f80-7a3f-11ea-87e9-16b930684c91.png)

**Comment by Qstick** [comment]
Seems doable, not sure how many clicks it will really save vs doing a manual import though.... but definitely not going to happen in v0.2....

**Comment by ta264** [comment]
How would you deal with remote maps? File explorer could be a mounted drive and you're looking at the Radarr webpage as hosted on the fileserver. Not sure you'd be able to figure out the correct path to put in the database?

**Comment by jbrady21** [comment]
@Qstick I find that when I am having to do manual processing, these are the more obscure shows that users have added. Having a visualization confirmation of the file to the website information (image, file status, path, etc.) for me, as an administrator, this cue helps ensure accuracy in the manual process I am performing. 

@ta264 I am by no means a programmer, however, I thought I read some documentation on the drag and drop API that the file path/name was aN accessible variable.

**Comment by ta264** [comment]
I'm sure the file path will be available via the drag and drop API, the issue is that's only the correct path if you have file explorer open on the same pc that's running radarr. More often than non Radarr is run on a remote machine so the API will provide the wrong path from radarr's pov I think

**Comment by Qstick** [comment]
Yea good point, I was thinking nothing but UI this morning... unlikely to happen
