### ISSUE TITLE
Save folder options

### ISSUE THREAD

**Issue by charlieny100** [Radarr/Radarr#430]
I save all my movies to the same folder and can't see anyway to add a movie without putting it in its own folder. Am I missing something? Is there a reason to save each movie in its own folder? Maybe I'm doing it wrong.

**Comment by onedr0p** [comment]
https://github.com/Radarr/Radarr/wiki/How-to-Create-a-Folder-for-Each-Movie

https://github.com/Radarr/Radarr/issues/153

**Comment by charlieny100** [comment]
You misunderstood. I like to keep all my movies in the same root folder and can't seem to do that. But I'm also willing to change my ways if it makes sense.

**Comment by onedr0p** [comment]
I understand, the way you want it is still custom, see here https://github.com/Radarr/Radarr/issues/153#issuecomment-274355794
