### ISSUE TITLE
Some Alternate Titles are not being retrieved

### ISSUE THREAD

**Issue by jobrien2001** [Radarr/Radarr#4300]
**Describe the bug**
Alternate titles are not being retrieved in some movies, others seem to work fine. Very odd other movies seem to have them, cant account to what the frequency of this because I usually do not check for this.  I was trying to set up ufc titles and this is when i noticed the behavior.  Odd, happens with many ufc releases. I checked the last 5 releases and none of them had alternate titles in radarr.

Here some tmdb info i was able to confirm the titles are there:

https://api.themoviedb.org/3/movie/661420?api_key=
`{"adult":false,"backdrop_path":"/2UpF6H5EpAiaLAfDbnrpRVplCMk.jpg","belongs_to_collection":null,"budget":0,"genres":[],"homepage":"","id":661420,"imdb_id":null,"original_language":"en","original_title":"UFC 248: Adesanya vs Romero","overview":"UFC 248 PPV Main Event On ESPN+:  185 lbs.: UFC Middleweight Champion Israel Adesanya vs. Yoel Romero |  115 lbs.: UFC Strawweight Champion Weili Zhang vs. Joanna Jedrzejczyk |  155 lbs.: Beneil Dariush vs. Drakkar Klose |  170 lbs.: Li Jingliang vs. Neil Magny |  170 lbs.: Max Griffin vs. Alex Oliveira","popularity":4.019,"poster_path":"/mpLHWueVf9V86OFXnozYFywhJmJ.jpg","production_companies":[],"production_countries":[],"release_date":"2020-03-07","revenue":0,"runtime":180,"spoken_languages":[{"iso_639_1":"en","name":"English"}],"status":"Released","tagline":"","title":"UFC 248: Adesanya vs Romero","video":false,"vote_average":0.0,"vote_count":0}`

https://api.themoviedb.org/3/movie/661420/alternative_titles?api_key=
`{"id":661420,"titles":[{"iso_3166_1":"CA","title":"UFC 248 Adesanya vs Romero","type":"alt"},{"iso_3166_1":"US","title":"UFC 248","type":""}]}`

**To Reproduce**
1. Set profile language to english
2. add movie "UFC 248: Adesanya vs Romero"
3. check empty titles tab

**Expected behavior**
titles from tmdb should be retrieved

**Desktop (please complete the following information):**
 - OS: Unraid
 - linuxserver.io docker
 - Version 3.0.0.2799-ls4

**Debug Logs**
`2020-4-9 09:03:50.0|Info|DiskScanService|Scanning disk for UFC 248: Adesanya vs Romero
2020-4-9 09:03:50.0|Debug|DiskScanService|Scanning '/media.movies.mma/UFC 248 Adesanya vs Romero (2020)' for video files
2020-4-9 09:03:50.0|Debug|DiskScanService|1 video files were found in /media.movies.mma/UFC 248 Adesanya vs Romero (2020)
2020-4-9 09:03:50.0|Debug|DiskScanService|[UFC 248: Adesanya vs Romero (2020)][, 661420] Cleaning up media files in DB
2020-4-9 09:03:50.0|Debug|ImportDecisionMaker|Analyzing 0/1 files.
2020-4-9 09:03:50.0|Debug|ImportApprovedMovie|Decisions: 0
2020-4-9 09:03:50.0|Info|DiskScanService|Completed scanning disk for UFC 248: Adesanya vs Romero
2020-4-9 09:03:50.0|Debug|ExistingExtraFileService|Looking for existing extra files in /media.movies.mma/UFC 248 Adesanya vs Romero (2020)
2020-4-9 09:03:50.0|Debug|DiskScanService|Scanning '/media.movies.mma/UFC 248 Adesanya vs Romero (2020)' for non-video files
2020-4-9 09:03:50.0|Debug|DiskScanService|3 non-video files were found in /media.movies.mma/UFC 248 Adesanya vs Romero (2020)
2020-4-9 09:03:50.0|Debug|ExistingMetadataImporter|Looking for existing metadata in /media.movies.mma/UFC 248 Adesanya vs Romero (2020)
2020-4-9 09:03:50.0|Info|ExistingMetadataImporter|Found 0 existing metadata files
2020-4-9 09:03:50.0|Debug|ExistingSubtitleImporter|Looking for existing subtitle files in /media.movies.mma/UFC 248 Adesanya vs Romero (2020)
2020-4-9 09:03:50.1|Info|ExistingSubtitleImporter|Found 0 existing subtitle files
2020-4-9 09:03:50.1|Debug|ExistingOtherExtraImporter|Looking for existing extra files in /media.movies.mma/UFC 248 Adesanya vs Romero (2020)
2020-4-9 09:03:50.1|Info|ExistingOtherExtraImporter|Found 0 existing other extra files
2020-4-9 09:03:50.1|Info|ExistingExtraFileService|Found 0 extra files
2020-4-9 09:03:50.2|Debug|CleanExtraFileService|Cleaning missing metadata files for movie: UFC 248: Adesanya vs Romero
2020-4-9 09:03:50.2|Debug|MetadataService|Movie image already exists: /media.movies.mma/UFC 248 Adesanya vs Romero (2020)/poster.jpg
2020-4-9 09:03:50.2|Debug|MetadataService|Movie image already exists: /media.movies.mma/UFC 248 Adesanya vs Romero (2020)/fanart.jpg
2020-4-9 09:03:50.2|Debug|XbmcMetadata|Generating Movie Metadata for: /media.movies.mma/UFC 248 Adesanya vs Romero (2020)/UFC.248.PPV.720p.HDTV.x264-VERUM.mkv
2020-4-9 09:03:50.2|Debug|Api|[GET] /api/v3/credit?movieId=5548: 200.OK (4 ms)
2020-4-9 09:03:50.3|Debug|Api|[GET] /api/v3/queue/details?movieId=5548: 200.OK (23 ms)
2020-4-9 09:03:50.3|Debug|Api|[GET] /api/v3/movieFile?movieId=5548: 200.OK (32 ms)
2020-4-9 09:03:50.3|Debug|Api|[GET] /api/v3/netimport/schema: 200.OK (28 ms)
2020-4-9 09:03:50.4|Debug|Api|[GET] /api/v3/extraFile?movieId=5548: 200.OK (135 ms)
2020-4-9 09:03:53.2|Debug|Api|[GET] /api/v3/customFilter: 200.OK (14 ms)
2020-4-9 09:03:53.2|Debug|Api|[GET] /api/v3/tag: 200.OK (13 ms)
2020-4-9 09:03:53.2|Debug|Api|[GET] /api/v3/language: 200.OK (13 ms)
2020-4-9 09:03:53.2|Debug|Api|[GET] /api/v3/netimport: 200.OK (14 ms)
2020-4-9 09:03:53.2|Debug|Api|[GET] /api/v3/qualityprofile: 200.OK (18 ms)
2020-4-9 09:03:53.2|Debug|Api|[GET] /api/v3/config/ui: 200.OK (2 ms)
2020-4-9 09:03:53.2|Debug|Api|[GET] /api/v3/system/status: 200.OK (4 ms)
2020-4-9 09:03:53.3|Debug|Api|[GET] /api/v3/health: 200.OK (8 ms)
2020-4-9 09:03:53.3|Debug|Api|[GET] /api/v3/queue/status: 200.OK (9 ms)
2020-4-9 09:03:58.0|Debug|Api|[GET] /api/v3/movie: 200.OK (4772 ms)
2020-4-9 09:03:58.6|Debug|Api|[GET] /api/v3/movieFile?movieId=5548: 200.OK (13 ms)
2020-4-9 09:03:58.6|Debug|Api|[GET] /api/v3/credit?movieId=5548: 200.OK (12 ms)
2020-4-9 09:03:58.6|Debug|Api|[GET] /api/v3/queue/details?movieId=5548: 200.OK (10 ms)
2020-4-9 09:03:58.6|Debug|Api|[GET] /api/v3/extraFile?movieId=5548: 200.OK (30 ms)
2020-4-9 09:03:58.6|Debug|Api|[GET] /api/v3/netimport/schema: 200.OK (24 ms)
2020-4-9 09:03:59.0|Debug|Api|[GET] /api/v3/history/movie?movieId=5548: 200.OK (413 ms)`

**Comment by Qstick** [comment]
I can confirm this, seems to happen if the Radarr API mapping call bombs out... it doesn’t even add the tmdb titles.
