### ISSUE TITLE
Movie with supplimental title after its sequel number is not identified in blackhole scan directory

### ISSUE THREAD

**Issue by TheFeshy** [Radarr/Radarr#4302]
**Describe the bug**

Movies with titles similar to "Gremlins 2: The New Batch" are not identified by radarr in the watch directory.

Radarr is set up to use a "black hole" directory, and a watch directory.  The movie "Gremlins 2: The New Batch" was placed in this watch directory, but never identified or moved to the library.  Other movies in the same directory were processed normally.  This was also true of "The Naked Gun 2 1/2: The Smell of Fear" and "The Naked Gun 33 1/3: The Final Insult."  No log messages regarding these movies appeared (except in debug logging.)

I tried several file names to get it to scan, e.g. with and without the colon or other problematic characters.  However, as long as that "2" was in the middle, it did not work.  E.g. "Gremlins.2.the.new.batch.1990.bluray.x265.mp4" was not identified, and no log messages were found in radar regarding the file, except at the debug level.

However, after shortening the name to "gremlins.2.1990.1080p.bluray.x265.mp4" it was identified and added to the library normally.

Of note is that my library contains several movies with similar names that appear to have been bulk imported properly.

**To Reproduce**
1. Place a movie with a sequel number in the middle of its title into a watch directory
2. Nothing happens.

**Expected behavior**
Movies with such titles should scan normally.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: linuxserver.io's radarr docker container (running on Arch linux)
- Version: 0.2.0.1480
- Mono version: 5.20.1.34

**Debug Logs**
Here is the relevant section of the log; I can attach the whole thing if necessary, but as it's likely just a parsing issue this should be enough (This shows one movie being parsed properly - Benjamin Button, and one that is ignored -  Naked Gun 33 1/3.)  Both movies were in the watch folder, under sub-folders with names that matched their file names.:

2020-4-8 17:36:10.2|Debug|Parser|Parsing string 'The.Curious.Case.of.Benjamin.Button.2008.1080p.BluRay.x265'
2020-4-8 17:36:10.2|Debug|Parser|Movie Parsed. The Curious Case of Benjamin Button - 2008 
2020-4-8 17:36:10.2|Debug|ParsingService|Language(s) parsed: 
2020-4-8 17:36:10.2|Debug|QualityParser|Trying to parse quality for The.Curious.Case.of.Benjamin.Button.2008.1080p.BluRay.x265
2020-4-8 17:36:10.2|Debug|ParsingService|Quality parsed: Bluray-1080p v1 (None)
2020-4-8 17:36:10.2|Debug|Parser|Parsing string 'The.Curious.Case.of.Benjamin.Button.2008.1080p.BluRay.x265'
2020-4-8 17:36:10.2|Debug|Parser|Movie Parsed. The Curious Case of Benjamin Button - 2008 
2020-4-8 17:36:10.3|Debug|Parser|Parsing string 'The.Curious.Case.of.Benjamin.Button.2008.1080p.BluRay.x265'
2020-4-8 17:36:10.3|Debug|Parser|Movie Parsed. The Curious Case of Benjamin Button - 2008 
2020-4-8 17:36:10.3|Debug|ParsingService|Language(s) parsed: 
2020-4-8 17:36:10.3|Debug|QualityParser|Trying to parse quality for The.Curious.Case.of.Benjamin.Button.2008.1080p.BluRay.x265
2020-4-8 17:36:10.3|Debug|ParsingService|Quality parsed: Bluray-1080p v1 (None)
2020-4-8 17:36:10.3|Debug|DownloadedMovieImportService|The.Curious.Case.of.Benjamin.Button.2008.1080p.BluRay.x265 folder quality: Bluray-1080p v1 (None)
2020-4-8 17:36:10.3|Debug|DiskScanService|Scanning '/downloads/The.Curious.Case.of.Benjamin.Button.2008.1080p.BluRay.x265' for video files
2020-4-8 17:36:10.3|Debug|DiskScanService|1 video files were found in /downloads/The.Curious.Case.of.Benjamin.Button.2008.1080p.BluRay.x265
2020-4-8 17:36:10.3|Debug|ImportDecisionMaker|Analyzing 1/1 files.
2020-4-8 17:36:10.3|Debug|Parser|Parsing string 'The.Curious.Case.of.Benjamin.Button.2008.1080p.BluRay.x265.mp4'
2020-4-8 17:36:10.3|Debug|Parser|Movie Parsed. The Curious Case of Benjamin Button - 2008 
2020-4-8 17:36:10.3|Debug|VideoFileInfoReader|Getting media info from /downloads/The.Curious.Case.of.Benjamin.Button.2008.1080p.BluRay.x265/The.Curious.Case.of.Benjamin.Button.2008.1080p.BluRay.x265.mp4
2020-4-8 17:36:10.3|Debug|ParsingService|Language(s) parsed: 
2020-4-8 17:36:10.3|Debug|QualityParser|Trying to parse quality for The.Curious.Case.of.Benjamin.Button.2008.1080p.BluRay.x265
2020-4-8 17:36:10.3|Debug|ParsingService|Quality parsed: Bluray-1080p v1 (None)
2020-4-8 17:36:10.3|Debug|ImportDecisionMaker|Size: 2782694750
2020-4-8 17:36:10.3|Debug|GrabbedReleaseQualitySpecification|No grabbed history for this download client item
2020-4-8 17:36:10.3|Debug|SameFileSpecification|'/downloads/The.Curious.Case.of.Benjamin.Button.2008.1080p.BluRay.x265/The.Curious.Case.of.Benjamin.Button.2008.1080p.BluRay.x265.mp4' Has the same filesize as existing file
2020-4-8 17:36:10.3|Debug|VideoFileInfoReader|Getting media info from /downloads/The.Curious.Case.of.Benjamin.Button.2008.1080p.BluRay.x265/The.Curious.Case.of.Benjamin.Button.2008.1080p.BluRay.x265.mp4
2020-4-8 17:36:10.3|Debug|DetectSample|Runtime is over 90 seconds
2020-4-8 17:36:10.3|Debug|ImportApprovedMovie|Decisions: 1
2020-4-8 17:36:10.3|Debug|Parser|Parsing string 'The.Naked.Gun.2.1.2.The.Smell.of.Fear.1991.1080p.BluRay.x265'
2020-4-8 17:36:10.3|Debug|Parser|Movie Parsed. The Naked Gun 2 1 2 The Smell of Fear - 1991 
2020-4-8 17:36:10.3|Debug|ParsingService|Language(s) parsed: 
2020-4-8 17:36:10.3|Debug|QualityParser|Trying to parse quality for The.Naked.Gun.2.1.2.The.Smell.of.Fear.1991.1080p.BluRay.x265
2020-4-8 17:36:10.3|Debug|ParsingService|Quality parsed: Bluray-1080p v1 (None)
2020-4-8 17:36:10.4|Debug|Parser|Parsing string 'The.Naked.Gun.2.1.2.The.Smell.of.Fear.1991.1080p.BluRay.x265'
2020-4-8 17:36:10.4|Debug|Parser|Movie Parsed. The Naked Gun 2 1 2 The Smell of Fear - 1991 
2020-4-8 17:36:10.4|Debug|Parser|Parsing string 'The.Naked.Gun.33.1.3.The.Final.Insult.1994.1080p.BluRay.x265'
2020-4-8 17:36:10.4|Debug|Parser|Movie Parsed. The Naked Gun 33 1 3 The Final Insult - 1994 
2020-4-8 17:36:10.4|Debug|ParsingService|Language(s) parsed: 
2020-4-8 17:36:10.4|Debug|QualityParser|Trying to parse quality for The.Naked.Gun.33.1.3.The.Final.Insult.1994.1080p.BluRay.x265
2020-4-8 17:36:10.4|Debug|ParsingService|Quality parsed: Bluray-1080p v1 (None)
2020-4-8 17:36:10.4|Debug|Parser|Parsing string 'The.Naked.Gun.33.1.3.The.Final.Insult.1994.1080p.BluRay.x265'
2020-4-8 17:36:10.4|Debug|Parser|Movie Parsed. The Naked Gun 33 1 3 The Final Insult - 1994

**Comment by anillohchab** [comment]
Is there a way to handle this ?

**Comment by austinwbest** [comment]
Install v3, try it. If you run into an issue then hit up discord for support. If it can't be sorted out then we can move to a bug report.

**Comment by anillohchab** [comment]
Alright, I did try v3. It seems to have worked with more number of movies then the earlier version.  But I see its still having issues in some cases. 

For now, I am noticing this with "Tremors - 4". I do not even see this movie in the activity list during or after downloading. When I try to manually import it, the import checkbox is disabled for this .

**Comment by bakerboy448** [comment]
@anillohchab  as Austin said 
Support Requests -> [Reddit](https://www.reddit.com/r/radarr/) or [Discord](https://discord.gg/r5wJPt9)

but more than likely the name the movie is being parsed on is not the TMDb movie name, not a TMDb [alt title](https://www.themoviedb.org/movie/10891-tremors-4-the-legend-begins/titles, nor a translated title.
