### ISSUE TITLE
Some movies missing in api.radarr.video feed for imdb list

### ISSUE THREAD

**Issue by tvebax** [Radarr/Radarr#4306]
**Describe the bug**
Some movies from imdb list "randomly" (?) do not appear in the api.radarr.video feed and therefore can't get imported in Radarr. They do exist in TMDB.

**To Reproduce**
Examples:
https://www.imdb.com/title/tt7397176/
https://www.imdb.com/title/tt9261218/

Both exist on tmdb:
https://www.themoviedb.org/movie/660609-uncorked
https://www.themoviedb.org/movie/655297-krudttonden

Imdb watchlists can work both with user watchlist id and list id - these are identical lists. Radarr api lists for either are also identical. Neither variant contains either example item:

Radarr api list with list id does not contain either example:
https://api.radarr.video/v2/imdb/list?listId=ls003351718
The list on imdb does contain both examples:
https://www.imdb.com/list/ls003351718/

Radarr api list with user watchlist id is identical to above and does not contain either example:
https://api.radarr.video/v2/imdb/list?listId=ur26432876
User id watchlist on imdb is also identical to above and does contain both examples:
https://www.imdb.com/user/ur26432876/watchlist

**Debugging**
I tried removing some items from the imdb watchlist, but this merely resulted in less items in the api.radarr.video feed. There was 951, now 944.

The list itself has 1262 items which is definitely a lot. It does not seem to be a max items issue though, as the number on api.radarr.video list is variable?

The example items also exist at completely different places in the imdb watchlist (ie not at the beginning or end):
https://www.imdb.com/list/ls003351718/export
tt7397176 is item 1255 on the list.
tt7397176 is item 694 on the list.

NB: The total items on imdb watchlist is expected to be higher than api.radarr.video list, as many are far future movies without a tmdb id.

**Current imdb list csv export**
https://www.imdb.com/list/ls003351718/export

[WATCHLIST(1).csv.zip](https://github.com/Radarr/Radarr/files/4466445/WATCHLIST.1.csv.zip)

**Expected behavior**
All items on imdb list should appear on api.radarr.video feed if they have a tmdb entry

**Related (closed) issue**
#3684  

**Desktop (please complete the following information):**
Not really relevant, as this is about the api.radarr.video feed import from imdb. As the items do not exist here, there is nowhere for Radarr to import them from. They "get excluded" before ever reaching Radarr. No issues in the local Radarr install.

For completeness sake:
 - OS: OSX 10.13.6
 - Mono Version: 6.8.0.105
 - Radarr: 0.2.0.1480

**Screenshots of settings**
Not relevant, but for completeness sake:
<img width="1090" alt="Settings_-_Radarr" src="https://user-images.githubusercontent.com/42374813/79069964-86841180-7cd2-11ea-8b20-b7a0418cbe83.png">
<img width="1524" alt="Settings_-_Radarr 2" src="https://user-images.githubusercontent.com/42374813/79069967-8d128900-7cd2-11ea-923e-0fbde65ee41d.png">

**Comment by tvebax** [comment]
Moved to:
https://github.com/Radarr/RadarrAPI.TMDB/issues/59

**Comment by tvebax** [comment]
Alright - no action on https://github.com/Radarr/RadarrAPI.TMDB for 15 months.

Reopening this..

**Comment by tvebax** [comment]
Here is a list of additional movies which all exist on tmdb + can be added to radarr manually, but do not show up in the api.radarr.video feed:

https://www.imdb.com/title/tt9902160
https://www.themoviedb.org/movie/576901-mareld

https://www.imdb.com/title/tt9773184
https://www.themoviedb.org/movie/653708-herself

https://www.imdb.com/title/tt9742794
https://www.themoviedb.org/movie/630004-way-down

https://www.imdb.com/title/tt9378216
https://www.themoviedb.org/movie/666227-the-story-of-plastic

https://www.imdb.com/title/tt9371362
https://www.themoviedb.org/movie/645452-the-truth-will-out

https://www.imdb.com/title/tt9179096
https://www.themoviedb.org/movie/560008-minamata

https://www.imdb.com/title/tt9170516
https://www.themoviedb.org/movie/650031-shadows-in-my-eyes

https://www.imdb.com/title/tt9115530
https://www.themoviedb.org/movie/601470-the-eyes-of-tammy-faye

https://www.imdb.com/title/tt8948132
https://www.themoviedb.org/movie/639514-de-forbandede-ar

https://www.imdb.com/title/tt8750570
https://www.themoviedb.org/movie/653744-sergio

https://www.imdb.com/title/tt8484160
https://www.themoviedb.org/movie/526702-black-beauty

https://www.imdb.com/title/tt8429474
https://www.themoviedb.org/movie/646394-tunnels

https://www.imdb.com/title/tt8332802
https://www.themoviedb.org/movie/653615-amulet

https://www.imdb.com/title/tt8240250
https://www.themoviedb.org/movie/573657-out-of-tune

https://www.imdb.com/title/tt8009744
https://www.themoviedb.org/movie/649394-what-is-life-worth

https://www.imdb.com/title/tt7983894
https://www.themoviedb.org/movie/568467-ammonite

https://www.imdb.com/title/tt7557108
https://www.themoviedb.org/movie/575776-saint-maud

https://www.imdb.com/title/tt7523172
https://www.themoviedb.org/movie/632478-onkel

https://www.imdb.com/title/tt6439020
https://www.themoviedb.org/movie/520900-the-personal-history-of-david-copperfield

https://www.imdb.com/title/tt5420210
https://www.themoviedb.org/movie/650783-the-comeback-trail

https://www.imdb.com/title/tt5259822
https://www.themoviedb.org/movie/517412-tesla

https://www.imdb.com/title/tt5114840
https://www.themoviedb.org/movie/670439-six-minutes-to-midnight

https://www.imdb.com/title/tt2235372
https://www.themoviedb.org/movie/686548-son-of-the-south

https://www.imdb.com/title/tt1230522
https://www.themoviedb.org/movie/678488-banking-on-mr-toad

**Comment by Hebusing** [comment]
Hi,

I'm facing the exact same issue with the movie (I've only notice for this one, but very likely to have this issue for others as well):
[](https://www.imdb.com/title/tt10199590)
[](https://www.themoviedb.org/movie/586863)

I also tried to add one of the movie listed in the above post [()](https://www.imdb.com/title/tt7397176/) and although it appears on IMDB []((https://www.imdb.com/list/ls047548663/export),) the api.radarr.video feed doesn't grab it: [](https://api.radarr.video/v2/imdb/list?listId=ls047548663)


### Debugging
I've removed the movies with this issue from my IMDB list, added others (they appear in Radarr after), added those causing an issue, but they still don't show up in Radarr


### Configuration
Synology Nas DS418 with last DSM software.
Mono Version: 5.8.0.108 (the newer versions are causing lots of bugs so I had to revert to this one)
Radarr: 0.2.0.1480


Thanks for your help!

**Comment by ta264** [comment]
Digging around a bit, nothing can appear in the radarr video feed that has a TMDB id > 629046.  It's using a stale snapshot of tmdb as of September 2019.

Some of your example have lower id numbers, but at this point I don't think it's worth the major effort to fix in 0.2 when it's going to be retired soon.  I'm working on a fix for v3.
