### ISSUE TITLE
HD4Free test fails

### ISSUE THREAD

**Issue by xelra** [Radarr/Radarr#431]
When testing the connection to HD4Free, the test fails. I'm using the exact same settings as in Sonarr. Looks like something is broken.

> System.InvalidOperationException: Sequence contains no elements
  at System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0006c] in <63992662b765477a898ef49cdcc99ee2>:0 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].TestConnection () [0x0001a] in <b06b0076249e46d9b060b3a4fd13390e>:0

**Comment by onedr0p** [comment]
If you want this to work, I'll need an invite, did you try setting up Jackett or NZBHydra instead?

**Comment by xelra** [comment]
HD4Free is a torznab indexer. I'm not using Jackett. Are you in #radarr on freenode?

**Comment by onedr0p** [comment]
I am on Discord.

**Comment by galli-leo** [comment]
@xelra That test usually fails when your indexer hasn't enabled movie search. You can ask them if they can enable that with imdbid search support. You can also just add the indexer, but the results will not be as good and it might not work.

**Comment by onedr0p** [comment]
Closing, spoke with xelra and it was the indexer not having movie search.
