### ISSUE TITLE
Releases incorrectly labeled as Web-DLs

### ISSUE THREAD

**Issue by cptv** [Radarr/Radarr#4312]
Releases that only contain "1080p" or "720p" and not the original media source are being incorrectly labeled as Web-DLs. For example the release "The.Emperors.New.Groove.2000.HD.1080p.H264.AC3-5.1-RypS" shows up in Radarr as a "WEBDL-1080p" release. However there is nothing in the release name that indicates it is indeed a Web-DL

This causes issues since I have WEBDL-1080p at a higher priority than Bluray-1080p. For movies where there is actually no true Web-DL releases it will almost always grab these misparsed "Web-DL" releases. This is usually a release that would otherwise be unwanted as the mislabeled "Web-DL" supersedes any preferred tags or custom profiles I have setup for Bluray-1080p releases

I know in Sonarr if the release only has "1080p", and no a Web/Bluray/HDTV source info, it's labelled as "HDTV-1080p". IMO that would suffice as 99% of the time a true Web-DL release will be labelled as such with Web, Web-DL, or Webrip in the release name

Thanks for looking into this!

Radarr Version: 0.2.0.1480

Mono Version: 6.8.0.105

**Comment by Qstick** [comment]
I think this behavior is already changed in v3

**Comment by cptv** [comment]
@Qstick Gotcha. Any chance it can be fixed in v2 as well? I'm under the impression that v3 is still in the early stages of development and not worth upgrading to just yet. Though if you feel it's stable enough for everyday use I could give it a go

**Comment by Qstick** [comment]
Not going to happen by dev team likely, sorry

**Comment by cptv** [comment]
@Qstick Understandable. Any guidance on how I might make the change on my own setup? In the Github it seems like the logic is contained in the "QualityParser.cs" file. However I don't think that files is accessible in my Radarr v2 install

Would the proper sequence be to to download the entire source from Github, make some changes, build a new instance of Radarr, and then see if the changes behave properly? Sorry if that is a totally nooby question. It'd mostly be an exercise in seeing how feasible it would be for me to make very minor contributions in the future

**Comment by Qstick** [comment]
Yes that would be it, but you are better off just trying V3 I'd say. Just keep a backup
