### ISSUE TITLE
Missing root folder: /opt/radarr

### ISSUE THREAD

**Issue by lordraiden** [Radarr/Radarr#4322]
I get this error Missing root folder: /opt/radarr
![imagen](https://user-images.githubusercontent.com/17175395/79635296-7192fc80-8170-11ea-9039-5b59e9a36d95.png)
2020-4-16 18:24:38.8|Warn|DiskScanService|Movies' root folder (/opt/radarr) doesn't exist.
I have followed the instructions on the wiki
https://github.com/Radarr/Radarr/wiki/Health-checks#missing-root-folder
![imagen](https://user-images.githubusercontent.com/17175395/79635292-68a22b00-8170-11ea-9fdc-2a6178144293.png)
But he folder is empty, there is nothing inside. I am not using that folder in my Docker config either. Any idea on how to fix it?

Version
    0.2.0.1480
Mono Version
    5.20.1.34
AppData directory
    /config
Startup directory
    /app/radarr/bin

**Comment by shapetheLOLa** [comment]
Are you sure this isn't a bug? This error started appearing in my radarr a few days ago too.
