### ISSUE TITLE
Improvements to file matching

### ISSUE THREAD

**Issue by abjugard** [Radarr/Radarr#4325]
I've recently noticed that many of my completed downloads are not being handled by radarr, seemingly because radarr does not find a suitable movie in my downloads directory post-download. The indexer I use (PTP) guarantees that the download will contain the movie in question, so I feel like it should be possible for us to guarantee that we will find that file once it's downloaded.

My main question is, why are we even bothering with trying to find and match files when we already know which files are part of a download? If, for example, radarr downloaded a movie via a torrent, then by analysing the torrent file we can figure out which files should exist post download, and then we don't have to bother with trying to match anything at all, we can just analyse the type of the downloaded files to figure out what to do with them, as we know what movie a download belongs to. Found an mkv/mp4 among those files? Chances are pretty good it's the movie that radarr was tasked to download. If there are several video files, we can be reasonably sure the one with the longest runtime is the movie right?

I guess this approach doesn't work for all download methods or indexers, but for some indexers and download methods (eg. PTP torrents) we do know for certain that the download will contain the expected movie, and it's a shame we're getting stuck trying to find that file post download just because it wasn't named exactly how we expected it to be.

Literally all of these movies I'm having issues with, the torrents only contain a single file, and radarr is still not managing to figure out what to do.

**Comment by Krandor1** [comment]
You are misunderstanding how radarr works.   

There are two separate black boxes.  One black box is the one that scans and finds downloads and sends them to to the download client.  

Then there is a separate black box that looks at the information for the download client to process them.  No information from one black box is sent to the other.  The black box looking at information from the download client doesn't know the information from the black box that sent it to the downloader.  

That is just how radarr is designed.  If you'd like to change this behavior you are welcome to submit a pull request to do so.

**Comment by abjugard** [comment]
Is there a reason it is designed this way? It seems like it opens up for this kind of issue unnecessarily.

**Comment by ta264** [comment]
Krandor's statement isn't quite correct. Radarr knows which movie the file was grabbed for, but doesn't trust that the Download is what it says it is, hence this check

**Comment by abjugard** [comment]
I get that, but could we make an option for users to override that uncertainty? I fully trust my indexer (especially with the settings I have configured) to provide the correct movie.

**Comment by ta264** [comment]
If you want to make a PR we'll consider it. It's a fair amount of work though and tbh I'm surprised movies on PTP are so badly named they're not parsed

**Comment by ta264** [comment]
PS if you're serious about doing it jump on the discord to discuss with qstick or me (though we're both quite busy atm so bear with us)

**Comment by abjugard** [comment]
Non-english movies for the record.

**Comment by bakerboy448** [comment]
@abjugard I think this has been improved since April in v3

Depending, TMDb may need the alt titles, but this should be good.

Has this still been an issue/required feature?
