### ISSUE TITLE
Not all extra filenames update correctly after a rename

### ISSUE THREAD

**Issue by SiliconKid** [Radarr/Radarr#4326]
When you rename a movie with the Files tab active and visible, the Extra files do not get updated immediately.

You have to navigate away from the Files tab, and then back to the Files tab, and then the list of Extras files updates to reflect the new name. 

In general it's the name of the .nfo file that changes to align with the name change of the movie file itself.

This is noticeable because the name of the main movie file DOES update immediately after the rename is complete, without any refreshing of the page or navigation away and back required.

**Comment by Qstick** [comment]
Likely a SignalR issues with extras, but please fill in the entire bug report template instead of wiping it and typing what you want.
