### ISSUE TITLE
"Update movie info and scan disk" does not refresh metadata as expected

### ISSUE THREAD

**Issue by SiliconKid** [Radarr/Radarr#4327]
When you click the "Update movie info and scan disk" button on the movie details page Radarr does not scan the file for metadata (mediainfo?) again if the filename has not changed.

This means that if you replace an existing movie file with a new version that has been re-encoded to a lower bitrate, Radarr does not pick up the reduction in filesize and still shows the filesize as the size of the original file, if the filename does not change.

Radarr also does not scan the file for metadata again, even if the filename HAS changed, when using the "Rename Movie" feature. In this case I assume it's because Radarr assumes that when you use the Rename feature its only because you've changed some metdata in the Radarr UI (like the Quality for example) and that you have NOT replaced the original file with a different version (lower bitrate for example). In reality, if you are changing the quality you actually probably HAVE replaced the movie file with a different version that has a different bitrate. 

If you do a "Update movie info and scan disk" immediately after a Rename, that also does NOT result in a metadata rescan because Radarr sees not change in the filename since the Rename and therefore concludes that no rescanning of metadata is necessary.

**NOTE:** 

If you simply manually rename the movie file itself, change nothing else in Radarr, and then do an "Update movie info and scan disk", that DOES seem to trigger a full metadata rescan and Radarr immediately shows the new correct file size. But then you have to manually go and rename the movie back to what you actually want it to be, and then "Update movie info and scan disk" again to get the movie name to reflect accurately in Radarr, so that's a hack manual solution to force Radarr to think there's a new file invovled.

**To Reproduce**

Option 1
----------

1. Replace a movie file that has already been imported into Radarr with a new version of the same movie that has a lower bitrate and is a smaller file. But do NOT change the name of the file.
2. Go to the Details page for that same movie in Radarr.
3. Click the small spanner next to quality (Edit information about this file).
4. Change the Quality and click Save.
5. Click the "Preview Rename for Movie" button and verify that Radarr is about to rename the folder and files for the movie to reflect the new Quality you have set.
6. Click the Organize button to proceed with the Rename.
7. Observe that the file names and folder name have been renamed correctly BUT the files size has not been updated, it still reflects the size of the original file.

Option 2
----------
1. Replace a movie file that has already been imported into Radarr with a new version of the same movie that has a lower bitrate and is a smaller file. But do NOT change the name of the file.
2. Go to the Details page for that same movie in Radarr.
3. Click the small spanner next to quality (Edit information about this file).
4. Change the Quality and click Save.
5. Click the "Update movie info and scan disk button".
6. Observe that the files size has not been updated, it still reflects the size of the original file.

**Expected behavior**

In both scenarios described above, it would be better if Radarr did a full metadata scan on the movie file again and didn't rely on any previous data. Radarr should rather just assume scan metadata every time to be safe.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser and Version: Chrome Version 80.0.3987.163 (Official Build) (64-bit)
 - Radarr Version: Version 0.2.0.1450

**Comment by OuticNZ** [comment]
From what I can tell the import decision is binary at the moment.  Either the file already exists or it doesn't.  

Current logic:  Does existing filename = scanned filename if so then do not import the scanned filename

The logic would need to be:  Does existing filename of size X = scanned filename of size Y if so then do not import scanned filename

This would likely need to be treated as an update rather than a new file since the indexing logic is based on filename.  You would end up having two media files linked to the movie with the same name.

**Comment by townsmcp** [comment]
I’m having the same issues. Using Tdarr to reencode the files but Radarr isn’t seeing the file as changed when doing a scan

**Comment by bakerboy448** [comment]
possibly related to https://github.com/Radarr/Radarr/issues/4956?
