### ISSUE TITLE
Create Empty Movie Folder option is not saving. 

### ISSUE THREAD

**Issue by jpborjas** [Radarr/Radarr#433]
Create Empty Movie Folder option is not saving. If I changing it to No and Save, click away and come back, it'll be back in Yes. 

I'm running OS X, Radarr Version
0.2.0.210
Mono Version
4.6.2 (mono-4.6.0-branch/ac9e222 Wed Dec 14 17:02:09 EST 2016)

**Comment by fedoranimus** [comment]
I'm unable to reproduce this. Is anything showing up in your logs?

**Comment by jpborjas** [comment]
It seems to be working now. I don't know what I did, as I had already restarted it, etc. Thanks for your reply.
