### ISSUE TITLE
Adding a MULTI language option to the profile language setting

### ISSUE THREAD

**Issue by SpykeYs** [Radarr/Radarr#4331]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Adding a MULTI language option to the profile language setting

**Describe alternatives you've considered**
Choosing a specific language

**Additional context**
My kids like their movies in French but often by selecting the French option will not trigger any downloads. This is due to the fact that many releases are MULTI. By adding a MULTI language these would trigger.

**Comment by Qstick** [comment]
They way to go would be select Any and use custom formats to set preference. This is much more user friendly in v3
