### ISSUE TITLE
Lituanian language for movies 

### ISSUE THREAD

**Issue by Melomas** [Radarr/Radarr#4332]
Hello,

I'm user from Lithuania. Is it possible to integrate Lithuanian language in "Profiles"  for better search results?

Thank you

**Comment by Qstick** [comment]
It's already there <https://github.com/Radarr/Radarr/blob/f02fa629ccbd79b1ee9489370f112a89f70fe830/src/NzbDrone.Core/Languages/Language.cs#L97>

**Comment by Melomas** [comment]
I'm sorry. I'm not very good in programming. How I can implement it to my Radarr version?

**Comment by ta264** [comment]
You probably need to upgrade radarr
