### ISSUE TITLE
list label & filter

### ISSUE THREAD

**Issue by azumukupoe** [Radarr/Radarr#4333]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Label(s) to indicate which list(s) the movie was added from.
Filter movies by lists to toggle monitored status and etc.

**Describe alternatives you've considered**

**Additional context**

**Comment by Qstick** [comment]
You can already do this with tags... Set a unique tag for each list. Not planning on doing anything additional to this

**Comment by azumukupoe** [comment]
> 
> 
> You can already do this with tags... Set a unique tag for each list. Not planning on doing anything additional to this

Usable character are limited to alphabets+numbers for tags which isn't quite enough for me...

**Comment by azumukupoe** [comment]
> 
> 
> You can already do this with tags... Set a unique tag for each list. Not planning on doing anything additional to this

Can you filter movies by tags?

**Comment by Qstick** [comment]
In V3 yes you can

**Comment by azumukupoe** [comment]
> 
> 
> In V3 yes you can

as well as displaying multiple tags?

**Comment by Qstick** [comment]
Custom filter by one or many tags
![image](https://user-images.githubusercontent.com/376117/79782748-9375b600-830d-11ea-89d7-c8e4097612be.png)

Index display showing all tags
![image](https://user-images.githubusercontent.com/376117/79782815-aa1c0d00-830d-11ea-88e3-f8a5fc13b9bf.png)

Soooo YES!

**Comment by azumukupoe** [comment]
> 
> 
> Custom filter by one or many tags
> ![image](https://user-images.githubusercontent.com/376117/79782748-9375b600-830d-11ea-89d7-c8e4097612be.png)
> 
> Index display showing all tags
> ![image](https://user-images.githubusercontent.com/376117/79782815-aa1c0d00-830d-11ea-88e3-f8a5fc13b9bf.png)
> 
> Soooo YES!

Okay, thanks.
