### ISSUE TITLE
Add NZBHydra2 to preset requests

### ISSUE THREAD

**Issue by alculete** [Radarr/Radarr#4334]
**Is your feature request related to a problem? Please describe.**
I have NZBHydra2 configured and I'm unable to add it on radarr indexers

**Describe the solution you'd like**
Having NZBHydra2 already preset would make it easier to add, since I'm not sure if I'm doing the right thing, but I think setting usenet index is not vert different from jackett index

**Describe alternatives you've considered**
I tried using Newznab or any other preset and the reconfigure with my api key and url but didnt work

**Additional context**
Bellow is the error I get when trying to add. Note that I can search for files directly on nzbhydra
![image](https://user-images.githubusercontent.com/2129497/79740384-e0529000-82ff-11ea-9d89-5d36cc66431f.png)

**Comment by reloxx13** [comment]
it works with newznab, check your category settings.

**Comment by reloxx13** [comment]
![grafik](https://user-images.githubusercontent.com/14855001/79779050-fc732300-8339-11ea-9930-d6e6bbcb0bdf.png)

![grafik](https://user-images.githubusercontent.com/14855001/79779068-05fc8b00-833a-11ea-9e90-9ec63dc09062.png)

**Comment by Qstick** [comment]
Not planning on a preset for this as the baseurl will likely be different for everyone, and the other settings are same as any other newznab indexer.

**Comment by alculete** [comment]
@reloxx13 is your radarr version preview or stable?

**Comment by alculete** [comment]
OK thank you
