### ISSUE TITLE
Discover tab missing select and actions columns

### ISSUE THREAD

**Issue by jcthorne** [Radarr/Radarr#4335]
**Describe the bug**
Aphrodite, Movies, Discover.  Screen does not show columns Select and Action even though they are forced selected in columns selection dialog.  No way to select and add films from the list.

**To Reproduce**
1. Go to Movies, Discover
2. Columns for item selection and actions are not shown

**Expected behavior**
There should be a way of selecting items from the Discover list and adding them to Radarr, including option to search indexers now.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser and Version [e.g. chrome, safari] Chrome version 80.0.3987.163 (64 bit)
 - Version 3.0.0.2824

**Comment by jcthorne** [comment]
Just an update, the Lists tab has the same missing columns and lack of ability to select and add.

**Comment by Qstick** [comment]
Done
