### ISSUE TITLE
Mass Rename Tool

### ISSUE THREAD

**Issue by tucker19** [Radarr/Radarr#4336]
Is your feature request related to a problem? Please describe.
Mass Rename Tool in Master Movie Editor List

Describe the solution you'd like
Currently to rename any already movies the user needs to go into the individual movie and hit the `Preview Rename`. I think it would be nice to have the same for entire library if possible. I thought this could be in the `Movie Editor` in the list of all Movies.

Describe alternatives you've considered
Currently have to go into each individual movie and hit `Preview Rename`

Additional context
This would mainly be for users who accidentally did not enable movie renaming before enabling

Thank you for considering!

**Comment by Qstick** [comment]
We already have this in both v0.2 and v3

**Comment by tucker19** [comment]
How do I get to it then?

**Comment by tucker19** [comment]
> 
> 
> We already have this in both v0.2 and v3

I have never saw this feature. Where is this feature other than individual movie pages?

**Comment by Qstick** [comment]
Mass Editor / Organize
