### ISSUE TITLE
[API] IMDB endpoint does not respect limit parameter

### ISSUE THREAD

**Issue by TheHolyWaffle** [Radarr/Radarr#4338]
**Describe the bug**
When calling the imdb list endpoint, it does not respect the limit parameter as described in https://github.com/Radarr/Radarr/wiki/Supported-NetImports#radarrlists

**To Reproduce**
1. Open https://api.radarr.video/v2/imdb/popular?limit=15

**Expected behavior**
Only the top 15 most popular movies are returned

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Debug Logs**
N/A

**Comment by TheHolyWaffle** [comment]
This is still an issue!

Op za 20 jun. 2020 21:39 schreef stale[bot] <notifications@github.com>:

**Comment by Qstick** [comment]
This isn’t going to get fixed, we are deprecating that api in favor of a new. List Filters and limits will likely get moved client side as to not kill caching.
