### ISSUE TITLE
No "scene name" for manually imported movies

### ISSUE THREAD

**Issue by Zamana** [Radarr/Radarr#4339]
**Describe the bug**
There is no "scene name" to use in Bazarr when you manually import a film in Radarr.

**To Reproduce**
1. Search and download a movie using your torrent or nzb client
2. Add the movie into Radarr, but don't let it to download automatically.
3. In Radarr, go to "Wanted", "Manual Import", and import the movie.
4. Go to Bazarr, find the movie, and try to grab a subtitle.
5. You'll see that the "Scene Name" is empty...

**Expected behavior**
As long as the movie was imported using the "Raddar engine", the scene name should be there.

**Screenshots**
Attached.

Radarr is configured to rename movies, and "Use Scene Name When Available" is configured in Bazarr. This is not a Bazarr issue.

**Desktop (please complete the following information):**
 - OS: FreeNAS 11.3-U2
 - Mono Version: 5.10.1.57
 - Version: 0.2.0.1480

<img width="923" alt="Screen Shot 2020-04-22 at 12 34 41" src="https://user-images.githubusercontent.com/6900313/80003309-373e9d80-8497-11ea-9f06-cd9d833accd2.png">

**Comment by JBou** [comment]
This is going to be fixed for aphrodite (Radarr v3) in this PR #4274.

**Comment by Zamana** [comment]
Well... I will only be able to use Aphrodite when .NET Core be ported to FreeBSD...

Until then is there any other way to force Radarr to fill the "scene_name" field for cases like this?

**Comment by Qstick** [comment]
We build Aphrodite for mono as well, just for FreeBSD folks

**Comment by Zamana** [comment]
Would you mind to tell me where I can find one of these builds?

Thanks.
Regards.
