### ISSUE TITLE
Trakt custom list not importing

### ISSUE THREAD

**Issue by RemakingEden** [Radarr/Radarr#4348]
Hi guys, I believe this is user error but I am at my wits end so hoping I can get some help. I have added a Trakt list from another user and I cannot get the films to import.

![image](https://user-images.githubusercontent.com/12913562/80240545-e9be5e00-8659-11ea-822c-c445fc70e1e3.png)

Above is the screenshot of my config. I currently don't have my Trakt auth details in the associated slots as this is not my list nor private.

I have tried refreshing, leaving for 24 hours, System > NetImportSync & everything else I can find online.

The list I am trying to add is https://trakt.tv/users/lish408/lists/rotten-tomatoes-best-of-2019?sort=rank,asc

Sorry if this is obvious and thank you for any help!

**Comment by Qstick** [comment]
Not sure why support bot didnt take care of this

**Comment by RemakingEden** [comment]
> Not sure why support bot didnt take care of this

Hi Qstick you closed this? Does that mean that no one can give any advice at all?

**Comment by ta264** [comment]
Use the discord for support not GitHub. The support bit was supposed to give a friendly message but he's obviously on lockdown too...
