### ISSUE TITLE
Use custom images for movie poster artwork

### ISSUE THREAD

**Issue by sunrisepi** [Radarr/Radarr#4352]
**Is your feature request related to a problem? Please describe.**
Sometimes a movie does not have an image shown (just the default Radarr image).  I notice when adding a movie that there is no image shown, as if the root database which is used (tvdb?) doesn't have an image available for download.  That's OK and I don't expect it to have every single movie image.  To work around this, I would like to be able to supply my own custom image (such as a JPG).  But I see no way to edit this in the UI within Radarr.  Example movies that have no posters available:  Just Peck, The Big Ask, Building Girl.

**Describe the solution you'd like**
I would like an option in the UI to be able to click on a field/option for a movie and be able to select a custom movie poster image from my local drive.

**Describe alternatives you've considered**
I tried looking in ./config/Radarr (using Linux) but cannot figure out where to place custom images.  Debug logs do not seem to indicate where the image is trying to load from.  It just doesn't exist.  I haven't had time to try to install sqllite and load the radarr DB to try to figure out how radarr stores movie posters.  I think if I did that it may give some clues.

**Additional context**
Thanks for considering my suggestion.   I tried searching on reddit (r/radarr) and was surprised that no one else has been having this issue??  Seems like this would be an easy feature to implement and it could make it really nice to add this customization.  If it is possible to do this using Radarr today, please let me know.  I didn't see this in the FAQ or wiki either...

**Comment by Qstick** [comment]
Not planned, update tmdb
