### ISSUE TITLE
All Movies Self-Deleted.

### ISSUE THREAD

**Issue by Renakh** [Radarr/Radarr#4355]
Radarr deleted everything in my movie folder. 

**Radarr Version:**
3.0.0.2871
**Mono Version:**

**Debug Logs:**
[radarr.txt](https://github.com/Radarr/Radarr/files/4533654/radarr.txt)

**Comment by Qstick** [comment]
I’d venture to say either you have list library clean on, accidentally deleted all in editor, or someone got access to your instance.. Radarr doesn’t just up and decide to delete your entire library. The info logs don’t really tell us anything about what triggered the delete, just that it happened. What were you doing at the time? Do you have the instance open to the web?

Also why are you running Aphrodite without recycle bin, or debug logs on?
