### ISSUE TITLE
radarr v3 -- Unable to add imdb watch list / incorrect log message

### ISSUE THREAD

**Issue by thezoggy** [Radarr/Radarr#4357]
unable to add imdb watch list: `Unable to connect to indexer. List responded with html content. Site is likely blocked or unavailable.`

log message is also incorrect as this is not an indexer.

```
2020-4-25 15:31:59.2|Debug|RSSImport|Downloading List http://rss.imdb.com/user/urXXXXXXXX/watchlist
2020-4-25 15:32:01.1|Warn|RSSImport|Unable to connect to list

[v3.0.0.2871] NzbDrone.Core.NetImport.Exceptions.NetImportException: List responded with html content. Site is likely blocked or unavailable.
   at NzbDrone.Core.NetImport.RSSImport.RSSImportParser.PreProcess(NetImportResponse netImportResponse) in d:\a\1\s\src\NzbDrone.Core\NetImport\RSSImport\RSSImportParser.cs:line 121
   at NzbDrone.Core.NetImport.RSSImport.RSSImportParser.ParseResponse(NetImportResponse importResponse) in d:\a\1\s\src\NzbDrone.Core\NetImport\RSSImport\RSSImportParser.cs:line 40
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.FetchPage(NetImportRequest request, IParseNetImportResponse parser) in d:\a\1\s\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 115
   at NzbDrone.Core.NetImport.HttpNetImportBase`1.TestConnection() in d:\a\1\s\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:line 151

2020-4-25 15:32:01.1|Warn|RadarrErrorPipeline|Invalid request Validation failed: 
 -- : Unable to connect to indexer. List responded with html content. Site is likely blocked or unavailable.
```

--

Desktop install (nothing funky)
OS: windows7 x64
Radarr Ver: 3.0.0.2877

**Comment by Qstick** [comment]
Does this actually work in v0.2? What is the specific list you are trying to access so I can test local?

Will fix the log saying indexer.

**Comment by magic-bear** [comment]
/imdb/list?listId=ls002728609

Might be a good example. This list was working for me and now doesn't.

**Comment by thezoggy** [comment]
Googling I see that the list my friend has in v2 used to work but looks like it stopped due to changes on imdb side // https://www.reddit.com/r/radarr/comments/7pdk66/how_to_add_an_imdb_watchlist_in_radarr/

I need to see if doing whats noted in here 'fixes' it to make it work again in v3 (and by proxy v2)

**Comment by thezoggy** [comment]
yeah, original issue is a dupe of: https://github.com/Radarr/Radarr/issues/2330

alright, focusing on the correct way which uses radarr proxy to pull it down

created a watch list on imdb with 3 movies on it,
https://www.imdb.com/user/ur117366287/watchlist

edited and got listid, `ls099199891`.
tried to add and no luck, trying the radarr proxy url manually `https://api.radarr.video/v2/imdb/list?listId=ls099199891` also resulted in 404.
edited imdb watch list again and toggled off private. tried radarr again, still no change.

```
2020-4-26 01:36:39.7|Debug|RadarrListImport|Downloading List https://api.radarr.video/v2/imdb/list?listId=ls099199891
2020-4-26 01:36:40.1|Warn|RadarrListImport|Unable to connect to list

[v3.0.0.2878] NzbDrone.Core.MetadataSource.RadarrAPI.RadarrAPIException: Error while calling api: Not Found
Full error(s): Not Found (404, RayId: 9147f3cb-7737-4582-a9bc-a0c52c71d768), Details: not found
```

for giggles I tried  changing the default `https://api.radarr.video/v2` to `https://api.radarr.video/v2/` and magically it worked. not sure if there is some delay and thats really the root or if this somehow makes it work and then once varnish see's it then its good from that point? 
```
2020-4-26 01:54:43.8|Debug|RadarrListImport|Downloading List https://api.radarr.video/v2/imdb/list?listId=ls099199891
2020-4-26 01:54:44.3|Debug|SkyHookProxy|Not a valid date time.
2020-4-26 01:54:44.3|Debug|Api|[POST] /api/v3/netimport/test: 200.OK (520 ms)
```

tryin `https://api.radarr.video/v2/imdb/list?listId=ls099199891` myself manually works fine. so its like the proxy server is just happy now with it...

**Comment by magic-bear** [comment]
Interesting. When I add ls002728609 using the proxy, both with or without the slash it tests fine and adds fine. But if I attempt a fetch it continues to give me an error.

**Comment by Qstick** [comment]
What is the error, running fetch on that list on my v3 instance works fine (ls002728609)

**Comment by Qstick** [comment]
Fixed wording of log error, don’t see an issue with lists.
