### ISSUE TITLE
Radarr auto deleted all movies but one... and it did it again on my friend's server too

### ISSUE THREAD

**Issue by bcsteeve** [Radarr/Radarr#4361]
April 10, 2020.  Not sure why, not sure how.

I've used Radarr for years and a few months ago I got my friend set up with his own server too.  I don't actually watch a lot of movies, so I only use Radarr very sporadically, but it has always been reliable.   Until a couple of days ago when I notice all my movies are gone (except one, for some reason).  That's about 40 or 50 movies suddenly deleted.

Now, stupid me I didn't think to look for logs. I just sucked it up and re-downloaded what I wanted and I re-installed Radarr fresh since my movies were gone anyway.

Then... then today my friend says all his movies are gone (again, all but one!).  In his case, he managed to amass a lot more than me.  This time, I do get the logs.  I'm not well versed enough to know what I'm looking at, but I see a lot of unexplained deletions start to happen at 2020-4-10 13:56:26.0.

Look, I'm not trying to complain or start crap or anything, but if this happened to two of us then it should be looked at.  Since we have very similar setups - and going by the fact I'm not getting any hits when I search for people with similar recent problems - I imagine it is something fairly specific... but knowing what would be important for your guys to find out, I think.

I had to chop off some of the logs to fit it in Pastebin's limits.  I cut off everything later than 2 days after the incident.  

**Radarr Version:**
0.2.0.1480 according to the log

**Mono Version:**

5.20.1.34 currently - unfortunately I can't be sure that was the version on April 10.

**Debug Logs:**
https://pastebin.com/jFQJ8bCL

I'm mostly posting to help you avoid a big problem (if there is one), but I would like to know what happened so I can avoid it happening again.

**Comment by Qstick** [comment]
There are only 3 ways this happens

- you trigger it from UI.
- you have list cleaning enabled and it gets triggered because nothing is on a list.
- you have an instance open to internet without proper auth and someone found it.

**Comment by bcsteeve** [comment]
Well, my friend and I obviously didn't trigger it ourselves independently and out of the blue after not managing to be that stupid for months/years.  :)

I've never used the list features and I doubt he did either, but I'll doublecheck.

A hack is possible.  I didn't secure it.  So if those really are the only three possibilities, then it must be that.  However, it seems absurdly unlikely to me that he and I would both suffer the same "hack" at roughly the same time when there's nothing linking our system and we use non-standard ports.  If someone did gain entry, why would they stop at only deleting movies?  Change password, mess with setting... trigger a massive addition in case I pay by the GB for bandwidth!  There's way more mischievous things said hacker could/would do.

So thank you for highlighting my security issue (I'll get right on that), but I'd say there's a 4th possibility no matter how confident you are in your code:  bug.

**Comment by Qstick** [comment]
If it were a bug we would see a flood of reports as that’s a huge bug. We have likely north of 100k users on that release. If you can turn on debug logs and reproduce that would be a huge help, otherwise we don’t know where to even start looking.

**Comment by bcsteeve** [comment]
Fair enough.  I certainly hope I can't reproduce it, but I'll let you know.  Meanwhile, I've secured my server better in case that was it.  As I thought, no watch lists are set and the clean option is unchecked on both our servers.

If it was a hacker situation... I don't know if you want to consider more strongly suggesting auth be turned on?  I mean... my bad for not thinking about it myself, 100%... but if some rando hacker really did break into my system just to mess around, I won't be the only one (two) of your 100k users.  Anyway, I certainly hope it was a hacker because you're right - a bug that did this would suck.

Thanks for your time.

**Comment by Qstick** [comment]
There is a way to search for open instances on certain search sites, so these are pretty easy to find if a user has exposed to the web with no auth. It’s a fairly common occurrence.
