### ISSUE TITLE
Auto-blacklist samples and redownload

### ISSUE THREAD

**Issue by VirsabiMunk** [Radarr/Radarr#4365]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when [...] Radarr has the ability to identify the file being a "sample" but not auto deleting and search for new release.

**Comment by thezoggy** [comment]
set size limits?

**Comment by VirsabiMunk** [comment]
> set size limits?

Well the "fake" torrents are cheating by having short files take up a lot of space, but I'm guessing whatever method flags a file as "sample" during import can figure out (by the length of the video?) whether its a fake sample or not. Or what else flags a file as "sample"?

**Comment by Qstick** [comment]
It’s based on file runtime. Yea size limits for qualities and decent indexers will prevent grabbing in first place.
