### ISSUE TITLE
Movies deleted (again)

### ISSUE THREAD

**Issue by Renakh** [Radarr/Radarr#4367]
OS: Windows
Version:    3.0.0.2887

All movies are set to not-monitored, quality was set to any and Clean Library Level set to Disabled but it deleted all movies in the library again. (luckily I just transferred these so I had a backup from the first time it happened.)

In the log files, its parsing my downloads folder so it has a mix of TV and movies. I still don't see what is causing it to decide to delete all content. 

[radarr.txt](https://github.com/Radarr/Radarr/files/4542033/radarr.txt)
[radarr.debug.16.txt](https://github.com/Radarr/Radarr/files/4542031/radarr.debug.16.txt)
[radarr.debug.15.txt](https://github.com/Radarr/Radarr/files/4542032/radarr.debug.15.txt)
[radarr.debug.21.txt](https://github.com/Radarr/Radarr/files/4542026/radarr.debug.21.txt)
[radarr.debug.22.txt](https://github.com/Radarr/Radarr/files/4542027/radarr.debug.22.txt)
[radarr.debug.23.txt](https://github.com/Radarr/Radarr/files/4542029/radarr.debug.23.txt)
[radarr.debug.24.txt](https://github.com/Radarr/Radarr/files/4542030/radarr.debug.24.txt)

**Comment by Qstick** [comment]
The mass delete was triggered via API as shown in debug log 15.... `2020-4-26 23:06:28.6|Debug|Api|[PUT] /api/v3/movie/editor: 202 Accepted`.  Either you triggered it or someone has access to your Radarr instance

**Comment by Qstick** [comment]
Do you have debug log 14 and 13?

**Comment by Renakh** [comment]
[radarr.debug.14.txt](https://github.com/Radarr/Radarr/files/4542719/radarr.debug.14.txt)
[radarr.debug.13.txt](https://github.com/Radarr/Radarr/files/4542720/radarr.debug.13.txt)

**Comment by Qstick** [comment]
Here is where the delete finished 
`2020-4-26 23:06:42.6|Debug|Api|[DELETE] /api/v3/movie/editor: 200.OK (5157 ms)`

It was called by the UI which would confirm you or someone else with access triggered from movie editor
