### ISSUE TITLE
Max file size too small

### ISSUE THREAD

**Issue by AuXBoX** [Radarr/Radarr#437]
The step down from unlimited file size is too small.
For example Bluray-1080p steps  down from unlimited to around 11.5GB per 60mins.

could we increase that to have more control please.

**Comment by emko** [comment]
this was fixed already, please update to latest version, Bluray-1080p goes up to 27.5GB before hitting Unlimited now

**Comment by AuXBoX** [comment]
Perfect thanks. Also changed to 90mins which is better too.

**Comment by galli-leo** [comment]
Please not that I did not change any limits. That was just a cosmetic update. Radarr calculates the maximum filesize based on runtime. If you have a 180 minute movie, the maximum filesize allowed will be around 30GB

**Comment by emko** [comment]
so what your saying is those fields do nothing if we adjust them at the moment?

**Comment by galli-leo** [comment]
@emko No, they do change the filesize limit. However, it's not that the maximum is what is displayed there. That is automatically adjusted for the movie runtime. What you are changing there (behind the scenes) is the MB/minute of runtime allowed.
