### ISSUE TITLE
System Tasks - Multiple spawns of Movie Refresh

### ISSUE THREAD

**Issue by liamarmitage** [Radarr/Radarr#4372]
**Describe the bug**
Upon reviewing the system>tasks there are pages of the task "Refresh Movie" some of which have been running for hours. I have cleared these down once however within the matter of minutes, pages of this task reappear.

**To Reproduce**
1. Go to 'System'
2. Click on 'Tasks'
3. Monitor tasks / queued tasks 

**Screenshots**
Screenshot attached

**Desktop (please complete the following information):**
Docker container - Aphrodite version 3.0.0.2890 (aphrodite-134f215-833 by hotio)
Chrome Browser: Version 81.0.4044.122 (Official Build) (64-bit)
Safari Browser: Version 13.0.5 (15608.5.11)

**Debug Logs**
Turn on debug logs under Settings -> General and wait for the bug to occur again. **Upload the full log file here (or another site and link it). Issues will be closed, if they do not include this!**

<img width="1344" alt="Screenshot 2020-04-28 at 22 24 34" src="https://user-images.githubusercontent.com/12185719/80539677-d8e65300-899f-11ea-9785-c3533359f427.png">
[radarr.0.txt](https://github.com/Radarr/Radarr/files/4548624/radarr.0.txt)
[radarr.debug.0.txt](https://github.com/Radarr/Radarr/files/4548626/radarr.debug.0.txt)
[radarr.txt](https://github.com/Radarr/Radarr/files/4548627/radarr.txt)
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/4548628/radarr.debug.txt)

**Comment by liamarmitage** [comment]
So another two pages have appeared and the current job has been running for 21 hours... is there a way to kill all tasks? I have also attempted to stop the container in order to amend the interval in the DB however the container will not stop naturally.. not sure if this is related to the bug or not

**Comment by liamarmitage** [comment]
Also to add further, i have managed to clear out the tasks form the "Commands" table in the DB and now multiple Process Monitored Downloads are spawning

<img width="1362" alt="Screenshot 2020-04-29 at 14 54 01" src="https://user-images.githubusercontent.com/12185719/80604283-746fd600-8a29-11ea-8e52-598e325485bb.png">

**Comment by Qstick** [comment]
Hopefully this is fixed in latest Aphrodite

**Comment by Qstick** [comment]
Hopefully this is really fixed now here d6f15af6b6045b79bcd67746b8918b3351650837

**Comment by liamarmitage** [comment]
Hey got the same issue again in the latest version of aphrodite...

**Comment by ta264** [comment]
Please confirm version and send trace logs

**Comment by liamarmitage** [comment]
Version
3.0.0.2925
Package Version
aphrodite-98bdf86-859 by hotio

[radarr.1.txt](https://github.com/Radarr/Radarr/files/4627182/radarr.1.txt)
[radarr.0 (1).txt](https://github.com/Radarr/Radarr/files/4627183/radarr.0.1.txt)
[radarr (1).txt](https://github.com/Radarr/Radarr/files/4627184/radarr.1.txt)
