### ISSUE TITLE
high cpu usage

### ISSUE THREAD

**Issue by apcrcom** [Radarr/Radarr#4373]
**Describe the bug**

Sits around 40-60% of cpu. Appears fairly consistent last few days. not sure why. 

**Expected behavior**

Lower cpu utilisation at idle

**Desktop (please complete the following information):**

MX (Buster/Antix variant)

Version    0.2.0.1480

Mono Version    6.8.0.105

[debug.txt](https://github.com/Radarr/Radarr/files/4549144/debug.txt)

[radarr.service.txt](https://github.com/Radarr/Radarr/files/4549159/radarr.service.txt)

**Comment by Qstick** [comment]
Closing, as we are not going to be doing anything about this in v0.2. All dev is on v3

**Comment by Qstick** [comment]
Feel free to jump on Discord and someone can try and help you diagnose what maybe going on and if its something avoidable.
