### ISSUE TITLE
settings > media management > Movie Naming

### ISSUE THREAD

**Issue by thezoggy** [Radarr/Radarr#4380]
radarr 3.0.0.2899

My end goal is to have  the show `{Original.Title}\movie.ext` but doesn't look like you can do this?

* "File Name Tokens" title is used for both file+folder naming modals: Standard Movie Format + Movie Folder Format

* `{Original.Title}` token is accepted for "Movie Folder Format"  but does not actually work. (and doesn't warn that it has any issues with it)

**Comment by Qstick** [comment]
This is not bug, its intentional. Why are you using original title for the folder name?

**Comment by thezoggy** [comment]
Just how i've done it for a decades now.

I used the release name as the movie parent folder and then didnt really care what the filenames end up being. Never had any problems, work out nicely when I needed to copy stuff or view it manually in other apps without having to dig into folders to know what the actual quality/release is. Makes it really easy to gleam if I had any internal/scr/proper/etc. Now granted a lot of this doing was well before things like couchpotato/radarr and media managers in general. I could see the rational on having the 'basic' show title as the show name as your folder then would be 'static' and you can swap out stuff within it and not really mess with the folder name anymore. But anyways just was shocked to see radarr couldnt do this setup.
