### ISSUE TITLE
Movie Posters not downloading.

### ISSUE THREAD

**Issue by promo76** [Radarr/Radarr#4381]
**Describe the bug**
Movie Posters not downloading.

**Screenshots**
![image](https://user-images.githubusercontent.com/53126190/80869667-bb4f0d00-8c6f-11ea-9e07-434d8ee59ded.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Linux, Synology Docker]
 - Mono Version: [e.g. Mono 5.20.1.19] (Only needed under Linux and Mac, found under System -> Status)
 - Browser and Version [e.g. chrome] (Only needed for UI issues)
 - Version [0.2.0.1358]

**Debug Logs**
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/4568192/radarr.debug.txt)

**Comment by Qstick** [comment]
Update Radarr

**Comment by promo76** [comment]
Hello,

I tried to download the latest version from linuxserver/radarr and the latest version is [0.2.0.1358]. Here is my yaml file:

---
version: "2"
services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1024
      - PGID=101
      - TZ=America/New_York
      - VERSION=latest
    volumes:
      - /volume1/configs/Radarr:/config
      - /volume1/configs/SMP4A:/mp4automator
      - /volume1/Media/UHD Movies:/uhdmovies
      - /volume1/Media/Movies:/movies
    ports:
      - 33000:7878
      - 33001:9898
    restart: unless-stopped
