### ISSUE TITLE
preview rename - no changes

### ISSUE THREAD

**Issue by thezoggy** [Radarr/Radarr#4382]
radarr: 3.0.0.2899

I added a movie and after it downloaded and created the folder I  changed the movie folder format from `{Movie CleanTitle}` to `{Movie.CleanTitle}`. I went back to the movie and the preview rename reports back there is no changes.

**Comment by Qstick** [comment]
Rename doesn’t change the folder

**Comment by thezoggy** [comment]
well thats unfortunate due to the fact you allow options for the user. perhaps maybe add some verbiage to the modal so those in the future will know this is by design instead of an oversight ?

**Comment by Qstick** [comment]
You can change folder names by using movie editor.

**Comment by tsubus** [comment]
Would folder renaming be a feature that you'd consider implementing? It's quite useful and it's available in the "stable" (v2?) version of Radarr

**Comment by ta264** [comment]
The dynamic paths option will not be returning, it causes too much grief. Like qstick says, you can rename folders manually via movie editor
