### ISSUE TITLE
Add the possibility to assign a score to an indexer

### ISSUE THREAD

**Issue by JohnCytron** [Radarr/Radarr#4383]
## Description
I see three cases where the possibility to assign a score to an indexer can be useful:
- Privilege private tracker (known for better quality).
- With private tracker, add a better score to your best buffered tracker (where you can download the most).
- Have the possibility to prioritize indexer matching the best with your profile (asian profile with asian indexeur...)

## A solution
For me one of the most powerful way to achieved it, is to add a new condition in the custom formats on aphrodite

## Simulation
![](https://i.imgur.com/r33NxRD.jpg)
![](https://i.imgur.com/kKNxiZQ.jpg)
![](https://i.imgur.com/UoU1EcK.jpg)

I hope my suggestion interest you 😃

**Comment by austinwbest** [comment]
There is a PR on sonarr for this that is nearly completed. We would implement the upstream version instead of having 2 different versions of the same feature. I will close this but know that it will be coming, just keep track of the PR on sonarr's github for knowing when

**Comment by bakerboy448** [comment]
Sonarr PR for posterity
https://github.com/Sonarr/Sonarr/pull/3899
