### ISSUE TITLE
Add "downloadId" to the webhooks

### ISSUE THREAD

**Issue by austinwbest** [Radarr/Radarr#4384]
As mentioned in Discord, please add the downloadId to the webhook responses.

Below is the Sonarr implementation of it that markus did for me last night that, onedr0p asked to create it here with a link to the sonarr commit.
https://github.com/Sonarr/Sonarr/commit/5d9dfee3c047c6ef9c63bf4991b7c2a79a53c617

**Comment by Qstick** [comment]
cc283f64a3d95db3c6832b482b01f74c38ab9884
