### ISSUE TITLE
Error while manually importing "Unknown Movie Items"

### ISSUE THREAD

**Issue by mr-mental** [Radarr/Radarr#4388]
**Describe the bug**
When I go to the queue and activate "Show Unknown Movie Items", I can see 36 items listed there.
If I click on the manual import button, I see that the title is not found. I find it and then click on Import. It failed and then the item remains in "importing" state forever.
This is movie in rTorrent client which didn't move since I migrated from v2 to v3

**To Reproduce**
1. Have a movie named "ngt-ironman2-1080p.mkv" in a folder named "Iron.Man.2.MULTi.1080p.BluRay.x264-THENiGHTMAREiNHD"
2. Make it available in your rTorrent instance labelled for Radarr
3. Open the queue and activate "Show Unknown Movie Items"
4. See it in the list
5. Click on manual import
6. Select the good movie
7. Click on Import
8. See the error

**Expected behavior**

**Screenshots**
https://i.imgur.com/KSLjHPa.png

**Desktop (please complete the following information):**
- OS: Window 10 for UI / Synology DSM for Docker host
- Version: 3.0.0.2907
- Package Version: 3.0.0.2907-ls6 by linuxserver.io 
- .NET Core: Yes
- Docker: Yes
- DB Migration: 172
- AppData directory: /config
- Startup directory: /app/radarr/bin
- Mode: Console

**Debug Logs**
https://pastebin.com/sTVWYbvH

**Comment by Qstick** [comment]
Hopefully fixed in latest

**Comment by mr-mental** [comment]
As discussed, fixed but items which failed in the past are no stuck forever in "Importing..." status...
Any ideas to "reset" this without deleting the releases?
