### ISSUE TITLE
API returns  "Unknown Movie Items" even if unselected

### ISSUE THREAD

**Issue by mr-mental** [Radarr/Radarr#4389]
**Describe the bug**
The API returns  "Unknown Movie Items" even if unselected in the UI

**To Reproduce**
1. Call the API with  "Show Unknown Movie Items" unselected and ensure you have some
2. You will see that the API count and return it. 

**Expected behavior**
It should not.

**Desktop**
- OS: Window 10 for UI / Synology DSM for Docker host
- Version: 3.0.0.2907
- Package Version: 3.0.0.2907-ls6 by linuxserver.io
- .NET Core: Yes
- Docker: Yes
- DB Migration: 172
- AppData directory: /config
- Startup directory: /app/radarr/bin
- Mode: Console

**Comment by ta264** [comment]
As discussed on discord, you need to append query string `?includeUnknownMovieItems=false`
