### ISSUE TITLE
Created new User/User Group: Issues with Backup (Within Synology + Docker) 

### ISSUE THREAD

**Issue by madvtak** [Radarr/Radarr#439]
I went with a suggestion another user gave me to fix some issue with importing. Still having issues with that, anyways. So, since i created a new user and group. I'm getting failed backups with access denied to path. Please see setup below.

dockeruser
dockergroup

Error
![image](https://cloud.githubusercontent.com/assets/18261123/22282535/e225edee-e291-11e6-8aef-c36d088e28cd.png)

Radarr Folder
![image](https://cloud.githubusercontent.com/assets/18261123/22282606/6320e1ba-e292-11e6-995f-30e265f494d6.png)

I gave dockergroup full access

![image](https://cloud.githubusercontent.com/assets/18261123/22282579/3501c3d0-e292-11e6-8f69-6f3c38aa9e61.png)

**Comment by hotio** [comment]
It's complaining about a file located in /tmp/...So probably the docker user has no rights to the file in /tmp/...

Did you stop/start an existing container after changing the user with -u?

But what has permission problems got to do with Radarr? Seems more of a general Linux/Docker problem than an issue with Radarr.

**Comment by madvtak** [comment]
Yes, i stopped the container and then made the changes with PUID PGID. and then started the container again. Some issues resolved but then i noticed that backup failed and it was due to that path not having access.

**Comment by hotio** [comment]
And there you have it, another downside of stopping and starting containers...delete the container and create it again.

**Comment by madvtak** [comment]
So....start all over from scratch? I was trying to avoid that.

**Comment by hotio** [comment]
If you setup your container properly, it takes just about hmm 5 seconds, give or take.

**Comment by madvtak** [comment]
i might as well, i've been having a lot of issues. I'll go a head and close this.

**Comment by hotio** [comment]
See for more info https://github.com/Radarr/Radarr/wiki/Docker-container-on-Ubuntu-16.04-LTS

**Comment by madvtak** [comment]
I'm installing this in a Synology environment.

**Comment by hotio** [comment]
The basics are the same

**Comment by madvtak** [comment]
any idea how i can get to the latest version? I deleted the container and started over. I'm showing to be on Radarr Ver. 0.2.0.61, and Updates are showing up empty.

**Comment by hotio** [comment]
use docker image hotio/radarr
