### ISSUE TITLE
Sort by multiple columns

### ISSUE THREAD

**Issue by Mushin** [Radarr/Radarr#4390]
**Is your feature request related to a problem? Please describe.**
It would be very useful for organisation to be able to sort by multiple columns within the movies and movie editor views. E.g. if I was to sort by title then profile, I could scroll down and look at the titles in alphabetical order within each profile.

**Describe the solution you'd like**
Radarr should remember the previous sort column and use that as a secondary sort after the new sort for identically ranked items. I.e. similar to sorting behaviour in Excel.

**Describe alternatives you've considered**
Another option would be to provide a multi sort selection within the menu.

**Additional context**
n/a

**Comment by pbergman111** [comment]
I second this request as stated above.  I find that I'm constantly clicking the headers so resort the table one every page load. 
Also, using multiple filter criteria for listing (i.e. Show only complex results like "monitored" and "missing")

**Comment by Qstick** [comment]
We already allow multiple filter criteria in V3 @pbergman111

**Comment by masterchrister** [comment]
Also adding custom filters would be nice. Be able to sort content based on path for when you need to mass-update allot of content.

**Comment by Qstick** [comment]
Custom filters are in v3 already as well

**Comment by masterchrister** [comment]
> n

Appriciated!

**Comment by masterchrister** [comment]
> Custom filters are in v3 already as well

Appriciated!

**Comment by bakerboy448** [comment]
Closing
v0.2 is no longer being actively developed.

If this is still an issue/request on recent v3 builds, please open a new issue.

custom filters exist in v3
