### ISSUE TITLE
Download client must allow to download file(s) to folder with name consisting of a movie's title and year

### ISSUE THREAD

**Issue by attacco** [Radarr/Radarr#4392]
**Is your feature request related to a problem? Please describe.**
Radarr can't parse downloaded (using transmission) movie's file name if it's path doesn't contains year. But on the other hand, radarr chooses exactly this torrent to download, because it's release title has a year in it and actually fit to all requirements. So, the problem is that when download completes the related activity (at the 'Activity' tab) get to error state and next step (moving of downloaded file to /media/movies/) doesn't happening.

Example.
Release name is: My.Best.Movie.2020.BDRip.1080p
Radarr sending command to transmission, and it start download to that path: /media/downloads/radarr/My Best Movie.mkv
As you can see, movie's file name in torrent doesn't contains year information. So, when this file will be downloaded, it never be moved to my 'movies folder' (/media/movies) automatically. And that is sad, because all subsystem worked correctly, but the total result is failed.

**Describe the solution you'd like**
Add one more option to any of supported download clients (at least to transmission): "Create and download to folder with movie's title and year in it's name". Of course, you can name it much better :) If this option is enabled, a new folder will be created for every download, name of folder will consist of '{movie title} ({movie year})' and that will be enough for parser to determine belonging of the downloaded movie's file because it's full path now will contain all required information.

Example.
Release name is: My.Best.Movie.2020.BDRip.1080p
Radarr sening command to transmission, and it start download to that path: /media/downloads/radarr/My Best Movie (2020)/My Best Movie.mkv

**Describe alternatives you've considered**
Alternative - is somehow do not forget movie (M), that initiated a download activity (D) and when download (D) will complete, proceed from the consideration that every file downloaded during (D) is related to and only to movie (M).

**Comment by ta264** [comment]
As discussed on discord I don't think we have any appetite to disable the import parser check
