### ISSUE TITLE
Posters not showing up in "Discover New Movies - Recommendations"

### ISSUE THREAD

**Issue by eplusg** [Radarr/Radarr#4393]
**Describe the bug**
I needed to reinstall Radarr a couple of days ago and it seems like movie posters which haven't showed up before the reinstall now shows up as "blank" in "Discover New Movies - Recommendations" section.
Posters shows up if I add one movie and then open it in Radarr and they also show up if I browse the "Recommendations" section on my mobile.

"Popular" and "Upcoming" doesn't have this problem, posters show up immediately.

**To Reproduce**
1. Go to 'Add new movies'
2. Click on 'Discover New Movies'
3. Go to 'Recommendations'

**Expected behavior**
Posters should show up as they are in other sections.

**Screenshots**
![n65l1hH](https://user-images.githubusercontent.com/18008933/81045543-b203b180-8eb6-11ea-9e21-63d170aa3d12.jpg)
![8tgFppe](https://user-images.githubusercontent.com/18008933/81045551-b5973880-8eb6-11ea-9f7e-4a2ad8bfa543.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser and Version: Microsoft Edge 84.0.495.2 & Safari 13.1 (15609.1.20.111.8)
 - Radarr Version: 0.2.0.1480

**Debug Logs**
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/4579524/radarr.debug.txt)

**Comment by Qstick** [comment]
TMDb issue

**Comment by OverlordQ** [comment]
This doesn't seem to be a TMDb issue, but an issue with the Radarr API Service. 

Data returned by TMDB:

```
{
  "adult": false,
  "backdrop_path": "/gh3uqEZQp4nhkyJqkGUJSgGr6AJ.jpg",
  "belongs_to_collection": null,
  "budget": 19000000,
  "genres": [
    {
      "id": 35,
      "name": "Comedy"
    },
    {
      "id": 10749,
      "name": "Romance"
    },
    {
      "id": 18,
      "name": "Drama"
    }
  ],
  "homepage": "http://theswitch-movie.com/",
  "id": 41210,
  "imdb_id": "tt0889573",
  "original_language": "en",
  "original_title": "The Switch",
  "overview": "An unmarried 40-year-old woman turns to a turkey baster in order to become pregnant. Seven years later, she reunites with her best friend, who has been living with a secret: he replaced her preferred sperm sample with his own.",
  "popularity": 11.789,
  "poster_path": "/g0Ll7tDEiOguvG1NojvumPeWQX2.jpg",
  "production_companies": [
    {
      "id": 771,
      "logo_path": null,
      "name": "Mandate Pictures",
      "origin_country": "US"
    },
    {
      "id": 2570,
      "logo_path": null,
      "name": "Bona Fide Productions",
      "origin_country": ""
    },
    {
      "id": 7382,
      "logo_path": "/IAg148Ri1dXi0gTaxFjklCwGhT.png",
      "name": "Echo Films",
      "origin_country": "US"
    }
  ],
  "production_countries": [
    {
      "iso_3166_1": "US",
      "name": "United States of America"
    }
  ],
  "release_date": "2010-05-11",
  "revenue": 49830607,
  "runtime": 101,
  "spoken_languages": [
    {
      "iso_639_1": "en",
      "name": "English"
    }
  ],
  "status": "Released",
  "tagline": "The most unexpected comedy ever conceived.",
  "title": "The Switch",
  "video": false,
  "vote_average": 6.1,
  "vote_count": 1203
}
```

VS

Data returned by api.radarr.movie:

```
{
  "id": 41210,
  "popularity": 11.256,
  "imdb_id": "tt0889573",
  "title": "The Switch",
  "overview": "An unmarried 40-year-old woman turns to a turkey baster in order to become pregnant. Seven years later, she reunites with her best friend, who has been living with a secret: he replaced her preferred sperm sample with his own.",
  "vote_average": 6.1,
  "vote_count": 1043,
  "tagline": "The most unexpected comedy ever conceived.",
  "poster_path": "/cikOGh4sUstWitAS3BTEpXsJ1vr.jpg",
  "release_date": "2010-05-11",
  "release_year": 2010,
  "trailer_key": "EEYqgyXyk9A",
  "trailer_site": "youtube",
  "backdrop_path": "/4UnmIN6aJhUiCIw8JlQuxUJ9vzR.jpg",
  "homepage": "http://theswitch-movie.com/",
  "runtime": 101,
  "genres": [
    "35",
    "10749",
    "18"
  ],
  "adult": false
}
```

Poster Url for TMDb: https://image.tmdb.org/t/p/original/g0Ll7tDEiOguvG1NojvumPeWQX2.jpg
Poster Url for api.radarr.video https://image.tmdb.org/t/p/original/cikOGh4sUstWitAS3BTEpXsJ1vr.jpg
