### ISSUE TITLE
Tracker search failing

### ISSUE THREAD

**Issue by pegatron89** [Radarr/Radarr#4395]
**Describe the bug**
When i add any movies to Radarr i am unable to search the tracker for said movie. I just get an error message. Using the exact same details works in Sonarr. I had left it on over night and woke up this morning with 1 movie downloading. but i cant search anywhere for the movie so have no idea how radarr started downloading it. 

**To Reproduce**
Add a movie and search the Scenetime Tracker

**Expected behavior**
"No files found" - Or sometimes it will find results once then wont search again. 

**Desktop (please complete the following information):**
 - OS: Rasbian Buster
 - Mono Version:  6.8.0.105
 - Chrome - latest

**Debug Logs**
An error occurred while processing feed. http://192.168.0.33:9117/api/v2.0/indexers/scenetime/results/torznab/api?t=search&cat=2000,2010,2020,2030,2040,2045,2050,2060&extended=1&apikey=(removed)&offset=0&limit=100&q=anymovie: Torznab error detected: Jackett.Common.IndexerException: Exception (scenetime): The user is not logged in. It is possible that the cookie has expired or you made a mistake when copying it. Please check the settings.
 ---> System.Exception: The user is not logged in. It is possible that the cookie has expired or you made a mistake when copying it. Please check the settings.

I am logged in fine as i use Jackett, Which speaks to Sonarr without any issues and im using the exact same URL in both bits of software. 
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/4585638/radarr.debug.txt)

**Comment by ta264** [comment]
That's an error jackett is sending to Radarr not a Radarr issue.
