### ISSUE TITLE
Problem with differents release year

### ISSUE THREAD

**Issue by lebnet** [Radarr/Radarr#4397]
Hello,
Related to issues #1886 and #3667
Related to reddit [here](https://www.reddit.com/r/radarr/comments/asip90/release_year_causing_radarr_not_to_pull_release/) and [here](https://www.reddit.com/r/radarr/comments/fxtfp5/problem_with_differents_release_year/)

I'm in v3. After searching on several other pages, I can't find a solution.

I have an example (among others) with the movie 300. IMDB says 2006. TMDB says 2007 (so Radarr too). My indexer lists many films from my tracker with 2006 and which correspond to my profiles, custom format etc but none in 2007 so automatic grab doesn't work because it finds nothing in 2007 (radarr info).

I thought I'd found a solution with https://mappings.radarr.video but it's no longer active as far as I can see.

Do you have any suggestion ?

**Comment by rg9400** [comment]
I've been having this problem a lot recently as well with movies listed as 2020 in Radarr but with the release titles using 2019

**Comment by Qstick** [comment]
As many examples as you have the better. I’m working on something with the new api to hopefully better this.

**Comment by rg9400** [comment]
Some recent examples

How to Build a Girl (2020 on tmdb, release listed as 2019) - https://www.themoviedb.org/movie/572299-how-to-build-a-girl
Saint Frances (2020 on tmdb, release listed as 2019) - https://www.themoviedb.org/movie/576005-saint-frances
The Lodge (2020 on tmdb, release listed as 2019) - https://www.themoviedb.org/movie/474764-the-lodge
True History of the Kelly Gang (2020 on tmdb, release listed as 2019) - https://www.themoviedb.org/movie/501395-the-true-history-of-the-kelly-gang
The Whistlers (2020 on tmdb, release listed as 2019) - https://www.themoviedb.org/movie/504582-gomera

**Comment by twig123** [comment]
Issue exists in Radarr Ver. 0.2.0.1484 nightly as well.

Another example:
"The Wretched" shows as 2019 in Radarr.
TMDB Shows as 2020 - https://www.themoviedb.org/movie/605804-the-wretched
IMDB Shows as 2019 - https://www.imdb.com/title/tt8305806/

No items match because Radarr is looking for 2019, but all releases are marked 2020

**Comment by Qstick** [comment]
It's not going to get fixed on 0.2, no need to report

**Comment by revers59** [comment]
@Qstick 
L'Esprit de famille (2019) https://www.imdb.com/title/tt8699286/
L'esprit de famille ( 2020) https://www.themoviedb.org/movie/613361-l-esprit-de-famille

Les vétos (2019) https://www.imdb.com/title/tt9041586/
Les vétos (2020) https://www.themoviedb.org/movie/613348-les-vetos

**Comment by Qstick** [comment]
Is this better now? If not Radarr may not be using the secondary year as it should for parsing
