### ISSUE TITLE
{IMDb Id} is not populating in to folder

### ISSUE THREAD

**Issue by dmintz7** [Radarr/Radarr#4399]
Using aphrodite, I have a Movie Folder Format as {Movie Title} ({Release Year}) - {ImdbId} but when new movies get added the {ImdbID} is left out.

I had this issue on the previous version but solved it following https://github.com/Radarr/Radarr/issues/2086 but those options seemed to be removed in aphrodite

**Comment by Qstick** [comment]
This will be fixed soon
