### ISSUE TITLE
Allow Setting Indexer Download Priority for Same Release on Multiple Indexers

### ISSUE THREAD

**Issue by testarea1** [Radarr/Radarr#440]
Requesting indexer download priority or "score" per indexer. 

For multiple indexers that post the same release around the same time, I would prefer to give the download priority to a specific indexer in the case of the same file (like preferring the "no ratio" private tracker instead of a public one). The Couchpotato example is setting a user score per indexer so the higher score gets the download. Not sure if that can be done?

Hopefully this wasn't submitted already, I did a search and didn't find anything related like this (that was obvious so if there is I apologize).

**Comment by hotio** [comment]
http://feathub.com/Radarr/Radarr

**Comment by galli-leo** [comment]
Closing due to discussion on feathub
