### ISSUE TITLE
List removed but movies still being added

### ISSUE THREAD

**Issue by NobleWolf** [Radarr/Radarr#4400]
**Describe the bug**
I previously added the TMDb Lists "Popular", but deleted it. The movies are still being added to my wanted list. When I delete them from my wanted list they still reappear after the next sync (unless they are "Excluded".

**To Reproduce**
1. Add the list "TMDb Lists" List Type: "Popular"
2. Allow the list to sync.
3. Delete the list
3.5 I may have rebooted the machine or restarted the docker container in here somewhere.
4. Manually remove all of the newly added movies from the Wanted list

**Expected behavior**
I expect the movies to not be re-added to the Wanted list unless they are added via a currently used list or manually.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Raspbian Buster Lite v10
 - Docker: https://fleet.linuxserver.io/image?name=linuxserver/radarr v0.2.0.1480-ls60
 - Browser and Version Chrome v81

**Debug Logs**
Turn on debug logs under Settings -> General and wait for the bug to occur again. **Upload the full log file here (or another site and link it). Issues will be closed, if they do not include this!**
For the logs I:
- Added the TMDb "Popular" list
- Deleted the TMDb "Popular" list
-- I suspect the first time I added the list is still influencing my "wanted" list. I did this less than 6 days ago, as of uploading the log files.
- Deleted the movies "Ad Astra" and "All Day and a Night" and Excluded them
- Unmonitored "Arkansas" and "Avengers: Infinity War" then deleted them
- Deleted "Beyond Before" and "Bloodshot"
They were all re-added automatically. 

[radarrbugreport1.tar.gz](https://github.com/Radarr/Radarr/files/4594456/radarrbugreport1.tar.gz)

**Comment by NobleWolf** [comment]
Also, I put the List refresh at "0" minutes deleted the movies and this still occurred.

**Comment by NobleWolf** [comment]
I deleted the movies and chose to add them to the "Excluded from auto import" and they have not re-imported after a couple of hours, but they also are not showing on the "Import Exclusions" list.

**Comment by Qstick** [comment]
Closing this as I can’t reproduce, and don’t see this happening in v3
