### ISSUE TITLE
Importing a Movie finds the movie, but then shows it as missing in the movie listing

### ISSUE THREAD

**Issue by Chowarmaan** [Radarr/Radarr#4402]
**Describe the bug**
Using the Bulk import option to load existing movies, I have a movie 'The Blue Umbrella (2015)/The Blue Umbrella (2015) 1080p.mkv' in my folder.  This movie is found (BulKImport-TheBlueUmbrella.png) and named to match the folder, except for the resolution and extension.  

Once the file is then processed to be imported, the screen shows the movie as missing (TheBlueUmbrella-Missing.png). However, the files are there on the hard drive.

Looking into the Debug logs that are attached, it appears to find the movie and everything is OK.  I have waited, refreshed, scanned for the movie again, but nothing seems to change the status. If I download a new version, it will replace the file and show the movie downloaded.

**To Reproduce**
1. Go to Add Movie
2. Click on Bulk Import
3. Scroll down to the movie to import
4. Import the movie
5. Go to the movie and look at the status

**Expected behavior**
The status should show the movie is downloaded (or at least in the library and not missing). The files list should also show the movie.

**Screenshots**
BulKImport-TheBlueUmbrella.png
![BulKImport-TheBlueUmbrella](https://user-images.githubusercontent.com/175738/81424957-b6350680-9124-11ea-8146-4b96c0f59e6c.png)

TheBlueUmbrella-Missing.png
![TheBlueUmbrella-Missing](https://user-images.githubusercontent.com/175738/81424967-b9c88d80-9124-11ea-8564-be24eca7cf57.png)

**Desktop (please complete the following information):**
 - OS: Docker Image
 - Mono Version: 5.20.1.34
 - Browser and Version Chromium: Version 81.0.4044.138 (Official Build) snap (64-bit)
 - Version 0.2.0.1480

About
Version 0.2.0.1480
Mono Version 5.20.1.34
AppData directory /config
Startup directory /app/radarr/bin

**Debug Logs**
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/4600159/radarr.debug.txt)

**Comment by fryfrog** [comment]
Turn logging up to trace and refresh that movie, see what is going on. Show us that section of logs in a pastebin. And show us an `ls -alh` of that folder too.
