### ISSUE TITLE
File renaming with Torrent Source File

### ISSUE THREAD

**Issue by lebnet** [Radarr/Radarr#4406]
Hello

Related to [this topic](https://www.reddit.com/r/radarr/comments/fzmxtn/unable_to_parse_some_torrents_misnamed/)

I tried multiple tests with media management > Movie Naming but I didn't succeed to do what I exactly want to do with movie renaming.

Example with "Mune Guardian of the Moon (2015)" but I have this issue with a lot of movies (>200)

Indexer results
![img](https://preview.redd.it/dobhmi0le6x41.png?width=2982&format=png&auto=webp&s=ba8bba08c1b949eb555c39366367649906002e56)

The first one will be grab (thanks to custom format) but the file has not the same name that the torrent name
![](https://preview.redd.it/9hh8izdte6x41.png?width=1364&format=png&auto=webp&s=b5eceb2119902a44d8ea1ac541e23ff62157d470)

I want to use {Source Title} for example to automatically rename "Mune, le gardien de la lune .mkv" in "Mune, Le gardien de la Lune 2015 Bluray 1080p DTS MA VFF.mkv".

Because when the torrent is deleted from transmission, it will be grab again in the next scan because the actual filename "Mune, le gardien de la lune .mkv" doesn't match my requirements (profile + custom format).

=> If the name was "Mune, Le gardien de la Lune 2015 Bluray 1080p DTS MA VFF.mkv", then the next scan won't grab the torrent again.

Do you have any suggestion ? Develop a {Source Title} token for example ?

Initially posted [on reddit](https://www.reddit.com/r/radarr/comments/geo1wz/file_renaming_with_torrent_source_file/)

**Comment by Qstick** [comment]
Why don’t you just include quality and cfs in your naming profile.

**Comment by lebnet** [comment]
@Qstick I have already tried this in multiple ways this but it doesn't meet all my requirements because the teams have 100 different ways of renaming the torrents. 

I have already posted [on reddit](https://www.reddit.com/r/radarr/comments/geo1wz/file_renaming_with_torrent_source_file/), no answer.

In the meantime, the only solution I've found is to 
1) disable the "Automatically import completed downloads from download client" feature
2) manually rename all completed torrents with the {Source Title} by switching between the tabs of my NAS and radarr...
3) make a manual import of these files

I took the liberty of tagging it as a feature request because the purpose is to add the {Source Title} token.

So what is the best to find a solution ? ask dev to add the {Source Title} tokenn ? 
I don't think there are any workarounds until this feature is added maybe I'm wrong.

**Comment by lebnet** [comment]
Hello @Qstick :)

**Comment by lebnet** [comment]
Hello @Qstick 

it would be great if that feature ever came out. I had to hand rename another 300 movies today. And I can't change the tracker because it's the only one with so much diversity in French.

**Comment by ta264** [comment]
Is `{Original Title}` what you want?

**Comment by lebnet** [comment]
@ta264 no, if you check my screen, you will understand that with {Original Title} token, the new filename will be "Mune, le gardien de la lune .mkv" and not "Mune, Le gardien de la Lune 2015 Bluray 1080p DTS MA VFF.mkv"

**Comment by ta264** [comment]
I'm pretty sure you're describing `Original File` and `Original Title` does what you want.

**Comment by lebnet** [comment]
@ta264 I also thought like you until i tried...

my settings
![image](https://user-images.githubusercontent.com/7726777/98856085-587bd100-245d-11eb-8491-6edf391ef689.png)

my attempts.
![image](https://user-images.githubusercontent.com/7726777/98856032-44d06a80-245d-11eb-9e73-c71ad8afa94e.png)

**Comment by ta264** [comment]
Hmm a quick look suggests that `Original Title` only works if the file has a 'scene-like' name, and one of the criteria there is no spaces.

Still, I don't see what's wrong with @Qstick's suggestion to include quality and custom formats in the filename.  If the indexer has silly names that's about all you can do.

**Comment by ta264** [comment]
PS if you want to discuss this further, please join the discord.

**Comment by lebnet** [comment]
The name and the variables are too random to find a constant rule, that's why I want to use the "source file" token. This token is somewhere in the DB, so my request is to ask to implement it in the rename token list.

see you in discord :)
