### ISSUE TITLE
Custom folder naming pattern is ignored when renaming movie

### ISSUE THREAD

**Issue by soapsud90** [Radarr/Radarr#4409]
**Describe the bug**
When attempting to rename a movie which will have a new name and folder name due to the pattern being different to the imported movie, the custom folder pattern is ignored when attempting to perform the rename, but the custom movie name is adhered to.

**To Reproduce**
1. Go to Settings -> Media Management -> Movie Naming
2. Set the value of 'Movie Folder Format' to something different (that is valid) (you'll need 'advanced settings' set to 'Shown' too) 
3. Go to any movie in the library
4. Click on 'Preview rename for movie'
5. See in the preview window that the folder name will not be changed (screenshot attached)
6. Click 'Organize' and watch the renamer rename the movie as it said in the prompt, changing the movie name, but not the folder name.

**Expected behavior**
The folder name to match the pattern in the settings when performing a rename

**Screenshots**
![image](https://user-images.githubusercontent.com/15066650/81590732-31135100-93b3-11ea-8323-b2a39565d648.png)

**Desktop:**
 - OS: FreeBSD
 - Mono Version: mono-5.10.1.57_3
 - Version: 0.2.0.1450

**Debug Logs**
No logging to provide. It doesn't do it and the screen agrees with what it doesn't do!

**Comment by ta264** [comment]
You have to disable static folders in 0.2. This ability has been deliberately removed in v3.
