### ISSUE TITLE
Radarr should download movie overview in English if it's not found in profile language

### ISSUE THREAD

**Issue by krisz-gemini** [Radarr/Radarr#4412]
I use Radarr with a Hungarian profile. When I search for a movie, I can see movie overviews (synopsis) in the result list. When I add a movie to my wanted list, the overview is often empty. I realized it happened when the movie had no overview in Hungarian. It would be better if in these cases Radarr downloads the overview in English.

**Comment by Qstick** [comment]
This works in Aphrodite
