### ISSUE TITLE
Option to choose globally the language of the movies' metadata

### ISSUE THREAD

**Issue by sound-matt** [Radarr/Radarr#4419]
**Is your feature request related to a problem? Please describe.**
Radarr v3.0.0.2915
On previous versions we could choose the language of the metadata (title, description, poster) grabbed by Radarr by adding a language tag to the movie (example: "french"). Recently this feature has been removed 😢 

**Describe the solution you'd like**
That would be cool to have an option to choose globally the language of the movies' metadata in `Settings > Metadata > Options`

**Comment by Qstick** [comment]
Dupe #3497, fixed in PR #4058
