### ISSUE TITLE
Tooltips missing or not fitting

### ISSUE THREAD

**Issue by schumi2004** [Radarr/Radarr#442]
I found a few issues regarding missing tooltips and or not fitting properly.

Missing for Standard Movie Format
![tooltips](https://cloud.githubusercontent.com/assets/968545/22287063/ba3bd8ce-e2f1-11e6-865f-cb795a911799.png)

Not fitting for Movie Folder Format
![tooltip2](https://cloud.githubusercontent.com/assets/968545/22287093/d577dde0-e2f1-11e6-96e5-e68b92f07bac.png)

Missing for Remove under Completed/Failed Download Handling
Note: These are missing in Sonarr also.
![tooltip3](https://cloud.githubusercontent.com/assets/968545/22287117/e2a22656-e2f1-11e6-9bb2-44c43d303c11.png)

**Comment by hotio** [comment]
They all show up OK for me.

**Comment by schumi2004** [comment]
Your right, works perfect in IE
