### ISSUE TITLE
Unable to Connect to NZBgeek - Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by sublimesed** [Radarr/Radarr#4422]
**Describe the bug**
When attempting to connect to NZBgeek I get the following error, but this does not happen in Sonarr v3.0.3.809: _The request was aborted: Could not create SSL/TLS secure channel._

**To Reproduce**
1. Click Settings
2. Click Indexers
3. Click the '+' sign to add a new Indexer
4. Click Custom under Newznab
5. Fill out the API info for NZBgeek
6. Click Test

**Expected behavior**
Ability to connect to NZBgeek

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Win7 Pro SP1 x64
 - Mono Version: N/A
 - Browser and Version: N/A
 - Version: 0.2.0.1480

**Debug Logs**
Attached.
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/4625872/radarr.debug.txt)

**Comment by Qstick** [comment]
Discussed numerous times see #1463 #4051 or google
