### ISSUE TITLE
In manual import, the movie search field gets deselected every time new results are returned

### ISSUE THREAD

**Issue by tpspoons** [Radarr/Radarr#4427]
**Describe the bug**
Every time new results are found when searching for a film to select for a file in the "Select Movie" window during a manual import, the search field is deselected. Not a big issue, but a few times now I've accidentally gone back a page after pressing backspace in the middle of typing because I didn't notice the field was no longer selected (which can be a bit annoying when importing many films, as you'll have to start the manual import from scratch). 

**To Reproduce**
1. Go on the Movies tab, select manual import, select a directory and press next
2. In the list of files, select a the "Movie" cell for one of the files to bring up the "Select Movie" window.
3. Type one or two characters. Wait for search to finish.
4. The search field will now be deselected.
5. If you press backspace, it will go back a page instead of deleting the last character as expected.

**Expected behavior**
The search field should remain selected.

**Radarr Version**
3.0.0.2934

**Desktop:**
 - OS: Windows 10
 - Firefox 
 - Version 76.01

**Comment by Qstick** [comment]
Dupe #4297
