### ISSUE TITLE
Files view should show a checksum SHA in addition to name/size

### ISSUE THREAD

**Issue by toli** [Radarr/Radarr#4434]
Would be nice to show the checksum SHA on the file view
Use case: talking to personB about a movie, we compare sizes to see if it's the same file we downloaded, but a SHA would go much further

**Describe the solution you'd like**
showing the SHA in the "Files" view

**Describe alternatives you've considered**
download the file and run shasum manually

**Additional context**
![image](https://user-images.githubusercontent.com/34369/82084386-133e3880-96a0-11ea-9600-c2e018ae0bca.png)

would be great to see the SHA there

**Comment by Qstick** [comment]
Likely not going to happen, this would require us read the file to calculate the SHA and would likely slow things down quite a bit. Currently we only ever read around 1-2% of a file to get mediainfo... 

Just throwing it in right quick,,, here is example time for a 2gb file...
`[Info] VideoFileInfoReader: SHA256 for file: 8fOxSZHBeF1M8WRlL6czk91TDUCevq/fNSIl82cswCw=, SHA calculation took 16.0027633s`

Thats about 8 hours in just calculation time for just 2000 2gb movies.
