### ISSUE TITLE
Option Download Client

### ISSUE THREAD

**Issue by TMTYD** [Radarr/Radarr#4437]
Hi

how about the option in the movie overview if you have added a new movie that the download client can select such as rtorrent, transmission, utorrent, deluge.

I have e.g. in the Settings -> Download Client, created twice rtorrent, once with option 1080 and once with option 2160 (4k).

Now to the problem if I now e.g. want to download a 4k, I have to go into the settings and deactivate the download client for 1080, which I can get with the settings from the 4k download client.

Since I also have separate folders with 1080 and with 2160 to sort it better.

Would that be a nice option, I might also think for others.

Thx

**Comment by Qstick** [comment]
Think #2266 or #1356 are more likely solutions
