### ISSUE TITLE
No picture on function "Discovery new movies"

### ISSUE THREAD

**Issue by Alandil35** [Radarr/Radarr#4439]
**Describe the bug**
No picture on "Discovery new movies"

**To Reproduce**
1. Go to 'Add Movies'
2. Click on 'Discovery New Movies'
3. Go to 'Recommandations' or 'Popular' or 'Upcoming'

**Expected behavior**
We should see some picture by movie

**Screenshots**
![image](https://user-images.githubusercontent.com/47626482/82138640-3d1f6880-9822-11ea-81e7-b36e8cdb0774.png)

**Desktop (please complete the following information):**
 - OS: Docker Synology
 - Mono Version: 5.20.1.34
 - Browser and Version : Chrome 81.0.4044.138 (Build officiel) (64 bits) + Firefox 76.0.1 (64 bits)
 - Version : 0.2.0.1480

**Debug Logs**
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/4639835/radarr.debug.txt)

**Comment by EarthDevour** [comment]
+1 same here
0.2.0.1480 version

**Comment by eplusg** [comment]
I wrote about this earlier also, not fixed for me yet.
The report is closed but another user seem to found something in the code:
https://github.com/Radarr/Radarr/issues/4393

**Comment by Qstick** [comment]
Not going to be fixed on v0.2. this gets reworked in v3
