### ISSUE TITLE
Manually import movie -  Recycling Bin Deletes 

### ISSUE THREAD

**Issue by madvtak** [Radarr/Radarr#444]
Still having issues after a fresh install on Docker. Somethings are finally working, but not completely. Movie downloads and then sits in the Completed folder, waits to imported. 

I get these errors when it tries to import. but a folder still gets created within /Movies folder.

What does "The existing movie was not lazy loaded" even mean?

My sonarr throws the same error about access to path denied, but still movies and renames all the shows. So i was giving it the benefit of the doubt with Radarr 

![image](https://cloud.githubusercontent.com/assets/18261123/22290987/c88997c4-e2b8-11e6-854f-76758a7ba3d9.png)

When I try to do a manual import, it just deletes it a min or two later. 

![image](https://cloud.githubusercontent.com/assets/18261123/22290944/8475ea38-e2b8-11e6-8561-6e7174f6cbd1.png)

![image](https://cloud.githubusercontent.com/assets/18261123/22290950/89bb5dac-e2b8-11e6-9653-c34bad758dec.png)

**Comment by hotio** [comment]
Seems logical to me...

You are upgrading an existing movie. It removes the file before copying over the other one. Then it wants to copy over the new file, but has no access to the path which has the new file stored.

**Comment by madvtak** [comment]
This wasn't an existing movie, it was a fresh movie. I just use "Speed" as my test as its readily available. As i said, once the movie has completed the download, Radarr creates the folder and moves the movie. A few minutes later the movie gets deleted. 

Yes my volume are properly mounted or else it wouldn't have completed in the first place.

What exactly would you like me to provide to rule out Radarr bug vs user error.

**Comment by hotio** [comment]
Mostly when people have these kinds of problems it's mostly permissions related...but it's just guess work with just a couple of images. Not saying it is 100% related to permissions, but there isn't a lot of info to rule that one out, before whe can assess it's a bug.

**Comment by madvtak** [comment]
How my volumes are setup

![image](https://cloud.githubusercontent.com/assets/18261123/22324230/e9c82b72-e35c-11e6-9f2f-a96668090e67.png)

dockeruser and dockergroup have R/W access file/folder mount paths seen above. 
![image](https://cloud.githubusercontent.com/assets/18261123/22324234/f3ea41f8-e35c-11e6-9537-5cdb088633fb.png)

**Comment by hotio** [comment]
So, let's recap...

/**M**ovies is mounted as /**m**ovies and the container has rw access to the volume. (volume is not mounted as read only)

dockeruser=1031
dockergroup=65540

The docker container will read and write files as 1031:65540 to /**m**ovies.

Does the dockeruser have write access to /**M**ovies? This I don't know from the images.

**Comment by madvtak** [comment]
Does case matter in this scenario,

dockeruser has r/w in Movies. 

![image](https://cloud.githubusercontent.com/assets/18261123/22325001/09fda2ce-e361-11e6-922a-57f4b9831b4e.png)

**Comment by hotio** [comment]
Case matters on *nix

**Comment by madvtak** [comment]
I believe filesystem, I don't think i set any permissions on network shares.

**Comment by hotio** [comment]
Consider me confused, your permissions seem to be ok, however you mention Sonarr also throwing a bit of an error, so something is still of....but what....

**Comment by madvtak** [comment]
It may be an issue with Docker rather than an issue with Radarr, or hell maybe its both. In /r/Radarr, a few people are also having issues with Docker + Radarr + Synology. 

Sonarr throws the same, access to path denied but then moves everything and clears the error. The difference between Sonarr and Radarr, is that Radarr is the only one that being ran in Docker. Sonarr is working just fine and dandy as a Synology Package.

**Comment by hotio** [comment]
I'm going to guess it's synology+docker related, because on ubuntu+docker, never have I seen such an error.

**Comment by zductiv** [comment]
@madvtak are you still having these issues? I run docker / Radarr / Synology and it all seems to be running smoothly.

In your original post you showed a path of /downloads/Speed.1994..etc as the path that Radarr doesn't have permissions on, but in your volume setup in docker, it lists /downloads/Complete. Radarr thus wouldn't have permissions on /downloads/.

Try changing the volume path to /downloads/ only and see if you have better luck.

**Comment by galli-leo** [comment]
@madvtak If you still have these issues let me know and I will reopen the issue.
