### ISSUE TITLE
Original Title instead of localized displayed 

### ISSUE THREAD

**Issue by tobsen987** [Radarr/Radarr#4446]
Since yesterday Radarr pulls the original Title for all movies instead of the localized ones. This results in  e.g. Japanese names for Anime although I only have German as wanted language. The german title is not in the ‚alternative titles‘ when you hover over the sign on the movie detail page.

**To Reproduce**
Update existing movie and watch it change the title. 

**Expected behavior**
Titles should be according to language profile. 

**Platform Information (please complete the following information):**
 Version
3.0.0.2973
Package Version
3.0.0.2973-ls7 by linuxserver.io
.NET Core
Yes
Docker
Yes

**Comment by doob187** [comment]
Go back to 2912 and it will work again  
Here also a German member, all above 2912 will used US/EN titel

**Comment by Qstick** [comment]
It’s in transition, as @doob187 mentioned 2912 works if you can’t take it for a week. Thanks

**Comment by tobsen987** [comment]
I'll just wait. Just wanted to make sure you guys are aware. Thanks for letting me know it's just a matter of a week or so.

**Comment by TobiasKneidl** [comment]
Is this already fixed or should I stay at 2912?

**Comment by Qstick** [comment]
It’s fixed, though some titles are still in cache

**Comment by tobsen987** [comment]
I just refreshed a couple movies and still the original title is pulled/displayed.

**Comment by christianfds** [comment]
Also having this problem, i noticed that the alternative titles are being pulled wrong.
 
![image](https://user-images.githubusercontent.com/16166854/84143048-43bd8c00-aa2c-11ea-89e1-cd8172374bc9.png)

**Comment by Manpeas** [comment]
Same. Quality Profile language is set to English.

![Screen Shot 2020-06-14 at 7 44 05 PM](https://user-images.githubusercontent.com/26843842/84593679-91485780-ae77-11ea-9765-08e037231115.png)

**Comment by Qstick** [comment]
Post the tmdb IDs if you want them fixed

**Comment by christianfds** [comment]
> Also having this problem, i noticed that the alternative titles are being pulled wrong.
> 
> ![image](https://user-images.githubusercontent.com/16166854/84143048-43bd8c00-aa2c-11ea-89e1-cd8172374bc9.png)



> Post the tmdb IDs if you want them fixed

13398

**Comment by tobsen987** [comment]
6957, german in profile, english is pulled as metadata. 

But  frankly it‘s my whole library.

**Comment by Manpeas** [comment]
> Post the tmdb IDs if you want them fixed

Thanks for the response but I'm not altogether sure what you mean. 

Post them here? Because that would involve adding any number of IDs whenever they crop up. There must be some other solution. 

What about the option to manually select the title from the available alternate titles?

![Screen Shot 2020-06-17 at 11 59 53 PM](https://user-images.githubusercontent.com/26843842/84927207-b39bd880-b0f6-11ea-9b0f-591451300921.png)

**Comment by Manpeas** [comment]
Here's a partial list:

`42506
54690
47909
2015
8938
50247
25838
57564
14696
34019
25858
37433
35861
3780
2517
43364
3764
44162
15318
98193
52398
21967
50759
3782
86664
104452
46918
46493
31439
47060
128722
17905
20527
14572
116690
11712
187662
43618
400114
28422
30959
45713
28272
125217
20532
21058
125232
41471
36253
19884
134350
45993
10835
90351
33320
14537
68341
33431
2487
104548
44154
24166
61475
111398
27031
25538
17962
9669
38047
33319
4241
9463
11299
10686
51929
64578
12496
55197
28276
54146
11366
23606
27904
47046
30017
30020
43978
43423
593
16646
31442
9764
50183
11190
643
47795
18421

**Comment by Manpeas** [comment]
Here's a partial list of non-latin titles I've had issues with:

42506,54690,47909,2015,8938,50247,25838,57564,14696,34019,25858,37433,35861,3780,2517,43364,3764,44162,15318,98193,52398,21967,50759,3782,86664,104452,46918,46493,31439,47060,128722,17905,20527,14572,116690,11712,187662,43618,400114,28422,30959,45713,28272,125217,20532,21058,125232,41471,36253,19884,134350,45993,10835,90351,33320,14537,68341,33431,2487,104548,44154,24166,61475,111398,27031,25538,17962,9669,38047,33319,4241,9463,11299,10686,51929,64578,12496,55197,28276,54146,11366,23606,27904,47046,30017,30020,43978,43423,593,16646,31442,9764,50183,11190,643,47795,18421

**Comment by Manpeas** [comment]
Could we reopen this issue as it still persists?

**Comment by jcthorne** [comment]
I agree it still exists.  I have a great number of films in my library that display and store with the Chinese character names rather than English ones.  Radarr needs to use localized names as TMDB does.

**Comment by tobsen987** [comment]
I still have many movies where some random languages are fetched as additional english  Titles

**Comment by Qstick** [comment]
You are talking about something completely different than the original issue.

**Comment by jcthorne** [comment]
No, I am referring to the exact problem explained step by step n the very first post.  In the latest Aphrodite build it still wants to rename files using chinese titles rather than english ones.  It also displays the chinese title rather than the english one.

Please reopen this item, its still broken.  tobsen987 does sound like he is referring to something else but the original issue is still a problem.

**Comment by Qstick** [comment]
Example movie?

**Comment by Manpeas** [comment]
https://www.themoviedb.org/movie/50759-sanma-no-aji

**Comment by Manpeas** [comment]
[![IMG-0274.png](https://i.postimg.cc/1RMhgmrf/IMG-0274.png)](https://postimg.cc/Rq3byz8B)

**Comment by Manpeas** [comment]
[![IMG-0274.jpg](https://i.postimg.cc/76msL6r4/IMG-0274.jpg)](https://postimg.cc/hzQbyKGZ)

**Comment by Qstick** [comment]
Have you refreshed them? The first one you posted is correct for me.

**Comment by Manpeas** [comment]
No, that’s done the trick. I assumed updating and refreshing were the same thing. Is there anyway to perform this task without going into each film and refreshing?

**Comment by Manpeas** [comment]
https://www.themoviedb.org/movie/11712-tsubaki-sanj-r

Stubbornly refuses to refresh

**Comment by Qstick** [comment]
Let me take a look at that one, yea just run a refresh all from the main Index.

**Comment by Qstick** [comment]
Seems to work here, are you getting any sort of log errors when trying to refresh that one? Feel free to come to discord, its alot easier to discuss than back and forth on Github

![image](https://user-images.githubusercontent.com/376117/86790814-d3a82300-c036-11ea-9c78-3cbcbf052476.png)

**Comment by Manpeas** [comment]
Of course, now it's working 🤷🏻‍♂️Thank you, nonetheless. It obviously needed another pair of eyes on it before it started behaving.

No error in the log, it just wasn't grabbing the title for some reason.

[![IMG-0276.jpg](https://i.postimg.cc/ryfwKtT0/IMG-0276.jpg)](https://postimg.cc/WtJvyzhT)

I'll be sure to join the discord if something else comes up.

Thanks again for all the hard work!
