### ISSUE TITLE
[Request] Remove Duplicate Copies

### ISSUE THREAD

**Issue by zero77** [Radarr/Radarr#4447]
**Is your feature request related to a problem? Please describe.**
Before the quality profile cut off is met there are sometimes multiple copies of the same film downloaded, that take up unnecessary disk space.

**Describe the solution you'd like**
Can you please add some kind of clean up that removes the duplicate copies ideally the lower resolution copies, thanks.

**Comment by ta264** [comment]
If it's not deleting old versions it's not set up correctly

**Comment by zero77** [comment]
@ta264 
Can you explain what you mean by `old versions`.
Also, is there a wiki post on this or where can i find the settings for this, thanks.

**Comment by ta264** [comment]
Join the discord channel for support
