### ISSUE TITLE
Radarr aphrodite, no entries in Discover tab

### ISSUE THREAD

**Issue by CHINCB** [Radarr/Radarr#4448]
**Describe the bug**
Selecting the discover tab in aphrodite I get a message as follows: Unable to load movies

**To Reproduce**
1. Go to 'Discover tab'
2. Get a message as follows: Unable to load movies

**Expected behavior**
Show suggested movies under discover tab

**Screenshots**

**Platform Information (please complete the following information):**
 - OS: Unraid
 - Mono Version: [e.g. Mono 5.8] (Only needed under Linux and Mac, found under System -> Status)
 - Browser and Version [e.g. chrome, safari] (Only needed for UI issues)
 - Radarr Version 3.0.0.2973

**Debug Logs**
2020-5-21 12:06:31.5|Debug|Api|[GET] /api/v3/health: 200.OK (0 ms)
2020-5-21 12:06:31.5|Debug|Api|[PUT] /api/v3/config/host: 202.Accepted (72 ms)
2020-5-21 12:06:31.5|Debug|Api|[GET] /api/v3/health: 200.OK (0 ms)
2020-5-21 12:06:36.9|Debug|RootFolderService|Generating list of unmapped folders
2020-5-21 12:06:37.1|Debug|RootFolderService|8 unmapped folders detected.
2020-5-21 12:06:37.1|Debug|Api|[GET] /api/v3/rootFolder: 200.OK (213 ms)
2020-5-21 12:06:38.1|Debug|Api|[GET] /api/v3/movies/discover: 404.NotFound (0 ms)
2020-5-21 12:06:38.1|Debug|RootFolderService|Generating list of unmapped folders
2020-5-21 12:06:38.2|Debug|RootFolderService|8 unmapped folders detected.
2020-5-21 12:06:38.2|Debug|Api|[GET] /api/v3/rootFolder: 200.OK (175 ms)
2020-5-21 12:06:53.7|Debug|Api|[GET] /api/v3/health: 200.OK (0 ms)
2020-5-21 12:06:53.7|Debug|Api|[GET] /api/v3/system/status: 200.OK (1 ms)
2020-5-21 12:06:53.7|Debug|Api|[GET] /api/v3/diskspace: 200.OK (44 ms)
2020-5-21 12:06:55.2|Debug|Api|[GET] /api/v3/log/file: 200.OK (12 ms)

**Comment by Qstick** [comment]
Thanks, we broke it on purpose. It’s getting a makeover. Will keep this open to avoid more issues being created
