### ISSUE TITLE
webui not responding 

### ISSUE THREAD

**Issue by gbdavidx** [Radarr/Radarr#4449]
**Describe the bug**

**To Reproduce**
1. no errors, but if i create a new appdata folder everything works but database is gone 

**Expected behavior**

**Screenshots**
This site can’t be reached when trying to load webui

**Platform Information (please complete the following information):**
 - OS: docker
 - Mono Version: [e.g. Mono 5.8] (Only needed under Linux and Mac, found under System -> Status)
 - Browser and Version [e.g. chrome, safari] (Only needed for UI issues)
 - Radarr Version [current stable release]

**Debug Logs**
ErrorWarningSystemArrayLogin

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-start-container: executing...

----------------------------------------------------------------------
ENVIRONMENT
----------------------------------------------------------------------
PUID=99
PGID=100

2
TZ=America/Los_Angeles
ARGS=
DEBUG=no
----------------------------------------------------------------------

Executing usermod...
[cont-init.d] 00-start-container: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

**Comment by Qstick** [comment]
Current stable release is not a version. Please give a number. Also I'd say this is likely a support/setup issue and not a bug on Radarr side
