### ISSUE TITLE
Permission problems on Qnap 

### ISSUE THREAD

**Issue by deiniolj** [Radarr/Radarr#445]
After Radarr moves and renames a file to it's proper location I am not able to write to that folder. (Put the file through a media manager to gets artwork and NFO) I have to go into my File station and give that folder write permission.. I have tried it with and without permission setting swith within settings. Have no proplems with CP nor Sonarr..

D

Please use the search bar and make sure you are not submitting an already submitted issue.

Provide a description of the feature request or bug, the more details the better.
When possible include a log!

Please use our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by hotio** [comment]
Is Radarr writing the files with the correct User, Group? What User, Group did you set in permissions? Are you starting Radarr as the same user as your media manager? What permissions are being set? What settings did you use inside Radarr?

Just please give us some info...

This is all basic Linux stuff, which should be tried to be resolved before creating an issue...If you have confirmed that your setup is 100% OK and are sure it's a Radarr bug, then you file an issue.

**Comment by mechanimal82** [comment]
I'm running this on a QNAP and have just checked the folder permissions for renamed movies and all are ok for me. I suspect your 'Movies' folder at level above may have different permissions. Check this container folder to ensure it is ok.

To clarify on my setup I have the (for example) folder tree... 
Multimedia/Movies/The Accountant (2016)/The Accountant (2016) - BluRay 1080p.mkv

All folders in the above tree carry the same permissions. Do yours?

I also do not have the Radarr renamer set to change permissions.

What programming are you using to write to this folder? I can give it a try and see if it fails for me also.

**Comment by deiniolj** [comment]
I had radarr set to the standard 0644,0744. I had tried it with permissions on and off same problem. But after reading your post something clicked and I did some digging and found that my Movies folder was set to 777 on both.. If you don't mind me asking what are your folder permission set to on Radarr and what are your qnap folder permission, for some reason mine are all ticked.

**Comment by deiniolj** [comment]
Mean't 0755 sorry

**Comment by mechanimal82** [comment]
Odd. You are using the same permissions as me. Which QNAP are you using and what firmware?

In each movie you are adding to the Radarr watchlist is the full file path to your movies folder something like: /share/CACHEDEV1_DATA/Multimedia/... or are you using the symlink shortcut /Share/Multimedia/...?

I'm setting mine as the true full path.

**Comment by hotio** [comment]
I have no experience with a QNAP...but 644 indicates that only the owner can write, is Radarr using the correct owner/group?

**Comment by deiniolj** [comment]
I have change everything to 777 now and it seems to have work on 2 movies I downloaded.. Will keep and eye on it.  Thanks lads for the input.. Sorry admin for putting this in issue..
