### ISSUE TITLE
Parameter 'remoteMovie.Movie' can not be null

### ISSUE THREAD

**Issue by lordkitsuna** [Radarr/Radarr#4450]
**Describe the bug**
When attempting to manually trigger download of a torrent that can not be matched the error "Request Failed. POST /api/v3/release: Value can not be null. (Parameter 'remoteMovie.Movie')" is given

**To Reproduce**
1. Go to 'movies'
2. Click on 'a movie that failed to match'
3. Go to  'search'
4. Click on 'A release to download'
5. See error

**Expected behavior**
File is downloaded 

**Platform Information (please complete the following information):**
 - OS: [Linux]
 - Mono Version: 6.4.0.198-1
 - Version: 3.0.0.2285
.NET Core: Yes
DB Migration: 161

**Debug Logs**
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/4666248/radarr.debug.txt)

**Comment by ta264** [comment]
Closing this as your build is so old I'm going to assume it's fixed. Let me know if it's broken on the latest version.

**Comment by lordkitsuna** [comment]
I'm not sure if the version on the general screen is incorrect but it disagrees with the update page which says I have latest 
![Screenshot_20200521-225450](https://user-images.githubusercontent.com/3444267/82635945-47d95500-9bb6-11ea-9d51-da2983782ae5.jpg)

**Comment by ta264** [comment]
Your update branch is set incorrectly. Join the discord channel for support.
