### ISSUE TITLE
sample detection not working

### ISSUE THREAD

**Issue by hr1232** [Radarr/Radarr#4451]
All old 700/800MB CD releases are being detected as samples. They all are marked for manual processing without exception.

As those releases are full length movies, the detection obviously uses some kind of filesize comparison instead of comparing the video's length with the movie length on record.

This should not happen, because there are still a lot of cd releases out there, escpecially for older movies.

"Analyse video files" is enabled, so Radarr should extract the video length from the file.

**Radarr Version:**
3.0.0.2913 and 0.2.0.1491

**Comment by Qstick** [comment]
Fill in the entire template for bug reporting and provide logs please
