### ISSUE TITLE
Filter for filename text in movies/movie editor views

### ISSUE THREAD

**Issue by Mushin** [Radarr/Radarr#4456]
**Is your feature request related to a problem? Please describe.**
It is not currently possible to filter by downloaded quality or any specific aspects such as resolution, audio codec, HDR, release group, etc.

**Describe the solution you'd like**
Currently the path filter only searches on the movie directory. I think it would be quite useful for filtering if the filename was also included (or if another filter for file name was added). This would allow filtering on any factor included in the renaming format.

**Describe alternatives you've considered**
Either adapting the current path filter to include the filename, or adding a separate filter specifically for filename.

**Comment by bakerboy448** [comment]
no plans at this time..

various filters exist in v3
