### ISSUE TITLE
Add support for simple configuration during initial startup 

### ISSUE THREAD

**Issue by ravensorb** [Radarr/Radarr#4457]
It would be very helpful if there was an easy way to configuration radarr during initial started -- especially when used within a containerized environment (like docker).

Maybe a preference.json or a configure.json file that allowed for settings things like
- media folders
- indexers
- downloaders

[AB#847](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/847)

**Comment by doob187** [comment]
that would be awesome

**Comment by Qstick** [comment]
No plans for this right now
