### ISSUE TITLE
Radarr is auto-importing 7z files as media files.

### ISSUE THREAD

**Issue by FrancisHG** [Radarr/Radarr#4458]
**Describe the bug**
Radarr is auto-importing 7z files as media files.

**To Reproduce**
1. Auto-import movie (in my example, via auto RSS Upgrade Quality)
2. The imported movie is in 7z extension format, replacing existing media file

**Expected behavior**
Radarr should fallback to "manual import" from queue logic, so I can examine the failed auto import. Instead the auto-import processes the 7z as a media file.

**Screenshots**

**Platform Information (please complete the following information):**
 - OS: LinuxServer docker container
 - Mono Version: [e.g. Mono 5.8] (Only needed under Linux and Mac, found under System -> Status)
 - Browser and Version [e.g. chrome, safari] (Only needed for UI issues)
 - Radarr Version [e.g. 3.0.0.2956]

**Comment by ta264** [comment]
https://github.com/Radarr/Radarr/blob/70601faa4f8782684074d5f6ef0817aa68a154cd/src/NzbDrone.Core/MediaFiles/MediaFileExtensions.cs#L19

If a 7z is in your library it wasn't Radarr. If you can provide trace logs of it importing a 7z we can reopen
