### ISSUE TITLE
Folder/files naming convention 

### ISSUE THREAD

**Issue by patsaindon** [Radarr/Radarr#4464]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by patsaindon** [comment]
My current movies collection setup is the current and it works great: /movies/{year}/{movie title}/{imdbid}.ext.

I wished to use radarr as an upgrade to my current Coupotato app for future features, but the required folder/file naming convention would mean for me to change again my setup.

**Comment by Qstick** [comment]
Dupe, and support
