### ISSUE TITLE
Renaming causing files to be copied (bug in mono)

### ISSUE THREAD

**Issue by dbond007** [Radarr/Radarr#4465]
**Describe the bug**
When you rename a file or folder it will copy not rename. This is due to a bug in mono, using rclone.

**To Reproduce**
have a remote with rclone, have radarr rename a file or folder, it will copy the file / folder, not rename.

**Expected behavior**
Should just rename, not copy the whole contents.

**Platform Information (please complete the following information):**
 - OS: Ubuntu
 - Mono Version: 6.8.0.105
 - Radarr Version 0.2.0.1480

I have reported this into Sonarr and the work around has been implemented: https://github.com/Sonarr/Sonarr/issues/3681

**Comment by ta264** [comment]
Fixed in v3, not going to get done in 0.2 I don't think
