### ISSUE TITLE
Update Notification Icon for Join

### ISSUE THREAD

**Issue by judhat2** [Radarr/Radarr#447]
Thanks for gettings the notifications working!

Can the icon used for Join notifications be updated to Radarr's image?  I think the line that needs to be changed is here: https://github.com/Radarr/Radarr/blob/develop/src/NzbDrone.Core/Notifications/Join/JoinProxy.cs#L90

**Comment by hotio** [comment]
Should be good, after they merge.

**Comment by judhat2** [comment]
That was quick. Thanks!
