### ISSUE TITLE
Unable to login w/ NGINX

### ISSUE THREAD

**Issue by feerlessleadr** [Radarr/Radarr#4471]
**Describe the bug**
I decided I wanted to test radarr v3, so I spun up an instance in docker and pointed my nginx reverse proxy to the ip/port on my docker server. 

I am using the same config in NGINX that I use for sonarr v3 (as well as all of my other reverse proxied apps). 

when I navigate to my url (radarr.mydomain.com), I am presented with the login screen, but after logging in I get a page error (HTTP ERROR 400) in Brave/Chrome/Edge. 

I am able to login and navigate the v3 version when accessing locally via IP/port, but am unable to get past the login screen when using my proxy. 

When I look at my radarr logs, I see this every time I try to login and get the page error:

`2020-5-28 16:38:02.0|Info|Auth|Auth-Unauthorized ip ::ffff:192.168.1.17 url 'http://radarr.mydomain.com/favicon.ico?h=VezoKLEyl0HB1VOmV11x8Q'
`
When I google that error, it looks like it could have something to do with fail2ban or nginx authentication, but I don't have fail2ban installed on my system, and don't utilize nginx authentication. 

Here is my nginx config for radarr (this works for all other services, including radarr v2):

`##Radarr Server##
	
	server {
    listen [::]:443 ssl;
    listen 443 ssl;
    server_name radarr.mydomain.com; 
	
        ssl_session_timeout 30m;
        ssl_protocols TLSv1.2 TLSv1.1 TLSv1;
    ssl_certificate /etc/letsencrypt/live/bazarr.mydomain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/bazarr.mydomain.com/privkey.pem; # managed by Certbot
        ssl_session_cache shared:SSL:10m;
		if ($scheme = http) {
        return 301 https://$server_name$request_uri;
    }

		add_header X-Xss-Protection "1; mode=block" always;
		add_header X-Content-Type-Options "nosniff" always;
		add_header Strict-Transport-Security "max-age=2592000; includeSubdomains" always;
		add_header X-Frame-Options "SAMEORIGIN" always;
		proxy_hide_header X-Powered-By;
		add_header 'Referrer-Policy' 'no-referrer';
		add_header Content-Security-Policy "frame-ancestors mydomain.com;emby.mydomain.com;radarr.mydomain.com;sonarr.mydomain.com;get.mydomain.com;pihole.mydomain.com;hydra.mydomain.com;vault.mydomain.com;ombi.mydomain.com;bazarr.mydomain.com;port.mydomain.com;sync.mydomain.com;lidarr.mydomain.com;cameras.mydomain.com;books.mydomain.com;qbt.mydomain.com;comics.mydomain.com;jellyfin.mydomain.com;bwvault.mydomain.com;";

     location / {
        proxy_pass http://192.168.1.17:7878;  # Local emby ip and non SSL port

		proxy_hide_header X-Powered-By;
		proxy_set_header Range $http_range;
		proxy_set_header If-Range $http_if_range;
		proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        #Next three lines allow websockets
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
		location ^~ /.well-known/acme-challenge/ {
}}`

**To Reproduce**
1. Add radarr v3 to my nginx proxy
2. navigate to radarr.mydomain.com
3. login

**Expected behavior**
Should login

**Platform Information (please complete the following information):**
 - OS: Ubuntu 18.04 inside docker
 - Browser and Version: Brave Version 1.10.73 Chromium: 81.0.4044.138 (Official Build) beta (64-bit)
 - Radarr Version [e.g. 3.0.0.2956]: 3.0.0.3002

**Debug Logs**
Turn on debug logs under Settings -> General and wait for the bug to occur again. **Upload the full log file here (or another site and link it). Issues will be closed, if they do not include this!**

`2020-5-28 16:43:45.5|Debug|ProcessProvider|Found 0 processes with the name: Radarr.Console
2020-5-28 16:43:45.6|Debug|ProcessProvider|Found 1 processes with the name: Radarr
2020-5-28 16:43:45.6|Debug|ProcessProvider| - [255] Radarr
2020-5-28 16:43:45.6|Info|Router|Application mode: Interactive
2020-5-28 16:43:45.6|Debug|Router|Console selected
2020-5-28 16:43:45.7|Info|MigrationController|*** Migrating data source=/config/radarr.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
2020-5-28 16:43:45.9|Debug|MigrationController|Took: 00:00:00.2802834
2020-5-28 16:43:45.9|Info|MigrationController|*** Migrating data source=/config/logs.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
2020-5-28 16:43:45.9|Debug|MigrationController|Took: 00:00:00.0108947
2020-5-28 16:43:46.0|Info|WebHostController|Listening on the following URLs:
2020-5-28 16:43:46.0|Info|WebHostController|  http://*:7878
2020-5-28 16:43:46.0|Debug|WebHostController|Attaching SignalRMiddleware to host
2020-5-28 16:43:46.1|Debug|WebHostController|Attaching NancyMiddleware to host
2020-5-28 16:43:46.3|Info|RadarrBootstrapper|Starting Web Server
2020-5-28 16:43:47.7|Debug|QualityDefinitionService|Setting up default quality config
2020-5-28 16:43:48.1|Debug|NotificationFactory|Initializing Providers. Count 18
2020-5-28 16:43:48.1|Debug|NetImportFactory|Initializing Providers. Count 13
2020-5-28 16:43:48.1|Info|CommandExecutor|Starting 2 threads for tasks.
2020-5-28 16:43:48.3|Debug|IndexerFactory|Initializing Providers. Count 12
2020-5-28 16:43:48.3|Debug|MetadataFactory|Initializing Providers. Count 4
2020-5-28 16:43:48.3|Debug|DownloadClientFactory|Initializing Providers. Count 15
2020-5-28 16:43:52.8|Debug|Api|[GET] /api/v3/movie: 200.OK (110 ms)
2020-5-28 16:43:52.9|Debug|Api|[GET] /api/v3/command: 200.OK (107 ms)
2020-5-28 16:43:52.9|Debug|Api|[GET] /api/v3/health: 200.OK (125 ms)
2020-5-28 16:43:52.8|Debug|Api|[GET] /api/v3/queue/status: 200.OK (136 ms)`

**Comment by ta264** [comment]
https://github.com/Radarr/Radarr/wiki/FAQ#why-doesnt-aphrodite-work-behind-an-nginx-reverse-proxy

**Comment by feerlessleadr** [comment]
mother f***ker

I read through the entire wiki and somehow missed that last section in the FAQ. Thanks, that fixed it for me.
