### ISSUE TITLE
Radarr core version fails to start

### ISSUE THREAD

**Issue by Bun-Bun** [Radarr/Radarr#4475]
V3 complains "Please upgrade to the .NET Core version of Radarr"

I follow the instructions and install the core version and get the following error back from systemd

"Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true"

**To Reproduce**
1. Download latest "core" version
2. Extract it
3. Update systemd file to launch core executable instead of mono

**Expected behavior**
Radarr to start without error.

**Platform Information (please complete the following information):**
 - OS: Centos 7.6
 - Mono Version: 5.20.1.19
 - Radarr Version 3.0.0.3005

**Debug Logs**
Radarr doesn't start, thus no debug logs.

**Comment by ta264** [comment]
See net core requirements here: https://docs.microsoft.com/en-us/dotnet/core/install/dependencies?tabs=netcore31&pivots=os-linux

I'll add that link to the wiki

**Comment by Bun-Bun** [comment]
Thank you for fixing the documentation.
