### ISSUE TITLE
Search field focus loose while results are shown

### ISSUE THREAD

**Issue by mwinandy** [Radarr/Radarr#4479]
When you manually match download import, when you write the title in the search bar, the focus is loose when AJAX request is done.

**To Reproduce**

1. Get an unmatched movie
2. Try to manually match, and start to write title of the movie in the search field.
3. and you can't write after firsts results of partial search matches is displayed

**Expected behavior**
Let the focus on search field

**Platform Information**
 - OS: Chrome 83.0.4103.61 / MacOs
 - Radarr Version 3.0.0.3005

**Comment by Qstick** [comment]
I closed this because it’s fixed and a dupe

**Comment by Qstick** [comment]
Use 3008 or above

**Comment by reloxx13** [comment]
Reopen cause mouse pointer on the input is gone now which sucks if u want paste text.
