### ISSUE TITLE
Remove white space before/after Remote Path Mappings

### ISSUE THREAD

**Issue by cekt-ws2010** [Radarr/Radarr#4481]
I had the issue with my remote path mappings not working, after some trouble i found that I had a single white space at the start of the path, this lead to the mapping not being applied.

Removing empty space that has been (accidentially) added to the paths would prevent such issues in the future.

![grafik](https://user-images.githubusercontent.com/504799/83399987-6d5e2e00-a402-11ea-906a-5e71728eaa67.png)

**Comment by Qstick** [comment]
Probably not a bad idea
