### ISSUE TITLE
Imdb List doesnt update quality profile, folder, tags

### ISSUE THREAD

**Issue by cimbi01** [Radarr/Radarr#4483]
**Describe the bug**
I have movies in an imdb list. If i put the movie to another imdb list radarr doesnt update the quality profile, folder, tags based on the list settings. Both list is added to radarr lists, but have different settings for quality profile, folder, tags. After I moved movie to other imdb list i runned a NetImportSync. Movie title is "The Bucket List"

**Expected behavior**
I expect that if i move a movie from imdb list A to imdb list B then radarr update the settings of the movie based on the list B.

**Platform Information (please complete the following information):**
 - OS: Ubuntu
 - Mono Version: 6.8.0.123
 - Radarr Version: 0.2.0.1480

**Comment by Qstick** [comment]
That's not how lists work or were ever intended to work. This sounds more like a feature request than bug

**Comment by cimbi01** [comment]
Thanks for reply, than i'll write a script for frequently check for imdb list change and remove from radarr which movie is deleted or added to list.

**Comment by Qstick** [comment]
Also you don't need to post the entire log in the issue, pleeeeese use pastebin or other
