### ISSUE TITLE
radarr v3 dotnet

### ISSUE THREAD

**Issue by mradzkii** [Radarr/Radarr#4484]
**Describe the bug**
Radarr v3 complains about Dot.net core

**To Reproduce**
https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-centos7
installed .net core from here,

dotnet  --version
3.1.300

**Expected behavior**
Please upgrade to the .NET Core version of Radarr

**Platform Information (please complete the following information):**
 - OS: Centos 7
 - Mono Version:  6.8.0.123
 - Chrome
 - Radarr Version 3.0.0.3014
- DotNet Version: 3.1.300

**Debug Logs**
no errors in the log about the dotnet

**Comment by Qstick** [comment]
Did you actually install the dot net version of Radarr? Yea you installed dot net, but we distribute 2 versions of Radarr.
