### ISSUE TITLE
Please update the Linux cmd to avoid trouble

### ISSUE THREAD

**Issue by ashagg1976** [Radarr/Radarr#4485]
find . -name "*.mkv" -exec sh -c 'mkdir "${1%.*}" ; mv "${1%}" "${1%.*}" ' _ {} \;

should be

find . -maxdepth 1 -name "*.mkv" -exec sh -c 'mkdir "${1%.*}" ; mv "${1%}" "${1%.*}" ' _ {} \;

I ran it without realizing and now all my existing media are 2 folders deep ... pffff...

**Comment by fryfrog** [comment]
This looks like something you found in the wiki? If so, just edit the wiki itself instead.
