### ISSUE TITLE
Interactive movies search screen is not showing all fields

### ISSUE THREAD

**Issue by alamoudimoh** [Radarr/Radarr#4489]
when i am trying to use manual search for a movie i cannot seem to see the entire fields (it is somehow as the template is not respossinve) i need to increase the res of my screen to 4k to be able to see all fields.

here it is https://imgur.com/a/hqzFUTZ

i think it is coz some of the search results of the movie title is too long 
(Bastille.Day.2016.720p.BluRay.X264-AMIABLE Repost usenethelp.org ) [25/45] - "Bastille.Day.2016.720p.BluRay.X264-AMIABLE Repost usenethelp.org.part24.rar"

**Radarr Version:** 3.0.0.3015

**Comment by Qstick** [comment]
Dupe https://github.com/Radarr/Radarr/issues/3926
