### ISSUE TITLE
Folder name doesn't change on movie upgrade with aphrodite

### ISSUE THREAD

**Issue by kxzaon** [Radarr/Radarr#4490]
**Describe the bug**
RadarrV3(Aphrodite) >>> I downloaded a 720p movie (Red.Beard.1965.BluRay.720p.AC3.x264-***) several weeks ago inside the same name folder (Red.Beard.1965.BluRay.720p.AC3.x264-***) and I found an upgrade to 1080p with a manual search (Red.Beard.1965.1080p.BluRay.x264-***). The movie file has been replaced by the 1080p version but the folder name hasn't change and is still in the folder. (Red.Beard.1965.BluRay.720p.AC3.x264-***)

In the media management setting I set the folder name with "Original Title"

In the V2 version of radarr, the name of the folder changes with the name of the new movie file.

**To Reproduce**
1. Download an upgrade of a 720p movie to a 1080p movie
2. The movie file has been upgrade but not the folder name

**Expected behavior**
I would expect that the folder name change with the name of the new movie file name.
**Platform Information (please complete the following information):**
 - OS: Docker > Ubuntu Linux 18.04
 - Radarr Version 3.0.0.3015

**Comment by Qstick** [comment]
Not a bug, it’s intentional, you need to manually trigger folder renames now via editor. However file data in folder names isn’t recommended

**Comment by kxzaon** [comment]
After talking to @Qstick on Discord, I'm understand why this is intentional.
However I keep needing this feature so I made a little probably dirty bash script to enable this.
It works like a charm for me for a couple days so I'm posting it here.

```#!/bin/bash
###
### Custom Post-Processing script for renaming folder according to movie file name
###

### You should enable this script for "On Import" and "On Upgrade"
if [[ $radarr_eventtype == "Download" ]] ; then
        ### Replace "/movies/1080p/" by your root path
        ROOTPATHMOVIE="/movies/1080p/"
        ### Get the newly imported movie json file and retrieve the movie file name. Don't forget to replace the radarr ip and the api key.
        curl -X GET "https://radarr-ip-or-domain/api/movie/$radarr_movie_id?apikey=YOURAPIKEY" -o /tmp/temp.json
        MOVIEFILENAME=$radarr_moviefile_relativepath
        ### Add the movie filename without the extension (.mkv) to the root path in a new Env Variable
        export FOLDERNAME=$ROOTPATHMOVIE${MOVIEFILENAME:0:-4}
        ### Move the movie file to the new folder
        mv $radarr_movie_path $FOLDERNAME
        ### Edit the json file to overwriting the new path and the new folderName
        CHANGEPATH="$(jq ''.path' = $ENV.FOLDERNAME | '.folderName' = $ENV.FOLDERNAME' /tmp/temp.json)" && echo "${CHANGEPATH}" > /tmp/temp.json
        ### Send back the json file to the radarr database. Don't forget to replace the radarr ip and the api key
        curl -X PUT -H "Content-Type: application/json" --data @/tmp/temp.json "https://radarr-ip-or-domain/api/movie/$radarr_movie_id?apikey=YOURAPIKEY"
fi
```
