### ISSUE TITLE
Search returning Inconsistent results - Jackett 

### ISSUE THREAD

**Issue by mattstrayer** [Radarr/Radarr#4496]
**Describe the bug**
Jackett Searches are inconsistently returning different results. Sometimes when I visit a movie and open the search tab, it will return extremely quickly and only return a limited result set (normally YTS releases). Other times I will visit and click search and it will return results from all indexers. Refreshing the movie page a few times will eventually let me see all indexer results. 

**To Reproduce**

1. Have Jackett installed with multiple trackers `/api/v2.0/indexers/all/results/torznab`
2. Go to movie
3. Click search
4. See results
5. Repeat multiple times for different results to show.

**Expected behavior**
Expect consistent results from all trackers on jackett. 

**Screenshots**

**Platform Information (please complete the following information):**
 - OS: Docker:preview (host Ubuntu 20)
 - Radarr Version 3.0.0.3024

**Debug Logs**
[radarr_log.txt](https://github.com/Radarr/Radarr/files/4737425/radarr_log.txt)

**Comment by ta264** [comment]
This will be a jackett issue i think. The `all` endpoint is best avoided.
