### ISSUE TITLE
Some downloads sent to download clients but not showing in the queue

### ISSUE THREAD

**Issue by kingdavid52** [Radarr/Radarr#4505]
**Some downloads sent to download clients but not showing in the queue**.

Some downloads get sent to my download clients (Deluge and NZBGet) but they never show up in the **Queue** under **Activity**. It doesn't happen to all of the downloads, but I notice it happens more often when downloading multiple movies at the same time.

**To Reproduce**
1. Try to download multiple/different movies so you end up with multiple movies in the queue.
2. Go to your queue under activity and compare the amount of downloads with the ones on your download client.

**Expected behavior**
All downloads sent to the download clients should show up in the queue under activity.

**Platform Information (please complete the following information):**
 - OS: Ubuntu 18.0.4
 - Mono Version: 6.8.0.123
 - Radarr Version: 0.2.0.1480

**Debug Logs**
[Radarr Logs.txt](https://github.com/Radarr/Radarr/files/4753919/Radarr.Logs.txt)

**Comment by Qstick** [comment]
These are likely releases that can’t be parsed or differ from original grab name. In v3 you can show these via Show unknown movies option.

**Comment by kingdavid52** [comment]
Ok, thank you.
