### ISSUE TITLE
Don't download Russian movies automatically

### ISSUE THREAD

**Issue by nikiie8** [Radarr/Radarr#4507]
Hi All
I struggle to make Radarr to download automatically movies from Russian torrent trackers.
I have a profile with Russian language inside. Parser Leniency - strict
Radarr finds a lot torrents but doesn't download them due to an error "Failed to map movie" as in most Russian trackers has the following name of a movie [Russian name]/ or ,[English name] [year] [other details]. The parser cannot recognize any sign between [Russian name] and [English name]
I have changed Parser Leniency to Lenient Mapping as it was suggest here.
But right now I faced another error. If a torrent name doesn't have a word RUS, I see an error " Russian is wanted but found English", although the movie has Russian name. 

As an interim solution I can change language to English in a profile and click "Strip Russian letters" in Jackett. But in this case I will not be able even to find Russian movies which doesn't have English name in Russian trackers. 

**Platform Information (please complete the following information):**
 - OS: Debian 10
 - Mono Version: 6.8.0.123
 - Radarr Version: 0.2.0.1480

Please fix

**Comment by Qstick** [comment]
Overed by #3748 #3747

**Comment by sisaenkov** [comment]
I workarouned "Russian is wanted but found English" by migrating to radarr 3.0.0.3186 (preview):
Settings -> Indexers -> Edit Russian tracker indexer -> Multi Languages -> specify "Any"

But there is no "Parser Leniency" option in Indexers, so I often get "Failed to map movie" again.
