### ISSUE TITLE
Movie Editor - Maintain all Columns from View Page

### ISSUE THREAD

**Issue by adamNewell** [Radarr/Radarr#451]
As a user, I want to be able to edit my list of movies and mark unmonitored all movies that have met my quality cutoff. In order to do that, I want to see the same columns on the /movieeditor page as I do on the index page

**Comment by mcroach** [comment]
+1

I do this as well so minimize the number of monitored items once I'm happy with the content.

**Comment by onedr0p** [comment]
Downloaded column was added to the movie editor a few days ago. Should be sufficient until a new UI comes around.
