### ISSUE TITLE
Pasting a specific move title in the search bar causes the page to go blank

### ISSUE THREAD

**Issue by Fringe09** [Radarr/Radarr#4510]
**Describe the bug**
I have the movie "Aurora Teagarden Mysteries: A Game of Cat and Mouse" in Radarr. When I attempt to search for it using the search bar on top of the page, I get a blank page.

**To Reproduce**
1. Launch Radarr v3.0.0.x
2. Add the movie `Aurora Teagarden Mysteries: A Game of Cat and Mouse`
3. Click on Movies to see all Movies
4. Copy `Aurora Teagarden Mysteries: A Game of Cat and Mouse` so it's in memory
4. Paste `Aurora Teagarden Mysteries: A Game of Cat and Mouse` in the search bar on top of the page
5. Blank page will show up

**Expected behavior**
Movie should show up in the search result(s)

**Platform Information (please complete the following information):**
 - OS: macOS Catalina 10.15.5
 - Mono Version: n/a (running in Docker)
 - Browser and Version: Microsoft Edge 83.0.478.45
 - Radarr Version: 3.0.0.3054

**Console Log**
[console_log.txt](https://github.com/Radarr/Radarr/files/4761508/console_log.txt)

**Comment by Qstick** [comment]
fixed 9c3b4e3025db6ccebbafbcd5a72ff1b4f8968feb
