### ISSUE TITLE
ConnectFailure for RadarrLists

### ISSUE THREAD

**Issue by cbude** [Radarr/Radarr#4514]
**Describe the bug**
Imdb lists are not working. Getting Connection Refused from https://api.radarr.video/v2/
Does not matter which type of imdblist I choose 

I've tried using backups and also redownloading all dependencies.

**To Reproduce**
1. Go to Settings->Lists
2. Click add list (plus sign)
3. Click Preset on Radarr Lists, choose any of imdb preset.
4. Click test
5. Error text "Unable to connect to list, check the log for more details" appears

**Expected behavior**
List should collect new movies from desired list.

**Platform Information (please complete the following information):**
 - OS: Ubuntu 18.04
 - Mono Version: 6.8.0.123
 - Radarr Version: 0.2.0.1480

**Debug Logs**
https://pastebin.com/raw/AfDzWTRn

**Comment by Qstick** [comment]
Working fine here

**Comment by cbude** [comment]
Works for me now as well after being down for 1 ½ week.
