### ISSUE TITLE
qBittorrent's Share Ratio Limit is not boolean, and only "remove" options should result in error condition for Radarr

### ISSUE THREAD

**Issue by craSH** [Radarr/Radarr#4515]
https://github.com/Radarr/Radarr/blob/8bbec88b6fe88b89a229bb09bfa00525b3806de8/src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentPreferences.cs#L12

qBittorrent currently supports 4 options for what to do once a torrent reaches its max ratio. It is currently impossible to have it set to "Enable super seeding for torrent" when adding/testing qBittorrent to Radarr. This setting should not impact Radarr's ability to manage the download.

**Comment by Qstick** [comment]
Closing due to you blitzing the template, Follow the template and we can open back up if this is legit

**Comment by craSH** [comment]
Sorry, I clicked the report issue link from the source code line number and it didn’t include it in the new issue template. Will recreate!
