### ISSUE TITLE
Discover: Unable to load movies (404)

### ISSUE THREAD

**Issue by michaelwijnands-zuyd** [Radarr/Radarr#4519]
**Describe the bug**
When opening the Discover page it shows a message "unable to load movies". When I check the console I see:
```
[signalR] starting
[signalR] Information: Normalizing '/signalr/messages?access_token=(removed)' to 'https://domain.nl/signalr/messages?access_token=(removed)'.
**GET https://domain.nl/api/v3/movies/discover 404   trycatch.js:131**
[signalR] Information: WebSocket connected to wss://domain.nl/signalr/messages?access_token=(removed)&id={ID}.
[signalR] Information: Using HubProtocol 'json'.
```

**To Reproduce**
1. Go to Discover
2. See error

**Expected behavior**
Expected a list of movies I haven't seen yet.

**Platform Information (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser and Version: Chrome 83.0.4103.97
 - Radarr Version: 3.0.0.3055

**Debug Logs**
Turn on debug logs under Settings -> General and wait for the bug to occur again. **Upload the full log file here (or another site and link it). Issues will be closed, if they do not include this!**
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/4776832/radarr.debug.txt)

**Comment by Qstick** [comment]
Dupe #4448 and fixed in Pr #4504
