### ISSUE TITLE
Add MediaInfo tag for "Resolution"

### ISSUE THREAD

**Issue by GordonSmith** [Radarr/Radarr#4520]
**Is your feature request related to a problem? Please describe.**
It appears that Radarr is able to extract and display the video resolution directly from the video file.   This feature would make that information available to the renamer.

**Describe the solution you'd like**
The following additional rename tags:
* MediaInfo.Resolution.x
* MediaInfo.Resolution.y

**Describe alternatives you've considered**
The use of an external tool to extract that information.

**Additional context**
![image](https://user-images.githubusercontent.com/966863/84659212-f7cc8480-af0e-11ea-98b6-7ce906eace74.png)

**Comment by Qstick** [comment]
What’s the use case here?

**Comment by GordonSmith** [comment]
To use in the bulk rename feature.  Most of the media info is available as a "tag" already, but this seems to be an omission.

Specific use case - I have a folder with duplicate movies at different resolutions (correct meta, but silly names) - I would like to organise by "y resolution".  Example:
* Video001.mkv -> Star Crash-320p  
* Video001b -> Star Crash-720p

**Comment by Qstick** [comment]
Why not just use the quality rename tag that already exists?

**Comment by GordonSmith** [comment]
That tag only exists if it was part of the name when the file was downloaded (and could be wrong) - which is obviously a chicken/egg scenario - in this case that tag does not exist for the above example...

**Comment by Qstick** [comment]
The quality tag is the quality of the file you have. Your use case is a bit confusing `I have a folder with duplicate movies at different resolutions`. Are you saying you have two copies of the same movie in different resolutions? In which case, use the quality tag with a nested folder. (However, Radarr doesn't support multiple copies so it won't handle the naming anyway). 

Anyway, Don't think we are going to do this right now, jump on discord if you want some help with your setup to ensure there is no conflict between any files.
