### ISSUE TITLE
Add Navigation Links for Related Tools

### ISSUE THREAD

**Issue by drowse7en** [Radarr/Radarr#4524]
Is it possible to add links to 'arr' tools by creating a 'Tools' menu in the left sidebar, with submenus pointing to related tools (Plex, Sonarr, Lidarr, Bazarr, etc.) so that users can easily circumnavigate their related tools?

![image](https://user-images.githubusercontent.com/4270365/84969845-8136af00-b0e7-11ea-9170-45d353c5fb89.png)

**Comment by Qstick** [comment]
This is why organizr exists.
