### ISSUE TITLE
Status of move is different between Table view and viewing it individually

### ISSUE THREAD

**Issue by Fringe09** [Radarr/Radarr#4526]
**Describe the bug**
I have several movies where the status is different between table view and viewing it individually. I have attached two screenshots.

**To Reproduce**
1. Launch Radarr v3
2. Add and download the movie `Hailey Dean Mysteries: Killer Sentence`
3. Go back to the home page and change the view to Table
4. Movie will have a blue status, which means Unreleased
5. Click on the movie to go into the individual view and status will be green, which means "Downloaded and Monitored"

**Expected behavior**
Status should be the same in both places

**Screenshots**
<img width="172" alt="radarr_status_poster" src="https://user-images.githubusercontent.com/4276475/85045796-53338800-b144-11ea-9cd1-a7d7ea3aa82b.png">

<img width="1198" alt="radarr_status_detail" src="https://user-images.githubusercontent.com/4276475/85045819-5e86b380-b144-11ea-8ad2-817b3cd54097.png">

**Platform Information (please complete the following information):**
OS: macOS Catalina 10.15.5
Mono Version: n/a (running in Docker)
Browser and Version: Microsoft Edge 83.0.478.50
Radarr Version: 3.0.0.3065

**Debug Logs**
I don't believe logs are needed for this specific bug as it is a visual one.

**Comment by Qstick** [comment]
Thanks, this is a know issue, just need time to fix it.
