### ISSUE TITLE
SceneName not always imported

### ISSUE THREAD

**Issue by jaredhobbz** [Radarr/Radarr#4528]
**Describe the bug**
After a recent update, I've noticed that the SceneName is not always imported into the database for some downloads after the completed download is handled and the movie is imported.

**To Reproduce**
The issue only occurs for some downloads. Other downloads work fine.

When importing "The.Big.Chill.1983.1080p.BluRay.H264.AAC-RARBG" the SceneName is imported.

However, when importing "The Personal History of David Copperfield 2019 1080p BluRay x265 HEVC 10bit AAC 5 1 Tigole QxR" and many others the SceneName is not imported. The field is null in the database.

**Expected behavior**
SceneName should always be imported when a completed download is handled.

**Platform Information (please complete the following information):**
 - OS: Ubuntu 20.04
 - Radarr Version: 3.0.0.3065

**Comment by ta264** [comment]
I believe a scene name cannot have spaces in it

**Comment by jaredhobbz** [comment]
I don’t think that is the issue unless this was a recent change? I’m looking at the MovieFiles table in the db and there are thousands of other scene names in there with spaces.

A Scanner Darkly 2006 (1080p Bluray x265 HEVC 10bit AAC 5.1 Tigole)
A Simple Plan 1998 (1080p Bluray x265 HEVC 10bit AAC 5.1 Tigole)
A Quiet Place (2018) (1080p BluRay x265 HEVC 10bit AAC 7.1 Tigole)

**Comment by ta264** [comment]
https://github.com/Radarr/Radarr/blob/57961df1df73fd8bcfc504ceae94174f00ee0e9a/src/NzbDrone.Core/Parser/SceneChecker.cs#L19

Yes it is the issue, spaces are not allowed in scene names.  This was changed in 40b630ef100aab9bc5409ec22760d4883f739777 - before then scene standards were not enforced.

**Comment by jaredhobbz** [comment]
Thank you for the reply and the help. I suppose I will need to roll back the version I am using then. Is it possible to request that this space requirement be removed or request that there be some sort of setting for enabling/disabling strict scene names? I am using a lot of Custom Formats to prefer QxR, UTR, TAoE, and SEV releases. These seem to all have spaces in them and not having the sources stored in the db will dramatically limit the usefulness of this program for me since I won't know where any of the files came from.
