### ISSUE TITLE
Custom Formats no longer work for releases with spaces in them. Check original file path.

### ISSUE THREAD

**Issue by jaredhobbz** [Radarr/Radarr#4529]
**Is your feature request related to a problem? Please describe.**
Please see issue #4528. Due to changes in 40b630e, scene names must now not contain any spaces or else null is stored in the database. Since no scene name is stored in the database, it is impossible to know where these downloads originated from.

**Describe the solution you'd like**
Create a setting for enabling/disabling strict scene names. If disabled, scene names with spaces or without periods should be stored in the database like they used to be.

Alternatively, remove the requirement that spaces not be in scene names and make periods optional as well.

**Describe alternatives you've considered**
Revert to a version prior to 40b630e.

Edit:
Instead of allowing scene names with spaces in them, custom formats should check the original file path in addition to the scene name and the relative path.

**Comment by ta264** [comment]
IMO scene names should be only scene names.  If you can point to any documentation to suggest that these are valid scene names then we can fix the checker.

If your real issue is with custom formats then I think perhaps the correct fix is to check custom formats against the original file name (which is stored in the database and will always be present, unlike scene name)

**Comment by JBou** [comment]
@ta264 The line of code referenced in your comment on the other issue https://github.com/Radarr/Radarr/issues/4528#issuecomment-646730034 is the problem, but it has not been introduced in my commit https://github.com/Radarr/Radarr/commit/40b630ef100aab9bc5409ec22760d4883f739777. I only changed the return type of the method, we made some changes there. But the white space check has already been there before, it has been introduced in https://github.com/Radarr/Radarr/commit/20287f84cee8dda33a877ffc01b9498e5a0c5810.

**Comment by ta264** [comment]
I disagree @JBou, prior to your commit I think it would return the filename as the scene name if the parser could parse the name
https://github.com/Radarr/Radarr/commit/40b630ef100aab9bc5409ec22760d4883f739777#diff-28db5f60c55a9a5be58138d7b4c1e608L215-L223

**Comment by ta264** [comment]
(Not that I think what you have done is wrong, but I think that explains the timeline)

**Comment by jaredhobbz** [comment]
Thank you for your reply @JBou. There are literally thousands of scene names in my database with spaces in them. Is this unusual? The last scene name with spaces in it was imported on 06/15. The same day I ran an update (I was like 4-5 updates behind at the time).

@ta264 for custom formats, I am checking everything against the release title. I was under the impression that this would check the scene name and the relative path for regex matches. Is there a way to check the original file path instead? This field is still being populated while the scene name is not.

**Comment by JBou** [comment]
Oh, you are right @ta264. This lines of code have been introduced by me.
Haven't even realized that when commiting it... Prior to my commit it used the downloadClientItem.Title as SceneName if it successfully parsed a movie, but didn't go trough SceneChecker methods, this has changed with my commit and brings up this issue.

But I think my changes are correct, calling the SceneChecker for the downloadClientItem is a good thing. If we want to support spaces we have to change the SceneChecker.GetSceneTitle and remove the [conditional which checks for spaces](https://github.com/Radarr/Radarr/commit/40b630ef100aab9bc5409ec22760d4883f739777#diff-b636ba0cba2b6ec2754ccc20b1a5fa79R19) IMO.

**Comment by ta264** [comment]
@jaredhobbz you can't make it check original file name currently, but I wonder if that is the correct fix for the behaviour that led you to open this issue. I don't think marking things as scene when they are not is the correct solution.

If release title custom formats checked original title also would you be content?

@JBou I agree your change is good, just wanted to make sure I understood the timeline

**Comment by jaredhobbz** [comment]
That sounds logical @ta264. If it checked the original title in addition to the scene name and the relative path, my issue would be resolved.

**Comment by ta264** [comment]
@jaredhobbz I've just made an untested PR to fix this. Please can you help test? Ping me on the discord channel for instructions.

**Comment by Qstick** [comment]
Confirmed working?

**Comment by ta264** [comment]
We're working on testing now

**Comment by jaredhobbz** [comment]
This fixed all of my issues. Thank you again @ta264!
