### ISSUE TITLE
Delete folder from source

### ISSUE THREAD

**Issue by jpborjas** [Radarr/Radarr#453]
This is an enhancement request. When SABnzbd finishes downloading a movie, it puts it in a folder. When Radarr moves that movie its final destination, it should remove the folder, but it isn't.

**Comment by onedr0p** [comment]
I think this is a SAB setting? Clean up files after download or something?

**Comment by jpborjas** [comment]
I'm new to Radarr. It works fine in Couch Potato, no additional PP scripts. SAB doesn't do it, but I don't think it is supposed to.

**Comment by jpborjas** [comment]
Couch Potato does it using this Renamer Setting: Cleanup leftover files after successful rename.
Can you guys add that? I checked SAB and I don't think it can do it. Other people here have added stand-alone scripts. I would like it to be automatic.

**Comment by onedr0p** [comment]
I see, please open this on our FeatHub http://feathub.com/Radarr/Radarr we will get to it in time :)
