### ISSUE TITLE
Codesign main and update executable for macOS

### ISSUE THREAD

**Issue by aniqueta** [Radarr/Radarr#4535]
**Describe the bug**
Each time Radarr opens on macOS Catalina, the user must manually allow incoming network connections. Allowing does not persist, even though Radarr is listed in the macOS firewall system settings as allowing incoming connections. This hinders remote and headless operation, especially for updates.

**To Reproduce**
1. Enable macOS firewall in System Preferences
2. Start Radarr
3. Allow incoming network connections per macOS firewall prompt
4. Shutdown Radarr
5. Restart Radarr
6. See request to allow incoming network connections again

**Expected behavior**
Allowing incoming network connections should only need to be done once

**Screenshots**
![screen](https://user-images.githubusercontent.com/65845439/85236735-5d1fea00-b3d5-11ea-97b7-76713c0bd70a.png)

**Platform Information**
 - OS: macOS Catalina 10.15.5
 - Mono Version: Not shown in System -> Status; instead notes .NET Core Yes
 - Radarr Version: 3.0.0.3071

**Debug Logs**
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/4810398/radarr.debug.txt)

[AB#852](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/852)

**Comment by Qstick** [comment]
I think we would need to sign the executable for this to go away on every run (at least from what I've read about it from Apple). @ta264 any thoughts here?

**Comment by bakerboy448** [comment]
bumping @ta264

**Comment by Smultie** [comment]
This is still an issue.
Sonarr did fix it.

**Comment by bakerboy448** [comment]
@Smultie any chance you know roughly what sonarr version fixed it? or better yet the commit?

**Comment by Smultie** [comment]
I'm sorry, I very recently switched to macOS and noticed Sonarr not having the network connections popup while Radarr does.

**Comment by ItchyData** [comment]
This is still happening with big sur 11.4 and the latest 3.2.2 version of Radar. 
<img width="372" alt="Screen Shot 2021-05-30 at 10 24 01 AM" src="https://user-images.githubusercontent.com/76266146/120802952-04c3f880-c511-11eb-8ce2-bd45dfaa5143.png">
Not sure if it's related, but in addition to the incoming requests prompt, I also get repeated requests for access to the Downloads folder and External Volumes, even though these are allowed for Radarr in the security preferences. This happens upon restart of the system. 
<img width="372" alt="Screen Shot 2021-05-30 at 10 24 34 AM" src="https://user-images.githubusercontent.com/76266146/120802980-0b527000-c511-11eb-94d1-1323c80cc0a7.png">
<img width="372" alt="Screen Shot 2021-05-30 at 10 27 31 AM" src="https://user-images.githubusercontent.com/76266146/120802992-0e4d6080-c511-11eb-87a7-e7400179b96e.png">

**Comment by alexclaydon** [comment]
I'm also having this issue.

**Comment by lexpostma** [comment]
Still an issue in version 4.0.0.5738

**Comment by ta264** [comment]
Unlikely to happen unless someone contributes a fix or donates some macos hardware...

**Comment by ta264** [comment]
Looks like this may be fixed by self signing the application?

https://apple.stackexchange.com/questions/3271/how-to-get-rid-of-firewall-accept-incoming-connections-dialog

We have no plans to jump through all the hoops apple requires to get it "officially" signed.

**Comment by lexpostma** [comment]
This workaround worked indeed:

```sudo codesign --force --deep --sign - /Applications/Radarr.app ```

Now I just hope I can still easily update Radarr when there's new releases. I'll find out and report back. Thanks!

**Comment by aliriddle** [comment]
/Applications/Radarr.app: resource fork, Finder information, or similar detritus not allowed


Im getting this error when I run the command. Any advice?

**Comment by bakerboy448** [comment]
> /Applications/Radarr.app: resource fork, Finder information, or similar detritus not allowed
> 
> 
> 
> 
> 
> Im getting this error when I run the command. Any advice?


Please use one of the support channels: [Reddit](https://www.reddit.com/r/radarr/) or  [Discord](https://radarr.video/discord) for support/questions.

Note that given so few run macs, you're very much on your own for support unfortunately as no one knows Apples security fun.

**Comment by Superspin3** [comment]
I was having the same issue, but then I resolved it by adding this entry.

_sudo codesign --force --deep --sign - /Applications/Radarr.app/Contents/MacOS/Radarr_

You should see the following response.
_replacing existing signature._

Job done! No more of this nonsense..
![85236735-5d1fea00-b3d5-11ea-97b7-76713c0bd70a](https://user-images.githubusercontent.com/111464476/185244750-b02cb17f-cb4b-40aa-8738-077efb0a79f2.png)

**Comment by Smultie** [comment]
Not working here on Monterey

**Comment by Superspin3** [comment]
> Not working here on Monterey

Sorry I should have mentioned, I'm still on Mojave.

**Comment by Smultie** [comment]
Not a problem at all, good find! However I think Apple prevented this
option in later versions of their OS

**Comment by alexreg** [comment]
Any chance of signing the app in future releases? Even self-signed would be a significant improvement for AMD Macs!

**Comment by bakerboy448** [comment]
As Ta mentioned - users can / are instructed to self-sign on their end.

**Comment by thezak48** [comment]
The issue being is one of us will have to publicly have our personal information and Gov ID tied to the arr apps, which we are not willing/wanting to do for obvious reasons.

**Comment by alexreg** [comment]
@thezak48 Yeah, that's fair enough. But what about creating your own *rr certificate authority and using that to create the signing certificate? It's not ideal, but at least then users can just to choose manually trust your certificate authority.

**Comment by bakerboy448** [comment]
No plans to properly sign with a PII linked Apple dev account

**Comment by aniqueta** [comment]
@bakerboy448 Makes sense. Could we have a better path that current state for automated updates on macOS, per https://github.com/Radarr/Radarr/issues/8181? Current state is to update using manual re-installation. I'm not sure what the options would be though. Is there a way to script `sudo codesign --force --deep --sign - /Applications/Radarr.app`? Probably not, since it requires `sudo` but just checking.

**Comment by bakerboy448** [comment]
Again, Servarr team has no plans to link their PII to Apple to facilitate signing the installer and updater.

As previously stated, users will need to self-sign the app due to Mac's Security posture

**Comment by aniqueta** [comment]
Yes, I understood. I was just asking if there are other ways to auto update, without an Apple dev account (linked to PII) and without `sudo codesign`. It sounds like the answer is no.

**Comment by aniqueta** [comment]
On macOS, Docker has a CPU, memory, and storage performance cost. It's a trade-off to use macOS for sure.
