### ISSUE TITLE
Can’t update from 0.2.0.1496 nightly

### ISSUE THREAD

**Issue by Speaktomenow** [Radarr/Radarr#4536]
**Description:**

**Radarr Version:** .1496 nightly 

**Mono Version:** 6.8.0.123

**Debug Logs:**

# Do not remove anything from your logs and post the full logs! If not everything fits in here use a service like https://pastebin.com to upload them.

**Comment by Speaktomenow** [comment]
Not a major issue, updates to .1498 keep failing from the nightly build. I’m stuck at 1496 and keep getting “update failed” errors.

**Comment by ta264** [comment]
Please check the discord for support, if you can produce logs to indicate a bug we can reopen (with a report that follows the template!)

**Comment by Qstick** [comment]
Reopen per bug found from discord discussion
