### ISSUE TITLE
Let us "replace" a movie that was already in the DB while bulk importing

### ISSUE THREAD

**Issue by Kedryn** [Radarr/Radarr#4537]
**Is your feature request related to a problem? Please describe.**
When we do some renaming/moving of movies already in the DB, then do a bulk import, all movies with the new names are found, but we are unable to add them because they already exists in the Database. Then we have go to old movies one by one and either edit their properties (file path) or delete them and rescan again.

**Describe the solution you'd like**
have a button on each movie already found, to REPLACE it in the database

**Describe alternatives you've considered**
have another checkbox enabled to replace while adding for movies already present

**Comment by ta264** [comment]
In v3 you can get radarr to rename the folders for already mapped movies so this isn't needed I don't think

**Comment by Kedryn** [comment]
> In v3 you can get radarr to rename the folders for already mapped movies so this isn't needed I don't think

Uhm, i'm using v3 now, and besides the fact that when i delete a movie in Radarr in one page, if i have a list of movies to import in another page, it get's refreshed and the movie i deleted gets the checkbox for import enabled, there is still no way to batch import already existing movies without deleting every single movie by hand before importing.

**Comment by ta264** [comment]
I think if you're trying to batch import existing movies you're doing something wrong. Join the discord and we can try to put you right

**Comment by Kedryn** [comment]
I'll join discord, but, to explain better, i have a large movie library that sometimes needs some rearrangement. Multiple root folders, some folders renaming and so on...
For example i had some collections (all Rambo movies, for example), that were nested under a movie root, that was fine for every other program i used (Plex, MCM, and many others) but it's not fine for Radarr. I started adding all collection's subfolders by hand as anothe root, but there were too many so i'm now moving movies out of the subfolder by hand (have to do in my local and cloud  backup storage). So, when i'm rescanning the root folder, Radarr find all those movies again, and i have no way to let it import them other than deleting them in the DB one by one. Thats what i'm doing right now. I understand that when you have a not-so-large library, it's easier to use the Radarr interface to move folders, but in my case i find it quicker doing it my way. But it can be a lot quicker if i don't have to delete every single movie before reimporting.

Let's meet on discord to see if there is a better way to to that.
Anyway, V3 is a HUGE improvement over V2.
