### ISSUE TITLE
Filters/search when mass editing movies

### ISSUE THREAD

**Issue by Kedryn** [Radarr/Radarr#4538]
**Is your feature request related to a problem? Please describe.**
When we are going to mass edit some movies, there is no way to search for them. So it's so hard to do some editing when you have like 3k+ movies

**Describe the solution you'd like**
Implement filters, or at least a search inside the list in the mass editor, to filter those shown (not redoing a search, but to shows client-side only those containing a word in the name or the path)

**Comment by ta264** [comment]
this is done in v3
