### ISSUE TITLE
Can't update qualityProfileId for movie via API

### ISSUE THREAD

**Issue by jtrott** [Radarr/Radarr#4539]
**Description:**

I am using PHP to update movie information in Radarr, specifically changing the currently set qualityProfileId (4) to a different qualityProfileId (3). I get a 202.Accepted return code from radarr and no errors are in the logs, but the value for the movie is not changed. I can test and set the "monitored" value to false without issues using the same code. 
I am doing a get, converting the JSON into an array, modifying the array, converting back to JSON, then using a curl PUT to write the changes. Works with "monitored", doesn't work with "qualityProfileId".

**Radarr Version:**

0.2.0.1480

**Mono Version:**

5.20.1.34

**Debug Logs:**

2020-6-23 13:29:01.1|Debug|Api|[GET] /api/movie/4846?apikey=(removed) 200.OK (100 ms)
2020-6-23 13:29:10.1|Debug|Api|[PUT] /api/movie/4846?apikey=(removed) 202.Accepted (8993 ms)

**Comment by ta264** [comment]
Best way is to watch the frontend do it via chrome dev tools network tab. It definitely works since the frontend uses the API.

**Comment by ta264** [comment]
Hmm support bot seems to be missing in action, please join the discord channel for support

**Comment by jtrott** [comment]
Looks like when you want to update "monitored" you can just get then put, when you want to update qualityProfileId, you need to also get the profilelist and return that with your put. I've moved to instead use sqlite queries, much easier and saves 10 seconds per action.
