### ISSUE TITLE
newznab requests use wrong url

### ISSUE THREAD

**Issue by pixxon** [Radarr/Radarr#4541]
**Describe the bug**
When the movie title contains a forward flash, it gets truncated which results in no search results from the indexer.
( Instead of A/B it becomes AB, which yields no search results )

**To Reproduce**
0. Add Jackett as indexer proxying over nyaa.si
1. Movies/Add New
2. Add Fate/Stay Night: Heaven's Feel II. Lost Butterfly
3. Search the indexers for release
4. See no results are found ( or very few )

**Expected behavior**
Radarr should be able to find releases from the indexers.

**Platform Information (please complete the following information):**
 - OS: Ubuntu 20.04 LTS (GNU/Linux 5.4.0-29-generic x86_64)
   - Using Docker version 19.03.8, build afacb8b7f0
   - Running linuxserver/radarr
 - Radarr Version 3.0.0.2911

**Debug Logs**
```
2020-6-24 13:42:54.4|Info|NzbSearchService|Searching 2 indexers for [Fate/Stay Night: Heaven's Feel II. Lost Butterfly]
2020-6-24 13:42:54.4|Debug|Torznab|Downloading Feed http://jackett:9117/api/v2.0/indexers/rarbg/results/torznab/api?t=movie&cat=100052,100051,100050,2045,2040&extended=1&apikey=(removed)&offset=0&limit=100&imdbid=8091892
2020-6-24 13:42:54.4|Trace|HttpClient|Req: [GET] http://jackett:9117/api/v2.0/indexers/rarbg/results/torznab/api?t=movie&cat=100052,100051,100050,2045,2040&extended=1&apikey=(removed)&offset=0&limit=100&imdbid=8091892
2020-6-24 13:42:54.4|Debug|Torznab|Downloading Feed http://jackett:9117/api/v2.0/indexers/nyaasi/results/torznab/api?t=search&cat=2020,5000,5070&extended=1&apikey=(removed)&offset=0&limit=100&q=fatestay%20night%20heaven%20s%20feel%20ii%20lost%20butterfly%202019
2020-6-24 13:42:54.4|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2020-6-24 13:42:54.4|Trace|RateLimitService|Rate Limit triggered, delaying 'jackett' for 1.999 sec
2020-6-24 13:42:54.6|Trace|HttpClient|Res: [GET] http://jackett:9117/api/v2.0/indexers/rarbg/results/torznab/api?t=movie&cat=100052,100051,100050,2045,2040&extended=1&apikey=(removed)&offset=0&limit=100&imdbid=8091892: 200.OK (182 ms)
2020-6-24 13:42:56.4|Trace|HttpClient|Req: [GET] http://jackett:9117/api/v2.0/indexers/nyaasi/results/torznab/api?t=search&cat=2020,5000,5070&extended=1&apikey=(removed)&offset=0&limit=100&q=fatestay%20night%20heaven%20s%20feel%20ii%20lost%20butterfly%202019
2020-6-24 13:42:56.4|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2020-6-24 13:42:56.6|Trace|HttpClient|Res: [GET] http://jackett:9117/api/v2.0/indexers/nyaasi/results/torznab/api?t=search&cat=2020,5000,5070&extended=1&apikey=(removed)&offset=0&limit=100&q=fatestay%20night%20heaven%20s%20feel%20ii%20lost%20butterfly%202019: 200.OK (250 ms)
2020-6-24 13:42:56.6|Debug|NzbSearchService|Total of 0 reports were found for [Fate/Stay Night: Heaven's Feel II. Lost Butterfly] from 2 indexers
2020-6-24 13:42:56.6|Info|DownloadDecisionMaker|No results found
```

**Comment by pixxon** [comment]
Additional info from Discord:

Both `NewznabRssParser` and `NewznabRequestGenerator` uses `Parser.Parser.NormalizeTitle`, which replaces special characters with empty.

**Comment by pixxon** [comment]
Also Sonarr uses the following: https://github.com/Sonarr/Sonarr/blob/phantom-develop/src/NzbDrone.Core/Indexers/Newznab/NewznabRequestGenerator.cs#L374

**Comment by fullmetal1** [comment]
I get the same issue with this movie. Looks like the issue is that the '/' is removed instead of being converted into a space.

**Comment by fullmetal1** [comment]
I quick fix would probably be to change 
```title = DuplicateSpacesRegex.Replace(title, " ");
title = SpecialCharRegex.Replace(title, string.Empty);```
to
```title = SpecialCharRegex.Replace(title, " ");
title = DuplicateSpacesRegex.Replace(title, " ");
```
I don't know why you'd want to get rid of special characters completely, and afterwords. Currently, special characters are &, :, \ and / and I can't think of any situation where erasing them is more beneficial than replacing them with spaces, especially when ' is considered a 'word delimiter', and replaced with a space

**Comment by ta264** [comment]
This is how it needs to be done for most usenet indexers. Radarr / Sonarr was originally usenet only, this probably needs separating out to an indexer or at least protocol specific routine.

**Comment by Qstick** [comment]
Can't reproduce this behavior, I think this was fixed at some point by replacing / with %20 instead of just dropping it
