### ISSUE TITLE
Radarr bombing /radarr/signalr/connect url

### ISSUE THREAD

**Issue by glensc** [Radarr/Radarr#4543]
I've set up my radarr to be served under `/radarr` with proxy in front.

But this configuration is not liked and the web interface bombs `/radarr/signalr/connect` several times in a second if looking at browser network console. The same error happens with sonarr, as apparently the use same codebase (forks).

The functionality does not seem to be broken. but sometimes it says connection failed, click reload, and **that** is annoying.

it should not flood the network with requests if it failed, it should at least throttle the retries, perhaps exponentially increasing delay until giving up after max attempts or time limit.

![image](https://user-images.githubusercontent.com/199095/85768069-4f45ce00-b721-11ea-88ba-031c2211820a.png)

**Comment by ta264** [comment]
Version?

This configuration definitely works (I use it myself)

**Comment by fryfrog** [comment]
You sure you've got websockets going properly? I'm doing this in nginx w/o issue too.

**Comment by ta264** [comment]
I'm going to go ahead and mark this as support and close. Discord is the best place to get assistance with setup issues.

**Comment by glensc** [comment]
radarr version is latest (of course).

I'm using lighttpd as a proxy, so might be WebSockets is not proxied correctly. thanks for the hint.

**Comment by glensc** [comment]
however, the application should be still fixed to add rate limiting, not bombing like this forever.

**Comment by ta264** [comment]
Latest is not a version (of course)

The frontend isn't very functional without a signalr connection (it won't update correctly) so we don't have any plans to change it, especially if you're on 0.2 which I suspect

**Comment by glensc** [comment]
I'm using latest stable from https://hub.docker.com/r/linuxserver/radarr/

- Version 0.2.0.1480
- Mono Version - 5.20.1.34

And I still disagree that bombing network and making CPU hurt is correct behavior, the problem will not be solved with retrying if the problem is with WebSocket packets being unusable. should not retry with 400 error I suppose. 

I can still reload the page and do most of the actions even without the signalr, it's only a minor annoyance to me that if I forget tab open with sonarr, ventilators on laptop start to vent at full power and I have to find the sonarr tab that I forgot open. I tried to block "signalr/connect" URLs in browser developer console, but chrome seems to forget them at some point.

**Comment by ta264** [comment]
I suspect that this works better in v3 (0.2 is end of life and vary major big fixes only, V3 approaching beta).  It's not going to get fixed in 0.2

If you want to stick on 0.2 the best approach is probably to figure out why your reverse proxy is broken.

**Comment by glensc** [comment]
Don't know where the websocket mention come from, but radar itself responds with an error:


```
curl 'https://censored.freemyip.com/radarr/signalr/connect?transport=longPolling&connectionToken=*censored*%*censored*%*censored*%*censored*%censored%*censored*%censored%*censored*%*censored*%2FRS%*censored*%*censored*%*censored*&apiKey=*censored*&tid=10&_=1593199378100' \
  -H 'Connection: keep-alive' \
  -H 'Pragma: no-cache' \
  -H 'Cache-Control: no-cache' \
  -H 'Authorization: Basic *censored*' \
  -H 'Accept: application/json, text/javascript, */*; q=0.01' \
  -H 'DNT: 1' \
  -H 'X-Requested-With: XMLHttpRequest' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36' \
  -H 'X-Api-Key: *censored*' \
  -H 'Content-Type: application/json; charset=UTF-8' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Referer: https://*censored*.freemyip.com/radarr/' \
  -H 'Accept-Language: en-US,en;q=0.9,es-ES;q=0.8,es;q=0.7,et;q=0.6' \
  -H 'Cookie: _pk_id.1.*censored*=*censored*.*censored*.; HYDRA-XSRF-TOKEN=*censored*-*censored*-*censored*-*censored*-*censored*; *censored*=*censored*.*censored*-*censored*-*censored*' \
  --compressed -i
```

responds with:
```
X-ApplicationVersion: 0.2.0.1480
X-Content-Type-Options: nosniff
Server: Mono-HTTPAPI/1.0
Date: Fri, 26 Jun 2020 19:29:23 GMT
Strict-Transport-Security: max-age=63072000
Content-Length: 45

The connection id is in the incorrect format.
```

**Comment by ta264** [comment]
Join the discord and we can try to figure it out

**Comment by glensc** [comment]
Switched to `linuxserver/radarr:preview` docker image.

> radarr     | [Info] Bootstrap: Starting Radarr - /app/radarr/bin/Radarr.dll - Version 3.0.0.3088

so far looks good in browser console:


```
[signalR] starting
SignalRConnector.js:78 [signalR] Information: Normalizing '/radarr/signalr/messages?access_token=(removed)' to 'https://*censored*.freemyip.com/radarr/signalr/messages?access_token=(removed)'.
SignalRConnector.js:78 [signalR] Information: WebSocket connected to wss://*censored*.freemyip.com/radarr/signalr/messages?access_token=(removed)&id=bT5OtAkrhR_NOL0spL9L3g.
SignalRConnector.js:78 [signalR] Information: Using HubProtocol 'json'.
```

so, this problem is solved for me after switching to v3 (radarr:preview)

tbh, the versioning is super confusing in this project:
1. github recent releases have only 0.2: https://github.com/Radarr/Radarr/releases
2. in git tags I see v2.0 from some years ago, no tags for v3 (see screenshot below)
2. docker image linuxserver/radarr:latest is 0.2
3. the download section in readme mentions only symbolic names, develop (stable), nightly (semi-unstable), aphrodite (very-unstable), but here you speak in versions (v0.2, v3): https://github.com/Radarr/Radarr#downloads


![image](https://user-images.githubusercontent.com/199095/85904710-19ccdd80-b812-11ea-8cc1-0b0bbdd1fba1.png)
