### ISSUE TITLE
Cannot bulk import from root folder if fetching unmapped folders takes more then 5 seconds.

### ISSUE THREAD

**Issue by Shakeandbake** [Radarr/Radarr#4548]
**Describe the bug**
When the import page loads, it calls RootFolderService.AllWithUnmappedFolders()
This method iterates over all rootFolders and calls RootFolderService.GetDetails() to populate the RootFolder models with details about the unmapped folders. This method performs this inside of a separate task with a timeout of 5 seconds. If it takes longer than 5 seconds to fetch the available space, total size and unmapped folders, the method will complete without waiting for the tasks to finished populating the model. The result is the UI receives json missing these properties which blocks import functionality.

A workaround for users encountering this issue is to create multiple dummy rootFolders to delay the RootFolderService.AllWithUnmappedFolders() method from completing before the GetDetails task for the non dummy rootFolder completes. Each dummy rootFolder will delay this a further 5 seconds. 

I have included logs to that showcase a configuration with 2 root folders. Issued at 17:15:54.8, the request incorrectly completes exactly 10 seconds later (5 seconds times 2) but the RootFolderService debug message about how many unmapped folders were detected did not complete until 5 and a half seconds later. 

**To Reproduce**
1. Configure a rootFolder for a mount which has many files and folders.
2. Click on import
3. When the page loads, observe that the unmapped folders column displays "-" rather then a number for the root folder.
4. Select the root folder and immediately be presented with a screen declaring that all folders have been imported.

**Expected behavior**
The UI should correctly show the number of unmapped folders and allow importing.

**Platform Information (please complete the following information):**
 - docker aphrodite-89e582f-999 by hotio on unraid (slack)
 - Radarr Version: 3.0.0.3088

**Debug Logs**
2020-6-27 17:15:54.8|Trace|Http|Req: 315 [GET] /api/v3/rootFolder (from ::ffff:10.88.111.6 Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Mobile Safari/537.36)
2020-6-27 17:15:54.9|Debug|RootFolderService|Generating list of unmapped folders
2020-6-27 17:15:59.9|Debug|RootFolderService|Generating list of unmapped folders
2020-6-27 17:16:04.8|Trace|Http|Res: 315 [GET] /api/v3/rootFolder: 200.OK (10006 ms)
2020-6-27 17:16:04.8|Debug|Api|[GET] /api/v3/rootFolder: 200.OK (10006 ms)
2020-6-27 17:16:07.2|Debug|RootFolderService|145 unmapped folders detected.
2020-6-27 17:16:09.3|Debug|RootFolderService|1 unmapped folders detected.
2020-6-27 17:16:13.5|Trace|Scheduler|Pending Tasks: 0

**Comment by Qstick** [comment]
This might take care of it https://github.com/Sonarr/Sonarr/commit/11cdf1314853151373c7c07e8f0329c28596a80c

I'll pull it in a bit

**Comment by Qstick** [comment]
Try 3.0.0.3094 when its finished building
