### ISSUE TITLE
Health Check gives false positive error

### ISSUE THREAD

**Issue by lukjod** [Radarr/Radarr#4549]
I got message You are using docker; download client QTransmission places downloads in /share/CACHEDEV1_DATA/Download/transmission/completed but this directory does not appear to exist inside the container. Review your remote path mappings and container volume settings.

My download folder is set on docker as 
-v /share/CACHEDEV1_DATA/Download/transmission/radarr/completed:/downloads \

it is also set in transmission configuration on advanced settings as 

Directory /share/CACHEDEV1_DATA/Download/transmission/radarr/completed

and also set in port mappings as

Host 192.168.1.197
Remote Path /share/CACHEDEV1_DATA/Download/transmission/radarr/completed
Local Path /downloads

All is working fine, Radarr sends movie to transmission and after sucesfull download grabs it from download directory.

Can be this meesagge removed somehow or its my wrong configuration.

QTransmission 3.0 installed as qpkg file on x64 qnap 251+

![Adnotacja 2020-06-28 210041](https://user-images.githubusercontent.com/1781446/85956005-b615f200-b982-11ea-9928-3e354d0738aa.jpg)
![Adnotacja 2020-06-28 210042](https://user-images.githubusercontent.com/1781446/85956007-b6ae8880-b982-11ea-9bb0-1981b136707d.jpg)
![Adnotacja 2020-06-28 210043](https://user-images.githubusercontent.com/1781446/85956008-b6ae8880-b982-11ea-93aa-3afd1cba1689.jpg)
Version
    3.0.0.3092
Package Version
    3.0.0.3092-ls12 by linuxserver.io 
.NET Core
    Yes
Docker
    Yes
DB Migration
    176
AppData directory
    /config
Startup directory
    /app/radarr/bin

**Comment by ta264** [comment]
Please can you join the discord channel so we can debug?

**Comment by fryfrog** [comment]
This turned out to be due to the Directory setting, @ta264 is going to work up a fix in the test.

**Comment by ta264** [comment]
Should be fixed

**Comment by lukjod** [comment]
thx, its fixed
