### ISSUE TITLE
Ramdom update folder radarrv3

### ISSUE THREAD

**Issue by gwenvador** [Radarr/Radarr#4555]
**Is your feature request related to a problem? Please describe.**
I am using a shared seedbox with the temp folder (/tmp/radarr_update) being owned by another user. So I cannot proceed with the built-in upgrade of radarr.

**Describe the solution you'd like**
We should be able to choose the location/name of the folder for the upgrade, use a random tag on the folder and/or clean the folder once upgraded.  

**Additional context**
A ticker with same idea was opened here (but closed because not following the template) https://github.com/Radarr/Radarr/issues/4272

**Comment by ta264** [comment]
You should start Radarr with environment variable `TMPDIR` set so that it provides a temporary directory that Radarr can actually use.
