### ISSUE TITLE
(Create empty series folders + Delete empty folders) possible problem?

### ISSUE THREAD

**Issue by Jorman** [Radarr/Radarr#4556]
Hi, I'm on
Radarr -> 3.0.0.3095
.NET Core -> Yes
DB Migration -> 176

Hi, maybe this's not a bug and this's the normal behavior.
For me is pretty strange this, I'll try to explain what happen:
If I activate both options
![image](https://user-images.githubusercontent.com/5203988/86047632-7537df00-ba4f-11ea-8bf9-b5d099a2177c.png)
The result is that a day or so (I think after a regular disk scan) I find all the movie folder about that are not yet released and obviously there's nothing inside.
So for example let say that Avatar 5 (2025) is monitored (and it's) so, for never forget I leave it monitored, lol!
So, after a while, I'll find Avatar 5 folder under the root folder structure.

Seems that the _**Delete empty folders**_ option was executed before the _**Create empty series folders**_ option, in that way Radarr Delete empty folder before, then create again the empty folder.

What do you think?

I don't have any log, let me know if you need any extra procedure to make a log for you, if needed.

Thanks, Jo

**Comment by ta264** [comment]
It's a bug in that you shouldn't be able to select both options, it should be an either/or I think

**Comment by Qstick** [comment]
@Jorman what did they decide on the Sonarr bug you filed?

**Comment by Jorman** [comment]
@Qstick 
Like you already know, this's a "common" bug for Sonarr/Radarr, and maybe all the *arr app that you can find out there.
I opened this so can be trackable.
On Sonarr side Marcus said that is not so important, just don't enable both options.

I don't know what's the original scope of this advanced functions, maybe like you said, only one at time have to be enabled.
I'm not a programmer, in my logic the purpose of this 2 options can be:
* If the movie is monitored and the folder is missing -> create it
* If the folder is empty -> delete it
Quite convenient if the folder was accidentally removed/deleted, actually if I remember correctly the downloaded movie stuck because the folder is missing.
Also convenient because empty folder make only confusion at first look.
Maybe, like I said, these 2 options runs in a reversed order inside the code, maybe the original purpose was to be enabled one at time and not both at the same time

It's only my opinion. I agree that is not a problematic bug, only one that one day will be fixed.

What do you think about it?

J

**Comment by Qstick** [comment]
I agree with you and @ta264, easy thing would be to ensure they can't be selected at same time.

**Comment by Qstick** [comment]
https://github.com/Radarr/Radarr/commit/027a388157e07b437fcc027e2350efba1314d9f5
