### ISSUE TITLE
Constant start loop bug

### ISSUE THREAD

**Issue by MiTvSpain** [Radarr/Radarr#4557]
Hello, since yesterday afternoon, I have had radar in a constant initiation loop, it does not allow me to access the application, it only loads the user and pass, and it remains on the logo screen with the balls loading. How do I fix this bug ?, I have updated services with apt update and apt upgrade without solution thanks

Version: 0.2.0.1480

Mono Version: 6.8.0.123
Ubuntu 18

Request Failed: The DataMapper was unable to load the following field: 'Quality' value: '{ "quality": 6, "customFormats": [ 1, 4 ], "revision": { "version": 1, "real": 0 } }'. The given key '1' was not present in the dictionary.
ExceptionMarr.Data.DataMappingException: The DataMapper was unable to load the following field: 'Quality' value: '{ "quality": 6, "customFormats": [ 1, 4 ], "revision": { "version": 1, "real": 0 } }'. The given key '1' was not present in the dictionary. ---> System.Collections.Generic.KeyNotFoundException: The given key '1' was not present in the dictionary. at System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) [0x0001e] in <a17fa1457c5d44f2885ac746c1764ea5>:0 at NzbDrone.Core.Datastore.Converters.CustomFormatIntConverter.ReadJson (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Object existingValue, Newtonsoft.Json.JsonSerializer serializer) [0x00027] in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\Converters\CustomFormatIntConverter.cs:83 at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable (Newtonsoft.Json.JsonConverter converter, Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Object existingValue) [0x00055] in <1fa899c21f554672afbc630cc93b185e>:0 at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList (System.Collections.IList list, Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonArrayContract contract, Newtonsoft.Json.Serialization.JsonProperty containerProperty, System.String id) [0x0016f] in <1fa899c21f554672afbc630cc93b185e>:0 at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, System.Object existingValue, System.String id) [0x001be] in <1fa899c21f554672afbc630cc93b185e>:0 at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) [0x0007f] in <1fa899c21f554672afbc630cc93b185e>:0 at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue (Newtonsoft.Json.Serialization.JsonProperty property, Newtonsoft.Json.JsonConverter propertyConverter, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty, Newtonsoft.Json.JsonReader reader, System.Object target) [0x00061] in <1fa899c21f554672afbc630cc93b185e>:0 at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject (System.Object newObject, Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonObjectContract contract, Newtonsoft.Json.Serialization.JsonProperty member, System.String id) [0x00267] in <1fa899c21f554672afbc630cc93b185e>:0 at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) [0x0015c] in <1fa899c21f554672afbc630cc93b185e>:0 at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) [0x0006d] in <1fa899c21f554672afbc630cc93b185e>:0 at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Boolean checkAdditionalContent) [0x000d9] in <1fa899c21f554672afbc630cc93b185e>:0 at Newtonsoft.Json.JsonSerializer.DeserializeInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00053] in <1fa899c21f554672afbc630cc93b185e>:0 at Newtonsoft.Json.JsonSerializer.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType) [0x00000] in <1fa899c21f554672afbc630cc93b185e>:0 at Newtonsoft.Json.JsonConvert.DeserializeObject (System.String value, System.Type type, Newtonsoft.Json.JsonSerializerSettings settings) [0x0002d] in <1fa899c21f554672afbc630cc93b185e>:0 at NzbDrone.Core.Datastore.Converters.EmbeddedDocumentConverter.FromDB (Marr.Data.Converters.ConverterContext context) [0x00029] in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\Converters\EmbeddedDocumentConverter.cs:47 at Marr.Data.Mapping.MappingHelper.LoadExistingEntity (Marr.Data.Mapping.ColumnMapCollection mappings, System.Data.Common.DbDataReader reader, System.Object ent, System.Boolean useAltName) [0x00061] in C:\projects\radarr-usby1\src\Marr.Data\Mapping\MappingHelper.cs:66 --- End of inner exception stack trace --- at Marr.Data.Mapping.MappingHelper.LoadExistingEntity (Marr.Data.Mapping.ColumnMapCollection mappings, System.Data.Common.DbDataReader reader, System.Object ent, System.Boolean useAltName) [0x000a8] in C:\projects\radarr-usby1\src\Marr.Data\Mapping\MappingHelper.cs:79 at Marr.Data.Mapping.MappingHelper.CreateAndLoadEntity (System.Type entityType, Marr.Data.Mapping.ColumnMapCollection mappings, System.Data.Common.DbDataReader reader, System.Boolean useAltName) [0x00012] in C:\projects\radarr-usby1\src\Marr.Data\Mapping\MappingHelper.cs:40 at Marr.Data.DataMapper.QueryToGraph[T] (System.String sql, Marr.Data.EntityGraph graph, System.Collections.Generic.List`1[T] childrenToLoad) [0x00087] in C:\projects\radarr-usby1\src\Marr.Data\DataMapper.cs:646 at Marr.Data.QGen.QueryBuilder`1[T].ToList () [0x00028] in C:\projects\radarr-usby1\src\Marr.Data\QGen\QueryBuilder.cs:275 at NzbDrone.Core.Datastore.BasicRepository`1+<>c[TModel].<All>b__6_0 (Marr.Data.QGen.QueryBuilder`1[T] q) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\BasicRepository.cs:76 at NzbDrone.Core.Datastore.BasicRepository`1[TModel].Query[T] (System.Func`2[T,TResult] finalizeQuery) [0x00014] in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\BasicRepository.cs:62 at NzbDrone.Core.Datastore.BasicRepository`1[TModel].All () [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Core\Datastore\BasicRepository.cs:76 at NzbDrone.Core.Movies.MovieService.GetAllMovies () [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Core\Movies\MovieService.cs:316 at NzbDrone.Core.DiskSpace.DiskSpaceService.GetMovieFreeSpace () [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Core\DiskSpace\DiskSpaceService.cs:48 at NzbDrone.Core.DiskSpace.DiskSpaceService.GetFreeSpace () [0x00005] in C:\projects\radarr-usby1\src\NzbDrone.Core\DiskSpace\DiskSpaceService.cs:39 at NzbDrone.Api.DiskSpace.DiskSpaceModule.GetFreeSpace () [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Api\DiskSpace\DiskSpaceModule.cs:20 at NzbDrone.Api.REST.RestModule`1[TResource].<set_GetResourceAll>b__32_0 (System.Object options) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Api\REST\RestModule.cs:111 at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object) at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, System.Threading.CancellationToken context) [0x00049] in <63c44d6f8d7e4f339a987bf9eb94d931>:0

![image](https://user-images.githubusercontent.com/30379060/86115180-e026fb80-bacb-11ea-8c55-071cfc53447d.png)

**Comment by ta264** [comment]
There is a bug here but it has been fixed in v3.  Marking as support so you get the link to discord.

Effectively your database is corrupt, you'll need to restore a backup.

**Comment by MiTvSpain** [comment]
How do I install version V3? What corrects error?

**Comment by ta264** [comment]
Please join the discord channel if you need support
