### ISSUE TITLE
[Feature Request] Add Movie Title to Custom Filter view.

### ISSUE THREAD

**Issue by Silent-Remux** [Radarr/Radarr#4563]
This would allow to me to filter out certain movies.

Ideally I'd be able to use `{MovieTitle}` + `{contains}` `{does not contain}` `{equal}` `{not equal to}`

<img width="588" alt="Screenshot at Jul 03 12-33-51" src="https://user-images.githubusercontent.com/16107603/86467129-bfa9ac00-bd2c-11ea-9ef1-53e9a91f3333.png">

**Comment by Qstick** [comment]
https://github.com/Radarr/Radarr/commit/347cd5982a0f27eea737461d7981623c6c4900c6
