### ISSUE TITLE
[Feature Request] Add {Year} to Custom Filter view.

### ISSUE THREAD

**Issue by Silent-Remux** [Radarr/Radarr#4564]
Would allow for filtering between certain decades i.e.

`{Year}` `{within}` `1990 - 1999`

<img width="588" alt="Screenshot at Jul 03 12-33-51" src="https://user-images.githubusercontent.com/16107603/86467924-41e6a000-bd2e-11ea-8969-be7fac9dc518.png">

**Comment by Qstick** [comment]
https://github.com/Radarr/Radarr/commit/347cd5982a0f27eea737461d7981623c6c4900c6
