### ISSUE TITLE
[Feature Request] Add {Year} to table options view.

### ISSUE THREAD

**Issue by Silent-Remux** [Radarr/Radarr#4566]
Physical release year / in cinemas dates are not as static as the year for each movie title.

<img width="357" alt="Screenshot at Jul 04 10-39-35" src="https://user-images.githubusercontent.com/16107603/86509834-ad8a4500-bde2-11ea-9168-4694175183a2.png">

**Comment by Qstick** [comment]
https://github.com/Radarr/Radarr/commit/b97e6977fb6fbd71598be61c1958f8447c48b84e
