### ISSUE TITLE
unable to change file permission on radarr

### ISSUE THREAD

**Issue by alculete** [Radarr/Radarr#4567]
**Describe the bug**
unable to change permission on linux

**To Reproduce**
1. Go to Settings > Media management
2. Click on Permission and change any 775 for example
3. See error below
![image](https://user-images.githubusercontent.com/2129497/86510132-6190cd80-bded-11ea-98bd-31ab9075ce55.png)

**Expected behavior**
Should change to the new set permission

**Platform Information (please complete the following information):**
 - OS: ubuntu-server  20.04
![image](https://user-images.githubusercontent.com/2129497/86510171-b3d1ee80-bded-11ea-9bee-ed4949b6642a.png)

**Debug Logs**

[radarr.debug.zip](https://github.com/Radarr/Radarr/files/4872494/radarr.debug.zip)

**Comment by Qstick** [comment]
Believe you want 664, as the help text says, the exec bits are added
