### ISSUE TITLE
Items per list broken. Can't add movies.

### ISSUE THREAD

**Issue by Sergiodiaz53** [Radarr/Radarr#4569]
Hello,

I'm having a problem adding movies to radarr. All my files are in the correct format -- filmname (year)/filmname.mkv -- and when I add the folder it detects all of the files (34 pages of movies). If I try to change the number of items per page (from 15 to anyother) it always shows 'No movies found in folder /movies/'

I have tried to add the movies from 1 page each time but at the second page it stop working showing the same problem (No movies found in folder /movies/).

Im using Unraid 6.8.3 and the radarr version 0.2.0.1504 (throug docker). 
I have my files in /movies
I just click 'add movies' > 'Bulk import movies' > select /movies > click on the green button

Thanks in advance.

**Comment by Qstick** [comment]
This works fine for me on same setup, can change page count, can change page, import works either way.
