### ISSUE TITLE
Add option for "GP Only" for PTP tracker

### ISSUE THREAD

**Issue by evulhotdog** [Radarr/Radarr#457]
Option to only download GP releases from PTP under the tracker

**Comment by onedr0p** [comment]
I can only add a require golden for both RSS sync and manual search, I cannot do one or the other without some additional changes in the download dicision engine.

**Comment by roquemore92** [comment]
To expand on this, would it be possible to have an option for GP to be a cutoff option under Profiles? Basically I would like it to grab any 1080p release as soon as it is available, and then upgrade it later when/if a GP becomes available.

The trick here would be it would need to know if the release it already grabbed was the one that gets upgraded to GP so it doesn't try to grab it again.

Having a "GP only" option is great for movies that have been out for a while, but for newer movies, it can take several months for a release to go through the GP screening process. I would like to be able to grab the release as soon as it is uploaded, so my users and I can be able to watch it, then upgrade it later once a release is given GP status.

**Comment by onedr0p** [comment]
@roquemore92 doing that will require the core of the decision engine to change. I am not looking into doing that any time soon.
