### ISSUE TITLE
Error in raname of movie folder format

### ISSUE THREAD

**Issue by lukjod** [Radarr/Radarr#4571]
Recently I get error in rename schema of my folder. Rest as movie and year is ok, it does not add additional info like quality, sound codec and channels.
My setup in advanced settings of Media Management Movie folder format is

{Movie Title} ({Release Year}) [{Quality Title}, {MediaInfo AudioCodec}, {MediaInfo AudioChannels}]

result is : The Outpost (2020) [, , ]
in previous version it was eg The Outpost (2020) [WEBDL-1080p, AC3, 5.1]

it came recently like last week i guess before all was ok.

My setup on Qnap 251+ x64 Linux, image from docker on linuxserver.io

Version
    3.0.0.3123
Package Version
    3.0.0.3123-ls13 by linuxserver.io 
.NET Core
    Yes
Docker
    Yes
DB Migration
    176
AppData directory
    /config
Startup directory
    /app/radarr/bin
Mode
    Console

**Comment by ta264** [comment]
Tags depending on the downloaded release are not supported in the folder name in v3
