### ISSUE TITLE
Ignore dots in moviename when searching

### ISSUE THREAD

**Issue by layzlayz** [Radarr/Radarr#4572]
Please make radarr ignore dots from a releasename automatically when searching.

[AB#855](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/855)

**Comment by layzlayz** [comment]
![radarr without dots](https://user-images.githubusercontent.com/57494874/86840735-6088c600-c0a3-11ea-8991-621a0ecfbb4a.png)
![radarr with dots](https://user-images.githubusercontent.com/57494874/86840740-61b9f300-c0a3-11ea-9a4d-49a9e3084442.png)

**Comment by austinwbest** [comment]
Uhm, this is a bad idea IMO as some movies have periods in the name. So by removing them there is now the risk of not matching them when it should. Why should radarr need to assume/alter something from a **manual entry** instead of the user simply not putting the query in how they want it to search?

**Comment by fryfrog** [comment]
Who.Types.In.Periods.Instead.Of.Spaces?

I don't agree it is a *bad* idea, but it certainly doesn't seem like a *good* idea either. What about `-` or `_`? What is special about `.`?

**Comment by layzlayz** [comment]
> Who.Types.In.Periods.Instead.Of.Spaces?
> 
> I don't agree it is a _bad_ idea, but it certainly doesn't seem like a _good_ idea either. What about `-` or `_`? What is special about `.`?

Have.you.heard.about.scene.releases.

The issue is only when you are pasting the releasename, which I do very often from the Activity page.

**Comment by layzlayz** [comment]
> Uhm, this is a bad idea IMO as some movies have periods in the name. So by removing them there is now the risk of not matching them when it should. Why should radarr need to assume/alter something from a **manual entry** instead of the user simply not putting the query in how they want it to search?

Because scene releasename

**Comment by austinwbest** [comment]
> > Uhm, this is a bad idea IMO as some movies have periods in the name. So by removing them there is now the risk of not matching them when it should. Why should radarr need to assume/alter something from a **manual entry** instead of the user simply not putting the query in how they want it to search?
> 
> Because scene releasename

I know what it is :) However this is a manual entry point in which you are searching TMDB, not PREDB. As i said, it is a bad idea (in my opinion of course & from a use-as-intended standpoint) and i'll stick to that regardless of the decision made to implement or not :)

Guess it'll be up to q or ta to do this or not in the end.

**Comment by layzlayz** [comment]
Maybe a solution would be a checkbox for that setting to be enabled or not?

**Comment by Qstick** [comment]
We're not going to add an option for it. Either we'll do it or not. I really don't see a downside to ignoring periods in the name but I need to investigate how our search handles movies that have periods.

**Comment by codeclem** [comment]
It makes no sense to do this. The search box is for searching movie titles, not release names. OP is just using it wrong.

**Comment by Qstick** [comment]
This already works assuming the search term is a release name that is parable
