### ISSUE TITLE
Sort Movies by Custom Format

### ISSUE THREAD

**Issue by Lonewolf982** [Radarr/Radarr#4573]
**Is your feature request related to a problem? Please describe.**
I want to know quickly which movies satisfy my custom formats and which do not that way I can differentiate between the movies and know which ones I need to search for when on private trackers (as I do want to pick and choose which movies i want in the particular custom format very quickly)

**Describe the solution you'd like**
The ability to sort movies according to their custom format tags.

**Describe alternatives you've considered**
Manually selecting each and every movie then creating an excel sheet to keep track...

**Comment by Qstick** [comment]
Dupe #3284
