### ISSUE TITLE
Renaming Tags for resolution?

### ISSUE THREAD

**Issue by STaRDoGG** [Radarr/Radarr#4575]
I like to add the resolution to my file names, but afaikt Radarr doesn't have these?

i.e. (after the codec)

`Mad Max - Fury Road (2015) - [HD 1080p x265 1920x800] [AAC 8ch]`

In Radarr's renaming section, it might look like:

` {MediaInfo VideoWidth}x{MediaInfo VideoHeight}`

Any chance on adding these?

TIA

**Comment by ta264** [comment]
Dupe #4520
