### ISSUE TITLE
Movie Posters Missing When Adding New Movies (since 0.2.0.1504)

### ISSUE THREAD

**Issue by flcowboy7** [Radarr/Radarr#4579]
**Describe the bug**
The movie poster image that shows next to a movie title when adding a new movie is sometimes missing.

**To Reproduce**
1. Go to '+Add Movies'
2. Click on 'Discover New Movies'
3. Scroll down to see that some (many) movies are no longer showing an image, though the image exists on themoviedb.org.

** Screenshot **
[radarr-images](https://user-images.githubusercontent.com/42279189/86983141-08140000-c159-11ea-97c1-a112dee897f9.png)

**Expected behavior**
Expect images to render.

**Platform Information (please complete the following information):**
 - OS: Windows 10
 - Browser and Version: Firefox 78.0.1 (64-bit) and Google Chrome 83.0.4103.116 (Official Build) (64-bit)
 - Radarr Version: 0.2.0.1504

**Debug Logs**
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/4893832/radarr.debug.txt)

**Comment by flcowboy7** [comment]
Should be easy to replicate the issue. Tried using a private Firefox window and the issue persists, so it's not browser-cache related.

**Comment by fryfrog** [comment]
I'm pretty sure posters missing from Discover on v0.2 is a known problem, did you have a search in the issues? No work is being done on v0.2 either, so it doesn't matter. At least v3 works.

**Comment by fryfrog** [comment]
#4393

**Comment by Qstick** [comment]
Yea, this won't be fixed, the v0.2 is like a mysterious unicorn... Noone really knows what it does or how it works.. V3 is the future

**Comment by flcowboy7** [comment]
@fryfrog - Yes, but I was only looking at open issues (my bad).
@Qstick - How do I get v3 then? This wasn't a problem in v0.2.0.1480.
