### ISSUE TITLE
[Bug] Movie refresh

### ISSUE THREAD

**Issue by Silent-Remux** [Radarr/Radarr#4580]
**Describe the bug**

When adding a new movie (no file) and then changing the path to an existing folder which contains a movie, hitting refresh on the movie entry takes you back to the main movie index. You then have to search to find the movie again where it now shows the "downloaded" file. 

The bug is the fact it shouldn't take you back to the movie index at all.

Seen on Aphrodite: `3.0.0.3143`

**Comment by bakerboy448** [comment]
@Silent-Remux is this still an issue on the recent builds?

**Comment by wobblybob** [comment]
I have a similar issue. Just updated my docker image and it upgraded me to 3.0. If I search for a movie in my library that I have never opened before, then click "refresh & scan", it refreshes but kicks me back to the main movie index. 

I then have to search for the movie again to pull it up. After that first kick out, it doesn't do it again for that movie, but any other movie that I have never loaded before does this. It should keep me on focused on the movie. Let me know If I should create a new bug or need more information. 

Unraid 6.8.3
binhex-radar docker

**Comment by austinwbest** [comment]
It is related to the slugs.. Do a full refresh rescan of your library

**Comment by wobblybob** [comment]
> 
> 
> It is related to the slugs.. Do a full refresh rescan of your library

thanks, that did it.

**Comment by Silent-Remux** [comment]
Don't think I'm seeing this anymore.
