### ISSUE TITLE
Adding more info to Discover screens

### ISSUE THREAD

**Issue by oliroe** [Radarr/Radarr#4583]
**Is your feature request related to a problem? Please describe.**
Adding more information to the screens within Discover to make it more useful. In the screen below it would be useful to be able to add it to the exclusion list. At present you have to close it, select the movie on the list and then click the exclusion button at the bottom

![image](https://user-images.githubusercontent.com/4500141/87143671-60a0e580-c29e-11ea-9522-51e36d6c64d2.png)

It would also be great if this screen included a link to IMDB/TMDB and also included the Director/Main Actors. At present I look at the list and then have to search for them manually in IMDB to see whether they're of interest

**Comment by austinwbest** [comment]
Was kind of agreed that adding things to that popup was not ideal. A better option was to add it to the previous page (results list) to avoid having to open/close each one to find the external links. 

Also adding of the actors/director(s) isn't something i feel belongs on the search results. Again, simply to much info for the use-case and trying to keep it organized, etc.. Trying to determine how many actors, which ones, etc.. Simply to many variables and adds clutter. For this reason i did not add that to the page. If ta or q want to add it i'm sure they will but for now at least you'll have the imdb/tmdb/trakt links easily accessible in the results table.

**Comment by oliroe** [comment]
Completely get your viewpoint, the one addition that would be useful and not clutter the pop up screen is the ability to add it to the exclusion list. It's all just opinions though :)

**Comment by austinwbest** [comment]
Maybe i am mistaken on what you mean, V3 has "Add Exclusion" on the bottom right

**Comment by Qstick** [comment]
Also it's on every item, the "x" icon

**Comment by oliroe** [comment]
I just thought it would be useful to have it in this window

![image](https://user-images.githubusercontent.com/4500141/87812540-4182f480-c858-11ea-94b8-8071554de20e.png)

Seems logical to have the option to add the movie or exclude it at this stage. Not a problem if it's not a popular viewpoint

**Comment by austinwbest** [comment]
I'm gonna call this closed. You can exclude in mass with the button or you can use the X on each row for individual items. To me that is sufficient. Your call @Qstick though :)
