### ISSUE TITLE
Radarr does not import movies on mounted NFS share from FreeNAS

### ISSUE THREAD

**Issue by ionutm80** [Radarr/Radarr#4585]
Hi guys, I'm having some problems with permissions rights for Radarr Docker. Long story short: my main system is FreeNAS where I have specific datasets for movies, tv shows and music already populated. I have created an Ubuntu VM and installed DockSTARTer.  I have mounted the the datasets above with NFS share on the UbuntuVM and imported all the movies, tv shows and music in Radarr, Sonarr and Lidarr Docker. Than I added a new movie to Radarr, the instruction has been sent to Transmission which download it in the downloads folder. However Radarr Docker is not able to import this new movie and move it in the movies folder where the dataset from FreeNAS is mounted.

The log error is the following:

```
Couldn't import movie /downloads/completed/Movie/movie.mkv: Value cannot be null. (Parameter 'path2')

System.ArgumentNullException: Value cannot be null. (Parameter 'path2')
   at System.IO.Path.Combine(String path1, String path2)
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeMovieFile(MovieFile movieFile, LocalMovie localMovie, Boolean copyOnly) in d:\a\1\s\src\NzbDrone.Core\MediaFiles\UpgradeMediaFileService.cs:line 50
   at NzbDrone.Core.MediaFiles.MovieImport.ImportApprovedMovie.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in d:\a\1\s\src\NzbDrone.Core\MediaFiles\MovieImport\ImportApprovedMovie.cs:line 123
```

Initially I thought about a permission issue but, please see below the permissions for the movies folder: 

```
from the Ubuntu VM host:
ionut@ubuntu-vm:~/media$ ls -la
total 105
drwxr-xr-x 3 root root 4096 Jul 10 05:01 .
drwxr-xr-x 7 ionut ionut 4096 Jul 10 05:01 ..
drwxrwxr-x 163 ionut ionut 163 Jul 10 05:20 movies
ionut@ubuntu-vm:/$ id ionut
uid=1000(ionut) gid=1000(ionut) groups=1000(ionut),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),116(lxd),998(docker)
```

from inside the Radarr Docker:
```
drwxrwxr-x 163 abc abc 163 Jul 10 08:20 movies
```
```
root@DockSTARTer:/# id abc
uid=1000(abc) gid=1000(abc) groups=1000(abc),100(users)
```

As you can see both the host user (ionut) and Radarr Docker user (abc) have the same UID=1000 and GID=1000.

The dataset from FreeNAS is shared with NFS and mounted in /etc/fstab:

```
192.168.1.81:/mnt/Homeserver/Media/Temporary_Movies /home/ionut/media/movies nfs auto,nofail,noatime,nolock,intr,tcp,actimeo=1800 0 0
```

The share in FreeNAS has Maproot User as Ionut with UID=1000 and Maproot Group as shares with GID=1000.

If I do not mount the FreeNAS dataset everything works as intended, Radarr Docker is capable to move the downloaded movie from downloads folder to movies folder. Once I mounted the dataset from FreeNAS something changes and Radarr Docker cannnot longer move files into the movies folder but can still add empty movies folders.

Sorry but I'm completely lost here!

v3.0.0.3154 Aphrodite

I’ll come back with a debug log!

**Comment by ta264** [comment]
I think this is probably a duplicate of #4360 which we are struggling to get to the bottom of. Please can you join the discord and hopefully you can help either me or qstick try to get to the bottom of jt

**Comment by ionutm80** [comment]
Ok, thanks for info, I’ll join discord.

**Comment by ionutm80** [comment]
[radarr.debug.6.txt](https://github.com/Radarr/Radarr/files/4906391/radarr.debug.6.txt)

**Comment by ionutm80** [comment]
Ok, I have managed to solve the issue, it was a permission issue on FreeNAS side, the dataset I was mounting was owned by multiple jails. I created a new dataset specifically for Ubuntu VM and voila, everything works like magic.
