### ISSUE TITLE
Indexer "Search by Title" 

### ISSUE THREAD

**Issue by Orishas** [Radarr/Radarr#4586]
**Description:**
On radarr stable you have the option "search by title".
aphrodite is missing this feature resulting in that my indexer is not finding anything.

**Radarr Version:**
aphrodite

**Comment by Qstick** [comment]
Fill in the entire template, “Aphrodite” is not a version. Please provide logs of said search failing as Radarr automatically defaults back to title if Id search fails. Will need some logs to see why it’s not doing what it’s supposed to.
