### ISSUE TITLE
Unrecognized Movie although downloaded and parsed correctly

### ISSUE THREAD

**Issue by HansBauer79** [Radarr/Radarr#4587]
**Describe the bug**
Although the movie is added correctly to the Radarr-Database and also downloaded correctly by sabnzbd, the activity page is showing it as "unknown movie".
The parsing shown in the debug log seems to be working right:

```
2020-7-13 08:18:03.1|Debug|TrackedDownloadService|Tracking 'SABNzbd:Der.Schlangenkuss.1997.German.DL.1080p.HDTV.x264-NORETAiL': ClientState=Completed RadarrStage=Downloading Movie='Der Schlangenkuss - 1997 HDTV-1080p v1' OutputPath=Downloads/complete/Der.Schlangenkuss.1997.German.DL.1080p.HDTV.x264-NORETAiL/.
2020-7-13 08:18:03.1|Debug|Parser|Parsing string 'Der.Schlangenkuss.1997.German.DL.1080p.HDTV.x264-NORETAiL'
2020-7-13 08:18:03.1|Debug|Parser|Movie Parsed. Der Schlangenkuss - 1997 
2020-7-13 08:18:03.1|Debug|Parser|Release Group parsed: NORETAiL
2020-7-13 08:18:03.1|Debug|Parser|Languages parsed: German
2020-7-13 08:18:03.1|Debug|QualityParser|Trying to parse quality for Der.Schlangenkuss.1997.German.DL.1080p.HDTV.x264-NORETAiL
2020-7-13 08:18:03.1|Debug|Parser|Quality parsed: HDTV-1080p v1
2020-7-13 08:18:03.1|Debug|Parser|Edition parsed: 
```

**Screenshots**
Activity Page:
![image](https://user-images.githubusercontent.com/68218222/87278362-8fa89880-c4e4-11ea-93bf-30bc56594116.png)

**Platform Information**
 - OS: Ubuntu 16
 - Browser: chrome 83
 - Radarr Version: 3.0.0.3164
 - Package Version: 3.0.0.3164-ls14 by linuxserver.io
 - .NET Core: Yes
 - Docker: Yes
 - DB Migration: 177

**Comment by JBou** [comment]
Same happens to me every now and then.
It says: "Unknown Movie". If i click the Refresh button on the Queue page, [this is the tracelog](https://pastebin.com/1Wafvn9y), but there are no logs of the movie being parsed.

I then restarted Radarr to try if i get some parsing logs. [This is the tracelog after restarting](https://pastebin.com/hnFwdNp8), it successfully parses the correct movie and year, but it doesn't import the the movie and afterwards it still says "Unknown movie".

![image](https://user-images.githubusercontent.com/4021928/87451544-4baab600-c600-11ea-8b66-f1213a08fede.png)

**Comment by austinwbest** [comment]
Because it can parse the name doesn't mean it can find the media in your library. That error happens when it cant match the movie to an existing one in the library.

Shining is The Shining for example which may be part of the problem :)

**Comment by Qstick** [comment]
This also happens right now because we are a bit looser with searching than final parsing when it comes to languages and alt titles

**Comment by HansBauer79** [comment]
Ok, so for my example above it means that radarr can´t find the parsed name of the movie in AlternativeTitles (there is only one french title):
![image](https://user-images.githubusercontent.com/68218222/87753305-9eec5680-c802-11ea-8665-f67f4f4f987a.png)

But the name can be found in the Table MovieTranslations:
![image](https://user-images.githubusercontent.com/68218222/87753434-e246c500-c802-11ea-8f61-d95428e9a7b9.png)

Does radarr only search for a title match in AlternativeTitles or also in MovieTranslations?

**Comment by Qstick** [comment]
Correct, It's on the to do list though. That's why I've left this issue open.
