### ISSUE TITLE
[Feature Request] Add {TMDb Id} as an extra option for naming movies

### ISSUE THREAD

**Issue by r0747249** [Radarr/Radarr#4592]
Plex is going to add support for IMDB and TMDB IDs in file names in their new movie scanner: [https://forums.plex.tv/t/new-plex-media-server-movie-scanner-and-agent-preview/593269/516](url)
You already support {IMDb Id} and so I was wondering if you could maybe add {TMDb Id}. This would improve the speed for matching movies in Plex.

**Comment by Qstick** [comment]
This is already in Aphrodite V3...

![image](https://user-images.githubusercontent.com/376117/87499016-3ac16b00-c627-11ea-88f3-20732d735256.png)
