### ISSUE TITLE
Movie not being added to queue

### ISSUE THREAD

**Issue by BodingClockchian** [Radarr/Radarr#4601]
**Describe the bug**
A particular movie is not being added to activity
This is the case with some movies now and then. 
Most of the time it works just fine.

**To Reproduce**
1. Auto search for a movie
2. Movie gets added to sabnzbd
3. Dead end

**Expected behavior**
I except that the movie is being monitored by radarr in the activity tab.

**Platform Information (please complete the following information):**
 - OS: Ubuntu 18
 - Mono Version: 5.20.1.34
 - Radarr Version 0.2.0.1504 develop linuxserver.io container
 - Sabnzbd 2.3.9 [03c10dc]

**Debug Logs**
Tracelog after downloading this movie that wont get added to the queue (https://pastebin.com/XAG3nGSC)
Error that shows up in logs (https://pastebin.com/w0Qdznud)

**Comment by ta264** [comment]
I expect this works on V3 (Currently still alpha). If not. If not let us know with some updated logs. We're not fixing bugs in 0.2 any more.
