### ISSUE TITLE
Call XML not a proper XML-RPC call.  XML-RPC request too large.

### ISSUE THREAD

**Issue by turkeyphant** [Radarr/Radarr#4602]
**Describe the bug**
Can't add certain torrents to download queue.

Server returned a fault exception: [-503] Call XML not a proper XML-RPC call.  XML-RPC request too large.  Max allowed is 524288 bytes

**To Reproduce**
1. Go to /movies/blow-4133
2. Click on Search
3. Use PTP as a source
4. Add torrent with highest number of seeds to download queue.
5. Receive XML error

(still happens with other browsers and after rebooting docker)

**Expected behavior**
Adds torrent to rutorrent. Works fine with other torrents.

**Screenshots**

**Platform Information (please complete the following information):**
 - OS: unraid
 - Mono Version: 5.20.1.34
 - Radarr Version 0.2.0.1504

**Debug Logs**
[radarr.txt](https://github.com/Radarr/Radarr/files/4932006/radarr.txt)

**Comment by larsjohnsen** [comment]
rTorrent must be configured to accept large requests. See https://github.com/Flood-UI/flood/issues/492#issuecomment-338419508

**Comment by Qstick** [comment]
Seems like this is not a Radarr issue by @larsjohnsen comment, closing for now
