### ISSUE TITLE
Movie Folder & File Renamer -- Movie Renaming

### ISSUE THREAD

**Issue by rmanzt** [Radarr/Radarr#4604]
When Radarr copies over files to /path it renames the folder and file based on how the user sets it in Settings>Movie Renaming.

This is nice, however, I've ran into an issue where I've now amassed 2000 movies and had radarr rename everything incorrectly.

It would be nice if there was an option to re-rename everything again after the fact. 

This isn't really achievable through other programs because I'd want to retain/rename to parts of the original file name (such as Release Group and Edition Tags) as it was initially when grabbed/downloaded from torrent/usenet source.

I'm thinking this would be pretty easy to implement because it would require something like a log of the original file names that Radarr grabbed from torrent/usenet to then restore the folder/file name back to.

**Comment by austinwbest** [comment]
V3.. Movie Editor > Check All > Rename Files
V2.. Has similar but i dont have V2 installed atm to tell you exactly how. The mass editor though should do what you're wanting.

**Comment by Qstick** [comment]
Yea calling this done in v3, you can bulk rename  files (and folders)
