### ISSUE TITLE
Ability to hard link already existing movies

### ISSUE THREAD

**Issue by venounan** [Radarr/Radarr#4605]
**Is your feature request related to a problem? Please describe.**
I installed Radarr, but I have a library of ~500 titles that I need to seed, and I can't find a suitable way to make them seed-able 

**Describe the solution you'd like**
I would like for a way for Radarr to take files from one spot and hard link them to another spot. It works fine with NEW files being downloaded, but I can't do this with any files that currently exist.

**Describe alternatives you've considered**
I could restructure my media folders, or give my dockers access to each-others data (currently torrent docker and plex docker don't have access to the same folders.

**Comment by Qstick** [comment]
Turn on Hardlinks, Use manual import instead of bulk import. As long as you are importing from outside of the movie folders it should work.
