### ISSUE TITLE
Movie Info Language "French (FR)" & "French (CA)"

### ISSUE THREAD

**Issue by sound-matt** [Radarr/Radarr#4612]
**Is your feature request related to a problem? Please describe.**
When set `Settings > UI > Movie Info Language` to "French" it's canadian french (fr-CA).

Same for `Settings > Media management`: {Movie Title:FR} renamme movies in canadian french

**Describe the solution you'd like**
Add option to choose "French (FR)" or "French (CA)".

Allow {Movie Title:fr_FR} and {Movie Title:fr_CA}

**Comment by foXaCe** [comment]
@Qstick please fix this bug

**Comment by Qstick** [comment]
Plan to look at it tomorrow

**Comment by foXaCe** [comment]
ok thank you

**Comment by foXaCe** [comment]
hello no news for this ?

**Comment by foXaCe** [comment]
can be with an omdb api key

**Comment by ta264** [comment]
Please stop spamming us with, we'll get to it when we get to it @foXaCe

**Comment by foXaCe** [comment]
ok sorry

**Comment by sound-matt** [comment]
Hello,

I updated radarr to the latest version (3.0.0.3369 - 05/08/2020) and I still have an issue. Now I have some movies with a fr-FR title and some with a fr-CA title.

- [16 Blocks](https://www.themoviedb.org/movie/2207-16-blocks) -> (fr-CA) 16 rues
- [Get Hard](https://www.themoviedb.org/movie/257091-get-hard) -> (fr-CA) Prison 101
- [Central Intelligence](https://www.themoviedb.org/movie/302699-central-intelligence) -> (fr-FR) Agents presque secrets
- [American Gangster](https://www.themoviedb.org/movie/4982-american-gangster) -> (fr-FR) American Gangster

**Comment by Qstick** [comment]
Refresh the movies

**Comment by sound-matt** [comment]
I did, I also tried to delete then add to movie again

**Comment by Qstick** [comment]
Works fine here, French FR shown correctly 

![68D963F6-2B4F-4D98-B449-C6F8A12B1D85](https://user-images.githubusercontent.com/376117/89464584-b900c100-d73e-11ea-8643-6f24cb9340e6.jpeg)

**Comment by sound-matt** [comment]
Hello, maybe there is something I miss because even with a new container (so I don't have hidden config or cache), I still get "16 rues"

I use the docker version "linuxserver/radarr:preview" (3.0.0.3371-ls18 by linuxserver.io)

![Capture d’écran du 2020-08-06 12-48-26](https://user-images.githubusercontent.com/16086894/89524403-ccfefe00-d7e4-11ea-8063-31ca678b4420.png)

1) Settings > UI > Language > UI Language: "French"
2) Settings > Media management > Movie Folder Format: "{Movie Title:FR} ({Release Year})"
3) Searching "16 blocs"
4)  Click "Add 16 block" (Root folder: "/movies_path/16 blocs (2006)")
5)  Go on 16 block page, movie became "16 rues" (Root folder: "/movies_path/16 rues (2006)")
