### ISSUE TITLE
Enable/Disable Restrictions

### ISSUE THREAD

**Issue by jaredhobbz** [Radarr/Radarr#4613]
**Is your feature request related to a problem? Please describe.**
Hello! I was wondering if it would be possible to add a toggle to the restrictions for enabling/disabling them? I often use restrictions to upgrade movies to a few specific release groups and then need to remove the restriction to allow everything else in after I'm done searching through my library. The cycle of deleting and recreating these restrictions can be cumbersome.

**Describe the solution you'd like**
Add an enable/disable toggle in the modal for editing a restriction. When enabled, use the "must contain" and "must not contain" tags when searching like usual. When disabled, skip them.

**Describe alternatives you've considered**
The only alternative is to delete the restriction and recreate all of the "must contain" and "must not contain" tags later.

**Additional context**
Just wanted to say that this is a great project and I appreciate the awesome support provided by everyone involved!

**Comment by Qstick** [comment]
You could use a tag to control restrictions or switch and use custom formats which can be controlled per profile

**Comment by jaredhobbz** [comment]
Thanks for the quick reply @Qstick. Could you describe using the tag to control restrictions? The custom formats option doesn't quite work because although I could make it prefer the release groups I specify, I wouldn't be able to make it skip anything and everything else. Does that make sense?

**Comment by Qstick** [comment]
If you add a tag to a restriction set, only movies that are tagged with the same tag will use those restrictions.

**Comment by jaredhobbz** [comment]
Ah ok so I guess I could assign a tag to all movies in my library, run the search with the restrictions enabled, and then remove the tag from everything in my library so that the restrictions no longer apply? That may be exactly what I'm looking for.

**Comment by Qstick** [comment]
Yep

**Comment by jaredhobbz** [comment]
Perfect. Appreciate the help and the quick response!
