### ISSUE TITLE
Tag Detail Service Uses GetAllMovies, Making it slow to return for Large Libraries

### ISSUE THREAD

**Issue by Qstick** [Radarr/Radarr#4615]
**Describe the bug**
The TagDetailService has two functions, Details(TagId) and Details(). Both Functions use GetAllMovies making them slow on large Libraries. Details(TagId) calls AllForTag(TagId) in MovieService which calls for all movies and then filters instead of querying by movies that contain TagId 

`return GetAllMovies().Where(s => s.Tags.Contains(tagId)).ToList();`

Details() first calls to MovieService `GetAllMovies` and then uses response to parse movie lists for each tag. A qucker way would be to query the Movie Table for only movies with Tags and use that in lieu of using the GetAllMovies call

**To Reproduce**
1. Go to Tags Page in Settings for a large library
2. Wait for load

**Expected behavior**
Quickly Load Page

[AB#859](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/859)

**Comment by bakerboy448** [comment]
Code changes aside; is this still impactful with .net5 now?

**Comment by Qstick** [comment]
This was fixed and reworked  a while back.
