### ISSUE TITLE
Hard link manual import

### ISSUE THREAD

**Issue by LeoShivas** [Radarr/Radarr#4619]
**Is your feature request related to a problem? Please describe.**
No, it is related to an existing option in "Media Management / Importing"
![image](https://user-images.githubusercontent.com/28844182/87884103-2eb12100-ca0c-11ea-9e5a-775c155066d5.png)

**Describe the solution you'd like**
When I manually import a movie, si possible to add a "copy by hard linking" option ?

**Additional context**
Here is a screenshot fo the actual situation :
![image](https://user-images.githubusercontent.com/28844182/87884094-1a6d2400-ca0c-11ea-9537-7ec146706581.png)

**Comment by Qstick** [comment]
It should be already doing this if you have it enabled

**Comment by LeoShivas** [comment]
@Qstick, thank you for your answer.
I just checked just now, you're right. The two files have the same inode. It's perfect.
Sorry for having opened this request.
