### ISSUE TITLE
Movie Editor won't update "static path" to no

### ISSUE THREAD

**Issue by scottmlew** [Radarr/Radarr#4620]
**Describe the bug**
When using Movie Editor, selecting change Static Paths to "no" does not work. I've tried numerous variants, such as selecting only 1 vs multiple movies, setting other options before clicking Organize Movies, etc. Static Path can be set to no at the individual movie level through the individual movie interface. 

**To Reproduce**
1. Go to Movie Editor
2. Select one or more movies
3. Set Static Path to "no"
4. Click Organize Movies
5. Viewing the movie information for a movie selected in step 2 will show that Static Path is still set to yes

**Expected behavior**
The selected movies should have Static Path set to "no"

**Platform Information (please complete the following information):**
 - OS: Ubuntu 20.04
 - Mono Version: 6.10.0.104
 - Browser and Version: Chrome 83.0.4103.116
 - Radarr Version: 0.2.0.1480

**Debug Logs**

2020-7-19 16:46:16.7|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (4 ms)
2020-7-19 16:46:27.8|Debug|Api|[POST] /api/command: 201.Created (25 ms)
2020-7-19 16:46:27.8|Debug|RenameMovieFileService|Renaming movie files for selected movie
2020-7-19 16:46:27.9|Info|RenameMovieFileService|Renaming movie files for 21 Jump Street
2020-7-19 16:46:27.9|Debug|RenameMovieFileService|Renaming movie file: [3728] 21 Jump Street (2012) Remux-1080p.mkv
2020-7-19 16:46:28.0|Debug|MediaInfoFormatter|Formatting audio channels using 'AudioChannelPositions', with a value of: '3/2/0.1'
2020-7-19 16:46:28.0|Debug|MovieFileMovingService|Renaming movie file: [3728] 21 Jump Street (2012) Remux-1080p.mkv to /mnt/movies/<path>/21 Jump Street (2012) Remux-1080p.mkv
2020-7-19 16:46:28.0|Debug|RenameMovieFileService|File not renamed, source and destination are the same: /mnt/movies/<path>/21 Jump Street (2012) Remux-1080p.mkv
2020-7-19 16:46:28.0|Info|RenameMovieFileService|All movie files renamed for 21 Jump Street
2020-7-19 16:46:32.3|Debug|Api|[GET] /api/history?page=1&pageSize=15&sortKey=date&sortDir=desc&movieId=2265: 200.OK (17 ms)
2020-7-19 16:46:38.6|Debug|Api|[GET] /api/health: 200.OK (1 ms)
2020-7-19 16:46:38.6|Debug|Api|[GET] /api/health: 200.OK (1 ms)
2020-7-19 16:46:39.7|Debug|Api|[GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc&filterType=equal: 200.OK (4 ms)
2020-7-19 16:46:39.8|Debug|Api|[GET] /api/log?page=1&pageSize=50&sortKey=time&sortDir=desc&filterType=equal: 200.OK (4 ms)
2020-7-19 16:46:40.8|Debug|Api|[GET] /api/diskspace: 200.OK (2175 ms)
2020-7-19 16:46:42.4|Debug|Api|[GET] /api/log/file: 200.OK (11 ms)

**Comment by ta264** [comment]
Nothing obvious in the log snippet, you could try with trace logs and join the discord for help working around it.

Dynamic paths are removed in v3, we won't be fixing whatever this is in 0.2...
