### ISSUE TITLE
Option to choose Trakt instead of IMDB for Pushover notifications

### ISSUE THREAD

**Issue by jin-ds** [Radarr/Radarr#4622]
**Is your feature request related to a problem? Please describe.**
No, there is no problem. The IMDB one works well, I just would like to have Trakt.tv links instead

**Describe the solution you'd like**
Currently, it's using IMDB links whenever a movie is downloaded:

![](https://cdn.zappy.app/7e83c18bdaeab07ee11dc4e6588370f7.png)

I would like the highlighted link, to be the equivalent of the link in trakt.tv

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

Thank you so much!

**Comment by Qstick** [comment]
Covered by #1809, not planning to add an option just for this. Instead fully customizable title and message
