### ISSUE TITLE
Updating will not be possible to prevent deleting AppData on Update Radarr detected that AppData folder for your Operating System is located inside the directory that contains the Radarr binaries. Normally it would be C:\ProgramData for Windows and, ~/.config for linux. Please look at System -> Info to see the current AppData & Startup directories.

### ISSUE THREAD

**Issue by Weezzel** [Radarr/Radarr#4625]
Updating will not be possible to prevent deleting AppData on Update
Radarr detected that AppData folder for your Operating System is located inside the directory that contains the Radarr binaries. Normally it would be C:\ProgramData for Windows and, ~/.config for linux.
Please look at System -> Info to see the current AppData & Startup directories.

Version 3.0.0.3223
.NET Core Yes
DB Migration 178
AppData directory C:\ProgramData\Radarr
Startup directory C:\ProgramData\Radarr
Mode Service

How will we be able to update this the install dont give any options to install in any other Directory.

I had to copy the updated version from the c:windows\temp folder over to the c:\program data\radarr directory and uninstallthe service with ServiceUninstall.exe in that directory and then install service with ServiceInstall.exe from same directory to resolve the the issue with service not running, as well as changing the account to local account for the service to run.

![Screenshot (2)](https://user-images.githubusercontent.com/67742562/87985828-4212c980-caaa-11ea-9da5-8b5abd0d5442.png)
![Screenshot (3)](https://user-images.githubusercontent.com/67742562/87985831-42ab6000-caaa-11ea-8182-b26841de3695.png)
![Screenshot (4)](https://user-images.githubusercontent.com/67742562/87985832-42ab6000-caaa-11ea-8f0e-158359174787.png)
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/4950054/radarr.debug.txt)
[radarr.txt](https://github.com/Radarr/Radarr/files/4950055/radarr.txt)

**Comment by Qstick** [comment]
Don’t tore data folder and program in same place, come to discord for help
