### ISSUE TITLE
Automatically creating empty movie folder doesn't work on empty root folders

### ISSUE THREAD

**Issue by r0747249** [Radarr/Radarr#4628]
**Describe the bug**
When I add a movie to a completely empty root folder the movie folder isn't automatically created. (I also created a list on this folder for all Shrek movies, those folder were also not automatically created)

**Platform Information:**
 - OS: Docker
 - Mono Version: .NET Core
 - Radarr Version 3.0.0.3223

**Debug Logs**
_2020-7-21 00:30:57.2|Info|RefreshMovieService|Updating Info for Shrek Forever After
2020-7-21 00:31:00.4|Debug|MovieService|Updating 1 movie
2020-7-21 00:31:00.5|Debug|MovieService|1 movie updated
2020-7-21 00:31:03.3|Debug|RefreshMovieService|Finished movie refresh for Shrek Forever After
2020-7-21 00:31:03.3|Warn|DiskScanService|Movie's root folder (/movies/DreamWorks/Shrek Collection/) is empty.
2020-7-21 00:31:03.5|Debug|CleanExtraFileService|Cleaning missing metadata files for movie: Shrek Forever After
2020-7-21 00:31:03.5|Info|MetadataService|Movie folder does not exist, skipping metadata creation_

**Comment by Qstick** [comment]
Believe this is an upstream Sonarr issue due to this logic returning if root folder is empty

https://github.com/Sonarr/Sonarr/blob/91b2fe8dcb39699a75244788347079f896eaa75e/src/NzbDrone.Core/MediaFiles/DiskScanService.cs#L83

@Taloth was this intended?

**Comment by fryfrog** [comment]
This is surely intended behavior, for the whole unmounted root folder protection.

**Comment by Taloth** [comment]
Yup, definitely intended. and as you can see it spits out a warning... although we could tack on some more explanation to the warning.

**Comment by diabl0w** [comment]
please add more info to the log if this is intended behavior, i spent many hours trying to figure out what was wrong and why movie folders werent being created. It was also causing the metadata update to spin infinitely and never complete. I was thinking there was a permissions issue or something. I saw the logs about the root path being empty, but that did not mean anything significant to me until i saw this report
