### ISSUE TITLE
Radarr picking releases with HD-TS and HDCAM

### ISSUE THREAD

**Issue by Garderoben** [Radarr/Radarr#463]
My Radarr is downloading releases with the names HD-TS and HDCAM and CAM.
Not sure if this is intended or not but this is my settings.

Would be nice if you could ban some worlds like HD-TS and HDCAM, CAM etc.

The files it downloaded
`
*****.2016.720p.HD-TS.x264-*****.mkv
*****.2016.new.hdcam.1080p.dont.read.nfo.h264-*****.mkv
`

My settings
[Picture](http://image.prntscr.com/image/3a8b845476e645dc8129a6e673705724.png)

**Comment by onedr0p** [comment]
Go to the indexers settings, click show advanced and look at the bottom, add your restriction words there.

![image](https://cloud.githubusercontent.com/assets/213795/22347504/3a12b286-e3d6-11e6-909a-b67c5c818af7.png)

**Comment by galli-leo** [comment]
You can add must not contain below the indexer settings :) Also we are currently working on adding detection for lower qualities.
