### ISSUE TITLE
Wrong video file selected

### ISSUE THREAD

**Issue by r0747249** [Radarr/Radarr#4630]
**Describe the bug**
I have the following file structure for Avatar (2009):

```
/Avatar (2009) 
    Avatar (2009).mkv
    Deleted Scenes-deleted.mkv
    The World of Pandora-other.mkv
```
The problem that I have is that he detects `Deleted Scenes-deleted.mkv` as the movie and not `Avatar (2009).mkv`. I saw in an old post ([https://github.com/Radarr/Radarr/issues/1494](url)) that you support the plex extra folders. I was wondering if you could maybe also support the "inline" version of adding extra's to a movie (https://support.plex.tv/articles/local-files-for-trailers-and-extras/#toc-1). 54/143 of my movies on radarr aren't being correctly recognized. 

**Expected behavior**
`Avatar (2009).mkv` should be selected as the movie and not `Deleted Scenes-deleted.mkv`.

**Platform Information (please complete the following information):**
 - OS: docker
 - Mono Version: .NET core
 - Radarr Version [e.g. 3.0.0.2956]

**Debug Logs**
To create these logs I manually imported the correct video file (`Avatar (2009).mkv`), this worked but then I clicked on Refresh & Rescan and then he detected `Deleted Scenes-deleted.mkv` as the movie again.
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/4954284/radarr.debug.txt)

**Comment by Qstick** [comment]
Should be easy enough to add as an import decision specification

**Comment by thezoggy** [comment]
just to note that this already exists in sonarr codebase, "Extras" had been the defacto subfolder for mediamanagers to know to exclude dvd/bluray extras.

**Comment by alexandrevryghem** [comment]
Yes but then I can't use those extra's with Plex
