### ISSUE TITLE
Manually Set Underlying Indexer Flags on MovieFile

### ISSUE THREAD

**Issue by DirtyCajunRice** [Radarr/Radarr#4633]
**Describe the bug**
You have no way to manually edit the files indexer flags to map a custom format

**To Reproduce**
1. Go to a movie page `http://localhost:788/movie/:id`
2. Click on the `Files` tab
3. See the `Formats` Column
4. Try to import a file that did not import properly and have a custom format using indexer flags be picked up

**Expected behavior**
Ability to hit an `Edit` button and add/remove Indexer Flag(s) on a MovieFile

**Platform Information (please complete the following information):**
 All Aphrodite

**Comment by ta264** [comment]
Sorry, discord misunderstanding

**Comment by kenvalleydc** [comment]
I do this in v2, adding the x265 custom format because I use an external process (Tdarr) to convert my files to HEVC.  I add the custom format to keep the file updated with the change.
