### ISSUE TITLE
Mechanism to give more priority to language than to quality

### ISSUE THREAD

**Issue by rubasace** [Radarr/Radarr#4641]
I share my library with my family. While they consume all content dubbed in Spanish, I just watch everything in original version. 

I have Radarr configured so it only stops looking for movies after Remux.  

Sometimes it downloads a movie in Spanish + English with quality Bluray-1080p (usually due to issues with the naming in Spanish trackers). It's annoying when after getting the Dual version of the movie Radarr decides to replace it with an only English Remux. 

Is there any way of indicating that custom format points are more important than quality ones? I guess there's already some kind of logic around it with the new v3 custom format extra points. I'd rather have a bit lower quality with both languages

**Comment by bakerboy448** [comment]
closing; no plans for this at this time

you can group multiple (or all) qualities together so they will be treated equally;  you can then use CFs in place of qualities
