### ISSUE TITLE
Radarr maps the first one if there are multiple movies parsed in queue

### ISSUE THREAD

**Issue by JBou** [Radarr/Radarr#4643]
**Describe the bug**
if I grab a release that can be parsed to multiple movies, i cannot select the one I want, Radarr just maps one of them. The problem here is, that there is no way to tell radarr it's the other movie. 

**To Reproduce**
For example, I have the movies `Countdown (2016)` and `Countdown (2019)` in my library.
I search for the movie `Countdown (2019)` and download the release `Countdown.German.720p.BluRay.x264-EmpireHD`. In the queue it gets mapped to the first found movie `Countdown (2016)` (I think because this movie has been added first to the library). 

Other movies where this could be a problem are seen in the screenshots:

**Expected behavior**
I suggest to show a yellow icon with the warning: `Failed to import movie, multiple matches found: Countdown (2016)`, Countdown (2019)` and to show the manual import button, so the user has to select the correct movie.

Another option would be to remember the tmdbid of the grab event when mapping the movie in queue, but @Qstick wasn't convinced with it because of fake releases.

**Screenshots**
![unknown](https://user-images.githubusercontent.com/4021928/88338990-88ca2300-cd39-11ea-8443-c01b19561df3.png)

![Screenshot_20200723-230816](https://user-images.githubusercontent.com/4021928/88339013-92538b00-cd39-11ea-955a-38ff33dd6abf.jpg)

**Platform Information (please complete the following information):**
 - OS: linux docker
 - Radarr Version 3.0.0.3216 by hotio

**Comment by JBou** [comment]
I think this is still a problem. It has not been resolved

**Comment by bakerboy448** [comment]
covered under https://github.com/Radarr/Radarr/issues/5282

closing
