### ISSUE TITLE
"Date Added" Pane in Movie Editor for Bulk Organization

### ISSUE THREAD

**Issue by rmanzt** [Radarr/Radarr#4647]
As far as I can tell, there isn't a good way to bulk add movies and set them to a new path for organization purposes -- e.g. bulk adding a bunch of sci-fi movies to set them to a certain path different from action movies.

If there was a "Date Added" pane in the Movie Editor you could bulk add a bunch of movies from list, go to movie editor and sort them by date added, see all the movies you just bulk added,, and then assign them all to a new path.

Otherwise, all the new movies you bulk add get jumbled into the pre-existing movies and you'd have to find each movie one by one and change its path.

**Comment by Qstick** [comment]
Already in v3

**Comment by rmanzt** [comment]
> Already in v3

It's not in "Movie Editor" though, only in Movies. So it's useless for the purpose of applying any changes to those movies.

**Comment by Qstick** [comment]
Sure it is. In v3 everything that is in one is in the other.

**Comment by austinwbest** [comment]
![Annotation 2020-07-25 194806](https://user-images.githubusercontent.com/8321115/88468333-d072bb00-ceaf-11ea-9239-30c09a090d0b.png)

Is this not the filter you speak of that doesn't exist @rmanzt ? Bud they are the **same** exact screen with the exception of editing turns on edit options lol

**Comment by rmanzt** [comment]
> ![Annotation 2020-07-25 194806](https://user-images.githubusercontent.com/8321115/88468333-d072bb00-ceaf-11ea-9239-30c09a090d0b.png)
> 
> Is this not the sort type you speak of that doesn't exist @rmanzt ? Bud they are the **same** exact screen with the exception of editing turns on edit options lol

I'm wasn't aware there was a v3 when I wrote this because I was using the most recent version from the Radarr website, so I was speaking in regards to v2, which doesn't have date added.

Unfortunately, from what I hear v3 isn't stable enough yet for public/everyday use :/

**Comment by austinwbest** [comment]
Your reply to Q telling you it was in v3 was telling him it wasn't :/ lol

Anyhow, v3 is not for those who are scared of testing for sure. If you are more comfortable with 'stable' then yes, you'll need to wait a little longer. Beta is around the corner, it's getting there
