### ISSUE TITLE
All movies deleted on list clean when disconnected from internet

### ISSUE THREAD

**Issue by troywilson** [Radarr/Radarr#4648]
**Describe the bug**
All movies in Radarr were deleted when Radarr was not connected to the internet for 12 hours.

**To Reproduce**
1. Add a list in settings
2. Select clean library: Remove and Delete
3. Unplug internet
4. Wait

**Expected behavior**
I expected that if radarr can't get the lists that it would wait till it could get the lists again before cleaning the library.

**Comment by Qstick** [comment]
Thanks, have you tested on both versions?

**Comment by troywilson** [comment]
Yes. Both running in docker only with external nas connected.

**Comment by Qstick** [comment]
Cool, thanks for reporting, will see about getting it fixed... That's definitely a nice one.
