### ISSUE TITLE
Non-full header icon

### ISSUE THREAD

**Issue by danshilm** [Radarr/Radarr#4659]
**Is your feature request related to a problem? Please describe.**
Background: I recently got Lidarr and realised that I hadn't updated Sonarr and Radarr to v3. So I did. Sonarr? All good. Radarr? All good. Except the ginormous header icon that looked like it wanted me to stare at it instead of the rest of the interface. 
The overall look of the interface has a good amount of padding in its components; like in the sidebar. This makes everything look a lot cleaner, which I like.

**Describe the solution you'd like**
Instead, I would like the non-full icon to be used instead so that it matches what the other arrs have. This is also so that the icon doesn't look so out of place in the new interface.

**Additional context**
Screenshots for reference: 
![Screenshot_82](https://user-images.githubusercontent.com/20923978/88910766-fad8c580-d26d-11ea-8f8d-05d26b532afd.png)
![Screenshot_83](https://user-images.githubusercontent.com/20923978/88910771-fd3b1f80-d26d-11ea-9b09-629a48da22cb.png)

**Comment by bakerboy448** [comment]
No plans to change the header at this time
