### ISSUE TITLE
Movies > Discover row level exclusion does not work

### ISSUE THREAD

**Issue by austinwbest** [Radarr/Radarr#4660]
If you use the Add Exclusion button on the bottom, the movie is removed from the discover list and added to the list exclusions. 

If you use the X in the movie row and pick to exclude it in the dialog, it is not removed & is not added to list exclusions.

**Comment by bakerboy448** [comment]
Definitely a bug in V3.

Trace log seems to indicate clicking exclude after clicking the x does nothing?

https://pastebin.com/4hgRQyg0

turned on trace > went to discover > clicked the x for "The 13th Warrior(1999)" > clicked exclude > turned off trace

**Comment by austinwbest** [comment]
Yea, I'll fix it. Just wanted to get it on here to remember since I have like 4 or 5 other things going too

**Comment by Qstick** [comment]
Fixed b2b0efe4eddddc64bec883a6b0c64c39177ffc2b
