### ISSUE TITLE
Prioritize custom format score over quality

### ISSUE THREAD

**Issue by MateEke** [Radarr/Radarr#4666]
**Description:**

I have three custom format settings, first one is 'HDR' (+1 score), the second one is English language (+2 score), the third one is Hungarian language (+4 score). My minimum score is 2 for not download any other languages (eg. German, French), and the cutoff is 5 for Hungarian HDR releases.
I have two issues with this setup:
- I would rather download a '1080p HDR' release than '2160p non HDR' if '2160p HDR' is not available
- I would rather download any quality Hungarian release over than a higher quality English release

Please allow prioritization of releases based on custom formats over pure qualities!

**Radarr Version:** 3.0.0.3312

**Mono Version:** .NET Core

**Comment by Qstick** [comment]
Couldn't you group your qualities and use CFs exclusive (ex. add 2160p and 1080p to the same group, use custom formats to score things up how you want)

**Comment by MateEke** [comment]
I think it would be possible, but it would result in more complicated profiles. In my opinion the language handling is better in Sonarr's newer versions, where you could prioritize them without custom formats, and even set it based on shows. IMO it's much more streamlined and user friendly. I think user friendliness should be NO.1 priority, otherwise you could just search and download torrents from the tracker or Jackett. I would like to provide an interface for my girlfriend and my parents to download shows/movies and not make me do that for them - too much or too complicated profiles results in that. HDR is not that big issue for me, it's kind of a "nice to have" thing.

Sonarr 3.0.3.904:
![image](https://user-images.githubusercontent.com/11072174/89099875-c80c0a00-d3f2-11ea-8fe0-58d0e1a24520.png)
![image](https://user-images.githubusercontent.com/11072174/89099893-e6720580-d3f2-11ea-91a3-3bff40c0ccac.png)

But in the current system I dont see why de default priorization is based on quality instead on custom profile score - if I have made a custom profile for something it's likely to be more important for me.

**Comment by bakerboy448** [comment]
@MateEke if you need a simplified request tool, just use Ombi!

**Comment by MateEke** [comment]
It seems like Radarr doesn't upgrade files over higher Custom Format score, so you would miss out better matching new releases.

**Comment by ta264** [comment]
Radarr can be configured to upgrade to releases of the same quality with a higher custom format score. If you need help join the discord channel.
