### ISSUE TITLE
Update fails on FreeNAS

### ISSUE THREAD

**Issue by ormanya** [Radarr/Radarr#468]
I installed 0.2.0.210 on FreeNAS using the instructions on the wiki here. When I try to update to 0.0.0.266 via the gui, the new package downloads ok, and starts the updater, but then the update fails as follows:

```
[Info] InstallUpdateService: Updater Arguments: 23123 /tmp/radarr_update /usr/local/Radarr/Radarr.exe  
[Debug] mono: Starting mono --debug /tmp/radarr_update/Radarr.Update.exe 23123 /tmp/radarr_update /usr/local/Radarr/Radarr.exe  
[Error] CommandExecutor: Error occurred while executing task ApplicationUpdate 

[v0.2.0.210] System.ComponentModel.Win32Exception (0x80004005): ApplicationName='mono', CommandLine='--debug /tmp/radarr_update/Radarr.Update.exe 23123 /tmp/radarr_update /usr/local/Radarr/Radarr.exe ', CurrentDirectory='', Native error= Cannot find the specified file
  at System.Diagnostics.Process.StartWithCreateProcess (System.Diagnostics.ProcessStartInfo startInfo) [0x001ee] in <bd46d4d4f7964dfa9beea098499ab597>:0 

```

**Comment by onedr0p** [comment]
Usually Permissions, or Mono venison problem. Can you double check your perms? `Cannot find the specified file` leads me to think it couldn't write to the folder.

**Comment by ormanya** [comment]
Mono version is 4.6.2 (Stable 4.6.2.7/08fd525 Tue Jan 17 01:47:51 UTC 2017)

Permissions are as follows:
/tmp/radarr_update 755 (contents are 644)
/usr/local/Radarr 755 (contents are 700)
/usr/local/Radarr/Radarr.exe 700

Ownership for everything is root:wheel and since this is running in a FreeNAS jail, mono runs as root

**Comment by galli-leo** [comment]
/tmp/radarr_update contents should be 755 or else the updater exe cannot be executed.

**Comment by mow4cash** [comment]
Same permissions as OP, changed /tmp/radarr_update contents to 755. Still failing to update.

**Comment by Firemad03** [comment]
@mow4cash did you try chmod -R 755 /tmp/radarr_update ? or you did only chmod 755 /tmp/radarr_update ?

**Comment by mow4cash** [comment]
I used chmod -R 755 /tmp/radarr_update but it still is failing

**Comment by ormanya** [comment]
I am finding the same issue where all permissions are reset when update is run.

**Comment by ormanya** [comment]
I have changed radarr to run in the FreeNAS jail as a non-root user and chowned the application and tmp folders for the non-root user. Now the updates work. It appears the issue only happens when radarr runs as root. This might be intentional since typically it is not a good idea to run services like this as root (although this is not necessarily the case in a FreeBSD jail)

**Comment by topper59** [comment]
How did you change the user you were running Radarr as? I thought maybe changing the startup command to su USER -c "command" would work but no luck

**Comment by ormanya** [comment]
I created a daemon script in /etc/rc.d https://ghostbin.com/paste/nbzkt

Of course you will also need to create the new user and change ownership of the appropriate folders.

It is based on the latest sonarr script in FreeBSD ports. Note that the code is still a work in progress (a bunch of stuff commented out).

**Comment by Firemad03** [comment]
#521 : "ln -s /usr/local/bin/mono /bin did the trick now I can update Radarr with GUI "

That's what I found on Freenas inside a jail.
