### ISSUE TITLE
Notifications for Radarr Updates

### ISSUE THREAD

**Issue by rodalpho** [Radarr/Radarr#4681]
I would like to get notifications (I use Pushover) when Radarr updates itself or runs into a problem that requires user intervention to correct (disk unavailable, all indexers unavailable, etc). 

[AB#813](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/813)

**Comment by austinwbest** [comment]
![Annotation 2020-07-31 110411](https://user-images.githubusercontent.com/8321115/89048274-9a08c600-d31d-11ea-850f-fa9cad29ad85.png)

**Comment by rodalpho** [comment]
Thanks, I thought that meant when a file didn't have enough parity files to repair. 

Does not cover notifications on upgrade however.

**Comment by austinwbest** [comment]
Only if an update fails, otherwise it isn't a health 'issue'

**Comment by rodalpho** [comment]
Yep, I would like to be notified on successful application upgrades as well.

**Comment by austinwbest** [comment]
I don't see that happening unless a new type for System Notifications or something along those lines is added.

Doesn't fit otherwise based on current usage and wording.

**Comment by rodalpho** [comment]
That is the feature request I'm making here.
