### ISSUE TITLE
Calendar API returning every movies, even those already downloaded and not monitored.

### ISSUE THREAD

**Issue by morpheus65535** [Radarr/Radarr#469]
When using the calendar API with a start date of 1970-01-01 and a end date of yesterday, it return me all movies including those already downloaded and not monitored anymore. I have to drop those with "hasFile" = TRUE to get only wanted movies. It works but it take some time to parse a large library in PHP.

Good work guys and thank you!

**Comment by galli-leo** [comment]
That's intentional, if you have a crappy web rip you might be wondering when the bluray release of a movie is.

**Comment by morpheus65535** [comment]
Don't want to push it but in that case the movie would be monitored. Actually the API return even unmonitored movies. Sound like a strange calendar giving me information on something I don't wanna monitor... ;-)

**Comment by morpheus65535** [comment]
@galli-leo I've created a feature request to add an option to the calendar API so it return only monitored movies: http://feathub.com/Radarr/Radarr/37

Thanks!
