### ISSUE TITLE
Calendar API return incorrect "status" value for in cinema movies

### ISSUE THREAD

**Issue by morpheus65535** [Radarr/Radarr#470]
Maybe I'm wrong but, in calendar API, movies still in cinema status should be "in cinema" (or something else), not "released". I'm my opinion, "released" should be only for movies available on DVD or Bluray.

**Comment by galli-leo** [comment]
Is this for movies that you have already downloaded?

**Comment by morpheus65535** [comment]
Nope, for movies I have put in my "wanted list".

`  {
    "title": "Jack Reacher : Never Go Back",
    "sortTitle": "jack reacher never go back",
    "sizeOnDisk": 0,
    "status": "released",
    "overview": "Reacher retourne dans sa base militaire de Virginie pour dîner avec une collègue. Mais il apprend que celle-ci a été arrêtée et que lui-même est accusé de meurtres.",
    "inCinemas": "2016-10-19T04:00:00Z",
    "physicalRelease": "2017-01-31T00:00:00Z",
    "images": [
      {
        "coverType": "poster",
        "url": "/radarr/MediaCover/299/poster.jpg?lastWrite=636211553000000000"
      },
      {
        "coverType": "banner",
        "url": "/radarr/MediaCover/299/banner.jpg?lastWrite=636210687490000000"
      }
    ],
    "website": "",
    "downloaded": false,
    "year": 2016,
    "hasFile": false,
    "youTubeTrailerId": "gcJj-lsbDYY",
    "studio": "Paramount Pictures",
    "path": "/films/Jack Reacher- Never Go Back (2016)",
    "profileId": 8,
    "monitored": true,
    "runtime": 118,
    "lastInfoSync": "2017-01-27T23:08:19.314306Z",
    "cleanTitle": "jackreachernevergoback",
    "imdbId": "tt3393786",
    "tmdbId": 343611,
    "titleSlug": "jack-reacher-never-go-back-2016",
    "genres": [
      "Action",
      "Crime",
      "Drame",
      "Mystère",
      "Thriller"
    ],
    "tags": [],
    "added": "2017-01-13T21:51:44.692794Z",
    "ratings": {
      "votes": 940,
      "value": 4.7
    },
    "alternativeTitles": [
      "Jack Reacher: Never Look Back",
      "Jack Reacher 2"
    ],
    "qualityProfileId": 8,
    "id": 299
  }`

As you can see, physicalRelease isn't met and status is "released".

**Comment by morpheus65535** [comment]
I call the API with this url:
/calendar?start=1970-01-01&end=2017-01-28&apikey=###################

**Comment by geogolem** [comment]
im not sure if this is what you are referring to but take a look at this screenshot: 
![image](https://cloud.githubusercontent.com/assets/23205277/22814878/2a1a2a9e-ef25-11e6-85e3-8561b8234907.png)

**Comment by geogolem** [comment]
Moanna is currently In Cinemas, but will be getting a physical release on Feb 20th... -- so the movie being turqoise and marked In Cinemas on Feb 20th is confusing. 

likewise, John WIck 2 will be in theaters on Feb 9th... but we are hsowing it as "Announced" on Feb 9th...

i guess the issue is that the dates on the calendar are the dates the state shoud change, but the colour is showing the current colour.. not the colour it will change to on that day.... 

not sure if this is related.. but just an observation i noticed.

**Comment by geogolem** [comment]
might also be related to: https://github.com/Radarr/Radarr/issues/601

**Comment by galli-leo** [comment]
@geogolem That's not actually a "bug". That's just how I implemented it.

**Comment by morpheus65535** [comment]
@geogolem I'm not sure how your posts are related to the issue documented here. We are talking about the developper API that return the status "released" however the movie is in cinema or on dvd/bluray...

@galli-leo told me that the UI is the one how interpret those dates and so, the backend is not aware of that so the API cannot give me a proper status. Correcting this would require a rewrite of some code and that he will, maybe, in the future, take a look at it.

@galli-leo AM I quoting you correctly? :-)

**Comment by galli-leo** [comment]
@morpheus65535 Yup. But I am going to rewrite that for sure. Just need to finish other things first.

**Comment by geogolem** [comment]
@morpheus65535 : Sorry i didnt realize you were talking about the API.. so I didnt really understand what you meant...

**Comment by morpheus65535** [comment]
@galli-leo thanks!

**Comment by morpheus65535** [comment]
@geogolem no problem!

**Comment by morpheus65535** [comment]
@galli-leo Would it be possible to add an optional parameter to the calendar API so we could filter return based on "isAvailable" value? It would be an acceptable workaround.

**Comment by galli-leo** [comment]
@morpheus65535 Maybe. Once I have time to add that. Anyways, status should now be reported correctly.

**Comment by morpheus65535** [comment]
Your right, the status is now reported correctly. My concern here was about the time required to generate the json for a library containing over 500 movies: if I do an API call to get those released between 1970 and now, therés now way to filter those I have downloaded and return only those missing. For my library, it take more than 5 seconds on a quad core CPU with plenty RAM. The json returned is over 1mB... When I call the same API from today till the end of time, it take less than a second to return 50 movies.
