### ISSUE TITLE
Series root folder Empty

### ISSUE THREAD

**Issue by Toasterthegamer** [Radarr/Radarr#471]
The exact error: "DiskScanService Series' root folder (F:\Movies) is empty."

I get this when I am trying to import existing movies into radarr from my local drive. 

I am running windows 10. I checked to make sure permissions are setup correctly and the files are recognized by other programs on my machine.

Thanks,
-Toaster

**Comment by seriosbrad** [comment]
I believe this is because at this time, Radarr requires all movies to be in its own directory.  As a quick temporary fix, you can use something like this to move them into folders.  https://code.google.com/archive/p/file2foldergui/downloads

**Comment by mow4cash** [comment]
Same issue here. Who would want separate folders to contain a single movie? I'm guessing it's because Radarr is a fork of Sonarr.

**Comment by Toasterthegamer** [comment]
That was def the issue once the movies were in separate folders it worked fine..

**Comment by jbmorgado** [comment]
Why was this closed? It is already in feature requests or do you plan to leave this limitation as is?

**Comment by galli-leo** [comment]
@jbmorgado There is already an other issue open regarding this.

**Comment by 19wolf** [comment]
Link?

**Comment by galli-leo** [comment]
@19wolf https://github.com/Radarr/Radarr/issues/153
