### ISSUE TITLE
sab - default category

### ISSUE THREAD

**Issue by thezoggy** [Radarr/Radarr#475]
when adding sab to radarr, default cat is still set to `tv`

**Comment by onedr0p** [comment]
I believe I fixed this awhile ago :)

**Comment by thezoggy** [comment]
yes, https://github.com/Radarr/Radarr/blob/develop/src/NzbDrone.Core/Download/Clients/Sabnzbd/SabnzbdSettings.cs#L41
`movies` is the default now..
