### ISSUE TITLE
Feature: Import indexers+downloaders+Connect from existing Sonarr instance

### ISSUE THREAD

**Issue by thezoggy** [Radarr/Radarr#476]
Would be nice to just have Radarr import existing Sonarr Indexers+Download Client+Connect..

**Comment by galli-leo** [comment]
Since a lot pf settings are different this would be kinda difficult to implement. Anyway this takes like 2 minutes top to setup so for now we wont do it.

**Comment by galli-leo** [comment]
Please post feature requests first on feathub: feathub.com/Radarr/Radarr

**Comment by schumi2004** [comment]
I find such requests useless imo. None of the programs like radarr, cp, sickbeard have such functionality. It are one a few settings why create a import function for such?

**Comment by thezoggy** [comment]
If CP was a fork of SB... You probably would have. Replicating the same
info to two apps with same code base just seems inefficient. And it being 2
mins is overly optimistic... Try having 10+ indexers, lots of connect
(multi client setup) + multi downloaders... Just gets teadious

**Comment by galli-leo** [comment]
Yeah but most of those work slightly differently on Radarr (e.g. All newznab indexers) so not really feasible.

**Comment by onedr0p** [comment]
@thezoggy set up usually takes 10 minutes and then you are done. If it was something that took 10 minutes everyday we would consider adding it, but once you get past the initial setup, you don't have to worry about it.

**Comment by jeaber** [comment]
Old post sure but this is annoying. Radarr doesnt support multiple versions of media so i have to spin up a radarr deployment for 3d, 4k, and 1080p. Then manually setup custom format tags, multiple indexers, quality settings, multiple profiles, and multiple downloaders that many times.

**Comment by thezoggy** [comment]
its now a 2min setup with radarr-sync
https://github.com/Sperryfreak01/RadarrSync
