### ISSUE TITLE
Drone Factory Interval

### ISSUE THREAD

**Issue by thezoggy** [Radarr/Radarr#477]
By default this is set to 1, but the factory folder isnt set.. thus it kicks off every 1 min to fail. 
Should default to 0 so its disabled. That way the user can set the folder+interval at the same time.

**Comment by thezoggy** [comment]
also to note, that form element can have negative numbers set... but 0 is the lowest.. thus adding `min="0"` fixes that... reported to sonarr as well.

**Comment by schumi2004** [comment]
I have drone-factory dir set to a fake dir and set interval to 0, this way it monitors download client and processes it once download is finished. Shouldn't that be the default setting?

**Comment by thezoggy** [comment]
if its monitoring your download client.. you dont need a drone factory (watch folder)... but anyways 0 should be the default interval since by default there is no drone factory set.

**Comment by fedoranimus** [comment]
Fixed by #515
