### ISSUE TITLE
Synology diskstation

### ISSUE THREAD

**Issue by foXaCe** [Radarr/Radarr#478]
Hello it possible to integre synology Download Station please ?

like this

https://github.com/Sonarr/Sonarr/pull/1620

**Comment by schumi2004** [comment]
submit request here pls https://github.com/Radarr/Radarr/issues

Op vr 27 jan. 2017 om 13:35 schreef foXaCe <notifications@github.com>:

**Comment by galli-leo** [comment]
Please post feature requests to http://feathub.com/Radarr/Radarr
