### ISSUE TITLE
Spotweb support

### ISSUE THREAD

**Issue by mbnn** [Radarr/Radarr#479]
While spotweb support works fine (Newznab custom) in Sonarr, it doesnt in Radarr:

NzbDrone.Core.Indexers.Newznab.NewznabException: Missing parameter
  at NzbDrone.Core.Indexers.Newznab.NewznabRssParser.PreProcess (NzbDrone.Core.Indexers.IndexerResponse indexerResponse) [0x000d4] in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\Newznab\NewznabRssParser.cs:45 
  at NzbDrone.Core.Indexers.RssParser.ParseResponse (NzbDrone.Core.Indexers.IndexerResponse indexerResponse) [0x0000d] in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\RssParser.cs:50 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].FetchPage (NzbDrone.Core.Indexers.IndexerRequest request, IParseIndexerResponse parser) [0x00008] in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:297 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].TestConnection () [0x0000e] in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:323 
Close

Invalid request Validation failed: 
 -- Unable to connect to indexer. Missing parameter
Close

This is what spotweb does to 'emulate' newznab support:
https://github.com/spotweb/spotweb/wiki/Spotweb-als-Newznab-Provider

**Comment by galli-leo** [comment]
Does spotweb support the RSS feed?

**Comment by mbnn** [comment]
It should yes, it works with Sonarr so.

**Comment by galli-leo** [comment]
Well the error given says that a parameter is missing. What parameters does the RSS feed need with Spotweb?

**Comment by mbnn** [comment]
I have no idea, the only thing I could find is this: https://github.com/spotweb/spotweb/wiki/Spotweb-als-Newznab-Provider

**Comment by MrSabel** [comment]
A newznab url should look like this:
`http://localhost:7878/api?t=movie&cat=2000,2040&extended=1&apikey=API_KEY&imdbid=1860357`

imdb must be stripped to = 1860357

**Comment by onedr0p** [comment]
@mbnn any chance i could test it out using your spotweb URL? I can fix this but I am not looking forward to setting up the server.

**Comment by mbnn** [comment]
'Unfortunately' I have removed spotweb as it was completely not useable for me anymore. Sorry.

**Comment by ZeroZorro999** [comment]
@onedr0p would you be so kind to have a look at this again, cause i would like to use my spotweb for Radarr :-) and probably more people are....

**Comment by p0nt** [comment]
I would love to have this supported as well, I am able to grant you access to mine if you like.

**Comment by the-darkvoid** [comment]
When using spotweb in movie searching move, it always requires an "imdbid" parameter.

A working query for "Suicide Squad" would be:
/spotweb/api?t=movie&imdbid=1386697&apikey=xxx&extended=1

@onedr0p: Hopefully this additional parameter "imdbid" can be implemented in Radarr? This should make Spotweb work.

P.S. Specific code in question in Spotweb:
https://github.com/spotweb/spotweb/blob/master/lib/page/SpotPage_newznabapi.php#L204

**Comment by onedr0p** [comment]
@p0nt Please get ahold of me on Discord sometime and give me the info. Thanks.

**Comment by p0nt** [comment]
Tried adding you but it seems to need a 4 digit tag or something? i've never used it before

**Comment by onedr0p** [comment]
You can find me in the radarr discord channels

**Comment by AlphaVortex** [comment]
@onedr0p I am having the same issue with Spotweb retrieves. If you'd like me to do any testing please let me know!

**Comment by onedr0p** [comment]
You guys may want to update to the latest spotweb, they just added support for movies.

https://github.com/spotweb/spotweb/pull/274

**Comment by AlphaVortex** [comment]
That seems like it did it! I will report back if I find anything, but so far so good. Thanks!

**Comment by p0nt** [comment]
connection is indeed working, but it is not working very well because it is not taking any nzb's from it while it has multiple releases available for multiple movies in my watch list.

**Comment by p0nt** [comment]
this works:
http://localhost/api?t=movie&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060&extended=1&apikey=8dbc8974b98d1038e90f8938aca6c1a8&offset=0&limit=25

the following does not work:
http://localhost/api?t=movie&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060&extended=1&apikey=8dbc8974b98d1038e90f8938aca6c1a8&offset=0&limit=25&imdbid=3640424

**Comment by p0nt** [comment]
I have found the issue, cat 2060 does not work.

After removing 2060 from SpotPage_newznabapi.php in spotweb it works:

http://imgur.com/a/0ic4T

**Comment by AlphaVortex** [comment]
I can confirm category 2060 is an issue. For now using only 2000 seems to be working for now. We should probably report this to the Spotweb guys since it looks like an issue with their API.

**Comment by p0nt** [comment]
I have already made a issue for that which can be found here:

https://github.com/spotweb/spotweb/issues/278

also I can confirm all categories work except 2060, so you can keep the rest but not 2060.

**Comment by p0nt** [comment]
FYI you can just leave out 2060 from the categories and everything will work.

**Comment by mesa57** [comment]
Btw, radarr should only use newznab category's when calling spotweb which are reported via the t=caps

**Comment by Zignature** [comment]
I'm using nzbstars.com as a Spotweb server. This also works fine in Sonaar but won't work in Radarr :(

**Comment by onedr0p** [comment]
They need to update spotweb.

**Comment by Zignature** [comment]
Thought so :)

**Comment by mesa57** [comment]
Sites like nzbstars or nzbserver hardly do.

**Comment by Zignature** [comment]
Guess I'll have to set up my own Spotweb server...
