### ISSUE TITLE
 "Automatically rename Folders" option in aphrodite

### ISSUE THREAD

**Issue by gitowok** [Radarr/Radarr#4791]
After some discussion in this issue:
https://github.com/Radarr/Radarr/issues/3969
it seems like the ability to automatically rename folder after download was removed.  Is there a way to get this functionality currently?

For example, I'm using '{Original Title}'  as my folder format.  I have an existing folder:
Bat.21.(1988).DVDRip.XviD-WR

Radarr then finds and downloads: Bat.21.1988.BluRay.1080p.FLAC.2.0.AVC.REMUX-FraMeSToR

As it stands now, Radarr puts the new movie into the DVDRip folder, and doesnt rename it.

![Screenshot_2020-08-01 Bat 21-Radarr](https://user-images.githubusercontent.com/2197441/89093650-e5d77000-d3ee-11ea-8884-e2ca7d865fa8.png)

Thanks guys.

**Comment by Qstick** [comment]
Negative, we don't plan to support dynamic tokens in folder naming anymore.

**Comment by gitowok** [comment]
When a movie is manually moved currently, aphrodite currently informs that it will be renamed at the same time. It seems like this would be a checkbox feature to implement - apply this same code to when the movie is moved from downloader to final destination.

I'm talking about in  frontend/src/Movie/MoveMovie/MoveMovieModal.js line 52:
` {
            destinationRootFolder ?
              <div>
                This will also rename the movie folder per the movie folder format in settings.
              </div> :
              null
          }`

Could we not just apply this same function?

**Comment by ta264** [comment]
We spent a long time discussing this. I'm afraid it's not going to happen.

**Comment by gitowok** [comment]
ok. I guess i need to get used to the idea that I'm going to have to do a full rename to fall in line with this narrowing of flexibility. I do understand the reasoning and can appreciate how this makes the code neater and easier to understand. Thanks for your fast response.
