### ISSUE TITLE
Expand Illegal Characters list to be Unix/Linux-friendly

### ISSUE THREAD

**Issue by pieterhelsen** [Radarr/Radarr#4792]
**Is your feature request related to a problem? Please describe.**
I have to manually rename quite a lot of files on my Linux filesystem since Linux dislikes special characters such as '[', ']', '|', '$', etc. 
Not only does it look untidy, it also complicates navigating to or using the file path. 

Below screenshot demonstrates this. Note especially the quotes around escaped filenames (or folders) and the behavior displayed when trying to perform operations on the filenames.

![Linux File Naming Policy](https://user-images.githubusercontent.com/783448/89099801-1ff64100-d3f2-11ea-8b79-5bd94dc7bc0a.png)

**Describe the solution you'd like**
I would like to include the following in the list of characters behind the 'Replace Illegal Characters' implementation:

- ' (single quote)
- " (double quote)
- < > (angle brackets)
- [  ] (square brackets)
- { } (curly brackets)
- | (pipe)
- ; (semicolon)
- : (colon)
- & (ampersand)

**Describe alternatives you've considered**

- Add a new text field to the 'Media Management' > 'Movie Naming' section (advanced settings) that allows the user to input a comma-separated list containing the characters to be omitted from the filename.

**Comment by ta264** [comment]
In my opinion this isn't really necessary - if you really want to navigate the files manually just use tab completion which should make dealing with the special characters less annoying.  I'm not sure why you need to rename the files since Linux filesystems escape them perfectly well?

**Comment by kelnos** [comment]
I sort of have the opposite issue here, I guess: looks like Radarr considers colon an invalid character (I guess because it is on Windows?), but it's fine on Linux, and quite a few movie titles have colons in them, and I'd want to keep them that way.

**Comment by bakerboy448** [comment]
There’s a setting to toggle what to do with colons

**Comment by kelnos** [comment]
> There’s a setting to toggle what to do with colons

Right, but the only options involve deletion or replacement.  I want an option to leave them alone.  I guess for now I'll just disable illegal character replacement entirely, which isn't ideal.

**Comment by bakerboy448** [comment]
it's still best practice to not use colons even on linux...it eventually causes some issues.

Why do you require colons on your file names/folders?

**Comment by austinwbest** [comment]
> > There’s a setting to toggle what to do with colons
> 
> Right, but the only options involve deletion or replacement. I want an option to leave them alone. I guess for now I'll just disable illegal character replacement entirely, which isn't ideal.

Dont think allowing it will happen bud. Upstream replaces them without any option, the difference being radarr gives the option of what to replace it with (which you wont get upstream).

Upstream:
Series:Title > Series-Title
Series: Title > Series - Title

To change the behavior to allow them would then require also keeping track of only allowing for when it is a valid character. Then you also have to take into account if one was to move from a system where it is allowed to one where it isn't. It is handled across the board in the easiest manner possible for a reason. 

Disabling the replace wont leave them either, they will then just be removed outright.

Radarr's naming scheme will stay in line for consistency with upstream options unless there is a really good reason to deviate from it (not even sure about then but that is situational) at which point it would be discussed for the situation.
