### ISSUE TITLE
Improve Parsing of Spanish Language Releases

### ISSUE THREAD

**Issue by tulkarxxx** [Radarr/Radarr#4793]
**Describe the bug**
Hi, language is always picked as english from indexers, I am using jackett. See picture
![image](https://user-images.githubusercontent.com/66320480/89100616-c5acae80-d3f8-11ea-90f2-3bfa86620736.png)

I have tried with radarr v2 and v3
**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform Information (please complete the following information):**
 - OS: [e.g. Windows]
 - Mono Version: [e.g. Mono 5.8] (Only needed under Linux and Mac, found under System -> Status)
 - Browser and Version [e.g. chrome, safari] (Only needed for UI issues)
 - Radarr Version [e.g. 3.0.0.2956]

**Debug Logs**
Turn on debug logs under Settings -> General and wait for the bug to occur again. **Upload the full log file here (or another site and link it). Issues will be closed, if they do not include this!**

**Comment by ta264** [comment]
Please post trace logs of parsing the releases

**Comment by tulkarxxx** [comment]
[radarr.trace.txt](https://github.com/Radarr/Radarr/files/5010354/radarr.trace.txt)

**Comment by Qstick** [comment]
Issue will be we don't parse esp as Spanish

**Comment by austinwbest** [comment]
ISO language codes are ES & SPA if I recall. Dunno if the parser uses any kind of structure like ISO though..

**Comment by Qstick** [comment]
No, it doesn’t really follow iso because none of the release groups do. For Spanish right now we only code if the movie is originally a Spanish movie or if “Spanish” is called out in title.... it’s not as refined as some of the other languages in terms of detection

**Comment by Qstick** [comment]
Seems there are alot of releases that use ESP, but that don't indicate spanish. So changing behavior will cause others to be incorrect.

Ex: 
The Glimmer Man 1996 720p BluRay ESP DTS x264-MaG-Obfuscated - English Audio

**Comment by jasimancas** [comment]
Same error here:
![image](https://user-images.githubusercontent.com/15717847/90658177-87f6b500-e243-11ea-8fcd-3e652b34e721.png)

**Comment by austinwbest** [comment]
Bad naming by the uploader. The language does not go in brackets at the end. Proper naming leads to proper detection as also shown in your screen shot with the 2 below.

**Comment by jasimancas** [comment]
Is it possible to force the language of the indexer?
Or is there a solution for the HacheDe indexer to allow Spanish language?

**Comment by austinwbest** [comment]
I can tell you nothing should be done for uploaders putting language in brackets at the end.

**Comment by jasimancas** [comment]
Logically that will not work, since in the indexer all files are uploaded the same.

But in this case: Memorias De Una Geisha (2005) [BDRip 1080p x265 _**AC3(ES/EN)**_ Subs(ES/EN)] [spanish]

This is the language of audio, can't radarr parse that?

**Comment by ta264** [comment]
This is Jackett being silly and blanket appending `[spanish]` to all titles. Something more sensible should be done in jackett I think.

**Comment by jasimancas** [comment]
In that case, is it possible to reach a consensus between Jackett and Radarr that the last parameter is the right one?

How should the string be passed? SPANISH at the end?

**Comment by ta264** [comment]
Really it shouldn't be at the end, the standard is that the group goes at the end afaik

**Comment by jasimancas** [comment]
Work in others providers with [spanish]
![image](https://user-images.githubusercontent.com/15717847/90730576-a226a680-e2c8-11ea-90d3-3ec9786eb39f.png)

**Comment by moralia** [comment]
> Work in others providers with [spanish]
> ![image](https://user-images.githubusercontent.com/15717847/90730576-a226a680-e2c8-11ea-90d3-3ec9786eb39f.png)

que versión usas de Radarr ? a mi no me sale como a ti y tengo problemas con los titulos e idioma. gracias !

**Comment by tulkarxxx** [comment]
Afrodita

**Comment by bakerboy448** [comment]
sounds like a non-issue in radarr.... jackett + uploader caused
