### ISSUE TITLE
Release Rejected: Failed to map movie

### ISSUE THREAD

**Issue by almottier** [Radarr/Radarr#4794]
**Describe the bug**
Release is rejected with correct alternative movie title.

**To Reproduce**
...

**Expected behavior**
Check releases names with all AKA movie titles

**Screenshots**
<img width="1054" alt="Screenshot 2020-08-01 at 13 57 41" src="https://user-images.githubusercontent.com/5426740/89101379-98173380-d3ff-11ea-9475-ad9014c1a1d1.png">

**Platform Information (please complete the following information):**
 - .0.0.3327-ls17 by linuxserver.io aphrodite

**Debug Logs**
[log.txt](https://github.com/Radarr/Radarr/files/5011853/log.txt)

**Comment by Qstick** [comment]
Need the logs

**Comment by almottier** [comment]
I added the logs.
