### ISSUE TITLE
VIDEO_TS directory or .ISO shows as Missing

### ISSUE THREAD

**Issue by chr55** [Radarr/Radarr#480]
Some of my movie folders contain only a VIDEO_TS directory containing the movie rip.

example:
Movie Name (YEAR)\VIDEO_TS\

Radarr does not recognize the movie and so it shows as Missing in the UI. 

This also happens when my movie folder has an .ISO file in it containing the movie.

**Comment by fedoranimus** [comment]
Radarr only supports the format `Movie Folder\MovieFile.format`. .ISO files are not movie files, so Radarr will not recognize them.

**Comment by schumi2004** [comment]
Could we make it so that Radarr at least shows some files are there as for example unknown? With a lot of movies it's sometimes hard to remember if you have the movie or not although media can't be read by Radarr.
