### ISSUE TITLE
Move Files instead of Copy the Delete

### ISSUE THREAD

**Issue by almulder** [Radarr/Radarr#4813]
I have noticed that once a file is downloaded from a download client (NZBs) the file is copied to its movie folder location, and once the copy is finished the file is then deleted from the download client folder, Can we get an option to move rather than copy the file and then delete. This would speed things up and reduce writing on the drives

**Comment by ta264** [comment]
Radarr does this if you set it up so that it's possible

**Comment by almulder** [comment]
How? I have checked the options and dont see any options

**Comment by ta264** [comment]
It does it automatically if it's possible. Join the discord if you need more assistance.
