### ISSUE TITLE
Brazilian Portuguese for metadata, radarr displays only Portuguese from Portugal

### ISSUE THREAD

**Issue by Havokdan** [Radarr/Radarr#4815]
Brazilian Portuguese for metadata? Radarr displays only Portuguese from Portugal. Example:

https://www.imdb.com/title/tt0399146/?ref_=fn_al_tt_1

Original name: A History of Violence
Portugal name:  Uma História de Violência
Brazilian name: Marcas da Violência

Not to mention that all other content comes from the wrong language.

**Comment by Qstick** [comment]
Dupe of #1626
