### ISSUE TITLE
[Feature Request] - Add delete button on movie listing page (or add poster on Movie Editor page)

### ISSUE THREAD

**Issue by jeanfrancoislarente** [Radarr/Radarr#4817]
When using the lists feature where movies are automatically added, some unwanted movies (personal preference) end up in your main movie list.

Currently you can filter by all unwatched movies in the movie list to choose which ones you want to delete but you need to click on the gear icon to get to the delete button if you don't want to see it in your list.

To bulk edit, you have the option of using the Movie Editor but it's more difficult to figure out which movie you're looking at (or if you're interested in it) when you can't see the poster.

It would be great to either: have the Delete button on the movie listing page OR see the movie poster in the Movie Editor. To keep the Movie Editor clean/crisp I think option #1 is better.

**Comment by Qstick** [comment]
Editor is reworked in v3, you can filter and view same as index
