### ISSUE TITLE
Add an rTorrent label change option

### ISSUE THREAD

**Issue by omoorej** [Radarr/Radarr#4828]
Is it possible to get an option to change an rTorrent label after import, similar to Sonarr's?

I understand you cannot remove post-processed torrents, but if they could be re-labelled it would make it a lot easier to manually identify and remove them through RuTorrent.

**Comment by austinwbest** [comment]
I do this in qbt with a post process script after import. Just use the hash and the api to update it. Not to say it couldn't be added to radarr but giving you an option that could be done now VS waiting :)

**Comment by Qstick** [comment]
Already in v3

![9EFC6C51-B898-4770-A5B5-D68E83C70115](https://user-images.githubusercontent.com/376117/99921539-0195b780-2cf9-11eb-9dc2-d04f7651797f.jpeg)
