### ISSUE TITLE
High CPU load when toggling monitored state in "Wanted" menu.

### ISSUE THREAD

**Issue by MLWeber** [Radarr/Radarr#4837]
**Describe the bug**
When selecting a high number (30-50) of unmonitored movies in the "Wanted" menu and clicking "Toggle Selected", the CPU load increases to 800% on my i7-8700 for up to five minutes until all movies are set to monitored. It takes unproportionally longer the more movies I select. I am not sure what happens in the background but I feel like setting a few movies to monitored shouldn't be that hard on the CPU. Can this be optimized?

**To Reproduce**
1. Go to 'Wanted'
2. Filter by 'Unmonitored Only'
3. Select 30+ movies
4. Click on "Toggle Selected"
5. Observe high CPU load

**Platform Information (please complete the following information):**
 - OS: CentOS 7
 - Mono Version: 5.20.1.34
 - Radarr Version: 0.2.0.1504

**Debug Logs**
https://pastebin.com/3t3QRNZv

**Comment by ta264** [comment]
I suspect this is fixed on v3. If you're feeling brave try V3 and if it's still broken we can reopen.
