### ISSUE TITLE
TMDB List Import Upcoming not working

### ISSUE THREAD

**Issue by silv3r23** [Radarr/Radarr#4842]
While I am wondering no new movies where added since a while I checked my List Import and notices that TMDB Upcoming fails. Could it be fixed soon or provided a workaround?

Error:
![image](https://user-images.githubusercontent.com/28316411/89730115-33ca2480-da3c-11ea-8de9-c47b4e3bae9c.png)

Log: 
![image](https://user-images.githubusercontent.com/28316411/89730109-20b75480-da3c-11ea-9df7-7f8580b48ea0.png)

Settings to reproduce:
![image](https://user-images.githubusercontent.com/28316411/89730126-43496d80-da3c-11ea-9f61-87ceff25b278.png)

List Types "Popular", "Theaters" and "Top" work

https://www.themoviedb.org/movie/upcoming?language=de shows some movies

version: 0.2.0.1504

**Comment by ta264** [comment]
Hmm not sure what the issue is but I don't think it qualifies as serious enough to fix in 0.2, which is now critical fixes only.

If you join the discord channel someone might be able to help you with a workaround

**Comment by Qstick** [comment]
There is a difference in original language set to German in the list and your query to TMDb with language=de. Original language in the list means I only want movies that were originally German movies.... language=de means show me results in German language (but still return every movie)

**Comment by silv3r23** [comment]
I set the Original Language to en that seems to work.
Am I understanding right, as Original Language cannot be ignored/leaved blank, I need multiple Import Lists e.g. 1 for en, 1 for fr, 1 for de (which is broken, my workaorund is use "In Cinemas" instead "Upcoming"), 1 for nl... and so on?
