### ISSUE TITLE
Add option for movie nfo-file for only IMDB-url so that other scrapers can do their things better! 

### ISSUE THREAD

**Issue by Paelsmoessan** [Radarr/Radarr#4845]
Header says it all.

**Comment by Qstick** [comment]
It’s already an option, turn on advance and it’s under kodi metadata (at least on v3)

**Comment by Paelsmoessan** [comment]
Is the version available on windows?

**Comment by ta264** [comment]
yes

**Comment by Paelsmoessan** [comment]
In that case I need an updated installation guide.

**Comment by bakerboy448** [comment]
You don't. V3 (aka **aphrodite**) is currently in alpha and is intentionally hard to locate.
The simple solution would be to change your release channel if you can. Or check the aphrodite discord for other options.

**Comment by Paelsmoessan** [comment]
Ok thanks!
