### ISSUE TITLE
Shutdown button no longer works

### ISSUE THREAD

**Issue by StevePearson-AIT** [Radarr/Radarr#4847]
On the System Tab there are two buttons, one for Shutdown and one for Restart. The Shutdown Button does not work. It reports in the log that a shutdown has been requested but then appears to do a restart instead.
This is happening in build 0.2.0.1504
This worked correctly in build 0.2.0.1480

**Platform Information (please complete the following information):**
 - OS: Windows 10 version 2004 (also occurs in version 1909)
 - Chrome Version 84.0.4147.105 (Official Build) (64-bit)
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/5053734/radarr.debug.txt)

Log shows shutdown request at 23:25:08

**Comment by ta264** [comment]
I imagine your service script is starting it up again. In any case I don't think we'll be doing anything to fix this is 0.2 since it is approaching end of life.

**Comment by StevePearson-AIT** [comment]
I don’t have any scripts to restart it. The only change was the version upgrade!
I do however accept that 0.2 is nearing EoL, and just wanted to make you aware of this issue really.

**Comment by bakerboy448** [comment]
Closing
v0.2 is no longer being actively developed.

If this is still an issue on **recent** v3 builds, please open a new issue.
