### ISSUE TITLE
Allow Quality >400MB/m

### ISSUE THREAD

**Issue by StevenAston** [Radarr/Radarr#4849]
**Is your feature request related to a problem? Please describe.**
The current max of 400MB/m caps a 2 hour movie at 47GB. A lot of movies, especially in 4K HDR, will fall somewhere between 40-80GB. I know there's the option to not download anything over x size but that sometimes stops results for very long movies from being snatched. Conversely sometimes an overly large file will be snatched if set to "Unlimited". I know that, personally, my network doesn't really like anything over ~600MB/m so I'd like to be able to just set it to that and not worry about it.

**Solution**
Upping the limit from 400MB/m to 690 or 1080MB/m to encompass the entire UHD-BD spec would be ideal, or allowing a user to enter their own max value or enable / disable the "Unlimited" option.

**Describe alternatives you've considered**
I've tried messing around with limiting file size on the indexer side etc but it doesn't seem to work well.

**Additional context**
None, but thank you for the excellent work on a great program!

**Comment by bakerboy448** [comment]
This exists in v3 and I believe under advanced options this also exists in V2.  You can edit your quality sizes.

**Comment by lightmaster** [comment]
When I edit the database to allow a max 2160p of 682.2 MB/min (40GB/hr), the UI does update to reflect this, however the manual search screen still says `42.2 GB is too big, maximum size is 25.0 GB` this is for a roughly 2 hour movie, so max allowed should be 80GB

**Comment by bakerboy448** [comment]
Default ( I believe) is unlimited...presumably they're set like that for a reason...
![image](https://user-images.githubusercontent.com/55419169/94710603-a359e300-030c-11eb-95a7-5a4e2d3d2f92.png)

**Comment by lightmaster** [comment]
Look to the right on your pic, "unlimited" means a max of 400MB/s which is too small for UHD HDR 4K content. Also, I get the same error with "unlimited" as I do with 682MB/s

**Comment by bakerboy448** [comment]
Do you have the trace logs of a movie that exceeds that or a movie/release to share so we can see what's up?  
This sounds more like a bug than a feature request...

For example this is my largest movie and is no issue..
![image](https://user-images.githubusercontent.com/55419169/94711734-1f085f80-030e-11eb-8a21-dffc2f780bc5.png)

**Comment by austinwbest** [comment]
It's not just the size as a factor, it is size per minute (or hour) and that is a 3+ hour movie

**Comment by lightmaster** [comment]
> Do you have the trace logs of a movie that exceeds that or a movie/release to share so we can see what's up?
> This sounds more like a bug than a feature request...
> 
> For example this is my largest movie and is no issue..
> ![image](https://user-images.githubusercontent.com/55419169/94711734-1f085f80-030e-11eb-8a21-dffc2f780bc5.png)

I'll get a trace log soon as I can.

**Comment by Qstick** [comment]
Sounds like you have the max size override setting enabled given its telling you 25gb on the nose

**Comment by lightmaster** [comment]
> 
> 
> Sounds like you have the max size override setting enabled given its telling you 25gb on the nose

Well, I've had my idiot moment for the day...

Please disregard everything else I've said on this, everything seems to be working now.
