### ISSUE TITLE
Movies not updating as downloaded and updates not working

### ISSUE THREAD

**Issue by sabmmtv** [Radarr/Radarr#485]
movies even if they are downloaded show as missing , need to manually show the location of the movies as I get this error:

Import failed, path does not exist or is not accessible by Radarr.... but if I manually point it, it works

updates do not work : get this message 

Update process failed: Your Radarr configuration 'C:\ProgramData\Radarr' is being stored in application folder 'C:\ProgramData\Radarr' which will cause data lost during the upgrade. Please remove any symlinks or redirects before trying

Please use the search bar and make sure you are not submitting an already submitted issue.

Provide a description of the feature request or bug, the more details the better.
When possible include a log!

Please use our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by galli-leo** [comment]
What os are you on? You cannot directly extract the release into your ProgramData\Radarr folder. You have to create a subdirectory (e.g. Bin) and extract it there.

**Comment by onedr0p** [comment]
This is a duplicate.
