### ISSUE TITLE
Radarr won't update with multiple instances running

### ISSUE THREAD

**Issue by andrsm** [Radarr/Radarr#4850]
**Describe the bug**
Radarr won't update with multiple instances running. When I try to update with two instances running at the same time Radarr won't update. If I shut down one instance the other updates fine.

**To Reproduce**
As far as I can tell having two instances running causes error when updating

**Expected behavior**
Update and restart Radarr with new version

**Platform Information (please complete the following information):**
 - OS: Ubuntu 20.04
 - Mono Version: net core version
 - Radarr Version: 3.0.0.3388

**Debug Logs**
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/5058123/radarr.debug.txt)
[radarr.update.log](https://github.com/Radarr/Radarr/files/5058122/radarr.update.log)

**Comment by bakerboy448** [comment]
closing....sounds like it is fixed with a easy workaround?

also running multiple instances here and no issues with updates

**Comment by andrsm** [comment]
Hi. I still run into this problem. Have to shut down all but one instance of radarr for it to update. Same error as in OP

**Comment by andrsm** [comment]
So I tried renaming one of the radarr instances to radarr2 and running the service as
ExecStart=/opt/amb/Radarr/Radarr2 -nobrowser -terminateexisting

It then updates fine. Problem is that when it updates the file is of course renamed back to just radarr.
But it defiantly seems like the problem is that the updater can't differentiate the two instances running when the name is the same. Maybe we need to kill process with ID instead of name?

You can see in the log file how it updates, but fails when attempting to restart the process
[2020.11.22-10.38.txt](https://github.com/Radarr/Radarr/files/5579323/2020.11.22-10.38.txt)

**Comment by bakerboy448** [comment]
@andrsm how are you running both instances?

What seems to work without issue is:
- run all instances using the same binaries, simply change the data paths and service names
- turn off auto updates for all but one instance

I've been running this for awhile now without any issues using standard systemds

**Comment by bakerboy448** [comment]
IS this still occuring in 3.0.2?  The key is to do what I mentioned.

**Comment by bakerboy448** [comment]
Closing; can reopen if needed; never heard from OP RE 4/17 comment

- if more than one instance is running, all instances need a `-data` argument
- only 1 instance should have auto update enabled
