### ISSUE TITLE
Incorrect Parsing of AudioChannels from MediaInfo

### ISSUE THREAD

**Issue by Qstick** [Radarr/Radarr#4852]
Currently Radarr uses `Audio_Channel(s)` and `Audio_ChannelPositionsText\String2`  for parsing audio channel layout from mediainfo. As found by @rg9400 this is inconsistent and often incorrect as we are looking at container metadata instead of the actual stream values. 

Per Mediainfo dev:
```
In your tool, you check if the value from the stream, if it is empty you take the one from the container (empty means same value as container): check if "Channel(s)_Original" exists", if yes use this value else use "Channel(s)" value.
```

Ref: https://sourceforge.net/p/mediainfo/feature-requests/413/

Rework mediainfo parsing to look at stream values prior to defaulting back to container metadata. Also need to test and see how that impacts the file read and how much of the file we are looking at during parse to ensure its not slowing down metadata read.

**Comment by rg9400** [comment]
![image](https://user-images.githubusercontent.com/39887349/89971657-7ef15c80-dc21-11ea-8702-f1ffbacfb2e8.png)

Here's an example where the two fields differ. `Audio_ChannelPositionsText\String2` cannot be parsed in these cases, so maybe we need to look at some other fields like `Audio_ChannelPositions_Original` or `Audio_Channel_Layout`/`Audio_Channel_Layout_Original`.

Worth noting that the PCM codec has no data outside of `Audio_Channel(s)`. In my library of 2k movies, only 15 movies had this codec. Out of these, 7 are being parsed as `0.0` in Radarr. Please refer below screenshot of the fields we have been discussing. I am not sure why Radarr parses this as `0.0`, which should probably not be a realistic channel count anyways unless the movie was fully silent. I do have some PCM movies coming as `1.0`, but the fields look the exact same as below. PCM is the only culprit for these `0.0` channel counts.

![image](https://user-images.githubusercontent.com/39887349/89971849-faeba480-dc21-11ea-88ff-892c01befae1.png)
