### ISSUE TITLE
Feature request: Customize On Grab/Download/Upgrade/Rename messages

### ISSUE THREAD

**Issue by Backspaze** [Radarr/Radarr#4871]
**Is your feature request related to a problem? Please describe.**
I've began using Trakt instead of IMDb but the link in the Radarr message always refer to IMDb, so instead of just clicking the link I have to manually search for it in Trakt.

**Describe the solution you'd like**
I'd like to be able to customize the contents of the message, especially for the URL for the movie in question to point to my service of choice instead of the default IMDb.

**Comment by austinwbest** [comment]
You should look into the custom script, that is the purpose of it :) you can do whatever you like with the data. Another option is a different notification type but it is unlikely that personal customization will be added in radarr, would lead to way too many requests and would have to be done to all the choices.

**Comment by Backspaze** [comment]
Yes, I've already taken a look at it and deemed it to be a fair bit above my knowledge when it comes to scripting, but I guess I'll have to dig in and see what can be done. Scripting something that basically sends the exact same message as Radarr already does but with the IMDb link replaced with a Trakt link shouldn't be **too** difficult right?

I don't see any variable for Trakt [here](https://github.com/Radarr/Radarr/wiki/Custom-Post-Processing-Scripts) though, there only seems to be variables for IMDb and TMDB, so I'll guess I'll have to use those to somehow lookup the Trakt URL?

As you point out adding customization for this might not be feasible because of the reasons you mention, but just to make it clear what I'm asking for with this feature request, so we're on the same page, I've provided a mockup screenshot below. I don't know enough about coding to know how much work it would be to implement and maintain that feature, and I don't know if there's any demand for it or if mine is just an edge case.

![bild](https://user-images.githubusercontent.com/12255362/90344652-f22d1100-e01b-11ea-98af-ec2ddc27f17a.png)

**Comment by austinwbest** [comment]
Yes, i understood what you where asking for. It is very unlikely simply because there would be no end to customizing and things would have to be done for all connection types. Again, anything beyond the preset can fall back to custom scripts. To get your trakt URL you would use the TMDb id

trakt.tv/search/tmdb/{tmdb_id_here}?id_type=movie

This is the same way the UI handles the external trakt link :)

**Comment by Backspaze** [comment]
Ok, thanks for the update and the info about the trakt URL. Unless someone else who has yet too see this issue and might be sitting on a custom script that might solve my issue, I think we can go ahead and close this. I'll try Reddit and Discord if I need further help with creating a custom script.

**Comment by Qstick** [comment]
I'm going to keep this open, as it's something I want to do. But not in 3.0

**Comment by Qstick** [comment]
Dup #1809
