### ISSUE TITLE
Radarr API V3 addExclusion (bool) doesn't work when using V3 API

### ISSUE THREAD

**Issue by luluhoc** [Radarr/Radarr#4884]
**Describe the bug**
Just wanted to let you know thataddExclusion (bool) doesn't work when using V3 API when using old API it works normally.

**To Reproduce**
make an API DELETE MOVIE Request https://xxxx.com/api/v3/movie/2080?deleteFiles=true&addExclusion=true
**Expected behavior**
Movies are not added to the exclusion list.

**Screenshots**

**Platform Information (please complete the following information):**
 - OS: [e.g. Windows] DOCKER
 - Radarr Version 3.0.0.3064
-  Package Version 3.0.0.3064-ls11 by linuxserver.io

**Debug Logs**
Turn on debug logs under Settings -> General and wait for the bug to occur again. **Upload the full log file here (or another site and link it). Issues will be closed, if they do not include this!**

**Comment by Qstick** [comment]
Please add the information requested on the template.

**Comment by luluhoc** [comment]
> Please add the information requested on the template.

Done

**Comment by Qstick** [comment]
Update Radarr, you are 400 builds behind

**Comment by Qstick** [comment]
Also, your api call is mixed up

https://xxxx.com/api/v3/movie/2080?deleteFiles=true&addExclusion=true

Not 

https://xxxx.com/api/movie/v3/2080?deleteFiles=true&addExclusion=true

**Comment by luluhoc** [comment]
> Also, your api call is mixed up
> 
> https://xxxx.com/api/v3/movie/2080?deleteFiles=true&addExclusion=true
> 
> Not
> 
> https://xxxx.com/api/movie/v3/2080?deleteFiles=true&addExclusion=true

This was just Github mistype I was making requests to correct URL. I updated it to 3.0.0.3423.  The problem still persists.

**Comment by bakerboy448** [comment]
Logs?

**Comment by Qstick** [comment]
I made an edit, look again, you are using the wrong parameter

**Comment by luluhoc** [comment]
> I made an edit, look again, you are using the wrong parameter

Oh, with this parameter it works, It wasn't written in API docs :)

Thanks

**Comment by Qstick** [comment]
It’s right on the v3 docs https://radarr.video/docs/api/#/Movie/deleteMovie

**Comment by luluhoc** [comment]
> It’s right on the v3 docs https://radarr.video/docs/api/#/Movie/deleteMovie

Oh, that's right I was looking at the docs on github

**Comment by Qstick** [comment]
But heads up it’s going to change again soon, with the rename of netimport
