### ISSUE TITLE
Defect: Sort order by Date added not behaving properly

### ISSUE THREAD

**Issue by eltanque** [Radarr/Radarr#4886]
When opening radarr on my browser, I've by default (my last view used) the movies view, as a table, sorted by Date Added, descending (more recent on top).
but the list is not sorted descending. I need to click on the sort order and then click again to have it sorted as expected.

**Radarr Version:** Version 0.2.0.1504
Windows 10 Pro OS Build 19041.450 (latest) 64 bit
Chrome OS browser Version 84.0.4147.125 (Official Build) (64-bit)

**Comment by ta264** [comment]
We're no longer fixing minor bugs in 0.2. if it's a major issue for use try (the alpha but almost beta) v3

**Comment by eltanque** [comment]
Would v3 update my install automatically?
