### ISSUE TITLE
Movie Folder Format doesn't allow recently added format {Movie Title:JP|FR}

### ISSUE THREAD

**Issue by w1ldg00se** [Radarr/Radarr#4889]
In #4058, the Option "Settings | Media Management | Movie Folder Format" from the web gui was extended to allow a list of languages for the Movie Title in the Format "{Movie Title:JP|FR}". 
This format can't be set from the web gui, because it displays the error "Must contain movie title". 
And PLEASE add some documentation for this setting, cause there is no info about this in the "?" button next to the field "Movie Folder Format" nor in the github wiki in the section "Sorting and Renaming".

Hint: The Format "{Movie Title:JP|FR}" is included in the test suite under src/NzbDrone.Core.Test/OrganizerTests/FileNameBuilderTests/FileNameBuilderFixture.cs.

**To Reproduce**
1. Go to the Radarr website
2. Click on 'Settings', then on 'Media Management' and enter the text '{Movie Title:JP|FR} ({Release Year})' in the field 'Movie Folder Format' (and 'Standard Movie Format' if 'Rename Movies' is set).
4. Click on 'Save Changes'
5. Saving not possible because the error 'Must contain movie title' appears next to the field 'Movie Folder Format' (and 'Standard Movie Format' if 'Rename Movies' is set).

**Expected behavior**
'Save Changes' should successfully save the new format.

**Platform Information:**
 - OS: Docker linuxserver/radarr:preview (this is running the currently latest commit 76804df from the aphrodite branch)
 - Browser: Vivaldi 3.2.1967.41
 - Radarr Version: 3.0.0.3433

**Debug Logs**
Nothing logged.

**Comment by Qstick** [comment]
I'll look at this, but one thing to note Japanese is JA not JP, so you'll never get a Japanese translation with your format once it's fixed

Also off topic, are you interested in working on the Japanese translation for Radarr UI?

**Comment by w1ldg00se** [comment]
Oh sorry i did choose JP|FR just because it's an example in your tests, actually i want to set it to DE|EN.
And sorry that I'm not interested in translations, i use english on all my apps and operating systems, just my media content is (mostly) in german.
