### ISSUE TITLE
Radarr does not start anymore on linux systems if "ldd" is missing (exception in OSInfo.cs)

### ISSUE THREAD

**Issue by littlemoses** [Radarr/Radarr#4890]
**Describe the bug**
aphrodite - commit 7722c5060397a26a832108c211ca55565c8f71b2 broke radarr on synology systems (recent version wont start / update is impossible). In more detail was happens is that the following code throws an exception if "ldd" is missing:

OSInfo.cs / starting at line 104

        private static bool IsMusl()
        {
            var output = RunAndCapture("ldd", "/bin/ls");     <-- this assumes that "ldd" is always available, which is wrong
            return output.Contains("libc.musl");
        }

        private static string RunAndCapture(string filename, string args)
        {
            Process p = new Process();
            p.StartInfo.FileName = filename;
            p.StartInfo.Arguments = args;
            p.StartInfo.UseShellExecute = false;
            p.StartInfo.CreateNoWindow = true;
            p.StartInfo.RedirectStandardOutput = true;

            p.Start();

            // To avoid deadlocks, always read the output stream first and then wait.
            string output = p.StandardOutput.ReadToEnd();
            p.WaitForExit(1000);

            return output;
        }

My current workaround is to have a "ldd shellscript" in the radarr folder, something like:

#!/bin/sh
echo "fail"
exit 0

will do

**To Reproduce**
 * Use the latest aphrodite version
 * Have a linux system without ldd (or "remove" it temporarily)
 * Start radarr

**Expected behavior**
Radarr starts.

**Platform Information (please complete the following information):**
 - OS: Any Linux without a "ldd" binary
 - Radarr Version 3.0.0.3433

**Comment by Qstick** [comment]
Care to test a fix?

**Comment by Qstick** [comment]
Merging as a temp fix until proper package info implementation
