### ISSUE TITLE
Radarr picking up .ts containers and parsing them as TeleSync

### ISSUE THREAD

**Issue by HitsvilleUK** [Radarr/Radarr#4891]
I have a custom format set up for Dolby Vision as an upgrade to 4K remuxes.
It works fine and Radarr always downloads the file which are all in a .ts container. 
It seems however that on importing that the .ts confuses Radarr into thinking its a Telesync and refuses to upgrade. 
It then moves onto the same .ts format from another group with the same result. 
Any thoughts on this?

**Comment by Qstick** [comment]
Post the rest of the template info, version, logs etc... Everything you wiped out when making this issue
