### ISSUE TITLE
Not recognising movie name in Exact movie name release.

### ISSUE THREAD

**Issue by OFark** [Radarr/Radarr#4894]
**Describe the bug**
Not finding title name in a release that exactly matches the title.

**To Reproduce**
Steps to reproduce the behaviour:
Add the movie The Flight of Dragons

**Expected behaviour**
Releases labelled The Flight Of Dragons to be recognised

**Screenshots**
![image](https://user-images.githubusercontent.com/4558132/90492423-1599ae00-e139-11ea-991a-6978bc951667.png)

**Platform Information (please complete the following information):**
 - OS: UNRAID
 - Version: 0.2.0.1504
 - Mono Version: 5.20.1.34
 - Browser and Version Chrome

**Debug Logs**
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/5089344/radarr.debug.txt)

**Comment by ta264** [comment]
Radarr requires the year in the release name
