### ISSUE TITLE
Small Graphic glitch with GDrive attached

### ISSUE THREAD

**Issue by Horatius314** [Radarr/Radarr#4899]
**Describe the bug**
Location shows as full while it is clearly not.

**To Reproduce**

7 Teamdrives are mounted in unionfs which means 7PB. 

**Expected behavior**

Not show as full

**Screenshots**

https://prnt.sc/u1wh6f

https://pastebin.com/QjqMKjih
The HTLM from that row, might come in handy

**Platform Information (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Mono Version: 3.0.0.3423, that is the radarr version I think but there wasn't a row with mono version.
 - Browser and Version: Hapens on Firefox and Chrome
 - Radarr Version 3.0.0.3423
- Package version aphrodite-b809d69-78 by hotio

**Comment by austinwbest** [comment]
HTML is kinda useless but the trace logs when you click that screen might help.

**Comment by bakerboy448** [comment]
on mergerfs as well.
Issue is the system is reporting the used space as the free space

**Comment by bakerboy448** [comment]
Non-issue (UI only)

it has to do with how the space is being reported.
