### ISSUE TITLE
Add nfo file when movies are upgraded or added

### ISSUE THREAD

**Issue by c0rnflake** [Radarr/Radarr#490]
CP has the option to create an nfo file which included an imdb full url to the movie that had just been added or upgraded.

Kodi would then look for that nfo file and use the containted imdb url to added the movie.

ie.

This.Is.Another.Movie.mkv

then

This.Is.Another.Movie.nfo

Would contain a  http://www.imdb.com/title/tt#######/

**Comment by thezoggy** [comment]
to be proper, nfo generation should not happen when its added but when its processed.
and when original d/ling you should offer to rename the .nfo included with a release to something that wont be mistakenly attempted to be scraped by kodi/plex or something.. since it wont be in the correct format.

**Comment by c0rnflake** [comment]
The CP written nfo file only contains one line with the valid imdb url.

The nfo can't be created when the movie is added as there's no way for radarr to know the filename that's needed until your download client returns that.

**Comment by thezoggy** [comment]
if you were following kodi's nfo guideline you could always just do `movie.nfo` ?
> movie.nfo will override all and any .nfo files in the same folder as the media files if you use the "Use foldernames for lookups" setting. If you don't, then moviename.nfo is used. If there is only one .nfo file in a folder, The scraper will use it for all media files in that folder. If there are multiple media files in a folder, the *.nfo should be named exactly the same as the video file it is representing (ie. moviename.avi and moviename.nfo). 

http://kodi.wiki/view/NFO_files/Movies

**Comment by onedr0p** [comment]
This will be handled in the metadata section on settings when we get that hooked up.

**Comment by ieno** [comment]
Found this issue through Google looking for the same scenario the OP mentioned. Unfortunately, radarr's current metadata section does not seem to offer this particular option of (only) writing the IMDB url to an nfo file. The radarr generated metadata is nice, but Kodi seems to then only rely on this generated metadata even though I have configured a scraper to complement it.

To work around this, I have disabled radarr's metadata generation and am now using the following connect > custom script on download/upgrade to let Kodi scrape all data. Thought I'd share in case anyone else went searching for it:

`#!/bin/sh

MOVIE_PATH=$(echo "$radarr_moviefile_path" | rev | cut -d "." -f2- | rev)
echo "https://www.imdb.com/title/$radarr_movie_imdbid/" > "${MOVIE_PATH}.nfo"`

**Comment by thezoggy** [comment]
the scene nfo is usually not in a format that kodi understands. ideally radarr should take the original nfo and rename it (so its not used but kept if someone wants to refer to it). and then the only .nfo that should exist is the one that radarr generates.
