### ISSUE TITLE
Losing Root Folder in "Add New" window.

### ISSUE THREAD

**Issue by Kedryn** [Radarr/Radarr#4902]
**Describe the bug**
After running for a while, Radarr loses all root paths in the "Add new" window. The "Root folder" path shows only the "\moviename" without the root part. The only way to have root paths back is going to "Import", let Radarr check all root paths configured, then go back to "Add New". At this point, all Root Folders are back and usable.

**To Reproduce**
1) Leave Radarr working for a while (dunno how, i check it 3-4 times a day)
2) Go to Add New
3) check the full path in "Root Folder"

**Expected behavior**
The full path always present

**Screenshots**

**Platform Information (please complete the following information):**
 - OS: Win10 x64
 - Latest Chrome
 - Radarr Version 3.0.0.3453, but i get this behaviour since i switched to 3x

**Debug Logs**
Don't have now, if needed i have to wait for next time it happens.

**Comment by austinwbest** [comment]
Going to need a but more. I use it on Win 10 and do not see that issue. My last reboot was > a week ago so does that qualify as "awhile"?

Change your logging to trace and leave it on until the problem happens again. Once it does grab the newest trace log as soon as it does so we dont have to sift through thousands of unrelated lines of logging.

**Comment by Kedryn** [comment]
Fine. 
I just enabled the trace, then went to the "Add new", searched for a movie i didnt had, opened it, and the Root Folder was already disappeared. Then i did the Import and went back to Add and it was there again. I saved the trace and i'm attaching it here. Maybe it's missing the part where it disappear. Anyway, i'll leave it on and wait a bit. If it happens again, i'll resend the updated trace log.
[radarr.trace.txt](https://github.com/Radarr/Radarr/files/5096621/radarr.trace.txt)

**Comment by ta264** [comment]
This is stored in the browser, so don't think you'll see anything in the logs unfortunately.  Make sure you're not using any sort of browser cleanup plugin, or switching browsers etc.

**Comment by austinwbest** [comment]
Didn't even think about browser local storage 😳

**Comment by jadehawk** [comment]
Been Experiencing the same issue. With both Sonarr (Preview) & Radarr (V3) Running on Docker and Root folders pointing to a NAS Share. Using Chrome as the browser.
I will switch browsers and give it a try next time I encounter the disappearing Root Folders..
Thanx for the info

**Comment by bakerboy448** [comment]
@jadehawk @Kedryn has this been experienced recently?  any logs?

**Comment by Kedryn** [comment]
Don't really know when, but it started working one day, and no more lost root folder in the "add new"
now it is working perfectly
