### ISSUE TITLE
Issues with manual title searches and nzbplanet.net and wrong results

### ISSUE THREAD

**Issue by bsahlhof** [Radarr/Radarr#4903]
When searching using Newznab search and nzbplanet.net, the IMDB # search works great, but when searching by movie name, it returns all recent results from nzbplanet.net.  I believe this is because the "t=movie" search does not accept the "q=<movie title>" syntax.  The only way to use this syntax is to use "t=search"

I haven't studied the code well enough to determine if this is the place which can effect this change, but it appears in the function I've referenced below, changing the keyword "movie" to "search" would effectively fix this issue for nzbplanet.net

I do not know how other newznab sites work, but hopefully at least for this site, the logic could be updated.

https://github.com/Radarr/Radarr/blob/075f024cec248a19a0c7a4294387f5b28b3f900a/src/NzbDrone.Core/Indexers/Newznab/NewznabRequestGenerator.cs#L147-L150

**Comment by austinwbest** [comment]
I dont use usenet and i'm sure @Qstick can correct me if i am wrong but this sounds like a category problem. If the files are categorized as movies as they should be when searching via radarr then it would find them. It seems switching to a generic search will pull more than needed. Maybe that isn't how the logic works for nzb though..

**Comment by bsahlhof** [comment]
After reviewing the API guidelines at:
[https://api.nzbplanet.net/apihelp](url)
and asking the question on the NZB Planet forum, it appears very clear that movies (using IMDB) would be in the form of:
?t=movie&imdbid=<IMDB #>

but, when doing a q=<term> does not function with that, the only way q=<term> does a search is when using the generic t=search

Like you, I was thinking it should work when selecting the category of movie for the search, but it's very specific - you must search movies by the imdb number, not the title.

**Comment by bsahlhof** [comment]
After speaking with nzbplanet, they suggest the functionality should be in their API, so lets put this request on hold for now until we see how those changes go.

**Comment by ta264** [comment]
Can you post the output of a caps call to nzbplanet?  That's what we base our API usage off of - I suspect they claim they're supporting `q` on `type=movie` when they don't actually.

Should be something like `https://nzbgeek.info/api?t=caps&apikey={yourkey}`

Eg an excerpt for one of my indexers:
```
<searching>
<search available="yes" supportedParams="q"/>
<tv-search available="yes" supportedParams="q,rid,tvdbid,tvmazeid,season,ep"/>
<movie-search available="yes" supportedParams="q,imdbid"/>
</searching>
```

**Comment by bsahlhof** [comment]
Doesn't help much in this case:

```
<searching>
<search available="yes"/>
<tv-search available="yes"/>
<movie-search available="yes"/>
<audio-search available="yes"/>
</searching>
```

Only suggests they are available.

**Comment by ta264** [comment]
I agree with you then, I think this is something for nzbplanet to fix

**Comment by bakerboy448** [comment]
closing; appears to be an indexer issue
