### ISSUE TITLE
Remake of movie "overview" view

### ISSUE THREAD

**Issue by reloxx13** [Radarr/Radarr#4909]
Hey guys, 

could you think over a re-make of the the "Overview" view of the movie list? 

The movie description should not be shown there. 
It should be a overview which replaces the table for better responsive support because tables are limited in space/width and oldschool. 
The overview view is the "new" way of showing tables as its responsive and can show alot of important informations.
We got digital release date added, which makes the table bigger again.

But in radarr its completly useless and im pretty sure there is almost noone which uses it.
The important infos are too far away from the movie title, alot of infos are mising and the movie description there is useless as a movie managment and not an imdb tool.

My suggestion is to remove the decription, make the title a lil bit smaller and add all information (some of them are shown on the right already) from the table in the space under the title. Add bigger action buttons to the right (or only bigger on mobile).

BR

[AB#831](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/831)

**Comment by ta264** [comment]
You've seen v3 exists with a total ui overall, right?

**Comment by reloxx13** [comment]
> 
> 
> You've seen v3 exists with a total ui overall, right?

i am on v3

**Comment by ta264** [comment]
OK, in that case could you perhaps mock up some screenshots of what you're suggesting?  I don't quite get it from your description.

**Comment by reloxx13** [comment]
Just as example:
It could even expand on click as accordion and show search/file/creaw etc tabs below

![grafik](https://user-images.githubusercontent.com/14855001/90793581-2ea68880-e30c-11ea-8aad-9c51fc58fc48.png)

**Comment by austinwbest** [comment]
I dont disagree with possibly adding more to it since there is real-estate to use, but i do not agree with removing the description. As an "overview" of the movie, the description is pretty well inline with that.

I'll tinker with it some unless @ta264 or @Qstick want to do it themself.

**Comment by reloxx13** [comment]
> 
> 
> I dont disagree with possibly adding more to it since there is real-estate to use, but i do not agree with removing the description. As an "overview" of the movie, the description is pretty well inline with that.
> 
Would be nice to have it optional with a checkbox like some other optional things you can hide/show already.

Some long descriptions will blow up this layout and the "overview" will be gone.
E.g. german descriptions r much longer than the english one.

**Comment by austinwbest** [comment]
In this concept, descriptions would truncate to leave room for other added items bud.

**Comment by ekk88d** [comment]
I noticed that this feature request was stale, but got reupped for a v4.X feature. Instead of starting a new feature request, I'll put this here.

As part of an Overview redesign, could we please get the IMDB rating added to the Overview view? The IMDB rating is listed on the Table view, but not Overview. Even with all of its Options currently checked, like a previous thread poster said, the Overview has a lot of leftover real estate.
The redesign can also include other ratings sources to check in the Options screen.

I was enthused to see the new IMDB integrations after Radarr said that it had upgraded to v4.0.4.5909, so thanks for making IMDB ratings found easier.

**Comment by Qstick** [comment]
> I noticed that this feature request was stale, but got reupped for a v4.X feature. Instead of starting a new feature request, I'll put this here.
> 
> As part of an Overview redesign, could we please get the IMDB rating added to the Overview view? The IMDB rating is listed on the Table view, but not Overview. Even with all of its Options currently checked, like a previous thread poster said, the Overview has a lot of leftover real estate. The redesign can also include other ratings sources to check in the Options screen.
> 
> I was enthused to see the new IMDB integrations after Radarr said that it had upgraded to v4.0.4.5909, so thanks for making IMDB ratings found easier.

No rework of overview is planned currently, open a new issue if you want to see IMDB ratings on overview.
