### ISSUE TITLE
Fix "isToday" on Calendar view

### ISSUE THREAD

**Issue by mouseware** [Radarr/Radarr#4914]
Can we move the class ".CalendarDay-isToday-1rFJO" (current day class) to the parent element "div.CalendarDay-day-2TMXA"? This would help with themes so as to be able to style the entire day block rather than just the date number. 

Example From:
`<div class="CalendarDay-day-2TMXA"><div class="CalendarDay-dayOfMonth-2CzdW CalendarDay-isToday-1rFJO">24</div><div></div></div>`

Example to:
`<div class="CalendarDay-day-2TMXA CalendarDay-isToday-1rFJO"><div class="CalendarDay-dayOfMonth-2CzdW">24</div><div></div></div>`

[AB#760](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/760)

**Comment by Qstick** [comment]
Why don't you just use a css selector to style the div which contains a div with the classname isToday? 

We would have to create a phony class which does nothing for us.

**Comment by mouseware** [comment]
> Why don't you just use a css selector to style the div which contains a div with the classname isToday?
> 
> We would have to create a phony class which does nothing for us.

Because that's not the way CSS works, at least not yet since the pseudo-class ":has()" is not approved or supported by any browser. You cannot style a parent based on child. This would require javascript not a native CSS solution. You can, however, style a child based on a parent, which is why it makes more sense to move the "isToday" class up to the parent. 

Today CSS:
`.CalendarDay-isToday-1rFJO {
    background-color: #ddd;
}`

Proposed CSS:
`.CalendarDay-isToday-1rFJO > .CalendarDay-dayOfMonth-2CzdW {
    background-color: #ddd;
}`

This way the parent container can be styled differently than just the date/header inside the container.

**Comment by Qstick** [comment]
My mistake, I thought :has was already a thing on css side. The isToday class is only there as a side effect to naming, not an intentional identify. As mentioned we would have to add a phony classname to the parent react component that we don't use so this really wouldn't be a high priority... Feel free to put a PR together though

**Comment by mouseware** [comment]
Wouldn't this just be as easy as moving Line 29 in CalendarDay.js  to after Line 21? Just applying the "isTodaysDate && styles.isToday," styles under the parent not the child.

**Comment by austinwbest** [comment]
Try it.. Create a PR for it & it'll get reviewed.
