### ISSUE TITLE
Qualities in the same group are not falling back to Custom Formats for Results Prioritization

### ISSUE THREAD

**Issue by bakerboy448** [Radarr/Radarr#4917]
V3
Reference https://www.reddit.com/r/radarr/comments/igc6pq/prefer_bluray1080p_ptp_golden_over_remux1080p/g2ytxfz/

Screenshots speak for themselves
![5BBwYkh](https://user-images.githubusercontent.com/55419169/91379077-77b47c00-e7e7-11ea-8029-276db4150429.png)
![Q7wkapH](https://user-images.githubusercontent.com/55419169/91379082-78e5a900-e7e7-11ea-9c7c-c9954769290d.png)

**Comment by Qstick** [comment]
0800029713cfe8bf03790e298a3234a35dceaba9

**Comment by Qstick** [comment]
Closing from your tests

**Comment by bakerboy448** [comment]
test results for posterity
https://imgur.com/a/tHgsXN5
