### ISSUE TITLE
Auto search not downloading non monitored movies

### ISSUE THREAD

**Issue by Xarishark** [Radarr/Radarr#4918]
If a movie is not monitored but you press the search button(from a list for example) instead of giving you a message to monitor the movie it will search and return nothing.
When a user forces a auto download on a movie radarr should download the first preferred result even if the movie is not monitored.

**Comment by Xarishark** [comment]
Dear god just saw that this is an open ticker from 2018!? Why is this still and issue?????????????

**Comment by bakerboy448** [comment]
Probably a lack of time by the devs to go through the ~400 issues...there’s more important things to do like code and day jobs lol 

I believe there was a bit of an transition period between the folks that were doing most of the development

**Comment by austinwbest** [comment]
Also because it is by design not to grab unmonitored items, so there is that..

That is the entire damn point of not monitoring something 🤣

**Comment by Xarishark** [comment]
> Also because it is by design not to grab unmonitored items, so there is that..

What? No monitor means It wont monitor the files for a better version or Search for it in the RSS feed.
Also by you logic the autosearch button should be grayed out OR throw an monitored movie message.

So no its not by design. It an oversight! Not a HUGE one if you know about it but if you just selected a movie from a list and forgot to monitor it but you press the button and nothing happens(no notification or error message, just no movies grabbed) while manual search returns results then you dont know what to think, until you see that flag and realize "Oh its not monitored".

**Comment by austinwbest** [comment]
The oversight is allowing to click search, that's all.
