### ISSUE TITLE
Movie stays on "Not Available" when skipping the cinema release

### ISSUE THREAD

**Issue by reloxx13** [Radarr/Radarr#4920]
**Describe the bug**
If a movie only gets release digital and not cinema, the movie will stay in "Not Available" state if the minimum availability is set to in cinemas. 
The icon next to the movie title in the movie list says "released". Released is after the in cinema flag. 
It should get the "Missing" state.

This causes a alot of movie not beeing watched to grab.

A wokaround is to set minimum availability to "Announced", but this way also movies announced for 2021+ will be searched.
Causing higher api rates when using manual "seach all".

There is also no posibillity to  make a custom filter with movies which have no cinema date (that way it would be possible to set a tag and change those movies minimum availability to released).

**To Reproduce**
Choose/Add a movie which has skipped cinema and is released (alot of n**f*ix movies).
Set minimum availability to in cinemas and in indexer settings availability delay -14days
=> Movies hat "not available" flag and will not occur in "wanted" filter.

**Expected behavior**

**Platform Information (please complete the following information):**
 - OS: Win10x64
 - Radarr Version: Latest Aphrodite 3.0.0.3497

**Debug Logs**
I can send it over Discord PN

**Comment by bakerboy448** [comment]
Do you have a few example movies to share?

**Comment by austinwbest** [comment]
Without looking at the code yet, i could see this happening if there is no date from TMDb to use and base the delay off of. If there isn't a check, there simply needs to be a check for cinema data before allowing to set it or after the data is grabbed, change it from cinema to release when it has to or just leave it at cinema and fall back to release internally.

Quite a few options can resolve this if it isn't doing anything yet

**Comment by reloxx13** [comment]
> 
> 
> Do you have a few example movies to share?

tt7550000



> 
> 
> Without looking at the code yet, i could see this happening if there is no date from TMDb to use and base the delay off of. If there isn't a check, there simply needs to be a check for cinema data before allowing to set it or after the data is grabbed, change it from cinema to release when it has to or just leave it at cinema and fall back to release internally.
> 
> Quite a few options can resolve this if it isn't doing anything yet

but still, the icon left to the movie name detects that the movie is released. 
this detection must be diffrent between the available state icon code and (monitor) state code.

**Comment by geogolem** [comment]
im looking in the code now, and i see where this is happening. i just need to look at it a bit and think about it.. hopefully ill have a fix in the next little bit.

**Comment by geogolem** [comment]
i think making this change should fix it: 
```
MovieStatusType effectiveMinimumAvailability = (MinimumAvailability == MovieStatusType.InCinemas && !InCinemas.HasValue) ? MovieStatusType.Released : MinimumAvailability;
            switch (effectiveMinimumAvailability)
            {
                case MovieStatusType.TBA:
                case MovieStatusType.Announced:
                    minimumAvailabilityDate = DateTime.MinValue;
                    break;
                case MovieStatusType.InCinemas:
                    if (InCinemas.HasValue)
                    {
                        minimumAvailabilityDate = InCinemas.Value;
                    }
                    else
                    {
                        //this branch should never be taken because of the check before the switch
                        minimumAvailabilityDate = DateTime.MaxValue; //this is a problem what if we dont have inCinemas date but we have digital/release dates
                    }

                    break;
```

I just need to reproduce with your test movie before the change and see what happens with the change..

**Comment by geogolem** [comment]
OK, so i think the above fix solves the problem; however, I think I should not use the switch and just an if structure - so I am cleaning the code up a bit. Will create a branch/PR with cleaned up code soon.

**Comment by geogolem** [comment]
You might want to create another issue for a feature request to add filter support for MinimumAvailability (if you want), if it doesnt already exist. that might have allowed you to workaround this issue, but it wasn't a solution - though it could be a useful feature...
