### ISSUE TITLE
Aphrodite: Wanted Filter not showing wanted movies

### ISSUE THREAD

**Issue by xen0m0rph2020** [Radarr/Radarr#4922]
Hi all
So in V2 of Radarr the wanted tab showed movies I want that are not downloaded yet,
However in V3 Wanted filter only shows movies I had previously downloaded but now no longer exist. I am seeing same movies in both Wanted and Missing. 

**To Reproduce**
Go to Wanted Filter

**Expected behavior**
See all movies I want but never downloaded before

**Platform Information (please complete the following information):**
 - OS: Linux Docker Container
 - Chrome
 - Radarr Version 3.0.0.2956

**Comment by bakerboy448** [comment]
That version is quote a few updates behind, the latest is 3.0.0.3502

The behavior appears to be performing as expected:
![image](https://user-images.githubusercontent.com/55419169/91470067-d6b2d900-e859-11ea-801e-cf1bdcd2d7f1.png)

**Comment by xen0m0rph2020** [comment]
hmm im using linuxservers docker image. need to wait for him to update it
So in v2 if I added a movie that is not released yet it would show in wanted but not in missing?
Is wanted in v3 same behaviour as in v2?

**Comment by bakerboy448** [comment]
The behavior sounds the same, no?
V2 if added and unreleased then wanted
V2 if missing and released then missing and wanted?
V3 if added and unreleased then wanted
V3 if missing and released then missing and wanted

several people's personal preference is to choose Hotio's Docker image over LSIO
> - Hotio has direct contact with the devs and even makes special docker build for them for testing (example RadarrV3)
> - Hotio Updates: every 30 minutes for apps and every hour for upstream image updates vs regular and timely application updates
> - Hotio's images are Tested before release compared to LSIO that had already a few times that certain images/build where borked.
> - Hotio's Configuration files are stored in /config/app what i actually like being i can use a /config/scripts for others things and keep the main appdata clean
> - Hotio's images by default don't provide a pre setup path what's in my opinion great

**Comment by xen0m0rph2020** [comment]
@bakerboy448 Yes the version im running it does not seem to work like that in Wanted its only showing movies which I had before. Will try Hotio image

**Comment by xen0m0rph2020** [comment]
latest version fixed it 
thanks

**Comment by ta264** [comment]
For the record linuxserver image is up to date, you'll have just not managed to pull the updated one.
