### ISSUE TITLE
Upgrades to better qualities don't seem to be snatched automatically

### ISSUE THREAD

**Issue by spuniun** [Radarr/Radarr#493]
I have imported a number of my existing titles from my library, all SD or lower HD qualities. Radarr does a fair job at automatching the quality (I know there an existing feature request to allow this to be modified manually like in Sonarr) but none are detected as Bluray-1080p which is my defined cutoff for my HD - All profile.
I've been watching the logs all day and noticed that Radarr never seems to include these titles when doing it's automated search, and is only searching for those items still marked as Monitored & Missing. If I do a manual search I can find better quality releases available and if I do an auto search Radarr picks them up as well (although sometimes not the best available for which I see there's already a bug), but I would expect Radarr to keep searching monitored titles until the cutoff quality has been met.

**Comment by galli-leo** [comment]
Radarr currently does not do an automated backlog search. It only uses RSS feeds of your indexers and thus only finds new releases.
