### ISSUE TITLE
Restart hangs after RSS Sync on Synology

### ISSUE THREAD

**Issue by houndtt** [Radarr/Radarr#4931]
**Describe the bug**
The restart function in Radarr does not complete after the program has been running a while. This results in the program attempting a shutdown but the instance does not stop. As a result, the restart does not complete because it sees an instance already running.

**To Reproduce**
1. Start Radarr
2. From the System > Tasks section fire the RSS Sync
3. Click on the Restart function
4. Interface will not update and eventually fail to load page

**Expected behavior**
1. Following a Restart the message log will show:
```
LifecycleService | Restart requested.
CommandExecutor | Starting 2 threads for tasks.
```

**Screenshots**
N/A

**Platform Information (please complete the following information):**
 - OS: Synology DSM 6.2.3-25426 Update 2
 - Mono Version: Mono 5.20.1.34
 - Browser and Version: Safari 13.1.2
 - Radarr Version: 0.2.0.1504

**Debug Logs**
https://pastebin.com/UC6SuCme

P.S. To get Radarr to eventually start, I terminal into the Synology and manually kill the process with owner "sc-radarr". Once this completes I am able to start it normally via the Package Center.

**Comment by houndtt** [comment]
Is there any further information you may need from me to help diagnose this issue? Let me know.

**Comment by bakerboy448** [comment]
Closing
v0.2 is no longer being actively developed.

If this is still an issue on **recent** v3 builds, please open a new issue.
