### ISSUE TITLE
[Bug] [Aphrodite] tv movies are not handled and show as "not available"

### ISSUE THREAD

**Issue by Silent-Remux** [Radarr/Radarr#4933]
Examples: 

https://www.themoviedb.org/movie/682598-the-scheme

https://www.themoviedb.org/movie/653748-the-go-go-s

**Comment by austinwbest** [comment]
Show as not available where?? Either this is quite vague or i am just slow... 

I went to Add New and searched for The Scheme and it finds it. I add it and all the data is there (poster, desc, crew, etc) and when i click search it finds it. What am i missing?

**Comment by Silent-Remux** [comment]
Sorry should've been more specific.

The release date type is TV so they don't get grabbed by Radarr.

**Comment by austinwbest** [comment]
Think this is a you issue? The green arrow in the screenshot means it was an auto-grab

Maybe your indexers?

![Annotation 2020-09-01 144843](https://user-images.githubusercontent.com/8321115/91893613-67c2ef00-ec62-11ea-8e89-d5ca1aa91790.png)

**Comment by Qstick** [comment]
It's definitely an issue, if a movie only has a tv release date it'll show as announced in Radarr forever.... We don't handle tv release types in servarr api if I recall correctly

**Comment by austinwbest** [comment]
Then how did it work I guess is another question 🤔

**Comment by Qstick** [comment]
It might have another release type as well, have to check tmdb

**Comment by austinwbest** [comment]
Oh, well I just used one from the OP so figured it was a broken one lol

**Comment by Qstick** [comment]
Yea what did you have minAvail set to?

**Comment by Qstick** [comment]
See no release data and shows unreleased... 

![image](https://user-images.githubusercontent.com/376117/92187377-92aa7000-ee27-11ea-8df9-165a65e644ec.jpeg)

**Comment by austinwbest** [comment]
That may be it, I think all mine are announced and then like - 5 or something for the delay

**Comment by Silent-Remux** [comment]
More examples showing as "unreleased" / not available:

https://www.themoviedb.org/movie/639422-same-time-next-christmas
https://www.themoviedb.org/movie/626313-the-christmas-song
https://www.themoviedb.org/movie/655730-agatha-and-the-curse-of-ishtar
https://www.themoviedb.org/movie/630919-a-homecoming-for-the-holidays

**Comment by austinwbest** [comment]
Yea, I think you're good. Mine worked because I use announced. If you don't use that, it will present the issue.

I believe this is something only Q out ta can fix since it is on the servarr side

**Comment by Qstick** [comment]
I’ll fix this tonight, let me know any other cases you have that are issue. I’ll have to bust the cache on them manually so you don’t have to wait 30 days

**Comment by Qstick** [comment]
Fixed on metadata and cache has been busted for the ones you have listed here. PM any more to me on discord @Silent-Remux
