### ISSUE TITLE
Blade runner 2049 replaces the first blade runner 

### ISSUE THREAD

**Issue by Xarishark** [Radarr/Radarr#4944]
If I have Both blade runner and bladerunner 2049 to on the wanted movies and search for the 2049 it downloads and is imported on the old bladerunner instead of the 2049. 
[radarr.txt](https://github.com/Radarr/Radarr/files/5173583/radarr.txt)

I can provide whatever other info you need.

**Comment by ta264** [comment]
please fill in the template you deleted
