### ISSUE TITLE
Can't add 2 movies with the same name but different years

### ISSUE THREAD

**Issue by revolter** [Radarr/Radarr#4948]
**To Reproduce**
1. Open the Radarr website
2. Search for movies with the title "Znachor"
3. Add both movies (first screenshot)

**Expected behavior**
Both movies should be downloaded.

**Describe the bug**
The movie from 1982 is downloaded, but gets renamed to "Znachor (1937)". Also, only the 1937 one shows up in the library (second screenshot).

**Screenshots**

---

<img width="1369" alt="image" src="https://user-images.githubusercontent.com/5748627/92282676-c8725600-ef06-11ea-962e-30d48f59662d.png">

---

<img width="540" alt="image" src="https://user-images.githubusercontent.com/5748627/92282748-f22b7d00-ef06-11ea-91a2-ddfe02bf9c23.png">

---

<img width="1340" alt="image" src="https://user-images.githubusercontent.com/5748627/92282844-269f3900-ef07-11ea-904f-e8512fdc6728.png">

---

<img width="425" alt="image" src="https://user-images.githubusercontent.com/5748627/92282873-3ae33600-ef07-11ea-9956-e7a48340497e.png">

---

<img width="554" alt="image" src="https://user-images.githubusercontent.com/5748627/92282927-59e1c800-ef07-11ea-9540-6dd5e5710ec3.png">

---

**Platform Information (please complete the following information):**
 - OS: Ubuntu Server 20.04
 - Mono Version: 5.20.1.34
 - Browser and Version [e.g. chrome, safari] (Only needed for UI issues)
 - Radarr Version 0.2.0.1504

**Debug Logs**
It's not a reoccurring bug, as I already have the movies added. And I also don't want to remove them and add them again.

**Comment by Qstick** [comment]
Believe this is fixed on v3 and won't be on v0.2

**Comment by bakerboy448** [comment]
Closing
v0.2 is no longer being actively developed.

If this is still an issue on **recent** v3 builds, please open a new issue.

**Comment by Qstick** [comment]
This is still an issues, but there is another GHI for it. <https://github.com/Radarr/Radarr/issues/5282>
