### ISSUE TITLE
Using shutdown button in radarr unable to restart it again Linux Mint

### ISSUE THREAD

**Issue by Dnkhatri** [Radarr/Radarr#495]
After I use the shutdown button in radarr I am unable to restart it get this error
sudo: /opt/Radarr/Radarr.exe: command not found
but deleting the Radarr install folder and reinstalling it fixes it.

**Comment by galli-leo** [comment]
Could you post the Debug logs here?

**Comment by Dnkhatri** [comment]
I cant make it happen again although this time I installed the latest version directly previously I was on an older release and used the internal updater to update and it happened multiple times. I am trying to make it happen again if it does will post the log

**Comment by Dnkhatri** [comment]
[radarr.txt](https://github.com/Radarr/Radarr/files/737013/radarr.txt)
[2017.01.29-00.43.txt](https://github.com/Radarr/Radarr/files/737014/2017.01.29-00.43.txt)

yes i was correct this happens because of the internal updater

**Comment by Firemad03** [comment]
#521 I found the solution for the update problem and maybe it's the same solution for this problem. You will need to adapt it for Linux Mint.

**Comment by Firemad03** [comment]
I had a problem with the restart too and now the restart is always working :)
