### ISSUE TITLE
Failed to load Radarr

### ISSUE THREAD

**Issue by Blisk** [Radarr/Radarr#4952]
**Describe the bug**
After updating radarr I get error
Failed to load Radarr
3.0.0.3502

**To Reproduce**
Open web page

**Expected behavior**

**Screenshots**

**Platform Information (please complete the following information):**
 - OS: [e.g. Windows] QNAP
 - Mono Version: [e.g. Mono 5.8] (Only needed under Linux and Mac, found under System -> Status)
 - Browser and Version [e.g. chrome, safari] (Only needed for UI issues) - firefox, chrome, both latest
 - Radarr Version [e.g. 3.0.0.2956] - 3.0.0.3502

**Debug Logs**
Turn on debug logs under Settings -> General and wait for the bug to occur again. **Upload the full log file here (or another site and link it). Issues will be closed, if they do not include this!**

**Comment by ta264** [comment]
Closing until we get some useful information

**Comment by Blisk** [comment]
I have uninstalled it and reinstalled it and now I get this error.


  |  
-- | --
message | "SQL logic error\nno such table: Users"
description | "code = Error (1), message = System.Data.SQLite.SQLiteException (0x800007BF): SQL logic error\nno such table: Users\n   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)\n   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()\n   at System.Data.SQLite.SQLiteDataReader.NextResult()\n   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)\n   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)\n   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in C:\\projects\\dapper\\Dapper\\SqlMapper.cs:line 1060\n   at Dapper.SqlMapper.QueryImpl[T](IDbConnection cnn, CommandDefinition command, Type effectiveType)+MoveNext() in C:\\projects\\dapper\\Dapper\\SqlMapper.cs:line 1079\n   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)\n   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)\n   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) in C:\\projects\\dapper\\Dapper\\SqlMapper.cs:line 721\n   at NzbDrone.Core.Datastore.SqlMapperExtensions.Query[T](IDatabase db, String sql, Object param) in D:\\a\\1\\s\\src\\NzbDrone.Core\\Datastore\\Extensions\\SqlMapperExtensions.cs:line 14\n   at NzbDrone.Core.Datastore.BasicRepository`1.Query(SqlBuilder builder) in D:\\a\\1\\s\\src\\NzbDrone.Core\\Datastore\\BasicRepository.cs:line 71\n   at NzbDrone.Core.Authentication.UserRepository.FindUser(String username)\n   at NzbDrone.Core.Authentication.UserService.FindUser(String username, String password) in D:\\a\\1\\s\\src\\NzbDrone.Core\\Authentication\\UserService.cs:line 93\n   at Radarr.Http.Authentication.AuthenticationService.Validate(String username, String password) in D:\\a\\1\\s\\src\\Radarr.Http\\Authentication\\AuthenticationService.cs:line 107\n   at Nancy.Authentication.Basic.BasicAuthentication.RetrieveCredentials(NancyContext context, BasicAuthenticationConfiguration configuration)\n   at Nancy.Authentication.Basic.BasicAuthentication.<>c__DisplayClass3_0.<GetCredentialRetrievalHook>b__0(NancyContext context)\n   at Nancy.BeforePipeline.<>c__DisplayClass8_0.<Wrap>b__0(NancyContext ctx, CancellationToken ct)\n   at Nancy.BeforePipeline.Invoke(NancyContext context, CancellationToken cancellationToken)\n   at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)"

**Comment by Blisk** [comment]
on version 3232 is the same
I have qnap firmware 4.4.3.1400

**Comment by ta264** [comment]
Sounds like your database is corrupted. Join the discord channel for support.

**Comment by Blisk** [comment]
I see that but I have uninstalled it and installed it again and it is the same, databse should be erased during uninstall.

**Comment by ta264** [comment]
Database is not erased on uninstall. Support issues are dealt with via discord and not GitHub.
