### ISSUE TITLE
Reanalyse Video File Option Even If No File Name Change

### ISSUE THREAD

**Issue by mmaghometech** [Radarr/Radarr#4956]
**Is your feature request related to a problem? Please describe.**

After reencoding movie to another format Radarr does not update movie to reflect new file size or format. Encoding program uses same file naming after completion.  A manual refresh of the movie or the library does not reanalyse the file. In order for the new attributes to be recognized correctly the movie must be renamed or removed and added again.  Or require the use of scripts or awkward folder manipulation depending on encoding app.  Apps that are commonly used to encode a file in place are Tdarr and Unmanic with Handbrake being capable of folder manipulation.  

**Describe the solution you'd like**

An option to have Radarr reanalyse the file even if the name hasn't changed.  Could be implemented as an advanced option with a warning if to resource intensive and the ability to set a schedule.

**Describe alternatives you've considered**

Not sure if possible via another in app means

[AB#764](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/764)

**Comment by Lollaskates** [comment]
bump, not recognizing the file information change (size, etc) by tdarr or manually re-encoding is sub-optimal. Lets get this implemented / fixed.

**Comment by bakerboy448** [comment]
Unproductive Comments such as "me too","Please fix", "when will this me merged" etc. are generally frowned upon.

Current workaround is to rename the file after editing it and then refreshing the movie in radarr

**Comment by bakerboy448** [comment]
https://github.com/Radarr/Radarr/commit/c538424229eadaed0ec8ce8eace95bd516676841
