### ISSUE TITLE
"Must contain a valid Unix permissions octal" when changing permissions

### ISSUE THREAD

**Issue by didyouexpectthat** [Radarr/Radarr#4968]
**Describe the bug**
Cannot change the `File chmod mode`

Installation: Freshly installed Radarr nightly and upgraded to aphrodite, changed from mono to dotnet. 

**To Reproduce**
1. Go to `/settings/mediamanagement`
2. Click `Show Advanced`
3. Scroll down to `File chmod mode`
4. Change from `0644` (default) to `0755`
5. Click Save
6. Error: Must contain a valid Unix permissions octal

**Expected behavior**
Save the expected and correct octal.

**Screenshots**
![image](https://user-images.githubusercontent.com/1329077/92437125-15e70100-f15b-11ea-8797-4ec81de0f398.png)
![image](https://user-images.githubusercontent.com/1329077/92437137-1b444b80-f15b-11ea-8668-1baa4630d8f2.png)
![image](https://user-images.githubusercontent.com/1329077/92437147-20a19600-f15b-11ea-8a04-f3fe5d2c264f.png)

**Platform Information (please complete the following information):**
 - OS: Debian 10
 - ~~Mono Version: [e.g. Mono 5.8]~~ .NET Core: Yes
 - Browser and Version [e.g. chrome, safari] Chrome 85.0.4183.83 (on Windows 10)
 - Radarr Version: 3.0.0.3641

**Debug Logs**
```
2020-9-7 22:47:01.4|Warn|RadarrErrorPipeline|Invalid request Validation failed: 
 -- FileChmod: Must contain a valid Unix permissions octal
2020-9-7 22:47:01.4|Debug|Api|[PUT] /api/v3/config/mediamanagement: 400.BadRequest (2 ms)
```

**Comment by ta264** [comment]
0755 is not valid in Radarr. It's a file octal, we don't want it making media files executable.
