### ISSUE TITLE
Aphrodite - only showing Engish titles

### ISSUE THREAD

**Issue by strunov** [Radarr/Radarr#4971]
**Describe the bug**
I upgraded to aphrodite branch yesterday, and after that all my Danish movies shows in English title. 
Previously I could control metadata language by using different quality profiles.

I am Danish, and I notice the error for Danish titles. But I use French language as an example because majority of titles are localized to French.

**To Reproduce**
1. create a quality profile with a language other than English ie French
2. search to a movie that have a localized title ie Dirty Harry
3. refresh movie.
4. notice title is still "Dirty Harry" in this case.

**Expected behavior**
The expected reaction is the description should be French and the title should be L'inspecteur Harry

**Screenshots**

**Platform Information (please complete the following information):**
 Version
3.0.0.3654
Package Version
aphrodite-dec2a76-212 by hotio
.NET Core
Yes
Docker
Yes
DB Migration
182

**Debug Logs**
Turn on debug logs under Settings -> General and wait for the bug to occur again. **Upload the full log file here (or another site and link it). Issues will be closed, if they do not include this!**

**Comment by Qstick** [comment]
Settings > UI > Language

**Comment by strunov** [comment]
So this change forces me to have the UI interface to Danish (in my case) even if I prefer UI in English?

This would also mean all titles are localized to Danish, correct? What if I prefer to have the titles on original languages. ie US movies in English, Danish movies in Danish, ect..? The old interface could manage this in Profiles.

**Comment by ta264** [comment]
That is correct

**Comment by Qstick** [comment]
@strunov there is some further tweaking to do, we will likely split the setting into UI and Movie Info and add Original Language option to movie info

**Comment by strunov** [comment]
@Qstick Thank you for clarifying.

I hope you come up with a better solution, and make it a per movie setting, rather than a general setting.
