### ISSUE TITLE
Movie folder format for multiple languages

### ISSUE THREAD

**Issue by AlexR00T** [Radarr/Radarr#4978]
**Describe the solution you'd like** 
A simple sounding solution to a problem probably quite a few people face. I watch most movies in English and then there are some i watch in Italian. Now i the whole thing is complicated if i were to have them separated in language folders. But if i there was a way to add that same tag that exists for filenames then i could simply have normal filtering by title all [en] Title folders would be on top of my android tv vlc and all [ita en] Title ones would be down on the bottom. And once i get a file thats also in italian the tag would update and thus move a folder from top half to lower half. Its not ideal but i think it could kinda work. But there should be another text input box for sorting filtering language tags. So that one can write ita, en and then it will always rename folders with ita first and english second and would simply ignore all the rest. Some big mkv files i got before had also other languages and i dont what those in the mix. Or if there would be a way to split the thing to display only ita and en separately. The idea is that all this tags would filter but then titles would still sort by their title since all ita files would then show up as ita a ita b ita c... and so on. Idk this is just an idea that came up to my mind.
P.S.: sorry for braking a ton of rules of how to write feature request and writing it long

**Comment by ta264** [comment]
We have deliberately decided to not allow in the folder name tags that depend on the specific movie file downloaded since the folder name is allocated before the movie is downloaded. We have no plans to revisit this I'm afraid.
