### ISSUE TITLE
Add region selection option for profiles

### ISSUE THREAD

**Issue by Suegrini** [Radarr/Radarr#4979]
**Is your feature request related to a problem? Please describe.**
While a language selection option is much appreciated, the lack of any way of setting a region makes it almost pointless for people in certain regions, in my case latin america, since usually certain regions not only get different dubs but different titles entirely, as you can see in the screenshot below the indexer is returning a file with the latin american title while sonarr is only looking for the original title and the european title forcing me to manually select the file for downloading. This issue isn't isolated to this or few other movies, most movies have different titles between the latin american and european versions which kills the automation part entirely for me and anyone else facing this issue.
![Untitled](https://user-images.githubusercontent.com/56095812/92545516-2e135a80-f205-11ea-9c8e-5cb71af906c5.png)

**Describe the solution you'd like**
An option to select the desired region for the profile would fix this issue, the tmdb api already has region support which make could implementing this feature easier.

**Describe alternatives you've considered**
Splitting the spanish language option between castilian and latin american spanish could also work for this but I don't know if the api supports this, it also would only fix the issue for spanish speaking users and not anyone else who could have the same issue in another language.

**Comment by moralia** [comment]
i have the same problem. The title never in language i choose in profile.

**Comment by Qstick** [comment]
V3 languages are better
