### ISSUE TITLE
Edit custom formats of existing files

### ISSUE THREAD

**Issue by Haulien** [Radarr/Radarr#4981]
Back in the v0.2 days, you used to be able to edit the custom formats of already-existing files, I'd love to have that feature in V3. 

The old way used to be clicking on these and a popup would show up allowing you to add/remove custom formats. 

![image](https://user-images.githubusercontent.com/640569/92590020-10f68e80-f2ce-11ea-9f1d-412cb17217bd.png)

-------------------------

I suppose the extension of this would be allowing the user to set custom formats using manual import.

**Comment by Qstick** [comment]
CFs are dynamically calculated now, thus there is no editing them per se. In order to add/remove you must edit the underlying properties of the file that cause the CF to match (name, quality, lang, etc...)

**Comment by Haulien** [comment]
> CFs are dynamically calculated now, thus there is no editing them per se. In order to add/remove you must edit the underlying properties of the file that cause the CF to match (name, quality, lang, etc...)

That seems counterproductive when you wish to import a file locally but also want an indexer flag in the custom format. If you're importing it then there's no way for the CF of a indexer flag to be dynamically calculated.

**Comment by ta264** [comment]
Being able to manually add indexer flags is on the todo list

**Comment by Haulien** [comment]
Indexer flags are however are still just a custom format. It would be limiting to only be able to edit one custom format type, yet not another. It would also require more work on the dev side to single out custom formats that do and don't have indexer flags.

**Comment by Qstick** [comment]
The indexer flags would be set/modified at the file level, not the CF level. Just like quality and language already are.
