### ISSUE TITLE
Display "In Queue" or "Downloading" tag instead of just "Missing" tag

### ISSUE THREAD

**Issue by beechfuzz** [Radarr/Radarr#4982]
**Is your feature request related to a problem? Please describe.**
On the main page where all your movies are listed, each movie will have a set of tags -- one of which gives you the status of the movie ("downloaded" or "missing").  The problem is that these two tags alone don't give you the full story.  When the "missing" tag is displayed, does that mean it's downloading?  Or does it mean that it's missing and nothing is happening for whatever reason?  You don't know without having to do more research to determine if more manual action is needed on your part.

**Describe the solution you'd like**
More "status" tags.  While "missing" is _technically true_ because technically the file is "missing", it would be much more helpful if there was a "Downloading" or "In Queue" tag to indicate the software is actually doing something with title.  This instantly tells the user that something is happening and there's nothing more they need to do righ tnow.  A "Searching" tag tells the user that the software is searching for a torrent or nzb.  A "Failed" tag tells the user that the software has exhausted all possible options on its own and manual action is required by the user.

**Describe alternatives you've considered**
There are no other alternatives that I'm aware of.

**Additional context**
![titles](https://i.imgur.com/4AUgqUJ.png)
Looking at these titles, you cannot tell that they are currently being downloaded.  All you see is a red tag that says 'missing.'  It's almost universally accepted that red tags, red lights, red signs, or red pop-ups indicate that there's a problem.  Thus, these red "missing" tags -- at first glance -- tell me that I need to do something to fix a problem.  It's not until after spending another minute or two clicking around that I can know that I don't actually need to do anything with these.

**Comment by bakerboy448** [comment]
this may be covered by PR #4664

**Comment by beechfuzz** [comment]
Woah, how do you get it to do that?  I looked throughout all the settings and couldn't get anything remotely close to that.

**Comment by bakerboy448** [comment]
It's a pull request that should be coming into V3 soon (tm)

**Comment by beechfuzz** [comment]
Ah, okay.  Thank you!
