### ISSUE TITLE
Allow interval for finished downloads to be in seconds

### ISSUE THREAD

**Issue by vanlooverenkoen** [Radarr/Radarr#4983]
Right now the interval for checking downloads is set to minutes. I think there should be an option to set it in seconds. Because right now the activity tab is not useful because it only updates every minute. My connection is very unstable and I want to make sure I get the latest status of my downloads. 

![image](https://user-images.githubusercontent.com/21172855/92661560-2c2cc280-f2fd-11ea-9402-93e50d262aea.png)

This pr allowed us to set a minute interval
https://github.com/Radarr/Radarr/pull/3233

**Comment by austinwbest** [comment]
If it is too be added, it wouldn't be in v0.2 bud.

**Comment by vanlooverenkoen** [comment]
Any other idea of a timeframe?

**Comment by vanlooverenkoen** [comment]
So basicly I should upgrade to v3? I am running on a synology ds415+ with 8gb with docker. Is it possible to upgrade to v3?

**Comment by austinwbest** [comment]
You can go to the discord for support with that.

There is no timeframe, I didn't say it would be done but if it was going to that it would not be in v0.2

**Comment by Qstick** [comment]
We are not interested in allowing anything under 1 minute due to load it'll put on the server checking downloads all the time. I would argue that 1 minute is "latest" enough. Are you constantly watching your activity tab?

**Comment by vanlooverenkoen** [comment]
If that is not an option. Is there a way to trigger the finished downloads check manually or with an api call?

**Comment by bakerboy448** [comment]
Refresh in the UI 
And I think yes for the API not sure

**Comment by vanlooverenkoen** [comment]
A refresh does not trigger the finished download check. My progress the progress of my downloads are only updated every minute

**Comment by bakerboy448** [comment]
Refresh the task; trigger it manually.
Just run radarr in two windows I guess?

Check the API docs in the wiki or ask on the discord

**Comment by vanlooverenkoen** [comment]
What do you mean with refresh the task? When I manually refresh the page the progress of my downloads is not updated only every minute

**Comment by vanlooverenkoen** [comment]
I couldn't find anything in the api docs

but in the source code I found this.

POST: /api/command
```
{
  "name": "CheckForFinishedDownload"
}
```
