### ISSUE TITLE
Sort by most recent added

### ISSUE THREAD

**Issue by baretomas** [Radarr/Radarr#4988]
**Description:**

Is it possible to add a feature to sort the Movies section by recently added? I usually want to watch the latest added movie, and seeing what has been downloaded by sorting by recently added would help here.

**Radarr Version:**
0.2.0.1504

**Mono Version:**

**Debug Logs:**

# Do not remove anything from your logs and post the full logs! If not everything fits in here use a service like

**Comment by Qstick** [comment]
It is in v3
