### ISSUE TITLE
Can't delete a single Custom Format condition

### ISSUE THREAD

**Issue by rg9400** [Radarr/Radarr#4992]
**Describe the bug**
In the latest Aphrodite build (after CF export was added), if you try to delete a single condition, it will actually delete all the conditions in that CF. Nothing in console

**To Reproduce**
1. Create a custom format with multiple conditions. I tried with even just 2 conditions and conditions of different and same types both.
2. Try to delete a single condition

**Expected behavior**
Only the deleted condition should be removed.

**Platform Information (please complete the following information):**
 - OS: Windows 10
 - Browser and Version: Edge Version 85.0.564.44 (Official build) beta (64-bit)
 - Radarr Version: 3.0.0.3695

**Comment by Qstick** [comment]
2f311452da78e0e35d51f8f1d83cf7f6bfc6c64a
