### ISSUE TITLE
Importing Sonarr Config

### ISSUE THREAD

**Issue by galli-leo** [Radarr/Radarr#5]

**Comment by onedr0p** [comment]
Another thing I doubt we need to invest time into developing. It doesn't take long to configure the app, people can just open a tab with sonarr and copypasta their stuff to Radarr

**Comment by galli-leo** [comment]
Decided against it. Not worth it from a time perspective and it's not really a lot of stuff to fill out. Additionally, most information is movie centric anyways.

**Comment by silentrob** [comment]
After setting up Radarr last night, this was the first thing I thought about. Mapping config fields from the forked repo should be super easy?!
