### ISSUE TITLE
Cleanup MovieStatus Type Enum 

### ISSUE THREAD

**Issue by geogolem** [Radarr/Radarr#5002]
There really isn't a bug, this is just an issue to track cleaning up MovieStatus Type Enum:

Deleted https://github.com/Radarr/Radarr/pull/4924#discussion_r487049770
TBA,and PreDB: https://github.com/Radarr/Radarr/pull/4921#discussion_r483908130

can likely be removed.

[AB#787](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/787)

**Comment by bakerboy448** [comment]
Any chance we can change released to "Physical/Web Release" at least in the UI so it makes more sense for the users?

We can keep the backend the same, just change the UI if that simplifies it.

**Comment by geogolem** [comment]
Deleted shouldn't be removed: https://github.com/Radarr/Radarr/pull/4924#discussion_r487576501

**Comment by bakerboy448** [comment]
Any updates on this Geo?

**Comment by geogolem** [comment]
ive been a way.. but i have a bunch of tasks here on github to look into.. so i will get back to you in a few more days..
