### ISSUE TITLE
Change History/Grabbed Icon to match Status Colors

### ISSUE THREAD

**Issue by bakerboy448** [Radarr/Radarr#5009]
title...
rather than gray, be purple (in process) and then green (success) or red (failed)

ensure incorporated when #5008 is merged

**Comment by austinwbest** [comment]
On the fence with this personally after thinking about it implemented. I dont personally sit on the history tab in the movie details enough to need the icon to change. It also changes at the top in the status on the details page already. 

It isn't a hard thing to do so much as a "but why" scenario. I'll defer to upper management to decide lol

**Comment by Qstick** [comment]
I'm in the same boat, seems an unnecessary add of color.
