### ISSUE TITLE
Kickass Torrents Indexer Error

### ISSUE THREAD

**Issue by rafspeik** [Radarr/Radarr#501]
Hi guys,

Loving Radarr, awesome work.

I noticed a while back that it looks like the KAT indexer doesn't work with the resurrected KAT website.
The URL is: https://katcr.co/new/

The following is logged when I try to add the indexer with the above URL:
`17-1-28 23:14:39.6|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- No results were returned from your indexer, please check your settings.`

This isn't a priority, but it'd be good to have it fixed when possible.

Cheers.

**Comment by bsod99** [comment]
Not sure about this but I'm fairly certain the rebooted version of the site doesn't do API calls. Which is why it doesn't work with KAT.

**Comment by galli-leo** [comment]
For now you can use the newest release of Jackett.

**Comment by onedr0p** [comment]
We suggest Jackett. KAT has been removed from Radarr.
