### ISSUE TITLE
Donation button ends up 404

### ISSUE THREAD

**Issue by k3anton** [Radarr/Radarr#5010]
**Description:** Clicking "Donate" in Radarr directs to a 404 page like [here](https://radarr.video/donate.html)

It seems like the donation page has been moved and therefor this should be fixed also.

**Radarr Version:** 0.2.0.1504

**Mono Version:** N/A

**Debug Logs:** N/A

**Comment by bakerboy448** [comment]
V2 is only receiving critical bug fixes at this time; I would not think this is a critical issue; the donate link can easily be found

**Comment by k3anton** [comment]
@bakerboy448 May I suggest moving it to a backlog so that it can be fixed when there is time?

**Comment by bakerboy448** [comment]
that' is up to the devs.
It would probably be a quick fix, but technically no further development work will occur on v0.2

V3 is nearing it's promotion to beta from alpha very soon

**Comment by Qstick** [comment]
Page has been recreated and redirects to our opencollective page
