### ISSUE TITLE
Add an "Added by List" Notification Trigger

### ISSUE THREAD

**Issue by bakerboy448** [Radarr/Radarr#5011]
title

**Comment by austinwbest** [comment]
It would be more likely that a attribute be added to the existing grab notification to indicate a list grab & which list, etc

**Comment by bakerboy448** [comment]
that could work as well maybe....but unlikely

My use case is monitoring a collection but adding as unmonitored....so i would want to know when one has been added so I can either monitor and search or remove it

**Comment by austinwbest** [comment]
Gotcha, yea I guess that would be a different one. Maybe a generic Added similar to grab, etc with a lists parameter.

**Comment by Qstick** [comment]
Dupe #4038
