### ISSUE TITLE
(UI) Connect -> Notification Triggers -> Display both the "Name" and description

### ISSUE THREAD

**Issue by bakerboy448** [Radarr/Radarr#5012]
Current: 
![image](https://user-images.githubusercontent.com/55419169/93004724-72597000-f50f-11ea-8238-c18c486e4594.png)

Change to (ex) 

"On Import - Be noted that....."

also add descriptions for those that are missing them

**Comment by Thirrian** [comment]
I'd rather shorten all the texts to:
- on grab
- on successful import
- on rename
- on delete
- on health issue
- on health warning

That way it's consistent and (imho) it's clear what they do.

Maybe change the text "Select which events should trigger this notification" to "For more information, click here to go to the wiki".
...and also actually write that wiki page 😄
