### ISSUE TITLE
Filter by video file format

### ISSUE THREAD

**Issue by morganzero** [Radarr/Radarr#5015]
Hi! I would very much like to have the ability to filter by container and audio codec. I'm currently collecting MP4 containers with AAC audio and every now and then an MKV with a different audio source slips through.

Having the option to filter them out would make it easier for me to identify them and replace them.

Thank you in advance!

**Comment by phife-dawg** [comment]
+1

**Comment by ta264** [comment]
Duplicate #5517.  We don't want to add filter that depend on the specific file.
