### ISSUE TITLE
Request/Suggestion - API repsonse timer

### ISSUE THREAD

**Issue by DejaVu** [Radarr/Radarr#5016]
I've been using Radarr for a long while now - perhaps 5 years and its a fantastic piece of software. 

One annoyance I've had for a while is the interactive searching for the right release I would like. The search is quick and responds and views the API request quite quickly and I realise that selecting the release is more aimed towards the speed of the API you've chosen to download from. However, quite frequently I end up with a lot of spinning donut of deaths waiting for the release to be sent.

My suggestion is, if after 10 seconds with no response, perhaps Radarr can resend the same request?
The reason is, I have to refresh the page, do a new search and then ask the indexer for the file again and it works.

A timer, after clicking the required release would also be a nice touch showing the end user how long the API is taking to respond.

Just a suggestion.

**Comment by Qstick** [comment]
Didn't follow template
