### ISSUE TITLE
radarr 3 isnt changing movie names to german titles-many files needs to be added manually

### ISSUE THREAD

**Issue by skapytek** [Radarr/Radarr#5018]
**Describe the bug**
If im adding a movie radarr should translate the movie name into the german title.
For example:
Death on the Nile (original title)
Tod auf dem Nil (german title)
Sonarr is searching for the movie through nzbhydra2 and is sendind it for downloading to sabnzbd where it downloads without any errors.
Radarr isnt auto-dedecting the downloaded file now so i have to manually add it.
This happens to many movies so its a little bit annoying cause i would like to have it automatically done.

**To Reproduce**
Add a movie like "Death on the Nile" (1978) and have set the language for movies to "german".
Movie title wont get converted and it still shows "Death on the Nile" instead of "Tod auf dem Nil"

**Expected behavior**
Movie title should get converted to the german title.

**Screenshots**
https://i.ibb.co/ct215Gd/2020-09-14-01h48-29.png
https://i.ibb.co/QQVSXp6/2020-09-14-01h48-22.png

**Platform Information (please complete the following information):**
 - OS: Linux
 - running radarr in a docker container
 - Browser and Version Firefox 81.0b9 and latest edge browser
 - Radarr Version: 3.0.0.3700
 - db is about 8000 movies

**Comment by Qstick** [comment]
UI titles are controlled via a setting in Settings>UI, not by profile language

**Comment by skapytek** [comment]
Both is set to german since ive installed radarr.
https://i.ibb.co/ZfdfN2Q/2020-09-14-13h26-51.png

**Comment by skapytek** [comment]
> 
> 
> UI titles are controlled via a setting in Settings>UI, not by profile language

Both is set to german since ive installed radarr.
https://i.ibb.co/ZfdfN2Q/2020-09-14-13h26-51.png

**Comment by Qstick** [comment]
Then either there is not a German translation for that movie, or you need to refresh it
