### ISSUE TITLE
Background image blocked on movie details page

### ISSUE THREAD

**Issue by essarn** [Radarr/Radarr#5019]
**Describe the bug**
The background image on the movie details page is not displayed correctly. 

**To Reproduce**
See the screenshot below. 

**Expected behavior**
The image should be visible and not partially blocked.

**Screenshots**
https://imgur.com/a/YNAJs9c

**Platform Information (please complete the following information):**
 - OS: Windows 10
 - Browser:  Brave v1.13.86 Chromium: 85.0.4183.102 (Officiell version) (64 bitar)
 - Radarr:  v0.2.0.1504

**Debug Logs**
Not applicable.

**Comment by ta264** [comment]
I think this is a problem with brave rather than Radarr. But in any case, 0.2 isn't in development any more so this won't get fixed.
