### ISSUE TITLE
Process unlisted movies

### ISSUE THREAD

**Issue by Mickroz** [Radarr/Radarr#5021]
It would be nice that unlisted movies get processed and imported into radarr regardless like couchpotato does.
With cps, i could send an nzb to sabnzbd, and it got imported in cps, this cannot be done with radarr.

**Comment by austinwbest** [comment]
You mean point to some random file or folder and have radarr import it even if the movie is not added to your database?

Radarr does that..

**Comment by ta264** [comment]
We have discussed this before, not going to happen in afraid.  If you want this, use couch potato.

**Comment by Mickroz** [comment]
Couldn't find the discussiob, hence my issue.
Too bad, will work my way around it then with a script.

**Comment by ta264** [comment]
Sorry, you wouldn't, it was on discord.  I just mentioned it so closing this looks less arbitrary :)
