### ISSUE TITLE
qBittorrent 4.3 won't import finished downloads

### ISSUE THREAD

**Issue by ShadwDrgn** [Radarr/Radarr#5032]
**Describe the bug**
qBittorrent 4.3 does not create subfolders with a the name of the downloading torrent. This causes the following code fail to find anything for all torrents that don't happen to have a subfolder with the exact torrent's name:
https://github.com/Radarr/Radarr/blob/4c0a906bfac91725c866ad7b6202e53957877fcc/src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrent.cs#L151

**To Reproduce**
1. Get QBT 4.3
2. download ANY torrent of any name. ensure it's got no subfolders OR a subfolder with a name AT ALL different from the name of the torrent OR rename the torrent to anything you'd like (not the same as it's content's)
3. let radarr try to import completed download
4. See error in logs failing to find folder

**Expected behavior**
I expect radarr to hit the /api/v2/torrents/files endpoint to get a list of file paths in the torrent and append THOSE to save_path in the api output from /api/v2/info that it currently uses.

**Pastebins of json output from the two endpoints above**
/info endpoint:
https://pastebin.com/u8bLcFJF
/torrents/files endpoint:
https://pastebin.com/Sgcuz3JZ

**Platform Information (please complete the following information):**
 - OS: linuxserver/radarr (with custom compose)
 - Mono Version: This appears to be a native linux ELF
 - Browser and Version Chrome (not UI issue)
 - Radarr Version 3.0.0.3736

**Comment by bakerboy448** [comment]
Sonarr PR to correct https://github.com/Sonarr/Sonarr/pull/3346

**Comment by ThatNerdyPikachu** [comment]
> qBittorrent 4.3 does not create subfolders with a the name of the downloading torrent

That... does not seem like intended behavior on qBittorrent's side.
What does it do instead?

Also:
![image](https://user-images.githubusercontent.com/15848969/94347815-7a340c80-0005-11eb-92c0-7ebef88aa988.png)

Did the default value for `Create subfolder` in API change?

**Comment by ShadwDrgn** [comment]
I'm not certain what your screenshot is from but it doesn't appear to be anywhere in 4.3.
in 4.3 there's a "Keep Top level folder" option instead and it does not create folders whether it's checked or unchecked. it only decides whether to delete the top folder in torrents with 1 folder and no other files or something along those lines. I believe they intended this because they have commits and PRs addressing this new "keep top level folder" option all over the place talking about how it was supposedly confusing to people.

**Comment by Miicker** [comment]
I have the same issue! Except that I'm using not using Torrents, I'm using NZBGet.

**Comment by ta264** [comment]
If you're using nzbget it's not the same issue, you just need to set it up correctly.

**Comment by Miicker** [comment]
@ta264 of course! I need to set it up correctly! How could I not have tought of that!
On a serious note: It was working for years, I haven't changed a thing and now all of the suddon I have the same problem, that Radarr cannot move/import downloaded files.

**Comment by ta264** [comment]
discord / reddit is the correct place for support requests please

**Comment by winklevos** [comment]
Qbit have added `content_path` to the /api/v2/info as of API v2.6.1 

For single file torrents `content_path: "/dir/file.ext"`
For multi file torrents `content_path: "/dir/subdir"`

see https://github.com/qbittorrent/qBittorrent/issues/13389 for more details
