### ISSUE TITLE
[Aphrodite] Show Original Language on List and Discovery Pages

### ISSUE THREAD

**Issue by rottenCoder** [Radarr/Radarr#5033]
Description:
At the moment you have, FILMNAME (2017) [Released] [6.2] [Trailer]
I propose to have FILMNAME (2017) [FILM GENRE] [LANGUAGE] [Released] [6.2] [Trailer]

Radarr Ver. 0.2.0.1504

**Comment by austinwbest** [comment]
Not gonna happen in v0.2 bud, that is feature locked & show stopper fixes only.

**Comment by rottenCoder** [comment]
The feature request is for V3

**Comment by austinwbest** [comment]
OK, your request is followed by v0.2 and you modified the title after my comment so I didn't expect it would be :)

**Comment by dramirvf** [comment]
Having information on **"Original Movie Language"** is very useful. Additionally, I suggest to include it in the main movie page, columns, filters, etc.

**Comment by bakerboy448** [comment]
duped by https://github.com/Radarr/Radarr/issues/5214
