### ISSUE TITLE
Sharding folder support

### ISSUE THREAD

**Issue by anoma** [Radarr/Radarr#5035]
**Is your feature request related to a problem? Please describe.**
It is a well known phenomenon of fileshares such as cifs/samba, especially on lower end devices, that after a certain node count day to day performance tanks (inode caching, real world browsing speed etc, disk spin ups).

**Describe the solution you'd like**
A common elegant and scalable solution is to use sharding as it does not require any special daemon configuration and just takes advantage of the natural distribution of the alphabet.

For example:

movies
---Alien
---The.A-Team
---Abbott.And.Costello
---A.Beautiful.Mind
---Bad.Boys

would become

movies
---A
-----Alien
-----The.A-Team
-----Abbott.And.Costello
---B
-----A.Beautiful.Mind
-----Bad.Boys

**Describe alternatives you've considered**
None

**Additional context**
This can have quite a radical impact on real world performance; has zero hardware cost, is platform agnostic, is easy to explain to users and can be reverted easily if later some other solution presents itself.

**Comment by xfouloux** [comment]
Hi,

this would need to not be the default, because plex/emby can't use that, and i assume most of radarr users are plex/emby users =)

But yeah it could be a good feature for others

**Comment by anoma** [comment]
Thanks for the reply.

For what it is worth Emby does support this for movies but not for TV (at least here). (TV data needs a source defined per shard but movies do not).

Kodi has an exact same set of requirements. I cannot speak to Plex but if it helps I can have it tested.

But I absolutely agree it probably should not be the default regardless.

**Comment by bakerboy448** [comment]
You can work around this now by just using multiple root folders.

**Comment by anoma** [comment]
Thanks for the advice.

This is how I am trying to test it now and whilst it is not hard it is klunky and breaks the elegance of the workflow. It does work though.

**Comment by Qstick** [comment]
We already support this naming scheme in v3 for imports and re org

Just set folder naming to “{Movie TitleFirstCharacter}/{Movie Title}”

**Comment by anoma** [comment]
Thanks this is extremely useful. I can see this feature and it looks like it does exactly this.

However I dont see any `File Name Tokens`  in the `Movie Folder Format` section that will allow the `Source Title` to be preserved.

e.g. `{Movie TitleFirstCharacter}/{Movie Title}` generates `Example: M/The Movie Title`

Is there an option to organize only and never rename

e.g. `{Movie TitleFirstCharacter}/{Source Title}` to maintain `Example: M/the.movie.title.1978.720p.BluRay.H264.AAC-SELF`

or am  I making a fundamental mistake in my thinking around this feature?

**Comment by xfouloux** [comment]
Yeah i don't know if you can use {Original Title} in the movie folder as it is a token for filename :/

**Comment by bakerboy448** [comment]
Movie folders are static and their names are/should be static.  This is not a change we are exploring at this time.  The same applies to the quality, group, or any other dynamic variable in the folder name.  This will likely never come due to the planned eventual multi-file support.

**Comment by austinwbest** [comment]
Use those fields in the naming if you want them all & radarr has grab history if you want to look at the scene name

**Comment by bakerboy448** [comment]
Creation of Sharding folders is a bug at the moment
https://github.com/Radarr/Radarr/issues/5247

**Comment by bakerboy448** [comment]
closing; feature exists;  follow #5247 for further details on it being fixed.
