### ISSUE TITLE
Discover tab doesn't follow the Movie Info Language setting

### ISSUE THREAD

**Issue by Galiwyx** [Radarr/Radarr#5036]
**Describe the bug**
In the Discover tab, Movie Info Language doens't follow the setting in the UI setting, it stays in English.

**Screenshot**
![image](https://user-images.githubusercontent.com/206181/93645178-c7135400-fa03-11ea-9ebb-625bf0de3344.png)

![image](https://user-images.githubusercontent.com/206181/93645214-d4304300-fa03-11ea-857e-b7d57e0e53e7.png)

**Platform Information:**
 - OS: unRAID Docker
- Version : 3.0.0.3736
- Package Version : aphrodite-8158f0f-294 by hotio

**Comment by Qstick** [comment]
https://github.com/Radarr/Radarr/commit/01f0f9d3bbc882d032d67b48f4aa85521c4f5a80
