### ISSUE TITLE
Formatting of the text for the "Date Added" column in table view of the movies list

### ISSUE THREAD

**Issue by cbdejavu** [Radarr/Radarr#5040]
**Is your feature request related to a problem? Please describe.**
The text for the "Added" column on the Movies Table view in v2 shows as the time if it was added that day then would go into labels relative to today (i.e. Yesterday, 3 days ago, 10 days ago, month ago, over a year ago, etc....)  In the v3 it follows that same format showing time if "today", then yesterday, then it just shows the date instead of "relative age as of today" (I guess that is a good a term as any to describe it)

**Describe the solution you'd like**
Is it possible to either return to the same naming conventions used in v2 or to make another "column" that uses that v2 conventions for the date added field.

**Describe alternatives you've considered**
Mostly this is an item of convenience and preference.

[AB#790](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/790)

**Comment by Qstick** [comment]
No plans to expand this
