### ISSUE TITLE
Release Date displays incorrect year

### ISSUE THREAD

**Issue by TheSpoon98** [Radarr/Radarr#5041]
**Description:**
It appears for release dates that start on the new year, for instance:
https://www.themoviedb.org/movie/209676-palm-springs
https://www.themoviedb.org/movie/209674-next-door

that Radarr is displaying them as the prior year on the movie detail page (the movies summary list page is displaying them correctly).  All sources that I can find, trakt/tmdb/imdb all display the date as appropriate.  

I had read a reddit comment from /u/DJ_Lectr0 (posted 2 years ago) that the earliest tmdb date is what's used, and if that's still the case, then there is still an issue as both the movies lists above only have 1 release date listed.

**Radarr Version:**
0.2.0.1504

**Mono Version:**
6.10.0

**Comment by austinwbest** [comment]
This is something that can be checked in v3 (to see if still an issue) but as for v0.2 it would not be addressed since that is critical fixes only bud.
