### ISSUE TITLE
RAM Hogging issue Aphrodite windows as service 

### ISSUE THREAD

**Issue by Bastien42** [Radarr/Radarr#5042]
**Description:**

recently after a big import of my list around 25k movie i already had 39k movie listed, Radarr started filling all my ram (32gb) on start with weird dips every now and then let say it fills 20gb go down to 10 then back to 22 tehn 12 etc till my pc is almost unusable and of course Radarr is unusable as my ram fills 

**Radarr Version:** 3.0.0.3746

**DB Migration** 184

**Debug Logs:**  [radarr.debug.txt](https://github.com/Radarr/Radarr/files/5258426/radarr.debug.txt) (Clean Logs from start till my ram is filled with a dip from 31gb to 8gb then going back up as explain before for finally leaving 400/200mb of memory)

PS : i know that 62k+ movie is a bit unusual but pls don't just tell me delete some movies ;) :)

**Comment by Qstick** [comment]
Delete some movies.... that would be a sin! I don’t see anything unusual in your logs, just appears to be updating all the ones you added. It’s going to take awhile with that many...

Just to rule out any other funny business.. you don’t have any third party tools connected to Radarr do you?

**Comment by Bastien42** [comment]
Well that's what I figured too that maybe it's just normal now I'm gonna let it do its thing I'm more concerned that when the ram is maxed out it will just not process any files until I restart and let the filling process start again and no I don't have any tool connected to radarr that I can think off if you can let me know if radarr will still function if it's not responsive with its interface

**Comment by ta264** [comment]
FWIW a user with 160k movies had memory usage of around 1gb. Do you have any external tools connected to Radarr? The user in question had been using requestrr which was causing memory usage to balloon to and crash the box, once it was removed everything behaved again.  Heimdall also exhibits similar behaviour.

Best place to debug this is the discord channel.

**Comment by Bastien42** [comment]
Well no no side software that communicate with radarr I'll let you know if and when my ram usage is going to settle when my new movie are gonna be all parsed

**Comment by Bastien42** [comment]
ok so i'm fine with the fact that it need to process the movies but if it would purge itself once in a while to not lock up the system and bock everything and crash the pc that would be fine my only option that i se now is to count how long it takes for the system to be unstable and force close radarr service and relaunch it every 30 / 60 min until all the files are process

**Comment by Qstick** [comment]
What's your setup, you mentioned windows in the title but no details? I can't say I've seen it hog that much memory on windows without cleaning up, but would agree it's not ideal.

**Comment by Bastien42** [comment]
Operating System
	Windows 10 Professionnel 64-bit
CPU
	Intel Core i7 @ 3.60GHz	72 °C
	Kaby Lake 14nm Technology
RAM
	32.0GB
Motherboard
	Gigabyte Technology Co. Ltd. Z390 GAMING SLI-CF (U3E1)	42 °C
Graphics
	6GB NVIDIA GeForce RTX 2060 (Gigabyte)	54 °C
Storage
	9314GB Western Digital WDC WD100EZAZ-11TDBA0 (SATA )	34 °C
	9314GB Western Digital WDC WD100EMAZ-00WJTA0 (SATA )	30 °C
	931GB Seagate ST31000524AS (SATA )	25 °C
	447GB Crucial CT480BX300SSD1 (SATA (SSD))
	9314GB Western Digital WDC WD100EMAZ-00WJTA0 (SATA )	28 °C
	2794GB Seagate ST3000DM001-1ER166 (SATA )	27 °C
	9314GB Western Digital WDC WD100EZAZ-11TDBA0 (SATA )	33 °C
	465GB Samsung SSD 970 EVO 500GB (Unknown (SSD))
	2794GB Seagate ST3000DM001-1ER166 (SATA )	27 °C
	7452GB Seagate ST8000DM004-2CX188 (SATA )	28 °C
	7452GB Seagate ST8000DM004-2CX188 (SATA )	28 °C
	9314GB Seagate ST10000VN0004-1ZD101 (SATA )	27 °C
Optical Drives
	No optical disk drives detected
Audio
	Realtek High Definition Audio

**Comment by Bastien42** [comment]
i mean if when the job of parsing all the new movies it goes back to normal sure i'm fine with it not really practical but a simple script make it less of a problem now if it will do that everytime it refresh the DB or else well that will be an issue for me

**Comment by Bastien42** [comment]
Ok so after 2 days with that script on order to flush the ram every hour it settled down to 300mb of constant usage so it was normal the only thing I would like to be implemented is a way for radarr to flush the ram when I goes through that kind of a process

**Comment by bakerboy448** [comment]
@Bastien42 is this still going on on the recent builds?
(Likely nothing addressing this exactly recently, but it may have just been a gremlin)

**Comment by bakerboy448** [comment]
So to be clear the ram usage only spikes when importing a metric ton of movies from lists? Or when specifically does it occur?

If you're not implying a ton at once, does it work fine?

Did you ever get a chance to troubleshoot this with the folks on discord?

**Comment by Bastien42** [comment]
So not when importing per say but when metadata is fetch for every new movie as it start a task per movie in the task tab and when you have a lot the Hoggin start spikes up then go back down but not as down as it was before the spike and so on until it tops up your ram hence restarting radarr flushes that and starts over until the fetching is over

**Comment by bakerboy448** [comment]
@Bastien42 any change on recent builds?

the net5 branch does improve performance a bit....may or may not solve the unknown ram issue

it should be merged into nightly soon(tm)

**Comment by bakerboy448** [comment]
closing pending information from OP that this occurs on recently releases
