### ISSUE TITLE
Custom filter: file paths

### ISSUE THREAD

**Issue by agneevX** [Radarr/Radarr#5044]
**Is your feature request related to a problem? Please describe.**
I want to create filters based on file paths. 

E.g. to filter REMUX movies.

**Describe the solution you'd like**
A new filter, `File Path` should be added, and `Path` should be renamed to `Folder Path`.

**Describe alternatives you've considered**
I've tried setting `Size on Disk`, but that's inconclusive at best. 

**Additional context**
N/A

**Comment by Qstick** [comment]
Likely not going to happen, not planning to introduce file related filters now as we’ll be going to multiple files per movie support eventually.
