### ISSUE TITLE
Wanted overview page missing

### ISSUE THREAD

**Issue by bruvv** [Radarr/Radarr#5045]
**Is your feature request related to a problem? Please describe.**
Since Radarr V3 is trying to look like sonarr's v3, why not use the same left bar? I am missing the ```wanted``` button on the left where I have a easy to see list overview with stuff that is still missing or where the cutoff is still unmet:
![afbeelding](https://user-images.githubusercontent.com/3063928/93875668-edb3e200-fcc4-11ea-938e-d3383068f3e8.png)

**Describe the solution you'd like**
Add the wanted page button on the left under Activity.

**Describe alternatives you've considered**
I know there is a filter option in the movies overview page. But that is different from Sonarr and I think Sonarr's way is more structered.

**Comment by hotio** [comment]
Who says radarr is trying to look like sonarr v3? It removed the wanted page, because it didn't want to look like sonarr anymore...

It's removed on purpose, it's not coming back, there's a filter called Wanted instead.

**Comment by ta264** [comment]
Like hotio says, there's a filter now.

**Comment by bruvv** [comment]
> Who says radarr is trying to look like sonarr v3? It removed the wanted page, because it didn't want to look like sonarr anymore...
Wait:

> New UI (Based on Sonarr with some Radarr Tweaks)
By removing the wanted page that doesn't mean it isn't loooking like Sonarr, it is exactly the same UI/UX/Look. With the word "tweaking" I see small tweaks that are usefull for radarr. Not removing usefull stuff.
 
> It's removed on purpose, it's not coming back, there's a filter called Wanted instead.
Like mentioned, I know the filter is there. But it makes much more sense since Radarr and Sonarr are 100% look a likes, to have at least a wanted button.

**Comment by hotio** [comment]
No they are not 100% look a likes, it's changed on purpose, probably for a good reason...

True, UI/UX/Look they might look similar, but under the hood they are totally different and that's probably what caused the removal of Wanted.....

**Comment by bakerboy448** [comment]
For posterity....there is now a reddit post for this as well https://www.reddit.com/r/radarr/comments/ixllpt/wanted_overview_page_missing/

**Comment by hotio** [comment]
What's stopping them from forking and adding back their precious `Wanted` tab? Yes, nothing.

**Comment by Qstick** [comment]
> No they are not 100% look a likes, it's changed on purpose, probably for a good reason...
> 
> True, UI/UX/Look they might look similar, but under the hood they are totally different and that's probably what caused the removal of Wanted.....

Exactly, Sonarr has child objects (Seasons and Episodes) in their data model, thus they need seperate pages/views (Season Pass, Wanted, Cutoff) to show relevant information about said objects... For Radarr we were showing the same info in three or four different views that needed to be managed.. thus the simplification

**Comment by wsegatto** [comment]
By the way, I'm a supporter of the Radarr project (moneywise).
OK, so what if I have downloaded a movie in my downloads folder and I want to import it like I used to do with the interactive import, how can I do it? 
In the movie page, it only looks for files in the own movie folder. Should I now manually copy the file to the right folder? I don't see the benefit of removing a working feature.

**Comment by bakerboy448** [comment]
Movies page

Manual filter at the top

**Comment by wsegatto** [comment]
I was so fixated on having the Wanted option that I completely forgot about that option. Thanks for the quick reply.
