### ISSUE TITLE
NZBhydra limited to 100

### ISSUE THREAD

**Issue by Firemad03** [Radarr/Radarr#505]
Hi,

Radarr is limited to check for only 100. Since I'm using nzbhydra with multiple indexer and sometime I'm using a foreign language (french in my case) the result can be at 400 for example.

I suggest to add a setting for people to increase it if they want.

Thanks

**Comment by theotherp** [comment]
Sonarr has a "Additional settings" box which would allow changing the limit (among others). That would probably be enough.

**Comment by onedr0p** [comment]
Where in sonarr is that?

**Comment by theotherp** [comment]
In the indexer settings where you enter your host, API key, etc.

**Comment by onedr0p** [comment]
Additional parameters? What do you put there?

**Comment by theotherp** [comment]
&limit=500

**Comment by galli-leo** [comment]
IIRC this should be working fine with the additional params. @onedr0p Can you check this?

**Comment by onedr0p** [comment]
I planned too

**Comment by onedr0p** [comment]
This is already there, enable show hidden settings on the indexer page and the additional parameters will show when you add the indexer.
