### ISSUE TITLE
[Metadata] Language .NFO file

### ISSUE THREAD

**Issue by jasimancas** [Radarr/Radarr#5051]
**Is your feature request related to a problem? Please describe.**
Radarr generates the folder and the file name in the select language, in my case Spanish using :ES in the renaming section.
But when it generates the NFO file it doesn't take into account the language and it generates the NFO file with the information in English.

**Describe the solution you'd like**
Allow the choice of language when generating the NFO file

**Describe alternatives you've considered**
Generate the NFO file using the language we have selected to display the movie data in the menu Settings -> UI

**Comment by danimart1991** [comment]
If it's okay, I'm going to take this issue to develop it.
