### ISSUE TITLE
Feature request to add "Hindi", "Tamil", "Telugu", "Bengoli/Bengali", "Marathi" and "Punjabi" as Indian Languages for Hindi & Bollywood Movies ?

### ISSUE THREAD

**Issue by devmanojsoni** [Radarr/Radarr#5057]
**Is your feature request related to a problem? Please describe.**
Could you please add at least "Hindi" language as an option in the profiles section or a custom format like "L_Hindi" ? like you have provided for English & French movies?

**Describe the solution you'd like**
Most of the Indian Film Industry make movies in the Hindi Language & and the South part of India (South Indian Film Industry) makes movies in Tamil and Telugu languages, many people even prefer watching South-Indian movies instead of Bollywood Movies. Many of the torrents of Hindi-dubbed movies I have come across  after searching with jackett have the words like 
"hindi", "hi", "hi-in", "hin", "Hindi", "Hi", "Hi-IN", "Hin", "HINDI", "HI", "HIN", "hi+en", "HI+EN", "HI+ENG"  included which tells us about the Language(s)
I know we can easily separate these by a custom format something like 
**C_RXRQ_\B(HINDI|HI|HI-IN|HIN)\B**
which I personally use, wouldn't it be nice If we could have an option to select the language "Hindi" in the profile section ?

![addhindi](https://user-images.githubusercontent.com/35931433/94142766-6913c000-fe8c-11ea-94bb-8a881eb361fc.PNG)

**Describe alternatives you've considered**

**Additional context**

**Comment by Qstick** [comment]
Dupe #3597
