### ISSUE TITLE
Trakt not Synching (anymore)

### ISSUE THREAD

**Issue by Bavich** [Radarr/Radarr#5058]
Hi,

Since few weeks ago trakt list is not importing new movies to Radarr. It was working without any issue previously.

Please note:

- it's a public list
- I deleted the list from Radarr and added it again. Didn't solve the issue.

Please find below my logs:
https://nvm.d.pr/cARP1P

My settings:
https://nvm.d.pr/JjSRSR

I'm currently running Radarr on a Docker (linuxserver.io) with a Preview build.

Thank you !

**Comment by ta264** [comment]
Please fill in the template you deleted

**Comment by Bavich** [comment]
**Describe the bug**
Since few weeks ago trakt is not importing any new movie to Radarr. There's no issue connecting Trakt to Radarr. When I test to connection a message confirming that is working appear: "Testing Trakt list succeeded". I've also increased the the limit to 10.000 files.
I also tried to delete the list an re-add it but it did not solve the issue.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to 'Settings'
2. Click on 'Lists'
3. Add a new 'Trakt list.'
4. There's no error

**Expected behavior**
Import new movies added to the trakt list.

**Screenshots**
https://nvm.d.pr/JjSRSR -> this is the Trakt list. (it used to work)

**Platform Information (please complete the following information):**
 - OS: Docker (linuxserver.io)
 - Mono Version: 4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4)
 - Browser and Version N/A
 - Radarr Version 0.2.0.980
- Preview build

**Debug Logs**
https://nvm.d.pr/cARP1P (Debug)
https://nvm.d.pr/AdsQwp

**Comment by ta264** [comment]
Are you seriously on 0.2.0.980? And pestering us for support?

**Comment by ta264** [comment]
Screenshot is indeed of 0.2. that build is from march 2018!
