### ISSUE TITLE
Integrate disc and keyart like a metadata files type.

### ISSUE THREAD

**Issue by jasimancas** [Radarr/Radarr#5059]
**Is your feature request related to a problem? Please describe.**
disc.png and keyart.jpg are image files from the movie (metadata) but radarr classifies them as "other

**Describe the solution you'd like**
Integrate this files like a metadata files

![image](https://user-images.githubusercontent.com/15717847/94180771-d03a7000-fe9e-11ea-81aa-9bb6ec89d45a.png)

**Comment by Qstick** [comment]
Can add keyart, disc should be discart per Kodi naming: https://kodi.wiki/view/Movie_artwork
