### ISSUE TITLE
Browser Scaling - Download button missing from manual search

### ISSUE THREAD

**Issue by daithi-coyle** [Radarr/Radarr#5067]
**Describe the bug**
Do a manual search from a movie page. Lots of results show up but there's no download button. There's also no horizontal scroll bar at the bottom of the browser window (although if you scroll to the last entry in the search results there is a scroll bar after the last result).

Zooming out to 90% displays the manual download button

**Expected behavior**
Scroll bar at the bottom of the browser window OR interface scaled to fit a smaller display

**Screenshots**
https://imgur.com/6NvZdYS

https://imgur.com/toRra65

**Platform Information (please complete the following information):**
 - OS:
 Radarr running in docker on ubuntu server
 Accessed via browser on Win10

Firefox 81.0 64-bit

Radarr Version 3.0.0.3743-ls23 by linuxserver.io

**Debug Logs**
Not relevant?

**Comment by austinwbest** [comment]
Can you fill out the template you deleted? Specifically the version. I think i know what the issue is but want to confirm

**Comment by daithi-coyle** [comment]
Yes, sorry.

**Comment by Qstick** [comment]
This is a duplicate issue, there is a horizontal scrollbar but it's all the way down the list

**Comment by Qstick** [comment]
Use #3926
