### ISSUE TITLE
[Aphrodite] Profile language still not used for title and metadata 

### ISSUE THREAD

**Issue by kcgthb** [Radarr/Radarr#5069]
**Description**
_This is a follow-up of #4862_ 

The chosen profile language is not used anymore to determine a movie's title, and its synopsis. This leads to movie folder names all being created in English. rather than the profile language, as was done before.

**Details**
I upgraded to Aphrodite, and as far as I can tell, the language in Profiles is still ignored. Up to recently, when a profile was set with a specific language (like French) in Settings > Profiles > Edit > Language, movies using that profile had their title and synopsis set in the profile's language (French). Now they appear to be set in English when new movies are added, or existing movies are refreshed, irrespective of the profile's language.

This doesn't seem to be related to specific movies, as movies that were previously added and for which the title had originally be set in French, are now changed to their English title and synopsis when their metadata is refreshed (by clicking the "Update movie info and scan disk" button.

Actually, things seem to change over time, and movies which had their metadata retrieved in French, and were later changed to English, have sometimes been re-changed to French, and then English again, depending on when the "Update" button is clicked. Which seems to maybe be pointing to Skyhook?

Anyway, having the movie synopsis, and most importantly, the movie title and the corresponding folder on disk use the language configured in the chose profile was something that used to work and doesn't anymore.

I've seen the new "Movie Info Language" setting, but it's not an equivalent solution and setting a language system-wide won't work for libraries containing titles in multiple languages. I've seen [mention](https://github.com/Radarr/Radarr/issues/4971#issuecomment-689110999) of a possible "Original Language" option for that setting, which would certainly solve the problem, but it doesn't look like it's implemented yet, right?

**Radarr version**
3.0.0.3785

**Comment by kcgthb** [comment]
Also, I tried changing the "Movie Info Language", but it doesn't look like it's taken into account for movie folder names.
What would be the best way to create folder names in the language specified in the movie profile?

Thanks!

**Comment by kcgthb** [comment]
Thanks for merging #5083, that brings things much closer to my desired goal!

Now, if we could just find a way to display the title and metadata of a movie in the language defined in the Profile (or even better, in a separate Language Profile as suggested in #5074), that would be perfect!

**Comment by Qstick** [comment]
There's already another PR for that

**Comment by kcgthb** [comment]
Ah great to hear! I couldn't find it here, do you have the PR number, by any chance?

**Comment by Qstick** [comment]
It’ll be part of https://github.com/Radarr/Radarr/pull/4980

**Comment by kcgthb** [comment]
Thank you!

**Comment by kcgthb** [comment]
Thanks @Qstick for merging #4980, that's great progress!
Now, if we could only choose to display movie info in the language set in a movie's profile, that'd be terrific! I've opened #5156 for this.
