### ISSUE TITLE
Radarr copies soft links from torrent folder and overwrites actual movie files

### ISSUE THREAD

**Issue by kskarlatos** [Radarr/Radarr#5073]
I have a setup where I use soft links in my torrent folder(movie file is replaced by a script with a softlink a few hours after it is copied by radarr). This works fine with Radarr and my torrent client, except when sometimes Radarr decides to re-import the movie and then it overwrites the movie file with its softlink. Can this behavior be optionally disabled? Can the copy function check for filesize or for the presence of a softlink?

**Comment by bakerboy448** [comment]
What’s your use case for ?seeding? From soft links?
Why not use hard links?

Going to need trace logs showing radarr reimporting automatically something it already imported, that should not happen, but it’s possible you’re doing something wrong to cause that to happen.

Also fill out the template you blew away.

**Comment by ta264** [comment]
I don't think we have any appetite to support softlinks in any way at all.  I'm not convinced your suggested change would solve more problems than it fixes.

**Comment by kskarlatos** [comment]
> What’s your use case for ?seeding? From soft links?
> Why not use hard links?
I use multiple drives, one for the torrent download folder and 5 for the movie library, so hard links don't work for me.
> 
> Going to need trace logs showing radarr reimporting automatically something it already imported, that should not happen, but it’s possible you’re doing something wrong to cause that to happen.
It happened when i changed the language of my quality profile from English to any. It then decided to re-import all my non english movies. My logging settings at the time were the default ones and i don't see anything useful in them. 

In the past year is has also happened sporadically

> 
> Also fill out the template you blew away.



**Describe the bug**
I think there are two bugs:
1) When changing language of the quality profile from english to any, Radarr reimports all non-english movies
2) When reimporting, radar copies soft links from torrent folder and overwrites actual movie files. 

**To Reproduce**
Steps to reproduce the behavior:
1)Have movies with a quality profile set to english
2)change language to any

**Expected behavior**
Nothing that should affect currently imported movies

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Platform Information (please complete the following information):**
 - OS: Arch linux
 - Mono Version: .NET Core
 - Radarr Version 3.0.0.3792

**Debug Logs**
I would like to produce them. 
Do you think a new installation with a couple of movies would be enough? I can also provide backups of the db before and after the problem.

**Comment by kskarlatos** [comment]
> I don't think we have any appetite to support softlinks in any way at all. I'm not convinced your suggested change would solve more problems than it creates.

I am not asking for any support for soft links, just for a check that an existing movie is not overwritten by an obviously invalid file. If this is something you are not willing to fix, may i kindly ask that you point me to the correct file to edit as i am unfamiliar with .NET. is it src/NzbDrone.Common/Disk/DiskTransferService.cs? 
thanks

**Comment by bakerboy448** [comment]
waiting for trace logs

**Comment by kskarlatos** [comment]
Unfortunately i didn't have trace logs open at the time. I have backups of the db before and after the problem, can that help in any way?

**Comment by bakerboy448** [comment]
Likely not.

Presumably you can reproduce the issue with trace logs sometime in the future?

**Comment by kskarlatos** [comment]
I will try in the next few weeks and post updates here. Thanks for your time :)

**Comment by bakerboy448** [comment]
any updates @kskarlatos

**Comment by bakerboy448** [comment]
closing pending information from OP that this occurs on recent releases
