### ISSUE TITLE
improve movie title matching

### ISSUE THREAD

**Issue by kaso17** [Radarr/Radarr#508]
Hello,

with short/common movie titles indexers without imdb search option often return incorrect results which then results in the wrong movie being downloaded.
See this example for the movie "Sing 2016"
![image](https://cloud.githubusercontent.com/assets/2273360/22393643/90f65d20-e4bf-11e6-8df9-25b5ea27f922.png)

**Comment by galli-leo** [comment]
There is nothing much we can do about that :( Anyways if the title does not match exactly it shouldn't download them.

**Comment by onedr0p** [comment]
Should be more accurate in next release.

**Comment by testarea1** [comment]
In follow up to this, radarr just grabbed the movie "Life 1999 1080p BluRay..." when the movie "Life (2017)" was added to radarr. I have radarr connected to jackett to grab releases and it grabbed it from indexer privatehd.to

**Comment by galli-leo** [comment]
@testarea1 Are you on the latest nightly?

**Comment by testarea1** [comment]
Yes, I'm on the develop branch setup, currently on version 0.2.0.299

**Comment by galli-leo** [comment]
@testarea1 That is not the latest nightly. To change to the latest nightly you have to change the branch to nightly.

**Comment by testarea1** [comment]
Oh sorry, I wasn't aware of the "nightly" option and was thinking of "develop", I'll change it over from develop later on.

Where there fixes for title searching in the latest nightly?

**Comment by galli-leo** [comment]
@testarea1 Yup I should have fixed your issue
