### ISSUE TITLE
Branch 'aphrodite' has been merged, switch to 'nightly' for further V3 development

### ISSUE THREAD

**Issue by thezoggy** [Radarr/Radarr#5086]
**Describe the bug**
I'm a 'aphrodite' user, and got the warning that branch was merged and to switch to 'nightly'.. but there is no 'nightly' branch
Should that have just said 'develop' ?

**Platform Information (please complete the following information):**
 - OS: [Windows10]
 - Mono Version: [N/A]
 - Browser and Version [N/A]
 - Radarr Version [3.0.0.3790]

**Comment by bakerboy448** [comment]
Not a bug.

Yes “nightly” is a branch

Just change your branch to nightly and you’ll be all set. (Assume not docker)

If docker, change your docker tag to nightly as well for either LSIO or Hotio

**Comment by thezoggy** [comment]
Gotcha, yeah was confused cause i came to GH expecting to see a 'nightly' branch but I see per digging through source its only up on azure. I tried 'develop' thinking it would be the 'stable' nightly as wiki noted.. but that then takes you to 2.x. So yeah kinda stuck on having to do nightly... so why not just auto migrate v3 users to it if there isnt another choice? and why the need now?

**Comment by thezoggy** [comment]
since switching to nightly, updates fail now
```
2020-9-30 22:07:13.8|Trace|HttpClient|Res: [GET] https://radarr.servarr.com/v1/update/nightly?version=3.0.0.3790&os=windows&arch=X64&runtime=netcore&runtimeVer=3.1.7: 200.OK (193 ms)
2020-9-30 22:07:13.8|Info|InstallUpdateService|Deleting old update files
2020-9-30 22:07:14.2|Trace|CommandQueueManager|Updating command status
2020-9-30 22:07:14.2|Error|Radarr.Update.exe|Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'System.Threading.Thread, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
2020-9-30 22:07:14.2|Error|Radarr.Update.exe|File name: 'System.Threading.Thread, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
2020-9-30 22:07:14.2|Trace|CommandExecutor|ProcessMonitoredDownloadsCommand -> DownloadProcessingService
2020-9-30 22:07:14.2|Trace|CommandQueueManager|Marking command as started: ProcessMonitoredDownloads
2020-9-30 22:07:14.2|Error|Radarr.Update.exe|   at NLog.Internal.ExceptionHelper.MustBeRethrownImmediately(Exception exception)

...

2020-9-30 22:07:14.2|Error|CommandExecutor|Error occurred while executing task ApplicationUpdate

[v3.0.0.3790] System.UnauthorizedAccessException: Access to the path 'clrjit.dll' is denied.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at System.IO.Directory.Delete(String path, Boolean recursive)
   at NzbDrone.Common.Disk.DiskProviderBase.DeleteFolder(String path, Boolean recursive) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 300
   at NzbDrone.Core.Update.InstallUpdateService.InstallUpdate(UpdatePackage updatePackage) in D:\a\1\s\src\NzbDrone.Core\Update\InstallUpdateService.cs:line 118
   at NzbDrone.Core.Update.InstallUpdateService.Execute(ApplicationUpdateCommand message) in D:\a\1\s\src\NzbDrone.Core\Update\InstallUpdateService.cs:line 276
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand[TCommand](TCommand command, CommandModel commandModel) in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 88
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands() in D:\a\1\s\src\NzbDrone.Core\Messaging\Commands\CommandExecutor.cs:line 44

2020-9-30 22:07:14.2|Trace|Http|Res: 28 [GET] /api/v3/command: 200.OK (2 ms)
```

**Comment by bakerboy448** [comment]
Go ahead and use the link in the updater logs and manually update...stuff probably got screwed up when you dropped to v0.2

GitHub read me pretty obviously says what’s nightly, what’s develop,  does it not?  Where’s the wiki say what you saw...may need to edit it 😅?

**Comment by thezoggy** [comment]
i think the branch change caused a stale instance and never fully exited. killed it all and manually grab latest nightly and upgraded. back up on latest now.

settings > general > 'more info' under the branch links to:
https://github.com/Radarr/Radarr/wiki/Release-Branches

**Comment by thezoggy** [comment]
radarr defaults their branch to 'develop' - which got is where aphrodite got merged to but still has 2.x numbers? anyways seems a bit wonky. hopefully gets all sorted

**Comment by bakerboy448** [comment]
> i think the branch change caused a stale instance and never fully exited. killed it all and manually grab latest nightly and upgraded. back up on latest now.
> 
> settings > general >updates - 'more info' links to:
> https://github.com/Radarr/Radarr/wiki/Release-Branches

sounds accurate!

Thanks; I've updated that wiki page!



> radarr defaults their branch to 'develop' - which got is where aphrodite got merged to but still has 2.x numbers? anyways seems a bit wonky. hopefully gets all sorted

Where do we still have v2 lurking around?  Nightly should all be v3

**Comment by thezoggy** [comment]
when I tried to use `develop` it was showing me 2.x stuff and warning that the branch isnt supported for 3.x

**Comment by bakerboy448** [comment]
hmmm have some screenshots to provide?

And using develop on a v3 install, correct?

**Comment by thezoggy** [comment]
if you do `develop` while on `nightly` (or when i was on `aphrodite`:
![radarr1](http://zoggy.net/firefox_2020-09-30_22-39-20.png)

**Comment by austinwbest** [comment]
you want the nightly channel, it is the develop branch. just syntax

**Comment by bakerboy448** [comment]
that's likely because the updater checks for updates and displays for updates based on the branch it is on.

You already get the health check, so I think it is fine.

**Comment by thezoggy** [comment]
> 
> 
> you want the nightly channel, it is the develop branch. just syntax. use nightly where it asks for the branch.

yes, we've established that `nightly` is the only branch v3 users can/should be using. which repeats my question, why not just migrate the users from aphrodite to nightly vs causing the confusion (as the wiki would make you think you could do develop especially since 'aphrodite' was merged to develop)

**Comment by thezoggy** [comment]
> 
> 
> > i think the branch change caused a stale instance and never fully exited. killed it all and manually grab latest nightly and upgraded. back up on latest now.
> > settings > general >updates - 'more info' links to:
> > https://github.com/Radarr/Radarr/wiki/Release-Branches
> 
> sounds accurate!
> 
> Thanks; I've updated that wiki page!
> 
> > radarr defaults their branch to 'develop' - which got is where aphrodite got merged to but still has 2.x numbers? anyways seems a bit wonky. hopefully gets all sorted
> 
> Where do we still have v2 lurking around? Nightly should all be v3

thanks for updating the wiki.

**Comment by austinwbest** [comment]
Im not sure the confusion, the message tells you what to do. The branch structure in GIT is not what is used, there are release channels.

**Comment by bakerboy448** [comment]
@austinwbest the wiki still had develop, nightly (implying v0.2), and aphrodite which i imagine caused the confusion, but I did a quick fix on that.

**Comment by austinwbest** [comment]
be that as it may, the original question was about the message shown in the UI so that is all i was referring to :)

Switch from aphrodite to nightly, at which point v3 picks back up and everything is good

**Comment by thezoggy** [comment]
> 
> 
> Im not sure the confusion, the message tells you what to do. The branch structure in GIT is not what is used, there are release channels.

the confusion is that the warning says the code got merged and that lead me to thinking that master/develop is the norm and i wanted to get new stuff but stay on stable and per wiki 'develop' what what it said to use (that is linked right there below the branch box). the confusion easily could have just been avoided by saying that the 'aphrodite' branch is going away and use 'nightly' (or you know, just auto migrate the users).

**Comment by bakerboy448** [comment]
perhaps the wording on the final aphrodite release could have been better.

the wiki was 100% confusing and wasn't update which likely lead to your confusion, it's all good now right zoggy?

**Comment by thezoggy** [comment]
yes

**Comment by austinwbest** [comment]
Devs tend to talk in a dev manner, so you got "merged" instead of "nuked" and i am not sure he made the choice not to add the branch as a migration, possibly to not force people? 

The working i guess should be channel instead of branch maybe? I dunno, 99% of people dont ask or care as long as it works so possibly why it isn't changed.

All of the documentation is a WIP so you'll have to stay on baker to get it sorted :)
