### ISSUE TITLE
Other language Title issue

### ISSUE THREAD

**Issue by Firemad03** [Radarr/Radarr#509]
I use Radarr for English and French.

I found that the title can change in French. For example the movie The Accountant is renamed to Mr Wolff and because of that when I'm searching movies with Radarr connected to nzbhydra they can't find it because Radarr see it as an unknown release movie not found because the title is different.

If I hit the tab for the search I can see all the movie with the right name "The Accountant" and if I check I can see the french one because in other language they add the word french in the title of the movie.

As a workaround I changed my profile to use the language English and I'm using the must contain with the word French but the language profile doesn't work as expected.

I saw the problem too with "The 5th Wave" renamed to "La 5ème Vague" but I got the same symptom. I don't know if it's because of the translation of the title or not.

As a side note I didn't have this problem with Sonarr at all for TV show and I checked my Sonarr and they don't translate the title and the description ? I don't know it's just a guess.

Thanks

**Comment by galli-leo** [comment]
Does your indexer support searching by imdbid? Also does the english original title show up in the details page under also known as?

**Comment by galli-leo** [comment]
Can you provide a screenshot of your search tab?

**Comment by Firemad03** [comment]
Yes my indexer support searching by imdbid. Some don't but I disabled them with nzbhydra for Radarr.
Yes the english original title is showing up fine. I can see the original title with the french word for example but for some reasons Radarr think it's unknown. I'll post some screenshots later.

**Comment by Firemad03** [comment]
![2017-01-29 14_12_33-mr wolff - radarr](https://cloud.githubusercontent.com/assets/24792889/22407063/394fef90-e62d-11e6-9275-c9210c74ed35.png)
![2017-01-29 14_13_32-la 5eme vague - radarr](https://cloud.githubusercontent.com/assets/24792889/22407062/394fb84a-e62d-11e6-9328-99a9eff33f69.png)

**Comment by Firemad03** [comment]
I uploaded 2 example. 

The Accountant for example see very well the movie but show as unknown release and don't detect the english one.

The 5th wave screenshot you will see both french and english but both of them is an unknown release. 

I think Radarr can't detect the language because it show as an unknown release but the things is it isn't an unknown release because he can see it as Bluray etc.

Both Movies is using the profile as a french language. I don't know maybe this problem can happen to other language too. 

I tried other movies and some are working fine and for some unknown reasons some movies have this problem.

**Comment by Firemad03** [comment]
![image](https://cloud.githubusercontent.com/assets/24792889/22407104/e662232e-e62d-11e6-8ef0-89f1d72b4a48.png)

Here an example of the movie 300 Rise of an Empire. The movie title is translated well in french and his able to detect the release and the type of language. I did a screenshot to show you that he detected the movies and found the language. I did the download fine for the french version.

**Comment by Firemad03** [comment]
I found something else weird. Check it out Conjuring 2:

![image](https://cloud.githubusercontent.com/assets/24792889/22407134/977a2436-e62e-11e6-9d1f-32dac4db06e0.png)
![image](https://cloud.githubusercontent.com/assets/24792889/22407136/a2720606-e62e-11e6-9fc1-4fa2965ebdc1.png)

Strange that he can detect some movies release and others release he can't.

**Comment by galli-leo** [comment]
@Firemad03 Can you post a screenshot of the accountant detail page (Poster, title, plot, etc.)

**Comment by Firemad03** [comment]
I don't know if it's related but I found this error in the logs:
Example for The 5th wave:

An error occurred while processing feed item from http://192.168.3.20:5075/api?t=movie&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060&extended=1&apikey=(removed)&offset=0&limit=100&imdbid=2304933: The string was not recognized as a valid DateTime. There is an unknown word starting at index 0

System.FormatException: The string was not recognized as a valid DateTime. There is an unknown word starting at index 0.
  at System.DateTimeParse.Parse (System.String s, System.Globalization.DateTimeFormatInfo dtfi, System.Globalization.DateTimeStyles styles) [0x0002d] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.DateTime.Parse (System.String s, System.IFormatProvider provider, System.Globalization.DateTimeStyles styles) [0x00012] in <8f2c484307284b51944a1a13a14c0266>:0 
  at NzbDrone.Core.Indexers.XElementExtensions.ParseDate (System.String dateString) [0x00029] in <3d8d3a2b296e4ac49085720b0dbdd16a>:0 

Unable to parse None: The string was not recognized as a valid DateTime. There is an unknown word starting at index 0

System.FormatException: The string was not recognized as a valid DateTime. There is an unknown word starting at index 0.
  at System.DateTimeParse.Parse (System.String s, System.Globalization.DateTimeFormatInfo dtfi, System.Globalization.DateTimeStyles styles) [0x0002d] in <8f2c484307284b51944a1a13a14c0266>:0 
  at System.DateTime.Parse (System.String s, System.IFormatProvider provider, System.Globalization.DateTimeStyles styles) [0x00012] in <8f2c484307284b51944a1a13a14c0266>:0 
  at NzbDrone.Core.Indexers.XElementExtensions.ParseDate (System.String dateString) [0x00029] in <3d8d3a2b296e4ac49085720b0dbdd16a>:0

**Comment by Firemad03** [comment]
Here the screenshot as requested:

![image](https://cloud.githubusercontent.com/assets/24792889/22407583/3a565ae6-e637-11e6-9153-1b1eff4d892c.png)

**Comment by galli-leo** [comment]
@Firemad03 Thanks I now know where the error lies. On to find out why that happens 😄

**Comment by Firemad03** [comment]
If I compare with Sonarr that is working fine and I don't know if it's related or not but the Title isn't translated and the description too. Maybe it's fine that it's translating ;) I don't know. I'm trying to help as much as I can ;)

**Comment by Firemad03** [comment]
Ah great that you find it 👍 what was the problem ? I'm curious :)

Do you want me to enable the debug log ?

**Comment by galli-leo** [comment]
No that's not necessary. Radarr should have added the US title (The Accountant) to also known as. But it didn't

**Comment by Firemad03** [comment]
On build 0.2.0.262 , I got an interesting bug too.

The language profile is detecting the NL SUB but the release is in English for the Audio :)

![image](https://cloud.githubusercontent.com/assets/24792889/22410034/da9199e8-e660-11e6-9240-0754535a83ee.png)

I don't know if I should open another issue or not but I posted it here since it's a little related.

**Comment by delphiactual** [comment]
Yes, but NL-Subs usually means hardcoded subs, so how to handle that?

**Comment by Firemad03** [comment]
I'm downloading the release to check it out. If the subtitle is hardcoded and if I put an English one if I will see both language at the same time and if yes well your right it's working as intended ;) I didn't though it was hardcoded heh you have a good point.

**Comment by Wesleyl89** [comment]
> Yes, but NL-Subs usually means hardcoded subs, so how to handle that?

Not necessarily, for this example I know QoQ just use selectable dutch subtitles and they do not engrave their subtitles in the video (hardcoded).

**Comment by Firemad03** [comment]
@galli-leo  I tested it on the build 0.2.0.269 and it's a lot better :) 👍 I'm downloading like crazy now =)

I found one Movie that got the same issue on this build:

![image](https://cloud.githubusercontent.com/assets/24792889/22445666/7da9aaca-e716-11e6-9183-ade744c6d761.png)

![image](https://cloud.githubusercontent.com/assets/24792889/22445739/dbc89d00-e716-11e6-9810-4e2dc2660ba1.png)


It's the Movie Conjuring 2013

**Comment by s0mm3rb** [comment]
> ![grafik](https://user-images.githubusercontent.com/38328575/50497330-c4561b80-0a36-11e9-835b-d14ed6429f11.png)

ok found the solution here [Radarr issue #3000 ](https://github.com/Radarr/Radarr/issues/3000#issuecomment-417580772)
the reason for this is the missing year in the release title
solve it by changing the parser settings to lenient mapping:
enable advanced settings -> goto indexers -> options -> parser leniency -> change it to lenient mapping
