### ISSUE TITLE
UI issues in the Add Movie modal

### ISSUE THREAD

**Issue by agneevX** [Radarr/Radarr#5096]
**Describe the bug**
Long movie titles in the Add Movie modal causes UI issues.

**To Reproduce**
1. Add a movie with a long title like Borat...

**Expected behavior**
* Text should not overflow, instead text exceeding a fixed width should be cut off with ellipsis,
* Add Movie modal should have a fixed width regardless of the length of movie title,
* `Add <movie_name>` should be changed to `Add Movie` so the button size stays the same.

**Screenshots**

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/19761269/94832186-39842b00-042b-11eb-905a-71464c5bad39.png">

**Platform Information:**
 - OS: N/A
 - Mono Version: N/A
 - Browser and Version: Safari 14.0
 - Radarr Version: 3.0.0.3825

**Debug Logs**
N/A

**Comment by bakerboy448** [comment]
Please edit in the radarr version :)

**Comment by Qstick** [comment]
I'm really fine either way.

**Comment by agneevX** [comment]
Thanks guys!
