### ISSUE TITLE
README.md Nightly 'develop' binary download link is broken

### ISSUE THREAD

**Issue by Ares4570** [Radarr/Radarr#5098]
The link to download the nightly v3 binary builds in README.md is broken; it leads to an error page on AppVeyor saying "Project not found or access denied."

https://ci.appveyor.com/project/galli-leo/radarr-usby1/branch/develop/artifacts

**Comment by bakerboy448** [comment]
working on a PR to fix this now

here's the links in the interim

Windows:
https://radarr.servarr.com/v1/update/nightly/updatefile?os=windows&runtime=netcore&arch=x64
Linux:
https://radarr.servarr.com/v1/update/nightly/updatefile?os=linux&runtime=netcore&arch=x64
https://radarr.servarr.com/v1/update/nightly/updatefile?os=linux&runtime=netcore&arch=arm64
https://radarr.servarr.com/v1/update/nightly/updatefile?os=linux&runtime=netcore&arch=arm
macOS:
https://radarr.servarr.com/v1/update/nightly/updatefile?os=osx&runtime=netcore&arch=x64
