### ISSUE TITLE
`In Cinemas` date formatting

### ISSUE THREAD

**Issue by woble** [Radarr/Radarr#511]
Does not respect settings. E.g. short date set to `2017-03-05` format. Wanted table view shows `2017-03-05`, Movies table view shows `March 2017`.

**Comment by geogolem** [comment]
i also thought that maybe this column in the table should be changed to "Initial Release"... so as not to confuse people.. with the "In Cinemas" tag referring to movies that are currently in Cinemas.. plus some movies never go to cinemas.. ... just posting here --- not really a big deal.

**Comment by onedr0p** [comment]
Fixed in next release
