### ISSUE TITLE
[Lists] Movieo.me

### ISSUE THREAD

**Issue by woble** [Radarr/Radarr#512]
https://movieo.me/lists

Unsure if it has API or RSS feed.

If I recall correctly, @onedr0p was looking into it at some point.

**Comment by onedr0p** [comment]
Unfortunately, I couldn't find a API or RSS to use.

**Comment by JigSawFr** [comment]
There is an private API

`https://movieo.me/api/r/movies?file[]=items%2Fmovies%2F_movies_cont&grid=list&list_id=182&from_section=list`

But it doesn't return JSON content and seems to be protected from external call.

**Comment by onedr0p** [comment]
Darn.. we should all keep an eye out if they add a API we can do something.

**Comment by onedr0p** [comment]
Closing this until a API becomes available.
