### ISSUE TITLE
Add an "Unmonitored" filter to the movies list

### ISSUE THREAD

**Issue by c0rnflake** [Radarr/Radarr#513]
Add an "Unmonitored" filter button to the current filters.

![image](https://cloud.githubusercontent.com/assets/2790597/22405167/3d0c58e0-e636-11e6-8e63-664c3438092f.png)

**Comment by hotio** [comment]
http://feathub.com/Radarr/Radarr

**Comment by geogolem** [comment]
https://github.com/Radarr/Radarr/issues/611
