### ISSUE TITLE
Add movie status to main search results page

### ISSUE THREAD

**Issue by Superawe69** [Radarr/Radarr#5144]
**Is your feature request related to a problem? Please describe.**
Not a problem

**Describe the solution you'd like**
Be able to see movie status (downloaded/monitored/missing/etc) in main search results. Right now it shows a green check, but no way to determine the movie status without clicking into movie details. Maybe add the progress bar under the poster or a label like on the details page.

Thanks!

**Comment by dramirvf** [comment]
I have a somewhat similar problem in this regard:
https://github.com/Radarr/Radarr/issues/5252

**Comment by austinwbest** [comment]
This ticket isn't for a problem, but a feature request bud.

**Comment by dramirvf** [comment]
> This ticket isn't for a problem, but a feature request bud. 

My ticket has two relevant sections which was much better to be demonstrated in a single post. 

The first part is a bug and the second part is a feature request. That feature request about using the "Availability Status" of items in different parts of Radarr is similar to the concept of this post and could be addressed simultaneously.
