### ISSUE TITLE
Add button to make default name scheme more linux friendly (replace spaces with whatever)

### ISSUE THREAD

**Issue by stormsz** [Radarr/Radarr#5149]
**Is your feature request related to a problem? Please describe.**
I think i can speak for 99.999% linux users that having file names with spaces is a pain to deal with and to read.
Stuff like: `'Spider\ Man: \Bla \bla'` instead of `Spider.Man:Bla_bla`

**Describe the solution you'd like**
A simple Check Box to automatically replace all the spaces of a file with whatever you guys are comfortable with, the ideal solution would be some sort of option, so we could chose more normal scheme like `.` `-` `_`

- [ ] Optimize names for Unix like systems

**Describe alternatives you've considered**
Right now most people have to manually edit the naming scheme of the movies in order to replace spaces with dots or whatever. Granted that they only have to do this 1 time but, having this simple option to cater to the users that find the default name scheme good would be great. 

**Additional context**
Great project and great support team! Thanks.

**Comment by bakerboy448** [comment]
can you create this upstream @ sonarr :) it's much easier to pull downstream than upstream sometimes, I would think team sonarr would be reasonably interested in it

**Comment by stormsz** [comment]
Will do! Thanks!

**Comment by ta264** [comment]
I don't think you'll get any traction over at sonarr either. Just learn how to use the command line properly :D 

You can use spaces in filenames by surrounding the filename with `'`

**Comment by stormsz** [comment]
Its not about using it properly or not. its just ugly and hard to read. Having the option to auto-optimize would be great and its probably an easy thing to add.  As i said on the feature request, its an easy manual fix to just go to the options and manually replace the file name spaces with a dot, so its not a big loss if they dont care to add it.
