### ISSUE TITLE
Adding user watchlist 404.NotFound error

### ISSUE THREAD

**Issue by hasselrot** [Radarr/Radarr#5152]
**Describe the bug**
Trying to add a trakt watchlist from **another user** gives a 404.NotFound error.
Adding my own watchlist using the list type "Trakt User" seems to work.

Now if this is not the correct way to do this, please disregard me (preferably with an instruction on how to do it correctly :) )

**To Reproduce**
1. Go to settings -> Import lists
2. Add a list with the type "Trakt list"
3. Enter the username and list name, "watchlist" in my case
4. Authenticate
5. Try to test it or save it

**Expected behavior**
The list gets added to Radarr.

**Screenshots**

**Platform Information (please complete the following information):**
Version
3.0.3.938
Package Version
3.0.3.938-ls48 by linuxserver.io
Mono Version
5.20.1.34

**Debug Logs**
2020-10-06 13:31:39 | [Warn] TraktListImport: Unable to connect to list
2020-10-06 13:31:39 | [Warn] HttpClient: HTTP Error - Res: [GET] https://api.trakt.tv/users/someonesusername/lists/watchlist/items/movies?limit=100: 404.NotFound
2020-10-06 13:30:43 | -- : Unable to connect to list, check the log for more details

I have looked at the API documentation for Trakt user lists, and I think the issue could be in how the URL gets generated.
https://trakt.docs.apiary.io/#reference/users/ratings/get-watchlist
For a user watchlist it should look like this.
```https://api.trakt.tv/users/id/watchlist/type/sort```

However in:
https://github.com/Radarr/Radarr/blob/aphrodite/src/NzbDrone.Core/ImportLists/Trakt/List/TraktListRequestGenerator.cs
It looks like it will create a url like this:
```link += $"users/{Settings.Username.Trim()}/lists/{listName}/items/movies?limit={Settings.Limit}";```
Which seems consistent with my logs.

It seems that the RequestGenerator assumes that the list is of "Custom" type, described here:
https://trakt.docs.apiary.io/#reference/users/list-items/get-items-on-a-custom-list

 
Again, if this is not the way to add another users watchlist, please let me know and disregard this :)

**Comment by bakerboy448** [comment]
3.0.3.938 does not appear to be a Radarr version...are you sure that information is not from sonarr?

Also please don't edit the logs that you're sharing...it makes giving any support impossible.

Also more than likely that is not a bug, this appears to be a support request please use the subreddit or discord.

**Comment by hasselrot** [comment]
Haha you are right of course!
I messed up the tabs!

Version
3.0.0.3790
Package Version
3.0.0.3790-ls25 by linuxserver.io
.NET Core
Yes

Ok, I will try that. Thank you!
