### ISSUE TITLE
Display Movie Info in Profile Language

### ISSUE THREAD

**Issue by kcgthb** [Radarr/Radarr#5156]
**Is your feature request related to a problem? Please describe.**
Movie information cannot be set based on a profile's chosen language. 

**Describe the solution you'd like**
Now that #4980 has been merged (thank you!) would it be possible to add an option in the Setting > UI > Language > Movie Info Language selection list that would allow movie info to be displayed in the language that is defined in the profile chose for each movie? Something like "Profile language", or even just "Profile"?

Right now, movie info can either be displayed in the same language for all movies, or in the movie's original language (thanks to #4980). There are cases where users would like to have movie info displayed in the same language they've chosen in the movie profile, independently of the original movie language.

**Describe alternatives you've considered**
v0.2 used to allow this

**Comment by austinwbest** [comment]
I think this is taking it to far personally, more and more options will keep being requested.. Here is one @Qstick , how about a dropdown on the movie details that allows real time language switching? Kinda my point there, to what end? Why? lol.. how many different languages need to be used when i can read the one it is currently in. Looking through radarr and you can see 3 or 4 languages at any given time might be neat, but to what real usable purpose to warrant the time?

If a person can read the UI then they can read the movie info in the UI language or movie language.

Just my 2 cents anyways.. Up to Q in the end as he is the one who is adding all the language options.

**Comment by kcgthb** [comment]
Well, imagine you're a German-speaking family with German-speaking kids. You want them to be able to understand their movies, so you define a Profile with German as a language, to make sure to get German versions of say English-speaking animated movies. You also want them to be able to read and recognize the titles of the movies, so having movie names and folders set in German, like in the Profile, is important.

Now, you, the parent, may read and understand English and prefer to watch international movies in English, so you setup a different Profile for those movies and set the language in that Profile to "English". But you also like Japanese movies, although you don't read Japanese. So naming the movies, their folder, and displaying the movie info in Japanese is not very helpful to you. You don't want to read those in German either, that wouldn't make much sense because they're not German movies. So you'd prefer to have Japanese movies and their info displayed in English, which is were using the original language for naming and displaying movies info doesn't work. Nor does using German or English for everything.

Bottom line, I think there's a real use case for having the movie metadata (movie info and naming templates) using the language defined in the Profile set for the movie. "Original language" is a step closer in that direction, but as with the Japanese example above, it doesn't work for every case. Multicultural households where a couple different languages are spoken is not the exception anymore, and I don't think those examples above are so far-fetched.

I don't see any downside of offering more flexibility and control over how things are displayed for the users. There's a language setting in Profiles already, and I'm not sure why it couldn't be used for the metadata associated to a movie too.

Plus, that's how 0.2 used to work, metadata was using the profile's language, so if anything, that's just trying to reach feature parity.  :)

**Comment by Qstick** [comment]
No plans to allow based on profile language right now.
