### ISSUE TITLE
Use Profile language for Movie naming

### ISSUE THREAD

**Issue by kcgthb** [Radarr/Radarr#5157]
**Is your feature request related to a problem? Please describe.**
Movie naming formats cannot be set based on a profile's chosen language.

**Describe the solution you'd like**
Similar to #5156, would it be possible to add a movie name token in the Setting > Media Management > Movie Naming > Standard Movie Format and Movie Folder Format fields, that would allow a movie to be named in the language that is defined in the profile chose for each movie? Something like "{Movie Title:Profile}" ?

Right now, movies (and folders) can either be displayed in the same language for all movies, or in the movie's original language. But there are cases where users would like to have movie named in the same language they've chosen in the movie profile, on a per-movie basis, and independently of the original movie language.

**Describe alternatives you've considered**
v0.2 used to allow this

**Comment by Qstick** [comment]
No plans to allow this as of 3.0, we may have naming as part of a profile in future at a later point that would allow for this
