### ISSUE TITLE
Alignment bug in "Edit quality profile" for scoring "Custom formats"

### ISSUE THREAD

**Issue by Nimradd** [Radarr/Radarr#5160]
**Describe the bug**
Alignment bug for the scoring of Custom formats when editing quality profiles. There's a huge empty space between the language setting and Custom Formats.

**To Reproduce**
1. Settings -> Profiles -> Click a profile
2. Notice alignment issue, see screenshot

**Expected behavior**
Expect the Custom Formats scoring to appear directly beneath the language settings.

**Screenshots**
![image](https://user-images.githubusercontent.com/58888762/95375617-274d3580-08e0-11eb-9d3a-97a1bdcd2520.png)

**Platform Information (please complete the following information):**
 - OS: Windows 10
 - Chrome 85.0.4183.121
 - Radarr Version 3.0.0.3873

**Debug Logs**
UI issue, not really applicable

**Comment by Qstick** [comment]
Fixed aeda4cb
