### ISSUE TITLE
NORDIC tag handled wrong

### ISSUE THREAD

**Issue by DjRicko** [Radarr/Radarr#5169]
**Describe the bug**
NORDIC tag is not translated correctly to corresponding languages.

**To Reproduce**
1. Set Radarr to download movies in Danish
2. It'll ignore movies with NORDIC tag.

**Expected behavior**
NORDIC usually means Danish, Swedish, Norwegian, most of the time Finnish, and sometimes Icelandic.
NORDIC releases should be grabbed for either of these languages and then checked if they have the correct language in the actual video file.

**Screenshots**
https://i.imgur.com/QIRJI35.png

**Comment by Qstick** [comment]
Nordic typically means subs, which is why it's not handled that way

**Comment by DjRicko** [comment]
NORDIC doesn't NOT mean subs unless it's english only and no dubbed version exists, usually they tag it NORDiCSUBS or similar if it's only subbed and a dubbed version does exists, like for most animated cartoons etc. At least give us the option to force it to take the tag like this, download it and check the audio language of the file.

**Comment by ta264** [comment]
See #1352 for discussion on how NORDIC is often just subs

**Comment by Qstick** [comment]
Yea, based on that thread, it's taken out of parsing in v3 so that you can handle it how you want with CF... It varies to much in meaning from group to group, indexer to indexer.. thus we ignore it now

**Comment by DjRicko** [comment]
How would i make a custom format that would allow to parse NORDIC as Danish, Swedish, Norwegian, English Audio...
As that is what it actually is on 99% of all releases for movies.

**Comment by austinwbest** [comment]
> How would i make a custom format that would allow to parse NORDIC as Danish, Swedish, Norwegian, English Audio...
> As that is what it actually is on 99% of all releases for movies.

Head over to discord or reddit for support bud.
