### ISSUE TITLE
Awesome-HD error. 

### ISSUE THREAD

**Issue by HitsvilleUK** [Radarr/Radarr#518]
When any torrent gets added via Radarr from Awesome-hd.me the torrent client immediately errors the torrent in both rutorrent & Deluge. 
Tracker: [Failure reason \"Malformed announce\"]
Manually adding a movie directly from A-HD works fine though. 
Radarr sees nothing wrong after it grabs the torrent and happily displays downloading (for eternity, if you leave the torrent with the error in the client).
I use around 9 private trackers and this only ever happens with A-HD but does happen with every A-HD grab in Radarr.

**Comment by onedr0p** [comment]
I use AHD and I cannot replicate this. I downloaded a release last night.

**Comment by HitsvilleUK** [comment]
Mmmm. @onedr0p That's really strange. Even though HD as always shown as connectable when hitting test , I noticed after the last attempt it said failed. After removing the provider and re-adding it suddenly works. Will close.
