### ISSUE TITLE
Radarr v3 stops tracking status sabnzbd

### ISSUE THREAD

**Issue by PotatoQuality** [Radarr/Radarr#5187]
**Describe the bug**

Sometimes, after sending a download to sabnzbd, radarr v3 stop tracking the download status in sabnzbd and does not start importing the file after sabnzbd is finished.

Workaround for me is now to manually selecting another in the menu to avoid the problem.

**To Reproduce**
1. Go to movie detail page The Prestige
2. Click on perform search movie
3. Wait
4. Sabnzbd is busy with progressing the download
5. After 2 minutes the activity marker of 1 is gone
7. Sabnzbd downloaded the movie.
8. Radarr doesn't import the movie. movie got stuck in download folder of sabnzbd

**Expected behavior**

Importing the movie after sabnzbd finished her job ;)

**Screenshots**
![image](https://user-images.githubusercontent.com/2944704/95682507-d8f0ad00-0be5-11eb-855e-450602dd0420.png)

**Platform Information (please complete the following information):**
 - OS: Linux Docker 
 - Mono Version: -
 - Browser and Version: - 
 - Radarr Version: 3.0.0.3913-ls26 by linuxserver.io

**Debug Logs**
Turn on debug logs under Settings -> General and wait for the bug to occur again. **Upload the full log file here (or another site and link it). Issues will be closed, if they do not include this!**
[radarr.trace.txt](https://github.com/Radarr/Radarr/files/5539562/radarr.trace.txt)

**Comment by bakerboy448** [comment]
that is not a trace log....can you reupload

**Comment by PotatoQuality** [comment]
Hi @bakerboy448 ,

Im sorry about that. Im not sure what going there. I re-upload the trace logs.

[Uploading radarr.trace.txt…]()

**Comment by bakerboy448** [comment]
If you go Activity -> Queue -> Options -> Show Unknown Movie Items   it should show up of course that doesn't answer why it disappears:

`Line 8276: 2020-10-11 17:08:07.6|Debug|ParsingService|No matching movie Le Prestige`
The issue appears to be that Radarr is parsing the downloading release as `Le Prestige` which it claims does not exist in the DB....but the translation is on TMDb now, so it should.

**Comment by PotatoQuality** [comment]
> If you go Activity -> Queue -> Options -> Show Unknown Movie Items it should show up of course that doesn't answer why it disappears:
> 
> `Line 8276: 2020-10-11 17:08:07.6|Debug|ParsingService|No matching movie Le Prestige`
> The issue appears to be that Radarr is parsing the downloading release as `Le Prestige` which it claims does not exist in the DB....but the translation is on TMDb now, so it should be fine.
> 
> If something similar happens in the future, the first place to check would be TMDb and ensure the alt title is there.

Thanks for your help and explanation <3
