### ISSUE TITLE
Make "Download Client" linkified / clickable

### ISSUE THREAD

**Issue by drowse7en** [Radarr/Radarr#5197]
Make column entry for "Download Client" in "Queue Activity" linkified and clickable.

**Comment by austinwbest** [comment]
Link to....

**Comment by bakerboy448** [comment]
@drowse7en where should the link, link to?  the client itself or the client settings?

**Comment by drowse7en** [comment]
> @drowse7en where should the link, link to?  the client itself or the client settings?

To the download client's Web UI.

**Comment by ta264** [comment]
Personally I don't think this is a good idea.  There's no guarantee at all that the details given to radarr to connect to the download client would be usable for the browser accessing the radarr UI.  I think this would cause more problems than it solves.

**Comment by austinwbest** [comment]
I also don't think it is solving any problem but creating potential ones as ta  mentioned
