### ISSUE TITLE
Radarr always take the lowest file size for a release

### ISSUE THREAD

**Issue by Firemad03** [Radarr/Radarr#520]
Hi,

Radarr always take the lowest file size available but it's wrong or at minimum make it as an option.

The reason why it's wrong is because if I want the highest quality possible because I don't care about the file size and because of that I will have a problem.

Here a screenshot:

Radarr added the 
![image](https://cloud.githubusercontent.com/assets/24792889/22408397/2bd9b95e-e646-11e6-9633-6834cc7d7a44.png)

I manually checked the search tab and I wanted this one because of a higher quality:

![image](https://cloud.githubusercontent.com/assets/24792889/22408399/3aaecc4e-e646-11e6-9f6c-fb61f6e81f34.png)

Here the full screenshot:

![image](https://cloud.githubusercontent.com/assets/24792889/22408367/c97e6e62-e645-11e6-819f-a8c248242558.png)

Here is the reason why this release didn't work:
![image](https://cloud.githubusercontent.com/assets/24792889/22408410/556c6b9a-e646-11e6-85ae-ab98c5fb98dd.png)

I was able to reproduce this problem with all movies.

Thanks

**Comment by Firemad03** [comment]
I expected that because I put the Bluray-1080p at Unlimited that Radarr will always take the biggest file available and add it.

I understand that if someone put at limit to 10 gigs for example it will refuse it. At unlimited I expected the biggest file first.

**Comment by galli-leo** [comment]
@Firemad03 Are you on the latest nightly?

**Comment by Firemad03** [comment]
![image](https://cloud.githubusercontent.com/assets/24792889/22408483/8ed9f43c-e647-11e6-9992-46540e08bf81.png)

I don't know ;) I think ?

**Comment by galli-leo** [comment]
No. But that's fixed in the latest nightly :)

**Comment by Firemad03** [comment]
Wow nice :) 🥇  if I want to use the latest nightly , what do I put in the Branch ? I have the develop.

**Comment by onedr0p** [comment]
put 'nightly' in the branch instead of develop

**Comment by Firemad03** [comment]
Thanks !

**Comment by Firemad03** [comment]
I tried the nighly Build: 0.2.0.262  that corrected this problem.

It's a lot better :) 👍  but I found another problem:

![image](https://cloud.githubusercontent.com/assets/24792889/22409247/bb47c5fa-e654-11e6-9ddf-11ffefbf4b8d.png)

Why he didn't take the first one ? Is it because Radarr have a problem with the Remux version or it's a concidence ?

Thanks

**Comment by Firemad03** [comment]
Another one:

![image](https://cloud.githubusercontent.com/assets/24792889/22409273/4dc16a62-e655-11e6-8416-ccd0c8441828.png)

Same release from FuzerHD but it took the 18GB one.

**Comment by Firemad03** [comment]
For 300 Rise of an Empire I think it's because of the subtitle bug that I found in this thread  #509 Radarr detected the release as a dutch one because of the NL.

**Comment by Firemad03** [comment]
Build: 0.2.0.262: I tested with the Accountant. Radarr took the 8.9 gb instead of the others :) I don't know why some Movies doesn't work and others are working fine now heh

![image](https://cloud.githubusercontent.com/assets/24792889/22410432/1f7826e4-e666-11e6-99b1-062e7a3ed55e.png)

**Comment by galli-leo** [comment]
Try hovering over the red i. It should give you the reason why that release wasn't chosen
