### ISSUE TITLE
Radarr V3: permissions must contain a valid Unix permissions octal, but it is valid

### ISSUE THREAD

**Issue by pven** [Radarr/Radarr#5208]
When changing the settings I get the attached error. But I did not change that part, and it loks valid to me.

**To Reproduce**
1. Go to 'Settings'
2. Go to 'Media Management'
3. Change something (ie checking 'Delete empty folders')
4. Click 'Save Changes'
Now it doesn't save, but it shows the attached error.

**Expected behavior**
Save it ;-)

**Screenshots**
![2020-10-13 11_32_32-Media Management Settings - Radarr](https://user-images.githubusercontent.com/671621/95843661-3c92eb80-0d48-11eb-839f-6c62207a88e9.png)

**Platform Information (please complete the following information):**
 - OS: Synology DMSM 6.2
 - Mono Version: 5.20.1.34
 - Radarr Version: 3.0.0.3918

**Logging**
```
2020-10-13 11:44:34.1|Warn|RadarrErrorPipeline|Invalid request Validation failed:
 -- FileChmod: Must contain a valid Unix permissions octal
```

**Comment by Qstick** [comment]
Ref https://github.com/Radarr/Radarr/issues/4968

**Comment by taylorcox75** [comment]
Short version is for file permissions, the octal can't have any permissions allowing it to be "executable" 

Long version: Your new permission & (FilePermissions._*_) will result in **False** if any of the FilePermissions.* are true.

The following if statements in DiskProvider.cs result in **False** if any of the below conditions are met 

1. "Executable by user or group, or 'sticky bit' (if person a owns the directory, person b owns a file in the directory, person c can only change his files, not person b's"
`if ((permissions & (FilePermissions.S_ISUID | FilePermissions.S_ISGID | FilePermissions.S_ISVTX)) != 0)`
`return false`

2. "Executable or searchable by owner, group, other user"
`if ((permissions & (FilePermissions.S_IXUSR | FilePermissions.S_IXGRP | FilePermissions.S_IXOTH)) != 0)`
`return false` 
3. "You cant change the permissions to  read or write if you previously don't have permission on that file"
`if ((permissions & (FilePermissions.S_IRUSR | FilePermissions.S_IWUSR)) != (FilePermissions.S_IRUSR | FilePermissions.S_IWUSR))`
`return false`

changed #4503  

TL-DR; Looks like a feature, not a bug.  Use http://permissions-calculator.org/ and just don't check the  "Execute" under User/Group/Other
