### ISSUE TITLE
Radarr V3: Title with colon don't match searches

### ISSUE THREAD

**Issue by idittansikte** [Radarr/Radarr#5209]
**Describe the bug**

**To Reproduce**
1. Add movie "American Murderer: The Family Next Door"
2. Click on "search movie"
3. Wont wont find any movie
4. Go to search page
5. Finds a lot but is not satisfied since its not match title.

**Expected behavior**
Movies are found even though there is colon and other "decorating" chars in title.

**Platform Information (please complete the following information):**
 - OS: Linux
 - Radarr Version: Docker image linuxserver/radarr:3.0.0.3913-ls26

**Comment by austinwbest** [comment]
https://www.themoviedb.org/movie/749796-american-murderer-the-family-next-door

Gonna have an issue there.. 

https://www.themoviedb.org/movie/743601-american-murder-the-family-next-door

I think is the one you want and is duplicated with the other one that is incomplete?

**Comment by idittansikte** [comment]
Yeah, you are right, sorry for wasting your time. Did not know duplicates on TMDB was a thing...

**Comment by austinwbest** [comment]
Oh yes, will have them on all crowd based content sites. Kinda hard not to unfortunately.

All good though, glad you are sorted out!
