### ISSUE TITLE
Radarr Update Error

### ISSUE THREAD

**Issue by Firemad03** [Radarr/Radarr#521]
Hi,

Radarr just trowed me an error when I try to update. I have Freenas and Radarr is in jail. I used the Freenas installation in the wiki.

Error occurred while executing task ApplicationUpdate: ApplicationName='mono', CommandLine='--debug /tmp/radarr_update/Radarr.Update.exe 41510 /tmp/radarr_update /usr/local/Radarr/Radarr.exe ', CurrentDirectory='', Native error= Cannot find the specified file

System.ComponentModel.Win32Exception (0x80004005): ApplicationName='mono', CommandLine='--debug /tmp/radarr_update/Radarr.Update.exe 41510 /tmp/radarr_update /usr/local/Radarr/Radarr.exe ', CurrentDirectory='', Native error= Cannot find the specified file

The /tmp path is existing and the /usr/local/Radarr too.

Thanks

**Comment by onedr0p** [comment]
https://forums.sonarr.tv/t/not-able-to-update/3319/11

https://forums.sonarr.tv/t/sonarr-on-freenas-instructions/2939/11

https://forums.sonarr.tv/t/unable-to-update-sonarr-to-2-0-0-3530-oct-20-2015/7673/12

Hopefully google can help you with this, as I do not have a FreeNAS

**Comment by onedr0p** [comment]
Feel free to make a wiki page if you find a solution.

**Comment by Firemad03** [comment]
I just untar the release that was downloaded in the tmp and I cp it in /usr/local and I restarted my jail. 

Weird because with Sonarr I don't have this problem in my jail... I always update fine.

I'll check it out with the link that you found.

**Comment by Dnkhatri** [comment]
This happens to me on linux mint as well something is wrong with the radar internal updater. And needs a fix you shouldn't be closing this issue without an actual fix. Sonarr updater works fine and I never had a problem with it. This is the same issue as #495

**Comment by Firemad03** [comment]
I confirm that with Sonarr I never had a problem too.

**Comment by Firemad03** [comment]
I found the problem!

ln -s /usr/local/bin/mono /bin did the trick now I can update Radarr with GUI ! 

I'm on Freenas btw 

Do a whereis mono on Linux Mint and add it to /bin !

I think Radarr need to check where is mono and create a symbolic link to /bin.

**Comment by topper59** [comment]
Nice! This works for updating. Although, after updating it kills the internet in the jail, I get:
Request Failed: Error: NameResolutionFailure
```
System.Net.WebException: Error: NameResolutionFailure
  at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x00065] in /wrkdirs/usr/ports/lang/mono/work/mono-4.6.2/mcs/class/System/System.Net/HttpWebRequest.cs:1025 
  at System.Net.HttpWebRequest.GetResponse () [0x0000e] in /wrkdirs/usr/ports/lang/mono/work/mono-4.6.2/mcs/class/System/System.Net/HttpWebRequest.cs:1037 
  at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse (NzbDrone.Common.Http.HttpRequest request, System.Net.CookieContainer cookies) [0x000fe] in C:\projects\radarr-usby1\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:61
```

And I can't ping anything from the jail. Restarting the jail solves this problem, so it's not too bad.

**Comment by Firemad03** [comment]
@onedr0p I think Radarr need a fix for the update module. We have 2 different distribution with the same problem for the path of Mono :)

**Comment by Firemad03** [comment]
@topper59 I think the nameresolutionfailure is linked to the resolv.conf file that is missing a dns server ? I always add manually my DNS server in the resolv.conf in the jail.

**Comment by topper59** [comment]
Oh wow I'm an idiot, I was using the IP of my IPMI interface for my jail haha so the IP conflict messed up Radarr every few minutes
