### ISSUE TITLE
Support TMDB Tags in Import and Rename

### ISSUE THREAD

**Issue by NetGuru87** [Radarr/Radarr#5213]
**Feature Request: Support TMDB Tags in Import and Rename**

Plex added support for TMDB tags in filenames to improve accuracy of automatching. The tags are enclosed in curly braces and prefixed with "tmdb-". An example is "Glass (2019) {tmdb-450465}.mkv". That filename will cause Plex to always match to the correct TMDB ID.

The following feature changes are requested to align with that Plex feature:
1. Update the Bulk Import agent to look for a {tmdb-#####} tag in the filename.
2. Update the Rename agent to support a {TMDB Id} variable.

**Comment by Qstick** [comment]
We already support the naming in v3, just not the import recognition

**Comment by NetGuru87** [comment]
> We already support the naming in v3, just not the import recognition

Thanks - I have confirmed in v3 I can use the {TMDB Id}. That part of my feature request can be removed.

I tested the import agent again on my media in v3. All my files are in a format like:
- D:\Media\Best Movie (2000) {tmdb-12345678}\Best Movie (2000) {tmdb-12345678}.mkv

In addition to not checking the filename for a TMDB Id, the new bulk import screen no longer shows the TMDB ID in an editable field like in v2 to quickly fix the matches. Importing my library had more than 40 incorrect matches (as found using a custom app I wrote that compares the radarr tmdb match id to the tmdb id in the filename), but the new import tool doesn't provide an easy way to fix that as the ID is hidden. For one example of why this adds difficulty, see the movie "Emma" from 1996. More than one movie with that same name and year exist, so it is a guessing game which is correct in the dropdown using the new import agent whereas the old one had both artwork and the tmdb id for reference.

**Comment by Qstick** [comment]
You can use TMDb in that search box, like below (case doesn't matter)

![Screenshot_20201014-184620.png](https://user-images.githubusercontent.com/376117/96053496-9c26ef00-0e4d-11eb-88eb-bf5e501c803d.png)

**Comment by bakerboy448** [comment]
@NetGuru87 are we all set here then? it sounds like everything you requested already exists?

**Comment by NetGuru87** [comment]
> @NetGuru87 are we all set here then? it sounds like everything you requested already exists?

I am still looking for the import agent to look for a tmdb tag in the file name to improve the initial matching in bulk import.

The option posted by Qstick helps with manually fixing mismatches, but it does not fix the issue of improving the initial match if the tmdb info is in the file name.

**Comment by Qstick** [comment]
The import matching doesn't look at file names, we could likely look at the folder naming though and use the tmdb if there
