### ISSUE TITLE
Radarr V3: Important missing information in Radarr movie main page

### ISSUE THREAD

**Issue by dramirvf** [Radarr/Radarr#5214]
Radarr Version: 3.0.0.3918

There are some important information which are missing in the movie main page. For example, in the main movie page in Radarr, there is no way to know what the **"Genre"** of the movie is. The same is true for **"Certification"** and **"Country of Origin/Original Movie Language"**. Some other information are available, but we need to look inside the movie tabs.

Having some key information altogether as overlay on the movie background is very critical, as a single look to the page will easily provide valuable information to the user.

To highlight the issue, I have made an image which includes a brief comparison between the main movie page in **"TMDB"** and **"Radarr"**:
![image](https://user-images.githubusercontent.com/40552131/96027337-9b4d8780-0e64-11eb-8e29-60a1c4334f31.png)

[AB#794](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/794)

**Comment by bakerboy448** [comment]
![image](https://user-images.githubusercontent.com/55419169/99030447-ac101c80-253a-11eb-8457-58788e268527.png)
Most of what you want exists already now.

Outstanding items from your request
- [  ] Country of Origin
- [  ] Original Language
- [  ] Genre 

@Qstick, @ta264 any plans? can the backend support this?

**Comment by dramirvf** [comment]
And some key crews.

**Comment by bakerboy448** [comment]
> And some key crews.

See Crew Tab

**Comment by dramirvf** [comment]
I know that. TMDB also has crew tab which shows the full list of crews. But
some KEY crews are included in the main header below the description which
is really helpful, especially when you use left and right keys to switch
fast between movies and want to get a general idea without the need to go
in each tab to see the full information.

**Comment by dramirvf** [comment]
One of the other important information which is currently missing in Radarr is **"Original Title"** of the movie!

Take a look at this movie:
`https://www.themoviedb.org/movie/1997-deux-fr-res`

![Deux Frères](https://user-images.githubusercontent.com/40552131/100413587-00fc7880-308d-11eb-87f3-c4eabd8b4927.jpg)

The **"Original Title"** of this movie is "Deux Frères", but the original title is not registered in Radarr from scratch! Additionally, TMDB does not register **"Original Title"** as **"Alternative Titles"** which are included in both Radarr and TMDB.

There is no way to look for this movie by the **"Original Title"**. Only **"Translated Title (English)"** is registered in Radarr. Not only we don't see this key info anywhere in Radarr Movie page, but also searching for the **"Original Title"** of this movie within Radarr returns no results.
