### ISSUE TITLE
[Feature Request] erase downloaded files from rtorrent after the seeding time or seeding ratio completed 

### ISSUE THREAD

**Issue by CyberPoison** [Radarr/Radarr#5219]
I have seen than Sonarr have prepared their code for the rtorrent to delete files after seedling time or seeding ratio. It will be nice to have some documentation and the same feature on radarr.

https://github.com/Sonarr/Sonarr/pull/3632

Kind regards. 

By performing a seeding time we can schedule a removal after some minutes so in that way the files doesn't cost more weight in the local HDD if moving to other ssd/hdd.

[AB#804](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/804)

**Comment by austinwbest** [comment]
If /when it is added in sonarr we can pull it :)

**Comment by leaty** [comment]
Merged! :beers: :rocket:

**Comment by neo-neo1** [comment]
> Merged! 🍻 🚀

Could you please take a look at the merge conflict? Been quite some time now. Thank you in advance, it's appreciated.
