### ISSUE TITLE
Deleted movie in folder Radarr doesn't update the information

### ISSUE THREAD

**Issue by Firemad03** [Radarr/Radarr#522]
Hi,

If I delete a movie manually in the folder and I try to refresh / rescan it Radarr still think it exist.

I tried to manually delete it in Radarr and it doesn't work. Example:

![image](https://cloud.githubusercontent.com/assets/24792889/22408825/d5903192-e64d-11e6-80f2-ecf8adb1844f.png)

The file doesn't exist anymore. I tried it with the nighly too ;)

If i press the X it's working but if I refresh the page it comeback.

Note: I deleted the movies folder too same problem

**Comment by Firemad03** [comment]
I got this error in Radarr: Series' root folder (/mnt/Movies-EN) is empty. 

I expected that he deleted it because everything is empty ;) so it doesn't exist.

**Comment by Firemad03** [comment]
I did a test and I created an empty folder. I created the 300 - 2006 and if I refresh/scan again Radarr deleted the file and now the Movie updated the status to missing.

![image](https://cloud.githubusercontent.com/assets/24792889/22408897/f6439900-e64e-11e6-84d2-194579bf00ed.png)

**Comment by Firemad03** [comment]
Conclusion if the movie folder doesn't exist Radarr don't know what to do with that.

**Comment by Firemad03** [comment]
I found a temporary solution: If you click on Organize movies it will create an empty folder. After that you can click on the X button to remove it.

If someone have this issues.

**Comment by scope999** [comment]
Hi I am having this problem too. Would it be possible for it to be labelled missing from disk like Sonarr? Then they could be filtered in the movie editor and deleted? Or even just deleted if there is no file?

**Comment by onedr0p** [comment]
You can choose unmonitor missing movies in settings. When a movie is deleted outside of year the movie gets set to unmonitored. Now for the issue here.. if you delete from within radarr and the update the movie via refresh movie should be gone.
