### ISSUE TITLE
Radarr V3: [Feature Request] - Allow edit of Custom Formats on existing files

### ISSUE THREAD

**Issue by kenvalleydc** [Radarr/Radarr#5220]
Currently in v2, after a file has been downloaded, I use an external process (Tdarr) to convert files to HEVC. To prevent Radarr from re-downloading a different x265 video, I add the "x265" custom format to keep the file updated with the change. Originally commented in #4633 (closed in #5183), but that change didn't include editing of Custom Formats on an existing file.

**Comment by ta264** [comment]
Not going to happen. Custom formats are now dynamically calculated and not saved against a file.

Is there a case not covered by #5183?

**Comment by kenvalleydc** [comment]
Just want to confirm that if a file is externally converted to HEVC, the Custom Format tag will be applied.  If it's done automatically, that's great, but I don't wish to have Radarr searching for a file that's already been converted.  I've been tagging manually in v2.

**Comment by ta264** [comment]
You'd have to make sure the file name was changed or something so that your x265 format conditions are met. You can see if the format is applied by seeing if it shows in the files page.

**Comment by bakerboy448** [comment]
Presumably resolved by https://github.com/Radarr/Radarr/commit/c538424229eadaed0ec8ce8eace95bd516676841 - which now rescans files if the size changes
