### ISSUE TITLE
Adding base URL path leads to 404s on movie posters

### ISSUE THREAD

**Issue by atrv7** [Radarr/Radarr#5224]
**Describe the bug**
When I add a base URL path like /radarr none of the images of the movie posters show up and are giving 404 errors. 

**To Reproduce**
1. Add URL base path "/radarr"
2. View your movies and none of the images are appearing

**Expected behavior**
Movie posters should be visible even with a base URL path

**Platform Information (please complete the following information):**
 - OS: Unraid
 - Mono Version: 5.20.1.34
 - Radarr Version 0.2.0.1504

**Debug Logs**
  | StaticResourceModule | Couldn't find handler for /radarr/Content/Images/poster-dark.png | 5:25pm
  | StaticResourceModule | Couldn't find handler for /radarr/MediaCover/4/poster-500.jpg | 5:25pm
  | StaticResourceModule | Couldn't find handler for /radarr/MediaCover/3/poster-500.jpg | 5:25pm
  | StaticResourceModule | Couldn't find handler for /radarr/MediaCover/21/poster-500.jpg | 5:25pm
  | StaticResourceModule | Couldn't find handler for /radarr/MediaCover/7/poster-500.jpg | 5:25pm
  | StaticResourceModule | Couldn't find handler for /radarr/MediaCover/25/poster-500.jpg | 5:25pm
  | StaticResourceModule | Couldn't find handler for /radarr/MediaCover/20/poster-500.jpg | 5:25pm
  | StaticResourceModule | Couldn't find handler for /radarr/MediaCover/8/poster-500.jpg | 5:25pm
  | StaticResourceModule | Couldn't find handler for /radarr/MediaCover/16/poster-500.jpg | 5:25pm
  | StaticResourceModule | Couldn't find handler for /radarr/MediaCover/1/poster-500.jpg | 5:25pm
  | StaticResourceModule | Couldn't find handler for /radarr/MediaCover/11/poster-500.jpg | 5:25pm
  | StaticResourceModule | Couldn't find handler for /radarr/MediaCover/12/poster-500.jpg | 5:25pm
  | StaticResourceModule | Couldn't find handler for /radarr/MediaCover/27/poster-500.jpg | 5:25pm
  | StaticResourceModule | Couldn't find handler for /radarr/MediaCover/22/poster-500.jpg | 5:25pm
  | StaticResourceModule | Couldn't find handler for /radarr/MediaCover/26/poster-500.jpg | 5:25pm
  | StaticResourceModule | Couldn't find handler for /radarr/MediaCover/6/poster-500.jpg | 5:25pm
  | StaticResourceModule | Couldn't find handler for /radarr/MediaCover/5/poster-500.jpg | 5:25pm
  | StaticResourceModule | Couldn't find handler for /radarr/MediaCover/18/poster-500.jpg | 5:25pm
  | StaticResourceModule | Couldn't find handler for /radarr/MediaCover/24/poster-500.jpg | 5:25pm
  | StaticResourceModule | Couldn't find handler for /radarr/MediaCover/14/poster-500.jpg | 5:25pm
  | StaticResourceModule | Couldn't find handler for /radarr/MediaCover/9/poster-500.jpg | 5:25pm
  | StaticResourceModule | Couldn't find handler for /radarr/MediaCover/17/poster-500.jpg | 5:25pm
  | StaticResourceModule | Couldn't find handler for /radarr/MediaCover/23/poster-500.jpg | 5:25pm
  | StaticResourceModule | Couldn't find handler for /radarr/MediaCover/13/poster-500.jpg | 5:25pm
  | StaticResourceModule | Couldn't find handler for /radarr/MediaCover/2/poster-500.jpg | 5:25pm
  | StaticResourceModule | Couldn't find handler for /radarr/MediaCover/15/poster-500.jpg | 5:25pm
  | StaticResourceModule | Couldn't find handler for /radarr/MediaCover/10/poster-500.jpg | 5:25pm

**Comment by Qstick** [comment]
I think this is likely a setup issue, but regardless we aren't making any more changes on v0.2... v3 is the future.

Feel free to join us on discord to get some help though
