### ISSUE TITLE
Enhanced Collection support

### ISSUE THREAD

**Issue by John-Gee** [Radarr/Radarr#5225]
**Is your feature request related to a problem? Please describe.**
The current support for Collections is a great step forward, but it seems still too rigid. Here are a few thing I would like to be able to do:

- Make optional the "Collection" word from the folder name got from the "{Movie Collection}" macro, that way I can get a cleaner folder structure (ie "{Movie Collection}/{Movie Title} ({Release Year})" could mean something like "Batman (DC Universe Animated)/Batman & Mr. Freeze SubZero (1998)" instead of "Batman (DC Universe Animated) Collection/Batman & Mr. Freeze SubZero (1998)". To me the absence of year in the folder name has always been enough to know that it's a collection, no need for extra letters. I'm guessing a new macro would be required for this.

- Being able to remove a movie from a collection. Since I'm going to be using the above Movie Folder Format, it'll always create a collection folder when possible, but I don't necessarily want that. Sometimes I don't like the collection, or if I only have one movie I don't see the point of creating an extra folder.

- Being able to edit the collection. I'm usually fine with having all related movies in 1 collection, I don't need multiples (for instance all Batman movies together, whether from the 80s, or later) though that may break the functionality of creating a list from a collection.

**Describe the solution you'd like**
Being able to change the items mentioned above in the global movie editor and in the one specific to the movie.

**Describe alternatives you've considered**
None so far, but I'd be happy to discuss it.

**Additional context**
None

Thank you!

[AB#805](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/805)

**Comment by ta264** [comment]
Collections are metadata coming from tmdb, I don't think there are any plans/desire to make that editable.

**Comment by John-Gee** [comment]
Not being able to edit or merge is understandable I guess.
How about to opt out or change the macro? That should be pretty separated.

Thanks!

**Comment by bakerboy448** [comment]
@Qstick  how much further are we going with collections; seems the collection changes knocked out most of this?

**Comment by Qstick** [comment]
Yea we likely won't go further in terms of this request. No plans to allow manually changing the movies in a collection.

**Comment by bakerboy448** [comment]
https://github.com/Radarr/Radarr/commit/f80272a65987b635b07448e6b959df0ad8c105d2
