### ISSUE TITLE
make the "were removed from TMDb" list click able links to the movie entry in radarr

### ISSUE THREAD

**Issue by Fredrik81** [Radarr/Radarr#5228]
**Is your feature request related to a problem? Please describe.**
Not a problem

**Describe the solution you'd like**
After upgrade, I got a BIG list of "were removed from TMDb" and when I try to hunt down the movie multiple results show up.
Cleaning this is a very annoying and time-consuming thing to do.
I would like the entries in the "were removed from TMDb" under System -> Status to be clickable as it would greatly speed up the cleanup process if the click would get you directly to the movie entry in radarr and the user can take the decision on what to do with it there.

**Describe alternatives you've considered**
Keep as is with the irritation of finding the movies one by one and cleaning up or make a full cleanup interface with automation.

**Comment by Qstick** [comment]
All you have to do is filter index by "deleted" status and you can bulk delete them all at once with movie editor... Takes about 3 seconds

**Comment by Fredrik81** [comment]
Can this be added to help text? It can be useful for others.
https://github.com/Radarr/Radarr/wiki/Health-checks#movie-was-removed-from-tmdb

**Comment by Qstick** [comment]
Sure, good idea, that wiki is public editable, so feel free to word something up.
