### ISSUE TITLE
Improve manual search

### ISSUE THREAD

**Issue by hadim** [Radarr/Radarr#5229]
I am using version 3.0.0.3790 provided by linuxserver as a docker image.

Manually searching for a certain movie can be slow. Manipulating the search results can also be slow and filtering does not always work as excepted. See below for details:

- would that be possible to return the search results as they come? so we don't have to wait for all results to be available before displaying them. UX would be smoother.
- sorting a certain column can be very slow and sometimes freeze the whole page for 20-30s.
- sorting by `peers` does not work
- filtering by peers does not work: could that be because the peers column actually contains two numeric values? could split this column into two columns?
- adding a search box to the search results would be nice too.

Here is an example of a table JS lib that could make the overall search experience smoother: https://datatables.net/

FYI: I am using a single indexer backed by Jackett that contains about 40 indexers.

**Comment by ta264** [comment]
Don't use the jackett all endpoint, you should add each indexer to Radarr individually

**Comment by hadim** [comment]
I haven't done that on purpose because I also use sonarr and I have 40 indexers, I don't' want to spend my time updating individually all the indexers when I add/delete ones.

**Comment by ta264** [comment]
If you want slow / incomplete results then carry on :) Even the jackett Devs advise against it.

**Comment by hadim** [comment]
that's fair @ta264, I guess I'll think about it at some point even if it's painful to maintain...

Are the other comments about displaying search results/filtering/sorting valid in your opinion?

**Comment by ta264** [comment]
I don't think we will return results as they come, since that would make the ordering clunky. And wouldn't help you with your `/all` either, since that doesn't return til jackett has all the results.

Which columns are slow to sort? In what way does filtering by peers not work?

I can't believe you have 40 trackers actually worth adding to Radarr, I suspect a lot of your issues would be fixed by only adding a handful of actually good indexers :D

**Comment by hadim** [comment]
Well, filtering by peers does not work as said above as well as sorting by peers.

**Comment by ta264** [comment]
I'm asking what filtering by peers currently does and what you expect it to do.

I'm also asking which columns are slow to sort? Without specifics we can't fix :)

**Comment by hadim** [comment]
I tried to filter with `peers > 5` and nothing is shown (all results are filtered I guess).

When sorting by clicking on the `peers` columns, nothing happens, the page just hangs forever.

**Comment by hadim** [comment]
Also, the fact the results are not paginated makes it very slow to scroll down a search results page (when it's not frozen).

**Comment by ta264** [comment]
How many results do you have? Are they all relevant? Or are many for the wrong movie and hence your request for a text search?

**Comment by hadim** [comment]
Yes, they're all relevant, some are fake of course but the goal of doing a manual search is for me to do the selection manually. I only do it for a few movies since 95% of the time automated searches do things correctly. I cant see the number of movies returned by the search but doing the estimation manually I would something like 100-200 results. Not something I would except any UI to struggle with.

**Comment by hadim** [comment]
Also being able to filter by peers would make this list smaller xD

Are the results paginated on the backend side?

**Comment by ta264** [comment]
The rendering issues could be fixed by only rendering what's on screen. We won't be paginating it - it's clunky and unneccessary.

**Comment by ta264** [comment]
We'll fix the peer filter too, verified broken.

**Comment by hadim** [comment]
Which numeric values are going to be used for both filltering and sorting the peers column? Would not that make sense to make it two columns?

**Comment by ta264** [comment]
It'll just work on the seeds value. Who cares about leechers?

**Comment by Qstick** [comment]
@hadim we already have a separate filter property for just `seeders`, I've fixed the peers column to filter by the total swarm. 

![image](https://user-images.githubusercontent.com/376117/96392206-63f31980-1189-11eb-932a-65e5d8e63cc1.png)

**Comment by bakerboy448** [comment]
@ta264  @Qstick still more work to do here, or can we close?

**Comment by bakerboy448** [comment]
Closing per Q; no additional work needed on this
