### ISSUE TITLE
Remove Wombles as an indexer

### ISSUE THREAD

**Issue by Firemad03** [Radarr/Radarr#523]
Hi,

Wombles is dead now:

https://www.reddit.com/r/usenet/comments/5l6soy/farewell_wombles_nzb_index/

http://newshost.co.za/

![image](https://cloud.githubusercontent.com/assets/24792889/22408935/a86373b2-e64f-11e6-8b1c-6b9095d16403.png)

I suggest to remove it ;)

Thanks

**Comment by onedr0p** [comment]
I will remove it in the next update.

**Comment by mattman86** [comment]
KickAss should be removed as well

**Comment by thezoggy** [comment]
and xem
