### ISSUE TITLE
[Feature Request] Add File info Columns to Films - Table view

### ISSUE THREAD

**Issue by danimart1991** [Radarr/Radarr#5243]
**Is your feature request related to a problem? Please describe.**
When have a lot of films, check if a film has all the parameters I like is tedious. You need to enter each film page, and then Files section to check this info.

![image](https://user-images.githubusercontent.com/5982912/96598498-39bb6c00-12ef-11eb-8098-c431af626055.png)

![image](https://user-images.githubusercontent.com/5982912/96598540-4213a700-12ef-11eb-903b-e0319d7b80f0.png)

**Describe the solution you'd like**
A solution could be to add these related columns to the Films - Table view. Then I could see all the films and maybe filter the ones that doesn't meet the requirements I look for.

**Describe alternatives you've considered**
Another option could be to have an icon "cutoff is met", but this required to include a lot of custom formats.

**Comment by bakerboy448** [comment]
to clarify; this would be to add the ability to filter by custom formats / if custom format cutoff is met

what needs to be kept in mind when implementing this is the future/eventual support for multiple files for a given movie

**Comment by danimart1991** [comment]
The Feature Request is for include the columns with that info. Maybe the filters could  be added too or added later in another issue.

And... yes, I think this must be kept in mind, the code related to this is exact the same that is used now to show the "Bluray-1080p" in the column Status but getting other properties.

I could implement this Issue if you agree with it.

**Comment by bakerboy448** [comment]
*point of clarification "table view" -> "movie index"*

@Qstick and @ta264 should probably give their thoughts.

As @austinwbest said "if so, i would say it will lead to issues.. one of which is 1:many movies would kill that right back off"

**Comment by danimart1991** [comment]
Yes. Sorry. I don't know how to name this Grid.

![image](https://user-images.githubusercontent.com/5982912/96625927-1a343b80-130f-11eb-9739-ca4bd935e4ac.png)

**Comment by austinwbest** [comment]
There is an outstanding feature request to allow multiple versions of the same movie that will be added. When this happens things like file properties wont be usable because it is no longer 1 movie : 1 file but 1 movie : n files so the property isn't usable for 1 file out of n

Hope that makes sense! :)
