### ISSUE TITLE
Unable to import files downloaded with Qbit - Radarr V3

### ISSUE THREAD

**Issue by crogers2287** [Radarr/Radarr#5244]
This is a problem that seems to have started with one of the recent nightly updates. Radarr will not import files downloaded with Qbittorrent. It is looking for the folder and file paths to have .torrent on them. Radarr when trying to import is appending .torrent to all the folders that it looks for even though the file and folder names are correct. 

I'm using qbit 4.3, radarr 3.0.0.3966 (linuxserver/radarr:nightly)

Folder structure qbit creates from torrents that are sent to it by radarr:

https://i.imgur.com/IvGl8TQ.png 

Debug log file:

https://bit.ly/3mhAIMz

**Comment by ta264** [comment]
dupe
