### ISSUE TITLE
Custom Format score for MovieFile

### ISSUE THREAD

**Issue by rg9400** [Radarr/Radarr#5245]
**Is your feature request related to a problem? Please describe.**
Right now, you can only see Custom Format scores during the Interactive Search. Without seeing the score for an existing file, you would not easily know if the score is above or below the cutoff or compare it against other releases. It also makes it harder to verify that the scoring system you are using is working as intended. 

**Describe the solution you'd like**
Display the score similar to Interactive Search on the MovieFile page

Interactive Search
![image](https://user-images.githubusercontent.com/39887349/96631574-1affaa00-12dc-11eb-9e07-103e40712179.png)

Existing MovieFile page
![image](https://user-images.githubusercontent.com/39887349/96631629-2d79e380-12dc-11eb-9eb5-08afb099cc0d.png)

**Describe alternatives you've considered**
While a user could reverse engineer the score based on the individual scores of each CF, this can be cumbersome and get complicated as you can have both positive and negative scores assigned to a CF, meaning combos of CFs can lead to surprising scores.

[AB#808](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/808)

**Comment by rg9400** [comment]
Probably could be added to history as well

![image](https://user-images.githubusercontent.com/39887349/96633265-80ed3100-12de-11eb-9690-8af15c1c00b1.png)

**Comment by bakerboy448** [comment]
https://github.com/Radarr/Radarr/commit/431bc14e76b90853208590f7e95742f169f3b87a
