### ISSUE TITLE
Api Paging and filtering

### ISSUE THREAD

**Issue by shareonline** [Radarr/Radarr#5246]
When getting movies from the V3 Api movie endpoint, we have to get everything. It would be nice to have paging and filtering implemented as a library of 10K movies does take a while to get..

The old Api had paging, but i get that Sonarr V3 doesn't have it either. But with sonarr you often don't have more than maybe a thousand series (if that many), so in real life it doesn't become a problem. There are movie libraries pretty large out there from what i can tell.

**Comment by ta264** [comment]
I don't think we have any appetite to do this.

I recently sped this up significantly so you can fetch 20k movies in ~4 seconds, so I don't see this as an issue personally.  If you find yourself repeatedly calling this endpoint you should refactor.
