### ISSUE TITLE
Add source list to main table view

### ISSUE THREAD

**Issue by syco** [Radarr/Radarr#5249]
Hi,

I'd like to see, in the main movie list, an option to see the list a movie was added from.
Would also be good to have the ability to filter by source list.
So I could check who (as in who's imdb watchlist) added a movie to the queue.

thanks

**Comment by ta264** [comment]
Set a tag for the watchlist, so it's added with a tag

**Comment by syco** [comment]
Thanks, I'll use that, but tags can't be filtered and can't be sorted, any way to add this?

**Comment by Qstick** [comment]
They can be used for filter in v3
