### ISSUE TITLE
Build: 0.2.0.262 - Search all missing doesn't work. 

### ISSUE THREAD

**Issue by Firemad03** [Radarr/Radarr#525]
Hi,

On build 0.2.0.262 the search all missing doesn't work. The search selected work if I select everything.

After I click on it nothing is happening ;)

Thanks

**Comment by scuppasteve** [comment]
I can verify this situation. Same happens to me.

**Comment by Firemad03** [comment]
I confirmed that on build 0.2.0.267 the problem is there too.

**Comment by Brianwuz** [comment]
I confirmed that on build 0.2.0.269 the problem is there too.

**Comment by fedoranimus** [comment]
Fixed by #710
