### ISSUE TITLE
Review your remote path mappings and container volume settings

### ISSUE THREAD

**Issue by casperse** [Radarr/Radarr#5251]
**Describe the bug**
I have always run my Radarr locally and my download client externally
But for a very long time I keep getting the error:

**You are using docker; download client Deluge places downloads in /home/server/downloads/#DOWNLOADTEMP but this directory does not appear to exist inside the container. Review your remote path mappings and container volume settings.**

But this shouldn't be in the docker, its a temp download folder remotely that moves the files and synch them to the server

**To Reproduce**
Upgrade Radarr

**Expected behavior**
No error message everything works perfectly

**Platform Information (please complete the following information):**
Version 3.0.0.3966
Package Version 3.0.0.3966-ls26 by linuxserver.io
.NET Core Yes
Docker Yes
DB Migration 186
AppData directory /config
Startup directory /app/radarr/bin
Mode Console

**Debug Logs**
N/A

**Comment by austinwbest** [comment]
So you have completed download handling disabled in radarr then?

**Comment by casperse** [comment]
No - I have it enabled so the the mapping (below on the same conf page) between the remote download client and the local Radarr
(Everything works perfectly) - Just keep getting the error...

**Comment by austinwbest** [comment]
That's fine, good to know..

So @ta264 i guess it shouldn't check at all if handle downloads is disabled & it should also look at the local if remote paths is used?

**Comment by rubbo898** [comment]
Same error for me too!

_You are using docker; download client qBittorent places downloads in /downloads/torrents/ but this directory does not appear to exist inside the container. Review your remote path mappings and container volume settings._


I've just switched from stable to nightly, everything seems working fine but this error notice. 
NB: remote path mappings it's working fine, I need few more time to check the behaviour but right now the import from download client is working.

I have the following configuration:

- Completed Download Handling --> ENABLED
- Remote Path --> /downloads/radarr/
- Local Path --> /media/downloads/radarr/

In qBittorent the "Default Save Path" is /downloads/torrents/ but with catagories management the Radarr path is /downloads/radarr/. 

Could it be a kind bug in Radarr checks?

**Comment by austinwbest** [comment]
It is an issue that needs looked at, yes.
