### ISSUE TITLE
Unable to add movies after update

### ISSUE THREAD

**Issue by almulder** [Radarr/Radarr#5257]
**Describe the bug**
Sfter I have updated tonight, I go to add new, find the movie click "Add Movie" and it spins and then just goes back to the "Add Movie" it never gets added into Radarr.

**To Reproduce**
1. Go to 'Add New'
2. Search for a movies to add
3. Click on 'the movie and then click on "Add Movie"'
4. Does not Add.

**Expected behavior**
Should add and then go back to search screen and show a checkmark, and should be able to find it in my movie list, but its not there.

**Screenshots**

**Platform Information (please complete the following information):**
 - Unraid 6.8.3
 - Browser and Version - Chrome 86.0.4240.111
 - Radarr Version - 3.0.0.3966
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/5434118/radarr.debug.txt)

**Debug Logs**
Turn on debug logs under Settings -> General and wait for the bug to occur again. **Upload the full log file here (or another site and link it). Issues will be closed, if they do not include this!**

**Comment by almulder** [comment]
Just updated to the new nighly build and issue is still there

**Comment by bakerboy448** [comment]
Support Requests -> [Reddit](https://www.reddit.com/r/radarr/) or [Discord](https://discord.gg/GS7jgXv)

**Comment by mhouston100** [comment]
Hi team,

I'm experiencing the same thing, receiving

```
2021-1-14 12:02:46.2|Trace|HttpClient|Req: [GET] https://radarrapi.servarr.com/v1/movie/226979
2021-1-14 12:02:46.2|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2021-1-14 12:02:46.3|Trace|HttpClient|Res: [GET] https://radarrapi.servarr.com/v1/movie/226979: 200.OK (102 ms)
2021-1-14 12:02:46.3|Trace|ConfigService|Using default config value for 'recyclebin' defaultValue:''
2021-1-14 12:02:46.6|Info|AddMovieService|Adding Movie [Test (2013)][tt2407380, 226979] Path: [/movies/Test (2013)]
2021-1-14 12:02:46.6|Trace|RadarrErrorPipeline|Handling Exception
2021-1-14 12:02:46.6|Trace|Http|Res: 256 [POST] /api/v3/movie: 409.Conflict (472 ms)
2021-1-14 12:02:46.6|Debug|Api|[POST] /api/v3/movie: 409.Conflict (472 ms)
```
If I create the folder by hand and then trry and import, I see the same log entries... 409.Conflict.

After visiting the Discord the only thing I can confirm is that recreating the DB from scratch resolves the issues (with a blank DB).

This also started around the same time as OP.

**Comment by mhouston100** [comment]
I've attempted a bunch of different V3 versions but no avail. The current version below:

Version 3.0.1.4259
Package Version 3.0.1.4259-ls89 by linuxserver.io
.NET Core Yes (3.1.10)
Docker Yes
DB Migration 188
AppData directory /config
Startup directory /app/radarr/bin
Mode Console

**Comment by bakerboy448** [comment]
Support Requests -> [Reddit](https://www.reddit.com/r/radarr/) or [Discord](https://discord.gg/r5wJPt9)
