### ISSUE TITLE
failed map to download, expected year (year found on imdb) but found (year in the torrent's title)

### ISSUE THREAD

**Issue by jacquesdupontd** [Radarr/Radarr#5264]
**Describe the bug**
Most movie are to be found in torrent a year after there release in theatres. So when you search for a movie that was just released in torrent with the year 2020, then it will "failed map to download, expected year (year found on tmdb) but found (year in the torrent's title)" because the year attributed to its release on TMDB is 2019. It's happening more on French releases. I just updated to v3 to see if i could find a solution around this but i didn't.

**To Reproduce**
1. Search for say "Casle in the ground" in 1080p (make a French profile and add a French torrent website like "oxtorrent" that you can find on Jackett).
2. Add it and search for it. It won't start the download, then manual search and you'll see it found but with the year 2020 instead of the year 2019 which is associated to its release on TMDB.

**Expected behavior**
I'd like to be able to have a condition so that it would download it anyway if the year is either -1 or +1 from the date attributed in TMDB. And if not possible I'd like to be able to completely remove that YEAR filter and that it would start the download of the movie whatever the year is.

**Screenshots**
![image](https://user-images.githubusercontent.com/13660220/97119895-a54c7180-1713-11eb-8aab-5a672ff187a4.png)

**Platform Information (please complete the following information):**
 - OS: [Ubuntu]
 - Mono Version: [6.12.0.90]
 - Radarr Version [3.0.0.3790]

**Debug Logs**
Turn on debug logs under Settings -> General and wait for the bug to occur again. **Upload the full log file here (or another site and link it). Issues will be closed, if they do not include this!**
[radarr.txt](https://github.com/Radarr/Radarr/files/5436007/radarr.txt)

**Comment by austinwbest** [comment]
Imdb is not where you should be looking. Meta is pulled from TMDb and if you fix the year there, then radarr will map it accordingly once the cache updates.

**Comment by jacquesdupontd** [comment]
Ok thanks but imdb or tmdb, the issue is the same, the service supposed to find the movie for me and download it looses all its purpose because i'm gonna have to do everything manually, ie go to tmdb, add the other year and then search the movie again in Radarr. In this case it would have been way simpler to just go on the torrent website and download the movie i want directly. So again, i want to know if it could be possible to add more years (like -1 and +1) in the Radarr rules to find a match to download ? or remove completely the year from the research. Thanks again

**Comment by Qstick** [comment]
This will be because there is no theatrical release on tmdb (just digital and premiere) and thus we just use the premiere, this could be handled a bit better on metadata server.

But we aren’t going to just arbitrarily do a plus minus 1

**Comment by jacquesdupontd** [comment]
Thank you for your answer. I think it would be nice to be able to choose what we want as match, [title] + [year] or just [title] or [title] + [year -1, year, year+1] as an option.

**Comment by Qstick** [comment]
Not planning on that either. Sorry. No plans to introduce a feature or option that will create more false matches and/or support issues. We will improve the logic to work to eliminate the issues as we see them.

**Comment by jacquesdupontd** [comment]
Ok. And thank you for the work you do, i really enjoy Radarr.

**Comment by bakerboy448** [comment]
@Qstick  close?
