### ISSUE TITLE
Subtitles in pt-BR incorrectly renamed when movie is renamed via Radarr - ".pt-BR" is lost

### ISSUE THREAD

**Issue by wsegatto** [Radarr/Radarr#5268]
**Describe the bug**
When you rename a movie via the "Preview Rename" feature and confirm, the subtitles are supposed to be renamed as well.
However, my pt-BR subtitles are not getting renamed correctly. The language portion "pt-BR" is lost. Maybe this is related to issue #1626 

**To Reproduce**
1. Have a movie with an EN and a pt-BR SRT subtitle.
2. Go to any Movie and click "Preview Rename"
3. Confirm the change, renaming the file
4. Check the new subtitle name, the ".pt-BR" part of the filename is missing.
5. See attached video, [Radarr Subtitle issue.zip](https://github.com/Radarr/Radarr/files/5438810/Radarr.Subtitle.issue.zip)

**Expected behavior**

**Screenshots**

**Platform Information (please complete the following information):**
- OS: Raspbian 10 arm64
- Radarr Version: 3.0.0.3974
- Mono Version: 5.18.0.240

**Debug Logs**
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/5438850/radarr.debug.txt)

**Comment by Qstick** [comment]
Dupe #5191
