### ISSUE TITLE
Possible to add these indexers?

### ISSUE THREAD

**Issue by jeeperv6** [Radarr/Radarr#527]
Hi

I've been running Radarr for the past 4 days since learning about it!  I want to say GREAT JOB! 👍 

I tried to add some of the extra indexers I've been using in Sonarr for the last while, but I can't seem to add them.  I've been trying to add them through Add Indexer/Newznab/Custom:

NewzTown
Nzb.is
NZBStars
Nzeeb

The error reply I get from Radarr is:

Unable to connect to indexer: Sequence contains no elements

Log says under this statement:

System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 322

Once again, I want to congratulate  you on a great job!

Thank you!

**Comment by onedr0p** [comment]
Duplicate, Please read my comment in #4 (comment)
