### ISSUE TITLE
Discord colour for download not obvious from other events

### ISSUE THREAD

**Issue by RobinDadswell** [Radarr/Radarr#5270]
**Is your feature request related to a problem? Please describe.**
Discord.OnDownload used to provide a green embed and now provides a yellow embed; the green was much easier to tell that something had been imported and it wasn't another grab

**Describe the solution you'd like**
Update the Discord.OnDownload method to use Success colouring

**Additional context**
Was
![image](https://user-images.githubusercontent.com/19610103/97194896-95c83980-17a2-11eb-9a57-1ad9e3f16ce6.png)

Now
![image](https://user-images.githubusercontent.com/19610103/97194710-61547d80-17a2-11eb-9c3f-e3c3a0f64513.png)

**Comment by Qstick** [comment]
Dupe #5269

**Comment by RobinDadswell** [comment]
@Qstick I have implemented the code I used in Sonarr into a pull request in Radarr #5271 - what is best practice surrounding PR's across the Sonarr/Radarr/Lidarr stack? do it in Sonarr and let it be moved across by the Servarr bot?

**Comment by Qstick** [comment]
Yea the PR is fine, but we have issues automatically created from their PRs so I just closed the extra issue. Just mention in your PR that it fixes the other auto issue. Thanks!
