### ISSUE TITLE
Conflicting quality between Release Title and File name prevents import even if quality profiles groups them

### ISSUE THREAD

**Issue by ExorcistF1** [Radarr/Radarr#5274]
If a Release Title is WEB-DL.1080p and File name WEBRip.1080p then sonarr doesn't know what it really is and blocks the import until the user intervenes.

https://imgur.com/K1SSGOs

**Platform Information (please complete the following information):**
 -Windows
qbittorent 4.2.5
3.0.0.3974 Oct 25 2020 nightly

**Debug Logs**
https://pastebin.com/89xAnCTS

**Comment by austinwbest** [comment]
This is not a bug, it is by design and won't change.

It happens when garbage trackers like rarbg rename things for no reason and do it incorrectly 99 percent of the time.

**Comment by ExorcistF1** [comment]
sonarr trying to change this. and bigest % of user using rarbg. its also happend to me 5 times in a month (not so good for automatic program)

**Comment by ExorcistF1** [comment]
its fixed in sonarr https://imgur.com/0SUYsUw

**Comment by austinwbest** [comment]
markus added a change to ignore it, so i will pull in the same change. 

also, an automatic program is only as good as its data. rarbg is garbage so you get a garbage result. simple as that.
