### ISSUE TITLE
Movie paths are sometimes not properly "linked" to the correct directory so import fails

### ISSUE THREAD

**Issue by Jadiction** [Radarr/Radarr#5275]
**Describe the bug**
I add & search for a movie and when downloaded, the path sometimes isn't "linked". Unsure if this is a bug or something I'm missing (maybe a bad setting).

**To Reproduce**
1. Add/search movie to download
2. It's found and sends to the torrent client (in my case - qbittorrent)
3. It downloads to directory `Paranormal Activity (2015) [1080p]`
4. Radarr thinks it's `paranormal-activity-the-ghost-dimension-2015` so it fails to import.
5. Receives error every time it tries to import automatically:  `Import failed, path does not exist or is not accessible by Radarr: /media/appdata/binhex-qbittorrentvpn/qBittorrent/downloads/paranormal-activity-the-ghost-dimension-2015`

Another example:
Movie: Hellboy the golden army
Downloads as directory: `Hellboy The Golden Army (2008) [1080p]`
Error: Import failed, path does not exist or is not accessible by Radarr:` Import failed, path does not exist or is not accessible by Radarr: /media/appdata/binhex-qbittorrentvpn/qBittorrent/downloads/hellboy-ii-the-golden-army-2008`
I noticed in the client it shows a different title than normal. (The first movie is how it usually shows)
![image](https://user-images.githubusercontent.com/8557785/97445401-36ca0800-18fb-11eb-9710-cfc4c6d0470d.png)

**Platform Information:**
 - OS: Linux (Unraid Docker)
 - Mono Version: 6.10.0
 - Browser and Version: Chrome
 - Radarr Version 0.2.0.1504

More info:

This doesn't always seem to be the case, so it may be a specific indexer (YTS)? All paths are properly set. This wasn't an issue for months and it suddenly became one recently. 

Relevant settings:
![image](https://user-images.githubusercontent.com/8557785/97445704-8f010a00-18fb-11eb-8680-28f13a72f2c2.png)

**Comment by ta264** [comment]
Dupe #5032 

Radarr 0.2 doesn't with qbittorrent 4.3. It still needs to be fixed in Radarr V3 too.

**Comment by Jadiction** [comment]
Ah, I see. Makes sense why it happened recently and not before, then.
Thanks & hope for this to be fixed soon. Appreciate the work you guys put into this.
