### ISSUE TITLE
Upgraded item colour change request

### ISSUE THREAD

**Issue by Conroy1988** [Radarr/Radarr#5276]
**Describe the problem**
Upgraded items in discord webhooks colour, it blends in too much with discord (Grey)

**Describe any solutions you think might work**
Changing the colour to something brighter and more out there, such as the following purple #9900FF

**Additional context**
I've also logged this for Sonarr too, hopefully get a universal sonarr/radarr colour coordination.

**Comment by austinwbest** [comment]
Or just add a color picker @Qstick lol :)

Issue with this, what works for one doesn't for another. It will be a never ending request to change colors, placement, etc

**Comment by Conroy1988** [comment]
> Or just add a color picker @Qstick lol :)
> 
> Issue with this, what works for one doesn't for another. It will be a never ending request to change colors, placement, etc

Either or, developing an entire like new segment to pick a colour just seems like more work than it's worth. But having a default for everyone perhaps would be a good quick option. A colour picker could be something later down the timeline?

**Comment by austinwbest** [comment]
It was sarcasm for Q :) The point is valid though, change it to purple and someone will want blue. Change it to blue and someone will want orange. What about people with color issues and can't tell what it is.

I'm sure Q will decide how much changing will be done and reply though.

**Comment by Qstick** [comment]
3e22658e277d4fb99618fae159740827fa2ade99
