### ISSUE TITLE
Radarr doesn't update 

### ISSUE THREAD

**Issue by KierenConnell** [Radarr/Radarr#5278]
**Describe the bug**
Radarr tells me there's an update, go and hit the update button, it runs through the motions, restarts the service, and I'm still on the same version as before.
This happens running as a service and also running via the tray.

**To Reproduce**
1. Click 'Install Update'
2. Wait for steps to run
3. Reload webpage
4. See that you're still on the same version as before

**Expected behavior**
Radarr to update

**Screenshots**

**Platform Information (please complete the following information):**
 - OS: Windows Server 2019
 - Radarr Version: 3.0.0.3879

**Debug Logs**
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/5465154/radarr.debug.txt)

**Comment by bakerboy448** [comment]
Support Requests -> [Reddit](https://www.reddit.com/r/radarr/) or [Discord](https://discord.gg/GS7jgXv)
