### ISSUE TITLE
In movie editor - custom filter for filename path or filter on specific root folder

### ISSUE THREAD

**Issue by hobbis75** [Radarr/Radarr#5279]
**Is your feature request related to a problem? Please describe.**
From time to time, I need to reorganize the root folders and movies. I use the movie editor to move content from one folder to another.
However I need to do this manually using checkboxes wherever I want to move content.

**Describe the solution you'd like**
A custom filter where I can filter on path, or part of a path in order to identify specific root folders where I can perform actions (such as change root folder)

**Describe alternatives you've considered**
Custom filtering options on for example path or manual expressions.

**Additional context**
None

**Comment by bakerboy448** [comment]
This exists in v3.


Will be closed
