### ISSUE TITLE
Disable logging or limit size

### ISSUE THREAD

**Issue by balazsorban44** [Radarr/Radarr#5280]
**Is your feature request related to a problem? Please describe.**
Recently my Radarr logs were growing to something like 2.000.000 entries in the matter of days,that crashed my server as I ran out of space on the main SSD.

**Describe the solution you'd like**

Currently there is no option to limit the allowed size of the logs, or disable it entirely. It would be great to add at least one of those options. 
![Screenshot_20201031-105027.png](https://user-images.githubusercontent.com/18369201/97776259-ef47b400-1b66-11eb-875a-37c9c19b6159.png)

**Describe alternatives you've considered**

I run Radarr in a docker container and thought that setting a limit on logging there would help but it had no effect:
![Screenshot_20201031-104916.png](https://user-images.githubusercontent.com/18369201/97776243-c58e8d00-1b66-11eb-83ea-ddc5ca8f7c92.png)

**Currently I have to remember to clear the event logs and delete the log files in every few days**, or else my server crashes

**Additional context**

Using it on Ubuntu 20.04

Radarr Version:  [3.0.0.3974-ls26 by linuxserver.io ](https://hub.docker.com/r/linuxserver/radarr/tags)

Since yesterday there are 40.000 entries of the following:
```
Unable to find exact quality for BLURAY, 2160, and BRDISK. Using Unknown as fallback
```

I can also see that backups can be cleaned up automatically after a few days. Something similar for the logs would be great:
![Screenshot_20201031-105931.png](https://user-images.githubusercontent.com/18369201/97776437-36827480-1b68-11eb-83fd-8d6be8ed364d.png)

**Comment by ta264** [comment]
Logs are already limited to 5 1mb files for info and 50 1mb files for debug/trace

**Comment by balazsorban44** [comment]
@ta264 Then it's a bug, one of the files were over 20gb!

**Comment by balazsorban44** [comment]
it does, the files are growing indefinitely, that's why I have to keep deleting them manually so my system does not crash.

**Comment by ta264** [comment]
Please join the discord for support. I suspect some sort of file permissions problem.

**Comment by balazsorban44** [comment]
![Screenshot_20201101-100510.png](https://user-images.githubusercontent.com/18369201/97798806-dc49e800-1c29-11eb-979b-ea02b8d0a2a7.png)

OK, so there maybe another file limit that you mentioned, cause I am getting more than 5 files here.

**Comment by bakerboy448** [comment]
@austinwbest just checked my instance and I have through 21 Radarr.#.log files for 22 total.

Seems OP may have found something.

The 50 rotation works on debug and Trace tho.
