### ISSUE TITLE
Cant find movies via imdb:tt12345678

### ISSUE THREAD

**Issue by lukjod** [Radarr/Radarr#5281]
newest version of v3 on docker
Version
    3.0.0.3977
Package Version
    3.0.0.3977-ls26 by linuxserver.io 
.NET Core
    Yes
Docker
    Yes
DB Migration
    186
cant find some movies althoughg they exist on imdb
examples
movie title:
Raz, jeszcze raz
imdb link [https://www.imdb.com/title/tt8925032/](url) 

movie title:
Banksterzy
imdb link [https://www.imdb.com/title/tt12869176/](url)

**Comment by Silent-Remux** [comment]
If the movie does not exist on TMDb, you can't use IMDB to add it, even if the IMDB entry exists. It is required to be on TMDb.

**Comment by austinwbest** [comment]
Please use discord for support topics. The movie needs to be on TMDb to be found by radarr.
