### ISSUE TITLE
Radarr unmapped movie replaces movie with similar name.

### ISSUE THREAD

**Issue by rycore** [Radarr/Radarr#5282]
**Describe the bug**
When forcing a download of a file that isn't mapped, it will replace an existing movie with the same name but different year than the one you do the manual search/download with.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add/Searched for a movie such as Casino Royal 2006 and Casino Royal 1967
- in my case, the 2006 version downloaded automatically but the 1967 didn't.

2. Manually search for the 1967 version.
- Discovered that the uploader labelled the movie as 1966, causing Radarr to not map it.

3. Forced this file to download.

4. Radarr downloads the movie but then replaces the 2006 version instead.

**Expected behaviour**
Radarr to download and import as the 1967 version.

**Screenshots**
![image](https://user-images.githubusercontent.com/49836558/97806637-92c2c280-1c54-11eb-9652-e1953db63c71.png)

**Platform Information (please complete the following information):**
 - OS: Windows Server 2012 r2
 - Radarr Version: 3.0.0.3978

Just to note, I know this is due to the file not being mapped, but maybe when a user forces these types of files to download, that they could be linked in some way to where we downloaded them from? maybe by using the internal movie ID from Radarr? so if we downloaded the file from a movie with ID 12208, the part of the code that tracks/imports would remember this and use that in these types of situations, if that makes sense.

**Comment by bakerboy448** [comment]
Going to need the Trace logs to see what the parser is doing.

**Comment by rycore** [comment]
Sorry about that, here's the debug and trace logs.

[radarr.trace.txt](https://github.com/Radarr/Radarr/files/5471218/radarr.trace.txt)
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/5471216/radarr.debug.txt)

**Comment by JBou** [comment]
It's very similar to #4643. Depending on the solution, maybe they can be resolved together

**Comment by bakerboy448** [comment]
> Sorry about that, here's the debug and trace logs.
> 
> 
> 
> [radarr.trace.txt](https://github.com/Radarr/Radarr/files/5471218/radarr.trace.txt)
> 
> [radarr.debug.txt](https://github.com/Radarr/Radarr/files/5471216/radarr.debug.txt)
> 
> 


No need for both; Trace includes Debug.

But I'm not seeing any attempted imports or any naming parsing in those logs.  We need the logs of the issue being reproduced.

**Comment by rycore** [comment]
> But I'm not seeing any attempted imports or any naming parsing in those logs. We need the logs of the issue being reproduced.

That is the log, I enabled trace logging,

**Comment by rycore** [comment]
I hit the wrong button, never ment to close. on my mobile.

That is the trace log, I removed the 1967 version, enabled tracing and then redownloaded the file, i waited for it to complete, disabled trace logging and then uploaded it to here.

**Comment by bakerboy448** [comment]
"casino" does not exist within that trace file at all... so we're missing something

fine the trace log that has the importer getting stuck or mapping the wrong movie

**Comment by rycore** [comment]
> 
> 
> "casino" does not exist within that trace file at all... so we're missing something
> 
> fine the trace log that has the importer getting stuck or mapping the wrong movie

When I replicated it to create the log, I deleted all the other logs first.

1. Deleted all logs
2. Removed the 1967 version.
3. Enabled Tracing
4. Manually downloaded the 1967 version.
5. Once completed, Stoped the trace logs.

I'll replicate it again and check the log. give me a min or two.

**Comment by rycore** [comment]
I decided to chek the trace log I uploaded while I waited and it does show Casino, along with parsing, https://imgur.com/a/zt3kBVJ

But I have another trace log.

[radarr.trace.txt](https://github.com/Radarr/Radarr/files/5477859/radarr.trace.txt)

**Comment by bakerboy448** [comment]
well that aint' right  @Qstick thoughts?
[relevant part of log](https://pastebin.com/bwLKqgGN)

**Comment by Qstick** [comment]
Yea its an issue in the parser where if there is no year match it just takes the first matching title candidate. We need to be more conservative and just throw out for manual import if there are multiple possible matches.

**Comment by rycore** [comment]
> We need to be more conservative and just throw out for manual import if there are multiple possible matches.

Just a thought, radarr seems to know it was downloaded for that specific movie, but then gets lost during the parsing due to the year, so what about attaching the movie ID during the download process and defaulting to that movie? 

That way you could have two extra fail safes, if the unmapped movie has a movie ID, then automatically import it to that movie, but if it doesn't then manual import.

**Comment by Qstick** [comment]
0e5f43e139aea694a9d32248d252b0e0fbfde1af
