### ISSUE TITLE
Feature Request- Custom qualities

### ISSUE THREAD

**Issue by astlaurent** [Radarr/Radarr#529]
I might be alone but one feature that was always lacking in Couch potato that i would love to see implemented is something like custom qualities or something else that would resolve this need.

Typically when i grab a movie I prefer lower size 720P rips typically found with Yify, SRG, etc and are around 1 - 2gb or so. These are much more easily streamed than large 4 - 5 gb rips. I however will take a 4 - 5gb rip for a while until a much more compact one comes out and then i would like to replace it with the smaller one. This could be achieved by having the standard 720 bluray or webrip quality with the 4 - 5gb sizing and then allowing us to make a copy of those qualities with the 1 - 2gb sizing and then reorder the custom one to the top. Right now if i take a bigger release i need to manually replace it later.

One other method although not as slick that i saw you mentioned is allowing cutoff on prefered word, i would prefer scenes that commonly do these releases and then cutoff when found.

Like i said i might be alone but i am sure there are individuals out there that do this same type of thing. 

I am so glad you guys are taking on this project, it is much in need to replace couch potato.

**Comment by scuppasteve** [comment]
I was hoping for something like more options listed for qualities

Like
1080p BluRay - DTS-HD or TrueHD
1080p BluRay - DTS or DD5.1
1080p WEB-DL - DTS-HD or TrueHD
1080p WEB-DL - DTS or DD5.1
1080p BluRay
1080p WEB-DL
720p BluRay - DTS-HD or TrueHD
720p BluRay - DTS or DD5.1
720p BluRay
1080p hdtv

**Comment by onedr0p** [comment]
Can't you use profile tags to get what you want with the new qualities we added?

**Comment by scuppasteve** [comment]
If you are replying to me, yes i can use tags, to limit those, but i dont want it to exclude that for everything. Like i want everything to end up being TrueHD or DTS-HD and 1080p Bluray. But i am k with dvdscr or web-dl or whatever until something better is available. I just want it to always look for a better copy, not just give up on 1080p Bluray.

**Comment by galli-leo** [comment]
@scuppasteve You can just add those tags to the preferred tags list in your profile. This feature should be available on the next release today.

**Comment by astlaurent** [comment]
The tagging would not work in my instance since once any 720p movie was marked as downloaded regardless of size the cutoff would be met and it would stop searching. Perhaps even just some flexability with the sizing where you would have a min size, max size and a preferred size. Maybe do not mark as done until it finds a release close to the preferred size. This would also work in the opposite direction where if a user takes a low bit rate release because that is all that is available but they really would prefer larger releases they could tweak it to work in that direction.

**Comment by scuppasteve** [comment]
@galli-leo I updated and i implemented it the way you suggested. Looks good so far. Thanks much man.

**Comment by astlaurent** [comment]
@galli-leo this thread was hijacked. You can leave it closed because I opened the request on the feature board but I would appreciate if you considered a solution to the above need. Thanks for all the effort.

**Comment by galli-leo** [comment]
@adtlaurent We wont forget about this ;) I think we will be integrating this together with 3D
