### ISSUE TITLE
Fails to map movie grabbed before the translation has been added, after re-grabbing the same nzb already in queue

### ISSUE THREAD

**Issue by JBou** [Radarr/Radarr#5290]
**Describe the bug / To Reproduce**
I have two same releases in the queue, one gets mapped, the other one doesn't.

On 31. Oct. Radarr automatically grabbed the release `The.2nd.Im.Fadenkreuz.der.Soeldner.2020.GERMAN.720p.BluRay.x264-UNiVERSUM`, but it didn't got mapped, because on TMDB the German translation was missing.
I haven't had time to add the translation yet.
But today (2. Nov), Radarr regrabbed the exact same nzb (even if it was already in the queue, this is the first problem), but this time it mapped the correct movie, because [in the meantime, someone else added the German translation on TMDB (1. Nov)](https://www.themoviedb.org/movie/724717-the-2nd/changes).
The Problem is, Radarr won't map the movie that was already in the queue before it has been added to TMDB.

**Expected behavior**
First of all, Radarr shouldn't grab the exact same nzb again, if it is already in queue.
Second, it should correctly map the release after adding the Translation to TMDB, even if it has been grabbed before adding the translation.

**Screenshots**
![2020-11-02 18_29_15-Warteschlange - Radarr](https://user-images.githubusercontent.com/4021928/97902035-48694080-1d3d-11eb-83a9-fb9b7ef13e94.png)

**Platform Information (please complete the following information):**
OS: linux docker
Radarr Version 3.0.0.3978 by hotio

**Debug Logs**
[radarr.trace.log](https://pastebin.com/dL7NN8yG)

**Comment by bakerboy448** [comment]
>First of all, Radarr shouldn't grab the exact same nzb again, if it is already in queue.
It typically does / should not.  Would need the logs of the grab to see why it was grabbed.

>Second, it should correctly map the release after adding the Translation to TMDB, even if it has been grabbed before adding the translation.

It it should/ does.  Have you tried restarting radarr and seeing if it would reparse that first one.  I'm not even seeing your logs try to map/parse it?  We'll need more than just the snippet.

**Comment by JBou** [comment]
the snippet contains the logs when I pressed refresh on the queue. I'm sorry, I don't have the logs of the grab event anymore.

For the second problem, restarting solved the issue, the movie has been successfully imported now. [Here are the logs](https://pastebin.com/8fzgjmPi) in case you need them. Don't know why it didn't worked before restarting, though.

There is no problem for me with this, just a bit strange and wanted to report it in case you want to fix it.
