### ISSUE TITLE
Sort by size

### ISSUE THREAD

**Issue by JacquelineHyde** [Radarr/Radarr#5292]
**Is your feature request related to a problem? Please describe.**
I can sort and filter on title, status, profile, but can't see what movies are taking up my storage space.

**Describe the solution you'd like**
Add the capability to sort by size on disk.

**Describe alternatives you've considered**
I've been using WinDirStat to find them.

**Additional context**
Sonarr has this capability.

**Comment by bakerboy448** [comment]
This exists in v3 and will be closed
