### ISSUE TITLE
Not Renaming Files According To Settings

### ISSUE THREAD

**Issue by y0himba** [Radarr/Radarr#5294]
**Describe the bug**
I have Radarr set to rename files using the following:
File name: {Movie Title} ({Release Year}) [{Quality Title}]
Folder name: {Movie Title} ({Release Year})
Replace colons with a dash.

Radarr isn't doing that. I am using it in conjunction with SABNZBD (3.1.1RC1) and NZBHydra2 (3.4.3)
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/5484826/radarr.debug.txt)
, and I have all renaming in SAB disabled. When I click a movie that is downloading or hasn't downloaded yet, the path is correct, however Radarr doesn't rename to that path, so I manually need to rename each folder and refresh file information so Radarr can find it. 

When I look at the "Activity" page, there is never an "Output Path" listed in the column. "Release Title" is there though.

I have my storage folder on a separate physical drive from the install, and all other folders are default. 

If anything else is needed, please let me know. 

**To Reproduce**
Go to settings->Media Management under the "Movie Naming" section.
Set your format using the allowed tags.
Radarr doesn't rename according to those tags. 

**Expected behavior**
I would expect Radarr to name the folders and files according to my settings. 

**Screenshots**
Screenshots attached.

**Platform Information (please complete the following information):**
 - OS: Windows 10
 - Mono Version: N/A
 - Browser and Version: N/A
 - Radarr Version 3.0.0.3978

**Debug Logs**
Attached.
![output_path](https://user-images.githubusercontent.com/11462603/98055297-2938e480-1e0b-11eb-8c59-d05d5e223f0c.jpg)
![sab_settings](https://user-images.githubusercontent.com/11462603/98055298-29d17b00-1e0b-11eb-987b-d0d466f7c1a1.jpg)
![settings_radarr](https://user-images.githubusercontent.com/11462603/98055299-2a6a1180-1e0b-11eb-991e-06f9833c22d0.jpg)

[radarr.debug.txt](https://github.com/Radarr/Radarr/files/5484828/radarr.debug.txt)

**Comment by y0himba** [comment]
I have al my settings correct, so I am not in need of support. This is a bug I cannot figure out. Please reopen it?

**Comment by bakerboy448** [comment]
99.9% sure this is not a bug and you are in fact in need of support.  (Nearly) Every single instance of these issues is QBT 4.3 known bug, user error, or permissions.

we'll discuss on discord.

**Comment by y0himba** [comment]
I just want to say thank you for all the help, and your patience. That was a lot of work we went through, and I truly appreciate it.
