### ISSUE TITLE
Movie Source column (manual vs automated list) || IMDB as a Rating Source || Setting option for changing default columns & their order

### ISSUE THREAD

**Issue by bmilcs** [Radarr/Radarr#5297]
**Is your feature request related to a problem? Please describe.**
No. Three quality of life enhancements :). I would really love to be able to sort movies by IMDB rating, quickly identify how a movie was added and change the default column configuration: what columns show up and in which order. It'd be great to not have to change the visibility of columns on every Radarr visit.

**Describe the solution you'd like**
All relate to viewing your movies list:
1) An Additional Column/Filter that will show the source of movies added to your list:
     - Manual addition via webgui
     - Automated addition, including the originating list's name **Being able to narrow down a troublesome list would be fantastic :)**

 2) A setting to change the source of movie reviews. Personally, I go by IMDB as a general baseline and have little faith in traktv, etc. It would be amazing to quickly sort my movie list by low to high and delete poorly reviewed additions.

 3) Column customization. A setting to permanently set your default column views, and what order they appear in :)

**Additional context**
Thank you for your amazing contribution to the community and keep up the great work!

**Comment by Qstick** [comment]
1. Use tags

2. Covered by #2115 

3. Column customization is possible in v3, no plans to persist the settings farther than local browser cache.
