### ISSUE TITLE
Automatic search choose lower quality and custom format over better quality and custom format

### ISSUE THREAD

**Issue by max01986** [Radarr/Radarr#5298]
**Describe the bug**
My quality profile has a group for 1080p and is set to upgrade until this group quality and is also set to upgrade until a specific custom format is reached. For some reason, when radarr parse for the best release, it choose a release that has a lower custom format over a better one for a quality that is in the same groupe as the release already grabbed.

This is my profile
![2020-11-04_19h24_25](https://user-images.githubusercontent.com/38813688/98182836-b8f69580-1ed4-11eb-880b-1dbe7102ce46.png)

Here's the file that was grabbed before. It is part of the 1080P quality group and has the value 5 for the custom format.
![2020-11-04_19h26_02](https://user-images.githubusercontent.com/38813688/98182847-bc8a1c80-1ed4-11eb-9173-bcb550016c04.png)

Here's the release it choose over the one I already have...
It is part of the 1080P quality group but only has the value 2 for the custom format.
![2020-11-04_19h27_08](https://user-images.githubusercontent.com/38813688/98182849-bf850d00-1ed4-11eb-9e15-0c809e0d4066.png)

**To Reproduce**
1. Create my profile and quality groups
2. Create a few custom formats (If needed, I can export all my custom formats)
3. search for a release - Shaft as in my screenshots or other movies.

**Expected behavior**
Lower custom format for lower or equal quality should not be prefered.

**Platform Information (please complete the following information):**
 - OS: Windows 10 1809
 - Radarr Version 3.0.0.3978

**Debug Logs**

[radarr.debug.txt](https://github.com/Radarr/Radarr/files/5491214/radarr.debug.txt)

**Comment by Qstick** [comment]
Looks like you have prefer indexer flags on or something? Quality doesn't matter as you have them all grouped so that's expected

**Comment by max01986** [comment]
Indexer 1137 has a priority of 25, YGG and some others have a priority of 24.

Prioritize releases with special indexer flags isn't checked.

**Comment by austinwbest** [comment]
Rerun that search with trace enabled and post it. The repack flag appears to be the trump here.

**Comment by max01986** [comment]
[radarr.trace.txt](https://github.com/Radarr/Radarr/files/5491352/radarr.trace.txt)
Here's the trace.

**Comment by Qstick** [comment]
You have prefer propers and repacks enabled?

**Comment by max01986** [comment]
@Qstick 
@austinwbest 

Thank you soooo much!!!! That was my issue....
