### ISSUE TITLE
New/Old movies in Trakt lists aren't tagged

### ISSUE THREAD

**Issue by danimart1991** [Radarr/Radarr#5299]
**Describe the bug**
I add a Radarr tag to any Trakt List configuration window. The new movies added from these Lists doesn't have been tagged. Not even the old movies that was previously added.

**To Reproduce**
1. Go to 'Settings -> List -> Add/Modify a Trakt List'
2. Add a tag to 'Raddar Tags' field.
3. [Optional] Authenticate again + Test
4. Save the form
5. Press update all movies button or wait for a new movie to be automatically imported.

**Expected behavior**
New and Old movies that are in the Trakt Lists must have the associated tags. 

![image](https://user-images.githubusercontent.com/5982912/98298698-b10f2200-1fb6-11eb-9b6e-99a5d0a73188.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/5982912/98298517-6c838680-1fb6-11eb-8c87-947bfb4d34bc.png)

**Platform Information (please complete the following information):**
 - OS: Debian 10 + Docker
 - Package Version: nightly-6f1d5a0-640 by hotio
 - Radarr Version: 3.0.0.3987

**Comment by Qstick** [comment]
It doesn't apply retroactively to movies already added. But new ones should get it if they are auto added (not manually added from discover)

**Comment by danimart1991** [comment]
Thanks for the answer. If old movies can't get the tag. New movies only get the tags of one list if is in two or more list? (the fist list to be detected).

Anyway, I check that new movies doesn't get the tag. 😥

**Comment by Qstick** [comment]
> New movies only get the tags of one list if is in two or more list? (the fist list to be detected).
> 

Correct, but discussed a few weeks ago on discord to use all tags if associated with multiple lists

**Comment by danimart1991** [comment]
It seems to be autofixed when restart the container. But as you said. Multiple lists or old movies compatibilities could be awesome.

Thanks for the answers.
