### ISSUE TITLE
Language profile any does only match english titles

### ISSUE THREAD

**Issue by ggogel** [Radarr/Radarr#5301]
**Describe the bug**
What I want to achieve is that I have radarr looking primarily for releases that include german and english audio (a.k.a German.DL). If there is no suitable german release found it should go with an english release instead and probably upgrade later.

The issue with that are the alternative titles. If I set the language profile to any it doesn't add the german alternative title of the movie. If I set it to german the title is added but then radarr is blocking all english only releases. 

If the language any is chosen it doesn't add all international alternative titles. Though to truly match for any language it should actually add all alternative titles that can be found for this movie.

**To Reproduce**
As an example I chose the movie "Only the Brave", which is called "No Way Out - Gegen die Flammen" in german.

In this case I have set the language to any and in the manual search it shows an error because it doesn't know the title, hence it is also not mapping this release in the automatic search.
![image](https://user-images.githubusercontent.com/13143850/98347036-290d3480-2017-11eb-93bc-b778eed22c0c.png)

Now I have changed the language of the profile to German and after I run "Update movie info and scan disk" it adds the german title under titles.
![image](https://user-images.githubusercontent.com/13143850/98347507-c49ea500-2017-11eb-9db1-651a98b31bd4.png)
Now radarr is blocking the release because the language doesn't match. This could be intended but often it is hard to find some movies on the few german private trackers that exist, so I have to go with english only.
![image](https://user-images.githubusercontent.com/13143850/98347815-3b3ba280-2018-11eb-89cc-a3b75aaf79d3.png)

**Expected behavior**
When the language any is selected in a profile, all international alternative titles should be added to the movie.

**Platform Information (please complete the following information):**
 - OS: CentOS 8, Docker 19.03.13
 - Mono Version: 5.20.1.34
 - Radarr Version: 0.2.0.1504

**Comment by ta264** [comment]
0.2 is no longer under development. Languages have seen a lot of changes in v3, try it there and let us know if still an issue.

**Comment by ggogel** [comment]
Oh wow. I am using linuxserver/radarr and they have tagged 0.2 as latest. I now upgraded to 0.3 and with the language profile any it actually adds all international titles as expected. Thanks 👍
