### ISSUE TITLE
Detecting wrong audio Codec/Channels

### ISSUE THREAD

**Issue by g4m3r7ag** [Radarr/Radarr#5302]
**Describe the bug**
Lately Radarr keeps detecting the wrong Audio Codec/Channels which due to Custom Formats causes the same release to be downloaded over and over. In every case I've seen it occur it should detect Dolby Digital Plus (E-AC3) 7.1 but detects Basic Dolby Digital (AC3) 5.1. Every instance I've noticed has been an iFT release. Running MediaInfo on the file manually shows it is indeed E-AC3 7.1 but Radarr does not detect that. 

**To Reproduce**
1. Download a 1080p DD+7.1 iFT release. 
2. After Import check the MediaInfo in Radarr it will show AC3 5.1
3. Check the file manually with MediaInfo and it will show E-AC3 7.1

**Expected behavior**
Radarr to properly detect the audio codec and channels

**Screenshots**

![Screenshot from 2020-11-08 05-46-47](https://user-images.githubusercontent.com/46694420/98481779-b8a71480-21ca-11eb-8406-7329c58381b0.png)

![Screenshot from 2020-11-08 06-26-52](https://user-images.githubusercontent.com/46694420/98481780-bfce2280-21ca-11eb-93a6-5126411d0d7a.png)

Pastebin of the MediaInfo I manually ran on the file

https://pastebin.com/528qaCxm

**Platform Information (please complete the following information):**
 - OS: [e.g. Windows] Docker (hotio) on Ubuntu 18.04
 - Mono Version: [e.g. Mono 5.8] (Only needed under Linux and Mac, found under System -> Status) N/A .NET Core (3.1.7)
 - Browser and Version [e.g. chrome, safari] (Only needed for UI issues)
 - Radarr Version [e.g. 3.0.0.2956] 3.0.0.3989

**Debug Logs**
Turn on debug logs under Settings -> General and wait for the bug to occur again. **Upload the full log file here (or another site and link it). Issues will be closed, if they do not include this!**

Trace log attached. Release was Unhinged. 
[Trace.log](https://github.com/Radarr/Radarr/files/5507001/Trace.log)

**Comment by Qstick** [comment]
Dupe #4852
