### ISSUE TITLE
RSS Sync Grabb Moviesize that not allowed in Qualitysettings

### ISSUE THREAD

**Issue by Mitnick84** [Radarr/Radarr#5303]
Version  3.0.0.3989

Hi, example of a Movie like: Children of Men 2006  Runtime: 1h 49m Size: 2.40GiB  
Releasename: Children.of.Men.2006.German.DL.AC3.1080p.BluRay.x265-FuN

I have in Qualitysettings under Bluray-1080p set a minimum: 60 Minutes 2GB/h, 90 Minutes 3GB/h and 120 Minutes 4.1GB/h

After a RSS Sync it Grabbs all Movies under this minimum settings, when i do a manual Search of the same Movie it say correctly the filesize is lower that i want. 
I can Reproduce this with all Movies when radarr do the RSS Sync Task.

**Comment by bakerboy448** [comment]
Please fill out the template you nuked and provide the trace logs of the grab as requested

**Comment by Mitnick84** [comment]
Cant Provide a log, im on German Trackers that become not so often x265 releases. 
I think the Problem is Clear.

**Comment by austinwbest** [comment]
The problem is clear sure and the trace logs will tell what it is doing. If you want help with it, they will need to be provided.

The trackers you use play no relevance with radarr trace logs bud, you can still provide them :)
