### ISSUE TITLE
v3 filter by quality

### ISSUE THREAD

**Issue by tungmeister** [Radarr/Radarr#5304]
I'd love the ability to filter my library by quality so for example I could create a 720p filter to see any film in my library that was 720p. I'd then be able to upgrade if I deemed it necessary depending on how much value I give to the film.
At present you have to click into the film and look at files to see what the current version's resolution/quality is.

[AB#1763](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1763)

**Comment by Qstick** [comment]
Not going to implement filters by file properties on index at current time
