### ISSUE TITLE
Disabled Automatic search download movies automatically

### ISSUE THREAD

**Issue by danimart1991** [Radarr/Radarr#5308]
**Describe the bug**
Despite disabling the option "Enable automatic search". Movies are automatically downloaded from the indexer.

**To Reproduce**
1. Disable option "Enable automatic search" from indexer.
2. Have a movie that doesn't met the cut off.
3. Wait...

**Expected behavior**
Indexer only must download a release if I manually download from interactive search.

**Screenshots**
![image](https://user-images.githubusercontent.com/5982912/98676420-e079b200-235b-11eb-93e0-4936b749f0cf.png)

**Platform Information:**
 - OS: Docker
 - Container Version: nightly-2f2761a-642 by hotio
 - Radarr Version: 3.0.0.3989

**Comment by ta264** [comment]
You'd need to disable RSS also

**Comment by danimart1991** [comment]
> You'd need to disable RSS also

So. If you disable "Automatic Search", the "Enable RSS" check must be unchecked and disabled automatically. Am i wrong?

**Comment by ta264** [comment]
You are wrong.  If you want to discuss further, please join the discord.
