### ISSUE TITLE
Grabbed file Language is different in Activity and History tabs.

### ISSUE THREAD

**Issue by max01986** [Radarr/Radarr#5312]
**Describe the bug**
For some movies, when it is grabbed, the language is english and the custom formats is matching in the movie history tab, but when I check in the Activity tab, the same file has a different language, (Lithuanian) and the custom format isn't matched.

**To Reproduce**
1. Go to the activity tab and find a movie with the Lithuanian language.
2. Click on the movie to go to the movie page then go in the History tab.
3. The language will be english.

**Expected behavior**
It should be showing the same language and the custom format should match.

**Screenshots**
![2020-11-11_11h42_31](https://user-images.githubusercontent.com/38813688/98839075-1a59bf80-2413-11eb-8b00-3e8c9d06be7f.png)
![2020-11-11_11h42_45](https://user-images.githubusercontent.com/38813688/98839077-1af25600-2413-11eb-963b-fe11301d1d0a.png)

**Platform Information (please complete the following information):**
 - OS: Windows 10 1809
 - Browser and Version Google Chrome 86.0.4240.183 x64
 - Radarr Version 3.0.0.4000

**Debug Logs**
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/5525452/radarr.debug.txt)

**Comment by bakerboy448** [comment]
Support Requests -> [Reddit](https://www.reddit.com/r/radarr/) or [Discord](https://discord.gg/GS7jgXv)

Root cause is likely the LT in the release name...use better groups. The file is not actually Lithuanian.
