### ISSUE TITLE
File renaming with Torrent Source Token

### ISSUE THREAD

**Issue by lebnet** [Radarr/Radarr#5313]
Hello

Related to this issue #4406. I post this feature request about file renaming.

@Qstick it would be great if that feature ever came out. Today, I have 900 files to manually rename...

I can't change the tracker as you suggest because it's the only one with so much diversity in French.

The {Source Title} is available in the history of every film description so radarr has the information somewhere. Do you think it would be possible to add this "source file" field as a token ?

![image](https://user-images.githubusercontent.com/7726777/98850239-bd7ef900-2454-11eb-833c-8a68948e0e7c.png)

Thank you.

**Comment by ta264** [comment]
Please don't open duplicate tickets

**Comment by lebnet** [comment]
@ta264 the last ticket was closed without resolution, the only way I found to get news was to post a new message. again sorry i will be careful next time
