### ISSUE TITLE
Movie Quality

### ISSUE THREAD

**Issue by Cokedriver** [Radarr/Radarr#5314]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to be able to see the Quality of the file on the main "Movies" page. 

**Describe alternatives you've considered**
The option to turn it on/off. (or show/hide how ever you look at it}

**Additional context**
Not sure how many are out there like me but i turn off monitoring once i reach a specific quality and would be nice when you have 2k+ movies to see the quality at a glance.

Also on the each movie page there is only Quality Profile not the quality of the file downloaded.

Thanks for looking and keep up the great work.

**Comment by austinwbest** [comment]
Why do it manually? That is the purpose of cut-off settings & quality settings

**Comment by Qstick** [comment]
You can already in v3
