### ISSUE TITLE
Tooltip for Thumbs Up on Discover Page

### ISSUE THREAD

**Issue by bakerboy448** [Radarr/Radarr#5317]
**Is your feature request related to a problem? Please describe.**
Unclear what the Thumbs Up Means

**Describe the solution you'd like**
Add a tooltip on hover

**Describe alternatives you've considered**
None

**Additional context**
![image](https://user-images.githubusercontent.com/55419169/98943499-39109280-24b5-11eb-8e3e-66bee9726188.png)

**Comment by Qstick** [comment]
@bakerboy448 you want to give this a try yourself?

**Comment by bakerboy448** [comment]
Yeah I'll take a look this evening @Qstick 

I suppose now is a good time to finally setup the desktop 😂

**Comment by Qstick** [comment]
Hehe yep, it's cool if not. Just figured this would be good one to start jumping in
