### ISSUE TITLE
Get Move Title from TMDB with the language used in the profile

### ISSUE THREAD

**Issue by Goluff** [Radarr/Radarr#5326]
This problem is for movies made in a foreign language. Let’s go with a concrete example :

[The 3 L’il Pigs (2007)](https://www.themoviedb.org/movie/35541-les-3-p-tits-cochons) 
This is the title that is grabbed by Radarr, even if my profile is set to French for this movie. The original title is : “Les 3 p'tits cochons“. When I use a french torrent source, the search with the english title returns nothing, since I rarely seen a movie from Quebec being translated...

Before Aphrodite, Radarr grabbed the correct movie title for the search and renaming purpose. Could we have this feature back?

I was wondering if the issue is the same as Sonarr (use of skyhook)?

I know you guys work hard on many different issues. All I would like is this feature request to stay opened until you guys have time for it. 

Thanks A LOT for all the efforts in Radarr.

**Comment by Qstick** [comment]
Naming translations are separate from search and parse now, you can use {Movie OriginalTitle} if you want the original title in naming or {Movie Title:FR} if you want a specific language.
