### ISSUE TITLE
GOOGLE calendar ical sync issues

### ISSUE THREAD

**Issue by geogolem** [Radarr/Radarr#5330]
GOOGLE calendar never refreshes the calendar from Sonarr or Radarr when added via ical/url. It will add the calendar successfully, but it never gets refreshed.

Removing the calendar from GOOGLE calendar and readding the same calendar via url will refresh... 

I have another ical calendar unrelated to Sonarr/Radarr that GOOGLE does refresh.

I believe there is some incompatibility between GOOGLE Calendar and the ical file radarr/sonarr is providing...

I scoured the web and found many others complaining of issues with GOOGLE calendar not syncing. I also noticed that GOOGLE calendar supposedly only refreshes every 12 or 24 hours, but I have not been able to confirm that.

I found a much better tool/solution that will allow the user to specify how often to sync the calendars. It has been working flawlessly for me.

The tool can be found here: https://github.com/derekantrican/GAS-ICS-Sync

I did need to open a PR for the tool in order to gracefully handle cases when the radarr ical link is unavailable. Without my PR, if a calendar URL is unavailable the tool will remove all entries from GOOGLE calendar... my PR handles the case that the URL is unavailable by simply skipping the syncing of that calendar.. The PR can be found here: https://github.com/derekantrican/GAS-ICS-Sync/pull/164

[AB#743](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/743)

**Comment by geogolem** [comment]
I have been using that tool (with my PR integrated) and it has been handling syncing of my calendar to Google calendar flawlessly.

I opened this issue to track the problem and also share my solution.

I still would like to further investigate what in the ical file that Radarr/Sonarr are providing google is tripping over; however, i still think that google script solution is much better because of the ability to set refresh rates etc.

**Comment by geogolem** [comment]
from discord: 
![image](https://user-images.githubusercontent.com/55031547/99151805-94848100-266b-11eb-8c4c-0c90ade3b113.png)

**Comment by bionicdude** [comment]
When i add to google it successfully grabs the title of the calendar but doesn't even initially sync the items, let alone sync after..

I was doing a quick eyeball of the generated ical and noticed that DTSTART and DTEND are both followed by a semicolon instead of a colon - would this affect any thing?

ie

```
BEGIN:VEVENT
CATEGORIES:LuckyChap Entertainment
DTEND;VALUE=DATE:20201226
DTSTAMP:20210114T121145Z
DTSTART;VALUE=DATE:20201225
SEQUENCE:0
STATUS:CONFIRMED
