### ISSUE TITLE
Notify when manual import required

### ISSUE THREAD

**Issue by derekoharrow** [Radarr/Radarr#5344]
**Is your feature request related to a problem? Please describe.**
Sometimes, films won't automatically import after download, which could be for a number of reasons.
They can sit in the Queue forever until you notice them and manually import, or delete them.
It would be useful to have an option to have Radarr send a notification in this situation so that you know to go and take a look at the queue.

**Describe the solution you'd like**
Add an option to the Connections dialogue to notify "On Manual Import Required", and send a notification accordingly.

**Comment by bakerboy448** [comment]
Closing no plans at this time.

Existing notifications can work for this...or more specifically the absence of one after the grab.

**Comment by Qstick** [comment]
We have import failure notifications on Lidarr, I wouldn't say this is out
