### ISSUE TITLE
Movie with year problem

### ISSUE THREAD

**Issue by Firemad03** [Radarr/Radarr#535]
Radarr have a problem with movie with year.

Check it out this one:

![image](https://cloud.githubusercontent.com/assets/24792889/22446778/83bdfa82-e71c-11e6-8c13-9830153c095a.png)

Radarr when to download this one:

![image](https://cloud.githubusercontent.com/assets/24792889/22446785/92853a58-e71c-11e6-853d-175a94a41277.png)

But I want the 2016 ;)

**Comment by Firemad03** [comment]
Same thing with Arrival

![image](https://cloud.githubusercontent.com/assets/24792889/22449590/1d2c09e0-e72f-11e6-8558-58fa36b98baf.png)

Radarr took Arrival 2013 because file size was bigger I think:

![image](https://cloud.githubusercontent.com/assets/24792889/22449609/3a93223e-e72f-11e6-8b05-43df52d3bafd.png)

**Comment by galli-leo** [comment]
Are you on the latest nightly? This should have been fixed a few days ago.

**Comment by Firemad03** [comment]
This one is on Build 0.2.0.267

**Comment by Aquatakat** [comment]
I can confirm with 0.2.0.267. The other releases are rejected for other reasons but this one is acceptable even though it's the wrong date:

![image](https://cloud.githubusercontent.com/assets/9537912/22614256/1fb49d88-ea3d-11e6-9f0f-0e620e015cb5.png)

**Comment by Aquatakat** [comment]
My example was fixed with 0.2.0.288.

**Comment by jOOc** [comment]
Im on .290 and getting this when adding Red Sonja 1985
![image](https://cloud.githubusercontent.com/assets/9382342/22662163/54b6b648-eca8-11e6-9ded-971992514ea4.png)

**Comment by onedr0p** [comment]
@jOOc what indexers are you using?

**Comment by jOOc** [comment]
@onedr0p Isohunt, Kickass (kat.how), RARBG & The Pirate Bay

**Comment by onedr0p** [comment]
Fixed in next released

**Comment by QT31416** [comment]
@jOOc how did you get The Pirate Bay to work as an indexer? I can't get it to work on radarr, but I have it working in sonarr. If you could attach a screenshot of the indexer settings, that would be great.

**Comment by onedr0p** [comment]
He prolly uses jackett which we recommend.

**Comment by QT31416** [comment]
Do you have a recommended config for the Torznab setting? I'm also using jackett, I copied my settings for sonarr, but it returns the error:
Unable to connect to indexer: Sequence contains no elements
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 324
![radarr](https://cloud.githubusercontent.com/assets/26166095/23556306/209bee78-0067-11e7-8f37-f1478571363d.png)

**Comment by onedr0p** [comment]
Try to update jacket to the latest version :)

**Comment by QT31416** [comment]
Wow. That worked perfectly. Thanks for the help, and thank you for the wonderful fork!

**Comment by jOOc** [comment]
Glad you solved it
