### ISSUE TITLE
Remove truncating/width restrictions on Interactive Search table

### ISSUE THREAD

**Issue by ephekt** [Radarr/Radarr#5350]
**Description:**

Remove the max-width on <td> html element on the interaction search page. The challenge is that any sufficiently long or verbose release title gets truncated use '...' and make it very difficult to see release group. Similarly, it breaks mobile very badly. By removing the td restriction on width, both the desktop and mobile are much more usable and a big win in my humble opinion. I'd appreciate anyone taking this into consideration.

InteractiveSearchRow-title-1bOVc {
    max-width: 30vw;

Removing the `max-width` here really makes everything nicer.

**Radarr Version:** 3.0.0.4000
```
Version
3.0.0.4000
Package Version
3.0.0.4000-ls29 by linuxserver.io
.NET Core
Yes (3.1.7)
Docker
Yes
DB Migration
186
AppData directory
/config
Startup directory
/app/radarr/bin
```

**Comment by austinwbest** [comment]
This won't be done again as it pushes things to much. Just need to adjust the html accordingly. It worked on mobile when it was added as I checked multiple resolutions and devices 🤔

iirc there is a tool tip to show the entire name

**Comment by ephekt** [comment]
I see. I've not seen the tooltips, and on-hover alt-text doesn't work on mobile (you can hover your mouse on a desktop and see the full filename, if you're thinking of that). I patched my local copy but obviously that will blow away with new updates. Kind of a bummer mobile got crushed in the v3 move. Thanks for replying, though.

**Comment by ephekt** [comment]
I just verified, Sonarr does the full-table. What was the issue with that version? On mobile, it's very easy to horizontal scroll w/ touch which is a nice benefit to Sonarr not having to truncate.

**Comment by austinwbest** [comment]
I can find the issue for it at some point as it has screenshots.. Now iirc
it was pushing things off screen and creating a nightmare of scrolling as a
desktop doesn't scroll like mobile.

It's not built specifically for mobile however it does support it and we do
try to make sure everything works on both.

To this end, it doesn't mean it will stay unusable for mobile (I know the
are not tool tips) but it won't go back to just full width either unless we
figure out a way to make it happy without a complete change of the layout.

I assigned it to myself so I won't forget about it, I'll do some more
tinkering and get to find a solution for all :)

**Comment by ephekt** [comment]
That make sense, horizontal scroll is tougher on desktop. Maybe we just need to include this line
`max-width: 100% !important;` in the @mobile constructed css? There is already a place for it, I just have not noticed. See screenshot below where I add it to the media max-width CSS rule:
![image](https://user-images.githubusercontent.com/35703/99190464-471c1880-272c-11eb-9f3e-86c291965007.png)

This would then leave desktop as-is! Win-win.

**Comment by ephekt** [comment]
I am also seeing, even on desktop, you have to horizontally scroll to see columns. So I think I'm more confused if this was an html regression? Current view on search requires hovering over a release title to see the alt-text to see the full release title. Seems like poor UX we could drastically improve by just showing the full title.

**Comment by glassbase** [comment]
Titles are way too short on iPhone and iPad for me. Unless the movie title is one word or 2 short words, I don’t see audio details or release group. 

This is my only issue with R v3. S v3 truncates the remaining title name to the next line.
