### ISSUE TITLE
library cleanup

### ISSUE THREAD

**Issue by mytvpro** [Radarr/Radarr#5359]
please consider feature to delete all files from libarary which are not mapped.
please also consider an option to delete directories which are indicated as containing existing movies during import or dedupe option to merge dirs and keep newer files.

my libarary is huge and unmanageable manually, with tens of thousands of movies. i really wish radarr would help me remove orphaned directories and files and duplicate movies

**Comment by bakerboy448** [comment]
Generally speaking it is not in the scope of *Arrs to deduplicate and cleanup your existing disorganized library.

Use Filebot or ~ + by hand to organize and cleanup.

We may enhance some of the import features, but not to this degree.

You can use the *arrs to mass move what you have organized in your library (change root folder -> move files)

also don't download to your library, I have a feeling you were doing that.

You can point manual import to your disorganized mess and pull whatever into your new organized library/root folder.
