### ISSUE TITLE
Import failing due to added "/" in path from qBit resulting in path combination failure

### ISSUE THREAD

**Issue by KierenConnell** [Radarr/Radarr#5362]
**Describe the bug**
The exact same issue as [Sonarr Issue 4091](https://github.com/Sonarr/Sonarr/issues/4091)
Torrent downloaded, goes missing on completion, Event Log shows
`Couldn't process tracked download Murder on the Orient Express 2017 10bit hevc-d3g: Cannot combine OsPaths of different platforms ('C:\Users\Administrator\Downloads\' + 'Murder on the Orient Express 2017 10bit hevc-d3g/Murder on the Orient Express 2017 BluRay 10Bit 1080p DD5.1 H265-d3g.mkv')`

System Information

Sonarr Version: 3.0.0.4079
Operating System: Windows Server 2019
qBit Version: 4.3.0.1

**Debug Logs**
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/5546230/radarr.debug.txt)

**Comment by Qstick** [comment]
Not quite the same issue, also that fix is already in your build.... @Taloth @ta264 something else we need to handle?

**Comment by KierenConnell** [comment]
Not sure if it's helpful, but on the 13th Radarr was importing from qBit perfectly fine for me.
Nothing else has changed on my side except Radarr updates, so it's been introduced since then.

**Comment by ta264** [comment]
@KierenConnell please could you join the discord to help us debug this?
