### ISSUE TITLE
Movie downloaded date in custom script?

### ISSUE THREAD

**Issue by Dr0bac** [Radarr/Radarr#5369]
Is date when movie is downloaded accessible through radarr custom scripts variables?

![Untitled](https://user-images.githubusercontent.com/43797966/99327553-7e98db00-287a-11eb-8eb4-a92ac70040c2.png)

I want to automate deleting movies from radarr database that meets several conditions, and downloaded date is included.

**Comment by austinwbest** [comment]
No but you can make an api request from the custom script data and get whatever you need. Please use discord for further questions & support.
