### ISSUE TITLE
Support of French movies in Radarr v3 (Aphrodite)

### ISSUE THREAD

**Issue by Ianik** [Radarr/Radarr#5373]
**Describe the bug**
I have upgraded from v2 to v3 today.
I used to have in my library some English Movies and some French Movies.
For the French movies, I use to have the movie profile downloaded in French and the movie tittle was in French.
I had set separate download profile for French and English. It was working well.

Now with Radarr v3 all my French movies have been updated to English profile and tittle names.
How can have both French and English movies working in the same set_up?

I also had 2 Epic Fail in the last hour I have used v3. And the Radarr is not installing correctly for me.

**Expected behavior**

**Platform Information (please complete the following information):**
 - OS: Windows Server 2012
Version 3.0.0.4103
.NET Core Yes (3.1.10)
DB Migration 186
Mode Tray
[radarr.txt](https://github.com/Radarr/Radarr/files/5559661/radarr.txt)

**Debug Logs**
Turn on debug logs under Settings -> General and wait for the bug to occur again. **Upload the full log file here (or another site and link it). Issues will be closed, if they do not include this!*
[]([]([radarr.txt](https://github.com/Radarr/Radarr/files/5559666/radarr.txt)))
*

**Comment by bakerboy448** [comment]
Support Requests -> [Reddit](https://www.reddit.com/r/radarr/) or [Discord](https://discord.gg/GS7jgXv)

Those logs do not show any issues.
