### ISSUE TITLE
Add Spain country for Certification Country

### ISSUE THREAD

**Issue by danimart1991** [Radarr/Radarr#5374]
Like #5351. It would be great if Spain were added as a certificate provider.

I have seen that it is not included from Servarr, but it is available in TMDb.

Best Regards. A Radarr lover 😍.

**Comment by Qstick** [comment]
Feel free to PR it, Fairly straightforward.. Servarr doesn't filter what's sent, do you have cases showing it not being included in response when it's on TMDB?

Example
https://github.com/Radarr/Radarr/commit/6beb8c8b05847e08eb775032048e37350dd350f3
