### ISSUE TITLE
no import after grab because of unknown title

### ISSUE THREAD

**Issue by s0mm3rb** [Radarr/Radarr#5375]
**Describe the bug**
in the past weeks radarr often does not import a downloaded movie from the dl client
because the release title does not match with the title in radarr
although the title exists on tmdb

I have movies in radarr, from which **i am sure** they where listed with the german title in radarr, at the moment I added them and are now listed with the english title
I guess that happend through the refresh movie task
but it does not make sense to me

the lastest issue was **Unhinged (2020)**
the torrent was grabbed yesterday, downloaded and is now sitting in the torrent client wasting space
the very same torrent is waiting in the activity tab to be added again
of course it can't add it because it already exists, so deluge throws an error
and it does not import the downloaded file because it can't map the title
the german title exists on tmdb: [https://www.themoviedb.org/movie/625568-unhinged/translations](https://www.themoviedb.org/movie/625568-unhinged/translations)

I request a feature to map the grabbed release to the matching movie at the moment radarr sends it to the dl client
(like it does when force grabbing it through manual search)
the releases for those movies are grabbed by imdb match
if it is able to grab a release that does not match the title in radarr but matches the imdb, it should also be able to import it afterwards

some movies where even downloaded 2 or 3 times and not imported
all torrent, because the torrent client removes them automatically after seeding requirements are fullfilled
and radarr added the same torrent again just minutes later...

I also tried switching to lenient parsing but that only made it worse
cause now it would not match movies like
`the.movie.2020.internal.german....`
or
`the.movie.2020.directors.cut.german...`

thanks

**Platform Information (please complete the following information):**
 - OS: Docker Container (linuxserver/sonarr:5.14)
 - Mono Version: 5.14.0.177
 - Radarr Version: 0.2.0.1504

**Debug Logs**
```
2020-11-18 13:30:27.9|Debug|Parser|Parsing string 'Unhinged.Ausser.Kontrolle.2020.German.DL.1080p.BluRay.x264-DETAiLS'
2020-11-18 13:30:27.9|Debug|Parser|Movie Parsed. Unhinged Ausser Kontrolle - 2020 
2020-11-18 13:30:27.9|Debug|ParsingService|Language(s) parsed: German
2020-11-18 13:30:27.9|Debug|QualityParser|Trying to parse quality for Unhinged.Ausser.Kontrolle.2020.German.DL.1080p.BluRay.x264-DETAiLS
2020-11-18 13:30:27.9|Debug|ParsingService|Quality parsed: Bluray-1080p v1 (None)
2020-11-18 13:30:27.9|Debug|Parser|Parsing string 'Unhinged Ausser Kontrolle 2020 German DL 1080p BluRay x264-DETAiLS'
2020-11-18 13:30:27.9|Debug|Parser|Movie Parsed. Unhinged Ausser Kontrolle - 2020 
2020-11-18 13:30:27.9|Debug|ParsingService|Language(s) parsed: German
2020-11-18 13:30:27.9|Debug|QualityParser|Trying to parse quality for A Movie 2020 German DL 1080p BluRay x264-DETAiLS
2020-11-18 13:30:27.9|Debug|ParsingService|Quality parsed: Bluray-1080p v1 (None)
2020-11-18 13:30:27.9|Debug|Parser|Parsing string 'Unhinged.Ausser.Kontrolle.2020.German.DL.1080p.BluRay.x264-DETAiLS'
2020-11-18 13:30:27.9|Debug|Parser|Movie Parsed. Unhinged Ausser Kontrolle - 2020 
2020-11-18 13:30:28.0|Debug|Parser|Parsing string 'Unhinged.Ausser.Kontrolle.2020.German.DL.1080p.BluRay.x264-DETAiLS'
2020-11-18 13:30:28.0|Debug|Parser|Movie Parsed. Unhinged Ausser Kontrolle - 2020 
2020-11-18 13:30:28.0|Debug|DownloadedMovieImportService|Unknown Movie Unhinged.Ausser.Kontrolle.2020.German.DL.1080p.BluRay.x264-DETAiLS
```
might be related: #5290

**Comment by bakerboy448** [comment]
closing; this exists on v3 and works fine;  alt titles are used on v3.

**Comment by s0mm3rb** [comment]
it's not just that alt titles are not used
it's also that radarr changed the titles in it's database
and does not use the language specific title anymore

I recently imported a bunch of x265 to replace x264 files
and radarr created new folders and named everything with the english titles
movies that have been added with the german titles a few months ago
I can live with that (although plex was unhappy)
but it clearly indicates a bigger issue than just not using alt titles in v2

I had to match a few of those in plex as well, cause plex also uses the library language to match them
for example:
![grafik](https://user-images.githubusercontent.com/38328575/99559714-5ff32b00-29c5-11eb-9b8c-b64ceb574fa5.png)

you can see that radarr automatically grabbed it in the past and upgraded it just fine, all with the german title
now when I imported the x265 version, I had to manually match it on import
because now, the title has changed in radarr, thus not recognizing the movie in the filename
and radarr imported it to a new path instead just replacing the old file

thanks

**Comment by fryfrog** [comment]
> because the torrent client removes them automatically after seeding requirements are fullfilled

Don't do this. Set your torrent client to *pause* when seed time/ratio goals are met, let sonarr/radarr do the remove after it has been imported by enabling Remove under Completed and Failed Download Handler. For exactly the reason you're seeing.

**Comment by s0mm3rb** [comment]
> Don't do this. Set your torrent client to _pause_ when seed time/ratio goals are met, let sonarr/radarr do the remove after it has been imported by enabling Remove under Completed and Failed Download Handler. For exactly the reason you're seeing.

it can't remove a torrent it does not recognize/accept after grab

it added the torrent "Unhinged.Ausser.Kontrolle.2020.German.DL.1080p.BluRay.x264-DETAiLS"
because the tracker supports imdb search and it matched with the id
so it was grabbed and sent to the dl client
but because the release title does not match the title in radarrs database it won't import it (and it does not show any AKA titles)
the active torrent will never be touched again by radarr, even though it had set the radarr category
on the next rss sync it will grab the exact same torrent that is now active again
and try to add it to the dl client, which it can't because the torrent already exists
the torrent will now just sit in the activity tab and radarr won't grab a new release because of the pending one

the issue is not download handling it is the fact that it changed the titles in its database and won't even add new movies with the language title rather than only the english title

for example: 
I have a [german kids movie](https://www.themoviedb.org/movie/698420-die-pfefferkorner-und-der-schatz-der-tiefsee/translations) in my database that is supposed to be released in february
it was added automatically from a trakt list about 2 weeks ago and it is listed in radarrs database with the english title and no AKA
I can most certainly quarantee that it will never be grabbed on any rss sync
because the scene will not release a german production with the english title
I tried to delete it and added it from imdb again and it still shows up with the english title
![grafik](https://user-images.githubusercontent.com/38328575/99695496-ec692080-2a8d-11eb-863a-d9986c66b96a.png)

an other one, from the same list, works fine because it has the AKA titles
is that something I can modify somehow?
why does it have alt titles on one movie but not the other?
when for both, the alt titles exist on tmdb
![grafik](https://user-images.githubusercontent.com/38328575/99692768-f2a9cd80-2a8a-11eb-878b-c83e963cff5a.png)

John Wick is another weird example for that (screenshot in the post above)
chapter 1 is listed with the english title, metadata and AKA titles
chapter 2 is listed with the german title, metadata and AKA titles
chapter 3 is listed with the englisch title and metadata and NO AKA titles
all three where grabbed and updated automatically in the past
but somehow down the road radarr changed the metadata of chapter 3, thus no longer accepting AKA titles

> Set your torrent client to _pause_ when seed time/ratio goals are met, let sonarr/radarr do the remove

and how would that prevent radarr to kick them out of seed prematurely?
I tried that in the past, it never worked
also I don't want torrents with 0 share ratio wasting space, 
that's why they are removed by the client after x days, no matter the ratio

**Comment by bakerboy448** [comment]
Add alt titles to TMDB

**Comment by s0mm3rb** [comment]
> 
> 
> Add alt titles to TMDB

they are already there

**Comment by bakerboy448** [comment]
> > 
> 
> > 
> 
> > Add alt titles to TMDB
> 
> 
> 
> they are already there

You literally just said it was not there

**Comment by s0mm3rb** [comment]
> You literally just said it was not there

I literally said that they are in TMDB but not in radarr
all the movies I mentioned have the alt titles in TMDB
but radarr does not show them

that's the summary of my posts above

**Comment by bakerboy448** [comment]
sounds like you have a SUPPORT request for alt titles not loading into radarr
have you tried refreshing the movie?
john wick is fine for me
Support Requests -> [Reddit](https://www.reddit.com/r/radarr/) or [Discord](https://discord.gg/GS7jgXv)

![image](https://user-images.githubusercontent.com/55419169/99700521-e6a51800-2a58-11eb-9cb3-20069d61079a.png)
![image](https://user-images.githubusercontent.com/55419169/99700643-09373100-2a59-11eb-88d5-8740e774875a.png)

**Comment by s0mm3rb** [comment]
> Add alt titles to TMDB

we might be talking apples and oranges here

I am talking about the translations tab on TMDB [https://www.themoviedb.org/movie/458156-john-wick-chapter-3/translations](https://www.themoviedb.org/movie/458156-john-wick-chapter-3/translations)
but you might be talking about the titles tab [https://www.themoviedb.org/movie/458156-john-wick-chapter-3/titles](https://www.themoviedb.org/movie/458156-john-wick-chapter-3/titles)

radarr always showed the profile specific language of the movies I added
as it still does for John Wick Chapter 2 but not for Chapter 3 any longer
and that movie also (like John Wick 3) does not have a german entry on the titles tab but of course it has a translation
[https://www.themoviedb.org/movie/324552-john-wick-chapter-2/titles](https://www.themoviedb.org/movie/324552-john-wick-chapter-2/titles)
[https://www.themoviedb.org/movie/324552-john-wick-chapter-2/translations](https://www.themoviedb.org/movie/324552-john-wick-chapter-2/translations)

so this should not be the issue

**Comment by s0mm3rb** [comment]
> have you tried refreshing the movie?

yes I have, thank you
radarr does an automatic refresh every 24h also
and I guess at one point the automatic task removed the translation from it's database
because they have been there

**Comment by s0mm3rb** [comment]
> sounds like you have a SUPPORT request for alt titles not loading into radarr

might be
but I never saw as much titles like you have in your screenshot
not on any movie in my db

**Comment by bakerboy448** [comment]
For v3 this is how things work:

Radarr uses both Alt title and translations for parsing and searching. Search will use the Original Title, English Title, and Translated Title from whatever languages you have preferred (in profile and CFs). Parsing should look for a match in all Translations, Alt Titles, and Original Title.

For v0.2
I'd suggest upgrading to v3... v0.2 is absolutely horrible for the situations you describe.

**Comment by bakerboy448** [comment]
Also for seeds you can set min ratio or min time requirements

**Comment by s0mm3rb** [comment]
will switch to v3 as soon as I can

thanks
