### ISSUE TITLE
Feature Request: unsolicited downloads

### ISSUE THREAD

**Issue by astlaurent** [Radarr/Radarr#538]
One feature I used very heavily in couchpotato (mostly because it never worked any other way, but still a nice feature actually) was to be able to manually send an NZB to SABNZB for a movie that was never added into couchpotato with the proper category and then after it downloaded couchpotato would see the movie and import it, rename it, and process it. I attempted to do the same thing with drone factory and it just ignores the movie sitting in the folder. This is nice for manual downloads that i see when i am browsing through the indexer, i can simply just send it to sab and rely on everything happening without worrying about adding it to Radarr and letting Radarr do all the leg work for it.

**Comment by Antexa** [comment]
This feature would be nice

**Comment by d4rk22** [comment]
+1 for this. There should be an option under the Media Management tab to specify your primary movie downloads folder where it auto adds movies to.

**Comment by onedr0p** [comment]
Please add this to feathub of it isn't already there.
