### ISSUE TITLE
MacOS nightly treated as a folder, not an executable

### ISSUE THREAD

**Issue by dkids** [Radarr/Radarr#5381]
I'm running Big Sur (MacOS 11.0.1) on an Intel Mac.   A couple of days ago, Radarr auto-updated and wouldn't reload.   When I tried right-click to open, the message that comes up is "You do not have permission to open the application “Radarr”.   Contact your computer or network administrator for assistance."

I downloaded the latest version two days ago and again today.  They're both being treated as a folder, not as an app.  Also, items are in Radarr/ where I would expect to see Radarr.app/Contents/

**Comment by ta264** [comment]
The downloads you are referring to are not mac app bundles, they're binaries for the updater tool / for you to run manually
