### ISSUE TITLE
Manual upgrade, missing from imports when under different title

### ISSUE THREAD

**Issue by 4C3T** [Radarr/Radarr#5389]
**Describe the bug**
When a movie, for eg. "Erased" was substituted for "The Expatriate" (From YIFY to RARBG, of course!), it went missing. It's still in µTorrent at 100% (and re-check didn't kick it into gear either).
When pulling up the page for the movies, you can still see in the history-tab that it was marked as downloaded:

(From the tab history when hovering the (?)-button):
`Details

Name:
    The.Expatriate.2012.1080p.BluRay.x265-RARBG
Indexer:
    RARBG
Release Group:
    RARBG
Info:
   (Some address here.... To a torrent)
Download Client:
    uTorrent
Age (when grabbed):
    6 days
Published Date:
    Nov 12 2020 17:21:39`

But it would seem that it got lost somewhere, and I'm guessing it's due to the alternate title.
It was the same with other titles as well, and it'd be nice to not having to manually import these. It's a bit cumbersome since, in my case, I have a remote computer and it takes a little longer to copy.
Not by much since it's a Gb-network, but still; Slow computer + Windows networking, in & out, back and forth, + other traffic makes Jack a dull boy.

**In the logs it can be seen that it's attempting to import the movie "The Hard Word" which was substituted for "The Australian Job", but it seem to think it doesn't exist.**

**Platform Information (please complete the following information):**
 - OS: Windows Server 2019
 - Mono Version: -
 - Browser: Firefox 83.0 (64-bit)
 - Radarr Version: 0.2.0.1504 develop

**Debug Logs**
Attached
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/5580609/radarr.debug.txt)

**Comment by bakerboy448** [comment]
V3 uses alt titles from TVDB

If v0.2 has an option in the activity queue to show unknown that will likely find it as well

Regardless v0.2 is EOL

**Comment by 4C3T** [comment]
Ok. I'll try the v3 then.

There's no mentioning of v3 on the default download page though, but I found it here on github and I could just change it into "nightly" under settings and it's currently undergoing an upgrade.

Thanks.

**Comment by 4C3T** [comment]
Nice... Took some tinkering, but I found it when I searched the indexers, then it had a lot more useful stuff, like grabbing it.
Only thing that I could complain about is that the search-tab would be nice to be re-clickable (like v2) and not one-shot, but I like the new layout (except for the front page which I think looked better in the old version).
