### ISSUE TITLE
Manual search works but RSS Sync doesn't

### ISSUE THREAD

**Issue by int3nz0r** [Radarr/Radarr#539]
I'm experiencing a weird thing. Some of the movies are released in the quality and profile I set up in Sonarr (I know for a fact). When I manually search a movie it finds releases that meet the requirements and sends them to my SABnzbd. But when I test it by starting the RSS sync for my whole wanted list it won't find any release to grab. All my added movies are monitored and I'm running 0.2.0.267.
![schermafbeelding 2017-01-31 om 03 58 19](https://cloud.githubusercontent.com/assets/1075373/22450870/16f8dbbc-e76a-11e6-87f0-9c250cc86d9f.png)
![schermafbeelding 2017-01-31 om 03 58 43](https://cloud.githubusercontent.com/assets/1075373/22450872/172da3ba-e76a-11e6-9a32-5da978688382.png)
![schermafbeelding 2017-01-31 om 03 59 05](https://cloud.githubusercontent.com/assets/1075373/22450871/171c0650-e76a-11e6-9312-25698988eb07.png)
![schermafbeelding 2017-01-31 om 04 00 14](https://cloud.githubusercontent.com/assets/1075373/22450873/172dc4c6-e76a-11e6-95f3-d909134f6a9f.png)

 The whole automatic downloading feature is not working for me. Any thoughts?

**Comment by fryfrog** [comment]
If the RSS feed doesn't contain a movie you want, it isn't going to be there for Radarr to see and fetch. To test *this* portion of it, you'll need to wait until a movie you've added is uploaded to usenet.

Or just use the search on the movies you want.

**Comment by galli-leo** [comment]
As fryfog said the rss sync only checks the 100 latest torrents / nzbs of your indexer and then those, that match any movie and match your profiles, are downloaded.
