### ISSUE TITLE
Release matching does not work for releases without semicolon

### ISSUE THREAD

**Issue by eliecharra** [Radarr/Radarr#5394]
**Describe the bug**
Radarr name matching is very strict as when searching for a movie with semicolon in name, indexer releases without semicolon are not matched. This excludes a lot of movie to be automatically downloaded.
Maybe we could make the matcher smart enough to allow releases without separators to be matched.

**To Reproduce**
1. Try to add a movie with semicolon : e.g. : `Ip Man: 4 The Finale`
2. Movie is added but releases without semicolon are not matched

**Expected behavior**
Releases without semicolon match movie title.

**Screenshots**
![image](https://user-images.githubusercontent.com/6154987/100102733-4c800e00-2e64-11eb-9501-b7c41fe983d3.png)

**Platform Information (please complete the following information):**
 - OS: **Arch linux 5.8.14-arch1-1**
 - Mono Version: **5.20.1.34**
 - Radarr Version: **0.2.0.1504**
- Docker setup:
```
version: "3.5"
services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    restart: always
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
    networks:
      - vpn
      - default
    volumes:
      - ./config:/config 
      - /mnt/downloads:/mnt/downloads
```

**Debug Logs**
```
radarr     | [Debug] NzbSearchService: Total of 13 reports were found for [Ip Man 4 : Le Dernier Combat] from 1 indexers 
radarr     | [Info] DownloadDecisionMaker: Processing 13 releases 
radarr     | [Debug] Parser: Parsing string 'Ip Man 4 The Finale 2019 VFi 1080p BluRay AC3 x265-Winks' 
radarr     | [Debug] Parser: Movie Parsed. Ip Man 4 The Finale - 2019  
radarr     | [Debug] ParsingService: Language(s) parsed:  
radarr     | [Debug] QualityParser: Trying to parse quality for A Movie 2019 VFi 1080p BluRay AC3 x265-Winks 
radarr     | [Debug] ParsingService: Quality parsed: Bluray-1080p v1 (None) 
radarr     | [Debug] ParsingService: No matching movie Ip Man 4 The Finale 
radarr     | [Debug] DownloadDecisionMaker: Release rejected for the following reasons: [Permanent] Failed to map movie, found title Ip Man 4 The Finale, expected one of: Ip Man 4 : Le Dernier Combat, Ip Man 4, Ip Man 4: 
The Finale 
radarr     | [Debug] Parser: Parsing string 'Ip Man 4 The Finale 2019 MULTi 1080P BluRay Remux (AVC-H264) Dani0000' 
radarr     | [Debug] Parser: Movie Parsed. Ip Man 4 The Finale - 2019  
radarr     | [Debug] ParsingService: Language(s) parsed:  
radarr     | [Debug] QualityParser: Trying to parse quality for A Movie 2019 MULTi 1080P BluRay Remux (AVC-H264) Dani0000 
radarr     | [Debug] ParsingService: Quality parsed: Remux-1080p v1 (None) 
radarr     | [Debug] ParsingService: No matching movie Ip Man 4 The Finale 
radarr     | [Debug] DownloadDecisionMaker: Release rejected for the following reasons: [Permanent] Failed to map movie, found title Ip Man 4 The Finale, expected one of: Ip Man 4 : Le Dernier Combat, Ip Man 4, Ip Man 4: 
The Finale 
```

Thanks a lot for this awesome tool which saves us a lot of time :+1: 
I can manage to make a pull request to fix this if we both agreed on a way to fix it :pray:

**Comment by bakerboy448** [comment]
Relatively fine in v3 as alt titles exist without the `:` for most movies with a `:`

**Comment by eliecharra** [comment]
Thanks for your quick answer, I'm giving a try with the v3 :+1: 

It's still not working for `Ip Man 4`.
What do you thing about appending additional alt names without semicolon when semicolon is found (`s/://`) on matcher side to improve compatibility ? I don't think this could introduce unwanted side effects.

**Comment by bakerboy448** [comment]
Discussed internally with the team and tested;

No issues with `:` so it's likely your indexers

![image](https://user-images.githubusercontent.com/55419169/100114593-33149d00-2e37-11eb-95e9-d6b040274476.png)
