### ISSUE TITLE
Radarr update to 3.0.0.4141 fails permissions denied macos

### ISSUE THREAD

**Issue by chrisfoster1971** [Radarr/Radarr#5395]
**Describe the bug**
via Radarr UI attempt update to 3.0.0.4141 also affects auto update.

**To Reproduce**
1. Go to 'System\Updates"
2. Click on 'Install latest"
3. Monitor left pane, Shows "Failed"

**Expected behavior**
Manually select "Install latest update"
Monitor progress in left pane
Reload when prompted
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/5591148/radarr.debug.txt)

**Screenshots**

**Platform Information (please complete the following information):**
 - OS: MacOS 10.13.6
 - Mono Version: [e.g. Mono 5.8] (Only needed under Linux and Mac, found under System -> Status) N/A .NET Core 3.1.10
 - Browser and Version: Safari
 - Radarr Version [e.g. 3.0.0.4136]

**Debug Logs**
Turn on debug logs under Settings -> General and wait for the bug to occur again. **Upload the full log file here (or another site and link it). Issues will be closed, if they do not include this!**

**Comment by bakerboy448** [comment]
Known issue;
Manually update to 4141

The updater for the prior 3 releases is borked.
