### ISSUE TITLE
Same release is grabbed twice if searched successively

### ISSUE THREAD

**Issue by agneevX** [Radarr/Radarr#5396]
**Describe the bug**

If `Search Movie` is run on a movie twice, in a very short amount of time, Radarr ends up grabbing the same movie twice. 

**To Reproduce**

1. Go to any movie (which can be upgraded)
2. Click on `Refresh Movie`
3. Immediately after a release is sent to download client, click the same button again
4. See the same movie being grabbed again

**Expected behavior**

Radarr does not grab the same release twice.

**Screenshots**

![alt_text_here](https://media.discordapp.net/attachments/264387956343570434/780832398026866688/unknown.png)

**Platform Information (please complete the following information):**
 - OS: `Debian Linux`
 - Mono Version: N/A
 - Browser and Version: N/A
 - Radarr Version: `3.0.0.4141`

**Debug Logs**
https://paste.ubuntu.com/p/FRVjD5jRBK

[AB#751](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/751)

**Comment by bakerboy448** [comment]
can you reproduce in sonarr and open the GHI there w/ appropriate details?

then just mention this one in that?

this way it'll be fixed up stream and then pulled downstream :D

**Comment by agneevX** [comment]
Is there any update on this?

**Comment by bakerboy448** [comment]
When there is an update to be posted then either an update will be posted here; or a Pull Request will be linked to this GitHub Issue.
