### ISSUE TITLE
Filter Library by file name

### ISSUE THREAD

**Issue by Glasti1** [Radarr/Radarr#5397]
**Is your feature request related to a problem? Please describe.**
I am trying to find UHD or HDR files in my 1080 library, but it seems not possible

**Describe the solution you'd like**
It would be great if we can filter the library by words in the file name.

**Describe alternatives you've considered**
writing a script, but i am not good at writing scripts! 

**Additional context**
I don't NEED this request, but it would be cool to have.

**Comment by Qstick** [comment]
No plans of this with multiple file support coming things will change
