### ISSUE TITLE
WebDL/WebRip being rejected for mismatch when grouped together

### ISSUE THREAD

**Issue by bakerboy448** [Radarr/Radarr#5398]
**Describe the bug**
WebDL and WebRip are grouped together and should not be rejected due to a mismatch
![image](https://user-images.githubusercontent.com/55419169/100130067-e5546080-2e47-11eb-97db-f997536d7ddc.png)

This _should_ be an easy pull from sonarr.

**Comment by Qstick** [comment]
a152ab2b5681c8060e561553b90135db77407042
