### ISSUE TITLE
Release Rejected -- Hardcoded subs found: Generic Hardcoded Subs

### ISSUE THREAD

**Issue by thezoggy** [Radarr/Radarr#540]
Seeing a release rejected for `Hardcoded subs found: Generic Hardcoded Subs`

Release: Nocturnal.Animals.2016.720p.HC.WEBRip.x264.AAC2.0-STUTTERSHIT

Doesn't appear to be a way to toggle off this being a reject reason... 
One could easily block these in the future with ignore tag with: `HC.WebRip` (assuming that `.` would match anything)?

**Comment by galli-leo** [comment]
You can still manually download that release. With that being said I will add a toggle for that.

**Comment by Stibbons** [comment]
+1. Got this on Fifty Shades Darker.

**Comment by SuperPotatoMen** [comment]
@galli-leo Can you make a switch to allow multisubs also? Will be fantiastic 👍

**Comment by galli-leo** [comment]
@SuperPotatoMen The idea is to have a "tag field" where you can put the subs you want whitelisted. e.g.: multi,swe,nl

**Comment by SuperPotatoMen** [comment]
@galli-leo that is fantastic, but if i follow you correctly, i use the tag field to allow MULTISUBS but it still rejected with the reason: 
Release Rejected
Hardcoded subs found: multisubs

**Comment by onedr0p** [comment]
He is talking about a new feature.

**Comment by Quiksmage** [comment]
+1 on this feature being added. I think that 99% of the reason I have WEB-DL enabled is for those early release korean subtitle rips.

**Comment by cwallace** [comment]
+1 would really like to see this feature added. many of the early release WEB-DL have HC subs, which I'm perfectly fine with.

**Comment by Quiksmage** [comment]
what should we white list for generic hc subs?

**Comment by galli-leo** [comment]
@quilsmage Try hc or just allow hardcoded subs

**Comment by galli-leo** [comment]
Orbetter try generic

**Comment by pbrink231** [comment]
I see you added this as an option to the indexer.

Here is my scenario.  I would like to be able to do these settings in the Profiles.  toggle for allow HC.  I would also like to have a label (Category) gets used for the Download Client over what is set (this second part might need its own issue #).

Option 2 - have the profile have an option to use a specific indexer.  That way you can have the HC allowed in the indexer.  Still need to figure out the label for download client.

That way I can set a profile that allows HC and keeps track of these through the process.  I will most likely want to get a better quality in the future.  These usually can be bad quality.

**Comment by galli-leo** [comment]
@pbrink231 Can you open a new feature request for that and also post it to feathub?

**Comment by pbrink231** [comment]
new issue labelled feature request? yes

what is feathub?

**Comment by galli-leo** [comment]
@pbrink231 [feathub.com/Radarr/Radarr](feathub.com/Radarr/Radarr)

**Comment by pbrink231** [comment]
done [http://feathub.com/Radarr/Radarr/+179](url)
