### ISSUE TITLE
List subtitles in api?

### ISSUE THREAD

**Issue by Dr0bac** [Radarr/Radarr#5405]
Is it possible to list susbtitle files in radarr api? I can see these files in radarr web-ui
![Untitled](https://user-images.githubusercontent.com/43797966/100275743-b54cb080-2f60-11eb-9830-7fdd3a5b72fb.png)

But when i go to `http://192.168.1.12:7878/api/v3/movie?apikey=xxxxxxx`
subtitle section for all movies are empty.

````
      "mediaInfo": {
        "audioAdditionalFeatures": "LC",
        "audioBitrate": 224000,
        "audioChannels": 5.1,
        "audioCodec": "AAC",
        "audioLanguages": "English",
        "audioStreamCount": 1,
        "videoBitDepth": 8,
        "videoBitrate": 2500000,
        "videoCodec": "x264",
        "videoFps": 23.976,
        "resolution": "1920x1036",
        "runTime": "1:35:23",
        "scanType": "Progressive",
        "subtitles": ""
````

**Comment by Qstick** [comment]
Those are MI subtitles from the moviefile info... 

You want to use
`http://192.168.1.12:7878/api/v3/extrafile?movieId=xx&apikey=xxxxxxx`

**Comment by stumpylog** [comment]
I stumbled on this from some Googling, and that endpoint does work, but it isn't documented at https://radarr.video/docs/api/.  It would be great to see it documented at some point.

**Comment by austinwbest** [comment]
Feel free to pitch in and add some documentation to it :) we won't object to the help. Just follow the same structure that is currently there
