### ISSUE TITLE
Wrong indexer url encoding 

### ISSUE THREAD

**Issue by MGlants** [Radarr/Radarr#5413]
Hello guys, there is a problem with encodings when using jackett and Multilanguage Indexer

jackett.default.svc.cluster.local:9117/api/v2.0/indexers/noname-club/results/torznab/api?t=movie&cat=100227,100659,100661,100882,100884,100885,100909,100912,100954&extended=1&apikey=(removed)&offset=0&limit=100&q=**Kitoboy 2020**: 200.OK (156 ms)

jackett.default.svc.cluster.local:9117/api/v2.0/indexers/noname-club/results/torznab/api?t=movie&cat=100227,100659,100661,100882,100884,100885,100909,100912,100954&extended=1&apikey=(removed)&offset=0&limit=100&q=**ÐšÐ¸Ñ‚Ð¾Ð±Ð¾Ð**¸ 2020: 200.OK (142 ms)

**Comment by ta264** [comment]
Fill in the bug template and we can think about taking a look
