### ISSUE TITLE
Adding movie as monitored - its not monitored

### ISSUE THREAD

**Issue by reloxx13** [Radarr/Radarr#5414]
**Describe the bug**
If you have another UI language set (in my case german) manual searched and imported movies are not set to monitored, but monitored selectbox was selected.

Its caused by the default value, which shows it is selected, but in real the selectbox has not value.
If there would be a default "please select" with value none, this would be shown as firt unselected.   

Maybe its a check on yes/no which is ja/nein in german, that why the default value is not set correctly and it shows the first option but unselected.
Or is yes/no saved in localstorage config?

The preselect does not work.

If you switch it off and on while adding, it will be saved as monitored yes.

**To Reproduce**
- Change you UI language   
- Search for a movie you dont have in your library   
- Click add   
- Default is "monitored yes", dont change this   
- Check the added movie, it should be monitored
 

**Platform Information (please complete the following information):**
 - OS: Win10x64 Up2date
 - Docker: []
 - Mono or.NET Core Version: Yes (3.1.10)
 - Browser and Version FF 84.0 x64
 - Radarr Version 3.0.0.4192
 - Radarr Branch [nightly]
- DB Migration 188

**Comment by bakerboy448** [comment]
Reproduced on my prod instance using English

appears related to the translate updates, but those didn't change the keys just the labels.... 🤔 

Per discussion w/ austin, need to take a look at the default values

**Comment by Qstick** [comment]
The default is ‘true’ which matches one of the keys, it’s possible that’s being over set by value set, or it was set wrong on the bad update... is this a one time after it’s toggled, or does it happen again on the next movie?

**Comment by bakerboy448** [comment]
appears to be fixed after it's toggled.

added 1 movie, toogled
added another move, no need to toggle

**Comment by bakerboy448** [comment]
@reloxx13 you should be good going forward after toggling it once.  Can you test and confirmed?

After discussing with @Qstick , it is more than likely due to adding a movie when on the bad reverted build that changed monitored to a checkbox which busted the default.  In theory, very few people should be affected....if we get a lot of complaints on it we can force something.

My quick testing indicated toggling it once should solve it going forward.

**Comment by reloxx13** [comment]
> 
> 
> appears to be fixed after it's toggled.
> 
> added 1 movie, toogled
> added another move, no need to toggle

i tried it a few times and alot of variations and it never worked, right now it worked -_-
ill come back if it appears agian
