### ISSUE TITLE
NZBndx Indexer works in Sonarr but not in Radarr

### ISSUE THREAD

**Issue by scope999** [Radarr/Radarr#542]
Hi Guys awesome project!!! I have a problem with indexer nzbndx not working. It does work in Sonarr.

Here is a link to the site: https://www.nzbndx.com/

I have contacted the admins.

**Comment by Recluse66** [comment]
What you told me in the email, vs what you posted here, is a little different.  Please explain exactly what is not working and I will do what I can from my end on the nzbndx site.

What you told me in the email:  "It is not accepting NZBNDX as an indexer while Sonarr does."

So, if you could be specific as to what is not working in Radarr maybe they (radarr team) or I could be of some assistance.

**Comment by onedr0p** [comment]
@Recluse66

See my post here:

https://github.com/Radarr/Radarr/issues/4#issuecomment-272230066

**Comment by scope999** [comment]
Thanks for your quick attention Recluse, I appreciate it.
