### ISSUE TITLE
Manual search results are sometimes wrong

### ISSUE THREAD

**Issue by cgarnier** [Radarr/Radarr#5420]
Hi,
Sometimes, when i click on the manual search tabs, the result is a list of random movies. I have to click again the tab several times to finaly get a correct result with the movie i m looking for.
Sometimes, the  some torrents are missing. After some retries, they appears.
I m using 2 torrents indexers. The torznab is provided by jackett.

Version
0.2.0.1504

**Comment by ta264** [comment]
Closing unless you can replicate in v3

**Comment by cgarnier** [comment]
Where is the v3 ? cant find the tag.

**Comment by austinwbest** [comment]
nightly
