### ISSUE TITLE
Radarr V3 Queue API return something but nothing's really downloading

### ISSUE THREAD

**Issue by D4lvi** [Radarr/Radarr#5421]
Radarr V3 Queue API return what is on the download client includind what is not radarr movie

![image](https://user-images.githubusercontent.com/26835772/100539063-e1538480-3233-11eb-9176-e09793224bd8.png)

![image](https://user-images.githubusercontent.com/26835772/100539068-eadcec80-3233-11eb-8b7e-555ffb135680.png)

Maybe this is a bug or not, but this is a little annoying because some script I run detect if there is movie downloading by checking the size of the json response.

In radarr 2, when nothing was downloading, the API response was: [ ]

**Comment by austinwbest** [comment]
Click options on the activity page and turn on show unknown. Please use discord for support.
