### ISSUE TITLE
Behavior of the Missing filter changed in the Movies list

### ISSUE THREAD

**Issue by Mannekino** [Radarr/Radarr#5422]
**Problem**
I upgraded to Radarr 3.x today and when I apply the Missing filter in the movies overview it no longer shows any Movies. Under Radarr 2.x it would show all the movies that were not on my storage. I also tested putting a single movie in Monitored status and then that single movie would show up with the Missing filter.

**To Reproduce**
1. Go to Movies tab in the left menu
2. Click on Filter top right
3. Click on Missing

**Expected behavior**
I would expect the same behavior under 2.x where it would simply show all the movies I currently don't have downloaded.

**Platform Information (please complete the following information):**
 - OS: FreeNAS-11.3-U5
 - Jail version: 11.4-RELEASE-p4
 - Docker: No
 - Mono or.NET Core Version: 5.10.1.57
 - Radarr Version: 3.0.0.4204

**Comment by bakerboy448** [comment]
Missing and Wanted do not show Unmonitored movies; that is intentional.

Create a custom filter for size on disk =0 to cover your needs
