### ISSUE TITLE
Add watched filter option to Trakt list sync on Additional Parameters

### ISSUE THREAD

**Issue by goodhuntergood** [Radarr/Radarr#5423]
**Feature request**
I would love to have a subset of a trakt list be synced with Radarr. In my case, I would want to filter out the already watched movies from a trakt list. By doing this, I don't collect a movie I have already seen and probably won't see again anyway.

On the trakt website there is a filtering option to hide watched movies in your history. 
![image](https://user-images.githubusercontent.com/75206426/100541550-fb499300-3244-11eb-8d6a-b6617571277c.png)

It then adds the following statement to the URL
![image](https://user-images.githubusercontent.com/75206426/100541577-2a600480-3245-11eb-8090-500e39b62fc5.png)

**Issue description**
I have tried setting "?hide=watched" to the additional parameters in the radarr set-up, unfortunately to no avail. I suspect that field is meant for the premium filter options of trakt, this is the basic filtering of lists. It might not plug in the same way, I don't know.

![image](https://user-images.githubusercontent.com/75206426/100541638-89be1480-3245-11eb-9fe1-af6faf4c2c85.png)

Alternatively, I tried adding the statement line to the list field, as in the URL it comes consecutively. 

**Describe the solution you'd like**
Have a field to add the filtering statement

**Comment by Qstick** [comment]
Additional Parameters supported are jus the ones supported by Trakt here (https://trakt.docs.apiary.io/#introduction/filters). You'd have to be capable of doing this via the API call that we make, which it appears is not possible. Get them to add it to the API and we can support it.
