### ISSUE TITLE
tmdb changed title from movie to miniseries

### ISSUE THREAD

**Issue by motrous** [Radarr/Radarr#5425]
Sorry if an issue like this has already been submitted. I tried looking for one.

Radarr presented an error that Dr Horrible's Sing-A-Long Blog was removed from tmdb. The original number that Radarr linked to doesn't exist anymore but Dr Horrible is still on tmdb. I don't have access to the original tmdb page but the new one lists it as a tv miniseries and so I suspect the original one listed it as a movie and that's the issue.

I would like to keep it as a movie. It was released in four 15-minute episodes as a web show, sure, but the file I have is a single file, it's edited down like a movie, and I've had it under movies for forever. Is there a way to circumvent this or am I just out of luck?

Thanks.

**Comment by bakerboy448** [comment]
SOL
Blame TMDb and likely just use sonarr instead, but indicate your file has all 4 episodes

**Comment by motrous** [comment]
Thanks for the quick response! And sorry this was the wrong spot to ask that question.

**Comment by austinwbest** [comment]
You're good bud, we just try to keep support to a minimum on github so the answers are usually quick and short with info to hop on discord :)
