### ISSUE TITLE
.Net-core version won't start

### ISSUE THREAD

**Issue by matmuilwijk** [Radarr/Radarr#5437]
**Describe the bug**
On finalizing the upgrade to the .Net-core version, it won't start on Ubuntu 20.04. .Net-core is installed, radarr.service-file has been edited according to the guidelines on servarr, and logs show nothing, not even an attempt to start up. Status just says Exited, status = 203.

**To Reproduce**
Steps follow from here: https://wiki.servarr.com/Radarr_System#update-to-net-core-version

**Expected behavior**
I expected Radarr to start up normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/20720945/100617718-31594680-331b-11eb-8dac-5c0992ee903e.png)

**Platform Information (please complete the following information):**
 - OS: Ubuntu 20.04 Lts
 - Docker: No
 - Mono or.NET Core Version: .Net-core 3.1 (subversion unknown, just updated to latest)
 - Browser and Version [e.g. chrome 86.0.4240.198] (Only needed for UI issues)
 - Radarr Version 3.0.0.4204
 - Radarr Branch Link from above, so no branch chosen yet.

**Trace Logs**
Turn on Trace logs under Settings -> General and wait for the bug to occur again. **Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**

Logs are empty, only show logs from mono-run

**Comment by ta264** [comment]
https://wiki.servarr.com/Radarr_System#update-to-net-core-version

See discord if you need further assistance

**Comment by maxengel** [comment]
In case this comes up for anyone else, I had the same issue on Ubuntu, and the problem was that somehow the link on the wiki redirected me to download `Radarr.master.3.0.0.4204.linux.tar.gz` instead of `Radarr.master.3.0.0.4204.linux-core-arm64.tar.gz`.

Once I had the proper file everything worked per the instructions on the wiki.

**Comment by bakerboy448** [comment]
Just checked; all 3 links on the wiki are good

if you used wget or the console to DL, ensure the URL is quoted
