### ISSUE TITLE
Add Original Movie Language to UI views

### ISSUE THREAD

**Issue by ditmarvisser** [Radarr/Radarr#5438]
**Is your feature request related to a problem? Please describe.**
With Tdarr we can remove unwanted language audio tracks from files. You can only configure it to remove certain languages, or keep certain languages. But there is no way to only keep the Original Movie Language, since that information is not available.

**Describe the solution you'd like**
Store the Original Movie Language to the local movie entry, so the Radarr API can be called from within Tdarr to filter the audio tracks.

**Describe alternatives you've considered**
You could also make an API call to TMBD, however you would then have to parse all those results. It's also better to limit calling external APIs and keep everything in the local machine.

**Additional context**
Semi-related to #4058

[AB#755](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/755)

**Comment by bakerboy448** [comment]
The linked issue you provided seems to indicate we already store the original language?

I’m not sure what exactly you’re asking?

**Comment by ditmarvisser** [comment]
It is nowhere to be found in the API schemas. In the linked issue it was probably talking about #3082, which as far as I can tell was not implemented.

**Comment by Qstick** [comment]
We do store it already, it's just not exposed to the API currently.

**Comment by ditmarvisser** [comment]
If it could be exposed to API calls then this FR can be closed. Thanks!

**Comment by pjaclark** [comment]
Exposing it to the view filters would also be a great idea. I store my movies by language, so finding (for example) all Non-English movies under the English Movies root would be brilliant!

**Comment by Qstick** [comment]
Yep, that is the plan @pjaclark. It'll be added to Movie Index Table Columns/Sort/Filters and same with Discover

**Comment by ditmarvisser** [comment]
Any update on this?

**Comment by discotimetraveler** [comment]
I am also looking for this feature. Thanks

**Comment by LoaneShark** [comment]
+1

**Comment by kingmotley** [comment]
+1

**Comment by bakerboy448** [comment]
> +1

Already implemented 

And for future reference a simple +1 via a 👍 on the OP would suffice :)
