### ISSUE TITLE
[Lists] IMDB Currrently Popular

### ISSUE THREAD

**Issue by simonk83** [Radarr/Radarr#544]
Any way to have the following added as a list?

http://www.imdb.com/search/title?count=100&title_type=feature,tv_series?ref_=nv_wl_img_2

Basically some sort of aggregate of popular films on IMDB.  I'd probably use that a lot.

**Comment by onedr0p** [comment]
We're looking into rays to add that, right now the only way is to scrape the IMDb website which I'm not thrilled about.

**Comment by onedr0p** [comment]
We could use themoviedb to get movies in theaters, upcoming and popular movies do you feel that would be good enough?

https://www.themoviedb.org/movie?language=en
https://www.themoviedb.org/movie/upcoming?language=en
https://www.themoviedb.org/movie/now-playing

**Comment by simonk83** [comment]
I think so yep, it's really just an easyish way to add popular upcoming movies so I think that'll work fine :)

That upcoming list looks especially handy, but all three would be great 👍

**Comment by suineg** [comment]
TMDB has a much easier API to work with than IMDB.

**Comment by simonk83** [comment]
Well it has one at all :D . One that doesn't require thousands of dollars at least ;)

**Comment by emko** [comment]
for me basically anything would work just would need a way to filter out genres i don't like and add a min rating to not add bad movies.

**Comment by simonk83** [comment]
> for me basically anything would work just would need a way to filter out genres i don't like and add a min rating to not add bad movies.

Just don't enable auto import.  I prefer control over what's added personally so I'll just check the list every couple of weeks and add anything new I fancy.

**Comment by fedoranimus** [comment]
Is this meaningfully different from the StevenLu's list?

**Comment by onedr0p** [comment]
Yea, Steven lu doesn't have upcoming release.

**Comment by mikelagase** [comment]
For me, http://www.imdb.com/chart/top?ref_=nv_mv_250_6 would be better to pull in as it has movies rated 8.0 and higher and if implemented like Couch Potato where you can select this, it would weed out all of the junk movies. I suppose I could just use Couchpotato for this now and then sync the two.

**Comment by untotren** [comment]
Yeah, I was pretty disappointed this wasn't available, CP has been doing it for years.

**Comment by galli-leo** [comment]
@mikelagase @untotren You can achieve pretty much the same with the TMDB lists, if you configure them correctly.
