### ISSUE TITLE
Radarr not removing Completed Downloads in qBittorrent

### ISSUE THREAD

**Issue by Fyb3roptik** [Radarr/Radarr#5440]
**Describe the bug**
When a movie is done downloading with qbittorrent, Radarr removes it from its own queue but never removes the download from qbittorrent. I was told to change qbittorrent to "Paused" and then uncheck the seed options. This seemed to work for a while, but now it is doing it again.

**Expected behavior**
Clear completed download from qbittorrent

**Platform Information (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Docker: No
 - Mono or.NET Core Version: .Net Core 3.1.10
 - Radarr Version 3.0.0.4203
 - Radarr Branch develop
- qBittorrent Version: 4.3.0.1

**Trace Logs**
There is nothing in the logs or any errors of any kind

**Comment by ta264** [comment]
Without trace logs nothing is going to happen.  Post a big bunch and we can take a look.

**Comment by Fyb3roptik** [comment]
I will have to keep an eye on this. Looks like most are working as expected. I will close this for now and will create a new one if I catch it in the act
