### ISSUE TITLE
Filter by lists in the main page

### ISSUE THREAD

**Issue by azumukupoe** [Radarr/Radarr#5445]
**Is your feature request related to a problem? Please describe.**
After updating to v3, I found out that filtering by lists have become a thing in "Discover." Would it be possible to add the same thing to the main page?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/31339007/100661136-58089300-3396-11eb-9b37-ca70d5ef608f.png)

**Comment by bakerboy448** [comment]
I don't think we have plans for this; use tags on your lists.

Q/Nit/Ta will correct me and reopen if needed.

**Comment by azumukupoe** [comment]
> use tags on your lists

Will the tags be added to movies already in the library, or just to newly added ones?

**Comment by bakerboy448** [comment]
> Will the tags be added to movies already in the library, or just to newly added ones?

just newly added ones...there is some mild discussion about changing that, but unlikely.


also 
Duplicate of #4333
Duplicate of #5249

**Comment by azumukupoe** [comment]
Well, the lists filter in "Discover" is exactly what I wanted to use in the main page...
