### ISSUE TITLE
Update to version 3.0.0.4204 broken

### ISSUE THREAD

**Issue by vkotheka** [Radarr/Radarr#5446]
**Describe the bug**

The application UI not visible after updating to latest version.

**To Reproduce**
Tried updating both ways:
1. Updating from the Radarr UI
2. By creating a container using :latest tag

**Expected behavior**
When I enter http://hostname:port - the Radarr UI should show up (my set-up was Authentication Off so no login screen)

**Screenshots**

**Platform Information (please complete the following information):**
 - OS: Raspberry Pi 4B
 - Docker: Yes
 - Mono or.NET Core Version: [e.g. Mono 5.8 or .Net Core 3.1.10] (found under System -> Status)
 - Browser and Version [e.g. chrome 86.0.4240.198] Firefox 83.0 & Safari 14.0.1
 - Radarr Version [e.g. 3.0.0.2956] 3.0.0.4204 (latest)
 - Radarr Branch [e.g. master]

**Trace Logs**
Turn on Trace logs under Settings -> General and wait for the bug to occur again. **Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**

**Comment by bakerboy448** [comment]
NEVER EVER EVER update docker applications through the application; you're supposed to repull the container

for it not working, my guess is you're using raspbian
![image](https://user-images.githubusercontent.com/55419169/100678475-de8b8900-3332-11eb-8d6c-ee3e1e4053c5.png)

**Comment by vkotheka** [comment]
Thanks bakerboy448. I will keep in mind to "never update using UI" and will use docker pull latest. I am using raspbian and on the same device my sonarr, bazarr and other docker containers are running. In fact, Radarr was running just fine before I upgraded to latest. What do you suggest I do now?

**Comment by vkotheka** [comment]
This is what I have on my raspi.
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

**Comment by bakerboy448** [comment]
suggestions in the image of my comment.

**Comment by bakerboy448** [comment]
https://wiki.servarr.com/Radarr_FAQ#I-am-using-a-Pi-and-Raspbian-and-Radarr-will-not-launch

for posterity

if you find an alt solution, we're all ears

**Comment by vkotheka** [comment]
Thanks bakerboy448. I will surely update the wiki page / this ticket if I find the solution.

Running docker with privileged mode works fine and I can see Radarr starting and working.

I am wondering what has changed / added in new version of Radarr that's causing it to fail on Raspbian now.

**Comment by bakerboy448** [comment]
we use dotnet core now

**Comment by vkotheka** [comment]
Can't figure out the issue - just tried running a [.net core container](https://www.hanselman.com/blog/building-running-and-testing-net-core-and-aspnet-core-21-in-docker-on-a-raspberry-pi-arm32) on my raspbian and it works fine. In the above comment there is mention of v3. Is that .net core v3?

**Comment by bakerboy448** [comment]
v3 = radarr v3
which killed radarr v0.2 this weekend

**Comment by vkotheka** [comment]
> we use dotnet core now

So wondering if I can run a sample .net core container on my rasp then why Radarr is failing.

**Comment by vkotheka** [comment]
I think I may have found something that might work
https://edi.wang/post/2019/9/29/setup-net-core-30-runtime-and-sdk-on-raspberry-pi-4

**Comment by vkotheka** [comment]
Negative - that doesn't work. 

It's quite challenging - I am trying to solve an unknown / not so well understood problem.

**Comment by ta264** [comment]
The issue is well known. Raspbian has a version of libseccomp2 that is too old to support running a docker container based on Ubuntu 20.04, which both hotio and Linuxserver use as their base for v3. You either need to use `--privileged`, update libseccomp2 from Ubuntu or get a better OS (I recommend Ubuntu 20.04 arm64)

**Comment by vkotheka** [comment]
Managed to fix the issue by installing the backport from debian repo.
Generally not recommended to use back ports  in blanket upgrade mode. 
I read installation of a single package may be ok but may also cause issues. So got to understand what you are doing.

Steps to fix:
First ensure you are running Raspbian buster e.g using `lsb_release -a`

Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	**buster**

If you are using buster:

```
Add the line `deb http://deb.debian.org/debian buster-backports` main to `/etc/apt/sources.list`
Run apt-get update
apt-get -t buster-backports install libseccomp2

```

Restart Radarr

**Comment by vkotheka** [comment]
Thanks ta264 & bakerboy448 for your help.
