### ISSUE TITLE
Add Sanity Check for Recycling Bin

### ISSUE THREAD

**Issue by bakerboy448** [Radarr/Radarr#5447]
Users should not be able to set the recycling bin to the path of the root folder or any of the root folder parent folders

**Comment by bakerboy448** [comment]
Taloth had similar comments on the Sonarr issue

> "Please can I shoot myself in the foot? "
> Should we protect against C: , C:\Windows, C:\Users, w/e as well?
> 
> I'm fine with adding the root folder guard, but sometimes people just gotta feel the consequences.

**Comment by fryfrog** [comment]
I think a *bare minimum* sanity check is reasonable. There should not be root folders *inside* the recycle bin.
