### ISSUE TITLE
Where did Growl support go?

### ISSUE THREAD

**Issue by LeeThompson** [Radarr/Radarr#5449]
**Describe the bug**
The growl connect option is no longer present.

**To Reproduce**
1. Click on Settings
2. Click on Connections
3. Click on the plus

**Expected behavior**
I expected growl to be in the list; it's still listed in the wiki.

**Platform Information (please complete the following information):**
 - OS: Debian
 - Docker: Yes
 - Whatever version is in the container.
 - Whatever version is in the container.
 - master

**Comment by ta264** [comment]
It was removed because it is not supported in net core

**Comment by LeeThompson** [comment]
Well if it's been removed from the core I guess that's it.

**Comment by austinwbest** [comment]
That is correct, you'll have to utilize one of the many other options.
