### ISSUE TITLE
Question: API command to scan drone factory?

### ISSUE THREAD

**Issue by Crowley007** [Radarr/Radarr#545]
Is there an API command to scan drone factory folder? With Sonarr I use this powerhsell script:

`$url = "http://localhost:8989/api/command"
$json = "{ ""name"": "**"downloadedepisodesscan**"" }"

Write-Host "Publishing update $version ($branch) to: $url"
Invoke-RestMethod -Uri $url -Method Post -Body $json -Headers @{"X-Api-Key"="******************"}
`

Manual scan works fine. So what is the correct parameter with Radarr?

**Comment by galli-leo** [comment]
Should be still the same in Radarr.

**Comment by Crowley007** [comment]
I tested it, and the same command does not scan drone factory folder.
