### ISSUE TITLE
Switch Studio and Release Dates in Movie Summuary

### ISSUE THREAD

**Issue by ToXinE** [Radarr/Radarr#5452]
**Is your feature request related to a problem? Please describe.**
At first i was really disapointed that V3 radar suppress the information of the release dates but I've accidentally discovered that I had to hover the year to display it... 
I'm really upset when I need to hover the year to see the releases dates (as i always use this information to determine if i need to refresh or manually search the movie).

**Describe the solution you'd like**
I don't think someone need to know asap the Studio of the movie but i need to know asap the releases dates. Let's switch them !

![iZ4deN5](https://user-images.githubusercontent.com/6205053/100728243-99656680-33c7-11eb-93db-5756de87b36c.png)

**Describe alternatives you've considered**
you can add release dates after "Studio" if you don't want to hide "Studio" but I don't want to do anything more than browsing to movie detail to see released dates.

**Comment by ta264** [comment]
Radarr handles refreshing automatically.  If you're looking at the dates to determine if you need to search you're doing it wrong - leave running and it will pick up the release when it becomes available

**Comment by austinwbest** [comment]
Based on your settings, that column right in the middle there will tell you and you dont need to look at dates. The one labeled Status and shows **Missing**

**Comment by Qstick** [comment]
Additionally all of these dates are available on index

**Comment by ToXinE** [comment]
I'm perfectly aware of the status of this movie because I've applied a filter on the movie list : 
I need those dates because there is no way to apply a filter like the one i want : 
- Missing 
- and monitored
- and (physical release date <= today OR digitally release date <= today)

With my profile "Any(but remux", I sometimes miss some movies that are excluded from this profile so i need to manually search for them (and i don't want remux for all movies, only best one i choose)

Do I misuse radarr ?
