### ISSUE TITLE
Files can't be imported from completed download folder

### ISSUE THREAD

**Issue by ToXinE** [Radarr/Radarr#5453]
**Describe the bug**
I've manually searched for Dirty  Computer (2018) and sent it to sabnzbdplus with radarrV3. Download went fine but nothing gets imported when finished (don't know why but maybe it's because the file downloaded is not quite the same (see attached gif).

I tried to manually import the file but something is wrong and the checkbox still grayed out.

**To Reproduce**
1. Go to 'movie > Import'
2. Click on the folder you want to import files from
3. select the movie not matching and type the corresponding movie
4. checkbox is still grayed out.

![radarr_import_bug](https://user-images.githubusercontent.com/6205053/100732839-9ec5af80-33cd-11eb-96fc-a1eb5aa59afd.gif)

**Expected behavior**
the checkbox is enabled and i can import it

![2020-12-01 11_47_34-Dirty Computer - Radarr](https://user-images.githubusercontent.com/6205053/100733291-40e59780-33ce-11eb-87d5-0008f414fdd1.png)
![2020-12-01 11_51_08-Download Client Settings - Radarr](https://user-images.githubusercontent.com/6205053/100733301-4347f180-33ce-11eb-90f8-4691caa94d4c.png)

**Platform Information (please complete the following information):**
 - OS: [Ubuntu 20.10]
 - Docker: [No]
 - Mono or.NET Core Version: [Mono 6.12.0.90] 
 - Browser and Version [FF 83.0]
 - Radarr Version [3.0.0.4204]
 - Radarr Branch [develop]

**Trace Logs**
[radarr.txt](https://github.com/Radarr/Radarr/files/5622104/radarr.txt)

**Comment by bakerboy448** [comment]
You're using the wrong import; that is the add organized movies you have import.

You want MANUAL IMPORT

**Comment by ToXinE** [comment]
oh, my bad 😊
