### ISSUE TITLE
v3 Search Results cropped on Narrow Desktops 

### ISSUE THREAD

**Issue by Cessquill** [Radarr/Radarr#5456]
For visibility, touchscreen laptop is set to display things a little larger than normal.  The search results table in v3 overflow off the right of display.  There is a scroll bar, but it's at the end of the results.  As it's a touchscreen I can drag to scroll the table, but when I get to the last column Radarr automatically loads the next movie.

Note, this is fine on mobile displays - the table is formatted differently.

**To Reproduce**
1. Go to any movie in collection
2. Set the browser width to anything less than about 1500px
3. Click on the "Search" tab and wait for results to load
4. All columns are not visible (including possible the most important column), and the only way to get there is go to the end of the list, scroll over, then back up (which is difficult, since you can't always match up the record you were looking at)

**Expected behavior**
Either the table reformats to fit the width of the display, or horizontal scroll bars are visible all the time.
Maybe not load the previous/next movie when swiping left/right?

**Platform Information (please complete the following information):**
 - OS: Unraid 6.8.3 (not sure of underlying O/S)
 - Docker: Yes
 - Mono or.NET Core Version: .NET Core (3.1.10)
 - Browser and Version: Chrome 86.0.4240.198
 - Radarr Version: 3.0.0.4204
 - Radarr Branch: master

**Trace Logs**
[radarr.trace.txt](https://github.com/Radarr/Radarr/files/5624686/radarr.trace.txt)

**Comment by bakerboy448** [comment]
@austinwbest  thoughts?

That jumping to the next movie is something that occurs on my end as well

**Comment by austinwbest** [comment]
It should, yes. 

Swiping is expected to happen on mobile devices (emulates the arrows onclick at the top & the keyboard arrows)

**Comment by bakerboy448** [comment]
Closing; dupe as per prior comment
