### ISSUE TITLE
Remote Path Mapping: using default qbittorrent save path, not category

### ISSUE THREAD

**Issue by erri120** [Radarr/Radarr#5457]
**Describe the bug**
`Remote download client qBittorrent places downloads in M:\Libraries\downloads\torrents\ but this is not a valid ubuntu path. Review your remote path mappings and download client settings.`

I'm running a Radarr Docker Container on a Windows machine. The download client also runs on the host machine. The download client will download Radarr related stuff to `M:\Libraries\downloads\torrents\radarr\` which is mapped to `/data/downloads/torrents/radarr` (Volume for the docker container is `m:/Libraries:/data`).

This problem **does not** happen with Sonarr:
![firefox_XDhlpuysa5](https://user-images.githubusercontent.com/16577545/100781312-c3884a00-3402-11eb-9b0c-58464b58b5ec.png)
but **does happen** with Lidarr as well:
![firefox_yDItI3E6q0](https://user-images.githubusercontent.com/16577545/100781360-d3079300-3402-11eb-9db6-fb5a0a1ae3c6.png)

**Possible Solution**
On my journey through this codebase I found a very interesting line in [`NzbDrone.Common.Extensions.PathExtensions.IsPathValid`](https://github.com/Radarr/Radarr/blob/34111509a949d71aba2bc27fe666e60f4e121921/src/NzbDrone.Common/Extensions/PathExtensions.cs#L148):
```csharp
if (OsInfo.IsNotWindows)
{
    return path.StartsWith(Path.DirectorySeparatorChar.ToString());
}
```
This gets called in [`NzbDrone.Core.HealthCheck.Checks.RemotePathMappingCheck`](https://github.com/Radarr/Radarr/blob/34111509a949d71aba2bc27fe666e60f4e121921/src/NzbDrone.Core/HealthCheck/Checks/RemotePathMappingCheck.cs#L68), a Health Check that doesn't exist in Sonarr. Sonarr doesn't have a _fix_ to this exact problem because it doesn't even have the check for it. 

What should be changed? I've only forked the repo like 5min ago but I suggest using [`NzbDrone.Core.RemotePathMappings.RemotePathMappingService.ValidateMapping`](https://github.com/Radarr/Radarr/blob/master/src/NzbDrone.Core/RemotePathMappings/RemotePathMappingService.cs#L92) or something similar which doesn't use the `IsValidPath()` Extension.

**Screenshots**
![firefox_VMVYD4MoJt](https://user-images.githubusercontent.com/16577545/100780232-6213ab80-3401-11eb-9f80-197820f93b8e.png)

**Platform Information (please complete the following information):**
 - Host OS: Windows 10
 - Docker: Yes (`hotio/radarr:nightly`)
 - Mono or.NET Core Version: .NET Core 3.1.10
 - Radarr Version 3.0.0.4203
 - Radarr Branch nightly

**Trace Logs**

(logs where captured when I removed and re-added the remote path mapping)

```log
2020-12-1 19:09:30.0|Trace|Http|Req: 340 [GET] /api/v3/downloadclient (from ::ffff:172.18.0.1 Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0)
2020-12-1 19:09:30.0|Trace|Http|Req: 341 [GET] /api/v3/remotepathmapping (from ::ffff:172.18.0.1 Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0)
2020-12-1 19:09:30.0|Trace|Http|Req: 342 [GET] /api/v3/config/downloadclient (from ::ffff:172.18.0.1 Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0)
2020-12-1 19:09:30.1|Trace|ConfigService|Using default config value for 'downloadclientworkingfolders' defaultValue:'_UNPACK_|_FAILED_'
2020-12-1 19:09:30.1|Trace|ConfigService|Using default config value for 'enablecompleteddownloadhandling' defaultValue:'True'
2020-12-1 19:09:30.1|Trace|ConfigService|Using default config value for 'checkforfinisheddownloadinterval' defaultValue:'1'
2020-12-1 19:09:30.1|Trace|ConfigService|Using default config value for 'autoredownloadfailed' defaultValue:'True'
2020-12-1 19:09:30.1|Trace|ConfigService|Using default config value for 'removefaileddownloads' defaultValue:'True'
2020-12-1 19:09:30.1|Trace|Http|Res: 340 [GET] /api/v3/downloadclient: 200.OK (13 ms)
2020-12-1 19:09:30.1|Debug|Api|[GET] /api/v3/downloadclient: 200.OK (13 ms)
2020-12-1 19:09:30.1|Trace|Http|Res: 341 [GET] /api/v3/remotepathmapping: 200.OK (10 ms)
2020-12-1 19:09:30.1|Trace|Http|Res: 342 [GET] /api/v3/config/downloadclient: 200.OK (11 ms)
2020-12-1 19:09:30.1|Debug|Api|[GET] /api/v3/remotepathmapping: 200.OK (10 ms)
2020-12-1 19:09:30.1|Debug|Api|[GET] /api/v3/config/downloadclient: 200.OK (11 ms)
2020-12-1 19:09:35.2|Trace|Http|Req: 343 [DELETE] /api/v3/remotepathmapping/1 (from ::ffff:172.18.0.1 Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0)
2020-12-1 19:09:35.2|Trace|Http|Res: 343 [DELETE] /api/v3/remotepathmapping/1: 200.OK (22 ms)
2020-12-1 19:09:35.2|Debug|Api|[DELETE] /api/v3/remotepathmapping/1: 200.OK (22 ms)
2020-12-1 19:09:37.6|Trace|Http|Req: 344 [GET] /api/v3/filesystem?path=&allowFoldersWithoutTrailingSlashes=true&includeFiles=false (from ::ffff:172.18.0.1 Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0)
2020-12-1 19:09:37.7|Trace|Http|Res: 344 [GET] /api/v3/filesystem?path=&allowFoldersWithoutTrailingSlashes=true&includeFiles=false: 200.OK (19 ms)
2020-12-1 19:09:37.7|Debug|Api|[GET] /api/v3/filesystem?path=&allowFoldersWithoutTrailingSlashes=true&includeFiles=false: 200.OK (19 ms)
2020-12-1 19:09:38.6|Trace|Http|Req: 345 [GET] /api/v3/filesystem?path=%2Fdata%2F&allowFoldersWithoutTrailingSlashes=true&includeFiles=false (from ::ffff:172.18.0.1 Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0)
2020-12-1 19:09:38.6|Trace|Http|Res: 345 [GET] /api/v3/filesystem?path=%2Fdata%2F&allowFoldersWithoutTrailingSlashes=true&includeFiles=false: 200.OK (5 ms)
2020-12-1 19:09:38.6|Debug|Api|[GET] /api/v3/filesystem?path=%2Fdata%2F&allowFoldersWithoutTrailingSlashes=true&includeFiles=false: 200.OK (5 ms)
2020-12-1 19:09:39.7|Trace|Http|Req: 346 [GET] /api/v3/filesystem?path=%2Fdata%2Fdownloads%2F&allowFoldersWithoutTrailingSlashes=true&includeFiles=false (from ::ffff:172.18.0.1 Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0)
2020-12-1 19:09:39.7|Trace|Http|Res: 346 [GET] /api/v3/filesystem?path=%2Fdata%2Fdownloads%2F&allowFoldersWithoutTrailingSlashes=true&includeFiles=false: 200.OK (3 ms)
2020-12-1 19:09:39.7|Debug|Api|[GET] /api/v3/filesystem?path=%2Fdata%2Fdownloads%2F&allowFoldersWithoutTrailingSlashes=true&includeFiles=false: 200.OK (3 ms)
2020-12-1 19:09:40.1|Trace|Http|Req: 347 [GET] /api/v3/filesystem?path=%2Fdata%2Fdownloads%2Ftorrents%2F&allowFoldersWithoutTrailingSlashes=true&includeFiles=false (from ::ffff:172.18.0.1 Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0)
2020-12-1 19:09:40.1|Trace|Http|Res: 347 [GET] /api/v3/filesystem?path=%2Fdata%2Fdownloads%2Ftorrents%2F&allowFoldersWithoutTrailingSlashes=true&includeFiles=false: 200.OK (5 ms)
2020-12-1 19:09:40.1|Debug|Api|[GET] /api/v3/filesystem?path=%2Fdata%2Fdownloads%2Ftorrents%2F&allowFoldersWithoutTrailingSlashes=true&includeFiles=false: 200.OK (5 ms)
2020-12-1 19:09:40.8|Trace|Http|Req: 348 [GET] /api/v3/filesystem?path=%2Fdata%2Fdownloads%2Ftorrents%2Fradarr%2F&allowFoldersWithoutTrailingSlashes=true&includeFiles=false (from ::ffff:172.18.0.1 Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0)
2020-12-1 19:09:40.8|Trace|Http|Res: 348 [GET] /api/v3/filesystem?path=%2Fdata%2Fdownloads%2Ftorrents%2Fradarr%2F&allowFoldersWithoutTrailingSlashes=true&includeFiles=false: 200.OK (4 ms)
2020-12-1 19:09:40.8|Debug|Api|[GET] /api/v3/filesystem?path=%2Fdata%2Fdownloads%2Ftorrents%2Fradarr%2F&allowFoldersWithoutTrailingSlashes=true&includeFiles=false: 200.OK (4 ms)
2020-12-1 19:09:42.7|Trace|Http|Req: 349 [POST] /api/v3/remotepathmapping (from ::ffff:172.18.0.1 Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0)
2020-12-1 19:09:42.8|Trace|EventAggregator|Publishing ModelEvent<RemotePathMapping>
2020-12-1 19:09:42.8|Trace|ConfigService|Using default config value for 'enablecompleteddownloadhandling' defaultValue:'True'
2020-12-1 19:09:42.8|Trace|HttpClient|Req: [GET] http://REDACTED:9090/api/v2/app/preferences
2020-12-1 19:09:42.8|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
2020-12-1 19:09:42.8|Trace|Http|Res: 349 [POST] /api/v3/remotepathmapping: 201.Created (25 ms)
2020-12-1 19:09:42.8|Debug|Api|[POST] /api/v3/remotepathmapping: 201.Created (25 ms)
2020-12-1 19:09:42.8|Trace|HttpClient|Res: [GET] http://REDACTED:9090/api/v2/app/preferences: 200.OK (4 ms)
```

**Comment by bakerboy448** [comment]
Why are you running Docker on Windows and getting all the pain of docker with all the pain of windows combined with the headache of linux on windows?

@Qstick your health check...thoughts?

It is not in Sonarr because Sonarr has not added the health check to warn users (commonly) using stupid poorly config'd docker paths.

**Comment by ta264** [comment]
I'm going to label this as support, unless you can document that those windows paths are valid in a windows docker (which presents as Ubuntu)

**Comment by Qstick** [comment]
@bakerboy448, @ta264 is the author on this check FYI, he knows it better than I. The check isn't necessarily meant to only warn of "stupid poorly configured docker paths" but more of remote path mapping issues as well as possible permissions issues with Radarr seeing the presented download client save path.

**Comment by erri120** [comment]
Well, the thing is that this path is valid and that the remote path mapping works Sonarr was even able to hard link correctly.

**Comment by ta264** [comment]
If you want to get this fixed please join the discord channel and help me understand

**Comment by ta264** [comment]
The issue is that radarr is fetching the default `savePath` from the api for the health check, not the category `savePath`

**Comment by ta264** [comment]
If a category is set in radarr `GetStatus` needs to fetch `api/v2/torrents/categories` and use the save path set there
