### ISSUE TITLE
Radarr v3 on a Mac with latest linuxserver images + docker-machine: Epic Fail

### ISSUE THREAD

**Issue by xcambar** [Radarr/Radarr#5458]
**Describe the bug**
A fresh installation on MacOS (Mojave), using docker-compose (from Homebrew), does not start and raises an SQLite-related exception.

**To Reproduce**
1. Use MacOS Mojave (did not test with other version)
2. Create the `docker-compose.yml` below
3. `docker-compose up`

**Expected behavior**
The application starts.

**Screenshots**

```
# docker-compose.yml
---
version: '3'

services:
  # Movie Downloader
  radarr:
    image: ghcr.io/linuxserver/radarr:latest
    restart: unless-stopped
    environment:
      - PUID=0
      - PGID=0
      - UMASK=002
      - TZ=Europe/Berlin
    volumes:
      - ./config:/config
      - ../NAS/Movies:/movies
      - ../NAS/downloads/movies:/downloads
    ports:
      - "7878:7878"
```

**Platform Information (please complete the following information):**
 - OS: MacOS Mojave
 - Docker: Yes
 - Mono or.NET Core Version: As per linuxserver/radarr Docker image
 - Radarr Version: As per linuxserver/radarr Docker image (v3)
 - Radarr Branch [e.g. master]

**Trace Logs**

```
# 
# Logs of `docker-compose up`
# 

radarr_1  | [Info] Bootstrap: Starting Radarr - /app/radarr/bin/Radarr.dll - Version 3.0.0.4204
radarr_1  | [Info] AppFolderInfo: Data directory is being overridden to [/config]
radarr_1  | [Info] Router: Application mode: Interactive
radarr_1  | [Info] MigrationController: *** Migrating data source=/config/radarr.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
radarr_1  |
radarr_1  |
radarr_1  | [Fatal] ConsoleApp: EPIC FAIL!
radarr_1  |
radarr_1  | [v3.0.0.4204] NzbDrone.Core.Datastore.CorruptDatabaseException: Radarr failed to start: Database file: code = IoErr (10), message = System.Data.SQLite.SQLiteException (0x800007FF): disk I/O error
radarr_1  | disk I/O error

[...]
```

I have tried many configurations of PUID/PGID in the image, with zero success.
The only working configuration that works is when the `config` folder is *not* mounted in the container.
But then, I'll lose my config at the next update, so... :shrug: 

Thanks for your help! :pray:

**Comment by ta264** [comment]
Don't use docker on mac
