### ISSUE TITLE
Sorting by descending brings blank items to the top of the table

### ISSUE THREAD

**Issue by azumukupoe** [Radarr/Radarr#5460]
**Describe the bug**
After updating to v3, sorting by "In Cinemas" by descending brings blank items to the top of the table

**To Reproduce**

**Expected behavior**
Blank items to be at the bottom of the table

**Screenshots**
![image](https://user-images.githubusercontent.com/31339007/100831007-30095480-34a8-11eb-8f98-f32bacc8d5fa.png)

**Platform Information (please complete the following information):**
 - OS: Windows 10
 - Docker: Yes
 - Mono or.NET Core Version: .Net Core 3.1.10
 - Browser and Version: Firefox/83.0
 - Radarr Version: 3.0.0.4204
 - Radarr Branch: master

**Trace Logs**
UI issue

**Comment by bakerboy448** [comment]
not a bug;

descending would in fact logically place blank first as blank is last when ascending

**Comment by azumukupoe** [comment]
> not a bug;

Then, why didn't this happen in v2?
Should I make this a feature request?

**Comment by bakerboy448** [comment]
>Then, why didn't this happen in v2?

i'd likely argue it was a bug in v0.2 as it was not sorting properly then.

quick googling agrees the go to for descending in various other applications is in fact blank up top.

>Should I make this a feature request?

I don't foresee changing to an illogical sort.

**Comment by azumukupoe** [comment]
> quick googling agrees the go to for descending in various other applications is in fact blank up top.

vice versa
https://learnsql.com/blog/how-to-order-rows-with-nulls/

> illogical

but is it really useful?

**Comment by bakerboy448** [comment]
SQLite
>Unlike the above database types, SQLITE considers NULLs to be smaller than any other value. If you sort a column with NULL values in ascending order, the NULLs will come first.

from your link.

well there we have it.
