### ISSUE TITLE
V3 Renaming is not working

### ISSUE THREAD

**Issue by jokerigno** [Radarr/Radarr#5465]
**Describe the bug**
Hi, I switched to v3 and want to rename my folders and file on my local language. I followed this steps but both folder and name stays in english while the name in web ui is in my native language:
**To Reproduce**

1.Click on Movies
2.Click the Movie Editor button
3.Locate the movie(s)/folder(s) and check the tick boxes
4. Use the Root Folder dropdown to select the same root folder the movies are already in
5. Select Yes, Move the Files
6 Click the Rename Files button in the bottom right of the screen

**Expected behavior**
folders and file on my local language.

**Platform Information (please complete the following information):**
 - Docker: [Yes]
 - .NET Core (3.1.10)
 - Browser and Version chrome  87.0.4280.66
 - Radarr Version 3.0.0.4204
 - Radarr Branch master

**Trace Logs**
Turn on Trace logs under Settings -> General and wait for the bug to occur again. **Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**

**Comment by bakerboy448** [comment]
Support Requests -> [Reddit](https://www.reddit.com/r/radarr/) or [Discord](https://discord.gg/r5wJPt9)

I’d suggest checking your folder and file naming schemas and ensure you are telling radarr to use the non-English version
