### ISSUE TITLE
File Size Not Updating

### ISSUE THREAD

**Issue by sbazzle** [Radarr/Radarr#5468]
Once a movie file is added to Radarr, it'll display the size of the file on the movie's page.  However, if I re-encode the file to a smaller file size and do a "refresh and scan", the new file size does not get updated; it stills shows the original file size.  If I re-encode multiple movie files, the same result happens if I go to the main Movies list and click "update all".  There's no change to the original file sizes.

**Comment by Qstick** [comment]
Try again with the template
