### ISSUE TITLE
API command to scan drone factory folder fails

### ISSUE THREAD

**Issue by Crowley007** [Radarr/Radarr#547]
Continuation of https://github.com/Radarr/Radarr/issues/545

So, indeed the same command is actually recognized, but for some reason does not work, it does not find anything. Manual scan of the drone factory folder does, so there is something wrong here.

I get this in the log when I send the command `17-1-31 19:48:50.4|Debug|Api|[POST] /api/command: 201.Created (19 ms)
17-1-31 19:48:50.4|Debug|Parser|Parsing string '*********************.2016.EXTENDED.1080p.BluRay.H264.AAC-RARBG'
17-1-31 19:48:50.5|Debug|Parser|Episode Parsed. ******************************* - Season 01 
17-1-31 19:48:50.5|Debug|Parser|Language parsed: English
17-1-31 19:48:50.5|Debug|QualityParser|Trying to parse quality for *********************.2016.EXTENDED.1080p.BluRay.H264.AAC-RARBG
17-1-31 19:48:50.5|Debug|Parser|Quality parsed: Bluray-1080p v1
17-1-31 19:48:50.5|Debug|Parser|Release Group parsed: RARBG
17-1-31 19:48:50.5|Debug|DownloadedEpisodesImportService|Unknown Series *********************.2016.EXTENDED.1080p.BluRay.H264.AAC-RARBG
17-1-31 19:48:50.5|Debug|DiskScanService|Scanning 'Z:\Data\Download\movie-radarr\' for video files
17-1-31 19:48:50.5|Debug|DiskScanService|**0 video files were found** in Z:\Data\Download\movie-radarr\
`

And as I said, manual scan finds the exact same file and imports it fine.

**Comment by Abzie** [comment]
API is different for Radarr, as Sonarr's API is closed source.

Try DownloadedMovieScan instead.

**Comment by Crowley007** [comment]
That works. Thanks!
