### ISSUE TITLE
Issue with nginx since v3

### ISSUE THREAD

**Issue by mamema** [Radarr/Radarr#5474]
Hi,

every save or change / test config button isn't working. As i have a nginx proxy chain with two nginx servers, i know it is a nginx issue, i 'm just lost, as it was working before changing to v3.
Everything is working, if i only use one proxy. With both proxy enabled i get a Bad request 400 if i click on eg: test indexer

192.168.0.30 - - [03/Dec/2020:19:02:10 +0100] "POST /api/v3/indexer/test HTTP/1.1" 400 0 "https://url/settings/indexers" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:83.0) Gecko/20100101 Firefox/83.0" "ip"

it's odd, that he "test all indexer" button is working:

192.168.0.30 - - [03/Dec/2020:19:11:15 +0100] "POST /api/v3/indexer/testall HTTP/1.1" 200 106 "https://url/settings/indexers" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:83.0) Gecko/20100101 Firefox/83.0" "ip"

My nginx of first nginx:

location / {
            default_type application/json;
            proxy_set_header        Host                $host;
            proxy_set_header        X-Real-IP           $remote_addr;
            proxy_set_header        X-Forwarded-For     $proxy_add_x_forwarded_for;
            proxy_intercept_errors  on;
            proxy_http_version      1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $http_connection;
            proxy_redirect off;
            proxy_no_cache $cookie_session;
            proxy_cookie_path ~*^/.* /;
            proxy_pass https://192.168.0.30:18889;

the second then does just

location / {
            proxy_pass http://192.168.0.30:8310;

which leads to the radarr web page

Any hints?

**Comment by bakerboy448** [comment]
See the FAQ

If you’re using self signed or unsigned certs, those won’t work as radarr now validates certs in 2020.

Invalid certs are merely security theatre.

Support Requests -> [Reddit](https://www.reddit.com/r/radarr/) or [Discord](https://discord.gg/r5wJPt9)

**Comment by mamema** [comment]
using letsencrypt no self signed certs....

**Comment by chadblose** [comment]
hey @mamema I had the same error and found it's a new webserver that needs a few changes in the nginx config. Found it at https://github.com/Radarr/Radarr/wiki/FAQ#why-doesnt-aphrodite-work-behind-an-nginx-reverse-proxy
This goes in the location block.
```
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $http_connection;
```
