### ISSUE TITLE
Search all wanted

### ISSUE THREAD

**Issue by Comb4tWombat** [Radarr/Radarr#5475]
The old version of Radarr had a feature/tab where we had an option to force a search of all the missing/wanted items.

This was very useful as sometimes I found that when I force a search of all wanted items it normally finds items that were not available for a while

**Comment by bakerboy448** [comment]
This exists; check filters -> wanted

Then search filtered

**Comment by Comb4tWombat** [comment]
Ah, thanks. I was looking everywhere for that.
