### ISSUE TITLE
Include "Add Collection" option when adding a new movie.

### ISSUE THREAD

**Issue by daFreeMan** [Radarr/Radarr#5476]
**Is your feature request related to a problem? Please describe.**
This isn't really a solution to a _problem_ but it would make life easier...

When adding a new movie, I often want to add all the movies in the collection. If it's a series like _Mad Max_ a search for "Mad Max" will likely show all the movies in the top page of results. However, if I search for _London Has Fallen_, I'm not going to get the rest of the _...Has Fallen_ collection showing up, and I certainly won't get all the movies in the series if I search for _Die Hard_. (Whether I _should_ or not is a totally different discussion, not for this forum. 🤣)

**Describe the solution you'd like**
On the `Add New Movie` dialogue, there should be a check box (enabled/visible only if the movie is IDd as a part of a collection) to `Add list - TMDB collection`. When checked, this would _either_:
* Add the collection using the `add collection` logic that already exists and using all the parameters defined for the individual movie, (preferable) or
* Go directly to the `Add Collection` dialogue, prepopulated with the parameters just used for adding the individual movie. (Less favorable from a UX perspective, but probably easier from a code perspective.)

**Describe alternatives you've considered**
The alternative is to leave it as is and force people to go to the individual movie to enable the Collection option.

**Additional context**
Having the `Add Collection` available as part of the `Add Movie` process would improve discoverability of the `Collections` feature added in v3.

[AB#786](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/786)

**Comment by Qstick** [comment]
Dupe #5435

**Comment by Qstick** [comment]
Gross, that other issue sucks. Yours is worded much better... Switcheroo

**Comment by daFreeMan** [comment]
I'm not a huge fan of following the rules, @Qstick, but they do have their good points... :)

**Comment by minermartijn** [comment]
This would be a great feature, hopefully someone will complete this soon 👍 .

Was about to write my own feature request for this, but then i thought hmhmh, i should look if someone beat me to it first..
Dont want to break the rules.

Maybe it also smart to make the collection name(That you can add in the table view) to make that clickable and then have radarr search for all the movies in the collection so you can add which ever you want to your own list.
