### ISSUE TITLE
Unable to connect to Plex Server

### ISSUE THREAD

**Issue by OneAshMan** [Radarr/Radarr#5477]
After Radarr upgrade to v3.0.0.4204, Radarr is unable to connect to Plex Server.
No settings have changed.
Same system running Radarr is also running Sonarr and Lidarr.  Neither have any issues.
PC has been restarted.
Am able to ping the Plex server.

OS - Windows 10 2004 (Build 19041.630) 86.0.4240.198] (Only needed for UI issues)
Radarr - 3.0.0.4204
Sonarr - 2.0.0.5344
Lidarr - 0.7.2.1878

[radarr.trace.txt](https://github.com/Radarr/Radarr/files/5639711/radarr.trace.txt)

**Comment by bakerboy448** [comment]
Support Requests -> [Reddit](https://www.reddit.com/r/radarr/) or [Discord](https://discord.gg/r5wJPt9)

**Comment by OneAshMan** [comment]
May I know why this was closed?I have no issues with any device connecting to Plex.I only have an issue with Radarr connecting AFTER the update. 

    On Thursday, December 3, 2020, 05:55:56 PM CST, bakerboy448 <notifications@github.com> wrote:  
 
 


Support Requests -> Reddit or Discord

**Comment by bakerboy448** [comment]
Not a bug; is a support request.


I'm guessing you're using HTTPS with invalid certificates.

If you're doing that on a local network, stop it does nothing.

If you're doing that remotely, stop that's security theater

If you're not, then Reddit or discord for some help

**Comment by OneAshMan** [comment]
That did it.It was not my intention to use HTTPs, but that was it.Thank you.
 

    On Thursday, December 3, 2020, 06:08:32 PM CST, bakerboy448 <notifications@github.com> wrote:  
 
 


Not a bug; is a support request.

I'm guessing you're using HTTPS with invalid certificates.

If you're doing that on a local network, stop it does nothing.

If you're doing that remotely, stop that's security theater

If you're not, then Reddit or discord for some help
