### ISSUE TITLE
Radarr reports Remote transmission "Likely missing or incorrect remote path mapping" despite working in the currently defined directory on the remote storage device

### ISSUE THREAD

**Issue by s0m3f00l** [Radarr/Radarr#5478]
Radarr reports Remote transmission "Likely missing or incorrect remote path mapping" despite working in the currently defined directory on the remote storage device I get this in my status:

Remote download client Remote_Transmission-syn places downloads in /volume1/Volume_1/Downloads/transmission-downloads/ but this directory does not appear to exist. Likely missing or incorrect remote path mapping.

This directory is correct and works when downloading but shows as incorrect according to RADARR

RADARR version     3.0.0.4204

Remote Transmission version   3.00 (bb6b5a062e)

**Comment by bakerboy448** [comment]
Native radarr or docker?

If docker then it’s correct.

Closing since most reports of those have been support related.

There are some edge cases and a fix is coming down the build pipes soon

**Comment by s0m3f00l** [comment]
Native
