### ISSUE TITLE
Docker container (:latest) starts without error, but no webinterface

### ISSUE THREAD

**Issue by prunhardt** [Radarr/Radarr#5481]
**Describe the bug**
Pulling the latest image and building/starting the container went flawlessly, but there's no webinterface.

**To Reproduce**
1:
sudo docker create --name=radarr \
--restart=always \
-v /home/docker/radarr/config:/config \
-v /home/docker/radarr/downloads:/downloads \
-v /home/docker/radarr/movies:/movies \
-e PGID=1000 -e PUID=1000 \
-e TZ=Europe/Amsterdam \
-p 7878:7878 \
linuxserver/radarr

2:
starting the container in portainer: starts without errors

3:
localhost:7878 in browser gives error "Site not available"

**Expected behavior**
The webinterface should start, as it does for similar containers (sonarr, sabnzbd, bazarr) 

**Screenshots**
n.a. I do have an observation that might help: the config folder is empty

**Platform Information (please complete the following information):**
 - Raspberry Pi 4B on Raspberry Pi OS (32bit) 
 - Docker: Yes
 - Mono or.NET Core Version: [e.g. Mono 5.8 or .Net Core 3.1.10] (found under System -> Status): don't know
 - Browser and Version [e.g. chrome 86.0.4240.198] (Only needed for UI issues): Chromium Versie 84.0.4147.141
 - Radarr Version [:latest]
 - Radarr Branch [develop, I think]

**Trace Logs**
n.a.

**Comment by ta264** [comment]
raspbian os doesn't support v3 docker images, see https://wiki.servarr.com/Radarr_FAQ#I_am_using_a_Pi_and_Raspbian_and_Radarr_will_not_launch

**Comment by prunhardt** [comment]
@ta264 Many thanks, using --privileged did the trick for me. So for other newbies like me, the proper command is 
sudo docker create **--privileged** 
--name=radarr
--restart=always
-v /home/docker/radarr/config:/config
-v /home/docker/radarr/downloads:/downloads
-v /home/docker/radarr/movies:/movies
-e PGID=1000 -e PUID=1000
-e TZ=Europe/Amsterdam
-p 7878:7878
linuxserver/radarr

**Comment by ta264** [comment]
A warning given the above comment: `--privileged` comes with some pretty bad security implications so most would recommend avoiding it.  Personally I'd recommend binning raspbian and installing ubuntu 20.04 arm64 instead.

**Comment by prunhardt** [comment]
Point taken. I will have a look at Ubuntu 20.04 arm64.
