### ISSUE TITLE
Cannot connect  to Radarr through web browser Mojave 10.14.6

### ISSUE THREAD

**Issue by contagius** [Radarr/Radarr#5483]
I have restarted my computer and I cannot connect through web browser localhost

I have deleted my config files with no success.
I have deleted and put in backup db with no success
I have reinstalled the v3 application via website with no success

Sonarr works fine.
[radarr.0.txt](https://github.com/Radarr/Radarr/files/5643950/radarr.0.txt)
[radarr.1.txt](https://github.com/Radarr/Radarr/files/5643951/radarr.1.txt)
[radarr.2.txt](https://github.com/Radarr/Radarr/files/5643952/radarr.2.txt)
[radarr.3.txt](https://github.com/Radarr/Radarr/files/5643953/radarr.3.txt)
[radarr.4.txt](https://github.com/Radarr/Radarr/files/5643954/radarr.4.txt)
[radarr.txt](https://github.com/Radarr/Radarr/files/5643955/radarr.txt)

Attached are my 5 most recent logs. I cannot find anything that would be easy for me to find.

**Comment by bakerboy448** [comment]
Support Requests -> [Reddit](https://www.reddit.com/r/radarr/) or [Discord](https://discord.gg/r5wJPt9)

also how did you manage to open a GHI that bypasses te template?

**Comment by contagius** [comment]
> Support Requests -> [Reddit](https://www.reddit.com/r/radarr/) or [Discord](https://discord.gg/r5wJPt9)
> 
> also how did you manage to open a GHI that bypasses te template?

I just hit new issue. I thought it was weird that there was no template myself. I will follow up with this issue via reddit. Thanks.
