### ISSUE TITLE
Synology package won't run after update to 3.0 (20200921-11)

### ISSUE THREAD

**Issue by Kramasz** [Radarr/Radarr#5484]
It updated on it's own and I was using the new interface. I tried to restart it and now I'm getting:

"Failed to run the package service"

Installed version is 20200921-11 which is the latest from SynoCommunity.

I saw the note about updating to .NET Core version, but would need a pretty thorough instruction on how to do that.

Others are experiencing the issue here:
https://community.synology.com/enu/forum/1/post/138813?page=1&sort=oldest

Happy to help provide logs, etc, but I'm no expert so would need guidance on that as well.

**Comment by bakerboy448** [comment]
Team Radarr does not handle the Synology Packages; you'll need to reach out to the synocommunity for them to troubleshoot.  That version, based on the date in the version, appears quite out of date.

if you (or anyone in that thread) use (or want to use) docker, just re-pull the image to get rid of that warning.

What link are you using to get here that is allowing you to create a totally blank issue that bypasses the templates?

**Comment by Kramasz** [comment]
I legit just hit "New issue"
