### ISSUE TITLE
Radarr/Sonarr With MacOS 11.0.1

### ISSUE THREAD

**Issue by DeadLeprechaun** [Radarr/Radarr#5486]
I'm running Big Sur (MacOS 11.0.1) on an Intel Mac.
Radarr Version
0.2.0.1480
Mono Version
6.8.0.123

Sonarr Version
2.0.0.5344
Mono Version
6.8.0.123

I am experiencing the same issue on both Radarr & Sonarr.  After upgrading to Big Sur MacOS 11.0.1. Since that time I am still able to download files that are scheduled or manually and they download on the Mac to the correct folders, however the files do not get re-named and are not transferring to my Synology NAS. From the Mac I can still browse over the network to the files on the NAS so I don’t think it’s an access/network issue.

Any help would be greatly appreciated!

**Comment by ta264** [comment]
Please join the discord channel for support, and upgrade to v3 - 0.2 is no longer supported.
