### ISSUE TITLE
Radarr Unable to See '(500) Days of Summer' File

### ISSUE THREAD

**Issue by Wreave** [Radarr/Radarr#549]
Radarr seems unable to detect my video for (500) Days of Summer. 
The file is named (500) Days of Summer (2009) [BluRay-1080p].mkv inside a folder named (500) Days of Summer (2009) (which is the path set for the movie in Radarr).

I am not sure if this has something to do with the formatting of the title, etc. Let me know if there is additional information that can be supplied to assist.

Radarr v. 0.2.0.274

**Comment by gtalmor** [comment]
Did you try to remove the [] signs and see if it works any better?

**Comment by Wreave** [comment]
So interestingly that did work and then when I did the rename function Radarr named it back to the way I had it...

Not sure why it had an issue reading it in the first place.

**Comment by gtalmor** [comment]
So just for the sake of making sure this is correct:
Filename | State in Radarr
------------ | -------------
(500) Days of Summer (2009) [BluRay-1080p].mkv | Radarr won't read file
(500) Days of Summer (2009) BluRay-1080p.mkv | Radarr will read the file but rename it to (500) Days of Summer (2009) [BluRay-1080p].mkv (to contain the [] signs)

Correct?
What will happen if you remove the movie from Radarr and let it scan it again?

**Comment by Wreave** [comment]
Actually i took out the '()' around 500 for Radarr to read it. I left the '[]' around the file quality. Sorry about that miscommunication.

After renaming Radarr put the '()' back and when I rescanned it is able to see the file.

**Comment by grufftech** [comment]
having a similar issue. 

Folder: ~/media/movies/Aliens (1986)
Filename: Aliens (1986).mkv

Radarr returns this as a "missing" file.

**Comment by geogolem** [comment]
if you go to the movie in radarr even if it says missing, it will show a movie path (folder and filename)

![image](https://cloud.githubusercontent.com/assets/23205277/22814571/b8705172-ef22-11e6-9ca9-00fbf01603f2.png)

if the movie is not named exactly as radarr specifies there, it wont pick it up. If you want it to pick up the movie, you cna edit the movie and change that field.... radarr will then see your movies files.

Not sure if this is the problem you are having.. but it would explain why the renamer fixed the problem without actually changing the name of the movie... in that case maybe radarr just changed what it was expecting... 

not really sure. but maybe you could confirm if this is the issue or not.

**Comment by Wreave** [comment]
I had checked that and it was the same. I will attempt to reproduce the issue again later tonight using the same movie.

**Comment by Wreave** [comment]
I just tried to reproduce it now instead here are my steps:
- removed movie from radarr (did not delete files)
- added the movie in radarr
- verified the path was correct
- radarr is not finding the movie

I am actually now completely unable to get radarr to find this movie. I am on version 0.2.0.316.
- I removed all formatting from the folder and file before I added it back to radarr
- Folder is name 500 Days of Summer
- File name is 500 Days of Summer

Radarr just can't seem to see this movie.

**Comment by galli-leo** [comment]
@Wreave Please make sure that the folder contains the year of the movie in the name (current limitation, will be fixed sometime soon)

**Comment by Wreave** [comment]
Okay I did that and I am still able to reproduce the issue as follows:
- Remove movie from Radarr
- Name folder **and file** (500) Days of Summer (2009)
- Add movie in Radarr, unable to find the file
- Removing leading '(' on the file and Radarr can see it
- Organize the file and Radarr adds the '(' back and can still see the file
