### ISSUE TITLE
v3 import is broken

### ISSUE THREAD

**Issue by ncsufan8628** [Radarr/Radarr#5491]
Hello, I can no longer import movies that exist in my watchlist after upgrading to v3.  I do this sometimes when my sources in Radarr cannot find content automatically but I can find it manually somewhere.  In this case, Radarr is already monitoring and looking for a release.  

My normal workflow that worked in v2

1.  Download Movie outside of radarr
2.  Browse radarr's import function to said movie location
3.  Match movie if not done automatically
4.  Click import

Currently I cannot import a file for an "existing movie" that is in my radarr monitored list.  When using the import function, it should allow me to select an existing movie in my monitored and import the file.  This is happening regardless if Radarr has marked the movie "Downloaded", meaning for missing movies that are in the list, I cannot import files for them.

**Comment by bakerboy448** [comment]
Support Requests -> [Reddit](https://www.reddit.com/r/radarr/) or [Discord](https://discord.gg/r5wJPt9)

You’re using the wrong import button probably 

You want manual import not import

**Comment by ncsufan8628** [comment]
yep, you're right.  I saw that shiny Import button under movies and assumed that was the same section.  thanks, and will move any further questions like this to Discord
