### ISSUE TITLE
Failed to load system status from api

### ISSUE THREAD

**Issue by dethknite** [Radarr/Radarr#5492]
Failed to load system status from API
Version 3.0.0.4204

On going to the main -- http://localhost:port, I initially get a login prompt. After entering credentials, and clicking login, the "random welcoming message" flashes for less than a second and the above error is displayed. After initial upgrade to v3, this was working for a period of a few hours maybe.. hard to tell as I wasn't checking often, then began consistently failing. The same error exhibits on Chrome, Firefox, and Edge (no plugins or extensions). I have tried rebooting, clearing cache/cookies, disabling extensions in chrome (though Edge has no extensions enabled on my PC).

*Screenshot attached*
*Trace/Debug logs attached*

Windows 10 build 19042.662
.NET Core
Chrome 87.0.4280.88 (Official Build) (64-bit)
Firefox 83.0 (64-bit)
Edge 87.0.664.55 (Official build) (64-bit)
Radarr v3.0.0.4204
![radarr v3 error](https://user-images.githubusercontent.com/965431/101228937-78b93d00-3663-11eb-95a8-0b502e1f66fc.png)
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/5646231/radarr.debug.txt)
[radarr.trace.txt](https://github.com/Radarr/Radarr/files/5646232/radarr.trace.txt)

[AB#1024](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1024)

**Comment by bakerboy448** [comment]
Reverse proxy?

Logs seem fine.

Hop over to Reddit or discord and let’s see

**Comment by dethknite** [comment]
No reverse proxy... this is just running and connecting on the same PC.

**Comment by bakerboy448** [comment]
Humor me and do a reinstall just to ensure nothing weird happen with the update

**Comment by dethknite** [comment]
I actually did that exact thing earlier... because the initial install was auto. I also tried changing the <Branch>develop</Branch> to master as there was a mention in the Release notes on here about switching it.

**Comment by dethknite** [comment]
Dang it... the manual install I tried after the error was x86. I am trying again with the x64.

**Comment by dethknite** [comment]
Alright... uninstalled everything (saved config, log/radarr dbs, backups). Reinstalled x64 installer... launched and still getting the error.

**Comment by bakerboy448** [comment]
Pop on over 
-> [Reddit](https://www.reddit.com/r/radarr/) or ideally [Discord](https://discord.gg/r5wJPt9) and someone can help further

Pretty sure it's not a bug, at least nothing stands out from skimming those logs

**Comment by dethknite** [comment]
I did notice that the error in the log bubbles from "Microsoft.Extensions.Hosting.WindowsServices.WindowsServiceHelpers.IsWindowsService()", and I did NOT install the Radarr service during the installation. Could this perhaps be causing an issue with code trying to communicate on an IPC pipeline with a non-existant service process?

2020-12-3 17:01:55.0|Fatal|RadarrErrorPipeline|Request Failed. GET /api/v3/system/status

[v3.0.0.4204] System.InvalidOperationException: Process has exited, so the requested information is not available.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_SessionId()
   at Microsoft.Extensions.Hosting.WindowsServices.WindowsServiceHelpers.IsWindowsService()
   at NzbDrone.Common.EnvironmentInfo.RuntimeInfo.get_IsUserInteractive() in D:\a\1\s\src\NzbDrone.Common\EnvironmentInfo\RuntimeInfo.cs:line 66
   at Radarr.Api.V3.System.SystemModule.GetStatus() in D:\a\1\s\src\Radarr.Api.V3\System\SystemModule.cs:line 51
   at Radarr.Api.V3.System.SystemModule.<.ctor>b__9_0(Object x) in D:\a\1\s\src\Radarr.Api.V3\System\SystemModule.cs:line 43
   at Nancy.NancyModule.<>c__DisplayClass14_0`1.<Get>b__0(Object args)
   at Nancy.NancyModule.<>c__DisplayClass16_0`1.<Get>b__0(Object args, CancellationToken ct)
   at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)
   at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context)
   at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
   at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)


2020-12-3 17:01:55.0|Debug|Api|[GET] /api/v3/system/status: 500.InternalServerError (32 ms)

**Comment by dethknite** [comment]
Well.. that seems to be the case. I uninstalled, and reinstalled it with the service... and it launches fine.

**Comment by Qstick** [comment]
@dethknite were you running as administrator? That's just a check we use to determine if it is running as a service, its a bit odd that it fails like that. Did you restart from within Radarr at any point (that's a known issue that may have also caused this)?

**Comment by dethknite** [comment]
The error occurred when I installed without the service. I always used to run the radarr.exe with a watchdog tool I wrote... as an administrator user. The service was never installed nor running when the error occurred... however, when I uninstalled and reinstalled selecting to install the service (radar.console.exe), the issue is gone. I left the service running as local service.

**Comment by Qstick** [comment]
Yep get that part, the service being installed or not shouldn't effect the failure of that function, its meant to return true or false, but instead has failed complete because it can't find the process that Radarr is currently running under. So just trying to frame up exactly how you were running it when you had it installed normally (non-service)

**Comment by austinwbest** [comment]
You can run radarr.console the same way as the tray app & likely it'll work if it is what we see last week Q

Disable the service & instead of running radarr.exe run radarr.console & see

**Comment by dethknite** [comment]
That did work... though the console window remains open.

**Comment by austinwbest** [comment]
Yea, it was more for a test to check a theory

**Comment by LtRipley36706** [comment]
I'm also seeing this issue frequently.

Multiple year old install auto upgraded on Sunday, and I currently launch via start up task which just does `start Radarr.exe /icon` at a certain time after system boot.

**Comment by FolkSong** [comment]
I can reproduce this as follows:
1. Run "start Radarr.exe" from a non-admin batch script or cmd window
2. Close the cmd window

If the batch or cmd is run as administrator there's no issue. As non-admin it works as long as the window remains open, but closing the window someone messes it up (although the process keeps running).

I noticed it because I use batch scripts to stop and start several downloader programs.

**Comment by neck27** [comment]
I too am having this issue.  I also run Sonarr on the same box and it gets a similar error.  Refreshing the browser seems to bring it back but as soon as I change tabs and go back (After some time) it throws the API error.

**Comment by dethknite** [comment]
> I too am having this issue. I also run Sonarr on the same box and it gets a similar error. Refreshing the browser seems to bring it back but as soon as I change tabs and go back (After some time) it throws the API error.

Likewise, I run Sonarr on the same box, in the exact same way I used to run Radarr, and Sonarr has never had this issue for me and still is running fine. I have temporarily let Radarr run as a service in the interim.... and Sonarr is still getting started by a startup script as "C:\ProgramData\Sonarr\bin\Sonarr.exe" and running great.

**Comment by neck27** [comment]
I switched to Edge.   For me it seems to be because of Google Chrome.

**Comment by Shredder5262** [comment]
I just got this same message also. Same errors in the logs and all. In  my case i couldn't uninstall because even the uninstall file was corrupted. Had to use Revo Uninstaller to scrub Radarr from the system. Fortunately i was able to back up the DB and config files. I reinstalled Radarr and everything seems ok now. But not sure why this happened.

**Comment by daes10** [comment]
I had the same problem today, after a clean windows installation. But i only restart my PC. And afterwords there was no more "Failed to load system status from api" Message. And then everything works fine!

**Comment by Ae3NerdGod** [comment]
i am having this issue starting via AHK (which closes after it opens radar) using another device to access radar AFTER i get the error, usually resolves the issue (on both browsers)

a workaround for the console having to be open in the interim is using AHK to hide the window as well:

```
#notrayicon
loop:
WinHide, ahk_exe Radarr.Console.exe
sleep 10000
goto loop
```

[compiled exe that hides radarr.console every ten seconds](https://github.com/Ae3NerdGod/hideradcon/raw/main/radarrhide.exe)

**Comment by Ae3NerdGod** [comment]
full workaround for starting radarrtray from a script without installing as service
https://raw.githubusercontent.com/Ae3NerdGod/hideradcon/main/radarrrunaround.ahk
[compiled EXE](https://raw.githubusercontent.com/Ae3NerdGod/hideradcon/main/radarrrunaround.exe)
just double click for setup if radarr isnt in `C:\ProgramData\Radarr\bin\Radarr.exe`

**Comment by dethknite** [comment]
I have attempted to run the radarr.exe again (stopped/disabled service) and it is working so far (24 hours later). Not sure if anything changed in the last several radarr releases, or windows, or something else... but the IPC/service communication doesn't seem to be offending the process at the moment.

**Comment by dethknite** [comment]
I believe this issue is resolved. At least the workaround is to install the service when installing Radarr... and then go to the service and stop it and disable it. Radarr.exe functions as before if the service exists even if disabled.
