### ISSUE TITLE
Cannot add two movies with same name and year

### ISSUE THREAD

**Issue by steve1977** [Radarr/Radarr#5495]
Title says it all. I cannot two movies with the same name and year. For example:

https://www.imdb.com/title/tt8530978/
https://www.imdb.com/title/tt7524414/

**Comment by bakerboy448** [comment]
Radarr does not use IMDB for data, but TMDB. Please link those entries

Also fill out the template you blew away

**Comment by steve1977** [comment]
https://www.themoviedb.org/movie/603519-beats
https://www.themoviedb.org/movie/493141-beats

**Comment by austinwbest** [comment]
You need to add imdb or tmdb token to folder names to do this. Discord or reddit if you need further assistance :)
