### ISSUE TITLE
Radarr v3 - Add Language columns in table view and filter

### ISSUE THREAD

**Issue by crush89** [Radarr/Radarr#5496]
I would like to search and filter movies based on the audio language. On the movie detail page, there is now the possibility to see the audio language (eg German, English, Multi-Languge), which is great and helpful if you maintain a bilangual database.

If I want to see all my movies in table view I am missing the possibility to sort them by language. It would be great, if you could extend the "add column" functionallity to "language" as well. Please also add the language filter to the filter selection too.

**Comment by Qstick** [comment]
#5304 same reasoning, we have plans to change the way movies and files interact which will break this... Thus we are not going to add it just to remove it again later.
