### ISSUE TITLE
Importing ISO files

### ISSUE THREAD

**Issue by drowse7en** [Radarr/Radarr#5498]
I've noticed that Radarr has been importing ISO files as "extra files".

I've found 3 files so far and will be disabling "import extra files".

**Comment by owine** [comment]
The extensions imported as extra files are configurable under `Settings -> Media Management`. Make sure you enable `Show Advanced`.

**Comment by drowse7en** [comment]
@owine "srt" is the only entry in the advanced field for **Import Extra Files**.

**Comment by Qstick** [comment]
Closing, Need all the template information.
