### ISSUE TITLE
IPv6 IP host validation. Claims IPv6 address is "invalid" 

### ISSUE THREAD

**Issue by Napsterbater** [Radarr/Radarr#5499]
**Describe the bug**
When adding a connection, such as Emby, suppling a Ipv6 address in the host field fails to validate, radarr compalins that it is no valid.
**To Reproduce**
1. Go to Connections.
2. Click on Emby
3. Supply all info and an IPv6 address for the host.
4. See error "must be valid Host without http://"

**Expected behavior**
It should accept it as valid.
**Screenshots**
https://drive.google.com/file/d/1NzegxGJOy4-fe79YoG2wJcswMUDiGXti/view?usp=sharing

**Platform Information (please complete the following information):**
 - OS: Windows Server 2019 1809
 - Docker: No
 - Mono or.NET Core Version: .NET Core Yes (3.1.10)
 - Browser and Version: N/A
 - Radarr Version: 3.0.0.4204
 - Radarr Branch: Master

**Trace Logs**
https://drive.google.com/file/d/1oZQ-FA7tlsu0s3vcqbAjA1ePHDEUhoPR/view?usp=sharing

[AB#701](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/701)

**Comment by austinwbest** [comment]
To be fair, it isn't valid. You can't use Ipv6 with http protocol like that.

**Comment by Napsterbater** [comment]
> To be fair, it isn't valid. You can't use Ipv6 with http protocol like that.
Ummmm. What are you talking about.


> I don't recall if it auto appends http,but you can try what is valid with Ipv6 and iirc that is brackets around it
It doesn't work with or without brackets.

**Comment by austinwbest** [comment]
What am I taking about.. Well if it prepends http to what you enter in the box to make its connection, then it is not valid as the error states. 

http://{ipv6} is not valid as it contains colons iirc (I don't use Ipv6 often) :)

**Comment by Napsterbater** [comment]
Most software I'm setting up a configuration for something you simply provided the IPv6 address just as a IPv4, It recognizes that it is an IPv6 address and uses it in whatever format it needs to.

If this software simply copies what's in this box adds http:// the front and a colon port number to the end then it should accept the [::1] format.

It doesn't accept either. That is the problem. You cannot use an IPv6 literal in either format.

**Comment by Qstick** [comment]
Right, this is an issue with the host field validation that we inherit from Sonarr... it doesn’t like IPv6 as of now.

**Comment by bakerboy448** [comment]
Xref Sonarr https://github.com/Sonarr/Sonarr/issues/4149

**Comment by bakerboy448** [comment]
https://github.com/Radarr/Radarr/commit/3617bef54bbfa533f291441c70ce19c19ecf87d0
