### ISSUE TITLE
Date sorting not working

### ISSUE THREAD

**Issue by Tiwas** [Radarr/Radarr#5501]
**Describe the bug**
Went into the list of movies to see what's coming. Sorted by date and it seems pretty clear (though I'm still pretty dazed after having to go to work *way* too early) that it cannot handle dd.mm.YYYY format.

I've attached an image showing the sorting. Logs probably won't do anyone any good, but please ask if I can provide something else.

![image](https://user-images.githubusercontent.com/17053402/101271380-697ce100-3782-11eb-9b1b-b8c5873962db.png)

**Comment by bakerboy448** [comment]
Get a good night’s sleep. Wake up,  make some fresh coffee, and take another look. I think that’s chronological order lol?

**Comment by Tiwas** [comment]
Uhm...yes. Sorry. I need to stop thinking my IQ is higher than my current intake of caffeine in mg 🤣
