### ISSUE TITLE
Add Movie Posters to Add New Movie search results in mobile resolution (v3)

### ISSUE THREAD

**Issue by arksharq** [Radarr/Radarr#5503]
**Is your feature request related to a problem? Please describe.**
The movie posters are not shown in the Add new movie search results when using a mobile resolution. I've found that without the movie poster, its more difficult to confirm the correct movie to select when titles are the same or you're just not familiar with the movie

**Describe the solution you'd like**
I would like for the movie poster to appear next to the title, however small it may need to be.

**Describe alternatives you've considered**
Adding the movie and then browsing to its entry to confirm the Poster.

[AB#695](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/695)

**Comment by bakerboy448** [comment]
condensing into https://github.com/Radarr/Radarr/issues/5732
