### ISSUE TITLE
File chmod mode: will not validate valid octal modes

### ISSUE THREAD

**Issue by scottcove** [Radarr/Radarr#5504]
**Describe the bug**
When attempting to change the file mode that Radarr sets, the validation will fail unless the file mode is 0644.  For samba shares, this is often needed to be 1777 or at the least 0766.  Neither of these validate despite being valid octals.

**To Reproduce**
1. Go to 'Settings > Media Management'
2. Click on 'Show Advanced'
3. Scroll down to 'File chmod mode and try to enter a valid octal such as 1777 or 0766'
4. See error.
p**Experected behavior**
This should validate all octals, not just the default set.

**Screenshots**
https://drive.google.com/file/d/1oLiKgT4Drs8aSCWHIaNXE7eo5EqVKGjw/view?usp=sharing
https://drive.google.com/file/d/1k9h0lMH-_2r5M3QxwwOY34toBSVCthB8/view?usp=sharing

**Platform Information (please complete the following information):**
 - OS: Linux 4.19.107-Unraid
 - Docker: Yes
 - Mono or.NET Core Version: (not found)
 - Browser and Version Vivaldi 3.3.2022.45 (Stable channel) (64-bit) (Windows 10) (Also appears on the equivalent on Ubuntu 20,04 Desktop)
 - Radarr Version 3.0.0.3790
 - Radarr Branch preview (via the linuxserver.io Docker repos - 3.0.0.3790-ls31 by linuxserver.io)

**Trace Logs**
https://drive.google.com/file/d/1f5IZr1BP74LerpJmROnXrm26aWu425gS/view?usp=sharing

**Comment by ta264** [comment]
upgrade, you're well out of date

**Comment by ta264** [comment]
PS docker tag should be latest now, not preview
