### ISSUE TITLE
Restart from UI doesn't work - Error

### ISSUE THREAD

**Issue by chench00** [Radarr/Radarr#5505]
**Describe the bug**
Restarting Radarr from UI causes an error. Resolution is to start it using `sudo systemctl start radarr.service`.

**To Reproduce**
1. Go to 'User icon on top right, click "restart"'
2. Systemctl outputs error

**Expected behavior**
Radarr restarts.

**Platform Information (please complete the following information):**
 - OS: Ubuntu 20.04
 - Docker: [No]
 - NET Core Version: (3.1.10)
 - Radarr Version 3.0.0.4204
 - Radarr Branch [develop]

Error:

`     Loaded: loaded (/etc/systemd/system/radarr.service; enabled; vendor preset: enabled)
     Active: inactive (dead) since Sun 2020-12-06 10:36:12 EST; 2s ago
    Process: 27394 ExecStart=/opt/Radarr/Radarr -nobrowser -data=/home/USER/.config/Radarr/ (code=exited, status=0/SUCCESS)
   Main PID: 27394 (code=exited, status=0/SUCCESS)
      Tasks: 0 (limit: 2317)
     Memory: 10.1M
     CGroup: /system.slice/radarr.service

Dec 06 10:36:12 ubuntufeed Radarr[27394]: [Info] LifecycleService: Restart requested.
Dec 06 10:36:12 ubuntufeed systemd[1]: radarr.service: Succeeded.
Dec 06 10:36:12 ubuntufeed Radarr[27457]: Error: no "view" mailcap rules found for type "application/x-msdos-program"
Dec 06 10:36:12 ubuntufeed Radarr[27440]: /usr/bin/xdg-open: 869: www-browser: not found
Dec 06 10:36:12 ubuntufeed Radarr[27440]: /usr/bin/xdg-open: 869: links2: not found
Dec 06 10:36:12 ubuntufeed Radarr[27440]: /usr/bin/xdg-open: 869: elinks: not found
Dec 06 10:36:12 ubuntufeed Radarr[27440]: /usr/bin/xdg-open: 869: links: not found
Dec 06 10:36:12 ubuntufeed Radarr[27440]: /usr/bin/xdg-open: 869: lynx: not found
Dec 06 10:36:12 ubuntufeed Radarr[27440]: /usr/bin/xdg-open: 869: w3m: not found
Dec 06 10:36:12 ubuntufeed Radarr[27440]: xdg-open: no method available for opening '/opt/Radarr/Radarr.dll'`

[AB#696](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/696)

**Comment by Qstick** [comment]
For further information, same problem happens on Windows. RuntimeInfo incorrectly chooses the dll as the executing assembly. There a fix in progress here #5416

**Comment by bakerboy448** [comment]
https://github.com/Radarr/Radarr/commit/6befbec38152192b262b1995d4045f79fd209d79

https://github.com/Radarr/Radarr/commit/399f242f87bff805a5aec57f2f0be32ac6f1bdeb
