### ISSUE TITLE
Radarr Indexer failures

### ISSUE THREAD

**Issue by chrisjc76** [Radarr/Radarr#5506]
**Describe the bug**
In the new platform, every time I refresh the filters, I constantly have to fix the indexers. I click the little health icon at the end and it refreshes it. Then a minute later and it fails again. Sometimes its one, two or all the indexers. I know many other people are having the same issue.. Any known fix or correction?

**To Reproduce**
Filter by missing or wanted. Click search filtered.

**Expected behavior**
To search for all/new or missing files
**Screenshots**

**Platform Information (please complete the following information):**
 - OS: Windows 10
 - Docker: [Yes/No]
 - Mono or.NET Core Version: [e.g. Mono 5.8 or .Net Core 3.1.10] (found under System -> Status)
 - Browser and Version [e.g. chrome 86.0.4240.198] (Only needed for UI issues) Chrome
 - Radarr Version [e.g. 3.0.0.2956]
 - Radarr Branch [e.g. master]

**Trace Logs**
Turn on Trace logs under Settings -> General and wait for the bug to occur again. **Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**
[radarr.trace.pdf](https://github.com/Radarr/Radarr/files/5649104/radarr.trace.pdf)

**Comment by bakerboy448** [comment]
Support Requests -> [Reddit](https://www.reddit.com/r/radarr/) or [Discord](https://discord.gg/r5wJPt9)

Nothing in your logs indicate any indexers are failing.   But based on the ones you’re using; they’re a bit shakey and will cause intermittent errors.

PS you missed some pieces of the template 

I’m also impressed, a 100 pg PDF of logs.

For future reference: Pastebin not PDF is preferred and not the entire log; just several hundred lines on either end of the issue
