### ISSUE TITLE
Memory optimisation

### ISSUE THREAD

**Issue by simonk83** [Radarr/Radarr#551]
I know this is on your list, just wanted to make an issue for it anyway.  I run in a docker and it's routinely getting up close to 1GB of ram (Sonarr by comparision generally sits under 200mb).  I've put a limit on it in the docker for now, but it'd be nice if it were a bit more efficient :)

Great job so far as always.

**Comment by onedr0p** [comment]
How many movies do you have? Radarr takes 26.1M in my docker container with 30 movies.

**Comment by simonk83** [comment]
114 at the mo. It usually starts off low but a day or two later it's
totally bloated.

I run Docker on a synology, no idea if that implementation is less
efficient, but I do run a few other dockers and they all stay relatively
low (Emby aside which appears to be a hog :D)

**Comment by webbson** [comment]
I run it on windows and have like 50 wanted movies and 300 in library. I sit on about 60MB memory usage.

**Comment by subzero79** [comment]
I noticed this a few days ago docker stats reported 800MB. Check if you have loglevel into debug or trace, if so switch to info.

**Comment by simonk83** [comment]
Definitely on info ;)

**Comment by simonk83** [comment]
Ok, I suspect it's due to the "Refresh movies" task not releasing memory when it's completed (or related to that task at least).

Fresh boot:
![img_6100](https://cloud.githubusercontent.com/assets/518440/22564475/bc9a02b0-e9d8-11e6-971b-f7ad3112cfb4.PNG)

During Refresh:
![img_6107](https://cloud.githubusercontent.com/assets/518440/22564489/d4d39e18-e9d8-11e6-82ab-d50ef4b4c528.PNG)

After refresh:
![img_6108](https://cloud.githubusercontent.com/assets/518440/22564495/dc5e4df4-e9d8-11e6-8d10-38acb7ae81d9.PNG)

**Comment by simonk83** [comment]
2 hours later:
![image](https://cloud.githubusercontent.com/assets/518440/22569816/10d1480c-e9ed-11e6-85fd-2a7b7fb7555b.png)

**Comment by Peap0d** [comment]
I don't think the DSM docker GUI is very reliable for determining actual memory usage. For example:

<img width="712" alt="syn-doc-gui" src="https://cloud.githubusercontent.com/assets/6188725/22574756/efd45248-e97e-11e6-8691-198b3906fcbd.png">
 and yet I'm only using 3,579 meg of memory:

root@DS2415:/# free -m
              total        used        free      shared  buff/cache   available
Mem:          16041        3579         911          32       11550       12097
Swap:          2047        1093         954

In addition inside my sonarr container:
  202 abc       20   0 2532168 769324  11148 S   0.0  4.7 901:35.05 mono

I'm clearly not using 6.5 gig of RAM.

**Comment by onedr0p** [comment]
Did you guys try to set a max_mem on your docker instances? I do this for rutorrent and it seems to keep it down.

**Comment by simonk83** [comment]
I have set a max mem yep.  That keeps it down, but I guess that's really fixing the issue :D

**Comment by onedr0p** [comment]
As @Peap0d I don't think it's reporting correctly...

![image](https://cloud.githubusercontent.com/assets/213795/22575071/4b45b96c-e981-11e6-84fb-a73116388e4a.png)

Yet my system says I am only using ~8GB of memory.

**Comment by simonk83** [comment]
I mean I only noticed as my NAS was redlining recently, so it's definitely
actual memory usage in my case. There's only 3GB in the box and the only
thing using it is Docker 😄

**Comment by onedr0p** [comment]
Do you use swap for additional memory?

**Comment by simonk83** [comment]
One sec, just VPN'ing in so I can check

**Comment by simonk83** [comment]
Ok
![img_6110](https://cloud.githubusercontent.com/assets/518440/22575373/5416314c-ea09-11e6-92f2-6b48f1b3c44f.PNG)
![img_6111](https://cloud.githubusercontent.com/assets/518440/22575375/54782992-ea09-11e6-8572-12d97fe457a7.PNG)
![img_6112](https://cloud.githubusercontent.com/assets/518440/22575374/547538d6-ea09-11e6-916e-231dc41e1c1d.PNG)

**Comment by simonk83** [comment]
To be fair, Radarr has dropped there and Nzbget is ramping up (it's downloading), so maybe I'm unfairly blaming Radarr here and Docker is just chucking memory at containers willy nilly :D

**Comment by onedr0p** [comment]
Closing this issue unless serious issues arise.
