### ISSUE TITLE
Allow us to change the width of the Source Title column

### ISSUE THREAD

**Issue by trulow** [Radarr/Radarr#5510]
**Is your feature request related to a problem? Please describe.**
When browsing releases, allow us to change the width of the [Source Title Column as most, if not all titles, are cut off.](https://i.imgur.com/j8vd6jA.png)

**Comment by austinwbest** [comment]
Duplicate and already fixed https://github.com/Radarr/Radarr/pull/5428

You'll just need to wait for it to reach your branch during the rollout process.
