### ISSUE TITLE
Remote path mapping reports it's not valid

### ISSUE THREAD

**Issue by redfellow** [Radarr/Radarr#5511]
![image](https://user-images.githubusercontent.com/1110164/101393029-21b7a000-38cf-11eb-98dd-cf52b65ad330.png)

"Remote download client QBittorrent places downloads in ... but this is not a valid Windows path. Review your remote path mappings and download client settings."

I just updated and have Radarr set up exactly the same way as Sonarr v3, yet Radarr complains about the remote mapping. I checked that the service is running on a user that has access to the share (same as Sonarr).

Is this a false nag?

**Comment by ta264** [comment]
Can't tell from the limited information you've given us.  Hop on the discord and someone will sort you out.

**Comment by redfellow** [comment]
Will do, thanks
