### ISSUE TITLE
Upgrade to v3 has broken reverse proxy

### ISSUE THREAD

**Issue by JimboJamez** [Radarr/Radarr#5513]
Hi everyone

I was automatically updated to Radarr v3 last week and since then have not been able to reach the app from outside my network. My NGINX reverse proxy was working perfectly with v2, but since the upgrade I am receiving the following error:

![image](https://user-images.githubusercontent.com/25968238/101418594-4c8f0c00-3942-11eb-9d48-182e06a7078d.png)

The related block in my config is as follows:

```
location /radarr {
            proxy_pass http://localhost:7878/radarr/;
            proxy_set_header  X-Real-IP  $remote_addr;
            proxy_set_header Host localhost;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_redirect off;
        }	
```

This has not been changed since the upgrade.

I'm wondering if anyone else has had the same issue and has been able to resolve it?

**Comment by bakerboy448** [comment]
https://wiki.servarr.com/Radarr_FAQ#why-doesnt-radarr-work-behind-an-nginx-reverse-proxy
