### ISSUE TITLE
V3: Sort movies by Custom Formats (or by Audio Codec/Channels)

### ISSUE THREAD

**Issue by fiveoone** [Radarr/Radarr#5517]
**Is your feature request related to a problem? Please describe.**
I use Custom Formats a lot to make sure I get the best audio quality possible. And I consider a movie finished (to be unmonitored) once I have a TrueHD 7.1/Atmos release. I need a way to sort all my movies based on these criteria.

**Describe the solution you'd like**
In the Movie browser, be able to add Custom Formats or Audio Codec/Channels to the Table so they can be sorted.

**Describe alternatives you've considered**
It only happens automatically with new movies, but since I also want to upgrade old movies, the movies don't end up in the Unmonitored state automatically even if they have reached the Upgrade Points necessary.
Auto-tagging could be another way based on criteria from the MediaInfo.

**Additional context**
None

**Comment by ta264** [comment]
Closing for same reasoning as #5496 - we don't want to add filters based on properties of the file
