### ISSUE TITLE
Radarr 3.0.0.4204 (docker) not accepting path when movie is added, but accepts path when edited

### ISSUE THREAD

**Issue by prunhardt** [Radarr/Radarr#5518]
**Describe the bug**
In Radarr for docker I have to add a movie to the database with a path in the config folder before I can change the path to what I want it to be

**To Reproduce**
1. Add path /movies to the container, pointing to /home/pi/movies, path /config for /home/pi/docker/radarr/config and /extracted for /home/pi/downloads/complete)
2. Run Radarr
3. Try to add a movie with path /movies: that will fail with error "invalid path".
4. Stop the container
5. Add another path e.g. /moviesconfig, pointing to home/pi/docker/radarr/config/movies
6. Add a movie with path /moviesconfig. That will work
7. Edit the path for the added movie to /movies, that will work

**Expected behavior**
I expected the path /movies to be accepted as a valid path when a movie is added.

**Screenshots**

**Platform Information (please complete the following information):**
 - OS: Ubuntu 20.10
 - Docker: Yes
 - Mono or.NET Core Version: [e.g. Mono 5.8 or .Net Core 3.1.10] (found under System -> Status): Net Core 3.1.10
 - Browser and Version [e.g. chrome 86.0.4240.198] (Only needed for UI issues) Firefox 83.0 (64 bit(
 - Radarr Version: 3.0.0.4204, package 3.0.0.4204-ls86
 - Radarr Branch: master
[radarr.txt](https://github.com/Radarr/Radarr/files/5660657/radarr.txt)
[radarr.trace.txt](https://github.com/Radarr/Radarr/files/5660659/radarr.trace.txt)
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/5660661/radarr.debug.txt)

**Trace Logs**
Turn on Trace logs under Settings -> General and wait for the bug to occur again. **Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**

**Comment by bakerboy448** [comment]
Those paths are suboptimal and likely permissions issues; see this.
https://wiki.servarr.com/Docker_Guide
