### ISSUE TITLE
Add "Preferred" section to Indexer Restrictions

### ISSUE THREAD

**Issue by edru** [Radarr/Radarr#552]
Can we get a preferred option? I like to have DTS as preferred, but not required, that way it cycles through DTS releases before AC3. Right now we can only require, or restrict, words.

Settings, Indexers - Restrictions section.

(Apologies if this is a duplicate. I could have sworn I had seen something like this before, but search was turning up nothing)

**Comment by onedr0p** [comment]
Can't you set in your quality profile to have DTS preferred?

![image](https://cloud.githubusercontent.com/assets/213795/22495901/1506dc1a-e813-11e6-8cc5-a998f3b8cfd8.png)

**Comment by galli-leo** [comment]
Already implemented
