### ISSUE TITLE
Missing PUT api/v3/moviefile/{id} API

### ISSUE THREAD

**Issue by acortelyou** [Radarr/Radarr#5520]
**Is your feature request related to a problem? Please describe.**

The v1 API allows PUT's to the MovieFile endpoint to change the quality.

The v3 API does not have a documented PUT method for the MovieFile endpoint.

**Describe the solution you'd like**

It would be helpful if the v3 MovieFile endpoint supported PUT's as well.

This can be used to mark files for replacement when the quality cutoff was previously considered as met.

**Describe alternatives you've considered**

Adding the PUT verb to the moviefile API is the most straightforward way to solve this, but perhaps alternatively/additionally:

A version of the MovieSearch command that optionally ignores the quality cut off requirements for a given movieId?

**Additional context**

MovieFiles aren't always what they originally seem to be: wrong FPS, bad bitrate, bad sync, etc.

**Comment by rg9400** [comment]
I'm pretty sure it does support PUTs. I use it in my code below to update the MovieFile language based on MediaInfo

```python
import requests
import json

##################################### CONFIG BELOW #####################################
RADARR_API_KEY = ""
RADARR_LOCAL_URL = 'http://radarr:7878/radarr/' # Make sure you include the trailing /
#########################################################################################


### CODE BELOW ###
radarr_language_url = '{}api/v3/language?apikey={}'.format(RADARR_LOCAL_URL, RADARR_API_KEY)
radarr_languages = requests.get(radarr_language_url).json()
for radarr_language in radarr_languages:
    del radarr_language['nameLower']

radarr_movie_url = '{}api/v3/movie?apikey={}'.format(RADARR_LOCAL_URL, RADARR_API_KEY)
radarr_movies = requests.get(radarr_movie_url).json()

downloaded_movies = list(filter(lambda x: (x['sizeOnDisk'] > 0), radarr_movies))
for movie in downloaded_movies:
    movie_file = movie['movieFile']
    movie_file_id = movie_file['id']
    languages = movie_file['mediaInfo']['audioLanguages']
    languages = set(languages.replace(" ", "").split("/"))
    new_languages = []
    for language in languages:
        id = next((radarr_language for radarr_language in radarr_languages if radarr_language['name'] == language), None)
        if id:
            new_languages.append(id)
    if not new_languages:
        new_languages = [{'id': 1, 'name': 'English'}]
    movie_file['languages'] = new_languages
    update_url = '{}api/v3/movieFile/{}?apikey={}'.format(RADARR_LOCAL_URL, movie_file_id, RADARR_API_KEY)
    update_movie = requests.put(update_url, data=json.dumps(movie_file))
```

**Comment by bakerboy448** [comment]
The API docs are still a bit of a work in progress; feel free to PR to add what’s there using the existing format.

Just because it isn’t documented (for the moment) doesn’t mean it isn’t there :)

Closing

**Comment by acortelyou** [comment]
Oh, that's great!

I thought it had been removed.

v3 is looking sweet.
