### ISSUE TITLE
This page isn’t working ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by julio8a** [Radarr/Radarr#5521]
**Describe the bug**
Everything was working fine, I had the UI for Radarr and was able to add and obtain with no problem. However, out of the blue, I think due to an update? The page (UI) doesn't load at all anymore. I never had this problem before and I've been using Radar for 6 months or so.

**To Reproduce**
1. Start up Radarr

**Expected behavior**
Interact with the Radarr UI.

**Screenshots**
![image](https://user-images.githubusercontent.com/6144462/101541775-b9140600-3956-11eb-905b-ca82b4968f69.png)
![image](https://user-images.githubusercontent.com/6144462/101541834-c9c47c00-3956-11eb-9f1d-9cba767f8f78.png)

**Platform Information (please complete the following information):**
Raspberry PI4
I'm on docker.

**Trace Logs**
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------

          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io

-------------------------------------

To support the app dev(s) visit:
Radarr: https://opencollective.com/radarr
To support LSIO projects visit:
https://www.linuxserver.io/donate/

-------------------------------------
GID/UID
-------------------------------------
User uid:    1000
User gid:    1000
-------------------------------------
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

**Comment by bakerboy448** [comment]
https://wiki.servarr.com/Radarr_FAQ#I-am-using-a-Pi-and-Raspbian-and-Radarr-will-not-launch

> ### if you are unsure go to our Reddit or Discord first. Exceptions do not mean you found a bug!
