### ISSUE TITLE
Loading Messages

### ISSUE THREAD

**Issue by McGeaverBeaver** [Radarr/Radarr#5523]
**Is your feature request related to a problem? Please describe.**
Now that V3 is being used, this was the first time I have seen this message..  Some folks might not know this is just a loading message.. I understand it's a joke but can cause some confusion. "   'Congratulations! you are the 1000th visitor.', " 

https://github.com/Radarr/Radarr/blob/develop/frontend/src/Components/Loading/LoadingMessage.js

**Describe the solution you'd like**
Would it be possible to turn on or off custom loading messages?

**Describe alternatives you've considered**
Remove  'Congratulations! you are the 1000th visitor.',

**Additional context**

**Comment by bakerboy448** [comment]
I’m not sure if there’s that much of a concern here; the page is clearly not a pop up and you’re only looking at those messages for a few seconds.

**Comment by McGeaverBeaver** [comment]
If it's not a big deal, then why is it not a big deal to remove it?   Stating it's clearly not a popup , that's not fact you don't know how I use my systems and how it's ben presented to a user.. This is indeed run on an iframe via a main site , so yes to the user it DOES look as a popup.. Not sure why such a nasty attitude also? Because no one else complained it's not much of a concern? Sound's like you're the creator of the "joke" and I have offended your poor taste  of humor.

**Comment by mwberry** [comment]
I have to agree, this is a really bad joke. Especially given the sort of supply chain attacks that have been in the news lately. I didn't see the message directly, my roommate did. When they told me about it I assumed the worst and was about to shut the whole server down. But I figured I'd quick check if the string appeared in the source code. They thought it said 10,000th visitor though so I didn't initially get any search hits. Was sweating bullets for a few seconds. The rest of the loading messages seem benign enough.

This reminds me of the ill-fated [Lineage April Fools joke](https://www.androidauthority.com/lineageos-april-fools-852705/)

**Comment by McGeaverBeaver** [comment]
Similarly the same is what happened to me, yet for some reason we can't even talk about options, such as just being able to turn off the message.. not difficult to add, they just seem to not care and think it's funny..

**Comment by bakerboy448** [comment]
> Sound's like you're the creator of the "joke" and I have offended your poor taste of humor.

Try looking at the history of the file before blaming people.

https://github.com/Radarr/Radarr/commits/develop/frontend/src/Components/Loading/LoadingMessage.js

but if it is a big deal then rather than complaining why not make the effort to make a PR to modify it and see if it gets merged.

also I think sonarr has a similar message does it not?
