### ISSUE TITLE
Trakt list is not synchronizing

### ISSUE THREAD

**Issue by CarliToes4** [Radarr/Radarr#5524]
**Describe the bug**
Hi, I link my Trakt account and my Trakt Watchlist to Radarr. Nevertheless, when I add a movie on this list, I am compelled to synchronize manually the list (by editing it, then clicking on save)

**To Reproduce**
1. I sync a public Trakt list or my Trakt watchlist with Radarr
2. I add a film to this list
3. I wait for hours
4. My list is not synchronizing and the added movie doesnt come to my Radarr library
5. I sync manually my list
6. The movie is finally coming to my Radarr library

**Expected behavior**
I want that my list synchronize every 10 minutes around to add automatically the movie from it to my Radarr Library without any interrraction

**Screenshots**
![chrome_ry4zWtV178](https://user-images.githubusercontent.com/41182776/101685784-75112600-3a68-11eb-9922-8ff8e7b30855.png)

**Platform Information (please complete the following information):**
 - OS: [e.g. Windows 10 2004 / Ubuntu 20.10]
 - Docker: [Yes/No]
 - Mono or.NET Core Version: [e.g. Mono 5.8 or .Net Core 3.1.10] (found under System -> Status)
 - Browser and Version [e.g. chrome 86.0.4240.198] (Only needed for UI issues)
 - Radarr Version [e.g. 3.0.0.2956]
 - Radarr Branch [e.g. master]

**Trace Logs**
[](https://www.writeurl.com/text/b25ahpde6jr8veyqln1j/n22pevbfew7ozy0jqckz
)
https://www.writeurl.com/text/b25ahpde6jr8veyqln1j/n22pevbfew7ozy0jqckz

**Comment by CarliToes4** [comment]
Sorry i forgot
OS: Windows 10 1990
Docker : No
.NET Core : Yes (3.1.10)
Browser : Chrome
Radarr Version : 3.0.0.4204
Radarr Branch : Settings --> Lists

**Comment by ta264** [comment]
Minimum sync interval is 6 hours. We are keeping this under review but no plans to make it any shorter currently. If you want to add a movie to radarr immediately use the radarr UI

**Comment by CarliToes4** [comment]
Is there a way to sync more frequently ?

**Comment by ta264** [comment]
No

**Comment by CarliToes4** [comment]
Even with the api ?

**Comment by bakerboy448** [comment]
Everything you can do in the UI, including kicking off tasks, is doable via the API.  Check your browser’s dev console if we still haven’t added what you’re looking for to the api docs
