### ISSUE TITLE
Movie titles that contain leading periods/ellipsis do not get renamed properly

### ISSUE THREAD

**Issue by codeclem** [Radarr/Radarr#5526]
For example, the movie `...And Justice For All` gets renamed to `.And Justice For All` with a single leading period, which causes it to be a hidden file in Linux.

**Comment by austinwbest** [comment]
There is already an open issue & PR for this.

**Comment by codeclem** [comment]
Thanks. Do you have a link so I can follow it?

**Comment by bakerboy448** [comment]
PR
https://github.com/Radarr/Radarr/pull/4509

Duplicate of #4350
