### ISSUE TITLE
Keep colons

### ISSUE THREAD

**Issue by John-Gee** [Radarr/Radarr#5528]
Hello,

**Is your feature request related to a problem? Please describe.**
We have options on how to deal with colons in Media  Management Settings, I think it'd be nice if we could have the option to keep them as well, I sometimes put them manually in the files/folders' names and it never caused any issue..

**Describe the solution you'd like**
Radarr to add an option to leave colons as they are.

**Describe alternatives you've considered**
Renaming manually.

**Additional context**
N/A

Thanks!

**Comment by bakerboy448** [comment]
support nightmare; they cause windows to crap itself.

no plans for this.

very limited use case.

**Comment by John-Gee** [comment]
The use case is that the folder matches the files that matche the title, I think that's quite nicer/cleaner.
Since I don't run Windows, I don't see the point of being limited by what it does not support, but I wouldn't mind for the option to be hidden somehow (having to edit the conf manually, add input parameter, etc) if that helps.
