### ISSUE TITLE
Radarr v3: filtering on "missing" does not show missing unmonitored

### ISSUE THREAD

**Issue by schullq** [Radarr/Radarr#5533]
Radarr version 3.0.0.4235.

On the main page showing the movie list, when trying to filter on "missing" movies, I only see the missing monitored movie, when I would like to see the unmonitored "missing" as well. I'm pretty sure that this was working that way on Radarr v2, but now it's not anymore on Radarr v3.

![image](https://user-images.githubusercontent.com/16139542/101881685-0e3d5b00-3b95-11eb-970e-7d4314762763.png)
When filtering on missing, I can't see the unmonitored missing (yellow tag)

![image](https://user-images.githubusercontent.com/16139542/101881790-362cbe80-3b95-11eb-9328-947458e6a7cb.png)
And I have some in this status (here there's no filtering)

**Comment by bakerboy448** [comment]
@geogolem do we have a true dupe on this? I know I’ve seen some filter discussions and I think you were apart of them?

**Comment by ta264** [comment]
dupe #4626, done this way following #3717

**Comment by schullq** [comment]
Alright I see. Don't know why this decision has been made, but ok.

According to the legend, there are two types of missing. I don't get why the unmonitored missing are not showing in the missing filter. Or maybe if you would keep it that way, maybe add an "Missing only (unmonitored)" filter.

**Comment by ta264** [comment]
If a movie is not monitored, it can't be missing because you've told radarr you don't want it.

**Comment by geogolem** [comment]
Yes, this seems to have been discussed before... Different people have different understanding or preference with respect to the Missing or Wanted filters...

My suggestion in the past was actually to ship Radarr with almost no preset filters and allow the user to create their own Missing or whatever filters via custom filters... this would avoid confusion and allow the user to make it do whatever they want...  but I understand it is nice to have some presets there for basic usage... Of course users can still create new filters and name them how they want, but as it is now, there is no way to actually remove or disable the basic filters that come preset.

**Comment by austinwbest** [comment]
Yea, it'll have to ship with filters. Support nightmare if not with constant filter questions.

I do think/agree missing & wanted need a tweak but not removal
