### ISSUE TITLE
Processing torrents: if a hardlink fails, optionally attempt to move the file before copying it.

### ISSUE THREAD

**Issue by cbussa** [Radarr/Radarr#5534]
**Is your feature request related to a problem?**
I'm using a remote ruTorrent / NZBGet seedbox sending files to rclone (GDrive), while the radarr process is running on my local network accessing the same rclone area. Things work fine in this mode using NZB:

- the NZB file is locally fetched and sent to the remote NZBGet, 

- the target file is downloaded remotely and then moved to a local/remote shared area using cron/rclone on a high bandwidth link, 

- a remote path mapping then allows local radarr to access the identical remote rclone import area.  

- the file is examined and (since hardlinks don't work) actually moves and renames it to it's final remote directory via rclone.  

Everything is automatic and just great without actually downloading the files.

But not so with torrents -- a similar process occurs, but because the hardlink fails, the local radarr only has the copy option and uses bandwidth to download the file while immediately uploading it to the target directory.  I'm running remotely _exactly because_ I don't really have the upload bandwidth; a single 5G file takes an hour (in my case) as opposed to a file move which is nearly instantiations, as with NZBs.

It's irksome that one mode (NZBs) work quickly and fine while the other (torrents) doing "the exact same thing" ends up with a radically different process.

**Describe the solution you'd like**
I'd like an advanced option (hidden and disabled for normal usage) that allows _either_ a copy **_or_** move to occur when a hardlink fails with torrents.  It probably wouldn't be an either/or; if the move itself somehow fails you'd need to fall back to the copy.

**Describe alternatives you've considered**
By running radarr on the seedbox, this problem is of course eliminated, but in my case requires a different seedbox.  Also, drop all torrents and stick to only NZBs.   Currently the few times I use torrents, I'm manually moving files around and importing -- irksome since NZBs fetch and process just fine without any help.  Also, wait until rclone/GDrive supports hardlinking.

**Additional context**
By leaving COPY as is and having a disabled MOVE function, this doesn't change the current functionality at all.  By placing it in the advanced section and disabled, hopefully no one will enable with without understanding what it's doing to/for torrents; descriptive text would help.  And by having an additional option between hardlink and copy, this allows for faster processing on success while still providing the same copy actions if not.

Also sending this to the Sonarr team since it has the exact same issue.  Thanks.

**Comment by bakerboy448** [comment]
Don’t write directly to mounts.

Use issue, not a bug.

https://wiki.servarr.com/Cloud_Setup

**Comment by cbussa** [comment]
I'm not writing directly to mounts; that's what the cron/rclone job is for -- occasionally it checks for new data, and then copies them to a staging area visible by both systems.

Hadn't seen that page / site, thanks!

**Comment by cbussa** [comment]
How does mergerfs (I assume what you're proposing, which is a good local-only solution) solve the torrent copy problem?   The unprocessed torrent files have been placed on rclone and when processed **will** be copied since they're torrent files.  Remember, radarr is far away from the actual file, so a local mergerfs won't do anything / has the exact same bandwidth problem, while the mergerfs on remote isn't visible.

And only a "rclone copy" is writing, but rclone mount IS renaming and moving files around within the directory structure. (AFAIK radarr doesn't directly write file data but only moves and renames so that shouldn't be a problem.)
