### ISSUE TITLE
Some movie titles cause huge query for all movie

### ISSUE THREAD

**Issue by bekon16** [Radarr/Radarr#5535]
Hi,

I would like to report a bug. 
I have the newest radarr version (os: newest Debian) connected with usenet indexers.
I have added movie using imdb:tt12515958 - this issue is related only to this particular movie.
When movie is added, radarr in "Search" tab return data related to all movies in library - it is almost killing my browser tab - which is pretty normal because it is resposnse for huge query made by radarr.

Before that I have spotted few more titles related to this problem but dont remember exactly know which one (this is not a one-time incident). I think issue can be reproducable by adding imdb:tt12515958 and searching for available movies to download.
All other 99% titles works as expected.

I have added hundred of movies on previous version of radarr and it always  searched for correct movie or just returned message "no found".

Can someone check whats going on with this? To confirm the bug simply add  imdb:tt12515958 to library, search for movies and wait for output.

If you have any question, just let me know.

**Comment by bakerboy448** [comment]
More than likely not a bug.

Every time we’ve seen this it’s the indexer or indexers returning garbage results
