### ISSUE TITLE
Sort on specific path

### ISSUE THREAD

**Issue by rinzes** [Radarr/Radarr#5541]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
right now I'm able to sort  on "Path" but I have several paths that I would like to sort on

**Describe alternatives you've considered**
NA

**Additional context**
DNA

**Comment by ta264** [comment]
I'm afraid I have no idea what you're asking for, can you give a concrete example?

**Comment by rinzes** [comment]
The sort on Path with filter does what I'm looking for
