### ISSUE TITLE
Disable scanning Unmonitored movies in daily Refresh Movie task

### ISSUE THREAD

**Issue by matijaerceg** [Radarr/Radarr#5543]
It is frustrating that a large rclone+gdrive library takes a super long time (over an hour) to scan, every day.

**My request: It would be nice if Unmonitored movies were not included in the daily Refresh Movie task.**

I am considering finding a hack to disable this daily task altogether, but it would be nice if there was a built-in way to reduce the load of the daily Refresh Movie task, because, unlike for some people, it doesn't take a couple minutes for my large library, it takes a really long time.

[AB#715](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/715)

**Comment by austinwbest** [comment]
Yea.. I tried a couple times to get something implemented upstream that would allow for a way to do this (lock it out archive it). Was rejected & simply isn't gonna happen there.

Have to decide if we want to make a way for radarr to do it regardless of what upstream does. Really up to Q on that one.

**Comment by matijaerceg** [comment]
I feel you on the TVDB ego-trips. But we digress.

As far as the daily Refresh Movie task is concerned, I believe that it will only become more of an issue as more people start to use cloud storage. On a local drive, scanning 10k files isn't a huge deal. But that many hits on a cloud storage mounted drive is pretty intense. 

If we can't change the way that task runs, I'm hoping with this request that we can at least lessen its impact, as most movies I have in radarr will never need to be automatically upgraded by Radarr (I'm talking 90%+), so there's no point in scanning them every single day. It would be nice not to just remove the movie from Radarr altogether, so that's why my request is to just skip scanning Unmonitored ones.

Why is it scanning Unmonitored movies in the first place?

**Comment by bakerboy448** [comment]
For posterity and others:

Check your rclone mount settings many people use rclone mounts without any issue

issue is likely using rclone’s default api key which Rclone itself and every guide I’ve seen explicitly recommends not doing

**Comment by bakerboy448** [comment]
Also, how large is your library?

Have you compared your rclone mount settings with the various guides out there?

**Comment by matijaerceg** [comment]
_Also, how large is your library?_
14k

_Have you compared your rclone mount settings with the various guides out there?_
I literally paid Animosity022 from the rclone forums and author of the best rclone setup guides for Plex to look at my setup himself. I could not have more thoroughly checked my rclone setup.

**Comment by fryfrog** [comment]
It seems very likely that GSuite unlimited is going away, so this isn't going to continue to be a problem much longer. It would be wise to think about a future plan for when the cut off happens. They've changed the terms to remove mention of unlimited and set an end date for Google Photos too. I've got my 🤞 they don't.

**Comment by matijaerceg** [comment]
@fryfrog do you have a link to info about this?

**Comment by fryfrog** [comment]
https://workspace.google.com/terms/user_features.html

> Customers that have 5 or more End Users will receive a total amount of Google Drive storage equal to 5TB times the number of End Users, with more storage available at Google's discretion upon reasonable request to Google. Customers that have received a Google for Nonprofits discount or have 4 or fewer End Users will receive 1TB storage in total for Google Drive, Google Photos, and Gmail combined for each End User.

https://blog.google/products/photos/storage-changes

*Right now*, shared drives are still "unlimited" on both old GSuite accounts and *new* Workspace ones. So who knows for sure. But to me and others, it really looks like the writing is on the wall.

**Comment by Dulanic** [comment]
Agreed, there should be a option to customize in the settings.

**Comment by bakerboy448** [comment]
@Dulanic no plans to significantly customize the settings.  Would you like to handle the deluge of support requests when people break their installs and question why things don’t work? 

Rescanning movies Chan be changed from always to just on import or never so the file is only scanned in import or never, but regardless the metadata would still refresh

@Qstick any input as far as what our appetite is here?

**Comment by Dulanic** [comment]
@bakerboy448 God no lol, but at the same time, it makes it my server bog down and buffer all the time because of the tons of activity. I have 5K+ items at ~ 30TB it has to scan, So not sure what my alternative is? I can't imagine if you put it in a hidden "advanced" setting, that it would cause questions? So while it may not be commonly used, there is a valid use case here.

I mean I guess I can setup a cron job to customer the sqlite DB every day, but that is quite a workaround just to change how often it scans.

**Comment by bakerboy448** [comment]
@Dulanic try changing this setting to manual.

https://wiki.servarr.com/Radarr_Settings#File_Management

That should keep automatic refresh to only metadata which should have much lower IO usage.

**Comment by austinwbest** [comment]
This comes down to a status of locked or archived being added to just keep it in there for history without updating anything for it.

Tried to get this added for about a year in sonarr as well, was rejected multiple times. Also discussed it for radarr and was decided against as well.

**Comment by bifa2** [comment]
I've just started experimenting with a Docker image of Radarr for testing / api development purposes and this is such a painful thing to have happening every single time I start the container. Running an update against 3000+ movies is taking at least 10 minutes (and additionally, this impacts Bazarr downstream as it updates from Radarr and refreshes everytime Radarr scans a movie, making it unusuable til that's done).

**Comment by bakerboy448** [comment]
> Running an update against 3000+ movies is taking at least 10-15 minutes

https://wiki.servarr.com/radarr/faq#can-i-disable-the-refresh-movies-task

**Comment by bakerboy448** [comment]
Closing; no plans for this at this time.

https://wiki.servarr.com/radarr/faq#can-i-disable-the-refresh-movies-task

should cover almost all use cases
