### ISSUE TITLE
System Health Status Notification and Error Reporting Feature

### ISSUE THREAD

**Issue by gist901** [Radarr/Radarr#5551]
Hi all,

First all I would like to give a big thanks to the people who are responsible for maintaining and improving this software!

A feature that I would like to see put into place is the ability to generate system reports and notifications. For me this software is great because once I have everything is configured properly, I can pretty much just walk away and not need to check in on it. However I do find occasionally it does run into an error, IE yesterday it lost connection to Jackett so it had no indexers for almost 24 hours.  I do believe the issue resolved itself on its own. 

So this bring up my request, it would be nice to have the ability to setup system health reports and to be notified if the system is experiencing an error. It would be awesome to get a text message saying: Hey your system has been running for 8 days with no major errors to report, or to get an email telling me that Radarr can't connect to my downloaders or can't find indexers, etc.

Thanks again for the awesome work guys and I hope to see this implemented.

Best,
gist

**Comment by bakerboy448** [comment]
Take a look at the various options in Settings -> Connect for notification methods

Closing pending additional information on specific notification methods that are not supported.

FYI Webhook acts as a good catchall
