### ISSUE TITLE
Core version unable to write to windows share mounted with cifs 

### ISSUE THREAD

**Issue by skaynl** [Radarr/Radarr#5554]
Hi, I'm new at Radarr (always used couchpotato) but I'm trying to install it and configure it. At first I had an old manual installing Radarr on Ubuntu and used Mono to run it. Everything worked fine. Later I however saw the status message "Please upgrade to the .NET Core version of Radarr" So seeing I didn't really configure much jet I deleted the old Radarr folder and .config folder under the Radarr user to start fresh.
One of the first things I tried to configure is setting the blackhole folders for nzb and torrent files. This however didn't work, You get the error "can not write to folder" and a 0kb file with the name "radarr_write_test.txt" in the folder I selected
So I'm stuck now, with mono it works and trying with sudo -u radarr I can create and delete files and folders fine in the mounted folder, seems that it's not the folder permissions causing this error but something else connected to the core system???

please let me know if you need any more information , maybe the cifs options from fstab I used are any help:
//"ip of windows server 2016"/Downloads   /Downloads         cifs  vers=3.0,uid=user,gid=user,credentials=/etc/.cifspasswd,file_mode=0666,dir_mode=0777     0       0

hope you can help with this issue, for now I'm trying the mono version to get to know radarr a little bit.

**Comment by SitramSoft** [comment]
I have a similar issue when trying to configure radarr to use a samba share from an ubuntu server. I logged in to the container in a bash terminal with the user under which radarr runs and I was able to create/delete files and folders in the smb share(mapped with -v from the host to the container). When I try to configure that location in the Media Management I get the error "can not write to folder" and a 0kb file with the name "radarr_write_test.txt" in the folder I selected.
