### ISSUE TITLE
Sort movies in folders

### ISSUE THREAD

**Issue by Vince0511** [Radarr/Radarr#5559]
**Describe the solution you'd like**
I would like the possibility to rename/replace movies in sorted folder based on tags. 
For example:

`share/movies/{Movie Collection}/{Movie Title1}/movie1-file`
`share/movies/{Movie Collection}/{Movie Title2}/movie1-file`
`share/movies/{Movie Collection}/{Movie Title3}/movie1-file`

or 'just' by year

`share/movies/2012/{Movie Title}/movie-file`
`share/movies/2013/{Movie Title}/movie-file`
`share/movies/2014/{Movie Title}/movie-file`

If this is allready a posibility, I'm very sorry to open up this Feature request. I could not find it in Radarr, or on the other topics.

**Comment by bakerboy448** [comment]
Turn on advanced settings and check out media management; you can configure your folder naming accordingly (including sub folders)
