### ISSUE TITLE
Ultra Minor -> Copy button doesn't work when grabbing API key

### ISSUE THREAD

**Issue by vortexrap** [Radarr/Radarr#556]
Minor issue with copy functionality on the API key under settings.

Also - Thanks so much for putting the preferred tags 👍 👍 👍

**Comment by onedr0p** [comment]
Works for me in Chrome, FF and Edge.

**Comment by vortexrap** [comment]
Looks like the issue exists only when accessing sonarr/radarr behind Muximux. Copy/Paste works fine accessing the application directly.

Thanks!
