### ISSUE TITLE
Allow {Original Title} and variants for Movie Folder Format

### ISSUE THREAD

**Issue by DesktopMan** [Radarr/Radarr#5560]
**Describe the solution you'd like**
{Original Title} works for file renaming, would be nice if it also worked for folder renaming.

This worked in v2 but in v3 it defaults back to Title.Year.

**Describe alternatives you've considered**
Don't think any apply.

**Comment by bakerboy448** [comment]
See #5426

{Original Title} is a file property which cannot be used in movie folders.

**Comment by DesktopMan** [comment]
> 
> 
> See #5426
> 
> {Original Title} is a file property which cannot be used in movie folders.

That was closed as it wasn't a bug. I'm adding it as a feature request. Shurely using file properties in the folder name isn't unusual.

**Comment by bakerboy448** [comment]
it actually was a bug and it was closed; nowhere on the chain does it not indicate there wasn't a bug.

Feature Request closed as it won't happen.

>The folder can not use file properties.

Namely the biggest issue, other than the massive headaches it caused on v0.2 as it only worked right if the correct settings were set....ignoring the database corruption.  Having multiple files per movie (i.e. 4k and 1080p) as planned would not be compatible with such a feature.
