### ISSUE TITLE
Notifications from Radarr to DC++..?

### ISSUE THREAD

**Issue by 4C3T** [Radarr/Radarr#5564]
I'm curious if there's any way to forward a "downloaded"-message to a ADC client?
There is an option for custom scripts under Connections, and there's a script that I installed on my hub which uses the CLI "!addrel <category> Title".

I know this maybe require a third party software. I have no idea, but I do get a lot of these.
I know that DC is a dying art, but it doesn't prevent it from being useful either - Would actually be very nice if there was a way to use it as a Download client too! Minimum requirements should be ADC-compliant hub though.
I do think a couple of 100 people would be happy to see both features implemented (Also I think it could be an incentive for others to use Radarr!). As you know, Radarr can spout quite a few "Movie imported"  , and this is tedious to do manually.

**Comment by ta264** [comment]
You could do this with a custom script. I don't think we have any appetite to add it as a native notification.

**Comment by bakerboy448** [comment]
Legitimate question: and why doesn’t a custom script work?

unlikely this would be added, but I’ll let the dev team address that

**Comment by 4C3T** [comment]
I don't know how I would go about this.
I need to be able to receive that notification somehow, an API of some kind, and then some way to relay that to DC if I want as close to realtime update.

There are supposedly Hub-scripts, as I gathered from a DC-user (who just sort of tossed me a bone about it, but haven't gotten back with any details yet), which, somehow, do a search for most recent files or something like that.

I tried google it, but my Google Fu isn't that good, and I only got irrelevant results, so I thought I'd ask here where the expertise is

**Comment by nls44** [comment]
Feel free to check this out: https://github.com/nls44/Radarr-AirDCPP. I try to stay updated with Radarr :)

**Comment by 4C3T** [comment]
> 
> 
> Feel free to check this out: https://github.com/nls44/Radarr-AirDCPP. I try to stay updated with Radarr :)

This looks promising, but I can't see a readme-file (There is one, but not of the "normal kind"), and I'd like to know a little more how it works.
I must admit, that at the time of writing this, I'm fresh off the bus from a bit of shopping groceries, so I'm a bit tired and not firing on all cylinders, as it were, but I just had a quick look, and it seem like an off-shoot or fork as it's called here, of Radarr.
I'll have to download it and install it to find out I guess, but still, it'd be nice with some more how-to's  on the page.
Perhaps a few screenshots too would perhaps look better too.

**Comment by nls44** [comment]
Ah, I totally understand, I'll add some screenshots and instructions to the README to make everything a lot more clear. I'll ping you here when it's done.

**Comment by nls44** [comment]
> > Feel free to check this out: https://github.com/nls44/Radarr-AirDCPP. I try to stay updated with Radarr :)
> 
> This looks promising, but I can't see a readme-file (There is one, but not of the "normal kind"), and I'd like to know a little more how it works.
> I must admit, that at the time of writing this, I'm fresh off the bus from a bit of shopping groceries, so I'm a bit tired and not firing on all cylinders, as it were, but I just had a quick look, and it seem like an off-shoot or fork as it's called here, of Radarr.
> I'll have to download it and install it to find out I guess, but still, it'd be nice with some more how-to's on the page.
> Perhaps a few screenshots too would perhaps look better too.

Done!

**Comment by 4C3T** [comment]
Ok. That looks better.
So, it looks like this is installed then use it to sort of mirror via the mounts-stuff mentioned...

One question though:
It appears you only share one directory - How does that work with multiple drives?

Also, I find it difficult to manage those pesky network mounts. About 1½ years ago, or something, I managed to get it to work, and I ran it for a short while until I swapped hardware and whatnot, then run it locally since then.

It's quite messy and contradictory in which order they're supposed to be (\\network-pc\share\etc & x:\share\etc\, not to mention which slash you're supposed to use: / or \).

I read the Wiki (or something) a while back after I'd moved my Radarr to another computer, but never got it to work.
Partially because of Windows 7 Lite (Radarr, etc) vs. Windows 7 Home Basic (Disks-host).

I just wish they'd allow network drives straight off to eliminate the hassle. In Linux, sure, N/P, but I don't want to run Linux on my disk-server.
I like Linux, but it's a bastard to get working properly, and it has difficulties to work with Windows network and a few other things.
Also, the whole UI feel isn't ultimate. The guys who develop these have still much to learn from Windows. They all need to stop with the graphics crap too, but that's another matter in itself.

I'm still currently running Win 7 Home Basic on the file-server, due to limited resources (Core2, 8GB 15x disks), so it's not exactly the fastest of computers. Radarr, Sonarr, Bazarr and µTorrent is sucking the most out of the CPU 24/7, but it works, most of the time. I would have loved to run XP on it, but nothing's compatible nowadays I'm afraid.

So, there are three questions then, to summarize it:

Can be installed on basically any computer and connects any AirDC client to any Radarr-client then?
Multiple drives?
Getting network shares to work?

**Comment by 4C3T** [comment]
Just downloaded the entire thing.
I put it directly under C;\Radarr-AirDCPP-develop
Went to the dir setup, and opened CMD (So that I can monitor it), and ran the build.bat, and I got this:

"(c) 2018 Microsoft Corporation. Med ensamrätt.

C:\Users\Administratör>cd C:\Radarr-AirDCPP-develop\setup

C:\Radarr-AirDCPP-develop\setup>build.bat

C:\Radarr-AirDCPP-develop\setup>#SET BUILD_NUMBER=1
'#SET' is not recognized as an internal or external command,
operable program or batch file.

C:\Radarr-AirDCPP-develop\setup>#SET branch=develop
'#SET' is not recognized as an internal or external command,
operable program or batch file.

C:\Radarr-AirDCPP-develop\setup>inno\ISCC.exe radarr.iss
Inno Setup 5 Command-Line Compiler
Copyright (C) 1997-2012 Jordan Russell. All rights reserved.
Portions Copyright (C) 2000-2012 Martijn Laan
Inno Setup Preprocessor
Copyright (C) 2001-2004 Alex Yackimoff. All rights reserved.

Compiler engine version: Inno Setup 5.5.4 (a)

[ISPP] Preprocessing.
[ISPP Warning] ISPPBuiltins.iss file was not found.
Error on line 29 in C:\Radarr-AirDCPP-develop\setup\radarr.iss: Column 76:
[ISPP] Undeclared identifier: "Framework".
Compile aborted."

It didn't like the first two rows in the .bat file:
#SET BUILD_NUMBER=1
#SET branch=develop

And it seem that this line is the culprit, somehow:
"OutputBaseFilename=Radarr.{#BranchName}.{#BuildVersion}.windows.{#Framework}"
Tt says ISPPBuiltins.iss can't be found either.

**Comment by 4C3T** [comment]
Just tried downloading Inno Setup Compiler 6.1.2 and it didn't like that line with "{#Framework}" either...

You should perhaps include pre-compiled install files too

**Comment by nls44** [comment]
Hi, I'll answer your questions when I'm back at the PC. You can download the binaries for Windows of the latest release: https://github.com/nls44/Radarr-AirDCPP/releases/tag/radarr-airdcpp-0.1

**Comment by 4C3T** [comment]
Ok. I was a bit surprised that there were no actual installer, but I managed to just execute the ServiceInstall.exe and it added it as a service and started it.
Got it up and running, added AirDC as both indexer and download client. <-The latter will be interesting to see. Also, still curious as how I can get this sucker to announce new arrivals in AirDC... The main idea was to have it call a announcer script. Something that I expect will more or less flood it, if I ever get this to work that is...

Now I need to make it connect to my network drives.
I tried using the both the UNC paths (// and \\ ip.address / \ path /\etc) and locally access paths (z:\path\etc) in all possible combinations, but it just won't budge. Not even the slightest. It's either wrong or invalid path.

I hate this crap with Radarr and Sonarr. Why the heck can't it just use the drive letters!!? Sure, the network can go down, but, so can a computer too, so what's the diff...

**Comment by 4C3T** [comment]
How weird...  It automatically updated to latest version, and all of the sudden, neither the indexers nor download clients are accessible. The log shows a few errors
`2020-12-19 02:25:46.4|Fatal|RadarrErrorPipeline|Request Failed. GET /api/v3/downloadclient

[v3.0.1.4259] System.ArgumentNullException: Value cannot be null. (Parameter 'returnType')
   at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
   at NzbDrone.Core.ThingiProvider.ProviderRepository`1.Query(SqlBuilder builder) in D:\a\1\s\src\NzbDrone.Core\ThingiProvider\ProviderRepository.cs:line 63
   at NzbDrone.Core.Datastore.BasicRepository`1.All() in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 87
   at NzbDrone.Core.ThingiProvider.ProviderFactory`2.All() in D:\a\1\s\src\NzbDrone.Core\ThingiProvider\ProviderFactory.cs:line 39
   at Radarr.Api.V3.ProviderModuleBase`3.GetAll() in D:\a\1\s\src\Radarr.Api.V3\ProviderModuleBase.cs:line 57
   at Radarr.Http.REST.RestModule`1.<set_GetResourceAll>b__34_0(Object options) in D:\a\1\s\src\Radarr.Http\REST\RestModule.cs:line 152
   at Nancy.NancyModule.<>c__DisplayClass14_0`1.<Get>b__0(Object args)
   at Nancy.NancyModule.<>c__DisplayClass16_0`1.<Get>b__0(Object args, CancellationToken ct)
   at Nancy.Routing.Route`1.Invoke(DynamicDictionary parameters, CancellationToken cancellationToken)
   at Nancy.Routing.DefaultRouteInvoker.Invoke(Route route, CancellationToken cancellationToken, DynamicDictionary parameters, NancyContext context)
   at Nancy.Routing.DefaultRequestDispatcher.Dispatch(NancyContext context, CancellationToken cancellationToken)
   at Nancy.NancyEngine.InvokeRequestLifeCycle(NancyContext context, CancellationToken cancellationToken, IPipelines pipelines)`

A restart didn't help either so...

**Comment by bakerboy448** [comment]
@4C3T 
Please keep comments relevant to the GHI


Support Requests -> [Reddit](https://www.reddit.com/r/radarr/) or [Discord](https://discord.gg/r5wJPt9)

**Comment by austinwbest** [comment]
Ok, so it does seem that the comments are related to the new direction of this GHI (starting after ta closed it).. The only problem is from what i can tell this has spun into someone creating their own fork of radarr to include some indexer & download client (which is fine).

The error appears to be related to the fork updating to the real radarr version and now those custom things added for this client/indexer are going into a tailspin because the real radarr has no clue wtf they are.

So with that said, since this is a fork there is no support here for it. I really dont want to keep getting emails and what not related to a fork so i would recommend jumping to the github page related to the fork and spinning up a GHI there and keep your support questions there as well since we dont support custom builds (use at your own risk).
