### ISSUE TITLE
Make the 'original' language option in Quality Profiles menu more visible 

### ISSUE THREAD

**Issue by jt196** [Radarr/Radarr#5568]
**Is your feature request related to a problem? Please describe.**
In Quality Profiles, the **Original** language option isn't in correct order on dropdown list - currently it's sandwiched between Norwegian and Polish. Personally I didn't even know it was there until I had saw warnings next to foreign language films and dug around to find a solution. 

**Describe the solution you'd like**
Can I suggest the 'Original' option get moved up the menu to the top above the other languages? I only found it as I was looking for it. Personally I think this should be the default option, and 'Any' second on the menu, with all the other languages below. 'Meta' options should be at the top of the list of languages, not hidden within them. 

**Additional context**
![Screenshot 2020-12-17 at 15 07 07](https://user-images.githubusercontent.com/8290163/102505174-929e4b00-4079-11eb-91e6-27992f45c67c.png)

**Comment by JohnBednarczyk** [comment]
Working on this

**Comment by jt196** [comment]
Excellent. Sure you're on it but something like

- Any
- Original
- ---
- Afrikaans
- Albanian
- etc

Makes sense to me to default on Original and have 'any' right above or below it. Any other languages below with maybe a separator line if you can be arsed.

**Comment by Danskleraftiva** [comment]
> Excellent. Sure you're on it but something like
> 
> * Any
> * Original
> 
> * Afrikaans
> * Albanian
> * etc
> 
> Makes sense to me to default on Original and have 'any' right above or below it. Any other languages below with maybe a separator line if you can be arsed.

thanks for adding this as an issue.  i also didn't know that "original" was an option because it was in alphabetical order vs a priority order.

**Comment by derinbay** [comment]
I'm using radarr for about 3 months but didn't know that there was an original option. I was trying to search a feature request for adding this Original option and see this ticket :)

It would be a very good UX improvement.
