### ISSUE TITLE
Can you add Aria2 to the download client?

### ISSUE THREAD

**Issue by 0x01x0** [Radarr/Radarr#5569]
Can you add Aria2 to the download client?

[AB#732](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/732)

**Comment by bakerboy448** [comment]
no plans for this

and closing regardless due to not following the template

**Comment by Qstick** [comment]
Seems like it supports torrent, and has a API. So no reason it couldn't be added fairly easily.

But yeah you need to use the FR template.

**Comment by bakerboy448** [comment]
Had a corresponding old Sonarr issue.

We punted there as there was effectively no interest by users for several years and I would say the same thing here.

**Comment by austinwbest** [comment]
So, its ok that Markus doesn't have any desire to do it, but we cant use that as a factor to insta-close a FR. There may be some interest in the Radarr community for it or a user might even do it. Doesn't hurt to leave it open for awhile and see if there is enough interest in it to warrant the time. Just add a tag for low priority or open to whoever wants to do it kinda thing and let it simmer.

**Comment by bakerboy448** [comment]
regardless; still need the template that was blown away filled out; @0x01x0 

template can be found here https://github.com/Radarr/Radarr/issues/new?assignees=&labels=feature+request&template=feature_request.md&title=

**Comment by bakerboy448** [comment]
and for posterity

xref: recent sonarr GHI https://github.com/Sonarr/Sonarr/issues/4172

xref legacy sonarr, no signifcant interest 2016 through 2020 GHI https://github.com/Sonarr/Sonarr/issues/1374
