### ISSUE TITLE
Add or Remove Quality Profiles 

### ISSUE THREAD

**Issue by madvtak** [Radarr/Radarr#558]
Hi all,

This is more than likely a feature request, i searched the opened and closed issues and i did not find this one. Also I may not be aware if this is already possible. 

So in CouchPotato you are able to set the movie profile/qualities, which you able to do the same in Radarr. Where they differentiate, as far as i can tell, you can enable and disable which type of profile/qualities it will grab. 

Shown in my screenshot below, screener and R5 profiles are unchecked, so when a movie i added to my want list is available it will show everything that is available  but those that are unchecked.

Is it possible to have Radarr do the same thing? Right now within Radarr you can set the size limits for each of the quality definitions, but you cannot disable or enable them. I have "Arrival" on my wanted list in Radarr, i received notifications showing that it has downloaded but not in the quality i have specified. 

![image](https://cloud.githubusercontent.com/assets/18261123/22496589/d8321a1a-e7ff-11e6-9be1-30530a2418de.png)

I do have it as HD-720P but everything that Radarr grabbed are not the ones i would like. If you're suggestion is to "add WEB-DL or HEVC" to the ignore list. i don't think thats the correct step lol. 

Anyways, as always i am happy to see a Couch Potato alternative growing as fast as Radarr is. I haven't kept up much with the other one "watcher". Thanks for all that you devs do, you're awesome!!! 

 
CP Profiles 
![image](https://cloud.githubusercontent.com/assets/18261123/22496384/262e196e-e7fe-11e6-8154-bf842476ba29.png)

Radarr Profiles

![image](https://cloud.githubusercontent.com/assets/18261123/22496413/5856cfda-e7fe-11e6-95da-29e4d266441c.png)

**Comment by onedr0p** [comment]
You can add or remove quality profiles, I am not really understanding your request...

![image](https://cloud.githubusercontent.com/assets/213795/22497245/3a549376-e81e-11e6-8a78-bbfe3f8a21bc.png)

**Comment by madvtak** [comment]
And there we have it, closing. That's what i was wanting. Thanks!
