### ISSUE TITLE
Radarr doesnt clean up after an update

### ISSUE THREAD

**Issue by Arathen** [Radarr/Radarr#5581]
**Describe the bug**
When Radarr performs an update on Linux using the built-in updater, it leaves behind a /tmp/radarr_update directory which can be around 500MB in size. Looking at https://github.com/Radarr/Radarr/blob/f90133d588a075f35e9ecb102269c2ec84ec4fe3/src/NzbDrone.Core/Update/InstallUpdateService.cs#L115 it seems this directory only ever gets cleaned up at the start of an update, never afterwards, so it hangs around forever essentially. While 500MB may not seem like much, this can add up on a headless linux server, and in conjunction with Lidarr (which does the same thing) has now filled my /tmp partition a few times. It would be nice if Radarr cleaned up after an update, perhaps on first run or as an element of housekeeping.

**To Reproduce**
1. Run an update on Linux using the built-in updater.
2. sudo du -skh /tmp/radarr_*

**Expected behavior**
Either clean up after an update, on first restart, or as part of housekeeping. Give the user a configuration toggle to choose this behaviour for extra credit.

**Screenshots**
```
[arathen@fedora2 /tmp]$ du -skh radarr_*
26M     radarr_backup
447M    radarr_update
```

**Platform Information (please complete the following information):**
 - OS: Fedora 33 server
 - Docker: No
 - Mono or.NET Core Version: .Net Core 3.1.10
 - Browser and Version: Chrome
 - Radarr Version: 3.0.1.4271
 - Radarr Branch: nightly

**Comment by bakerboy448** [comment]
https://github.com/Radarr/Radarr/commit/94591dea939c6d9c278f65a7b6fe31f4a6458340#diff-28ac805e6226e9bc97f6d5e0cd96844b55d33d0391985c49ea60ae8de255a4de

https://github.com/Radarr/Radarr/commit/6de847a361404033408cfbeee23bfb1ffef77ba3#diff-28ac805e6226e9bc97f6d5e0cd96844b55d33d0391985c49ea60ae8de255a4de
