### ISSUE TITLE
Radarr v3: Failed to map movie

### ISSUE THREAD

**Issue by gelato** [Radarr/Radarr#5585]
**Describe the bug**

The movie title goes like Angry Birds 2 в кино The Angry Birds Movie 2 and Radarr expects it strictly to be "Angry Birds 2 в кино" or The Angry Birds Movie 2, it can't just search one of them inside the name when autosearching. In v2 we had parser settings for this (lenient, etc), but can't find anything like that in v3.

**To Reproduce**
Search movie with bilingual naming scheme

**Expected behavior**
Radarr v3 will match movie name from database with part of the name from the indexer and successfully map it.

**Screenshots**
<img width="799" alt="scr" src="https://user-images.githubusercontent.com/1236528/102702809-027a2480-4278-11eb-9f29-1ddfebfee1ae.png">

**Platform Information (please complete the following information):**
 - OS: Ubuntu 18.04
 - Docker: No
 - Mono or.NET Core Version: .NET Core Yes (3.1.10)
 - Browser and Version: Safari
 - Radarr Version 3.0.1.4259
 - Radarr Branch master

**Comment by bakerboy448** [comment]
Not a bug; radarr uses TMDB for alt titles

also
Support Requests -> [Reddit](https://www.reddit.com/r/radarr/) or [Discord](https://discord.gg/r5wJPt9)


add the title as an alt title at TMDB
Wait a minute
Refresh the movie in radarr and you should be good

**Comment by gelato** [comment]
@bakerboy448 Movie is added automatically via lists... Radarr rejects movie name consisting from 2 names in different language, like Том и Джерри Tom and Jerry - it will reject this movie because it expects only one of them - Том и Джерри or Tom and Jerry, not both. And every movie in my country has 2 names in naming scheme - one original name and otheer translated name. Radarr v2 cold work with this by setting parser leniency.

**Comment by bakerboy448** [comment]
Again, add the alt title to TMDB

no plans to change the parser

we can’t help it if your indexer can’t name releases in anything remotely close to standard format.
