### ISSUE TITLE
Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Request body too large.

### ISSUE THREAD

**Issue by fhedstrom** [Radarr/Radarr#5587]
I did an upgrade on Radarr to 3.0.1.4259 and my whole database was empty. After that, I upgraded Net Core (https://wiki.servarr.com/System_status#update-to-net-core-version) but when I wanted to restore my old database I get the following error: 

Connection id "0HM4ULOHUIOEE", Request id "0HM4ULOHUIOEE:00000001": An unhandled exception was thrown by the application.: Request body too large.

https://pastebin.com/Jq8j1u96

My old database is 57.4 MB and it seems like there is a limit to Kestrel in AspNetCore to 28,6 MB as described here:

https://github.com/dotnet/aspnetcore/issues/20369

**Comment by bakerboy448** [comment]
please fill out the template you blew away and provide the radarr trace logs
(ps if you didn't blow away the template, what is the exact link / method you're using to open the GHI; there should only be two options and blank issues w/o the template like this are supposedly blocked)
![image](https://user-images.githubusercontent.com/55419169/102720159-4db42780-42b8-11eb-80dc-4a2363ae771e.png)

**Comment by fhedstrom** [comment]
Sorry for not using the template. Could you delete this and I will post it in two parts, first the database which disappeared and secondly the feature request of changing Asp Net Core to allow bigger files than 28,6 MB.
