### ISSUE TITLE
Sample code for Custom Scripts

### ISSUE THREAD

**Issue by 4C3T** [Radarr/Radarr#5588]
Sorry if this is the wrong place for it, but I'm going out of my mind here trying to find the correct answers.

I'm looking to make a very simple script for sending a message to a client (AirDC++, via Curl command), a very short and simple string including login credentials, category and downloaded file.

I did try google sample code for Radarr in all possible ways I could think of, but I didn't find anything that I could use.
Also, running the Windows version for Radarr.

Only scripts that I could find were for Linux bash, some information about which tags I could use, but nothing that showed me the syntax and/or what's necessary to run a such script.

Some pointers would be greatly appreciated. Thanks.

**Comment by bakerboy448** [comment]
https://wiki.servarr.com/Radarr_Tips_and_Tricks#Custom_Post_Processing_Scripts

[Discord](https://discord.gg/r5wJPt9) for further talks
