### ISSUE TITLE
URL Base /movie conflict

### ISSUE THREAD

**Issue by neox387** [Radarr/Radarr#5603]
URL Base /movie conflicts with opening a movie item wich results in You must be lost, nothing to see here.
This was not an issue in the previous radarr before the new ui look
This bug is not present in latest sonarr v3

no url base
http://xxx/movie/xxx

url base /test
http://xxx/test/movie/xxx

url base /movie
http://xxx/movie/xxx

You must be lost, nothing to see here.
Manually changing to http://xxx/movie/movie/xxx does open the item.

**Comment by bakerboy448** [comment]
https://github.com/Radarr/Radarr/issues/5555  when deconflicted and merged will fix this

**Comment by neox387** [comment]
ok thank did not see
