### ISSUE TITLE
Get priority to personal score

### ISSUE THREAD

**Issue by navycrow** [Radarr/Radarr#5608]
Hello,
From what I know, the quality of the video takes priority over the personal score. Most of the time that's fine with me but sometimes it doesn't and I'd prefer my personal rules to come first.
Is it possible to deactivate the possibility of upgrading according to quality while leaving the possibility of upgrading according to our personal rules.
Or failing that, to prioritize our personal rules over quality rules ?
Thx

**Comment by bakerboy448** [comment]
Closing;

- template not filled out
- if you want to use custom formats over quality then group all your qualities together....be careful you’ll need to handle qualities within their CFs
