### ISSUE TITLE
activity screen stuck

### ISSUE THREAD

**Issue by pengocha** [Radarr/Radarr#5609]
**Describe the bug**
Lately the activity screen in my gui keeps loading (the moving orbs) No matter how long i wait or on every browser i use.
This happens on multiple devices (windows 10 and android). Movie search seems not affected by this.
My radarr and sonarr are running along side each other on a raspberry pi dietpi os. Sonarr is ok.
Any way i can fix this?

**Platform Information (please complete the following information):**
 - OS: Windows 10 / Android
 - Docker: [No]
 - Mono or.NET Core Version: 6.12.0.107
 - Radarr Version 0.2.0.1504

**Comment by ta264** [comment]
Upgrade, v0.2 is out of support now. If you still have an issue on v3 you can jump on the discord channel for support
