### ISSUE TITLE
Radarr not passing properly titles to jackett (special characters not handled)

### ISSUE THREAD

**Issue by t2pierre** [Radarr/Radarr#5620]
**Describe the bug**
Trying to find movie in French (title = "Le père noël est une ordure") with torrent9 indexer in jackett.
Radarr is converting special characters before passing title to jackett: "Le pere noel est une ordure" > resulting to a no found

**To Reproduce**
0. having previously configured the "torrent9" tracker thru jackett
1. Add new Movie "Le père noël est une ordure"
2. Do manual search
3. empty result

**Expected behavior**
doing a search directly in jacket (torrent) with "le père noël est une ordure" returns 2 positive results

**Platform Information (please complete the following information):**
 - OS: synology DSM 6.2
 - Docker: No
 - Mono or.NET Core Version: 5.20.1.34-16
 - Browser: chrome
 - Radarr Version: 3.0.0.4204
 - Radarr Branch: develop

**Trace Logs**
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/5739693/radarr.debug.txt)

**Comment by ta264** [comment]
Duplicate #4502
