### ISSUE TITLE
Add 'Show Release Date' option to all views

### ISSUE THREAD

**Issue by alaneo** [Radarr/Radarr#5622]
Hi, please could you add a Show Release Date option to all views? I know there is a Digital and Psychical Release dates in Table view but those are not working, for example for Avatar 2. Many thanks Alan

**Comment by austinwbest** [comment]
OK bud, you need to provide examples, screenshots etc

Explain what isn't working, show what you want where you want it.

**Comment by alaneo** [comment]
Hi, please see example belowe:

When I add for example movie Avatar 2 then I can see the Release Date when I hoover the mouse pointer over the date:

![image](https://user-images.githubusercontent.com/36469942/103166829-303a0d00-4826-11eb-97f5-15a281c6a54d.png)

But when I go to the movie list when the Table View is selected including the Digitial Release or Psychical Release checkboxes in Overveiw Options there is no date.

![image](https://user-images.githubusercontent.com/36469942/103166853-77280280-4826-11eb-972a-8d478bec35b3.png)

My future request is to add this Release Dates into the Overwiev Options for all Views - if possible.

![image](https://user-images.githubusercontent.com/36469942/103166999-b30f9780-4827-11eb-9ed5-e939bcfa5b9c.png)

**Comment by bakerboy448** [comment]
Reopening, pending review

**Comment by Qstick** [comment]
The release you see is an in cinemas date, add that column to your table view and you'll see it.

**Comment by austinwbest** [comment]
> The release you see is an in cinemas date, add that column to your table view and you'll see it.

I think this was about the other dates being seen as well or instead of only cinema?

**Comment by Qstick** [comment]
All dates can be seen in table view... OPs example above was looking in detail view which was showing in cinema date for that particular case, but he was only looking at release and digital in table view claiming the date couldn't be seen, when he should have also looked at In Cinema column.

**Comment by alaneo** [comment]
Hi, yes the "In Cinemas" date is what I was looking for in Table view - many thanks for this. Could the "In Cinemas" date be also included in "Posters" and "Overwiev" views please?
