### ISSUE TITLE
Radarr v3: Unmonitored color is wrong in Posters view

### ISSUE THREAD

**Issue by flecamus** [Radarr/Radarr#5623]
Radarr v3.0.1.4259

Hello!

It seems like Unmonitored in Posters and Overview views have the incorrect color underneath. They are red instead of being orange.

<img width="286" alt="Screen Shot 2020-12-24 at 20 42 48" src="https://user-images.githubusercontent.com/34439360/103104851-192ecb80-462a-11eb-84e6-8f8a5642e4a5.png">

In Table view, Unmonitored are orange as the legend suggests:
<img width="122" alt="Screen Shot 2020-12-24 at 20 44 35" src="https://user-images.githubusercontent.com/34439360/103104852-1a5ff880-462a-11eb-82a0-05d53ccbe8ec.png">

**Comment by austinwbest** [comment]
This bug has been fixed for about 3 months, sitting in a PR :)

**Comment by Qstick** [comment]
You'd probably have better luck getting it merged at Sonarr :P

**Comment by austinwbest** [comment]
> You'd probably have better luck getting it merged at Sonarr :P

One may think being on the team helps lower that wait time, but uhm... 😜

**Comment by bakerboy448** [comment]
> > You'd probably have better luck getting it merged at Sonarr :P
> 
> One may think being on the team helps lower that wait time, but uhm... 😜

It does  😝 
must be a support team thing 🤷‍♂️
