### ISSUE TITLE
Movies containing a colon won't turn up on search if colon is missing in title

### ISSUE THREAD

**Issue by hollandschevisch** [Radarr/Radarr#5628]
When a movie contains a colon and in the title no colon is present, the movie won't be found by Radarr.

1. For example Captain America: Civil War is added.
2. In Radarr there are results, but not all. If the title misses the colon in the indexer, it won't be found by Radarr. Manual search in the indexer also shows Captain America Civil War (without the colon).

**Expected behavior**
Is it possible to also add the results when no colon is present.

**Comment by austinwbest** [comment]
Radarr doesn't do any searching, it passes the query along to be searched. So in this case, your indexer can't handle it and doesn't return results it would seem.

**Comment by hollandschevisch** [comment]
In that case. Is it possible to let the indexer search without the colon? Instead of Captain America: Civil War just Captain America Civil War.
Is this is a possibility and if not is there a workaround?

**Comment by bakerboy448** [comment]
As austin noted; not a radarr bug
