### ISSUE TITLE
Add an option to auto rename the year in movie folders if it changes

### ISSUE THREAD

**Issue by simonk83** [Radarr/Radarr#5630]
**Is your feature request related to a problem? Please describe.**
Sometimes, the movies release year changes after you've added it to Radarr (for example, WW1984 was originally 2019, but changed to 2020). As the folder name never changes, this throws off the Plex movie matching, as it takes the year from the movie folder and tries to match on that (and fails). 

**Describe the solution you'd like**
It'd be great if an auto rename job could be added, maybe as part of the Refresh Movie job? So while it's checking for other changes (date, title etc), check for a new release date, and if it differs then auto rename the folder.

**Describe alternatives you've considered**
It's possible to do this manually, but it's not ideal and a bit cumbersome (you have to remember to do it occasionally for starters). It's easier just to wait for the plex match to fail and then update that manually, but obviously being automated would be great.

**Comment by rg9400** [comment]
While this Feature Request could be useful, another alternative to guarantee Plex matching (with the new agent) regardless of year is to use the below in your filename

`{imdb-{ImdbId}}`

**Comment by simonk83** [comment]
Oh right! So add imdb id to the actual filename? Does Plex match now check the filename as well (I thought it was just folder)? To be fair I haven't really looked into the new agent, let me have a poke around.

**Comment by rg9400** [comment]
Yes, it looks as filename as long as you use the format above (works with tmdb as well). Only works using the new native agent. I think even allowing an option to rename a folder in Radarr is not simple, so doing it automatically may not be something that will be added soon. This is a better workaround in the meantime anyways as it helps prevent issues with movies with the same title and year, i.e. `The Call (2020)`

**Comment by simonk83** [comment]
Yep, this'll work perfectly and totally solves the problem, thanks for that 👍

**Comment by Silent-Remux** [comment]
Hey, you there, you're finally awake.

https://github.com/l3uddz/movearr
