### ISSUE TITLE
Movie scheduled for release not on the calendar

### ISSUE THREAD

**Issue by AlienProber** [Radarr/Radarr#5632]
I'm running a Arch based OS and am using the nightly releases of Radarr. I noticed the other day that Escape Room 2 is not listed on the calendar even though it's added to Radarr and all the information I see says it will be released to theaters on 01-01-2021. Any idea why it may not be being listed on the calendar? Thanks

**Comment by bakerboy448** [comment]
Support Requests -> [Reddit](https://www.reddit.com/r/radarr/) or [Discord](https://discord.gg/r5wJPt9)
https://www.themoviedb.org/movie/585216-escape-room-2/releases?language=en-US

**Comment by AlienProber** [comment]
Thanks for the info. I was looking for that to see if the rest of the info out there was wrong., but in the future I strongly suggest you keep the arrogance to yourself.

**Comment by bakerboy448** [comment]
What that meant to state/come as was the source of your knowledge was wrong 

not necessarily your fault! I see even google is listing it wrong on their knowledge card 😅

but for future reference of anyone stumbling here: radarr gets its info from TMDb
