### ISSUE TITLE
Integration link with Pushover claims to be Sonarr

### ISSUE THREAD

**Issue by MikeBishop** [Radarr/Radarr#5635]
**Describe the bug**
When configuring Pushover notifications, Radarr links into setting them up with the name and icon of Sonarr. It should be distinct.

**To Reproduce**
1. Go to Settings > Connect > + > Pushover
2. Scroll to API Key
3. Click on More Info
4. See page for setting up Sonarr notifications

**Expected behavior**
Prepopulated page with Radarr info, not Sonarr

**Comment by bakerboy448** [comment]
https://github.com/Radarr/Radarr/blob/80a744eff5cd686b7fb082684896846c28e5e6f2/src/NzbDrone.Core/Notifications/Pushover/PushoverSettings.cs#L29

Closing; per code notes, appears to be Pushover that needs to make changes first.

If they've created a Radarr page, let me know and I can reopen then it would be a true bug :)

**Comment by Qstick** [comment]
Pretty sure we have to drive this

**Comment by Qstick** [comment]
Found our old Lidarr application and have submitted one for Radarr. Once they make it public we can switch it over in code. Thanks for reporting.

**Comment by Qstick** [comment]
They've added it to their integration page now, so should be good to fix the code reference to

https://pushover.net/apps/clone/radarr
