### ISSUE TITLE
Core net version on Ubuntu 20.10 has multiple permissions issues not present in identical mono install

### ISSUE THREAD

**Issue by elegantalchemist** [Radarr/Radarr#5638]
**Describe the bug**
Cannot add a root folder or check local disk space in net.core version but can in mono version - everything else remains default/unchanged apart from renaming old Radarr folder and replacing with new net.core version in /opt as per upgrade instructions.

Radarr net.core installed in /opt/Radarr folder, all settings left to default - NOT running as service, manually started each time from terminal to minimise bug potential variables from systemd.

Adding media management root folder to a NAS mounted in fstab - error that folder is not writeable by user. Folder is mounted with noperm and owned by the same user that is running radarr.

Root folder mounts fine in mono version but not net.core so not an underlying permissions issue. Only change is mono/net.core version of Radarr - can switch back and forth in seconds and reproducible.

net.core version also unable to query API to get local diskspace. Mono version on identical install does this fine.

**To Reproduce**

- Install Radarr net.core version Ubuntu 20.10 leave all settings as default.
- Run from command line to start:  /opt/Radarr/Radarr -nobrowser
- Navigate to browser, media management and use folder in NAS attached with fstab with owner being the same user as Radarr is running under and the noperm tag tested to be working (other users can read/write fine).
- Radarr says: Path: Folder is not writable by user andrew
- User andrew is the owner of the folder mounted via fstab with full read/write permission and the user running Radarr
- rename /opt/Radarr to /radarrOLD and install/unzip the mono version folder to /opt/Radarr to replace the same install with default settings. Config files (~/.config/Radarr) left untouched.
- Run the mono version with $ /usr/bin/mono --debug /opt/Radarr/Radarr.exe -nobrowser
- Navigate to browser, media management and add NAS identical to before - adds fine and with no errors given

- All other variables remain same which confirm not an underlying permission issue - mono version can write to folder but net.core version cannot in the same install.
- Error also extends to querying local disk space, mono version shows local disk free space fine, net.core version throws error about unable to access API/Diskspace.

**Expected behavior**
Should be able to mount a NAS folder mounted via fstab with noperm - mono can, net.core can't in an identical install.

user is owner and has rw all of /opt/Radarr and /.config/Radarr folders

**Platform Information (please complete the following information):**
 - OS: Ubuntu 20.10 Groovy Gorilla
 - Hardware - Intel NUC8i5
 - Docker: No
 - NET Core Version: Yes (3.1.10)
 - Radarr Version 3.0.1.4259
 - Radarr Branch - manual download latest tar.gz from releases page

**Trace Logs**
https://pastebin.com/JxFcM9NY - trace log add root folder on Mono version (working)
https://pastebin.com/A93AdgSS - trace log NOT working (net.core version)

**Comment by ta264** [comment]
You haven't told us how the Nas drive is mounted, SMB or NFS or something else? I suspect this is fixed in nightly builds.

**Comment by elegantalchemist** [comment]
Sorry - it's using CIFS-Utils to a SMB access (v3) on a synology NAS.

The fstab mount file line is:

//192.168.1.70/Plex /home/username/media/ cifs uid=1000,gid=1002,credentials=/var/lib/plexmediaserver/.mountaccess,iocharset=utf8,noperm,vers=3.0 0 0

UID 1000 is the user which runs Radarr as well so has full ownership, confirmed in mounted folder properties.

I'm very happy to try a nightly build - easy to drop into the /opt/Radarr folder. Where can I find these? Or do I need to change the update branch inside radarr itself?

**Comment by elegantalchemist** [comment]
I'm going to close this as the problem/bug is solved in recent nightlies (mount CIFS shares write permissions broken) and multiple issues are confusing - i'll open seperate reports for others
