### ISSUE TITLE
"4K" Releases are parsed as in the quality of 480p

### ISSUE THREAD

**Issue by kSotin** [Radarr/Radarr#5639]
**Describe the bug**
Releases with titles that contain "4K" are parsed as in the quality of 480p, causing unexpected rejection. 

**To Reproduce**
1. Execute a normal release search, either automatically or manually. 
2. "4K" releases are parsed as 480p. 

**Expected behavior**
"4K" releases should be parsed as in the quality of 2160p. 

**Screenshots**
<img width="1202" alt="image" src="https://user-images.githubusercontent.com/57791410/103294270-7fea2580-4a2c-11eb-867b-21d1cd9181d1.png">
The lower "WEB-DL 4K" release is parsed as WEBDL-480p, while the upper "WEB-DL 1080p" release is parsed correctly. 

**Platform Information (please complete the following information):**
 - Radarr Version 3.0.1.4259
 - Radarr Branch master

**Comment by austinwbest** [comment]
As im pretty sure "4K" isn't something being looked for (and likely wont be), this isn't a bug. This is an issue with a group/person not putting 2160 in the release name as they should. Since it is able to find web-dl but no actual quality it defaults to 480

Can check if 4K is mapped to 2160 and not matching or if we will map or leave it

**Comment by monsn0** [comment]
Version: 3.0.1.4259
Package Version: 3.0.1.4259-1 by radarr 
.NET Core: Yes (3.1.10)
Docker: Yes

I'm experiencing virtually the same issue yet the release does have "2160p" in its name.
1080p as well as other resolutions appear to be working as expected from same source.
Please see my screenshots and clipped debug log below (Just an example, but happens to all "2160p" releases from YTS).

![image](https://user-images.githubusercontent.com/27322762/103467102-925cab80-4d19-11eb-8e9b-998dbe46101d.png)

![image](https://user-images.githubusercontent.com/27322762/103467104-95f03280-4d19-11eb-89ad-7db807987ee9.png)

-----------------
2021-1-2 16:12:19.4|Debug|Parser|Parsing string 'Resident.Evil.Retribution.2012.2160p.BRRip-YTS'
2021-1-2 16:12:19.4|Debug|Parser|Movie Parsed. Resident Evil Retribution - 2012 
2021-1-2 16:12:19.4|Debug|Parser|Release Group parsed: YTS
2021-1-2 16:12:19.5|Debug|Parser|Languages parsed: Unknown
2021-1-2 16:12:19.5|Debug|QualityParser|Trying to parse quality for Resident.Evil.Retribution.2012.2160p.BRRip-YTS
2021-1-2 16:12:19.5|Debug|Parser|Quality parsed: Bluray-480p v1
2021-1-2 16:12:19.5|Debug|Parser|Edition parsed: 
2021-1-2 16:12:19.5|Debug|ParsingService|Language couldn't be parsed from release, fallback to movie original language: English
2021-1-2 16:12:19.5|Debug|AcceptableSizeSpecification|Beginning size check for: Resident.Evil.Retribution.2012.2160p.BRRip-YTS
2021-1-2 16:12:19.5|Debug|AcceptableSizeSpecification|Item: Resident.Evil.Retribution.2012.2160p.BRRip-YTS, meets size constraints
2021-1-2 16:12:19.5|Debug|AlreadyImportedSpecification|Performing already imported check on report
2021-1-2 16:12:19.5|Debug|LanguageSpecification|Checking if report meets language requirements. English
2021-1-2 16:12:19.5|Debug|MaximumSizeSpecification|Maximum size is not set.
2021-1-2 16:12:19.5|Debug|MinimumAgeSpecification|Not checking minimum age requirement for non-usenet report
2021-1-2 16:12:19.5|Debug|QualityAllowedByProfileSpecification|Checking if report meets quality requirements. Bluray-480p v1
2021-1-2 16:12:19.5|Debug|QualityAllowedByProfileSpecification|Quality Bluray-480p v1 rejected by Movie's quality profile

**Comment by bakerboy448** [comment]
@monsn0 A+ on providing the info needed!

got it https://github.com/Radarr/Radarr/blob/56b658cc96bb58df1c67cce1cb6ec3ce48358deb/src/NzbDrone.Core/Parser/QualityParser.cs#L326

we don't handle 2160p for BRrips, so it falls back to 480p.  should be an easy fix

**Comment by bakerboy448** [comment]
@austinwbest 4k is checked in the parser, but doesn't look for H265

**Comment by TheKronzo** [comment]
this happens for me too, I like to rename my movies as 4k instead of 2160p buit radarr sees it as 480p and redownloads

**Comment by feellikealot** [comment]
I'm having a similar bug where it is detecting 4k DolbyVision as 720p and causing nothing to be downloaded. Is this the same bug
![image](https://user-images.githubusercontent.com/78455666/106683926-4d2ad400-657a-11eb-8e91-836a005cf647.png)

**Comment by bakerboy448** [comment]
@feellikealot yup looks like it; 

just tested and `Spectre 2015 UHD BluRay DolbyVision MP4 Multi H265-d3g`  is parsed as 2160p BR in my PR

**Comment by feellikealot** [comment]
@bakerboy448 any eta on it being merged?

**Comment by monsn0** [comment]
@feellikealot if you manually download the release, it should parse it correctly once it finishes downloading.

**Comment by wheelerlaw** [comment]
@bakerboy448 This is not fixed:

![image](https://user-images.githubusercontent.com/3081566/107261342-34ed0600-6a0d-11eb-8033-40329339a35a.png)
