### ISSUE TITLE
Request: Add option to rename to movies to all lowercase and into directory of the same name

### ISSUE THREAD

**Issue by mrjack711** [Radarr/Radarr#564]
Hi,

My movies are all stored in the format of:

/movies/movie.name.1080p.2003.dts.group/movie.name.1080p.2003.dts.group.mkv

I have all movies in their own directories within the master movies directory and everything is lowercase.
I keep the same name as the release, just all uppercase characters are changed (manually) to lowercase.
They're all in their own separate directories to allow for things like movie extras and subtitles etc to be stored with them and show up nicely in plex.
The lowercase thing is just a preference of mine.

Is there any chance of adding lowercase and "directory of the same name" options in the renaming preferences?

Thanks

**Comment by onedr0p** [comment]
In the mean time, create a script to scan a directory and rename the files to lowercase and set it on a cron to run every 12 hours :)

For example:
`find /path/to/root/folder/ -exec perl-rename -n 'y/A-Z/a-z/' "{}" \;`

You'll get a verbose output of the file/folders being renamed, remove the `-n` in the `find` command and the files and folders will be renamed.

**Comment by schumi2004** [comment]
Should such functionality be really in Radarr? It's there for renaming options (if i'm correct) 
Just use a script like onedr0op suggested or grab a copy of bulk renaming tool and rename them.
This are imo 1 time actions and shouldn't be in Radarr, doesn't have anything to do with core functionality.

**Comment by mrjack711** [comment]
Thanks, and i take it this will rename the folders and files?

**Comment by onedr0p** [comment]
Yes, be careful though. Make sure you have the result you want with the -n flag before running it.

**Comment by onedr0p** [comment]
Closing this, as I believe it can be taken care of by the user.
