### ISSUE TITLE
Restarting from within browser/console gets stuck

### ISSUE THREAD

**Issue by elegantalchemist** [Radarr/Radarr#5640]
**Describe the bug**
If I restart Radarr from within the web browser (for example a port change or add authentication which forces a restart) it doesn't come back up.

Running systemctl start or restart radarr brings it back up fine. Seems like the internal restart call is having an issue.

Systemctl status has a log of errors but nothing is recorded in the trace logs (verified time from systemctl and trace logs have a big gap until maual restart)

**To Reproduce**
Change something which forces an internal restart. Happens every time.

**Expected behavior**
Should restart not hang.

**Platform Information (please complete the following information):**
 - OS: Ubuntu 20.10
 - Docker: No
 - Mono or.NET Core Version:.Net Core 3.1.10
 - Radarr Version 3.0.1.4330
 - Radarr Branch nightly

**Trace Logs**
Trace log has a gap for this error so not helpful. Pastebin below is of the systemctl monitor error logs.

https://pastebin.com/6bqSvg3a

**Comment by austinwbest** [comment]
https://github.com/Radarr/Radarr/pull/5416

Going to group it with the open PR for restart issues.
