### ISSUE TITLE
Can't access free space on local hardrive - API call fails no permission

### ISSUE THREAD

**Issue by elegantalchemist** [Radarr/Radarr#5641]
**Describe the bug**
.net core ONLY

When you navigate to the 'system' tab the information about local drive free space is absent. When viewing this page Radarr throws an error/exception which isn't present in the Mono version and isn't present if you run the radarr.service as root:root.

The user running in radarr.service for this error definitely owns both opt/Radarr and ~/.config/Radarr so it's not a permission error on the user side - no idea where the API folders and files being referenced are. have tried making a new user radarr:radarr and running under that and same issue happens.

**To Reproduce**
View the system folder - Radarr throws an error - not a fatal one, can't get disk space API call fails no permission.
Doesn't happen if run as root:root in radarr.service. Doesn't happen in an identical mono version so looks like a .net core bug

**Expected behavior**
Should get disk space API call without having permission issues

**Screenshots**

**Platform Information (please complete the following information):**
 - OS: Ubuntu 20.10
 - Docker: No
 - Mono or.NET Core Version: .Net Core 3.1.10
 - Radarr Version 3.0.1.4259
 - Radarr Branch master

**Trace Logs**

https://pastebin.com/tLdMZj6T

Happens a few times here. no visible error in the UI and not fatal but shows up in systemctl status and the logs.

[AB#1014](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1014)

**Comment by bakerboy448** [comment]
The paths to the code on the error are just the drive that it was on when built.  If you want to poke at the code you’d go from src/ onward and then it shows which file and the line number(s)

It does work, so it’s either a case not considered or something weird with your OS/setup.

on mobile else I’d be poking around with more info

**Comment by elegantalchemist** [comment]
I've not modified anything on the OS - it's plain Ubuntu 20.10 fairly new install.

If I swap the opt/Radarr folder out with the Mono version it works fine with user:user.

If I change .net core Radarr itself to run under root:root it works fine also - it seems like a permission error (systemIO calling the internal API? I don't have access to this, I presume this is something radarr controls and sets up itself?

Would it be sueful to delete the files which are listed and let radarr recreate them in case it's an unpack error or something?

**Comment by elegantalchemist** [comment]
Closing this - did a fresh install of UBUNTU and it's gone away and works fine.

Somewhere, something has stuffed up the .net core permissions to call the API for disk space but given that Radarr only specifies it needs two folders (/opt/Radarr and ~/.config/Radarr) this issue is a bit frustrating. Why does Radarr only say it can be run as a 'normal user' when this clearly isn't a perfect case is a permission deep in an API call gets stuffed up it can't be reset by a new install of Radarr?

**Comment by elegantalchemist** [comment]
OK problem reocurred

Flat minimal reinstall of Ubuntu 20.10, installed Radarr using manual install of .net core version only and it all worked fine. Could get the local diskspace. Also have installed sonarr, Plex, sabnzbd. Seemed all to be playing nice

Noticed an error that said: MediaInfo Library could not be loaded Unable to load shared library 'libmediainfo.so.0' or one of its dependencies - no problem - my install is missing the MediaInfo so apt-get mediaInfo installs fine.

Restart Radarr and bang, cannot access local disk space API any longer. Tried disabling sonarr, plexmediaserver, sabnzbd and still get the same error.

There is a permissions issue deep in the API call somewhere and it's way beyond my Linux digging ability. I will reopen as bug - happy to provide any inof requested

**Comment by ta264** [comment]
You need to tell us about the filesystem it's failing for and show permissions and files.

It probably is a bug in net core but it's not a widespread one, it's something peculiar to your setup I think.

**Comment by elegantalchemist** [comment]
Very happy to help provide whatever and show the filesystem it's failing for - how do I do that?

Local filesystem is NVMe and shows on the status page when it works as / (UUID = longstringalphanumeric) Remote used as a root path is a NAS mounted via fstab using CIFS. Works fine permissions wise.

Only permissions and files I know you want are /opt/Radarr and ~/.config/Radarr which the output is below - radarr.service runs with user andrew group andrew. The program ran fine with no error for about half an hour then started giving the error again after a restart. Trace logs in the original error are the same as now

drwxrwxr-x  5 andrew andrew 4096 Dec 30 18:59 Radarr (~/.config/Radarr)
drwxr-xr-x  5 andrew andrew 28672 Dec 30 17:31 Radarr (/opt/Radarr)

I've tried to duplicate it on a different set of hardware and so far failed so it may be a setup quirk, yes. Just a nightmare as it's all a fresh install as of about 45 min ago. I've changed nothing regarding the OS, just some basic installs.

**Comment by ta264** [comment]
Its the CIFS one that isn't working? Most likely another manifestation of the CIFS issue that's was worked around in nightly recently.

Tell me everything you can about the CIFS server and mount. I don't know enough about what the issue could be to ask specific questions....

**Comment by elegantalchemist** [comment]
No it's both - the remote CIFS one and the local NVMe drive, they both fail to get the free space data. (one on the media management page, one on the system page)

Give me 30min and I will do another trace log to see if there's any difference in the error message generated by looking at the local and remote disk space pages and if one/both generate the same error.

**Comment by ta264** [comment]
Does local fail if the CIFS is not mounted and the root directory is removed from radarr? Id bet not but it would be interesting if it did

**Comment by elegantalchemist** [comment]
Tried that already and local still fails with CIFS removed as a root path in Radarr. But I haven't tested it in depth by actually unmounting etc - will try shortly.

Also have a working new install test machine (old laptop) trying to replicate things on. Not got it to fail there yet.

On 30 Dec 2020 19:38, ta264 <notifications@github.com> wrote:

Does local fail if the CIFS is not mounted and the root directory is removed from radarr? Id bet not but it would be interesting if it did

**Comment by elegantalchemist** [comment]
Ok i've now successfully replicated it on a new system which has never had the CIFS mount added - I added the root folder to a random folder in ~/home. It's a bare install not even configured beyond a port change. An old laptop, totally different hardware.

Seems to be a time related thing or restart thing. As if it happens when time passes, not from a config change. This one was working fine and reporting the disk space just fine and now, no changes made but it's dropped the ball after a system restart. Was working fine before.

Memory leak perhaps? Some underlying state change to the .net core files used in the Disk Space API?

The strong impression I get from the fact that the mono version works is that this isn't a permission issue in the traditional sense (a file/folder it needs not got permission). This is the underlying .net core file used in the Disk Space API refusing to do it's job and reporting a permission issue - whether that's true or not is hard to tell.

Here's a huge trace paste from the other hadware which covers more than one hour. You can see multiple examples of successful API diskspace calls

2020-12-30 18:38:54.8|Trace|Http|Req: 51 [GET] /api/v3/diskspace (from ::ffff:127.0.0.1 Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0)

At 19:22:02.3 the get diskspace works fine. At 19:22:52.5 it fails and keeps failing.

https://pastebin.com/DQDVHzK3

Now i've replicated it on hardware I don't mind trashing i'm happy to re-do this hardware with ANOTHER clean install of Ubuntu 20.10 and try again with absolutely nothing but Radarr .net core if that helps. Alternatively any diagnostics you want let me know how to do and I can pull from this disposable machine - no problem.

**Comment by jasonoff** [comment]
Did this ever get resolved?  I have the same issue in Radarr Version 4.2.1.6478.  Ubuntu 21.10 and no issues reading drive space in Sonarr which is configured nearly identical.

**Comment by bakerboy448** [comment]
> Did this ever get resolved?  I have the same issue in Radarr Version 4.2.1.6478.  Ubuntu 21.10 and no issues reading drive space in Sonarr which is configured nearly identical.

For what file system and mount?

This was particularly only for certain network drives IIRC.

**Comment by jasonoff** [comment]
ext4 local drive mounted.  The title of this thread is "Can't access free space on local hardrive - API call fails no permission" which is exactly what I see in the logs.

I've always just ignored it but was chasing down an indexer issue and the stack trace of this error was bugging me.

**Comment by jasonoff** [comment]
I upgraded Ubuntu to 22.04.1 and bumped Mono to 6.12.0.182 thinking it may have been a version issue calling AspNetCore.  No dice, same issue.

Trace logs here --> https://pastebin.com/1iaQ18Fj

I haven't dug into it yet, but does Radarr call the same API to fetch disk space?  I don't have this issue with Sonarr but the install procedure was completely different.

**Comment by jasonoff** [comment]
Sonarr successful call
2022-08-19 11:44:56.0|Debug|Api|[GET] /api/v3/diskspace: 200.OK (178 ms)

**Comment by RobinDadswell** [comment]
> I upgraded Ubuntu to 22.04.1 and bumped Mono to 6.12.0.182 thinking it may have been a version issue calling AspNetCore. No dice, same issue.
> 
> Trace logs here --> https://pastebin.com/1iaQ18Fj
> 
> I haven't dug into it yet, but does Radarr call the same API to fetch disk space as Sonarr? I don't have this issue with Sonarr but the install procedure was completely different.

Radarr doesn't use Mono as it uses .net which is native to all platforms. Thanks for the trace log

**Comment by jasonoff** [comment]
> > I upgraded Ubuntu to 22.04.1 and bumped Mono to 6.12.0.182 thinking it may have been a version issue calling AspNetCore. No dice, same issue.
> > Trace logs here --> https://pastebin.com/1iaQ18Fj
> > I haven't dug into it yet, but does Radarr call the same API to fetch disk space as Sonarr? I don't have this issue with Sonarr but the install procedure was completely different.
> 
> Radarr doesn't use Mono as it uses .net which is native to all platforms. Thanks for the trace log

Ok thanks, could have sworn I saw it in the logs somewhere.  I may have read that somewhere else while searching the error.

.NET
Yes (6.0.8)

**Comment by jasonoff** [comment]
Bump for some traction.

**Comment by Fabrice-x-m** [comment]
Same problem

**Comment by musictrivianut** [comment]
Definitely having the same problem.

Running on Ubuntu 22.04.1 LTS with Radarr version information:

Version - 4.2.4.6635
.NET - Yes (6.0.8)
DB Migration - 214
Database - Sqlite 3.37.2
AppData directory - /home/xxx/.config/Radarr (home directory masked)
Startup directory - /home/xxx/git/radarr (home directory masked)
Mode - Console

Radarr not showing free space for Root Folders under Media Management (just a dash), nor under System Disk Space (no information at all).

All of the log entries look the same to my untrained eye - https://pastebin.com/gjAZZJfX

Don't know that anything detrimental is happening, since Radarr creates folders and imports files just fine.

**Comment by jasonoff** [comment]
I haven't resolved this.  A few searches keep pointing to permissions but both Sonarr and Radarr run as the same user/group and Sonar can call the same API without an issue.

**Comment by tabormeister** [comment]
Just started having the same issue here with Radarr, Sonarr/Prowlarr/qbit working fine. Recent upgrade to 20.04 only change to my setup

**Comment by jasonoff** [comment]
Haven't paid much attention to this in a while, but just noticed this is working in Version: 4.6.1.7456 so one of the updates must have fixed it.
