### ISSUE TITLE
Movie editor: sort by size

### ISSUE THREAD

**Issue by feld** [Radarr/Radarr#5646]
I'd really appreciate if I could sort the movies by size so I can easily remove the largest items and/or redownload them in a sane quality. The current method requires I do this manually outside of Radarr, and then I have to deal with making changes in Radarr manually as well.

**Comment by austinwbest** [comment]
Set the max file size accordingly & radarr won't grab anything above it.

Delete from disk & you don't have to manually do anything in radarr except a rescan & search missing.

Using file properties isn't something supported as the changes to support multiple qualities would break it.

Please use github when creating issues as 3rd parties kill the template & if you did use github, please don't kill the template when adding something.

**Comment by feld** [comment]
The profiles and max size are not compatible with HEVC/H265. It makes very bad assumptions about what size things should be based on old encoding estimates. It's pretty much unusable.

**Comment by bakerboy448** [comment]
You can adjust the quality sizes yourself.

https://trash-guides.info/Radarr/V3/Radarr-Quality-Settings-File-Size/


closing; Size on Disk is a sort option already

**Comment by feld** [comment]
Where is the option to sort by size? It's not even a column


<img width="1271" alt="image" src="https://user-images.githubusercontent.com/40271278/103372299-400c5800-4a97-11eb-87da-869f80fd7846.png">

**Comment by bakerboy448** [comment]
You’re using v0.2 which is EOL and no longer supported.

upgrade to v3

**Comment by feld** [comment]
> You can adjust the quality sizes yourself.
> 

In order for this to work correctly we need to be able to set quality sizes per each possible file type: MPEG2, MPEG4, HEVC

This is not possible. We can only do it by resolution.

**Comment by feld** [comment]
> You’re using v0.2 which is EOL and no longer supported.
> 
> upgrade to v3

oh dear, I didn't realize there was a v3 for Radarr... sorry and thanks

**Comment by bakerboy448** [comment]
> > You can adjust the quality sizes yourself.
> 
> In order for this to work correctly we need to be able to set quality sizes per each possible file type: MPEG2, MPEG4, HEVC
> 
> This is not possible. We can only do it by resolution.

Don’t think we’ve heard any issues with the v3 defaults nor TRaSH’s recommended settings (which are a bit larger)

regardless, hop on discord or Reddit for these types of discussions
