### ISSUE TITLE
Fallback to "Digital Release Date"

### ISSUE THREAD

**Issue by SugarDroid** [Radarr/Radarr#5647]
**Is your feature request related to a problem? Please describe.**
I'm using the feature offered by Radarr called "Change File Date" and set it to "Physical Release Date", which works fine if any date is added to TMDb. If there's none then most time i can fix it manually by searching and adding a date to where it needed. 

But on the other hand there are movies -I'm looking at you NF- which has digital release only, and with those there's nothing I can do. Since those movies has no physical date, Radarr keep them with the date it's been downloaded at.

If by any chance a repack/proper appears or just simple want to upgrade to higher quality, then the new file will get a new date, so the same movie will pop up again as a new movie added today to the library.

**Describe the solution you'd like**
Since this could apply to both "In Cinemas Date" and "Physical Release Date" options, it would be great if Radarr could fallback to digital's date and set the file to that if no physical or cinema exist.

[AB#665](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/665)

**Comment by bakerboy448** [comment]
looks like just need to add a case to https://github.com/Radarr/Radarr/blob/develop/src/NzbDrone.Core/MediaFiles/UpdateMovieFileService.cs

**Comment by Qstick** [comment]
> looks like just need to add a case to https://github.com/Radarr/Radarr/blob/develop/src/NzbDrone.Core/MediaFiles/UpdateMovieFileService.cs

Not necessarily another case, just a fallback.. Basically we should just fall back to digital if physical doesn't exist or just use the earliest of the two... whatever makes most sense. We would run into the same issue adding another option.
