### ISSUE TITLE
Couldn't import movie - Access to the path is denied (Radarr + Rclone)

### ISSUE THREAD

**Issue by luke-rig** [Radarr/Radarr#5648]
Hi,

My Radarr is not able to copy anything to my Rclone VFS Google Drive Mount, extract of log below.
I have tried everything and unable to resolve so believe this is a bug with Radarr.

This is not an issue for Sonarr which works perfectly copying files over to the Rclone mount as needed and uses the exact same settings.

I have tried both the latest Rclone V3 and also the nightly build on the off chance this was fixed (no luck).

OS: MacOS 10.15.4
Docker: No
Radarr Version 3.0.1.4337 (also tried with latest master)
.NET Core Yes (3.1.10)
DB Migration 188
AppData directory /Users/Luke/.config/Radarr
Startup directory /Applications/Radarr.app/Contents/MacOS
Mode Console

> 2020-12-30 16:58:08.5|Warn|ImportApprovedMovie|Couldn't import movie /Volumes/Transmission/Die Hard 4 Live Free Or Die Hard 2007.mkv
> 
> [v3.0.1.4337] System.UnauthorizedAccessException: Access to the path is denied.
>  ---> System.IO.IOException: Operation not permitted
>    --- End of inner exception stack trace ---
>    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
>    at Interop.CheckIo(Int64 result, String path, Boolean isDirectory, Func`2 errorRewriter)
>    at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
>    at NzbDrone.Mono.Disk.DiskProvider.TransferFilePatched(String source, String destination, Boolean overwrite, Boolean move) in D:\a\1\s\src\NzbDrone.Mono\Disk\DiskProvider.cs:line 337
>    at NzbDrone.Common.Disk.DiskProviderBase.CopyFile(String source, String destination, Boolean overwrite) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 227
>    at NzbDrone.Common.Disk.DiskTransferService.TryCopyFileVerified(String sourcePath, String targetPath, Int64 originalSize) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 487
>    at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 296
>    at NzbDrone.Core.MediaFiles.MovieFileMovingService.TransferFile(MovieFile movieFile, Movie movie, String destinationFilePath, TransferMode mode) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\MovieFileMovingService.cs:line 134
>    at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeMovieFile(MovieFile movieFile, LocalMovie localMovie, Boolean copyOnly) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\UpgradeMediaFileService.cs:line 51
>    at NzbDrone.Core.MediaFiles.MovieImport.ImportApprovedMovie.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\MovieImport\ImportApprovedMovie.cs:line 123

**Comment by bakerboy448** [comment]
99% sure this is a permissions issue
Support Requests -> [Reddit](https://www.reddit.com/r/radarr/) or [Discord](https://discord.gg/r5wJPt9)

if we find out it is in fact a bug, we can reopen
