### ISSUE TITLE
Import Existing Movies On Disk - Display Existing Movies doesn't fully hide existing movies

### ISSUE THREAD

**Issue by wipash** [Radarr/Radarr#565]
The 'Display Existing Movies' switch doesn't fully hide existing movies when it's switched off, it just collapses their descriptions.

It would be more useful to fully hide the movies, so that this list only contains movies that exist on disk and not in your library. If you have a library of many hundreds of movies, you still have to scroll through this list for a long time to find movies that aren't yet imported.

![radarr-display-yes](https://cloud.githubusercontent.com/assets/2068349/22521973/b7980d30-e91e-11e6-8b4d-0a71100d59be.PNG)
![radarr-display-no](https://cloud.githubusercontent.com/assets/2068349/22521977/b95b2a62-e91e-11e6-8613-cc3da71ad4b0.PNG)

**Comment by fedoranimus** [comment]
Fixed in the next release.
