### ISSUE TITLE
Quality Profiles are creating copies when editing to change them

### ISSUE THREAD

**Issue by CelagentT3** [Radarr/Radarr#5650]
**Describe the bug**
In Profiles when editing a profile it always makes a copy when saving, no way to remove all the copies and the original is not updated to the new settings

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Profiles'
3. Scroll down to 'Edit any profile and save'
4. See error (look multiple copies!)

**Expected behavior**
I would expect that editing a quality profile will save changes on the original profile rather than a new copy. Also there is no way to delete the extra ones.

**Screenshots**
![image](https://user-images.githubusercontent.com/29201193/103369892-50bdcd80-4a99-11eb-8589-36904e328928.png)

**Platform Information (please complete the following information):**
 - OS: Windows 2016 Server
 - Docker: [No]
 - Mono or.NET Core Version: [e.g. Mono 5.8 or .Net Core 3.1.10] (found under System -> Status)
 - Browser and Version [e.g. chrome 86.0.4240.198] (Only needed for UI issues)
 - Radarr Version [e.g. 3.0.0.2956]
 - Radarr Branch [e.g. master]

**Trace Logs**
Turn on Trace logs under Settings -> General and wait for the bug to occur again. **Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**

**Comment by CelagentT3** [comment]
My bad using newest Firefox
.net is the newest
Radarr is newest 3.0.1.4259
—
2020-12-10
developCurrently Installed

**Comment by Qstick** [comment]
Seems you are cloning instead of editing, how are you triggering the edit? I've seen no other reports of this.

**Comment by CelagentT3** [comment]
awe crap you are so right. Sorry for the waste of a post. I think it is that there is that one really small icon in the upper right corner now that I stopped and hovered it says clone.... I now know clicking anywhere on the profile to edit will open for edit.
