### ISSUE TITLE
Radarr not renaming files and not moving them.

### ISSUE THREAD

**Issue by bwarthen2000** [Radarr/Radarr#5653]
I have downloaded Radarr and am trying to download through Newsbin Pro which works but Radarr doesn't pick up the unzipped files and move them from my download folder to my movie folder on the same drive.

**Comment by bakerboy448** [comment]
Support Requests -> [Reddit](https://www.reddit.com/r/radarr/) or [Discord](https://discord.gg/r5wJPt9)

If you used GitHub...don’t blow away the template
If you used a third party app to create the issue...don’t it ignores templates.

That client is not compatible with radarr...you probably need to setup a Usenet blackhole
