### ISSUE TITLE
Addition of Release dates on Poster view mode

### ISSUE THREAD

**Issue by Conroy1988** [Radarr/Radarr#5656]
**Is your feature request related to a problem? Please describe.**
Feature QOL Request

**Describe the solution you'd like**
An ability on Poster view, to toggle release dates/digital/physical release dates.

**Describe alternatives you've considered**
I tried list view, but they have no banners for the movies.

The following is where I mean the info to show
https://i.imgur.com/TAEy7Cj.png

**Comment by bakerboy448** [comment]
Closing; no plans for this.

You can have them as a sort.  But this is what the table view is for (lots of info)

There's limited space for information as it is, and really isn't conducive to clutter the poster view.

**Comment by RobinDadswell** [comment]
As discussed I'll work on this
