### ISSUE TITLE
Show genre (movie page) v3

### ISSUE THREAD

**Issue by DecipherIt** [Radarr/Radarr#5657]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when, I get to see pretty much everything (links, rating etc.) on the page except for the GENRE.

**Describe the solution you'd like**
Pretty easy, add a scraper that adds genre (universal scraper, IMDB, TMDB, Trakt whatever, all api's work for that) in the main menu of a movie (click any movie you own, add the genre section anywhere).

**Describe alternatives you've considered**
Clicking one of the links and checking for genre, but this is a lot of work when you have a full database.

**Additional context**
To put this in context, I filter based on genre, I do it as much as I can auto but what I can't I do manually, so, for me, it would be a HUGE improvement if the page of the movie says what genre it is so I can delete them if they aren't interesting for me.

Hope you guys can add this, i've requested it a few times in v2 but v3 would make a great starting point for this!

[AB#654](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/654)

**Comment by psi5asp** [comment]
Pretty important when trying to determine if a video is a documentary, show, special, movie, etc.

Current workaround is to click on the available external link for TMDb, Trakt...IMDb...etc., which is great for the detail, but for something simple and quick to organise media in bulk - having Genre on the main page near the ratings saves a lot of time.
