### ISSUE TITLE
Ability to limit what file types are downloaded (ex. .mkv only, no .ts or .mp4)

### ISSUE THREAD

**Issue by phife-dawg** [Radarr/Radarr#5658]
**Is your feature request related to a problem? Please describe.**
Not related to a problem

**Describe the solution you'd like**
Currently, we can only limit what is downloaded based on the torrent name. I would love to be able to limit based on the filetype as well. Often times two torrents exist with the exact same torrent name, but one is an .mp4 and one is an .mkv. I would like to be able to use custom formats or some other restrictions to say only download .mkv files

**Describe alternatives you've considered**
Custom formats only work when the filetype is in the torrent name, which is very rare

**Additional context**
None needed

**Comment by Qstick** [comment]
See #2452, not in Radarr scope
