### ISSUE TITLE
Some dialog submissions don't work in chrome for android

### ISSUE THREAD

**Issue by demonspork** [Radarr/Radarr#5664]
Version
3.0.1.4259
Package Version
3.0.1.4259-ls88 by linuxserver.io

Some pages like editing a movies settings or trying to select request when adding a movie don't seem to work on 3.0. when I select the request button when adding a movie it does a small animation but never actually submits. Same when editing the properties of a movie, to change its quality for example, selecting save does the same thing where it doesn't actually submit. I have to open radarr elsewhere because it won't work on mobile.

**Comment by bakerboy448** [comment]
if you’re using a 3rd party GH app, don’t... they ignore templates

if you didn’t use a 3rd party GH app, don’t blow away the damn template

sounds like a reverse proxy and you didn’t make the v3 changes for SignalR.

Support Requests -> [Reddit](https://www.reddit.com/r/radarr/) or [Discord](https://discord.gg/r5wJPt9)

https://wiki.servarr.com/Radarr_FAQ#Why_doesn.27t_Radarr_work_behind_an_nginx_reverse_proxy
