### ISSUE TITLE
The info buttons on the Add List modal point to Sonarr's wiki

### ISSUE THREAD

**Issue by wipash** [Radarr/Radarr#567]
The modal that pops up when you click Add List (/settings/netimport) contains info buttons that point to Sonarr's wiki, for instance:
[https://github.com/Sonarr/Sonarr/wiki/Supported-NetImports#couchpotatoimport](https://github.com/Sonarr/Sonarr/wiki/Supported-NetImports#couchpotatoimport)
[https://github.com/Sonarr/Sonarr/wiki/Supported-NetImports#rssimport](https://github.com/Sonarr/Sonarr/wiki/Supported-NetImports#rssimport)

![image](https://cloud.githubusercontent.com/assets/2068349/22522785/cc318106-e921-11e6-9f68-7be368557ebe.png)

**Comment by jOOc** [comment]
@onedr0p didnt you fix this in #998 ?

**Comment by bobbintb** [comment]
The message for a new update does as well. Also the SSL login prompt says "Sonarr".
