### ISSUE TITLE
Setting Certificate Validation "Disabled for local adresses" does not work as expected

### ISSUE THREAD

**Issue by phit42** [Radarr/Radarr#5676]
The setting Certificate Validation "Disabled for local adresses" does not work as expected, a local sabnzbd on a different machine is not excluded from certificate validation.
Environment: both Sonarr and Radarr run in docker containers on the same machine, same network setup within docker, and both have the same download client configured. Sabnzbd is on a different server.
Whereas the connection to sab works fine within Sonarr with disabled for local adresses, it does not within Radarr. I have to completely disable it.

The attached log file contains at "2021-1-3 14:24:37.4" the error when testing the connection of the download client with setting "disabled for local adresses", secondly tested again with "disabled".

[https://pastebin.com/7kPq9fg5](https://pastebin.com/7kPq9fg5 )

**Platform Information (please complete the following information):**
 - OS: Synology
 - Docker: Yes
 - .NET Core: Yes (3.1.10)
 - Browser and Version [e.g. chrome 86.0.4240.198] (Only needed for UI issues)
 - Radarr Version 3.0.1.4259
 - Package Version 3.0.1.4259-ls88 by linuxserver.io
 - Radarr Branch master (I think)
 - DB Migration 188

**Comment by bakerboy448** [comment]
can you pastebin the logs?

also, if you can edit & fill out the template that'd be appreciated https://github.com/Radarr/Radarr/issues/new?assignees=&labels=bug&template=bug_report.md&title=

**Comment by ta264** [comment]
What are the IP addresses of all the various docker containers? SAB / Sonarr / radarr

**Comment by phit42** [comment]
Sonarr/Radarr run on a Syno server in docker environment with 192.168.9.111. IPv6 is disabled within docker, network driver is bridge, Sab is on a different Syno server 192.168.9.115 (not dockered).

**Comment by Qstick** [comment]
Is this fixed in nightly with https://github.com/Radarr/Radarr/commit/e2b2061ee1531f3320f79d9a1503d6cf2faebb91?

**Comment by phit42** [comment]
@Qstick are you asking me? I would think that e2b2061 should not have any effect on my scenario, as Sab is not on localhost. The function IsLocalAddress should run true though, or else it could be sth with network handling within docker containers.

**Comment by Qstick** [comment]
I was fooled by your issue post

The setting Certificate Validation "Disabled for local adresses" does not work as expected, a local sabnzbd 

I stopped reading and missed the:

on a different machine

Either way the code should be the same from Sonarr to Radarr, I can take a peek to ensure nothing obvious, but Id think we'd have gotten more reports of this not working right

**Comment by bakerboy448** [comment]
closing unless more info confirming this is broken in current builds is provided
