### ISSUE TITLE
Enforce selection of at least one credits option for Person Lists 

### ISSUE THREAD

**Issue by henkin67** [Radarr/Radarr#5684]
**Bug Description**
The import list doesn't work for any person IMDB ID. I tried for example with  Sean Connery and I got "No results were returned from your import list, please check your settings.".

**To Reproduce**
1. Go to a movie
2. Click on 'Cast'
3. Click on '+ icon' of any actor
4. Click on 'Test'
4. See error "No results were returned from your import list, please check your settings."

**Expected behavior**
Return a list of movies with the selected actor present in the casting of these movies.

**Screenshots**
![image](https://user-images.githubusercontent.com/29369709/103522608-ec28b700-4e7a-11eb-8277-7636a2bf341d.png)

**Platform Information:**
- Version: 3.0.1.4259
- Package Version: 3.0.1.4259-ls88 by linuxserver.io
- .NET Core: Yes (3.1.10)
- Docker: Yes

**Trace Logs**
[radarr.txt](https://github.com/Radarr/Radarr/files/5764080/radarr.txt)

**Comment by SugarDroid** [comment]
(You're mixing IMDb with TMDb up. Radarr uses TMDb's person ID so I think there's no way it could work with IMDb ID. )
I added him manually without any error through settings > lists.

Related to your steps to reproduce it and the 2 lines long log, the error it gave is happening when you don't choose any of the options available to the person. At least **one** of them **must be checked**, or it won't work.

![image](https://user-images.githubusercontent.com/56313144/103595719-72d1a880-4efc-11eb-8d48-07ee64088328.png)

**Note to developer**
This should be clear by simple looking at the form itself, or at least through the error message.

**Comment by henkin67** [comment]
I confirm it worked on my side as well.
Thanks for the help, and I confirm the need to enforce the selection.
As I selected this person through the cast tab, it as a sens to automatically select "person cast" to avoid this problem.
Thanks again for the help!
