### ISSUE TITLE
Movie title with special characters doesn't work

### ISSUE THREAD

**Issue by JamesDAdams** [Radarr/Radarr#5685]
**Describe the bug**
When Radarr search in indexer with a title movie which contains special characters (apostrophe) he replace the special characters by nothing (**Ex: Harry Potter and the Philosopher's Stone = Harry Potter and the Philosophers Stone** )

**To Reproduce**
1. Go to Movies
2. Add movie Harry Potter
3. Click to Harry Potter movie
3. Click to Search button
5. We can see in jackett log that radarr has researched the movie **Harry Potter and the Philosophers Stone**

**Expected behavior**
**A solution**

Add a option for each Indexers **Replace special characters** with 3 option

1.  Replace special characters by nothing (Ex: Philosopher's Stone = Philosophers Stone )
2.  Replace special characters by space (Ex: Philosopher's Stone = Philosopher s Stone )
3.  Not replace special characters (Ex: Philosopher's Stone = Philosopher's Stone )

**Screenshots**
**Mock**
![Untitled](https://user-images.githubusercontent.com/20860324/103538577-babde480-4e96-11eb-90c7-22f1ad325062.png)

**Platform Information (please complete the following information):**
 - OS: Unraid
 - Docker: Yes
 - Radarr Version 3.0.1.4259
 - Radarr Branch master

**Trace Logs**

`Radarr Log :

[Info] DownloadDecisionMaker: Processing 2074 releases
[Info] RssSyncService: RSS Sync Completed. Reports found: 2074, Reports grabbed: 0
[Info] NzbSearchService: Searching 2 indexers for [Harry Potter and the Philosopher's Stone]
[Info] DownloadDecisionMaker: No results found
[Info] NzbSearchService: Searching 2 indexers for [Harry Potter and the Philosopher's Stone]
[Info] DownloadDecisionMaker: No results found

Jackett Log

2021-01-04 13:50:06	Info	
Torznab search in Casa-Torrent for Harry Potter a lecole des sorciers 2001 => Found 0 releases (from cache)
2021-01-04 13:50:04	Info	
Torznab search in Sharewood for Harry Potter and the Philosophers Stone 2001 => Found 0 releases (from cache)
2021-01-04 13:50:02	Info	
Torznab search in Casa-Torrent for Harry Potter and the Philosophers Stone 2001 => Found 0 releases (from cache)
2021-01-04 13:44:09	Info	
Torznab search in Casa-Torrent for Harry Potter and the Philosophers Stone 2001 => Found 0 releases
2021-01-04 13:44:08	Info	
Torznab search in Sharewood for Harry Potter and the Philosophers Stone 2001 => Found 0 releases`

**Comment by Qstick** [comment]
Dupe #4502

**Comment by JamesDAdams** [comment]
@Qstick I was asked to create a new ticket on the discord...

**Comment by Qstick** [comment]
> @Qstick I was asked to create a new ticket on the discord...

I'm sure they didn't look to see if there was one already there. Use the other one that you've already commented on.
