### ISSUE TITLE
API: Malformed encoding found in chunked-encoding

### ISSUE THREAD

**Issue by JagandeepBrar** [Radarr/Radarr#5692]
**Describe the bug**
When making API calls to Radarr v3, typically on the first connection to Radarr will cause the API to throw an error with the error claiming in the following tools:
- Insomnia REST client: `Malformed encoding found in chunked-encoding`
- My mobile application, LunaSea: `HttpException: Connection closed while receiving data`
- Chrome: `net::ERR_INCOMPLETE_CHUNKED_ENCODING`

I have multiple users who brought this to my attention, who all had recently upgraded to Radarr v3. Using Radarr v2, they had no issues using my application or making API calls.

It seemingly happens at random too, it isn't always the first connection, and the first connection can pass in many attempts. It does appear after an initial successful response received, the clients will continue to receive valid data until (my assumption) that the intact HTTP connection has been closed and a new one has to be created.

Interestingly enough, I cannot reproduce this error at all on my own instance of Radarr (running using .NET Core on Ubuntu 20.04 via `linuxserver/radarr` docker images). My instance is relatively fresh, and does not have a large library imported yet.

This bug also occurs when doing a direct connection via IP address + port, as well as when using a reverse proxy.

**To Reproduce**
1. Make any API call (the most reliable one to throw this error is `/api/history`). The exact call that LunaSea makes is: `api/history?sortKey=date&pageSize=250&sortDir=desc`, but I have seen this error appear when no additional query parameters are passed.

**Expected behavior**
A valid HTTP 200 response with the data body.

**Screenshots**
I have posted the timeline output from Insomnia for a failed request (with redacted information) here: https://gist.github.com/JagandeepBrar/830c0d287a4be7c920b9e93ccc488a20

**Platform Information (please complete the following information):**
User 1:

```json
{
    "version": "3.0.1.4259",
    "buildTime": "2020-12-16T05:58:39Z",
    "isDebug": false,
    "isProduction": true,
    "isAdmin": false,
    "isUserInteractive": false,
    "startupPath": "/usr/local/share/Radarr",
    "appData": "/config",
    "osName": "Bsd",
    "isNetCore": false,
    "isMono": true,
    "isLinux": true,
    "isOsx": false,
    "isWindows": false,
    "branch": "develop",
    "authentication": "forms",
    "sqliteVersion": "3.33.0",
    "migrationVersion": 188,
    "urlBase": "",
    "runtimeVersion": "5.10.1.57",
    "runtimeName": "mono"
}
```

User 2:

```json
{
    "version": "3.0.1.4345",
    "buildTime": "2021-01-01T01:50:05.2186251Z",
    "isDebug": false,
    "isProduction": true,
    "isAdmin": false,
    "isUserInteractive": false,
    "startupPath": "/usr/local/share/Radarr",
    "appData": "/usr/local/radarr",
    "osName": "freebsd",
    "osVersion": "12.2",
    "isNetCore": false,
    "isMono": true,
    "isLinux": true,
    "isOsx": false,
    "isWindows": false,
    "branch": "nightly",
    "authentication": "forms",
    "sqliteVersion": "3.34.0",
    "migrationVersion": 188,
    "urlBase": "",
    "runtimeVersion": "6.12.0",
    "runtimeName": "mono"
}
```

**Trace Logs**

Trace logs supplied by a user (trimmed and redacted):

```
2020-12-29 17:46:02.9|Trace|Http|Req: 30018 [GET] /api/profile?apikey=(removed) (from ::ffff:192.168.0.78 Dart/2.10 (dart:io))
2020-12-29 17:46:02.9|Trace|Http|Res: 30018 [GET] /api/profile?apikey=(removed) 200.OK (3 ms)
2020-12-29 17:46:02.9|Debug|Api|[GET] /api/profile?apikey=(removed) 200.OK (3 ms)
2020-12-29 17:46:02.9|Trace|Http|Req: 30019 [GET] /api/movie?apikey=(removed) (from ::ffff:192.168.0.78 Dart/2.10 (dart:io))
2020-12-29 17:46:03.0|Trace|Http|Req: 30020 [GET] /api/profile?apikey=(removed) (from ::ffff:192.168.0.78 Dart/2.10 (dart:io))
2020-12-29 17:46:03.0|Trace|Http|Res: 30020 [GET] /api/profile?apikey=(removed) 200.OK (3 ms)
2020-12-29 17:46:03.0|Debug|Api|[GET] /api/profile?apikey=(removed) 200.OK (3 ms)
2020-12-29 17:46:03.0|Trace|Http|Req: 30021 [GET] /api/movie?apikey=(removed) (from ::ffff:192.168.0.78 Dart/2.10 (dart:io))
2020-12-29 17:46:03.0|Trace|Http|Req: 30022 [GET] /api/history?apikey=(removed)&sortKey=date&pageSize=250&sortDir=desc (from ::ffff:192.168.0.78 Dart/2.10 (dart:io))
2020-12-29 17:46:03.4|Trace|Http|Res: 30022 [GET] /api/history?apikey=(removed)&sortKey=date&pageSize=250&sortDir=desc: 200.OK (341 ms)
2020-12-29 17:46:03.4|Debug|Api|[GET] /api/history?apikey=(removed)&sortKey=date&pageSize=250&sortDir=desc: 200.OK (341 ms)
2020-12-29 17:46:05.5|Trace|Http|Res: 30019 [GET] /api/movie?apikey=(removed) 200.OK (2515 ms)
2020-12-29 17:46:05.5|Debug|Api|[GET] /api/movie?apikey=(removed) 200.OK (2515 ms)
2020-12-29 17:46:05.5|Trace|Http|Res: 30021 [GET] /api/movie?apikey=(removed) 200.OK (2483 ms)
2020-12-29 17:46:05.5|Debug|Api|[GET] /api/movie?apikey=(removed) 200.OK (2483 ms)
```

If there is additional information needed, I can reach out to the users who have reported the issue (and I have sent this issue to those users as well!)
An interesting thing to notice as well, is that typically other commands will receive their data correctly.

**Comment by ta264** [comment]
Please can you find out the mono version in use in each case?

**Comment by ta264** [comment]
Ah,I see it in your report now.

**Comment by JagandeepBrar** [comment]
> Ah,I see it in your report now.

Yes, sorry! Posted the issue a bit early before I got that data.

If there's anything else needed, please let me know!

**Comment by ta264** [comment]
Is there a way you can capture the actual chunk that insomnia thinks is invalid?

I think this is going to be to do with running on mono Vs net core (bsd doesn't support net core). You might have more luck replicating if you run the mono version on Linux. You can get the mono version from the GitHub releases page. Any docker image will use the net core version.

**Comment by JagandeepBrar** [comment]
> Is there a way you can capture the actual chunk that insomnia thinks is invalid?

I don't believe I can, but the user has given me their host and API key information for debugging this issue, so if you know of any other REST client that supports this, I can download and replicate the issue.

Using `curl` in Terminal I was able to also get the exact same response and it shows the point where it was finding the next chunk to be invalid. What is interesting is that it is returning an invalid chunk seemingly at a random location in the response.

Example 1: 
<img width="1123" alt="Screen Shot 2021-01-04 at 9 09 26 PM" src="https://user-images.githubusercontent.com/3048295/103602369-7d2a7d00-4ed1-11eb-8b00-f2dbe7d65c17.png">

Example 2:
<img width="1123" alt="Screen Shot 2021-01-04 at 9 10 03 PM" src="https://user-images.githubusercontent.com/3048295/103602374-8287c780-4ed1-11eb-877b-031b54e10727.png">

Both calls were made within a minute of each other, and no additional history had been recorded between the calls.

I can spin-up a mono-based instance if that would help, but as I mentioned I have their host and API key, so I can pull and test on their instance.

**Comment by JagandeepBrar** [comment]
Actually you can see in the first example above, there seems to be a random `website500` in the chunk (after the images array), and in the second example a random `400` after `lastInfoSync`.

**Comment by ta264** [comment]
Interesting, does it fail in a browser too? I was wondering if it was just insomnia being odd.

Can you get the output of `env` for the users too?

**Comment by JagandeepBrar** [comment]
<img width="1025" alt="Screen Shot 2021-01-04 at 9 20 12 PM" src="https://user-images.githubusercontent.com/3048295/103603086-566d4600-4ed3-11eb-98be-91123d7affaf.png">

Here is an example of repeatedly calling the same call until it throws that same error.

Below is attached the output JSON.

[output.json.zip](https://github.com/Radarr/Radarr/files/5767935/output.json.zip)

**Comment by JagandeepBrar** [comment]
<img width="1025" alt="radarr_error_output" src="https://user-images.githubusercontent.com/3048295/103603260-cf6c9d80-4ed3-11eb-8b00-93270e9d50cb.png">

Here is an example of repeatedly calling the same call until it throws that same error.

Below is attached the output JSON.

[output.json.zip](https://github.com/Radarr/Radarr/files/5767935/output.json.zip)

**Comment by JagandeepBrar** [comment]
> Interesting, does it fail in a browser too? I was wondering if it was just insomnia being odd.
> 
> Can you get the output of `env` for the users too?

I can't imagine it is a specific client issue, as this error occurs across LunaSea (written in Dart), in Insomnia (node-based REST client), and `curl`

**Comment by ta264** [comment]
(I edited your post to remove the users API key)

**Comment by JagandeepBrar** [comment]
> (I edited your post to remove the users API key)

I actually edited it right before you to update it with a redacted image, haha. Regardless, the output JSON is likely more useful.

**Comment by JagandeepBrar** [comment]
@ta264 I can confirm that the error does occur when using Google Chrome on both MacOS and Windows 10.

Here are some of the important pieces from the network logging:

<img width="654" alt="Screen Shot 2021-01-05 at 7 56 03 PM" src="https://user-images.githubusercontent.com/3048295/103720286-a5c57c00-4f90-11eb-8901-c1b1d2d5737b.png">

<img width="770" alt="Screen Shot 2021-01-05 at 7 53 45 PM" src="https://user-images.githubusercontent.com/3048295/103720281-a1995e80-4f90-11eb-9d35-35e24a89b0b6.png">

<img width="615" alt="Screen Shot 2021-01-05 at 7 54 46 PM" src="https://user-images.githubusercontent.com/3048295/103720299-ab22c680-4f90-11eb-9357-3c0633b7070d.png">

**Comment by Qstick** [comment]
Based on the content Download being dead on 2min (seems crazy) seems like some sort of timeout is causing this?

**Comment by JagandeepBrar** [comment]
> Based on the content Download being dead on 2min (seems crazy) seems like some sort of timeout is causing this?

When using an API client or `curl`, the response returns in a regular timeframe (under 2s on a remote connection) with the error. Only when using a web browser does it wait for 2 minutes before return the error.

**Comment by CrypticOne** [comment]
I believe I have the same issue. Bazarr 0.9.0.8 not talking to Radarr 3.0.2.4552. Bazarr Log says Received response with content-encoding: gzip, but failed to decode it., error(\Error -3 while decompressing data: invalid block type))..

After downloading a certain amount of data from the api, the json starts to get corrupted with binary data. Bazarr reads this as gzip data.

**Comment by ta264** [comment]
Bug Synology packages to swap to the net core version. I suspect this is a mono bug and we'll be dropping support for mono in the not too distant future.

**Comment by CrypticOne** [comment]
Sounds good. I have been meaning to try out a setup in docker instead of the native app.

**Comment by bakerboy448** [comment]
> I suspect this is a mono bug and we'll be dropping support for mono in the not too distant future.

Mono support has been dropped with 4.0

can reopen if still experienced on non-mono installs
