### ISSUE TITLE
IMDB User List Issues

### ISSUE THREAD

**Issue by bakerboy448** [Radarr/Radarr#5698]
**Describe the bug**
Public user watch list is not found

**To Reproduce**
Add public user watch list

**Expected behavior**
List actually loads

**Screenshots**
N/A

**Platform Information (please complete the following information):**
v3.0.1.4259
N/A otherwise; appears to be Servarr related issue

**Trace Logs**
```
2021-1-6 13:22:53.3|Debug|IMDbListImport|Downloading List https://radarrapi.servarr.com/v1/list/imdb/ur24290398

2021-1-6 13:22:53.3|Trace|HttpClient|Req: [GET] https://radarrapi.servarr.com/v1/list/imdb/ur24290398

2021-1-6 13:22:53.3|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'

2021-1-6 13:22:53.8|Trace|HttpClient|Res: [GET] https://radarrapi.servarr.com/v1/list/imdb/ur24290398: 404.NotFound (472 ms)

2021-1-6 13:22:53.8|Warn|IMDbListImport|Unable to connect to list

​[v3.0.1.4259] NzbDrone.Core.ImportLists.Exceptions.ImportListException: Radarr API call resulted in an unexpected StatusCode [NotFound]
```

**References**
https://www.reddit.com/r/radarr/comments/kr87i8/imdb_watchlist_error/
https://discord.com/channels/264387956343570434/264388019585286144/796410861492895774

**Work Around**

Use the LS obtained via export (ls057712773)

**Comment by Qstick** [comment]
Works fine now, 404 was likely cached if it was hit before it was public or something.
