### ISSUE TITLE
Feature Request: Plex Watchlist monitoring

### ISSUE THREAD

**Issue by vanstinator** [Radarr/Radarr#5705]
Plex has been rolling out and improving upon a personal watchlist feature. It used to only work with their own stream-able content. But it now works with any content at all. You can manage your own watchlist at https://mediaverse.plex.tv/

I'd like to add an additional `List` Subheader and list item for `Plex` in `Settings > Lists`. The list API needs an authentication token. So I'd either re-use the `Settings > Connect > Plex` token or provide an additional login feature on the list item settings panel.

Here are some rough ideas on what the screens would look like:

![modal](https://user-images.githubusercontent.com/577219/103928408-cc4afa80-50e9-11eb-9230-b55608d30098.png)
![lists](https://user-images.githubusercontent.com/577219/103928409-cce39100-50e9-11eb-9a38-e77ae63974c1.png)

[AB#664](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/664)

**Comment by bakerboy448** [comment]
Not sure if that’s something that would get merged, you’ll probably want to discuss with the dev team first.

Also can you hash out your FR a bit more: see template that third party apps ignore for examples 
https://github.com/Radarr/Radarr/issues/new?assignees=&labels=feature+request&template=feature_request.md&title=

**Comment by vanstinator** [comment]
I've updated the OP

**Comment by TobiMiller** [comment]
+1 

This feature request is an up to date topic. https://www.plex.tv/blog/end-the-streaming-struggle-with-plex/

**Comment by Lesthat** [comment]
+1

**Comment by nfribeiro** [comment]
+1

**Comment by bakerboy448** [comment]
Comments such as +1 or I want this feature too are unproductive and spammy.  Please just +1 the Original Post instead.

**Comment by tastyratz** [comment]
This would have been a cool feature before, but, since Plex just rolled out it's discover feature I think it's going to add significantly more value in it's integration. It went from cool to fantastic and I hope discovery gives the idea some traction.

**Comment by akaBrotherNature** [comment]
Sonarr can now sync with the new Plex watchlist feature. It would be fantastic to have Radarr do the same.

**Comment by bakerboy448** [comment]
Again, comments such as +1 or I want this feature too are unproductive and spammy. Please just +1 the Original Post instead.

There's already an in-progress pull-request to add this to Radarr

**Comment by andyincountry** [comment]
Very excited about this!!! I set this up in Sonarr and actually was able to set up multiple lists from different plex users so that the ones i selected can add to their plex watch list, sonarr will automatically pick up what they want to watch and add it to sonarr.  I am hoping that works the same here in radarr!!
