### ISSUE TITLE
Moved wiki breaks links to solutions of previous issues

### ISSUE THREAD

**Issue by kaipee** [Radarr/Radarr#5706]
https://github.com/Radarr/Radarr/wiki/FAQ#why-doesnt-aphrodite-work-behind-an-nginx-reverse-proxy

_Originally posted by @ta264 in https://github.com/Radarr/Radarr/issues/4471#issuecomment-635468469_

The above link was provided as a solution to an issue I am also currently experiencing (Login to Radarr through NGINX proxy causing a white/bank page.

The URL (thus solution) cannot be followed and search engine results aren't returning anything similar.

**Comment by bakerboy448** [comment]
https://wiki.servarr.com/Radarr_FAQ#Why_doesn.27t_Radarr_work_behind_an_nginx_reverse_proxy

**Comment by ta264** [comment]
https://wiki.servarr.com/Radarr_FAQ#i_am_using_a_pi_and_raspbian_and_radarr_will_not_launch
