### ISSUE TITLE
"NOT" on title is not working

### ISSUE THREAD

**Issue by quinnmjcj** [Radarr/Radarr#5709]
The "Not" portion of the title match in custom formats is not working

**To Reproduce**

Create 2 Custom formats - 
1080p BluRay - BRDisk, the word Complete (.+COMPLETE.+) in title, and NOT the word .+UHD.+ in title
COMPLETE is required - doesn't make sense for the Negate to be "required", so it's not (but it doesn't seem to change anything if I use it)

2160P Bluray - BRDisk, the word Complete (.+COMPLETE.+) in title, and the word .+UHD.+ in title
UHD and COMPLETE are both required
BRDisk

 Titles match both of them.

**Screenshots**
![formats](https://user-images.githubusercontent.com/46435100/104046681-4dab9700-5195-11eb-8bd4-6b4a12ecb521.jpg)
![PB](https://user-images.githubusercontent.com/46435100/104046688-500df100-5195-11eb-9c45-0ae0bd3ead48.jpg)

**Platform Information (please complete the following information):**
 Version 3.0.1.4259
Package Version 3.0.1.4259-1 by radarr
.NET Core Yes (3.1.10)
Docker Yes
DB Migration 188
AppData directory /config
Startup directory /usr/lib/radarr/bin
Mode Console

running asunraid docker

**Trace Logs**
[radarr.trace.txt](https://github.com/Radarr/Radarr/files/5788634/radarr.trace.txt)

**Comment by bakerboy448** [comment]
can you post the release names for easy copy pasting and also provide an export of both CFs

I'm guessing the Regex is probably not set _just_ right.

For future reference:
Support Requests -> [Reddit](https://www.reddit.com/r/radarr/) or [Discord](https://discord.gg/r5wJPt9)

**Comment by quinnmjcj** [comment]
{
  "name": "1080p BRay",
  "includeCustomFormatWhenRenaming": false,
  "specifications": [
    {
      "name": "BRDisk",
      "implementation": "QualityModifierSpecification",
      "negate": false,
      "required": true,
      "fields": {
        "value": 4
      }
    },
    {
      "name": "Complete",
      "implementation": "ReleaseTitleSpecification",
      "negate": false,
      "required": true,
      "fields": {
        "value": ".+COMPLETE.+"
      }
    },
    {
      "name": "not UHD",
      "implementation": "ReleaseTitleSpecification",
      "negate": true,
      "required": false,
      "fields": {
        "value": ".+UHD.+"
      }
    }
  ]
}

{
  "name": "UHD BRay",
  "includeCustomFormatWhenRenaming": false,
  "specifications": [
    {
      "name": "BRDisk",
      "implementation": "QualityModifierSpecification",
      "negate": false,
      "required": true,
      "fields": {
        "value": 4
      }
    },
    {
      "name": "UHD",
      "implementation": "ReleaseTitleSpecification",
      "negate": false,
      "required": true,
      "fields": {
        "value": ".+UHD.+"
      }
    },
    {
      "name": "Complete",
      "implementation": "ReleaseTitleSpecification",
      "negate": false,
      "required": true,
      "fields": {
        "value": ".+COMPLETE.+"
      }
    }
  ]
}


Pitch Black 2000 COMPLETE UHD BLURAY-COASTER[TorrentLeech]

**

**Comment by ta264** [comment]
You need to set required on the "not UHD" specification.

**Comment by bakerboy448** [comment]
for future CF reference
https://wiki.servarr.com/Radarr_Settings#Conditions

>Required - only applies to formats with more than one condition of the same type and changes the matching rules for type groups. Enabling this option means that this specific condition must be satisfied for the whole custom format to apply regardless of if another condition of the same type would otherwise satisfy the type group.

In this case you are using `Release Title` twice in your CF

**Comment by quinnmjcj** [comment]
Thanks, for some reason I convinced myself it didn't make sense to set 
it (and I actually thought I tried it and nothing changed), but setting 
it does work, and I understand why now.

Sorry for the bother.

Thanks again
