### ISSUE TITLE
MediaCover folder 40gb+ , pls add setting to change behavior

### ISSUE THREAD

**Issue by bob454522** [Radarr/Radarr#5711]
**Is your feature request related to a problem? Please describe.**
yes, the MediaCover folder is getting way to large

**Describe the solution you'd like**
i understand this is for caching / speed up the user gui when browsing radarr (and reduce api/url request counts) but I suggest there be a radarr setting added, with options:
1- to fully disable movie .jpg local caching  OR
2- let user set it so that when you access a movie's page in radarr, at that point the fan-art is downlaoded (and cached locally) OR
(the stock/default can be as it is now (ie every movie in the library auto has its fan art downloaded and cache'd locally) 

**Describe alternatives you've considered**
im aware i can symlink or change my data directory location over to a HDD,  however i like having the DB itself on my nvme drive, and in some cases this is much more difficult (ie if using a VM or container for only radarr)

**Platform Information (please complete the following information):**
 - OS: win server 2016
 - Docker: No
Version: 3.0.1.4259
.NET Core: Yes (3.1.10)
AppData directory:  C:\ProgramData\Radarr
Startup directory: C:\ProgramData\Radarr\bin

-------
please let the user decide if they want the delay/slower gui  vs less storage usage.

as of the past few months i rarely go into the radarr interface,   i have it setup to auto download/add new movie releases and its working GREAT!! (radarr usually adds 1-3  new movies per day).  

However as i have a large collection (40k+ movies in radarr),  C:\ProgramData\Radarr\MediaCover  (the folder) ,  has grown to over 40GB in size.

so about a month ago i deleted all the sub-folders in MediaCover, however all were re-downloaded over the past month.   I understand what these files are, but what i dont , Prior added movies had their covers / fan-art re-downloaded

i feel this will become a large issue over time as more users collection grow (and storage gets cheaper).
(also in many cases this causes *more* url/api lookups as most people will not ever browse every single movie in their radarr library, via the radarr web gui , so the cache isnt even used/needed).  

ie in my extreme case,  i have only ever looked at maybe 100-200 movie pages in radarr's web gui,  ever , yet 40k + url/api requests were sent out, over time, to get the MediaCover .jpgs for all 40k+ movies in my library.

thanks

**Comment by Qstick** [comment]
> as of the past few months i rarely go into the radarr interface, i have it setup to auto download/add new movie releases and its working GREAT!! (radarr usually adds 1-3 new movies per day).

Awesome news that you have things working great! We appreciate the use and support.

> However as i have a large collection (40k+ movies in radarr), C:\ProgramData\Radarr\MediaCover (the folder) , has grown to over 40GB in size.
> 
> so about a month ago i deleted all the sub-folders in MediaCover, however all were re-downloaded over the past month. I understand what these files are, but what i dont , Prior added movies had their covers / fan-art re-downloaded

Correct, there is no point in deleting this folder as its just going to get added again. 

> i feel this will become a large issue over time as more users collection grow (and storage gets cheaper).

This sort of goes against your argument, if storage is cheaper you shouldn't care about 40GB of cached images (about $0.72 in todays storages rates, and cheaper in the future to your point)

> (also in many cases this causes _more_ url/api lookups as most people will not ever browse every single movie in their radarr library, via the radarr web gui , so the cache isnt even used/needed).
> 
> ie in my extreme case, i have only ever looked at maybe 100-200 movie pages in radarr's web gui, ever , yet 40k + url/api requests were sent out, over time, to get the MediaCover .jpgs for all 40k+ movies in my library.

Actually in your case 80k requests, since you deleted it once allowing Radarr to re-download everything :)

In the end this for most people (including yourself) this is less than half a percent of the overall space used by your library it only happens once per movie (unless you clear the folder or your library). As well your cache folder for Plex/Other is likely just as big if not bigger. We have no plans to make this into a setting or disable it at current time.
