### ISSUE TITLE
Movies with special characters causes radarr to ignore download progress and fails to import.

### ISSUE THREAD

**Issue by rycore** [Radarr/Radarr#5716]
**Describe the bug**
Radarr will grab the movie to download like normal and it will be sent to the download client, but it won't show in the **Activity > Queue**, it seems to completely ignore the movie after the initial grab and the only difference seems to be a special character, in this case, it occurred with Alien 3 also known as "Alien³" and is shown in the log as "AlienÂ³".

**To Reproduce**
1. Add New
2. Search "Alien 3 1992"
3. Download

**Expected behavior**
Radarr to grab the movie, send it to the download client, then monitor the progress for it to import once the download completes.

**Platform Information (please complete the following information):**
 - OS: Windows Server 2012r2 (also occurs for a friend on windows 10)
 - Docker: No
 - Radarr Version: 3.0.1.4259
 - Radarr Branch: master

**Trace Logs**
[radarr.trace.txt](https://github.com/Radarr/Radarr/files/5792772/radarr.trace.txt)

**Comment by bakerboy448** [comment]
Doesn’t appear special characters are the problem here.

Issue is it’s parsing the name as `Alien 3 Assembly Cut`

Movie “Alien 3” =! “Alien 3 Assembly Cut”

Presumably Assembly Cut should be added as an edition... @Qstick ?

**Comment by austinwbest** [comment]
The 3 being superscript won't break radarr, that is for sure :)

**Comment by Qstick** [comment]
> Doesn’t appear special characters are the problem here.
> 
> Issue is it’s parsing the name as `Alien 3 Assembly Cut`
> 
> Movie “Alien 3” =! “Alien 3 Assembly Cut”
> 
> Presumably Assembly Cut should be added as an edition... @Qstick ?

Yep, looks like we don't handle just `Assembly Cut`.
