### ISSUE TITLE
For non-English movies, able to show 'original title/alias/aka name' on movie page, able to search via original title, and able to refer to it while renaming

### ISSUE THREAD

**Issue by skygunner** [Radarr/Radarr#5720]
**Is your feature request related to a problem? Please describe.**
For most of non-English native movies, they usually have a new English name other than the original title. 
For example:
https://www.imdb.com/title/tt2635846/
English name: Primary Love (2009)
Original title: Mo 3 pii 4 rao rak nai (original title)
The English name is less known to the movie's original market. Thus fetch and display the original title along with the English title
might be a good idea. Easier to search, know, read or manage it. 

**Describe the solution you'd like**
 able to show 'original title' on movie page under the English title, able to search via 'original title' (both movie library, adding new, and maybe online), and able to refer to it while doing renaming, so the original title can be kept along side the English title in the file name or folder. 

Further, if Radarr could alow the user put alias or aka name to an existing movie, this will be great. 
Because IMDB or TMDB might just have one original title. Sometimes a movie for example, a Japanest movie, you would have the tilte in English, Japanese and 'original title'. For example https://www.imdb.com/title/tt0223339/
A movie alias or aka name would let the user have full control over what they want to put there to fill the gap. 
And with this, Radarr should also allow the user to search and rename the movie with the alias/aka name. 

**Describe alternatives you've considered**
None

**Additional context**

**Comment by bakerboy448** [comment]
Can’t speak to the rest, I’ll defer to the devs for that.

> Further, if Radarr could alow the user put alias or aka name to an existing movie, this will be great.

just go to TMDB, add the alt title or translation, give it a minute, then refresh the movie in radarr and the new info will be there

**Comment by skygunner** [comment]
Thanks for the reply. I understand the alternative title works as aka or alias then and edit the TMDB website , a user can add alternative title. 

For my other suggestions, I still think it will be a good diea. 

Radarr doesn't provide a way to display the 'original title' on the movie page. 

I suggest for non-English native movies,  support to display, search in the library, interactive/auto search, and renaming reference with the 'original title', and maybe a stared alternative title the user think fits. 

The problem currently I have expereienced is, for non-English movies, either interactive or auto search will yield very few results 
 through the indexers (via Jackett) . And a lot of time the result is not even related to the searched movie at all (breaked the words to search I think).  
I guess the main reason is they exists mainly in the original title or alternative titles, very few resources in the English title (after a while).  
While search the original title or alternative title in Jackett directly does give a lot more results.

**Comment by titom1986** [comment]
Hi,
I'm trying to download a french movie and having exactly the same issue... The english title won't find any result (Tmdb alternative titles neither since it's other foreign languages).
That's one of the feature that prevent me from moving from Couhpotato (which handle that very well) to Radarr on a daily basis...

**Comment by bakerboy448** [comment]
@titom1986 
Support Requests -> [Reddit](https://www.reddit.com/r/radarr/) or [Discord](https://discord.gg/r5wJPt9)

add the appropriate title to TMDB and get better indexers that support TMDB ID search

**Comment by titom1986** [comment]
What do you mean about the translated title ? TMDB has already the french Title as primary Title, but Radarr is searching for the English one (Yes my Radarr is in english since I'm manly watching english movies).
But it doesn't make sens to discard the movie orginal title when searching...

**Comment by skygunner** [comment]
I believe currently in Radarr the 'translated title ' or alternative title is only used as reference for the user. Not used in searching. 
Plus anyone could add an alternative title, and there's many for a movie.  If we are going to support searching via those, the main one to support is the 'original title', the next to support might be let the user enable/approve one or several of the alternative titles, or maybe just let the user input the keywords for a movie to be searched.

**Comment by titom1986** [comment]
I totaly agree with you about letting the user defines some alternative searches.
For the searching part you might be right, but i had to create a 720p profile setted to french language to make the serach find something... This associated with a tag FRENCH... whithout this setting -> no results

**Comment by Qstick** [comment]
Translations are already used for searching and parsing for the languages you prefer in profile and CFs

There is already an issue open to allow selection of which alt titles to use.

You can already use original title or any translated title in naming.

The original title is shown as tooltip on the displayed title on movie page.

I don’t see a strong reason to keep this issue open given items discussed are either there or covered in other issues.

**Comment by bakerboy448** [comment]
> Translations are already used for searching and parsing for the languages you prefer in profile and CFs

No issue here. If you want to search for translated movies then prefer the language(s) in CFs and/or set your profile accordingly

> There is already an issue open to allow selection of which alt titles to use.

See https://github.com/Radarr/Radarr/issues/1447

> You can already use original title or any translated title in naming.

https://wiki.servarr.com/Radarr_Settings#Movie_Naming_2

> The original title is shown as tooltip on the displayed title on movie page.

Yup...

> I don’t see a strong reason to keep this issue open given items discussed are either there or covered in other issues.

And with that, closing.
