### ISSUE TITLE
Import List Sync

### ISSUE THREAD

**Issue by Paul5656** [Radarr/Radarr#5722]
**Is your feature request related to a problem? Please describe.**
There are a couple of ways to add movies to Radarr. Manual search, Discover Tab, or use Import Lists. It used to be that Radarr synced with Trakt every 15 minutes, which wasn't a problem but the limit was raised to 6 hrs minimum even though IMDb and Trakt have quite high rate limits. This forces users who use lists to have to either;
a) Go to Movies>Discover>Refresh Lists
or
b)System>Tasks>Import List Sync
every time they need to import their lists. Both options taking up a few extra seconds and requiring a few additional clicks of the mouse (wear and tear).

**Describe the solution you'd like**
Move the Refresh List to the main/front page next to the RSS button.

**Describe alternatives you've considered**
Drop the Minimum sync period to an hour or so.

**Additional context**
It's mostly a convenience issue but I feel like the Refresh list sync option is misplaced and needs to be on the Front/Main Page.

**Comment by bakerboy448** [comment]
This covers part of this discussion:
https://wiki.servarr.com/Radarr_FAQ#Why_are_lists_sync_times_so_long_and_can_I_change_it.3F

>But ultimately: Lists never were nor are intended to be `add it now` they are `hey i want this, add it eventually` tools

I'll defer to Nit or Q as far as if that is a UI change that makes sense given the purposes of lists.

**Comment by Paul5656** [comment]
@bakerboy448 Thanks for your response and that makes sense. I don't know why everyone else uses lists, but I use it as a main/backup i.e if my server were to crash to the point the data is unrecoverable I would still have/know which movies I had collected since all the titles are mirrored to Trakt. That's why I don't add manually because I tend to forget to add it on Trakt if I want to retain it. I only add manually and don't sync to Trakt if it's a movie that I don't really care about. Personally, I don't care about the List interval refresh period, it's the UI change that this suggestion was mostly about.

**Comment by austinwbest** [comment]
Radarr makes backups, your entire library is in it as well :)

As for a UI change for faster syncing.. I'm not opposed to taking about it but it needs to only show for those using lists if anything is changed.

However with the purpose of lists being what they are & not intended for a get it now kinda usage, I would lean away from  another button for it personally. Let it sync & do it's thing. Based on your main reason for usage of having it as a backup, how fast it gets into radarr isn't relevant.

For those instances of something you want now you have enough options. Use a bot, use the UI, use your list & sync it for those cases.

**Comment by Paul5656** [comment]
> Radarr makes backups, your entire library is in it as well :)
**Locally**, not in the cloud that's why I said if my server were to crash 😉 
 
> As for a UI change for faster syncing.. I'm not opposed to taking about it but it needs to only show for those using lists if anything is changed.
That would work, probably a checkbox in Advanced settings...Show/Hide Import List Sync button on main page or something to that extent

> However with the purpose of lists being what they are & not intended for a get it now kinda usage, I would lean away from another button for it personally. Let it sync & do it's thing. Based on your main reason for usage of having it as a backup, how fast it gets into radarr isn't relevant.
I wanted to avoid responding to the Import List usage responses at the risk of coming out as rude but the thing is there is no one to say there is a right/wrong way of using something. In this world lots of things are used for purposes that they weren't designed to be used eg Cars...Made for transportation but used for racing, living in them i.e RV, used as a source of income uber,etc can also be used as a weapon lol. In any case, people will always find ways of using something positively other than intended and that doesn't mean it should be limited in any way since the developer didn't have that in mind in retrospect.

I honestly don't see a negative in pushing the option to the main page other than users spamming the button more easily which can still be done right where it's at. Nonetheless, I see your frame of reference and totally get it.

**Comment by bakerboy448** [comment]
@austinwbest 

I'm thinking we can close; `Refresh Lists` button already exists on discover and frankly IMO that's the best spot for it

**Comment by Paul5656** [comment]
@bakerboy448 cool just close it, I rest my case.
