### ISSUE TITLE
Radarr.exe missing file format

### ISSUE THREAD

**Issue by sege5641** [Radarr/Radarr#5723]
**Describe the bug**
The release Radarr.master.3.0.1.4259.linux-core-x64.tar.gz is missing the file format .exe on /opt/Radarr/Radarr.exe.
 Only after adding the .exe to the file name was I able to launch the program. 

**To Reproduce**
Download Radarr.master.3.0.1.4259.linux-core-x64.tar.gz

**Expected behavior**
It would start

**Screenshots**

**Platform Information (please complete the following information):**
 - OS: Debian 10
 - Docker: No
 - Mono or.NET Core Version: (3.1.10) (found under System -> Status)
 - Browser and Version 
 - Radarr Version 3.0.1.4259
 - Radarr Branch: master

**Trace Logs**
Turn on Trace logs under Settings -> General and wait for the bug to occur again. **Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**

**Comment by bakerboy448** [comment]
Support Requests -> [Reddit](https://www.reddit.com/r/radarr/) or [Discord](https://discord.gg/r5wJPt9)

Don't run the .netcore version with mono; the correct start is just /opt/Radarr/Radarr
