### ISSUE TITLE
Show radarr's Source of new movie in radarr logs

### ISSUE THREAD

**Issue by bob454522** [Radarr/Radarr#5725]
**Is your feature request related to a problem? Please describe.**
Trying to troubleshoot various radarr issues related to excessive cpu use + mem leak with a large radarr library (and also clean out old lists that arent useful/updated to have in my radarr settings->lists).

**Describe the solution you'd like**
When radarr decides a new movie needs to be downloaded (ie sent over to your download Client),  it would be very helpful to know where (why) radarr decided to add this movie.  **Mainly: did it come from one of your lists?  and if so which one**.
or did it come from a calendar entry (and was then detected as available due to via a RSS scan?). or was it via a list that was marked as auto search movie, when added.

This "source" info ideally would be sent to the debug logs or the standard info log (which i currently have splunk indexing for better access/searching).   Or additionally on the radarr movie page of a movie,  show where/how the movie was found (ie on xyz list, or manually added, or via calendar ect) (best!)

**Additional context**
Ive never been able to find this info, even in the debug or trace logs (ie the specific list, by list name, from which a new movie was located on by radarr).  This would be very helpful in bugs/issues ive been trying to troubleshoot on radarr v2,  and still now on radarr v3 (as of the recent update from v2 to v3 on the develop chain)

When this v2 to v3 update auto occured a month or so ago, i noticed that radarr started running MUCH better (in terms of cpu/mem/(disk IO of radarr's db disk) - all of which i track).  **however as of the past few days i noticed that during the the v2 to v3 auto update all of my settings->lists were set to "disabled".  While a few new movies were still being auto added everyday (good!)  once i started re-enabling a few lists, even more movies started being added each day (great!)  however the same v2 cpu/mem/disk IO issues then started to reappear,  thus it would be very helpful if i could use the logs to help narrow down problem lists or just prune out lists that dont help to add new movies to my collection**

**Comment by bakerboy448** [comment]
If movies are from a list and which list; use tags, per #4333 no plans to change that, thus closing.

This PR may interest you as well
#5411

>I've never been able to find this info, even in the debug or trace logs (ie the specific list that a new movie was located on by radarr).

Have you checked v3?

I wouldn't expect performance issues with v3 it's way better than v0.2;  [upcoming .net5](https://github.com/Radarr/Radarr/pull/4638) changes will speed that up even more

But for slowness, hop on and folks can help narrow that down
Support Requests -> [Reddit](https://www.reddit.com/r/radarr/) or [Discord](https://discord.gg/r5wJPt9)

**Comment by bob454522** [comment]
Thanks for the reply,  Excellent!  tags do look like it iwll do what i need!
#Have you checked v3?

I assume i am on v3,  copy/paste from settings: 
3.0.2.4369  /  Jan 9 2021 / develop / Currently Installed

 (was forced onto it as of a few months ago,  i dont mean forced in a bad way, it was just auto-updated from v2 to v3 a few months ago via my:  Settings->General->Branch = develop  , which ive had it set to "develop" branch since day one.  Then randomlly a few months ago the entire gui changed, and i noticed i was no longer on version 2.xx  but rather 3.xx).

That said i will look into Discord for the peromance issues, as i do have a huge library, but also top notch HW ( dedicated machine for Radarr + Sonarr w enterprise nvme for their data/db).  
thanks!
