### ISSUE TITLE
Feature - Add Trakt List (one time only) by pasting it right into the Add New search box

### ISSUE THREAD

**Issue by Tharic99** [Radarr/Radarr#5728]
I'm very familiar with adding Trakt lists to Radarr. Settings -> List-> Add a New List, etc, etc.

I'd like to propose that a "one time" list could be added to the Movies -> Add New search bar. The process works currently by looking at a tmdbid, could it be enhanced to find when the search item begins with the `https://trakt.tv/`path that Radarr then recognizes that this is a list from Trakt and importing the entire contents of the list is what is intended? I understand completely adding a list to the List settings itself, in the event that list is updated, the items would then be picked up.

But if I just want to add all of the Bruce Lee movies to Radarr, wouldn't it be so much easier to just google "trakt bruce lee" find the best list and paste it right into the Add New search bar?

https://trakt.tv/users/echang/lists/bruce-lee?sort=rank,asc

Then every one of those movies is just added into Radarr with my default settings.

**Comment by bakerboy448** [comment]
closing; No plans to open up the add movie search to include lists.
