### ISSUE TITLE
Manual Search Results Columns

### ISSUE THREAD

**Issue by DaVoodoo** [Radarr/Radarr#5730]
**Is your feature request related to a problem? Please describe.**
When I do a manual search the results that come up have many columns. Unless I change the magnification I can't see all the columns and have to scroll horizontally to get to the last column to download.

**Describe the solution you'd like**
Could it be possible to select which columns I want to see?

**Comment by bakerboy448** [comment]
No plans to customize the table;

But we're aware we need to better optimize for small and mobile screens; to that end, opened https://github.com/Radarr/Radarr/issues/5732
