### ISSUE TITLE
qBittorrent Label not set when adding a torrent

### ISSUE THREAD

**Issue by rogerfar** [Radarr/Radarr#5736]
I was looking through the codebase and noticed that the function `Proxy.SetTorrentLabel` only gets called when an item is marked as imported.

In v2 the label would get set immediately when the torrent is added. What I find odd is that when you add a qBittorrent Download Client, it forces you to have a `radarr` label in qBittorrent, but it doesn't really do anything with it.

Is this a bug or an intended change?

**Comment by austinwbest** [comment]
There is a category added when it is grabbed & can also be changed when it is imported. Post import category, seen when advanced is enabled.

**Comment by rogerfar** [comment]
I see the API call to set the category here: https://github.com/Radarr/Radarr/blob/3e795d290b1542a0eac755831dcf185b87b45b50/src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrentProxyV2.cs#L187

But this function `SetTorrentLabel` is only called here:
https://github.com/Radarr/Radarr/blob/4f281669fcd460efa4191590de31da12c7e4271d/src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrent.cs#L57

But when I look in for example uTorrent, it's done here:
https://github.com/Radarr/Radarr/blob/adedbc1bed9358454ccf6678bab4f56803fb173a/src/NzbDrone.Core/Download/Clients/uTorrent/UTorrent.cs#L47

and here:
https://github.com/Radarr/Radarr/blob/adedbc1bed9358454ccf6678bab4f56803fb173a/src/NzbDrone.Core/Download/Clients/uTorrent/UTorrent.cs#L64

But then RTorrent also had it only on `MarkItemAsImported`.

This was removed in this commit:
https://github.com/Radarr/Radarr/commit/91ab518dfb78d5dac8f96448fb4fe83c337182b3#diff-4aa480003e8ce16bee777a84e906e71a29f45c4d6ea7c25bdbb2080795c36460

**Comment by austinwbest** [comment]
Exactly what problem are you trying to solve? Radarr properly sets the channel on grab and post import (as i use it that way so i know it does)

**Comment by rogerfar** [comment]
The SetTorrentLabel code was removed from the QBittorrent download client, but is still intact in UTorrent. So depending on the download client you get different behavior.

It looks like this code was taken over from Sonarr directly, I raised an issue there too.

**Comment by austinwbest** [comment]
Be that as it may, that doesn't answer my question. What is the **problem** you are trying to solve?

**Comment by rogerfar** [comment]
> Be that as it may, that doesn't answer my question. What is the **problem** you are trying to solve?

My qBittorrent config downloads to C:\downloadpath\$category. Since v2 when I fetch a movie it sets the category of the torrent directly after. Since v3 it never set the category.

**Comment by rogerfar** [comment]
I suppose it would help to upgrade qBitorrent.. I didn't realize it was now passed as a parameter on the add api call.
