### ISSUE TITLE
Core dump on armhf Ubuntu 18.04.5 LTS

### ISSUE THREAD

**Issue by frankicia** [Radarr/Radarr#5743]
**Describe the bug**
Trying to run radarr fails with: "Aborted (core dumped)"

**To Reproduce**
1. Start Radarr
2. Get core dump

**Expected behavior**
It should run

**Platform Information (please complete the following information):**
 - OS: Ubuntu 18.04.5 LTS
 - Docker: Yes
 - Mono or.NET Core Version: Yes (3.1.10)
 - Radarr Version: 3.0.1.4259
 - Radarr Branch: master

**Trace Logs**
How can I paste the core dump? Another flag to debug?

**Comment by ta264** [comment]
Please join the discord channel if you want to get to the bottom of this.  There are plenty of arm users so likely something off with your setup
