### ISSUE TITLE
Resolution and quality token separation 

### ISSUE THREAD

**Issue by Shredder5262** [Radarr/Radarr#5745]
Under 
Media Management>?> File Name token>Quality; Please add the ability to separate movie quality and resolution 
In it's current state Quality  can only be stated as bluray-2160p or DVD-720p in the same token using either option. I would like to add a spacer in between the quality and resolution, but cannot do so because it is all one entitiy. 
I would like it to say Blu-ray - 1080p or Web-DL - 2160p

**Comment by bakerboy448** [comment]
Fun Fact; Settings -> Qualities -> Rename your qualities and add a space between source and resolution (which together form the quality)

**Comment by Shredder5262** [comment]
submitted 2 issues by mistake
