### ISSUE TITLE
Quality and Resolution token seperation

### ISSUE THREAD

**Issue by Shredder5262** [Radarr/Radarr#5746]
Under 
Media Management>?> File Name token>Quality; Please add the ability to separate movie quality and resolution 
In it's current state Quality  can only be stated as bluray-2160p or DVD-720p in the same token using either option. I would like to add a spacer in between the quality and resolution, but cannot do so because it is all one entitiy. 
I would like it to say Blu-ray - 1080p or Web-DL - 2160p

**Comment by ta264** [comment]
You can rename the qualities to whatever you want

**Comment by bakerboy448** [comment]
Fun Fact; Settings -> Qualities -> Rename your qualities and add a space between source and resolution (which together form the quality)

**Comment by Shredder5262** [comment]
Wasn't aware that these fields are where the "Qualities" settings are pulled from, thank you. Could have did without the "Fun Fact" part though
