### ISSUE TITLE
Open File Path in Finder / File Explorer

### ISSUE THREAD

**Issue by mina-gaid** [Radarr/Radarr#5757]
**Is your feature request related to a problem? Please describe.**
I have to manually navigate to the file location.

**Describe the solution you'd like**
Make the file path, in the movie detail view, clickable. On click, the folder in which the movie is downloaded should open in the Finder / File Explorer.

**Describe alternatives you've considered**
A button that opens the file explorer. Or simply using Plex, tho I would rather not use Plex as its quite bloated.

**Additional context**
N/a

**Comment by Qstick** [comment]
No plans for this, the device being used to access Radarr UI doesn't always have access to the file system that the media library is on. Mapping becomes a nightmare.

**Comment by mina-gaid** [comment]
How tho? You're already pulling the file path and displaying it on the UI. Just make it so that file path gets sent to a shell script and it opens the folder.

At least make it optional in the settings.

**Comment by bakerboy448** [comment]
How tho what?

This covers it:
> the device being used to access Radarr UI doesn't always have access to the file system that the media library is on
