### ISSUE TITLE
Samples

### ISSUE THREAD

**Issue by Firemad03** [Radarr/Radarr#577]
We need an option somewhere that if Radarr detect a samples movies to delete it and rescan again. 
I got some samples after my download and I hate them :)

Make it as an option in Quality: Ignore sample.
This option need to detect a 0 bytes files and 0 min files too and reject it.

My Ignore Samples is on in sabnzbd but some pass.

Anyways if someone doesn't have sabnzbd it will be useful if he want samples.

**Comment by galli-leo** [comment]
What were the sample runtimes like? Radarr should already reject samples from being imported.

**Comment by kniffs** [comment]
System as it works now functions fairly well imo, it avoids samples and detects them somewhat well - But still gives enough time for a movie with 0 bytes that is being extracted to not be ignored.

**Comment by Firemad03** [comment]
@galli-leo I didn't update with the fix that you did but here a screenshot for one that was happening:

![image](https://cloud.githubusercontent.com/assets/24792889/22575002/d25aafb2-e980-11e6-942a-7b1b6cf455ce.png)

I saw others too.

I don't know the runtime because I deleted it.

**Comment by Firemad03** [comment]
Well I think if Radarr found something for 30 minutes or less should be detected as a sample. Does anyone saw a movie less then 30 minutes ?

For Sonarr I will understand for something less then 6 or 15 min that should be a sample.

**Comment by Firemad03** [comment]
![image](https://cloud.githubusercontent.com/assets/24792889/22575620/bccfcc82-e984-11e6-804e-28e5cf15beba.png)

**Comment by galli-leo** [comment]
@Firemad03 The doctor strange seems like a fake release (No BRRip available yet) Probably the runtime is far too short, so it get's recognised as a sample.

**Comment by wifiuk** [comment]
i have a 23.6GB .mkv file, and its not transferring over as it just says Sample as the screenshot above not sure why
