### ISSUE TITLE
API V3 - /history/movie no way to mark history item as failed

### ISSUE THREAD

**Issue by georgemcc** [Radarr/Radarr#5776]
**Is your feature request related to a problem? Please describe.**
I'm trying to implement the V3 API in my Swift code and noticed that I can perform a GET for a specific movie using /history/movie?moiveId=xxx.  However, I don't see an API endpoint for marking  history item as failed (although you can do this using the Web UI).

**Describe the solution you'd like**
Perhaps a POST endpoint to allow this?  Or at least let us know how it's performed using the Web UI?

**Describe alternatives you've considered**
No API alternative at this point that I can see.

**Comment by bakerboy448** [comment]
check the dev console; everything in the UI is done via the API; the API docs are a perceptual Work In Progress, feel free to make a PR for them following the existing format if you wish.

**Comment by georgemcc** [comment]
Okay.  I found /history/failed via the dev console in Safari.  I tried passing id=xxx as a parameter as well as POST body but neither work.  Any insight would be appreciated!
