### ISSUE TITLE
Issue Importing Existing Library Docker

### ISSUE THREAD

**Issue by shley008** [Radarr/Radarr#5777]
Changing setup today over to docker just to get some experience with it. Everything seems to work, EXCEPT, when trying to import existing files, it fails with the error in my screenshot. It does seem to work fine if I stop the processing at 120 files or less, but over that results in an error.

![image](https://user-images.githubusercontent.com/61912791/104869857-a7862c80-590c-11eb-828a-7cf4c336567b.png)

**Comment by shley008** [comment]
Here is the error output
`TypeError: Cannot read property 'map' of undefined

    in a
    in T
    in div
    in DocumentTitle
    in SideEffect(DocumentTitle)
    in a
    in fI
    in a
    in a
    in T
    in t
    in t
    in a
    in a
    in t
    in t
    in a
    in eee
    in div
    in div
    in a
    in a
    in T
    in withRouter(Connect(a))
    in t
    in n
    in i
    in T
    in c
    in DocumentTitle
    in SideEffect(DocumentTitle)
    in e`

**Comment by bakerboy448** [comment]
if you used a third party app to create the issue....please don't it ignores templates.

with that said
[Use The Bug Template (just copy/paste & edit)](https://github.com/Radarr/Radarr/issues/new?assignees=&labels=bug&template=bug_report.md&title=)

**Comment by shley008** [comment]
My apologies, I've never raised an issue for anything on github before.

**Comment by Qstick** [comment]
This is usually result of some type of permissions issue on the backend. Have a look at your logs and come to discord if you want some help with things. Going to close this up, we can re-open it if it turns out to be something else.

**Comment by r3dsn0wz** [comment]
Having the same issue. The only solution is to import less than about 75 files at a time for me

**Comment by bakerboy448** [comment]
@r3dsn0wz 

Issue was closed
Support Requests -> [Reddit](https://www.reddit.com/r/radarr/) or [Discord](https://discord.gg/r5wJPt9)

thanks
