### ISSUE TITLE
Download Client Priority [feature request]

### ISSUE THREAD

**Issue by Smokex365** [Radarr/Radarr#578]
Would like to see download client priority (re)-added. I for instance have my main download client behind a VPN on my local network in a VM. I however use another server(s) from Scaleway currently for downloading and seeding. In particularly the leecher machine is only on when I'm downloading something.

Having it prioritize the leecher client and and then fall back to my local client when the leecher one is unavailable would be nice. Right now I have to disable my local client in radarr when I intend to use my leecher box.

**Comment by galli-leo** [comment]
Duplicate issue
