### ISSUE TITLE
Radarr trying to import from wrong directory

### ISSUE THREAD

**Issue by SugarDroid** [Radarr/Radarr#5780]
**Describe the bug**
Sometimes movies gets stuck in queue. Does not matter that the client shows the appropriate directory where the files actually are, Radarr keep trying to import from wrong, obsolete directory, where the files been during download.

**To Reproduce**
Happens randomly so I don't know any way to intentionally reproduce it.
 
**Expected behavior**
Files gets imported.

**Platform Information (please complete the following information):**

- Version 3.0.2.4414
- Package Version 3.0.2.4414-ls8 by linuxserver.io
- .NET Core Yes (3.1.10)
- Docker Yes

**Trace Logs**
https://pastebin.com/ZYrxNfNk

**Comment by bakerboy448** [comment]
`/mnt/share/data/downloads/incoming/radarr/`  I'm assuming is  the temp folder?  (weird that it's not a docker path; but I digress)

What client and version?

**Comment by Qstick** [comment]
I think there is a Sonarr pull to fix this, but was waiting on @ta264 take on the fix. It seemed to be doing what we were trying to avoid and making further calls to client.

**Comment by SugarDroid** [comment]
> `/mnt/share/data/downloads/incoming/radarr/` I'm assuming is the temp folder? (weird that it's not a docker path; but I digress)

Yes that's it, but why do you think it's not docker path? Is it because instead of some silly directory in`/`, I use the existing `/mnt` directory -within containers too- for what it was originally created for? :smile: 

> What client and version?

rTorrent 0.9.8

**Comment by DirtyCajunRice** [comment]
The fix was done via https://github.com/Sonarr/Sonarr/commit/ca34f64eb0a8f26be66030988284b17c9d65f460 based on the identical issue posted at https://github.com/Sonarr/Sonarr/issues/4206.

Additional information to help the devs:

Recent trace log: https://bin.cajun.pro/raw/geginulido
slice of response that includes affected movie:
```json
[
    "Skylines.2020.1080p.BluRay.DD+5.1.x264-iFT.mkv",
    "1F596F67A460CBD1BC4CAF06A4C0EE3AE98D4EB5",
    "/mnt/torrents/completed/radarr/Skylines.2020.1080p.BluRay.DD+5.1.x264-iFT.mkv",
    "radarr",
    10544986102,
    0,
    0,
    0,
    1,
    1,
    1
]
```
area of log that references it after
```
2021-1-25 04:23:42.1|Debug|Api|[GET] /api/v3/command: 200.OK (6 ms)
2021-1-25 04:23:42.2|Debug|DownloadedMovieImportService|Processing path: /mnt/media/torrents/incomplete/radarr/Skylines.2020.1080p.BluRay.DD+5.1.x264-iFT.mkv
2021-1-25 04:23:42.2|Error|DownloadedMovieImportService|Import failed, path does not exist or is not accessible by Radarr: /mnt/media/torrents/incomplete/radarr/Skylines.2020.1080p.BluRay.DD+5.1.x264-iFT.mkv. Ensure the path exists and the user running Radarr has the correct permissions to access this file/folder
2021-1-25 04:23:42.2|Trace|TrackedDownloadAlreadyImported|Checking if all movies for 'Skylines.2020.1080p.BluRay.DD+5.1.x264-iFT.mkv' have been imported
2021-1-25 04:23:42.2|Trace|TrackedDownloadAlreadyImported|Last event for movie: [Skylines (2020)][tt9387250, 560144] is: Grabbed
2021-1-25 04:23:42.2|Trace|TrackedDownloadAlreadyImported|All movies for 'Skylines.2020.1080p.BluRay.DD+5.1.x264-iFT.mkv' have been imported: False
2021-1-25 04:23:42.2|Debug|CompletedDownloadService|Not all movies have been imported for Skylines.2020.1080p.BluRay.DD+5.1.x264-iFT.mkv
```
