### ISSUE TITLE
updated version 3.0.2.4369 broke install (Fedora 27)

### ISSUE THREAD

**Issue by mattman73** [Radarr/Radarr#5784]
**Describe the bug**
Just updated to version 3.0.2.4369 via built-in version update and after a restart, the software will no longer run, I have run the install and can see that the database has migrated to the new version but once the webserver starts I get the error.
[Info] RadarrBootstrapper: Starting Web Server
* Assertion at local-propagation.c:555, condition `ins->opcode > MONO_CEE_LAST' not met
**To Reproduce**
Steps to reproduce the behaviour:
1. Run /usr/bin/mono --debug /opt/Radarr/Radarr.exe -nobrowser
2. * Assertion at local-propagation.c:555, condition `ins->opcode > MONO_CEE_LAST' not met

**Expected behaviour**
after the software starts it should finish migrating the database then start the webserver

**Screenshots**

**Platform Information (please complete the following information):**
 - OS: Fedora 27, kernel 4.18.19-100.fc27.x86_64 
 - Docker: [Yes/No] No
 - Mono or.NET Core Version: Mono JIT compiler version 4.8.0 (Stable 4.8.0.520/8f6d0f6 Thu Sep 21 07:12:44 UTC 2017)
 - Browser and Version [e.g. chrome 86.0.4240.198] (Only needed for UI issues) no issues with browser
 - Radarr Version 3.0.2.4369
 - Radarr Branch [e.g. master]

**Trace Logs**
Due to the software not starting here is the terminal output.
https://1drv.ms/t/s!AmQePyx9R1BXh9B7aGzjdojmLE-hTg?e=nN8ABE 
[radarr-output.txt](https://github.com/Radarr/Radarr/files/5832658/radarr-output.txt)

**Comment by bakerboy448** [comment]
someone with more knowledge will likely swing by....but my guess is going to be that [your mono version is too old](https://github.com/Radarr/Radarr/blob/develop/src/NzbDrone.Core/HealthCheck/Checks/MonoVersionCheck.cs)

Your OS has also been EOL for a bit over two years as well.

**Comment by Qstick** [comment]
Yea mono 4.8 is too old
