### ISSUE TITLE
Mono build breaks install after net5/472 bump

### ISSUE THREAD

**Issue by pkreuzt** [Radarr/Radarr#5785]
After an (automatic) upgrade, daemon is unable to start anymore. It keeps trying giving same error until service is stopped. Relevant start log appended.

 - OS: Raspberry OS 10 Buster armv7l
 - Docker: No
 - Mono or.NET Core Version: Mono version 5.18.0.240 (Debian 5.18.0.240+dfsg-3)
 - Radarr Version 3.0.2.4438

[radarr_start.log](https://github.com/Radarr/Radarr/files/5832786/radarr.log)

**Comment by bakerboy448** [comment]
https://wiki.servarr.com/Radarr_FAQ#I_am_using_a_Pi_and_Raspbian_and_Radarr_will_not_launch

**Comment by pkreuzt** [comment]
It's NOT a Docker install. And it was running a couple hours ago, so I think that's
 not the problem.

**Comment by Qstick** [comment]
Ah you are on nightly (Bleeding edge) and this is the first net5/net framework 472 build. So it's likely related to that.

**Comment by pkreuzt** [comment]
I was on Aphrodite, then some time ago changelog suggested to switch to nightly to receive further updates. I suppose it's safe to stick to master now. Am I right?

**Comment by bakerboy448** [comment]
Nope.
Once you’re on nightly at this point you’re stuck there until a new develop is pushed and you’ll be stuck their until a new latest/master is released

**Comment by Qstick** [comment]
@pkreuzt you maybe able to help us diagnose the issue if you are up for it? Else you are likely good to switch to `develop` without trouble right now. Just don't go all the way to `master`

**Comment by pkreuzt** [comment]
@Qstick I can help, just tell me what you need.

**Comment by bakerboy448** [comment]
@pkreuzt give the non-mono build a shot https://wiki.servarr.com/Radarr_System#update_to_net_core_version

**Comment by pkreuzt** [comment]
@bakerboy448 .Net build seems to work, but its version is higher (3.0.2.4445). CPU use is slightly higher, probably because of some running migration. I'm not a fan of MS though.

**Comment by Qstick** [comment]
The .Net build is 10-15X faster in places... Its what you want to run. Mono, while it has its place and has served well over the years, is slow, can be buggy and is destined to merge (be replaced) with .Net when 6 is released later this year. We do want to make sure that mono build runs still, but by all means if the .Net build works, you want to run it.

Also I don't think you are getting away from your friends at MS either way :)

`Sponsored by Microsoft, Mono is an open source implementation of Microsoft's .NET Framework based on the ECMA standards for C# and the Common Language Runtime.`

**Comment by pkreuzt** [comment]
@Qstick Then should we close this issue or do you need more info to address Mono build issue?

**Comment by Qstick** [comment]
We should leave it open until someone on team can proper test the mono builds and figure out what's wrong.

**Comment by rlangtind** [comment]
Im getting the same.. 

Native App on Synology..

Getting this in log:


2021-1-19 13:33:47.7|Info|InstallUpdateService|Preparing client
2021-1-19 13:33:48.3|Info|InstallUpdateService|Starting update client /tmp/radarr_update/Radarr.Update.exe
2021-1-19 13:33:48.3|Info|InstallUpdateService|Radarr will restart shortly.
.. then it stops..

is the .Net version even available on the Synology?

**Comment by bakerboy448** [comment]
@rlangtind the native Synology app is unrelated to this issue as it is certainly not on Net5. Last I saw the SynoCommunity Package was still on 3.0.0 (latest stable is 3.0.1).  

Updating the package as an application (I.e radarr self updates) I believe is also blocked as Syno now runs applications as a Quasi-docker. 
https://github.com/Radarr/Radarr/issues/5633

talk to SynoCommunity about their package; we don’t have anything to do with it

we generally recommend running via docker on NAS

**Comment by ta264** [comment]
Confirmed, this is broken on 5.18 but working on 5.20 (on x64).  I'd say it's not worth the effort to fix on 5.18 and we just declare 5.20 the minimum required version.
