### ISSUE TITLE
Radarr does not honor the folder set in lists (IMDB) settings

### ISSUE THREAD

**Issue by stappel** [Radarr/Radarr#5787]
**Describe the bug**
I use the IMDB import list to get wanted movies from IMDB. In the settings i selected /moves as destination folder.
When i flag a new move in IMDB it gets added by radarr, but with the wrong destination path (/downloads).

**To Reproduce**
Add IMDB as list provider
Select a new movie in IMDB and set it on the watch list
See it gets added automatically in radarr
check path in movie list in radarr

**Expected behavior**
to use the path set in imdb list provider

**Screenshots**
![image](https://user-images.githubusercontent.com/13430384/105048517-f4cce000-5a6b-11eb-8186-93c2398e7216.png)
![image](https://user-images.githubusercontent.com/13430384/105048620-0dd59100-5a6c-11eb-8efa-e35023c49534.png)
![image](https://user-images.githubusercontent.com/13430384/105048672-1af28000-5a6c-11eb-9754-88c943e5e777.png)

**Platform Information (please complete the following information):**
 - OS: Ubuntu 20.04
 - Docker: Yes
 - Mono or .NET Version (System -> Status): included in docker image (linuxserver/radarr:latest)
 - Browser and Version (Only needed for UI issues): n/a
 - Radarr Version: latest 3.0.1.4259
 - Radarr Branch: master

**Comment by bakerboy448** [comment]
1) Fix your paths unless you hate your harddrives  [TRaSH's Guide](https://trash-guides.info/Misc/how-to-set-up-hardlinks-and-atomic-moves/)  [Docker Guide](https://wiki.servarr.com/Docker_Guide)
2) Any chance you're behind a reverse proxy and didn't make the [SignalR changes](https://wiki.servarr.com/Radarr_System#Could_not_connect_to_signalR)?
3) 
Support Requests -> [Reddit](https://www.reddit.com/r/radarr/) or [Discord](https://discord.gg/r5wJPt9)

Pretty sure it is not a bug and is a setup issue, but i'll hold off on closing for the moment

**Comment by stappel** [comment]
Both paths are correctly mapped to the docker image. In Radarr both are also visible in Settings -> Media Management.
![image](https://user-images.githubusercontent.com/13430384/105510386-dd416180-5cce-11eb-8260-92231b58c299.png)

No proxy involved. all local LAN

**Comment by bakerboy448** [comment]
one should never have their downloads folder as a root folder....the only thing radarr should do with a downloads folder is import from it.

also again, fix your docker mounts unless you like double seed space and slow i/o intensive copy deletes

Do you have any other lists setup

also hop on one of these and work through to figure it out
Support Requests -> [Reddit](https://www.reddit.com/r/radarr/) or [Discord](https://discord.gg/r5wJPt9)

**Comment by stappel** [comment]
the /movies is a nfs mount on a different host. it is intentionally to have it copied to it after download is complete.
/download is local, fast.

the screenshot is just to show it has access to it. normally it only has /movies in media management.

no other lists as source defined

**Comment by cableghost** [comment]
This is occurring to me as well. Syncing of list (IMDb) creates the Movie and sets the 'Path' in radarr to that of my download folder, not my root folder.

**Comment by Qstick** [comment]
I can't reproduce this behavior

**Comment by stappel** [comment]
Removing and adding the IMDB list provider looks like it solved the issue.
it now honors the correct folder.

so closing it for me.
