### ISSUE TITLE
Import failed, path does not exist or is not accessible by Radarr

### ISSUE THREAD

**Issue by seriosbrad** [Radarr/Radarr#579]
> Import failed, path does not exist or is not accessible by Radarr: E:\Downloads\Usenet\Complete\Movies\Movie Title.2016.1080p.WEB-DL.cp(ttxxxxxxx)

My log is being spammed with dozens of these messages every few minutes.  I'm not sure where it's getting the information that Radarr should be trying to import these movies from that directory. The movies have already been imported using the "Import Existing Movies On Disk" tool from "G:\Movies", not the directory in the error. 

Windows
0.2.0.281 nightly

**Edit:**
I seem to have fixed it (fingers crossed; knock on wood).  In December, before I had discovered Radarr, I changed the download location for SABnzbd from "E:\Downloads\Usenet\Complete\Movies" to "G:\Downloads\Usenet\Complete\Movies" due to acquiring a new storage drive.  I'm assuming Radarr was peaking into SAB's history and looking for stuff and failing because of the directory changes to. Clearing SAB's history seems to have resolved it.

**Comment by galli-leo** [comment]
Yeah it looks through your SAB history and sees if any if your movies have been downloaded.
