### ISSUE TITLE
YouTube trailers do not play from scraped data

### ISSUE THREAD

**Issue by bushbrother** [Radarr/Radarr#5796]
Currently the scraper puts an https:// link, this is not compatible with the YouTube plugin, it needs to be in plugin format with YouTube ID

**To Reproduce**
Enable "Kodi (XBMC) / Emby Metadata" scraping in Settings -> Metadata
When a movie is added the .nfo and images are all created but the Trailer URL is in a format that does not work with Kodi YouTube plugin.

Currently the URL is generated as the https:// link to the video ID, this caused an error in Kodi to say:

ERROR: Open - error probing input format, https://www.youtube.com/watch?v=xxxxxxxxxx

I have raised a pull request with the fix.

**Expected behavior**
It is expected that the URL is created in the plugin:// format like:

plugin://plugin.video.youtube/play/?video_id=xxxxxxxxxx

This seems to have been raised and resolved before here: https://github.com/Radarr/Radarr/pull/3609

Current branches seem to have reverted back to normal https:// URL format.

**Platform Information (please complete the following information):**
 - OS: Libreelec
 - Docker: No
 - Radarr Version: 3.0.2.4446
 - Radarr Branch: nightly/develop
 - 
**Trace Logs**
Logs not attached as there is no error generated here, the code is doing what it is told to do ...

**Comment by bakerboy448** [comment]
you didn't actually raise a pull request to the Radarr/Radarr Repo 

Take a look at <https://github.com/Radarr/Radarr/blob/develop/CONTRIBUTING.md#contributing-code>

Feel free to hop on discord if you need some help :)
