### ISSUE TITLE
Cannot delete profile that is not being used

### ISSUE THREAD

**Issue by charliwest** [Radarr/Radarr#5800]
As the title says, I was doing some clean up for an old bug that is fixed.
Cleaning up my profile meant moving all films from the old broken profile to the new working one. I moved them all, then went to delete the old broken profile. Worked for a bunch of profiles, but this one just won't allow me to delete it.

<img width="978" alt="Screenshot 2021-01-22 at 15 53 57" src="https://user-images.githubusercontent.com/7933076/105507004-f6481380-5cca-11eb-95a2-6df861e3dd37.png">
<img width="795" alt="Screenshot 2021-01-22 at 15 54 28" src="https://user-images.githubusercontent.com/7933076/105507052-0233d580-5ccb-11eb-9117-555a7c059efa.png">
<img width="319" alt="Screenshot 2021-01-22 at 15 54 37" src="https://user-images.githubusercontent.com/7933076/105507057-05c75c80-5ccb-11eb-9e0e-31fdf9bfd17c.png">

Log here https://gist.github.com/charliwest/708e2737ce9bfd502bc2a771b81d6ad1

**Comment by bakerboy448** [comment]
Support Requests -> [Reddit](https://www.reddit.com/r/radarr/) or [Discord](https://discord.gg/r5wJPt9)

The profile is still in use...probably via a list
