### ISSUE TITLE
Failure to login, and multiple UI failures when using URL Base

### ISSUE THREAD

**Issue by apwelsh** [Radarr/Radarr#5805]
When Radarr is configured with a URL Base, and using a reverse proxy, the application fails to authenticate and presents the url: http://docker.host:1080/radarr/login?returnUrl=/radarr/

If I reconfigure the docker image to use port redirection, and remove the UrlBase entry from XML, then radarr works fine, but this is not a viable solution.

**To Reproduce**
**config.xml**
<Config>
  <LogLevel>Info</LogLevel>
  <Port>7878</Port>
  <UrlBase>/radarr</UrlBase>
  <BindAddress>*</BindAddress>
  <SslPort>9898</SslPort>
  <EnableSsl>False</EnableSsl>

Restart docker with above configuration  (UrlBase).  Point browser to radarr instance Using the 

**Expected behavior**
The user should be logged in, and the main application rendered.

**Screenshots**

<img width="1350" alt="image" src="https://user-images.githubusercontent.com/15111403/105618688-07625480-5d9f-11eb-94ae-5ad3d29649b1.png">

<img width="1350" alt="image" src="https://user-images.githubusercontent.com/15111403/105618676-edc10d00-5d9e-11eb-9fd5-106564b25a76.png">

**Platform Information (please complete the following information):**
 - OS: MacOS, iOS
 - Docker: YES
 - Mono or .NET Version (System -> Status): linux server image (Version 3.1.0)
 - Browser and Version (Only needed for UI issues): Safari 14.0.2, Chrome 88.0.4324.96, Edge 88.0.705.50
 - Radarr Version: 3.0.1.4259 (3.0.1.4259-ls90 by linuxserver.io)
 - Radarr Branch: ??

**Trace Logs**
Turn on Trace logs under Settings -> General and wait for the bug to occur again. 
**Trace logs not possible, as cannot login.**

**Comment by austinwbest** [comment]
This was fixed, just might not be in your branch yet.

**Comment by bakerboy448** [comment]
@austinwbest I’m thinking link the commit and close this?

**Comment by Qstick** [comment]
What fixed this?

**Comment by bakerboy448** [comment]
IS this still occuring in 3.0.2?

**Comment by bakerboy448** [comment]
Closing pending further information and confirmation this still occurs.

logs wise, the network calls and any dev console spew from your browser would be useful.
