### ISSUE TITLE
Movie First Letter Naming Token

### ISSUE THREAD

**Issue by Cerothen** [Radarr/Radarr#581]
Good Day,

I installed Radarr excited about a CP replacement and have a few requests suggestions that I am hoping can be incorporated:
- [x] When scraping movies if the tt code is in the file name use that as a search criteria (I would suggest the TMDB but I think I heard once that it isnt a fixed length and has no identifiable markings)
- [ ] Folder "first letter" option resolving accented characters to their associated letter (é = e) and numbers/symbols to 0-9 (Or perhaps something configurable).

I didn't notice anything like this in any other issues but forgive me if anything is a duplicate.

**Comment by galli-leo** [comment]
We already do number one.

**Comment by delphiactual** [comment]
Number two should also apply to movies like `Æon Flux`
