### ISSUE TITLE
Folder is not writable by user abc

### ISSUE THREAD

**Issue by muadxili** [Radarr/Radarr#5826]
**Describe the bug**
Hello,

I'm currently moving from my native Docker setup to my new Docker with UNRaid setup. So far so good, Sonarr and Lidarr are running correctly  but I have some issues with Radarr.
When I map a folder, Radarr does not seems to have the permissions to write on this folder. Nevertheless, It's the same folder and permissions than in Sonarr and Lidarr which are both OK.

The folder is a SMB mount \\192.168.2.100\Data1 in /mnt/remotes/192.168.2.100_Data1

I have mapped /movies folder to /mnt/remotes/192.168.2.100_Data1/Films/ but unable to add it to root folder, it ends up with a radarr_write_test.txt file in this folder.
Ditto for the blackhole which is also in Data1

I did several tests, everything seems ok in term of permissions: drwxrwxrwx 2 nobody users 0 Jan 25 23:51 movies
Just like with sonarr, but radarr can't write inside this folder...

Thanks for your help to solve this issue.

**Screenshots**

![2021-01-26 10_32_22-Window](https://user-images.githubusercontent.com/37447398/105827543-6c49c480-5fc2-11eb-8716-e59e89a0c1c3.png)

![2021-01-26 10_34_02-Window](https://user-images.githubusercontent.com/37447398/105827605-7bc90d80-5fc2-11eb-82fb-d96fefd58fb1.png)

**Platform Information (please complete the following information):**
 - OS: Unraid
 - Docker: Yes
 - Mono or .NET Version (System -> Status): LSIO Image
 - Browser and Version (Only needed for UI issues): Firefox
 - Radarr Version:
 - Radarr Branch: latest

**Trace Logs**
Turn on Trace logs under Settings -> General and wait for the bug to occur again. 
2021-1-26 10:33:13.9|Error|TorrentBlackhole|Folder '/downloads/watch/' is not writable.
2021-1-26 10:33:13.9|Error|TorrentBlackhole|Folder '/downloads/download/' is not writable.
2021-1-26 10:33:13.9|Warn|RadarrErrorPipeline|Invalid request Validation failed: 
 -- TorrentFolder: Unable to write to folder
 -- WatchFolder: Unable to write to folder

2021-1-26 10:33:52.1|Warn|RadarrErrorPipeline|Invalid request Validation failed: 
 -- Path: Folder is not writable by user abc

**Comment by ta264** [comment]
You didn't specify the version which was the crucial bit of information.  This should already be fixed in develop builds I think.
