### ISSUE TITLE
Monitor specific folder for new movies

### ISSUE THREAD

**Issue by Bryant2of3** [Radarr/Radarr#5829]
Would like to see radarr monitor specific folders which movies were added to and then moved into a default folder. Even if movie is not listed. And a function that deletes files and folder after moving it.

Couchpotato currently does that which is cool.

**Comment by bakerboy448** [comment]
No plans to re-add drone factory 

hop on discord to discuss your use case further; there’s likely a proper way to do what you want to do, but need to know the why
