### ISSUE TITLE
New Dolby Vision Tag

### ISSUE THREAD

**Issue by Defs3c** [Radarr/Radarr#5835]
Since DV has become more popular and I am grabbing them, Radarr has grabbed "proper" 4K HDR releases to replace them which are often separate to the DV releases and only in standard HDR10. 

I think with DV becoming bigger and bigger as its now supported in MKV that perhaps a new tag - something like Remux-2160p-DV or Remux-2160p-DoVi may be useful so Radarr can distinguish between standard HDR10 and DV. This would also give the option to prefer DV releases or keep looking for DV releases until the cutoff is met.

I could add DV or DoVi into the restrictions as a must but that'd hinder downloading 4K video that don't have a DV release or the 1080p files that don't have a 4K release.

**Comment by bakerboy448** [comment]
Dupe #4844

**Comment by bakerboy448** [comment]
CFs can help a bit in the interim 
https://trash-guides.info/Radarr/V3/Collection-of-Custom-Formats-for-RadarrV3/
