### ISSUE TITLE
Cannot disable images in emby metadata

### ISSUE THREAD

**Issue by edrock200** [Radarr/Radarr#5836]
**Describe the bug**
On the last develop release as well as the last week or so of nightlys for radarr, if metadata for emby is enabled, you can't untick the poster option. If you untick and save it auto reticks.
**To Reproduce**
Enable emby/kodi metadata with nfo and images. Click save. Open up again and untick images, click save. If you open it again, posters is still ticked. It won't apply with images disabled.

**Expected behavior**
Images can be disabled with nfos enabled.

**Platform Information (please complete the following information):**
 - OS: Ubuntu 18.04
 - Docker: Yes
 - .NET (5.0.2)
 - Browser and Version - reproducible on mobile and desktop chrome and desktop IE
 - Radarr Version: 3.0.2.4504-ls11 by linuxserver.io
 - Radarr Branch: nightly (started on develop, switched to nightly to see if it would fix, can't revert because nightly seems to have updated the database and get db error if I revert.)

**Trace Logs**
https://pastebin.com/51Wr39jV

I have reproduced this on two of my radarr instances as well as two of a friend's that are on completely different setups. Thanks in advance!

**Comment by Qstick** [comment]
@ta264 this is DB mapper related, it's only saving "true" values for checkboxes on Provider Settings fields

Change to false

Object is correct at ProviderModuleBase L96:

![image](https://user-images.githubusercontent.com/376117/107161981-459a6f00-696e-11eb-914e-93f38b2ddeee.png)

Then what gets put in the DB:

```
{
  "movieMetadata": true,
  "movieMetadataLanguage": 1,
  "isValid": true
}
```

This is troublesome as the default value for MovieImages is true, thus when its not saved to DB as false, it picks up true. Meaning you can never toggle it to false. Map to object thing again?

**Comment by Qstick** [comment]
Changing to Ignore when Null instead of Default seems to fix
![image](https://user-images.githubusercontent.com/376117/107162191-85ae2180-696f-11eb-8ef0-24674c2db3a6.png)
