### ISSUE TITLE
HDBits 'prefer/require internal release'

### ISSUE THREAD

**Issue by emilsvennesson** [Radarr/Radarr#584]
First of all, thanks a lot for fixing the HDBits indexer! :-) 

It'd be very nice to have an internal releases-only option available in the indexer settings as well. This is possible by sending 'origin: 1' in the POST request to the API.

**Comment by onedr0p** [comment]
Do you want the `Required Internal` flag only set on RSS Sync? I think that makes the most sense. That way you can still manually search for other releases on HD-Bits.

**Comment by emilsvennesson** [comment]
@onedr0p Yeah, that's a good idea. :-) The other releases should probably have something like 'Not an internal release' on the 'Release Rejected' list when this setting is activated.

**Comment by onedr0p** [comment]
@emilsvennesson that will not be possible for awhile. I have made it so when you check Require Internal RSS Sync will only retrieve Internals, but when you manually search it will include everything. I also added a setting 'Prefer Internal' which on manual search should prefer internal when manually searching.

**Comment by onedr0p** [comment]
I'll get back to this, for some reason it is not working and my local dev build won't launch..

**Comment by emilsvennesson** [comment]
@onedr0p Any reason why this was closed?

**Comment by onedr0p** [comment]
It's added in the next release.

**Comment by emilsvennesson** [comment]
@onedr0p Nice! Thanks a lot. :-)

**Comment by captainnapalm** [comment]
Is this option now gone? I can't seem to see an option for HDBits for Required Internal anymore and I have started to see scene releases be grabbed unexpectedly.
