### ISSUE TITLE
update service painfully slow

### ISSUE THREAD

**Issue by astlaurent** [Radarr/Radarr#5842]
I noticed that when Radarr goes to update it is now painfully slow taking hours to update. a manual install takes a couple minutes though. basically an update that launched at 1145pm last night is still running at 8:47am this morning. Disk is showing healthy and file copies go typically quick however it looks like it takes like 30 seconds for radarr to transfer a single file. 

you can see my logs here. First section is the app logs showing the update triggering followed by the update logs
https://pastebin.com/xcQrsZYH

**Platform Information (please complete the following information):**
 - OS: Windows 10
 - Docker: no 
 - Mono or .NET Version (System -> Status): dotnet
 - Browser and Version (Only needed for UI issues): 
 - Radarr Version: 
 - Radarr Branch: nightly

**Comment by astlaurent** [comment]
Also to add onto this i did a complete remove/reinstall, disabled AV protection, did not import any settings or db, changed the branch to develop and enabled debug logging. then launched the update manually through the gui and it is still painfully slow. 
debug log is here. I only waited around 8 minutes before deciding it wasn't going to be any better. the log pretty much shows the same behavior
https://pastebin.com/PjmDxaNS

**Comment by ta264** [comment]
I would say this is likely something odd about your setup otherwise we'd have heard about this before. You'll have more luck tracking it down via the discord channel I think.

**Comment by astlaurent** [comment]
thanks, i noticed sonarr does something similar but doesn't quite take as long like a couple hours vs 8 hours. from the logs it looks like it started around 11/22/20 but i can't track down anything that changed on my side. one thing i noticed is the disk space scan takes forever to load in the gui and in the debug log during the update it looks like it might check that via api as well and it takes really long to respond back in the logs

**Comment by bakerboy448** [comment]
Hop to [Discord](https://discord.gg/r5wJPt9)

Sounds maybe your disks are going or other I/O issues?

**Comment by astlaurent** [comment]
thanks guys, i think i figured it out and it was odd. I have a media card reader on my computer and i noticed i had an empty sd > micro sd converter sitting in it empty. out of curiosity i took it out and the disk scan completed right away and the update went perfect.
