### ISSUE TITLE
Update folder when movie year has been added

### ISSUE THREAD

**Issue by imran0** [Radarr/Radarr#5853]
Currently Radarr creates folders for each movie based on **FILM NAME (YEAR)**, however this doesn't work on films that don't have a year associated to them yet often leaving the ane like "A film name (0)", later during the year(s) when the film meta has been updated to include a year the file path is not updated.

Is it possible to build a fix for this?

**Comment by bakerboy448** [comment]
No plans to automate renaming at this time


for renaming movie folders, see this wiki article 
https://wiki.servarr.com/Radarr_Tips_and_Tricks#Rename_Movie_Folders
