### ISSUE TITLE
I prefer a new program. Just to split the normal stuff from the Porns and also have some optimations for it

### ISSUE THREAD

**Issue by Istalri-dragon** [Radarr/Radarr#5859]
I prefer a new program. Just to split the normal stuff from the Porns and also have some optimations for it

_Originally posted by @Animizio in https://github.com/Radarr/Radarr/issues/4254#issuecomment-656017186_

Was a separate program ever created? I wasnt able to find one. Is there still plans to make one?

**Comment by bakerboy448** [comment]
Bonarr never went anywhere.

Also Github is not the place for these questions as this is neither a Bug nor a Feature Request nor applicable to Radarr;  better asked on Reddit or Discord
