### ISSUE TITLE
Add new import TV movies fails

### ISSUE THREAD

**Issue by Cobragt92** [Radarr/Radarr#5867]
**Describe the bug**
When you try to add "TV Movies" like this: https://www.themoviedb.org/tv/19614-it?language=en-CA it does not find the movie even if you try to add new and use tmdb:19614 it comes up with a different movie. As you can see from the movie database it it is there but why does Radarr not allow this?

**To Reproduce**

**Expected behavior**
 It should use tmdb:19614 and import or add it (1990) but it does not, it wants to use Fade To Black (2004)

**Screenshots**

![image](https://user-images.githubusercontent.com/78600306/107038456-8d60a100-678a-11eb-8fe7-f87d35e7c068.png)

**Platform Information (please complete the following information):**
 - OS: Unraid 6.9.0 Rc2
 - Docker: Yes
 - Mono or .NET Version (System -> Status): 
 - Browser and Version (Only needed for UI issues): chrome 88.0.4324.104
 - Radarr Version: 3.0.1.4259
 - Radarr Branch: 3.0.1.4259

**Trace Logs**
Turn on Trace logs under Settings -> General and wait for the bug to occur again. 
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**

**Comment by ta264** [comment]
That's a tv show

**Comment by bakerboy448** [comment]
https://www.themoviedb.org/tv/19614-it?language=en-CA  Is a tv show

Sonarr is not for tv shows (tv movies included as TMDB has them classified as tv not movie)

**Comment by Qstick** [comment]
TV movies are fine, But that's classified as a mini-series and not a movie.
