### ISSUE TITLE
To be able to add or import TV Movies / Mini series

### ISSUE THREAD

**Issue by Cobragt92** [Radarr/Radarr#5868]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [When you try to add a TV mini series movie it doesn't]

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Please add the TV Movie mini series Movie to the add / Library import. These might be classified as mini series but are full length 1-2 hour movies. It should not matter if its labeled as TV movie or TV mini series Movie it should just add or import it. If the movie database has it in its list.

**Describe alternatives you've considered**

**Additional context**

**Comment by ta264** [comment]
Sonarr is for TV, Radarr is for Movies
