### ISSUE TITLE
Input fields on General Settings page are unsanitized

### ISSUE THREAD

**Issue by MBRO95** [Radarr/Radarr#5871]
**Describe the bug**
Recently discovered a bug in the General Settings/config.xml files.
Text entered into these fields appears to be processed through a URL decoder or some hash function that is converting characters, causing certain character combinations in a text string to be stored improperly resulting in the password desired != the password being saved. This is happening in both master and develop branches latest release.
**This DOES affect Sonarr v3 as well:** [view issue here](https://github.com/Sonarr/Sonarr/issues/4309)

**To Reproduce**
1. Got to page: http://localhost:7878/settings/general
2. Fields affected (so far): SSL Cert Password, Basic Auth Password
6. Set User Password field in Basic Auth settings to the text Pa$$%20Word, save changes
7. Alternatively, create a cert with passphrase as Pa$$%20Word. Try to specify cert file and passphrase, it will error out saying it's invalid password or cert match.
8. Review C:\ProgramData\Radarr|Sonarr\config.xml --> <SslCertPassword>Pa$$+Word</SslCertPassword>
9. Open radarr|sonarr.db > Navigate to 'Users' table > Notice 'Password' column is encrypted password
10. Calculate SHA256 hash for Pa$$%20Word. Notice it does not match the Password column contents.
11. Calculate SHA256 hash for Pa$$+Word. Notice it matches the Password column contents.
9. Caveat is that you can manually modify the config.xml and database values to the proper text strings and they WILL work. So deducing it's the web interface field/processing behavior that's awry. Anyways, these errors prevent saving on General Settings page.

**Expected behavior**
Configuring SSL Certificates and Basic Authentication passwords properly in the General Settings page.
Having expected passwords written to config.xml and raddar|sonnar.db, respectively.

**Platform Information (please complete the following information):**
 - OS: Windows 10 Pro 20H2
 - Docker: No
 - Mono or .NET Version (System -> Status): Yes (3.1.10)
 - Browser and Version (Only needed for UI issues): Chrome 88.0.4324.146 (Official Build) (x86_64)
 - Radarr Version: 3.0.2.4552
 - Radarr Branch: develop

**Trace Logs**
Not providing, I already remedied these issues manually, not going to screw it all up again.

**Comment by bakerboy448** [comment]
If it's reproducible on Sonarr v3 as well, open a ticket up there and we can leverage the fix when pulled downstream

**Comment by MBRO95** [comment]
Thanks. It is not reproducible in Sonarr v3...maybe a port issue? I added some additional context above

**Comment by MBRO95** [comment]
Opened: https://github.com/Sonarr/Sonarr/issues/4309

**Comment by bakerboy448** [comment]
can you edit both this OP and the Sonarr OP to follow the bug report template?
