### ISSUE TITLE
Rarbg - Indexer API call returned error 10: Cant find imdb in database

### ISSUE THREAD

**Issue by jOOc** [Radarr/Radarr#590]
When going to wanted and clicking "search selected" I sometimes end up with this message. After that the indexer (rarbg) stops to work. I need to go into indexers and click test on rargb again. But as I have this movie (and others with the same error) in the list the search stops working all the time
![image](https://cloud.githubusercontent.com/assets/9382342/22602795/00f26814-ea45-11e6-98cc-8af51c927c3b.png)

Here are output from the trace log
`17-2-3 18:50:10.3|Info|NzbSearchService|Searching 1 indexers for [Sherlock: The Final Problem]
17-2-3 18:50:10.3|Debug|Rarbg|Downloading Feed http://torrentapi.org/pubapi_v2.php?mode=search&search_imdb=tt3845892&ranked=0&category=movies&limit=100&token=(removed)&format=json_extended&app_id=Sonarr
17-2-3 18:50:15.4|Warn|Rarbg|Indexer API call returned error 10: Cant find imdb in database. Are you sure this imdb exists? - http://torrentapi.org/pubapi_v2.php?mode=search&search_imdb=tt3845892&ranked=0&category=movies&limit=100&token=(removed)&format=json_extended&app_id=Sonarr

[v0.2.0.285] NzbDrone.Core.Indexers.Exceptions.IndexerException: Indexer API call returned error 10: Cant find imdb in database. Are you sure this imdb exists?
   at NzbDrone.Core.Indexers.Rarbg.RarbgParser.ParseResponse(IndexerResponse indexerResponse) in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\Rarbg\RarbgParser.cs:line 38
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 297
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchReleases(IndexerPageableRequestChain pageableRequestChain, Boolean isRecent) in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 154

17-2-3 18:50:15.4|Debug|NzbSearchService|Total of 0 reports were found for [Sherlock: The Final Problem] from 1 indexers`

**Comment by ashishdhngr** [comment]
I just ran into a similar issue. 
![screen shot 2017-02-03 at 1 33 25 pm](https://cloud.githubusercontent.com/assets/25535537/22603493/a589a3c2-ea15-11e6-8085-5c2536e0f87a.png)


As you can see it resolved it self after a couple of minutes, but the problem keeps persisting. 

![screen shot 2017-02-03 at 1 32 42 pm](https://cloud.githubusercontent.com/assets/25535537/22603527/ca4f457c-ea15-11e6-88b4-59ca5d5c2179.png)

**Comment by jOOc** [comment]
But as soon as the search hit a movie that it cant find (probably the same as last) it stops searching for the movies that comes after in the list.

**Comment by onedr0p** [comment]
Not a solution on Radarr side of things but Maybe you guys could use jackett? It supports public trackers.

**Comment by jOOc** [comment]
@onedr0p Im testing Jackett out now

**Comment by galli-leo** [comment]
Sadly I think this issue is not on our end. What I think is happening is that OMDBAPI (The api used by many to grab info on an imdb movie) is being ddosed. They are currently trying to get their servers back up again.
