### ISSUE TITLE
Custom formats that are assigned a negative value in the respective profile, with a red background instead of blue, green if positive and blue if zero.

### ISSUE THREAD

**Issue by Havokdan** [Radarr/Radarr#5900]
Custom formats that are assigned a negative value in the respective profile, with a red background instead of blue, green if positive and blue if zero. At least when displayed in search results.

**Comment by bakerboy448** [comment]
What’s the use case other than some pretty optics?

**Comment by Havokdan** [comment]
Well, when looking at the results it would be more evident when looking at results, I think that in Sonarr there is something like that. Ok then, thanks for listening. :)

**Comment by Qstick** [comment]
Closing no template, I'm not sure we want to turn this page into a rainbow either as of current time.

**Comment by Havokdan** [comment]
![imagem_2021-02-08_132817](https://user-images.githubusercontent.com/6549729/107248855-80091800-6a11-11eb-8606-442d5a1db452.png)
My idea would be to use Sonarr's "Releases Profiles" color system, which uses different colors, red for terms that "Must Not Contain", orange (or it would be yellow, I'm bad with color names) for negative values ​​in "Preferred "and gray (or is it a dark blue ??) for positive values ​​in" Preferred ", and use this logic and adapt for this part of Radarr:

![imagem_2021-02-08_133345](https://user-images.githubusercontent.com/6549729/107249589-42f15580-6a12-11eb-8f77-d9a3b468a606.png)

that in the example in the image above, all the terms that appear have a negative value in the respective film profile, so they would then be red (just an example, the idea is to have a different color for negative, positive and zero), only when displayed in the " Format "in the" Search "tab of each movie.

Well, I just posted to try to explain myself better, I use the Google translator, so I may not have been clear on my request, anyway, thanks. :)
