### ISSUE TITLE
Able to delete a root folder despite import lists using the root folder

### ISSUE THREAD

**Issue by MrAnanas** [Radarr/Radarr#5904]
**Describe the bug**

 if you make a new root folder (d:) and delete another root folder (c:) which you do not use anymore, then import lists continue to use the old "c:" folder despite showing the new "d:" folder in the lists setup form.... to avoid this you need to have two root folders and then select the other one and then back to the one you want to use.... I don't know why this is how it is but I checked the database and made sure this is the problem... Just wanted to let you know in case you want to do something about it... (I was getting movies added with "Root folder missing" errors)

**To Reproduce**

1. The root folder should not be deleted if assigned to anything!

**Screenshots**

**Platform Information (please complete the following information):**
 - OS:  unRaid 6.9.RC1
 - Docker:  Yes
 - Mono or .NET Version (System -> Status): 5 .NET.0.2
 - Browser and Version (Only needed for UI issues):  Chrome
 - Radarr Version:  3.1.0.4610
 - Radarr Branch:  nightly

**Trace Logs**
Turn on Trace logs under Settings -> General and wait for the bug to occur again. 
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**

**Comment by bakerboy448** [comment]
Fixed by #5908

**Comment by bakerboy448** [comment]
Fixed by https://github.com/Radarr/Radarr/commit/2fd030bd5c94ee2614354292ec93da7ad694f0a2
