### ISSUE TITLE
Add Formats column to movies list + Filter by option

### ISSUE THREAD

**Issue by GodKratos** [Radarr/Radarr#5909]
**Describe the solution you'd like**
I'd like the ability to add a column for Custom Formats in use on the Movies table view.
You can see the Formats on the files tab of an individual movie but being able to see that on the movie list without having to open each movie would be terrific.
Alternatively, having that as a filter option so you could filter by custom formats would be excellent

**Describe alternatives you've considered**
Another alternative would be to add a filter on the filename. There is a path filter but that only includes the folder name whereas my custom filters are specific to the filename.

**Additional context**
I have a bunch of movies added and I'd like to know which ones don't match a specific custom format at a glance without having to check them all individually.

**Comment by austinwbest** [comment]
Custom formats are calculated and not stored. The load wouldn't be acceptable for a filter option.

**Comment by GodKratos** [comment]
What about the alternative option then?
How about adding a filter for Filename as well as Path?
