### ISSUE TITLE
Multilingual DVD/BR feature request

### ISSUE THREAD

**Issue by kalhel** [Radarr/Radarr#591]
Hi,

I have spanish family who wants see films with spanish audio, and i prefer VO. It would be great download fiilms with both audio.

Thanks!!

**Comment by Firemad03** [comment]
Well it will be hard to find for Radarr. Lot of Multi movie that have the word multi in the title is english/french for some reasons. Your best bet will be to find a movie in english and setup radarr for spanish so you have 2 differents profiles. Yes you will have both movies but in Plex for example you can create 2 different group.

In Radarr they have the preferred tag in profile. You can set a profile in spanish with the word multi in the prefered tag. I guess this way you will find what you want : a movie with both spanish and english for the audio.

![image](https://cloud.githubusercontent.com/assets/24792889/22612588/a975d24c-ea3f-11e6-8ea0-c37103fd86fe.png)

I'm using the nightly build and I don't know if the normal build have this option.
