### ISSUE TITLE
{Original Title} folder renaming has stopped working

### ISSUE THREAD

**Issue by fragande** [Radarr/Radarr#5919]
**Describe the bug**

Using `{Original Title}` for `Movie Folder Format` does not work as intended in recent versions (v3?). Instead of what is displayed in the example ( `Example: The.Movie.Title.2010.1080p.BluRay.DTS.x264-EVOLVE` ) it results in: `The Movie Title 2010`. 

**To Reproduce**

Simply use  `{Original Title}` as `Movie Folder Format`.

**Expected behavior**

I expect `{Original Title}` to result in what the example states, i.e. `The.Movie.Title.2010.1080p.BluRay.DTS.x264-EVOLVE`.

**Screenshots**

**Platform Information (please complete the following information):**
 - OS:  Windows 10 2004
 - Docker:  No
 - Mono or .NET Version (System -> Status):  .Net Core 3.1.10
 - Radarr Version:  3.0.2.4552
 - Radarr Branch:  master

**Trace Logs**
Due to privacy concerns I can't post that, go ahead and close if absolutely needed. Looking through the logs there doesn't seem to be any errors related to the folder creation at all.

**Comment by bakerboy448** [comment]
https://wiki.servarr.com/Radarr_FAQ#Movie_Folders_Named_Incorrectly

**Comment by fragande** [comment]
> 
> 
> https://wiki.servarr.com/Radarr_FAQ#Movie_Folders_Named_Incorrectly
> 
> > Movie Folder Naming Formats from v0.2 that include dynamic names such as File properties in the movie folder name such as {Movie.Title}.{Release Year}.{Quality.Full}-{MediaInfo.Simple}{`Release.Group} will not work in v3.

That's very unfortunate and real deal breaker for me personally. I guess I would have to downgrade to v2 then. There's no setting for disabling auto updates on Windows 10, is there another way to block these?

**Comment by bakerboy448** [comment]
V0.2 will likely have its server side access disabled in the next month or two

Nope.

Most folks who absolutely require something like that use it to create a sub folder in your file naming scheme and then your file with I’ll within that sub folder

**Comment by fragande** [comment]
> 
> 
> V0.2 will likely have its server side access disabled in the next month or two
> 
> Nope.
> 
> Most folks who absolutely require something like that use it to create a sub folder in your file naming scheme and then your file with I’ll within that sub folder

I see, thank you. Creating an additional sub folder wouldn't really help. Guess I'll have to work around it as best as I can by setting up an auto renaming tool or similar. Never caused me any issues at all so I would really like to keep it as it's the most usable format for me by far.

Maybe it would be a good idea to make `{Original Title}` an `Invalid Format` for folder naming as it's very confusing that it still displays the correct example when using it.

**Comment by austinwbest** [comment]
> > V0.2 will likely have its server side access disabled in the next month or two
> > Nope.
> > Most folks who absolutely require something like that use it to create a sub folder in your file naming scheme and then your file with I’ll within that sub folder
> 
> I see, thank you. Creating an additional sub folder wouldn't really help. Guess I'll have to work around it as best as I can by setting up an auto renaming tool or similar. Never caused me any issues at all so I would really like to keep it as it's the most usable format for me by far.
> 
> Maybe it would be a good idea to make `{Original Title}` an `Invalid Format` for folder naming as it's very confusing that it still displays the correct example when using it, when in reality is doesn't work anymore.

Remember to also have your script unmonitor everything it does that too as well as a scan will show it as missing and download it again. And keep in mind it is use at your own risk which means all issues raised will be closed with a response of Upgrade.

You can set your branch to anything invalid "dont-update" as well to stick to 0.2

Best of luck with it!

**Comment by fragande** [comment]
> 
> 
> > > V0.2 will likely have its server side access disabled in the next month or two
> > > Nope.
> > > Most folks who absolutely require something like that use it to create a sub folder in your file naming scheme and then your file with I’ll within that sub folder
> > 
> > 
> > I see, thank you. Creating an additional sub folder wouldn't really help. Guess I'll have to work around it as best as I can by setting up an auto renaming tool or similar. Never caused me any issues at all so I would really like to keep it as it's the most usable format for me by far.
> > Maybe it would be a good idea to make `{Original Title}` an `Invalid Format` for folder naming as it's very confusing that it still displays the correct example when using it, when in reality is doesn't work anymore.
> 
> Remember to also have your script unmonitor everything it does that too as well as a scan will show it as missing and download it again. And keep in mind it is use at your own risk which means all issues raised will be closed with a response of Upgrade.
> 
> You can set your branch to anything invalid "dont-update" as well to stick to 0.2
> 
> Best of luck with it!

Thank you! Yes, I realize renaming will create problems. Will probably try to stay on v2 as long as possible then, thank you for the tip. I'm not sure what server side access @bakerboy448 is referring to (I thought it was all locally hosted).

Also apologize for my lack of searching skills, I see this issue has been brought up several times before on reddit.
