### ISSUE TITLE
Movies Sorted into Wrong Directory

### ISSUE THREAD

**Issue by scuppasteve** [Radarr/Radarr#592]
Is anyone else having an issue of items not being put in the right folders? i consistently have files in wrong directories and i cant seem to figure out why. It also seems to be loosing them, stuff gets imported and Plex identifies it and then it disappears.

So i only have 1 main directory
\Movies\
So like for example i regularly get
Cars.2006.1080p.BluRay.DTS-HD.x264.mkv
\Movies\Scarface (1983)\Cars.2006.1080p.BluRay.DTS-HD.x264.mkv
and Scarface.1983.1080p.BluRay.DTS.x264.mkv will end up in some other directory.
This doesn't affect movies that were imported already on the hard drive, but items that are downloaded through Radarr are affected. The majority of them go to the right location but like 25% end up in the wrong directory.

I have logging enabled, but there are so many movies in the system i can't find an instance where it is in the log.

**Comment by scuppasteve** [comment]
It seems to be a common case when downloading DVDrips as one of the two parts will go in the proper directory and the other ends up in a random directory. Then it screws up like the next 4 or 5 movies.

**Comment by jackflash1991** [comment]
I had this issue too. Files were abandoned in the Radarr folder and filled my unraid cache. Had to uninstall until this issue is closed. Props to that app though!

**Comment by scuppasteve** [comment]
I continue to see this issue, where if i add a bunch of movies to Radarr to monitor, it goes and adds them all to DL and then when they unpack they regularly get sorted into the wrong final directory
