### ISSUE TITLE
Upgrades to 'Proper' selectable based on group

### ISSUE THREAD

**Issue by houndtt** [Radarr/Radarr#5922]
**Is your feature request related to a problem? Please describe.**

I recently had my Radarr v3.0.2.4552 download a bunch of releases. For about two thirds of them these were legitimate upgrades (e.g. Web to Blu-ray) but in some of them they were downloading so called 'Proper' releases. The challenge is that these were selecting multi-language releases where English was not the primary language and this resulted in having to manually changing languages on viewing. In the end I just re-downloaded the straight English versions.

In one case however Radarr kept on re-downloading a 'Proper' and in the last case the language was not even English. So I eventually just removed monitoring on that movie. This is the specific example:

1. I had an original download of `Furious.Seven.2015.EXTENDED.720p.BluRay.x264-SPARKS` from many years ago
2. Recently, it was replaced by `Furious.Seven.2015.Pl.Dual.720p.Proper.BluRay.x264-FLAME` which had English as a second language
3. I re-downloaded a new copy using `Furious.7.2015.720p.BluRay.x264.DTS-WiKi`
4. Radarr once again replaced this with a download of `Furious.Seven.2015.Pl.Dual.720p.Proper.BluRay.x264-FLAME-Obfuscated` where English wasn't included at all
5. I re-downloaded the copy in step 3 and removed monitoring from the movie

**Describe the solution you'd like**

I note in a discussion on a related issue (https://github.com/Radarr/Radarr/issues/5637#issuecomment-751897001) that Radarr considers upgrades released by the same group as a 'Repack' and upgrades released by another group as a 'Proper'. If this is the case I would like for an advanced option in the configuration for when 'Upgrades Allowed' that would specify if repacks and propers are allowed or just repacks only. For me this should solve the problem.

**Describe alternatives you've considered**

I don't know if there is a way for Radarr to interrogate a download to determine if in a single-language or multi-language release that the primary language is English and if so then complete the upgrade and if not, reject the upgrade. That is another way which should resolve my current issue. The challenge I suspect is that the downloaded file would need to be inspected since as we saw in the scenario in step 4 above, the filename had 'Pl' which I assume represents Polish however Radarr still downloaded it because it thought it was English.

**Additional context**

I only have a very simple single profile configured in Radarr called 'HD-720p/1080p' where the language is set to English and I prefer downloads in the following order: `Bluray-720p`, `WEB 720p`, `Bluray-1080p`, `WEB 1080p`.

**Comment by bakerboy448** [comment]
Disable prefer repacks and proper and then use custom formats to fine tune for specific groups

https://wiki.servarr.com/Radarr_Settings#File_Management

https://trash-guides.info/Radarr/


Furious.Seven.2015.Pl.Dual.720p.Proper.BluRay.x264-FLAME-Obfuscated

Is Polish DUAL audio meaning Polish and English typically. Radarr can only work with what information is in the release name

**Comment by houndtt** [comment]
Thank you @bakerboy448, I didn't think of looking at the Wiki to see how to handle 'Propers and Repacks'. I have since changed the setting to be 'Do not Upgrade Automatically' and I guess that should fix things for me for the moment.

Yes, based on what was downloaded I think the uploaded meant dual audio Polish and English in the original (though the explicit languages were omitted). Furthermore, in the 'Obfuscated' release which seems to typically strip out extra subtitles and audio tracks the secondary English channel was stripped and thus the release was actually just Polish at that point.

**Comment by bakerboy448** [comment]
Got it. I think existing functionality has this covered; thus closing
