### ISSUE TITLE
Radarr reports error when adding qBittorrent client with 'superseeding' enabled

### ISSUE THREAD

**Issue by rlkennedyreid** [Radarr/Radarr#5927]
**Describe the bug**

When adding a qbittorrent client with superseeding enabled, an error is displayed:

_qBittorrent is configured to remove torrents when they reach their Share Ratio Limit_

Adding the client works perfectly fine when qBittorrent is set to 'pause' after share ratio is reached.

So Radarr seems to incorrectly interpret the superseeding qbittorrent setting as the remove settings.

**Platform Information (please complete the following information):**
 - Radarr Version: 3.0.2.4552-ls93 by linuxserver.io
 - Docker: Yes 
 - Mono or .NET Version (System -> Status): .Net Core 3.1.10  

**Trace Logs**
[radarr.trace.txt](https://github.com/Radarr/Radarr/files/5969387/radarr.trace.txt)

[AB#708](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/708)

**Comment by ta264** [comment]
This may be so,but you still shouldn't be using that setting. It's for the initial uploader, not something you want to be enabling after you've met seeding goals

**Comment by rlkennedyreid** [comment]
This is true, I don't use the setting. just thought it a worthwhile bug to mention, as it does stop you saving a new client.
