### ISSUE TITLE
Add tags to NFO files

### ISSUE THREAD

**Issue by theg00s3** [Radarr/Radarr#5929]
**Is your feature request related to a problem? Please describe.**
Unlike Sonarr, Radarr doesn't write the tags to the NFO files

**Describe the solution you'd like**
Radarr writes the tags to the NFO files, in a way similar to Sonarr, so that media servers (like Jellyfin) can read them

**Comment by Qstick** [comment]
This is already done in nightly

**Comment by theg00s3** [comment]
oh nice! do you know when it’ll show up in stable?
