### ISSUE TITLE
FR: Notification Timer

### ISSUE THREAD

**Issue by breezytm** [Radarr/Radarr#593]
Hey guys, 

I am new to Radarr and I am also trying to check out Plex Cloud. I added Plex Cloud server to Radarr and it seems to accept it. What I would like to know is, if you guys would be kind and allow users to set a timer for X minutes before signaling the connection to start scanning the directory. My reasoning behind this is I would like to let's say give the uploader about 15 minutes to upload the content to the cloud folder before telling Plex or Emby to scan it.

**Comment by onedr0p** [comment]
Please add this to feathub if it's not there, thanks!
