### ISSUE TITLE
Add ability to rename file/folder with "Indexer name"

### ISSUE THREAD

**Issue by JhonnyMnemonic320** [Radarr/Radarr#5930]
**Is your feature request related to a problem? Please describe.**
I need a way to track from wich indexer the relases are downloaded.
I know that I can find this information clicking on the "i" of the snatched relase on the history tab of each movies page, but is very unpractical when mass editing a lot of movies.

**Describe the solution you'd like**
add the ability in "Media managment" to add the indexer name to the file (or folder) when renamed.
Using somenthing like this: {Movie Title} ({Release Year}) {indexer name}
In this way I can filter the movies by Indexer name with a simple custom filter in the Movies page.

Thanks

**Comment by bakerboy448** [comment]
Not sure if this will happen or not, but I can state with certainty it won’t be added to the folder.

movie folders are related to the movie and not the release (file)

**Comment by Qstick** [comment]
No plans to do this right now

**Comment by JhonnyMnemonic320** [comment]
Ok thanks for the answer. 

**Describe alternatives you've considered**
as alternative is possible to make a custom filter in the Movies page that filter by "Indexer name"?

**Comment by ta264** [comment]
We have no plans to add filters that depend on the movie file (as opposed to metadata on the movie itself. So no, afraid not.
