### ISSUE TITLE
Uppercase the first letter for each words of the movie's title for all languages

### ISSUE THREAD

**Issue by Al4ndil** [Radarr/Radarr#5931]
Hi,

The {Movie Title} renaming parameter allows you to have the first letter of each word of the English title in uppercase.

When we want to retrieve the French title, we use the {Movie Title: FR} parameter. This recovers the French title of the film well.

If we want to manage the case from this {Movie Title: FR} parameter, it seems impossible except going to TMDB to modify the title (which is not always possible).

Is it possible to be able to manage the case of the different words in the title of a film in languages other than English?

Thx a lot

[AB#710](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/710)

**Comment by Alandil35** [comment]
is this request possible and taken into account?

**Comment by bakerboy448** [comment]
If it hasn't been closed that typically indicates it is something that is possible and will be evaluated when there is time to do so.

The main development team is split across 3 apps: Radarr, Readarr, and Lidarr.
There are only 3 or 4 active developers who work on this, and of those 3 or 4 exactly zero work on this fulltime. Exactly zero of any members involved (developers / support) get paid to do this. Everyone of us has fulltime real jobs. Everyone of us has kids and family. Everyone of us works on more than just this project.

Needless to say; there's only so many hours that exist for development work.

**Comment by Alandil35** [comment]
I wasn't criticizing the team :) i know they don't get paid and they try their best!

**Comment by SugarDroid** [comment]
> If we want to manage the case from this {Movie Title: FR} parameter, it seems impossible except going to TMDB to modify the title (which is not always possible).

By doing that you simply break [TMDb's rules](https://www.themoviedb.org/bible/movie) which says: 

> Capitalization
> 
> The guidelines for title capitalization are language dependent. The rules for English and French, for example, are completely different. Please familiarize yourself with the rules of the language(s) you are editing.
> 
> One exception is officially stylized titles. The first letter of the film mother! and the television series black-ish and grown-ish is not capitalized. Another example is Japanese titles in all caps such as the film GHOST IN THE SHELL and the series DEATH NOTE. In all cases, the stylized capitalization is used in the opening credits, on the official website and in press material such as press releases.

Maybe you're one of the reasons those titles get locked. I guess Radarr also not doing it for the same reason because it reads what's written on TMDb. IMHO doesn't matter that you like that way better. I would be very upset if someone would start to edit the titles for my language because that also restrictive about capitalization and I for sure don't want to see Movies' Titles That Way.

**Comment by theotocopulitos** [comment]
To add to this, capitalizing for all languages would be incorrect. For example, in Spanish, only proper names and initial letter a should be capitalized in file titles: “La gran aventura de Tarzán” would be the correct Spanish title (while “La Gran Aventura de Tarzán” is grammatically wrong).
