### ISSUE TITLE
Removed from TMDb Filter

### ISSUE THREAD

**Issue by Novem30** [Radarr/Radarr#5944]
**Is your feature request related to a problem? Please describe.**
When movies get removed from TMDB a message is posted to the health section in setting->status. User has to look up each movie and remove from radarr. This happens more frequently when using features like following cast or crew members import lists.

![image](https://user-images.githubusercontent.com/77077353/108100342-b253ee80-707d-11eb-9dcd-f0a5e3870870.png)

**Describe the solution you'd like**
Add a filter that would show all the effected movies and have that be a link from the health area that would take you to that view.

**Describe alternatives you've considered**
Look up each movie and delete them.

**Additional context**
The discord support team are very nice people.

**Comment by bakerboy448** [comment]
This exists

Custom Filter -> Status = Deleted
