### ISSUE TITLE
Radarr doesn't see resumed downloads in qbittorrent which were errored previously

### ISSUE THREAD

**Issue by Siddhant-k** [Radarr/Radarr#5947]
Once qBittorrent reports an error for a download, radarr doesn't update if qBittorrent starts downloading same the file again after the error is resolved.

1. Torrent sent through Radarr to qBittorrent for download.
2. qBittorrent starts downloading the file, well and good
3. qBittorrent then reports "Errored" and the torrent is moved in Radarr from Queue to History with the error "qBittorrent is reporting an error"
4. Manually resolve the error in qBittorrent (which in my case was that my HDD ran out of space, so I made space) and hit resume, qbittorrent starts downloading the file again.
5. Radarr doesn't update and ignores that download.
6. qbittorrent reaches 100%, also completes seeding but Radarr never looks at the file again.

**Expected behavior**
I would expect Radarr to have the file in the queue after qbittorrent starts downloading the file again, since it does have the category (ie. "movies" for me) that is also configured in qbittorrent.

Sonarr (v2.0.0.5344) (not related, but an example) reported that qbittorrent was reporting an error, but added it back to the queue after qbittorrent was downloading the file again.

**Platform Information (please complete the following information):**
 - OS: Ubuntu 20.04.1
 - Docker: Yes
 - Mono or .NET Version (System -> Status): .NET (3.1.10)
 - Radarr Version: 3.0.1.4259
 - Radarr Branch: master

**Trace Logs**
[radarr.trace.txt](https://github.com/Radarr/Radarr/files/5998127/radarr.trace.txt)

**Comment by bakerboy448** [comment]
logs don't show a response from the client with anything in its queue which is what is critical to seeing what's up

**Comment by Siddhant-k** [comment]
That's odd. Is there something we can even do then? How did Sonarr see it then, just curious?

**Comment by bakerboy448** [comment]
[get the logs of the client response](https://wiki.servarr.com/Radarr_Troubleshooting#Downloads_and_Importing)

**Comment by bakerboy448** [comment]
Closing pending info from OP
