### ISSUE TITLE
Wiki button for external links

### ISSUE THREAD

**Issue by AlexR00T** [Radarr/Radarr#5948]
**Is your feature request related to a problem? Please describe.**
on external links i miss a button for Wikipedia if available

**Describe the solution you'd like**
i want that if there is a wiki page for a certain movie that it shows up a button in the external links. when you click on it it opens directly that movies wiki page

**Describe alternatives you've considered**
an alternative of a more simple solution. Well an always present Wiki button and when one clicks it just searches for that movies title and year. Its less elegant as then user always has to pick a result.

**Additional context**
Its useful in many cases but especially for non english countries. Me personally i use it for editing all titles in Italian. I open english wiki page then switch to italian and see how its titles/ translated for italian market, then i go to tmdb and add that as an alternative title. In case ill have time or if anyone is up for helping i may try to program like a daemon or something for adding alternative titles to tmdb automatically. However wiki button it would still be useful for those who like to look up there.

**Comment by bakerboy448** [comment]
I think the problem with implementing something like this is unlike the current links there is no consistent link to a wikipedia page that is universal across movies such as tmdb/imdb, etc.

**Comment by Qstick** [comment]
Indeed @bakerboy448 is correct
