### ISSUE TITLE
Refresh & Scan causing 100% disk utilization

### ISSUE THREAD

**Issue by Mr-Cake** [Radarr/Radarr#5949]
**Describe the bug**
Refreshing a moving either manually or the daily task is causing massive io. This is a recent issue, first now system slow down without realizing it was radarr maybe 2-3 weeks ago. I tried asking on discord about this, and google has been no help. I'm at the limits of my linux knowledge to trace what radarr is actually do with all those io ops.

**To Reproduce**
Select a movie, hit refresh & scan, via netdata watch nvme drive hit 100% while task is running.

**Expected behavior**
Movie to refresh without ridiculous io

**Screenshots**
Netdata 3x Refresh
![firefox_2021-02-20_03-09-25](https://user-images.githubusercontent.com/8469644/108515392-e2bfb500-7329-11eb-9dfc-779b4385173e.png)

ionotifywatch
![firefox_2021-02-20_03-03-55](https://user-images.githubusercontent.com/8469644/108515488-fec35680-7329-11eb-94f3-b76806e5dc4b.png)

 - OS: Unraid 6.9.0rc1
 - Docker: Yes
 - Mono or .NET Version (System -> Status):  .NET Core  Yes (3.1.10)
 - Browser and Version (Only needed for UI issues): Firefox 32bit
 - Radarr Version: 3.0.2.4552
 - Radarr Branch:  linuxserver.io 

I have a second radarr client that exhibits the same behavior, the second was forked from the first it uses binhex build though. Same media, different download clients. (can't assign download clients based on tracker)

**Trace Logs**
https://pastebin.com/tJDQnSCr
https://pastebin.com/1HmF6q1q

**Comment by Mr-Cake** [comment]
SSD dying was the issue

**Comment by bakerboy448** [comment]
That's the second dying SSD that radarr symptoms pointed towards!

hopefully you got it before it died!
