### ISSUE TITLE
Text Being Cut Off on Discover Tab

### ISSUE THREAD

**Issue by corylowry12** [Radarr/Radarr#5950]
**Describe the bug**

When you go to discover tab the hook on the "g" is cut off.

**To Reproduce**

1. Go to Discover.
2. Scroll down till you find a movie with a lower case g and the bottom part of the hook will be cut off. 

**Expected behavior**

Expected to show the whole letter and not cut any of them off. 

**Screenshots**

https://imgur.com/gallery/jpj6j6q

**Platform Information (please complete the following information):**
 - OS: Windows 10 Pro 2004
 - Docker: No
 - Mono or .NET Version (System -> Status): .Net 5.0.3
 - Browser and Version (Only needed for UI issues): Brave 1.20.103
 - Radarr Version: 3.1.0.4634
 - Radarr Branch: nightly

**Trace Logs**
Turn on Trace logs under Settings -> General and wait for the bug to occur again. 
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**
https://pastebin.com/W71T1Aub

[AB#1005](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1005)

**Comment by corylowry12** [comment]
This is still an issue

**Comment by RobinDadswell** [comment]
@corylowry12  what zoom level is your browser at for Radarr? I can only reproduce this when my zoom is not at 100%

**Comment by corylowry12** [comment]
100%. But it only happens for me when a title contains a lowercase g.

**Comment by Qstick** [comment]
Can't reproduce this either on latest at 100%
