### ISSUE TITLE
Root Folder Unable to Access Network Storage

### ISSUE THREAD

**Issue by paeore** [Radarr/Radarr#5954]
**Describe the bug**
I am unable to change the Radarr root folder to that of a network attached drive

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Media Management'
3. Scroll down to 'Root Folder'
4. Click on 'Add Root Folder'
5. Navigate to '/mnt/Location/of/Mounted/NetworkDrive' - (So the path can obviously be seen by Radarr...)
6. Click 'OK'
7. Nothing happens

**Expected behavior**
Expect to see new network mounted storage to be seen as new Root Folder

 - Raspberry Pi Model: Raspberry Pi 4 Model B Rev 1.1
 - OS: Raspbian 10 (Buster)
 - Docker: No
 - Mono or .NET Version (System -> Status): Mono JIT compiler version 6.12.0.107
 - Browser and Version (Only needed for UI issues): Firefox 85.0.2 (64 bit)
 - Radarr Version: 3.0.2.4552
 - Radarr Branch: master

**Trace Logs**
radarr.trace.txt
[radarr.trace.txt](https://github.com/Radarr/Radarr/files/6017660/radarr.trace.txt)

**Comment by bakerboy448** [comment]
Since you decided to paste the entire log file rather than just context around the issue:

```2021-2-21 11:53:23.3|Trace|DiskProviderBase|Directory '/mnt/12TbBackup/Video/Films/' isn't writable. Access to the path '/mnt/12TbBackup/Video/Films/radarr_write_test.txt' is denied.
2021-2-21 11:53:23.3|Trace|RadarrErrorPipeline|Handling Exception
2021-2-21 11:53:23.3|Warn|RadarrErrorPipeline|Invalid request Validation failed: 
 -- Path: Folder is not writable by user radarr```

What’s critical to network issues is the storage type.....

if you’re using NFS v3 try v4
Etc etc try the music mount type game.

Support Requests -> [Reddit](https://www.reddit.com/r/radarr/) or [Discord](https://discord.gg/r5wJPt9)

**Comment by paeore** [comment]
Cool. Thanks for the reply

So how do I make the Folder writeable by user radarr? Need a step by step play for this please.

Cheers
