### ISSUE TITLE
Issues with radarr/UI/index.js

### ISSUE THREAD

**Issue by muddro1** [Radarr/Radarr#5958]
The index.js is a unformatted, one line, file that is very long. It caused issues loading behind reverse proxy giving an error, essentially because it could not load the whole JS file.

**To Reproduce**

1. Setup Radarr behind reverse proxy
2. go to the intended site
3. site doesnt fully load
4. inspect and review console message
5. says something along the lines of 
`Uncaught SyntaxError: missing } after property list index.js:1:198267`
`note: { opened at line 1, column 198253index.js:1:198253`

**Expected behavior**

For reverse proxy site to open up fine. Did so in the past and with other instance of radarr running.
**Screenshots**

**Platform Information (please complete the following information):**
 - OS: FreeNAS 11.3
 - Docker: No
 - Mono or .NET Version (System -> Status): 5.20.1.34
 - Browser and Version (Only needed for UI issues): Firefox 85.0.2 but also occured in Edge
 - Radarr Version:     3.0.2.4552
 - Radarr Branch: master

**Trace Logs**
Turn on Trace logs under Settings -> General and wait for the bug to occur again. 
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**

I was able to resolve this issue by taking the contents of the file and applying a "cleaner" https://html-cleaner.com/js/. then using the formatted file in the original index.js's place. Recommend ensuring the file is properly formatted instead of one extremely long string.

**Comment by bakerboy448** [comment]
Support Requests -> [Reddit](https://www.reddit.com/r/radarr/) or [Discord](https://discord.gg/r5wJPt9)

The file is certainly valid; so likely a BSD specific issue or Reverse Proxy config issue. Hop on discord into #bsd-support
