### ISSUE TITLE
The colour of the progress bar does not match the key at the bottom of the page

### ISSUE THREAD

**Issue by outdooracorn** [Radarr/Radarr#5963]
**Describe the bug**

On the Movies page, the colour of the progress bar does not match the key at the bottom of the page.

**To Reproduce**

1. Go to the Movies page
2. View an unmonitored missing movie and note that the colour of its progress bar is red
3. Scroll down to the bottom of the page and note that the key informs the user that an unmonitored and missing movie should have an orange progress bar
4. Understand the error: red != orange

**Expected behavior**

The colour of the progress bar matches the key. In this case, the unmonitored missing movie would have an orange progress bar as per the key at the bottom of the page.

**Screenshots**

![image](https://user-images.githubusercontent.com/43674967/109033269-5eb95480-76be-11eb-9a3b-92da1514fbcb.png) ![image](https://user-images.githubusercontent.com/43674967/109033317-6f69ca80-76be-11eb-9f07-a97169d37c55.png)

**Platform Information:**
 - OS:  Ubuntu 20.04 
 - Docker:  Yes
 - Mono or .NET Version (System -> Status): .NET Core 3.1.10
 - Browser and Version (Only needed for UI issues):  Mozilla Firefox for Manjaro Linux 85.0.2 (64-bit)
 - Radarr Version:  3.0.2.4552
 - Radarr Package Version: 3.0.2.4552-ls95 by linuxserver.io 

**Trace Logs**
I don't believe logs will be of any help in this situation. If I am wrong, let me know and I shall provide them.

**Comment by bakerboy448** [comment]
Fixed in nightly;  I'll edit back with the commit once I find it.
![image](https://user-images.githubusercontent.com/55419169/109044449-07a08900-7698-11eb-9183-c43f0b700763.png)
