### ISSUE TITLE
Multipart Movies: download handler deleting previous part

### ISSUE THREAD

**Issue by Felixrising** [Radarr/Radarr#5967]
I'm downloading a two part movie. One file has "part1" in it, the second file "part2"
Radarr decides the second file supercedes the first and deletes part1 immediately on completing part2.

**To Reproduce**
1) Download a movie with two or more file parts, e.g. 
a, movie.name.year.720p.part1.bluray.x264.mkv 
b, movie.name.year.720p.part2.bluray.x264.mkv, 
c, etc.
2) Monitor folder, part1 appears after part1 completes downloading.
3) Part2 completes downloading and is moved into the movie folder
4) Part1 is moved to the recycling bin (I configured this in an attempt to stop radarr from insta-trashing my downloads).
5) place palm on face.

**Expected behavior**
Files should be added to movie folder without auto-trashing them. A method to turn off this behaviour is required in settings.

**Platform Information (please complete the following information):**
 - OS: Debian 10, Radarr in docker container
 - Docker: Yes
 - Mono or .NET Version (System -> Status): Yes (3.1.10)
 - Browser and Version (Only needed for UI issues): Version 88.0.4324.190 (Official Build) (64-bit)
 - Radarr Version: 3.0.2.4552 (3.0.2.4552-ls95 by linuxserver.io)

**Trace Logs**
[radarr.trace.txt](https://github.com/Radarr/Radarr/files/6043160/radarr.trace.txt)

**Comment by Qstick** [comment]
Can you provide the exact filenames? There's logic to handle this so we need to know the exceptions to determine why they are getting through.

**Comment by Felixrising** [comment]
Anne.of.Green.Gables.1985.720p.part1.BluRay.x264-x0r.mkv
Anne.of.Green.Gables.1985.720p.part2.BluRay.x264-x0r.mkv

**Comment by bakerboy448** [comment]
![image](https://user-images.githubusercontent.com/55419169/109169609-97504100-7745-11eb-88ee-d1a59a8afbef.png)
https://github.com/Radarr/Radarr/blob/60ac9d3ad75902384ba3cc1721d064216c281867/src/NzbDrone.Core/MediaFiles/MovieImport/Specifications/NotMultiPartSpecification.cs#L26

yeah those should be rejected and punted for manual review

**Comment by Felixrising** [comment]
So can we just disable deletion of files? There should be a button for enabling/disabling it. I really don't want radarr just deleting files without my approval.

**Comment by bakerboy448** [comment]
Closing;

The [movie entry on TMDB is really a duplicate](https://www.themoviedb.org/movie/17663-anne-of-green-gables?language=en-US).  [TMDB](https://www.themoviedb.org/tv/5874-anne-of-green-gables?language=en-US) and [TVDB ](https://thetvdb.com/series/anne-of-green-gables-1985)have it as a series. 

You are downloading TWO releases. To Radarr each release is a movie file. Radarr has no way of knowing that the two distinctly different releases you are downloading are two parts to the same movie.

No immediate plans to disable deletion of files; that would mean radarr would need to maintain two separate releases for a single movie.  The details of that are TBD.

With that said, the team may reopen to add a stop gap to prevent this, but I wouldn't see that as likely.

**Comment by Felixrising** [comment]
I guess TV mini-series are a grey area. 

I still consider it a bug if I download a new release of a movie, I believe the average user would not expect Radarr to delete the first release without explicitly enabling it under Settings | Media Management | Importing OR File Management. 
What is the current behaviour for Directors Cuts, Fan Edits, etc? Are those being detected by regex and excluded from deletion?

**Comment by bakerboy448** [comment]
Radarr only maintains one release. If the user downloads or radarr automatically grabs (likely via CFs) a director cut. The existing file will be replaced.

**Comment by bakerboy448** [comment]
The behavior is 100% expected and users understand radarr only supports one version of a movie.  Supporting 1 movie with many files/editions (i.e. 1080p and 4k etc.) is a long standing requested feature that requires serious rewriting to do ( 1->1 to 1->M) which is not at all simple.

  Happy to discuss more on [discord](radarr.video/discord).

Maybe you'll be better off with couchpotato...if it works still.
