### ISSUE TITLE
Pick the interval to run tasks. 

### ISSUE THREAD

**Issue by Arturoe1** [Radarr/Radarr#5972]
The tasks running as frequently as every minute will bog down any consumer grade NAS as some tasks are CPU intensive. 
Even with "Analyze media files" disabled Refresh Movies running every minute is very taxing as  in new Celeron J4125 consuming up to 100% in 2 CPU threads. 
This is happening with a library of only 2.5K movies in a EXT4 RAID with NMVE cache. 

**Describe the solution you'd like**

The option to pick the interval in the tasks screen. To avoid any miss use from the users establish reasonable a low and high limits. Some radio buttons with 3 different options would be amazing. 

Example: Refresh movie maybe doesn't need to be run every minute, but every 5-10 minutes should be fine as to give time the system to cache the queries and have some meaningful update. 

Even if Download status from the downloader does not get updated every minute, a delay of 5-10 minutes should be fine. 

**Describe alternatives you've considered**
Updating the DB is a no go as it gets rewritten with default values constantly. 

**Additional context**
Right now the design of radarr is to be operated in a modern computer ignoring the fact NAS are being used more and more. The CPUs of those machines although improving over time are still limited performance wise. 
The current setup is unsustainable as libraries grow and a system with Sonarr and Radarr  will be eating at least  a constant 50% of the CPU resources leaving less room for other apps like jackett, media server or download clients.

**Comment by ta264** [comment]
So many duplicates of this I'm going to let you find them.

No plans for this. Sounds like you have something misconfigured.

**Comment by Arturoe1** [comment]
There are many duplicates because they keep being closed but the problem is there with no solution. 

There is no much to missconfigure, only checkbox is "Analyze media files" and that is turned off. Refresh movies is a hog on resources and forcing it to run every minute with no other choice is an extremely bad design.

**Comment by ta264** [comment]
We have users with 120k libraries where refresh takes minutes. Something is wrong on your system. Please join the discord channel if you want to try to fix it (or convince us there is a big that needs looking at). Adjusting the timings is a band-aid at best.

**Comment by Arturoe1** [comment]
You misunderstood the issue, it is not the time it takes to read the library and the impact of those in a NAS system. 
The issue is the frequency of the runs + the amount of resources it takes. 

If the Refresh Movies runs every minute and takes 50% of your total CPU resources for 60 seconds and then Sonarr does exactly the same you will have the CPU at continuously 50% with just those 2 processes leaving less resources in a NAS to deal with the downloader, the indexer and the player.

In a NAS, Do we really  need to Refresh Movies every minute? 

Why is that difficult to include in this project 3 radio buttons which updates one value in the db?

**Comment by bakerboy448** [comment]
The refresh movie task does not run every minute. I have no idea where you are seeing that. Sounds like you don’t understand the problem you’re seeing :)
![52199720-DCAE-4887-943A-60D58531EB8A](https://user-images.githubusercontent.com/55419169/109307336-160cb300-7806-11eb-951b-df1f0e19ddae.jpeg)

Also please see:
https://wiki.servarr.com/Radarr_FAQ#can_I_disable_the_refresh_movies_task

As Ta said, to discuss further please come to discord.

**Comment by Arturoe1** [comment]
I meant **Refresh Monitored Downloads**.  1 minute 30seconds at 50% of CPU usage. 

![image](https://user-images.githubusercontent.com/58043011/109308294-17f46780-7842-11eb-82a5-d937385bb39d.png)

![image](https://user-images.githubusercontent.com/58043011/109308504-66096b00-7842-11eb-990b-4015cff18fc0.png)
