### ISSUE TITLE
Include more variables in the "Grab" event type

### ISSUE THREAD

**Issue by Lucane** [Radarr/Radarr#5981]
I'd like to use some of the variables from "Grab" events to run my scripts off of, but as it stands now, not a lot of information is made available during that event type. What I'm particularly interested in are the path variables (SourcePath and SourceFolder). I'd like to know what the movie download path is upon grabbing the release. The only other time I could get this information is during the "Import" event type, but there are cases where by that point the information is outdated.

![image](https://user-images.githubusercontent.com/7999446/109439086-95cc9480-7a35-11eb-9963-94f3d18c9575.png)

[AB#638](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/638)

**Comment by Qstick** [comment]
At the time of grab event we don't know where the files are going to end up at the end after the client has downloaded and processed them, etc... What exactly is it you are trying to achieve with this, maybe we can help you get there some other way?

**Comment by Lucane** [comment]
So, basically I make my download folder visible to Plex, so when I download a torrent, I can keep it seeding while making the content available to Plex. I'm aware this approach is not recommended, but I use that download folder exclusively for Plex content and it's setup to only match TV shows (I use private trackers, so ratios are important). I figured I could add a .plexignore file to every newly added Radarr release with a script so they don't clutter my homse screen with nonsense while they finish downloading. I could copy the files and later delete the leftover ones or hardlink everything, but I feel like it creates unneeded complexity.

I solved it now by dedicating a separate directory for the Radarr category in qBittorrent and using automatic torrent management to move the files when it detects a category change. Every time a new Radarr release is added, qBittorrent moves it to a directory dedicated to Radarr that's not monitored by Plex, hence solving my issue. I actually separated all of my downloads now, so Plex only sees the releases I want to include in my library while I'm seeding them.

Since I couldn't know the source path during the "Grab" event, I couldn't tell my script where to place the .plexignore file. My current solution is more elegant anyways, but I still feel like it could be beneficial if that information was available upon grabbing a torrent. Either the grab event could be postponed until the path is known or create a separate event that handles download starts.

**Comment by bakerboy448** [comment]
@Lucane 

> Either the grab event could be postponed until the path is known
Unlikely that goes against the purpose of a grab event (i.e. grabbed; sent to client)

I'll skip commenting on your setup as I'm sure you're already know that is the completely wrong way of doing it;  tho have you looked into sonarr and the magic of hardlinks?   or at the very least you can get a script to hardlink your download folder shows to a tv library folder.

> create a separate event that handles download starts.
Defer to Q, but I'm not sure on the usecase.

**Comment by Lucane** [comment]
@bakerboy448

My half-witted usecase is just one example and I can't really think of any others off the top of my head, but knowing the source path on download start seems useful to me (also the quality and scene name). Maybe it's just me though.

P.S. I'll look into hardlinking my download folder to my library. I've not bothered so far because things seem to be working fine. Is there a particular reason why this method is preferred? I know it can sometimes mess with matching and indexing, but I haven't seen any major hiccups.
