### ISSUE TITLE
Can't add any root folder

### ISSUE THREAD

**Issue by jibbajabber** [Radarr/Radarr#5985]
**Describe the bug**
Can't add any root folder under Setting | Media Management | Add root folder

**To Reproduce**
1. Go to settings
2. Click on media management
3. Scroll down to add root folder
4. No error returned in UI or trace level log and no root folder added

**Expected behavior**
Root folder or error raised either in UI or trace level log

**Screenshots**
Not necessary as nothing raised as an error

**Platform Information (please complete the following information):**
 - OS: Centos 7
 - Docker: yes
 - Mono or .NET Version (System -> Status): Not sure mono not present in path for linuxserver/radarr:amd64-latest
 - Browser and Version (Only needed for UI issues): chrome 88.0.4324.192
 - Radarr Version: 3.0.2.4552
 - Radarr Branch: Not sure package version reported as 3.0.2.4552-ls96 by linuxserver.io

**Trace Logs**
Trace output when trying to add root folder => https://pastebin.com/0dWJNcLE

Full trace output => https://pastebin.com/rjg15GyP

**Comment by bakerboy448** [comment]
Support Requests -> [Reddit](https://www.reddit.com/r/radarr/) or [Discord](https://radarr.video/discord)

My crystal ball says reverse proxy issues;

**Comment by jibbajabber** [comment]
Thanks will try without RP and see if working ok and report back

**Comment by jibbajabber** [comment]
Still can't add root folder when hitting direct without RP => https://pastebin.com/kJDDRegY

**Comment by jibbajabber** [comment]
Interesting way of dealing with potential bugs, closing before waiting for feedback

**Comment by bakerboy448** [comment]
**Support Requests -> [Reddit](https://www.reddit.com/r/radarr/) or [Discord](https://radarr.video/discord)**

**Comment by jibbajabber** [comment]
https://www.reddit.com/r/radarr/comments/lwctfl/cant_add_any_root_folder/

Surely if there is no error log there is a problem here?

**Comment by jibbajabber** [comment]
You could elaborate on thumbs down please, are you saying the trace log does show an error?

**Comment by bakerboy448** [comment]
I'm saying quit replying and exploding everyone's inbox.

Support requests are not for github, as stated twice and as indicated when opening an issue (_emphasis added_)
"**Support Requests will be closed immediately, _if you are not 100% certain this is a bug please go to our Reddit or Discord first. Exceptions do not mean you found a bug!_**"
