### ISSUE TITLE
Import Existing Movies On Disc only worked once

### ISSUE THREAD

**Issue by hawkeyefla** [Radarr/Radarr#599]
So I've gotten Radarr up and running, and I'm slowly bringing my collection into it.  I wanted to move files in a bit at a time, bringing in only things that have resolution and source already in the filename.  I put about 10 movies into my /movies folder and did the Import Existing and it found them just fine.  Looks great.  So I added about 10 more and now Import Existing doesn't do anything.  My path /plex-media/movies shows as a Recent Folder, and just like in Sonarr I click on it, and it does nothing.  I try removing it and adding it again, and still nothing.

**Comment by simonk83** [comment]
I think something recent might be causing this to act strange.  I also found that clicking on my movies directory did nothing, until I did a refresh of the page and then it started working fine.  This happened 4 or 5 times tonight.  In between checks I was generally searching for releases for movies I'd added.

**Comment by hawkeyefla** [comment]
And today it appears to be working correct.  Fresh browser session is really the only difference I can think of.

**Comment by hawkeyefla** [comment]
I can confirm that it appears to be browser session based.  Google Chrome 56.0.2924.87 (64-bit).  If I do an Import Existing, I cannot run it again until I have closed the browser completely and reloaded.  
Does not appear to occur in Firefox.

**Comment by notapantso** [comment]
It does happen in Firefox and a page refresh will indeed make it go away.
My movie folder is on a mounted NAS path, served via *gasp* SMB.

Radarr 0.2.0.288
Firefox 51.0.1 64b

**Comment by zebulon501** [comment]
Same for me using Chrome and Radarr 0.2.0.288 on a Synology NAS.
Closing the tab and opening a new one works.

**Comment by hawkeyefla** [comment]
For what it's worth, Ctrl-F5 or Command-R will usually work, since that forces a refresh. 
Which leads me to believe it's cookie related.

**Comment by OUBeaver** [comment]
Just chiming in to say I experienced as well with Chrome on MacOS.  Definitely cookie related.  Should be an easy fix, right?  ;-)

**Comment by onedr0p** [comment]
In any way, you can use the bulk import to add existing movies now instead.
