### ISSUE TITLE
Import from CP

### ISSUE THREAD

**Issue by woble** [Radarr/Radarr#6]
Any plans to impl importing from CP?

**Comment by galli-leo** [comment]
The idea is to support adding movies from disk. I will have to look about importing not yet downloaded movies from couchpotato.

**Comment by onedr0p** [comment]
I'm not sure if we should invest dev time into this, Sonarr doesn't have a import from SickRage/beard function.

I would like to see importing from other various online sources instead like imdb, letterboxd, http://movies.stevenlu.com,

**Comment by woble** [comment]
Correct me if I am wrong, but doesn't SickBeard/Rage create an empty folder for each series, something that Sonarr can easily pick up; you would only have to specify quality again. With movies it's obviously different and you would have to do it manually. And I imagine it could be somewhat tedious for those who have a lot of movies in wanted.

I honestly wouldn't know how much work it would require to implement this, but if it's too much, leave it until the app is more mature and there's time to do it. As I think it would make the transition from CP a lot smoother.

**Comment by onedr0p** [comment]
Consolidating to issue #114
