### ISSUE TITLE
Add "date when added to radarr"

### ISSUE THREAD

**Issue by grubbe123** [Radarr/Radarr#600]
Hi

Would be nice if i could sort my movies by "date added". That way i can easily check when my lists added a movie. For me it would be nice to have more control over that :)

Thanks, great software, been waiting for a sonarr for movies :)

**Comment by onedr0p** [comment]
Duplicate issue

**Comment by barrystaes** [comment]
So.. whats the duplicate # ?

**Comment by galli-leo** [comment]
@barrystaes I don't actually know, but we already have that in Radarr and you can even sort by that.

**Comment by Shadesss** [comment]
Old but I ended up here from google so I'll comment.
You need to have it in "table" -view to be able to sort by date. I had the overview list -view which doesn't display it.

@galli-leo if sorting by "Date added" could be included on the dropdown menu of the "Sort" -button that'd be cool.

**Comment by galli-leo** [comment]
@Shadesss That will come with the new UI
