### ISSUE TITLE
radarr -- add from watch list (suggestions) manually

### ISSUE THREAD

**Issue by thezoggy** [Radarr/Radarr#602]
While the watch list is great if you want it all, but I'd like to see something more along the lines of this:

![add](https://camo.githubusercontent.com/5043121e1c8f3b8a17a15e60156ac040531639c5/687474703a2f2f692e696d6775722e636f6d2f79727a32707a6c2e676966)
> image from: https://github.com/tidusjar/Ombi

when you can load the list then pick off the ones you want..  also seeing movies with context really helps (in theaters/coming soon/trending)

**Comment by jOOc** [comment]
You can still use it like that if you turn of automatic sync.
Im with you regarding the context so I did a suggestion: http://feathub.com/Radarr/Radarr/+39
