### ISSUE TITLE
Feature request: TMDb Company list option

### ISSUE THREAD

**Issue by icopp** [Radarr/Radarr#6023]
**Is your feature request related to a problem? Please describe.**
For those people who really enjoy movies made by particular production companies, a company list option would be very useful as a counterpart to using the TMDb Person option to always get movies with particular directors or crew.

**Describe the solution you'd like**
In Settings -> List, an additional TMDb option of "TMDb Company" that works like TMDb Person, but with a CompanyID corresponding to the IDs of company pages on TMDb (such as "3" for [the Pixar company page](https://www.themoviedb.org/company/3/movie)). This would probably have no options.

**Describe alternatives you've considered**
User-maintained TMDb lists can serve a similar purposes, but their decentralized nature makes them less useful, as the vast majority of lists are unmaintained after being originally created.

**Comment by Qstick** [comment]
Last time I checked on this TMDb didn't have a endpoint to retrieve movies by company, thus why it's not been done.

**Comment by RobinDadswell** [comment]
Looks like we should be able to get this on the backlog of possible things to look at as TMDb does appear to be able to search via a company now [https://developers.themoviedb.org/3/search/search-companies](https://developers.themoviedb.org/3/search/search-companies)

**Comment by Qstick** [comment]
Doesn't appear that returns a list of movies for a given company.
