### ISSUE TITLE
Custom Formats include extension when download history is lost

### ISSUE THREAD

**Issue by rg9400** [Radarr/Radarr#6025]
**Describe the bug**

**To Reproduce**
1. Create a custom format with `.mkv` as the only condition, based on Release Title.
2. Verify an already imported file with download history does not match against this condition, despite `.mkv` being in the full filepath.
3. Purposefully delete download history for a movie (move the file out, rescan in Radarr, move the file back, scan it in again).
4. Note that the created Custom Format is now matching the file.

**Expected behavior**
Even if download history is lost, the logic for Custom Formats should be consistent. Extension should be stripped out prior to running the CF regex.

**Comment by rg9400** [comment]
This does not seem to be specific only to when history is lost. I cannot figure out why it happens, but it seems the behavior is inconsistent. The extension should be stripped out prior to CF calculation in all the situations. I guess if it makes sense to include extension, I could find a workaround, but only if it is consistent because it is very hard to try and handle both scenarios.

**Comment by ta264** [comment]
As discussed on discord, the extension is never stripped when matching against files (where both filenames and release titles are checked).  For history events, we don't have filenames and only the release title is checked.

I think nothing to do, it's working as expected.
