### ISSUE TITLE
Cannot restart on macOS

### ISSUE THREAD

**Issue by CarterVE** [Radarr/Radarr#6030]
**Describe the bug**

When I try to restart Radarr on macOS 10.13.6 it will fail, and launch textedit with a Radarr.dll file, with text at the top that says "... This program cannot be run in DOS mode. ...". When I launch Radarr from the GUI, however, it works perfectly fine, and launches without issue. I've tried deleting the logs files, and the .db files, and reinstalling from backup. Neither of these things fixed the problem. I'm also running Sonarr and Lidarr, and neither of these have the same issues.

**To Reproduce**

Radarr should have restarted

**Screenshots**

<img width="649" alt="Screen Shot 2021-03-09 at 11 39 26 AM" src="https://user-images.githubusercontent.com/18474523/110522049-b8ae1700-80cd-11eb-8c99-fe573f4315ab.png">

**Platform Information (please complete the following information):**
 - OS:  MacOS 10.13.6
 - Docker:  No
 - Mono or .NET Version (System -> Status):  6.12.0.107
 - Browser and Version (Only needed for UI issues): 
 - Radarr Version:  3.0.2.4552
 - Radarr Branch:  master

**Trace Logs**
Turn on Trace logs under Settings -> General and wait for the bug to occur again. 
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**
[radarr.trace.txt](https://github.com/Radarr/Radarr/files/6110802/radarr.trace.txt)

**Comment by ta264** [comment]
Fixed in 3.1
