### ISSUE TITLE
Back to last scrolled position

### ISSUE THREAD

**Issue by ghost** [Radarr/Radarr#6033]
**Is your feature request related to a problem? Please describe.**
Clicking the back button returns to the top of the previous page instead of the last scrolled position.

**Describe the solution you'd like**
I think it should just go back to the last scrolled position just like most websites do. 

**Additional context**
It's a pain when navigating through a large library and have to constantly scroll down or have to open movies in new tabs so as to avoid having to re-scroll.

**Comment by ta264** [comment]
This needs pulling from lidarr https://github.com/lidarr/Lidarr/commit/1bc52d0138c7bcb94ffce31ec05f675387612a62
