### ISSUE TITLE
Filter downloaded files before downloading

### ISSUE THREAD

**Issue by zductiv** [Radarr/Radarr#604]
#### Feature request
Often movie torrents are bundled with extras, extra subtitles etc. Rather than download the whole torrent, filter out the files that are not requested.

Example:
Utorrent [getfiles](http://help.utorrent.com/customer/en/portal/articles/1573949-files-list---webapi)
Utorrent [setpriority](http://help.utorrent.com/customer/en/portal/articles/1573952-actions---webapi)

**Comment by galli-leo** [comment]
Well those files are usually small. I don't think that's an option we will support. But you can open a feature request on Feathub.

**Comment by galli-leo** [comment]
Regarding this, it would probably better to do this in your download client. The dl client can react faster than we and also should have those options built in (IIRC at least Sabnzb and nzbget have)

**Comment by zductiv** [comment]
Yeh, because I have a significant queue I can generally filter these out before they start, though I haven't found a way to automate it with utorrent. Might have to see what else is available from different clients.
