### ISSUE TITLE
Group Release Name `D-Z0N3` Not Being Parsed Correctly

### ISSUE THREAD

**Issue by angrycuban13** [Radarr/Radarr#6044]
**Describe the bug**

Discussed in [Discord](https://discord.com/channels/264387956343570434/264388019585286144/819383299544973373)

**Screenshots**

Release name example `POTC.Dead.Mans.Chest.2006.1080p.BluRay.DTS.x264.D-Z0N3`

**Platform Information (please complete the following information):**
 - OS: Ubuntu 20.04
 - Docker: Yes
 - Mono or .NET Version (System -> Status): N/A
 - Browser and Version (Only needed for UI issues): N/A
 - Radarr Version: `3.1.0.4724`
 - Radarr Branch: `nightly`

**Trace Logs**

Logs are for losers.
 
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**

**Comment by bakerboy448** [comment]
Very much stuck with fighting the regex to get this to work

**Comment by angrycuban13** [comment]
> Very much stuck with fighting the regex to get this to work

Have you tried getting good?
