### ISSUE TITLE
Option to add movie name under items in list

### ISSUE THREAD

**Issue by YouveGotMeowxy** [Radarr/Radarr#6055]
Could we have an option to enable showing the movie title under each item, where it shows "monitored" and it's quality? Some move posters make it hard to know which movie it is when scanning through the list real fast with your eye, and that would help.

![image](https://user-images.githubusercontent.com/39491297/111090197-f14e5600-84fc-11eb-912c-4a83d9b9a271.png)

**Comment by bakerboy448** [comment]
Closing; Exists

![image](https://user-images.githubusercontent.com/55419169/111090360-6c177100-84fd-11eb-847f-9d57d927a8d7.png)

![image](https://user-images.githubusercontent.com/55419169/111090320-599d3780-84fd-11eb-939e-cfa2a03c5d98.png)

**Comment by YouveGotMeowxy** [comment]
@bakerboy448 ahh, ty. I was looking through the actual settings for it and didn't see it. :)
