### ISSUE TITLE
[Enhancement] Allow movie to be rechecked 

### ISSUE THREAD

**Issue by mishmishb** [Radarr/Radarr#6058]
Sometimes when I torrent a movie, I will find that there are some graphical glitches throughout playback, and will often find that I can fix this by requesting the torrent client "force recheck" the movie, whereby it will scan the file and detect that some parts are missing and download them.

I think it would be great if there were the option to do this with Radarr as I currently have a couple movies where this is an issue, but would rather not delete and redownload them in their entirety just to find out if this is the reason for their glitching.

I understand this may be considered a minor addition that perhaps takes an unnecessary amount of work but I thought I would just raise it to see if perhaps there are others who would find this useful :)

**Comment by bakerboy448** [comment]
Likely no / this will be closed.

If the torrent client is misreporting a file as complete then that’s sounds like a bug in the torrent client.

how would Radarr know a torrent is not complete when the torrent client says the file is complete?

Otherwise, maybe something odd with your setup.

**Comment by mishmishb** [comment]
Understandable if it does get closed. 

I don't mean anything automatic, more like a button you would click if you notice glitches, that would in effect re-add the torrent to the client and force it to recheck

**Comment by bakerboy448** [comment]
No plans to add that functionality I don't think.

Also quite an edge case as well.

If it is happening frequently, I'd suggest trying to figure out why your client isn't working as expected then,  and reach out to their support.
