### ISSUE TITLE
Wrong File Size

### ISSUE THREAD

**Issue by ppffffpp** [Radarr/Radarr#6059]
Some of my movies show the wrong file size ie. the file size shown in Radarr does not match the actual file size on disk.

If I click on "Refresh & Scan" the file size does not get updated.

If I manually import the movie it will show up as another line in files at the correct file size but when I refresh the page it disappears again and shows the old file size.

The only way I have found to resolve it is to rename the file on disk and click "Refresh & Scan".

**Screenshots**
![image](https://user-images.githubusercontent.com/76928342/111165641-a7ee1d00-8575-11eb-8803-81f8e8a8a997.png)
![image](https://user-images.githubusercontent.com/76928342/111165689-b805fc80-8575-11eb-816b-8611d48827b1.png)
![image](https://user-images.githubusercontent.com/76928342/111166409-7295ff00-8576-11eb-9171-e18aaa3f5850.png)

**Platform Information (please complete the following information):**
 - OS: OpenMediaVault 5.5.10-1 (Linux 5.7 kernel)
 - Docker: Yes
 - Radarr Version: 3.0.2.4552-ls12 by linuxserver.io
 - Radarr Branch: develop

[radarr.trace.txt](https://github.com/Radarr/Radarr/files/6141940/radarr.trace.txt)

**Comment by bakerboy448** [comment]
Not a bug; expected behavior.

https://github.com/Radarr/Radarr/issues/4956

**Comment by ppffffpp** [comment]
There appears to be an underlying bug then before this stage as these files are not being modified after import (like in #4956) and are being imported for the first time with the incorrect file size. I will upload a new bug report once it happens while having trace logs enabled.

**Comment by bakerboy448** [comment]
See this for providing better log files rather than the entire trace log filled with lots of noise :)

https://wiki.servarr.com/Radarr_Troubleshooting#Logging_and_Log_Files

don't capture in the middle of a download client refresh with lots of items in your category (unless relevant to the issue) and ditto for an RSS refresh
