### ISSUE TITLE
Support for DSM 7 download station

### ISSUE THREAD

**Issue by konfiot** [Radarr/Radarr#6061]
**Describe the bug**
Adding a synology DSM 7 Download station client results in the following error : Failed to login. Reason: The requested method does not exist

The error is the same as the one reported for Sonarr here : https://github.com/Sonarr/Sonarr/issues/3943

**To Reproduce**
Add a DSM 7 download station as a download client

**Expected behavior**
The client works is added

**Platform Information (please complete the following information):**
 - OS: Ubuntu 20.04
 - Docker: Yes
 - Mono or .NET Version (System -> Status): Mono 
 - Browser and Version (Only needed for UI issues): 
 - Radarr Version: 
 - Radarr Branch:

**Comment by Qstick** [comment]
Already fixed in nightly

https://github.com/Radarr/Radarr/commit/b0753ab153a79203de10a928e99fcec5b6a7c895
