### ISSUE TITLE
Lots of failed downloads with Download Station

### ISSUE THREAD

**Issue by bxlouis** [Radarr/Radarr#6073]
**Describe the bug**

Since v3, most of the movies downloaded with Synology Download Station fail, although they were properly downloaded. 
For the same movie, I end up having 4, to 6 failed downloads and the 7th is correctly downloaded.

**To Reproduce**
1. Go to Radarr
2. Download a movie
3. Wait for it to complete
4. Observe

**Expected behavior**

Downloads are marked as successful as of the first time. 

**Screenshots**

<img width="1389" alt="Screenshot 2021-03-19 at 08 12 59" src="https://user-images.githubusercontent.com/4128333/111744537-b09f6580-888b-11eb-8392-ed887dcd6e36.png">

**Platform Information (please complete the following information):**
 - OS: DSM v6.2.3-25426 Update 3
 - Docker: Yes - v18.09.8
 - Radarr Version: 3.0.2.4552
 - Radarr Branch: linuxserver/latest

**Trace Logs**
[radarrlog.txt](https://github.com/Radarr/Radarr/files/6169291/radarrlog.txt)

**Comment by bakerboy448** [comment]
Known issue due to a change on Synology's side

pleased use the search functionality or see the pinned issue 
https://github.com/Radarr/Radarr/issues/6062

additionally for future bug reports please provide TRACE logs as requested
