### ISSUE TITLE
Catagory options for Torznab indexers

### ISSUE THREAD

**Issue by warhansen** [Radarr/Radarr#6074]
**Is your feature request related to a problem? Please describe.**
When I try to add some of the indexers I have in Jackett then Radarr comes back with the error: Query successful, but no results were returned from your indexer.

I came across this sometimes in Sonarr as well, but there I can enter catagories, and some of the torrent feeds need a "all" category to pass back a response.

**Describe the solution you'd like**
I there could be an option for "catagories" in which you could enter a different code for that torrent indexer it would help.

**Additional context**
As suggested above in Sonarr this is an option where you can add a catagory when adding a torznab entry, eg: 5000,5070,8000, where 8000 is the code for a status check.

Thanks
![Screenshot from 2021-03-19 11-48-46](https://user-images.githubusercontent.com/28757226/111761907-164e1a80-88a9-11eb-8208-951d3ce8c712.png)

**Comment by ta264** [comment]
Pretty sure it's there and you need to enable advanced options

**Comment by ta264** [comment]
Double checked and it is there

**Comment by warhansen** [comment]
Oi, I feel so sheepish! Sorry about that!
