### ISSUE TITLE
omg - info line

### ISSUE THREAD

**Issue by thezoggy** [Radarr/Radarr#608]
looks like bad parsing, info line shown in radarr history looks like:
`https://omgwtfnzbs.me/details?id=2z0ok" target="_blank`

Radarr Ver. 0.2.0.285

**Comment by thezoggy** [comment]
tried another, same thing:
`https://omgwtfnzbs.me/details?id=tUy7g" target="_blank`

**Comment by thezoggy** [comment]
hey its been a year! :)

**Comment by galli-leo** [comment]
Good time to fix it then :P. Sorry, there are lots of bugs still open.
