### ISSUE TITLE
Radarr not upgrading when custom format conditions are met

### ISSUE THREAD

**Issue by alculete** [Radarr/Radarr#6083]
**Describe the bug**

**To Reproduce**

**profile**
![Quality profile](https://user-images.githubusercontent.com/2129497/111873033-0d3b7700-8997-11eb-9544-3e423c0da145.png)

**Custom Format**
![custom format](https://user-images.githubusercontent.com/2129497/111873036-0f053a80-8997-11eb-9300-f618641822f9.png)

**Platform Information (please complete the following information):**
OS: Ubuntu 20.04.2 LTS x86_64 
Kernel: 5.4.0-67-generic 
Shell: bash 5.0.17 

 - Docker: Yes
 - Radarr Branch: nightly

**Comment by bakerboy448** [comment]
Please fully fill out the template that you butchered including version, logs, and what the existing file is, what you think it should have upgrade to

**Comment by alculete** [comment]
> Please fully fill out the template that you butchered including version, logs, and what the existing file is, what you think it should Firstly it is supposed to download a file in any language and then upgrade to Portuguese language

**Comment by bakerboy448** [comment]
Please use one of the support channels: [Reddit](https://www.reddit.com/r/radarr/) or  [Discord](https://radarr.video/discord) for support/questions.
