### ISSUE TITLE
Keep monitoring for files that are closer to the preferred size

### ISSUE THREAD

**Issue by UnknownUser6** [Radarr/Radarr#6084]
I very much like the new feature of the "preferred size" slider. But I would like it to keep monitoring for files that are closer to the actual preferred size. Let's say it downloaded a Bluray-1080p movie that is 9 gb big, while my preferred size would be 5 gb. As soon as there is a release with the same quality, but closer to the preferred size it should replace it with that.

**Comment by Qstick** [comment]
No plans to changing this logic, but you should be able to use CF to achieve this. Just be careful as it’s an easy way to cause download loops upgrading due to size
