### ISSUE TITLE
Navigation Pane

### ISSUE THREAD

**Issue by ajzc20** [Radarr/Radarr#6085]
**Is your feature request related to a problem? Please describe.**

I am using a 4:3 monitor as a computer monitor. Every time I'm doing a search, there's no room for me to see the Formats, Custom formats, Flags, and Download icon. I have to scroll down and scroll to the right for it to show unless I am using a wide screen monitor. It's a pane to navigate to and choose which indexer you want to download it from.
**Describe the solution you'd like**

What if when you click on a movie that window will pop up just like on Sonarr or make the navigation pane hide when you click a button just like in Outlook to make more room when you need to?
**Describe alternatives you've considered**

**Additional context**

Sonar Pop up:
![Pop up](https://user-images.githubusercontent.com/63054491/111910701-73c0a380-8a30-11eb-95b0-8b0b6d39e477.PNG)

Outlook Navigation Pane showing:
![Outlook1](https://user-images.githubusercontent.com/63054491/111910728-90f57200-8a30-11eb-98b2-2dc9b3003949.PNG)

Outlook Navigation Pane hides:
![Outlook2](https://user-images.githubusercontent.com/63054491/111910753-aa96b980-8a30-11eb-8124-d3d067ec3ac8.PNG)

Thank you for all you do!

**Comment by Qstick** [comment]
Dupe on the table being difficult, no plans on making this a modal
