### ISSUE TITLE
API: /rootfolder missing

### ISSUE THREAD

**Issue by woiza** [Radarr/Radarr#6087]
`/rootfolder` is missing in the current API docs / swagger file. Why?
I am pretty sure it was there a few weeks ago...
The following curl command succeeds:

`curl -X GET "http://HOST:7878/api/v3/rootfolder" -H "accept: application/json" -H "X-Api-Key: APIKEY"`

**Comment by bakerboy448** [comment]
https://github.com/Radarr/Radarr/blob/develop/src/Radarr.Api.V3/swagger.json

should still be there?

**Comment by woiza** [comment]
I don't see `/rootfolder` in `"paths":`. Only `/movie`, `/tag` ,  `/diskspace` etc.

**Comment by bakerboy448** [comment]
my guess is it needs to be added then, API docs as you know are a perpetual WIP

nothing for that file since https://github.com/Radarr/Radarr/commit/065846464dce18b1b019566f376a8f0aa72524d4

**Comment by woiza** [comment]
That is strange. I use swagger codegen. A few weeks ago it generated a Radarr client including code for `/rootfolder`. I generated the client code again today and the code for `/rootfolder` was deleted (git status).
Who can add it to the swagger file?

**Comment by bakerboy448** [comment]
PRs welcome ;) (again :D)

I would, but I don't have an understanding of swagger docs.

Anyone with Repo merge abilities (not I) can update the docs

**Comment by woiza** [comment]
I will create a PR for `/rootfolder` tomorrow.
Is there a reason why the swagger file is written by hand instead of generated from the code?

**Comment by woiza** [comment]
https://github.com/Radarr/Radarr/pull/6106
