### ISSUE TITLE
Synology : Radarr doesn't launch after update

### ISSUE THREAD

**Issue by Diplo95** [Radarr/Radarr#6090]
I'm facing a problem I don't understand, so I don't know how to resolve it. I hope to find some help here.

I use Radarr on a synology, a DS213J. It's too old to use Docker. 
I have DSM 6.2.3-25426 Update 3.

Everything was ok until Radarr updated to the version 20210311-15 a few days ago. From now, Radarr is considered as installed by my synology, but it's impossible to launch it. I can't reach the GUI either.

When I try to launch it, I receive an error message in french meaning some failure when repairing the package.

My problem appeared updating radarr to v20210311-15
I have Mono v 5.20.1.34-16 (dont't know when happened last update)
I also have Sonarr 20200921-18 working like a charm

I know this problem happened to some others but I haven't found a solution which could be applied to my case. 

Thx for the help.

(I tried to log to the Discord chanel but it seems the invitation link has expired)

**Comment by ta264** [comment]
Does this discord link work? https://radarr.video/discord

Without logs not a lot we can do.  Have you tried reinstalling the package?

**Comment by Diplo95** [comment]
I tried to uninstall and re-install : same problem.
I also tried to come back to previous version : it doesn't work any more. 

I'll try to find the logs

**Comment by Diplo95** [comment]
Hi, I finally find the way to get the logs files. I've got 2 files in Volume1/@appstore/radarr/var :
radarr_install.log :
[https://pastebin.com/RXL70V1C](url)

Radarr/log :
[https://pastebin.com/ELi2zNhA](url)

**Comment by ta264** [comment]
Try this one https://discord.gg/HXz7feyM

Support is much more effective via discord we find

**Comment by Diplo95** [comment]
Thanks : this one works. I try on Discord
