### ISSUE TITLE
Trakt List suddenly won't import from Radarr

### ISSUE THREAD

**Issue by cruzerkk** [Radarr/Radarr#6094]
It was working fine. I changed nothing and then today noticed that a movie I added yesterday did not sync with Radarr. 
Test - fails
I have attached log for your reference. 
[radarr.txt](https://github.com/Radarr/Radarr/files/6201236/radarr.txt)

**Comment by bakerboy448** [comment]
Closing;

1) [ GHI opened via 3rd party app or template just ignored  or intentionally butchered]((https://github.com/Radarr/Radarr/issues/new?assignees=&labels=Type%3A+Bug&template=bug_report.md&title=)) (please note that 3rd party apps ignore templates and frustrate users and dev teams alike)
2) v0.2.0.1480  is out of date even for v0.2
3) v0.2 is end of life and no longer supported. For further support upgrade to v3.  [Please see the website and/or wiki for installation instructions.](https://wiki.servarr.com/Radarr_Installation)
4) your logs indicate a ton of network, permissions, inaccessible clients, and general setup issues.

Please use one of the support channels: [Reddit](https://www.reddit.com/r/radarr/) or  [Discord](https://radarr.video/discord) for support/questions.
