### ISSUE TITLE
Radarr V3: Add "Filename" Filter

### ISSUE THREAD

**Issue by zalaare** [Radarr/Radarr#6096]
Radarr Version: 3.0.2.4552

Custom filters are great!  However I went to create a filter to find all my movies that are of quality Remux that I am still monitoring.  Specifically so I could stop monitoring them and transcode them down to more "manageable" size.  When attempting this I discovered that Path was an option, but Filename wasn't.  I don't store the quality of the video in the Path.

If there is a way to auto-tag movies with the quality profile upon import success (and consequently to remove tags that no longer apply if replaced), then I could use the Tags filter.  This seems like the long way around though.

Currently I've "cheesed" this with a close approximation using "Size on Disk", however there are many false positives this way.

![radarr_v3_filter](https://user-images.githubusercontent.com/8794362/112534042-02128d80-8d81-11eb-9acf-a602e24f2c8f.png)

**Comment by ta264** [comment]
Many duplicates of this closed for same reasons. Search if you're curious.
