### ISSUE TITLE
Transmission downloaded files moved immediately after download (no seeding possible)

### ISSUE THREAD

**Issue by efelon** [Radarr/Radarr#6097]
## Description

After adding the movie, the download folder gets created and used by transmission:
/mnt/Qdownload/transmission/completed/radarr/Supermovie.2020.720p.BluRay.H264.AAC-RARBG

This part "radarr/Supermovie.2020.720p.BluRay.H264.AAC-RARBG" gets deleted and content moved to the "End Result" root folder (see below) as soon as download is detected as finished by radarr. Additionally the rename operation produces a second movie file. I don't know what comes first the renaming or the moving.

> End Result:
/mnt/Qdownload/download_web/Supermovie (2020)# ll -h
-rwxrwxr-x 1 dluser debian-transmission 1.3G Mar 25 21:47 'Supermovie (2020) Bluray-720p.mp4'
-rwxrwxr-x 1 dluser debian-transmission 1.3G Mar 25 21:47 'Supermovie_720p.mp4'
-rwxrwxr-x 1 dluser debian-transmission 4.7K Mar 25 22:30 'Supermovie_720p.nfo'
-rwxrwxr-x 1 dluser debian-transmission   30 Mar 25 21:47 'Supermovie_720p.orig.txt'
-rwxrwxr-x 1 dluser debian-transmission  30K Mar 25 21:47 'Supermovie_720p.srt'

_First file is the rename from Radarr_

Here what is working and what not (all using the web interface directly (no proxy,no ssl):

- [x] Fresh install (run as user dluser)
- [x] Adding some indexer and transmission as download client
- [x] Enable renaming
- [x] Setup root folder and import some movies
- [x] Finding/Adding movie
- [x] Automatic search
- [x] Automatically adding download to transmission
- [x] Detect download complete
- [x] Import into radarr database with status Downloaded
- [ ] Continue seeding
- [ ] Delete download from client
- [ ] Delete original movie file or leave it in the download folder

_Side Notes_:
* Seed ratio and -time are not set in the indexers oder download client settings
* Seed ratio default in transmission: 0.1	
* "Use hardlinks" is selected
* Sonarr, installed on the same system, can do hardlinks on the same disk/folder, running with the same user
* Root folder is a cifs mount

### System Info:
* Linux testpi3 4.19.0-14-arm64 #1 SMP Debian 4.19.171-2 (2021-01-30) aarch64 GNU/Linux
* transmission-daemon: Installed: 2.94-2+deb10u2
* Radarr: 3.1.0.4799 — Mar 24 2021 nightly Currently Installed
* mono --version
Mono JIT compiler version 6.12.0.122 (tarball Mon Feb 22 17:35:18 UTC 2021)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       normal
	Notifications: epoll
	Architecture:  arm64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(610)
	Suspend:       preemptive
	GC:            sgen (concurrent by default)

### Debug (No Errors or Warnings found):
```
/opt/downloaders.conf/radarr/logs# cat radarr.debug_moviemove.txt | grep -E '(Download|Movie|Moving)(Service|Event)'
2021-3-25 21:46:39.0|Info|AddMovieService|Adding Movie [Supermovie (2020)][tt6475714, 458576] Path: [/mnt/Qdownload/download_web/Supermovie (2020)]
2021-3-25 21:46:39.1|Info|RefreshMovieService|Updating info for Supermovie
2021-3-25 21:46:40.0|Debug|MovieService|Updating 1 movie
2021-3-25 21:46:40.0|Debug|MovieService|1 movie updated
2021-3-25 21:46:40.1|Debug|RefreshMovieService|Finished movie refresh for Supermovie
2021-3-25 21:47:00.8|Info|DownloadService|Report sent to Transmission. Supermovie 2020 720p BluRay H264 AAC RARBG
2021-3-25 21:48:26.4|Debug|TrackedDownloadService|Tracking 'Transmission:Supermovie.2020.720p.BluRay.H264.AAC-RARBG': ClientState=Downloading (readonly) RadarrStage=Downloading Movie='Supermovie - 2020 Bluray-720p v1' OutputPath=/mnt/Qdownload/transmission/completed/radarr/Supermovie.2020.720p.BluRay.H264.AAC-RARBG.
2021-3-25 22:30:27.0|Debug|TrackedDownloadService|Tracking 'Transmission:Supermovie.2020.720p.BluRay.H264.AAC-RARBG': ClientState=Completed (readonly) RadarrStage=Downloading Movie='Supermovie - 2020 Bluray-720p v1' OutputPath=/mnt/Qdownload/transmission/completed/radarr/Supermovie.2020.720p.BluRay.H264.AAC-RARBG.
2021-3-25 22:30:31.1|Debug|MovieFileMovingService|Hardlinking movie file: /mnt/Qdownload/transmission/completed/radarr/Supermovie.2020.720p.BluRay.H264.AAC-RARBG/Supermovie.2020.720p.BluRay.H264.AAC-RARBG.mp4 to /mnt/Qdownload/download_web/Supermovie (2020)/Supermovie (2020) Bluray-720p.mp4
2021-3-25 22:30:31.7|Info|MovieService|Assigning file [Supermovie (2020) Bluray-720p.mp4] to movie [[Supermovie (2020)][tt6475714, 458576]]
2021-3-25 22:30:31.9|Debug|CompletedDownloadService|All movies were imported for Supermovie.2020.720p.BluRay.H264.AAC-RARBG
2021-3-25 22:30:32.0|Debug|DownloadEventHub|[Supermovie.2020.720p.BluRay.H264.AAC-RARBG] Marking download as imported from Transmission
2021-3-25 22:30:32.0|Debug|DownloadEventHub|Transmission does not support marking items as imported
2021-3-25 22:58:57.7|Debug|TrackedDownloadService|Tracking 'Transmission:Supermovie.2020.720p.BluRay.H264.AAC-RARBG': ClientState=Warning RadarrStage=Imported Movie='Supermovie - 2020 Bluray-720p v1' OutputPath=/mnt/Qdownload/transmission/completed/radarr/Supermovie.2020.720p.BluRay.H264.AAC-RARBG.
```

### Settings

![Bildschirmfoto von 2021-03-25 23-09-51](https://user-images.githubusercontent.com/10722552/112557900-d5389780-8dcd-11eb-951c-5f7a0c3e6c6d.png)
![Bildschirmfoto von 2021-03-25 23-08-30](https://user-images.githubusercontent.com/10722552/112557924-dff32c80-8dcd-11eb-93e9-298c779493d1.png)

**Comment by bakerboy448** [comment]
Please use one of the support channels: [Reddit](https://www.reddit.com/r/radarr/) or  [Discord](https://radarr.video/discord) for support/questions.

-----
The below is additional only because you put in a ton of effort on your GHI, but missed the first part of checking on reddit or discord unless you are 100% sure.

It hardlinked as expected:

`2021-3-25 22:30:31.1|Debug|MovieFileMovingService|Hardlinking movie file: /mnt/Qdownload/transmission/completed/radarr/Supermovie.2020.720p.BluRay.H264.AAC-RARBG/Supermovie.2020.720p.BluRay.H264.AAC-RARBG.mp4 to /mnt/Qdownload/download_web/Supermovie (2020)/Supermovie (2020) Bluray-720p.mp4`

`/mnt/Qdownload/download_web/` is your root folder, odd, but fine.

> Delete download from client
>  Delete original movie file or leave it in the download folder

This will never happen ever by radarr with your current configuration.
https://wiki.servarr.com/Radarr_Settings#Completed_Download_Handling

> Seed ratio default in transmission: 0.1
>ClientState=Completed

This is your problem.  Transmissions is marking the torrent as complete, thus radarr **moves** it as expected.
https://wiki.servarr.com/Radarr_Settings#Torrent_Process

>/mnt/Qdownload/download_web/Supermovie (2020)# ll -h
>-rwxrwxr-x 1 dluser debian-transmission 1.3G Mar 25 21:47 'Supermovie (2020) Bluray-720p.mp4'
>-rwxrwxr-x 1 dluser debian-transmission 1.3G Mar 25 21:47 'Supermovie_720p.mp4'
>-rwxrwxr-x 1 dluser debian-transmission 4.7K Mar 25 22:30 'Supermovie_720p.nfo'
>-rwxrwxr-x 1 dluser debian-transmission 30 Mar 25 21:47 'Supermovie_720p.orig.txt'
>-rwxrwxr-x 1 dluser debian-transmission 30K Mar 25 21:47 'Supermovie_720p.srt'

this is....strange, swing by reddit or discord and get some trace logs.

Also you should upgrade to the .net build.. mono builds will be killed in the very near future.

**Comment by efelon** [comment]
@bakerboy448 Thanks for coming back to me anyway.

I'm enjoying participating in open source projects. For me it is mandatory to provide feedback and bug reports as detailed and carefully evaluated as my time and knowledge allows. That's the least I can do. Most of the projects are on github but more and more starting to outsource their feedback loop to other platforms, which I can understand somehow, but for me it makes the thinks more difficult since I need more and more accounts on all this platforms. In this example, I don't have a Discord or reddit account (yet, lets see).  
Of course I would prefer staying on github, but I'll think about going to reddit because of your polite and forthcoming answer.

I will do another evaluation run with traces active.

But let me clarify some points from above since your questions helped a lot to understand (I'm very new to radarr).

> Also you should upgrade to the .net build.. mono builds will be killed in the very near future.

The mentioning of mono was my fault. I'm already on .netcore
```
Version  3.1.0.4799
.NET  Yes (5.0.4)
DB Migration  192
```

> It hardlinked as expected:

and

> This will never happen ever by radarr with your current configuration.
https://wiki.servarr.com/Radarr_Settings#Completed_Download_Handling

I read all of this before and I think that is the key why I think this is a bug:
1. I have not enabled "Completed Download Handling - Remove" option but still
  * it moves the files (although debug log indicates hardlinking)
  * it doesn't only rename it also copies

> Did transmission move the files? Did you point transmission at these files and it filled the rest?

I don't think so but it is a good point. I try to raise the log level for that as well.  
In the last log line you see that transmission returns the torrent as warning. And in the transmission GUI itself the torrent is marked as failed "data not found" and the download path still points to ` /mnt/Qdownload/transmission/completed/radarr/Supermovie.2020.720p.BluRay.H264.AAC-RARBG`

**Comment by efelon** [comment]
I'm here for my walk of shame. I could have sworn I disabled the damn thing while switching to the much better Radarr.
@bakerboy448 A big sorry for wasting your time. Your question if transmission moved the file finally triggered the thought when I knew I fucked up.
