### ISSUE TITLE
Status/Size Display Bug during Update All

### ISSUE THREAD

**Issue by JesseWV** [Radarr/Radarr#6098]
If I issue the Update All command and then select any title that has a status of "Missing," after a few seconds it's Status erroneously changes from "Missing" to "Downloaded" and it's size starts increasing as the background scanning continues. 

I'm guessing it's somehow pulling data from the scan into the display for the actively shown title. If you go back to the Movie Index and reselect the same title it's back the way it should be for a second or two before the same process is repeated.

Additionally when the scanning is complete the displayed information is restored to it's correct state.

**Describe the bug**
The displayed information for movies with "Missing" status is corrupted by issuing a Update All command.

**To Reproduce**
1. Issue "Update All" command.
2. Select an existing title from the Movie Index that has a status of "Missing."
3. Observe the Status change from "Missing" to "Downloaded" before your very eyes.
4. Observe the Size begin to be incremented, eventually reaching comical sizes.

**Expected behavior**
The displayed information should not change and should remain as Status: Missing and Size: 0 B

**Platform Information (please complete the following information):**
 - OS: Microsoft Windows Server 2019 Standard Version 10.0.17763 Build 17763
 - Docker: No
 - Mono or .NET Version (System -> Status): .NET Core 3.1.10
 - Browser and Version (Only needed for UI issues): Version 89.0.4389.90 (Official Build) (64-bit)
 - Radarr Version: 3.0.2.4552
 - Radarr Branch: develop

**Trace Logs**
N/A - See next post

**Comment by bakerboy448** [comment]
please fill out the whole bug template
https://github.com/Radarr/Radarr/issues/new?assignees=&labels=Type%3A+Bug&template=bug_report.md&title=

**Comment by JesseWV** [comment]
**UPDATE
I can no longer reproduce the bug to produce a trace log. Ever since the Update All scan was complete as mentioned above, it no longer occurs. I suspect the initial bug may be due to several crashes that occurred during failed Library Imports that required the service to be stopped an restarted.
