### ISSUE TITLE
Memory / context switches optimization

### ISSUE THREAD

**Issue by ngosang** [Radarr/Radarr#6099]
**Is your feature request related to a problem? Please describe.**
I have been monitoring Radarr for a week. Also other processes for base line. The processes we not updated or restarted during the week. I'm running these tests in a RaspberryPi 4 with 8GB of RAM. The CPU is idle most of the time and I have 6 GB of RAM free so Radarr is not affected by resource limitations.
* Version 3.0.2.4552
* .NET Core Yes (3.1.10)
* Monitored movies 700
* Downloaded movies  593

1) CPU usage is very low. This is really good.

2) I have found some memory spikes. I can't correlate the spikes with the tasks. I tried to run all the task manually one by one and I can't see any spike. **Do you have more tasks in the background that can't be seen in the UI?** This issue is not critical, but is desirable to have a stable RAM usage (like Sonarr). These spikes can crash the process if there is not enough RAM. The spikes are from ~220 MB => ~340 MB that is a 120MB of RAM increase...

3) The number of **non voluntary** context switches is really high and it increases over time. I think it could be related to how .netcore handles threads in idle state or the garbage collector. I can see the same issue in Sonarr (also .net app). **I don't know if this can be fixed but, do you have information about that?** We are experience similar issues in Jackett and I don't have an explanation. https://github.com/Jackett/Jackett/issues/11407

![image](https://user-images.githubusercontent.com/10577978/112623411-9be34480-8e2c-11eb-8586-ab3f4091e426.png)

Context switches compared to Deluged doing really heavy disk/network work.
![image](https://user-images.githubusercontent.com/10577978/112627325-bd92fa80-8e31-11eb-8fc6-b0b08d8f32b4.png)

In Jackett (another .netcore app) the context switches are voluntary, caused by Jackett calling system calls. In Radarr/Sonarr the context switches are caused by the OS.
![image](https://user-images.githubusercontent.com/10577978/112627824-62add300-8e32-11eb-8eb9-422baf9fc518.png)

**Describe the solution you'd like**
I would like the Radarr memory were more stable (with less spikes) to be able to run Radarr in a SBC with few RAM.
I would like to know the reason because there are too many context switches.

**Comment by ngosang** [comment]
Radarr is perfectly fine. There is a bug in my monitoring app.

Related https://github.com/ncabatoff/process-exporter/issues/193

**Comment by Qstick** [comment]
@ngosang thanks for the follow-up!
