### ISSUE TITLE
Radarr shows Remote Transmission directory as  "Likely missing or incorrect remote path mapping." but Directory is working

### ISSUE THREAD

**Issue by s0m3f00l** [Radarr/Radarr#6100]
Hello folks, 

  I think there is just a  cosmetic bug here. In System it shows the error:

`Remote download client Remote_Transmission-syn places downloads in /volume1/Volume_1/Downloads/transmission-downloads/ but this directory does not appear to exist. Likely missing or incorrect remote path mapping.`

but the directory is working fine and Downloads are working fine.   

The setup I currently have is a Remote Transmission server in a separate container on a NAS with the storage and RADARR running on a separate bare metal server. 

The message appears to be cosmetic as everything is working but I just get a red circle with the error on it that I cannot clear.

----

**Version**
    3.0.2.4552
**.NET Core**
    Yes (3.1.10)
**DB Migration**
    188
**AppData directory**
    /home/MEMEME/.config/Radarr
**Startup directory**
    /opt/Radarr
**Mode**
    Console

And your product is amazing, thanks for all the hard work!

**Comment by bakerboy448** [comment]
Please use one of the support channels: [Reddit](https://www.reddit.com/r/radarr/) or  [Discord](https://radarr.video/discord) for support/questions.

**Comment by s0m3f00l** [comment]
Not sure what you mean no support is needed. I was reporting a bug @bakerboy448

**Comment by s0m3f00l** [comment]
I will however comply, though again **NO SUPPORT IS NEEDED** 

https://www.reddit.com/r/radarr/comments/mdnss3/radarr_shows_remote_transmission_directory_as/

**Comment by bakerboy448** [comment]
Not a bug, Solved with setting a correct remote map.

https://www.reddit.com/r/radarr/comments/mdnss3/radarr_shows_remote_transmission_directory_as/gsamg0b/?utm_source=share&utm_medium=ios_app&utm_name=iossmf&context=3
