### ISSUE TITLE
Backup Status Icon on Completed Scheduled Backups is Confusing

### ISSUE THREAD

**Issue by majorgear** [Radarr/Radarr#6107]
**Is your feature request related to a problem? Please describe.**
When there is a scheduled run on the backup task, every backup created by the scheduled tasks shows the "scheduled" status icon. I find this confusing as completed backups have the "scheduled" icon next to them. This signifies that the backup task has not completed, causing confusion.  This can be seen in the Radarr UI System->Backup screen.

**Describe the solution you'd like**
I propose that completed backups should have a "completed" status icon. Scheduled backups would still be display with the scheduled status icon and the future scheduled date on the backup page.

**Describe alternatives you've considered**
I haven't considered alternatives.

**Additional context**
Radarr Version 3.1.0.4738

<img width="2082" alt="Screen Shot 2021-03-26 at 7 42 51 AM" src="https://user-images.githubusercontent.com/16109553/112732393-53488b80-8eff-11eb-8c8c-8deb6fb48a10.png">

**Comment by Qstick** [comment]
They are all completed backups as its just listing the backup files available. They are identified differently via icons as they are handled differently in the code for various purposes (cleanup, etc), thus there are cases when a user want's to know what type of backup each is.

No plans to change this, but if you have other suggestions to clarify it I'm open to hear and open this back up.
