### ISSUE TITLE
Filters enhancements

### ISSUE THREAD

**Issue by woble** [Radarr/Radarr#611]
Related to this.
![image](https://cloud.githubusercontent.com/assets/494873/22628695/1a04ca46-ebd9-11e6-9e85-018a3bb866b8.png)

1. Add `Downloaded` filter button.
2. Allow selecting multiple filters, i.e. `monitored` and `downloaded`.

**Comment by fedoranimus** [comment]
Allowing multiple filters opens a can of worms that involves specifying queries using boolean operators.

**Comment by woble** [comment]
Why not fetch all from the start and filter on the client side?

**Comment by geogolem** [comment]
I agree the ability to apply more filters would be appreciated... but some thought needs to be put into it..

We would need to have some kind of grouping.. it would almost be like having 3 distinct filtering stages, each with their own controls.


[ ALL ]  ---- [ Missing | Downloaded] ---- [ Monitored | Not Monitored ] ---- [ Released | In Cinemas | Announced ]

**Comment by jOOc** [comment]
Please have a look at how Plex handle filters and sorting.

**Comment by galli-leo** [comment]
@jOOc Reworking the filters probably wont happen until the new UI.

**Comment by WhySoSaurus** [comment]
this can be solved with three drop down menus.
first is for "monitored", "un-monitored" and "all". this would default to all.
second for "downloaded", not "downloaded" and "all". this would default to all.
third would be "Released", "in Cinema" and "Announced" and "all". this would default to all.

this would allow the user to easily filter how they wish.
only limitation of this is that the user wont be able to view. "Release" and "in Cinema" without "Announced". which is not in the current functionality anyway.

any thoughts?

**Comment by galli-leo** [comment]
@WhySoSaurus This does not solve the problem however how we are gonna actually implement the sorting feature.
