### ISSUE TITLE
Excessive History Logging On Failed Import

### ISSUE THREAD

**Issue by Iristyle** [Radarr/Radarr#6126]
**Describe the bug**

Radarr generates a large volume of history entries for a single movie based on a failing import. This issue appears to have been triggered by incorrect permissions being set by Transmission as a download client, but in all my years of running Sonarr / Radarr I've never seen this happen, so figured I would report it:

**To Reproduce**

* Transmission successfully downloads a file
* Radarr attempts to import the file, but fails - but keeps trying, repeatedly
* Radarr generates 7000+ import fail history entries in the sqlite database in a span of 2 weeks
* History data for this one movie obscures all history information across the system in the `/activity/history` view
* Similarly, due to the volume of history, loading the specific movie page at `/movie/621757` takes an excessive time to render

**Expected behavior**

* Radarr supports an exponential backoff policy when trying to import and/or only supports manual retry after failures
* A nice feature request would be a way to multi-select or delete all history entries on a specific movie page - I had to use sqlite to purge the database spam

**Platform Information (please complete the following information):**
 - OS: Synology
 - Docker: Yes
 - Mono or .NET Version (System -> Status): .NET 5.0.4
 - Radarr Version: 3.1.0.4799-ls43 by linuxserver.io
 - Radarr Branch: radarr:nightly container auto-updated by ouroboros

**Trace Logs**

The import failure due to permissions is pretty evident in the logs:

```
2021-3-29 03:12:11.9|Warn|ImportApprovedMovie|Couldn't import movie /volume1/Media/Downloads/Transmission/completed/movies/Dads.2019.1080p.WEBRip.x264-RARBG/Dads.2019.1080p.WEBRip.x264-RARBG.mp4

[v3.1.0.4799] System.UnauthorizedAccessException: Access to the path '/volume1/Media/Downloads/Transmission/completed/movies/Dads.2019.1080p.WEBRip.x264-RARBG/Dads.2019.1080p.WEBRip.x264-RARBG.mp4' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at NzbDrone.Common.Disk.DiskTransferService.TransferFile(String sourcePath, String targetPath, TransferMode mode, Boolean overwrite) in D:\a\1\s\src\NzbDrone.Common\Disk\DiskTransferService.cs:line 296
   at NzbDrone.Core.MediaFiles.MovieFileMovingService.TransferFile(MovieFile movieFile, Movie movie, String destinationFilePath, TransferMode mode) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\MovieFileMovingService.cs:line 134
   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeMovieFile(MovieFile movieFile, LocalMovie localMovie, Boolean copyOnly) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\UpgradeMediaFileService.cs:line 51
   at NzbDrone.Core.MediaFiles.MovieImport.ImportApprovedMovie.Import(List`1 decisions, Boolean newDownload, DownloadClientItem downloadClientItem, ImportMode importMode) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\MovieImport\ImportApprovedMovie.cs:line 123


2021-3-29 03:13:44.8|Info|RecycleBinProvider|Recycling Bin has not been configured, deleting permanently. /volume1/Media/Feature Films/Dads [2019]/Dads [2019].mp4
```

**Database query results**

I figured I'd have to execute commands against the database to purge the bad history rows in the `History` table. I determind the movie id then checked the count of History records.

```
sqlite> SELECT COUNT(*) FROM History WHERE MovieId=1726;
7374
```

I figured out the range of entries to delete and purged by movie with `DELETE FROM History WHERE MovieId=1726 AND ID>15767 AND ID<23139;`, leaving just a few records around for that movie:

```
sqlite> SELECT COUNT(*) FROM History WHERE MovieId=1726 AND ID>15767 AND ID<23139;
0
sqlite> SELECT COUNT(*) FROM History WHERE MovieId=1726;
3
```

Here's a sample of what the 10 newest records looked like prior to purging. You can see the import is reattempted every 90 seconds, filling up logs on disk and the History table in the database:

```
sqlite> SELECT * FROM History ORDER BY "DATE" DESC LIMIT 10;
23139|/volume1/Media/Feature Films/Dads [2019]/Dads [2019].mp4|2021-03-29 15:02:52.5760295Z|{
  "quality": 9,
  "revision": {
    "version": 1,
    "real": 0,
    "isRepack": false
  }
}|{
  "reason": "Upgrade"
}|6||1726|[
  1
]
23138|/volume1/Media/Feature Films/Dads [2019]/Dads [2019].mp4|2021-03-29 15:01:50.4970247Z|{
  "quality": 9,
  "revision": {
    "version": 1,
    "real": 0,
    "isRepack": false
  }
}|{
  "reason": "Upgrade"
}|6||1726|[
  1
]
23137|/volume1/Media/Feature Films/Dads [2019]/Dads [2019].mp4|2021-03-29 15:00:15.406796Z|{
  "quality": 9,
  "revision": {
    "version": 1,
    "real": 0,
    "isRepack": false
  }
}|{
  "reason": "Upgrade"
}|6||1726|[
  1
]
23136|/volume1/Media/Feature Films/Dads [2019]/Dads [2019].mp4|2021-03-29 14:58:44.7148828Z|{
  "quality": 9,
  "revision": {
    "version": 1,
    "real": 0,
    "isRepack": false
  }
}|{
  "reason": "Upgrade"
}|6||1726|[
  1
]
23135|/volume1/Media/Feature Films/Dads [2019]/Dads [2019].mp4|2021-03-29 14:57:13.1646209Z|{
  "quality": 9,
  "revision": {
    "version": 1,
    "real": 0,
    "isRepack": false
  }
}|{
  "reason": "Upgrade"
}|6||1726|[
  1
]
23134|/volume1/Media/Feature Films/Dads [2019]/Dads [2019].mp4|2021-03-29 14:55:41.1001312Z|{
  "quality": 9,
  "revision": {
    "version": 1,
    "real": 0,
    "isRepack": false
  }
}|{
  "reason": "Upgrade"
}|6||1726|[
  1
]
23133|/volume1/Media/Feature Films/Dads [2019]/Dads [2019].mp4|2021-03-29 14:54:11.5905483Z|{
  "quality": 9,
  "revision": {
    "version": 1,
    "real": 0,
    "isRepack": false
  }
}|{
  "reason": "Upgrade"
}|6||1726|[
  1
]
23132|/volume1/Media/Feature Films/Dads [2019]/Dads [2019].mp4|2021-03-29 14:52:40.9028709Z|{
  "quality": 9,
  "revision": {
    "version": 1,
    "real": 0,
    "isRepack": false
  }
}|{
  "reason": "Upgrade"
}|6||1726|[
  1
]
23131|/volume1/Media/Feature Films/Dads [2019]/Dads [2019].mp4|2021-03-29 14:51:11.5245317Z|{
  "quality": 9,
  "revision": {
    "version": 1,
    "real": 0,
    "isRepack": false
  }
}|{
  "reason": "Upgrade"
}|6||1726|[
  1
]
23130|/volume1/Media/Feature Films/Dads [2019]/Dads [2019].mp4|2021-03-29 14:49:43.2506567Z|{
  "quality": 9,
  "revision": {
    "version": 1,
    "real": 0,
    "isRepack": false
  }
}|{
  "reason": "Upgrade"
}|6||1726|[
  1
]
```

[AB#657](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/657)

**Comment by RobinDadswell** [comment]
This is expected behaviour, every time Radarr checks for downloads it will find the offending one as it's returned as completed from the download client and then attempt to process it. The issue is a permissions issue on the file for the user that Radarr is running as and not an issue with Radarr itself.

**Comment by austinwbest** [comment]
As mentioned, this is not a bug. I don't think there is a need to change the UI to manipulate the history personally. It is real history of what happened so that is my thought on it. 

Stop after x tries
Add a failed import notification trigger

I believe those are the best options
