### ISSUE TITLE
[0.2.0.267] Cardigann Torznab Indexer Not Working

### ISSUE THREAD

**Issue by CaptObvious** [Radarr/Radarr#613]
This works fine in Sonarr, but when adding with identical settings on Radarr the test fails with unable to connect.  My only indexer in Cardigann is TPB.  Log says:

Invalid request Validation failed: 
 -- Unable to connect to indexer, check the log for more details

Unable to connect to indexer: Sequence contains no elements
System.InvalidOperationException: Sequence contains no elements
  at System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0006c] in <63992662b765477a898ef49cdcc99ee2>:0 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].TestConnection () [0x0001a] in <4b9eac3c6f3d436993b6ad16b653110e>:0

**Comment by CaptObvious** [comment]
Actually, if TPB could be added as an indexer this would remove my requirement for Cardigann completely.

**Comment by onedr0p** [comment]
Use Jackett.

Cardigann will not work until this is added:
https://github.com/cardigann/cardigann/issues/327
