### ISSUE TITLE
french language regex

### ISSUE THREAD

**Issue by stygmate** [Radarr/Radarr#6136]
https://github.com/Radarr/Radarr/blob/6702c7d21b9eb8118e54be2ed4b2a97ab34c47fd/src/NzbDrone.Core/Parser/LanguageParser.cs#L20

maybe it can be a good idea to add FRE / FRA to french regex it's really common.

**Comment by bakerboy448** [comment]
We would need example release names for this

also please edit and fill out the template....FYI third party apps ignore the templates and bypass the restrictions on blank issues being opened.
https://github.com/Radarr/Radarr/issues/new?assignees=&labels=feature+request&template=feature_request.md&title=

That's the case sensitive regex, so it likely would not go there specifically, but the line or two above that.

**Comment by stygmate** [comment]
ex:
Goodfellas 1990 1080p Eng Fra Ger Hun Ita Rus Spa [mkvonly]
Goodfellas Scorsese 25 Anniversary 1990 Eng Fre Ita Multi Subs 720p [H264 mp4]
Quei-Bravi-Ragazzi-Goodfellas-(1990)-[DVDRip]-H264-Ita-Fra-Ac3-2-0-Eng-5-1
