### ISSUE TITLE
Make Rarbg use smart category options instead of just numbers (Like Filelist)

### ISSUE THREAD

**Issue by Qstick** [Radarr/Radarr#6139]
This
![image](https://user-images.githubusercontent.com/376117/113483238-6bc12480-9470-11eb-8dab-c3f6fb42fc16.png)

Instead of this 
![image](https://user-images.githubusercontent.com/376117/113483231-5f3ccc00-9470-11eb-8bca-a7480e7751ca.png)

**Comment by bakerboy448** [comment]
Shouldn't we do this upstream at sonarr? 🙃
