### ISSUE TITLE
Movie wont show up after sending to Radarr Via Ombi and wont let me add new in Radarr

### ISSUE THREAD

**Issue by Hizzie36** [Radarr/Radarr#6140]
A House on Fire (2021) - Movie will not allow me to add to Radarr as a new Film, Also when adding in Ombi to send to Radarr, It sends it and it is in the Movie library for a brief moment and then disapears.

**Comment by bakerboy448** [comment]
Please use one of the support channels: [Reddit](https://www.reddit.com/r/radarr/) or  [Discord](https://radarr.video/discord) for support/questions.
