### ISSUE TITLE
Login with forms loops until cookies cleared

### ISSUE THREAD

**Issue by oscy** [Radarr/Radarr#6144]
Version
3.0.2.4552

Running as service on windows 10 pro machine.

When I try logging in to Radarr with forms (username and password) nothing happens. It loops right back around to the same login page to enter credentials. It doesn't give any error message in browser or anything like that.

My only way of getting it to log in successfully is to remove the cookies from browser and then reenter my details and it works immediately. I tried finding solution but could only see some Sonarr users reporting the same problem a couple of years ago but this seems fixed.

I do run Sonarr, SABnzbd on the same computer and they have never had any similiar problem.

**Comment by RobinDadswell** [comment]
Can you please follow the template when logging bugs - also this seems like it is a support request so Discord/Reddit will more likely provide you with a more rapid answer. Most importantly please make sure you have trace logs of when you are trying to authenticate and post the link when asking for support.

**Comment by bakerboy448** [comment]
closing; support or dupe

Sounds like a form filler

Please use one of the support channels: [Reddit](https://www.reddit.com/r/radarr/) or  [Discord](https://radarr.video/discord) for support/questions.

or you're using radarr under HTTPS direct which is a problem and no one who cares enough about it has taken the time to look into it

The use case for HTTPS on a LAN is very limited and 999/1000 users never setup correct.
https://github.com/Radarr/Radarr/issues/5444
