### ISSUE TITLE
Custom format size: v3 doesnt save numbers behind the dot .

### ISSUE THREAD

**Issue by michpas** [Radarr/Radarr#6145]
**Describe the bug**
In radarr v2 it was possible to have customformat filters on filesize with values that have a broken numbers (eg 2.5)
When upgrading to v3, the broken values get correctly incorporated; but when i try to edit or create new, the size customformat value only saves full rounded numbers. Eg. Nothing behind the dot

**To Reproduce**
Goto customfilters
Add size as filter
Enter 4.5 or 4,5   
Press save
Reopen screen and value will be 4

**Expected behavior**
To store 4.5 (as it was in v2), or to allow mb value instead of gb 

Added 2 images. Both of radar v3.

- One with imported profile from v2 (with value behind dot) 
- and one newly in v3 created (where its impossible to indicate a broken number)

![Screenshot_20210405-072643_Chrome](https://user-images.githubusercontent.com/66222810/113541225-1442c600-95e2-11eb-9221-47020ef5543f.jpg)
![Screenshot_20210405-072534_Chrome](https://user-images.githubusercontent.com/66222810/113541227-14db5c80-95e2-11eb-96ee-bfa08eb73add.jpg)

 - Docker: 
 Yes,.latest linuxserver docker on synolohy ds218+

**Comment by bakerboy448** [comment]
Please fill out the full bug report template rather than butchering it

**Comment by michpas** [comment]
> Please fill out the full bug report template rather than butchering it

Ok, tried to resubmit with the formal headers.
