### ISSUE TITLE
Prevent WebRip?

### ISSUE THREAD

**Issue by Buster14** [Radarr/Radarr#6149]
So i have this situation, the priority download is : 

Bluray -720p > cutoff
WEBDL-1080p

Problem is now webdl-1080p can't be separated with webrip-1080p
And sometimes there are movies that arent released in bluray and i'd rather keep webdl-1080p instead.
But radarr always replaces the better webdl with worse webrip
Is there anyway to prevent this behavior?

**Comment by bakerboy448** [comment]
Please use one of the support channels: [Reddit](https://www.reddit.com/r/radarr/) or  [Discord](https://radarr.video/discord) for support/questions.

ungroup then
