### ISSUE TITLE
How to add Trending, Popular, Top Anticipated, Top Box Office, Top Watched Movies

### ISSUE THREAD

**Issue by rickytin** [Radarr/Radarr#615]
How to add Trending, Popular, Top Anticipated, Top Box Office, Top Watched Movies to Trakt List

**Comment by onedr0p** [comment]
Huh..? Go to the Lists tab in Settings, click the plus sign, click Trakt, Do what-haves-you.

To import from teh list manually, go to Add movie on the main page, click import form lists, ?? Success

**Comment by madvtak** [comment]
Will the Trakt list only work if you're signed up as a VIP?

**Comment by blackley** [comment]
It works for free and VIP users

**Comment by madvtak** [comment]
I deleted my comment, but yeah it looks like it does. $30 saved :P
