### ISSUE TITLE
Indexer API call returned error 14: Cant find themoviedb in database

### ISSUE THREAD

**Issue by Z3R0C00l1500** [Radarr/Radarr#6151]
**Describe the bug**

When searching for all missing movies, all indexer fail and become unavailable.

**To Reproduce**
1. Go to Movies
2. Click on Filter
3. Click on Wanted
4. Click on Search Filtered
5. Optionally confirm with Search (if many item are wanted)
4. System -> Status shows these errors ->

```
All rss-capable indexers are temporarily unavailable due to recent indexer errors
All search-capable indexers are temporarily unavailable due to recent indexer errors
All indexers are unavailable due to failures
```

**Expected behavior**

**Screenshots**

**Platform Information (please complete the following information):**
 - OS: macOS 11.1 (20C69)
 - Docker: No
 - Mono or .NET Version (System -> Status): Yes (3.1.10)
 - Browser and Version (Only needed for UI issues): Safari 14.0.3 (16610.4.3.1.4)
 - Radarr Version: 3.0.2.4552
 - Radarr Branch: master

**Trace Logs**
Turn on Trace logs under Settings -> General and wait for the bug to occur again. 
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**
[radarr.trace.txt](https://github.com/Radarr/Radarr/files/6265957/radarr.trace.txt)

That’s what I find in the logs, any clue? It says error code 14

> 2021-3-18 22:05:22.4|Warn|Rarbg|https://torrentapi.org/pubapi_v2.php?mode=search&search_themoviedb=649781&ranked=0&category=14%3B48%3B17%3B44%3B45%3B47%3B50%3B51%3B52%3B42%3B46&limit=100&token=(removed)&format=json_extended&app_id=Radarr
> 
> [v3.0.2.4552] NzbDrone.Core.Indexers.Exceptions.IndexerException: Indexer API call returned error 14: Cant find themoviedb in database. Are you sure this themoviedb exists?
>    at NzbDrone.Core.Indexers.Rarbg.RarbgParser.ParseResponse(IndexerResponse indexerResponse) in D:\a\1\s\src\NzbDrone.Core\Indexers\Rarbg\RarbgParser.cs:line 17
>    at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 291
>    at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchReleases(Func`2 pageableRequestChainSelector, Boolean isRecent) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 125
> RequestUri: https://torrentapi.org/pubapi_v2.php?mode=search&search_themoviedb=649781&ranked=0&category=14%3B48%3B17%3B44%3B45%3B47%3B50%3B51%3B52%3B42%3B46&limit=100&token=(removed)&format=json_extended&app_id=Radarr;StatusCode: OK;ContentType: application/json;ContentLength: 98;ContentSample: {"error":"Cant find themoviedb in database. Are you sure this themoviedb exists?","error_code":14}

**Comment by bakerboy448** [comment]
Please use one of the support channels: [Reddit](https://www.reddit.com/r/radarr/) or  [Discord](https://radarr.video/discord) for support/questions.

it would appear the movie you are searching does not exist on TMDB and RarBG's API can't handle that and fails.

my guess is you only have one  indexer, RarBG.

leaving this open pending one of the devs reviewing to see if this is an indexer error that should be handled more gracefully and handled not as a failure.

**Comment by bakerboy448** [comment]
Closing as OP never provided additional information; can reopen if needed
