### ISSUE TITLE
Bug still apparent: "Digital Releases in Calendar #4582"

### ISSUE THREAD

**Issue by cmgfender** [Radarr/Radarr#6155]
**Describe the bug**
Noticed this a little bit ago, radarr in iCal, Google calendar, etc wasn't showing all the movies during the pandemic correctly.
I went through and it seems to be because none of the releases marked "digital" not physical or theatrical are coming over.

Noticed it was a fixed bug, still occurring for me,
**To Reproduce**
Exported calendar to ical, MacBook Pro, Big Sur. 

**Expected behavior**
Digital releases not showing, theatrical and physical are.
**Screenshots**

**Platform Information (please complete the following information):**
MacBook Pro big sur
Version
3.0.2.4552
**Trace Logs**
N/A?

**Comment by bakerboy448** [comment]
Latest is not a version

system -> status

**Comment by cmgfender** [comment]
Sorry!
Version
3.0.2.4552

So. I'm running it through iCal. As in subscribing to the calendar that way. But the digital releases aren't pulling through to other apps I have set up to read those accounts, like fantastical, for instance. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by cmgfender** [comment]
>Latest is not a version ...

@bakerboy448 added!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
