### ISSUE TITLE
"Downloaded Episodes Scan" showing up in system tasks

### ISSUE THREAD

**Issue by blackley** [Radarr/Radarr#616]
"Downloaded Episodes Scan" showing up in system tasks - need to be changed to Movie scan or missing movie scan etc.

When adding new torrent client the default label is still showing "tv-sonarr" also.

**Comment by galli-leo** [comment]
Which torrent client?

**Comment by blackley** [comment]
utorrent

**Comment by onedr0p** [comment]
utorrent's label is now defaulted to radarr
