### ISSUE TITLE
Add paging to the home page

### ISSUE THREAD

**Issue by KaraokeStu** [Radarr/Radarr#617]
I currently have over 800 movies on my system and the home page takes forever to load.

Could we possibly limit to x amount of movies per page (with infinite scroll if required) to reduce the overhead of the homepage?

**Comment by OUBeaver** [comment]
I too would like this feature.

**Comment by danpowell88** [comment]
This would be great, for me with 2000+ movies chrome pretty much is unusable even when set to the table view.

**Comment by geogolem** [comment]
i definitely would like this feature, but i would also like to still have the *optional* ability to load all the movies on a single page, maybe let the user specify how many movies can be on a page. with one of the options be no limit...

**Comment by danpowell88** [comment]
agreed, things quickly break down with a large amount on there, chrome takes 600mb+ of memory and basically is unusable with only  2000ish items in there.

Is there a lot of event wiring happening on the page or something that would be causing this? The page is quite long but I've seen similar length pages load fine elsewhere without too much issues.

**Comment by galli-leo** [comment]
I don't know if we will handle this with the current UI. Paging is a bitch to get done correctly :(

**Comment by KaraokeStu** [comment]
I might be able to help there - I can take a look at the code next week on my break and see what could potentially be done

**Comment by onedr0p** [comment]
We really want to wait for a new UI to solve this problem and others.

**Comment by galli-leo** [comment]
I already started working on it. Shouldn't be too hard.
