### ISSUE TITLE
Import JSON to an existing Custom Format

### ISSUE THREAD

**Issue by Fringe09** [Radarr/Radarr#6178]
**Is your feature request related to a problem? Please describe.**
I use many Custom Formats with Quality Profiles. The Custom Formats have various scoring. There are times a Custom Format needs to be updated. The update is in a JSON format. Today, I need to rename the current Custom Format, create a new one, go to the various Quality Profiles, add the score, and then delete the original Custom Format.

**Describe the solution you'd like**
Add support to import JSON to an existing Custom Format.

**Describe alternatives you've considered**
Can't think of any.

[AB#576](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/576)

**Comment by TRaSH-** [comment]
something like this

![image](https://user-images.githubusercontent.com/6155095/115609737-36c62600-a2e8-11eb-894e-8e400a83b015.png)

**Comment by iammanbeard** [comment]
> 
> 
> something like this
> 
> ![image](https://user-images.githubusercontent.com/6155095/115609737-36c62600-a2e8-11eb-894e-8e400a83b015.png)

Exactly!

**Comment by bakerboy448** [comment]
![image](https://user-images.githubusercontent.com/55419169/147020862-a76abe65-7bf3-47d4-bf01-d524770bab84.png)
