### ISSUE TITLE
Radarr does not allow sending notification on delete

### ISSUE THREAD

**Issue by dolohow** [Radarr/Radarr#6188]
**Describe the bug**
Radarr does not allow sending notification on delete for instance when using telegram.

**To Reproduce**

1. Go to /settings/connect
2. Try to create new notification for instance using Telegram as medium.
3. On delete checkbox is grayed out

**Expected behavior**
Checkbox is selectable like `On grab`.

**Screenshots**
![image](https://user-images.githubusercontent.com/1408564/114934934-dbed8400-9e3a-11eb-9f39-4a61b51336a5.png)

**Platform Information (please complete the following information):**
 - OS:  Ubuntu 20.04
 - Docker:  Yes
 - Mono or .NET Version (System -> Status):  3.1.10
 - Browser and Version (Only needed for UI issues):  Firefox 87
 - Radarr Version:  3.0.2.4552
 - Radarr Branch:  master

**Comment by bakerboy448** [comment]
Closing;
Doesn't appear to be an issue in nightly.
https://github.com/Radarr/Radarr/commit/5926ca5d8a78ed3b907a18b0b5a2bba3703e330e

![image](https://user-images.githubusercontent.com/55419169/114940409-6b793f80-9e07-11eb-8f64-f6c83fcec32a.png)
