### ISSUE TITLE
Do not require each movie to be contained it's own folder.

### ISSUE THREAD

**Issue by GJB85641** [Radarr/Radarr#6191]
I use the Sonaar product for my TV shows and was opening to have the same capabilities with the Radaar product, but alas no..

It is foolish to require a movie series like Star Trek or Ace Ventura to have a separate folder for each movie.  The ability to open a movie series folder and see/play all the movies associated with that series is a much better solution.

It would take me several days to create folders and move each single movie into it's own specific folder let alone the confusion it would also cause within PLEX and Twonky.     

My synology and qnap NAS file structures are built under the Movies/Series/movie 1, 2, 3, etc. within that series.

![image](https://user-images.githubusercontent.com/79336319/115098058-b87e1400-9ee2-11eb-93ae-c48633988578.png)

**Comment by bakerboy448** [comment]
many dupes of this if you search...closing

See also [{Movie Collection}](https://wiki.servarr.com/Radarr_Settings#Movie_Naming_3)

**Comment by GJB85641** [comment]
Thanks, but the issue remains the same.   It does not seem reasonable to create a folder for each movie rather than place all movies of a series in one folder, especially when you want to view them as a group.  

From what I read, you may be working on the "enhancement".  I'll keep checking back.   
Good luck and thanks again.
