### ISSUE TITLE
Movie upgrade issue

### ISSUE THREAD

**Issue by N3EOP** [Radarr/Radarr#6193]
**Describe the bug**

Radarr deletes existing file before replacement file is downloaded.

**Expected behavior**

Radarr would verify a successful download before deleting the existing file.

Notes and observations:

---
Reason
    File was deleted to import an upgrade
---

This behavior was triggered by an existing bug; it tried to download the same file it just deleted (closed bug #1108), and the downloader ignored the duplicate request.

The only reason I noticed this behavior is because I watched part of a movie the other night, then when I went to finish it, the file was missing.

**Platform Information (please complete the following information):**

binhex-radarr docker container under Unraid 6.9; current version.

Version
    3.0.2.4552
Package Version
    3.0.2.4552-1 by radarr 
.NET Core
    Yes (3.1.10)
Docker
    Yes
DB Migration
    188
AppData directory
    /config
Startup directory
    /usr/lib/radarr/bin
Mode
    Console

**Comment by RobinDadswell** [comment]
Can you get trace logs of this happening please?

**Comment by bakerboy448** [comment]
Closing for now; will reopen once the appropriate logs showing the issue on 3.1.1 or newer are provided
