### ISSUE TITLE
[REQ] The option to edit the custom format in json format

### ISSUE THREAD

**Issue by TRaSH-** [Radarr/Radarr#6205]
**Is your feature request related to a problem? Please describe.**

When changes happen on guide that has a big collection of custom formats it's easier for the end user to edit/replace the json then trying to do it the other way.
Yes you could just create a new one but that also means you need to redo the scoring.
**Describe the solution you'd like**

I would like to see a edit option where you got the import and export option
**Describe alternatives you've considered**

A auto sync with the guide button ;)
**Additional context**

Will follow when I get home.

**Comment by Qstick** [comment]
Dupe #6178 ?
