### ISSUE TITLE
Add Connection - Plex Media Server (SQL Logic Error)

### ISSUE THREAD

**Issue by klinkeye** [Radarr/Radarr#6214]
**Describe the bug**

Adding connection to PMS in Radarr (test works) however when saving - fails.

**To Reproduce**
1. Go to Settings > Connect
2. Add connection Plex Media Server
3. Fill in details
4. Click Save (red exclamation mark)
5. See error in log

**Expected behavior**

Expected to save connection and display saved connection.

**Screenshots**

![radarr-error](https://user-images.githubusercontent.com/83050259/115811607-5c137b00-a433-11eb-899a-ebd0849de805.PNG)

**Platform Information (please complete the following information):**
 - OS: Ubuntu 20.04
 - Docker: No
 - Mono or .NET Version (System -> Status): .Net Core 3.1.10
 - Browser and Version (Only needed for UI issues): Chrome Version 90.0.4430.72
 - Radarr Version: 3.0.2.4552
 - Radarr Branch: develop

**Trace Logs**
Turn on Trace logs under Settings -> General and wait for the bug to occur again. 
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**

[radarr.trace.txt](https://github.com/Radarr/Radarr/files/6362437/radarr.trace.txt)

**Comment by bakerboy448** [comment]
`develop`

`3.0.2.4552`

You're out of date update and see if it still occurs.

**Comment by klinkeye** [comment]
Yep my bad, updated to 3.1.0.4893 - resolved.
