### ISSUE TITLE
Handling of completed but invalid downloads

### ISSUE THREAD

**Issue by Bterrell721** [Radarr/Radarr#622]
When Radarr sends a grab to downloader and downloader sends back that the download was successful BUT the actual files end up being bad somehow (bad format, bad RARs, etc.) I notice that the CompletedDownloadHandler will just sit there saying that there are no good files for it to process, but it never tries a new release.  I know I can mark the release as blacklisted manually, but could we possibly add the ability to have it automatically blacklist a release and re-search after a certain time period of an import not being successful even with a completed download event (60 minutes perhaps as default)?

Thank you very much for this fork, excellent work so far!

**Comment by onedr0p** [comment]
There's not much we can do about this if the download was returned as successful. Radarr thinks, "Ok movie was downloaded but I cannot import because I can't find the movie file".

The same goes with sonarr, you'll need to manually blacklist the release. That is why that feature exists.

**Comment by Bterrell721** [comment]
Note that this is actually resolved by using NZBGet instead of SABnzbd, as NZBGet will return a failed status if there are no proper files at the end of a release instead of Successful like SAB does.  Thanks for looking into it!
