### ISSUE TITLE
Version 3.1.0.4893 on Mono v5.10.1.57 crashes shortly after startup

### ISSUE THREAD

**Issue by MrMaik** [Radarr/Radarr#6222]
So my install of radarr keeps crashing within a couple minutes of starting.
It seems to be during the RefreshMovieService, since that's on the last line before the stacktrace.

> [Info] RefreshMovieService: Updating info for The Bank Job 
> Stacktrace:
> 
>   at <unknown> <0xffffffff>
>   at (wrapper managed-to-native) object.__icall_wrapper_mono_gc_alloc_vector (intptr,intptr,intptr) [0x00009] in <0e06830de9a44394a7e366951eabca52>:0
>   at (wrapper alloc) object.AllocVector (intptr,intptr) [0x000bf] in <0e06830de9a44394a7e366951eabca52>:0
>   at System.Collections.Generic.List`1<T_REF>.set_Capacity (int) [0x00021] in /wrkdirs/usr/ports/lang/mono/work/mono-5.10.1.57/mcs/class/referencesource/mscorlib/system/collections/generic/list.cs:123
>   at System.Collections.Generic.List`1<T_REF>.EnsureCapacity (int) [0x00036] in /wrkdirs/usr/ports/lang/mono/work/mono-5.10.1.57/mcs/class/referencesource/mscorlib/system/collections/generic/list.cs:419
>   at System.Collections.Generic.List`1<T_REF>.Add (T_REF) [0x00010] in /wrkdirs/usr/ports/lang/mono/work/mono-5.10.1.57/mcs/class/referencesource/mscorlib/system/collections/generic/list.cs:228
>   at System.Collections.Generic.List`1<T_REF>..ctor (System.Collections.Generic.IEnumerable`1<T_REF>) [0x0006b] in /wrkdirs/usr/ports/lang/mono/work/mono-5.10.1.57/mcs/class/referencesource/mscorlib/system/collections/generic/list.cs:100
>   at System.Linq.Enumerable.ToList<TSource_REF> (System.Collections.Generic.IEnumerable`1<TSource_REF>) [0x0000e] in /wrkdirs/usr/ports/lang/mono/work/mono-5.10.1.57/external/corefx/src/System.Linq/src/System/Linq/ToCollection.cs:30
>   at Dapper.SqlMapper.Query<T_REF> (System.Data.IDbConnection,string,object,System.Data.IDbTransaction,bool,System.Nullable`1<int>,System.Nullable`1<System.Data.CommandType>) [0x0003d] in <5acd85318ab348a09a089b0cd3453a07>:0
>   at NzbDrone.Core.Datastore.SqlMapperExtensions.Query<T_REF> (NzbDrone.Core.Datastore.IDatabase,string,object) [0x0001f] in <7641cd73c5194ec9b1d81e3624415782>:0
>   at NzbDrone.Core.Datastore.SqlMapperExtensions.Query<T_REF> (NzbDrone.Core.Datastore.IDatabase,NzbDrone.Core.Datastore.SqlBuilder) [0x0002f] in <7641cd73c5194ec9b1d81e3624415782>:0
>   at NzbDrone.Core.Datastore.BasicRepository`1<TModel_REF>.Query (NzbDrone.Core.Datastore.SqlBuilder) [0x00007] in <7641cd73c5194ec9b1d81e3624415782>:0
>   at NzbDrone.Core.Datastore.BasicRepository`1<TModel_REF>.All () [0x00007] in <7641cd73c5194ec9b1d81e3624415782>:0
>   at NzbDrone.Core.Movies.AlternativeTitles.AlternativeTitleService/<>c__DisplayClass11_0.<UpdateTitles>b__3 (NzbDrone.Core.Movies.AlternativeTitles.AlternativeTitle) [0x00018] in <7641cd73c5194ec9b1d81e3624415782>:0
>   at System.Linq.Enumerable/WhereListIterator`1<TSource_REF>.ToList () [0x00017] in /wrkdirs/usr/ports/lang/mono/work/mono-5.10.1.57/external/corefx/src/System.Linq/src/System/Linq/Where.cs:391
>   at System.Linq.Enumerable.ToList<TSource_REF> (System.Collections.Generic.IEnumerable`1<TSource_REF>) [0x0000e] in /wrkdirs/usr/ports/lang/mono/work/mono-5.10.1.57/external/corefx/src/System.Linq/src/System/Linq/ToCollection.cs:30
>   at NzbDrone.Core.Movies.AlternativeTitles.AlternativeTitleService.UpdateTitles (System.Collections.Generic.List`1<NzbDrone.Core.Movies.AlternativeTitles.AlternativeTitle>,NzbDrone.Core.Movies.Movie) [0x000b2] in <7641cd73c5194ec9b1d81e3624415782>:0
>   at NzbDrone.Core.Movies.RefreshMovieService.RefreshMovieInfo (int) [0x00287] in <7641cd73c5194ec9b1d81e3624415782>:0
>   at NzbDrone.Core.Movies.RefreshMovieService.Execute (NzbDrone.Core.Movies.Commands.RefreshMovieCommand) [0x001c4] in <7641cd73c5194ec9b1d81e3624415782>:0
>   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommand<TCommand_REF> (TCommand_REF,NzbDrone.Core.Messaging.Commands.CommandModel) [0x0006a] in <7641cd73c5194ec9b1d81e3624415782>:0
>   at (wrapper dynamic-method) object.CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,NzbDrone.Core.Messaging.Commands.CommandExecutor,object,NzbDrone.Core.Messaging.Commands.CommandModel) [0x00074] in <0e06830de9a44394a7e366951eabca52>:0
>   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3<T0_REF, T1_REF, T2_REF> (System.Runtime.CompilerServices.CallSite,T0_REF,T1_REF,T2_REF) [0x00110] in /wrkdirs/usr/ports/lang/mono/work/mono-5.10.1.57/external/corefx/src/System.Linq.Expressions/src/System/Dynamic/UpdateDelegates.Generated.cs:1836
>   at (wrapper dynamic-method) object.CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,NzbDrone.Core.Messaging.Commands.CommandExecutor,object,NzbDrone.Core.Messaging.Commands.CommandModel) [0x00096] in <0e06830de9a44394a7e366951eabca52>:0
>   at NzbDrone.Core.Messaging.Commands.CommandExecutor.ExecuteCommands () [0x0008d] in <7641cd73c5194ec9b1d81e3624415782>:0
>   at System.Threading.ThreadHelper.ThreadStart_Context (object) [0x00014] in /wrkdirs/usr/ports/lang/mono/work/mono-5.10.1.57/mcs/class/referencesource/mscorlib/system/threading/thread.cs:68
>   at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool) [0x00071] in /wrkdirs/usr/ports/lang/mono/work/mono-5.10.1.57/mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs:957
>   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool) [0x00000] in /wrkdirs/usr/ports/lang/mono/work/mono-5.10.1.57/mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs:904
>   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object) [0x0002b] in /wrkdirs/usr/ports/lang/mono/work/mono-5.10.1.57/mcs/class/referencesource/mscorlib/system/threading/executioncontext.cs:893
>   at System.Threading.ThreadHelper.ThreadStart () [0x00008] in /wrkdirs/usr/ports/lang/mono/work/mono-5.10.1.57/mcs/class/referencesource/mscorlib/system/threading/thread.cs:105
>   at (wrapper runtime-invoke) object.runtime_invoke_void__this__ (object,intptr,intptr,intptr) [0x0004f] in <0e06830de9a44394a7e366951eabca52>:0
> 
> =================================================================
> Got a SIGSEGV while executing native code. This usually indicates
> a fatal error in the mono runtime or one of the native libraries 
> used by your application.
> =================================================================
>

**Comment by ta264** [comment]
Not a bug, minimum mono for 3.1 is 5.20.

But really you should be using the net core build. Come by the discord if you need help
