### ISSUE TITLE
Feature Request - If using hardlinks, delete original file as well as hardlink on upgrade

### ISSUE THREAD

**Issue by phife-dawg** [Radarr/Radarr#6223]
I permaseed everything that Radarr grabs, thus I am using hardlinks when importing. However, the current behavior of Radarr means that when I upgrade a file, I only delete the hardlink, not the actual file itself of the older version. I would like the option to delete the older version as well, even if radarr (and the torrent client) see the file as incomplete.

**Comment by bakerboy448** [comment]
Closing; template not followed

But also won't likely happen anytime soon anyway....With torrents and hit n runs this is very complicated. We have no short term plans for doing it at this time.
