### ISSUE TITLE
Importing existing movies not detecting symbols (i.e. periods)

### ISSUE THREAD

**Issue by fstjsb** [Radarr/Radarr#624]
When importing movies (like I.T. (2016) or R.I.P.D. (2013)), Radarr doesn't detect the movie until I remove the periods. Once I remove them, it detects fine.

**Comment by Garderoben** [comment]
I have the same issue, just came here to report it and i saw this.

**Comment by WallaWallaWA** [comment]
Same here with [REC] (2007).

**Comment by galli-leo** [comment]
This is fixed in the latest nightly.
