### ISSUE TITLE
Sort/Rearrange Custom Filters

### ISSUE THREAD

**Issue by ghost** [Radarr/Radarr#6248]
**Is your feature request related to a problem? Please describe.**
Custom filters are ordered in the order they were created. It would be a plus if they would also be sortable/rearrangeable.

**Describe the solution you'd like**
Ability to sort them out kind of the way you can slide the quality profiles up and down.

**Describe alternatives you've considered**
None

**Additional context**
It will help if you have a growing amount of tags and filters.

[AB#610](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/610)

**Comment by YodaSpow** [comment]
This would be useful as have them scattered and like to keep them together.

**Comment by Loidauk** [comment]
This is a little thing that would be really nice to have. 
Is it something that can be taken up again?

**Comment by cryodream** [comment]
This is very much needed. Managing a huge library is impossible without this.
And, additionally:
- A better way to access filters. The drop-down is too short, even on my 4 monitor, which is limiting the number of filters I can use.
- More/better options to filter by, eg: cannot filter by "movies that are not in a collection", or by "collection name contains", etc...
## Finally, the very best thing would be
- Make filters additive/combined. Eg: enable filter by tag and by year and by rating, etc.

This would make filters super-powered - extremely easy and fast to use 🚀
You could filter into exactly what you want to be displayed in the list in seconds 🎂

**Comment by Qstick** [comment]
Dupe #5377
