### ISSUE TITLE
Adding custom script fails

### ISSUE THREAD

**Issue by ilarramendi** [Radarr/Radarr#6250]
**Describe the bug**
Radarr fails when trying to add a custom script

**To Reproduce**
1. Go to add a new custom script
2. Add any sh file and test
3. Click add button and fails

**Expected behavior**
Custom script is added

**Platform Information (please complete the following information):**
 - OS: debian 10
 - Docker: yes
 - Mono or .NET Version (System -> Status): .NET (3.1.10) 
 - Radarr Version: 3.0.2.4552 
 - Radarr Branch: Not sure, is linuxserver container with :latest tag

**Trace Logs**
https://pastebin.com/raw/tkxKpaC8

**Comment by bakerboy448** [comment]
Did you downgrade from `:develop` or `:nightly` to :latest?

**Comment by ilarramendi** [comment]
Yes! nightly to latest!

**Comment by bakerboy448** [comment]
This is not a bug; that is not supported.

go back to `develop` or `nightly`
https://wiki.servarr.com/Radarr_FAQ#can_i_switch_between_branches
