### ISSUE TITLE
Failing to upgrade to 3.1.0.4893 with the Built-in mechanism

### ISSUE THREAD

**Issue by eevlogiev** [Radarr/Radarr#6251]
**Describe the bug**
Hello, 
I am currently runnig on 3.0.2.4552 and I am trying to do an in-app update with the Built-in mechanism to the latest version 3.1.0.4893. However the upgrade is failing due an outdated library "libstdc++.so.6: version `GLIBCXX_3.4.21".  I haven't had any dependancy issues during in-app upgrades before.

**To Reproduce**
1. Go to System/Updates
2. Click on Install Latest
3. Upgrade is failing after phase "Restarting Radarr to apply Updates"

**Expected behavior**
Radarr to restart and boot with the new version

**Screenshots**

**Platform Information (please complete the following information):**
 - OS: QNAP TS-231P2, latest Firmware 4.5.2
 - Docker: No
 - Mono or .NET Version (System -> Status): .NET version - .NET Core Yes (3.1.10)
 - Browser and Version (Only needed for UI issues): 
 - Radarr Version: 3.0.2.4552
 - Radarr Branch: develop

**Trace Logs**
```
2021-4-27 13:32:39.5|Info|InstallUpdateService|Deleting old update files
2021-4-27 13:32:39.8|Info|InstallUpdateService|Downloading update 3.1.0.4893
2021-4-27 13:32:50.0|Info|InstallUpdateService|Verifying update package
2021-4-27 13:32:51.4|Info|InstallUpdateService|Update package verified successfully
2021-4-27 13:32:51.4|Info|InstallUpdateService|Extracting Update package
2021-4-27 13:33:04.2|Info|InstallUpdateService|Update package extracted successfully
2021-4-27 13:33:04.2|Info|BackupService|Starting Backup
2021-4-27 13:33:12.0|Info|InstallUpdateService|Preparing client
2021-4-27 13:33:16.1|Info|InstallUpdateService|Starting update client /share/CACHEDEV1_DATA/.qpkg/RadarrDotNet/tmp/radarr_update/Radarr.Update
2021-4-27 13:33:16.1|Info|InstallUpdateService|Radarr will restart shortly.
2021-4-27 13:33:16.1|Error|Radarr.Update|/share/CACHEDEV1_DATA/.qpkg/RadarrDotNet/tmp/radarr_update/Radarr.Update: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /share/CACHEDEV1_DATA/.qpkg/RadarrDotNet/tmp/radarr_update/Radarr.Update)
2021-4-27 13:33:16.1|Error|Radarr.Update|/share/CACHEDEV1_DATA/.qpkg/RadarrDotNet/tmp/radarr_update/Radarr.Update: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /share/CACHEDEV1_DATA/.qpkg/RadarrDotNet/tmp/radarr_update/Radarr.Update)
```

**Comment by RobinDadswell** [comment]
We have had a dependency update - you will need to update the version of the file within the NAS.

**Comment by eevlogiev** [comment]
dear @RobinDadswell ,
could you please suggest how can I update this file libstdc++.so.6 to the latest version? I've tried to find a version for Arm32 for QNAP but no luck here.

**Comment by RobinDadswell** [comment]
As stated above you would need to go onto Discord or the Subreddit for assistance with that - I don't have a QNAP and so am unsure how to do that on this platform - someone may be able to help in the support locations. If not it may be worth asking QNAP.

**Comment by ta264** [comment]
Sounds like the OS on your QNAP might be too old to support Radarr 3.1. you probably need to contact QNAP support.

**Comment by ta264** [comment]
Looks like your nas supports docker https://www.qnap.com/en-uk/product/ts-231p2

If so you should use a radarr docker image and that will sidestep the problem.  https://wiki.servarr.com/Docker_Guide
