### ISSUE TITLE
Manually type in indexer categories

### ISSUE THREAD

**Issue by Paul5656** [Radarr/Radarr#6254]
**Is your feature request related to a problem? Please describe.**
Radarr won't let you type in any indexer categories that it doesn't show you in the drop-down list. As a result, you cannot search any other categories other than what radarr shows.

**Describe the solution you'd like**
Ability to type in categories that radarr doesn't show.

**Describe alternatives you've considered**
Not sure there is any other solution other than to allow to key in categories manually as you used to be able to in the past.

**Comment by Qstick** [comment]
Which other categories would you want to search that are not there?

**Comment by Paul5656** [comment]
3020

**Comment by RobinDadswell** [comment]
That would be Audio/Video which would generally be music videos which aren't supported by Radarr

**Comment by Paul5656** [comment]
Oh well, alot (and I mean alot) of live performance DVDs and BluRays that have actual IMDB and TMDB pages get thrown in that category. And I'm not talking about 3-minute music videos.

**Comment by bakerboy448** [comment]
I'd argue it sounds like the indexers have those misclassified. as they are not music videos.

Swing by discord to discuss more if needed.
[Discord](https://radarr.video/discord)
