### ISSUE TITLE
FR Add TMDB List type for Keywords

### ISSUE THREAD

**Issue by mattheys** [Radarr/Radarr#6255]
**Is your feature request related to a problem? Please describe.**
Not particularly a problem

**Describe the solution you'd like**
I would like to be able to use TMDB keywords as a list, e.g. "marvel cinematic universe (mcu)" id 180547 or "dc extended universe" id 229266. This would allow the ability to automatically add films that are part of a larger collection as tmdb collections are generally Iron man collection, Ant man collection etc and not the larger universe.

**Describe alternatives you've considered**
Add all the collections seperatly but it's not ideal with new mcu film series coming out.

**Additional context**
There are a number of series like this, Monsterverse for example is the King Kong / Godzilla series but the Godzilla collection doesn't have Kong Skull island.
There may not be a huge demand for this, although since the other types of TMDB lists have been implimented it might not be too hard to add this extra type in.

**Comment by bakerboy448** [comment]
not sure on the appetite for this or feasibility, so I'll defer.

But there are various TMDB and/or IMDB lists that cover this w/o the keywords.

**Comment by Krandor1** [comment]
What i personally use for this is https://listrr.pro.   You can setup all
kinds of filters and it will create a custom Trakt list for you and
periodically update it (updates more often if you donate).  Then you can
import those trakt lists into radarr/sonarr.
--
Brian Hartsfield

**Comment by Qstick** [comment]
This will depend on if tmdb has an endpoint that allows us to query for movies by keyword

**Comment by Qstick** [comment]
Should be able to use this
https://developers.themoviedb.org/3/keywords/get-movies-by-keyword
