### ISSUE TITLE
Manual Category Options for Indexers without Categories in a Caps Call

### ISSUE THREAD

**Issue by bmarohl** [Radarr/Radarr#6256]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Working with non standard categories on various indexing sites isn't possible. Current case is with www.gingadaddy.com. These are their movie and tv categories:
85,45,42,48,51,54,60,69,66,72,67,75

I'd like a custom button so categories numbers could be manually entered.

**Describe alternatives you've considered**
I would just like some form of manual entry for cases like this.

**Additional context**

[AB#608](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/608)

**Comment by Qstick** [comment]
Assume you are using Jackett?

**Comment by bmarohl** [comment]
I do not, that data is my example. They advertise working with Radarr, so I picked them up as a secondary NZB indexer but it can't be setup natively.

And no, Jackett is for torrents only I believe.

**Comment by drizzt09** [comment]
I am also a Gingadaddy user and once adding gingadaddy options it hangs and cant even click on the dropdown.
Manual option or a preset that handles their custom category numbers would be awesome. thanks

**Comment by bakerboy448** [comment]
Sounds like gingadaddy does not support a caps call / does not abide by newszab standards

**Comment by drizzt09** [comment]
Give me instructions to do so and I'll try to get it for you

**Comment by bakerboy448** [comment]
> Give me instructions to do so and I'll try to get it for you

apologies on the delayed reply, but the standardized newzab caps call is `http://servername.com/api?t=caps`

Do you get different results if you authenticate with an API key than I do below?  should be the same url just append `&apikey={yourapikeyhere}`  My guess is the caps are the same as I got.


Looks like they don't respond with any categories in their caps call.  They should update their site to follow the newzab standard and actually provide the caps.

using `https://www.gingadaddy.com/api?t=caps`

@Qstick at least trying to access the caps w/o auth indicates they have no cats

```
<caps>
<!--  server information  -->
<server version="1.0" title="GingaDADDY" strapline="The DADDY of NZB indexers" email="support@gingadaddy.com" url="https://www.gingadaddy.com/" image="https://www.gingadaddy.com/themes/ICGstation/images/newlogo2.png"/>
<!--  limit parameter range  -->
<limits max="100" default="50"/>
<retention days="9001"/>
<registration available="no" open="no"/>
<searching>
<search available="yes"/>
<tv-search available="yes"/>
<movie-search available="yes"/>
</searching>
<categories> </categories>
</caps>
```

**Comment by drizzt09** [comment]
ya, even with my api key appended:

**Comment by drizzt09** [comment]
ya even with my api key appended i still do not get categories:
https://www.gingadaddy.com/api?t=caps&apikey={MyKeyWasHereWithoutBrackets}
https://www.gingadaddy.com/api.php?t=caps&apikey={MyKeyWasHereWithoutBrackets}
`<caps>

<server version="1.0" title="GingaDADDY" strapline="The DADDY of NZB indexers" email="support@gingadaddy.com" url="https://www.gingadaddy.com/" image="https://www.gingadaddy.com/themes/ICGstation/images/newlogo2.png"/>

<limits max="100" default="50"/>
<retention days="9001"/>
<registration available="no" open="no"/>
<searching>
<search available="yes"/>
<tv-search available="yes"/>
<movie-search available="yes"/>
</searching>
<categories> </categories>
</caps>`

I do notice they do use custom categories. Would it be beneficial if I got you a list of some of the custom categories? Could that be useful?

**Comment by bakerboy448** [comment]
Likely wouldn't hurt. Tho given they don't comply to newznab spec (further research indicate they don't/didn't  even properly handle errors if searching w/ an unsupported method)  I'm not sure if supporting effectively a completely custom usenet indexer is in the cards.  I'll defer to @Qstick on that.  If it can be done just with allow caps...maybe.

I'd also suggest you - join the presumable many others who probably have - and ask the admins to actually follow spec and not some unique custom implementation that no one else uses.

**Comment by drizzt09** [comment]
Movies cat=45,42,48,51
![image](https://user-images.githubusercontent.com/6366965/128102169-bf1389b2-1f65-4e54-a065-17920b968a5b.png)

TV cat=69,66,72,67,75
![image](https://user-images.githubusercontent.com/6366965/128102162-1c3c4d7a-09b8-4647-96ed-5dc4e5200df0.png)

**Comment by drizzt09** [comment]
ya it seems owners have disappeared.
They basically let the site run on autopilot.
But i paid for lifetime VIP like 8 years ago so I keep using it because it has great content. Just a nightmare with API.
But if Radaar, Sonaar and Prowlarr allowed custom categories it can work.
You can see here with Sonaar that I have the custom TV categories set and thats why Sonaar works:
![image](https://user-images.githubusercontent.com/6366965/128102675-8ca27639-2d59-40f4-9cd6-bf9b41c61663.png)
If there was an added option of "custom categories" where we can enter our own numbers I think it could work.

**Comment by bakerboy448** [comment]
Not sure what version of sonarr you're using, but didn't think it allowed custom/manual inputs?  3.0.6 is what's current.

Anyway, some additional food for thought from checking out GingaDaddy's forums it seems they are no longer even giving out VIP to users once the users have paid in 2020 and 2021. Staff is also - as you noted - gone.

I'm not sure of the benefits for making code changes to support a site that - by all appearances frankly - is scamming its users at this point; doesn't abide by any standards; has no devs/ownership to be found; and technically isn't able to be used by any new users.

Just my $0.02.  But I'll defer on what/if any code changes are needed.

**Comment by drizzt09** [comment]
Sonarr Version: 3.0.6.1265
.net Version: 4.8.0

this was someones workaround to get it working in Sonarr which worked for me:
![image](https://user-images.githubusercontent.com/6366965/128104241-6cb42154-42d4-43b0-8527-e91792cf0fbf.png)
but not working for radarr. Radarr says to leave blank to disable all:
![image](https://user-images.githubusercontent.com/6366965/128104318-fb3082ad-0740-4b82-ba8d-e1ad459d6c7b.png)
but then contradicts itself when you try to save:
![image](https://user-images.githubusercontent.com/6366965/128104362-1be35dd7-f8fa-4cd3-9d3a-ad43cf90642a.png)

**Comment by austinwbest** [comment]
I personally dont think it should be changed. I'm also not even sure how free-type is working there as it is a div and not a textbox.. If the site has no staff and doesn't want to add a proper caps call, well that kinda sums it up from my perspective.

**Comment by bakerboy448** [comment]
[Help Text for indexers was corrected;](https://github.com/Radarr/Radarr/commit/d2d81db8b3f41f45ac155cd51ac1ec3d215f8a0e) verbiage is likely long carry over from Sonarr back in the day which has two separate category inputs so 1 is able to be blank.

Nit summed it up.
Q can reopen if he desires, but I don't foresee any action to take on this for a site that is effectively defunct in addition to not following standards.
