### ISSUE TITLE
Catalan language is not in the list

### ISSUE THREAD

**Issue by xeviff** [Radarr/Radarr#6257]
**Is your feature request related to a problem? Please describe.**
When I want to set Catalan language to a movie I discover that this language is not in the list

**Describe the solution you'd like**
"Catalan" language appear should be in the list

[AB#611](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/611)

**Comment by Qstick** [comment]
Correct, because you are the first of 300k users to request it 😁

**Comment by jvmonjo** [comment]
Please, I would like to add it too. There's a huge user base who can benefit from it

**Comment by ta264** [comment]
So 2 users now 😁

**Comment by xeviff** [comment]
Well, I would want to point something, @ta264. There are a difference between users would benefit from it and whos enters on github :wink:

**Comment by jmcomellas** [comment]
Any update for this issue? It would be really useful to have Catalan at last....

**Comment by dtalens** [comment]
This issue remains open and has not been resolved.
