### ISSUE TITLE
feature request: torrentz2 indexer

### ISSUE THREAD

**Issue by muhahacz** [Radarr/Radarr#626]
Please add torrentz2 indexer, it has multiple sources (https://torrentz2.eu/help)

Example from SickRage
https://github.com/SickRage/SickRage/blob/4cc00e51a62cb2a19ff9ddea2390c1cde16efc3b/sickbeard/providers/torrentz.py

**Comment by zductiv** [comment]
If you use jackett, it was added a few days ago.

**Comment by onedr0p** [comment]
I will close this, please use Jackett.
