### ISSUE TITLE
Same title same year will not add second movie

### ISSUE THREAD

**Issue by Twisted7ech** [Radarr/Radarr#6262]
When trying to add a second movie of the same title, that was released the same year, the second movie will not add.
Checking logs confirms that it is not allowing the second movie to be added because it is expecting the folder to be the same as well.   By moving first movie to a new folder, second movie is added correctly.
I believe this to be rare that 2 movies have the exact same title and release year but I believe this is the second time I've encountered it myself.

**To Reproduce**
Add new movie
Search breakthrough
Currently the first 2 titles are breakthrough (2019)
add one
search breakthrough again
try to add the other

**Expected behavior**
I expected a second folder to be created with a -1  or -a

**Platform Information (please complete the following information):**
 - Docker: Yes
 - Radarr Version:  3.0.2.4552-ls95 by linuxserver.io

**Logs**
2021-5-1 19:35:28.0|Info|Database|Vacuuming Log database
2021-5-1 19:35:40.0|Info|Database|Log database compressed
2021-5-1 19:35:40.0|Info|Database|Vacuuming Main database
2021-5-1 19:35:54.4|Info|Database|Main database compressed
2021-5-1 19:41:55.3|Info|AddMovieService|Adding Movie [Breakthrough (2019)][tt7083526, 514439] Path: [/movies/Breakthrough (2019)]
2021-5-1 19:41:59.8|Info|RefreshMovieService|Updating info for Breakthrough
2021-5-1 19:42:05.8|Info|MediaCoverService|Downloading Poster for [Breakthrough (2019)][tt7083526, 514439] https://image.tmdb.org/t/p/original/t58dx7JIgchr9If5uxn3NmHaHoS.jpg
2021-5-1 19:42:05.8|Info|DiskScanService|Scanning disk for Breakthrough
2021-5-1 19:42:05.8|Info|DiskScanService|Completed scanning disk for Breakthrough
2021-5-1 19:42:05.8|Info|MovieScannedHandler|[Breakthrough] was recently added, performing post-add actions
2021-5-1 19:42:06.1|Info|MediaCoverService|Downloading Fanart for [Breakthrough (2019)][tt7083526, 514439] https://image.tmdb.org/t/p/original/2kR79WCmVIzFYQWH9X3LqcehvC2.jpg
2021-5-1 19:42:07.1|Info|MetadataService|Movie folder does not exist, skipping metadata image creation
2021-5-1 19:42:10.5|Info|MetadataService|Movie folder does not exist, skipping metadata creation
2021-5-1 19:42:12.4|Info|NzbSearchService|Searching 1 indexers for [Breakthrough]
2021-5-1 19:42:18.2|Info|DownloadDecisionMaker|Processing 18 releases
2021-5-1 19:42:25.2|Info|Sabnzbd|Adding report [Breakthrough.2019.1080p.BluRay.H264.AAC-RARBG-postbot] to the queue.
2021-5-1 19:42:28.2|Info|DownloadService|Report sent to SabNzbd. Breakthrough.2019.1080p.BluRay.H264.AAC-RARBG-postbot
2021-5-1 19:42:34.2|Info|MovieSearchService|Movie search completed. 1 reports downloaded.
2021-5-1 19:44:01.5|Warn|RadarrErrorPipeline|Invalid request Validation failed: 
 -- Path: Path is already configured for an existing movie: /movies/Breakthrough (2019)
2021-5-1 19:44:27.2|Warn|RadarrErrorPipeline|Invalid request Validation failed: 
 -- Path: Path is already configured for an existing movie: /movies/Breakthrough (2019)
2021-5-1 19:45:59.4|Info|MovieService|Assigning file [Breakthrough (2019).mp4] to movie [[Breakthrough (2019)][tt7083526, 514439]]
2021-5-1 20:10:32.8|Info|RssSyncService|Starting RSS Sync
2021-5-1 20:10:40.0|Info|DownloadDecisionMaker|Processing 100 releases
2021-5-1 20:10:46.6|Info|RssSyncService|RSS Sync Completed. Reports found: 100, Reports grabbed: 0
2021-5-1 20:38:28.3|Warn|RadarrErrorPipeline|Invalid request Validation failed: 
 -- Path: Path is already configured for an existing movie: /movies/Breakthrough (2019)
2021-5-1 20:39:04.2|Warn|RadarrErrorPipeline|Invalid request Validation failed: 
 -- Path: Path is already configured for an existing movie: /movies/Breakthrough (2019)
2021-5-1 20:39:57.6|Warn|RadarrErrorPipeline|Invalid request Validation failed: 
 -- Path: Path is already configured for an existing movie: /movies/Breakthrough (2019)
2021-5-1 21:05:20.6|Warn|RadarrErrorPipeline|Invalid request Validation failed: 
 -- Path: Path is already configured for an existing movie: /movies/Breakthrough (2019)
2021-5-1 21:06:16.7|Warn|RadarrErrorPipeline|Invalid request Validation failed: 
 -- Path: Path does not exist
2021-5-1 21:07:55.9|Info|AddMovieService|Adding Movie [Breakthrough (2019)][tt9617570, 576687] Path: [/movies/Breakthrough (2019)]
2021-5-1 21:08:12.6|Info|RefreshMovieService|Updating info for Breakthrough
2021-5-1 21:08:23.7|Info|MediaCoverService|Downloading Poster for [Breakthrough (2019)][tt9617570, 576687] https://image.tmdb.org/t/p/original/iTYAFNGSYT2Re9v5BxTfursWMAA.jpg
2021-5-1 21:08:23.8|Info|DiskScanService|Scanning disk for Breakthrough
2021-5-1 21:08:23.8|Info|DiskScanService|Completed scanning disk for Breakthrough
2021-5-1 21:08:23.8|Info|MovieScannedHandler|[Breakthrough] was recently added, performing post-add actions
2021-5-1 21:08:26.0|Info|MetadataService|Movie folder does not exist, skipping metadata image creation
2021-5-1 21:08:27.7|Info|NzbSearchService|Searching 1 indexers for [Breakthrough]
2021-5-1 21:08:29.1|Info|DownloadDecisionMaker|Processing 1 releases
2021-5-1 21:08:29.5|Info|MetadataService|Movie folder does not exist, skipping metadata creation
2021-5-1 21:08:31.4|Info|Sabnzbd|Adding report [Jim.Allison.Breakthrough.2019.DOCU.HDTV.x264-W4F] to the queue.
2021-5-1 21:08:31.6|Info|DownloadService|Report sent to SabNzbd. Jim.Allison.Breakthrough.2019.DOCU.HDTV.x264-W4F
2021-5-1 21:08:38.2|Info|MovieSearchService|Movie search completed. 1 reports downloaded.

**Comment by austinwbest** [comment]
This change wont be made to auto-append numbers. You can use a unique identifier such as TMDb or IMDb.
