### ISSUE TITLE
Not detecting some downloads sent to nzbget

### ISSUE THREAD

**Issue by rycore** [Radarr/Radarr#6265]
**Describe the bug**
When I add a movie to radarr it searches then sends it to nzbget, but then it doesn't track it from there, only seems to happen to some but not all movie. So far Tamara Drewe (2010) and From Dusk Till Dawn 3 (1999) are two that I noticed this with.

**To Reproduce**
1. Click "Add New"
2. Search for a movie.
3. Enable "Search for missing movie"
4. Click "Add Movie"

Alternatively
1. Go to a monitored movie that's not downloaded (but can be).
2. Click Search movie

**Expected behavior**
The movie should be added to nzbget, radarr should keep track of it, then rename/move that movie to the root folder.

**Platform Information (please complete the following information):**
 - OS: Debian GNU/Linux 9 (stretch)
 - Docker: Yes
 - Mono or .NET Version: .Net Core 3.1.10
 - Browser and Version (Only needed for UI issues): chrome 90.0.4430.93
 - Radarr Version: 3.0.2.4552
 - Radarr Branch: master

**Trace Logs**
[radarr.trace.txt](https://github.com/Radarr/Radarr/files/6414244/radarr.trace.txt)

**Comment by bakerboy448** [comment]
Please use one of the support channels: [Reddit](https://www.reddit.com/r/radarr/) or  [Discord](https://radarr.video/discord) for support/questions.

> 2021-5-3 12:12:40.8|Debug|ParsingService|No matching movie Tamara Drew

`Tamara Drew` != `Tamara Drewe`

https://trash-guides.info/Radarr/V3/Tips/Radarr-show-unknown-movie-items/
