### ISSUE TITLE
Unable to load movie results after manual search

### ISSUE THREAD

**Issue by ArGaMer** [Radarr/Radarr#6269]
**Describe the bug**
a message appears after failure to load movie results from a manual search. message is Unable to load results for this movies search, please try again later

**To Reproduce**
1. go to movie
2. Click Search next to history tab
3. wait till search is finished
4. error appears

**Expected behavior**
a list of torrents matching the required movie

**Platform Information (please complete the following information):**
 - OS: [Unraid 6.9]
 - Docker: [Yes]
 - Mono or .NET Version (System -> Status): [.NET 5.0.5]
 - Radarr Version: [3.1.1.4954]
 - Radarr Branch: [master]
[radarr.trace.txt](https://github.com/Radarr/Radarr/files/6425217/radarr.trace.txt)

**Trace Logs**
Turn on Trace logs under Settings -> General and wait for the bug to occur again. 
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**

[radarr.trace.txt](https://github.com/Radarr/Radarr/files/6425218/radarr.trace.txt)

**Comment by RobinDadswell** [comment]
@ArGaMer  that is not the log file that is a html file... also please use discord/reddit for support
