### ISSUE TITLE
Custom Script

### ISSUE THREAD

**Issue by shocker2** [Radarr/Radarr#627]
Hello,
  I'm trying to use a custom script the same way as Sonarr but is not working.
  Did the variables changed? 

As an example with my previous script I was getting via the $_SERVER variable the **sonarr_series_title**, **sonarr_episodefile_path**, **sonarr_episodefile_scenename** etc..

Thanks!

**Comment by galli-leo** [comment]
Now you have to use radarr_movie_title, etc. See https://github.com/Radarr/Radarr/wiki/Custom-Post-Processing-Scripts
