### ISSUE TITLE
Cant read generated NFO

### ISSUE THREAD

**Issue by Lerrrtaste** [Radarr/Radarr#6277]
Hi,

I tried every possible configuration for the "Kodi (XMBC) / Emby" Metadata setting.
Jellyfin is displaying the correct Title, description, date etc but the movie is not "matched" at all, meaning it can't fetch images or get other metadata, which is not from the nfo file. Only option is to disable nfo generation completly, then JF matches the movie based on the filename, which does work. The nfo from Sonarr works fine.

The Jellyfin log reports `Error reading existing nfo`.

(I guess this could also be a JF bug) 

Radarr Version 3.1.1.4954
Package Version 3.1.1.4954-ls103 by linuxserver.io 
.NET Yes (5.0.5)
Docker Yes
DB Migration 192
Jellyfin Version: 10.7.5

**Comment by bakerboy448** [comment]
Please use one of the support channels: [Reddit](https://www.reddit.com/r/radarr/) or  [Discord](https://radarr.video/discord) for support/questions.

could re-open if confirmed to be a radarr bug; check permissions;  and run down JF first

Also, please use one of the template in the future.  3rd party apps ignore both the templates and the blank issue restriction.

https://github.com/Radarr/Radarr/issues/new/choose
