### ISSUE TITLE
Radarr doesnt download torrent once it gets enough seeders

### ISSUE THREAD

**Issue by ikomhoog** [Radarr/Radarr#6282]
**Describe the bug**

When there are only torrents with seeders below the minimum amount, radarr doesnt recheck them later when the torrent has been out for a while and gained enough seeders.

Am I doing something wrong with my settings?
How can I make sure that radarr will download the movie after it has gained enough seeders?

**To Reproduce**

I expected radarr to download the torrent

**Screenshots**

![image](https://user-images.githubusercontent.com/9083045/117499720-e7385900-af7b-11eb-8d4b-9fb2f5c6b30c.png)

**Platform Information (please complete the following information):**
 - OS: Unraid
 - Docker: Yes
 - Mono or .NET Version (System -> Status): .NET 5.0.5
 - Browser and Version (Only needed for UI issues): 
 - Radarr Version: 3.1.1.4954
 - Radarr Branch: latest

**Comment by bakerboy448** [comment]
Please use one of the support channels: [Reddit](https://www.reddit.com/r/radarr/) or  [Discord](https://radarr.video/discord) for support/questions.

Please see the FAQ for how Radarr works.

This is expected if the release is no longer on the indexer's RSS feed (i.e. newly added feed).

**Comment by ikomhoog** [comment]
Sorry, I thought that this might not be the expected result and would thus be a bug.
