### ISSUE TITLE
Allow to add custom torrent in Manual Import

### ISSUE THREAD

**Issue by Gaudi111** [Radarr/Radarr#6293]
**Is your feature request related to a problem? Please describe.**
Sometimes the configured providers do not find a torrent for a specific release.

**Describe the solution you'd like**
In the Manual Import screen, I would like to have the possibility to add a manual magnet link/.torrent link/upload torrent file.
This way without having to configure extra providers, we could have the possibility of Radarr adding a torrent for a specific movie and having it processed accordingly.

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/5664943/117578605-7e5cf800-b0c5-11eb-9b4b-dc92ac3daa09.png)

**Comment by bakerboy448** [comment]
No plans for this.

just add it to your download client in Radarr's category and it'll show in Activity (you may need to enable show unknown)  it'll either automatically import or it'll have issues matching it and you can manually import it from queue
