### ISSUE TITLE
Re-download same release when file is missing

### ISSUE THREAD

**Issue by DIDev1** [Radarr/Radarr#6298]
**Is your feature request related to a problem? Please describe.**

I've had a massive crash of hard drives. And lost a lot of my movies. The issue is that Sonarr/Radarr doesn't import same release again by design (because it's already been imported). However i don't understand why i can't re-download the same file in case if the stored file is missing (like in my case after a data loss).

**Describe the solution you'd like**
A way to remove from sonarr/radarr history some movies that were downloaded but are not present anymore.
Or a change to the import process, and allow same downloaded file for missing movies.

**Describe alternatives you've considered**
Currently i'm moving each files manually which can be really time consuming.

**Additional context**

**Comment by bakerboy448** [comment]
- Nothing prevents you from re-downloading files.
- Removing / Readding the movie(s) should clear the history
- Manual Import exists.
