### ISSUE TITLE
Upgrading a movie doesn't delete subtitle files

### ISSUE THREAD

**Issue by karirafn** [Radarr/Radarr#630]
When Radarr finds a better version and downloads it the old video file is deleted but the subtitle files are left alone (.srt, .idx, .sub).

**Comment by onedr0p** [comment]
Yea, we don't have any subtitle support yet.

**Comment by karirafn** [comment]
But wouldn't it make sense to delete all files that are named the same as the old video file (but with different extensions)?

**Comment by onedr0p** [comment]
Yes but we don't yet.

**Comment by schumi2004** [comment]
Sonarr doesn't delete it either.

**Comment by karirafn** [comment]
Sonarr does delete them. I don't have any leftover subtitle files in my tv show folders where episodes have been upgraded from, for example, HDTV to BluRay. My movies however do have these leftover subtitle files.

**Comment by galli-leo** [comment]
@karirafn That's because we don't handle extra files (e.g. subtitles) yet like Sonarr does.

**Comment by galli-leo** [comment]
Closing this as this will be fixed once we handle extra files (separate issue).
