### ISSUE TITLE
Parse Bluray.avc and Bluray.hevc as BR-Disk not Bluray Encodes (German Scene Naming Standards)

### ISSUE THREAD

**Issue by ghost** [Radarr/Radarr#6307]
Remux / BR-DISK releases are parsed as encodes.

Example releases of Remux that are parsed as encodes

https://www.xrel.to/remux-release-list.html

They follow the German scene naming convention, found here

https://scenerules.org/t.html?id=2016_DE_AVC.nfo

Adding (german+bluray.avc) and (german+bluray.hevc) to the remux regex will solve the problem.

[AB#623](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/623)

**Comment by TRaSH-** [comment]
Okay here a few examples how English scene/p2p groups name their stuff.

These are BR-DISK that are recognized with the special Custom Format helper.
and no they aren't remuxes just look at the sizes. and when you look at the actual file they are .iso's or bluray folder structure both that Radarr don't support.

![image](https://user-images.githubusercontent.com/6155095/117851188-5a94e000-b286-11eb-8eb8-80fdc3eedf1e.png)

i could provide several screenshots with different groups, but at the end it will all come to the same result.

I don't think Team Radarr will do changes in how to recognize German own made scene rules for remuxes for only 1-5% of the users that prefer German remuxes that use the German scene naming vs the English naming what is used for remuxes and/or BR-DISK.

**Comment by TRaSH-** [comment]
> Radarr should still properly tag those as Remux or BR-DISK and not as 2160p (Encode).

Definitely as BR-DISK and not remux
As explained on discord, English scene doesn't do remux, so we fall back to the P2P releases that add the logical choice of remux to the release name.

Custom formats are made to help Radarr decide certain preferences and many other things.

When the devs find the time and the need they will update the BR-DISK regex.
What would result in better BR-DISK recornizing.

Thx for your suggestions, the devs will take your suggestion in consideration.

**Comment by holiday2** [comment]
Ok, and what about the the second part I mentioned? 

German scene rules for Remux could easily be implemented with my suggestion, without affecting English releases.

**Comment by austinwbest** [comment]
PR it bud. Make the change, provide a bunch of test cases that show it won't mess with existing logic.

That is the easiest way to move forward.

**Comment by holiday2** [comment]
No idea what you are talking about. I am not a coder, I am just pointing out the idea to fix it.

**Comment by ItsME6969** [comment]
An Unfinished Life 2005 1080p USA Blu-ray AVC DTS-HD MA 5.1-PTP
Jamesy Boy 2014 1080p Blu-ray AVC DTS-HD MA 5.1-PTP
Pig 2021 1080p Blu-ray AVC DTS-HD MA 5.1-ESiR
The Dry 2020 1080p Blu-ray AVC DTS-HD MA 5.1-CultFilms™
The Servant 1963 2160p UHD Blu-ray HEVC DTS-HD MA 2.0-GUHZER
Fired Up! 2009 Unrated 1080p CEE Blu-ray AVC TrueHD 5.1-EiMi
Erin Brockovich 2000 1080p EUR Blu-ray AVC TrueHD 5.1
Enchanted 2007 1080p Blu-ray AVC TrueHD 5.1-PTP
The Servant 1963 Bonus Disc 1080p Blu-ray AVC DD2.0-OLDHAM
Benny's Video 1992 1080p Blu-ray AVC DTS-HD MA 2.0-NoGroup
Cast Away 2000 1080p EUR Blu-ray AVC DTS-HD MA 5.1-FULLSiZE
Jiro Dreams Of Sushi 2011 USA Blu-ray 1080p AVC DTS-HD MA 5.1-TTG
Unbreakable 2000 2160p UHD Blu-ray HEVC HDR DTS-HD MA 5.1-MAXAGAZ
The Notebook 2004 1080p FRA Blu-ray VC-1 TrueHD 5.1-HDBEE
Shrek 2001 Blu-ray CEE AVC TrueHD 7.1-HDCLUB
Taxi Driver 1976 2160p UHD Blu-ray DTS-HD MA 5.1 DV HDR HEVC-UNTOUCHED
Black Widow 1080p 2021 3D Blu-ray AVC DTS-HD MA 7.1-3DTorrents
Dragonfly 2002 (USA) 1080p Blu ray AVC DTS HD MA 5 1
Back Street 1961 (Kino Lorber) 1080p BluRay AVC DTS HD MA 2 0
Flodder 3 1995 1080p Blu-ray GER AVC DTS-HD MA 2.0
Harold & Kumar Escape from Guantanamo Bay 2008 1080p Blu-ray VC-1 DTS-HD MA 7.1-PTP
Harold And Kumar Escape From Guantanamo Bay 2008 UNRATED SPECIAL EDITION 1080p Blu-ray AVC DTS-HD MA 5.1-Kamihikouki
The United Way 2021 1080i Blu-ray AVC DTS-HD MA 5.1-KiFFLOM
The Hitman's Wife's Bodyguard 2021 UHD Blu-ray 2160p HEVC Atmos TrueHD 7.1-CHDBits
Eight Legged Freaks 2002 REPACK 1080p Blu-ray AVC DTS-HD MA 5.1-COYS
The Deuce S02 1080p Blu-ray AVC DTS-HD MA 5.1-COASTER
Band of Brothers 2001 S01 1080p CEE Blu-ray VC-1 DTS-HD MA 5.1
Better Call Saul S01 1080p EUR Blu-ray AVC DTS-HD MA 5.1
Mr. Robot S02 1080p NLD Blu-ray AVC DTS-HD MA 5.1-PCH
Mr. Robot S03 1080p USA Blu-ray AVC DTS-HD MA 5.1-o0o
Band of Brothers 2001 S01 1080p BluRay VC-1 DTS-HD MA 5.1-NOGROUP

**Comment by holiday2** [comment]
Looks good! What happens now, developers have to implement it?

**Comment by bakerboy448** [comment]
> Looks good! What happens now, developers have to implement it?

Reviewed, discussed, and extensively vetted before being developed and tested to ensure it does not break existing functionality.

Given the existence of custom formats that currently mitigate this to a decent degree, it's fairly low on the totem pole of fish to fry

**Comment by TRaSH-** [comment]
I reached out to @ItsME6969 and asked him to help me to use his regex with the Custom Format BR-DISK Helper, so we can test it for a while.
The few tests i've done i must say i was impressed, and much better results then the build in BR-DISK and also no false positive till now.

He also has a few other regex for other better source recognizing we might consider to replace/add.

But let's test this first as Custom Format

**Comment by holiday2** [comment]
Sounds good. Hope to see it implemented if all goes fine!
