### ISSUE TITLE
manual import requires selection of film

### ISSUE THREAD

**Issue by vertig0ne** [Radarr/Radarr#632]
When manually importing a movie from the activity window you have to select a the film to bring up a dialog box to select which files to import.

Expected Results: Film imports under film name that was selected to bring up dialog.

Actual Results: Import errors because film name is not selected for the file.

**Comment by vertig0ne** [comment]
<img width="1267" alt="screen shot 2017-02-06 at 23 42 17" src="https://cloud.githubusercontent.com/assets/23177238/22671387/03d7cb40-ecc6-11e6-80d6-52f14e367269.png">

**Comment by hazell20** [comment]
also having this issue is their way to select the movie in the the mean time

**Comment by delphiactual** [comment]
try clicking the blank space in the movie column
