### ISSUE TITLE
Ability to determine which list downloaded movie

### ISSUE THREAD

**Issue by goku-son** [Radarr/Radarr#6326]
**Is your feature request related to a problem? Please describe.**
I have several lists I am testing. There appears to be no way to tell which list is responsible for the downloaded content. 

**Describe the solution you'd like**
I would like a way to be able to tell which list triggered the download, so I can either tweak the list or remove it altogether. 

**Describe alternatives you've considered**
Using one list at a time, but that is not practical. 

**Additional context**

**Comment by RobinDadswell** [comment]
Use a Radarr tag when creating the list and all new items for that list will have the tag you create

**Comment by goku-son** [comment]
Thanks @RobinDadswell!
