### ISSUE TITLE
setting username/password on Settings --> General requires restart but logout button is shown before restart

### ISSUE THREAD

**Issue by geogolem** [Radarr/Radarr#633]
This is kind of a minor bug.... but I ran into it.. and I thought authentication was broken, until I realized that the change i made in the configuration requires a restart to take effect...

STEPS to reproduce the problem:

Make sure Settings --> General --> Authentication is set to None.

shutdown radarr to make sure this setting of None is in effect.

Start radarr, go to Settings--> General --> Authentication and set it to something else, set up the username and password. Click the Save button.

do not restart radarr (even though radarr must be restarted for the change to take effect)
Navigate to System..  the logout button should not be present, but if you refresh the page in the browser, the log out button will be present on the System page.. click the logout button.

you will receive an error of the form: {
  "message": "Object reference not set to an instance of an object.",
  "description": "System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at Nancy.Authentication.Forms.FormsAuthentication.BuildLogoutCookie(FormsAuthenticationConfiguration configuration)\r\n   at Nancy.Authentication.Forms.FormsAuthentication.LogOutAndRedirectResponse(NancyContext context, String redirectUrl)\r\n   at Nancy.Authentication.Forms.ModuleExtensions.LogoutAndRedirect(INancyModule module, String redirectUrl)\r\n   at NzbDrone.Api.Authentication.AuthenticationModule.Logout() in P:\\$Applications\\Radarr-fullyMerged\\src\\NzbDrone.Api\\Authentication\\AuthenticationModule.cs:line 51\r\n   at NzbDrone.Api.Authentication.AuthenticationModule.<.ctor>b__2_1(Object x) in P:\\$Applications\\Radarr-fullyMerged\\src\\NzbDrone.Api\\Authentication\\AuthenticationModule.cs:line 22\r\n   at CallSite.Target(Closure , CallSite , Func`2 , Object )\r\n   at Nancy.Routing.Route.<>c__DisplayClass4.<Wrap>b__3(Object parameters, CancellationToken context)"
}

the reason this is happening, is because the logout button should not yet be present, because the username and password requires a restart to take effect. The solution is to restart radarr... you will then be required to log in with the username and password....  and then the logout button will work fine.. 

the issue is that we are showing the logout button because the authentication is enabled.. but the authentication does not come into effect until a restart and so the logout button is not handled properly.

perhaps the solution is to either not show the logout button until radarr is restarted and the authentication is in effect... or clicking the logout button will produce a dialog reminding the username that the authentication settings will not take effect until radarr is restarted....

simply allowing the user to click the button and receive that error is not proper..

This isn't a high priority issue because it doesnt really effect anything... it just confused me.. because i didnt realize that the setting only took effect upon restart and i was trying to test my new authentication settings....

**Comment by geogolem** [comment]
i was able to reproduce this in sonarr as well so I oppened an issue over there: https://github.com/Sonarr/Sonarr/issues/1666

**Comment by RyanAStrouse** [comment]
Having this happen now as well
