### ISSUE TITLE
Request: Add release year to queue

### ISSUE THREAD

**Issue by neuman1812** [Radarr/Radarr#6330]
Forgive me if this is the wrong location for this.  Just a simple request if possible. 

In my setup,  I dont automatically download movies when their added,  I have them set to pause.  Im limited on space,  so I have to be a bit selective when downloadng.

So I will often have a queue with several movies from the my "new list"    and some older movies that I manually add.  I then choose which one I would like to get when I have time to watch.  If  could add a "Year" column to my queue,  I would know which movies are new vs older.  So If I feel like a new one,  I can choose it.

![queue](https://user-images.githubusercontent.com/9267886/118581871-625df400-b760-11eb-80c3-77164c096cb4.png)

[AB#632](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/632)

**Comment by bakerboy448** [comment]
I'll leave it up for the moment and defer on the close....don't see this happening.

however, if you enable viewing the release title....that should give you the year ( at least as part of the grabbed release name)

**Comment by giuliapetenazzi** [comment]
I am doing it.
