### ISSUE TITLE
QNAP - dotnet upgrade

### ISSUE THREAD

**Issue by jun6lee** [Radarr/Radarr#6336]
Re: Mono warning changed to error.

Been following this: https://wiki.servarr.com/Radarr_System#update_to_net_core_version
The instructions don't work for QNAP.

Qnap uses old school systemv not systemd so it will be however those files are configured.

I manage to stop radarr using ./Radarr.sh stop
Starting up with the updated files is the problem.

Find here the contents of Radarr.sh
https://pastebin.com/sUrD9SGx

I have tried manually starting up the .exe with other errors.
but if you could guide what I should amend in the shell script, I may not encounter them (is the hope)

**Comment by bakerboy448** [comment]
> The Radarr v0.2 Qnap port was maintained by the Qnap forum community.
> Please contact us if you wish to maintain a v3 package so that we can include the appropriate install instructions.

https://radarr.video/#downloads-v3-nas-qnap

We do not support nor create the Qnap package.  This is something that you will need to work with the Qnap community to resolve.

Those instructions are for linux....not necessarily NAS specific.

Please use one of the support channels: [Reddit](https://www.reddit.com/r/radarr/) or  [Discord](https://radarr.video/discord) for support/questions.
