### ISSUE TITLE
Disable root folder checking

### ISSUE THREAD

**Issue by mlsmithjr** [Radarr/Radarr#6338]
**Is your feature request related to a problem? Please describe.**
Radarr is now giving this error status condition: "Download client qbit places downloads in the root folder /downloads/. You should not download to a root folder."
This is not literally a root folder location but a docker mapped filesystem.  Radarr thinks it is root because of the leading / but it is not.

**Describe the solution you'd like**
Remove this check.  If people store downloads in their root it's their problem.

**Describe alternatives you've considered**
Have the ability to dismiss this message and not see it again.

**Additional context**

**Comment by bakerboy448** [comment]
Please use one of the support channels: [Reddit](https://www.reddit.com/r/radarr/) or  [Discord](https://radarr.video/discord) for support/questions.

Please see the wiki with the healthcheck that explains the error.

root folder = library folder as noted within the rest of the ui.

the error is accurate

**Comment by austinwbest** [comment]
> Remove this check.  If people store downloads in their root it's their problem.

Except it leads to way more support issues when leaving it at 'its their problem' that users don't have to deal with, support members do 

> Have the ability to dismiss this message and not see it again.

Going to be added at some point but unlikely this check will be dissmissable
