### ISSUE TITLE
Fix Blackhole Torrent downloader

### ISSUE THREAD

**Issue by ashmandias** [Radarr/Radarr#634]
Forked from: https://github.com/Radarr/Radarr/issues/14

`17-1-13 13:28:21.5|Trace|Http|Req: 752 [POST] /api/release
17-1-13 13:28:21.5|Debug|ReleaseModule|Couldn't find requested release in cache, cache timeout probably expired.
17-1-13 13:28:21.6|Trace|HttpClient|Req: [GET] http://jackett:9117/xxx.torrent
17-1-13 13:28:21.6|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
17-1-13 13:28:21.7|Trace|HttpClient|Res: [GET] http://jackett:9117/xxx.torrent: 200.OK (148 ms)
17-1-13 13:28:21.7|Debug|TorrentBlackhole|Downloading torrent for episode 'XXX' finished (14773 bytes from http://jackett:9117/xxx.torrent)
17-1-13 13:28:21.7|Debug|TorrentBlackhole|Torrent download failed, trying magnet. (The method or operation is not implemented.)
17-1-13 13:28:21.7|Info|DownloadService|Report sent to Blackhole. XXX
17-1-13 13:28:21.7|Trace|EventAggregator|Publishing MovieGrabbedEvent
17-1-13 13:28:21.7|Trace|EventAggregator|MovieGrabbedEvent -> HistoryService
17-1-13 13:28:21.8|Trace|EventAggregator|MovieGrabbedEvent <- HistoryService
17-1-13 13:28:21.8|Trace|EventAggregator|MovieGrabbedEvent -> PendingReleaseService
17-1-13 13:28:21.8|Trace|EventAggregator|MovieGrabbedEvent <- PendingReleaseService
17-1-13 13:28:21.8|Trace|Http|Res: 752 [POST] /api/release: 200.OK (232 ms)
17-1-13 13:28:21.8|Debug|Api|[POST] /api/release: 200.OK (232 ms)`

**Comment by onedr0p** [comment]
In the next nightly, or release let me know if it's fixed.

**Comment by ashmandias** [comment]
Looking forward to testing.

**Comment by ashmandias** [comment]
Looks like it works!  Thanks!
