### ISSUE TITLE
Discover new and upcoming releases (like CouchPotato)

### ISSUE THREAD

**Issue by Paelsmoessan** [Radarr/Radarr#6355]
**Is your feature request related to a problem? Please describe.**

I am not getting Radarr to present new and upcoming releases. Is there a workaround for this?

**Describe the solution you'd like**

I would like to see lists similar to what CouchPotato used to show, In Cinemas, Out on Bluray etc.  

**Describe alternatives you've considered**

CouchPotato when it still was working as intended.

**Additional context**

Just let me sort through some different lists e.g. In Cinemas, Ratings (IMDB, TMDB), Bluray releases etc.

**Comment by Qstick** [comment]
Add a list and you can sort through it in discover. We don’t bake any in out of box.
