### ISSUE TITLE
Rename Event doesn't include relevant Renaming information

### ISSUE THREAD

**Issue by danimart1991** [Radarr/Radarr#6361]
**Is your feature request related to a problem?**
The movie rename event generates notifications for different providers that barely contains relevant information.

**Describe the solution you'd like**
As with the delete event, include a field that indicates if files have been renamed in the movie renaming process, as well as extra events for each renamed file. 

```
{
  "movie": {
    "id": 2255,
    "title": "The Man Who Shot Liberty Valance",
    "year": 2016,
    "releaseDate": "2002-01-18",
    "folderPath": "/movies/The Man Who Shot Liberty Valance (1962)",
    "tmdbId": 11697,
    "imdbId": "tt0056217"
  },
  "eventType": "Rename",
  "renamedFiles": true
}

---

{
  "movie": {
    "id": 2255,
    "title": "The Man Who Shot Liberty Valance",
    "year": 2016,
    "releaseDate": "2002-01-18",
    "folderPath": "/movies/The Man Who Shot Liberty Valance (1962)",
    "tmdbId": 11697,
    "imdbId": "tt0056217"
  },
  "movieFile": {
    "id": 2255,
    "relativePath": "The Man Who Shot Liberty Valance (1962) - BluRay 1080p.mkv",
    "path": "/movies//The Man Who Shot Liberty Valance (1962)/The Man Who Shot Liberty Valance (1962) - BluRay 1080p.mkv",
    "quality": "BluRay-1080p",
    "qualityVersion": 1,    
    "indexerFlags": "1",
    "size": 1467308032
  },
  "renameReason": "manual", // Optional
  "eventType": "MovieFileRename"
}
```

**Describe alternatives you've considered**
Maybe, until Radarr supports more than one moviefile. Get First movie file from the list that the service gives and include all in the RenameEvent instead of creating a new one.

**Additional context**
Already discussed a few points in #6333.
Related with #5934

[AB#553](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/553)

**Comment by Qstick** [comment]
Closing in lieu of #5934
