### ISSUE TITLE
Support for 3D and non 3D formats at the same time

### ISSUE THREAD

**Issue by duindain** [Radarr/Radarr#6370]
**Is your feature request related to a problem? Please describe.**
I can't have a movie in 3D and non 3D at the same time as the UI doesn't distinguish between them and would delete one to upgrade to the next based only on quality settings and custom rules

**Describe the solution you'd like**
We should be able to specify that we want a 3D version of a movie and also the normal version side by side or not probably in Edit in the movie details or during creating (Add new) the movie

**Describe alternatives you've considered**
I have already imported the custom naming schema from Trash Guides [here](https://trash-guides.info/Radarr/Radarr-recommended-naming-scheme/) so I can specify and preserve the state if a movie is 3D but i can't have both movies present at the same time unless I keep one version un-monitored outside of radarr

I currently keep a 3D collection folder with a series of 3D movies in it but i don't get great visibility over it and it isn't kept up to date or monitored as it would conflict with the existing non 3D versions

**Additional context**
Happy to learn of a different way to manage this or if its just not going to be implemented

Thanks

**Comment by bakerboy448** [comment]
Closing; Multi version of same movie dupe

**Comment by duindain** [comment]
Thanks for the exhaustive reply @bakerboy448 very helpful

Looks related to this feature which has been ongoing since 2017 #5791 and #1910 [1910](https://github.com/Radarr/Radarr/issues/1910)

at least 1910 is still open

**Comment by fryfrog** [comment]
In the mean time, run a second radarr and connect them via lists. One radarr can use another radarr as a list.

**Comment by duindain** [comment]
Thanks @fryfrog I was thinking of adding a custom rule to exclude 3D from the primary radarr to prevent getting the wrong release for now and either a 2nd radarr or just keep the 3D titles out of radarr and manage it myself

Cheers

**Comment by austinwbest** [comment]
> Thanks for the exhaustive reply @bakerboy448 very helpful
> 
> Looks related to this feature which has been ongoing since 2017 #5791 and #1910
> 
> at least 1910 is still open

Indeed it has been ongoing for awhile because it was not even a thought until v3 was cut loose, only months ago compared to the issue life time :)

**Comment by duindain** [comment]
@austinwbest are you commenting on #5791 or #1910? the issue has been open since 2017 and open in sonarr since 2013
It predates radarr v3 by several years? although v3 was in beta/alpha for quite awhile so I may be wrong on that number so its been a thought for four years at least in radarr and 8 in sonarr

If you are talking about the direction for solving and adding the milestone for 3.X, I'm glad to hear something is in the works and yes that has only been 7 months

By adding the issue numbers it has raised the link back to the open issue and hopefully the importance of the feature though since its already a milestone perhaps that's not needed now

Looking forward to it
Cheers
