### ISSUE TITLE
Can't Authenticate Trakt

### ISSUE THREAD

**Issue by mediacenterkodi84** [Radarr/Radarr#6372]
When I click the Authenticate link, it just takes me to a  error 500 page. When I try to bypass the authenticating by manually entering the user and list, it won't let me set the list to active. The test runs just fine with Enabled turned off, but whenever I try to enable the list, it won't pass on the test and it won't let me save.

**Comment by RobinDadswell** [comment]
In the future can you please fill in the template properly so that we have all the information needed.

Please update your Radarr instance as this is fixed in the latest release and is due to a breaking change that Trakt implemented in their authentication service

**Comment by mediacenterkodi84** [comment]
Thank you! I figured it was a break in the api I just didn't know if you were aware. My apologies on the template! Didn't see one when I opened the issue. This is the first issue ive ever opened! Thanks again!
