### ISSUE TITLE
Radarr movie metadata updates not being applied to folder path

### ISSUE THREAD

**Issue by teejo75** [Radarr/Radarr#6374]
**Describe the bug**
If you add a future movie release to be monitored for download, and the title or release date of the movie subsequently changes, the new information is not applied to the folder path, so when radarr finally detects and grabs the newly released movie, it puts it in the original folder name.

**To Reproduce**
Add newly announced movie "Upcoming Movie 3 (2021)" to download to default movie path `"/movies/Upcoming Movie 3 (2021)"`.
Time passes, movie subsequently changes title to "Upcoming Movie An Exciting Sequel (2022)". Radarr detects the metadata change and applies it to the record, however the folder path does not update and remains `"/movies/Upcoming Movie 3 (2021)"`.
Eventually the movie releases, radarr grabs it, and downloads it to the old folder name.

I've seen cases where a movie has been added without a release year, and when it was eventually released, radarr downloaded it to "Movie Title (0)".

**Expected behavior**
Folder path for the movie updates to reflect the new metadata (title & release year).

**Platform Information (please complete the following information):**
 - OS: Ubuntu 20.04
 - Docker: Yes
 - Mono or .NET Version (System -> Status): 
 - Browser and Version (Only needed for UI issues): 
 - Radarr Version: 3.2.2.5080
 - Radarr Branch: master

**Comment by bakerboy448** [comment]
This is not a bug; this is expected.  Movie Folders are not dynamic; 

just rename them if needed
https://wikijs.servarr.com/radarr/faq#how-can-i-rename-my-movie-folders

**Comment by teejo75** [comment]
This defeats the point of having management software if it can't automatically update information for movies it hasn't downloaded yet.

**Comment by RobinDadswell** [comment]
It can and does (assuming it's configured to) update the file name, the folder name should not generally contain information about the media file.

**Comment by teejo75** [comment]
> 
> 
> It can and does (assuming it's configured to) update the file name, the folder name should not generally contain information about the media file.

Your response makes no sense.

The folder name contains the title and year of the media. It remains static when you add future media, and if the information for that media changes, which happens from time to time, the folder name that was automatically generated based on the title of the media when you add the record does not change to reflect any potential future updates. This is the issue. So I need to manually go in and check if any of the future media I have added has potentially changed their title and/or release year, and manually update the folder entry in the record (note that since it's future media, the folder does not yet exist in the file system until the media is grabbed at some time in the future). Do you see the problem?

**Comment by austinwbest** [comment]
You can create empty folders if you choose to do it doesn't have to wait until some time in the future.

You can also choose to wait until the import is triggered and it'll create it then.

The latter will give you a better chance of accurate name/year since by the time it is released it is likely to have proper info on TMDb. With that said, it will not go back and update the name and year automatically just like sonarr won't update automatically if the name or numbering changes on TVDb

99 percent of the time this isn't an issue with radarr as things don't typically change (covid exception there)
