### ISSUE TITLE
Gaps RSS list support

### ISSUE THREAD

**Issue by olnir** [Radarr/Radarr#6375]
Request for implementation of support for RSS Lists for Gaps: https://github.com/JasonHHouse/Gaps

Gaps searches through your Plex Server or local folders for all movies, then queries for known movies in the same collection. If those movies don't exist in your library, Gaps will recommend getting those movies.

RSS Format Example from Gaps:

[{"imdb_id":"tt0057076","release_date":1963,"tmdb_id":657,"title":"From Russia with Love","poster_path":"https://image.tmdb.org/t/p/w185//zx4V17FP8oclNvOpTgs2iCCtiYk.jpg"},{"imdb_id":"tt0830515","release_date":2008,"tmdb_id":10764,"title":"Quantum of Solace","poster_path":"https://image.tmdb.org/t/p/w185//jN5YDjkjvcp0pX3zEVRJpnhcX7k.jpg"},{"imdb_id":"tt0122151","release_date":1998,"tmdb_id":944,"title":"Lethal Weapon 4","poster_path":"https://image.tmdb.org/t/p/w185//qc0GVMhZk44icQdynIin0xkE9YZ.jpg"},{"imdb_id":"tt3393786","release_date":2016,"tmdb_id":343611,"title":"Jack Reacher: Never Go Back","poster_path":"https://image.tmdb.org/t/p/w185//wxLUQ1pIms3HAlVGYvEG9zg2kDs.jpg"},

[AB#558](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/558)

**Comment by Qstick** [comment]
I'm pretty sure either custom list or RSS list option will work
