### ISSUE TITLE
Download Client - Flood - support for Completed Download Handling

### ISSUE THREAD

**Issue by AlexR00T** [Radarr/Radarr#6378]
**Is your feature request related to a problem? Please describe.**
I love Flood UI and would love to see it support Completed Download Handling. Sonarr currently supports it and I'm not sure why Radarr not yet. Please port it / add it and thank you a lot for your work 🙏

**Comment by bakerboy448** [comment]
.... seriously search before submitting another issue

https://github.com/Radarr/Radarr/issues/6328
