### ISSUE TITLE
Add On Added connection trigger

### ISSUE THREAD

**Issue by ricreis394** [Radarr/Radarr#6379]
**Is your feature request related to a problem? Please describe.**

In my setup I have very different types of content, let's say, horror and the other movies. I wish I had a simple solution to change the root path between these two categories. 

**Describe the solution you'd like**

My solution is to add a On Added on the connection triggers, that way I could develop a script to change that through the api. 

**Describe alternatives you've considered**

**Additional context**

I did a search and couldn't find any people asking for the onAdded trigger, neither asking why it isn't implemented.

**Comment by bakerboy448** [comment]
Would this not cover it? https://github.com/Radarr/Radarr/issues/4038

**Comment by ricreis394** [comment]
> Would this not cover it? #4038

More or less, instead of notifying I prefer to run a script so that will be 100% automatic without human need. And my added movies rarely comes from a list. 
But seems very similar overall.

**Comment by RobinDadswell** [comment]
> More or less, instead of notifying I prefer to run a script so that will be 100% automatic without human need. And my added movies rarely comes from a list.

That would just be a Custom Script connection - connections/notifications are used interchangeably as it's the same events and sections of the source code that drives them

**Comment by ricreis394** [comment]
> That would just be a Custom Script connection

Exactly that. How hard this feature request would be?

**Comment by ricreis394** [comment]
@bakerboy448 why did you closed? Still think its very useful...

**Comment by bakerboy448** [comment]
#4038 covers adding a connect trigger for on added
