### ISSUE TITLE
Deluge issues with seedbox

### ISSUE THREAD

**Issue by DarrenPIngram** [Radarr/Radarr#6386]
Issue configuring Deluge to work with seedbox.eu

Entering configuration information (that works in Sonarr) yields the error "unable to connect". Radarr does lack the base 
**To Reproduce**

Expect the client to be added.
**Screenshots**

**Platform Information (please complete the following information):**
 - OS: 
 - MacOS 10.15.7
 - Docker: 
 - No
 -  - Mono or .NET Version (System -> Status): 
 - Version
0.8.1.2135
.NET Core
Yes (3.1.13)
 - Browser and Version (Only needed for UI issues): 
 - Radarr Version: 
 - 3.2.2.5080
 - Radarr Branch: 
Master I think.

**Trace Logs**
Turn on Trace logs under Settings -> General and wait for the bug to occur again. 
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**

https://pastebin.com/w64EXjWF

**Comment by ta264** [comment]
https://Sea.seedhost.Eu:443/json returns 404

Please join the discord channel for support

**Comment by DarrenPIngram** [comment]
It seems to be more of a bug as the settings do not let you make a connection, compared to using the same settings in Sonarr. It seems like the missing ability to set a path is the issue?!

**Comment by RobinDadswell** [comment]
Turn advanced settings on - it's definitely not a bug as the setting exists. As previously mentioned please use either Discord or Reddit for support

**Comment by DarrenPIngram** [comment]
Noted. That resolved matters too. I guess the advanced options being turned
off was not noticed. It was "on" in Sonarr and Lidarr so I guess the eyes
didn't pick up on the difference.

‌
