### ISSUE TITLE
Large movie imports (greater than 200) crash

### ISSUE THREAD

**Issue by khumps** [Radarr/Radarr#6389]
**Describe the bug**
I have a library of 1500 movies. I can't seem to do an import of them all in 1 go as when it completed scanning and I clicked "Import 1500 movies" it immediately crashed. I currently am getting away by pausing the importer after 100 and importing in groups of 100. I can't find a definitive number that causes the crash. It happens 100% of the time when I try to do the entire library. If I segment it I can get everything imported without errors

**To Reproduce**
1. Open movie importer
2. Give a path with a large quantity of movies
3. Start scanning
4. Let scanning complete
5. Click import movies

**Expected behavior**
The import shouldn't fail

**Screenshots**
![image](https://user-images.githubusercontent.com/7849025/121789346-3b4de300-cba3-11eb-8134-a568bc43f0c8.png)
![image](https://user-images.githubusercontent.com/7849025/121789375-66383700-cba3-11eb-9db8-9a46c35007fd.png)

**Platform Information (please complete the following information):**
 - OS: Ubuntu 20.04
 - Docker: Yes (Kubernetes 20)
 - Mono or .NET Version (System -> Status):Net 5.0.5
 - Browser and Version (Only needed for UI issues): N/A
 - Radarr Version: 3.2.2.5080-ls105 by linuxserver.io

**Trace Logs**
https://gist.github.com/khumps/cd7cad2c5e0cd5c099a1cfd09753ac38

[AB#559](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/559)

**Comment by dcbinder** [comment]
Is there any work around?

**Comment by ta264** [comment]
Personally I'm not interested in bug reports when running in kubernetes. If you can replicate on a regular docker container with a normal bind mount or volume we might take notice. Come by the discord channel for help narrowing it down.
