### ISSUE TITLE
Lists: IMDB not showing up

### ISSUE THREAD

**Issue by jorijnsmit** [Radarr/Radarr#639]
When trying to add an IMDB list in Settings > Lists, I do not see an option to add one. Only CouchPotato, RSSList, StevenLu and Trakt List buttons show up. Am I missing something?

I am running v0.2.0.288 but the feature should be included since 0.2.0.267...

**Comment by onedr0p** [comment]
It's under presets on RSS List

**Comment by jorijnsmit** [comment]
Ah cheers missed that. Thanks!
