### ISSUE TITLE
Radarr ignores blacklist

### ISSUE THREAD

**Issue by teejo75** [Radarr/Radarr#6390]
**Describe the bug**
Radarr is ignoring the blacklist and continually grabbing the same release.

**To Reproduce**
1. In Activity screen, click 'remove from queue' button.
2. Release is added to blacklist (blacklist grows, but is ignored)
3. Radarr immediately grabs the same release again.

**Expected behavior**

Once added to the blacklist, the release is no longer grabbed from any source.

**Screenshots**

![remove-from-q](https://user-images.githubusercontent.com/437200/121792358-1a36d200-cc37-11eb-8df3-96a625539feb.png)
![blacklist](https://user-images.githubusercontent.com/437200/121792366-35094680-cc37-11eb-976d-7572188694c5.png)

**Platform Information (please complete the following information):**
 - OS: Ubuntu 20.04
 - Docker: Yes
 - Mono or .NET Version (System -> Status): N/A
 - Browser and Version (Only needed for UI issues): N/A
 - Radarr Version: 3.2.2.5080
 - Radarr Branch: master

**Trace Logs**
Turn on Trace logs under Settings -> General and wait for the bug to occur again. 
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**

[radarr.trace.txt](https://github.com/Radarr/Radarr/files/6643119/radarr.trace.txt)

[AB#571](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/571)

**Comment by bakerboy448** [comment]
If they don't have the same hash then this is expected.  My guess is the same torrent is uploaded to multiple trackers?

**Comment by resonanttoe** [comment]
I'm running in to this as well. It's repeatedly grabbing the same hash from the same tracker despite blocklist addition
![Screen Shot 2021-07-09 at 1 36 02 pm](https://user-images.githubusercontent.com/4146864/125072239-a2838800-e0ba-11eb-94f3-291c9b2e6979.png)
Checked the hash an its always the same on the torrent client. (It's also ignoring the quality profile entirely but that's another problem)

One thing I am noticing, is in the blacklist section, the info pane is saying that the tracker its picking it up from isn't the tracker of what is handed to the torrent client. 
![Screen Shot 2021-07-09 at 1 38 28 pm](https://user-images.githubusercontent.com/4146864/125072495-f8f0c680-e0ba-11eb-8931-1abd08cf3671.png)

From client: (It's always this same torrent, same hash and same tracker)
![Screen Shot 2021-07-09 at 1 39 21 pm](https://user-images.githubusercontent.com/4146864/125072681-2b9abf00-e0bb-11eb-8da4-4d7799f26f15.png)

So it appears its blacklisted the torrent from the specific tracker, but its not the right one? (Or it is, but it needs to do BeyondHD as well?)

Is it possibly caching the result/file and using that? (That seems unlikely)

**Comment by johnfenwick** [comment]
I'm also seeing this. Grabs torrent. I blacklist. Grabs the same torrent (same hash). I blacklist again. Over and over. I'd be happy to provide whatever logs are needed. I've unmonitored the movie in question for now, but can repeat the bug on demand.
