### ISSUE TITLE
SQLite version detection

### ISSUE THREAD

**Issue by Rubueno** [Radarr/Radarr#6393]
**Describe the bug**

After I was prompted the message "Currently installed SQLite version 3.7.17 is no longer supported. Please upgrade SQLite to at least version 3.9.0." I attempted to update the sqlite package from the available repos (CentOS 7). As there was no later version available from any CentOS specific repo, I downloaded a precompiled binary from the [sqlite website](https://www.sqlite.org/download.html) and overwrote the binary. The error message does not disappear as it seems to be looking at the version from `yum info sqlite`. It should however detect the version by running `sqlite3 --version`:
```
$ /usr/bin/sqlite3 --version
3.35.5 2021-04-19 18:32:05 1b256d97b553a9611efca188a3d995a2fff712759044ba480f9a0c9e98fae886
``` 

**To Reproduce**
On a CentOS 7 host:
1. `yum install sqlite`
2. Overwrite sqlite binary with precompiled one found in https://www.sqlite.org/2021/sqlite-tools-linux-x86-3350500.zip
2. Install radarr from provided release file
3. Start radarr
4. See error/warning at System -> Status

**Expected behavior**
I would expect the error to be gone with a later version installed (whether by yum/apt/dnf, compiling from source or by precompiled binary).

**Platform Information (please complete the following information):**
 - OS: CentOS 7
 - Docker: No
 - Mono or .NET Version (System -> Status): .NET 5.0.5
 - Radarr Version: 3.1.0.4893
 - Radarr Branch: develop
 
**Trace Logs**
Turn on Trace logs under Settings -> General and wait for the bug to occur again. 
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**

https://pastebin.com/ZWsWfKgQ
Seems irrelevant as it has no references to sqlite.

**Comment by bakerboy448** [comment]
Please use one of the support channels: [Reddit](https://www.reddit.com/r/radarr/) or  [Discord](https://radarr.video/discord) for support/questions.


Please see the wiki health entry linked via the healthcheck.

**Comment by Rubueno** [comment]
@bakerboy448 I'm sorry but this is not a support question.

**Comment by bakerboy448** [comment]
It is not a bug and is a support question.

https://wikijs.servarr.com/radarr/system#currently-installed-sqlite-version-is-not-supported

**Comment by Rubueno** [comment]
@bakerboy448 
> The SQLite3 library installed on your system is too old.
```
$ /usr/bin/sqlite3 --version
3.35.5 2021-04-19 18:32:05 1b256d97b553a9611efca188a3d995a2fff712759044ba480f9a0c9e98fae886
```

**Comment by bakerboy448** [comment]
> Note that Radarr uses libSQLite3.so which may or may not be contained in a SQLite3 upgrade package.
