### ISSUE TITLE
Original Language in Custom Formats not working

### ISSUE THREAD

**Issue by virusperfect** [Radarr/Radarr#6395]
**Describe the bug**
Creating a custom format that's supposed to detect the original language doesn't work properly. When searching for a movie the original language format will not be detected even if a release is in the original language of the movie. All other languages seem to work perfectly fine just "Original" doesn't work.

**To Reproduce**
1. Create a custom format called "Original" with the only condition being Language: "Original"
2. Manually search for releases in the movie page.
3. The "Original" format will never be applied.

**Expected behavior**
If the language of the release is in the original language then the format should be applied and the custom format score should be changed.

**Screenshots**

**Platform Information (please complete the following information):**
 - OS: Ubuntu 20.04
 - Docker: Yes
 - Mono or .NET Version (System -> Status): .Net 5.0.5
 - Radarr Version: 3.2.2.5080
 - Radarr Branch: master

**Trace Logs**
Turn on Trace logs under Settings -> General and wait for the bug to occur again. 
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**
[radarr.trace.txt](https://github.com/Radarr/Radarr/files/6665324/radarr.trace.txt)

[AB#853](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/853)

**Comment by bakerboy448** [comment]
based on your logs, I'm assuming you're searching [All About My Mother - 1999](https://www.themoviedb.org/movie/99-todo-sobre-mi-madre)  which is `Original Language Spanish; Castilian`

Tried this with [Roma](https://www.themoviedb.org/movie/426426-roma) and confirmed on  `4.0.0.5093`

Also confirmed with [Downfall](https://www.themoviedb.org/movie/613-der-untergang) as well.

Note:  Using the actual language (Spanish) or (German) works fine.

**Comment by foux** [comment]
I confirm this issue : 

- Doesn't work when using the "Original" language
- Works when using the actual original language

**Comment by foux** [comment]
Any news on this one?

**Comment by bakerboy448** [comment]
> Any news on this one?

Nope

**Comment by foux** [comment]
> > Any news on this one?
> 
> Nope

Anything we can do to help on this one?

**Comment by bakerboy448** [comment]
Learn to code or find someone who can and push this forward :)

the todo list across all 4 apps + backend servers is long and time / developer resources short
