### ISSUE TITLE
Documentation issue with chown

### ISSUE THREAD

**Issue by arthurwolf** [Radarr/Radarr#6397]
I'm trying to follow the instructions at https://wiki.servarr.com/Radarr_Installation#Debian.2FUbuntu to install on latest Debian.

When I run 

`sudo chown radarr:radarr /opt/Radarr`

It complains about: 

```
arthur@aquarelle  ~/Downloads  sudo mv Radarr/ /opt 
arthur@aquarelle  ~/Downloads  sudo chown radarr:radarr /opt/Radarr                                                                                                                                                                                     
chown: invalid user: ‘radarr:radarr’
```

Which I am guessing wildly might be because I do not currently have a "radarr" user around.

Does this mean I need to create one before running this command?

And if so, shouldn't the documentation / wiki page instruct me on what command to run to create said user?

**Platform Information (please complete the following information):**
 - OS: Latest Debian
 - Docker: No
 - Mono or .NET Version (System -> Status):  Not getting that far

**Comment by bakerboy448** [comment]
Please use one of the support channels: [Reddit](https://www.reddit.com/r/radarr/) or  [Discord](https://radarr.video/discord) for support/questions.

Correct, that is the issue.  

No plans to add Linux 101 how to create a user and users may or may not want to run radarr under radarr
