### ISSUE TITLE
Ability to DISABLE download quality settings

### ISSUE THREAD

**Issue by DarrenPIngram** [Radarr/Radarr#6398]
**Is your feature request related to a problem? Please describe.**

I would like the ability to DISABLE (not delete) quality profiles.

**Describe the solution you'd like**

I would like the ability to DISABLE (not delete) quality profiles. This would let me later on "upgrade" or use the settings, but for the current user case I would prefer a system-wise ability to DISABLE the profile so it cannot be used, e.g. the UltraHD profile.

**Describe alternatives you've considered**

There is none that I know of to achieve my goal (I do not consider individual program settings to be a replacement, I know I can set program X to download in only 720p, for example. 

**Additional context**

[AB#575](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/575)

**Comment by austinwbest** [comment]
I'm not really clear on the problem. If you don't want to use a profile, don't assign it.

I don't see a clutter issue as there are only a few of them. 

I don't see an issue with hard to find one when assigning it to a movie as again there are not many and it remembers the last one used. 

Maybe some clarification on a use case would help to understand.

**Comment by DarrenPIngram** [comment]
The issue I have had is that (somehow) other formats have at times been downloaded, despite them not being selected within my profile/an individual movie, e.g. disc images. I have not tracked the issue down yet for a number of reasons. Therefore I feel having the ability to disable an entire profile group that I am not going to use presently, e.g. UHD video, would work well, being similar to the enable/disable function that can be present within other functions within the application. I don't want to delete the entire profile(s) as one day I may want to use them.

**Comment by bakerboy448** [comment]
> despite them not being selected within my profile/an individual movie, e.g. disc images.

this is due to poor release naming.  Check out TRaSH's Custom formats, specifically BR-Disk

If you delete a profile you can just recreate it later , there's not much to it

**Comment by DarrenPIngram** [comment]
Thank you. I will check out the referenced guide. Of course, should it be
also possible to implement the requested feature some time, it may also
benefit a few others :)



‌

**Comment by bakerboy448** [comment]
closing; no plans  maybe one day.
