### ISSUE TITLE
Title detection fails with "French" in the title

### ISSUE THREAD

**Issue by pums974** [Radarr/Radarr#6412]
The "French" tag is sometimes disturbing title detection

**To Reproduce**
1. Search for "The French Minister" 
2. Find "The French Minister 2013 1080p BluRay x264 anoXmous"
3. Find out that it is rejected because the detected title is "The"

[AB#587](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/587)

**Comment by bakerboy448** [comment]
Can you fill in the rest of the bug template you decided to blow away...?


Possibly the fix
https://github.com/Radarr/Radarr/issues/5574

**Comment by pums974** [comment]
Yeah, sorry, that was rude of me. I was in a hurry but that's no excuse.
Here it is

**Platform Information:**
 - OS: Synology
 - Docker: Yes (linuxserver)
 - Mono or .NET Version (System -> Status): .NET 5.0.5
 - Radarr Version: 3.2.2.5080-ls106 by linuxserver.io

The trace log : https://0bin.net/paste/lp4H8DQ+#I41Y7LNBs+FUld3nUTXhEG3VL3x1EUSg2ux94J0H900
The log was too large, I hope I didn't remove relevant informations

**Comment by pums974** [comment]
Do you need more infos ?

**Comment by bakerboy448** [comment]
For posterity If/when the log expires

`The.French.Minister.2013.720p.BluRay.x264-ROUGH [PublicHD]`
![74B8C24F-1911-42C3-92E3-4740BDCA0A19](https://user-images.githubusercontent.com/55419169/125077657-f6747980-e086-11eb-84ea-fca8747f1999.png)

**Comment by bakerboy448** [comment]
Consolidating into 

https://github.com/Radarr/Radarr/issues/6474
