### ISSUE TITLE
State Error

### ISSUE THREAD

**Issue by Crane49** [Radarr/Radarr#6419]
OS: Windows 10 Radarr: 3.2.2.5080 SAB: 3.3.0
I get akeyerror when try to use Slickbeard mp4 converter. I have the latest Radarr and Slickbeard converter. This started to happen after i updated radarr. i have contact Higgins and I can use the api site to authincate but I cannot get the script to finsh as it just says sate error in sabdnzb and never completes the script. when i search the logs i see an api error but no way to fix it.

please help
mike c.

**Comment by bakerboy448** [comment]
Please use one of the support channels: [Reddit](https://www.reddit.com/r/radarr/) or  [Discord](https://radarr.video/discord) for support/questions.
