### ISSUE TITLE
I find it annoying when searching for wanted films in Radarr that there isnt an actual "wanted" radio button as there is in Sonarr. Would love that added if possible :-)

### ISSUE THREAD

**Issue by Chipster69** [Radarr/Radarr#6428]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

[AB#93](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/93)

**Comment by ta264** [comment]
Use filters.

Duplicate #5045

**Comment by bakerboy448** [comment]
Also on the FAQ
https://wiki.servarr.com/radarr/faq#where-did-wanted-and-cut-off-unmet-go
