### ISSUE TITLE
{MediaInfo VideoDynamicRange} not labeling all HDR content correctly

### ISSUE THREAD

**Issue by Mathis001** [Radarr/Radarr#6434]
**Describe the bug**
When setting up Standard Movie Format to include {MediaInfo VideoDynamicRange}, the file renamer excludes this info even if the file is HDR (Color Primaries BT.2020). Looking through the code, it appears that since the file does not contain video transfer characteristics, it fails the HDR match.

Eg. 

With the "Standard Movie Format" as the following:
> {Movie Title} ({Release Year}) [{Quality Title}] [{MediaInfo VideoBitDepth}Bit] {[MediaInfo VideoDynamicRange]} [{MediaInfo VideoCodec}]

File with Color Primaries bt.2020 should be named:
> Movie Title (2021) [WEBDL-2160p] [10Bit] [HDR] [x265].mkv

But is named:
> Movie Title (2021) [WEBDL-2160p] [10Bit] [x265].mkv

"File Details" within radarr for the file in question shows:
> Details
Audio Bitrate - 3395168
Audio Channels - 5.1
Audio Codec - DTS
Audio Languages - English / English
Audio Stream Count - 2
Video Bit Depth - 10
Video Bitrate - 17566088
Video Codec - x265
Video Fps - 23.976
Resolution - 3840x2160
Run Time - 2:04:44
Subtitles - English / Czech / Danish / Dutch / Finnish / French / German / Hungarian / Italian / Norwegian / Polish / Portuguese / Romanian

This is missing any reference to HDR or Color Primaries that can be seen with mediainfo (ran from command line):
>Video
ID                                       : 1
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L5.1@Main
Codec ID                                 : V_MPEGH/ISO/HEVC
Duration                                 : 2h 4mn
Bit rate                                 : 17.6 Mbps
Width                                    : 3 840 pixels
Height                                   : 2 160 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) fps
Original frame rate                      : 23.976 (23976/1000) fps
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 10 bits
Bits/(Pixel*Frame)                       : 0.088
Stream size                              : 15.3 GiB (83%)
Writing library                          : x265 3.0_RC+11-72188bd2f034:[Linux][GCC 4.9.2][64 bit] 10bit
Encoding settings                        : cpuid=1111039 / frame-threads=3 [...]
Default                                  : Yes
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.2020
Matrix coefficients                      : BT.2020 non-constant

**To Reproduce**
Find any HDR file with a Color Primaries using BT.2020/ Rec 2020, but without any video transfer characteristics and set the Standard Movie Format to include {MediaInfo VideoDynamicRange} like above. Attempt to rename the file with the renamer.

**Expected behavior**
The renamed filed should include "HDR" when using {MediaInfo VideoDynamicRange} on a BT.2020 file. 

Looking through the code, it does appear that defines Color Primaries for HDR as BT.2020 then checks case-insensitively for color primaries, as well as verify 10bit, and importantly checks for Video Transfer Characteristics and verifies not null or whitespace. 
https://github.com/Radarr/Radarr/blob/a7088ce387f428cc2ab8207506b2771ae783859b/src/NzbDrone.Core/MediaFiles/MediaInfo/MediaInfoFormatter.cs#L15
https://github.com/Radarr/Radarr/blob/a7088ce387f428cc2ab8207506b2771ae783859b/src/NzbDrone.Core/MediaFiles/MediaInfo/MediaInfoFormatter.cs#L604-L622
Well the mediainfo on the above file does not contain Video Transfer Characteristics, but only color primaries and matrix coefficients.

I am by no means a video codec or mediainfo expert, but would it be beneficial to check if color range OR transfer characteristics OR matrix coefficients has "bt.2020" to verify that a file is HDR? Is there something I am missing on why transfer characteristics are important?

**Screenshots**
Available on request, although I copied all of the relevant data.

**Platform Information (please complete the following information):**
 - OS: Ubuntu 16.04
 - Docker: No
 - Mono or .NET Version (System -> Status): Mono JIT compiler version 6.12.0.122 (tarball Mon Feb 22 17:28:32 UTC 2021)
 - Browser and Version (Only needed for UI issues): Chrome Version 91.0.4472.114 (Official Build) (64-bit)
 - Radarr Version: 3.2.2.5080

**Trace Logs**

Logs do not return anything since the preview rename reports "Success! My work is done, no files to rename.", therefore there is no log since a rename attempt is not made. If you can direct me to gather specific logs, I will be happy to report back.

**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**

TBD if needed.

[AB#1153](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1153)

**Comment by bakerboy448** [comment]
Believe this to have been likely switched with FFprobe on nightly; can re-open in the future if needed
https://github.com/Radarr/Radarr/commit/f0f8a4ffaf65b892aa6e6fb6290096dfd8d5e7b2
