### ISSUE TITLE
API refusing IPv6 API calls

### ISSUE THREAD

**Issue by perimore** [Radarr/Radarr#6436]
**Describe the bug**

SABnzbd is using the NZBtomedia script below on the same host. The host has IPv6 disabled but I am still seeing the below in the logs:

https://github.com/clinton-hall/nzbToMedia

2021-07-01 12:36:15.9|Info|Auth|Auth-Unauthorized ip ::ffff:127.0.0.1 url 'http://ds.local:7878/api/command'

First, why is the host sourcing from the v4 mapped v6 address.

And why does Radarr reject this?

**To Reproduce**

Run the NZBtomedia script.

**Expected behavior**

Script sourced from ipv4 and/or Radarr accept the connection.

**Screenshots**

**Platform Information (please complete the following information):**
 - OS: Debian 10.7
 - Docker: No
 - Mono or .NET Version (System -> Status): .NET 5.0.5
 - Browser and Version (Only needed for UI issues): 
 - Radarr Version: 3.2.2.5080
 - Radarr Branch: master

**Trace Logs**
Turn on Trace logs under Settings -> General and wait for the bug to occur again. 
**Upload the full log file here (or another site (e.g. pastebin) and link it). Issues will be closed, if they do not include this!**

**Comment by ta264** [comment]
This looks like a configuration issue to me. If you work it through with us on the discord channel to prove it is a bug we can reopen
