### ISSUE TITLE
[Feature request] Changing path dynamically depending on quality

### ISSUE THREAD

**Issue by stefangross** [Radarr/Radarr#6439]
**Is your feature request related to a problem? Please describe.**

I have different qualities of movies in different folders and I always have to move them manually since I don't know when adding a movie which quality is available. It would be nice if Radarr could do this for us

**Describe the solution you'd like**

I would like an option where you could set a path on a quality (see screenshot). The paths that you could chose from in the quality settings is retrieved from your media root folders within Radarr. When Radarr is grabbing a movie that has a quality with a custom path set, it would dynamically change the path of that movie. Since Radarr is already deleting previous movie when upgrading I don't see an issue with actually changing the path when upgrading.

**Describe alternatives you've considered**

doing it manually which is undesirable

**Additional context**

![image](https://user-images.githubusercontent.com/8499989/124362513-9d938400-dc35-11eb-94f9-60c4f612a59c.png)

[AB#1177](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1177)

**Comment by stefangross** [comment]
Id love to have a discussion on how to implement this as I'd like to contribute as well.

**Comment by bakerboy448** [comment]
Closing  Q/Ta/Robin can reopen if needed, but I don't believe we have plans for this given the eventual integration of https://github.com/Radarr/Radarr/issues/1910

**Comment by austinwbest** [comment]
I don't think this would really be something to be added. Property tokens where removed from the filename to eliviate some headaches so I dont think a dynamic root folder change would really be put in.

If it was, it would be an upstream pull for something like this. You are welcome to try and convince the sonarr crew lol

**Comment by stefangross** [comment]
> Closing Q/Ta/Robin can reopen if needed, but I don't believe we have plans for this given the eventual integration of #1910

this has nothing to do with #1910 . This request is not about keeping multiple copies of a movie. For my feature request it could easily delete the old movie when doing an upgrade after it changes the path.

**Comment by ta264** [comment]
This was in Radarr 0.2 and we removed it as it caused a lot of grief. No plans to put it back in.

**Comment by stefangross** [comment]
Also for Sonarr this makes much less sense. 
Lets say its grabbing s01e01 with 1080p quality, then it would move it to the normal season folder.  When grabbing s01e02 with 2160p quality it would need to move it to a second location so Sonarr would have to be able to keep track of two different folders at the same time, for the same show AND season. This is not what im trying to suggest here.

I dont want to change anything with filename or anything like that, the only thing that needs to be done is to set a path depending on IF the user has set a custom path. I can already change the path manually in Radarr for a movie when i notice it grabbing a certain quality. I'd like Radarr to change the path automatically instead, as an option. If the user doesnt set a path for that quality the movie/release gets handled as per todays implementation.

@ta264 if you dont mind me asking, what kind of grief was it causing? I want to ensure we are not misunderstanding each other on what I'm actually proposing here (English is not my first language)

**Comment by ta264** [comment]
Allowing root folders to change after the movie was added (which would be required for this to work) caused a lot of bugs. It's too painful / dangerous given the way the code is structured.

**Comment by stefangross** [comment]
@ta264 is it the same thing if i change it manually then? Would that cause the exact same issues as you are mentioning ? If i change the folder path in the Radarr UI, it's asking me if I also want to move all the files as well. If a user is allowed to do everything in the UI manually, why wouldn't it be possible to automate that process? 
I want to make absolute clear im not questioning you here, I just want to understand better. I appreciate all the hard work you guys put in.

![image](https://user-images.githubusercontent.com/8499989/124363425-73dd5b80-dc3b-11eb-8626-9aec4da945d1.png)
