### ISSUE TITLE
Manual snatching of release does not pass category label and starts releases in stopped mode in rtorrent/ruTorrent

### ISSUE THREAD

**Issue by testarea1** [Radarr/Radarr#644]
Using seedbox with rtorrent 0.9.6/ruTorrent 3.7 setup.

When rss sync doesn't find a release automatically, I need to do a manual search/grab. When grabbing manually and having radarr send the download to the seedbox, I've noticed that the download is always defaulting to "stopped" mode along with missing the category label I've setup in the download clients settings. I have to manually start the torrent and then set the category label manually so my autotools work properly. 

When it auto grabs a release from the rss sync, everything seems fine, just seems to be an issue with manual grabbing and sending.

Using latest radarr develop release as of Feb, 6th.

**Comment by weirdcrap** [comment]
The only time I have ever seen this sort of behavior is when the indexer is giving out magnet links not torrents. If you are getting magnet links this is a known issue with Sonarr/radarr -  rutorrent/rtorrent.

**Comment by onedr0p** [comment]
I have no issue with rtorrent/rutorrent and manual grabs or rss sync.

**Comment by testarea1** [comment]
This appears to be related to magnet links. Non-magnet links grab fine. I'm using Jackett with all the indexers and have rarbg configured and they use magnet links through Jackett. All other non-magnet links grab and download automatically.

**Comment by weirdcrap** [comment]
That is a known issue with Radarr/sonarr. Most people get referred to this issue: https://github.com/rakshasa/rtorrent/issues/107

**Comment by testarea1** [comment]
Looks like Sonarr may have fixed this issue, would this also work for Radarr? https://github.com/Sonarr/Sonarr/commit/3590fedeaf5b0372930f56d8f02aedc77b3c5c94

**Comment by weirdcrap** [comment]
Oh neat! I will have to spin up a test VM with rtorrent and Sonarr and see how the new changes behave. It would be nice to not have to need the torrent black hole functionality.

**Comment by testarea1** [comment]
Sonarr also just committed another fix: https://github.com/Sonarr/Sonarr/commit/2326db0deabb387a1020466ae66e8cdbe5e6c2c2

**Comment by weirdcrap** [comment]
@testarea1 I opened a new issue requesting someone  merge the sonarr fixes into the radarr rtorrent implementation.

**Comment by bobbintb** [comment]
Does this definitively resolve the issue? I don't want to migrate everything over again if it doesn't.
