### ISSUE TITLE
STRM Support

### ISSUE THREAD

**Issue by hasamba** [Radarr/Radarr#6450]
**Describe the solution you'd like**
Radarr (and sonarr) will treat strm files as normal video files

**Additional context**
my IPTV comes with a VOD, from this VOD i create a STRM file for each movie/episode, kodi & emby treat it like a local movie, they scan it and play it like any other movie,
i would like radarr, sonarr and mostly bazarr to read them also so i can download subtitles for them.
i know that a lot of people store their movies on google drive and use strm files to view them locally.

thanks

[AB#1223](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1223)

**Comment by bakerboy448** [comment]
Ref #3104

no plans at this time; especially since release groups don't release STRM files; I'd suggest converting those to mkv/mp4 

tabling for future consideration
