### ISSUE TITLE
Allow Subdirectories when renaming movies

### ISSUE THREAD

**Issue by Phillips57** [Radarr/Radarr#6452]
**Is your feature request related to a problem? Please describe.**
I've seenow my movie collection is getting larger I'm getting issues on how long it takes to list the full folder, due to the number folders in the root movie directory
(Not a Radarr issue)

**Describe the solution you'd like**
At the moment my directory structre is
/volume1/movies/[Movie Name (Year)]

what id like to be able to do is add the Year as an additional folder in the Renamer Section of the Config
/volume1/movies/[YEAR]/[Movie Name (Year)]
Then Radarr would create the Year Folder if missing as well as the Movie Folder that contains the movie files.

**Describe alternatives you've considered**
I've looked at other Renaming tools, but once they create the new directory structure Radarr is no longer able to see the files, and tags all movies as missing.

[AB#1228](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1228)

**Comment by RobinDadswell** [comment]
`({Release Year})/{Movie Title} ({Release Year})` inside the Movie Folder Format should work, but you may need to take account on the ability for media servers/players handling that (if applicable)

To rename existing folders you will need to do as per the instructions in this guide https://wiki.servarr.com/en/radarr/faq#movie-folders-named-incorrectly

**Comment by RobinDadswell** [comment]
If that doesn't work come by the discord and someone will be happy to help further
