### ISSUE TITLE
Feature: Start & pause torrents

### ISSUE THREAD

**Issue by drtcode** [Radarr/Radarr#6457]
It'd be nice to be able to start & pause activity queue. The calls already exist to add & remove, so I'd expect this should be an relatively simple extension to add a start & pause button to the ribbon and make the start/stop/pause call into the torrent client's API.

[AB#1237](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1237)

**Comment by austinwbest** [comment]
Id expect this to be done in the client directly. Not sure it is necessary for arr to do it not to mention that has to be added to every client class since there isn't a one call fits all.
