### ISSUE TITLE
More options for movie folder

### ISSUE THREAD

**Issue by Rajackar** [Radarr/Radarr#6465]
**Is your feature request related to a problem? Please describe.**

I have my movies organized based on quality, like 2160p, 1080p etc. In previous versions I used the Movie Folder Format option in media management and used {quality title} to create the correct folder. In recent versions this is no longer supported.

**Describe the solution you'd like**

If possible I'd like to see the option return to use the {quality title} (and maybe others) to be used in folder creation.

I've also considered using the Standard Movie Format option as this allows for the creation of sub folders (and maybe even renders the movie folder format option redundant) and will work for me just fine. The only problem is that the folder option needs to have movie title in there. This is mandatory and can't be left empty. 

[AB#1253](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1253)

**Comment by austinwbest** [comment]
Sorry but this was removed for a reason a will not make a return.

It has been answered numerous times previously so if you are curious on the why you can search and read some of the closed ones.

An extra folder is going to be the only possible solution

**Comment by Rajackar** [comment]
Thanks for the quick response. I've done some digging and can't really find the reasoning behind this but I'm sure it was done with a good reason. 
Is there a chance we can maybe accept an empty entry for movie folder? That would also fix my issue.

**Comment by ta264** [comment]
Not really. The top level folder needs to be unique per movie and independent of any file metadata

**Comment by Rajackar** [comment]
OK, thanks for explaining.
