### ISSUE TITLE
Query for releases could use all titltes shown in "Titles" tab

### ISSUE THREAD

**Issue by bertoccoj** [Radarr/Radarr#6468]
**Is your feature request related to a problem? Please describe.**
Here's my problem. i have this movie i want to download: https://www.themoviedb.org/movie/624812

it is shown in radarr like this:
![image](https://user-images.githubusercontent.com/51322002/125373630-e2b56580-e35b-11eb-9172-3f8a2c304545.png)
and it have these Alternative Titles:
![image](https://user-images.githubusercontent.com/51322002/125373681-f95bbc80-e35b-11eb-84a9-f6b0e9d62e29.png)

i'm using jackett's Torznap, and it shows on the log that it searched for these titles:
![image](https://user-images.githubusercontent.com/51322002/125373842-33c55980-e35c-11eb-9641-c59f38cf11ee.png)

and found no matching releases for the quality on the Search tab:
![image](https://user-images.githubusercontent.com/51322002/125373981-6d966000-e35c-11eb-9ed1-273a6a429a2b.png)

the thing is, if it used the title "Omoi, Omoware, Furi, Furare"(one of the titles in the alternatives tab) it would have found Bluray 1080p release on the same tracker
![image](https://user-images.githubusercontent.com/51322002/125375360-4b521180-e35f-11eb-84bc-147ee3e42b9a.png)
as seen on jackett web interface
![image](https://user-images.githubusercontent.com/51322002/125375419-61f86880-e35f-11eb-88e2-72a4690141f4.png)

**Describe the solution you'd like**
I would like radarr to use all available titles instead of only TheMovieDb titles for search and if possible allow m eto add custom ones that are not listed there(but that's not extremely necessary as the other request).

[AB#1258](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1258)

**Comment by bakerboy448** [comment]
I'll defer to Q, but I don't believe we have plans to change this.

https://wiki.servarr.com/radarr/faq#how-does-radarr-handle-foreign-movies-or-foreign-titles

**Comment by bertoccoj** [comment]
> I'll defer to Q, but I don't believe we have plans to change this.
> 
> https://wiki.servarr.com/radarr/faq#how-does-radarr-handle-foreign-movies-or-foreign-titles
> 
> there do seem to be some issues with mapping the TMDB language incorrectly in radarr as English tho...those would be languages not explicitly supported

it says it should use alt titles, but it is not
![image](https://user-images.githubusercontent.com/51322002/125376594-bb619700-e361-11eb-921c-1630a6af7cd2.png)
am i missing any configuration?

**Comment by bakerboy448** [comment]
That's for parsing not searching.

**Comment by Qstick** [comment]
Searching with all titles would completely demolish indexers, many movies have upwards of 10+ titles, many of which are bogus. Radarr currently uses translations for languages you want in addition to the original title
