### ISSUE TITLE
List movies added to exclusion list are re-added again

### ISSUE THREAD

**Issue by alculete** [Radarr/Radarr#6469]
**Describe the bug**

removed movies keep being readded through lists 

**To Reproduce**

1. Go to a downloaded movie
2. Click on delete movie and select **add list exclusion** and **delete movie folder**
![image](https://user-images.githubusercontent.com/2129497/125486646-dd5991aa-38b4-46ef-a05c-34e0064d4a4e.png)

3. After a few hours the movie is readded and downloaded again

**Expected behavior**
The movie should be added to the **exclusion list**  

**Screenshots**

**Platform Information:**
 - OS:  Ubuntu_server 20.04.2 LTS x86_64
 - Version:   4.0.0.5126
 - Package Version:   4.0.0.5126-ls103 by linuxserver.io 
 - .NET:  Yes (5.0.5)
 - Docker:   Yes
 - Branch: nightly

[AB#1261](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1261)

**Comment by ta264** [comment]
This shouldn't be happening.  Please provide proof (i.e. the logs requested in the template)

**Comment by RobinDadswell** [comment]
Trace logs?

**Comment by bakerboy448** [comment]
Any chance Ombi or a similar application is adding the movie? that was the case for a similar issue just seen

**Comment by alculete** [comment]
> Any chance Ombi or a similar application is adding the movie? that was the case for a similar issue just seen

I've just enabled trace logs. I have plex and jellyfin installed but nothing on this too servers is enabled to trigger any download. I will wait for excluded movies to e added again

**Comment by alculete** [comment]
not sure if it related but after enabling trace logs my lists are always unavailable. I will close this  ticket for now and will open when it happens again

![image](https://user-images.githubusercontent.com/2129497/125728940-e0f2e75a-e351-4853-82f8-d35e4fadffbd.png)
