### ISSUE TITLE
Title detection fails with "German" in the title (Language Parser)

### ISSUE THREAD

**Issue by inspector71** [Radarr/Radarr#6474]
**Describe the bug**

A download of `The Good German (2006)` where the folder and file names:

`The.Good.German.2006.720p.WEB-DL.AAC2.0.H264-RARBG`

`The.Good.German.2006.720p.WEB-DL.AAC2.0.H264-RARBG.mkv`

`The.Good.German.2006.720p.WEB-DL.AAC2.0.H264-RARBG.nfo`

... use dots instead of spaces, with the country name part of the title, was scanned incorrectly as containing German language content.

I wonder if this happens with `The.English.Patient` and/or `Captain.America`. If the latter only, the country name in the title may only be scanned as the language if the country name is the last word in the title.

**To Reproduce**

1. Add the above movie
2. Use `WEBDL-720p` profile
3. Search indexers for any release replacing spaces with dots in the name
4. Send to download client
5. After download completed, file(s) not processed

**Expected behavior**

Regex the movie title correctly, process the movie file(s) normally.

**Screenshots**

https://i.imgur.com/xDSrrQe.png

https://i.imgur.com/OByZBrI.png

https://i.imgur.com/1gGPrfF.png

**Platform Information (please complete the following information):**
- Windows 10
- Docker: No
- Radarr Version: 3.2.2.5080
- .NET: Yes (5.0.5)
- DB Migration: 195

**Trace Logs**

Can provide in time.

**Comment by bakerboy448** [comment]
This is also an issue for French

> For posterity If/when the log expires
> 
> `The.French.Minister.2013.720p.BluRay.x264-ROUGH [PublicHD]`
> ![74B8C24F-1911-42C3-92E3-4740BDCA0A19](https://user-images.githubusercontent.com/55419169/125077657-f6747980-e086-11eb-84ea-fca8747f1999.png)


likely is an issue for Only German and French given it seems this line is the culprit

Traced it down; seems related to this line which outputs the movie title as `The`
https://github.com/Radarr/Radarr/blob/8fd6c720374352faa7b739c5e14f96c68974ef3c/src/NzbDrone.Core/Parser/Parser.cs#L24

**Comment by inspector71** [comment]
I guess `The French Connection (1971)` may then be an interesting test case? Movie filmed in English as it is set in New York / is a US production involving two English speaking primary characters.

https://en.m.wikipedia.org/wiki/The_French_Connection_(film)

**Comment by inspector71** [comment]
Renamed issue for consistency with https://github.com/Radarr/Radarr/issues/6412

Might make searching for others clearer in future / reduce possibility of duplicate issues.

**Comment by inspector71** [comment]
Forgot I have `French Exit (2021)` (English language, US production) and **IIRC** it scanned fine. However, it was some time ago. 

https://i.imgur.com/I53fp69.png

https://i.imgur.com/0ARWL3w.png

**Comment by bakerboy448** [comment]
French is fixed https://github.com/Radarr/Radarr/commit/1cb31aa95cf9b8b6514f2dd526f7357c2cdb56e9

**Comment by jaum20** [comment]
@batuhankrmn How is this fixed? How to proceed to make it work? I just realized today that French Dispatch was no downloaded due this bug.

**Comment by bakerboy448** [comment]
> @batuhankrmn How is this fixed? How to proceed to make it work? I just realized today that French Dispatch was no downloaded due this bug.

Did you not see this comment?

https://github.com/Radarr/Radarr/issues/6474#issuecomment-998902984

**Comment by Qstick** [comment]
It's fixed on nightly, as soon as I updated mine was imported successfully. If you aren't on nightly, you don't get the love yet.
