### ISSUE TITLE
a way to auto blacklist + remove rar torrents

### ISSUE THREAD

**Issue by icf20** [Radarr/Radarr#6476]
i did some googling and i do not find a way to remove this type of crap, so can something like that ever be implemented? so when radarr try to import the file if the file ends in .rar normally radarr ask for manual import i want just to remove and blacklist 

[AB#1274](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1274)

**Comment by RobinDadswell** [comment]
Firstly can you please fill in the template properly. 

Secondly and more to the point of your issue, have a look at unpackerr as it unpacks zipped/rar'd things for this purpose

**Comment by icf20** [comment]
@RobinDadswell i dont want to unpack rar files simply i dont want to grab rar file as a matter of principle

**Comment by bakerboy448** [comment]
Get indexers that don't pack their releases. There is just about never any information in a release name that would allow radarr to know it is a packed release.

**Comment by austinwbest** [comment]
We can but it would not be straight forward at all and I don't see anyone taking it on anytime soon. Rar files are part of this life, is what it is.

**Comment by icf20** [comment]
> Get indexers that don't pack their releases

that is not really a choice, for stuff outside mainstream EN

**Comment by bakerboy448** [comment]
> that is not really a choice, for stuff outside mainstream EN

regardless this is not feasible and not happening 

> and by the way blacklisting dont work

Please use one of the support channels: [Reddit](https://www.reddit.com/r/radarr/) or  [Discord](https://radarr.video/discord) for support/questions.  It 100% does work.

**Comment by icf20** [comment]
>  It 100% does work.

Current blacklist

![image](https://user-images.githubusercontent.com/17784575/132711115-facce163-41fa-4d21-8e2d-a40681be4f76.png)

**Comment by bakerboy448** [comment]
Likely those are the same release, across different  indexers and/or with different torrent hashes.
