### ISSUE TITLE
[Bug] Mark a download as failed from history event modal is not working

### ISSUE THREAD

**Issue by n3ssi3** [Radarr/Radarr#6483]
**Describe the bug**

When you try to mark a download release as failed nothing happens.
In the inspector tool, you can see, that the request fails:
`POST :7878/api/v3/history/failed/[object%20Object]`

(Pressing on the x to mark as failed works)

**To Reproduce**

The post url should not contain an `[object%20Object]`

**Platform Information (please complete the following information):**
 - OS:  Ubuntu 20.04
 - Docker: Yes
 - .NET 5.0.5
 - Browser and Version: chrome 92.0.4515.107 
 - Radarr Version: 4.0.0.5126-ls103 by linuxserver.io
 - Radarr Branch: nightly

[AB#1289](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1289)

**Comment by bakerboy448** [comment]
From what screen in the UI?

Clicking the x in history works, correct?
What exact method is this?

**Comment by bakerboy448** [comment]
just a bump for the additional info.

**Comment by bakerboy448** [comment]
@Qstick close?  Between lack of info / lack of additional reports / and aspnetcore - is this an issue?

**Comment by n3ssi3** [comment]
Sorry I missed the last notifications:

If you open a movie and go to download history, each entry has an info icon and an X icon.
If you click on the :information_source:  a popup opens, there you have a big red button `Mark as Failed`
![Screenshot 2021-11-03 at 17 53 42](https://user-images.githubusercontent.com/694883/140111063-fc066a9c-92fb-4abb-9ca8-de08a87bc4a3.png)
Pressing this button does not do anything

----
Version 4.0.0.5332
Package Version 4.0.0.5332-ls125 by linuxserver.io
.NET Yes (5.0.10)
Docker Yes
DB Migration 197

**Comment by bakerboy448** [comment]
> Version 4.0.0.5332

you are over 100 builds out of date - update and try again, the whole API was just recently re-done

If it persists 
check the browser network console for the call being made and provide what that call and response is (note: not censored, so you may need to strip out your API key if it's in there)

**Comment by TheMeanCanEHdian** [comment]
I am seeing this same issue on version: `4.0.0.5437`

Here is the screenshot you requeste
![chrome_GQyUX9CnA2](https://user-images.githubusercontent.com/16025103/140565946-d066be66-51b5-4641-a79a-3d5d8b7c8abc.png)
d

**Comment by Qstick** [comment]
I can't reproduce this, UI sends correct Id in route on my side instead of the object. And 13c03d9958b0264bd42c8d934cbf8480a152f904 fixes the backend

**Comment by TheMeanCanEHdian** [comment]
I am still able to reproduce this on version `4.0.0.5448`. Is there other information I can help provide to solve it?

**Comment by bakerboy448** [comment]
> I am still able to reproduce this on version `4.0.0.5448`. Is there other information I can help provide to solve it?

Confirmed & Reproduced here as well `radarr/api/v3/history/failed/[object Object]` on `4.0.0.5448`

Movie => History => (i) for a grab => Click the big red Mark as Failed Button => No action occurs; Network Console shows a 405

**Comment by n3ssi3** [comment]
I just pulled the latest docker container `4.0.0.5547`
the POST request still has the `[object%20Object]` in the URL (as mentioned by @TheMeanCanEHdian and @bakerboy448)

```
Request URL: http://192.168.178.25:7878/api/v3/history/failed/[object%20Object]
Request Method: POST
Response:
{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
  "title": "One or more validation errors occurred.",
  "status": 400,
  "traceId": "00-1f7419bc638addb45ff24c47a0a08c77-e4653544da515d6a-00",
  "errors": {
    "id": [
      "The value '[object Object]' is not valid."
    ]
  }
}
```

However, now that I pulled the latest version, pressing the `x` does not work anymore either.
![Screenshot 2021-12-01 at 16 17 30](https://user-images.githubusercontent.com/694883/144261272-a05d531c-2df9-4f73-8bc9-656a920092e1.png)
 
 ```
Request URL: http://192.168.178.25:7878/api/v3/history/failed/323
Request Method: POST
Status Code: 500 Internal Server Error
{
  "message": "Operation is not valid due to the current state of the object.",
  "description": "System.InvalidOperationException: Operation is not valid due to the current state of the object.\n   at System.Text.Json.Serialization.JsonConverter\u00601.WriteNumberWithCustomHandling(Utf8JsonWriter writer, T value, JsonNumberHandling handling)\n   at System.Text.Json.Serialization.JsonConverter\u00601.TryWrite(Utf8JsonWriter writer, T\u0026 value, JsonSerializerOptions options, WriteStack\u0026 state)\n   at System.Text.Json.Serialization.JsonConverter\u00601.WriteCore(Utf8JsonWriter writer, T\u0026 value, JsonSerializerOptions options, WriteStack\u0026 state)\n   at System.Text.Json.JsonSerializer.WriteCore[TValue](JsonConverter jsonConverter, Utf8JsonWriter writer, TValue\u0026 value, JsonSerializerOptions options, WriteStack\u0026 state)\n   at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)\n   at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)\n   at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)\n   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeNextResultFilterAsync\u003Eg__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State\u0026 next, Scope\u0026 scope, Object\u0026 state, Boolean\u0026 isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()\n--- End of stack trace from previous location ---\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeFilterPipelineAsync\u003Eg__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeAsync\u003Eg__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.\u003CInvokeAsync\u003Eg__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.\u003CInvoke\u003Eg__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\n   at Radarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\\a\\1\\s\\src\\Radarr.Http\\Middleware\\BufferingMiddleware.cs:line 28\n   at Radarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\\a\\1\\s\\src\\Radarr.Http\\Middleware\\IfModifiedMiddleware.cs:line 41\n   at Radarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\\a\\1\\s\\src\\Radarr.Http\\Middleware\\CacheHeaderMiddleware.cs:line 33\n   at Radarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\\a\\1\\s\\src\\Radarr.Http\\Middleware\\UrlBaseMiddleware.cs:line 27\n   at Radarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\\a\\1\\s\\src\\Radarr.Http\\Middleware\\VersionMiddleware.cs:line 28\n   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)\n   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)\n   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.\u003CInvoke\u003Eg__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)"
}
```

**Comment by n3ssi3** [comment]
Tested, works thank you 👍

**Comment by bakerboy448** [comment]
> Movie => History => (i) for a grab => Click the big red Mark as Failed Button => No action occurs; Network Console shows a 405

Reopening; this is still occurring
