### ISSUE TITLE
[Feature Request] Additional renaming scheme/filename token: {MediaInfo.BestAudioCodec}

### ISSUE THREAD

**Issue by vp-en** [Radarr/Radarr#6488]
**Is your feature request related to a problem? Please describe.**
In some cases, when Radarr grabs a release from certain groups, they include 2 audio tracks in their mkv file. E.g. an audio track with `AC3` and one with `DTS-HD MA`. The release name will typically include the highest available audio codec, like `Test.Movie.2007.DTS-HD.MA.1080p.BluRay.x264-EXAMPLE`

This can be a little problematic with the current available scheme `{MediaInfo.AudioCodec}`.

Some release groups embeds/muxes the lowest "lossiest" audio codec **first** (usually AC3), and that's what Radarr uses for the renaming. So in their release title, it'll refer to a release as one with DTS-HD.MA, but after the renaming is done (using the `{MediaInfo.AudioCodec}`), it'll be listed as AC3.

The renaming will remove the traces of the 2nd / highest available audio codec, in this case the one with the highest bitrate, DTS-HD MA. 

This creates a weird loop, as Radarr will seek to download and try to upgrade the release over and over again, if the DTS-HD.MA score (in custom formats) is set with a higher score (as it typically will be, if you're using the [trash-guides recommendations](https://trash-guides.info/Radarr/Radarr-setup-custom-formats/#basics)).

**Describe the solution you'd like**
It would be nice with an additional renaming scheme / filename token, like `{MediaInfo.BestAudioCodec}`, that renames according to the "highest" / "best" available audio codec. This is of course a bit problematic, seeing as that can vary based on personal opinion(s).
Or, a token like `{MediaInfo.HigestBitrateAudioCodec}` that lists the highest available audio codec, based on the bitrate.
Another possible solution would be to arrange / sort the audio codecs by "quality", like (from "worst" to "best"):
AC3 -> EAC3 -> DTS -> DTS-ES -> DTS-HD MA -> TrueHD -> DTS-X / TrueHD ATMOS
Again.. That can be problematic for a lot of reasons, I know.

**Describe alternatives you've considered**
As a temporary solution, I just added all the "advanced audio codecs" to my `{Custom.Formats}` in my renaming scheme, so it'll used that if it's in the title of the release, instead of using the first available/first muxed audio codec from `{MediaInfo.AudioCodec}`.
But again, this is a temporary solution.. Since this will not always work, if you want to always include the audio codec in the renaming process / filename. Since the custom formats renaming will only apply, if it's part of the actual release name.

**Additional context**
I don't know any C# :(

[AB#1297](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1297)

**Comment by mateherber** [comment]
I've just hit the same issue downloading in loops.
