### ISSUE TITLE
Upgrade when smaller but same quality

### ISSUE THREAD

**Issue by tcheronneau** [Radarr/Radarr#6493]
**Is your feature request related to a problem? Please describe.**
With the encoding x265 getting more and more used I would love to allow upgrade of existing movie if size is smaller and same quality. 

**Describe the solution you'd like**
Allow upgrade same quality but size smaller

**Describe alternatives you've considered**
Manually search

**Additional context**
Adding the possibility to upgrade when size is smaller maybe with some threshold in order to avoir re-download if size is like 100mb less. 

[AB#1302](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1302)

**Comment by bakerboy448** [comment]
Use custom formats; no plans to change the quality ranking of the higher size

**Comment by ta264** [comment]
For the record you can prefer smaller to bigger by adjusting the quality definition - the middle blob is the preferred size, and by default it's max
