### ISSUE TITLE
[Feature Request] Sort order for root folders

### ISSUE THREAD

**Issue by PeterKse** [Radarr/Radarr#6497]
**Is your feature request related to a problem? Please describe.**

I have a few different root folders to choose from, but the sort order of these folders can't be changed

**Describe the solution you'd like**

I'd like to be able to put the most frequently used on top. Perhaps under Settings -> Media Management under the Root Folder section there could be up/down arrows adjusting the sort order of the folder list.

[AB#1312](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1312)

**Comment by bakerboy448** [comment]
Merging with #3371
