### ISSUE TITLE
Queue detecting Symlink files as Samples

### ISSUE THREAD

**Issue by texiun** [Radarr/Radarr#650]
Using Latest build, On downloading via torrent (Transmission) the files are then moved to another location and the Symlink is created.  Issue is under queue the symlink file is then being flagged as downloading "Torrent" then recognising it as a Sample due to it's size.

If it's a simple configuration issue please advise, Downloader and Radarr are all running on local machine.

**Comment by onedr0p** [comment]
How is the symlink being created? Have you thought about using hard links?
