### ISSUE TITLE
Additional Filename & Folder tokens for 'Simple Quality' identifer (ie 480, 720, 1080, etc.)

### ISSUE THREAD

**Issue by psi5asp** [Radarr/Radarr#6519]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Simply add an extra Quality token to the File and Folder movie renaming tokens that _only contains the resolution_ (without the HD/SD, etc and without the HDTV, WEBRip, etc text):

ie
**_Name_**: {Simple Qualiry} ...for both Folder and File.
**_Contains_**: 360pi, 480pi, 576pi, 720p, 1080p, 2160p, 4320p

**Describe alternatives you've considered**
There are none, other than the existing renaming options

**Additional context**
Most people don't care where the source video came from (especially for viewers) webrip, bluray, HDTV, etc.  all that matters is the actual resolution of the footage in terms of 360p, 480p, 720p, 1080p, etc... Unfortunately Radarr currently does not strip down or allow the bare min for the resolution identifier for the video file. This should be a simple matter of only using the number portion of the existing variable (regx it even).

**Comment by bakerboy448** [comment]
Names are based on the quality settings which are user editable; closing as that covers it.

Note that the quality is a property of the movie file and always recoverable.  The source is irreplaceable metadata.  Once that is lost if the movie is ever removed and readded / the file disappears and reappears. Or any other type of actions. Radarr will assume the movie is the lowest quality (HDTV) and this would always result in an upgrade.

**Comment by psi5asp** [comment]
The request was to add an addition, not the replace what's already there.

Radarr should not be setting 'standards' of jow users manage and rename their files, (Radarr do not own the servers, h/d's, files, etc.) The admins need options not restrictions based on options of know-bests.

**Comment by bakerboy448** [comment]
There's no functionality to add as you can already do this.

change the quality names in settings -> qualities to just the resolution or use one of the media info tags.

Naming is up to the user (other than movie name and year being required)  but intentionally removing irreplaceable metadata from names and not following the sane - generally universal - standards that exist does have consequences as I mentioned.

**Comment by fryfrog** [comment]
> Radarr should not be setting 'standards' of how users manage and rename their files

In this one particular case, I strongly disagree. Failure to preserve the source/quality of the file is a *frequent* support issue because once that data is *gone*, the file is considered `HDTV` or `SDTV` which slates it for upgrade in most profiles. So users that re-install and lose their database or some how have their files disappear and re-appear end up screwed by this.

Out of curiosity, why do you need *resolution* in the file name when it is literally a property of the file itself?
