### ISSUE TITLE
Indexers problem

### ISSUE THREAD

**Issue by rickytin** [Radarr/Radarr#652]
I have 9 Indexers that works in Sonarr, 4 of them don't work in Radarr.
I have enter the exact information (copy from Sonarr - paste to Radarr), what can be the problem?

Thanks

**Comment by onedr0p** [comment]
What indexers? torrent or nzb? We need more information...

**Comment by rickytin** [comment]
Nzb

**Comment by galli-leo** [comment]
@rickytin The problem here is that these indexers are not configured for movie search. You can either tell the admins of these indexers to enable that or try and add them anyways.
