### ISSUE TITLE
Unable to add Download Station after DSM 7.0 update

### ISSUE THREAD

**Issue by nieroivan** [Radarr/Radarr#6525]
Hi.

 After the update from DSM 6 to DSM 7.0 on my Synology, I'm unable to add DownloadStation on Download Client Settings.

I'm doing exactly the same configuration that I have on Sonarr, but instead of success, I'm getting those messages below:

Unknown exception: Failed to login. Reason: The requested method does not exist
Failed to get the list of torrents: Failed to login. Reason: The requested method does not exist

Anyone have faced the same message?

**Comment by bakerboy448** [comment]
DS I believe is currently only fixed on our nightly/alpha branch.

this was due to a breaking change that Synology pushed with a recent DS Version.

wait it out or switch to a proper download client
