### ISSUE TITLE
Blacklist entries not staying in list

### ISSUE THREAD

**Issue by bsod99** [Radarr/Radarr#653]
Fairly often Radarr downloads fake copies that I later remove, but I want to avoid them downloading in the future. I am not sure at what point they disappear, but at some point the episodes I blacklist are gone from the blacklist and are redownloaded if I search that movie again.

**Comment by jOOc** [comment]
Yes, blacklist does not work for me either. 

![image](https://cloud.githubusercontent.com/assets/9382342/22855641/08d2ee24-f084-11e6-95a9-27206bf82c7f.png)

**Comment by galli-leo** [comment]
I know why. Expect a fix in a few minutes.
