### ISSUE TITLE
[BUG]: Systemd on Lubuntu 21.04 wont start Radarr Service

### ISSUE THREAD

**Issue by potequity** [Radarr/Radarr#6543]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

OS: Lubuntu 21.04
Radarr version: 3.2.2.5080
SELinux is disabled.

After installing Radarr as per https://wiki.servarr.com/radarr/installation, radarr service does not start on reboot. I'm able to manually start it after the reboot.

Contents of /etc/systemd/system/radarr.service file:

[Unit]
Description=Radarr Daemon
After=syslog.target network.target
[Service]
User=radarr
Group=radarr
Type=simple

ExecStart=/opt/Radarr/Radarr -nobrowser -data /home/radarr/.config/Radarr
TimeoutStopSec=20
KillMode=process
Restart=always
[Install]
WantedBy=multi-user.target

Thanks in advance!

-PE

### Expected Behavior

Radarr service is running after reboot.

### Steps To Reproduce

OS: Lubunt 21.04
Radarr: 3.2.2.5080
Docker Install: No
Using Reverse Proxy: No

### Environment

```markdown
- OS: 
- Radarr:
- Docker Install:
- Using Reverse Proxy:
- Browser:
```

### What branch are you running?

Master

### Anything else?

No errors in either /var/log/syslog or /home/radarr/.config/Radarr/logs/radarr.txt

[AB#1420](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1420)

**Comment by RobinDadswell** [comment]
Have you run this command `sudo systemctl enable --now -q radarr` 

If you have then this is a support request so please drop by https://radarr.video/discord or https://www.reddit.com/r/radarr/ for some help

**Comment by potequity** [comment]
Why is this closed?

**Comment by potequity** [comment]
sudo systemctl enable --now -q radarr

This command only creates a symlink so systemd can start the service on reboot. I'm not sure how this would fix my issue?

**Comment by ta264** [comment]
Because most likely this isn't a Radarr bug but an issue with your setup.

Join the discord channel for support resolving it. If it does turn out to be a Radarr bug we can reopen.
