### ISSUE TITLE
[BUG]: Large number of categories (253) in a single indexer (e.g. Jackett => Hydra single entry (~/all)) fails to load

### ISSUE THREAD

**Issue by Manfred73** [Radarr/Radarr#6546]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm using Jackett for my torrent searches and NZBHydra2 to combine both torrents and newsgroups in one place.
I looked at all the torrent providers I have configured in Jackett and for movies I have around 253 categories.
From NZBHydra2 I can choose "Configure NZBHydra in Radarr v3 and that seems to work fine. It creates both a NZBHydra2 (Newznab) and NZBHydra2 (Torznab) indexer.
It seems also that the categories are filled, but when I try to view those, only two seem to have been marked. When I try to scroll down to check the rest, I get an error (see image below). When I look at the details of the error message, it says: "TypeError: t.map is not a function". This error occurs in both NZBHydra2 (Newznab) as well as NZBHydra2 (Torznab) indexer. I guess this is because there are too many categories or maybe unknown categories? Is there a limitation to the number of categories you can enter?
![error](https://user-images.githubusercontent.com/13829887/128896015-e73b4b9c-cdae-43da-9a87-13fd93cef161.jpg)

### Expected Behavior

All categories uploaded from NZBHydra2 should be visible.

### Steps To Reproduce

As described above. Enter a lot of categories in NZBHydra2 and configure Radarr v3 from there.

### Environment

```markdown
- OS: QTS Hero (Qnap)
- Radarr: v3.2.2.5080
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Chrome v92.0.4515.131
```

### What branch are you running?

Develop

### Anything else?

![Schermafbeelding 2021-08-10 181449](https://user-images.githubusercontent.com/13829887/128896999-437ed2e3-cb70-4fcf-bd58-bdf40983074d.jpg)

[AB#1428](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1428)

**Comment by bakerboy448** [comment]
https://wikijs.servarr.com/radarr/troubleshooting#logging-and-log-files

and likely the web broswer dev console spew and failed network call as well

But using Hydra as a single - not multi - entry and/or jackett's `/all`  is not recommended by anyone, explicitly advised against, and always causes issues.
https://wiki.servarr.com/radarr/faq#jacketts-all-endpoint

this would also likely cause issues when trying to search trackers that do not support one of the categories selected.

**Comment by Manfred73** [comment]
Browser dev console:
![image](https://user-images.githubusercontent.com/13829887/128902567-00e5d536-6120-473c-9574-ca59a0df9c43.png)

But as I understand, it's better to not use Jackett and NZBHydra and enter every single tor indexer and nzb indexer manually?
Do you also need to provide categories for nzb indexers?

**Comment by Manfred73** [comment]
Ah, I didn't notice that single/multiple option.
I just imported all tor from jackett into hydra so I can push them to Radarr.

(unfortunately hydra doesn't have a select all/delete checked items if you wanted to delete them again; have to delete one by one).

**Comment by Manfred73** [comment]
I think I will go for Prowlarr and skip Jackett all together. Prowlarr looks promising and a better option (at least for torrentz).

**Comment by Manfred73** [comment]
I think the problem was that I was using Jackett and NZBHydra as a single indexer and adding all the categories from all indexers in one go, but certain indexers don't know all the categories. Therefore I'm closing this issue.
Now using Prowlarr for my torrent indexers to keep them in sync and NZBHydra for some nzb indexers that I can't add in Prowlarr.
