### ISSUE TITLE
PTP does not honour "Require Golden"

### ISSUE THREAD

**Issue by SJ50** [Radarr/Radarr#655]
I have set yes to "Require Golden" but Radarr is not downloading GP it it is available. (debug log -removed-) , I even turned "Prefer Golden" but no success.

If GP is not available than it grabs available release which I do not want.

**Comment by onedr0p** [comment]
Require golden shouldn't be there, whoops... it's not implemented yet. 

https://github.com/Radarr/Radarr/issues/457

The logic to grab movies is, prefer GP, prefer scene, and then date added descending.

**Comment by onedr0p** [comment]
Interesting the following code should have GP at the top,

```csharp
return torrentInfos.OrderBy(o => ((dynamic)o).Golden ? 0 : 1).ThenBy(o => ((dynamic)o).Scene ? 0 : 1).ThenByDescending(o => ((dynamic)o).PublishDate).ToArray();
```

Maybe your quality profile is not allowing the GP to be chosen? For example if the GP is 1080p and you only want 720p it won't grab the GP.

**Comment by SJ50** [comment]
There are 3 720p release and one is GP.
If I see log it does not even considering at "ProcessDownloadDecisions" stage.
log http://pastebin.com/gU0UkSQB
![release](http://i.imgur.com/e3FlnFD.png)

**Comment by onedr0p** [comment]
Awesome I have a fix, it will be in the nightly soon.

**Comment by onedr0p** [comment]
Thanks for pointing that out, should be good now :)

**Comment by SJ50** [comment]
thanks for quick fix

**Comment by MrDemous** [comment]
Has this been fixed yet? I'm on the latest nightly (0.2.0.358) and Radarr is still grabbing any torrent that meets the quality profile even if it's not golden.

**Comment by onedr0p** [comment]
Hmm.. it is. Works here... Try re saving the PTP indexer settings.

**Comment by MrDemous** [comment]
I did. I tried enabling only require golden and turning off require approved and still it didn't work, I even tried deleting the indexer and re-adding it but it still doesn't work. It just grabs whatever release is available if a golden popcorn torrent is not available. 

Don't know what else I can try to get it to work.

**Comment by onedr0p** [comment]
I'll take a look when I have time.

**Comment by MrDemous** [comment]
Great, thanks onedr0p.

**Comment by onedr0p** [comment]
I wanted to ask are you on the latest nightly? The fix wasn't in the pre-release.

**Comment by MrDemous** [comment]
Yes I am. Ver. 0.2.0.358

**Comment by onedr0p** [comment]
I want to point out that RSS Sync will only Require Golden torrents, can you confirm a movie was grabbed via RSS sync what wasn't golden? When manually searching for a release it will show both. Make sure you have both require and prefer golden enabled.

**Comment by MrDemous** [comment]
OK, I tested with RSS Sync and it's only grabbing golden torrents but if I search for a movie manually it just grabs whatever release is available.

Is this normal behavior for Radarr? Shouldn't it grab golden torrents only even if I search for a movie manually?

**Comment by onedr0p** [comment]
This is normal behavior. If you choose prefer gold, it should prefer it over other releases. 

I want to make sure people can still manually search for not-golden popcorn torrents because of Screeners and Web-DLs, otherwise you will need to keep toggling the setting on and off when looking for a non GP torrent.

**Comment by MrDemous** [comment]
I see. But I think normal behavior for "Require Golden" should allow Radarr to only download golden torrents automatically and if I want any other release that isn't a golden torrent I'll just go to the movie's page and search for and download whichever release I want manually from Radarr.

Anyway thanks for your help onedr0p.

**Comment by onedr0p** [comment]
Currently as it stands in the code there is no way to differentiate searching manually on the search tab or searching automatically via the search button. This is a bigger issue then just PTP and affects all indexers the same way.
