### ISSUE TITLE
[FEAT]: Notify when a release is seen on a tracker (Manual Downloads)

### ISSUE THREAD

**Issue by moi15moi** [Radarr/Radarr#6550]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

My goal is to receive a notification when Radarr notices that the movie is available on x tracker.
So, it must not automatically download.

Why you would need this feature?
If you like to manually download because you have a lot of criteria and it is basically impossible to configure a profile that meet your requirements.

### Describe the solution you'd like

When you add a movie, there would be a check box call _Manually Download_.

If you check it, you will receive a notification when radarr notices that X movies is available.
If you do not check it, it will work like it is now.

### Describe alternatives you've considered

Sorry, I do not have any alternatives.

### Anything else?

Thank you very much

[AB#1443](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1443)

**Comment by ta264** [comment]
I don't think we have any interest in adding this, but lets see what the rest of the team think

**Comment by austinwbest** [comment]
> I don't think we have any interest in adding this, but lets see what the rest of the team think

I think this falls in line with another request about a trigger for available content

**Comment by Qstick** [comment]
> I don't think we have any interest in adding this, but lets see what the rest of the team think

Agree
