### ISSUE TITLE
[FEAT]: Supply framework-dependent .NET Core builds

### ISSUE THREAD

**Issue by winterqt** [Radarr/Radarr#6551]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I package Radarr for NixOS as apart of [kaidame](https://github.com/winterqt/kaidame), and I currently patch the `x86_64-linux` binaries provided to work on NixOS.

However, x86_64 is not the only architecture that NixOS runs on, and Linux is not the only OS that the Nix package manager supports. The easiest way for me to package these is to do so via .NET Cores framework-dependent binary support, as then I only need to supply the .NET Core runtime and the dynamically loaded libraries such as SQLite and libmediainfo.

### Describe the solution you'd like

For [framework-dependent builds](https://docs.microsoft.com/en-us/dotnet/core/deploying/#publish-framework-dependent) to be provided alongside the other binaries.

### Describe alternatives you've considered

- Creating logic for all of the different supported platforms in my packaging
    - This is possible with not much effort, but using framework-dependent builds provides much less friction in the packaging process (and provides other benefits, that the Microsoft page linked above mentions)

### Anything else?

n/a

[AB#1445](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1445)

**Comment by ta264** [comment]
I don't think this is something we want to do. Providing standalone builds lets us control which framework version is used.

**Comment by Qstick** [comment]
> I don't think this is something we want to do. Providing standalone builds lets us control which framework version is used.

Agree

**Comment by winterqt** [comment]
How much does the exact framework version matter in terms of stability / bugs / whatever? For example, are there things that would become unstable or break if I use a different .NET minor / micro version to run Radarr?

I ask because these framework dependent builds are dependent on the major / minor version that the application was built with, or a higher **minor** version, but never a lower one.

See https://docs.microsoft.com/en-us/dotnet/core/versions/selection#framework-dependent-apps-roll-forward for more details.

Either way, thanks for considering this request, I appreciate it.
