### ISSUE TITLE
[BUG]: RemoteIP address is that of reverse proxy and not external IP address like in Sonarr

### ISSUE THREAD

**Issue by FuzzyMistborn** [Radarr/Radarr#6552]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm trying to set up Fail2ban for Radarr and running into an issue where the IP address listed in the logs is that of my reverse proxy and NOT the actual external IP address I want to ban.  Sonarr has the right IP address in the log.  Cross-comparing code, I think I see the issue:

**Sonarr**: https://github.com/Sonarr/Sonarr/blob/20306a38e1d0f6a7954978cf07cde8e185f79c78/src/Sonarr.Http/Extensions/RequestExtensions.cs#L90-L133

**Radarr**: https://github.com/Radarr/Radarr/blob/8d1a9f98afa0b8ad74b3be4507d8f3158840c910/src/Radarr.Http/Extensions/RequestExtensions.cs#L90-L146

I don't know what the extra 13 lines of code in Radarr do but it causes this difference:

**Sonarr**: Warn|Auth|Auth-Failure ip ACTUAL_EXTERNAL_IP username 'test'Warn|Auth|Auth-Failure ip 108.11.247.107 username 'test'
**Radarr**: Warn|Auth|Auth-Failure ip ::ffff:REVERSE_PROXY_INTERNAL_IP username 'test'Warn|Auth|Auth-Failure ip ::ffff:192.168.50.10 username 'test'

Perhaps it's because Radarr is adding the IPv6 address, but the result is that the wrong IP address would get banned with fail2ban.

### Expected Behavior

The correct IP address is shown in the log when used with a reverse proxy, similar to what I see in Sonarr.

### Steps To Reproduce

See above information in Current Behavior.  I can provide more details if necessary.

### Environment

```markdown
- OS: Ubuntu 20.04
- Radarr: 3.2.2.5080
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Not UI related
```

### What branch are you running?

Master

### Anything else?

Nothing, though again happy to provide any information that might be relevant/useful.

[AB#1446](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1446)

**Comment by bakerboy448** [comment]
Already fixed in nightly https://github.com/Radarr/Radarr/commit/6f0d5a0583593f4ffe82f6029b609b1bbf622f83

**Comment by FuzzyMistborn** [comment]
Ahh thank you, guess this just missed the cutoff for the last stable.  I'll switch to nightly.

**Comment by bakerboy448** [comment]
> Ahh thank you, guess this just missed the cutoff for the last stable. I'll switch to nightly.

Just so you know what you're getting into.

> nightly - Current Nightly/Unstable - (Alpha/Unstable) : The bleeding edge. Released as soon as code is committed and passed all automated tests. Use this branch only if you know what you are doing and are willing to get your hands dirty to recover a failed update. This is currently v4. This version is updated immediately.
> Warning: You may not be able to go back to master after switching to this branch. On GitHub, this is the develop branch.

And currently that warning is true; you cannot go back to master nor develop from nightly at this time.

https://wiki.servarr.com/radarr/faq#how-do-i-update-radarr

**Comment by FuzzyMistborn** [comment]
I'll just wait then it's not that urgent hahaha.  Any idea when the next stable will be released?

**Comment by bakerboy448** [comment]
given the current v4 changes and further anticipated changes....it'll be a decent while.
