### ISSUE TITLE
[BUG]: Radarr misses out Country code in Certification in NFO files

### ISSUE THREAD

**Issue by cooljimy84** [Radarr/Radarr#6556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Radarr writes out Certification Country U or PG or 18 to the NFO file

### Expected Behavior

Radarr to write out GB-U or GB-PG or GB-18 to the NFO file
as Certification Country is set to Great Britain

### Steps To Reproduce

Downloading a new movie.
In settings metadata i have Kodi (XBMC) / Emby Metadata enabled with the following options
Enable
Movie Metadata
Movie Metadata URL
Metadata Language English
Movie Images

I also have Certification Country set to Great Britain.

### Environment

```markdown
- OS: Ubuntu 18.04.5 LTS
- Radarr: Version
    3.2.2.5080
.NET
    Yes (5.0.5)
DB Migration
    195
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Firefox
```

### What branch are you running?

Master

### Anything else?

.

[AB#1459](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1459)

**Comment by Qstick** [comment]
Have a kodi doc reference that it expects country code?

**Comment by cooljimy84** [comment]
I can't find anythinig
But then I'm using filtered view from Jellyfin (which works with emby metadata) for age restriction for my child. Kodi shows all shows (but is only on when we are watching TV) Jellyfin is on all the time.

**Comment by cooljimy84** [comment]
I should have included an example.
So https://www.themoviedb.org/movie/218-the-terminator
shows " The Terminator (1984) 15 11/01/1985 (GB)" So the age certification is 15, the location of the age certification is GB
but when Radarr writes out the metadata with the above settings (in the ticket), it sets it as 15. not GB-15

To confirm if you goto https://www.imdb.com/title/tt0088247/parentalguide then a little bit down the page you can see in 2000 it was reclassified to 15, and if you hover over the link, it says GB:15

**Comment by Qstick** [comment]
Right thanks, but to ensure we fix it properly we need some idea of exactly what is expected by emby/jellyfin

**Comment by cooljimy84** [comment]
Kool, I'll see if I can find docs or the code that it expects in the field.
