### ISSUE TITLE
[FEAT]: Postprocessing being able to deactivate or scheduled

### ISSUE THREAD

**Issue by elpedriyo** [Radarr/Radarr#6563]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I have radarr to move my movies from the dedicated seeding disk to the movie pool disks. Once a download is completed Radarr start moving the file, and hitting 100% my destination pool media disks. This can have some impact on the performance of the pool, if it is in use for other stuff

### Describe the solution you'd like

I would like to schedule the postprocessing activity at night, when all my disk pool is mostly inactive, for all downloads completed during the day, are then moved, without causing any impact.

### Describe alternatives you've considered

Stopping Radarr, and relaunching it again at night. But this ends up with myself not being able to use Radarr durin the day.
Tagging the Radarr tag out from the torrent tracker, though this will end up with order issues I was told on discord

### Anything else?

N/A

[AB#1493](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1493)

**Comment by ta264** [comment]
I don't think we have any desire to do this but will let other members of the team comment before closing.

**Comment by elpedriyo** [comment]
At least an API call to to start/stop the postprocessor and continue using Radarr :(

**Comment by ta264** [comment]
Very unlikely

**Comment by bakerboy448** [comment]
I don't think it'd make sense to add a 0.1% feature.

Seems like this would best be handled in the script that post processing calls.  The script should handle its own queueing and delays. 

Just my $0.02

**Comment by austinwbest** [comment]
> Very unlikely

I answered this on discord yesterday as well. No plans (it has come up one other time and that was the response)

**Comment by klepp0906** [comment]
Let me +1 this as it sounds like what im trying to accomplish.   This can not be a fringe issue in any way.   Most, dare i say ALL of us are using spinners for our media.

I download and unpack to an SSD but upon moving to my spinner, it smashes my io and for anyone who happens to be playing something on my plex server, in comes the phone calls. 

I've resigned to having to get up in the middle of the night and change "check for finished downloads interval" to 24 hours and then remember to re-do the aforementioned if things restart for any other reason/at any other time.

otherwise theres no way to run a plex server when your media is going to the same drive(s) as you are at risk of this happening. 

the easiest solution I can imagine (with close to zero programming knowledge) would be to simply expand on the "Check for finished downloads interval" to use either an interval, or a specific time as the setting.   

That has to be easy to implement in the grand scheme of things right?

**Comment by austinwbest** [comment]
The feeling hasn't changed. Maybe flip the add state from start to paused.. then start all the paused ones nightly or something and they can download/move during the night. About the only "quick" fix i can think of to help with that.

**Comment by klepp0906** [comment]
Ah, I assumed adding a box for time and checking against the windows clock would be almost a copy past job lol.  The switching from paused to go (assume you mean within radarr) would require me to be up in the middle of the night to do so.  

I honestly don’t get is how this is not one of the most posted about issues lol.  I guess if you only fetch stuff manually with radarr or have upgrades come through incredibly rarely you could just deal. 

Would a donation Ala bountysource or something spur a dev to implement it you think?

**Comment by ta264** [comment]
I've never had any issues playing back from a spinning disk while something is being imported or downloaded to the same disk.  So I think the reason it's not the most posted about is it's just not an issue for most people.

Have you actually observed an impact?

If it does actually cause issues in your setup have you tried tweaking ionice values for plex / download client / radarr to alleviate them?

I think you're going to struggle to convince us this is an issue for more than a handful of users.

**Comment by klepp0906** [comment]
I mean I’m just a layman so please don’t take offense.  I’m not trying to be snooty nor condescending and I could be entirely missing something integral.  

That being said, how could it not?  (Be an issue)

I have high end spinners.  7200rpm barracuda pros and I can watch radarr like clock work peg them to 100%

short of being able to limit the write speed to the media disk I don’t know how I could limit it and leave a bit of meat on the bone for reading for a simultaneous plex user or two. 

I am on windows, ionice is like a Linux or max thing isn’t it?

I did limit my bandwidth on both sabnzbd and BitTorrent to leave a healthy 40% of my gig line free up and down.  Still this would have no bearing on the finished downloads transfer to said disk.  Pretty sure windows just sends it as fast as the drive will accommodate. 

The one point you made that is a fair point that I’m ashamed to say is no, outside of the numbers via perfmon ui haven’t tested as I’m just now getting radarr set up for the long haul. 

Perhaps windows has some kind of scheduler that will give plex what it needs io wise.  Once I get home it’s the first thing I’ll test. 

Won’t hold my breath as someone on Reddit posted saying they had to script some janky workaround to solve the issue but we shall see. 

Normally I’d just say more options are rarely a bad thing but free/open source I don’t have too much of a leg to stand on lol.

**Comment by austinwbest** [comment]
> Ah, I assumed adding a box for time and checking against the windows clock would be almost a copy past job lol.  The switching from paused to go (assume you mean within radarr) would require me to be up in the middle of the night to do so.  
> 
> I honestly don’t get is how this is not one of the most posted about issues lol.  I guess if you only fetch stuff manually with radarr or have upgrades come through incredibly rarely you could just deal. 
> 
> Would a donation Ala bountysource or something spur a dev to implement it you think? 
> 
> im sure the priorities list and bug fixes list is ever growing but if it’s something relatively easy programmatically I’d toss some money at it to empower users to have a bit more control over impact on themselves and the people they serve. 
> 
> Either way, gods work gentlemen.  Gods work. 

You don't have to do anything manually. Set and leave it on add paused. Make a simple script that connects to the qbt api and flips all paused to start then can that script every day at 1am for example. That will start the days grabs and the next day will start building up :)

Should be a pretty simple one & gets you some kind of download control now

**Comment by klepp0906** [comment]
Only problem is it’s not the download it’s the import.   I guess if all those hypothetical paused downloads finished and imported during the night.  All the same.  That’s also reasonable as I use private trackers and I’m on fiber. 

That just leaves sabnzbd. How would you implement something familiar there? Is there a way to queue downloads in Sab but not start them?

I see it has a scheduler for pause/resume but would radarr still queue items in sab when it’s in a paused state?  Or after it releases itself from pause at a predetermined time?

I just don’t want to miss out on stuff coming across rss. 

(Even though you could still argue delaying the download could still cost you due to dmca as opposed to delaying import)

**Comment by klepp0906** [comment]
> > Ah, I assumed adding a box for time and checking against the windows clock would be almost a copy past job lol.  The switching from paused to go (assume you mean within radarr) would require me to be up in the middle of the night to do so.
> > I honestly don’t get is how this is not one of the most posted about issues lol.  I guess if you only fetch stuff manually with radarr or have upgrades come through incredibly rarely you could just deal.
> > Would a donation Ala bountysource or something spur a dev to implement it you think?
> > im sure the priorities list and bug fixes list is ever growing but if it’s something relatively easy programmatically I’d toss some money at it to empower users to have a bit more control over impact on themselves and the people they serve.
> > Either way, gods work gentlemen.  Gods work.
> 
> You don't have to do anything manually. Set and leave it on add paused. Make a simple script that connects to the qbt api and flips all paused to start then can run that script every day at 1am for example. That will start the days grabs and the next day will start building up :)
> 
> Should be a pretty simple one & gets you some kind of download control now..
> 
> As for a bounty, ta is a dev who doesn't really agree with it as am i. That leaves Q and Robin. Robin won't do it unless Q is OK with it either so really it needs a blessing from Q first lol

Lol I mean are you guys against it purely from a spare time/good use of time standpoint or is it something else?  Just curious.  Your reasons are your own and are entirely valid regardless.   Just back to the whole empowering the use thing and in the name of covering bases.  Especially for those without dedicated servers it’s nice to have as much control as possible to limit intrusion. 

(Usenet already murders my kvm but that’s a concession I’ll accept lol)

**Comment by ta264** [comment]
Why would you expect windows to use anything less than 100% available disk i/o when there's no contention?  Test it out with simultaneous import and playback and let us know.

I don't think your setup is that unusual.  If it caused an issue I think we'd be flooded with complaints :)

On principle, we like to avoid options.  It just gives users more scope to cause themselves problems.  That, and the fact that this option is something very few people want.

**Comment by klepp0906** [comment]
Two sides of the same coin I suppose.  But you’re un arguably right about one thing.  I should have tested.  I will and report back and hopefully you are in fact right.  The logic is sound. 

Perhaps the guy posting here and the guys on Reddit have something else going on.  

I’ll let ya know within the next couple hours.  Then I’ll donate what I was going to bounty source for giving you guys a hard time if that’s the case lol.

**Comment by klepp0906** [comment]
well everyone gets to feel stupid once in awhile.  its what i get for assumptions.

ive had radarr, qbittorrent, sabnzbd all pegged to the hilt using 800-900 of my gigabit line and unpacking/shuttling movies to my drive as fast as it can get it done.

so far its an hour into a movie i started for my kids.  (went with a movie as opposed to animated in an attempt to pump the bitrate) with not so much as a hiccup.

I think the only concern i have left is it having something to do with the fact its being direct played as opposed to a scenario where it has to transcode but i doubt it.  i know at least at home it will always be direct play anyhow. 

this is me, with my tail between my legs.

**Comment by ta264** [comment]
Kudos for owning up to it 👍 

It's possible you might have an issue streaming multiple 4k or something, but I think it's unlikely.

**Comment by Asher9971** [comment]
I also appreciate this feature because if you're using a cloud drive as storage like me, with 20mbit upload, i'd like to stop import when someone is streaming remote

**Comment by bakerboy448** [comment]
No near term plans for this. Users can likely accomplish this with the import via custom script functionality and have the script handle the use cases
