### ISSUE TITLE
Exclude existing movies from the list when Import Existing Movies on Disk

### ISSUE THREAD

**Issue by shocker2** [Radarr/Radarr#659]
Hello,
  I've seen that this awesome feature has been added but somehow for me is not working.
  When I scan my disk to import movies via Movies -> Add Movie -> Import Existing Movies on Disk and select to see only the movies that are not already in the database is not properly working.
  It will be nice to have this implemented as it's help when you are scanning for new movies added from Couch as currently I'm only beta testing the Radarr.

Thanks!

**Comment by shocker2** [comment]
I have updated to v0.2.0.299 and now the button to exclude movies is missing.

**Comment by onedr0p** [comment]
We removed that switch, By default you do not see movies you already have in your radarr library.

**Comment by shocker2** [comment]
Indeed new most of the movies are hidden but not all of them. I can still see movies that are on my library.

**Screenshot:**
https://gyazo.com/891f006d7643b507bc1b73d4456232de

**Comment by onedr0p** [comment]
Do those movies exist on disk? Or just a empty folder?

**Comment by shocker2** [comment]
I've checked for two of them, and the movie exist.
The path is like: /path/to/movies/The.Movie.Year.1080p.WEB-DL.DD5.1.H264-RLS/The.Movie.Year.1080p.WEB-DL.DD5.1.H264-RLS.mp4

**Also it's not an empty file:**
# du -hs /path/to/movies/The.Movie.Year.1080p.WEB-DL.DD5.1.H264-RLS/The.Movie.Year.1080p.WEB-DL.DD5.1.H264-RLS.mp4
3.7G    The.Movie.Year.1080p.WEB-DL.DD5.1.H264-RLS.mp4

**Comment by fedoranimus** [comment]
I can take a look at this tonight.

**Comment by shocker2** [comment]
Let me know if you need more details in order to reproduce this.

**Comment by fedoranimus** [comment]
After further investigation, this seems to appear when you're trying to import a movie that already exists in another root folder that has already been imported. Could you verify if this is what you're seeing @shocker2 ?

**Comment by galli-leo** [comment]
Closing this as this way of importing is depreciated.
