### ISSUE TITLE
[BUG]: Radarr search ignores ' symbol

### ISSUE THREAD

**Issue by Mrpink200** [Radarr/Radarr#6590]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After months wondering why radarr was not able to catch some movies - especially french ones - on ygg, i finally found the issue.
When setting radarr to use YGG (and probably other indexer sets on Jackett", radarr ignore the symbol ' in the movie name
For example : 
I search the movie "Mort d'un pourri" , movie released in 1977 on ygg using jackett
Radarr finds no release (below is the english name of the movie)

![image](https://user-images.githubusercontent.com/7417251/132653476-44b106c1-8806-46c3-8317-e076bae0e4ae.png)

When i do the same on ygg i found plenty

![image](https://user-images.githubusercontent.com/7417251/132653337-4f0bf40e-4f11-4777-9396-ad7c7839fca7.png)

When i take a look at Jackett, i think i got the reason : 

![image](https://user-images.githubusercontent.com/7417251/132653816-54db3f99-2703-46b2-907a-cc1d4e12f5c3.png)

the movie is only released on the trackers i use under it's original movie name in french and in the name searched by radarr "d'un" becomes "dun"

My technical competencies are low and i cannot troubleshoot any further to explain at what step of the search request the bug appears and even if it can be solved ... but if it does it would allow to grab a lot of releases excluded for multiple movies.

### Expected Behavior

to have radarr request jacket to search "mort d'un pourri" as the movie name is .... and NOT "mort dun pourri"

### Steps To Reproduce

detailed in the current behavior section

### Environment

```markdown
- OS: Synology
- Radarr: 4.0.0.5241-ls118 by linuxserver.io
- Docker Install: Docker
- Using Reverse Proxy: No
- Browser: Firefox (but not relative to uissue)
```

### What branch are you running?

Nightly

### Anything else?

[radarr.trace.txt](https://github.com/Radarr/Radarr/files/7135062/radarr.trace.txt)

[AB#1570](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1570)

**Comment by ta264** [comment]
Duplicate #4502
