### ISSUE TITLE
[FEAT]: Option to block "Multi-Language" from being pulled

### ISSUE THREAD

**Issue by cryptominerau** [Radarr/Radarr#6592]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Radarr can auto detect if the file is single or multi-language when it searches, can a setting be added to block Radarr pulling "multi-language" files. Currently the only way this seems to be possible is by adding custom formats, but then you need to add each type of language, being able to specify to Radarr to only grab "English" rather than "Multi-Language" where English is one of them would be perfect. While i have Radarr set to English as the only release language it seems to keep grabbing Multi Language files, which seem to default to non English audio track. 

### Describe the solution you'd like

A option to only grab single language files, or to exclude "multi-Language" files

### Describe alternatives you've considered

Custom Formats, however this can be laborious as you need to add each language and combination. 

### Anything else?

n/a

[AB#1573](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1573)

**Comment by bakerboy448** [comment]
Guessing these are multiple languages in the release name that also do not contain "multi" ?

got a few examples for reference?

**Comment by cryptominerau** [comment]
that is correct, 

*movie name* ITA-ENG Ac3 5.1 WebRip 1080p H264 [ArMor] - Radarr under the language section will pick this up as "multi-language" however as the title does not contain Multi, it needs a ITA.ENG custom to remove it from being grabbed, then on another movie, it might grab a different language and ENG, so that again requires another custom format. So being able to just tell Radarr when it detects that the file is "Multi-Language" to ignore it would be amazing. Can post some IMGR links if you want more examples / me to be more specific if im not making myself 100% clear.

**Comment by bakerboy448** [comment]
Custom format that may work, assuming the releases are in the format of `{3 Letter Code}-ENG`

`\b\w{3}-ENG\b`

or something along those lines with some more robust regex

**Comment by cryptominerau** [comment]
would i need to add another one for things like HIND / HINDI, so a 4 or 5 rather than 3? 

Getting this added as a feature would be way more accurate, given Radarr is already detecting the Multi-Language aspect of files. at least that's my thought with it.

**Comment by ta264** [comment]
The much easier solution from our point of view is to configure your player to default to the English audio track if available :D I know you can do that with Kodi for example, I'd be surprised if you can't in others.

You could also try a custom format using the actual language options instead of trying to guess at all the permutations possible in the release title

**Comment by cryptominerau** [comment]
Some players do allow setting a default language for audio (plex, kodi etc) but some don't (some PC based players, for instance i cant find this option in the MPC i have). 

I thought rather than having to work out a custom format that would work for it, given Radarr already picks up they're multi audio when its searching before adding them, it would be somewhat easier to allow a setting to say to ignore results it has detected as being multi-language (see attached image)
![Multi Langauge](https://user-images.githubusercontent.com/72789552/132805287-1809ea42-aea8-40f9-ae1a-4fbb91ac6d5c.JPG)
