### ISSUE TITLE
[BUG]: "Remove completed" missing from qBittorrent connection settings.

### ISSUE THREAD

**Issue by peturgq** [Radarr/Radarr#6594]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1. Navigate to settings -> Download clients
2. See no setting to delete completed downloads

Resulting in the user not having a way to remove the completed file pre-rename.

![radarr_1](https://user-images.githubusercontent.com/15036579/132949294-31f4398a-f97c-4470-bd5a-3c67b8cb85de.png)

![radarr_2](https://user-images.githubusercontent.com/15036579/132949301-b34aaa73-90b0-4385-830e-e37f22c486a5.png)

### Expected Behavior

Find a checkbox to enable automatic removal of completed downloads like in Sonarr.

![sonarr_1](https://user-images.githubusercontent.com/15036579/132949317-77c72242-66cf-4235-9b47-db6d208fca00.png)

### Steps To Reproduce

1. In Docker container https://registry.hub.docker.com/layers/linuxserver/radarr/version-3.2.2.5080/images/sha256-d31a8ba68c887cb9a2fd3e7f9dbe1b100f822251ff0b1a4c5787fc0464d2e5e4?context=explore
2. Add qbittorrent connection
3. Notice no way to automatically remove completed movies.

### Environment

```markdown
- OS: 
- Radarr:
- Docker Install:
- Using Reverse Proxy:
- Browser:
```

### What branch are you running?

Master

### Anything else?

Nothing relevant in logs.

[AB#1575](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1575)

**Comment by ta264** [comment]
Enable advanced settings

**Comment by ta264** [comment]
And its global in radarr, not per download client
