### ISSUE TITLE
Update Profiles to be movie-centric

### ISSUE THREAD

**Issue by fedoranimus** [Radarr/Radarr#66]
Things like "HDTV" don't exist in movie downloads.

**Comment by aaearon** [comment]
I do not necessarily agree re: "HDTV" doesn't exist in movie downloads. A quick search for 'hdtv' in movies on an indexer would agree. From what I understand the "HDTV" designates the source and it is not necessarily too uncommon for movies to be captured from an HDTV source.

**Comment by fedoranimus** [comment]
Does anyone have any suggestions for what some movie-centric qualities would be?

**Comment by galli-leo** [comment]
CAM, HDCAM, Telesync, Telecine, DVDScreener

**Comment by weirdcrap** [comment]
I feel like CouchPotato has a fairly comprehensive list. I tossed WEB-DL into the mix because I personally don't like how CouchPotato bundles them in with BR-Rips.

2160p, BR-Disk, 1080p Bluray, Bluray 720p, WEB-DL, BR-Rip, DVD-R, DVD-Rip, Screener, R5, TeleCine, TeleSync, Cam

**Comment by thezoggy** [comment]
its resolution.source.codec
you logically group by resolution then source...  

for tv.. aired (sdtv/hdtv), web (web/web-dl/webrip), retail/media (bluray/dvdr)

for movies there are a bit more to it because of how many 'sources'..  then lots of people care more about audio which then brings into the whole concept of 1:1 rips.. 

plenty of info about release formats:
https://en.wikipedia.org/wiki/Pirated_movie_release_types

**Comment by Crowley007** [comment]
I added this as a feature request, but "remux" should definitely be a selectable quality.  After all, it is the highest quality you can get, but still in a mkv container. It's also widely used.

**Comment by thezoggy** [comment]
`remux` just means taking the audio+video from one container and putting it into another.. 
the 'best' quality is the 1:1 `BLURAY` aka ~COMPLETE` rips

**Comment by Crowley007** [comment]
Like I said, best that it is in a mkv container that is easily played by anything. The video and audio for the movie part is untouched here as well, but of of course it's missing the extras and usually some language and lower quality audio options.

 Of course, Complete would be a pretty good candidate as separate a quality setting too.

**Comment by thezoggy** [comment]
your now talking about p2p vs scene 'best quality'

**Comment by Crowley007** [comment]
I'm still talking about the best **MKV** release of a given movie, and remux is 1:1 for the movie part.

**Comment by cwrunks** [comment]
I sincerely hope there will be specific profiles for HJ-style 480p/576p encodes! Is this on your radar? (Pun intended)
