### ISSUE TITLE
Option to not link/move completed movies?

### ISSUE THREAD

**Issue by fent** [Radarr/Radarr#660]
I have the "Rename Movies" option set to no

![screen shot 2017-02-08 at 7 28 05 am](https://cloud.githubusercontent.com/assets/933490/22737234/3abeabdc-edd0-11e6-8058-b8cde546a2a1.png)

And my download directory in my client is the same as my movie folder. So when a movie was downloaded and finished, Radarr created a hardlink for it on the same folder

    /volume1/Download/Movies/Example.2016.1080p.BluRay.x264.DTS.mkv`
    /volume1/Download/Movies/Example (2016)/Example.2016.1080p.BluRay.x264.DTS.mkv

Is there a way to disable this?
Am I using these options in a non-intended way and should I keep my download directory different from my movies library directory?

**Comment by onedr0p** [comment]
I for one would keep it separate, you cannot have a flat folder of movie files. Radarr doesn't like that.
