### ISSUE TITLE
[FEAT]: Table view Request a column that allows you to add the language of the file and have it sortable

### ISSUE THREAD

**Issue by firebf00** [Radarr/Radarr#6601]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Just seems like that can help some user

### Describe the solution you'd like

Just add file language column and have it sortable

### Describe alternatives you've considered

na

### Anything else?

na

[AB#1605](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1605)

**Comment by ta264** [comment]
We have no plans to add file based properties to the movies view.  It will cause problems when we add support for keeping multiple copies of a movie.
