### ISSUE TITLE
Unable to parse bluray folder structure

### ISSUE THREAD

**Issue by Amelsfort** [Radarr/Radarr#661]
Radarr recently download a full bluray movie (which I prefer), but is unable to parse the files.
The movie is downloaded to the folder E:\Downloads\complete\Movies\<title>.1080p.BluRay.AVC.TrueHD.7.1.Atmos.

It looks like the ParsingService is scanning the folder for subfolders or files and tries to parse them. The error I see in the logs is: Unable to parse movie info from path E:\Downloads\complete\Movies\<title>.1080p.BluRay.AVC.TrueHD.7.1.Atmos\BDMV\STREAM\01076.m2ts

This error occurs for every files in the stream-folder and keeps showing up in the logs. Also, the movie is not being processed and moved.

**Comment by onedr0p** [comment]
Maybe delete `\BDMV\STREAM\01076.m2ts` or if that is the movie file move it to E:\Downloads\complete\Movies\<movie-title>\<movie-name>.m2ts

Radarr expects each movie to have 1 file, which is the movie.

**Comment by Amelsfort** [comment]
But that is not the case for bluray folders. They have a lot of different files and it's a very common format to download (and for me the reason to switch to Radarr instead of Couchpotato). It should be possible to recognise a bluray folder since it has specific folders inside (bdmv, certificate). In that case the folder name should be used to check the movie.

**Comment by onedr0p** [comment]
This would be a feature request, as we do not handle Bluray folders or DVD folders.

http://feathub.com/Radarr/Radarr

**Comment by NelCapeTown** [comment]
I completely agree that it would be nice if Radarr could handle Bluray folders, since more and more UHD media seems to be in this format.
