### ISSUE TITLE
[FEAT]: Add "Custom Format Score" as a Custom Filter property in Manual Search Results

### ISSUE THREAD

**Issue by millercentral** [Radarr/Radarr#6616]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Not blocking, but it would be nice to be able to filter search results to only show those above a certain custom format score

### Describe the solution you'd like

I rely heavily on custom format scores for finding the best option for a given movie. When using interactive search on a movie page, Radarr allows custom filters of the results, but doesn't allow "Custom Format Score" as an option. It would be great if that could be a property used to create a custom search result filter, with the filter operands being "equal or greater", "less than" and I guess for completeness, "is" and a numerical value as the attribute. I would use this as a default filter for interactive search results if available.

### Describe alternatives you've considered

The only alternative I can think of is sorting by Custom Format Score (which is supported), but not as useful, as that can't be included with other properties like custom filters can.

### Anything else?

Thanks for considering!

[AB#1649](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1649)

**Comment by bakerboy448** [comment]
Closing - similar to various other feature requests (and likely duplicated by then)

no plans for filters based on file properties
