### ISSUE TITLE
Conflict between Radarr and Sonarr

### ISSUE THREAD

**Issue by newkind** [Radarr/Radarr#663]
Hey,

The issue I'm having is on my Synology NAS with latest DSM 6. It is impossible for me now to have both Radarr and Sonarr running at the same time. Depending on which started first - this is the one I can access.

If I'll start Radarr first - I can't access Sonarr. If i'll stop both, then start firstly Sonarr and after that Radarr, I can access the first one, but not the second one (connection refused).

I'm not sure but there might be some conflict between those two.

**Comment by onedr0p** [comment]
This is a problem with the Synology package, please seek help form the package maintainer or the Synology community. Thanks.
