### ISSUE TITLE
[BUG]: Settings>Lists>Add New>More Info Button is linking to a dead wiki page. 

### ISSUE THREAD

**Issue by flyingwolf79** [Radarr/Radarr#6632]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Settings>Lists>Add New>More Info button links to a dead page on the wiki.

Example.

https://wiki.servarr.com/radarr/supported-couchpotatoimport

### Expected Behavior

To link to a live page with more info. 

The current live wiki page on settings is located here. 

Settings are now located here: https://wiki.servarr.com/radarr/settings 

### Steps To Reproduce

Settings>Lists>Add New>More Info

### Environment

```markdown
- OS: Windows
- Radarr: 3.2.2.5080
- Docker Install: No
- Using Reverse Proxy: No.
```

### What branch are you running?

Master

### Anything else?

N/A

[AB#1703](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1703)

**Comment by bakerboy448** [comment]
fixed in nightly https://github.com/Radarr/Radarr/commit/28e9d112c8ef1c10d5a0a7785534ac50dee5fa71

correct link https://wiki.servarr.com/radarr/supported#couchpotatoimport

but yes refer to the settings page as well
