### ISSUE TITLE
Implement simple script to fix malformed databases.

### ISSUE THREAD

**Issue by dskvr** [Radarr/Radarr#6647]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Malformed database issues seem to have plagued upgrades for as long as I can remember. 

### Describe the solution you'd like

Implement or distribute or link to or port [this 16 line bash script](https://gist.github.com/sarim/6460936) that has solved this problem for me every time it has happened. It generally runs in about 5% of the time it takes to restore the backup `"I would have been faster in python"` 

### Describe alternatives you've considered

- Recommended over and over by devs and community: Delete the database (how about no?)
- Load into an SQL GUI and try to repair there
- Spend $100+ on repair tools
- Weep

### Anything else?

https://gist.github.com/sarim/6460936

[AB#1748](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1748)

**Comment by dskvr** [comment]
> This is an isolated issue with your setup that is causing the dB to get jacked up. .. Adding things such as bandaids isn't good practice when it effects 300k users and only one is having the issue..

It took me about 5 seconds to find data to disprove this statement, **on reddit alone** (plenty more on forums, stackoverflow, unraid forums, etc...) 

<img width="1190" alt="Screenshot 2021-10-09 at 18 04 02" src="https://user-images.githubusercontent.com/299465/136665852-392f0083-4237-42c0-90be-5c16494ff5f0.png">

> Corrupt databases are generally caused by an environmental issue not an application specific issue.

It's most likely related to docker, and a docker container being shutdown during a system task; [SQLite doesn't handle this situation well](https://www.sqlite.org/howtocorrupt.html). **SQLite is a design decision that made for the application,** so to say this isn't application-specific or at least in the domain of the application is a bit of a stretch. 

Docker isn't some fringe environment issue, either. `linuxserver/radarr` has 1B+ downloads which suggests this is a fairly sizeable portion of the user-base 
<img width="171" alt="Screenshot 2021-10-09 at 18 02 54" src="https://user-images.githubusercontent.com/299465/136665827-34bf7ba6-3ea3-400c-a317-75f5be0224a8.png">

> Looks like this effectively does the same thing as .recover. Except a PRAGMA check will frequently pass when the database is otherwise corrupt, so it would need some work.

You're right, I used to use sqlite.recover but switched to this bash script when I found it because it didn't place any requirements on my host and did the same thing, faster. 

That said, I fail to see how "not solving every issue" negates the benefit to users. Attempting `.recover` or this script or a port (that might not always work!)  to save `n` number of people 10-20 minutes each (assuming they know what they're doing, wayyy more if they are non-technical) is a huge win. If the database is still malformed, the error is still thrown. Doesn't seem that anything is lost in this situation, _unless I really am missing something here._ 

It could even just be a checkbox that is optionally selected when restoring a backup `[ ] Attempt disgruntled sandwich fix`
 
I understand very well that you need to limit the scope of Radarr, the efforts of development and have boundaries up to sustain forward momentum and stability, especially since I anticipate a large portion of the developers contribute on the side. For that, I'm forever grateful. 

I don't feel like dying on this hill, it's not that interesting of a hill, but do feel it's important that this is said because IMO the logic behind disqualifying this request seems woefully inadequate.

**Comment by Krandor1** [comment]
I’m just a user but a lot of your links are 2019 or 2020 so doesn’t seem common. 

Also If I was importing a db and saw “attempt disgruntled sandwich fix” checkbox I’d stop right there and hit discord or Reddit and ask what the heck that was, do I need to use it and how do I know if I need to use it because I’d have no idea what the heck that was or if I needed to use it?  That is a support nightmare and woukd generate way more threads then your one page of stuff from 2019 and 2020. 

I’m just a user and defer to the devs but this simple checkbox seems to me like it would cause more confusion then it would help.
