### ISSUE TITLE
Execute flag is not set during install and removed on update

### ISSUE THREAD

**Issue by stoeff42** [Radarr/Radarr#666]
I am running Radarr on Ubuntu Linux 16.10.
During initial install, the execute flag is not set and has to be set manually.
I am also using the automatic built-in update mechanism, which removes the execute flag on every update. This prohibits further starts of the executable and requires to set the execute flag again manually, which defeats the purpose of an automatic install.
Can you ensure the execute flag is set during install and not removed on every update?

**Comment by galli-leo** [comment]
can you try setting the execute flag for the folder?

**Comment by stoeff42** [comment]
I have set the execute flag on the installation folder for the owning user (radarr).
Will have to wait for the next update to see how it behaves. ;)

**Comment by stoeff42** [comment]
The udpate on February 22 again removed the execute flag. I realise the same problem is also apparent in NzbDrone, I will post a similar issue there.

**Comment by onedr0p** [comment]
I would make sure the user / group has full RW perms to the directory. I never had problems updating using the built in updater. I think this is an issue with your set up and not with radarr or sonarr.

**Comment by onedr0p** [comment]
Moreover radarr and sonarr don't change permissions.
