### ISSUE TITLE
[FEAT]: Change interval of tasks to be carried out

### ISSUE THREAD

**Issue by tandy-1000** [Radarr/Radarr#6666]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Radarr does a lot of work maintaining metadata because I have a lot of unmonitored movies which I don't have copies of in my library.
For my purposes, it would be much more efficient to have Radarr carry out certain tasks at a much larger interval, such as every week, rather than a short interval (some tasks are carried out as little as every minute) as I don't need the most up-to-date metadata.
It would reduce a lot of API calls from my Radarr, Sonarr, and Lidarr instances which would help on my low power server.

I know that this issue has been considered numerous times, but I am opening this issue in the hope that we can find a solution that the devs can agree on.

### Describe the solution you'd like

The ability to change the interval at which tasks are carried out either in Settings, or under System / Tasks.

To avoid bugs, this could be done by not allowing to tweak individual numbers, but by tweaking a single scale (which is greater than 0) which would allow you to scale up each individual interval in proportion. This potential solution would hopefully prevent unwanted user behaviour such as completely disabling tasks, or mess with the internal workings by changing individual intervals.

### Describe alternatives you've considered

I think I have read of some hacky ways to do this now, but it would be nice in the long term to have this feature, I would ask that this issue is kept open, even if a solution isn't agreed upon immediately, because this feature is highly requested by the community.

I think there is a solution which would satisfy everyone, including the devs.

### Anything else?

https://github.com/Radarr/Radarr/issues/3563
https://github.com/Radarr/Radarr/issues/3556
https://github.com/Radarr/Radarr/issues/2975

[AB#1789](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1789)

**Comment by ta264** [comment]
Closing for the same reason as all the others...
