### ISSUE TITLE
[FEAT]: Provide dotnet x86 binary for FreeBSD

### ISSUE THREAD

**Issue by mvanbaak** [Radarr/Radarr#6668]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Radarr under mono on FreeBSD runs on x86 and x64.
For dotnet there's only a binary for x64. While discussing the update of the radarr port in FreeBSD the 'downgrade' to x64 only was brought up.
See https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=259194#c4

### Describe the solution you'd like

Provide Radarr.master.<version>.freebsd-core-x86.tar.gz next to Radarr.master.<version>.freebsd-core-x64.tar.gz

### Describe alternatives you've considered

.

### Anything else?

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=259194

[AB#1795](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1795)

**Comment by ta264** [comment]
As soon as someone produces a working dotnet SDK with support for `freebsd-x86` we can build radarr for that platform
