### ISSUE TITLE
[FEAT]: Default Custom Format Scores

### ISSUE THREAD

**Issue by archonofletters** [Radarr/Radarr#6679]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Currently, when you create Custom Formats, you then go to the profiles section, select a profile, and then give a custom format a score that weights it numerically. 
This means that if you have multiple profiles and want to add, adjust or change custom formats it is a time consuming and repetitive process to go through and add or adjust the scoring in multiple profiles. This becomes very irritating as the number of custom formats and profiles increase

### Describe the solution you'd like

It would be good if you had a location to give the custom formats a "default" sore - either by a value box on the custom format setup panel itself, or a specific page that listed all the currently available custom formats. This would then apply to all profiles, but with the capacity for the profile itself to overwrite it. 

Ideally a profile would use the default as standard and show the score box with a greyed out placeholder value that represented the default value it was using, and black text as per usual when a user entered value has overwritten the default on that particular profile. I have added a mock up below of how that might look - in this mock up all "atmos" custom formats are using default values, and the DTS X and TrueHD custom formats are overwritten on the profile:
![Capture](https://user-images.githubusercontent.com/93259032/139057518-1301c834-569b-4ea9-9c5e-9cff1af65f24.PNG)

This would allow the quality of life afforded by only having to set a value in one place to affect multiple profiles, while maintaining the granularity to specify separate values per profile if required.

### Describe alternatives you've considered

I cannot think of any other way to circumvent the issue

### Anything else?

-

[AB#1825](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1825)

**Comment by Qstick** [comment]
> This feels to me like its a lot of work for minimal gain and a fair amount of scope for users shooting themselves in the foot. Let's see what others think.

I'd agree we have it defaulting to 0 by design so that a CF has no effect on profiles when initially added, thus protecting profiles/users from unwanted behavior.

**Comment by archonofletters** [comment]
I would argue that a user adding a value already indicates intention to not have a default 0 value apply.

If there was any other idea for a more elegant solution to having improving the QOL for managing CFs across multiple profiles though, I think that would be super valuable to explore.

**Comment by bakerboy448** [comment]
Third party sync apps such as notifiarr and Recylarr can handle this.

it can be scripted by users via the API as well
