### ISSUE TITLE
Once downloaded, remove it from the Movies list

### ISSUE THREAD

**Issue by greatvc** [Radarr/Radarr#668]
Like in Couchpotato, what i love is once a movie is downloaded then the movie gets removed automatically from the Movies list first page. A "Done" button will be good after download movie so once pressed the movie is deleted from the list. Maybe be added on another list like "Downloaded" but this is not important for me.

I do not want a huge list with movies that are downloaded and get messed up with my wanted list, after a while it will be unmanaged.

If you don't want this to be in a core feature an option with "Remove movie after download from list"  "YES / NO" could be a solution.

Thank you for your time

**Comment by galli-leo** [comment]
You can filter the first page to only include missing movies.

**Comment by greatvc** [comment]
yes ok but again the list will be huge after a while. Having downloaded and wanted films on the same page it will probably affect performance. I watch the movie and then i delete it from the computer. Whats the purpose of having the movie on the list even if it is hidden. After a while with 20+ movies per month the list will be unmanageable and huge.

Please re consider or let it live a bit so other users can see if it is interesting.

thank you

**Comment by onedr0p** [comment]
When the UI is redesigned we will take it into consideration. We do not want to spend time on improving the current UI.
