### ISSUE TITLE
Remote Paths Edit Button Off Screen for some Resolutions

### ISSUE THREAD

**Issue by hbednar** [Radarr/Radarr#6686]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

At the moment i am unable to edit or delete remote paths that i have already configured. 
I have to keep adding new ones and ignore the old ones.

### Expected Behavior

In Sonarr there is a spanner icon at the end of the path mapping that allows you to delete or edit the mapping.

### Steps To Reproduce

Add a mapping

### Environment

```markdown
- OS: Debian Sid and 11
- Radarr: 4.0.0.5385
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Any
```

### What branch are you running?

Develop

### Anything else?

Radarr:
![image](https://user-images.githubusercontent.com/71215137/139249343-38a4d06e-c201-42dc-93f4-b30176c4ebe5.png)

Sonarr:
![image](https://user-images.githubusercontent.com/71215137/139249426-6c8be41a-3815-4733-bf6d-dc09d0c38476.png)

[AB#1832](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1832)

**Comment by austinwbest** [comment]
Cant reproduce, any smaller and it goes to mobile layout..

![image](https://user-images.githubusercontent.com/8321115/139565608-0ffdc272-8684-437e-8c9f-a18656e0b070.png)
![image](https://user-images.githubusercontent.com/8321115/139565611-d829735a-209c-4aac-8a54-87dfed77dd7e.png)
![image](https://user-images.githubusercontent.com/8321115/139565630-edafe575-2d2a-4330-b3f5-03aaa94805a0.png)

**Comment by malaki86** [comment]
This is an old issue, but I have the same issue on my new install. No bottom scrollbar on the screen at all. This is on my mobile and on my PC.

**Comment by malaki86** [comment]
This is an old issue, but I have the same issue on my new install. No bottom scrollbar on the screen at all. This is on my mobile (both portrait and landscape) and on my PC (landscape).

![Screenshot_20221216-115650_Chrome](https://user-images.githubusercontent.com/50643710/208149931-99c8cdfd-9098-4605-8fe1-1c8645e67300.jpg)

![Screenshot_20221216-115707_Chrome](https://user-images.githubusercontent.com/50643710/208149963-bf06bbe6-21cb-4fbe-9b72-1925eb31e67b.jpg)
