### ISSUE TITLE
API command "RescanMovie" not working

### ISSUE THREAD

**Issue by SJ50** [Radarr/Radarr#669]
1. RescanMovie does not mark movie as downloaded but RefreshMovie does mark movie as downloaded
2. for PUT method to update existing movie, if json object does not contain value of imdbId and tmdbId than these value changes to null.

**Comment by fedoranimus** [comment]
What endpoint are you calling to update an existing movie for the second part of your issue?

**Comment by SJ50** [comment]
I wanted to update path so I run this command 
`http://$RADARRHOST/api/movie  -H "Content-Type: application/json" -H "X-Api-Key:$RADARRAPI" -X PUT -d '{"path":"'$MOVIEPATH'","profileId":"'$MOVIEPROFILEID'","id":"'$MOVIEID'"}'`
Than I checked the result and compared it with original result, new result was missing IMDBID and TMDB was "0".

**Comment by galli-leo** [comment]
@SJ50 As stated on the wiki you have PUT the whole json body, you retrieved before with GET

**Comment by SJ50** [comment]
At this moment I am using 
````
-X PUT -d '{"path":"'$MOVIEPATH'","profileId":"'$MOVIEPROFILEID'","imdbId":"'$IMDBIDR'","tmdbId":"'$TMDBID'","id":"'$MOVIEID'"}'
````
which does the job
