### ISSUE TITLE
[FEAT]: auto-blacklist "sample" (scam) releases

### ISSUE THREAD

**Issue by Ae3NerdGod** [Radarr/Radarr#6705]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

sometimes when a new movie is about to come out, a bunch of spammers upload a fake "download this codec" release before the movie comes out, these often (almost always actually) get detected as "samples" despite being a possible size of a regular release ([apparantly due to runtime detection after the release is downloaded)](https://github.com/Radarr/Radarr/issues/4365#issuecomment-620275352)

i know this has been closed here: https://github.com/Radarr/Radarr/issues/4365 but im confused and would like to argue the case better, i dont think the problem was made clear in that issue.

confusion:  if sample detection is based on runtime, how is a size limit meant to help? as mentioned in the issue, the file size is often far larger than the runtime, and some releases are actually the same size as these scam releases. 

this is often very frustrating when it prevents a real release from being downloaded once a title is actually released (this type of fake-release is very common for highly anticipated movies from my experience.) its also worth noting this happens just about EVERY time you add a movie that hasnt come out yet. to the point where i can recreate the issue in just a few minutes:
![scam-releases](https://user-images.githubusercontent.com/2036505/140445521-5f3a79c2-6823-41f3-adf8-1e00536fd43a.png)
.

### Describe the solution you'd like

a checkbox somewhere to auto-blacklist releases detected as samples, since they cant be detected on filesize or before theyre downloaded

### Describe alternatives you've considered

cant think of any other solution, unless im misunderstanding the file size solution. and scanning the video to detect scam files seems like too much to ask

### Anything else?

would really appreciate some consideration to this issue.

[AB#1867](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1867)

**Comment by thezoggy** [comment]
ideally your indexer should filter out this stuff, theres lots of stuff out there for them to weed this sort of stuff out. then also you can just set sensible quality sizes in radarr to have it skip trying to download these bogus releases. and then finally in your downloading app it can filter out things that have .exe or x bad files.

**Comment by bakerboy448** [comment]
Closing Duplicate

set your availability settings appropriately if you have indexers that have lots of fakes, covered on the FAQ.  Groups that do this can be blocked as well

it does not make sense to auto reject and blocklist if a sample as found as there are many reasons why a release has a sample and a blanket reject doesn't make sense

**Comment by Ae3NerdGod** [comment]
> ideally your indexer should filter out this stuff, theres lots of stuff out there for them to weed this sort of stuff out. then also you can just set sensible quality sizes in radarr to have it skip trying to download these bogus releases. and then finally in your downloading app it can filter out things that have .exe or x bad files.  

the indexers (if you mean the sites) do take care of it,  just not fast enough. 

all due respect, not everyone wants to download 85 gig 4k 10bit downloads of everything. these are sensible file sizes, and as you can see from the hex editor, theyre padded. they're simply going to start padding them larger. i think there should be a solution to this, you guys are in the position to solve it.

**Comment by Ae3NerdGod** [comment]
> Closing Duplicate
> 
> set your availability settings appropriately if you have indexers that have lots of fakes, covered on the FAQ.  Groups that do this can be blocked as well
> 
> it does not make sense to auto reject and blocklist if a sample as found as there are many reasons why a release has a sample and a blanket reject doesn't make sense

these releases have *only* a sample. surely that can be detected and filtered separately than releases that *include* a sample.

**Comment by Ae3NerdGod** [comment]
i forked and added the option. seriously guys youre just being lazy.

**Comment by austinwbest** [comment]
> I cloned the source and added the option. seriously guys you're just being lazy. 

The smarter thing to do would have been to submit a PR for it and discuss it with the devs.

I guess calling people lazy is your preference so as far as I'm concerned, use your fork as I sure as hell will continue to be lazy and not even bother looking at it.

**Comment by Ae3NerdGod** [comment]
>The smarter thing to do would have been to submit a PR for it and discuss it with the devs.

hahahaha right, because you people have proven to be so receptive! puh-lease.

> I guess calling people lazy is your preference so as far as I'm concerned, use your fork as I sure as hell will continue to be lazy and not even bother looking at it.

When it takes me, an amateur, less than a month to learn your code, and add a simple fucking checkbox? yea you're lazy AF. but keep trying to highroad me, author of software that automates piracy, that cant even maintain a debian repo?. its cute. i tried nice so did another guy and all the people who liked the feature request, you rejected it.  ridiculous

**Comment by Ae3NerdGod** [comment]
![5xia7l](https://user-images.githubusercontent.com/2036505/145684753-b9ceebcc-4c87-4b3c-ba36-6dfdee8912e0.jpg)
