### ISSUE TITLE
[BUG]: 405 When Marking Item As Failed From Table In History Tab

### ISSUE THREAD

**Issue by TheMeanCanEHdian** [Radarr/Radarr#6708]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When marking an item as failed from the history tab a 405 error is given. I have tested this behavior on 2 movies. 

### Expected Behavior

I would expect no 405 error and the item to be successfully marked as failed.

### Steps To Reproduce

1. Go to a movie's history tab
2. Click the `x` to mark as failed
3. 405 error is given

### Environment

```markdown
- OS: Unraid
- Radarr: 4.0.0.5437
- Docker Install: 4.0.0.5437-ls145 by linuxserver.io
- Using Reverse Proxy: no
- Browser: Chrome
```

### What branch are you running?

Nightly

#### Example movie 1
GIF of console showing 405 behavior:
![ou9ysv2T6X](https://user-images.githubusercontent.com/16025103/140566716-3e44b70b-a7ea-4a58-9c16-cb0245ab6667.gif)

#### Example movie 2
Screenshot of everything in the payload under the network developer tool:
![chrome_xyslU5FabL](https://user-images.githubusercontent.com/16025103/140566875-77311989-44c1-4a4c-8319-bc6ef2ec049e.png)

[AB#1875](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1875)

**Comment by bakerboy448** [comment]
Same as https://github.com/Radarr/Radarr/issues/6483  No?

**Comment by ta264** [comment]
Related but different
