### ISSUE TITLE
[BUG]: Bad "More Info" Link - Prefer Indexer Flags

### ISSUE THREAD

**Issue by neo-neo1** [Radarr/Radarr#6717]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`Settings` -> `Indexers` -> `Prefer Indexer Flags` -> Click [More Info](https://wiki.servarr.com/Definitions#Indexer_Flags)

### Expected Behavior

Not aware of the current proper link. Ideally a link to the Radarr Wiki.

### Environment

```markdown
- OS: Agnostic
- Radarr: 3.2.2.5080
- Docker Install: ghcr.io/linuxserver/radarr:develop
- Using Reverse Proxy: Agnostic 
- Browser: Firefox 94.0.1
```

### What branch are you running?

Develop

### Anything else?

It was [marked done a year ago](https://github.com/Servarr/Wiki/issues/2).

[AB#1891](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1891)

**Comment by bakerboy448** [comment]
fixed in nightly
https://github.com/Radarr/Radarr/commit/84d1a8983bee6ec17e4ca11bdcb97ff6254845f2
