### ISSUE TITLE
[BUG]: NOT NULL constraint failed: Notifications_temp.OnRename Sql Exception during database migration

### ISSUE THREAD

**Issue by Sohardh** [Radarr/Radarr#6728]
### Current Behavior

Release Version: 3.2.2.5080
Platform: Unraid docker

Hi, 
Radarr is not working on unraid with the latest release. I also tested on develop as well as on fortnight, it didn't work. In logs it says Sql constraint violation in the migration script -> add_on_delete_to_notifications. 

Please find the attached log file for the full stack trace
[radarr.log](https://github.com/Radarr/Radarr/files/7540264/radarr.log)

### Expected Behavior

OnRename null constraint is failing, maybe we are inserting a null value. OnRename column should not have a null value.

### Steps To Reproduce

1. Platform: Unraid
2. Download Radarr from Community Applications. I download it from linuxserver.
3. Attached are my configurations for the container.
<img width="1035" alt="Screenshot 2021-11-15 at 10 20 30 PM" src="https://user-images.githubusercontent.com/31403178/141821525-b21ab49b-db31-462e-b3a8-a51f76d4f98e.png">
3. After it launches the container, check web UI is not working. 
4. Check the logs and you will see the same logs as attached.

### Environment

```markdown
- OS: Unraid
- Radarr: 3.2.2.5080
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Chrome
```

### What branch are you running?

Master

### Anything else?

No

[AB#1908](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1908)

**Comment by RobinDadswell** [comment]
Looking at your log file you are running version `4.0.0.5492` and not `3.2.2.5080`.

This looks like it's an issue with your database already having that column in the notifications table. 

Please take it to discord though as it looks it is specific to you
