### ISSUE TITLE
Feature Request - Minimal movie requirements

### ISSUE THREAD

**Issue by julienki** [Radarr/Radarr#673]
Couchpotatoe has a feature called "minimal movie requirements" which exclude movies from being monitored if they don't meet minimal requirements, like for example the IMDb score.

It would be great if a similar feature could be implemented in the List tab.
I would be even better if we could also filter out by genre (ex: Action).

So for example, you could make all movies imported from lists being monitored automatically except movies with a IMDb score less than _7_ or the genre _Musical_.

**Comment by SJ50** [comment]
+1 for this feature.
Please add language requirement as well, because CP is also adding lots of foreign movies to my wanted list.

**Comment by galli-leo** [comment]
@SJ50 You can control the language in your quality profile.

**Comment by SJ50** [comment]
If I understand correctly than movie gets into wanted list but never gets snatched.

**Comment by geogolem** [comment]
I worked on a feature to allow exclusions on the lists page: 

https://github.com/Radarr/Radarr/pull/656

![temp](https://cloud.githubusercontent.com/assets/23205277/22848982/b852a376-efc6-11e6-83ef-e85319b239fa.PNG)

perhaps other things like genre could be added... 

@galli-leo : I dont think the quality profile handles what this request is describing -- they want to prevent movies from being imported into Radarr -- not just certain releases from being downloaded.. It is basically an extension to the exclusions feature i recently implemented..  My feature allows exclusions to be specified via imdbid or tmdbid --> they want to exclude based on more complex attributes... Its possible but not a priority right now.. (@onedr0p and I were discussing this last night too - I might look into it in the future, but not right now)

**Comment by SWu** [comment]
+1, more options around filtering automatic lists would be really useful.

The new TMdb lists have an option to filter by avg vote, but it would be great to add a related option to also filter by minimum number of votes to suppress movies with only a few votes (number of votes should be exposed by the TMdb API). And along with the other suggestions here, black/whitelisting specific languages and genres should also be possible with the information available in the TMdb response object.

**Comment by onedr0p** [comment]
Trakt and tmdb have filtering options via lists

**Comment by Nyghto** [comment]
Still, the minimum imdb votes required from CouchPotato was very very useful, and would really like to see this filter option added to all list sources. New movies tend to have high ratings so chance is bigger 'crap' movies get on wanted list. Seeing this now with Radarr and havent found a way yet to work around it.

**Comment by Nyghto** [comment]
Feature is not in Radarr yet, still missing this feature from couchpotato a lot: minimum amount of votes, year and rating (for imdb). With current list criteria in Radarr crap movies get downloaded more often.

**Comment by Rouzax** [comment]
@galli-leo Sorry for the kick, but just migrated from CouchPotato and the import restrictions are really missing.
Is this still on the roadmap?

**Comment by monkiibiz** [comment]
I'd be interested in knowing this as well - made the mistake of subscribing to the Popular Movies list today... the amount of crap that was added to the queue was mind-boggling!

**Comment by Rouzax** [comment]
@monkiibiz, I have a new feature request open for this.
https://github.com/Radarr/Radarr/issues/2955
