### ISSUE TITLE
[BUG]: Cannot Remove Pending Release from Queue (Possibly any release?)

### ISSUE THREAD

**Issue by bakerboy448** [Radarr/Radarr#6730]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is no longer possible to remove a pending release due to a 500 Server Error

### Expected Behavior

It should be possible to remove a pending release

### Steps To Reproduce

1. Have a pending release in queue
2. Attempt to remove OR remove & blocklist pending release
3. Release is not removed; UI shows no errors

### Environment

```markdown
- OS: agnostic
- Radarr: 4.0.0.5497
- Docker Install: agnostic
- Using Reverse Proxy: agnostic
- Browser: agnostic
```

### What branch are you running?

Nightly

### Anything else?

There are at least two bugs here:
- Removing a queue item without blocklisting should not call the blocklist
- Removing a queue item should be possible

Logs
https://gist.github.com/bakerboy448/954655b59b2f5b21f19c3924914fe7de

occurs for blocklist=true and blocklist=false

This line appears it may not be right and should be inserted above Ln 234
https://github.com/Radarr/Radarr/blob/a8b563de7b56c9875ef504b7f087bf17c093625b/src/Radarr.Api.V3/Queue/QueueController.cs#L207

Seems this may be the cause of the missing language?
https://github.com/Radarr/Radarr/blob/develop/src/NzbDrone.Core/Blocklisting/BlocklistService.cs#L80-L88

[AB#1912](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1912)

**Comment by RobinDadswell** [comment]
> This line appears it may not be right and should be inserted above Ln 234

This is only for pending releases and matches the behaviour implemented in Sonarr in https://github.com/Sonarr/Sonarr/commit/3f60e28c42d946691c4d44eb391b7888466538d9
