### ISSUE TITLE
[FEAT]: Add "Imported From" metadata in imported movies 

### ISSUE THREAD

**Issue by mxilievski** [Radarr/Radarr#6734]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Nope

### Describe the solution you'd like

I have multiple lists that grabs movies automatically. Ideally when a movie is being improrted from a list, I would like to know from which list it was imported or if I imported this movie manually. 

Why? 
Often I get some very bad movies that I have no idea where they come from. Having this metadata would help me filter out the list and improve my content. 

### Describe alternatives you've considered

None.

### Anything else?

None.

[AB#1920](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1920)

**Comment by ta264** [comment]
Assign a tag to the list, then the movie will get that tag.  I don't think we have any plans to do any more on this.

**Comment by mxilievski** [comment]
@ta264 that's exactly what I needed and will get the job done. Tnx a lot.
