### ISSUE TITLE
[BUG]: Logging in to one instance, logs me out of the other and vice-versa.

### ISSUE THREAD

**Issue by ghost** [Radarr/Radarr#6738]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have two instances of radarr running via docker.

I recently updated my image like I always do, however, now, I have this issue where when I log into to one instance, it will log me out of the other. I had never had this issue before and I'm not sure how to fix it.

### Expected Behavior

When you log in to one instance, the other should stay logged in, like it always had.

### Steps To Reproduce

1. Install docker
2. Install radarr
3. Create 2 radarr instances on different ports
4. Log into both and the first to be logged in will be logged out once you log into the first one.

### Environment

```markdown
- OS: Synology DSM 6.2
- Radarr: Radarr 4.0.0.5473
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Edge 95.0.1020.53
```

### What branch are you running?

Nightly

### Anything else?

Sonarr doesn't have this issue and prior to one of the recent updates, neither did radarr.

[AB#1925](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1925)

**Comment by bakerboy448** [comment]
This is due to the Servarr *Arrs not having a unique cookie name.

discussed on discord previously

ref from @geogolem 

> Sonarr uses SonarrAuth
> whereas the others (Lidarr, Radarr, Readarr and Prowlarr) all use: .AspNetCore.Forms

https://discord.com/channels/264387956343570434/264388019585286144/909229516625428550

**Comment by geogolem** [comment]
https://github.com/Radarr/Radarr/pull/6722

**Comment by Qstick** [comment]
#6722 doesn't quite fix this issue but will ensure that logging into Radarr doesn't log out of Lidarr, Readarr, or Prowlarr. Leaving this open as still some work Todo to solve it as detailed in 6722 comments

**Comment by bakerboy448** [comment]
Tracking under https://github.com/Radarr/Radarr/issues/10416

**Comment by rafapirotto** [comment]
Pr created [here](https://github.com/Radarr/Radarr/pull/10440)
