### ISSUE TITLE
[BUG]: /notification api for Pushover is missing "onHealthIssue"

### ISSUE THREAD

**Issue by anonyme123** [Radarr/Radarr#6744]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

curl -s "$serverURL:$radarrPort/radarr/api/notification" -H "X-Api-Key: $radarrAPIkey" 
{
  "onGrab": false,
  "onDownload": false,
  "onUpgrade": true,
  "onRename": false,
  "onMovieDelete": false,
  "onMovieFileDelete": false,
  "onMovieFileDeleteForUpgrade": false,
  "supportsOnGrab": true,
  "supportsOnDownload": true,
  "supportsOnUpgrade": true,
  "supportsOnRename": false,
  "supportsOnMovieDelete": true,
  "supportsOnMovieFileDelete": true,
  "supportsOnMovieFileDeleteForUpgrade": true,
  "tags": [],
  "name": "Pushover",
...

### Expected Behavior

curl -s "$serverURL:$radarrPort/radarr/api/notification" -H "X-Api-Key: $radarrAPIkey" 
{
  "onGrab": true,
  "onDownload": true,
  "onUpgrade": true,
  "onRename": true,
  "onDelete": true,
  **"onHealthIssue": true,**
  "supportsOnGrab": true,
  "supportsOnDownload": true,
  "supportsOnUpgrade": true,
  "supportsOnRename": true,
  "supportsOnDelete": true,
  "supportsOnHealthIssue": true,
  "includeHealthWarnings": true,
  "name": "Pushover",
...

### Steps To Reproduce

1. Run curl -s "$serverURL:$radarrPort/radarr/api/notification" -H "X-Api-Key: $radarrAPIkey" 

### Environment

```markdown
- OS: Linux-4.19.0-0.bpo.17-amd64-x86_64-with
- Radarr: 3.2.2.5080
- Docker Install: Yes (3.2.2.5080-ls119 by linuxserver.io)
- Using Reverse Proxy: No
- Browser:
```

### What branch are you running?

Master

### Anything else?

No

[AB#1935](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1935)

**Comment by Qstick** [comment]
Use api/v3 endpoints
