### ISSUE TITLE
Duplicate  Movies

### ISSUE THREAD

**Issue by mpatel514** [Radarr/Radarr#675]
It appears I'm getting duplicate movies that are being synced from lists.  One version has the 6 digits appended and the other has the year.

Example:
movies/before-i-fall-397837
movies/before-i-fall-2017

**Comment by onedr0p** [comment]
Which one was in your library already?

**Comment by mpatel514** [comment]
I'm not sure, is there a way to check?  I was going to check the creation of the folder but they share the same folder.

Most of them look similar but Fifty Shades Darker has some different tags.

movies/fifty-shades-darker-341174
- In Cinemas: February 2017
- Rating 6.3
- Also known as: Fifty Shades Darker and 50 Shades Darker.

fifty-shades-darker-2017
- Announced
- Rating 6
- Also known as: Fifty Shades Darker.

Not sure where it's pulling the data from but I'm hoping that may help.

**Comment by mpatel514** [comment]
Seeing this in the logs starting yesterday @ 10:21am EST

Couldn't refresh info for [tt1691916][Before I Fall]: constraint failed
UNIQUE constraint failed: Movies.TitleSlug

**Comment by onedr0p** [comment]
Delete the duplicate movies, then run the update to all your movies. That should fix this.

**Comment by galli-leo** [comment]
This is probably and issue where the TMDBId changed.
