### ISSUE TITLE
[FEAT]: Might be cool to have IMAX as a quality option

### ISSUE THREAD

**Issue by AtariBaby** [Radarr/Radarr#6753]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Not a problem!

### Describe the solution you'd like

I thought it might be cool to have IMAX as a quality option, among choices like 1080p and 2160p. Maybe unnecessary and for too small an audience. Currently only three brands of TV even have a build-in IMAX feature, and I’m lucky to have a Sony Bravia that does it.

### Describe alternatives you've considered

As BakerBoy responded:

“No plans to add a special IMAX quality given this is already accomplished with custom formats and requires no additional effort.”

Just adding it here in case it become attractive in future brainstorming or whatever. Feel free to dismiss!

### Anything else?

Just thanks for working so hard on Radarr!

[AB#1958](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1958)

**Comment by bakerboy448** [comment]
Closing No plans :)

imax is an edition, not a quality (source+resolution)

already possible to prefer imax with custom formats
