### ISSUE TITLE
[FEAT]: linux-musl-arm

### ISSUE THREAD

**Issue by radumamy** [Radarr/Radarr#6754]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Could you please add support for a linux-musl-arm / arm32 build? There is one arm64. Thank you. 

### Describe the solution you'd like

An arm32 build to be added for current and future releases. Thank you. 

### Describe alternatives you've considered

Mono, but support will be dropped soon. 

### Anything else?

N/A. 

[AB#1961](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1961)

**Comment by ta264** [comment]
This will be added in v4 (along with osx-arm64).  We will not be adding linux-musl-arm builds for existing releases.

**Comment by radumamy** [comment]
Excellent, thank you. Am I right in thinking that from v4, there will be no more Mono builds published? Just wondering what users on i686 would do as MS hasn't released a Linux dotnet SDK for it yet. I appreciate Mono won't be supported, but users could still build it locally.

**Comment by ta264** [comment]
Radarr v4 will not run on i686.  It's no longer possible to build Radarr for mono without significant code edits.

**Comment by radumamy** [comment]
Thank you.
