### ISSUE TITLE
Custom Formats to Discord Notification

### ISSUE THREAD

**Issue by mikertoad** [Radarr/Radarr#6773]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

No existing problem

### Describe the solution you'd like

Include the custom formats and score to the Discord Notification on grab or import.

### Describe alternatives you've considered

I usually check the titles activity or logs to see what the score was

### Anything else?

None

[AB#2019](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2019)

**Comment by bakerboy448** [comment]
https://github.com/Radarr/Radarr/commit/3d3562dcdaa23ca0a5b6dcb0ea3064da79c57a33
