### ISSUE TITLE
Bulk Add Not Adding All Movies And Throws Exception

### ISSUE THREAD

**Issue by dcplaya** [Radarr/Radarr#678]
I spoke to Gallileo on Discord and he said to post the trace log on Github. I am unable to get certain movies to show up when adding existing movies via bulk or individually. 

[radarr.trace.1.txt](https://github.com/Radarr/Radarr/files/764753/radarr.trace.1.txt)

**Comment by drafie** [comment]
@galli-leo Not sure if you want me to open a new issue or not - but I have the same fundamental problem.  Bulk import is not adding movies.   However, the error is different I think.

I've bulk added about 3,000 movies.   But the total count on the Movie page has not moved from 800ish.

Attaching the logs here. 
[radarr.txt](https://github.com/Radarr/Radarr/files/775424/radarr.txt)

**Comment by drafie** [comment]
Actually it appears my issue is related to #743 and #748

**Comment by galli-leo** [comment]
Can you try this again on the latest nightly. A lot of issues in the Bulk import should have been fixed.

**Comment by fedoranimus** [comment]
Should be fixed by #785. Will re-open if the issue continues to exist.
