### ISSUE TITLE
UI: Allow custom text in HTML title bar

### ISSUE THREAD

**Issue by KarmicIT** [Radarr/Radarr#6791]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

A common question lately for the *arr's is to allow a single instance of the application to support multiple versions of a download (i.e. 1080p and 4k versions). This is not currently possible and the workaround is to run multiple instances instead, one per download type.

I'd like to request the ability to "name" an instance and have that name shown in the HTML title bar, either next to - or replacing - the existing text of "Radarr". This would let people easily see which instance they are currently browsing without needing to remember that the Radarr instance on port 1234 is the 4k version versus the instance on port 4321 which is for 1080p.

This feature could be added within the Settings>General>Host area, with a freeform text box that is only visible when showing advanced options is enabled.

### Describe alternatives you've considered

Raw HTML files are not available to edit and would be overwritten by any updates.

### Anything else?

This capability already exists for hard-coded menus and movie names when you browse the GUI. I.e. if you go to the Settings menu the HTML title bar shows "Settings - Radarr". Likewise, if you are looking at an existing movie release it will say "Lord of the Flies - Radarr".

This request would enable the HTML title bar show something similar to "Indexer Settings - 1080p - Radarr" or "Lord of the Flies - All Your Bases Are Belong To Us - Radarr", etc.

[AB#2087](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2087)

**Comment by Qstick** [comment]
I think we'd be up for it, but I'd want to require the program name as a validation... Ex. `Radarr 4k` OK, `CouchPotato 4` NOT OK

**Comment by bakerboy448** [comment]
https://github.com/Radarr/Radarr/commit/a37fc0dc1f64e7e8becaabc8296a4bec80bc8dc7
https://github.com/Radarr/Radarr/commit/0559996566c6813cdf6c7529b2f31d23e08d0a43

Supported w/ the Instance Name commits
