### ISSUE TITLE
Allow customs user-agent for RSS indexers

### ISSUE THREAD

**Issue by YggNode** [Radarr/Radarr#6793]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

In a way yes.

If a website is protected by cloudfare anti-DDOS system, then we've to use jackett and flaresolverr.

### Describe the solution you'd like

In a way to light our system, is it possible to introduce a new form entry in indexers form to allow user to set custom userAgent.

For example on yggtorret.re, it's YggRobot. It allows the request to bypass automatically CF protection without resolving a challenge.

### Describe alternatives you've considered

Flaresolverr and Jackett but it's really heavy and for simple users without technics skills, it's hard to understand all those tools simultaneously.

### Anything else?

With democratization of this method to allow automatic tools to bypass CF protection, it could be a great idea to simplify user requirements which are actually not quite easy .

[AB#2094](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2094)

**Comment by bakerboy448** [comment]
I concur with Ta.

this would be best (and is for Prowlarr) handled on the Jackett / Prowlarr side

of course ideally the UAs for Jackett/Prowlarr/Radarr/Sonarr are all just allow listed
