### ISSUE TITLE
Radarr is eating space in my tmp folder for backup

### ISSUE THREAD

**Issue by eephyne** [Radarr/Radarr#6815]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I build some package sometimes I miss space on /tmp, and when I check I see that radarr is eating between 1.2 and 1,6g for backup but is not running any backup at this moment. 
I delete them but eventually they come back.

I precise that I use tmpfs to use ram for /tmp folder thats why its kind of important :) (I have only 4g of ram for now).

inside the  radarr_backup folder I have three files radarr.db radarr.db-journal and config.xml.

### Expected Behavior

not having thoses files remaining after the end (I guess) of the backup.

### Environment

```markdown
- OS: arch
- Radarr: 3.2.2.5080
- Docker Install: no
- Using Reverse Proxy: yes but not related
- Browser: chrome but not related
```

### What branch are you running?

Master

### Trace Logs?

no trace log in particular.

I found that in the log of the day corresponding of the last auto backup, don't think it's useful.

2021-12-06 18:59:59.4|Info|BackupService|Starting Backup
2021-12-06 19:02:29.4|Error|CommandExecutor|Error occurred while executing task MessagingCleanup

[AB#2147](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2147)

**Comment by ta264** [comment]
While using a ramdrive for tmp might not be smartest, leaving temp files behind should be fixed

**Comment by eephyne** [comment]
using tmpfs is for avoiding high demand on ssd drive

**Comment by bakerboy448** [comment]
This should be cleaned up during the housekeeping task, no?

Let's see trace logs of that task being kicked off and running.

And while we're at it the same for a backup task as well

**Comment by ta264** [comment]
> This should be cleaned up during the housekeeping task, no?
As far as I can see it only clears out update files, not backup.

Still, it would be better if you came by the discord channel to dig into this

**Comment by eephyne** [comment]
I joined but need to wait to be able to speak.
In the meantime I did a manual backup and I discovered one issue . since its tmpfs, my ram was full and the radarr process was killed (out of memory) so no cleaning.

I deactivated the tmpfs and retry.
The backup complete but the db file stay.

**Comment by ta264** [comment]
`Cleanup()` probably needs calling additionally after creating the backup zip

https://github.com/Radarr/Radarr/blob/3d36f88939dd1b238452bfd7749a8afc9fa0ad16/src/NzbDrone.Core/Backup/BackupService.cs#L75
