### ISSUE TITLE
Poster View showing path without a way to disable it

### ISSUE THREAD

**Issue by TerraTech** [Radarr/Radarr#6816]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

While I was importing some manually downloaded movies, I had switched to "Table View" and enabled the option to display the Path.  When I returned to the "Poster View", the path was now displayed without any way to turn it off.

I went back to "Table View" and disabled the Path option, then switched back to "Poster View" but unfortunately that did not turn it off there.  There is not option within "Poster View" to disable the Path.

Another oddity is switching to "Overview View", the Path is displayed.  Disabling the "Show Path" option has no effect, however if you click "Show Date Added" it will replace the Path output with the Date Added output.  If you turn off "Show Date Added" the Path will show up again.

### Expected Behavior

1. Add a "Show Path" option to "Poster View", like it is for "Overview View"
2. Enabling/Disabling "Show Path" actually working correctly

### Steps To Reproduce

1. Switch to "Table View"
2. Enable "Path" [path will be displayed]
3. Switch to "Poster View", path will be displayed
4. Switch to "Table View" and disable "Path"
5. Switch to "Poster View", path will still be displayed
6. _See "Current Behavior" above for details about "Overview View"_

### Environment

```markdown
- OS: Windows 10
- Radarr: Radarr 3.2.2.5080
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Chrome 96.0.4664.45 (Official Build) (64-bit)
```

### What branch are you running?

Master

### Trace Logs?

I don't believe Trace file is relevant in this case (_has sensitive info in it_)

_Below image shows the displayed path at bottom_
![radarr-poster-view-big-bug-bunny](https://user-images.githubusercontent.com/1118433/146100745-54e227e4-4069-49a3-8e50-58b28ed49b2e.png)
.

[AB#2150](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2150)

**Comment by Qstick** [comment]
I'd assume this is because of your sort, it'll always show the property you are sorting by

**Comment by TerraTech** [comment]
Aha - that was it.  Switched to "Title" sort and path is no longer displayed.

Thank you for pointing me in the right direction.

**Comment by Qstick** [comment]
No problemo
