### ISSUE TITLE
Brave/Chrome/Chromium not working

### ISSUE THREAD

**Issue by Y0ngg4n** [Radarr/Radarr#6819]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When i navigate to my Radarr Page i just get a blank page and this console log:
```
xhr.js:39 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ xhr.js:39
translate.js:33 Uncaught TypeError: Cannot read properties of null (reading 'MovieTitle')
    at No (translate.js:33)
    at Object.71639 (blacklistActions.js:36)
    at r (bootstrap:19)
    at startup:4
    at Function.r.O (chunk loaded:25)
    at startup:5
    at index.js?h=zUcZaiTWuIKF4+Ac3h78Ow:1
```

### Expected Behavior

Just useable like in Firefox

### Steps To Reproduce

- Setup Radarr with docker and nginx reverse proxy.
- Browse to Radarr Instance with Brave

### Environment

```markdown
- OS: Debian Bullseye
- Radarr: docker:lates
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Brave
```

### What branch are you running?

Master

### Trace Logs?

xhr.js:39 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ xhr.js:39
translate.js:33 Uncaught TypeError: Cannot read properties of null (reading 'MovieTitle')
    at No (translate.js:33)
    at Object.71639 (blacklistActions.js:36)
    at r (bootstrap:19)
    at startup:4
    at Function.r.O (chunk loaded:25)
    at startup:5
    at index.js?h=zUcZaiTWuIKF4+Ac3h78Ow:1

[AB#2154](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2154)

**Comment by bakerboy448** [comment]
"Docker latest" is not a radarr version

No other issues reported in over 6 months on master / 3.2.2 so I'm thinking this is either a corrupt install or an extension or setting in brave causing issues.

can you go through the classic browser troubleshooting steps of trying incognito without any extensions

Swing by discord to debug further

**Comment by bakerboy448** [comment]
For posterity - resolved by correctly configuring the radarr nginx per the official Radarr instructions
