### ISSUE TITLE
Feature Request: After processing the file, put it directly in a preset folder (flat file structure)

### ISSUE THREAD

**Issue by Paradoxx2015** [Radarr/Radarr#683]
I dont see any config of setting the prosessed file directly in i preset folder. Every time a file is downloaded it creates a folder with the file name and put the file in this folder. 
Because of som media scanners its not possible to locate the file because its in a folder and not in a flat file structure.

E.g:
Today: c:\movies\Nocturnal\Nocturnal.mvk

Request: c:\movies\Nocturnal.mkv
(dropping the "Nocturnal" folder)

**Comment by onedr0p** [comment]
This is already a feature request, but it's not anything we will support any time soon. Sorry.
