### ISSUE TITLE
When a movie cannot be parsed, a huge number of entries are entered into the logs

### ISSUE THREAD

**Issue by RoldGold25** [Radarr/Radarr#685]
I downloaded a movie as BD50, with the entire directory structure of the blu-ray still intact. As a result, Radarr couldn't parse out the movie file. Radarr added 800,000 entries to the logs over the course of the past couple days before I realized.

![image](https://cloud.githubusercontent.com/assets/25273633/22812568/8f3971a8-ef13-11e6-9b59-120a3b15e1f1.png)

The entries offer no new information (as best as I can tell) each time they are added to the logs. It seems unnecessary to muddy up the logs by posting so frequently to them. Perhaps once the parse operation fails it shouldn't keep trying.

[Logs are attached here](https://github.com/Radarr/Radarr/files/765577/radarr.txt). (This is not the entire 800k entry log, just a snippet).

**Comment by onedr0p** [comment]
Until (If?) we support BR-Disk or DVD folder structure you should remove managing those from Radarr

**Comment by RoldGold25** [comment]
How would I go about doing that? I looked through the settings menu and I couldn't find that option.

I'm suggesting that once Radarr fails the attempt to import the files, it should stop trying. Seems like it wastes CPU cycles and balloons the log file (to 200MB in my case).

**Comment by galli-leo** [comment]
Also this causes issue with RAM usage, since linux likes to map files into RAM (and a large log database takes up a large amount of RAM).
