### ISSUE TITLE
Better Collection Support

### ISSUE THREAD

**Issue by IllMethods** [Radarr/Radarr#6861]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

It would be good if there was a page setup to view collections of movies in your list, that aren't monitored. Also movie collection suggestions, and an option to automatically monitor collections of added movies.

### Describe the solution you'd like

Add an extra page under Discover, for Collections and also add a checkbox option to automatically monitor collections of added / imported movies.

### Describe alternatives you've considered

going through my entire library looking for any collection check box that is not monitored :|

### Anything else?

I think it is described well enough.

[AB#2248](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2248)

**Comment by austinwbest** [comment]
I've started a collections page that is similar to season pass in sonarr. Will do most of this. Just have not got to finishing it yet

**Comment by IllMethods** [comment]
Oh awesome, I can't wait. Have you any thoughts on a check box to automatically monitor collections of imported movies?

**Comment by baloodusudouest** [comment]
To improve the collection tab, maybe it would be great to have the possibility to download collection information (fanart, folder, poster, theme...) like it's done with the movie

**Comment by IllMethods** [comment]
> I've started a collections page that is similar to season pass in sonarr. Will do most of this. Just have not got to finishing it yet

Is this in any of the branches yet?

**Comment by Qstick** [comment]
This issue will be closed when it's in a branch, given I assigned it to myself that generally indicates it'll be soon.

**Comment by xdpirate** [comment]
Can't wait for this to be merged and implemented in release, I found it really strange that I could add and monitor collections/lists but not see their actual contents. For the impatient like me, I made a userscript that adds a link to the collection add/edit dialogs that will open the collection page on TMDB. If you run Radarr on a different domain than localhost, edit the appropriate match lines in the script:

```
// ==UserScript==
// @name         Radarr View Collections
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  Add a link to view TMDB collections when adding/editing them in Radarr
// @author       xdpirate
// @license      GPLv3
// @match        http://localhost:7878/*
// @match        http://192.168.0.123:7878/*
// @icon         https://www.google.com/s2/favicons?sz=64&domain=radarr.video
// @grant        none
// ==/UserScript==

let mainBox = document.querySelector(`div[class^="Page-main-"]`);

let observer = new MutationObserver(function(event) {
    let collectionIdBox = document.querySelector(`input[type="text"][name="collectionId"]`);
    if(collectionIdBox) {
        if(collectionIdBox.RBLDetected !== "Detected") {
            collectionIdBox.RBLDetected = "Detected";

            if(collectionIdBox.value) {
                let modalHeader = document.querySelector(`div[class^="ModalHeader-modalHeader-"]`);
                let browseLink = document.createElement("span");
                browseLink.innerHTML = ` | <a target="_blank" href="https://www.themoviedb.org/collection/${collectionIdBox.value}#sort_menu">View collection on TMDB</a>`;
                modalHeader.append(browseLink);
            }
        }
    }
});

observer.observe(document, {subtree: true, childList: true});
```

https://greasyfork.org/en/scripts/443951-radarr-view-collections

**Comment by Qstick** [comment]
> Can't wait for this to be merged and implemented in release, I found it really strange that I could add and monitor collections/lists but not see their actual contents.

You can already see contents of lists and collections on discovery. This just makes collections a bit cleaner

**Comment by IllMethods** [comment]
Thank you for getting this done
