### ISSUE TITLE
Could Radarr please adopt the BTLS patch from Sonarr?

### ISSUE THREAD

**Issue by piejanssens** [Radarr/Radarr#6878]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

This would solve many: https://github.com/Radarr/Radarr/issues?q=btls (note: closed as stale, but not solved)

### Describe the solution you'd like

Implement the same patch that Sonarr uses.

https://github.com/Sonarr/Sonarr/blob/0d99c87d8739be8fdd5891bcbd9fd4c5c05542f4/src/Sonarr.RuntimePatches/Mono/BoringTLSVerifyFlagsPatch.cs

### Describe alternatives you've considered

There isn't any alternative for my CPU arch.

### Anything else?

Mono 5.20.1.34

[AB#2275](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2275)

**Comment by bakerboy448** [comment]
No Mono is no longer supported with v4

**Comment by piejanssens** [comment]
I am aware of that. I'm looking at the current released version as Radarr v4 is not out yet and many users would still benefit from this patch in Radarr v3... Can you please reconsider this?

**Comment by bakerboy448** [comment]
If you're on mono 6.10 or earlier - it's a non-issue.  That patch is only applicable to mono newer than 6.10

it will not solve your 5.20 SSL issue - that is due to out of date certs and needing to update either your system's certs and mono's certs or just needing to sync mono's certs.

Please use one of the support channels: [Reddit](https://www.reddit.com/r/radarr/) or  [Discord](https://radarr.video/discord) for support/questions.

**Comment by ta264** [comment]
The real solution is to upgrade your 3.1 install to the .net version.

There will be no more patches to 3.x.

**Comment by piejanssens** [comment]
Thanks @bakerboy448 @ta264. That would be preferred, yes. However, on some architectures such as armada370 Radarr with .NET Core will not run (at least not the version supplied by Synocommunity).

FYI Synocommunity is currently listing all of these as unsupported:

- powerpc ppc824x ppc853x ppc854x qoriq
- 88f6281
- hi3535
- evansport
- armada370 See https://github.com/SynoCommunity/spksrc/pull/4528

**Comment by ta264** [comment]
As I mentioned on the SynoCommunity PR, radarr is no longer supported on those platforms I'm afraid. Might be time to get a Pi4 or something if you don't have an alternative server

**Comment by piejanssens** [comment]
Your call, but I find it a pity, since it appears only to take a compiler flag and a separate build/release target.

**Comment by bakerboy448** [comment]
It's not at all that simple

Simply put it also takes a ton of additional code and hacky work arounds

**Comment by piejanssens** [comment]
@bakerboy448 I was more referring to https://github.com/dotnet/runtime/blob/main/docs/workflow/building/coreclr/cross-building.md#cross-compiling-coreclr-for-other-vfp-configurations in order to get .NET to work for Armada370

**Comment by bakerboy448** [comment]
> @bakerboy448 I was more referring to https://github.com/dotnet/runtime/blob/main/docs/workflow/building/coreclr/cross-building.md#cross-compiling-coreclr-for-other-vfp-configurations in order to get .NET to work for Armada370

Doesn't work

https://github.com/dotnet/runtime/issues/56706

**Comment by piejanssens** [comment]
I cannot see any references to the use of the flags (`-DCLR_ARM_FPU_TYPE=vfpv3-d16`) provided by MS to make .NET work on "armv7 CPU with VFPv3-d16" (showing MS is well aware of this armv7 subfamily), so I'm not sure this was ever tested by @publicarray when filing dotnet/runtime#56706

**Comment by piejanssens** [comment]
@bakerboy448 @publicarray says it would require a custom build .NET with those flags. Might be too much of a hassle.. Therefore, it would still be nice to have this Sonarr-like BTLS patch applied to Radarr too (you can keep it out of v4), so that at least, arm 16bit archs can enjoy Radarr on a mono versions > 5.8.

**Comment by ta264** [comment]
We have no plans to make any further releases on 3.x

**Comment by bakerboy448** [comment]
Again, the patch does not apply to any mono 5.X versions nor Mono < 6.10.

Unless you're running Mono > 6.10 then the proposed patch pull from Sonarr does nothing as it already exists and applies for the other versions.

Any SSL issues on Mono <= 6.10 is due to the user needing to update (sync) either their system's or mono's SSL certificates.

**Comment by piejanssens** [comment]
It looks like it does target 5.X and 6.X if I look at the comments: https://github.com/Sonarr/Sonarr/blob/0d99c87d8739be8fdd5891bcbd9fd4c5c05542f4/src/Sonarr.RuntimePatches/Mono/BoringTLSVerifyFlagsPatch.cs#L11

On 5.20.1.34-16 I did perform a sync (`/var/packages/mono/target/bin/cert-sync /etc/ssl/certs/ca-certificates.crt`), 
which didn't solve the Boring SSL verifyciation issue.

**Comment by ta264** [comment]
Yes it does target 5.x.

No we won't be adding it to radarr. Sorry.
