### ISSUE TITLE
Manual file rename

### ISSUE THREAD

**Issue by cinghialino** [Radarr/Radarr#6886]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

If you uncheck the rename feature you can't use the rename function manually. Not all movies needs to be renamed but having to go in the setting every time you need a file renamed is very inconvenient.

### Describe the solution you'd like

allow the rename feature to be used even when the automatic rename is disabled. A confirmation screen would be enough to warn the users.

### Describe alternatives you've considered

hand renaming. it sucks.

### Anything else?

nothing else.

[AB#2292](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2292)

**Comment by bakerboy448** [comment]
I'm not sure if this makes sense to implement.

If you told Radarr to never rename anything, then why would you want to rename anything?

**Comment by cinghialino** [comment]
Of course it make sense! Sometimes Radarr renames movies in English even when the original title is different, just because the UI is in English. Sometimes Radarr renames a movie when there's really no need for it, and it could add clutter to the filename. 

There isn't a "catchall" formula. I prefer to use the function (very useful) without the automatic setting.

**Comment by bakerboy448** [comment]
Radarr renames movies EXACTLY how you configure it to. So your reasons indicate configuration errors not really use cases.

**Comment by cinghialino** [comment]
I want the filenames in more than one language. Do you want me to change the UI every time I need to rename? 

Did I catch you in a bad mood? You don't have to do it but don't deny that there isn't a use case of it.

**Comment by bakerboy448** [comment]
The UI Language has no impact on the naming schema configured by the user.  So if you want movies in different languages then you already need to go in and change the language you selected the title to be renamed to, thus I don't particularly follow what you're doing as if you name movies in different languages you already need to go into settings and change the language.

Given that you want the movie's in different languages, is it that you want the movies renamed to be their original title? E.g. if it was originally French then use the French title, english, etc.

`{Movie OriginalTitle}` accomplishes that

**Comment by cinghialino** [comment]
I simply want to use two different languages overall, on a case by case use. I prefer to use English for my UI and the majority of the movies. If I use {Movie OriginalTitle}, since sometimes I watch a [third language] (say, russian) movies, it would include Cyrillic characters in my filenames and I wouldn't be able to find them when browsing the directories, hence it's best to leave the filename in English. Same thing for French movies, or Nordic movies, it becomes a true mess.

**Comment by bakerboy448** [comment]
File names have no impact on the folder names so there would be no issue with browsing directories.

Anyway will run it past the team and see if there's appetite for this.

**Comment by cinghialino** [comment]
Please do, thank you. I wish you a happy new year.

**Comment by Krandor1** [comment]
So you are wanting not just a manual rename option but a manual reanme option where you can also adjust all the settings on how it is renamed and not just format but language and other settings as well?

**Comment by cinghialino** [comment]
no. I meant to ask a manual rename button. Clicking on the "preview rename" shouldn't give you an error "Renaming is disabled, nothing to rename" just because it's not enabled for all the files. That's it. Some files need renaming, some do not.

**Comment by Krandor1** [comment]
But that won’t change the language like it sounds like you want.

**Comment by cinghialino** [comment]
I might not be able to describe it correctly, but the resistance I find in here is really toxic. 

Fuck this. It's just a suggestion what's the fucking deal? bUt iT doEsN't worK? 

it would be fucking better than having a button that doesn't do anything in the UI, wouldnt it? what's the point of showing it if it's not enabled anyway? jfc

I'm quite sure that it wouldn't be a groundbreaking change, but maybe for somebody it would be useful and for what? half a day of coding?

You know what? I'm gonna stop donating. Not because I don't get the feature I asked for but of the answers you guys give.

way to encourage feedback, good job.

**Comment by Krandor1** [comment]
It is more you are not clear on what you want. So you want the button to just rename based on current settings or let you adjust settings like language which you mentioned wanting to change?  
A request is only useful if very clear on what is wanted.

**Comment by cinghialino** [comment]
I just would like (not _want_) the "preview rename" button in the movie page to work independently from the "media management" setting "rename movies" in the "Movie naming" section. 

If this is not clear I don't know what else to do.

**Comment by Krandor1** [comment]
So no options to change languages or anything  else and simply just rename based on all the current settings?

**Comment by cinghialino** [comment]
you gotta be trolling. I'm done.

**Comment by Krandor1** [comment]
You were the one who brought up changing languages originally.  Just asking for clarification.  No need to be hostile.
