### ISSUE TITLE
Include Documentation For Advanced Connect Notification Options

### ISSUE THREAD

**Issue by ThePieMonster** [Radarr/Radarr#6896]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In the below documentation articles there is no mention of the advanced features or how they effect Discord notifications. 
https://wiki.servarr.com/radarr/settings#connections
![image](https://user-images.githubusercontent.com/11359134/148022011-057cfac8-cd7f-4cd4-af6d-cec8fb9c6f7b.png)

### Expected Behavior

I would like to see a example notification with the different parts of the image labeled. 

Example Discord notification:
![image](https://user-images.githubusercontent.com/11359134/148022557-f6bec20d-9c2c-4869-861f-fb73b9121cb6.png)

### Steps To Reproduce

View the documentation page linked above.

### Environment

```markdown
N/A
```

### What branch are you running?

Master

### Trace Logs?

N/A

[AB#2309](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2309)

**Comment by bakerboy448** [comment]
This is not a bug.

The wiki is always a work in progress and contributions are welcome.

**Comment by ThePieMonster** [comment]
@bakerboy448 Any chance someone could get a full discord alert image and label the different parts? I could add it to the documentation then myself. I however can't label the image as I don't know what parts are which (hence the request).

**Comment by austinwbest** [comment]
> @bakerboy448 Any chance someone could get a full discord alert image and label the different parts? I could add it to the documentation then myself. I however can't label the image as I don't know what parts are which (hence the request). 

Pretty sure the titles in the notification match the labels in radarr

**Comment by ThePieMonster** [comment]
@austinwbest what is the difference between poster art and fan art? I'm guessing one is the larger image on the bottom.

I wanted to modify the alert to not include the large image at the bottom but keep the one in the top right corner.

**Comment by austinwbest** [comment]
> @austinwbest what is the difference between poster art and fan art? I'm guessing one is the larger image on the bottom.
> 
> I wanted to modify the alert to not include the large image at the bottom but keep the one in the top right corner.

Poster is the poster (right of the notification)
