### ISSUE TITLE
Importing Movies from disk doesn't find any matches

### ISSUE THREAD

**Issue by bakthomas** [Radarr/Radarr#69]
When I do an import from disk, Radarr searches the folder I have selected, displays are movie folders, but dones't find matches for any movies.

Log or Console don't show any errors at all

[Info] Bootstrap: Starting Sonarr - C:\Program Files (x86)\Radarr\Radarr.Console
.exe - Version 0.2.0.18
[Info] MigrationLogger: *** Migrating data source=C:\ProgramData\Radarr\nzbdrone
.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=
3 ***
[Info] MigrationLogger: *** Migrating data source=C:\ProgramData\Radarr\logs.db;
cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 **
*
[Info] Router: Application mode: Interactive
[Info] OwinHostController: Listening on the following URLs:
[Info] OwinHostController:   http://*:7878/
[Info] NancyBootstrapper: Starting NzbDrone API
[Info] BrowserService: Starting default browser. http://localhost:7878
[Info] ProcessProvider: Opening URL [http://localhost:7878]
[Info] RssSyncService: Starting RSS Sync
[Warn] FetchAndParseRssService: No available indexers. check your configuration.

[Info] DownloadDecisionMaker: No results found
[Info] RssSyncService: RSS Sync Completed. Reports found: 0, Reports grabbed: 0

**Comment by bakthomas** [comment]
It appears to be a greater issue. I am unable to search a new movie I want to add.

**Comment by fedoranimus** [comment]
We're looking into it.

**Comment by CBers** [comment]
I was about to report the same, but I can confirm bakthomas's findings.

Running v0.2.0.18.

**Comment by galli-leo** [comment]
Should be fixed in the latest commit.

**Comment by fedoranimus** [comment]
Can you retest this on the latest version?

**Comment by evulhotdog** [comment]
@bakthomas Were you going to Wanted > Manual import? Can you walk us through how you were importing from disk?

**Comment by dawtmaytrikx** [comment]
I'm having this problem with movies that aren't being recognized by their release name. Plex occasionally has this issue, too but it also allows manually matching the file. Would be awesome if Radarr had that feature as well.

**Comment by fedoranimus** [comment]
@dawtmaytrikx You can manually match the file through the "Manual Import" on the "Wanted" Page.

Closing this issue for lack of response, will reopen if necessary.
