### ISSUE TITLE
Login screen redirects to `localhost` if accessing via reverse proxy in Radarr 4.

### ISSUE THREAD

**Issue by jamieshaw** [Radarr/Radarr#6906]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When attempting to access Radarr UI via reverse proxy, the user is redirected to `localhost` at the specified port.  After initial redirection, the URL can be corrected and remote access provided.  Similarly, the issue is elevated once logged in.  It seems to be the initial login screen request where the redirect happens.

Reverse proxy is a Apache config with SSL enabled. SSL is disabled in Radarr, being handled by the Reverse Proxy.

Current, unchanged config, previously working as expected as Radarr 3.  Broken by automatic installation of Radarr 4.

### Expected Behavior

The requested host to remain as requested, and not redirect to `localhost`.

### Environment

```markdown
- OS: macOS High Sierra 10.13
- Radarr: 4.0.0.5745
- Docker Install: No
- Using Reverse Proxy: Yes
- Browser: Safari 12
```

### What branch are you running?

Develop

### Trace Logs?

N/A

[AB#2314](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2314)

**Comment by ta264** [comment]
The proxy needs reconfiguring for radarr 4, in particular the `Host` header needs to be set, along with the `X-Forwarded-*` headers.

For more help join the discord channel.

**Comment by jamieshaw** [comment]
> The proxy needs reconfiguring for radarr 4, in particular the `Host` header needs to be set, along with the `X-Forwarded-*` headers.
> 
> For more help join the discord channel.

Thanks — think I might've jumped the gun on this one.  Digging through my reverse proxy config, I can see that I implicitly disable proxying the host for Sonarr/Radarr/Lidarr.  Seems this is fixed in Radarr 4, and as you say, my config needs updating to fix. 👍🏻
