### ISSUE TITLE
radarr_download_client variable not giving any output.

### ISSUE THREAD

**Issue by BaukeZwart** [Radarr/Radarr#6907]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`radarr_download_client` variable doesn't give any output on `Import` and `Upgrade`.
tested with nightly 4.0.1.5764, docker install.

tested this by adding the following to a Connections - Custom Script script.

```
echo "Download client: $radarr_download_client" > /config/logs/script.log
echo "Full path to the folder the episode file was imported from: $radarr_moviefile_sourcefolder" >> /config/logs/script.log
```
`$radarr_download_client` doesn't report anything
`$radarr_moviefile_sourcefolder` does report the full path.

### Expected Behavior

Expect the `radarr_download_client` variable to return the download client when used in a Connections - Custom Script script.

### Steps To Reproduce

use 

### Environment

```markdown
- OS: Synology DSM 7.0.1-42218
- Radarr: nightly 4.0.1.5772
- Docker Install: yes
- Using Reverse Proxy: yes (NPM)
- Browser: Chrome 96.0.4664.110
```

### What branch are you running?

Nightly

### Trace Logs?

[radarr.trace.txt](https://github.com/Radarr/Radarr/files/7821922/radarr.trace.txt)

[AB#2315](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2315)

**Comment by foux** [comment]
Do you have the issue on all events, or only particular ones? Because on `GRAB` events, I do have it populated

**Comment by BaukeZwart** [comment]
I use the variable on Import and upgrade but only tested on Import.
