### ISSUE TITLE
Have connect notify on move

### ISSUE THREAD

**Issue by edrock200** [Radarr/Radarr#6909]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Presently connect triggers on grab/import/delete/rename/upgrade, but doesn't appear to send a notification if an item is moved, e.g. moved from one root folder to another or has it's parent folder renamed. 

### Describe the solution you'd like

Add a connect trigger for moves that triggers for the source and destination folders.

### Describe alternatives you've considered

Have attempted all connect options but doesn't work in my testing. 

### Anything else?

Thanks in advance for your consideration.

[AB#2317](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2317)

**Comment by bakerboy448** [comment]
Related to / similar to https://github.com/Radarr/Radarr/issues/5487

**Comment by Qstick** [comment]
> Related to / similar to #5487

Yep, same thing
