### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by IllMethods** [Radarr/Radarr#6920]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Quality profiles, languages...

It would be good to be able to select more than one option, with the first one selected being the language it would download first. A lot of items would not download just because the language is wrong, but a lot of stuff (Mainly Anime Movies) has been dubbed in more than one language. 

### Describe the solution you'd like

So what I'm asking is for you to be able to select multiple languages, with the first language being the priority.

### Describe alternatives you've considered

Manually downloading them which isn't what an automated setup is all about.

### Anything else?

Thankyou for your time

[AB#2334](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2334)

**Comment by bakerboy448** [comment]
This already exists

any & Custom Formats 

https://wiki.servarr.com/radarr/faq#how-does-radarr-handle-foreign-movies-or-foreign-titles
