### ISSUE TITLE
Add "language" filter to manual search

### ISSUE THREAD

**Issue by jeff47** [Radarr/Radarr#6921]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

While several parameters (Indexer, Size, Seeders, etc) can be used to filter the releases when searching manually, "language" is missing.

### Describe the solution you'd like

Add option to filter releases by language in the manual search window.

### Describe alternatives you've considered

Sort by language instead

### Anything else?

<img width="1243" alt="Screen Shot 2022-01-09 at 11 54 38 AM" src="https://user-images.githubusercontent.com/7215369/148692317-d2b67fff-eea5-4312-bc3e-5fc802d8ba2f.png">

[AB#2335](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2335)

**Comment by zypherion** [comment]
Agreed, simple like a simple oversight. Given the application can pull the release language (which is generally accurate) I should be able to just click "filter" and add it to a custom filter template. Just came here to post this myself and am glad it's already been posted.
