### ISSUE TITLE
Better title searching in other language than English

### ISSUE THREAD

**Issue by przemekrr** [Radarr/Radarr#6922]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

When I want a movie with polish dubbing only small percent of torrents fulfills bazarr's title requirements. 5 years ago was also problem with titles and your fixed was "Radarr now searches for up to 5 alternative titles. This should fix this issue". In polish and I suppose other languages file names are (polish title)+(optional "-")+(English/Original title). You have added 4 extra titles and that is good but only in useful languages I don't need English, Chinese, Thai, French and Latvian titles rather I would like to have Original, English and Polish

### Describe the solution you'd like

The most important is to change language of additional titles it should be at least English, Original if it's not English and Movie Info Language from settings in most cases imdb have them only in translations.

also bazarr should check title in formulas:
-(Movie Info Language from settings title)+(" ")+(Original title)
-(Movie Info Language from settings title)+(" - ")+(English title)
-(Movie Info Language from settings title)+(" ")+(Original title)
-(Movie Info Language from settings title)+(" - ")+(English title)

### Describe alternatives you've considered

also it can take language from quality profile

### Anything else?

https://github.com/Radarr/Radarr/issues/334

https://www.themoviedb.org/movie/451048-jungle-cruise/titles
https://www.themoviedb.org/movie/451048-jungle-cruise/translations
en title: jungle cruise
pl title: Wyprawa do dżungli
<img width="1440" alt="Zrzut ekranu 2022-01-9 o 21 15 05" src="https://user-images.githubusercontent.com/33704264/148700197-31fb1300-3c49-4d88-b441-99f3c6d44d74.png">
<img width="1440" alt="Zrzut ekranu 2022-01-9 o 21 16 03" src="https://user-images.githubusercontent.com/33704264/148700202-83d90bf3-9eb1-4ee5-93cc-cf35303489bd.png">
<img width="1440" alt="Zrzut ekranu 2022-01-9 o 21 18 12" src="https://user-images.githubusercontent.com/33704264/148700203-e6d4f37d-f5e5-4daa-933c-b6a110b8296e.png">
<img width="1440" alt="Zrzut ekranu 2022-01-9 o 21 26 40" src="https://user-images.githubusercontent.com/33704264/148700204-3a89db81-ce98-465f-92c2-931986169f56.png">

[AB#2336](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2336)

**Comment by bakerboy448** [comment]
Does the existing functionality with Quality Profiles and Custom Formats not already cover this?  Also FYI the UI language settings have no bearing on how Radarr searches.

https://wiki.servarr.com/radarr/faq#how-does-radarr-handle-foreign-movies-or-foreign-titles

**Comment by przemekrr** [comment]
in Custom Format only useful in this situation is release Title - This is a regular expression matched against the release title and, after download, the filename on disk. (Note: Radarr only considers text after the movie title and year which means anything preceding the title is ignored.)
also I think it should be working out of the box rather than you should learn Custom Format and repair it for yourself
<img width="1440" alt="Zrzut ekranu 2022-01-9 o 22 02 13" src="https://user-images.githubusercontent.com/33704264/148701698-307991af-0e69-4e26-ad7e-992596b93528.png">

**Comment by bakerboy448** [comment]
- Custom Format `Release Title` would not be the correct condition to use and has no bearing on what languages are searched or preferred etc.
- Custom Format `Language` is what one needs to use
> Language - This language is matched against any language(s) Radarr parses. All languages previously selectable in profiles work here.

This is all explicitly noted in the FAQ entry linked.

**Comment by przemekrr** [comment]
custom format language is the same as language in quality profile it filters column "Language" my problem is that radarr is thinking that those results are not what he is looking for. Only problem is with name of the movie.
You can try to download movie Jungle Cruise in Polish language and it won't because non of the torrents meet all requirements(Polish language and correct title). All Polish torrents have different title. Radarr is searching for one of Jungle Cruise, 幻險森林奇航, ผจญภัยล่องป่ามหัศจรรย์, Croisière dans la jungle, Džungļu kruīzs but he gets Wyprawa do dżungli - Jungle Cruise and for him it is diferent movie so he is not downloading it.
<img width="1440" alt="Zrzut ekranu 2022-01-10 o 18 02 03" src="https://user-images.githubusercontent.com/33704264/148807216-6300bb59-63bc-400a-a825-2ad86b2152d1.png">
<img width="1440" alt="Zrzut ekranu 2022-01-10 o 18 01 51" src="https://user-images.githubusercontent.com/33704264/148807235-6c75dba4-eb69-4ac9-8382-1a741eb94035.png">
<img width="1440" alt="Zrzut ekranu 2022-01-10 o 17 59 40" src="https://user-images.githubusercontent.com/33704264/148807278-ef9a345f-dea0-4534-8be9-01f3aca9f26d.png">
<img width="1440" alt="Zrzut ekranu 2022-01-10 o 18 01 39" src="https://user-images.githubusercontent.com/33704264/148807316-52ca1f01-76fa-4766-9578-7cd148ffe0db.png">

**Comment by bakerboy448** [comment]
If TMDb does not have the translation for a movie - that is not a Radarr issue and TMDb needs to be updated.

Those releases are also not in a supported format and cannot be downloaded automatically. 

`Foreign Title - English Title` is not a valid standard by any means and not supported.  You'll need to search and grab manually if the release groups refuse to follow standard naming.

`Foreign Title aka English Title` support has been started in the develop and nightly branches.

**Comment by przemekrr** [comment]
I wrote that earlier
radarr titles for this movie are:
Jungle Cruise, 幻險森林奇航, ผจญภัยล่องป่ามหัศจรรย์, Croisière dans la jungle, Džungļu kruīzs
titles from tmdb https://www.themoviedb.org/movie/451048-jungle-cruise/titles
幻險森林奇航, ผจญภัยล่องป่ามหัศจรรย์, Croisière dans la jungle, Džungļu kruīzs
but there is another tab called translations and it contains titles in all language so there is a easy fix just download titles from titles tab and also download searching language title from translations tab
[https://www.themoviedb.org/movie/451048-jungle-cruise/translations](https://www.themoviedb.org/movie/451048-jungle-cruise/translations)

"Those releases are also not in a supported format and cannot be downloaded automatically."
so this is why I opened ticket in Feature request it will be nice to be able to download movies is different language than English, now downloading in languages like Polish doesn't work or there is only few torrents that meet those requirements
and also I wrote solutions it is very simple you have to add only 5 additional titles:
-(Movie Info Language from settings title)+(" ")+(Original title)
-(Movie Info Language from settings title)+(" - ")+(Original title)
-(Movie Info Language from settings title)+(" ")+(English title)
-(Movie Info Language from settings title)+(" - ")+(English title)
and also searching title form translations tab
Movie Info Language from settings title can be changed to searching title

**Comment by bakerboy448** [comment]
> able to download movies is different language than English, now downloading in languages like Polish doesn't work

This is not your feature request.  Your request is to parse poor, non-standard release names.  Languages and searching are not involved.

> -(Movie Info Language from settings title)

No plans to change searching to use the language from the Settings.  This is why the language in Quality Profiles and languages in Custom Formats exist.

Again, the settings in General have nothing to do with what is searched.

> but there is another tab called translations and it contains titles in all language so there is a easy fix just download titles from titles tab and also download searching language title from translations tab

- Search will use the Movie's Original Title, English Title, and Translated Title. No plans to change that.
- Note that the Translated Title (for the selected language in Quality Profile or Languages in Custom Formats) is already used 
- there is nothing to change here.  There are no `Translated Titles` within the Radarr GUI.  Alternative Titles are listed and are only used for parsing - not search terms.

Don't believe there are any plans to add support for poorly named releases that do not follow any standard e.g.
- `Wyprawa do dżungli - Jungle Book`
- `Wyprawa do dżungli Jungle Book`

You should talk to your tracker and/or the release groups and they need to follow the defined naming standards that exist - which is just the movie name...not multiple titles for it.  Russian Trackers and some others as well use AKA or a slash (`/`) to separate their names which is something that is a unique pattern and identifiable. 

If they did `Wyprawa do dżungli AKA Jungle Book` or `Wyprawa do dżungli / Jungle Book` instead of  ` ` and ` - ` that is something that is partially supported in develop & nightly and can be enhanced from there.

If they insist on their arguably poor nonstandard naming, then they cannot be automated  `-` is a common replacement for movies with a `:` in their name.
