### ISSUE TITLE
Language in movie title

### ISSUE THREAD

**Issue by Freeben666** [Radarr/Radarr#6923]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When a movie title contains a language name (e.g. "The French Dispatch (2021) ), it causes problems with the search. The matching function seems to stop at the language name (here matching only "The"). And all results are shown as being in the language in question.

### Expected Behavior

Radarr should properly match the movie title, even if a language name is in the title.

### Environment

```markdown
- OS: Linux
- Radarr: 3.2.2.5080-ls124 by linuxserver.io
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Firefox
```

### What branch are you running?

Master

### Trace Logs?

No trace log

[AB#2337](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2337)

**Comment by ta264** [comment]
Duplicate #6474

**Comment by Freeben666** [comment]
Thanks, I misssed it when I searched existing issues.
