### ISSUE TITLE
HD.DVD gets parsed as DVD

### ISSUE THREAD

**Issue by ItsME6969** [Radarr/Radarr#6925]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

"HD.DVD" gets parsed as DVD

### Expected Behavior

Parsed as BR-DISK since there is no actual Quality Definition for HDDVDs.

### Steps To Reproduce

!parse Random.Title.2010.1080p.HD.DVD.AVC.DDP.5.1-GRouP

### Environment

```markdown
- OS:linux
- Radarr:4.0.1.5813
- Docker Install:yes
- Using Reverse Proxy:no
- Browser:Chrome
```

### What branch are you running?

Develop

### Trace Logs?

!parse Random.Title.2010.1080p.HD.DVD.AVC.DDP.5.1-GRouP

[AB#2350](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2350)

**Comment by bakerboy448** [comment]
Don't believe we will want to add another quality.

Should this just be tested as BluRay480p ?

**Comment by austinwbest** [comment]
> Don't believe we will want to add another quality.
> 
> Should this just be tested as BluRay480p ?
> 
> A BR-Disk is effectively an image of the disk. Is that the case for HD-DVD releases?

Excepting that the release name shows 1080p and you're suggestion puts it to 480p

**Comment by ItsME6969** [comment]
HD-DVD (!= Bluray|DVD). It was supposed to be the DVD successor but it lost the battle to bluray. Currently FULL HDDVDs already get parsed as Bluray-1080p (even though they are a whole nother format) but the bug that I was referring to was that the radarr regex does not catch all HD.DVD variations. So a simple \bHD][_. -]?DVD\b to the bluray-1080p should do it.

**Comment by bakerboy448** [comment]
We already map HDDVD to BluRay

So this is an easy fix - will PR

**Comment by ItsME6969** [comment]
Thanks
