### ISSUE TITLE
Paginate list exclusions

### ISSUE THREAD

**Issue by scphantm** [Radarr/Radarr#6932]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

On the lists page, in my database, i have thousands of blocked movies as i use lists extensively.  My problem is that any time i go to the lists page, it takes several minutes to load the page due to the fact the browser is churning away trying to render a datagrid with thousands of rows in it.

### Describe the solution you'd like

The block list should be rendered in a datagrid.  Something with pagination, filtering\sorting, and rudimentary search. There are almost as many datagrid controls out there as there are javascript frameworks, any of them will do the job.  

For this, I'm not entirely sure the service needs to change.  I mean, it could change to paginate the results, but it doesn't have to.  it can dump the entire block list to the browser and just handle everything with javascript.  These rows are fairly simple.  

### Describe alternatives you've considered

currently, what i do is open the database in DataGrip, export the block list to a csv file, truncate the table, go into the lists page, do whatever i need to do with my lists, when I'm done, import the blocklist back into the table.

### Anything else?

nope

[AB#2362](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2362)

**Comment by bakerboy448** [comment]
related to https://github.com/Radarr/Radarr/issues/4846
