### ISSUE TITLE
Year in Title

### ISSUE THREAD

**Issue by ItsME6969** [Radarr/Radarr#6950]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Failed to map movie

### Expected Behavior

Map movie correctly

### Steps To Reproduce

Look for a movie with release year in the title. If the release year is the same as the release year, some uploaders wont bother repeating the year in the release name and thus wont be parsed correctly by radarr.
Example--> (Made up Title) Party Like it's 1999 (1999). 
No try parsing it
!Parse Party.Like.it's.1999.1080p.BluRay.x264-SoMEGroup
!Parse Party.Like.it's.1999.1999.1080p.BluRay.x264-SoMEGroup

The first will fail. Happens alot with concerts because concerts have the years in the titles

### Environment

```markdown
- OS: 
- Radarr:
- Docker Install:
- Using Reverse Proxy:
- Browser:
```

### What branch are you running?

Develop

### Trace Logs?

.

[AB#2400](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2400)

**Comment by bakerboy448** [comment]
Not a bug IMO.

All movies require the year to be parsed.

The movie title is `Party Like It's 1999` the 1999 is not the year in that case.

`Party Like It's` in 1999 would be what those releases match.

**Comment by ItsME6969** [comment]
I understand but like I said if the numbers in the Title (read year) and the year (it was released) happen to coincide, some groups will drop one of them bcoz maybe they saw it as redundant to have the same number twice.
Party.Like.it's.`1999.1999`.1080p.BluRay.x264-SoMEGroup
Might be wrong for them to do so in someone elses opinion or maybe not what radarr has been programmed to expect but it happens. So a fix for that would be for the parser to also expect that when the year in the release title is the same as the year it was released, treat that number also as the year. I've seen the issue pop up with a number of releases over time not just one otherwise I wouldn't have opened the issue. To easily see it reproduced yourself go to add new movie, and type in a year to see movies with that year in the actual title. Add any random one from the list that has the year in the title and year released be the same and do a search. It's almost guaranteed that atleast one releaser/release group will drop the year from the release name, maybe coz `they` thought it was redundant. Since you have removed the bug tag lets make it a feature suggestion then.
