### ISSUE TITLE
Add Name to `/system/status` API endpoint

### ISSUE THREAD

**Issue by angrycuban13** [Radarr/Radarr#6951]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Currently there is no easy way to differentiate between Sonarr and Radarr when hitting the `/system/status` API endpoint.

### Describe the solution you'd like

Add something that will differentiate Radarr from Sonarr when hitting `/system/status`

```json
{
"appname": Radarr
}
```

### Describe alternatives you've considered

Buying more IPAs for Q.

### Anything else?

No

[AB#2404](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2404)

**Comment by Qstick** [comment]
8fd6101
