### ISSUE TITLE
IMDB rating data not showing up

### ISSUE THREAD

**Issue by braytoni** [Radarr/Radarr#6960]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I upgraded my V3 Radarr installation to V4, I refreshed my library but noticed that ~10% of the movies are not correctly picking up their IMDB ratings.  I've isolated it to a clean installation with just two movies, Amadeus (1984) and Zootopia (2016), to illustrate the point.

![image](https://user-images.githubusercontent.com/28615628/150613556-a699c5ee-c5cf-493a-afcd-2c1f04904f68.png)

In this instance, Amadeus does not pick up the IMDB rating, but Zootopia does.

### Expected Behavior

I would expect that both Amadeus and Zootopia would get their IMDB rating.

### Steps To Reproduce

1. Created a Movies directory with the two movies in it.
2. In a freshly installed docker instance of 4.0.2.5836, with an empty /config directory, started the container.
3. Turned on Trace logging.
4. Movies --> Import directory with the two movies in it.
5. Movies --> click on each movie to see that one (Amadeus) did not get IMDB ratings, but the other (Zootopia) did.

### Environment

```markdown
- OS: Synology DSM 7.0.1.42218
- Radarr: 4.0.2.5836 (develop)
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Edge 97.0.1072.62
- Docker Compose:

version: '3.3'
services:
    radarr-test:
        image: linuxserver/radarr:develop
        container_name: radarr-test
        hostname: radarr
        restart: unless-stopped
        ports:
            - '7979:7878'
        volumes:
            - '/volume1/Media/Movies-Test:/data'
            - '/volume1/System/Radarr-Test:/config'
        environment:
            - PUID=1026
            - PGID=100
            - TZ=America/Los_Angeles
```

### What branch are you running?

Develop

### Trace Logs?

[radarr.trace.txt](https://github.com/Radarr/Radarr/files/7917183/radarr.trace.txt)

[AB#2423](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2423)

**Comment by bakerboy448** [comment]
Not a bug - the IMDb ratings won't show until the movies' cache expire on the metadata server

**Comment by braytoni** [comment]
Thanks.  That explains it.  Appreciate the quick response.
