### ISSUE TITLE
Lists: Change/Add IMDB list/watchlist

### ISSUE THREAD

**Issue by jOOc** [Radarr/Radarr#697]
Current IMDB preset "IMDB Wacthlist" example URL points to IMDB lists (http://rss.imdb.com/list/YOURLISTID)
![image](https://cloud.githubusercontent.com/assets/9382342/22841443/f2ed3f0e-efd1-11e6-8a6b-d86fad282188.png)

Maybe change this preset to just "IMBD list" and then add a new preset "IMDB Watchlist" with the URL as: http://rss.imdb.com/user/IMDBUSERID/watchlist

**Comment by onedr0p** [comment]
Done :)
