### ISSUE TITLE
IMDd Watchlist adds Mini Series

### ISSUE THREAD

**Issue by petwri** [Radarr/Radarr#699]
When on the same watchlist, rss import seems to add miniseries. Full TV Series are properly ignored, but everything IMDb considers a "Mini-Series" is imported. Would be happy if this could be fixed.

**Comment by onedr0p** [comment]
Do you have an example IMDb RSS list you care to share?

**Comment by petwri** [comment]
I don't wanna publish my watchlist here, but it's entries like 'Sonic Highways (2014 Mini-Series)' that cause the problem. I didn't dig through the code, but I assume you are only filtering IMDb entries for "TV Series" in the title, not "Mini-Series".
