### ISSUE TITLE
Optional upgrade until certain custom format(s) found

### ISSUE THREAD

**Issue by falcorr** [Radarr/Radarr#7001]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Radarr repeatedly downloading the same movie. The same release but also different releases. I'm also interested in the feature regardless - I think it'd be very useful. 

### Describe the solution you'd like

Profiles > Edit Quality Profile > [new] 'Upgrade Until Custom Format Found'

With a list like Custom Formats below it, but where they can be selected by checkbox. Could possibly also select custom formats that negate the rest and require the given desired score to be reached before stopping but that's not my primary request. 

While scoring custom formats is extremely useful, I'd also get a lot of utility out of this option alongside it. 

### Describe alternatives you've considered

Giving certain custom formats definitively large values but this would remove their intended use at the same time. 

### Anything else?

(This field probably shouldn't be required..)

[AB#2513](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2513)

**Comment by foux** [comment]
You can already do that by designing correctly your CF scores

**Comment by ta264** [comment]
No plans for this, just score your CFs appropriately.

**Comment by falcorr** [comment]
Kind of goes against the modular point of Custom Formats - it'd require duplicating terms for new super specific entries.

**Comment by ta264** [comment]
I disagree. Join the discord of you need help setting your scores properly

**Comment by falcorr** [comment]
Fair enough.

I think I've got the scores going more than properly! Below gets excellent results, for reasonable bitrate 1080p. And you may see why I would've liked the feature. 

![20220131_Radarr_quality_1080preasonablebitrate](https://user-images.githubusercontent.com/65019252/151746223-d513fe74-4a5f-4b97-9fd6-5b7711df070d.jpg)

**Comment by bakerboy448** [comment]
Your custom formats do not need to be duplicated like that - you can have multiple conditions in a single format.

Those seem extremely complicated and convoluted and there's almost certainly a better way to structure them and reduce duplicate scoring.

Swing by our discord to discuss further  or  [Discord](https://radarr.video/discord)
