### ISSUE TITLE
Media management 

### ISSUE THREAD

**Issue by patsaindon** [Radarr/Radarr#7006]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

The way I setup my media files is this way: YEAR/Movie Title (YEAR)/imdb_id.ext.

I still need my Couchpotato to rename my files because when I try to set up Radarr to duplicate my pattern, I'm asked for the movie title in the file name.

### Describe the solution you'd like

Being able to duplicate my media renaming pattern as it is, YEAR/Movie Title (YEAR)/imdb_id.ext.

### Describe alternatives you've considered

Use CP container

### Anything else?

No

[AB#2523](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2523)

**Comment by bakerboy448** [comment]
no plans to not allow no movie title in the movie file name

also please use more descriptive titles in the future.
