### ISSUE TITLE
When Enabling Renaming in Media Management then Disabling, Folders still get renamed

### ISSUE THREAD

**Issue by PrSinister** [Radarr/Radarr#701]
When i first installed Radarr, i enabled the renaming. When i noticed that the metadata wasn't being generated, i disabled the renaming so i could know the release name (source, group, language, proper or not) by looking at the folder but the folder still gets renamed when the setting is set to no.

**Comment by fedoranimus** [comment]
After rereading this issue, it's not a bug. It functions as designed.

Folders, by default, are named as `{Movie Title} ({Year})`. You would need to enable renaming to get a different name. Folder renaming is not supported, so the folders will not update once created.

Folder Renaming is an existing feature request, closing this issue.
