### ISSUE TITLE
Re-enable support for Jackett 'all' endpoint

### ISSUE THREAD

**Issue by ciberboy** [Radarr/Radarr#7010]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Feature exists and was very handy as it avoids configuring each indexer manually.

Can't understand the reason why the support was removed as it provided a way to avoid to configure each individual indexer.

### Describe the solution you'd like

Revert the removal of 'all' endpoint.

Instead of removing the support for the feature, enhance Jackett and Sonarr / Radarr interface to consider only the relevant indexers

### Describe alternatives you've considered

Revert to a previous version of Radarr

### Anything else?

Removal of the feature has been documented in the changelog.

Manually adding entries isn't an efficient solution.

Furthermore, I'm sure a lot of people weren't expecting this and currently their system doesn't work

[AB#2533](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2533)

**Comment by ta264** [comment]
No plans

**Comment by foux** [comment]
You can use Prowlarr, and you won't have to configure each indexer. Jackett `All`endpoint has only disadvantages : https://wiki.servarr.com/radarr/faq#jackett-all-endpoint

**Comment by ta264** [comment]
And for the record, existing setups will work, you just get a warning telling you to stop doing it.

For new setups, either add the indexers manually or use prowlarr which can add them all automatically to Radarr.

**Comment by ciberboy** [comment]
Going to try Prowlarr, but I don't see the need for change when Jackett was working perfectly fine. This is still a nightly and far for a fully developed system

**Comment by foux** [comment]
You can continue to use Jackett without issues, I was just advising Prowlarr to automatically configure your indexers.

> but I don't see the need for change

Did you even read the servarr link I provided?

**Comment by ciberboy** [comment]
Yes. I found that information even before I created this ticket. Prowlar looks promising, but still very far away in order to consider decom Jackett.

I have now configured Prowlar and it works
