### ISSUE TITLE
osx-arm64 4.0.4.5922 - killed

### ISSUE THREAD

**Issue by ppogorze** [Radarr/Radarr#7011]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I try to run core or app - process is killed instantly.
x64 version works.

### Expected Behavior

App should start.

### Steps To Reproduce

-

### Environment

```markdown
- OS: MacOS 12 Monterey
- Radarr: 4.0.4.5922 (Standalone)
- Docker Install: No
- Using Reverse Proxy: No
- Browser: -
```

### What branch are you running?

Master

### Trace Logs?

Nothing logged.
Process killed with 137 (-9)

[AB#2535](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2535)

**Comment by ta264** [comment]
You need to self-sign the executable for MacOS to allow it to run.  Apple making life difficult again...

**Comment by ppogorze** [comment]
So 'codesign --force --deep -s - Radarr.app' should do the trick, thanks.
