### ISSUE TITLE
Size over duration column in Library

### ISSUE THREAD

**Issue by eltharynd** [Radarr/Radarr#7018]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

no

### Describe the solution you'd like

It would be handy to have a column in Library with size on disk / length.
This way you can see which movies you want to find a lower bitrate version.

### Describe alternatives you've considered

Manually figuring it out 

### Anything else?

no

[AB#2554](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2554)

**Comment by bakerboy448** [comment]
No Plans for columns that are at the movie file attribute level due to eventually multi-edition support
