### ISSUE TITLE
Option to add "Original Language" column to Movies - Table View 

### ISSUE THREAD

**Issue by wellingssimon** [Radarr/Radarr#7019]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Just a feature I, and hopefully others, would find useful

### Describe the solution you'd like

Would like the option to add an Original Language column to the Movies - Table view. This could hopefully then also be used in Filters and Profiles.

### Describe alternatives you've considered

I've been unable to find a suitable alternative from the options currently available.

### Anything else?

Nothing further.

[AB#2561](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2561)

**Comment by bakerboy448** [comment]
Filters I can see. But what's the end goal here? Note that if implemented it would just be the movie's original language and nothing to do with the file.

Profiles - already exists for languages, so I don't know what you're looking for.

**Comment by wellingssimon** [comment]
@bakerboy448 I pull a lot of movies in from import lists. In some cases I probably don't want movies that are not originally English language. The ability to list all my movies and order by Original Language seemed like a nice feature to have so I could easily remove movies I do not require. I found OriginalLanguage column in Movies table so thought adding this option would be possible.  I accept that better organisation of my import lists would negate the need for this but that seems like unnecessary manual work if the relevant fields are already available in the database. I also realise the effort involved to implement this may outweigh the overall benefit to the wider Radarr user base. Appreciate you taking the time to request further information before dismissing it though :)
