### ISSUE TITLE
Requesting support for S3 object storage

### ISSUE THREAD

**Issue by ofersadan85** [Radarr/Radarr#7020]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I'm storing my media on S3 object storage buckets, which is currently the cheapest and most common solution (in cloud computing) for storage. Since Radarr only supports direct file system storage, it can be a real hassle to setup properly.

### Describe the solution you'd like

I'd love for there to be direct support for S3. Instead of setting up "root folders" for media, we should be able to set up root folders as S3 buckets, providing just the proper settings (links and credentials)

### Describe alternatives you've considered

Personally I have a working solution, by using Radarr as a docker container with a mapped volume, that volume is mapped on the host via Rclone mount to my S3 bucket. It's a real pain to set up properly, and it can still fail (for example, if rclone loses connection, or if files need to be renamed - which isn't directly supported on S3 without proper configuration).

### Anything else?

S3 is a very common storage solution these days, and is supported on all major platforms. It's very well documented and easy to work with as developers, while also being quite cheap for users as long-term storage.

While we're on the subject, this can even be extended to support other storage solutions! For example: integration with Google Drive or Microsoft's OneDrive. Maybe even Nextcloud and other similar options.

I'm imagining something like the following example under Settings -> Media Management:
<img width="284" alt="s3" src="https://user-images.githubusercontent.com/18385610/153200736-375f15ca-513d-405e-8c5b-ddfd105fd953.png">

Note - I've opened a related feature request here: https://github.com/Sonarr/Sonarr/issues/4891

[AB#2562](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2562)

**Comment by ta264** [comment]
No plans for this. Just use rclone if you must use remote storage.

**Comment by ofersadan85** [comment]
@ta264 Thank you for your quick reply. I realize there are currently no plans for this (why would we request features that are already planned?), but shouldn't the issue remain unclosed for a while to see if this feature is more widely requested/wanted by your users?

**Comment by DevYukine** [comment]
Well anybody running a similar setup to yours is already using rclone mounts and also it would add a lot of overhead to Radarr (or Sonarr looking at the issue you opened over there as well) because it would require

1. implementing the S3 spec
2. add caching and file system onto the "mount" (and handle it properly)

so why would radarr add a feature which already is working with the help of another software and introduce so much work/bloat inside when really its out of scope of radarr itself?
especially because rclone already does it perfectly fine and many users are running it like this
