### ISSUE TITLE
Replace upgraded CF items in queue for usenet

### ISSUE THREAD

**Issue by Silent-Remux** [Radarr/Radarr#7022]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

- item added to queue
- new higher CF hits
- new item added to queue 
- old one remains in queue potentially ahead of new one

### Describe the solution you'd like

New items to replace old items (or an option to turn on)

### Describe alternatives you've considered

delay profiles but they don't allow for this kind of flexibility

### Anything else?

Nothing I can think of.

[AB#2565](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2565)

**Comment by bakerboy448** [comment]
Not sure if we want this; if done for torrents it can cause a lot of hit and runs.

not sure on the effort for applying it to only Usenet, when delay profile serves the purpose

**Comment by bakerboy448** [comment]
Closing; delay profiles with custom format score bypass solve this usecase
