### ISSUE TITLE
Failed to create CoreCLR, HRESULT: 0x80004005 - Alpine 3.14.1 arm 32bit

### ISSUE THREAD

**Issue by radumamy** [Radarr/Radarr#7030]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

localhost:/opt/Radarr# ./Radarr -nobrowser            
Failed to create CoreCLR, HRESULT: 0x80004005

### Expected Behavior

Radarr doesn't launch. I had no issues using v3 Mono builds. 

### Environment

```markdown
- OS: Alpine 3.14.1 arm 32bit 
- Radarr:Radarr 4.0.4.5922 
- Docker Install: No 
- Using Reverse Proxy: No 
- Browser: N/A
```

### What branch are you running?

Master

### Trace Logs?

Doesn't log anything apart from above console output. 

[AB#2580](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2580)

**Comment by ta264** [comment]
Either your CPU is not supported or you have some other config issue.  Please come by the discord if you want to debug further.

**Comment by radumamy** [comment]
Fixed it with `export COMPlus_EnableDiagnostics=0`
