### ISSUE TITLE
"Ignore deleted movies" have no effect.

### ISSUE THREAD

**Issue by darzur** [Radarr/Radarr#704]
Hi,

With "Ignore deleted movies" enabled Radarr should unmonitor every movie that was previously grabbed, downloaded and then removed from disk. Good thing will be to mark it with special label like "archived" or something like this, but with green status.

Instead it just marks it as missing and keeps monitored. This leads to situation when after watching and deleting a movie Radarr will download it again.

**Comment by 4getit** [comment]
Right now, after a movie was successfully downloaded, watched and deleted, Radarr starts downloading again.

In my opinion, this is a rather large bug with no workaround. Is it possible to somehow give this more priority?

**Comment by onedr0p** [comment]
This is fixed in the nighties.
