### ISSUE TITLE
Mobile version shows different items than webversion

### ISSUE THREAD

**Issue by KillahInstinct1** [Radarr/Radarr#7042]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I open the mobile version of the web page, I get a different list in activity than when I open the same page on a desktop/laptop. I've tried different browsers too. It seems to somehow show an older version of caching, refreshing it and so on does not change it.

I've no idea how this would be possible.

### Expected Behavior

Webversion activity page is identical to mobile webversion.

### Steps To Reproduce

Go to /activity/queue on browser on phone, and do the same on PC/laptop.

### Environment

```markdown
- OS: Windows 10, Windows 11, Android 12.0 with Brave and Chrome
- Radarr: Version 4.0.4.5922
- Docker Install: not applicable, running stand-alone on Windows 11 (NUC)
- Using Reverse Proxy: no
- Browser: Brave, Chrome, Firefox, tried them all on both mobile as PC.
```

### What branch are you running?

Master

### Trace Logs?

I'm not sure how including logs here would help?

https://imgur.com/a/oCUWh42

[AB#2606](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2606)

**Comment by ta264** [comment]
Logs always help.

I would guess you have "show unknown items in queue" enabled on on browser but not the other.  Come by discord for further support.

**Comment by KillahInstinct1** [comment]
Ah yes that was it. Pretty sure I never set that option on either (I just found it) but this can be closed than. My bad - I feel dumb.
