### ISSUE TITLE
Adding movies via net import monitors but does not search.

### ISSUE THREAD

**Issue by VanCityGuy** [Radarr/Radarr#705]
It would be nice to have movies added via a list either searched for automatically, or have the option when importing selected, to have the button like when adding a movie manually. Give an option to import selected, and a little button beside/attached to it that will import and search at the same time.

As of now, when I add older movies through lists that I know are already released, I have to then go a search manually for them.

Thanks, loving this feature, it's so handy!

**Comment by onedr0p** [comment]
Something like 'Import and Search selected' alongside 'Imported selected'? 

For now you can use the wanted page to search the missing movies.

**Comment by VanCityGuy** [comment]
Ahh yes, I forgot all about that wanted page, but yes, 'Import and Search selected' alongside 'Imported selected' would be excellent!

**Comment by VanCityGuy** [comment]
I just thought about it, and it would also be great to have box for adding tags when creating a new list in the same area we choose profile, folder, link, etc.

**Comment by onedr0p** [comment]
Fixed in next release. It will just search if you have enabled auto sync. It will only search for the movies on the net import sync task.
