### ISSUE TITLE
Set chinese but notice webhook is english

### ISSUE THREAD

**Issue by yybinpitaya** [Radarr/Radarr#7070]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

my setting Set language is chinese,
 but  webhook notice Api language is english

### Expected Behavior

send my setting language

### Environment

```markdown
OS: Ubuntu 20.04
Radarr: Radarr 4.0.4.5922
Docker Install: Yes
Using Reverse Proxy: No
Browser: Chrome
```

### What branch are you running?

Master

### Trace Logs?

none

[AB#2656](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2656)

**Comment by bakerboy448** [comment]
There's no setting called "set language"

what are your language settings in the UI & for Movie Info

**Comment by yybinpitaya** [comment]
The message sent to me in webhook is in English, but both languages in my UI settings are set in Chinese.

**Comment by Qstick** [comment]
Dupe, #7023 covers language support for notifications
