### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by nydave69** [Radarr/Radarr#7072]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I noticed this morning that Radarr was using 52% of the CPU and 7GB of memory  I let it run and now

![image](https://user-images.githubusercontent.com/14140816/155620645-46027b91-b820-43e3-aa76-bb8b9735d92f.png)

It's the only application running with the OS...  Windows 7.
I can't even get a browser to open to shut it down.
Took 30 mins to load the resource monitor this evening.
CPU is now in the 10% range, everything else but memory looks normal.

Any thoughts?

### Expected Behavior

run normaly...

### Environment

```markdown
- OS: windows 7
- Radarr: latest 
- Docker Install:no
- Using Reverse Proxy:no
- Browser:chrome
```

### What branch are you running?

Master

### Trace Logs?

no access

[AB#2659](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2659)

**Comment by bakerboy448** [comment]
Without logs - which do not require radarr access, see the wiki link in the template - there is nothing at all to do here.

also Windows 7 is not supported by Microsoft and thus not officially supported for Radarr either

**Comment by nydave69** [comment]
[radarr.0.txt](https://github.com/Radarr/Radarr/files/8137156/radarr.0.txt)

NOTE: I to suspend Radarr to get to the logs

**Comment by RobinDadswell** [comment]
This is likely an issue with TLS support on Windows 7, please upgrade your OS to a supported OS and try again.

**Comment by nydave69** [comment]
Guess I'll crash it and see what happens...  Thanks for the help...
