### ISSUE TITLE
Radarr Fails to add new movies

### ISSUE THREAD

**Issue by BigBadBruins7478** [Radarr/Radarr#7108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

since receiving an upgrade, I am getting error messages whenever I try to add a new movie to my Radarr searches. 

Version
4.0.5.5981
.NET
Yes (6.0.1)
DB Migration
206

error is "couldn't find any results". This happens whether I search on a movie title or tmdb:xxxxxxx. 

Greg

### Expected Behavior

Expected behavior is how it used to work. You search for a movie that exists on imdb or tmdb and the radarr tool adds it to your list of movies to search. 

### Environment

```markdown
- OS: Windows 10
- Radarr:4.0.5.5981
- Docker Install:
- Using Reverse Proxy:
- Browser:Chrome
```

### What branch are you running?

Develop

### Trace Logs?

I don't have any logs

[AB#2756](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2756)

**Comment by Silent-Remux** [comment]
It is nothing to do with the new version. The search backend is having difficulties. Close your issue.
