### ISSUE TITLE
DKsubs is not included with hardcoded Subs

### ISSUE THREAD

**Issue by dan-the-man-nz** [Radarr/Radarr#711]
i believe you have a hardcoded list of hard coded subs terms built into radarr which it will reject

DKSubs does not appear to be included in the list, as radarr grabbed some releases with it.

example

MovieName.2016.DKSubs.BLUR.720p.HDRip.x264-UNiTAiL
MovieName.2012.Retail.DKSubs.720p.BluRay.x264-RAPiDCOWS

**Comment by simonk83** [comment]
Yep, I had to add this to my ignore list manually
