### ISSUE TITLE
Remux is missing from the option of Source on Conditions of Custom Formats

### ISSUE THREAD

**Issue by janusn** [Radarr/Radarr#7110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The option Remux is missing from the pull down menu of the Source of the Source Condition in the Custom Format of the Settings.

### Expected Behavior

The option Remux is show on the Source pull down menu of Source Condition of the Custom Format of the Settings.

### Steps To Reproduce

1. Click on the Settings from the left pane Hamburger.
2. Click on the Custom Formats.
3. Click the "+" on the Formats.
4. Click on the "+" on the Condition.
5. Choose Source.
6. Click on the Source pull down menu.

### Environment

```markdown
- OS: Synology DSM 7.0.1-42218 Update 2
- Radarr: 4.0.5.5981
- Docker Install: yes
- Using Reverse Proxy: No
- Browser: Google Chrome Version 98.0.4758.109 (Official Build) (x86_64)
```

### What branch are you running?

Master

### Trace Logs?

The Source Condition was shown at 1:43 PM.
No relevant log line is found.

<img width="715" alt="Screen Shot 2022-03-06 at 1 50 20 pm" src="https://user-images.githubusercontent.com/21253783/156926166-6b0d0c42-2ca1-4426-95fc-42923e1206f9.png">

[AB#2757](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2757)

**Comment by bakerboy448** [comment]
Remux is a quality modifier

**Comment by janusn** [comment]
Sorry. I have misread the settings.

Thanks for pointing it out.
