### ISSUE TITLE
Radarr insists on redownload of files that have been converted

### ISSUE THREAD

**Issue by gacopl** [Radarr/Radarr#7112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Radarr grabs an mkv realease
Radarr imports release
Custom script to convert release to mp4 is triggered by Connect
Convert finished from mkv-mp4, mkv gets deleted
Radarr picks up mp4 file under File tab
<img width="1247" alt="image" src="https://user-images.githubusercontent.com/2278688/156940666-b9fe5745-302a-4307-b47c-123b86b37793.png">
Radarr in history shows mkv as deleted
Radarr on next release at RSS will download new release even though mp4 exists and Radarr sees it under Files tab, whats worse it will grab any release even worse
<img width="1625" alt="image" src="https://user-images.githubusercontent.com/2278688/156940705-d91ed42d-31dd-4d23-8e21-49694207f396.png">

### Expected Behavior

Radarr grabs an mkv realease
Radarr imports release
Custom script to convert release to mp4
Convert finished from mkv-mp4, mkv gets deleted
Radarr picks up mp4 file under File tab
Radarr does not redownload unless it finds better release like Remux instead of WEB-DL

OR expose API to register converted file properly so Radarr will not redownload

### Environment

```markdown
- OS: Ubuntu 20.04
- Radarr: 4.0.5.5981
- Docker Install: yes
- Using Reverse Proxy: nginx
- Browser: not related
```

### What branch are you running?

Master

### Trace Logs?

[radarr.txt](https://github.com/Radarr/Radarr/files/8193434/radarr.txt)

[AB#2760](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2760)

**Comment by bakerboy448** [comment]
Looks like the on disk file has no custom formats and the upgrade/grab does.

**Comment by gacopl** [comment]
Well it's direct conversion to mp4, on disk mkv also does not have custom formats in name as its already renamed. So any kind of api to add that file to Radarr properly would be welcome. For now i will try to trick it with hard links to mp4, as i dont want to keep original mkvs

**Comment by ta264** [comment]
The issue is your file naming. When you delete the file radarr gets rid of the original release title which is driving the custom formats. Make the renamed file include custom formats and you should be ok I think.

The API exists if you want to dig into it and use it.

For any further discussion, please use discord since this is a support issue.

**Comment by gacopl** [comment]
sorry but i don't see a PUT here and its not support, if its not a bug it's an FR
<img width="528" alt="image" src="https://user-images.githubusercontent.com/2278688/156942617-a6c23228-853b-4ebd-b89f-9f7efc6ecbb6.png">

**Comment by bakerboy448** [comment]
Note that the API Docs are a perpetual work-in-progress and may not be complete. Contributions welcome. The best way to view see the API is to watch the network calls the frontend makes via the browser development network call console.

**Comment by gacopl** [comment]
Call me stubborn but please show me workflow in browser where i can click somewhere and add file to File to tab i would happily grab calls then in DT :) maybe there's an edit or maybe a full reimport of mp4 would make more sense ?

For anyone experiencing the same in future looks like truncating original file or hardlinking original mkv to mp4 workarounds the issue tricking radarr

**Comment by ta264** [comment]
Manual import

**Comment by gacopl** [comment]
Manual Import does not allow to set custom format tags
Also why when radar found new RSS release for that "missing file" it immediately grabbed THAT RSS release while there were others with higher score in cache (search tab)

**Comment by bakerboy448** [comment]
You could rename the mp4 to match the original file name (not the imported file name) and then do a manual import.

Custom format tags are never set. They are dynamically calculated from the file name and scene name (I.e. original file name)

**Comment by gacopl** [comment]
it would make most sense to make the conversion prior to import/renaming is there a way to hook between download and import? currently im running my script on Download and on Upgrade but it seems it happens after Import
