### ISSUE TITLE
Please port Radarr to ReadyNAS

### ISSUE THREAD

**Issue by lobbie1978** [Radarr/Radarr#7118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Hi guys,

Since CouchPotato for the ReadyNAS is pretty much dead, it would be great to develop Radarr for the Netgear ReadyNAS. These NAS boxes are still very much supported by Netgear with regular firmware updates and are very popular amongst a lot of people, including me ;)

### Describe the solution you'd like

I would like a one-click install app (*.deb) for the Netgear ReadyNAS.

### Describe alternatives you've considered

I've tried your Easy Install script on my ReadyNAS 102 (ARM) but it ends up with a "Arch not supported" error. There goes that. :(

### Anything else?

It'll be greatly appreciated :)

[AB#2773](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2773)

**Comment by lobbie1978** [comment]
https://community.netgear.com/t5/ReadyNAS-Storage-Apps-Current/Getting-started-as-a-developer/td-p/1283978

**Comment by lobbie1978** [comment]
https://github.com/ReadyNAS/sdk/wiki

**Comment by Qstick** [comment]
I was thinking ReadyNAS was debian based, if your box is arm32 you should be able to use the Radarr.master.4.0.5.5981.linux-core-arm.tar.gz binary and debian install instructions?

**Comment by lobbie1978** [comment]
> I was thinking ReadyNAS was debian based, if your box is arm32 you should be able to use the Radarr.master.4.0.5.5981.linux-core-arm.tar.gz binary and debian install instructions?

I tried the Debian install but it gives me a "arch not supported" error unfortunately.
The ReadyNAS community is not working on a port 👎

**Comment by ta264** [comment]
Did you do it manually or using the script on the wiki? I'd wager the script on the wiki doesn't work on Ready as.

**Comment by ta264** [comment]
For assistance installing please use the discord channel.

**Comment by lobbie1978** [comment]
> Did you do it manually or using the script on the wiki? I'd wager the script on the wiki doesn't work on Ready as.

I tried both. Manual and using the script. Both fail.

**Comment by ta264** [comment]
Please join the discord channel if you want us to assist further
