### ISSUE TITLE
Info and Warn Events filter not working

### ISSUE THREAD

**Issue by azumukupoe** [Radarr/Radarr#7119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

only the Error filter works properly
Info doesn't filter anything
Warn only filters out Info

### Expected Behavior

Info filter to show only Info items
Warn filter to show only Warn items

### Environment

```markdown
- OS: Windows 11 Pro
- Radarr: 4.0.5.5981
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Firefox 97.0.2 (64-bit)
```

### What branch are you running?

Master

### Trace Logs?

https://www.toptal.com/developers/hastebin/gajetataco.yaml/

[AB#2774](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2774)

**Comment by bakerboy448** [comment]
Not a but.

It's a hierarchical filter.

Info=info+warn+error
Warn=warn+error
