### ISSUE TITLE
Allow to find foreign movies with aphostrophes

### ISSUE THREAD

**Issue by finfa** [Radarr/Radarr#7121]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Kudos.

Yet another apostrophe issue.

I am aware of [4502](https://github.com/Radarr/Radarr/issues/4502), currently closed as resolved and locked.

I want to appeal to you and demonstrate that the problem is still open and impairing, and that **[4502](https://github.com/Radarr/Radarr/issues/4502) won't solve it**, despite of the resolution (kudos to the author, though).

The problem affects ITA and FRA titles and presumably other Latin-derived languages. 

To give you an idea of how frequent the problem is, consider that in Italian the equivalents of **_the_**, **_a_**, **_of_** get an apostrophe every time that they're followed by a vowel. That's a lot of apostrophes.

At the moment it's impossible to find all these movies.

For example, searching for the Italian _Ace Ventura L'acchiappanimali_:

```
03-07 22:45:33 Info Torznab search in Torlock for Ace Ventura Lacchiappanimali 1994 => Found 0 releases 
03-07 22:45:33 Info Torznab search in Zooqle for Ace Ventura Lacchiappanimali 1994 => Found 0 releases 
03-07 22:45:33 Info Torznab search in Il Corsaro Nero for Ace Ventura Lacchiappanimali 1994 => Found 0 releases 
03-07 22:45:34 Info Torznab search in 1337x for Ace Ventura Lacchiappanimali 1994 => Found 0 releases 
03-07 22:45:37 Info Torznab search in Il Corsaro Blu for Ace Ventura Lacchiappanimali 1994 => Found 0 releases 
03-07 23:56:13 Info Manual search in Il Corsaro Verde for Ace Ventura Lacchiappanimali 1994 => Found 0 releases
```
As you can see, **the problem affects every Indexer**.

Without merging words, releases are found:

```
03-07 23:49:34 Info Manual search in Torlock for Ace Ventura L acchiappanimali 1994 => Found 1 releases 
03-07 23:50:24 Info Manual search in Zooqle for Ace Ventura L acchiappanimali 1994 => Found 1 releases 
03-07 23:50:42 Info Manual search in Il Corsaro Nero for Ace Ventura L acchiappanimali 1994 => Found 0 releases 
03-07 23:51:15 Info Manual search in Il Corsaro Verde for Ace Ventura L acchiappanimali 1994 => Found 3 releases 
03-07 23:54:31 Info Manual search in The Pirate Bay for Ace Ventura Lacchiappanimali 1994 => Found 0 releases 
03-07 23:55:13 Info Manual search in 1337x for Ace Ventura L acchiappanimali 1994 => Found 4 releases 
```
_The problem happens because Radarr merges the words after removing the apostrophe (L'acchiappanimali => Lacchiappanimali). Instead, ITA/FRA movies are released as either _L'acchiappanimali_ or _L acchiappanimali_, and never as _Lacchiappanimali_ (for reasons). This results in a no-match._

**Why [4502](https://github.com/Radarr/Radarr/issues/4502) doesn't solve the problem?**

The main reason is, it proposes to enable raw search on **_some_** indexers (by asking the Prowlarr/Jackett devs case by case).

To find IT/FR releases we need instead to preserve the separation of apostrophed words for **_every_** indexer. 

As a matter of fact, Italian releases are often present on English trackers only, and not on Italian ones. Or they are present without seeders, just because of the sheer number of users, or because they were used to adopt international ones before local ones emerged.

In order to solve the issue through [4502](https://github.com/Radarr/Radarr/issues/4502), we would have to somehow set **_every_** indexer to raw search, which equals to disable sanitization globally.

And as you know, **this ain't gonna happen**. One reason being some English releases merge words (E.g. _It's_ => _its_, _Don't_ => _dont_). This Anglophone tradition is rather the exception, but also the majority).

Now, how to help the apostrophe-troubled minority? 

### Describe the solution you'd like

A global setting (advanced? disabled by default) to perform 2 searches in presence of apostrophes: one with ' => "" and one with ' => " ". This solves the problem once for all and has no downsides. Please correct me if I am wrong.

### Describe alternatives you've considered

**How to **NOT** solve the problem**:

- with [4502](https://github.com/Radarr/Radarr/issues/4502), as explained before, the problem affects all Indexers.
- with a setting in the Indexer. This would produce less to no results for English titles, preventing international users from finding and watching movies in English along with movies in their language.
- with a global setting that let you choose one approach OR the other. Same as above.
- solutions changing the search pattern, engine or involving all symbols. It's like treating dandruff by cutting off the head. The problem here is the apostrophe only, which is by far the most used non-inter-punctual symbol in western languages. It could deserve a special treatment in Radarr, the way the comparatively infrequent ampersand already has.

### Anything else?

Sorry for the lengthy report. I'm a big fan and it's such a pity that many foreign movies are out there and Radarr can't find them for a silly space.

[AB#2777](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2777)

**Comment by finfa** [comment]
> Please use one of the support channels: [Reddit](https://www.reddit.com/r/radarr/) or [Discord](https://radarr.video/discord) for support/questions.
> 
> #4502 does solve this
> 
> Indexers need to be reported as supporting/needing RawSearch to have their definitions updated for Prowlarr.
> 
> Jackett does not currently support RawSearch.

Hi @bakerboy448 , Help me understand:

- the problem affects every indexer
- not every indexer will support RawSearch
Therefore:
- the problem persists

Where am I wrong? Tnx

**Comment by finfa** [comment]
@bakerboy448 Sorry to insist, mybe it's my limit. But I still see a problem.

Say a tracker contains both Italian and English releases (common scenario).

- Its a wonderful life
- L'acchiappanimali

A) Tracker is enabled for RawSearch: aphostrophes are preserved in queries.
- English release missed with query "It's a wonderful life"
- Italian release found with query "L'acchiappanimali"

B) Tracker is not enabled for RawSearch: aphostrophes are stripped from queries.
- English release found with query "Its a wonderful life"
- Italian release missed with query "L'acchiappanimali"

How can RawSearch find both Italian and English releases?

**Comment by ta264** [comment]
Seems so.

Are you saying that Italian / french *titles* should always keep the space? If so thats something we should be able to achieve automatically.

Having an option to "fix" this is very much a last resort, it should *just work

**Comment by ta264** [comment]
Actually no, I don't think that is a valid example, because both titles work on zooqle with apostrophes, so it just needs raw search enabled

**Comment by finfa** [comment]
An example where RawSearch would not satisfy both: Limetorrent "Don't Look Up 2021" and "Ace Ventura L'Acchiappanimali 1994". Leaving or stripping hyphens on Limetorrent leads to different results:

Query with stripped apostrophe:
English top release seeders: 2,642
Italian: 0

Query with apostrophe:
English top release seeders: 168
Italian: 1

Limeotrrent replaces the apostrophe with a space and then performs exact match.

If I would spend enough time it's reasonable to assume that I would find cases where IT or EN releases are not found

**Comment by finfa** [comment]
> Actually no, I don't think that is a valid example, because both titles work on zooqle with apostrophes, so it just needs raw search enabled

@ta264 I agree with you for Zoogle, but my latest example on Limetorrents should be valid. It's reasonable to think, that if I continue testing I will find other trackers that behave like Limetorrents.

Solving the Italian problem in Limetorrent with RawSearch would go in disfavor of English searches.

If you want to favor both Italian and English searches all the times, then you cannot decide in advance which pattern to use for which tracker. 
 
> Seems so.
> 
> Are you saying that Italian / french _titles_ should always keep the space? If so thats something we should be able to achieve automatically.
> 
> Having an option to "fix" this is very much a last resort, it should _just work_ if at all possible

Yes. That would help, but not 100% of the cases. The reality is that non-English releases are far less disciplined in their titles. Especially for old stuff. To aggravate this, the general scarcity of releases does not allow for a single miss. And I talk also about private trackers. They usually have just one release per movie.

Something that would really help is to have somehow both "stripped" and "spaced" queries for Italian and French titles in presence of apostrophes. This would maximize the chances to find releases on apostrophe-sensitive trackers like Limetorrents without penalizing English searches.

**Comment by bakerboy448** [comment]
Doubling the API calls for every single indexer due to a small percentage sucking at searching themselves does not make any sense.

LimeTorrents is also one of several notoriously crappy public trackers - including lying about seeds as well fwiw.

**Comment by finfa** [comment]
@bakerboy448 I agree with you, but that's the situation. I am not talking about doubling all requests. I am talking of only doubling few requests that contain apostrophes for those foreigners that manage to find and feel the need to enabled that option.

**Comment by finfa** [comment]
@bakerboy448 the reason I am using Radarr is not because I suck at searching. It's because I don't _want_ to search :) . I have no time for it. Also I don't thin it's a good use of time to discuss whether or not to enable or disable an apostrophe on every given tracker, one by one. And I also don't like solutions where someone has to lose, even if in minority. I prefer win-win solutions.

**Comment by bakerboy448** [comment]
No one said anything about you searching?  Only that the trackers themselves suck at internal searching. They should follow the rest of the world and not require rawsearch....let alone being inconsistent across languages as you pointed out (which goes back to the same root cause - indexers having poor internal search methods)

This is primarily only a problem with public trackers - that lie about seeds anyway - and a tiny handful of private trackers which all known/reported ones have been fixed in Prowlarr at this point.  

Every other decent tracker supports Id based searches which makes this all moot.

**Comment by finfa** [comment]
Sorry, misunderstanding.

Now everything is clear. I am the noob obsessing about garbage :) I didn't know they were lying about seeders, but it's not hard to believe now. I will get rid of them. Thank you for the lesson. Receiving it directly form a member of the Radarr team is a privilege for the few.
