### ISSUE TITLE
Sending Command using API fails with Unsupported Media Type 415 error

### ISSUE THREAD

**Issue by euphoria360** [Radarr/Radarr#7122]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using cron and i was sending scheduled CURL command for searching missing movies:

`curl -X POST "http://localhost:7878/api/v3/command?apikey=abcdefabcdef123456789abcdef1234" -H "accept: application/json" -d '{"name": "MissingMoviesSearch", "filterKey": "monitored", "filterValue": "true"}'`

this was working since recently, now it fails with the following response:
```
{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.13",
  "title": "Unsupported Media Type",
  "status": 415,
  "traceId": "00-1bdf6fd317c09f4901e97cddc00f3796-15c62810df35eefb-00"
}
```

### Expected Behavior

successful JSON responce

### Steps To Reproduce

1. open up a terminal with CURL installed.
2. Run: `curl -X POST "http://localhost:7878/api/v3/command?apikey=yourapihere" -H "accept: application/json" -d '{"name": "MissingMoviesSearch", "filterKey": "monitored", "filterValue": "true"}'`

### Environment

```markdown
- OS: Debian Buster
- Radarr: 4.0.5.5981
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Google Chrome
```

### What branch are you running?

Master

### Trace Logs?

Only log with related timestamp was this:

2022-03-08 21:16:02.3|Info|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was challenged.

[AB#2779](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2779)

**Comment by ta264** [comment]
You need to set the content type header to `application/json`

**Comment by y0un3s3a** [comment]
> 2\. "name": "MissingMoviesSearch", "filterKey": "monitored", "filterValue": "true"

This is correct. The command would be:

`sudo curl -X POST -s "http://localhost:7878/api/v3/command?apikey=APIKEY" -H "Content-Type: application/json" -d '{"name": "MissingMoviesSearch", "filterKey": "monitored", "filterValue": "true"}'
`



If somebody ever crosses this and wants to use the API to recursively import you can do this:

This would be the command to import 1 folder in Radarr via API:

`sudo curl -X POST -s "http://localhost:7878/api/v3/command?apikey=APIKEY" -H "Content-Type: application/json" -d '{"name": "DownloadedMoviesScan", "importMode": "Move", "path": "PATHFOLDERTOIMPORT"}'`


This would recursively import folders from '/home/data/downloads/completed/movies/' in Radarr via API:

`for d in /home/data/downloads/completed/movies/*;  do  pathname=$d; sudo curl -X POST -s "http://localhost:7878/api/v3/command?apikey=APIKEY" -H "Content-Type: application/json" -d '{"name": "DownloadedMoviesScan", "importMode": "Move", "path": "'"$pathname"'"}'; done; `
