### ISSUE TITLE
Add custom filter to filter the "Status" of releases

### ISSUE THREAD

**Issue by thezak48** [Radarr/Radarr#7124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

When I try to show only Missing releases it shows "Missing, Downloading and Not Available"

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/1936903/157444276-473aa0cb-6b12-487b-8cfa-37c16a698e73.png)
Add a Status filter to the list so that you can show only "Missing" Unlike the default one that shows "Missing" but also "Downloading" and "Not Available" as shown below
![image](https://user-images.githubusercontent.com/1936903/157445140-17a16d3e-3be0-44b3-9e6c-28514c82342a.png)

### Describe alternatives you've considered

N/A

### Anything else?

Naaaa

[AB#2780](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2780)

**Comment by Qstick** [comment]
Dupe #5004
