### ISSUE TITLE
Radarr does not support dragging profile quality ranking preferences on mobile browsers

### ISSUE THREAD

**Issue by ajax-lives** [Radarr/Radarr#7136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you go to a profile on Radarr via mobile browser - and try to drag a quality up or down, nothing happens.  However, if you hold it down, it'll do the "pick up" animation, but then it does not actually allow you to move or slot it, and instead is stuck on screen.

### Expected Behavior

When you go to a profile on Radarr via mobile browser - and try to drag a quality up or down, nothing happens.  However, if you hold it down, it'll do the "pick up" animation, but then it does not actually allow you to move or slot it, and instead is stuck on screen.

I'd expect that I'd able to move it, and then slot it down where I want it in my rankings.  This is currently doable in Sonarr, so I'm guessing it shouldn't be **too much** more, than some copy + reformat + refactor.

### Steps To Reproduce

1. Open Radarr on Mobile
2. Go to "Profiles"
3. Open a Profile
4. Try to drag a quality

### Environment

```markdown
- OS: Android/iOS
- Radarr: Yes
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Mobile Chrome (Someone mentioned similar behavior on Safari)
```

### What branch are you running?

Master

### Trace Logs?

Not applicable.

[AB#2796](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2796)

**Comment by ajax-lives** [comment]
Fix pls pls pls fix fix fix fix pls pls pls

**Comment by bakerboy448** [comment]
Spamming a GitHub issue does not increase how quickly it is fixed or when it is worked on.

**Comment by ajax-lives** [comment]
We all have dreams, Bakey!

**Comment by Qstick** [comment]
https://github.com/Radarr/Radarr/commit/17fda02d8c5830f64a6d51bbc2db66cf248cbede
