### ISSUE TITLE
Synology Download Station

### ISSUE THREAD

**Issue by foXaCe** [Radarr/Radarr#715]
Hello, please it possible to add this ?

https://github.com/Sonarr/Sonarr/commit/82a99b7f806fbfb756ae5fe1296fb45c2047a9cb

**Comment by margaale** [comment]
Hi, feel free to contact me if you need any help.

**Comment by onedr0p** [comment]
It should be as easy as copying the files over to Radarr. I'll look into this when I have time.

**Comment by onedr0p** [comment]
Actually, just did it :) test it out and let me know if it works!

**Comment by kevincork** [comment]
I don't see Synology Download Station from the list, was that removed?
