### ISSUE TITLE
Custom Format - Expand Title Custom Formats Uses (Regex Enhancment)

### ISSUE THREAD

**Issue by ItsME6969** [Radarr/Radarr#7151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Currently the regex works but not to its full potential given that it filters out and works only on part of the complete release title.
I had discussed with @ta264 a while back on [discord](https://discord.com/channels/264387956343570434/264388019585286144/911531940639830026) and he noted that he would look into creating an extra function to work on the unfiltered title. So I'm just creating this suggestion as a reminder incase it was forgetten.
Other bug reports that involve regex that can be solved and closed if this suggestion were implemented;
https://github.com/Radarr/Radarr/issues/4859
https://github.com/Radarr/Radarr/issues/6824

### Describe the solution you'd like

An extra option in the Regex "Conditions" options that works on the `unfiltered` title.

### Describe alternatives you've considered

.

### Anything else?

.

[AB#2838](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2838)

**Comment by bakerboy448** [comment]
Closing as covered in https://github.com/Radarr/Radarr/issues/4859
https://github.com/Radarr/Radarr/issues/6824
