### ISSUE TITLE
 Library: Show current 'profile' under posters (as in currently SD/HD/etc.), not WANTED profile.

### ISSUE THREAD

**Issue by YouveGotMeowxy** [Radarr/Radarr#7156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

In the main library screen, you can choose to show "profile" under each poster.

So for example, I create a profile to fetch HD/UHD, regardless  of what the file *currently* is (lets say it's currently SD), it'll just show "HD/UHD" under the poster. This can get confusing and uninformative, when you want to just look over the list to see which are currently SD and you want to add them to your HD profile; especially after a bulk library import, or if you're looking through to see whether they've been upgraded yet.

example: Not all of these movies are in fact already HD/UHD, but I've chosen to have Radarr upgrad them until they are; but the label ONLY shows HD/UHD under them:

![image](https://user-images.githubusercontent.com/39491297/159951009-a303340c-a374-4585-8216-4bca0617d366.png)

### Describe the solution you'd like

I'd like an option to also show what the file *currently* is. So if the file is *currently* SD, it'll show "SD" under the poster.

Perhaps add an ability to create our own tags to display under posters? IN this case, we could choose to show a resolution label under posters.

### Describe alternatives you've considered

None

### Anything else?

Nope!

[AB#2844](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2844)

**Comment by austinwbest** [comment]
Anything related to file properties is not something that is going to be used for sorting, searching, tags, etc at this time.
