### ISSUE TITLE
Importing Enhancements

### ISSUE THREAD

**Issue by YouveGotMeowxy** [Radarr/Radarr#7157]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

The importing page is pretty basic.

1. There's no ability to simply select/unselect all (see screenshot)
2. Plex uses Collection folders for great, neat and clean organization and reading of its movies; Radarr see's none of those due to them being in subfolders (weird) (see screenshot)
3. I noticed whilst importing a large library for the first time, many movies weren't matched properly, and I couldn't tell which to manually select them as. I had to go back to my remote machine via RDP and look in File Explorer to be able to tell.
This is especially noticeable with movies that have the same name, but were released in different years, for example later remakes.
4. No ability to tell a movie's current resolution, to help decide WHILE importing whether to select to monitor it or not.

### Describe the solution you'd like

1. The usual click the box in the column header to select/unselect all.
2. Simply do a recursive search through all folders while scanning? I don't need to see the folder structure reflected on the Library page; I just want the importer to "see" them so I can add them. Nothing fancy or special here.
3. Simply add a column showing it's path, like you do in the library list:

![image](https://user-images.githubusercontent.com/39491297/159955749-32c60b86-d8cb-4658-99d7-19bc5f5eb6e9.png)

4. In the screenshot I highlighted at the middle-top where the above column, and this column could go. One of the columns would be the current file's resolution (let's say it's currently an SD movie), THEN we'd easily be able to see whether or not we want to choose "yes or now" in the Monitor field. Currently there's no way to tell whether or not we want to upgrade (sometimes we don't) w/out referring to the actual folder itself (my server is remote, and I have to RDP into it, which for things like this can be a PITA).

### Describe alternatives you've considered

None

### Anything else?

Screenshot:

![image](https://user-images.githubusercontent.com/39491297/159956600-34e8f23e-75bb-44a6-8f08-a8b0d38bd5d7.png)

[AB#2845](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2845)

**Comment by bakerboy448** [comment]
> There's no ability to simply select/unselect all (see screenshot) || The usual click the box in the column header to select/unselect all.

This exists and is at the top of the page.  You simply needed to wait for Radarr to finish processing.
![image](https://user-images.githubusercontent.com/55419169/159959429-b4523b7f-e1aa-44d9-955e-c1b846d6fb6c.png)

> Simply do a recursive search through all folders while scanning? I don't need to see the folder structure reflected on the Library page; I just want the importer to "see" them so I can add them. Nothing fancy or special here.

Covered under https://github.com/Radarr/Radarr/issues/1170

>Simply add a column showing it's path, like you do in the library list:

Why is this needed? You already have the folder name?

> No ability to tell a movie's current resolution, to help decide WHILE importing whether to select to monitor it or not.

agreed, This would be useful

**Comment by austinwbest** [comment]
The checkbox is disabled because there is nothing matched to import. Movies have to be matched first to something in radarr before the related checkbox enables.

**Comment by bakerboy448** [comment]
Thinking it through;  at this time displaying movie file properties even on library import is likely not something to explore at this time as it may conflict with the future eventual multi-edition support.

Closing since the comments cover the existing features
