### ISSUE TITLE
BluRay/BMDV support

### ISSUE THREAD

**Issue by danpowell88** [Radarr/Radarr#717]
Radarr can see the folders are there and identifies the movie but cannot find any files and marks it as missing.

Folder structure looks as follows
```
Movies (Year)/BMDV/
Movies (Year)/CERTIFICATE/
Movies (Year)/QT4_UPDATE/
Movies (Year)/QT4_VPRM/
Movies (Year)/QT4_DISC.SFB
```

**Comment by onedr0p** [comment]
Is that folder structure standard to bd-disk?

**Comment by woble** [comment]
Seems like it. Should be BDMV though.

https://en.wikipedia.org/wiki/Blu-ray#Directory_and_file_structure

**Comment by Amelsfort** [comment]
I also asked for this feature and was asked to create a request at feathub: http://feathub.com/Radarr/Radarr/+85

**Comment by galli-leo** [comment]
@willsthompson There are other issues already open for this. Search for iso support

**Comment by willsthompson** [comment]
@galli-leo Gotcha. For anyone who stumbles across this issue, see #809.
