### ISSUE TITLE
Wrong video codec displayed

### ISSUE THREAD

**Issue by acrane1** [Radarr/Radarr#7170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Radarr is reported the file as h264 for the video codec. when file is actually H265
![20220329204507690](https://user-images.githubusercontent.com/6483954/160703958-04e544d0-1bdd-4665-ad83-67e368d498e2.jpeg)
![20220329204453262](https://user-images.githubusercontent.com/6483954/160703979-0668bbf8-f678-4b0e-8f0e-5eb0c6d165db.jpeg)

### Expected Behavior

Radarr should show H265 under video codec

### Steps To Reproduce

Converted Media from x264 to x265
moved file from conversion folder to target folder, overriding existing file. Preserving original filename
Ran Refresh and scan on movie

Also tried to resolve by enabling Analyze video files under Settings > File Mangement.

### Environment

```markdown
- OS: Unraid 6.9.2
- Radarr: Version 4.0.5.5981
- Docker Install: Yes
- Using Reverse Proxy: no
- Browser: Chrome
```

### What branch are you running?

Master

### Trace Logs?

![20220329204453262](https://user-images.githubusercontent.com/6483954/160704760-06787531-e595-40b3-92b4-d74e79a0120c.jpeg)
![20220329204507690](https://user-images.githubusercontent.com/6483954/160704772-67d6bb90-870d-4629-ae78-115e7b00279a.jpeg)

[AB#2880](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2880)

**Comment by bakerboy448** [comment]
Files are only rescanned for media info if the name changes or the file size changes.

This also requires the user to have the default rescan settings enabled as well.
