### ISSUE TITLE
Radarr snap package

### ISSUE THREAD

**Issue by kinekt4** [Radarr/Radarr#7172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

There is currently no snap package for radarr.

### Describe the solution you'd like

This issue has been raised before: #2735 

But it was raised before a snap package for `sonarr` was implemented,

* https://snapcraft.io/sonarr
* https://github.com/albertodonato/sonarr-snap

I assume they are similar so it might be easy to implement.

### Describe alternatives you've considered

* Docker

### Anything else?

* https://snapcraft.io/sonarr
* https://github.com/albertodonato/sonarr-snap

[AB#2888](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2888)

**Comment by bakerboy448** [comment]
Sonarr snap packages are unofficial and not maintained nor created by the Sonarr team.

Don't think there are any plans for a first-party snap package as well; will defer to the others on that

**Comment by Qstick** [comment]
We'd be more than happy to accept some help on this from someone but we don't plan to do it ourselves anytime soon

**Comment by kinekt4** [comment]
Thanks for your consideration. I've never built a snap package before but I might look into it.

**Comment by Qstick** [comment]
We'd be happy to support with answers to any questions related to our binaries, afraid we just don't have time. 

Jump on discord if you want to talk and we can get it sorted if you are interested in maintaining.
