### ISSUE TITLE
Postgres migration unique constraint violation

### ISSUE THREAD

**Issue by TheSpad** [Radarr/Radarr#7178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Trying to migrate an existing sqlite db into postgres with pgloader generates the following errors:
```
2022-04-03T11:13:40.516000Z ERROR Database error 23505: duplicate key value violates unique constraint "PK_Metadata"
DETAIL: Key ("Id")=(1) already exists.
CONTEXT: COPY Metadata, line 1
2022-04-03T11:13:40.592000Z ERROR Database error 23505: duplicate key value violates unique constraint "PK_DelayProfiles"
DETAIL: Key ("Id")=(1) already exists.
CONTEXT: COPY DelayProfiles, line 1
2022-04-03T11:13:40.624000Z ERROR Database error 23505: duplicate key value violates unique constraint "UC_Version"
DETAIL: Key ("Version")=(1) already exists.
CONTEXT: COPY VersionInfo, line 1
2022-04-03T11:13:40.644000Z ERROR Database error 23505: duplicate key value violates unique constraint "PK_ScheduledTasks"
DETAIL: Key ("Id")=(3) already exists.
CONTEXT: COPY ScheduledTasks, line 1
2022-04-03T11:13:40.848000Z ERROR Database error 23505: duplicate key value violates unique constraint "PK_QualityDefinitions"
DETAIL: Key ("Id")=(1) already exists.
CONTEXT: COPY QualityDefinitions, line 1
2022-04-03T11:13:43.055999Z ERROR Database error 23505: duplicate key value violates unique constraint "PK_Profiles"
DETAIL: Key ("Id")=(3) already exists.
```
Loading Radarr after this import results in
![image](https://user-images.githubusercontent.com/8425502/161425182-6ef56390-f29a-40e6-832d-23ff9f096465.png)
and none of the menu items loading correctly.

### Expected Behavior

Import of an existing sqlite database into postgres should succeed.

### Steps To Reproduce

1. Pre-create postgres databases `radarr-main` & `radarr-log`
2. Update config.xml and start radarr to create schema
3. Shut down radarr and run `pgloader --with "quote identifiers" --with "data only" ./radarr.db 'postgresql://arr:arr@localhost/radarr-main'`
4. -key constraint errors occur here-
5. Start radarr
6. Load webui
7. -key not present errors occur here-

### Environment

```markdown
- OS: Ubuntu 20.04.4
- Radarr: nightly-4.1.0.6133
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: N/A
- pgloader 3.6
```

### What branch are you running?

Nightly

### Trace Logs?

radarr  | [Fatal] RadarrErrorPipeline: Request Failed. GET /api/v3/movie 
radarr  | 
radarr  | [v4.1.0.6133] System.Collections.Generic.KeyNotFoundException: The given key '7' was not present in the dictionary.
radarr  |    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
radarr  |    at NzbDrone.Core.Movies.MovieRepository.<>c__DisplayClass6_0.<All>b__5(Movie movie, MovieFile file) in D:\a\1\s\src\NzbDrone.Core\Movies\MovieRepository.cs:line 110
radarr  |    at NzbDrone.Core.Datastore.SqlMapperExtensions.<>c__DisplayClass1_0`3.<Query>g__MapWithLazy|0(TFirst first, TSecond second) in D:\a\1\s\src\NzbDrone.Core\Datastore\Extensions\SqlMapperExtensions.cs:line 43
radarr  |    at Dapper.SqlMapper.<>c__DisplayClass160_0`8.<GenerateMapper>b__0(IDataReader r) in /_/Dapper/SqlMapper.cs:line 1589
radarr  |    at Dapper.SqlMapper.MultiMapImpl[TFirst,TSecond,TThird,TFourth,TFifth,TSixth,TSeventh,TReturn](IDbConnection cnn, CommandDefinition command, Delegate map, String splitOn, IDataReader reader, Identity identity, Boolean finalize)+MoveNext() in /_/Dapper/SqlMapper.cs:line 1491
radarr  |    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
radarr  |    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
radarr  |    at Dapper.SqlMapper.MultiMap[TFirst,TSecond,TThird,TFourth,TFifth,TSixth,TSeventh,TReturn](IDbConnection cnn, String sql, Delegate map, Object param, IDbTransaction transaction, Boolean buffered, String splitOn, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 1451
radarr  |    at Dapper.SqlMapper.Query[TFirst,TSecond,TReturn](IDbConnection cnn, String sql, Func`3 map, Object param, IDbTransaction transaction, Boolean buffered, String splitOn, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 1306
radarr  |    at NzbDrone.Core.Datastore.SqlMapperExtensions.Query[TFirst,TSecond,TReturn](IDatabase db, String sql, Func`3 map, Object param, IDbTransaction transaction, Boolean buffered, String splitOn, Nullable`1 commandTimeout, Nullable`1 commandType) in D:\a\1\s\src\NzbDrone.Core\Datastore\Extensions\SqlMapperExtensions.cs:line 50
radarr  |    at NzbDrone.Core.Datastore.SqlMapperExtensions.QueryJoined[T,T2](IDatabase db, SqlBuilder builder, Func`3 mapper) in D:\a\1\s\src\NzbDrone.Core\Datastore\Extensions\SqlMapperExtensions.cs:line 156
radarr  |    at NzbDrone.Core.Movies.MovieRepository.All() in D:\a\1\s\src\NzbDrone.Core\Movies\MovieRepository.cs:line 105
radarr  |    at NzbDrone.Core.Movies.MovieService.GetAllMovies() in D:\a\1\s\src\NzbDrone.Core\Movies\MovieService.cs:line 239
radarr  |    at Radarr.Api.V3.Movies.MovieController.<AllMovie>b__9_0() in D:\a\1\s\src\Radarr.Api.V3\Movies\MovieController.cs:line 128
radarr  |    at System.Threading.Tasks.Task`1.InnerInvoke()
radarr  |    at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
radarr  |    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
radarr  | --- End of stack trace from previous location ---
radarr  |    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
radarr  |    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
radarr  | --- End of stack trace from previous location ---
radarr  |    at Radarr.Api.V3.Movies.MovieController.AllMovie(Nullable`1 tmdbId) in D:\a\1\s\src\Radarr.Api.V3\Movies\MovieController.cs:line 137
radarr  |    at lambda_method93(Closure , Object , Object[] )
radarr  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
radarr  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
radarr  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
radarr  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
radarr  | --- End of stack trace from previous location ---
radarr  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
radarr  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
radarr  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
radarr  | --- End of stack trace from previous location ---
radarr  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
radarr  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
radarr  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
radarr  |    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
radarr  |    at Radarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\BufferingMiddleware.cs:line 27
radarr  |    at Radarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\IfModifiedMiddleware.cs:line 40
radarr  |    at Radarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\CacheHeaderMiddleware.cs:line 32
radarr  |    at Radarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\UrlBaseMiddleware.cs:line 26
radarr  |    at Radarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\VersionMiddleware.cs:line 27
radarr  |    at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
radarr  |    at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
radarr  |    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
radarr  |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
radarr  |    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
radarr  | SQL: 
radarr  | ==== Begin Query Trace ====
radarr  | 
radarr  | QUERY TEXT:
radarr  | SELECT "Movies".*, "MovieFiles".*
radarr  |  FROM "Movies"   
radarr  | LEFT JOIN "MovieFiles" ON ("Movies"."MovieFileId" = "MovieFiles"."Id")
radarr  |     
radarr  | 
radarr  | PARAMETERS:
radarr  | 
radarr  | ==== End Query Trace ====

[AB#2902](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2902)

**Comment by RobinDadswell** [comment]
Hi @TheSpad, this is expected, as per the migrating data to Postgres section on the [wiki](https://wiki.servarr.com/en/radarr/postgres-setup#migrating-data) please ensure that you delete the data within the following tables: Profiles, QualityDefinitions & DelayProfiles

**Comment by TheSpad** [comment]
I blame Rox for not updating his Prowlarr gist. I'll give it a go, thanks.

**Comment by RobinDadswell** [comment]
> I blame Rox for not updating his Prowlarr gist. I'll give it a go, thanks.

I also blame Rox :D

**Comment by TheSpad** [comment]
All sorted
