### ISSUE TITLE
No possibility to add a movie by the search engine

### ISSUE THREAD

**Issue by FloydKulis** [Radarr/Radarr#7200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am unable to add a video via the video search system. Nothing happens while pressing the add movie button.

### Expected Behavior

The video should add to monitoring.

### Environment

```markdown
- OS: Docker
- Radarr: 4.0.5.5981
- Docker Install: 4.0.5.5981-ls136 by linuxserver.io
- Using Reverse Proxy: Yes
- Browser: Opera
```

### What branch are you running?

Master

### Trace Logs?

```
Radarr.Api.V3.Movies.MovieController.AddMovie
{
  "$.minimumAvailability": {
    "errors": [
      {
        "errorMessage": "The JSON value could not be converted to NzbDrone.Core.Movies.MovieStatusType. Path: $.minimumAvailability | LineNumber: 0 | BytePositionInLine: 3794."
      }
    ],
    "validationState": "invalid",
    "isContainerNode": false
  }
}
```

[AB#2937](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2937)

**Comment by ta264** [comment]
Change the availability to something other than predb

**Comment by FloydKulis** [comment]
@ta264 it`s work!
