### ISSUE TITLE
Error adding nzeeb.com as indexer

### ISSUE THREAD

**Issue by magma2007** [Radarr/Radarr#722]
The connectivity test fails in the "Add Newsnab" window under the Settings -> Indexers Tab and I see the following Debug Messages:

17-2-12 00:16:45.1|Warn|Newznab|Unable to connect to indexer

[v0.2.0.299] System.InvalidOperationException: Sequence contains no elements
  at System.Linq.Enumerable.First[TSource] (IEnumerable`1 source) <0x40caccb0 + 0x00143> in <filename unknown>:0 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].TestConnection () [0x0000e] in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:325 

17-2-12 00:16:45.9|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Unable to connect to indexer, check the log for more details
17-2-12 00:16:45.9|Debug|Api|[POST] /api/indexer/test: 400.BadRequest (2902 ms)

--------------------------------------------------------------------------------------

The indexer works fine in 2.0.0.4427 version of Sonarr and Mono version 4.2.3 (Stable 4.2.3.4/832de4b

The Version of Radarr is 0.2.0.299 with Mono version 4.2.1

**Comment by galli-leo** [comment]
This is often times happening when your indexer does not support movie search. You can either try and add the indexer anyways or ask the admins to enable movie search.
