### ISSUE TITLE
Incorrect matches on Plex Watchlist import

### ISSUE THREAD

**Issue by benfishbus** [Radarr/Radarr#7223]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When my Plex Watchlist was imported, two movies were incorrectly matched. The correct two movies, as it happens, already existed in Radarr.

So instead of just ignoring:
Softie (2021) - on IMDb: tt12322986 / on TMDb: 661925
Satellite (2004) - on IMDb: tt0408162 / on TMDb: 95861
(both of which contain IMDb ID mappings in their TMDb entries)

Radarr did this:
```
2022-04-13 12:50:40.8|Info|ImportListSyncService|Adding 2 movies from your auto enabled lists to library
2022-04-13 12:50:40.8|Info|AddMovieService|Adding Movie [The Sheriff and the Satellite Kid (1979)][tt0079859, 10770] Path: []
2022-04-13 12:50:41.8|Info|AddMovieService|Adding Movie [Softie (2020)][tt11394314, 653761] Path: []

```

### Expected Behavior

Radarr should always import movies from Plex Watchlists accurately based on ID.  If the movie already exists in Radarr, don't import anything.

### Steps To Reproduce

Unfortunately I've not been able to reproduce the behavior. Here is how I got there originally:
1. Search for the two titles above in Plex and add them to watchlist
2. Add the watchlist to Radarr
3. Observe incorrect matches

### Environment

```markdown
- OS: Unraid 6.9.2
- Radarr: 4.1.0.6186
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: N/A
```

### What branch are you running?

Nightly

### Trace Logs?

When I observed this, trace or debug logs weren't turned on. Now I can't reproduce the behavior.

[AB#2988](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2988)

**Comment by Qstick** [comment]
Need the Plex response showing that Plex is returning IDs. As we've found in some cases it does not.

**Comment by Qstick** [comment]
After doing some testing between @markus101 and I this appears to be a plex issue in that GUIDs are not always returned leading to Radarr having to fall back to mapping by title and year, or title alone and giving false positives.
