### ISSUE TITLE
Log movie + file downloaded

### ISSUE THREAD

**Issue by svenskman** [Radarr/Radarr#7224]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I have a problem with movies downloaded that I don't have on the list.

### Describe the solution you'd like

I would like to see what movie made the wrong file download.
Example:  movie "The Big Blue" downloaded "14.Hours.Blue.Whale.Song.nzb" 

### Describe alternatives you've considered

Manually check every movie in the list to see the search resluts

### Anything else?

The best solution would be to show what made the download of what file in the log.

[AB#2989](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2989)

**Comment by bakerboy448** [comment]
Grabs are viewable via history. Presumably your indexer had the wrong id associated with that release.

**Comment by svenskman** [comment]
Yes, I can see that the file is grabbed... but I need to know what entry made the search so I can remove it. It's downloading the same release several times in a day. Need som kind of referance.

**Comment by bakerboy448** [comment]
If it's the same release several time a day then you can easily identify the same release being grabbed multiple times in history.

That also means it's coming from an RSS feed and not any search. The release also has an incorrect id associated with it and needs to be reported to your indexer.

Names don't matter at all for grabs if the id is there.
