### ISSUE TITLE
Remove item from plex watchlist once downloaded or ignore item from future list imports

### ISSUE THREAD

**Issue by RileyXX** [Radarr/Radarr#7225]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I'm using the new plex watchlist with radarr list importing to automatically add shows from my plex watch list. Once they are downloaded and in my library I have no need for them to stay in my plex watchlist. And if I end up deleting the show in plex it will automatically redownload again in radarr on the next list import unless I manually remove shows from my plex watch list.

### Describe the solution you'd like

Add an option under **Settings > Lists > Plex Import List** to **Remove item from watchlist once downloaded**

### Describe alternatives you've considered

Add option under **Settings > Media management > Importing** to **Ignore item from future import lists once downloaded**

### Anything else?

<img width="530" alt="Capture" src="https://user-images.githubusercontent.com/49823202/163334030-d277f2aa-f9a4-4ad8-9ba4-210f9cd4d8d1.PNG">

[AB#2991](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/2991)

**Comment by bakerboy448** [comment]
If you delete a movie in Plex, then Unmonitor Deleted Movies already accomplishes this. How does it not?

Additionally, the list won't add the movie if it already exists in Radarr, so I'm it sure how you're saying it'll be added again when it already exists and thus wouldn't be added?

**Comment by bakerboy448** [comment]
Closing; no plans to modify plex watchlists and add removals.

Unmonitor Deleted Movies satisfies the usecase of not redownloading movies once the file is deleted.

Lists don't modify existing movies; cannot add movies that already exist to Radarr; do not update existing movies in anyway including monitoring them; and do not trigger searches for existing movies.  If this is happening please open a detailed bug report with the appropriate trace logs of a list import sync modifying an existing movie in radarr to monitored and/or triggering a search for an existing movie in radarr.
