### ISSUE TITLE
Manual Movie Search `Filter` option not filtering when multiple Qualities are excluded

### ISSUE THREAD

**Issue by angrycuban13** [Radarr/Radarr#7230]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When excluding multiple qualities from manual search results, the excluded qualities remain on the results.

See [Discord conversation ](https://discord.com/channels/264387956343570434/264388019585286144/965656698679332895) for pictures

### Expected Behavior

Manual resulst should be excluded if it matches the custom filter

### Steps To Reproduce

1. Click on a movie
2. Select `Search`
3. Click `Filter` on the right
4. Exclude multiple qualities
5. Excluded qualities are still listed in the manual search results

### Environment

```markdown
- OS: N/A
- Radarr: 4.1.0.6197
- Docker Install: Yes
- Using Reverse Proxy: Yes & No
```

### What branch are you running?

Nightly

### Trace Logs?

If you really need them...ping me

[AB#3003](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3003)

**Comment by angrycuban13** [comment]
Issue fixed upstream. 

https://github.com/Sonarr/Sonarr/commit/c93f63cd204bf62dab3dffef6e29c8dd4c408cab

**Comment by bakerboy448** [comment]
https://github.com/Radarr/Radarr/commit/2fc7cbff8941f928fe09167df6b15d425014ab7b
