### ISSUE TITLE
Display "Megabytes per Minutes" value of files in Movies list

### ISSUE THREAD

**Issue by Nakda** [Radarr/Radarr#7234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I tweaked the `Quality` settings (`Quality Definitions`) following TRaSH guide a long time ago, and after Radarr downloaded a movie with a lesser quality I decided to update my config. I didn't know how far I should move the sliders, because there is no indicator available to tell me which Quality my movies are at (are they generally closer to the Min value, or somewhere else in the range?).

Instead of doing it manually for each individual movie, I had to write a script to:
- browse all my files
- calculate size/duration for each movie (Megabytes per Minutes)
- generate a csv to analyse the data properly (min/max, average, check values for movies which I enjoyed the quality and vice-versa, etc)

Only then I had enough confidence to adjust the sliders with a certain logic.

### Describe the solution you'd like

Since the `Megabytes per Minutes` value is already calculated (size/runtime), I simply want it to be displayed in the movies list (possibly a column that could be shown/hidden like the rest).

### Describe alternatives you've considered

- Calculating this manually for each movie everytime you want to analyse your data
- Write a script to generate the data, then analyse it with another tool

### Anything else?

Example of a spreadshet I had to generate to analyse common Megabytes per Minutes values within my collection, to cut out the lowest ones I didn't enjoy, and ensuring I'm not cutting out too much:

![image](https://user-images.githubusercontent.com/25755503/164000275-818988c7-c840-41d5-b2e4-f4d4847bf196.png)

[AB#3014](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3014)

**Comment by bakerboy448** [comment]
No immediate plans for movie file properties on the movie index due to any uses needing to be completely rewrote with https://github.com/Radarr/Radarr/issues/1910
