### ISSUE TITLE
[Feature Request] Add IMDB to Movies Imports

### ISSUE THREAD

**Issue by XzMrtrevorzX** [Radarr/Radarr#7236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Yes it is. So TMDB [Harry Potter and the Philosopher's Stone](https://www.themoviedb.org/movie/671?language=en-US) but I need (Harry Potter and the Sorcerer's Stone)(https://www.imdb.com/title/tt0241527/?ref_=tt_mv_close) which has entirely different movie cover art.

### Describe the solution you'd like

I would like to see IMDB added so I can import the correct and matching Movie Photo Cover.

### Describe alternatives you've considered

Not sure of any alternatives ways to grab said image and metadata.

### Anything else?

https://www.themoviedb.org/movie/671?language=en-US - Wrong One.

https://www.imdb.com/title/tt0241527/?ref_=tt_mv_close - Correct One.

[AB#3017](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3017)

**Comment by Qstick** [comment]
No plans to add IMDB art, you'll have to manage the metadata outside of Radarr for this one.
