### ISSUE TITLE
Dates overview tab

### ISSUE THREAD

**Issue by stappel** [Radarr/Radarr#7238]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

There is no overview page on when a move is shown, released, etc details.

### Describe the solution you'd like

Please add an extra tab with these details on the movie page, for example between History and Search

### Describe alternatives you've considered

.

### Anything else?

.

[AB#3024](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3024)

**Comment by RobinDadswell** [comment]
Hover over the year, or if on mobile then tap the year
![image](https://user-images.githubusercontent.com/19610103/164886816-e1f5fb70-65f7-42ad-aa35-832521a97633.png)
