### ISSUE TITLE
Radarr pulling multi-language at the expense of format/profile score

### ISSUE THREAD

**Issue by Avsynthe** [Radarr/Radarr#7262]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

Radarr is finding file and ignoring the higher scored file in lieu of multi-language. My exact example is as follows where language is set in the profile to "English" from the drop-down menu and there are no custom formats to do with language:

File Names:
Movie title (2022) UHD.BRrip.4K.HDR10.HEVC [ENG,TAM,TEL,HIN] ESub         score +130

Movie title (2002) 2160p 4K 10 Bit BluRay H265 iTA ENG AC3 5.1 Sub Ita Eng        score +50

Scoring is based on custom formats for HDR and x265/HEVC. Radar pulls the ITA ENG file instead of the higher scoring file every time. I have spoken to Bakerboy on Reddit and he assured me that BRrip vs BluRay is not the issue as they a part of the same quality entry and thus have the same weight. UHD vs 2160p also does not seem to be the issue

### Expected Behavior

Radarr should be pulling the higher scoring release unless specified to prefer multi-language. It would also be advantageous to have some sort of toggle for multi-language that could be overridden by both score and specific custom formats i.e. dual audio for anime

### Environment

```markdown
- OS: unRAID
- Radarr: 4.1.0.6175
- Docker Install: linuxserver/radarr - latest
- Using Reverse Proxy: no
- Browser: Chrome
```

### What branch are you running?

Master

### Trace Logs?

[radarr.txt](https://github.com/Radarr/Radarr/files/8598127/radarr.txt)

**Comment by bakerboy448** [comment]
![413227EA-67E4-4820-B091-F8703179B596](https://user-images.githubusercontent.com/55419169/166128522-b17e3d5f-e856-4243-b808-b851fc7028f0.png)
![CDFDDC38-8D0A-43D2-B9F6-68609E12C78D](https://user-images.githubusercontent.com/55419169/166128524-d7f57e2a-11b0-4290-a996-f0fdd61788ee.png)

**Comment by Avsynthe** [comment]
Ok, I believe I've figured it out. Most likely a very particular case depending heavily on release availability for any given film.

The higher scoring file has been parsed as having hardcoded subs and so is ignored, all other higher-scoring files belong to the WebDL quality and so are being ignored in favour of BluRay. My workaround is to group the BluRay quality with WebDL in the profile if I wish to prioritise HDR over all else

**Comment by Qstick** [comment]
Closing unless you have an example of the hardcode sub logic being off
