### ISSUE TITLE
Modify Daily Refresh task to be a simple Synchronization task.

### ISSUE THREAD

**Issue by Absenm** [Radarr/Radarr#7268]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Excessive and lengthy daily I/O.  Known issue with daily refreshes. On my system (Synology DS220+ 6Gb / 32Tb) the nightly refresh takes about 1.5 - 2 hours and pound my drives hard.  

### Describe the solution you'd like

Modify Daily Refresh task to be a simple Synchronize task.   Since it appears the importance of this task is to keep Radarr metadata synchronized, maybe have a daily task that ONLY queries the upstream Servarr proxy and checks to see if the metadata for each movie has updated compared to what is currently in Radarr and if necessary update the applicable movies (**without** also analyzing the video files and **without** rescanning the movie folder.)  A full refresh task could still remain, but maybe on a weekly or monthly basis.  

This solution would incorporate to recommendations from the WikArr Help under "Can I disable the refresh movies task" while keeping a refresh task. 

### Describe alternatives you've considered

I have considered hacking the radarr.db but decided against it.

### Anything else?

I know this is an ongoing complaint and I just wanted to give my idea.  This is my first GitHub suggestion/request.

[AB#3109](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3109)

**Comment by ta264** [comment]
Disable rescan after refresh
