### ISSUE TITLE
Radarr believes my path is a location it is not

### ISSUE THREAD

**Issue by ArmonicPvP** [Radarr/Radarr#7284]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Getting this error: Remote download client Transmission places downloads in \\tower\appdata\transmission\downloads but this is not a valid ubuntu path. Review your remote path mappings and download client settings.

However under Settings > Download Clients > Remote Path Mappings > the remote path is set to 
\\tower\Plex-Media-Server\Downloads and nowhere is it set to \\tower\appdata\transmission\downloads, already changed it on unRAID in the docker settings

### Expected Behavior

Radarr should see that I changed this part and it isn't 

### Environment

```markdown
- OS: unRAID 6.10.0-rc5
- Radarr: latest 
- Docker Install: latest?
- Using Reverse Proxy: no
- Browser: chrome?
```

### What branch are you running?

Master

### Trace Logs?

https://www.toptal.com/developers/hastebin/omadocaqef.csharp Trace

![image](https://user-images.githubusercontent.com/24983808/168210248-01c6edc6-c1a2-4b2a-b2e7-d901f0afccf7.png)

![image](https://user-images.githubusercontent.com/24983808/168210280-0f4ebb3e-6396-4237-bed1-3227843fba3d.png)

![image](https://user-images.githubusercontent.com/24983808/168210314-48c0fad9-f459-4b21-b00d-3034827d9880.png)

[AB#3137](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3137)

**Comment by ArmonicPvP** [comment]
Also wanted to add I have the same config for sonarr and it works fine

**Comment by bakerboy448** [comment]
1) your docker paths are poor and result in duplicate space for all seeding torrents, slow imports, and easy permissions/path issues. See the Docker Guide

2) sonarr does not have that healthcheck 

3) the healthcheck uses the download path that your client reports it is configured to use; see the wiki section the healthcheck links for details (blue book icon)
