### ISSUE TITLE
Bug: filesnames or folder names with numbers not recognized

### ISSUE THREAD

**Issue by scoopydude2002** [Radarr/Radarr#729]
I notice a bug that any movies with numbers (in addition to the year) in either the filename or folder name really nows off Radarr.

1st example folder name: I have a few movies with "2in1" in the foldername. Radarr doesn't automatically recognize the movie on import from local disk. I'll have to manually search for the file.

2nd example filenames: I have a move called "Movie.2015.25th.Anniversary.Edition.1080p.BluRay.DTS.x264.mkv". Having "75th" in the filename, Radarr cannot recognize that the video file exists and list the movie as "missing".

3rd example (aslo filenames): A folder with "1080" instead of "1080p" throws off Radarr and it doesn't automatically recognize the movie on import from local disk.

**Comment by galli-leo** [comment]
Can you provide the full folder name for the first example?

**Comment by scoopydude2002** [comment]
Here's an example of one: /movies/101.Dalmatians.II.Patchs.London.Adventure.2003.1080.BluRay.x264.DTS-NoGroup

The "101" throws it off.

**Comment by galli-leo** [comment]
That one matches fine for me with 1080p. It's a good naming convention to change 1080 to 1080p. Although I suppose I could add 1080 (without the p) to the parser.

**Comment by scoopydude2002** [comment]
If that's not too difficult, would be great. I have a lot of movies folder to rename. Especially movies in the cloud take time to rename.

Another question (kind of off topic). If I turn on file renaming, will it rename new movies only or also old movies? I turned this on once for Sonarr and it start rename my old shows which are stored in the cloud. It downloaded all the shows and then renaming them. I just want to rename new movies being downloaded.

**Comment by galli-leo** [comment]
You can click organize in the movie editor and it will rename all your existing files. But it should not rename old ones.

**Comment by scoopydude2002** [comment]
Thanks, will give it a try.

Any thoughts about my example 2 above? Here's the full folder name and filename: /movies/The.Wizard.Of.Oz.1939.75th.Anniversary.Edition.1080p.BluRay.DTS.x264/The.Wizard.Of.Oz.1939.75th.Anniversary.Edition.1080p.BluRay.DTS.x264-PublicHD.mkv

**Comment by galli-leo** [comment]
Yeah, for these I would just remove the 75th string. I may update the parser, but these are very rare.
