### ISSUE TITLE
Include the QxR release group encoder "r00t" under ExceptionReleaseGroupRegex

### ISSUE THREAD

**Issue by jbk0** [Radarr/Radarr#7290]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

A manual list of encoders who do not follow the -RlsGrp format was added in this PR: https://github.com/Radarr/Radarr/pull/5612

This list primarily includes encoders from the QxR release group, but the encoder `r00t` is not included in the list. They primarily do older/foreign films but have a large number of encodes available.

@bakerboy448 suggests I should ping them if a release name is not included in the list.

### Describe the solution you'd like

`r00t` is added to the regex string in `src/NzbDrone.Core/Parser/Parser.cs => ExceptionReleaseGroupRegex`

### Describe alternatives you've considered

N/A

### Anything else?

N/A

[AB#3149](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3149)

**Comment by bakerboy448** [comment]
Need some example releases from the wild

**Comment by jbk0** [comment]
Sure thing.

```
A Shot in the Dark (1964) (1080p BluRay x265 r00t).mkv 
Near Dark (1987) (1080p BluRay x265 r00t).mkv
Midnight Run (1988) (1080p BluRay x265 r00t).mkv
The Hidden (1987) (1080p BluRay x265 r00t).mkv 
The Pink Panther (1963) (1080p BluRay x265 r00t).mkv
```

You can find a bunch more by doing a name search on 1337x, `r00t` seems to have hundreds of releases.

**Comment by jbk0** [comment]
TY 🚀
