### ISSUE TITLE
IMDb watchlist: single episodes get added

### ISSUE THREAD

**Issue by petwri** [Radarr/Radarr#730]
Similar to the issue https://github.com/Radarr/Radarr/issues/699, when adding single episodes on IMDb to a watchlist, they get added to Radarr as well.

**Comment by galli-leo** [comment]
What is the title of such an episode in the rss feed?

**Comment by petwri** [comment]
Something like "Episode name (2016 TV Episode)"

**Comment by onedr0p** [comment]
Incoming fix
