### ISSUE TITLE
PTP implementation doesn't grab the actual RSS feed

### ISSUE THREAD

**Issue by jonoff** [Radarr/Radarr#7307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

With RSS enabled, old items may be grabbed when a new version is made available.
Due to this line https://github.com/Radarr/Radarr/blob/master/src/NzbDrone.Core/Indexers/PassThePopcorn/PassThePopcornRequestGenerator.cs#L54

using `BaseUrl.Trim().TrimEnd('/')}/torrents.php?action=advanced&json=noredirect&searchstr={searchParameters}",` as the request URL, but it is not equivalent to an RSS feed, since this homepage can be affected by user settings.

The correct RSS URL looks something like: `feeds.php?feed=torrents_all&user=#####&auth=#####&passkey=#####&authkey=#####`

### Expected Behavior

RSS feed only grabs new items, instead of grabbing old items which may appear depending on user settings.

### Environment

```markdown
- OS: Linux
- Radarr: 4.1.0.6175
- Docker Install: yes
```

### What branch are you running?

Master

### Trace Logs?

N/A

[AB#3189](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3189)

**Comment by Qstick** [comment]
https://github.com/Radarr/Radarr/commit/1762a189d2ef7e3e383b1a8b7d2dd059cea36ed8
