### ISSUE TITLE
Collection api very slow

### ISSUE THREAD

**Issue by reloxx13** [Radarr/Radarr#7318]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The web ui still takes multiple minutes for loading (showing radarrs loading screen). I'm looking through the logs but cannot find any more errors beside    

```
2022-05-30 14:48:42.3|Error|LocalizationService|Missing translation/culture resource: X:\Radarr-V3\bin\Localization\Core\de_DE.json
```   

While my radarr 4k instance runs fine.    

In the browser console, I can see the request to `http://192.168.178.12:7777/api/v3/collection` is taking so looooooong.   
`GET http://192.168.178.12:7777/api/v3/collection`,  15mins, still running.   

The `/api/v3/movie` endpoint also takes ~30s.   

Server completely restarted already.

Tested in Firefox and chrome, private tabs and also cleared cache, sessions and cookies.    
CPU is idling while the request is running.

### Expected Behavior

Normal loading time

### Environment

```markdown
- OS: Win10x64
- Radarr: 4.2.0.6318
- Docker Install: no
- Using Reverse Proxy: no
- Browser: Firefox and Chrome
```

### What branch are you running?

Nightly

### Trace Logs?

No errors found in trace, debug, radarr logs.

May be related to https://github.com/Radarr/Radarr/commit/f80272a65987b635b07448e6b959df0ad8c105d2

[AB#3210](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3210)

**Comment by Qstick** [comment]
@reloxx13 feel free to come by Discord for some testing and discussion on this. I've added you to the testing channel.

**Comment by malventano** [comment]
> @reloxx13 feel free to come by Discord for some testing and discussion on this. I've added you to the testing channel.

I've replicated what appears to be the same slowdown issue here. Noticed it on 4.2.0.6320, but could have existed on 4.2.0.6318
 here as well. Pull me into the testing channel on Discord if more info is needed.
