### ISSUE TITLE
ffprobe No such file or directory

### ISSUE THREAD

**Issue by akgh11** [Radarr/Radarr#7324]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Downloaded movies are not being fully imported once download is complete.

```
VideoFileInfoReader | Unable to parse media info from file: M:\Videos\Pending torrent downloads\Pirates.of.the.Caribbean.Dead.Mans.Chest.2006.2160p.UHD.BluRay.x265.10bit.HDR.DTS-HD.MA.TrueHD.7.1.Atmos-SWTYBLZ\Pirates.of.the.Caribbean.Dead.Mans.Chest.2006.2160p.UHD.BluRay.x265.10bit.HDR.DTS-HD.MA.TrueHD.7.1.Atmos-SWTYBLZ.mkv: ffprobe exited with non-zero exit-code (1 - M:\Videos\Pending torrent downloads\Pirates.of.the.Caribbean.Dead.Mans.Chest.2006.2160p.UHD.BluRay.x265.10bit.HDR.DTS-HD.MA.TrueHD.7.1.Atmos-SWTYBLZ\Pirates.of.the.Caribbean.Dead.Mans.Chest.2006.2160p.UHD.BluRay.x265.10bit.HDR.DTS-HD.MA.TrueHD.7.1.Atmos-SWTYBLZ.mkv: No such file or directory) |  
-- | -- | --
  | 5:02pm | DetectSample | Failed to get runtime from the file, make sure ffprobe is available

```

The error occurs even when I copy the ffprobe.exe bundled with Radarr into 1 of the affected movie's folders:
```
PS M:\Videos\Pending torrent downloads\Pirates.of.the.Caribbean.Dead.Mans.Chest.2006.2160p.UHD.BluRay.x265.10bit.HDR.DTS-HD.MA.TrueHD.7.1.Atmos-SWTYBLZ> .\ffprobe.exe .\Pirates.of.the.Caribbean.Dead.Mans.Chest.2006.2160p.UHD.BluRay.x265.10bit.HDR.DTS-HD.MA.TrueHD.7.1.Atmos-SWTYBLZ.mkv
ffprobe version 5.0.1 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 9.3-win32 (GCC) 20200320
  configuration: --prefix=/ffmpeg/build --bindir=/ffmpeg/bin --logfile=/ffmpeg/bin/log.txt --disable-autodetect --disable-iconv --enable-libdav1d --disable-programs --enable-ffprobe --disable-avdevice --disable-swresample --disable-swscale --disable-postproc --disable-avfilter --disable-network --disable-everything --enable-protocol=file --enable-demuxers --enable-parsers --enable-decoders --enable-bsf=av1_frame_split --enable-bsf=av1_frame_merge --enable-bsf=av1_metadata --enable-cross-compile --arch=x86_64 --target-os=mingw32 --cross-prefix=x86_64-w64-mingw32- --pkg-config=pkg-config --pkg-config-flags=--static --extra-ldexeflags=-static --extra-libs='-lpthread -lm'
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
.\Pirates.of.the.Caribbean.Dead.Mans.Chest.2006.2160p.UHD.BluRay.x265.10bit.HDR.DTS-HD.MA.TrueHD.7.1.Atmos-SWTYBLZ.mkv: No such file or directory
PS M:\Videos\Pending torrent downloads\Pirates.of.the.Caribbean.Dead.Mans.Chest.2006.2160p.UHD.BluRay.x265.10bit.HDR.DTS-HD.MA.TrueHD.7.1.Atmos-SWTYBLZ>
```

### Expected Behavior

Movie should finish downloading, then get imported into Radarr/Emby

### Steps To Reproduce

1. Add a movie to the monitored list.
2. Allow Radarr to send the torrent to qBittorrent for download.
3. Download completes successfully.
4. Error occurs in logs and the movie does not get added to my Emby library.

### Environment

```markdown
- OS: Windows
- Radarr: 4.1.0.6175
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Edge
- .NET: Yes (6.0.3)
- DB Migration: 206
- AppData directory: C:\ProgramData\Radarr
- Startup directory: C:\ProgramData\Radarr\bin\bin
- Mode: Tray
```

### What branch are you running?

Master

### Trace Logs?

[radarr.0.txt](https://github.com/Radarr/Radarr/files/8809470/radarr.0.txt)

[AB#3216](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3216)

**Comment by bakerboy448** [comment]
`No such file or directory` is the key error message there.

`M:\Videos\Pending torrent downloads\Pirates.of.the.Caribbean.Dead.Mans.Chest.2006.2160p.UHD.BluRay.x265.10bit.HDR.DTS-HD.MA.TrueHD.7.1.Atmos-SWTYBLZ\Pirates.of.the.Caribbean.Dead.Mans.Chest.2006.2160p.UHD.BluRay.x265.10bit.HDR.DTS-HD.MA.TrueHD.7.1.Atmos-SWTYBLZ.mkv` has length of that path is 265 characters which exceeds windows max length of 260 characters and thus is correctly not accessible.

> The error occurs even when I copy the ffprobe.exe bundled with Radarr into 1 of the affected movie's folders:

This is not the issue nor would have anything to do with the file/path being not accessible.

> Trace Logs?
> radarr.0.txt

For future reference, info logs are not trace logs.
