### ISSUE TITLE
Bulk Import - Background feature

### ISSUE THREAD

**Issue by shushry** [Radarr/Radarr#733]
Like others, I have a very large collection of existing media I would like to add to Radarr from the git-go.
I've experimented with the recently added "Bulk Import" feature - but even this, with a large collection is tedius as I'm needing to paginate at the "1000 per page" level just to make this tolerable - but even at the 100 per-page level, the import seems to stall and crash.   I've only really been able to get this to work at the 15 per page level successfully, and that leaves me with several hundred pages to process.    Hard to manage bulk like this.

Suggestions:
- I would envision the "select all and import feature" would be appropriate on the standard "import" button that exists now (the one where you have to manually add each title currently).   And instead of a separate "bulk import" section, one of the two ideas:
1)  How about a task to "watch" your root directory?   Set a root folder, and Radarr will silently in the background (maybe as a task that chews through 10 at a time for sanity, every few minutes) looks for matching titles in appropriately names folders in the 'root' watch folder - ignoring any titles that have explicitly been deleted or already exist perhaps...but otherwise adding titles as found in small batches in the background.   CP does this now and does it pretty well.   The Drone factory folder "could" work for this, but it would mean cycling in one's existing titles to there, only to be put back where it belongs in it's root folder.   I thought maybe the "RescanMovies" api command might do this, but this just appears to scan the contents of existing/already added movies for content.

2) How about loosening up the API required fields for adding a title?   Currently it seems (per the docs) you have to know quite a bit about the title you're adding in order to get this to work - how about just an API call that only requires the new title's "folder" and Radarr does the rest - just as if it had found it in the drone folder?   Maybe a new api command to "import" ?

Just some thoughts on really streamlining the import of a collection.

[AB#888](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/888)

**Comment by galli-leo** [comment]
Are you on the latest nightly. I have fixed an issue with the bulk import crashing on loading your movies. If yes can you post your logs?

**Comment by shushry** [comment]
I'm configured for the nightly build, yes.   I'll grab today's and do a run and see what happens.

**Comment by shushry** [comment]
One observation in my logs from my last attempt (last night) is that during a bulk import there are a ton of timeout errors trying to grab media from IMDB.   Things like this:

17-2-13 07:38:06.8|Warn|HttpClient|Failed to get response from: http://image.tmdb.org/t/p/original/fRP1XYUWdXZKdplXtPXmJg42wBq.jpg The request timed out
17-2-13 07:38:06.8|Warn|MediaCoverService|Couldn't download media cover for [tt5354160]. The request timed out

[v0.2.0.341] System.Net.WebException: The request timed out

Do we need a throttle on hits to IMDB?

**Comment by shushry** [comment]
I'm going to open a new thread for the imdb issue above - and keep this a feature request so we don't get split-topic.

**Comment by galli-leo** [comment]
Currently have a somewhat working branch that could potentially remove the necessity of this, as it would speed up the bulk import by a lot (e.g. showing a 1000 movies in ~10 seconds)

**Comment by aaronkuchma** [comment]
See https://github.com/Radarr/Radarr/issues/2273 for strategies to mostly-automate importing a huge poorly named collection with duplicates

**Comment by NeoJoris** [comment]
Any news on this, or known workarounds? As this is still an issue after 5 years.

**Comment by bakerboy448** [comment]
There hasn't been a bulk import feature in years.

For Library Imports, most are fine with chunks of a few thousand depending on their systems.

Api docs clearly note what is and isn't required (nullable) for adding movies.

What's the current actual issue since this issue isn't relevant or connected to any existing features and significant changes have been made in the last 5 years?

**Comment by mattmattox** [comment]
I have been stuck for months trying to import around 12k movies.

Can someone point me to where the import is because I want to see if I can just make the api calls directly

**Comment by bakerboy448** [comment]
Please use [Discord](https://radarr.video/discord) for support/questions.
