### ISSUE TITLE
Import to the wrong movie that has the same year and English title

### ISSUE THREAD

**Issue by wloot** [Radarr/Radarr#7331]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If I have two movies that have the same year and English title, eg: آن شب (2021), 良夜不能留 (2021), and those two movies both have the same English translated name as "The Night".
I manually grab a release for one of them, it may be wrongly imported to another after downloading.

### Expected Behavior

Importing to the one I grubbed for.

### Steps To Reproduce

1. two movies like above
2. manual grab
3. wait importing

### Environment

```markdown
- OS: Centos 9
- Radarr: 4.1.0.6175
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Chrome
```

### What branch are you running?

Develop

### Trace Logs?

If needed

[AB#3223](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3223)

**Comment by ta264** [comment]
How do you expect radarr to know? I think really it should refuse to import at all in this case and await manual intervention

**Comment by wloot** [comment]
I'm not sure how it works inside radar, but is it possible to save metadata while grabbing for use when importing? And yes, I think it is a good way that disabling auto-import while the problem is deleted.

**Comment by bakerboy448** [comment]
Even if we maintained the grab info for import parsing (those two blackboxes are intentionally separate), if it was not an ID based search and was only by name, one can't even be sure the movie grabbed/returned by the indexer is the correct movie. Let alone which import to do.

I think it should be kicked over to the user to handle.

**Comment by wloot** [comment]
> Even if we maintained the grab info for import parsing (those two blackboxes are intentionally separate), if it was not an ID based search and was only by name, one can't even be sure the movie grabbed/returned by the indexer is the correct movie. Let alone which import to do.
> 
> I think it should be kicked over to the user to handle.

Okay, I get it now and totally agree with you!
