### ISSUE TITLE
Filtering for collections screen

### ISSUE THREAD

**Issue by PearsonFlyer** [Radarr/Radarr#7338]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

On the collections screen, a couple more filters would be handy to have.

### Describe the solution you'd like

1) Filter for collections missing 1+ movies.
2) Sorting by number of missing movies.
3) Filter for complete collections.

### Describe alternatives you've considered

None

### Anything else?

N/A

[AB#3233](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3233)

**Comment by ricci2511** [comment]
I came up with a solution for all 3 points you mentioned that seems to work as intended.

Will submit a pr later today.
