### ISSUE TITLE
Deleted Files not Being Detected

### ISSUE THREAD

**Issue by hughesjs** [Radarr/Radarr#7339]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I had a bunch of films of mixed profiles and restrictions that was a bit of a mess.

I want to consolidate them down onto one tag/restriction and one profile.

I used the bulk editor to add these tags and change the profiles.

I ran a refresh (hoping that it would replace my 4k or x265 videos with 1080o versions) but I guess it doesn't downgrade files even if they now fall outside of the profile.

So I figure, I'll delete all my film files from disk, do a rescan and it'll download with the correct bits and bobs.

So I do that, but everything is still showing up as downloaded.

I've checked in media management and "Rescan Movie Folder after Refresh" is set to "Always". I've also tried restarting the docker container to no avail.

### Expected Behavior

On rescan, Radarr realises the files are missing, marks the films as missing and attempts to redownload them.

### Steps To Reproduce

1. Add loads of films to Radarr
2. Get a cuppa while they download
3. `rm -rf ./` the files into oblivion
4. Trigger a rescan in Radarr
5. Observe that everything is still showing as downloaded

### Environment

```markdown
LSIO Docker Image Latest on an Arch Host
```

### What branch are you running?

Develop

### Trace Logs?

Holding off on this as I imagine refresh all would count as "spammy". Can provide if needed.

[AB#3234](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3234)

**Comment by Qstick** [comment]
You triggered another refresh and scan after the delete? Because your summary seems to indicate that was before.

Need version info as well

**Comment by bakerboy448** [comment]
> On rescan, Radarr realises the files are missing, marks the films as missing and attempts to redownload them.

a rescan does not do any searching at all. Simply refreshes meta and rescans the disk.

If they're still showing as downloaded, is your entire root folder empty and thus you've triggered the protection mechanism?

**Comment by hughesjs** [comment]
Ahh that'll be it, didn't realise there was a protection mechanism.

Makes sense I suppose in-case something didn't mount properly!

Can I suggest we consider changing this log entry "Movie's root folder (/movies) is empty." to something a bit more verbose that indicates that there's a protection mechanism at play?

I'd suggest: "Movie's root folder (/movies) is empty. Refusing to update file states in case this is due to a filesystem mount issue."

**Comment by Qstick** [comment]
I'm fine with adding a bit more, Refusing is likely not the word to use.
