### ISSUE TITLE
In Activity -> History, URLs for movies don't include url_base

### ISSUE THREAD

**Issue by fryfrog** [Radarr/Radarr#734]
Screen shot available to share privately, if needed... but @onedr0p knows what this is.

Go to Activity -> History and hover over the link to a movie. It is missing url_base.

http://example.com/movies/movie-123 when it should be http://example.com/radarr/movies/movie-123

Clicking it works, but opening in a new tab doesn't.

**Comment by fryfrog** [comment]
This is still in 0.2.0.434, fwiw.

**Comment by onedr0p** [comment]
Fixed in next release
