### ISSUE TITLE
FreeBSD 13.1 Cannot get required symbol DSA_generate_parameters_ex from libssl

### ISSUE THREAD

**Issue by d1th** [Radarr/Radarr#7342]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When executing Radarr the following error is displayed:

[Info] Bootstrap: Starting Radarr - /usr/local/share/radarr/bin/Radarr - Version 4.1.0.6175 
[Debug] Bootstrap: Console selected 
[Info] AppFolderInfo: Data directory is being overridden to [/usr/local/radarr] 
[Debug] Microsoft.Extensions.Hosting.Internal.Host: Hosting starting 
[Info] AppFolderInfo: Data directory is being overridden to [/usr/local/radarr] 
Cannot get required symbol DSA_generate_parameters_ex from libssl
zsh: abort (core dumped)  /usr/local/share/radarr/bin/Radarr --data=/usr/local/radarr --nobrowser

### Expected Behavior

Radarr to succesfuly start.

### Steps To Reproduce

1. Installation of radarr package on FreeBSD 13.1 through pkg or by downloading the latest release.
2. Starting radarr

openssl: 1.1.1o_1,1 - Removed pkg and reinstalled.
radarr - Removed pkg and reinstalled. Tried FreeBSD releases binary. Same error.
Renamed datadir to determine if the issue was related to previous configuration. 

Sonarr & Bazarr are not having this issue.

### Environment

```markdown
- OS: FreeBSD 13.1
- Radarr: 4.1.0.6175
- Mono: mono6.8-6.8.0.123_1  
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Safari
```

### What branch are you running?

Master

### Trace Logs?

Enabling debug does not procedure .debug.txt logging. 

[AB#3239](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3239)

**Comment by bakerboy448** [comment]
Please use one of the support channels: [Discord](https://radarr.video/discord) for support/questions - #bsd-builds channel

if after some debugging and investigating and it is a bug we can reopen.

**Comment by mvanbaak** [comment]
For future reference: On discord we found out it's an issue with the users install. A clean freebsd VM did not show this error, nor my 2 radarr jails.
