### ISSUE TITLE
Import movie error (Nightly 4.2.0.6349)

### ISSUE THREAD

**Issue by casperse** [Radarr/Radarr#7347]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Dosent import movie, when doing a manual import I get:
![image](https://user-images.githubusercontent.com/2026859/172623771-afe38499-53a3-4259-ba66-d1d33c0ad779.png)

No write read rights/access problem.....

Message
Failed to get runtime from the file, make sure ffprobe is available

Docker install no special install of ffprobe?
I wanted to go back to develop version but DB is not reversable

### Expected Behavior

Import of files should work
If I move them manually and try to do a "rename" then I get this:
![image](https://user-images.githubusercontent.com/2026859/172625297-ddf37186-a2a1-4fb9-b4af-145746fcb325.png)

This worked before

### Steps To Reproduce

Copy files to folder
refresh scan
preview rename

Or do a manually import

### Environment

```markdown
Docker
Version
4.2.0.6349
Package Version
4.2.0.6349-ls315 by linuxserver.io
.NET
Yes (6.0.5)
Docker
Yes
DB Migration
210
Database
Sqlite 3.36.0
AppData directory
/config
Startup directory
/app/radarr/bin
Mode
Console
```

### What branch are you running?

Nightly

### Trace Logs?

[radarr.txt](https://github.com/Radarr/Radarr/files/8861821/radarr.txt)

[AB#3242](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3242)

**Comment by bakerboy448** [comment]
> [v4.2.0.6344] FFMpegCore.Exceptions.FFMpegException: ffprobe exited with non-zero exit-code (1 - [matroska,webm @ 0x1a236c0] 0x00 at pos 0 (0x0) invalid as first byte of an EBML number


Invalid/corrupt video file


Also info logs are not valid for bug reports, trace logs are required.
