### ISSUE TITLE
Bulk Editing for Collections

### ISSUE THREAD

**Issue by ascentweb** [Radarr/Radarr#7350]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

There is no ability to bulk edit Collections (Movies, Collections) to change the root folder. This has to be done at an individual level which isn't practical for large collections.

### Describe the solution you'd like

The ability to bulk edit collections (just as you can bulk edit movies and change the root folder). Just add the same option you currently have under Movies, Movie Editor)

### Describe alternatives you've considered

Could change the drive letter in Windows as a workaround but that has other implications

### Anything else?

Description is hopefully clear enough

[AB#3249](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3249)

**Comment by reloxx13** [comment]
Same for quality profile.

I cleaned and re-made my quality profiles and now i cannot delete the old profiles because they r used in the collections and i would need to edit every collection by hand to change the profile to the newer.
