### ISSUE TITLE
History not complete

### ISSUE THREAD

**Issue by mikey2p22** [Radarr/Radarr#736]
Failed downloads and deleted files doesn't appear in History

**Comment by geogolem** [comment]
yup - i noticed this as well.

**Comment by galli-leo** [comment]
Failed downloads are grouped in the blacklist. Should they appear in history?

**Comment by mikey2p22** [comment]
In Sonarr are they in the history wich makes it easy to see whar exactly happened.
See screenshot for example:
![image](https://cloud.githubusercontent.com/assets/18078206/23095869/ed0e878c-f611-11e6-8e4c-249cd3b6c27b.png)

**Comment by geogolem** [comment]
ya - I noticed this before.. I think they should appear in history..

![image](https://cloud.githubusercontent.com/assets/23205277/23096417/1d903978-f5ea-11e6-99f8-5240aea53449.png)


the legend/filters show for "failed" and "deleted" but i havent seen anything show up with those tags. I think deleted should correspond to when the download was deleted from the downloader... 

not too sure though.. but i think both should show up in the history.. same as sonarr -- it is especially useful for when we have the option for radarr/sonarr to remove items from the download client...

**Comment by onedr0p** [comment]
Fixed in next release.
