### ISSUE TITLE
Long path support for ffprobe

### ISSUE THREAD

**Issue by fredskis** [Radarr/Radarr#7370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

On Windows, when a completed download media file is probed by ffprobe, if the path to the file is beyond the max path limit of 260 characters, ffprobe returns a "No such file or directory." error and Radarr is unable to get info from and import the file. 

### Describe the solution you'd like

Update the file system functions that ffprobe uses to support the modern Windows long file path API. 

### Describe alternatives you've considered

I have ensured LongPathsEnabled is set to 1 in the HKLM\SYSTEM\CurrentControlSet\Control\FileSystem registry key. 
I cannot simply shorten my completed downloads path as I have come across files that once extracted by SABnzbd reach 260 characters with the folder\filepath name alone. 

### Anything else?

Extra details may be found in my original Reddit post: 
https://www.reddit.com/r/radarr/comments/vcokzz/ffprobe_and_long_file_path_in_windows/ 

[AB#3290](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3290)

**Comment by ta264** [comment]
The patches here might do it: https://github.com/yt-dlp/FFmpeg-Builds/tree/master/patches/ffmpeg/release_5.0

**Comment by bakerboy448** [comment]
Servarr ffprobe binaries with long path support for testing are now available for testing.

swing by [our Discord](https://radarr.video/discord)

**Comment by Qstick** [comment]
This should be fixed with ffprobe5.1
