### ISSUE TITLE
Show "Release Group" in Table View

### ISSUE THREAD

**Issue by somewherebutnothere** [Radarr/Radarr#7377]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

It's a very minor thing but in the main movies page, table view, it would be nice to have a column for the release group. Sonarr already does this.

### Describe the solution you'd like

Add a column for the relase group in the Movies page, table view.

### Describe alternatives you've considered

None.

### Anything else?

Sonarr example:

![image](https://user-images.githubusercontent.com/6793358/174805187-59885199-47fe-4dc7-9b3a-63440eb3134b.png)

[AB#3307](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3307)

**Comment by ta264** [comment]
We have no plans to show properties of the file on the main overview page until we have finalize multiple file support

**Comment by bakerboy448** [comment]
Related to https://github.com/Radarr/Radarr/issues/7086
