### ISSUE TITLE
Multi Language option inexistant for custom formats

### ISSUE THREAD

**Issue by saturday92** [Radarr/Radarr#7382]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hey team. I wanted to choose the multi language as a custom format... But there's no such option.
I looked everywhere and i saw a screenshot of a person showing she had that option on V3.
Now we are V4 and there's no option for that, at all.
#sad

### Expected Behavior

If we had the possibility to choose... It would be wonderful.
Example:
OPTION 1 - I want my movies: ENG but when FRE is out, replace by FRE.
and
OPTION 2 - I want my movies: Multi (ENG+FRE) but if there's only ENG available... DL ENG.
                                                  Then, when multi ENG+FRE is out, replace ENG for MULTI ENG+FRE.

With this 2 options... Life would be so easy ^^

### Steps To Reproduce

Windows 10
Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz   3.60 GHz
32,0 Go
 64 bits, processeur x64

### Environment

```markdown
- OS: Ubuntu 20.04
- Radarr: 4.1.0.6175
- Docker Install: private server on OneProvider
- Using Reverse Proxy: no
- Browser: google chrome
```

### What branch are you running?

Master

### Trace Logs?

![image](https://user-images.githubusercontent.com/25355466/175298667-f44c9ad9-5346-4792-8882-8680f8df65bf.png)

**Comment by saturday92** [comment]
Can we add this to feature request then?

**Comment by bakerboy448** [comment]
- https://wiki.servarr.com/radarr/faq#how-does-radarr-handle-foreign-movies-or-foreign-titles
- https://trash-guides.info/Radarr/Radarr-import-custom-formats/
- https://trash-guides.info/Radarr/Radarr-collection-of-custom-formats/#multi
