### ISSUE TITLE
Error loading page when navigating to Movies > Collections

### ISSUE THREAD

**Issue by sydlexius** [Radarr/Radarr#7392]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When navigating to Movies > Collections, I get a "There was an error loading this page" message: [collectionserror.txt](https://github.com/Radarr/Radarr/files/8987394/collectionserror.txt)
.

### Expected Behavior

Able to view and modify monitoring of collections.

### Steps To Reproduce

1. Start Container
2. Browse to WebUI (or reverse-proxy URL
3. Authenticate
4. Navigate to Movies > Collections
5. See green alien gerbil run away with someone's router

### Environment

```markdown
- OS: Unraid 6.10.3
- Radarr: 4.2.0.6389
- Docker Install: Yes.  LSIO.
- Using Reverse Proxy: Yes (LSIO Swag) (also tested without)
- Browser: Vivaldi 5.3.2679.61 (Stable channel) (64-bit), Edge Version 103.0.1264.37 (Official build) (64-bit)
```

### What branch are you running?

Nightly

### Trace Logs?

[radarr.trace.txt](https://github.com/Radarr/Radarr/files/8987395/radarr.trace.txt)

[AB#3400](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3400)

**Comment by sydlexius** [comment]
Just a note that when I open the page on mobile Chrome, it works.  When I change Chrome to "View Desktop Site", the error returns.

**Comment by sydlexius** [comment]
Additionally, when I set the display width > 768 pixels, it bombs.

**Comment by bakerboy448** [comment]
Possibly fixed with https://github.com/Radarr/Radarr/commit/d8891ee4ea9e635919781e8fcbb0ea751e815506 ?

**Comment by Qstick** [comment]
Closing unless it’s reported broken again
