### ISSUE TITLE
Add "Companies" ID as list option

### ISSUE THREAD

**Issue by hellot1m** [Radarr/Radarr#7393]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Not related to a problem

### Describe the solution you'd like

The current options for using list from IMDB are only by List ID `ls` or User ID `ur`. It would be nice to also be able to use Company ID `co` as a option. This would allow monitoring of production companies like Marvel and A24. each time a studio releases a new movie, Radarr using List automatically adds or at least gives the option to add using discover and list.  

### Describe alternatives you've considered

none, that i am aware of.

### Anything else?

the `co` id for Marvel Studios is `co0051941` 

[AB#3318](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3318)

**Comment by Qstick** [comment]
As an FYI, you can already use TMDb company Id which works just as well in most all cases.

**Comment by hellot1m** [comment]
> As an FYI, you can already use TMDb company Id which works just as well in most all cases.

That's good to know! I'll try that out. Although it seems silly to include this feature with one site but not another. TMDB has always been unreliable, site is super slow compared to IMDb and their series tracking is riddled with issues. I try not to rely on TMDB much.

**Comment by austinwbest** [comment]
One site provides free api access, one doesn't. Not so much silly as straight forward.

**Comment by hellot1m** [comment]
> > That's good to know! I'll try that out. Although it seems silly to include this feature with one site but not another. TMDB has always been unreliable, site is super slow compared to IMDb and their series tracking is riddled with issues. I try not to rely on TMDB much.
> 
> All Radarr data is originally sourced from TMDB

yea i know. its always been a pain. i wish radarr gave options to choose which host to use to sort. sometimes TMDB is fine. sometimes its horrible. for example, the pokemon series. that series has many formats, but none of the packs for this show match the way radarr (TMDB) organizes it. another issue with TMDB are with cartoons that have two episodes in one. it hardly ever gets it right the first time so i have to go in and reimport them. IMDB and other host sites tend to get these much better. also i've had issues where TMDB changes their series format which messes with future grabs till i fix the issue. 

all im asking is for a simple feature to be added that the radarr team clearly already has the api to do so as list and users are already able to be used. 

you actually gave me another idea lol. if Plex is able to give its users the choice of which agent to use to organize your shows, it would be nice if radarr was able to do the same.

**Comment by Qstick** [comment]
Until we have a way to grab a company list or get a exportable list from a company on IMDB, this won't happen. Closing for now, if someone has a way to get an exportable list of company movies from IMDB (like normal lists) we can open it back up.
