### ISSUE TITLE
Prefer new media rather than upgrading media

### ISSUE THREAD

**Issue by p5-f20w18k** [Radarr/Radarr#7395]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

When adding a lot of movies from a list (say over 100). I'd prefer to prioritise downloading these rather than upgrading existing media.

### Describe the solution you'd like

A button, or switch in the UI that will set radarr in a "download new movies only" mode, or "upgrade existing movies only" mode. 

It would be great if this could be set on a schedule and have a "hybrid" mode. The hybrid mode would be the same as how radarr currently works.

### Describe alternatives you've considered

Manually selecting new movies for download and setting the priority in the download client, or just letting radarr eventually grab it.

### Anything else?

N/A

[AB#3321](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3321)

**Comment by Qstick** [comment]
I don't think we have plans for this, you can toggle update off in the quality profile if you really want something quick and dirty.
