### ISSUE TITLE
Verify torrent has a video file before downloading it to prevent malware

### ISSUE THREAD

**Issue by initialseed** [Radarr/Radarr#7398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Radarr downloaded a torrent that has a file called "MOVIE.mkv.lnk" (windows shortcut) which is malware.

### Describe the solution you'd like

I'm not sure how to this can be solved but maybe verify file extensions and make sure that there is at least one video file in the torrent before downloading it?

### Describe alternatives you've considered

Torrents with .lnk/powershell/batch files could be automatically blacklisted or the .lnk/powershell/batch file set to not be downloaded. (in case the torrent is legit and it has a shortcut to the group's website)

### Anything else?

Same issue as here:
https://www.reddit.com/r/radarr/comments/amqstx/beware_of_some_cleverly_packaged_malware_that_my/

[AB#3328](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3328)

**Comment by bakerboy448** [comment]
Not possible to verify the torrents prior to downloading as the data does not exist.

- get better trackers that don't allow fakes
- Use custom formats and restrictions to avoid release groups and other keywords in the releases that are fakes
- Set your availability delay and profile to released with a negative delay as the FAQ suggests
