### ISSUE TITLE
Delay Search until Physical Release date

### ISSUE THREAD

**Issue by ajslater** [Radarr/Radarr#740]
Feature Request: Delay searching indexers until the Physical Release date passes.
An added bonus might be to also allow delaying until this In Cinemas date passes for people who want that.

The issue is that searching before these dates results in a great deal of fakes being auto downloaded.

Relates to: https://github.com/Radarr/Radarr/issues/601

**Comment by SuperPotatoMen** [comment]
+1

**Comment by SuperPotatoMen** [comment]
I got a lot of fake or bad downloads :(

**Comment by ajslater** [comment]
Actually the proper place to vote for this feature is here:
http://feathub.com/Radarr/Radarr/+86

**Comment by galli-leo** [comment]
I will implement this when I get around to finish the predb integration.

**Comment by toddcurry** [comment]
The broader solve would be state-specific actions and locations:
- define the states (pre-release, in cinemas, between cinema & blu ray, out on blu-ray)
- define the actions (do nothing, get a certain quality or upgrade the quality)
- and define locations (some people keep libraries for "cam" captures, keeping main library "pure)

Stop there and imagine how nice it would be to have that level of logic in a movie download tool -- and how we've had to work around a certain potato's limitations.

Now, when Radarr adds a movie and comes back with movie info, it already suggests a location and a quality, based on your last input.  Having the ability to override a default = fantastic, but the suggestion from Radarr should ideally come from the defaults set as described above.   

Having an explicit action to "upgrade at this state" means that if you have a screener, it is replaced, but if you do not have one, it simply gets a high quality version.

**Comment by galli-leo** [comment]
@toddcurry @SuperPotatoMen (@fedoranimus @onedr0p Can you chime in on this, what you think about it?) My current implementation looks like this:
Five monitor states:
- Unmonitored (same as now)
- Monitored (same as now)
- Monitored after cinemas release (For grabbing cams, ts, etc.)
- Monitored after bluray / web release (for grabbing blurays, web-dl)
- Monitored according to predb: When a scene release of the movie appears on PreDB, monitor the movie and download accordingly (Useful for grabbing Screeners, early blurays etc.) Will probably be the default.

Maybe an advanced options to start monitoring x amount of days before the actual release.

**Comment by SuperPotatoMen** [comment]
@galli-leo looks good. Maybe one more option: Afther cinemas release, bluray /web release and predb, you can delay it X days for a better release.

**Comment by galli-leo** [comment]
@SuperPotatoMen This can already be achieved with a delay profile. If you setup one, it will delay all releases until a better one is found.

**Comment by SuperPotatoMen** [comment]
@galli-leo i didn't know that sorry! One more question, is it possible to add a option in the api so we can send from Ombi a request with a monitor state (that the user can config in the ombi settings)

**Comment by galli-leo** [comment]
@SuperPotatoMen Should very much be possible. Since our UI also uses the API, we have to update the API to support these states anyways :)

**Comment by SuperPotatoMen** [comment]
@galli-leo cool! I just open a issue on our site to support this. Can you inform us when its live? (https://github.com/tidusjar/Ombi/issues/1145)

**Comment by toddcurry** [comment]
Galli-leo, I think that works.  A couple of suggestions:
- Unmonitored -- you'll be happy later in debugging to have Unmonitored - by user differentiated from Unmonitored - by rule.  
- Monitored status in your list will become, by reduction, movies that are pre-cinema release, right?  You might just make that clear by calling it something.  Not enough coffee to offer you a great name for that...

Having a delay profile with some flexibility in timing would be great.

**Comment by galli-leo** [comment]
@SuperPotatoMen Probably not in the next few days or even weeks. But I will surely mention it.

@toddcurry Maybe Always monitored?

**Comment by toddcurry** [comment]
Or "Awaiting Release"?

**Comment by geogolem** [comment]
Isnt there already a precedent for what to call these.
![image](https://cloud.githubusercontent.com/assets/23205277/23100106/d116e004-f645-11e6-85ad-7ac17e1c8e97.png)

**Comment by geogolem** [comment]
i dont think we need to touch the monitoring code.. but perhaps have another field on the movieInfo object called AvailabilityTarget or something..

This can be user defined for each movie... and then have another check separate from the monitoring which accept/rejects the movies based on this criteria

so in order for a download to happen.. it would have to be monitored + meet the availability criteria

**Comment by onedr0p** [comment]
Added in nightly.
