### ISSUE TITLE
Coupling of UNKNOWN movies currently downloading.

### ISSUE THREAD

**Issue by rsunde** [Radarr/Radarr#7400]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

A movie title might be long and the regular automagical search wont find it, as such I have to search manually and add to download client.

UFC events in my case.

### Describe the solution you'd like

Ability to couple an active UNKNOWN movie in the queue with a monitored movie.

ability to couple from 
1. movie page (extra tab perhaps)
2. active queue, similar to when importing.

### Describe alternatives you've considered

download manually and them import works just fine.

### Anything else?

not at this time.

[AB#3333](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3333)

**Comment by ta264** [comment]
What's the point? What would it achieve? You'll still have to manually import at the end like you do now.

**Comment by rsunde** [comment]
why?

if the coupling is achieved manually by me, then the whole thing will work as if the search worked,
the download might be slow, and I want to stream the movie at a later time away from home without the possibility to manually import at the end of the download...

**Comment by ta264** [comment]
So you just want to set radarr to blindly import whatever comes in as part of the torrent when it finishes downloading? No plans for that.

**Comment by rsunde** [comment]
No,

I explained that I have manually added something to the download client, Radarr actually sees this in the ACTIVE QUEUE as an UNKNOWN movie, all I want to be able to do is say that it is NOT AN UNKNOWN movie, but to couple it with a correct movie.

thus once the the download is complete it will do everything as normal.

the coupling UI stuff is already in the application in the form of MANUAL IMPORT functionality.

**Comment by ta264** [comment]
Identification in the queue (based on releass name) is separate to identification on import (based on file name) and there are no plans to change this. Importing a torrent blindly based on only the release name is not a good idea.

**Comment by rsunde** [comment]
Feels like we are talking about different things...

if I interactively search for a release and then hit the download button,
something is sent to the download client and the movie is coupled with this download.

all I am asking is being able to do that coupling manually, no identification logic needed.

**Comment by ta264** [comment]
What I'm telling you is that doing that coupling wouldn't affect the import, because the movie being coupled in the queue has nothing to do with whether it imports or not.

If you want to discuss this further please join the discord channel where people can explain how the import process works in more detail.

**Comment by rsunde** [comment]
I suspect its a rather quick fix for an experienced Radarr contributor which is why I added a small feature request, 

I guess I will have to provide my own pull request 💪.

**Comment by ta264** [comment]
As one of the devs I can tell you it's not a small change, and even if you succeeded it would be unlikely to get merged. Importing stuff blindly based on just what was grabbed is not how we want radarr to work. What if the torrent was mislabelled on the tracker and contained something different,

**Comment by rsunde** [comment]
importing blindly?

I have added the torrent... ME... smarter than any search engine or filename title match logic any dev have created.

anyway.

**Comment by austinwbest** [comment]
> importing blindly?
> 
> I have added the torrent... ME... smarter than any search engine or filename title match logic any dev have created.
> 
> anyway.

I think you are missing a little understanding.. There is no physical link somewhere for things in queue. The item in queue is matched to a movie on the fly based on the release name.

What you would need to do in theory is rename the release in the download client so radarr can match it on the fly. A proper name and year to something it can match to on tmdb.

That help understand?
