### ISSUE TITLE
Movie not getting downloaded with error: "will only be considered available 0 days after Released"

### ISSUE THREAD

**Issue by shadyabhi** [Radarr/Radarr#7402]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I hit "Search Movie", the workflow which is executed as scheduled tasks, all the "correct releases" get rejected with `will only be considered available 0 days after Released`

However, if I use the `Search` tab, it gets classified as a proper release, without any `exclamation marks`. 

Movie link: https://www.themoviedb.org/movie/888268-anek
The movie is configured with `Minimum Availability = Released`.  

* The release date is not logged in `trace logs`. Do you think we can add it? 
* What's causing this classification reason? I've verified that there is no `Delay configured` in the profile. 

### Expected Behavior

The releases should be accepted as the `Release Date` is in the past. 

### Steps To Reproduce

Add movie: https://www.themoviedb.org/movie/888268-anek
Try the automated `Search Movie` workflow.

### Environment

```markdown
Radar: 4.1.0.6175
Package Version: 4.1.0.6175-ls145 by linuxserver.io
```

### What branch are you running?

Master

### Trace Logs?

It was too big, so uploaded it here:- https://abhi.host/radarr.trace.txt

[AB#3338](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3338)

**Comment by bakerboy448** [comment]
That movie only has Theatrical release dates on TMDb. The automatic search ignoring it as not available is accurate.

**Comment by shadyabhi** [comment]
Why does the item not get listed as invalid in manual Search tab? 
Also, we should work on improving logs to make it less confusing and more obvious.

**Comment by bakerboy448** [comment]
Manual Search is just that a manual search and thus it's assumed the user knows when they're looking for it.  The availability is not a release reject reason.   It'd prevent RSS grabs and not do an auto search.

**Comment by shadyabhi** [comment]
Search tab should show an exclamation mark to hint the user why a particular release was rejected by auto search. It was unclear and I had to enable trace logs where it was unclear as well. Logs could be better as well to make it clearer.

Is this a sonarr design decision, or radarr?

**Comment by bakerboy448** [comment]
The UI clearly indicates if a movie is consider available or not.  It's on the movie index and the movie's page itself as the Status.

Why are additional details needed that already exists?

Again, releases are not rejected.  Why would you want to misinform the user and claim a release is rejected when it is not?

Again, Availability impacts RSS grabs and auto search....it does not impact manual search, why should every result in a manual search - that the user triggers - be rejected no valid reason?

**Comment by shadyabhi** [comment]
>Again, Availability impacts RSS grabs and auto search

First of all, thanks a lot to explain in detail, I really appreciate it. @bakerboy448. I'm a `developer myself`, so I understand your side perfectly. However, it is not user-friendly, let me explain why. 

* When a user adds the movie, here is what they see. Here, they opt to choose `Released` in the hope to avoid downloading fake torrents. (public torrents user)
![image](https://user-images.githubusercontent.com/631797/177375059-076fe8c4-b9c0-4912-b44b-232ab68c10af.png)

* User notices, despite the release date, the movie didn't download automatically via RSS feeds. The user does a manual search to debug but can't see an `exclamation mark` against releases. So, as a user, he's puzzled why it didn't end up downloading. 
<img width="1566" alt="image" src="https://user-images.githubusercontent.com/631797/177375710-e9cea224-434b-45e5-b13b-8b2f68454ee2.png">

For general workflows as simple as this one, a user shouldn't be forced to turn on trace logging, open documentation, and read wiki pages just to get an answer as simple as this.  @bakerboy448  Please note, I'm only saying the user side of things, as a developer you are absolutely right, but here, I see an opportunity to improve. 

We have the following challenges in implementation currently:- 

* Release date is different for `Theatre` and `Digital/Physical`. As it is user-contributed, it might always be up-to-date. In this case, the movie is already up on Netflix. 
    * UI shows this particular situation as `Not Available` in status, but it is confusing when the `Release` date is already populated with a date in the past. 

As a proposal, the UI can probably do a better job of making distinction b/w `Digital/Physical` and `Theatre` release dates. Once that's there, things will start to make more sense. 

If this is more of a sonarr territory as radarr is a maintained fork, I understand and I appreciate you taking the time to make me understand what's really happening and I won't pursue this further :)

**Comment by bakerboy448** [comment]
The release dates are already differentiated with unique icons when you however over the year like you've already done.

The UI clearly indicates the movie is not available.  Torrent/Usenet Release upload dates have no relevance to a movie's availability.

It comes down to the user not knowing what availability is or not seeing that that the movie is clearly indicated as "Not Available"

I'm not sure why you want features that already exist and are clear in the UI. I think the only missing piece is then a tooltip hover over the theater/digital/BluRay icons in the release date hover over in case the icons themselves aren't clear enough.

**Comment by shadyabhi** [comment]
I'll personally remember it from now on :), this was just an attempt to make it useful for all users. 

@bakerboy448, thanks for your time and I truly appreciate the quick responses here which is remarkable. Thanks for maintaining a really helpful tool that I use every single day.
