### ISSUE TITLE
Round numbers in ratings

### ISSUE THREAD

**Issue by herkalurk** [Radarr/Radarr#7404]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Rating appears to have 15 decimal places

### Expected Behavior

Only 1 decimal place rounded

### Environment

```markdown
- OS: Centos 7
- Radarr: 4.1.0.6175
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Chrome 103.0.5060.114
```

### What branch are you running?

Master

### Trace Logs?

Screenshots showing tmdb rating 

![image](https://user-images.githubusercontent.com/2532699/177385982-7df6c59c-e05e-4869-8b1c-dac9b47ba2fa.png)

![image](https://user-images.githubusercontent.com/2532699/177386342-486473ff-c2ca-4fbf-a65c-5b5800f029e5.png)

[AB#3340](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3340)

**Comment by bakerboy448** [comment]
Fixed in nightly

https://github.com/Radarr/Radarr/commit/0a77a13fa821a923186b1a973fec90b81e1e1522

**Comment by erri120** [comment]
![image](https://user-images.githubusercontent.com/16577545/180501310-85d5be12-b3f8-4bb8-b5f2-ac76da4ce623.png)

The rating in the movie discovery info still has this "bug" (Radarr 4.2.1.6446). I believe this is the code responsible for that: https://github.com/Radarr/Radarr/blob/43910af1273b4ed2226008333325f528a02f8d47/frontend/src/DiscoverMovie/Overview/DiscoverMovieOverviewInfo.js#L72-L78
