### ISSUE TITLE
Suggestions for Importing Functions

### ISSUE THREAD

**Issue by knight-sq** [Radarr/Radarr#7408]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

You are advised to add an official file and delete the original file after the file is imported. Otherwise, the original file still exists after the import, which will occupy two copies of space

### Describe the solution you'd like

You are advised to delete the original file after the import is successful

### Describe alternatives you've considered

There is no

### Anything else?

There is no

[AB#3345](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3345)

**Comment by ta264** [comment]
I don't really understand what you're asking for. But I think it's to do with removing seeding copies of torrents which we have no plans to change.

**Comment by bakerboy448** [comment]
Also in a proper setup that supports hardlinks, double space is not used

**Comment by austinwbest** [comment]
Hardlinks does not define a 'proper' setup.
