### ISSUE TITLE
Unable to parse, unicode being incorrectly displayed

### ISSUE THREAD

**Issue by thezoggy** [Radarr/Radarr#741]
Radarr Ver. 0.2.0.344

on the log screen I see:
```
17-2-13 10:55:55.4|Debug|Parser|Parsing string 'Edgar Wallace l�st den Fall - Folge 1 - Der unheimliche Pfeifer von Blending Castle'
17-2-13 10:55:55.4|Debug|Parser|Unable to parse Edgar Wallace l�st den Fall - Folge 1 - Der unheimliche Pfeifer von Blending Castle
```

looking at the title on newznab:
`Edgar Wallace löst den Fall - Folge 1 - Der unheimliche Pfeifer von Blending Castle`

on the rss feed
`<title>Edgar Wallace löst den Fall - Folge 1 - Der unheimliche Pfeifer von Blending Castle</title>`

**Comment by galli-leo** [comment]
Could you maybe post the whole RSS feed? So we can add a test later on.

**Comment by onedr0p** [comment]
I believe This was fixed. Closing.
