### ISSUE TITLE
Stop Radarr from re-downloading movies already downloaded

### ISSUE THREAD

**Issue by JayBoom** [Radarr/Radarr#7413]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

For some reason Radarr will download movies even if I already have them.

Scenarios:

Same quality movie (1080p) but smaller file (will redownload even if watched through plex)
Better quality movie (1080p exists but downloads 2160p if for some rare reason the quality isn't set)
How do I basically tell it, if the file exists or the movie is already there, don't download it, unmonitor the movie?

Thanks!

### Expected Behavior

Unmonitor movies that have successfully downloaded

### Steps To Reproduce

1. Download a movie

### Environment

```markdown
- OS: Ubuntu 20.04
- Radarr: Radarr 3.0.8.1507
- Docker Install: Yes
- Using Reverse Proxy: No
```

### What branch are you running?

Master

### Trace Logs?

Unfortunately my trace logs are empty sorry

[AB#3352](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3352)

**Comment by ta264** [comment]
See https://wiki.servarr.com for the quick start guide

**Comment by JayBoom** [comment]
> See https://wiki.servarr.com for the quick start guide

I've been using Radarr for 3 years and it's still an issue :(

**Comment by ta264** [comment]
It's not an issue, you've had it set up wrong for 3 years. Use one of the support options to get straighted out.

**Comment by JayBoom** [comment]
> It's not an issue, you've had it set up wrong for 3 years. Use one of the support options to get straighted out.

Ah yes "It's not an issue" yet its a well known bug

8 people have experienced it here: https://github.com/Radarr/Radarr/issues/1428

and more here
https://www.reddit.com/r/radarr/comments/e5b501/stop_redownloading_movies/

https://bytemeta.vip/repo/Radarr/Radarr/issues/7225

**Comment by ta264** [comment]
People on discord will be able to help you get everything set up right.
