### ISSUE TITLE
Movie endpoint very slow

### ISSUE THREAD

**Issue by dawnerd** [Radarr/Radarr#7423]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

/api/v3/movie takes ~30 seconds to load, response is 19.6MB. Loading locally so it shouldn't be network related - maybe related to #7318

### Expected Behavior

Load under <10s at least

### Environment

```markdown
- OS: Unraid 6.10.3 w/ linuxserver/radarr:nightly
- Radarr: 4.2.0.6430
- Docker Install: Yes
- Using Reverse Proxy: Yes (tested without as well)
- Browser: Chrome Mac 103.0.5060.114 (Official Build) (arm64)
```

### What branch are you running?

Nightly

### Trace Logs?

[trace-logs.txt](https://github.com/Radarr/Radarr/files/9137035/trace-logs.txt)

Didn't see any relevant errors

Thought maybe it was sqlite so switched to postgres but that didn't improve anything.

Maybe some useful db stats?:

Collections: 520
Movies: 3575
MovieTranslations: 83151
MovieMetadata: 3592
History: 29366
Credits: 177041
AlternativeTitles: 23430

A quick look seems like indexes are in there.

[AB#3372](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3372)

**Comment by bakerboy448** [comment]
logs / using the load time in the middle of a download client refresh certainly doesn't help the load times.  but the issue is typically disk IO if the response times are slow.

is the 30s consistently repeatable?

DB on an SSD?

**Comment by dawnerd** [comment]
Yep on an ssd. CPU/Disks are pretty idle while the request is going - this is a pretty overbuilt server tbh.

it's always around 30s, I've been doing some curl calls to check just as you mention about it being during a download/import/etc. Doesn't seem to have any impact.

Would it help to have a copy of the sqlite db? The movie endpoint response?

**Comment by bakerboy448** [comment]
It'll be extremely spammy, but add `<LogSql>True</LogSql>` to your config and restart radarr.  that'll have it log out all the sql queries to narrow down which is/are taking a signifcant time.

**Comment by dawnerd** [comment]
<details>
<summary>query traces</summary>

```
2022-07-18 20:38:13.9|Trace|Http|Req: 39 [GET] /api/v3/movie (from 192.168.1.1 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36)
2022-07-18 20:38:13.9|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2022-07-18 20:38:13.9|Trace|ConfigService|Using default config value for 'movieinfolanguage' defaultValue:'1'
2022-07-18 20:38:13.9|Trace|ConfigService|Using default config value for 'availabilitydelay' defaultValue:'0'
2022-07-18 20:38:13.9|Trace|SqlBuilderExtensions|
==== Begin Query Trace ====

QUERY TEXT:
SELECT "Profiles".*
 FROM "Profiles"       

PARAMETERS:

==== End Query Trace ====


2022-07-18 20:38:13.9|Trace|SqlBuilderExtensions|
==== Begin Query Trace ====

QUERY TEXT:
SELECT "MovieTranslations".*
 FROM "MovieTranslations"    WHERE ("MovieTranslations"."Language" = @Clause1_P1)
   

PARAMETERS:
Clause1_P1 = [{
  "id": 1,
  "name": "English"
}]

==== End Query Trace ====


2022-07-18 20:38:13.9|Trace|SqlBuilderExtensions|
==== Begin Query Trace ====

QUERY TEXT:
SELECT "AlternativeTitles".*
 FROM "AlternativeTitles"       

PARAMETERS:

==== End Query Trace ====


2022-07-18 20:38:14.3|Trace|SqlBuilderExtensions|
==== Begin Query Trace ====

QUERY TEXT:
SELECT "Movies".*, "MovieFiles".*, "MovieMetadata".*
 FROM "Movies"   
LEFT JOIN "MovieFiles" ON ("Movies"."MovieFileId" = "MovieFiles"."Id")
LEFT JOIN "MovieMetadata" ON ("Movies"."MovieMetadataId" = "MovieMetadata"."Id")
    

PARAMETERS:

==== End Query Trace ====


2022-07-18 20:38:40.1|Trace|Scheduler|Pending Tasks: 0
2022-07-18 20:38:44.6|Trace|Http|Res: 39 [GET] /api/v3/movie: 200.OK (30699 ms)
2022-07-18 20:38:44.6|Debug|Api|[GET] /api/v3/movie: 200.OK (30699 ms)
```
</details>

Running those queries manually, response times:

Profiles: 1 rows fetched, 8ms (1ms fetch)
Translations: 3575 rows fetched, 44ms (2ms fetch)
Alternative titles: 23430 rows fetched, 87ms (12ms fetch)
Movies: 3575 rows fetched, 1.89s (72ms fetch)

That last one looks like it's not using the indexes like it should be. I do notice theres no index for `MovieFileId` but manually adding one in didn't seem to really help any. Also did some config tuning on postgres but that also didn't seem to make any meaningful change. Maybe down a second.

```
Node Type	Entity	Cost	Rows	Time	Condition
Hash Join	[NULL]	540.18 - 1137.91	3575	31.832	("Movies"."MovieFileId" = "MovieFiles"."Id")
Hash Join	[NULL]	127.44 - 715.77	3575	17.667	("MovieMetadata"."Id" = "Movies"."MovieMetadataId")
Seq Scan	MovieMetadata	0.00 - 578.90	3592	7.171	[NULL]
Hash	[NULL]	82.75 - 82.75	3575	5.158	[NULL]
Seq Scan	Movies	0.00 - 82.75	3575	2.669	[NULL]
Hash	[NULL]	368.44 - 368.44	3548	7.735	[NULL]
Seq Scan	MovieFiles	0.00 - 368.44	3548	3.482	[NULL]

```

**Comment by ta264** [comment]
I can't replicate this.  On a test database with 3800 movies it responds in 500ms for me using sqlite.  I think if you want to debug this further, join the discord channel and if it turns out to be a bug we can re-open

**Comment by austinwbest** [comment]
HDD, not SSD so just for a visual...

~350 collections
~2000 movies

![image](https://user-images.githubusercontent.com/8321115/179763378-c8004412-f0d3-441c-b390-0a086ca0df1b.png)
