### ISSUE TITLE
Mark existing movie as "bad quality" and re download

### ISSUE THREAD

**Issue by th0str** [Radarr/Radarr#7425]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

If I have a movie in my library that mets the conditions, but is unwanted in other way, the only way to current redownload is to delelete exsisting movie and lat radarr pick up a new movie. I would like to keep the existing copy untill a new version is downloaded that mets my requrements 

### Describe the solution you'd like

I would like to have a flag a status as ie "unmet quality" so Radarr replaces my existing movie then a new version is available

### Describe alternatives you've considered

na

### Anything else?

na

[AB#3375](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3375)

**Comment by ta264** [comment]
Set up your quality profiles properly and radarr will upgrade things. You might want to read the quick start guide on the wiki, seems you're missing how radarr works.

**Comment by bakerboy448** [comment]
> I want to let Radarr replace an exsisting with the same conditions.

Again, that is how Radarr works.  Your quality profile needs to allow upgrades.  Radarr will not upgrade if the quality cutoff is met unless it's the same or better quality and improves the custom format score. This is explained in the QuickStart guide.

**Comment by th0str** [comment]
wich is why i am making a feature request to change that....

**Comment by th0str** [comment]
cancel this ticket..

**Comment by bakerboy448** [comment]
Basically mark a release as invalid to allow Radarr to replace it even if the release it finds isn't an upgrade?

That's a lot of effort for something that already has existing options and shouldn't need to be done more than a handful of times every few years if at all. If it's happening often then you need to 1) get better sites and 2) use custom formats to avoid those groups.

Immediate Fixes:
- mark the grab as failed which will blocklist that release and trigger a search
- trigger an automatic search
- do an interactive search

Helpful settings:
- set your quality profile correctly and ensure preferring repacks/propers are set (or a custom format is used to do so)
- set/create/score your custom formats appropriately to avoid groups that release shit releases.
