### ISSUE TITLE
ntfy.sh for notification

### ISSUE THREAD

**Issue by mabed-fr** [Radarr/Radarr#7434]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

no

### Describe the solution you'd like

no

### Describe alternatives you've considered

no

### Anything else?

Hello,

Can you add ntfy.sh integration for notifications?

https://ntfy.sh/

Regards,

[AB#3383](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3383)

**Comment by bakerboy448** [comment]
I don't see how this already cannot be accomplished via the existing custom script functionality.

create the necessary custom scripts and have them send the payload to ntfy

**Comment by Qstick** [comment]
> I don't see how this already cannot be accomplished via the existing custom script functionality.

Same could be said for notifiarr or any other implementation we have.

**Comment by mabed-fr** [comment]
> > Je ne vois pas comment cela ne peut déjà pas être accompli via la fonctionnalité de script personnalisé existante.
> 
> La même chose pourrait être dite pour notifiarr ou toute autre implémentation que nous avons.

Hello,

Yes I agree with you a specific integration is more efficient and adapted
