### ISSUE TITLE
stand-alone files and collections/trilogies folder support

### ISSUE THREAD

**Issue by Mellowlynx** [Radarr/Radarr#7437]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I run Plex and have it setup that movie collections/trilogies are in there own folder collection that contain the movie files.
(Police Academy, Harry Potter, Matrix, LotR, etc) My solo movies are just in a movies root folder, this to keep the movies folder clean.

### Describe the solution you'd like

It would be great if Radarr would support this way of saving collections. (It's fine if it's only recognize then and not saving them there)

Also support for stand-alone movie files in the movie root folder would be great.

I don't need a folder with the movie name just to save the movie in there, just save the movie in the root.
(as a bonus this will also keep the inode as low as possible)

### Describe alternatives you've considered

I might temporarily move my solo movies to there own folder, this is not going to happen for the collections/trilogies.

### Anything else?

Small overview of my movies folder:

Movies
├── We.Bought.a.Zoo.mkv
├── Studio Ghibli
│   ├── My neighbour Totoro.mkv
│   ├── Kiki's delivery service.mkv
│   └── And more...
├── Police Academy - The Complete Collection
│   ├── 01 Police Academy.mkv
│   ├── 02 Police Academy 2 Their First Assignment.mkv
│   └── And more...
├── Red.Notice.2021..mkv
└── Teen Spirit.2019.avi

[AB#3385](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3385)

**Comment by ta264** [comment]
Duplicate #153
