### ISSUE TITLE
Can't set Movie Folder Format to blank

### ISSUE THREAD

**Issue by adefaria** [Radarr/Radarr#7444]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The current default for Movie Folder Format is {Movie Title} ({Release Year}) but I don't want my movies submerged in yet another folder. This increases the length of the path name and can cause problems.

### Expected Behavior

I expected Radarr to allow me to blank out Movie Folder Format or have a toggle to say "do not place the movie into any subfolder". 

### Environment

```markdown
- OS: Synology DSM 7.x
- Radarr: Docker container
- Docker Install: ??? Yes.
- Using Reverse Proxy: Yes.
- Browser: Chrome/Firefox Linux
```

### What branch are you running?

Master

### Trace Logs?

What are we tracing here? I merely want to be able to say "no subfolders please".

[AB#3391](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3391)

**Comment by bakerboy448** [comment]
- Not a bug
- Radarr requires all movies to be in their own folder 
- `docker container` is not a radarr version

Please use one of the support channels: [Reddit](https://www.reddit.com/r/radarr/) or  [Discord](https://radarr.video/discord) for support/questions.

**Comment by adefaria** [comment]
Did I say it was a bug? 

Requiring movies to be in their own folder is a silly and needless restriction.

I am running radarr in a docker container. Quite frankly that's irrelevant to the request at hand.

**Comment by bakerboy448** [comment]
> Did I say it was a bug?

You filed a bug report, so yes.


> Requiring movies to be in their own folder is a silly and needless restriction.

Dropping that restriction may never occur...it requires a significant rewrite that touches almost every aspect of radarr.

**Comment by adefaria** [comment]
That seems strange! Surely just specifying "./" or some symbol representing that would work... 

Anyways, it seems clear to me that you guys are against making this work or even trying so I'll just have to implement my own solution.

**Comment by austinwbest** [comment]
> Anyways, it seems clear to me that you guys are against making this work or even trying so I'll just have to implement my own solution.

Couchpotato i think it is called allows for a flat file system bud.

**Comment by adefaria** [comment]
Huh? You make no sense.

**Comment by austinwbest** [comment]
> Huh? You make no sense.

Well, Radarr doesn't allow for dumping all your movies into a single folder, Couch potato does. Seems like it made sense in my head but my mistake.
