### ISSUE TITLE
Radarr.Common - Could not load file or assembly

### ISSUE THREAD

**Issue by ekimseekem** [Radarr/Radarr#7446]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I've upgraded to v4.2.0.6438 and get the following error trying to execute `/opt/Radarr/Radarr`

> Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Radarr.Common, Version=4.2.0.6438, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

> File name: 'Radarr.Common, Version=4.2.0.6438, Culture=neutral, PublicKeyToken=null'

Can't find the file manually on the file system, no permissions have changed, just upgraded from the WebUI. 

I do not use the radarr user account however, I have a service account i use to run Radarr, Sonaar, etc. I've logged into that account and tried the command also, same error.

### Expected Behavior

Expecting to start and run Radarr on port 7878.

### Environment

```markdown
- OS: Ubuntu 18.04.6
- Radarr: 4.2.0.6438
- Docker Install: n/a
- Using Reverse Proxy: no
- Browser: n/a
```

### What branch are you running?

Develop

### Trace Logs?

Only the above output returns useful troubleshooting info. Logs under `/home/run-user/.config/Radarr/logs` do not contain entries since running the update from the webUI.

[AB#3397](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3397)

**Comment by bakerboy448** [comment]
Reinstall.

Seems something on your system messed with the tmp dir when the update took place and deleted files. If you look at the updater logs that should confirm that.

**Comment by ekimseekem** [comment]
Yup, reinstall fixed the issue.

I've attached the update log in case the developer would like to further troubleshoot:
[2022.07.26-23.32.txt](https://github.com/Radarr/Radarr/files/9204591/2022.07.26-23.32.txt)

**Comment by bakerboy448** [comment]
There's nothing to debug nor troubleshoot.

Your system or something on it deleted files in the /tmp directory causing the update to fail.

```
2022-07-26 23:32:37.3|Error|InstallUpdateService|Failed to copy upgrade package to target folder.

[v4.2.0.6438] System.IO.FileNotFoundException: Could not find file '/tmp/radarr_update/Radarr/Microsoft.AspNetCore.WebUtilities.dll'.
```
