### ISSUE TITLE
Slow to load library

### ISSUE THREAD

**Issue by stevenatherton42** [Radarr/Radarr#7452]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I open Radar in the web browser, it takes several minutes for the list of movies to load. I discovered this when trying to run Ombi and noticed Radarr was the only program which doesn't send the request. Sonarr and Lidarr work fine.

The log file of Ombo states the request to Radarr times out which I presume is connected to the slow load times in Radarr.

Once the library is loaded in Radarr, I seem to be able to navigate as normal, until I refresh the page.

### Expected Behavior

Radarr to load the library faster and requests from Ombi to be processed and not timeout

### Steps To Reproduce

1. Load Radarr
2. Wait several minutes

### Environment

```markdown
- OS: Windows 10
- Radarr:4.2.0.6438
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Chrome
```

### What branch are you running?

Develop

### Trace Logs?

[radarr.txt](https://github.com/Radarr/Radarr/files/9227002/radarr.txt)

[AB#3406](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3406)

**Comment by RobinDadswell** [comment]
You have multiple errors around connecting to download clients and root folders; these shouldn't be causing it but may be. You also have not includes trace logs but regular logs and the log file is the entire file and not a section around the relevant bit. 

This is also support and not a bug. Please swing by discord about this https://radarr.vide/discord
