### ISSUE TITLE
Improve checks for determining if Radarr is deployed via a container

### ISSUE THREAD

**Issue by onedr0p** [Radarr/Radarr#7456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I run Radarr in a container in Kubernetes and Kubernetes uses the [containerd](https://containerd.io/) CRI (container runtime interface) instead of Docker.

The following check seems to only look for docker to check if radarr is deployed via a container.

https://github.com/Radarr/Radarr/blob/develop/src/NzbDrone.Common/EnvironmentInfo/OsInfo.cs#L80-L83

In my container the output of this command is:

```
cat /proc/1/cgroup
0::/
```

Maybe it is worth renaming this check in source and in the UI to `IsContainer` to be more accurate as Docker isn't the only kid on the block.

### Expected Behavior

Probably set `IsDocker` to true if Radarr is running in a container using any CRI.

### Steps To Reproduce

Deploy Radarr via a container using a different CRI other than Docker.

### Environment

```markdown
- OS: Fedora Server 36
- Radarr: 4.2.0.6438
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Chrome
```

### What branch are you running?

Develop

### Trace Logs?

N/A

[AB#3420](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3420)

**Comment by onedr0p** [comment]
According to this [stackoverflow](https://stackoverflow.com/questions/20010199/how-to-determine-if-a-process-runs-inside-lxc-docker) discussion, there doesn't seem to be a great way of telling if the app is running in a container. Maybe we should make this an environment variable that LSIO/Hotio/etc containers can set? e.g. if `CONTAINER_INSTALL=true` Radarr  will check for this and apply logic accordingly.

**Comment by psylenced** [comment]
Just something to note on this issue.

I run Radarr inside a LXC container, but I **do** want it to update via the normal process.

So it's a little more tricky than simply not updating if in **any** container.
