### ISSUE TITLE
iCal feed doesn't respond

### ISSUE THREAD

**Issue by matthewdias** [Radarr/Radarr#746]
**Description:**

The iCal feed for the calendar doesn't respond with any events. I tested it with google calendar, a desktop calendar app, and an online ical previewer.

**Radarr Version:**

0.2.0.288

**Comment by onedr0p** [comment]
Are you behind a reverse proxy with basic auth? If so you will need to not have basic auth set up for that path.

**Comment by onedr0p** [comment]
Fixed in next release
