### ISSUE TITLE
Remove filters from trakt user and trakt list 

### ISSUE THREAD

**Issue by Yuexiaochen** [Radarr/Radarr#7464]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior
![1](https://user-images.githubusercontent.com/64216534/183447898-1a3a6fe5-ae30-4642-8533-2b08c5d9146c.jpg)
![2](https://user-images.githubusercontent.com/64216534/183447925-a2573df4-2d00-4c95-b7fd-81f9d89486b9.jpg)
![3](https://user-images.githubusercontent.com/64216534/183447952-2f72d063-773a-44cf-b1a9-8fc61e2d9e9b.jpg)
![4](https://user-images.githubusercontent.com/64216534/183447972-cf729e5d-490b-4330-98fa-e00a18fe0492.jpg)

Filter year does not work

### Expected Behavior

The function cannot be filtered. The programmer friend said that code filtering was not enabled

### Environment

```markdown
- OS: archlinux
- Radarr:4.1.0.6175
- Docker Install:yes
- Using Reverse Proxy:no
- Browser:
```

### Trace [Logs?](url)

Master
[radarr.txt](https://github.com/Radarr/Radarr/files/9282766/radarr.txt)

[AB#3445](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3445)

**Comment by bakerboy448** [comment]
Trace logs are not optional for bug reports. They will show the url of the list and the additional parameters used.

no value was entered in the screenshot and thus no filtering is to occur

what trakt list type? Several have limited to no filtering options per Trakt's API

**Comment by Yuexiaochen** [comment]
> Trace logs are not optional for bug reports. They will show the url of the list and the additional parameters used.
> 
> no value was entered in the screenshot and thus no filtering is to occur
> 
> what trakt list type? Several have limited to no filtering options per Trakt's API.
> 
> There is no "code filtering" so not sure what your programmer friend looked at, but it doesn't sound like it was radarr's request generator for your trakt list type nor compared it to trakt's api to see if your list type even supports those filters

The information file has been updated. It doesn't work after the filtering is set. I hope that after the filtering time, the movies of the corresponding year will be downloaded instead of all

**Comment by bakerboy448** [comment]
For future reference
A log file is not trace logs nor does that appear to have anything with a list sync.

See the troubleshooting wiki article linked on the bug report template for how to get and provide trace logs

-—

Trakt User Lists do not support filtering. This is a Trakt API limitation. https://trakt.docs.apiary.io/#reference/users/list-items

**Comment by Qstick** [comment]
If that’s the case we probably shouldn’t have filter options for them…

**Comment by bakerboy448** [comment]
> If that’s the case we probably shouldn’t have filter options for them…

Been mentioned a few times before.

Partially bandaided in UI with https://github.com/Radarr/Radarr/commit/f6590e71d2f6378ee64cf61bf5ec4c6015b42553

**Comment by Yuexiaochen** [comment]
OK, then I need to find another way. Is there any other way to filter the time? This feature will be much more convenient for downloading movies

**Comment by Qstick** [comment]
Use TMDB lists or another list type
