### ISSUE TITLE
Trigger File Rename via API

### ISSUE THREAD

**Issue by Mundokiir** [Radarr/Radarr#7470]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I am running an automation to transcode files into alternate encodings for both audio and video, and need to inform Radarr when this happens. I'm able to trigger a refresh via the API using the /command endpoint which does work but the filename ends up with the OLD encoding information embedded into it (Think x264 etc..).

To remedy this I'm forced to login to the web interface and manually trigger a rename/organize. I'd like to instead automate the rename so that the filename contains the updated encoding information.

There's already a /rename endpoint but this appears to only return the result of what the rename WOULD be but not actually trigger the rename.

### Describe the solution you'd like

Add a PUT method to the /rename API endpoint to allow triggering the automatic rename process.

### Describe alternatives you've considered

I've tested using multiple other endpoints to see if I could trigger the rename but none seem to do so, including /moviefile, /movie/editor, /movie, and /command.

### Anything else?

The API documentation seems sparse so it's possible there's a method here that will do this that I missed. Especially in the /command endpoint, my searches on the internet suggest there's a lot of utility here but there doesn't seem to be any list of functionality that can be done here.

[AB#3451](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3451)

**Comment by bakerboy448** [comment]
Please use one of the support channels: [Reddit](https://www.reddit.com/r/radarr/) or  [Discord](https://radarr.video/discord) for support/questions.

Everything the UI does - including triggering the rename - is via the API.  View the network calls made by the API.

Rename is a command posted to the command endpoint
