### ISSUE TITLE
HQCAM is being parsed as HDTV

### ISSUE THREAD

**Issue by rmichelena** [Radarr/Radarr#7471]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

releases named "HQCAM" and "HQ PreDVD" are both being considered HDTV, which causes them to download even if you've configured to reject CAM.
e.g. [Whatever Movie 2022 1080p HQCAM x265-iDiOTS]) is being parsed as HDTV-1080p
e.g. [Whatever Movie (2022) 1080p HQ PreDVD Rip x264 AAC CineVood] is also being parsed as HDTV-1080p

### Expected Behavior

HQCAM should be considered CAM and PreDVD should be considered DVD (I'm not sure of this last one, as it states 1080p)

### Environment

```markdown
- OS: Ubuntu 18.04.6
- Radarr:4.1.0.6175
- Docker Install:yes
- Using Reverse Proxy:no
- Browser:any
```

### What branch are you running?

Master

### Trace Logs?

n/a

[AB#3453](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3453)

**Comment by bakerboy448** [comment]
Already fixed in nightly and develop
https://github.com/Radarr/Radarr/pull/7412
