### ISSUE TITLE
Super Long release titles messes up the UI

### ISSUE THREAD

**Issue by ItsME6969** [Radarr/Radarr#7472]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

super long release names prevent CFs and Scores to be visible.
![Screenshot 2022-08-11 192220 - Copy](https://user-images.githubusercontent.com/89707006/184274329-67067de0-7b84-4804-8374-792b64edc56a.jpg)

### Expected Behavior

Textwrap to new line or even animate the text to move across the screen so as to cover only one line and maybe set a max width for release titles

### Steps To Reproduce

Encounter super-long release titles

### Environment

```markdown
- OS: linux
- Radarr: 3.0.9.1555
- Docker Install: yes
- Using Reverse Proxy: no
- Browser: chrome
```

### What branch are you running?

Develop

### Trace Logs?

Screenshot attached

[AB#3454](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3454)

**Comment by bakerboy448** [comment]
> 3.0.9.1555

pretty sure that's a sonarr version not radarr

**Comment by ItsME6969** [comment]
lol had both of em running
4.1.0.6175
master

**Comment by Qstick** [comment]
This is getting re-worked in v5
