### ISSUE TITLE
Original Language in Custom Formats not working if it is the only CF condition 

### ISSUE THREAD

**Issue by ItsME6969** [Radarr/Radarr#7473]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Original Language still does not detect original movie languages. Previous discussion https://github.com/Radarr/Radarr/issues/6395

### Expected Behavior

Should detect Original Language as Original original language

### Steps To Reproduce

1. Create a CF with Original Language as the Filter
2. Find your favorite flick in whichever language
3. See that the CF doesn't register as it should

### Environment

```markdown
- OS: linux
- Radarr: 4.2.0.6438
- Docker Install: yes
- Using Reverse Proxy: no
- Browser: chrome
```

### What branch are you running?

Develop

### Trace Logs?

Happy to provide but I think this is a pretty straightforward test.
1. Create a CF with Original Language as the Filter
2. Find your favorite flick in whichever language
3. See that the CF doesn't register as it should

[AB#3455](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3455)

**Comment by bakerboy448** [comment]
@foux are you able to look at all?
Probably just needs tweaks after the metadata rework

likely related to #7348

**Comment by foux** [comment]
Hum, weird, I didn't have any issues. I'll look this weekend !

**Comment by foux** [comment]
@ItsME6969 still working for me. Can tiu provide some logs where it's not matching the original language ?

**Comment by ItsME6969** [comment]
@foux here you go https://pastebin.com/r76F2FU4

**Comment by bakerboy448** [comment]
Is this only impacting English original language or others as well?

**Comment by ItsME6969** [comment]
@bakerboy448 All. Tried with movies from different languages non register portuguese, german, spanish, etc they all dont but of course using their actual language registers.

**Comment by ItsME6969** [comment]
@bakerboy448 I think I'm also coming across another bug. I wanted to test out "unknown" as the language but I cant even have that as a filter i get the error `'Value' must not be empty.` 
![Screenshot 2022-08-12 115557 - Copy](https://user-images.githubusercontent.com/89707006/184425318-a9c4a056-19b8-4ee5-8862-9813159aa75c.jpg)

**Comment by foux** [comment]
@ItsME6969 are you sure your custom format is enabled in your profile? (ie you have given it a score), because there's nothing about custom formats in your logs.

And I've just tried again on my end with no issues.

**Comment by bakerboy448** [comment]
Json export of the custom format and screenshots of the quality profile and interactive search results for a movie are probably the 3 best pieces for looking further

**Comment by foux** [comment]
The score should of course be different than 0 (be it positive or negative)

**Comment by bakerboy448** [comment]
> The score should of course be different than 0 (be it positive or negative)

0 will still show, but it's just informational and doesn't impact grabs.  It _should_ be logged but not 100% sure there.

**Comment by ItsME6969** [comment]
was gonna say that the score doesntt matter

**Comment by ItsME6969** [comment]
CF Created

![1 - Copy](https://user-images.githubusercontent.com/89707006/184427325-cf42491f-4e39-4baa-97ea-8b4d263d5be1.jpg)
....
![2 - Copy](https://user-images.githubusercontent.com/89707006/184427351-98d2eff2-29d1-468e-a7e1-27a13075f35b.jpg)
....
Saved
....
Search
???doesnt show up
....
![3 - Copy](https://user-images.githubusercontent.com/89707006/184427426-9b929816-a9d4-462f-92c9-74ae9e423907.jpg)

`{
  "name": "ORIGINAL LANGUAGE",
  "includeCustomFormatWhenRenaming": false,
  "specifications": [
    {
      "name": "ORIGINAL LANGUAGE",
      "implementation": "LanguageSpecification",
      "negate": false,
      "required": true,
      "fields": {
        "value": -2
      }
    }
  ]
}`

**Comment by foux** [comment]
Can you give us logs after giving your CF a score please. Just the logs at the moment of the search

**Comment by foux** [comment]
And try setting "Any" as the language for the profile

**Comment by ItsME6969** [comment]
@foux 
Cleared the logs
Set to Any
Searched
Same result
Logs --- https://pastebin.com/ZTn2qZRU

**Comment by foux** [comment]
Nothing about the formats in your logs, I don't get it (not even the Amazon ones). Are you sure you're sending the right logs? Just asking because I really don't get it :/

**Comment by ItsME6969** [comment]
yea those are the trace logs unless you also want the debug and the info logs

**Comment by foux** [comment]
Oh yeah, we definitely need all the logs : trace + debug + info

**Comment by bakerboy448** [comment]
Trace contain trace+debug+info
Debug contain debug+info

**Comment by ItsME6969** [comment]
I guess that answers that. Nothing different in the debug log that I see isnt on the trace ones(no mention of custom formats (not even the Amazon ones)).

**Comment by foux** [comment]
Can you please just put the content on the `radarr.trace.txt` ? It should have way more logs that what you have on pastebin

**Comment by foux** [comment]
Well, I'm kind of lost here.  We can try to force logs : can you put a minimum score of any positive interger to your profile, and a score of any negative integer to your ORIGINAL LANGUAGE?

Thanks

**Comment by foux** [comment]
There seems to be an issue when there's *only* this condition in the CF (in my CF I've got Original + another language and it's working). If I create a CF with only Original I've got the same issue. I'll investigate that tomorow.

**Comment by ItsME6969** [comment]
@foux Thanks preicate that maybe also investigate the other bug where unknown cannot be set https://github.com/Radarr/Radarr/issues/7473#issuecomment-1213424358
It can be set in another older version that im also running 4.0.5.5981

**Comment by ItsME6969** [comment]
Thanks @Qstick for the fix working as intended now only thing not working is the unknown filter but eeh not worried about that now.
