### ISSUE TITLE
Custom Format Condition Size requires both Minimum Size and Maximum Size to be entered

### ISSUE THREAD

**Issue by darkzabat** [Radarr/Radarr#7477]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When entering a Size condition to a Custom Format, it requires both Maximum Size and Minimum Size to be entered.

### Expected Behavior

Only one of either Maximum Size or Minimum Size should be required for Size condition in Custom Format.

### Steps To Reproduce

1.  Create new Custom Format
2. Add Condition - Size
3. Do not enter Minimum Size
4. Put any number greater than 0 for Maximum Size
5. Save Condition - Size
6. Save Custom Format
7. Get error “'Min' must be greater than '0'.”

### Environment

```markdown
- OS: Fedora
- Radarr: 4.2.2.6482
- Docker Install: No
- Using Reverse Proxy: No
- Browser: N/A
```

### What branch are you running?

Nightly

### Trace Logs?

2022-08-14 10:40:37.9|Warn|RadarrErrorPipeline|Invalid request Validation failed: 
 -- Min: 'Min' must be greater than '0'.

[AB#3459](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3459)

**Comment by bakerboy448** [comment]
Does https://github.com/Radarr/Radarr/commit/192dd9c137451f6f73699de6f4337d26e2992f87 cover this then
Min is 0 or greater
Max must be greater than Min

**Comment by darkzabat** [comment]
> Does [192dd9c](https://github.com/Radarr/Radarr/commit/192dd9c137451f6f73699de6f4337d26e2992f87) cover this then
> Min is 0 or greater
> Max must be greater than Min

Yes, this seems like a good way to handle this.
