### ISSUE TITLE
Regex Not Matching Movie Title (Custom Format)

### ISSUE THREAD

**Issue by RileyXX** [Radarr/Radarr#7478]
`^(?=.*Prey)(?=.*[\ |\.]DV|.*[\ |\.]DoVi).*`

For some reason I just can't figure out a way to get radarr to match with this regex. I tested it in [regex101](https://regex101.com/r/u6LgH6/1) and it works fine there. When I change "Prey" to something else like DSNP it matches the same release just fine. Is there some kind of bug with radarr that doesn't let you query for the movie title?  I'm trying to block DV for a specific release since I was having playback issues.

**Comment by ta264** [comment]
Custom formats only match stuff after the year.

**Comment by RileyXX** [comment]
> Custom formats only match stuff after the year.

Thanks. I was scratching my head at this for the longest time. That kinda sucks I have a bunch of specific series blocked in the same way on sonarr and it works. I wish radarr offered the same flexibility.
