### ISSUE TITLE
Bulk Add - silent failure if SQL error

### ISSUE THREAD

**Issue by shushry** [Radarr/Radarr#748]
While debugging loading large title lists into Radarr using the bulk import feature, chasing down what I thought was a timeout and hang with a large page size, I discovered in the trace logs that if there is a SQL _error_ during import, the importer will silently fail and not import your selections (be it a full page of selections or even a single title).

A problem title would produce this in the trace log:

17-2-15 01:35:55.2|Trace|Owin|SQLite error (2067): abort at 53 in [INSERT INTO [Movies] ([TmdbId],[ImdbId],[Title],[CleanTitle],[SortTitle],[Status],[Overview],[Monitored],[ProfileId],[LastInfoSync],[Runtime],[Images],[TitleSlug],[Website],[Path],[Year],[Ratin

...unfortunately - that's it.   Nothing more.  Seems the error line was cut off due to length.   I couldn't lock down the exact cause of the error - but in some cases these were titles that were in a directory that had a different year for the title than reported by TMDB, such as:

"My Movie Title (2008)"   Located in /path/to/file/My Movie Title (2007)

Although that wasn't always the case.   Again, couldn't lock down the exact reason.

Suggestion would be - try to handle the sql error regardless, publish the error if you can to the log, and continue importing, skipping that item.

**Comment by Snorflake** [comment]
It's the same if the db is locked, as I discovered in #743

**Comment by shushry** [comment]
Interestingly, i'm seeing a lot of DB Locked messages in the trace log, during a lot of operations but this doesn't seem to stop bulk import operations - at least for me.   Only the SQL error above.

**Comment by Snorflake** [comment]
I tried in a different browser (chrome) and it worked fine.

**Comment by shushry** [comment]
I found the cause of the SQL error, at least at my end.  In some cases I had a movie twice, with two different years for the same title.   i.e, "My Movie (2008)" and "My Movie (2009)".   Not to be confused with two seperate movies with the same title, and different years.   This was a case of several copies of the SAME movie (id wise) but two different instances.     During the bulk add of a group of titles containing this, I'm sure it's running into a unique constraint issue and rejecting the batch.

Obviously this falls to the end user to have a reasonably "clean" collection - but as a suggestion to development, perhaps consider committing a title to the database one at a time,  instead of a big batch.  Might take a little longer, but at least you can get the good ones in and reject any that don't import (with a nice report at the end?).

**Comment by fedoranimus** [comment]
This issue seems to occur when a duplicate movie is being imported that already exists.

The UI is showing all movies that exist in a folder that aren't added _for that folder_. So, if you have the same movie in two places (or a few other situations), they will appear in the bulk import list, but will throw an exception upon import (because we only allow a movie to exist once).

I have a patch on a branch to fix the import issue, but I also need to dig into why they're showing up at all. There are several other QoL improvements I will try to make as well.

**Comment by fedoranimus** [comment]
Fixed by #785.
