### ISSUE TITLE
Translate sort titles and other info in Metadata (nfo) generation

### ISSUE THREAD

**Issue by KevoM** [Radarr/Radarr#7482]
### Is your feature request related to a problem? Please describe

~~If you set your Radarr in a different language, for instance French, the titles displayed (UI) are in English no matter what. Fortunately, you can format it to the desire language via {Movie.Title:country} (during importing and renaming of files)
But the sort title tag (.nfo) will stay exclusively in english...~~

When you set your Radarr in a different language, the sort title tag (.nfo) will stay exclusively in english...

### Describe the solution you'd like

- The sorted titles `<sorttitle>` should match the titles  `<title>` in generated .nfo

- Prevent Radarr to revert back manual changes of the titles

### Describe alternatives you've considered

Allowing selecting Alternate Name when adding movies
see : [https://github.com/Radarr/Radarr/issues/1447](url)

### Anything else?

The unmatched titles in nfo :

<img width="665" alt="Capture d’écran 2022-08-15 à 17 51 17" src="https://user-images.githubusercontent.com/8274366/184669943-d941790c-6e58-4419-98d4-27bc6d1cc23e.png">

Leading to this kind of unsorted library (i.e Jellyfin uses the sort title tag):

<img width="1652" alt="Capture d’écran 2022-08-15 à 17 48 24" src="https://user-images.githubusercontent.com/8274366/184671627-69d8e435-b5e4-4f8d-af6e-93e7a6a7d0d7.png">

Because of this sort title : 

<img width="924" alt="Capture d’écran 2022-08-15 à 17 48 54" src="https://user-images.githubusercontent.com/8274366/184671688-8594ca83-4b90-4279-8221-318c62d355e4.png">

[AB#3467](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3467)

**Comment by Qstick** [comment]
> If you set your Radarr in a different language, for instance French, the titles displayed (UI) are in English no matter what.

Not quite True, Titles in the UI are controlled by the setting Movie Info Language

![image](https://user-images.githubusercontent.com/376117/185031777-162e936b-c917-4fe4-a82d-635bead8c8c9.png)

Metadata translations need more work, so I'll leave this open given I can't find another issue which discusses it.

**Comment by KevoM** [comment]
Yes you right !
Most other infos are already in the correct language in Metadata. Except sort titles which could easily match titles
