### ISSUE TITLE
Scheduler - Tasks bug in Radarr

### ISSUE THREAD

**Issue by hellcry37** [Radarr/Radarr#7488]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

this is how it shows in radarr for me:

![tasks_radarr](https://user-images.githubusercontent.com/41516437/185341289-5a46d758-cda3-41df-9214-097d4f8aa28c.png)

### Expected Behavior

to actually say the correct duration, as you can see almost all reports 1d and something except one

### Steps To Reproduce

system -> tasks

### Environment

```markdown
- OS: Ubuntu 22.04 LTS
- Radarr: 4.1.0.6175
- Docker Install: Yes
- Using Reverse Proxy: no
- Browser: Firefox 103.0.2
```

### What branch are you running?

Master

### Trace Logs?

This is only a UI error is my best guess, 1d before every task duration is bogus I believe.

[AB#3473](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3473)

**Comment by bakerboy448** [comment]
typically this is indicative of a corrupt db or regional issues

what's the actual values in the commands table in the DV vs. the tasks

**Comment by hellcry37** [comment]
> 

please assume i am not a dev, because I am not!

before reporting this I've reinstalled everything re indexed etc so it cant be a corrupt db

what's the actual values in the commands table in the DV vs. the tasks - I have no idea what this means. Where do I look?

**Comment by bakerboy448** [comment]
DV = typoed "DB" = database

Tasks page in radarr

**Comment by hellcry37** [comment]
how can i see values in db? in tasks is not an issue

**Comment by bakerboy448** [comment]
Assuming you have a device with windows happy

Copy the database over and then use db editor for sqllite to view the data in the commands table

**Comment by RobinDadswell** [comment]
> before reporting this I've reinstalled everything re indexed etc so it cant be a corrupt db

When you reinstalled did you delete the database from the config directory that you presumably then reutilised on the new install? 

This seems like support as opposed to a bug at this point though so please swing by discord if you want more help on it. https://radarr.video/discord

**Comment by hellcry37** [comment]
> > before reporting this I've reinstalled everything re indexed etc so it cant be a corrupt db
> 
> When you reinstalled did you delete the database from the config directory that you presumably then reutilised on the new install?
> 
> This seems like support as opposed to a bug at this point though so please swing by discord if you want more help on it. https://radarr.video/discord

yes I've delete everything

@bakerboy448 I have db open where do i look?

**Comment by hellcry37** [comment]
> Assuming you have a device with windows happy
> 
> Copy the database over and then use db editor for sqllite to view the data in the commands table

in db everything is correct, if u remove from lastexecution the laststarttime all seem ok, is just in the ui somehow not sown correctly
