### ISSUE TITLE
Feature Request: Date and Rating Limit for imported movies from List

### ISSUE THREAD

**Issue by scoopydude2002** [Radarr/Radarr#749]
Would be nice to have a Date and Rating cut off limit for movies that are being automatically imported via the List. Maybe being able to disable/enable this limit for each individual list (for example you may want everything imported from your Trakt watchlist regardless of the date or rating).

**Comment by edru** [comment]
They have requested all feature requests be made at http://feathub.com/Radarr/Radarr and leave this place strictly for bugs.

**Comment by onedr0p** [comment]
Added trakt and tmdb filtering check it out :)
