### ISSUE TITLE
Add functionality to switch from unmonitored to monitored on release date

### ISSUE THREAD

**Issue by jluce50** [Radarr/Radarr#751]
One of CP's features that was really useful was the ability to not download anything until the release date. When you add a movie, there could a third option in the Monitor dropdown that says "Monitor at release" (or something). This goes a really long way toward preventing fakes and crappy CAM videos, etc.

**Comment by SuperPotatoMen** [comment]
dub: https://github.com/Radarr/Radarr/issues/740
