### ISSUE TITLE
Release and In Cinema dates are all over the place

### ISSUE THREAD

**Issue by jluce50** [Radarr/Radarr#752]
For some reason, the dates for most movies are all out of whack. Some titles on the calendar say Announced for the In Cinemas date. Others say In Cinemas for the Available date (see attached image).

Also, it's not clear how the Available and Announced dates should relate to the Physical Release date. It would be great if the terminology was consistent across the screens (I vote for Physical Release as that's less ambiguous).

Radarr Version: 0.2.0.299

![2017-02-15_101515](https://cloud.githubusercontent.com/assets/8754370/22983495/e5bf0bde-f367-11e6-85c2-8e47697cc5b3.gif)

**Comment by galli-leo** [comment]
Duplicate issue.
