### ISSUE TITLE
Folder Renamed With Alternative Title

### ISSUE THREAD

**Issue by MVallee** [Radarr/Radarr#753]
Whenever a movie is downloaded that has an alternative title (such as foreign films with original language titles) the video file gets named with the proper English title but the folder that Radarr creates gets named with the alternative title. It's happened with a few anime movies and a few French films and I've had to manually rename them and then change the path to the file in Radarr.

Radarr Version: 0.2.0.341

**Comment by galli-leo** [comment]
Known issue. Can only be fixed once we get folder renaming working
