### ISSUE TITLE
Torrentpotato wrong URL in jackett

### ISSUE THREAD

**Issue by Undeadhunter** [Radarr/Radarr#754]
**Description:**

Torrentpotato adds additional parameters to RSS sync

**Radarr Version:**

2.0.0.4472

**Logs:**

```
17-2-15 18:48:28.1|Info|RssSyncService|Starting RSS Sync
17-2-15 18:48:28.1|Debug|FetchAndParseRssService|Available indexers 2
17-2-15 18:48:28.1|Debug|TorrentPotato|Downloading Feed http://jackett:9117/potato/tracker?passkey=(removed)&user=(removed)&search=the
17-2-15 18:48:28.1|Debug|Torznab|Downloading Feed http://jackett:9117/torznab/tracker/api?t=movie&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060&extended=1&apikey=(removed)&offset=0&limit=100
```

The `&search=the` added to the URL makes it so that only RSS is search with 'The' in the title, and thus missing a lot of entries in RSS

**Comment by hotio** [comment]
A workaround for this could be `&search=-`, however I think it's best to delete the torrentpotato provider and focus on torznab...

**Comment by onedr0p** [comment]
That fix is incoming

**Comment by galli-leo** [comment]
Not really a fix. I think we should disable RSS for TorrentPotato by default.

**Comment by mvanbaak** [comment]
`&search=-` actually breaks it as jacket returns a 500 error when we send that to it.
