### ISSUE TITLE
Ignore Deleted Movies

### ISSUE THREAD

**Issue by hotio** [Radarr/Radarr#755]
The setting "Ignore Deleted Movies" does not set the the movie to unmonitored when a file gets deleted, it changes the status to Missing and will re-download the movie, again and again and... .

**Comment by gcoan** [comment]
I am also seeing this behavior on OSX. Specifically if I delete a movie from Plex, the file gets deleted, radarr does not unmonitor the movie and it gets re-downloaded.

**Comment by onedr0p** [comment]
Fix incoming
