### ISSUE TITLE
Adding any German title displays all movies with 0 minute length

### ISSUE THREAD

**Issue by magiin** [Radarr/Radarr#756]
**Description:**

All movies with German language, or adding the movie as German, is displaying any entry with 0 minute film length.  This not only causes any future release you want to upgrade to display an error (ie. 2 GB is larger than maximum allowed 0 B)

**Radarr Version:**
develop, 0.2.0.299 - Feb 7 2017 
**Logs:**
Not a log, submitting this for another user (Maggus, on discord)
See image for proper error displaying

![oyfawlpspmdsqg](https://cloud.githubusercontent.com/assets/25332158/22994193/0b849c18-f394-11e6-8aa6-42f1d1f20b84.jpg)

**Comment by fedoranimus** [comment]
@onedr0p Can you take a look at this?

**Comment by Cliffield** [comment]
Does not occur for every movie with german language. 
I noticed the "0 minutes" error for "The Accountant" and "Doctor Strange", but not for "Assasin's Creed".

Version 0.2.0.299

![unbenannt](https://cloud.githubusercontent.com/assets/20584910/23044597/27877274-f4a1-11e6-84fb-23129a6e8f21.PNG)

**Comment by theCheek** [comment]
Same issue found for 'If there be thorns' . Is it due to the TMDB showing this movie's runtime as '-' ?

**Comment by galli-leo** [comment]
@theCheek That could be it.

**Comment by theCheek** [comment]
I created an account on tmdb to edit and test this. Updated the runtime to what was shown on imdb, but the problem still seems to exist. Not too sure how tmdb works though and if they allow edits to go live immediately from new accounts. I tried deleting the movie and re-adding it to radarr but no joy.

**Comment by galli-leo** [comment]
@theCheek Can you try and update the movie info?

**Comment by onedr0p** [comment]
@theCheek TMDb takes about an hour or 2 inorder to update with your changes, at least on the API side.

**Comment by theCheek** [comment]
@galli-leo I did this but no change, but this following morning it seems to have taken, which makes sense after @onedr0p 's explanation. So this confirms the issue relates to TMDB missing movie length.

**Comment by galli-leo** [comment]
I added a default runtime of 110 minutes in case the movie does not have a runtime given by TMDB.
