### ISSUE TITLE
Rounding error on certain ratings. (Discovery queue)

### ISSUE THREAD

**Issue by digdilem** [Radarr/Radarr#7567]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When viewing items in the discovery queue at http://{IP}:7878/add/discover - some of them have ratings that are not whole numbers. These can be from 1 to many points and it looks a little silly. 

For example;

![image](https://user-images.githubusercontent.com/4052275/186443156-fc7f7b6d-ae6c-4834-b80e-4a7a4d1afeb2.png)

### Expected Behavior

I suspect that whole integers are perfectly adequate. Without knowing the code, I imagine something like round(call-to-get-number) would suffice.

### Steps To Reproduce

View discovery queue and sooner or later you'll spot some of these.

### Environment

```markdown
- OS: Debian 11
- Radarr: 4.1.0.6175
- Docker Install: 20.10.5+dfsg1
- Using Reverse Proxy: No
- Browser: Chrome
```

### What branch are you running?

Master

### Trace Logs?

N/A

[AB#3674](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3674)

**Comment by austinwbest** [comment]
Have a quick search for some info on this.
 
https://github.com/Radarr/Radarr/issues?q=is%3Aissue+rating+is%3Aclosed
