### ISSUE TITLE
Parse out list from URL

### ISSUE THREAD

**Issue by daleharris541** [Radarr/Radarr#7568]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

When adding a list for Custom IMDB, it prefers the following: 
IMDb list ID (e.g ls12345678), IMDb user ID (e.g. ur12345678), 'top250' or 'popular'

When I drop the entire URL, it gives me an error:
List ID mist be 'top250', 'popular', an IMDb List ID of the form 'ls12345678' or an IMDb user watchlist of the form 'ur12345678'

### Describe the solution you'd like

I was thinking there's a way to make it easier for people to copy and paste into the field the entire URL and drop the rest of the unneeded info. Example:
https://www.imdb.com/list/ls055592025/
If "/" is detected in the string, grab last parsed out element of the string and simply accept either URL or accept the exact "ls" or "ur" code. I use the docker container for Radarr  from linuxserver/radarr on docker hub.

### Describe alternatives you've considered

Alternatives would be keeping existing content.

### Anything else?

Python code would be something similar to the following: (my preferred language is PowerShell but python is popular)

string = "https://www.imdb.com/list/ls055592025/" #textbox is named listId

for '/' in string:
     stringarray = string.split("/")
     if 'ls' in stringarray[-1]:
          (Test out this string when hitting the test button, store -1 element to the value for listId)
          break
     if 'us' in stringarray[-1]:
          (Test out this string when hitting the test button, store -1 element to the value for listId)
          break

(Test listId value from textbox)

If you guys show me where to make the code suggestion, I'd gladly make the change to be reviewed and merge into main as I don't normally contribute to github projects, but have always enjoyed coding and scripting. It seems logical to me that we parse it and if we can't make heads or tails of it, then we simply test it and provide the error back until they get it right.

[AB#3677](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3677)

**Comment by bakerboy448** [comment]
The Entire logic would need to be rewrote to support entering a URL. What benefit does this add?

**Comment by daleharris541** [comment]
There’s not a way to add in this as an option if a “/“ is found so no need to re-write the logic? Or is it because the logic applies to all of the custom lists and it’s too specific for IMDB?

**Comment by austinwbest** [comment]
> The Entire logic would need to be rewrote to support entering a URL. What benefit does this add?

The frontend JS can easily do this and strip it. Just a matter of if Q wants it in there really.

**Comment by Qstick** [comment]
Given thingiprovider settings are not individually handled in the frontend, that's definitely not the place for it

@daleharris541 if you want to play with it, the logic around how it's used is here

https://github.com/Radarr/Radarr/blob/a3f508b8d46665b6a2315a10ba82a19c87f1e0f4/src/NzbDrone.Core/ImportLists/RadarrList2/IMDb/IMDbListRequestGenerator.cs#L13

And the validation is here

https://github.com/Radarr/Radarr/blob/a3f508b8d46665b6a2315a10ba82a19c87f1e0f4/src/NzbDrone.Core/ImportLists/RadarrList2/IMDb/IMDbListSettings.cs#L12

Shouldn't be crazy to change.

**Comment by Qstick** [comment]
PRs welcome for this, but no plans for us to work on it anytime soon
