### ISSUE TITLE
Profile or Filter to avoid HDR downloads

### ISSUE THREAD

**Issue by carlos-443-diaz** [Radarr/Radarr#7569]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

HDR downloads are queueing and are unwanted.

### Describe the solution you'd like

I'd like to be able to to configure or set a profile to avoid or prioritize HDR content.

### Describe alternatives you've considered

Manually downloading desired color profiles is possible, but only after determining that undesired content was retrieved.

### Anything else?

From what I can tell, HDR content usually has the "HDR" label in the content title.

[AB#3682](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3682)

**Comment by bakerboy448** [comment]
This can already be done with custom formats.  Nothing needs to be added to radarr.
