### ISSUE TITLE
Deletion of file not working

### ISSUE THREAD

**Issue by lue30499** [Radarr/Radarr#7573]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When clicking on a movie profile, then "Files" then clicking the little "x" next to the file. The file does not get deleted.
This did use to work I believe. The log shows that radarr has tried.

I have provided screenshots of the log + the docker-compose I'm using showing file permissions.

### Expected Behavior

When clicking on a movie profile, then "Files" then clicking the little "x" next to the file. The file should be deleted.

### Steps To Reproduce

1. When clicking on a movie profile
2. Then "Files"
3. Then clicking the little "x" next to the file.
4. Refresh or check the filesystem

### Environment

```markdown
- OS: Ubuntu 20.04.5
- Radarr: 4.1.0.6175
- Docker Install: Yes (linuxserver image)
- Using Reverse Proxy: Yes (Caddy)
- Browser: Chrome
```

### What branch are you running?

Master

### Trace Logs?

![radarrLog](https://user-images.githubusercontent.com/63104612/187024632-ff340df9-df6d-4091-bdeb-0cac4c14c7ee.png)

![radarrCompose](https://user-images.githubusercontent.com/63104612/187024635-e9771c5e-9269-440d-a968-af8b12684d20.png)

[AB#3685](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3685)

**Comment by RobinDadswell** [comment]
They are not trace logs they are info logs, that being said this seems like a support issue. It's likely permissions related. On a side note your volumes are not setup for optimal use of space (i.e. hardlinks). Please come to the discord and we would be more than willing to help. https://radarr.video/discord
