### ISSUE TITLE
Wrong reported free disk space

### ISSUE THREAD

**Issue by sisoteuz** [Radarr/Radarr#7574]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I run Radarr version 4.1.0.6175 in a FreeBSD jail and I expose my root folder `/data/films` through a nullfs mount. I have 2.1TB free on the root folder but Radarr says I only have 17GB free which makes it impossible to import any movies larger than that. I tried a few things to work it around but couldn't figure out a way, **I'm currently stuck and unable to import any movies.** (read below for more details)

The 17GB free space is actually for the `/` filesystem of my jail and I suspected that Radarr couldn't evaluate the size of `/data/films` because of the default setting `enforce_statfs=2` on the jail that only exposes the jail chroot filesystem for statistics (for example through the command `df -h`).

Hence I set `enforce_statfs=0` on the jail so that all filesystems are visible within the jail which makes `df -h /data/films` correctly show 2.1TB free however Radarr still shows 17GB of free space.

I think Radarr might only take `/` filesystem into account to evaluate the free space of my root folder or something of that sort.

I didn't have this issue with Radarr 3+ which didn't show any free space as it couldn't evaluate the free space on `/data/films`, this behaviour was fine by me.

Thanks for looking into it and please let me know if you need more details.

### Expected Behavior

Radarr should correctly show the free space of the filesystem or don't show anything if it cannot evaluate it (like it was in version 3+)

### Steps To Reproduce

Just check Root Folders in Settings > Media Management to see the wrong reported Free Space

### Environment

```markdown
- OS: FreeBSD 13.1-RELEASE-p1
- Radarr: 4.1.0.6175
- Docker Install: No
- Using Reverse Proxy: Yes
- Browser: Chrome
```

### What branch are you running?

Master

### Trace Logs?

2022-08-27 16:41:37.0|Warn|FreeSpaceSpecification|Not enough free space (18300076032) to import: /data/downloads/dst/movies/... (38322648462)

[AB#3686](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3686)

**Comment by RobinDadswell** [comment]
Can we have trace logs when going to "System" -> "Status" please.

**Comment by bakerboy448** [comment]
Searched discord 

you need to set `enforce_statfs` to 1  And then restart the jail

**Comment by RobinDadswell** [comment]
Information about the particular requirements for Radarr on BSD can be found here https://wiki.servarr.com/radarr/installation#jail-setup-using-truenas-gui

**Comment by sisoteuz** [comment]
I was using enforce_statfs to 0 instead of 1. It works now thanks a lot @RobinDadswell.
