### ISSUE TITLE
In the main page, ordering per Collection gives odd results

### ISSUE THREAD

**Issue by Kedryn** [Radarr/Radarr#7577]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when in the mail view, clicking on the Collection column to order by that, either descending or ascending, gives always the same result, that is the moviename ascending (fixed).

### Expected Behavior

1) Movies ordered by collection name, with all movies of the same collection one near another
2) all movies with no collection either first or last in the list
3) the list being ordered in ascending or descending, by collection name.

### Steps To Reproduce

Click on the Collection column header to sort.

### Environment

```markdown
- OS: Win10
- Radarr: 4.2.3.6555
- Docker Install: no
- Using Reverse Proxy: no
- Browser: any
```

### What branch are you running?

Nightly

### Trace Logs?

none

[AB#3694](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3694)

**Comment by thezoggy** [comment]
I can confirm, on table view if you show collections. sorting by it does not work.
