### ISSUE TITLE
TMDB Ratings has a rounding error

### ISSUE THREAD

**Issue by csandman** [Radarr/Radarr#7586]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It appears that the TVDB Rating component is suffering from a floating point rounding error in some cases.

<img width="1089" alt="image" src="https://user-images.githubusercontent.com/9214195/188967716-58c31c8a-c469-45e1-888c-7a04cc531275.png">

### Expected Behavior

The number representing this movie's (and multiple others') TMDB ratings should be rounded to probably at most 2 decimal places but you probably don't need any decimals.  I have looked at the source and as far as I can tell it should be working right but maybe I was looking at the wrong component?

The component I was looking at is located at `frontend/src/Components/TmdbRating.js`.  The code for formatting the number:

```js
ratingString = `${(rating.value * 10).toFixed()}%`;
```

appears all fine as `.toFixed` without any args should be the same as `.toFixed(0)`, so I'm not sure what could be wrong.  I could attempt to get a local build up and running if you want me to explore further.

### Steps To Reproduce

Add a movie such as **Harry Potter and the Chamber of Secrets** or **Harry Potter and the Deathly Hallows: Part 1** to a server and view the movie overview at the top.

### Environment

```markdown
- OS: Unraid
- Radarr: 4.1.0.6175-ls151 by linuxserver.io
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Chrome Version 105.0.5195.52 (Official Build) (arm64)
```

### What branch are you running?

Master

### Trace Logs?

<img width="1722" alt="image" src="https://user-images.githubusercontent.com/9214195/188969103-5628c38b-a1e9-417d-aa96-e42fd7a487f1.png">

<img width="1724" alt="image" src="https://user-images.githubusercontent.com/9214195/188969153-5a6f6107-4140-4966-a3f3-36a26d0082f7.png">

[AB#3715](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3715)

**Comment by ta264** [comment]
Fixed in nightly. Please search next time :D

**Comment by bakerboy448** [comment]
And to keep all the duplicates easily linked

- https://github.com/Radarr/Radarr/issues/7466
- https://github.com/Radarr/Radarr/issues/7567
- https://github.com/Radarr/Radarr/issues/7404

**Comment by csandman** [comment]
Oh man, thats my bad, I totally forgot to search closed issues (because it appeared to still be an issue).  Sorry about that @ta264 @bakerboy448
