### ISSUE TITLE
qBittorrent Indexer Tags

### ISSUE THREAD

**Issue by CarlitoGil** [Radarr/Radarr#7588]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

To easily determine visually in qBittorrent which indexer the release was grabbed from, especially for private trackers, qBittorrent "Tags" can be used (not to be confused with Radarr tags).

Perhaps you need to free space up, but don't want to delete anything from a private tracker, then you can quickly sort by the "Tags" column.

### Describe the solution you'd like

Add to the qBittorrent Download Client settings a checkmark to add the Indexer's name as a qBittorrent "Tag".

### Describe alternatives you've considered

Tags are separate from Categories in qBittorrent. The latter can be used to determine the save path, and can also have Subcategories.

The proposed solution is better than using the Tracker column, which takes more space and is not as clean to read.
You may choose shorter names for the Indexers than the whole official name or tracker URL.

### Anything else?

No.

[AB#3716](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3716)

**Comment by Barina** [comment]
I'm new here and I am missing a way to distinguish between indexers too.
Any progress with this issue?

**Comment by bakerboy448** [comment]
No plans

- qbit_manage or various qbit tools let you add tags based on trackers
- users can write  custom on grab script
