### ISSUE TITLE
Strip additional website domains prefixing movie names

### ISSUE THREAD

**Issue by subexx** [Radarr/Radarr#7589]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

I have issues with mapping movies in my regional language. The links are found by jackett, but radarr says it can't map due to the title containing the website name instead of the Movie name.

### Describe the solution you'd like

Remove the below prefixes when mapping movies.

www.TamilBlasters.casa
www.5MovieRulz.tc 
www.1TamilMV.pics

### Describe alternatives you've considered

Ignore the below prefixes when mapping movies.

www.TamilBlasters.casa
www.5MovieRulz.tc 
www.1TamilMV.pics

### Anything else?

![radarr](https://user-images.githubusercontent.com/91825280/189008877-b32037e5-4b78-4f99-983d-698727aa2296.jpg)
This is an example.

[AB#3717](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3717)

**Comment by bakerboy448** [comment]
Should just need additional domains here
https://github.com/Radarr/Radarr/blob/2ce9d099e1001eb4fccd61edcb0597782da872d4/src/NzbDrone.Core/Parser/Parser.cs#L118
