### ISSUE TITLE
Auto Search once added

### ISSUE THREAD

**Issue by baxter0** [Radarr/Radarr#759]
Please can we have the function to automatically search for films that are monitored.

I am using the Ombi system for users to request movies. When Ombi adds a movie it will add it monitored then i would have to manually search within Radarr

I think one of the biggest things that is missing from Radarr is to automatically search monitored movies.

**Comment by hadim** [comment]
That would a really nice feature to have !

**Comment by porkie02** [comment]
When I add a movie from Ombi it automatically searches no problem, double check the Ombi settings, also you can search for all missing files by using the wanted section of radarr its not full auto but its easy enough. wanted>select all> search selected

**Comment by fedoranimus** [comment]
Closing, functionality already exists in Wanted page.

**Comment by baxter0** [comment]
Hi, Yes after testing after Omni adds it automatically does complete a search. 

The whole point in having Radarr download films is to make this as automated as possible. I have RSS feeds adding films into the collection under monitored. Yes i agree that you can go to Wanted and search but that is a manual step where things could be improved.

If we only had a function where once a day all monitored movies search without manual intervention this would make the whole system better.

This is such a good program lets not stop... This is something that couch potato does (Agree not brilliant but at least it does do it)

**Comment by baxter0** [comment]
can this be opened again please as the function does not already exist

**Comment by MrDemous** [comment]
I think this is a needed addition to Radarr. I want Radarr to completely overtake the process of downloading movies for me and it shouldn't require any input from me after I set it up.

+1 for automatically searching for monitored movies.

**Comment by fedoranimus** [comment]
Radarr will already parse the RSS feeds from the indexers to determine if a new copy of any monitored movie has been added. 

Additionally, this request already exists on [Feathub](http://feathub.com/Radarr/Radarr/+64). Leaving closed.

**Comment by DrFarber** [comment]
You're incorrect. I think you're misunderstanding what they are asking. They are talking about movies that are older, and already exist on trackers.

Source: https://www.reddit.com/r/radarr/comments/7ity0g/radarr_doesnt_autodownload_movies/

**Comment by Qstick** [comment]
This is what add and search option is for. If you add everything via add+search you'll get any old results, and then Radarr takes over after as  Radarr monitors your indexers RSS feeds for new releases. The only way you miss something at that point is you shutdown Radarr  long enough to have a gap in indexer recent feeds.

This results in much less traffic to the indexer than doing automatic searches all the time. Meaning you are much less likely to get banned, and indexers are much happier dealing with Radarr traffic.
