### ISSUE TITLE
TMDB rating sometimes shows excessive number of digits after the decimal point

### ISSUE THREAD

**Issue by hugalafutro** [Radarr/Radarr#7594]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Some movies show the rating with too many decimals.

### Expected Behavior

rating should be displayed as XY.Z not XY.ZZZZZZZZZZZZZZ

### Steps To Reproduce

Not reproducible unless you look at the movie where it happens.

### Environment

```markdown
- OS: Ubuntu 21.04.1
- Radarr: 4.1.0.6175
- Docker Install: 4.1.0.6175-ls152 by linuxserver.io
- Using Reverse Proxy: no
- Browser: vivaldi (chromium based)
- Database: no idea, default docker-compose.yaml from lsio
```

### What branch are you running?

Master

### Trace Logs?

Trace logs not applicable, issue generates no log output.

Screenshot example (I have no idea how to identify more movies with the issue to suss out any kind of pattern):
![image](https://user-images.githubusercontent.com/30209689/189477971-2618b2b3-f6c3-4cd5-89c5-503ac99f95a1.png)

[AB#3724](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3724)

**Comment by ta264** [comment]
Please search for the many duplicates next time

**Comment by bakerboy448** [comment]
And to keep all the duplicates easily linked

- https://github.com/Radarr/Radarr/issues/7466
- https://github.com/Radarr/Radarr/issues/7567
- https://github.com/Radarr/Radarr/issues/7404
- https://github.com/Radarr/Radarr/issues/7586
