### ISSUE TITLE
Collections adding movies with NULL tags breaks Settings/Tags - Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by bakerboy448** [Radarr/Radarr#7623]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

![image](https://user-images.githubusercontent.com/55419169/191806438-9768675d-9e99-4292-8d6c-9abb612b27c8.png)

RCA Movies having NULL Tags
![image](https://user-images.githubusercontent.com/55419169/191809915-abc50b0b-474c-4fdd-851b-02d6c337fa21.png)

Appears to be due to collections adding movies without tags https://github.com/Radarr/Radarr/blob/9bc31b46fa2a28d37437e48c241c1980a23ba320/src/NzbDrone.Core/Movies/RefreshCollectionService.cs#L109-L122

### Expected Behavior

- Tags/Details should handle movie.tags being null gracefully
OR
- Movie.Tags DB schema should not allow null fields
- Collections should add tags empty, not null
- DB Migration to recover users on develop and nightly who have movie.tags as null and need to change to `[]` (empty list)

--- 

Temporary fix: users manually edit the database and update movies.tags that are null to `[]`
Backups unless prior to collections will not repair this.

### Steps To Reproduce

Use nightly or develop and allow collections to be added

### Environment

```markdown
- OS: agnostic
- Radarr: 4.2.4.6605
- Docker Install: agnostic
- Using Reverse Proxy: agnostic
- Browser: agnostic
- Database: Sqlite 3.31.1
- Migration: 214
```

### What branch are you running?

Nightly

### Trace Logs?

https://gist.github.com/bakerboy448/9f05b771af22fe142370b3e165318213

[AB#3799](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3799)

**Comment by owine** [comment]
I am seeing this on movies added by Traktarr which does not send anything in its payload regarding tags.

**Comment by bakerboy448** [comment]
https://github.com/Radarr/Radarr/commit/9f3eecb2a93e24800cb36669e46038c05558aed8
https://github.com/Radarr/Radarr/commit/f50e8f631ea335f218cf2d2a6f8c572f3824b7af
