### ISSUE TITLE
Need a minimum file size

### ISSUE THREAD

**Issue by porkie02** [Radarr/Radarr#763]
As the title says will we ever see a minimum file size I keeps catching radarr adding files that are obviously not a movie because of their size. Take a look at the image , I have quite decent qualities too.

https://i.imgur.com/ev3mACx.png

https://i.imgur.com/oEIlo3W.png

**Comment by galli-leo** [comment]
Well yeah you set the minimum file size of every quality to 0 bytes. Of course now every movie can be downloaded.

**Comment by porkie02** [comment]
oh lol my bad :) feel like an idiot now.
