### ISSUE TITLE
 TypeError: a.responseJSON.map

### ISSUE THREAD

**Issue by m-GDEV** [Radarr/Radarr#7639]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Hi I'm new to radarr and when I tried importing my library, the page goes blank (just white) and in the console it displays this error:

` TypeError: a.responseJSON.map` 

### Expected Behavior

I expect it to properly import my collection.

### Steps To Reproduce

1. Installed using the script here: <https://wiki.servarr.com/install-script>
2. attempt to import library

### Environment

```markdown
- OS: Debian 11
- Radarr: 4.2.4.6635
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Chrome 104
- Database:Sqlite 3.34.1
```

### What branch are you running?

Master

### Trace Logs?

I'm trying to enable trace mode in the settings but when I go to Setting > General it gives me this error: Unable to load General settings

[AB#3826](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3826)

**Comment by AsherJac** [comment]
Looks like this might be similar to miy issue with not being able to import library. Issue is explained in more detail (with logs) here: https://www.reddit.com/r/radarr/comments/zwctja/cant_import_library_error_typeerror/

**Comment by m-GDEV** [comment]
> Looks like this might be similar to miy issue with not being able to import library. Issue is explained in more detail (with logs) here: https://www.reddit.com/r/radarr/comments/zwctja/cant_import_library_error_typeerror/

Yup seems similar, no response there either though 😅. Thanks!

**Comment by bakerboy448** [comment]
browser dev console will have more details.

likely you have an app or extension mucking with http requests or your connection to the frontend has timed out.

**Comment by m-GDEV** [comment]
> browser dev console will have more details.
> 
> likely you have an app or extension mucking with http requests or your connection to the frontend has timed out....increase your reverse proxy timeout and ensure you're using ip:port for large initial imports

Thanks for the response.

Something changed from then till now. I did indeed happen to remove some chrome extensions over the last few months and now it seems to work properly.

Thanks for clarifying!
