### ISSUE TITLE
Radarr wont open

### ISSUE THREAD

**Issue by Coltonc188** [Radarr/Radarr#7642]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Radarr wont open at all, it gets an EPIC FAIL error in log file 

### Expected Behavior

to open 

### Steps To Reproduce

Im running it in unraid, and trying to open it, and it wont open.

### Environment

```markdown
- OS: Unraid Version: 6.11.0 
- Radarr:I'm not sure, it says the lates, but I cant open to check it
- Docker Install:yes
- Using Reverse Proxy: no
- Browser: Chrome
- Database: not sure
```

### What branch are you running?

Master

### Trace Logs?

I can't get trace logs as I can't get into radarr to activate them, here are the logs I get when I try to run radarr.  Looking, I've seen a few of these, but none recently and everyone appears to be on nightly builds and were able to upgrade/switch to the prod build and was fine.  Not sure what to do here. 

https://pastebin.com/ae8ZUAAb

[AB#3830](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3830)

**Comment by bakerboy448** [comment]
> I can't get trace logs as I can't get into radarr to activate them

You don't need the UI to turn on trace logs.  This is explained in the wiki the bug report template links.

> Radarr failed to start: Error creating log database

https://wiki.servarr.com/radarr/faq#i-am-getting-an-error-database-disk-image-is-malformed

**Comment by Coltonc188** [comment]
> > I can't get trace logs as I can't get into radarr to activate them
> 
> You don't need the UI to turn on trace logs. This is explained in the wiki the bug report template links.
> 
> > Radarr failed to start: Error creating log database
> 
> https://wiki.servarr.com/radarr/faq#i-am-getting-an-error-database-disk-image-is-malformed

ahh, I didn't read far enough on that.

**Comment by Coltonc188** [comment]
I will get them, and go to the Discord, since it seems this was the wrong place for this.

Thanks
