### ISSUE TITLE
Poster windows folder icon 

### ISSUE THREAD

**Issue by abewartech** [Radarr/Radarr#7644]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

https://github.com/sameera-madushan/PosterPy

### Describe the solution you'd like

https://github.com/sameera-madushan/PosterPy

### Describe alternatives you've considered

https://github.com/sameera-madushan/PosterPy

### Anything else?

https://github.com/sameera-madushan/PosterPy

[AB#3839](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3839)

**Comment by bakerboy448** [comment]
Blindly copying and pasting the URL for some random program is not a valid feature request

please populate the fields with actual context not just a url
