### ISSUE TITLE
Synology DSM 7.0, Radarr failed to start package after update. (Version 20220515-18)

### ISSUE THREAD

**Issue by Sweepr** [Radarr/Radarr#7650]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Radarr was working fine, but stopped working after I updated some packages and now it won't start.

```
synopkg start radarr
{"action":"start","beta":false,"error":{"code":272,"description":"Failed to run script, script=[start]"},"finished":true,"language":"enu","last_stage":"prepare_start","package":"radarr","pid":15758,"scripts":[{"code":1,"message":"","type":"start"}],"stage":"start_failed","status":"start_failed","status_code":272,"status_description":"failed to start on previous startup","success":false,"username":"","version":"20220515-18"}
```

![afbeelding](https://user-images.githubusercontent.com/2857865/193472922-06467d1a-c029-412c-bc07-43253b92816c.png)

![afbeelding](https://user-images.githubusercontent.com/2857865/193472970-751d63c1-6081-4c90-a1aa-4a2fa040b4a2.png)

### Expected Behavior

I expected it to start after the update, but it won't start .

### Environment

```markdown
- OS: DSM 7.1-42661
- Radarr: 20220515-18
- Docker Install:
- Using Reverse Proxy:
- Browser:
- Database:
```

### What branch are you running?

Master

### Trace Logs?

None

[AB#3851](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3851)

**Comment by bakerboy448** [comment]
logs are required  there's nothing anyone can do with the existing information.

**Comment by Sweepr** [comment]
> logs are required there's nothing anyone can do with the existing information.
> 
> you'll probably also have better luck at the SynoCommunity as they provide support for their packages and have a better understanding of synology.

True, i'll check there..

Thanks for the help, i will close this for now.

**Comment by Sweepr** [comment]
Fixed, for reference see: https://github.com/SynoCommunity/spksrc/issues/5440
