### ISSUE TITLE
Amount of votes IMDB

### ISSUE THREAD

**Issue by speelgoedauto2** [Radarr/Radarr#7658]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

No, not a problem, just a feature

### Describe the solution you'd like

Is it possible to add a colom or table with the amount of **votes** next to the IMDB rating. 

### Describe alternatives you've considered

No alternatives

### Anything else?

No

[AB#3873](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3873)

**Comment by Qstick** [comment]
It's available on mouse hover.
