### ISSUE TITLE
Custom Filter option to search for collections with missing movie(s)

### ISSUE THREAD

**Issue by spikysimonw** [Radarr/Radarr#7664]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe

Unable to use the missing movie(s) metadata attribute within custom filters. 

### Describe the solution you'd like

To be able to create a custom filter to surface collections with missing movie(s).

### Describe alternatives you've considered

Manually scrolling down the collections list (!).

### Anything else?

Nope, thanks.

[AB#3879](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3879)

**Comment by Qstick** [comment]
Dupe #7338
