### ISSUE TITLE
Postgres Credentials Not Cleansed From Docker Log

### ISSUE THREAD

**Issue by owine** [Radarr/Radarr#7670]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Postgres credentials are written to the log/console in the `MigrationController` item.

### Expected Behavior

Credentials should be cleansed before writing to log.

### Steps To Reproduce

1. Migrate to Postgres
2. Start Radarr
3. View log entry for `MigrationController`

### Environment

```markdown
- OS: Ubuntu 22.04
- Radarr: 4.3.0.6660
- Docker Install: Yes
- Using Reverse Proxy: Traefik
- Browser: Wavebox (Chromium)
- Database: Postgresql 14.5
```

### What branch are you running?

Nightly

### Trace Logs?

`[Info] MigrationController: *** Migrating Database=radarr-main;Host=postgres14;Username=zak;Password=pleasefix;Port=5432;Enlist=False ***`

[AB#3892](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3892)

**Comment by bakerboy448** [comment]
Console logs are not cleansed, log files are
