### ISSUE TITLE
feature request audio description 

### ISSUE THREAD

**Issue by Mrpuppyz** [Radarr/Radarr#7673]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Currently no options for audio description in language profiles

### Describe the solution you'd like

I would like the sonarr and radarr to have the option to add audio description under the add language profile. This would help for people that are blind and for people like me that would like to listen to a show/movie while driving.

### Describe alternatives you've considered

Alternative to this would be a Jellyfin/Plex plugin for download audio description similar to the way opensubtitles works on Jellyfin. I have tried searching for such plugin with no success. 

### Anything else?

In my case I would have two languages profiles one for just regular English without descriptions for nondriving watching and a second profile with English audio description for driving/listening.

[AB#3894](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3894)

**Comment by bakerboy448** [comment]
This should be able to be done with custom formats.   Swing by the discord and see the wiki on custom formats / trash's guide for more info
