### ISSUE TITLE
Unable to retireve Blocklist

### ISSUE THREAD

**Issue by Romeriz** [Radarr/Radarr#7688]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Hello,

I am unable to retrieve the blocklist via the GUI. The screen displays unable to load blocklist.

Radarr: 4.2.4.6635
Database: Postgresql 13.6

I followed the following to create and migrate the database from the SQLite DB. https://wiki.servarr.com/radarr/postgres-setup

I looked at the schema on both the PostgreSQL server and the SQLite db and this column does not exist in either location.

### Expected Behavior

Display a list of items on the blocklist

### Environment

```markdown
- OS: Debian 11
- Radarr: 4.2.4.6635
- Docker Install: 19.03.15, build 99e3ed8919
- Using Reverse Proxy: Yes, Traefik
- Browser: Firefox
- Database: PostgreSQL
```

### What branch are you running?

Master

### Trace Logs?

adarr  | [Fatal] RadarrErrorPipeline: Request Failed. GET /api/v3/blocklist 
radarr  | 
radarr  | [v4.2.4.6635] Npgsql.PostgresException (0x80004005): 42703: column "SortTitle" does not exist
radarr  | 
radarr  | POSITION: 125
radarr  |    at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|211_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
radarr  |    at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
radarr  |    at Npgsql.NpgsqlDataReader.NextResult()
radarr  |    at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
radarr  |    at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
radarr  |    at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior)
radarr  |    at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior) in /_/Dapper/SqlMapper.cs:line 1075
radarr  |    at Dapper.SqlMapper.MultiMapImpl[TFirst,TSecond,TThird,TFourth,TFifth,TSixth,TSeventh,TReturn](IDbConnection cnn, CommandDefinition command, Delegate map, String splitOn, IDataReader reader, Identity identity, Boolean finalize)+MoveNext() in /_/Dapper/SqlMapper.cs:line 1470
radarr  |    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
radarr  |    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
radarr  |    at Dapper.SqlMapper.MultiMap[TFirst,TSecond,TThird,TFourth,TFifth,TSixth,TSeventh,TReturn](IDbConnection cnn, String sql, Delegate map, Object param, IDbTransaction transaction, Boolean buffered, String splitOn, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 1451
radarr  |    at Dapper.SqlMapper.Query[TFirst,TSecond,TReturn](IDbConnection cnn, String sql, Func`3 map, Object param, IDbTransaction transaction, Boolean buffered, String splitOn, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 1306
radarr  |    at NzbDrone.Core.Datastore.SqlMapperExtensions.Query[TFirst,TSecond,TReturn](IDatabase db, String sql, Func`3 map, Object param, IDbTransaction transaction, Boolean buffered, String splitOn, Nullable`1 commandTimeout, Nullable`1 commandType) in D:\a\1\s\src\NzbDrone.Core\Datastore\Extensions\SqlMapperExtensions.cs:line 50
radarr  |    at NzbDrone.Core.Datastore.SqlMapperExtensions.QueryJoined[T,T2](IDatabase db, SqlBuilder builder, Func`3 mapper) in D:\a\1\s\src\NzbDrone.Core\Datastore\Extensions\SqlMapperExtensions.cs:line 156
radarr  |    at NzbDrone.Core.Blocklisting.BlocklistRepository.PagedQuery(SqlBuilder sql) in D:\a\1\s\src\NzbDrone.Core\Blocklisting\BlocklistRepository.cs:line 44
radarr  |    at NzbDrone.Core.Datastore.BasicRepository`1.GetPagedRecords(SqlBuilder builder, PagingSpec`1 pagingSpec, Func`2 queryFunc) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 434
radarr  |    at NzbDrone.Core.Datastore.BasicRepository`1.GetPaged(PagingSpec`1 pagingSpec) in D:\a\1\s\src\NzbDrone.Core\Datastore\BasicRepository.cs:line 404
radarr  |    at NzbDrone.Core.Blocklisting.BlocklistService.Paged(PagingSpec`1 pagingSpec) in D:\a\1\s\src\NzbDrone.Core\Blocklisting\BlocklistService.cs:line 68
radarr  |    at Radarr.Http.Extensions.RequestExtensions.ApplyToPage[TResource,TModel](PagingSpec`1 pagingSpec, Func`2 function, Converter`2 mapper) in D:\a\1\s\src\Radarr.Http\Extensions\RequestExtensions.cs:line 133
radarr  |    at Radarr.Api.V3.Blocklist.BlocklistController.GetBlocklist() in D:\a\1\s\src\Radarr.Api.V3\Blocklist\BlocklistController.cs:line 32
radarr  |    at lambda_method461(Closure , Object , Object[] )
radarr  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
radarr  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
radarr  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
radarr  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
radarr  | --- End of stack trace from previous location ---
radarr  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
radarr  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
radarr  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
radarr  | --- End of stack trace from previous location ---
radarr  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
radarr  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
radarr  |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
radarr  |    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
radarr  |    at Radarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\BufferingMiddleware.cs:line 28
radarr  |    at Radarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\IfModifiedMiddleware.cs:line 41
radarr  |    at Radarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\CacheHeaderMiddleware.cs:line 33
radarr  |    at Radarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\UrlBaseMiddleware.cs:line 27
radarr  |    at Radarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\a\1\s\src\Radarr.Http\Middleware\VersionMiddleware.cs:line 28
radarr  |    at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
radarr  |    at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
radarr  |    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
radarr  |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
radarr  |    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
radarr  |   Exception data:
radarr  |     Severity: ERROR
radarr  |     SqlState: 42703
radarr  |     MessageText: column "SortTitle" does not exist
radarr  |     Hint: Perhaps you meant to reference the column "Blocklist.SourceTitle".
radarr  |     Position: 125
radarr  |     File: parse_relation.c
radarr  |     Line: 3514
radarr  |     Routine: errorMissingColumn
radarr  | Severity: ERROR;InvariantSeverity: ERROR;SqlState: 42703;MessageText: column "SortTitle" does not exist;Hint: Perhaps you meant to reference the column "Blocklist.SourceTitle".;Position: 125;File: parse_relation.c;Line: 3514;Routine: errorMissingColumn;SQL: 
radarr  | ==== Begin Query Trace ====
radarr  | 
radarr  | QUERY TEXT:
radarr  | SELECT "Blocklist".*, "Movies".*
radarr  |  FROM "Blocklist" 
radarr  | JOIN "Movies" ON ("Blocklist"."MovieId" = "Movies"."Id")
radarr  |       ORDER BY "SortTitle" DESC LIMIT 20 OFFSET 0
radarr  | 
radarr  | 
radarr  | PARAMETERS:
radarr  | 
radarr  | ==== End Query Trace ====

[AB#3942](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3942)

**Comment by RobinDadswell** [comment]
Can you try clearing the cache please?

**Comment by Romeriz** [comment]
If you are talking about the web browser cache, I tried it with the same results

**Comment by RobinDadswell** [comment]
Probably best to swing by discord as I cannot see the frontend calling for "SortTitle" in the database at all as it doesn't exist for Blocklist and I cannot reproduce on my end.

https://radarr.video/discord

will reopen this if it's an actual bug
