### ISSUE TITLE
radarr - fails test when sab is running from source

### ISSUE THREAD

**Issue by thezoggy** [Radarr/Radarr#769]
Radarr Ver. 0.2.0.366

add sabnzbd download client to radarr, it fails because it gets back the version `develop` when you run from source...
```
17-2-16 07:32:24.8|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Sabnzbd develop version, assuming version 1.1.0 or higher.
```

reported it upstream as it used to work in sonarr: https://github.com/Sonarr/Sonarr/issues/1688

**Comment by thezoggy** [comment]
also to note, you can have the host field empty... not caught before the test fires:
```
17-2-16 07:44:47.8|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- 'Host' should not be empty.
 -- must be valid Host without http://
```

**Comment by thezoggy** [comment]
`https://localhost:ip/api?mode=version&apikey=(removed)&output=json` returns: `{"version": "develop"}`

**Comment by onedr0p** [comment]
I see that in sonarr the issue is closed, but i didn't see a fix. Did I miss something?

**Comment by thezoggy** [comment]
they plan to address it in v3

**Comment by onedr0p** [comment]
We will do the same then unless you feel like helping to contribute.
