### ISSUE TITLE
Add Torrserver support

### ISSUE THREAD

**Issue by daromanyuk** [Radarr/Radarr#7701]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Please add TorrServer torrent client support
Here the link to the project 
https://github.com/YouROK/TorrServer

### Describe the solution you'd like

New added torrents passed to TorrServer

### Describe alternatives you've considered

none

### Anything else?

none

[AB#3970](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3970)

**Comment by bakerboy448** [comment]
It looks like this is for streaming files while/ in lieu of downloading them?

\*arr requires the video files to be downloaded and the download client to have some status files to indicate it is completely downloaded. It also requires the path to the downloaded file.

 It does not appear that any of these requirements are met from skimming their readme. They seemingly provide a streaming torrent client, not a download client.

**Comment by bakerboy448** [comment]
Can reopen if OP or another user provide additional information

**Comment by rgubin** [comment]
@bakerboy448 
Yep, your assumptions is right.
This can gave ability to use Radarr and any its integrated clients as a search engine and after add to torrserver as a download client - immediately start watching video (using integrated to torrserver DLNA or another torrserver clients).
As soon as torrent loaded to torrserver it can be considered as `downloaded`
Torrserver has an REST API to get torrents and its files.

I know it's a bit tricky, cause its not a usual download client flow.
I vote for this feature.
