### ISSUE TITLE
Custom Format Score tooltip

### ISSUE THREAD

**Issue by techie2000** [Radarr/Radarr#7706]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Whilst the Custom Format Score is shown and is sortable, there is no way to (easily) determine how the score was derived and thus difficult to determine why one release was picked over another (unexpectedly).

### Describe the solution you'd like

It would be helpful when trying to work out why one release was picked over another (unexpectedly) if a tooltip was displayed showing how the score had been derived, similar to the Release Rejected tooltip that shows all the reasons why any given result was not chosen.

### Describe alternatives you've considered

The only way I can see to do this today is to review the rules manually and do your own calculation. With tens of rules in-play, this is time consuming at best, and human-error often sees a different answer derived.

### Anything else?

Ideally a tooltip similar to 
![image](https://user-images.githubusercontent.com/38585780/198537981-296e5eec-64a5-48d4-9146-0d4e4f08ea42.png)
should be available here
![image](https://user-images.githubusercontent.com/38585780/198537009-89e3012a-c41e-4c27-bcc0-1e8e26b6cfb8.png)

[AB#3976](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3976)

**Comment by bakerboy448** [comment]
https://github.com/Radarr/Radarr/commit/f8cbca79589a7a1a9c09f4f74a6034496f792299 ?
