### ISSUE TITLE
Language tags (i.e. sdh, forced, etc.) in subtitle files don't get parsed on library import (contains fix!)

### ISSUE THREAD

**Issue by tomaszni** [Radarr/Radarr#7710]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When importing a movie from an existing folder into the library, language tags (sdh, forced, etc.) from subtitle files don't get parsed. As a result, when e.g. renaming, the same language subtitles with different tags get grouped into one group and named sequentially.

```
movie.2022.mkv                  Movie (2022).mkv
movie.2022.en.forced.srt  ===>  Movie (2022).1.en.srt
movie.2022.en.srt               Movie (2022).2.en.srt
movie.2022.es.srt               Movie (2022).es.srt
```

There is a #7459 which is resolved and working, but is not applied on import (only on grab maybe)?
A fix is provided (see "Expected behavior").

### Expected Behavior

Importing parses the tags properly.

A working fix can be done by patching `src/NzbDrone.Core/Extras/Subtitles/ExistingSubtitleImporter.cs`:
```
diff --git a/src/NzbDrone.Core/Extras/Subtitles/ExistingSubtitleImporter.cs b/src/NzbDrone.Core/Extras/Subtitles/ExistingSubtitleImporter.cs
index 8d1e23f3e..4e70c2cdd 100644
--- a/src/NzbDrone.Core/Extras/Subtitles/ExistingSubtitleImporter.cs
+++ b/src/NzbDrone.Core/Extras/Subtitles/ExistingSubtitleImporter.cs
@@ -54,6 +54,7 @@ public override IEnumerable<ExtraFile> ProcessFiles(Movie movie, List<string> fi
                         MovieFileId = movie.MovieFileId,
                         RelativePath = movie.Path.GetRelativePath(possibleSubtitleFile),
                         Language = LanguageParser.ParseSubtitleLanguage(possibleSubtitleFile),
+                        LanguageTags = LanguageParser.ParseLanguageTags(possibleSubtitleFile).ToList(),
                         Extension = extension
                     };
```

(diff based on v4.2.4.6635, develop branch doesn't touch the file)

I'm not familiar with the codebase enough to prepare a full-on PR with unit tests etc., so I ask someone from the team to please pick it up :)

### Steps To Reproduce

"Movies > Library import" pick a movie folder with multiple subtitle files, with at least two of the same language and differing language tags (sdh, forced, etc.). See example in "Current behavior".

### Environment

```markdown
- OS: Debian 11.4 (LXC on ProxMox)
- Radarr: 4.2.4.6635
- Docker Install: yes
- Using Reverse Proxy: no
```

### What branch are you running?

Develop

### Trace Logs?

Not relevant (nothing in logs)

[AB#3981](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3981)

**Comment by klepp0906** [comment]
just ran across this now.  doing a rename of my naming convention and noticed my subs between standard and forced were all slaughtered.

![image](https://user-images.githubusercontent.com/10392920/228308618-9165ee52-0019-4b73-90b3-b438913463be.png)

ran it past the bazarr dev and he pointed to radarr.  radarr disc got some nods from others experiencing it so i came here to make a bug report. 

pleasantly found one in place :)

**Comment by edrock200** [comment]
Will this fix work for all sideloaded files such as bifs that also add additional tags at the end of the name or just subs? Thanks in advance.
