### ISSUE TITLE
Simplify Movie PUT payloads for easier Linking for Tags and Movies

### ISSUE THREAD

**Issue by crypticraven** [Radarr/Radarr#7711]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Problem: 
When trying to link movies to tags via the API; a complete scrub of the movie return has to be done and posted back to the API to make updates to tags. This is not intuitive since most of the data here comes from other sources and is auto-filled form TVDB/IMDB. This also increases memory use and script runtime where the script has to now save each object, scrub, update, send new information to the API.

### Describe the solution you'd like

A more simple way to link tags and movies via the API. Being able to update a few lines allows for faster scripting and better memory utilization because we're not needing to save full objects into memory.

### Describe alternatives you've considered

Alternatives I've considered are either manually entering these in the UI (not fun) and using more memory than required to perform this action via script. With 3000+ items, the objects stored in memory consume ~15 meg; this can take a while to churn through to make simple updates and return the tags to the API with the current implementation.

### Anything else?

Rapid7 has an elegant solution for manually linking tags to assets via the API. With their implementation, I can send a call to the tags endpoint that has the asset ID and it links the two together with less than 10 lines of code and not having to have full objects retained in memory during script execution.

I've looked for help on the Reddit and not received significant help; but to be told "You're doing it wrong."

[AB#3986](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3986)

**Comment by bakerboy448** [comment]
Point of clarification and what was suggested: Just use the response, edit the tags attribute, and put it back is not "you're doing it wrong" it's KISS so you don't need to deal with validation.

And all data in the API with the exception of the few external lookup endpoints already is within radarr and comes from radarr - not externally gotten on an api call basis.
