### ISSUE TITLE
build.sh has wrong path in PackageWindows() function

### ISSUE THREAD

**Issue by joshdavidson** [Radarr/Radarr#7715]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When running build.sh on a linux box, the script fails with the following error:
```
Start 'Creating Windows Package for net6.0'
Adding LICENSE
cp: cannot stat '_output/net6.0-windows/win-x64/publish/*': No such file or directory
```

### Expected Behavior

build.sh to run without errors as long as host has all of the package/build dependencies

### Steps To Reproduce

On linux host execute:
```
git clone git@github.com:Radarr/Radarr.git
cd Radarr && ./build.sh
```

### Environment

```markdown
- OS: Ubuntu 22.04.1 LTS
- Radarr: development branch
- Docker Install: N/A
- Using Reverse Proxy: N/A 
- Browser: N/A
- Database: N/A
```

### What branch are you running?

Develop

### Trace Logs?

N/A

[AB#3996](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/3996)

**Comment by bakerboy448** [comment]
you're likely missing _something_ given the CI process uses the build script and works.

can figure it out on discord.

**Comment by ta264** [comment]
This will only work on windows.  `./build.sh` builds for every os, and that's only possible on windows due to dotnet limitations.

**Comment by joshdavidson** [comment]
My bad - This is non-discrepant.  I was not building with the correct flags -f net6.0 -r linux-x64.  Thanks for the help
