### ISSUE TITLE
Standard movie format doesn't save

### ISSUE THREAD

**Issue by dannymichel** [Radarr/Radarr#7738]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Go to settings > media management, change standard movie format renaming.
Click save settings
It saves for the time being
But doesn't save when you update the docker container

### Expected Behavior

Should save/stay consistent 

### Steps To Reproduce

Go to settings > media management, change standard movie format renaming.
Click save settings

### Environment

```markdown
- OS: Ubuntu 20
- Radarr: 4.3.0.6671
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Chrome
- Database: Sqlite 3.36.0
```

### What branch are you running?

Develop

### Trace Logs?

[radarr.txt](https://github.com/Radarr/Radarr/files/9955131/radarr.txt)

[AB#4042](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4042)

**Comment by bakerboy448** [comment]
> But doesn't save when you update the docker container

then you have not mounted `/config` so everything is lost after every update or container restart.

**Comment by dannymichel** [comment]
```
    ports:
      - '7878:7878'
    volumes:
      - '/data/radarr:/config'
      - '/media:/media'
```
```
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
```
```
➜  ~ ls -lah /data/radarr
total 52M
drwxr-xr-x   12 user user 4.0K Nov  7 20:14 .
drwxr-xr-x   35 user user 4.0K Nov  7 09:10 ..
drwxr-xr-x    2 user user 4.0K Oct 26 12:41 asp
drwxr-xr-x    4 user user 4.0K Feb 24  2020 Backups
drwxrwxr-x    2 user user 4.0K May 24 02:00 bak
drwxrwxr-x    3 user user 4.0K May 23 18:30 bak.orig
-rw-rw-r--    1 user user  553 Nov  7 19:51 config.xml
drwxr-xr-x    2 user user 4.0K Jun 26  2021 custom-cont-init.d.xhrjh38q
drwxr-xr-x    2 user user 4.0K Jun 26  2021 custom-services.d.xhrjh38q
drwxrwxrwx    6 user user 4.0K Sep 24 05:06 extended
drwxr-xr-x    2 user user 4.0K Nov  7 19:46 logs
-rw-r--r--    1 user user 6.9M Nov  7 20:01 logs.db
drwxr-xr-x 2063 user user  36K Nov  6 03:00 MediaCover
-rwxr-xr-x    1 user user    4 Feb  8  2020 nzbdrone.pid
-rw-rw-r--    1 user user  44M Nov  7 20:13 radarr.db
-rw-rw-r--    1 user user  32K Nov  7 20:28 radarr.db-shm
-rw-rw-r--    1 user user 516K Nov  7 20:28 radarr.db-wal
-rw-r--r--    1 user user    3 Nov  7 19:51 radarr.pid
drwxr-xr-x    2 user user 4.0K Feb  8  2020 UpdateLogs
```
https://gist.github.com/dannymichel/4adba899f8147d99126e6e02e7ed0d06

https://gist.github.com/dannymichel/a0c256ab2d6b852dec69dc4dd797222d
