### ISSUE TITLE
Button to suggest new folder name for existing movie

### ISSUE THREAD

**Issue by SimFre** [Radarr/Radarr#7739]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Existing folders imported with "scene names" don't follow Radarr's set of "Movie (year)", standardize naming between old and new data.

### Describe the solution you'd like

Just a button to alter the folder name from existing name to suggested name. Since Radarr already supports renaming, just having a button to quickly set the new suggested name would make the rename of existing archive very simple.

Add new button "Suggest Name" (or a good icon). User then hits save and can choose to rename.
Changes path from /movies/movie.scene.rls.2000-asdf to /movies/Movie (2000).

![image](https://user-images.githubusercontent.com/9532326/201313289-8294c7fb-5348-45a3-9639-cac90cf09333.png)

### Describe alternatives you've considered

- Manual rename of folder, delete entry from radarr, re-import.
- Rename manually in gui, chose to rename when hitting save.

### Anything else?

See picture in solution description.

[AB#4054](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4054)

**Comment by bakerboy448** [comment]
This seems like significantly more effort for users to have to go movie by movie to rename the movie folders than to just use the existing functionality: https://wiki.servarr.com/radarr/faq#how-can-i-rename-my-movie-folders

**Comment by SimFre** [comment]
@bakerboy448 that is indeed a very nice solution, didn't know that. I still maintain that it would be nice to have this button though for singular changes.

**Comment by Qstick** [comment]
Thanks for the FR, but we have no plans to add a button like this for now.
