### ISSUE TITLE
Collections extend offscreen

### ISSUE THREAD

**Issue by KingIzzymon** [Radarr/Radarr#7740]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

# Issue
As shown in this screenshot, longer collections keep going offscreen but no horizontal scroll bar ever appears. Can't pan right to see what other movies are in the collection. There are 15 items in this [collection.](https://www.themoviedb.org/collection/374509-godzilla-showa-collection)

![image](https://user-images.githubusercontent.com/94716517/201493700-184b230b-6161-4025-b44a-7869672e2edd.png)

# Environment
## Radarr (Docker on Ubuntu Server)
![image](https://user-images.githubusercontent.com/94716517/201493847-14df9d1b-fd1f-45b0-a92b-9020a0a9b0df.png)

## Google Chrome
![image](https://user-images.githubusercontent.com/94716517/201493872-7d5d41c0-693f-4847-bbb4-4659d703d8f7.png)

## Windows OS
![image](https://user-images.githubusercontent.com/94716517/201493907-ef98f488-b23b-4309-8a40-ac6b1e6f1f67.png)

### Expected Behavior

Expected a horizontal scroll bar to appear at the bottom of the screen, or for the posters to loop back and stay within the screen constraints.

### Steps To Reproduce

Run Radarr in Docker (see above)

### Environment

```markdown
(see above)
```

### What branch are you running?

Master

### Trace Logs?

( see above)

[AB#4056](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4056)

**Comment by Qstick** [comment]
Click the arrow buttons above the posters or drag to scroll

**Comment by KingIzzymon** [comment]
... please close this ticket as fast as you can
