### ISSUE TITLE
Radarr not adding movies from folder.

### ISSUE THREAD

**Issue by bakthomas** [Radarr/Radarr#776]
Description:

When I added my Movies folder Radarr added all of the movies to the Movies tab.
However, it sees half of the movies as missing, even though the movie file is in the directory.

Radarr Version: 0.2.0.299

Logs:

17-2-17 10:09:10.1|Info|RefreshMovieService|Updating Info for Best Man Down
17-2-17 10:09:11.0|Info|DiskScanService|Scanning disk for Best Man Down
17-2-17 10:09:11.0|Warn|ParsingService|Unable to parse movie info from path \\192.168.0.60\Media\Movies\Best Man Down\Best Man Down.mp4
17-2-17 10:09:11.0|Info|DiskScanService|Completed scanning disk for Best Man Down

**Comment by fedoranimus** [comment]
If you add "(YEAR)", where Year is the year the movie was released to the filename, does Radarr see it?

**Comment by bakthomas** [comment]
Yeah, looks that way, just testing now.

**Comment by bakthomas** [comment]
Yes it does. Thanks. painful, but thanks.
