### ISSUE TITLE
Make a List's root folder an array

### ISSUE THREAD

**Issue by dfadev** [Radarr/Radarr#7786]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

If the root folder a List refers to is full and Radarr wants to move a completed downloaded, it will fail.

### Describe the solution you'd like

The root folder a list refers to should be an array of folders so radarr can determine a folder with enough space to move the download into.

### Describe alternatives you've considered

When a root folder fills up, I currently:

- add more space / add a root folder
- change the list's root folder
- manually edit the movie file paths for queued downloads
- manually import downloads that failed due to no space on root folder

### Anything else?

The filesystem layout I'm using is similar to:

/data/scratch/downloads
/data/scratch/torrents
/data/a/movies
/data/b/movies
/data/c/movies

[AB#4179](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4179)

**Comment by Qstick** [comment]
No plans to add this right now.
