### ISSUE TITLE
add additional search buttom to cut 

### ISSUE THREAD

**Issue by jscottdouglas** [Radarr/Radarr#779]
![image](https://cloud.githubusercontent.com/assets/15646181/23052312/5a343dea-f49e-11e6-8235-ad15d0a508ab.png)

Can we please get a button to search all unmet cut off like in the missing tab

![image](https://cloud.githubusercontent.com/assets/15646181/23052330/7f903b20-f49e-11e6-801a-b85ecad5d2e8.png)

I have 88 pages that I would have to select each one individually for them to re-search all cutoff not met woud like a button to just search them all.

**Comment by onedr0p** [comment]
Fixed in next release
