### ISSUE TITLE
Please support QoQ

### ISSUE THREAD

**Issue by mbnn** [Radarr/Radarr#780]
**Description:**

Please support QoQ or -QoQ- in the name of the releasename when it's saving/renaming.
QoQ are one of the biggest release groups in NL and have a great reputation.

Right now when it saves/renames (with rlsgroup), it will come out as Sonarr.

**Radarr Version:**
 0.2.0.299

**Logs:**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by schumi2004** [comment]
They are also stubborn to follow scene release rules which forces you to do this request!

**Comment by onedr0p** [comment]
Can you give us a full release name example?

**Comment by michielbeenen** [comment]
Examples:
LIVE BY NIGHT x264 1080p (WEB-DL) DD5.1 NLSubs -QoQ-
SING (2016) x264 1080p (WEB-DL) DD5.1 NLSubs -QoQ-
COLLATERAL BEAUTY (2016) x264 1080p Bluray DTS-HDMA 5.1 NLSubs -QoQ-
or
PASSENGERS (2016) x264 1080p (WEB-DL) DD5.1 NLSubs -QoQ-

Thank you :)

**Comment by mbnn** [comment]
Another example:
LOOKING GLASS (2018) 1080P x264 NL SUBS INSTELBAAR (QoQ)

Radarr renames it to: Looking Glass (2018) x264 1080p Radarr

Can this please include QoQ when  it is from QoQ? :)

**Comment by bakerboy448** [comment]
No plans for special handling for groups that don't follow scene rules at this time.
