### ISSUE TITLE
Radarr not seeing newly downloaded movies in Movies folder

### ISSUE THREAD

**Issue by english06** [Radarr/Radarr#781]
**Description:**

Order of events: Radarr sends request to Deluge, Deluge downloads, rclone moves, FileBot runs and moves to movie folder Radarr/Plex is using.

I have 'completed download handling' and 'renamer' off for Radarr. I would expect it to be able to refresh the library and see that there is now a movie (appropriately named) in the folder Radarr has on file, but it does not. Is this a bug or just something that needs to still be implemented?

**Radarr Version:** 0.2.0.299

**Comment by fedoranimus** [comment]
Have you tried running "Refresh Library" or the Refresh button on the specific movie page to see if Radarr picks it up?

What is the naming scheme of the folder and directory that FileBot is handling?

**Comment by english06** [comment]
> Have you tried running "Refresh Library" or the Refresh button on the specific movie page to see if Radarr picks it up?

Yes. That was Step 1.

> What is the naming scheme of the folder and directory that FileBot is handling?

Media Drive/Movies/Title (Year)/Title [Quality]

**Comment by zductiv** [comment]
Try renaming the file as Media Drive/Movies/Title (Year)/Title (Year) and seeing if it picks it up.

**Comment by english06** [comment]
This also did not solve the issue. Each of these were newly downloaded files by Radarr not part of the initial manual import.

**Comment by english06** [comment]
@galli-leo I have attached some logs to help diagnose.

```
17-2-22 01:25:32.1|Info|RefreshMovieService|Updating Info for Room
17-2-22 01:25:32.4|Info|DiskScanService|Scanning disk for Room
17-2-22 01:25:32.6|Error|VideoFileInfoReader|Unable to parse media info from file: \\Expandrive\nh1pjf-1\Media Drive\Movies\Room (2015)\Room [720p].mp4

[v0.2.0.299] System.IO.IOException: A device attached to the system is not functioning.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.ReadCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.FileStream.Read(Byte[] array, Int32 offset, Int32 count)
   at NzbDrone.Core.MediaFiles.MediaInfo.MediaInfo.Open(Stream stream) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\MediaInfo\MediaInfoLib.cs:line 202
   at NzbDrone.Core.MediaFiles.MediaInfo.VideoFileInfoReader.GetMediaInfo(String filename) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\MediaInfo\VideoFileInfoReader.cs:line 55

17-2-22 01:25:32.7|Error|ImportDecisionMaker|Couldn't import file. \\Expandrive\nh1pjf-1\Media Drive\Movies\Room (2015)\Room [720p].mp4

[v0.2.0.299] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.MediaFiles.EpisodeImport.ImportDecisionMaker.GetDecision(String file, Movie movie, ParsedMovieInfo folderInfo, Boolean sceneSource, Boolean shouldUseFolderName, Boolean shouldCheckQuality) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaFiles\EpisodeImport\ImportDecisionMaker.cs:line 125

17-2-22 01:25:32.7|Info|DiskScanService|Completed scanning disk for Room
```

**Comment by galli-leo** [comment]
Seems like MediaInfo cannot read the file. I should implement a try catch there, but it's probably a permission issue.

**Comment by english06** [comment]
> Seems like MediaInfo cannot read the file. I should implement a try catch there, but it's probably a permission issue.

Permission issue? It can see the drive and folders, but not the individual files.

**Comment by mechanimal82** [comment]
Not sure if this is related but I have 203 movies in my library, 76 of these are showing as 'Missing' in Radarr even though the file exists and meets the cut-off. 

The first error captured is by the VideoFileInfoReader:

> Unable to parse media info from file: /mnt/data/Plex/Movies/Terminator Genisys (2015)/Terminator Genisys (2015) Bluray-1080p.mkv: Invalid handle to path "/mnt/data/Plex/Movies/Terminator Genisys (2015)/Terminator Genisys (2015) Bluray-1080p.mkv"

and the exception details:

> System.IO.IOException: Invalid handle to path "/mnt/data/Plex/Movies/Terminator Genisys (2015)/Terminator Genisys (2015) Bluray-1080p.mkv"
>   at System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean anonymous, FileOptions options) <0x7f1e4a8e2240 + 0x005ed> in <filename unknown>:0 
>   at System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean isAsync, Boolean anonymous) <0x7f1e4a8e21e0 + 0x0005a> in <filename unknown>:0 
>   at System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access) <0x7f1e4a8e1e50 + 0x00053> in <filename unknown>:0 
>   at (wrapper remoting-invoke-with-check) System.IO.FileStream:.ctor (string,System.IO.FileMode,System.IO.FileAccess)
>   at NzbDrone.Common.Disk.DiskProviderBase.OpenReadStream (System.String path) <0x414e3bf0 + 0x00050> in <filename unknown>:0 
>   at NzbDrone.Core.MediaFiles.MediaInfo.VideoFileInfoReader.GetMediaInfo (System.String filename) <0x414e2ba0 + 0x00224> in <filename unknown>:0

This then leads to an error with the ImportDecisionMaker:

> Couldn't import file. /mnt/data/Plex/Movies/Terminator Genisys (2015)/Terminator Genisys (2015) Bluray-1080p.mkv: Object reference not set to an instance of an object

with exception detail:

> System.NullReferenceException: Object reference not set to an instance of an object
>   at NzbDrone.Core.MediaFiles.EpisodeImport.ImportDecisionMaker.GetDecision (System.String file, NzbDrone.Core.Tv.Movie movie, NzbDrone.Core.Parser.Model.ParsedMovieInfo folderInfo, Boolean sceneSource, Boolean shouldUseFolderName, Boolean shouldCheckQuality) <0x414e0f10 + 0x0022f> in <filename unknown>:0 


I've tried refreshing the list, but the same errors are getting captured. Any thoughts?

**Comment by onedr0p** [comment]
@mechanimal82 I am getting this as well, while I have that reproduced on my server. I cannot get it reproduced on my dev machine.

**Comment by jamescross91** [comment]
Same issue here

**Comment by obelisk3847** [comment]
Seen this intermittently myself. Seems to be only with mp4 and not mkv or avi.
