### ISSUE TITLE
Option to "Search for Upgrades for XX days After Initial Download" in quality profiles.

### ISSUE THREAD

**Issue by grooves12** [Radarr/Radarr#7817]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Upgrades are sometimes happening long after a movie has been released, downloaded, and watched.

### Describe the solution you'd like

I would like an option in the quality profile to limit the amount of time Radarr will continue searching for an upgraded format:
"Continue searching for upgrades for _____ days after first download"

### Describe alternatives you've considered

All other solutions require manual intervention, which is not ideal.

### Anything else?

N/A

[AB#4253](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4253)

**Comment by bakerboy448** [comment]
Easiest existing way would be to set up some sort of script that unmonitored the movie after it's imported the file after X days.

In download custom script to create a date stamped movie file with the radarr ID. And then a script on a cron checking those files and making calls to the api to unmonitor the movies

**Comment by Qstick** [comment]
No plans for this sort of setting, we'll be doing some fun things with automation in v5, until then you can turn off upgrades in the quality profile or unmonitor it.
