### ISSUE TITLE
Allow filtering option for Trakt Lists

### ISSUE THREAD

**Issue by onedr0p** [Radarr/Radarr#782]
Should be able to implement filtering via their API:
http://docs.trakt.apiary.io/#introduction/filters/common-filters

**Comment by galli-leo** [comment]
Wouldn't it be better to enable filtering of lists at a global list level in map movie to tmdb? And instead of using url params, just check the info we get back from tmdb and decide if we should import it or not? This way it's handeled the same aceoss all lists.

**Comment by onedr0p** [comment]
@galli-leo I think it's better handle it per list, every API handles things differently. For example trakt doesn't have number of votes and tmdb does. 

Also say someone wants a list of kids movies with a popular rating, and also another list with a adult rated R list of movies with a higher than 3 rating with 1000 minimum votes. We could write a system for list requirements and then people can attach that to a list but that's a lot of work I don't have time for that ultimately does the same thing.

**Comment by onedr0p** [comment]
The URL params are needed though, those endpoints are specific to what kind of list they want. Without the params we would have to search thru hundred or thousands of pages of movies to find the ones they want for the list.

**Comment by galli-leo** [comment]
We can still implement this globally in the map movie to tmdb method and then do it individually, if the list provides an endpoint for that? That could save us some work and would enable this feature easily for lists such as StevenLu or RSS.

**Comment by onedr0p** [comment]
Ah I see, yeah global filters can be added along with list filters. That's another issue though.
