### ISSUE TITLE
Set limit for IMDb popular result

### ISSUE THREAD

**Issue by lsaadeh** [Radarr/Radarr#7822]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

IMDb list returns all of the top 100 most popular movies.

### Describe the solution you'd like

Define a limit for the results to return.. i.e. top 5, 10, 23 etc..

### Describe alternatives you've considered

no alternatives for imdb

### Anything else?

neg

[AB#4269](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4269)

**Comment by bakerboy448** [comment]
Does not appear possible / IMDB does not appear to support.

@Qstick is this something that could/should be done app side and truncating the response?

**Comment by Qstick** [comment]
There's an issue for additional list filtering already, this would be essentially same thing. That is in plan

**Comment by Qstick** [comment]
Closing for reference to #1576
