### ISSUE TITLE
Indexers unavailable due to failures

### ISSUE THREAD

**Issue by breezytm** [Radarr/Radarr#784]
My indexers constantly and randomly stops working and I have to manual restart the application for them to work again. I know the indexers work because the same exact ones are working in Sonarr without any issues. After a reboot, the test runs successfully. After the issue occurs it states it's unable to connect. Both of them, same issue.

In radarr

17-2-16 15:11:30.5|Info|RssSyncService|Starting RSS Sync
17-2-16 15:11:30.5|Warn|FetchAndParseRssService|No available indexers. check your configuration.
17-2-16 15:11:30.6|Info|DownloadDecisionMaker|No results found
17-2-16 15:11:30.6|Info|RssSyncService|RSS Sync Completed. Reports found: 0, Reports grabbed: 0
17-2-16 15:26:40.3|Info|InstallUpdateService|Deleting old update files
17-2-16 15:26:40.3|Info|InstallUpdateService|Downloading update 0.2.0.368
17-2-16 15:26:40.3|Info|RssSyncService|Starting RSS Sync
17-2-16 15:26:40.4|Warn|FetchAndParseRssService|No available indexers. check your configuration.
17-2-16 15:26:40.4|Info|DownloadDecisionMaker|No results found
17-2-16 15:26:40.4|Info|RssSyncService|RSS Sync Completed. Reports found: 0, Reports grabbed: 0
17-2-16 15:26:40.6|Warn|HttpClient|Failed to get response from: https://ci.appveyor.com/api/buildjobs/a5g7h6b5y9xumklf/artifacts/_artifacts/Radarr.develop.0.2.0.368.linux.tar.gz Error: SecureChannelFailure (The authentication or decryption has failed.)
17-2-16 15:26:40.9|Error|CommandExecutor|Error occurred while executing task ApplicationUpdate

In Sonarr

17-2-15 20:51:23.7|Info|NzbSearchService|Searching 3 indexers for [24: Legacy : S01E03]
17-2-15 20:51:25.9|Info|DownloadDecisionMaker|Processing 46 releases
17-2-15 20:52:11.6|Info|Nzbget|Adding report [24.Legacy.S01E03.1080p.Amazon.WEBRip.DD.5.1.x264-ViscaBarca-Obfuscated] to the queue.
17-2-15 20:52:12.4|Info|DownloadService|Report sent to NZBGet. 24.Legacy.S01E03.1080p.Amazon.WEBRip.DD.5.1.x264-ViscaBarca-Obfuscated
17-2-15 20:52:25.6|Info|RssSyncService|Starting RSS Sync
17-2-15 20:52:25.8|Info|NzbSearchService|Searching 3 indexers for [The Walking Dead : S07E09]
17-2-15 20:52:30.1|Info|DownloadDecisionMaker|Processing 225 releases

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by galli-leo** [comment]
Which indexers are you using?

**Comment by rickytin** [comment]
For me it's dognzb, it was working but not now, it's works in Sonarr not in Radarr.

**Comment by breezytm** [comment]
I have https://nzb.cat and https://01100111011001010110010101101011.info 
I also have my local spotweb in Sonarr but that does not work at all in Radarr. I know it's a known issue.

**Comment by galli-leo** [comment]
Is this happening after a specific movie? I am suspecting the failing omdbapi to be the issue here.

**Comment by breezytm** [comment]
It's weird. I switched from nightlies to master and it stopped happening. Interestingly enough I went to nightlies from master because I thought the issue could have had already been fixed in nightlies. I just wanted to check before opening an issue. It's been a couple of days now and the error has not appeared.

**Comment by galli-leo** [comment]
@breezytm It could just be because omdbapi is back up and the switch to master branch (btw. it should be develop, master will not get an update until the full 0.2 release which is quite far off) somehow made Radarr test them again.

**Comment by breezytm** [comment]
Yeah. I will monitor if for a few days. If nothing happens I will ask to close the issue. Funny thing is my colleague had the same issue and we both switched branches and we both are not longer seeing the issue :/

**Comment by onedr0p** [comment]
Are you still experiencing issues?

**Comment by breezytm** [comment]
No sir. I would say close it and if it reappears I can always open a new case.
