### ISSUE TITLE
Search is not triggered when switching between movies while 'Search' tab is focused

### ISSUE THREAD

**Issue by lps-rocks** [Radarr/Radarr#7895]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When using the next/previous movie arrows in the top right-hand corner, and the 'Search' tab is focused - a manual search is not triggered when navigating to the next or previous movie. The 'search' tab must be unfocused by clicking to another tab and then selected again.

### Expected Behavior

A manual search should automatically be triggered when the 'Search' tab is focused after navigating between movies using the arrows.

### Steps To Reproduce

1. Add 2 movies to radarr
2. View movie A
3. Trigger manual search by focusing the 'Search' tab
4. Use navigation arrow in top right to navigate to Movie B
5. Search tab is still focused but no manual search is completed.

### Environment

```markdown
- OS: Whatever the docker container is using as a base
- Radarr: 4.3.1.6822
- Docker Install: Yes
- Using Reverse Proxy: No 
- Browser: Firefox 107.0.1
- Database: Sqlite
```

### What branch are you running?

Develop

### Trace Logs?

N/A  - looks like a UI bug?

[AB#4468](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4468)

**Comment by austinwbest** [comment]
It is a long standing UI bug, yes.

**Comment by lps-rocks** [comment]
Is there another issue for it, if so i'll close this one referencing the other one - The search terms to try and find other issues with this behavior are super common so I wasn't able to find an existing issue without going through 10+ pages of issues.

**Comment by Qstick** [comment]
Dupe #5575
