### ISSUE TITLE
Testing note / Potato Caution

### ISSUE THREAD

**Issue by toddcurry** [Radarr/Radarr#790]
With the magic of docker, I setup Radarr in mere moments, selectively copying the docker setup from CP.

I regretted that immediately, but not terribly:  the two started stepping on each other's toes, particularly with CP re-naming and moving movies that appear in a "working" directory, forcing Radarr to wonder what happened.  

If I were a "script kiddie" I would be posting "Radarr isn't working" here, and ugh: the noise.... Big ugh.

To avoid that ring of Dante's hell, I respectfully suggest you include a one-liner here (and ask the LinuxServer.io guys to do same in their docker container), saying:   Users who are evaluating Radarr while continuing to run CP are advised to set up separate NZB categories and download folders to avoid contention and help us get the cleanest information we can for testing.    Just a suggestion.

**Comment by onedr0p** [comment]
I think that's common sense tbh, you don't want to have 2 applications like these working with the same directories.
