### ISSUE TITLE
Authenticate with Trakt failed

### ISSUE THREAD

**Issue by gipasoft** [Radarr/Radarr#7905]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

If I try to authenticate with Trakt fron list settings i obtain this exception: `Received oauth token was invalid.`

![image](https://user-images.githubusercontent.com/1884550/208296072-cae39c2f-d77f-417c-a8ce-43394bf5e134.png)

Exception:

![image](https://user-images.githubusercontent.com/1884550/208296085-466cccf8-a855-4399-b662-81290d8e2647.png)

### Expected Behavior

Complete the trakt auhentication

### Steps To Reproduce

1. Open Settings ==> List
2. Add New List selecting `Trakt List`
3. Click on `Authenticate with Trakt`

### Environment

```markdown
- OS: Qnap QTS 5.0.1.2248
- Radarr: Radarr 4.2.4.6635
- Docker Install: Yes (4.2.4.6635-ls153 by linuxserver.io)
- Using Reverse Proxy: No
- Browser: Chrome 108.0.5359.125 (64 bit)
- Database: Sqlite 3.36.0
```

### What branch are you running?

Master

### Trace Logs?

[radarr.trace.txt](https://github.com/Radarr/Radarr/files/10253726/radarr.trace.txt)
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/10253727/radarr.debug.txt)

[AB#4492](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4492)

**Comment by Qstick** [comment]
They’ve had api issues for over a week due to a db corruption. They have advised things should be back next week.
