### ISSUE TITLE
Migration from 4.1.0.6175 to 4.2.x fails

### ISSUE THREAD

**Issue by XciD** [Radarr/Radarr#7906]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I can't update from `4.1.0.6175` to any `4.2.x` version

I've got this error:
```
NOT NULL constraint failed: AlternativeTitles.MovieMetadataId
While Processing:
"UPDATE "AlternativeTitles"
                          SET "MovieMetadataId" = (SELECT "Movies"."MovieMetadataId"
                                                  FROM "Movies"
                                                  WHERE "Movies"."Id" = "AlternativeTitles"."MovieId")"
 ---> code = Constraint (19), message = System.Data.SQLite.SQLiteException (0x800027AF): constraint failed
NOT NULL constraint failed: AlternativeTitles.MovieMetadataId
```

### Expected Behavior

Migration to sucess

### Environment

```markdown
- OS: Linux
- Radarr:  4.1.0.6175
- Database: Sqlite
```

### What branch are you running?

Master

### Trace Logs?

None

[AB#4493](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4493)

**Comment by bakerboy448** [comment]
See the malformed database entry on the FAQ

migration issues caused by existing corruption are generally not bugs

**Comment by Qstick** [comment]
This is not a case of corruption, it's generally a case of orphaned alt titles in the DB that were not cleaned by housekeeping prior to the migration. Running the housekeeper first should theoretically fix this for migration, wouldn't be bad for the migration to handle it, but 90% of users are already migrated through this, so it's low reward.
