### ISSUE TITLE
Radarr (and Sonarr) not removing download task and file from Deluge

### ISSUE THREAD

**Issue by illuvattarr** [Radarr/Radarr#7918]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I have Radarr (and Sonarr) set up to use hardlinks when copying files that are still seeded by Deluge, and to remove download tasks from Deluge when seeding is finished is also set in the download client settings. But when seeding is finished and the task is paused by Deluge, Radarr does not remove the task and the file in the download folder is also not removed.

This is the process that happens:

1.     Radarr sends download task to Deluge
2.     Deluge completes downloading the torrent
3.     Radarr hardlinks the files to the correct folder and keeps a file in the download folder
4.     The AutoRemovePlus plugin in Deluge pauses the task in Deluge after seeding time/ratio conditions are met
5.     Radarr does not remove the paused task and does not remove the file from the downloads folder

### Expected Behavior

I expect Radarr/Sonarr to remove the paused task in Deluge, and delete the file in the download folder.

### Environment

```markdown
- OS: Docker on Synology NAS
- Radarr: 4.2.4.6635-ls156 by linuxserver.io
- Docker Install: Yes
```

### What branch are you running?

Master

### Trace Logs?

https://gist.github.com/illuvattarr/52bf1ebd38ab341d0552fc6d358c6195

[AB#4523](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4523)

**Comment by bakerboy448** [comment]
Seed time is not supported for deluge

https://wiki.servarr.com/radarr/settings#torrent-client-remove-download-compatibility

**Comment by illuvattarr** [comment]
I'm using a plugin (AutoRemovePlus) to pause the torrent. 
What is then exactly needed to have Radarr remove torrenttasks and their download files? Do the files only need to be paused for it to trigger to remove, or does it necessarily have to get to the set ratio?

**Comment by bakerboy448** [comment]
The wiki details exactly whats needed.

https://wiki.servarr.com/radarr/settings#completed-download-handling

> For torrents this requires your download client to **pause upon hitting the seed goals. It also requires the seed goals to be supported by Radarr per the above table.** Torrents must also stay in the same category.

Code
https://github.com/Radarr/Radarr/blob/develop/src/NzbDrone.Core/Download/Clients/Deluge/Deluge.cs#L179-L185

Again, please use one of the support channels: [Reddit](https://www.reddit.com/r/radarr/) or  [Discord](https://radarr.video/discord) for support/questions.
