### ISSUE TITLE
Radarr not finding movies that are there

### ISSUE THREAD

**Issue by petwri** [Radarr/Radarr#792]
I have the problem that Radarr (both current nightly build and older versions) never finds certain movies that the indexer shows when doing a manual search. When I do a standard search on usenet-crawler for one of the candidates, they are there. Using the same search string as radarr does, I get a result with the name 'Movie Title (2008) 720p Blu-ray' in a matching category, 2.2 yrs old, which is less then 3100 days retention, among other results that are the correct movie. Any ideas why radarr could complain about no movie found?

**Comment by petwri** [comment]
I figured out what the problem was, apparently Radarr uses the imdbid to search an indexer, not the name of the movie as a string. This requires the movie to be properly indexed with an imdb, otherwise it will never get found by Radarr.

**Comment by qdev76** [comment]
do you know where Radarr makes that call?

**Comment by petwri** [comment]
@qdev76 what do you mean by "where"? Where the particular code is? I found it going through the debug logs.

**Comment by onedr0p** [comment]
@petwri please close this issue if you think you're set.. There's not much we can do if we can't find the movie via IMDB or by title

**Comment by petwri** [comment]
@onedr0p well, thats the issue: the movie can be found via title. But it seems like radarr only works via imdb, which is kind of a bummer, because it misses quite a lot of releases then.

**Comment by galli-leo** [comment]
@petwri But it makes sense, since the title is often very innaccurate. So you get lots of useless releases. Maybe we can think about doing a search by title, if no results came up. Please open a feathub for that.
