### ISSUE TITLE
[API] MovieSearch command not working

### ISSUE THREAD

**Issue by mikey2p22** [Radarr/Radarr#794]
The API Command "MovieSearch" does not work.
Since I'm developing an Android App for Radarr this is a quiet important feature.

**Comment by onedr0p** [comment]
I'm sure this works, are you sending the right parameters?

**Comment by mikey2p22** [comment]
Well, not sure... ^^
I tried what you guys wrote in the wiki page:

![image](https://cloud.githubusercontent.com/assets/18078206/23702217/a107674a-03fa-11e7-9f0b-fac3278a1833.png)

I also tried different post requests, changing the parameter "episodeIds" to every possible variable. without success.
My Request:
![image](https://cloud.githubusercontent.com/assets/18078206/23702300/ecc255c8-03fa-11e7-9d0c-9e86f9e4b7be.png)

The Response:
![image](https://cloud.githubusercontent.com/assets/18078206/23702311/f8ed8d36-03fa-11e7-81a3-16bce20ab5fb.png)

Can you maybe give me an example of a working request? (with fake url of course)

**Comment by galli-leo** [comment]
```
{
	"name" : "MoviesSearch",
		"movieIds" : [3]
	
}
```

Works for me

**Comment by mikey2p22** [comment]
Thank you.
I tried the parameter "movieIds" more than once without success.
The problem was the name. I used MovieSearch instead of MoviesSearch.
