### ISSUE TITLE
Manual import UI issues

### ISSUE THREAD

**Issue by danpowell88** [Radarr/Radarr#795]
When click the movie cell to enter in the movie title the filter box should be focused, currently it isn't happening, looking at the code there is something in there that looks like its trying to set focus so not sure if that's just not working.

Additionally if I hit escape (possible other keys) after the select movie page has loaded it closes the Manual Import dialog instead of the "Select movie" dialog, again this might be related to the focus issue as if I click the filter textbox and then try this doesn't seem to happen.

**Comment by galli-leo** [comment]
What browser are you on? Did you try another one?

**Comment by danpowell88** [comment]
Chrome 56.0.2924.87
IE Edge
IE 11 (11.576.14393.0)
