### ISSUE TITLE
Updating will not be possible to prevent deleting AppData on Update

### ISSUE THREAD

**Issue by squeakygreens** [Radarr/Radarr#796]
Radarr is throwing the "Updating will not be possible..." error, and upon investigating, I noticed all Radarr settings files are in the root Radarr directory (C:\ProgramData\Radarr) while my Sonarr installation has more subfolders, namely for the configuration files, seemingly preventing this error (C:\ProgramData\NZBDrone\Bin).

Is there any way to change the directory of these files in Radarr to remedy this error?

**Comment by galli-leo** [comment]
Please follow the installation instructions on the wiki. You have to delete all Radarr exe files from the ProgramData folder and the follow the instructions on the wiki.
