### ISSUE TITLE
Add Croatian Language

### ISSUE THREAD

**Issue by TheHrle** [Radarr/Radarr#7967]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Croatian language not available.

### Describe the solution you'd like

I would translate the apps myself to Croatian. I could also translate to Serbian and Bosnian since the languages are similar.

### Describe alternatives you've considered

There are no alternatives.

### Anything else?

No

[AB#4646](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4646)

**Comment by Qstick** [comment]
These should be available to translate now
