### ISSUE TITLE
|Info|SingleInstancePolicy|1 instance(s) of Sonarr are running

### ISSUE THREAD

**Issue by ajkis** [Radarr/Radarr#797]
17-2-19 04:03:29.9|Info|Bootstrap|Starting Radarr - /opt/Radarr/Radarr.exe - Version 0.2.0.299
17-2-19 04:03:36.8|Info|SingleInstancePolicy|1 instance(s) of Sonarr are running
17-2-19 04:03:36.8|Warn|SingleInstancePolicy|Another instance of Radarr is already running.
17-2-19 04:03:36.8|Info|Bootstrap|Application is being terminated. Reason : Another instance is already running
17-2-19 04:07:52.4|Info|Bootstrap|Starting Radarr - /opt/Radarr/Radarr.exe - Version 0.2.0.299
17-2-19 04:07:53.9|Info|MigrationLogger|*** Migrating data source=/home/plex/.config/Radarr/nzbdrone.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
17-2-19 04:07:54.0|Info|MigrationLogger|*** Migrating data source=/home/plex/.config/Radarr/logs.db;cache size=-10485760;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
17-2-19 04:07:54.0|Info|Router|Application mode: Interactive
17-2-19 04:07:54.0|Info|OwinHostController|Listening on the following URLs:
17-2-19 04:07:54.0|Info|OwinHostController|  http://*:7878/
17-2-19 04:07:54.1|Info|NancyBootstrapper|Starting NzbDrone API

**Comment by galli-leo** [comment]
What about that? It's just an info statement wont impact anything.
