### ISSUE TITLE
Avoid loading more movies on the import screen than radarr is capable of importing.

### ISSUE THREAD

**Issue by lknite** [Radarr/Radarr#7984]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

![image](https://user-images.githubusercontent.com/92187614/211688225-2fa646c4-b87b-4abf-b413-e4d596ef2977.png)

### Describe the solution you'd like

Two solutions:
1. Add a drop down with how many movies to try importing, such as '25', '50' or '100' or whatever makes sense.  For those bringing in many files, it can be easier to do a few at a time now and then, rather than try to work with them all at once.
2. Only load as many import rows as the app is capable of handling.  This is to avoid the situation where someone takes the time to review several lines of imports, only to watch the page crash when they click 'import'

### Describe alternatives you've considered

I usually try to click 'cancel' after a few load, review those then import, but after canceling if sometimes you click an unmatched file to match it will start scanning imports again ... then you might only catch this after quite a few have been loaded up pending import... then when you finally click to import, crash.

### Anything else?

I run things in a kubernetes home lab and this means I am trying out new things all the time.  This has lead to starting over and reloading things as I learn more.  Leading to re-imports of my media files.  Making this for an issue which has been revisited on several occasions.  Possibly it's been overlooked because in general people import once and forget about it ...

[AB#4691](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4691)

**Comment by bakerboy448** [comment]
- There's no limit to the number of library folders to be import.  The theoretical limit is based on the user's system's specs.
- typically that or a similar error has been seen it has been caused by a improperly configured reverse proxy or something messing with the http requests.....not radarr

> This has lead to starting over and reloading things as I learn more. 

Any particular reason you delete your radarr database and config file and start from scratch every time / use a different path for your config mount?  I can't think of any reason why one would need to do that.

**Comment by lknite** [comment]
I think something else may be happening here.  I allowed 10 records to be found, waited 5 minutes and clicked import.  This worked, then I did it again with 10 records, waited 10 minutes and clicked import, this worked.

So I let 500 records fill in, this took 5 minutes, then I clicked import and it crashed.  So, I don't think it is related to a timeout.  I was watching the log / console of the container at the time and it didn't produce any errors.  Also was watching the nginx ingress controller log (reverse proxy) and there were no errors there either.

I'm still under the impression it might be a bug or something, but if you are sure it's just support I can go there for troubleshooting.  Can also perform any debugging steps if you have any for me ...

**Comment by lknite** [comment]
Actually, I'll go over to support ... maybe its something else still to do with the reverse proxy / proxy body size or something.  Thanks for your help.  If / when I figure it out I'll post the fix here if it's just something simple like an annotation on the ingress.

**Comment by lknite** [comment]
The following annotation got things working for me:
```nginx.ingress.kubernetes.io/proxy-body-size: 8m```
