### ISSUE TITLE
Add New only loading posters for first few movies

### ISSUE THREAD

**Issue by bakerboy448** [Radarr/Radarr#7988]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Posters are greyed out and not loaded.
URLs for images are in the api response and load when clicked/opened for details....seems UI related

![image](https://user-images.githubusercontent.com/55419169/212183611-4d08f963-96b7-4d0e-b811-6fe6dd397e1b.png)
![image](https://user-images.githubusercontent.com/55419169/212183714-ca1d6895-7bed-4725-9938-4c151a6f03ca.png)

### Expected Behavior

all posters should load as when scrolling

### Steps To Reproduce

1. Add New
2. Search anything
3. see only first 3 posters

### Environment

```markdown
- OS: ubuntu 20.04
- Radarr: 4.4.0.6875
- Docker Install: No
- Using Reverse Proxy: Yes
- Browser: Chrome Version 108.0.5359.126 (Official Build) (64-bit)
- Database: DB Migration 214 Database Sqlite 3.31.1
```

### What branch are you running?

Nightly

### Trace Logs?

https://gist.github.com/bakerboy448/876412d8149e57ac04d540a7ad77007d

[AB#4704](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4704)

**Comment by ABEIDO** [comment]
I have the same issue, running on win10. 
Tested to set up new radarr install on unraid docker with same issue occuring.

To add  when you click a movie to add it, poster is shown in the popup window.

**Comment by littlebirdiegr** [comment]
Hopefully this will be fixed. I have been using third party apps that connect to radarr since this bug started, as not seeing the posters, makes it really hard to find the stuff I want. Fingers Crossed

**Comment by clipper99** [comment]
> Hopefully this will be fixed. I have been using third party apps that connect to radarr since this bug started, as not seeing the posters, makes it really hard to find the stuff I want. Fingers Crossed

Could you share what apps I could try to fix this for me? 

Cheers

**Comment by Qstick** [comment]
12e360ab4f
