### ISSUE TITLE
watch folder to process manually downloaded movies

### ISSUE THREAD

**Issue by skaynl** [Radarr/Radarr#7990]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

no

### Describe the solution you'd like

watch a folder for new files
suggest a movie (manually override option like with library imports)
use this information to create the folder and movie with predefined set names ({movietitlethe} {Release Year} {Quality Full} etc) and the other metadata files 
option to delete the file in the watch folder

### Describe alternatives you've considered

I come from a couchpotato background and still use that for this purpose only, it watches the folder and moves and creates all the files I want. If it doesn't no what movie it is (or if it chooses the wrong movie) you can create an moviename.nfo file with the imdb ttxxxxx number in it and it will proceeds correctly.

### Anything else?

nothing else

[AB#4708](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4708)

**Comment by austinwbest** [comment]
At this time that is not something that is being discussed or planned. Movies should be added to Radarr prior to trying to attach media to them. I will leave this open and Q can give his thoughts if he likes but i dont see this one making it in, sorry bud.

**Comment by Qstick** [comment]
You can use blackhole to process the files, but yes the movie has to already be in Radarr. You can likely script something up to make this happen if you really need it, but no plans to add into Radarr for now
