### ISSUE TITLE
Able to import Custom Formats in one file. 

### ISSUE THREAD

**Issue by bokkoman** [Radarr/Radarr#8000]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

No. 

### Describe the solution you'd like

Right now you'd have to import each CF separately. Would be nice if you can import (and maybe export?) them from one file. Perhaps in a big json (or other format).

### Describe alternatives you've considered

There is notifiarr and recyclarr.
Just thinking this would be a nice addition to the arrs. 

### Anything else?

Can be helpful together with trash-guides. Especially with interactive flowcharts. Where you potentially could end up with 1 file containing all the CFs you'd need to import.

[AB#4737](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4737)

**Comment by bakerboy448** [comment]
- notifiarr and recyclarr can do this
- Someone can also right a quick script for the api to do the same
- Trash CFs are not in one file anyway so a user would still need to combine each one individually making this less needed in radarr
