### ISSUE TITLE
Filename token help popup not properly using darkmode.

### ISSUE THREAD

**Issue by Shadowalker125** [Radarr/Radarr#8001]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Under media management, the help popup boxes for:

- Standard Movie Format
- Movie Folder Format

the text boxes use a white background with grey text when dark mode is turned on. 
 

### Expected Behavior

Maintain an acceptable web contrast standard of at least 7:1 for text.

### Steps To Reproduce

1: Turn on dark mode
2: Open help boxes

### Environment

```markdown
- OS: unRAID 6.11.5
- Radarr: 4.3.2.6857
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Firefox 108.0.2
- Database: Sqlite 3.40.0
```

### What branch are you running?

Master

### Trace Logs?

![image](https://user-images.githubusercontent.com/16189570/212530473-3511e552-11f8-4fcd-8248-734616cc3ae3.png)

[AB#4738](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4738)

**Comment by Qstick** [comment]
@thezak48 FYI
