### ISSUE TITLE
Update keeps changing windows service log on setting

### ISSUE THREAD

**Issue by imthenachoman** [Radarr/Radarr#8005]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I have Radarr installed as a service on Windows 10. I changed the `Log On` property to `Local System account` from the default.

Every time Radarr does an update, it reverts the setting back to the default.

![image](https://user-images.githubusercontent.com/83817/212589310-b1f9789a-7456-4bc8-a533-635d2c49dcf0.png)

### Expected Behavior

It should not revert the `Log On` setting.

### Steps To Reproduce

1. Change `Log On` setting to `Local System account`
2. Let Radarr do an automatic update

### Environment

```markdown
- OS: Windows 10
- Radarr: 4.3.2.6857
- Docker Install: N/A
- Using Reverse Proxy: No
- Browser: N/A
- Database: ?
```

### What branch are you running?

Master

### Trace Logs?

I assume a log is not needed for this? If it is, I can provide.

[AB#4744](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4744)

**Comment by RobinDadswell** [comment]
Can you provide the update logs for radarr please

**Comment by imthenachoman** [comment]
I actually decided to move to running it from a container. I am spinning up a Windows 10 VM and will get logs. I will install an older version, change the `Log On` and then let it update.

**Comment by imthenachoman** [comment]
Heh. I'm having trouble installing an older version. This might take me a while to figure out.

![image](https://user-images.githubusercontent.com/83817/214680300-19230a6b-8c24-4398-99b2-e59bd516142f.png)

**Comment by imthenachoman** [comment]
Okay, so I just tested and this time it did not change the log on as. Very strange. I will debug some more and, if the issue is still valid, I will reopen. Sorry!
