### ISSUE TITLE
Filter Button being squished

### ISSUE THREAD

**Issue by unclenospam** [Radarr/Radarr#8024]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Filter button is sitting within an extra div element compared to the Options, View and Sort buttons.

![image](https://user-images.githubusercontent.com/4606124/214044413-659c384f-369f-47bf-bdaa-0dab9ba27c14.png)
![image](https://user-images.githubusercontent.com/4606124/214044498-9b10fdf5-fdf9-4a5b-adb7-d8d94091cb05.png)

When the filter button is manually moved upped a level, outside of the extra div, it behaves normally like this:

![image](https://user-images.githubusercontent.com/4606124/214044758-ef3e82dc-6003-4f06-82f6-48d41ae6406b.png)
![image](https://user-images.githubusercontent.com/4606124/214044776-efa14b59-71c7-4e5f-8a91-23d4abd92d8f.png)

### Expected Behavior

I would expect the behavior to be closer to this:

![image](https://user-images.githubusercontent.com/4606124/214044758-ef3e82dc-6003-4f06-82f6-48d41ae6406b.png)
![image](https://user-images.githubusercontent.com/4606124/214044776-efa14b59-71c7-4e5f-8a91-23d4abd92d8f.png)

### Environment

```markdown
- OS: Debian 10
- Radarr: Radarr 4.4.1.6900
- Docker Install: No
- Using Reverse Proxy: Yes (NGINX)
- Browser: Firefox 109.0
- Database: Sqlite 3.27.2
```

### What branch are you running?

Nightly

### Trace Logs?

N/A

[AB#4793](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4793)

**Comment by voltron4lyfe** [comment]
I'm looking
