### ISSUE TITLE
Movie poster incorrectly updates to a different movie when adding a new movie

### ISSUE THREAD

**Issue by Spykerwolf** [Radarr/Radarr#8029]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

New movies being added have the incorrect movie poster when you click add movie

### Expected Behavior

New movies should display the correct poster once added

### Steps To Reproduce

Search for a new movie - Rush Hour for example
![image](https://user-images.githubusercontent.com/26391619/214243751-f5c2fe17-d1a4-4407-980d-142b07c41173.png)

Correct poster shows
![image](https://user-images.githubusercontent.com/26391619/214243877-599e870e-49e6-4694-98c6-f938718b26fe.png)

Click Add Movie - poster changes to a different film
![image](https://user-images.githubusercontent.com/26391619/214244009-fb8ebd62-934b-43a1-b8b7-3c54cc84d1f0.png)

However browsing to the movie displays the correct poster
![image](https://user-images.githubusercontent.com/26391619/214244164-41eca3f3-f51a-4c20-b6f5-db10ac87f915.png)

### Environment

```markdown
- OS: Windows 11 Version 21H2 (OS Build 22000.1455)
- Radarr: 4.3.2.6857
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Chrome Version 109.0.5414.75 (Official Build) (64-bit)
- Database: Sqlite 3.36.0
```

### What branch are you running?

Master

### Trace Logs?

https://gist.github.com/Spykerwolf/1f57d0567db4f0d939b0278ab6afdab6

[AB#4799](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4799)

**Comment by Qstick** [comment]
Usually this happens when you start with a new db at some point but don't clear your old MediaCovers folder. 

Thus when you add a new movie it sees the old poster in cache based on the db id, which soon gets overridden by the new poster once the even gets handled in the poster service.

**Comment by Spykerwolf** [comment]
> Usually this happens when you start with a new db at some point but don't clear your old MediaCovers folder.
> 
> Thus when you add a new movie it sees the old poster in cache based on the db id, which soon gets overridden by the new poster once the even gets handled in the poster service.

I think you're right. I renamed the MediaCovers folder & clicked Update All.
Now when I add a movie it shows the correct poster & then 'Missing' once added:

![image](https://user-images.githubusercontent.com/26391619/215889863-37edc7e7-9479-4e4f-8836-c87451d72aef.png)
![image](https://user-images.githubusercontent.com/26391619/215889953-e266ec38-3713-4c41-996d-64333531b227.png)

**Comment by PsychoManiac189** [comment]
> > Usually this happens when you start with a new db at some point but don't clear your old MediaCovers folder.
> > Thus when you add a new movie it sees the old poster in cache based on the db id, which soon gets overridden by the new poster once the even gets handled in the poster service.
> 
> I think you're right. I renamed the MediaCovers folder & clicked Update All. Now when I add a movie it shows the correct poster & then 'Missing' once added:
> 
> ![image](https://user-images.githubusercontent.com/26391619/215889863-37edc7e7-9479-4e4f-8836-c87451d72aef.png) ![image](https://user-images.githubusercontent.com/26391619/215889953-e266ec38-3713-4c41-996d-64333531b227.png)

so it went from showing the poster to not showing the poster? am i understanding this? because ive had this issue for a long time and i dont know how to fix this bug
