### ISSUE TITLE
(not a bug) Added Radarr to AlternativeTo.net

### ISSUE THREAD

**Issue by ZaLiTHkA** [Radarr/Radarr#803]
I've just gone through the initial process of adding Radarr to the app list over on AlternativeTo.net as the first ever alternative to CouchPotato.. These are happy days indeed! :grinning: 

It's currently still awaiting approval, but once that's done it will be available at the following URL: http://alternativeto.net/software/radarr/

When it's available, perhaps someone more closely tied to the project development should have a look and adjust/add information to that page? This will go a long way to getting the word out there that we can *finally* ditch CP.

**Comment by galli-leo** [comment]
Thanks :)
