### ISSUE TITLE
Radarr fails to import short movies automatically

### ISSUE THREAD

**Issue by tvanicraath** [Radarr/Radarr#8038]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Problem: When you download a short movie, say, [Dr. Jekyll and Mr. Hyde (1912)](https://www.imdb.com/title/tt0002143/) Radarr thinks that it is a sample. I have to maunually import it to get it working.

### Describe the solution you'd like

Proposed Solution: Radarr already knows the length of the movie. It can calculate expected file size for different resolutions. If the downloaded movie is a well-formed media file and roughly matches the guessed file size, it should import it automatically.

### Describe alternatives you've considered

Manual import

### Anything else?

NA

[AB#4804](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4804)

**Comment by bakerboy448** [comment]
Tmdb link https://www.themoviedb.org/movie/130523-dr-jekyll-and-mr-hyde?language=en-US

it should already be using runtime as a factor

what was the size of the file?

there a hardcoded min of 70 megabytes

> subject.Release.Size < 70.Megabytes

https://github.com/Radarr/Radarr/blob/d4ce08a044d9c175c4b0f4a0a21c3db6bcf93c4c/src/NzbDrone.Core/DecisionEngine/Specifications/NotSampleSpecification.cs#L21

**Comment by tvanicraath** [comment]
Is the 70MB hardcoded limit enforced? My file size is 69.3MB :-| 

Here's the output of ffprobe:

```
ffprobe version 5.1.2-essentials_build-www.gyan.dev Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.1.0 (Rev2, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-sdl2 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libgme --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libtheora --enable-libvo-amrwbenc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-librubberband
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '.\Dr. Jekyll and Mr. Hyde (1912-01-16) (480p).mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp41isom
  Duration: 00:11:04.53, start: 0.000000, bitrate: 875 kb/s
  Stream #0:0[0x1](und): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p(progressive), 640x480, 2460 kb/s, 29.97 fps, 29.97 tbr, 29970 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
      encoder         : AVC Coding
  Stream #0:1[0x2](und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 6 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]

```
