### ISSUE TITLE
ping endpoint not working

### ISSUE THREAD

**Issue by modem7** [Radarr/Radarr#8043]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Going to http://myip:7878/ping results in a 401 error.

Recommending that this should be unauthenticated as it's an easy way to do a healthcheck.

This would also mimic the behaviour of the latest Sonarr API.

### Expected Behavior

```json
{
  "status": "OK"
}
```

### Environment

```markdown
- OS: Ubuntu
- Radarr: 4.3.2.6857
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Vivaldi
```

### What branch are you running?

Master

### Trace Logs?

NA

[AB#4813](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4813)

**Comment by Qstick** [comment]
Sonarr v4 changes this behavior

**Comment by modem7** [comment]
> Sonarr v4 changes this behavior

Is there any documentation for the v4 API currently?

**Comment by Qstick** [comment]
Yes, and it's authenticated in v4 as noted in the docs. Same behavior as Radarr.

![Screenshot_20230129-091432.png](https://user-images.githubusercontent.com/376117/215335960-9c61b287-ab0a-45fc-8a97-e252619d4ff5.png)

**Comment by modem7** [comment]
Good spot - hadn't noticed the icon/significance of. 

I've put in a feature request in the Sonarr repo for the same as this. 

https://github.com/Sonarr/Sonarr/issues/5396
