### ISSUE TITLE
aria2 connection issue

### ISSUE THREAD

**Issue by ww2283** [Radarr/Radarr#8045]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

<img width="879" alt="image" src="https://user-images.githubusercontent.com/21956104/215369027-21746441-341d-4047-bd0a-886b0d73676a.png">
I'm not sure what should be done to get radarr connect to the aria2. What am I doing wrong? The aria2 is running fine and can download any magnets on its own.

### Expected Behavior

I can connect to aria2c.com and https://ziahamza.github.io/webui-aria2/# without problem of downloading.

### Environment

```markdown
- OS: Ubuntu 20.04
- Radarr: latest docker
- Docker Install: yes
- Using Reverse Proxy: no
- Browser: chrome latest
- Database:
```

### What branch are you running?

Master

### Trace Logs?

2023-01-30 00:57:13.5|Warn|RadarrErrorPipeline|Invalid request Validation failed:
 -- Host: Unable to connect to Aria2

[AB#4817](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4817)

**Comment by bakerboy448** [comment]
- `latest docker` is not a radarr version.  See System => Status
- A single line error saying an error occurred are not the trace logs required for bug reports; the bug report template links to the wiki for how to get and provide trace logs
