### ISSUE TITLE
Add "dumb" HTTP fetch for recurring actions

### ISSUE THREAD

**Issue by kiler129** [Radarr/Radarr#8048]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

This is a FR. The simplest way to monitor recurring jobs is to use so-called deadman switch. In short the application is supposed to periodically access a URL to prevent the monitoring system from marking it as malfunctioning.

### Describe the solution you'd like

Radarr contains various periodic actions:

- Lists update
- Download clients queue update
- Update indexers RSS
- Various system tasks

The first 3 support various endpoints utilizing HTTP(S). However, since every single one of them contains subtypes which are verified upon save, it is not possible to add e.g. a fake indexer which is just a ping to a monitoring system. The simplest and probably quite easy solution would be to add a "Dummy HTTP" type to each one of them which simply requests a URL and returns nothing.

### Describe alternatives you've considered

An alternative to a deadman switch/push system is using a pull-based system. In such scenarios the monitoring system will connect to the application externally and verify if it's alive. However, this has a significant drawback: it usually requires the instance to be exposed to the internet. In some cases (e.g. https://github.com/Radarr/Radarr/issues/8043) it may even require authentication which is less than idea.

### Anything else?

Issue was also cross-posted to Sonarr: https://github.com/Sonarr/Sonarr/issues/5404

[AB#4822](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4822)

**Comment by bakerboy448** [comment]
> The simplest way to monitor recurring jobs is to use so-called deadman switch. In short the application is supposed to periodically access a URL to prevent the monitoring system from marking it as malfunctioning.

So effectively you want radarr to do a reverse ping to tell _something_ that is is up, running, and alive...?

the /ping endpoint is still usable, even with the current auth situation - it'd just be a 401 back instead of a 200.

> which are verified upon save, it is not possible to add e.g. a fake indexer which is just a ping to a monitoring system

Saving twice should allow it to force save and skip the validation checks.

**Comment by bakerboy448** [comment]
Like Markus said upstream; this is the intent of the ping endpoint
