### ISSUE TITLE
Release Year tag in folder name always set to 0

### ISSUE THREAD

**Issue by rigrassm** [Radarr/Radarr#806]
**Description:**
When a movie is added, the resulting folder that gets created always has 0 for the {Release Year}. The release year value appears to get set correctly for the actual movie file when it's imported. 

Movie Folder Format
` {Movie Title} ({Release Year})`

Example: Folder created for "Fences 2016"
`/movies/Fences (0)`

I had the option to create empty folders set but just turned this option off to see if it will make a difference. I'll update this issue once I have a new movie added.

**Radarr Version:**
Note: running application using the Linuxserver.io Docker image 
Version
0.2.0.299
Mono Version
4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4)

Host:
OS: Linux - Fedora 24
Kernel: 4.8.15-200.fc24.x86_64

**Logs:**
```
:30:11.6|Info|DownloadDecisionMaker|Processing 100 releases
17-2-19 14:30:16.4|Info|RssSyncService|RSS Sync Completed. Reports found: 100, Reports grabbed: 0
17-2-19 15:30:39.9|Info|RssSyncService|Starting RSS Sync
17-2-19 15:30:44.0|Info|DownloadDecisionMaker|Processing 100 releases
17-2-19 15:30:48.8|Info|RssSyncService|RSS Sync Completed. Reports found: 100, Reports grabbed: 0
17-2-19 16:11:51.7|Info|MovieService|Adding Movie [][Fences] Path: [/movies/Fences (0)]
17-2-19 16:11:53.9|Info|RefreshMovieService|Updating Info for Fences
17-2-19 16:11:56.0|Info|DiskScanService|Scanning disk for Fences
17-2-19 16:11:56.1|Info|MovieScannedHandler|[Fences] was recently added, performing post-add actions
17-2-19 16:11:56.1|Info|MediaCoverService|Downloading Poster for [tt2671706][Fences] http://image.tmdb.org/t/p/original/e3QX3tY0fBR1GuxdP0mwpN16cqI.jpg
17-2-19 16:11:56.7|Info|NzbSearchService|Searching 1 indexers for [Fences]
17-2-19 16:11:58.7|Info|MediaCoverService|Downloading Banner for [tt2671706][Fences] http://image.tmdb.org/t/p/original/jNlCIAcheh0iOuL3kz9x1Wq9WLG.jpg
17-2-19 16:12:03.8|Info|DownloadDecisionMaker|Processing 6 releases
17-2-19 16:12:03.9|Info|MovieSearchService|Movie search completed. 0 reports downloaded.
17-2-19 16:14:05.4|Fatal|NzbDroneErrorPipeline|Request Failed

[v0.2.0.299] System.InvalidOperationException: Sequence contains more than one matching element
  at System.Linq.Enumerable.SingleOrDefault[TSource] (IEnumerable`1 source, System.Func`2 predicate) <0x40fbd870 + 0x0018f> in <filename unknown>:0 
  at NzbDrone.Api.Frontend.StaticResourceModule.Index () [0x000a5] in C:\projects\radarr-usby1\src\NzbDrone.Api\Frontend\StaticResourceModule.cs:55 
  at NzbDrone.Api.Frontend.StaticResourceModule.<.ctor>b__3_0 (System.Object x) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Api\Frontend\StaticResourceModule.cs:25 
  at (wrapper dynamic-method) System.Object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)
  at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, CancellationToken context) <0x41183f90 + 0x0014f> in <filename unknown>:0 

17-2-19 16:14:31.4|Info|NzbSearchService|Searching 1 indexers for [Fences]
17-2-19 16:14:36.3|Info|DownloadDecisionMaker|Processing 6 releases
17-2-19 16:14:59.3|Info|Nzbget|Adding report [Fences.2016.DVDSCR.XviD.AC3-UnKnOwN] to the queue.
17-2-19 16:14:59.4|Info|DownloadService|Report sent to NZBGet. Fences.2016.DVDSCR.XviD.AC3-UnKnOwN
17-2-19 16:15:51.3|Info|NzbSearchService|Searching 1 indexers for [Fences]
17-2-19 16:15:58.3|Info|DownloadDecisionMaker|Processing 6 releases
17-2-19 16:16:05.3|Info|Nzbget|Adding report [Fences.2016.DVDScr.XVID.AC3.HQ.Hive-CM8-Obfuscated] to the queue.
17-2-19 16:16:07.0|Info|DownloadService|Report sent to NZBGet. Fences.2016.DVDScr.XVID.AC3.HQ.Hive-CM8-Obfuscated
17-2-19 16:16:12.8|Info|NzbSearchService|Searching 1 indexers for [Fences]
17-2-19 16:16:20.2|Info|DownloadDecisionMaker|Processing 6 releases
17-2-19 16:16:20.3|Info|MovieSearchService|Movie search completed. 0 reports downloaded.
17-2-19 16:17:19.9|Error|EventAggregator|MovieMissingModule failed while processing [MovieDownloadedEvent]

[v0.2.0.299] System.NullReferenceException: Object reference not set to an instance of an object
  at NzbDrone.Api.NzbDroneRestModuleWithSignalR`2[TResource,TModel].BroadcastResourceChange (ModelAction action, Int32 id) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Api\NzbDroneRestModuleWithSignalR.cs:38 
  at NzbDrone.Api.Wanted.MovieMissingModule.Handle (NzbDrone.Core.MediaFiles.Events.MovieDownloadedEvent message) [0x00000] in C:\projects\radarr-usby1\src\NzbDrone.Api\Wanted\MovieMissingModule.cs:74 
  at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent] (NzbDrone.Core.Messaging.Events.TEvent event) [0x000c3] in C:\projects\radarr-usby1\src\NzbDrone.Core\Messaging\Events\EventAggregator.cs:56 

17-2-19 16:18:21.4|Info|RefreshMovieService|Updating Info for Fences
17-2-19 16:18:22.0|Info|DiskScanService|Scanning disk for Fences
17-2-19 16:18:22.0|Info|DiskScanService|Completed scanning disk for Fences
17-2-19 16:30:50.4|Info|RssSyncService|Starting RSS Sync
17-2-19 16:30:55.0|Info|DownloadDecisionMaker|Processing 100 releases
17-2-19 16:30:59.9|Info|RssSyncService|RSS Sync Completed. Reports found: 100, Reports grabbed: 0
```

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by galli-leo** [comment]
How did you add these movies? Did you add them using the Radarr UI?

**Comment by rigrassm** [comment]
Well, I didn't even think twice about it but I did add them using Plexrequests-meteor. Being the person who added Radarr integration to it, I probably should have thought to check if it was behaving the same when adding through the UI lol.

I'll look into it tonight and if it turns out it's something with our API call I'll let you know here.

On that note, I'm assuming Radarr is just using the POST data sent to it via the API call from the client. If that's the case, since Radarr already does a lookup on the tmdb id, I think it would likely be better if Radarr uses the data it fetches rather than relying on the client provided data. Especially since that data is being used for things like the naming of folders which is something that's likely to have an affect on other services.

Y'all got a lot on your plate so I know this will likely be something that takes a back seat to more pressing issues, just wanted to throw the thought out there while it was on my mind lol.

Thanks for always the work y'all are putting into this project, I've been waiting for a viable replacement for CP for a while now. So much so I took the plunge the moment I got it added into Plexrequests lol.

I'll get back to you on the Release Year issue later this evening.

**Comment by galli-leo** [comment]
Ah thats the problem. You have to send the year in the post request when creating a movie. Because the folder name cannot be changed after the movie was created, we need the year then.

**Comment by rigrassm** [comment]
Plexrequests is sending it, I used the same implementation that we used for Sonarr and the  schema was derived from what's used by Radarr internally. Not saying that Plexrequests isn't sending the wrong data, but it is sending it.

Regarding the folder not being able to be changed, I'm not sure I follow why that's 1) an issue since you can change it manually from the Movie configuration and 2) why the folder has to be created before Radarr performs the metadata search?

 Even if the folder must be created at the time the movie is added, surely it can be renamed if it's found to not match what Radarr would expect it to be.

**Comment by galli-leo** [comment]
Well it currently can't be renamed from our code (actually we have working code that does allow that, we just need to make sure it does not break it) And the folder is only then created if you have enabled create empty movie directories in settings.

**Comment by rigrassm** [comment]
Oh OK, so that's something that is planning to be implemented, glad to hear
it.

As a client developer I want my application to behave properly and will fix
that if it's not, as a user of Radarr though I just want it to work
(everything should just work!) lol.

Thanks for the info and keep up the good work!
