### ISSUE TITLE
Allow Radar To Downgrade/Download and Move/"Upgrade" ANy File

### ISSUE THREAD

**Issue by sqlallstar** [Radarr/Radarr#8063]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

An option to allow Radarr to download any release and replace the existing release. (For example, sometimes for a particular bad movie, I may want to go from a 80GB 4k movie to a 20gb 1080P movie, especially if no lower bitrate 4K movies exist

### Describe alternatives you've considered

I tried reversing the cutoffs, didn't seem to work.  What I end up having to do, is manually go move and overwrite the file as Radarr will not import it.

### Anything else?

I can offer a small donation to the project, if this is something easily implemented.

[AB#4851](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4851)

**Comment by Qstick** [comment]
Just create a profile with the qualities in backward order and set the cutoff to the one you want. This will make Radarr consider the lower quality as an "upgrade" to the current. Assign this profile to movies you want downgraded.

**Comment by sqlallstar** [comment]
I’ve tried that it didn’t seem to work. I’ll check again. However, this will not work if the quality matches but for example one release is superior. 4Kx264 to 4kx265 (in my opinion)

**Comment by Qstick** [comment]
That's why custom formats exist, feel free to stop by discord if you want to discuss
