### ISSUE TITLE
Radarr to Downgrade Movies based off time

### ISSUE THREAD

**Issue by dd231344** [Radarr/Radarr#8068]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

So this idea of being able to choose a downgrade of "Quality" base on how long the said "Movie or Object" has been on the server. I have noticed that there is a "Upgrade Until Quality" option but what if we wanted the option to downgrade the quality after a certain time span. Due to the fact that there isn't really a reason to keep movies at least in my opinion in 4k or 8k because no one watches the same movie everyday this can help save library space.

![image](https://user-images.githubusercontent.com/124531983/216846141-ec39d1bd-6f37-40f5-ac9d-95c15ae98b3c.png)

### Describe alternatives you've considered

I don't have any alternatives

### Anything else?

I have ask a moderator on discord if there is a way to automate this or if its possible and i have been told no

**Comment by Qstick** [comment]
No plans for something like this right now, but you could script it fairly easily if you wanted to 

- Create a downgrade profile in Radarr
- Pull Movies from API
- Filter to Movies without downgrade profile
- Look at Date
- Set profile to downgrade profile if earlier than a certain date
- Trigger search

Upgradinatorr is a good start, as it already essentially does this in reverse. 
https://github.com/angrycuban13/Just-A-Bunch-Of-Starr-Scripts
