### ISSUE TITLE
/api/v3/movie/lookup endpoint incorrectly handles movie titles that are two words followed by a year

### ISSUE THREAD

**Issue by khumps** [Radarr/Radarr#8083]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

`/api/v3/movie/lookup?term=Blade`
returns:
```
[
    {
        "title": "Blade Runner 2049",
        "originalTitle": "Blade Runner 2049",
        "originalLanguage": {
            "id": 1,
            "name": "English"
        },
...
]
```

`/api/v3/movie/lookup?term=Blade+Runner`
returns:
```
[
    {
        "title": "Blade Runner 2049",
        "originalTitle": "Blade Runner 2049",
        "originalLanguage": {
            "id": 1,
            "name": "English"
        },
...
]
```
`/api/v3/movie/lookup?term=Blade+Runner+2049`
returns:
`[]`

Replicating this through the add movie UI, it can't find the movie as well (it uses the same lookup endpoint):
![image](https://user-images.githubusercontent.com/7849025/217436168-83466513-ff3f-4e00-b1b3-30e52758f953.png)
![image](https://user-images.githubusercontent.com/7849025/217436276-047157fd-fe08-40a3-8a4a-9570b1d522b7.png)

### Expected Behavior

`/api/v3/movie/lookup?term=Blade+Runner+2049` should return the first result being
```
[
    {
        "title": "Blade Runner 2049",
        "originalTitle": "Blade Runner 2049",
        "originalLanguage": {
            "id": 1,
            "name": "English"
        },
...
```

### Steps To Reproduce

1. Launch postman
2. Import openapi spec
3. Run query `{{baseUrl}}/api/v3/movie/lookup?term=Blade+Runner+2049` with authentication

### Environment

```markdown
- OS: Ubuntu 20.04
- Radarr: 4.3.2.6857
- Docker Install: Yes (Kubernetes)
- Using Reverse Proxy: Yes, behind nginx ingress controller. Verified query was being passed correctly `"GET /api/v3/movie/lookup?term=Blade+Runner+2049 HTTP/1.1" 200 16 "-" "PostmanRuntime/7.30.0" 350 0.120` [radarr-7878] [] 10.1.14.169:7878 21 0.120 200 33bbc59110204521bdb641c404e5e91`
- Browser: Postman
- Database: Sqlite
```

### What branch are you running?

Master

### Trace Logs?

Relevant section from trace:
```
2023-02-08 04:29:34.3|Trace|Http|Req: 220598 [GET] /api/v3/movie/lookup?term=Blade+Runner+2049 (from 192.168.2.95 PostmanRuntime/7.30.0)
2023-02-08 04:29:34.3|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-02-08 04:29:34.3|Debug|Parser|Parsing string 'Blade Runner 2049'
2023-02-08 04:29:34.3|Trace|Parser|^(?<title>(?![(\[]).+?)?(?:(?:[-_\W](?<![)\[!]))*(?<year>(1(8|9)|20)\d{2}(?!p|i|(1(8|9)|20)\d{2}|\]|\W(1(8|9)|20)\d{2})))+(\W+|_|$)(?!\\)
2023-02-08 04:29:34.3|Debug|Parser|Movie Parsed. Blade Runner - 2049 
2023-02-08 04:29:34.3|Debug|Parser|Release Group parsed: 
2023-02-08 04:29:34.3|Debug|Parser|Languages parsed: Unknown
```

It appears the regex for this endpoint expect a one or two word movie title followed by the movie year. 

[AB#4882](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4882)

**Comment by khumps** [comment]
Playing around with the regex, it appears the capture groups do correctly handle the title if I instead query for `Blade Runner 2049 2017` (movie released in 2017). It seems there are related issues to this regex like #6843. For what I am doing I do have the movie year available to me so I can work around it, but it seems like odd behavior to expect the movie title in this form in the search bar without showing it in a tooltip.

**Comment by Qstick** [comment]
This should be fixed upstream with more robust metadata search handling
