### ISSUE TITLE
Radarr Marks Incorrect Torrent As Failed

### ISSUE THREAD

**Issue by manuth** [Radarr/Radarr#8086]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I'm trying to download two different torrents (with an identical `DownloadId`, as it looks) from two different indexers.
When trying to mark both torrents as failed, Radarr will instead Block the first torrent two times:
![image](https://user-images.githubusercontent.com/7085564/217673016-e32ea0df-def3-46c9-b4c9-ee6de3e919c4.png)

```sh
1. `QxR`   # Me trying to download the 1st torrent
2. `QxR`   # Me marking the 1st torrent as failed
3. `[QxR]` # Radarr automatically starting the 2nd torrent
4. `QxR`   # Me flagging `[QxR]` as failed - however, the newly created entry states `QxR` instead of `[QxR]`
5. `[QxR]` # Radarr, once more starting the `[QxR]` torrent despite the fact that I tried to mark it as failed
```

I even went as far as to edit the `SourceTitle` and the `Indexer` field in the `Blocklist` table as well as the `SourceTitle` in the `History` table manually. However, the `History` section on Radarr still looks the same (the `Source Title` is incorrect despite the fact that I edited it on my own). 

### Expected Behavior

Radarr should ignore both torrents and show the correct `Source Title` in the corresponding movie's overview.

### Steps To Reproduce

Sadly, I can't pinpoint the issue, so there is no way to reproduce it.
If necessary, I could send the links to the torrents I was trying to download via DM/Mail etc.

### Environment

```markdown
- OS: Docker on Ubuntu Server 22.04
- Radarr: Radarr 4.3.2.6857-ls160
- Docker Install: Yes
- Using Reverse Proxy: Yes (nginx)
- Browser: Brave (Chromium Browser)
- Database: SQLite
```

### What branch are you running?

Master

### Trace Logs?

These logs start at the point where the 1st torrent is queued already.
The log shows following events:
  - `QxR` is marked as failing manually
  - `QxR` is removed from the queue manually
  - `[QxR]` is queued by Radarr automatically
  - `[QxR]` is marked as failing manually
    - A duplicate entry for `QxR` is created by Radarr instead
  - `[QxR]` is removed from the queue manually
  - `[QxR]` is queued by Radarr automatically again despite the fact that I tried to flag it as failing.

[radarr.trace.txt](https://github.com/Radarr/Radarr/files/10691322/radarr.trace.txt)
[radarr.txt](https://github.com/Radarr/Radarr/files/10691323/radarr.txt)
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/10691324/radarr.debug.txt)

[AB#4886](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/4886)

**Comment by bakerboy448** [comment]
Blocklisting looks like it is done by torrenthash if it exists. They're both blocked because it is the exact same torrent and thus the same hash across indexers; so indexer is not a factor like it would be by title

with that said this is probably something worth rethinking, but a discussion for upstream first

Reject logic

https://github.com/Radarr/Radarr/blob/0697dbff96a7437d2aac933f9e3121838b0417e7/src/NzbDrone.Core/DecisionEngine/Specifications/BlocklistSpecification.cs#L24-L30

https://github.com/Radarr/Radarr/blob/0697dbff96a7437d2aac933f9e3121838b0417e7/src/NzbDrone.Core/Blocklisting/BlocklistService.cs#L38-L64

https://github.com/Radarr/Radarr/blob/0697dbff96a7437d2aac933f9e3121838b0417e7/src/NzbDrone.Core/Blocklisting/BlocklistService.cs#L127-L134

**Comment by manuth** [comment]
Now that's strange 🥲
Based on this method, the 2nd torrent shouldn't be queued automatically but rather blocked.
However, Radarr keeps putting it (and many other torrents with the same `DownloadId`) in the queue.

Should I go try to use the unstable build of Radarr?

**Comment by bakerboy448** [comment]
No there's been other reports of this kind of funky behavior with blocklisting and public trackers but no one really ever opened an issue for it.

**Comment by manuth** [comment]
Thank you so much for answering so rapidly 😄 
Wasn't sure whether or not I've searched the existing issues thoroughly enough, tbh

**Comment by joaoptc** [comment]
Please check the issue I opened #8354 all logs attached.
It is blocklisting with the wrong indexer.
That might be the problem ....

**Comment by bakerboy448** [comment]
https://github.com/Radarr/Radarr/issues/8369
