### ISSUE TITLE
Movies with *.iso extension not recognized

### ISSUE THREAD

**Issue by terrelsa13** [Radarr/Radarr#809]
**Movies that have an extension of *.iso show as missing.***
![butshownasmissing](https://cloud.githubusercontent.com/assets/16886488/23104822/9bd5897c-f69a-11e6-8be7-dfcc12374eb3.png)

**You can see it is in the correct location.**
![correctlocation](https://cloud.githubusercontent.com/assets/16886488/23104980/8a7e9d5a-f69d-11e6-97e3-88f4ef50a4ff.png)

Seems like Radarr is not able to show the movie is "Downloaded" when it has an *.iso extension.

Shouldn't *.iso's be recognized?

Radarr Version: Radarr Ver. 0.2.0.299 develop

Log output after "Updating Movie Info And Scanning Disk":
> 17-2-19 11:33:41.2|Info|RefreshMovieService|Updating Info for Phantom
17-2-19 11:33:41.5|Info|DiskScanService|Scanning disk for Phantom
17-2-19 11:33:41.5|Error|DetectSample|[/media/Pharaoh/xbmc/Movies/Phantom.2013/Phantom.2013.BR-Disk.DTS.2.0.iso] has a runtime of 0, is it a valid video file?
17-2-19 11:33:41.5|Info|DiskScanService|Completed scanning disk for Phantom

All of the *.iso movies in my library show 'missing' as well. Good news is, they are all recognized and playable from the client side.

Let me know if I need to provide additional information for this.

#781 is the only previously reported issue I could find that could have been related to this one.
Correction: #764 seems to have a similar log output. May be related, but not an *.iso in this case.

**Comment by galli-leo** [comment]
Well this is because we don't support movie formats other than simple files yet. (mkv, mp4, etc.) Iso's and whole bluray movie folders will come later down the line.

**Comment by galli-leo** [comment]
I have marked your issue therefore as a feature request.

**Comment by schumi2004** [comment]
Previous issues about this were closed because of the unsupported argument. I would like to seem them recognized as unknown (or something similar) though, that way users at least know a file is there but not recognized by Radarr. I would limit this to iso and video_ts only I think.

**Comment by terrelsa13** [comment]
That explains it.
Known issue to be addressed in the future.

**Comment by Hubszo** [comment]
Handling of ISO files as well as entire disk structure (DVD or Blu-ray) is really necessary. High quality blu-ray releases in particular are mostly ISO or full disk shares.
Currently not only movie is marked as missing but movie files are not moved to the destination folder (although folder has been created).

**Comment by alexkoch89** [comment]
I have the same issue, .iso are not moved to the destination folder. I hope this will be fixed soon!

Thank you for this great job

**Comment by talentedmrripley** [comment]
I too would really like to see this implemented.  Everyone that does too should go vote for it - https://feathub.com/Radarr/Radarr/+120

**Comment by rubdos** [comment]
Is this an issue that I can tackle/contribute? I assume some directory structure parsing would be needed (of the ISO, or the m2ts extract), and classify it that way?

**Comment by triksmelb** [comment]
Just wanted to add my support for ISO movie file format support in Radarr. 

Those of us watching 3D BD iso on devices like the Minix the only way to get 3D to work correctly with various hardware is to keep the file structure as ISO. BD structure is usually predictable :\BDMV\STREAM\ and video containers as M2TS Video File (.m2ts).

As a point of reference [Media Center Master](http://mediacentermaster.com/) works in a similar way to Radarr but has the ability to scan ISO files without issue. 

Hopefully developers will be able to see the importance of this feature.

**Comment by TRaSH-** [comment]
> I too would really like to see this implemented. Everyone that does too should go vote for it - https://feathub.com/Radarr/Radarr/+120

Upvoted it,
ISO's are more and more a standard for full blurays and 4K (for years now),
but it seems most people are more of "as long as i've seen it in any quality it's okay with me (welcome back to the 90's with .rm video files)"
Personally i don't see why it's so hard to support iso files (i understand that bluray folder structure is a issue because of multiple files).

**Comment by Ltek** [comment]
> 
> 
> > I too would really like to see this implemented. Everyone that does too should go vote for it - https://feathub.com/Radarr/Radarr/+120
> 
> Upvoted it,
> ISO's are more and more a standard for full blurays and 4K (for years now),
> but it seems most people are more of "as long as i've seen it in any quality it's okay with me (welcome back to the 90's with .rm video files)"
> Personally i don't see why it's so hard to support iso files (i understand that bluray folder structure is a issue because of multiple files).

Ditto... Support for ISO and Blueray rips (BDMV folder) should be easy enough and these are the norm for those that want full res rips.

**Comment by Exist2Resist** [comment]
I guess a year later and this is still not implemented. Now I know why I must put off moving to Radarr from CouchPotato.

Hopefully this will be implemented soon.

**Comment by Ltek** [comment]
It is Odd the goal was t be better that CP but they dont support formats that have been standard for two decades (ISO). Sad they also don't read the file specs like CP does.  I have used Radarr exclusively for several months now and I've had more issues with it that I ever did with CP... and CP still supports more stuff.  I may need to switch back to CP. I guess its hard to beat a classic!

**Comment by Qstick** [comment]
Guys feel free to submit a PR or comment with something productive, otherwise the useless comments are not helping anyone get motivated to add this.

**Comment by Qstick** [comment]
This may be working in Aphrodite, per @fryfrog files are getting picked up now due to the changes in sample detection

**Comment by PawelTroka** [comment]
@Qstick are you saying that Radarr is now able to handle BDMV releases? AFAIK this is not the case, at least not in current `Aphrodite`.

**Comment by fryfrog** [comment]
A `BDVM` folder is *not* a `.iso`.

**Comment by PawelTroka** [comment]
> A `BDVM` folder is _not_ a `.iso`.

Well, I know... However, everyone is referring to this issue (#809) when talking about BDMV as well.
See for example here: https://github.com/Radarr/Radarr/issues/717

**Comment by Qstick** [comment]
Should likely be seperate issues

**Comment by Ltek** [comment]
@galli-leo   why are ISOs still not supported?  The standard was ratified in the late 80s and is still in WIDE use?

**Comment by OuticNZ** [comment]
My approach to handling these is to pre-process into a supported format before presenting to Radarr.  

Download Client ->  Completed Folder -> Tdarr (packing/transcoding/moving) -> Completed Folder Final

ISO -> MKV (HEVC)     _working_
BDMV -> ISO -> MKV(HEVC)      _inprogress_

**Comment by rubdos** [comment]
> My approach to handling these is to pre-process into a supported format before presenting to Radarr.
> 
> Download Client -> Completed Folder -> Tdarr (packing/transcoding/moving) -> Completed Folder Final
> 
> ISO -> MKV (HEVC) _working_
> BDMV -> ISO -> MKV(HEVC) _inprogress_

That's not what this issue is about. This issue is about Radarr being able to handle .iso's, because our media players can handle them.

**Comment by fryfrog** [comment]
Sonarr/Radarr handling `.iso` files or DVD/Bluray folders is *very* unlikely. @OuticNZ's reply is probably the only way you'll ever get this to "work". They just not a common way for movies or shows to be distributed and very little tooling that Sonarr/Radarr utilize work w/ them.

**Comment by rubdos** [comment]
> Sonarr/Radarr handling `.iso` files or DVD/Bluray folders is _very_ unlikely. @OuticNZ's reply is probably the only way you'll ever get this to "work".

His reply does not make this work. Transcoding/extracting to .mkv can be done through `makemkv` and other tools too. If it wouldn't be possible, this issue would have been closed for long.

> They just not a common way for movies or shows to be distributed and very little tooling that Sonarr/Radarr utilize work w/ them.

This is very common on private trackers. Ten seconds of Googling found me [this .NET Core library](https://github.com/DiscUtils/DiscUtils) that seems maintained and able to dissect many different disc formats.

**Comment by fryfrog** [comment]
Super, Radarr loves development help. You have plenty of time to learn .NET and code this up before anyone else does. Hop on Discord and work w/ the developers to do it in a way that is acceptable and can get merged in. Dip your toes in working on / fixing some easy stuff maybe. :)

**Comment by rubdos** [comment]
I've been planning to do that ([see e.g. my previous comment](https://github.com/Radarr/Radarr/issues/809#issuecomment-349566278)) for three years now, but I have to admit, my ... dislike for .NET and Discord has been holding me back quite a bit :-)

Anyhow, let's cut the noise, and I'll be back when I'm more annoyed with ISO's than I am with .NET :D

**Comment by MadsMighty** [comment]
If you support pulling down releases that are labelled BD-DISC I really don't understand why the client can't understand them at all. The amount of downloads I have where I have to go manually check and move because of this makes Radarr feel like more of a chore than downloading things myself manually.

**Comment by fryfrog** [comment]
If they're labeled `BD-DISC` and you *don't* want them, add that to your must not contain. If you *do* want full disks, I wouldn't use Radarr for this. I don't actually recall, but maybe CouchPotato will happily handle full disks and `.iso` files?

**Comment by MadsMighty** [comment]
> If they're labeled `BD-DISC` and you _don't_ want them, add that to your must not contain. If you _do_ want full disks, I wouldn't use Radarr for this. I don't actually recall, but maybe CouchPotato will happily handle full disks and `.iso` files?

I'll take a look at that, I'm just honestly surprised that a platform like Radarr would choose to support a download type, then explicitly not support the actual file itself within Radarr. Seems like an incongruity people have wanted fixed for 3 years and I'm exactly sure what prevents it.

**Comment by dkrahmer** [comment]
I added support for DVD/BR files (iso, img, vob, m2ts) and VIDEO_TS directories in my fork of Radarr (v0.2.0.1480). My change seems to work well so far when scanning existing movies. I will upload a release to my repo and submit a PR after I run a few more tests. 

These are the relevant commits so far:
https://github.com/dkrahmer/Radarr/commit/15c993c21b94c8d008c228f3db63c3090cbf99a0
https://github.com/dkrahmer/Radarr/commit/679bb68fc4af7f54d44d1f88794cef443dfb838a

**Comment by ta264** [comment]
Thanks, PRs always appreciated. But please note that we're only accepting PRs against aphrodite (V3), not develop (v0.2)

**Comment by Qstick** [comment]
Fixed by #4531
