### ISSUE TITLE
Radarr Synology Docker not Importing movies from disk

### ISSUE THREAD

**Issue by monsieurlatte** [Radarr/Radarr#810]
So I have 2413 running dsm 6, using a docker image from linuxserver tree.  It all is working however it wont find any movies that are on my NAS.  In the docker config I set the PUID and PGID to be admin (tried 2 other users too but no difference).  

The way I have my movies is  like so, I have a folder/share called Movies.  In there I have folders for 4K Movies, HD Movies 1, HD movies 2, HD Movies 3, HD Movies 4, JR Movies(scary movies).  I do this because it's how I back them up, I create a folder and then rip movies into them until the corresponding backup drive is full and then I create a new movies folder.  In those folders I have tons of movies all labeled with Moviename (year).ext (mostly mkv).  

When I point radarr to the root of Movies it tries to find movies name 4K Movies, HD Movies 1 etc.  Which doesnt work of course.  If I tell it to look inside those folders it never detects any movies in there.  

Any ideas?

PS I am a plex ninja so if you're in the plex slack team and have more questions feel free to ping me in there, same username as here.

**Comment by galli-leo** [comment]
Currently each movie file needs to be in a folder called Movie Name (Year).

**Comment by monsieurlatte** [comment]
Thanks for the heads up, so in that aspect it's just like sonarr, bummer.  I am not going to change my structure for this, maybe down the road it will support it.  Thanks.

**Comment by galli-leo** [comment]
The plan is definitely to support that structure down the road. It will just require to rewrite a lot of stuff.
