### ISSUE TITLE
Lists: Radarr Tags are not applied to movie if it's not directly in list, but added via Collection relation

### ISSUE THREAD

**Issue by mantas3** [Radarr/Radarr#8124]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I am importing IMDB TOP 250 movies and collections.
I have tag set for this list.
Movie 1 and Movie 2 are in this list as movies. Movie 3 is imported via collection.
Both Movie 1 and 2 has tag, but Movie 3 is not.
![image](https://user-images.githubusercontent.com/808053/219086653-e54a1e4b-deb8-421d-9c67-43887a756abb.png)
![image](https://user-images.githubusercontent.com/808053/219087094-9669b643-1189-4d60-a508-e1b6dae06f2a.png)

### Expected Behavior

Tags should be added to related movies even if they are not directly in list.

### Steps To Reproduce

1. Setup list to import both movies and collections
2. Add radarr tag to that list
3. Click save.

### Environment

```markdown
- OS: Unraid OS
- Radarr: 4.3.2.6857
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: -
- Database: Sqlite 3.40.1
```

### What branch are you running?

Master

### Trace Logs?

-

**Comment by austinwbest** [comment]
This has been discussed before and I still disagree with it. The movie was not added by a list and just because a list happens to contain it doesn't mean it should be tagged.

**Comment by mantas3** [comment]
> This has been discussed before and I still disagree with it. The movie was not added by a list and just because a list happens to contain it doesn't mean it should be tagged.

but isn't the whole point of these tags to know which list movie came from?

**Comment by bakerboy448** [comment]
Not a bug as nit said;

Existing feature request covers this https://github.com/Radarr/Radarr/issues/2529

**Comment by RobinDadswell** [comment]
> > This has been discussed before and I still disagree with it. The movie was not added by a list and just because a list happens to contain it doesn't mean it should be tagged.
> 
> but isn't the whole point of these tags to know which list movie came from?

Yes - but not when it wasn't added by the list initially as it didn't come from the list

**Comment by austinwbest** [comment]
You're basically wanting list contains VS list added.

It skews the purpose of knowing how it was added and opens up people wanting to modify existing items to add tags or they will then say it's a bug because this list has it but the movie doesn't. Then it has to remove tags as it is removed from lists. Becomes a sink hole and isn't the purpose is why I disagree with it personally.
