### ISSUE TITLE
Blackhole not respecting Release date on import/grab

### ISSUE THREAD

**Issue by sflix** [Radarr/Radarr#8125]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Movie is set to Minimum Availability: Released
File on Blackhole folder is grabbed even if movie has not been released.

I don't have any movie that has an early release date at the moment, so am attaching an example with a strm file. 
John Wick Chapter 4 is set to be released on 22/03/2022

### Expected Behavior

Movie should not be grabbed/imported until digital o physical released web.
Ideally it should differentiate between digital and physical  releases so that it correspondes with the desired qualities in the profiles.

### Environment

```markdown
- OS: DMS
- Radarr: 4.3.2.6857   4.3.2.6857-ls159 by linuxserver.io
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Brave
```

### What branch are you running?

Master

### Trace Logs?

-------------------------------------------------------------------------------------------------------------

2023-02-16 10:29:57.5|Error|VideoFileInfoReader|Unable to parse media info from file: /download/John Wick Chapter 4 (2023).strm

[v4.3.2.6857] FFMpegCore.Exceptions.FFMpegException: ffprobe exited with non-zero exit-code (1 - /download/John Wick Chapter 4 (2023).strm: Invalid data found when processing input)
   at FFMpegCore.FFProbe.GetStreamJson(String filePath, Int32 outputCapacity, FFOptions ffOptions)
   at NzbDrone.Core.MediaFiles.MediaInfo.VideoFileInfoReader.GetMediaInfo(String filename) in D:\a\1\s\src\NzbDrone.Core\MediaFiles\MediaInfo\VideoFileInfoReader.cs:line 62

2023-02-16 10:29:57.7|Info|MovieService|Assigning file [John Wick Chapter 4 (2023).strm] to movie [[John Wick: Chapter 4 (2023)][tt10366206, 603692]]

**Comment by bakerboy448** [comment]
- the provided logs do not show radarr grabbing a release and sending it to the blackhole nor are they the trace logs that bug reports require and the bug report template links to
- believe Minimum Availability - like monitored status - only impacts Grabs; not Imports. So this would be expected behavior

**Comment by sflix** [comment]
Sorry I'm not used to tinker in logs, I attach file with trace log. If this is not it please let me know who to get them.
In relation to the Grab/Import, I didn't know which word to use as this is not my main language.  I suppose is grab when the file is on the blackhole (download folder) and the is moved to root folder.



[log.txt](https://github.com/Radarr/Radarr/files/10756457/log.txt)

**Comment by bakerboy448** [comment]
- logs do not show any grab only an import
- Grabs are when the release is pulled from the indexer and sent to the client
- Imports are imports


There does not appear to be a bug and radarr is not grabbing a release as you initially described based on your trace logs and most recent  comment

**Comment by sflix** [comment]
sorry to messed up the terms.
Could it be possible to add a rule to respect the release date on blackhole import?

**Comment by bakerboy448** [comment]
That would be a feature request to open and have triaged.

tho that would then open the larger can of worms (and this specifically would be upstream to sonarr too) - should importing respect monitored status

**Comment by sflix** [comment]
ok thank you.
