### ISSUE TITLE
Message displayed after no new movies have been found on RSS list is not helpful

### ISSUE THREAD

**Issue by nsgundy** [Radarr/Radarr#813]
**Description:**
When trying to add movies from the RSS list `http://rss.imdb.com/list/ls062928724/` (via `Movies` > `Add Movie` > `Add Movies From Lists`), Radarr shows `Sorry. We Couldn't Find Any Movies Matching ''`. The list has a single movie (`War Dogs (2016)`) in it and the movie had previously been added, so there aren't any new movies to add from that list. The displayed message should reflect that as it currently reads more like an error message.

**Radarr Version:**
0.2.0.299 (Windows)

**Comment by nsgundy** [comment]
Apologies, the issue seems to be that that movie had already been imported. So I am changing the title and description to reflect that the message wasn't very helpful / misleading.

**Comment by davidn1984** [comment]
I also get the `Sorry. We Couldn't Find Any Movies Matching ''` message, however it is not adding movies, and yes there are movies in the list which aren't in Radarr.

**Comment by Stephonomon** [comment]
Has this been changed? It should either tell you it imported all of them, or if there is another error.
