### ISSUE TITLE
Rich file name tokens, e.g. "Movie Title [2019] [189min] [★7] [co,dr]"

### ISSUE THREAD

**Issue by davidcm** [Radarr/Radarr#8131]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

There's too little info about the movies when listed in a file explorer or DLNA client.

### Describe the solution you'd like

Previously I used Watcher, and with it I was able to make a postprocess plugin with which I renamed the movie folder with my own tags like duration, users rating and genre hints, retrieved from OMDB api. For example a movie folder would look like "Movie Title [2019] [189min] [★7] [co,dr]".
I found it very helpful to have all the relevant info I need when looking for what movie to watch.
Genre hints is normally enough showing maximum 3 and limiting each of them to 2 characters (at least in english).

### Describe alternatives you've considered

The most versatile solution would be to have a postprocess plugin system like Watcher has (which, if I'm not wrong, I think Radarr hasn't), but if the infrastructure needed for that is too much, simply adding the new tokens I mention above (plus others that could be interesting) to the current list, would be nice.

### Anything else?

I think Radarr already has a lot of info retrieved from the movie in question. Using it for a richer renaming would be a nice and smart feature.

**Comment by bakerboy448** [comment]
No plans for now; maybe one day
