### ISSUE TITLE
radarr sending low quality to downloader instead the better quality

### ISSUE THREAD

**Issue by aniel300** [Radarr/Radarr#8133]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

radarr is sending low quality to downloader instead of the better quality one however it does send the correct one if i do a manual automatic search. 

### Expected Behavior

Automatically add the best avalible quality new releases to the downloader 

### Steps To Reproduce

only happens when rss is in action so N/A for how to reproduce.  

### Environment

```markdown
- OS: Ubuntu 22.04.1 LTS
- Radarr: 4.4.2.6956-ls85 by linuxserver.io
- Docker Install: yes
- Using Reverse Proxy: no
- Browser: crhome
- Database: Sqlite 3.40.1
```

### What branch are you running?

Develop

### Trace Logs?

Here are some screenshots and logs: 

![chrome_onl4kGiUpR](https://user-images.githubusercontent.com/7571729/219934768-35155e35-9ffe-44d3-9438-49b257741dc8.png)
![chrome_YFYbovfy1x](https://user-images.githubusercontent.com/7571729/219934771-d54f5846-5ca8-466b-a256-374bdecf0204.png)
![chrome_L0aGhbpQFL](https://user-images.githubusercontent.com/7571729/219934775-2e8a6a52-e519-4930-a130-23c98fd7d08a.png)
![chrome_h1m8MVZEK3](https://user-images.githubusercontent.com/7571729/219934779-90eba8c9-8a5b-451f-b282-ef6802785bdd.png)
![sly6Og8O6P](https://user-images.githubusercontent.com/7571729/219934787-886c7d8e-f2dc-4522-a519-c22d1a6c8b29.png)

[radarr.trace.txt](https://github.com/Radarr/Radarr/files/10776346/radarr.trace.txt)

**Comment by bakerboy448** [comment]
Please use one of the support channels: [Reddit](https://www.reddit.com/r/radarr/) or  [Discord](https://radarr.video/discord) for support/questions.

see the first FAQ entry and the how downloads are compared entry
