### ISSUE TITLE
Radarr - Port in use (check nzbdrone)

### ISSUE THREAD

**Issue by henrikrox** [Radarr/Radarr#814]
**Description:**

I have sonarr installed as service at least i think so, when i start radarr i get a message saying port is in use and i need to check nzbdrone (ifi ts already been started). I have to manually use

ServiceUninstall.exe

then

ServiceInstall.exe

Each time my computer restarts, which is a hassle. Is there a way to fix this? without restarting my config file from radarr?

**Radarr Version:**
Cant check, cant login.

**Logs:**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by galli-leo** [comment]
Did you try and start it manually? Because if you installed the service, you do not need to run it manually. It will auto start. Radarr will not interfere with Sonarr.

**Comment by Unthred** [comment]
There definitely seems to be a port issue, I have Radarr installed on my Synology NAS and I cannot install Sonarr as there is a port conflict

**Comment by galli-leo** [comment]
@Unthred Well that can only happen if you set the ports of Radarr to be that of Sonarr.

**Comment by Unthred** [comment]
I have not changed the default ports its set to 7878 and 9898 if I use SSL. Could it be a synology package problem instead of Radarr?

**Comment by galli-leo** [comment]
Maybe because you are using ssl? I don't think I changed the ssl port. Try changing that one.

**Comment by onedr0p** [comment]
If you're still having problems please go on discord, there's lots of people who can help that might have a similar set up as you.

**Comment by Foozor** [comment]
Having the exact same issue, suspect that having Sonarr and Radarr both using NzbDrone is the main issue. Any fix?

**Comment by rogerizo** [comment]
I had this issue but managed to open it via open as administrator
