### ISSUE TITLE
[Error] LocalizationService: Missing translation/culture resource: /app/radarr/bin/Localization/Core/fr_FR.json

### ISSUE THREAD

**Issue by dexter74** [Radarr/Radarr#8150]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Hello,

After configuration Radarr, i take the error.

### Expected Behavior

None error.

### Steps To Reproduce

1. Create Docker
2. Configure Radarr
3. Use Radarr
4. Look Logs with Dozzle

### Environment

```markdown
- OS                  : ASUSTOR
- Radarr              : 4.3.2.6857
- Docker Install      : Yes
- Using Reverse Proxy : Local
- Browser             : Microsoft Edge
- Database            : Sqlite 3.40.1

```

### What branch are you running?

Master

### Trace Logs?
```
[Error] LocalizationService: Missing translation/culture resource: /app/radarr/bin/Localization/Core/fr_FR.json
```

**Comment by derSumo** [comment]
same Problem "Missing translation/culture resource: /app/radarr/bin/Localization/Core/de_DE.json"

**Comment by bakerboy448** [comment]
> same Problem "Missing translation/culture resource: /app/radarr/bin/Localization/Core/de_DE.json"

trace logs and radarr version required

**Comment by Al4ndil** [comment]
Hi,
I have the same error on Sonarr Version 4.0.0.748.
Can you help me for that ?

**Comment by bakerboy448** [comment]
Please use one of the Sonarr support channels: [forums](https://forums.sonarr.tv/), [discord ](https://discord.gg/Ex7FmFK), or [IRC ](https://web.libera.chat/?channels=#sonarr) for Sonarr support/questions.
