### ISSUE TITLE
Browser based search doesn't work properly in new UI

### ISSUE THREAD

**Issue by alzeebum** [Radarr/Radarr#8159]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

A browser based page search (CTRL-F) doesn't find content in the page that is scrolled out of view.

### Expected Behavior

Browser based search should find all content on the current page, scrolling it into view, as it does on other web pages using other UI frameworks.

### Steps To Reproduce

1. Open any RADARR page, such as the main movie list.
2. Press CTRL-F in an up to date Firefox or Chrome browser.
3. Type a word you know exists further down the page.
4. Note that the browser says the search has failed.

### Environment

```markdown
- OS: Any
- Radarr: 4.2.4.6635
- Docker Install: n/a
- Using Reverse Proxy: n/a
- Browser: All
- Database:
```

### What branch are you running?

Master

### Trace Logs?

n/a

**Comment by bakerboy448** [comment]
The table is loaded dynamically and it's not expected for control f to find what is not currently loaded in view
