### ISSUE TITLE
Radarr gives a blank white page on IPAd

### ISSUE THREAD

**Issue by pbranly** [Radarr/Radarr#8160]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

As described in title 

### Expected Behavior

Access to radarr

### Environment

```markdown
- OS: synology dsm7
- Radarr: latest
- Docker Install: 
- Using Reverse Proxy: 
- Browser: safari
- Database:
```

### What branch are you running?

Master

### Trace Logs?

None

**Comment by bakerboy448** [comment]
for future reference `latest` is not a version

most likely this is caused by an improperly configured reverse proxy or simply just needs a reinstall of radarr

**Comment by pbranly** [comment]
According to docker latest should be the 4.3.2

**Comment by pbranly** [comment]
I can try and reinstall but it is working from my windows pc. It seems linked with IOS. 
I use it in local. So no proxy
