### ISSUE TITLE
[Bug] Radarr not adding Freeleech indexer flag to custom format score on search

### ISSUE THREAD

**Issue by RyanAStrouse** [Radarr/Radarr#8165]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Custom indexer score is not generating correctly when searching indexer items that have a freeleech flag. However, if downloaded manually the history shows the "FreeLeech" custom format tag and correct score.

![image](https://user-images.githubusercontent.com/4588529/221931122-29020ff0-2005-46a8-9f80-56b46c9eecaf.png)

![image](https://user-images.githubusercontent.com/4588529/221930997-4a5ea9bb-79ed-4978-8012-da00b7c09301.png)

![image](https://user-images.githubusercontent.com/4588529/221931362-2539b80b-63ec-44a0-99e6-46b95fa4d13b.png)

![image](https://user-images.githubusercontent.com/4588529/221931581-ac7685bb-8e87-48f0-9a51-a5847ae36ffd.png)

### Expected Behavior

An item that has a freeleech flag should add the custom value to the score on search.

### Steps To Reproduce

Search an indexer for a result that would be in G_Freeleech 
View the custom indexer score, the value you have for G_Freeleech does not get added to the sum of all formats custom score.

### Environment

```markdown
- OS: Ubuntu 19.04
- Radarr: Version 4.4.3.6983 
- Docker Install: Package Version nightly-9f4152d by hotio
- Using Reverse Proxy: No
- Browser: Chrome
- Database:
```

### What branch are you running?

Nightly

### Trace Logs?

https://pastebin.com/ytmFhyMv

**Comment by bakerboy448** [comment]
Seems likely regression from https://github.com/Radarr/Radarr/commit/cbcf3d1058f47a87c43658084eafac13e7e0889f

**Comment by RyanAStrouse** [comment]
Thanks! Works great now!
