### ISSUE TITLE
Edit "Destination" Folder for List modifies all lists instead of selected list only

### ISSUE THREAD

**Issue by fremenfigure** [Radarr/Radarr#817]
**Description:**
Edit "Destination" Folder for List modifies all lists instead of selected list only.
This does indeed change every list as the downloads will go to this single folder.
Unable to set separate "Destination" folder per list.
Seems the same issue as #679 ?!

**Radarr Version:**
0.2.0.299

**Logs:**
n/a

**Comment by galli-leo** [comment]
As you saw yourself there is already another issue open because of that. We are investigating that one.
