### ISSUE TITLE
Radarr returning incorrect DATEADDED value.

### ISSUE THREAD

**Issue by CBers** [Radarr/Radarr#8171]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When using the NZB 360 app, the internal Dashboard returns old movies downloaded months ago, as being downloaded "today".

Two movies in question have different qualities in the same folder, suffixed with either 1080p or 4K.

The Chrome Dev Tools returns this:

 "movieFile": {
      "movieId": 1470,
      "relativePath": "Spider-Man Far from Home (2019) - 1080p.mkv",
      "path": "X:\\Videos\\Movies\\Spider-Man Far from Home (2019)\\Spider-Man Far from Home (2019) - 1080p.mkv",
      "size": 11219882529,
      "dateAdded": "2023-03-02T01:53:07Z",
      "indexerFlags": 0,
      
"movieFile": {
      "movieId": 935,
      "relativePath": "Men in Black International (2019) - 1080p.mkv",
      "path": "X:\\Videos\\Movies\\Men in Black International (2019)\\Men in Black International (2019) - 1080p.mkv",
      "size": 13346792431,
      "dateAdded": "2023-03-02T01:52:55Z",
      "indexerFlags": 0,
      
      The dates in file manager on Windows is:
            
![image](https://user-images.githubusercontent.com/1756472/222463916-449ff56c-4aed-4b7f-967a-ba35da8f38d8.png)
![image](https://user-images.githubusercontent.com/1756472/222463980-92f96479-909f-4e51-ae87-eb478e24133e.png)
     
     Kev, the NZB 360 developer, is aware of this and suggests a possible bug in Radarr.

     

### Expected Behavior

The correct downloaded date should be returned. 

### Steps To Reproduce

Please liaise with Kev, the NZB 360 developer.

### Environment

```markdown
- OS: Windows
- Radarr: v4.4.3.6983
- Docker Install: No
- Using Reverse Proxy: Yes
- Browser: Chrome
- Database: ??
```

### What branch are you running?

Nightly

### Trace Logs?

[Radarr-Trace.txt](https://github.com/Radarr/Radarr/files/10872641/Radarr-Trace.txt)

**Comment by bakerboy448** [comment]
- File system file properties have nothing to do with Radarr 
- Can't reproduce this on `4.4.3.6983`
- `dateAdded` of the MovieFile Property should be when the file appeared to Radarr
- What's the history tab for that movie show?
- Most likely the movie files vanished from Radarr's view and then reappeared

**Comment by CBers** [comment]
![image](https://user-images.githubusercontent.com/1756472/222469693-cad6e5a5-e5ed-44d5-b321-98bcde7973ce.png)
![image](https://user-images.githubusercontent.com/1756472/222469792-b6e4884b-0f7f-4aec-bc99-ec1f418b2a93.png)

Without going through 500+ movies, these are the only 2 that exhibit the issue.

**Comment by bakerboy448** [comment]
So the two movies with issues have never been imported by Radarr?
That's likely the cause then;  interim workaround may be to manual import from the movie folder so it gets an import event I think. 
======
the blocklist error is unreleated - https://github.com/Radarr/Radarr/issues/8136

**Comment by austinwbest** [comment]
There is a scenario that causes the date added value to constantly change to the current date during refreshes.

**Comment by CBers** [comment]
> So the two movies with issues have never been imported by Radarr? That's likely the cause then; interim workaround may be to manual import from the movie folder so it gets an import event I think.

Please can you expand on your suggestion, as Radarr knows about them, otherwise they wouldn't show.

**Comment by bakerboy448** [comment]
> > So the two movies with issues have never been imported by Radarr? That's likely the cause then; interim workaround may be to manual import from the movie folder so it gets an import event I think.
> 
> Please can you expand on your suggestion, as Radarr knows about them, otherwise they wouldn't show.

may or may not work, but movie page => manual import => import the file

hopefully it creates a history event for the import and that works around the issue

it's worth a shot at least

**Comment by CBers** [comment]
Deleting and re-importing the movie just sets the date added to the current date/time.

**Comment by austinwbest** [comment]
> Deleting and re-importing the movie just sets the date added to the current date/time.

That is expected but it should also stop it from updating every day to the current day

**Comment by CBers** [comment]
> > Deleting and re-importing the movie just sets the date added to the current date/time.
> 
> That is expected but it should also stop it from updating every day to the current day

Will check tomorrow.

**Comment by Qstick** [comment]
This `dateAdded` property is when that specific `movieFile` record was added to the DB. It doesn't persist updates (new movieFile record) and never was meant to.

**Comment by CBers** [comment]
> This `dateAdded` property is when that specific `movieFile` record was added to the DB. It doesn't persist updates (new movieFile record) and never was meant to.

That's not the issue though.

Radarr is returning the wrong date.

It is returning today's date rather than when the movie file was actually added, which was month's ago.

Removing a movie and re-importing gives you today's date, which is correct I assume, but this is for older movies.

I see the issue manifesting in NZB 360 app and Kev said to raise it here, as NZB 360 just gets the info from Radarr.
