### ISSUE TITLE
URLEncode the string for searching

### ISSUE THREAD

**Issue by mihaiblaga89** [Radarr/Radarr#818]
**Description:**

Please make sure that the query string is url encoded before making a request to torznab

[...]apikey=(removed)&offset=0&limit=100&q=spring breakers%202013

**Radarr Version:**
Radarr Ver. 0.2.0.299
**Logs:**
17-2-20 13:15:28.6|Debug|Torznab|Downloading Feed http://192.168.0.200:5060/torznab/filelist/api?t=search&cat=2010,2030,2040,2060,2070&extended=1&apikey=(removed)&offset=0&limit=100&q=spring breakers%202013
17-2-20 13:15:28.7|Trace|HttpClient|Req: [GET] http://192.168.0.200:5060/torznab/filelist/api?t=search&cat=2010,2030,2040,2060,2070&extended=1&apikey=(removed)&offset=0&limit=100&q=spring breakers%202013

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by onedr0p** [comment]
Need to think of another way to do this, currently it breaks search with movie titles that have Ö or other UTF8 characters.. reverting this commit.
