### ISSUE TITLE
Add new BitTorrent client

### ISSUE THREAD

**Issue by raynoxfr** [Radarr/Radarr#8184]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Impossible to add another bitorrent download client (not listed) or my own program to radarr

### Describe the solution you'd like

Is it possible to add the functionality to add another client not listed ?
(and API to implement it) 

### Describe alternatives you've considered

Can you give the API documentation about the existant BitTorrent client supported (aria2, utorrent) to know the communication from and to Radarr.
With this documentation, I can develop and adapt another client to make a "bridge" and use another not referenced

### Anything else?

Like that, I can create some programs, not really doing BitTorrent, but communicating with Radarr / Sonarr, not seeing the difference.
Behind, I simulate bittorent client, but using debrid link with BitTorrent (realdebrid, alldebrid).
Otherwise, I have to make reverse engineering, but it's long and boring

**Comment by bakerboy448** [comment]
Refer to the other client's API docs for how they work. Starr's use the client's api, nothing unique to Starrs themselves.

No plans to support Debrid. It is also toxic to the torrent community

duplicate of https://github.com/Radarr/Radarr/issues/3083
