### ISSUE TITLE
Support for MFA

### ISSUE THREAD

**Issue by jin-ds** [Radarr/Radarr#8200]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I'd love the option for Radarr to natively support MFA (2FA, OTP, etc.) to secure Radarr instances.

There are 2nd-layer auth solutions available, but not all rented shared servers can implement this.

Adding it to the application-level, we'd be able to keep our Radarr instances secure.

### Describe the solution you'd like

Optional 2FA/MFA support

### Describe alternatives you've considered

Using a 3rd-party application

### Anything else?

Nothing to add.

**Comment by RobinDadswell** [comment]
We are currently looking at implementing OIDC support which would then allow for MFA via the 3rd party auth solutions; I don't believe we are looking at implementing MFA support directly within the app at the moment.

**Comment by thezoggy** [comment]
rather than doing mfa for radarr, then to do it for sonarr, then your downloader.. etc. you are better off just using a reverse proxy so you have one thing to secure, which then you could use authentik/authelia or whatever you want to do your sso with mfa.

**Comment by bakerboy448** [comment]
No native MFA plans.

Refer to https://github.com/Radarr/Radarr/issues/7047 for OIDC FR and using MFA with said authentication
