### ISSUE TITLE
[BUG] Update Library : SceneMappingService failed 

### ISSUE THREAD

**Issue by ajkis** [Radarr/Radarr#821]
When i try to Update Library ( atm have 1200 out of 2800 movies in ), latest nightly version 
I see the following error in log and scanning is stopped. 

> 17-2-20 14:15:26.8|Info|SceneMappingService|Updating Scene mappings
> 17-2-20 14:15:28.4|Warn|HttpClient|HTTP Error - Res: [GET] http://radarr.aeonlucid.com/v1/scenemapping: 404.NotFound
> 17-2-20 14:15:28.4|Error|SceneMappingService|Failed to Update Scene Mappings:
> 
> [v0.2.0.368] NzbDrone.Common.Http.HttpException: HTTP request failed: [404:NotFound] [GET] at [http://radarr.aeonlucid.com/v1/scenemapping]
>   at NzbDrone.Common.Http.HttpClient.Execute (NzbDrone.Common.Http.HttpRequest request) <0x41b5d990 + 0x0047f> in <filename unknown>:0 
>   at NzbDrone.Common.Http.HttpClient.Get (NzbDrone.Common.Http.HttpRequest request) <0x41d18c70 + 0x0002b> in <filename unknown>:0 
>   at NzbDrone.Common.Http.HttpClient.Get[T] (NzbDrone.Common.Http.HttpRequest request) <0x41d7acc0 + 0x00017> in <filename unknown>:0 
>   at NzbDrone.Core.DataAugmentation.Scene.SceneMappingProxy.Fetch () <0x41d80630 + 0x00059> in <filename unknown>:0 
>   at NzbDrone.Core.DataAugmentation.Scene.ServicesProvider.GetSceneMappings () <0x41d80600 + 0x00024> in <filename unknown>:0 
>   at NzbDrone.Core.DataAugmentation.Scene.SceneMappingService.UpdateMappings () <0x41d7d6f0 + 0x000c7> in <filename unknown>:0

**Comment by galli-leo** [comment]
That does not have any effect on Radarr
