### ISSUE TITLE
Must Not Contain

### ISSUE THREAD

**Issue by Fiala06** [Radarr/Radarr#823]
I've noticed the "Must Not Contain" on the indexers tab isn't doing an absolute value. I think that's how to describe it. 

I have a word "TS" as I don't want anything with that in the title. Well after checking a random movie noticed it blocked DTS which is a preferred word but since it has "TS" its being blocked. 

Radarr Ver. 0.2.0.299

Screenshots:
![tags](https://cloud.githubusercontent.com/assets/5183146/23138796/32b609e8-f75e-11e6-99da-7c1721e5c10e.png)

![must not contatin](https://cloud.githubusercontent.com/assets/5183146/23138801/36075cd2-f75e-11e6-9ac5-190dc6c448a2.png)

**Comment by galli-leo** [comment]
We have a Telesync quality, so no need to exclude ts. But we will keep that in my mind.

**Comment by Fiala06** [comment]
Ok I'll remove it. Thanks, wasn't sure if its a bug or not since it wasn't matching the word inside of other words.

**Comment by galli-leo** [comment]
You can also remove the language tags as well as korsub & swesub and HDCam, HC, DVDScreener, etc. Radarr recognizes these accordingly.

**Comment by Fiala06** [comment]
I just copied everything I had from the darkside (couchpotato).

Anyways everything else seems to be working great since I set it up last night. You guys are awesome!

**Comment by rkmfl** [comment]
I ran into the exact same issue myself.

This is my "Must Not Contain" list from CP.  I'm including here just to be certain that all of these cane be removed, or whether some of them might still be required?  If there is a list of terms Radarr is setup to recognize, it would be a great resource.

**Language Exclusions:**
------------------
subbed 
dubbed 
german, dutch, french, truefrench, danish, swedish, spanish, italian, korean, swesub, korsub, dksubs, 

**Quality Exclusions:**
------------------
HC 
telesync 
cam 
hdcam 
hdrip 
web 
webrip 
webdl 
web-dl 
web-rip 
hd-ts 
hd-tc 
dvdr 
dvd-rip 
line audio 
vain (low bitrate/quality release group)

**Codec exclusion:**
------------------
xvid
