### ISSUE TITLE
When downloading film get error "Memory stream is not expandable."

### ISSUE THREAD

**Issue by RiccardoBarbieri** [Radarr/Radarr#8233]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When I go on the search tab of a film I want to download and click the download cloud of https://1337x.unblockninja.com/torrent/234951/Contact-1997-720p-BrRip-mkv-600MB-YIFY/](this torrent) I get the error "Memory stream not expandable.".

### Expected Behavior

Start of the download

### Environment

```markdown
- OS: Ubuntu 22.04
- Radarr: 4.3.2.6857
- Docker Install: No
- Using Reverse Proxy: Yes
- Browser: Firefox
- Database: Sqlite 3.37.2
```

### What branch are you running?

Master

### Trace Logs?

[radarr.trace.log](https://github.com/Radarr/Radarr/files/10994693/radarr.trace.log)

**Comment by Qstick** [comment]
Seems like a bad torrent from the indexer, or app you are using to feed Radarr
