### ISSUE TITLE
2 HDR10 movie, one get renamed with HDR10 the other with PQ

### ISSUE THREAD

**Issue by nodiaque** [Radarr/Radarr#8249]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Using the naming pattern
{Movie Title} ({Release Year}) [imdbid-{ImdbId}] {MediaInfo Simple} {MediaInfo AudioLanguages} {MediaInfo AudioChannels}{ Custom Formats}{-Release Group} - {Quality Full} {MediaInfo VideoDynamicRangeType} {Edition Tags}

I have 2 movie that are HDR10 but when they get renamed, one get PQ and the other HDR10

### Expected Behavior

I expect both to have HDR10 as quality from {MediaInfo VideoDynamicRangeType}

### Steps To Reproduce

Set namming scheme to 

{Movie Title} ({Release Year}) [imdbid-{ImdbId}] {MediaInfo Simple} {MediaInfo AudioLanguages} {MediaInfo AudioChannels}{ Custom Formats}{-Release Group} - {Quality Full} {MediaInfo VideoDynamicRangeType} {Edition Tags}

### Environment

```markdown
- OS: Unraid 6.9
- Radarr: 4.3.2.6857
- Docker Install: lscr.io/linuxserver/radarr
- Using Reverse Proxy: yes
- Browser: firefox
- Database:
```

### What branch are you running?

Master

### Trace Logs?

Attached are 2 json from media info, one from encanto and other from bridget. Both display HDR when played and both show HDR10 metadata in mediainfo. But Encanto get PQ instead of HDR10 like Bridget.
[jsons.zip](https://github.com/Radarr/Radarr/files/11069253/jsons.zip)

**Comment by bakerboy448** [comment]
PQ is a type of HDR and is what was probed by ffprobe

**Comment by nodiaque** [comment]
Ok, but both are HDR10 so why it show as PQ?

**Comment by bakerboy448** [comment]
https://github.com/Radarr/Radarr/blob/42c9e4e3e542cc06aac1a71b56635c2ab9577638/src/NzbDrone.Core/MediaFiles/MediaInfo/VideoFileInfoReader.cs#L158

radarr doesn't use mediainfo and has a whole chain of logic to determine the HDR type from the ffprobe results so your jsons aren't really relevant 

```bash
/path/to/radarr/binaries/ffprobe -v quiet -print_format json -show_format -sexagesimal -show_streams  -i /path/to/file
```
Should be how to see the raw data radarr uses

And PQ (aka PQ10) is a form of HDR10.
https://en.m.wikipedia.org/wiki/HDR10
