### ISSUE TITLE
Importing Movies In Flat Directory Structure

### ISSUE THREAD

**Issue by bushbrother** [Radarr/Radarr#826]
When importing existing movies, there is no way to import from a flat "Movies" folder. I do not put my downloads in individual directories and don't really want to start. Any way to get around this?

Radarr Version: 0.2.0.299

**Comment by fedoranimus** [comment]
Nope.

**Comment by bushbrother** [comment]
Thanks - I will keep an eye on this project as it looks great :)

**Comment by darknessgp** [comment]
Just an FYI for @bushbrother my best guess is this will come with #153 when flat directory structure is completely supported. Something I'm waiting on too to fully utilize Radarr.

**Comment by dogsthatbarkbees** [comment]
This needs to be upvoted!  Having movies in individual folders make absolutely no sense unless you are storing subtitles and other data alongside the files.  

As Radarr is a fork of Sonarr it makes sense why it's set out like that, but movies are not TV shows and flat folders should be the default and then there should be option for nested folders.

Please make this an option Radarr, it is the one feature that is stopping me from using Radarr.  I am not changing my entire library to be in nested folders when its unnecessary.
