### ISSUE TITLE
Search film with french title

### ISSUE THREAD

**Issue by PepeMax** [Radarr/Radarr#8271]
### Is there an existing issue for this?

- [x] I have searched the existing open and closed issues

### Current Behavior

I am looking for a way to force radarr to search for movies on my indexers with the title of the movie in French, for example if I search for "La vérité si je mens !" it searches for "Would I Lie to You?" how to force the use of the French name and even for English movies?

In the parameters I am well in French:
![image](https://user-images.githubusercontent.com/35230511/227857528-85723bcd-ec50-46ca-920c-f5a093d89369.png)

### Expected Behavior

I would like Radarr to search for films with the title in French

### Environment

```markdown
- Docker Install: Yes
- Docker Image: linuxserver/radarr
- Using Reverse Proxy: No
```

### What branch are you running?

Master

### Trace Logs?

2023-03-27 06:24:50.7|Info|ReleaseSearchService|Searching indexers for [Would I Lie to You?]. 10 active indexers
2023-03-27 06:25:11.1|Info|DownloadDecisionMaker|No results found

**Comment by bakerboy448** [comment]
https://wiki.servarr.com/radarr/faq#how-does-radarr-handle-foreign-movies-or-foreign-titles
