### ISSUE TITLE
Subtitle hearing-impaired tags are lost when renaming files

### ISSUE THREAD

**Issue by augustuen** [Radarr/Radarr#8275]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Hearing-impaired tags (e.g. forced, sdh, cc) in subtitle file names are lost when Radarr renames files it didn't import. If the subtitle files are imported alongside the movie file they keep the tags, but files added after import (e.g. by Bazarr) don't. Tested both with Master, and with a develop build. 

### Expected Behavior

Expected is for the renamed subtitle files to have the same tags for forced or hearing-impaired as they originally had. 

### Steps To Reproduce

1. Add a subtitle file with a tag to a movie's folder, example:
`30 Rock A One-Time Special (2020) WEBRip-1080.en.forced`
2. Run a Scan & Refresh (on that movie or the scheduled task) 
3. Trigger a rename 
4. The subtitle file should now have been renamed to 
`30 Rock A One-Time Special (2020) WEBRip-1080.en`
If there are multiple subtitle files for the same language, Radarr affixes a number between the name and language indicator:
`30 Rock A One-Time Special (2020) WEBRip-1080.1.en
30 Rock A One-Time Special (2020) WEBRip-1080.2.en`

### Environment

```markdown
- OS: Windows & Kubernetes (Truecharts)
- Radarr: 10.0.0.34194 & 4.3.2.6857
- Docker Install: No & Yes
- Using Reverse Proxy: No
- Browser: N/A
- Database: Sqlite 3.36.0 & Sqlite 3.40.1
```

### What branch are you running?

Master

### Trace Logs?

Expected behaviour is seen at around 19:17:19 and the unexpected happens at 19:18:12

[radarr.trace.txt](https://github.com/Radarr/Radarr/files/11092665/radarr.trace.txt)

**Comment by klepp0906** [comment]
Yes, i was renaming when i noticed the issue. searched for a existing issue report and that seemed pretty close.  I assume(d) it would stem from the same place regardless. 

eager for a fix to be pushed though so thank you for taking a look <3
