### ISSUE TITLE
Discover ratings don't have a limit on decimal places

### ISSUE THREAD

**Issue by Lagicrus** [Radarr/Radarr#8278]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

14 decimal place precision on ratings

### Expected Behavior

To stop at 1 decimal place

### Environment

```markdown
- OS: Ubuntu 22
- Radarr: 4.3.2.68.57
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Chrome 110
- Database: Sqlite 3.40.0
```

### What branch are you running?

Master

### Trace Logs?

![image](https://user-images.githubusercontent.com/24227350/228659923-38ee2c52-1ff1-4631-a3a1-49e991467bd5.png)
![image](https://user-images.githubusercontent.com/24227350/228660024-36421a75-17c8-4596-8ecb-5898bdeb22d1.png)

**Comment by bakerboy448** [comment]
Confirmed in Discover Overview - 4.4.3.7014
