### ISSUE TITLE
Local Disk Scan issue

### ISSUE THREAD

**Issue by astlaurent** [Radarr/Radarr#828]
**Description:**

Radarr grabbed the old ghost in the shell anime version thinking it was the new version which is added in my watch list. I deleted it from my disk manually and there is no folder or file for it on my disk anymore. However Radarr still thinks it is there. If i click update movie and scan disk it does not remove the file listing in Radarr and the downloaded tag does not go away. 

I have also seen this issue when i have manually imported movies. It claims that i have not downloaded them. If i click on scan disk it still claims i do not have them. If i browse to a folder and pick literally the same folder that is listed in the movie profile and save it again then it claims that it is downloaded. 

**Radarr Version:** 
0.2.0.373

**Logs:**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by KiLLeRRaT** [comment]
I'm having the same issue.  I have a movie, I moved the files to another folder, and then clicked Update movie and scan disk, it shows in the logs that it was successful, but it still shows that the file is in the original location. As if it's not checking the file to make sure it's there.

**Comment by galli-leo** [comment]
This is fixed on the latest version.
