### ISSUE TITLE
False positive error shown due to torrent client UNC data path being incorrectly parsed by Radarr

### ISSUE THREAD

**Issue by ReeKorl** [Radarr/Radarr#8280]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

An error message is being displayed in System -> Status -> Health about the torrent client path not being a valid Windows path, specifically "Remote download client qBittorrent places downloads in /hogbrisnasprd01/media/torrents/data/complete/radarr but this is not a valid Windows path. Review your remote path mappings and download client settings". This error is not correct.
![TeamViewer_Ii9sfncU2B](https://user-images.githubusercontent.com/3449717/228841065-dab86a34-1cf0-4ffe-97f0-5bba208e3fbc.png)

Radarr is running as a Windows service on the host machine, with its own service account which has been granted the requisite R/W path access to all locations involved. qBittorrent is running in a Hyper-V Windows 10 guest OS on the host. Data (both for downloads, and stored media library) are on a NAS, accessed via UNC network path. No remote mappings are in use - all paths used everywhere are the full UNC path, and are the same no matter what is looking for them, or from where.

An identical setup, on the same hardware, is working flawlessly for Sonarr with no error message being displayed.
![TeamViewer_o3e8mvd7Mh](https://user-images.githubusercontent.com/3449717/228841312-7c04a999-056c-4a07-8341-a4b4d4fe0603.png)

Other than the spurious error message, Radarr is also working flawlessly, and despite warning the path is not valid, is able to handle all operations from finding releases to importing them to the library and removing from torrent client.

### Expected Behavior

Error does not appear.

### Steps To Reproduce

1. Configure qBittorrent to save downloads categorised as "radarr" to a UNC network path (ie "\\\HOSTNAME\path\to\directory")
2. Trigger a health check via System -> Tasks -> Check Health 
3. See error message show on System -> Status -> Health with malformed path of "/HOSTNAME/path/to/directory"

### Environment

```markdown
- OS: Host: Windows 10 Pro 21H2. Guest: Windows 10 Pro 21H2. Datastore: Synology DSM 7.1 release 4
- Radarr: 4.3.2.6857
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Any/all
- Database: Sqlite 3.36.0
```

### What branch are you running?

Master

### Trace Logs?

Trace log: https://gist.github.com/ReeKorl/5c1203b7e17eb2660ec93adf79804769

Torrent client download path for Radarr:
![TeamViewer_gnBJczbnAv](https://user-images.githubusercontent.com/3449717/228841682-50502429-a073-4721-9737-e2f599e9e262.png)

and Sonarr:
![TeamViewer_9fo4WJGzml](https://user-images.githubusercontent.com/3449717/228841828-1b9c5640-63ff-403c-bbd4-40f7cff3727f.png)

**Comment by bakerboy448** [comment]
For quick note - Sonarr has no error because Sonarr v3 does not have this check.

**Comment by bakerboy448** [comment]
What qbit version? This seems to be their API returning non-windows paths for categories.

Categories - not valid windows pathing

```none
2023-03-30 13:22:24.4|Trace|HttpClient|Response content (501 bytes): {"RemoteSeed NAS":{"name":"RemoteSeed NAS","savePath":"Z:/torrents/data/seed"},"other":{"name":"other","savePath":"Z:/torrents/data/complete/other"},"radarr":{"name":"radarr","savePath":"//hogbrisnasprd01/media/torrents/data/complete/radarr"},"readarr-a":{"name":"readarr-a","savePath":"Z:/torrents/data/complete/readarr-a"},"readarr-b":{"name":"readarr-b","savePath":"Z:/torrents/data/complete/readarr-b"},"sonarr":{"name":"sonarr","savePath":"//hogbrisnasprd01/media/torrents/data/complete/sonarr"}}
```

versus from preferences, valid windows pathing

```none
"scan_dirs":{"Z:\\torrents\\autoload"
```

If this is qbit 4.5.X, does it persist with qbit 4.3.9 and qbit 4.4?

**Comment by bakerboy448** [comment]
> difficult to tell exactly what's being returned as-is and what's being output to the log as 'sanitised because of escape characters' from just the trace though?

the logged output is exactly what is being returned.

neither `//hogbrisnasprd01/media/torrents/data/complete/radarr` nor `/hogbrisnasprd01/media/torrents/data/complete/radarr` is not a valid windows nor UNC path.  So the dropping of the leading `/` doesn't matter.

it looks like Qbit v4.5.2 for the categories api call is returning UNC paths as \*Nix Paths.  Given Qbit's frequent history of undocumented breaking API changes and given the lack of any other of the hundreds of thousands of radarr users reporting this.....it seems the most likely it is an issue with qbit v4.5.2.   Thus please test a previous known working qbit build - 4.3.9 or 4.4.5.
