### ISSUE TITLE
Custom scripts are not running

### ISSUE THREAD

**Issue by yjiawqgj** [Radarr/Radarr#8281]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

My custom script in notification connection, notification trigger: when renamed, fire the script. The script content is:
#!/bin/bash
cd /volume1/tms && ./tinyMediaManager movie -u -n &>radarr.log

When adding a custom script, it needs to be tested before it can be saved, and after the test is completed, a radarr.log file will be generated. But after the test is passed and saved, after adding the search to grab the movie file, downloading, importing, hard linking and renaming, the radarr.log file is not generated, and the tinyMediaManager in the script does not run. I don't think radarr is running the script.

### Expected Behavior

I have found many people to solve this problem, but no one can solve it. Later, someone told you to add an output log command in the custom script, and I was sure that the problem was that radarr did not execute the script. Just ran the script while adding and testing, but got errors. I think it should be this instruction: "Testing will execute the script with the EventType set to Test, ensure your script handles this correctly" which causes the script to run incorrectly. I tried contacting your Discord channel, but my request was ignored. I am disappointed.

### Environment

```markdown
- OS: synology
- Radarr: 4.3.2.6857
- Docker Install: no
- Using Reverse Proxy: no
- Browser: chrome
- Database: Sqlite 3.39.3
```

### What branch are you running?

Master

### Trace Logs?

[radarr.txt](https://github.com/Radarr/Radarr/files/11112701/radarr.txt)

**Comment by bakerboy448** [comment]
- Not a bug, support request.....GitHub is not for support
- Custom Scripts function fine
- Info Logs are not valid for bug reports
- logs show nothing relating to a custom script being triggered
- logs show no attempt to test the script
- the script must handle the test event as the UI and docs say: https://wiki.servarr.com/radarr/custom-scripts#on-test

most likely your script is invalidly formatted, perhaps CRLF instead of LF or the user/group radarr is running as does not have the appropriate permissions

Use the appropriate methods the bot said for support.

**Comment by yjiawqgj** [comment]
> * 不是错误，支持请求.....GitHub 不提供支持
> * 自定义脚本功能正常
> * 信息日志对错误报告无效
> * 日志显示与正在触发的自定义脚本无关
> * 日志显示没有尝试测试脚本
> * 该脚本必须按照 UI 和文档所述处理测试事件：[https ://wiki.servarr.com/radarr/custom-scripts#on-test](https://wiki.servarr.com/radarr/custom-scripts#on-test)
> 
> 很可能您的脚本格式无效，可能是 CRLF 而不是 LF，或者用户/组 radarr 正在运行，因为没有适当的权限
> 
> 使用机器人所说的适当方法以获得支持。

I've consulted on Discord, but didn't get a solution. The script is correct and passes the connection test. And the script can be executed manually and correctly in the ssh terminal.

**Comment by bakerboy448** [comment]
- Not a bug, support request.....again, GitHub is not for support
- Custom Scripts function fine
- Info Logs are not valid for bug reports
- logs show nothing relating to a custom script being triggered
- logs show no attempt to test the script

> The script is correct and passes the connection test.

Then provide the trace logs of it running or failing to run when using the correct trigger as was requested on discord.

Again, Please use one of the support channels: [Reddit](https://www.reddit.com/r/radarr/) or  [Discord](https://radarr.video/discord) for support/questions.
