### ISSUE TITLE
Unable to recognize BluRay disc correctly

### ISSUE THREAD

**Issue by Gladtbam** [Radarr/Radarr#8286]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When the downloaded BDVM exists in the form of a folder, radarr cannot import it correctly.

![Snipaste_2023-03-31_19-42-08](https://user-images.githubusercontent.com/49943258/229111161-10b8efdc-d9c7-4ba6-b998-8ecab3f89854.png)
![Snipaste_2023-03-31_19-43-21](https://user-images.githubusercontent.com/49943258/229111364-4f688abc-6f3b-4ed3-a734-949f45f77a66.png)
![Snipaste_2023-03-31_19-44-32](https://user-images.githubusercontent.com/49943258/229111587-d08ccf2d-ffa3-4487-a564-9cb9fa91aa27.png)

### Expected Behavior

If I package it as an ISO using a shell script, will Radarr automatically recognize it on import?

### Environment

```markdown
- OS: Debian GNU/Linux 11 (bullseye)
- Radarr: 4.3.2.6857
- Docker Install: No
- Using Reverse Proxy: Yes
- Browser: 
- Database: Sqlite 3.34.1
```

### What branch are you running?

Master

### Trace Logs?

Sorry, the corresponding log seems to have been cleaned up

**Comment by bakerboy448** [comment]
- trace logs are not optional for bug reports
- Likely duplicate/related to https://github.com/Radarr/Radarr/issues/145
- `.iso` are supportedish, but broken -  https://github.com/Radarr/Radarr/issues/7828

**Comment by Gladtbam** [comment]
I created a shell script, when the file downloaded by qbittorrent is in the form of a BDMV folder, copy it directly to the corresponding folder created by radarr.  But I can't prevent radarr from continuing to detect the wrong .m2ts file, or prevent radarr from continuing Let qbittorrent download the same torrent.

**Comment by bakerboy448** [comment]
Closing; can reopen if/when logs are provided
