### ISSUE TITLE
Add new "Change file date" option to apply to future files only, not existing

### ISSUE THREAD

**Issue by Silent-Remux** [Radarr/Radarr#8289]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

This would be helpful to avoid unnecessary ffprobes in media apps if you change between "physical release date" and "in cinema release date".

### Describe the solution you'd like

A tickbox to "apply to future imports only".

### Describe alternatives you've considered

Can't think of another alternative to avoid affecting existing files.

### Anything else?

None.

**Comment by Qstick** [comment]
Similar to #4913, lets track options for file date there.
