### ISSUE TITLE
Feature Request: Ability to add multiple languages in Profiles

### ISSUE THREAD

**Issue by Fredrik81** [Radarr/Radarr#829]
**Description:**

As i live in none english speaking country i want to be able to download some movies in my own language.
It would be good if we could add multiple languages in the profile with a priority.
Example:
1. English
2. Swedish

So if no english is found it will grab Swedish version. This should cover if the movie is only in swedish or if two versions exists the preferred one will be grabbed.

**Radarr Version:**
0.2.0.299

**Logs:**
N/A

**Comment by inkubux** [comment]
+1

As someone who speaks french but listen to movies in english, I would like to specify the language per release as my kids wants some french movies. I tried with tags, but french releases are always rejected

**Comment by saitoh183** [comment]
@Fredrik81 
http://feathub.com/Radarr/Radarr

Vote it up

**Comment by galli-leo** [comment]
Since it's already on feathub, I am closing it for now
