### ISSUE TITLE
Consider supporting {tags} for renaming (Allowing "Extended,Uncut,Director's Cut, etc" when renaming)

### ISSUE THREAD

**Issue by chrisallen** [Radarr/Radarr#83]
Basically offering the same functionality as "FileBot"

see here for a list of "tags": https://github.com/filebot/filebot/blob/72da7935bfbd498b92aa44674806127f8b850a3f/source/net/filebot/media/ReleaseInfo.properties#L4-L5

and here for how they normalise them:

```java
	@Define("tags")
	public List<String> getVideoTags() {
		// look for video source patterns in media file and it's parent folder (use inferred media file)
		List<String> matches = releaseInfo.getVideoTags(getFileNames(getInferredMediaFile()));
		if (matches.isEmpty()) {
			return null;
		}

		// heavy normalization for whatever text was captured with the tags pattern
		return matches.stream().map(s -> {
			return lowerTrail(upperInitial(normalizePunctuation(s)));
		}).sorted().distinct().collect(toList());
	}
```

**Comment by ShanDestromp** [comment]
Adding this here since I don't think it's worthy of it's own issue but can we also get just "more" options for naming?  For example, all my existing media is in the format of "Title (Year) [Resolution]/Title (Year) [Resolution] [Codec].ext" because I'm not (too) picky on whether it's BluRay-1080p or a WebDL.

**Comment by chrisallen** [comment]
In a perfect world I would love to see the Movies detail page look like this:

Where we have Tags as `Titlecase` and shown with a "badge" style vs. tooltip, and then have `[Extended]` etc in the filenames.

![image](https://cloud.githubusercontent.com/assets/203867/22186971/2947419e-e163-11e6-99e0-51c9dd37a9b0.png)

**Comment by galli-leo** [comment]
Fixed in latest commit.
