### ISSUE TITLE
Search (on Movie page) drops you at the bottom of search results

### ISSUE THREAD

**Issue by simonk83** [Radarr/Radarr#830]
**Description:**

Fairly minor bug, but a quick fix and makes for a nicer experience.   If you go to a specific movie and click the search tab, if the resulting list is larger than the height of your window it drops you at the bottom of the list, which in some cases can be quite large.  Just means you have to scroll up to the top to see the most relevant releases.

**Radarr Version:** 0.2.0.370

**Logs:**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by thejacer87** [comment]
not sure if this was fixed accidentally already, but i was going to try to tackle this and could not reproduce on the develop branch.

![peek 2017-03-26 23-27](https://cloud.githubusercontent.com/assets/6412919/24343575/0c85e818-127c-11e7-91a9-1069d0dfb73f.gif)

**Comment by simonk83** [comment]
Sorry, I just didn't explain it very well. It's when you search for
releases. So you bring up, for example, the Rogue One movie and click the
search tab down the bottom (next to Files). Once the results are in, if
there are enough, it drops you at the bottom of the list .

**Comment by simonk83** [comment]
That said, I can't actually reproduce that either, so maybe it was stealth fixed afterall :D

**Comment by thejacer87** [comment]
got it k
