### ISSUE TITLE
Have a "Grabbed for Movie" Column Option in Activity Queue

### ISSUE THREAD

**Issue by edrock200** [Radarr/Radarr#8306]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Radarr does a great job of grabbing appropriate releases. But every now and again it will grab something very random and not close to the movie it was attempting to grab, or it has grabbed something by it's alternate title which is nothing close to the listed name in Radarr. When it does this, and cannot match the item, its very difficult to know what that entry was grabbed for.

For example. Lets say I add movie "Amazing ABC." Radarr finds it a few weeks later by imdb ID in an indexer, but the indexer has it listed by alt title "Incredible ABC." The Activity queue shows yellow entry "Incredible ABC" but no reference to the fact that it was grabbed for Amazing ABC, unless its a feature I'm unaware of. (In Activity/Options, you have to have "Show movies without a movie in the queue..." ticked.)

At this point, the only options to match it are to scroll through the History queue looking for downloads without imports and trying to match it up, or, deleting it from queue and selecting "block release and start new search" in which case you can see what it thought that download was for in the bottom left hand running tasks dialogue. If the movie was in a usenet downloader, it is deleted, as there doesn't seem to be a way to untick the "Remove from download client" box for usenet entries.

### Describe the solution you'd like

Add a column or mouse over entry that lists what movie Radarr grabbed each download in the activities window for.

### Describe alternatives you've considered

Presently, as noted above I will scroll through history and try to find/match, or delete/blocklist and let it search again so I can see what it thought that entry was for.

### Anything else?

If this feature exists already or was requested already, my apologies for the dupe.

**Comment by bakerboy448** [comment]
> the only options to match it are to scroll through the History queue looking for downloads without imports

Source Title has been an available column in history which should allow you to match up the torrent name for the release name.

The Activity Queue Parser is intentionally disconnected from the Grab parser

Most likely these grabs are due to your indexers having the wrong id for the movie

**Comment by edrock200** [comment]
> > the only options to match it are to scroll through the History queue looking for downloads without imports
> 
> Source Title has been an available column in history which should allow you to match up the torrent name for the release name.
> 
> The Activity Queue Parser is intentionally disconnected from the Grab parser
> 
> Most likely these grabs are due to your indexers having the wrong id for the movie

I don't see a source title option but I see "Movie" and "Release Title" options. I forgot one step above, you have to have "Show movies without a movie in the queue" ticked on options on the activity pain. It's rare, but once or twice a month radarr will grab something (most likely due to indexer error) that doesn't align to any movie in radarr. Radarr seems to have a mapping somewhere of what it was grabbed for, because if you delete and tick blocklist/search again, it searches for the actual title in radarr. I guess thats what I'm asking, wherever that mapping is stored, can that be a column in options?

Thanks in advance for your consideration.

**Comment by bakerboy448** [comment]
> I don't see a source title option but I see "Movie" and "Release Title" options.

again, this is on History.  Which would then allow you to match up the `Release Title` in queue to the `Source Title` from the grab

>  (most likely due to indexer error) that doesn't align to any movie in radarr.

*near 100% due to indexer error

**Comment by edrock200** [comment]
Right. but if you don't check the queue often, then happen to see a yellow a day later after a good bit of history has been accumulated, its hard to match them up. Hence the feature request :) @bakerboy448

**Comment by reloxx13** [comment]
I feel you, have the same problem, and it's just unnecessary annoying, the grabbed release is showing in the movie details page in the history, why should it not be connected to the queue page (grab parser↔queue parser).

**Comment by bakerboy448** [comment]
The Grab Parser and Import Parser are intentionally disconnected.

You don't want Radarr to blindly grab and import that is say The Scooby Doo Movie by Id,  but the actual file is Wolf of Wall Street.

**Comment by reloxx13** [comment]
its NOT BLINDLY if its in the movie history and GRABBED FROM movie X

**Comment by edrock200** [comment]
> The Grab Parser and Import Parser are intentionally disconnected - that will likely never change.
> 
> You don't want Radarr to blindly grab and import that is say The Scooby Doo Movie by Id, but the actual file is Wolf of Wall Street.
> 
> > you'll re-download the movie multiple times because it gets not matched but re-grabbed
> 
> only if it shows on the rss feed again etc.

Understand they are intentionally disconnected, but somewhere theres a mapping, because deleting and marking the release blocked then searches for the correct original movie title. However it's doing that, would be nice to have as a column option. 

Not trying to be difficult, just thought it would be a nice feature add.  :) If I'm the minority here, I understand. Either way, appreciate the consideration @bakerboy448 and team.

**Comment by edrock200** [comment]
@bakerboy448 my apologies. I just realized what you meant. I was looking for the column in activity, which would still be nice, however I added the Source title column in History and this will at least make tracing down the orphaned activity item much easier.

**Comment by bakerboy448** [comment]
https://github.com/Radarr/Radarr/pull/8378

- Fixed: Don't automatically import if release title doesn't match movie title
- Fixed: Automatic import of releases when file is not matched to movie
- New: Include Movie Match Type in grab event details

Make this largerly moot / redundant as the request is due to Indexer.Id != Downloaded Movie?
