### ISSUE TITLE
import scheduler

### ISSUE THREAD

**Issue by DeadSledge989** [Radarr/Radarr#8308]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

when importing to a single disk, applications stop responding during import

### Describe the solution you'd like

set a time period to allow imports during that period. let's say in the night when nobody is using the system.

### Describe alternatives you've considered

download stop during use periods, but this won't stop imports during day

### Anything else?

none

**Comment by bakerboy448** [comment]
Duplicate of https://github.com/Radarr/Radarr/issues/6563
