### ISSUE TITLE
Source title

### ISSUE THREAD

**Issue by screamjojo** [Radarr/Radarr#8309]
The name and the variables are too random (as VFF/VFI/&more specific french tag for example) to find a constant rule, that's why I want to use the "source file" token. This token is somewhere in the DB, so my request is to ask to implement it in the rename token list.

see you in discord :)

_Originally posted by @lebnet in https://github.com/Radarr/Radarr/issues/4406#issuecomment-725631445_

Hello,

I'm in the exact same wanted. A solution is it available ?

Thanks in advance

**Comment by lebnet** [comment]
Hello,
no solution so far unfortunately...

**Comment by screamjojo** [comment]
Source Title has an available column in Activity history, why is it impossible to add the same thing for renaming ?
I've search a solution a lot of hours without success ...
