### ISSUE TITLE
Url base proxy nginx 404 issue

### ISSUE THREAD

**Issue by phairplay** [Radarr/Radarr#831]
**Description:**

Ive added radarr to my nginx setup using /radarr in the url base and the following in my nginx setup

}
	location /radarr {
		proxy_pass http://127.0.0.1:7878/radarr/;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		auth_basic           "Movies closed site";
        auth_basic_user_file .htpasswd;
}
same as my sonarr yet i keep getting 404, can you please hrlp

**Comment by phairplay** [comment]
sorry im a dum ass 
all sorted

**Comment by justlookingaround12** [comment]
Could you tell us what you were doing wrong? My nginx set up is not working and i just can't understand what i'm doing wrong.
