### ISSUE TITLE
Release Parser multi tag is not working

### ISSUE THREAD

**Issue by danimart1991** [Radarr/Radarr#8328]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Release titles including Multi word tag, for example "Movie (2023) WEBDL 1080p Multi/Spanish", doesn't get the values of Multi tag set in Indexers section.

### Expected Behavior

"Movie (2023) WEBDL 1080p Multi/Spanish" must detect the languages set in the multi tag option for that specific indexer and Spanish.

### Steps To Reproduce

Release titles including Multi word tag, for example "Movie (2023) WEBDL 1080p Multi/Spanish", doesn't get the values of Multi tag set in Indexers section. So, in the example, I set multi tag with Original but only the language Spanish is detected.

It seems that this issue is caused by these commits:
- https://github.com/Radarr/Radarr/commit/ad8629fac981217f5a4a5068da968c29d9ee634c
- https://github.com/Radarr/Radarr/commit/7ec0fd1cea5e6203a6f7acbd3de5354c24193dec

Indeed, when Multi tag in Indexer options is set with more than one language, an exception throw:
- https://github.com/Radarr/Radarr/pull/7713

### Environment

```markdown
- OS: Debian 11
- Radarr: 4.3.2.6857
- Docker Install: Latest
- Using Reverse Proxy: Yes
- Browser: Edge
- Database: Native
```

### What branch are you running?

Develop

### Trace Logs?

[radarr.trace.txt](https://gist.github.com/danimart1991/2c8fa942d401ef3c5cf99d3e3b715483)

**Comment by danimart1991** [comment]
Hello @bakerboy448. Thanks for the triage.

- Sorry. I put the trace logs in the Issue description. 
- I tried with indexers configured with multi only with Original and with Original + English. In the example, "Movie (2023) WEBDL 1080p Multi/Spanish", only Spanish is detected.
- Indeed, It seems that this issue is happening too in Sonarr.

**Comment by bakerboy448** [comment]
@Qstick test case to add?
