### ISSUE TITLE
Different folders for different qualities

### ISSUE THREAD

**Issue by ersan** [Radarr/Radarr#834]
**Description:**

I'm not sure if this is a common usage scenario but what I do with my library is have two separate sections, one for low quality releases (CAM, TS, WEBDL) and a main section with BluRay's - I just discovered Radarr today and am in the process of migrating from CouchPotato but I don't know if this is achievable.  I had a pretty convoluted system set up to do this with CP (Two separate CP servers running with a script to check for BluRay's downloaded that would remove the old low-quality release from the low quality folder) but I can see Radarr making this 10000x easier if it had the ability to move releases to a different folder depending on the quality.

I don't believe there is any way to do this currently but if there is I would love to hear about it.

I totally understand if this isn't a feature you want to implement, and I will start coming up with ways to script it externally.

**Radarr Version:**

0.2.0.374

**Logs:**

N/A

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by galli-leo** [comment]
Not really something we want to implement.

**Comment by ersan** [comment]
I actually spent about a half hour working on this and came up with a very simple custom postprocessing script in PHP that did exactly what I need, if anyone sees this post that is looking for a similar feature you can probably modify it to suit your needs: http://pastebin.com/mSEAa8mn

I'm really glad Radarr exists, I had been looking to get rid of CP for a very long time - thank you guys so much for making it!

**Comment by galli-leo** [comment]
@ersan Thanks for sharing it. Would be cool if you made a wiki entry :)

**Comment by onedr0p** [comment]
Please open on feathub if its not there.
