### ISSUE TITLE
Newer metadata not pulled from TMDb

### ISSUE THREAD

**Issue by benfishbus** [Radarr/Radarr#8345]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When adding movies to Radarr that were added to TMDb within the last - I don't know - month or two? - a lot of metadata is not retrieved: release date/year, cast, crew, poster, genre. For older movies these are retrieved, but any recent updates (again, anything less than 1-2 months old) are never reflected in Radarr. I've raised this a couple of times in Discord, and other users report experiencing the same thing. My calls to the TMDb API outside of Radarr (using my personal API key) return normal results, including all the elements mentioned above.

### Expected Behavior

Movie metadata in Radarr always reflects what is in TMDb, give or take a couple of days.

### Steps To Reproduce

1. Add a movie to Radarr that was recently added to TMDb, such as tmdb-1106741 "The Motor City Slice" or tmdb-1103772 "Seasons of the Otter"
2. See lots of information missing in Radarr for the added movie

### Environment

```markdown
- OS: Unraid/Slackware
- Radarr: 4.4.4.7035
- Docker Install: Yes - linuxserver.io
- Using Reverse Proxy: Yes
- Browser: Firefox current
- Database: Sqlite 3.40.1
```

### What branch are you running?

Nightly

### Trace Logs?

[radarr.trace.x.txt](https://github.com/Radarr/Radarr/files/11240920/radarr.trace.x.txt)

**Comment by xen0m0rph2020** [comment]
same here
a title got updated on TMDB on 14th but its still not updated in Radarr.

**Comment by Qstick** [comment]
This is being tracked and worked on in another repo for the metadata cache.

**Comment by xen0m0rph2020** [comment]
@Qstick Is there a github page where we can track when the fix is done?

**Comment by benfishbus** [comment]
FYI, the movies I listed above (Motor City Slice and Seasons of the Otter) now have metadata in Radarr, as do some others. But there are still some that do not. Examples:
https://www.themoviedb.org/movie/1108592-the-fallen-fortress
https://www.themoviedb.org/movie/1108595-tamahagane-miracle-steel-of-japanese-swords
https://www.themoviedb.org/movie/1110109-decommissioning-fukushima-2021-ten-years-on-from-the-nuclear-accident

Perhaps coincidentally, these are all TV Movies with only "TV" release dates...

**Comment by bakerboy448** [comment]
Please use one of the support channels: [Reddit](https://www.reddit.com/r/radarr/) or  [Discord](https://radarr.video/discord) for support/questions.

[themoviedb.org/movie/1108592-the-fallen-fortress](https://www.themoviedb.org/movie/1108592-the-fallen-fortress)
[themoviedb.org/movie/1108595-tamahagane-miracle-steel-of-japanese-swords](https://www.themoviedb.org/movie/1108595-tamahagane-miracle-steel-of-japanese-swords)
[themoviedb.org/movie/1110109-decommissioning-fukushima-2021-ten-years-on-from-the-nuclear-accident](https://www.themoviedb.org/movie/1110109-decommissioning-fukushima-2021-ten-years-on-from-the-nuclear-accident)

All three of those were last modified back in early april before any fix was in.
Unless they are modified again, they should be back to normal in a few more days after the cache expires.

Pretty sure Radarr does not use TV release dates - so they will not have a release date accordingly.
