### ISSUE TITLE
Radarr adds movies to activity list that it didn't download

### ISSUE THREAD

**Issue by rschmetzer** [Radarr/Radarr#8346]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

manually add movies to sabnzbd to download without using radarr.  Radarr eventually adds these movies to it's activity queue as 100% downloaded and leaves them there.  Removing them from the queue causes Radarr to delete them from the file system.  These movies were never added to Radarr.

This may happen after movie downloads are completed and a new version of Radarr is installed.

Radarr update performed on 4/15

### Expected Behavior

Movies downloaded without being added to Radarr should never show up in it's activity queue.

### Steps To Reproduce

Download movies independent of Radarr with sabnzbd.
Install Radarr update.

### Environment

```markdown
- OS: Windows 10
- Radarr: Any
- Docker Install: 
- Using Reverse Proxy: 
- Browser: 
- Database:
```

### What branch are you running?

Master

### Trace Logs?

[radarr.txt](https://github.com/Radarr/Radarr/files/11242703/radarr.txt)

**Comment by Qstick** [comment]
If you don't want them to show in Radarr then don't apply Radarr's category in SAB. This is not a bug, it's intentional

**Comment by rschmetzer** [comment]
And Radarr will continue to correctly download movies via Sabnzbd?

**Comment by Qstick** [comment]
Movies that you want Radarr to see = apply Radarr's category
Movies that you don't want Radarr to see = different category

**Comment by rschmetzer** [comment]
Thank you!
