### ISSUE TITLE
nzb in Synology Download Station

### ISSUE THREAD

**Issue by foXaCe** [Radarr/Radarr#836]
@margaale  hello, it possible to add usenet DS Station support like sonarr please ?

**Comment by margaale** [comment]
Sure, the developers should get the commits from sonarr Sonarr/Sonarr@c56c83e169a2fa64579d9986b107a9fd89c429ee

**Comment by onedr0p** [comment]
@margaale I'll add this but can you help maintain? I do not have a Synology to test it out.

**Comment by margaale** [comment]
Sure, i'm already doing it on sonarr...

**Comment by onedr0p** [comment]
Ok I'll have it updated in a few minutes. Thanks!
