### ISSUE TITLE
Documentation for the import list JSON format

### ISSUE THREAD

**Issue by denizdogan** [Radarr/Radarr#8370]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I can't find _any_ documentation on the expected import list JSON format/structure.

### Describe the solution you'd like

I would like _some_ documentation on the expected import list JSON format/structure.

### Describe alternatives you've considered

Not doing what I need to do

### Anything else?

The only thing I've found is "look at the code", but that's not good enough. The code is pretty convoluted, and largely undocumented, and you really shouldn't have to be a programmer to make a list of JSON entries.

**Comment by RobinDadswell** [comment]
All API documentation can be found https://radarr.video/docs/api/#/

**Comment by denizdogan** [comment]
> All API documentation can be found https://radarr.video/docs/api/#/

That's an OpenAPI specification, not documentation. Which one of these endpoints corresponds to the expected import list JSON structure?

**Comment by RobinDadswell** [comment]
I may be missing something, do you mean as in if you were creating an endpoint for radarr to listen to for a list? If so that changes based on which list type you are using (e.g. tmdb goes out to tmdb and uses their schema, stevenlu goes to the stevenlu schema, trakt uses the trakt schema etc.). But if it's a adding a new list (for an existing type) this would done via the importlist endpoints. 

Radarr pulls from lists via api calls. If you are looking to add movies without a 3rd party service you would need to add the movie via the movie endpoints.

**Comment by denizdogan** [comment]
@RobinDadswell Thanks. So just to clarify, what I mean is the thing under "Settings / Lists", where you tap the big "+" button, then choose "Custom Lists", and then I get to enter a list URL at the bottom.

I have a web service which I have developed myself, and I'm able to spit out JSON in any format or structure. Currently it's spitting out things in this format:

```json
[
  {
    "ImdbId": "tt0113247",
    "Title": "La Haine",
    "Overview": "24 hours in the lives of three young men in the French suburbs the day after a violent riot.",
    "Images": [
      {
        "CoverType": "Poster",
        "Url": "https://..."
      }
    ],
    "Genres": ["Drama", "Crime"],
    "MovieRatings": { "Imdb": { "Count": 0, "Value": 8.1, "Type": "User" } }
  },
  {
    "ImdbId": "tt0111161",
    "Title": "The Shawshank Redemption",
    "Overview": "Internationally acclaimed actors Tim Robbins and Morgan Freeman star in a compelling drama of hope, friendship and atonement behind the walls of a maximum security prison in The Shawshank Redemption. From a novella by best-selling author Stephen King comes a poignant tale of the human spirit. Red (Freeman), serving a life sentence, and Andy Dufresne (Robbins), a mild-mannered banker wrongly convicted of murder, forge an unlikely bond that will span more than twenty years. Together they discover hope as the ultimate means of survival. Under horrifying conditions and the ever-present threat of violence, two lifers reclaim their souls and find freedom within their hearts in The Shawshank Redemption.",
    "Images": [
      {
        "CoverType": "Poster",
        "Url": "https://..."
      }
    ],
    "Genres": ["Drama"],
    "MovieRatings": { "Imdb": { "Count": 0, "Value": 9.3, "Type": "User" } }
  }
]
```

When I try to use this with Radarr, the logs get filled with these:

```
2023-04-22 14:45:42.7|Warn|SkyHookProxy|System.InvalidOperationException: Sequence contains no elements

[v4.4.4.7068] System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewMovie(String title) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 500


2023-04-22 14:45:42.7|Warn|SkyHookProxy|Couldn't map movie  to a movie on The Movie DB. It will not be added :(

[v4.4.4.7068] NzbDrone.Core.MetadataSource.SkyHook.SkyHookException: Search for '' failed. Invalid response received from TMDb.
 ---> System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewMovie(String title) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 500
   --- End of inner exception stack trace ---
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewMovie(String title) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 500
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.MapMovieToTmdbMovie(MovieMetadata movie) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 372
```

So this is where my frustration comes from: I don't know anything about what JSON structure Radarr expects from my service.

Which fields are accepted? Which fields are _required_?

Does it require TMDb ID's? Because looking at Steven Lu's famous list, it doesn't provide any TMDb ID's, just IMDb ID's. But then I found this other Radarr-specific URL which seems to use Steven Lu's list as a source, but _also_ has TMDb ID's, and other information: https://api.radarr.video/v1/list/stevenlu

How does any of this work?

**Comment by denizdogan** [comment]
@RobinDadswell I think this should be reopened. I still can't find any documentation on this. There's nothing about custom lists on the wiki as far as I can tell. Radarr itself says "Radarr supports any RSS movie lists as well as the one stated below", but there is no documentation on what an "RSS movie list" is either. You closed this issue linking to the OpenAPI specification, which has nothing to do with this.

**Comment by austinwbest** [comment]
> @RobinDadswell Thanks. So just to clarify, what I mean is the thing under "Settings / Lists", where you tap the big "+" button, then choose "Custom Lists", and then I get to enter a list URL at the bottom.
> 
> I have a web service which I have developed myself, and I'm able to spit out JSON in any format or structure. Currently it's spitting out things in this format:
> 
> ```json
> [
>   {
>     "ImdbId": "tt0113247",
>     "Title": "La Haine",
>     "Overview": "24 hours in the lives of three young men in the French suburbs the day after a violent riot.",
>     "Images": [
>       {
>         "CoverType": "Poster",
>         "Url": "https://..."
>       }
>     ],
>     "Genres": ["Drama", "Crime"],
>     "MovieRatings": { "Imdb": { "Count": 0, "Value": 8.1, "Type": "User" } }
>   },
>   {
>     "ImdbId": "tt0111161",
>     "Title": "The Shawshank Redemption",
>     "Overview": "Internationally acclaimed actors Tim Robbins and Morgan Freeman star in a compelling drama of hope, friendship and atonement behind the walls of a maximum security prison in The Shawshank Redemption. From a novella by best-selling author Stephen King comes a poignant tale of the human spirit. Red (Freeman), serving a life sentence, and Andy Dufresne (Robbins), a mild-mannered banker wrongly convicted of murder, forge an unlikely bond that will span more than twenty years. Together they discover hope as the ultimate means of survival. Under horrifying conditions and the ever-present threat of violence, two lifers reclaim their souls and find freedom within their hearts in The Shawshank Redemption.",
>     "Images": [
>       {
>         "CoverType": "Poster",
>         "Url": "https://..."
>       }
>     ],
>     "Genres": ["Drama"],
>     "MovieRatings": { "Imdb": { "Count": 0, "Value": 9.3, "Type": "User" } }
>   }
> ]
> ```
> 
> When I try to use this with Radarr, the logs get filled with these:
> 
> ```
> 2023-04-22 14:45:42.7|Warn|SkyHookProxy|System.InvalidOperationException: Sequence contains no elements
> 
> [v4.4.4.7068] System.InvalidOperationException: Sequence contains no elements
>    at System.Linq.ThrowHelper.ThrowNoElementsException()
>    at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
>    at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewMovie(String title) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 500
> 
> 
> 2023-04-22 14:45:42.7|Warn|SkyHookProxy|Couldn't map movie  to a movie on The Movie DB. It will not be added :(
> 
> [v4.4.4.7068] NzbDrone.Core.MetadataSource.SkyHook.SkyHookException: Search for '' failed. Invalid response received from TMDb.
>  ---> System.InvalidOperationException: Sequence contains no elements
>    at System.Linq.ThrowHelper.ThrowNoElementsException()
>    at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
>    at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewMovie(String title) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 500
>    --- End of inner exception stack trace ---
>    at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewMovie(String title) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 500
>    at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.MapMovieToTmdbMovie(MovieMetadata movie) in D:\a\1\s\src\NzbDrone.Core\MetadataSource\SkyHook\SkyHookProxy.cs:line 372
> ```
> 
> So this is where my frustration comes from: I don't know anything about what JSON structure Radarr expects from my service.
> 
> Which fields are accepted? Which fields are _required_?
> 
> Does it require TMDb ID's? Because looking at Steven Lu's famous list, it doesn't provide any TMDb ID's, just IMDb ID's. But then I found this other Radarr-specific URL which seems to use Steven Lu's list as a source, but _also_ has TMDb ID's, and other information: https://api.radarr.video/v1/list/stevenlu
> 
> How does any of this work?

Here is a simple example to get you going. This format is either a `Custom List` or `Steven Lu List` as i dont recall off hand. There is not a lot of documentation around the lists and their formats or examples.

```
[
    {
        "title": "Weird: The Al Yankovic Story",
        "poster_path": "https://notifiarr.com/images/posters/2/928344_poster.jpg",
        "imdb": "tt17076046",
        "tmdb": "928344"
    },
    {
        "title": "Ant-Man and the Wasp: Quantumania",
        "poster_path": "https://notifiarr.com/images/posters/2/928344_poster.jpg",
        "imdb": "tt10954600",
        "tmdb": "640146"
    },
    {
        "title": "Shin Ultraman",
        "poster_path": "https://notifiarr.com/images/posters/2/928344_poster.jpg",
        "imdb": "tt10737918",
        "tmdb": "634429"
    },
```

**Comment by Qstick** [comment]
Documentation Issues can be tracked here. Feel free to open an issue here

<https://github.com/Servarr/Wiki/issues>
