### ISSUE TITLE
using debian 12 testing    with only cinnamon desktop and debian utilities        radarr will not run properly

### ISSUE THREAD

**Issue by tostane** [Radarr/Radarr#8390]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

when startning radarr page after page of errors happen      

I then installed gnome  and     and uninstalled it

after that then radarr will start.   why do I have to install gnome to get radar to run on cinnamon desktop ?

### Expected Behavior

wanted it to run like radarr 3 did

### Steps To Reproduce

install debian 12 testing  at tasksel  stage   uncheck gnome and check cinnamon.
hold down shift while it boots to get to root and create a sudo user
reboot 
install radarr as per instructions on the support page
start radarr      it will give pages of errors

run tasksel install gnome   reboot start gnome        start tasksel remove gnome
start cinnamon
start radar        now it will start

### Environment

```markdown
- OS: debian 12 testing
- Radarr: 4 latest beta
- Docker Install: no
- Using Reverse Proxy: no
- Browser: fox
- Database: usual
```

### What branch are you running?

Develop

### Trace Logs?

varies

**Comment by bakerboy448** [comment]
- bug report is not valid and the required information wasn't provided
- Logs / journal output are required

> reboot
> install radarr as per instructions on the support page
> start radarr it will give pages of errors

there's a wiki is install page, not support a support page  https://wiki.servarr.com/radarr/installation#debian-ubuntu-hands-on-install

most likely the instructions were not fully followed, prerequisite packages missing, or prerequisites (orange box) not met

regardless, more of a support issue than a bug given you've confirmed it does run a Debian 12

**Comment by tostane** [comment]
im on my third try installing totally the os debian 12  and radar from
scratch following the instructions      i erase and reinstall
 so explain that
