### ISSUE TITLE
Check For Finished Download interval?

### ISSUE THREAD

**Issue by darknessgp** [Radarr/Radarr#840]
**Description:**

I see that the Check For Finished Download task has an interval of "1 few seconds" and seem to basically be constantly running because of that, with it eating up cpu cycles for no good reason. I also know that Sonarr has it defaulted to 1 minute... Ideally, I'd love to be able to customize all of these task intervals. but baring that, 1 second is too much.

**Comment by galli-leo** [comment]
It's actually 30 seconds. The ui just cannot display it correctly.

**Comment by galli-leo** [comment]
I still want to have an option to set the interval.

**Comment by darknessgp** [comment]
I'm going to bump this from going stale, as we cannot currently customize the interval.

**Comment by mynameisfiber** [comment]
I would love to see this feature. Currently, every 30 seconds I see CPU usage from radarr jump to 100% as these checks complete. I'd be more than happy to have this complete every 5 minutes to reduce CPU use (although it seems that radarr can be smarter in what it checks since 100% of the items in my downloader are completed and don't need to be checked anymore).

![image](https://user-images.githubusercontent.com/47370/38097004-3fd6f5da-3342-11e8-975d-9472f812c697.png)

**Comment by galli-leo** [comment]
@mynameisfiber Hmm that seems bad, do you have that in Sonarr as well? (Just in a lower frequency). Also I just checked the code, most of the logic should be cached, so not sure why you get such a spike.

**Comment by mynameisfiber** [comment]
@galli-leo Yea... I do have sonarr but it's utilization is much less aggressive (granted, I remove those items from my download client a lot sooner than for radarr where I try to seed as long as possible). Radarr seems to have 150 things "active" (although they are _all_ seeding), while sonarr only has 3 active.

![image](https://user-images.githubusercontent.com/47370/38102767-3efd9bea-3352-11e8-847b-175cd67eac06.png)

**Comment by galli-leo** [comment]
@mynameisfiber Can you try moving about half of the Radarr items to a different label?

**Comment by galli-leo** [comment]
@mynameisfiber Your download client has different labels (or categories) for different items. For example, radarr might have the movies label (or category). Try changing all items from the Radarr label to a new one.

**Comment by mynameisfiber** [comment]
@galli-leo sorry for the delay. What I did was change the default category for my downloader in radarr that way all the existing things in the client don't get found (I couldn't find a way to change the category for existing downloads). This removed all of the 150 active items in radar and changed the CPU use quite a lot (can you see in the screenshot when I changed the label? :))

![image](https://user-images.githubusercontent.com/47370/38507267-1a6996ee-3bea-11e8-9c43-effe15fc314f.png)

I do think though that this issue still needs resolution... the number of things in radarr's activity is just going to grow again. Being able to change the check interval would be one way of at least reducing the effective CPU use and let my system to into idle.

**Comment by blkhwk0833** [comment]
Still an issue .

**Comment by blkhwk0833** [comment]
Really need to be able to change .

**Comment by oleroc** [comment]
I second this, must be able to change..

**Comment by Thatindianbruh** [comment]
Would be a great addition especially for lowering cpu utilization and drive run times.

**Comment by broizter** [comment]
Still an issue.

**Comment by timekills** [comment]
I'll add my name to the list.

**Comment by galli-leo** [comment]
On the latest develop release the interval was reset to Sonarr‘s original value (1 minute)

**Comment by broizter** [comment]
Big improvement now that it's only 1 minute, but the CPU spike still seems a bit excessive. I would love if there was either an option to disable the check (since I have no use for it personally) or to modify the timer easily from the gui.

**Comment by scrouchman** [comment]
How is this not a thing? Every other client I use I can configure this. I have a 5bay nas and this stops the disks ever spinning down. Am I forced to download the source and change this myself?

**Comment by Qstick** [comment]
That’s the beauty of open source, you can do that and change whatever you wish! Go for it!

I don’t quite understand how Radarr talking to your download client every minute is stopping all 5 disks from spinning down?

Radarr only scans your actual stored movie files once a day. And only scans your download directory if you have dronefolder setup (not recommended) or if your download client says something is finished and ready to move.

**Comment by scrouchman** [comment]
PR opened
https://github.com/Radarr/Radarr/pull/3233

**Comment by scrouchman** [comment]
Bumping this as its not stale, I have an open pr to fix it

**Comment by Bau250** [comment]
Mind=blown this isn’t a feature.  My array is constantly spinning

**Comment by scrouchman** [comment]
Don't assume it's this thats keeping your array awake. For me I use deluge for torrents, that writes a file every 3 minutes even if everything is paused. To get round that I have a script for stopping and starting it.
The problem radarr has is it runs this check every minute and if deluge isn't running it logs an error
