### ISSUE TITLE
Radarr renaming movie files despite "Rename Movies" = disabled

### ISSUE THREAD

**Issue by coryallegory** [Radarr/Radarr#8403]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Possibly a regression of an issue from 5+ years ago https://github.com/Radarr/Radarr/issues/2089

Radarr is renaming movie files to match torrent names upon Import, even though `Settings > Media Management > Movie Naming > Rename Movies` is unchecked.

As mentioned in the previous issue linked above, I only noticed it affecting YTS torrents, BUT this is because some of those torrents are named "Movie (Year)" rather than having a name more closely matching the movie filename as with many other movie torrents.

### Expected Behavior

I am expecting Radarr to import movie files without renaming any filenames.

### Steps To Reproduce

- Configure Radarr not to rename files.
- Add a new movie to Radarr
- Search for the movie and add it to qbittorrent via Radarr
- In qbittorrent, rename the torrent to "Movie (Year)"
- Wait for the download to finish, and for Radarr to automatically import the movie file.
- Notice that the imported movie filename has been renamed to match the torrent name, rather than the original filename as downloaded.

### Environment

```markdown
- OS: see docker below (alpine)
- Radarr: 4.4.4.7068
- Docker Install:  Yes, linuxserver/radarr:4.4.4
- Using Reverse Proxy: Yes, k8s environment, nginx ingress controller
- Browser: Chrome Version 112.0.5615.138 (Official Build) (64-bit)
- Database: Postgres 15.1
```

### What branch are you running?

Master

### Trace Logs?

Logs show working with the cinematic masterpiece The Sentinel (2007), as this is unlikely to be in tester's existing db when replicating.

![torrent](https://user-images.githubusercontent.com/658220/235269838-6c0c7ce2-0e63-4f40-9297-83220e88c8cf.png)

```
2023-04-28 18:28:29.0|Debug|DiskScanService|Scanning '/downloads/The Last Sentinel (2007) [720p] [BluRay] [YTS.MX]' for video files
2023-04-28 18:28:29.1|Trace|EventAggregator|HealthCheckCompleteEvent <- HealthController
2023-04-28 18:28:29.1|Trace|Http|Req: 4930 [GET] /api/v3/health (from 10.244.2.0 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36)
2023-04-28 18:28:29.1|Trace|DiskScanService|2 files were found in /downloads/The Last Sentinel (2007) [720p] [BluRay] [YTS.MX]
2023-04-28 18:28:29.1|Trace|EventAggregator|HealthCheckCompleteEvent ~> NotificationService
2023-04-28 18:28:29.1|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was successfully authenticated.
2023-04-28 18:28:29.1|Trace|EventAggregator|HealthCheckCompleteEvent <~ NotificationService
2023-04-28 18:28:29.1|Debug|DiskScanService|0 video files were found in /downloads/The Last Sentinel (2007) [720p] [BluRay] [YTS.MX]
2023-04-28 18:28:29.2|Trace|Http|Res: 4930 [GET] /api/v3/health: 200.OK (77 ms)
2023-04-28 18:28:29.2|Debug|DownloadedMovieImportService|Deleting folder after importing valid files
2023-04-28 18:28:29.2|Debug|Api|[GET] /api/v3/health: 200.OK (77 ms)
2023-04-28 18:28:29.5|Debug|CompletedDownloadService|All movies were imported for The Last Sentinel (2007)
2023-04-28 18:28:29.5|Trace|EventAggregator|Publishing DownloadCompletedEvent
```

![radarr](https://user-images.githubusercontent.com/658220/235269842-0286b944-4bd6-4a24-9c85-bcf0d51f85e9.png)

**Comment by bakerboy448** [comment]
Logs provided are after the import occurs and do not capture nor show the issue

**Comment by coryallegory** [comment]
Thanks for looking at this (current filepaths are good enough for my use case, they make use of network shares so not concerned about speed or keeping any files in-place/in-system).

I've re-run the replication flow using The Cat Creeps (1946). Filename as downloaded is `The.Cat.Creeps.1946.720p.BluRay.x264.AAC-[YTS.MX].mp4` although Radarr ultimately imports it as `The Cat Creeps (1946).mp4`.

`2023-04-29 11:52:17.4|Debug|MovieFileMovingService|Moving movie file: /downloads/The Cat Creeps (1946) [720p] [BluRay] [YTS.MX]/The.Cat.Creeps.1946.720p.BluRay.x264.AAC-[YTS.MX].mp4 to /movies/The.Cat.Creeps.(1946)/The Cat Creeps (1946).mp4`

More complete logs attached,

[catcreeps.trace.log](https://github.com/Radarr/Radarr/files/11359680/catcreeps.trace.log)

**Comment by bakerboy448** [comment]
debugging notes:

SceneName seems to be 1) populated for a non-scene name and 2) seems to be the torrent name/title in client
![image](https://user-images.githubusercontent.com/55419169/235317284-4c2625ca-7463-4ac3-8937-ef84d7aac733.png)

**Comment by bakerboy448** [comment]
- Radarr is not renaming anything and is working as designed
- The Download Client Release Title is used for naming when renaming is disabled
https://github.com/Radarr/Radarr/blob/c6bb5024bc16c4983f5943f460ad36db958d49d4/src/NzbDrone.Core/MediaFiles/MovieImport/SceneNameCalculator.cs#L15-L17

https://wiki.servarr.com/radarr/settings#original
- If you want the original file name then enable renaming and use that token
- If you want the original release title then enable renaming and use that token

Radarr docs updated to clarify this

```md
- Rename Movies - If unchecked, Radarr will use the existing name if renaming is disabled
  - If unchecked:
    - Download Client Import
      - Download Client's Release Title is used
    - Manual (Ad-Hoc) Import: Original File Name
 ```

**Comment by coryallegory** [comment]
@bakerboy448 the in-app config text reads as "Radarr will use the existing file name if renaming is disabled". I think at some point the implementation must have been changed. But regardless, if the code isn't to be changed that UI text should be updated.

Much thanks for diving into this for me, it is appreciated
