### ISSUE TITLE
Cannot import all movies

### ISSUE THREAD

**Issue by jaydavies** [Radarr/Radarr#842]
Hi, 

I have an issues that I have had from the start (About 3 weeks now) I cannot import all of my movies. I have 311 movies and about half of them can be imported. The rest say that the file cannot be found. I have attached screenshot of what it says. The movie files are defiantly there.

All movies are on the same drive. I have checked permissions and the movies that import have the same permissions as the movies that don't work. I also tried to import movies with the full path name \\server....\movies etc, no luck there either. 

I am not having this issues when I have recently downloaded a movie, just movies that I am trying to import. 

Love your work, so hoping you can solve this one :)

Radarr Ver. 0.2.0.375

Logs say this:

ParsingService	Unable to parse movie info from path Y:\Movies\Arthur Christmas\Arthur Christmas 1080p.mkv	10:39am
ParsingService	Unable to parse movie info from path Y:\Movies\Ant-Man\Ant-Man 1080p.mkv	10:39am
ParsingService	Unable to parse movie info from path Y:\Movies\Angry Birds Movie, The\Angry Birds Movie.mkv	10:39am
ParsingService	Unable to parse movie info from path Y:\Movies\Alice Through the Looking Glass\Alice Through the Looking Glass BR-Disk.mkv	10:39am
ParsingService	Unable to parse movie info from path Y:\Movies\33, The\The 33 BR-Disk.mkv	10:39am
ParsingService	Unable to parse movie info from path Y:\Movies\2 Fast 2 Furious\2 Fast 2 Furious BR-Disk.mkv	10:39am
DiskScanService	Completed scanning disk for 13 Hours: The Secret Soldiers of Benghazi	10:27am
ParsingService	Unable to parse movie info from path Y:\Movies\13 Hours The Secret Soldiers of Benghazi\13 Hours The Secret Soldiers of Benghazi.mkv

![movie1](https://cloud.githubusercontent.com/assets/25497449/23238683/3606d234-f9b7-11e6-8d46-69083156ebaa.PNG)
![movie](https://cloud.githubusercontent.com/assets/25497449/23238685/3625e80e-f9b7-11e6-8850-0905e90d1145.PNG)

**Comment by fedoranimus** [comment]
If you add the year to the movie file, does it work?

**Comment by dhaos21** [comment]
I think its more to do with having unrecognised profiles in the filename, example i have some files that was downloaded by couchpotato and had a profile of BR-Rip added to the title but because i dont have the same profile in radarr it cant parse it. so in Jay's case, it looks like the files with lack of a profile in the filename are returning parsing errors.

**Comment by jaydavies** [comment]
@fedoranimus Yes actually, I added the year to the movie it did recognise the file and imported successfully. Looks like I will be doing a manual change of the folder and movie file names!!! Yuck.......
