### ISSUE TITLE
Error when loading or creating profiles

### ISSUE THREAD

**Issue by she11sh0cked** [Radarr/Radarr#8420]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I'm getting a minified error whenever I click on a profile or the "create new" button. (see below)

### Expected Behavior

It should show the profile editor

### Environment

```markdown
- OS: Ubuntu 22.04.2
- Radarr: 4.5.1.7132-ls463 by linuxserver.io 
- Docker Install: Yes
- Using Reverse Proxy: Yes (Traefik)
- Browser: Firefox 112.0.2
- Database: Sqlite 3.40.1
```

### What branch are you running?

Nightly

### Trace Logs?

https://gist.github.com/she11sh0cked/8257450423ce1f5b35dafee208e2489f

![image](https://user-images.githubusercontent.com/22623152/235357750-9f24df68-2cef-472e-b9c6-4a4b4129b0b7.png)

**Comment by Qstick** [comment]
Already fixed by https://github.com/Radarr/Radarr/commit/d32582fa7c8fae1d7a32b2ce6a35737fa2628018
