### ISSUE TITLE
Edit Selected Movies popup shows 1 Selected when many are selected

### ISSUE THREAD

**Issue by netheadplurk** [Radarr/Radarr#8423]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

on the overly large Edit Selected Movies pop-up, "1 Movie(s) Selected" text is shown in bottom left corner, but in fact (in this latest case) 131 Movies are selected

### Expected Behavior

the text should say '131 Movie(s) Selected"

### Steps To Reproduce

latest nightly build 4.5.1.7163
in filter view, select all films (131 films), click on Edit (bottom left), text at bottom left displays "1 Movie(s) Selected"

### Environment

```markdown
- OS: Windows 
- Radarr: 4.5.1.7163
- Docker Install: 
- Using Reverse Proxy: 
- Browser: Edge/Chrome/Brave/Firefox
- Database:
```

### What branch are you running?

Nightly

### Trace Logs?

turned on trace; didn't see anything in the trace that was related to the edit movie/select movie

**Comment by bakerboy448** [comment]
![image](https://user-images.githubusercontent.com/55419169/235380740-f7911f9d-002e-48cd-b7e2-c394054eb238.png)

https://discord.com/channels/264387956343570434/264388019585286144/1102357973784871042

https://discord.com/channels/264387956343570434/264388019585286144/1102108999987499119

**Comment by Qstick** [comment]
For clarity this seems to happen with `Select All`. Thanks for the GHI

**Comment by netheadplurk** [comment]
Also happens when sorted by year and having selected a group using the check boxes (common action that was working before the new edit interface change)
