### ISSUE TITLE
Manual Import of Movies just spins forever when attempting to enumerate movie list

### ISSUE THREAD

**Issue by edrock200** [Radarr/Radarr#8425]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When manually importing a movie, when the file name window opens, then clicking movie to match it, the movie list enumeration just spins with no movies ever populating.

### Expected Behavior

Movies populate so you can select one

### Steps To Reproduce

1. Go to Movies.
2. Click "Manual Import"
3. Select a folder with a movie file within
4. Click Interactive Import
5. To the right of the filename, click "Movie" to match the file with a movie.
6. In the next window where movies are supposed to be listed, the window will just spin forever. I've left it here for up to 10m without anything changing.

### Environment

```markdown
- OS: Ubuntu 18.04
- Radarr: I have tried with 4.5.1.7166 and 4.5.1.7171
- Docker Install: linuxserver.io nightly container
- Using Reverse Proxy: Yes, nginx + ssl
- Browser: Chrome 64 bit
- Database: Sqlite 3.40.1
```

### What branch are you running?

Nightly

### Trace Logs?
[radarr.trace.submit.txt](https://github.com/Radarr/Radarr/files/11366348/radarr.trace.submit.txt)

In the trace log, I attemped to use a 20/20 episode file for manual import (I know it's not a movie, but it was readily available in my temp folder to reproduce the issue.)

**Comment by bakerboy448** [comment]
Regression from https://github.com/Radarr/Radarr/commit/e0b91c6406f1587ac6e8aef6522b2fc495561245

Console Error
```
Warrning: React does not recognize the `registerScroller` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `registerscroller` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

Per q - needs to tweak some things from the scroller rework in the mentioned commit
