### ISSUE TITLE
Snatching UFC events

### ISSUE THREAD

**Issue by deldran** [Radarr/Radarr#843]
**Description:**

Radarr and couch potato do not handle automatic downloads of UFC events very well at all.  Currently I am asking it to find UFC192.  I know it exists on my tracker.  I use jackett to index my torrent tracker.
When I manually search jackett it does return several items.

I am more than happy to help test this in any way.  If we could get Radarr to search and pull UFC events it would be epic imho.

**Radarr Version:**
0.2.0.299
**Logs:**

Here is the output from the log.  If I need to turn additional logging or something on please let me know.

`17-2-22 16:47:39.9|Info|NzbSearchService|Searching 1 indexers for [UFC 192: Cormier vs. Gustafsson]
17-2-22 16:47:40.9|Info|DownloadDecisionMaker|No results found`

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by onedr0p** [comment]
Isn't UFC considered series and should be handled by sonarr?

**Comment by deldran** [comment]
It's categorized as "TV Sport" but it appears the MovieDB has all the info on the UFC events.
I have tried sonarr as well and that is a no go.  The TV DB does not have any info about the events, so you cannot even add "UFC 192" to sonarr.

**Comment by onedr0p** [comment]
I don't know if we plan on adding TV sports functionality, definitely  sounds like you need to handle it manually...

**Comment by onedr0p** [comment]
Related https://github.com/Radarr/Radarr/issues/771

**Comment by deldran** [comment]
Im not sure why this was closed so quickly.  I surely cannot be the only person that would like to have this kind of thing automated.  What would it take to just allow radarr to search TV Sports category?  This is something that is currently not offered by anyone.

I am more than happy to test this or help in any way.

**Comment by onedr0p** [comment]
I closed it because it is a duplicate to issue #771

**Comment by onedr0p** [comment]
Please discuss there with anymore information you would like to add.

**Comment by Dudleydogg** [comment]
I can Add them via List with IMDB and even a list from nzbgeeks, and it will ADD the show to Radarr, but it just stays "Not Downloaded" if you manually search it does not find files.
Then I just go grab the NZB and do a manual import, and you have to specify the Exact name of the movie to import.  so its like it just has trouble scraping the name and associating with the NZB

**Comment by davidjmorin** [comment]
Im gonna post in this old thread as well.  Would love this ability.

**Comment by Dudleydogg** [comment]
would be nice every week i have to go find the UFC for my brother even though its listed in my Radarr.

**Comment by onedr0p** [comment]
I standby my thoughts 3 years ago and really think this is something that needs to be managed by Sonarr.

Has anyone tried? I see a bunch of UFC related things on TVDB...
