### ISSUE TITLE
Upgrades blocked: `UpgradeSpecification` error

### ISSUE THREAD

**Issue by owine** [Radarr/Radarr#8431]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

All upgrades are blocked and stuck in the queue with the error `UpgradeSpecification: Object reference not set to an instance of an object.`

### Expected Behavior

Upgrades processed properly, no error

### Steps To Reproduce

Download movie
Download "upgrade" for same movie either manually or automatically
Let parser work
Observe error

### Environment

```markdown
- OS: Ubuntu 22.04
- Radarr: 4.5.1.7174
- Docker Install: Yes, hotio
- Using Reverse Proxy: Yes
- Browser: Chromium
- Database: PG
```

### What branch are you running?

Master

### Trace Logs?

https://privatebin.net/?17bf1ad13e792e51#6MjapFr5ouQ5P4eCVgmJGhUEg1d7vWR7s6Afx4wSL5KV

**Comment by bakerboy448** [comment]
presumable regression from https://github.com/Radarr/Radarr/commit/44bec71752af0829d7dca7461dc9b03cdd2e1b89
