### ISSUE TITLE
Request: Please allow MPAA rating tagging in folder and file names. e.g, G, PG, PG-13, R, NR.

### ISSUE THREAD

**Issue by Ascendin81** [Radarr/Radarr#844]
Please allow MPAA rating tagging in folder and file names. e.g, G, PG, PG-13, R, NR.

**Comment by onedr0p** [comment]
Once folder renaming is working, then we can add that.

**Comment by onedr0p** [comment]
On feathub http://feathub.com/Radarr/Radarr/+100

**Comment by TNosredna** [comment]
Did this ever get added?  If so, how to reference it in the renamer?

**Comment by fryfrog** [comment]
No.
