### ISSUE TITLE
Mobile - Scrolling on Movie Index in Edit clears selected

### ISSUE THREAD

**Issue by bakerboy448** [Radarr/Radarr#8446]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Movie Index => Table Mode => enable movie editor and select movies => scroll => selections are cleared

### Expected Behavior

Selections should not be cleared

### Steps To Reproduce

See above

### Environment

```markdown
- OS: agnostic
- Radarr: 4.5.1.7194
- Docker Install: agnostic
- Using Reverse Proxy: Yes
- Browser: chrome iOS 112.0.5615.167
- Database: agnostic
```

### What branch are you running?

Nightly

### Trace Logs?

N/A UI
Non-issue on Sonarr 4.0.0.471

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have followed the steps in the wiki link above and provided the required trace logs that are relevant and show this issue.

**Comment by edrock200** [comment]
I had opened a similar ticket for sonarr and was resolved. Not sure if it can be borrowed. 
https://github.com/Sonarr/Sonarr/issues/5539
