### ISSUE TITLE
Start/stop the download manager automaticaly

### ISSUE THREAD

**Issue by killo3967** [Radarr/Radarr#8455]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I don't want that my download manager works 24x7

### Describe the solution you'd like

Start/stop the download manager automaticaly, when it was configured in the Indexer and a checkbox (new one) is checked. 

Also if this condition, the checkbox,  is set, then do not assume that, if the download manager is stopped, is an error. 

### Describe alternatives you've considered

I have a powwershell scripts that do the same but i think this is not the proper solution

### Anything else?

Nothing else

**Comment by bakerboy448** [comment]
No plans for Starr to control starting and stopping your download client.

Most if not all supported download clients already have a native scheduling feature - if yours does not then request it with your client's development team or switch clients.
