### ISSUE TITLE
Manual Import: Add ID Data to Movie Picker

### ISSUE THREAD

**Issue by owine** [Radarr/Radarr#8483]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Radarr now identifies when an import was blocked due to matching multiple movies. This is good! The rejection gives IMDb and TMDb values for each movie. One can browse to the movies manually to identify which may be the correct match. When manually importing the movie, the picker simply shows `Title (Year)` and not necessarily in the order the search bar would for instance. This makes it difficult to associate with the correct movie.

### Describe the solution you'd like

Add additional movie data to the movie picker for manual import in order to have additional data points to match against.

### Describe alternatives you've considered

Yelling at baker every time.

### Anything else?

You don't wanna know

**Comment by Qstick** [comment]
> Yelling at baker every time.

I'm fine with this alternative.
