### ISSUE TITLE
Title with numbers sorted wrong

### ISSUE THREAD

**Issue by jmartensson** [Radarr/Radarr#849]
**Description:**

When sorting the movie list by title, movies with numbers is sorted wrong. 

**Radarr Version:**

0.2.0.386

**Logs:**

![image](https://cloud.githubusercontent.com/assets/9382342/23261356/218f2832-f9d6-11e6-8357-e208e727878a.png)

**Comment by onedr0p** [comment]
1 comes before 9 ;) Programming humor.

**Comment by galli-leo** [comment]
@onedr0p It would be two (because binary). But It makes sense, as it's just a text comparison, so 10 comes before 9. I will look, if I can change something about that.

**Comment by onedr0p** [comment]
Fixed in v3
