### ISSUE TITLE
Add Tags to all movies if adding a collection

### ISSUE THREAD

**Issue by PartTheSeas** [Radarr/Radarr#8492]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I'm not sure if it is intended or not, but I see it more as a "feature" request or functionality request and not as a bug.

If you add a single movie to the database from the search field and select "movie & collection" as monitoring status, the tags you select for that specific item are not applied to the other movies that are added from that collection

### Describe the solution you'd like

If adding any movie with/as a collection, apply the selected tags to all movies of that collection, rather than just to the one you added from the search field

### Describe alternatives you've considered

Alternative is to add the desired tags 1 by 1 to each movie of the collection manually

### Anything else?

Nope =) Let me know if the current behaviour is intended, then all is fine <3

**Comment by fryfrog** [comment]
I think OP means tags in most of the places they say CFs. It probably does make sense to apply tags set there to all of them in the collection. I've asked them to edit the original issue.

**Comment by PartTheSeas** [comment]
Hey there guys, yes, very sorry! Of course I mean tags, not CFs :see_no_evil: 
Corrected it in the OP

**Comment by ricci2511** [comment]
I'm looking into this now, hopefully I will do a pr for this soon.
