### ISSUE TITLE
Bulk Import incorrect match against existing movie

### ISSUE THREAD

**Issue by imatt9959** [Radarr/Radarr#850]
Trying to add the final movies by bulk import and it has matched some movies incorrectly. The movies it has matched have already been added to Radarr so the checkbox is grayed out.

However when I manually add the Tmdb ID and it finds the movie the checkbox is still grayed out. These new matches are not in the movie library.

A solution that seems to work is deleting the incorrectly matched movie from the library, then re-searching and updating the incorrectly matched tmdb id and it then will let you add it.

https://gyazo.com/d0cf0fc945bf68b4c24e038a43ca36d3
https://gyazo.com/0982d8a3b3eb6d67c7a671dfcf027e83
https://gyazo.com/4d3ecd7e4bb60ce78d9536c66ef5a6ee
https://gyazo.com/9305e5081e132cb24ebde43763e0a3c1

Radarr Ver. 0.2.0.385
nightly

**Comment by jpborjas** [comment]
The suggested workaround of deleting and re-adding the single movie from the folder doesn't work for me, because I just can't see any movie files anymore, just the folder that contain them.

**Comment by galli-leo** [comment]
This is fixed now.
