### ISSUE TITLE
Unable to Import Any Movies from any directory

### ISSUE THREAD

**Issue by hematic** [Radarr/Radarr#851]
Fresh Install.
Have multiple local folders with [movies.](http://imgur.com/a/b02wa)
Movie titles include dates.
Radarr Version 0.2.0.375

When importing i get the following displayed : "Loading search results from TheTVDB for your movies, this may take a few minutes."

However no matter how many hours i wait nothing happens.

Log [Paste Bin](http://pastebin.com/z4wcPJAQ)

**Comment by fedoranimus** [comment]
Radarr does not support a flat list of movies. Each movie needs to be a `/movie name (year)/` directory.
