### ISSUE TITLE
Movie Editor - Unmonitored

### ISSUE THREAD

**Issue by Fiala06** [Radarr/Radarr#852]
Using Movie Editor and trying to change all my movies to unmonitored isn't working. If I select only 1 or 2 movies it works. Anything over 2 and I click save it does nothing.

Radarr Ver. 0.2.0.375

**Logs:**
Nothing in the logs except a bunch of File C:\ProgramData\Radarr\MediaCover\196\poster.jpg not found.
[radarr.txt](https://github.com/Radarr/Radarr/files/797070/radarr.txt)

**Comment by Ascendin81** [comment]
Make sure you are extracting the zip file into "ProgramData/Radarr/Bin"  not "ProgramData/Radarr".  This fixed my issue, also with updating, but would be nice to pick a folder on another drive than my boot drive for poster and meta data.

**Comment by Fiala06** [comment]
Where is the setting to change that dir?

In System > Status mine says

AppData directory:    C:\ProgramData\Radarr
Startup directory:      C:\Radarr

**Comment by Ascendin81** [comment]
You manually make the bin folder, extract zip into it, and run .exe from inside the bin folder.

**Comment by Fiala06** [comment]
Figured it out the issue with bulk editing movies and setting them to unmonitored. I had to select all movies, then browse through the whole list and uncheck any that haven't downloaded yet. Then once I clicked save it registered.
