### ISSUE TITLE
Radarr: Indexer Flag Not Displaying Custom Format Label Or Adding Score

### ISSUE THREAD

**Issue by RyanAStrouse** [Radarr/Radarr#8524]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When searching for a movie the indexer flag does not contain golden (when using PTP they tag their highest quality as Golden)
![image](https://github.com/Radarr/Radarr/assets/4588529/b2a4bf8b-dae3-4499-bee5-a004ad634492)
Also notice there is no High Quality flag either, hopefully around the same issue both can be fixed.

Unrelated to Radarr, but performing the search query on Prowlarr it does show a flag coming back from the indexer. Also, note the high quality flag.
![image](https://github.com/Radarr/Radarr/assets/4588529/fd45e391-8b83-4ed4-af9f-34fca37fcd04)

### Expected Behavior

Indexer search result should show flags for Golden and PTP Approved and display the tags appropriately (along with performing the appropriate math to calculate the custom score).

### Steps To Reproduce

Search for a movie from the PTP indexer that has results of Golden or PTP Approved.

When using custom formats configured for those flags, notice the search results do not display those in the Formats column OR in the indexer flag column.

### Environment

```markdown
- OS: Ubuntu 22.04.02
- Radarr: Version 4.4.3.7030
- Docker Install: Package Version nightly-00020ba by hotio
- Using Reverse Proxy: No
- Browser: Chrome
- Database: Sqlite 3.38.5
```

### What branch are you running?

Nightly

### Trace Logs?

![image](https://github.com/Radarr/Radarr/assets/4588529/ad885d28-8306-4d56-8987-ca2b2547dde2)

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have followed the steps in the wiki link above and provided the required trace logs that are relevant and show this issue.

**Comment by bakerboy448** [comment]
Not a bug; Torznab does not support the flags

See https://github.com/Radarr/Radarr/issues/6268

**Comment by RyanAStrouse** [comment]
> Not a bug; Torznab does not support the flags
> 
> See #6268 for the feature request
> 
> Also duplicate of #7951

Well shoot, thank you for providing updated information!
