### ISSUE TITLE
Radarr with large amount of movies won't load on iPhone 13/14 Pro Max

### ISSUE THREAD

**Issue by edrock200** [Radarr/Radarr#8526]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Ever since the release which incorporated this fix:
https://github.com/Radarr/Radarr/issues/8425
Radarr will not load on iPhone 13 Pro Max or 14 Pro Max in Safari, Chrome or Firefox. 

It will start to load, then as it's loading, it will refresh and start loading all over again, and gets stuck in this loop.

### Expected Behavior

Radarr loads properly

### Steps To Reproduce

1. Have a radarr instance with 50k+ movie entries
2. Attempt to access it from an iphone

### Environment

```markdown
- OS: Ubuntu 18.04
- Radarr: 4.5.2.7294
- Docker Install: hotio develop container
- Using Reverse Proxy: nginx/ssl
- Browser: iPhone Safari/Chrome/Firefox
- Database: Sqlite 3.40.1
```

### What branch are you running?

Develop

### Trace Logs?

[radarr.trace (1).txt](https://github.com/Radarr/Radarr/files/11489087/radarr.trace.1.txt)

Since this release, radarr seems to be consuming more RAM, even on the client end. I suspect this might be part of the issue as it does load on a Samsung Galaxy and iPad Pro, both of which have 8GB RAM vs the iPhones 6GB.

It's also pertinent to note that a Radarr instance with  < 20k movie objects will load on iPhones.

For the attached trace - Enabled trace logs, then immediately tried accessing radarr from iphone. Waited for the iphone to "restart" the loading process loop, then stopped trace logs.

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have followed the steps in the wiki link above and provided the required trace logs that are relevant and show this issue.

**Comment by edrock200** [comment]
> I assume this is trying to load the Movie Index?
> 
> On Desktop, Browser Dev Tools => network tab => load radarr what's the response size of the /movie endpoint?


![radarr-debug](https://github.com/Radarr/Radarr/assets/26733879/34e44cdd-7e08-41d3-bb91-aa7710ce85b5)
Correct the movie index.
It shows 2 movie endpoints, and both are 57.4MB

I should have also had a few friends try from their iphones to rule out a specific config or hardware issue.
Thanks for the help.

**Comment by bakerboy448** [comment]
confirmed here as well that the /movie endpoint is getting hit 2x on load

**Comment by edrock200** [comment]
> confirmed here as well that the /movie endpoint is getting hit 2x on load

Thank you. Sorry for removing the pic, I realized it had key and url info. I blacked those out and reattached if its helpful in anyway.

**Comment by Qstick** [comment]
https://github.com/Radarr/Radarr/commit/fe76cbfc6b021913255b45038e67f868ab65b9f9

**Comment by edrock200** [comment]
Confirmed working now! Seems to be faster as well, thank you!
