### ISSUE TITLE
Option to refresh sideloaded metadata (jpg, nfo etc) on schedule vs daily

### ISSUE THREAD

**Issue by edrock200** [Radarr/Radarr#8536]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

When enabling sideloaded data such as emby nfo files and poster/background/etc jpgs, Radarr appears to refresh this data on the daily scans. In addition to causing a significant amount of metadata downloads, when media apps such as emby sees the modify date on an nfo or jpg change, it reprocesses that data, causing a singnificantly longer scan time. 

### Describe the solution you'd like

Add a refresh interval which applies if metadata already exists, e.g.:
If metadata exists refresh every:
Never
1 week
1 month
3 months
6 months
1 year
Or whatever intervals seem appropriate.

### Describe alternatives you've considered

Presently I turn this option off, enable once a month, refresh all, disable again.

### Anything else?

Appreciate the consideration. 

As I know code is sometimes shared between sonarr and radarr, I am noting a similar sonarr request I made here:
https://github.com/Sonarr/Sonarr/issues/5659

**Comment by Qstick** [comment]
Similar position as Sonarr here, I’m not really excited about turning this into an option. If there are cases in which metadata is getting refreshed or changed too often we can certainly investigate those deeper.

**Comment by edrock200** [comment]
Got it. Appreciate the quick response! @Qstick
