### ISSUE TITLE
Fix incorrect match after Bulk Import

### ISSUE THREAD

**Issue by jpborjas** [Radarr/Radarr#854]
I just started using the new Bulk Import feature. The first folder I added was for Concerts, and I noticed that there are some mismatched videos. I can't seem to find how to correct the incorrect match. I saw the option for the IMDB or TVDB ID in the bulk import, but I thought to import all of them, and then fix the ones mismatched. How do I do that?

Also, after the initial import, I can't seem to be able to add more folders, as the folder containing the movies, appears to be empty in Radarr. 

In addition, all this movies (concerts) appear as missing, and when I go into the Path, there is nothing there. If I try to edit it and point at the file, there's nothing inside the folder, it doesn't see the actual file, so I can't match it manually. 

I've restarting the service, to no avail. 

**Radarr Version:** 0.2.0.375
![screen shot 2017-02-23 at 11 25 39 am](https://cloud.githubusercontent.com/assets/14253583/23268601/4151bd70-f9bc-11e6-8106-563566116975.png)
![screen shot 2017-02-23 at 11 25 59 am](https://cloud.githubusercontent.com/assets/14253583/23268605/436664f8-f9bc-11e6-9d3d-53332663ae19.png)
![screen shot 2017-02-23 at 11 26 15 am](https://cloud.githubusercontent.com/assets/14253583/23268609/455f0b0c-f9bc-11e6-9eeb-3329d3c99e88.png)
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/797086/radarr.debug.txt)

**Logs:**

**Comment by galli-leo** [comment]
You can't edit the match anymore, except if you edit the tmdbid directly in the database. In regards to the missing, it won't display the files in the browser, since you only need to point Radarr to the folder.

**Comment by jpborjas** [comment]
If it is a mismatch and I can't edit it, sounds like an feature request, right?

As far as the missing ones, Radarr is not seeing them. Notice my last screenshot, I selected Missing Only, but they are not missing, the right folder is selected, and they came from the bulk impost. Moreover, others that are not in the Missing Only view, do show the file. Please see new screenshot. Something is amiss. 
![screen shot 2017-02-23 at 4 39 45 pm](https://cloud.githubusercontent.com/assets/14253583/23280372/e360a908-f9e6-11e6-83d4-45f2af8d2ac7.png)

**Comment by onedr0p** [comment]
If it's a mismatch just delete the wrong ones and re-add them. Also radar doesn't support multi part movies yet, this is a feature request already. Closing this issue.

**Comment by onedr0p** [comment]
Also, police isn't showing up because it's in a nested folder.
