### ISSUE TITLE
Wanted > Missing not displaying after 0.2.0.386 nightly

### ISSUE THREAD

**Issue by Lagrik** [Radarr/Radarr#855]
Just upgraded to the latest nightly 0.2.0.386.  Love that you guys are working on minimum availability.  However, when I look at Wanted > Missing, nothing shows there anymore after updating.  Had plenty of movies in there prior to the latest nightly.

I initially thought, ok, let me go in and Edit a Movie and saw Minimum Availability was blank.  I modified Minimum Availability to some of my movies to be Physical/Web.  But, I still see nothing in Wanted > Missing.  Tried restarting Radarr as well but same issue.

**Comment by galli-leo** [comment]
We have added filtering there, you may have to click monitored instead of available. Stuff that does not meet the min availability will not show up under available.

**Comment by Lagrik** [comment]
Bingo.  That was it.  Thanks!

**Comment by Lagrik** [comment]
Looking at the filtering options
