### ISSUE TITLE
Unknown release. Movie not Found.

### ISSUE THREAD

**Issue by EffeF** [Radarr/Radarr#856]
**Description:**
Some movies are not downloaded, and performing a manual search the file can not be downloaded for the following reason:
"Unknown release. Movie not Found."

**Radarr Version:** 0.2.0.375

**Comment by galli-leo** [comment]
Can you provide me with the exact movie where this is happening? And a screenshot of the manual search page would also be very good.

**Comment by EffeF** [comment]
These are the screenshots:

<img src="https://anonimag.es/i/2017-02-231f1f64.png" alt="2017-02-231f1f64.png" border="0">
<img src="https://anonimag.es/i/2017-02-232db7e4.png" alt="2017-02-232db7e4.png" border="0">
<img src="https://anonimag.es/i/2017-02-233031ca.png" alt="2017-02-233031ca.png" border="0">

**Comment by scambra** [comment]
I have same issue with [REC]⁴ Apocalypse, I don't if related to brackets or 4 being superindex

**Comment by galli-leo** [comment]
@EffeF The screenshots seem to be missing. Can you upload them again?

**Comment by tac00** [comment]
I have the same unknown release issue with some of my movies in Radarr.

![](https://i.imgur.com/DjGHbdX.png)

**Comment by galli-leo** [comment]
@tac00 Try updating your library.

**Comment by tac00** [comment]
@galli-leo I have downgraded to 0.2.0.299 and it seems to work. I will test more when I get home later

**Comment by heinis3** [comment]
Same issue here with 0.2.0.375. Indexer works if I'm searching the move in english, but throws the _Unknown release. Movie not Found._ if it is in different language (tried russian here), even if it has the english name in the title.

**Comment by zprewitt** [comment]
Seeing the same issue on v0.2.0.375 with the movie Green Room (2016). You'll notice in the attached screenshot that there's one release available but the rest are not.

![greenroom](https://cloud.githubusercontent.com/assets/12501149/23580722/a25c1a6a-00bb-11e7-90b0-a045eed4c189.png)

**Comment by onedr0p** [comment]
Looks like the one that works has the year 2016 and the others are 2015

**Comment by zprewitt** [comment]
Good catch! Wonder why it didn't get snatched automatically.

**Comment by onedr0p** [comment]
@zprewitt I have pushed a update to nightly to use the lowest year returned by tmdb for the year.

**Comment by ikvirsingh** [comment]
I'm having the same issue with 0.2.0.453. I encountered three scenarios where the issue occurred:

1) If a title has an alternate title. Ex. Mesrine: Killer Instinct has an original title in French as L'instinct de mort and Radarr is rejecting the releases with the French title.
2) Try searching for Gangs of Wasseypur. This title has two parts. Radarr will show it as Gangs of Wasseypur and Gangs of Wasseypur II in the search results. When searching for releases for these titles, the results list contains Gangs of Wasseypur Part 1 and Gangs of Wasseypur Part 2, which get rejected.
3) Try searching To Live and Die in L.A. For the life of me, I cannot understand why every release found is tagged as unknown release.

I've attached some screenshots for reference.

![screen shot 2017-03-06 at 8 58 11 pm](https://cloud.githubusercontent.com/assets/974037/23638645/ded6f3ba-02b0-11e7-89d3-526c121dc17d.png)
![screen shot 2017-03-06 at 9 06 01 pm](https://cloud.githubusercontent.com/assets/974037/23638649/e377bf30-02b0-11e7-992e-3dc531b1c4df.png)

**Comment by onedr0p** [comment]
@ikvirsingh 

* For the movie `Mesrine: Killer Instinct` none of the release names match that movie title so Radarr can't parse the movie title, year and release info.

* For the movie `Gangs of Wasseypur` and `Gangs of Wasseypur II` both are listed as the same imdbid: http://www.imdb.com/title/tt1954470/

* `To Live and Die in L.A.` looks fixable, maybe @galli-leo can take a look sometime.

**Comment by ikvirsingh** [comment]
@onedr0p 

Is there anything that could be done for movies that have different titles in different languages? I suspect this could be a problem for other foreign films that have an English equivalent title.

Thanks for the quick response.

**Comment by onedr0p** [comment]
As it stands we don't currently search the release name for alternative titles, definitely something we will look into though. Unfortunately that still won't fix your problem for `Mesrine: Killer Instinct` since nothing matches at all (via title or any alternative titles). Once we allow matching release name to alternative titles you would need to add that title as a alternative title to themoviedb movie under the country France.

**Comment by mooop12** [comment]
Not sure if it's related but Radarr can't parse this file name `The.Lord.of.the.Rings.2001.The.Fellowship.of.the.Ring.BluRay.Remux.AVC.1080p.DTS-HD.MA.6.1-HDX.mkv`. It didn't detect it when searching for download, and it doesn't detect it when trying to manually import it, after starting the download manually. It says "Unknown Movie".

**Comment by onedr0p** [comment]
@mooop12 it cannot parse that because the year doesn't come after the movie title, it's in between.

**Comment by bpaczkowski** [comment]
@onedr0p What about manually selecting the movie in import window? That should work, right?

**Comment by onedr0p** [comment]
Not sure about that, I don't believe so because the movie name cannot be matched to a movie in radarr. For example `Lord.of.the.Rings.2001.The.Fellowship.of.the.Ring.BluRay.Remux.AVC.1080p.DTS-HD.MA.6.1-HDX.mkv` will be parsed as `Lord of the Rings` with the year `2001`. `The.Fellowship.of.the.Ring` will screw it up because radar expects to see `BluRay.Remux.AVC.1080p.DTS-HD.MA.6.1-HDX` there instead.

**Comment by galli-leo** [comment]
@mooop12 What exact issue does the parser have? Parses fine on my end.

**Comment by mooop12** [comment]
@galli-leo Derp, the reason why I couldn't import it manually is because I didn't tick the checkbox on the left ;) After I did that it imported fine. What @onedr0p wrote still applies, Radarr wont parse it automatically. What happens under the hood I do not know, but in the UI it only says "Unknown Movie".

**Comment by onedr0p** [comment]
We will change that message to be Unknown movie - cannot parse release name .. or something.

**Comment by onedr0p** [comment]
I have an update coming that should fix a lot of problems with Unknown Movie. If the indexer supports searching by imdbId you should be able to download the release with radarr. It's only tricky when we try to match the name of the movie with the release title when imdbId searching is not enabled on your indexer.

**Comment by onedr0p** [comment]
Closing this issue, please open up separate requests if a movie is not able to be downloaded. We will need to handle most requests on a case by case basis, like with `To Live and Die in L.A.` Majority of releases should be working better now, especially foreign films with indexers that support searching by imdbId.
