### ISSUE TITLE
Movies all show as In Cinema after 0.2.0.386 nightly

### ISSUE THREAD

**Issue by Lagrik** [Radarr/Radarr#857]
Not sure how this looked prior to this nightly or several before it (as I had skipped about 5 nightly builds) but when clicking on Movies, all of them show as In Cinemas even if they've been released on blu-ray even years ago.  They still show the proper Available Date or if they are in cinemas next to it.  But the left most button has "In Cinemas" for every  movie.

**Comment by Lagrik** [comment]
This suddenly started displaying properly.  Weird.  I'll close the issue for now and if I see it creep up again, I'll re-open.

**Comment by galli-leo** [comment]
Ah this is fixed by doing an update library (probably it did that itself)
