### ISSUE TITLE
New Bulk Importer option to search by quality

### ISSUE THREAD

**Issue by jmacul2** [Radarr/Radarr#858]
I think it would be useful for those of us that are upgrading our movies to a higher quality to have the new bulk import give us the option to search or filter based on quality.  Also sorting might be useful as well.  A simple javascript filter could work, so that we could then do a select all on the filtered display.

[AB#890](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/890)

**Comment by galli-leo** [comment]
Not gonna happen until we have a new UI. Filtering will be near impossible to implement as well as sorting.
