### ISSUE TITLE
Unable to add root folder

### ISSUE THREAD

**Issue by lamepennies** [Radarr/Radarr#8584]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Currently getting this error adding new library folders:

`Unable to add root folder
{"message":"One or more errors occurred. (Value was either too large or too small for an Int64.)","description":"System.AggregateException: One or more errors occurred. (Value was either too large or too small for an Int64.)\n ---> System.OverflowException: Value was either too large or too small for an Int64.\n at System.Convert.ThrowInt64OverflowException()\n at NzbDrone.Mono.Disk.ProcMount.get_AvailableFreeSpace() in D:\\a\\1\\s\\src\\NzbDrone.Mono\\Disk\\ProcMount.cs:line 23\n at NzbDrone.Mono.Disk.DiskProvider.GetAvailableSpace(String path)\n at NzbDrone.Core.RootFolders.RootFolderService.<>c__DisplayClass14_0.<GetDetails>b__0() in D:\\a\\1\\s\\src\\NzbDrone.Core\\RootFolders\\RootFolderService.cs:line 208\n at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)\n--- End of stack trace from previous location ---\n at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\n --- End of inner exception stack trace ---\n at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\n at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)\n at NzbDrone.Core.RootFolders.RootFolderService.GetDetails(RootFolder rootFolder, Dictionary`2 moviePaths, Boolean timeout) in D:\\a\\1\\s\\src\\NzbDrone.Core\\RootFolders\\RootFolderService.cs:line 209\n at NzbDrone.Core.RootFolders.RootFolderService.Add(RootFolder rootFolder) in D:\\a\\1\\s\\src\\NzbDrone.Core\\RootFolders\\RootFolderService.cs:line 121\n at Radarr.Api.V3.RootFolders.RootFolderController.CreateRootFolder(RootFolderResource rootFolderResource) in D:\\a\\1\\s\\src\\Radarr.Api.V3\\RootFolders\\RootFolderController.cs:line 56\n at lambda_method1789(Closure , Object , Object[] )\n at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\n at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()\n at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()\n--- End of stack trace from previous location ---\n at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\n at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\n--- End of stack trace from previous location ---\n at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\n at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\n at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\n at Radarr.Http.Middleware.BufferingMiddleware.InvokeAsync(HttpContext context) in D:\\a\\1\\s\\src\\Radarr.Http\\Middleware\\BufferingMiddleware.cs:line 28\n at Radarr.Http.Middleware.IfModifiedMiddleware.InvokeAsync(HttpContext context) in D:\\a\\1\\s\\src\\Radarr.Http\\Middleware\\IfModifiedMiddleware.cs:line 41\n at Radarr.Http.Middleware.CacheHeaderMiddleware.InvokeAsync(HttpContext context) in D:\\a\\1\\s\\src\\Radarr.Http\\Middleware\\CacheHeaderMiddleware.cs:line 33\n at Radarr.Http.Middleware.StartingUpMiddleware.InvokeAsync(HttpContext context) in D:\\a\\1\\s\\src\\Radarr.Http\\Middleware\\StartingUpMiddleware.cs:line 41\n at Radarr.Http.Middleware.UrlBaseMiddleware.InvokeAsync(HttpContext context) in D:\\a\\1\\s\\src\\Radarr.Http\\Middleware\\UrlBaseMiddleware.cs:line 27\n at Radarr.Http.Middleware.VersionMiddleware.InvokeAsync(HttpContext context) in D:\\a\\1\\s\\src\\Radarr.Http\\Middleware\\VersionMiddleware.cs:line 28\n at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)\n at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)\n at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\n at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\n at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)"}`

### Expected Behavior

It adds the directory and sources files 

### Environment

```markdown
- OS: 
- Radarr: 4.4.4.7068
- Docker Install: YES
- Using Reverse Proxy: 
- Browser: Brave
- Database: Sqlite 3.40.1
```

### What branch are you running?

Master

### Trace Logs?

2023-05-24 18:11:34.3|Error|RootFolderService|Unable to get free space and unmapped folders for root folder /home/(removed)/DIRECTORY

[v4.4.4.7068] System.OverflowException: Value was either too large or too small for an Int64.
   at System.Convert.ThrowInt64OverflowException()
   at NzbDrone.Mono.Disk.ProcMount.get_AvailableFreeSpace() in D:\a\1\s\src\NzbDrone.Mono\Disk\ProcMount.cs:line 23
   at NzbDrone.Mono.Disk.DiskProvider.GetAvailableSpace(String path)
   at NzbDrone.Core.RootFolders.RootFolderService.<>c__DisplayClass14_0.<GetDetails>b__0() in D:\a\1\s\src\NzbDrone.Core\RootFolders\RootFolderService.cs:line 208
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have followed the steps in the wiki link above and provided the required trace logs that are relevant and show this issue.

**Comment by bakerboy448** [comment]
What's the free space available for that path in bytes?

**Comment by lamepennies** [comment]
It says 0 but it's a mergefs with a google drive.

**Comment by bakerboy448** [comment]
the value being returned would be not 0.  I believe historically in radarr it would show like 1PB as free space

**Comment by lamepennies** [comment]
Yeah, I remember seeing that before but now I see this



Free Space | Unmapped Folders


0 B | -

**Comment by bakerboy448** [comment]
What's your mergerfs command?

**Comment by lamepennies** [comment]
Using a service file:

[Unit]
Description = MergerFS Service
After=rclone-vfs.service
RequiresMountsFor=%h/DIR/Local
RequiresMountsFor=%h/DIR/Mount

[Service]
Type=forking
TimeoutStopSec=60
ExecStart=%h/bin/mergerfs \
    -o use_ino,func.getattr=newest,category.action=all \
    -o category.create=ff,cache.files=auto-full,threads=8 \
    %h/DIR/Local:%h/DIRMount %h/G_MergerFS

StandardOutput=file:%h/scripts/mergerfs_mount.log
ExecStop=/bin/fusermount -uz %h/G_MergerFS
Restart=on-failure

[Install]
WantedBy=default.target

**Comment by bakerboy448** [comment]
Adjust your merge to match the wiki.

`/usr/bin/mergerfs /mnt/local:/mnt/cloud /mnt/merge -o rw,use_ino,allow_other,func.getattr=newest,category.action=all,category.create=ff,cache.files=auto-full,statfs_ignore=nc,func.getattr=newest,dropcacheonclose=true,nonempty`

https://wikiold.servarr.com/Cloud_Setup#Setting_up_Mergerfs

**Comment by lamepennies** [comment]
So it sounds like it's an rclone issue. Trying problem solve that. When I do rclone about gdrive:, Free is 'off'. Will reply if I find a solution.

**Comment by Krandor1** [comment]
Google is starting to enforce storage limits on the drives. Check your admin console and see if it shows you are over the limit. That might be way it’s reporting no free space. On May 28, 2023, at 15:26, lamepennies ***@***.***> wrote:﻿
So it sounds like it's an rclone issue. Trying problem solve that. When I do rclone about gdrive:, Free is 'off'. Will reply if I find a solution.

**Comment by lamepennies** [comment]
So wrapping it up, Krandor1 is right. It's due to my drives being full.

**Comment by Krandor1** [comment]
Glad to help and one of those times I don’t like being right.  On May 28, 2023, at 17:55, lamepennies ***@***.***> wrote:﻿
So wrapping it up, Krandor1 is right. It's due to my drives being full.
