### ISSUE TITLE
Updating error 0.2.0.299 to version 0.2.0.375

### ISSUE THREAD

**Issue by noorbertt** [Radarr/Radarr#859]
Hi,

I use ubuntu server and cannot upgrade to the new Radarr version.
From version 0.2.0.299 to version 0.2.0.375

http://pastebin.com/W9smRHvg

**Comment by Fiala06** [comment]
Not really familiar with Ubuntu but looks like you need to adjust your permissions:

17-2-23 17:08:39.8|Fatal|UpdateApp|An error has occurred while applying update package.
[v0.2.0.375] System.UnauthorizedAccessException: Access to the path "/opt/Radarr/CookComputing.XmlRpcV2.dll" is denied.

**Comment by noorbertt** [comment]
This was my first thought but all file is 777 because of this.

**Comment by noorbertt** [comment]
UP
OK that's was odd...
After the second server restart just works fine. #confused
