### ISSUE TITLE
Collections aren't being removed when removed from TMDB

### ISSUE THREAD

**Issue by klepp0906** [Radarr/Radarr#8596]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I recently decided to monitor all collections and yolo add everything to my library.  I immediately became aware of some 2m and 5m "shorts" that sent me to the mods at TMDB.  They confirmed that the collection in question shouldnt even exist and removed it.

I found a second collection that also should not exist which had been taken care of without my intervention at some unknown point having already passed.

needless to say I was curious how to remove these collections from my library as I assumed this updated/synced with TMDB at some interval. 

After manually refreshing collections,  the offenders still exist. 

### Expected Behavior

As TMDB is community ran,  the unfortunate bit is that depending on level of QA/moderation over there, bad collections are going to make it through and wreak havoc.

I'm assuming these are supposed to disappear when they disappear from TMDB but for some reason they are not.

The aforementioned withstanding, for those of us that have films auto added to our library from collections and/or auto grabbed from said collection(s) a notification would be nice indicating the collection was removed from TMDB (and the films it contained) similar to the one you get when a movie is removed.  (i recall this happening at some point but i cant remember how or the exact notification radarr gave)

certainly have been given pause about enabling the auto add going forward :p

### Steps To Reproduce

not sure how to provide steps as seeing the issue will require a specific movie(s)

I'll provide some screenshots in the log area.

### Environment

```markdown
- OS: Win11
- Radarr: 4.5.2.7368
- Browser: Brave
- Database: Sqlite 3.36.0
```

### What branch are you running?

Nightly

### Trace Logs?

This collection no longer exists on TMDB.  If you search Ninjago Collection there, you get nothing.  If you search The Ninjago Movie, it will show as belonging to no collections.
![image](https://github.com/Radarr/Radarr/assets/10392920/ab6a339a-fc33-405c-9b4c-ff2cb416530b)

Nor does this one, note the details indicating its hot-messed-ness
![image](https://github.com/Radarr/Radarr/assets/10392920/e7486db3-2d80-49e8-bf6f-0500362771b4)

If you want/need trace logs, i can provide some just let me know.  I did grab them but after clearing and running a quick update collections to try to catch the issue, not only did i see no errors (doesnt mean much as a layman) but they were already too long/big for 0bin to accept. 

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have followed the steps in the wiki link above and provided the required trace logs that are relevant and show this issue.

**Comment by bakerboy448** [comment]
Please use one of the support channels: [Reddit](https://www.reddit.com/r/radarr/) or  [Discord](https://radarr.video/discord) for support/questions.

https://github.com/Radarr/Radarr/blob/develop/src/NzbDrone.Core/Housekeeping/Housekeepers/CleanupOrphanedCollections.cs

Refresh Collection only refreshes the collections.

Housekeeping handles the cleanup

**Comment by bakerboy448** [comment]
Metadata server still has that collection and it hasn't purged out https://api.radarr.video/v1/movie/collection/1072678

Similar for the movie - it still has the collection in the cache
https://api.radarr.video/v1/movie/274862

@Qstick this a timing / cache issue? Or an actual metadata server issue.

**Comment by klepp0906** [comment]
FWIW, these are still present.  so theyre not clearing from somewhere. for some reason.  I unmonitored them both, removed all unwanted movies from my library (all but 1 from each), and let it sit about a week. 

unsure if this is a you guys thing, or a tmdb thing?

**Comment by Qstick** [comment]
It's an us thing on metadata, we are working on some options

**Comment by klepp0906** [comment]
> It's an us thing on metadata, we are working on some options

okay, thank you for letting me know.  and thank you guys for all your time you spend on this stuff!
