### ISSUE TITLE
rTorrent client download folder not respected

### ISSUE THREAD

**Issue by Vaelek** [Radarr/Radarr#862]
When using the rTorrent downloader, setting the directory (or category) has no effect. The default directory is used, which breaks the process of determining a download has finished and it never gets imported.

**Radarr Version:**
0.2.0.375

**Comment by Vaelek** [comment]
Some more information on this I've noticed. It seems that when adding an item via magnet, the category/directory are lost when the magnet resolves the actual torrent. The download is also stopped at that point. Adding it to queue a second time via Radarr causes it to start and applies the category and directory. Depending on the timing and if files are pre-allocated, this breaks everything as the location changes after it is created and then the torrent is stuck in a paused state.

**Comment by onedr0p** [comment]
@Vaelek there is a prob with magnets and rtorrent and it affects Sonarr too. Unfortunately there is nothing we can do, if a fix is proposed in Sonarr we will add it here too.

See here
https://github.com/Radarr/Radarr/issues/644

**Comment by Vaelek** [comment]
@onedr0p Actually I have no issues at all using magnets (via Jackett) with Sonarr. They don't work with the blackhole client, but they work fine with the rTorrent client.

**Comment by Vaelek** [comment]
After looking at this again, I was mistaken and the feed I thought was giving magnets in Sonarr was actually not. That being said, I have also solved the problem, but I don't know Git well enough to submit a proper pull request.

in NzbDrone.Core\Download\Clients\rTorrent\RTorrent.cs, I made the following changes, and it is working beautifully now. 

```cs
    protected override string AddFromMagnetLink(RemoteMovie remoteMovie, string hash, string magnetLink)
    {
      _proxy.AddTorrentFromUrl(magnetLink, Settings);

      // Download the magnet to the appropriate directory.
      _proxy.SetTorrentLabel(hash, Settings.MovieCategory, Settings);
      SetDownloadDirectory(hash);
      _proxy.StartTorrent(hash, Settings);

      // Wait for the magnet to be resolved.
      var tries = 10;
      var retryDelay = 500;
      if (WaitForTorrent(hash, tries, retryDelay))
      {
        // Begin Changes *****************************************************
        _logger.Info("Resolved magnet for {0}", remoteMovie.Movie.CleanTitle); 
        SetDownloadDirectory(hash);
        _proxy.SetTorrentLabel(hash, Settings.MovieCategory, Settings);
        _proxy.StartTorrent(hash, Settings);
        // End Changes ********************************************************
        return hash;
      }
      else
      {
        _logger.Warn("rTorrent could not resolve magnet within {0} seconds, download may remain stuck: {1}.", tries * retryDelay / 1000, magnetLink);

        return hash;
      }
    }
```

**Comment by onedr0p** [comment]
I'll commit it tonight.

**Comment by onedr0p** [comment]
Fixed in next release
