### ISSUE TITLE
Reusable configuration via config file(s)

### ISSUE THREAD

**Issue by AurimasNav** [Radarr/Radarr#8634]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Running multiple instances of radarr (4k/non4k/specific language etc.) requires a lot of clicking around webgui, which is prone to mistakes and very time consuming. 
In a cases where server needs to be wiped clean / reinstalled this becomes a very tedious task.

### Describe the solution you'd like

It would be great if we could have a way to define all the configuration outside the webgui, via config file, so it can be saved (git) and reused, or basically deployed together with radarr in gitops scenarios.

### Describe alternatives you've considered

Not aware of any alternatives.

### Anything else?

Sorry if this was discussed, could not find anything, but it is also hard to believe that this topic never came up, since there is whole kubernetes@home community which would really appreciate this.

**Comment by RobinDadswell** [comment]
Config is split between the database and the config file dependant of it is required for startup of Radarr or not. 

We have no plans to have everything handled via config file however everything is configurable via the API.
