### ISSUE TITLE
Movies imported from a list would not start downloading automatically

### ISSUE THREAD

**Issue by elad-maimon** [Radarr/Radarr#864]
**Description:**

I'm using Trakt user watch list to import movies for download. The movies are imported to the library as "missing" but never get downloaded even if there's available version. I need to press the "search for movie" (magnifying glass) button in order for the movie to be added to download queue.

**Radarr Version:**
0.2.0.375

**Comment by onedr0p** [comment]
This is on Feathub

http://feathub.com/Radarr/Radarr/+64
