### ISSUE TITLE
Expand categories to allow 3020

### ISSUE THREAD

**Issue by ItsME6969** [Radarr/Radarr#8644]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

https://predb.me/?search=MDVDR%7CMBLURAY&page=1
Search your favorite indexer for any of those releases and you will see they end up on 3020.

https://github.com/Radarr/Radarr/issues/3023

### Describe the solution you'd like

Add 3020

### Describe alternatives you've considered

None

### Anything else?

Thanks

**Comment by bakerboy448** [comment]
Already possible with Prowlarr and the site's custom cats. Simply select them accordingly.

**Comment by Qstick** [comment]
Why are movies ending up in audio/video (music video) category?

**Comment by Qstick** [comment]
Thanks for the clarification. I see your note above, but I wouldn’t think the tmdb population would be too big here. And while the change to support the category would be a one liner, we really don’t want to advertise support for something we don’t FULLY support. In this case rss may or may not work to pick these but search certainly wouldn’t as bogdan pointed out (it sends a t=movie). Feels very 0.1%
