### ISSUE TITLE
Piwik sending stats to Sonarr

### ISSUE THREAD

**Issue by d2dyno** [Radarr/Radarr#865]
**Description:**

It seems Piwik (piwikCheck.js) is still sending usage stats to sonarr.tv (https://github.com/Radarr/Radarr/blob/develop/src/UI/Shared/piwikCheck.js#L10). Is this supposed to happen?

**Radarr Version:**

0.2.0.386

**Comment by onedr0p** [comment]
@AeonLucid we can either have these stats, or just remove it. It's up to you since you have access to the server.

**Comment by AeonLucid** [comment]
@galli-leo Are you interested in these analytics? If so, let me know and I'll set it up. https://piwik.org/

Looks pretty cool / useful to me.

**Comment by onedr0p** [comment]
@AeonLucid seems good to me too.

**Comment by galli-leo** [comment]
@AeonLucid Yeah looks useful.

**Comment by galli-leo** [comment]
@AeonLucid Did you get around to implementing it?

**Comment by ottowayne** [comment]
To be honest I think it's a big privacy issue that this is enabled by default and hidden under advanced settings. Users are not even being informed about this.

**Comment by galli-leo** [comment]
While I would usually agree with you, every part of the analytics software is open source: Radarr and Piwiki itself. Also we don't collect any data pertaining to specific users. I specifically disabled ip logging to keep you guys as anonymous as possible. Additionally, you probably leave more data, with just a simple request to our or any other API server, since webservers log ip, user agent, request url, etc.

**Comment by ainola** [comment]
@galli-leo Sorry to necro this but I have to agree with @ottowayne. You're collecting a large list of who has radarr installed in one place. Piwik is free software, sure, but that doesn't justify it!

**Comment by Qstick** [comment]
Turn analytics off if you care that much. It's a user opinion right in settings and the logic statement is right there in the code link above if you want confirmation. Anonymous Analytics are used to find bugs and make Radarr better overall for everyone, but the option is there for those that care. Also couch potato is an alternative if you still feel it's an issue or feel that strongly about it.
