### ISSUE TITLE
check indexers with alternative movie name for download availability

### ISSUE THREAD

**Issue by thelittleblackbird** [Radarr/Radarr#8654]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

movies does have normally different names in different languages/ regions of the world, when adding a language normally people selects also which local language is preferred, which may depart from the original one.

Radarr seems to check only with the original language and then checks the metadata if additional languages are also incorporated. This behaviour leads into very few positive hits when the movie was released in that language with a different name. Even when there is a curated list of localized scene resources.

you can easily reproduce the problem with "Harry Potter y la piedra filosofal" as alternative title in search engines vs "Harry Potter and the Sorcerer's Stone" when you add this movie in the library with the Spanish as the only selected language

### Describe the solution you'd like

because TMDB and IMDB already incorporate alternative names of the movies when they are released in different regions of the world. the information is present and only needs to be used.

I would expect radarr to check the language profile of the library and when selected a language/title different from the original one, to perform the search via the alternative name.

In case more than a name is selected perhaps a prio based in the "points" of the custom format can be done. As an extremely nice to have, if more than a single name is selected  then more than a single search is triggered and perhaps the results consolidated (an union perhaps?) before the grabbing is done.

### Describe alternatives you've considered

no alternatives in the arr suite. the only feasible way is to really make this process by hand which invalidate all the workflow created with this program.

Apart that it would not be any automatic update either.

asking search engines to do this process is highly improbable due to the small internationalization of some scenes.

### Anything else?

2 screenshots to illustrate the difference when searching with original name vs the alternative name of the desired language

![imagen](https://github.com/Radarr/Radarr/assets/135506298/41540142-67c0-472b-9621-b60ce058ebce)

![imagen](https://github.com/Radarr/Radarr/assets/135506298/40639206-8fe1-422a-b32d-7a7088f666c1)

**Comment by bakerboy448** [comment]
https://wiki.servarr.com/radarr/faq#how-does-radarr-handle-foreign-movies-or-foreign-titles

**Comment by thelittleblackbird** [comment]
thanks for the explanation, but just a question out of curiosity.
Why radarr is not checking the release date in the metadata? why using the date of the title exclusively?

**Comment by bakerboy448** [comment]
There is no metadata for releases indicating the year...? It only has the name in the release to go off of....and multiple movies with the same name are rather often released in different years so it's the only way to identify them

again 
Please use one of the support channels: [Reddit](https://www.reddit.com/r/radarr/) or  [Discord](https://radarr.video/discord) for *support/questions.*
