### ISSUE TITLE
Feature request: Easy access to exclusions list

### ISSUE THREAD

**Issue by Bekkenes** [Radarr/Radarr#8659]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

The "add exclusion" button is next to the "add movies" in "discover" section.
If you by accident manage to push the wrong one you exclude movies you might want to add.
Its of course the users "fault", but it can happen (especially if you navigate the website on a mobile device with 1cm clearance between the two).

My wish/desire is that somewhere in in the menu you can nix out erroneous added movies from exclusion list.
I have after some research found out it can be done by editing the database but for the average person this is not something they would (or should) do.

-Thomas

### Describe the solution you'd like

Add to menu a place to remove movies from exclusion list.

### Describe alternatives you've considered

When you push exclude video you get up a warning asking if you are sure.

### Anything else?

none

**Comment by Qstick** [comment]
You can do this one by one in Settings>Lists. Otherwise there is already an issue to track bulk management #4846
