### ISSUE TITLE
Error after updating movies

### ISSUE THREAD

**Issue by Locutus64** [Radarr/Radarr#8664]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I'm getting a fail error after updating movies even though it looks like they were upodated.

### Expected Behavior

once the movies are finished I expect it to say completed not Failed.

### Steps To Reproduce

Launch Radarr-Developer in Vivaldi
Click to update movies
When movies update is done get Failed

### Environment

```markdown
- OS: Garuda Linux - Plasma Desktop
- Radarr: 4.6.1.7447
- Using Reverse Proxy: 
- Browser: Vivaldi
- Database: ???
```

### What branch are you running?

Develop

### Trace Logs?

https://pastebin.com/euAXfU4h

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have followed the steps in the wiki link above and provided the required trace logs that are relevant and show this issue.

**Comment by bakerboy448** [comment]
```
2023-06-07 11:04:25.6|Trace|HttpClient|Res: [GET] https://api.radarr.video/v1/movie/collection/578704: 404.NotFound (0 bytes) (159 ms)
2023-06-07 11:04:25.6|Error|AddMovieCollectionService|TmdbId 578704 was not found, it may have been removed from TMDb.
2023-06-07 11:04:25.6|Error|RefreshMovieService|Couldn't refresh info for [Live Die Repeat and Repeat (0)][tt5617712, 424775]
 
[v4.6.1.7447] FluentValidation.ValidationException: Validation failed: 
 -- TmdbId: A collection with this ID was not found.
 ```

Run refresh collections task, housekeeping task, and then refresh collections task again see if that cleans it up

**Comment by Locutus64** [comment]
Simply removed Live Die and Repeat and all's good. Not sure why it just didn't tell me that it had been removed from TMDB like it did for Aladdin 2 today.
