### ISSUE TITLE
anyway to not import files with a specific file type? Most fakes are in wmv and avi

### ISSUE THREAD

**Issue by jscottdouglas** [Radarr/Radarr#867]
is there anyway to block importing file with specific file type, most fakes seem to be in wmv and avi, and I noticed a few were sneaky enough to get thru today.  I noticed the new release availability function but the help box has me confused if i add or minus based on availability date, example I am ok with ones that are 30 days before their release date as I know some come out prior. does that mean i put -30?

**Comment by jscottdouglas** [comment]
I guess this is an enhancement I didn't see anyway to do this in the options please add a feature to exclude file types.

**Comment by extremeshok** [comment]
+1 for this

**Comment by maxdec** [comment]
I would love to be able to blacklist some kinds of files too (based on the extension or some regex on the filename).

**Comment by onedr0p** [comment]
Just came here to say: Radarr doesn't know the file extension before it downloads it. We will need to make quite a few changes to get this working the way we all want.

**Comment by jscottdouglas** [comment]
Can you not check the file extension prior to importing? personally I don't care if it downloads the garbage but if it imports it, that's my issue.  I would be ok with a import check to check the file extension.

**Comment by kingmotley** [comment]
If you use sabnzbd, just add those file types into your unwanted file types, and it'll even stop downloading it as soon as it can.

**Comment by jscottdouglas** [comment]
considering i use sabnzbd for other stuff as well that do include those file types that would not work for me and i am not familar with any other way to do it in sabnzbd, please feel free to do tell.

**Comment by galli-leo** [comment]
IMO I think this is best handled by your download client. The dl client can immediately stop the download when it get's the filetype and it can even mark the download as failed, prompting Radarr to download another release.

**Comment by maxdec** [comment]
Will try with an ["On Grab"](https://github.com/Radarr/Radarr/wiki/Custom-Post-Processing-Scripts) script and Transmission [rpc api](https://trac.transmissionbt.com/browser/trunk/extras/rpc-spec.txt).

**Comment by jscottdouglas** [comment]
I don't see how it would be best for the download client to handle it, if you have multiple things going thru the download client one type maybe acceptable for a certain file type but another may not.

**Comment by galli-leo** [comment]
@jscottdouglas Most nzb clients have the ability to set such filters per label, so it would only apply to the Radarr downloads

**Comment by Lonli-Lokli** [comment]
Is it possible with any torrent client?
Is it possible to do not import such files and also immediately send the delete request to download client and blacklist it?

**Comment by bakerboy448** [comment]
set your availability right and don't use poor trackers
