### ISSUE TITLE
Available renaming options?

### ISSUE THREAD

**Issue by aptalca** [Radarr/Radarr#868]
Is there a list of available options for renaming variables?

From the default I can see that some options include:
Movie Title
Release Year
Quality Full

By trial and error I figured out the following option also works:
Original Title

Are there any other options? Perhaps one for just the resolution such as 720p or 1080p rather than the "Quality Full"?

For reference, in couchpotato I am currently renaming the filenames as "{Movie Title} ({Release Year}) {Resolution} ({Original Title})" and the folder names as "{Movie Title} ({Release Year}) {Resolution}" (Resolution as just 720p)

Thanks

**Comment by aptalca** [comment]
I see that the wiki page has been updated to include the available rename options: https://github.com/Radarr/Radarr/wiki/Sorting-and-Renaming#rename-options
Thanks for that.

The only thing I noticed is that, some of those options only work for the filename, and not the folder name. Perhaps those could be marked for clarification?

Thanks

**Comment by fryfrog** [comment]
I think the folder name option doesn't work at all, but it is on the todo list.
