### ISSUE TITLE
Bulk changing of movie profile not sticking.

### ISSUE THREAD

**Issue by akanealw** [Radarr/Radarr#869]
When I bulk imported my movie folder, I didn't set the profile as there is no way to set it for all movies being imported. When using Movie Editor to change profiles in bulk, changes aren't sticking. I set all to Monitored and 720p. After hitting Save, I scrolled down the list on the same page in the Movie Editor and verified that the change was set. However, when going back to the normal movie list, the change disappears after a few seconds and removes the profile.

If I edit the movie directly and set the profile there, it sticks. 

0.2.0.375

[radarr.debug.txt](https://github.com/Radarr/Radarr/files/798634/radarr.debug.txt)

**Comment by wiscokidd** [comment]
same problem

**Comment by akanealw** [comment]
well, i "fixed" it by deleting my database and renaming my movies files to include the quality before setting up radarr again and reimporting them. however, i then wanted to bulk change my existing movies to unmonitored and that isn't sticking either.

**Comment by onedr0p** [comment]
Handling this in #869
