### ISSUE TITLE
Block release not working

### ISSUE THREAD

**Issue by Milincho** [Radarr/Radarr#8697]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Block release is not working. I block the same fake Spiderman release 20 times and Radarr keeps grabbing the exact same release...

![image](https://github.com/Radarr/Radarr/assets/60118859/63d18222-9aa0-4888-bbef-4dcf2e858446)

![image](https://github.com/Radarr/Radarr/assets/60118859/ce0d049d-ee62-4f7a-a981-4394aef9fbb2)

### Expected Behavior

Radarr blocking the release instead of downloading it again and again...

### Steps To Reproduce

Search and add "Spider-Man: Across the Spider-Verse"

### Environment

```markdown
- OS: Windows
- Radarr: 4.6.1.7456
- Docker Install: 
- Using Reverse Proxy: 
- Browser: 
- Database:
```

### What branch are you running?

Develop

### Trace Logs?

https://gist.github.com/Milincho/20b8b0314e575eff4aa98597857a9402

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have followed the steps in the wiki link above and provided the required trace logs that are relevant and show this issue.

**Comment by Milincho** [comment]
> * "No" is not valid for trace logs
> * its extremely unprofessional to check the box saying you provided trace logs and followed the wiki when that is incorrect

Sorry. I added the Trace log: https://gist.github.com/Milincho/20b8b0314e575eff4aa98597857a9402

> * Screenshots of interactive search results would be beneficial
Like this?
![image](https://github.com/Radarr/Radarr/assets/60118859/b3ffb76d-5400-400b-97db-2b76f99ee884)

**Comment by Milincho** [comment]
> @Milincho can you check the hashes of the two same named torrents?

Mmm...    how/where do I do that?

BTW...    what happens when you add that movie? doesn't do the same for you?

**Comment by bakerboy448** [comment]
Considering I don't have nor use the crappy public trackers - impossible for me to reproduce :D

Most trackers have the torrent's hash on their page or you can get them from the torrent client once they're added

**Comment by Milincho** [comment]
It's always the same hash from the same tracker...

https://torrentgalaxy.to/torrent/15413315/Spider-Man-Across-the-Spider-Verse-2023-1080p-V3-New-Clean-Audio-Video-X264-Will1869-No-Chew-Edition

Info Hash v1: bb8cc6f77129d403672569467509698775f8139d
Info Hash v1: bb8cc6f77129d403672569467509698775f8139d
...

**Comment by Milincho** [comment]
Also, this torrent is in CAM/TS category:
![image](https://github.com/Radarr/Radarr/assets/60118859/eb556105-7503-4edc-9037-24b5f84185ee)

that shouldn't fit my Quality profile:
![image](https://github.com/Radarr/Radarr/assets/60118859/850ed64c-eaf8-4796-b172-1af324b860a4)

**Comment by bakerboy448** [comment]
And what's the hash for the torrent by the same name from a different tracker that is already blocked?

**Comment by Milincho** [comment]
Same: https://www.limetorrents.lol/Spider-Man-Across-the-Spider-Verse-2023-1080p-V3-New-Clean-Audio-Video-X264-Will1869-No-Chew-Edition-torrent-18043757.html

Torrent Hash :	BB8CC6F77129D403672569467509698775F8139D

**Comment by Milincho** [comment]
If I disable 'Torrent Galaxy' as an indexer it does the same with LimeTorrents, so it's not a tracker thing.

This is my Block List. All these entries are from LimeTorrents:

![image](https://github.com/Radarr/Radarr/assets/60118859/00b647f6-79a6-4eb8-afc0-cb6ba91fbc37)

**Comment by janusn** [comment]
I have encountered a similar problem on blocking does not work. I have attached a log. The offender is "Transformers Rise of the Beasts.2023.1080p.WEBRip.x264-[TGx]"

Here is a [log regarding "Transformers Rise of the Beasts.2023.1080p.WEBRip.x264-[TGx]"](https://pastebin.com/bBZbf3PF)
<img width="1661" alt="Screen Shot 2023-06-16 at 2 21 06 pm" src="https://github.com/Radarr/Radarr/assets/21253783/18c8c84a-1e3e-48b1-ace6-75ce461f7cb0">


Is it possible to block a release by the hash as suggested?

**Comment by Qstick** [comment]
I'm hoping this helps https://github.com/Sonarr/Sonarr/commit/7986488c6d1687b0810b3bcac2c1dae725e770ac

**Comment by Milincho** [comment]
Still not working. Radarr keeps trying to download the same release again and again:
![image](https://github.com/Radarr/Radarr/assets/60118859/ec719949-89ab-4799-abca-a5e8ad10517d)

Even when repeatedly told not to:
![image](https://github.com/Radarr/Radarr/assets/60118859/bca84a8e-f526-4fb3-a079-bec89cd79532)

Trace Log
https://gist.github.com/Milincho/1de95b14bb455c542ad45eb24a0628c2

**Comment by bakerboy448** [comment]
@Milincho need a screenshot of the history for that movie

**Comment by Milincho** [comment]
There you go:

![image](https://github.com/Radarr/Radarr/assets/60118859/06d086f1-7b44-48da-843a-1e08d2f48024)

**Comment by bakerboy448** [comment]
Sorry one more And the (I) with the grab details for two of the grab

if you're comfortable with some database exploring eyes on the blocklist entries and the history entries to see where the disconnect is would be helpful

**Comment by Milincho** [comment]
![image](https://github.com/Radarr/Radarr/assets/60118859/ebc252cf-e379-46b0-a3dc-c78bc06ae7d9)

![image](https://github.com/Radarr/Radarr/assets/60118859/3d5fe7c1-dcd9-44fe-b2cc-3ffd97e69e5b)

What do you mean by "database exploring"?  where and how do I do that?

**Comment by bakerboy448** [comment]
Different release from a different tracker even the release name is different.  So that's working as designed

**Comment by Milincho** [comment]
No, those are just the two only different indexers. All these others are the same one from TPB and keeps trying to download it:

![image](https://github.com/Radarr/Radarr/assets/60118859/14e775e7-d1ec-403c-bc57-8cf806e9bea1)

**Comment by bakerboy448** [comment]
All of those entries are the same thing. Grab of =~ and blocklist entry of.

what's the info hashes for both?

**Comment by Milincho** [comment]
That was Radarr repeatedly downloading the same release from TPB and me blocklisting it without success...

How can I have so many exact same blocklist entries if they are supposed to work?

Where can I see the hashes? the source page don't display the hash

**Comment by janusn** [comment]
> Where can I see the hashes? the source page don't display the hash

I am not sure about radarr interface but the hash is show on my download client, Transmission.
<img width="761" alt="Screen Shot 2023-08-29 at 4 00 17 pm" src="https://github.com/Radarr/Radarr/assets/21253783/497751b1-ff4f-4ac4-9441-0026ea845898">

**Comment by Milincho** [comment]
Where can I see the list of 'Blocklist'ed releases?

**Comment by Milincho** [comment]
They are all the same release from TPB with the same hash:
![image](https://github.com/Radarr/Radarr/assets/60118859/a14a7a16-d4b4-47ca-9a83-e55ea13adab7)

The first bad release it tries to download is from BullTorrent and the blocklist feature works fine with it, it doesn't try to redownload it:
![image](https://github.com/Radarr/Radarr/assets/60118859/e65ed1b6-4a3c-479e-8069-4df0dabb704f)

But then it tries to download the TPB bad release ad infinitum, no matter how many times I blocklist it:
![image](https://github.com/Radarr/Radarr/assets/60118859/f2f1efcd-b6c1-44b0-a079-ec36646fc6b9)

**Comment by Milincho** [comment]
Also, this is what I get when trying to access the release url ( https://thepiratebay.org/description.php?id=70627899 )

![image](https://github.com/Radarr/Radarr/assets/60118859/29984c46-1fc8-43e5-a100-0daf798737c7)

**Comment by Milincho** [comment]
Still the same problem with the exact same release...   infinite grabbing despite blocklisting it infinitely.
Is there any reason why this can't be blocklisted by name or hash? it's always the exact same name and hash:

![image](https://github.com/Radarr/Radarr/assets/60118859/0d290951-4659-4215-83ac-0a0877decad4)

**Comment by AndreiArdelean1** [comment]
If it helps:

torrent: [Oppenheimer (2023) NEW ENG 1080p.MP4.InfosPack022](https://1337x.to/torrent/5829624/Oppenheimer-2023-NEW-ENG-1080p-MP4-InfosPack022/)

<img width="1728" alt="Screenshot 2023-10-12 at 17 36 51" src="https://github.com/Radarr/Radarr/assets/9552100/b22da12d-eed4-4ca2-bc21-b84d604db575">

[radarr.debug.txt](https://github.com/Radarr/Radarr/files/12883795/radarr.debug.txt)

**Comment by bakerboy448** [comment]
please remove the torrent link.

logs won't help this one much; view the history entries and more info to see what the hash of the blocked release is.

**Comment by bakerboy448** [comment]
RCA possibly determined upstream - https://github.com/Sonarr/Sonarr/issues/6108#issuecomment-1767232152

**Comment by bakerboy448** [comment]
hopefully will be fixed upstream soon https://github.com/Sonarr/Sonarr/pull/6138

**Comment by bakerboy448** [comment]
https://github.com/Radarr/Radarr/issues/9420

**Comment by bakerboy448** [comment]
> > #9420
> 
> What this?

The sonarr pull GHI that  _should_ resolve this
