### ISSUE TITLE
Quality being ignored

### ISSUE THREAD

**Issue by donldmn** [Radarr/Radarr#87]
Radarr seems to grab a random quality (so far 720p or 1080p) despite the assigned profile.

I tried a few different combinations of movies, profiles, and size limits and the results are the same.
Radarr does detect the correct quality when searching but it just ignores it.

**Comment by galli-leo** [comment]
Hmm, working fine with me. Could you provide trace logs? Also can you search manually and see, if the movies have a ! next to them?

**Comment by donldmn** [comment]
I added The Lion King with the SD profile

`17-1-10 12:04:32.5|Info|MovieService|Adding Movie [][The Lion King] Path: [D:\MOVIE TESTING FOLDER\COMPLETE\The Lion King (1994)]
17-1-10 12:04:32.5|Info|MediaCoverService|Downloading Poster for [][The Lion King] http://image.tmdb.org/t/p/original/bKPtXn9n4M4s8vvZrbw40mYsefB.jpg
17-1-10 12:04:32.5|Info|RefreshMovieService|Updating Info for The Lion King
17-1-10 12:04:32.7|Info|DiskScanService|Scanning disk for The Lion King
17-1-10 12:04:32.7|Info|MovieScannedHandler|[The Lion King] was recently added, performing post-add actions
17-1-10 12:04:32.7|Info|NzbSearchService|Searching 1 indexers for [The Lion King]
17-1-10 12:04:32.8|Error|EventAggregator|ExtraService failed while processing [MediaCoversUpdatedEvent]

[v0.2.0.45] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Extras.ExtraService.Handle(MediaCoversUpdatedEvent message) in C:\projects\radarr\src\NzbDrone.Core\Extras\ExtraService.cs:line 105
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event) in C:\projects\radarr\src\NzbDrone.Core\Messaging\Events\EventAggregator.cs:line 56

17-1-10 12:04:32.8|Error|EventAggregator|SeriesModule failed while processing [MediaCoversUpdatedEvent]

[v0.2.0.45] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Api.Series.SeriesModule.Handle(MediaCoversUpdatedEvent message) in C:\projects\radarr\src\NzbDrone.Api\Series\SeriesModule.cs:line 239
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event) in C:\projects\radarr\src\NzbDrone.Core\Messaging\Events\EventAggregator.cs:line 56

17-1-10 12:04:32.8|Info|MediaCoverService|Downloading Banner for [tt0110357][The Lion King] http://image.tmdb.org/t/p/original/klI0K4oQMsLhHdjA9Uw8WLugk9v.jpg
17-1-10 12:04:33.2|Error|EventAggregator|ExtraService failed while processing [MediaCoversUpdatedEvent]

[v0.2.0.45] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Extras.ExtraService.Handle(MediaCoversUpdatedEvent message) in C:\projects\radarr\src\NzbDrone.Core\Extras\ExtraService.cs:line 105
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event) in C:\projects\radarr\src\NzbDrone.Core\Messaging\Events\EventAggregator.cs:line 56

17-1-10 12:04:33.2|Error|EventAggregator|SeriesModule failed while processing [MediaCoversUpdatedEvent]

[v0.2.0.45] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Api.Series.SeriesModule.Handle(MediaCoversUpdatedEvent message) in C:\projects\radarr\src\NzbDrone.Api\Series\SeriesModule.cs:line 239
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event) in C:\projects\radarr\src\NzbDrone.Core\Messaging\Events\EventAggregator.cs:line 56

17-1-10 12:04:37.7|Info|DownloadDecisionMaker|Processing 17 releases
17-1-10 12:04:37.7|Info|DownloadDecisionMaker|Spec BlacklistSpecification does not care about movies.
17-1-10 12:04:37.7|Info|DownloadDecisionMaker|Spec AnimeVersionUpgradeSpecification does not care about movies.
17-1-10 12:04:37.7|Info|DownloadDecisionMaker|Spec FullSeasonSpecification does not care about movies.
17-1-10 12:04:37.7|Info|DownloadDecisionMaker|Spec SameEpisodesGrabSpecification does not care about movies.
17-1-10 12:04:37.7|Info|DownloadDecisionMaker|Spec DailyEpisodeMatchSpecification does not care about movies.
17-1-10 12:04:37.8|Info|DownloadDecisionMaker|Spec EpisodeRequestedSpecification does not care about movies.
17-1-10 12:04:37.8|Info|DownloadDecisionMaker|Spec SeasonMatchSpecification does not care about movies.
17-1-10 12:04:37.8|Info|DownloadDecisionMaker|Spec SingleEpisodeSearchMatchSpecification does not care about movies.
17-1-10 12:04:37.8|Info|DownloadDecisionMaker|Spec MonitoredEpisodeSpecification does not care about movies.
17-1-10 12:04:37.8|Info|DownloadDecisionMaker|Spec BlacklistSpecification does not care about movies.
17-1-10 12:04:37.8|Info|DownloadDecisionMaker|Spec AnimeVersionUpgradeSpecification does not care about movies.
17-1-10 12:04:37.8|Info|DownloadDecisionMaker|Spec FullSeasonSpecification does not care about movies.
17-1-10 12:04:37.8|Info|DownloadDecisionMaker|Spec SameEpisodesGrabSpecification does not care about movies.
17-1-10 12:04:37.8|Info|DownloadDecisionMaker|Spec DailyEpisodeMatchSpecification does not care about movies.
17-1-10 12:04:37.8|Info|DownloadDecisionMaker|Spec EpisodeRequestedSpecification does not care about movies.
17-1-10 12:04:37.8|Info|DownloadDecisionMaker|Spec SeasonMatchSpecification does not care about movies.
17-1-10 12:04:37.8|Info|DownloadDecisionMaker|Spec SingleEpisodeSearchMatchSpecification does not care about movies.
17-1-10 12:04:37.8|Info|DownloadDecisionMaker|Spec MonitoredEpisodeSpecification does not care about movies.
17-1-10 12:04:37.8|Info|DownloadDecisionMaker|Spec BlacklistSpecification does not care about movies.
17-1-10 12:04:37.8|Info|DownloadDecisionMaker|Spec AnimeVersionUpgradeSpecification does not care about movies.
17-1-10 12:04:37.8|Info|DownloadDecisionMaker|Spec FullSeasonSpecification does not care about movies.
17-1-10 12:04:37.9|Info|DownloadDecisionMaker|Spec SameEpisodesGrabSpecification does not care about movies.
17-1-10 12:04:37.9|Info|DownloadDecisionMaker|Spec DailyEpisodeMatchSpecification does not care about movies.
17-1-10 12:04:37.9|Info|DownloadDecisionMaker|Spec EpisodeRequestedSpecification does not care about movies.
17-1-10 12:04:37.9|Info|DownloadDecisionMaker|Spec SeasonMatchSpecification does not care about movies.
17-1-10 12:04:37.9|Info|DownloadDecisionMaker|Spec SingleEpisodeSearchMatchSpecification does not care about movies.
17-1-10 12:04:37.9|Info|DownloadDecisionMaker|Spec MonitoredEpisodeSpecification does not care about movies.
17-1-10 12:04:37.9|Info|DownloadDecisionMaker|Spec BlacklistSpecification does not care about movies.
17-1-10 12:04:37.9|Info|DownloadDecisionMaker|Spec AnimeVersionUpgradeSpecification does not care about movies.
17-1-10 12:04:37.9|Info|DownloadDecisionMaker|Spec FullSeasonSpecification does not care about movies.
17-1-10 12:04:37.9|Info|DownloadDecisionMaker|Spec SameEpisodesGrabSpecification does not care about movies.
17-1-10 12:04:37.9|Info|DownloadDecisionMaker|Spec DailyEpisodeMatchSpecification does not care about movies.
17-1-10 12:04:37.9|Info|DownloadDecisionMaker|Spec EpisodeRequestedSpecification does not care about movies.
17-1-10 12:04:37.9|Info|DownloadDecisionMaker|Spec SeasonMatchSpecification does not care about movies.
17-1-10 12:04:37.9|Info|DownloadDecisionMaker|Spec SingleEpisodeSearchMatchSpecification does not care about movies.
17-1-10 12:04:37.9|Info|DownloadDecisionMaker|Spec MonitoredEpisodeSpecification does not care about movies.
17-1-10 12:04:37.9|Info|DownloadDecisionMaker|Spec BlacklistSpecification does not care about movies.
17-1-10 12:04:37.9|Info|DownloadDecisionMaker|Spec AnimeVersionUpgradeSpecification does not care about movies.
17-1-10 12:04:37.9|Info|DownloadDecisionMaker|Spec FullSeasonSpecification does not care about movies.
17-1-10 12:04:37.9|Info|DownloadDecisionMaker|Spec SameEpisodesGrabSpecification does not care about movies.
17-1-10 12:04:38.0|Info|DownloadDecisionMaker|Spec DailyEpisodeMatchSpecification does not care about movies.
17-1-10 12:04:38.0|Info|DownloadDecisionMaker|Spec EpisodeRequestedSpecification does not care about movies.
17-1-10 12:04:38.0|Info|DownloadDecisionMaker|Spec SeasonMatchSpecification does not care about movies.
17-1-10 12:04:38.0|Info|DownloadDecisionMaker|Spec SingleEpisodeSearchMatchSpecification does not care about movies.
17-1-10 12:04:38.0|Info|DownloadDecisionMaker|Spec MonitoredEpisodeSpecification does not care about movies.
17-1-10 12:04:38.0|Info|DownloadDecisionMaker|Spec BlacklistSpecification does not care about movies.
17-1-10 12:04:38.0|Info|DownloadDecisionMaker|Spec AnimeVersionUpgradeSpecification does not care about movies.
17-1-10 12:04:38.0|Info|DownloadDecisionMaker|Spec FullSeasonSpecification does not care about movies.
17-1-10 12:04:38.0|Info|DownloadDecisionMaker|Spec SameEpisodesGrabSpecification does not care about movies.
17-1-10 12:04:38.0|Info|DownloadDecisionMaker|Spec DailyEpisodeMatchSpecification does not care about movies.
17-1-10 12:04:38.0|Info|DownloadDecisionMaker|Spec EpisodeRequestedSpecification does not care about movies.
17-1-10 12:04:38.0|Info|DownloadDecisionMaker|Spec SeasonMatchSpecification does not care about movies.
17-1-10 12:04:38.0|Info|DownloadDecisionMaker|Spec SingleEpisodeSearchMatchSpecification does not care about movies.
17-1-10 12:04:38.0|Info|DownloadDecisionMaker|Spec MonitoredEpisodeSpecification does not care about movies.
17-1-10 12:04:40.6|Info|Sabnzbd|Adding report [The Lion King (1994) 1080p Blu-ray] to the queue.
17-1-10 12:04:42.2|Info|DownloadService|Report sent to sab. The Lion King (1994) 1080p Blu-ray
17-1-10 12:04:42.2|Info|MovieSearchService|Movie search completed. 1 reports downloaded.
17-1-10 12:04:46.7|Error|EventAggregator|QueueService failed while processing [TrackedDownloadRefreshedEvent]

[v0.2.0.45] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Queue.QueueService.<MapQueue>d__6.MoveNext() in C:\projects\radarr\src\NzbDrone.Core\Queue\QueueService.cs:line 47
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NzbDrone.Core.Queue.QueueService.Handle(TrackedDownloadRefreshedEvent message) in C:\projects\radarr\src\NzbDrone.Core\Queue\QueueService.cs:line 39
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event) in C:\projects\radarr\src\NzbDrone.Core\Messaging\Events\EventAggregator.cs:line 56

17-1-10 12:04:49.0|Info|NzbSearchService|Searching 1 indexers for [The Lion King]
17-1-10 12:04:55.4|Info|DownloadDecisionMaker|Processing 17 releases
17-1-10 12:04:55.4|Info|DownloadDecisionMaker|Spec BlacklistSpecification does not care about movies.
17-1-10 12:04:55.4|Info|DownloadDecisionMaker|Spec AnimeVersionUpgradeSpecification does not care about movies.
17-1-10 12:04:55.4|Info|DownloadDecisionMaker|Spec FullSeasonSpecification does not care about movies.
17-1-10 12:04:55.4|Info|DownloadDecisionMaker|Spec SameEpisodesGrabSpecification does not care about movies.
17-1-10 12:04:55.4|Info|DownloadDecisionMaker|Spec DailyEpisodeMatchSpecification does not care about movies.
17-1-10 12:04:55.4|Info|DownloadDecisionMaker|Spec EpisodeRequestedSpecification does not care about movies.
17-1-10 12:04:55.4|Info|DownloadDecisionMaker|Spec SeasonMatchSpecification does not care about movies.
17-1-10 12:04:55.4|Info|DownloadDecisionMaker|Spec SingleEpisodeSearchMatchSpecification does not care about movies.
17-1-10 12:04:55.4|Info|DownloadDecisionMaker|Spec MonitoredEpisodeSpecification does not care about movies.
17-1-10 12:04:55.4|Info|DownloadDecisionMaker|Spec BlacklistSpecification does not care about movies.
17-1-10 12:04:55.4|Info|DownloadDecisionMaker|Spec AnimeVersionUpgradeSpecification does not care about movies.
17-1-10 12:04:55.4|Info|DownloadDecisionMaker|Spec FullSeasonSpecification does not care about movies.
17-1-10 12:04:55.5|Info|DownloadDecisionMaker|Spec SameEpisodesGrabSpecification does not care about movies.
17-1-10 12:04:55.5|Info|DownloadDecisionMaker|Spec DailyEpisodeMatchSpecification does not care about movies.
17-1-10 12:04:55.5|Info|DownloadDecisionMaker|Spec EpisodeRequestedSpecification does not care about movies.
17-1-10 12:04:55.5|Info|DownloadDecisionMaker|Spec SeasonMatchSpecification does not care about movies.
17-1-10 12:04:55.5|Info|DownloadDecisionMaker|Spec SingleEpisodeSearchMatchSpecification does not care about movies.
17-1-10 12:04:55.5|Info|DownloadDecisionMaker|Spec MonitoredEpisodeSpecification does not care about movies.
17-1-10 12:04:55.5|Info|DownloadDecisionMaker|Spec BlacklistSpecification does not care about movies.
17-1-10 12:04:55.5|Info|DownloadDecisionMaker|Spec AnimeVersionUpgradeSpecification does not care about movies.
17-1-10 12:04:55.5|Info|DownloadDecisionMaker|Spec FullSeasonSpecification does not care about movies.
17-1-10 12:04:55.5|Info|DownloadDecisionMaker|Spec SameEpisodesGrabSpecification does not care about movies.
17-1-10 12:04:55.5|Info|DownloadDecisionMaker|Spec DailyEpisodeMatchSpecification does not care about movies.
17-1-10 12:04:55.5|Info|DownloadDecisionMaker|Spec EpisodeRequestedSpecification does not care about movies.
17-1-10 12:04:55.5|Info|DownloadDecisionMaker|Spec SeasonMatchSpecification does not care about movies.
17-1-10 12:04:55.5|Info|DownloadDecisionMaker|Spec SingleEpisodeSearchMatchSpecification does not care about movies.
17-1-10 12:04:55.5|Info|DownloadDecisionMaker|Spec MonitoredEpisodeSpecification does not care about movies.
17-1-10 12:04:55.5|Info|DownloadDecisionMaker|Spec BlacklistSpecification does not care about movies.
17-1-10 12:04:55.5|Info|DownloadDecisionMaker|Spec AnimeVersionUpgradeSpecification does not care about movies.
17-1-10 12:04:55.5|Info|DownloadDecisionMaker|Spec FullSeasonSpecification does not care about movies.
17-1-10 12:04:55.6|Info|DownloadDecisionMaker|Spec SameEpisodesGrabSpecification does not care about movies.
17-1-10 12:04:55.6|Info|DownloadDecisionMaker|Spec DailyEpisodeMatchSpecification does not care about movies.
17-1-10 12:04:55.6|Info|DownloadDecisionMaker|Spec EpisodeRequestedSpecification does not care about movies.
17-1-10 12:04:55.6|Info|DownloadDecisionMaker|Spec SeasonMatchSpecification does not care about movies.
17-1-10 12:04:55.6|Info|DownloadDecisionMaker|Spec SingleEpisodeSearchMatchSpecification does not care about movies.
17-1-10 12:04:55.6|Info|DownloadDecisionMaker|Spec MonitoredEpisodeSpecification does not care about movies.
17-1-10 12:04:55.6|Info|DownloadDecisionMaker|Spec BlacklistSpecification does not care about movies.
17-1-10 12:04:55.6|Info|DownloadDecisionMaker|Spec AnimeVersionUpgradeSpecification does not care about movies.
17-1-10 12:04:55.6|Info|DownloadDecisionMaker|Spec FullSeasonSpecification does not care about movies.
17-1-10 12:04:55.6|Info|DownloadDecisionMaker|Spec SameEpisodesGrabSpecification does not care about movies.
17-1-10 12:04:55.6|Info|DownloadDecisionMaker|Spec DailyEpisodeMatchSpecification does not care about movies.
17-1-10 12:04:55.6|Info|DownloadDecisionMaker|Spec EpisodeRequestedSpecification does not care about movies.
17-1-10 12:04:55.6|Info|DownloadDecisionMaker|Spec SeasonMatchSpecification does not care about movies.
17-1-10 12:04:55.6|Info|DownloadDecisionMaker|Spec SingleEpisodeSearchMatchSpecification does not care about movies.
17-1-10 12:04:55.6|Info|DownloadDecisionMaker|Spec MonitoredEpisodeSpecification does not care about movies.
17-1-10 12:04:55.6|Info|DownloadDecisionMaker|Spec BlacklistSpecification does not care about movies.
17-1-10 12:04:55.6|Info|DownloadDecisionMaker|Spec AnimeVersionUpgradeSpecification does not care about movies.
17-1-10 12:04:55.6|Info|DownloadDecisionMaker|Spec FullSeasonSpecification does not care about movies.
17-1-10 12:04:55.7|Info|DownloadDecisionMaker|Spec SameEpisodesGrabSpecification does not care about movies.
17-1-10 12:04:55.7|Info|DownloadDecisionMaker|Spec DailyEpisodeMatchSpecification does not care about movies.
17-1-10 12:04:55.7|Info|DownloadDecisionMaker|Spec EpisodeRequestedSpecification does not care about movies.
17-1-10 12:04:55.7|Info|DownloadDecisionMaker|Spec SeasonMatchSpecification does not care about movies.
17-1-10 12:04:55.7|Info|DownloadDecisionMaker|Spec SingleEpisodeSearchMatchSpecification does not care about movies.
17-1-10 12:04:55.7|Info|DownloadDecisionMaker|Spec MonitoredEpisodeSpecification does not care about movies.
17-1-10 12:05:17.7|Error|EventAggregator|QueueService failed while processing [TrackedDownloadRefreshedEvent]

[v0.2.0.45] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Queue.QueueService.<MapQueue>d__6.MoveNext() in C:\projects\radarr\src\NzbDrone.Core\Queue\QueueService.cs:line 47
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NzbDrone.Core.Queue.QueueService.Handle(TrackedDownloadRefreshedEvent message) in C:\projects\radarr\src\NzbDrone.Core\Queue\QueueService.cs:line 39
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event) in C:\projects\radarr\src\NzbDrone.Core\Messaging\Events\EventAggregator.cs:line 56

17-1-10 12:05:46.7|Error|EventAggregator|QueueService failed while processing [TrackedDownloadRefreshedEvent]

[v0.2.0.45] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Queue.QueueService.<MapQueue>d__6.MoveNext() in C:\projects\radarr\src\NzbDrone.Core\Queue\QueueService.cs:line 47
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NzbDrone.Core.Queue.QueueService.Handle(TrackedDownloadRefreshedEvent message) in C:\projects\radarr\src\NzbDrone.Core\Queue\QueueService.cs:line 39
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event) in C:\projects\radarr\src\NzbDrone.Core\Messaging\Events\EventAggregator.cs:line 56

17-1-10 12:05:46.8|Info|RssSyncService|Starting RSS Sync
17-1-10 12:05:49.7|Info|DownloadDecisionMaker|Processing 100 releases
17-1-10 12:05:50.2|Info|RssSyncService|RSS Sync Completed. Reports found: 100, Reports grabbed: 0
17-1-10 12:06:16.9|Error|EventAggregator|QueueService failed while processing [TrackedDownloadRefreshedEvent]

[v0.2.0.45] System.NullReferenceException: Object reference not set to an instance of an object.
   at NzbDrone.Core.Queue.QueueService.<MapQueue>d__6.MoveNext() in C:\projects\radarr\src\NzbDrone.Core\Queue\QueueService.cs:line 47
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NzbDrone.Core.Queue.QueueService.Handle(TrackedDownloadRefreshedEvent message) in C:\projects\radarr\src\NzbDrone.Core\Queue\QueueService.cs:line 39
   at NzbDrone.Core.Messaging.Events.EventAggregator.PublishEvent[TEvent](TEvent event) in C:\projects\radarr\src\NzbDrone.Core\Messaging\Events\EventAggregator.cs:line 56
`
http://imgur.com/1I3ipFf

**Comment by dawtmaytrikx** [comment]
I'm gonna chime in here because I think my bug is related: Radarr also grabs files despite containing strings on the blacklist/not containing strings on the whitelist. When I manually search for the files however the releases it auto-dl's correctly show up with the red ! next to them. My logs look essentially like donldmn's.

**Comment by galli-leo** [comment]
This issue should be fixed in the last commit.
