### ISSUE TITLE
Updating using Winget changes the service log on account, can cause "Missing root folder"

### ISSUE THREAD

**Issue by ak47uk** [Radarr/Radarr#8703]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When Radarr updates via winget, it overwrites the service log on account with "Local Service". This can break access to file shares with errors such as:
Missing root folder
Import failed, path does not exist or is not accessible by Sonarr
Unable to find a volume mounted for the path

Editing the service's log on account to set it back to the local user that has permissions to access the file shares (UNC paths) fixes it. 

### Expected Behavior

When updating the program using Winget, the existing log on account for the service would be preserved. 

### Steps To Reproduce

Install Radarr
Configure as necessary
Set the service log on account to a local user that has permissions to access network file shares
Update Radarr using winget (in cmd/terminal `winget update TeamRadarr.Radarr`) the service log on account will revert to "Local Service"

### Environment

```markdown
- OS: Windows 10 Pro
- Radarr: 4.6.2.7485
- Browser: Edge Chromium
- Database: Sqlite 3.36.0
```

### What branch are you running?

Master

### Trace Logs?

N/A

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have followed the steps in the wiki link above and provided the required trace logs that are relevant and show this issue.

**Comment by ak47uk** [comment]
> Contact winget for support with their third party packaging of radarr & breaking of radarr installs with the user change

Winget pulls from this repo, it doesn't repackage Radarr.
```
winget install TeamRadarr.Radarr
Found Radarr [TeamRadarr.Radarr] Version 4.5.2
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/Radarr/Radarr/releases/download/v4.5.2.7388/Radarr.master.4.5.2.7388.windows-core-x64-installer.exe
```

**Comment by RobinDadswell** [comment]
We didn't upload the manifest to winget for this - however it is because it upgrades via the installer and our automatic updates are done in a different manner (we replace the files). 

There is no need to do upgrades via winget due to the in-app updates

**Comment by ak47uk** [comment]
> We didn't upload the manifest to winget for this - however it is because it upgrades via the installer and our automatic updates are done in a different manner (we replace the files).
> 
> There is no need to do upgrades via winget due to the in-app updates

Thanks, I have added it as an exclusion to my winget auto-update script.
