### ISSUE TITLE
Show Open/Play button on hover

### ISSUE THREAD

**Issue by Milincho** [Radarr/Radarr#8704]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

No way to open the file directly.

### Describe the solution you'd like

An Open/Play button on hover that would open the file with the system's default association.

![image](https://github.com/Radarr/Radarr/assets/60118859/d24b36e6-813a-4651-b8de-f6adc31b1091)

### Describe alternatives you've considered

It would be great to have it also inside the page:
![image](https://github.com/Radarr/Radarr/assets/60118859/e9eb5ce0-9c48-4998-99be-0caef30911b8)

### Anything else?

No.

**Comment by bakerboy448** [comment]
Related to https://github.com/Radarr/Radarr/issues/5757
related to #7229

no plans for the same reasons as no open to click file path support

Also likely duplicate as well, but cannot easily find the dupe
