### ISSUE TITLE
Filter Collections by Missing Movies

### ISSUE THREAD

**Issue by cevznriny** [Radarr/Radarr#8707]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I would like to be able to filter the Collections by Missing Movies like in the Movies list, please.

### Describe the solution you'd like

A Missing Movies filter in Collections.

### Describe alternatives you've considered

Manually looking through all of the collections.

### Anything else?

It should be relatively easy as there is already a tag in Collections showing how many movies are missing.

**Comment by bakerboy448** [comment]
Duplicate of https://github.com/Radarr/Radarr/issues/7338
