### ISSUE TITLE
Column Widths in Table View

### ISSUE THREAD

**Issue by stevenolsen** [Radarr/Radarr#871]
The row formatting is double high because of 'in cinemas' and 'links' in many cases.

![capture](https://cloud.githubusercontent.com/assets/5187453/23299451/7c7d09de-fa36-11e6-814d-e56099bdd3e3.JPG)

The interface is about 1200 pixels wide currently and that's creeping near older laptop widths so I'm not sure the answer is "just make the interface wider". A dynamically scaling width would be fantastic. Another option would be to abbreviate the months and year (September 2016 -> Sept. '16). #511 is worth referencing here, but they are separate.

I'm not sure the ratio of people who wait for a Bluray release before they download but I'm one of them. 'In Cinemas' is nice, but I would much rather see 'Bluray Release'. Could this be a toggle option? I'd much rather see 'Unknown' or left blank under Bluray release than an 'in Cinemas' date from 4 months ago. Both columns would be ideal but the real estate just isn't there.

A few changes to Links would be nice. To make them fit shortening "The Movie DB" down to "Movie DB". Perhaps shortening "Homepage" to "Studio", maybe "Promo"? I got nothing, but I would like to see the goal to be fitting the maximum amount of links onto a single line. Colourizing the links would be nice as shown.
![highlights](https://cloud.githubusercontent.com/assets/5187453/23300360/033164ae-fa3a-11e6-806f-7b5bf44f43e2.jpg)

**Comment by stevenolsen** [comment]
As a follow-up. How necessary is the Profile column? I'd wager over 95% of people use one profile for everything. Just a suggestion to acquire more space.

**Comment by delphiactual** [comment]
or just show short dates in locale (e.g. 2/24/17, 24/2/17)

**Comment by galli-leo** [comment]
We want to replace the links with images. So that would shorten them quite a bit.

**Comment by stevenolsen** [comment]
If each row is locked in height it doesn't really matter. I don't mind the text buttons. It's table view, I don't feel it needs to be pretty, just readable and presentable. Thanks for listening. 👍

**Comment by onedr0p** [comment]
FIxed in next release
