### ISSUE TITLE
Can't run Radarr on M2

### ISSUE THREAD

**Issue by cscetbon** [Radarr/Radarr#8711]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Radarr fails to start

### Expected Behavior

Radarr should start

### Steps To Reproduce

1. brew install radarr
2. try to run it
```
$ file /Applications/Radarr.app/Contents/MacOS/Radarr
/Applications/Radarr.app/Contents/MacOS/Radarr: Mach-O 64-bit executable arm64
$ uname -a
Darwin Unleash-2022.local 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:52:43 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T8112 arm64
```

### Environment

```markdown
- OS: MacOs 13.4
- Radarr: 4.5.2.7388
```

### What branch are you running?

Master

### Trace Logs?

NA it doesn't even start even after having passed the security phase in MacOS. It was working with previous versions before I upgraded using `brew upgrade radarr`

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have followed the steps in the wiki link above and provided the required trace logs that are relevant and show this issue.

**Comment by bakerboy448** [comment]
The radarr team does not maintain, create, nor support the brew package - contact the creator of the package for support with their third party application

otherwise, see the official installation instructions on the wiki

**Comment by cscetbon** [comment]
> ~/.config/Radarr/Logs

Because there are no logs at all 🤷 it crashes before it even starts it seems

**Comment by cscetbon** [comment]
> Then check the Console app, you have reports there like crash reports.

I did and there is nothing. Also the brew formulae just downloads your binary and installs it, nothing else.

**Comment by bakerboy448** [comment]
So the brew formula doesn't match the install docs and thus presumably fails to self sign the app..?  That'd be the issue

**Comment by cscetbon** [comment]
Yes I'm passed all of this and it just gets killed in a terminal with no explicit reason

**Comment by cscetbon** [comment]
> > I did and there is nothing. Also the brew formulae just downloads your binary and installs it, nothing else.
> 
> Are you sure it's a formula? It should be a cask.
> 
> You need to figure out why is failing after a upgrade, because currently there's isn't anyone with a M2 Mac on the dev team.

It's a cask but there is a corresponding formula no matter what 
```
$ brew cat radarr|head -2
cask "radarr" do
  arch arm: "arm64", intel: "x64"
```

```
$ brew install radarr
==> Downloading https://github.com/Radarr/Radarr/releases/download/v4.5.2.7388/Radarr.master.4.5.2.7388.osx-app-core-arm64.zip
Already downloaded: /Users/cscetbon/Library/Caches/Homebrew/downloads/c928e3106be82ab61adf1f46cdb28ad97d7af32169f4b9312e0466caca92c0bc--Radarr.master.4.5.2.7388.osx-app-core-arm64.zip
==> Installing Cask radarr
==> Moving App 'Radarr.app' to '/Applications/Radarr.app'
🍺  radarr was successfully installed!
```

**Comment by cscetbon** [comment]
So something weird @mynameisbogdan. I was able to open it after I used `codesign --force --deep -s - /Applications/Radarr.app`. However before that, like I said, I did already authorize it to run in Settings -> Privacy & Security, so there must be something new or hidden, or it comes from 13.4 ....

**Comment by bakerboy448** [comment]
Self signing the app has been a requirement for a while - hence why the instructions note it as required;  the other security settings are different than that

the brew maintainer should be contacted to update their formula to self sign the app if possible....or add some instructions to do so post-install

**Comment by cscetbon** [comment]
It's weird to not see any messages ...

**Comment by bakerboy448** [comment]
mac's security completely prevents it from executing and doesn't display any messages annoyingly.

yell at apple :D

**Comment by NoSoyJoselito** [comment]
> So something weird @mynameisbogdan. I was able to open it after I used `codesign --force --deep -s - /Applications/Radarr.app`. However before that, like I said, I did already authorize it to run in Settings -> Privacy & Security, so there must be something new or hidden, or it comes from 13.4 ....

That worked for me. Thanks

**Comment by cscetbon** [comment]
> mac's security completely prevents it from executing and doesn't display any messages annoyingly.
> 
> yell at apple :D

But why on that one and not on Sonarr ? Is it because my version hasn't been upgraded since my last OS upgrade ?
