### ISSUE TITLE
Radarr downloading the same movie NZB multiple times

### ISSUE THREAD

**Issue by david-steg** [Radarr/Radarr#8719]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Hello
like the old closed issue https://github.com/Radarr/Radarr/issues/1108.

I have the issue that Radarr put the same Movie multiple times in the qeue, it can be an different Version, or the identical.
![Capture](https://github.com/Radarr/Radarr/assets/71213394/4a969465-c6b6-4ee6-af76-18721cf06ad8)

I seems to appends when I add multiple (different) Movies at the same time. 
To the Logs, it seems to abort the queue Upload, with the message "Software caused connection abort".
Radarr and SABnzbd run on the same Hypervisor, in the same VLAN, the network is rock solid.
I installed Radarr on Ubuntu 20.04 with the Arr* Script. I even try the develop Version 4.6.2.7490, same issue.
I tried nzbget and SABnzbd, same issue.
I tried to set the Delay Profile to 60', but it didn't helps.

Thanks in advance!

### Expected Behavior

Download the Movie just on Time.

### Steps To Reproduce

1. add multiple Movie at the same time
2. Wait to automatic add to queue.
3. Check Queue

### Environment

```markdown
- OS: Ubuntu 20.04
- Radarr: 4.6.2.7490 AND 4.5.2.7388
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Chrome
- Database: Sqlite 3.31.1
- .NET 6.0.16
```

### What branch are you running?

Master

### Trace Logs?

[logs.txt](https://github.com/Radarr/Radarr/files/11793765/logs.txt)

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have followed the steps in the wiki link above and provided the required trace logs that are relevant and show this issue.

**Comment by david-steg** [comment]
Correction: 
Expected Behavior
Download the Movie just one time.

**Comment by bakerboy448** [comment]
- Info logs are not the required trace logs you lied and incorrectly claimed you followed the wiki to provide
- v4.6.2 is not a master release at this time
- appears you have network issues
