### ISSUE TITLE
Cant Bulk import from folders?

### ISSUE THREAD

**Issue by tiddles155** [Radarr/Radarr#872]
**Description:**

cant use the bulk import function, i seledct the folder and it always shows no movies available, this is the same for 2 different folders.

0.2.0.375

17-2-24 19:44:56.3|Warn|SkyHookProxy|Couldn't map movie Dragonball Z Movies to a movie on The Movie DB. It will not be added :(
17-2-24 19:44:57.8|Warn|SkyHookProxy|Couldn't map movie Dragonball Z Movies to a movie on The Movie DB. It will not be added :(

thats all i get when trying to bulk add movies

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by jpborjas** [comment]
Same for me.

**Comment by fedoranimus** [comment]
How are your movies structured in those folders you tried to add?

**Comment by RaphaelJenni** [comment]
Same here.
My movies are structured as following:
/video/Downloads/
- movie1.mkv
- movie2.mp4
- ...

**Comment by onedr0p** [comment]
@RaphaelJenni we plan on support flat folder of movies in the future, but not any time soon enough.

We have a wiki article here on how to move them https://github.com/Radarr/Radarr/wiki/How-to-Create-a-Folder-for-Each-Movie

**Comment by Anakim** [comment]
same for me
my movies in folders but two films are not imported
i can't see any differents between the other folders and movies
access rights ok, 
17-8-10 21:14:49.6|Warn|SkyHookProxy|Couldn't map movie Project Almanac to a movie on The Movie DB. It will not be added :(

**Comment by jrizz43** [comment]
"Planned to be supported" that kind of sucks for anyone with a current media library. If i put them all into folders now my Plex server will go batshit crazy saying it doesn't know where any of the files are...fun

**Comment by fhscholl** [comment]
Except it won't. When Plex updates the library it will find the files in their new location.

**Comment by jrizz43** [comment]
Mine shows 2 files then, 1 unavailable and the new one

**Comment by cbussa** [comment]
onedr0p commented on Feb 25, 2017

@RaphaelJenni We have a wiki article here on how to move to move them https://github.com/Radarr/Radarr/wiki/How-to-Create-a-Folder-for-Each-Movie

Well, we have an article there **NOW**, anyway.  (What's 18 months between friends?) Should work / be close to working (I ran 'em on my system earlier to do just that) but I'm in a hurry right now so it's a bit verbose and probably sarcastic as well.  Fix to taste.
