### ISSUE TITLE
Just installed Radarr and added an Indexer (Jackett/IPTorrents) but Radarr does not use it

### ISSUE THREAD

**Issue by Lusiphur** [Radarr/Radarr#873]
I added a movie I knew a relevant version was available for on IPTorrents. Search doesn't look at any indexers although I have one set up. These indexer settings work fine in Sonarr.

![image](https://cloud.githubusercontent.com/assets/10370854/23306080/9d01aef4-fa99-11e6-9a33-c1bd5e98baeb.png)

**Radarr Version:**
![image](https://cloud.githubusercontent.com/assets/10370854/23306096/b7459686-fa99-11e6-8dc0-a2601c17f1d3.png)

**Logs:**
	NzbSearchService	Searching 0 indexers for [Wanted]	1:49pm

Now it uses the indexer but I get

An error occurred while processing feed. http://192.168.1.105:9117/torznab/iptorrents/api?t=movie&cat=2000,2010,2020,2030,2035,2040,2045,2050,2060&extended=1&apikey=(removed)&offset=0&limit=100&imdbid=0493464: Torznab error detected: Incorrect parameter: invalid imdbid format

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by onedr0p** [comment]
NzbSearchService? For torrents?

**Comment by Lusiphur** [comment]
Exactly. That's a torznab indexer I have set up.

**Comment by onedr0p** [comment]
Could you try the TorrentPotato? Sadly, I do not have IPTorrents to test.

**Comment by onedr0p** [comment]
Also make sure your Jackett is up to date.

**Comment by Lusiphur** [comment]
Torrent Potato doesn't work at all.

**Comment by onedr0p** [comment]
Looking thru Jackett source code they didn't change anything recently, do you have another indexer you can test with torznab?

**Comment by Lusiphur** [comment]
![image](https://cloud.githubusercontent.com/assets/10370854/23306792/f0964d1a-fa9c-11e6-8256-904df0b4f5d4.png)

**Comment by Lusiphur** [comment]
I have two indexers in Sonarr on the same server. Both of those work fine. Unfortunately the other indexer is TV only.

**Comment by onedr0p** [comment]
Hm interesting, I have no idea what is causing that issue. I have multiple indexers set up using Torznab and I have no problems here. BTW the latest Jackett version I think is `Jackett Version 0.7.1075.0` You are quite behind.

**Comment by Lusiphur** [comment]
I suspect it is the Jackett version. The updater never seems to work on Linux. I will update manually now.

**Comment by Lusiphur** [comment]
Finally got Jackett updated to the new version. It all works fine now. Please close and thanks for the help.
