### ISSUE TITLE
Ability to use subtitle files detected in release in custom format score?

### ISSUE THREAD

**Issue by douglas24** [Radarr/Radarr#8749]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I would like to be able to set a custom format score for releases with subtitles for deaf viewers so I can prioritize them.

### Describe the solution you'd like

The ability to set a custom format score for releases with files that match what a user sets (similar to the Import Extra Files in Media Management). For example being able to set a string match of "sdh.srt" as 999 score, "srt" as 998 score, and "forced.srt" as 997 score so that radarr would rank a release with deaf and hard of hearing subtitle file(s) higher than a release with basic subtitles with both higher than the subtitle files which only play during non-English scenes.

### Describe alternatives you've considered

The only alternative is manually searching for sdh subtitle files elsewhere. I find sometimes alternate-sourced subtitles do not match video timestamps and scene movement, but the srt files within a release always match because they were from the same source and made by the same creator.

### Anything else?

I don't know how the filetype match coding in the Media Management settings works, but I'm hoping it might be an easy thing to copy into the custom format settings.

**Comment by bakerboy448** [comment]
There's no data available in for Radarr to identify any given release from an indexer has subs so this functionality is not possible to facilitate grabbing any release over another.

if your preferred releases included something in the naming; this can already be done with the release title custom format....same with groups you know that include them.

generally you'd likely want to target Remux or webdl for all the subs being existing embedded in the file
