### ISSUE TITLE
No indexers to choose from

### ISSUE THREAD

**Issue by amanzone** [Radarr/Radarr#875]
**Description:**

Hi there. I'm having an issue with Radarr. I don't have any indexers to coose from when I try to add one.
When I click on the "+" icon to add one it only opens a popup where it statees "Radarr supports any indexer that uses the Newznab standard, as well as other indexers listed below.
For more information on the individual indexers, click on the info buttons."

There's none I can select. Would you please be able to tell me how to proceed?

Thanks in advance for any help you can provide me.

Alberto

**Radarr Version:**
 0.2.0.375

**Logs:**
No related entry

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by onedr0p** [comment]
Seems like your data might have gotten corrupt.. You may want to start from scratch if that isn't a big hassle for you. As we are in alpha, these things are bound to happen.

**Comment by amanzone** [comment]
Thanks for your reply.
I just did as you suggested but nothing changed.

Maybe it's better that I attach here the log file generated now that I started from scratch.
[radarr.txt](https://github.com/Radarr/Radarr/files/799983/radarr.txt)

**Comment by amanzone** [comment]
By the way, I don't know what migration this log is talking about. This is the first installation of Radarr I ever had...

**Comment by onedr0p** [comment]
Migrations are run on update or install to get the database set up.

I just installed radarr from scratch and I cannot replicate your issue.. Do you have another machine you can test this on? Try incognito window in your browser too.

**Comment by amanzone** [comment]
Thanks, you nailed it. Sure enough incongnito browser seems to solve the issue.

Thank you very much, I owe you.

**Comment by onedr0p** [comment]
To fix without incognito, clear your browser cache.
