### ISSUE TITLE
Flatpak version

### ISSUE THREAD

**Issue by logos88** [Radarr/Radarr#8753]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Nowadays Flatpak is becoming the new standar method in Linux to install packages, but Radarr doesn't offer it.

### Describe the solution you'd like

It would facilitate a lot the installation if Radarr would provide a Flatpak package, and even better if it would be officially uploaded to Flathub

### Describe alternatives you've considered

Snap or Appimage have lot less adoption

### Anything else?

https://docs.flatpak.org/en/latest/introduction.html
https://flathub.org

**Comment by bakerboy448** [comment]
Duplicate of https://github.com/Radarr/Radarr/issues/4551
