### ISSUE TITLE
[API] SizeOnDisk is 0 on Request by movieId

### ISSUE THREAD

**Issue by mikey2p22** [Radarr/Radarr#876]
As the Title says. The Field SizeOnDisk is correct if the whole MovieList is requested.
If the Movie is requested by id, the Field SizeOnDisk is 0.

List Request: 
![image](https://cloud.githubusercontent.com/assets/18078206/23314784/a50104fe-fac3-11e6-9191-ea8cb500d220.png)

Single Request:
![image](https://cloud.githubusercontent.com/assets/18078206/23314759/95d9987e-fac3-11e6-8e7d-55551863fc69.png)

**Comment by onedr0p** [comment]
For now you can grab the Size in the movieFile JSON property

**Comment by mikey2p22** [comment]
Yeah, that's what I did. I just wanted to let you know.
Thanks anyway.

**Comment by galli-leo** [comment]
this is fixed.
