### ISSUE TITLE
Manual import shows all movies even the ones already in Radarr media

### ISSUE THREAD

**Issue by jpdsc** [Radarr/Radarr#8764]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When performing Interactive manual import, it also shows all the movies already available in Radarr media.
I took Extraction (2020) as an example.

Movie path in Radarr: `/shared/Downloads/Movies/Extraction (2020) {imdb-tt8936646}`
Relative path in Radarr: `/shared/Downloads/Movies/Extraction (2020) {imdb-tt8936646}/Extraction (2020) {imdb-tt8936646} [NF Hybrid][WEBDL-2160p][DV HDR10][EAC3 Atmos 5.1][HEVC]-SiC.mkv`

Interactive manual import using folder: `/shared/Downloads/Movies/`
![image](https://github.com/Radarr/Radarr/assets/7014736/5fcb4eb9-0cc8-4d9b-8f15-c304e2a5b610)

Post import History tab:
![image](https://github.com/Radarr/Radarr/assets/7014736/38abdf99-1850-4deb-b1b9-782884a8831f)

Files tab:
![image](https://github.com/Radarr/Radarr/assets/7014736/1b04c25a-fc59-45f1-b93d-f0f782521e5f)

Going back to manual import now shows the movie again the list with a checkmark.

Note: `/shared/Downloads/Movies` is the final movie folder which is where Radarr imports unpacked movies.

### Expected Behavior

I'm not sure if this is intended or not, however, shouldn't manual import only show movies which are not in Radarr media and therefore can be imported manually (including adding missing information such as resolution etc)?
Having all the movies there will be endless scrolling until you find a movie which is not in Radarr media but in the final Movies folder.

### Steps To Reproduce

1. Use develop version 4.6.3.7516
2. Successfully import a movie in Radarr
3. Start manual import
4. The movie just imported successfully by Radarr is in the list to be manually imported
5. Check movie history tab, you'll see the relative path with a bin icon
6. You can do loop from step 3

### Environment

```markdown
- OS: Debian
- Radarr: 4.6.3.7516
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Edge
- Database: Sqlite 3.41.2
```

### What branch are you running?

Develop

### Trace Logs?

[radarr.trace.txt](https://github.com/Radarr/Radarr/files/11937099/radarr.trace.txt)

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
Not a bug....this is expected

manual import shows all files in a folder and matches them to existing movies if under 100 files

there's really no valid use case why one should be pointing manual import at their library folder.
