### ISSUE TITLE
When Radarr runs as a service in Windows, cannot see mapped network drives

### ISSUE THREAD

**Issue by bartolomesoriano** [Radarr/Radarr#877]
**Description:**

If I run Radarr as a service under Windows 10, then the program does not see any mapped network drives, and thus I cannot import my existing movie collection that resides in my NAS.

**Radarr Version:**

0.2.0.375

**Logs:**

Even if I change the service to run under a local account and not the system account, it still does not see mapped network drives (and there is no option to specify UNC paths).  If I uninstall the service and run Radarr directly, then it does see all mapped network drives.

**Comment by chansearrington** [comment]
+1

**Comment by galli-leo** [comment]
Well if it worked for you when not running as a service there is nothing much we can do :/. According to the guys over at Sonarr it's a slim chance that network drives will work with an application running as a service.
