### ISSUE TITLE
[Request] Add 'delete selected' button on Wanted page 

### ISSUE THREAD

**Issue by d0t1q** [Radarr/Radarr#878]
**Description:**

Would be nice if there was a delete all selected button on the wanted page - my imported Couch Potato list was about 60+ and I recently changed my folder structure so atm I either have to go in and change all of their folders or delete and re-add under the new folder, only problem is there's 60+ of them.

Thanks 

**Radarr Version:** 0.2.0.375

**Comment by onedr0p** [comment]
We will add a delete to the Movie Editor, I think that's the only place we want it...

**Comment by d0t1q** [comment]
But movie editor is only for each individual movie right? So you'd have to manually go through an edit each movie. That hierarchy of management  would make sense for Sonarr because you're only managing a few tv shows and a ton of episodes, but for Radarr you're managing a more individual entries. Mass managment just makes sense for radarr rather than sonarr.

**Comment by onedr0p** [comment]
Well we would add more filtering options, so you can get your desired request, we can apply same filters that are on the movie list page.

![image](https://cloud.githubusercontent.com/assets/213795/23335466/064268b4-fb84-11e6-8279-f40402820f57.png)

**Comment by geogolem** [comment]
I think the movieEditor and inline delete button as @bassrock  are both good... and complementary... i think it would be useful to separate Delte and Edit out.. so when you click Edit you get the edit dialog (without the delete options).. when you click delete you get the delete dialog..

and then a Delete all selected button the movie editor..

I think those two things would be suficient..

**Comment by hilljd00** [comment]
It would be great if you could mass select all wanted movies to be able to delete in bulk. Removing one at a time is a pain!

I have over 200 in wanted

**Comment by onedr0p** [comment]
Using filters in the movie editor when we add mass delete should be sufficient, closing this issue.

**Comment by nifharv** [comment]
When are you planning on adding this? would be very useful...

**Comment by WhySoSaurus** [comment]
looking forward to this functionality

**Comment by ascottmccauley** [comment]
+1, urgently need this. Right now removing movies is painfully difficult. I have hundreds of movies that I don't want downloaded that I have to dig through every time I want to find the one that I do, and I don't want to open each one and "Exclude movie from Auto List Import" them. 

Monitored/unmonitored makes sense for TV shows, but movies, just need "Managed", "Wanted", and "Blacklisted".

**Comment by wrapper** [comment]
+1

**Comment by d0t1q** [comment]
@galli-leo which is not what was requested from this issue, they are supporting the request not the built in feature. 

If you are unable to add new features that are being requested either due to understanding of code or lacking in time just close the request.

**Comment by jstevenson72** [comment]
Can you at least please add either **Wanted** as a filter to the Movie Editor, so I can delete the 68 movies I accidentally added via a "List"; or put a **Delete** button on the Wanted page?

**Comment by Qstick** [comment]
Likely not going to happen, but this can be done in Aphrodite (V2). So you can rest assured knowing it'll be in the next major version when it's done.

**Comment by jstevenson72** [comment]
Is Aphrodite functional? Is there a Windows build? Thanks!

**Comment by Qstick** [comment]
It's somewhat functional, still a few things broken. There are appveyor generated windows builds. I wouldn't recommend using it yet as your main instance, only if you want to help with testing/development.
