### ISSUE TITLE
Filters on Home Page no longer working - Nightly Updates

### ISSUE THREAD

**Issue by fash202** [Radarr/Radarr#880]
I use the nightly updates branch and it seems over last last ~12hours an update has broken the filters in the movies page. 

Currently all my movies are viewable even when selecting "missing only" and selecting different options doesn't seem to have any effect.

**Comment by onedr0p** [comment]
try in incognito

**Comment by fash202** [comment]
Actually looking closer it doesnt show any of my missing movies only Downloaded movies, even when wanting to show all monitored.

**Comment by onedr0p** [comment]
Update again, that was fixed.
