### ISSUE TITLE
Radarr changes the letter case in edition tag

### ISSUE THREAD

**Issue by edrock200** [Radarr/Radarr#8805]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When an edition tag is all caps, like "IMAX" radarr changes it in the filename to Imax.

### Expected Behavior

Keeps the case the same as entered into edition field 

### Steps To Reproduce

1. Have a file naming convention that includes the edition tag as part of the filename. 
2. Mark the edition as "IMAX"
3. Click rename
4. Observe the changing of the edition letter case.

### Environment

```markdown
- OS: ubuntu 18.04
- Radarr: 4.7.1.7625
- Docker Install: linuxserver version
- Using Reverse Proxy: yes nginx
- Browser: chrome latest prod
- Database: Sqlite 3.41.2
```

### What branch are you running?

Nightly

### Trace Logs?

Can provide if needed but easily reproduceable

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by Qstick** [comment]
Dupe #7649
