### ISSUE TITLE
Cannot change default folder for downloads

### ISSUE THREAD

**Issue by bartolomesoriano** [Radarr/Radarr#884]
**Description:**

Have not found where to change the default folder for downloaded movies.

**Radarr Version:**
0.2.0.375

**Logs:**

Where can I change what the default path is for downloading movies? it seems to default to the Radarr install path + "Select Path", so in my case "F:\Radarr\Select Path".  I have not found anywhere in the UI where you can specify this path.  This would be incredibly useful, so that whenever a movie is added, manually or from a list, this path would be used.  Now I have to go and edit every single movie and change the path.

**Comment by onedr0p** [comment]
Granted it's not intuitive, you need to set up paths before anything else in Radarr. You can get to the Root folders by searching for any movie and Select Add new path. in the options for that movie.

**Comment by bartolomesoriano** [comment]
I am sorry, but I cannot see any option to add new path.  You mean when you select the "Edit Movie" option? Or is this somewhere else? Please clarify.  Thanks. A screenshot would be of great help to me.

**Comment by onedr0p** [comment]
Search for any movie, and choose the path, you'll see select a different path
