### ISSUE TITLE
Post-Import Category based on used Indexer

### ISSUE THREAD

**Issue by Seroczynski** [Radarr/Radarr#8848]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I like to have my downloads labelled in rTorrent. For this I use the source tracker, i.e. if I download something from tracker A, B or C, I label my downloads accordingly.

Recently I started using another indexer in Radarr. This indexer has Priority 2, and is sometimes used to download content from. However, where I previously used a static value for the Post-Import Category, this does not seem to work with my personal method of labeling.

### Describe the solution you'd like

It would be great if there was some way to use a variable or setting that would allow for the Indexer to be used as Post-Import Category. When searching for content, I notice the name of the Indexer being shown in the result. To me, this looks to be an opening to a possible feature being implemented.

### Describe alternatives you've considered

Since I do now know if or how other people label their content, I can imagine I have to resort to using a global Post-Import Category.

### Anything else?

Even thought this come from a personal preference, I think there are more people that for some reason could benefit from this feature.

**Comment by bakerboy448** [comment]
This can already be accomplished with download clients configured per indexer and duplicating the download client with unique post-import categories as needed.
