### ISSUE TITLE
Update movie directory when refreshing metadata

### ISSUE THREAD

**Issue by ryanwalder** [Radarr/Radarr#8854]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

If you add a movie and the name/year/etc. changes between adding and release the directory it's stored in may have the incorrect name/year.

Example:

Directory naming structure: `{Movie Title} ({Release Year})`

1. Add a new unreleased movie as soon as it's confirmed
    * This is titled `Unreleased FooBar Movie (2022)` in TMDB at this point
    * Directory is locked into `/path/to/movies/Unreleased FooBar Movie (2022)`
2. Time passes and the TMDB is update with the actual Movie name and release date, Radarr refreshes the Metadata and it updates in the Radarr db/ui
    * Movie Title: `FooBar 7:  Electric Boogaloo`
    * Year: `2024`
    * **Does NOT** Update directory name
3. More time passes and the Movie is released
    * Film is downloaded
    * Radar puts it in `/path/to/movies/Unreleased FooBar Movie (2022)`
    * It should be put in `/path/to/movies/FooBar 7  Electric Boogaloo (2023)`

### Describe the solution you'd like

This could be resolved a couple of ways:

1. When refreshing metadata (and it changes) update target directory if:
    1. The film has not yet been released in cinemas
    2. The film has not yet been downloaded
2. When refreshing metadata (and it changes) ensure the directory name (and possibly file name) is updated (moving files as needed) for all movies at all times

1 seems more reasonable and safe, 2 would be extreme but could also be useful but very expensive in operations.

### Describe alternatives you've considered

No automated solutions, only manual editing as needed.

### Anything else?

The solution should probably be governed by a settings somewhere in `Media Management > Movie Naming` called something like `Rename Directories if Metadata Changes`.

**Comment by bakerboy448** [comment]
No plans for automated folder renaming
