### ISSUE TITLE
Force different Download even though original meets profile..

### ISSUE THREAD

**Issue by samedarkclouds** [Radarr/Radarr#8858]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I am an experiences user and saw someone ask about this before and get lambasted.  But the issue he was describing is real. 

I set my profiles and everything is great. 

Some movies download that absolutely DO meet those profiles, but it turns out that when you view it it does not REALLY meet the profile OR the quality of the cut is poor OR the movie isn't complete...

Now, if I click the "failed" x it usually just downloads the same broken copy. 

What I am looking for is a way to say I want the SAME profile as the download I already got BUT NOT THAT PARTICULAR ONE so I can get a different copy that meets the same profile criteria but isn't the zombie P.O.S. that downloaded first. There is no way to ask radarr to "try again and ignore that shit copy." 

### Describe the solution you'd like

I would like a button next to the x on the history of each movie that allows you to mark that file as needing to be replaced with a new search that OMITS the copy it already downloaded or is trying to download. This would allow users that successfully downloaded a copy that does meet the indexers and profiles criteria, but ended up being a dud for some other reason to get a different core rip than the one from before. This is important because the current behavior when you click the x to call it failed is to often just download that same copy again.

### Describe alternatives you've considered

Currently the only way to omit a particular copy that meets your profile seems to be to do it manually, which seems counter to the point of the program.

### Anything else?

Nope.

**Comment by bakerboy448** [comment]
- mark as failed in history / blocklist already exists and does exactly what you ask before; you can also do this directly from the queue as well
- blocklisting is on a per release; per indexer basis.
-  Use custom formats to block shit release groups
- Use better indexers that don't rename releases
- it's not possible for radarr to know the on disk details prior to the release being on disk

It's strongly recommended to visit our discord to hash out feature requests prior to opening them

**Comment by dRoskar** [comment]
Why was this closed exactly? This is a much needed feature.

**Comment by bakerboy448** [comment]
> Mark as failed in history does not do what this user asked. It just imports the same broken file again, just like they described.

Mark as failed would never trigger an import of the same file and the behavior you describe does not exist in the code.


Please use one of the support channels: [Discord](https://radarr.video/discord) for support/questions.

**Comment by dRoskar** [comment]
@bakerboy448 I have just been to discord. We tested out the behavior and all concluded that 'Mark as failed" does not trigger an alternative download.
If a movie is downloaded, and you go into the movie History, and mark the download as failed, nothing will happen. Please go ahead and try it yourself.
It most definitely will not download an alternative version of the movie (which should be the expected behavior imo).

**Comment by bakerboy448** [comment]
> 'Mark as failed' does not trigger an alternative download.

from history it does not; from activity queue it does.

from the movie detail it's a trivial two-three clicks: mark as failed, (optional, delete file), search movie 

> movie History, and mark the download as failed, nothing will happen.

completely false - the grab is marked as failed and blocklisted.

> It most definitely will not download an alternative version of the movie

that was not the feature requested and aligning history as failed and queue blocklisting functionality (or with an option) is a different feature request.  Again, the requested and described behavior in the OP is a mixture of already exists and not at all possible as previously mentioned

**Comment by dRoskar** [comment]
So, for other people looking for answers on how to force the download of an alternative file, you have to:
1. Go to the history tab, for that specific movie.
2. Click the x next to the unwanted download and then confirm with 'Mark as failed'
3. Click the 'Search Movie' button at the top of the page
