### ISSUE TITLE
Radarr not parsing movie correctly

### ISSUE THREAD

**Issue by ghallford** [Radarr/Radarr#886]
Radarr version: 0.2.0.375

Description: Radarr is not parsing movies correctly and is thinking they are TV series still (I am guess old Sonarr code). Here are the debug lines:

17-2-25 10:42:44.3|Debug|QualityParser|Trying to parse quality for Bill.and.Teds.Excellent.Adventure.1989.720p.BluRay.H264.AAC-RARBG
17-2-25 10:42:44.3|Debug|Parser|Quality parsed: Bluray-720p v1
17-2-25 10:42:44.3|Debug|Parser|Release Group parsed: RARBG
7-2-25 10:42:44.4|Debug|Parser|Parsing string 'Bill.and.Teds.Excellent.Adventure.1989.720p.BluRay.H264.AAC-RARBG'
17-2-25 10:42:44.4|Debug|Parser|Episode Parsed. Bill and Teds Excellent Adventure - Season 01 
17-2-25 10:42:44.4|Debug|DownloadedEpisodesImportService|Unknown Series Bill.and.Teds.Excellent.Adventure.1989.720p.BluRay.H264.AAC-RARBG

**Comment by galli-leo** [comment]
Where exactly did this happen? Can you post the full logs?

**Comment by ghallford** [comment]
Not sure what you mean by "where". This is from the debug logs in Radarr. I have attached the full debug log for you. Thanks.
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/801322/radarr.debug.txt)

**Comment by ghallford** [comment]
It appears this was an erroneous error. It wouldn't process the files because they were dropped by Deluge into the Drone Factory folder, so it was skipping processing them. Once I changed the drone factory folder, then it processed them properly.
