### ISSUE TITLE
Different path based on some parameter

### ISSUE THREAD

**Issue by atjpatatatj2** [Radarr/Radarr#8873]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Hey!

I have a system set up for me and my family. I prefer to watch many foreign movies like kungfu and bollywood action while my family rather enjoys the latest hollywood movies.
Therefor I have a system setup on plex where each user has a different view (see the movies they wanted and not the other ones)
Functionally it works by specific folders and each user only reads from their folder.

Now, Radarr only downloads to one folder and is not able to download to a specific folder and thus can't download indian movies to one folder and hollywood movies to another.

### Describe the solution you'd like

I'd like some parameter when adding a movie that is linked to a folder. 
Maybe a dropdown that lets you select where the movie should be downloaded rather than throwing it all together.

### Describe alternatives you've considered

I did write my own code for this with the Radarr API. But now I'm migrating to docker and this is a not doable anymore.

### Anything else?

/

**Comment by RobinDadswell** [comment]
Just add a second root folder and use the other root folder for it's path. Also API scripts should still work even though Radarr is in docker.
