### ISSUE TITLE
v4.7.2.7686 Radarr wont start

### ISSUE THREAD

**Issue by tellice** [Radarr/Radarr#8877]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Radarr will not run i get the following error:

Jul 24 10:04:08 DietPi systemd[1]: radarr.service: Start request repeated too quickly.
Jul 24 10:04:08 DietPi systemd[1]: radarr.service: Failed with result 'exit-code'.
Jul 24 10:04:08 DietPi systemd[1]: Failed to start Radarr (DietPi).

I am running Dietpi v8.19.1

I have been running the pre-release version for about 2 years with out no problem. But these latest version as stopped radarr from running at all

I have tried reinstalling with no luck

### Expected Behavior

Radarr to run

### Environment

```markdown
- OS: Dietpi 8.19.1
- Radarr: 4.7.2.7686
- Docker Install: No
- Using Reverse Proxy: No 
- Browser: Firefox 115 (UI access)
- Database: 3
```

### What branch are you running?

Nightly

### Trace Logs?

Not sure where this is

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by tellice** [comment]
Jul 24 11:09:57 DietPi systemd[620]: radarr.service: Failed to locate executable /opt/radarr/Radarr: No such file or directory
Jul 24 11:09:57 DietPi systemd[620]: radarr.service: Failed at step EXEC spawning /opt/radarr/Radarr: No such file or directory
Jul 24 11:09:57 DietPi systemd[1]: radarr.service: Main process exited, code=exited, status=203/EXEC
Jul 24 11:09:57 DietPi systemd[1]: radarr.service: Failed with result 'exit-code'.

**Comment by bakerboy448** [comment]
Reinstall.

systemd journal are not the required radarr trace logs nor any radarr app logs / updater logs that the bug report template and bot both requested

DietPi is not recommended at all because they make poor shortsighted changes that ultimately often result in updates failing because /tmp gets wiped or ends up being too small and thus both the update and the rollback fail
