### ISSUE TITLE
Bad language detected

### ISSUE THREAD

**Issue by krisz-gemini** [Radarr/Radarr#8878]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Radarr detected English language in Secrets.in.the.Woods.2020.1080p.AMZN.WEB-DL.DDP2.0.H.264.**Hun**-ARROW file.
[](url)

### Expected Behavior

Radarr must detect Hungarian language in Secrets.in.the.Woods.2020.1080p.AMZN.WEB-DL.DDP2.0.H.264.**Hun**-ARROW file.

### Steps To Reproduce

You can easily reproduce with the "Test parsing" function under Custom Format menu.

### Environment

```markdown
- OS: Win10 (irrelevant)
- Radarr: 4.7.2.7686
- Docker Install: No
- Using Reverse Proxy: Yes
- Browser: (irrelevant)
- Database: (irrelevant)
```

### What branch are you running?

Master

### Trace Logs?

![lng-bug](https://github.com/Radarr/Radarr/assets/46231613/5855616b-c070-403e-9ed9-69fffa4db831)

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
https://github.com/Radarr/Radarr/blob/bf0f681d466479f6c625a9bcc6862aafea94adc9/src/NzbDrone.Core/Parser/LanguageParser.cs#L27

`HUN` is already detected. This is simply a poorly named release as it's generally not expected that languages are suffixed nor prefixed by a `-`

**Comment by Qstick** [comment]
I'm confused, your screenshot shows it was parsed correct and Hungarian was detected
