### ISSUE TITLE
Kodi update fails if similar named movie exists in Kodi db

### ISSUE THREAD

**Issue by thezoggy** [Radarr/Radarr#8879]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

on tmdb there are multiple "The Little Mermaid" where they have different years
![image](https://github.com/Radarr/Radarr/assets/500882/1834e403-b4d6-4584-b7de-e15846618551)

Lets say you have the 1989 version in kodi. now added the 2023 one in radarr, it wrongly tries to update the 1989 one because it 'matched' that by the title as they all have the same title.

This is because radarr's GetMoviePath  looks through kodi response for all movies, and returns first match on either the imdb id or movie title.  

example data from kodi response,
```
            "file": "smb://server/Movies/Movies-SD/The.Little.Mermaid.1989.iNTERNAL.BDRip.XviD-EXViDiNT/exvid-mermaid1.avi",
            "imdbnumber": "tt0097757",
            "label": "The Little Mermaid",
            "movieid": 791
        }
```

because the lack of year is being used, it always ends up matching something in the db rather than returning null to actually know to get kodi to update the library to pick it up

### Expected Behavior

add year to movie title comparison to reduce false positives?

### Steps To Reproduce

1. add "The Little Mermaid" from 1989
2. add "The Little Mermaid" from another year (theres many) to radarr and have it grab release
3. See radarr wrongly use the existing movie to update

### Environment

```markdown
- OS: Unraid
- Radarr: 4.7.3.7701
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Firefox 115.02
- Database: sqlite
```

### What branch are you running?

Develop

### Trace Logs?

i can provide trace logs if you like, can get lengthy (one log for just the kodi json response) 
```
2023-07-24 08:40:36.2|Debug|XbmcService|Updating movie [The Little Mermaid (2023)][tt5971474, 447277] (Kodi path: smb://server/Movies/Movies-SD/The.Little.Mermaid.1989.iNTERNAL.BDRip.XviD...
```

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
Snippet per Zoggy per discord
> ok yeah i see what its doing, radarr's GetMoviePath  looks through kodi response for all movies..   then trying to match off movie title/imdb and returns on first match
`return s.ImdbNumber == movie.ImdbId || s.Label == movie.Title;`

**Comment by Qstick** [comment]
I suppose we should just compare IMDb? Likely more reliable

**Comment by thezoggy** [comment]
was looking at the GetMovies call, and there is a year parm you can pass and then you could leverage that info with the title (youd also have to use the title on the radarr side)

`/jsonrpc?request={"jsonrpc": "2.0", "id": 1, "method": "VideoLibrary.GetMovies", "params": {"properties": ["file","imdbnumber", "year"]} }`

```
      {
        "file": "smb://husky/Movies/Movies-SD/The.Little.Mermaid.1989.iNTERNAL.BDRip.XviD-EXViDiNT/exvid-mermaid1.avi",
        "imdbnumber": "tt0097757",
        "label": "The Little Mermaid",
        "movieid": 791,
        "year": 1989
      },
      {
        "file": "smb://husky/Movies/Movies-SD/The.Little.Mermaid.II.Return.To.The.Sea.2000.iNTERNAL.BDRip.XviD-EXViDiNT/exvid-mermaid2.avi",
        "imdbnumber": "tt0240684",
        "label": "The Little Mermaid II: Return to the Sea",
        "movieid": 792,
        "year": 2000
      },
      {
        "file": "smb://husky/Movies/Movies-Asian/The.Mermaid.2016.LIMITED.720p.BluRay.x264-USURY/Csazv69xxHBOzn3AOglQGwM1eweeEGAuTLuJu0YTA66Jx04qpsbi9ao.mkv",
        "imdbnumber": "tt4701660",
        "label": "The Mermaid",
        "movieid": 1726,
        "year": 2016
      },
      {
        "file": "smb://husky/Movies/Movies-HD/The.Little.Mermaid.2018.1080p.AMZN.WEB-DL.DD.5.1.H.264-NTG/yay.mkv",
        "imdbnumber": "tt5493944",
        "label": "The Little Mermaid",
        "movieid": 1873,
        "year": 2018
      },      
```
