### ISSUE TITLE
edit downloader - apikey not hidden

### ISSUE THREAD

**Issue by thezoggy** [Radarr/Radarr#8880]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

add sab as download client, configure it. go back to edit, apikey is shown. 

### Expected Behavior

apikey should not be exposed. its masked in sonarr as example

### Environment

```markdown
- OS: Unraid
- Radarr: 4.7.3.7701 
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Firefox 115.02
- Database: sqlite
```

### What branch are you running?

Develop

### Trace Logs?

none needed

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by Qstick** [comment]
This is known, there are other issues covering the Sonarr commits to pull this, also it's in v5 due to the API breakage
