### ISSUE TITLE
Unable to import more than a few dozen movies at a time

### ISSUE THREAD

**Issue by mikebutash** [Radarr/Radarr#8885]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

With a new installation, attempting to do a Library Import I am unable to add more than small amounts of movies at a time, or the application will fail, giving errors next to the "Start Processing" button,  and will never actually import after clicking the "Import ## Movies" button.

Enabling debug logging, the only thing logs show abnormally are dotnet errors for a connection to the api being reset.  The only reason for the application to reset the connection is if the server failed, or timed out for some reason.  I'm not sure why radarr would cause a tcp connection reset on itself, but something is causing the tcp connection seemingly to time out.

### Expected Behavior

After entering Library Import, I would expect the files to automatically start processing, run all the way through the list to finish processing (this could take a long time), and then it would be expected after to be able to click on "Import ## Movies" to queue these for actual import, but this will fail if the time between starting processing and clicking Import Movies is more than a few minutes.

If I quickly refresh the page to start processing, waiting only a minute or so for however many actually processed to click Import Movies, it works fairly consistently, but if I wait more than a few minutes, it will definitely fail.  It's as though there is a very short tcp timeout on the connection occurring if not an error condition in the application forcing the tcp connection reset.

### Steps To Reproduce

Working Steps:
1. Log into Radar
2. Navigate to Library Import, then click on the root folder.
3. Watch as files begin being automatically processed.
4. Within a minute, click "Cancel Processing", then immediately "Import ## Movies"
5. Watch the page refresh itself, and see files being actively imported in the lower left-hand corner.

Broken Steps:
1. Log into Radar
2. Navigate to Library Import, then click on the root folder.
3. Watch as files begin being automatically processed.
4. Wait 5 minutes for a larger number of files, click "Cancel Processing", then immediately "Import ## Movies"
5. The page will not refresh, but the activity on the "Import ## Movies" will stop spinning, show an error triangle next to "Start Processing", showing the same connection reset and various other non-specific logs.
6. Subsequent pressing of "Import ## Movies" will fail, only choice is to refresh the page, and do quicker, smaller amounts at a time within a minute or two.

Oddly this is consistent with Sonarr as well doing the same thing for TV Show imports.

### Environment

```markdown
- OS: Ubuntu 22.04
- Radarr: 4.6.4.7568
- Docker Install: No
- Using Reverse Proxy: No
- Browser: Firefox 114.0.2
- Database: Sqlite 3.37.2

There is 8gb in the server, watching htop shows only around 3gb in use, 2gb swap.
```

### What branch are you running?

Master

### Trace Logs?

[radarr.debug.txt](https://github.com/Radarr/Radarr/files/12173079/radarr.debug.txt)

This log trace is started immediately before refreshing the Library Import page, waiting 3 minutes or about 100 movies to process for Import, then clicking to import, waiting minutes after for any update, after about 3-4 minutes the spinning activity on the Import Movies button stops and does nothing more.  No OOM's or anything bad showing in journalctl.

Within ~30 seconds after pushing the Import, I'll see the connection reset.
'''
2023-07-26 13:00:19.8|Fatal|RadarrErrorPipeline|Request Failed. POST /api/v3/movie/import

[v4.6.4.7568] System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer.
 ---> System.Net.Sockets.SocketException (104): Connection reset by peer
   at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
'''

Logs actually show movies selected being imported, but these never get out of the Library Import screen or added to Movies library.  Eventually after the import process began, I'll see this at the start of another error blob:

'''
2023-07-26 13:26:39.6|Fatal|RadarrErrorPipeline|Request Failed. POST /api/v3/movie/import

[v4.6.4.7568] System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
'''

"Red Cliff" is one of the movies that I was attempting to add there, you can find that to see the lifespan of my attempting to add that and it processing unsuccessfully. 

### Trace Logs have been provided as applicable. Reports may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by mikebutash** [comment]
I don't believe this is a support issue, but seems rather a software defect since it works fine other than the import bugging out and crashing, never completing.

**Comment by mikebutash** [comment]
So going into this vm and doubling both cpu (to 8 cores) and memory (8 to 16gb) it did allow larger batches to run of movies, at least ~150 tested as the last lot to finish my import.  I guess my question would be to what end?

This tells me a few things after 20 years of troubleshooting enterprise applications.   The app is hitting some sort of virtual memory limit, and crashing as a result at worst, implying a performance limit at best to severely cripple itself.  If an application doesn't have enough memory, it shouldn't just fall over die ugly on the floor.  This seems to be some artificial constraint or simply a software bug, and I don't seem to be the only one since issue #8482 too.

If this were java, I'd say add more memory to the jvm, but at what point does one just keep throwing memory at it, or it behaves better/properly?  This shouldn't be a heavyweight proposition to run these, it just seems poorly behaved.

I'm not sure what to expect for performance from dot.net things under Linux, but this seems just bug or performance issues causing the software to break in ugly ways.

This is a beefy 20 core, 128gb ram proxmox vm host server with a simple ubuntu guest running this, 4 cores/8gb ram originally, now 8/16gb, flash os, nfs media, no network or otherwise service issues running on here, and none showing strain or full.

**Comment by nydave69** [comment]
Yes I have the same problem..  and You can't do more that a hundred at a time if your lucky..

**Comment by mikebutash** [comment]
I've seen enough other reports of similar happenings, I'm pretty sure this isn't a support issue more than a bug.  The fact that I'm seeing the application forcibly tcp connection reset a localhost 127.0.0.1 connection (look ma, no firewall) typically means an application is freaking out and doing something bad, or in response to something bad.  The fact it's happening with both radarr and sonarr tell me their shared codebase is somehow borked.

That the problem seems exacerbated by lack of ram (adding more definitely helped, but not fix), which tells me the thing is spiking usage somehow, probably blowing out memory (or some other finite resource), crashing the task, and resetting the connection handler for that.  I've dealt with buggy enterprise applications for 25 years as an engineer/architect in various IT capacities, I like to think I have a decent feel for these things, but developer I am not.

Asking around discord was about as useful as you'd imagine any chat support is (ie. not), and obviously attempting a bug report wasn't any more, so not sure what to do other than wait for the devs to have an epiphany their own code just might be buggy.
