### ISSUE TITLE
[Feature request] Job queuing or multi threading 

### ISSUE THREAD

**Issue by ajkis** [Radarr/Radarr#889]
Please consider implementing job que eg do not run Library Update while RSS Sync is in progress and vice versa.

**Comment by onedr0p** [comment]
This shouldn't cause an issue, maybe if your computer is from 1995.

**Comment by ajkis** [comment]
Well that happens on dual xeon E2560 with 32 cores/threads, while avarege CPU load is 2.

**Comment by onedr0p** [comment]
Right, I am saying that your server can handle the requests.

**Comment by onedr0p** [comment]
I am not seeing a need for this, everything runs fine! Even on ARM devices.
