### ISSUE TITLE
[Enchantment] Queue copy/moves from download folder 

### ISSUE THREAD

**Issue by ajkis** [Radarr/Radarr#890]
Please consider implementing que for copies so you do not copy multiple completed files at the same time but rather one by one. Copying multiple files at the same time completely overwhelms HDD I/O's so the result is actually much slower performance. This is especially noticeable for those using fuse overlays (uniofs ..)  or encryption like ENCFS:

**Comment by onedr0p** [comment]
I can only see this being a issue if the movies complete at the same time. As long as the movies copy over (no matter the speed) you're good.

**Comment by ajkis** [comment]
Well since Iam using nzbget and transmission at the same time, there are quite few cases when multiple files are downloaded at same time. So far I had record of radarr moving 7 files at same time.

The main problem is that I download the 8GB movie in 3 to 4 minutes while copying over unionfs takes longer.

**Comment by onedr0p** [comment]
Speed really isn't a issue, as long as the move complete's you're good to go.
