### ISSUE TITLE
Group movie collection/sequel to one folder 

### ISSUE THREAD

**Issue by natget21** [Radarr/Radarr#8902]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

if I have a movie with multiple parts like Iron Man or spider man each of them are added to a separate folder in the root folder I looked at the options to see if there was a way to group with a collection but I couldn't find one I searched online and found this issue but was marked closed

https://github.com/Radarr/Radarr/issues/3560

### Describe the solution you'd like

it would be better if there is a sequel to group them in a folder inside the root folder like

/root_movie/{collection name}/{movie folders}/{movie}
like 
/root_movie/spiderman/spiderman 1/ spiderman1.mkv
/root_movie/spiderman/spiderman 2/ spiderman2.mkv

### Describe alternatives you've considered

searched for the option to rename the movie when downloading the file

### Anything else?

no

**Comment by Qstick** [comment]
Movie folder naming: `{Movie Collection}\{Movie Title} {(Release Year)}`
