### ISSUE TITLE
 Changes to size restrictions on quality tab does not save.

### ISSUE THREAD

**Issue by vertigo235** [Radarr/Radarr#891]
**Description:**

I change the sliders and hit save, I get a message that general settings were saved but nothing about quality settings. Exit and return to quality page and the old values are still there. 

**Radarr Version:**
0.2.0.405

**Logs:**
I didnt see any relevant info in the debug logs, since this should be fairly easy to reproduce, let me know if it can not be reproduced and I'll turn on trace logging. 

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by onedr0p** [comment]
@galli-leo this is due to the page limit not containing a value, when you set a limit in the UI settings, you can save the Qaulity Size settings.

**Comment by vertigo235** [comment]
Thanks guys I had not yet played with the page limit settings so that makes sense.

**Comment by onedr0p** [comment]
Fixed in next release.
