### ISSUE TITLE
Add new movie + "start search for missing movie" - even when not released available

### ISSUE THREAD

**Issue by PeterKse** [Radarr/Radarr#8912]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When adding a movie using "add new" function, the option is to tick "start search for missing movie". Simultanious I can choose "Minimum Availability" as "Released" for example - to ensure I get a correct quality release.

Even when the movie I'm trying to add is in a not released state - the start search for missing movie forces Radarr to search for the movie.

### Expected Behavior

It shouldn't look for a movie when the "minimum availability" condition isn't met.

### Environment

```markdown
- OS:  Windows Server 2019
- Radarr:  4.6.4.7568
- Docker Install: 
- Using Reverse Proxy: 
- Browser:  
- Database:
```

### What branch are you running?

Master

### Trace Logs have been provided as applicable. Rep
[radarr.trace.txt](https://github.com/Radarr/Radarr/files/12227349/radarr.trace.txt)

added
orts may be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by PeterKse** [comment]
Added trace log

**Comment by Qstick** [comment]
Given you are manually telling it to search, this is actually by design. The minimum availability check is only enforced during RSS and not during a user triggered search.
