### ISSUE TITLE
Following directors

### ISSUE THREAD

**Issue by jamesla** [Radarr/Radarr#8924]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

It's annoying to add movies one by one, it would be better if there was an option to make radarr work more like sonarr where it's automatic

### Describe the solution you'd like

Like in Sonarr how you can add a series, in Radarr you should be able to add a director/actor and from there it works similar to how sonarr works where it automatically grabs antyhing made by them/with them in it.

For example if I added quinten tarantino it would grab all of his movies and if a new one came out it would grab them too.

If i added Leonardo decaprio it would search for anything he is in and grab anything that he makes after adding him.

### Describe alternatives you've considered

nothing

### Anything else?

nothing

**Comment by bakerboy448** [comment]
- this is already accomplished via lists
