### ISSUE TITLE
Release Dates not pulling through for the following titles

### ISSUE THREAD

**Issue by MrCee** [Radarr/Radarr#8944]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Using docker having tried master and nightly, I see that release dates are not populated for the following links. This may help identify some gaps with real world examples where the release date is published in various databases...

https://www.imdb.com/title/tt6213952/
https://www.imdb.com/title/tt10397932/
https://www.imdb.com/title/tt0120240/

or alternatively:

https://www.themoviedb.org/movie/460100-anything
https://www.themoviedb.org/movie/612074-learning-to-skateboard-in-a-warzone-if-you-re-a-girl
https://www.themoviedb.org/movie/209802-subwaystories-tales-from-the-underground

### Expected Behavior

in the table moviemetadata there are 3 fields that could potentially be populated... InCinemas, DigitalRelease, PhysicalRelease and for some reason these movies are not pulling in any release date.
VERSION 4.7.4.7758

### Steps To Reproduce

SELECT l.Title, l.InCinemas, l.DigitalRelease, l.PhysicalRelease
FROM MovieMetadata l
INNER JOIN Movies r 
ON  r.moviemetadataid = l.Id
WHERE (InCinemas IS NULL) AND (DigitalRelease IS NULL) AND (PhysicalRelease IS NULL);

### Environment

```markdown
- OS: MacOS, Linux 
- Radarr: 4.7.4.7758
- Docker Install: linuxserver/radarr:nightly
- Using Reverse Proxy: No 
- Browser: Brave / Safari
- Database: radarr.db
```

### What branch are you running?

Nightly

### Trace Logs? **Not Optional**

No need for trace logs here

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by RobinDadswell** [comment]
Following on from Bodgan, if you are aware of Theatrical, Digital or Physical release dates then update TMDB and Radarr will update with the data as it filters through the TMDB changes API. 

We do not plan on using Premiere as a the release date within Radarr as it is not technically a proper release and the behaviour of only having a Premiere date is typically films released during film festivals.

**Comment by MrCee** [comment]
@RobinDadswell  I don't see that 'Premiere'  is an option in the SQLite3 tables. But if it's nothing that we should go by, what release date could we fall back to `WHERE (InCinemas IS NULL) AND (DigitalRelease IS NULL) AND (PhysicalRelease IS NULL)` ?

**Comment by RobinDadswell** [comment]
> @RobinDadswell I don't see that 'Premiere' is an option in the SQLite3 tables. But if it's nothing that we should go by, what release date could we fall back to `WHERE (InCinemas IS NULL) AND (DigitalRelease IS NULL) AND (PhysicalRelease IS NULL)` ?

Premiere isn't, as far as Radarr is concerned it's not been released if it's only premiered and so is behaving as expected. As I previously mentioned TMDB should be updated to reflect it's actual release date.
