### ISSUE TITLE
Updating info changes the custom file path

### ISSUE THREAD

**Issue by DaveAlton** [Radarr/Radarr#8955]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

1. Radarr automatically updates the info of all movies
2. Radarr changes the file path of the existing movies
3. Radarr finds that there is no movie file in the new file path
4. Radarr begins search for movie and begins downloading
5. Radarr continues to do this for every movie, triggering hundreds of downloads, crashing the system
6. User now has to manually change the individual file paths of hundreds of movies back to the original paths, then trigger a movie scan for Radarr to recognize its no longer missing. 

### Expected Behavior

When updating a movie that currently exists in Radarr, keep the file path that has already been set if the movie already has a file. If an unreleased movie changes its title, fine. Change the file path. But if I have “Scream 6” files, Radarr shouldn’t change the folder to “Scream IV” and then re-trigger a download just because it can’t find the file at the location I never gave it. 

### Environment

```markdown
- OS: Synology DS 7
- Radarr: 4.6.4.7568
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: NA
- Database: Sqlite 3.41.2
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

[radarr.txt](https://github.com/Radarr/Radarr/files/12305018/radarr.txt)

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by DaveAlton** [comment]
I've restored from yesterday's backup to try and mass-fix the file paths, and now it's "Updating info" on all my movies again. I've turned on trace logs and disabled my download client's connection. I hope to have better trace logs soon.

**Comment by bakerboy448** [comment]
> Radarr doesn't change the movie folder path unless you move it to the same root.

*Radarr doesn't change the movie folder path unless you change root folders in radarr and tell it to move movies

**Comment by DaveAlton** [comment]
The only API access I've granted is to Prowlarr. I have no scripts running in my movie folder.

Could there be a moment when Radarr fails to read from the root folder and assumes it's empty or something? I'm running this on the same Synology that holds the files, but I'm wondering if for a moment it somehow disconnects?
