### ISSUE TITLE
Import list changes

### ISSUE THREAD

**Issue by pablorodriguezzurro** [Radarr/Radarr#9004]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

No.

### Describe the solution you'd like

It would be great to have import list changes detection and apply the new list properties to the movies moved to the other list. 

For example, if I have 2 movies that changed from watchlist to watched movies list, I would like to apply the root folder of the watched list and change the monitor status. 

### Describe alternatives you've considered

I move manually the movies to the destination folder, then delete and re-import them after changing the movies list in Trakt.

### Anything else?

No.

**Comment by bakerboy448** [comment]
> I move manually the movies to the destination folder, then delete and re-import them after changing the movies list in Trakt.

Why are you unable to use radarr's native change root folder functionality to have radarr move the movies itself?  There's no reason that deleting he movies from radarr and doing things externally from radarr is required.

What if a movie is on multiple lists? Which root folder or which quality profile wins?

**Comment by pablorodriguezzurro** [comment]
Hi bakerboy448,

In that case, it would be great to sync tags from the lists the movies are on.

So I can bulk edit the destination folder or make operations with multiple movies.

Thank you for your time.

Best regards,

Pablo

**Comment by RobinDadswell** [comment]
Lists are not for updating existing items within Radarr but about adding movies. 

We have discussed that in the past and have no plans on changing that
