### ISSUE TITLE
Import list sync runs every 5 minutes in 4.7.5.7809

### ISSUE THREAD

**Issue by 1nu** [Radarr/Radarr#9011]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

In version 4.7.5.7809 the task Import Lists Sync runs every 5 minutes. I noticed the UI in lists changed as well, it doesn’t offer an advanced option to set the interval yourself anymore. When I navigate to lists I see the list should be updated every 12 hours.

### Expected Behavior

The job should run every 12 hours, as advertised.

### Environment

```markdown
- OS: Synology DSM
- Radarr: Radarr 4.7.5.7809
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: 
- Database: Sqlite 3.40.0
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

https://gist.github.com/1nu/a7b2fd0a6a0dadcb862e928d0e968bc1#file-gistfile1-txt

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by 1nu** [comment]
That job does a full scan of the library, which results in my NAS doing incredible noise every 5 minutes. It's not something I can live with, so I'll stick to 4.6.4.

**Comment by 1nu** [comment]
Trace: https://gist.github.com/1nu/13f3f3025cce58b10b50a076f4f2ad8b
ImportListSync started at 22:44:34 and my HDDs started doing insane amounts of I/O for the whole duration of the task, 01:44. From the trace to me it looks like MovieService is responsible for this.

**Comment by 1nu** [comment]
Not on NFS. It's the default filesystem of the NAS.

**Comment by bakerboy448** [comment]
https://github.com/Radarr/Radarr/blob/a946546793e140e15a68dacdc40526ce9a27958f/src/NzbDrone.Core/Movies/MovieService.cs#L250-L267

Seems like your movies dont have any root folder assigned somehow if I'm reading the code right?

**Comment by Qstick** [comment]
> https://github.com/Radarr/Radarr/blob/a946546793e140e15a68dacdc40526ce9a27958f/src/NzbDrone.Core/Movies/MovieService.cs#L250-L267
> 
> Seems like your movies dont have any root folder assigned somehow if I'm reading the code right? But also seems like Lists is somehow triggering a movie update?

Off topic, an existing movie has m.Path set and not m.RootFolderPath, these are existing, thus why it's not changing paths
