### ISSUE TITLE
List simkl

### ISSUE THREAD

**Issue by foXaCe** [Radarr/Radarr#902]
Hello, it possible to support watchtlist of this site ?

https://simkl.com

**Comment by onedr0p** [comment]
Maybe, can you give us more information, like do they have an API and some examples?

**Comment by joelm3103** [comment]
According to the site, they have an API. Just made an account to reply here. Hope this is of some use.
https://api.simkl.com/

**Comment by onedr0p** [comment]
Please add this request to Feathub

**Comment by joelm3103** [comment]
Added to Feathub.
http://feathub.com/Radarr/Radarr/+109
