### ISSUE TITLE
Return to movie editor screen after deleting a movie from the movie editor screen

### ISSUE THREAD

**Issue by PearsonFlyer** [Radarr/Radarr#9028]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

When you're in the movie editor, selecting movie(s), and then deleting them, Radarr returns you to the standard Movies screen.

### Describe the solution you'd like

Ideally, Radarr would remember that you were in the Movie Editor screen, and return you to that screen. I know it's only an extra click, but when you're trying to do a bunch of movie management, it's just a small pain point.

### Describe alternatives you've considered

Clicking that one extra time.

### Anything else?

Nothing else.

**Comment by Qstick** [comment]
This seems to work now
