### ISSUE TITLE
Can't import existing Movies from a Network drive

### ISSUE THREAD

**Issue by jordy1955** [Radarr/Radarr#904]
Hi, New to Radarr, but long time Sonarr user. I cannot get Radarr to import existing Movies from my Network Library. It will allow me to add a network address eg \\servername\foldername\ but it does not import the movies on that drive. Movies follow the correct folder naming conventions eg \\servername\Movies\MovieName (year)\MovieName (year).ext etc.
I'm noticing that the wiki does not show network paths in the examples for importing existing movies. Does t his mean that Network libraries are not supported?. Sonarr does this extremely well (from the same pc) and I thought Radarr would do so as well. Perhaps I am wrong?

**Comment by galli-leo** [comment]
@jordy1955 Are you running Radarr as a service? Did you see anything in the logs? What exactly happens when you try to import movies from a network drive?

**Comment by SuperGaco** [comment]
I'm also struggling with adding my network drive.  I have google cloud mounted, and while i can point to it and browse folder, it just hangs forever on the movie folder, and if I try to add it, It wont work "Request Failed: The given path's format is not supported." I have Radarr installed as service with proper privileges, (sonarr works just fine), I have tried putting the shortcut in the startup folder, (which doesnt work, cause it wont boot up when the computer boots up) and that also fails. I would be happy to hop on discord or w/e to try to get this fixed, at this point I think i tried everything, but I really like the idea of Radarr, which is why I'm still hanging in there.

**Comment by jordy1955** [comment]
Hi @galli-leo, yes, I am running Radarr as a service - whatever the default installation setup is. When I try to import my existing movie libraries (I have 3), using the "Import Existing Movies on Disk" dialogue, it allows me to add the network path but all I get then is a msg "Loading search results from TheTVDB for your movies, this may take a few minutes." but I am yet to see any results. The curious bit is the reference to T**V**DB, shouldn't it be T**M**DB?

Todays logs attached.
[logs.zip](https://github.com/Radarr/Radarr/files/802031/logs.zip)

**Comment by jordy1955** [comment]
A couple of other things I should add.
The pc on which Radarr is running is permanently connected to the Internet via VPN, however Sonarr has no problem with this.
All the entries in the log are for items from an RSS list I imported as a indexer/source, except for the movie in the H:\downloads

**Comment by galli-leo** [comment]
First I would advise you to use Bulk import instead of import existing movies. Second, services have a very low chance of working correctly with networked drives, so I would advise you to make a shortcut to Radarr.exe and launch that when your computer starts up.

**Comment by SuperGaco** [comment]
@galli-leo Using the shortcut in the startup folder wont boot up radarr, it just wont work.

**Comment by jordy1955** [comment]
Ok ta. will give that a go.

**Comment by SuperGaco** [comment]
![image](https://cloud.githubusercontent.com/assets/25994857/23340959/4bdae8fe-fc0d-11e6-977c-63df8fac2449.png)

**Comment by ctroncoso** [comment]
Check if you have Analize Video File enabled. 
If you do, while adding, it will have to download all (partial) your files in order to analyze them.
![image](https://cloud.githubusercontent.com/assets/121016/23340996/ad7eabca-fc1e-11e6-97bf-fcef8ecb54d9.png)
Try disabling it.

**Comment by SuperGaco** [comment]
@ctroncoso disabled that it did nothing :(

**Comment by SuperGaco** [comment]
It just hangs on this forever 
![image](https://cloud.githubusercontent.com/assets/25994857/23341018/57bb1742-fc0e-11e6-91c2-8050e855363e.png)

**Comment by ctroncoso** [comment]
thy this. 
Can you make a folder with just one small movie file and try to import that one?
I'm almost sure it's not hanging, but just trying to read the whole file.
If it take forever, then there is an issue with how windows handles samba or whatever protocol it uses for remote access.
I got my files on a network folder as well, but I run linux and had no issues. 

The idea is that if it does take some time on the small file, but does end, then there must be some process that can be excluded on a network location. That is: "if the folder is a network folder, don't parse the file and just do all the matching and analytics based on the file name."

**Comment by SuperGaco** [comment]
Trying so far just 
![image](https://cloud.githubusercontent.com/assets/25994857/23341139/024b49ec-fc10-11e6-8b63-1bba65b81113.png)

**Comment by SuperGaco** [comment]
It worked!
![image](https://cloud.githubusercontent.com/assets/25994857/23341161/47e5fdbc-fc10-11e6-8289-a2d4be2e72ff.png)

**Comment by SuperGaco** [comment]
So I just have to leave it over night or something?

**Comment by ctroncoso** [comment]
Nope... that's an issue. If it is doing what I think it's doing (I have no part in this project), it's not detecting that it is a network drive and it might be parsing the whole file. So, it will (might) download all your library just to identify it. 
I'm not even sure if it can detect that it's a network drive. 
Paste your logfile here so that a coder can have a look at it, but my bet is that it's parsing the content of the file instead on relying on the filename.

**Comment by SuperGaco** [comment]
Thats alot of data to download about 4 terrabytes.

**Comment by ctroncoso** [comment]
Neat.. please remember to close this issue.

**Comment by jordy1955** [comment]
OK, it's working now.

A couple of suggestions:

- Allow bulk editing of movies to change things like Profiles, Monitored status etc

- In the settings pages there are still a lot of references to TV Shows, they should be removed or modified to reflect Movies only

**Comment by jordy1955** [comment]
OIne more thing. The calendar does not reflect my choice of date format. Choosing Tues 05/03 and 03 March etc does not change it from the US style -Tues 03/05 .

**Comment by jordy1955** [comment]
I've struck a problem importing a movie where Radarr is getting an incorrect match. Using The Bulk Import Movies Dialogue.
The Runner (2015) is being matched to The Maze Runner (2014). I have edited the TMBD id field and it has updated the movie name correctly but it will not allow me to check it and add it to the library, The check box is disabled.
Tks

**Comment by jordy1955** [comment]
@galli-leo , Hi, Radarr imports movies to <LocalDrive>:\Radarr\Select Path\MovieName (year).

1. I cannot see where to rename the "Select Path" part of this address
2. I need to have Radarr import the Movie to a Network Drive where my existing Movie Library exists. Just like Sonarr does with TV shows.
3. How can I do this?

Thanks for your help  Jordy

**Comment by jordy1955** [comment]
OK, I think i've got most of this stuff sorted now. Still can't directly see Network drives, have to type them in manually but then Radarr remembers them. And sometimes Radarr will not look for new movies either using the Bulk import or existing Import dialogues - click on the required drive and nothing happens, have to refresh (F5) the page to get any response.
