### ISSUE TITLE
Plot foreign

### ISSUE THREAD

**Issue by foXaCe** [Radarr/Radarr#906]
Hello
The plot and titile on add new movies is in english. is chnage in my foreign language after click on add buttons.

**Comment by galli-leo** [comment]
If you add the movie with a different language set in the profile, plot and title will change accordingly.

**Comment by foXaCe** [comment]
yes but the name of destination directory is not good
example: /Video/The Girl on the Train (2016) .
in french the name is "La fille du train (2016)"
