### ISSUE TITLE
Ability to rest Quality Definitions

### ISSUE THREAD

**Issue by ryancurrah** [Radarr/Radarr#9077]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I would like to reset my quality definitions to the default. Sonarr has the ability and it was merged into this repository I think via https://github.com/Radarr/Radarr/issues/7363. So I'm not sure what it would take to turn the feature on.

### Describe the solution you'd like

Turn on the ability to reset quality definitions.

### Describe alternatives you've considered

Manually determining the defaults and resetting manually.

### Anything else?

Nope.

**Comment by bakerboy448** [comment]
![image](https://github.com/Radarr/Radarr/assets/55419169/84276aa1-afbb-491d-b2bd-b5b158b9ffca)
