### ISSUE TITLE
Clickable Movies removed from TMDb list

### ISSUE THREAD

**Issue by Jhonny0007** [Radarr/Radarr#9086]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

sometimes Movies get removed from TMDb in larger quantities. Its a tedious process to remove (and potentially readd) the Movie. Currently if movies were removed from TMDb the Status displays a single list of movies that are missing. Sometimes the search function does not work at all (eg:  "In (tmdbid 997915)").

### Describe the solution you'd like

Please make the Names of the Movies that are missing from TMDb clickable, resolving to the radarr internal url.

### Describe alternatives you've considered

If the Code allows it, can you make radarr create one issue for each missing instance, instead of one status for all missing movies? 

### Anything else?

If the one issue per missing movie is doable, can you create a delete button in the right action-column?

**Comment by bakerboy448** [comment]
> Its a tedious process to remove 

It's not.
Simply filter for a movie status of deleted on the Movie Index 

![image](https://github.com/Radarr/Radarr/assets/55419169/8d83ae51-8f32-4b78-afb8-92ba392b0828)

> Please make the Names of the Movies that are missing from TMDb clickable

deleting movies 1x1 is the exact tedious process one is trying to avoid.   The fact they're deleted from TMDb is already filterable and this adds little as far as user experience goes
