### ISSUE TITLE
Quality Definitions Title

### ISSUE THREAD

**Issue by hotio** [Radarr/Radarr#909]
Renaming the title of a quality in Quality Definitions does not stick, after refreshing the UI they go back to the defaults.

Radarr Ver. 0.2.0.413

**Comment by onedr0p** [comment]
Any errors in the chrome console?

**Comment by onedr0p** [comment]
Also try setting a page limit value in the UI settings.

**Comment by onedr0p** [comment]
See #891

**Comment by hotio** [comment]
Yep that fixed it, sorry
