### ISSUE TITLE
Radarr doesn't import torrent that had been deleted previously

### ISSUE THREAD

**Issue by samuelbarata** [Radarr/Radarr#9090]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Radarr isn't importing a movie that finished downloading
I checked the Blocklist and it isn't listed there

I was removing and adding the movie because I was trying to reproduce another bug

### Expected Behavior

Radarr would import the movie

### Steps To Reproduce

1. Add a movie
2. Download movie normally
3. remove movie and all files from radarr
4. make sure the torrent isn't on the client
5. add the same movie and download the same torrent
6. Radarr won't import it even tho is has finished

### Environment

```markdown
- OS: Arch Linux
- Radarr: Radarr 4.6.4.7568
- Docker Install: No
- Using Reverse Proxy: Yes [10.2.128.79]
- Browser: 
- Database: Sqlite 3.42.0
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

find `Res: [GET] http://plexie.barata.pt:8080/api/v2/torrents/info?category=radarr`

```
{"added_on":1693162277,"amount_left":0,"auto_tmm":false,"availability":-1,"category":"radarr","completed":525463921,"completion_on":1693162389,"content_path":"/home/(removed)/media/downloads/The Lion King (1994)","dl_limit":0,"dlspeed":0,"download_path":"/home/(removed)/media/downloads","downloaded":528421043,"downloaded_session":0,"eta":8640000,"f_l_piece_prio":false,"force_start":false,"hash":"1957368624b6ee89737f9876f9dc3a8cd794705a","infohash_v1":"1957368624b6ee89737f9876f9dc3a8cd794705a","infohash_v2":"","last_activity":1693162389,"magnet_uri":"magnet:?xt=urn:btih:1957368624b6ee89737f9876f9dc3a8cd794705a&dn=The%20Lion%20King%20(1994)&tr=http%3a%2f%2finferno.demonoid.me%3a3404%2fannounce&tr=udp%3a%2f%2ftracker.1337x.org%3a80%2fannounce&tr=http%3a%2f%2fexodus.desync.com%2fannounce&tr=http%3a%2f%2f10.rarbg.com%2fannounce&tr=http%3a%2f%2ft1.pow7.com%2fannounce&tr=http%3a%2f%2f9.rarbg.com%3a2710%2fannounce&tr=http%3a%2f%2feztv.tracker.prq.to%2fannounce&tr=http%3a%2f%2fopentracker.umunu.com%2fannounce&tr=http%3a%2f%2ftracker.publicbt.com%3a80%2fannounce&tr=http%3a%2f%2fpow7.com%2fannounce&tr=http%3a%2f%2ftracker.istole.it%2fannounce&tr=http%3a%2f%2ftracker.torrent.to%3a2710%2fannounce&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=http%3a%2f%2ftracker.openbittorrent.com%3a80%2fannounce&tr=udp%3a%2f%2fopentracker.i2p.rocks%3a6969%2fannounce&tr=udp%3a%2f%2ftracker.internetwarriors.net%3a1337%2fannounce&tr=udp%3a%2f%2ftracker.leechers-paradise.org%3a6969%2fannounce&tr=udp%3a%2f%2fcoppersurfer.tk%3a6969%2fannounce&tr=udp%3a%2f%2ftracker.zer0day.to%3a1337%2fannounce","max_ratio":0.1,"max_seeding_time":1,"name":"The Lion King (1994) 720p BluRay x264 - 500MB - YIFY","num_complete":142,"num_incomplete":33,"num_leechs":0,"num_seeds":0,"priority":0,"progress":1,"ratio":0,"ratio_limit":-2,"save_path":"/home/(removed)/media/downloads","seeding_time":63,"seeding_time_limit":-2,"seen_complete":1693162389,"seq_dl":false,"size":525463921,"state":"pausedUP","super_seeding":false,"tags":"","time_active":175,"total_size":525463921,"tracker":"http://pow7.com/announce","trackers_count":19,"up_limit":0,"uploaded":0,"uploaded_session":0,"upspeed":0},
```

[radarr.trace.txt](https://github.com/Radarr/Radarr/files/12448624/radarr.trace.txt)

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
Missing the log line that would be 

```
2023-08-27 19:55:49.6|Debug|TrackedDownloadService|Tracking 'qb:Wreck.It.Ralph.2012.4K.HDR.DV.2160p.BDRemux Ita Eng x265-NAHOM': ClientState=Downloading (readonly) RadarrStage=Downloading Movie='Wreck It Ralph - 2012 Remux-2160p v1' OutputPath=/home/(removed)/media/downloads/Wreck.It.Ralph.2012.4K.HDR.DV.2160p.BDRemux Ita Eng x265-NAHOM.
```

but for lion king.

Does it show in activity queue with show unknown?  There's no attempts for radarr to even be parsing it.


More than likely a support issue;  did you run housekeeping after deleting the movie from radarr?

**Comment by samuelbarata** [comment]
I deleted the movie from Radarr again, ran the housekeeping task, and added the movie again
now I can see those lines
`2023-08-27 20:28:50.5|Debug|TrackedDownloadService|Tracking 'qb:The Lion King (1994)': ClientState=Downloading (readonly) RadarrStage=Imported Movie='The Lion King - 1994 Unknown v1' OutputPath=/home/(removed)/media/downloads/The Lion King (1994).`
It shows as imported even while the download is running
`2023-08-27 20:31:50.6|Debug|TrackedDownloadService|Tracking 'qb:The Lion King (1994)': ClientState=Completed RadarrStage=Imported Movie='The Lion King - 1994 Unknown v1' OutputPath=/home/(removed)/media/downloads/The Lion King (1994).`

Yes in the queue I have an Unknown
[I don't believe I had Radarr on trace when I ran the housekeeping task, I can rerun the test if you need me to]
[radarr.trace.0.txt](https://github.com/Radarr/Radarr/files/12448687/radarr.trace.0.txt)

**Comment by samuelbarata** [comment]
Wait, the unknown torrent wasn't lion king, it was something else
The Lion King doesn't show on the activity at all

**Comment by robertmx** [comment]
I see this behavior as well on 5.1.3.8246. Some previously deleted movies don't show up in the activity queue and are not picked up on completion (with qbittorrent).

**Comment by robertmx** [comment]
It seems to be identical to the problem described here:
https://www.reddit.com/r/radarr/comments/vp7vwy/how_to_redownload_a_movie_and_have_it_import_for/

**Comment by robertmx** [comment]
Restarting fixes it. But the root cause would still be interesting. Some cache artifacts maybe?

**Comment by agorgl** [comment]
Bumped into this exact problem too.
Steps to reproduce:
1. Add a movie
2. Download the movie
3. Wait for the movie to be downloaded and imported
4. Delete the movie file from radarr
5. Re-download a different version
6. The movie is added to the download client and download starts, but not shown in radarr activity
7. The movie is downloaded, removed from the download client but not imported in radarr
Using the latest container images for everything
