### ISSUE TITLE
Radarr sometimes moves files instead of using hard links

### ISSUE THREAD

**Issue by samuelbarata** [Radarr/Radarr#9092]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Radarr is moving the movie file instead of using hardlinks
`2023-08-27 21:58:54.2|Trace|DiskProvider|Moved '/home/(removed)/media/downloads/Puss in Boots (2011) (2160p BluRay x265 HEVC 10bit HDR AAC 7.1 Tigole)/Puss in Boots (2011) (2160p BluRay x265 10bit HDR Tigole).mkv' -> '/movies/Puss in Boots (2011)/Puss in Boots - 2011.mkv' using Syscall.rename`

This only happens sometimes, and all my files are in the same path, I can't understand the pattern

### Expected Behavior

Radarr would use a hardline and leave the original files intact

### Steps To Reproduce

Media Management:
- Rename Movies [X]
- Replace Ilegal Characters [X]
- Create empty movie folders [X]
- Delete empty movie folders [ ]
- Skip free space check [X]
- **Use hardlinks instead of copy** [X]
- Import using script [ ]
- import extra files:`.sub, .nfo, .srt`
- Unmonitored deleted movies [X]
- Analyse video files [X]
- Rescan movies after refresh: `Always`
- No recycle bin path configured
- Set Permissions [ ]

1. Add a movie to the download client
2. Radarr imports movie
3. Most of the times it moves the files instead of using hardlinks

### Environment

```markdown
- OS: Arch Linux
- Radarr: Radarr 4.6.4.7568
- Docker Install: No
- Using Reverse Proxy: Yes [10.2.128.79]
- Browser: 
- Database: Sqlite 3.42.0
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

[radarr.trace.txt](https://github.com/Radarr/Radarr/files/12448898/radarr.trace.txt)

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
> Hardlinks allow Radarr to import seeding torrents to the movie folder without taking extra disk space or copying the entire contents of the file. **Hardlinks will only work if the source and destination are on the same volume**

- from the UI

> usenet: Radarr will scan that completed file location for files that Radarr can use. It will parse the file name to match it against the requested media. If it can do that, it will rename the file according to your specifications, and move it to the specified media location.
> torrents: Completed files are left in their original location to allow you to seed the file (ratio or time can be adjusted in the download client or from within Radarr under the specific download client). When files are imported to your media folder Radarr will hardlink the file if supported by your setup or copy if not hardlinks are not supported.

- https://wiki.servarr.com/radarr/quick-start-guide#download-clients

**Comment by samuelbarata** [comment]
I've checked on discord and I do believe this is a bug
Both the download and media folder are on the same volume
I can manually create hardlinks between those folders
Radarr can sometimes create them, but sometimes doesn't
Is there anything in the logs that could show the error when trying to create the link that forces it to copy the file?

**Comment by quentin-bettoum** [comment]
I have the same issue. I've recently used rmlint to find replace all duplicates by hardlinks to save some space.
I'm also using Lidarr, but only Radarr can't create hardlinks.

**Comment by bakerboy448** [comment]
Please use [Discord](https://radarr.video/discord) for support/questions.

GitHub is not for support. This is not a bug and is just about always an issue with the user's setup or environment
