### ISSUE TITLE
Add option to disable authentication requirement when different authentication is present

### ISSUE THREAD

**Issue by msfreaks** [Radarr/Radarr#9104]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I am using alternate authentication when I use Radarr remotely.
As of the latest version I now need to authenticate again, since I am connecting remotely and there's no option to disable authentication for remote connections.

### Describe the solution you'd like

At the moment it's not possible to disable authentication for remote access.
I have been using Azure AD Authentication using Azure Application Proxy services to authenticate using my Azure AD user, password, Conditional Access, Multi-Factor etc.
This worked fine before, but now I cannot disable authentication for remote access anymore.

Perhaps show a disclaimer when someone wants to disable authentication for remote access?

### Describe alternatives you've considered

None. All my remote enabled applications are accessed using AAD Authentication, I would very much like to use that for Radarr as well.

### Anything else?

None

**Comment by bakerboy448** [comment]
This exists. https://wiki.servarr.com/radarr/faq#forced-authentication

**Comment by msfreaks** [comment]
No it does not.
I explicitly want the option to turn off the forced authentication when accessing Radarr remotely. What you link to is how you can disable it for local access.
I have a far better authentication option which I want to use instead of Radarr's authentication, when accessing remotely. I personally couldn't care less about local access, but that's just me.

**Comment by Qstick** [comment]
Yes it does, take another read there or come to discord and we can explain it.

**Comment by msfreaks** [comment]
Ah apologies, Qstick and bakerboy448... I just read the part involving manually editing the config.xml.
Thanks for correcting, and thanks for the discord link, where I found https://discord.com/channels/264387956343570434/264388019585286144/1145931665798078465

Thanks!
