### ISSUE TITLE
Radarr Authentication Not Working with Reverse Proxy for Safari

### ISSUE THREAD

**Issue by OKok-3** [Radarr/Radarr#9106]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When authentication (either basic or form) is enabled in Radarr, any browser that is safari based won't be able to launch the website using the reverse proxy URL (specifically HAProxy)

### Expected Behavior

Radarr launches to the login screen and prompts user for username and password

### Steps To Reproduce

1. Check if authentication is enabled, if not enable it in radarr
2. Clear all cache and history in safari (or any safari based browsers, like Chrome/Firefox on iOS)
3. Quit and reopen the said browser
4. Visit the radarr via the reverse proxy URL

### Environment

```markdown
- OS: Ubuntu 22.04.3
- Radarr: 4.7.5.7809
- Docker Install: Yes 
- Using Reverse Proxy: Yes (HAProxy on pfSense 2.7.8-58c657f)
- Browser: Safari 16.6 on macOS 13.5.1 (22G90), iOS 16.6, iPad OS 16.6
- Database: Sqlite 3.41.2
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

[radarr.trace.txt](https://github.com/Radarr/Radarr/files/12485225/radarr.trace.txt)

It appears that radarr trace is reporting "Failed to bind to address http://[::]:7878: address already in use. This can happen if another instance of Radarr is already running another application is using the same port (default: 7878) or the user has insufficient permissions". However, I've double checked all my containers and network devices and non has the same IP or is using the same port as radarr. 

Edit: it works fine on Firefox/Chrome on macOS and Windows with or without authentication turned on in radarr

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
Reverse proxy conf?

**Comment by bakerboy448** [comment]
closing pending info from OP and lack of reports by other users
