### ISSUE TITLE
Bitrate custom format

### ISSUE THREAD

**Issue by Mythic000** [Radarr/Radarr#9108]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

The quality slider is only good for excluding releases and preferring the first download bitrate. Sometimes, the first release is a bad release with a low bitrate, and a better release will follow. However, if the only difference is a higher bitrate, no custom format can be applied to score this higher. File size can be used as a very crude rule set, but the length between short and long movies makes this very ineffective.

### Describe the solution you'd like

The simplest way would be to create a bitrate custom format, since the quality slider already uses bitrate. This should be possible.

### Describe alternatives you've considered

Otherwise, you could create a checkbox in the quality menu to continue upgrading until the preferred bitrate is received, but that would make it more convoluted. I think. It’s better to keep quality as rules for what you will and will not accept from the beginning and use custom format rules for what you want to achieve in the end.

### Anything else?

Any argument that bitrate is not an indicator of quality is strange because this is one of the few indicators we have to work with. Yes, resolution, codec, encoder, sources, and compression are not accounted for by looking at bitrate, but to some extent bitrate will always correlate to quality, hence the quality menu. Anyway, this custom format would have to be combined with others to weigh releases.

Too low bit-rate will be noticeable and too high will take up too much space and bandwidth. I myself find that about half the remux bitrate is usually optimal for most media.

**Comment by bakerboy448** [comment]
This isn't possible for grabs and can only be used for imports which wouldn't be helpful for grabbing upgrades as desired.
Prefer groups that make better releases is the solution here.

larger discussion on incorporating media info to custom formats being thought about upstream https://github.com/Sonarr/Sonarr/issues/5598

**Comment by Mythic000** [comment]
well hope you find a solution, maybe the alternative solution would work

**Comment by bakerboy448** [comment]
Quality doesn't use bitrate for anything and it's only there for informational to give the user useful guidance.

**Comment by Mythic000** [comment]
> Quality doesn't use bitrate for anything and it's only there for informational to give the user useful guidance.

Im not sure what you mean by quality is only informational? with quality i was referring to the quality menu where you are setting bitrate rules for what bitrates you accept on the releases. Uses GiB/h. So for this to function file size and play length must be accounted for in the grab selection process.

**Comment by Mythic000** [comment]
Ok. So ill try to explain a bit better. That exact function is what i would want from the custom format nothing more size/length. To set a score on for example  on a movie with 9Gib/h to 19Gib/h as higher than a movie with 1GiB/h to 9 GiB/h. I'm sorry if I where confusing. Radarr is reading this information as you can se when a movie is outside of these rules when manually searching. So it has information of size and length of the movie.

**Comment by bakerboy448** [comment]
> To set a score on for example on a movie with 9Gib/h to 19Gib/h as higher than a movie with 1GiB/h to 9 GiB/h

this is already supported with the preferred size in quality defintions.

**Comment by Mythic000** [comment]
No because preferred size will never be used to upgrade a file. That is why it is needed as a custom format. I rather get any file that i can and then let radarr upgrade the file, but this is the only mayor hurdle where radarr and sonarr can not do this. Otherwise ill love the app. Hope you come around and see the benefit. But thanks for your work.
