### ISSUE TITLE
Unable to communicate with TMDb

### ISSUE THREAD

**Issue by tillkruss** [Radarr/Radarr#9109]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When searching for movies (or trying to import media) I see:

```
Failed to load search results, please try again.
Search for 'asdasd' failed. Unable to communicate with TMDb.
```

### Expected Behavior

Search results.

### Steps To Reproduce

N/A

### Environment

```markdown
- OS: Synology DSM 7.2-64570 Update 1
- Radarr: 4.7.5.7809
- Docker Install: No
- Using Reverse Proxy: No
- Browser: macOS Safari 16.6
- Database: ???
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

I'm not sure I can access trace logs on Synology, but this is the event exception.

```
NzbDrone.Common.Http.UnexpectedHtmlContentException: Site responded with browser content instead of api data. This disruption may be temporary, please try again later. [https://api.radarr.video/v1/search?q=test&year=]: Site responded with browser content instead of api data. This disruption may be temporary, please try again later. [https://api.radarr.video/v1/search?q=test&year=]
```

The exception:
```
NzbDrone.Common.Http.UnexpectedHtmlContentException: Site responded with browser content instead of api data. This disruption may be temporary, please try again later. [https://api.radarr.video/v1/search?q=asdasd&year=]
   at NzbDrone.Common.Http.HttpClient.CheckResponseContentType(HttpResponse response) in ./Radarr.Common/Http/HttpClient.cs:line 383
   at NzbDrone.Common.Http.HttpClient.GetAsync[T](HttpRequest request) in ./Radarr.Common/Http/HttpClient.cs:line 333
   at NzbDrone.Common.Http.HttpClient.Get[T](HttpRequest request) in ./Radarr.Common/Http/HttpClient.cs:line 340
   at NzbDrone.Core.MetadataSource.SkyHook.SkyHookProxy.SearchForNewMovie(String title) in ./Radarr.Core/MetadataSource/SkyHook/SkyHookProxy.cs:line 483
<!DOCTYPE html>
<html>
    <body>
        <input type="hidden" id="http" name="http" value="5000">
        <input type="hidden" id="https" name="https" value="5001">
        <input type="hidden" id="prefer_https" name="prefer_https" value="false">
    </body>
    <script type="text/javascript">
        var protocol=location.protocol;
        var port=location.protocol === "https:" ? 5001 : 5000;
        var URL=protocol+"//"+location.hostname+":"+port+location.pathname+location.search;
        location.replace(URL);
    </script>
</html>
```

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
> I'm not sure I can access trace logs on Synology, but this is the event exception.

The bug report template links to the wiki that describes how to get and provide trace logs. As the template notes: trace logs are not optional.

furthermore
 
 > Report a new bug, **if you are not 100% certain this is a bug please go to our Discord first**

This appears to be a issue with your local network or ISP hijacking the request and/or returning an invalid ip via dns

**Comment by tillkruss** [comment]
Understood @bakerboy448.

The issue was UniFi's "ad blocking" feature.
