### ISSUE TITLE
Set default Profile on Bulk import

### ISSUE THREAD

**Issue by onedr0p** [Radarr/Radarr#912]
**Description:**

Seeing a lot of people having issues when they import because they didn't select a profile, we need it to either have a default value or validate that the field isn't empty.

**Comment by onedr0p** [comment]
should be "fixed" in next release (uses the ID of profile 1 if not default is not set.

**Comment by fishslapman** [comment]
Im on 0.2.0.1450 and I'm still getting this problem. Any profile changes made to all movies via the movie editor only last for a few minutes before reverting back to their original profiles.
