### ISSUE TITLE
Change default quality from HDTV-720p to DVD (or something else) in Bulk import

### ISSUE THREAD

**Issue by onedr0p** [Radarr/Radarr#913]
**Description:**

HDTV-720p isn't a really a common movie quality, so changing it will be beneficial to people.

**Comment by stevenolsen** [comment]
Possible to have this as a settable option please?

**Comment by obelisk3847** [comment]
I think the only real change that needs to be made is for it to assume HD rips are BluRay rather than HDTV. The HDTV assumption made sense for Sonarr since it was for TV content but most people download BluRay rips if they are keeping them as far as movies go.

**Comment by mow4cash** [comment]
+1 for a settable option

**Comment by onedr0p** [comment]
Moved to #1005
