### ISSUE TITLE
Manifest.json missing + Wrong start_url

### ISSUE THREAD

**Issue by hebval** [Radarr/Radarr#9138]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Tried to add my webpage "mydomain.com/radarr" to my iPhone home screen. 
However, my iPhone won't let me have the full URL, and always used to rewrite just "mydomain.com".

Apparently, this comes from the manifest.json file + a start_url field missing : 
https://apple.stackexchange.com/questions/385417/add-to-home-screen-saves-wrong-url

So I checked if my Sonarr folder had a manifest.json file, and it did, but he didn't have the start_url field.
I just copied that file to the same location under my Radarr folder, and added the following line :

"start_url":"/radarr"

Restarted, and it did the job. 

### Expected Behavior

It would be nice to have the manifest directly, and not to add it manually. :)

### Steps To Reproduce

Windows -> Radarr as a service behind NGINX with "radarr" as URL Base.
WIth Safari/Chrome on a iOS device, open the Radarr webpage, and try to add this webpage to your homescreen : The menu to add the app won't let you add the /radarr and only writes your base site name.

### Environment

```markdown
- OS: Windows 10
- Radarr: 4.7.5.7809
- Docker Install: No 
- Using Reverse Proxy: Yes 
- Browser: Chrome/Safari latest
- Database: /
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

I fixed the issue on my side without tracing logs sorry... :| 

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by hebval** [comment]
Sorry for the version, updated it. 
Seeing here https://github.com/Radarr/Radarr/commit/854b3045fe45006dd713ccbf2192e62cb0651c41 
That it got fixed 4 months ago, but apparently, even with the updated version, I never got this file.

**Comment by ShadowXVII** [comment]
This causes issues with chrome mobile because you can't install a non-manifest version of the app like Sonarr.

Same issue with start URL breaking the installed Chrome app.
