### ISSUE TITLE
Synology Download Station Client - "Failed to get the list of torrents (...)"

### ISSUE THREAD

**Issue by dequire** [Radarr/Radarr#914]
**Description:**

Hi,
I installed Radarr on Synology DS215j and then updated to the recent dev version.
When trying to configure Synology Download Station as a download Client, I'm getting such error

> Failed to get the list of torrents: Error converting value "https" to type 'NzbDrone.Core.Download.Clients.DownloadStation.DownloadStationTaskType'. Path 'data.tasks[1].type', line 1, position 1520.

![synologyds_failed_to_get_the_list_of_torrents](https://cloud.githubusercontent.com/assets/24354336/23342965/d2b98d20-fc63-11e6-9b05-de4d5a565eec.PNG)

At the same time I have CouchPotato and SickRage using SynologyDS as downloader and it works fine :-)

**Radarr Version:**
0.2.0.375

**Logs:**

17-2-26 20:35:56.2|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Failed to get the list of torrents: Error converting value "https" to type 'NzbDrone.Core.Download.Clients.DownloadStation.DownloadStationTaskType'. Path 'data.tasks[1].type', line 1, position 1520.

**Comment by onedr0p** [comment]
Think this was fixed in the nighties, please confirm.

**Comment by maxkoning** [comment]
I also have this problem, but with Sonarr, on the DS215j.
