### ISSUE TITLE
Group Recognition Error

### ISSUE THREAD

**Issue by PlanZV** [Radarr/Radarr#9149]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Source Title:
[马达加斯加]Madagascar 2005 Blu-ray Remux 1080p AVC True-HD 5.1-Azure@Dream

Standard Movie Format：
{Movie CleanTitle} {(Release Year)} [imdbid-{ImdbId}] - {Edition Tags }{[Custom Formats]}{[Quality Full]}{[MediaInfo 3D]}{[MediaInfo VideoDynamicRangeType]}{[Mediainfo AudioCodec}{ Mediainfo AudioChannels}][{Mediainfo VideoCodec}]{-Release Group}

Final movie title generated by radarr：
Madagascar (2005) [imdbid-tt0351283] - [Remux-1080p][TrueHD 5.1][AVC]-马达加斯加.mkv

### Expected Behavior

Apparently the squeeze team should be Dream and not 马达加斯加

### Environment

```markdown
- OS: synology
- Radarr: 4.7.5.7809 — Aug 14 2023
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: chrome
- Database:
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

none

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
`@Dream` is not and is never a valid naming format for a group. The standard is `-GROUP` with some doing `(Group)` or `[Group]` at the end. Based on that naming the detected group is hitting the anime logic which may or may not be fixable.

`@Dream` can be added to the exception group list, but how many releases do they have/ do

**Comment by PlanZV** [comment]
I don't know much about this group, I just don't quite understand why 马达加斯加 is recognized as a {group}

Final movie title generated by radarr:
Madagascar (2005) [imdbid-tt0351283] - [Remux-1080p][TrueHD 5.1][AVC]-Madagascar.mkv

**Comment by bakerboy448** [comment]
Because anime group convention is [Group] Movie Title Release Details

what's the (I) in history show for the import event details.

and screenshot of history as well. Trying to see grab name and pre-import name.
