### ISSUE TITLE
API result shows only 10 results

### ISSUE THREAD

**Issue by SJ50** [Radarr/Radarr#915]
I used to run to get id and use id value to change movie path and refresh.
````
curl -s http://$RADARRHOST/api/movie -H X-Api-Key:$RADARRAPI --compressed | jq -rs --arg title "$NAME" '.[]| .[] | select(.title == $title ) | .id'
````
to get desire id value and run further operations.
after 25th feb (nightly update) it shows following error 
````
jq: error (at <stdin>:907): Cannot index number with string "title"
````

so I just run this command 
````
curl -s http://$RADARRHOST/api/movie -H X-Api-Key:$RADARRAPI -X GET -k
````
it only fetched 10 results starting as follows
````{
  "page": 1,
  "pageSize": 10,
  "sortKey": "Id",
  "sortDirection": "ascending",
  "totalRecords": 389,
  "records": [
....
....
....
````

I have no idea how to use JQ, I just modified my sonarr script a little to get desire workflow to finish successfully.

**Comment by onedr0p** [comment]
@galli-leo this has to do with the paging, we should still have a API request for all movies?

**Comment by galli-leo** [comment]
I think I will give back the full movies of you dont specify any paging parameters.

**Comment by geogolem** [comment]
this should be fixed...  in the latest build. I ran into this issue too.  

if no page size was specified we were defaulting to 10.

now we default to 100000....

**Comment by onedr0p** [comment]
It prolly is fixed but the API returns different JSON then what it used to, thats okay though just need to update the docs

**Comment by onedr0p** [comment]
Closing. Someone please update the docs.
