### ISSUE TITLE
Disable the need for Authentication if using SSO

### ISSUE THREAD

**Issue by Subdarub** [Radarr/Radarr#9163]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

All my infrastructure is sitting behind Authentik. While i dont expect Radarr to support header based authentication, i dont want to login twice. 

### Describe the solution you'd like

I understand that having authentication be a default requirement is a best practice to keep people from exposing their instances to the public, for everyone to access. 

So i am suggestion a simple opt in setting e.g "SSO enabled - disable Login Form" 
This setting can also be Advanced only to keep more casual users from accidentally enabling it. 

### Describe alternatives you've considered

- Login Disabled for Local IP Addresses -> Not gonna work unless you let me specify 0.0.0.0/0 as local 
- Autofill Browser based Login -> Unfortunately not supported by Authentik

### Anything else?

-

**Comment by bakerboy448** [comment]
Duplicate of https://github.com/Radarr/Radarr/issues/9104
