### ISSUE TITLE
Radarr doesn't match on alternate title

### ISSUE THREAD

**Issue by mschumacher69** [Radarr/Radarr#9167]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I use mdblist and torrentgalaxy rss indexer.

For example the movie Eloises.Lover.2009 from the indexer is not captured because radarr knows it as Eloise.2009 from the list.

### Describe the solution you'd like

Radarr should capture on alternate titles as well.

### Describe alternatives you've considered

No alternatives.

### Anything else?

No.

**Comment by bakerboy448** [comment]
What's the issue here? That movie names as the alt title from lists are not looked up by alt title?

please provide trace logs of the import lists

**Comment by mschumacher69** [comment]
Movie name in the indexer: Alt title
Movie name in the list: Original title

So movie names as the original title from lists are not looked up by alt title in indexers.
In other words, if the indexer has a movie by alt title, it's not matched to the movie in the list which would have the movie by original title.

I just enabled trace logs now, do I have to wait a while before sharing the logs or can I share it right away?

**Comment by bakerboy448** [comment]
- https://wiki.servarr.com/radarr/troubleshooting#missing-results
- https://wiki.servarr.com/radarr/faq#text-searches

alt titles are not used for searching
