### ISSUE TITLE
Using remote (cloud) folders for media. Very slow to add existing. [Feature/Fix]

### ISSUE THREAD

**Issue by ctroncoso** [Radarr/Radarr#917]
When mounting a remote folder (via SMB or other), adding existing movies is almost a standstill.

Testing with a single folder with a single movie, it took some time (10 minutes), but it got added.
I "assume" that the import process has to parse the file, thus downloading the whole library just to parse it. 
I'd recommend an 1MB test download to test the parsing speed. If the time exceeds N seconds, the adding procedure should fall back to "only filename" identification to speed up the process, and delay the analysis to  idle cycles.

Check https://github.com/Radarr/Radarr/issues/904#issuecomment-282564577

Radarr Ver. 0.2.0.375

**Comment by SuperGaco** [comment]
+1 Right now I'm struggling to setup docker instead, since I cant use the windows version till this fixed.  On a side note, if anyone is willing to help me set it up, I would be much obliged, as I'm currently hitting my head against a brick wall.

**Comment by ctroncoso** [comment]
I'm running it on docker, but this is not the place to talk about it. Post it on https://www.reddit.com/r/radarr/ and I'll follow up.

**Comment by SuperGaco** [comment]
done will delete this comment soon

**Comment by SuperGaco** [comment]
https://redd.it/5wd1jc

**Comment by hotio** [comment]
Try disabling media scanning or upgrade your network...

**Comment by dm447** [comment]
Appears to the the case with RClone too. When adding a folder mounted with RClone and monitoring network traffic I see the download speed shoot up. What does this parse in order to identify the movie, the whole file? That could take a long time (1TB).

**Comment by galli-leo** [comment]
@dm447 It only parses the first few percent of the file, but it probably takes a long time regardless, due to the latency. This should work better with custom-formats, since you can disable analyzing.

**Comment by dm447** [comment]
Is it safe to say that after a bulk import and library scan it no longer downloads the first few percent of everything again when the scheduled tasks run?

**Comment by Qstick** [comment]
Calling this fixed in v3. Let me know otherwise
