### ISSUE TITLE
[Feature request] Bookmarklet to add movies directly from IMDb/TMDb or wherever you are.

### ISSUE THREAD

**Issue by mescon** [Radarr/Radarr#921]
I just migrated to Radarr, and HOLY SMOKES is it much much better than CouchPotato already!
One thing that I do miss though, is the possibility to add movies directly to Radarr when browsing around IMDb.

Perhaps their implementation can be (mostly) ported over to Radarr, but with other API calls of course?

Just a thought!

**Comment by seriosbrad** [comment]
YES

I used that [Chrome extension](https://chrome.google.com/webstore/detail/couchpotato/jochingjncojldfclaicaomboafaiong) button a ton when running CouchPotato, it's extremely handy.  I doubt it can be ported, that extension is monetized and closed source I believe.  Gonna need to be done from scratch.



FWIW, on Android, if you have nzb360, you can "share to nzb360" from the IMDB app and it will be added to Radarr.

**Comment by onedr0p** [comment]
This is outside the scope of the project, we have an API so other developers can build this tool.

**Comment by ericmagnuson** [comment]
For those still looking, try [roboticsound/Pulsarr](https://github.com/roboticsound/Pulsarr).
