### ISSUE TITLE
[DVD] Add support to dinstinguish qualities

### ISSUE THREAD

**Issue by gravelfreeman** [Radarr/Radarr#9213]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

It's currently impossible to distinguish the quality of DVD releases.

### Describe the solution you'd like

Add the following formats:
- DVD9
- DVD5
- Remux-480p*
- Remux-576p*
- DVDRip

Remove the following format:
- DVD

### Describe alternatives you've considered

Use Custom formats regex but this adds up to when using an already complicated language setup.

### Anything else?

The saying that H264 DVDRip are better than DVD Remuxes is an incorrect statement. Both have their advantages and I would say that in theory a good H264 encode will feature lossless perceived visual quality, will save a lot of space over MPEG2 and will remove unwanted letter-boxing and black bars. In practice most DVDRip releases floating around are badly encoded. DVD encoding is a rather complicated process and will require a lot of knowledge despite what's commonly believed. I understand this wouldn't matter few years ago but now that the majority of mainstream media has been released on Blu-ray and/or streaming platforms, what remains on DVD if more than  often less popular. Those are usually seek by collectors whom quality matters. As a collector myself I have a lot of rare DVDRip movies that I would like to be informed once the full DVD or Remux is uploaded somewhere.

* 480p is NTSC DVD format
* 576p is PAL DVD format

**Comment by Qstick** [comment]
We have no plans for this, this is why Custom Formats exists
