### ISSUE TITLE
Possible move movie from Wanted when download started?

### ISSUE THREAD

**Issue by joelm3103** [Radarr/Radarr#922]
**Description:**

May look cleaner if you move the movie from "**Wanted**" when the download starts. This way when you hit "**Search All Missing**", those won't be included again. Alternatively you can add the **download status** on the Wanted page for all that is currently in "**Activity**".

**Radarr Version:**
0.2.0.375

**Comment by zductiv** [comment]
Search all missing will filter items in the activity queue so they shouldn't be searched again. They'll still show in missing though as you said. Like the rest.

**Comment by djoole** [comment]
+1, a "snatched" state to differentiate the really "missing" stuff would be a big plus, and would clean the wanted list, that I would like to use to watch for movies that are "stuck" (ie released but not auto dl for any reason)

**Comment by djoole** [comment]
This is still an enhancement wanted on my side
