### ISSUE TITLE
Quality wanted 720p but Radarr grabbed a 1080p release

### ISSUE THREAD

**Issue by sollz** [Radarr/Radarr#9229]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Radarr grabs a 1080p release as you can see in the image below, the quality mapped is 720p while the actual quality is 1080p

release is imdb:tt0076085 

![grabbed 1080p instead of 720p](https://github.com/Radarr/Radarr/assets/146654529/421d333c-ccd2-4ba4-8621-08210e3a3e85)
 

### Expected Behavior

Radarr should grab a 720p release, with so many 720p releases to choose from it grabbed the only one that is incorrectly mapped as 720p

![it should have grabbed any 720p release](https://github.com/Radarr/Radarr/assets/146654529/165c9274-ba41-44e9-b26d-40c1474d099a)

### Environment

```markdown
- OS: Debian 11
- Radarr: 4.4.4.7068
- Docker Install: No
- Using Reverse Proxy: Yes
- Browser: not needed
- Database: Sqlite 3.34.1
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

https://gist.github.com/sollz/f1e0dfcc24ca7c3d9a705329a1ef13cd

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
```
2023-10-01 16:05:33.1|Debug|QualityParser|Trying to parse quality for Una giornata particolare-1977-tt0076085-Bluray-1080pSpecial-IT-GCJM-
2023-10-01 16:05:33.1|Trace|Http|Res: 13237 [GET] /radarr/api/v3/importlist/schema: 200.OK (6 ms)
2023-10-01 16:05:33.1|Debug|Parser|Quality parsed: Bluray-720p v1
```

**Comment by Qstick** [comment]
I'd chock this up to a bad release name. Nobody uses 1080pSpecial in their release names, and no reason to have code for a single release.
