### ISSUE TITLE
Default view for Wanted -> Missing should be "All" instead of "Available & Monitored"

### ISSUE THREAD

**Issue by fryfrog** [Radarr/Radarr#923]
After a recent update, it looked like all my Wanted movies had disappeared. Turns out the new view default for Wanted -> Missing is "Available & Monitored" instead of All. Nothing was listed and it wasn't obvious why until I added and searched for an older movie, then started flipping through the views.

**Comment by hotio** [comment]
There's now a new movie field called "Minimum Availability", if you set this to preDB, you'll see the advantage of the new default "Available & Monitored". No need to load a list with movies which could be years into the future.

**Comment by fryfrog** [comment]
Thanks, I'll flip over all my Wanted movies and see how that looks. Doing it one at a time is fun so far! :)

**Comment by hotio** [comment]
movie editor

**Comment by geogolem** [comment]
ya.. i just made the default view here "Available & Monitored" because generally that is what *I* found most useful... if people object we could change the default view or work something else out...

**Comment by geogolem** [comment]
i think this has been changed and the default view is now "Monitored".. I am going to close this issue off.
