### ISSUE TITLE
Backup/Restore Password

### ISSUE THREAD

**Issue by WoodyJ007** [Radarr/Radarr#9233]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I have Radarr on my windows PC.  I'm trying to move it to Synology using the community install.  All installs and runs file.

If I backup my settings on the PC and restore them I can not login.  Username and password are incorrect but they are not.  I've tried the wiki where it says to set authentication to none in config,XML but that doesn't work as I then get an error about profiles missing and I cant get into any settings to turn authentication back on.

### Expected Behavior

Restore to work and bring the system back correctly.

### Steps To Reproduce

See description.  Backup on PC.  Newly installed Radarr on Synology DSM 7.1.1 using community package (not docker),  Restore and fails to login with correctly username and password.  Updating config makes things worse.

### Environment

```markdown
- OS: DSM 7.1.1
- Radarr: 20230426-20
- Browser: Chrome
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

None

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
- 20230426-20 is not a valid Radarr version
- Trace logs are not optional
- The database includes the username/password
