### ISSUE TITLE
Radarr adding 'radarr' directory to seeding location

### ISSUE THREAD

**Issue by prem1er** [Radarr/Radarr#924]
Since the latest update 0.2.0.375, radarr has added a directory to my seeding location titled 'radarr'. The created directory is nesting movies inside it upon downloading. It places movies that are a part of a directory into the 'radarr' directory. If the downloaded movie is not in a directory itself, the movie is not nested inside 'radarr'.

Example:
Previous functionality - /path/to/seeding/movies/movie.name/movie-name.mkv
Current functionality - /path/to/seeding/movies/radarr/movie.name/movie-name.mkv

It is not a major problem, I just don't understand why it is nesting my movies in another directory.

Ubuntu 16.04

**Comment by fryfrog** [comment]
I think Radarr and Sonarr do this as an alternative for clients that don't support labels so that they don't try to process literally every torrent. What torrent client are you using?

**Comment by onedr0p** [comment]
what download client are you using? I think this is expected behavior so the radarr movies are separate from your other downloads.

**Comment by prem1er** [comment]
I'm using transmission 2.84. Sonarr doesn't do this with my TV shows and radarr just started doing this after the latest release.

**Comment by onedr0p** [comment]
![image](https://cloud.githubusercontent.com/assets/213795/23388590/09b4c48e-fd31-11e6-862a-8b85df8ec400.png)

Maybe you need to change that to movies and save?

**Comment by prem1er** [comment]
This might be the correct solution. I don't have anything set there for sonarr and I do have 'radarr' as a value for radarr. I removed the value altogether and will test. I'll close if this is what was causing it. Thanks for the responses.

**Comment by onedr0p** [comment]
Seems like your set, closing.
