### ISSUE TITLE
Disabling authentication for "local addresses" should include configuration to define "local addresses".

### ISSUE THREAD

**Issue by garyblythe** [Radarr/Radarr#9242]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Offering authentication for Internet exposed Radarr instances makes sense. Mandating that requirement for all "non-local addresses", without allowing the user to define what constitutes local versus remote addresses (i.e., beyond the configured web interface address and 127.0.0.0/8) is relatively constraining - and not in a good way.

### Describe the solution you'd like

Suggest taking a look at Plex Server, for example, which provides the ability to use the default and configurable parameters that define local, vice remote network prefixes. In this case, local "LAN Networks" are defined by a comma delimited collection of CIDR prefixes that define local subnets that should be treated as local and may not require authentication...
![LocalNetworks](https://github.com/Radarr/Radarr/assets/27743318/be077d59-07eb-4c16-a87b-40e9b166d564)

### Describe alternatives you've considered

N/A

### Anything else?

N/A

**Comment by bakerboy448** [comment]
Please use [Discord](https://radarr.video/discord) for support/questions.

there's no need for this as the logic should already handle local addresses

https://github.com/Radarr/Radarr/blob/5517e578b6abd2e33ea3ce6b117edb2d4086b296/src/NzbDrone.Common/Extensions/IpAddressExtensions.cs#L8

**Comment by skykingjwc** [comment]
What about IPV6?

**Comment by RobinDadswell** [comment]
> What about IPV6?

IPV6 is handled in that same block Mentioned, but here are the lines. Follows the RFC for "local" when it comes to IPv6 

https://github.com/Radarr/Radarr/blob/8fb21e073b7f7d1b4b090f20fca0cd19acab2aad/src/NzbDrone.Common/Extensions/IpAddressExtensions.cs#L31-L33

**Comment by jkoelker** [comment]
Should [rfc6598](https://www.rfc-editor.org/rfc/rfc6598) Shared Address Space (`100.64.0.0/10`) be added to the list of local networks? Its common in private networks (netbird, tailscale, and others) and is treated similarly to 1918 addresses on router ingress (dropped).
