### ISSUE TITLE
Disable authentication entirely

### ISSUE THREAD

**Issue by Fossil01** [Radarr/Radarr#9245]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I am now forced to login to Radarr and cannot disable it. Radarr sits behind a Cloudflare Tunnel which uses authentication on it's own so it's perfectly safe.

I don't want to have to login a second time. The local address exclusion does not help me since it always thinks I am external due to Cloudflare.

### Expected Behavior

No login

### Environment

```markdown
.
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

.

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
Please use [Discord](https://radarr.video/discord) for support/questions.

> forcing a large portion of your user base to have a separate Radarr acount and making them login twice.

This is 100% incorrect. Again see the FAQ link or visit discord for support.

**Comment by zombu2** [comment]
^^^

**Comment by bakerboy448** [comment]
> Apologies I misread that portion. I figured `External` had more settings to integrate it with an external IDP. Still this should just be an option in the UI IMHO.

See https://github.com/Radarr/Radarr/issues/7047

something being explored in Zeus

**Comment by rocketeeer** [comment]
Why is the `<AuthenticationMethod>External</AuthenticationMethod>` `config.xml` option buried in the FAQ and not presented as an option in the GUI?

This type of railroading, even though well-intentioned, is concerning

**Comment by RobinDadswell** [comment]
> Why is the `<AuthenticationMethod>External</AuthenticationMethod>` option in `config.xml` buried in the FAQ and not presented as an option in the GUI?
> 
> This type of railroading, even though well-intentioned, is concerning.

We have been asked by multiple indexers to ensure authentication due to people leaving their instances open. The reason this is not in the GUI is to make it harder for people to do that and ensure that they actually know what they are doing when they go to do this as it could leave the application unauthenticated if other configuration is not setup appropriately.

**Comment by gardner** [comment]
```bash
docker compose stop
sed -i 's/AuthenticationMethod>None/AuthenticationMethod>External/' radarr/config/config.xml 
sed -i '/AuthenticationRequired/d' radarr/config/config.xml
docker compose restart radarr
```

**Comment by Trolann** [comment]
> > Why is the `<AuthenticationMethod>External</AuthenticationMethod>` option in `config.xml` buried in the FAQ and not presented as an option in the GUI?
> > This type of railroading, even though well-intentioned, is concerning.
> 
> We have been asked by multiple indexers to ensure authentication due to people leaving their instances open. The reason this is not in the GUI is to make it harder for people to do that and ensure that they actually know what they are doing when they go to do this as it could leave the application unauthenticated if other configuration is not setup appropriately.

I don't keep up with the project as much as I should, and finals kept me from updating until Christmas break. I didn't go to the FAQ, I went to google 'radarr disable authentication' and this is the first result.

As a suggestion, could there be some indication in the UI pointing to the FAQ? "See the FAQ for information on integrating external authentication providers"? 

Appreciate all the clear instructions in here and the direct links to the relevant FAQ. Disabling auth was a quick fix.
