### ISSUE TITLE
Current version adds unwanted collection artwork

### ISSUE THREAD

**Issue by Killface1980** [Radarr/Radarr#9246]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

For freshly downloaded films, Radarr also downloads unwanted artwork like movieset-banner.jpg, movieset-clearart.png, movieset-clearlogo.png, movieset-fanart.jpg and movieset-landscape.jpg and maybe more.

I have unchecked all metadata downloads as I see it as unreliable. I do not want those files.

### Expected Behavior

No unwanted downloads unless explicitly wanted.

### Steps To Reproduce

Download a film that's part of a collection.

### Environment

```markdown
- OS: 
- Radarr: 
- Docker Install: 
- Using Reverse Proxy: 
- Browser: 
- Database:
```

### What branch are you running?

Develop

### Trace Logs? **Not Optional**

No log.

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
Invalid bug report. Please populate the required information in Environment and provide the required trace logs of radarr downloading this artwork. Also please do not check the box stating you provided trace logs and followed the wiki when no logs are provided.

> **Trace Logs have been provided as applicable.** ***Reports will be closed if the required logs are not provided.***

Can reopen if/when the required information is provided.
