### ISSUE TITLE
[Nightly] Can't change REMUX values

### ISSUE THREAD

**Issue by d2dyno** [Radarr/Radarr#926]
**Description:**

I'm unable to edit the name field for the 'Remux-1080p' quality field (from #900). Nor can I adjust the minimum size. When I make the changes and click save, there is no confirmation of the values being saved. Reloading the pages, shows the changed values were not saved.

**Radarr Version:**
Radarr Ver. 0.2.0.413 - nightly
**Logs:**
None for this.

**Comment by onedr0p** [comment]
Set a page size in UI settings, this is already reported.
