### ISSUE TITLE
When moving files, the filename can sometimes be lost.

### ISSUE THREAD

**Issue by Jleagle** [Radarr/Radarr#927]
I import files from NZBGet and sometimes the filenames are just random strings and the folder name is where all the data is. (maybe caused by the unraring process?)

When Radarr takes the file it loses all the data and just moves the file. I'd really like to keep the filename as it's intended filename to not lose any info. I'm guessing this instance is NZBGet's fault but it would be great to recognise when this happens and just use the folder name for the newly moved file.

An example:
![screen shot 2017-02-26 at 19 02 43](https://cloud.githubusercontent.com/assets/381099/23362644/9dc7819a-fcee-11e6-8bdb-3c252f4a7cd6.png)

Thanks.

**Comment by fryfrog** [comment]
Are you using {Original Filename} for your movies?

Maybe consider something better from the available options at https://github.com/Radarr/Radarr/wiki/Sorting-and-Renaming ?

I use {Movie CleanTitle} {(Edition Tags)} {(Release Year)} {[Quality Title]} personally.

That said, it wouldn't be crazy for {Original Filename} to have a counter part that gets the name from the folder. Or falls back to that for obfuscated file names.

**Comment by Jleagle** [comment]
I am actually using {Original Title}:
![screen shot 2017-02-27 at 16 07 23](https://cloud.githubusercontent.com/assets/381099/23371104/e9724ec0-fd0e-11e6-98b1-f6e3935f9109.png)


{Original Title} and {Original Filename} look the same for me in the preview, I didn't know the latter existed as it's not in the UI. When i set it to use just {Original Filename} i get an error "Must contain movie title"

But what I'm, really after is having the filename match the original release filename, not something that is generated.

**Comment by galli-leo** [comment]
This is fixed in the latest nightly. Be sure to use {Original Title}. If that detects a Scene name in the download client it will use that one. Else original filename is used.
