### ISSUE TITLE
Automatic renaming of folders and files

### ISSUE THREAD

**Issue by oli-g-sk** [Radarr/Radarr#9271]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I know there are related issues filed for this, even closed as wont-fix. I'm just posting this separately to hopefully get some explanation and clarification from the community, not necessarily from the contributors.

I feel like I'm missing something. I just started using Radarr today and I just can't phantom the fact that all of the following are true at the same time:

- Radarr insists on movies being in folders, ignores top-level files
- It won't create those folders for you
- It's perfectly capable of detecting a movie from a messy folder name
- The auto-rename feature will rename the files inside that folder, but not the folder

So after _finally_ trying out the software that's meant to...
1. Auto-download new content for me
2. Make my movie library nicely organized

Well, I truly do believe it kicks ass at no. 1 (haven't got there yet)
Regarding no. 2 though, what I'm currently left with is a root folder containing

1. Messy top-level file names that Radarr completely ignores.
2. Top level folders that Radarr detected, but won't let me rename.
3. Nice looking filenames within those folders. What's the point of that?

Just look:

- Movies
  - A.Moment.to.Remember.2004.Director's.Cut.1080p.BluRay.DTS.x264-DON
    - A Moment to Remember (2004) Bluray-1080p.mkv
    - A Moment to Remember (2004) Bluray-1080p.srt
  - Climax.2018.1080p.BluRay.x264-nikt0
    - Climax (2018) Bluray-1080p.mkv
  - 02 The Raid 2 - Berandal [2014] [Uncut Edition] 1080p BDRip x265 DTS-HD MA 5.1 Kira [SEV].mkv
  - Hotel.Fear.aka.Pensione.paura.1978.1080p.BluRay.REMUX.AVC.FLAC.1.0-aCant.mkv
  - Non.si.sevizia.un.paperino.1972.aka.Dont.Torture.a.Duckling.1080p.BluRay.x265.hevc.10bit.AAC.1.0.dual-HeVK
  
Now without trying to sound arrogant or rude... how does this make sense to _anyone_? Instead of making it more organized, it's still messy, but _differently_. As a bonus, Plex won't play and torrents won't seed.

One could argue that I should deal with those top-level files myself. Fair, it's okay to insist on "prerequisities". But even if I did and Radarr recognized them, I'd have to go and rename each folder manually by copying the filename Radarr generously generated inside of it. That's not very helpful.

### Describe the solution you'd like

Radarr is doing two things.
1. Auto download
2. Organization

If it's only capable of doing 50% in the organization department, wouldn't it be a better app if it did one thing and did that one thing well, and besides that, not care about how I organize my files? Plex is doing just fine with that messy folder. I just wanted it to look nice in file browsers; now I'm left with a broken library.

Again, I don't want to come off as rude, and I appreciate all the hard work here. **I just don't get it from the philosophy / design decisions point of view, at all, and it's driving me nuts.** Tbh, I expected a 2 minute library scan that would give me something like:

- Movies
  - A Moment To Remember (2004)
    - A.Moment.to.Remember.2004.Director's.Cut.1080p.BluRay.DTS.x264-DON.mkv
    - A.Moment.to.Remember.2004.Director's.Cut.1080p.BluRay.DTS.x264-DON.srt
  - Climax (2018)
    - Climax.2018.1080p.BluRay.x264-nikt0
 - Don't Torture a Duckling (1972)
   - Non.si.sevizia.un.paperino.1972.aka.Dont.Torture.a.Duckling.1080p.BluRay.x265.hevc.10bit.AAC.1.0.dual-HeVK.mkv
   - ...or
   - Dont.Torture.a.Duckling.1080p.BluRay.x265.HEVC.10bit.AAC.1.0.DUAL-HeVK.mkv

Basically, the ideal "onboarding" experience for a new Radarr user with existing (messy) Plex library would be
1. Match both folder names _and_ file names to movies (the implementation is there)
2. Ask me **if I want Sonarr to move/rename my _current_ media**
  a. If yes, ask me if a want **a flat folder, or subfolders**
  b. If I opt for subfolders, ask me if I want to **rename only folders, or also the files within them** (for me, the folder is the nice clean gateway, and having the file name more "detailed" is acceptable, even desired)
3. Once we're clear about my current media, ask me **how to organize the media it downloads itself** (with similar options)

### Describe alternatives you've considered

This is something I'm hoping someone would suggest to me, actually.

As I said, I'm new to Radarr, but the entire setup and initialization process came off as counter-intuitive and left me with a lot of things to manually undo.

Experienced users or devs might point out what I missed, or some secret trick to get me closer to what I was after. I created this issue to learn and to discuss, not to rant and diminish open-source work. Yes, I'll need to manually rename around 300 files. No, it's not the end of the world 😄

### Anything else?

Again, no hard feelings, not complaining or bitching.

I just... DON'T. GET. IT.

**Comment by bakerboy448** [comment]
https://wiki.servarr.com/radarr/quick-start-guide As well
