### ISSUE TITLE
Files not being properly moved and stay stuck in *.partial~ 

### ISSUE THREAD

**Issue by ajkis** [Radarr/Radarr#928]
**Description:**
Some files not being properly moved and stay stuck in *.partial~ , while radarr then proceed with next file. ( Edge of Darkness in image bellow )
![issue](https://puu.sh/umlN3/cc23de9e1a.png)

**Radarr Version:**
0.2.0.375
**Logs:**

> 17-2-27 17:27:25.3|Info|RecycleBinProvider|Recycling Bin has not been configured, deleting permanently. /mnt/unionfs/movies/Edge of Darkness (2010)/Edge of Darkness (2010).mp4
> 17-2-27 17:28:31.8|Warn|ImportApprovedMovie|Couldn't import movie /storage/download/nzbget/completed/movies/Edge.of.Darkness.2010.PROPER.1080p.BluRay.x264-NODLABS English/edge.of.darkness.2010.1080p.bluray.x264-nodlabs.mkv
>  
> [v0.2.0.375] System.IO.FileNotFoundException: Could not find file ""
>   at System.IO.File.Move (System.String sourceFileName, System.String destFileName) <0x7ff94415a5c0 + 0x002f0> in <filename unknown>:0
>   at NzbDrone.Common.Disk.DiskProviderBase.MoveFile (System.String source, System.String destination, Boolean overwrite) <0x4056c9c0 + 0x0024c> in <filename unknown>:0
>   at NzbDrone.Common.Disk.DiskTransferService.TryMoveFileTransactional (System.String sourcePath, System.String targetPath, Int64 originalSize, DiskTransferVerificationMode verificationMode) <0x4056b580 + 0x00189> in <filename unknown>:0
>   at NzbDrone.Common.Disk.DiskTransferService.TransferFile (System.String sourcePath, System.String targetPath, TransferMode mode, Boolean overwrite, DiskTransferVerificationMode verificationMode) <0x40563ac0 + 0x00a67> in <filename unknown>:0
>   at NzbDrone.Common.Disk.DiskTransferService.TransferFile (System.String sourcePath, System.String targetPath, TransferMode mode, Boolean overwrite, Boolean verified) <0x40563a40 + 0x0005b> in <filename unknown>:0
>   at NzbDrone.Core.MediaFiles.MovieFileMovingService.TransferFile (NzbDrone.Core.MediaFiles.MovieFile movieFile, NzbDrone.Core.Tv.Movie movie, System.String destinationFilePath, TransferMode mode) <0x40563370 + 0x00421> in <filename unknown>:0
>   at NzbDrone.Core.MediaFiles.MovieFileMovingService.MoveMovieFile (NzbDrone.Core.MediaFiles.MovieFile movieFile, NzbDrone.Core.Parser.Model.LocalMovie localMovie) <0x4055bd00 + 0x000fb> in <filename unknown>:0
>   at NzbDrone.Core.MediaFiles.UpgradeMediaFileService.UpgradeMovieFile (NzbDrone.Core.MediaFiles.MovieFile episodeFile, NzbDrone.Core.Parser.Model.LocalMovie localEpisode, Boolean copyOnly) <0x4055b970 + 0x002e6> in <filename unknown>:0
>   at NzbDrone.Core.MediaFiles.EpisodeImport.ImportApprovedMovie.Import (System.Collections.Generic.List`1 decisions, Boolean newDownload, NzbDrone.Core.Download.DownloadClientItem downloadClientItem, ImportMode importMode) <0x40556c40 + 0x01372> in <filename unknown>:0

**Comment by onedr0p** [comment]
We will need to replicate this issue... I never have seen this on my server. Maybe this is an issue with unionfs?

**Comment by onedr0p** [comment]
Can you enable trace logging and post the log when it happens again?

**Comment by ajkis** [comment]
hmm i upgraded to nightly and will see if it happens

**Comment by ajkis** [comment]
DId not happen with latest nightly version yet.

**Comment by onedr0p** [comment]
I'll close the issue then, report back if you are still having problems.
