### ISSUE TITLE
Can't save disabling auth

### ISSUE THREAD

**Issue by mzrimsek** [Radarr/Radarr#9282]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

The new window that forces you to enable auth does not allow me to save.

In my opinion this shouldn't be a forced feature and should be opt out.

I have my install behind a reverse proxy and protected by Authelia and it seems it is now broken and stuck on this screen. Very frustrating.

As it stands I will be forced to downgrade and pin my version to before this update as it introduces a very silly extra step that should be easily disabled with environment variables.

### Expected Behavior

I should be able to save

### Steps To Reproduce

Try to save the settings in the window that shows with the new update.

### Environment

```markdown
- OS: Ubuntu 20.p4
- Radarr: latest
- Docker Install: yes
- Using Reverse Proxy: yes
- Browser: Chrome latest
- Database: Sqlite
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

N/A

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
https://wiki.servarr.com/radarr/faq#forced-authentication
