### ISSUE TITLE
Disabling auth should be an Anv

### ISSUE THREAD

**Issue by azukaar** [Radarr/Radarr#9284]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

THe new forced authentication is good for most cases, but when using an external authentication method, it forces you to take some very manual in config files to disable it

### Describe the solution you'd like

While I understand why it's not in the UI, it should be settable via environment variables at least, in order to not destroy the scriptability of Radarr (for example if you have a docker-compose with reverse-proxy + Radarr in it)

### Describe alternatives you've considered

-

### Anything else?

-

**Comment by bakerboy448** [comment]
No near plans for Env Var support nor does Radarr support any Env Var at this time.

oneDr0p has containers that have some Env var support hacked in https://github.com/onedr0p/containers

**Comment by Qstick** [comment]
> No near plans for Env Var support nor does Radarr support any Env Var at this time.
> 
> oneDr0p has containers that have some Env var support hacked in https://github.com/onedr0p/containers

Radarr supports Env variables for Postgres Options

**Comment by azukaar** [comment]
Yes and it supports PG has env var, because the PG setup would require additional wizard to happen on first start, and not being able to set those var as Env, would mean building a turn-key Radarr app wouldn't be possible
Which is the same thing here IMO, it falls in the same category

In the meantime I will use the suggested docker image, thanks for the suggestion
