### ISSUE TITLE
Custom Filters not adhearing

### ISSUE THREAD

**Issue by MoldyTaint** [Radarr/Radarr#9290]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I have created a custom filter for monitored missing movies, there are a few movies that are downloaded and still show up

It does bring up all my unmonitored missing movies however there's 2-3 of them that are downloaded and still show up under the filer. I have tried to show a few screenshots for a better understanding.

![image](https://github.com/Radarr/Radarr/assets/98976440/44c44d31-9de4-4d4d-be60-e636e3c560fc)
![image](https://github.com/Radarr/Radarr/assets/98976440/134a7bd6-1154-4282-ab70-7b96a944d88c)
![image](https://github.com/Radarr/Radarr/assets/98976440/1dca06ed-cb92-4045-ad0e-88c372bde162)

### Expected Behavior

Filter should be able to see the movie size and keep those selected out.

### Environment

```markdown
- OS: Proxmox
- Radarr: 5.0.3.8127
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Firefox
- Database: Sqlite 3.41.2
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

https://pastebin.com/Z6wD4eNW

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
- logs not accessible

> there's 2-3 of them that are downloaded and still show up under the filer. I have tried to show a few screenshots for a better understanding.

f5 to reload the movie api data
