### ISSUE TITLE
Manual Import / Automatic Import from folder does not work

### ISSUE THREAD

**Issue by evulhotdog** [Radarr/Radarr#93]
![image](https://cloud.githubusercontent.com/assets/365456/21808969/abc2c1fc-d713-11e6-86d9-f16f5448f0d1.png)

![image](https://cloud.githubusercontent.com/assets/365456/21809012/d4b1b4b0-d713-11e6-9596-1c6eaa3175ff.png)

**Comment by fedoranimus** [comment]
Is this still an issue? I cannot imagine this problem still exists on the current version, as the shown UI is very out of date..

**Comment by fedoranimus** [comment]
Closing for lack of information. Will re-open if issue still exists.

**Comment by daveyboy37** [comment]
Guys, in the few days that I have been using Radarr, I haven't done any manual importing until today, so
I'm not really sure what I should be seeing but every movie gives the little pop-up in the bottom right. 
I read that there has been issues with manual importing previously (before my time with radarr), but that they should be fixed on the latest, which I'm running...Any ideas? 


<img width="567" alt="capture99" src="https://cloud.githubusercontent.com/assets/9288228/22251157/b346aa04-e241-11e6-8460-f9409d038afc.PNG">
<img width="353" alt="capture98" src="https://cloud.githubusercontent.com/assets/9288228/22251533/fa43731e-e242-11e6-9280-25f2d8c19705.PNG">
