### ISSUE TITLE
White list "hardcoded" subs (dksubs)

### ISSUE THREAD

**Issue by gilbN** [Radarr/Radarr#931]
**Description:**

I'd like to be able to white list dksubs. As in my experience, dksubs does not equal hardcoded.

**Radarr Version:**

0.2.0.375 

**Logs:**
 none

**Comment by tac00** [comment]
I have the same problem with dksubs releases. They gets rejected since the latest update of Radarr. If you want it to work for now downgrade to version 0.2.0.299. It works for me for Danishbits and HoundDawgs releases with dksubs.

**Comment by galli-leo** [comment]
Are all dksubs not hardcoded?

**Comment by gilbN** [comment]
I can't say for sure, but I have never seen a dksubs release with hard coded subs.

**Comment by onedr0p** [comment]
I thought dksubs were hardcoded? We added that in this issue:

https://github.com/Radarr/Radarr/issues/711

**Comment by tac00** [comment]
Nope none of the releases with dk.subs that I download is hardcoded. And I only download with dk.subs from danish trackers.

**Comment by onedr0p** [comment]
Just to confirm, no releases marked as DKSubs have hardcoded subs? I will revert that commit, just want to make sure you have seen a lot of these releases.

**Comment by onedr0p** [comment]
Fixed in next release

**Comment by galli-leo** [comment]
This is not how you fix this.

**Comment by onedr0p** [comment]
What do you mean? Now dksubs aren't marked as hard coded.

**Comment by galli-leo** [comment]
Yeah but other subs such as korsubs are allowed as well. We want a field to individually allow certain subs to be let through and to allow all subs.

**Comment by onedr0p** [comment]
Closing, duplicate #540
