### ISSUE TITLE
'Download client SABnzbd is set to remove completed downloads'

### ISSUE THREAD

**Issue by pven** [Radarr/Radarr#9310]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Radarr shows 'Download client SABnzbd is set to remove completed downloads'. Since I've configured 'Keep completed jobs maximum number of days' to 2 days, I don't want to see this warning. When Radarr is not able to import the job within 2 days, something else is wrong.

### Expected Behavior

I think this warning is only valid if History Retention is set to 'Do not keep any completed jobs'

### Environment

```markdown
- OS: Ubuntu 22.04.3 LTS
- Radarr: 5.0.3.8127
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: NA
- Database: NA
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

NA

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
- not a bug
- dismissible healthchecks is covered by existing GHI
- Retention must be 14 days at least as noted in the [release notes](https://github.com/Radarr/Radarr/commit/33d1d1f875d9bf2c23f35256a2c644bea1a61e7f) and the [docs linked by the healthcheck](https://wiki.servarr.com/en/radarr/system#download-client-removes-completed-downloads)
