### ISSUE TITLE
Postgres migration didnt work

### ISSUE THREAD

**Issue by barbequesauce** [Radarr/Radarr#9317]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Following directions on #7269 and in the [wiki](https://wiki.servarr.com/radarr/postgres-setup), I attempted to migrate my database to Postgres and received the following series of errors. I tried asking in the [Discord](https://discord.com/channels/264387956343570434/264388019585286144/1166406191170191441) but didnt receive a response...

```
KABOOM!
SIMPLE-ERROR: pgloader failed to find anything in schema "public" in target catalog.
An unhandled error condition has been signalled:
   pgloader failed to find anything in schema "public" in target catalog.




What I am doing here?

pgloader failed to find anything in schema "public" in target catalog.
```

Help please!

### Expected Behavior

Successful Postgres migration.

### Environment

```markdown
- OS: Debian Bullseye
- Radarr: :latest
- Docker Install: 24.0.6 
- Using Reverse Proxy: No
- Browser: N/A
- Database: SQLite at the moment....
```

### What branch are you running?

Nightly

### Trace Logs? **Not Optional**

See above

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by barbequesauce** [comment]
As mentioned in the body, I did ask in Discord and didn’t receive a response

**Comment by barbequesauce** [comment]
Scratch that - Discord response just came in, I missed this bit:

“ Before starting a migration please ensure that you have run Radarr against the created Postgres databases at least once successfully. ”

**Comment by Qstick** [comment]
The migration program isn't one that's officially supported by this team, it's community driven

**Comment by barbequesauce** [comment]
Thanks @Qstick - now that I've dropped/recreated the dbs and launched/shutdown Radarr to populate the shells, I've rerun the pgloader command and received a [load of warnings/errors](https://gist.github.com/barbequesauce/e71442ec20da90b2c400b2fc71d56289). Any thoughts?
