### ISSUE TITLE
convert german umlaut (ä|ü|ö) to (ae|ue|oe) when building newznab query string

### ISSUE THREAD

**Issue by FinalRikku** [Radarr/Radarr#932]
[**Description:**]

Radarr is not finding any releases when the original movie title is translated to german and contains german umlauts.

**Radarr Version:**

0.2.0.375

**Example:**

Jack Reacher: Never Go Back (original title)
Jack Reacher: Kein Weg zur**ü**ck (german title)

Name of the release and how it is indexed
Jack.Reacher.Kein.Weg.zur**ue**ck.2016.German.DL.1080p.BluRay.x264-ANYGROUP

Fifty Shades Darker (original title)
Fifty Shades Of Grey - Gef**ä**hrliche Liebe (german title)

Name of the release and how it is indexed
Fifty.Shades.of.Grey.Gef**ae**hrliche.Liebe.2017.TS.AC3MD.German.XViD-ANYGROUP

**Comment by onedr0p** [comment]
I think this is related #818 I'll revert that commit for now and see if it works.

**Comment by mihaiblaga89** [comment]
@onedr0p does it work? if not, we can convert "Kein Weg zurück" to "Kein Weg zuruck" first, and then encode it the way I did it

**Comment by onedr0p** [comment]
I reversed the commit, please let me know of it works on the current nightly and any logs if not..

**Comment by mihaiblaga89** [comment]
either way, you can't have any url encoding, and spaces are more common than umlauts

**Comment by onedr0p** [comment]
I didn't set any encoding, I removed it.

**Comment by mihaiblaga89** [comment]
That's the point :) none there is no urlencode. Whatever the user types, that's what is forwarded in the link. A simple space, a &, etc and it's broken.

**Comment by onedr0p** [comment]
I'll replace those characters with nothing.

**Comment by onedr0p** [comment]
And spaces with %20

**Comment by mihaiblaga89** [comment]
you still don't fix @FinalRikku's problem, because he needs ü replaced with ue. Just replace the special characters first, then use my function to encode the url. That's it, plain and simple

**Comment by FinalRikku** [comment]
Hey @onedr0p. I pulled to test Ver. 0.2.0.426 an there is no success so far. Still not finding any releases.

**Comment by mihaiblaga89** [comment]
@onedr0p please revert my commit and i'll make a new pull request that will fix @FinalRikku's problem

**Comment by onedr0p** [comment]
You can just submit one with it added back too. That's fine.

**Comment by onedr0p** [comment]
Fixed in next release. (in nightly). Still unsure how to to urlencoding.. I will do more research on that another day.

**Comment by FinalRikku** [comment]
Hi @onedr0p, i was testing the fix in version 0.2.0.479 and can confirm its works very well - perfect fine! Got a lot of results now for releases containing german umlauts. thank you.

**Comment by onedr0p** [comment]
Awesome! Glad to hear.

**Comment by InfAmoUsaeble** [comment]
Sorry to poke on this, but we have the same problem in Denmark :)

Failed to map movie, found title **Hjaelp** Jeg Er En Fisk, expected one of: Help! I'm A Fish, **Hjælp**, jeg er en fisk, A Fish Tale, Help! I'm a Fish

æ = ae
ø = oe
å = aa

Thank you!! <3

**Comment by galli-leo** [comment]
@InfAmoUsaeble Can you open a new issue for that?
