### ISSUE TITLE
Allow automatic import if custom score is higher, as an optional checkbox.

### ISSUE THREAD

**Issue by kmadaras** [Radarr/Radarr#9345]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I use custom formats, and have to manually intervene on a regular-basis to import higher scored items after the cutoff has been met for quality.

### Describe the solution you'd like

If I use custom formats, and I've reached the cutoff, I would like the option to check a box that would allow for Radarr to auto-import, even if the cutoff has been met.  The manual intervention is almost daily when using complex scoring to get the formats I'm seeking.  This would be an option, rather than the default, perhaps under advanced.  It could also be per profile to allow for additional flexibility.  Thanks for the consideration!

### Describe alternatives you've considered

I don't know of any settings that currently allow for this.

### Anything else?

No, it's a pretty straight-forward idea.

**Comment by bakerboy448** [comment]
Merge your qualities together and use the custom formats to rank everything
