### ISSUE TITLE
AuthenticationMethod is ignored after a restart

### ISSUE THREAD

**Issue by stumpylog** [Radarr/Radarr#9353]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

After editing `config.xml` to include `<AuthenticationMethod>External</AuthenticationMethod>`, Radarr will still prompt me to configure authentication settings, after every restart of the container.  My config now looks like:

```xml
  <AuthenticationMethod>External</AuthenticationMethod>
  <AuthenticationRequired>DisabledForLocalAddresses</AuthenticationRequired>
  <AuthenticationMethod>None</AuthenticationMethod>
  <AuthenticationMethod>None</AuthenticationMethod>
  <AuthenticationMethod>Forms</AuthenticationMethod>
  <AuthenticationMethod>None</AuthenticationMethod>
  <AuthenticationMethod>None</AuthenticationMethod>
  <AuthenticationMethod>Forms</AuthenticationMethod>
  <AuthenticationMethod>None</AuthenticationMethod>
  <AuthenticationMethod>None</AuthenticationMethod>
  <AuthenticationMethod>Forms</AuthenticationMethod>
```

### Expected Behavior

Radarr should read the config file, see `External` and follow it, not adding additional entries to the config file.

### Steps To Reproduce

1. Edit `config.xml` to add `<AuthenticationMethod>External</AuthenticationMethod>`
2. Restart Radarr container
3. Be prompted for authentication settings
4. Put in some settings
5. cat `config.xml`
6. See more and more `AuthenticationMethod` lines

### Environment

```markdown
- OS: Ubuntu 22.04
- Radarr: 5.0.3.8127
- Docker Install: Yes
- Using Reverse Proxy: Yes
- Browser: Firefox
- Database: SQLite
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

https://gist.github.com/stumpylog/7731dfa7fb9e73da9171c4e37d0c0f38

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by stumpylog** [comment]
This has also been mentioned in Discord: https://discord.com/channels/264387956343570434/264388019585286144/1166760590065291415 and https://discord.com/channels/264387956343570434/264388019585286144/1166831703902404730

**Comment by owine** [comment]
You say adding, do you then have two entries for `<AuthenticationMethod>` because there is one already there which you should edit.

**Comment by stumpylog** [comment]
I added a single entry for it.  After restarting the container, assuming it would be picked up, new entries are being added automatically

**Comment by owine** [comment]
> I added a single entry for it with External. After restarting the container, assuming it would be picked up, new entries are being added automatically, with both None and Forms

There is an existing line you should be editing rather than adding a new, duplicate entry which is being ignored

**Comment by stumpylog** [comment]
There was no existing entry, as I had not configured anything in the webui.  Regardless, even with a single entry, it is ignored after a container restart and new entries are added by Radarr.  As you can see in the config snipper above, I added my (single) entry at the top, as per the FAQ, only the top entry is used.

**Comment by stumpylog** [comment]
Doing more step by step with a lot of `cat` checks.

1. Stop radarr container
2. Single line `<AuthenticationMethod>External</AuthenticationMethod>` to the end of `config.xml`.  There are no other `Authentication*` settings in the file
3. Start radarr
4. Line `<AuthenticationRequired>Enabled</AuthenticationRequired>` added to config
5. Navigate to Web UI
6. Prompted for authentication and `<AuthenticationMethod>None</AuthenticationMethod>` added to config
7. Have to put something in to use my instance (Choose Forms)
8. Second `<AuthenticationMethod>None</AuthenticationMethod>` added, first `<AuthenticationMethod>Forms</AuthenticationMethod>` added too

**Comment by owine** [comment]
Provide the full contents of config.xml at each stage rather than just snippets. Redact your api key

**Comment by stumpylog** [comment]
It appears if I add two `AuthenticationMethod` lines, with a None first, then External, Radarr does not edit the None line, but instead starts adding None/Forms/Basic to new AuthenticationMethod lines with each restart.  It essentially makes the first None immutable, regardless of user input to the UI and enters a loop asking for setting up authentication at every start.

There must have been another line I didn't catch.  So the issue is the entering of this loop of requesting auth setup, adding a new line (instead of editing the existing first line), then ignoring that line at next start.  Hope that helps.

**Comment by stumpylog** [comment]
I still think it's a bug that radarr keeps adding new lines to the config, resulting in a loop, instead of editing the correct line to add the user's selected method.

If I'm a user, and I've selected Forms, isn't it wrong that after a restart, that setting is ignored and I have to input it again and again?

**Comment by bakerboy448** [comment]
https://wiki.servarr.com/radarr/faq#forced-authentication

> radarr keeps adding new lines to the config, resulting in a loop, instead of editing the correct line to add the user's selected method.

your steps as you noted are incorrect https://github.com/Radarr/Radarr/issues/9353#issuecomment-1784314268 the FAQ is clear in what is required and `<AuthenticationMethod>External</AuthenticationMethod> to the end of config.xml. There are no other Authentication* settings in the file` is not valid.  authentication method to External and NOT removing `AuthenticationRequired` is what is needed

**Comment by rotilho** [comment]
This is exactly what I have done @bakerboy448. I stopped the Radarr, replaced None with External and after starting it I'm again prompted with the Authentication Required screen.

Actually every single restart causes a new entry to be added.

**Comment by rotilho** [comment]
Hey @bakerboy448! Already done as posted earlier: https://discord.com/channels/26438795634357o434/264388019585286144/11 66831703902404730

I didn't post anything here because I was waiting to see if it was just me.

I can try again later but since there weren't any other release since my last try I'm afraid the outcome will be exactly the same.

**Comment by bakerboy448** [comment]
It's not a bug. Every single time the issue - including with other \*Arr Apps that have had this longer - you've described has been seen it has without a doubt a config issue.  Either there are invalid config settings (typically SSL) or the user has multiple attribute entries has perviously described and thus is without a doubt a support issue.
