### ISSUE TITLE
Feature Request: Manual Magnet Link Input on Radarr's Search Page

### ISSUE THREAD

**Issue by xr4t3d** [Radarr/Radarr#9355]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

**Summary**:
Introduce the ability to manually input torrent magnet links on the "Search" page during indexer searches in Radarr.

**Description**:
While Radarr effectively automates movie downloads from various indexers, there are instances where users may want to provide a specific torrent magnet link directly. This feature would enable users to input a magnet link manually on the Search page when searching through indexers. This can be particularly useful in scenarios where Radarr might not automatically find a desired version of a movie, or when a user already has a preferred source.

**Proposed Implementation**:
- Add a new input field on the "Search" page within the UI.
- This field should accept valid magnet links.
- Once a magnet link is inputted and submitted, Radarr would treat it like any other search result, handling the download and subsequent file management.

**Benefits**:
- Provides greater flexibility and control to users in sourcing their media.
- Enhances the utility of Radarr in scenarios where automated searches might not yield the desired results.
- Increases user satisfaction by accommodating a wider range of use cases.

This feature would significantly enhance Radarr’s functionality, catering to a broader range of user preferences and scenarios.

### Describe the solution you'd like

n/a

### Describe alternatives you've considered

n/a

### Anything else?

Nothing else. Thanks!

**Comment by bakerboy448** [comment]
You can simply add the release to your client in radarr's category
