### ISSUE TITLE
Locked out of account

### ISSUE THREAD

**Issue by ckat90** [Radarr/Radarr#9356]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I have the app nzb360 that I use in my network to add movies and TV shows. The app recently had me set a username and password that I seem to have forgotten. I have tried changING the config file but then radarr doesn't open without giving me an error. 

### Expected Behavior

have the username/password removed so I can access on my computer 

### Environment

```markdown
- OS: windows 10
- Radarr: 5.0.3.8127
- Docker Install: 
- Using Reverse Proxy: 
- Browser: chrome
- Database:
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

i get a corrupt database error

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
> i get a corrupt database error

are not valid trace logs nor reflect the steps on the wiki you checked as acknowledging you followed.

--— 

https://wiki.servarr.com/radarr/faq#i-am-getting-an-error-database-disk-image-is-malformed
