### ISSUE TITLE
Unable to connect to indexer when using Cardigann

### ISSUE THREAD

**Issue by RoldGold25** [Radarr/Radarr#936]
I can't add any indexers that are proxied through Cardigann. Interestingly these same Cardigann indexers work fine in Sonarr. When I try to add them I get the following errors in the logs:

NzbDroneErrorPipeline
`Invalid request Validation failed: 
 -- Unable to connect to indexer, check the log for more details`

Torznab
`Unable to connect to indexer: Sequence contains no elements`
`System.InvalidOperationException: Sequence contains no elements
  at System.Linq.Enumerable.First[TSource] (IEnumerable`1 source) <0x41e12ad0 + 0x0013f> in <filename unknown>:0 
  at NzbDrone.Core.Indexers.HttpIndexerBase`1[TSettings].TestConnection () [0x0000e] in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:325 `

Radarr Version: nightly 0.2.0.373

**Comment by onedr0p** [comment]
Cardigann isn't support until they fix their API, it is on their end.. not ours.

**Comment by RoldGold25** [comment]
Gotcha. Any idea why it works with Sonarr and not Radarr?

**Comment by onedr0p** [comment]
Yes because sonarr is for tv searching which they allow and radarr is for movie searching which they don't allow.

**Comment by RoldGold25** [comment]
Very interesting, thank you!
