### ISSUE TITLE
create language priority with default

### ISSUE THREAD

**Issue by nekotome** [Radarr/Radarr#9363]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Currently the media profile only sets one preferred language.  In cases where multiple foreign films are under the same profile it would be nice to create a language priority.  For instance, 1-English, 2-Multi, 3-Any.  This prevents the user from having to maintain multiple profiles, one for each language.

### Describe the solution you'd like

 In cases where multiple foreign films are under the same profile it would be nice to create a language priority.  For instance, 1-English, 2-Multi, 3-Any

### Describe alternatives you've considered

Creating a profile per language, it does work but i.s a bit cumbersome

### Anything else?

N/A

**Comment by bakerboy448** [comment]
This can already be done with custom formats
