### ISSUE TITLE
Deluge additional setting options

### ISSUE THREAD

**Issue by Daedalus911** [Radarr/Radarr#9364]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Deluge instance has 1 download default location, some setups preclude the ability to have all files on one drive/share, due to various pool setups, network interfaces etc. This issue is conflated if using multiple instances of sonarr as well because TV, anime and movies would be in the same drive/folder/pool setups preventing an easy way to get plex to separate the 3 genres.

### Describe the solution you'd like

Deluge supports download locations and move-on complete locations, as well as automanage settings. it would be nice if this could be utilized to help with downloading to specific drives or to move completed torrents to other drives to allow for permanent seeding. as well as the ability to disable the link feature that Radarr uses. 

### Describe alternatives you've considered

I have considered just rebuilding my NAS server set up to make this work however i already have over 50TB of files on separate pools which would result in massive data loss. 

### Anything else?

![image](https://github.com/Radarr/Radarr/assets/1811283/abf8af22-34be-4941-b790-909632e05fdb)

**Comment by bakerboy448** [comment]
- deluge controls where it downloads files to not radarr

> as well as the ability to disable the link feature that Radarr uses.

no plans to allow radarr to have the download folder and root folder as the same. One should not and generally cannot seed from their library folder.

if radarr cannot hardlink then imports will be copies
