### ISSUE TITLE
Radarr Regex path Config not working

### ISSUE THREAD

**Issue by rstuhlmuller** [Radarr/Radarr#9368]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Access denied to path because of the ' ' (space) character in between the movie title and the year. 

I have the 'Movie File Format' set to `{Movie_CleanTitle}_{Release Year}` and this setting turned on for my indexer. 

<img width="603" alt="Screenshot 2023-11-05 at 8 59 34 PM" src="https://github.com/Radarr/Radarr/assets/57728706/8e854c39-0066-4648-b9c7-8a52d2eda5e4">

Yet still seeing this issue.

### Expected Behavior

I want to be able to set the path to something with no spaces so that my NAS can handle the file path.

### Environment

```markdown
- OS: casaos (debian linux docker image)
- Radarr: 4.7.5.7809
- Docker Install: yes, linuxserver/radarr:4.7.5
- Using Reverse Proxy: No
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

```
[v4.7.5.7809] System.UnauthorizedAccessException: Access to the path '/movies/Office_Space (1999)' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at NzbDrone.Common.Disk.DiskProviderBase.CreateFolder(String path) in ./Radarr.Common/Disk/DiskProviderBase.cs:line 193
   at NzbDrone.Core.MediaFiles.DiskScanService.Scan(Movie movie) in ./Radarr.Core/MediaFiles/DiskScanService.cs:line 114
   at NzbDrone.Core.Movies.RefreshMovieService.RescanMovie(Movie movie, Boolean isNew, CommandTrigger trigger) in ./Radarr.Core/Movies/RefreshMovieService.cs:line 200
```

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
The indexer search setting has no relation to file naming or file organization

**Comment by thezoggy** [comment]
a space is not an invalid character for file systems.. and if it was every movie in the world would just not work for everyone, you wouldnt be the first one to magically stumble across it affter all these years.

if you really feel it is you would need to provide a lot more details about your setup like what /movies is (file system / try doing it manually via cli and see if it works or not). generically it just looks like what the error says.. radarr doesnt have permission. which is a bit different than it couldnt create it.

**Comment by bakerboy448** [comment]
Feel free to reopen when you can provide the required logs and on a current radarr version (v5)
