### ISSUE TITLE
Remotely move from downloaded to movie folder

### ISSUE THREAD

**Issue by lmerega** [Radarr/Radarr#9369]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Hallo, I cannot find this feature and it is very strange.
Both download and movies file are on the same remote server.
After finishing download, the move process is extremely slow, since it is done via NFS.
Is there a way to accelerate it?

### Describe the solution you'd like

It would be useful a script to login via ssh on the remote server and move the file.

### Describe alternatives you've considered

An FTP server or something else automated.

### Anything else?

Nothing

**Comment by bakerboy448** [comment]
> It would be useful a script to login via ssh on the remote server and move the file.

import via a script functionality exists
