### ISSUE TITLE
Newztown can not be reached

### ISSUE THREAD

**Issue by diedrichg** [Radarr/Radarr#939]
**Description:**

Newztown.co.za (Newznab indexer) can not be reached. Settings are identical to Sonarr and Sonarr can connect to it just fine. 

**Radarr Version:**
0.2.0.375

**Logs:**

17-2-27 22:12:38.6|Warn|Newznab|Unable to connect to indexer

[v0.2.0.375] System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.TestConnection() in C:\projects\radarr-usby1\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 324

17-2-27 22:12:39.0|Warn|NzbDroneErrorPipeline|Invalid request Validation failed: 
 -- Unable to connect to indexer, check the log for more details

**Comment by onedr0p** [comment]
Contact the staff and have them enable movie search.

`<movie-search available="yes" supportedParams="q,imdbid"/>`

That needs to be in the caps endpoint. You can refer them to this post of you wish, they'll understand what I mean.
