### ISSUE TITLE
Filter: Language on disk

### ISSUE THREAD

**Issue by DjRicko** [Radarr/Radarr#9398]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

As a user of multi language support, it would be really great to be able to make a filter based on language in the files on disk, just like you can filter by original language etc.
Say i have How to train a dragon series,
i would prefer to have them with both danish and english audio.
I could then make a filter to show any that are missing those 2 languages etc.

### Describe alternatives you've considered

Not really any alternatives.

### Anything else?

No

**Comment by bakerboy448** [comment]
Filters are for movie properties not movie file properties

**Comment by adfgdsgd** [comment]
It would be really nice to have a way to filter on file properties, such as languages and/or custom formats

I currently have mixed languages in the same profile and want to separate them. There is no way for me to know/filter what language is downloaded from the movie list, i need to enter the detail page of a movie

I am willing to work on this but I am knowledgeable enough only for the backend work, I would need someone else to work in react

Let me know if this is something you would likely merge or you just don't like the idea
