### ISSUE TITLE
Remove Series / Season / Episode from Import, replace with "Movie Title(Year)"?

### ISSUE THREAD

**Issue by evulhotdog** [Radarr/Radarr#94]
![image](https://cloud.githubusercontent.com/assets/365456/21808969/abc2c1fc-d713-11e6-86d9-f16f5448f0d1.png)

**Comment by Fossil01** [comment]
Maybe replace on of the columns with the postdate of the release on Usenet.

**Comment by fedoranimus** [comment]
Fixed by #133.
