### ISSUE TITLE
Be able to put a log level of warn or error

### ISSUE THREAD

**Issue by Brawdunoir** [Radarr/Radarr#9406]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Radarr does a lot of write operations on disk. On 6 days it has written 18GB of data on my SSD. My guess is that the vast majority of the writes operations are coming from the logs.

### Describe the solution you'd like

Be able to put the log level of our Radarr instance to WARN and ERROR in addition of the INFO, DEBUG and TRACE.

### Describe alternatives you've considered

Looking for other reasons why Radarr would write that much on disk.

### Anything else?

I feel like these log levels should be available to select on the UI.

Nonetheless, as a power user, I don't mind editing the xml config file or looking inside the documentation to make some tweaks. It's a shame that right now, even this option is not possible by the code.

I'd be happy to contribute on a PR.

**Comment by bakerboy448** [comment]
closing; x-y problem

Please use [Discord](https://radarr.video/discord) for support/questions.

Info logs would be 51 \* 1mb  of rotating data. It is highly unlikely that log files account for your significant numerous gigabytes of data.

you should be able to set the log level via the config file; no plans for quieter log level user selectable in the UI.  Non-info logs would make debugging effectively impossible
