### ISSUE TITLE
Indexer can't find titles with ampersand(&)

### ISSUE THREAD

**Issue by thejacer87** [Radarr/Radarr#941]
**Description:**

Not returning results for movies with ampersand in the title. I went to my trackers and could find releases manually. Granted, at least for Bill & Ted, the torrent name was Bill.and.Ted... Love & Friendship torrent had the ampersand though... so I dunno

**Radarr Version:**
0.2.0.375

**Mono Version:**
4.8.0

**Logs:**
```
17-2-27 22:37:44.1|Info|NzbSearchService|Searching 3 indexers for [Bill & Ted's Bogus Journey]
17-2-27 22:38:01.7|Info|NzbSearchService|Searching 3 indexers for [Love & Friendship]
17-2-27 22:38:02.4|Info|DownloadDecisionMaker|Processing 33 releases
17-2-27 22:38:08.6|Info|DownloadDecisionMaker|No results found
17-2-27 22:38:39.5|Info|DownloadDecisionMaker|No results found
17-2-27 22:38:45.9|Info|NzbSearchService|Searching 3 indexers for [The Matrix]
17-2-27 22:39:24.4|Info|DownloadDecisionMaker|Processing 17 releases
17-2-27 22:44:51.3|Info|HousekeepingService|Running housecleaning tasks
17-2-27 22:44:52.1|Info|Database|Vacuuming Log database
17-2-27 22:44:52.9|Info|Database|Log database compressed
17-2-27 22:44:52.9|Info|Database|Vacuuming Main database
17-2-27 22:44:53.6|Info|Database|Main database compressed
17-2-27 22:53:19.6|Info|Database|Vacuuming Log database
17-2-27 22:53:19.7|Info|Database|Log database compressed
17-2-27 22:53:28.5|Info|NzbSearchService|Searching 3 indexers for [Bill & Ted's Bogus Journey]
17-2-27 22:53:55.4|Info|DownloadDecisionMaker|No results found
```

**Comment by hotio** [comment]
Does manual search give any results? I get results back with `and` and `&amp;`.

**Comment by thejacer87** [comment]
what manual search? i just click the icon to do a manual search ya

![image](https://cloud.githubusercontent.com/assets/6412919/23488622/af3eb55a-fea2-11e6-844f-2908d9ed0c25.png)

**Comment by hotio** [comment]
Are you using jackett? Or direct? Which tracker?

**Comment by thejacer87** [comment]
jackett

**Comment by onedr0p** [comment]
Let me know if this is still not working on the latest release, thanks.

**Comment by thejacer87** [comment]
still no results found, i tried:

Love & Friendship
Bill & Ted's Excellent Adventure
Bill & Ted's Bogus Journey
