### ISSUE TITLE
Radaar alternative titles is missing lots of alternative titles (TMDB)

### ISSUE THREAD

**Issue by Mrpink200** [Radarr/Radarr#9443]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Hello. 
After trying to understand why radarr was not able to match multiple French titles of english movies, i have discovered that Radarr is looking for alternative titles by matching TMDB alternatives titles only.
It appears that this behaviour is missing lots of alternatives titles that are documented in TMDB

Example: It's a Wonderfull Life (1946)

TMDB alternatives titles : 12 (https://www.themoviedb.org/movie/1585-it-s-a-wonderful-life/titles?language=fr-FR)
TMDB translation titles : 41 (https://www.themoviedb.org/movie/1585-it-s-a-wonderful-life/translations?language=fr-FR)
it could be great if radarr could lookup both fields to improve a lot the search.

### Expected Behavior

Lookup alternative title and translation titles

### Steps To Reproduce

you can test it with "it's a wonderful life"

### Environment

```markdown
Version     5.2.3.8290
Version du paquet     5.2.3.8290-ls95 by linuxserver.io
.NET     Yes (6.0.21)
Docker     Yes
Migration de la base de données     233
Base de données     Sqlite 3.41.2
Dossier AppData     /config
Répertoire de démarrage     /app/radarr/bin
Mode     Console



### What branch are you running?

Master

### Trace Logs? **Not Optional**

Not a code issue but behaviour issue


### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
https://wiki.servarr.com/radarr/faq#text-searches

**Comment by Mrpink200** [comment]
hello @bakerboy448 ; many thx fo answering; what i do not get in the behaviour, despite the explantion is that 👍 $if i had a french missing translated title in TMDB, the search in radarr then works. that is the reason why i thought it was liked to this tmdb field. if it is not the case, i m a bit lost :s
