### ISSUE TITLE
Advanced Transcoding Integration for Plex Library Management with Emphasis on AV1 Format

### ISSUE THREAD

**Issue by martinkeat** [Radarr/Radarr#9448]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Annoyance of radarr moving stuff before transcoding. 

#### **Summary**
This proposal introduces enhancements for Tdarr, Radarr, and Sonarr, aimed at improving integration and management of media files for Plex, with a special focus on the transcoding process and efficient library updates. The adoption of the AV1 format by Plex serves as a primary trigger for this proposal.

---

#### **Detailed Features**

**On Tdarr's Side:**

1. **Source Directory Enhancement:**
   - Implement an option under the "source" directory in Tdarr's interface.
   - Indicate the inclusion of a Plex 'tbp/' folder and a '.plexignore' file.
   - Set `/[root folder]/` as the source, with Tdarr processing files in `/[root_folder]/tbp`, and moving them to `/[root folder]/` after transcoding.

2. **AV1 Plugin Addition:**
   - Introduce a specific AV1 plugin to Tdarr, simplifying the transcoding process for users and embracing the latest video encoding standards.

---

**On Radarr/Sonarr's Side:**

3. **New 'Transcoding' Tab in Settings:**
   - Add a "Transcoding" tab within the Settings menu of Radarr and Sonarr, focusing on streamlined transcoding workflows.

4. **Transcoding Settings Page Enhancements:**
   - Feature a tickbox for creating a 'tbp' folder and a '.plexignore' file in the root directory.
   - Facilitate the handling of files destined for transcoding and protect against misclassification by Radarr and Sonarr.

5. **Integrated Workflow and Automation:**
   - Configure Radarr and Sonarr to recognize `/[root folder]/tbp` as a temporary storage for files awaiting Tdarr transcoding.
   - Ensure these systems update their libraries to reflect file presence in both directories, and automate Plex library updates post-transcoding.

---

#### **Collaboration and Flexibility:**

- The enhancements proposed can be independently implemented by Tdarr, Radarr, or Sonarr. 
- Even if only one party adopts these changes, the new setup will still offer benefits and can be utilized effectively.
- However, as part of a collaborative community, synchronized adoption would greatly enhance user experience and operational efficiency.

#### **Benefits:**
- Provides a more streamlined process for managing and transcoding media files, especially with the AV1 format.
- Reduces manual intervention and error in media file handling.
- Enhances user experience through a unified, automated workflow.

---

### Describe alternatives you've considered

Many, but by far this is the simplest. 

### Anything else?

Nope

**Comment by bakerboy448** [comment]
- no plans
- Import via custom script exists; use that for any custom import needs

**Comment by martinkeat** [comment]
Hi Bakerboy. 

I am aware of its existence, but a simple tick box that creates a subdirectory /tbp in the root directory and a .plexignore file with its only text being "tbp/" would be, i think a great enhancement for the less tech savy, especially if it enabled havagitgat to make an equally simple tick box on tdarr which allows the two to work together. Would also enhance Radarr substantively for users knowing that the second a file is added it goes straight for transcoding. 

Martin

**Comment by bakerboy448** [comment]
Which requires a complete rewrite of the import process for 0.001% of users that this use case applies for.

again, import via custom script is the solution for this

**Comment by martinkeat** [comment]
Ok, a bit of an obtuse response. That's a real shame. 

But just to clarify. How exactly does it require a full re-write of the import process. Surely if the tbp (to be processed) directory is being created as a second root directory and the downloader is set to deposit said files there, radarr knows the files exist because it can see them. Then when Tdarr moves them, on the next refresh radarr is going to see that it is not in the /tbp folder anymore, it's in the root directory?

Of course, you could look at it another way, less user adoption because it doesn't already exist. Not everyone has the mindset (or indeed is medically well enough) to be able to implement custom scripting.

**Comment by RobinDadswell** [comment]
> Surely if the tbp (to be processed) directory is being created as a second root directory and the downloader is set to deposit said files there, radarr knows the files exist because it can see them. Then when Tdarr moves them, on the next refresh radarr is going to see that it is not in the /tbp folder anymore, it's in the root directory?

Radarr should not have a root folder that is having things moved into directly by the download tool. 

Ultimately we as a team believe you should download the right quality in the first place and not need to transcode and as such don't intend on changing the process from this. As baker has mentioned custom import scripts can be utilised to process movie files in ways outside of the standard methodology within the tool

**Comment by martinkeat** [comment]
Well, thats a shame. But I noticed you closed the feature request before any of the community got the opportunity to comment. That's kind of telling.
