### ISSUE TITLE
Use TAGs to specify saving folder

### ISSUE THREAD

**Issue by Patatra** [Radarr/Radarr#9453]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I'd like to have two libraries on plex, one for movies, one for animes. We can use auto tagging for new content to specify if it's a movie or an anime using `genre` condition but there's no way to use that to choose the saving folder

### Describe the solution you'd like

Add an option to specify saving folder depending on tag, in `Settings` - `Media Management`

### Describe alternatives you've considered

We can choose the root folder when adding a movie, but having users asking throw Overseer, they often forgot to change  and can't find their content till I manually move it. Making it automatic by using autotagging would be perfect

### Anything else?

Nope. Merci! Thank you!

**Comment by bakerboy448** [comment]
- No plans
- Likely dupe
- Your request app should handle facilitating selecting the correct folder

**Comment by Patatra** [comment]
Well, I wrote a python script triggered on import via a custom script connection and autotagging Animations movies to handle that automatically through radarr API, thanks
