### ISSUE TITLE
Search for 'Doctor' failed. Unable to communicate with TMDb.

### ISSUE THREAD

**Issue by tornado909** [Radarr/Radarr#9460]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Can`t connect to IMDB

### Expected Behavior

My films

### Environment

```markdown
- OS: Windows 11
- Radarr: 
- Docker Install: 
- Using Reverse Proxy: 
- Browser: 
- Database:
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

Aaa?

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by tornado909** [comment]
> :wave: @tornado909, we use the issue tracker exclusively for bug reports and feature requests. However, this issue appears to be a support request. Please hop over onto our [Discord](https://radarr.video/discord).

![Screenshot_20231204-222303.jpg](https://github.com/Radarr/Radarr/assets/65523887/e0f3fff9-2376-479f-8e48-5e9b186240e2)

**Comment by bakerboy448** [comment]
-IMDb is not used
- Servarr proxies tmdb 
- your ip per maxmind is Belarus or russia

**Comment by tornado909** [comment]
> - IMDb is not used
> - Servarr proxies tmdb 
> - your ip per maxmind is Belarus or russia
> - Not a bug at all

Then, it's not free and open software. Why Russia up is blocked? What reason?

**Comment by bakerboy448** [comment]
The Servarr Team made the decision to block access for IPs associated by Maxmind (Cloudflare's geo-database provider) located within Belarus and Russia at the start of the Ukraine war. This will not be changed.

The software is still by [definition FOSS](https://ssd.eff.org/glossary/open-source-software).

> Open source software, or [free software ](https://ssd.eff.org/glossary/open-source-software), is software that can be distributed freely in a form that lets others modify it and rebuild it from scratch.

**Comment by tornado909** [comment]
> The Servarr Team made the decision to block access for IPs associated by Maxmind (Cloudflare's geo-database provider) located within Belarus and Russia at the start of / as a result of the Ukraine war. This will not be changed.
> 
> The software is still by [definition FOSS](https://ssd.eff.org/glossary/open-source-software).
> 
> > Open source software, or [free software ](https://ssd.eff.org/glossary/open-source-software), is software that can be distributed freely in a form that lets others modify it and rebuild it from scratch.

But why block Russia? Ukraine start this war in 2014. Russia is just defending itself. Block Ukraine if you think that blocking will help the war.
