### ISSUE TITLE
Show whether file is NZB or Torrent in activity tab

### ISSUE THREAD

**Issue by Fluff663** [Radarr/Radarr#9462]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

New collum under activity tab to differentiate between NZBs and Torrents

### Describe alternatives you've considered

Show whether it is a NZB or Torrent when removing it in radarr

### Anything else?

No

**Comment by bakerboy448** [comment]
Protocol Exists
