### ISSUE TITLE
Issue with Search Tab in Chrome on Android Smartphone

### ISSUE THREAD

**Issue by ninidas** [Radarr/Radarr#9466]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I'm experiencing a consistent issue with the search tab when using Chrome on my Android smartphone. Each time I begin scrolling down in the search tab, the left panel automatically opens. Once this happens, I'm unable to close the panel, forcing me to refresh the page to regain functionality.

This problem is specific to when I scroll down on the search tab and occurs every time. Notably, this issue is only present in Radarr and does not happen in Sonarr. Additionally, the problem does not occur when I use the Firefox browser on my smartphone. I have also confirmed that my browser is not in "desktop mode."

See the screen below : 
![Screenshot_2023-12-06-20-45-43-77_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Radarr/Radarr/assets/51442132/9e65fedc-3a09-42f3-9428-1d648c880da9)

### Expected Behavior

Navigate to a specific movie and initiate a search. Begin scrolling down to review and select the movie from the available releases.

### Steps To Reproduce

1. On an Android smartphone, open the Chrome web browser.
2. Enter the URL to access Radarr.
3. Choose a movie from the list.
4. Initiate a search for the selected movie.
5. Begin scrolling down.

### Environment

```markdown
- OS: Ubuntu 22.04 
- Radarr: 5.1.3.8246
- Docker Install: yes
- Using Reverse Proxy: yes (SWAG)
- Browser: Chrome
- Database: N/A
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

![Screenshot_2023-12-06-20-45-43-77_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Radarr/Radarr/assets/51442132/eb16e6f0-783d-4fef-b9c2-8b38eb69c876)

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by Kakoen** [comment]
Same issue here. Huge annoyance, blocking you from using the search functionality on a phone. Hope it gets fixed soon. Can only add that I've had this issue for a longer while, not a recently introduced bug.

**Comment by Qstick** [comment]
Indeed this is all changed now
