### ISSUE TITLE
Radarr stops copying downloaded videos prior to the coping being complete, leading to videos that suddenly stop while watching them.

### ISSUE THREAD

**Issue by lightmaster** [Radarr/Radarr#9479]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When Radarr copies a file from my download folder to my movies folder, it stops copying before the file is complete. For example, when it tried to copy a 1.9GB file, it stopped around 760MB. The movie initially disappeared from the Activity page, but then showed up again saying "Failed to import movie, Destiation already exists." When I told it to manually import the movie again, it did the same thing, but stopped at a slightly different file size, but still far from complete. I was able to use the `cp` from a shell to copy the file as expected.

### Expected Behavior

Radarr should successfully copy files from the Downloads folder to the Movies folder without issue and without prematurely stopping the copy.

### Steps To Reproduce

1. Have Radarr initiate a download and wait for the download to complete
2. Refresh the movie's folder while watching the file copy and the filesize increase
3. Filesize stops increasing at some point and Radarr now shows the movie in the activity's tab, saying that it failed to import the movie.

### Environment

```markdown
- OS: Debian 12
- Radarr: 5.1.3.8246
- Docker Install: No
- Using Reverse Proxy: Yes
- Browser: Unrelated, but using Firefox 121
- Database: Postgresql 15.5
- Files stored on Synology DS1621+, accessed via a NFS share.
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

[radarr.debug.txt](https://github.com/Radarr/Radarr/files/13655662/radarr.debug.txt)
[radarr.trace.txt](https://github.com/Radarr/Radarr/files/13655663/radarr.trace.txt)

deleted files from failed copies
![deleted files from failed copies](https://github.com/Radarr/Radarr/assets/5307827/c4dd384a-cbd2-4496-9d2a-631dc738450a)

Correct filesize after manually copying from shell
![Correct filesize after manually copying from shell](https://github.com/Radarr/Radarr/assets/5307827/c4325d6f-3af2-4d9b-98d3-9481de73f6df)

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
- missing nolock on the nfs mount (faq/troubleshooting/docs cover this)?
- Not a radarr bug that the file system says the file already exist and the file system or mount is resulting in partial incomplete copies.  Radarr simply is using native dotnet system calls for the file movement

**Comment by lightmaster** [comment]
>     * Not a radarr bug that the file system says the file already exist and the file system or mount is resulting in partial incomplete copies.  Radarr simply is using native dotnet system calls for the file movement

It looks like Radarr is attempting to copy the file, for some reason the file isn't copied completely, the movie is removed from the activity page, then Radarr notices that the copy wasn't successful and the files don't match so it shows back up in the activities page again as radar attempts to copy it again and this time says that the file already exists.

**Comment by bakerboy448** [comment]
> It looks like Radarr is attempting to copy the file, for some reason the file isn't copied completely

again, not a radarr issue/bug as it's just using system file calls. It's your system / environment / file system / network is what's causing the partial copy

**Comment by lightmaster** [comment]
Yup. I posted to the Discord group and they helped me get straightened out. Thanks.
