### ISSUE TITLE
Movie is physically missing from disk but shows Status downloaded

### ISSUE THREAD

**Issue by mow4cash** [Radarr/Radarr#948]
**Description:**
The movie shows the Status 'Downloaded' however when I go to the file path the folder and movie does not exists. Should it be displaying 'Missing' instead?

**Radarr Version:**
0.2.0.415

**Comment by geogolem** [comment]
If you click the refresh (update Movie Info and scan disk) does it change from downloaded to missing?

**Comment by mow4cash** [comment]
No, I just tried it again.

**Comment by scope999** [comment]
Hi I am having this problem too. Would it be possible for it to be labelled "missing from disk" like Sonarr? Then they could be filtered in the movie editor and deleted? Or even just deleted from the list if there is no longer a file?

**Comment by geogolem** [comment]
can you try with the latest version.. and if you still have the problem I will try to reproduce and find out whats going on.

**Comment by scope999** [comment]
Thanks, latest version 0.2.0.453, movie folder removed from directory, ran task "update movie info and scan disk" and the movie remained downloaded.

**Comment by geogolem** [comment]
I havent looked into this yet, but I will try to reproduce it and report my findings back here...

**Comment by tro-co** [comment]
Moved some movies to another drive.  Radarr still shows they are "downloaded" with original folder path.  Added new folder location, import could not fix/update existing movie locations (duplicates). Tried "update movie info and scan disk" after adding new folder location, didn't work.  "Update Library" also yielded no resolve.   No option to mass remove movies from list to re-import.  Please advise :)

**Comment by underwnm** [comment]
I have this same problem. It shows that the movie is completely downloaded but shows missing from disk. It didn't rename or hard link and can't find the file location if you search. I ran updates and scanning. Radarr Ver. 0.2.0.453

**Comment by razlebol** [comment]
I have the same issue. Even if I "delete" the file in Radarr, it goes back to downloaded after.


NzbDroneErrorPipeline | Request Failed: File doesn't exist: \\N5550\Media\movies\400 Days (2015)\400 Days (2015) Bluray-1080p x264 AC3[FR+EN] [FR].mkv | 8:31am
-- | -- | --
  | RecycleBinProvider | Unable to move '\\N5550\Media\movies\400 Days (2015)\400 Days (2015) Bluray-1080p x264 AC3[FR+EN] [FR].mkv' to the recycling bin: '\\N5550\downloads\recycle\400 Days (2015) Bluray-1080p x264 AC3[FR+EN] [FR].mkv': File doesn't exist: \\N5550\Media\movies\400 Days (2015)\400 Days (2015) Bluray-1080p x264 AC3[FR+EN] [FR].mkv | 8:31am
  | MovieFileModule | Deleting movie file: \\N5550\Media\movies\400 Days (2015)\400 Days (2015) Bluray-1080p x264 AC3[FR+EN] [FR].mkv

**Comment by douglas24** [comment]
Having the same problem. Files are physically missing but Radarr still showing them as downloaded despite disk scans.

**Comment by HinksUK** [comment]
Same issue here as well. When you click into the individual movie it lists the file as on the drive but missing on the main page.

**Comment by marx1** [comment]
Having this issue as well. It's a game breaker for me as I lost my storage, and the movie list is in radarr, but I can't get it to download again.

**Comment by galli-leo** [comment]
@marx1 @HinksUK It only shows as missing on the main page if you sort by downloaded.
