### ISSUE TITLE
Option to move instead of copy

### ISSUE THREAD

**Issue by alpinewinter** [Radarr/Radarr#949]
I would like the ability to have Radarr move the completed file, instead of copying and leaving the original.

In my use case, I have a remote download client. Finished downloads are copied to a directory that is synchronized across the network to a folder that Radarr watches. The original file does not need to stay in that directory for the client to continue seeding, since it has it's own local copy.

This might be an edge case, but it would be a nice feature to have.

**Comment by onedr0p** [comment]
You can use the Custom script in Connection in settings to do this for you, no?

**Comment by onedr0p** [comment]
Closing. You can use the above to accomplish what you wish. Good luck!
