### ISSUE TITLE
Radarr wont restart after update on Fedora

### ISSUE THREAD

**Issue by Arathen** [Radarr/Radarr#9493]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Im running nightly and using the built-in updater on Fedora 39. As of `Radarr.develop.5.2.5.8330.linux-core-x64.tar.gz` Radarr has not been able to start after the update is applied.
The fix is to restore the SELinux execution permissions on the Radarr binary by running `restorecon /path/to/Radarr` as root.
Im also running Sonarr, Lidarr and Prowlarr on the same box, and so far none of them exhibit the same issue.

### Expected Behavior

Radarr should start after an update.

### Steps To Reproduce

1. Have an update available.
2. Apply update using built-in updater mechanism.

### Environment

```markdown
- OS: Fedora 39 (headless server)
- Radarr: 5.2.5.8353
- Docker Install: No
- Using Reverse Proxy: Yes, but irrelevant
- Browser: Not related
- Database: Sqlite 3.42.0
```

### What branch are you running?

Nightly

### Trace Logs? **Not Optional**

Trace logs just show a normal, healthy update/restart sequence, but systemd logs provide more info:

```
(Radarr)[154139]: radarr.service: Failed to locate executable /opt/radarr/radarr/Radarr: Permission denied
(Radarr)[154139]: radarr.service: Failed at step EXEC spawning /opt/radarr/radarr/Radarr: Permission denied
systemd[1]: radarr.service: Main process exited, code=exited, status=203/EXEC
systemd[1]: radarr.service: Failed with result 'exit-code'.
```

And the SELinux audit log also shows:

`type=AVC msg=audit(1702612285.200:5057): avc:  denied  { execute } for  pid=61274 comm="(Radarr)" name="Radarr" dev="dm-0" ino=27912 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:user_tmp_t:s0 tclass=file permissive=0`

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by fryfrog** [comment]
Its probably worth commenting here, we don't get a lot of hits for "selinux". If the "fix" is running something as `root`, then sonarr/radarr couldn't do it because it would be *crazy* to run them as `root` or give them access to doing something like that. Why even bother w/ selinux if you give them the power to `root` your system?

**Comment by Arathen** [comment]
You're absolutely right. My mistake. You do not need to run it as root after all. That was my sudo autopilot kicking in. The fix can be run as the user who owns the Radarr binary/directory.

To add a little more "context" to this, the following SELinux permissions are what happens before/after a built-in update.

Before:
`-rwxr-xr-x. 1 radarr radarr system_u:object_r:usr_t:s0 142840 Dec 16 10:56 Radarr`

After:
`-rwxr-xr-x. 1 radarr radarr system_u:object_r:user_tmp_t:s0 142840 Dec 16 16:30 Radarr`

At this point, Radarr will not restart, until a restorecon is run as the radarr user, after which we're back to:
`-rwxr-xr-x. 1 radarr radarr system_u:object_r:usr_t:s0 142840 Dec 16 16:30 Radarr`

and the Radarr binary will start again.

I believe this is because the built in updater unpacks the update into /tmp where it inherits the SELinux context from that directory, and that restricted "tmp" context is preserved and not reset when the updated binary is then moved into its final proper location.

To correct myself, root is not needed to fix this. The user who owns the radarr directory/process can fix it with restorecon.

If thats the case, and the built in updater can do this:
`2023-12-16 10:56:42.9|Debug|DiskProvider|Setting permissions: 755 on /tmp/radarr_update/Radarr.Update`

Then my request would be to also please include an SELinux context setting step for distros which it applies to, once the binary is moved to its final location.

Many thanks.
