### ISSUE TITLE
API /api/v3/update Connection Refused

### ISSUE THREAD

**Issue by Feramance** [Radarr/Radarr#9502]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

[update.json](https://github.com/Radarr/Radarr/files/13727397/update.json)
Getting the attached error when trying to get update info using the API

### Expected Behavior

As has been the case, this api call should return the json format show in the API doc

### Steps To Reproduce

go to url: http://RADARR-IP:7878/api/v3/update?apikey=API_KEY

### Environment

```markdown
- OS: Ubuntu 20.04
- Radarr: Radarr 5.2.5.8361
- Docker Install: Yes
- Using Reverse Proxy: No
- Browser: Chrome
- Database: Sqlite 3.41.2
```

### What branch are you running?

Develop

### Trace Logs? **Not Optional**

[radarr.trace.txt](https://github.com/Radarr/Radarr/files/13727434/radarr.trace.txt)

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
- logs not attached
- From the provided text file it appears you placed authelia in front of your API

**Comment by bakerboy448** [comment]
The file you're uploading is still authelia html not the logs

Can do do `nslookup radarr.servarr.com`

**Comment by Feramance** [comment]
![image](https://github.com/Radarr/Radarr/assets/38938175/93e14dab-988d-490a-80e9-b7283b85314a)
That's the nslookup and this is the output of the update API call when connecting directly to the container, outside authelia or reverse proxy or anything.
[update.json](https://github.com/Radarr/Radarr/files/13731231/update.json)

**Comment by bakerboy448** [comment]
Support issue. Not a radarr bug.

Your DNS is returning an invalid IP.
