### ISSUE TITLE
Sub Collections and Sorting

### ISSUE THREAD

**Issue by PapaTrotzki** [Radarr/Radarr#9503]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I've searched a few 'issues' and many were similar but not quite what I was looking for. I've found some of the collection behaviour to be odd, particularly with larger franchises. I don't like that all my MCU collections are split apart or that the Wolverine and Deadpool collections aren't part of the X-men collection or that Rogue One and Solo are left out of the Star Wars collection. I think I understand why this decision was made which is why I've come up with the solution I have.

Also, a minor tangentially related thing that's not really big enough for it's own issue: the main library page I'd like to be able to sort by collections, my brain instinctively assumes Logan should be sorted with the other wolverine movies despite knowing that it's alphabetically wrong, I tried to sort by Studio but I ended with the Deadpool films separated as they've been made with 3 separate studios (including Deadpool 3).

### Describe the solution you'd like

To solve my primary issue, I am proposing sub-collections. Most films will be their own collection as just a trilogy. With larger franchises the sorting should use sub-collections, for example you could have a MCU collection which groups together all the MCU movies, than inside that you have sub collections for the Iron Man collection and avengers collection and etc.

### Describe alternatives you've considered

Another way I believe this could be solved with is allowing the manual creation/editing of collections. A possible solution could also be an ability to link Jellyfin which already has this feature. 

I did attempt to use folders to achieve this but it didn't seem to change anything with the collections, although maybe I did it wrong.

### Anything else?

Thank you for reading, I hope this comes to a satisfying solution or I find an alternative solution to my issue.

**Comment by bakerboy448** [comment]
> MCU collections are split apart or that the Wolverine and Deadpool collections aren't part of the X-men collection or that Rogue One and Solo are left out of the Star Wars collection

Collection info comes from tmdb not radarr. Nothing to do with radarr here

no plans for end user collection created....this can largely be done with custom filters

**Comment by PapaTrotzki** [comment]
Alright, well thank you for the response. I did take a look at lists and custom lists after your comment and I think I see a way to make it sort of work though it's not quite what I was looking for.
