### ISSUE TITLE
link to imdb alternate editions page

### ISSUE THREAD

**Issue by thezoggy** [Radarr/Radarr#9505]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Provide link to imdb/alternateversions page, `https://www.imdb.com/title/<imdbid>/alternateversions/`

On IMDB there is a page that shows the editions/alternate versions of a movie which is sometimes very useful to know what editions may exist or are best.

examples:
The 40 Year Old Virgin
https://www.imdb.com/title/tt0405422/alternateversions/

Lady and the Tramp
https://www.imdb.com/title/tt0048280/alternateversions/

example with no alt:

Poor Things
https://www.imdb.com/title/tt14230458/alternateversions/

### Describe the solution you'd like

Linking to imdb is already there, all I'm asking is another one to take me straight to the alt page vs me having to manually do it each time.

### Describe alternatives you've considered

none

### Anything else?

none

**Comment by Qstick** [comment]
I sort of agree, this seems redundant. I assume you can use a browser extension to inject this should you really want it.
