### ISSUE TITLE
Delete movie tag on upgrade

### ISSUE THREAD

**Issue by Navino16** [Radarr/Radarr#9506]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I manualy set some tags to my movies for filtering them in radarr but when when radarr download a new realease for a movie my tags can become irrelevant.

### Describe the solution you'd like

I wood like to have an option to delete movie tags on import/upgrade with a setting which should be enabled (for not breaking existing installation).

### Describe alternatives you've considered

I have looked for custom script with some API calls but there is no easy way to delete movie tag.

For doing that with API I have first to get the movie with /api/v3/movie/{id}, get response content and pass it to /api/v3/movie/{id} as PUT request without tags.
So I have to made 2 calls for 1 operation and if something is wrong on the PUT request it will messed up the all movie since it's update every part of it.

### Anything else?

Maybe add a PATCH endpoint to the API to only update the provided attribut.

**Comment by bakerboy448** [comment]
Can you not custom script using https://radarr.video/docs/api/#/MovieEditor ?

**Comment by Qstick** [comment]
Indeed there are a few ways to go about this via the API and custom scripts, no plans to add a setting for this.

**Comment by Navino16** [comment]
Oh didn't see that API call thanks 👍

BTW maybe on the API documentation you can indicate which attributes are mandatory or not inside the body and what append if you don't add them.

For example on /api/v3/movie/editor:
* movieIds is mandatory
* Other attributs are optional
* If you don't add them, current values are keept except for tags, if you don't add this attribut tags will be removed
