### ISSUE TITLE
Multiple bugs with filtering

### ISSUE THREAD

**Issue by SWu** [Radarr/Radarr#952]
On the latest nightly (0.2.0.418), in movie editor the filters at the top right (e.g. filter by missing) don't change the the items in the movie editor list.

Edit:
On new build (0.2.0.422) filters stopped working entirely even in normal movie view, until I toggled the sorting drop down. There's a major bug now with filters in the normal movie view as well: if you select a filter that returns no results (e.g. if all the movies in your list are already in theaters and you filter by announced), you get the default message about "You must be new around here, You should add some movies" and **all filter buttons disappear**. This makes it almost impossible to switch back to a sane view with your movie listings unless you refresh the page and manage to click a different filter fast enough before the buttons disappear.

**Comment by onedr0p** [comment]
We are already aware of this, thanks :)

**Comment by onedr0p** [comment]
Let us know if you have any other problems with the movieeditor, we are all testing it out with the changes @geogolem made.

**Comment by SWu** [comment]
One more minor thing I noticed: the notification message for "Done Saving" doesn't use the normal Radarr notification UI in the lower right, but pops up a plain window in the browser that you need to dismiss by clicking a button.

And a feature request: add min availability and monitored status as columns in the movie editor so that it's easier to see what the current values are.

**Comment by jscottdouglas** [comment]
All filtering does not work for me in the latest nightly, not on the home page or the movie editor

**Comment by geogolem** [comment]
It should be fixed in the latest build now.. please let me know if anything changed for you..

**Comment by adamysu** [comment]
I'm still having issues with this on  0.2.0.535
