### ISSUE TITLE
Collection object within movies endpoint always has an ID of 0

### ISSUE THREAD

**Issue by garwedgess** [Radarr/Radarr#9521]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When calling the movie endpoint - `/api/v3/movie`, the collection object for each movie that is part of a collection always has a collection id of 0.

Example:
```json
"collection": {
      "title": "Halloween Collection",
      "tmdbId": 91361,
      "monitored": false,
      "qualityProfileId": 0,
      "searchOnAdd": false,
      "minimumAvailability": "tba",
      "images": [],
      "added": "0001-01-01T00:01:00Z",
      "tags": [],
      "id": 0
    }
   ```
   
   When calling the collection endpoint - `/api/v3/collection`, the correct collection id is returned:
   
   Example:
   ```json
   {
        "title": "Halloween Collection",
        "sortTitle": "halloween collection",
        "tmdbId": 91361,
        "images": [
            ...
        ],
        "overview": "...",
        "monitored": false,
        "rootFolderPath": "...",
        "qualityProfileId": 1,
        "searchOnAdd": false,
        "minimumAvailability": "announced",
        "movies": [
            ...
        ],
        "missingMovies": 1,
        "tags": [],
        "id": 2
    }
```

### Expected Behavior

The collection id returned in the movie endpoint should match that of the actual collection id

### Environment

```markdown
- OS: DietPi 5.10.103
- Radarr: 5.1.3.8246
- Docker Install: No
- Using Reverse Proxy: No 
- Browser: via postman request
- Database: Sqlite 3.40.1
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

[radarr.trace.txt](https://github.com/Radarr/Radarr/files/13799306/radarr.trace.txt)

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by Qstick** [comment]
The collection object attached to movies is really just meant to be title and tmdbId. pulling the full object with a join will slow the initial load quite a bit. The fix I see here is to have a reduced object for collection on movies so that it only shows those two fields, thus wrong data wouldn't be included. Or we can add an `includeCollection` parameter for that endpoint for the full collection
