### ISSUE TITLE
What it mean PreDB

### ISSUE THREAD

**Issue by rickytin** [Radarr/Radarr#953]
What it mean PreDB in When to consider a movie available.

**Comment by onedr0p** [comment]
PreDB means when the a movie has been added by scene groups.

**Comment by hotio** [comment]
Please note

Quote from @geogolem on Discord
> the minimum availability effects RSS Sync
> preDB measn the same as physical release right now
> but yes, during RSSSync,movies will not be grabbed if they do not meet their minimumAvailability requirements
> so if you put Physical Release/Web  (or preDB for now)... no movies will get grabbed unless the status of the movie is released..

> ya preDB is reated just like physical/Web for now.. but soon, it should be checking preDB
