### ISSUE TITLE
New Download Client: btfs

### ISSUE THREAD

**Issue by OliverOffing** [Radarr/Radarr#9535]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I'm running out of disk space. I'd prefer to watch movies directly while streaming (à la [Popcorn Time](https://github.com/popcorn-official/popcorn-desktop)) rather than having to persist the data to disk (ahead of time).

### Describe the solution you'd like

I'd like to add [btfs](https://github.com/johang/btfs) as a new Download Client. Once Radarr find a torrent and passes it to btfs, the movie would be immediately marked as "Downloaded" (as there's no "pre-downloading" phase). I've tried this process manually with btfs + [jellyfin](https://github.com/jellyfin/jellyfin) and it works well, so the next step would be automating the finding of the torrents which is something Radarr excels at.

### Describe alternatives you've considered

- buying more disk space (I guess that could work but I don't particularly enjoy managing large disk arrays)
- delegating storage to a cloud provider (e.g. Google Drive + `rclone` to mount it as a file system)

### Anything else?

Wanted to check everyone's appetite for this feature. I don't have experience in C# but I'm willing to contribute to the development of it.

**Comment by bakerboy448** [comment]
Upstream: 

> It may be possible to achieve this with the existing blackhole integration, using the read-only option so it hardlinks/copies the file from the "completed" download. No sure if it'd work, but at the moment we're not going to implement a custom solution for this.

https://github.com/Sonarr/Sonarr/issues/5114#issuecomment-1212613735
