### ISSUE TITLE
Integration JustWatch

### ISSUE THREAD

**Issue by Christian-Seiler** [Radarr/Radarr#9558]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Integration with JustWatch

### Describe the solution you'd like

Integration of JustWatch similar to Trakt
Import/Update of Watchlist, watched Movies etc

### Describe alternatives you've considered

API Documentation: https://apis.justwatch.com/docs/

### Anything else?

See also: https://github.com/Sonarr/Sonarr/issues/6306

**Comment by bakerboy448** [comment]
- Duplicate of https://github.com/Radarr/Radarr/issues/3333
- Duplicate of https://github.com/Radarr/Radarr/issues/8698
- Duplicate of https://github.com/Radarr/Radarr/issues/3114

>  I have searched the existing open and closed issues

Please don't check the box to check the box if you don't actually search.

https://github.com/search?q=repo%3ARadarr%2FRadarr+justwatch&type=issues
