### ISSUE TITLE
"ignore deleted moves" function seems broken

### ISSUE THREAD

**Issue by breadcan** [Radarr/Radarr#956]
I have set the "ignore deleted movies" in media management.
Normally my watched movie files are deleted automatically after some days.
I can't find them in the radarr movie list or quick search anymore but they still show up in the wanted list.
When I click on one of them in the wanted list I get a 404 for the movie details screen.

Version is latest nightly.

And if I want to add the movie through add movie function, it says the movie is already added, but still does not show up in movies list.

In wanted - unmonitored filter it shows only 2 movies I removed, but there are more movies with this issue in the full list.

As i read the description I guess it should only remove the monitored status and not the movie itself?

**Comment by breadcan** [comment]
the 404 of the movie details looks unrelated to the ignore movies issue.

**Comment by hotio** [comment]
There has been a bug that's recently fixed, correct behaviour should be that a deleted movie file is set to unmonitored. Perhaps a few of your movies are from before the issue was fixed.

see: https://github.com/Radarr/Radarr/issues/755
