### ISSUE TITLE
Custom automatically tagged Editions (based on custom formats?)

### ISSUE THREAD

**Issue by redexer** [Radarr/Radarr#9561]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Some way of adding your own automatically tagged editions that are synced into the file name (if the file name formatting has editions added) and to Plex.

### Describe the solution you'd like

I am imagining something similar to how custom formats can be added to the filename. I want something that allows me to add editions that are custom for me.
Specific use case for me is Cinema recordings (CAM). I want to be able to see if a movie is CAM or not before choosing to watch it.

### Describe alternatives you've considered

Currently the only alternative ive found is doing it manually.

### Anything else?

Mockup boolean button in custom formatting area:
![image](https://github.com/Radarr/Radarr/assets/155886006/2272d667-1650-4d76-b65e-badaf1e7e0e4)

Example for how it would look in the media:
![image](https://github.com/Radarr/Radarr/assets/155886006/4b50eaa1-2a3e-46b1-a324-fbdedf5afcb9)

**Comment by bakerboy448** [comment]
CAM is a quality not an edition.  There is not a movie that is released that as a CAM edition.
editions are: extended cuts, director cuts, etc.

0.00001% usecase given few if any users actually want shitty CAMs

**Comment by redexer** [comment]
CAM is just an example. And I do understand that specifically CAM isn't a real edition. That's why I want to be able to add my own editions based on formats.
I can think of a lot of situation where you want for example plex to show a specific text in the edition location.

@bakerboy448 do you have a suggestion on how to work around this if you don't want to add support?
