### ISSUE TITLE
Couchpotato list not importing

### ISSUE THREAD

**Issue by SJ50** [Radarr/Radarr#957]
nightly v 0.2.0.418
couchpotato list is showing anything. There is no debug log or anything.

**Comment by onedr0p** [comment]
Do all the movies in cp already exist in radarr?

**Comment by SJ50** [comment]
I just added one movie, tried to manually import and it shows list is empty. 
Problem with nightly only not develop.

**Comment by onedr0p** [comment]
Can you try to delete the list and re add it? Also do other lists work?

**Comment by SJ50** [comment]
Yes other list works, I already tried deleting and adding serval time. No luck

**Comment by Enf0** [comment]
Same issue here. Logs tell me the following:
`NetImportSearchService	No lists are enabled for auto-import.`

![image](https://cloud.githubusercontent.com/assets/825808/23609507/a53fbbe2-026e-11e7-9080-6dcadc621840.png)

**Comment by onedr0p** [comment]
Fixed in next release
