### ISSUE TITLE
MovieIndexPage Missing/Not Monitored

### ISSUE THREAD

**Issue by 4getit** [Radarr/Radarr#959]
Nightly 0.2.0.418 has made the MovieIndexPage more stable. It works much better now. Thank you.

However, I still can't seem to find a way to see the Missing only. Closest I can get is hiding the Downloaded but the Missing and Not Monitored are always mixed up.

Is it possible to make it so that the Missing can be shown only?

**Comment by hotio** [comment]
Doesn't this button work for you? Or does this button also show you "Not Monitored"?
![missing](https://cloud.githubusercontent.com/assets/25102010/23461021/55ed921a-fe88-11e6-9e9a-703fe61dc7a5.png)

**Comment by 4getit** [comment]
Yes, they're mixed up and it's getting a bit hard to see what is Radarr is still looking for.
![Image](https://dl.dropboxusercontent.com/u/609785/other/scrn01.png)

Unless I'm mistaken, I think that (in most cases) 'Not Monitored' -entries mean that those were downloaded already and then removed from disk. I'm leaving them in hoping that they prevent downloading again (when accidentally adding movies that were downloaded before already). Or when importing lists with duplicates.

With Sonarr, the 'Missing Only' button filters everything out and just shows whatever is 'Wanted'.

**Comment by geogolem** [comment]
i think the wanted gets filtered on the Missing/Wanted page..
but more filters and perhaps and improvement to the structuring of the filters is something I plan to look at in the future.

There already is an aditional Monitored & Available filter on the missing page... (i added that one)
