### ISSUE TITLE
Drone Factory does not import movies

### ISSUE THREAD

**Issue by evulhotdog** [Radarr/Radarr#96]
I've configured the dronefactory folder, put a movie in there, and Radarr doesn't even seem to be searching/picking it up via the logs, not even when forced from the Wanted > Rescan Drone Factory Folder button.

**Comment by fedoranimus** [comment]
Fixed by #133.

**Comment by jpborjas** [comment]
What build do I need for this fix? I'm running Version
0.2.0.210
Mono Version
4.6.2 (mono-4.6.0-branch/ac9e222 Wed Dec 14 17:02:09 EST 2016)

**Comment by tr0nllam** [comment]
Drone Factory is not working for me in the latest build and never has.

**Comment by mushbuddygoose** [comment]
I have the same issue..

If you use some automation tool like hazel or using watch folders, you can force a manual download episode scan via the api call which will work to start the import on the drone factory folder. You can use something like this to run: curl http://localhost:YOUR_SERVER_ADDRESS/api/command -X POST -d '{"name": "downloadedmoviescan"}' --header "-Api-Key:YOUR_API_KEY_HERE"

**Comment by wifiuk** [comment]
drone factory does not work for me on the latest version
