### ISSUE TITLE
Add ability to ALERT when new film added by a flagged director (or actor)

### ISSUE THREAD

**Issue by imzenreally** [Radarr/Radarr#9605]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

no problem - purely a feature request - totally understand prioritization 

BUT ;)

it would be awesome if I flag lets say Ridley Scott as a director I want to auto pull all new movies for - when a new movie from said director is grabbed if it would alert me via pushover - I'm sure I could probably figure a third party solution via PMM or some other tool but I think it would be great built into RADARR

### Describe the solution you'd like

no problem - purely a feature request - totally understand prioritization 

BUT ;)

it would be awesome if I flag lets say Ridley Scott as a director I want to auto pull all new movies for - when a new movie from said director is grabbed if it would alert me via pushover - I'm sure I could probably figure a third party solution via PMM or some other tool but I think it would be great built into RADARR

### Describe alternatives you've considered

PMM - Tautulli - debated writing a python or bash script to do the polling but I'd rather It be built into the primary app controlling my movies

### Anything else?

app is the shit - big fan

**Comment by imzenreally** [comment]
specifically - alerts via the built in alerting systems ... discord pushover etc ( I primarily care about pushover -- but others may vary)

**Comment by bakerboy448** [comment]
This exists with the movie added trigger for notifications
