### ISSUE TITLE
Movie is in wanted list but reports 'was in your library, not found in your list'

### ISSUE THREAD

**Issue by mow4cash** [Radarr/Radarr#961]
**Description:**
This is happening for every movie regardless of if the movie is in my wanted list.
I am aware of the setting that causes this log.
  `  was in your library, but not found in your lists --> You might want to unmonitor or remove it`

**Radarr Version:**

0.2.0.418

**Logs:**

`was in your library, but not found in your lists --> You might want to unmonitor or remove it`

**Comment by onedr0p** [comment]
@geogolem might have an answer to this.

**Comment by geogolem** [comment]
very weird.. will have to look more into this. I will look into it tonight or tomorrow and will get back to you then.

**Comment by geogolem** [comment]
so i experimented with the latest driver and I could not seem to reproduce this issue.

Some thoughts:  This only uses lists with enable-Auto... if it is in a list of yours that is not used during netsync intervals then you will get that message output...

Can you please verify if this is corresponding to movies from a list that is not auto enabled?

**Comment by geogolem** [comment]
ok with the latest driver.. i am seeing something like this.. so i seem to be able to reproduce it now.. I am investigating.

**Comment by mow4cash** [comment]
Maybe the function is working as it is supposed to. Most of the movies in my wanted list are not from Trakt or IMBD but were added manually.

If understand correctly this setting would only monitor Trakt and IMBD? So even if the movie was in my wanted list it would still throw the log since the movie is not in the Trakt or IMBD lists? 

My lists are TMBD and Trackt both set to enable-auto. I think I originally added my movies with a CouchPotato list and then deleted the list after they were added if that had anything to do with it.

"The feature is really only intended for people who totally sync radarr up with a list(s) automatically.. and don't add or remove items from radarr directly..."
I add movies directly and don't just sink up with my list. The explanation you gave makes more sense of what this feature is used for.

**Comment by geogolem** [comment]
Just to clarify.. the movies you have added to Radarr are not really what we are calling a List... Lets call that the Library...

the lists we are referring to, are lists added via the Settings --> List option...

in any case, i am experiencing something similar to what you originally referred to.. where this message is getting logged for every movie; however, I think it is not the same case you are referring to. I am investigating now -- and I will report back here when I figure out what is happening.

**Comment by geogolem** [comment]
I checked in a fix related to this part of the code here: https://github.com/Radarr/Radarr/issues/995

I dont think it is related to your issue, but Im not sure.. Let me know if you still notice any issues with respect  to this feature.

**Comment by geogolem** [comment]
I'm going to close this issue off --> but if you still have concerns please let me know. If you also have ideas or sugestions for features or enhancements I might take alook at them -- but its probably best to suggest over on feathub.
