### ISSUE TITLE
RSS issues

### ISSUE THREAD

**Issue by darknessgp** [Radarr/Radarr#964]
**Description:**

I receive the below error messages when doing an RSS sync, either by waiting or manually kicking off the process. It appears to work correctly the first time if I remove the indexers and re-add them. But one the second time or beyond, I start to get these error messages. Sometimes it's just for PTP or AHD, sometimes both. Sometimes it's Jackett erroring. 

Manual searching works great though.

**Radarr Version:**
0.2.0.375

**Logs:**
17-3-1 18:07:07.6|Debug|PassThePopcorn|Downloading Feed https://passthepopcorn.me/torrents.php?action=advanced&json=noredirect&searchstr=
17-3-1 18:07:07.6|Trace|HttpClient|Req: [GET] https://passthepopcorn.me/torrents.php?action=advanced&json=noredirect&searchstr=
17-3-1 18:07:07.8|Trace|ConfigService|Using default config value for 'proxyenabled' defaultValue:'False'
17-3-1 18:07:07.9|Trace|Owin|SQLite error (5): database is locked
17-3-1 18:07:08.0|Trace|RateLimitService|Rate Limit triggered, delaying '(removed)' for 1.760 sec
17-3-1 18:07:08.0|Warn|PassThePopcorn|PassThePopcorn https://passthepopcorn.me/torrents.php?action=advanced&json=noredirect&searchstr= Curl Error RecvError for Url https://passthepopcorn.me/torrents.php?action=advanced&json=noredirect&searchstr=

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by darknessgp** [comment]
To somewhat bump this, noticed today that because of these errors, Radarr has marked PTP and AHD unavailable and now won't search them until I went in and did a manual test.

**Comment by onedr0p** [comment]
Honestly looks like a issue on your end, i use ptp and ahd with no issues. Maybe its something to do with your network or your version of curl?

**Comment by darknessgp** [comment]
I am running this on a seedbox, curl is version 7.35.0. A bit old, but not too old. I'm a bit more confused as I run sonarr here without issue... presumably, radarr should be using the same method sonarr does for RSS watching.

**Comment by galli-leo** [comment]
It does. The problem may be coming from the indexers that use ssl to new for your curl to handle maybe? Try installing libcurl3.

**Comment by darknessgp** [comment]
I'm closing this issue... Not sure exactly what happened, but updated to the latest Radarr version and my issue has completely gone away...
