### ISSUE TITLE
Merge DownloadStation fixes from sonarr

### ISSUE THREAD

**Issue by margaale** [Radarr/Radarr#965]
Please, merge Sonarr/Sonarr@9a870a37090bfb5dfcf26bc4108c767614c163e7 to fix some issues and add one test when adding the client.

See Sonarr/Sonarr#1720

**Comment by onedr0p** [comment]
@margaale can you open a PR? Thanks. I do not have as much free time to work on radarr.

**Comment by onedr0p** [comment]
Any help is appreciated.

**Comment by margaale** [comment]
Sure, but not now, maybe over the weekend.

**Comment by onedr0p** [comment]
Thanks

**Comment by margaale** [comment]
Done, sooner than i thought...
