### ISSUE TITLE
Import files with missing extension

### ISSUE THREAD

**Issue by John-Gee** [Radarr/Radarr#9650]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Sometimes downloaded files' filenames don't have an extension for a reason or another, but the files themselves are fine.

### Describe the solution you'd like

 Radarr should be able to use file, mediainfo, etc. to figure out if the file is correct if there is no extension and move on from there.

### Describe alternatives you've considered

If you have a good reason to not allow automatic import of files without extension, at least allow the manual import to see those files.

### Anything else?

Thanks!

**Comment by bakerboy448** [comment]
Files with no extension are not valid and the type cannot be determined.

Your download client should fix the missing extension or your should block the release groups that fail to provide valid files with custom formats

**Comment by John-Gee** [comment]
How is the file not valid? The simple 'file' command can tell me what type the file is. The extension is mostly for the human user, the computer has no need for it.

For instance last case:

` # file GARBAGE_NAME
GARBAGE_NAME: Matroska data` 

or even

` # file GARBAGE_NAME.avi
GARBAGE_NAME: Matroska data` 


Maybe I was not clear enough, I'm talking about a file downloaded on Radarr's request, so Radarr should have all the info but the file type from the indexer, and that it can find easily locally.

I actually even think that on rename Radarr should verify that the extension does match the actual file type and change it as needed.

**Comment by bakerboy448** [comment]
Out of scope of Radarr to try and fix broken invalid files. Again the download client is responsible for fixing broken files.

**Comment by John-Gee** [comment]
I don't know why you keep saying files need fixing/require extensions, they are optional on Unixes OS. I can have media files without extensions in their filenames and they will still have proper thumbnails in the file explorer and play in a video player automatically just fine.

But I'll trust you that it is the wrong place to change that and will see how to do it from the download client.

Thank you for your replies!
