### ISSUE TITLE
 Issue with Prioritization Using Custom Scores and Qualities

### ISSUE THREAD

**Issue by PromotheusParis** [Radarr/Radarr#9651]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I'm experiencing an issue with Radarr that I'm unable to determine whether it's a bug or a misunderstanding on my part.
I have set up custom scores and qualities for movie downloads and radarr dosen’t seems to download the highest score for the same category ( for example the category Bluray-2160p )

In the example below, you can see that Radarr didn’t download the highest score for the Blu-ray profile. ( be careful I have a quality limit of 31 GIB for this movie )
![image](https://github.com/Radarr/Radarr/assets/106491825/38731d37-8d63-4b1f-bb7a-e7af40784335)

 
The message error when I select the highest score +6505 . You can see that Raddarr consider the video with the score +3255 higher quality than the video with +6505
![image](https://github.com/Radarr/Radarr/assets/106491825/50b2e650-908b-48b6-9354-0c500bb80709)

 
My quality limit for bluray-2160p which limit at 31 GIB for this movie 
 
![image](https://github.com/Radarr/Radarr/assets/106491825/7335ad9b-7ca4-480a-92dc-4683c0d7b118)

### Expected Behavior

In the example I was expecting that Raddarrr grab the video with the highest score . In the example provided, there is a limit of the size of the video of  31 GiB maximum, So I was expecting that radarr grab the movie with the score of  6505

### Environment

```markdown
- OS: alpine
- Radarr: 5.2.6.8376-ls199 by linuxserver.io
- Docker Install:  lscr.io/linuxserver/radarr:latest
- Using Reverse Proxy: yes treafik
- Browser: 
- Database: Sqlite 3.41.2
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

there is no error related to this issue on the debug log file. I can provide it if need it

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
99% sure this will be support issue and having proper/repack not configured per the guide / wrongly set to prefer propers/repacks

**Comment by PromotheusParis** [comment]
Hi

Thank you @bakerboy448 you were completely right. **The issue was  that I set to prefer propers/repacks**

I apologize for the log file. In the future, I will ensure to upload it as per the required guidelines.

I'm closing this issue and would like to extend my sincere thanks for your assistance. Your help has been truly appreciated

**Comment by bakerboy448** [comment]
The next master will have some coloring which should make this more obvious 

Sonarr PR example for a repack
https://private-user-images.githubusercontent.com/1117625/286373560-808f847b-ac5e-4f88-aa60-2f9d09f26d76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3MTY5NjUsIm5iZiI6MTcwNTcxNjY2NSwicGF0aCI6Ii8xMTE3NjI1LzI4NjM3MzU2MC04MDhmODQ3Yi1hYzVlLTRmODgtYWE2MC0yZjlkMDlmMjZkNzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjBUMDIxMTA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmRkNjI5ODA1ODAzMTc3YTljNzc1OWE3Y2U5NDllNzc1YTZlOTU1MmQyNTc5MzkxYmFhN2RjN2QxY2RlNDZlOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.K8bkzLauH7uqNuWragqXzDe10fmhisrIi7E7kPcWRDQ
