### ISSUE TITLE
[Feature request] Cutoff unmet - Option to choose results per page [ 50, 100, 500, 1000 ]

### ISSUE THREAD

**Issue by ajkis** [Radarr/Radarr#966]
Atm its really hard to search for all movies where Cutoff unmet since its showing only 15 movies per page.
For example I have 54 pages of it and to upgrade movies I need to select all, search wait 10 minutes ( while all indexers are processed ) go to next page and repeat the process.

![image](https://cloud.githubusercontent.com/assets/23003132/23474521/4e269cee-feb4-11e6-939e-793adb76c65b.png)

p.s. Another option would also be a button Search All like its there for Missing ones.

**Comment by onedr0p** [comment]
We talked about this, just making a flat 50 per page and adding a search all cutoff unmet is sufficient.

**Comment by onedr0p** [comment]
Fixed in next release
