### ISSUE TITLE
Custom Format - language negate not working for 'Multi-Language'

### ISSUE THREAD

**Issue by soleous** [Radarr/Radarr#9669]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

When I configure a Custom Format with a language of "English" that is negated and perform an interfactive search.  It scores for single language content such as "French" or "Dutch", but not for "Multi-Language" that content non English languages such as "French" or "Dutch".

If I perform a normal (without negate) score for "French" or "Dutch".  It scores for "Multi-Language" content that has "French" or "Dutch" languages.

### Expected Behavior

Custom Formats that have a negated language, should match/score for "Multi-Language" content that contain the negated language.

### Steps To Reproduce

Configure Custom Format, with:
1. name of "Non-English"
2. language of "English"
3. negate option enabled

Perform an interactive search for a movie and look for:
1. centent that has language "French", "Dutch", "German", etc. and inspect the score to see the Custom Format "Non-English" listed
2. centent that has language "Multi-Language" and inspect the score, where I expect to see the Custom Format "Non-English" listed

### Environment

```markdown
- OS: linuxserver.io
- Radarr: 5.3.3.8509
- Docker Install: Yes
- Using Reverse Proxy: both
- Browser: Chrome and Firefox
- Database: Sqlite 3.41.2
```

### What branch are you running?

Nightly

### Trace Logs? **Not Optional**

[radarr.trace.txt](https://github.com/Radarr/Radarr/files/14010852/radarr.trace.txt)

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
What/ which movies?

if their original language is English and if Multi - well multi will ALWAYS be English (movie original language)

**Comment by soleous** [comment]
Any movie, for example "the lego movie" or "Tango & Cash".

This is a bug, discord was not helpful.  The negate on languages is not working.

**Comment by soleous** [comment]
I discussed it last or a couple of weeks ago.  Its is not working for "multi-languages".  Please re-read the "Current Behavior" and test if it you need, you'll see that negated languages do not match when in multi-languages.  When negate is not enabled it works for multi-languages.

**Comment by bakerboy448** [comment]
Negate means does not match

If a release's multi language includes English - which it appears all do then with a Custom Format of English negated, the format will correctly never ever match as the release includes English

**Comment by soleous** [comment]
Negate is a not, therefore not english, so it matches everything but English.  What I am expecting is if content has german and english, the german peace will match and score.  This is the behaviour when its negate is disabled.

**Comment by soleous** [comment]
I'll move over to discord to discuss again. I'm not discounting my understanding, but I'll update after discussing.

**Comment by soleous** [comment]
For anyone else,

To clarify, the understanding of the negate logic is correct, however radarr is looking at all languages holistically for the content, therefore the search term apples to all languages of the content.  This results in a "Multi-Language" with "English and Dutch" containing English and therefore not scoring.

@bakerboy448 thats for clarifing my understanding.
