### ISSUE TITLE
Radarr (and other *arrs) report Proxy IPs in logs for authentication warnings.

### ISSUE THREAD

**Issue by karserasl** [Radarr/Radarr#9698]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

Hello

When you are behind a proxy, ex Cloudflare, the X-Forwarded-For header contains a list of IPs separated by comma.
Usually the client ip is at position 0.

Radarr (and other *arrs) log the Proxy IP instead of the client ip when an authentication warning (ex. bruteforce) occurs.

### Expected Behavior

Either should you look for X-Real-IP header, Cf-Connecting-Ip header or get the 1st IP in X-Forwarded-For header and report it.

Security programs like crowdsec, parse the logs for banning the client. But if you report the Proxy IP (which usually is whitelisted) they cannot ban the client.

### Environment

```markdown
- OS: debian 12
- Radarr: latest nightly
- Docker Install: Yes
- Using Reverse Proxy: Traefik (cloudflare infront)
- Browser: 
- Database:
```

### What branch are you running?

Nightly

### Trace Logs? **Not Optional**

> 2024-01-27 13:47:37.3|Trace|Http|Req: 358 [POST] /login?returnUrl=/&loginFailed=true (from 162.*.*.75 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36)
> 2024-01-27 13:47:37.3|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was not authenticated.
> 2024-01-27 13:47:37.4|Trace|Http|Res: 358 [POST] /login?returnUrl=/&loginFailed=true: 302.Redirect (16 ms)
> 2024-01-27 13:47:37.9|Trace|Http|Req: 359 [GET] /login?returnUrl=/&loginFailed=true (from 162.*.*.75 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36)
> 2024-01-27 13:47:37.9|Trace|Http|Res: 359 [GET] /login?returnUrl=/&loginFailed=true: 200.OK (1 ms)
> 2024-01-27 13:47:43.9|Trace|Http|Req: 360 [POST] /login?returnUrl=/&loginFailed=true (from 162.*.*.75 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36)
> 2024-01-27 13:47:43.9|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was not authenticated.
> 2024-01-27 13:47:44.0|Trace|Http|Res: 360 [POST] /login?returnUrl=/&loginFailed=true: 302.Redirect (15 ms)
> 2024-01-27 13:47:44.4|Trace|Http|Req: 361 [GET] /login?returnUrl=/&loginFailed=true (from 162.*.*.75 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36)
> 2024-01-27 13:47:44.4|Trace|Http|Res: 361 [GET] /login?returnUrl=/&loginFailed=true: 200.OK (0 ms)
> 2024-01-27 13:47:46.2|Trace|Http|Req: 362 [POST] /login?returnUrl=/&loginFailed=true (from 162.*.*.75 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36)
> 2024-01-27 13:47:46.2|Debug|Radarr.Http.Authentication.ApiKeyAuthenticationHandler|AuthenticationScheme: API was not authenticated.
> 2024-01-27 13:47:46.2|Trace|Http|Res: 362 [POST] /login?returnUrl=/&loginFailed=true: 302.Redirect (1 ms)
> 2024-01-27 13:47:46.6|Trace|Http|Req: 363 [GET] /login?returnUrl=/&loginFailed=true (from 162.*.*.75 Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36)
> 2024-01-27 13:47:46.6|Trace|Http|Res: 363 [GET] /login?returnUrl=/&loginFailed=true: 200.OK (0 ms)

> 2024-01-27 13:47:44.0|Warn|Auth|Auth-Failure ip 162.158.xxx.xxx username 'admin'

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
- latest nightly is not a version
- Provide the proxy co no and headers from a request

**Comment by karserasl** [comment]
Version: 5.3.3.8527

Headers:

> X-Forwarded-For: 37.120.xxx.xxx, 172.71.xxx.xxx
> X-Forwarded-Port: 443
> X-Forwarded-Proto: https
> X-Forwarded-User: xxx@xxx.com
> X-Real-Ip: 37.120.xxx.xxx
> X-Trusted-Proxy: 172.71.xxx.xxx
> X-Webauth-User: xxx@xxx.com

**Comment by bakerboy448** [comment]
Still waiting for the other info requested - nginx conf 

logs also don't match your headers. Where is that 162 address from?

**Comment by karserasl** [comment]
Thats the cdn of Cloudflare.
It changes. Every CF subnet is whitelisted, so that crowdsec doesnt ban the whole proxy.

As for the traefik config, its complicated and a lot. Dont think it would help. The problem is shown above.
Radarr is logging the RP IP, not the client.

**Comment by bakerboy448** [comment]
Radarr is logging the cloudflare Ip based on what you just said which is not the RP IP. Which means the headers provided are not the headers used when the logs where gathered.

pretty sure this is a RP config issue not a radarr issue ... double so given how complicated traeflik is and frequent misconfigurations
