### ISSUE TITLE
Movies not dropping off activity after drone factory import

### ISSUE THREAD

**Issue by chicaneau** [Radarr/Radarr#970]
**Description:**

Movies are not not dropping off activity after drone factory import. This works fine in Sonarr and is a workaround I use for Radarr + Sonarr not having an unrar feature.

If i try and remove a movie from activity after the import, it deletes the torrent entirely from utorrent which is not ideal. There is no other workaround I don't believe.

https://i.imgur.com/HoEeV6R.png

https://i.imgur.com/vHYW5hD.png

**Radarr Version:**0.2.0.375

**Logs:**N/A

**Comment by onedr0p** [comment]
No logs?

**Comment by hotio** [comment]
The workaround is disabling Drone Factory and using Completed Download Handling with Remote Path Mappins setup correctly, just make sure you disable "Remove", visible by enabling advanced settings.

**Comment by chicaneau** [comment]
Hey Hotio, 

this is a good idea for some scenarios, however for my situation, some torrents i download are rar'd and some not rar'd. I have a script auto-extract the rars to the drone factory to take care of that situation. If i change the mapping, it wont find the non-rar'd ones.

This works fine in Sonarr, so it should be fixable.

onedr0p. There was nothing written to the log when the import of Star Wars: Episode III occurred from drone factory. I thought it was odd.. You can't make the logs more verbose can you? 

Cheers

**Comment by hotio** [comment]
I understand your situation and it's perfectly doable without using the drone factory.

**Comment by AlexWalder** [comment]
Why not extract to downloaded location rather than drone factory, that way Radarr sees it and can process it in place. Completely bypass drone factory

**Comment by chicaneau** [comment]
Because, if i extract to the downloaded location, it wont cleanup/delete the mkv files after it copies them, because they're in the torrent folder. And i never want radarr to cleanup downloaded torrents so they can keep seeding. so the 2 configurations i'd need would conflict each other. 

One for torrents where it only downloads RAR's, which handles the 'extra' extracted mkv's and deletes the extracted MKV but not the RAR's, 

One for torrents where it only downloads an MKV. Which i don't want to be removed/deleted from the torrent download folder

My setup in sonarr works perfectly, having a script extract the mkv's from the rars to the sonarr factory, which are then cleaned up/deleted and copied/rename. The activity item is removed and the tv episode is marked as downloaded as expected. Radarr is not behaving like this and that's what this bug report is for.

**Comment by onedr0p** [comment]
We will get this fixed, just give us time :)

**Comment by chicaneau** [comment]
onedr0p, you're a gentleman and a scholar, thankyou sir

**Comment by AlexWalder** [comment]
You can set it to Move rather than Copy, and that will keep the torrent folder clean, and it won't delete the torrent if you've set radarr to not remove from torrent client upon completion

**Comment by AlexWalder** [comment]
This exact way is the way I've set it up and it's working perfectly for me

**Comment by chicaneau** [comment]
How does it know the difference between an extracted file and a downloaded one? 
I have no move/copy option anywhere just "Use Hardlinks instead of Copy"

**Comment by AlexWalder** [comment]
Well crap, you are 100% right, it is copying. This ruins my whole setup. Back to drone folder it is.

**Comment by AlexWalder** [comment]
I could have swore it was moving. Maybe that was on my Couch potato setup

**Comment by seanvree** [comment]
FYI: I wrote a little tutorial how to deal with RARed releases.  But it requires you to use the drone factory. 

However, I'm seeing this issue as well, if it imports it from the drone factory, it will not remove it from the client download history.  Sonarr works fine, but Radarr does not. 

https://forums.sonarr.tv/t/guide-automatically-process-rar-releases-in-sonarr-radarr-while-using-usenet-and-torrents-on-a-windows-environment/13743

**Comment by hotio** [comment]
All of this is easily handled with a post-processing script for deluge that extracts the torrents and "Remote path mappings" pointing to the location of the extracted content. Absolutely 0 reasons to include the drone factory in your automated setup.

Radarr/Sonarr will however not remove processed content coming from torrents, so a simple script running periodically to remove content older than a day/hours should clean that up.

**Comment by seanvree** [comment]
@hotio  - I agree, however, I have have not found a script that will run on windows that does this.

**Comment by chicaneau** [comment]
So with Sonarr depracating the factory, i presume Radarr will too, I am now using a script to hit the API to manage the completed download handling on unrar'd torrents. It's working nicely too. Only issue is, even when using the API, i see the same behaviour where it doesnt not remove the movie from the activity list after import. Even though it works fine in Sonarr
