### ISSUE TITLE
Add edit Audio Info

### ISSUE THREAD

**Issue by Cobragt92** [Radarr/Radarr#9732]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

there is no problem it is an add on.

### Describe the solution you'd like

 in edit movie options if there if there is MulLanguages and you remove one I'd like too be able to switch the Audio info to what Language you choose.

### Describe alternatives you've considered

i don't have any other idea's sorry.

### Anything else?

i don't have any other idea's sorry.

**Comment by bakerboy448** [comment]
Audio languages come from media info via ffprobe.  You can use manual import from the movie's page to force a rescan. Or if the size changed or file name changed a refresh/rescan should do it as well.

Please use [Discord](https://radarr.video/discord) for support/questions.
