### ISSUE TITLE
Ability to have custom qualities

### ISSUE THREAD

**Issue by abcasada** [Radarr/Radarr#9733]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Inability to specify more than one quality definition for a particular resolution and type combo. For example:

Bluray-2160p, Min 20, Preferred 30, Max 40
Bluray-2160p-2, Min 60, Preferred 100, Max 150

### Describe the solution you'd like

I would like to be able to have more flexibility to have more quality settings for different movies.

I can envision accomplishing this two ways:

1. Be able to add custom quality definitions to the existing ones, such as a new Bluray-2160p-2 quality
2. Be able to specify quality in a profile instead of selecting an existing quality definition

My use case is something like this:

* Low quality
  * WEBDL-1080p, 20, 30, 40
  * WEBRip-1080p, 20, 30, 40
  * Bluray-1080p, 20, 30, 40
  * WEBDL-2160p, 20, 30, 40
  * WEBRip-2160p, 20, 30, 40
  * Bluray-2160p, 20, 30, 40
* Medium quality
  * Bluray-2160p, 60, 100, 150
* Best possible quality
  * Remux-2160p, 0, 399, 400
  * WEBDL-2160p, 0, 399, 400
  * WEBRip-2160p, 0, 399, 400

The reason I want low, medium, and best qualities:
* Low: the bulk of my movies
* Medium: a subset that I really like and want better quality
* Best: a smaller subset that I really want best quality

A large part of this is wanting to not need as much storage.

### Describe alternatives you've considered

I have tried utilizing the multiple quality definitions that already exist at each resolution. However, there are not enough to do what I'd like (in my example profiles).

### Anything else?

I am interested to discuss the pros and cons of this. I am assuming I'm not the first one to think along these lines, and I certainly realize this will require work and there are probably obstacles that I don't understand.

**Comment by abcasada** [comment]
I just realized I didn't look through closed issues. Looking at those now for duplicate. My apologies.

**Comment by Qstick** [comment]
No plans to do something like this right now, custom formats is about as far as we're taking this
