### ISSUE TITLE
Sync wish list with Kinopoisk

### ISSUE THREAD

**Issue by and7ey** [Radarr/Radarr#9753]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

It would be create to have regular sync of movies to be watched with Kinopoisk.ru. Ideally regular sync from Kinopoisk to Radarr. Or at least one time import.

### Describe the solution you'd like

The list of movies is available at https://www.kinopoisk.ru/user/17367/movies/list/type/3575/, where 17367 is unique user id and 3575 is a constant folder id for wish list

### Describe alternatives you've considered

copy movies manually

### Anything else?

kinopoisk is biggest RU website equal to imdb

**Comment by Dukobpa3** [comment]
Or better to ban it forever the same as maintaining country

**Comment by Qstick** [comment]
Do they have an API?

**Comment by and7ey** [comment]
> Do they have an API?

They have, but it is not open.

**Comment by Qstick** [comment]
If Radarr can't use the API then it's a no go
