### ISSUE TITLE
Custom Filter: the ability to filter/compare with {File Name Tokens}

### ISSUE THREAD

**Issue by deathbybandaid** [Radarr/Radarr#9765]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

N/A

### Describe the solution you'd like

Example:

My Deadpool collection had "Deadpool 3" instead of the released title "Deadpool & Wolverine".

I would like to be able to create a custom filter that can

`Path` `Does NOT Contain` `{Movie Title}`

This would allow me to see all the movies that need directories renamed. It would also open up other methods of filtering.

### Describe alternatives you've considered

The method of renaming folders/movies by changing the root folder to the same root folder works fine, but you'd have to know what movies had the wrong name.

### Anything else?

N/A

**Comment by deathbybandaid** [comment]
You'd be amazed how many root folders I use. Not everybody organizes their library the same.

**Comment by bakerboy448** [comment]
> You'd be amazed how many root folders I use. Not everybody organizes their library the same.

Script it?

get all root folders
Get all movies
Filter for the root folders
Move to same root folder

repeat
