### ISSUE TITLE
edit Movie folder name

### ISSUE THREAD

**Issue by moreje** [Radarr/Radarr#9784]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

unwanted police when using original movie name for folder

### Describe the solution you'd like

I'm using the Original Movie Name tag to build the folder name when importing new movie.
But for some movies, i.e, japanese or chinese, I can't read the police...

### Describe alternatives you've considered

when importing a movie, It would be usefull to bypass the pre defined folder name and set a custom one

### Anything else?

![image](https://github.com/Radarr/Radarr/assets/5374164/f1035331-ebd3-46ab-ba08-f3d001341f52)

**Comment by Qstick** [comment]
No plans to make this custom, use title or a translated title tag in your naming. Original title will always have foreign names

**Comment by moreje** [comment]
> Can you explain better your issue with the unwanted police?

I can easily read English names, but when the original name is written with japanese alphabet, I can't..
 so I would found useful to be able, sometimes, to be able to edit the folder name for a movie
I'm French speaker, so my guess would be::every French movies stored in French named folders... And all the others in English named folders. But I can't find how to do that in radarr...
