### ISSUE TITLE
Perform a search for already existing movie when update via RSS is triggered

### ISSUE THREAD

**Issue by MadaxDeLuXe** [Radarr/Radarr#9789]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

**To encounter this problem:**

- have a fresh install of sonarr and add custom formats and points (i.e: release group +2 languages [eng + ger])
- have the naming scheme just include title, year and quality 
- download a movie (i.e: Ace Ventura Jetzt wirds wild (1995.Bluray-1080p).mkv)
- re-install sonarr, add all your settings as before, but DON'T re-import sonarrs database
- change naming scheme to include release groups a.s.o
- add your base-dir again and import your movies which were downloaded before the re-install

Sonarr now will list the movie as just english, even though it's multi-lang and has no idea of the formats and the format-score (of course, since that info is stored in sonarrs not-reimported-db, I guess). Even though the "details" button will show it's ger + eng, but that's not the main problem. (See included screenshots.)

_**If said movie now shows up in an RSS scan, it will just download that version - even though that indexer has a version which matches your formats way better and would get a much better score.**_

### Describe the solution you'd like

An option to turn on, that when a movie is found via RSS:

1. a search against that movie is performed
2. points for the RSS-version and the search-version (if existant) are calculated
3. the version with the most points is downloaded

### Describe alternatives you've considered

I can't think of a better option if you don't wanna re-import your old database, because you want to create a clean, new one. Even if that means you have to download the same file as in the past, because Sonarr doesn't have all data, because you didn't re-import your old Sonarr database. That's the most simple solution, given you have a good internet connection, I guess.

Maybe if your Indexer provides hashes for the unpacked movie file, sonarr could create hashes on import to compare and add your custom formats and your score if it's a match. 

Or Sonarr has it's own database with hashes and corresponding infos (Release-Group, languages, etc) saved serverside for the clients to compare when importing an already filled media folder (but I guess that would be too gigantic). Anonymous and with the option for the user to turn that feature on or off, of course.

An option that Sonarr creates said DB locally, isolated from all other data, so it may querry against that hash-db on import and flag your formats + add your custom score.

### Anything else?

![list_entry](https://github.com/Radarr/Radarr/assets/11695286/a33a85c5-6c33-4fea-838c-6b27400e87d3)
![details](https://github.com/Radarr/Radarr/assets/11695286/e8263e91-4298-40f9-936a-9abae19a458a)

**Comment by bakerboy448** [comment]
No plans to automatically search on RSS match cause Radarr to be banned from every tracker & indexer.

**Comment by bakerboy448** [comment]
https://wiki.servarr.com/radarr/faq#how-does-radarr-work
