### ISSUE TITLE
renaming issues (unpack folder)

### ISSUE THREAD

**Issue by thebetterjort** [Radarr/Radarr#979]
Some movies are unpacked into the _unpack folder and never renamed.

Plex picks up these movies as unpack and never pulls metadeta. 

The foldernames also never get renamed.

Am I missing a setting, or do others have this issue?

**Comment by onedr0p** [comment]
What download client are you using? Is you downloader extracting the files?

**Comment by thebetterjort** [comment]
Using nzbget and yes the downloader is extracting the files.

**Comment by onedr0p** [comment]
You need to use the flatten pp script to move all files to the same folder. 

https://github.com/clinton-hall/GetScripts

**Comment by thebetterjort** [comment]
This behavior doesn't happen all the time, but I think that maybe due to how the file is archived.

Thank you @onedr0p
