### ISSUE TITLE
Import Exclusions list does not work

### ISSUE THREAD

**Issue by jOOc** [Radarr/Radarr#981]
**Description:**

Import Exclusions list does not work. Excluded movie(s) gets added anyway.

![image](https://cloud.githubusercontent.com/assets/9382342/23525705/a1106896-ff8f-11e6-979a-4f15e462d351.png)

![image](https://cloud.githubusercontent.com/assets/9382342/23525795/eff210f4-ff8f-11e6-9cac-a7a862ab8f36.png)

![image](https://cloud.githubusercontent.com/assets/9382342/23525833/1c90a666-ff90-11e6-82e7-3429e56857af.png)

**Radarr Version:**

0.2.0.426

**Logs:**

`17-3-2 21:26:12.7|Info|NetImportSearchService|Movie: {0} was found but will not be added because it {exclusion} was found on your exclusion list
17-3-2 21:26:13.0|Debug|Api|[GET] /api/log/file: 200.OK (14 ms)
17-3-2 21:26:13.1|Debug|Api|[GET] /api/log/file/radarr.debug.txt: 200.OK (15 ms)
17-3-2 21:26:13.8|Info|NetImportSearchService|Movie: {0} was found but will not be added because it {exclusion} was found on your exclusion list
17-3-2 21:26:17.7|Debug|MovieService|Adding 1 movies, 0 duplicates detected and skipped
17-3-2 21:26:18.1|Debug|Api|[PUT] /api/movie/import: 202.Accepted (1802 ms)
17-3-2 21:26:18.1|Info|MediaCoverService|Downloading Poster for [][A Monster Calls] http://image.tmdb.org/t/p/original/oqZ0MBWxNrArZpyVqk3QGAA37QL.jpg
17-3-2 21:26:18.2|Debug|HttpClient|Downloading [http://image.tmdb.org/t/p/original/oqZ0MBWxNrArZpyVqk3QGAA37QL.jpg] to [C:\ProgramData\Radarr\MediaCover\444\poster.jpg]
17-3-2 21:26:18.3|Info|RefreshMovieService|Updating Info for A Monster Calls
17-3-2 21:26:20.2|Debug|RefreshMovieService|Finished movie refresh for A Monster Calls
17-3-2 21:26:20.2|Info|DiskScanService|Scanning disk for A Monster Calls
17-3-2 21:26:20.2|Debug|DiskScanService|Series folder doesn't exist: E:\PLEX\movies\A Monster Calls (2016)
17-3-2 21:26:20.3|Debug|CoverAlreadyExistsSpecification|Corrupted image found at: C:\ProgramData\Radarr\MediaCover\444\poster.jpg. Redownloading...

[v0.2.0.426] System.ArgumentException: Parameter is not valid.
   at System.Drawing.Bitmap..ctor(String filename)
   at NzbDrone.Core.MediaCover.CoverAlreadyExistsSpecification.IsValidGDIPlusImage(String filename) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaCover\CoverAlreadyExistsSpecification.cs:line 51

17-3-2 21:26:20.6|Debug|Api|[GET] /api/log/file: 200.OK (8 ms)
17-3-2 21:26:20.8|Debug|Api|[GET] /api/log/file/radarr.debug.txt: 200.OK (16 ms)
17-3-2 21:26:20.8|Error|MediaCoverService|Couldn't download media cover for [tt3416532][A Monster Calls]

[v0.2.0.426] System.IO.IOException: The process cannot access the file 'C:\ProgramData\Radarr\MediaCover\444\poster.jpg' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at NzbDrone.Common.Disk.DiskProviderBase.DeleteFile(String path) in C:\projects\radarr-usby1\src\NzbDrone.Common\Disk\DiskProviderBase.cs:line 177
   at NzbDrone.Core.MediaCover.CoverAlreadyExistsSpecification.AlreadyExists(String url, String path) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaCover\CoverAlreadyExistsSpecification.cs:line 36
   at NzbDrone.Core.MediaCover.MediaCoverService.EnsureCovers(Movie movie, Int32 retried) in C:\projects\radarr-usby1\src\NzbDrone.Core\MediaCover\MediaCoverService.cs:line 125

17-3-2 21:26:20.9|Debug|MediaCoverService|Resizing Poster-500 for [tt3416532][A Monster Calls]
17-3-2 21:26:20.9|Debug|MediaCoverService|Couldn't resize media cover Poster-500 for [tt3416532][A Monster Calls], using full size image instead.
17-3-2 21:26:20.9|Debug|MediaCoverService|Resizing Poster-250 for [tt3416532][A Monster Calls]
17-3-2 21:26:20.9|Debug|MediaCoverService|Couldn't resize media cover Poster-250 for [tt3416532][A Monster Calls], using full size image instead.
17-3-2 21:26:20.9|Info|MediaCoverService|Downloading Banner for [tt3416532][A Monster Calls] http://image.tmdb.org/t/p/original/xVW8REyVqKwxAtUYY07UGlZH43L.jpg
17-3-2 21:26:21.0|Debug|HttpClient|Downloading [http://image.tmdb.org/t/p/original/xVW8REyVqKwxAtUYY07UGlZH43L.jpg] to [C:\ProgramData\Radarr\MediaCover\444\banner.jpg]
17-3-2 21:26:21.1|Info|NetImportSearchService|Movie: {0} was found but will not be added because it {exclusion} was found on your exclusion list
17-3-2 21:26:23.0|Info|NetImportSearchService|Movie: {0} was found but will not be added because it {exclusion} was found on your exclusion list
17-3-2 21:26:23.8|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (44 ms)
17-3-2 21:26:23.8|Debug|Api|[GET] /api/queue?sort_by=timeleft&order=asc: 200.OK (8 ms)
17-3-2 21:26:24.2|Info|NetImportSearchService|Movie: {0} was found but will not be added because it {exclusion} was found on your exclusion list
17-3-2 21:26:25.7|Debug|HttpClient|Downloading Completed. took 7s
17-3-2 21:26:25.8|Debug|MediaCoverService|Resizing Poster-500 for [][A Monster Calls]
17-3-2 21:26:26.1|Debug|MediaCoverService|Resizing Poster-250 for [][A Monster Calls]
17-3-2 21:26:28.5|Debug|HttpClient|Downloading Completed. took 7s
17-3-2 21:26:28.5|Debug|MediaCoverService|Resizing Banner-70 for [tt3416532][A Monster Calls]
17-3-2 21:26:29.0|Debug|MediaCoverService|Resizing Banner-35 for [tt3416532][A Monster Calls]`

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by geogolem** [comment]
i have to double check.. but i am pretty sure the importExclusions only applies to automatic list import.. if you actually select the movie and import it, it will be imported... otherwise why select and import it..?

**Comment by jOOc** [comment]
@geogolem I have a few list with many movies on them that have not yet been released/found, so sometimes I add movies and select to add from "all lists". That ends up in a very long list and I'm not sure which ones I have excluded (and to lazy to uncheck the ones I know about :) ) so I just choose to add all.

**Comment by jOOc** [comment]
I think that the movies in the exclude list should never be added. Or have an checkmark when adding movies from the list to choose to override it.

**Comment by geogolem** [comment]
Why not import the movies using the automated netimport task.. in the cases when you want to add all?

this can be triggered by making sure the list is "auto enabled" and then hitting the little refresh button in the row specified "NetImport Sync" on the System/Tasks page..

they will be excluded during that.. of course this will trigger an add from all the lists that have auto enabled; however, only moved you dont already have and that dont appear on the exclusion list will be imported.

**Comment by geogolem** [comment]
If you want to disable the auto netimport sync, set the interval to 0.. but you can still trigger this manually via the system/tasks page..
I think that is the best way to add from all lists... and take into account exclusions.

**Comment by onedr0p** [comment]
I think this has become a enhancement request to just remove excluded movies from the list all together :) I can see that being handy.

**Comment by geogolem** [comment]
Im open to discussion here. i think onedrop's suggestion is not a bad one..

I consider it a user error, if the user selects a movie and clicks import, and expects it not to be imported; however, i can understand why the user would be confused here..

@jOOc : I envision two things to fully resolve this issue...

First, Make it very clear that the current implementation only applies to the automatic list import...

Second,, perhaps add a switch, where the user can choose to have the exclusions not even appear in the manually list import..

**Comment by geogolem** [comment]
In Settings below "List Import Exclusions"  add an on/off switch: Hide excluded movies from Manual List Import (default no) ... with a helper saying "if off List import exclusions will only apply to automatic list imports, if on excluded movies will not even be available for import during manual list import"

of course the wording would have to be more concise and clear....

but this is the general idea.

**Comment by jOOc** [comment]
@geogolem I will use the sync task as you suggested for now.

And then I can add the switch/checkbox suggestion to feathub.

Thank you!

**Comment by onedr0p** [comment]
Cool, we will close this then and keep an eye on feathub.
