### ISSUE TITLE
Feature request - Auto directory/folder creation/fix for reported missing folders (Sonarr, Radarr, Readarr etc)

### ISSUE THREAD

**Issue by jacosmitza** [Radarr/Radarr#9812]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

No

### Describe the solution you'd like

I propose a radio or check button next to the missing folder report called "fix" or "fix it for me" to create the missing folders.

![image](https://github.com/Radarr/Radarr/assets/4435207/216fa079-8996-4386-ae08-a57468210aaa)

### Describe alternatives you've considered

My 5TB drive crashed and I lost everything (again, sigh), including my complex organizing folder structure.

What I have done so far is to copy the list to notepad++ and used the replace tool to get line breaks and insert the quotes and md command around the filenames.

### Anything else?

n/a

**Comment by bakerboy448** [comment]
Missing root folders? No plans to have radarr automagically or manually create folders on the disk besides the movie folders it already does
