### ISSUE TITLE
Calendar: Links to movies does not work

### ISSUE THREAD

**Issue by jOOc** [Radarr/Radarr#982]
**Description:**

In the calendar when clicking on a movie it ends up in a 404

**Radarr Version:**

0.2.0.426

**Logs:**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by SWu** [comment]
Same here

**Comment by onedr0p** [comment]
bleh :(

**Comment by onedr0p** [comment]
Works here, try the new nightlies

**Comment by SWu** [comment]
0.2.0.441

Still getting 404 when clicking on calendar links. Weird thing is that the page URL is correct, but when directed from calendar just results in 404. If I go to the 'wanted' page and click the same movie, page loads properly.

**Comment by SWu** [comment]
Actually, clearing cookies for Radarr seems to fix the 404. But clicking calendar links still takes a really long time to load compared to clicking the movie link from e.g. the wanted page.

**Comment by onedr0p** [comment]
Are there any difference between the links?

**Comment by SWu** [comment]
No, that's the really strange thing. If I click from calendar, it 404's. If I copy paste link into new browser window, still 404s. If I click from the 'wanted' list, it works, but if I copy and paste (again the same) link into new browser window it also 404s.

**Comment by SWu** [comment]
OK, I can consistently repro this in incognito:

Open Radarr, go to calendar, click link, works (but takes a strangely long time to actually load the movie page).
Go to settings -> UI -> set page size to some value and save.
Go back to movies page to make sure paging updates.
Go to calendar, click link, 404.

**Comment by sch1308** [comment]
![image](https://cloud.githubusercontent.com/assets/7896067/23596052/008800ba-01f5-11e7-8458-3c02a0c5fda3.png)
still happening on 2.0.457 nighly
