### ISSUE TITLE
Feature Request: Show existing file's quality score for manual import overrides

### ISSUE THREAD

**Issue by jordanlambrecht** [Radarr/Radarr#9832]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

![Screenshot 2024-03-13 at 09 36 57](https://github.com/Radarr/Radarr/assets/54866853/0a277b74-3bdb-4929-a610-368bc98cb5fe)

When an item is held in the activity queue for manual import, one of the warning flags that can be thrown is "Not an upgrade for existing file." As it stands, it displays the quality format of the existing file, but not the quality score. This makes it hard to make a decision if it's better to import the new file or keep the existing.

### Describe the solution you'd like

It would be great if the warning displayed, at the very least, the quality score of the existing file so you can compare scores. Even better would be if the information shown when hovering the warning also displayed the custom format tags on the existing file. This would help the user make a more informed decision.

### Describe alternatives you've considered

Right now you have to manually track down the existing file to view its quality score in order to compare to the import. Or you have to guess.

### Anything else?

Nope, nothing else. I appreciate everything y'all do for this community.

**Comment by bakerboy448** [comment]
> but not the quality score. This makes it hard to make a decision if it's better to import the new file or keep the existing.

If the release is rejected for quality with the message you say then custom format score has no relevance. https://github.com/Radarr/Radarr/blob/04f792c55a97d31809b68378741c2d2a896de1fe/src/NzbDrone.Core/MediaFiles/MovieImport/Specifications/UpgradeSpecification.cs#L50

If the reject is for custom formats, those are already displayed. https://github.com/Radarr/Radarr/blob/04f792c55a97d31809b68378741c2d2a896de1fe/src/NzbDrone.Core/MediaFiles/MovieImport/Specifications/UpgradeSpecification.cs#L77
