### ISSUE TITLE
Feature Request - Downloaded Quality on Radarr Home Screen

### ISSUE THREAD

**Issue by wonkieinc** [Radarr/Radarr#985]
**Description:**

Profile is listed, but not the currently downloaded quality. It would be nice to have this and maybe a search button for quality upgrade on the home page.

**Radarr Version:** 0.2.0.375

**Logs:**

Please use the search bar and make sure you are not submitting an already submitted issue.
Visit our [Discord server](https://discord.gg/NWYch8M) for support or longer discussions.

**Comment by onedr0p** [comment]
Downloaded quality is in the nightly, please use the cutoff in the wanted page to search for upgrading a movie.

**Comment by wonkieinc** [comment]
This does not resolve the issue, I'm asking for a display of what's already downloaded

**Comment by galli-leo** [comment]
That's already displayed on the home page.

**Comment by wonkieinc** [comment]
It displays the profile quality but not the quality of the currently downloaded file, [like so ](http://i.imgur.com/rky3Scw.png)

**Comment by galli-leo** [comment]
If you hover your mouse over Downloaded it will show
