### ISSUE TITLE
Allow ignoring the error "qBittorrent is configured to remove torrents when they reach their Share Ratio Limit"

### ISSUE THREAD

**Issue by carlos-sarmiento** [Radarr/Radarr#9850]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

I have configured my qbittorrent client to delete torrents after they have been seeding for 3 weeks. The existing validation in Radarr provides for a blanket error and blocks me from adding my torrent client. I understand warning people that if the values provided to qbittorrent are too small there is a risk the torrent is removed before import, but with larger values, the issue becomes very unlikely.

### Describe the solution you'd like

Allow an (advanced?) option to ignore the warning (effectively tell Radarr: I know what I'm doing)

### Describe alternatives you've considered

I've had to disable the functionality on qbittorrent. I know there is an option on Radarr to remove imported torrents, but that is not what I want to do. I want to keep the torrent seeding for a certain amount of time, which should be much longer than the time Radarr needs for import.

### Anything else?

N/A

**Comment by bakerboy448** [comment]
14 days is already the minimum https://github.com/Radarr/Radarr/commit/6b9a6223289f016dea1c4ede6ff36ed013a5ab82

**Comment by carlos-sarmiento** [comment]
Thanks for the super quick reply @bakerboy448. I verified and I'm still hitting the error. It seems that [this line in qbittorrent.cs ](https://github.com/Radarr/Radarr/blob/1ee30290efd1dcb79afb0ca45b1f7d7f6010bd51/src/NzbDrone.Core/Download/Clients/QBittorrent/QBittorrent.cs#L453) does not include the validation for minimum retention and so the error is still being shown.

I'd be happy to create a PR to fix it if you think it is a bug that should be fixed.

**Comment by bakerboy448** [comment]
Open a bug report and sore PR upstream in sonarr as the code is the same there as well so it should have the same issue

**Comment by carlos-sarmiento** [comment]
Will do. Thanks
