### ISSUE TITLE
Add from IMDB list, delete, then IMDB adds again..

### ISSUE THREAD

**Issue by paulmorabito** [Radarr/Radarr#986]
**Description:**

I've got an IMDB watch list. Radarr automatically imports a movie and downloads. I watch it, delete from directory and in Radarr. Radarr then seems to re-add it (at a seemingly random point later).

Is there a way to flag already seen items from a feed and not act on them again?

**Radarr Version:**  0.2.0.375

**Comment by onedr0p** [comment]
Turn on ignore deleted movies in settings

**Comment by onedr0p** [comment]
Or unmonitor the movie manually

**Comment by paulmorabito** [comment]
ignore deleted movies is already enabled.

**Comment by onedr0p** [comment]
Sorry you need to wait for the next pre release, or use the nighties.
