### ISSUE TITLE
Movie list broken when filter with no results selected

### ISSUE THREAD

**Issue by SWu** [Radarr/Radarr#987]
If you go to the movie list, select a filter with no results the movie list page goes completely blank and there's no way to get back your movie list.

**Comment by onedr0p** [comment]
Try in incognito?

**Comment by SWu** [comment]
Thanks, I can view the page again in incognito, and I can also reproduce that as soon as I select the filter for  'announced' something breaks and the entire movie page fails to load when I refresh.

Clearing cookies in my browser associated with the Radarr endpoint also reset the main movie view.

**Comment by SWu** [comment]
I really like the new paging feature, but I've noticed a lot of instability probably stemming from the async implementation. In addition to the above issue which totally breaks all page loading on the movie view, I've noticed:
- setting the page size setting isn't reflected in the movie view unless refreshing the browser
- first load of the movie list is noticeably slow; the rest of the page loads but it takes several seconds before the movie list displays
- all sorts of weird behavior with clicking on various filters/sorting and the movie list not updating or updating to the wrong thing

**Comment by geogolem** [comment]
this should be fixed in the latest build. Please let me know.

**Comment by geogolem** [comment]
@SWu : i have fixed, but it wont be merged until later today... the fact that changing the pageSize is not reflected until you reload radarr... It will now be reflected when you switch back to the Movie Index or MovieEditor after saving the change in the settings without reloading...  

It should be merged later today..

https://github.com/Radarr/Radarr/pull/994
