### ISSUE TITLE
[Feature] Import improvement - allow manual reimport already imported torrents

### ISSUE THREAD

**Issue by GAS85** [Radarr/Radarr#9888]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Sometimes by mistake or some other inconvenience it could be that I need to reimport already imported materials. If I e.g. manually download it again, it will not appear in Radarr any more regardless of enabled checkbox "Show items without a movie in the queue. This could include removed movies or anything else in Radarr's category".
![image](https://github.com/Sonarr/Sonarr/assets/6813635/a37212eb-0d0b-48d5-9c1d-537204d6fcaa)

This forced me to do some manual job - copy paste file to the folder and only then do manual import in sonarr and renaming of files.

### Describe the solution you'd like

I would like to see *all* torrents that are currently seeding on my client and have a button for manual import of it, similar how I see currently not imported torrents. Simply do not hide them in UI. E.g. as for "ubuntu" on screenshot:
![image](https://github.com/Sonarr/Sonarr/assets/6813635/331a37f1-2a00-4825-b432-fafc31187320)

### Describe alternatives you've considered

[#1365](https://github.com/Sonarr/Sonarr/issues/1365) similar as here doing some SQL editing is not the way.

### Anything else?

Like your Project 👍 Thanks a lot for it!

**Comment by bakerboy448** [comment]
And to expand on that

              Once imported Sonarr no longer shows items in the queue, but you can use Manual Import from Wanted: Missing, no need to copy/paste files. At this time no plans to add an option to see everything still in the client.

_Originally posted by markus101 in https://github.com/Sonarr/Sonarr/issues/6680#issuecomment-2033264649_

Same applies for Radarr but Manual Import from the Movie Index

**Comment by galeksandrp** [comment]
Okay, if i delete Movie, and then, half a year later, add it back, Radarr
does not import back previously imported downloads from my torrent client (qBittorrent).

Look like that at least on deleting a movie Radarr should either
- purge history of imported downloads from it's sqlite database or
- mark this movie downloads as "desimported", so they can be imported again when adding a Movie.

Guess Sonarr does the same, although I don't use it at all, can't check.

**Comment by galeksandrp** [comment]
[BUG] After deleting Movie from Library in Radarr and adding it back Radarr does not reimport already existing torrents from torrent client without restarting Radarr.

How to reproduce:
1. Install Radarr 5.4.6.8723
2. Add Movie to Library and ensure that torrent is imported.
3. Remove Movie from Library, and keep torrent in torrent client.
5. Add same Movie to Library
6. Voila, no import. No torrent in Activity > Queue.

How to fix temporarily:
- Restart Radarr.

Why occures:
- Seems that Radarr caches History tables from sqlite in memory or what.

**Comment by galeksandrp** [comment]
https://github.com/Sonarr/Sonarr/issues/1365

**Comment by galeksandrp** [comment]
> Can you try restarting Radarr to clear any caches? 🤔

sorry, couldn't resist :)

![image](https://github.com/Radarr/Radarr/assets/3586205/e06054b8-f250-4b99-9bec-c728dd6abe8e)
