### ISSUE TITLE
Script radarr is broken: incomplete LSB comment.

### ISSUE THREAD

**Issue by qriff** [Radarr/Radarr#989]
[https://github.com/Radarr/Radarr/wiki/Autostart-on-Linux)](https://github.com/Radarr/Radarr/wiki/Autostart-on-Linux)

Defines "Method 2: LSB style init-script (Debian/Ubuntu)" with space intendation

```
    #!/bin/bash

    ### BEGIN INIT INFO
    # Provides:          radarr
    # Required-Start:    $local_fs $network $remote_fs
    # Required-Stop:     $local_fs $network $remote_fs
    # Default-Start:     2 3 4 5
    # Default-Stop:      0 1 6
    # Short-Description: radarr
    # Description:       Radarr
    ### END INIT INFO
```

Which with Debian Jessie causes "sudo insserv -v radarr" error:

```
insserv: Script radarr is broken: incomplete LSB comment.
insserv: missing `Provides:' entry: please add.
insserv: missing `Required-Start:' entry: please add even if empty.
insserv: missing `Required-Stop:'  entry: please add even if empty.
insserv: missing `Default-Start:'  entry: please add even if empty.
insserv: missing `Default-Stop:'   entry: please add even if empty.
```

Pre-Release v0.2.0.375

Removing space intendation fixes issue.

In addtion same instructions note 

> Note: The script by default runs as root. I suggest adding an radarr user (useradd -m -d /var/lib/radarr --gid nogroup radarr) and adjusting the script so that RUNASUSER=radarr & RUNASGROUP=nogroup.

Which doesn't produce the /home/radarr home directory referenced in the script.

In addtion same script refer to the executable /opt/radarr/Radarr.exe but the instructions https://github.com/Radarr/Radarr/wiki/Installation reference https://github.com/Radarr/Radarr/releases which spell the release filename in Uppercase resulting in /opt/Radarr instead of /opt/radarr

This seems to be direct inheritance from Sonarr's instructions https://github.com/Sonarr/Sonarr/wiki/Autostart-on-Linux

**Comment by hotio** [comment]
Why don't you fix the Wiki yourself?

**Comment by onedr0p** [comment]
Please help out and contribute what you can to the wiki @qriff
