### ISSUE TITLE
Custom Format Score not updating after download and rename.

### ISSUE THREAD

**Issue by vincentleclerc** [Radarr/Radarr#9911]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

The format tags and scores based on "Release Title" remain the same as when a release was grabbed from an indexer.

### Expected Behavior

The format tags and scores should get reprocessed based on the new "Release Title" after the movie has been downloaded, moved and renamed.

### Steps To Reproduce

1. Have at least one custom format that looks for a keyword in a "Release Title", but doesn't add it by default when renaming. I.e: Multi-Audio, Keyword: "multi"
2. Have at least one other custom format that adds back the keyword from Step#1 in the filename based on post-processing. I.e: Multi-French
3. Download a release that fits the format of Step1  and will get renamed by Step2.
4. Observe the current & expected behaviour.

Here's a few screenshots to illustrate the use-case:

Release from manual search:
![Screenshot 2024-04-09 at 7 00 11 PM](https://github.com/Radarr/Radarr/assets/7295423/3d6a61ca-7957-4fac-b8ae-9176de6bb9cb)

Release after being downloaded & renamed (notice Multi-Audio is still showing up, even though "Multi" isn't part of the filename anymore):
![Screenshot 2024-04-09 at 6 33 40 PM](https://github.com/Radarr/Radarr/assets/7295423/2ad919e8-c61c-4d2a-a16d-e8c90e222314)

Here's a confirmation that radarr should have updated the tags and scores, based on the Test Parsing of the renamed filename (Multi-Audio tag not present):
![Screenshot 2024-04-09 at 6 34 32 PM](https://github.com/Radarr/Radarr/assets/7295423/cdaf7421-64d0-4be0-b13d-9abc3276f03b)

I can actually manually modify the filename, and then hit the "Refresh & Scan" once. The movie becomes "Missing" even though the file is still there.
![Screenshot 2024-04-09 at 6 36 57 PM](https://github.com/Radarr/Radarr/assets/7295423/4c82bb96-eff8-45f8-9957-d325b4d1b0fb)

Clicking "Refresh & Scan" one more time makes the file show back up, with the expected and updated score & tags (I added "test123" to the filename in this case):
![Screenshot 2024-04-09 at 6 38 33 PM](https://github.com/Radarr/Radarr/assets/7295423/550a7462-75bf-4c0d-bb42-542171d77d88)

To me this bug feels like we're simply not automatically triggering a refresh of the scores right after the file has been renamed.. But I don't know much about radarr's internal logic.

NB: This "Multi-Audio" use-case is pretty common and explained quite well over here: https://trash-guides.info/Radarr/radarr-setup-quality-profiles-french-en/

![Screenshot 2024-04-09 at 6 40 09 PM](https://github.com/Radarr/Radarr/assets/7295423/28dd4a9b-7e8a-4c67-8f2d-4f9abe405350)

### Environment

```markdown
- OS: Debian LVM (Proxmox host)
- Radarr: 5.4.3.8677
- Docker Install: No
- Using Reverse Proxy: Yes
- Browser: Chrome
- Database: Sqlite 3.34.1
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

[radarr.txt](https://github.com/Radarr/Radarr/files/14924593/radarr.txt)
[radarr.trace.txt](https://github.com/Radarr/Radarr/files/14924594/radarr.trace.txt)
[radarr.debug.txt](https://github.com/Radarr/Radarr/files/14924595/radarr.debug.txt)

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
```
2024-04-09 22:51:59.8|Trace|CustomFormatCalculationService|Using scene name for release title: The.Zone.of.Interest.2023.MULTi.1080p.WEB.H264-FW
```
Just after the import

- not a bug
- for future issues please follow the wiki you claimed you followed, but did not actually - and provide trace logs as per the 6 steps. Sharing uneeded info, debug, and entire trace logs is noise and not exactly valid for bug reports

Not a bug but known pain point....see the upstream issue for tracking and discussion. https://github.com/Sonarr/Sonarr/issues/5598
