### ISSUE TITLE
Add release date to movies not yet in library

### ISSUE THREAD

**Issue by Ummagummbo** [Radarr/Radarr#9920]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

If a movie isn't in my library yet I can go to the calendar to find the release date if it's available

### Describe the solution you'd like

Add the date for the 'minimum availability' for the movie on the movies page, ideally next to/near the release status if known. The metadata is available already in the calendar but it would be handy to just have it on the movie page in 2 different scenarios, 1) the movie is nearly released and if you go into the movie page it will say the current status and when the day you should expect the system will start hunting for it and 2) a movie has already been released but not yet in the library, you can see how long it has been available for

### Describe alternatives you've considered

Checking the calendar and IMDb and general google searches

### Anything else?

![image](https://github.com/Radarr/Radarr/assets/86087706/130fdd84-4ee3-405f-8583-710d39b14328)

**Comment by bakerboy448** [comment]
- No plans to show every movie on tmdb that is not in radarr in the calendar
- Movies in radarr already have the release date available to view. However the year

**Comment by Ummagummbo** [comment]
This is my fault, I explained poorly but 

> * No plans to show every movie on tmdb that is not in radarr in the calendar
I'm just talking about the movies I have added to radarr that aren't in my library yet

> * Movies in radarr already have the release date available to view. hover the year
I didn't realise this till a chat in discord yesterday, that's basically the date I thought would be useful to be visible, preferably the date that lines up with the profile i.e. release/cinema etc

> * How radarr figures the release date / availability is on the faq
> 
> > it will say the current status and when the day you should expect the system will start hunting for it
> 
> Radarr does not "hunt" for any movie. See the first faq entry to understand how Radarr works

This was poorly worded but I meant more the date that I could expect the movie from, given the minimum release I have chosen etc.
