### ISSUE TITLE
Added choosing between Hardlink, Copy or Move 

### ISSUE THREAD

**Issue by aiemassfiria** [Radarr/Radarr#9939]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Im using cloud storage. So when torrent complete download the file, Radarr will copy or hardlinks the file depends on configuration we set. The problem is when using cloud, if we use the copy function (untick the hardlink), it will take a long time to duplicate the file, its the same also when using hardlink.

### Describe the solution you'd like

Added function Move either than Copy (untick the hardlink) and hardlink (tick hardlink). So user can choose Move/Hardlink/Copy. Drowdown button suggest either than tick checkbox.

### Describe alternatives you've considered

Nothing.

### Anything else?

Nothing.

**Comment by bakerboy448** [comment]
No plans to change.

seeding torrents are copied or hardlinked
Completed torrents or Usenet are copy+delete or moves.

fix your setup accordingly
Please use [Discord](https://radarr.video/discord) for support/questions.
