### ISSUE TITLE
NZB always gets prioritized regardless of indexer priority due to size

### ISSUE THREAD

**Issue by SnippetSpace** [Radarr/Radarr#9940]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Current Behavior

I have set a private tracker to priority 1, and a usenet indexer to priority 25 in prowlarr/radarr. In theory, for the same release the PT should thus be prioritized. However, in reality the usenet release will always be larger in size (I assume due to error correction) and thus preferred if there is a preference for large/maximum sized releases, like for example trash guides recommend.

Example:
10.Cloverfield.Lane.2016.1080p.BluRay.DD-EX.x264-TayTO
- Usenet: 13.7GB
- PT:  13GB

If size preference is > 13.35GB usenet will always be chosen

It might make sense to implement a way to negate this effect for releases with the same name, so that prioritization works correctly.

### Expected Behavior

Respect the indexer priority order.

### Steps To Reproduce

1. Set preferred release size to maximum
2. set PT to priority 1 and usenet to priority 50
3. search for well known release
4. Usenet will always be chosen regardless of priority if the release is available.

### Environment

```markdown
- OS: Linux
- Radarr: 5.4.6.8723
- Docker Install: yes
- Using Reverse Proxy:no
- Browser: edge
- Database: Sqlite 3.44.2
```

### What branch are you running?

Master

### Trace Logs? **Not Optional**

not necessary for this "bug"

### Trace Logs have been provided as applicable. Reports will be closed if the required logs are not provided.

- [X] I have read and followed the steps in the wiki link above and provided the required trace logs - the logs contain `trace` - that are relevant and show this issue.

**Comment by bakerboy448** [comment]
https://wiki.servarr.com/radarr/faq#how-are-possible-downloads-compared

**Comment by SnippetSpace** [comment]
@bakerboy448 i understand protocol (delay profile) can override this but then the reverse is true where usenet never gets prioritized, indexer priority still gets ignored.

**Comment by bakerboy448** [comment]
No bug exists. No plans to change download priority. The faq explains the order. For support understanding the faq visit discord.

For future reference logs are not optional and will result in instant closure.
