### ISSUE TITLE
Adding multiple future releases in the calendar

### ISSUE THREAD

**Issue by undead9786** [Radarr/Radarr#9968]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

Currently there is a physical release entry in the calendar but for a while now older movies are getting 4k bluray releases much later (even decades ie Beverly Hills Cop) but is not being captured in the calendar.

### Describe the solution you'd like

I am requesting that if there are multiple release dates of media that it would be captured in the calendar. So if a movie releases 1080p physical on Jan 1, 2000 and then they do a July 30, 2024 physical 4k release that the calendar also captures that as well.

### Describe alternatives you've considered

Currently I have either been surprised by a release on a tracker or I check https://www.blu-ray.com/ randomly to see if there are any new releases coming out.

### Anything else?

Maybe utilize https://www.blu-ray.com/ as another source of info?

**Comment by bakerboy448** [comment]
No plans to display anything other than the oldest release (digital or physical) or theater.

the calendar has nothing to do with when anything is released on indexers and only when the movie is available
